### ISSUE TITLE
Convert pytorch to onnx, Unsupported: ONNX export of operator adaptive_avg_pool2d

### ISSUE THREAD

**Issue by Sobel-Li** [pytorch/pytorch#67611] opened 2021-11-01 05:48 UTC

**Comment by hwangdeyu** [comment] 2021-11-02 11:19
Could you please provide more details, such as minimum script for us to reproduce the issue?

**Comment by thiagocrepaldi** [comment] 2022-01-03 20:37
It’s been over 2 months, so closing this. Feel free to open another one.

**Closed by thiagocrepaldi** 2022-01-03 20:37 UTC
Labels: module: onnx, triaged, onnx-needs-info

**Comment by listener17** [comment] 2022-03-11 15:58
Hi all: 

I'm getting this error while trying ONNX export on our model. 

`RuntimeError: Unsupported: ONNX export of operator adaptive_avg_pool2d, since output size is not factor of input size. Please feel free to request support or submit a pull request on PyTorch GitHub.`

Is it expected ONNX will support the export of adaptive_avg_pool2d anytime soon?
Is there any workaround?
