### ISSUE TITLE
Cannot find reference ... in '__init__.py' in PyCharm

### ISSUE THREAD

**Issue by YoongiKim** [pytorch/pytorch#15609] opened 2018-12-29 12:14 UTC
Hello. I can't see code inspections or hints in Pycharm.
Such as torch.max, torch.rand, torch.sum, torch.log, torch.utils.data ...

![image](https://user-images.githubusercontent.com/38288705/50538136-ef16b000-0bad-11e9-8900-b41291ea73ed.png)

![image](https://user-images.githubusercontent.com/38288705/50538139-06559d80-0bae-11e9-9c9a-af0a3a637682.png)

I have tested on Ubuntu, Windows by installing conda, pip.

Thank you.

**Comment by soumith** [comment] 2018-12-29 16:03
it still hasn't been solved, but the issue is tracked in https://github.com/pytorch/pytorch/issues/7318

closing this issue as duplicate

**Closed by soumith** 2018-12-29 16:03 UTC

**Comment by soumith** [comment] 2019-02-08 19:27
just fyi, the new v1.0.1 release now has this solved, and it's fixed.

**Comment by gwzhangx** [comment] 2019-10-18 11:24
I still got the same problem with Pycharm 2019.2 and PyTorch 1.3.0

**Comment by LarsHill** [comment] 2019-11-05 17:53
Same here: Pycharm 2019.1.3 and Pytorch 1.2.0

**Comment by cowry5** [comment] 2019-11-14 07:26
Same here: Pycharm 2019.1.4 and Pytorch 1.2.0

**Comment by wangwwno1** [comment] 2019-12-05 06:01
Same here: Pycharm 2019.1.3 and Pytorch 1.2.0

**Comment by wangwwno1** [comment] 2019-12-05 06:49
> just fyi, the new v1.0.1 release now has this solved, and it's fixed.

Look like this issue will pop up again **if one use a remote environment in PyCharm**, because PyCharm somehow forget to sync these *.pyi files to the local remote storage.
Solution: **Manually mapping the local remote storage to the remote path, then sync *.pyi files to local**  would solve these problem.

Plz spread this tip so nobody suffer from these annoying falsify inspection warning again : )

**Comment by nothingeasy** [comment] 2019-12-07 15:05
> > just fyi, the new v1.0.1 release now has this solved, and it's fixed.
> 
> Look like this issue will pop up again **if one use a remote environment in PyCharm**, because PyCharm somehow forget to sync these `*.pyi` files to the local remote storage.
> Solution: **Manually mapping the local remote storage to the remote path, then sync `*.pyi`files to local** would solve these problem.
> 
> Plz spread this tip so nobody suffer from these annoying falsify inspection warning again : )

could you give more details about how to manually mapping the path on pycharm

**Comment by wangwwno1** [comment] 2019-12-07 15:13
> > > just fyi, the new v1.0.1 release now has this solved, and it's fixed.
> > 
> > 
> > Look like this issue will pop up again **if one use a remote environment in PyCharm**, because PyCharm somehow forget to sync these `*.pyi` files to the local remote storage.
> > Solution: **Manually mapping the local remote storage to the remote path, then sync `*.pyi`files to local** would solve these problem.
> > Plz spread this tip so nobody suffer from these annoying falsify inspection warning again : )
> 
> could you give more details about how to manually mapping the path on pycharm

> > > just fyi, the new v1.0.1 release now has this solved, and it's fixed.
> > 
> > 
> > Look like this issue will pop up again **if one use a remote environment in PyCharm**, because PyCharm somehow forget to sync these `*.pyi` files to the local remote storage.
> > Solution: **Manually mapping the local remote storage to the remote path, then sync `*.pyi`files to local** would solve these problem.
> > Plz spread this tip so nobody suffer from these annoying falsify inspection warning again : )
> 
> could you give more details about how to manually mapping the path on pycharm

See [this PyCharm doc](https://www.jetbrains.com/help/pycharm/creating-a-remote-server-configuration.html) for details.
You can locate the path to local storage at the Project View -> External Libraries -> Your Environment -> Remote Libraries, then right click and choose "Copy Path"

**Comment by chessychev** [comment] 2020-01-16 11:27
> > > > just fyi, the new v1.0.1 release now has this solved, and it's fixed.
> > > 
> > > 
> > > Look like this issue will pop up again **if one use a remote environment in PyCharm**, because PyCharm somehow forget to sync these `*.pyi` files to the local remote storage.
> > > Solution: **Manually mapping the local remote storage to the remote path, then sync `*.pyi`files to local** would solve these problem.
> > > Plz spread this tip so nobody suffer from these annoying falsify inspection warning again : )
> > 
> > 
> > could you give more details about how to manually mapping the path on pycharm
> 
> See [this PyCharm doc](https://www.jetbrains.com/help/pycharm/creating-a-remote-server-configuration.html) for details.
> You can locate the path to local storage at the Project View -> External Libraries -> Your Environment -> Remote Libraries, then right click and choose "Copy Path"

i do not have 'remote libraries' under my environment and am not sure which other folder to map.
could you please give another hint as to which folder to map and to where exactly?

i managed to find one that might be related:
/Applications/PyCharm with Anaconda plugin .app/Contents/plugins/python/helpers/typeshed
is that it? even if so, i'm not sure where to map it to, because there server's folder structure is different.

**Comment by alberthe** [comment] 2020-08-12 15:29
Seems not fixed. PyCharm 2020.2 still has the same issue
