### ISSUE TITLE
`win-vs2019-cpu-py3 / build` workflows failing consistently with linker crash

### ISSUE THREAD

**Issue by ZainRizvi** [pytorch/pytorch#91933] opened 2023-01-10 00:18 UTC
> NOTE: Remember to label this issue with "`ci: sev`"

## Current Status
Ongoing

## Error looks like
`win-vs2019-cpu-py3 / build` builds are failing consistently right now with a linker crash.

```
FAILED: bin/torch_python.dll lib/torch_python.lib 
cmd.exe /C "cd . && C:\Jenkins\Miniconda3\Library\bin\cmake.exe -E vs_link_dll --intdir=caffe2\torch\CMakeFiles\torch_python.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10\bin\100190~1.0\x64\mt.exe --manifests  -- C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_python.rsp  /out:bin\torch_python.dll /implib:lib\torch_python.lib /pdb:bin\torch_python.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /INCREMENTAL:NO  /NODEFAULTLIB:LIBCMT.LIB  -WHOLEARCHIVE:C:/actions-runner/_work/pytorch/pytorch/build/lib/onnx.lib  && cd ."
LINK: command "C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_python.rsp /out:bin\torch_python.dll /implib:lib\torch_python.lib /pdb:bin\torch_python.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT.LIB -WHOLEARCHIVE:C:/actions-runner/_work/pytorch/pytorch/build/lib/onnx.lib /MANIFEST /MANIFESTFILE:bin\torch_python.dll.manifest" failed (exit code 0) with the following output:

LINK : fatal error LNK1000: Internal error during CImplib::EmitImportThunk
Access violation
ninja: build stopped: subcommand failed.
```

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

e.g.
- 1/9 12:59pm PST - First known build that failed ([link](https://hud.pytorch.org/pytorch/pytorch/commit/26beb46da4b4c778e8162a67711ebe8fcd1408ae))
- 1/9 Reached out to Windows team for advice, but they're Europe based so response will be slow
- 1/9 4:21pm PST - after confirming the issue repros reliably, disabled the relevant workflows

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
1/9 4:17 pm PST Disabling the win vs2019 cpu build+test workflows for now 

## Prevention/followups
*How do we prevent issues like this in the future?*

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by ZainRizvi** [comment] 2023-01-10 00:23
As an experiment, rerunning an old build from Sunday night which had passed this step. Wanting to see if previous builds continue to succeed or if they fail now

https://github.com/pytorch/pytorch/actions/runs/3870842040/jobs/6615486564

**Comment by huydhn** [comment] 2023-01-10 02:27
I suspect that this is something to do with sccache poisoning or corrupting as my test run https://github.com/pytorch/pytorch/actions/runs/3879203156/jobs/6616170352 completes successfully with the latest commits from trunk https://github.com/pytorch/pytorch/commits/40c2c92859c9f8fe5d920addd200b94f19986cf6.

Retry bot also completes successfully now https://github.com/pytorch/pytorch/actions/runs/3877679506 (1st run failed)

**Comment by malfet** [comment] 2023-01-10 02:40
Hmm, so should we just clean up the cache and re-enable the workflow?

**Comment by Blackhex** [comment] 2023-01-10 15:30
The issue still seems to be prevailing as I tried to create testing PR from the latest master commit enabling the build step and it failed [https://github.com/pytorch/pytorch/actions/runs/3883808122/jobs/6625638192.](https://github.com/pytorch/pytorch/actions/runs/3883808122/jobs/6625638192.) I'll try to collect crash data with /LINKREPRO enabled ([https://learn.microsoft.com/en-us/cpp/build/reference/linkrepro?view=msvc-170](https://learn.microsoft.com/en-us/cpp/build/reference/linkrepro?view=msvc-170)) and then we can submit the issue to the MSVC ticketing system.

**Comment by huydhn** [comment] 2023-01-10 20:23
> Hmm, so should we just clean up the cache and re-enable the workflow?

Unfortunately, this turns out to be a wrong lead.  I disabled the cache top of the failed run that @Blackhex mentioned and it still failed.  So it must be something else.

**Comment by malfet** [comment] 2023-01-10 21:14
As nightly win cpu builds pass, I assume it has something to do with S3 cache corruption. Let me drain the cache and see whether it will help anything.

**Comment by huydhn** [comment] 2023-01-11 04:33
I'm a bit closer to root cause the issue.  The linker command fails when `/MANIFESTFILE:bin\torch_python.dll.manifest` is set

```
C:\PROGRA~2\MICROS~2\2019\BUILDT~1\VC\Tools\MSVC\1428~1.293\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\torch_python.rsp /out:bin\torch_python.dll /implib:lib\torch_python.lib /pdb:bin\torch_python.pdb /dll /version:0.0 /machine:x64 /ignore:4049 /ignore:4217 /ignore:4099 /INCREMENTAL:NO /NODEFAULTLIB:LIBCMT.LIB -WHOLEARCHIVE:C:/actions-runner/_work/pytorch/pytorch/build/lib/onnx.lib /MANIFEST /MANIFESTFILE:bin\torch_python.dll.manifest

LINK : fatal error LNK1000: Internal error during CImplib::EmitImportThunk
```

The weird thing is that removing this flag still ensures the same file is created because `/MANIFEST` flag is still there AND the linker works without any issue.  I couldn't explain it, but quickly draft a bandaid fix for that here https://github.com/pytorch/pytorch/pull/91988 in case we need to re-enable Windows CPU jobs while waiting for further investigation.

**Comment by Blackhex** [comment] 2023-01-11 19:32
So far it seems that the reproduction of the issue is correlated to not using `/LINKREPRO` option. I haven't reproduce it with the `/LINKREPRO` enabled. 

@huydhn Is this what you've ment by

> Looking a bit closer into the failures, it turns out to be something else related to`/LINKREPRO`. Re-running one more time without `/LINKREPRO` and without sccache now to confirm.

?

Even if it cannot be reproduced with th `/LINKREPRO`, the data produced might contain some clue what is going on...

**Comment by huydhn** [comment] 2023-01-12 01:44
As the issue has been mitigated.  Windows CPU build and test are back (https://github.com/pytorch/pytorch/pull/91988).  I will close this one now so that it won't be a sev anymore.  But please update us with the outcome of the investigation if anything new is found

**Closed by huydhn** 2023-01-12 01:44 UTC
Labels: module: windows, ci: sev

**Comment by Blackhex** [comment] 2023-01-12 15:58
@huydhn The more I think about it, the more I suspect it was a caching issue after all. You've changed, the linker command line by removing `/MANIFESTFILE` - the issue disappeared, I've changed the linker command line with `/LINKREPRO` the issue disappeared. Coincidence?

**Comment by ZainRizvi** [comment] 2023-01-12 17:27
Hmm...in that case we could validate the theory by adding a random no op parameter (like a new D flag) and see if that fixes the issue as well

**Comment by huydhn** [comment] 2023-01-12 18:15
Indeed, I have another data point to support the theory, the linker command also works if I keep the `/MANIFESTFILE` flag but choose a different name.  However, it shouldn't a problem with the cache on S3 because I tried the build with sccache locally but without setting an S3 bucket, and it still failed AFAICT (https://github.com/pytorch/pytorch/pull/91969)

**Comment by Blackhex** [comment] 2023-01-12 18:48
It can be issue with caching on Ninja level when the same runner is used for different builds without cleanup. I don't know if this is the case, just trowing the theories.
