### ISSUE TITLE
Bug of LongTensor/IntTensor ?

### ISSUE THREAD

**Issue by Naruto-Sasuke** [pytorch/pytorch#23369] opened 2019-07-25 08:07 UTC
## 🐛 Bug
When longtensor/intTensor multiply a float number, it ouptuts a tensor full of 0.

## To Reproduce
```python
import torch
a = (torch.rand(3,4)*10).long()
print(a)
print(a*0.9)
```

```bash
tensor([[8, 5, 3, 4],
        [1, 3, 6, 7],
        [8, 5, 8, 8]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
```
## Expected behavior
```bash
tensor([[8, 5, 3, 4],
        [1, 3, 6, 7],
        [8, 5, 8, 8]])
tensor([[7, 4, 2, 3],
        [0, 2, 5, 6],
        [7, 4, 7, 7]])
```

## Environment
Pytorch1.0 stable

**Comment by Chillee** [comment] 2019-07-25 23:12
I guess, to be clear,  the issue isn't that it outputs a tensor full of 0. The issue here is that when you do `a*0.9`, the `0.9` needs to be cast to a long, and it gets cast down to `0`. For example, if you do `1.9`, then it becomes `a*1`. I don't know enough about the type promotion to say whether this is intended, but it makes sense to me.

**Comment by izdeby** [comment] 2019-07-26 22:29
fyi, @nairbv

**Comment by nairbv** [comment] 2019-07-29 01:05
This will be (mostly) addressed by https://github.com/pytorch/pytorch/pull/22273. 

It's not exactly what you want: with the change in #22273 you'll get a float tensor as a result, but you'll be able to cast the floating point result back to long to get your expected result. 

As @Chillee mentioned, what you're seeing is that the 0.9 is truncated to zero when being cast to long to performing the operation.

**Comment by Naruto-Sasuke** [comment] 2019-07-30 13:04
@nairbv I agree with you, 

> with the change in #22273 you'll get a float tensor as a result, but you'll be able to cast the floating point result back to long to get your expected result.

makes sense to me.

**Comment by nairbv** [comment] 2019-12-16 17:00
fixed by type promotion changes:

https://github.com/pytorch/pytorch/pull/22273

**Closed by nairbv** 2019-12-16 17:00 UTC
Labels: module: operators, topic: type promotion, triaged
