### ISSUE TITLE
"Bus error" on /dev/shm OOM; hard/impossible to fix

### ISSUE THREAD

**Issue by adamlerer** [pytorch/pytorch#5247] opened 2018-02-14 21:56 UTC
@colesbury helped me diagnose this; posting an issue here to document.

Running out of space on /dev/shm leads to a "Bus error" that dumps core inside of `THTensor_(rawCopy)`, with no stack trace, error message, etc. It's kind of similar to a regular OOM except that you can't even look at `top` to see that you're running out of memory, or `/var/log/messages` to see that you were killed by OOM, etc.

I'm not sure there's any way to fix this. The behavior is very strange, because the OS doesn't seem to provide any error when we run out of space. The TH `_map_alloc` function calls `ftruncate` which returns successfully even if there's not enough space. And then `mmap`ing the file also succeeds, and gives a non-null pointer. It's only when I try to write to it (inside the subsequent copy) that I get a bus error.

Here's an example to repro:

```
import torch

tensors = []
for i in range(1000):
    print(i)
    a = torch.Tensor(1000000000)
    a.share_memory_()
    tensors.append(a)
```

**Comment by ezyang** [comment] 2018-02-15 06:41
https://bugzilla.redhat.com/show_bug.cgi?id=607738 claims that a `write()` will fail with an error code we can detect. Don't know if we actually want to add a test for it this way.

Previous instance of this: #2244

**Comment by apaszke** [comment] 2018-02-15 10:25
[We have always been doing the `write` check](https://github.com/pytorch/pytorch/blob/master/aten/src/TH/THAllocator.c#L324-L333). The problem is that touching only the first element will not catch all errors, since the OS is allocating the pages lazily and will send the bus error only once it runs out of them.

**Comment by ngimel** [comment] 2020-08-24 16:21
Closing, please reopen if needed.

**Closed by ngimel** 2020-08-24 16:21 UTC
