### ISSUE TITLE
Very Slow Moving Tensor to CUDA device (CUDA 10.1 with PyTorch 1.3)

### ISSUE THREAD

**Issue by dhpollack** [pytorch/pytorch#27807] opened 2019-10-12 08:55 UTC
## 🐛 Bug

Moving tensors to cuda devices is super slow when using pytorch 1.3 and CUDA 10.1.  The issue does not occur when using pytorch 1.3 and CUDA 10.0.  

## To Reproduce

```
# takes seconds with CUDA 10.0 and minutes with CUDA 10.1
torch.zeros(25000, 300, device=torch.device("cuda"))
```
## Expected behavior

should be almost instance

## Environment

 - PyTorch Version (e.g., 1.0): PyTorch 1.3
 - OS (e.g., Linux): Linux (Arch Linux)
 - How you installed PyTorch (`conda`, `pip`, source):  conda
 - Python version:  3.7
 - CUDA/cuDNN version:  10.1 (does not happen with 10.0)

## Additional context

I am not the only one having this problem. See below:

https://discuss.pytorch.org/t/model-cuda-is-very-slow/57993

https://discuss.pytorch.org/t/cuda-problem-i-cant-transfer-objects-to-the-gpu/57988

Below is my output from `nvidia-smi`, I am running this on a laptop with a GTX 1050.

```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 105...  Off  | 00000000:01:00.0 Off |                  N/A |
| N/A   38C    P8    N/A /  N/A |    439MiB /  4042MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     41760      C   python                                       429MiB |
+-----------------------------------------------------------------------------+
```

cc @ezyang @gchanan @zou3519

**Comment by soumith** [comment] 2019-10-12 11:17
cc: @csarofeen @ptrblck similar / same as the other issue I tagged ptrblck in. can you lend a hand to get to the bottom of this

**Comment by soumith** [comment] 2019-10-12 11:51
I tried to reproduce this in a Colab notebook, with a `!pip install -U torch` and it seems the startup time there is really fast.

So it might be one of these:
- something correlated wrt GPU model
- something correlated to driver version
- something specific to conda / 10.1 interaction

**Comment by soumith** [comment] 2019-10-12 11:52
@dhpollack can you confirm or deny that `pip install -U torch` does not produce the slow-down?

**Comment by soumith** [comment] 2019-10-12 12:04
ok I got a repro. It is specific to conda / 10.1 interaction, i.e. 10.1.243 vs 10.1.168.
I am going to regen the conda binaries with `10.1.243`, it'll take me a few hours to get there.

**Comment by soumith** [comment] 2019-10-12 13:11
kicked off builds for fixing the binaries here: https://circleci.com/workflow-run/f3094949-d5c4-47e8-a42c-4983efc893d4

**Comment by ptrblck** [comment] 2019-10-12 13:38
@soumith thanks for isolating this issue! I'll try to dig into it and see, what's going on in `10.1.243`.

**Comment by dhpollack** [comment] 2019-10-12 16:57
> @dhpollack can you confirm or deny that `pip install -U torch` does not produce the slow-down?

there is no slowdown when installing from pip

**Comment by soumith** [comment] 2019-10-12 18:10
ok the new binaries didn't fix the issue, but I nailed it on the head.
I'm re-spinning binaries again that will fix the issue 100%.

**Comment by soumith** [comment] 2019-10-12 21:44
This issue is now fixed with newly updated binaries.
Uninstalling and reinstalling PyTorch from Anaconda will fix it.

**Closed by soumith** 2019-10-12 21:44 UTC
Labels: high priority, module: binaries

**Comment by ghltshubh** [comment] 2019-12-08 02:09
What's up with cudaMalloc? 

```
      API calls:   34.94%  61.7341s       417  148.04ms  23.025us  11.5520s  cudaMalloc
                   30.06%  53.1117s       102  520.70ms  5.8550us  9.95000s  cudaStreamCreateWithFlags
                   14.17%  25.0391s      5938  4.2168ms  8.5790us  466.50ms  cudaMemcpyAsync
                   10.94%  19.3274s        66  292.84ms  1.4710us  3.02502s  cudaFree
```

**Comment by ptrblck** [comment] 2019-12-08 06:15
`cudaMalloc` allocates memory and PyTorch caches it afterwards for faster reusage.
Do you see any new `cudaMalloc` calls after the fix in the PR?

**Comment by tayo** [comment] 2020-01-13 18:37
I am seeing behavior similar to this.  This is in a new python3 venv with packages installed using pip on 2020 Jan-13, so binaries should be fresh.

My program spends upward of 60 minutes (and counting) for my model:

> device = torch.device("cuda", 0)
> my_model = my_model.to(device)

@soumith @ptrblck -- Is it possible there is another system interaction which triggers this?


My environment:
torch==1.3.1
NVIDIA-SMI 418.116.00   Driver Version: 418.116.00   CUDA Version: 10.1 


pip freeze:
future==0.18.2
graphviz==0.13.2
joblib==0.14.1
numpy==1.18.1
onnx==1.6.0
pkg-resources==0.0.0
protobuf==3.11.2
pydot==1.4.1
pyparsing==2.4.6
scikit-learn==0.22.1
scipy==1.4.1
six==1.13.0
torch==1.3.1
torchviz==0.0.1
typing-extensions==3.7.4.1

**Comment by soumith** [comment] 2020-01-13 20:10
@tayo what GPU? also please open a new issue. the original problem wrt this issue was resolved.

**Comment by tayo** [comment] 2020-01-13 23:01
@soumith 

16 x Tesla V100-SXM3-32GB (dgx2).

Okay, I will open a new issue.  Regards.

**Comment by jediofgever** [comment] 2020-03-31 07:38
what about pip users?

**Comment by rolambert** [comment] 2020-07-15 22:40
Hi I have been running into slow CUDA runtime, I'm thinking is vscode not torch tho.

**Comment by raqueldias** [comment] 2021-01-25 20:22
I found the same problem now: Variable().cuda() takes 30 seconds in a 4xA100 server with AMD EPYC 7352 24-Core Processor, while it takes 2 seconds in a DGX Station (4xV100 with Intel Xeon 20-Core Processor E5-2698). 
Both servers have the same amount of RAM and same software installed:
pytorch 1.7.1 (tried 1.8.0 as well)
Driver Version: 440.82 (tried 450.102.04 as well)       
CUDA Version: 10.2 (tried 11.0 as well)

**Comment by ptrblck** [comment] 2021-01-25 20:44
@raqueldias The slow startup might be caused by JIT compilation in case you were using binaries with CUDA<11 for the server with A100s.
Note that your local CUDA installation will not be used, if you installed the conda binaries or pip wheels and you can verify the shipped CUDA runtime via `print(torch.version.cuda)`.

**Comment by raqueldias** [comment] 2021-01-25 23:12
Thanks! I tested a locally compiled from source version of pytorch 1.8.0 as well, but didn't seem solve the problem.
When I run this:
```
print("Pytorch version is:", torch.__version__)
print("Cuda version is:", torch.version.cuda)
```
The outputs look like this:
```
Pytorch version is: 1.8.0a0+1f40f2a
Cuda version is: 11.0
```

**Comment by raqueldias** [comment] 2021-01-26 23:19
Turned out the problem was in the numactl configuration for AMD CPU systems. Adding these numactl options fixed my problem:
```
numactl --physcpubind=0-23 -l <my model training script for GPU0>
numactl --physcpubind=48-71 -l <my model training script for GPU1>
numactl --physcpubind=24-47 -l  <my model training script for GPU2> 
numactl --physcpubind=72-95 -l <my model training script for GPU3>
```
I hope that helps anyone having the same issue.

**Comment by Davidrjx** [comment] 2022-08-30 12:17
> Turned out the problem was in the numactl configuration for AMD CPU systems. Adding these numactl options fixed my problem (example in a CPU with 96 threads):
> 
> ```
> numactl --physcpubind=0-23 -l <my model training script for GPU0>
> numactl --physcpubind=48-71 -l <my model training script for GPU1>
> numactl --physcpubind=24-47 -l  <my model training script for GPU2> 
> numactl --physcpubind=72-95 -l <my model training script for GPU3>
> ```
> 
> I hope that helps anyone having the same issue.

@raqueldias how did you find that?

**Comment by raqueldias** [comment] 2023-01-30 17:05
> > Turned out the problem was in the numactl configuration for AMD CPU systems. Adding these numactl options fixed my problem (example in a CPU with 96 threads):
> > ```
> > numactl --physcpubind=0-23 -l <my model training script for GPU0>
> > numactl --physcpubind=48-71 -l <my model training script for GPU1>
> > numactl --physcpubind=24-47 -l  <my model training script for GPU2> 
> > numactl --physcpubind=72-95 -l <my model training script for GPU3>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I hope that helps anyone having the same issue.
> 
> @raqueldias how did you find that?

It was actually the HPC support team from the supercomputer that I use at work who helped me providing this solution.
