### ISSUE TITLE
torchaudio error: OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xvdp** [pytorch/pytorch#91186] opened 2022-12-20 18:58 UTC
### 🐛 Describe the bug

torchaudio fails to open on a fresh conda installation, using cuda 11.6 and ubuntu 18.

```bash
conda create -n abj python=3.9 numpy  matplotlib psutil opencv pandas h5py jupyter networkx accimage
conda activate abj
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
conda install -c fvcore -c iopath -c conda-forge fvcore iopath
conda install -c bottler nvidiacub
conda install pytorch3d -c pytorch3d
python
```
```python
import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torch/_ops.py", line 256, in load_library
    ctypes.CDLL(path)
  File "/home/z/miniconda3/envs/abj/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
```
Adding `print(path)` to line 255 torch/_ops.py, ie just before `ctypes.CDLL(path)` 
prints  /home/z/miniconda3/envs/abj/lib/python3.9/site-packages/torchaudio/lib/libtorchaudio.so, which exists, and isnt the path that mentioned in the error. 

running 
```~/miniconda3/envs/abj$ find . -name libtorch_cuda_cpp.so```
returns a blank.

I noticed that this error is also mentioned in https://github.com/NVIDIA/NeMo/issues/4406
and seems similar to    https://github.com/pytorch/pytorch/issues/85085
but im not working with pytorch-nightly and im not on the latest cuda. 

Is this the correct place to log this bug or should it be in torchaudio, or is this something falling thru the cracks.
I posted it as well on torchaudio  https://github.com/pytorch/audio/issues/2932

### Versions

Collecting environment information...
PyTorch version: 1.12.1.post201
Is debug build: False
CUDA used to build PyTorch: 11.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 15:55:03)  [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA TITAN RTX
Nvidia driver version: 510.39.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.0
[pip3] pytorch3d==0.7.2
[pip3] torch==1.12.1.post201
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.14.0a0+2ba5a5d
[conda] cudatoolkit               11.6.0               habf752d_9    nvidia
[conda] magma                     2.5.4                hc72dce7_4    conda-forge
[conda] mkl                       2022.1.0           hc2b9512_224  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch                   1.12.1          cuda112py39hb0b7ed5_201    conda-forge
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorch3d                 0.7.2           py39_cu116_pyt1121    pytorch3d
[conda] torchaudio                0.12.1               py39_cu116    pytorch
[conda] torchvision               0.14.0          cuda112py39h1a1de93_0    conda-forge

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment] 2022-12-20 19:51
Sounds like a duplicate of https://github.com/pytorch/audio/issues/2932: You've end up with  pytorch installed conda-forge (built against cuda 11.2 I guess), but `torchaudio` from `pytorch` channel, which are not compatible with each other.

I guess is due to `pytorch3d` dependency. Please consider building pytorch3d from source (or ask the maintainer to build against pytorch rather than conda-forge channel)

If running `conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia` in fresh environment results in non-working `torchaudio` please do not hesitate to reopen this one, or file another issue.

**Closed by malfet** 2022-12-20 19:51 UTC
Labels: oncall: binaries, module: third_party

**Comment by xvdp** [comment] 2022-12-21 02:57
It still doesnt work. There seems to be something odd in the conda packaging.

I wiped the entire set of stored packages miniconda3/pkgs then installed according to instructions https://pytorch.org/get-started/locally/ 
```bash
conda create -n abk python=3.9 numpy matplotlib psutil jupyter
conda activate abk
conda install pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch -c nvidia
```
The pytorch installation line downloads the following packages- < see download list below >. Notice that `torchvision` and `pytorch` are downloaded from conda-forge in spite of the conda install pointing to -c pytorch.

Also, it isn't just torchaudio that fails but also torchvision. < see errors below >

These errors also occur if I try to install previous version with cuda 11.6  as spec'd in https://pytorch.org/get-started/previous-versions/
`conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.6 -c pytorch -c conda-forge`

But the build seems to work if installed with pip instructions
` pip install torch==1.12.1+cu116 torchvision==0.13.1+cu116 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu116` 

So my guess is that something is off in the conda builds. I have been using this machine, and prior versions of torch, torchvision and torchaudio for a couple years, never a prolbem with conda installs. 

So, @malfet while  I should update my drivers to use latest cuda, the bug in the build is still there, and has nothing to do with pytorch3d. 


## Errors
```python
>>> import torch
>>> torch.cuda.is_available()
True
>>> torch.__version__
'1.12.1.post201'
>>> import torchvision
/home/z/miniconda3/envs/abk/lib/python3.9/site-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: /home/z/miniconda3/envs/abk/lib/python3.9/site-packages/torchvision/image.so: undefined symbol: _ZN2at4_ops19empty_memory_format4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEENS6_INS2_12MemoryFormatEEE
  warn(f"Failed to load image Python extension: {e}")
>>> import torchaudio
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/z/miniconda3/envs/abk/lib/python3.9/site-packages/torchaudio/__init__.py", line 1, in <module>
    from torchaudio import (  # noqa: F401
  File "/home/z/miniconda3/envs/abk/lib/python3.9/site-packages/torchaudio/_extension.py", line 103, in <module>
    _init_extension()
  File "/home/z/miniconda3/envs/abk/lib/python3.9/site-packages/torchaudio/_extension.py", line 88, in _init_extension
    _load_lib("libtorchaudio")
  File "/home/z/miniconda3/envs/abk/lib/python3.9/site-packages/torchaudio/_extension.py", line 51, in _load_lib
    torch.ops.load_library(path)
  File "/home/z/miniconda3/envs/abk/lib/python3.9/site-packages/torch/_ops.py", line 255, in load_library
    ctypes.CDLL(path)
  File "/home/z/miniconda3/envs/abk/lib/python3.9/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libtorch_cuda_cpp.so: cannot open shared object file: No such file or directory
>>> 
```

                      


    package                    |            build
    ---------------------------|-----------------
    brotlipy-0.7.0             |py39hb9d737c_1005         342 KB  conda-forge
    charset-normalizer-2.1.1   |     pyhd8ed1ab_0          36 KB  conda-forge
    cryptography-38.0.4        |   py39h3ccb8fc_0         1.3 MB  conda-forge
    cuda-11.6.1                |                0           1 KB  nvidia
    cuda-cccl-11.6.55          |       hf6102b2_0         1.2 MB  nvidia
    cuda-command-line-tools-11.6.2|                0           1 KB  nvidia
    cuda-compiler-11.6.2       |                0           1 KB  nvidia
    cuda-cudart-11.6.55        |       he381448_0         194 KB  nvidia
    cuda-cudart-dev-11.6.55    |       h42ad0f4_0         1.0 MB  nvidia
    cuda-cuobjdump-11.6.124    |       h2eeebcb_0         134 KB  nvidia
    cuda-cupti-11.6.124        |       h86345e5_0        22.1 MB  nvidia
    cuda-cuxxfilt-11.6.124     |       hecbf4f6_0         283 KB  nvidia
    cuda-driver-dev-11.6.55    |                0          16 KB  nvidia
    cuda-gdb-12.0.90           |                0         5.3 MB  nvidia
    cuda-libraries-11.6.1      |                0           1 KB  nvidia
    cuda-libraries-dev-11.6.1  |                0           2 KB  nvidia
    cuda-memcheck-11.8.86      |                0         168 KB  nvidia
    cuda-nsight-12.0.78        |                0       113.6 MB  nvidia
    cuda-nsight-compute-12.0.0 |                0           1 KB  nvidia
    cuda-nvcc-11.6.124         |       hbba6d2d_0        42.2 MB  nvidia
    cuda-nvdisasm-12.0.76      |                0        47.9 MB  nvidia
    cuda-nvml-dev-11.6.55      |       haa9ef22_0          65 KB  nvidia
    cuda-nvprof-12.0.90        |                0         4.3 MB  nvidia
    cuda-nvprune-11.6.124      |       he22ec0a_0          65 KB  nvidia
    cuda-nvrtc-11.6.124        |       h020bade_0        17.1 MB  nvidia
    cuda-nvrtc-dev-11.6.124    |       h249d397_0        16.8 MB  nvidia
    cuda-nvtx-11.6.124         |       h0630a44_0          58 KB  nvidia
    cuda-nvvp-12.0.90          |                0       114.3 MB  nvidia
    cuda-runtime-11.6.1        |                0           1 KB  nvidia
    cuda-samples-11.6.101      |       h8efea70_0           5 KB  nvidia
    cuda-sanitizer-api-12.0.90 |                0        16.6 MB  nvidia
    cuda-toolkit-11.6.1        |                0           1 KB  nvidia
    cuda-tools-11.6.1          |                0           1 KB  nvidia
    cuda-visual-tools-11.6.1   |                0           1 KB  nvidia
    cudatoolkit-11.6.0         |       habf752d_9       821.4 MB  nvidia
    cudnn-8.4.1.50             |       hed8a83a_0       618.4 MB  conda-forge
    gds-tools-1.5.0.59         |                0        40.9 MB  nvidia
    intel-openmp-2022.1.0      |    h9e868ea_3769         4.5 MB
    libcublas-11.9.2.110       |       h5e84587_0       300.8 MB  nvidia
    libcublas-dev-11.9.2.110   |       h5c901ab_0       310.9 MB  nvidia
    libcufft-10.7.1.112        |       hf425ae0_0        93.6 MB  nvidia
    libcufft-dev-10.7.1.112    |       ha5ce4c0_0       197.2 MB  nvidia
    libcufile-1.5.0.59         |                0         754 KB  nvidia
    libcufile-dev-1.5.0.59     |                0          13 KB  nvidia
    libcurand-10.3.1.50        |                0        51.7 MB  nvidia
    libcurand-dev-10.3.1.50    |                0         449 KB  nvidia
    libcusolver-11.3.4.124     |       h33c3c4e_0        87.0 MB  nvidia
    libcusparse-11.7.2.124     |       h7538f96_0       160.9 MB  nvidia
    libcusparse-dev-11.7.2.124 |       hbbe9722_0       328.9 MB  nvidia
    libnpp-11.6.3.124          |       hd2722f0_0       118.4 MB  nvidia
    libnpp-dev-11.6.3.124      |       h3c42840_0       115.6 MB  nvidia
    libnvjpeg-11.6.2.124       |       hd473ad6_0         2.3 MB  nvidia
    libnvjpeg-dev-11.6.2.124   |       hb5906b9_0         2.0 MB  nvidia
    libprotobuf-3.21.12        |       h3eb15da_0         2.1 MB  conda-forge
    magma-2.5.4                |       hc72dce7_4       106.8 MB  conda-forge
    mkl-2022.1.0               |     hc2b9512_224       129.7 MB
    nccl-2.14.3.1              |       h0800d71_0       145.2 MB  conda-forge
    ninja-1.11.0               |       h924138e_0         2.8 MB  conda-forge
    nsight-compute-2022.4.0.15 |                0       764.0 MB  nvidia
    pyopenssl-22.1.0           |     pyhd8ed1ab_0         122 KB  conda-forge
    pysocks-1.7.1              |     pyha2e5f31_6          19 KB  conda-forge
    pytorch-1.12.1             |cuda112py39hb0b7ed5_201       490.1 MB  conda-forge
    pytorch-cuda-11.6          |       h867d48c_1           3 KB  pytorch
    pytorch-mutex-1.0          |             cuda           3 KB  pytorch
    requests-2.28.1            |     pyhd8ed1ab_1          53 KB  conda-forge
    sleef-3.5.1                |       h9b69904_2         1.5 MB  conda-forge
    torchaudio-0.12.1          |       py39_cu116         6.1 MB  pytorch
    torchvision-0.14.0         |cuda112py39h1a1de93_0         7.1 MB  conda-forge
    urllib3-1.26.13            |     pyhd8ed1ab_0         108 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        5.19 GB

**Comment by malfet** [comment] 2022-12-21 15:27
@xvdp I assume it happens because `coda-forge` now vendors `pytorch` and is a preferred channel to a pytorch one. Can you please explicitly prefixing packages with the channel name, i.e.:
```
conda install pytorch:pytorch==1.12.1 pytorch:torchvision==0.13.1 pytorch:torchaudio==0.12.1 nvidia:cudatoolkit=11.6 -c pytorch -c nvidia -c conda-forge
```

**Comment by xvdp** [comment] 2022-12-21 17:26
Is it possible that you have the correct pytorch in your `miniconda3/pkgs` folder?
If I look at pytorch channel I see the one that looks like it should be installed - My machine has cuda11.6 and cudnn8.3.2
[linux-64/pytorch-1.12.1-py3.9_cuda11.6_cudnn8.3.2_0.tar.bz2](https://anaconda.org/pytorch/pytorch/1.12.1/download/linux-64/pytorch-1.12.1-py3.9_cuda11.6_cudnn8.3.2_0.tar.bz2)

While always deleting the packages  pytorch*, torchivsion* and torchaudio* from `miniconda/pkgs/`  
Specifiying channel as you suggest did not work it still downloads 
` pytorch-1.12.1             |cuda112py39hb0b7ed5_201       490.1 MB  conda-forge`

## Solution 
add pytorch to top channel priority and setting priority to strict.
```
conda config --add channels pytorch
conda config --set channel_priority strict
```

So this is in fact solved, but it'd be good to add a note to the pytorch installation instructions to prevent others wasting the time i just did.
thanks
