### ISSUE TITLE
[BUG] Some forward AD operators are not implemented in Python 3.11 wheel but they are available for Python 3.10

### ISSUE THREAD

**Issue by XuehaiPan** [pytorch/pytorch#91100] opened 2022-12-19 13:24 UTC
Hi, I am trying to build a pre-built Python 3.11 wheel for [metaopt/torchopt](https://github.com/metaopt/torchopt), which heavily depends on `functorch`. However, the CI tests report "operator not implemented" errors for Python 3.11 while everything goes fine for Python 3.10. (https://github.com/metaopt/torchopt/actions/runs/3731244616/jobs/6329250038)

PS: I report this issue in [pytorch/functorch](https://github.com/pytorch/functorch) repo here because the forward AD is usually called by `functorch` users. If the [pytorch/pytorch](https://github.com/pytorch/pytorch) repo is the right place to report this. Maybe transfer this issue there.

A minimal snippet to reproduce:

```python
import functorch
import torch

functorch.hessian(torch.nn.Softmax(dim=-1))(torch.randn(32, 10))
functorch.hessian(torch.nn.LogSoftmax(dim=-1))(torch.randn(32, 10))
```

The `hessian` function is a combination of `jacfwd` and `jacrev`, while the `jacfwd` function uses the forward AD APIs.

For Python 3.10:

```bash
python3.10 -m venv py310
source py310/bin/activate
pip3 install 'torch>=1.13'
python3 -c 'import functorch, torch; functorch.hessian(torch.nn.Softmax(dim=-1))(torch.randn(4, 2))'
```

no error will araise.

For Python 3.11:

```bash
python3.11 -m venv py311
source py311/bin/activate
pip3 install 'torch>=1.13'
python3 -c 'import functorch, torch; functorch.hessian(torch.nn.Softmax(dim=-1))(torch.randn(4, 2))'
```

it reports:

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/eager_transforms.py", line 996, in wrapper_fn
    results = vmap(push_jvp, randomness=randomness)(basis)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/vmap.py", line 362, in wrapped
    return _flat_vmap(
           ^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/vmap.py", line 489, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/eager_transforms.py", line 989, in push_jvp
    output = _jvp_with_argnums(func, args, basis, argnums=argnums, has_aux=has_aux)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/eager_transforms.py", line 837, in _jvp_with_argnums
    result_duals = func(*duals)
                   ^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/eager_transforms.py", line 474, in wrapper_fn
    results = vmap(vjp_fn)(basis)
              ^^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/vmap.py", line 362, in wrapped
    return _flat_vmap(
           ^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/vmap.py", line 489, in _flat_vmap
    batched_outputs = func(*batched_inputs, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/eager_transforms.py", line 323, in wrapper
    result = _autograd_grad(flat_primals_out, flat_diff_primals, flat_cotangents,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/functorch/_src/eager_transforms.py", line 113, in _autograd_grad
    grad_inputs = torch.autograd.grad(diff_outputs, inputs, grad_outputs,
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/PanXuehai/PycharmProjects/torchopt/py311/lib/python3.11/site-packages/torch/autograd/__init__.py", line 300, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NotImplementedError: Trying to use forward AD with _softmax_backward_data that does not support it because it has not been implemented yet.
Please file an issue to PyTorch at https://github.com/pytorch/pytorch/issues/new?template=feature-request.yml so that we can prioritize its implementation.
Note that forward AD support for some operators require PyTorch to be built with TorchScript and for JIT to be enabled. If the environment var PYTORCH_JIT=0 is set or if the library is not built with TorchScript, some operators may no longer be used with forward AD.
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @Chillee @samdow @soumith @SherlockNoMad @ngimel

**Comment by zou3519** [comment] 2022-12-19 14:58
Unfortunately this is expected. The problem is forward-mode AD uses TorchScript decompositions to gain coverage for certain operations, but TorchScript doesn't work with Python 3.11.

cc @soulitzer for forward-mode AD -- if PyTorch does release support for Python 3.11 and TorchScript doesn't work for Python 3.11, then it's important that forward-mode AD maintains its level of coverage

**Comment by zou3519** [comment] 2023-01-05 18:42
I can't find the other issue I wrote this in, so here is a quick summary on the state of things for folks who are interested.

functorch transforms ([vmap](https://github.com/pytorch/pytorch/blob/f11dc26ed5aad4574fab54685086c5adff724b2d/torch/_functorch/vmap.py#L205-L233), jvp - which wraps PyTorch [forward-mode AD](https://github.com/pytorch/pytorch/blob/master/torch/_decomp/decompositions_for_jvp.py)) use Python decompositions of operations to get coverage for operations. These Python decompositions must be called from C++. They get called from C++ by going through TorchScript.

Unfortunately we do not have good TorchScript support for 3.11. To make functorch more portable, we should excise the TorchScript dependencies. There are a number of known ways to call Python code from C++:
- straight up use the Python dispatcher. Meta tensors get coverage from Python implementations this way. Some care is needed to register a decomposition for jvp because autograd is logically one DispatchKey and consists of both reverse-mode AD and forward-mode AD.
- write some new mechanism of calling into Python from C++. We do this in many places in PyTorch (e.g. autograd.Function, torch_dispatch) so it shouldn't be too bad.

**Comment by zou3519** [comment] 2023-03-08 18:36
Was fixed by https://github.com/pytorch/pytorch/pull/91805 and https://github.com/pytorch/pytorch/pull/91825

**Closed by zou3519** 2023-03-08 18:36 UTC
Labels: module: autograd, triaged, module: forward ad, module: functorch, module: decompositions
