### ISSUE TITLE
`aminmax()` with an empty 1D tensor still gets error even if setting `dim=0` to it

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130185] opened 2024-07-05 23:17 UTC
### 🐛 Describe the bug

[aminmax()](https://pytorch.org/docs/stable/generated/torch.aminmax.html) with an empty 1D tensor gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.aminmax(input=my_tensor) # Error
```

> RuntimeError: aminmax(): cannot compute aminmax over an empty dimension as the operation has no identity.

So, I set `dim=0` to `aminmax()` following the error message above but it still gets other error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.aminmax(input=my_tensor, dim=0) # Error
```

> IndexError: aminmax: Expected reduction dim 0 to have non-zero size.

In addition, `aminmax()` with an empty 2D or 3D  tensor also gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.aminmax(input=my_tensor) # Error

my_tensor = torch.tensor([[[]]])

torch.aminmax(input=my_tensor) # Error
```

> RuntimeError: aminmax(): cannot compute aminmax over an empty dimension as the operation has no identity.

But setting `dim=0` to `aminmax()` following the error message above works properly as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.aminmax(input=my_tensor, dim=0)
# torch.return_types.aminmax(
# min=tensor([]),
# max=tensor([]))

my_tensor = torch.tensor([[[]]])

torch.aminmax(input=my_tensor, dim=0)
# torch.return_types.aminmax(
# min=tensor([], size=(1, 0)),
# max=tensor([], size=(1, 0)))
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by albanD** [comment] 2024-07-08 14:41
Near duplicate of https://github.com/pytorch/pytorch/issues/130187
Let's continue discussion there since they have the same behavior

**Closed by albanD** 2024-07-08 14:41 UTC
