### ISSUE TITLE
Pytorch-elastic doesn't generate run_id for jobs when --rdzv_id is not specified

### ISSUE THREAD

**Issue by zclyne** [pytorch/pytorch#82160] opened 2022-07-25 20:37 UTC
### 🐛 Describe the bug

Hi! I am trying to launch elastic PytorchJobs using kubeflow training-operator on my Kubernetes cluster, and I found from the container log that the run_id of the job was "none" rather than a uuid. According to the code,
https://github.com/pytorch/pytorch/blob/c88fbae480c90ace2d6612fdff26c840850eae05/torch/distributed/launcher/api.py#L181
pytorch-elastic should generate an id for the job when it is not set, but actually I got "none" for the id rather than a generated one.

I found that it might be because the default value of the `rdzv_id` parameter is set to string "none" rather than the python keyword `none`
https://github.com/pytorch/pytorch/blob/11fe277b62e46c4acbf7de0599004535b90b54ef/torch/distributed/run.py#L437

As a result, each time I launch an elastic PytorchJob to my cluster, the job has run_id="none" and as a result, the rendezvous states stored in etcd of different jobs conflict with each other because they have the same key. If a worker is restarted, it picks up the state of the last rendezvous rather than create a new one, and thus throws a `RendezvousClosedError` which causes the worker to exist with code 1 and restart again, so the entire job fails.

### Versions

I'm using Pytorch 1.10.0 release on Python 3.7.11. I'm sorry that I cannot run the command above because the image is running in the company's private network and cannot get connected to external websites.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501

**Comment by mrshenli** [comment] 2022-08-02 16:32
cc @d4l3k

**Comment by d4l3k** [comment] 2022-08-02 17:35
For all of the workers to find each other they need a shared common ID between all of the workers. If you're doing distributed training and use a random ID they won't be able to rendezvous. I'd recommend explicitly setting it to a shared unique value on all workers (you could use the job ID or randomly generate an ID before creating the pods). With c10d you can also set the master address/port so etcd isn't required at all.

See the TorchX dist.ddp component as an example: https://github.com/pytorch/torchx/blob/main/torchx/components/dist.py#L164

**Comment by zclyne** [comment] 2022-08-02 18:07
Thank you! I think generating an ID before creating pods is the best way for me. I''ll try it out.

**Comment by mrshenli** [comment] 2022-08-05 17:14
Looks like question resolved. I am closing this issue. Please feel free to open new ones or re-open this one for followup discussions.

**Closed by mrshenli** 2022-08-05 17:14 UTC
Labels: oncall: distributed, oncall: r2p

**Comment by lmelinda** [comment] 2023-08-10 19:23
Hi I have set `torch.distributed.run --rdzv_id=0 --rdzv_backend=c10d` when I kick off multi-worker jobs, however I still encounter the issue of `RendezvousClosedError` when one worker restarts and joins the group (it'd happen right after it joins back). Do you know what's missing in this case?

**Comment by H-Huang** [comment] 2023-08-10 20:31
Hi @lmelinda, can you try setting `--max-restarts=X` where X>0? I believe the default is 0, so if any part of the group fails then the run will be cancelled

Also feel free to file a new issue with a reproduction script for the issue you are facing

**Comment by lmelinda** [comment] 2023-08-14 14:19
Sure, so the other nodes would restart when one node fails right? In the case of min/max workers are the same (no elasticity), does that mean that the failing node needs to restart and join back in the group before the other nodes finishes restarting? Say I have 4 workers and 1 fail, the rest 3 workers can't keep running since we don't meet the min number of workers right
