### ISSUE TITLE
UserWarning: The operator 'aten::sgn.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1690702789476/work/aten/src/ATen/mps/MPSFallback.mm:13.)   Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

### ISSUE THREAD

**Issue by youngboyooo** [pytorch/pytorch#106594] opened 2023-08-04 01:45 UTC
### 🐛 Describe the bug

UserWarning: The operator 'aten::sgn.out' is not currently supported on the MPS backend and will fall back to run on the CPU. This may have performance implications. (Triggered internally at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1690702789476/work/aten/src/ATen/mps/MPSFallback.mm:13.)
  Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass

### Versions

python 3.8

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by youngboyooo** [comment] 2023-08-04 01:46
use macbook pro m2 max，then I run  wav2lip_train.py   this bug will Appear

**Comment by malfet** [comment] 2023-08-24 00:22
Closing as duplicate of https://github.com/pytorch/pytorch/issues/86805

**Closed by malfet** 2023-08-24 00:22 UTC
Labels: triaged, module: mps
