### ISSUE TITLE
Building from source error

### ISSUE THREAD

**Issue by SingL3** [pytorch/pytorch#14215] opened 2018-11-20 03:10 UTC
## Issue description
Hello! I am trying to install pytorch from source in conda, and I got these error message:

> /home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:31:17: error: ‘ncclInt8’ was not declared in this scope
     {at::kChar, ncclInt8},
                 ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:32:17: error: ‘ncclUint8’ was not declared in this scope
     {at::kByte, ncclUint8},
                 ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:35:16: error: ‘ncclInt32’ was not declared in this scope
     {at::kInt, ncclInt32},
                ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:38:1: error: could not convert ‘{{at::kChar, <expression error>}, {at::kByte, <expression error>}, {at::kFloat, ncclFloat}, {at::kDouble, ncclDouble}, {at::kInt, <expression error>}, {at::kLong, ncclInt64}, {at::kHalf, ncclHalf}}’ from ‘<brace-enclosed initializer list>’ to ‘std::unordered_map<at::ScalarType, ncclDataType_t>’
 };
 ^
In file included from /home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:1:0:
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp: In member function ‘void thd::DataChannelNccl::_destroyNcclResources(THDGroup)’:
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:187:40: error: void value not ignored as it ought to be
         NCCL_CHECK(ncclCommDestroy(comm));
                                        ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp: In member function ‘thd::NcclResourcePair thd::DataChannelNccl::_getNcclResourcePair(std::vector<at::Tensor>&, THDGroup)’:
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:295:29: error: ‘ncclGroupStart’ was not declared in this scope
   NCCL_CHECK(ncclGroupStart());
                             ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:302:27: error: ‘ncclGroupEnd’ was not declared in this scope
   NCCL_CHECK(ncclGroupEnd());
                           ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp: In member function ‘virtual void thd::DataChannelNccl::allReduce(std::vector<at::Tensor>&, THDReduceOp, THDGroup)’:
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:417:29: error: ‘ncclGroupStart’ was not declared in this scope
   NCCL_CHECK(ncclGroupStart());
                             ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:432:27: error: ‘ncclGroupEnd’ was not declared in this scope
   NCCL_CHECK(ncclGroupEnd());
                           ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp: In member function ‘virtual void thd::DataChannelNccl::allGather(std::vector<at::Tensor>&, std::vector<at::Tensor>&, THDGroup)’:
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:466:29: error: ‘ncclGroupStart’ was not declared in this scope
   NCCL_CHECK(ncclGroupStart());
                             ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:473:27: error: invalid conversion from ‘void*’ to ‘int’ [-fpermissive]
         output[i].data_ptr(),
                           ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:474:23: error: invalid conversion from ‘int64_t {aka long int}’ to ‘ncclDataType_t’ [-fpermissive]
         input[i].numel(),
                       ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:477:15: error: cannot convert ‘ncclDataType_t’ to ‘void*’ for argument ‘4’ to ‘ncclResult_t ncclAllGather(const void*, int, ncclDataType_t, void*, ncclComm_t, cudaStream_t)’
         stream));
               ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:480:27: error: ‘ncclGroupEnd’ was not declared in this scope
   NCCL_CHECK(ncclGroupEnd());
                           ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp: In member function ‘virtual void thd::DataChannelNccl::reduce(std::vector<at::Tensor>&, THDReduceOp, thd::rank_type, THDGroup)’:
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:516:29: error: ‘ncclGroupStart’ was not declared in this scope
   NCCL_CHECK(ncclGroupStart());
                             ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:532:27: error: ‘ncclGroupEnd’ was not declared in this scope
   NCCL_CHECK(ncclGroupEnd());
                           ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp: In member function ‘virtual void thd::DataChannelNccl::broadcast(std::vector<at::Tensor>&, thd::rank_type, THDGroup)’:
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:568:29: error: ‘ncclGroupStart’ was not declared in this scope
   NCCL_CHECK(ncclGroupStart());
                             ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                          ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.cpp:582:27: error: ‘ncclGroupEnd’ was not declared in this scope
   NCCL_CHECK(ncclGroupEnd());
                           ^
/home/lin/pytorch/torch/lib/THD/base/data_channels/DataChannelNccl.hpp:16:26: note: in definition of macro ‘NCCL_CHECK’
     ncclResult_t error = cmd;                                             \
                    
I have searched on google. And I find it may be the problem of nccl. I run 

> export NO_SYSTEM_NCCL=1

but it didn't work.

## System Info
- PyTorch
- How you installed PyTorch (conda, pip, source):conda
- Build command you used (if compiling from source):python setup install
- OS: Ubuntu 16.04
- PyTorch version: 1.0.0
- Python version: 3.7.1
- CUDA/cuDNN version: Cuda8 cudnn 7.0.5
- GPU models and configuration: 1080Ti
- GCC version (if compiling from source): gcc 5.3.1
- CMake version: 3.12.2

**Comment by SsnL** [comment] 2018-11-20 07:30
Duplicate of #13764

**Comment by SingL3** [comment] 2018-11-20 07:45
Thanks for your reply!
I do as the PR, but then I got this

> Makefile:83: recipe for target '/home/lin/pytorch/build/nccl/obj/collectives/device/devlink.o' failed
make[5]: *** [/home/lin/pytorch/build/nccl/obj/collectives/device/devlink.o] Error 1
Makefile:45: recipe for target 'devicelib' failed
make[4]: *** [devicelib] Error 2
Makefile:25: recipe for target 'src.build' failed
make[3]: *** [src.build] Error 2
CMakeFiles/nccl_external.dir/build.make:110: recipe for target 'nccl_external-prefix/src/nccl_external-stamp/nccl_external-build' failed
make[2]: *** [nccl_external-prefix/src/nccl_external-stamp/nccl_external-build] Error 2
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/nccl_external.dir/all' failed
make[1]: *** [CMakeFiles/nccl_external.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn --use-qnnpack caffe2'

Do you have any solutions?

**Comment by SingL3** [comment] 2018-11-21 03:13
I tried torch-1.0.0a0+b827a40 and the build just passed.
But I tried 1.0.0a0+2681852 and there are still problems.

**Comment by zou3519** [comment] 2021-05-24 14:58
Closing due to age. Please feel free to reopen if you are still experiencing this issue.

**Closed by zou3519** 2021-05-24 14:58 UTC
