### ISSUE TITLE
[inductor][cpu] performance regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#109874] opened 2023-09-22 09:53 UTC
<p>new_perf_regression: 2023-09-20 nightly release vs 2023-09-17 nightly release</p>

<p>Note: multi threads secnario for models above first *, single thread for models between two *</p>

<p>new_perf_regression</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>llama</td>
      <td>1</td>
      <td>0.077857</td>
      <td>0.416423326</td>
      <td>0.032421470892381996</td>
      <td>39.62569</td>
      <td>1</td>
      <td>0.318457</td>
      <td>0.102005337</td>
      <td>0.032484313605009</td>
      <td>38.0415</td>
      <td>0.24</td>
      <td>1.0</td>
      <td>0.24</td>
      <td>0.96</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>00ae5fa</td>
      <td>1b3e5b5</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td>ede4309</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td>45e4b8c</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td>4ac707a</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td>d76d92c</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

</table>
<p>Reference SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>0de2555</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

<p>Repro</p>
<a href=https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh>
  inductor_single_run.sh </a>
<code>
bash inductor_single_run.sh multiple/single inference performance torchbench/huggingface/timm_models model float32 first static default 0
</code>

<p><a href=https://github.com/pytorch/pytorch/commit/1a361e4e9ff1a8dadd72c7301441cfb83d687f24#diff-cf6ca00beddc32a2a6a2933fb9913b6a2b925ffc3b745488967210e4343134ac>
  Suspected guilty commit </a></p>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen

**Comment by jansel** [comment] 2023-09-23 16:16
cc @peterbell10 

The link above is pointing to #108126

**Comment by leslie-fang-intel** [comment] 2023-10-08 04:36
We found 2 commits:

- https://github.com/pytorch/pytorch/pull/108126
- https://github.com/pytorch/pytorch/pull/107614

caused this regression. After these 2 PRs, there are several extra buffer created with memory copy.

**Comment by leslie-fang-intel** [comment] 2023-12-17 03:34
- Similar issue as https://github.com/pytorch/pytorch/pull/112440 and I think this issue is backend irreverent.
  - Similar fixes by adding `unsafe_alias=True` like https://github.com/pytorch/pytorch/pull/112440 also fixes this issue https://github.com/pytorch/pytorch/blob/87ea6fb84471c09795672de542622515f81af3d7/torch/_inductor/lowering.py#L4790
  - But I don't think it's safe by adding this flag `return mutate_to(dst, src, unsafe_alias=True)` during the lowering of `copy_` .  

- The root-cause is extra buffer copy introduced which are not necessary in this case
  - Generated code before regression is: https://gist.github.com/leslie-fang-intel/a5923cb16b93e029242b99c6c4eff77e
  - Generated code after regression is: https://gist.github.com/leslie-fang-intel/d48f2fa719609ff6e8ea55d83a1cb163
  - As you can see extra memory copies after the regression:
    
<img width="668" alt="image" src="https://github.com/pytorch/pytorch/assets/53841472/dc8e874d-f266-4d20-9396-3ed3f2008892">

Take `buf288`, `buf289` and `arg76_1` as example:

- `arg76_1` is a input buffer, here we will do `copy_(arg76_1, buf288)` which seems will change the input buffer.
- `buf288` is also a user of `arg76_1`, so `buf288` is realized firstly here https://github.com/pytorch/pytorch/blob/87ea6fb84471c09795672de542622515f81af3d7/torch/_inductor/ir.py#L2685
- Then `buf289` is realized as a copy of `buf288` https://github.com/pytorch/pytorch/blob/87ea6fb84471c09795672de542622515f81af3d7/torch/_inductor/ir.py#L2698-L2709
- `buf289` is also `MutationLayout` of `arg76_1` https://github.com/pytorch/pytorch/blob/87ea6fb84471c09795672de542622515f81af3d7/torch/_inductor/ir.py#L2710-L2711
- Before regression, there is no `buf289`. We will directly mark `buf288` as the `MutationLayout` of `arg76_1`.  
- **How to fix**:
  - Per the comment here https://github.com/pytorch/pytorch/blob/87ea6fb84471c09795672de542622515f81af3d7/torch/_inductor/ir.py#L2690-L2695  and discussion with @peterbell10 here https://github.com/pytorch/pytorch/pull/110787#discussion_r1350375182, if we want to skip the copy from `buf288` to `buf 289`, we need to ensure `dst` (`arg76_1`) will not be further mutated again. 
  - Per my understanding, since marking `buf288` copy to `buf289` is still during the graph lowering process, we are not sure whether `dst` (`arg76_1`) will be mutated again. So, we are not able to do it during the `GraphLowering`.
  - Is it possible to do it during the scheduler? During the `scheduler`, We possible can know that
    - `buf289` is the only mutation of  `arg76_1`
    - `buf289` depends on `buf288`.
    - How can we know `buf289` is just a copy of `buf288`? 
      - If we know that, can we directly remove `buf289`? After we remove `buf289`, how to mark `buf288` as the mutation of `arg76_1`?

**Comment by leslie-fang-intel** [comment] 2024-01-09 02:18
Expected fixing by https://github.com/pytorch/pytorch/pull/116899

**Comment by leslie-fang-intel** [comment] 2024-01-30 05:44
Close this issue as per https://github.com/pytorch/pytorch/issues/93531#issuecomment-1916066691, the llama single thread speedup is 1.392433x now.

**Closed by leslie-fang-intel** 2024-01-30 05:44 UTC
Labels: triaged, oncall: pt2, module: inductor, oncall: cpu inductor
