### ISSUE TITLE
Tensor can not get grad_fn attribute in backward hook.

### ISSUE THREAD

**Issue by xiwei777** [pytorch/pytorch#90520] opened 2022-12-09 02:42 UTC
### 🐛 Describe the bug

I try use backward in backward hook
```python
import torch
import torch.nn as nn

inp = torch.eye(4, 5, requires_grad=True)
out = (inp+1).pow(2).t()
print(out)
out.backward(torch.ones_like(out), retain_graph=True)

def hook_out(module, grad_in, grad_out):
    print("backward hook out")

    def hook_in(module, grad_in, grad_out):
        print("backward hook in")

    inp = torch.eye(4, 5, requires_grad=True)
    out = (inp+1).pow(2).t()
    print(out)
    # out.backward(torch.ones_like(out), retain_graph=True)

model_out = nn.Conv2d(3, 3, 1, 1)
input_out = torch.randn([1, 3, 16, 16])
back_hook_out = model_out.register_full_backward_hook(hook_out)
model_out(input_out).sum().backward()
```
get erro
```
tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]], grad_fn=<TBackward0>)
backward hook out
tensor([[4., 1., 1., 1.],
        [1., 4., 1., 1.],
        [1., 1., 4., 1.],
        [1., 1., 1., 4.],
        [1., 1., 1., 1.]])
Traceback (most recent call last):
  File "regist_bh.py", line 23, in <module>
    model_out(input_out).sum().backward()
  File "/data/application/xiw/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/application/xiw/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/data/application/xiw/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/utils/hooks.py", line 175, in hook
    res = user_hook(self.module, grad_inputs, self.grad_outputs)
  File "regist_bh.py", line 18, in hook_out
    out.backward(torch.ones_like(out))
  File "/data/application/xiw/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/_tensor.py", line 363, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/application/xiw/anaconda3/envs/pytorch/lib/python3.8/site-packages/torch/autograd/__init__.py", line 173, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

### Versions

torch                         1.11.0+cu113

**Comment by soulitzer** [comment] 2022-12-09 16:34
Closing since this is the expected behavior. By default the outer background runs with no-grad mode enabled, so tensors computed during backward won't require gradients, you'll need to run the outer backward with create_graph=True.  If you do you may want to use autograd.grad instead of .backward as using .backward with create_graph=True creates a reference cycle.

**Closed by soulitzer** 2022-12-09 16:34 UTC
