### ISSUE TITLE
the bug of torch._export.aot_compile when it is using a _mm_plus_mm operator

### ISSUE THREAD

**Issue by sujuyu** [pytorch/pytorch#128475] opened 2024-06-12 01:56 UTC
### 🐛 Describe the bug

I am currently using torch._export.aot_compile to compile a piece of Python logic into a dynamic library. Within the Python forward function, there is logic that involves multiplying two matrices and then adding them together.
```python
user_model_main_logits_layer = self.user_model.main_logits_layer(user_model_main_net_4_activation_fn)
user_model_bias_logits_layer = self.user_model.bias_logits_layer(user_model_bias_net_2_activation_fn)
add_8 = user_model_main_logits_layer + user_model_bias_logits_layer
```
During the process of compiling into a dynamic library, AOT (Ahead-of-Time) generates intermediate C++ code, where this logic is compiled into the _mm_plus_mm operator.
```C++
at::Tensor buf111 = at::detail::empty_strided_cpu({s0, 1L}, {1L, 1L}, at::kFloat);
// Source Nodes: [add_8, user_model_bias_net_2_activation_fn, user_model_main_net_4_activation_fn], Original ATen: [aten.add, aten.leaky_relu]
torch::inductor::_mm_plus_mm(
    buf111, 
    buf109, 
    reinterpret_tensor(L__self___user_model_main_logits_layer_weight, {128L, 1L}, {1L, 128L}, 0L), 
    buf110, 
    reinterpret_tensor(L__self___user_model_bias_logits_layer_weight, {128L, 1L}, {1L, 128L}, 0L)
    );
```
However, the process encounters a compilation error.
```bash
/tmp/torchinductor_zy429782/./dynamicLib/cb6oo6gvkfiukftkru65urbuff6lqpy4ebmw3c2quffeftjvupn7.cpp:1970:171: error: cannot bind non-const lvalue reference of type ‘at::Tensor&’ to an rvalue of type ‘at::Tensor’
 1970 | inductor::_mm_plus_mm(buf102, buf100, reinterpret_tensor(L__self___user_model_main_logits_layer_weight, {128L, 1L}, {1L, 128L}, 0L), buf101, reinterpret_tensor(L__self___user_model_bias_logits_layer_weight, {128L, 1L}, {1L, 128L}, 0L));
      |                                                                                                                                                                ^

In file included from /tmp/torchinductor_zy429782/./dynamicLib/cb6oo6gvkfiukftkru65urbuff6lqpy4ebmw3c2quffeftjvupn7.cpp:448:
/home/zy429782/miniconda3/envs/recommend/lib/python3.8/site-packages/torch/include/torch/csrc/inductor/inductor_ops.h:13:17: note:   initializing argument 5 of ‘at::Tensor torch::inductor::_mm_plus_mm(const at::Tensor&, const at::Tensor&, const at::Tensor&, const at::Tensor&, at::Tensor&)’
   13 |     at::Tensor& out);
```
In comparison with the intention of the Python code, it becomes evident that AOT has mistakenly assumed the return value is placed as the first argument when invoking the _mm_plus_mm operator. In reality, according to the function signature of _mm_plus_mm, the return value is positioned as the last argument.
```python
   21 Tensor _mm_plus_mm(
   22     const Tensor& a,
   23     const Tensor& b,
   24     const Tensor& c,
   25     const Tensor& d,
   26     Tensor& out) {
   27   at::mm_out(out, a, b);
   28   out.addmm_(c, d);
   29   return out;
   30 }
```
The issue stems from a deeper level in the generate_extern_kernel_out function within the file site-packages/torch/_inductor/codegen/cpp_wrapper_cpu.py, where by default, it assumes the first argument of all similar operators to be the return value. Unfortunately, this assumption holds true for operations like mm_out, addmm_out, and bmm_out, but does not apply to the _mm_plus_mm function, which leads to the misalignment.
![image](https://github.com/pytorch/pytorch/assets/58780297/f14643c3-9094-415f-8fdb-ae632ed57d70)
I am now in the process of adding a conditional check within the generate_extern_kernel_out function to specially handle the _mm_plus_mm operation, thereby rectifying the discrepancy.
![image](https://github.com/pytorch/pytorch/assets/58780297/fb3402b0-d931-418b-996f-3db68fcdae85)
I suggest revising the interface of the _mm_plus_mm function to harmonize coding conventions and align its parameter sequence with functions such as bmm_out, addmm_out, ensuring uniformity, and thus, definitively correcting this error.

### Versions

$python collect_env.py
Collecting environment information...
PyTorch version: 2.3.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Alibaba Group Enterprise Linux Server 7.2 (Paladin) (x86_64)
GCC version: (GCC) 10.2.1 20200825 (Alibaba 10.2.1-3 2.17)
Clang version: 13.0.1 (Alibaba 13.0.1-2.fix20230201115828.alios7 727b56cdb0c6a98b5ebb5052fbcfeef35f1397d3)
CMake version: version 3.29.3
Libc version: glibc-2.32

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.19.91-009.ali4000.alios7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    2
Core(s) per socket:    32
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 106
Model name:            Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Stepping:              6
CPU MHz:               2900.000
CPU max MHz:           3500.0000
CPU min MHz:           800.0000
BogoMIPS:              5800.00
Virtualization:        VT-x
L1d cache:             48K
L1i cache:             32K
L2 cache:              1280K
L3 cache:              49152K
NUMA node0 CPU(s):     0-31,64-95
NUMA node1 CPU(s):     32-63,96-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 invpcid_single ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local wbnoinvd dtherm ida arat pln pts avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq rdpid fsrm md_clear pconfig flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.3.0+cu118
[pip3] torchmetrics==1.0.3
[pip3] torchrec==0.6.0+cu118
[pip3] triton==2.3.0
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.3.0+cu118              pypi_0    pypi
[conda] torchmetrics              1.0.3                    pypi_0    pypi
[conda] torchrec                  0.6.0+cu118              pypi_0    pypi
[conda] triton                    2.3.0                    pypi_0    pypi

cc @ezyang @anijain2305 @chauhang

**Comment by eellison** [comment] 2024-06-13 16:03
dupe of https://github.com/pytorch/pytorch/issues/128475

**Closed by eellison** 2024-06-13 16:03 UTC
Labels: oncall: pt2
