### ISSUE TITLE
torch.cuda.memory_stats segfaults when called immediately after import torch

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#50721] opened 2021-01-19 12:12 UTC
When called with `python3 -c 'import torch; print(torch.cuda.memory_stats(0))'`, it prints `Segmentation fault (core dumped)`
```
#0  0x00007f40571b190f in c10::cuda::CUDACachingAllocator::getDeviceStats(int) ()
   from /miniconda/lib/python3.8/site-packages/torch/lib/libc10_cuda.so
#1  0x00007f4094f3e5c7 in THCPModule_memoryStats(_object*, _object*) () from /miniconda/lib/python3.8/site-packages/torch/lib/libtorch_python.so
```

When called with `python3 -c 'import torch; a = torch.zeros(3).cuda(); print(torch.cuda.memory_stats(0))'` everything works. I guess `memory_stats` does not check if CUDA is initialized?

This is on PyTorch 1.6.0 (a bit vintage now). I wonder if it's still there on 1.7.1.

@ngimel

**Comment by ngimel** [comment] 2021-01-19 18:15
duplicate of #49952.

**Closed by ngimel** 2021-01-19 18:15 UTC

**Comment by vadimkantorov** [comment] 2021-01-19 18:30
for my second case, it printed something even when passed just `0`
