### ISSUE TITLE
`sum` and `sparse.sum` have different behavior for scalar tensor

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#72793] opened 2022-02-14 12:15 UTC
### 🐛 Describe the bug

`sum` and `sparse.sum` have different behavior for scalar tensor when `dim=0`(dimension 0 needs to reduce).

```python
import torch
results = dict()
input_tensor = torch.rand([], dtype=torch.float64)

input = input_tensor.clone()
dim = 0
print(torch.sum(input, dim=dim))
# tensor(0.1512, dtype=torch.float64)
torch.sparse.sum(input_tensor.clone().to_sparse(),dim=dim,)
# RuntimeError: Trying to create tensor with negative dimension -1: [-1, 1]
```

I think the behavior of `torch.sparse.sum` makes sense because you cannot reduce the 0-dimension of scalar tensor.

### Versions

pytorch: 1.10.1

cc @nikitaved @pearu @cpuhrsch

**Comment by samdow** [comment] 2022-02-14 14:38
Note that the dense version matches what numpy does:
```
>>> x = numpy.array(0.5)
>>> numpy.sum(x, axis=0)
0.5
```

**Comment by pearu** [comment] 2022-02-14 15:21
This is a duplicate of https://github.com/pytorch/pytorch/issues/65400 but with different expected behavior.

**Comment by cpuhrsch** [comment] 2022-02-14 16:43
@TestSomething22 - this seems to be more about the behavior of torch.sum than torch.sparse.sum. If you agree, can you open a separate issue only focused on torch.sum? Then we can redirect it more accurately.

**Comment by samdow** [comment] 2022-02-14 17:07
Per @pearu's comment, it seems like this is a duplicate with different expected behavior. Closing to consolidate conversation to that earlier issue

**Closed by samdow** 2022-02-14 17:07 UTC
Labels: module: sparse, triaged, module: reductions
