### ISSUE TITLE
DISABLED test_broadcast (__main__.TestNCCL)

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#38833] opened 2020-05-20 23:23 UTC
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28226//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28233//console
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/py3.6-clang7-rocmdeb-ubuntu16.04-test2/28234//console

cc @ezyang @gchanan @zou3519

**Comment by jithunnair-amd** [comment] 2020-05-20 23:33
@jeffdaily Isn't test_nccl already blacklisted for ROCm CI runs?

**Comment by jeffdaily** [comment] 2020-05-20 23:36
Yes, merged yesterday.
https://github.com/pytorch/pytorch/pull/38730

**Comment by jithunnair-amd** [comment] 2020-05-21 01:34
@pritamdamania87 Can you please elaborate on when certain tests are added to the list at https://raw.githubusercontent.com/zdevito/pytorch_disabled_tests/master/result.json (which results in them needing to be run with PYTORCH_RUN_DISABLED_TESTS=1), vs being annotated as being skipped in the unit test file eg. using `skipIfRocm` annotation. Esp. in this case since these tests seem to be failing only for ROCm CI builds. Having the skip logic be within the pytorch source code allows the ROCm team to enable tests as and when they are fixed. It'd help if we understand the reasoning behind when certain tests are added to the above list instead.

**Comment by ezyang** [comment] 2020-05-21 13:58
@jithunnair-amd the way pytorch disabled tests works is that it is a "faster" way of getting disables into master, since you don't have to land anything. I agree with you though, we shouldn't be using disable tests mechanism here. Can you submit PRs to skip these tests in ROCm? Then you can close these DISABLED issues (and that will update result.json)

**Comment by jithunnair-amd** [comment] 2020-05-21 14:26
As Jeff mentioned above, in PR #38730, we disabled the entire test_nccl suite for ROCm. The reason we went that route is because these tests pass when run standalone, but fail when running the entire test_nccl suite. You can read the gory details in the PR. We're pretty confident it's surfaced by mruberry's changes in 9cfc10d, but we're still trying to root cause it, as the connection is not clear.
Given that we have disabled the entire test suite for the above reason, do you still want me to disable the individual tests? As I said, they run fine standalone on ROCm

**Comment by ezyang** [comment] 2020-05-26 13:49
OK, reenabling this test.

**Closed by ezyang** 2020-05-26 13:49 UTC
Labels: high priority, topic: flaky-tests, triage review
