### ISSUE TITLE
Can't compile pytorch from source

### ISSUE THREAD

**Issue by shepherd1530** [pytorch/pytorch#34040] opened 2020-03-01 10:32 UTC
## 🐛 Bug

I have been trying to build pytorch v1.4 from the GitHub repo on a device running arm64 but I get an error once I start building. 
I have looked through the issues page for similar issues but the one's I saw are for v1.0.

Here's my stacktrace.

`[ 53%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/math/sigmoid-neonfma-rr2-lut64-p2-div.c.o                                      In file included from /root/pytorch_install/pytorch/third_party/XNNPACK/include/xnnpack.h:15,                        from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/params.h:15,                     from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/spmm.h:11,                       from /root/pytorch_install/pytorch/third_party/XNNPACK/src/f32-spmm/gen/8x2-neonfma.c:14:                                            /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_1d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:189:2: warning: ‘pthreadpool_function_1d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_1d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:196:2: warning: ‘pthreadpool_function_2d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_2d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:203:2: warning: ‘pthreadpool_function_2d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_2d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:212:2: warning: ‘pthreadpool_function_3d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_3d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_4d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 [ 53%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/math/sigmoid-neonfma-rr2-p5-div.c.o                                            [ 53%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c.o                                        [ 53%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f16-gemm/gen/6x8-neonfp16arith-ld64.c.o                                        [ 53%] Building C object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f16-gemm/gen/8x8-neonfp16arith-ld64.c.o                                        [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-dwconv/up4x9-aarch64-neonfma-cortex-a55.S.o                              [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-dwconv/up4x9-aarch64-neonfma.S.o                                         [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/1x12-aarch64-neonfma-cortex-a53.S.o                             [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/1x8-aarch64-neonfma-cortex-a53.S.o                              In file included from /root/pytorch_install/pytorch/third_party/XNNPACK/include/xnnpack.h:15,                        from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/params.h:15,                     from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/gemm.h:14,                       from /root/pytorch_install/pytorch/third_party/XNNPACK/src/f16-gemm/gen/4x8-neonfp16arith-ld64.c:18:                                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_1d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:189:2: warning: ‘pthreadpool_function_1d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_1d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:196:2: warning: ‘pthreadpool_function_2d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_2d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:203:2: warning: ‘pthreadpool_function_2d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_2d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:212:2: warning: ‘pthreadpool_function_3d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_3d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_4d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/1x8-aarch64-neonfma-cortex-a57.S.o                              [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/1x8-aarch64-neonfma-cortex-a75.S.o                              [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/4x12-aarch64-neonfma-cortex-a53.S.o                             [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/4x8-aarch64-neonfma-cortex-a53.S.o                              In file included from /root/pytorch_install/pytorch/third_party/XNNPACK/include/xnnpack.h:15,                        from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/params.h:15,                     from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/gemm.h:14,                       from /root/pytorch_install/pytorch/third_party/XNNPACK/src/f16-gemm/gen/6x8-neonfp16arith-ld64.c:18:                                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_1d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:189:2: warning: ‘pthreadpool_function_1d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_1d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:196:2: warning: ‘pthreadpool_function_2d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_2d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:203:2: warning: ‘pthreadpool_function_2d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_2d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:212:2: warning: ‘pthreadpool_function_3d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_3d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_4d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/4x8-aarch64-neonfma-cortex-a57.S.o                              [ 53%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/4x8-aarch64-neonfma-cortex-a75.S.o                              [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/4x8-aarch64-neonfma-ld128.S.o                                   [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/4x8-aarch64-neonfma-ld64.S.o                                    [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/5x8-aarch64-neonfma-cortex-a57.S.o                              [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/5x8-aarch64-neonfma-cortex-a75.S.o                              [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/6x8-aarch64-neonfma-cortex-a73.S.o                              [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/6x8-aarch64-neonfma-cortex-a53.S.o                              [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/6x8-aarch64-neonfma-cortex-a75.S.o                              [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/6x8-aarch64-neonfma-cortex-a57.S.o                              In file included from /root/pytorch_install/pytorch/third_party/XNNPACK/include/xnnpack.h:15,                        from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/params.h:15,                     from /root/pytorch_install/pytorch/third_party/XNNPACK/src/xnnpack/gemm.h:14,                       from /root/pytorch_install/pytorch/third_party/XNNPACK/src/f16-gemm/gen/8x8-neonfp16arith-ld64.c:18:                                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:183:2: warning: ‘pthreadpool_function_1d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_1d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:189:2: warning: ‘pthreadpool_function_1d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_1d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:196:2: warning: ‘pthreadpool_function_2d_t’ is deprecated [-Wdeprecated-declarations]                                         pthreadpool_function_2d_t function,               ^~~~~~~~~~~~~~~~~~~~~~~~~                       /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:203:2: warning: ‘pthreadpool_function_2d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_2d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:212:2: warning: ‘pthreadpool_function_3d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_3d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 /root/pytorch_install/pytorch/third_party/pthreadpool/include/pthreadpool.h:223:2: warning: ‘pthreadpool_function_4d_tiled_t’ is deprecated [-Wdeprecated-declarations]                                   pthreadpool_function_4d_tiled_t function,         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~                 [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/6x8-aarch64-neonfma-ld128.S.o                                   [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/1x12-aarch64-neonfma-cortex-a53.S.o                         [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen/6x8-aarch64-neonfma-ld64.S.o                                    [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/1x8-aarch64-neonfma-cortex-a75.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/1x8-aarch64-neonfma-cortex-a57.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/4x12-aarch64-neonfma-cortex-a53.S.o                         [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/1x8-aarch64-neonfma-cortex-a53.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/4x8-aarch64-neonfma-cortex-a53.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/4x8-aarch64-neonfma-cortex-a57.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/4x8-aarch64-neonfma-ld128.S.o                               [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/4x8-aarch64-neonfma-ld64.S.o                                [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/5x8-aarch64-neonfma-cortex-a57.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/4x8-aarch64-neonfma-cortex-a75.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/5x8-aarch64-neonfma-cortex-a75.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/6x8-aarch64-neonfma-cortex-a53.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/6x8-aarch64-neonfma-cortex-a75.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/6x8-aarch64-neonfma-cortex-a57.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/6x8-aarch64-neonfma-cortex-a73.S.o                          [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/6x8-aarch64-neonfma-ld64.S.o                                [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-gemm/gen-inc/6x8-aarch64-neonfma-ld128.S.o                               [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/1x12-aarch64-neonfma-cortex-a53.S.o                                [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/1x8-aarch64-neonfma-cortex-a53.S.o                                 [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/1x8-aarch64-neonfma-cortex-a57.S.o                             [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/1x8-aarch64-neonfma-cortex-a75.S.o                             [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/4x8-aarch64-neonfma-cortex-a53.S.o                                 [ 54%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/4x12-aarch64-neonfma-cortex-a53.S.o                                [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/4x8-aarch64-neonfma-cortex-a75.S.o                             [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/4x8-aarch64-neonfma-cortex-a57.S.o                             [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/5x8-aarch64-neonfma-cortex-a75.S.o                             [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/5x8-aarch64-neonfma-cortex-a57.S.o                             [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/6x8-aarch64-neonfma-cortex-a53.S.o                                 [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/6x8-aarch64-neonfma-cortex-a73.S.o                                 [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/6x8-aarch64-neonfma-cortex-a75.S.o                             [ 55%] Building ASM object confu-deps/XNNPACK/CMakeFiles/XNNPACK.dir/src/f32-igemm/gen/6x8-aarch64-neonfma-cortex-a57.S.o                             [ 55%] Linking C static library ../../lib/libXNNPACK.a                                              [ 55%] Built target XNNPACK                       make: *** [Makefile:141: all] Error 2             Traceback (most recent call last):                  File "setup.py", line 737, in <module>              build_deps()                                    File "setup.py", line 316, in build_deps            cmake=cmake)                                    File "/root/pytorch_install/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2            cmake.build(my_env)                             File "/root/pytorch_install/pytorch/tools/setup_helpers/cmake.py", line 337, in build                 self.run(build_args, my_env)                    File "/root/pytorch_install/pytorch/tools/setup_helpers/cmake.py", line 141, in run                   check_call(command, cwd=self.build_dir, env=env)                                                  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call                                      raise CalledProcessError(retcode, cmd)        subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.`

## Environment

 - PyTorch Version : v1.4
 - OS : Ubuntu 19.04
 - How you installed PyTorch : pip
 - Build command you used (if compiling from source): python3 setup.py build
 - Python version: 3.7
 - Any other relevant information: Ubuntu on  Arm64 

## Step to reproduce

Running **python3 setup.py build**

**Comment by ezyang** [comment] 2020-03-02 19:52
cc @AshkanAliabadi 

Can you post your full cmake log? There don't seem to enough log lines from the bottom.

**Comment by ezyang** [comment] 2020-03-02 19:52
Also, PyTorch v2.0 is not a thing; can you post what the real version you're trying to compile is?

**Comment by AshkanAliabadi** [comment] 2020-03-02 21:37
I would try the following:

- Make sure you have saved all your work, then do a "git clean -xfd" followed by a "git reset --hard" to remove build artifacts and pending changes, if any.  As mentioned, make sure you have saved all your changes prior to issuing these commands.

- Update to the tip of master.  Then do a "git submodule sync" followed by "git submodule update --init --recursive".

- In order to build native C++ PyTorch Mobile for Android without JNI bindings, do:
BUILD_PYTORCH_MOBILE=1 ANDROID_ABI=arm64-v8a ./scripts/build_android.sh

If you have ccache and want to speed up the build, add a -DANDROID_CCACHE=$(which ccache) to the end, but this step is not required for a proper build.

If you still run into issues, please provide detailed steps to repo and I will take a look.  Thank you!

**Comment by shepherd1530** [comment] 2020-03-02 23:05
@ezyang my bad I edited the version it's actually v1.4 and I added more logs.

**Comment by shepherd1530** [comment] 2020-03-02 23:13
@AshkanAliabadi I tried the commands and I still get the same error but building actually speeds up considerably.

My steps include

`sudo apt install libopenblas-dev libblas-dev m4 cmake cython python3-dev PyYaml python3-setuptools`

```
git clone --recursive https://github.com/pytorch/pytorch

export NO_CUDA=1
export NO_DISTRIBUTED=1
export NO_MKLDNN=1 
export NO_NNPACK=1
export NO_QNNPACK=1

python3 setup.py build
```

**Comment by AshkanAliabadi** [comment] 2020-03-02 23:49
Can you also post the CMake logs?  You can find it inside ./build or ./build_android under CMakeFiles/CMakeOutput.log and CMakeFiles/CMakeError.log.  The output you have posted only shows warnings, and a final error that a CMake invocation failed, but not where or why the error happened.  I will look into replicating it using the instructions you sent on my end on macOS since I don't have access to an Ubuntu machine. :/

**Comment by shepherd1530** [comment] 2020-03-03 00:05
@AshkanAliabadi 
These are the log files thanks.

[CMakeError.log](https://github.com/pytorch/pytorch/files/4278597/CMakeError.log)
[CMakeOutput.log](https://github.com/pytorch/pytorch/files/4278598/CMakeOutput.log)

**Comment by AshkanAliabadi** [comment] 2020-03-03 01:11
OK unfortunately couldn't replicate on macOS.  PyTorch built successfully following your instructions.  By the way when you say building on ARM64, you mean your host is running on an ARM64, right?  Not that you are cross compiling for an ARM64 device, which is what I thought originally?

Can you also do a "python3 setup.py build >> output.txt" and upload the results as well?  I'm thinking maybe going through the console output can help unravel the mystery.

**Comment by shepherd1530** [comment] 2020-03-03 08:54
Here is the output [output.txt](https://github.com/pytorch/pytorch/files/4280160/output.txt)

And yes I my host Device is arm64(arch64).

**Comment by yuanzhangzhu** [comment] 2020-05-14 04:39
also hit this issue , aarch64 host , build pytorch, failed in XNNPACK,  anybody know the reason, thanks!





[ 53%] Linking C static library ../../lib/libXNNPACK.a
[ 53%] Built target XNNPACK
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 745, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "/root/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 339, in build
    self.run(build_args, my_env)
  File "/root/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 2.
root@pytorch:~/pytorch#

**Comment by AshkanAliabadi** [comment] 2020-05-14 06:00
Unfortunately it's difficult for me to replicate this issue without having access to an ARM based host.  Can you see anything in the logs that may suggest where this is happening?  Any error messages besides that can help root cause this?  As a workaround you can just pass USE_XNNPACK=OFF to CMake to disable XNNPACK for the time being.

**Comment by yuanzhangzhu** [comment] 2020-05-14 06:24
https://github.com/pytorch/pytorch/pull/35157/commits/5c318611978a7f9add5b889ad70e4af5b10a9c00
gcc don't support MOV V8.4s, V9.4s 
change MOV V8.4s, V9.4s  to MOV V8.16b, V9.16b works

**Comment by AshkanAliabadi** [comment] 2020-05-14 06:27
So this has nothing to do with XNNPACK?

**Comment by yuanzhangzhu** [comment] 2020-05-14 06:32
seems gcc issue.

**Comment by yuanzhangzhu** [comment] 2020-05-14 06:33
XNNPACK better rewite in "c" , asm is hard to maintain

**Comment by AshkanAliabadi** [comment] 2020-05-14 06:38
Right so to be clear there is a difference between QNNPACK and XNNPACK.  These are two separate libraries.  I want to make sure that the link you provided actually solves the issue you are seeing.  The fix you linked to is in the QNNPACK library which is different from XNNPACK.  With that patch applied, can you actually build PyTorch successfully without any issues?

**Comment by yuanzhangzhu** [comment] 2020-05-14 06:40
root@pytorch:~# uname -a
Linux pytorch 4.15.0-99-generic #100-Ubuntu SMP Wed Apr 22 20:33:59 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
root@pytorch:~# python3
Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
1.5.0a0+4ff3872
>>>

**Comment by stashvala** [comment] 2020-05-29 13:04
> [5c31861](https://github.com/pytorch/pytorch/commit/5c318611978a7f9add5b889ad70e4af5b10a9c00)
> gcc don't support MOV V8.4s, V9.4s
> change MOV V8.4s, V9.4s to MOV V8.16b, V9.16b works

I had the same problem when building `q8gemm/8x8-dq-aarch64-neon.S.o` on aarch64 (via qemu) and can confirm that this patch solved the issue!

**Comment by ezyang** [comment] 2020-06-01 14:06
Closing this as fixed.

**Closed by ezyang** 2020-06-01 14:06 UTC
Labels: module: build, module: xnnpack, triaged

**Comment by MBorgesT** [comment] 2021-06-28 18:46
> [5c31861](https://github.com/pytorch/pytorch/commit/5c318611978a7f9add5b889ad70e4af5b10a9c00)
> gcc don't support MOV V8.4s, V9.4s
> change MOV V8.4s, V9.4s to MOV V8.16b, V9.16b works

How do I change the MOV version? Can't find anything on google

**Comment by AnirbanHFX** [comment] 2022-03-04 10:27
Facing the same issue when trying to build PyTorch 1.10.2 on ARMv7l (Odroid XU4) using g++ (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0.

XNNPACK build fails due to the following error -
```
/third_party/XNNPACK/src/qs8-gemm/gen/8x8c4-minmax-fp32-neondot.c:245:16: error: incompatible types when assigning to type ‘int32x4_t’ from type ‘int’
48:16: error: incompatible types when assigning to type ‘int32x4_t’ from type ‘int’
     vacc7x0123 = vcvtnq_s32_f32(vproduct7x0123);
```

Has anyone solved this issue?

**Comment by rita-carv** [comment] 2022-10-20 14:31
> > [5c31861](https://github.com/pytorch/pytorch/commit/5c318611978a7f9add5b889ad70e4af5b10a9c00)
> > gcc don't support MOV V8.4s, V9.4s
> > change MOV V8.4s, V9.4s to MOV V8.16b, V9.16b works
> 
> How do I change the MOV version? Can't find anything on google

i have the same question, I can't find anywhere how to change the MOV version
