### ISSUE TITLE
torch.multinomial samples same elements multiple times when replacement=False

### ISSUE THREAD

**Issue by SneachChea** [pytorch/pytorch#25030] opened 2019-08-22 15:55 UTC
## 🐛 Bug

Sometimes a sampled index is drawn multiple time in a row even if replacement=False on `torch.multinomial`. This happens when an element of `input` is very small but not zero.

## To Reproduce

Here is a minimal working example:
```python 
import torch
torch.manual_seed(0)
w = torch.tensor( [1.2899e-01, 6.2532e-01, 3.6483e-02, 1.5196e-01, 2.9675e-03, 
4.9773e-03,4.5881e-02, 2.9019e-03, 5.2139e-04, 1.5281e-17] )
print(torch.multinomial(w, 10, replacement=False))
```
.

## Expected behavior

Raise an error because one element of `input` is almost zero.

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.2.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.3.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @vincentqb @fritzo @neerajprad @alicanb @vishwakftw @nikitaved

**Comment by andreaskoepf** [comment] 2019-08-22 18:31
I can confirm the bug for CPU tensors. The Cuda version seems to be more robust with the values above but has a related problem (see below).
Relevant code for the CPU version starts [here](https://github.com/pytorch/pytorch/blob/ae342fd0760d66ca870484553bce805cc466a4bc/aten/src/TH/generic/THTensorRandom.cpp#L431).

Refs for x-check with cuda version: 
- [THCTensor_(multinomial)](https://github.com/pytorch/pytorch/blob/839b496fbdb737ec95e66e4c6bc7c356e846c900/aten/src/THC/generic/THCTensorRandom.cu#L33)
- [sampleMultinomialWithoutReplacement()](https://github.com/pytorch/pytorch/blob/839b496fbdb737ec95e66e4c6bc7c356e846c900/aten/src/THC/THCTensorRandom.cuh#L323)

The cuda-backend completely brakes due to an assert when `torch.multinomial(w, 10, replacement=False)` is executed with a 10-element cuda tensor of which one element is <= 0. The following assert is triggered:
 
/opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCTensorRandom.cuh:107: int binarySearchForMultinomial(T *, T *, int, T) [with T = float]: block: [0,0,0], thread: [0,0,0] Assertion `THCNumerics<T>::gt(cumdist[size - 1], 0)` failed.

After the assert all other cuda-operations generate `RuntimeError: CUDA error: device-side assert triggered`.

**Comment by andreaskoepf** [comment] 2019-08-23 17:56
If the exponents of the probabilities in one row have significantly differing values (e.g. half < 1e-15 and others > 1e+15) the optimized local cumulative sum update of the CPU impl does not work as expected. The mantissa information of smaller values that come after large values in the tensor is lost during the summation and those small entries may effectively get the same value as their predecessor in the tensor - even though they have not been drawn before. I noticed cases where the current impl even ran into states with a cumulative sum table that was no longer monotonically increasing.

The cuda implementation does not have these problems since it recomputes the cumulative sum for each sampling step, keeping a local copy of the original distribution and setting in it the probability of selected elements to zero.

A simple fix of the CPU version would be to also to recompute the cumulative sum after each sample. If the performance should not be affected by the fix the row normalization step could be removed and instead the uniform random sample before the binary-search be multiplied by the row sum. On the other hand to improved the CPU performance of multinomial it could probably be easily parallelized (though I do currently not know if special care has to be taken for the rng states).

General question: Should this be fixed in the old TH/THC code first and later be ported to ATen or is the rule to port everything touched to ATen directly?

Regarding the CUDA assert problems I this that a similar check to the one in the cpu impl could be added to detect ill input distributions, e.g. [this THArgChecks](https://github.com/pytorch/pytorch/blob/649c9cd1cab7432ca9dc6a096777033b378171c5/aten/src/TH/generic/THTensorRandom.cpp#L371-L378).

**Comment by ezyang** [comment] 2019-08-23 19:23
> General question: Should this be fixed in the old TH/THC code first and later be ported to ATen or is the rule to port everything touched to ATen directly?

If the TH/THC fix is short, I won't hold a fix like that hostage to porting the kernel. If it is big / necessitates a rewrite, better to do the port in that case.

**Comment by ezyang** [comment] 2019-08-23 19:30
(@andreaskoepf I am not familiar enough with this part to say if your fix is along the right lines; maybe some of the distributions folks could help. I've cc'ed them on)

**Comment by ifedan** [comment] 2019-09-26 16:12
@andreaskoepf multinomial was moved from TH/THC to ATen. Does the issue still exist?

**Comment by andreaskoepf** [comment] 2019-09-27 09:08
@ifedan I fear this issue is not solved for the CPU case. I created a new test (which currently fails) in `test_torch.py` and sumbitted it as PR, please see https://github.com/pytorch/pytorch/pull/26962.

To run it use: `python test_torch.py TestTorch.test_multinomial_unnormalized`

**Comment by rgommers** [comment] 2019-11-30 19:32
@ifedan you have a PR in progress on this. Not sure why you unassigned yourself, could you comment on what the next step should be here?

**Comment by zou3519** [comment] 2019-12-02 19:57
@rgommers I think we are looking for someone to take over @ifedan's WIP pull request. I am happy to either take it over or review any changes to it.

**Comment by ngimel** [comment] 2022-02-07 19:43
Fixed on master

**Closed by ngimel** 2022-02-07 19:43 UTC
Labels: high priority, module: distributions, triaged, module: correctness (silent)
