### ISSUE TITLE
[TensorDict - compile] Iterating over `__dataclass_fields__` breaks within dynamo

### ISSUE THREAD

**Issue by vmoens** [pytorch/pytorch#129661] opened 2024-06-27 15:14 UTC
### 🐛 Describe the bug

Iterating over `__dataclass_fields__` breaks within dynamo.

Example code: https://github.com/pytorch/tensordict/blob/b5cb40aaeb824ac632c0a2f178430105513525d1/tensordict/tensorclass.py#L608

```
You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

======================================================================= short test summary info =======================================================================
FAILED test/test_compile.py::TestTC::test_tc_arithmetic - torch._dynamo.exc.Unsupported: call_method GetAttrVariable(UserDefinedObjectVariable(MyClass), __dataclass_fields__) items [] {}
```

### Versions

PyTorch version: 2.5.0.dev20240627
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.5 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.3
Libc version: N/A

Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec 4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-14.5-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Max

Versions of relevant libraries:
[pip3] mujoco-torch==0.1.0
[pip3] numpy==1.26.4
[pip3] optree==0.11.0
[pip3] torch==2.5.0.dev20240627
[pip3] torchao==0.1
[pip3] torchaudio==2.4.0.dev20240627
[pip3] torchrl==0.4.0+7c0a7c8
[pip3] torchtext==0.18.0
[pip3] torchvision==0.20.0.dev20240627
[conda] Could not collect

cc @ezyang @anijain2305 @chauhang @penguinwu

**Comment by anijain2305** [comment] 2024-07-22 17:05
Duplicate of https://github.com/pytorch/pytorch/issues/129660 and should be resolved now.

@vmoens please confirm from TensorDict side.

**Comment by anijain2305** [comment] 2024-07-23 04:34
Checked. This works. Closing.

**Closed by anijain2305** 2024-07-23 04:34 UTC
Labels: triaged, oncall: pt2
