### ISSUE TITLE
Bug: torch.tensordot is not consistent with np.tensordot

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#65989] opened 2021-10-01 08:11 UTC
Sample program:

```
a = torch.tensor((1, 2, 3))
b = torch.tensor((4, 5, 6))
torch.tensordot(a, b, dims=0)
: RuntimeError: unsupported input to tensordot, got dims=0

np.tensordot(a, b, axes=0)
: array([[ 4,  5,  6],
             [ 8, 10, 12],
             [12, 15, 18]])
```

There may be other inconsistencies.

The documentation and examples for torch.tensordot could also use an update. If updating the docs it'd be nice to also add a seealso section and close https://github.com/pytorch/pytorch/issues/50802.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by ngimel** [comment] 2021-10-01 19:31
duplicate of many previous issues, and fixed on master.

**Closed by ngimel** 2021-10-01 19:31 UTC
Labels: triaged, module: linear algebra
