### ISSUE TITLE
"fatal: not a git repository (or any of the parent directories): .git", indicates that PyTorch is trying to access submodules during its installation process, but it can't find a valid .git directory within the project.

### ISSUE THREAD

**Issue by KillshotELOx** [pytorch/pytorch#116088] opened 2023-12-19 07:46 UTC
### 🐛 Describe the bug

(base) C:\Users\emili\Downloads\pytorch-main\pytorch-main>python setup.py develop
fatal: not a git repository (or any of the parent directories): .git
Building wheel torch-2.3.0a0+gitUnknown
-- Building version 2.3.0a0+gitUnknown
 --- Trying to initialize submodules
fatal: not a git repository (or any of the parent directories): .git
 --- Submodule initalization failed
Please run:
        git submodule update --init --recursive

(base) C:\Users\emili\Downloads\pytorch-main\pytorch-main>git submodule update --init --recursive
fatal: not a git repository (or any of the parent directories): .git

(base) C:\Users\emili\Downloads\pytorch-main\pytorch-main>
------------------------------------------------------------------------------------------------------------------------------------------
Explanation:

Submodules: PyTorch relies on external libraries called "submodules" for certain functionalities.
Initialization: During installation, it attempts to initialize and update these submodules using the git submodule update --init --recursive command.
Missing or Invalid .git: However, the error message suggests that the expected .git directory, which manages the submodules, is either missing or not recognized as a valid git repository.

### Versions

To simplify download and installation in the future, consider using choco install wget before running wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py. Remember to check collect_env.py for security purposes before running it.

Wget v1.21.4 [Approved]
Wget package files install completed. Performing other installation steps.
The package Wget wants to run 'chocolateyinstall.ps1'.
Note: If you don't run this script, the installation will fail.
Note: To confirm automatically next time, use '-y' or consider:
choco feature enable -n allowGlobalConfirmation
Do you want to run the script?([Y]es/[A]ll - yes to all/[N]o/[P]rint): Y

Getting x64 bit zip

PS C:\Users\emili> python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22631-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture=9
CurrentClockSpeed=4000
DeviceID=CPU0
Family=107
L2CacheSize=2048
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=4000
Name=AMD Ryzen 3 5300G with Radeon Graphics
ProcessorType=3
Revision=20480

Versions of relevant libraries:
[pip3] numpy==1.26.2
[pip3] torchmetrics==1.2.1
[pip3] torchmetrics==1.2.1
[conda] Could not collect

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by KillshotELOx** [comment] 2023-12-19 07:50
Main Point: I am trying to install PyTorch for Audiocraft but encountered errors during the installation process.

Details:

Several packages including audiocraft, demucs, encodec, etc., are throwing deprecation warnings about using "eggs" instead of pip for installation.
Pip successfully downloaded and prepared the PyTorch package but failed to build the wheel due to an error message stating the package name should be "torch" instead of "pytorch".
Restructure:

While installing PyTorch for Audiocraft, I encountered deprecation warnings for several packages suggesting pip instead of "eggs". The installation itself started well, but building the PyTorch wheel failed due to an incorrect package name (should be "torch").

Additional Notes:

The provided snippet includes unnecessary details like the "DEPRECATION" messages and full tracebacks. These can be omitted unless specifically requested for debugging purposes.
Focusing on the main points and restructuring with clear language makes the situation easier to understand and address.

Error return:

DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\audiocraft-1.2.0a2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\demucs-4.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\encodec-0.1.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\gradio-4.10.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\librosa-0.10.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\protobuf-4.25.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\torchmetrics-1.2.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
Collecting pytorch
  Downloading pytorch-1.0.2.tar.gz (689 bytes)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pytorch
  Building wheel for pytorch (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\emili\AppData\Local\Temp\pip-install-2bu4xm1v\pytorch_238b8f1383db4defbf9df0343ae5b116\setup.py", line 15, in <module>
          raise Exception(message)
      Exception: You tried to install "pytorch". The package named for PyTorch is "torch"
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pytorch
  Running setup.py clean for pytorch
Failed to build pytorch
ERROR: Could not build wheels for pytorch, which is required to install pyproject.toml-based projects
PS C:\Users\emili>

**Comment by KillshotELOx** [comment] 2023-12-19 07:53
attempt to install torch:

Initial Goal: Install torch using pip for your Audiocraft project.

Steps Taken:

Ran pip install torch in your Command Prompt.
Outcome:

Encountered several deprecation warnings about outdated package installation methods for other packages like audiocraft and demucs.
Received an error message stating pip couldn't find any matching versions for torch (no versions available).
Possible Cause:

Your previous attempt to install pytorch (incorrect package name) might have confused the package index and disrupted the search for torch.
Next Steps:

Clean pip cache: Run pip cache clean to remove any remnants of the failed pytorch installation.
Rerun with correct name: Try again with pip install torch to use the proper package name.
Additional Information:

Ignore the deprecation warnings for now, they shouldn't impact torch installation.
If the error persists, share the full output from pip install torch for further guidance on interpreting the specific error and finding a solution.

PS C:\Users\emili> pip install torch
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\audiocraft-1.2.0a2-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\demucs-4.0.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\encodec-0.1.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\gradio-4.10.0-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\librosa-0.10.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\protobuf-4.25.1-py3.12-win-amd64.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
DEPRECATION: Loading egg at c:\users\emili\appdata\local\programs\python\python312\lib\site-packages\torchmetrics-1.2.1-py3.12.egg is deprecated. pip 24.3 will enforce this behaviour change. A possible replacement is to use pip for package installation.. Discussion can be found at https://github.com/pypa/pip/issues/12330
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
PS C:\Users\emili>

**Comment by malfet** [comment] 2023-12-21 22:04
- PyTorch is yet not available for Python3.12 (but nightly builds and upcoming 2.2 release should be)
- `git clone --recurse-submodules https://github.com/pytorch/pytorch` should check out the repo with submodules

**Comment by malfet** [comment] 2023-12-21 22:05
Please do not hesitate to start a discussion thread on https://discuss.pytorch.org/ or open a new issue if you encounter issues with PyTorch

Closing as duplicate of https://github.com/pytorch/pytorch/issues/110436

**Closed by malfet** 2023-12-21 22:05 UTC
Labels: module: build, module: windows, triaged
