### ISSUE TITLE
In-place sub with shared memory, wrong result

### ISSUE THREAD

**Issue by bermanmaxim** [pytorch/pytorch#950] opened 2017-03-07 11:09 UTC
Hi, I ran into this non-intuitive behavior:
```
test = torch.Tensor([1, 2, 3, 4, 5])
test[1:] -= test[:-1]
```
results in `test = [1, 1, 1, 1, 4]` for me, while the non in-place version `test[1:] = test[1:] - test[:-1]` returns the correct result `[1, 1, 1, 1, 1]`. If I put the tensor to cuda() first the output seems correct...
(pytorch compiled from master '0.1.9+aaf41c6')

**Comment by albanD** [comment] 2017-03-07 12:30
I think this is a duplicate of #906

**Comment by bermanmaxim** [comment] 2017-03-07 14:19
Alright, thanks, hadn't seen that other one.

**Closed** 2017-03-07 14:19 UTC
