### ISSUE TITLE
warning: field of class type without a DLL interface used in a class with a DLL interface OR from that of the derived class

### ISSUE THREAD

**Issue by liuchanfeng165** [pytorch/pytorch#19667] opened 2019-04-24 10:07 UTC
Hi ,
compiled ‘setup.py’  in dir 'cuda' of  extension-cpp-master  and got  2 erros like that:

![image](https://user-images.githubusercontent.com/18642811/56650882-83a3a180-66ba-11e9-866e-6301b23e63cd.png)

ran it in torch1.0,1 , win7-x64
help pls!
regards

**Comment by peterjc123** [comment] 2019-04-24 10:45
These are warnings, aren't they?

**Comment by liuchanfeng165** [comment] 2019-04-24 10:55
> These are warnings, aren't they?

haaa, thanks...
![image](https://user-images.githubusercontent.com/18642811/56654367-82767280-66c2-11e9-80b1-f8500b064658.png)

**Comment by peterjc123** [comment] 2019-04-24 11:03
Pybind11 cannot be compiled with NVCC 9.2 or up with VS above 15.4 on Windows. The workaround is:
1. Use <torch/script.h> instead of <torch/torch.h> or <torch/extension.h>
2. Use macro to limit the including of the header file `pybind11.h` to CPU only, that is 
```c++
#ifndef __CUDACC__
#include <pybind/pybind11.h>
#endif
```

**Comment by peterjc123** [comment] 2019-04-24 11:05
I'm going to close this because it is a duplicate of https://github.com/pytorch/pytorch/issues/11004.

**Closed by peterjc123** 2019-04-24 11:05 UTC
Labels: module: windows
