### ISSUE TITLE
torch v1.4.0 Unable to checkout '6aaaa4754fe2a7467c5f0584648ba47482caad7d' in submodule path 'third_party/fbgemm'

### ISSUE THREAD

**Issue by bigcmos** [pytorch/pytorch#35149] opened 2020-03-21 05:02 UTC
## 🐛 Bug

I'm trying to build pytorch from source at tag `v1.4.0`.

In tag `v1.4.0` I'm unable to init submodule `third_party/fbgemm`.

I get this error:
`Unable to checkout '6aaaa4754fe2a7467c5f0584648ba47482caad7d' in submodule path 'third_party/fbgemm'`

This was working earlier this morning and stopped working a few hours ago.  When I inspect the fbgemm repo and compare it to an old repo I had lying around it looks like the commit hashes have changed.

fbgemm repo from a few days ago:
```
* 66e415d 2019-11-25 | Optimized im2col for more shapes
* 6aaaa47 2019-11-20 (HEAD) | early return when block.row_size == 0 (#202)
* 672beab 2019-11-19 | Fused 8 bit Rowwise Sparse Lengths Sum (#198)
```
fbgemm repo now:
```
* b169d9d 2019-11-25 | Optimized im2col for more shapes
* 399ea14 2019-11-20 | early return when block.row_size == 0 (#202)
* bac2acf 2019-11-19 | Fused 8 bit Rowwise Sparse Lengths Sum (#198)
```

It looks like something has scrubbed the entire repo today causing everything to get rehashed: https://github.com/pytorch/FBGEMM/commits/399ea14

![image](https://user-images.githubusercontent.com/1166657/77219811-7bd0c500-6af6-11ea-8af5-a5ce09fa2b38.png)

This is the commit that no longer exists in the fbgemm tree that is still referenced by torch tagged at `v1.4.0`: https://github.com/pytorch/FBGEMM/commits/6aaaa4754fe2a7467c5f0584648ba47482caad7d

![image](https://user-images.githubusercontent.com/1166657/77219807-72475d00-6af6-11ea-8bd2-fb20ec6db612.png)

## To Reproduce

1. Clone the repo at v1.4.0
1. update the submodules recursively.

```
git clone https://github.com/pytorch/pytorch.git
cd pytorch
git fetch --tags
git checkout v1.4.0
git submodule update --init --recursive
```

Error:
```
Unable to checkout '6aaaa4754fe2a7467c5f0584648ba47482caad7d' in submodule path 'third_party/fbgemm'
```

You can also quickly reproduce this for just `third_party/fbgemm`:

```
$ git submodule update --init third_party/fbgemm
fatal: reference is not a tree: 6aaaa4754fe2a7467c5f0584648ba47482caad7d
Unable to checkout '6aaaa4754fe2a7467c5f0584648ba47482caad7d' in submodule path 'third_party/fbgemm'
```

## Expected behavior

All submodules should get updated.

## Environment

 - PyTorch Version (e.g., 1.0): v1.4.0
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): n/a
 - Python version: 3.5
 - CUDA/cuDNN version: cuda-10.0
 - GPU models and configuration: n/a
 - Any other relevant information: n/a

cc @ezyang @seemethere

**Comment by ddkalamk** [comment] 2020-03-22 15:26
Even pytorch v1.5.0-rc1 has similar issue with fbgemm.

**Comment by bigcmos** [comment] 2020-03-23 05:52
I'm currently working around this for now by checking out fbgemm @ `399ea14` manually before building.  This seems to work, but it would be great to have an official update of `v1.4.0`.

**Comment by yns88** [comment] 2020-03-23 19:16
I just pushed a new tag for v1.4.1 that should fix this issue. Can you check your build on that tag?

**Comment by bigcmos** [comment] 2020-03-23 20:55
Success.  Thank you!
```Submodule path 'third_party/fbgemm': checked out '399ea148f1403c100e6d601ec3587a621de96a84'```

**Comment by bigcmos** [comment] 2020-03-23 20:57
Oh

**Comment by seemethere** [comment] 2020-03-24 00:22
We probably won't update the tag and push a new tag with the updated `version.txt`. We're about to release 1.5.0, if you want to get the correct version while building I'd suggest setting the following environment variables:

- `PYTORCH_BUILD_VERSION=1.4.1`
- `PYTORCH_BUILD_NUMBER=1`

Going to go ahead an close this since we do have a valid tag to build off of.

Feel free to re-open if there are any other issues!

**Closed by seemethere** 2020-03-24 00:22 UTC
Labels: module: binaries, module: build, triaged

**Comment by bigcmos** [comment] 2020-03-24 03:05
ok.  That's a bummer.  I was already setting the `PYTORCH_BUILD_VERSION` manually, but was using that file to validate the version number.

I guess I can't trust that file so, I'll work around it.

**Comment by UlrichFreitag** [comment] 2020-04-02 12:13
FYI, I had the same issue when using the docker image of `pytorch/builder` (`pytorch/manylinux-cuda102`) when building a manywheel fork of LMS (https://github.com/pytorch/pytorch/issues/35633).

It seems that the issue is only appearing when using git 1.8.3.1. When installing git 2.16 it works just fine:

```bash
yum -y remove git*
yum -y install https://centos7.iuscommunity.org/ius-release.rpm
yum -y install git2u-all
```
