### ISSUE TITLE
Inductor pattern matching percolate_tags is slow

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#116581] opened 2024-01-01 00:48 UTC
### 🐛 Describe the bug

Reported at: https://github.com/pytorch/pytorch/issues/98434

cc @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @stas00 @jansel 

### Versions

main

**Comment by aorenste** [comment] 2024-01-11 20:47
@stas00 Are you able to provide a simple(ish) repro for this? The direct patch described to in the referenced issue is no longer applicable and I was unable to get torch.compile() to stall using that test.

**Comment by stas00** [comment] 2024-01-11 21:08
I'm no longer with HF, and it looks like the way torch.compile is integrated has been changed since I filed the report. Now it's `--torch_compile` flag that acted upon in Accelerate. So most likely this should do the trick:

```
diff --git a/src/transformers/training_args.py b/src/transformers/training_args.py
index 9acb9d78d..0bff9a100 100644
--- a/src/transformers/training_args.py
+++ b/src/transformers/training_args.py
@@ -1255,7 +1255,7 @@ class TrainingArguments:
         },
     )
     torch_compile: bool = field(
-        default=False, metadata={"help": "If set to `True`, the model will be wrapped in `torch.compile`."}
+        default=True, metadata={"help": "If set to `True`, the model will be wrapped in `torch.compile`."}
     )
     torch_compile_backend: Optional[str] = field(
         default=None,
```
we are making it the default so all the tests should now run with it activated.

Not sure if you also need to tweak `torch_compile_backend`

Please let me know if this helps.

**Comment by aorenste** [comment] 2024-01-11 21:13
I tried that change (and also set the `torch_compile_backend` to `"inductor"` as well).
Running
```
WANDB_DISABLED=1 pytest tests/trainer/test_trainer.py --tb=native -k test_adafactor_lr_none
```
completes in about 20s for me.

**Comment by stas00** [comment] 2024-01-11 21:18
great, so it probably means it has been fixed in torch, right?

**Comment by aorenste** [comment] 2024-01-11 21:38
Either fixed or this test doesn't tickle the issue anymore. I'm going to close this issue and we can reopen if it pops up again with a new repro.

**Comment by anijain2305** [comment] 2024-01-11 22:55
Made `percolate_tag` iterative .. just in case the problem is hidden - https://github.com/pytorch/pytorch/pull/117306

**Closed** 2024-01-12 07:52 UTC
Labels: triage review, good first issue, oncall: pt2, module: inductor, internal ramp-up task
