### ISSUE TITLE
NotImplementedError: Could not run 'aten::channel_shuffle' with arguments from the 'CUDA' backend.

### ISSUE THREAD

**Issue by beanduan22** [pytorch/pytorch#114030] opened 2023-11-18 23:16 UTC
### 🐛 Describe the bug
```python
import torch
import torchvision
import torchvision.transforms as transforms
import torch.nn as nn
import os
import torch.nn.functional as F
gpu_device = torch.device("cuda")
cpu_device = torch.device("cpu")
class PreprocessAndCalculateModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.channel_shuffle = nn.ChannelShuffle(groups=3)
    def forward(self, x):
        # = x.view(x.size(0), -1
        output = self.channel_shuffle(x)
        return output


real_inputs = torch.rand(2, 3, 8, 8)
model = PreprocessAndCalculateModel()
x = real_inputs
output_gpu = model.to(gpu_device)(x.cuda())
output_cpu = model.to(cpu_device)(x.cpu())
```
### Outputs
```
NotImplementedError: Could not run 'aten::channel_shuffle' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::channel_shuffle' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].
```

**Comment by malfet** [comment] 2023-11-24 15:25
Duplicate of https://github.com/pytorch/pytorch/issues/65325

**Closed** 2023-11-24 15:25 UTC
