### ISSUE TITLE
nn.init will give different result if a tensor is contiguous

### ISSUE THREAD

**Issue by DanielHesslow** [pytorch/pytorch#80041] opened 2022-06-22 16:00 UTC
### 🐛 Describe the bug

Depending on if a target tensor is contiguous or not `torch.nn.init` will give different results 

Minimal repro:
```python
a = torch.randn(64,64)
b = torch.randn(64,64).T

torch.manual_seed(42)
torch.nn.init.uniform_(a)
torch.manual_seed(42)
torch.nn.init.uniform_(b)

(a==b).all()  # False.
```

While this rarely will cause any issues, I did just spend a couple of hours debugging an issue stemming from this. And more importantly the current behavior is rather unexpected. 

Thanks

### Versions

PyTorch version: 1.11.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (conda-forge gcc 12.1.0-16) 12.1.0
Clang version: Could not collect
CMake version: version 3.22.4
Libc version: glibc-2.23

Python version: 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-142-generic-x86_64-with-glibc2.23
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration:
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000

Nvidia driver version: 465.19.01
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.4
[pip3] torch==1.11.0+cu113
[pip3] torchaudio==0.11.0+cu113
[pip3] torchvision==0.12.0+cu113
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.11.0+cu113             pypi_0    pypi
[conda] torchaudio                0.11.0+cu113             pypi_0    pypi
[conda] torchvision               0.12.0+cu113             pypi_0    pypi

**Comment by ngimel** [comment] 2022-06-22 18:29
Duplicate of #71090, this is expected behavior, there's no guarantee that random initialization of transposed tensors will match.

**Closed** 2022-06-23 14:01 UTC
