### ISSUE TITLE
[XPU] Failed to build libtorch program with XPUs

### ISSUE THREAD

**Issue by piDack** [pytorch/pytorch#140877] opened 2024-11-16 15:27 UTC
### 🐛 Describe the bug

I encountered an issue while attempting to build a libtorch program that utilizes XPUs. The build process terminated with errors, and I have not been able to resolve the issue despite following the available documentation and troubleshooting steps.
Below are my steps of operation：

1. Download xpu backend torch 2.5.1 by pip

```python
pip3 install torch --index-url https://download.pytorch.org/whl/test/xpu
```

2. CMake
```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(libtorch_trace)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED True)
Set(Torch_DIR "<path>\\cmake\\Torch")
find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}"))
include_directories("C:/Users/Public/yhl/miniconda/envs/torchxpu/Lib/site-packages/torch/include/torch/csrc/api/include")
add_executable(${PROJECT_NAME} test.cpp)
target_link_libraries(${PROJECT_NAME} ${TORCH_LIBRARIES})
set_property(TARGET ${PROJECT_NAME} PROPERTY CXX_STANDARD 17)
```

3. Cpp code
```
#include <torch/torch.h>
#include <iostream>
#include <chrono>
#include <thread>
#include <torch/xpu.h>

int main() {
  printf("xpu is alive %d\n",torch::xpu::is_available());
}
```

The error

```
CMake Error at C:/Users/Public/yhl/miniconda/envs/torchxpu/Lib/site-packages/torch/share/cmake/Caffe2/Caffe2Targets.cmake:106 (set_target_properties):
  The link interface of target "torch_xpu_library" contains:

    torch::xpurt

  but the target was not found.  Possible reasons include:

    * There is a typo in the target name.
    * A find_package call is missing for an IMPORTED target.
    * An ALIAS target is missing.

Call Stack (most recent call first):
  C:/Users/Public/yhl/miniconda/envs/torchxpu/Lib/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:114 (include)
  C:/Users/Public/yhl/miniconda/envs/torchxpu/Lib/site-packages/torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:8 (find_package)
```

I tried using CPU LibTorch with the aforementioned program and CMakeLists, and it works.How to fix it?

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 专业版 (10.0.26100 64 位)
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.31.0
Libc version: N/A

Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] (64-bit runtime) 
Python platform: Windows-10-10.0.26100-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Name: Intel(R) Core(TM) Ultra 9 288V
Manufacturer: GenuineIntel
Family: 775
Architecture: 9
ProcessorType: 3
DeviceID: CPU0
CurrentClockSpeed: 3300
MaxClockSpeed: 3300
L2CacheSize: 14336
L2CacheSpeed: None
Revision: None

Versions of relevant libraries:
[pip3] numpy==2.1.3
[pip3] optree==0.13.1
[pip3] torch==2.5.1+xpu
[conda] Could not collect

cc @jbschlosser @gujinghui @EikanWang @fengyuan14 @guangyey

**Comment by dvrogozh** [comment] 2024-11-18 21:37
@piDack : Please, attach full log from cmake. Package checks stage is important to look at.

`torch::xpurt` is defined in https://github.com/pytorch/pytorch/blob/v2.5.1/cmake/public/xpu.cmake. Note that there is a prerequisite on line 9:
https://github.com/pytorch/pytorch/blob/a8d6afb511a69687bbb2b7e88a3cf67917e1697e/cmake/public/xpu.cmake#L9-L13 

If sycl toolkit won't be found, then `torch::xpurt` won't be defined. I guess you might not have SYCL development environment available or not activated. Hence this issue. Try to follow https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html to install it.

**Comment by piDack** [comment] 2024-11-19 03:37
> @piDack : Please, attach full log from cmake. Package checks stage is important to look at.
> 
> `torch::xpurt` is defined in https://github.com/pytorch/pytorch/blob/v2.5.1/cmake/public/xpu.cmake. Note that there is a prerequisite on line 9:
> 
> https://github.com/pytorch/pytorch/blob/a8d6afb511a69687bbb2b7e88a3cf67917e1697e/cmake/public/xpu.cmake#L9-L13
> 
> If sycl toolkit won't be found, then `torch::xpurt` won't be defined. I guess you might not have SYCL development environment available or not activated. Hence this issue. Try to follow https://www.intel.com/content/www/us/en/developer/articles/tool/pytorch-prerequisites-for-intel-gpu/2-5.html to install it.

Thank you for your response. I have already installed the environment as mentioned. It appears that specifying the compiler as icx is necessary(cmake -DCMAKE_C_COMPILER=cl -DCMAKE_CXX_COMPILER=icx -B build -G Ninja), and I have tried this approach which works.

However, after the compilation is complete, the resulting program does not seem to be able to directly use to(at::XPU) like with the CUDA backend. It is necessary to first execute at::detail::getXPUHooks().initXPU(); before using the XPU. Additionally, before calling initXPU, it is essential to ensure that at::detail::empty_xpu is called.This is very strange.

```
printf("xpu device %d\n",torch::xpu::is_available());   //output is 0
  printf("xpu device %d\n",at::xpu::is_available());   //output is 1
  // torch::Tensor out = torch::randn({3,3}).xpu(); //will abort() in windows11
  torch::Tensor out = at::detail::empty_xpu({0}, c10::TensorOptions().dtype(at::kFloat).device(at::kXPU)); //work great
  printf("context have xpu %d\n",at::detail::getXPUHooks().hasXPU()); //output 1
//if not  run at::detail::empty_xpu will abort
  at::detail::getXPUHooks().initXPU(); 
  torch::Tensor hihi = torch::randn({3,3}).to(at::kXPU);
  std::this_thread::sleep_for(std::chrono::minutes(1));
  printf("has xpu %d\n",c10::xpu::device_count());
```

Here is all of my code. Although it seems odd to call empty_xpu at the beginning, if I remove it, the entire program will abort.

**Comment by guangyey** [comment] 2024-11-21 14:26
Thank you very much. The root cause is that XPU is not initialized automatically when calling empty_xpu. We will address this issue and provide you with an update soon.

**Comment by guangyey** [comment] 2024-11-22 04:07
@piDack We have prepared a [PR](https://github.com/intel/torch-xpu-ops/pull/1115) to fix the initialization issue. Once this PR is merged, we will update the commit pin in `third_party/xpu.txt`.

**Closed** 2024-11-25 01:35 UTC
Labels: module: cpp, triaged, module: xpu
