### ISSUE TITLE
Fail to find unused parameters when find_unused_parameters is True

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#41324] opened 2020-07-12 20:59 UTC
## 🐛 Bug

For a model like this:
```
class ToyModel(nn.Module):
    def __init__(self):
        super(ToyModel, self).__init__()
        self.net1 = nn.Linear(10, 5, bias=False)
        self.bias = nn.Parameter(torch.zeros(5))
        self.net1.bias = self.bias
        self.net2 = nn.Linear(10, 5)

    def forward(self, x):
        return self.net2(x)
```
(In this model, net1 is not used.)
When running ddp with this model (when find_unused_parameters=True), I got error: 
```
RuntimeError: Expected to have finished reduction in the prior iteration before starting a new one. This error indicates that your module has parameters that were not used in producing loss. You can enable unused parameter detection by (1) passing the keyword argument `find_unused_parameters=True` to `torch.nn.parallel.DistributedDataParallel`; (2) making sure all `forward` function outputs participate in calculating loss. If you already have done the above two steps, then the distributed data parallel module wasn't able to locate the output tensors in the return value of your module's `forward` function. Please include the loss function and the structure of the return value of `forward` of your module when reporting this issue (e.g. list, dict, iterable).
```

The trigger seems to be this line:
```
self.net1.bias = self.bias
```

I am not sure why this situation cannot handled by ddp. BTW, this kind of "artificial" definition is from [link](https://github.com/huggingface/transformers/blob/7fad617dc1fc681a7f5da5e0172c8b83f4bf0024/src/transformers/modeling_bert.py#L520).

## To Reproduce

https://gist.github.com/ruotianluo/94f318cbf2612850ba12f6e7ad7b82f9

The code is modified from https://pytorch.org/tutorials/intermediate/ddp_tutorial.html.

## Expected behavior

The unused parameters should be handled when find_unused_parameter = True

## Environment
PyTorch version: 1.5.1+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000
GPU 2: Quadro RTX 8000
GPU 3: Quadro RTX 8000

Nvidia driver version: 450.57
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.4
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.4

Versions of relevant libraries:
[pip3] numpy==1.13.3
[pip3] torch==1.3.0
[pip3] torchvision==0.4.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] pytorch-lightning         0.8.5.dev0                dev_0    <develop>
[conda] torch                     1.5.1+cu101              pypi_0    pypi
[conda] torchtext                 0.5.0                    pypi_0    pypi
[conda] torchvision               0.6.1+cu101              pypi_0    pypi

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski

**Comment by rohan-varma** [comment] 2020-07-14 02:20
@ruotianluo, Thanks for reporting this error!

I can confirm that [this script](https://gist.github.com/rohan-varma/8a2c8575d192307e3d22d5b89344afe6) can repro the issue on current master. From some basic logging, it seems that if we add `        self.net1.bias = self.bias` to the model which triggers this error, a few things happen:
- total no. of params in the model goes from 4 to 5
- We expect to mark 3 params as unused, but only mark 2
- the size of the internal `func_` (i.e. the number of distinct grad accumulators) stays at 4, instead of 5 (which is what would happen if they have the same no. of parameters). This seems like it is because `self.net1.bias` and `self.bias` are names for the same underlying variable, so they share the same `grad_accumulator`. In reducer.cpp we have the following line:
`func_[grad_accumulator.get()] = index;` , which means we can overwrite the mapping of grad accumulator to index, even if a mapping already exists. 

This means that in the following logic:

```
  for (const auto& it : func_) {
    // If the accumulator function is present in the graph, we know
    // a gradient will be computed for the corresponding parameter.
    if (seen.count(it.first) > 0) {
      continue;
    }

    unused_parameters_.push_back(it.second);
  }
}
```
we would unfortunately not go through all variables, since the assumption that there is a 1:1 mapping of grad_accumulator to variable_index is no longer True.

As a work around, it looks like you can simply copy the parameter: `self.net1.bias = nn.Parameter(self.bias.clone())`, and now the grad_accumulators would be different. I also think we can fix this in the reducer by fixing the mapping logic.

**Comment by ruotianluo** [comment] 2020-07-19 15:35
The fact that total no. of params in the model goes from 4 to 5 seems a bug to me. If you run .parameters(), it correctly returns that the model only have 4 parameters.

**Comment by rohan-varma** [comment] 2020-11-17 21:43
Fixed by https://github.com/pytorch/pytorch/pull/46755

**Closed by rohan-varma** 2020-11-17 21:43 UTC
Labels: oncall: distributed, triaged
