### ISSUE TITLE
[BUG] python3.8 ---- cannnot convert nullptr to Py_ssize_t

### ISSUE THREAD

**Issue by ygwangthu** [pytorch/pytorch#29162] opened 2019-11-04 23:43 UTC
compiler error with python3.8, but works with python3.7.
the error information is: cannot convert nullptr to Py_ssize_t for the file with  /*tp_print*/:

For example: 

> torch\csrc\Dtype.cpp --> line65, nullptr /*tp_print*/

could you help to solve this bug for all the files with /*tp_print*/ ?

**Comment by VitalyFedyunin** [comment] 2019-11-05 17:38
Hello! 

Can you please provide mode details such as:

1)

Instructions you are using to compile

2)

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by vishwakftw** [comment] 2019-11-06 01:37
This is a duplicate of https://github.com/pytorch/pytorch/issues/28060.

**Comment by yf225** [comment] 2019-11-07 17:01
Since this is a duplicate and https://github.com/pytorch/pytorch/issues/28060 has more information, I am going to close this one.

**Closed by yf225** 2019-11-07 17:01 UTC
Labels: module: pybind, triaged
