### ISSUE TITLE
aminmax increases dimension from 0-dim to 1-dim when given scalar inputs and keepdim.

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#64008] opened 2021-08-26 07:06 UTC
```
>>> torch.aminmax(torch.randn(()), dim=0, keepdim=True)
torch.return_types.aminmax(
min=tensor([1.9132]),
max=tensor([1.9132]))

>>> torch.nansum(torch.randn(()), dim=0, keepdim=True)
tensor(0.6512)

>>> torch.argmax(torch.randn(()), dim=0, keepdim=True)
tensor(0)
```

We should probably make this consistent.

`torch.aminmax` is increasing the dimension from a 0-dim tensor to a 1-dim tensor.

cc @heitorschueroff

**Comment by ngimel** [comment] 2023-03-08 19:12
Duplicate of #96042

**Closed by ngimel** 2023-03-08 19:12 UTC
Labels: triaged, module: reductions
