### ISSUE TITLE
[Autograd] `Variable._execution_engine.queue_callback` swallows error message

### ISSUE THREAD

**Issue by awgu** [pytorch/pytorch#112438] opened 2023-10-30 20:42 UTC
```
from typing import Any, Callable

import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.distributed.utils import _apply_to_tensors


def hook(*args, **kwargs):
    assert 0, "Hello world!"


def register_backward_hook(output: Any, hook: Callable):
    if not torch.is_grad_enabled():
        return output

    def _register_hook(tensor: torch.Tensor):
        if tensor.requires_grad:
            tensor.register_hook(
                lambda *args, **kwargs: Variable._execution_engine.queue_callback(hook)
            )
        return tensor

    return _apply_to_tensors(_register_hook, output)


model = nn.Sequential(
    nn.Linear(3, 3, device="cuda"), nn.ReLU(), nn.Linear(3, 3, device="cuda")
)
out = model(torch.randn(2, 3, device="cuda"))
register_backward_hook(out, hook)
out.sum().backward()
```

`Hello world!` is not printed:
```
Traceback (most recent call last):
  File "/data/users/andgu/sandbox/non_distributed/repro_autograd_error.py", line 32, in <module>
    out.sum().backward()
  File "/data/users/andgu/pytorch/torch/_tensor.py", line 503, in backward
    torch.autograd.backward(
  File "/data/users/andgu/pytorch/torch/autograd/__init__.py", line 254, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
SystemError: <built-in method run_backward of torch._C._EngineBase object at 0x7f762e58bd40> returned NULL without setting an exception
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by albanD** [comment] 2023-10-30 20:52
I cannot reproduce with my local build:
```
$ python foo.py 
Traceback (most recent call last):
  File "/home/albandes/local/pytorch/3.11_debug_source/test/foo.py", line 32, in <module>
    out.sum().backward()
  File "/home/albandes/local/pytorch/3.11_debug_source/torch/_tensor.py", line 503, in backward
    torch.autograd.backward(
  File "/home/albandes/local/pytorch/3.11_debug_source/torch/autograd/__init__.py", line 254, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/albandes/local/pytorch/3.11_debug_source/test/foo.py", line 9, in hook
    assert 0, "Hello world!"
AssertionError: Hello world!
```

(I had to remove `_apply_to_tensor` as importing distributed crashes when not built

**Comment by albanD** [comment] 2023-10-30 21:02
Actually also moved it to cpu which disables the use of worker thread and leads to this problem!
Working on a fix

**Comment by awgu** [comment] 2023-10-30 21:03
Thanks @albanD! This is not high priority, so please take your time!

**Comment by awgu** [comment] 2023-11-05 14:53
I realized this should be a duplicate of https://github.com/pytorch/pytorch/issues/75750

**Comment by albanD** [comment] 2023-11-06 22:56
Ok closing this as duplicate then.

**Closed by albanD** 2023-11-06 22:56 UTC
Labels: module: autograd, triaged
