### ISSUE TITLE
Pytorch Data Distributed Training across 8 H100 randomly gets stuck

### ISSUE THREAD

**Issue by raeudigerRaeffi** [pytorch/pytorch#135703] opened 2024-09-11 16:08 UTC
### 🐛 Describe the bug

Hi I have a script that runs with the DataParralell trainer on a machine with 8 H100 GPUs (aws p5 vm). When we run the script it starts to randomly get stuck forever at some iteration relatively late in the process (between 2000 - 4000th iteration).
We start the script with the following command:

accelerate launch src/compactifai_back/healing/scripts/fine_tune_accelerate.py --config_file src/compactifai_back/healing/configs/mixtral_8x7b/config.yaml
The gpus are only at 30% memory occupied and util is at 0%.
The stack trace of the relevant processes looks the following:

 pgrep -P $(pgrep -o accelerate) | xargs -I {} py-spy dump --pid {}
Process 39: /usr/bin/python3.10 -u src/compactifai_back/healing/scripts/fine_tune_accelerate.py --config_file src/compactifai_back/healing/configs/mixtral_8x7b/config.yaml
Python v3.10.12 (/usr/bin/python3.10)

Thread 39 (idle): "MainThread"
    backward (torch/autograd/__init__.py:266)
    backward (torch/_tensor.py:522)
    backward (deepspeed/runtime/fp16/loss_scaler.py:63)
    backward (deepspeed/runtime/zero/stage3.py:2213)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    backward (deepspeed/runtime/engine.py:1976)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    backward (accelerate/utils/deepspeed.py:166)
    backward (accelerate/accelerator.py:2126)
    training_loop (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:410)
    training_function (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:540)
    main (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:583)
    <module> (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:587)
Thread 930 (idle): "Thread-1"
    wait (threading.py:324)
    wait (threading.py:607)
    run (tqdm/_monitor.py:60)
    _bootstrap_inner (threading.py:1016)
    _bootstrap (threading.py:973)
Thread 4067 (active)
    all_gather_into_tensor (torch/distributed/distributed_c10d.py:2709)
    wrapper (torch/distributed/c10d_logger.py:72)
    all_gather_into_tensor (deepspeed/comm/torch.py:219)
    _fn (torch/_dynamo/eval_frame.py:489)
    all_gather_into_tensor (deepspeed/comm/comm.py:305)
    log_wrapper (deepspeed/comm/comm.py:117)
    allgather_fn (deepspeed/comm/comm.py:320)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    _dist_allgather_fn (deepspeed/runtime/zero/partition_parameters.py:93)
    all_gather_coalesced (deepspeed/runtime/zero/partition_parameters.py:1217)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    __all_gather_params_ (deepspeed/runtime/zero/partitioned_param_coordinator.py:463)
    __all_gather_params (deepspeed/runtime/zero/partitioned_param_coordinator.py:434)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    fetch_sub_module (deepspeed/runtime/zero/partitioned_param_coordinator.py:385)
    decorate_context (torch/utils/_contextlib.py:115)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    _fn (torch/_dynamo/eval_frame.py:489)
    pre_sub_module_backward_function (deepspeed/runtime/zero/parameter_offload.py:474)
    decorate_context (torch/utils/_contextlib.py:115)
    _run_before_backward_function (deepspeed/runtime/zero/parameter_offload.py:339)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    backward (deepspeed/runtime/zero/parameter_offload.py:358)
    apply (torch/autograd/function.py:289)
    backward (torch/autograd/__init__.py:266)
    backward (torch/utils/checkpoint.py:320)
    apply (torch/autograd/function.py:289)
Thread 4069 (idle)
Thread 4070 (idle)
Thread 4071 (idle)
Thread 4072 (idle)
Thread 4073 (idle)
Thread 4074 (idle)
Thread 4075 (idle)
Process 40: /usr/bin/python3.10 -u src/compactifai_back/healing/scripts/fine_tune_accelerate.py --config_file src/compactifai_back/healing/configs/mixtral_8x7b/config.yaml
Python v3.10.12 (/usr/bin/python3.10)

Thread 40 (idle): "MainThread"
    backward (torch/autograd/__init__.py:266)
    backward (torch/_tensor.py:522)
    backward (deepspeed/runtime/fp16/loss_scaler.py:63)
    backward (deepspeed/runtime/zero/stage3.py:2213)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    backward (deepspeed/runtime/engine.py:1976)
    wrapped_fn (deepspeed/utils/nvtx.py:15)
    backward (accelerate/utils/deepspeed.py:166)
    backward (accelerate/accelerator.py:2126)
    training_loop (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:410)
    training_function (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:540)
    main (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:583)
    <module> (src/compactifai_back/healing/scripts/fine_tune_accelerate.py:587)
Thread 924 (idle): "Thread-1"
    wait (threading.py:324)
    wait (threading.py:607)
    run (tqdm/_monitor.py:60)
    _bootstrap_inner (threading.py:1016)
    _bootstrap (threading.py:973)
Thread 4040 (idle)
Thread 4044 (active)
    all_gather_into_tensor (torch/distributed/distributed_c10d.py:2709)
    wrapper (torch/distributed/c10d_logger.py:72)
    all_gather_into_tensor (deepspeed/comm/torch.py:219)

### Versions

# Machine Learning and Deep Learning Libraries
torch==2.4.1 --index-url https://download.pytorch.org/whl/cu121  # Deep learning framework
torchvision==0.17.1        # Computer vision library for PyTorch
deepspeed==0.15.1          # Deep learning optimization library
accelerate==0.34.2         # Simplifies training and inference
trl==0.9.6                 # Training language models with reinforcement learning
peft==0.11.1               # Parameter-efficient fine-tuning library
bitsandbytes               # 8-bit optimizers and quantization
cuquantum-python==23.10.0  # GPU-accelerated quantum computing

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by fegin** [comment] 2024-09-12 15:58
@raeudigerRaeffi the information you provide is not enough for further debugging, like what how do you wrap the model? What parallelisms do you use? You mentioned that you are using DataParallel, the the error message seems to fail in `all_gather_into_tensor` which is not used by DDP or DataParallel. Please identify and provide more detail if you think the issue is related to PyTorch DDP.

**Comment by wconstab** [comment] 2024-09-12 21:38
> deepspeed/runtime/zero/parameter_offload.py:339)

this may be a deepspeed issue- maybe better to close this and file an issue on https://github.com/microsoft/DeepSpeed

**Comment by fegin** [comment] 2024-09-12 21:51
I'll close the issue for now. Feel free to reopen the issue if the root cause is suspected to be PyTorch distributed library related.

**Closed by fegin** 2024-09-12 21:51 UTC
Labels: oncall: distributed
