### ISSUE TITLE
torch.dot bug

### ISSUE THREAD

**Issue by vlasenkov** [pytorch/pytorch#1822] opened 2017-06-16 12:51 UTC
Built Torch from source with:
```
MACOSX_DEPLOYMENT_TARGET=10.9 CC=clang CXX=clang++ python setup.py build develop
```
running:
```
test/run_test.sh
```
getting:
```
FAIL: test_dot (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 35, in test_dot
    self.assertEqual(res1, res2)
  File "/Users/leonidvlasenkov/pytorch/test/common.py", line 211, in assertEqual
    super(TestCase, self).assertEqual(x, y, message)
AssertionError: 0.0 != -15.408409330303812 : 
```
OS X 10.12.4.

From interpreter:
```
>>> v1 = torch.randn(100).float()
>>> v2 = torch.randn(100).float()
>>> torch.dot(v1, v2)
0.0
```

**Comment by soumith** [comment] 2017-06-16 13:49
is this regression of the just-merged `dot` PR @gchanan ?

**Comment by gchanan** [comment] 2017-06-16 15:14
I couldn't reproduce it on linux, I'll try on MacOSX later.

**Comment by vlasenkov** [comment] 2017-06-19 20:42
I could try to solve this problem if you lack free hands. Just need to be sure that the work won't done twice.

**Comment by soumith** [comment] 2017-06-19 20:50
please do, we're actually not able to reproduce this.

**Comment by vlasenkov** [comment] 2017-06-21 16:23
Found these:

**Comment by vlasenkov** [comment] 2017-06-21 16:41
- Dot fails [here](https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THBlas.c#L174). `sdot_` just returns zero.
- Also found this in `./torch/lib/build/TH/CMakeFiles/CMakeError.log`:
```
/Library/Developer/CommandLineTools/usr/bin/cc    -DUSE_SSE4_1 -msse4.2 -DUSE_SSE4_2 -DUSE_AVX2 -DUSE_AVX   -DUSE_SSE3   -DUSE_SSE2  -DTH_INDEX_BASE=0 -I/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/include   -I/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/include/TH -I/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/include/THC   -I/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/include/THS -I/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/include/THCS   -I/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/include/THPP  -L/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/lib  -Qunused-arguments -Wl,-rpath,@loader_path -std=gnu99 -DHAVE_GCC_GET_CPUID -DBLAS_F2C_FLOAT_WORKS -Wl,-search_paths_first -Wl,-headerpad_max_install_names   CMakeFiles/cmTC_5cb31.dir/src.c.o  -o cmTC_5cb31  -framework Accelerate 
ld: warning: directory not found for option '-L/Users/leonidvlasenkov/pytorch/torch/lib/tmp_install/lib'

Return value: 1
Source file was:

#include <stdlib.h>
#include <stdio.h>
float x[4] = { 1, 2, 3, 4 };
float y[4] = { .1, .01, .001, .0001 };
int four = 4;
int one = 1;
extern float sdot_();
int main() {
  int i;
  double r = sdot_(&four, x, &one, y, &one);
  exit((float)r != (float).1234);
}
Determining if the function malloc_usable_size exists failed with the following output:
Change Dir: /Users/leonidvlasenkov/pytorch/torch/lib/build/TH/CMakeFiles/CMakeTmp
```
Are there any  ideas?

**Comment by pavanky** [comment] 2017-06-21 17:56
If it is failing in a standalone file, it could be a problem with the Accelerate frame work.

**Comment by vlasenkov** [comment] 2017-06-21 18:31
@pavanky, it seems that there is no `sdot_` in Accelerate framework...

**Comment by vlasenkov** [comment] 2017-06-21 18:38
[Here](https://github.com/tenomoto/dotwrp) is one possible solution. Or we just use cblas API.

**Comment by apaszke** [comment] 2017-06-21 18:55
@soumith has some opinions on cblas API

**Closed** 2017-07-13 07:10 UTC
