### ISSUE TITLE
Python Pickle Serialization Mangles NllLossBackward Objects in Tensor Objects

### ISSUE THREAD

**Issue by dkostecki** [pytorch/pytorch#48697] opened 2020-12-02 06:52 UTC
## 🐛 Bug
Python Pickle serialization mangles NllLossBackward objects in Tensor objects without throwing an error, but attempting to serialize the grad_fn object encapsulated in the Tensor object throws a TypeError. This behavior seems inconsistent.

## To Reproduce

torch.nn.functional.nll_loss returns Tensor objects which contain a loss value as well as a grad_fn object. Pickle does not throw an exception when serializing (dumps) the Tensor object. When loading (loads) the serialized data, the grad_fn object is lost and it becomes a requires_grad object. 

However, if one attempts to serialize the grad_fn object encapsulated in the Tensor object, Pickle then throws a TypeError (TypeError: cannot pickle 'NllLossBackward' object). This behavior seems inconsistent. Perhaps serialization of NllLossBackward objects should be supported or their encapsulating Tensors should also throw a TypeError.

This behavior should be easily reproducible.

## Expected behavior

Either Pickle should also throw a TypeError for the whole object, or serialization of the NllLossBackward object should be supported.
## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Pop!_OS 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 2.7 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.7.0
[pip3] torchvision==0.8.1
[conda] Could not collect

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @mruberry

**Comment by mruberry** [comment] 2020-12-09 08:48
Thank you for reporting this issue, @dkostecki, that does seem odd.

**Comment by albanD** [comment] 2020-12-09 20:41
Hi,

I think this is expected behavior. Serialization is just not a differentiable operation in pytorch (and so autograd related metadata of the Tensor may change when serializing).
The gist here I think is:
- We don't want to forbid serialization of Tensors that require gradients or are not leafs to allow users to save all the Tensors they want
- When de-serialized, because the op is not differentiable, it is expected that the grad_fn is None.

A simple repro if people are interested:
```python
import torch

a = torch.rand(2, requires_grad=True)
b = a.clone()
print(b)

torch.save(b, "foo.pth")
c = torch.load("foo.pth")
print(c)
```
Prints
```
tensor([0.2270, 0.5702], grad_fn=<CloneBackward>)
tensor([0.2270, 0.5702], requires_grad=True
```

**Comment by albanD** [comment] 2021-01-21 23:16
Closing this as expected behavior.
And there is no plan right now to make a "differentiable serialization".

Feel free to re-open if you have further questions.

**Closed by albanD** 2021-01-21 23:16 UTC
Labels: module: autograd, module: pickle, module: serialization, triaged
