### ISSUE TITLE
torch.cdist Tried to allocate huge amount of GPU memory during the forward process

### ISSUE THREAD

**Issue by HilbertXu** [pytorch/pytorch#57720] opened 2021-05-06 10:33 UTC
## To Reproduce

>a=torch.randn(2,80000,5, device="cuda", requires_grad=True)
>b=torch.randn(2,80000,5, device="cuda", requires_grad=True)
>c=torch.cdist(a,b)
>c.sum().backward()

## Expected behavior

normally calculate L1-norm distance between input tensors

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.0
 - OS (e.g., Linux): Ubuntu 16.04 LTS
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.8
 - CUDA/cuDNN version: CUDA 10.2 cuDNN 7.6.5(8.1.1)
 - GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX

cc @heitorschueroff

**Comment by albanD** [comment] 2021-05-06 13:19
Hi,

Isn't this expected? The cdist, as mentioned in the doc here: https://pytorch.org/docs/stable/generated/torch.cdist.html?highlight=cdist#torch.cdist
Takes two Tensor of size BxPxM and BxRxM and outputs a Tensor of size BxPxR.
So in your case, the output is expected to be of size 2x80000x80000 so that's not surprising that you're getting an OOM.

Did you meant to use a different function maybe?

**Comment by HilbertXu** [comment] 2021-05-07 05:00
Hi @albanD ,

Thanks for your reply!

Sorry for my mis-description, yes, I know the result is expected. I am just wondering if there exists any replacement of torch.cdist to calculate distance between tensors of such a big size so that OOM can be avoided.

**Comment by albanD** [comment] 2021-05-10 14:15
I don't think you can no. The problem is that just the Tensor that contains the result is 300+GB (if you use float32). So you can't even store the Tensor containing the result.

If you need to compute it, you will have to compute it piece by piece.

I'm closing this as this is not a bug or feature request but feel free to ask follow up question here or on the forum: https://discuss.pytorch.org/

**Closed by albanD** 2021-05-10 14:15 UTC
Labels: module: distance functions, module: reductions, triaged
