### ISSUE TITLE
[CUDA] Errors when building with cuda 12.2 

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#110624] opened 2023-10-05 16:56 UTC
# Summary

While attempting to build PyTorch from source with Cudatoolkit 12-2 I ran into a number of issuess:

``` Shell
In file included from /home/drisspg/meta/pytorch/aten/src/ATen/cuda/CUDASparseDescriptors.cpp:4:
/home/drisspg/meta/pytorch/aten/src/ATen/cuda/CUDASparseDescriptors.h:101:46: error: 'cusparseDestroyBsrsv2Info' is deprecated: The routine will be removed in the next major release [-Werror,-Wdeprecated-declarations]
    : public CuSparseDescriptor<bsrsv2Info, &cusparseDestroyBsrsv2Info> {
                                             ^
/usr/local/cuda-12.2/include/cusparse.h:468:1: note: 'cusparseDestroyBsrsv2Info' has been explicitly marked deprecated here
CUSPARSE_DEPRECATED
^
/usr/local/cuda-12.2/include/cusparse.h:108:12: note: expanded from macro 'CUSPARSE_DEPRECATED'
         [[deprecated("The routine will be removed in the next major release")]]
```

This is confirmed here: https://docs.nvidia.com/cuda/cusparse/#cusparsedestroybsrsv2info-deprecated
Interestingly they don't provide a path forward.

### Potential issues with Symbool
``` Shell
en/src/ATen/cuda/cub-RadixSortKeys.cu.o
/home/drisspg/meta/pytorch/c10/core/SymBool.h:66:8: error: no viable conversion from returned value of type 'optional<typename std::decay<const bool &>::type>' to function return type 'optional<bool>'
return c10::make_optional(data_);
```

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @malfet @seemethere @ptrblck

**Comment by amjames** [comment] 2023-10-05 21:25
That is concerning... It looks like the legacy API for BSR solve is deprecated, but it does not seem like the [generic solve](https://docs.nvidia.com/cuda/cusparse/#cusparsespsv) supports BSR yet. 

If this is a documentation mix up and BSR is supported by the generic API we will have to swap the legacy descriptors here for the generic ones (conditional on cuda 12.2). If this is not an oversight and they are just dropping the functionality all together we will have to figure something else out.

**Comment by cpuhrsch** [comment] 2023-11-06 20:26
Closing this since we've identified the root cause and are tracking the resolution in https://github.com/pytorch/pytorch/issues/113053

**Closed by cpuhrsch** 2023-11-06 20:26 UTC
Labels: module: sparse, module: build, module: cuda, triaged
