### ISSUE TITLE
torch.jit.script gives incorrect result when inplace operations are used on namedtuple elements

### ISSUE THREAD

**Issue by davisking** [pytorch/pytorch#36031] opened 2020-04-04 20:51 UTC
## 🐛 Bug

Using an inplace operation on an element of a named tuple, in a number of cases, causes `torch.jit.script` to generate an incorrect script.

## To Reproduce

Here is a simple torch program that reproduces the problem.  Note that the `Foo` module behaves differently when run with and without scripting.

```
import torch
from collections import namedtuple

Outputs = namedtuple('Outputs', ['val'])

class Foo(torch.nn.Module):
    def __init__(self):
        super(Foo, self).__init__()

    def forward(self, x, y):
        out = Outputs(val = x + y)

        # This statement doesn't execute when this model is converted to torchscript
        out.val.add_(x)
        return out

x = torch.tensor([1.0])
y = torch.tensor([3.0])

net = Foo()
print('This gives the correct output of 5:', net(x,y))
net = torch.jit.script(net)
print('But when using the torchscripted version of net you get this wrong output (gives 4):',net(x,y))

# Looking at the torchscript you can see that out.val.add_(x) has been elided.  This prints:
#  def forward(self,
#      x: Tensor,
#      y: Tensor) -> __torch__.Outputs:
#    out = __torch__.Outputs(torch.add(x, y, alpha=1),)
#    return out
print(net.code)
```

Alternatively, if you do this:
```
    def forward(self, x):
        out = Outputs(val = x)
        out.val.add_(x)
        return out
```
You get a slightly different problem where the correct output is 2, but the torchscript model outputs 4.  So it's not the case that inplace operations are always being elided.  Sometimes they are executed too many times.

## Environment

```
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.15.4

Python version: 3.5
Is CUDA available: No
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 960M
Nvidia driver version: 410.104
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.0

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

 - PyTorch Version: 1.4.0 
 - OS (e.g., Linux): Ubuntu 16.04.6 LTS
 - How you installed PyTorch (`conda`, `pip`, source): `pip3 install torch`
 - Python version: 3.5

cc @suo

**Comment by ak-source** [comment] 2020-04-06 00:46
Hello,
I reproduced the first issue in 1.4.0, but it seems to be fixed in recent master builds. Also, tuples are supposed to be immutable, so one may even find 1.4.0 behaviour somewhat reasonable, but of course it is inconsistent with python. Note that identical "script class" mutates without issues:
```
@torch.jit.script
class OutputsC:
    def __init__(self, val):
        self.val = val
```
Your second code snippet never copies a tensor, so you probably just testing jit mode with mutated x tensor.

**Comment by davisking** [comment] 2020-04-06 02:56
That's awesome that the first case is fixed already.  Is the second though?  In the second example the jit output does not match the python output.  Try running it.

**Comment by ak-source** [comment] 2020-04-06 12:24
That's because x in global scope changes to 2 after first call. Otherwise, a bit suprisingly, second code compiles correctly even in 1.4.0.

**Comment by eellison** [comment] 2020-04-06 18:48
Hi @davisking, thanks for the issue & succinct repros. As @ak-source mentioned, I tried running your examples on master and got the correct answers. I'm going to close the issue, if you try this on a newer pytorch version and still have a failure feel free to reopen.

**Closed by eellison** 2020-04-06 18:48 UTC
Labels: jit

**Comment by davisking** [comment] 2020-04-07 01:39
No problem.  I just tried the nightly build and it indeed fixes my first example, but the second example I gave still gives the wrong output.   To be specific, run this little program on master pytorch:

```
import torch
from collections import namedtuple

Outputs = namedtuple('Outputs', ['val'])

class Foo(torch.nn.Module):
    def __init__(self):
        super(Foo, self).__init__()

    def forward(self, x):
        out = Outputs(val = x)
        out.val.add_(x)
        return out

x = torch.tensor([1.0])

net = Foo()
print('This gives the correct output of 2:', net(x))
net = torch.jit.script(net)
print('This gives a value of 4:',net(x))
```
And you will see there is still a problem as the outputs differ, and are wrong, with the jit.

I installed the nightly build via `pip3 install torch_nightly -f https://download.pytorch.org/whl/nightly/cu100/torch_nightly.html --user`.

**Comment by davisking** [comment] 2020-04-07 01:42
Er, wait, duh, that second example just modifies the input `x`.  Seems like it's all good :)

**Comment by davisking** [comment] 2020-04-07 01:43
Indeed.  I played around with master and it's all fixed already.  Nice :)
