### ISSUE TITLE
matrix multiplication sometimes can launch very unoptimized kernels

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#16594] opened 2019-01-31 03:11 UTC
## 🐛 Bug

I have a matmul where 
(4, 4) matmul (4, 400K)

non-contiguous tensor takes 40ms
contiguous tensor takes 0.5ms

Profiler shows that the non-contiguous tensor launches a lot of 1x1x1 kernels
![image](https://user-images.githubusercontent.com/3519115/52028102-c4d14e80-24db-11e9-8f7e-ea1663aa0885.png)

This is the profiler output for the contiguous tensor

![image](https://user-images.githubusercontent.com/3519115/52028137-dd416900-24db-11e9-9518-f3d75a797637.png)

## To Reproduce

I have seen this on 1080, 1080Ti, etc. 

```
import torch
import time
import numpy as np
all_my_tensors = {
    "t4x4_1": torch.from_numpy(np.random.rand(4, 4)).cuda(),
    "t4x4_2": torch.from_numpy(np.random.rand(4, 4)).cuda(),
    "t4x4_3": torch.from_numpy(np.random.rand(4, 4)).cuda(),
    "big_tensor": torch.from_numpy(np.random.rand(400000, 3)).cuda().float(),
}

def f1(my_tensors):
    t4x4_1 = my_tensors['t4x4_1'].float()

    device = t4x4_1.device
    t4x4_1 = t4x4_1.to("cpu", torch.float)
    # This does the inverse in CPU and then bring it back to the original device
    t4x4_1_inverse = torch.inverse(t4x4_1)
    t4x4_1_inverse = t4x4_1_inverse.to(device, torch.float)

    t4x4_2 = my_tensors['t4x4_2'].float()
    t4x4_3 = my_tensors['t4x4_3'].float()

    t4x4_1_inv_mm_t4x4_2 = t4x4_1_inverse.mm(t4x4_2)
    return t4x4_1_inv_mm_t4x4_2.mm(t4x4_3).float()

def f2(big_tensor, t4x4):
    ones = torch.ones((big_tensor.shape[0], 1), dtype=torch.float, device=big_tensor.device)
    homo_big_tensor = torch.cat([big_tensor, ones], dim=1)


    torch.cuda.synchronize()
    start = time.time()
    print "Here we do not call contiguous after transpose. This should lead to slow computation"
    experiment_1 = homo_big_tensor.transpose(0, 1)
    t4x4.mm(experiment_1)
    torch.cuda.synchronize()
    print "slow without contiguous {:.2f}ms".format((time.time()-start) * 1000)

    torch.cuda.synchronize()
    start = time.time()
    print "Here we call contiguous after transpose. This should lead to fast computation"
    experiment_2 = homo_big_tensor.transpose(0, 1).contiguous()
    t4x4.mm(experiment_2)
    torch.cuda.synchronize()
    print "fast with contiguous {:.2f}ms".format((time.time() - start) * 1000)

def f3(frame, t4x4_from_f1):
    t4x4_3 = frame['t4x4_3']
    # do inverse for small matrix in cpu because it's faster
    t4x4_3_inverse = torch.inverse(t4x4_3.to("cpu", dtype=torch.float))
    t4x4_3_inverse = t4x4_3_inverse.to(t4x4_3.device, torch.float)
    t4x4_reference = t4x4_from_f1.mm(t4x4_3_inverse)

    big_tensor = frame['big_tensor'].float()

    f2(big_tensor, t4x4_reference)


small_tensor = f1(all_my_tensors)
f3(all_my_tensors, small_tensor)
```

You should see

```
Here we do not call contiguous after transpose. This should lead to slow computation
slow without contiguous 56.15ms
Here we call contiguous after transpose. This should lead to fast computation
fast with contiguous 0.38ms
```

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233 @Lezcano @VitalyFedyunin

**Comment by sidazhang** [comment] 2019-02-05 15:04
@zou3519 Please see here for the repro

**Comment by musikisomorphie** [comment] 2019-02-15 09:39
Hi @zou3519,  I would like to work on it. Will that be okay?

**Comment by zou3519** [comment] 2019-02-15 16:37
I don't know how hard this is or what is going on, but feel free to go for it @musikisomorphie

**Comment by sidazhang** [comment] 2019-02-15 18:15
@musikisomorphie First of all, are you able to reproduce the problem on your end?

I have seen this across multiple versions of pytorch (up until a very recent nightly)

**Comment by musikisomorphie** [comment] 2019-02-15 18:23
@sidazhang, I run the code on my cluster with GPU K20.  It shows 

> Here we do not call contiguous after transpose. This should lead to slow computation
> slow without contiguous 1.44ms
> Here we call contiguous after transpose. This should lead to fast computation
> fast with contiguous 0.83ms

The time difference exists. 

@zou3519, I could look into it in the next few days, see if I can come up with a solution.

**Comment by sidazhang** [comment] 2019-02-15 20:44
Seems like your speed discrepancy is much more reasonable. Is this specific to a certain type of GPU?

**Comment by musikisomorphie** [comment] 2019-02-18 09:44
@zou3519, @sidazhang I reproduced the code on 3 GPU versions:
unfortunately, GTX 1080x are not available for me.  It seems the time difference can be reproduced on Titan.
My pytorch version: 1.1.0a0+ae1fc58



GeForce GTX TITAN:

> Here we do not call contiguous after transpose. This should lead to slow computation
> slow without contiguous 80.36ms
> Here we call contiguous after transpose. This should lead to fast computation
> fast with contiguous 0.99ms
> ==31536== Profiling application: python mm.py
> ==31536== Profiling result:
>             Type  Time(%)      Time     Calls       Avg       Min       Max  Name
>  GPU activities:   98.46%  79.643ms         1  79.643ms  79.643ms  79.643ms  void gemmSN_TN_kernel<float, float, float, int=128, int=16, int=2, int=4, int=4, int=4, bool=1>(int, int, int, float const *, int, float const *, int, float*, int, float const *, float const *, float, float, int, int)
>                     1.01%  813.67us         8  101.71us  1.0240us  805.10us  [CUDA memcpy HtoD]
>                     0.20%  159.55us         4  39.888us  3.2640us  146.08us  void gemmSN_NN_kernel<float, float, float, int=128, int=2, int=4, int=8, int=4, int=4>(cublasGemmSmallNParams<float, float, float>, float const *, float const *, float, float, int)
>                     0.14%  115.84us         1  115.84us  115.84us  115.84us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a36CopyOpIffE5applyERNS_6TensorERKS6_EUlRfRKfE_ffjLi1ELi2ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
>                     0.10%  82.625us         1  82.625us  82.625us  82.625us  void CatArrayBatchedCopy<float, unsigned int, int=2>(float*, CatArrInputTensor<float, unsigned int>*, OutputTensorSizeStride<unsigned int, unsigned int=4>, int, unsigned int)
>                     0.07%  60.609us         4  15.152us  1.7600us  54.753us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a36CopyOpIfdE5applyERNS_6TensorERKS6_EUlRfRKdE_fdjLi1ELi1ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
>                     0.01%  7.9360us         1  7.9360us  7.9360us  7.9360us  void kernelPointwiseApply1<TensorFillOp<float>, float, unsigned int, int=1>(OffsetInfo<TensorFillOp<float>, float, unsigned int>, float, float)
>                     0.01%  5.0560us         2  2.5280us  2.5280us  2.5280us  [CUDA memcpy DtoH]
>       API calls:   80.97%  2.60661s         9  289.62ms  12.543us  2.60568s  cudaMemcpyAsync
>                    10.17%  327.34ms         1  327.34ms  327.34ms  327.34ms  cudaFree
>                     6.11%  196.85ms         8  24.607ms  13.461us  195.03ms  cudaMalloc
>                     2.48%  79.756ms         4  19.939ms  9.2750us  79.610ms  cudaDeviceSynchronize
>                     0.14%  4.4964ms       367  12.251us     327ns  633.68us  cuDeviceGetAttribute
>                     0.04%  1.1828ms         1  1.1828ms  1.1828ms  1.1828ms  cudaGetDeviceProperties
>                     0.04%  1.1774ms         4  294.34us  206.06us  341.18us  cuDeviceTotalMem
>                     0.02%  694.12us         1  694.12us  694.12us  694.12us  cudaHostAlloc
>                     0.01%  377.74us         4  94.434us  89.360us  99.266us  cuDeviceGetName
>                     0.01%  279.71us        12  23.308us  17.153us  49.451us  cudaLaunch
>                     0.01%  195.90us       160  1.2240us     729ns  7.0650us  cudaGetDevice
>                     0.00%  129.82us         8  16.226us  3.3410us  91.039us  cudaStreamSynchronize
>                     0.00%  104.62us        71  1.4730us     832ns  5.1520us  cudaSetDevice
>                     0.00%  24.681us        17  1.4510us  1.1420us  2.8100us  cudaEventCreateWithFlags
>                     0.00%  15.998us         1  15.998us  15.998us  15.998us  cudaMemcpy
>                     0.00%  14.312us        67     213ns     110ns  2.2700us  cudaSetupArgument
>                     0.00%  10.414us        11     946ns     738ns  1.7380us  cudaDeviceGetAttribute
>                     0.00%  7.8480us        12     654ns     384ns  1.4370us  cudaConfigureCall
>                     0.00%  5.1820us        13     398ns     167ns  1.1420us  cudaGetDeviceCount
>                     0.00%  4.9020us         6     817ns     390ns  2.0260us  cuDeviceGetCount
>                     0.00%  4.1020us         3  1.3670us  1.0750us  1.5610us  cuInit
>                     0.00%  3.5860us        14     256ns     170ns     411ns  cudaGetLastError
>                     0.00%  3.2820us         5     656ns     401ns  1.0790us  cuDeviceGet
>                     0.00%  2.5390us         1  2.5390us  2.5390us  2.5390us  cudaEventRecord
>                     0.00%  2.2580us         3     752ns     442ns  1.0940us  cuDriverGetVersion


TITAN Xp:

> Here we do not call contiguous after transpose. This should lead to slow computation
> slow without contiguous 58.49ms
> Here we call contiguous after transpose. This should lead to fast computation
> fast with contiguous 1.59ms
> ==15659== Profiling application: python mm.py
> ==15659== Profiling result:
>             Type  Time(%)      Time     Calls       Avg       Min       Max  Name
>  GPU activities:   97.84%  57.359ms         1  57.359ms  57.359ms  57.359ms  void gemmSN_TN_kernel<float, float, float, int=128, int=16, int=2, int=4, int=4, int=4, bool=1>(int, int, int, float const *, int, float const *, int, float*, int, float const *, float const *, float, float, int, int)
>                     1.68%  982.70us         8  122.84us  1.0240us  974.92us  [CUDA memcpy HtoD]
>                     0.14%  84.485us         4  21.121us  2.4010us  75.043us  void gemmSN_NN_kernel<float, float, float, int=128, int=2, int=4, int=8, int=4, int=4>(cublasGemmSmallNParams<float, float, float>, float const *, float const *, float, float, int)
>                     0.13%  76.643us         1  76.643us  76.643us  76.643us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a36CopyOpIffE5applyERNS_6TensorERKS6_EUlRfRKfE_ffjLi1ELi2ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
>                     0.13%  74.851us         1  74.851us  74.851us  74.851us  void CatArrayBatchedCopy<float, unsigned int, int=2>(float*, CatArrInputTensor<float, unsigned int>*, OutputTensorSizeStride<unsigned int, unsigned int=4>, int, unsigned int)
>                     0.06%  37.217us         4  9.3040us  1.3120us  33.153us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a36CopyOpIfdE5applyERNS_6TensorERKS6_EUlRfRKdE_fdjLi1ELi1ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
>                     0.01%  5.1200us         1  5.1200us  5.1200us  5.1200us  void kernelPointwiseApply1<TensorFillOp<float>, float, unsigned int, int=1>(OffsetInfo<TensorFillOp<float>, float, unsigned int>, float, float)
>                     0.00%  2.6240us         2  1.3120us  1.2480us  1.3760us  [CUDA memcpy DtoH]
>       API calls:   93.34%  22.2165s         9  2.46850s  17.702us  22.2153s  cudaMemcpyAsync
>                     4.78%  1.13700s         1  1.13700s  1.13700s  1.13700s  cudaFree
>                     1.58%  375.11ms         8  46.889ms  19.873us  371.09ms  cudaMalloc
>                     0.24%  57.424ms         4  14.356ms  17.200us  57.316ms  cudaDeviceSynchronize
>                     0.02%  4.7590ms       367  12.967us     604ns  589.43us  cuDeviceGetAttribute
>                     0.02%  4.7347ms         4  1.1837ms  394.95us  3.4804ms  cuDeviceTotalMem
>                     0.01%  1.8289ms         1  1.8289ms  1.8289ms  1.8289ms  cudaHostAlloc
>                     0.01%  1.3412ms         1  1.3412ms  1.3412ms  1.3412ms  cudaGetDeviceProperties
>                     0.00%  751.89us         4  187.97us  127.73us  316.99us  cuDeviceGetName
>                     0.00%  404.32us        12  33.693us  23.041us  53.035us  cudaLaunch
>                     0.00%  295.50us       160  1.8460us     987ns  9.8140us  cudaGetDevice
>                     0.00%  154.59us        71  2.1770us  1.0090us  7.4950us  cudaSetDevice
>                     0.00%  131.20us         8  16.399us  5.3380us  79.356us  cudaStreamSynchronize
>                     0.00%  34.528us        17  2.0310us  1.6510us  3.9040us  cudaEventCreateWithFlags
>                     0.00%  21.664us         1  21.664us  21.664us  21.664us  cudaMemcpy
>                     0.00%  21.372us        67     318ns     157ns  2.6640us  cudaSetupArgument
>                     0.00%  13.475us        11  1.2250us     996ns  2.7020us  cudaDeviceGetAttribute
>                     0.00%  10.968us        12     914ns     452ns  1.9110us  cudaConfigureCall
>                     0.00%  7.2000us         3  2.4000us  2.0990us  2.8700us  cuInit
>                     0.00%  6.9450us         6  1.1570us     643ns  2.6600us  cuDeviceGetCount
>                     0.00%  6.5950us        13     507ns     176ns  1.8050us  cudaGetDeviceCount
>                     0.00%  5.6490us         5  1.1290us     753ns  2.0620us  cuDeviceGet
>                     0.00%  5.5360us        14     395ns     173ns     650ns  cudaGetLastError
>                     0.00%  3.4330us         3  1.1440us     847ns  1.5030us  cuDriverGetVersion
>                     0.00%  3.4110us         1  3.4110us  3.4110us  3.4110us  cudaEventRecord
> 

Tesla K20Xm 

> Here we do not call contiguous after transpose. This should lead to slow computation
> slow without contiguous 1.52ms
> Here we call contiguous after transpose. This should lead to fast computation
> fast with contiguous 1.03ms
> ==22569== Profiling application: python mm.py
> ==22569== Profiling result:
>             Type  Time(%)      Time     Calls       Avg       Min       Max  Name
>  GPU activities:   81.71%  5.4441ms         8  680.52us     960ns  5.4355ms  [CUDA memcpy HtoD]
>                     7.96%  530.66us         1  530.66us  530.66us  530.66us  void magma_lds128_sgemm_kernel<bool=1, bool=0, int=6, int=6, int=4, int=3, int=4>(int, int, int, float const *, int, float const *, int, float*, int, int, int, float const *, float const *, float, float, int)
>                     2.93%  195.30us         1  195.30us  195.30us  195.30us  void CatArrayBatchedCopy<float, unsigned int, int=2>(float*, CatArrInputTensor<float, unsigned int>*, OutputTensorSizeStride<unsigned int, unsigned int=4>, int, unsigned int)
>                     2.72%  181.12us         1  181.12us  181.12us  181.12us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a36CopyOpIffE5applyERNS_6TensorERKS6_EUlRfRKfE_ffjLi1ELi2ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
>                     2.51%  166.98us         1  166.98us  166.98us  166.98us  void magma_lds128_sgemm_kernel<bool=0, bool=0, int=6, int=5, int=3, int=3, int=3>(int, int, int, float const *, int, float const *, int, float*, int, int, int, float const *, float const *, float, float, int)
>                     1.44%  95.906us         4  23.976us  2.3680us  88.130us  _ZN2at4cuda75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a321kernelPointwiseApply2IZN75_GLOBAL__N__51_tmpxft_00020431_00000000_12_Copy_compute_70_cpp1_ii_dd3fb9a36CopyOpIfdE5applyERNS_6TensorERKS6_EUlRfRKdE_fdjLi1ELi1ELi1EEEvNS0_6detail10TensorInfoIT0_T2_EENSF_IT1_SH_EESH_T_
>                     0.46%  30.976us         3  10.325us  8.3840us  14.144us  sgemm_sm35_ldg_nn_64x16x64x16x16
>                     0.19%  12.608us         1  12.608us  12.608us  12.608us  void kernelPointwiseApply1<TensorFillOp<float>, float, unsigned int, int=1>(OffsetInfo<TensorFillOp<float>, float, unsigned int>, float, float)
>                     0.08%  5.3120us         2  2.6560us  2.6240us  2.6880us  [CUDA memcpy DtoH]
>       API calls:   85.79%  3.90813s         9  434.24ms  15.810us  3.90185s  cudaMemcpyAsync
>                     8.08%  368.00ms         1  368.00ms  368.00ms  368.00ms  cudaFree
>                     5.84%  265.91ms         8  33.239ms  21.330us  264.33ms  cudaMalloc
>                     0.14%  6.5466ms       734  8.9190us     850ns  332.46us  cuDeviceGetAttribute
>                     0.04%  1.7922ms         8  224.02us  201.24us  260.97us  cuDeviceTotalMem
>                     0.03%  1.4599ms         2  729.97us  703.38us  756.56us  cudaGetDeviceProperties
>                     0.02%  875.86us         1  875.86us  875.86us  875.86us  cudaHostAlloc
>                     0.01%  653.09us         8  81.636us  61.007us  124.10us  cuDeviceGetName
>                     0.01%  625.01us         4  156.25us  9.5840us  467.01us  cudaDeviceSynchronize
>                     0.01%  591.55us        12  49.295us  22.800us  106.87us  cudaLaunch
>                     0.01%  411.00us       160  2.5680us     877ns  19.611us  cudaGetDevice
>                     0.00%  209.90us        72  2.9150us  1.2230us  10.340us  cudaSetDevice
>                     0.00%  172.32us         8  21.540us  4.9810us  98.565us  cudaStreamSynchronize
>                     0.00%  43.152us        17  2.5380us  1.9790us  5.2270us  cudaEventCreateWithFlags
>                     0.00%  35.586us         4  8.8960us  5.8740us  13.592us  cudaBindTexture
>                     0.00%  30.421us       102     298ns     146ns  3.5990us  cudaSetupArgument
>                     0.00%  30.302us         1  30.302us  30.302us  30.302us  cudaMemcpy
>                     0.00%  16.325us        11  1.4840us  1.1310us  3.4780us  cudaDeviceGetAttribute
>                     0.00%  15.610us        12  1.3000us     474ns  3.0500us  cudaConfigureCall
>                     0.00%  12.833us        10  1.2830us     953ns  2.0800us  cuDeviceGet
>                     0.00%  12.743us         4  3.1850us  1.9750us  4.5760us  cudaUnbindTexture
>                     0.00%  12.152us        19     639ns     223ns  2.4200us  cudaGetDeviceCount
>                     0.00%  9.9250us         6  1.6540us     996ns  3.2780us  cuDeviceGetCount
>                     0.00%  8.6280us         3  2.8760us  2.1750us  3.6790us  cuInit
>                     0.00%  7.2740us        14     519ns     265ns  1.0500us  cudaGetLastError
>                     0.00%  5.5290us         1  5.5290us  5.5290us  5.5290us  cudaEventRecord
>                     0.00%  4.2610us         3  1.4200us  1.2830us  1.6080us  cuDriverGetVersion
>

**Comment by zou3519** [comment] 2019-02-20 20:33
@musikisomorphie sorry for the slow response, it should be this function: https://github.com/pytorch/pytorch/blob/14dcdc4c35d10fce70bf8b98dd57f9318dfb8dd7/aten/src/THC/generic/THCTensorMathBlas.cu#L251-L412.

**Comment by musikisomorphie** [comment] 2019-02-20 21:24
> @musikisomorphie sorry for the slow response, it should be this function:
> 
> [pytorch/aten/src/THC/generic/THCTensorMathBlas.cu](https://github.com/pytorch/pytorch/blob/14dcdc4c35d10fce70bf8b98dd57f9318dfb8dd7/aten/src/THC/generic/THCTensorMathBlas.cu#L251-L412)
> 
> Lines 251 to 412 in [14dcdc4](/pytorch/pytorch/commit/14dcdc4c35d10fce70bf8b98dd57f9318dfb8dd7)
> 
>  void THCTensor_(addmm)(THCState *state, THCTensor *r_, scalar_t beta, THCTensor *t, scalar_t alpha, THCTensor *m1, THCTensor *m2) 
>  { 
>  #if defined(THC_REAL_IS_HALF) || defined(THC_REAL_IS_FLOAT) || defined(THC_REAL_IS_DOUBLE) 
>   
>    THCAssertSameGPU(THCTensor_(checkGPU)(state, 4, r_, t, m1, m2)); 
>    char transpose_r, transpose_m1, transpose_m2; 
>    THCTensor *r__, *m1_, *m2_; 
>   
>    if( (m1->dim() != 2) || (m2->dim() != 2) ) 
>      THError("2D tensors expected, got %dD, %dD tensors", m1->dim(), m2->dim()); 
>   
>    if(t->dim() != 2) 
>      THError("2D tensor expected, got %dD tensor for t", t->dim()); 
>   
>    if(m1->size(1) != m2->size(0)) { 
>      THCDescBuff bm1 = THCTensor_(sizeDesc)(state, m1); 
>      THCDescBuff bm2 = THCTensor_(sizeDesc)(state, m2); 
>      THError("size mismatch, m1: %s, m2: %s", bm1.str, bm2.str); 
>    } 
>   
>    if( (t->size(0) != m1->size(0)) || (t->size(1) != m2->size(1)) ) { 
>      THCDescBuff bt  = THCTensor_(sizeDesc)(state, t); 
>      THCDescBuff bm1 = THCTensor_(sizeDesc)(state, m1); 
>      THCDescBuff bm2 = THCTensor_(sizeDesc)(state, m2); 
>      THError("size mismatch, t: %s, m1: %s, m2: %s", bt.str, bm1.str, bm2.str); 
>    } 
>   
>    if(t != r_) 
>    { 
>      THCTensor_(resizeAs)(state, r_, t); 
>      if (ScalarConvert<scalar_t, double>::to(beta) != 0.0) { 
>        THCTensor_(copy)(state, r_, t); 
>      } 
>    } 
>   
>    /* r_ */ 
>    if(r_->stride(0) == 1 && 
>       r_->stride(1) != 0) 
>    { 
>      transpose_r = 'n'; 
>      r__ = r_; 
>    } 
>    else if(r_->stride(1) == 1 && 
>            r_->stride(0) != 0) 
>    { 
>      THCTensor *swap = m2; 
>      m2 = m1; 
>      m1 = swap; 
>      transpose_r = 't'; 
>      r__ = r_; 
>    } 
>    else 
>    { 
>      transpose_r = 'n'; 
>   
>      THCTensor *transp_r_ = THCTensor_(newTranspose)(state, r_, 0, 1); 
>      r__ = THCTensor_(newClone)(state, transp_r_); 
>      THCTensor_(free)(state, transp_r_); 
>      THCTensor_(transpose)(state, r__, NULL, 0, 1); 
>    } 
>   
>    /* m1 */ 
>    if(m1->stride((transpose_r == 'n' ? 0 : 1)) == 1 && 
>       m1->stride((transpose_r == 'n' ? 1 : 0)) != 0) 
>    { 
>      transpose_m1 = 'n'; 
>      m1_ = m1; 
>    } 
>    else if(m1->stride((transpose_r == 'n' ? 1 : 0)) == 1 && 
>            m1->stride((transpose_r == 'n' ? 0 : 1)) != 0) 
>    { 
>      transpose_m1 = 't'; 
>      m1_ = m1; 
>    } 
>    else 
>    { 
>      transpose_m1 = (transpose_r == 'n' ? 't' : 'n'); 
>      m1_ = THCTensor_(newContiguous)(state, m1); 
>    } 
>   
>    /* m2 */ 
>    if(m2->stride((transpose_r == 'n' ? 0 : 1)) == 1 && 
>       m2->stride((transpose_r == 'n' ? 1 : 0)) != 0) 
>    { 
>      transpose_m2 = 'n'; 
>      m2_ = m2; 
>    } 
>    else if(m2->stride((transpose_r == 'n' ? 1 : 0)) == 1 && 
>            m2->stride((transpose_r == 'n' ? 0 : 1)) != 0) 
>    { 
>      transpose_m2 = 't'; 
>      m2_ = m2; 
>    } 
>    else 
>    { 
>      transpose_m2 = (transpose_r == 'n' ? 't' : 'n'); 
>      m2_ = THCTensor_(newContiguous)(state, m2); 
>    } 
>   
>  #ifdef THC_REAL_IS_HALF 
>    THCudaBlas_Hgemm(state, 
>                     transpose_m1, 
>                     transpose_m2, 
>                     r__->size((transpose_r == 'n' ? 0 : 1)), 
>                     r__->size((transpose_r == 'n' ? 1 : 0)), 
>                     m1_->size((transpose_r == 'n' ? 1 : 0)), 
>                     alpha, 
>                     THCTensor_(data)(state, m1_), 
>                     (transpose_m1 == 'n' ? m1_->stride((transpose_r == 'n' ? 1 : 0)) : m1_->stride((transpose_r == 'n' ? 0 : 1))), 
>                     THCTensor_(data)(state, m2_), 
>                     (transpose_m2 == 'n' ? m2_->stride((transpose_r == 'n' ? 1 : 0)) : m2_->stride((transpose_r == 'n' ? 0 : 1))), 
>                     beta, 
>                     THCTensor_(data)(state, r__), 
>                     r__->stride((transpose_r == 'n' ? 1 : 0))); 
>  #elif defined(THC_REAL_IS_FLOAT) 
>    THCudaBlas_Sgemm(state, 
>                     transpose_m1, 
>                     transpose_m2, 
>                     r__->size((transpose_r == 'n' ? 0 : 1)), 
>                     r__->size((transpose_r == 'n' ? 1 : 0)), 
>                     m1_->size((transpose_r == 'n' ? 1 : 0)), 
>                     alpha, 
>                     THCTensor_(data)(state, m1_), 
>                     (transpose_m1 == 'n' ? m1_->stride((transpose_r == 'n' ? 1 : 0)) : m1_->stride((transpose_r == 'n' ? 0 : 1))), 
>                     THCTensor_(data)(state, m2_), 
>                     (transpose_m2 == 'n' ? m2_->stride((transpose_r == 'n' ? 1 : 0)) : m2_->stride((transpose_r == 'n' ? 0 : 1))), 
>                     beta, 
>                     THCTensor_(data)(state, r__), 
>                     r__->stride((transpose_r == 'n' ? 1 : 0))); 
>  #elif defined(THC_REAL_IS_DOUBLE) 
>    THCudaBlas_Dgemm(state, 
>                     transpose_m1, 
>                     transpose_m2, 
>                     r__->size((transpose_r == 'n' ? 0 : 1)), 
>                     r__->size((transpose_r == 'n' ? 1 : 0)), 
>                     m1_->size((transpose_r == 'n' ? 1 : 0)), 
>                     alpha, 
>                     THCTensor_(data)(state, m1_), 
>                     (transpose_m1 == 'n' ? m1_->stride((transpose_r == 'n' ? 1 : 0)) : m1_->stride((transpose_r == 'n' ? 0 : 1))), 
>                     THCTensor_(data)(state, m2_), 
>                     (transpose_m2 == 'n' ? m2_->stride((transpose_r == 'n' ? 1 : 0)) : m2_->stride((transpose_r == 'n' ? 0 : 1))), 
>                     beta, 
>                     THCTensor_(data)(state, r__), 
>                     r__->stride((transpose_r == 'n' ? 1 : 0))); 
>  #endif 
>   
>    /* free intermediate variables */ 
>    if(m1_ != m1) { 
>      THCTensor_(free)(state, m1_); 
>    } 
>   
>    if(m2_ != m2) { 
>      THCTensor_(free)(state, m2_); 
>    } 
>   
>    if(r__ != r_) { 
>      THCTensor_(freeCopyTo)(state, r__, r_); 
>    } 
>  #else 
>    ERROR_ONLY_FP_TYPES("addmm"); 
>  #endif 
>  } 
> .

thanks @zou3519,  according to me and @sidazhang's nvprof output, this problem involve's certain implementation detail's of cublas. I suppose the problem won't be easy since the source code of cublas is not available.  Nevertheless, I am going to spend some more time to see if I can do something about it.

**Comment by musikisomorphie** [comment] 2019-03-01 14:40
Hi @zou3519, @sidazhang, after running some experiments, I realize that the problem may not be contiguous. Actually, if you uncomment torch.cuda.synchronize( ) in the f2 function of @sidazhang 's code, then gemmSN_TN_kernel will not be called.  I am still not sure how difficult the problem is, but I guess I will spend some more time on it.

**Comment by sidazhang** [comment] 2019-03-02 02:03
@musikisomorphie Amazing discovery. That's indeed really weird.

**Comment by musikisomorphie** [comment] 2019-03-08 21:27
I did some further investigation this week.  torch.cuda.synchronize( ) is a simple wrapper of cudaStreamSynchronize(), which triggers the gemmSN_TN_kernel. The reason why it triggers this kernel is beyond the scope of my cuda understanding, I can barely find any clue online. But as long as we don't use synchronize( ), this rare inefficient case can be avoided.

**Comment by ezyang** [comment] 2021-08-04 17:23
On  Quadro GP100 here are the numbers I get on master

```
Here we do not call contiguous after transpose. This should lead to slow computation
slow without contiguous 1.62ms
Here we call contiguous after transpose. This should lead to fast computation
fast with contiguous 0.26ms
```

nvprof says

```
                   27.26%  536.25us         2  268.13us  7.7430us  528.51us  void gemmSN_TN_kernel_64addr<float, int=128, int=16, int=2, int=4, int=4, int=4, bool=1, cublasGemvTensorStridedBatched<float const >, cublasGemvTensorStridedBatched<float const >, cublasGemvTensorStridedBatched<float>>(cublasGemmSmallNParams<float const , cublasGemvTensorStridedBatched<float const >, cublasGemvTensorStridedBatched<float const >, float>)
                    5.45%  107.20us         2  53.600us  8.4800us  98.720us  void gemmSN_NN_kernel<float, int=128, int=2, int=4, int=8, int=4, int=4, bool=0, cublasGemvTensorStridedBatched<float const >, cublasGemvTensorStridedBatched<float const >, cublasGemvTensorStridedBatched<float>>(cublasGemmSmallNParams<float const , cublasGemvTensorStridedBatched<float const >, cublasGemvTensorStridedBatched<float const >, float>)
                    3.47%  68.223us         1  68.223us  68.223us  68.223us  _ZN2at6native27unrolled_elementwise_kernelIZZZNS0_21copy_device_to_deviceERNS_14TensorIteratorEbENKUlvE0_clEvENKUlvE6_clEvEUlfE_NS_6detail5ArrayIPcLi2EEE16OffsetCalculatorILi1EjESC_NS0_6memory15LoadWithoutCastENSD_16StoreWithoutCastEEEviT_T0_T1_T2_T3_T4_
                    2.92%  57.407us         1  57.407us  57.407us  57.407us  void at::native::_GLOBAL__N__52_tmpxft_0000771a_00000000_14_Shape_compute_86_cpp1_ii_cedd8df2::CatArrayBatchedCopy<float, unsigned int, int=2, int=128, int=1>(float*, at::native::_GLOBAL__N__52_tmpxft_0000771a_00000000_14_Shape_compute_86_cpp1_ii_cedd8df2::CatArrInputTensorMetadata<at::native::_GLOBAL__N__52_tmpxft_0000771a_00000000_14_Shape_compute_86_cpp1_ii_cedd8df2::CatArrayBatchedCopy<float, unsigned int, int=2, int=128, int=1>, unsigned int, int=128, int=1>, at::native::_GLOBAL__N__52_tmpxft_0000771a_00000000_14_Shape_compute_86_cpp1_ii_cedd8df2::TensorSizeStride<at::native::_GLOBAL__N__52_tmpxft_0000771a_00000000_14_Shape_compute_86_cpp1_ii_cedd8df2::CatArrInputTensorMetadata, unsigned int=4>, int, at::native::_GLOBAL__N__52_tmpxft_0000771a_00000000_14_Shape_compute_86_cpp1_ii_cedd8df2::CatArrInputTensorMetadata)
                    2.49%  48.959us         4  12.239us  3.1680us  38.655us  _ZN2at6native27unrolled_elementwise_kernelIZZZNS0_21copy_device_to_deviceERNS_14TensorIteratorEbENKUlvE0_clEvENKUlvE6_clEvEUlfE_NS_6detail5ArrayIPcLi2EEE23TrivialOffsetCalculatorILi1EjESC_NS0_6memory12LoadWithCastILi1EEENSD_13StoreWithCastEEEviT_T0_T1_T2_T3_T4_
                    1.19%  23.488us         1  23.488us  23.488us  23.488us  maxwell_sgemm_128x64_nt
                    0.32%  6.3040us         1  6.3040us  6.3040us  6.3040us  void at::native::vectorized_elementwise_kernel<int=4, at::native::FillFunctor<float>, at::detail::Array<char*, int=1>>(int, float, at::native::FillFunctor<float>)
```

**Comment by ngimel** [comment] 2021-08-05 04:23
On V100, with benchmarking adjusted to run multiple loops, and confirmed by nvprof output, one of the kernels takes 60 us, another 40 us, which is a reasonable difference. Closing, please reopen if still an issue.

**Closed by ngimel** 2021-08-05 04:23 UTC
Labels: module: cuda, module: linear algebra, module: performance, triaged
