### ISSUE TITLE
automatically inferring

### ISSUE THREAD

**Issue by develooper1994** [pytorch/pytorch#30880] opened 2019-12-06 17:48 UTC
## 🚀 Feature

automatically inferring the input size after the first forward pass

## Motivation
https://mxnet.apache.org/api/python/docs/tutorials/getting-started/to-mxnet/pytorch.html
In PyTorch you have to specify the input size as the first argument of the Linear object. Apache MXNet provides an extra flexibility to network structure by automatically inferring the input size after the first forward pass.

## Pitch
I have to specify input of the hidden layer input. I want to make sequence without specifing input size.
Exp: #for now;
pt_net = pt_nn.Sequential(
    pt_nn.Linear(28*28, 256),
    pt_nn.ReLU(),
    pt_nn.Linear(256, 10))

My request; #input size is know and second layer input size also known
pt_net = pt_nn.Sequential(
    pt_nn.Linear(256),
    pt_nn.ReLU(),
    pt_nn.Linear(10))

**Comment by albanD** [comment] 2020-06-15 14:24
Closing this as a duplicate of https://github.com/pytorch/pytorch/issues/23352 that has discussions concerning this feature.

**Closed by albanD** 2020-06-15 14:24 UTC
Labels: module: nn, triaged
