### ISSUE TITLE
RuntimeError using torch.nn.functional.pad only when using MPS

### ISSUE THREAD

**Issue by mattgrayling** [pytorch/pytorch#87277] opened 2022-10-19 10:28 UTC
### 🐛 Describe the bug

I am having an issue with torch.nn.functional.pad when training using MPS on an M1 Mac. I am using someone else's package but have made a minimal example to demonstrate the problem. When I run this code on CPU:

```
import torch
y = torch.ones((50, 9, 300))
y_pad = torch.nn.functional.pad(y, (0, 0, 0, 31))
```

everything works as expected and there are no issues. However, when I change the device to MPS by instead running:

```
import torch
y = torch.ones((50, 9, 300), device='mps')
y_pad = torch.nn.functional.pad(y, (0, 0, 0, 31))
```

then the third line raises this error:

```Traceback (most recent call last):
  File "/Users/matt/Documents/parsnip/mps_pad_test.py", line 3, in <module>
    y_pad = torch.nn.functional.pad(y, (0, 0, 0, 31))
RuntimeError: Argument #6: Padding size should be less than the corresponding input dimension, but got: padding (0, 31) at dimension 1 of input 3
```

I have this problem with the nightly from a couple of days ago and also the most recent nightly. Apologies if this is just me doing something wrong but I can't see what would be responsible other than a bug.

### Versions

Collecting environment information...
PyTorch version: 1.14.0.dev20221019
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:38:29) [Clang 13.0.1 ] (64-bit runtime)
Python platform: macOS-12.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221019
[pip3] torchaudio==0.13.0.dev20221017
[pip3] torchvision==0.15.0.dev20221017
[conda] numpy                     1.23.4          py310h5d7c261_0    conda-forge
[conda] torch                     1.14.0.dev20221019          pypi_0    pypi
[conda] torchaudio                0.13.0.dev20221017          pypi_0    pypi
[conda] torchvision               0.15.0.dev20221017          pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by DenisVieriu97** [comment] 2022-10-19 17:16
@razarmehr, could you please take a look?

**Comment by mattgrayling** [comment] 2022-10-24 11:16
Could I just check the status of this? I see it was closed and then reopened again, and I am still getting the same issue with the latest nightly?

**Comment by kulinseth** [comment] 2022-10-24 14:12
@mattgrayling the issue is fixed in a branch linked in the issue https://github.com/kulinseth/pytorch/pull/144 , but needs to be upstreamed to the pytorch/master. We will update here when it’s done .

**Closed** 2022-12-13 17:29 UTC
Labels: triaged, module: mps
