### ISSUE TITLE
pr build failures in inductor dynamic shape test for operation tests with simple tensors. Side effect of current test framework

### ISSUE THREAD

**Issue by davidradl** [pytorch/pytorch#109016] opened 2023-09-11 09:42 UTC
### 🐛 Describe the bug

As follow on from pull request [https://github.com/pytorch/pytorch/pull/108513]( https://github.com/pytorch/pytorch/pull/108513).

Some tests were created with tensors with a single operand  like `torch.tensor([128]` This tests fail in dynamic tests. I have left the tests commented out as per the pull request and created tests that pass. 

This issue is tracking the problem that dynamic shape tests fail for some tests. The code fails as it expects a loop when there is not one.

### Versions

Collecting environment information...
PyTorch version: 2.1.0a0+gite68b3ad
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.5.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.10.12 | packaged by conda-forge | (main, Jun 23 2023, 22:41:52) [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-13.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.4.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.1.0a0+git716c0c8
[pip3] torchgen==0.0.1
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.1.0a0+git716c0c8          pypi_0    pypi
[conda] torchgen                  0.0.1                    pypi_0    pypi

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by davidradl** [comment] 2023-09-11 13:38
this could be fixed by [https://github.com/pytorch/pytorch/pull/109012](https://github.com/pytorch/pytorch/pull/109012)

**Comment by bdhirsh** [comment] 2023-09-14 21:51
@davidradl should I assign to you since this looks like a followup issue to https://github.com/pytorch/pytorch/issues/105264?

**Comment by davidradl** [comment] 2023-09-22 12:54
@bdhirsh sorry I am not in position to take this on at them moment. If this changes then I will let you know.

**Comment by leslie-fang-intel** [comment] 2023-12-07 08:10
@davidradl will you follow up for this one?

**Comment by leslie-fang-intel** [comment] 2024-01-09 08:28
Per the description in issue summary, this issue should be a follow up of PR: https://github.com/pytorch/pytorch/pull/108513. However, looks like https://github.com/pytorch/pytorch/pull/108513 has been closed without merging. I am not if it's still a valid a issue, if so, how to reproduce the failure? Since https://github.com/pytorch/pytorch/pull/108513 is too big to find out the command for reproducing the issue.

**Comment by leslie-fang-intel** [comment] 2024-01-11 08:09
Hi @davidradl, I will close this issue since https://github.com/pytorch/pytorch/pull/108513 didn't landed. Feel free to re-open if any further discussion needed.

**Closed by leslie-fang-intel** 2024-01-11 08:09 UTC
Labels: triaged, oncall: pt2, module: dynamic shapes, oncall: cpu inductor
