### ISSUE TITLE
ONNX export regression: examples/fast_neural_style fails to export (pytorch_nightly)

### ISSUE THREAD

**Issue by borisfom** [pytorch/pytorch#19374] opened 2019-04-17 22:25 UTC
## 🐛 Bug
ONNX export regression: examples/fast_neural_style fails to export (pytorch_nightly)

## To Reproduce

1. cd pytorch/examples/fast_neural_style
2. python3 neural_style/neural_style.py eval --content-image test,jpg --output-image res.jpg --cuda 1 --export_onnx mosaic.onnx --model saved_models/mosaic.pth

Traceback (most recent call last):
  File "neural_style/neural_style.py", line 240, in <module>
    main()
  File "neural_style/neural_style.py", line 236, in main
    stylize(args)
  File "neural_style/neural_style.py", line 147, in stylize
    output = torch.onnx._export(style_model, content_image, args.export_onnx).cpu()
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 19, in _export
    result = utils._export(*args, **kwargs)
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 338, in _export
    _retain_param_name)
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 260, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type)
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 178, in _optimize_graph
    Graph = Torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 563, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/bfomitchev/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): pytorch_nightly
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda install -c pytorch pytorch-nightly
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version: 10.0/7.4
 - GPU models and configuration: Volta, Turing
 - Any other relevant information:  This export worked  since forever, broke  at some point last month

**Comment by borisfom** [comment] 2019-04-19 23:22
@nairbv : Any ETA on this one ?

**Comment by soumith** [comment] 2019-04-20 02:29
cc: @houseroad @zrphercule

**Comment by houseroad** [comment] 2019-04-23 06:15
I will take a look.

**Comment by dtmoodie** [comment] 2019-04-29 20:41
I can confirm that my model exports with pytorch 1.0.1 but not with the nightly.

**Comment by borisfom** [comment] 2019-04-30 00:04
@houseroad : Any ETA in mind ?

**Comment by pk-g** [comment] 2019-05-03 21:52
The issue here seems to be with upsample upon export. Please feel free to review the proposed fix #20116 on this.

**Comment by glenn-jocher** [comment] 2019-05-05 10:10
Same issue here. Export works in 1.0.1 but is broken in 1.1.

**Comment by aliYaHf** [comment] 2019-05-05 12:18
I have the same problem. Is there any solution?
`Traceback (most recent call last):
  File "tools/train.py", line 253, in <module>
    main()
  File "tools/train.py", line 138, in main
    writer_dict['writer'].add_graph(model, (dump_input, ))
  File "/root/anaconda3/lib/python3.6/site-packages/tensorboardX/writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/root/anaconda3/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 235, in graph
    _optimize_trace(trace, torch.onnx.utils.OperatorExportTypes.ONNX)
  File "/root/anaconda3/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 175, in _optimize_trace
    trace.set_graph(_optimize_graph(trace.graph(), operator_export_type))
  File "/root/anaconda3/lib/python3.6/site-packages/tensorboardX/pytorch_graph.py", line 206, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/root/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/root/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 130, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/root/anaconda3/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 90, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible
`

**Comment by spandantiwari** [comment] 2019-05-07 17:28
Track PR https://github.com/pytorch/pytorch/pull/20116 for the fix for this issue.

**Comment by houseroad** [comment] 2019-05-09 18:01
Ideally, we should also add this model to the CI to prevent regression in the future. https://github.com/pytorch/pytorch/issues/20327

**Comment by Aeroxander** [comment] 2019-05-21 05:18
I wasn't even using this particular style transfer project but I had the same issue! Hope it gets fixed soon, I'll just stay at 1.1 for now! (unless it will take super long for the fix but it seems it's almost fixed)

**Comment by cuixing158** [comment] 2019-05-22 10:25
I meet same error to, pytorch1.1+python3.7+onnx1.5,any advices?

**Comment by houseroad** [comment] 2019-05-22 21:40
@cuixing158 checkout this: https://github.com/pytorch/pytorch/pull/20116

**Comment by spandantiwari** [comment] 2019-06-11 17:28
This issue has been fixed in master.

**Closed** 2019-06-11 18:52 UTC
Labels: module: onnx, triaged
