### ISSUE TITLE
Expected is_sm80 || is_sm90 to be true, but got false. (on batch size > 6)

### ISSUE THREAD

**Issue by ArrowM** [pytorch/pytorch#98771] opened 2023-04-10 18:55 UTC
## Description
The following error is thrown when attempting to train with batch sizes > 6 on consumer cards (I have verified with my 3080 ti):
```
Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.  (Could this error message be improved? If so, please report an enhancement request to PyTorch.
```
Training works fine with batch size <= 6. It only seems to effect Torch2. I have reproduced the error on the latest release build and the nightly build from April 04. I understand that the error implies it expects sm80 or sm90 architecture, but I don't understand why that is the case and how I could possibly adjust the code to avoid it.

edit: Apparently this issue doesn't occur for a 4080

edit2: I also tried setting `use_reentrant=False` in the `checkpoint()` calls, but that did not change the error.
</details>

## Stacktrace
```st
  File "C:\stable-diffusion-webui-auto\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1274, in inner_loop
    accelerator.backward(loss)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\accelerate\accelerator.py", line 1681, in backward
    self.scaler.scale(loss).backward(**kwargs)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\autograd\__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\autograd\function.py", line 274, in apply
    return user_fn(self, *args)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\utils\checkpoint.py", line 161, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\autograd\__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected is_sm80 || is_sm90 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
```
 I also tried fp32 precision, which threw a different exception.
```st
  File "C:\stable-diffusion-webui-auto\extensions\sd_dreambooth_extension\dreambooth\train_dreambooth.py", line 1274, in inner_loop
    accelerator.backward(loss)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\accelerate\accelerator.py", line 1683, in backward
    loss.backward(**kwargs)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\autograd\__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\autograd\function.py", line 274, in apply
    return user_fn(self, *args)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\utils\checkpoint.py", line 161, in backward
    torch.autograd.backward(outputs_with_grad, args_with_grad)
  File "C:\stable-diffusion-webui-auto\venv\lib\site-packages\torch\autograd\__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: CUDA error: invalid argument
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
</details>

## Reproduction
 I'm not very adept with PyTorch, so my reproduction is probably spotty. Myself and other are running into the issue while running [train_dreambooth.py](https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/train_dreambooth.py); I have tried to extract the relevant code. If there is any relevant information missing, please let me know and I would be happy to provide it.

<details>
<summary>Reproduction attempt</summary>

```python
batch_size = 7

accelerator = Accelerator(
    gradient_accumulation_steps=1,
    mixed_precision="fp16",
)

train_dataset = Dataset(
    # ...
    batch_size=batch_size,
)
train_dataloader = torch.utils.data.DataLoader(
    # ...
    train_dataset,
    batch_size=batch_size,
    collate_fn=collate_fn,  # https://github.com/d8ahazard/sd_dreambooth_extension/blob/main/dreambooth/train_dreambooth.py#L512
)
unet = UNet2DConditionModel.from_pretrained(
    args.get_pretrained_model_name_or_path(),
    torch_dtype=torch.float32,
)
unet.enable_gradient_checkpointing()
unet.requires_grad_(False)

(unet, train_dataloader) = accelerator.prepare(unet, train_dataloader)

for step, batch in enumerate(train_dataloader):
    # ...
    unet.train()
    with accelerator.accumulate(unet)
        # ...
        noise_pred = unet(noisy_latents, timesteps, encoder_hidden_states).sample
        loss = torch.nn.functional.mse_loss(noise_pred.float(), target.float(), reduction="mean")
        accelerator.backward(loss)  # <---- THIS IS WHERE THE ERROR IS THROWN
```
</details>

<details>
<summary>Versions</summary>

PyTorch version: 2.1.0.dev20230404+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Education
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.26.1
Libc version: N/A

Python version: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22624-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080 Ti
Nvidia driver version: 531.41
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3801
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3801
Name=AMD Ryzen 7 5800X 8-Core Processor
ProcessorType=3
Revision=8448

Versions of relevant libraries:
[pip3] lion-pytorch==0.0.7
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.3
[pip3] open-clip-torch==2.7.0
[pip3] pytorch-lightning==2.0.1
[pip3] torch==2.1.0.dev20230404+cu118
[pip3] torchdiffeq==0.2.3
[pip3] torchmetrics==0.11.4
[pip3] torchsde==0.2.5
[pip3] torchvision==0.16.0.dev20230404+cu118
[conda] Could not collect
</details>

**Comment by ngimel** [comment] 2023-04-11 21:03
Duplicate of #98140

**Closed by ngimel** 2023-04-11 21:03 UTC

**Comment by AwayFromKeyboardwarrior** [comment] 2024-08-31 04:29
for me, when i did
tokenized = tokenizer(text, padding=True, truncation=True, return_tensors="pt")
it showed that error, but after changing the tokenizer to below
tokenized = (text,add_special_tokens=True,max_length=args.max_seq_length,padding='max_length',truncation=True,return_tensors="pt")
I don't see that error anymore.
