### ISSUE TITLE
[compile] output does not match eager mode

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#100075] opened 2023-04-26 07:25 UTC
### 🐛 Describe the bug

```python
import torch
from torch import nn
from torchvision.models import resnet18
from torch._dynamo import allow_in_graph
from functools import wraps
from functorch import make_functional_with_buffers, vmap, grad

def traceable(f):
    f = allow_in_graph(f)

    @wraps(f)
    def wrapper(*args, **kwargs):
        return f(*args, **kwargs)

    return wrapper

torch.manual_seed(42)
device = 'cpu'  # also fails on CUDA

model = resnet18(pretrained=False, norm_layer=(lambda c: nn.GroupNorm(min(c, 32), c)))
model.to(device)
model.eval()

fnet, params, buffers = make_functional_with_buffers(model)

x = torch.randn(10, 3, 224, 224, device=device)
f = lambda p, b, x : fnet(p, b, x).sum()

# Works for this simpler function
# f = lambda p, b, x: (torch.sin(x) + torch.cos(x) + torch.exp(x)).sum()

f = grad(f)

expected = f(params, buffers, x)
actual = torch.compile(traceable(f))(params, buffers, x)

torch.testing.assert_close(actual, expected)
```

Output
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 9406 / 9408 (100.0%)
Greatest absolute difference: 0.12333643436431885 at index (0, 2, 3, 4) (up to 1e-05 allowed)
Greatest relative difference: 41.227630615234375 at index (5, 0, 0, 6) (up to 1.3e-06 allowed)

```

### Versions

master

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @Chillee @samdow @janeyx99 @SherlockNoMad @wconstab @soumith @ngimel

**Comment by gchanan** [comment] 2023-04-26 14:59
CC @zou3519

**Comment by yanielc** [comment] 2023-04-28 05:50
I am seeing the issue, even with the minimal code from the torch.compile [tutorial](https://pytorch.org/tutorials/intermediate/torch_compile_tutorial.html).

``` 
    import torch
    from torchvision.models import resnet18

    model = resnet18().to(torch.float32).cuda()
    inp = torch.randn(100, 3, 128, 128).to(torch.float32).cuda()
    out1 = model(inp)

    model_opt = torch.compile(model, mode="reduce-overhead")
    out2 = model_opt(inp)

    print(torch.testing.assert_close(out1, out2), atol=1e-3)
```    

Prints the following:

```
AssertionError: Tensor-likes are not close!

Mismatched elements: 97157 / 100000 (97.2%)
Greatest absolute difference: 0.001302957534790039 at index (19, 516) (up to 1e-05 allowed)
Greatest relative difference: 111.66625463535229 at index (30, 755) (up to 1.3e-06 allowed)
```

**Comment by anijain2305** [comment] 2023-04-28 13:33
Thanks for reporting. Looking into it.

**Comment by anijain2305** [comment] 2023-04-28 13:40
@yanielc The `atol` is outside of assert_close and therefore, it looked so bad. This passes

~~~
import torch
from torchvision.models import resnet18

model = resnet18().to(torch.float32).cuda()
inp = torch.randn(100, 3, 128, 128).to(torch.float32).cuda()
out1 = model(inp)

model_opt = torch.compile(model, mode="reduce-overhead")
out2 = model_opt(inp)

torch.testing.assert_close(out1, out2, atol=5*1e-3, rtol=1e-3)

~~~

**Comment by zou3519** [comment] 2023-04-28 13:44
I put the hi-pri back so that we can investigate @kshitij12345's example. I agree that @yanielc's example is just floating point precision.

**Comment by ngimel** [comment] 2023-04-28 15:48
@kshitij12345 does it fail with GroupNorm only, or with default BatchNorm also?

**Comment by kshitij12345** [comment] 2023-04-28 17:57
It is failing with default BatchNorm as well

<details>

```python
import torch
from torch import nn
from torchvision.models import resnet18
from torch._dynamo import allow_in_graph
from functools import wraps
from functorch import make_functional_with_buffers, vmap, grad

def traceable(f):
    f = allow_in_graph(f)

    @wraps(f)
    def wrapper(*args, **kwargs):
        return f(*args, **kwargs)

    return wrapper

torch.manual_seed(42)
device = 'cpu'  # also fails on CUDA

model = resnet18(pretrained=False)
model.to(device)
model.eval()

fnet, params, buffers = make_functional_with_buffers(model)

x = torch.randn(10, 3, 224, 224, device=device)
f = lambda p, b, x : fnet(p, b, x).sum()

# Works for this simpler function
# f = lambda p, b, x: (torch.sin(x) + torch.cos(x) + torch.exp(x)).sum()

f = grad(f)

expected = f(params, buffers, x)
actual = torch.compile(traceable(f))(params, buffers, x)

torch.testing.assert_close(actual, expected, atol=1e-3, rtol=1e-3)

```

Output
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 3877 / 9408 (41.2%)
Greatest absolute difference: 0.027460098266601562 at index (37, 0, 0, 5) (up to 0.001 allowed)
Greatest relative difference: 6.730027675628662 at index (45, 0, 0, 5) (up to 0.001 allowed)

The failure occurred for item [0]
```

</details>

**Comment by ezyang** [comment] 2023-04-29 20:19
Updated accuracy minifier successfully extracts this. Minifying.

**Comment by ezyang** [comment] 2023-04-29 20:22
Analyze suggests the divergence happens only at the very end:

```
OK at convolution_1: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 64, 56, 56])                
OK at convolution_2: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 64, 56, 56])                
OK at convolution_3: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 64, 56, 56])                
OK at convolution_4: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 64, 56, 56])                
OK at convolution_5: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 128, 28, 28])               
OK at convolution_6: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 128, 28, 28])               
OK at convolution_7: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 128, 28, 28])               
OK at convolution_8: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 128, 28, 28])               
OK at convolution_9: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 128, 28, 28])               
OK at convolution_10: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 256, 14, 14])              
OK at convolution_11: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 256, 14, 14])              
OK at convolution_12: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 256, 14, 14])              
OK at convolution_13: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 256, 14, 14])              
OK at convolution_14: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 256, 14, 14])              
OK at convolution_15: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 512, 7, 7])                
OK at convolution_16: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 512, 7, 7])                
OK at convolution_17: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 512, 7, 7])                
OK at convolution_18: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 512, 7, 7])                
OK at convolution_19: RMSE (res-fp64): 0.00000, (ref-fp64): 0.00000 and shape=torch.Size([10, 512, 7, 7])                
```

**Comment by ezyang** [comment] 2023-04-29 23:24
I think this is not a real problem. Minification reveals that the divergence is occurring on a less than test inside the network. You are not loading pretrained weights and you are sending random input to the network. It can easily be the case that the network is unstable as is and small perturbations (which are valid for inductor) are causing a wildly different classification result. Unfortunately I cannot easily confirm this is the case as you are using a non-standard norm layer and I don't have a pretrained model for that ;)

**Comment by ezyang** [comment] 2023-04-30 12:20
I ran the minifier again overnight but instructed it only to allow for divergence on floating point numbers. I got a relatively large repro https://gist.github.com/ezyang/9809906a6c56faef90235bae503175f1

```
[2023-04-30 05:14:55,529] torch._dynamo.utils: [ERROR] RMSE (res-fp64): 0.00017, (ref-fp64): 0.00000 and shape=torch.Size([10, 32, 8])
```

But if you look carefully all it is doing is taking the small accumulated errors from the < 0 truncation and then accumulating them together in a sum

```
        le_5 = torch.ops.aten.le.Scalar(relu_4, 0);  relu_4 = None
        where_5 = torch.ops.aten.where.self(le_5, scalar_tensor, getitem_37);  le_5 = scalar_tensor = getitem_37 = None
        view_56 = torch.ops.aten.view.default(where_5, [10, 32, 8, 196]);  where_5 = None
        mul_106 = torch.ops.aten.mul.Tensor(view_56, view_8);  view_56 = view_8 = None
        sum_26 = torch.ops.aten.sum.dim_IntList(mul_106, [3]);  mul_106 = None
        return (sum_26,)
```

at which point we only *slightly* exceed our tolerance.  So if we had used @Chillee's t-test idea, this difference probably wouldn't have been statistically significant.

I suppose another experiment we can do on the repro is repeatedly feed in the real floating point inputs and plot out which operations diverge the most, to figure out where most of the precision change is coming from. I haven't coded this up yet though.

**Comment by yanielc** [comment] 2023-05-02 08:04
> @yanielc The `atol` is outside of assert_close and therefore, it looked so bad. This passes
> 
> ```
> import torch
> from torchvision.models import resnet18
> 
> model = resnet18().to(torch.float32).cuda()
> inp = torch.randn(100, 3, 128, 128).to(torch.float32).cuda()
> out1 = model(inp)
> 
> model_opt = torch.compile(model, mode="reduce-overhead")
> out2 = model_opt(inp)
> 
> torch.testing.assert_close(out1, out2, atol=5*1e-3, rtol=1e-3)
> ```

Thanks for the response. Ok, I was expecting equality at quite high precision. But good to know. Actually, my question came up from because in my team we are working with another model whose outputs and metrics performance change drastically when using torch.compile.

**Comment by ezyang** [comment] 2023-05-02 15:07
I'm currently working on our accuracy debugging tools and I would like to help. If you are on master, try the new accuracy repro extraction tools, they are much much better. I'll write a dev-discuss post about it.

**Comment by ezyang** [comment] 2023-05-03 16:24
Post as promised: https://dev-discuss.pytorch.org/t/major-updates-to-the-after-aot-accuracy-minifier/1241

I think there is some sensitivity here to cudnn or not. In fact, when I run your script as is on master, without any atol/rtol setting, I don't even get any divergence at all. If you are able to give us a repro for the real case I'm also happy to take a look.

**Comment by kshitij12345** [comment] 2023-05-03 16:30
Let me try that again on master.

The real case was that I was trying to torch.compile the above model which uses functorch from torchbenchmark repository

Ref: https://github.com/kshitij12345/benchmark/blob/9eb84597fde018cb83e6a012a5837df561dd325a/torchbenchmark/models/functorch_dp_cifar10/__init__.py#L84-L110

**Comment by ezyang** [comment] 2023-05-03 16:58
I guess my point is, I don't expect it to be fixed on master, but it's also not obvious to me that there actually is a problem. Does functorch_dp_cifar10 have pretrained weights?

**Comment by kshitij12345** [comment] 2023-05-03 17:03
> Does functorch_dp_cifar10 have pretrained weights?

I don't think so. But since, torch.compile is also meant to be used for training, it probably shouldn't diverge on randomly initialised model. Wdyt?

Also, I ran the snippet with `TORCHDYNAMO_REPRO_AFTER="aot" TORCHDYNAMO_REPRO_LEVEL=4` and got following error as expected.
```
File "/home/kshiteej/Pytorch/pytorch_functorch/torch/_dynamo/repro/after_aot.py", line 154, in inner_debug_fn
    raise AccuracyError("Bad accuracy detected")
``` 

But then running `python repro.py analyze` seems to pass successfully
```bash
$ python repro.py analyze
Loading inputs: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████| 63/63 [00:00<00:00, 2746.65it/s]
Compiling: 0it [00:11, ?it/s]
Saving inductor intermediates:   0%|                                                                                                | 0/20 [00:00<?, ?it/s][2023-05-03 16:58:02,091] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Saving inductor intermediates:   5%|████▍                                                                                   | 1/20 [00:02<00:54,  2.88s/it][2023-05-03 16:58:03,606] torch._inductor.utils: [WARNING] using triton random, expect difference from eager
Saving inductor intermediates: 100%|███████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:04<00:00,  4.17it/s]
Checking inductor determinism: 100%|███████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 49.49it/s]
Saving float64 intermediates: 100%|████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 14.51it/s]
Checking float64 determinism: 100%|████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:01<00:00, 17.96it/s]
Checking divergence: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [00:00<00:00, 40.78it/s]
```

**Comment by ezyang** [comment] 2023-05-03 18:25
My point is that you can't randomly initialize weights, show eager and compile diverge, and say compile is buggy. It might be fine if the model training converges anyway.

**Comment by ezyang** [comment] 2023-05-03 21:16
OK, so when I use `aot_eager_decomp_partition` it also reproduces the divergence. So it could just be a decomp thing.

**Comment by kshitij12345** [comment] 2023-05-04 06:29
Thanks for the hint @ezyang

Looks like the problem is with `group_norm` decomposition.

With following patch the assert passes

```patch
diff --git a/torch/fx/experimental/proxy_tensor.py b/torch/fx/experimental/proxy_tensor.py
index c6c8c68a9c8..913ae6adc4e 100644
--- a/torch/fx/experimental/proxy_tensor.py
+++ b/torch/fx/experimental/proxy_tensor.py
@@ -260,6 +260,7 @@ def proxy_call(proxy_mode, func, pre_autograd, args, kwargs):
     if not pytree.tree_all_only(torch.Tensor, can_handle_tensor, (args, kwargs)):
         return NotImplemented
 
+    popped = CURRENT_DECOMPOSITION_TABLE.pop(torch.ops.aten.native_group_norm.default, None)
     if func in CURRENT_DECOMPOSITION_TABLE:
         with proxy_mode:
             r = CURRENT_DECOMPOSITION_TABLE[func](*args, **kwargs)
```

**Comment by voznesenskym** [comment] 2023-11-13 23:12
@kshitij12345 can you check if this is still happening?

**Comment by bdhirsh** [comment] 2023-12-12 01:01
This still gives wrong results for me locally

**Comment by tugsbayasgalan** [comment] 2024-03-13 19:08
This still happens today.

**Comment by kshitij12345** [comment] 2024-03-13 19:34
cc: @guilhermeleobas

**Comment by xmfan** [comment] 2024-05-21 18:37
@guilhermeleobas have you had the chance to look at this yet?

**Comment by guilhermeleobas** [comment] 2024-05-21 18:44
Not yet. I forgot about this one.

**Comment by bdhirsh** [comment] 2024-06-20 19:21
After talking with @zou3519: this repro uses both:

* decomps (like `group_norm`)

* the functional_call API

We should figure out which of these two is causing the divergence (e.g. is dynamo handling the functional_call API properly)

**Comment by zou3519** [comment] 2024-07-23 19:02
I'm getting a segfault on a modified version of this test case (backend="inductor" instead exhibits a correctness errors)
```py
import torch
from torch import nn
from torchvision.models import resnet18

torch.manual_seed(42)
device = 'cpu'

model = resnet18(pretrained=False, norm_layer=(lambda c: nn.GroupNorm(min(c, 32), c)))
model.to(device)

x = torch.randn(10, 3, 224, 224, device=device)

def compute_grad(x): # E: Function is missing a type annotation  [no-untyped-def]
    loss = model(x).sum()
    return torch.autograd.grad(loss, list(model.parameters()))

expected = compute_grad(x)
actual = torch.compile(compute_grad, backend="aot_eager_decomp_partition")(x)

torch.testing.assert_close(actual, expected)
```

**Comment by zou3519** [comment] 2024-07-23 21:00
I think (aside from the segfault) this is just "resnet18 doesn't have the best numerics with random data". Evidence:
- I compared torch.compile (float32) vs eager (float32) vs eager (float64) vs compile (float64). 
- compile (float64) and eager (float64) pass the checks.
- eager (float32) and eager (float64) differ a lot (0.16 absolute 20 relative), torch.compile (float32) and eager (float64) also differ a lot (0.18 absolute 55 relative). The implication is that the model doesn't have good numerical accuracy in float32 (it differs from the float64 result) so anything goes.
- script: https://gist.github.com/zou3519/71e8718fd3c71d21dd12b5e1e13a301c

Though the segfault is concerning to me

**Comment by zou3519** [comment] 2024-07-24 14:59
Closing this one as expected, going to open a new one for the segfault

**Closed by zou3519** 2024-07-24 14:59 UTC
Labels: high priority, triaged, actionable, oncall: pt2, module: functorch, module: decompositions, module: pt2 accuracy, module: pt2-dispatcher
