### ISSUE TITLE
Possible support of mean operation on bool Tensor

### ISSUE THREAD

**Issue by kirk86** [pytorch/pytorch#78889] opened 2022-06-05 11:02 UTC
### 🚀 The feature, motivation and pitch

Numpy seems to support arithmetic operations on boolean arrays.
For instance one could do the following on numpy.

```
x = np.array([True, False, True])
x.mean()
0.6666666666666666
```

But on pytorch this is not supported yet.
```
x = torch.tensor([True, False, True])
x.mean()

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_1964789/1739705503.py in <module>
      1 x = torch.tensor([True, False, True])
----> 2 x.mean()

RuntimeError: mean(): input dtype should be either floating point or complex dtypes. Got Bool instead.
```

### Alternatives

But it seems that in pytorch the following operations are supported on bool Tensors.
```
x = torch.tensor([True, False, True])
x.sum().div(len(x))
tensor(0.6667)
```

These operations `mean(x) = x.sum().div(len(x))` in principle are equivalent but the difference between them is a type cast I believe?

I think what pytorch does is converting the tensor `x` into floating point via the operation `x.sum()` and from there you are simply dividing 2 floating point numbers. 

The question is what is `mean` doing internally, haven't check the code to see how is implemented but my guess is that it first checks the type of tensor `x` and if not in float or complex reject doing any operation, that's my best guess so far?

### Additional context

Here's a [discussion](https://discuss.pytorch.org/t/why-doesnt-mean-work-on-bool-tensors/143322) on the forums regarding this issue.

**Comment by vadimkantorov** [comment] 2022-06-05 23:19
duplicate of https://github.com/pytorch/pytorch/issues/64897 ?

**Comment by ezyang** [comment] 2022-06-06 20:15
ya

**Closed by ezyang** 2022-06-06 20:15 UTC
