### ISSUE TITLE
MPS backed returning wrong results 

### ISSUE THREAD

**Issue by tonytorm** [pytorch/pytorch#120403] opened 2024-02-22 14:22 UTC
### 🐛 Describe the bug

quick copy paste of the preview of theresulting tensors

**gpu_emission** = {Tensor: (1, 3094, 28)} tensor([[[-0.1032, -4.6794, -5.0462,  ..., -7.4768, -7.4350, -7.9886],\n         [-0.0953, -4.7485, -5.0339,  ..., -7.6503, -7.8024, -8.3415],\n         [-0.1166, -4.6339, -4.9951,  ..., -7.2928, -7.6421, -7.9455],\n         ...,\n         [-0.1068, -4.6564, -

**cpu emission** = tensor([[[-5.4571e-04, -1.0208e+01, -1.0352e+01,  ..., -1.0278e+01,
          -1.2886e+01, -1.2079e+01],
         [-5.4285e-04, -1.0074e+01, -1.0111e+01,  ..., -1.0475e+01,
          -1.3170e+01, -1.2462e+01],
         [-5.2665e-04, -9.7797e+00, -9.8958e+00,  ..., -1.0722e+01,
          -1.3586e+01, -1.2895e+01],
         ...,

as you can see there is a substantial differnce in the values

### Versions

just writing little code as the issue is very easy to recreate

`device_gpu = torch.device("mps")
`
  `model = bundle.get_model(with_star=False).to(device_gpu, non_blocking=False)
`  
`with torch.inference_mode():
`  
`.   emission, _ = model(waveform.to(device_gpu))
`

this produces completely wrong emissions, the same code provides very precise results if ran on the cpu device (at more and less half the speed unfortunately)

Reporting the same issue on the wav2vec github as I'm not capable of understanding where the the actual problem is located, loading the model to cpu or gpu provides same result (in terms of the model object data) but the inferences return 2 substantially different results.

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment] 2024-02-22 18:13
@tonytorm can you provide a link to a model you are referring to?

**Comment by tonytorm** [comment] 2024-02-22 20:27
The model is the wav2vec2, downloadable through the torchaudio pipelines: 

`bundle = torchaudio.pipelines.MMS_FA`
 `model = bundle.get_model(with_star=False).to(device)`


I can give you more insights as well, the problem is with the gelu forward pass, I actually noticed that you replied to a very similar issue here:

**issue**: https://github.com/pytorch/pytorch/issues/98212

it appears to be a non-contiguous memory issue, I patched the forward function in one of the auxiliary scripts and fixed it, I am going to update the issue in the wav2vec2 git as well.

**Comment by skotapati** [comment] 2024-08-30 18:22
As the related gelu issues have been closed and there hasn't been any recent activity, closing this issue. Please reopen if the issue is observed again, repro code would also be appreciated. Thanks!

**Closed by skotapati** 2024-08-30 18:22 UTC
Labels: needs reproduction, triaged, module: correctness (silent), module: mps
