### ISSUE TITLE
ONNX export for sparse_coo_tensor

### ISSUE THREAD

**Issue by mszuyx** [pytorch/pytorch#71786] opened 2022-01-25 22:37 UTC
### 🚀 The feature, motivation and pitch

We developed a CNN model in pytorch that largely relying **torch.sparse.FloatTensor** as well as functions like: **torch.sparse.sum** and **torch.sparse.mm**. The use of spare tensors greatly enhance the runtime performance of our model and requires much much less GPU memory. 

We had a great experience developing the model, and now we are looking forward to converting the trained model to ONNX and then complete the deployment process using Openvino.
However, it appears that the latest opset version (which I believe it is 14) has not yet support sparse_coo_tensor conversion just yet.

We wonder if this is already an ongoing process for the torch team and when should we expect to have this feature in the future?
Thanks!  :  )

cc @nikitaved @pearu @cpuhrsch

**Comment by garymm** [comment] 2022-02-03 02:08
Duplicate of #35294

**Closed by garymm** 2022-02-03 02:08 UTC
Labels: module: sparse, module: onnx, triaged

**Comment by erwangccc** [comment] 2023-03-27 03:23
@mszuyx 

Hi, have you solved it?

**Comment by mszuyx** [comment] 2023-03-27 03:29
@erwangccc Unfortunately, I didn't. I "move" the part of the model that requires torch.sparse outside of the model since these operations don't have trainable parameters (for us, they so happen to live at the end of the model, making them easy to be moved). We converted the model to ONNX and handled the sparse operations in numpy.

**Comment by erwangccc** [comment] 2023-03-27 05:27
@mszuyx So you doesn't convert the part model with a torch.sparse tensor to ONNX and just use numpy to replace some sparse operations, right?

**Comment by mszuyx** [comment] 2023-03-27 05:32
@erwangccc That's the idea. If that part has no parameter, it can be outside of the model. (Well, it worked since we only needed ONNX for deployment. The training has been done in PyTorch.) I wish you luck! And please let me know if you find the proper way to handle it!

**Comment by erwangccc** [comment] 2023-03-27 05:36
@mszuyx Thank you, got it. In my case the sparse tensor is trainable parameter. I'll share some info with you if i find a proper way.

**Comment by mszuyx** [comment] 2023-03-27 05:38
@erwangccc Can you break your model into two parts? Has the sparse operation been done outside and fed them back to the second part of the model?

**Comment by erwangccc** [comment] 2023-03-27 06:11
@mszuyx 
Many sparse tensors are in my model. So i think it's too complicated that break my model into many parts.
