### ISSUE TITLE
Exception on aten.index_put_(accumulate=True) with mixed types of indices

### ISSUE THREAD

**Issue by sangongs** [pytorch/pytorch#85973] opened 2022-09-30 15:02 UTC
### 🐛 Describe the bug

```
import torch
def test(device, accumulate):
    x = torch.randn([2, 3, 4], device=device)
    i1 = torch.as_tensor([0, 1], device=device)
    i2 = torch.as_tensor([True, True, False], device=device)
    v = torch.randn([], device=device)
    torch.ops.aten.index_put_(x, [i1, i2, None], v, accumulate)
    print(f"Test on {device}(accumulate={accumulate}) passed")

test('cpu', False)
test('cuda', False)
test('cpu', True)
test('cuda', True)
```

Output
```
Test on cpu(accumulate=False) passed
Test on cuda(accumulate=False) passed
Test on cpu(accumulate=True) passed
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb Cell 1 in <cell line: 13>()
     [11](vscode-notebook-cell://ssh-remote%2Bpytorch-dev/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=10) test('cuda', False)
     [12](vscode-notebook-cell://ssh-remote%2Bpytorch-dev/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=11) test('cpu', True)
---> [13](vscode-notebook-cell://ssh-remote%2Bpytorch-dev/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=12) test('cuda', True)

/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb Cell 1 in test(device, accumulate)
      [5](vscode-notebook-cell://ssh-remote%2Bpytorch-dev/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=4) i2 = torch.as_tensor([True, True, False], device=device)
      [6](vscode-notebook-cell://ssh-remote%2Bpytorch-dev/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=5) v = torch.randn([], device=device)
----> [7](vscode-notebook-cell://ssh-remote%2Bpytorch-dev/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=6) torch.ops.aten.index_put_(x, [i1, i2, None], v, accumulate)
      [8](vscode-notebook-cell://ssh-remote%2Bpytorch-dev/fsx/users/guoqiang/work/torchdynamo/bool_index.ipynb#W0sdnNjb2RlLXJlbW90ZQ%3D%3D?line=7) print(f"Test on {device}(accumulate={accumulate}) passed")

File /fsx/users/guoqiang/work/torchdynamo-env/lib/python3.10/site-packages/torch/_ops.py:437, in OpOverloadPacket.__call__(self, *args, **kwargs)
    432 def __call__(self, *args, **kwargs):
    433     # overloading __call__ to ensure torch.ops.foo.bar()
    434     # is still callable from JIT
    435     # We save the function ptr as the `op` attribute on
    436     # OpOverloadPacket to access it here.
--> 437     return self._op(*args, **kwargs or {})

RuntimeError: linearIndex.numel()*sliceSize*nElemBefore == expandedValue.numel() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1664176352726/work/aten/src/ATen/native/cuda/Indexing.cu":326, please report a bug to PyTorch. number of flattened indices did not match number of elements in the value tensor: 8 vs 2
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0.dev20220929+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.24.1
Libc version: glibc-2.27

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1069-aws-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.112
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.3
[pip3] torch==1.13.0.dev20220929+cu116
[pip3] torchdynamo==1.13.0.dev0
[pip3] torchtext==0.14.0.dev20220929
[pip3] torchvision==0.14.0.dev20220929+cu116
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] torch                     1.13.0.dev20220929+cu116          pypi_0    pypi
[conda] torchdynamo               1.13.0.dev0               dev_0    <develop>
[conda] torchtext                 0.14.0.dev20220929          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220929+cu116          pypi_0    pypi

**Comment by ngimel** [comment] 2022-10-02 06:10
This is not due to mixed type, same type fails in the same way:
```
import torch
def test(device, accumulate):
    x = torch.randn([2, 3, 4], device=device)
    i1 = torch.as_tensor([0, 1], device=device)
    i2 = i1 
    v = torch.randn([], device=device)
    torch.ops.aten.index_put_(x, [i1, i2, None], v, accumulate)
    print(f"Test on {device}(accumulate={accumulate}) passed")

test('cpu', False)
test('cuda', False)
test('cpu', True)
test('cuda', True)
```
and this is a duplicate of #79987, #76176 and multiple other issues.

**Closed by ngimel** 2022-10-02 06:10 UTC
