### ISSUE TITLE
Build with MKLDNN broken

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#22346] opened 2019-06-28 17:58 UTC
## 🐛 Bug

Source build fails because of MKL-DNN's use of `-Werror` and there being a warning thrown in the code 

## To Reproduce

```
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
REL_WITH_DEB_INFO=1 NO_CAFFE2_OPS=1 NO_CUDA=1 USE_FBGEMM=1 time python setup.py develop
```

```
[2/1073] Building CXX object third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.o
FAILED: third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.o 
/usr/lib64/ccache/c++  -DMKLDNN_DLL -DMKLDNN_DLL_EXPORTS -DMKLDNN_THR=MKLDNN_THR_OMP -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTH_BLAS_MKL -DUSE_C11_ATOMICS=1 -DUSE_MKL -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I../third_party/protobuf/src -I../cmake/../third_party/benchmark/include -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../third_party/ideep/mkl-dnn/include -Ithird_party/ideep/mkl-dnn/include -I../third_party/ideep/mkl-dnn/src -I../third_party/ideep/mkl-dnn/src/common -I../third_party/ideep/mkl-dnn/src/cpu -I../third_party/ideep/mkl-dnn/src/cpu/xbyak -I../third_party/ideep/mkl-dnn/src/../include -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem /home/jamesreed/miniconda3/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party -isystem ../cmake/../third_party/eigen -isystem /home/jamesreed/miniconda3/include/python3.7m -isystem /home/jamesreed/miniconda3/lib/python3.7/site-packages/numpy/core/include -isystem ../torch/include -Wno-deprecated -fvisibility-inlines-hidden -fopenmp -std=c++11 -fvisibility-inlines-hidden  -Wall -Wno-unknown-pragmas -Werror -fvisibility=internal -march=native -mtune=native -fPIC -Wformat -Wformat-security -fstack-protector-strong  -fopenmp -Wmissing-field-initializers  -Wno-strict-overflow  -O2 -g -DNDEBUG -fPIC   -DCAFFE2_USE_GLOO -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -Wno-maybe-uninitialized -Wno-strict-overflow -Wno-error=strict-overflow -Wno-tautological-compare -std=gnu++11 -MD -MT third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.o -MF third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.o.d -o third_party/ideep/mkl-dnn/src/CMakeFiles/mkldnn.dir/common/utils.cpp.o -c ../third_party/ideep/mkl-dnn/src/common/utils.cpp
../third_party/ideep/mkl-dnn/src/common/utils.cpp: In function ‘int mkldnn::impl::mkldnn_getenv(char*, const char*, int)’:
../third_party/ideep/mkl-dnn/src/common/utils.cpp:50:24: error: ‘char* strncpy(char*, const char*, size_t)’ output truncated before terminating nul copying as many bytes from a string as its length [-Werror=stringop-truncation]
                 strncpy(value, buffer, value_length);
                 ~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../third_party/ideep/mkl-dnn/src/common/utils.cpp:46:34: note: length computed here
             value_length = strlen(buffer);
                            ~~~~~~^~~~~~~~
cc1plus: all warnings being treated as errors
```

Build works fine with `USE_MKLDNN=0`.

## Expected behavior

Builds successfully

## Environment

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Fedora release 29 (Twenty Nine)
GCC version: (GCC) 8.2.1 20180801 (Red Hat 8.2.1-2)
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.168
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-include               2019.4                      243  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0

## Additional context

**Comment by xuhdev** [comment] 2019-07-02 21:28
It looks like having already been fixed long time ago, probably should ask ideep to update submodule. https://github.com/intel/mkl-dnn/commit/983e097a93a47ad3ffa0815c9c9b6eb7c610b732

**Comment by jgong5** [comment] 2019-07-09 23:46
@xuhdev Yes. The issue was fixed with MKL-DNN 0.19 and later releases. We will upgrade from IDEEP side to fix the problem. Thanks for the reminder.

**Comment by mdreammao** [comment] 2019-08-07 02:50
Is the problem fixed ? I download the latest version of pytorch, the problem is exists.

**Comment by jgong5** [comment] 2019-08-07 03:26
@mdreammao PR #22910 should solve the problem and it is being reviewed.

**Comment by mdreammao** [comment] 2019-08-07 04:56
> @mdreammao PR #22910 should solve the problem and it is being reviewed.

so which version should I download and to build with?

**Comment by gujinghui** [comment] 2019-08-07 06:17
@mdreammao
Pls try to apply the patch in #22910 , then run "git submodule update --init --recursive".

Thanks.

**Comment by mdreammao** [comment] 2019-08-07 07:59
Thank you! I'll try to build by your branch.@gujinghui

**Comment by vpirogov** [comment] 2019-08-16 23:02
Just wanted to let you know that Intel MKL-DNN does not use `-Werror` in the builds by default starting from v0.20.

**Comment by rgommers** [comment] 2019-12-07 09:20
`mkl-dnn` in `third_party/ideep/mkl-dnn/` is currently at `v0.21.1`. It enable `-Werror` only if `MKLDNN_WERROR` is set to `ON`, which is not default. gh-22910 was merged, and I can no longer reproduce this issue. So pretty sure it was fixed, closing.

**Closed by rgommers** 2019-12-07 09:20 UTC
Labels: high priority, module: mkldnn, topic: dependency bug, triaged
