### ISSUE TITLE
Floating point exception (core dumped) when divided by zero tensor with int data type (including int32 int64), instead of raising ZeroDivisionError

### ISSUE THREAD

**Issue by seanywang0408** [pytorch/pytorch#26536] opened 2019-09-20 11:25 UTC
## 🐛 Bug

When `torch.Tensor` is divided by **zero tensors** with data type as **int**, including **int8**, **int32**, **int64**, the program is terminated forcibly and throw **Floating point exception (core dumped) error**.
If run the code in jupyter notebook, the kernel would be killed. 

Based on my experiments,  the bug happens both in torch 1.0 and torch 1.4.

However, the bug would not happen if the dividend is not `torch.Tensor`.

## To Reproduce

`torch.ones(3, dtype=torch.int8) / torch.zeros(3, dtype=torch.int8)`

## Expected behavior

1. `ZeroDivisionError: division by zero`, which is the common bahavior in python when the divisor is zero.
    or 
2. get `tensor(nan)`. (when the data type is float, such as `torch.zeros(3, dtype=torch.float64) / torch.zeros(3, dtype=torch.float64)`)
    or
3. get **a tensor with very large value**. (when the dividend is an integer or float, such as `1 / torch.zeros(3, dtype=torch.int8))`)

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.6.3

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 384.145
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.0
[pip] numpydoc==0.6.0
[pip] torch==1.0.1.post2
[pip] torchsummary==1.5.1
[pip] torchvision==0.2.1
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] mkl                       2019.1                      144    defaults
[conda] mkl-include               2019.1                      144    defaults
[conda] mkl-service               1.1.2                    py36_3    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
[conda] pytorch                   0.4.0           py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torch                     1.0.1.post2               <pip>
[conda] torchsummary              1.5.1                     <pip>
[conda] torchvision               0.2.1                     <pip>
[conda] torchvision               0.2.1                      py_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

**Comment by f2013519** [comment] 2019-09-20 14:00
This is same as #327. This was initially marked as wontfix but it looks like there are plans to address this now (at least partially).

**Comment by seanywang0408** [comment] 2019-09-20 14:20
> This is same as #327. This was initially marked as wontfix but it looks like there are plans to address this now (at least partially).

Just curious about why there are various behaviors in Pytorch when divided by zero, even if they said that it is a hardware exception.

**Comment by fmassa** [comment] 2019-09-20 14:23
Closing as a duplicate of #327.

@seanywang0408 can you move your comments there?

**Closed** 2019-09-20 14:23 UTC

**Comment by f2013519** [comment] 2019-09-20 14:26
Behaviour is undefined for integer div by zero. Some architectures generate SIGFPE and some don't.

**Comment by OOXXXXOO** [comment] 2020-09-11 09:52
This is a bug？ I test the case from version 1.0 to 1.5 ，the all version will cause this bug with different model  from resnet to Mask RCNN ， so how i aviod this error by code？ What cause the bug？

**Comment by OOXXXXOO** [comment] 2020-09-11 09:55
Python 3.7.0 (default, Oct  9 2018, 10:31:47)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.ones(3, dtype=torch.int8) / torch.zeros(3, dtype=torch.int8)
[1]    624290 floating point exception (core dumped)  python
❯
❯ source activate nightly
❯ python
Python 3.7.9 (default, Aug 31 2020, 12:42:55)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.ones(3, dtype=torch.int8) / torch.zeros(3, dtype=torch.int8)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.
