### ISSUE TITLE
Segmentation fault occur when using index_copy_

### ISSUE THREAD

**Issue by MrFive5555** [pytorch/pytorch#20322] opened 2019-05-09 14:53 UTC
## 🐛 Bug

When using the index_copy_ function, the programme will throw a segmentation fault.

## To Reproduce

Run the code below:
```python
import torch
a = torch.randn(3, 5)
c = torch.zeros(3)
a.index_copy_(dim=1, index=torch.tensor([3]), source=c)
```
```bash
MrFive@mrfive-home:~$ python
Python 3.7.2 (default, Dec 29 2018, 06:19:36) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> a = torch.randn(3, 5)
>>> b = torch.zeros(3, 4)
>>> c = torch.zeros(3)
>>> a.index_copy_(dim=1, index=torch.tensor([3]), source=c)
Segmentation fault (core dumped)
```
I know the code following will work, but it seems that the issue above is an unexpected performent.
```python
a.index_copy_(dim=1, index=torch.tensor([3]), source=c.unsqueeze(1))
```
## Environment
```
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.2
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2019.1                      144    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.0.10           py37ha843d7b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.0.2            py37hd81dba3_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch-cpu               1.0.1               py3.7_cpu_2    pytorch
[conda] torchvision-cpu           0.2.2                      py_3    pytorch
```

**Comment by ailzhang** [comment] 2019-05-09 21:00
I'm adding "high pri" since I feel we should at least give a better error message instead of segfault, and it doesn't seem hard to do.

**Comment by gchanan** [comment] 2019-05-10 14:08
@izdeby can you take a look?

**Comment by ezyang** [comment] 2019-06-04 13:56
Reproduced on 5fcd37bd8fcd0d392e2fcacf4ab11dd43bb0d108

**Comment by VitalyFedyunin** [comment] 2019-06-10 22:33
Agree about error messaging, but it seems reasonable to have broadcasting here.

**Comment by SsnL** [comment] 2019-06-13 20:25
fixed via https://github.com/pytorch/pytorch/commit/4b45f08f8765549915417997c30ae8981f2ad125

**Comment by SsnL** [comment] 2019-06-13 20:27
I'll leave this open until a test is added. cc @izdeby

**Comment by izdeby** [comment] 2019-06-18 16:29
@Ssnl, i've created [PR](https://github.com/pytorch/pytorch/pull/21912/files) with a test to cover this case. Please, let me know if you would like me to add any other cases.

**Closed** 2019-06-19 01:42 UTC
Labels: high priority, module: operators, topic: crash, triaged
