### ISSUE TITLE
["GPU", "Float"] pair in ATen/preprocess_declarations.py

### ISSUE THREAD

**Issue by scopatz** [pytorch/pytorch#19414] opened 2019-04-18 17:46 UTC
## 🐛 Bug

I am working on fixing up https://github.com/pytorch/pytorch/pull/15310. I merged from master today (commit 2d0d153288c3b186c7232a71021b4f1648c14def), and I am seeing an error where `aten/src/ATen/preprocess_declarations.py` gets a "GPU" flag, instead of what I assume should be a "CUDA" flag.  Everything builds fine on master.

## To Reproduce

1. grab the `max_unpool` branch from https://github.com/Quansight/pytorch
1. `python setup.py install`
1. note the build failure due to a missing `aten/src/ATen/CPUBoolType.cpp` file, presumably because this file is not generated due to the issue above.

Here is the error message:

```
Traceback (most recent call last):
  File "/home/scopatz/pytorch/cmake/../aten/src/ATen/gen.py", line 612, in <module>
    generate_outputs()
  File "/home/scopatz/pytorch/cmake/../aten/src/ATen/gen.py", line 535, in generate_outputs
    declarations = preprocess_declarations.run(declarations)
  File "/home/scopatz/pytorch/aten/src/ATen/preprocess_declarations.py", line 255, in run
    process_types_and_backends(option)
  File "/home/scopatz/pytorch/aten/src/ATen/preprocess_declarations.py", line 57, in process_types_and_backends
    pairs = set(p for pair in pairs for p in expand(pair))
  File "/home/scopatz/pytorch/aten/src/ATen/preprocess_declarations.py", line 57, in <genexpr>
    pairs = set(p for pair in pairs for p in expand(pair))
  File "/home/scopatz/pytorch/aten/src/ATen/preprocess_declarations.py", line 52, in expand
    assert(p in all_backends)
AssertionError
make[2]: *** [aten/src/ATen/CPUBoolType.cpp] Error 1
make[1]: *** [caffe2/CMakeFiles/ATEN_CPU_FILES_GEN_TARGET.dir/all] Error 2
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 719, in <module>
    build_deps()
  File "setup.py", line 285, in build_deps
    build_dir='build')
  File "/home/scopatz/pytorch/tools/build_pytorch_libs.py", line 281, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/home/scopatz/miniconda/envs/pytorch/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', 'install']' returned non-zero exit status 2.
caffe2/CMakeFiles/ATEN_CPU_FILES_GEN_TARGET.dir/build.make:222: recipe for target 'aten/src/ATen/CPUBoolType.cpp' failed
CMakeFiles/Makefile2:4797: recipe for target 'caffe2/CMakeFiles/ATEN_CPU_FILES_GEN_TARGET.dir/all' failed
Makefile:140: recipe for target 'all' failed
```

## Expected behavior

To compile.

## Environment

```
$ python collect_env.py 
Collecting environment information...
PyTorch version: 1.1.0a0+3fcee48
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.14.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.1.0a0+3fcee48
[conda] mkl                       2019.3                      199  
[conda] mkl-include               2019.3                      199  
[conda] torch                     1.1.0a0+3fcee48          pypi_0    pypi
```

 - PyTorch Version (e.g., 1.0): master 
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): `python setup.py install`
 - Python version: 3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by soumith** [comment] 2019-04-18 18:01
I think this / the original PR might need a `git pull --rebase origin master` where origin is github.com/pytorch/pytorch

The problem is that the branch is not fully rebased yet onto upstream master, and is stuck in a stage where only part of the BoolTensor codegen is committed. (The BoolTensor work was stack-landed, so some commits might not be in a working state).

**Comment by scopatz** [comment] 2019-04-18 18:23
Ahh good catch, @soumith. However that doesn't seem like the issue.  I just updated the branch and did a clean rebuild (`rm -rf build/`) and am seeing the same issue.

**Comment by scopatz** [comment] 2019-04-18 18:32
Oh, I think I see the issue. `aten/src/ATen/native/native_functions.yaml` wasn't updated an this branch, and the GPU flag became CUDA at some point in the past few months.

**Closed** 2019-04-18 18:37 UTC
