### ISSUE TITLE
[FSDP] Full State Dict unable to save models, assert failure fqn in state dict. 10/23+ nightlies

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#87815] opened 2022-10-26 20:08 UTC
### 🐛 Describe the bug

1 - Run FSDP using T5 (HF or modified)
2 - Attempt to save model checkpoint using Full State Dict.
3 - Receive assert :

AssertionError: FSDP assumes _fsdp_wrapped_module.encoder.block.0.layer.0.SelfAttention.q.weight is in the state_dict 
but the state_dict only has odict_keys(['_fsdp_wrapped_module._flat_param', 
'_fsdp_wrapped_module.encoder.block.0._flat_param']). prefix=_fsdp_wrapped_module.encoder.block.0., module_name=layer.0.SelfAttention.q. param_name=weight rank=1.

This worked as of 10/13 nightly, but now fails with 1024 and 1026 nightlies to help pin down the cause. 

Full trace:
Traceback (most recent call last):
  File "/home/ubuntu/transformer_framework/main_training.py", line 407, in <module>
    fsdp_main()
  File "/home/ubuntu/transformer_framework/main_training.py", line 344, in fsdp_main
    model_checkpointing.save_model_checkpoint(
  File "/home/ubuntu/transformer_framework/model_checkpointing/checkpoint_handler.py", line 135, in save_model_checkpoint
    cpu_state = model.state_dict()
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2326, in state_dict
Traceback (most recent call last):
  File "/home/ubuntu/transformer_framework/main_training.py", line 407, in <module>
    fsdp_main()
  File "/home/ubuntu/transformer_framework/main_training.py", line 344, in fsdp_main
    model_checkpointing.save_model_checkpoint(
  File "/home/ubuntu/transformer_framework/model_checkpointing/checkpoint_handler.py", line 135, in save_model_checkpoint
    state_dict = super().state_dict(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    cpu_state = model.state_dict()
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2326, in state_dict
    Traceback (most recent call last):
module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
  File "/home/ubuntu/transformer_framework/main_training.py", line 407, in <module>
    state_dict = super().state_dict(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    fsdp_main()
  File "/home/ubuntu/transformer_framework/main_training.py", line 344, in fsdp_main
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    model_checkpointing.save_model_checkpoint(
      File "/home/ubuntu/transformer_framework/model_checkpointing/checkpoint_handler.py", line 135, in save_model_checkpoint
module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    cpu_state = model.state_dict()
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2326, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2326, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    state_dict = super().state_dict(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  [Previous line repeated 1 more time]
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2326, in state_dict
    state_dict = super().state_dict(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1697, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
        return func(*args, **kwargs)state_dict = super().state_dict(*args, **kwargs)

  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 365, in _post_state_dict_hook
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1697, in state_dict
    module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1695, in state_dict
    processed_state_dict = _post_state_dict_hook_fn[fsdp_module._state_dict_type](
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 85, in _full_post_state_dict_hook
    assert fqn in state_dict, (
AssertionError    : hook_result = hook(self, destination, prefix, local_metadata)FSDP assumes _fsdp_wrapped_module.encoder.block.0.layer.0.SelfAttention.q.weight is in the state_dict but the state_dict only has odict_keys(['_fsdp_wrapped_module._flat_param', '_fsdp_wrapped_module.encoder.block.0._flat_param']). prefix=_fsdp_wrapped_module.encoder.block.0., module_name=layer.0.SelfAttention.q. param_name=weight rank=3.    
module.state_dict(destination=destination, prefix=prefix + name + '.', keep_vars=keep_vars)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context

  [Previous line repeated 1 more time]
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py", line 2326, in state_dict
    return func(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 365, in _post_state_dict_hook
    processed_state_dict = _post_state_dict_hook_fn[fsdp_module._state_dict_type](
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 85, in _full_post_state_dict_hook
    assert fqn in state_dict, (
AssertionError: FSDP assumes _fsdp_wrapped_module.encoder.block.0.layer.0.SelfAttention.q.weight is in the state_dict but the state_dict only has odict_keys(['_fsdp_wrapped_module._flat_param', '_fsdp_wrapped_module.encoder.block.0._flat_param']). prefix=_fsdp_wrapped_module.encoder.block.0., module_name=layer.0.SelfAttention.q. param_name=weight rank=2.
    state_dict = super().state_dict(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1697, in state_dict
    hook_result = hook(self, destination, prefix, local_metadata)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 365, in _post_state_dict_hook
    processed_state_dict = _post_state_dict_hook_fn[fsdp_module._state_dict_type](
  File "/opt/conda/envs/pytorch/lib/python3.9/site-packages/torch/distributed/fsdp/_state_dict_utils.py", line 85, in _full_post_state_dict_hook
    assert fqn in state_dict, (
AssertionError: FSDP assumes _fsdp_wrapped_module.encoder.block.0.layer.0.SelfAttention.q.weight is in the state_dict but the state_dict only has odict_keys(['_fsdp_wrapped_module._flat_param', '_fsdp_wrapped_module.encoder.block.0._flat_param']). prefix=_fsdp_wrapped_module.encoder.block.0., module_name=layer.0.SelfAttention.q. param_name=weight rank=1.
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 28608 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 28610 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 28611 closing signal SIGTERM

### Versions

Collecting environment information...
PyTorch version: 1.14.0.dev20221026+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.3
Libc version: glibc-2.31

Python version: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:58:50)  [GCC 10.3.0] (64-bit runtime)
Python platform: Linux-5.15.0-1022-aws-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.6.124
GPU models and configuration: 
GPU 0: NVIDIA A10G
GPU 1: NVIDIA A10G
GPU 2: NVIDIA A10G
GPU 3: NVIDIA A10G

Nvidia driver version: 510.73.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221026+cu116
[pip3] torch-model-archiver==0.5.3b20220226
[pip3] torch-workflow-archiver==0.2.4b20220513
[pip3] torchaudio==0.12.1
[pip3] torchserve==0.6.0b20220513
[pip3] torchvision==0.15.0.dev20221026+cu116
[pip3] vit-pytorch==0.37.1
[conda] blas                      2.116                       mkl    conda-forge
[conda] blas-devel                3.9.0            16_linux64_mkl    conda-forge
[conda] captum                    0.5.0                         0    pytorch
[conda] cudatoolkit               11.6.0              hecad31d_10    conda-forge
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] liblapacke                3.9.0            16_linux64_mkl    conda-forge
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2022.1.0           h84fe81f_915    conda-forge
[conda] mkl-devel                 2022.1.0           ha770c72_916    conda-forge
[conda] mkl-include               2022.1.0           h84fe81f_915    conda-forge
[conda] numpy                     1.23.4           py39h3d75532_0    conda-forge
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     1.14.0.dev20221026+cu116          pypi_0    pypi
[conda] torch-model-archiver      0.5.3                    py39_0    pytorch
[conda] torch-workflow-archiver   0.2.4                    py39_0    pytorch
[conda] torchaudio                0.12.1               py39_cu116    pytorch
[conda] torchserve                0.6.0                    py39_0    pytorch
[conda] torchvision               0.15.0.dev20221026+cu116          pypi_0    pypi
[conda] vit-pytorch               0.37.1                   pypi_0    pypi

cc @ezyang @gchanan @zou3519 @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu

**Comment by lessw2020** [comment] 2022-10-26 20:12
Sharded State Dict works with no issue for the above scenario.

**Comment by H-Huang** [comment] 2022-10-26 22:49
cc @zhaojuanmao @rohan-varma @awgu for FSDP, @svekars was wondering if this regression is in 2.13 and if it will affect FSDP tutorials since those are releasing soon?

**Comment by awgu** [comment] 2022-10-26 22:50
It is not a regression for 1.13. I landed changes to `FlattenParamsWrapper` after branch cut relating to this.

**Comment by awgu** [comment] 2022-10-30 20:54
https://github.com/pytorch/pytorch/pull/87950

**Closed by awgu** 2022-10-30 20:54 UTC
Labels: high priority, triage review, oncall: distributed, module: fsdp
