### ISSUE TITLE
ImportError: cannot import name 'caffe2_pb2' on Windows 10. Python 3.6

### ISSUE THREAD

**Issue by alejo9719** [pytorch/pytorch#16725] opened 2019-02-04 19:44 UTC
## 🐛 Bug

I installed PyTorch via conda in a Windows 10 machine, Python 3.6 environment.

I get this error:
ImportError: cannot import name 'caffe2_pb2'

When trying to execute this tutorial:
https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html

Specifically when importing the Caffe2 ONNX Backend

## Traceback

Traceback (most recent call last):
  File "onnxLoader.py", line 9, in <module>
    import caffe2.python.onnx.backend as onnx_caffe2_backend
  File "C:\Users\alejo\AppData\Local\conda\conda\envs\pyTorchEnv\lib\site-packages\caffe2\python\__init__.py", line 2, in <module>
    from caffe2.proto import caffe2_pb2
ImportError: cannot import name 'caffe2_pb2'

## Environment

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.6.8
 - CUDA/cuDNN version: 9.0
 - GPU models and configuration: GeForce GTX 960M

**Comment by peterjc123** [comment] 2019-02-05 04:18
Yes, it's fixed in master and will be available in the upcoming v.1.0.1 release.

**Comment by peterjc123** [comment] 2019-02-05 04:22
Duplicate of https://github.com/pytorch/pytorch/issues/15156. Would you please close this PR?

**Closed** 2019-02-05 04:55 UTC
Labels: caffe2, windows
