### ISSUE TITLE
[MPS] Expand does not work for torch.uint8 type

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#82305] opened 2022-07-27 11:48 UTC
### 🐛 Describe the bug

Attempts to expand column of uint8 very often returns an empty tensor
```
% python -c "import torch; x=torch.randint(100, (2, 1), dtype=torch.uint8, device='mps');print(x, '\n', x.expand((2, 2)))"
tensor([[45],
        [60]], device='mps:0', dtype=torch.uint8)
tensor([[0, 0],
        [0, 0]], device='mps:0', dtype=torch.uint8)
```

But the same mysteriously works for int8 tensors:
```
% python -c "import torch; x=torch.randint(100, (2, 1), dtype=torch.int8, device='mps');print(x, '\n', x.expand((2, 2)))"
tensor([[13],
        [77]], device='mps:0', dtype=torch.int8)
tensor([[13, 13],
        [77, 77]], device='mps:0', dtype=torch.int8)
```

### Versions

trunk

cc @ezyang @gchanan @zou3519 @kulinseth @albanD

**Comment by malfet** [comment] 2022-07-27 14:17
Fixable by the following patch, but looks like a bug in MPS library itself:
```
diff --git a/aten/src/ATen/native/mps/operations/View.mm b/aten/src/ATen/native/mps/operations/View.mm
index 7fed4dea06e..4fa614ae6e2 100644
--- a/aten/src/ATen/native/mps/operations/View.mm
+++ b/aten/src/ATen/native/mps/operations/View.mm
@@ -35,7 +35,7 @@ static std::string getStridedKey(const ScalarType& dtype, const IntArrayRef& bas
          getArrayRefString(base_shape) + "]:[" + getArrayRefString(new_shape) + "]";
 }
 
-// initializes the MTLBuffers for tesnsor data and runs the MPSGraph for the view op
+// initializes the MTLBuffers for tensor data and runs the MPSGraph for the view op
 static Tensor& runViewGraph(ViewCachedGraph* cachedGraph, const at::Tensor& src, Tensor& output,
                             bool needsScatter, bool requires_sync = false)
 {
@@ -53,7 +53,7 @@ static Tensor& runViewGraph(ViewCachedGraph* cachedGraph, const at::Tensor& src,
   MPSStream* stream = getCurrentMPSStream();
   @autoreleasepool {
     NSMutableDictionary *feeds = [[NSMutableDictionary new] autorelease];
-    // in case of scatter, we use ouput tensor as input buffer and write the results back to the source buffer
+    // in case of scatter, we use output tensor as input buffer and write the results back to the source buffer
     feeds[cachedGraph->inputTensor] = [[[MPSGraphTensorData alloc] initWithMTLBuffer: needsScatter ? outputBuffer : sourceBuffer
                                                                                shape: inputShape
                                                                             dataType: inputType] autorelease];
@@ -66,9 +66,15 @@ static Tensor& runViewGraph(ViewCachedGraph* cachedGraph, const at::Tensor& src,
     for (int i = 0; i < sizes.size(); i++) {
       feeds[cachedGraph->strideTensors[i]] = getMPSGraphTensorFromScalar(stream, Scalar(strides[i]), MPSDataTypeInt32);
     }
+    // Workaround for MPSShaderLibrary bug
+    // TODO: Remove once https://github.com/pytorch/pytorch/issues/82305 is resolved
+    auto outputType = getMPSDataType(output.scalar_type());
+    if (outputType ==  MPSDataTypeUInt8) {
+        outputType =  MPSDataTypeInt8;
+    }
     MPSGraphTensorData* outputTensorData = [[[MPSGraphTensorData alloc] initWithMTLBuffer: outputBuffer
                                                                                     shape: outputShape
-                                                                                 dataType: getMPSDataType(output.scalar_type())] autorelease];
+                                                                                 dataType: outputType] autorelease];
     NSDictionary<MPSGraphTensor*, MPSGraphTensorData*>* results = @{
       cachedGraph->outputTensor : outputTensorData
     };
@@ -193,8 +199,14 @@ static ViewCachedGraph* createViewGraph(const Tensor& self, IntArrayRef size, In
         @autoreleasepool {
             MPSGraph* mpsGraph = make_mps_graph();
             newCachedGraph = new ViewCachedGraph(mpsGraph);
+            // Workaround for MPSShaderLibrary bug
+            // TODO: Remove once https://github.com/pytorch/pytorch/issues/82305 is resolved
+            auto inputType = getMPSScalarType(self.scalar_type());
+            if (inputType ==  MPSDataTypeUInt8) {
+                inputType =  MPSDataTypeInt8;
+            }
             // Self is the input tensor we are creating view of
-            newCachedGraph->inputTensor = mpsGraphRankedPlaceHolder(mpsGraph, getMPSScalarType(self.scalar_type()), getMPSShape(base_shape));
+            newCachedGraph->inputTensor = mpsGraphRankedPlaceHolder(mpsGraph, inputType, getMPSShape(base_shape));
             newCachedGraph->storageOffsetTensor = mpsGraphRankedPlaceHolder(mpsGraph, MPSDataTypeInt32, @[@1]);
             for (int i = 0; i < size.size(); i++) {
               newCachedGraph->strideTensors.push_back(mpsGraphRankedPlaceHolder(mpsGraph, MPSDataTypeInt32, @[@1]));
```

**Comment by kulinseth** [comment] 2022-07-27 18:51
@DenisVieriu97 can you take a look.

**Comment by kulinseth** [comment] 2022-08-08 19:05
@malfet , can we close this issue ?

**Comment by malfet** [comment] 2022-08-19 00:03
Sure, why not.

**Comment by kit1980** [comment] 2024-02-01 20:06
I've re-opened this as looks like the issue is still present.
See https://github.com/pytorch/pytorch/pull/118820
The test fails
> test_mps.py::TestMPS::test_bernoulli 2024-02-01 18:19:13.323 python3[31832:15284139] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderArray initWithObjects:count:]: attempt to insert nil object from objects[0]'

**Comment by kit1980** [comment] 2024-02-01 20:45
nevermind

**Closed by kit1980** 2024-02-01 20:45 UTC
Labels: high priority, triaged, module: correctness (silent), module: mps
