### ISSUE TITLE
torch.Tensor.to(memory_format=torch.contiguous_format) does not work properly.

### ISSUE THREAD

**Issue by liufeimath** [pytorch/pytorch#79813] opened 2022-06-17 21:53 UTC
### 🐛 Describe the bug

`torch.Tensor.to(memory_format=torch.contiguous_format)` has a bug when the underlying tensor is contiguous in memory blocks but not row-major / C-ordering. E.g. if a tensor is col-major/F-ordering, the `.to(...)` operation is a no-op, which goes against the description of what [`torch.contiguous_format`](https://pytorch.org/docs/stable/tensor_attributes.html#torch.torch.memory_format) does. Specifically, check the following code:

```python
a = torch.rand((2, 2))  # row-major
b = a.T  # column-major

print(a.stride())
# output: (2, 1), expected

print(b.stride())
# output: (1, 2), expected

print(b.to(memory_format=torch.contiguous_format).stride())
# output: (1, 2), unexpected, shouldn't it be transformed to row-major?

print(b.contiguous().stride())
# output: (2, 1), this works fine
```

### Versions

Collecting environment information...
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (x86_64)
GCC version: Could not collect
Clang version: 11.0.3 (clang-1103.0.32.62)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.3 (v3.8.3:6f8c8320e9, May 13 2020, 16:29:34)  [Clang 6.0 (clang-600.0.57)] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.10.0
[pip3] torchvision==0.11.1
[conda] Could not collect

cc @VitalyFedyunin @jamesr66a

**Comment by albanD** [comment] 2022-06-21 13:18
cc @mruberry who looked into the stride behavior of ops recently.

**Comment by yuguo68** [comment] 2022-06-23 18:38
It seems underneath `b.to(memory_format=torch.contiguous_format)` goes through the fast path https://github.com/pytorch/pytorch/blob/438142a5991a6544137d2565b47eacf4089a458b/aten/src/ATen/native/TensorConversions.cpp#L192-L195 and the `self` tensor is returned so the strides is wrong. 

The implementation of `to_will_alias` seems problematic: https://github.com/pytorch/pytorch/blob/438142a5991a6544137d2565b47eacf4089a458b/aten/src/ATen/native/TensorConversions.cpp#L178-L179

cc @swolchok to take a look.

**Comment by yuguo68** [comment] 2022-06-23 21:42
also, this is a duplicate of #62027

**Comment by swolchok** [comment] 2022-08-11 16:03
> cc @swolchok to take a look.

@yuguo68 in what way does it seem problematic? https://github.com/pytorch/pytorch/commit/4d8fc8693cbce0693cd4e278fb3eca0cd57d8976 directly extracted it from to().

**Comment by ezyang** [comment] 2022-10-21 01:51
closing this as dupe

**Closed by ezyang** 2022-10-21 01:51 UTC
Labels: triaged, module: memory format, module: python frontend
