### ISSUE TITLE
SegFault in aten::Tensor::~Tensor on exit after converting CUDA allocated GPU memory to GPU tensor

### ISSUE THREAD

**Issue by NathanSegerlind** [pytorch/pytorch#15949] opened 2019-01-11 00:04 UTC
## 🐛 Bug

I am encountering a segmentation fault when converting a CUDA allocated blob of memory
on the GPU into a tensor on the GPU.  The application seems to proceed as expected, but
segfaults during cleanup in calls to the aten and c10 tensor destructors.

## To Reproduce

Here  is the full C++ program I am running:

```

#include <torch/script.h>
#include <stdio.h>
#include <cuda.h>
#include <cuda_runtime.h>

using namespace at;

int main(int argc, const char* argv[]) {

    const unsigned int data[4] = {0, 1, 2, 3};
    const unsigned int N = 4;
    size_t size = sizeof (unsigned int) * N;

    unsigned int* cuda_pointer;
    cudaMalloc((void **) &cuda_pointer, size);
    cudaMemcpy(cuda_pointer, data, size, cudaMemcpyHostToDevice);

    auto gpu_tensor = torch::CUDA(at::kInt).tensorFromBlob(cuda_pointer,{N});
    auto cpu_tensor = gpu_tensor.toType(CPU(kInt));

    std::cout << "  data after the round trip:  ";
    auto cpu_a = cpu_tensor.accessor<int, 1>();
    for (int i = 0; i < N; i++) {

        std::cout << cpu_a[i] << ", ";
    }
    std::cout << "\n";

    cudaFree(cuda_pointer); // presence  or absence of this cudaFree call
                            // does not change the segfault on exit
}
```

### obeserved behavior
nathan@machine:~/pytorch-segmentation/read_cuda_buffer/build$ ./simple-test 
  data after the round trip:  0, 1, 2, 3, 
Segmentation fault (core dumped)

### Call stack at the segmentation fault:

std::_Function_handler<void (void*), void (*)(void*)>::_M_invoke(std::_Any_data const&, void*&&) (__functor=@0xf604c0: {_M_unused = {_M_object = 0x413b9d <at::noop_deleter(void*)>, _M_const_object = 0x413b9d <at::noop_deleter(void*)>, _M_function_pointer = 0x413b9d <at::noop_deleter(void*)>, _M_member_pointer = &virtual table offset 4275100, this adjustment 1}, _M_pod_data = \"\\235;A\\000\\000\\000\\000\\000\\001\\000\\000\\000\\000\\000\\000\"}, __args#0=<unknown type in /home/nathan/pytorch-segmentation/read_cuda_buffer/build/simple-test, CU 0x0, DIE 0xb62bd>)	
c10::deleteInefficientStdFunctionContext(void*) ()	
c10::TensorImpl::release_resources() ()	
c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::reset_ (this=0x7fffffffe0d0)	
c10::intrusive_ptr<c10::TensorImpl, c10::UndefinedTensorImpl>::~intrusive_ptr (this=0x7fffffffe0d0)	
at::Tensor::~Tensor (this=0x7fffffffe0d0)	
main (argc=1, argv=0x7fffffffe258)
## Expected behavior

output:
data after the round trip:  0, 1, 2, 3, 
...  but without the segfault :)

## Environment

 - PyTorch Version (e.g., 1.0): 1.0 (only libtorch)
 - OS (e.g., Linux): Ubuntu 16.04
 - How you installed PyTorch (`conda`, `pip`, source):   extraction of libtorch stable library

 - CUDA/cuDNN version:  CUDA 9.2
 - GPU models and configuration:  GTX 1080, nvidia 410.78

**Comment by ezyang** [comment] 2019-01-14 03:58
This is pretty weird. What happens if you explicitly pass in a no-op deleter, e.g.,

```
    auto gpu_tensor = torch::CUDA(at::kInt).tensorFromBlob(cuda_pointer,{N}, [&](void*) {});
```

Also, your syntax is not the current idiomatic way of creating a blob from a raw pointer, the modern way is:

```
auto gputensor = torch::from_blob(cuda_pointer, {N}, [&](void* ptr) { cudaFree(ptr); }, torch::kCUDA);
```

(I haven't tried running your example)

(Note to self: let's update the `tensorFromBlob` test case in atest to use the new idiomatic way)

**Comment by NathanSegerlind** [comment] 2019-01-14 19:00
Howdy ezyang!

Here's what is happening with the latest nightlies for libtorch that I pull about 10am Pacific time Jan 11th 2019:

**with the "no-op deleter"  that you first suggested:**   
The modified example  core dumps in the aten::Tensor destructor (same place as with the example first posted) 

**with the idiomatic method that you propose in the second line of your comment**  

This modification of the example throws an exception in the conversoin to CPU tensor..


(pytorch_36) nathan@machine:~/pytorch-segmentation/read_cuda_buffer/build$ ./simple-test 
terminate called after throwing an instance of 'c10::Error'
  what():  copy_from does not support automatic differentiation; use copy_ instead (_s_copy_from at /pytorch/torch/csrc/autograd/VariableTypeManual.cpp:287)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fa8fa279581 in /home/nathan/libtorch-cu90-nightly/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fa8fa278eba in /home/nathan/libtorch-cu90-nightly/libtorch/lib/libc10.so)
frame #2: torch::autograd::VariableType::_s_copy_from(at::Tensor const&, at::Tensor const&, bool) const + 0x60 (0x7fa9398f78f0 in /home/nathan/libtorch-cu90-nightly/libtorch/lib/libtorch.so.1)
frame #3: at::native::_s_copy__cpu(at::Tensor&, at::Tensor const&, bool) + 0xa6 (0x7fa92d016da6 in /home/nathan/libtorch-cu90-nightly/libtorch/lib/libcaffe2.so)
frame #4: <unknown function> + 0xa84772 (0x7fa92d26c772 in /home/nathan/libtorch-cu90-nightly/libtorch/lib/libcaffe2.so)
frame #5: at::TypeDefault::copy_(at::Tensor&, at::Tensor const&, bool) const + 0x108 (0x7fa92d31fca8 in /home/nathan/libtorch-cu90-nightly/libtorch/lib/libcaffe2.so)
frame #6: at::TypeDefault::copy(at::Tensor const&, bool, c10::optional<c10::Device>) const + 0x1dd (0x7fa92d2ef47d in /home/nathan/libtorch-cu90-nightly/libtorch/lib/libcaffe2.so)
frame #7: at::Tensor::toType(at::Type const&, bool) const + 0x98 (0x41957c in ./simple-test)
frame #8: main + 0x143 (0x41817a in ./simple-test)
frame #9: __libc_start_main + 0xf0 (0x7fa8f9eaf830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: _start + 0x29 (0x417689 in ./simple-test)

thanks for your help

**Comment by ezyang** [comment] 2019-01-15 05:35
That's... even more irregular. Self-assigning to look into this.

**Comment by d1ff** [comment] 2019-01-22 13:13
I encountered the same problem with opencv's GpuMat and tensor, how can I help?

**Comment by ezyang** [comment] 2019-03-20 20:10
I cannot reproduce this on abc171bd53ee00caa3ab638b770316583a0c6c5f. I'm going to check if I could ever have reproduced this.

**Comment by ezyang** [comment] 2019-03-20 20:26
I could not reproduce this on https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip either. I guess it's time to get on an Ubuntu docker image...

**Comment by ezyang** [comment] 2019-03-20 20:55
I am able to reproduce using  https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip on an Ubuntu docker image with the nvidia/cuda:9.2-cudnn7-devel Docker image.

I suspect this is a C++ compiler ABI incompatibility. Suggested workaround is to build PyTorch from source and try again.

**Comment by ezyang** [comment] 2019-03-20 20:55
For reference, I used gcc 4.8.5 on the machine I couldn't reproduce from; and gcc 7.3.0 on the machine I could reproduce from.

**Comment by ezyang** [comment] 2019-03-20 22:20
I bet the ABI incompatibility is std::function related.

**Comment by NathanSegerlind** [comment] 2019-03-22 21:05
> For reference, I used gcc 4.8.5 on the machine I couldn't reproduce from; and gcc 7.3.0 on the machine I could reproduce from.

If it helps refine things any... I'm getting it with gcc 5.4.0

**Comment by ezyang** [comment] 2019-03-24 18:41
@NathanSegerlind Yeah, that's consistent with the problem. Did building from source fix the problem for you?

**Comment by soumith** [comment] 2019-03-24 19:28
the incompatibility is wrt the GCC ABI that is different from gcc >= 5.1 and gcc < 5.1.

https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

We compile the binaries with the old ABI.

If you are compiling under gcc >= 5.1 and you want to use the binaries, define the flag `-D_GLIBCXX_USE_CXX11_ABI=0`. Alternatively, compile libtorch from source.

**Closed by soumith** 2019-03-24 19:28 UTC
Labels: abi

**Comment by deeplearning666** [comment] 2020-04-27 14:05
@NathanSegerlind Have you solved the problems? I met the same question with you! I'm looking for ward to hearing from you soon!

**Comment by csukuangfj** [comment] 2020-09-22 02:55
> If you are compiling under gcc >= 5.1 and you want to use the binaries, define the flag -D_GLIBCXX_USE_CXX11_ABI=0

I am facing the same problem even if the code is compiled with `-D_GLIBCXX_USE_CXX11_ABI=0`.
