### ISSUE TITLE
Meet a bug in complex index of Tensor, got random result every time.

### ISSUE THREAD

**Issue by AegeanYan** [pytorch/pytorch#96806] opened 2023-03-15 07:48 UTC
### 🐛 Describe the bug

I found this bug when I was reproducing someone's project. The code is easy to read: `sumtokens` is initialized as a 30523 * 256 size Tensor, `tokenids` is a Tensor with lenth 472 to index lines in `sumtokens`, and `tokens` is a Tensor sized 472 * 256. The wrong line means to add `tokens` to `sumtokens` indexed by `tokenids` . It went wrong because I got different result every time, and it got same result if I transfer it into Numpy.array. Also if I change the code style, it can get fixed result.  

My code is as follows:
~~~python
import torch
import torch.nn as nn
import numpy as np

import math
#torch.manual_seed(42)
sumtokens = torch.zeros(30523,256)
tokenids = torch.load('token_ids.pt')
tindex = torch.arange(0,472)
tokens = torch.load('tokens.pt')

# sumtokens = sumtokens.numpy()
# tokenids = tokenids.numpy()
# tindex = tindex.numpy()
# tokens = tokens.numpy()

sumtokens[tokenids] += tokens[tindex]###bug line
# for i in range(472):
#     sumtokens[tokenids[i]] += tokens[i] ##correct by change into this.
print(sum(map(sum,sumtokens)))
```
The fixed result in numpy() is:
-50.11308448069735
The fixed result in torch if you change to correct line is:
tensor(-65.1095)
The bug result can be:
tensor(-87.8888)
tensor(-83.6938)
tensor(-113.1932)
tensor(-119.6431)
...
```
~~~
You can get 'token_ids.pt' and 'tokens.pt' from https://github.com/AegeanYan/pytorch_issue

### Versions

```
Versions of relevant libraries:                                                                                              [2/1918]
[pip3] numpy==1.24.2                                                                                                                 
[pip3] torch==1.10.0+cu113                                                                                                           
[pip3] torchaudio==0.10.0+cu113
[pip3] torchvision==0.11.1+cu113
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] torch                     1.10.0+cu113             pypi_0    pypi
[conda] torchaudio                0.10.0+cu113             pypi_0    pypi
[conda] torchvision               0.11.1+cu113             pypi_0    pypi
```

I don't think it is caused by version corruption because I've tried this bug on colab and get same bug.

**Comment by soulitzer** [comment] 2023-03-16 03:02
I cannot reproduce this. The following always returns the same result:
```python
import torch

torch.manual_seed(42)

sumtokens = torch.randn(512, 32)
tokenids = torch.arange(0,472)
tindex = torch.arange(0,472)
tokens = torch.randn(512,32)

sumtokens[tokenids] += tokens[tindex]

print(sum(map(sum,sumtokens)))
```
Do you have a short self-contained snippet?

**Comment by AegeanYan** [comment] 2023-03-16 06:45
Hi, I have upload my data on https://github.com/AegeanYan/pytorch_issue and I have tried to make the same experiment as you. I don't have a short snippet to this problem because I met it by accident when debugging the project. It's so weird that as you have tried, simple random data cannot result in this problem. What needs to be concerned is that the 'tokenids' is not just arange() from 0 to 472. I'm going to upload a notebook for you to reproduce this

**Comment by AegeanYan** [comment] 2023-03-16 07:24
Hi, soulitzer. I've just found that on colab, things only go wrong when run on GPU, but on my server, both on GPU and CPU have bad result. Maybe it is caused by a kind of memory leak? But I want to know why. There is a colab link you can try to reproduce this bug. https://colab.research.google.com/drive/1-SmR0XGjP769lXsy7qBWczu7IN7UHUq8?usp=sharing

**Comment by soulitzer** [comment] 2023-03-16 13:10
Thanks for the repro, I was able to reproduce the issue.

You should use `torch.use_deterministic_algorithms(True)` if you want to get the same result every time. This is because  `sumtokens[tokenids] += tokens[tindex]` calls `index_put` underneath, which is normally non-deterministic, but will act deterministically when `use_deterministic_algorithms` is set. 

See: https://pytorch.org/docs/stable/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms

Closing because this is expected behavior.

**Closed by soulitzer** 2023-03-16 13:10 UTC
Labels: triaged, module: advanced indexing

**Comment by AegeanYan** [comment] 2023-03-16 13:21
Thank you so much for solving my problem.

**Comment by AegeanYan** [comment] 2023-03-16 13:29
I think this usage is risky in Pytorch because people would not set deterministic when training their large models, why don't add to new version Pytorch to throw out a warning or error when indices contain duplicate elements.

**Comment by soulitzer** [comment] 2023-03-16 13:32
> why don't add to new version Pytorch to throw out a warning or error when indices contain duplicate elements.

I think some people might rely on the the indices to contain duplicate elements, and for deep learning applications non-determinism tends to be OK.

**Comment by ngimel** [comment] 2023-03-16 17:50
`a[indices] += b[b_indices]` is inherently non-deterministic operation. With non-deterministic implementation, a random element from `b[b_indices]` would be added to `a` if `indices` has repeated indices, with deterministic implementation that element will be the same each time, but it would still correspond to a single value out of `b`, and not accumulate all corresponding values. So I'd argue that nondeterministic behavior here is not risky, it's expected (and the fact that only a single value is picked for update agrees with numpy). If you want to actually accumulate all contributions, then you should use `index_put` with `accum=True`
