### ISSUE TITLE
torch.split with tensor sizes fails in tracing

### ISSUE THREAD

**Issue by bddppq** [pytorch/pytorch#27551] opened 2019-10-08 18:23 UTC
## To Reproduce

Code
```python
import torch


class MyModule(torch.nn.Module):
    def forward(self, x):
        return torch.split(x, x.size(1))


m = MyModule()
x = torch.randn(1, 2, 3, 4)

# ok to run the model
m(x)

# fail to trace it
print(torch.jit.trace(m, x))
```

Error:

```shell
(tensor([[[[-0.8175, -0.3000,  0.0693, -1.0097],
          [-0.3261,  0.6817, -0.8282, -1.8818],
          [-1.1303,  1.8587,  0.0275, -0.2838]],

         [[ 0.2386,  0.3672,  1.0122, -1.3396],
          [ 0.6037, -0.8609,  0.6339,  0.8278],
          [ 1.0117, -0.3204, -1.6440,  2.8207]]]]),)

Traceback (most recent call last):
  File "/tmp/1.py", line 12, in <module>
    print(torch.jit.trace(m, x))
  File "torch/jit/__init__.py", line 860, in trace
    check_tolerance, _force_outplace, _module_class)
  File "torch/jit/__init__.py", line 999, in trace_module
    module._c._create_method_from_trace(method_name, func, example_inputs, var_lookup_fn, _force_outplace)
  File "torch/nn/modules/module.py", line 543, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "torch/nn/modules/module.py", line 529, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/tmp/1.py", line 6, in forward
    return torch.split(x, x.size(1))
  File "torch/functional.py", line 77, in split
    return tensor.split(split_size_or_sections, dim)
  File "torch/tensor.py", line 339, in split
    return super(Tensor, self).split_with_sizes(split_size, dim)
TypeError: split_with_sizes(): argument 'split_sizes' (position 1) must be tuple of ints, not Tensor
```
## Expected behavior

Trace successfully

## Additional context

I think this is related to sizes being handled specially in tracing mode.

cc @ezyang @gchanan @zou3519 @suo

**Comment by houseroad** [comment] 2019-10-08 21:05
cc: @spandantiwari @neginraoof I think this also affects ONNX exporter.

**Comment by cpuhrsch** [comment] 2019-10-10 17:19
I was able to reproduce this as well.

**Comment by spandantiwari** [comment] 2019-10-11 17:21
@cpuhrsch and @houseroad - we just put in a PR https://github.com/pytorch/pytorch/pull/27247 to update support for `unbind`. 

@bowenbao - is this issue resolved by that PR?

**Comment by BowenBao** [comment] 2019-10-11 18:49
> @cpuhrsch and @houseroad - we just put in a PR #27247 to update support for `unbind`.
> 
> @BowenBao - is this issue resolved by that PR?

unbind PR is unrelated. This is an issue with the tracer to handle traced Tensor inputs where int/int list is expected.

**Comment by secretsh** [comment] 2019-12-30 18:26
I have the same issue when using torch.onnx.export to export my model. The model can successfully run for prediction though.
Is there any update on this fix?
Thanks!

**Comment by joabim** [comment] 2020-01-15 19:01
Same as @secretsh - I'm experiencing this when using `torch.onnx.export` on 1.3.1.

**Comment by ptigwe** [comment] 2020-01-19 11:31
I also experienced this issue when using `torch.onnx.export` and currently using an imperfect workaround by converting the size of x to a Python integer (as I needed a quick way to resolve the issue).

```python
import torch

class MyModule(torch.nn.Module):
    def forward(self, x):
        x_size = int(x.size(1))
        return torch.split(x, x_size)


m = MyModule()
x = torch.randn(1, 2, 3, 4)

m(x)

print(torch.jit.trace(m, x))
```

This does, however, give the following warning

```
TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
```

**Closed** 2020-02-08 01:18 UTC
Labels: high priority, jit

**Comment by jiangxiluning** [comment] 2020-09-05 07:13
I have the same issue with 1.5.1 and 1.6.0 when I used torch.onnx.export. And I also found the element of torch.Size will be changed in the method of  torch._C._create_graph_by_tracing. You can refer to https://github.com/pytorch/pytorch/blob/3c31d73c875d9a4a6ea8a843b9a0d1b19fbe36f3/torch/jit/__init__.py#L357. 

Normally, the  list(tensor.size()) will return list of int, this function did changes to the structure, the list(tensor.size()) will be changed to list of tensors.

**Comment by 227BaronChen** [comment] 2020-09-19 05:15
I found a solution that seems to work. Using “int(x.size(1))” instead of “x.size(1)”

**Comment by catica** [comment] 2021-03-15 12:12
> I found a solution that seems to work. Using “int(x.size(1))” instead of “x.size(1)”

Can you elaborate on the solution? More specifically, where did you apply the change? I think I am having a similar problem in generating a onnx model from my RefineNet PyTorch implementation. I am trying to generate a netron graph, so I am trying to convert my PyTorch model into onnx `torch.onnx.export(model, inputs, onnx_path, verbose=True)`.

The strange thing is I don't get any error. It simply prints the output in red and breaks. I was thinking it could have been related to memory problems (since the exact same export function works well for my other Pytorch models). 

![image](https://user-images.githubusercontent.com/4283843/111151344-3cad4680-8587-11eb-8b83-be24c4e14a0e.png)
