### ISSUE TITLE
NotImplementedError: Could not run 'aten::_slow_conv2d_forward' with arguments from the 'MPS' backend

### ISSUE THREAD

**Issue by maheshwarkuchana** [pytorch/pytorch#77956] opened 2022-05-20 09:54 UTC
### 🐛 Describe the bug

Unable to run the deep learning models on the new PyTorch Nightly version using **MPS** backend.
<img width="800" alt="Screenshot 2022-05-20 at 10 50 21 am" src="https://user-images.githubusercontent.com/25655673/169502854-3e01439c-be15-4b09-abbf-bf1cb623dbc3.png">
 
Trying to check the architecture of this network with

<img width="800" alt="Screenshot 2022-05-20 at 10 51 04 am" src="https://user-images.githubusercontent.com/25655673/169502967-95881bf3-cd57-4780-acc1-dafa59cc1962.png">

Got this error.

<img width="1157" alt="Screenshot 2022-05-20 at 10 51 27 am" src="https://user-images.githubusercontent.com/25655673/169503073-e6f4479b-fa64-4eaf-8849-4d39d6766d46.png">

**Running on new M1 Pro MacBook Pro**

**Specs**

Mac OS version: 12.4
PyTorch version: 1.12.0.dev20220519
Python version: 3.9.12
Miniconda Environment: True

### Versions

wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

**Comment by pannous** [comment] 2022-05-20 10:05
duplicate of https://github.com/pytorch/pytorch/issues/77931

**Comment by albanD** [comment] 2022-05-20 14:04
Thanks for reporting this.
This has been added to the tracking issue.
I'll close this issue as this is a duplicate of https://github.com/pytorch/pytorch/issues/77931 and you can follow that other issue to know when this will be added!

**Closed by albanD** 2022-05-20 14:04 UTC
