### ISSUE TITLE
Jit traces interpolate scale_factor as constant

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#36596] opened 2020-04-14 18:49 UTC
## To Reproduce

1. Check the inlined IR graph for the following model

```
@torch.jit.script
def f2(self_min_size, self_max_size):
    # type: (int, int) -> Tensor
    scale_factor = 2.5
    if self_min_size * scale_factor > self_max_size:
        scale_factor = self_max_size / self_min_size

    return torch.tensor(scale_factor)


class MyModel(torch.nn.Module):
  def forward(self, x):
    scale_factor = f2(10, 15)
    y = torch.nn.functional.interpolate(
        x, scale_factor=float(scale_factor), mode='bilinear', align_corners=False)[0]

    return y
```

The graph is:
```
graph(%input : Float(1, 3, 30, 40)):
  %3 : int = prim::Constant[value=10]() # test_onnx.py:25:0
  %4 : int = prim::Constant[value=15]() # test_onnx.py:25:0
  %5 : Function = prim::Constant[name="f2"]()
  %scale_factor.1 : float = prim::Constant[value=2.5]() # test_onnx.py:16:19
  %64 : None = prim::Constant()
  %65 : bool = prim::Constant[value=0]()
  %66 : float = aten::mul(%3, %scale_factor.1) # test_onnx.py:17:7
  %67 : bool = aten::gt(%66, %4) # test_onnx.py:17:7
  %scale_factor : float = prim::If(%67) # test_onnx.py:17:4
    block0():
      %scale_factor.3 : float = aten::div(%4, %3) # test_onnx.py:18:23
      -> (%scale_factor.3)
    block1():
      -> (%scale_factor.1)
  %70 : Tensor = aten::tensor(%scale_factor, %64, %64, %65) # test_onnx.py:20:11
  %7 : int = prim::Constant[value=2]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %8 : int = aten::size(%input, %7) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %9 : Long() = prim::NumToTensor(%8)
  %10 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %11 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %12 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %13 : None = prim::Constant()
  %14 : Float() = aten::to(%9, %10, %11, %12, %13) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %15 : Float() = **prim::Constant[value={1.5}]()** # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %16 : Device = prim::Constant[value="cpu"]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %17 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %18 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %19 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %20 : None = prim::Constant()
  %21 : Float() = aten::to(%15, %16, %17, %18, %19, %20) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %22 : Float() = aten::detach(%21) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %23 : Float() = aten::mul(%14, %22) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %24 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %25 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %26 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %27 : None = prim::Constant()
  %28 : Float() = aten::to(%23, %24, %25, %26, %27) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %29 : Float() = aten::floor(%28) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %53 : int = aten::Int(%29)
  %30 : int = prim::Constant[value=3]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %31 : int = aten::size(%input, %30) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %32 : Long() = prim::NumToTensor(%31)
  %33 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %34 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %35 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %36 : None = prim::Constant()
  %37 : Float() = aten::to(%32, %33, %34, %35, %36) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %38 : Float() = prim::Constant[value={1.5}]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %39 : Device = prim::Constant[value="cpu"]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %40 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %41 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %42 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %43 : None = prim::Constant()
  %44 : Float() = aten::to(%38, %39, %40, %41, %42, %43) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %45 : Float() = aten::detach(%44) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %46 : Float() = aten::mul(%37, %45) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %47 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %48 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %49 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %50 : None = prim::Constant()
  %51 : Float() = aten::to(%46, %47, %48, %49, %50) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %52 : Float() = aten::floor(%51) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %54 : int = aten::Int(%52)
  %55 : int[] = prim::ListConstruct(%53, %54)
  %56 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3051:0
  %57 : None = prim::Constant()
  %58 : None = prim::Constant()
  %59 : Float(1, 3, 45, 60) = aten::upsample_bilinear2d(%input, %55, %56, %57, %58) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3051:0
  %60 : int = prim::Constant[value=0]() # test_onnx.py:27:0
  %61 : int = prim::Constant[value=0]() # test_onnx.py:27:0
  %62 : Float(3, 45, 60) = aten::select(%59, %60, %61) # test_onnx.py:27:0
  return (%62)
```

## Expected behavior

The scale_factor is not traced dynamically in this graph. Node %15 contains the scale_factor as a fixed constant.
However, if I remove float() cast for the scale_factor in the model:
```
class MyModel(torch.nn.Module):
  def forward(self, x):
    scale_factor = f2(10, 15)
    y = torch.nn.functional.interpolate(
        x, scale_factor=scale_factor, mode='bilinear', align_corners=False)[0]

    return y
```
Then the scale_factor is not constant anymore, as in the node %17 below. The graph would be 

```
graph(%input : Float(1, 3, 30, 40)):
  %3 : int = prim::Constant[value=10]() # test_onnx.py:25:0
  %4 : int = prim::Constant[value=15]() # test_onnx.py:25:0
  %5 : Function = prim::Constant[name="f2"]()
  %scale_factor.1 : float = prim::Constant[value=2.5]() # test_onnx.py:16:19
  %66 : None = prim::Constant()
  %67 : bool = prim::Constant[value=0]()
  %68 : float = aten::mul(%3, %scale_factor.1) # test_onnx.py:17:7
  %69 : bool = aten::gt(%68, %4) # test_onnx.py:17:7
  %scale_factor : float = prim::If(%69) # test_onnx.py:17:4
    block0():
      %scale_factor.3 : float = aten::div(%4, %3) # test_onnx.py:18:23
      -> (%scale_factor.3)
    block1():
      -> (%scale_factor.1)
  %scale : Tensor = aten::tensor(%scale_factor, %66, %66, %67) # test_onnx.py:20:11
  %9 : int = prim::Constant[value=2]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %10 : int = aten::size(%input, %9) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %11 : Long() = prim::NumToTensor(%10)
  %12 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %13 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %14 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %15 : None = prim::Constant()
  %16 : Float() = aten::to(%11, %12, %13, %14, %15) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  **%17 : Double() = aten::detach(%scale)** # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %18 : Device = prim::Constant[value="cpu"]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %19 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %20 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %21 : bool = prim::Constant[value=1]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %22 : None = prim::Constant()
  %23 : Float() = aten::to(%17, %18, %19, %20, %21, %22) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %24 : Float() = aten::detach(%23) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %25 : Float() = aten::mul(%16, %24) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %26 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %27 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %28 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %29 : None = prim::Constant()
  %30 : Float() = aten::to(%25, %26, %27, %28, %29) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %31 : Float() = aten::floor(%30) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %55 : int = aten::Int(%31)
  %32 : int = prim::Constant[value=3]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %33 : int = aten::size(%input, %32) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %34 : Long() = prim::NumToTensor(%33)
  %35 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %36 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %37 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %38 : None = prim::Constant()
  %39 : Float() = aten::to(%34, %35, %36, %37, %38) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %40 : Double() = aten::detach(%scale) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %41 : Device = prim::Constant[value="cpu"]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %42 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %43 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %44 : bool = prim::Constant[value=1]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %45 : None = prim::Constant()
  %46 : Float() = aten::to(%40, %41, %42, %43, %44, %45) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %47 : Float() = aten::detach(%46) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %48 : Float() = aten::mul(%39, %47) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %49 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %50 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %51 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %52 : None = prim::Constant()
  %53 : Float() = aten::to(%48, %49, %50, %51, %52) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %54 : Float() = aten::floor(%53) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:2902:0
  %56 : int = aten::Int(%54)
  %57 : int[] = prim::ListConstruct(%55, %56)
  %58 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3051:0
  %59 : None = prim::Constant()
  %60 : None = prim::Constant()
  %61 : Float(1, 3, 45, 60) = aten::upsample_bilinear2d(%input, %57, %58, %59, %60) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3051:0
  %62 : int = prim::Constant[value=0]() # test_onnx.py:27:0
  %63 : int = prim::Constant[value=0]() # test_onnx.py:27:0
  %64 : Float(3, 45, 60) = aten::select(%61, %62, %63) # test_onnx.py:27:0
  return (%64)
```

cc @suo

**Comment by eellison** [comment] 2020-04-14 19:04
I believe this is expected behavior. If you call `float()` on a Tensor it becomes a scalar, which can no longer be tracked. Also, the `float` call is in user-code, so there's no actionable change within pytorch.

**Comment by neginraoof** [comment] 2020-04-14 19:21
@eellison So the problem is that when scripting model with interpolate without float() call, it throws this exception:
 Expected a value of type 'Optional[List[float]]' for argument 'scale_factor' but instead found type 'Tensor'.      
interpolate(Tensor input, int[]? size=None, float[]? scale_factor=None, str mode="nearest", bool? align_corners=None, bool? recompute_scale_factor=None) -> (Tensor)


Does this mean that we cannot track scale_factor dynamically for interpolate at all?

**Comment by neginraoof** [comment] 2020-04-14 19:25
@eellison For the reference, I'm trying to export interpolate dynamically for torchvision models in this PR:
https://github.com/pytorch/vision/pull/2087
And I'm seeing the above exception on CI.

**Comment by eellison** [comment] 2020-04-14 19:50
I'm not really sure what the solution is there. Closing since this isn't a pytorch issue.

**Comment by neginraoof** [comment] 2020-04-14 19:54
But I'm not clean on the solution. Why is the behavior with float() is that to output a scalar?

**Comment by eellison** [comment] 2020-04-14 20:00
`float()` casts a tensor to a python float value. once it is no longer a tensor it can't be traced, so it has to be inserted as a constant. 

```
def foo(x):
    return torch.tensor(float(x))
print(torch.jit.trace(foo, (torch.tensor(3.),)).graph)

graph(%0 : Double()):
  %1 : Double() = prim::Constant[value={3}]() # test/test_jit.py:7842:0
  %2 : Device = prim::Constant[value="cpu"]() # test/test_jit.py:7842:0
  %3 : int = prim::Constant[value=7]() # test/test_jit.py:7842:0
  %4 : bool = prim::Constant[value=0]() # test/test_jit.py:7842:0
  %5 : bool = prim::Constant[value=0]() # test/test_jit.py:7842:0
  %6 : None = prim::Constant()
  %7 : Double() = aten::to(%1, %2, %3, %4, %5, %6) # test/test_jit.py:7842:0
  %8 : Double() = aten::detach(%7) # test/test_jit.py:7842:0
  return (%8)
```

**Comment by neginraoof** [comment] 2020-07-23 23:03
We're seeing this behavior even without the float cast. An example model would be:
```
        class MyModel(torch.nn.Module):

            def forward(self, x, y):
                return torch.nn.functional.interpolate(x, mode='bilinear', scale_factor=y.shape[0])

        x = torch.randn(1, 2, 4, 6)
        y = torch.randn(1, 2, 4, 6)
```
The jit trace graph here still contains constant nodes for upsample_bilinear2d:

```
graph(%input : Float(1:48, 2:24, 4:6, 6:1, requires_grad=0, device=cpu),
      %1 : Float(1:48, 2:24, 4:6, 6:1, requires_grad=0, device=cpu)):
  %6 : int = prim::Constant[value=0]() # test/onnx/test_pytorch_onnx_onnxruntime.py:1383:0
  %7 : int = aten::size(%1, %6) # test/onnx/test_pytorch_onnx_onnxruntime.py:1383:0
  %scale : Long(device=cpu) = prim::NumToTensor(%7)
  %22 : int = prim::Constant[value=2]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %23 : int = aten::size(%input, %22) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %24 : Long(device=cpu) = prim::NumToTensor(%23)
  %25 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %26 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %27 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %28 : None = prim::Constant()
  %29 : Float(requires_grad=0, device=cpu) = aten::to(%24, %25, %26, %27, %28) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %30 : Long(requires_grad=0, device=cpu) = aten::detach(%scale) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %31 : Device = prim::Constant[value="cpu"]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %32 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %33 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %34 : bool = prim::Constant[value=1]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %35 : None = prim::Constant()
  %36 : Float(requires_grad=0, device=cpu) = aten::to(%30, %31, %32, %33, %34, %35) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %37 : Float(requires_grad=0, device=cpu) = aten::detach(%36) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %38 : Float(requires_grad=0, device=cpu) = aten::mul(%29, %37) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %39 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %40 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %41 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %42 : None = prim::Constant()
  %43 : Float(requires_grad=0, device=cpu) = aten::to(%38, %39, %40, %41, %42) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %44 : Float(requires_grad=0, device=cpu) = aten::floor(%43) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %68 : int = aten::Int(%44)
  %45 : int = prim::Constant[value=3]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %46 : int = aten::size(%input, %45) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %47 : Long(device=cpu) = prim::NumToTensor(%46)
  %48 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %49 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %50 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %51 : None = prim::Constant()
  %52 : Float(requires_grad=0, device=cpu) = aten::to(%47, %48, %49, %50, %51) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %53 : Long(requires_grad=0, device=cpu) = aten::detach(%scale) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %54 : Device = prim::Constant[value="cpu"]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %55 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %56 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %57 : bool = prim::Constant[value=1]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %58 : None = prim::Constant()
  %59 : Float(requires_grad=0, device=cpu) = aten::to(%53, %54, %55, %56, %57, %58) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %60 : Float(requires_grad=0, device=cpu) = aten::detach(%59) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %61 : Float(requires_grad=0, device=cpu) = aten::mul(%52, %60) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %62 : int = prim::Constant[value=6]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %63 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %64 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %65 : None = prim::Constant()
  %66 : Float(requires_grad=0, device=cpu) = aten::to(%61, %62, %63, %64, %65) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %67 : Float(requires_grad=0, device=cpu) = aten::floor(%66) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3142:0
  %69 : int = aten::Int(%67)
  %70 : int[] = prim::ListConstruct(%68, %69)
  %71 : bool = prim::Constant[value=0]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3163:0
  %72 : float = prim::Constant[value=1.]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3163:0
  %73 : float = prim::Constant[value=1.]() # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3163:0
  %74 : Float(1:48, 2:24, 4:6, 6:1, requires_grad=0, device=cpu) = aten::upsample_bilinear2d(%input, %70, %71, %72, %73) # /opt/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/nn/functional.py:3163:0
  return (%74)
```

**Closed** 2021-02-18 23:31 UTC
Labels: oncall: jit, triaged

**Comment by AyanamiReiFan** [comment] 2024-05-19 12:37
This problem has not yet been solved. Currently, interpolate can only track the specified dynamic size, but does not support the dynamic sacle_factor. This is very strange...
