### ISSUE TITLE
A Strange type properties in pytorch math function

### ISSUE THREAD

**Issue by MARD1NO** [pytorch/pytorch#65685] opened 2021-09-27 09:46 UTC
## 🐛 Bug

Hi, I found a strange type properties in math function like torch.add, torch.mul etc. 

```python
x_tensor = torch.ones((3, ), dtype=torch.int8)
y_tensor = torch.tensor(1, dtype=torch.float64)
out = torch.mul(x_tensor, y_tensor) # torch.float64
```

```python
x_tensor = torch.ones((3, ), dtype=torch.int8)
y_tensor = torch.tensor(1, dtype=torch.int64)
out = torch.mul(x_tensor, y_tensor) # torch.int8
```

```python
x_tensor = torch.ones((3, 3), dtype=torch.int8)
y_tensor = torch.ones((3, 3), dtype=torch.int64)
out = torch.mul(x_tensor, y_tensor) # torch.int64
```

```python
x_tensor = torch.ones((3, 3), dtype=torch.int8)
out = torch.mul(x_tensor, 9223372036854775807) # torch.int8
```
## Expected behavior
I think in each case the output tensor should be cast the higher priority dtype. 

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): mac os
 - How you installed PyTorch (`conda`, `pip`, source): pip install 
 - Python version: 3.9.0

cc @nairbv @mruberry

**Comment by gchanan** [comment] 2021-09-27 18:36
This is intended behavior -- changing the dtype based on the runtime value is pretty fraught, e.g. in general it involves a sync point on CUDA.

**Comment by MARD1NO** [comment] 2021-09-28 00:01
> This is intended behavior -- changing the dtype based on the runtime value is pretty fraught, e.g. in general it involves a sync point on CUDA.

The above code shows different behavior of type promotion with different input types.

For case 1, a int8 tensor multiplies a float64 tensor, the output dtype is float64 and I think is right. 

In case2, a int 8 tensor multiplies a scalar int64 tensor, the output dtype is still int8, and it may cause overflow problem. 

Case3 is consistent with case1, it also promotes a right datatype. 

In case4, a int8 tensor multiply a scalar, which is the max value of int64(9223372036854775807 equals to 2^63-1), but its output dtype is int8, it may cause overflow problem too. 

In my opinion, all the dtype should promise the right dtype promotion.

**Comment by mruberry** [comment] 2021-09-29 05:35
Thanks for filing this issue @MARD1NO. The first three cases described here are a symptom of https://github.com/pytorch/pytorch/issues/58736 and I think this issue can be closed as a duplicate of that. For the fourth case @gchanan's answer is correct that PyTorch does not inspect the value of a number to determine an appropriate dtype for it. This is divergent from NumPy but consistent with the newer Python Array API specification and we intentionally do not support this behavior.

**Closed by mruberry** 2021-09-29 05:35 UTC
Labels: triaged, module: type promotion

**Comment by MARD1NO** [comment] 2021-09-29 06:10
> This is divergent from NumPy but consistent with the newer Python Array API specification and we intentionally do not support this behavior.

thanks for your reply!
