### ISSUE TITLE
`torch.fft.ifft` has different jacobians computed by reverse and forward mode

### ISSUE THREAD

**Issue by cafffeeee** [pytorch/pytorch#93028] opened 2023-01-25 23:52 UTC
### 🐛 Describe the bug

`torch.fft.ifft` has different jacobians computed by reverse and forward mode

```py
import torch
from torch.autograd.functional import jacobian
x = torch.zeros(3,3, dtype=torch.complex128)

def func(x):
    x = torch.fft.ifft(x)
    return x

jac_rev = jacobian(func, (x.clone().requires_grad_(), ), strategy='reverse-mode', vectorize=True)[0][0]
jac_fwd = jacobian(func, (x.clone().requires_grad_(), ), strategy='forward-mode', vectorize=True)[0][0]
print(torch.isclose(jac_rev, jac_fwd, atol=1e-4, rtol=1e-4))
```

```
tensor([[[ True,  True,  True],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True, False, False],
         [ True,  True,  True],
         [ True,  True,  True]],

        [[ True, False, False],
         [ True,  True,  True],
         [ True,  True,  True]]])
```

It turns out that reverse mode returns ` -0.1667+0.2887j` but forward mode returns ` -0.1667-0.2887j`. They have different signs for the imag

### Versions

```
PyTorch version: 2.0.0.dev20230105
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0.dev20230105
[pip3] torchaudio==2.0.0.dev20230105
[pip3] torchvision==0.15.0.dev20230105
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.5           py39h14f4228_0
[conda] numpy-base                1.23.5           py39h31eccc5_0
[conda] pytorch                   2.0.0.dev20230105 py3.9_cuda11.7_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.7                 h67b0de4_2    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230105      py39_cu117    pytorch-nightly
[conda] torchtriton               2.0.0+0d7e753227            py39    pytorch-nightly
[conda] torchvision               0.15.0.dev20230105      py39_cu117    pytorch-nightly
```

**Comment by cafffeeee** [comment] 2023-01-25 23:57
It seems that `x * 1j` will have different jacobians for reverse and forward mode when `x=1`

```py
a = torch.tensor([1], dtype=torch.complex64)

def func(a):
    b = a * 1j
    return b

jac_rev = jacobian(func, (a.clone().requires_grad_(), ), strategy='reverse-mode', vectorize=True)[0][0]
jac_fwd = jacobian(func, (a.clone().requires_grad_(), ), strategy='forward-mode', vectorize=True)[0][0]
print(torch.isclose(jac_rev, jac_fwd, atol=1e-4, rtol=1e-4))

print(jac_rev)
print(jac_fwd)
```

```
tensor([False])
tensor([0.-1.j])
tensor([0.+1.j], grad_fn=<SelectBackward0>)
```

**Comment by kshitij12345** [comment] 2023-01-26 05:07
Duplicate of https://github.com/pytorch/pytorch/issues/92140.

**Closed by kshitij12345** 2023-01-26 05:07 UTC
