### ISSUE TITLE
torch.sign(bfloat16) on CPU is wrong on largish tensors

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#41238] opened 2020-07-10 10:39 UTC
```
t = torch.tensor([-6.5625e-01, -1.5000e+00, -2.0898e-01, -1.8750e-01, -1.7188e+00,
         1.9375e+00, -2.5000e-01,  1.2695e-01,  3.7500e-01, -1.5547e+00,
        -1.8281e+00,  1.0859e+00,  3.1445e-01,  7.1875e-01, -1.0469e+00,
         1.2734e+00, -1.1816e-01, -3.6523e-01, -1.6641e+00,  9.9945e-04,
         1.5078e+00, -4.2188e-01,  1.1797e+00,  1.2188e+00,  1.1572e-01,
         1.9219e+00, -1.8516e+00,  1.0312e+00, -1.0781e+00, -1.3438e+00,
         1.4531e+00, -1.4219e+00, -9.8438e-01, -1.6172e+00, -1.5781e+00,
         1.5430e-01, -7.5000e-01,  1.8984e+00,  4.3750e-01, -2.7148e-01,
         1.3828e+00, -1.9062e+00,  5.3906e-01,  5.2734e-01, -1.5391e+00,
         1.9141e+00, -1.2188e+00,  1.8828e+00,  9.3750e-01,  4.9770e-06,
         1.4141e+00,  1.1953e+00, -7.8516e-01,  1.9531e+00,  3.7500e-01,
        -1.0547e+00,  9.6484e-01, -1.8359e+00,  1.9766e+00,  4.4727e-01,
        -7.1094e-01,  5.7812e-01, -4.0625e-01, -5.3906e-01, -1.6113e-01,
        -3.7109e-01, -1.2891e-01, -7.9590e-02,  6.8359e-01, -9.6191e-02,
        -1.6328e+00, -1.6172e+00,  1.6562e+00, -2.2363e-01, -4.1016e-01,
         3.1406e+00, -6.4453e-01, -1.0000e+00, -3.1406e+00,  1.8125e+00,
         1.1328e+00,  2.5000e-01, -6.1719e-01, -1.9688e+00, -1.1250e+00,
        -8.5156e-01, -1.9336e-01,  1.5625e+00, -4.0234e-01, -7.2266e-01,
        -1.6016e+00,  1.7891e+00, -9.9945e-04, -1.5859e+00, -5.6641e-01,
        -1.2734e+00,  1.4922e+00, -1.9922e+00, -1.9766e+00, -1.4258e-01,
         1.0000e+00,  5.7812e-01, -4.8340e-02, -8.2422e-01,  8.9844e-01,
         1.5312e+00, -8.6719e-01,  1.1562e+00,  5.1953e-01, -6.0547e-01,
         1.8203e+00, -1.3984e+00,  1.2578e+00,  7.5000e-01, -1.2109e+00,
         1.8945e-01,  9.9609e-01,  1.9766e+00,  1.8203e+00,  2.6172e-01,
        -1.6953e+00, -8.2422e-01, -1.2266e+00, -8.5156e-01,  1.2656e+00,
         6.0938e-01,  6.8750e-01,  0.0000e+00,  1.0078e+00,  4.5312e-01,
        -2.3145e-01, -6.3281e-01], dtype=torch.bfloat16)
print(torch.sign(t))
```

Prints:
```
tensor([-1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38, -1.1755e-38,
        -1.1755e-38,  1.1755e-38,  1.1755e-38,  1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,  1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38,  1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38,  1.1755e-38,
         1.1755e-38,  1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38,
        -1.1755e-38,  1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38,
        -1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,
        -1.1755e-38, -1.1755e-38, -1.1755e-38,  1.1755e-38, -1.1755e-38,
        -1.1755e-38, -1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,  1.1755e-38,
         1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,
        -1.1755e-38, -1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38,
        -1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,
        -1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,
         1.1755e-38,  1.1755e-38, -1.1755e-38, -1.1755e-38,  1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38, -1.1755e-38,
         1.1755e-38, -1.1755e-38,  1.1755e-38,  1.1755e-38, -1.1755e-38,
         1.1755e-38,  1.1755e-38,  1.1755e-38,  1.1755e-38,  1.1755e-38,
        -1.1755e-38, -1.1755e-38, -1.1755e-38, -1.1755e-38,  1.1755e-38,
         1.1755e-38,  1.1755e-38,  0.0000e+00,  1.0000e+00,  1.0000e+00,
        -1.0000e+00, -1.0000e+00], dtype=torch.bfloat16)
```

Which is obviously incorrect. 

cc @VitalyFedyunin

**Comment by malfet** [comment] 2020-07-10 15:26
Sounds like a fun little problem. Self assigning to myself.

**Comment by malfet** [comment] 2020-07-13 14:36
crux of the issue is that `Vec256<float>:operator<` returns vector of 0 and -nans, but `Vec256<BFloat>:operator<` returns vector of 0 and nans.

**Closed** 2020-12-14 16:54 UTC
Labels: module: NaNs and Infs, module: bfloat16, module: cpu, triaged
