### ISSUE TITLE
saved tensor hooks silently incorrect with torch.compile

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#116221] opened 2023-12-20 23:15 UTC
I would have expected us to graph break on it.
```py
import torch

def pack_hook(x):
    return x
def unpack_hook(x):
    return 2 * x

@torch.compile(backend="aot_eager", fullgraph=True)
def f(a, b):
    return a * b

a = torch.ones([], requires_grad=True)
b = torch.tensor(2., requires_grad=True)
with torch.autograd.graph.saved_tensors_hooks(pack_hook, unpack_hook):
    y = f(a, b)

y.backward()
print(a.grad, b.grad)
```
gives different results with/without the torch.compile.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by bdhirsh** [comment] 2023-12-21 00:06
I have a PR here to no-op saved_tensor_hook during tracing, so they can (only) be executed during runtime: https://github.com/pytorch/pytorch/pull/113417

It's stuck in CI-hell though (I haven't had a chance to debug the errors). I'm going to try to come back to it soon but if anyone else wants to grab it, feel free.

**Comment by bdhirsh** [comment] 2023-12-21 00:07
This issue might be a dupe of https://github.com/pytorch/pytorch/issues/113263 ?

**Comment by zou3519** [comment] 2023-12-21 00:34
closing as dupe

**Comment by yf225** [comment] 2023-12-21 21:33
As discussed, closing as dupe.

**Closed by yf225** 2023-12-21 21:33 UTC
Labels: oncall: pt2
