### ISSUE TITLE
RuntimeError - onnx export a model with transformer layer

### ISSUE THREAD

**Issue by lawpdas** [pytorch/pytorch#61277] opened 2021-07-06 07:53 UTC
## 🐛 Bug

My model can be exported under pytorch1.8.1, but there is a runtime error under pytorch1.9.0.
I have located the error at a MultiheadAttention layer.
I don't know how to solve it.

```python
Traceback (most recent call last):
  File "/data2/Documents/Experiments/BaseT/models/baseline/model2trt.py", line 218, in <module>
    torch.onnx.export(
  File "/home/space/Public/anaconda3/envs/py38torch19/lib/python3.8/site-packages/torch/onnx/__init__.py", line 275, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/home/space/Public/anaconda3/envs/py38torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 88, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/home/space/Public/anaconda3/envs/py38torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 689, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/home/space/Public/anaconda3/envs/py38torch19/lib/python3.8/site-packages/torch/onnx/utils.py", line 501, in _model_to_graph
    params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
RuntimeError: expected scalar type Long but found Float
```

## Environment
```shell
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-6ubuntu2) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 460.80
cuDNN version: Probably one of the following:
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.1.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.2.1
/usr/local/cuda-11.2/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.74              h6bb024c_0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.19.5                    <pip>
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0  
[conda] pytorch                   1.9.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.9.0                      py38    pytorch
[conda] torchvision               0.10.0               py38_cu111    pytorch

```

 - PyTorch Version (e.g., 1.0): 1.9.0  py3.8_cuda11.1_cudnn8.0.5_0
 - OS (e.g., Linux): ubuntu2020
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8
 - CUDA/cuDNN version: 11.1.74/
 - GPU models and configuration: 2080ti
 - Any other relevant information:

**Comment by floboc** [comment] 2021-08-18 16:29
Hello, I am encountering the same issue with PyTorch 1.9.0.
Here is a code sample to reproduce this issue:

```
import torch


class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mha = torch.nn.MultiheadAttention(embed_dim=1024, num_heads=8, batch_first=True)

    def forward(self, x, y):
        return self.mha(query=x, key=y, value=y)


net = TestModule()
x = torch.randn((1, 5, 1024))
y = torch.randn((1, 11, 1024))
torch.onnx.export(net, (x, y), "model.onnx", opset_version=11, verbose=True)
```

**Comment by hwangdeyu** [comment] 2021-08-19 09:44
@floboc  @lawpdas  This issue is fixed in PyTorch 1.10. You can try to use PyTorch nightly versions 1.10.

**Comment by lawpdas** [comment] 2021-09-01 09:11
@hwangdeyu Many thanks! The issue has been solved. I have exported my model with PyTorch1.10.

**Comment by lawpdas** [comment] 2021-09-02 10:00
Hi @hwangdeyu
I export my model to ONNX, then I parse it to be a TensorRT engine. I find that the engine can output correct results if I use PyTorch1.8 to export, but it outputs wrong results under PyTorch1.10 with the same code.
Are there some differences between PyTorch1.10 and PyTorch1.8?
Could you help me?

**Comment by hwangdeyu** [comment] 2021-09-07 10:04
> Hi @hwangdeyu Deyu Huang FTE
> I export my model to ONNX, then I parse it to be a TensorRT engine. I find that the engine can output correct results if I use PyTorch1.8 to export, but it outputs wrong results under PyTorch1.10 with the same code.
> Are there some differences between PyTorch1.10 and PyTorch1.8?
> Could you help me?

I am not very sure which part causes this issue. Could you tell me which model you used met this problem? Then I can try to repro it.

**Comment by lawpdas** [comment] 2021-09-08 02:50
Thanks for your reply!
I create a [repo](https://github.com/lawpdas/onnx_61277) for this issue. The script `lib/model/model_multimodal_trt_Dynamic.py` is used for reproduction. I also provide my ONNX files, you can find them in README.
Besides, I noticed that the ONNX exported by pytorch18 also works well under pytorch110.

**Comment by xuezu29** [comment] 2021-09-14 13:58
@lawpdas Have you solved this problem yet?   I've met the same question.

**Comment by lawpdas** [comment] 2021-09-14 14:00
Which problem?

**Comment by xuezu29** [comment] 2021-09-14 14:10
> Hi @hwangdeyu
> I export my model to ONNX, then I parse it to be a TensorRT engine. I find that the engine can output correct results if I use PyTorch1.8 to export, but it outputs wrong results under PyTorch1.10 with the same code.
> Are there some differences between PyTorch1.10 and PyTorch1.8?
> Could you help me?

when I export transformer layer to onnx report error:  'RuntimeError: expected scalar type Long but found Float. ' 
bug I haven't upgraded to the latest version after seeing your problem that will get wrong results by TensorRT.

**Comment by lawpdas** [comment] 2021-09-14 14:50
@xuezu29 Using PyTorch1.10 can solve the problem of export. But I have not solved the problem of the wrong result.
Please let me know if you get the correct result with PyTorch1.10.

**Comment by hwangdeyu** [comment] 2021-09-17 11:59
> Thanks for your reply!
> I create a [repo](https://github.com/lawpdas/onnx_61277) for this issue. The script `lib/model/model_multimodal_trt_Dynamic.py` is used for reproduction. I also provide my ONNX files, you can find them in README.
> Besides, I noticed that the ONNX exported by pytorch18 also works well under pytorch110.

It looks like the two ONNX graph between 1.08 and 1.10 has little difference. Such as it has `Cast` op  in front of `CumSum_387` operator in 1.08, but 'CumSum_379' operator without it.
I'm trying setting the code environment and reproduce it to find the root cause.

**Comment by hwangdeyu** [comment] 2021-09-18 09:37
Hi @xuezu29, 
I have reproduced [your repo](https://github.com/lawpdas/onnx_61277), do you meet this error right?
>[TensorRT] ERROR: [graphShapeAnalyzer.cpp::throwIfError::1306] Error Code 9: Internal Error (Reshape_624: reshape changes volume
)
In node 624 (parseGraph): INVALID_NODE: Invalid Node - Reshape_624
[graphShapeAnalyzer.cpp::throwIfError::1306] Error Code 9: Internal Error (Reshape_624: reshape changes volume
)

**Comment by lawpdas** [comment] 2021-09-18 09:45
@hwangdeyu Sorry, I have never seen the error.

**Closed** 2022-10-24 18:44 UTC
Labels: module: onnx, triaged, module: regression

**Comment by Zalways** [comment] 2023-08-18 06:47
> @hwangdeyu Many thanks! The issue has been solved. I have exported my model with PyTorch1.10.

hi imet this problem,too
**when i use pytorch1.9(cuda 11.1),it got error:**
params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
RuntimeError: expected scalar type Long but found Float

**but when i change pytorch1.9(cuda 11.1) to pytorch 1.10(cuda 11.3),i got another error:**
Traceback (most recent call last):
  File "deploy/export_model00.py", line 227, in <module>
    exported_model = export_tracing(torch_model, sample_inputs)
  File "deploy/export_model00.py", line 132, in export_tracing
    torch.onnx.export(traceable_model, image, f, input_names=['input'], output_names=['output'], opset_version=11,dynamic_axes={'input':[1,2],'output':[1,2]})
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/__init__.py", line 316, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 107, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 724, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 493, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 437, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/onnx/utils.py", line 388, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, strict=False, _force_outplace=False, _return_inputs_states=True)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/jit/_trace.py", line 1166, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/envs/deepsolo/lib/python3.8/site-packages/torch/jit/_trace.py", line 127, in forward
    graph, out = torch._C._create_graph_by_tracing(
RuntimeError: 0INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/alias_analysis.cpp":584, please report a bug to PyTorch. We don't have an op for aten::fill_ but it isn't a special case.  Argument types: Tensor, bool, 

do you met problem like this? how do you change pytorch? i pip install pytorch 1.10 directly @lawpdas @hwangdeyu
