### ISSUE TITLE
F.pad input pad_size=[0,0] will cause custom backward function throw RuntimeError: leaf variable has been moved into the graph interior

### ISSUE THREAD

**Issue by One-sixth** [pytorch/pytorch#31748] opened 2019-12-31 09:11 UTC
## 🐛 Bug

F.pad may be have a bug when pad_size=[0, 0, 0, 0, 0, 0]. It will cause my custom bp function to fail.

## To Reproduce

1.  Run the code will throw RuntimeError: leaf variable has been moved into the graph interior
2.  Comment line 62 and uncomment lines 63, 64, 65, 66
3.  Run the code will be success.

## Environment

 - PyTorch Version (e.g., 1.0): pytorch 1.3.1
 - OS (e.g., Linux): windows10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration: gtx1070
 - Any other relevant information:

## Additional context

```
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.checkpoint import check_backward_validity


class RevSequentialBackwardFunction(torch.autograd.Function):

    @staticmethod
    def forward(ctx, rev_block_stack, *inputs):
        check_backward_validity(inputs)

        assert hasattr(rev_block_stack, 'mod_list') and isinstance(rev_block_stack.mod_list, nn.ModuleList)
        assert hasattr(rev_block_stack, 'invert') and callable(rev_block_stack.invert)

        ctx.rev_block_stack = rev_block_stack

        with torch.no_grad():
            outputs = rev_block_stack(*inputs)

        ctx.save_for_backward(*outputs)
        return outputs

    @staticmethod
    def backward(ctx, *grad_output):
        bak_outputs = ctx.saved_tensors
        with torch.no_grad():
            for m in ctx.rev_block_stack.mod_list[::-1]:
                inputs = m.invert(*bak_outputs)
                inputs = [t.detach() for t in inputs]
                print(len(inputs))
                for inp in inputs:
                    inp.requires_grad = True

                with torch.enable_grad():
                    outputs = m.forward(*inputs)
                if isinstance(outputs, torch.Tensor):
                    outputs = (outputs,)

                torch.autograd.backward(outputs, grad_output)
                grad_output = tuple(inp.grad if isinstance(inp, torch.Tensor) else inp
                                    for inp in inputs)
                bak_outputs = inputs

        return (None,) + grad_output


def rev_sequential_backward_wrapper(m, *args):
    return RevSequentialBackwardFunction.apply(m, *args)


class RevChannelPad2D(nn.Module):
    def __init__(self, pad_size, mode='constant', value=0):
        super().__init__()
        assert pad_size >= 0
        self.pad_size = pad_size
        self.mode = mode
        self.value = value

    def forward(self, x):
        # Bug here
        y = F.pad(x, pad=[0, 0, 0, 0, 0, self.pad_size], mode=self.mode, value=self.value)
        # if self.pad_size != 0:
        #     y = F.pad(x, pad=[0, 0, 0, 0, 0, self.pad_size], mode=self.mode, value=self.value)
        # else:
        #     y = x
        return y

    def invert(self, x):
        return x[:, :x.shape[1] - self.pad_size, :, :]


class SimpleRevBlock2(nn.Module):
    def __init__(self, in_ch, out_ch):
        super().__init__()

        self.pad = RevChannelPad2D(out_ch - in_ch)

        self.func = nn.Sequential(
            nn.Conv2d(in_ch, in_ch, 1, 1, 0),
            nn.BatchNorm2d(in_ch),
            nn.Conv2d(in_ch, out_ch, 1, 1, 0),
            nn.BatchNorm2d(out_ch),
        )

    def forward(self, x1, x2):
        x2 = self.pad(x2)
        y = x1 + self.func(x2)
        return x2, y

    def invert(self, y1, y2):
        x2, y = y1, y2
        x1 = y - self.func(x2)
        x2 = self.pad.invert(x2)
        return x1, x2


class RevSequential(nn.Module):
    def __init__(self, modules=None):
        super().__init__()
        self.mod_list = nn.ModuleList(modules)

    def append(self, module):
        assert hasattr(module, 'invert') and callable(module.invert)
        self.mod_list.append(module)

    def extend(self, modules):
        for m in modules:
            self.append(m)

    def forward(self, x1, x2):
        y1, y2 = x1, x2
        for m in self.mod_list:
            y1, y2 = m(y1, y2)
        return y1, y2

    def invert(self, y1, y2):
        x1, x2 = y1, y2
        for m in self.mod_list[::-1]:
            x1, x2 = m.invert(x1, x2)
        return x1, x2

    def __len__(self):
        return len(self.mod_list)

    def __getitem__(self, item):
        return self.mod_list[item]


class Like_IRevNet(nn.Module):
    def __init__(self, use_rev_bw):
        super().__init__()
        self.use_rev_bw = use_rev_bw

        self.seq2 = RevSequential([
            SimpleRevBlock2(32, 32)
        ])

    def forward(self, x):
        x1, x2 = x, x
        y1, y2 = rev_sequential_backward_wrapper(self.seq2, x1, x2)
        y = y1 + y2
        return y


if __name__ == '__main__':
    net = Like_IRevNet(True)
    im = torch.rand(5, 32, 128, 128) + torch.zeros(1, requires_grad=True)
    out = net(im)
    out.sum().backward()

```

**Comment by ezyang** [comment] 2020-01-02 14:52
I'm going to close this as a dupe of https://github.com/pytorch/pytorch/issues/31734 , per your comment on that issue.

**Closed by ezyang** 2020-01-02 14:52 UTC

**Comment by xmyqsh** [comment] 2020-01-07 23:12
@One-sixth 
But why `        #     y = x` works here?
It should be `y = x[:]`

But `y = x` works here. I have tested it.
Why?

**Comment by One-sixth** [comment] 2020-01-08 04:43
> @One-sixth
> But why ` # y = x` works here?
> It should be `y = x[:]`
> 
> But `y = x` works here. I have tested it.
> Why?

It's strange? I think `y = x` and `y = x[:]` similar effects. There are only a few differences. One is a reference to the variable name, and the other is a reference to the value of the variable.

**Comment by xmyqsh** [comment] 2020-01-08 08:38
@One-sixth 
All right.
```
        # Bug here
        y = F.pad(x, pad=[0, 0, 0, 0, 0, self.pad_size], mode=self.mode, value=self.value)
        # if self.pad_size != 0:
        #     y = F.pad(x, pad=[0, 0, 0, 0, 0, self.pad_size], mode=self.mode, value=self.value)
        # else:
        #     y = x
```
Can you explain why `y = x` works here?
There is something I cannot get.

**Comment by One-sixth** [comment] 2020-01-08 15:18
> @六分之一
> 好。
> 
> ```
>         # Bug here
>         y = F.pad(x, pad=[0, 0, 0, 0, 0, self.pad_size], mode=self.mode, value=self.value)
>         # if self.pad_size != 0:
>         #     y = F.pad(x, pad=[0, 0, 0, 0, 0, self.pad_size], mode=self.mode, value=self.value)
>         # else:
>         #     y = x
> ```
> 
> 您能解释一下为什么`y = x`在这里工作吗？
> 我无法得到某些东西。
> 
> 另外，pytorchviz.make_dot在您的IRevNet上不起作用

So I think this is a torch.pad bug. I don't know much about the internals of pytorch. So I can’t explain it to you. You need to ask other people.  
I do not use pytorchviz, I think you need to ask the author of pytorchviz for this question.  
If you are interested in the IRevNet I implemented, you can check the full version https://github.com/One-sixth/like_i_revnet_pytorch

**Comment by xmyqsh** [comment] 2020-01-09 04:49
@One-sixth 
In a word, it is all about the trade-off.

You do not need to hold all the inputs and outputs of the operators to occupy the GPU memory.
That's the `IRevNet` target, right?
An alternative sub-option is re-forward.

Obviously, `invert` is better than `re-forward` in terms of run-time efficiency.
Anyway, all of these stuffs is trade-off.

**Comment by xmyqsh** [comment] 2020-01-09 04:54
@One-sixth 
Let me have a blind guess :)
The run-time is 3/2 of the normal one.
The memory usage is ..., oh my god!!!!!!!!

**Comment by One-sixth** [comment] 2020-01-09 13:57
> @One-sixth
> In a word, it is all about the trade-off.
> 
> You do not need to hold all the inputs and outputs of the operators to occupy the GPU memory.
> That's the `IRevNet` target, right?
> An alternative sub-option is re-forward.
> 
> Obviously, `invert` is better than `re-forward` in terms of run-time efficiency.
> Anyway, all of these stuffs is trade-off.

Things are a little different from what you think, and re-forward is still needed. Limited by my technology and pytorch. My approach is to save the output, then invert to get the input, and then re-forward to get the gradient. I can't get the gradient while inverting.  
  
The calculation time of this method is slightly slower than using torch.utils.checkpoint. In my test, it is about 4/3 to 6/5 times the normal operation time. Of course, only during training, the test can still have the same speed as the original method. As you think, if used properly, you can save a lot of VRAM.

**Comment by xmyqsh** [comment] 2020-01-10 04:12
@One-sixth over

**Comment by xmyqsh** [comment] 2020-01-10 11:19
@One-sixth 
`swap(x2, y)` is necessary.
Do you know Dirty Paper Coding?

**Comment by One-sixth** [comment] 2020-01-10 13:09
@xmyqsh Yes, when I don't swap them, the model performance seems to drop a lot. I was thinking from the perspective of restoring input, and no exchange would have no effect on restoring input.
I don't know that paper. But i'll read it later. Thanks for your hint.
