### ISSUE TITLE
confusing result between a tensor and singular tensor operation

### ISSUE THREAD

**Issue by wenyun** [pytorch/pytorch#7484] opened 2018-05-10 21:14 UTC
## Issue description

    >>> a = torch.Tensor([1,2,3,4,5])
    >>> a -= a[0]
    >>> a
    tensor([ 0.,  2.,  3.,  4.,  5.])

This seems to be a very confusing result. Even though the below works. I think the above should at least do broadcasting or throw an exception? Now it is doing a confusing operation but silent.

    >>> a = torch.Tensor([1,2,3,4,5])
    >>> a -= a[0].item()
    >>> a
    tensor([ 0.,  1.,  2.,  3.,  4.])

**Comment by fmassa** [comment] 2018-05-10 21:33
Duplicate of https://github.com/pytorch/pytorch/issues/906
I don't think we will be fixing it anytime soon.

**Comment by gchanan** [comment] 2019-12-27 16:28
closing in favor of https://github.com/pytorch/pytorch/issues/10756 and https://github.com/pytorch/pytorch/issues/17935.

**Closed by gchanan** 2019-12-27 16:28 UTC
Labels: module: operators, topic: partial aliasing, triaged
