### ISSUE TITLE
CPU and CUDA overflow in an inconsistent way

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#87565] opened 2022-10-23 01:57 UTC
### 🐛 Describe the bug

CPU and CUDA overflow in an inconsistent way.

For example, the `linalg.cond` will return `INF` for tensor with all ones on CPU, but returns a large number `6.9682e+15` instead

```py
import torch
print(torch.linalg.cond(torch.ones(5, 5, device='cuda'))) # tensor(6.9682e+15, device='cuda:0')
print(torch.linalg.cond(torch.ones(5, 5, device='cpu'))) # tensor(inf)
```

### Versions

torch: 1.12.1
cuda: 11.6

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by lezcano** [comment] 2022-10-23 20:28
Alas, as per usual, I don't think we can do much about this one. CPU and CUDA use different algorithm for performance reasons, so the results cannot be the same in edge cases. You can declare very large numbers to be infinity with something like `torch.where(result > 1e10, math.inf, result)`, but that's as good as it gets.

We should document these edge cases...

**Comment by IvanYashchuk** [comment] 2022-10-23 20:50
Closing as duplicate of https://github.com/pytorch/pytorch/issues/87170

**Closed by IvanYashchuk** 2022-10-23 20:50 UTC
Labels: triaged, module: linear algebra, module: edge cases
