### ISSUE TITLE
pytorch2.0 train compiled fairseq hubert model got error:torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised DynamicOutputShapeException: aten.index.Tensor

### ISSUE THREAD

**Issue by Qoboty** [pytorch/pytorch#97511] opened 2023-03-24 09:30 UTC
### 🐛 Describe the bug

pytorch2.0 , add model = torch.compile(model) to  fairseq  on
https://github.com/facebookresearch/fairseq/blob/main/fairseq_cli/train.py#L97

<img width="921" alt="image" src="https://user-images.githubusercontent.com/21211666/227479629-3f9017e6-6d06-4d60-b6f7-7f8fd530f0d5.png">

and train hubert model, got an error

torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised DynamicOutputShapeException: aten.index.Tensor

### Error logs

File "/tools/fairseq/fairseq2/fairseq/fairseq/models/hubert/hubert.py", line 352, in <graph break in apply_mask>
    mask_indices = torch.from_numpy(mask_indices).to(x.device)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1792, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 541, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 588, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/tools/anaconda/envs/myenv/lib/python3.9/site-packages/torch/_dynamo/output_graph.py", line 675, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e) from e
torch._dynamo.exc.BackendCompilerFailed: debug_wrapper raised DynamicOutputShapeException: aten.index.Tensor

### Versions

pytorch2.0

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @soumith @ngimel

**Comment by ezyang** [comment] 2023-03-24 15:20
What happens if you run with dynamic=True?

**Comment by ezyang** [comment] 2023-03-24 15:21
dynamic=True probably doesn't help; the problem is we have a data dependent index that we're not graph breaking on, at a guess.

**Comment by nanoric** [comment] 2023-04-21 14:20
This can be producted from:
```
import torch
@torch.compile()
def test():
    a = Tensor([i for i in range(10)])
    a[a > 5] = 0

test()
```
Though this might seems a bug of torch.compile.
But you can fix it with:
```
torch.where(a > 5, 0, a)
```

PS: It seems that most of failure when using torch.compile() is caused by Python's syntax sugar.

**Comment by ezyang** [comment] 2023-04-21 15:43
@nanoric you forgot to import Tensor. With the import

```
(/home/ezyang/local/c/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/c/pytorch (23b25eb5)]$ python wzz.py
(/home/ezyang/local/c/pytorch-env) [ezyang@devgpu020.ftw1 ~/local/c/pytorch (23b25eb5)]$ cat wzz.py
import torch
from torch import Tensor
@torch.compile()
def test():
    a = Tensor([i for i in range(10)])
    a[a > 5] = 0

test()
```

But the perf is bad because it will recompile. dynamic=True will help here.

**Comment by ezyang** [comment] 2023-05-09 15:24
A lot of these have been fixed in main; and we're very interested in fixing any of the other ones. Send us the bugs.

**Comment by anijain2305** [comment] 2023-05-25 05:10
@Qoboty @nanoric Is there a way to reproduce this issue for us? We are very interested in fixing these bugs.

**Comment by janeyx99** [comment] 2023-06-05 17:19
This should be fixed on main now. Closing, but feel free to reopen if otherwise

**Comment by ezyang** [comment] 2023-06-05 17:20
I think it was fixed in https://github.com/pytorch/pytorch/pull/102843

**Closed by janeyx99** 2023-06-05 17:19 UTC
Labels: triage review, bug, oncall: pt2, module: dynamic shapes
