### ISSUE TITLE
cuda runtime error (59)

### ISSUE THREAD

**Issue by klu1211** [pytorch/pytorch#5916] opened 2018-03-21 00:53 UTC
When I run this code:

```
N, C = 1, 1
criterion = nn.NLLLoss()
model = nn.Conv2d(C, 3, (3, 3)).cuda()
inp = Variable(torch.randn(N, 1, 3, 3)).cuda()
pred = model(inp)
target = Variable(torch.from_numpy(np.array([3]))).view(1, 1, 1).cuda()
criterion(pred, target)
```

I get this error:
```
cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1518244421288/work/torch/lib/THC/generic/THCTensorCopy.c:70
```

Due to the value of `target` being `3`, and not in the set of `{0, 1, 2}`. It took me a while to figure out and I was wondering this is an easy to fix issue, and if it is I was wondering how I would get started as I'm quite eager to contribute to Pytorch

**Comment by apaszke** [comment] 2018-03-21 12:44
Duplicate of #5857. It should be quite easy. If you want to submit a PR you should look for definition of `THCudaCheck` and modify that to report a better error message in case of assertion failures. Thanks!

**Comment by li-roy** [comment] 2018-03-29 00:17
@apaszke Can we reopen this? I think the other issue is actually caused by a different check.

**Comment by weiyangfb** [comment] 2018-06-12 22:20
@li-roy Can I ask what is the cause of this issue?

**Comment by li-roy** [comment] 2018-06-12 22:59
It's being thrown here, I think:
https://github.com/pytorch/pytorch/blob/master/aten/src/THC/generic/THCTensorCopy.cpp#L66

I think we're just looking to improve the error message.

**Comment by ezyang** [comment] 2020-09-23 19:48
New error seems pretty clear.

```
/scratch/ezyang/pytorch-scratch2/aten/src/THCUNN/SpatialClassNLLCriterion.cu:106: cunn_SpatialClassNLLCriterion_updateOutput_kernel: block: [0,0,0], thread: [0,0,0] Assertion `t >= 0 && t < n_classes` failed.
(/scratch/ezyang/pytorch-scratch2-env) ezyang@devfair040:/scratch/ezyang/pytorch-scratch2$ cat foo.py
import torch
import torch.nn as nn
import numpy as np
N, C = 1, 1
criterion = nn.NLLLoss()
model = nn.Conv2d(C, 3, (3, 3)).cuda()
inp = torch.randn(N, 1, 3, 3).cuda()
pred = model(inp)
target = torch.from_numpy(np.array([3])).view(1, 1, 1).cuda()
criterion(pred, target)
```

**Closed by ezyang** 2020-09-23 19:48 UTC
Labels: todo
