### ISSUE TITLE
Upgrade pytorch to use XNNPACK instead of NNPACK for android

### ISSUE THREAD

**Issue by RuABraun** [pytorch/pytorch#30622] opened 2019-12-02 19:52 UTC
## 🚀 Feature

Use [XNNPACK](https://github.com/google/XNNPACK) for floating point operations on android. 

## Motivation

At the moment pytorch uses NNPACK for floating point operations on Android. NNPACK is not actively developed anymore and [XNNPACK is the successor](https://github.com/Maratyszcza/NNPACK/issues/168), and is in my experience faster (as well as having a better and more complete interface).

**Comment by AshkanAliabadi** [comment] 2019-12-03 19:00
Hi Rudolf.  This is work in progress and should be done soon.  The bulk of the work is already done, but an efficient integration requires a bit of work on the PyTorch side to cache one-time computations, which is where currently my focus is.  I'll update this issue when I am done.  Cheers.

**Comment by forresti** [comment] 2020-01-06 04:23
@AshkanAliabadi This is slightly off-topic, but how does one select whether to use THNN or NNPACK for inference on ARM in PyTorch? When I look at some profiling results, I see I am using THNN (very slow, and evidently single-threaded), and I would prefer to use something more optimized.

**Comment by AshkanAliabadi** [comment] 2020-01-06 05:20
The answer to your question will be somewhat different based on the state
of the code before integration with XNNPACK, or after it.

Assuming that you are indeed compiling PyTorch with NNPACK enabled, before
the XNNPACK switch, and as it currently stands on master, you are
effectively at the mercy of the the checks in
aten/src/ATen/native/Convolution.cpp:_convolution() for convolutions (and
equivalent checks for other operators) which do their best to pick the most
efficient code path based on a multitide of conditions, the core of which
usually boil down to testing whether an efficient implementation indeed
exists for that particular configuration or not.  Your best bet then, would
be to either put a breakpoint in that function or printf-debug it to see
why a more efficient code path is not taken, and then modify your network
to meet those requirements.  It might also be the case that you are not
compiling with NNPACK enabled.

After the patch that introduces XNNPACK integration is merged, we may
expose mobile specific operators that directly trigger these efficient
implementations, or we may end up making the workflow more transparent to
the user by introducing a JIT pass that automatically modifiea the network
to use these newly introduced modules that decouple operator creation from
exexution, or both.  We are currently debating the pros and cons of each
approach.  These newer modules will be significantly more efficient mostly
because they allow for caching of one-time computations in computationally
expensive operators as mentioned above.

Regardless, we are close to merging this code and FP32 performance will
soon see a significant boost on mobile as part of moving to NHWC memory
layout, integration with XNNPACK and a multitude of smaller optimizations.
We will make sure to clearly communicate the best practices to achieve
maximum performance in the documentation and I will update this issue with
a link to that, but for now, and as things currently stand, your best bet
would be to debug your code as mentioned above to see which check's failure
is preventing a more efficient code path to be taken.

**Comment by AshkanAliabadi** [comment] 2020-01-06 05:27
The current state of XNNPACK integration can be tracked in this PR https://github.com/pytorch/pytorch/pull/30644.

**Comment by forresti** [comment] 2020-01-06 05:36
Thanks a ton for your detailed reply! I will try what you suggested. Once I figure out what is causing the check to fail, I will see if I can tweak my net design to fit the constraints of NNPACK. (And, I might do the same exercise again once XNNPACK is integrated.)

**Comment by forresti** [comment] 2020-01-07 18:38
@AshkanAliabadi I just made a build of pytorch with -O0 and -DEBUG. Now, probably a dumb question, but I have to admit that I've never put a breakpoint in a C++ library (pytorch / aten) that I am calling via Python. Presumably I should use GDB?

I was looking at [this question on stackoverflow](https://stackoverflow.com/questions/46169522/how-to-debug-underlying-c-library-from-python-interface), which says it's as simple as this:
```
gdb python
b aten/src/ATen/native/Convolution.cpp 748
run train.py
```

**Comment by soumith** [comment] 2020-01-07 19:41
@forresti you can also set a breakpoint on a function. So, maybe set a breakpoint on `_convolution_nogroup` (or whichever is in the call-stack before that, which you want to enter)

**Comment by AshkanAliabadi** [comment] 2020-01-07 20:07
OK, so I need to preface this answer by saying that there is a bit of personal preference involved in how one debugs - it depends on what feels most natural to you - but here is how I personally do it in general.

If developing on Windows, I use MSVC - nothing comes close to Microsoft's debugger in terms of responsiveness and ease of use.  On all Unix based operating systems I use **printf**s for 90+% of all debugging since most of the time you just want to inspect the value of a variable and printf is more than enough for that usecase.  The other 10% where there is something more serious going on, I use gdb.  [Here](**url**)'s a GDB cheat sheet that you might find useful.  In this particular case though, printf is good enough for me.

Following the code, you want to make sure that your convolution is not transposed and not dilated.  That will be enough to make the code reach the following condition in _convolution_nogroup:

```
if (params.use_nnpack()) {
...
}
```

Then I would put a bunch of print statements in ConvParams::use_nnpack to see what's causing it to return false.


```
std::cout << "at::_nnpack_available(): " << at::_nnpack_available() << std::endl;
std::cout << "input.options().backend() == at::Backend::CPU: " << (input.options().backend() == at::Backend::CPU) << std::endl;

```

and so on for every check in there.

**Comment by forresti** [comment] 2020-01-08 20:11
Both of your suggestions worked -- I was able to get a `_convolution_nogroup` breakpoint to work, and I also added print statements. As a result, I was able to figure out why PyTorch was using THNN instead of NNPACK:

As I understand it, the issue causing it to use THNN instead of NNPACK before was that, that C10_MOBILE and CAFFE2_FB_LIMITED_MOBILE_CAPABILITY are undefined (which they are in my build), it requires `input.size(0) >= 16`, i.e. `batch size > 16`. So, in `aten/src/ATen/native/Convolution.cpp : use_nnpack()`, I commented out the following statement, and I recompiled PyTorch, and then I confirmed with torchprof that it is now using `_nnpack_spatial_convolution`.

```
#if !defined(C10_MOBILE) && !defined(CAFFE2_FB_LIMITED_MOBILE_CAPABILITY)
         && input.size(0) >= 16 // ensure large enough batch size to ensure perf, tuneable
#endif
```

Thanks for your help!

**Comment by AshkanAliabadi** [comment] 2020-01-09 00:59
Glad that we managed to help. By the way, if you are developing for ARM on
mobile or an embedded ARM processor you probably want C10_MOBILE defined.
Are you running into any issues with that defined?

**Comment by RuABraun** [comment] 2020-02-12 17:49
How's this going?

**Comment by AshkanAliabadi** [comment] 2020-02-12 18:28
#32509

**Comment by shekhirin** [comment] 2020-11-02 06:54
I suppose it's a resolved issue since https://github.com/pytorch/pytorch/commit/941b42428aaf51489a7e1848bfc145205d372eb7 is merged

**Comment by windmaple** [comment] 2021-01-24 06:06
Is XNNPACK used by default now for FP32 models? Or do we still need to turn on some compile/runtime switch?

**Comment by AshkanAliabadi** [comment] 2021-01-24 21:09
It is ON by default, but there are two steps to efficient use of XNNPACK as a backend in PyTorch:

1) First, making sure it is enabled as part of the build and compiled in, which it is by default.  This is controlled by the [USE_XNNPACK CMake option which is defaulted to ON](https://github.com/pytorch/pytorch/blob/1f40f2a1723fd3b9302bea3829f2570c8e0e7e94/CMakeLists.txt#L227).

2) Second, and more importantly - and I say more importantly because it is often the one neglected - is making sure your model is massaged and prepared to hit the fastest code paths available.  Otherwise, PyTorch's use of XNNPACK will be far from optimal and this will come at a considerable cost to performance.  This preparation step can be done as a result of running you model through [mobile optimizer](https://pytorch.org/docs/stable/mobile_optimizer.html).

Follow this [performance recipe](https://pytorch.org/tutorials/recipes/mobile_perf.html).  This recipe is for quantized models, but quantization aside, the steps are similar.  In a nutshell:

```
import torch
import torchvision  # Only if you are interested in using MobileNet v2 as I am using in this example.
from torch.utils.mobile_optimizer import optimize_for_mobile

# Replace with a model of your choosing.
fp_model = torchvision.models.mobilenet_v2(pretrained=True).eval()
scripted_fp_model = torch.jit.script(fp_model)

# scripted_fp_model is the torchscript model prior to optimization.  This will hit some code paths in XNNPACK but not all.  If you are interested in seeing the delta in performance, save this model now, otherwise you can skip this step.
# torch.jit.save(scripted_fp_model, "mobilenetv2_reference.pt")

optimized_scripted_fp_model = optimize_for_mobile(scripted_fp_model)
torch.jit.save(optimized_scripted_fp_model, "mobilenetv2_optimized.pt")

# mobilenetv2_optimized.pt should take advantage of XNNPACK much more optimally.
```

**Closed** 2021-01-25 03:11 UTC
Labels: enhancement, module: third_party, oncall: mobile, triaged
