### ISSUE TITLE
Unexpected conversion using .int()

### ISSUE THREAD

**Issue by mravanelli** [pytorch/pytorch#68561] opened 2021-11-18 01:45 UTC
Hi, 
when I do the following int() casting  with some specific numbers, I got the wrong result:

```
N = 41.0
(N* torch.tensor([1.0/N], dtype=torch.float32)).int()
```
The correct answer should be ` tensor([1], dtype=torch.int32)`, but it actually returns  ` tensor([0], dtype=torch.int32)`.
This happens only with some specific numbers (e.g, 41.0 or 82.0) and. most of the times this is correct (see examples below). 
I don't really understand why this happens. If I use `(N* torch.tensor([1.0/N], dtype=torch.float64)).int()` it works.

You can find some examples below. 

_________________________________________________________
**Correct (most of the times):**

```
(15.0 * torch.tensor([1.0/15.0], dtype=torch.float32)).int()
tensor([1], dtype=torch.int32)
 (42.0 * torch.tensor([1.0/42.0], dtype=torch.float32)).int()
tensor([1], dtype=torch.int32)
 (4540.0 * torch.tensor([1.0/4540.0], dtype=torch.float32)).int()
tensor([1], dtype=torch.int32)
```

**Wrong:**
```
(41.0 * torch.tensor([1.0/41.0], dtype=torch.float32)).int()
tensor([0], dtype=torch.int32)
(82.0 * torch.tensor([1.0/82.0], dtype=torch.float32)).int()
tensor([0], dtype=torch.int32)
```

One way to fix it is to convert the tensor to float64:

```
(41.0 * torch.tensor([1.0/41.0], dtype=torch.float64)).int()
tensor([1], dtype=torch.int32)
```

**Comment by kit1980** [comment] 2021-11-18 03:39
This is because floating point arithmetic is imprecise. 
41 * (1/41) is actually less than 1 using fp32:

```
N = 41.0
(N* torch.tensor([1.0/N], dtype=torch.float32)).item()
0.9999999403953552
```

And `int()` basically rounds down (for example, `torch.tensor(0.9).int()` returns 0 tensor).

For the behavior you expect, you can call `round()` before `int()`.

**Comment by mravanelli** [comment] 2021-11-18 03:46
True. I think we can switch from int() to round(). This should solve the issue. I bet there are other recipes with this potential issue and tomorrow I will fix all of them.

**Comment by albanD** [comment] 2021-11-18 08:56
Closing as expected behavior due to floating point arithmetic.

**Closed by albanD** 2021-11-18 08:56 UTC
