### ISSUE TITLE
tensor_with_bizarre_strides.copy_(src) may run into data race for cuda kernel

### ISSUE THREAD

**Issue by zhaolianshuizls** [pytorch/pytorch#107110] opened 2023-08-14 02:25 UTC
### 🐛 Describe the bug

```python
import torch

dst = torch.full([7, 2], -1).int().cuda()
dst_with_bizarre_stride = torch.as_strided(dst, [7, 2], [1,2])

src = torch.tensor([1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]).int().cuda()
src_t = src.t()

dst_with_bizarre_stride.copy_(src_t)
```

the above example is just to show that `dst_with_bizarre_stride` has a stride that results in space sharing of multiple elements, so when doing copy_, is such data race condition being properly coped with? From what I know, cuda kernel does not deal with this data race.
[each src element is simply mapped to a dst element](https://github.com/pytorch/pytorch/blob/7c98e70d44abc7a1aead68b6ea6c8adc8c554db5/aten/src/ATen/native/cuda/Copy.cu#L26)

[copy is done through an elementwise cuda kernel](https://github.com/pytorch/pytorch/blob/7c98e70d44abc7a1aead68b6ea6c8adc8c554db5/aten/src/ATen/native/cuda/Copy.cu#L26)

So I think when output tensor has elements sharing the same space, there is a data race issue here, and the final output tensor is undefined.

### Versions

![image](https://github.com/pytorch/pytorch/assets/121373234/431cdfdd-2a36-4723-a8d8-fb49f725d323)

**Comment by colesbury** [comment] 2023-08-14 17:03
This is, depending on how you look at it, either a known issue or "by design".  There are number of similar issues, related to overlapping elements, for example: https://github.com/pytorch/pytorch/issues/5272. I'm closing this, since the same underlying behavior is described there.

It would be great to detect and either properly handle or raise an error message for these calls, but we don't have any current plans to do so.

**Closed by colesbury** 2023-08-14 17:03 UTC
