### ISSUE TITLE
Compiling error of master branch

### ISSUE THREAD

**Issue by lfz** [pytorch/pytorch#5152] opened 2018-02-09 07:55 UTC
- OS: Ubuntu 14.04
- PyTorch version: master
- How you installed PyTorch (conda, pip, source): source
- Python version: 3.5
- CUDA/cuDNN version: 8.0/ v6
- GPU models and configuration: 8 titan x
- GCC version (if compiling from source): 4.9

I am trying to compiling the source code from the recent master branch, but it failed. The error log is:

> gcc -pthread -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/usr/local/cuda/include -I/data/home/liao/Downloads/pytorch -I/data/home/liao/Downloads/pytorch/torch/csrc -I/data/home/liao/Download
s/pytorch/torch/lib/pybind11/include -I/data/home/liao/Downloads/pytorch/torch/lib/tmp_install/include -I/data/home/liao/Downloads/pytorch/torch/lib/tmp_install/include/TH -I/data/home/liao/Downloads
/pytorch/torch/lib/tmp_install/include/THNN -I/data/home/liao/Downloads/pytorch/torch/lib/tmp_install/include/ATen -I/home/liao/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/data/home/l
iao/Downloads/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/data/home/liao/Downloads/pytorch/torch/lib/tmp_install/include/THCUNN -I/home/liao/anaconda3/include/python3.5m -c
 torch/csrc/autograd/python_variable_indexing.cpp -o build/temp.linux-x86_64-3.5/torch/csrc/autograd/python_variable_indexing.o -D_THP_CORE -std=c++11 -Wno-write-strings -fno-strict-aliasing -Wno-mis
sing-braces -DWITH_NUMPY -DWITH_DISTRIBUTED -DWITH_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DWITH_NCCL -DWITH_CUDNN
torch/csrc/jit/script/compiler.cpp: At global scope:
torch/csrc/jit/script/compiler.cpp:350:41: error: converting to ‘const AttributeMap {aka const std::unordered_map<std::basic_string<char>, std::pair<double, std::basic_string<char> > >}’ from initial
izer list would use explicit constructor ‘std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::unordered_map(std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type, const hasher&, const key_e
qual&, const allocator_type&) [with _Key = std::basic_string<char>; _Tp = std::pair<double, std::basic_string<char> >; _Hash = std::hash<std::basic_string<char> >; _Pred = std::equal_to<std::basic_st
ring<char> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::size_type = long u
nsigned int; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::hasher = std::hash<std::basic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::key_equal = std::equal_to<std::bas
ic_string<char> >; std::unordered_map<_Key, _Tp, _Hash, _Pred, _Alloc>::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::pair<double, std::basic_string<char> > > >]’
       const AttributeMap& attributes = {},
                                         ^

I believe it is caused by the recently modification in torch/csrc/jit/script/compiler.cpp (3e856137518da977ea08468d5cf2c2aa8d547370)

**Comment by ezyang** [comment] 2018-02-09 17:49
CC @bddppq

**Comment by zou3519** [comment] 2020-08-11 14:21
Closing this issue because of time and inability to reproduce. Please feel free to reopen if you are still having this problem.

**Closed by zou3519** 2020-08-11 14:21 UTC
