### ISSUE TITLE
nn.Parameter{List,Dict} not copied to gpus in forward pass when nn.DataParallel is used

### ISSUE THREAD

**Issue by grtzsohalf** [pytorch/pytorch#36035] opened 2020-04-05 03:30 UTC
## 🐛 Bug

When I use nn.DataParallel to wrap an nn.Module X, nn.Parameter in X is not copied to gpus in the forward pass. I think nn.Parameter can be considered as a part of module parameters, so it should be treated like other nn.Module parameters in X as well. Is it an intentional design?

## To Reproduce

test.py:
```python
import sys
import torch
import torch.nn as nn
import torch.nn.functional as F


gpus = list(map(int, sys.argv[1].split(',')))


class Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.alpha = nn.ParameterList()

        for i in range(4):
            self.alpha.append(nn.Parameter(1e-3*torch.randn(i+2, 5)))

        self.cnn = nn.Conv2d(1, 1, 1, 1, 1)


    def forward(self, x):
        print(self.alpha)
        print(self.cnn)
        return x


if __name__ == '__main__':
    net = Net().cuda()
    if len(gpus) > 1:
        net = nn.DataParallel(net, device_ids=gpus)

    net(torch.rand(4, 5))
```
When I run `python3 test.py 0` (which means device_id = [0]), the output is
```
ParameterList(
    (0): Parameter containing: [torch.cuda.FloatTensor of size 2x5 (GPU 0)]
    (1): Parameter containing: [torch.cuda.FloatTensor of size 3x5 (GPU 0)]
    (2): Parameter containing: [torch.cuda.FloatTensor of size 4x5 (GPU 0)]
    (3): Parameter containing: [torch.cuda.FloatTensor of size 5x5 (GPU 0)]
)
Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1), padding=(1, 1))
```
However, when I run `python3 test.py 0,1` (which means device_id = [0, 1]), the output is
```
ParameterList()
Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1), padding=(1, 1))
ParameterList()
Conv2d(1, 1, kernel_size=(1, 1), stride=(1, 1), padding=(1, 1))
```
Only nn.Module is copied to gpus in forward pass.
How can I use and train nn.Parameter just like nn.Module with nn.DataParallel?

## Expected behavior

When the nn.Module X is wrapped with nn.DataParallel, both nn.Module and nn.Parameter in X should be copied to gpus.

## Environment

PyTorch version: 1.6.0.dev20200401+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Arch Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.17.0

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX 1060 6GB

Nvidia driver version: 440.64
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.2
[pip3] torch==1.6.0.dev20200401+cu101
[pip3] torchexp==0.1.0
[pip3] torchvision==0.6.0.dev20200401+cu101
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by zou3519** [comment] 2020-04-06 15:01
Seems like a correctness issue so I am marking it as high-pri.

**Comment by albanD** [comment] 2020-04-06 17:08
Looks like a bad interaction between ParameterList and the replicate function on nn.Module. This needs more investigation.

**Comment by albanD** [comment] 2020-04-06 17:26
Reducing the priority as many other things do not interact nicely with DataParallel. We can increase it again if we see many users hit this issue.

**Comment by grtzsohalf** [comment] 2020-04-07 02:49
Thanks for your notice, @zou3519 @albanD .
For now, is there a recommended work around to use nn.Parameter with nn.DataParallel?

**Comment by zou3519** [comment] 2020-04-07 12:54
Instead of using `nn.ParameterList`, Does it work if you directly assign the parameters to the model?

**Comment by grtzsohalf** [comment] 2020-04-07 13:14
Now I directly pass nn.Parameter as a part of inputs into the model.
test.py:
```python
import sys
import torch
import torch.nn as nn
import torch.nn.functional as F


gpus = list(map(int, sys.argv[1].split(',')))


class Net(nn.Module):
    def __init__(self):
        super().__init__()

        self.alpha = nn.ParameterList()
        for i in range(2):
            self.alpha.append(nn.Parameter(1e-3*torch.randn(i+2, 5)))
        print('Init: ', [a for a in self.alpha])


    def forward(self, x, alphas):
        # print('Inputs: ', x.shape)
        if alphas is not None:
            alphas = [a.squeeze(0) for a in alphas]
            print('In forward pass: ', [a for a in alphas])
            print([a.shape for a in alphas])
        else:
            print('In forward pass: ', [a.shape for a in self.alpha])
        return x


if __name__ == '__main__':
    net = Net().cuda()
    if len(gpus) > 1:
        net = nn.DataParallel(net, device_ids=gpus)
        alphas = [a.unsqueeze(0).repeat(2,1,1) for a in net.module.alpha]
        print([a.shape for a in alphas])
    else:
        alphas = None

    net(torch.rand(4, 5), alphas)
    # print('Not in forward pass: ', [n for n, p in net.named_parameters()])
```
If I run `python3 test.py 0,1`, then I get:
```
Init:  [Parameter containing:
tensor([[-0.0011,  0.0020,  0.0002, -0.0011,  0.0001],
        [ 0.0008,  0.0002,  0.0022,  0.0007, -0.0011]], requires_grad=True), Parameter containing:
tensor([[ 0.0010, -0.0008,  0.0010,  0.0003, -0.0013],
        [-0.0005, -0.0005, -0.0008,  0.0005,  0.0003],
        [ 0.0003,  0.0016,  0.0003, -0.0002,  0.0009]], requires_grad=True)]

[torch.Size([2, 2, 5]), torch.Size([2, 3, 5])]

In forward pass:  In forward pass:  [tensor([[-0.0011,  0.0020,  0.0002, -0.0011,  0.0001],
        [ 0.0008,  0.0002,  0.0022,  0.0007, -0.0011]], device='cuda:0',
       grad_fn=<SqueezeBackward1>), tensor([[ 0.0010, -0.0008,  0.0010,  0.0003, -0.0013],
        [-0.0005, -0.0005, -0.0008,  0.0005,  0.0003],
        [ 0.0003,  0.0016,  0.0003, -0.0002,  0.0009]], device='cuda:0',
       grad_fn=<SqueezeBackward1>)]
[torch.Size([2, 5]), torch.Size([3, 5])]
[tensor([[-0.0011,  0.0020,  0.0002, -0.0011,  0.0001],
        [ 0.0008,  0.0002,  0.0022,  0.0007, -0.0011]], device='cuda:1',
       grad_fn=<SqueezeBackward1>), tensor([[ 0.0010, -0.0008,  0.0010,  0.0003, -0.0013],
        [-0.0005, -0.0005, -0.0008,  0.0005,  0.0003],
        [ 0.0003,  0.0016,  0.0003, -0.0002,  0.0009]], device='cuda:1',
       grad_fn=<SqueezeBackward1>)]
[torch.Size([2, 5]), torch.Size([3, 5])]
```
This approach can work.

**Comment by grtzsohalf** [comment] 2020-04-07 13:15
> Instead of using `nn.ParameterList`, Does it work if you directly assign the parameters to the model?

It doesn't work in this way.

**Comment by lidazhang** [comment] 2020-04-14 15:43
Same problem here using nn.Parameter() with DataParallel

**Comment by cyranawm** [comment] 2020-05-29 16:29
Same problem here, during the forward pass of a module wrapped with DataParallel, the  nn.ParameterList is empty.

**Comment by ruoshiliu** [comment] 2020-06-19 02:39
I also encountered the same problem. This problem also applies to ```ParameterDict()```. Is there any workaround solution for this issue?

**Comment by albanD** [comment] 2020-06-19 14:39
Hi,

The workaround right now is just to save the Parameter directly on the module and not in the dict.

**Comment by ezyang** [comment] 2020-06-22 17:27
nb that if at all possible, you should using DistributedDataParallel instead!

**Comment by vfdev-5** [comment] 2020-06-25 15:38
@ezyang I'll work on this issue. 

As far as I understand from the code of `replicate` method of `nn/parallel/replicate.py`, I think the problem is with this line: 
https://github.com/pytorch/pytorch/blob/e440c370c5ea47e5e4345788320391a51154b50f/torch/nn/parallel/replicate.py#L146
as seems like we cannot add parameters with `setattr` for `ParameterList` or `ParameterDict`.
Replacing it with 
```python
    if isinstance(replica, (ParameterList, ParameterDict)):
        replica._parameters[str(key)] = Parameter(param)
    else:
        setattr(replica, key, param)
```
propagates parameters from list/dict to replicas. What do you think about such solution ? Otherwise, could you please hint another way to fix the problem. Thanks !

**Comment by albanD** [comment] 2020-06-25 15:54
Should they actually be Parameters? The comment seem to hint at the fact that they should not.

**Comment by vfdev-5** [comment] 2020-06-25 15:59
@albanD seems like we cannot add non-`Parameter` object to `replica._parameters[str(key)] = ...`

**Comment by albanD** [comment] 2020-06-25 17:54
But do we want them to be in `_parameters` ?  When we do ` setattr(replica, key, param) ` they are just saved as regular Tensors attributes no?

**Comment by vfdev-5** [comment] 2020-06-25 20:29
> When we do setattr(replica, key, param) they are just saved as regular Tensors attributes no?

yes, that's true and it works correctly for simple `Parameter`s as being declared in the module as attributes (e.g. `self.beta = nn.Parameter(tensor)`) they are added to replicas as tensors (e.g. `setattr(replica, "beta", tensor_on_appropriate_device)`).

> But do we want them to be in `_parameters`  ?

Yes, as for `ParameterList` and `ParameterDict` it is a bit different, IMO. Parent module's replica (e.g. `Net` from the example) will contain empty copy of `ParameterList/Dict` due to https://github.com/pytorch/pytorch/blob/e440c370c5ea47e5e4345788320391a51154b50f/torch/nn/parallel/replicate.py#L113-L121
and 
https://github.com/pytorch/pytorch/blob/e440c370c5ea47e5e4345788320391a51154b50f/torch/nn/parallel/replicate.py#L133
where we would like to insert tensors from original parameter list/dict. Currently, the code inserts the following:
```
getattr(replica.alpha, "0")
getattr(replica.alpha, "1")
...
```
instead of 
```
replica.alpha._parameters["0"]
replica.alpha._parameters["1"]
```

**Comment by albanD** [comment] 2020-06-25 21:41
Can you confirm that I understand the root cause properly here:
- ParameterList, when accessed, only returns from the Parameters it contains
- When replication happens we set regular attributes on them (that are not Parameters)
- When accessing them, it fails as no Parameter with that name exist (attributes do, but they are plain Tensors and not Parameters. And they can't be accessed because of our custom getitem anyway).

If so should replicate keep the `ParameterList` given that there are no Parameters anymore?
Or make `ParameterList` aware of the replicate and behave accordingly by handling non-Parameter objects?

**Comment by vfdev-5** [comment] 2020-06-25 22:06
> ParameterList, when accessed, only returns from the Parameters it contains

Well, normally, yes. Maybe, I do not understand this question...

> When replication happens we set regular attributes on them (that are not Parameters)

Yes, the code `setattr(replica, key, param)` if `replica` is a `ParameterList` sets key as `0`, `1`, ... and `param` as Tensor on appropriate cuda device.

> When accessing them, it fails as no Parameter with that name exist (attributes do, but they are plain Tensors and not Parameters. And they can't be accessed because of our custom getitem anyway).

yes, exactly `__getitem__` on ParameterList is looking in `self._parameters`.

> If so should replicate keep the ParameterList given that there are no Parameters anymore?
Or make ParameterList aware of the replicate and behave accordingly by handling non-Parameter objects?

Well, difficult to say. How about just replacing ParameterList replica's `_parameters` by `OrderedDict` with tensors (on correct cuda device) same as for Parameter ? 
Like that 
```python
        if isinstance(module_copies[0][i], (ParameterList, ParameterDict)):
            # if replica is ParameterList or ParameterDict we setup its _parameters as
            # ordered dict of tensors
            for j in range(num_replicas):
                replica = module_copies[j][i]
                parameters = OrderedDict()
                for key, param in module._parameters.items():
                    param_idx = param_indices[param]
                    param = param_copies[j][param_idx]
                    parameters[str(key)] = param
                replica._parameters = parameters
```

**Comment by albanD** [comment] 2020-06-26 14:00
I agree that this would solve this issue but I wonder if it's not going to cause more issues when other part of torch.nn interact with it. I don't think we want to "pretend" these are Parameters even though they are Tensors with history. Won't `.parameters()` pick up these new Tensors as it traverse all the `_parameters` dict?

One thing I can thing of would be to allow ParameterList to contain elements that are not Parameters (like any other nn.Module). These would be added via a special API and won't be registered in the _parameters dict.

**Comment by vfdev-5** [comment] 2020-06-26 14:49
> Won't `.parameters()` pick up these new Tensors as it traverse all the `_parameters` dict?

Thanks for pointing this out ! Yes, we pick this tensors up.

> One thing I can thing of would be to allow ParameterList to contain elements that are not Parameters (like any other nn.Module). These would be added via a special API and won't be registered in the _parameters dict.

I think, the problem will then appear from the user side when he/she would like to access the elements of ParameterList...

**Comment by albanD** [comment] 2020-06-26 15:15
> I think, the problem will then appear from the user side when he/she would like to access the elements of ParameterList...

Ho yes sorry, this would imply modifying the getitem to return the elements from either _parameters or regular attributes (saved in another dict I guess).

**Comment by vfdev-5** [comment] 2020-06-29 11:35
Just checked DDP case single process multiple-devices use-case (https://github.com/pytorch/pytorch/pull/36503) and same issue persist for ParameterList/Dict.

<summary>

Code and output

<details>

```python
> python -m torch.distributed.launch --use_env --nproc_per_node=1 ddp_parameters.py

import torch
import torch.nn as nn
import torch.distributed as dist
from torch.nn.parallel import DistributedDataParallel as DDP


class Net(nn.Module):
    
    def __init__(self):
        super().__init__()
        
        self.beta = nn.Parameter(torch.tensor(0.0))
        self.alpha = nn.ParameterList([nn.Parameter(torch.tensor(1.0)), nn.Parameter(torch.tensor(2.0))])
        self.gamma = nn.ParameterDict({"a": nn.Parameter(torch.tensor(3.0)), "b": nn.Parameter(torch.tensor(4.0))})


class NestedNet(nn.Module):
    
    def __init__(self):
        super().__init__()
        
        self.base = Net()

        self.main_beta = nn.Parameter(torch.tensor(10.0))
        self.main_alpha = nn.ParameterList([nn.Parameter(torch.tensor(11.0)), nn.Parameter(torch.tensor(12.0))])
        self.main_gamma = nn.ParameterDict({"A": nn.Parameter(torch.tensor(13.0)), "B": nn.Parameter(torch.tensor(14.0))})

    def forward(self, x):
        print(dist.get_rank(), "- forward", self.main_beta)
        print(dist.get_rank(), "-- forward", self.main_alpha)
        print(dist.get_rank(), "--- forward", self.base.alpha)


if __name__ == '__main__':
    import os    
    dist.init_process_group("gloo", init_method="env://")
    
    local_rank = int(os.environ["LOCAL_RANK"])
    torch.cuda.set_device(local_rank)
    net = NestedNet().cuda()
    ddp_net = DDP(net, device_ids=[0, 1])

    if dist.get_rank() == 0:
        print("ddp_net parameters:", list(ddp_net.parameters()))
    
    ddp_net(torch.rand(2, 4))

```
Output
```
ddp_net parameters: [Parameter containing:
tensor(10., device='cuda:0', requires_grad=True), Parameter containing:
tensor(0., device='cuda:0', requires_grad=True), Parameter containing:
tensor(1., device='cuda:0', requires_grad=True), Parameter containing:
tensor(2., device='cuda:0', requires_grad=True), Parameter containing:
tensor(3., device='cuda:0', requires_grad=True), Parameter containing:
tensor(4., device='cuda:0', requires_grad=True), Parameter containing:
tensor(11., device='cuda:0', requires_grad=True), Parameter containing:
tensor(12., device='cuda:0', requires_grad=True), Parameter containing:
tensor(13., device='cuda:0', requires_grad=True), Parameter containing:
tensor(14., device='cuda:0', requires_grad=True)]
0 - forward 0 - forward Parameter containing:
tensor(10., device='cuda:0', requires_grad=True)
0 -- forward ParameterList(
    (0): Parameter containing: [torch.cuda.FloatTensor of size  (GPU 0)]
    (1): Parameter containing: [torch.cuda.FloatTensor of size  (GPU 0)]
)
0 --- forward ParameterList(
    (0): Parameter containing: [torch.cuda.FloatTensor of size  (GPU 0)]
    (1): Parameter containing: [torch.cuda.FloatTensor of size  (GPU 0)]
)
tensor(10., device='cuda:1', requires_grad=True)
0 -- forward ParameterList()
0 --- forward ParameterList()
```

</details>
</summary>

User can fetch correctly all parameters with `.parameters()`, but ParameterList/Dict are only present on replica 0.

**Comment by concretevitamin** [comment] 2020-08-02 19:35
This is a serious issue preventing us from upgrading to 1.6. Working around ParameterList (e.g., assign directly as attributes) is non-ideal as it breaks loading prior checkpoints. Adding glue code to load prior checkpoints would work, but it's something I don't expect from a stable release.

Also related to issue #42327.

**Comment by mrshenli** [comment] 2020-08-03 16:20
This seems to be another error instances caused by the changes we made in #33907? 

If the goal is to access parameters in replicated models, it will no longer work after #33907. I temporary work-around is to access them from `_former_parameters` as we did in DDP. 

@ngimel do we have a long-term solution for this? This error seems to emerge quite frequently.

**Comment by vfdev-5** [comment] 2020-08-03 16:31
@mrshenli in this PR : https://github.com/pytorch/pytorch/pull/40589 I tried to propose a fix for this issue with DP and ParameterList/Dict. Could you please take a look and give a feedback ? Thanks

**Comment by ngimel** [comment] 2020-08-03 16:55
@mrshenli not really. In case of ParameterList/ParameterDict #33907 exposed a deficiency in ParameterList/ParameterDict design that already made them incompatible with reparameterization, see e.g. the following example where ParameterList fails without any data_parallel replication:
```
import torch
import torch.nn as nn

class MyMod(torch.nn.Module):
    def __init__(self):
        super(MyMod, self).__init__()
        self.params = nn.ParameterList([nn.Parameter(torch.randn(10, 10)) for i in range(10)])

    def forward(self, x):
        print( self.params[0].size())
        # ParameterList can act as an iterable, or be indexed using ints
        for i, p in enumerate(self.params):
            x = self.params[i // 2].mm(x) + p.mm(x)
        return x

m = MyMod()
torch.nn.utils.weight_norm(m.params, name="0")
print("applied weight norm")
x = torch.randn(10, 10)
out=m(x)
```
Note that while one should not access `parameters()` in the forward pass (and this is the only thing that #33907 breaks), and accessing them by attribute name works even after #33907, accessing elements of ParameterList by index is the sole purpose of its existence, and the only way to access those attributes, and yet it does not work after a regular reparameterization. ParameterList/ParameterDict happened to work with data parallel replication before #33907 because it hid the fact that it was, in fact, reparameterization, but the proper fix is to make ParameterList/ParameterDict behave correctly in reparameterization scenarios.

**Comment by mrshenli** [comment] 2020-08-03 19:12
Hey @vfdev-5, based on @ngimel's comments above, the fix for `ParameterList` should be general one that works for both with and without `DataParallel`?

**Comment by vfdev-5** [comment] 2020-08-03 20:36
@mrshenli I see. As far as I understand `weight_norm` issue with `ParameterList` is that we can not simply add and fetch tensors from those structures. For example, a regular module after `weight_norm` of a parameter contains 1 tensor and 2 parameters
```python
import torch
import torch.nn as nn

m = nn.Linear(10, 10)
m2 = torch.nn.utils.weight_norm(m, name="weight")
print(type(m2.weight), type(m2.weight_g), type(m2.weight_v))
> <class 'torch.Tensor'> <class 'torch.nn.parameter.Parameter'> <class 'torch.nn.parameter.Parameter'>
```
but for `ParameterList` we lose original parameter and have 2 additional parameters:
```python
import torch
import torch.nn as nn

plist = nn.ParameterList([nn.Parameter(torch.randn(10, 10)) for i in range(2)])
plist2 = torch.nn.utils.weight_norm(plist, name="0")
print(["{}:{}".format(n, p.shape) for n, p in plist2.named_parameters()])
type(plist2[0])
> ['1:torch.Size([10, 10])', '0_g:torch.Size([10, 1])', '0_v:torch.Size([10, 10])']
> KeyError: '0'
```

So, naively, the fix for `ParameterList` is to be able to to do `setattr(parameter_list_module, name, tensor)`  and redirect 
`parameter_list_module[name]` to `getattr(parameter_list_module, name)` and fetch the tensor from the module instead of `parameter_list_module._parameters` ?

**Comment by jacobaustin123** [comment] 2020-09-08 23:30
Running into the same problem here. Seems like a fairly annoying issue. And the error messages are unhelpful. The data in the ParameterList/Dict just disappears at some point during the forward pass.

**Comment by XinYuan-believe** [comment] 2020-10-08 06:55
Yeah, this is a serious issue especially for meta learning which changes the network parameter online according to the parameter list.

**Comment by vaxenburg** [comment] 2020-10-10 00:12
I'm having the same problem. ParameterList appears empty in the forward pass. Perhaps the workaround could help, but it's far from ideal.

**Comment by ymthink** [comment] 2020-10-14 03:03
Encountered the same problem, which slows down the training time a lot.

**Comment by Devchonka** [comment] 2020-12-14 21:11
Could the fix for this please please be prioritized? Its been half a year..

**Comment by Devchonka** [comment] 2021-01-29 19:13
@albanD sorry to bother you, do you guys have a timeline for when you think a fix could be integrated? I'm relatively new to ML and torch and this is a big blocker for me (the above proposed workaround isn't an option in my case).

**Comment by JeanKossaifi** [comment] 2021-01-30 00:46
I also encountered the issue.

Snippet to reproduce:
```python
class Dummy(nn.Module):
    def __init__(self):
        super().__init__()
        self.params = nn.ParameterList()
        self.params.append(nn.Parameter(torch.Tensor(3, 4)))
        self.params.append(nn.Parameter(torch.Tensor(4, 5)))
        
    def forward(self, x):
        print(len(self.params), self.params)
        return x
```

Everything works as expected on a single GPU:
```python
>>> device = 'cuda:0'
>>> d = Dummy().to(device)
>>> x = torch.randn(32, 4, 4).to(device)
>>> r = d(x)
2 ParameterList(
    (0): Parameter containing: [torch.cuda.FloatTensor of size 3x4 (GPU 0)]
    (1): Parameter containing: [torch.cuda.FloatTensor of size 4x5 (GPU 0)]
)
```

However, when using DataParallel and more than one device, the `ParameterList` is empty:
```python
>>> device = 'cuda'
>>> d = nn.DataParallel(d).to(device)
>>> r = d(x)
00 ParameterList()
 ParameterList()
```

In addition, I get the warning: 
```
.../torch/nn/modules/container.py:435: UserWarning: Setting attributes on ParameterList is not supported.
  warnings.warn("Setting attributes on ParameterList is not supported.")
```

**Comment by albanD** [comment] 2021-02-01 15:57
@Devchonka  I am afraid there is no one working on a fix for this at the moment. The main reason is that this is due to an issue in the original design of ParameterList/Dict and it cannot be easily fixed without having many side effects on other usage of these wrappers.
The "simplest" workaround for now is not to use them unfortunately and save all your Parameters directly on the Module.
Or if you want to make your code cleaner, you can have a custom nn.Module that will hold them for you but you won't be able to access them as if it was a list.

**Comment by JeanKossaifi** [comment] 2021-02-08 13:11
@albanD what about https://github.com/pytorch/pytorch/pull/40589?

We are using ParameterList in our project and this bug breaks the library for several users who are using DataParallel. Do you recommend implementing our own ParameterList as an nn.Module until this is fixed?

**Comment by zanshuxun** [comment] 2021-03-06 06:21
same error

**Comment by Issam28** [comment] 2021-04-16 09:01
I'm getting the same error, any fixes?

**Comment by Bingo-W** [comment] 2021-05-08 05:12
I also encountered the issue. Are there any solutions or alternative ones?

**Comment by 13952522076** [comment] 2021-05-26 01:26
Same issue. I suppose this should not take too long to be solved.

**Comment by ngimel** [comment] 2021-07-14 18:55
One solution is to not use DataParallel and use DistributedDataParallel instead https://pytorch.org/docs/stable/generated/torch.nn.DataParallel.html?highlight=dataparallel#torch.nn.DataParallel. DataParallel is less efficient than DistributedDataParallel, and it is in maintenance mode, which means that new features are not added to it, and bug fixes are not prioritized.

**Comment by GuoleiSun** [comment] 2021-11-23 14:17
Same problem!

**Comment by patrickvonplaten** [comment] 2021-12-17 13:20
Same problem in HF transformers

**Comment by marsggbo** [comment] 2021-12-25 05:25
same problem...

**Comment by Hang14** [comment] 2022-01-24 17:51
same problem.

**Closed** 2022-02-10 16:14 UTC
Labels: high priority, module: nn, triaged, module: data parallel

**Comment by myname4423** [comment] 2023-03-12 09:31
still encoutered this problem, seems that the best idea is to not use DataParallel

**Comment by pminimd** [comment] 2023-07-25 03:06
still encoutered this problem, 2.0

**Comment by guillaumeguy** [comment] 2024-03-05 18:12
> still encoutered this problem, seems that the best idea is to not use DataParallel

You should upgrade your Torch version. For instance, on my version (2.0.0+cu118), the results are as expected:

![image](https://github.com/pytorch/pytorch/assets/5290678/774b2767-484e-4ad6-8e03-08f0c110af4c)

**Comment by zhangguangbei** [comment] 2024-10-16 11:35
你好
