### ISSUE TITLE
PyTorch+HIP AMD GPU?!

### ISSUE THREAD

**Issue by fire17** [pytorch/pytorch#10670] opened 2018-08-19 20:24 UTC
Hi there,
Currently I'm running a program that uses pytorch on a machine with Nvidia GPU with cuda
I'd like to move it to a computer that has AMD GPU

noticed that you have support for HIP, which should allow me to do this, as I understand
https://github.com/pytorch/pytorch/tree/382ff032224a14eecee476c564615204bcab4beb/tools/amd_build
https://github.com/ROCm-Developer-Tools/HIP

So how do I do this?
Should I just change something while I'm installing pytorch? or after installation?
Do I need to run some tool from HIP?
I've read it should be fairly simple, but I havn't found a way to do this
any suggestions?

Thank you very much :smile: 
Tami

cc @jeffdaily @sunway513

**Comment by Jorghi12** [comment] 2018-08-22 15:07
Hello,

Disclaimer: PyTorch AMD is still in development, so full test coverage isn't provided just yet.

PyTorch AMD runs on top of the Radeon Open Compute Stack (ROCm), which you can install from over here: https://rocm.github.io/install.html

Once installed, you'll need to run these two scripts.

*CUDA->HIP source to source transpiler:* python tools/amd_build/build_pytorch_amd.py
*Build PyTorch in ROCm mode:* USE_ROCM=1 python setup.py install

**Comment by Jorghi12** [comment] 2018-08-22 15:11
Hello,

**Disclaimer:** PyTorch AMD is still in development, so full test coverage isn't provided just yet.

PyTorch AMD runs on top of the Radeon Open Compute Stack (ROCm), which you can install from over here: https://rocm.github.io/install.html.

Once installed, then run the cuda->hip transpiler & build PyTorch.

- python tools/amd_build/build_pytorch_amd.py
- USE_ROCM=1 python setup.py install

For the list of AMD GPUs the ROCm stack supports, [see](https://github.com/RadeonOpenCompute/ROCm).

**Comment by davclark** [comment] 2018-09-10 20:00
I thought it was currently recommended to build from the AMD fork: https://github.com/ROCmSoftwarePlatform/pytorch

Have things progressed to where pytorch master is a better choice?

**Comment by ezyang** [comment] 2018-09-10 20:17
The AMD fork is regularly reintegrated back into PyTorch master. They shouldn't really be distinguishable.

**Comment by JulesGM** [comment] 2018-12-13 02:06
> Hello,
> 
> **Disclaimer:** PyTorch AMD is still in development, so full test coverage isn't provided just yet.
> 
> PyTorch AMD runs on top of the Radeon Open Compute Stack (ROCm), which you can install from over here: https://rocm.github.io/install.html.
> 
> Once installed, then run the cuda->hip transpiler & build PyTorch.
> 
> * python tools/amd_build/build_pytorch_amd.py
> * USE_ROCM=1 python setup.py install
> 
> For the list of AMD GPUs the ROCm stack supports, [see](https://github.com/RadeonOpenCompute/ROCm).

Why doesn't the installer do this automatically when detecting an AMD GPU?

**Comment by tannisroot** [comment] 2020-11-03 14:38
It has been 2 years, is the ROCM support still too incomplete to enable it by default upstream?

**Comment by JulesGM** [comment] 2020-11-03 17:32
It's crazy to me that AMD is not paying someone to get PyTorch to feature
parity between AMD and NVidia, including ease of installation

**Comment by jeffdaily** [comment] 2020-11-04 17:20
> One big blocker to enabling it by default is that HIP builds of PyTorch are mutually exclusive with CUDA builds, as they take over the "cuda" name to mean "hip". So we'd have to fix that first, but no one has been motivated enough to do this fairly large change.

We ROCm developers are certainly motivated, but there are concerns both technical and otherwise.  On the technical side, yes, "hip" takes over the name "cuda".  The hip and cuda backends are not mutually exclusive.  Even if they were, we'd run into usability concerns if we forced users to update all of their models to use "rocm" or "hip" as the device name instead of "cuda", and "cuda" having come first, this is frankly an unrealistic request.  This is a longer term discussion between the upstream PyTorch and ROCm PyTorch teams and we have not yet reached any actionable decision how to proceed.

> It's crazy to me that AMD is not paying someone to get PyTorch to feature parity between AMD and NVidia, including ease of installation

AMD does indeed have more than just me trying to get PyTorch to feature parity.  No doubt we're swimming upstream, but we're gaining, and if unit tests are any indication we have significant parity.

Concerning ease of installation, we now have nightly wheel files available as of ROCm 3.7.

- https://download.pytorch.org/whl/nightly/rocm3.7/torch_nightly.html
- https://download.pytorch.org/whl/nightly/rocm3.8/torch_nightly.html
- https://download.pytorch.org/whl/nightly/rocm3.9/torch_nightly.html

The only caveat being that you should use match the same ROCm version on your host that you do with the wheel; backward compatibility between ROCm releases is not yet feature complete.

We also have provided, for some time now, ROCm PyTorch docker images.
https://hub.docker.com/repository/docker/rocm/pytorch/tags?page=1

**Comment by JulesGM** [comment] 2020-11-04 20:03
Does calling `.cuda()` just work with the HIP/ROCm version, or would one have to change code to get the HIP/ROCm backend?

**Comment by jeffdaily** [comment] 2020-11-04 20:27
Yes, calling `.cuda()` just works the same way when you build PyTorch for ROCm to transfer tensors to the AMD GPU.  No code or model changes needed.  We recognize it is a bit counterintuitive, but it makes it a lot easier to "port" your pytorch code to use ROCm since there really aren't any code changes at all.

**Comment by JulesGM** [comment] 2020-11-12 21:57
I see, so the problem is the `.device("cuda")` calls?

**Comment by jeffdaily** [comment] 2020-11-13 00:12
Today, using `.device("cuda")` will also work for ROCm PyTorch because we fully masquerade as CUDA when you build for ROCm.

**Comment by Symbadian** [comment] 2022-08-16 09:25
Hi @BramVanroy and good day to you,

I am having a challenge where I am trying to use my M1 GPU for training via python3 train.py etc..

I have been trying to implement this for some time now by googling but this seems a little more challenging than I expected it to be.

I discovered the MPS component but that based on my research is used when deploying inference or detect.py. I can be wrong based on my limited experience. Can you guide me as to how to install the M1 GPU Silicon Chip on the new Macbook Pro for YOLOV5 Training, Please?

This training procedure is extremely painful on my old mac so I bought a newer model to handle the processing and I'm not sure how this works. Thanx loads for the YOLOV5 approach and your efforts. This is working on my old mac but that has been training since last Friday morning 3am and today is Tuesday, 16th Aug 2021 and it's now gotten to 8 epochs out of 30??!!!?!??!

Please help me initiate this faster with the M1 GPU or MPS not sure how it goes nevertheless my googling.

Thanx loads for anyone responding to my limitation, I am grateful just to learn

**Comment by shaw586** [comment] 2023-03-03 22:42
I am trying to use pytorch with rocm5.4. I installed pytorch using
`pip3 install --pre torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/nightly/rocm5.4/`

when I try torch.cuda.is_available(), it return False,
![image](https://user-images.githubusercontent.com/122632692/222845266-e9003c67-2e86-4e85-8886-245f5945c33d.png)

what am I missing?

**Comment by jeffdaily** [comment] 2023-03-06 16:34
@shaw586 not enough information.  Do you have ROCm kernel driver installed?  Which AMD GPU are you trying to use?

**Comment by shaw586** [comment] 2023-03-06 17:45
Yes, I do have ROCm kernel driver installed. I am able to run rocblas.

Here is rocm libs and version
![image](https://user-images.githubusercontent.com/122632692/223189163-21562c09-fd2a-4f5d-a627-92a99165d470.png)

Here is kernel driver info
![image](https://user-images.githubusercontent.com/122632692/223189295-21dc722c-b63c-4789-b6e0-9a56cb5d3419.png)

I am using MI250X (gfx90a architecture).

**Comment by hongxiayang** [comment] 2023-08-16 16:35
we have support now. close this issue

**Closed by hongxiayang** 2023-08-16 16:35 UTC
Labels: module: rocm, triaged
