### ISSUE TITLE
CUPTI error `CUPTI_ERROR_MULTIPLE_SUBSCRIBERS_NOT_SUPPORTED` when monitoring pytorch nightly with an external profiler

### ISSUE THREAD

**Issue by Jokeren** [pytorch/pytorch#117935] opened 2024-01-20 23:50 UTC
### 🐛 Describe the bug

There seems to be some problems with pytorch *nightly* and cupti. 
We tested using the official `cupti_trace_injection` example and a one-line pytorch code:
```Python
# test.py
import torch
import tempfile

def test_single():
    a = torch.ones((2, 2), device="cuda")
```
```bash
export CUDA_INJECTION64_PATH=<path/to/sample>/libcupti_trace_injection.so
pytest -vs ./test.py
```
We were not able to inject cupti callbacks or enable any activities. But the same cupti code and test code work well with pytorch *stable*.
CUPTI reported this error:
```
CUPTI_ERROR_MULTIPLE_SUBSCRIBERS_NOT_SUPPORTED
```
I wonder if somehow kineto accidentally subscribed cupti callbacks? Or there are some cuda context issues? Haven't investigated very deep yet.

### Versions

PyTorch
```
pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu121
```
CUPTI
```
/usr/local/cuda-12.3/extras/CUPTI/samples/cupti_trace_injection
```

cc @robieta @chaekit @aaronenyeshi @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by malfet** [comment] 2024-01-22 03:50
@Jokeren what nightly version are you on? I.e. it was indeed the case (for almost a month) until https://github.com/pytorch/pytorch/pull/116201 was landed

**Comment by Jokeren** [comment] 2024-01-22 05:06
![image](https://github.com/pytorch/pytorch/assets/2306281/a3eb9af1-9d00-462e-86e1-1d98c3dd5114)

@malfet Thanks for taking a look!

It doesn't conflict with every cupti tools I wrote, but it indeed errored out with the official `cupti_trace_injection` example shipped with cuda 12.3.

**Comment by Jokeren** [comment] 2024-01-22 05:11
Actually I found it's fixed now on torch nightly! I forgot to reload my environment. 
Sorry for bothering. Please feel free to close the issue.

**Closed** 2024-01-22 05:59 UTC
Labels: module: regression, oncall: profiler

**Comment by savitamittal1** [comment] 2024-06-04 05:32
I am running into same CUPTI error of 'CUPTI_ERROR_MULTIPLE_SUBSCRIBERS_NOT_SUPPORTED'. Already tried different version of pytorch and nothing seems to help. @Jokeren, can you please suggest which build of pytorch fixed your issue and do you have detail on the root cause?

Registering daemon config loader
WARNING:2024-06-04 04:03:49 109:109 init.cpp:155] function cbapi->getCuptiStatus() failed with error CUPTI_ERROR_MULTIPLE_SUBSCRIBERS_NOT_SUPPORTED (39)
WARNING:2024-06-04 04:03:49 109:109 init.cpp:156] CUPTI initialization failed - CUDA profiler activities will be missing
