### ISSUE TITLE
Memory leak in C++ when running module in separate thread

### ISSUE THREAD

**Issue by MikhailPxl** [pytorch/pytorch#24237] opened 2019-08-13 10:47 UTC
## 🐛 Bug

When calling the forward function of a Module, some memory is allocated that is not de-allocated at the end of the thread. 

## To Reproduce

Module scripted from Python as in tutoriel:
```
import torchvision
import torch

model = torchvision.models.resnet18()
example = torch.rand(1,3,224,224)
my_torchscript_module = torch.jit.trace(model, example)
torch.jit.save(my_torchscript_module, "sciptedModule.pt")
```
Loaded and ran in C++ in separate thread:

```
#include "torch/script.h"
#include "torch/torch.h"


void runModel(at::Tensor, torch::jit::script::Module);

int main()
{
	torch::NoGradGuard no_guard;
	torch::jit::script::Module m_module = torch::jit::load("./sciptedModule.pt");
	m_module.eval();
	at::Tensor testTensor = torch::rand({ 1,3,224,224}, at::kFloat);
	testTensor = testTensor.div(testTensor.norm());
	for (int i = 0; i < 10000; i++) {
		std::thread newThread(&runModel, testTensor, m_module);
		newThread.join();
	}
}

void runModel(at::Tensor testTensor, torch::jit::script::Module m_module) {
	torch::NoGradGuard no_guard;
	at::Tensor out = m_module.forward({ testTensor }).toTensor().detach();
}

```
![MemoryIncrease](https://user-images.githubusercontent.com/31984573/62935760-3f065800-bdc8-11e9-9e59-f296b64240da.PNG)

## Expected behavior

Inference is done in separate thread with no increase in memory

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] numpydoc==0.8.0
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] _tflow_1100_select        0.0.3                       mkl  
[conda] _tflow_select             2.3.0                       mkl  
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] libmklml                  2019.0.3                      0  
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] mkl-service               1.1.2            py36hb782905_5  
[conda] mkl_fft                   1.0.10           py36h14836fe_0  
[conda] mkl_random                1.0.2            py36h343c172_0  
[conda] pytorch                   1.2.0               py3.6_cpu_1  [cpuonly]  pytorch
[conda] tensorflow-base           1.10.0          mkl_py36h81393da_0  
[conda] torchvision               0.4.0                  py36_cpu  [cpuonly]  pytorch

## Additional context

When running on main thread, the memory seems to be allocated once on first call and then re-used.
Python threading doesn't have this problem

**Comment by pietern** [comment] 2019-08-13 10:55
This is likely to be caused by some thread local state that isn't cleaned up.

Could you try running without MKL and see what happens?

**Comment by MikhailPxl** [comment] 2019-08-13 12:40
Hi @pietern , thanks for quick answer. Sure, do you mean in the python part when tracing the model? I don't think I use MKL in the C++ part, unless it's inside the torch lib.

**Comment by pietern** [comment] 2019-08-13 12:43
I mean on the C++ side. PyTorch compiled with MKL support will transparently use it, I think.

**Comment by MikhailPxl** [comment] 2019-08-13 13:13
I'm not sure how to check if it uses it or run without it. Could you walk me through or point to some documentation?
I only downloaded the latest stable version and link to it.

**Comment by MikhailPxl** [comment] 2019-08-22 08:45
I found a way to not use std::thread in my application, so this is not a problem for me anymore.

**Comment by pietern** [comment] 2019-08-26 12:06
While this still might be an issue by itself, I'll close the issue since you found a workaround.

**Closed by pietern** 2019-08-26 12:06 UTC
Labels: module: cpp, module: mkl, topic: memory usage, triaged

**Comment by Bsting** [comment] 2019-10-15 07:26
i am facing the similar problem
https://discuss.pytorch.org/t/heap-size-increase-constantly-when-inference-with-new-thread/57621/4

**Comment by tiberiusferreira** [comment] 2019-11-27 01:05
I'm facing the same problem using the [Rust bindings](https://github.com/LaurentMazare/tch-rs).
The thread local variables seem to not be cleaned after inference.

**Comment by jingxil** [comment] 2020-01-18 04:21
Hi @pietern, I am facing a similar problem. The memory usage is keeping going up when I do the inference in separate threads. And without the mkl lib, the memory usage is stable.  I tried to set the env variable MKL_DISABLE_FAST_MM=1. But it did not work out.

**Comment by Junan007** [comment] 2020-03-10 05:52
I am facing a similar problem.

**Comment by WilliamTambellini** [comment] 2021-09-20 23:18
Still the same issue with libtorch 1.7.

**Comment by ofaucoz** [comment] 2022-10-12 12:55
I'm having the exact same issue using libtorch called in a thread from unity.
This is a derived code from my problem:

## C++ script
```C++
torch::NoGradGuard no_grad;
at::Tensor tensor_image = torch::from_blob(...)
tensor_image.set_requires_grad(false);

vector<torch::jit::IValue> inputs;
inputs.push_back(tensor_image);
at::Tensor output;
output = model.forward(inputs).toTensor();
...
``` 
## (Unity) C# script calling the libtorch script
``` C#
void Update(){
    ...
    ThreadMl = new Thread(Action);
    ThreadMl.Start();
}

private void Action(){ // launched in a thread
    ...
    ScriptML(...); // Memory being leaked
    ...
}
```

libtorch version : (CPU - Windows) 1.11

**Comment by RVirmoors** [comment] 2023-02-05 17:47
this is very much still an active issue and should probably be reopened

**Comment by joshhansen** [comment] 2023-05-19 00:04
I seem to be getting this - coming from Rust like @tiberiusferreira. In a multithreaded async environment, inference appears to leak memory.

**Comment by ofaucoz** [comment] 2023-09-06 11:55
Any news to fix this issue ?

**Comment by ezorita** [comment] 2024-02-01 17:37
Also having the same issue running a model for inference in a Thread  class.

**Comment by thecargocultnz** [comment] 2025-02-19 01:40
Why is this closed???
This is still an issue in Feb 2025, and renders torch non-viable in a commercially released product.
Any serious inference is gonna cause this massive memory leak.

To be clear: we cannot use torch any longer. I don't know how anyone does? Is it just for academics?

**Comment by thecargocultnz** [comment] 2025-02-19 01:43
@pietern can we get it reopened please?
