### ISSUE TITLE
Creating CPU DeviceMesh fails without GPUs

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#117746] opened 2024-01-18 13:45 UTC
### 🐛 Describe the bug

Creating a `DeviceMesh` on a node/nodes without GPUs fails as it tries to create the NCCL backend:

Reduced example:
```
import os
import torch
from torch.distributed._tensor.device_mesh import DeviceMesh
os.environ['RANK'] = '0'; os.environ['WORLD_SIZE'] = '1'; os.environ['MASTER_ADDR'] = 'localhost'; os.environ['MASTER_PORT'] = '25364'
DeviceMesh("cpu", torch.arange(1))
```

Error:
```
  File "/dev/shm/venv/lib/python3.10/site-packages/torch/distributed/_tensor/device_mesh.py", line 147, in __init__
    self._get_or_create_default_group()
  File "/dev/shm/venv/lib/python3.10/site-packages/torch/distributed/_tensor/device_mesh.py", line 154, in _get_or_create_default_group
    init_process_group()
  File "/dev/shm/venv/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 74, in wrapper
    func_return = func(*args, **kwargs)
  File "/dev/shm/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1148, in init_process_group
    default_pg, _ = _new_process_group_helper(
  File "/dev/shm/venv/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 1279, in _new_process_group_helper
    backend_class = ProcessGroupNCCL(backend_prefix_store, group_rank, group_size, pg_options)
RuntimeError: ProcessGroupNCCL is only supported with GPUs, no GPUs found!
```

Reason seems to be the choice of default backends at https://github.com/pytorch/pytorch/blob/main/torch/distributed/distributed_c10d.py#L287-L288 where only `is_nccl_available` gets checked but not if there are any GPUs

### Versions

PyTorch 2.1.2

**Comment by awgu** [comment] 2024-01-18 14:50
This looks like a duplicate of https://github.com/pytorch/pytorch/issues/114629. If so, shall we close this one and keep the original open?

**Comment by Flamefire** [comment] 2024-01-18 15:01
Yes looks like the same underlying cause just different usage. This here has the simpler reproducer though.

BTW: I have a fix or at least workaround:
```
--- a/torch/distributed/distributed_c10d.py
+++ b/torch/distributed/distributed_c10d.py
@@ -271,9 +271,11 @@ class BackendConfig:
         if backend == Backend.UNDEFINED:
             # default config when backend is not specified
             # supported since PyTorch 2.0
-            for device in Backend.default_device_backend_map:
-                if is_backend_available(Backend.default_device_backend_map[device]):
-                    self.device_backend_map[device] = Backend.default_device_backend_map[device]
+            for device, default_backend in Backend.default_device_backend_map.items():
+                if is_backend_available(default_backend):
+                    if default_backend == Backend.NCCL and not torch.cuda.is_available():
+                        continue
+                    self.device_backend_map[device] = default_backend
         elif backend.lower() in Backend.backend_list:
             # Cases for when backend is a single string (without device types)
             # e.g. "nccl", "gloo", "ucc", "mpi"

```

**Comment by wz337** [comment] 2024-01-26 18:39
@kwen2501 @H-Huang

**Comment by kwen2501** [comment] 2024-01-27 00:08
@Flamefire @wz337 Thanks for catching the issue and the fix. Do you mind porting the fix to a PR, thanks!

**Closed** 2024-02-05 23:55 UTC
Labels: triaged, module: DeviceMesh
