### ISSUE TITLE
symbolic trace argument unpack

### ISSUE THREAD

**Issue by supriyar** [pytorch/pytorch#44665] opened 2020-09-14 21:56 UTC
Currently there doesn't seem to be a way to skip tracing of certain functions. Encountered this error when trying to symbolically trace open source BERT model to quantize it.

Original error is from 
https://github.com/huggingface/transformers/blob/master/src/transformers/modeling_bert.py#L238

Unit test to repro -
```
import torch
from torch.fx import symbolic_trace
import torch.nn as nn

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def transpose_inp(self, x):
        new_shape = x.size()[:-1] + (5, 5)
        x = x.view(*new_shape)
        return x.permute(0, 2, 1, 3)

    def forward(self, x):
        tmp = self.transpose_inp(x)
        return tmp

m = symbolic_trace(M())
```

Throws the following error
```
m = symbolic_trace(M())
  File "/home/supriyar/local/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/fx/symbolic_trace.py", line 219, in symbolic_trace
    graph.output(delegate.create_arg(fn(*args)))
  File "scripts/test_fx.py", line 49, in forward
    tmp = self.transpose_inp(x)
  File "scripts/test_fx.py", line 44, in transpose_inp
    x = x.view(*new_shape)
  File "/home/supriyar/local/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/fx/proxy.py", line 62, in __iter__
    self._no_arg_unpack()
  File "/home/supriyar/local/miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/fx/proxy.py", line 70, in _no_arg_unpack
    raise TraceError('Proxy object cannot be unpacked as function argument')
torch.fx.proxy.TraceError: Proxy object cannot be unpacked as function argument
```

cc @gmagogsfm @jerryzh168, @vkuzo

**Comment by jerryzh168** [comment] 2020-09-15 16:32
@SplitInfinity are fx issues triaged by JIT? or should we just cc james?

**Comment by jerryzh168** [comment] 2020-09-15 18:36
btw, I think it would be better to workaround this with an option to support skipping symbolic trace for certain methods. This will help several other similar errors as well.
cc @jamesr66a

**Comment by jamesr66a** [comment] 2020-09-16 17:58
Duplicate of https://github.com/pytorch/pytorch/issues/43679

**Closed by jamesr66a** 2020-09-16 17:58 UTC
Labels: fx
