### ISSUE TITLE
Non-deterministic parallel scatter reduction algorithms for scatter operations for CPU (sum, subtract, divide, multiply).

### ISSUE THREAD

**Issue by v0dro** [pytorch/pytorch#33389] opened 2020-02-16 02:15 UTC
## 🚀 Feature

Implementing non-deterministic parallel scatter algorithms for various reduction operations. This issue is a follow-up of https://github.com/pytorch/pytorch/issues/33065 and a prelude to https://github.com/pytorch/pytorch/issues/22378.

## Motivation

Read comment https://github.com/pytorch/pytorch/issues/22378#issuecomment-586081656 for more details.

## Pitch

A scatter reduction API for addition, subtraction, multiplication and division that will have the following form:
``` python
input = torch.zeros(4, 4, device=device)
src = torch.ones(2, 2, device=device)
index = torch.tensor([[1], [2]], device=device, dtype=torch.long)
input.scatter_(0, index, src, reduce="sum")
```

**Comment by v0dro** [comment] 2020-02-16 04:13
@gchanan @ngimel can you please comment on the expected behaviour for boolean operands when doing something other than `sum`? This is the test for the current `scatter_add_` using boolean operands. https://github.com/pytorch/pytorch/blob/master/test/test_torch.py#L10736

**Comment by rgommers** [comment] 2020-02-17 02:52
Boolean operations aren't implemented for regular tensors it seems:
```
In [13]: t1                                                                                    
Out[13]: tensor([False, False, False, False], dtype=torch.bool)

In [14]: t2                                                                                    
Out[14]: tensor([False,  True, False,  True], dtype=torch.bool)

In [15]: t1 - t2                                                                               
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-15-df8792ca3294> in <module>
----> 1 t1 - t2

RuntimeError: "add_cpu" not implemented for 'Bool'

In [19]: t3 = torch.BoolTensor([True, False])                                                  

In [20]: t3                                                                                    
Out[20]: tensor([ True, False], dtype=torch.bool)

In [21]: t3 + t3                                                                               
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-21-904678a7d691> in <module>
----> 1 t3 + t3

RuntimeError: add not supported on CPUType for Bool
```
Only logical operators (`&`, `|`, etc.) are supporteed. So it probably doesn't make sense to make any scatter functions support the regular operators for bools.

Note that the test you are referencing does `bool + int64`, not `bool + bool`. So what will happen is that the `bool` array is cast to `int64` first, and then the expected behavior is clear (also for the other operators).

**Comment by VitalyFedyunin** [comment] 2020-02-18 17:07
Triage review because need signoff from @gchanan @ngimel @rgommers

**Comment by VitalyFedyunin** [comment] 2020-02-18 17:07
Same, but CUDA https://github.com/pytorch/pytorch/issues/33394

**Comment by rgommers** [comment] 2020-02-19 05:34
> Triage review because need signoff from @gchanan @ngimel @rgommers

I think this is simply one of the steps of https://github.com/pytorch/pytorch/issues/22378#issuecomment-586081656, which is the high-prio issue. I suggest to review that plan, and not triage the individual issues that are broken off from that master issue. Nor should this one be made high-prio, that just confuses the count.

**Comment by v0dro** [comment] 2020-02-23 01:59
The current implementation is trivially parallelizable since the operations for a single output location are always confined to a single thread.

I just found that the threading in the current implementation happens over the dimension being reduced anyway, so the memory locations that each thread writes to is unique even if there are non-unique indices along the dimension being reduced. Therefore now I can conclude that we did not need the atomic operations in the first place and the parallelization can happen in a thread-safe manner in the current implementation too.

The current way a scatter addition performs multi-threading can be summarized in this diagram:
![IMG_1798](https://user-images.githubusercontent.com/2629909/75102215-35896280-562b-11ea-88a5-1bda80b32fea.JPG)

In this case the order of reduction is always preserved since one loop always runs in a single thread and we don't need to implement special deterministic operations for CPU anymore. 

However if the parallelization is done over the non-reduction dimension we will need the deterministic operations implementation since the reduction can happen in different orders in that case. The GPU implementation implements parallelism differently and hence will need a deterministic mode anyway.

Therefore, we're good on CPU for now.

**Comment by rgommers** [comment] 2020-06-30 20:10
@v0dro this can be closed right, now that gh-36447 is merged?

**Comment by ngimel** [comment] 2020-06-30 21:41
We still need documentation before closing the issue.

**Comment by rgommers** [comment] 2020-07-09 10:06
Documentation was added in gh-40962, so now it's really done - closing. Thanks @v0dro and @ngimel

**Closed by rgommers** 2020-07-09 10:06 UTC
Labels: enhancement, module: operators, triaged
