### ISSUE TITLE
onnx missing operator bug

### ISSUE THREAD

**Issue by bladesaber** [pytorch/pytorch#46515] opened 2020-10-17 07:30 UTC
## 🐛 Bug

RuntimeError: Exporting the operator triu to ONNX opset version 12 is not supported. Please open a bug to request ONNX export support for the missing operator.

## To Reproduce

1. highly depended on my code, so difficult to show reproduce

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.6):
 - OS (e.g., Linux ubuntu.18.0.4):
 - How you installed PyTorch (pip):
 - Build command you used (if compiling from source):
 - Python version:3.7.8
 - CUDA/cuDNN version: cuda-10.1 cudnn-7
 - GPU models and configuration: GTX1050
 - Any other relevant information:

**Comment by vadimkantorov** [comment] 2020-10-18 19:40
It seems that this issue is a duplicate of https://github.com/pytorch/pytorch/issues/32968

**Closed** 2020-10-20 00:48 UTC
