### ISSUE TITLE
Support LBFGS closures in torchscript

### ISSUE THREAD

**Issue by fdan** [pytorch/pytorch#80290] opened 2022-06-26 00:35 UTC
### 🚀 The feature, motivation and pitch

From my reading of the LBFGS documentation, it doesn't seem this optimiser can be used in torchscript, as it's step method requires a closure parameter.  If I try to pass one in, torch jit complains saying: _UnsupportedNodeError: function definitions aren't supported_.  From this I gather this optimiser cannot be used with torchscript, although I'm yet to find confirmation of this in the documentation.  I was hoping to get clarification on this, whether there is some solution that I am missing.

PyTorch 1.10.2

https://pytorch.org/docs/stable/_modules/torch/optim/lbfgs.html#LBFGS.step

### Alternatives

Using a different optimiser, however LBFGS works best for my use case.

### Additional context

```import torch

class Test(torch.nn.Module):
    def __init__(self):
        super(Test, self).__init__()      
        
    def forward(self, 
                input_: torch.Tensor, 
                target: torch.Tensor) -> torch.Tensor:
        
        optim = torch.optim.LBFGS(tensor)
        max_iter = 50
        n_iter = 0
        
        def closure():
            optim.zero_grad()
            loss = input_ - target
            loss.backward()
            n_iter += 1
            return loss  
        
        while n_iter <= max_iter:
            optim.step(closure)
        
        return tensor
    
    
test = torch.jit.script(Test())
test.save('test.pt')```


```UnsupportedNodeError: function definitions aren't supported:
  File "/tmp/ipykernel_4162/3211224755.py", line 15
        n_iter = 0
        
        def closure():
        ~~~ <--- HERE
            optim.zero_grad()
            loss = input_ - target
'Test.forward' is being compiled since it was called from 'Test.forward'
  File "/tmp/ipykernel_4162/3447201789.py", line 20
                target: torch.Tensor) -> torch.Tensor:
        
        optim = torch.optim.LBFGS(tensor)
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        max_iter = 50
        n_iter = 0```

**Comment by davidberard98** [comment] 2022-06-28 17:48
Duplicate of https://github.com/pytorch/pytorch/issues/80412

**Closed by davidberard98** 2022-06-28 17:48 UTC
Labels: oncall: jit
