### ISSUE TITLE
building with libtorch and MKL-DNN/DNNL

### ISSUE THREAD

**Issue by avaxman** [pytorch/pytorch#27744] opened 2019-10-11 14:38 UTC
I am trying to cmake a C++ project as follows: cmake .. -G Xcode -DCMAKE_PREFIX_PATH=/pathto/libtorch 

where libtorch was downloaded from here: https://download.pytorch.org/libtorch/nighlty/cpu/libtorch-macos-1.3.0.zip

however, I get the following error: 
mported target "torch" includes non-existent path

    "MKL_INCLUDE_DIR-NOTFOUND"

I have installed mkl-dnnl through homebrew, and I suspect the problem is that libtorch has not updated the name to dnnl? because dnnl.h exists in my /usr/local/include.

**Comment by gtamba** [comment] 2019-10-11 15:12
#14727 May be related although this has a different error message, maybe try dropping in the `*.dylib` files int `lib/` of your libtorch folder

**Comment by gchanan** [comment] 2019-10-13 02:28
@gtamba I'm going to close this as a duplicate of https://github.com/pytorch/pytorch/issues/14727 -- as @soumith is fixing these, as noted there.

**Closed by gchanan** 2019-10-13 02:28 UTC
