### ISSUE TITLE
intrin.h: No such file or directory  #include <intrin.h>

### ISSUE THREAD

**Issue by qiulesun** [pytorch/pytorch#8831] opened 2018-06-24 01:20 UTC
Editorial note: There were multiple reports in this issue; the intrin.h problem is reported further below.

----

## Issue description

running install
running build_deps
+ USE_CUDA=0
+ USE_ROCM=0
+ USE_NNPACK=0

......

-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "7.0") 
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;6.1+PTX
-- Set NVCC_GENCODE for building NCCL: -gencode=arch=compute_30,code=sm_30 -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_61,code=compute_61
-- Configuring done
-- Generating done
-- Build files have been written to: /media/hh/pytorch_dir/pytorch/third_party/build/nccl
+ make install
Scanning dependencies of target nccl
[100%] Generating lib/libnccl.so
Grabbing  src/nccl.h                          > /media/hh/pytorch_dir/pytorch/third_party/build/nccl/include/nccl.h
Compiling src/libwrap.cu                      > /media/hh/pytorch_dir/pytorch/third_party/build/nccl/obj/libwrap.o
nvcc fatal   : redefinition of keyword 'code' 
make[3]: *** [/media/hh/pytorch_dir/pytorch/third_party/build/nccl/obj/libwrap.o] Error 1
make[3]: INTERNAL: Exiting with 9 jobserver tokens available; should be 8!
make[2]: *** [lib/libnccl.so] Error 2
make[1]: *** [CMakeFiles/nccl.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'

## Code example

python setup.py install

## System Info

- PyTorch or Caffe2:PyTorch
- How you installed PyTorch (conda, pip, source): source
- Build command you used (if compiling from source):python setup.py install
- OS:ubuntu14.04
- PyTorch version:master
- Python version:3.6
- CUDA/cuDNN version:8.0
- GPU models and configuration:GTX1080Ti
- GCC version (if compiling from source):4.9.2
- CMake version:3.7.2
- Versions of any other relevant libraries:

**Comment by zasdfgbnm** [comment] 2018-06-24 04:59
I have the same problem on one of my machine.
I this this is a duplicate of https://github.com/pytorch/pytorch/issues/8729

**Comment by TensorDL** [comment] 2018-06-24 07:09
I got it. However, after that, the error is occured. How do I handle it?

3 errors detected in the compilation of "/tmp/tmpxft_00004442_00000000-7_THCTensorMath.cpp1.ii".
CMake Error at caffe2_gpu_generated_THCTensorMath.cu.o.Release.cmake:279 (message):
  Error generating file
  /media/hh/pytorch_dir/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/./caffe2_gpu_generated_THCTensorMath.cu.o

make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/__/aten/src/THC/caffe2_gpu_generated_THCTensorMath.cu.o] Error 1
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
make: *** [all] Error 2
Failed to run 'bash tools/build_pytorch_libs.sh --use-cuda --use-nnpack --use-mkldnn nccl caffe2 nanopb libshm gloo THD c10d'

**Comment by SsnL** [comment] 2018-06-24 19:42
@TensorDL Could you try the patch in #8834 and see if it builds for you? It should fix the `redefinition of 'code'` problem, but not sure about `make[3]: INTERNAL: Exiting with 9 jobserver tokens available; should be 8!`. That might be a make bug.

**Comment by SsnL** [comment] 2018-06-25 15:08
@TensorDL The patch was merged into master. Can you try again?

**Comment by bhavesh2109** [comment] 2018-07-17 08:29
Hey I had the same error and this fixed it for me (https://discuss.pytorch.org/t/solved-source-compile-error/9490/2). It might help you all as well @TensorDL .

**Comment by TensorDL** [comment] 2018-07-20 03:02
running install
running build_deps
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "7.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl
Scanning dependencies of target nccl
[100%] Generating lib/libnccl.so
Grabbing  src/nccl.h                          > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/include/nccl.h
Compiling src/libwrap.cu                      > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/obj/libwrap.o
Compiling src/core.cu                         > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/obj/core.o
Compiling src/all_gather.cu                   > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/obj/all_gather.o
Compiling src/all_reduce.cu                   > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/obj/all_reduce.o
Compiling src/broadcast.cu                    > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/obj/broadcast.o
Compiling src/reduce.cu                       > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/obj/reduce.o
Compiling src/reduce_scatter.cu               > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/obj/reduce_scatter.o
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
Linking   libnccl.so.1.3.5                    > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/lib/libnccl.so.1.3.5
Archiving libnccl_static.a                    > /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/nccl/lib/libnccl_static.a
[100%] Built target nccl
Install the project...
-- Install configuration: "Release"
-- Installing: /media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/tmp_install/include/nccl.h
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found CUDA: /usr/local/cuda-8.0 (found suitable version "8.0", minimum required is "5.5") 
-- Automatic GPU detection failed. Building for common architectures.
-- Autodetected CUDA architecture(s): 3.0;3.5;5.0;5.2;6.0;6.1;6.1+PTX
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- Removing -DNDEBUG from compile flags
-- Found OpenMP_C: -fopenmp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
-- Compiling with OpenMP support
-- Checking prototype magma_get_sgeqrf_nb for MAGMA_V2 - True
-- Compiling with MAGMA support
-- MAGMA INCLUDE DIRECTORIES: /usr/local/anaconda3/include
-- MAGMA LIBRARIES: /usr/local/anaconda3/lib/libmagma.a
-- MAGMA V2 check: 1
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Performing Test HAVE_GCC_GET_CPUID
-- Performing Test HAVE_GCC_GET_CPUID - Success
-- Performing Test NO_GCC_EBX_FPIC_BUG
-- Performing Test NO_GCC_EBX_FPIC_BUG - Success
-- Performing Test C_HAS_SSE1_1
-- Performing Test C_HAS_SSE1_1 - Failed
-- Performing Test C_HAS_SSE1_2
-- Performing Test C_HAS_SSE1_2 - Failed
-- Performing Test C_HAS_SSE1_3
-- Performing Test C_HAS_SSE1_3 - Failed
-- Performing Test C_HAS_SSE2_1
-- Performing Test C_HAS_SSE2_1 - Failed
-- Performing Test C_HAS_SSE2_2
-- Performing Test C_HAS_SSE2_2 - Failed
-- Performing Test C_HAS_SSE2_3
-- Performing Test C_HAS_SSE2_3 - Failed
-- Performing Test C_HAS_SSE3_1
-- Performing Test C_HAS_SSE3_1 - Failed
-- Performing Test C_HAS_SSE3_2
-- Performing Test C_HAS_SSE3_2 - Failed
-- Performing Test C_HAS_SSE3_3
-- Performing Test C_HAS_SSE3_3 - Failed
-- Performing Test C_HAS_SSE4_1_1
-- Performing Test C_HAS_SSE4_1_1 - Failed
-- Performing Test C_HAS_SSE4_1_2
-- Performing Test C_HAS_SSE4_1_2 - Failed
-- Performing Test C_HAS_SSE4_1_3
-- Performing Test C_HAS_SSE4_1_3 - Failed
-- Performing Test C_HAS_SSE4_1_4
-- Performing Test C_HAS_SSE4_1_4 - Failed
-- Performing Test C_HAS_SSE4_2_1
-- Performing Test C_HAS_SSE4_2_1 - Failed
-- Performing Test C_HAS_SSE4_2_2
-- Performing Test C_HAS_SSE4_2_2 - Failed
-- Performing Test C_HAS_SSE4_2_3
-- Performing Test C_HAS_SSE4_2_3 - Failed
-- Performing Test C_HAS_SSE4_2_4
-- Performing Test C_HAS_SSE4_2_4 - Failed
-- Performing Test C_HAS_AVX_1
-- Performing Test C_HAS_AVX_1 - Failed
-- Performing Test C_HAS_AVX_2
-- Performing Test C_HAS_AVX_2 - Failed
-- Performing Test C_HAS_AVX_3
-- Performing Test C_HAS_AVX_3 - Failed
-- Performing Test C_HAS_AVX2_1
-- Performing Test C_HAS_AVX2_1 - Failed
-- Performing Test C_HAS_AVX2_2
-- Performing Test C_HAS_AVX2_2 - Failed
-- Performing Test C_HAS_AVX2_3
-- Performing Test C_HAS_AVX2_3 - Failed
-- Performing Test CXX_HAS_SSE1_1
-- Performing Test CXX_HAS_SSE1_1 - Failed
-- Performing Test CXX_HAS_SSE1_2
-- Performing Test CXX_HAS_SSE1_2 - Failed
-- Performing Test CXX_HAS_SSE1_3
-- Performing Test CXX_HAS_SSE1_3 - Failed
-- Performing Test CXX_HAS_SSE2_1
-- Performing Test CXX_HAS_SSE2_1 - Failed
-- Performing Test CXX_HAS_SSE2_2
-- Performing Test CXX_HAS_SSE2_2 - Failed
-- Performing Test CXX_HAS_SSE2_3
-- Performing Test CXX_HAS_SSE2_3 - Failed
-- Performing Test CXX_HAS_SSE3_1
-- Performing Test CXX_HAS_SSE3_1 - Failed
-- Performing Test CXX_HAS_SSE3_2
-- Performing Test CXX_HAS_SSE3_2 - Failed
-- Performing Test CXX_HAS_SSE3_3
-- Performing Test CXX_HAS_SSE3_3 - Failed
-- Performing Test CXX_HAS_SSE4_1_1
-- Performing Test CXX_HAS_SSE4_1_1 - Failed
-- Performing Test CXX_HAS_SSE4_1_2
-- Performing Test CXX_HAS_SSE4_1_2 - Failed
-- Performing Test CXX_HAS_SSE4_1_3
-- Performing Test CXX_HAS_SSE4_1_3 - Failed
-- Performing Test CXX_HAS_SSE4_1_4
-- Performing Test CXX_HAS_SSE4_1_4 - Failed
-- Performing Test CXX_HAS_SSE4_2_1
-- Performing Test CXX_HAS_SSE4_2_1 - Failed
-- Performing Test CXX_HAS_SSE4_2_2
-- Performing Test CXX_HAS_SSE4_2_2 - Failed
-- Performing Test CXX_HAS_SSE4_2_3
-- Performing Test CXX_HAS_SSE4_2_3 - Failed
-- Performing Test CXX_HAS_SSE4_2_4
-- Performing Test CXX_HAS_SSE4_2_4 - Failed
-- Performing Test CXX_HAS_AVX_1
-- Performing Test CXX_HAS_AVX_1 - Failed
-- Performing Test CXX_HAS_AVX_2
-- Performing Test CXX_HAS_AVX_2 - Failed
-- Performing Test CXX_HAS_AVX_3
-- Performing Test CXX_HAS_AVX_3 - Failed
-- Performing Test CXX_HAS_AVX2_1
-- Performing Test CXX_HAS_AVX2_1 - Failed
-- Performing Test CXX_HAS_AVX2_2
-- Performing Test CXX_HAS_AVX2_2 - Failed
-- Performing Test CXX_HAS_AVX2_3
-- Performing Test CXX_HAS_AVX2_3 - Failed
-- Performing Test HAS_C11_ATOMICS
-- Performing Test HAS_C11_ATOMICS - Failed
-- Performing Test HAS_MSC_ATOMICS
-- Performing Test HAS_MSC_ATOMICS - Failed
-- Performing Test HAS_GCC_ATOMICS
-- Performing Test HAS_GCC_ATOMICS - Failed
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
CMake Error at CMakeLists.txt:309 (TARGET_LINK_LIBRARIES):
  Cannot specify link libraries for target "TH" which is not built by this
  project.


-- Configuring incomplete, errors occurred!
See also "/media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/aten/CMakeFiles/CMakeOutput.log".
See also "/media/cv-pc-00/SSD500G_860EVO2/pytorch_dir/pytorch/torch/lib/build/aten/CMakeFiles/CMakeError.log".

what should I do next?

**Comment by EmmaW8** [comment] 2019-04-15 09:04
@qiulesun 
Hi, have you solved your problem?
I got a similar one.

**Comment by colesbury** [comment] 2019-04-15 18:11
@EmmaW8 are you also on ubuntu14.04?

**Comment by marchss** [comment] 2019-05-15 11:52
I also got the same issue when compiling libtorch from source

**Comment by ezyang** [comment] 2019-05-15 19:55
@marchss Which error? There are multiple, different errors, reported throughout this issue.

**Comment by marchss** [comment] 2019-05-17 03:24
Thanks @ezyang 

The <intrin.h> error as listed below.

pytorch/CMakeFiles/CMakeTmp/src.c:2:22: fatal error: intrin.h: No such file or direct    ory
298    #include <intrin.h>
299                       ^
300 compilation terminated.
301 gmake[1]: *** [CMakeFiles/cmTC_222f8.dir/src.c.o] Error 1
302 gmake[1]: Leaving directory `/data1/charliexiao/pytorch/CMakeFiles/CMakeTmp'

**Comment by marchss** [comment] 2019-05-17 03:25
Thanks @ezyang

The <intrin.h> error as listed below.

pytorch/CMakeFiles/CMakeTmp/src.c:2:22: fatal error: intrin.h: No such file or direct ory
298 #include <intrin.h>
299 ^
300 compilation terminated.
301 gmake[1]: *** [CMakeFiles/cmTC_222f8.dir/src.c.o] Error 1
302 gmake[1]: Leaving directory `pytorch/CMakeFiles/CMakeTmp'

**Comment by colesbury** [comment] 2019-05-17 15:49
That doesn't seem like the actual error. `intrin.h` is specific to Windows. That part is **expected** to fail on Linux. It just means that `HAS_MSC_ATOMICS` will be 0.

https://github.com/pytorch/pytorch/blob/1136ad59f91138c886c8585de0bcb6f23667ce0e/cmake/Dependencies.cmake#L1247-L1258

**Comment by marchss** [comment] 2019-05-20 02:47
@colesbury That is right, thanks.

**Closed** 2023-02-01 01:38 UTC
Labels: module: build, triaged
