### ISSUE TITLE
[Feature Request] Deformable Convolution

### ISSUE THREAD

**Issue by novioleo** [pytorch/pytorch#2260] opened 2017-07-31 05:39 UTC
MSRA's deformable Convolution Net needed~
i found that it had been implement in pytorch at :https://github.com/oeway/pytorch-deform-conv
is there any possiblity add this module into core of pytorch?

**Comment by ruotianluo** [comment] 2017-08-01 23:00
Official code on mxnet (which includes c and cuda code; should be potentially faster): https://github.com/msracver/Deformable-ConvNets

**Comment by novioleo** [comment] 2017-08-02 01:48
@ruotianluo tks,i knew it.However i don't want to add another deeplearning framework into my project~so,i'd like to use the deformable-cnn in pytorch.

**Comment by ruotianluo** [comment] 2017-08-02 01:49
What I mean is one can actually port the c and cuda code into pytorch.

**Comment by novioleo** [comment] 2017-08-02 01:52
thks,i'll take a look.

**Comment by 1zb** [comment] 2017-08-04 13:28
Here is a pytorch deformable convolution module (ConvOffset2d): https://github.com/1zb/deformable-convolution-pytorch ported from the official implementation.

**Comment by novioleo** [comment] 2017-08-05 08:52
@1zb tks for your work~i'll try it soon.

**Comment by isalirezag** [comment] 2019-02-10 16:43
Does pytorch have any plan to add deformable convolution to its library? so researchers who use pytorch can compete with state of the art methods that use deformable convolution as their baseline?

**Comment by HamsterHuey** [comment] 2019-08-22 15:31
Can this issue be re-opened as a Feature Request in the issue tracker? It would be nice to have a reference implementation in Pytorch that installs correctly and portably rather than relying on 3rd party libs that each have different build requirements. Deformable convs definitely seem to provide a decent boost in performance in various computer vision tasks and it would be nice to be able to utilize them easily when training models in Pytorch.

**Comment by ahkarami** [comment] 2019-09-02 20:37
I think this issue must be re-open.

**Comment by novioleo** [comment] 2019-09-03 02:51
fine


 
---Original---

**Comment by pbelevich** [comment] 2019-09-04 00:47
maybe a duplicate of #15864 ?

**Comment by novioleo** [comment] 2019-09-04 01:30
@pbelevich this issue proposed in 2017

**Comment by veritas9872** [comment] 2019-09-04 03:10
However, it was re-opened only yesterday...

**Comment by veritas9872** [comment] 2019-09-04 06:05
I would like to mention again, however, that the code is already available in https://github.com/open-mmlab/mmdetection/tree/master/mmdet/ops/dcn and that all we need do is copy-paste it and maybe add some backward-compatibility. 
I would be most grateful if someone with the proper authorization would take up this task.

**Comment by breznak** [comment] 2020-01-24 11:06
pytorch vision gained DCN functionality recently! :clap: 
https://github.com/pytorch/vision/pull/1586

**Comment by mruberry** [comment] 2020-05-09 06:05
It appears this. issue has been addressed! Please reopen if it hasn't.

**Closed by mruberry** 2020-05-09 06:05 UTC
Labels: feature, module: nn, topic: convolution, triaged
