### ISSUE TITLE
fully_shard with a gloo group segfault

### ISSUE THREAD

**Issue by ppwwyyxx** [pytorch/pytorch#132471] opened 2024-08-02 02:32 UTC
### 🐛 Describe the bug

```python
from torch.distributed._composable.fsdp import fully_shard
import torch.distributed as dist
from torch import nn

if __name__ == '__main__':
    dist.init_process_group(backend='gloo')
    model = nn.Sequential(nn.Linear(100, 100))
    print(model[0].weight.device)
    model_fsdp = fully_shard(model)
    dtensor = model_fsdp[0].weight
    print(dtensor.device)
    print(dtensor.full_tensor())
```
Run this code with 
`torchrun --nnodes=1 --nproc-per-node=2  a.py` on a machine with >=2 GPUs. It will segfault. Tested on torch2.4.0 and nightly.

It seems `fully_shard` moves the model to CUDA but still trying to run collectives with the default GLOO group. 

I'm not sure the correct behavior should be which of the following two:
* raise exception somewhere
* `fully_shard`  just shard on CPU given that the original model & the default PG is both on CPU.

### Versions

```
PyTorch version: 2.5.0.dev20240801+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.4 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35
```

cc @XilunWu @H-Huang @awgu @kwen2501 @wanchaol @fegin @fduwjj @wz337 @wconstab @d4l3k @c-p-i-o

**Comment by awgu** [comment] 2024-08-02 15:00
Thanks! I need some time to triage this precisely.

**Comment by wz337** [comment] 2024-08-02 15:42
> torchrun --nnodes=1 --nproc-per-node=2 a.py

@awgu I have some ideas. I think the issue may be that dtensor still uses the default gloo pg to run the all_gather for full_tensor call, which resulted in the the sigterm. Since if I do change `init_process_group` to `nccl`, this is running fine: 

```
from torch.distributed._composable.fsdp import fully_shard
import torch.distributed as dist
from torch import nn
import os
import torch
from torch.distributed.device_mesh import init_device_mesh

if __name__ == '__main__':
    dist.init_process_group(backend='nccl')
    rank = int(os.environ['RANK'])
    torch.cuda.set_device(rank)
    model = nn.Sequential(nn.Linear(100, 100))
    # print(f"rank:{rank}, model device: {model[0].weight.device=}")
    device_mesh = init_device_mesh("cuda", (dist.get_world_size(),))
    model_fsdp = fully_shard(model)
    dtensor = model_fsdp[0].weight
    # print(f"rank:{rank}, fully_shard device: {dtensor.device=}")
    print(dtensor.full_tensor())
```

**Comment by awgu** [comment] 2024-08-05 15:08
@wz337 Is there a way to tell that FSDP's `DeviceMesh` is backed by a gloo PG and raise that that is not supported?

**Comment by wz337** [comment] 2024-08-05 17:33
> @wz337 Is there a way to tell that FSDP's `DeviceMesh` is backed by a gloo PG and raise that that is not supported?

Probably need to rely on c10d's `get_backend()` to check, something like `get_backend(device_mesh.get_group())` `DeviceMesh` itself don't expose any API to get the backend.

I am thinking what a good way for a proper fix would be. Maybe we shouldn't reuse the default group unless it is using the 'cpu:gloo,cuda:nccl' backend so users wouldn't see this misalignment between device and backend.

**Comment by awgu** [comment] 2024-08-05 17:50
https://github.com/pytorch/pytorch/blob/7b2664ece6a961ce9e4557be913c2cead09c7390/torch/distributed/_composable/fsdp/_fsdp_init.py#L60-L62

I think there are two cases:
1. CUDA is not available, so FSDP2 will call `init_device_mesh` with `device_type="cpu"`.
2. CUDA is available, so FSDP2 will call `init_device_mesh` with `device_type="cuda"`.

IIUC, we are hitting the second case here since the original repro uses >=2 GPUs. In that case, I think `DeviceMesh` should not reuse the default PG if it is gloo PG? Actually, I thought gloo PG also supports CUDA tensors. I wonder why it is segfaulting.

**Comment by wz337** [comment] 2024-08-05 19:49
> ```python
> print(dtensor.device)
> ```

Ye. For 2, as gloo PG should support CUDA tensors, this should be something that can be repro-ed without DTensor. 

I tried a local repro without `DTensor` and `full_tensor` call. Seems there is an issue with using gloo PG on CUDA tensors. 

```
from torch.distributed._composable.fsdp import fully_shard
import torch.distributed as dist
from torch import nn
import os
import torch
from torch.distributed.device_mesh import init_device_mesh
import torch.distributed._functional_collectives as funcol

if __name__ == '__main__':
    dist.init_process_group(backend='gloo')
    local_tensor = torch.ones(3, 3)  #  works fine if we don't move the local_tensor to cuda
    local_tensor = torch.ones(3, 3).to("cuda")
    mesh = init_device_mesh("cpu", (dist.get_world_size(),))
    result = funcol.all_gather_tensor(
        local_tensor, # local tensor is on cuda
        gather_dim=0,
        group=(mesh, 0), # this is to get the default group of device_mesh since the mesh is 1D
    ) # SIGTERM here
    print(f"{result=}") 
```

**Comment by wz337** [comment] 2024-08-05 20:42
> Ye. For 2, as gloo PG should support CUDA tensors, this should be something that can be repro-ed without DTensor.
> 
> I tried a local repro without `DTensor` and `full_tensor` call. Seems there is an issue with using gloo PG on CUDA tensors.
> 
> ```
> from torch.distributed._composable.fsdp import fully_shard
> import torch.distributed as dist
> from torch import nn
> import os
> import torch
> from torch.distributed.device_mesh import init_device_mesh
> import torch.distributed._functional_collectives as funcol
> 
> if __name__ == '__main__':
>     dist.init_process_group(backend='gloo')
>     local_tensor = torch.ones(3, 3)  #  works fine if we don't move the local_tensor to cuda
>     local_tensor = torch.ones(3, 3).to("cuda")
>     mesh = init_device_mesh("cpu", (dist.get_world_size(),))
>     result = funcol.all_gather_tensor(
>         local_tensor, # local tensor is on cuda
>         gather_dim=0,
>         group=(mesh, 0), # this is to get the default group of device_mesh since the mesh is 1D
>     ) # SIGTERM here
>     print(f"{result=}") 
> ```

Maybe @yifuwang knows more on the expected behavior here. If this is not allowed, we will go with `DeviceMesh` should not reuse the default PG if it is gloo PG.

**Comment by wz337** [comment] 2024-08-05 21:20
> > Ye. For 2, as gloo PG should support CUDA tensors, this should be something that can be repro-ed without DTensor.
> > I tried a local repro without `DTensor` and `full_tensor` call. Seems there is an issue with using gloo PG on CUDA tensors.
> > ```
> > from torch.distributed._composable.fsdp import fully_shard
> > import torch.distributed as dist
> > from torch import nn
> > import os
> > import torch
> > from torch.distributed.device_mesh import init_device_mesh
> > import torch.distributed._functional_collectives as funcol
> > 
> > if __name__ == '__main__':
> >     dist.init_process_group(backend='gloo')
> >     local_tensor = torch.ones(3, 3)  #  works fine if we don't move the local_tensor to cuda
> >     local_tensor = torch.ones(3, 3).to("cuda")
> >     mesh = init_device_mesh("cpu", (dist.get_world_size(),))
> >     result = funcol.all_gather_tensor(
> >         local_tensor, # local tensor is on cuda
> >         gather_dim=0,
> >         group=(mesh, 0), # this is to get the default group of device_mesh since the mesh is 1D
> >     ) # SIGTERM here
> >     print(f"{result=}") 
> > ```
> 
> Maybe @yifuwang knows more on the expected behavior here. If this is not allowed, we will go with `DeviceMesh` should not reuse the default PG if it is gloo PG.

@awgu Ah. I think only `broadcast` and `all_reduce` is supported for `cuda` tensor with `gloo` according to our doc here: https://pytorch.org/docs/stable/distributed.html. For users using `gloo` with CUDA, they would need to explicitly move the cuda tensor to cpu before calling `full_tensor()` or any collective not supported. 

Separately, I agree that when DeviceMesh's device_type is 'cuda', we should avoid reusing the default pg if it is 'gloo' so users won't run into the mysterious segfault. Let me try put up a fix.

**Comment by wz337** [comment] 2024-08-14 17:05
Closing as we landed https://github.com/pytorch/pytorch/commit/8b50d5398fab79b599178627bed766859b3cd9dd

**Closed by wz337** 2024-08-14 17:05 UTC
Labels: oncall: distributed, triaged
