### ISSUE TITLE
"GET was unable to find an engine to execute this computation" when kerner_size larger than input_size using stride conv

### ISSUE THREAD

**Issue by in-water** [pytorch/pytorch#103665] opened 2023-06-15 10:05 UTC
#### Here is a minimal example to reproduce the bug

```python
import torch
a=torch.randn(1,208,2,2).cuda()
b=torch.nn.Conv2d(208,208,kernel_size=3,stride=2,padding=1).cuda()
print(b(a).shape)
# output: torch.Size([1, 208, 1, 1])
a=torch.randn(1,209,2,2).cuda()
b=torch.nn.Conv2d(209,209,kernel_size=3,stride=2,padding=1).cuda()
print(b(a).shape)
# RuntimeError: GET was unable to find an engine to execute this computation
```

### Versions

PyTorch version: 2.0.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.26.4
Libc version: glibc-2.27

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-42-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.4.48
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Quadro RTX 8000
GPU 1: Quadro RTX 8000
GPU 2: Quadro RTX 8000
GPU 3: Quadro RTX 8000
GPU 4: Quadro RTX 8000
GPU 5: Quadro RTX 8000
GPU 6: Quadro RTX 8000
GPU 7: Quadro RTX 8000

Nvidia driver version: 470.42.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.4/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 5220R CPU @ 2.20GHz
Stepping:            7
CPU MHz:             1072.212
CPU max MHz:         4000.0000
CPU min MHz:         1000.0000
BogoMIPS:            4400.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-23,48-71
NUMA node1 CPU(s):   24-47,72-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] open-clip-torch==2.16.0
[pip3] pytorch-lightning==1.8.6
[pip3] torch==2.0.1
[pip3] torch-tensorrt==1.3.0
[pip3] torchlm==0.1.6.10
[pip3] torchmetrics==0.11.4
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] numpy                     1.24.3                   pypi_0    pypi
[conda] torch                     2.0.1                    pypi_0    pypi
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchvision               0.15.2                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by cpuhrsch** [comment] 2023-06-15 17:26
@in-water I can't reproduce this issue on a recently nightly *using CUDA 11.8*. Maybe this has already been fixed or you have to update your CUDA version.

```
>>> import torch
>>> a=torch.randn(1,208,2,2).cuda()
>>> b=torch.nn.Conv2d(208,208,kernel_size=3,stride=2,padding=1).cuda()
>>> print(b(a).shape)

torch.Size([1, 208, 1, 1])
>>> # output: torch.Size([1, 208, 1, 1])
>>> a=torch.randn(1,209,2,2).cuda()
>>> b=torch.nn.Conv2d(209,209,kernel_size=3,stride=2,padding=1).cuda()
>>> print(b(a).shape)
torch.Size([1, 209, 1, 1])
```

**Comment by in-water** [comment] 2023-06-16 04:13
@cpuhrsch Thanks. The issue was addressed by install torch2.0 by conda instead of pip

**Comment by jbschlosser** [comment] 2023-06-16 17:39
Closing as resolved, but feel free to reopen if additional issues are encountered.

**Closed by jbschlosser** 2023-06-16 17:39 UTC
Labels: module: nn, triaged
