### ISSUE TITLE
Windows Build Failure: error C2672

### ISSUE THREAD

**Issue by HDCharles** [pytorch/pytorch#31180] opened 2019-12-12 10:37 UTC
note I wrote similar details here but haven't gotten an answer:
https://stackoverflow.com/questions/59291287/trouble-installing-pytorch-from-source

### **Background**
As mentioned in the above link, I'm trying to compile from source due to my GPU being old and support for it has been removed per the thread:  https://discuss.pytorch.org/t/pytorch-no-longer-supports-this-gpu-because-it-is-too-old/13803. I found someone with similar errors (I think) here: https://github.com/pytorch/pytorch/issues/20420 but haven't had any luck. I've uninstalled everything including anaconda, pytorch, cuda, visual studio, python and reinstalled (with cuda being installed after visual studio) but nothing has worked. I'm really unsure what the issue could be tbh. Some additional notes that I'm not sure are relevant: my main drive is C but I have most things including Cuda installed on E, I'm running the python setup.py install command from within an anaconda terminal, not sure if thats whats I'm supposed to do, the readme repeatedly refers to anaconda so all the dependencies and stuff are installed only there. Also i've literally never installed something by compiling it from source before so its possible im doing something very basic wrong. I've been at it a while (multiple weeks off and on) and scoured every relevant page I could find though so I really hope not. Also I'm using VS17 but was doing it with 19 before without luck.

### **LOGS**
I have 2 logs from a ninja and non ninja build here:
https://www.dropbox.com/s/fx9wc38utijx8f3/build.log?dl=0
https://www.dropbox.com/s/4zkb5qz2hqbysn0/build%20ninjaoff.log?dl=0

Here's some environment details: 

### **Env**
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 7 Professional
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 770M
Nvidia driver version: 425.31
cuDNN version: E:\python\CUDA\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] numpydoc==0.9.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      245  
[conda] mkl-include               2019.4                      245  
[conda] mkl-service               2.3.0            py37hb782905_0  
[conda] mkl_fft                   1.0.14           py37h14836fe_0  
[conda] mkl_random                1.1.0            py37h675688f_0

Any help would be greatly appreciated.

**Comment by peterjc123** [comment] 2019-12-12 11:06
Your build error is a duplicate of https://github.com/pytorch/pytorch/issues/30886. You can try building with VS 2019.

**Closed by peterjc123** 2019-12-12 11:06 UTC

**Comment by HDCharles** [comment] 2019-12-12 11:08
Alright will return to 19 and retry again.
