### ISSUE TITLE
Compiling failure on pytorch 1.6.0 with old gpu

### ISSUE THREAD

**Issue by showgood163** [pytorch/pytorch#43487] opened 2020-08-24 08:11 UTC
Environment:

arch linux (latest)
python 3.8.5
cuda 11.0.2
cudnn 8.0.2

Goal:

Trying to build custom package for an old gpu (GTX770m, 'compute_30')

Steps to reproduce:

1. Get offcial PKGBUILD and other 4 patch files listed [here](https://www.archlinux.org/packages/community/x86_64/python-pytorch-opt-cuda/) (actually download from [here](https://www.archlinux.org/packages/community/x86_64/python-pytorch-opt-cuda/)
2. Modify just one line about the target in PKGBUILD, `export TORCH_CUDA_ARCH_LIST="3.0;"`
3. run `makepkg`

Result:

1. The most significant failure in the compiling process is:
```
[1367/4917] cd /home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir && /usr/bin/cmake -E make_directory /home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda.cu.o -D generated_cubin_file:STRING=/home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda.cu.o.cubin.txt -P /home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//gloo_cuda_generated_cuda.cu.o.Release.cmake
FAILED: third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir/gloo_cuda_generated_cuda.cu.o 
cd /home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir && /usr/bin/cmake -E make_directory /home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//. && /usr/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda.cu.o -D generated_cubin_file:STRING=/home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda.cu.o.cubin.txt -P /home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//gloo_cuda_generated_cuda.cu.o.Release.cmake
nvcc fatal   : Unsupported gpu architecture 'compute_30'
CMake Error at gloo_cuda_generated_cuda.cu.o.Release.cmake:217 (message):
  Error generating
  /home/asteria/pytorch-custom/src/pytorch-1.6.0-opt-cuda/build/third_party/gloo/gloo/CMakeFiles/gloo_cuda.dir//./gloo_cuda_generated_cuda.cu.o
```

2. The detailed log is [makepkg.log](https://github.com/pytorch/pytorch/files/5116549/makepkg.log)

**Comment by peterjc123** [comment] 2020-08-24 14:03
It seems that CUDA ARCH 3.0 is not supported anymore. Please use a new GPU card.

**Comment by showgood163** [comment] 2020-08-24 14:20
If so, what's the latest pytorch version with the support of CUDA ARCH 3.0? Could you give me some advices?

**Comment by ngimel** [comment] 2020-08-24 20:13
Closing, compute capability 3.0 is not supported (has not been supported for a long time, so can't tell exactly what's the latest pytorch version that supports it).

**Closed by ngimel** 2020-08-24 20:13 UTC

**Comment by cyberwillis** [comment] 2020-11-02 20:00
@showgood163

I know is a little bit late to answet this, but the problem is that NVIDIA dropped sm_30 architecture in cuda 11.0. 

https://docs.nvidia.com/cuda/archive/11.0/cuda-toolkit-release-notes/index.html#deprecated-features

If you downgrade your cuda to 10.2 or 10.0 then you can still build pytorch 1.6.0 or 1.7.0

**Comment by showgood163** [comment] 2020-11-03 01:27
@cyberwillis Thanks for the explaination! I may try it when I have time...

**Comment by LeorFinacre** [comment] 2024-04-04 15:42
Hello @showgood163 

I also have a 770M graphic card and I ran into the same issue as yours when I try to run Deepstack.

> Found GPU0 GeForce GTX 770 which is of cuda capability 3.0.
PyTorch no longer supports this GPU because it is too old.
The minimum cuda capability that we support is 3.5.

I also try to downgrade my CUDA version to 10.2 and install another version of pytorch.

Do you succeed and if so, what were your steps ?

Thank's a lot if you have, or anybody else, informations on this problem. I have checked online and tried lots of things since the last 3 days.

**Comment by cyberwillis** [comment] 2024-04-04 16:42
> Hello @showgood163
> 
> I also have a 770M graphic card and I ran into the same issue as yours when I try to run Deepstack.
> 
> > Found GPU0 GeForce GTX 770 which is of cuda capability 3.0.
> > PyTorch no longer supports this GPU because it is too old.
> > The minimum cuda capability that we support is 3.5.
> 
> I also try to downgrade my CUDA version to 10.2 and install another version of pytorch.
> 
> Do you succeed and if so, what were your steps ?
> 
> Thank's a lot if you have, or anybody else, informations on this problem. I have checked online and tried lots of things since the last 3 days.

Hi ....

Ohhhh Long time this... anyway I will try to guide you a little because this today is old.
I am talking for the point of view of using a Linux OS, if you want to adventure yourself in windows don't ask me.

Using cuda 10.2 and nccl libraries at maximum. Also you will need to set some environment variables before you compile pythorch. I believe the variables bellow are compatible with Pythorch up to 1.10 or even 1.13 if I am not wrong, some of them can be different.
Also last time I built using this variables was for Python 3.8 and I had success even with pythorch 1.13.1 and cuda 10.2

So first download from source, and checkout the tag relative to the version you want to build and their sub modules.
```
export PYTORCH_BUILD_VERSION="1.13.1"
git clone https://github.com/pytorch/pytorch.git
git checkout "v${PYTORCH_BUILD_VERSION}"
git submodule sync;
git submodule update --init --recursive;
```
Environment variables 
```
export USE_CUDA=1
#export MAGMA_HOME=/opt/magma  # I suppose you don't have or use Magma lib
#export USE_MAGMA=1                       # I suppose you don't have or use Magma lib
export DEBUG=0
export CUDA_DEVICE_DEBUG=0
export USE_MKL=0
export USE_MKLDNN=0
export USE_NNPACK=0
export USE_QNNPACK=0
export USE_NCCL=1
export USE_CUDNN=1
export CMAKE_CXX_FLAGS="-fPIC"
export TORCH_CUDA_ARCH_LIST="3.0"
export TORCH_NVCC_FLAGS="-Xfatbin -compress-all"

export PYTORCH_BUILD_VERSION=${PYTORCH_BUILD_VERSION}
export PYTORCH_BUILD_NUMBER=1
```

There are some patches that you need to run over the source code in order to allow to compile for your GPU architecture.
The GTX 770 if I am not wrong uses a Kepler and/or 3.0 cuda capability so you will have to enable those.

For Pythorch 1.13.1 look for ./torch/utils/cpp_extension.py  and update manually accordingly to the script bellow or . Create a file *torch_1.13.1.patch* with this content bellow, 

Notice that every version of Pytorch in the past had some patches after February 2020, because the architecture Kepler was depricated that time. The patch bellow is only for Pytorch 1.13.1 only others versions should be similar. If are not trying to build for this version or the version 1.9.1 at least you can ignore creating or trying to patch it.
```
diff --git a/torch/utils/cpp_extension.py b/torch/utils/cpp_extension.py
index 9ab43e5ccdd..2740a6bdf4d 100644
--- a/torch/utils/cpp_extension.py
+++ b/torch/utils/cpp_extension.py
@@ -49,7 +49,7 @@ MINIMUM_MSVC_VERSION = (19, 0, 24215)
 # summarizes the minimum valid major versions of g++/clang++ for each supported
 # CUDA version: https://gist.github.com/ax3l/9489132
 CUDA_GCC_VERSIONS = {
-    '10.2': (MINIMUM_GCC_VERSION, (8, 0, 0)),
+    '10.2': (MINIMUM_GCC_VERSION, (8, 4, 0)),
     '11.1': (MINIMUM_GCC_VERSION, (10, 0, 0)),
     '11.2': (MINIMUM_GCC_VERSION, (10, 2, 1)),
     '11.3': (MINIMUM_GCC_VERSION, (10, 2, 1)),
@@ -1739,7 +1739,7 @@ def _get_cuda_arch_flags(cflags: Optional[List[str]] = None) -> List[str]:
     # string replacement may not do the right thing
     named_arches = collections.OrderedDict([
         ('Kepler+Tesla', '3.7'),
-        ('Kepler', '3.5+PTX'),
+        ('Kepler', '3.0+PTX'),
         ('Maxwell+Tegra', '5.3'),
         ('Maxwell', '5.0;5.2+PTX'),
         ('Pascal', '6.0;6.1+PTX'),
@@ -1748,7 +1748,7 @@ def _get_cuda_arch_flags(cflags: Optional[List[str]] = None) -> List[str]:
         ('Ampere', '8.0;8.6+PTX'),
     ])
 
-    supported_arches = ['3.5', '3.7', '5.0', '5.2', '5.3', '6.0', '6.1', '6.2',
+    supported_arches = ['3.0', '3.5', '3.7', '5.0', '5.2', '5.3', '6.0', '6.1', '6.2',
                         '7.0', '7.2', '7.5', '8.0', '8.6']
     valid_arch_strings = supported_arches + [s + "+PTX" for s in supported_arches]
```

If you created the patch file in your HOME Directory then execute :
```
if [[ $PYTORCH_BUILD_VERSION == 1.13.1 ]];then
    git apply "${HOME}/torch_1.13.1.patch"
fi
```

Building. Also this can take a while depending of your machine or number of cores you have.
```
python3 setup.py bdist_wheel
```
At the end you will have a WHL inside "dist" folder that you can install.

**Comment by cyberwillis** [comment] 2024-04-04 16:56
Also verify you will have to do something similar with Torchvision in case you need it, because it will depend on "your" version of torch that will be plugged to your Cuda 10.2 and NCCL libraries.

**Comment by LeorFinacre** [comment] 2024-04-04 19:14
Hello @cyberwillis 

Thank's A LOT for your quick and detailled answer ! 
I am on Debian 12. I tried to reproduce your steps with the exact same versions for now.

During compilation (last step from your tutorial) I encountered an error : 

> -- Found CUDA: /usr/local/cuda (found version "12.4")
-- The CUDA compiler identification is unknown
CMake Error at /usr/share/cmake-3.25/Modules/CMakeDetermineCUDACompiler.cmake:603 (message):
  Failed to detect a default CUDA architecture.



>   Compiler output:
> 
> Call Stack (most recent call first):
>   cmake/public/cuda.cmake:47 (enable_language)
>   cmake/Dependencies.cmake:43 (include)
>   CMakeLists.txt:722 (include)
> 
> 
> -- Configuring incomplete, errors occurred!

I tried to add an environnement variable named DTCNN_CUDA_ARCHITECTURES with the value native but didn't worked.

Is there something missing ?

**Comment by cyberwillis** [comment] 2024-04-04 19:28
Okay, so .. if you don't need cuda 12 I suggest you remove because if you don't have on this machine a recent GPU it will not work with kepler at all. 

Every time you install a cuda version a .so library is registred on the system and the higher version probably is taking priority during the configuration processo pre-building the pytorch. So in order to stop this conflict you should try to remove completely the folder of cuda, and execute the 

```sudo ldconfig ```

then after install the 10.2 and execute this again only the new shared library will be available in the system and stop giving conflicts.

**Comment by LeorFinacre** [comment] 2024-04-05 07:02
Ok, so fresh install of Debian 12 since I couldn't get the cuda, cuda12 and cuda12.4 installed on my machine properly uninstalled without packages corruption etc ...

So what I did so far is preparing my machine with these commands 

**Machine preparation**

> su -
apt-get install sudo software-properties-common net-tools docker-compose aptitude python3
sudo nano /etc/systemd/logind.conf
#Since it's an old notebook (laptop)
_HandleLidSwitch=ignore 
HandleLidSwitchDocked=ignore_

**Then Kernel Headers installation**

> sudo apt install linux-headers-$(uname -r)
> sudo apt upgrade

**Desabling driver Nouveau since I'm gonna install the Nvidia .run file**

> sudo nano /etc/modprobe.d/blacklist-nouveau.conf
> _blacklist nouveau
> options nouveau modeset=0_
> 
> sudo update-initramfs -u
> sudo reboot

Then I installed the correct driver version that supports my Graphic Card (Legacy Driver) from there :
https://us.download.nvidia.com/XFree86/Linux-x86_64/470.239.06/NVIDIA-Linux-x86_64-470.239.06.run

After a reboot I'm able to see something with these commands : 

> lsmod | grep nvidia
nvidia-smi

![image](https://github.com/pytorch/pytorch/assets/408695/50858af4-a92d-4553-86a1-6acd3f06cc2b)

Don't know why it says CUDA 11.4 at this stage because I don't have any CUDA installed yet.

Then I'm finally able to run the installer for CUDA10.2 (I tried before all those commands on a fresh install but it failed to install the driver and when I specify to not install the driver it also fails. Strange thing, in the logs everything went pretty smoothly but it uninstall everything it just installed and says it failed ...)

When running the installer from there https://developer.nvidia.com/cuda-10.2-download-archive?target_os=Linux&target_arch=x86_64&target_distro=Ubuntu&target_version=1804&target_type=runfilelocal 
I had to specify to NOT install the Driver.
And so far, so good, I have a directory in /usr/local/cuda-10.2

Now I'm running the commands from [your post](https://github.com/pytorch/pytorch/issues/43487#issuecomment-2037694772) again.

**Comment by LeorFinacre** [comment] 2024-04-05 08:13
I added a new env variable : 

> export CMAKE_CUDA_ARCHITECTURES="native"
Now the error changed to this one : 

![image](https://github.com/pytorch/pytorch/assets/408695/3a2d9113-4f4a-4d0f-858e-1c9f5372deec)
I'm guessing I miss a lot of environment variables (?)

**Comment by cyberwillis** [comment] 2024-04-05 08:44
Hi... 

Yeah appear you did everything well. 
Your gcc is bigger than 8.xx !

> /usr/local/cuda-10.2/bin/../targets/x86_64-linux/include/crt/host_config.h:138:2:
>  error: #error -- unsupported GNU version! gcc versions later than 8 are not
>  supported!
>
>    138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
>        |  ^~~~~
>
>   --error 0x1 --

In order to verify if this is truth could you post to me the result of 

```
gcc --version && nvcc --version;
```

If you review in my patch code I set to use my gcc on that time that was 8.4.0

> CUDA_GCC_VERSIONS = {
> -    '10.2': (MINIMUM_GCC_VERSION, (8, 0, 0)),
> +    '10.2': (MINIMUM_GCC_VERSION, (8, 4, 0)),

Let me know.

**Comment by LeorFinacre** [comment] 2024-04-05 08:57
Yeah, I tried to change my gcc version. It was indeed greater than 8
![image](https://github.com/pytorch/pytorch/assets/408695/17dde733-0c0f-4d77-8796-6cba9daa15c1)

So I managed to download and install the version 8 with those commands : 
Adding the repo in _/etc/apt/sources.list_

> deb http://ftp.de.debian.org/debian buster main

Then I ran this command : 
```bash
sudo aptitude install gcc-8
```
And anwsered yes to the conflict with some libs.

So now I have 2 versions of GCC installed.
![image](https://github.com/pytorch/pytorch/assets/408695/05600bf7-5f6e-4687-b76e-6acf44d0e79a)

So I defined another environment variable to specify which version of GCC to use : 
```bash
export CMAKE_C_COMPILER=/usr/bin/gcc-8
```
And ran the script to build pytorch again : 

```bash
romain@MSI-DEBIAN:~/pytorch$ python3 setup.py bdist_wheel
Building wheel torch-1.13.1
-- Building version 1.13.1
cmake -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_CUDA_ARCHITECTURES=native -DCMAKE_CXX_COMPILER=/usr/bin/gcc-8 -DCMAKE_CXX_FLAGS=-fPIC -DCMAKE_C_COMPILER=/usr/bin/gcc-8 -DCMAKE_INSTALL_PREFIX=/home/romain/pytorch/torch -DCMAKE_PREFIX_PATH=/usr/local/lib/python3.11/dist-packages -DCUDA_NVCC_EXECUTABLE=/usr/local/cuda-10.2/bin/nvcc -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.11 -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.11.so.1.0 -DTORCH_BUILD_VERSION=1.13.1 -DUSE_CUDA=1 -DUSE_CUDNN=1 -DUSE_MKL=0 -DUSE_MKLDNN=0 -DUSE_NCCL=1 -DUSE_NNPACK=0 -DUSE_NUMPY=True -DUSE_QNNPACK=0 /home/romain/pytorch
-- The CXX compiler identification is unknown
-- The C compiler identification is GNU 8.3.0
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /usr/bin/gcc-8
-- Check for working CXX compiler: /usr/bin/gcc-8 - broken
CMake Error at /usr/share/cmake-3.25/Modules/CMakeTestCXXCompiler.cmake:63 (message):
  The C++ compiler

    "/usr/bin/gcc-8"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: /home/romain/pytorch/build/CMakeFiles/CMakeScratch/TryCompile-b5Oe6o

    Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_06a72/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_06a72.dir/build.make CMakeFiles/cmTC_06a72.dir/build
    gmake[1] : on entre dans le répertoire « /home/romain/pytorch/build/CMakeFiles/CMakeScratch/TryCompile-b5Oe6o »
    Building CXX object CMakeFiles/cmTC_06a72.dir/testCXXCompiler.cxx.o
    /usr/bin/gcc-8   -fPIC  -o CMakeFiles/cmTC_06a72.dir/testCXXCompiler.cxx.o -c /home/romain/pytorch/build/CMakeFiles/CMakeScratch/TryCompile-b5Oe6o/testCXXCompiler.cxx
    gcc-8: error trying to exec 'cc1plus': execvp: Aucun fichier ou dossier de ce type
    gmake[1]: *** [CMakeFiles/cmTC_06a72.dir/build.make:78 : CMakeFiles/cmTC_06a72.dir/testCXXCompiler.cxx.o] Erreur 1
    gmake[1] : on quitte le répertoire « /home/romain/pytorch/build/CMakeFiles/CMakeScratch/TryCompile-b5Oe6o »
    gmake: *** [Makefile:127 : cmTC_06a72/fast] Erreur 2





  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:23 (project)


-- Configuring incomplete, errors occurred!
See also "/home/romain/pytorch/build/CMakeFiles/CMakeOutput.log".
See also "/home/romain/pytorch/build/CMakeFiles/CMakeError.log".
```

It appears I need to do something else to my gcc installation in order for it to work properly.

Should I uninstall properly gcc-12 with

> sudo apt remove gcc-12

And reinstall gcc-8 ?

**Comment by cyberwillis** [comment] 2024-04-05 09:03
Actually you don't need to remove. 

Do you know how to use update-alternatives ?

Anyway when I used to do this I did in a container and inside it I had all the gcc installed 8,9,10,11 then using update alternative I used to switch the gcc I wanted, in that way the /bin/gcc and /bin/g++  would use the links created by the update-alternatives instead what the system wants.

But in case yeah you could try to uninstall or just setup all the gccs as alternative and select witch one you prefer at any moment

**Comment by cyberwillis** [comment] 2024-04-05 09:10
I used to do this during installation process inside my container
```
sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 8 \
--slave /usr/bin/g++ g++ /usr/bin/g++-8 \
--slave /usr/bin/gfortran gfortran /usr/bin/gfortran-8 \
--slave /usr/x86_64-linux-gnu libgfortran /usr/lib/gcc/x86_64-linux-gnu/8

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 9 \
--slave /usr/bin/g++ g++ /usr/bin/g++-9 \
--slave /usr/bin/gfortran gfortran /usr/bin/gfortran-9 \
--slave /usr/x86_64-linux-gnu libgfortran /usr/lib/gcc/x86_64-linux-gnu/9

sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-10 10 \
--slave /usr/bin/g++ g++ /usr/bin/g++-10 \
--slave /usr/bin/gfortran gfortran /usr/bin/gfortran-10 \
--slave /usr/x86_64-linux-gnu libgfortran /usr/lib/gcc/x86_64-linux-gnu/10
```

During build time depending on the cuda version I was using I used to set this before start configuration or set the environment variables.
```
sudo update-alternatives --set gcc /usr/bin/gcc-8
sudo ldconfig
```

**Comment by cyberwillis** [comment] 2024-04-05 10:30
https://unix.stackexchange.com/questions/592657/full-upgrade-to-debian-testing-fails-due-to-libc6-dev-breaks-libgcc-8-dev

Try this ?

```sudo apt install gcc-8-base```

**Comment by LeorFinacre** [comment] 2024-04-05 10:36
(I saw this post yeah and I tried anyway)
```bash
Reading package lists... Done
Building the dependency tree... Done
Reading status information... Done
gcc-8-base is already the most recent version (8.3.0-6).
0 updated, 0 newly installed, 0 to remove and 0 not updated.
```
It said it was already installed and still got the error about libc6-dev lib.
It's really a pain to get it working : two steps back to one forward, jesus.

**Comment by cyberwillis** [comment] 2024-04-05 11:06
Well yeah I see the libgcc-8-dev is conflicting in version with the libc-6-dev for that I don't know the answer for this.
If you not trying to be a brave person to learn how to compyle pytorch and  don't mind to just install it one version earlier (1.12.0) you could install from pip package without build anything.

```
pip install torch==1.12.1+cu102 torchvision==0.13.1+cu102 torchaudio==0.12.1 --extra-index-url https://download.pytorch.org/whl/cu102
```

**Comment by cyberwillis** [comment] 2024-04-05 11:14
If after installing it you be able to verify those lines it probably will work

```
import torch
print(torch.__version__)  #should return 1.12.1
print(torch.cuda.is_available())  #should return  True
print(torch.backends.cudnn.enabled) #should return True
```

**Comment by LeorFinacre** [comment] 2024-04-05 11:43
I would like to thank you a lot for your time and effort put in the resolution of my problem.
I think I will move from Deepstack, as it seems to really be too old to run on this machine and focus on codeproject.Ai Server

Yes, I won't be able to use my graphic card either as their minimum compute level support is 6 but at least I will have something fresh and maintained.

After nearly 5 days to struggle to get it working and nearly 10 Debian reinstall, I still learned a lot even if I didn't succeed.

Thank's anyway, that was painful but enriching.
