### ISSUE TITLE
Pytorch 2.0 [compile] Cast from scalar to tensor error

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#95184] opened 2023-02-21 06:39 UTC
### 🐛 Describe the bug

Please use below code to reproduce error:
```
import torch

class BasicModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, tensor, scalar):
        tensor = tensor.__or__(scalar)
        return tensor

if __name__ == "__main__":
    tensor = torch.tensor([7, 2, 3, 4], dtype=torch.uint8)
    model = BasicModule()
    model = torch.compile(model)
    fwd_res = model(tensor, 7)
    print(fwd_res)
```
Error:
```
RuntimeError: Failed running call_method __or__(*(FakeTensor(FakeTensor(..., device='meta', size=(4,), dtype=torch.uint8), cpu), 7), **{}):
aten::bitwise_or() Expected a value of type 'Tensor' for argument 'other' but instead found type 'int'.
Position: 1
Value: 7
Declaration: aten::bitwise_or.Tensor(Tensor self, Tensor other) -> Tensor
Cast error details: Unable to cast 7 to Tensor
(scroll up for backtrace)
```

Same graphs works fine in eager mode. Shouldn't it fallback to eager if compile execution breaks?

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230209+cpu
[pip3] torchaudio==2.0.0.dev20230209+cpu
[pip3] torchvision==0.15.0.dev20230209+cpu

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment] 2023-02-23 00:23
Likely duplicate of #93224, @kshitij12345 can you confirm if it's a dupe?

**Comment by kshitij12345** [comment] 2023-02-23 07:27
Yes, this is a duplicate of #93224. Closing this as a duplicate.

**Closed by kshitij12345** 2023-02-23 07:27 UTC
Labels: oncall: pt2
