### ISSUE TITLE
Different values of index of topk  for one tensor

### ISSUE THREAD

**Issue by kudep** [pytorch/pytorch#4935] opened 2018-01-30 13:11 UTC
## Environment info
- OS: Linux 4.13.0-31-generic #34~16.04.1-Ubuntu
- PyTorch version: 0.3
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.5
- CUDA/cuDNN version: 8/7
- GPU models and configuration: 1080Ti

## Issue
Snippet:
```
print("============================================================")
if DEBUG_LOG1 : print("type(decoder_output) = {}".format(type(decoder_output)))
if DEBUG_LOG1 : print("decoder_output.size() = {}".format(decoder_output.size()))
print("++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++")
if DEBUG_LOG1 : print("decoder_output.data.topk(1) = ".format(decoder_output.data.topk(1)))
if DEBUG_LOG1 : print("decoder_output.data.topk(1) = ".format(decoder_output.data.topk(1)))
if DEBUG_LOG1 : print("decoder_output.data.topk(1) = ".format(decoder_output.data.topk(1)))
if DEBUG_LOG1 : print("decoder_output.data.topk(1) = ".format(decoder_output.data.topk(1)))
print("////////////////////////////////////////////////////////////")
topv, topi = decoder_output.data.topk(1)
if DEBUG_LOG1 : print("topi,topv = {}{}".format(topi,topv))
topv, topi = decoder_output.data.topk(1)
if DEBUG_LOG1 : print("topi,topv = {}{}".format(topi,topv))
topv, topi = decoder_output.data.topk(1)
if DEBUG_LOG1 : print("topi,topv = {}{}".format(topi,topv))
topv, topi = decoder_output.data.topk(1)
if DEBUG_LOG1 : print("topi,topv = {}{}".format(topi,topv))
print("------------------------------------------------------------")
```
Out:
```
============================================================
type(decoder_output) = <class 'torch.autograd.variable.Variable'>
decoder_output.size() = torch.Size([1, 29419])
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
decoder_output.data.topk(1) = (
nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]
, 
 0
[torch.cuda.LongTensor of size 1x1 (GPU 0)]
)
decoder_output.data.topk(1) = (
nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]
, 
 0
[torch.cuda.LongTensor of size 1x1 (GPU 0)]
)
decoder_output.data.topk(1) = (
nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]
, 
 0
[torch.cuda.LongTensor of size 1x1 (GPU 0)]
)
decoder_output.data.topk(1) = (
nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]
, 
 0
[torch.cuda.LongTensor of size 1x1 (GPU 0)]
)

////////////////////////////////////////////////////////////
topi,topv = 
 0
[torch.cuda.LongTensor of size 1x1 (GPU 0)]

nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]

topi,topv = 
 9.2234e+18
[torch.cuda.LongTensor of size 1x1 (GPU 0)]

nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]

topi,topv = 
 9.2234e+18
[torch.cuda.LongTensor of size 1x1 (GPU 0)]

nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]

topi,topv = 
 2.1475e+09
[torch.cuda.LongTensor of size 1x1 (GPU 0)]

nan
[torch.cuda.FloatTensor of size 1x1 (GPU 0)]

------------------------------------------------------------

```

**Comment by SsnL** [comment] 2018-01-31 21:14
I'm supposing that topk is consistent when there is no nan?

**Comment by kudep** [comment] 2018-02-01 08:22
The tensor has nan. You're right, thank you!

**Comment by albanD** [comment] 2018-02-05 18:03
This is a duplicate of #1810 no?

**Comment by SsnL** [comment] 2018-06-06 21:37
Yes this is a duplicate. Closing in favor of #1810

**Closed by SsnL** 2018-06-06 21:37 UTC
