### ISSUE TITLE
Dataloader crashes if num_worker>0 on MacOS with Python 3.8

### ISSUE THREAD

**Issue by PiotrJander** [pytorch/pytorch#46648] opened 2020-10-21 10:01 UTC
## 🐛 Bug

When using a `DataLoader` with `num_workers` > 0, the process crashes with a stack trace which contains

```
...
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
...
RuntimeError: DataLoader worker (pid 88201) exited unexpectedly with exit code 1. Details are lost due to multiprocessing. Rerunning with num_workers=0 may give better error trace.
...
```

The full stack trace is here: https://gist.github.com/PiotrJander/e82ca1d94ae85e746f33a18d7ca2d492

The error does not occur when `num_workers` is set to 0.

The error only occurs on MacOS (specifically tested on 10.15.7) with Python 3.8 (specifically tested with Python 3.8.5). I could not reproduce it on Linux, or on MacOS with Python 3.6 or 3.7.

## To Reproduce

Run the following script which is taken verbatim from the [official](https://pytorch-lightning.readthedocs.io/en/latest/introduction_guide.html) [documentation](https://colab.research.google.com/drive/1-_LKx4HwAxl5M6xPJmqAAu444LTDQoa3): https://gist.github.com/PiotrJander/be093261db295b2571e3dde952a61ff4

on MacOS with Python 3.8 in an environment containing

```
pytorch-lightning==1.0.0
torch==1.6.0
torchvision==0.7.0
```

The full stack trace is here: https://gist.github.com/PiotrJander/e82ca1d94ae85e746f33a18d7ca2d492

## Environment

```
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.15.7
GCC version: Could not collect
CMake version: version 3.16.2

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-lightning==1.0.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect
```

## Additional notes

This seems to be related to https://github.com/pytorch/pytorch/issues/5301 and https://github.com/pytorch/pytorch/issues/25302 but those issues were closed without providing a solution.

cc @SsnL @VitalyFedyunin @ejguan

**Comment by zou3519** [comment] 2020-10-21 15:02
PyTorch lightning is a separate project from PyTorch. @PiotrJander you may want to cross-post there: https://github.com/PyTorchLightning/pytorch-lightning

**Comment by ThoenigAdrian** [comment] 2020-11-05 22:23
@zou3519 this is not a pytorch lightning issue

**Comment by zou3519** [comment] 2020-11-09 15:15
@ThoenigAdrian did you run into the same issue? Do you have a minimal script that we could run?

**Comment by ThoenigAdrian** [comment] 2020-11-09 15:57
@zou3519 
Make sure to run it with python 3.8 afaik 3.7 and below isn't affected.
```
import torch
import torchvision
from torchvision import transforms as tf

dtype = torch.float32
device = torch.device("cuda:0")

transforms = tf.Compose([tf.ToTensor()])

mnist_data = torchvision.datasets.MNIST("./mnist", transform=transforms, download=True)
batch_size = 500
# num workers needs to be set to 0 because of pytorch bug in python3.8 as multiprocessing changed
data_loader = torch.utils.data.DataLoader(mnist_data,
                                          batch_size=batch_size,
                                          shuffle=False,
                                          num_workers=1)

first_batch = next(data_loader.__iter__())
```

**Comment by leriomaggio** [comment] 2020-11-13 20:33
I can confirm the very same issue of @ThoenigAdrian with the following configuration: 

```
Platform: mac OS (so `torch.device("cpu")` 
Python: 3.8
PyTorch 1.7  (so **NO** lightning involved).
```

Everything works fine if I switch back to Python 3.7. 

In my very humble opinion it seems related to `multiprocessing` with Python 3.8 on Win/Mac, and a `spawn` Vs `fork` situation.  Same settings, on Linux works perfectly!

**Comment by SsnL** [comment] 2020-11-13 22:21
Have you tried doing what the error message says, wrapping with `if __name__ == '__main__':`?

**Comment by ThoenigAdrian** [comment] 2020-11-14 18:50
@SsnL yes even when this line is introduced , the same Exception is raised.

Code i tried: 

````
import torch
import torchvision
from torchvision import transforms as tf
from multiprocessing.spawn import freeze_support

if __name__ == '__main__':
    freeze_support()


dtype = torch.float32
device = torch.device("cuda:0")

transforms = tf.Compose([tf.ToTensor()])

mnist_data = torchvision.datasets.MNIST("./mnist", transform=transforms, download=True)
batch_size = 500
# num workers needs to be set to 0 because of pytorch bug in python3.8 as multiprocessing changed
data_loader = torch.utils.data.DataLoader(mnist_data,
                                          batch_size=batch_size,
                                          shuffle=False,
                                          num_workers=1)

first_batch = next(data_loader.__iter__())
```

**Comment by SsnL** [comment] 2020-11-14 18:58
You are using that wrong. What you need to do is to wrap all execution code
in the if. Try looking up Python spawn multiprocessing.

**Comment by ThoenigAdrian** [comment] 2020-11-14 19:04
This works ! Thx

**Comment by SsnL** [comment] 2020-11-14 20:10
Since this is standard python spawn multiprocessing issue, I'll close this.

**Closed by SsnL** 2020-11-14 20:10 UTC
Labels: module: dataloader, triaged

**Comment by leriomaggio** [comment] 2020-11-16 07:23
Hi @SsnL: sorry I forgot to mention I was in a notebook. 

I investigated the issue more in the details and now I am completely convinced that my initial guess was right: it is a `fork` vs `spawn` issue here. Thus `multiprocessing` related, rather than PyTorch, and it made sense to close this issue.

On my end, the issue I was having was caused by a combination of two factors: (1) Python 3.8 on macOS + (2) custom `collate_fn`, defined within the notebook!

In Python 3.8 on mac now the default backend for `multiprocessing` is now `spawn`, and the default `collate_fn` could not be found. 
This could be resolved by either **forcing** the `start_method` to `fork`; or defining the `collate_fn` in a separate module, and import it.

Writing all of this only for the records, and in case it may be helpful to anybody.

Anyway, since it took me a bit to understand all of these details by myself, testing on multiple platforms and configurations (Py versions and/or PyTorch versions), I was wondering whether it would be worthwhile clarifying this in the online documentation? I was keen to open an issue and PR about this. 
What would you think @SsnL ?

Cheers!

**Comment by SsnL** [comment] 2020-11-16 17:48
I think it would be reasonable to mention potential mp caveats and refer readers to other sources, but it should not be longer than 1~3 sentences as it is not the main purpose of the pytorch doc to describe python mp behavior.

**Comment by bogdns** [comment] 2024-04-08 04:14
The following may help some people:
```
import multiprocessing
multiprocessing.set_start_method("fork")
```
