### ISSUE TITLE
[cuda] Debug builds of PyTorch results in segmentation faults if CUDA-12 is used

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#102372] opened 2023-05-26 14:58 UTC
### 🐛 Describe the bug

Following PR, switching CI from 11.8 to 12.1 CUDA : https://github.com/pytorch/pytorch/pull/102178

Failure of libtorch-linux-bionic-cuda12.1-py3.7-gcc7 build: https://github.com/pytorch/pytorch/actions/runs/5071681366/jobs/9135310361

```
2023-05-25T19:49:58.6329395Z [ 87%] [32mBuilding CUDA object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/EmbeddingBag.cu.o[0m
2023-05-25T19:49:58.6357565Z cd /var/lib/jenkins/cpp-build/caffe2/build/caffe2 && /opt/cache/bin/sccache /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -DAT_PER_OPERATOR_HEADERS -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTORCH_CUDA_BUILD_MAIN_LIB -DTORCH_ENABLE_LLVM -DUSE_C10D_GLOO -DUSE_C10D_MPI -DUSE_C10D_NCCL -DUSE_CUDA -DUSE_DISTRIBUTED -DUSE_EXPERIMENTAL_CUDNN_V8_API -DUSE_EXTERNAL_MZCRC -DUSE_FLASH_ATTENTION -DUSE_NCCL -DUSE_RPC -DUSE_TENSORPIPE -D_FILE_OFFSET_BITS=64 -Dtorch_cuda_EXPORTS -I/var/lib/jenkins/cpp-build/caffe2/build/aten/src -I/var/lib/jenkins/workspace/aten/src -I/var/lib/jenkins/cpp-build/caffe2/build -I/var/lib/jenkins/workspace -I/var/lib/jenkins/workspace/cmake/../third_party/benchmark/include -I/opt/llvm/include -I/var/lib/jenkins/workspace/third_party/onnx -I/var/lib/jenkins/cpp-build/caffe2/build/third_party/onnx -I/var/lib/jenkins/workspace/third_party/foxi -I/var/lib/jenkins/cpp-build/caffe2/build/third_party/foxi -I/var/lib/jenkins/workspace/aten/src/THC -I/var/lib/jenkins/workspace/aten/src/ATen/cuda -I/var/lib/jenkins/workspace/aten/src/ATen/../../../third_party/cutlass/include -I/var/lib/jenkins/cpp-build/caffe2/build/caffe2/aten/src -I/var/lib/jenkins/workspace/aten/src/ATen/.. -I/var/lib/jenkins/cpp-build/caffe2/build/nccl/include -I/var/lib/jenkins/workspace/c10/cuda/../.. -I/var/lib/jenkins/workspace/c10/.. -I/var/lib/jenkins/workspace/third_party/tensorpipe -I/var/lib/jenkins/cpp-build/caffe2/build/third_party/tensorpipe -I/var/lib/jenkins/workspace/third_party/tensorpipe/third_party/libnop/include -I/var/lib/jenkins/workspace/torch/csrc/api -I/var/lib/jenkins/workspace/torch/csrc/api/include -isystem=/var/lib/jenkins/cpp-build/caffe2/build/third_party/gloo -isystem=/var/lib/jenkins/workspace/cmake/../third_party/gloo -isystem=/var/lib/jenkins/workspace/cmake/../third_party/googletest/googlemock/include -isystem=/var/lib/jenkins/workspace/cmake/../third_party/googletest/googletest/include -isystem=/var/lib/jenkins/workspace/third_party/protobuf/src -isystem=/opt/conda/envs/py_3.10/include -isystem=/var/lib/jenkins/workspace/third_party/gemmlowp -isystem=/var/lib/jenkins/workspace/third_party/neon2sse -isystem=/var/lib/jenkins/workspace/third_party/XNNPACK/include -isystem=/var/lib/jenkins/workspace/third_party/ittapi/include -isystem=/var/lib/jenkins/workspace/cmake/../third_party/eigen -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include -isystem=/usr/local/cuda/include -isystem=/var/lib/jenkins/workspace/third_party/ideep/mkl-dnn/third_party/oneDNN/include -isystem=/var/lib/jenkins/workspace/third_party/ideep/include -isystem=/var/lib/jenkins/workspace/third_party/ideep/mkl-dnn/include -isystem=/var/lib/jenkins/workspace/cmake/../third_party/cudnn_frontend/include -Xfatbin -compress-all -DONNX_NAMESPACE=onnx_torch -gencode arch=compute_52,code=sm_52 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -Xfatbin -compress-all -Wno-deprecated-gpu-targets --expt-extended-lambda -DCUB_WRAPPED_NAMESPACE=at_cuda_detail -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__  -g -lineinfo --source-in-ptx -Xcompiler=-fPIC -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -Xcompiler=-Wall,-Wextra,-Wno-unused-parameter,-Wno-unused-function,-Wno-unused-result,-Wno-missing-field-initializers,-Wno-unknown-pragmas,-Wno-type-limits,-Wno-array-bounds,-Wno-unknown-pragmas,-Wno-strict-overflow,-Wno-strict-aliasing,-Wno-missing-braces,-Wno-maybe-uninitialized -std=c++17 -MD -MT caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/EmbeddingBag.cu.o -MF CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/EmbeddingBag.cu.o.d -x cu -c /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/EmbeddingBag.cu -o CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/EmbeddingBag.cu.o
2023-05-25T19:50:09.0358226Z Segmentation fault (core dumped)
2023-05-25T19:50:09.0366676Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1849: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistributionCauchyKernel.cu.o' failed
2023-05-25T19:50:09.0367561Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistributionCauchyKernel.cu.o] Error 139
2023-05-25T19:50:09.0368155Z make[2]: *** Waiting for unfinished jobs....
2023-05-25T19:50:11.8324638Z Segmentation fault (core dumped)
2023-05-25T19:50:11.8331053Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1821: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistanceKernel.cu.o' failed
2023-05-25T19:50:11.8332060Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistanceKernel.cu.o] Error 139
2023-05-25T19:50:13.3739061Z Segmentation fault (core dumped)
2023-05-25T19:50:13.3746483Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1653: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/ComplexKernel.cu.o' failed
2023-05-25T19:50:13.3747260Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/ComplexKernel.cu.o] Error 139
2023-05-25T19:50:18.1706902Z Segmentation fault (core dumped)
2023-05-25T19:50:18.1713054Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1975: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Embedding.cu.o' failed
2023-05-25T19:50:18.1713786Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Embedding.cu.o] Error 139
2023-05-25T19:50:26.1047444Z /var/lib/jenkins/workspace/aten/src/ATen/cuda/cub.cuh: In instantiation of ‘void at::cuda::cub::unique_by_key(KeysInputIteratorT, ValuesInputIteratorT, KeysOutputIteratorT, ValuesOutputIteratorT, NumSelectedIteratorT, int64_t) [with KeysInputIteratorT = const int*; ValuesInputIteratorT = thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>; KeysOutputIteratorT = std::nullptr_t; ValuesOutputIteratorT = int*; NumSelectedIteratorT = long int*; int64_t = long int]’:
2023-05-25T19:50:26.1049099Z /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/EmbeddingBackwardKernel.cu:244:1185:   required from here
2023-05-25T19:50:26.1050261Z /var/lib/jenkins/workspace/aten/src/ATen/cuda/cub.cuh:170:1: warning: parameter ‘keys_out’ set but not used [-Wunused-but-set-parameter]
2023-05-25T19:50:26.1052584Z    KeysOutputIteratorT keys_out, ValuesOutputIteratorT values_out,
2023-05-25T19:50:26.1053020Z  ^ ~~~~~~
2023-05-25T19:50:26.1055162Z /var/lib/jenkins/workspace/aten/src/ATen/cuda/cub.cuh: In instantiation of ‘void at::cuda::cub::unique_by_key(KeysInputIteratorT, ValuesInputIteratorT, KeysOutputIteratorT, ValuesOutputIteratorT, NumSelectedIteratorT, int64_t) [with KeysInputIteratorT = const long int*; ValuesInputIteratorT = thrust::counting_iterator<int, thrust::use_default, thrust::use_default, thrust::use_default>; KeysOutputIteratorT = std::nullptr_t; ValuesOutputIteratorT = long int*; NumSelectedIteratorT = long int*; int64_t = long int]’:
2023-05-25T19:50:26.1056677Z /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/EmbeddingBackwardKernel.cu:244:2193:   required from here
2023-05-25T19:50:26.1057709Z /var/lib/jenkins/workspace/aten/src/ATen/cuda/cub.cuh:170:1: warning: parameter ‘keys_out’ set but not used [-Wunused-but-set-parameter]
2023-05-25T19:50:41.6908673Z Segmentation fault (core dumped)
2023-05-25T19:50:41.6915266Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1947: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Distributions.cu.o' failed
2023-05-25T19:50:41.6915766Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/Distributions.cu.o] Error 139
2023-05-25T19:50:41.6916223Z make[2]: Leaving directory '/var/lib/jenkins/cpp-build/caffe2/build'
2023-05-25T19:50:41.6917181Z CMakeFiles/Makefile2:6791: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/all' failed
2023-05-25T19:50:41.6917710Z make[1]: *** [caffe2/CMakeFiles/torch_cuda.dir/all] Error 2
2023-05-25T19:50:41.6918316Z make[1]: Leaving directory '/var/lib/jenkins/cpp-build/caffe2/build'
2023-05-25T19:50:41.6920314Z Makefile:145: recipe for target 'all' failed
2023-05-25T19:50:41.6920703Z make: *** [all] Error 2
2023-05-25T19:50:41.7423219Z + sccache_epilogue
2023-05-25T19:50:41.7423662Z + echo '::group::Sccache Compilation Log'
2023-05-25T19:50:41.7424398Z ##[group]Sccache Compilation Log
2023-05-25T19:50:41.7424729Z + echo '=================== sccache compilation log ==================='
2023-05-25T19:50:41.7425003Z =================== sccache compilation log ===================
2023-05-25T19:50:41.7425353Z + python /var/lib/jenkins/workspace/.ci/pytorch/print_sccache_log.py /var/lib/jenkins/sccache_error.log
2023-05-25T19:50:41.7587745Z [0m[1m[31mERROR[0m 2023-05-25T19:50:09Z: sccache::server: Compilation failed: Output { status: ExitStatus(unix_wait_status(35584)), stdout: "", stderr: "Segmentation fault (core dumped)\n" }
2023-05-25T19:50:41.7588269Z 
2023-05-25T19:50:41.7588704Z [0m[1m[31mERROR[0m 2023-05-25T19:50:11Z: sccache::server: Compilation failed: Output { status: ExitStatus(unix_wait_status(35584)), stdout: "", stderr: "Segmentation fault (core dumped)\n" }
2023-05-25T19:50:41.7588998Z 
2023-05-25T19:50:41.7589420Z [0m[1m[31mERROR[0m 2023-05-25T19:50:13Z: sccache::server: Compilation failed: Output { status: ExitStatus(unix_wait_status(35584)), stdout: "", stderr: "Segmentation fault (core dumped)\n" }
2023-05-25T19:50:41.7589689Z 
2023-05-25T19:50:41.7590173Z [0m[1m[31mERROR[0m 2023-05-25T19:50:18Z: sccache::server: Compilation failed: Output { status: ExitStatus(unix_wait_status(35584)), stdout: "", stderr: "Segmentation fault (core dumped)\n" }
2023-05-25T19:50:41.7590450Z 
2023-05-25T19:50:41.7590878Z [0m[1m[31mERROR[0m 2023-05-25T19:50:41Z: sccache::server: Compilation failed: Output { status: ExitStatus(unix_wait_status(35584)), stdout: "", stderr: "Segmentation fault (core dumped)\n" }
2023-05-25T19:50:41.7591155Z 
2023-05-25T19:50:41.7610095Z + echo '=========== If your build fails, please take a look at the log above for possible reasons ==========='
2023-05-25T19:50:41.7610453Z =========== If your build fails, please take a look at the log above for possible reasons ===========
```

### Versions

2.1.0 nightly 

cc @ngimel @seemethere @malfet @pytorch/pytorch-dev-infra @ptrblck

**Comment by malfet** [comment] 2023-05-26 16:48
Looks like an ICE to me, but considering that all binary builds are green, and gcc-7.5 was released in 2019, no reason not to update to gcc-8.5 or even gcc-9 for our bionic jobs.

**Comment by atalman** [comment] 2023-05-26 18:09
Good, point let me look into updating to later gcc version

**Comment by atalman** [comment] 2023-06-01 16:20
Same failure on different runner type linux.2xlarge
```
system=/var/lib/jenkins/workspace/cmake/../third_party/cudnn_frontend/include -Xfatbin -compress-all -DONNX_NAMESPACE=onnx_torch -gencode arch=compute_52,code=sm_52 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -Xfatbin -compress-all -Wno-deprecated-gpu-targets --expt-extended-lambda -DCUB_WRAPPED_NAMESPACE=at_cuda_detail -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__  -g -lineinfo --source-in-ptx -Xcompiler=-fPIC -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -Xcompiler=-Wall,-Wextra,-Wno-unused-parameter,-Wno-unused-function,-Wno-unused-result,-Wno-missing-field-initializers,-Wno-unknown-pragmas,-Wno-type-limits,-Wno-array-bounds,-Wno-unknown-pragmas,-Wno-strict-overflow,-Wno-strict-aliasing,-Wno-missing-braces,-Wno-maybe-uninitialized -std=c++17 -MD -MT caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistributionNormal.cu.o -MF CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistributionNormal.cu.o.d -x cu -c /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/DistributionNormal.cu -o CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistributionNormal.cu.o
2023-06-01T16:13:35.3916144Z Segmentation fault (core dumped)
2023-06-01T16:13:35.3923120Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1654: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/ComplexKernel.cu.o' failed
2023-06-01T16:13:35.3923946Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/ComplexKernel.cu.o] Error 139
2023-06-01T16:13:35.3924468Z make[2]: *** Waiting for unfinished jobs....
2023-06-01T16:13:37.6238379Z Segmentation fault (core dumped)
2023-06-01T16:13:37.6246381Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1822: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistanceKernel.cu.o' failed
2023-06-01T16:13:37.6247243Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistanceKernel.cu.o] Error 139
2023-06-01T16:13:38.4279368Z Segmentation fault (core dumped)
2023-06-01T16:13:38.4284615Z caffe2/CMakeFiles/torch_cuda.dir/build.make:1850: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistributionCauchyKernel.cu.o' failed
2023-06-01T16:13:38.4285156Z make[2]: *** [caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistributionCauchyKernel.cu.o] Error 139
2023-06-01T16:13:47.0955006Z make[2]: Leaving directory '/var/lib/jenkins/cpp-build/caffe2/build'
2023-06-01T16:13:47.0956261Z CMakeFiles/Makefile2:6793: recipe for target 'caffe2/CMakeFiles/torch_cuda.dir/all' failed
2023-06-01T16:13:47.0956591Z make[1]: *** [caffe2/CMakeFiles/torch_cuda.dir/all] Error 2
2023-06-01T16:13:47.0956962Z make[1]: Leaving directory '/var/lib/jenkins/cpp-build/caffe2/build'
2023-06-01T16:13:47.0960513Z Makefile:145: recipe for target 'all' failed
2023-06-01T16:13:47.0960760Z make: *** [all] Error 2
2023-06-01T16:13:47.5822134Z + sccache_epilogue
2023-06-01T16:13:47.5822650Z + echo '::group::Sccache Compilation Log'
2023-06-01T16:13:47.5823347Z ##[group]Sccache Compilation Log
2023-06-01T16:13:47.5823726Z + echo '=================== sccache compilation log ==================='
2023-06-01T16:13:47.5824226Z =================== sccache compilation log ===================
```

**Comment by ptrblck** [comment] 2023-06-01 16:28
I tried the originally reported segmentation fault in different ways using a current CUDA 12.1 base container and replaced the used compiler with gcc-7 which wasn't failing and built PyTorch successfully.

Next I used the container from the failing job ([ghcr.io/pytorch/ci-image:pytorch-linux-bionic-cuda12.1-cudnn8-py3-gcc7-8b91b1ce8130db8f9c7e2968ea36d364e4105ed1](http://ghcr.io/pytorch/ci-image:pytorch-linux-bionic-cuda12.1-cudnn8-py3-gcc7-8b91b1ce8130db8f9c7e2968ea36d364e4105ed1)) and tried to reproduce it there.
I needed to get rid of the cache (e.g. using the `/usr/bin/c++` instead of `/opt/cache/bin/c++`) as the latter was timing out so I guess it tried to connect to your internal caching. (same for `nvcc`)
Afterwards I built PyTorch via `CUDA_HOME=/usr/local/cuda TORCH_CUDA_ARCH_LIST="5.2" python setup.py install` and was also not able to reproduce the segfault.

I guess I might be missing something so please let me know if you see any issues in my workflow trying to reproduce it.

**Comment by malfet** [comment] 2023-06-01 17:50
Ok, I can reliable reproduce the crash in the container, by running:
```bash
cd /var/lib/jenkins/cpp-build/caffe2/build/caffe2 && /opt/cache/bin/sccache /usr/local/cuda/bin/nvcc -forward-unknown-to-host-compiler -DAT_PER_OPERATOR_HEADERS -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DIDEEP_USE_MKL -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DTORCH_CUDA_BUILD_MAIN_LIB -DTORCH_ENABLE_LLVM -DUSE_C10D_GLOO -DUSE_C10D_MPI -DUSE_C10D_NCCL -DUSE_CUDA -DUSE_DISTRIBUTED -DUSE_EXPERIMENTAL_CUDNN_V8_API -DUSE_EXTERNAL_MZCRC -DUSE_FLASH_ATTENTION -DUSE_NCCL -DUSE_RPC -DUSE_TENSORPIPE -D_FILE_OFFSET_BITS=64 -Dtorch_cuda_EXPORTS -I/var/lib/jenkins/cpp-build/caffe2/build/aten/src -I/var/lib/jenkins/workspace/aten/src -I/var/lib/jenkins/cpp-build/caffe2/build -I/var/lib/jenkins/workspace -I/var/lib/jenkins/workspace/cmake/../third_party/benchmark/include -I/opt/llvm/include -I/var/lib/jenkins/workspace/third_party/onnx -I/var/lib/jenkins/cpp-build/caffe2/build/third_party/onnx -I/var/lib/jenkins/workspace/third_party/foxi -I/var/lib/jenkins/cpp-build/caffe2/build/third_party/foxi -I/var/lib/jenkins/workspace/aten/src/THC -I/var/lib/jenkins/workspace/aten/src/ATen/cuda -I/var/lib/jenkins/workspace/aten/src/ATen/../../../third_party/cutlass/include -I/var/lib/jenkins/cpp-build/caffe2/build/caffe2/aten/src -I/var/lib/jenkins/workspace/aten/src/ATen/.. -I/var/lib/jenkins/cpp-build/caffe2/build/nccl/include -I/var/lib/jenkins/workspace/c10/cuda/../.. -I/var/lib/jenkins/workspace/c10/.. -I/var/lib/jenkins/workspace/third_party/tensorpipe -I/var/lib/jenkins/cpp-build/caffe2/build/third_party/tensorpipe -I/var/lib/jenkins/workspace/third_party/tensorpipe/third_party/libnop/include -I/var/lib/jenkins/workspace/torch/csrc/api -I/var/lib/jenkins/workspace/torch/csrc/api/include -isystem=/var/lib/jenkins/cpp-build/caffe2/build/third_party/gloo -isystem=/var/lib/jenkins/workspace/cmake/../third_party/gloo -isystem=/var/lib/jenkins/workspace/cmake/../third_party/googletest/googlemock/include -isystem=/var/lib/jenkins/workspace/cmake/../third_party/googletest/googletest/include -isystem=/var/lib/jenkins/workspace/third_party/protobuf/src -isystem=/opt/conda/envs/py_3.10/include -isystem=/var/lib/jenkins/workspace/third_party/gemmlowp -isystem=/var/lib/jenkins/workspace/third_party/neon2sse -isystem=/var/lib/jenkins/workspace/third_party/XNNPACK/include -isystem=/var/lib/jenkins/workspace/third_party/ittapi/include -isystem=/var/lib/jenkins/workspace/cmake/../third_party/eigen -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include/openmpi/opal/mca/event/libevent2022/libevent/include -isystem=/usr/lib/x86_64-linux-gnu/openmpi/include -isystem=/usr/local/cuda/include -isystem=/var/lib/jenkins/workspace/third_party/ideep/mkl-dnn/third_party/oneDNN/include -isystem=/var/lib/jenkins/workspace/third_party/ideep/include -isystem=/var/lib/jenkins/workspace/third_party/ideep/mkl-dnn/include -isystem=/var/lib/jenkins/workspace/cmake/../third_party/cudnn_frontend/include -Xfatbin -compress-all -DONNX_NAMESPACE=onnx_torch -gencode arch=compute_52,code=sm_52 -Xcudafe --diag_suppress=cc_clobber_ignored,--diag_suppress=set_but_not_used,--diag_suppress=field_without_dll_interface,--diag_suppress=base_class_has_different_dll_interface,--diag_suppress=dll_interface_conflict_none_assumed,--diag_suppress=dll_interface_conflict_dllexport_assumed,--diag_suppress=bad_friend_decl --expt-relaxed-constexpr --expt-extended-lambda -Xfatbin -compress-all -Wno-deprecated-gpu-targets --expt-extended-lambda -DCUB_WRAPPED_NAMESPACE=at_cuda_detail -DCUDA_HAS_FP16=1 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__  -g -lineinfo --source-in-ptx -Xcompiler=-fPIC -DCAFFE2_USE_GLOO -DTH_HAVE_THREAD -Xcompiler=-Wall,-Wextra,-Wno-unused-parameter,-Wno-unused-function,-Wno-unused-result,-Wno-missing-field-initializers,-Wno-unknown-pragmas,-Wno-type-limits,-Wno-array-bounds,-Wno-unknown-pragmas,-Wno-strict-overflow,-Wno-strict-aliasing,-Wno-missing-braces,-Wno-maybe-uninitialized -std=c++17 -MD -MT caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistanceKernel.cu.o -MF CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistanceKernel.cu.o.d -x cu -c /var/lib/jenkins/workspace/aten/src/ATen/native/cuda/DistanceKernel.cu -o CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/DistanceKernel.cu.o
```

**Comment by malfet** [comment] 2023-06-01 20:35
Removing `--source-in-ptx` fixed the crash, will propose change soon

**Closed** 2023-06-01 23:11 UTC
Labels: module: cuda, module: ci, triaged

**Comment by malfet** [comment] 2023-06-05 13:56
@MatthiasKohl sorry, I should've mentioned it in PR description: when CUDA language is used in cmake nvcc flags inherit from c++ flags, so -g was passed twice.
