### ISSUE TITLE
[Feature Request] Make nn layers accept empty batch size

### ISSUE THREAD

**Issue by fmassa** [pytorch/pytorch#12013] opened 2018-09-24 15:39 UTC
Now that we have support for tensors with zero in its size, I believe it would be very handy to have support for accepting batches of size 0 in `nn.functional` functions.

A (non-exhaustive) list of functions that would be good supporting:
- [x] `conv{1-2-3}d`
- [x] `conv_transpose{1-2-3}d`
- [x] `batch_norm`
- [x] `interpolate`

Handling the losses is a bit trickier, because it generally involves computing a `.mean()`, which results in `NaN` due to 0 / 0 division. I'd expect having a 0 loss for empty batches to make sense, but that's debatable so might be worth postponing this decision.

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by bhushan23** [comment] 2018-10-01 04:07
@fmassa what is the use of 0 batch size? What should we support it?

**Comment by fmassa** [comment] 2018-10-01 05:32
@bhushan23 some models (see Detectron Mask R-CNN for example) have a data-dependent generation of batches inside of their model. So even if we pass a fixed number of images, there might be no image which contains (or at least the model doesn't detect) a certain subset of categories, which corresponds to forwarding to a model a batch size of zero.

Another use-cases if when tracing models using the jit. If we support empty batch sizes, the runtime cost for the tracing is reduced, as we don't need to compute convolutions/ poolings anymore, almost if we had shape inference functions for those operations.

More generally, with support for zero-sized tensors, a number of restrictions that we used to have can be removed, and just makes writing code that works in some edge cases a no-brainer

**Comment by fmassa** [comment] 2018-10-03 23:32
@bhushan23 this is not an urgent feature, so no worries. I'm assigning it to you then.

**Comment by lerks** [comment] 2019-01-14 22:19
I'm using empty tensors (as in, some dimension being zero) to define clearer interfaces: sometimes some parts of my network's computation shouldn't be performed; instead of adding boolean flags to (de)activate those parts, I give them empty tensors as inputs.

A good PyTorch support for this would mean a better developer experience for me: now I need explicit checks to handle these cases, which add new codepaths (that could have bugs, need to be tested, and add to the maintenance burden); if I could delegate that to PyTorch, my code would be sleeker.

**Comment by fmassa** [comment] 2019-01-14 22:57
@lerks I totally agree with you, and I do believe having native support for those cases would bring value.

My approach in this case for now was to have special-cased modules which handle tensors with 0 in its dimension, see [here for an example](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/layers/misc.py).

**Comment by pietern** [comment] 2019-01-23 18:53
This would also allow use of `DistributedDataParallel` with empty batches. The workaround @fmassa posted where these layers are wrapped and return a different autograd function if the batch is empty ([this one](https://github.com/facebookresearch/maskrcnn-benchmark/blob/9b53d15c12cca33764ff218f61e95bb52bc7d0f3/maskrcnn_benchmark/layers/misc.py#L17-L26)) does not work with `DistributedDataParallel` because it depends on a fixed set of autograd function hooks. By using a dynamically generated function the existing hooks for these layers will never be called and the worker with the empty batch will hang on the backwards pass waiting for those hooks to be called.

**Comment by ppwwyyxx** [comment] 2019-08-13 06:53
The [workaround](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/layers/misc.py) by @fmassa cannot apply to `nn.SyncBatchNorm`, because all the workers have to enter the layer in order to finish the allgather call. Otherwise the layer will deadlock.

**Comment by fmassa** [comment] 2019-08-13 07:25
We should bump the priority of this feature. It will also simplify the task of having torch script-ready models for object detection

**Comment by raghuramank100** [comment] 2019-08-15 02:49
For quantization support, we are planning on supporting torchvision. Having this support as part of regular torch.nn removes the need to special case torchvision.ops

**Comment by fmassa** [comment] 2019-08-15 06:22
Added needs discussion because bumped the priority to high

**Comment by fmassa** [comment] 2019-09-06 17:47
@bhushan23 any updates on this issue? did you managed to make some progress on it?

**Comment by bhushan23** [comment] 2019-09-06 17:57
@fmassa no. I will work on it over the weekend.

**Comment by fmassa** [comment] 2019-09-09 17:06
Hey @bhushan23 did you managed to make progress on this issue?

It would be good to have it implemented soon, as it is important to a few people like @raghuramank100 and @ppwwyyxx

**Comment by raghuramank100** [comment] 2019-09-09 18:01
Hi @bhushan23 , this is a feature that we need fairly soon, so please let us know if you are able to work on it/need it reviewed etc.

**Comment by bhushan23** [comment] 2019-09-09 18:46
@fmassa I am little confused regarding handling the backward pass and looking into it
forward pass will simply be returning a tensor of expected output shape here https://github.com/pytorch/pytorch/blob/13292ec3c7f47228b93dbef1ca750b66b4b8e0af/aten/src/ATen/native/Convolution.cpp#L512
@raghuramank100 will let you know if I want to pass this on to someone by end of day
@gchanan do you have any idea's on handling backward pass? If we handle this at ATen, then will need to change all the backends to respectively handle 0d shape. Another approach is to handle at python api level (one place)
Issue will later is exposing tensor specific handling to higher level whereas ATen approach is much more concrete and non-exposing

**Comment by bhushan23** [comment] 2019-09-10 07:10
@fmassa @gchanan @raghuramank100 @soumith I don't have enough bandwidth to finish this sooner. I would like someone else to take over.

I tried a small change with [mkldnn](https://github.com/bhushan23/pytorch/commit/ebff27f61ac00036d79ad2dbd062d98773714439) 
Basically, If any one of dimension is 0 then, pass it as it is (we don't need to compute the shape): computing shape is incorrect representation and such a tensors should be ignored during both forward and backward pass.

**Comment by dashesy** [comment] 2019-09-18 18:14
It seems pooling also has problem with empty-batch size

```python
/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    545             result = self._slow_forward(*input, **kwargs)
    546         else:
--> 547             result = self.forward(*input, **kwargs)
    548         for hook in self._forward_hooks.values():
    549             hook_result = hook(self, input, result)

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/pooling.pyc in forward(self, input)
    139         return F.max_pool2d(input, self.kernel_size, self.stride,
    140                             self.padding, self.dilation, self.ceil_mode,
--> 141                             self.return_indices)
    142
    143

/usr/local/lib/python2.7/dist-packages/torch/_jit_internal.pyc in fn(*args, **kwargs)
    132             return if_true(*args, **kwargs)
    133         else:
--> 134             return if_false(*args, **kwargs)
    135
    136     if if_true.__doc__ is None and if_false.__doc__ is not None:

/usr/local/lib/python2.7/dist-packages/torch/nn/functional.pyc in _max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode, return_indices)
    485         stride = torch.jit.annotate(List[int], [])
    486     return torch.max_pool2d(
--> 487         input, kernel_size, stride, padding, dilation, ceil_mode)
    488
    489 max_pool2d = boolean_dispatch(

RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

```

This is the input tensor `tensor([], size=(0, 64, 112, 112))`

**Comment by dashesy** [comment] 2019-11-11 18:31
I have an input and model that I get `Floating point exception` and segfault when a tensor is empty. Ideally empty tensors should just be short-circuit to empty outputs, but at least there should be no segfault.

**Comment by kurtamohler** [comment] 2019-12-06 17:53
I just assigned this issue to myself, but if someone else is working on it, please let me know.

**Comment by kurtamohler** [comment] 2019-12-06 19:19
Actually, after looking more into this, I think this issue might be a bit too involved for me at this point since I only started working on PyTorch a week ago.

**Comment by v0dro** [comment] 2019-12-17 09:33
I'm thinking of working on this issue. Starting with `ConvTranspose1d`, do you think this code would be a useful way of reproducing the issue? Would be a good starting point for a test.

``` python
import torch

y = torch.ones(1,1,1)
d1 = torch.nn.ConvTranspose1d(1, 1, 3)
d1.weight.data = torch.ones(1,1,3)
b = torch.tensor(2)
x = d1(b)

print(x)
```

Also, @fmassa says that the `conv_{1,2,3}d` NN's currently accept 0-dim tensors but I'm unable to find a PR that says so and the current pytorch on conda does not seem to allow it either. Can you please point me to where this has been implemented?

**Comment by v0dro** [comment] 2019-12-19 09:56
Changing `ConvTranspose1d` to work with 0 dimensional tensors.

# Problem
The ConvTranspose1d throws errors when you give it 0-dimensional tensors as input.
This should be made possible because there are cases where you have parts of an image
without any feature and you want to be able to pass them through the layer without
writing any edge case handling code.

The solution should involve working with tensors that have 0-dim in any dimension.

A sample failing program is as follows:
``` python
import torch 
 
y = torch.ones(1,1,1) 
d1 = torch.nn.ConvTranspose1d(1, 1, 3) 
d1.weight.data = torch.ones(1,1,3) 
b = torch.ones([]) 
q = d1(b)
```

# Literature Survey

## Previous Work

[This](https://github.com/facebookresearch/maskrcnn-benchmark/blob/master/maskrcnn_benchmark/layers/misc.py) link has some details of a workaround for the problem by writing wrapper autograd
functions around `ConvTraspose1d`. It works by intercepting the `forward` and `backward` functions.
The `forward` function simply returns a new empty tensor of a different calculated shape.
I have not been able to make the `backward` work out of the box in that file since the
tensor object returned by the `forward` does not have a `grad\_fn` and therefore leads
to error:
```
RuntimeError: element 0 of tensors does not require grad and does not have a grad\_fn
```

A very simple C++-level effort to make the forward pass for the MKLDNN backend work
has been proposed [here](https://github.com/bhushan23/pytorch/commit/ebff27f61ac00036d79ad2dbd062d98773714439) but it does not have a lot of code worth talking about.

A comment [here](https://github.com/pytorch/pytorch/issues/12013#issuecomment-529614705) states some
suggestions for implementing backward pass.

# Goals

Can be roughly split into goals:
* Change the forward differentiation to handle 0-dim tensor input.
* Change the backward differentiation to handle empty gradient produced from 0-dim forward pass.

**Comment by v0dro** [comment] 2019-12-22 11:53
Past work: https://github.com/pytorch/pytorch/pull/26214

**Comment by v0dro** [comment] 2019-12-30 10:57
I'm working on the `batch_norm` now and have a doubt regarding the batch norm layer accepting 0 dim input size.

It seems that `BatchNorm1d` already works for 0-dim input. Here's the sample code:
```
import torch

bn = torch.nn.BatchNorm1d(5)
x = torch.ones(0,5)
bn(x)
#=> tensor([], size=(0, 5), grad_fn=<NativeBatchNormBackward>)
```

Can please clarify with a minimal example how the batch norm issue is supposed to work?

**Comment by gchanan** [comment] 2019-12-30 15:20
@v0dro: that looks correct.  You probably want to also check 3-dimensional inputs for BatchNorm1d, and the correct input sizes for BatchNorm2d, BatchNorm3d.

**Comment by ppwwyyxx** [comment] 2019-12-31 02:51
Another issue with BatchNorm is how to update its moving_mean and moving_variance in case of 0-batchsize inputs. There is no convention but I would argue that the correct way is to leave them not updated.

**Comment by v0dro** [comment] 2019-12-31 05:37
Regarding the running mean and var:

``` python
import torch

bn = torch.nn.BatchNorm1d(5)
x = torch.ones(0,5,9)
bn(x)
# tensor([], size=(0, 5, 9), grad_fn=<NativeBatchNormBackward>)

bn.running_mean   
# tensor([nan, nan, nan, nan, nan])

bn.running_var
# tensor([0.9000, 0.9000, 0.9000, 0.9000, 0.9000])
```
Considering that the 0-dim is not actually supposed to 'do' anything I don't think the running variables should be updated. Thoughts?

**Comment by v0dro** [comment] 2019-12-31 06:36
About 2D and 3D batch norm:
``` python
import torch

bn = torch.nn.BatchNorm2d(5) 
print(bn.running_mean) 
print(bn.running_var) 
x = torch.ones(0,5,2,2) 
bn(x) 
print(bn.running_var) 
print(bn.running_mean)

# tensor([0., 0., 0., 0., 0.])
# tensor([1., 1., 1., 1., 1.])
# tensor([0.9000, 0.9000, 0.9000, 0.9000, 0.9000])
# tensor([nan, nan, nan, nan, nan])
```

For the 3D case:
``` python
import torch

bn = torch.nn.BatchNorm3d(5) 
print(bn.running_mean) 
print(bn.running_var) 
x = torch.ones(0,5,2,2,2) 
bn(x) 
print(bn.running_var) 
print(bn.running_mean)

# tensor([0., 0., 0., 0., 0.])
# tensor([1., 1., 1., 1., 1.])
# tensor([0.9000, 0.9000, 0.9000, 0.9000, 0.9000])
# tensor([nan, nan, nan, nan, nan])
```

**Comment by ppwwyyxx** [comment] 2019-12-31 06:51
Backward also needs to be tested:
```python
import torch
bn = torch.nn.BatchNorm2d(5)
x = torch.ones(0,5,2,2)
x.requires_grad = True
y = bn(x)
y.sum().backward()
print(y)  # correct
print(bn.running_var)  # wrong
print(bn.running_mean)  # wrong
print(x.grad)  # correct
print(bn.weight.grad)  # wrong
print(bn.bias.grad)  # correct

#tensor([], size=(0, 5, 2, 2), grad_fn=<NativeBatchNormBackward>)
#tensor([0.9000, 0.9000, 0.9000, 0.9000, 0.9000]) expect 1
#tensor([nan, nan, nan, nan, nan]) expect 0
#tensor([], size=(0, 5, 2, 2))
#tensor([nan, nan, nan, nan, nan]) expect 0
#tensor([0., 0., 0., 0., 0.])
```

**Comment by v0dro** [comment] 2019-12-31 08:32
Works. So in summary, for the batch norm the fix is centered around the running variables.

**Comment by v0dro** [comment] 2020-01-18 06:20
The behaviour seems to have changed in the current master.  Here's my program:
``` python
import torch

print("-----BatchNorm2d-----")
bn = torch.nn.BatchNorm2d(5)
x = torch.ones(0,5,2,2, requires_grad=True)
y = bn(x)
print("\tFORWARD PASS:")
print("\t\ty: ", y)
print("\t\trunning mean: ", bn.running_mean)
print("\t\trunning var: ", bn.running_var)
y.sum().backward()
print("\tBACKWARD PASS:")
print("\t\tweight grad: ", bn.weight.grad)
print("\t\tbias grad: ", bn.bias.grad)
```

And this is the output:
```
-----BatchNorm2d-----
	FORWARD PASS:
		y:  tensor([], size=(0, 5, 2, 2), requires_grad=True)
		running mean:  tensor([0., 0., 0., 0., 0.])
		running var:  tensor([1., 1., 1., 1., 1.])
	BACKWARD PASS:
		weight grad:  None
		bias grad:  None
```

@ezyang @rgommers can you please comment whether this behaviour is alright? The issue is already solved if yes.

**Comment by ppwwyyxx** [comment] 2020-01-19 02:29
The expected behavior for backward was given above in https://github.com/pytorch/pytorch/issues/12013#issuecomment-569876108

**Comment by v0dro** [comment] 2020-01-19 07:03
@ppwwyyxx will correct.

Meanwhile here is the 0-dim for interpolate: https://github.com/pytorch/pytorch/pull/32400

**Comment by ngimel** [comment] 2020-01-31 01:46
All flavors of convolution and batch norm now correctly handle empty batches and return zero gradients for parameters.

**Comment by v0dro** [comment] 2020-02-03 18:40
Should close this one subject to merging of #32384

**Comment by v0dro** [comment] 2020-02-04 03:48
Closing since all relevant PRs have been merged.

**Comment by dashesy** [comment] 2020-02-04 20:50
@v0dro thanks. Are empty batch sizes also supported for pooling now? this was the error before:

>    489 max_pool2d = boolean_dispatch(
> RuntimeError: non-empty 3D or 4D input tensor expected but got ndim: 4

**Comment by ppwwyyxx** [comment] 2020-03-14 07:24
I found that `Linear` still does not work for empty batch on master.
```
    import torch

    x = torch.randn(0, 3).cuda()
    w = torch.randn(3, 3).cuda()
    b = torch.randn(3).cuda()
    w.requires_grad = True
    b.requires_grad = True
    z = torch.addmm(b, x, w.t())
    loss = z.sum()
    loss.backward()
```
gives an error of 
```
RuntimeError: at::cuda::blas::gemm<float> argument ldb must be positive and less than 2147483647 but got 0 (gemm at caffe2/aten/src/ATen/cuda/CUDABlas.cpp:163)                                    
```

**Comment by rgommers** [comment] 2020-03-16 20:05
> A (non-exhaustive) list of functions ...

The _non-exhaustive_ seems important here - the listed functions in the PR description were all done, but no triaging of other functions happened.

Perhaps needs a generic test for all functions in the `nn.functional` namespace?

**Comment by v0dro** [comment] 2020-04-16 07:38
I'll prepare a list of NN modules that still don't support 0-size batches.

**Comment by v0dro** [comment] 2020-04-24 06:42
I'm in the process of building this list. Its rather large and am still building it but comments are welcome.

# Survey of various layers

## Linear

Status: works :heavy_check_mark: 

``` python
z = torch.ones(0, 3, 10, 10)
w = torch.ones(10,10)

# Linear
lin = torch.nn.Linear(10, 10)
lin_b = lin(z)
lin_b.sum().backward() # WORKS
```

## Bilinear

Status: :negative_squared_cross_mark: 

``` python
z = torch.ones(0, 3, 10, 10)
bil = torch.nn.Bilinear(10, 10, 10)
bil_b = bil(z, z)
bil_b.sum().backward() # DOES NOT WORK
```

## AdaptiveAvgPool2d

Status: :negative_squared_cross_mark: 

``` python
z = torch.ones(0, 3, 10, 10)
avg_p2 = torch.nn.AdaptiveAvgPool2d((5,5))
avg_p2(z)
```

## AdaptiveAvgPool3d

Status: :negative_squared_cross_mark: 

``` python
z = torch.ones(0, 3, 10, 10, 10)
p3 = torch.nn.AdaptiveAvgPool2d((5,5,5))
p3(z)
```

## AlphaDropout

Status: works :heavy_check_mark: 

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.AlphaDropout(p=0.3)
m(z)
```

## AvgPool2d

Status: not working :negative_squared_cross_mark: 

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.AvgPool2d((3,3))
m(z)
```

## Bilinear

Status: not working :negative_squared_cross_mark: 

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Bilinear(10,10,10)
m(z)
```

## CELU

Status: works

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.CELU()
m(z)
```

## ConstantPad2d

Status: works

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ConstantPad2d(2,3.5)
m(z)
```

## CrossEntropyLoss

``` python
z = torch.ones(0,3,10,10)
```

## Dropout


``` python
z = torch.ones(0,3,10,10)
```

## Dropout2d

``` python
z = torch.ones(0,3,10,10)
```

## ELU

``` python
z = torch.ones(0,3,10,10)
```

## Embedding

``` python
z = torch.ones(0,3,10,10)
```

## EmbeddingBag

``` python
z = torch.ones(0,3,10,10)
```

## FeatureAlphaDropout

``` python
z = torch.ones(0,3,10,10)
```

## Flatten

``` python
z = torch.ones(0,3,10,10)
```

## FractionalMaxPool2d

``` python
z = torch.ones(0,3,10,10)
```

## GLU

``` python
z = torch.ones(0,3,10,10)
```

## GRU

``` python
z = torch.ones(0,3,10,10)
```

## GroupNorm

``` python
z = torch.ones(0,3,10,10)
```

## Hardshrink

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Hardshrink
m(z)
```

## Hardtanh

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Hardtanh
m(z)
```

## HingeEmbeddingLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.HingeEmbeddingLoss
m(z)
```

## Identity

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Identity
m(z)
```

## InstanceNorm1d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.InstanceNorm1d
m(z)
```

## InstanceNorm2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.InstanceNorm2d
m(z)
```

## InstanceNorm3d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.InstanceNorm3d
m(z)
```

## KLDivLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.KLDivLoss
m(z)
```

## L1Loss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.L1Loss
m(z)
```

## LPPool1d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LPPool1d
m(z)
```

## LPPool2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LPPool2d
m(z)
```

## LSTM

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LSTM
m(z)
```

## LSTMCell

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LSTMCell
m(z)
```

## LayerNorm

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LayerNorm
m(z)
```

## LeakyReLU

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LeakyReLU
m(z)
```

## Linear

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Linear
m(z)
```

## LocalResponseNorm

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LocalResponseNorm
m(z)
```

## LogSigmoid

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LogSigmoid
m(z)
```

## LogSoftmax

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.LogSoftmax
m(z)
```

## MSELoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MSELoss
m(z)
```

## MarginRankingLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MarginRankingLoss
m(z)
```

## MaxPool1d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MaxPool1d
m(z)
```

## MaxPool2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MaxPool2d
m(z)
```

## MaxPool3d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MaxPool3d
m(z)
```

## MaxUnpool1d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MaxUnpool1d
m(z)
```

## MaxUnpool2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MaxUnpool2d
m(z)
```

## MaxUnpool3d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MaxUnpool3d
m(z)
```

## Module

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Module
m(z)
```

## ModuleDict

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ModuleDict
m(z)
```

## ModuleList

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ModuleList
m(z)
```

## MultiLabelMarginLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MultiLabelMarginLoss
m(z)
```

## MultiLabelSoftMarginLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MultiLabelSoftMarginLoss
m(z)
```

## MultiMarginLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MultiMarginLoss
m(z)
```

## MultiheadAttention

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.MultiheadAttention
m(z)
```

## NLLLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.NLLLoss
m(z)
```

## NLLLoss2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.NLLLoss2d
m(z)
```

## PReLU

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.PReLU
m(z)
```

## PairwiseDistance

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.PairwiseDistance
m(z)
```

## Parameter

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Parameter
m(z)
```

## ParameterDict

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ParameterDict
m(z)
```

## ParameterList

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ParameterList
m(z)
```

## PixelShuffle

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.PixelShuffle
m(z)
```

## PoissonNLLLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.PoissonNLLLoss
m(z)
```

## RNN

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.RNN
m(z)
```

## RNNBase

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.RNNBase
m(z)
```

## RNNCell

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.RNNCell
m(z)
```

## RNNCellBase

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.RNNCellBase
m(z)
```

## RReLU

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.RReLU
m(z)
```

## ReLU

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ReLU
m(z)
```

## ReLU6

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ReLU6
m(z)
```

## ReflectionPad1d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ReflectionPad1d
m(z)
```

## ReflectionPad2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ReflectionPad2d
m(z)
```

## ReplicationPad1d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ReplicationPad1d
m(z)
```

## ReplicationPad2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ReplicationPad2d
m(z)
```

## ReplicationPad3d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ReplicationPad3d
m(z)
```

## SELU

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.SELU
m(z)
```

## Sequential

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Sequential
m(z)
```

## Sigmoid

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Sigmoid
m(z)
```

## SmoothL1Loss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.SmoothL1Loss
m(z)
```

## SoftMarginLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.SoftMarginLoss
m(z)
```

## Softmax

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Softmax
m(z)
```

## Softmax2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Softmax2d
m(z)
```

## Softmin

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Softmin
m(z)
```

## Softplus

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Softplus
m(z)
```

## Softshrink

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Softshrink
m(z)
```

## Softsign

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Softsign
m(z)
```

## SyncBatchNorm

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.SyncBatchNorm
m(z)
```

## Tanh

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Tanh
m(z)
```

## Tanhshrink

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Tanhshrink
m(z)
```

## Threshold

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Threshold
m(z)
```

## Transformer

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Transformer
m(z)
```

## TransformerDecoder

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.TransformerDecoder
m(z)
```

## TransformerDecoderLayer

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.TransformerDecoderLayer
m(z)
```

## TransformerEncoder

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.TransformerEncoder
m(z)
```

## TransformerEncoderLayer

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.TransformerEncoderLayer
m(z)
```

## TripletMarginLoss

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.TripletMarginLoss
m(z)
```

## Unfold

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Unfold
m(z)
```

## Upsample

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.Upsample
m(z)
```

## UpsamplingBilinear2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.UpsamplingBilinear2d
m(z)
```

## UpsamplingNearest2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.UpsamplingNearest2d
m(z)
```

## ZeroPad2d

``` python
z = torch.ones(0,3,10,10)
m = torch.nn.ZeroPad2d
m(z)
```

**Comment by v0dro** [comment] 2020-05-22 00:28
@rgommers how about we close this one and move the discussion to #38115 ?

**Comment by rgommers** [comment] 2020-05-22 13:01
> @rgommers how about we close this one and move the discussion to #38115 ?

As discussed offline, let's keep this open, close gh-38115, use `<details>` to clean up the large comments so the conversation becomes readable again, and check off all the other layers in the checklist above that we found do support empty batch dim.

Next step here is to fix the currently segfaulting operators (`InstanceNorm*d`). And then there's ~45 other operators left.

**Comment by v0dro** [comment] 2021-09-11 06:23
All models listed in https://github.com/pytorch/pytorch/issues/38115 have been changed to support 0-dim batch tensors so I will close this issue.

**Closed by v0dro** 2021-09-11 06:23 UTC
Labels: high priority, module: nn, triaged, function request

**Comment by rgommers** [comment] 2021-09-13 13:11
Thanks @v0dro!

@thomasjpfan is a size-0 batch dim tested in `ModuleInfo` already? If not, would you agree that that is needed to prevent this issue reoccurring for new layers?

**Comment by thomasjpfan** [comment] 2021-09-13 13:17
> @thomasjpfan is a size-0 batch dim tested in ModuleInfo already? If not, would you agree that that is needed to prevent this issue reoccurring for new layers?

Samples with no batch dimension is not tested in `ModuleInfo` and I agree that it should be included.
