### ISSUE TITLE
conda installation from nighlty causes package conflicts and fails to install PyTorch

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#52751] opened 2021-02-24 17:00 UTC
```shell
PREFIX=/my/prefix
mkdir -p $PREFIX

curl -L -so $PREFIX/miniconda.sh https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh && chmod +x $PREFIX/miniconda.sh && $PREFIX/miniconda.sh -b -p $PREFIX/miniconda && rm $PREFIX/miniconda.sh

export PATH=$PREFIX/miniconda/bin:$PATH

conda install -y -c pytorch-nightly cudatoolkit=11.0 pytorch torchvision
```

Log: 
[condalog.txt](https://github.com/pytorch/pytorch/files/6037596/condalog.txt)

And then torch is not available:
```
>>> import torch
ModuleNotFoundError: No module named 'torch'
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr

**Comment by vadimkantorov** [comment] 2021-02-27 14:13
Is using miniconda3 a problem? Would switching to miniconda4 help?

**Comment by walterddr** [comment] 2021-02-27 15:11
seems like you are using py3.9? did you add `-c=conda-forge` to pytorch installation like it suggested on pytorch.org?

**Comment by vadimkantorov** [comment] 2021-02-27 15:18
No, I'm using py3.8. No, I used `-c pytorch-nightly`, since I wanted to install a nightly version

**Comment by walterddr** [comment] 2021-02-27 16:14
hmm. I can reproduce it but seems like pytorch-cuda11.0 conda package hasn't been updated for a while and it is still on `dev1.8.0.dev` tag.
We has been moved to [pytorch-cuda11.1](https://anaconda.org/pytorch-nightly/pytorch/files). However, there's only cudatoolkit=11.1 in conda-forge channel. so a workaround is
```
conda install cudatoolkit=11.1 -c conda-forge
conda install pytorch torchvision torchaudio -c pytorch-nightly 
```

This will install the correct versions -
```
  pytorch            pytorch-nightly/linux-64::pytorch-1.9.0.dev20210227-py3.8_cuda11.1_cudnn8.0.5_0
  torchaudio         pytorch-nightly/linux-64::torchaudio-0.8.0.dev20210227-py38
  torchvision        pytorch-nightly/linux-64::torchvision-0.9.0.dev20210227-py38_cu111
```

**Comment by walterddr** [comment] 2021-02-27 16:15
FYI ^ @seemethere

**Comment by seemethere** [comment] 2021-02-27 20:51
We’re no longer producing nightly binaries for CUDA 11.0, please consider using CUDA 11.1

**Comment by vadimkantorov** [comment] 2021-02-27 20:57
I guess the official main page should be updated:
![image](https://user-images.githubusercontent.com/1041752/109400054-c1bd1c80-7946-11eb-80d5-7a46021f1e60.png)

**Comment by stas00** [comment] 2021-03-03 01:28
I came here to report the same:
```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu110/torch_nightly.html -U
```
from the the snapshot @vadimkantorov made is very outdated!

It needs to be updated to:
```
pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu111/torch_nightly.html -U
```

Thank you!

**Comment by vadimkantorov** [comment] 2021-03-13 10:10
What is Compute Platform "None"? "CPU only" would be more clear... (another problem for CPU options for ARM, Intel, AMD...)

![image](https://user-images.githubusercontent.com/1041752/111026780-8877b880-83ec-11eb-8c9d-dda6cc95882b.png)

**Comment by seemethere** [comment] 2021-03-15 17:41
I don't disagree that `None` is potentially confusing.

I've submitted https://github.com/pytorch/pytorch.github.io/pull/626 as a fix for that.

**Comment by rgommers** [comment] 2021-05-28 20:10
These reported issues were all resolved:
- Compute platform: `None` was changed to `CPU`
- CUDA 11.0 is no longer displayed on the install widget
- The current install command for the CUDA 10.2 and 11.1 nightlies is currently correct.

<img width="611" alt="image" src="https://user-images.githubusercontent.com/98330/120030445-c6ea4000-bff7-11eb-94d1-df4c7d178b4f.png">

The cuda 11.1 nightlies have a new issue, https://github.com/pytorch/pytorch/issues/52751#issuecomment-787096577 worked 3 months ago, but now there's an issue with the `glibc` dependency in the `torchvision` nightly:
```
The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.33=0
  - feature:|@/linux-64::__glibc==2.33=0
  - cudatoolkit=11.1 -> __glibc[version='>=2.17,<3.0.a0']
  - pytorch -> __glibc[version='>=2.17|>=2.17,<3.0.a0']
  - torchvision -> __glibc[version='>=2.17|>=2.17,<3.0.a0']

Your installed version is: 2.33

Note that strict channel priority may have removed packages required for satisfiability.
```
Leaving out `torchvision` makes everything install smoothly.

**Comment by rgommers** [comment] 2021-05-29 13:28
The `glibc` issue is not pytorch-specific, it also happens for RAPIDS right now. The cause is `channel_priority: strict`, which may give such issues when installing a complex set of dependencies from multiple channels. If you comment that out in `~/.condarc`, the nightlies install smoothly.

For more context on `__glibc`, see https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html.

So, everything in this issue is fixed. I'll close this issue.

> Can PyTorch have actual automated tests that install various configurations of PyTorch from conda on different Docker containers and do some smoke tests?

Tests are run for produced packages, the battery of CI is pretty large. The `__glibc` issue I don't think you can exhaustively run smoke tests for, because there's too many variations: it depends on the glibc version on the users' Linux distro (and there are many different versions that are relevant), as well as `.condarc` settings.

**Closed by rgommers** 2021-05-29 13:28 UTC
Labels: module: binaries, triaged

**Comment by vadimkantorov** [comment] 2021-05-29 13:40
In the past there were already quite a few issues about conda that could have been discovered some basic tests (that seemed missing somehow). E.g. problems with cpu-only/gpu, torchvision reinstalling older torch, this issue and etc.

**Comment by vadimkantorov** [comment] 2021-05-29 13:44
If glibc issue happens frequently, even if it can be fixed by condarc change , I think it should be clearly documented in PyTorch installation instructions (even if it happens for RAPIDS too)

**Comment by rgommers** [comment] 2021-05-29 13:50
Yes, and those hiccups will remain I think - packaging is complex. Effort is probably best spent on structural improvements (e.g. the `cpuonly` issues should be improved by landing https://github.com/pytorch/builder/pull/488) that are known to be necessary, rather than even more CI.

> If glibc issue happens frequently, even if it can be fixed by condarc change , I think it should be clearly documented in PyTorch installation instructions

It's not that frequent, as a search for `__glibc` on this issue tracker will reveal.
