### ISSUE TITLE
vmap not working on tensor indexing

### ISSUE THREAD

**Issue by ZhouMengjie** [pytorch/pytorch#135018] opened 2024-09-03 13:54 UTC
### 🐛 Describe the bug

@functools.partial(torch.vmap, in_dims=0)  # batch
@functools.partial(torch.vmap, in_dims=(None, 0, 0))  # points
@functools.partial(torch.vmap, in_dims=(None, 0, 0))  # observations
@functools.partial(torch.vmap, in_dims=(-1, None, None), out_axes=-1)  # channels
def interpolate_views_selective(
    arrays, point, index):
  point = point.type(arrays.dtype)
  size = torch.tensor(arrays.shape[-2:])
  point = torch.maximum(torch.minimum(point - 0.5, size - 1), 0)
  lower = torch.floor(point).type(torch.int32)
  upper = lower + 1
  w_upper = point - lower
  w_lower = 1.0 - w_upper

  weights = [w_lower, w_upper]
  coords = [lower, upper]
  values = []
  for i, j in itertools.product(range(2), repeat=2):
    w = weights[i][0] * weights[j][1]
    values.append(w * arrays[index, coords[i][0], coords[j][1]])
  return sum(values)

f_proj = interpolate_views_selective(f_images, p2d_views, view_indices)

f_images has the shape of B,V,H,W,D, p2d_vew has the shape of B,N,K,2 view_indices has the shape of B,N,K
this function is used for fast interpolation. when i run to "values.append(w * arrays[index, coords[i][0], coords[j][1]])", i met: RuntimeError: vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.

it seems that in arrays[index, coords[i][0], coords[j][1]], the indexes is automatically convert to scalar with .item() calling. Is there any suggestion to help tackle this issue. This seems to be an easy function but do make me struggle for several days. Many thanks for any help!
   

### Versions

i just use pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
to install the latest version of torch which is compatible to cu11.8

cc @zou3519 @Chillee @samdow @kshitij12345

**Comment by zou3519** [comment] 2024-09-03 18:56
This is a duplicate of https://github.com/pytorch/pytorch/issues/124423. Please voice your support there.

**Closed by zou3519** 2024-09-03 18:56 UTC
Labels: module: vmap, module: functorch
