### ISSUE TITLE
can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by simonm3** [pytorch/pytorch#13568] opened 2018-11-05 13:48 UTC
`x.numpy()`

clearly means I want to convert something to numpy, which is always on the CPU. It is redundant to have to say .cpu().numpy(). The conversion should be automatic rather than throwing an exception. 

In my specific case I have set default tensor type to CUDA because that is what I am using by default - and because it makes it really easy to switch everything to CPU in one line of code without cluttering up the rest of it with passing a device around. However when I call third party software they create a tensor without an explicit type; then try to numpy() it expecting it to be CPU based. I have suggested they add a .cpu() but would be better to fix in pytorch.

**Comment by SsnL** [comment] 2018-11-05 13:58
`.numpy()` shares memory with the input CPU tensor, so `cuda_t.cpu().numpy()` is different with `cpu_t.numpy()` and we want to explicitly ask users to convert to CPU tensor.

**Comment by simonm3** [comment] 2018-11-05 14:55
I am not sure I understand. The warning is only generated for a CUDA tensor
which presumably never has any sharing of cpu memory as it is on the gpu
only. If I have a CUDA tensor and call .numpy() then clearly I want to get
a numpy array on the cpu. There is no circumstance where I would want it to
fail.

**Comment by Balandat** [comment] 2018-11-08 22:55
I guess the concern is that people might start doing in-place modifications to a `cuda_t.numpy()` tensor and then being confused that `cuda_t` remains untouched?

**Comment by rgommers** [comment] 2020-04-25 19:44
There's gh-20778 to add a `force` keyword to `.numpy()`, and gh-36560 which is essentially a duplicate of this issue with more detail/rationale. So I'll close this issue.

**Closed by rgommers** 2020-04-25 19:44 UTC

**Comment by LequanatUCI** [comment] 2020-05-11 18:01
I still encounter this error using colab and torchvision version is 0.5.0. Is there any way to solve this?
Thanks.

**Comment by rgommers** [comment] 2020-05-11 21:10
@LequanatUCI this is still under discussion / TODO. The issue for it is gh-36560, which is still open. This issue is closed simply because it's a duplicate.

**Comment by LequanatUCI** [comment] 2020-05-12 05:19
> @LequanatUCI this is still under discussion / TODO. The issue for it is [gh-36560](https://github.com/pytorch/pytorch/issues/36560), which is still open. This issue is closed simply because it's a duplicate.

Thanks for your quick reply, really appreciate it.
