### ISSUE TITLE
spectral_norm used in RNN causes "parameter types mismatch" in GPU

### ISSUE THREAD

**Issue by oh-y** [pytorch/pytorch#26714] opened 2019-09-24 09:11 UTC
## Issue description
spectral_norm used in `nn.Linear` is okay. But when it's used in `nn.RNN`,there will be a 
```
RuntimeError while running `model = network().cuda()`

Traceback (most recent call last):
  File "/anaconda3/envs/env1/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-66814b2fa07a>", line 1, in <module>
    runfile('example.py')
  File "/home/.pycharm_helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/home/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "example.py", line 17, in <module>
    model = network().cuda()
  File "/anaconda3/envs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 265, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/anaconda3/envs/env1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 193, in _apply
    module._apply(fn)
  File "/anaconda3/envs/env1/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 127, in _apply
    self.flatten_parameters()
  File "/anaconda3/envs/env1/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 123, in flatten_parameters
    self.batch_first, bool(self.bidirectional))
RuntimeError: param_from.type() == param_to.type() ASSERT FAILED at /pytorch/aten/src/ATen/native/cudnn/RNN.cpp:541, please report a bug to PyTorch. parameter types mismatch
```

## Code

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

class network (nn.Module):
    def __init__(self):
        super(network, self).__init__()
        self.sn_rnn = nn.utils.spectral_norm(nn.RNN(20,10,1),name='weight_hh_l0')
        # self.fc = nn.utils.spectral_norm(nn.Linear(20,10), name='weight')
    def forward (self,x):
        # x = F.tanh(self.fc(x))
        out,_ = self.sn_rnn(x)
        return F.log_softmax(out, dim=1)

if __name__ == '__main__':
    x = torch.randn(2, 10, 20).cuda()
    model = network().cuda()
    out= model(x)
    print('end')
```
## Environment
 - PyTorch Version (e.g., 1.0): 1.1.0
 - Python version: 3.6.8
 - CUDA/cuDNN version:  cuda9.0

**Comment by huguyuehuhu** [comment] 2019-09-26 15:04
I came across the same Bug, did this problem be solved? @VitalyFedyunin @pbelevich @oh-y

**Comment by jbschlosser** [comment] 2021-05-18 18:00
Closing as I cannot reproduce this on master.

**Closed by jbschlosser** 2021-05-18 18:00 UTC
Labels: module: nn, triaged
