### ISSUE TITLE
INTERNAL ASSERT FAILED at “/pytorch/aten/src/ATen/native/cuda/Reduce.cuh”:896, please report a bug to PyTorch.

### ISSUE THREAD

**Issue by Algomorph** [pytorch/pytorch#54415] opened 2021-03-22 14:16 UTC
## 🐛 Bug

This bug seems to stem from usage of torch.where (and perhaps some other functions), with the resulting tensors in an inconsistent state (negative dimensions). Subsequent usage of the resulting tensors leads to various errors.

## To Reproduce

I don't have time right now to get this down to a minimal reproducible example, so if you want to reproduce & fix, you'll have to do (quite) some work.

1. Check out my fork of the NeuralTracking repository, https://github.com/Algomorph/NeuralTracking (commit 6b8a10b2536eda26f9b613c3521b2fe4894602ad is where I'm getting the bug right now), install missing packages via python3 pip directly (do not use conda or docker as the README directions say), run CMake (check various flags in CMake gui if unsure), build the install-pip-package target.
2. Download the data I provide [here](https://easyupload.io/4ut2q7) for the "RED_SHORTS" sequence (note that the download link will expire in 30 days after this post).
3. Run the basic_pipepline.py python3 script.

For code sample (which probably won't work without the above context) and further explanation, see this [PyTorch forum post](https://discuss.pytorch.org/t/error-in-torch-where-trying-to-create-tensor-with-negative-dimension-2133151913-2133151913/115583/2) 
 and especially [this answer](https://discuss.pytorch.org/t/error-in-torch-where-trying-to-create-tensor-with-negative-dimension-2133151913-2133151913/115583/3?u=algomorph).

## Expected behavior

No exception...

## Environment

Output from the
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)

Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 460.39
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.1.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.1.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchvision==0.9.0+cu111
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @heitorschueroff

**Comment by malfet** [comment] 2021-03-22 17:11
@Algomorph can you please try if the same is reproducible using cuda10.2 nightly images?

**Comment by Algomorph** [comment] 2021-03-22 21:55
@malfet , would that involve installing an older CUDA on my machine? I'm trying to avoid that.

**Comment by malfet** [comment] 2021-03-22 22:07
@Algomorph no, all CUDA dependencies outside of driver are embedded into pytorch wheel package.

**Comment by Algomorph** [comment] 2021-03-22 22:09
@malfet then will do as soon as I can get to it.

**Comment by vfdev-5** [comment] 2021-03-23 00:21
@Algomorph can you post the content of `graph_clusters_i` according to https://discuss.pytorch.org/t/error-in-torch-where-trying-to-create-tensor-with-negative-dimension-2133151913-2133151913/115583

Direct reproduction of the issue following your description leads to other issues between open3d and cuda ... irreproducible from my side.

**Comment by Algomorph** [comment] 2021-03-24 13:11
@vfdev-5, I see, I had the feeling this wasn't going to be easy. I actually have Open3D built from source with CUDA 11, I believe. I can post the contents of graph_clusters_i for you, but this may or may not lead to the result you expect (e.g. see operations on mask2 in [this forum answer](https://discuss.pytorch.org/t/invalid-shape-dimension-huge-negative-number-on-tensor-masking-operation/114606/3?u=algomorph), where I was dealing with the same code base).

I foresee that posting the contents won't be difficult, but trying my setup with pytorch+cu10 might prove more of a problem than earlier anticipated, since I'd have to install a different version of Open3D. I'll see what I can do, though.

**Comment by Algomorph** [comment] 2021-03-24 13:19
@vfdev-5 , here is the file containing `index_equals_cluster_id` before crash point: https://easyupload.io/1x1net

**Comment by vfdev-5** [comment] 2021-03-24 14:08
@Algomorph as you can check as well, this `index_equals_cluster_id.pt` is malformed and can not be loaded:
```
RuntimeError: Trying to create tensor with negative dimension -1139981731: [-1139981731]
```

I think the way you could debug the issue is to do the following:
```python
model = DeformNet().cuda()

with torch.no_grad():
    model_data = model(
                    source_cuda, target_cuda,
                    graph_nodes_cuda, graph_edges_cuda, graph_edges_weights_cuda, graph_clusters_cuda,
                    pixel_anchors_cuda, pixel_weights_cuda,
                    num_nodes_cuda, intrinsics_cuda,
                    evaluate=True, split="test"
    )
```
and ensure that model has non-inf/nan weights and all inputs (`source_cuda`, `target_cuda,`, etc) are well-formed tensors on the same device and correct dtype.
Maybe, https://github.com/zasdfgbnm/TorchSnooper this could be of help in order to debug data content.

**Comment by Algomorph** [comment] 2021-03-24 19:00
@vfdev-5 , that sounds like a reasonable approach, but I believe I've already checked the `graph_clusters_i` tensor (the only input to generate  `index_equals_cluster_id`) for inf & Nan and it's device. I'll go back and redo this, just to make sure. Do you think that should be sufficient to check? Perhaps we might also benefit from the saved contents of`graph_clusters_i`, since it appears to be in a consistent state but produces the malformed `index_equals_cluster_id` with the `torch.where` clause?

**Comment by vfdev-5** [comment] 2021-03-24 19:11
Yes, after checking complete forward pass of the model, if you can dump a correct tensor of graph_clusters_i that produces bad tensor with torch where, that could be helpful.

**Comment by Algomorph** [comment] 2021-03-26 16:24
@vfdev-5 , [here](https://easyupload.io/yglab5) is the `graph_clusters_i` saved immediately before the error is raised. If I just perform operations on that in a separate shell to produce `index_equals_cluster_id`, everything seems fine. I haven't yet checked the complete forward pass, I'll get back to you on that. My intuition is telling me that's a wild goose chase, though. I think the better approach would be for me to see if I can reproduce it with the stock open3d + cuda10 pytorch, since not having the open3d for CUDA11 is what's holding you up from reproducing this reliably.

**Comment by Algomorph** [comment] 2021-03-26 18:14
So, apparently, stock open3d from PyPI doesn't even come with CUDA, you need to custom-build it. So if you guys don't want to go through the pains of building that just to replicate this, the only thing I can do on my end is to try to dumb down the code on my end and get rid of the open3d depencency, and we're back to square one: I don't want to spend time right now on trying to produce a minimal example.

I can still try to check the complete forward pass for NaNs / Infs and such with TorchSnooper, not sure how much of a time investment on my part that will involve, but as I mentioned before, that unlikely to yield any beneficial result: seeing as `graph_clusters_i`, the only tensor used to produce `index_equals_cluster_id`, not having NaN or inf (it's an integer tenser to begin with, btw), I don't see how infs or NaNs elsewhere could be causing this issue.

So if noone wants to work on resolving this ATM, I'd say just leave it open for now and we'll figure out what to do with it later.

**Comment by vfdev-5** [comment] 2021-03-26 20:51
@Algomorph I can try to repro with cuda10, but here are few comments on your repository:
- can not checkout Eigen and have to replace git@gitlab.com:libeigen/eigen.git by https://gitlab.com/libeigen/eigen.gitnano in .git/config and .gitmodules
- have to comment out `find_package(Pybind11StubgenExecutable)` as no idea how to get it.
- have to install deps `apt-get install -y libglu1-mesa-dev libc++-7-dev libudev-dev libusb-1.0-0-dev` to install open3d
- have to comment out cupy usage in NeuralTracking/model/correlation/correlation.py as installing it takes ages.

**Comment by vfdev-5** [comment] 2021-03-27 07:26
@Algomorph I could reproduce the issue using [this setup](https://gist.github.com/vfdev-5/75e283f5decb042acab3ec6a8b39b271#execute-inside-pytorch-docker-pytorchpytorch181-cuda111-cudnn8-devel)

**Comment by Algomorph** [comment] 2021-03-27 18:58
@vfdev-5 , that's great!
Sorry I cannot be more involved in this right now, but I'm glad you were able to reproduce.

- Not sure what's going on with Eigen, it's supposed to work as a git submodule, but might have given you trouble by requiring the ssh (git) protocol. But whatever works for you works.
- About the pybind11 stubgen: it can be set up by `pip install pybind11-stubgen` from PyPI. But I recon it's not necessary to reproduce the bug, so that's fine.
- I think it's fine to go w/o cupy, it's true that its installation takes eons for whatever reason (I think it tries to build the thing from scratch on every platform).

**Comment by vfdev-5** [comment] 2021-03-28 09:13
@Algomorph finally I should use cupy otherwise model forward does not work. With cuda11 I had to use latest version of cupy as 6.0.0 can't be build (was an error on installation)

**Comment by Algomorph** [comment] 2021-03-28 12:38
@vfdev-5 , that's what I did to as well, and fixed the usage of cupy to the latest version.

**Comment by vfdev-5** [comment] 2021-04-15 22:19
@Algomorph the issue is related to Open3D and mainly to the code: `volume = o3d.t.geometry.TSDFVoxelGrid(...)` which should fail somehow with cuda11 and break the cuda context.
For example, if you set the open3d device to CPU: `device = o3d.core.Device('CPU:0')` and reexecute `python basic_pipeline.py`, forward pass terminates without issues.

On the other hand, if cuda device is used, then `python basic_pipeline.py` fails with
```
Traceback (most recent call last):
  File "basic_pipeline.py", line 301, in <module>
    sys.exit(main())
  File "basic_pipeline.py", line 274, in main
    model_data = model(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/repro/model/model.py", line 433, in forward
    x = torch.nonzero(mask, as_tuple=True)[0].tolist()
RuntimeError: Trying to create tensor with negative dimension -2133151913: [-2133151913]
```
as you stated on the forum. If we sync `mask` before calling `x = torch.nonzero(mask, as_tuple=True)[0].tolist()` we see more error messages saying about Open3D:
```
    source_weights = source_weights[valid_corresp_mask]                                                                                                                                       
RuntimeError: CUDA error: device-side assert triggered        
stdgpu : CUDA ERROR :                                                                                                                                                                         
  Error     : device-side assert triggered                   
  File      : /tmp/Open3D/build/stdgpu/src/ext_stdgpu/src/stdgpu/cuda/impl/memory.cpp:165                                                                                                     
  Function  : void stdgpu::cuda::dispatch_memcpy(void*, const void*, stdgpu::index64_t, stdgpu::dynamic_memory_type, stdgpu::dynamic_memory_type)
terminate called without an active exception                                                                                                                                                  
Aborted (core dumped) 
```

A minimal code snippet with pytorch and open3D to reproduce a failure:
```python
import torch


def main():

    print("---")
    d = torch.tensor([0.0, 0.5, 0.7, 1.0], device="cuda")
    print(d.mean())

    print("---")

    import open3d as o3d
    import open3d.core as o3c

    voxel_size = 3.0 / 512.0  # voxel resolution in meters
    sdf_trunc = 0.04  # truncation distance in meters
    block_resolution = 16  # 16^3 voxel blocks
    initial_block_count = 100  # initially allocated number of voxel blocks
    device = o3d.core.Device('CUDA:0')

    volume = o3d.t.geometry.TSDFVoxelGrid(
        {
            'tsdf': o3d.core.Dtype.Float32,
            'weight': o3d.core.Dtype.UInt16,
            'color': o3d.core.Dtype.UInt16
        },
        voxel_size=voxel_size,
        sdf_trunc=sdf_trunc,
        block_resolution=block_resolution,
        block_count=initial_block_count,
        device=device
    )

    print("---")

    d = torch.tensor([0.0, 0.5, 0.7, 1.0], device="cuda")
    print(d.mean())

    print("---")

    return 0


if __name__ == "__main__":
    main()

```
>
```
---
tensor(0.1250, device='cuda:0')
---
---
tensor(0.5500, device='cuda:0')
---
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  after reduction step 1: cudaErrorInvalidDevice: invalid device ordinal
Aborted (core dumped)
```

**Comment by Algomorph** [comment] 2021-04-15 23:17
I see. Thank you so much for figuring this out, it must have taken a lot of your time. 

So, it seems like Open3D and PyTorch don't play nice together, even when their C++ ABI versions match. I haven't been able to replicate these issues again with the latest Open3D master + PyTorch 1.8.1 (built from source) so far, but we might as well keep this open for awhile, just in case something similar crops up or someone else stumbles upon this issue.

**Comment by vfdev-5** [comment] 2021-04-15 23:43
@Algomorph yes, I confirm that Open3D master (0.12.0+317628457) and PyTorch nightly (1.9.0.dev20210415) work OK together and there is no issues with `basic_pipeline.py` and minimal code snippet.
Apparently, the possible issue was fixed since then.

**Comment by rgommers** [comment] 2021-04-17 09:30
Thanks @vfdev-5, nice detective work!

> I haven't been able to replicate these issues again with the latest Open3D master + PyTorch 1.8.1 (built from source) so far, but we might as well keep this open for awhile, just in case something similar crops up or someone else stumbles upon this issue.

Since you both confirmed it's fixed in master, let's close it to avoid other people spending time looking at it (it's tagged `high priority`, so it'll show up in many people's queue).

**Closed by rgommers** 2021-04-17 09:30 UTC
Labels: high priority, module: assert failure, module: cuda, module: reductions, triaged

**Comment by LetterLiGo** [comment] 2022-11-09 11:24
In my case, it is caused by the mismatch of context, where the model is warpped by @torch.no_grad(). You might try keeping each model within @torch.no_grad() whenever you call the model.
