### ISSUE TITLE
Build documentation without emitting warnings

### ISSUE THREAD

**Issue by mattip** [pytorch/pytorch#38011] opened 2020-05-07 12:25 UTC
Currently documentation builds emit many warnings. We should resolve them, then turn on `-WT --keep-going` to report warnings as errors so that new build problems are caught as they are created.

cc @ezyang @zou3519

**Comment by zou3519** [comment] 2020-05-07 14:16
Duplicate of https://github.com/pytorch/pytorch/issues/27765, but I agree we should have this.

**Comment by rgommers** [comment] 2020-05-08 05:47
I closed gh-27765 as a duplicate. Of the remaining items after https://github.com/pytorch/pytorch/pull/37419#issuecomment-625227494, I think this is the most important one.

**Comment by mattip** [comment] 2020-05-22 08:57
From gh-32703: 
> We should also ensure document building is clean with/without torchvision, and `USE_DISTRIBUTED=0`

**Comment by mattip** [comment] 2020-07-07 10:44
After gh-41068 the only warnings are emitted by [quantization](https://pytorch.org/docs/master/quantization.html) which needs some curation. In particular, it has these sections that I think should be separate pages:
```
torch.nn.intrinsic
torch.nn.instrinsic.qat
torch.nn.intrinsic.quantized
torch.nn.qat
torch.nn.quantized
torch.nn.quantized.dynamic
```

The remaining warnings are due to repeating names of some of the classes in those modules. For instance, ConvBn2d appears in both [torch.nn.intrinsic](https://pytorch.org/docs/master/quantization.html#id2) and [torch.nn.intrinsic-qat](https://pytorch.org/docs/master/quantization.html#torch-nn-instrinsic-qat)

**Comment by mattip** [comment] 2020-07-12 21:21
After gh-41321, there are (currently) two warnings left:
- `pytorch/docs/source/index.rst:65: WARNING: toctree contains
  reference to nonexisting document 'torchvision/index'`
- `WARNING: autodoc: failed to import class 'tensorboard.writer.SummaryWriter' from module 'torch.utils'`

Should I refactor the docs to remove the offending links or make those components prerequisites to building documentation? It may be tricky to install torchvision since it seems the versions of torch and torchvision are tightly linked, I think we would have to build torchvision in-place.

**Comment by rgommers** [comment] 2020-07-13 09:59
For `torchvision`, you can just treat it like `torchaudio` and `torchtext` with an explicit link, https://pytorch.org/vision works.

For the `tensorboard` one, `torch.utils.tensorboard` is part of PyTorch so I'd add it to the doc build requirements.

**Closed** 2020-07-29 05:35 UTC
Labels: module: doc infra, module: docs, triaged
