### ISSUE TITLE
[v2.2.2] Release Tracker

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#120999] opened 2024-03-01 15:18 UTC
This issue is for tracking cherry-picks to the release branch. Following is [release branch](https://github.com/pytorch/pytorch/tree/release/2.2) for the 2.2.2 release.

Our plan from this point is roughly the following:

* Phase 1 (until 3/18): Cherry-pick post deadline (End of day 5PM PST)
* Phase 2 (after 3/18):  Perform extended integration/stability/performance testing based on Release Candidate builds.

**Only issues that have ‘cherry-picks’ in this tracker will be considered for the release.**

## Cherry-Pick Criteria

**Phase 1 (until 3/18):**

The Releng team relies on the cherry pick process to manage risk to release quality, i.e. by porting a small set of commit from trunk that are "must-have" into the release branch, we limit the change to the minimal to address pressing issues. Thus, not everything a developer land into the trunk will make it into the release. So, please consider the criteria below and follow the cherry picking process. Only low-risk changes may be cherry-picked from master:

1. Fixes to regressions against the most recent release (e.g. 2.2.0 for 2.2.2 release; see [module: regression issue list](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22module%3A+regression%22+))
2. Low risk critical fixes for: silent correctness, backwards compatibility, crashes, deadlocks, (large) memory leaks
3. Fixes to new features being introduced in 2.2.0 release
4. Documentation improvements
5. Release branch specific changes (e.g. blocking ci fixes, change version identifiers)

Any other change requires special dispensation from the release managers (currently @atalman, @huydhn, @PaliC, @osalpekar, @malfet). If this applies to your change please write "Special Dispensation" in the "Criteria Category:" template below and explain. 

**Phase 2 (after 3/18):**

Note that changes here require us to rebuild a Release Candidate and restart extended testing (likely delaying the release). Therefore, the only accepted changes are **Release-blocking** critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+)

Changes will likely require a discussion with the larger release team over VC or Slack.

## Cherry-Pick Process

1. Ensure your PR has landed in master. This does not apply for release-branch specific changes (see Phase 1 criteria).
2. Create (but do not land) a PR against the [release branch](https://github.com/pytorch/pytorch/tree/release/2.1).
   <details>

    ```bash
    # Find the hash of the commit you want to cherry pick
    # (for example, abcdef12345)
    git log

    git fetch origin release/2.2
    git checkout release/2.2
    git cherry-pick abcdef12345

    # Submit a PR based against 'release/2.2' either:
    # via the GitHub UI
    git push my-fork

    # via the GitHub CLI
    gh pr create --base release/2.2
    ```

    </details>
3. Make a request below with the following format:

```
Link to landed trunk PR (if applicable):
* 

Link to release branch PR:
* 

Criteria Category:
* 
```

1. Someone from the release team will reply with approved / denied or ask for more information.
2. If approved, someone from the release team will merge your PR once the tests pass. **Do not land the release branch PR yourself.**

**NOTE: Our normal tools (ghstack / ghimport, etc.) do not work on the release branch.**

See [HUD 2.2](https://hud.pytorch.org/hud/pytorch/pytorch/release%2F2.2/1?per_page=50) 

### Versions

2.2.2

**Comment by thiagocrepaldi** [comment] 2024-03-01 18:26
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/115969

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/121026

Criteria Category:
* Low risk critical fixes for backwards compatibility

@malfet @kit1980 FYI

**Comment by mvpatel2000** [comment] 2024-03-04 02:31
Link to landed trunk PR:
- https://github.com/pytorch/pytorch/pull/115525
Link to release branch PR:
- https://github.com/pytorch/pytorch/pull/121108
Criteria Category:
- Low risk critical fixes for regressions in recent releases. Checkpointing with dtensor fails with `AssertionError: Size to be sharded on dim 0 must be at least as large as the number of devices in that dimension 32` otherwise

**Comment by atalman** [comment] 2024-03-05 14:49
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/121169

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/121229

Criteria Category:
* Fixes build instructions

**Comment by atalman** [comment] 2024-03-05 15:05
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/120567

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/121232

Criteria Category:
* Regression in 2.2.0 release

**Comment by mvpatel2000** [comment] 2024-03-05 18:32
Link to landed trunk PR:
- https://github.com/pytorch/pytorch/pull/120837
Link to release branch PR:
- https://github.com/pytorch/pytorch/pull/121250
Criteria Category:
- Low risk critical fixes for regressions in recent releases. Users cannot export checkpoints otherwise with non-sharded format

**Comment by atalman** [comment] 2024-03-07 15:57
Link to landed trunk PR (if applicable):
*  https://github.com/pytorch/pytorch/pull/120126

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/121419

Criteria Category:
* Critical fix

**Comment by atalman** [comment] 2024-03-14 22:18
Link to landed trunk PR (if applicable):
* 

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/121934

Criteria Category:
* Release only

**Comment by huydhn** [comment] 2024-03-16 01:13
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/118681

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/120518

Criteria Category:
* Ci fix to grant permission to create release workflow

---
@huydhn merged

**Comment by patrikhuber** [comment] 2024-03-16 14:45
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/117497

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/117497

Criteria Category:
* Critical fix. Building libTorch from source has been broken on latest MSVC since Dec 2023, due to an ICE. This PR fixes the build on Windows/MSVC.

**Comment by atalman** [comment] 2024-03-18 19:46
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/120361
* https://github.com/pytorch/pytorch/pull/121262

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/122121
* https://github.com/pytorch/pytorch/pull/122122

Criteria Category:
* Usecase: In Torch-TensorRT, we use _SplitterBase partitioner to split graphs into Pytorch and TensorRT nodes. For single output graphs, the resultant graph from this partitioner will output tuples which differs from the output type of Pytorch eager (in this case - torch.tensor). The correct output type should be torch.tensor and this PR adds the fix (by adding codegen which unflattens the output)

**Comment by atalman** [comment] 2024-03-19 14:42
Please Note: We are in Phase 2 (after 3/18):

Note that changes here require us to rebuild a Release Candidate and restart extended testing (likely delaying the release). Therefore, the only accepted changes are Release-blocking critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22+sort%3Aupdated-desc), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+sort%3Aupdated-desc), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+sort%3Aupdated-desc), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+sort%3Aupdated-desc), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+sort%3Aupdated-desc)

**Comment by huydhn** [comment] 2024-03-19 17:06
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/121918

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/122207

Criteria Category:
* CI fix to keep the signals on release branch sane

---
@huydhn merged

**Comment by atalman** [comment] 2024-03-19 17:52
Please Note: We are in Phase 2 (after 3/18):

Note that changes here require us to rebuild a Release Candidate and restart extended testing (likely delaying the release). Therefore, the only accepted changes are Release-blocking critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22+sort%3Aupdated-desc), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+sort%3Aupdated-desc), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+sort%3Aupdated-desc), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+sort%3Aupdated-desc), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+sort%3Aupdated-desc)

**Comment by atalman** [comment] 2024-03-27 21:39
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/121618

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/122645

Criteria Category:
* Critical perf fix on Windows

**Closed** 2024-03-27 21:40 UTC
Labels: oncall: releng, triaged
