### ISSUE TITLE
If want to add Bert for pytorch community,  which path should I push  models and weights of BERT

### ISSUE THREAD

**Issue by daydayfun** [pytorch/pytorch#27689] opened 2019-10-10 08:29 UTC
## ❓ Questions and Help

If want to add Bert for pytorch community,  can I put the models and weights of BERT into the repository of **pytorch/text** ?
As **pytorch/vision**  is for Models specific to Computer Vision,  but i can't find any NLP models in   **pytorch/text**

**Comment by cpuhrsch** [comment] 2019-10-10 17:29
Hello @daydayfun,

Do you have the relevant code already available in a separate repository? We don't yet have models within pytorch/text at the same level as we do with pytorch/vision and it is not clear if we want to go down that route, since many frameworks such as fairseq or huggingface already implement this. It could however be good to add a minimal implementation as a reference.

cc @zhangguanheng66

**Comment by daydayfun** [comment] 2019-10-11 13:08
Thanks for your help. I have some demo code of bert based on Pytorch 1.0.

**Comment by soumith** [comment] 2019-10-11 22:10
duplicate of the other issue

**Closed** 2019-10-11 22:10 UTC
Labels: module: docs, triaged
