### ISSUE TITLE
type error when calling 'adagrad' optimization method

### ISSUE THREAD

**Issue by BigeyeDestroyer** [pytorch/pytorch#2021] opened 2017-07-08 16:31 UTC
There is a type mismatch in line 82 of file 'adagrad.py' since we feed torch.cuda.FloatTensor to function 'addcmul_' which requires torch.FloatTensor input.

**Comment by apaszke** [comment] 2017-07-15 15:18
Can you paste a small snippet that reproduces the error in here?

**Comment by BigeyeDestroyer** [comment] 2017-07-16 05:31
<img width="1051" alt="screen shot 2017-07-16 at 1 31 04 pm" src="https://user-images.githubusercontent.com/7389174/28244912-19c8167a-6a2b-11e7-8afa-548f0839fa26.png">

**Comment by soumith** [comment] 2017-07-16 05:38
David Lopez-Paz reported this as well, seems like a small bug to fix. Here's david's stack trace:

```
TypeErrorTraceback (most recent call last)
<ipython-input-23-8ab80c925f36> in <module>()
    144     lossD = bce(netD(torch.cat((fake, real))), labD)
    145     lossD.backward()
--> 146     optD.step()
    147 
    148     fake = netG(sample_noise(bs, n_latent, gpu))

/home/dlp/local/anaconda2/lib/python2.7/site-packages/torch/optim/adagrad.pyc in step(self, closure)
     80                     p.data.add_(-clr, make_sparse(grad_values / std_values))
     81                 else:
---> 82                     state['sum'].addcmul_(1, grad, grad)
     83                     std = state['sum'].sqrt().add_(1e-10)
     84                     p.data.addcdiv_(-clr, grad, std)

TypeError: addcmul_ received an invalid combination of arguments - got (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor), but expected one of:
 * (torch.FloatTensor tensor1, torch.FloatTensor tensor2)
 * (torch.SparseFloatTensor tensor1, torch.SparseFloatTensor tensor2)
 * (float value, torch.FloatTensor tensor1, torch.FloatTensor tensor2)
      didn't match because some of the arguments have invalid types: (int, !torch.cuda.FloatTensor!, !torch.cuda.FloatTensor!)
 * (float value, torch.SparseFloatTensor tensor1, torch.SparseFloatTensor tensor2)
      didn't match because some of the arguments have invalid types: (int, !torch.cuda.FloatTensor!, !torch.cuda.FloatTensor!)
```

**Comment by BigeyeDestroyer** [comment] 2017-07-16 06:15
Yeah, exactly the same problem !

**Comment by apaszke** [comment] 2017-07-16 18:31
is it possible that you run at least a single iter on a CPU and then use a GPU? alternatively, do you deserialize the optimizer onto CPU and try to use it with a GPU model? I still don't know how to reproduce that 😕

**Comment by matt-gardner** [comment] 2017-08-25 00:13
I am seeing the same error with adagrad.  If I switch the optimizer to adam, I can train just fine.  Happy to help figure out the issue, but don't know what info you need.

**Comment by luyaojie** [comment] 2017-08-27 15:22
I was encountering the same bug when i define the optmizer before move the model to cuda.

optimizer = Adagrad(model.parameters()) # TypeERROR
model.cuda() # TypeERROR

however, change their order is FINE.

model.cuda() # FINE
optimizer = Adagrad(model.parameters()) # FINE

**Comment by matt-gardner** [comment] 2017-08-27 15:34
Thanks for the tip.  Yep, that would do it: https://github.com/pytorch/pytorch/blob/5a0163cdee7d2071329d35ec44811abb572c74e8/torch/optim/adagrad.py#L31

Is there are reasonable way to provide something like `.cuda()` for optimizers?  Probably not...  At the least, the documentation needs to be updated to say that models must be moved to the GPU before the optimizer is created, either [here](http://pytorch.org/docs/master/optim.html#torch.optim.Adagrad), or [here](http://pytorch.org/docs/master/optim.html#constructing-it) (probably the latter).  Happy to submit a PR for this if you think that's the best solution.

**Comment by matt-gardner** [comment] 2017-08-27 15:48
I guess another option is leave `state['sum']` as `None` in `__init__`, but set it here if it's not present: https://github.com/pytorch/pytorch/blob/5a0163cdee7d2071329d35ec44811abb572c74e8/torch/optim/adagrad.py#L83

Seems ugly, though...

**Comment by phiedulxp** [comment] 2018-04-19 12:14
`
    state['sum'].addcmul_(1, grad, grad)
TypeError: addcmul_ received an invalid combination of arguments - got (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor), but expected one of:
 * (torch.FloatTensor tensor1, torch.FloatTensor tensor2)
 * (torch.SparseFloatTensor tensor1, torch.SparseFloatTensor tensor2)
 * (float value, torch.FloatTensor tensor1, torch.FloatTensor tensor2)
      didn't match because some of the arguments have invalid types: (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor)
 * (float value, torch.SparseFloatTensor tensor1, torch.SparseFloatTensor tensor2)
      didn't match because some of the arguments have invalid types: (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor)
`

**Comment by phiedulxp** [comment] 2018-04-19 12:15
state['sum'].addcmul_(1, grad, grad)
TypeError: addcmul_ received an invalid combination of arguments - got (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor), but expected one of:
 * (torch.FloatTensor tensor1, torch.FloatTensor tensor2)
 * (torch.SparseFloatTensor tensor1, torch.SparseFloatTensor tensor2)
 * (float value, torch.FloatTensor tensor1, torch.FloatTensor tensor2)
      didn't match because some of the arguments have invalid types: (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor)
 * (float value, torch.SparseFloatTensor tensor1, torch.SparseFloatTensor tensor2)
      didn't match because some of the arguments have invalid types: (int, torch.cuda.FloatTensor, torch.cuda.FloatTensor)

**Comment by weiyangfb** [comment] 2018-08-22 18:34
As https://github.com/pytorch/pytorch/pull/3056 got merged, should we close this issue?

**Closed** 2018-08-23 22:01 UTC
Labels: bug, high priority, needs-reproduction
