### ISSUE TITLE
Constant strings aren't captured in TorchScript function

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#42388] opened 2020-07-31 22:35 UTC
## To Reproduce

```
import torch


MY_STR_CONST = "Hi, I am a string, please realize I am a constant"


@torch.jit.script
def fn():
    return MY_STR_CONST


print(fn())
```
```
Traceback (most recent call last):
  File "closed_over_string.py", line 8, in <module>
    def fn():
  File "/private/home/ycao/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 929, in script
    fn = torch._C._jit_script_compile(
RuntimeError:
python value of type 'str' cannot be used as a value:
  File "closed_over_string.py", line 9
@torch.jit.script
def fn():
    return MY_STR_CONST
           ~~~~~~~~~~~~ <--- HERE
```

## Expected behavior

fn() should return constant string

cc @suo @gmagogsfm

**Comment by suo** [comment] 2020-07-31 22:44
I think we should consider this a duplicate of #41288 (my comment there applies here as well)

**Comment by suo** [comment] 2020-07-31 22:45
This issue description and repro is more accurate though (although this behavior applies to all python values, not just strings)

**Comment by gmagogsfm** [comment] 2020-07-31 23:30
Closing as it is a dup of #41288 

Moving the problem description there as well

**Closed** 2020-08-01 05:22 UTC
Labels: jit
