### ISSUE TITLE
Feature request: ability even not to sum up over all batches in loss functions

### ISSUE THREAD

**Issue by analvikingur** [pytorch/pytorch#1054] opened 2017-03-21 18:40 UTC
Hi

One may want to evaluate perplexity in language modelling task. In this case it is necessary to average over sequence length, then take exponent and only then average over batch size.

For now it is impossible to implement such logic with `torch.nn.NLLLoss` in case of implicitly result averaging or summing up.

From my point of view, it may be reasonable not to perform any implicitly operations with result of loss functions to make them more flexible.

Cheers!

**Comment by kuangliu** [comment] 2017-03-22 11:31
Maybe `size_average=False` should return a tensor of losses, instead of a number of `loss_sum`.

**Comment by apaszke** [comment] 2017-03-22 12:01
Duplicate of #264

**Closed by apaszke** 2017-03-22 12:01 UTC
