### ISSUE TITLE
Setting the 0D tensor of only one element to `fill_value` of `full()` works against error message

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#129969] opened 2024-07-02 16:40 UTC
### 🐛 Describe the bug

Setting the 1D tensor of only one element to `fill_value` of [full()](https://pytorch.org/docs/stable/generated/torch.full.html) gets the error as shown below:

```python
import torch

torch.full(size=(3,), fill_value=torch.tensor([8])) # Error
```

> TypeError: full(): argument 'fill_value' must be Number, not Tensor

But setting the 0D tensor of only one element to `fill_value` of `full()` works against the error message above as shown below:

```python
import torch

torch.full(size=(3,), fill_value=torch.tensor(8)) # tensor([8, 8, 8])
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

cc @svekars @brycebortree @albanD

**Comment by soulitzer** [comment] 2024-07-02 23:55
We'd accept a PR to make the error more accurate.

**Comment by malfet** [comment] 2024-07-03 00:08
Closing as duplicate of https://github.com/pytorch/pytorch/issues/129970 (because they are talking about the same thing)

**Closed by malfet** 2024-07-03 00:08 UTC
Labels: module: docs, triaged, module: python frontend
