### ISSUE TITLE
rfftn / irfftn is not functioning properly

### ISSUE THREAD

**Issue by AndersGarpebring** [pytorch/pytorch#49829] opened 2020-12-24 12:06 UTC
## 🐛 Bug

rfftn returns the wrong size of the output. For example the results differ from both rfft2 and rfft and is not consistent with numpy as for all other fft operations. The irfft is indeed the inverse of rfft but returns a complex value which is inconsistent with irfft2.

## To Reproduce
(I have only tested it in rather complex environement calling c++ from c#. So I simplify it here how to reproduce the issue in python. I see no reason why the problem should not be there too. But since I have not tested in that enviroment I cannot be 100% sure.

torch.fft.rfftn(torch.arange(0,7,1)).shape
This gives
(7,) 
but I expected (4,)

## Environment
Im using the nighly build from 20201219. Libtorch, C++ Win10. Working i visual studio.

## Additional context

I know that Im using a version under development so this might already be fixed. But in case not I thought this might be of help.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @mruberry @peterbell10 @walterddr

**Comment by Sifat1998** [comment] 2020-12-24 12:09
![Uploading 103087883...]

**Comment by mruberry** [comment] 2020-12-25 00:37
Thank you for reporting this issue, @AndersGarpebring. On the latest nightly I ran this script:

```
import numpy as np
import torch

t = torch.arange(0, 7, 1)
print(torch.fft.rfftn(t).shape)
print(np.fft.rfftn(t).shape)
```

and it printed

```
torch.Size([4])
(4,)
```

Which seems correct? Would you try updating to the latest nightly? Or maybe I'm missing something?

**Comment by eduardo4jesus** [comment] 2021-05-26 20:39
Just tested this with `1.8.1+cu101`. I could not reproduce it. The issue seems to be fixed.

**Comment by peterbell10** [comment] 2021-05-26 23:12
This issue is from a 6 month old nightly release used in a non-standard environment. It wasn't reproducible at the time, and I can't reproduce it now. So, I think it's fair to close this.

**Closed by peterbell10** 2021-05-26 23:12 UTC
Labels: module: fft, needs reproduction, triaged
