### ISSUE TITLE
torch.compile() results in inflexible model with mistralai/Mistral-7B-v0.1

### ISSUE THREAD

**Issue by petermcaughan** [pytorch/pytorch#113393] opened 2023-11-09 21:52 UTC
### 🐛 Describe the bug

When applying torch.compile() to HF model `mistralai/Mistral-7B-v0.1`, the resulting model is inflexible in sequence length. The repro code and error message is below:

```python
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer

model = AutoModelForCausalLM.from_pretrained(
            "mistralai/Mistral-7B-v0.1",
            torch_dtype=torch.float16,,
            use_cache=True,
        ).to(torch.device('cuda'))

model = torch.compile(model)

#Below three lines work as expected
input_ids =torch.randint(low=0, high=60000, size=(1, 32), dtype=torch.int64)
attention_mask = torch.ones(1, 32, dtype=torch.int64)
model(input_ids=input_ids, attention_mask=attention_mask)

#Next three lines throw error
input_ids =torch.randint(low=0, high=60000, size=(1, 64), dtype=torch.int64)
attention_mask = torch.ones(1, 64, dtype=torch.int64)
model(input_ids=input_ids, attention_mask=attention_mask)

'''
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function not_>(*(Eq(s1, s0) & Eq(s2, s0),), **{}):
The expression should not be static by this point: False
 
from user code:
   File "/dev_data/petermca/python_packages/transformers/models/mistral/modeling_mistral.py", line 295, in forward
    if attention_mask.size() != (bsz, 1, q_len, kv_seq_len):
 
Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information
 
You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True"
'''
```

### Versions

torch==2.2.0.dev20231108+cu118
transformers==4.34.1

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by petermcaughan** [comment] 2023-11-09 21:53
@BowenBao

**Comment by BowenBao** [comment] 2023-11-09 22:00
cc @ezyang for advice

**Comment by jon-chuang** [comment] 2023-11-09 22:03
Seems like an issue with automatic_dynamic.

Could you try `torch.compile(mode, dynamic=True)`?

**Comment by msaroufim** [comment] 2023-11-09 23:16
Marking as high pri since this is a very popular model

**Comment by voznesenskym** [comment] 2023-11-13 23:18
High pri is for bugs. @petermcaughan please try w/ automatic dynamic

**Comment by jon-chuang** [comment] 2023-11-16 04:47
I think this is huggingface-only and doesn't impact the original impl. But hugging face is probably more popular.

**Comment by jon-chuang** [comment] 2023-11-16 06:01
Repro:
```python
def fn(x):
    if x.size() != (1, 1, 2, 3):
      return x.cos()
    return x.sin()

torch.compile(fn, backend="eager")(torch.ones(1, 1, 3, 4))
torch.compile(fn, backend="eager")(torch.ones(1, 1, 2, 3))
```

Non repros:
```
x.size() != (1, x, y)
x.size() != (x, y)
x.size() != (1, 1, x)
````

For some reason, it needs to be exactly `(1, 1, x, y)`.

**Comment by jon-chuang** [comment] 2023-11-16 06:08
I think this has to do with guarding on more than one symbolic Eq exprs. Somehow we cannot fold `Not(And(Eq(a, b), Eq(c, d)))` to `Or(Ne(a, b), Ne(c, d))`. But the weird thing is that we don't encounter this when we dont lead with two 1, 1 or 0, 1

**Comment by jon-chuang** [comment] 2023-11-16 06:27
The root cause is that `1 and True` can evaluate to `1` instead of boolean. This confuses `symbolic_shapes` to take the wrong code path.

**Closed** 2023-11-16 23:25 UTC
Labels: triage review, oncall: pt2, module: dynamic shapes

**Comment by jon-chuang** [comment] 2023-11-16 23:51
@petermcaughan please confirm if the issue is solved for you on latest main
