### ISSUE TITLE
c10::Error ... Probably file system error, posting in case it's of interest

### ISSUE THREAD

**Issue by drevicko** [pytorch/pytorch#45826] opened 2020-10-04 23:27 UTC
## 🐛 Bug

This error came up during a slurm run:

```

  File "main.py", line 473, in main_loop
    state = torch.load(output_folder / model_file_name)
  File "/apps/pytorch/1.4.0-py37-cuda90/lib/python3.7/site-packages/torch/serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/apps/pytorch/1.4.0-py37-cuda90/lib/python3.7/site-packages/torch/serialization.py", line 709, in _legacy_load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: read(): fd 33 failed with Stale file handle
terminate called after throwing an instance of 'c10::Error'
  what():  owning_ptr == NullType::singleton() || owning_ptr->refcount_.load() > 0 INTERNAL ASSERT FAILED at ../c10/util/intrusive_ptr.h:348, please report a bug to PyTorch. intrusive_ptr: Can only intrusive_ptr::reclaim() owning pointers that were created using intrusive_ptr::release(). (reclaim at ../c10/util/intrusive_ptr.h:348)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x2aaad1d302b5 in /apps/pytorch/1.4.0-py37-cuda90/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: THStorage_free + 0xe6 (0x2aaac04bbbe6 in /apps/pytorch/1.4.0-py37-cuda90/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: <unknown function> + 0x9752a7 (0x2aaabc6b12a7 in /apps/pytorch/1.4.0-py37-cuda90/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #21: __libc_start_main + 0xf5 (0x2aaaac37da35 in /lib64/libc.so.6)

/cm/local/apps/slurm/var/spool/job46936306/slurm_script: line 26:  4933 Aborted                 (core dumped) python main.py ...
```

## To Reproduce

1. The same file loaded ok on subsequent runs, and I've not seen this error on any of a large number of runs
1.
1.

## Environment

PyTorch version: 1.4.0a0+f067088
Is debug build: False
CUDA used to build PyTorch: 9.0
ROCM used to build PyTorch: N/A

OS: SUSE Linux Enterprise Server 12 SP4 (x86_64)
GCC version: (SUSE Linux) 4.8.5
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla P100-SXM2-16GB
GPU 1: Tesla P100-SXM2-16GB
GPU 2: Tesla P100-SXM2-16GB
GPU 3: Tesla P100-SXM2-16GB

Nvidia driver version: 440.64.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.15.4
[pip3] numpydoc==0.9.1
[pip3] torch==1.4.0a0+f067088
[pip3] torchfile==0.1.0
[pip3] torchfm==0.7.0
[pip3] torchnet==0.0.4
[conda] Could not collect

## Additional context

This appears to be a file system error, however I thought I'd post it in case there's something of interest to pytorch developers.

cc @mruberry

**Comment by mruberry** [comment] 2020-10-06 20:34
Thanks for the report, @drevicko. I agree it looks like a file system issue. Closing for the moment unless we get additional reports or a reproduction.

**Closed by mruberry** 2020-10-06 20:34 UTC
Labels: module: serialization, needs reproduction, triaged
