### ISSUE TITLE
Inconsistent ctc_loss API

### ISSUE THREAD

**Issue by jpuigcerver** [pytorch/pytorch#22234] opened 2019-06-25 21:57 UTC
## 🐛 Bug

When running ctc on the GPU, torch.nn.functional.ctc_loss expects different types for the "targets" input, depending on whether the selected backed is cudnn or the native implementation.

However, the user does not know in advance whether the cuDNN implementation will be used by PyTorch or not. This is very inconvenient since the program may crash without any clear mechanism to prevent it.

## To Reproduce

Python script:
```python
import torch

# Generate data.
logits = torch.normal(mean=torch.zeros((20, 10, 5), dtype=torch.float32))
logprobs = torch.nn.functional.log_softmax(logits, dim=-1)
targets = torch.randint(1, 10, size=(10, 4), dtype=torch.int32)
target_lengths = torch.randint(1, 5, size=(10,), dtype=torch.int32)

# All examples have the same input length, so that cuDNN can be used.
input_lengths = 20 * torch.ones((10,), dtype=torch.int32)
# Reshape targets, so that cuDNN can be used
targets = torch.cat(tuple(targets[i, :target_lengths[i]] for i in range(10)))

# CPU: OK
print(torch.nn.functional.ctc_loss(logprobs, targets, input_lengths, target_lengths))

# CUDA, PyTorch native implementation: OK
torch.backends.cudnn.enabled = False
print(torch.nn.functional.ctc_loss(logprobs.to('cuda'), targets.to('cuda'), input_lengths, target_lengths))

# CUDA, cuDNN implementation: CRASHES (cuDNN expects targets in CPU).
torch.backends.cudnn.enabled = True
print(torch.nn.functional.ctc_loss(logprobs.to('cuda'), targets.to('cuda'), input_lengths, target_lengths))
```

Output:
```
$ python minimal_ctc.py 
tensor(17.2880)
tensor(17.2880, device='cuda:0')
Traceback (most recent call last):
  File "minimal_ctc.py", line 24, in <module>
    print(torch.nn.functional.ctc_loss(logprobs.to('cuda'), targets.to('cuda'), input_lengths, target_lengths))
  File "/home/joapuipe/.virtualenvs/pytorch1.1-py3.6/lib/python3.6/site-packages/torch/nn/functional.py", line 1813, in ctc_loss
    zero_infinity)
RuntimeError: Expected tensor to have CPU Backend, but got tensor with CUDA Backend (while checking arguments for cudnn_ctc_loss)
```

## Expected behavior

First, the ctc_loss API should specify in the doc which device it expects the inputs.
Secondly, I think it should be consistent regardless of the backend implementation used (e.g. copy to the expected device if necessary). 

If the dev team does not like implicit copies, I suggest a function like: `torch.backends.cudnn.will_ctc_loss_run_on_cudnn(logprobs, targets, inputs_lengths, targets_length, blank)` so that the user can check whether or not cudnn will be used for the given input (i.e the same check as https://github.com/pytorch/pytorch/blob/1d705b4b075e32540293d1717b582442a66ffcce/aten/src/ATen/native/LossCTC.cpp#L344).

## Environment

```
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.6.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce GTX 780
GPU 1: GeForce GTX 1080

Nvidia driver version: 415.27
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] nnutils-pytorch==0.4.0
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torch-baidu-ctc==0.3.0
[pip3] torchvision==0.3.0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @jerryzh168 @SsnL

**Comment by ezyang** [comment] 2019-07-01 17:10
cc @t-vi

Per @soumith @fmassa we should get rid of the cuDNN CTCLoss implementation and use ours all the time. cc @ngimel It would be helpful to know if we might ever want to bring back the cuDNN implementation in the future.

As you point out, there is a mild BC issue; we might need to also (as a deprecation mechanism) accept CPU targets in the native implementation. If we deprecate this implicit copy, that seems acceptable.

**Comment by ngimel** [comment] 2019-07-01 17:24
As @t-vi pointed out, cudnn is currently the only available deterministic option, and it might be worth keeping it for just this reason. Currently though cudnn's nondeterministic path is used in pytorch , leading to accuracy loss, there's another issue about it, but switching pytorch to deterministic cudnn is easy. cudnn's CTC is not being actively worked on, so if you want to get rid of it now, it's unlikely you'd want to bring it back in future.

**Comment by t-vi** [comment] 2019-07-02 11:06
We could always accept the performance hit and use the "naive" kernel currently used for small problems for deterministic.
The obvious improvement would be to sort & count the targets beforehand and then we would only have "max number of any character occurs" steps instead of `max_target_len`. Or one could have a warp reduction for each character or so.

**Comment by sapjunior** [comment] 2019-07-13 18:08
Is there anyway to use only native cuda CTC loss while enable cuDNN for other functions?

**Comment by t-vi** [comment] 2019-07-13 18:46
Yes, by wrapping only the call to ctc loss with `with torch.backends.cudnn.flags(enabled=False):`.

**Comment by sapjunior** [comment] 2019-07-14 02:45
Thank you for your answer. I also encounter strange behavior when using cuDNN CTCLoss as well. At first the loss decrease as plus usual good accuracy on train, but at some points, the loss start increasing and the network cannot learn predict anything even on train set. This behavior doesn't happen when I disable cuDNN by using torch.backends.cudnn.enabled = False

**Comment by ezyang** [comment] 2019-07-14 15:31
Yeah, the non-deterministic cuDNN implementation is bad and we should *really* stop using
it. :)

Excerpts from Thananop Kobchaisawat's message of 2019-07-13 19:46:16 -0700:
> Thank you for your answer. I also encounter strange behavior when using cuDNN CTCLoss as well. At first the loss decrease as plus usual good accuracy on train, but at some points, the loss start increasing and the network cannot learn predict anything even on train set. This behavior doesn't happen when I disable cuDNN by using torch.backends.cudnn.enabled = False
>

**Comment by gchanan** [comment] 2019-07-16 16:37
is this a duplicate of https://github.com/pytorch/pytorch/issues/21680?

**Comment by t-vi** [comment] 2019-07-16 17:29
It's closely related but not exactly the same.
I think removing the reliance on atomicAdd in the native implementation would allow removing the CuDNN binding.

**Comment by zh217** [comment] 2019-07-16 17:51
As things stand now, I think it is not the time to remove CuDNN CTC completely. The deterministic CuDNN works quite well for me.

The problems I have with the native CTC implementation are:

* It doesn't work on edge cases like https://github.com/pytorch/pytorch/issues/18215
* It might not show for small number of classes, but for some of my use cases with ~10k classes, I am seeing x50 performance drop compared to deterministic CuDNN. This is totally not acceptable.

In terms of API, I suggest giving the choice of which implementation to use to the user, in the form of arguments to functions, with sensible default values.

**Comment by t-vi** [comment] 2019-07-16 18:13
Could you please share a self-contained (i.e. with random data or somesuch) test case illustrating your speed concern?
How does it relate to the overall speed of a pass through the network?
Requiring the user choose the implementation (beyond disabling backends) is very foreign to PyTorch.

**Comment by t-vi** [comment] 2019-07-24 07:39
@zh217 would it be possible to share a test case for your speed concern? I am fixing the zero length deficiency and I will work on CuDNN ctc removal next if I can get the benchmarks for the known use cases to be reasonable. Even if you cannot share a use-case, just shape of probs, shape of targets, input lengths and target lengths would be super helpful.

**Comment by zh217** [comment] 2019-07-24 15:42
I ran a series of tests and it doesn't seem that I can reproduce the x50 slowdown under controlled setting. More typical is x5 slowdown (when number of classes is greater than 10000, almost any input will do).

Given that the problematic slowdown occurs in code that is rather ancient, quite convoluted and highly parallel, I suspect that the slow down may have something to do with some units of work completely stalling, which may be related to the zero length problem. So maybe we should come back to the problem after the zero-length problem is fixed.

**Comment by zh217** [comment] 2019-07-24 15:58
Also, I have some algorithmic suggestion: it pays to explicitly construct the lattice beforehand so that repeated target lookup during forward-backward is avoided. The lattice construction is trivially parallel and doesn't need any atomic operations.

I have an non-pytorch implementation that did just that and it helps quite a bit when the number of classes is big. Unfortunately I cannot share the code.

**Comment by t-vi** [comment] 2019-07-24 18:12
How much of the total pass is CTC. Obviously if it is 50 percent, a 5x slowdown is terrible whereas when it is 1% it would just be undesirable.
What is your sequence length / batch size?
I'll first get rid of the nondeterministic bits and then would love to also discuss other speedups.

**Comment by anjali411** [comment] 2019-12-17 19:19
Resolved in https://github.com/espnet/espnet/pull/1343

**Comment by t-vi** [comment] 2019-12-17 19:25
@anjali411 ?

**Comment by Oktai15** [comment] 2019-12-20 20:04
https://github.com/pytorch/pytorch/issues/22234#issuecomment-511168497

Very-very bad situation that @sapjunior mentioned on this summer! Can we add something to CTCLoss documentation about inner softmax in `cudnn_ctc_loss`?

**Comment by t-vi** [comment] 2019-12-20 20:50
The softmax would be mostly an inefficient "exp" given that softmax(logsoftmax(x)) == softmax(x) == exp(logsoftmax(x)), but it's even gone in PyTorch 1.4, which catches up with the more problematic CuDNN BC breaking change between 7.1 and 7.6 was not so nice. 
We also added some automatic casting.

So what exactly is the "very very bad situation" and what would you want to add?

**Comment by Oktai15** [comment] 2019-12-20 21:12
As far as I understood @sapjunior correctly, current implementation of `cudnn_ctc_loss` do `softmax` again. It means that we need to pass logits, not log probs to `cudnn_ctc_loss`?

**Comment by t-vi** [comment] 2019-12-20 21:35
@Oktai15 This never was much of a problem (except wasting a few gpu cycles). But again, it's gone now.

#27039 also addressed most of the inconsistency problem the original poster observed, so maybe closing this is best after all.

**Closed by t-vi** 2019-12-20 21:35 UTC
Labels: high priority, module: cudnn, topic: bc-breaking, topic: loss, triaged

**Comment by redwrasse** [comment] 2025-08-19 06:13
Hello, resurrecting this old thread. 

There's some momentum behind https://github.com/pytorch/pytorch/issues/52241, a reasonable goal of expecting the `CTCLoss` to give gradients with respect to its arguments.

At least from what I've seen in my attempt in https://github.com/pytorch/pytorch/pull/159106, the structure of the CUDNN ctc loss APIs are what's preventing this being possible. 

Accomodating the CUDNN ctc loss APIs seems (for example, this issue) to be more generally a cause of undesired complexity- manifesting in the CTC Loss docs, and special testcases. 



Would the maintainers be interested in considering say:


1. Removing CUDNN support entirely? In particular @ezyang's comment 'https://github.com/pytorch/pytorch/issues/22234#issuecomment-507349516' 'we should get rid of the cuDNN CTCLoss implementation and use ours all the time'

2. Alternatively, if wish to continue supporting CUDNN ctc loss, isolating CUDNN ctc loss functionality, like a separate API `CTCLossCuDnn()`? Thinking of for example 'In terms of API, I suggest giving the choice of which implementation to use to the user..' (https://github.com/pytorch/pytorch/issues/22234#issuecomment-511919416).



cc @albertz
