### ISSUE TITLE
torch/include/pybind11/eigen.h:12:10: 致命错误：eigen/matrix.h：没有那个文件或目录

### ISSUE THREAD

**Issue by weixiu00** [pytorch/pytorch#112841] opened 2023-11-03 10:54 UTC
### 🐛 Describe the bug

torch/include/pybind11/eigen/matrix.h   not found

### Versions

torch                    2.1.0+cu121
torchaudio               2.1.0+cu121
torchvision              0.16.0+cu121

cc @seemethere @malfet @osalpekar @atalman

**Comment by bdhirsh** [comment] 2023-11-06 15:16
It sounds like you're hitting an issue either building or running pytorch with eigen? Do you have a minimal reproduction?

**Comment by malfet** [comment] 2023-11-06 19:11
Looks like a regression caused by pybind update to 2.11, we just need to package a few more headers, PR is coming.
Marked as regression as with older pybind there were no `eigen` subfolder

**Closed** 2023-11-07 04:27 UTC
Labels: module: binaries, triaged, module: regression

**Comment by atalman** [comment] 2023-11-22 21:20
Lets confirm its regression against 2.0 release

**Comment by atalman** [comment] 2023-11-29 13:40
confirmed this issue existed in 2.1.0 release we packaged with pybind 2.11.1

**Comment by huydhn** [comment] 2023-12-11 23:17
Confirm that the issue is fixed in 2.1.2 final RC, so it will be fixed in 2.1.2:

```
$ pip install --pre torch==2.1.2 --index-url https://download.pytorch.org/whl/test
$ ls ~/miniconda3/envs/py3.11/lib/python3.11/site-packages/torch/include/pybind11/eigen
common.h	matrix.h	tensor.h
```
