### ISSUE TITLE
Training on 360 sequences, validating on 0 sequences. python3: symbol lookup error: /home/ankitakulkarni/anaconda3/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack

### ISSUE THREAD

**Issue by gangubai** [pytorch/pytorch#17221] opened 2019-02-17 16:35 UTC
## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by vishwakftw** [comment] 2019-02-17 16:53
Maybe related to https://github.com/pytorch/pytorch/issues/14931.

Could you please specify the version of Python that you use? `PySlice_Unpack` was introduced in Python 3.6.1.

**Comment by gangubai** [comment] 2019-02-17 17:46
Solved ...Update the version of python from 3.6.0 to 3.6.2 
Thanks!!

**Comment by vishwakftw** [comment] 2019-02-17 17:48
Please close the issue if you think the issue is resolved.

**Closed** 2019-02-17 17:55 UTC

**Comment by cuge1995** [comment] 2020-12-07 12:47
> Solved ...Update the version of python from 3.6.0 to 3.6.2
> Thanks!!

It works !
