### ISSUE TITLE
AssertionError: Default process group is not initialized

### ISSUE THREAD

**Issue by jm90korea** [pytorch/pytorch#38300] opened 2020-05-12 02:56 UTC
## 📚 Documentation

There is error in Google Colab
=======
INFO:lightning:GPU available: True, used: True
INFO:lightning:CUDA_VISIBLE_DEVICES: [0]
Traceback (most recent call last):
  File "/content/gdrive/My Drive/Google_Colab_Notebooks/2020-CURT/fastMRI-playground-29Apr20/models/unet/train_unet.py", line 229, in <module>
    main()
  File "/content/gdrive/My Drive/Google_Colab_Notebooks/2020-CURT/fastMRI-playground-29Apr20/models/unet/train_unet.py", line 226, in main
    run(args)
  File "/content/gdrive/My Drive/Google_Colab_Notebooks/2020-CURT/fastMRI-playground-29Apr20/models/unet/train_unet.py", line 205, in run
    trainer.test(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 954, in test
    self.check_testing_model_configuration(model if model else self.model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 1029, in check_testing_model_configuration
    gave_test_loader = hasattr(model, 'test_dataloader') and model.test_dataloader()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/core/decorators.py", line 13, in inner_fx
    return fn(self)
  File "/content/gdrive/My Drive/Google_Colab_Notebooks/2020-CURT/fastMRI-playground-29Apr20/models/unet/models/mri_model.py", line 84, in test_dataloader
    return self._create_data_loader(self.test_data_transform(), data_partition=self.hparams.mode, sample_rate=1.)
  File "/content/gdrive/My Drive/Google_Colab_Notebooks/2020-CURT/fastMRI-playground-29Apr20/models/unet/models/mri_model.py", line 55, in _create_data_loader
    sampler = DistributedSampler(dataset)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/data/distributed.py", line 43, in __init__
    num_replicas = dist.get_world_size()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 582, in get_world_size
    return _get_group_size(group)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 196, in _get_group_size
    _check_default_pg()
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 187, in _check_default_pg
    "Default process group is not initialized"
AssertionError: Default process group is not initialized
=======

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment] 2020-05-15 19:44
@jm90korea can share a repro? It looks like you didn't call [`init_process_group`](https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group) before using DDP or c10d APIs?

**Comment by mrshenli** [comment] 2020-05-19 15:25
Hey @jm90korea, I am closing this issue for now, as the cause seems to be missing call on `init_process_group` before using c10d APIs. Please feel free to reopen if this turns out to be a different problem.

**Closed by mrshenli** 2020-05-19 15:25 UTC
Labels: module: distributed, needs reproduction, triaged
