### ISSUE TITLE
Getting runtime error on pytorch when using VALL-E-X

### ISSUE THREAD

**Issue by kesavakimmich** [pytorch/pytorch#119799] opened 2024-02-13 17:09 UTC
### 🐛 Describe the bug

I am getting runtime error when trying to generate voice using vall-e-x library. I sharing the code below
```
from utils.generation import SAMPLE_RATE, generate_audio, preload_models
from scipy.io.wavfile import write as write_wav

preload_models()
text_prompt = """
Hello, my name is Nose. And uh, and I like hamburger. Hahaha... But I also have other interests such as playing tactic toast.
"""
audio_array = generate_audio(text_prompt)

write_wav("vallex_generation.wav", SAMPLE_RATE, `audio_array)
```

Sharing track below
```
Traceback (most recent call last):
  File "/Users/sivakesavakuchi/Personal/VALL-E-X/run.py", line 11, in <module>
    audio_array = generate_audio(text_prompt)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sivakesavakuchi/Personal/VALL-E-X/utils/generation.py", line 150, in generate_audio
    samples = vocos.decode(features, bandwidth_id=torch.tensor([2], device=device))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos/pretrained.py", line 113, in decode
    audio_output = self.head(x)
                   ^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/vocos/heads.py", line 67, in forward
    S = mag * (x + 1j * y)
                   ~~~^~~
RuntimeError: c10::isComplexType(input.scalar_type()) && c10::isComplexType(other.scalar_type()) INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/operations/BinaryKernel.mm":340, please report a bug to PyTorch. 
```

Also sharing the documentation to install vall-e-x locally below:
[vall e x installation](https://github.com/Plachtaa/VALL-E-X/blob/master/README.md)

### Versions

Collecting environment information...
PyTorch version: 2.2.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.1.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.0.40.1)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.7 (v3.11.7:fa7a6f2303, Dec  4 2023, 15:22:56) [Clang 13.0.0 (clang-1300.0.29.30)] (64-bit runtime)
Python platform: macOS-14.1.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] torch==2.2.0
[pip3] torchaudio==2.2.0
[pip3] torchvision==0.17.0
[conda] Could not collect
```[tasklist]
### Tasks
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by lezcano** [comment] 2024-02-14 14:36
Can you try using the last nightly version? @malfet has been working on improving the complex support on MPS

**Comment by alexicanesse** [comment] 2024-02-15 15:20
I had the same issue with torch version 2.3.0.dev20240124  and the issue is solved on my side with the last nightly build (2.3.0.dev20240215).

**Comment by lezcano** [comment] 2024-02-15 15:22
Closing then

**Closed by lezcano** 2024-02-15 15:22 UTC
Labels: triaged, module: complex, module: mps

**Comment by smartbrandnew** [comment] 2024-03-15 09:04
> Closing then

How can this problem be resolved?

**Comment by lezcano** [comment] 2024-03-15 09:34
It is resolved in master, so just upgrade to the lastest nightly version.
