### ISSUE TITLE
`msort()` can use the 0D tensor of a complex type value against error message

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#129312] opened 2024-06-22 17:06 UTC
### 🐛 Describe the bug

[msort()](https://pytorch.org/docs/stable/generated/torch.msort.html) cannot use the tensor of `complex` type values according to the error message as shown below:

```python
import torch

my_tensor = torch.tensor([7.+5.j])

torch.msort(input=my_tensor) # Error

my_tensor = torch.tensor([[7.+5.j]])

torch.msort(input=my_tensor) # Error
```

> RuntimeError: "sorting_kernel_method_name" not implemented for 'ComplexFloat'

But `msort()` can use the 0D tensor of a `complex` type value against the error message as shown below:

```python
import torch

my_tensor = torch.tensor(7.+5.j)

torch.msort(input=my_tensor)
# tensor(7.+5.j)
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

cc @malfet @albanD

**Comment by malfet** [comment] 2024-06-26 14:45
Closing as duplicate of https://github.com/pytorch/pytorch/issues/129296

**Closed by malfet** 2024-06-26 14:45 UTC
Labels: module: error checking, triaged, module: sorting and selection, module: python frontend, module: edge cases
