### ISSUE TITLE
Transformer Engine Checkpointing Broken on Torch 2.3

### ISSUE THREAD

**Issue by j316chuck** [pytorch/pytorch#122946] opened 2024-03-29 05:52 UTC
### 🐛 Describe the bug

We've been seeing a strange checkpointing bug when using torch 2.3 and Transformer Engine. 

Concretely, in `get_model_state_dict()` for torch 2.3 it seems that we aren't ignoring the `_extra_state` properly when saving checkpoints. If I'm reading the distributed FSDP checkpoint code correctly, it seems to be trying to map the keys in the state_dict into module attributes. This will work for everything that we save with `module.register_parameter(...)` or `module.register_buffer(...)`, but it does not account for the fact that` _extra_state` is not intended to be a registered attribute per PyTorch's own model saving workflow.

- Composer + torch 2.3 checkpoint code path ❌ 
https://github.com/mosaicml/composer/blob/99b86dd7b2ae4ec35c4d84c5d9431577d113180f/composer/core/state.py#L871-L889

- Composer + torch 2.1 checkpoint code path ✅ 
https://github.com/mosaicml/composer/blob/99b86dd7b2ae4ec35c4d84c5d9431577d113180f/composer/core/state.py#L891-L896

Error log attached in message.

### Error logs

[checkpoint_error_log.txt](https://github.com/pytorch/pytorch/files/14800199/checkpoint_error_log.txt)

### Minified repro

- Create simple FSDP Linear model but use transformer engine for linear layers
- try to save FSDP checkpoint with `get_model_state_dict()` in torch 2.3. 

### Versions

Torch 2.3 

cc @LucasLLC @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by awgu** [comment] 2024-03-29 13:50
cc: @wz337 @LucasLLC

**Comment by wz337** [comment] 2024-04-05 21:34
Root cause showing the fix in distributed state dict would rely on a fix for https://github.com/pytorch/pytorch/issues/123411

**Comment by wz337** [comment] 2024-04-05 21:48
Hey, @j316chuck. Based on my understanding, `_extra_state` is included in `state_dict` based on the documentation. https://pytorch.org/docs/stable/generated/torch.nn.Module.html 

So it would be included as part of state_dict and thereby gets saved during checkpoint. Just want to confirm if this aligns with your expectation.

**Comment by j316chuck** [comment] 2024-04-08 22:57
Yes that is in line with our expectation. For some reason from the error log it seems that the model is not able to get the `extra_state` [correctly](https://github.com/pytorch/pytorch/blob/main/torch/nn/modules/module.py#L1696-L1709).

**Comment by j316chuck** [comment] 2024-04-08 22:59
cc: @denera from TE

**Comment by denera** [comment] 2024-04-08 23:29
Hi @wz337 -- `_extra_state` is indeed part of the `state_dict` for our custom Transformer Engine modules, but it is not an attribute of the modules themselves. We're following the `torch.nn.Module` specs in the documentation and returning `_extra_state` via `get_extra_state()`.

The FSDP checkpoint appears to incorrectly assume that `_extra_state` is a module attribute. If this is now expected in any `torch.nn.Module` implementation, we can update ours to match but the documentation for `torch.nn.Module` should also be updated to highlight this change. Otherwise though, FSDP checkpoint should exempt `_extra_state` from the attribute check.

**Comment by wz337** [comment] 2024-04-10 04:05
cc. @fegin

**Comment by fegin** [comment] 2024-04-10 06:42
@denera I'm a little confused. This is the statement from the document:
`Implement this and a corresponding [set_extra_state()](https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.set_extra_state) for your module if you need to store extra state. This function is called when building the module’s state_dict().` 

So the `extra_state` will be included in the `state_dict() call and `get_model_state_dict()` will also call `state_dict()`. In such a case, isn't it legit `get_model_state_dict()` to return the extra state?

**Comment by denera** [comment] 2024-04-11 15:30
@fegin -- TE modules follow the `torch.nn.Module` documentation and correctly implement `get_extra_state()` to return a pickle-able `_extra_state` (as well as the matching `set_extra_state()` to load the same object back into the module).

The issue is that PyTorch's distributed checkpointing is trying to directly access `_extra_state` as a module attribute (i.e. `getattr(module, '_extra_state')`) instead of going through the `get_extra_state()` call. 

To be more specific, [`_get_model_state_dict(model, ...)` calls `_get_fqn(model, key)` on every key in the model's state dictionary](https://github.com/pytorch/pytorch/blob/134e56fa3352aefa208b33b0a86aaabed8033f7a/torch/distributed/checkpoint/state_dict.py#L336), and [`_get_fqn(model, key)` eventually fails at `getattr(cur_obj, cur_obj_name)`](https://github.com/pytorch/pytorch/blob/c83900887f2fb5c7a04e7fd78ad8de7a20f356d4/torch/distributed/checkpoint/state_dict.py#L179) when `cur_obj_name == '_extra_state'`.

Ultimately, `_get_model_state_dict(...)` is making an assumption here that every key in the state dictionary corresponds to a model attribute (like registered parameters and buffers). This is not true for `_extra_state` and the specs for `torch.nn.Module` do not specify any such requirement.

If PyTorch now expects `_extra_state` to be a module attribute, this change needs to be documented in the `torch.nn.Module` specs. We can then modify the TE modules to comply with this.

Otherwise, the `_get_fqn()` needs a new conditional check on `cur_obj_name == '_extra_state'` in order to use `cur_obj = cur_obj.get_extra_state()` to recover the extra states instead of `cur_obj = getattr(cur_obj, cur_obj_name)`.

**Comment by fegin** [comment] 2024-04-15 18:39
Let me understand the question. So the issue you pointed out is not about the `_extra_state` should be or not be in the returned `state_dict`. The issue is about the implementation of `get_model_state_dict` should not directly access the the `_extra_state` as these states are not supposed to be the module attributes. Is my understanding correct?

**Comment by denera** [comment] 2024-04-15 19:10
@fegin Yes, that's right. We need clarification from PyTorch on whether this is intended behavior or a bug, so we can upstream a fix on our end if necessary.

**Comment by fegin** [comment] 2024-04-25 22:55
I'll have a PR to fix this issue.

**Comment by j316chuck** [comment] 2024-05-02 21:07
@fegin curious if we can get this fix in for torch 2.3.1? Composer team is planning on doing a release around this for our FP8 support in Q2.

**Comment by fegin** [comment] 2024-05-03 16:45
The timeline looks possible. Can you try https://github.com/pytorch/pytorch/pull/125336 to see if that PR resolves your issue?

**Comment by azaccor** [comment] 2024-05-15 03:10
@fegin I looked at the above PR, but that does not seem to resolve the incompatibility between mosaic composer library's required torch and cuda versions versus llama v3's preferred ones: If I run 2.1.x+cu118 then I can get llama-v3 to work nicely with transformers, but composer breaks, and if I run 2.3.0+cu121 then I can get composer to run but llama-v3 won't play nice anymore. 
Given that composer is working on the newest stable release of torch it seems like something that needs to be resolved from the llama side. Thoughts?

**Comment by fegin** [comment] 2024-05-16 01:20
No, this is nothing to do with llama. If the model uses the extra_state in a way that torch allows, it is PTD's API should fix the issue. @j316chuck can you verify if the PR fix the issue? We could only cherry-pick the PR if it actually fix the issue. I can only verify through the unittest.

**Comment by j316chuck** [comment] 2024-05-16 17:40
Hey @fegin, is this fix in PyTorch nightly? 

For what it's worth, we recently rebuilt the nightly image: `mosaicml/pytorch:2.4.0_cu121-nightly20240512-python3.11-ubuntu20.04` and our transformer script still fails with the same error: 

```
[rank6]: │ /usr/lib/python3/dist-packages/composer/utils/checkpoint.py:1055 in          │
[rank6]: │ _save_checkpoint                                                             │
[rank6]: │                                                                              │
[rank6]: │   1052 │   │   }                                                             │
[rank6]: │   1053 │   else:                                                             │
[rank6]: │   1054 │   │   state_dict = {                                                │
[rank6]: │ ❱ 1055 │   │   │   'state': state.state_dict(),                              │
[rank6]: │   1056 │   │   │   'rng': reproducibility.get_rng_state(),                   │
[rank6]: │   1057 │   │   }                                                             │
[rank6]: │   1058                                                                       │
[rank6]: │                                                                              │
[rank6]: │ /usr/lib/python3/dist-packages/composer/core/state.py:960 in state_dict      │
[rank6]: │                                                                              │
[rank6]: │    957 │   │   │   if attribute_name == 'dataset_state':                     │
[rank6]: │    958 │   │   │   │   serialized_value = self._dataset_state_dict()         │
[rank6]: │    959 │   │   │   elif attribute_name == 'model':                           │
[rank6]: │ ❱  960 │   │   │   │   serialized_value = self.get_model_state_dict()        │
[rank6]: │    961 │   │   │   elif attribute_name == 'optimizers':                      │
[rank6]: │    962 │   │   │   │   serialized_value = self.get_optim_state_dict()        │
[rank6]: │    963 │   │   │   elif attribute_name == 'algorithms':                      │
[rank6]: │                                                                              │
[rank6]: │ /usr/lib/python3/dist-packages/composer/core/state.py:888 in                 │
[rank6]: │ get_model_state_dict                                                         │
[rank6]: │                                                                              │
[rank6]: │    885 │   │   │   │   │   ),                                                │
[rank6]: │    886 │   │   │   │   )                                                     │
[rank6]: │    887 │   │   │                                                             │
[rank6]: │ ❱  888 │   │   │   model_state_dict = get_model_state_dict(                  │
[rank6]: │    889 │   │   │   │   model=self.model,                                     │
[rank6]: │    890 │   │   │   │   submodules=None,                                      │
[rank6]: │    891 │   │   │   │   options=StateDictOptions(                             │
[rank6]: │                                                                              │
[rank6]: │ /usr/lib/python3/dist-packages/torch/distributed/checkpoint/state_dict.py:65 │
[rank6]: │ 9 in get_model_state_dict                                                    │
[rank6]: │                                                                              │
[rank6]: │    656 │   │   │   submodules=submodules,                                    │
[rank6]: │    657 │   │   │   options=options,                                          │
[rank6]: │    658 │   │   )                                                             │
[rank6]: │ ❱  659 │   │   model_state_dict = _get_model_state_dict(model, info)         │
[rank6]: │    660 │   │   _verify_state_dict(model_state_dict, {}, info)                │
[rank6]: │    661 │   │   return model_state_dict                                       │
[rank6]: │    662                                                                       │
[rank6]: │                                                                              │
[rank6]: │ /usr/lib/python3/dist-packages/torch/distributed/checkpoint/state_dict.py:34 │
[rank6]: │ 3 in _get_model_state_dict                                                   │
[rank6]: │                                                                              │
[rank6]: │    340 │   │   state_dict = _state_dict_fn(model, "state_dict")()            │
[rank6]: │    341 │                                                                     │
[rank6]: │    342 │   for key in list(state_dict.keys()):                               │
[rank6]: │ ❱  343 │   │   fqns = _get_fqns(model, key)                                  │
[rank6]: │    344 │   │   assert len(fqns) == 1                                         │
[rank6]: │    345 │   │   fqn = next(iter(fqns))                                        │
[rank6]: │    346 │   │   if fqn != key:                                                │
[rank6]: │                                                                              │
[rank6]: │ /usr/lib/python3/dist-packages/composer/trainer/mosaic_fsdp_utils.py:633 in  │
[rank6]: │ _get_fqns                                                                    │
[rank6]: │                                                                              │
[rank6]: │   630 │   │   │   │   │   fqn_obj_names.append(curr_obj_name)                │
[rank6]: │   631 │   │   │   else:                                                      │
[rank6]: │   632 │   │   │   │   fqn_obj_names.append(curr_obj_name)                    │
[rank6]: │ ❱ 633 │   │   │   │   curr_obj = getattr(curr_obj, curr_obj_name)            │
[rank6]: │   634 │   │                                                                  │
[rank6]: │   635 │   │   return {'.'.join(fqn_obj_names).replace(_CHECKPOINT_PREFIX, '' │
[rank6]: │   636                                                                        │
[rank6]: │                                                                              │
[rank6]: │ /usr/lib/python3/dist-packages/torch/nn/modules/module.py:1709 in            │
[rank6]: │ __getattr__                                                                  │
[rank6]: │                                                                              │
[rank6]: │   1706 │   │   │   modules = self.__dict__['_modules']                       │
[rank6]: │   1707 │   │   │   if name in modules:                                       │
[rank6]: │   1708 │   │   │   │   return modules[name]                                  │
[rank6]: │ ❱ 1709 │   │   raise AttributeError(f"'{type(self).__name__}' object has no  │
[rank6]: │   1710 │                                                                     │
[rank6]: │   1711 │   def __setattr__(self, name: str, value: Union[Tensor, 'Module'])  │
[rank6]: │   1712 │   │   def remove_from(*dicts_or_sets):                              │
[rank6]: ╰──────────────────────────────────────────────────────────────────────────────╯
[rank6]: AttributeError: 'Linear' object has no attribute '_extra_state'
```
 
 
 Run yaml: 
 ```
 
YAML: 
```
name: mpt-125m-monolithic-regression-fp8
image: mosaicml/pytorch:2.4.0_cu121-nightly20240512-python3.11-ubuntu20.04
scheduling:
  priority: low
compute:
  gpus: 8
  cluster: ***
parameters:
  seed: ${global_seed}
  model:
    name: mpt_causal_lm
    d_model: 768
    fc_type: te
    n_heads: 12
    n_layers: 12
    vocab_size: 50368
    attn_config:
      attn_impl: flash
    init_device: meta
    max_seq_len: ${max_seq_len}
    expansion_ratio: 4
  loggers:
    wandb:
      entity: mosaic-ml
      project: llm-foundry-regressions
  run_name: mpt-125m-monolithic-regression
  callbacks:
    lr_monitor: {}
    speed_monitor:
      window_size: 10
    memory_monitor: {}
    runtime_estimator: {}
  optimizer:
    lr: 0.0006
    eps: 1.0e-08
    name: decoupled_adamw
    betas:
    - 0.9
    - 0.95
    weight_decay: 0
  precision: amp_fp8
  scheduler:
    name: cosine_with_warmup
    alpha_f: 0.1
    t_warmup: 100ba
  tokenizer:
    name: EleutherAI/gpt-neox-20b
    kwargs:
      model_max_length: ${max_seq_len}
  algorithms:
    gradient_clipping:
      clipping_type: norm
      clipping_threshold: 1
  data_local: ./my-copy-c4
  eval_first: false
  data_remote: null
  eval_loader:
    name: text
    dataset:
      local: ${data_local}
      split: val
      remote: ${data_remote}
      shuffle: false
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: false
    num_workers: 8
  fsdp_config:
    verbose: false
    mixed_precision: PURE
    state_dict_type: full
    limit_all_gathers: true
    sharding_strategy: FULL_SHARD
    activation_cpu_offload: false
    activation_checkpointing: false
    activation_checkpointing_reentrant: false
  global_seed: 17
  max_seq_len: 2048
  save_folder: ./{run_name}/checkpoints
  max_duration: 4800ba
  progress_bar: false
  train_loader:
    name: text
    dataset:
      local: ${data_local}
      split: train
      remote: ${data_remote}
      shuffle: true
      max_seq_len: ${max_seq_len}
      shuffle_seed: ${global_seed}
    drop_last: true
    num_workers: 8
  eval_interval: 500ba
  save_interval: 10ba
  log_to_console: true
  console_log_interval: 1ba
  device_eval_batch_size: 16
  eval_subset_num_batches: -1
  global_train_batch_size: 256
  device_train_microbatch_size: auto
integrations:
- integration_type: git_repo
  git_repo: mosaicml/llm-foundry
  git_branch: chuck/bump_torch_2_4
  pip_install: -e .[gpu-flash2]
command: |-
  export MOSAICML_LOG_DIR=false
  cd llm-foundry/scripts
  export NVTE_FRAMEWORK=pytorch && pip install git+https://github.com/NVIDIA/TransformerEngine.git@stable
  python data_prep/convert_dataset_hf.py \
    --dataset c4 --data_subset en \
    --out_root ./my-copy-c4 --splits train_small val_small \
    --concat_tokens 2048 --tokenizer EleutherAI/gpt-neox-20b --eos_text '<|endoftext|>'
  composer train/train.py /mnt/config/parameters.yaml  \ \
    max_duration=20ba \
    train_loader.dataset.split=train_small \
    eval_loader.dataset.split=val_small
  composer train/train.py /mnt/config/parameters.yaml \
    max_duration=40ba  \
    autoresume=false \
    load_path=./mpt-125m-monolithic-regression/checkpoints/ep0-ba20-rank0.pt \
    train_loader.dataset.split=train_small \
    eval_loader.dataset.split=val_small
 ```

**Comment by j316chuck** [comment] 2024-05-16 18:01
Apologies, looking at the stack trace it seems that we monkey patch the fqn fix in mosaic_fsdp_utils.py. Let me try adding your fix in our monkey patch

**Comment by j316chuck** [comment] 2024-05-17 19:55
@fegin we have validated that this PR fixes the TE ckpting extra state issue once monkey-patched into our composer `mosaic_fsdp_utils` . Composer monkey-patch PR [here](https://github.com/mosaicml/composer/pull/3298/files). Thanks for your work on this!

@mvpatel2000 has started the cherry-pick for this issue into torch-2.3.1 at https://github.com/pytorch/pytorch/issues/125425#issuecomment-2118261677.

**Comment by fegin** [comment] 2024-05-20 16:57
Close the issue because it is fixed by https://github.com/pytorch/pytorch/pull/125336

**Closed by fegin** 2024-05-20 16:57 UTC
Labels: triaged, module: distributed_checkpoint
