### ISSUE TITLE
[ppc64le] test_torch.py test failing in test_qr

### ISSUE THREAD

**Issue by avmgithub** [pytorch/pytorch#3716] opened 2017-11-15 16:28 UTC
Running on Ubuntu 16.04 ppc64le , when running test_torch.py  test fails in test_qr.  Test only fails when running on Virtual Machine.

$ python -m unittest test_torch.TestTorch.test_qr
check_qr 1
check_qr 2
check_qr 3
check big matrix 4
F

FAIL: test_qr (test_torch.TestTorch)

Traceback (most recent call last):
  File "/home/ubuntu/builder/jenkins/pytorch/pytorch/test/common.py", line 53, in wrapper
    fn(*args, **kwargs)
  File "/home/ubuntu/builder/jenkins/pytorch/pytorch/test/test_torch.py", line 2127, in test_qr
    self.assertEqual(a, a_qr, prec=1e-3)
  File "/home/ubuntu/builder/jenkins/pytorch/pytorch/test/common.py", line 204, in assertEqual
    assertTensorsEqual(x, y)
  File "/home/ubuntu/builder/jenkins/pytorch/pytorch/test/common.py", line 196, in assertTensorsEqual
    self.assertLessEqual(max_err, prec, message)
AssertionError: 5.990425851987622 not less than or equal to 0.001 :

----------------------------------------------------------------------
Ran 1 test in 0.457s

FAILED (failures=1)

This only fails when running on a virtual machine.  Baremetal systems do not seem to exhibit the failure. Also this particular line seems to affect the failure:
a = torch.randn(1000, 1000)  after the comment # check big matrix

If I change this to a = torch.randn(130, 130),   in most cases the test passes but there are random failures.

If someone can please point me to where the torch.randn  code is , I'll see if I can figure this out.

**Comment by soumith** [comment] 2017-11-16 04:47
the torch.randn code eventually links to 

https://github.com/pytorch/pytorch/blob/master/aten/src/TH/generic/THTensorRandom.c#L80
https://github.com/pytorch/pytorch/blob/master/aten/src/TH/THRandom.c#L253

**Comment by sdmonov** [comment] 2017-12-08 18:12
Hi,

I found that the problem is in the LAPACK implementation in OpenBLAS. OpenBLAS 0.2.19 has issues detecting the correct number of CPUs and this leads to some threading issues as far as I can understand. This happens on Virtual Machines and also on other systems where there are CPU limitations. As of today Conda provides OpenBLAS 0.2.19 on ppc64le. RHEL 7.4 ships with OpenBLAS 0.2.20 and Ubuntu 16.04 ships with OpenBLAS 0.2.18. I tested both RHEL 7.4 and Ubuntu 16.04 and it works fine with them.

The PR in OpenBLAS that fixes the problem is https://github.com/xianyi/OpenBLAS/pull/981.

**Comment by avmgithub** [comment] 2018-05-09 11:53
I'm also using openBlas 0.2.20.
$ rpm -qa | grep blas
libopenblas-0.2.20-2528.e2e928f.ppc64le
Are you using the version that comes from the OS  or from PowerAI

**Comment by hartb** [comment] 2018-05-09 21:51
Problem doesn't seem to reproduce with environment variable `OMP_NUM_THREADS=1` set, so it's presumably an issue with OpenBLAS multi-threading that shows up on Power9.

**Comment by deepali-c** [comment] 2018-06-29 13:37
I am able to reproduce this issue with the following snippet:

```
import torch
a = torch.randn(1000,1000)
q,r = torch.qr(a)
m,tau = torch.geqrf(a)
a_qr = torch.orgqr(m,tau)
m_triu = torch.triu(m)
y = float(max(max(x) for x in q - a_qr))
z = float(max(max(x) for x in r - m_triu))

print("Q max diff = {0:.6f}{1}".format(y, " FAIL!" if y > 0.001 else ""))
print("R max diff = {0:.6f}{1}".format(z, " FAIL!" if z > 0.001 else ""))
```

**Comment by ezyang** [comment] 2020-05-26 16:09
Given https://github.com/pytorch/pytorch/issues/3716#issuecomment-350332992 I am optimistically closing this as fixed.

**Closed by ezyang** 2020-05-26 16:09 UTC
Labels: module: POWER, todo, topic: dependency bug, triaged
