### ISSUE TITLE
`matmul()` outputs `tensor(0.)` with two of empty 1D tensors

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130061] opened 2024-07-03 21:12 UTC
### 🐛 Describe the bug

[matmul()](https://pytorch.org/docs/stable/generated/torch.matmul.html) outputs `tensor(0.)` with two of empty 1D tensors as shown below:

```python
import torch

t1 = torch.tensor([])
t2 = torch.tensor([])

torch.matmul(input=t1, other=t2)
# tensor(0.)

# Additional
t1 = torch.tensor([0.])
t2 = torch.tensor([0.])

torch.matmul(input=t1, other=t2)
# tensor(0.)
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by malfet** [comment] 2024-07-03 23:12
Please refer to the documentation to make a judgement whether or not file one or two issue, as doc for [torch.matmul ](https://pytorch.org/docs/stable/generated/torch.matmul.html)clearly says that:
> If both tensors are 1-dimensional, the dot product (scalar) is returned.

Therefore, closing as duplicate of https://github.com/pytorch/pytorch/issues/130063

**Closed by malfet** 2024-07-03 23:12 UTC
