### ISSUE TITLE
Better error message when a quantized operator is not supported

### ISSUE THREAD

**Issue by lly-zero-one** [pytorch/pytorch#24395] opened 2019-08-15 07:29 UTC
## 🚀 Feature
Currently, the quantization flow insert the observer for non-supported operator module. In the runtime, the error message will be always something like the following:
```
... 
self.min_val = torch.min(torch.min(x), self.min_val)
RuntimeError: No function is registered for schema aten::min.other(Tensor self, Tensor other) -> Tensor on backend QuantizedCPU

We had better to report the corresponding unsupported operator module.

Maybe a simple fix could be checking the mapping table and avoid the insertion of observer for non-supported operator module.

## Motivation
```

## Additional context

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @pytorch/quantization

**Comment by jerryzh168** [comment] 2019-08-15 16:21
although we probably need to support this function, but it looks like you have extra observer in quantized model. 
As we discussed this is caused by empty Sequential, it will be fixed in https://github.com/pytorch/pytorch/pull/23753

**Comment by jerryzh168** [comment] 2019-12-03 00:54
fixed now I think

**Closed by jerryzh168** 2019-12-03 00:54 UTC
Labels: quantization, triaged
