### ISSUE TITLE
[Break XPU][Inductor UT] The cpu test case `TestFlexAttention::test_GQA_float32_score_mod6` failed on XPU server.

### ISSUE THREAD

**Issue by etaf** [pytorch/pytorch#142367] opened 2024-12-09 12:50 UTC
### 🐛 Describe the bug

The CPU test case `test/inductor/test_flex_attention.py::TestFlexAttention::test_GQA_float32_score_mod6`  introduced in #141453 failed on XPU server, the error log: https://hud.pytorch.org/pr/pytorch/pytorch/142348#34118282020
```
2024-12-09T09:39:32.4631704Z ============================= test session starts ==============================
2024-12-09T09:39:32.4632134Z platform linux -- Python 3.9.21, pytest-7.3.2, pluggy-1.5.0 -- /opt/conda/envs/py_3.9/bin/python
2024-12-09T09:39:32.4632529Z cachedir: .pytest_cache
2024-12-09T09:39:32.4632995Z hypothesis profile 'pytorch_ci' -> database=None, max_examples=50, derandomize=True, suppress_health_check=[HealthCheck.too_slow]
2024-12-09T09:39:32.4633494Z rootdir: /var/lib/jenkins/pytorch
2024-12-09T09:39:32.4633754Z configfile: pytest.ini
2024-12-09T09:39:32.4634184Z plugins: hypothesis-5.35.1, xdoctest-1.1.0, cpp-2.3.0, xdist-3.3.1, flakefinder-1.1.0, rerunfailures-14.0, typeguard-4.3.0
2024-12-09T09:39:32.4634711Z collecting ... collected 528 items / 266 deselected / 262 selected
2024-12-09T09:39:32.4635305Z stepcurrent: skipping 0 already run items. Running only test/inductor/test_flex_attention.py::TestFlexAttention::test_GQA_float32_score_mod6
2024-12-09T09:39:32.4635846Z Running 1 items in this shard
2024-12-09T09:39:32.4636001Z 
2024-12-09T09:39:32.4636271Z inductor/test_flex_attention.py::TestFlexAttention::test_GQA_float32_score_mod6 free(): invalid pointer
2024-12-09T09:39:32.4636701Z Fatal Python error: Aborted
2024-12-09T09:39:32.4636920Z 
```

### Versions

PyTorch version: 2.6.0a0+git05c1f37
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.29.4
Libc version: glibc-2.35

Python version: 3.9.20 | packaged by conda-forge | (main, Sep 30 2024, 17:49:10) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.15.47+prerelease23.5.18-x86_64-with-glibc2.35

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @yf225 @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by jianan-gu** [comment] 2024-12-09 15:57
Tried to pull the docker image below that is used in CI but unable to reproduce the issue. 
```
docker pull ghcr.io/pytorch/ci-image:pytorch-linux-jammy-xpu-2024.0-py3-fe9ef91eb32c6792150cb8f81eb86e60bdc42347
```

**Comment by jianan-gu** [comment] 2024-12-10 09:45
Hi @etaf , we refined the PR https://github.com/pytorch/pytorch/pull/141453 and this issue will not be there to block xpu. Could you have a check if possible (once the PR merged maybe), and close this issue if it is double confirmed on your side. Thanks.

**Closed** 2024-12-10 12:46 UTC
Labels: module: cpu, triaged, oncall: pt2, module: higher order operators, module: pt2-dispatcher, module: flex attention

**Comment by etaf** [comment] 2024-12-10 12:55
> Hi @etaf , we refined the PR #141453 and this issue will not be there to block xpu. Could you have a check if possible (once the PR merged maybe), and close this issue if it is double confirmed on your side. Thanks.

Great, thanks~.
