### ISSUE TITLE
torch.argmax only returns -9223372036854775808 on mps 

### ISSUE THREAD

**Issue by kevinfjiang** [pytorch/pytorch#98191] opened 2023-04-03 06:37 UTC
### 🐛 Describe the bug

Calling torch.argmax on a mps tensor results in -9223372036854775808 for all outputs. torch.argmax works fine on cpu. No exception is raised during execution. I've tested this after reinstalling in a new anaconda env and the result was the same

```python
import torch

cpu_tensor = torch.tensor([[0, 1], [2,1], [1, 0]])
torch.argmax(cpu_tensor, dim=1)  # tensor([1, 0, 0])

mps_tensor = cpu_tensor.to(torch.device('mps'))
torch.argmax(mps_tensor, dim=1)  # tensor([-9223372036854775808, -9223372036854775808, -9223372036854775808], device='mps:0')
```

### Versions

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.11.2 | packaged by conda-forge | (main, Mar 31 2023, 17:54:27) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[pip3] torchvision==0.15.1
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchvision               0.15.1                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by pat749** [comment] 2023-04-04 06:30
The MPS device currently does not support some of the tensor operations including `torch.argmax`. Thus, when you call `torch.argmax` on an MPS tensor, it returns an incorrect value of -9223372036854775808 for all outputs instead of raising an exception.

**Comment by TheBloke** [comment] 2023-04-04 18:31
FYI this issue is a duplicate of : https://github.com/pytorch/pytorch/issues/92311

Also, `torch.multinomial()` is affected as well (I believe because it calls argmax in the C++ code)

As per info in the other issue:
1. You can work around the lack of working `torch.argmax(...)` by running `torch.max(...).indices` instead
2. To work around the lack of `multinomial()` you can write code to do the same operation manually in a few steps.

**Comment by todochenxi** [comment] 2023-04-05 12:30
I also found this problem and used another method
<img width="350" alt="image" src="https://user-images.githubusercontent.com/108149467/230080858-f1cddb0b-74ec-4784-b79f-63405e460d04.png">

**Comment by todochenxi** [comment] 2023-04-05 13:07
or 
<img width="568" alt="image" src="https://user-images.githubusercontent.com/108149467/230089578-d3fc8d70-c364-417c-87f1-31aa91005904.png">

**Comment by TheBloke** [comment] 2023-04-05 13:10
Yeah using `max` is better than moving to CPU I would say.

I have been using this syntax:
`y_hat = torch.max(y_hat, 1).indices`

**Comment by todochenxi** [comment] 2023-04-05 13:26
> Yeah using `max` is better than moving to CPU I would say.
> 
> I have been using this syntax: `y_hat = torch.max(y_hat, 1).indices`

thank you very much

**Comment by malfet** [comment] 2023-04-10 23:29
Seem specific to AMD GPUs. @kevinfjiang can you try upgrading to MacOS-13.3 and see if it's the problem there.

**Comment by TheBloke** [comment] 2023-04-11 07:02
> Seem specific to AMD GPUs. @kevinfjiang can you try upgrading to MacOS-13.3 and see if it's the problem there.

It is still an issue in 13.3 and 13.3.1. This is being discussed in the other bug thread: https://github.com/pytorch/pytorch/issues/92311#issuecomment-1500937251

**Closed** 2023-06-30 18:11 UTC
Labels: triaged, module: mps
