### ISSUE TITLE
[feature request] torch.aminmax

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#62161] opened 2021-07-25 10:13 UTC
Often min and max are computed together (e.g. for min-max normalization). It may be convenient to have a special idiomatic method for this (similar to torch.std_mean, torch.var_mean). At least, for version that doesn't return the index, it may be a reasonably convenient API

it exists in opencv as `cv2.minMaxLoc`

**Comment by ngimel** [comment] 2021-07-25 19:00
Duplicate of #62164, functionality exists already as torch._aminmax

**Closed by ngimel** 2021-07-25 19:00 UTC

**Comment by vadimkantorov** [comment] 2021-07-25 19:10
@ngimel I don't mind you closing this one, but i would claim that it's #62164 that's duplicate of this earlier one #62161 ^^

**Comment by vadimkantorov** [comment] 2021-07-25 19:12
So the proposal is then to make torch._aminmax public and supported

**Comment by ngimel** [comment] 2021-07-25 19:19
> @ngimel I don't mind you closing this one, but i would claim that it's #62164 that's duplicate of this earlier one #62161 ^^

True, but #62164 already mentions that the requested functionality exists, so it's a more accurate request of making it public API.
