### ISSUE TITLE
 `torch.Tensor.clamp` and `torch.Tensor.clamp_` are still not implemented for the sparse backend.

### ISSUE THREAD

**Issue by ILoveSE** [pytorch/pytorch#95351] opened 2023-02-23 01:56 UTC
### 🐛 Describe the bug

In Pytorch 1.12/ 1.13/ 1.13.1/ nightly versions, none of these clamp-related functions seem to support the SparseCPU backend.
If using the SparseCPU backend in `clamp`, it will raise an error.
`NotImplementedError: Could not run 'aten::clamp' with arguments from the 'SparseCPU' backend.`
But the `clamp` operation supports the SparseCsrCPU backend.
It should be related to [#82494](https://github.com/pytorch/pytorch/issues/82494)

### To Reproduce
```python
import torch

sparse_tensor = torch.sparse_coo_tensor([[1,1]], [1,1], (2,))
torch.Tensor.clamp(sparse_tensor, -1, 1)
# torch.Tensor.clamp_(sparse_tensor, -1, 1)
```

<details>
  <summary>The error result is</summary>
  <pre><code>
  NotImplementedError: Could not run 'aten::clamp' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::clamp' is only available for these backends: [CPU, CUDA, HIP, MPS, IPU, XPU, HPU, VE, Meta, MTIA, PrivateUse1, PrivateUse2, PrivateUse3, FPGA, ORT, Vulkan, Metal, QuantizedCPU, QuantizedCUDA, QuantizedHIP, QuantizedMPS, QuantizedIPU, QuantizedXPU, QuantizedHPU, QuantizedVE, QuantizedMeta, QuantizedMTIA, QuantizedPrivateUse1, QuantizedPrivateUse2, QuantizedPrivateUse3, CustomRNGKeyId, MkldnnCPU, SparseCsrCPU, SparseCsrCUDA, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].

  Undefined: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  CPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCPU.cpp:31085 [kernel]
  CUDA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCUDA.cpp:44037 [kernel]
  HIP: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  MPS: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  IPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  XPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  HPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  VE: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  Meta: registered at /dev/null:219 [kernel]
  MTIA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  PrivateUse1: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  PrivateUse2: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  PrivateUse3: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  FPGA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  ORT: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  Vulkan: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  Metal: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedCPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterQuantizedCPU.cpp:929 [kernel]
  QuantizedCUDA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedHIP: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedMPS: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedIPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedXPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedHPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedVE: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedMeta: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedMTIA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  QuantizedPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  CustomRNGKeyId: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  MkldnnCPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  SparseCsrCPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  SparseCsrCUDA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/build/aten/src/ATen/RegisterCompositeExplicitAutogradNonFunctional.cpp:21456 [default backend kernel]
  BackendSelect: fallthrough registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/core/BackendSelectFallbackKernel.cpp:3 [backend fallback]
  Python: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/core/PythonFallbackKernel.cpp:144 [backend fallback]
  FuncTorchDynamicLayerBackMode: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/functorch/DynamicLayer.cpp:491 [backend fallback]
  Functionalize: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/FunctionalizeFallbackKernel.cpp:280 [backend fallback]
  Named: fallthrough registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/core/NamedRegistrations.cpp:11 [kernel]
  Conjugate: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/ConjugateFallback.cpp:17 [backend fallback]
  Negative: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/native/NegateFallback.cpp:19 [backend fallback]
  ZeroTensor: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/ZeroTensorFallback.cpp:86 [backend fallback]
  ADInplaceOrView: fallthrough registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/core/VariableFallbackKernel.cpp:63 [backend fallback]
  AutogradOther: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradCPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradCUDA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradHIP: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradXLA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradMPS: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradIPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradXPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradHPU: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradVE: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradLazy: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradMeta: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradMTIA: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradPrivateUse1: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradPrivateUse2: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradPrivateUse3: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  AutogradNestedTensor: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/VariableType_2.cpp:17483 [autograd kernel]
  Tracer: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/torch/csrc/autograd/generated/TraceType_2.cpp:16868 [kernel]
  AutocastCPU: fallthrough registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/autocast_mode.cpp:487 [backend fallback]
  AutocastCUDA: fallthrough registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/autocast_mode.cpp:354 [backend fallback]
  FuncTorchBatched: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/functorch/BatchRulesBinaryOps.cpp:324 [kernel]
  FuncTorchVmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/functorch/VmapModeRegistrations.cpp:28 [backend fallback]
  Batched: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/LegacyBatchingRegistrations.cpp:1077 [kernel]
  VmapMode: fallthrough registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/VmapModeRegistrations.cpp:33 [backend fallback]
  FuncTorchGradWrapper: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/functorch/TensorWrapper.cpp:210 [backend fallback]
  PythonTLSSnapshot: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/core/PythonFallbackKernel.cpp:152 [backend fallback]
  FuncTorchDynamicLayerFrontMode: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/functorch/DynamicLayer.cpp:487 [backend fallback]
  PythonDispatcher: registered at /opt/conda/conda-bld/pytorch_1676794384034/work/aten/src/ATen/core/PythonFallbackKernel.cpp:148 [backend fallback]</code></pre>
</details>

### Expected behavior
Hopefully, the support for SparseCPU can be implemented, or explain the backend that `clamp` does not support in the corresponding [docs](https://pytorch.org/docs/stable/generated/torch.clamp.html#torch.clamp).

Is it possible to support this backend in PyTorch 2.0?

### Versions

<details>
  <summary>pytorch 1.12.0</summary>
  <pre><code>
  [pip3] numpy==1.21.5
  [pip3] torch==1.12.0
  [pip3] torchelastic==0.2.0
  [pip3] torchtext==0.13.0
  [pip3] torchvision==0.13.0
  [conda] blas                      1.0                         mkl  
  [conda] cudatoolkit               11.3.1               ha36c431_9    nvidia
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py37h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py37hd3c417c_0  
  [conda] mkl_random                1.2.2            py37h51133e4_0  
  [conda] numpy                     1.21.5           py37he7a7128_2  
  [conda] numpy-base                1.21.5           py37hf524024_2  
  [conda] pytorch                   1.12.0          py3.7_cuda11.3_cudnn8.3.2_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.0                    pypi_0    pypi
  [conda] torchtext                 0.13.0                     py37    pytorch
  [conda] torchvision               0.13.0               py37_cu113    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.13.0</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.0
  [pip3] torchtext==0.14.0
  [pip3] torchvision==0.14.0
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0            py39h7f8727e_0  
  [conda] mkl_fft                   1.3.1            py39hd3c417c_0  
  [conda] mkl_random                1.2.2            py39h51133e4_0  
  [conda] numpy                     1.22.3           py39he7a7128_0  
  [conda] numpy-base                1.22.3           py39hf524024_0  
  [conda] pytorch                   1.13.0          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_0    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchtext                 0.14.0                     py39    pytorch
  [conda] torchvision               0.14.0               py39_cu116    pytorch</code></pre>
</details>

<details>
  <summary>pytorch 1.13.1</summary>
  <pre><code>
  [pip3] numpy==1.22.3
  [pip3] torch==1.13.1
  [pip3] torchelastic==0.2.2
  [pip3] torchtext==0.14.1
  [pip3] torchvision==0.14.1
  [conda] blas                      1.0                         mkl  
  [conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
  [conda] mkl                       2021.4.0           h06a4308_640  
  [conda] mkl-service               2.4.0           py310h7f8727e_0  
  [conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
  [conda] mkl_random                1.2.2           py310h00e6091_0  
  [conda] numpy                     1.22.3          py310hfa59a62_0  
  [conda] numpy-base                1.22.3          py310h9585f30_0  
  [conda] pytorch                   1.13.1          py3.10_cuda11.6_cudnn8.3.2_0    pytorch
  [conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
  [conda] pytorch-mutex             1.0                        cuda    pytorch
  [conda] torchelastic              0.2.2                    pypi_0    pypi
  [conda] torchtext                 0.14.1                    py310    pytorch
  [conda] torchvision               0.14.1              py310_cu116    pytorch</code></pre>
</details>

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by amjames** [comment] 2023-02-27 20:55
> ... It should be related to [#82494](https://github.com/pytorch/pytorch/issues/82494)

I believe this is actually a duplicate issue rather than just related. Both issues report missing functionality. If you could provide information on your use-case that can help us prioritize this feature. 

> Hopefully, the support for SparseCPU can be implemented, or explain the backend that clamp does not support in the corresponding [docs](https://pytorch.org/docs/stable/generated/torch.clamp.html#torch.clamp).

As sparse is still designated as a beta feature (See the warning [here](https://pytorch.org/docs/stable/sparse.html) ). The documentation is written with the assumption that most operators doe not support sparse unless sparse support is mentioned. I don't think it is sustainable for us to add a note about missing operator coverage to every operator without support. 

> Is it possible to support this backend in PyTorch 2.0?

The 2.0 release is already closed to features, so no. The earliest this could appear would be 2.1 if we are able to prioritize development.

Further discussion, regarding your use case and the importance of this feature can continue on the original issue. However to avoid splitting the information I will close this as a duplicate of #82494.

**Closed by amjames** 2023-02-27 20:55 UTC
Labels: module: sparse, triaged

**Comment by ILoveSE** [comment] 2023-02-28 02:18
> The 2.0 release is already closed to features, so no. The earliest this could appear would be 2.1 if we are able to prioritize development.
> 
> Further discussion, regarding your use case and the importance of this feature can continue on the original issue. However to avoid splitting the information I will close this as a duplicate of #82494.

Thank you very much for your explanation!
I have now understood the basic relationship between these APIs and the sparse-related issues.
If there are other questions, I will continue to discuss them under the [original question](https://github.com/pytorch/pytorch/issues/82494).
Thanks again.
