### ISSUE TITLE
odd behavior w/ add_out_dense_sparse_cuda

### ISSUE THREAD

**Issue by realdoug** [pytorch/pytorch#12633] opened 2018-10-14 14:22 UTC
## 🐛 Bug

Given the following code, the two sparse tensors constructed here appear identical, but produce two different results when added to a 0 tensor of the same shape.

```c++
#include <torch/torch.h>
#include <ATen/SparseTensorImpl.h>
#include <iostream>
#include <vector>

using at::Tensor;
using at::SparseTensorImpl;

Tensor make_sparse_from_indices(Tensor& indices, at::TensorOptions opts){
  at::Tensor vals = at::tensor({3, 0, 0, 9, 0, 0}, opts).view({2, 3});
  at::Tensor sparse = at::sparse_coo_tensor(indices, vals, {3, 3, 3}, opts);
  _get_sparse_impl(sparse)->set_coalesced(true);

  return sparse;
}

int main() {
  at::TensorOptions opts = at::device(at::kCUDA).dtype(at::kLong);

  Tensor inds1 = at::tensor({0, 1, 0, 0}, opts).view({2, 2});
  Tensor inds2 = inds1.transpose(0,1).clone().transpose(0,1);//.clone();

  Tensor sparse1 = make_sparse_from_indices(inds1, opts);
  Tensor sparse2 = make_sparse_from_indices(inds2, opts);

  Tensor z1 = at::zeros({3, 3, 3}, opts);
  std::cout << z1.add(sparse1) << std::endl;
  printf("\n===\n");
  std::cout << z1.add(sparse2) << std::endl;

  /* line 28 and line 29 do not produce the same result */
}
```

Un-commenting the call to ```clone()``` fixes the issue.  The answer might be  "Just use ```coalesce()``` instead of manually setting the flag", but the only reason this works is because ```coalesce()``` appears to always make a clone of indices*.  That strikes me as just another way of accomplishing the same thing & not fully answering why an extra call to ```clone()``` is needed.

This is a simplified reproduction of an issue that came up when trying to implement ```dense.to_sparse()``` (#12171).  When converting a dense tensor to sparse, we know there won't be any dupe indices, so I'm trying to determine whether I really need to call the entire ```coalesce()``` routine or not.

*unless ```is_coalesced``` is already true.

## To Reproduce

See code snippet above.  Issue only appears on CUDA.

## Expected behavior
both calls to ```add``` should return the same result

## Environment

Please copy and paste the output from our
Collecting environment information...
PyTorch version: 1.0.0a0+894e4ec
Is debug build: No
CUDA used to build PyTorch: 9.2.148

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla P4
Nvidia driver version: 396.54
cuDNN version: Probably one of the following:
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.0.5
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] torch (1.0.0a0+2745997, /home/dougfriedman/anaconda3/envs/pytorch-dev/lib/python3.7/site-packages)
[conda] magma-cuda92              2.3.0                         1    pytorch
[conda] torch                     0.5.0a0+7561bbb           <pip>
[conda] torch                     1.0.0a0+3ab005f           <pip>
[conda] torch                     1.0.0a0+90965fc           <pip>
[conda] torch                     1.0.0a0+efcc8a0           <pip>
[conda] torch                     0.5.0a0+2c31971           <pip>
[conda] torch                     1.0.0a0+1d35ab2           <pip>
[conda] torch                     1.0.0a0+a6f8553           <pip>
[conda] torch                     1.0.0a0+faa60ee           <pip>
[conda] torch                     1.0.0a0+1e70500           <pip>
[conda] torch                     1.0.0a0+15539b0           <pip>
[conda] torch                     1.0.0a0+61264b7           <pip>
[conda] torch                     1.0.0a0+2745997           <pip>
[conda] torch                     1.0.0a0+367874            <pip>
[conda] torch                     1.0.0a0+e8a828e           <pip>
[conda] torch                     1.0.0a0+c4f0628           <pip>
[conda] torch                     0.5.0a0+13f9214           <pip>
[conda] torch                     1.0.0a0+894e4ec           <pip>
[conda] torch                     1.0.0a0+5cb2b23           <pip>

cc @aocsa @nikitaved @pearu @mruberry @gchanan

**Comment by weiyangfb** [comment] 2018-10-15 19:00
Will this be fixed by asserting `indicies.is_contiguous()` in sparse constructors?

**Comment by weiyangfb** [comment] 2018-10-16 21:06
@SsnL what's the proper fix for this issue?

**Comment by realdoug** [comment] 2018-10-16 22:08
Would step A be figuring out a non-contiguous test case to add to the sparse test suite and identifying which functions need work?

**Comment by SsnL** [comment] 2018-10-17 02:56
@weiyangfb Quick fix would be enforcing contiguity in sparse tensor ctor. Real fix is to fix the kernels because users can still ._indices().as_strided_(...)

**Comment by weiyangfb** [comment] 2018-10-17 18:08
@SsnL yeah, right now all sparse methods can assert `indices.is_contiguous()` until kernels can work with non-contiguous indices.

**Comment by weiyangfb** [comment] 2018-10-17 21:05
calling `indices.contiguous()` and `values.contiguous()` everywhere still looks cumbersome. Previously people relies on `SparseTensor.coalesce()` to assert contiguity. But this is no long true since `set_coalesced()` is exposed. To ensure contiguity, currently I have to write code this way:
```
SparseTensor sparse = sparse_.coalesce();

  // Ensure indices and values to be contiguous,
  // This is because set_coalesced() can mutate the coalesce bit,
  // and so sparse_.coalesce() doesn't guarantee contiguity.
  // Remove this when kernels in this function can deal with non-contiguous case.
  LongTensor indices = sparse._indices().contiguous();
  Tensor values = sparse._values().contiguous();
  AT_ASSERT(indices.is_contiguous());
  AT_ASSERT(values.is_contiguous());
```

**Comment by weiyangfb** [comment] 2018-10-17 22:02
If we want to keep `set_coalesced()`, can we have `is_coalesced()` explicitly check if the indices is both unique and sorted? We should be able to parallelize it in both of CPU and CUDA by checking left and right neighbors for each index.
@ezyang @SsnL @zou3519

**Comment by SsnL** [comment] 2018-10-17 22:47
FWIW, set_coalesced is becoming _coalesced_, a part of the unsafe
use-at-your-own-discretion API.

**Comment by weiyangfb** [comment] 2018-10-17 23:16
@SsnL I see, can we also have a `_coalesced_safe` to do the explicit check? Right there is no easy way to safely assert a sparse tensor is truly coalesced.

**Comment by weiyangfb** [comment] 2018-10-18 00:28
I see, with that we can close this issue.

**Comment by SsnL** [comment] 2018-10-18 00:47
This should be open until we have ways to deal with noncontiguous indices and values. Either some note+error msg, or make the kernels work.

**Comment by cpuhrsch** [comment] 2021-07-27 20:55
I'm trying to reproduce this using the Python frontend, but can't seem to get it to fail. I'm using
```
import torch

def make_sparse_from_indices(indices, vals):
    print("indices.stride: ", indices.stride())
    print("vals.stride: ", vals.stride())
    sparse = torch.sparse_coo_tensor(indices, vals, (3, 3, 3))
    return sparse

inds1 = torch.tensor([0, 1, 0, 0]).view(2, 2).cuda()
inds2 = inds1.t().contiguous().t().cuda()

vals1 = torch.tensor([3, 0, 0, 9, 0, 0]).view(2, 3).cuda()
vals2 = vals1

sparse1 = make_sparse_from_indices(inds1, vals1)
print(sparse1.indices.stride())
sparse2 = make_sparse_from_indices(inds2, vals2)
print(sparse2.indices.stride())

z1 = torch.zeros(3, 3, 3).cuda()
print(z1.add(sparse1))
print(z1.add(sparse2))
```

Did we land something that fixes this in the last 3 years?

**Comment by cpuhrsch** [comment] 2021-07-27 21:13
Looks like https://github.com/pytorch/pytorch/issues/17950 addressed this issue and the PR https://github.com/pytorch/pytorch/pull/18179 fixed it.

**Closed by cpuhrsch** 2021-07-27 21:13 UTC
Labels: module: sparse, module: tensor creation, triaged
