### ISSUE TITLE
Reduce manylinux wheel size for x86_64 arch

### ISSUE THREAD

**Issue by aignas** [pytorch/pytorch#94262] opened 2023-02-07 02:37 UTC
### 🚀 The feature, motivation and pitch

Right now the linux x86_64 wheels are huge and are more than 800MB, whilst the aarch64 counterparts are much smaller.
Supplying the manylinux2014 wheels in addition to the manylinux1 wheels may provide users access to potential size optimizations because of fewer deps needing to be bundled within the wheel (this is an assumption on my part and maybe someone can clarify why the size is so large).

Source: https://pypi.org/project/torch/#files

### Alternatives

Do nothing and keep downloading the existing wheels. Whilst this works, it increases the size of the docker images and the amount of data that a user needs to download to just work with the package.

cc @ezyang @seemethere @malfet

**Comment by Skylion007** [comment] 2023-02-07 14:52
Related to #93955 and partial duplicate of #34058

**Comment by seemethere** [comment] 2023-02-07 18:31
The difference in the size of wheels has less to do with manylinux2014 vs. manylinux1 and more to do with the fact that the linux x86_64 wheels that are larger than 800MB typically have CUDA dependencies bundled with them.

So unfortunately it's not really something that can be drastically reduced since we want to keep the CUDA experience as simple as possible but has been something that's been talked about for a long time.

Past discussions on this:
* https://github.com/pytorch/pytorch/issues/26340
* https://github.com/pytorch/pytorch/issues/34058
* https://github.com/pytorch/pytorch/issues/17621
* https://github.com/pytorch/pytorch/issues/17023 (related in terms of size issues, but for conda)

With the past discussions linked here I think we can safely close this as a duplicate but we do understand the issues here and are continually trying to investigate ways to make the binaries smaller, but unfortunately there are just not a whole lot of things we can do to drastically change the binary sizes.

**Closed by seemethere** 2023-02-07 18:31 UTC
Labels: oncall: binaries
