### ISSUE TITLE
python3.10 windows wheels >=1.12.0 silently requires numpy>=1.23.0

### ISSUE THREAD

**Issue by jvesely** [pytorch/pytorch#100690] opened 2023-05-05 05:21 UTC
### 🐛 Describe the bug

```
PS C:\> ~\AppData\Local\Microsoft\WindowsApps\python3.10.exe -m venv .\test-venv 
PS C:\> .\test-venv\Scripts\Activate.ps1
(test-venv) PS C:\> pip install numpy==1.22.4
Collecting numpy==1.22.4
  Using cached numpy-1.22.4-cp310-cp310-win_amd64.whl (14.7 MB)
Installing collected packages: numpy
Successfully installed numpy-1.22.4

[notice] A new release of pip is available: 23.0.1 -> 23.1.2    
[notice] To update, run: python.exe -m pip install --upgrade pip
(test-venv) PS C:\> pip install torch
Collecting torch
  Using cached torch-2.0.0-cp310-cp310-win_amd64.whl (172.3 MB)
Collecting filelock
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting sympy
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, filelock, jinja2, torch
Successfully installed MarkupSafe-2.1.2 filelock-3.12.0 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 sympy-1.11.1 torch-2.0.
0 typing-extensions-4.5.0

[notice] A new release of pip is available: 23.0.1 -> 23.1.2    
[notice] To update, run: python.exe -m pip install --upgrade pip
(test-venv) PS C:\> python -c 'import torch; torch.tensor([1,2,3]).numpy()'
<string>:1: UserWarning: Failed to initialize NumPy: module compiled against API version 0x10 but this version of nump
y is 0xf . Check the section C-API incompatibility at the Troubleshooting ImportError section at https://numpy.org/dev
docs/user/troubleshooting-importerror.html#c-api-incompatibility for indications on how to solve this problem . (Trigg
ered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
Traceback (most recent call last):    
  File "<string>", line 1, in <module>
RuntimeError: Numpy is not available  
(test-venv) PS C:\>
```

### Versions

python3.10-win_amd64 wheel

cc @ezyang @gchanan @zou3519 @seemethere @malfet @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht

**Comment by jvesely** [comment] 2023-05-05 05:22
python3.9 wheel doesn't have this issue:

```
PS C:\> ~\AppData\Local\Microsoft\WindowsApps\python3.9.exe -m venv .\test-venv
PS C:\> .\test-venv\Scripts\Activate.ps1
(test-venv) PS C:\> pip install numpy==1.22.4
Collecting numpy==1.22.4
  Using cached numpy-1.22.4-cp39-cp39-win_amd64.whl (14.7 MB)
Installing collected packages: numpy
Successfully installed numpy-1.22.4
WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
You should consider upgrading via the 'C:\test-venv\Scripts\python.exe -m pip install --upgrade pip' command.
(test-venv) PS C:\> pip install torch        
Collecting torch
  Using cached torch-2.0.0-cp39-cp39-win_amd64.whl (172.3 MB)
Collecting filelock
  Using cached filelock-3.12.0-py3-none-any.whl (10 kB)
Collecting typing-extensions
  Using cached typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting sympy
  Using cached sympy-1.11.1-py3-none-any.whl (6.5 MB)
Collecting networkx
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting jinja2
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting MarkupSafe>=2.0
  Using cached MarkupSafe-2.1.2-cp39-cp39-win_amd64.whl (16 kB)
Collecting mpmath>=0.19
  Using cached mpmath-1.3.0-py3-none-any.whl (536 kB)
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, filelock, jinja2, torch        
Successfully installed MarkupSafe-2.1.2 filelock-3.12.0 jinja2-3.1.2 mpmath-1.3.0 networkx-3.1 sympy-1.11.1 torch-2.0.
0 typing-extensions-4.5.0
WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available.
You should consider upgrading via the 'C:\test-venv\Scripts\python.exe -m pip install --upgrade pip' command.
(test-venv) PS C:\> python -c 'import torch; torch.tensor([1,2,3]).numpy()'
(test-venv) PS C:\> python -c 'import torch; print(torch.tensor([1,2,3]).numpy())'
[1 2 3]
(test-venv) PS C:\>
```

**Comment by malfet** [comment] 2023-05-05 20:45
@atalman That's exactly the issue I was talking about last time when you've updated AMI. Let's make sure we get this fixed on priority.
cc: @seemethere

**Comment by jvesely** [comment] 2023-05-08 16:54
this impacts all wheels for py3.10 windows >= 1.12.0.
1.11.0 needs numpy 1.22.0 which is still later than the first numpy version to support py3.10 (1.20)

**Comment by atalman** [comment] 2023-05-11 15:51
this issue happens also with releases 2.0.1, 2.0.0 and 1.13.0 as pointed out by @jvesely earlier. Will try to modify https://github.com/pytorch/builder/blob/e0399f017be348625d2df621e627f64e2d956e4a/windows/condaenv.bat#L15 and see if it fixes it

**Comment by atalman** [comment] 2023-05-16 19:59
> eeds numpy 1.22.0 which is still later than the first numpy version to support py

@jvesely 
To capture current issue looks like:
torch for windows with python 3.9, requires numpy 1.22.4 to be installed in separate step
torch for windows with python 3.10, requires numpy 1.23.0 to be installed in separate step

I have following question: Why is this a problem depending on numpy 1.23.0 rather then 1.22.4 for Python 3.10 ?

**Comment by jvesely** [comment] 2023-05-16 21:51
> > eeds numpy 1.22.0 which is still later than the first numpy version to support py
> 
> @jvesely To capture current issue looks like: torch for windows with python 3.9, requires numpy 1.22.4 to be installed in separate step torch for windows with python 3.10, requires numpy 1.23.0 to be installed in separate step
> 
> I have following question: Why is this a problem depending on numpy 1.23.0 rather then 1.22.4 for Python 3.10 ?

both of them are a problem, I ran into this for python3.10 because I'm limited to numpy <1.23, but specific numpy versions are not that important.
Having silent dependency (i.e. things fail and throw expectations unless a specific version is installed), is a user-hostile way to handle dependencies.

If torch requires a specific version of numpy it should be listed in wheel dependencies.
If numpy is not required but can be used if available. the wheels have to be built using the oldest numpy that supports the same python version + platform (e.g. using [0]) to avoid ABI conflicts.

[0] https://github.com/scipy/oldest-supported-numpy

**Comment by atalman** [comment] 2023-05-17 14:54
@malfet If numpy is required package should we depend on it in our wheels and conda ?

**Comment by malfet** [comment] 2023-05-17 15:02
@atalman No, NumPy is not a required dependency for PyTorch, and our binaries should work with all versions on NumPy available for the platform at the time of the release.
As @jvesely have said, it is a regression in binary build scripts that should be fixed and tested for.
I'll put up a fix by the end of the week.

**Comment by atalman** [comment] 2023-05-17 20:09
@jvesely this PR should pin numpy to earlier version: https://github.com/pytorch/builder/pull/1406, let me know if this resolves your issue.

Regarding silently requiring numpy dependency as per @malfet comment, numpy is not required dependency

**Comment by atalman** [comment] 2023-05-23 14:28
Confirmed. This issue is resolved in nightly:
```
(base) C:\Windows\system32>conda create -n py310 python=3.10
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 22.9.0
  latest version: 23.3.1

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: C:\Jenkins\Miniconda3\envs\py310

  added / updated specs:
    - python=3.10


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    libffi-3.4.4               |       hd77b12b_0         113 KB
    pip-23.0.1                 |  py310haa95532_0         2.8 MB
    python-3.10.11             |       h966fe2a_2        15.8 MB
    setuptools-66.0.0          |  py310haa95532_0         1.2 MB
    sqlite-3.41.2              |       h2bbff1b_0         894 KB
    tk-8.6.12                  |       h2bbff1b_0         3.1 MB
    tzdata-2023c               |       h04d1e81_0         116 KB
    wheel-0.38.4               |  py310haa95532_0          83 KB
    ------------------------------------------------------------
                                           Total:        24.0 MB

The following NEW packages will be INSTALLED:

  bzip2              pkgs/main/win-64::bzip2-1.0.8-he774522_0 None
  ca-certificates    pkgs/main/win-64::ca-certificates-2023.01.10-haa95532_0 None
  libffi             pkgs/main/win-64::libffi-3.4.4-hd77b12b_0 None
  openssl            pkgs/main/win-64::openssl-1.1.1t-h2bbff1b_0 None
  pip                pkgs/main/win-64::pip-23.0.1-py310haa95532_0 None
  python             pkgs/main/win-64::python-3.10.11-h966fe2a_2 None
  setuptools         pkgs/main/win-64::setuptools-66.0.0-py310haa95532_0 None
  sqlite             pkgs/main/win-64::sqlite-3.41.2-h2bbff1b_0 None
  tk                 pkgs/main/win-64::tk-8.6.12-h2bbff1b_0 None
  tzdata             pkgs/main/noarch::tzdata-2023c-h04d1e81_0 None
  vc                 pkgs/main/win-64::vc-14.2-h21ff451_1 None
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.27.29016-h5e58377_2 None
  wheel              pkgs/main/win-64::wheel-0.38.4-py310haa95532_0 None
  xz                 pkgs/main/win-64::xz-5.4.2-h8cc25b3_0 None
  zlib               pkgs/main/win-64::zlib-1.2.13-h8cc25b3_0 None


Proceed ([y]/n)? y


Downloading and Extracting Packages
sqlite-3.41.2        | 894 KB    | ############################################################################ | 100%
python-3.10.11       | 15.8 MB   | ############################################################################ | 100%
setuptools-66.0.0    | 1.2 MB    | ############################################################################ | 100%
libffi-3.4.4         | 113 KB    | ############################################################################ | 100%
tk-8.6.12            | 3.1 MB    | ############################################################################ | 100%
wheel-0.38.4         | 83 KB     | ############################################################################ | 100%
tzdata-2023c         | 116 KB    | ############################################################################ | 100%
pip-23.0.1           | 2.8 MB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate py310
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Retrieving notices: ...working... done

(base) C:\Windows\system32>conda activate py310

(py310) C:\Windows\system32>pip3 install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu
Looking in indexes: https://download.pytorch.org/whl/nightly/cpu
Collecting torch
  Downloading https://download.pytorch.org/whl/nightly/cpu/torch-2.1.0.dev20230523%2Bcpu-cp310-cp310-win_amd64.whl (174.6 MB)
     ---------------------------------------- 174.6/174.6 MB 411.9 kB/s eta 0:00:00
Collecting typing-extensions
  Downloading https://download.pytorch.org/whl/nightly/typing_extensions-4.4.0-py3-none-any.whl (26 kB)
Collecting fsspec
  Downloading https://download.pytorch.org/whl/nightly/fsspec-2023.4.0-py3-none-any.whl (153 kB)
     ---------------------------------------- 154.0/154.0 kB 9.0 MB/s eta 0:00:00
Collecting filelock
  Downloading https://download.pytorch.org/whl/nightly/filelock-3.9.0-py3-none-any.whl (9.7 kB)
Collecting sympy
  Downloading https://download.pytorch.org/whl/nightly/sympy-1.11.1-py3-none-any.whl (6.5 MB)
     ---------------------------------------- 6.5/6.5 MB 104.2 MB/s eta 0:00:00
Collecting networkx
  Downloading https://download.pytorch.org/whl/nightly/networkx-3.0rc1-py3-none-any.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 64.9 MB/s eta 0:00:00
Collecting jinja2
  Downloading https://download.pytorch.org/whl/nightly/Jinja2-3.1.2-py3-none-any.whl (133 kB)
     ---------------------------------------- 133.1/133.1 kB ? eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading https://download.pytorch.org/whl/nightly/MarkupSafe-2.1.2-cp310-cp310-win_amd64.whl (16 kB)
Collecting mpmath>=0.19
  Downloading https://download.pytorch.org/whl/nightly/mpmath-1.2.1-py3-none-any.whl (532 kB)
     ---------------------------------------- 532.6/532.6 kB 34.8 MB/s eta 0:00:00
Installing collected packages: mpmath, typing-extensions, sympy, networkx, MarkupSafe, fsspec, filelock, jinja2, torch
Successfully installed MarkupSafe-2.1.2 filelock-3.9.0 fsspec-2023.4.0 jinja2-3.1.2 mpmath-1.2.1 networkx-3.0rc1 sympy-1.11.1 torch-2.1.0.dev20230523+cpu typing-extensions-4.4.0

(py310) C:\Windows\system32>python -c 'import torch; torch.tensor([1,2,3]).numpy()'
  File "<string>", line 1
    'import
    ^
SyntaxError: unterminated string literal (detected at line 1)

(py310) C:\Windows\system32>python
Python 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; torch.tensor([1,2,3]).numpy()
<stdin>:1: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at ..\torch\csrc\utils\tensor_numpy.cpp:84.)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Numpy is not available
>>> exit()

(py310) C:\Windows\system32>pip install numpy==1.22.4
Collecting numpy==1.22.4
  Downloading numpy-1.22.4-cp310-cp310-win_amd64.whl (14.7 MB)
     ---------------------------------------- 14.7/14.7 MB 24.2 MB/s eta 0:00:00
Installing collected packages: numpy
Successfully installed numpy-1.22.4

(py310) C:\Windows\system32>python
Python 3.10.11 | packaged by Anaconda, Inc. | (main, Apr 20 2023, 18:56:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch; torch.tensor([1,2,3]).numpy()
array([1, 2, 3], dtype=int64)
>>> exit()

```

**Closed by atalman** 2023-05-23 14:28 UTC
Labels: high priority, oncall: binaries, module: windows, triaged, module: regression

**Comment by atalman** [comment] 2023-05-23 19:02
@jvesely  Please refer to the comment from @malfer here: https://github.com/pytorch/pytorch/issues/100690#issuecomment-1551566094 regarding putting numpy as required dependency
