### ISSUE TITLE
Dynamo dynamic graph capture error: `Tensor.__contains__` does not support SymInt

### ISSUE THREAD

**Issue by haijieg** [pytorch/pytorch#98535] opened 2023-04-06 20:20 UTC
### 🐛 Describe the bug

```
import torch
import torch._dynamo as dynamo
import logging
dynamo.config.set_loggers_level(logging.DEBUG)


def f(idx: int, y: torch.Tensor, z: torch.Tensor):
    if idx in z:
        y[idx] += 1
    return y


f = dynamo.optimize('eager', dynamic=True)(f)

f(10, torch.tensor([0, 0, 0]), torch.tensor([1, 2, 10]))
```

```
Traceback (most recent call last):
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1239, in run_node
    return getattr(args[0], node.target)(*args[1:], **kwargs)
  File "/home/jgu/Projects/dynamite/env/lib/python3.8/site-packages/torch/_tensor.py", line 1000, in __contains__
    raise RuntimeError(
RuntimeError: Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'torch.SymInt'>.

```

`idx` is a SymInt, and Tensor.__contain__ does not support argument of SymInt. This is an simplified example of HuggingFace generation util code:

```
      def _prepare_attention_mask_for_generation(
          self,
          inputs: torch.Tensor,
          pad_token_id: Optional[int],
          eos_token_id: Optional[Union[int, List[int]]],
      ) -> torch.LongTensor:
          is_input_ids = len(inputs.shape) == 2 and inputs.dtype in [torch.int, torch.long]
>>>   is_pad_token_in_inputs = (pad_token_id is not None) and (pad_token_id in inputs)
```

### Versions

torch==2.1.0.dev20230331+cu117

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment] 2023-04-11 23:16
This is an easy fix but I will note your repro doesn't run without errors even in eager.

**Comment by ngimel** [comment] 2023-04-11 23:21
Duplicate of #98870

**Closed by ngimel** 2023-04-11 23:21 UTC
Labels: triaged, oncall: pt2, module: dynamic shapes
