### ISSUE TITLE
Don't know how to explain but here's the error

### ISSUE THREAD

**Issue by Nohj9984** [pytorch/pytorch#133397] opened 2024-08-14 02:53 UTC
### 🐛 Describe the bug

File "C:\Users\USER\Downloads\pytorch\main.py", line 3, in <module>
    import torch
  File "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22631-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture=9
CurrentClockSpeed=2419
DeviceID=CPU0
Family=205
L2CacheSize=5120
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2419
Name=11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] onnx==1.16.2
[pip3] onnxruntime==1.18.1
[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchvision==0.19.0
[conda] Could not collect

**Comment by Lazarus42** [comment] 2024-08-14 19:36
Seems related to this [PyTorch discussion](https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969/7). Some people had the libomp140.x86_64.dll dependency missing from fbgemm.dll.

**Comment by malfet** [comment] 2024-08-15 00:59
Closing as duplicate of https://github.com/pytorch/pytorch/issues/131662

Nightly builds as well as release candidate for 2.4.1 (that could be downloaded from htttps://download.pytorch.org/whl/test/cu121 ) should have this fixed already

**Closed by malfet** 2024-08-15 00:59 UTC
