### ISSUE TITLE
Pytorch 1.4 much slower than 1.3 on Ubuntu 18.04

### ISSUE THREAD

**Issue by huijunzhao-ds** [pytorch/pytorch#35561] opened 2020-03-27 19:17 UTC
## 🐛 Bug
We were trying to accelerate the inference of some transformers model in Pytorch. We found that the same code takes >5 times long in 1.4 as in 1.3 on Ubuntu OS. 

## To Reproduce

1. Code as below
```
import torch
import time
from transformers import DistilBertModel, DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

model = DistilBertModel.from_pretrained("distilbert-base-uncased")

text = "This text is to test profile of huggingface's transfomers, especially distilbert model."

input_ids = torch.tensor([tokenizer.encode(text).ids])

with torch.autograd.profiler.profile() as prof:
    with torch.no_grad():
        for _ in range(30):
            output = model(input_ids)

print(prof.key_averages().table(sort_by="self_cpu_time_total"))
```
1. Profiling result of pytorch 1.4.0
![image](https://user-images.githubusercontent.com/45569733/77791598-53d4ea80-703d-11ea-99c5-8bd3fff2e86e.png)

1. Profiling result of pytorch 1.3.1
![image](https://user-images.githubusercontent.com/45569733/77791581-46b7fb80-703d-11ea-8f0e-edafe90b2434.png)

## Expected behavior

Inference times (self CPU time total in the pictures) should be approximately the same.

## Environment

 - PyTorch Version: 1.4.0 vs 1.3.1
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch: conda
 - Build command you used (if compiling from source): N/A
 - Python version: 3.6.9
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @VitalyFedyunin @ngimel @suo @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by julianmack** [comment] 2020-03-30 09:13
Does this result hold on GPU too?

**Comment by huijunzhao-ds** [comment] 2020-03-30 11:36
> Does this result hold on GPU too? 

Never tried on GPU.

**Comment by ailzhang** [comment] 2020-03-30 22:27
Marking high priority to repro the regression and figure out where it happens.

**Comment by ezyang** [comment] 2020-03-31 21:05
Some useful information would be try the 1.5rc and see if it also has this problem

**Comment by gchanan** [comment] 2020-04-06 17:05
This should probably be tagged with one or both of quantization and JIT as a starting point.

**Comment by ailzhang** [comment] 2020-04-06 17:16
Yeah sorry I missed the `jit.trace` in the code snippet, will redirect this to jit triage review :P

**Comment by zdevito** [comment] 2020-04-07 18:29
Given the trace is showing very different performance for `mm` across the two versions, I think the right place to start looking is in the quantization code. It is unlikely to be specific to the jit for an operator to drastically change performance.

**Comment by zdevito** [comment] 2020-04-07 18:29
@jerryzh168

**Comment by jerryzh168** [comment] 2020-04-07 20:47
@jianyuh can you take a look?

**Comment by jerryzh168** [comment] 2020-04-07 20:51
Why is it calling `mm`? is this model successfully quantized? I think we only have `quantized::linear_dynamic`

**Comment by dzhulgakov** [comment] 2020-04-07 22:25
From looking at your profile, it seems to affect all operators, more or less uniformly. I'd guess it's either different build setup (are both just regular pypi downloads?) or different threading options. Do you set multithreading by any change? Play with `torch.set_num_threads` and/or `OMP_NUM_THREADS=1` env var

**Comment by huijunzhao-ds** [comment] 2020-04-08 14:07
> Why is it calling `mm`? is this model successfully quantized? I think we only have `quantized::linear_dynamic`

Sorry the results was obtained using unquantized and untraced model. Updated the code snippet.

**Comment by huijunzhao-ds** [comment] 2020-04-08 14:08
> Some useful information would be try the 1.5rc and see if it also has this problem

Have tried 1.5rc. It takes about twice the time of 1.3.1, but faster than 1.4.

**Comment by huijunzhao-ds** [comment] 2020-04-08 14:14
> From looking at your profile, it seems to affect all operators, more or less uniformly. I'd guess it's either different build setup (are both just regular pypi downloads?) or different threading options. Do you set multithreading by any change? Play with `torch.set_num_threads` and/or `OMP_NUM_THREADS=1` env var

Tried torch.set_num_threads(1). 1.3.1 gives 2.276s, 1.4.0 2.287s, and 1.5rc 2.366s. Almost the same.

**Comment by suo** [comment] 2020-04-24 19:44
I am removing the JIT tag, as it appears the performance regression is with an un-jitted, un-quantized model. @ngimel heads up as it appears to be a general perf regression, unrelated to those two submodules.

**Comment by ngimel** [comment] 2020-04-24 20:12
Removing "triaged" as it's making its way back into regular queue, and I don't think we ever discussed it in the OSS triage meeting.

**Comment by Exlsunshine** [comment] 2020-04-27 07:59
> From looking at your profile, it seems to affect all operators, more or less uniformly. I'd guess it's either different build setup (are both just regular pypi downloads?) or different threading options. Do you set multithreading by any change? Play with `torch.set_num_threads` and/or `OMP_NUM_THREADS=1` env var

I find pytorch 1.4 is slower than 1.3 if I don't specify `OMP_NUM_THREADS`, however if I set python 1.4 with `OMP_NUM_THREADS=2`, both 1.4 and 1.3 speed are almost equal.

**Comment by gchanan** [comment] 2020-04-27 17:28
CC @ilia-cher.

**Comment by Baranowski** [comment] 2020-05-18 07:22
@huijunzhao-ds, I cannot run the script from the bug report, I'm getting the following error:

```
Traceback (most recent call last):
  File "benchmark.py", line 5, in <module>
    tokenizer = BertTokenizer.from_pretrained("distilbert-base-uncased")
  File "/home/wbaranowski/miniconda3/envs/pytorch-bin/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 902, in from_pretrained
    return cls._from_pretrained(*inputs, **kwargs)
  File "/home/wbaranowski/miniconda3/envs/pytorch-bin/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 1007, in _from_pretrained
    list(cls.vocab_files_names.values()),
OSError: Model name 'distilbert-base-uncased' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased). We assumed 'distilbert-base-uncased' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
```

I have version `2.9.1` of `transformers`

**Comment by huijunzhao-ds** [comment] 2020-05-18 13:12
> @huijunzhao-ds, I cannot run the script from the bug report, I'm getting the following error:
> 
> ```
> Traceback (most recent call last):
>   File "benchmark.py", line 5, in <module>
>     tokenizer = BertTokenizer.from_pretrained("distilbert-base-uncased")
>   File "/home/wbaranowski/miniconda3/envs/pytorch-bin/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 902, in from_pretrained
>     return cls._from_pretrained(*inputs, **kwargs)
>   File "/home/wbaranowski/miniconda3/envs/pytorch-bin/lib/python3.6/site-packages/transformers/tokenization_utils.py", line 1007, in _from_pretrained
>     list(cls.vocab_files_names.values()),
> OSError: Model name 'distilbert-base-uncased' was not found in tokenizers model name list (bert-base-uncased, bert-large-uncased, bert-base-cased, bert-large-cased, bert-base-multilingual-uncased, bert-base-multilingual-cased, bert-base-chinese, bert-base-german-cased, bert-large-uncased-whole-word-masking, bert-large-cased-whole-word-masking, bert-large-uncased-whole-word-masking-finetuned-squad, bert-large-cased-whole-word-masking-finetuned-squad, bert-base-cased-finetuned-mrpc, bert-base-german-dbmdz-cased, bert-base-german-dbmdz-uncased, bert-base-finnish-cased-v1, bert-base-finnish-uncased-v1, bert-base-dutch-cased). We assumed 'distilbert-base-uncased' was a path, a model identifier, or url to a directory containing vocabulary files named ['vocab.txt'] but couldn't find such vocabulary files at this path or url.
> ```
> 
> I have version `2.9.1` of `transformers`
> 
> I ran the following modified script:
> 
> ```
> import torch
> import time
> from transformers import DistilBertModel, BertTokenizer, DistilBertTokenizer
> 
> tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")
> 
> model = DistilBertModel.from_pretrained("distilbert-base-uncased")
> 
> text = "This text is to test profile of huggingface's transfomers, especially distilbert model."
> 
> #input_ids = torch.tensor([tokenizer.encode(text).ids])
> input_ids = torch.tensor(tokenizer.encode("Hello, my dog is cute")).unsqueeze(0)
> 
> with torch.autograd.profiler.profile() as prof:
>     with torch.no_grad():
>         for _ in range(30):
>             output = model(input_ids)
> 
> print(prof.key_averages().table(sort_by="self_cpu_time_total"))
> ```
> 
> but I didn't see any significant performance difference on Ubuntu 18.04 with PyTorch versions 1.3.1, 1.4.0 and built from current `master`.

Thanks for the feedback. Have changed the code accordingly. 
I don't know why the difference is not reproduced. But we experienced similar difference between 1.3.1 and 1.4.0 on Ubuntu 18.04 regarding an LSTM model inference recently, with both conda and pip installations. This time 1.4.0 takes 2-3 times longer than 1.3.1. Could it be the installing method that makes the difference?

**Comment by peterbell10** [comment] 2020-05-21 14:35
@huijunzhao-ds I cannot reproduce either. I tried installing from both the pytorch conda channel and the default channel. Both were within 2-3% of the 1.3 performance. Also tried on a non-AVX cpu and get the same results.

- Is it possible that you have an MKL or OMP environment variable defined that could be effecting threading performance?
- If you run with `KMP_AFFINITY=verbose` do you get output showing that mkl's openmp implementation is used?
- What version of `transformers` are you using?

**Comment by mruberry** [comment] 2020-11-06 19:13
Closing due to age and lack of reproduction. If this issue is still occurring please update and reopen it.

**Closed by mruberry** 2020-11-06 19:13 UTC
Labels: high priority, module: multithreading, module: performance, module: regression, needs reproduction, triaged
