### ISSUE TITLE
torch.cuda.is_available() closes the Python command prompt

### ISSUE THREAD

**Issue by Metaldandy** [pytorch/pytorch#96998] opened 2023-03-17 03:39 UTC
I'm trying to do these three lines to check if they're compatible with my system but upon entering the third line the Python command prompt closes after a couple seconds.
```python
import torch
print(torch.__version__)
print(torch.cuda.is_available())
```
The only error I can find is from the event viewer and it's this
```
Faulting application name: python.exe, version: 3.10.9150.1013, time stamp: 0x638fa05d
Faulting module name: nvcuda64.dll, version: 31.0.15.3129, time stamp: 0x640826be
Exception code: 0xc0000409
Fault offset: 0x000000000053c834
Faulting process id: 0x2084
Faulting application start time: 0x01d958809081fd62
Faulting application path: C:\Users\Tampa\AppData\Local\Programs\Python\Python310\python.exe
Faulting module path: C:\WINDOWS\system32\DriverStore\FileRepository\nv_dispi.inf_amd64_059948e396d205d5\nvcuda64.dll
Report Id: 1c46ed49-3cd8-4eaf-b09d-31f53d53dbee
Faulting package full name: 
Faulting package-relative application ID: 
```
Possibly unrelated but I was trying to check the compatibility because I'm getting this error when trying to run a webui and I'm assuming they are related. I'm wanting to avoid the --skip-torch-cuda-test because it's a graphics based UI.
```
Command: "C:\Users\Tampa\sd-webui\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
```
System information
- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): `pip install torch==1.13.1+cu117 torchvision==0.14.1+cu117 torchaudio==0.13.1 --extra-index-url https://download.pytorch.org/whl/cu117`
- Build command you used (if compiling from source):
- OS: Windows 10 Home Edition
- PyTorch version: 1.13.1
- Python version: 3.10.9
- CUDA/cuDNN version: 11.7 (Though nvidia-smi outputs 12.1)
- GPU models and configuration: GTX 1660 Super

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel

**Comment by malfet** [comment] 2023-03-17 03:56
0xc0000409 is [STATUS_STACK_BUFFER_OVERRUN](https://devblogs.microsoft.com/oldnewthing/20190108-00/?p=100655), but looks like it happens inside `nvcuda64.dll`

Considering that PyTorch-1.13.1 were release a while back ,  and no other such issues were reported, I suspect there is something wrong with system setup, rather than with PyTorch.

**Comment by Metaldandy** [comment] 2023-03-17 04:07
> Can you run any CUDA examples on your system?

No, this is the only thing I've tried to use CUDA. I'm still very new to it.

**Comment by alinpahontu2912** [comment] 2023-09-05 11:40
@Metaldandy hi, are you still having having this issue? I tried reproducing it but did not reach that error.

**Comment by iremyux** [comment] 2023-10-02 10:46
Closing this issue since it no longer seems relevant. Please feel free to open a new issue if you entounter any problems or have a feature request.

**Closed by iremyux** 2023-10-02 10:46 UTC
Labels: module: windows, module: cuda, triaged
