### ISSUE TITLE
Caffe2 Error: more than one operator "+" matches these operands, windows and Cuda 11

### ISSUE THREAD

**Issue by GrimReaper420** [pytorch/pytorch#42549] opened 2020-08-04 19:03 UTC
## 🐛 Bug

An error occurs while building PyTorch from the latest master on Win10 with VS2019 and Cuda 11. The error seems to be from Caffe2 (refer to the error quote below). Thanks in advance.

## To Reproduce

On Windows 10 Home:
1. Download and install the latest NVIDIA drivers and Visual Studio 2019 (with Visual C++).
2. Download and install the latest Cuda Toolkit (Cuda 11).
3. Download and install python 3.8
3. Clone the master branch of PyTorch.
4. Download and install the PyTorch dependencies.
5. In CMD: run "set CMAKE_GENERATOR=Visual Studio 16 2019"
6. In the PyTorch repo directory: run "python setup.py install"

The error:
> [1040/1919] Building NVCC (Device) object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/torch_cuda_generated_DilatedMaxPool2d.cu.obj
> FAILED: caffe2/CMakeFiles/torch_cuda.dir/operators/torch_cuda_generated_utility_ops.cu.obj
> ...[cmd command info here]...
> C:/.../pytorch/build\caffe2/proto/caffe2.pb.h(151): error: more than one operator "+" matches these operands:
>             built-in operator "arithmetic + arithmetic"
>             function "c10::operator+(int, c10::BFloat16)"
>             function "c10::operator+(c10::BFloat16, int)"
>             function "c10::operator+(int, c10::Half)"
>             function "c10::operator+(c10::Half, int)"
>             operand types are: const caffe2::ExternalDataProto_SourceType + int

## Expected behavior

The build should complete successfully. I haven't made any modifications to the clone.

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10 Home (ver 19041)
GCC version: Could not collect
CMake version: version 3.18.0

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Cuda 11
GPU models and configuration: GPU 0: GeForce GT 710 (compute capability: 3.5)
Nvidia driver version: 451.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.18.4
[conda] Could not collect

cc @malfet @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by glaringlee** [comment] 2020-08-04 22:45
@GrimReaper420 
Can you try build this under cuda 10.x see whether it can be built?
@malfet 
It seems we don't have windows + cuda 11 coverage in CI, I saw all the cuda10.x CI tests passed though. Do you think this is caused by cuda 11?

**Comment by peterjc123** [comment] 2020-08-04 23:49
9ed210e75701d8760a0b7cc9e11498b3R40

**Comment by GrimReaper420** [comment] 2020-08-04 23:56
> @GrimReaper420
> Can you try build this under cuda 10.x see whether it can be built?

I am doing so now.

**Comment by peterjc123** [comment] 2020-08-05 01:57
Please see https://github.com/pytorch/pytorch/pull/42420/files#diff-9ed210e75701d8760a0b7cc9e11498b3R40.

**Comment by GrimReaper420** [comment] 2020-08-05 11:31
> @GrimReaper420
> Can you try build this under cuda 10.x see whether it can be built?

Build Successful :-).

> Please see https://github.com/pytorch/pytorch/pull/42420/files#diff-9ed210e75701d8760a0b7cc9e11498b3R40.

Hopefully, Cuda 11 support will be implemented soon as the latest Nvidia drivers are installed with Cuda 11.

**Comment by peterjc123** [comment] 2020-08-10 05:19
Should be fixed in master.

**Closed** 2020-08-10 05:19 UTC
Labels: module: build, module: operators, module: windows, triaged
