### ISSUE TITLE
[OSX] pip package does not ship MKL, RuntimeError: fft: ATen not compiled with MKL support

### ISSUE THREAD

**Issue by SunHaozhe** [pytorch/pytorch#18996] opened 2019-04-07 12:33 UTC
## 🐛 Bug

The pip package does not ship MKL with it and MKL is required for fft support on cpu.

## To Reproduce

1. Run the following code with Pytorch installed with pip

import torch
from kymatio import Scattering2D

scattering = Scattering2D(J=2, shape=(32, 32))
x = torch.randn(1, 1, 32, 32)
Sx = scattering(x)
print(Sx.size())

## Expected behavior

<img width="1019" alt="Screenshot 2019-04-07 at 14 26 59" src="https://user-images.githubusercontent.com/26926814/55683542-43fe5b00-5941-11e9-86f3-0cc5475e86ba.png">

## Environment

 - PyTorch Version (e.g., 1.0): 1.0.1.post2
 - OS (e.g., Linux): Mac OS Mojave version 10.14.3
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): None
 - Python version: 3.6.1
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: None

cc @ezyang @gchanan @zou3519

**Comment by soumith** [comment] 2019-05-27 20:50
This indeed affects OSX. We'll aim to fix it by next release.

**Comment by mlinxiang** [comment] 2019-07-04 09:31
@soumith did this fix on master branch?

**Comment by soumith** [comment] 2019-07-29 04:39
yes it actually did

**Comment by VictoryDong** [comment] 2019-08-20 08:38
torch._C._VariableFunctions.stft  has the same problem

**Comment by yatingge** [comment] 2019-08-20 09:14
I tried to run the sample code for https://gpytorch.readthedocs.io/en/latest/examples/03_Multitask_GP_Regression/Multitask_GP_Regression_Scalable_With_KISSGP.html?highlight=KISS.

It has the same problem that " RuntimeError: fft: ATen not compiled with MKL support".. I have tried to install MKL but it didn't work. Can someone help me ?

**Comment by faroit** [comment] 2019-08-27 08:12
> torch._C._VariableFunctions.stft has the same problem

indeed, I can verify this. 

@soumith can you reopen this issue?

**Comment by ezyang** [comment] 2019-08-29 14:51
This bug got duped so I'm bumping it up in triage review

**Comment by rgommers** [comment] 2019-08-29 23:38
Here's a complete reproducer:
```
conda create python=3.7 -n pytorch-pip-macos --yes
conda activate pytorch-pip-macos
conda install pip numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing --yes
pip install torch
python -c "import torch; torch.fft(torch.randn(3,12,12,2), 2)"
```

That will result in:
```
...
Installing collected packages: torch
Successfully installed torch-1.2.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: fft: ATen not compiled with MKL support
```

The 1.2.0 wheel is linking against `Accelerate` rather than `MKL`:
```
$ otool -L ~/anaconda3/envs/pytorch-pip-macos/lib/python3.7/site-packages/torch/lib/libtorch.dylib 
/Users/rgommers/anaconda3/envs/pytorch-pip-macos/lib/python3.7/site-packages/torch/lib/libtorch.dylib:
	@rpath/libtorch.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
```

The 1.2.0 conda package does link against `MKL`:
```
pip uninstall torch
conda install pytorch -c pytorch
python -c "import torch; torch.fft(torch.randn(3,12,12,2), 2)"  # passes
```
```
$ otool -L ~/anaconda3/envs/pytorch-pip-macos/lib/python3.7/site-packages/torch/lib/libtorch.dylib 
/Users/rgommers/anaconda3/envs/pytorch-pip-macos/lib/python3.7/site-packages/torch/lib/libtorch.dylib:
	@rpath/libtorch.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_intel_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_intel_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.0.0)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
```

I'm assuming the use of `Accelerate` in the wheels is unwanted, it should be using `MKL` for everything?

**Comment by ezyang** [comment] 2019-08-30 13:21
I'm not sure, actually. @soumith, when we build wheels on Linux, do we statically link in MKL?

**Comment by soumith** [comment] 2019-09-01 05:13
with Linux, yes, with OSX no.

The right fix is to patch https://github.com/pytorch/builder/blob/master/wheel/build_wheel.sh
While we traditionally didn't link MKL on OSX because Accelerate was just fine as a BLAS, we are now starting to rely on MKL-specific functionality as above, and so we need to fix this to statically link MKL on OSX as well.
I can attempt it sometime this weekend.

**Comment by rgommers** [comment] 2019-09-14 06:14
I was looking at a similar issue for SciPy, and decided to have a look whether [delocate](https://github.com/matthew-brett/delocate/) works for a `torch` wheel. It all looks right to me, when only replacing `conda install nomkl` with `conda install mkl mkl-include` in `build_wheel.sh` and running delocate over the produced wheel.

Running `build_wheel.sh` and checking linked libs:
```
$ otool -L ~/anaconda3/envs/wheel_py37/lib/python3.7/site-packages/torch/lib/libtorch.dylib
/Users/rgommers/anaconda3/envs/wheel_py37/lib/python3.7/site-packages/torch/lib/libtorch.dylib:
	@rpath/libtorch.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_intel_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_intel_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libmkl_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	@rpath/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

Output of `delocate-listdeps torch-1.2.0-cp37-cp37m-macosx_10_9_x86_64.whl` on the wheel produced by `builder/wheel/build_wheel.sh`:
```
/Users/rgommers/anaconda3/envs/wheel_py37/lib/libiomp5.dylib
/Users/rgommers/anaconda3/envs/wheel_py37/lib/libmkl_core.dylib
/Users/rgommers/anaconda3/envs/wheel_py37/lib/libmkl_intel_lp64.dylib
/Users/rgommers/anaconda3/envs/wheel_py37/lib/libmkl_intel_thread.dylib
@rpath/libc++.1.dylib
@rpath/libc10.dylib
@rpath/libshm.dylib
@rpath/libtorch.dylib
@rpath/libtorch_python.dylib
```

Output of `delocate-listdeps torch-1.2.0-cp37-cp37m-macosx_10_9_x86_64.whl` after running `delocate-wheel` on it:
```
... <some warnings> ...
@loader_path/../.dylibs/libiomp5.dylib
@loader_path/../.dylibs/libmkl_core.dylib
@loader_path/../.dylibs/libmkl_intel_lp64.dylib
@loader_path/../.dylibs/libmkl_intel_thread.dylib
@rpath/libc++.1.dylib
@rpath/libc10.dylib
@rpath/libiomp5.dylib
@rpath/libshm.dylib
@rpath/libtorch.dylib
@rpath/libtorch_python.dylib
```

For the fixed wheel:
```
$ otool -L libtorch.dylib 
libtorch.dylib:
	@rpath/libtorch.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/../.dylibs/libmkl_intel_lp64.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/../.dylibs/libmkl_intel_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/../.dylibs/libmkl_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	@loader_path/../.dylibs/libiomp5.dylib (compatibility version 5.0.0, current version 5.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.250.1)
	@rpath/libc10.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
```

```
$ ls fixed_wheels/torch/.dylibs/
libiomp5.dylib			libmkl_core.dylib		libmkl_intel_lp64.dylib		libmkl_intel_thread.dylib
```

Tests pass, at least to the same extent as the 1.2.0 wheel from PyPI. Happy to open a PR if that's helpful.

**Comment by ezyang** [comment] 2019-09-16 14:31
TIL about delocate :) But I think @soumith would be the best person to respond here.

**Comment by soumith** [comment] 2019-09-18 05:25
`delocate` is similar to `auditwheel repair`, and does what it is advertised to do.

Generally speaking, this is not good for:
1. binary sizes (we only need and use a very small portion of MKL)
2. side-effects from multiple versions of mkl loaded. System MKL dynamic libs installed and loaded via a different dependency and libtorch's own MKL libs installed and loaded in the same namespace

We can't do a lot about (2), but we can statically link and hide the symbols only for libtorch's usage. We used to do that with a version control script on Linux, but stopped it because our symbol versioning script was wrong and caused other side-effects ( [reference](https://github.com/pytorch/pytorch/blob/v0.4.0/tools/pytorch.version) ). One can do it with `fvisibility=hidden` where most of the basic symbol hiding works.
Statically linking will save binary size space as well, because we will only link symbols we need and not all of MKL.

The ideal alternative situation is to depend on the `pip` package `mkl`, because then if `scipy` and `numpy` also depend on pip package `mkl`, we are all sharing binary size overheads and using dynamic libraries for what they are. But the exercise to do is to figure out whether it plays well with `conda` `mkl` package. What happens if `pip install numpy` which depends on `pip` `mkl`, but a `conda` `mkl` was already installed.... will the `pip` `mkl` overwrite the `conda` `mkl` and cause havoc, or will `conda` be aware of what `pip install mkl` is doing. Considering that this situation has some homework, we've just statically linked to `mkl` for the linux binaries. For OSX, I'll get to it soon and keep it as a thing to do for 1.3

**Comment by rgommers** [comment] 2019-09-18 06:08
> The ideal alternative situation is to depend on the `pip` package `mkl`, because then if `scipy` and `numpy` also depend on pip package `mkl`, we are all sharing binary size overheads and using dynamic libraries for what they are.

The default for NumPy and SciPy is likely to remain shipping with OpenBLAS (bundled in via `delocate`). We've discussed in the past shipping wheels with MKL, but that had license issues with redistribution that Intel was unable to solve. We could indeed rely on the MKL wheels now, which solves the licensing issue. There's still two issues though: (1) `pip install numpy[mkl]` doesn't quite have the right behavior, since we need a whole new wheel there rather than install `mkl` as an add-on (BLAS linkage is determined at build time), and (2) I don't trust the robustness of relying on any BLAS package until `pip` gets a resolver and that's been tested for a while (https://github.com/pypa/pip/issues/6536).

To get around the above we could put up a separate `numpy-mkl` package, but that's not very useful since people will put `numpy` rather than `numpy-mkl` in their `pyproject.toml` or `install_requires`.

> But the exercise to do is to figure out whether it plays well with `conda` `mkl` package. What happens if `pip install numpy` which depends on `pip` `mkl`,

so this won't happen

> but a `conda` `mkl` was already installed.... will the `pip` `mkl` overwrite the `conda` `mkl` and cause havoc, 

Won't cause havoc, the `conda`-installed one lives in `site-packages/mkl` while the `pip`-installed one goes into `mkl-2019.0` so they won't conflict. `mkl_fft` and `mkl_random` do keep the same install path for conda and pip, however the `pip` installed in a `conda` env is aware of a previously-installed version:
```
$ pip install mkl-random
Requirement already satisfied: mkl-random in /Users/rgommers/anaconda3/envs/mklcheck/lib/python3.7/site-packages (1.0.2)
Requirement already satisfied: numpy in /Users/rgommers/anaconda3/envs/mklcheck/lib/python3.7/site-packages (from mkl-random) (1.16.5)
```
Of course this is still not 100% fool-proof, because if `pip` finds a newer version of `mkl_fft` or `mkl_random` than is installed in the conda env, then it will install to that path, overwriting the older conda-installed version. Note that this is hard to trigger in practice, because the most recent PyPI versions of `mkl_fft`/`mkl_random` are the oldest versions available in conda's `main` channel (possibly by design so `pip` won't be able to overwrite conda ever).

> or will `conda` be aware of what `pip install mkl` is doing

In general, yes `conda` is aware. It's still better not to rely on this though, since it's inherently more fragile than a conda-only or pip-only approach.

**Comment by soumith** [comment] 2019-10-09 03:16
issued https://github.com/pytorch/builder/commit/7b69a95bbd3298c6303e137c9beee4fadd71a894 to attempt to fix. awaiting results

**Comment by soumith** [comment] 2019-10-09 12:47
things are looking good, still needed delocation for `libiomp5.dylib`, so added https://github.com/pytorch/builder/commit/9637336a682482a301f47da4f40a2bfe01690759

**Comment by soumith** [comment] 2019-10-10 05:06
as of the above two commits, it is now fixed and verified. nightlies and v1.3.0 binaries will not have this problem

**Closed by soumith** 2019-10-10 05:06 UTC
Labels: high priority, module: binaries, triaged

**Comment by soumith** [comment] 2019-10-21 10:26
so, it turned out that `delocate`'s pip binary has a bug that was fixed in master over a year ago, i.e. commit: https://github.com/matthew-brett/delocate/commit/a2a4e576d1b8001ae465d96e541dbf95761a3438

I kicked of binaries with `delocate` master instead of `pip` and will file an issue to them to do a new release

**Comment by keyboardAnt** [comment] 2020-10-14 14:55
Oct 14, 2020:

```python
In [67]: print(torch.__version__)
1.6.0

In [68]: torch.get_num_threads()
Out[68]: 1

In [69]: torch.torch.set_num_threads(4)

In [70]: torch.get_num_threads()
Out[70]: 1

In [71]: mkl.get_max_threads()
Out[71]: 4
```
