### ISSUE TITLE
Not Being Able to Install PyTorch

### ISSUE THREAD

**Issue by nivedvenugopalan** [pytorch/pytorch#67669] opened 2021-11-02 07:22 UTC
When installing PyTorch using the following command:<br/>
<br/>
```pip3 install torch==1.10.0+cu113 torchvision==0.11.1+cu113 torchaudio===0.10.0+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html```<br/>
<br/>

I got this error: <br/>
`Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.10.0+cu113 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.10.0+cu113`

cc @ezyang @seemethere @malfet

**Comment by MaltheG** [comment] 2021-11-02 10:08
I am getting the same error.

I am using python 3.10 and pip 21.3.1

**Comment by MaltheG** [comment] 2021-11-02 13:31
I fixed the issue by downgrading to python version 3.9.7. I guess pytorch isn't upgraded for 3.10 yet

**Comment by malfet** [comment] 2021-11-02 14:26
Removing "module: build" as it has nothing to do with building PyTorch and closing as duplicate of https://github.com/pytorch/pytorch/issues/66424 

PyTorch builds again python-3.10 are not yet supported for 1.10

**Closed by malfet** 2021-11-02 14:26 UTC
Labels: module: binaries, triaged

**Comment by famzah** [comment] 2021-11-13 05:13
❌ It didn't work with Python 3.6 on Windows 10.
✔️ It works with Python 3.9 on Windows 10.

**Comment by alik604** [comment] 2021-12-21 21:19
I hope they bother to update to fix their site. It clearly implies 3.10 was fine, I checked being downloading python. I just did fresh windows install. 
>Currently, PyTorch on Windows only supports Python 3.x; Python 2.x is not supported.

**Comment by Bengt** [comment] 2022-01-04 00:02
> I fixed the issue by downgrading to python version 3.9.7. I guess pytorch isn't upgraded for 3.10 yet

@MaltheG That isn't a fix, but merely a workaround. PyTorch should still support Python 3.10. You may be able to downgrade your interpreter, but others might not.

**Comment by agusavior** [comment] 2022-01-06 20:13
I'm using python 3.9 and I get this error

**Comment by cpoptic** [comment] 2022-01-19 13:54
> Currently, PyTorch on Windows only supports Python 3.x; Python 2.x is not supported.

Looks like in the last 29 days maintainers updated the PyTorch website to exclude Python 3.10:
> Currently, PyTorch on Windows only supports Python 3.7-3.9; Python 2.x is not supported.

**Comment by leonekwolfik** [comment] 2022-01-31 14:56
Same error:

```
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

Using  Python 3.10.2 and try to install PyTorch 1.10.2

Try on macOS 12.2 and Windows 10.

**Comment by malfet** [comment] 2022-01-31 16:10
PyTorch-1.10.x was not  not built/uploaded with python-3.10 support. Nightlies and PyTorch-1.11 will support it.

**Comment by Alpha787** [comment] 2022-02-23 10:33
Guys I post a solution for this problem. 
https://stackoverflow.com/questions/69826153/cant-install-pytorch-in-pycharm-terminal-python-3-10-win-10/71235282#71235282
