### ISSUE TITLE
RuntimeError: The size of tensor a (2048) must match the size of tensor b (7) at non-singleton dimension 3 when resuming adam optimizer and model training

### ISSUE THREAD

**Issue by nicolasch96** [pytorch/pytorch#40769] opened 2020-06-30 12:50 UTC
## 🐛 Bug

Hello,
I am facing an issue when I load adam optimizer and or scheduler to resume my training. The bug happens on certain points of the training in the deeper epochs. early resume does not produce the error. So that means, some checkpoints does not produce this error.

Here is the error:
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-20-c4bb3cbb5bba> in <module>
      2       checkpoint_path = os.path.join(experiment_path,"checkpoints_2_bis.tar"), push_epoch = push_epoch,
      3       train_loss = train_loss, batch_size = batch_size, nb_epochs = nb_epochs, start_epoch = last_epoch + 1,
----> 4       log_interval = log_interval, use_cuda = use_cuda, use_scheduler = use_scheduler, freeze_CNN = freeze_CNN)

<ipython-input-19-1b3b39cf61e1> in Train(criterion, optimizer, scheduler, model, train_loader, checkpoint_path, train_loss, batch_size, push_epoch, nb_epochs, start_epoch, log_interval, use_cuda, use_scheduler, freeze_CNN, device)
     30             loss = criterion(output, target.view(-1,1))
     31             loss.backward()
---> 32             optimizer.step()
     33 
     34             epoch_avg_loss += loss.item() * batch_size / len(train_loader.dataset)

~\.conda\envs\env2\lib\site-packages\torch\optim\lr_scheduler.py in wrapper(*args, **kwargs)
     65                 instance._step_count += 1
     66                 wrapped = func.__get__(instance, cls)
---> 67                 return wrapped(*args, **kwargs)
     68 
     69             # Note that the returned function here is no longer a bound method,

~\.conda\envs\env2\lib\site-packages\torch\autograd\grad_mode.py in decorate_context(*args, **kwargs)
     13         def decorate_context(*args, **kwargs):
     14             with self:
---> 15                 return func(*args, **kwargs)
     16         return decorate_context
     17 

~\.conda\envs\env2\lib\site-packages\torch\optim\adam.py in step(self, closure)
     97 
     98                 # Decay the first and second moment running average coefficient
---> 99                 exp_avg.mul_(beta1).add_(grad, alpha=1 - beta1)
    100                 exp_avg_sq.mul_(beta2).addcmul_(grad, grad, value=1 - beta2)
    101                 if amsgrad:
```

Here is my code:

```
  optimizer = optim.Adam([{'params': param} for param in model_MSCNN.parameters() if param.requires_grad], lr = lr , amsgrad = True)
   scheduler = StepLR(optimizer, step_size = scheduler_step_size , gamma = scheduler_gamma )
  if  resume_training and os.path.exists(os.path.join(experiment_path,checkpoint_file_name)):

    checkpoint = torch.load(os.path.join(experiment_path,checkpoint_file_name))
    
    scheduler.load_state_dict(checkpoint['scheduler_state_dict'])
    model_MSCNN.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    
    
    last_epoch = checkpoint['last_epoch']
    train_loss = checkpoint['train_loss']
    freeze_CNN = checkpoint['freeze_CNN']
```

When I comment the optimizer load state dict, the error disappears but I do not resume from the same loss obviously.

**Comment by colesbury** [comment] 2020-06-30 14:35
It seems like some important aspect of your model changes between checkpoints. From the error, it looks like the shape of the gradient average does not match the shape of the current gradient. There is not enough information here to know what's going on, so I'm closing the issue.

Please re-open if you're able to provide more information, such as a self-contained example that reproduces the error.

**Closed by colesbury** 2020-06-30 14:35 UTC

**Comment by nicolasch96** [comment] 2020-06-30 15:06
Thank you for your reply. I have to mention that I extracted the current learning rate manually and redefined the optimized without leading its state dict and it worked. So I guess the problem is with the saved state dict of the optimizer.

Here is the model structure, it is a multiscale CNN model:
class Identity(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        return x
    
class MSCNN(nn.Module):
    '''
    Implementation of Multi-scale CNN for NR image quality assessment
    '''        
        
    def __init__(self, n_multiScale = 3, n_fcOut_features = 256, model_name = "resnet18" , n_classes = 1, pretrained = False, use_cuda = False, freeze_CNN = True):
        super(MSCNN,self).__init__()
        
        self.n_multiScale = n_multiScale
        self.use_cuda = use_cuda
    
        self.multiModels = [self.getModel(model_name, n_fcOut_features, pretrained, freeze_CNN) for n in range(n_multiScale)]
        if use_cuda:
            self.multiModels = [model.cuda() for model in self.multiModels]
            
        self.multiModels = nn.ModuleList(self.multiModels)
            
        self.fc = nn.Sequential(
            nn.Linear(n_fcOut_features * n_multiScale , n_fcOut_features),
            nn.ReLU(inplace=True),
            nn.Linear( n_fcOut_features, n_fcOut_features),
            nn.ReLU(),
            nn.ReLU(inplace=True),
            nn.Linear( n_fcOut_features, n_classes)             
        )
        

        assert len(multi_scale_images) == self.n_multiScale, "Expected {} multiscale patches, got {}.".format(self.n_multiScale , len(multi_scale_images))  
        
        x = tuple([model(img) for (model , img) in zip(self.multiModels , multi_scale_images)])
        x=torch.cat(x,1)
       
        x = self.fc(x)
        
        return x

    def _initialize_weights(self):
        for m in self.modules():
            if isinstance(m, nn.Conv2d):
                nn.init.normal_(m.weight, std=0.01)
                if m.bias is not None:
                    nn.init.constant_(m.bias, 0)
            elif isinstance(m, nn.BatchNorm2d):
                nn.init.constant_(m.weight, 1)
                nn.init.constant_(m.bias, 0)
                
    def getModelFromName(self, model_name = "resnet18", pretrained = False):
        models = {
            "resnet18": tvmodels.resnet18,
            
            "resnet50": tvmodels.resnet50,
            
            "resnet101": tvmodels.resnet101,
            
            "resnet152": tvmodels.resnet152,
            
#             "basicModel": self.basicModel
        }
        
        if model_name in models.keys():
            return models[model_name](pretrained)
        else:
            raise ValueError("Model {} is not defined".format(model_name))
                    
    
    def getModel(self, model_name = "resnet18", n_fcOut_features = 256, pretrained = False, freeze_CNN = True):
        try:
            model = self.getModelFromName(model_name, pretrained)
            num_ftrs = model.fc.in_features
            
            # Freeze all parameters except fully connected layer
            if(pretrained and freeze_CNN):
                for param in model.parameters():
                    param.requires_grad = False

            if num_ftrs == n_fcOut_features:
                model.fc == Identity()
            else:
                model.fc = nn.Linear(num_ftrs, n_fcOut_features)
            
            return model
 
        except:
            print("An error occured:")
            traceback.print_exc()  


Here is my training function where I save the checkpoint:

def Train(criterion, optimizer, scheduler, model, train_loader, checkpoint_path = "",
          train_loss = [], batch_size = batch_size, push_epoch = 20, nb_epochs = 50, start_epoch = 0, log_interval = 5, use_cuda = False, use_scheduler = False, freeze_CNN = True, device = "" ):
    
    model.train()
    
    for epoch in range(start_epoch, nb_epochs):
        epoch_avg_loss = 0.0
        
        # After 10 epochs, unfreeze all parameters and continue training 
        if (epoch == push_epoch or (not freeze_CNN and epoch == start_epoch)):
            for param in model.parameters():
                if (param.requires_grad == False):
                    param.requires_grad = True
                    optimizer.add_param_group({'params': param})   
            freeze_CNN = False

        for batch_idx, (data, target) in enumerate(train_loader):
            data = [torch.stack([d[i] for d in data]) for i in range(len(data[0]))]
            if use_cuda:
                data = [d.cuda() for d in data]
                target = target.cuda()
                            

            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target.view(-1,1))
            loss.backward()
            optimizer.step()
            
            epoch_avg_loss += loss.item() * batch_size / len(train_loader.dataset)
            if batch_idx % log_interval == 0:
                print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
                    epoch, batch_idx * len(data), len(train_loader.dataset),
                    100. * batch_idx / len(train_loader), loss.data.item()))
        print("-------------------------------------------")
        print("End of epoch: {}, average epoch loss: {}, trainable parameters: {}".format(epoch, epoch_avg_loss, 
                                                                                          sum([p.numel() for p in model.parameters() if p.requires_grad])))
        print("-------------------------------------------")
        train_loss.append(epoch_avg_loss) 
        if use_scheduler:
            scheduler.step()
        
        # Save checkpoint
        if checkpoint_path:
            torch.save({
                    'last_epoch': epoch,
                    'model_state_dict': model.state_dict(),
                    'optimizer_state_dict': optimizer.state_dict(),
                    'scheduler_state_dict': scheduler.state_dict(),
                    'train_loss': train_loss,
                    'freeze_CNN': freeze_CNN

                    }, checkpoint_path)
            
    return train_loss

**Comment by LZCai** [comment] 2021-08-19 07:06
1、首先确定是否修改了网络的结构和参数；
2、如果网路没有变化，应该就是__init__()方法中网络层的定义顺序发生变化，从而导致optimizer中id相同的层参数发生变化（即：对应了网络中的不同层）。
3、将model直接print出来对比一下就好。
