### ISSUE TITLE
Serious perf drop on CPU 

### ISSUE THREAD

**Issue by MlWoo** [pytorch/pytorch#7903] opened 2018-05-29 00:29 UTC
I have tracked performance of [our rnn benchmark](https://github.com/MlWoo/PyTorch-benchmark/tree/master/rnn_benchmark) of PyTorch on CPU. Here are some critical logs. The first column is the commit id of PyTorch. The second one is  the perf(sentence per second) of my benchmark, the larger the number is, the better perf PyTorch achieves.
```
197412fa8f2d3c280afa06a07e2025e77a8efc54  442.7792
619a56bf21897fca2ed794cf1d9e596ebbc6361f  447.3579
88a705555ae88d2f3302b6227010b82a857b8eb1  433.6706
4d2693973e638d5b8a8fe4e11bb4da85d1698596  1015.3741
19040583702377c6f5f60e88477424a113a27565  1009.2084
e6330559c8769d4f9bfe4e1a11301a8cbfd63081  1024.4980
```
It is very clear that the commit `88a705555ae88d2f3302b6227010b82a857b8eb1` results in serious perf drop on CPU.  But I did not find any coding problems of the commit.   
However, profiling results of Vtune shows` tbb` works in the comimit but does not do that in previous commit. I suspect that the introduction of `tbb` may cause that serious perf drop although I am not an expert on parallel solutions. Because I have heared that [openmp could not cooperates very well with other parallel solution](https://software.intel.com/en-us/forums/intel-threading-building-blocks/topic/281761 ). Different parallel solutions may race the computation resource because they has their own mechanism of resource management.
Similar perf problems also occurs in CNN benchmark.

Maybe some more infos listed below is useful.
Platform:

|CPU Model|Sockets|Cores/Socket|Frequency|  
|---|---|---|---|  
|Intel(R) Core(TM) i7-5960X CPU |1|8|3.00GHz|  

|OMP_NUM_THREADS| Perf(SPS)|
|---|---|
|4|557|
|6|685 |
|8|433|

I think the abnorm phenomenon could reflect the results of resource race. When threads of openmp is set to cores of platform, contrary the perf would be worse. 
@cpuhrsch Do you have some suggestion for us?

**Comment by cpuhrsch** [comment] 2018-05-29 04:57
I think you're right. Please see https://github.com/pytorch/pytorch/pull/7907 in response to this. I'd like to kindly ask you to rerun your benchmarks on the referenced pull request.

I suspect this is a bad interaction of OpenMP and tbb, as you mentioned, possibly due to MKL. There is a choice in threading libraries for MKL and one of them is tbb. I will look into that as part of a deeper investigation for this performance regression.

**Comment by MlWoo** [comment] 2018-05-29 06:29
@cpuhrsch It will be OK for us to rerun the benchmark.
However, OpenMP also plays an important role not only in hreading libraries for MKL but also in other parts of TH and THNN modules. I think introduction of tbb will influence widely and deeply in current project. @mingfeima Has Intel MKLDNN introduce TBB support right now?

**Comment by cpuhrsch** [comment] 2018-05-29 14:21
@MlWoo do you, in general, have an opinion on TBB vs OpenMP? We chose TBB over OpenMP because of it's more modern interface, hence easier integration into cpp and more flexible parallelism constructs.

**Comment by cpuhrsch** [comment] 2018-05-29 15:14
@MlWoo Does https://github.com/pytorch/pytorch/pull/7907 resolve the issues with the CNN benchmarks?

**Comment by MlWoo** [comment] 2018-05-29 23:32
@juliusshufan will help us benchmark the data. OpenCV adopts `tbb` in their project as well as blas library. I think it maybe give us a light.

**Comment by MlWoo** [comment] 2018-05-30 02:34
@cpuhrsch I find some info which are maybe useful.  [However, oversubscription is possible because TBB and OpenMP run-time libraries create separate thread pools, by default each creates a number of threads that matches the number of cores](https://software.intel.com/en-us/intel-threading-building-blocks-openmp-or-native-threads). You can acquire more info in this post.

**Comment by juliusshufan** [comment] 2018-05-30 06:02
@cpuhrsch Hi, we took a trial here, and the test results indicate the https://github.com/pytorch/pytorch/pull/7907 does not resolve the CNN perf, while the LSTM perf is speed-up.

Thanks.

**Comment by mingfeima** [comment] 2018-05-30 06:17
@cpuhrsch  just confirmed with mkl-dnn team, mkl-dnn doesn't support TBB at the moment, they are looking into supporting it but no ETA. So it's not likely that mkl-dnn can support TBB in a short while.
Data from @MlWoo and @juliusshufan verified that the perf drop is related to TBB and OpenMP competition.

Anyway, i think still we have two things to follow up:

- figure out if it is possible for TBB and OpenMP thread pool to run peacefully
- refine CPU benchmarks to track the performance regression

**Comment by anton-malakhov** [comment] 2018-05-31 15:57
I'd suggest trying `KMP_COMPOSABILITY=mode=exclusive` if you use Intel's OpenMP runtime, it will prevent quadratic over-subscription cases.
If PyTorch uses any Python threads or plain MKL (not just DNN part), you could try `tbb4py` (Python part of what used to be `tbb` package in Intel Distribution, now available on conda-forge as well) running application in TBB monkey-patch mode `python -m tbb app.py`

More details: https://github.com/anton-malakhov/scipy_proceedings/blob/2018-composability/papers/anton_malakhov/composability.rst

**Comment by cpuhrsch** [comment] 2018-05-31 16:07
I've also discovered that we set a relatively high grain size for functions such as tanh. [Lowering that threshold](https://github.com/pytorch/pytorch/pull/7941) has helped the performance a lot. The gap effectively disappears on the larger LSTM example (which is commented out), however for the smaller example the issue prevails. It's also important to explicitly call "torch.set_num_threads" at the beginning of the program.

@anton-malakhov Thank you for the pointer! I'll look into this while further investigating the regression on the small SLTm example.

@juliusshufan I've ran the [berkely example](https://github.com/MlWoo/PyTorch-benchmark/tree/master/berkely) within the [PyTorch-benchmark repo](https://github.com/MlWoo/PyTorch-benchmark) and didn't find a significant perf difference even without adjusting the grain size. Could you kindly post the commands you ran so I can try reproducing this regression locally?

@mingfeima I'm currently extending [the pytorch benchmark repo](https://github.com/pytorch/benchmark). We have indeed mostly focused on ad-hoc microbenchmarks to evaluate the performance. I'm working on a more rigorous and reproducible setup around this that we can hopefully all agree on. I'll also include the examples in the [PyTorch-benchmark repo](https://github.com/MlWoo/PyTorch-benchmark).

**Comment by cpuhrsch** [comment] 2018-05-31 20:28
I've rerun the LSTM example with the following modifications on top of [this PR](https://github.com/pytorch/pytorch/pull/8003).

```
--- a/rnn_benchmark/LSTM.py
+++ b/rnn_benchmark/LSTM.py
@@ -20,7 +20,7 @@ if 'daily' in sys.argv:

 if daily:
     sizes = [[64,50,500,500],
-         #[128,25,4096,4096]
+         [128,25,4096,4096]
         ]
     print("daily test")
 else:
```

It looks like the PR together with the small change largely resolves the perf issues.

`c9fc7b5` is the commit of the PR and `4d26939` the ID of the last commit without perf regression mentioned by @MlWoo.

I'm controlling the number of threads via `OMP_NUM_THREADS` and `MKL_NUM_THREADS`.

```
Using 16 threads

Commit: c9fc7b5
daily test
size = [64, 50, 500, 500], duration = 0.0637, gflops = 12.8000, GFLOPS = 200.8536, SPS = 1004.2682
size = [128, 25, 4096, 4096], duration = 1.7347, gflops = 858.9935, GFLOPS = 495.1874, SPS = 73.7887

Commit: 4d26939
daily test
size = [64, 50, 500, 500], duration = 0.0497, gflops = 12.8000, GFLOPS = 257.3203, SPS = 1286.6016
size = [128, 25, 4096, 4096], duration = 1.7258, gflops = 858.9935, GFLOPS = 497.7455, SPS = 74.1699


Using 8

Further benchmarks
Commit: c9fc7b5
daily test
size = [64, 50, 500, 500], duration = 0.0889, gflops = 12.8000, GFLOPS = 144.0471, SPS = 720.2356
size = [128, 25, 4096, 4096], duration = 2.5287, gflops = 858.9935, GFLOPS = 339.7022, SPS = 50.6196

Commit: 4d26939
daily test
size = [64, 50, 500, 500], duration = 0.0822, gflops = 12.8000, GFLOPS = 155.6714, SPS = 778.3568
size = [128, 25, 4096, 4096], duration = 2.4360, gflops = 858.9935, GFLOPS = 352.6199, SPS = 52.5445


Using 4

Commit: c9fc7b5
daily test
size = [64, 50, 500, 500], duration = 0.1511, gflops = 12.8000, GFLOPS = 84.6913, SPS = 423.4566
size = [128, 25, 4096, 4096], duration = 4.8528, gflops = 858.9935, GFLOPS = 177.0087, SPS = 26.3764

Commit: 4d26939
daily test
size = [64, 50, 500, 500], duration = 0.1495, gflops = 12.8000, GFLOPS = 85.6460, SPS = 428.2300
size = [128, 25, 4096, 4096], duration = 4.8822, gflops = 858.9935, GFLOPS = 175.9422, SPS = 26.2174
```

**Comment by anton-malakhov** [comment] 2018-06-01 15:59
No, it forces parallel regions to run in order, preventing their overlapping (due to outermost parallelism through TBB, Python threads or multiple processes) and thus preventing quadratic oversubscription. It cannot prevent oversubscription between 2 different thread pools though, e.g. TBB vs OMP if other TBB threads are not invoking OMP parallel regions. The worst performance hit is usually caused by quadratic oversubscription while running < 2P threads does not usually cause that bad effects (though is still sub-optimal)

**Comment by jhmenke** [comment] 2018-06-04 08:15
I also get a significant performance drop upgrading from 0.3 (via https://github.com/peterjc123/pytorch-scripts) to the official Windows 0.4.
The model is a simple feedforward network with two hidden layers and relatively small size (< 100 inputs and outputs). The batch size is 24.
I'm training on an i7-7700HQ.

Previous training times for three models were:

1. 49 s
2. 24 s
3. 56 s

Now, the same models use more time:
1. 61 s
2. 36 s
3. 94 s

**Comment by apaszke** [comment] 2018-06-04 15:22
@jhmenke could you please post the code you used to obtain those times? We need samples like those to debug problems

**Comment by jhmenke** [comment] 2018-06-05 07:01
Sorry, i made a minimal example and submitted it as a separate issue #8154

**Comment by mingfeima** [comment] 2018-06-14 05:16
@cpuhrsch update on the perf regression issue.
the [rnn_benchmark](https://github.com/MlWoo/PyTorch-benchmark/blob/master/rnn_benchmark/run.sh) is running inference only be default. By `python LSTM.py train daily`, you can run training.

One thing i didn't consider at the beginning it that `mkldnn v0.13` was compiled against `mkl v2018.0.2` of which certain gemm size has perf regression. This is fixed on `mkl v2018.0.3` and i have updated `mkldnn v0.14`. So make sure you have latest `mkl` and `mkldnn` installed.

Once the distraction is eliminated, i tested different KMP environment setting. I tried `KMP_COMPOSABILITY` and scale `KMP_BLOCKTIME` at the range of **[0.1, 10]**, the default value is `200`.

tested on Xeon 8180, 28 cores * 2 sockets, 2.5GHz

SPS | size | 4d26939 | c9fc7b5 | c9fc7b5  + KMP_BLOCKTIME=1
--|--|--|-- | --
training | [64, 50, 500,500] | 518.64 | 324.48 | 538.37
training | [128, 25, 4096, 4096] | 46.21 | 45.35 | 46.64
inference | [64, 50, 500,500] | **2173.17** | 1265.75 | **1252.68**
inference | [128, 25, 4096, 4096] | 93.70 | 92.22 | 92.60

it turns out with `KMP_BLOCKTIME=1` has the best perf, but **1~10** actually has very similar perf. Perf regression is pretty much solved except on inference of small LSTM, still has **1.7x** gap.

i will continue to dig how to solve this.

**Comment by cpuhrsch** [comment] 2018-06-14 20:12
@mingfeima - I looked into [removing tbb and replacing it with openmp](https://github.com/pytorch/pytorch/pull/8255) and then running the benchmark. I get much better performance when doing so. You could give this a try as well if you like. We generally prefer tbb for many reasons, but might need to (temporarily) go ahead with this if it turns out to be the main source for this and then reintroduce it as part of a larger effort.

Generally we can't expect the user to set or know about things like `KMP_BLOCKTIME` or 
 `KMP_AFFINITY`, so we'd either need to set them statically or change our setup so that they are not necessary.

**Comment by cpuhrsch** [comment] 2018-06-19 15:46
We removed TBB for now. Please try again.

**Comment by cpuhrsch** [comment] 2018-07-02 22:32
I'm closing this issue for now as the original topic is resolved and we want to be able to track these issues efficiently. Please let me know if this isn't the case.

The fallout issues from this are:
1. Conflict between TBB and OpenMP
2. Separate regression as mentioned by @jhmenke 

@mingfeima - I'll reproduce this locally and create a separate issue so we can close this out.
@juliusshufan - Are the conv numbers still an issue? I couldn't reproduce the regression as part of my benchmarks. If so, please create a separate issue.

**Closed by cpuhrsch** 2018-07-02 22:32 UTC
