### ISSUE TITLE
functionality mis-match for _multi_tensor_adam and _single_tensor_adam

### ISSUE THREAD

**Issue by zhuhaozhe** [pytorch/pytorch#78807] opened 2022-06-03 14:02 UTC
### 🐛 Describe the bug

In _single_tensor_adam, with inplace change the max_exp_avg_sq
https://github.com/pytorch/pytorch/blob/master/torch/optim/adam.py#L255
while in _multi_tensor_adam, with not change the value of max_exp_avg_sqs
https://github.com/pytorch/pytorch/blob/master/torch/optim/adam.py#L304

### Versions

PyTorch version: 1.13.0a0+gitdcbc823
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.11.0-46-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.13.0+cpu
[pip3] numpy==1.21.2
[pip3] pytorch-widedeep==1.0.0
[pip3] torch==1.13.0a0+gita4bc844
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.14.0a0+7b28442
[conda] intel-extension-for-pytorch 1.13.0+cpu                dev_0    <develop>
[conda] mkl                       2022.0.1           h06a4308_117  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] numpy                     1.21.2           py38hd8d4704_0  
[conda] numpy-base                1.21.2           py38h2b8c604_0  
[conda] pytorch-widedeep          1.0.0                     dev_0    <develop>
[conda] torch                     1.13.0a0+gita4bc844           dev_0    <develop>
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchvision               0.14.0a0+7b28442           dev_0    <develop>

cc @ezyang @gchanan @zou3519 @vincentqb @jbschlosser @albanD

**Comment by albanD** [comment] 2022-06-03 23:05
Hi,

Is that a problem? We don't provide any guarantee on how these algorithms are implemented and how they handle internal buffers.

**Comment by zhuhaozhe** [comment] 2022-06-04 01:13
> Hi,
> 
> Is that a problem? We don't provide any guarantee on how these algorithms are implemented and how they handle internal buffers.

Hi, yes. I think there are problems here.
From my understanding, internal buffers **max_exp_avg_sqs** aim to hold the max value of **exp_avg_sqs**. For each step, we should compare them and **update** max value into **max_exp_avg_sqs**.
In _multi_tensor_adam, the max value are not **updated** to **max_exp_avg_sqs**.

Here we need a ".out" version for _foreach_maximum just like maximum.out

**Comment by albanD** [comment] 2022-06-06 22:13
The value is actually updated.
Just that in one case the Tensor is updated inplace while in the other the self.max_exp_avg_sqs field is updated with a new set of values.

**Comment by zhuhaozhe** [comment] 2022-07-18 08:48
> The value is actually updated. Just that in one case the Tensor is updated inplace while in the other the self.max_exp_avg_sqs field is updated with a new set of values.

Hi, @albanD. Sorry for replying this late. The "self.max_exp_avg_sqs" are not updated with a new set of values.

It can be reproduced by the following codes:
```python
import torch
import copy

x = torch.rand(1, 1)
L = torch.nn.Linear(1, 1)
adam = torch.optim.Adam(L.parameters(), foreach=False, amsgrad=True)

L2 = copy.deepcopy(L)
adam2 = torch.optim.Adam(L2.parameters(), foreach=True, amsgrad=True)
for i in range(2):
    y = L(x).sum()
    adam.zero_grad()
    y.backward()
    adam.step()
print(adam.state)

for i in range(2):
    y = L2(x).sum()
    adam2.zero_grad()
    y.backward()
    adam2.step()
print(adam2.state)
```

The outputs will be 
```
defaultdict(<class 'dict'>, {Parameter containing:
tensor([[0.7942]], requires_grad=True): {'step': tensor(2.), 'exp_avg': tensor([[0.0539]]), 'exp_avg_sq': tensor([[0.0002]]), 'max_exp_avg_sq': tensor([[0.0002]])}, Parameter containing:
tensor([-0.9144], requires_grad=True): {'step': tensor(2.), 'exp_avg': tensor([0.1900]), 'exp_avg_sq': tensor([0.0020]), 'max_exp_avg_sq': tensor([0.0020])}})
defaultdict(<class 'dict'>, {Parameter containing:
tensor([[0.7942]], requires_grad=True): {'step': tensor(2.), 'exp_avg': tensor([[0.0539]]), 'exp_avg_sq': tensor([[0.0002]]), 'max_exp_avg_sq': tensor([[0.]])}, Parameter containing:
tensor([-0.9144], requires_grad=True): {'step': tensor(2.), 'exp_avg': tensor([0.1900]), 'exp_avg_sq': tensor([0.0020]), 'max_exp_avg_sq': tensor([0.])}})
```

We can find with foreach=True, max_exp_avg_sq are always 0 but with foreach=False, it can be updated as expected.

**Comment by albanD** [comment] 2022-07-20 15:08
Ho my bad, the given list is indeed a temporary object and so the original optimizer is not updated inplace.

cc @mikaylagawarecki this was most likely introduced in the refactor you helped with. Would you have a bit of time to take a look at this?

**Comment by mikaylagawarecki** [comment] 2022-07-25 16:56
Following up on this, tested parameter mismatches between the single and multi tensor optimizers and it seems that buffer mismatches in the state dict only exist for Adam and AdamW

As @zhuhaozhe suggested, the problem indeed seems to arise because pointwise maximum `foreach_maximum` does not have an `out` variant unlike [torch.maximum](https://pytorch.org/docs/stable/generated/torch.maximum.html?highlight=maximum#torch.maximum) and as such the buffer tensors in the state have not been being updated [here](https://github.com/pytorch/pytorch/blob/master/torch/optim/adam.py#L368).

If I understand correctly, none of the pointwise foreach operations support out variants yet and I'm not quite sure whether this is by design. A workaround for now would be to serially copy the results of foreach_maximum into the buffer tensors
Alternatively, we could look into adding foreach_maximum.out, @albanD what is the best course of action here? :)

**Comment by albanD** [comment] 2022-07-25 17:18
The alternatives are:
- Use the newly created Tensor (not possible with current API)
- Use copy in the for-loop
- Add foreach copy_ or inplace maximum

**Comment by albanD** [comment] 2022-07-25 17:18
We should also expand test coverage as such discrepancy should be easy to test for.

**Comment by crcrpar** [comment] 2022-07-26 00:28
Thanks for pinging me. I'll implement `foreach_maximum_` (and `foreach_minimum_`)

**Comment by mikaylagawarecki** [comment] 2022-08-09 15:07
Closing as this should be fixed on master

**Closed by mikaylagawarecki** 2022-08-09 15:07 UTC
Labels: high priority, module: optimizer, triaged, module: correctness (silent)
