### ISSUE TITLE
[docs] torch.nn.functional.bilinear has no description at all

### ISSUE THREAD

**Issue by henon** [pytorch/pytorch#22688] opened 2019-07-10 16:26 UTC
## 📚 Documentation

![image](https://user-images.githubusercontent.com/44090/60986664-41e0d980-a340-11e9-8fa6-89984863d69e.png)

**Comment by SsnL** [comment] 2019-07-10 16:39
duplicate of https://github.com/pytorch/pytorch/issues/9886

**Closed by SsnL** 2019-07-10 16:39 UTC
