### ISSUE TITLE
[pypi] Unavailability of Source Distribution for torch and torchvision

### ISSUE THREAD

**Issue by akjindal53244** [pytorch/pytorch#20518] opened 2019-05-15 02:34 UTC
## 🚀 Feature
I need to install `pytorch` through `pypi` (https://pypi.org/project/pytorch/) but it says:

> You tried to install “pytorch”. The package named for PyTorch is “torch"

While trying to install `torch` and `torchvision` through `pypi`, I found that there is no source distribution available for both, there are only wheels. In order to include any library, we require only source distribution available on `pypi` and due to unavailability of the same, it is not part of officially supported libraries within our company due to which we are not able to use `pytorch`.

## Motivation
Not able to build any `pytorch` model. Reason: Unavailability of source distribution of `torch` and `torchvision` on `pypi` and unsuccessful installation of `pytorch`

Question: What is the purpose of having `pytorch` source distribution if it can't be installed via `pip`? (shows above error)

## Pitch
1. Availability of source distributions of `torch` and `torchvision` on `pypi`
2. Alternatively successful installation of `pytorch` (since it's source distribution is available) on `pypi`.

## Alternatives
None

## Additional context
None

**Comment by ezyang** [comment] 2019-05-20 17:25
cc @soumith, what do you think?

**Comment by soumith** [comment] 2019-05-20 19:02
I'm pretty sure that providing a source distribution wont solve the problem -- because of dependencies (our git submodules and stuff), and the CUDA / CuDNN dependency

**Comment by akjindal53244** [comment] 2019-05-21 13:58
Hi @soumith , Is there any workaround to this problem? Also, since source distribution of pytorch is available, is there a way to install pytorch from there itself? currently while installing, it says: 

> You tried to install “pytorch”. The package named for PyTorch is “torch"

**Comment by soumith** [comment] 2019-05-27 05:53
@akjindal53244 not at this time

**Comment by nog642** [comment] 2020-09-26 04:00
This is preventing us from installing PyTorch conveniently on an ARM machine.

Should be fixed.

**Comment by rgommers** [comment] 2022-12-16 11:16
Sdist's are not on PyPI by design; building from source is highly likely to fail and result in lots of new issues. The remaining sdists for a few old releases were yanked last year, see https://github.com/pytorch/pytorch/issues/50535#issuecomment-969172240.

This issue is old, and there's nothing more to say here I think - closing.

**Closed by rgommers** 2022-12-16 11:16 UTC
Labels: oncall: binaries, feature, triaged
