### ISSUE TITLE
Add Variable to double strange behavior

### ISSUE THREAD

**Issue by nadavbh12** [pytorch/pytorch#2716] opened 2017-09-13 08:30 UTC
See the example below

```
>>> double = np.array([0.0], dtype=np.float64)[0]
>>> float = 0.0
>>> a = Variable(torch.FloatTensor(1))
>>> a + float
Variable containing:
1.00000e-34 *
  1.3192
[torch.FloatTensor of size 1]
>>> float + a
Variable containing:
1.00000e-34 *
  1.3192
[torch.FloatTensor of size 1]
>>> a + double
Variable containing:
1.00000e-34 *
  1.3192
[torch.FloatTensor of size 1]
>>> double + a
array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[Variable containing:
1.00000e-34 *
  1.3192
[torch.FloatTensor of size 1]
]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]], dtype=object)
```

**Comment by fmassa** [comment] 2017-09-13 11:08
This is a duplicate of https://github.com/pytorch/pytorch/issues/1294

**Comment by soumith** [comment] 2017-09-13 13:28
closing in favor of #1294

**Closed by soumith** 2017-09-13 13:28 UTC
