### ISSUE TITLE
[jit] Python built-in function support

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#18627] opened 2019-03-29 18:59 UTC
We support many built-in functions ([Python 2](https://docs.python.org/2/library/functions.html), [Python 3](https://docs.python.org/3/library/functions.html)), but not all of them. Some of these need some more discussion (i.e. what about builtins that exist in Python 2 but not 3 and vice versa), but many can be done piecemeal and should be straightforward to implement. When you implement a builtin please check to see if it is a [magic method](https://rszalski.github.io/magicmethods/).

To do
- [x] `abs()`
- [ ] `all()`
- [ ] `any()`
- [x] `bin()`
- [x] `bool()`
- [ ] `bytearray()`
- [x] `chr()`
- [x] `dict()`
- [x] `divmod()`
- [x] `enumerate()`
- [x] `float()`
- [x] `getattr()`
- [x] `hash()`
- [x] `hex()`
- [x] `int()`
- [x] `isinstance()`
- [x] `len()`
- [x] `list()`
- [x] `long()` (long is deprecated in py3 builtins)
- [x] `max()`
- [x] `min()`
- [x] `oct()`
- [x] `ord()`
- [x] `pow()`
- [x] `print()`
- [x] `range()`
- [x] `reversed()`
- [x] `round()`
- [ ] `set()`
- [ ] `slice()`
- [x] `sorted()` ([separate issue](https://github.com/pytorch/pytorch/issues/19372), implemented for lists)
- [x] `str()`
- [ ] `sum()`
- [ ] `type()`

Maybe to do later (when things like first class modules are in, or if we ever have something like iterators)
- [ ] `callable()`
- [x] `tuple()`
- [ ] `complex()`
- [ ] `delattr()`
- [ ] `filter()`
- [ ] `format()`
- [ ] `frozenset()`
- [ ] `globals()`
- [ ] `hasattr()`
- [ ] `issubclass()`
- [ ] `iter()`
- [ ] `locals()`
- [ ] `next()`
- [ ] `object()`
- [ ] `property()`
- [ ] `reduce()`
- [ ] `setattr()`
- [ ] `repr()`
- [ ] `super()`
- [ ] `vars()`
- [x] `zip()`

Probably won't do
- [ ] `__import__()`
- [ ] `basestring()`
- [ ] `classmethod()`
- [ ] `cmp()`
- [ ] `compile()`
- [ ] `dir()`
- [ ] `eval()`
- [ ] `execfile()`
- [ ] `file()`
- [ ] `help()`
- [ ] `id()`
- [ ] `input()`
- [ ] `map()`
- [ ] `memoryview()`
- [ ] `open()`
- [ ] `raw_input()`
- [ ] `reload()`
- [ ] `staticmethod()`
- [ ] `unichr()`
- [ ] `unicode()`
- [ ] `xrange()`

cc @suo

**Comment by eellison** [comment] 2019-03-29 19:23
@https://github.com/pytorch/pytorch/pull/18502 handles `abs`

**Comment by ailzhang** [comment] 2019-04-03 23:45
`range` is partially available as `rangelist()`, we just need to add `step` support.
rangelist(2) -> [0, 1]

**Comment by aditya1702** [comment] 2019-04-08 05:08
are pull requests welcome for this issue?

**Comment by driazati** [comment] 2019-04-08 16:00
Yes of course. As far as I know no one is working on any of these, so you can just pick whichever you want to do. Be sure to tag me and @eellison when you submit it so we can review it.

**Comment by qb-tarushg** [comment] 2019-04-08 16:07
@driazati @aditya1702 I have also started working on this #18627 but not mentioned it as I was getting familiar with the code base. If possible can we divide these functions among ourselves for the implementation so as to avoid duplicate work?

**Comment by aditya1702** [comment] 2019-04-08 16:15
@qb-tarushg Sure. I am also going through the codebase. We will divide the functions.

**Comment by qb-tarushg** [comment] 2019-04-08 16:22
@aditya1702 cool, thanks 👍

**Comment by eellison** [comment] 2019-04-08 16:30
Another good first issue is supporting the builtin-in math functions. I'll create a separate issue to track that

**Comment by aditya1702** [comment] 2019-04-08 16:40
@eellison Cool! Also what does [jit] tag mean?

**Comment by eellison** [comment] 2019-04-08 17:17
FYI: https://github.com/pytorch/pytorch/issues/19026

It means that the issue is relevant to Pytorch jit / Torchscript and not really pytorch when run in pure python.

**Comment by michaelarg** [comment] 2019-04-09 03:15
Hi all, I have started work on all() and sum().

**Comment by aditya1702** [comment] 2019-04-09 19:46
Hi all, I am working on any() and long()

**Comment by qb-tarushg** [comment] 2019-04-09 20:38
Hi all, I am working on bin(), enumerate(), reversed()

**Comment by michaelarg** [comment] 2019-05-16 03:21
Here is my all pull request #20521

**Comment by pandeykartikey** [comment] 2019-05-24 09:41
Hi all, I would like to work on `pow()` function. If nobody else is already working on it. Also, I am a first time contributor so if i should look up something else before working on it, It would be great help if you can point that out. Thanks!

**Comment by driazati** [comment] 2019-05-24 20:46
@pandeykartikey Looks like we already have a `pow()` implementation, feel free to pick up something else if you'd like (maybe `divmod()`). #20769 is also a very similar task if you want to look there.

**Comment by pandeykartikey** [comment] 2019-05-26 06:48
Thanks @driazati . `divmod()` sounds nice. Will soon submit a PR for the same. :smile:

**Comment by pandeykartikey** [comment] 2019-05-27 06:51
@driazati here is my all pull request #20979 for `divmod()`.

**Comment by ailzhang** [comment] 2019-05-30 04:49
Hey all, we have promoted priority of this task and will try finish the unchecked ones in todo section. If you have wip PRs that would like to commit, it would be great if you send them in the next a few days or let us know. Thanks a lot!

**Comment by ailzhang** [comment] 2019-05-30 05:07
I've seen 
`* all
* sum
* any
* long
* bin
* enumerate
* reversed
* divmod
` have been claimed, please let us know if you are still working on them. Thanks!

**Comment by pandeykartikey** [comment] 2019-05-30 05:22
@ailzhang I have submitted a PR #20979  for `divmod` it's under review.

**Comment by michaelarg** [comment] 2019-05-30 05:23
Hey @ailzhang all was completed and merged earlier, see #20521. 
I have just submitted my pull request for sum, see #21121.

**Comment by ailzhang** [comment] 2019-06-17 16:56
#21451

**Comment by anhar-adiljan** [comment] 2019-06-30 23:48
Hello all. Is anyone working on `all()`, `range()`, or `max()`? If not, then I would like to be involved in this. Also a first time contributor here.

**Comment by wanchaol** [comment] 2019-07-01 18:36
> Hello all. Is anyone working on `range()` or `max()`? I noticed that `range()` is mostly available except for `step` support from a previous comment. If not then I am interested in getting involved. Also a first time contributor here.

@anhar-adiljan `range()` is supported already with the step argument, and `max` is already supported as well.

**Comment by anhar-adiljan** [comment] 2019-07-03 04:25
> > Hello all. Is anyone working on `range()` or `max()`? I noticed that `range()` is mostly available except for `step` support from a previous comment. If not then I am interested in getting involved. Also a first time contributor here.
> 
> @anhar-adiljan `range()` is supported already with the step argument, and `max` is already supported as well.
> 
> update: `max()` that takes a list or tuple or iterators need to implement though, that part is under discussion, I think `max()`, `min()` and `all()` `any()` will follow the same pattern of implementation after the discussion is clear.
> 
> Fell free to take any other builtins :)

Thank you for the quick update. How about `set()`, `slice()`, and `type()`? I searched for them in this thread, and it seems like they are not claimed yet.

Also, you mentioned about discussion for `max()` that takes a list of tuples or iterators. Would you mind pointing out  where the discussion is for those who are interested in observing / participating?

**Comment by wanchaol** [comment] 2019-07-16 20:08
> > > Hello all. Is anyone working on `range()` or `max()`? I noticed that `range()` is mostly available except for `step` support from a previous comment. If not then I am interested in getting involved. Also a first time contributor here.
> > 
> > 
> > @anhar-adiljan `range()` is supported already with the step argument, and `max` is already supported as well.
> > update: `max()` that takes a list or tuple or iterators need to implement though, that part is under discussion, I think `max()`, `min()` and `all()` `any()` will follow the same pattern of implementation after the discussion is clear.
> > Fell free to take any other builtins :)
> 
> Thank you for the quick update. How about `set()`, `slice()`, and `type()`? I searched for them in this thread, and it seems like they are not claimed yet.
> 
> Also, you mentioned about discussion for `max()` that takes a list of tuples or iterators. Would you mind pointing out where the discussion is for those who are interested in observing / participating?

@anhar-adiljan hi sorry for the late reply. Yeah I think you could take those as no one working on them.

For the discussion on `max()`, it's mainly come from the stack of these PRs https://github.com/pytorch/pytorch/pull/22006, we would want to utilize our new iterator infrastructure to implement those.

**Comment by jaydeepthik** [comment] 2019-09-11 00:47
@ailzhang I really want to contribute to the built in functions what are the next steps ? thanks

**Comment by ailzhang** [comment] 2019-09-11 00:55
Hi is there any particular builtin functions that you would like to contribute? Or are you looking for issues to start contributing to Pytorch JIT? Thanks!

**Comment by jaydeepthik** [comment] 2019-09-11 01:08
> Hi is there any particular builtin functions that you would like to contribute? Or are you looking for issues to start contributing to Pytorch JIT? Thanks!

I would like to contribute to max and min for a start

**Comment by eellison** [comment] 2019-10-22 09:23
@driazati some of the builtins were marked finished that are not actually implemented: `all`, 'any', `sum`

**Comment by ppwwyyxx** [comment] 2020-02-13 20:09
`all()` appears to work on tensors but not `List[bool]`:
```
import torch
from typing import List
@torch.jit.script
def fun(tensor, v: List[bool]):
    return all(tensor)
    assert all(v)
    return tensor + 1
fun(torch.random(3), [True, False])
```
```
Arguments for call are not valid.
The following variants are available:
  
  aten::all(Tensor self) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'List[bool]'.
  
  aten::all.dim(Tensor self, int dim, bool keepdim=False) -> (Tensor):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'List[bool]'.
  
  aten::all.out(Tensor self, int dim, bool keepdim=False, *, Tensor(a!) out) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'self' but instead found type 'List[bool]'.

The original call is:
  File "a.py", line 6
def fun(tensor, v: List[bool]):
    return all(tensor)
    assert all(v)
           ~~~ <--- HERE
    return tensor + 1

```

**Comment by michaelarg** [comment] 2020-02-14 01:48
I'm back on this issue today.

**Comment by ppwwyyxx** [comment] 2020-04-29 20:08
`zip` does not work for list of python objects:
```
> Only constant Sequential, ModueList, or ModuleDict can be used as an iterable:
>   File "detectron2/modeling/anchor_generator.py", line 158              
>     def _grid_anchors(self, grid_sizes: List[List[int]]):
>         anchors = []
>         for size, stride, base_anchors in zip(grid_sizes, self.strides, self.cell_anchors):
>                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE                                                                                              
>             shift_x, shift_y = _create_grid_offsets(size, stride, self.offset, base_anchors.device)                                                                                              
>             shifts = torch.stack((shift_x, shift_y, shift_x, shift_y), dim=1)
```

**Closed** 2021-02-19 07:05 UTC
Labels: jit-backlog, oncall: jit, triaged
