### ISSUE TITLE
tensorboardx add_graph unexpected error 

### ISSUE THREAD

**Issue by HusainKapadia** [pytorch/pytorch#22199] opened 2019-06-25 13:03 UTC
I get the following error when I use writer.add_graph. The code works totally fine when I comment the line. 
Error dialog shows:
```
UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. Negative axis is not supported in ONNX. Axis is converted to 2 based on input shape at export time. Passing an tensor of different rank in execution will be incorrect.
  "Passing an tensor of different rank in execution will be incorrect.")
/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/symbolic.py:1388: UserWarning: ONNX export unsqueeze with negative axis -1 might cause the onnx model to be incorrect. Negative axis is not supported in ONNX. Axis is converted to 4 based on input shape at export time. Passing an tensor of different rank in execution will be incorrect.
  "Passing an tensor of different rank in execution will be incorrect.")
/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/onnx/symbolic.py:173: UserWarning: ONNX export failed on RNN/GRU/LSTM because batch_first not supported
  warnings.warn("ONNX export failed on " + op + " because " + msg + " not supported")
Traceback (most recent call last):
  File "train.py", line 279, in <module>
    train(model, optimiser, epochs=config.num_epochs, batch_size=bs, step=step, lr=1e-4)
  File "train.py", line 195, in train
    writer.add_graph(model, (x, m))
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorboardX/writer.py", line 566, in add_graph
    self.file_writer.add_graph(graph(model, input_to_model, verbose))
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py", line 240, in graph
    list_of_nodes, node_stats = parse(graph, args, omit_useless_nodes)
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py", line 161, in parse
    nodes_py.append(Node_py_OP(node))
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py", line 74, in __init__
    super(Node_py_OP, self).__init__(Node_cpp, methods_OP)
  File "/home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/tensorboardX/pytorch_graph.py", line 54, in __init__
    io_tensorSize_list.append(n.type().sizes())
RuntimeError: r ASSERT FAILED at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/ATen/core/jit_type.h:142, please report a bug to PyTorch. (expect at /opt/conda/conda-bld/pytorch_1556653215914/work/aten/src/ATen/core/jit_type.h:142)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7f74a6162dc5 in /home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: std::shared_ptr<c10::CompleteTensorType> c10::Type::expect<c10::CompleteTensorType>() + 0xa3 (0x7f74cc20ef43 in /home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x421abb (0x7f74cc224abb in /home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x12d07a (0x7f74cbf3007a in /home/hkapadia/anaconda3/envs/pytorch/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #36: __libc_start_main + 0xf0 (0x7f74db142830 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by jamesr66a** [comment] 2019-06-25 20:54
@orionr do you have context on this? It looks like TensorboardX is expecting a Value with full shape information, but we don't have that info in the graph

**Comment by HusainKapadia** [comment] 2019-06-27 18:50
I'm not sure I understand, what kind of context are you looking for? If you can specify something you need, I can share it here.

**Comment by jamesr66a** [comment] 2019-07-01 22:22
I'm talking to @orionr, not you

**Comment by HusainKapadia** [comment] 2019-07-02 06:40
Lol...sorry...didn't see that

**Comment by suo** [comment] 2019-11-22 18:04
Going to close this as TensorboardX is no longer a thing (the core functionality has been merged into PyTorch), and I don't have enough information to reproduce this issue. If the actual problem persists, feel free to reopen this issue or file a new one!

**Closed by suo** 2019-11-22 18:04 UTC
Labels: jit, module: tensorboard, topic: assert failure, triaged
