### ISSUE TITLE
nn.MaxUnpool{1,2,3}d does not handle the invalid input when running in CUDA

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#68727] opened 2021-11-22 12:31 UTC
## 🐛 Bug

For some invalid input, `torch.nn.MaxUnpool2d` will raise an error in cpu mode, but work normally and return a tensor in cuda mode.

## To Reproduce

```python
import torch

cpu = torch.nn.MaxUnpool2d(2,stride=2,)
cuda = torch.nn.MaxUnpool2d(2,stride=2).to("cuda:0")

output = torch.rand(torch.Size([1, 1, 2, 2]), dtype=torch.float32)
indices = torch.randint(-32768,32768,torch.Size([1, 1, 2, 2]), dtype=torch.int64)

cuda_res = cuda(output.cuda(), indices.cuda())
print(cuda_res)

cpu_res = cpu(output, indices)
print(cpu_res)
```

The result will be:
```
tensor([[[[0., 0., 0., 0.],
          [0., 0., 0., 0.],
          [0., 0., 0., 0.],          [0., 0., 0., 0.]]]], device='cuda:0')
...
RuntimeError: Found an invalid max index: -27538 (output volumes are of size 4x4
```

## Expected behavior

It should handle such invalid behavior. At least they should have the same behavior.

## Environment

 - PyTorch Version (e.g., 1.0): 1.10.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.9.7
 - CUDA/cuDNN version: 11.1
 - GPU models and configuration: RTX 3090

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @mruberry @walterddr @ngimel

**Comment by malfet** [comment] 2021-11-22 18:05
Is this a regression? Or it was always like that?

**Comment by malfet** [comment] 2021-11-22 18:23
We want to check that indexes are valid and raise an error in this case

**Comment by ngimel** [comment] 2021-11-23 02:33
Can repro in 1.9, not a regression

**Comment by kurtamohler** [comment] 2021-12-29 22:42
Looks like `MaxUnpool3d` has this issue as well.

What is the best way to detect the invalid values given to a CUDA kernel? We could just check them before the CUDA kernel is called--but that would require a CUDA sync. Maybe another option is to return an error flag from the CUDA kernel if it sees an invalid value and then throw the error after the kernel is finished. How do other CUDA operations handle errors like this?

**Comment by ngimel** [comment] 2021-12-30 02:24
Other cuda kernels raise device assert. There's no way to nicely raise a flag

**Comment by kurtamohler** [comment] 2021-12-30 22:25
So I guess there must not be a good way to write tests for device asserts either, right? Or do we have a way to do that?

**Comment by ngimel** [comment] 2021-12-31 05:17
By running a test in a subprocess, we have a few tests like this (marked as slow), but not for all ops that are supposed to trigger device-side assert.

**Closed** 2022-05-23 21:08 UTC
Labels: high priority, module: nn, module: cuda, module: error checking, triaged, module: pooling
