### ISSUE TITLE
TestE2ETensorPipe.TestTrainingLoop is Flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#51110] opened 2021-01-26 15:17 UTC
https://app.circleci.com/pipelines/github/pytorch/pytorch/263779/workflows/c1535b0d-74cb-467f-9955-b05adf928ade/jobs/10367433/steps

```
Jan 25 23:17:56 [----------] Global test environment tear-down
Jan 25 23:17:56 [==========] 9 tests from 4 test cases ran. (1651 ms total)
Jan 25 23:17:56 [  PASSED  ] 8 tests.
Jan 25 23:17:56 [  FAILED  ] 1 test, listed below:
Jan 25 23:17:56 [  FAILED  ] TestE2ETensorPipe.TestTrainingLoop
```

```
/var/lib/jenkins/workspace/test/cpp/rpc/test_e2e_tensorpipe.cpp:59
Expected equality of these values:
  0
  tensorpipeAgent->timeoutMapSize()
    Which is: 2
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @lw @beauby @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment] 2021-01-31 02:23
Closing as this is a duplicate of https://github.com/pytorch/pytorch/issues/51007

**Closed by rohan-varma** 2021-01-31 02:23 UTC
Labels: module: flaky-tests, module: rpc, module: tensorpipe, oncall: distributed, triaged
