### ISSUE TITLE
Inductor doesn't inplace normalization operations

### ISSUE THREAD

**Issue by Chillee** [pytorch/pytorch#136099] opened 2024-09-14 18:50 UTC
### 🚀 The feature, motivation and pitch

Inductor can inplace pointwise operations, but it doesn't inplace normalization operations.

```
@torch.compile
def f(a, op):
    a = torch.mm(a, a)
    if op == "cos":
        a = a.cos()
    elif op == "softmax":
        a = torch.softmax(a, dim=-1)
    return a

def measure_peak_mem(f):
    start_memory = torch.cuda.memory_allocated()
    f()
    peak_mem = (torch.cuda.max_memory_allocated() - start_memory)
    torch.cuda.reset_peak_memory_stats()
    return peak_mem

inp = torch.randn(8192, 8192)
buf_size = inp.numel() * inp.dtype.itemsize
print("cos: ", measure_peak_mem(lambda: f(inp, "cos"))/buf_size)
print("softmax: ", measure_peak_mem(lambda: f(inp, "softmax"))/buf_size)
```
```
cos:  1.03173828125
softmax:  2.0
```

cc @ezyang @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by eellison** [comment] 2024-09-14 21:30
Dupe of https://github.com/pytorch/pytorch/issues/132826

**Closed by eellison** 2024-09-14 21:30 UTC
Labels: oncall: pt2, module: inductor
