### ISSUE TITLE
`torch.nn.functional.gumbel_softmax` returns different results on cpu and on cuda with the same input

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#82071] opened 2022-07-24 03:48 UTC
### 🐛 Describe the bug

`torch.nn.functional.gumbel_softmax` returns different results on cpu and on cuda with the same input

```
import torch
torch.random.manual_seed(420)
input = torch.randn(2,3,requires_grad=True)
res_cpu = torch.nn.functional.gumbel_softmax(input, hard=True)
print("res_cpu: ", res_cpu)
input2 = input.clone().detach().to('cuda')
res_gpu = torch.nn.functional.gumbel_softmax(input2, hard=True)
print("res_gpu: ", res_gpu)
```

Outputs:
```
res_cpu:  tensor([[0., 1., 0.],
        [1., 0., 0.]], grad_fn=<AddBackward0>)
res_gpu:  tensor([[0., 1., 0.],
        [0., 1., 0.]], device='cuda:0')
```

### Versions

pytorch: 1.12.0

cc @ezyang @gchanan @zou3519 @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ngimel

**Comment by Aidyn-A** [comment] 2022-07-25 18:09
Hi @fuzzyswan,
Thank you for reporting the issue.
I could replicate the bug in the latest master. I will take care of it.

**Comment by Aidyn-A** [comment] 2022-08-02 16:24
Hi @fuzzyswan,

From what I gathered so far, it seems that the exact match between CPU and GPU results is impossible due to stochastic nature of `gumbel_softmax`. Moreover, two different calls on CPU-only may produce different results.
The line here:
https://github.com/pytorch/pytorch/blob/5aef03513f2ebcc56bd0687d99da04cc073af15c/torch/nn/functional.py#L1893
generates a set random numbers that later is used for obtaining the final result, so the direct comparison between two results is basically a comparison between two different sets of random numbers. It would make more sense to compare statistical averages, that must be equal. 

For more information please read the original papers [here](https://arxiv.org/abs/1611.00712) and [here](https://arxiv.org/abs/1611.01144).

**Comment by ngimel** [comment] 2022-08-02 16:51
Closing as expected behavior, thanks for checking @Aidyn-A

**Closed by ngimel** 2022-08-02 16:51 UTC
Labels: high priority, module: nn, module: cuda, triaged, module: correctness (silent)
