### ISSUE TITLE
Regression in JIT tracer with loops

### ISSUE THREAD

**Issue by lara-hdr** [pytorch/pytorch#29909] opened 2019-11-15 17:40 UTC
## 🐛 Bug
I noticed a regression in the jit tracer in the last 3 days.
I made some test and it seems that it is coming from https://github.com/pytorch/pytorch/pull/29230 (commit 5b702ab52b572895f8dd2bf49e50f187febe4047).

## To Reproduce
In the below example I have a loop on "i" in range(10), when I trace it, "i" starts taking weird values when torch.cat() is used in the loop, I think it starts taking the value of the output of cat and becomes a tensor (it is not happening with all operators, but I not sure if cat is the only operator affected).
When I test with the commit right before #29230 was merged (cedca377bd005d68f553648c5b36dbd58a62a520), I do not see this error, but I am not sure how the changes in #29230 affect the tracer.
Here is a simple repro.

```
@torch.jit.script
def fct_loop(x):
    for i in range(10):
        print(i)
        x = torch.cat((x, x), 0)
    return x

x = torch.randn(2, 3, 4,dtype=torch.float32)
out = fct_loop(x)
jit_trace = torch.jit.trace(fct_loop, x)
out_trace = jit_trace(x)
```

## Environment
 - PyTorch Version (e.g., 1.0): Commit 5b702ab52b572895f8dd2bf49e50f187febe4047
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup develop
 - Python version: 3.7.3
 - CUDA/cuDNN version: -
 - GPU models and configuration: - 
 - Any other relevant information: -

## Additional context

cc @suo

**Comment by houseroad** [comment] 2019-11-15 17:41
cc: @Krovatkin @suo

**Comment by Krovatkin** [comment] 2019-11-15 18:25
@lara-hdr Thanks for reporting this! I'll look into this ASAP.

**Comment by Krovatkin** [comment] 2019-11-15 18:41
@lara-hdr could you try removing `@torch.jit.script` if you are decided to use a jit tracer? I think we usually use either tracer or jitter, using both is a bit unusual mode for us and seems to have exposed an issue in our new graph executor infrastructure.

**Comment by lara-hdr** [comment] 2019-11-15 18:59
Indeed if I remove @torch.jit.script, it works fine in the above example.
In this example, it is fine since it is just a simple repro, but more complex scenarios that require to mix both tracing and scripting will be broken... 
Do you have an idea of why this regression is introduced?

**Comment by Krovatkin** [comment] 2019-11-15 19:25
@lara-hdr we are switching to a new graph executor infrastructure and we are enabling it for our OSS users. We would like our users to use andh help us test our new infrastructure as much as possible but at this point you could get the original behaviour by setting these switches to false in python
```python
torch._C._jit_set_profiling_executor(False)
torch._C._jit_set_profiling_mode(False)
```
and in c++
```cpp
getExecutorMode() = false;
getProfilingMode() = false;
```

**Comment by jamesr66a** [comment] 2019-11-18 21:48
Tracing scripted modules should work just fine (the graph should just be inlined) so this indeed seems like a regression. @Krovatkin did you change affect how this behavior works?

**Comment by Krovatkin** [comment] 2019-11-18 21:58
> Tracing scripted modules should work just fine (the graph should just be inlined) so this indeed seems like a regression. @Krovatkin did you change affect how this behavior works?

Yes and no. I believe traced graphs look exactly the same, but the way we are handling input specialization in Profiling executor seems to have a bug that is exposed by `check_trace` switching between `requires_grad` true and false. I'm investigating this issue.

**Comment by Krovatkin** [comment] 2019-11-19 18:39
@lara-hdr your repro hit not just one, but two bugs at the same time 🥇 
I have a fix for a more glaring one, which is a crash due to a missing argument to one of the nodes: https://github.com/pytorch/pytorch/pull/30097
The second issue is that `i` counter isn't updated properly when we transition to a new graph, so in one of the iterations the counter value will be wrong.
I'm still working on the second issue, but there's a workaround you could use: if you switch to `while (i < count)` the counter should be updated properly.
I'll let you know when I have a fix for the second issue and the first fix is merged.

**Comment by lara-hdr** [comment] 2019-11-19 18:59
thanks for the fix!

**Comment by Krovatkin** [comment] 2019-11-20 22:07
@lara-hdr I also have a tentative fix for the second issue now: https://github.com/pytorch/pytorch/pull/30186 Hopefully, the fix for the first issue will be merged today.

**Comment by Krovatkin** [comment] 2020-01-23 19:48
this should be fixed now

**Closed by Krovatkin** 2020-01-23 19:48 UTC
Labels: jit, triaged
