### ISSUE TITLE
torch.topk returns floating type indecies

### ISSUE THREAD

**Issue by roger60229** [pytorch/pytorch#14679] opened 2018-12-02 10:42 UTC
## 🐛 Bug

Hi, i get an error when i using the torch.topk to fetch indices and feeding the indices to the torch.gather.
The indices tensor is feeded to gather()  in scientific format.
## To Reproduce
Part of the code:
```
# choose top K
candidate_weight, idx = torch.topk(weights, self.num_cxt, dim=1) # (batch, num_cxt), (batch, num_cxt)
idx_expand  = idx.unsqueeze(-1).expand(batch_size, self.num_cxt, self.fc7_dim) # (batch, num_cxt, fc7_dim)
# the error reported under the line
candidate_value = torch.gather(value, dim = 1, index = idx_expand) # (batch, topK, fc7_dim ) -> (batch, num_cxt, fc7_dim)
```
Log error:
```
/opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [71,0,0], thread: [221,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [71,0,0], thread: [222,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
/opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/THCTensorScatterGather.cu:97: void THCudaTensor_gatherKernel(TensorInfo<Real, IndexType>, TensorInfo<Real, IndexType>, TensorInfo<long, IndexType>, int, IndexType) [with IndexType = unsigned int, Real = float, Dims = 3]: block: [71,0,0], thread: [223,0,0] Assertion `indexValue >= 0 && indexValue < src.sizes[dim]` failed.
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCTensorScatterGather.cu line=70 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "./tools/train.py", line 234, in <module>
    main(args)
  File "./tools/train.py", line 160, in main
    loss, T, wrapped = lossFun(loader, optimizer, model, mm_crit, att_crit, opt, iter)
  File "./tools/train.py", line 71, in lossFun
    labels)
  File "/home/larrymaw/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/caffe3/9099c731-7470-410b-80ff-0f68765873aa/larrymaw/Visual_grounding/tools/../lib/layers/joint_match.py", line 218, in forward
    cxt_fc7, cxt_fc7, cxt_lfeats) # (n, num_cxt, fc7_dim), (n, num_cxt, 2)
  File "/home/larrymaw/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 357, in __call__
    result = self.forward(*input, **kwargs)
  File "/media/caffe3/9099c731-7470-410b-80ff-0f68765873aa/larrymaw/Visual_grounding/tools/../lib/layers/joint_match.py", line 315, in forward
    candidate_value = torch.gather(value, dim = 1, index = idx_expand) # (batch, topK, fc7_dim ) -> (batch, num_cxt, fc7_dim)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1518238409320/work/torch/lib/THC/generic/THCTensorScatterGather.cu:70
```
## Expected behavior
Due to the bug turns out after training a few iteration
I have printed out the right(expected) behavior
```
idx : Variable containing:
    5     2     0     3     1
    5     2     0     3     1
    5     1     0     3     2
              ⋮
    8     2     0     3     1
    8     2     0     3     1
    8     2     0     3     1
[torch.cuda.LongTensor of size 387x5 (GPU 0)]

value_size : [387L, 12L, 2048L]
idx : Variable containing:
    0     3     1     4     2
    0     3     1     4     2
    0     3     1     4     2
              ⋮
    0     3     1     4     2
    0     3     1     4     2
    0     3     1     4     2
[torch.cuda.LongTensor of size 396x5 (GPU 0)]

value_size : [396L, 12L, 2048L]
idx : Variable containing:
    1     3     0     4     2
    1     3     0     4     2
    1     3     0     4     2
              ⋮
    1     3     0     4     2
    1     3     0     4     2
    1     3     0     4     2
[torch.cuda.LongTensor of size 423x5 (GPU 0)]
```
And the error turns out follow by printing out a scientific indices
```
idx : Variable containing:
 1.0000e+00  3.0000e+00  0.0000e+00  4.0000e+00  2.0000e+00
 1.0000e+00  3.0000e+00  0.0000e+00  4.0000e+00  2.0000e+00
 1.0000e+00  3.0000e+00  0.0000e+00  4.0000e+00  2.0000e+00
                             ⋮
 0.0000e+00  3.0000e+00  1.0000e+00  4.0000e+00  2.0000e+00
 0.0000e+00  3.0000e+00  1.0000e+00  4.0000e+00  2.0000e+00
 0.0000e+00  3.0000e+00  1.0000e+00  4.0000e+00  2.0000e+00
[torch.cuda.LongTensor of size 360x5 (GPU 0)]

value_size : [360L, 12L, 2048L]

```

## Environment

 - PyTorch Version: both 0.4.1 and 0.3.1.post2 get the error
 - OS : Ubuntu 14.04
 - How you installed PyTorch : conda
 - Python version: 2.7
 - CUDA/cuDNN version: 8.0/5.0.5

**Comment by fmassa** [comment] 2019-01-10 14:57
I couldn't reproduce this, and the tensor you have printed is a long tensor.
Closing this issue, but let us know if you have a repro.

**Closed by fmassa** 2019-01-10 14:57 UTC
Labels: todo
