### ISSUE TITLE
[C++] Inference Pytorch and TensorRT got errors on Windows

### ISSUE THREAD

**Issue by long-senpai** [pytorch/pytorch#71079] opened 2022-01-10 07:25 UTC
### 🐛 Describe the bug

- I need to integrate [Alphapose](https://github.com/LuongTanDat/AlphaPose-Cpp) with pytorch and Yolov4 based TensorRT into my C++ project. On Ubuntu, the code on this link was OK, but when i tranfer to Windows 10.
- When I use `torch.jit.trace(model)` for [conversion](https://github.com/LuongTanDat/AlphaPose-Cpp/blob/main/convert_torchscript.py#L37), I maked sure that model was transfer to GPU.
- If I load model into GPU by: `torch::jit::load(model_path, torch::kCUDA);`, I got `PyTorch is not linked with support for cuda devices`, I tried it both pytorch `built from source` and `libtorch 1.10.1` for `CUDA-11.3`.
- If I load model pytorch to CPU by `torch::jit::load(model_path, torch::kCPU);`, the loading was finished successfully, but new error occured:
```
Exception thrown at 0x00007FFAE364BB46 (torch_cpu.dll) in AlphaPoseCpp.exe: 0xC0000005: Access violation reading location 0x000002971D5FE000.
```
- **Is there any method to create new context that separate with context used by Yolo tensorRT?**

### Versions

```
Collecting environment information...
PyTorch version: 1.10.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: version 3.22.0-rc2
Libc version: N/A

Python version: 3.8.8 (default, Apr 13 2021, 15:08:03) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.3.58
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650
Nvidia driver version: 497.29
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.1
[pip3] numpydoc==1.1.0
[pip3] torch==1.10.1+cu113
[pip3] torchaudio==0.10.1+cu113
[pip3] torchfile==0.1.0
[pip3] torchvision==0.11.2+cu113
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.2.0           haa95532_296
[conda] mkl-service               2.3.0            py38h2bbff1b_1
[conda] mkl_fft                   1.3.0            py38h277e83a_2
[conda] mkl_random                1.2.1            py38hf11a4ad_2
[conda] mypy_extensions           0.4.3                    py38_0
[conda] numpy                     1.20.1           py38h34a8a5c_0
[conda] numpy-base                1.20.1           py38haf7ebc8_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.10.1+cu113             pypi_0    pypi
[conda] torchaudio                0.10.1+cu113             pypi_0    pypi
[conda] torchvision               0.11.2+cu113             pypi_0    pypi
```

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by alexkehoe** [comment] 2022-01-13 16:09
@mruberry Hi Mike, any thoughts on this issue? We have a customer demo coming up soon so it would be good to get this resolved asap. Any assistance would be much appreciated. Thanks

**Comment by mszhanyi** [comment] 2022-01-14 04:36
After replacing a lot AT_CHECK to TORCH_CHECK in alphapose, there's the error below while installing the Alphapose
`error: Setup script exited with error: library dfftpack has Fortran sources but no Fortran compiler found`

**Comment by mszhanyi** [comment] 2022-01-14 08:40
@long-senpai , I'm trying to reproduce it. But I came across issues to install alphapose on Windows. 
```
    Fortran 77 wrappers are saved to "build\src.win-amd64-3.9\scipy\stats\mvn-f2pywrappers.f"
WARN: Could not locate executable g77
WARN: Could not locate executable f77
WARN: Could not locate executable ifort
WARN: Could not locate executable ifl
WARN: Could not locate executable f90
WARN: Could not locate executable DF
WARN: Could not locate executable efl
WARN: Could not locate executable gfortran
WARN: Could not locate executable f95
WARN: Could not locate executable g95
WARN: Could not locate executable efort
WARN: Could not locate executable efc
WARN: Could not locate executable flang
WARN: don't know how to compile Fortran code on platform 'nt'
D:\programs\Continuum\anaconda3\envs\py39\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Custom 'build_py' does not implement 'get_data_files_without_manifest'.
Please extend command classes from setuptools instead of distutils.
no previously-included directories found matching 'benchmarks\env'
no previously-included directories found matching 'benchmarks\results'
no previously-included directories found matching 'benchmarks\html'
no previously-included directories found matching 'benchmarks\scipy'
no previously-included directories found matching 'scipy\special\tests\data\boost'
no previously-included directories found matching 'scipy\special\tests\data\gsl'
no previously-included directories found matching 'scipy\special\tests\data\local'
no previously-included directories found matching 'doc\build'
no previously-included directories found matching 'doc\source\generated'
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.bak' found anywhere in distribution
warning: no previously-included files matching '*.swp' found anywhere in distribution
warning: no previously-included files matching '*.pyo' found anywhere in distribution
WARN: CCompilerOpt.__init__[1167] : feature 'AVX512_KNL' is disabled, MSVC compiler doesn't support it
WARN: CCompilerOpt.__init__[1167] : feature 'AVX512_KNM' is disabled, MSVC compiler doesn't support it
WARN: CCompilerOpt.generate_dispatch_header[2289] : dispatch header dir build\src.win-amd64-3.9\numpy\distutils\include does not exist, creating it
error: Setup script exited with error: library dfftpack has Fortran sources but no Fortran compiler found
```

**Comment by long-senpai** [comment] 2022-01-14 13:26
@mszhanyi When I install [AlphaPose](https://github.com/MVIG-SJTU/AlphaPose) on Windows, I encountered some errors, And I fixed by change line 124 of `setup.py` as `force_compile = False`

**Comment by mszhanyi** [comment] 2022-01-14 17:13
`force_compile = False` doesn't work in my machine.

**Comment by mszhanyi** [comment] 2022-01-17 03:30
@long-senpai , 
It worked while running the [conversion](https://github.com/LuongTanDat/AlphaPose-Cpp/blob/main/convert_torchscript.py#L37)  in my machine;
```
 d:\dev\AlphaPose>python ..\testalpha.py --cfg configs/coco/resnet/256x192_res50_lr1e-3_1x-simple.yaml --pth ..\file\simple_res50_256x192.pth
1.10.1
Downloading: "https://download.pytorch.org/models/resnet50-0676ba61.pth" to C:\Users\zhanyi/.cache\torch\hub\checkpoints\resnet50-0676ba61.pth
100%|█████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:01<00:00, 54.7MB/s]
```

**Comment by mszhanyi** [comment] 2022-01-17 04:58
It's my C++ script, it works.
```
#include <torch/torch.h>
#include <torch/script.h>
#include <iostream>

int main() {
  if (torch::cuda::is_available()) {
	  std::cout << "CUDA is available! Training on GPU" << std::endl;
	  torch::jit::load("D:\\dev\\file\\simple_res50_256x192.jit", torch::kCUDA);
	  std::cout << "model is loaded" << std::endl;
  }
  else
  {
	  std::cout << "CUDA is not available! Training on CPU" << std::endl;
  }

  std::cin.get();
}
```

**Comment by long-senpai** [comment] 2022-01-17 05:19
- This is the code I convert to jit: https://github.com/LuongTanDat/AlphaPose-Cpp/blob/main/convert_torchscript.py
- And this is the code I used to load model: https://github.com/LuongTanDat/AlphaPose-Cpp/blob/main/AlphaPose.cpp#L8

**Comment by mszhanyi** [comment] 2022-01-17 06:03
Your model works too in my PC. Could you try using my (VS extension for libtorch)[https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001] to create a simple libtorch project to verify your model too?
![image](https://user-images.githubusercontent.com/16190118/149715844-d3a64568-400a-46d1-8e80-a0dbe9575830.png)

**Comment by mszhanyi** [comment] 2022-01-20 11:12
@long-senpai 
any progress?
It looks not a JIT issue. 
I'll close it next week.

**Comment by long-senpai** [comment] 2022-01-24 08:19
@mszhanyi It maybe I got error when install libtorch on windows
- I download this libtorch version https://download.pytorch.org/libtorch/cu113/libtorch-win-shared-with-deps-1.10.1%2Bcu113.zip for CUDA 11.3 installed on my PC.
- But when I check by `torch::cuda::is_available()` returned result  was `false`.
- Do you know what I am missing when install libtorch on Windows

**Comment by mszhanyi** [comment] 2022-01-24 10:44
Generally python version works, the C++ version(libtorch) should work too.

1. If python version doesn't work, please check if there's gpu card or cuda issue.
2. If python version works, please check the difference between your downloads libtorch and the C++ binaries in pytorch.
    `python -c 'import torch;print(torch.utils.cmake_prefix_path)'`

**Comment by long-senpai** [comment] 2022-01-27 03:03
@mszhanyi pytorch in python I installed with anaconda, that version still return `True` when i run `torch.cuda.is_available()`.
```
>>> print(torch.utils.cmake_prefix_path)
C:\Users\datlt\anaconda3\lib\site-packages\torch\share\cmake
```

- I have not ever run pytorch from libtorch i downloaded, and I think my python doesn't have any link to C++ binaries in libtorch downloaded
.

**Comment by mszhanyi** [comment] 2022-01-27 05:31
Could you please checkout https://pytorch.org/cppdocs/installing.html

```
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..
cmake --build . --config Release
```
check the result if  `/absolute/path/to/libtorch ` is `torch.utils.cmake_prefix_path` or your downloads path

**Comment by long-senpai** [comment] 2022-01-28 09:46
mkdir build
cd build
cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..
cmake --build . --config Release

**Comment by long-senpai** [comment] 2022-01-28 10:10
I create small C++ script with below content:
```Cpp
#include <torch/torch.h>
#include <iostream>

int main() {
    if (torch::cuda::is_available())
        std::cout << "[ LOG ] GPU is available" << std::endl;
    else
        std::cout << "[ LOG ] GPU is NOT available" << std::endl;
    torch::Tensor tensor = torch::rand({2, 3});
    std::cout << tensor << std::endl;
}
```

- `CmakeLists.txt`

```
cmake_minimum_required(VERSION 3.0 FATAL_ERROR)
project(example-app)

find_package(Torch REQUIRED)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS}")

add_executable(example-app main.cpp)
target_link_libraries(example-app "${TORCH_LIBRARIES}")
set_property(TARGET example-app PROPERTY CXX_STANDARD 14)

# The following code block is suggested to be used on Windows.
# According to https://github.com/pytorch/pytorch/issues/25457,
# the DLLs need to be copied to avoid memory errors.
if (MSVC)
  file(GLOB TORCH_DLLS "${TORCH_INSTALL_PREFIX}/lib/*.dll")
  add_custom_command(TARGET example-app
                     POST_BUILD
                     COMMAND ${CMAKE_COMMAND} -E copy_if_different
                     ${TORCH_DLLS}
                     $<TARGET_FILE_DIR:example-app>)
endif (MSVC)
```

- And then I run cmake command (I copied downdoaded libtorch folder to `C:\Program Files (x86)\Torch`)
```
cmake -DCMAKE_PREFIX_PATH="C:\Program Files (x86)\Torch" ..
```

 but I got error, and I don't know why Cmake ask `D:\gitlab\NVTX/include` directory:

```
D:\gitlab\EMoi\build>cmake -DCMAKE_PREFIX_PATH="C:\Program Files (x86)\Torch" ..
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.19043.
-- Caffe2: CUDA detected: 11.3
-- Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3/bin/nvcc.exe
-- Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3
-- Caffe2: Header version is: 11.3
-- Found cuDNN: v8.2.1  (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3/lib/x64/cudnn.lib)
-- C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3/lib/x64/nvrtc.lib shorthash is c7f1618d
-- Autodetected CUDA architecture(s):  7.5
-- Added CUDA NVCC flags for: -gencode;arch=compute_75,code=sm_75
CMake Warning (dev) at C:/Program Files (x86)/Torch/share/cmake/Caffe2/public/cuda.cmake:467 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  C:/Program Files (x86)/Torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  C:/Program Files (x86)/Torch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at C:/Program Files (x86)/Torch/share/cmake/Torch/TorchConfig.cmake:166 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "MSVC" will no longer be dereferenced when the policy
  is set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  CMakeLists.txt:4 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring done
CMake Error in CMakeLists.txt:
  Imported target "torch" includes non-existent path

    "D:\gitlab\NVTX/include"

  in its INTERFACE_INCLUDE_DIRECTORIES.  Possible reasons include:

  * The path was deleted, renamed, or moved to another location.

  * An install or uninstall procedure did not complete successfully.

  * The installation package was faulty and references files it does not
  provide.
```

**Comment by mszhanyi** [comment] 2022-01-28 12:20
```
Build with CUDA

NVTX is needed to build Pytorch with CUDA. NVTX is a part of CUDA distributive, where it is called "Nsight Compute". To install it onto already installed CUDA run CUDA installation once again and check the corresponding checkbox. Make sure that CUDA with Nsight Compute is installed after Visual Studio.
```
from https://github.com/pytorch/pytorch/blob/master/README.md

**Comment by long-senpai** [comment] 2022-02-07 03:58
Sorry for the late reply. I reinstalled CUDA. And now, the sample app, which pytorch check Cuda is available, the program returned `True` with `torch::cuda::is_available()`. But the project in visual studio still cannot find the GPU device

**Comment by mszhanyi** [comment] 2022-02-07 14:57
I couldn't reproduce your issue. 
For `cmake -DCMAKE_PREFIX_PATH=/absolute/path/to/libtorch ..`
If both `your downloads binaries path` and `torch.utils.cmake_prefix_path `worked with cmake, could you please share the 2 *.vcxproject files to me at your convenience. (one is generated by the VS extension, another is generated by CMake).

Anyway, It's not a jit issue any more. I think we could close the issue. For `torch::cuda::is_available()` in VS , we could open a new one.

**Closed** 2022-02-10 06:36 UTC
Labels: oncall: jit, module: windows
