### ISSUE TITLE
[RFC] Distributed Pipeline Parallelism

### ISSUE THREAD

**Issue by mrzzd** [pytorch/pytorch#55256] opened 2021-04-02 21:31 UTC
## 🚀 Feature

Extend Pipeline API to support

* Multi-process/multi-host setting
* More flexible connections between layers.
* Automatic placement of layers

## Terminology

* A *layer* is a single module in the model that has to be placed entirely on a single device. So if a part of the module is sharded, a layer here refers to individual shards (or parts of individual shard)
* A *partition* is a group of layers that are put together into a single device and scheduled atomically by pipeline implementation.

## Overview

With this proposal a pipeline model is authored in following steps

* The user provides description of each layer in the model (in the form of module class and constructor parameters). Additional metadata may also be required (e.g. for automatic placement). The user also provides information how different layers are connected to each other. In the simplest form, layers have single input/output and are connected sequentially.
* The user assigns layers to different devices (local or remote). Assignment could be done manually by user or by using provided helper utilities.
* A pipeline scheduler class takes in these information and runs the module efficiently.

### Layers Definition

We would like to use existing [RemoteModule](https://github.com/pytorch/pytorch/blob/61914cb2fabea02016e5f3357051ae407dcc3070/torch/distributed/nn/api/remote_module.py#L335) implementation to let user describe individual layers in the model.

```
linear_layer_1 = RemoteModule("worker1/cuda:0", nn.Linear, (4, 10), {}), 
rlu_layer = RemoteModule("worker1/cuda:0", nn.ReLU, (), {})]
linear_layer_2 = RemoteModule("worker2/cuda:1", nn.Linear, (10, 1000), {}), 
```

In order to allow separation of layers description and placement, we need to extend RemoteModule to allow for deferred placement:

```
layers = [
  RemoteModule(None, nn.Linear, (4, 10), {}), 
  RemoteModule(None, nn.ReLU, (), {})]
  RemoteModule(None, nn.Linear, (10, 1000), {})
]  

sequential_placement(layers, ["worker1/cuda:0", "worker2/cuda:1"], balance=[2, 1])
```

### Connections

We provide API for user to define connections between layers. This let’s user to cover various scenarios, to name some:

* a simple sequence of layers where each layer feeds its output to the next layer in sequence
* skip connections
* sharded modules, as an example:
![Screenshot from 2021-04-02 14-01-35](https://user-images.githubusercontent.com/63922063/113455541-b9ca1f80-93bf-11eb-8513-46ee3087f87a.png)

The API is in the form of a class `PipelineModulesGraph`  that is instantiated by the user

```

class PipelineModulesGraph(nn.Module):
    def add_sequence(self, modules: List[RemoteModule]) -> None:
        ...
    def add_multi_input_layer(self,
                              module: RemoteModule,
                              inputs: List[RemoteModule]) -> None:
        ...
                            
    def feed_model_input(self, module: RemoteModule) -> None:
        ....
       
```

A graph defined this way is a module can run layers on given input (but not in an efficient way).

### DistributedPipeline

DistributedPipeline is a wrapper module around PipelineModulesGraph that can run the underlaying pipeline-module-graph with pipelining technique. The API is similar to existing [Pipe](https://github.com/pytorch/pytorch/blob/61914cb2fabea02016e5f3357051ae407dcc3070/torch/distributed/pipeline/sync/pipe.py#L138) class, with the difference that the constructor accepts an instance of the more general PipelineModulesGraph class instead of nn.Sequential.

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment] 2021-04-02 23:24
> In order to allow separation of layers description and placement, we need to extend RemoteModule to allow for deferred placement

What is the reason we need deferred placement? 

> DistributedPipeline is a wrapper module around PipelineModulesGraph that can run the underlaying pipeline-module-graph with pipelining technique. The API is similar to existing Pipe class, with the difference that the constructor accepts an instance of the more general PipelineModulesGraph class instead of nn.Sequential.

I'm trying to understand why we need PipelineModulesGraph and why can't we express everything as nn.Sequential? In case of sharded layer, can't we still express this as an nn.Sequential and the shardedlayer itself is responsible to shard its input across multiple devices? I feel it is much simpler if Pipe just accepts an nn.Sequential and doesn't have to worry about  a graph of execution. Can't we move the sharding logic into individual modules?

**Comment by mrzzd** [comment] 2021-04-05 19:08
> > In order to allow separation of layers description and placement, we need to extend RemoteModule to allow for deferred placement
> 
> What is the reason we need deferred placement?
> 
That will enable the user to first have a description of model in form of a set of remote-modules (without device assignment), and creates graph of data connections between them, and then separately the user can do device assignment. As an example please see how instantiate function is used [here](https://github.com/facebookresearch/fairscale/pull/567/files#diff-2b737cf9b42bd10c2b5f83b2d8d99e4f18fb606233d2f72108c9c31587aa7708R533).

> > DistributedPipeline is a wrapper module around PipelineModulesGraph that can run the underlaying pipeline-module-graph with pipelining technique. The API is similar to existing Pipe class, with the difference that the constructor accepts an instance of the more general PipelineModulesGraph class instead of nn.Sequential.
> 
> I'm trying to understand why we need PipelineModulesGraph and why can't we express everything as nn.Sequential? In case of sharded layer, can't we still express this as an nn.Sequential and the shardedlayer itself is responsible to shard its input across multiple devices? I feel it is much simpler if Pipe just accepts an nn.Sequential and doesn't have to worry about a graph of execution. Can't we move the sharding logic into individual modules?

nn.Sequential case is still supported with a could of lines (which could be a simple helper function). This helps support more complex situation like skip connections, sharded layers, etc. For the sharding case, I believe integrated pipeline implementation can handle data movements more efficiently that a separate sharding on top of pipeline. Please note the API we define here is a relatively low level API. A sharding library can use this API to provide a higer level more convenient API for user.

**Comment by pritamdamania87** [comment] 2021-04-06 22:08
> That will enable the user to first have a description of model in form of a set of remote-modules (without device assignment), and creates graph of data connections between them, and then separately the user can do device assignment. As an example please see how instantiate function is used here.

The link above is not working for me (probably because github is not rendering large diff of certain files). But are you referring to the `create_sequence_pipeline` part? I do see we are first defining the pipeline and then placing the modules on the devices, but I'm wondering if there is any real need to do it? Why don't we create an `nn.Sequential` with all modules placed on appropriate devices? Also, I'm not sure if a RemoteModule with deferred placement makes sense. A RemoteModule with no device associated, just says this module is remote but provides no other value in terms of describing what this model actually looks like. I do feel that a RemoteModule should always point to a concrete module that you can execute. Overall I feel the deferred placement idea is a good idea for PyTorch in general but should be addressed via things like virtual device instead (some discussion on virtual device can be found here: https://github.com/pytorch/pytorch/issues/55207).


> nn.Sequential case is still supported with a couple of lines (which could be a simple helper function). This helps support more complex situation like skip connections, sharded layers, etc. For the sharding case, I believe integrated pipeline implementation can handle data movements more efficiently than a separate sharding on top of pipeline. Please note the API we define here is a relatively low level API and does not have any logic specific to sharding. A sharding library can use this API to provide a higher level more convenient API for user.

I guess the part I'm confused about is that if you provide an API where the user can express a graph, its no longer necessarily pipelining right? Pipelining is usually when you have a set of sequential ops and you pipeline those, thats why something like `nn.Sequential` fits well for describing a pipeline. For the example image in your RFC, LinearLayerSharded1, LinearLayerSharded2 and the two RELU layers could just be wrapped into a single module called `ShardedLinear` and then your pipeline is `Embedding->Split->ShardedLinear->Concatenate`. It's already possible to do skip connections in the current design of pipeline and sharded layers should be possible by incorporating them into a single module? The tricky thing with sharded layers is that they have more than one device and current pipelining allows a module to be only on a single device, but I think this can be fixed by other means instead of having a graph representation. For example, you could tag a module in the pipeline as being "multi-device" and define its input and output devices so that you can synchronize cuda streams appropriately in the pipeline.

**Comment by mrshenli** [comment] 2021-04-09 17:20
> DistributedPipeline is a wrapper module around PipelineModulesGraph that can run the underlaying pipeline-module-graph with pipelining technique. The API is similar to existing Pipe class, with the difference that the constructor accepts an instance of the more general PipelineModulesGraph class instead of nn.Sequential.

I would like to follow up on our offline discussions regarding consolidating `DistributedPipeline` and `Pipeline`. Would I be correct if I assume that launching RPC processes is orthoganal to the Pipeline API design? Looks like the same API can work for both single-process multi-GPU and single-process single-GPU use cases?

```python
# single-process multi-GPU
init_rpc("worker0", rank=0, world_size=1)

layers = nn.Sequential(
    RemoteModule("worker0/cuda:0", nn.Linear, (4, 10), {}), 
    RemoteModule("worker0/cuda:1", nn.ReLU, (), {})]
    RemoteModule("worker0/cuda:2", nn.Linear, (10, 1000), {}), 
)

Pipeline(layers)
```

```python
# single-process single-GPU

# on all workers
init_rpc(f"worker{rank}", rank=rank, world_size=3)

# on worker0
layers = nn.Sequential(
    RemoteModule("worker0/cuda:0", nn.Linear, (4, 10), {}), 
    RemoteModule("worker1/cuda:0", nn.ReLU, (), {})]
    RemoteModule("worker2/cuda:0", nn.Linear, (10, 1000), {}), 
)

Pipeline(layers)
```

**Comment by pritamdamania87** [comment] 2021-04-19 23:18
@mrshenli I think we should strive for that goal, but I guess the proposal here is to use PipelineModulesGraph everywhere instead of `nn.Sequential`.

**Comment by pritamdamania87** [comment] 2021-04-19 23:54
I was wondering if the following long term idea would make sense (needs a lot of things to land for this to work). The API would just accept an `nn.Module` and not a custom `PipelineModulesGraph`. The steps would be as follows:

1. First the user would initialize the module using the virtual device concept mentioned in https://github.com/pytorch/pytorch/issues/55207. Or they could just directly initialize a custom nn.Module on a set of devices (using RemoteModule).
2. Then the user would place the appropriate submodules on different devices using `.to()`. We need `.to()` to support remote device for this.
3. This `nn.Module` is then passed the Pipe API, where we now trace it using `torch.fx` to retrieve a graph. For this step, we need `torch.fx` to understand `RemoteModule` and handle it appropriately.
4. Finally this graph is fed into the graph executor built by @mrzzd in https://github.com/facebookresearch/fairscale/pull/567.

A simple example:

```
class MyModel(nn.Module):
   def __init__(self, device, init_parameters):
        self.fc1 = nn.Linear(10, 10, device, init_parameters)
        self.fc2 = nn.Linear(10, 10, device, init_parameters)
        self.fc3 = nn.Linear(10, 10, device, init_parameters)
   
    def forward(self, inp):
        return self.fc3(self.fc2(self.fc1(inp)))

mod = MyModel(device="meta", init_parameters=False)
mod.fc1.to("rank:0/cuda:0")
mod.fc2.to("rank:1/cuda:1")
mod.fc3.to("rank:2/cuda:2")

pipe = DistributedPipeline(mod)
```

This API naturally extends to automatic device placement as well where the user can just provide a model on virtual device and let the Pipe API figure out placement:

```
mod = MyModel(device="meta", init_parameters=False)
pipe = DistributedPipeline(mod, devices=....) # provide a list of devices to use for automatic placement.
```

**Comment by mrzzd** [comment] 2021-04-20 15:31
>I'm not sure if a RemoteModule with deferred placement makes sense. A RemoteModule with no device associated, just says this module is remote but provides no other value in terms of describing what this model actually looks like. I do feel that a RemoteModule should always point to a concrete module that you can execute. Overall I feel the deferred placement idea is a good idea for PyTorch in general but should be addressed via things like virtual device instead (some discussion on virtual device can be found here: #55207).
> 
Well, we could have  "materialized" and "non-materialized" stages for Remote Module. A non-materialized Remote-Module has all information for creating and initializing a module, but it's not materialized because placement information is not provided yet.  Honestly I  prefer that kind of API over virtual-device for reasons that we can discuss separately. 
Since this was not required for the purpose of our goal here, I dropped this part from my implementation.


> I guess the part I'm confused about is that if you provide an API where the user can express a graph, its no longer necessarily pipelining right? Pipelining is usually when you have a set of sequential ops and you pipeline those, thats why something like `nn.Sequential` fits well for describing a pipeline. For the example image in your RFC, LinearLayerSharded1, LinearLayerSharded2 and the two RELU layers could just be wrapped into a single module called `ShardedLinear` and then your pipeline is `Embedding->Split->ShardedLinear->Concatenate`. It's already possible to do skip connections in the current design of pipeline and sharded layers should be possible by incorporating them into a single module? The tricky thing with sharded layers is that they have more than one device and current pipelining allows a module to be only on a single device, but I think this can be fixed by other means instead of having a graph representation. For example, you could tag a module in the pipeline as being "multi-device" and define its input and output devices so that you can synchronize cuda streams appropriately in the pipeline.

Well, we have a generalized version of pipelining that works on DAGs instead of sequential, and it covers more topologies.
As discussed offline, this provides an alternative approach for providing sharded layers. It let's user create its custom sharding approach without worrying about moving data between devices.

**Comment by mrzzd** [comment] 2021-04-20 15:36
> I would like to follow up on our offline discussions regarding consolidating `DistributedPipeline` and `Pipeline`. Would I be correct if I assume that launching RPC processes is orthoganal to the Pipeline API design? Looks like the same API can work for both single-process multi-GPU and single-process single-GPU use cases?
> 
> ```python
> # single-process multi-GPU
> init_rpc("worker0", rank=0, world_size=1)
> 
> layers = nn.Sequential(
>     RemoteModule("worker0/cuda:0", nn.Linear, (4, 10), {}), 
>     RemoteModule("worker0/cuda:1", nn.ReLU, (), {})]
>     RemoteModule("worker0/cuda:2", nn.Linear, (10, 1000), {}), 
> )
> 
> Pipeline(layers)
> ```
> 
> ```python
> # single-process single-GPU
> 
> # on all workers
> init_rpc(f"worker{rank}", rank=rank, world_size=3)
> 
> # on worker0
> layers = nn.Sequential(
>     RemoteModule("worker0/cuda:0", nn.Linear, (4, 10), {}), 
>     RemoteModule("worker1/cuda:0", nn.ReLU, (), {})]
>     RemoteModule("worker2/cuda:0", nn.Linear, (10, 1000), {}), 
> )
> 
> Pipeline(layers)
> ```

Yes, I think the same API works for both cases. Ideally we should need one RPC worker per host.

**Comment by mrzzd** [comment] 2021-04-20 15:56
> I was wondering if the following long term idea would make sense (needs a lot of things to land for this to work). The API would just accept an `nn.Module` and not a custom `PipelineModulesGraph`. The steps would be as follows:
> 
> 1. First the user would initialize the module using the virtual device concept mentioned in #55207. Or they could just directly initialize a custom nn.Module on a set of devices (using RemoteModule).
> 2. Then the user would place the appropriate submodules on different devices using `.to()`. We need `.to()` to support remote device for this.
> 3. This `nn.Module` is then passed the Pipe API, where we now trace it using `torch.fx` to retrieve a graph. For this step, we need `torch.fx` to understand `RemoteModule` and handle it appropriately.
> 4. Finally this graph is fed into the graph executor built by @mrzzd in [facebookresearch/fairscale#567](https://github.com/facebookresearch/fairscale/pull/567).
> 
> A simple example:
> 
> ```
> class MyModel(nn.Module):
>    def __init__(self, device, init_parameters):
>         self.fc1 = nn.Linear(10, 10, device, init_parameters)
>         self.fc2 = nn.Linear(10, 10, device, init_parameters)
>         self.fc3 = nn.Linear(10, 10, device, init_parameters)
>    
>     def forward(self, inp):
>         return self.fc3(self.fc2(self.fc1(inp)))
> 
> mod = MyModel(device="meta", init_parameters=False)
> mod.fc1.to("rank:0/cuda:0")
> mod.fc2.to("rank:1/cuda:1")
> mod.fc3.to("rank:2/cuda:2")
> 
> pipe = DistributedPipeline(mod)
> ```
> 
> This API naturally extends to automatic device placement as well where the user can just provide a model on virtual device and let the Pipe API figure out placement:
> 
> ```
> mod = MyModel(device="meta", init_parameters=False)
> pipe = DistributedPipeline(mod, devices=....) # provide a list of devices to use for automatic placement.
> ```

How about separating DistributedPipeline from device placement:
```
mod = MyModel(device="meta", init_parameters=False)
utils.auto_placement(mod, devices=...)
pipe = DistributedPipeline(mod)
```

For now the input to the pipe is DistributedPipeline could to be a module with a number of RemoteModules as submodule. The sequential module in Shen example [above](https://github.com/pytorch/pytorch/issues/55256#issuecomment-816833122)  is an example. For a non-sequential example, see [here](https://github.com/facebookresearch/fairscale/blob/56224d84852d855c5c9afd04bd23a5044ef73513/tests/experimental/nn/test_multiprocess_pipe.py#L292)

**Comment by pritamdamania87** [comment] 2021-04-20 18:14
> How about separating DistributedPipeline from device placement:

I guess the placement needs to be tied to distributed pipeline though right? The device placement might not be agnostic to the model parallel strategy and you probably might have different device placement for pipeline parallelism compared to another strategy. If you meant `utils.auto_placement` is just a helper library in the pipeline package, that makes sense.

**Comment by pritamdamania87** [comment] 2021-04-29 23:22
@mrzzd I was wondering if we can build out the distributed pipeline support in incremental steps providing additional value to the user as we go:

1. For the first step, we keep the API the same and only support an `nn.Sequential` but add support for pipelining across process/hosts.
2. As a second step, we modify the API to accept a generic `nn.Module` provided by the user which they have manually partitioned and placed on the right devices. This way we can trace the graph using fx and use the existing graph executor in https://github.com/facebookresearch/fairscale/pull/567.
3. The final step would be @wanchaol's work where the user just provides an `nn.Module` on virtual device and the Pipe API figures out what is the best placement based on the available devices.

**Comment by mrzzd** [comment] 2021-04-30 15:07
@pritamdamania87 Thanks for proposal. I feel it makes a bit more sense to merge steps 1 and 2. Otherwise some complexities comes to my mind that need to deal with.
-- For step 1, modules in Sequential should be all remote-modules, right? Otherwise, we will  have incompatible API changes from step 1 to 2.
 -- In step 1 we want support for pipelining across hosts, but graph executor is used in step 2. Does it mean we will need a new implementation for step 1? That seems unnecessary work.
-- How about support for skip connections in step 1? In step 2, we do not support current syntax for skip connections. We keep that for step 1? In either case there are some questions around api and implementation for them.

**Comment by pritamdamania87** [comment] 2021-04-30 19:12
> -- For step 1, modules in Sequential should be all remote-modules, right? Otherwise, we will have incompatible API changes from step 1 to 2.

I think we can have RemoteModule in nn.Sequential without any incompatible API changes right? RemoteModule is just a type of nn.Module and can be part of nn.Sequential?

> -- In step 1 we want support for pipelining across hosts, but graph executor is used in step 2. Does it mean we will need a new implementation for step 1? That seems unnecessary work.

This is a good point, I think we can actually use the same graph executor in step 1 since nn.Sequential is just a special case of graph. So we keep the API same in step 1, but under the hood use the graph executor. I think one important thing to keep in mind here is that we should definitely benchmark the graph executor on multiple workloads to ensure we don't have any regressions compared to the current executor.

> How about support for skip connections in step 1? In step 2, we do not support current syntax for skip connections. We keep that for step 1? In either case there are some questions around api and implementation for them.

I think we can have a limitation that skip connection support works only in the single process environment for step 1, then in step 2 when we anyways have a graph we don't need any specific skip connection support.

**Comment by Jack47** [comment] 2022-08-04 01:55
any update on this?

**Comment by wanchaol** [comment] 2022-08-04 02:47
> any update on this?

@Jack47 We ended up with PiPPy for pipeline parallelism, checkout the repo here https://github.com/pytorch/PiPPy

Closing this, feel free to open issues in PiPPy repo directly when trying it out :)

**Closed by wanchaol** 2022-08-04 02:47 UTC
Labels: oncall: distributed, pipeline parallelism
