### ISSUE TITLE
flaky "test_constant_fold_slice_*" tests on "caffe2_onnx_py2_gcc5_ubuntu16_04_test" job

### ISSUE THREAD

**Issue by kostmo** [pytorch/pytorch#30764] opened 2019-12-04 23:26 UTC
## 🐛 Bug

Observed four occurrences of intermittent failures in the `caffe2_onnx_py2_gcc5_ubuntu16_04_test` job on the `master` branch within the last day (December 4, 2019):

* https://circleci.com/gh/pytorch/pytorch/3775754
* https://circleci.com/gh/pytorch/pytorch/3774709
* https://circleci.com/gh/pytorch/pytorch/3773548
* https://circleci.com/gh/pytorch/pytorch/3766154

Highlighted here:
https://dr.pytorch.org/master-timeline.html?min_commit_index=12683&max_commit_index=12711&max_columns_suppress_successful=35&should_suppress_scheduled_builds=true&should_suppress_fully_successful_columns=true&highlight_job=caffe2_onnx_py2_gcc5_ubuntu16_04_test

Example console output:
```
Dec 04 00:35:04 test/onnx/test_utility_funs.py::TestUtilityFuns::test_constant_fold_slice_index_exceeds_dim /var/lib/jenkins/workspace/scripts/onnx/test.sh: line 55: 11464 Segmentation fault (core dumped) pytest "${args[@]}" -k 'not (TestOperators and test_full_like) and not (TestOperators and test_zeros_like) and not (TestOperators and test_ones_like) and not (TestModels and test_vgg16) and not (TestModels and test_vgg16_bn) and not (TestModels and test_vgg19) and not (TestModels and test_vgg19_bn)' --ignore "$top_dir/test/onnx/test_pytorch_onnx_onnxruntime.py" --ignore "$top_dir/test/onnx/test_custom_ops.py" --ignore "$top_dir/test/onnx/test_models_onnxruntime.py" "${test_paths[@]}"
```

cc @ezyang @gchanan @zou3519 @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment] 2019-12-06 18:09
cc @houseroad:
Error is in caffe2_symbolic for Slice:

Dec 04 14:43:21 test/onnx/test_utility_funs.py:112: 
Dec 04 14:43:21 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Dec 04 14:43:21 ../.local/lib/python2.7/site-packages/torch/onnx/utils.py:317: in _model_to_graph
Dec 04 14:43:21     fixed_batch_size=fixed_batch_size, params_dict=params_dict)
Dec 04 14:43:21 ../.local/lib/python2.7/site-packages/torch/onnx/utils.py:135: in _optimize_graph
Dec 04 14:43:21     graph = torch._C._jit_pass_onnx(graph, operator_export_type)
Dec 04 14:43:21 ../.local/lib/python2.7/site-packages/torch/onnx/__init__.py:179: in _run_symbolic_function
Dec 04 14:43:21     return utils._run_symbolic_function(*args, **kwargs)
Dec 04 14:43:21 ../.local/lib/python2.7/site-packages/torch/onnx/utils.py:686: in _run_symbolic_function
Dec 04 14:43:21     return op_fn(g, *inputs, **attrs)
Dec 04 14:43:21 ../.local/lib/python2.7/site-packages/torch/onnx/symbolic_helper.py:129: in wrapper
Dec 04 14:43:21     return fn(g, *args)
Dec 04 14:43:21 ../.local/lib/python2.7/site-packages/torch/onnx/symbolic_caffe2.py:205: in slice
Dec 04 14:43:21     "Y_scale_f": input.node()["Y_scale"],
Dec 04 14:43:21 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Dec 04 14:43:21 
Dec 04 14:43:21 self = <[MemoryError("std::bad_alloc") raised in repr()] SafeRepr object at 0x7fe3896296c8>
Dec 04 14:43:21 k = 'Y_scale'
Dec 04 14:43:21 
Dec 04 14:43:21     def _node_getitem(self, k):
Dec 04 14:43:21         r"""
Dec 04 14:43:21         Accessor for attributes of a node which is polymorphic over
Dec 04 14:43:21         return type.
Dec 04 14:43:21     
Dec 04 14:43:21         NB: This is monkey-patched onto Node.
Dec 04 14:43:21         """
Dec 04 14:43:21 >       sel = self.kindOf(k)
Dec 04 14:43:21 E       RuntimeError: required keyword attribute 'Y_scale' is undefined
Dec 04 14:43:21 
Dec 04 14:43:21 ../.local/lib/python2.7/site-packages/torch/onnx/utils.py:812: RuntimeError

All util tests calling _model_to_graph are set to test ONNX models, not caffe2 quantized models.
Looking at the test arguments, expected export_type is ONNX by default.
I'm unable to reproduce this locally.

**Comment by houseroad** [comment] 2019-12-06 18:14
@supriyar seems related to ONNX->C2 quantization pass, could you please take a look?

**Comment by supriyar** [comment] 2019-12-06 19:22
@kostmo I'm unable to repro this locally so tried to connect to the CI machine, however the docker containers listed on the CI job don't seem valid anymore. Eg. https://circleci.com/gh/pytorch/pytorch/3827886
```
DOCKER_IMAGE: 308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-gcc5-ubuntu16.04:345-a55f125e3bf01aae2687c7d2364181d855b2e08e
Error response from daemon: manifest for 308535385114.dkr.ecr.us-east-1.amazonaws.com/caffe2/py2-gcc5-ubuntu16.04:345-a55f125e3bf01aae2687c7d2364181d855b2e08e not found

Exited with code exit status 1
```
Any idea how I can repro this?

**Comment by ezyang** [comment] 2019-12-08 21:44
@supriyar Since this is a flaky test you're unlikely to repro it by simply running a CI job once. I'd perhaps see if you can repro the flakiness locally running it in a loop, or perhaps just read the code until you find the bug.

**Comment by ezyang** [comment] 2019-12-08 21:45
If you do want to rerun the CI job, just rerun the entire job from scratch by making a new PR.

**Comment by supriyar** [comment] 2019-12-12 22:22
It didn't fail on rerunning. I've been monitoring the task and it doesn't seem to have failed since these reports. 
@kostmo/@ezyang can we close this and re-visit if this shows up again?

**Comment by ezyang** [comment] 2019-12-13 00:11
@kostmo Can you setup a durable query for this test name and check for more recent occurrences?

**Comment by kostmo** [comment] 2020-01-02 20:38
Here are 12 instances of the failure since Dec. 4, with 3 from January 2nd alone:
* https://circleci.com/gh/pytorch/pytorch/3793385
* https://circleci.com/gh/pytorch/pytorch/3803110
* https://circleci.com/gh/pytorch/pytorch/3804410
* https://circleci.com/gh/pytorch/pytorch/3808124
* https://circleci.com/gh/pytorch/pytorch/3808166
* https://circleci.com/gh/pytorch/pytorch/3828006
* https://circleci.com/gh/pytorch/pytorch/4037798
* https://circleci.com/gh/pytorch/pytorch/4039379
* https://circleci.com/gh/pytorch/pytorch/4073178
* https://circleci.com/gh/pytorch/pytorch/4098956 <- today
* https://circleci.com/gh/pytorch/pytorch/4099820 <- today
* https://circleci.com/gh/pytorch/pytorch/4102300 <- today

At the bottom of [this page](https://dr.pytorch.org/pattern-details.html?pattern_id=89), I provide a filter textbox in the "Match" column that allows one to narrow the matches to `test_constant_fold_slice_index_exceeds_dim` specifically.

**Comment by kostmo** [comment] 2020-01-16 21:45
5 more instances so far this week in `master` of this segfault:
* https://circleci.com/gh/pytorch/pytorch/4221427
* https://circleci.com/gh/pytorch/pytorch/4260838
* https://circleci.com/gh/pytorch/pytorch/4225451
* https://circleci.com/gh/pytorch/pytorch/4264005
* https://circleci.com/gh/pytorch/pytorch/4277295

**Comment by mruberry** [comment] 2020-11-08 08:26
This issue appears to be moot (and possibly fixed) since we no longer have this build in CI.

**Closed by mruberry** 2020-11-08 08:26 UTC
Labels: high priority, module: flaky-tests, module: onnx, triaged
