### ISSUE TITLE
[Inductor] [CPU] hf_Longformer performance regression > 10% on 2023-05-28 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#102507] opened 2023-05-30 03:48 UTC
### 🐛 Describe the bug

Performance regression:  **hf_Longformer**  [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1567662304) on 2023-05-28 as bellow:

|  2023-05-28  |   |     |   |  2023-05-25  |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|1.172147	 |0.082288565	|0.096454295	|1	|1.358556	 |0.070512074	|0.095794601	|0.86	|0.99	|0.86

SW information:

SW	| Nightly commit	| Main commit
-- | -- | --
Pytorch|[3dedcb3](https://github.com/pytorch/pytorch/commit/3dedcb3)|[c3ea8cc](https://github.com/pytorch/pytorch/commit/c3ea8cc)
Torchbench|/|[987bbec3](https://github.com/pytorch/benchmark/commit/987bbec3)
torchaudio|[894388d](https://github.com/pytorch/audio/commit/894388d)|[72d3fe0](https://github.com/pytorch/audio/commit/72d3fe0)
torchtext|[3cf1db6](https://github.com/pytorch/text/commit/3cf1db6)| [0dc07eb](https://github.com/pytorch/text/commit/0dc07eb)
torchvision|[50fb988](https://github.com/pytorch/vision/commit/50fb988)|[abc40ef](https://github.com/pytorch/vision/commit/abc40ef)
torchdata|[a754743](https://github.com/pytorch/data/commit/a754743)|[ba31745](https://github.com/pytorch/data/commit/ba31745)
dynamo_benchmarks|[174d01b](https://github.com/pytorch/pytorch/commit/174d01b)|/

graph:
2023_05_28
[graph.txt](https://github.com/pytorch/pytorch/files/11595496/graph.txt)

2023_05_25
[graph.txt](https://github.com/pytorch/pytorch/files/11595499/graph.txt)

### Versions

repro:

```bash
python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --inference --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only hf_Longformer  --cold_start_latency

```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @ngimel

**Comment by blzheng** [comment] 2023-05-31 01:06
This performance regression is caused by #102068 cc @XiaobingSuper

**Comment by XiaobingSuper** [comment] 2023-05-31 07:32
Before: for integer div_floor, we directly return the div number by ```/``` which nor consider the rem number when two input has a different sign, but https://github.com/pytorch/pytorch/pull/102068 consider this case:
```
inline scalar_t div_floor_integer(scalar_t a, scalar_t b) {
  if (c10::signs_differ(a, b)) {
    // Subtracts one from the results of truncation division if the
    // divisor and dividend have different sign(bit)s and the remainder of
    // the division is nonzero
    const auto quot = a / b;
    const auto rem = a % b;
    return rem ? quot - 1 : quot;
  }
  return a / b;
}
```
which introduces ```%```, it is slow for an integer that introduces this regression, we need to check whether we can avoid using ```%``` for better performance.

**Comment by lezcano** [comment] 2023-05-31 08:40
Note that, at least condeptually, `rem == a - b * quot` (modulo some sign considerations that you'll need to adjust) so you should be able to get rid of that that mod.

**Comment by leslie-fang-intel** [comment] 2023-12-21 09:10
@blzheng please help to follow up.

**Comment by blzheng** [comment] 2023-12-21 09:13
According to this report ( https://github.com/pytorch/pytorch/issues/93531#issuecomment-1846297537), the speedup is 1.41x now, which is better than the speedup (1.358x) of 2023-05-25.
I tried replacing a%b with a-b*quot, performance has no change.

**Comment by leslie-fang-intel** [comment] 2024-01-04 07:55
Since it's expected to fix a correctness issue, we will close this now.

**Closed by leslie-fang-intel** 2024-01-04 07:55 UTC
Labels: triaged, oncall: pt2, oncall: cpu inductor
