### ISSUE TITLE
Unexpected behavior when using MPS (M1)

### ISSUE THREAD

**Issue by murundb** [pytorch/pytorch#86153] opened 2022-10-03 20:33 UTC
### 🐛 Describe the bug

Setting tensor values by index doesn't seem to be working correctly when the tensors are on MPS. Example:

    input = torch.randn(128, 10)
    mps_dev = torch.device("mps")
    input = input.to(device=mps_dev)

    
    N, C = input.shape

    target = torch.randint(0, C, (N,))
    target = target.to(device=mps_dev)

    z = torch.zeros(input.shape)

    for n in range(N):
        for c in range(C):
            if (c == target[n]):
                z[n, c] = input[n, c]
            else:
                z[n, c] = -1 * input[n, c]

Here, only the very first element of `z` gets updated and spits out an error after few loops:

`dst_tensor_nbytes >= (dst.storage_offset() * dst.element_size()) INTERNAL ASSERT FAILED at "/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1664781123540/work/aten/src/ATen/native/mps/operations/Copy.mm":159, please report a bug to PyTorch. `

### Versions

```
PyTorch version: 1.13.0.dev20221003
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.5.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.13 (main, Aug 25 2022, 18:24:45)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.5.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.1
[pip3] torch==1.13.0.dev20221003
[pip3] torchvision==0.14.0.dev20221003
[conda] numpy                     1.23.1           py39h42add53_0
[conda] numpy-base                1.23.1           py39hadd41eb_0
[conda] pytorch                   1.13.0.dev20221003         py3.9_0    pytorch-nightly
[conda] torchvision               0.14.0.dev20221003        py39_cpu    pytorch-nightly
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment] 2022-10-03 22:04
Thank you very much for reporting. Looks like a duplicate of https://github.com/pytorch/pytorch/issues/86152

**Comment by malfet** [comment] 2022-10-04 02:05
Sorry, this is something quite different than the previous issue and sounds like a very simple wrong assert in place, which reproduces by something like the following:
```
% python -c "import torch;x=torch.empty(10);y=torch.tensor([10], device='mps');x[2]=y[0]"  
torch.Size([10])
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: dst_tensor_nbytes >= (dst.storage_offset() * dst.element_size()) INTERNAL ASSERT FAILED at "../aten/src/ATen/native/mps/operations/Copy.mm":159, please report a bug to PyTorch. 

```

**Closed** 2022-10-04 19:02 UTC
Labels: triaged, module: mps
