### ISSUE TITLE
Conversion of finetuned resnet50 (pytorch) to onnx (not the same results)

### ISSUE THREAD

**Issue by AyaNasser96** [pytorch/pytorch#80133] opened 2022-06-23 11:55 UTC
### 🐛 Describe the bug

The problem is when I convert the pytorch model (finetuned resnet50) to onnx the results of the pytorch inference and onnx inference are not the same, the detected class is the same in most cases but the difference in the confidence is huge at some pics that could reach 30%!!

It's not a consatn drop number in confidence, no at some img inference the drop is 2% and other could reach to 30% !!

I will provide the code for pytorch and onnx inference, but the model could be sent via mail

#####
also when I use the same model and the same code with the same environment but on another laptop that consist of different PCU And GPU the pytorch model gives a slightly difference results (not a complete difference but there's still a difference)

### Pytroch inference code

```python

def get_s_predictions(model, x):
    model.eval()
    with torch.no_grad():
        x = x.to(device)
        y_pred = model(x)
        y_prob = F.softmax(y_pred, dim=-1)
        top_pred = y_prob.argmax(1, keepdim=True)
        print("[Pytorch] prob list: ", y_prob)

    return top_pred

def infer_with_pytorch(img_path, pytorch_model):
    # Load the models:
    model = ResNet(config.resnet50_config, config.OUTPUT_DIM)
    model.load_state_dict(torch.load(pytorch_model))

    test_transforms = transforms.Compose([
        transforms.Resize(pretrained_size),
        transforms.CenterCrop(pretrained_size),
        transforms.ToTensor(),
        transforms.Normalize(mean=pretrained_means,
                             std=pretrained_stds)
    ])

    img = Image.open(img_path)
    img_t = test_transforms(img)
    img_tensor = torch.unsqueeze(img_t, 0)
    vtype_class = str(classes[get_s_predictions(model, img_tensor)])
    return vtype_class
```

### ONNX inference code:
```python

def infer_with_onnx(img_path, onnx_model):
    ort_session = onnxruntime.InferenceSession(onnx_model)
    def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    img = Image.open(img_path)
    resize = transforms.Resize([224, 224])
    img = resize(img)

    to_tensor = transforms.ToTensor()
    img = to_tensor(img)

    normalize = transforms.Normalize(mean=pretrained_means, std=pretrained_stds)
    img = normalize(img)
    img.unsqueeze_(0)

    ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(img)}
    ort_outs = ort_session.run(None, ort_inputs)
    out_y = ort_outs[0]
    print("[ONNX] onnx prob: ", out_y)
    e_x = np.exp(out_y - np.max(out_y))
    new_list = e_x / e_x.sum()  # only difference
    print("[ONNX] new list: ", new_list)
    detected_class = str(classes[out_y.argmax(axis=1)[0]])
    print("[ONNX] predicted class: ", detected_class)
    return detected_class

```

The conversion code is:

```python
import torch
import onnx
from model import ResNet
import config

# define model and load weights 
model = ResNet(config.resnet50_config, config.OUTPUT_DIM)
model.load_state_dict(torch.load('Models/resnet-model-erasing.pt'))

device = 'cpu'
model = model.to(device)

# export model to ONNX
dummy_input = torch.autograd.Variable(torch.randn(1, 3, 224, 224))

input_names = ["data"]
output_names = ["output"]
torch.onnx.export(model,
                  dummy_input.to(device),
                  'new_onnx/resnet-erasing.onnx',
                  input_names=input_names,
                  output_names=output_names,
                  opset_version=11)

# check created model
onnx_model = onnx.load('new_onnx/resnet-erasing.onnx')
onnx.checker.check_model(onnx_model)

```

you'll find the model.py and config.py at this link 
https://drive.google.com/drive/folders/1jUdvMaDi5pg8K4tl_lyB5NqJlOZeMEWW?usp=sharing

### Versions

Note: I ran the above code with CPU because when I use cuda it gives me the following error
![image](https://user-images.githubusercontent.com/98317981/175291615-342d2e34-25fb-4c08-ae29-13661e1814e6.png)

" RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same "

### My Machine:
GPU:  NVIDIA Corporation / NVIDIA GeForce RTX 3050 Ti Laptop GPU/PCIe/SSE2

Processor: 11th Gen Intel® Core™ i7-11370H @ 3.30GHz × 8 

**The requirements file:**

> matplotlib==3.5.1
> onnx==1.10.2
> scikit_learn==1.1.1
> torch==1.11.0
> torchvision==0.12.0

**Comment by AyaNasser96** [comment] 2022-06-26 09:26
@jbschlosser anyone could help soon ?

**Comment by jbschlosser** [comment] 2022-06-27 14:54
@AyaNasser96 Unfortunately, I'm not knowledgeable about ONNX - I was just applying the label for triage purposes. If no one answers here, maybe you'll get more help on the [PyTorch forums](https://discuss.pytorch.org/)?

Note that we don't guarantee 100% numerical consistency across devices or between PyTorch and ONNX, so there may be nothing we can do on our end.

**Comment by AllenTiTaiWang** [comment] 2022-06-27 19:01
Hi @AyaNasser96,

Could you please upload your model here if it's < 2GB, and it's not, could you upload to Cloud so that we would be able to reproduce it. 

I had a quick scan on the question, and found this CI test case under onnx which you might be interested (not ResNet though):
https://github.com/pytorch/pytorch/blob/471c8330432c64b41dab7483be2f1f234efe5ef3/test/onnx/test_pytorch_onnx_onnxruntime.py#L399-L420

Given that ResNet50 is a pretty common model, I figure that exporter might not be the one to be blamed. My guess is that some custom adjustments of the model (if there is any) or CPU/GPU issue you referred might be the cause (most likely issue is in onnxruntime). And also based on the code you provide, I am curious that if they are having different preprocessing?

**Comment by AyaNasser96** [comment] 2022-06-28 06:13
@AllenTiTaiWang  Thank you for you reply. 
Could you sent me your email to send you the model and the needed scripts ^^

**Comment by AyaNasser96** [comment] 2022-07-05 12:12
@AllenTiTaiWang 
Hello, any updates ?

**Comment by justinchuby** [comment] 2022-07-05 23:29
Hi @AyaNasser96, thanks for providing the additional information. There is not any updates yet but we are tracking this issue. I would also test export with the pytorch-nightly version to verify that you see the same output as many fixes have been applied in the latest pytorch.

**Comment by AyaNasser96** [comment] 2022-07-18 10:38
@justinchuby  Could check this issue too, it might lead u to the error is at the onnxruntime. 
https://github.com/openvinotoolkit/openvino/issues/11942

**Comment by BowenBao** [comment] 2022-10-29 00:56
Experiment in related issue found the difference was due to different input preprocessing. https://github.com/openvinotoolkit/openvino/issues/11942#issuecomment-1295668267

@AyaNasser96 Could you validate if that's the reason for this mismatch as well?

**Comment by BowenBao** [comment] 2022-11-14 23:44
Closing as is resolved. @AyaNasser96 please feel free to re-open if you could still observe mismatch.

**Closed by BowenBao** 2022-11-14 23:44 UTC
Labels: module: onnx, triaged, onnx-needs-info
