### ISSUE TITLE
[inductor][cpu] basic_gnn_gcn fp32 static/dynamic shape default wrapper multiple thread performance regression

### ISSUE THREAD

**Issue by WeizhuoZhang-intel** [pytorch/pytorch#122281] opened 2024-03-20 05:56 UTC
### 🐛 Describe the bug

new_perf_regression in 2024-02-11
| suite | name | batch_size_new | speed_up_new | inductor_new | eager_new | compilation_latency_new | batch_size_old | speed_up_old | inductor_old | eager_old | compilation_latency_old | Ratio Speedup(New/old) | Eager Ratio(old/new) | Inductor Ratio(old/new) | Compilation_latency_Ratio(old/new)
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
torchbench | basic_gnn_gcn | 1.0 | 1.288219 | 0.010225241000000001 | 0.013172349735779002 | 12.064328 | 1 | 1.517554 | 0.008838759 | 0.013413294075486 | 12.073023 | 0.85 | 1.02 | 0.86 | 1.0

### Versions

SW info
| name | target_branch | target_commit | refer_branch | refer_commit
-- | -- | -- | -- | --
torchbench | main | ff42d907 | main | ff42d907
torch | main | 3ab08946d5052eaeda11d683d6a58e801a032755 | main | d0ca849fdf9807e730f91ce8e86d126b241e0940
torchvision | main | 0.18.0a0+a52607e | main | 0.18.0a0+806dba6
torchtext | main | 0.16.0a0+b0ebddc | main | 0.16.0a0+b0ebddc
torchaudio | main | 2.2.0a0+5286f9f | main | 2.2.0a0+02586da
torchdata | main | 0.7.1a0+0790338 | main | 0.7.1a0+0790338
dynamo_benchmarks | main | nightly | main | nightly

Repro:
[inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
```shell
bash inductor_single_test.sh multiple inference performance torchbench basic_gnn_gcn float32 first static default 0
```

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/896cf9d1ce3dec70fc33bf08fe21fa30ab4ff77c

[torchbench-basic_gnn_gcn-inference-float32-static-default-multiple-performance-drop_guilty_commit.log.txt](https://github.com/pytorch/pytorch/files/14663957/torchbench-basic_gnn_gcn-inference-float32-static-default-multiple-performance-drop_guilty_commit.log.txt)

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire @zxd1997066 @WeizhuoZhang-intel @chuanqi129

**Comment by jgong5** [comment] 2024-04-09 07:36
The regression should be caused by the fact that we cannot collapse the loops for parallelization due to the loop split for vectorization. See the generated code below:
```c++
            #pragma omp for
            for(long x0=static_cast<long>(0L); x0<static_cast<long>(2L); x0+=static_cast<long>(1L))
            {
                for(long x1=static_cast<long>(0L); x1<static_cast<long>(199984L); x1+=static_cast<long>(16L))
                {
                    auto tmp0 = at::vec::VectorizedN<int64_t,2>::loadu(in_ptr0 + static_cast<long>(x1 + (199985L*x0)), 16);
                    tmp0.store(out_ptr0 + static_cast<long>(x1 + (209985L*x0)), 16);
                }
                #pragma omp simd simdlen(8) 
                for(long x1=static_cast<long>(199984L); x1<static_cast<long>(199985L); x1+=static_cast<long>(1L))
                {
                    auto tmp0 = in_ptr0[static_cast<long>(x1 + (199985L*x0))];
                    out_ptr0[static_cast<long>(x1 + (209985L*x0))] = tmp0;
                }
            }
```
Previously, without int32/int64 vectorization, the two loop levels can be collapsed but not now. With multi-threaded benchmarks, only two threads are occupied in this case. The regression doesn't happen with single-threaded benchmark. One possible solution is to avoid splitting the vectorized loops but introduce "if-else" on the vectorized kernel and scalar kernel in the loop body. When we would still have a perfect loop nest and the loop levels can be collapsed well. The open is whether this would impact the performance in general. cc @zhuhaozhe

**Comment by zhuhaozhe** [comment] 2024-04-17 05:31
A [PR ](https://github.com/pytorch/pytorch/pull/124060) is WIP

**Comment by IvanKobzarev** [comment] 2024-09-15 21:50
Hi @WeizhuoZhang-intel , doing issue scrapping. Is this issue still relevant or can be closed?

**Comment by jgong5** [comment] 2024-09-23 11:17
> Hi @WeizhuoZhang-intel , doing issue scrapping. Is this issue still relevant or can be closed?

Yes, it is still relevant. PR https://github.com/pytorch/pytorch/pull/128812 is trying to fix the problem.

**Comment by zhuhaozhe** [comment] 2024-12-02 06:36
https://github.com/pytorch/pytorch/pull/128812 is merged

**Closed by zhuhaozhe** 2024-12-02 06:36 UTC
Labels: triaged, oncall: pt2, module: inductor, oncall: cpu inductor
