### ISSUE TITLE
PyTorch 2.4 windows performance regression compared with 0410 nightly

### ISSUE THREAD

**Issue by WeizhuoZhang-intel** [pytorch/pytorch#130619] opened 2024-07-12 14:01 UTC
### 🐛 Describe the bug

We are measuring performance on windows and observed that Windows whl performance regressed on rls/2.4 pre-released whl. In my local env, dev20240410 nightly whl was downloaded few month ago and we can see windows performance improved which might related to optimization PR by @xuhancn . We are get our best to search which nightly whl caused this regression, but the oldest nightly whl is 0513 which is already regressed.

| Model               	| BS 	| Pytorch   2.1 THP 	| Pytorch   0314 THP 	| Pytorch      0410 	| Pytorch 2.4 THP 	|
|---------------------	|----	|-------------------	|:------------------:	|-------------------	|-----------------	|
| RN50                	|  4 	|              40.1 	|            40.0962 	|            41.401 	|         13.7635 	|
| Mobilenetv3   Large 	|  8 	|          147.3972 	|           139.6188 	|           219.277 	|         116.182 	|
| distilbert-base     	|  8 	|             6.641 	|           5.603333 	|            8.7825 	|        3.249667 	|
| roberta-base        	|  8 	|           3.48425 	|              2.572 	|             4.201 	|          1.6335 	|

Hardware: 13th Gen Intel Core i7-13700H 2.4GHz
OS: Windows 11 23H2 22631.3593

### Versions

How to reproduce:
https://github.com/WeizhuoZhang-intel/win_benchmarks/blob/main/torchvision_models.py   
```shell
# torchvision
python torchvision_models.py

# transformers
pip install datasets evaluate accelerate transformers==4.34.1 scipy scikit-learn
git clone -b v4.34.1 --depth 1 https://github.com/huggingface/transformers.git
cd .\transformers\examples\pytorch\text-classification\

python run_glue.py --model_name_or_path distilbert-base-uncased-finetuned-sst-2-english --task_name sst2 --do_eval   --max_seq_length 384 --output_dir ./tmp --per_device_eval_batch_size 8 --dataloader_drop_last

python run_glue.py --model_name_or_path "deepset/roberta-base-squad2" --task_name sst2 --do_eval   --max_seq_length 384 --output_dir ./tmp --per_device_eval_batch_size 8 --dataloader_drop_last
```

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @seemethere @malfet @osalpekar @atalman @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by xuhancn** [comment] 2024-07-12 14:37
Thanks for @WeizhuoZhang-intel 's effort. 

Here are two key PRs on the timeline:
## 1. https://github.com/pytorch/pytorch/pull/118980 merged on Mar 31.
This PR enabled AVX2/AVX512 on pytorch Windows. So `Pytorch 0410` has perf improvememt to `Pytorch 0314`.

## 2. https://github.com/pytorch/builder/pull/1798 merged on April 26.
This PR changes:
a. switch mkl to static link.
b. change mkl version.
We can download the earliest nightly build was `0514` : https://download.pytorch.org/whl/nightly/torch/
The earlier nightly of `0514` was deleted.

I plan to pull `release/2.4` code to debug https://github.com/pytorch/builder/pull/1798, Wish it has some progress.

**Comment by xuhancn** [comment] 2024-07-12 15:29
Hi @WeizhuoZhang-intel ,
@atalman give us the URL can download the nightly build before `0514`: https://pytorch.s3.amazonaws.com/whl/nightly/cpu/torch-2.4.0.dev20240420%2Bcpu-cp311-cp311-win_amd64.whl

Please do the binary search between `0410` to `0514`, and locate the issue date. Thanks.

**Comment by atalman** [comment] 2024-07-12 16:04
Test with 
```
# torchvision
python torchvision_models.py
```
on Pytorch 2.3.1:
```
  warnings.warn(msg)
Test: [  0/100] Time  0.000 ( 0.000)
Test: [ 10/100] Time  0.069 ( 0.069)
Test: [ 20/100] Time  0.065 ( 0.068)
Test: [ 30/100] Time  0.071 ( 0.070)
Test: [ 40/100] Time  0.070 ( 0.070)
Test: [ 50/100] Time  0.065 ( 0.069)
Test: [ 60/100] Time  0.068 ( 0.069)
Test: [ 70/100] Time  0.071 ( 0.069)
Test: [ 80/100] Time  0.068 ( 0.069)
Test: [ 90/100] Time  0.065 ( 0.068)
inference latency 17.116 ms
Throughput: 58.425 fps
```

on Pytorch 2.4.0:
```
Test: [  0/100] Time  0.000 ( 0.000)
Test: [ 10/100] Time  0.094 ( 0.094)
Test: [ 20/100] Time  0.072 ( 0.073)
Test: [ 30/100] Time  0.080 ( 0.072)
Test: [ 40/100] Time  0.087 ( 0.075)
Test: [ 50/100] Time  0.071 ( 0.074)
Test: [ 60/100] Time  0.071 ( 0.073)
Test: [ 70/100] Time  0.063 ( 0.073)
Test: [ 80/100] Time  0.070 ( 0.073)
Test: [ 90/100] Time  0.085 ( 0.073)
inference latency 18.318 ms
Throughput: 54.590 fps
```

**Comment by atalman** [comment] 2024-07-12 16:44
Pytorch 0420:
```
python run_glue.py --model_name_or_path "deepset/roberta-base-squad2" --task_name sst2 --do_eval   --max_seq_length 384 --output_dir ./tmp --per_device_eval_batch_size 8 --dataloader_drop_last
***** eval metrics *****
  eval_accuracy           =     0.9106
  eval_loss               =     0.3902
  eval_runtime            = 0:01:10.33
  eval_samples            =        872
  eval_samples_per_second =     12.397
  eval_steps_per_second   =       1.55
```

**Comment by xuhancn** [comment] 2024-07-12 18:17
> Test with
> 
> ```
> # torchvision
> python torchvision_models.py
> ```
> 
> on Pytorch 2.3.1:
> 
> ```
> Test: [  0/100] Time  0.000 ( 0.000)
> Test: [ 10/100] Time  0.069 ( 0.069)
> Test: [ 20/100] Time  0.065 ( 0.068)
> Test: [ 30/100] Time  0.071 ( 0.070)
> Test: [ 40/100] Time  0.070 ( 0.070)
> Test: [ 50/100] Time  0.065 ( 0.069)
> Test: [ 60/100] Time  0.068 ( 0.069)
> Test: [ 70/100] Time  0.071 ( 0.069)
> Test: [ 80/100] Time  0.068 ( 0.069)
> Test: [ 90/100] Time  0.065 ( 0.068)
> inference latency 17.116 ms
> Throughput: 58.425 fps
> ```
> 
> on Pytorch 2.4.0:
> 
> ```
> Test: [  0/100] Time  0.000 ( 0.000)
> Test: [ 10/100] Time  0.094 ( 0.094)
> Test: [ 20/100] Time  0.072 ( 0.073)
> Test: [ 30/100] Time  0.080 ( 0.072)
> Test: [ 40/100] Time  0.087 ( 0.075)
> Test: [ 50/100] Time  0.071 ( 0.074)
> Test: [ 60/100] Time  0.071 ( 0.073)
> Test: [ 70/100] Time  0.063 ( 0.073)
> Test: [ 80/100] Time  0.070 ( 0.073)
> Test: [ 90/100] Time  0.085 ( 0.073)
> inference latency 18.318 ms
> Throughput: 54.590 fps
> ```
> 
> Pytorch 2.1.0
> 
> ```
> Test: [  0/100] Time  0.000 ( 0.000)
> Test: [ 10/100] Time  0.060 ( 0.060)
> Test: [ 20/100] Time  0.047 ( 0.057)
> Test: [ 30/100] Time  0.067 ( 0.059)
> Test: [ 40/100] Time  0.051 ( 0.058)
> Test: [ 50/100] Time  0.061 ( 0.058)
> Test: [ 60/100] Time  0.051 ( 0.058)
> Test: [ 70/100] Time  0.057 ( 0.059)
> Test: [ 80/100] Time  0.052 ( 0.059)
> Test: [ 90/100] Time  0.064 ( 0.059)
> inference latency 14.822 ms
> Throughput: 67.469 fps
> ```
> 
> Pytorch nightly from 0420
> 
> ```
> torch-2.4.0.dev20240420%2Bcpu-cp311-cp311-win_amd64.whl
> torchvision-0.19.0.dev20240420%2Bcpu-cp311-cp311-win_amd64.whl
> ```
> 
> ```
> Test: [  0/100] Time  0.000 ( 0.000)
> Test: [ 10/100] Time  0.048 ( 0.048)
> Test: [ 20/100] Time  0.045 ( 0.045)
> Test: [ 30/100] Time  0.059 ( 0.046)
> Test: [ 40/100] Time  0.049 ( 0.047)
> Test: [ 50/100] Time  0.046 ( 0.047)
> Test: [ 60/100] Time  0.046 ( 0.046)
> Test: [ 70/100] Time  0.039 ( 0.046)
> Test: [ 80/100] Time  0.048 ( 0.046)
> Test: [ 90/100] Time  0.039 ( 0.046)
> inference latency 11.543 ms
> Throughput: 86.635 fps
> ```

@atalman could you please test the 0428, which after mkl changed?

**Comment by xuhancn** [comment] 2024-07-12 20:28
@atalman We can fork from `release/2.4` and then:
revert https://github.com/pytorch/builder/pull/1798 and https://github.com/pytorch/pytorch/pull/129493
Let's check if static link mkl cause the performance regression.

**Comment by malfet** [comment] 2024-07-12 20:51
If there are no regression between 2.3 and 2.4, we don't need to make any reverts

**Comment by atalman** [comment] 2024-07-12 21:00
Rerun of 2.3.1
```
***** eval metrics *****
  eval_accuracy           =     0.4495
  eval_loss               =     0.7004
  eval_runtime            = 0:07:03.91
  eval_samples            =        872
  eval_samples_per_second =      2.057
  eval_steps_per_second   =      0.257
```

**Comment by xuhancn** [comment] 2024-07-12 21:24
> If there are no regression between 2.3 and 2.4, we don't need to make any reverts

Hi @malfet ,

This a regression since `0425` and it before the `release/2.4` branch cut.
The data shows it seems not a regression to `2.3.1`. The reason is https://github.com/pytorch/pytorch/pull/118980 boost the performance and fill the `mkl-static` regression's performance gap.

I think we need revert them for better performance.

**Comment by malfet** [comment] 2024-07-12 21:26
I think the challenge here is that it's a bit late(and too risky) in the release cycle to do something like that.

**Comment by xuhancn** [comment] 2024-07-12 21:29
> I think the challenge here is that it's a bit late(and too risky) in the release cycle to do something like that.

I known your concern, but the revert only impact on Windows. We can only rebuild the Windows binary.

**Comment by atalman** [comment] 2024-07-12 21:31
hi @xuhancn we would need to do complete rebuild of the rc. I agree with @malfet we should target this change for 2.4.1 release

**Comment by xuhancn** [comment] 2024-07-12 21:32
> hi @xuhancn we would need to do complete rebuild of the rc. I agree with @malfet we should target this change for 2.4.1 release

release 2.4.1 is good for me.

**Comment by malfet** [comment] 2024-07-12 21:53
I suspect one can solve it by using wholelib flag when linking with the library

**Comment by xuhancn** [comment] 2024-07-12 21:58
> I suspect one can solve it by using wholelib flag when linking with the library

What flag? could you please show me the detailed information?

**Comment by xuhancn** [comment] 2024-07-12 22:09
Hi @malfet 

Maybe we can try to PR fix build options for `main` branch, and fix `mkl-static`.

<img width="508" alt="image" src="https://github.com/user-attachments/assets/7d48cab6-ea24-4d5c-a95f-178cfb5a2bc4">
https://www.intel.com/content/www/us/en/developer/tools/oneapi/onemkl-link-line-advisor.html#gs.c3oeg2

**Comment by xuhancn** [comment] 2024-07-13 05:35
MKL build options comparsion:

Linux:
<img width="1384" alt="image" src="https://github.com/user-attachments/assets/629e974f-2b72-4909-9ea8-58446ce9fe61">

Windows:
<img width="1662" alt="image" src="https://github.com/user-attachments/assets/4d37cfbf-90da-4489-8fb2-683a7b359948">

It seems Windows MKL cmake file, miss some configuration. I will try to figure out it.

**Comment by xuhancn** [comment] 2024-07-14 18:02
Hi @atalman , @malfet 

I have submited a PR to fix Windows version `mkl-static` build options issue: https://github.com/pytorch/pytorch/pull/130697 .
Please take a look.

After this PR merged, @WeizhuoZhang-intel we can test the new nightly build, and check the perf regression issue.

**Comment by WeizhuoZhang-intel** [comment] 2024-07-16 17:00
We verified the latest 0716 nightly whl of windows and this performance issue has been fixed.
| Model               	| BS 	| Pytorch   0716 THP 	|
|---------------------	|----	|--------------------	|
| RN50                	|  4 	|           46.76667 	|
| Mobilenetv3   Large 	|  8 	|            216.963 	|
| distilbert-base     	|  8 	|            11.1668 	|
| roberta-base        	|  8 	|              5.337 	|

**Comment by WeizhuoZhang-intel** [comment] 2024-08-15 05:39
Hi @malfet ,
We have verified PyTorch v2.4.1 RC build whl: https://download.pytorch.org/whl/test/cpu/torch-2.4.1%2Bcpu-cp38-cp38-win_amd64.whl. And this performance issue was fixed. 
|       Model       	| BS 	| Pytorch   2.4 THP 	| Pytorch 0716 THP 	| Pytorch 2.4.1 THP 	|
|:-----------------:	|:--:	|-------------------	|------------------	|-------------------	|
| RN50              	| 4  	|           13.7635 	|         46.76667 	|           46.9074 	|
| Mobilenetv3 Large 	| 8  	|           116.182 	|          216.963 	|          219.9962 	|
| distilbert-base   	| 8  	|          3.249667 	|          11.1668 	|            12.387 	|
| roberta-base      	| 8  	|            1.6335 	|            5.337 	|             5.353 	|


cc @xuhancn  @atalman

**Comment by atalman** [comment] 2024-08-22 17:49
Closing this one since fixed in Nightly and cherry-picked to RC

**Closed by atalman** 2024-08-22 17:49 UTC
Labels: high priority, module: binaries, module: windows, triaged, module: regression

**Comment by atalman** [comment] 2024-08-30 15:18
Confirmed final rc 2.4.1:

```
100.0%
Test: [  0/100] Time  0.000 ( 0.000)
Test: [ 10/100] Time  0.035 ( 0.035)
Test: [ 20/100] Time  0.030 ( 0.035)
Test: [ 30/100] Time  0.026 ( 0.035)
Test: [ 40/100] Time  0.032 ( 0.036)
Test: [ 50/100] Time  0.039 ( 0.036)
Test: [ 60/100] Time  0.042 ( 0.036)
Test: [ 70/100] Time  0.034 ( 0.036)
Test: [ 80/100] Time  0.035 ( 0.036)
Test: [ 90/100] Time  0.034 ( 0.036)
inference latency 8.988 ms
Throughput: 111.255 fps
```
