### ISSUE TITLE
When I tried to use 'torch.nn.MaxUnpool3d', the following error occurred

### ISSUE THREAD

**Issue by cheyennee** [pytorch/pytorch#80853] opened 2022-07-05 01:55 UTC
### 🐛 Describe the bug

import torch
arg_1 = 49
arg_2 = 2
arg_class = torch.nn.MaxUnpool3d(arg_1,stride=arg_2,)
arg_3_0_tensor = torch.rand([20, 16, 25, 16, 7], dtype=torch.float32)
arg_3_0 = arg_3_0_tensor.clone()
arg_3_1_tensor = torch.randint(-16384,16,[20, 16, 25, 16, 7], dtype=torch.int64)
arg_3_1 = arg_3_1_tensor.clone()
arg_3 = [arg_3_0,arg_3_1,]
res = arg_class(*arg_3)

Expected outcome: The result should be a pytorch tensor.
Actual outcome: Actually there is no any error messages, the program is not responding. I have to forcibly close this program.

### Versions

python version: 3.8.3
PyTorch version: 1.8.1+cu111
CUDA used to build PyTorch: 11.1
OS: win11

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by cheyennee** [comment] 2022-07-06 13:16
> I can't reproduce this on linux, someone should try again on windows

Thank you very much for taking time to reproduce this on linux. I think maybe it only goes wrong on windows11😫.

**Comment by mantaionut** [comment] 2022-08-18 11:26
I managed to reproduce this with 1.8.1+cu11.1 but not on 1.12.1 cu11.6.

**Comment by mantaionut** [comment] 2022-11-23 14:22
I will close this issue since it cannot be reproduced on newer versions. Please try on version >1.12.1 and if it happens, open another issue.

**Closed by mantaionut** 2022-11-23 14:22 UTC
Labels: module: windows, triaged, module: deadlock
