### ISSUE TITLE
[feature request] A rank-revealing factorization of a matrix that is stable in backward.

### ISSUE THREAD

**Issue by de-gozaru** [pytorch/pytorch#84622] opened 2022-09-07 07:57 UTC
### 🚀 The feature, motivation and pitch

Hi,

I have a tall rectangular matrix `A` of shape `m` by `n`, where `m` >> `n`, and it has a rank `r` such that `r` <= `n`.

I want to extract the set of r columns from A that are linearly independent, i.e, I’m looking for removing the linearly dependent column from matrix `A`, so I end up with a matrix that has the dimension `m` by `r`, that is full rank! (basically, I'm trying to have the matrix `C` from [here](https://en.wikipedia.org/wiki/Rank_factorization#Existence))

is there an implemented function in Pytorch that does this?

One way to do this is to perform [rank factorization](https://en.wikipedia.org/wiki/Rank_factorization), and I want to know if such an algorithm is implemented in Pytorch, because it will be more efficient than implementing from scratch, and support back-propagation.

Thank you in advance for your help!

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Lezcano** [comment] 2022-09-07 10:23
What about performing an SVD and then discarding the singular vectors associated with the singular values that are zero (or better, close to zero)? Now, this is a linear algebra question, not a bug, so I'm closing this one. We can follow the discussion in the forums https://discuss.pytorch.org/

**Comment by nikitaved** [comment] 2022-09-07 11:42
@Lezcano is right, you can perform an SVD and take the top-k left singular values as column basis for your matrix. The problem is that backward will fail unless https://github.com/pytorch/pytorch/pull/71126 is merged. See https://github.com/pytorch/pytorch/issues/69532 for why there might be issues.

**Comment by Lezcano** [comment] 2022-09-07 11:48
This boils down to https://github.com/pytorch/pytorch/issues/69532, so I think it'd be better to track it there, but I'll let you choose.

**Comment by nikitaved** [comment] 2022-09-07 11:49
Ok, let's reduce the clutter then. Sorry, @de-gozaru , closing this as a duplicate of https://github.com/pytorch/pytorch/issues/69532.

**Closed** 2022-09-07 12:16 UTC
Labels: triaged, module: linear algebra

**Comment by de-gozaru** [comment] 2022-09-07 14:12
Hi @nikitaved @Lezcano 
Thank you for your answer!
So you are suggesting to wait for the PR to be merged, right?

**Comment by Lezcano** [comment] 2022-09-07 14:13
You can already try to use `linalg.svd` in your use case and see how it does. If you have issues with the gradients, then you can follow that PR, yes.

**Comment by de-gozaru** [comment] 2022-09-07 14:15
I see, thank you for your response!
