### ISSUE TITLE
dtype consistency not checked for larger tensors

### ISSUE THREAD

**Issue by lg-zhang** [pytorch/pytorch#50980] opened 2021-01-23 04:38 UTC
## 🐛 Bug

Torch checks dtypes when multiplying two tensors, which is nice for debugging, but it doesn't seem to check large tensors.

## To Reproduce

```
x = torch.rand(1,4,4).double()
y = torch.rand(2,4,5).float()
z = x @ y

# RuntimeError: expected scalar type Double but found Float
```

However, if y is a larger tensor it doesn't throw runtime error:
```
x = torch.rand(1,4,4).double()
y = torch.rand(2,4,1000).float()
z = x @ y

# Works just fine, but z is wrong -- `x.float() @ y` gives a different result
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @nairbv @mruberry

**Comment by ngimel** [comment] 2021-01-24 00:43
It's a bug in _baddbmm_mkl_ https://github.com/pytorch/pytorch/blob/d54cf2aa2710023ccedc2b7a89e8a3a45dc01e78/aten/src/ATen/native/mkl/LinearAlgebra.cpp#L137

**Comment by ngimel** [comment] 2021-01-24 00:58
Caused by #49506, cc @hlu1. We cannot have unchecked `data_ptr` accesses, even if it speeds up some benchmarks.

**Comment by mattip** [comment] 2021-01-27 18:45
lableing as "not for quansight" in the hope that @hlu1 will revert the change that causes the error.

**Comment by gchanan** [comment] 2021-02-03 17:45
Looks like it's fixed by https://github.com/pytorch/pytorch/pull/51248.

**Closed by gchanan** 2021-02-03 17:45 UTC
Labels: high priority, module: correctness (silent), module: type promotion, quansight-nack, triaged
