### ISSUE TITLE
Nightly Build Runtime Error 

### ISSUE THREAD

**Issue by kerry-Cho** [pytorch/pytorch#31509] opened 2019-12-20 00:52 UTC
## To Reproduce

19-12-18 Nightly Build Verion Runtime error 
Occurs when running a program

also How do I use a Nightly version with a different date?
The build time is too long and needs a different version.
Thanks All
call stack
```c++
ntdll.dll!00007ff92825fe0e()	Unknown
KernelBase.dll!00007ff92529a839()	Unknown
vcruntime140d.dll!00007ff904ba82b0()	Unknown
c10.dll!c10::util::detail::extract(c10::basic_string_view<char> prefix, c10::basic_string_view<char> suffix, c10::basic_string_view<char> str) line 51	C++
c10.dll!c10::util::detail::fully_qualified_type_name_impl<float>() line 62	C++
c10.dll!c10::util::get_fully_qualified_type_name<float>() line 	C++
c10.dll!caffe2::detail::_makeTypeMetaDataInstance<float>() line 298	C++
c10.dll!caffe2::TypeMeta::_typeMetaDataInstance<float>() line 44	C++
c10.dll!caffe2::TypeMeta::Make<float>() line C++
c10.dll!c10::`dynamic initializer for 'default_dtype''() line 5	C++
```

break point 
```c++
template <typename T>
inline C10_TYPENAME_CONSTEXPR string_view fully_qualified_type_name_impl() noexcept {
#if defined(_MSC_VER)
  return extract(//<< here
      "class c10::string_view __cdecl c10::util::detail::fully_qualified_type_name_impl<",
      ">(void)",
      __FUNCSIG__);
#elif defined(__clang__)
  return extract( 
      "c10::string_view c10::util::detail::fully_qualified_type_name_impl() [T = ",
      "]",
      __PRETTY_FUNCTION__);
#elif defined(__GNUC__)
  return extract(
    #if C10_TYPENAME_SUPPORTS_CONSTEXPR
      "constexpr c10::string_view c10::util::detail::fully_qualified_type_name_impl() [with T = ",
    #else
      "c10::string_view c10::util::detail::fully_qualified_type_name_impl() [with T = ",
    #endif
      "; c10::string_view = c10::basic_string_view<char>]",
      __PRETTY_FUNCTION__);
#endif
```

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
PyTorch version: 1.4.0.dev20191214
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 441.22
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin\cudnn64_7.dll

[pip3] numpy==1.16.3
[pip3] torch==1.4.0.dev20191214
[pip3] torchvision==0.5.0.dev20191215
[conda] blas                      1.0                         mkl
[conda] mkl                       2018.0.3                      1
[conda] mkl-include               2019.3                      203
[conda] mkl-service               1.1.2                    py35_2
[conda] mkl_fft                   1.0.6            py35hdbbee80_0
[conda] mkl_random                1.0.1            py35h77b88f5_1
[conda] torch                     1.4.0.dev20191214           <pip>
[conda] torch                     1.3.1                     <pip>
[conda] torch                     1.1.0                     <pip>
[conda] torchvision               0.5.0.dev20191215           <pip>
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): windows 10
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version: 
 - CUDA/cuDNN version: 10.2 
 - GPU models and configuration: 
 - Any other relevant information:

## Additional context
cc @ezyang @gchanan @zou3519 @peterjc123

**Comment by ngimel** [comment] 2019-12-20 02:58
Can you please provide a reproduction example (e.g. what program are you running to get this behavior)?

**Comment by kerry-Cho** [comment] 2019-12-20 04:35
@ngimel 
It occurs only by running the program.
It also occurs when you run the official example.
https://pytorch.org/cppdocs/installing.html#minimal-example

**Comment by peterjc123** [comment] 2019-12-20 04:45
Should be duplicate of https://github.com/pytorch/pytorch/issues/31370 although that is a python error.

**Closed by peterjc123** 2019-12-20 04:45 UTC
Labels: needs reproduction, triaged
