### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: Attribute 'strides' is expected to have field 'ints'

### ISSUE THREAD

**Issue by jianwolf** [pytorch/pytorch#19643] opened 2019-04-23 23:42 UTC
## 🐛 Bug report

Hi! I followed [the tutorial for exporting pytorch to onnx and run it with caffe2](https://pytorch.org/tutorials/advanced/super_resolution_with_caffe2.html). The pytorch model can run, and the command to generate the onnx model executed with a lot of warinings but no errors (`model = onnx.load(onnx_model_path)`). When I ran

```
prepared_backend = onnx_caffe2_backend.prepare(model)
```

I got the following error:

```
Traceback (most recent call last):
  File "pytorch2onnx.py", line 82, in <module>
    prepared_backend = onnx_caffe2_backend.prepare(model)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/caffe2/python/onnx/backend.py", line 686, in prepare
    super(Caffe2Backend, cls).prepare(model, device, **kwargs)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/onnx/backend/base.py", line 74, in prepare
    onnx.checker.check_model(model)
  File "/liveperson/code/p3env/lib64/python3.6/site-packages/onnx/checker.py", line 86, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Attribute 'strides' is expected to have field 'ints'

==> Context: Bad node spec: input: "56" output: "57" op_type: "MaxPool" attribute { name: "kernel_shape" ints: 98 type: INTS } attribute { name: "pads" ints: 0 ints: 0 type: INTS } attribute { name: "strides" type: INTS } doc_string: "/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/functional.py(386): max_pool1d_with_indices\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/functional.py(394): _max_pool1d\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/_jit_internal.py(132): fn\n/data/deep-intent-classifiers/models.py(64): <listcomp>\n/data/deep-intent-classifiers/models.py(64): forward\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/modules/module.py(477): _slow_forward\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/modules/module.py(487): __call__\n/data/deep-intent-classifiers/models.py(166): forward\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/modules/module.py(477): _slow_forward\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/modules/module.py(487): __call__\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/jit/__init__.py(252): forward\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/nn/modules/module.py(489): __call__\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/jit/__init__.py(197): get_trace_graph\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/onnx/utils.py(192): _trace_and_get_graph_from_model\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/onnx/utils.py(224): _model_to_graph\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/onnx/utils.py(281): _export\n/liveperson/code/p3env/lib64/python3.6/site-packages/torch/onnx/__init__.py(22): _export\npytorch2onnx.py(71): <module>\n"
```

I suspect this is a bug of caffe2, since there's no bug when running the model with pytorch and the onnx export is successful and there's no mentioning of anything about strides when exporting. Could someone help? Thanks!

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0.1.post2
 - OS (e.g., Linux): CentOS Linux 7
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6

**Comment by PhotonQuantum** [comment] 2020-01-27 11:56
Maybe this is a bug of `torch.onnx` ? It seems that the exporter unexpectedly omits the value of `strides` attribute.
I worked this around by specifying the stride of my pool layer explicitly:
```python
# out = F.avg_pool2d(out, (10, 25))
out = F.avg_pool2d(out, (10, 25), stride=(10, 25))

**Comment by neginraoof** [comment] 2020-03-24 07:48
@PhotonQuantum  This problem was fixed recently in avg_pool. Could you try the latest build?

**Comment by PhotonQuantum** [comment] 2020-03-24 17:19
@neginraoof Yes, the problem is solved.

**Comment by Ryuk17** [comment] 2021-03-23 06:48
I met the same question and my torch verison is 1.4.0, are there else solutions?

**Comment by garymm** [comment] 2021-09-20 18:36
That tutorial has been updated to use ONNX Runtime instead of caffe2.
In any case I was able to run the latest version of the Caffe2 tutorial with very minor tweaks (pin onnx to 1.8.1, set `keep_initializers_as_inputs=True` when calling `export`) using torch 1.9.0, so closing this.

**Closed by garymm** 2021-09-20 18:36 UTC
Labels: module: onnx, triaged
