### ISSUE TITLE
view+in-place masked_fill operation is ignored when exporting onnx

### ISSUE THREAD

**Issue by 1049451037** [pytorch/pytorch#95050] opened 2023-02-17 07:25 UTC
### 🐛 Describe the bug

Pytorch will ignore view+masked_fill_ operation when exporting onnx. Here is the example script:

```python
import torch

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.mask = torch.tensor([True, False])
    def forward(self, x):
        x.view(3, 2).masked_fill_(self.mask.unsqueeze(0), torch.finfo(x.dtype).max)
        return x

m = M()
x = torch.randn(6)
torch.onnx.export(m, (x,), 'mask.onnx')
```

The exported onnx is:

<img width="195" alt="image" src="https://user-images.githubusercontent.com/15194939/219577572-c9117c7a-b263-438e-965e-22e3a2a075bd.png">

### Versions

nvidia docker container 22.12 with pytorch 1.14

**Comment by BowenBao** [comment] 2023-03-08 18:07
Hi @1049451037, thanks for reporting. This is caused by aliasing + mutation, and I'm afraid there is no plan to fully support this for ONNX export. Basic aliasing and mutation are supported, but not the combination. You can workaround this by removing aliasing with explicitly updating `x` after `view`. 
```
8,9c8,10
<         x.view(3, 2).masked_fill_(self.mask.unsqueeze(0), torch.finfo(x.dtype).max)
<         return x
---
>         x = x.view(3, 2)
>         x.masked_fill_(self.mask.unsqueeze(0), torch.finfo(x.dtype).max)
>         return x.view(-1)
```

**Comment by BowenBao** [comment] 2023-03-22 17:36
Closing as not planned and workarounds given.

As a side note, we are working on a new dynamo based export, and we are considering handling functionalization more robustly.

**Closed by BowenBao** 2023-03-22 17:36 UTC
Labels: module: onnx, triaged
