### ISSUE TITLE
Allow C++ inference of JITted modules to run different modules on different streams

### ISSUE THREAD

**Issue by mkolod** [pytorch/pytorch#16614] opened 2019-01-31 18:47 UTC
## 🚀 Feature

It would be useful to be able to run inference on a JITted module on a non-default stream using the C++ API.

## Motivation

Let's imagine a case in which I have 2 models, A and B, which I'm trying to run in sequence on a small batch size, say bs=1. The models are streaming, e.g. for audio synthesis, or the workflow is such that small-batch requests keep coming quickly, but low latency is expected per request, so large batches are out of the question. Both models don't fully utilize the GPU with a small batch size, so running the pre-computation of model A's output concurrently with model B's inference (excluding the first iteration which is a cold start) would hide the latency of model A while having negligible impact on model B. This is similar to any other pipelining, say the traditional fetch-decode-execute-store CPU pipeline. For instance

**Step 1 (cold start):**

Stream 1:

cudaEventCreate(model_a_done_1) -> Input 1 -> Model A forward -> Buffer 1 -> cudaEventRecord(model_a_done_1)

**Step 2 (concurrently, on different streams):**

Stream 1:
cudaEventCreate(model_a_done_2) -> Input 2 -> Model A forward -> Buffer 2 -> cudaEventRecord(model_a_done_2)

Stream 2:
cudaEventSynchronize(model_a_done_1)  -> Buffer 1 -> Model B forward -> Output

**Step 3 (concurrently, on different streams):**

cudaEventCreate(model_a_done_3) -> Input 3 -> Model A forward -> Buffer 1 -> cudaEventRecord(model_a_done_3)

Stream 2: 
cudaEventSynchronize(model_a_done_2)-> Buffer 2-> Model B forward -> Output

etc.

A good example here is streaming speech synthesis, with say Tacotron generating the next mel spectrogram from text while WaveGlow is synthesizing audio from the previous spectrogram. For small batches, Tacotron is launch-latency bound and does little compute, and WaveGlow is still not using all of the GPU, so there are spare SMs to run the next Tacotron step to pre-compute it for WaveGlow's consumption.

## Pitch

I think simply exposing a setter method to allow the JITted model serialized from a .pt file to run on a provided CUDA stream (whether it's manually created using the CUDA API or managed by say ATen/c10 would work.

Note that currently it's a deficiency of the C++ API, because one can't JIT models which include Python with statements, so that for instance excludes JITting code which uses 2 Python models and a pre-fetcher running model A on a different stream using `torch.cuda.current_stream().wait_stream(stream)`, e.g. the way the Apex data prefetcher does it [here](https://github.com/NVIDIA/apex/blob/master/examples/imagenet/main.py#L257:L289).

## Alternatives

So far the only alternative that I see is keeping 2 JITted models in Python, with the stream control not being JITted. If a user wants to do the same using a C++ client, that's not possible, so paradoxically the Python client becomes more performant than the C++ client. It's problematic because there are lots of reasons to eliminate the dependence on Python in production. e.g. making performance deterministic by not having to deal with Python's garbage collector non-determinism.

**Comment by mkolod** [comment] 2019-01-31 19:22
@apaszke We talked about this issue on Slack, mentioning you here in case you're interested.

**Comment by mkolod** [comment] 2019-01-31 19:22
@ngimel @mruberry ^^

**Comment by jamesr66a** [comment] 2019-02-01 19:05
Hi @mkolod, thanks for the detailed feature request! We will discuss technical approaches and prioritization of this request at our meeting early next week.

**Comment by bhack** [comment] 2019-02-04 11:32
Is this not possible just setting the stream before the forward?

**Comment by dzhulgakov** [comment] 2019-02-05 07:56
Thanks for the suggestion!

On adding support of `with torch.cuda.stream(...):` in TorchScript, we'd prefer to avoid it or at least wait until it's absolutely necessary. The reason is that this API hard-codes pretty explicitly device (gpu) and it'd be harder to move the saved model to CPU later. Similarly, for inference cases, it might be preferable to control stream behavior in a central fashion - for example, be able to instruct jit::Interpreter to run only on X stream. Design-wise, it's preferable to expose more abstract parallelization primitives. We have a fork/join prototype (https://github.com/pytorch/pytorch/blob/master/test/test_jit.py#L12172) and it would be logical to extend this mechanism to introduce parallel streams.

However, nothing prevents us from manipulating streams directly in C++. `torch.cuda.stream` are just a thin wrappers around c10::Stream and the current stream gets stored in a thread-local variable. Thus if one puts `CUDAStreamGuard` around module invocation in C++ it should make all computation run on that stream transparently. Let me know if it doesn't work for some reason.

**Comment by bhack** [comment] 2019-02-05 11:13
So is it ok to just put a guard or a setcudastream before the module forward in c++?

**Comment by mkolod** [comment] 2019-02-05 22:36
Hi @dzhulgakov, I agree with all your points of course. 

The `CUDAStreamGuard` should work fine, of course. I didn't know it existed. Honestly the C++ API is poorly documented unless one works on the backend every day.

That's not a problem for ATen, because the API is very similar to the Python one, so one knows what to grep for. For things like `CUDAStreamGuard` one will find it depending on whether one has a good regex for it. I guess if one also knows that one should be looking for a guard/RAII block-scope pattern, one will also find it. In general I guess I wouldn't be asking the question if the C++ API were better documented. :)

**Comment by bhack** [comment] 2019-02-05 23:08
Honestly I had problem to set the cuda stream or guards just before the module forward and the set on another stream (or use the out of scope for the guards) i.e. for post-processing. I had random numerical differences.
Are we sure that is it supported?

**Comment by mkolod** [comment] 2019-02-06 19:45
@dzhulgakov @jamesr66a @bhack I just tested running JITted code with the guard and it's working perfectly fine, at least for me.

```
  bool use_streams = true;
  bool high_stream_priority = true;
  bool device = 0;
  
  c10::cuda::CUDAStream stream =
    use_streams ? 
      c10::cuda::getStreamFromPool(high_stream_priority, device) :
      c10::cuda::getDefaultCUDAStream();
  
  // guard active for this scope
  c10::cuda::CUDAStreamGuard guard(stream);

  std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("module.pt");

  auto output = module->forward(args);
```

**Comment by bhack** [comment] 2019-02-06 19:50
@mkolod 
Have you seen random instabilities on the output with this.

```
bool use_streams = true;
bool high_stream_priority = true;
bool device = 0;
  
c10::cuda::CUDAStream stream =
  use_streams ? 
    c10::cuda::getStreamFromPool(high_stream_priority, device) :
    c10::cuda::getDefaultCUDAStream();
  
std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("module.pt");

// guard active for this scope
c10::cuda::CUDAStreamGuard guard(stream);
auto output = module->forward(args);
```

 Is there any internal side effect to change the stream only for the forward?

**Comment by mkolod** [comment] 2019-02-06 21:09
@bhack I haven't found numerical issues yet. If there are any, I'll share. Also, I'm only using the C++ API for inference. For model training, the backprop always runs on the default stream, unlike fprop, for which you can choose the stream both in Python and in C++.

**Comment by bhack** [comment] 2019-02-06 21:14
@mkolod Yes it is also my context. But I have changed the stream just for the forward and not for the load.

**Comment by mkolod** [comment] 2019-02-06 21:36
@bhack I see, then maybe you need to record and event on the load stream and wait for the next step of the forward to make sure data has been loaded? Check out the event API [here](https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cuda/CUDAEvent.h). There's a block() method. You can block another stream to wait for the event in question to be recorded, e.g. you can record it when loading has finished.

**Comment by bhack** [comment] 2019-02-06 21:41
@mkolod Is the load async? Cause in my design the load is executed on class init and the module is a class member. So if it is not async I doubt that we need to block() explicitly.

**Comment by mkolod** [comment] 2019-02-06 21:55
@bhack Oh I thought load as in data load, which could be called many times, before each forward. I thought you meant that one CPU thread does loading and copies data to the GPU, and another runs inference. In this case I'm not sure if I have any good ideas.

**Comment by bhack** [comment] 2019-02-06 22:06
@mkolod I meant that if you have `torch::jit::load` at the constructor of a class and `module` is a class member you could want to just to execute `module->forward` on different thread/streams.

**Comment by hijkzzz** [comment] 2019-02-08 02:21
> @mkolod I meant that if you have `torch::jit::load` at the constructor of a class and `module` is a class member you could want to just to execute `module->forward` on different thread/streams.

I also encountered this problem.
Predictive value is abnormal.

**Comment by bhack** [comment] 2019-02-08 03:01
@hijkzzz Have you a minimal code to share to reproduce this on a public traceable model? 
We have embedded this inside a more large code base and we have still not found a slot to extract a minimal snipset over a public model to reproduce.

**Comment by vraivon** [comment] 2019-05-22 08:24
@hijkzzz @mkolod

have you solved this problem?

**Closed** 2020-09-25 15:55 UTC
Labels: jit
