### ISSUE TITLE
Weird interaction between sum, scalar multiplication and sparse tensor

### ISSUE THREAD

**Issue by serhii-havrylov** [pytorch/pytorch#28650] opened 2019-10-25 12:41 UTC
## 🐛 Bug
There is a weird behaviour of a backward function when performing a reduction operation (sum) on a dense tensor generated from the sparse one. For example, just multiplying the dense tensor by one causes the generation of the RuntimeError during the backward pass: `view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.`. Weirdly enough if there are several sums for resulting dense tensor the problem disappears.

```python
import torch


idxs = torch.tensor([[0, 2, 3], [1, 1, 2], [2, 1, 4], [3, 5, 1]], device=0)
values = torch.randn((4, 6, 5), device=0, requires_grad=True)

sparse_tensor = torch.sparse_coo_tensor(indices=idxs.t(),
                                        values=values[idxs.split(split_size=1, dim=1)].squeeze(),
                                        size=values.shape)
dense_tensor = torch.sparse.sum(sparse_tensor, dim=2).to_dense()
dense_tensor = dense_tensor.sum(dim=1) # + dense_tensor.sum(dim=1)

(dense_tensor * 1).sum().backward()  #  `view size is not compatible with input tensor's size and stride`
# dense_tensor.sum().backward()  #  no exceptions observed
```

## Environment
PyTorch Version is 1.2.0
OS: Ubuntu
Cuda: 10.1

cc @ezyang @SsnL @albanD @zou3519 @gqchen @vincentqb

**Comment by gchanan** [comment] 2019-10-25 17:10
interesting.   I'm not sure why off the top of my head the multiplication makes the difference.

**Comment by vadimkantorov** [comment] 2019-11-05 16:13
Not sure if this is relevant, but multiplying by 1 does incur a copy

**Comment by albanD** [comment] 2019-11-27 20:46
The problem is because `sum` returns a non-contiguous Tensor, while the backward of `to_dense` assumes what is given to it is contiguous because it uses `.view()` [here](https://github.com/pytorch/pytorch/blob/65bb34d88561b0011f0b74bd866a3ca22587e251/aten/src/ATen/native/sparse/SparseTensor.cpp#L500).
We should modify `sparse_mask` to make sure it works as expected on non-contiguous inputs.

**Comment by gchanan** [comment] 2020-02-20 21:44
Duplicate of https://github.com/pytorch/pytorch/issues/32705.

**Closed by gchanan** 2020-02-20 21:44 UTC
Labels: actionable, module: autograd, module: sparse, triaged
