### ISSUE TITLE
"new_full" support for torch 1.6.0+cu101

### ISSUE THREAD

**Issue by tangyanf** [pytorch/pytorch#44928] opened 2020-09-18 02:53 UTC
## 🐛 Bug

when i export a model to onnx then i got a RuntimeError:Exporting the operator new_full to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.
 I updated the source code today，found that you have already supported new_full in symbolic_opset9,but it still not support in torch which was installed by pip. so,which time i can use this.

## To Reproduce

    raise RuntimeError(msg)
    RuntimeError: Exporting the operator new_full to ONNX opset version 11 is not supported. Please open a bug to request  ONNX export support for the missing operator.

 - PyTorch Version :1.6.0+cu1010
 - OS :Linux
 - How you installed PyTorch :pip
 - Python version:3.8
 - CUDA/cuDNN version:101

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by neginraoof** [comment] 2020-09-18 16:10
new_full has been added as a PR that's merged 2 days back. If you're using PyTorch build nightly, you should be able to export it with latest nightly. But it will be part of the stable build starting from next release.
I'm closing this as it's not a bug. Please fill free to re-open if you see any further issues with export of this op.

**Closed by neginraoof** 2020-09-18 16:10 UTC
Labels: module: onnx, module: operators, triaged
