### ISSUE TITLE
cuda_tensor.norm(dim=(X, Y)) is broken

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#30704] opened 2019-12-04 00:57 UTC
```py
In [1]: torch.__version__
Out[1]: '1.4.0a0+91c6d2e'

In [2]: torch.randn(3, 3, device='cuda').norm(dim=(0, 1))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-32861c8633ea> in <module>
----> 1 torch.randn(3, 3, device='cuda').norm(dim=(0, 1))

/data/packages/pytorch/torch/tensor.py in norm(self, p, dim, keepdim, dtype)
    337     def norm(self, p="fro", dim=None, keepdim=False, dtype=None):
    338         r"""See :func:`torch.norm`"""
--> 339         return torch.norm(self, p, dim, keepdim, dtype=dtype)
    340
    341     def lu(self, pivot=True, get_infos=False):

/data/packages/pytorch/torch/functional.py in norm(input, p, dim, keepdim, out, dtype)
    780             dim = tuple(range(ndim))
    781         if out is None:
--> 782             return torch._C._VariableFunctions.frobenius_norm(input, dim, keepdim=keepdim)
    783         return torch._C._VariableFunctions.frobenius_norm(input, dim, keepdim=keepdim, out=out)
    784     elif p == "nuc":

RuntimeError: Could not run 'aten::conj.out' with arguments from the 'CUDATensorId' backend. 'aten::conj.out' is only available for these backends: [CPUTensorId, Va
riableTensorId].

In [3]: torch.randn(3, 3, device='cuda').norm()
Out[3]: tensor(3.6015, device='cuda:0')

In [4]: torch.randn(3, 3).norm(dim=(0, 1))
Out[4]: tensor(3.5681)

In [5]: torch.randn(3, 3).norm()
Out[5]: tensor(2.7136)
```

Yet passing in a 2-tuple is perfectly valid, per the `torch.norm` doc:
> dim (int, 2-tuple of python:ints, 2-list of python:ints, optional) – If it is an int, vector norm will be calculated, if it is 2-tuple of ints, matrix norm will be calculated. If the value is None, matrix norm will be calculated when the input tensor only has two dimensions, vector norm will be calculated when the input tensor only has one dimension. If the input tensor has more than two dimensions, the vector norm will be applied to last dimension.

cc @ezyang @gchanan @zou3519 @anjali411 @dylanbespalko

**Comment by zou3519** [comment] 2019-12-04 16:46
Based on the documentation, this sounds like a regression so I am marking it as high-pri. We should figure out if it is actually a regression (I haven't tested this on previous versions of pytorch).

**Comment by ngimel** [comment] 2019-12-04 17:53
This is likely a regression resulting from #27653

**Comment by ezyang** [comment] 2019-12-05 14:27
cc @dylanbespalko

**Comment by ezyang** [comment] 2019-12-05 14:31
It sounds like the correct fix is to make sure `conj` (and `real`) work on CUDA tensors as well as CPU tensors. Actually, it's possible that https://github.com/pytorch/pytorch/pull/30295 just up and fixes this.

**Comment by ezyang** [comment] 2019-12-05 14:32
Also @dylanbespalko, it seems like the modified version of `norm` and similar sites are a pessimization for the non-complex case, because it looks like your implementations of conj/real always do "work" (in the sense that they have to allocate and fill a new tensor). So regardless it may be a good idea to avoid calling these functions at all for non-complex inputs.

**Comment by dylanbespalko** [comment] 2019-12-05 19:38
@ezyang, 

Yes, this was definitely caused by me. This should effect the frobenius norm in `aten/src/ATen/native/LinearAlgebra.cpp`. The line of code in question is

```C++
at::sqrt(at::sum((self.conj() * self).real(), dim, keepdim));
```

And can be fixed two ways:

1. Adding CUDA support for Unary ops in #30295.
2. Creating a separate code-path for non-complex and complex cases.
    - @ezyang points out that conj() and real() are not in-place operations, so fix 1 will still have performance degradation. 

Solution:
Fix 1 should resolve the bug, but I will also submit a PR of fix 2 to improve the performance.

**Comment by ezyang** [comment] 2019-12-05 21:08
I confirmed that the CUDA strided complex patch fixes this problem.

**Comment by ngimel** [comment] 2019-12-05 23:05
@dylanbespalko even if you make `.conj` inplace do-nothing for non-complex tensors, it will still go through another round of dispatch, adding to overheads, so is it possible to just bypass `.conj` for non-complex types at the call site?

**Comment by dylanbespalko** [comment] 2019-12-05 23:13
@ngimel,

Agreed, I am working on bypassing it right now. I should have something submitted soon.

**Comment by brucemuller** [comment] 2020-02-21 11:58
I'm having this issue too in 1.4.0. Is this fixed in a new update or do I have to downgrade the pytorch version?

**Comment by ezyang** [comment] 2020-02-21 22:07
I think it's fixed in master, but someone should confirm.

**Comment by brucemuller** [comment] 2020-02-22 19:02
Thanks @ezyang how can I update to master or should I downgrade?

**Comment by peterbell10** [comment] 2020-02-24 17:32
Confirmed the original issue is fixed in master:
```python
>>> x = torch.randn(3,3)
>>> x.norm(dim=(0,1)), x.cuda().norm(dim=(0,1))
(tensor(2.9104), tensor(2.9104, device='cuda:0'))
```

@brucemuller you could try one of the nightly builds from https://pytorch.org/

**Closed by peterbell10** 2020-02-24 17:32 UTC
Labels: high priority, module: complex, module: operators, triaged

**Comment by Multihuntr** [comment] 2020-03-04 03:00
There's a simple workaround until the fix gets released. If you pass `p=2`, then it calculates it as you expect.

Not sure why it works, when the default `p='fro'` doesn't.

**Comment by drorpip** [comment] 2020-08-02 13:50
Hi,
Is the problem still exist?
I have pytorch 1.5.1

**Comment by Multihuntr** [comment] 2020-08-04 02:49
@drorpip The problem is fixed.

The problem was already fixed in the master branch at least on Feb 25th 2020. And pytorch 1.5.1 was released on Jun 19th 2020. But you can try it yourself by pasting this into the python interpreter

```python
import torch
x = torch.randn(3,3)
x.norm(dim=(0,1)), x.cuda().norm(dim=(0,1))
```

If it runs without crashing and gives the same answer for CPU and CUDA, then this issue is fixed in your version.
