### ISSUE TITLE
torch::serialize::OutputArchive::save_to crash if save on C:\

### ISSUE THREAD

**Issue by MaIronCool** [pytorch/pytorch#111121] opened 2023-10-12 06:16 UTC
### 🐛 Describe the bug

```
string model_path = "C:\\model.pt";
serialize::OutputArchive output_archive;
cp_net.save(output_archive);
output_archive.save_to(model_path);

```
Then crash - empty file are created.

If add some folder like this:
`string model_path = "C:\\Folder\\model.pt";`
Works fine

### Versions

libtorch-win-shared-with-deps-2.1.0+cpu

MSVC++Windows 10 VS 2022

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @mruberry @mikaylagawarecki

**Comment by albanD** [comment] 2023-10-12 13:00
Hey!
How does it crash? Is it because you don't have permission to write to C:\ by any chance?

**Comment by MaIronCool** [comment] 2023-10-12 13:33
UAC is deactivated. I have full access to C:\ 
I think it's a filename parsing problem. But the file is created, but empty.
![img](https://github.com/pytorch/pytorch/assets/17903004/bd6e770f-1de1-49a5-a622-a7813788f45c)

**Comment by kalaskarsanket** [comment] 2024-04-15 15:17
@malfet assigning you for PR review.

**Comment by alinpahontu2912** [comment] 2024-05-07 13:49
We tested with the latest nightly version and the problem is now fixed, feel free to open it again if needed and don't hesitate to open new issues for other problems or requests you may have.

**Closed by alinpahontu2912** 2024-05-07 13:49 UTC
Labels: module: windows, module: serialization, triaged
