### ISSUE TITLE
"undefined symbol: PySlice_Unpack" of pytorch 1.0.0 with Python 3.6.0

### ISSUE THREAD

**Issue by bfujiwara** [pytorch/pytorch#19161] opened 2019-04-11 12:07 UTC
## 🐛 Bug

`python: symbol lookup error: /usr/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack`

when generating and displaying big tensors.

## To Reproduce

```
$ python
Python 3.6.0 (default, Jan 16 2017, 12:12:55)
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'1.0.1.post2'
>>> torch.ones(10000)
python: symbol lookup error: /usr/lib/python3.6/site-packages/torch/lib/libtorch_python.so: undefined symbol: PySlice_Unpack
$
```

## Env

 - PyTorch 1.0.1.post2 installed via pip. cuda 9 (but same bug without cuda)
 - Linux os
- Python 3.6.0

**Comment by peterjc123** [comment] 2019-04-11 12:33
You'll need Python 3.6.1 or up. They are not compatible.

**Comment by vishwakftw** [comment] 2019-04-11 13:42
Upgrading to Python 3.6.1 was suggested in https://github.com/pytorch/pytorch/issues/14931#issuecomment-445448141.

Duplicate of #14931.

**Closed** 2019-04-11 16:36 UTC
Labels: duplicate, triaged
