### ISSUE TITLE
fftn and fftshift didn't work correctly together in 5D tensor

### ISSUE THREAD

**Issue by TripleCoenzyme** [pytorch/pytorch#69294] opened 2021-12-02 15:06 UTC
## 🐛 Bug

The output is completely different every time when I run fft.fftshift and fft.fftn together for some dims on 5D tensors.

### Code:

```python
import torch
from torch import fft

def test_function(x, dim=None):
    return fft.fftn(fft.fftshift(x, dim=dim), dim=dim)

a = torch.rand(4,1,64,64,64).cuda()
torch.testing.assert_close(test_function(a, (2,3,4)), test_function(a, (2,3,4)), check_stride=False)
```

### Output:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-c0f4420c4288> in <module>
      6
      7 a = torch.rand(4,1,64,64,64).cuda()
----> 8 torch.testing.assert_close(test_function(a, (2,3,4)), test_function(a, (2,3,4)), check_stride=False)

c:\users\fengjie\appdata\local\programs\python\python38\lib\site-packages\torch\testing\_asserts.py in assert_close(actual, expected, allow_subclasses, rtol, atol, equal_nan, check_device, check_dtype, check_stride, check_is_coalesced, msg)
    969     )
    970     if error_meta:
--> 971         raise error_meta.to_error()

AssertionError: Tensor-likes are not close!

Mismatched elements: 1048576 / 1048576 (100.0%)
Greatest absolute difference: 131221.6595396615 at index (0, 0, 0, 0, 0) (up to 1e-05 allowed)
Greatest relative difference: 262.78589086755204 at index (1, 0, 13, 63, 47) (up to 1.3e-06 allowed)
```
And if I continued to run `torch.testing.assert_close(test_function(a, (2,3,4)), test_function(a, (2,3,4)), check_stride=False)` in the same ipython kernel, the mismatched elements information is totally different, such as:
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 1048576 / 1048576 (100.0%)
Greatest absolute difference: nan at index (0, 0, 0, 0, 0) (up to 1e-05 allowed)
Greatest relative difference: nan at index (0, 0, 0, 0, 0) (up to 1.3e-06 allowed)
```
```
AssertionError: Tensor-likes are not close!

Mismatched elements: 786432 / 1048576 (75.0%)
Greatest absolute difference: nan at index (0, 0, 0, 0, 0) (up to 1e-05 allowed)
Greatest relative difference: nan at index (0, 0, 0, 0, 0) (up to 1.3e-06 allowed)
```

## Expected behavior

The behavior of the test_function should always be the same and the test code should end up with no AssertionError. 

## Environment

```
PyTorch version: 1.10.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 471.21
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] pytorch-lightning==1.0.8
[pip3] torch==1.10.0+cu113
[pip3] torch-tb-profiler==0.1.0
[pip3] torchaudio==0.10.0+cu113
[pip3] torchkbnufft==1.2.0.post3
[pip3] torchvision==0.11.1+cu113
[conda] Could not collect
```

## Additional context

I have done some tests:

1. Input the dim for different combination, the result can be different; but it seems that if I try to test under 2 dims (like `dim=(3,4)`), the test result is correct.
2. Input a CPUTensor (like `a = torch.rand(4,1,64,64,64).cpu()` ) to the test function, the test result is correct.
3. Change test_function to 
```python
def test_function(x, dim=None):
    return fft.fftn(fft.fftshift(x.cpu(), dim=dim), dim=dim).cuda()
```
or 
```python
def test_function(x, dim=None):
    return fft.fftn(fft.fftshift(x, dim=dim).cpu(), dim=dim).cuda()
```
the test result is correct.

4. Do the same test on an Ubuntu server with environment as:
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: Could not collect
CMake version: version 3.20.4
Libc version: glibc-2.27

Python version: 3.9.7 (default, Sep 16 2021, 13:09:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-4.15.0-162-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 455.32.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.3
[pip3] numpydoc==1.1.0
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.3.1               h2bc3f7f_2
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] mypy_extensions           0.4.3            py39h06a4308_0
[conda] numpy                     1.20.3           py39hf144106_0
[conda] numpy-base                1.20.3           py39h74d4b33_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchvision               0.11.1               py39_cu113    pytorch
```
the test result is correct.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @peterjc123 @mszhanyi @skyline75489 @nbcsm @mruberry @peterbell10

**Comment by zou3519** [comment] 2021-12-02 17:43
Tentatively marking high priority because this could be a silent correctness issue

**Comment by peterbell10** [comment] 2021-12-02 20:56
I wasn't able to reproduce on linux. Tried conda and pip installs, as well as a master building from source. In all cases the assert passed.

**Comment by malfet** [comment] 2021-12-06 18:18
@mszhanyi can you please check if this is the case?

**Comment by mszhanyi** [comment] 2021-12-07 03:22
I couldn't reproduce it locally, my desktop GPU is 1080.
There's no error in the example script.

The user installed the PyTorch with pip. 
I tested with conda and pip. both are OK.

**Comment by TripleCoenzyme** [comment] 2021-12-07 06:41
That's really weird...
BTW, I did the same test on conda with same windows environment and it showed the same error.
I guess if it is some CUDA-based error?

**Comment by TripleCoenzyme** [comment] 2021-12-08 12:40
By installing cuda 10.2 version pytorch in a new conda environment (`conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`), the problem disappeared.

However, if using `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch` in a new conda environment, the problem occurred.

Hope it will help you guys to locate the problem.

Thanks twice.

The two environment is attached below:

CUDA: 10.2 (work fine)
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 471.21
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.2.89              h74a9793_1    defaults
[conda] mkl                       2021.4.0           haa95532_640    defaults
[conda] mkl-service               2.4.0            py39h2bbff1b_0    defaults
[conda] mkl_fft                   1.3.1            py39h277e83a_0    defaults
[conda] mkl_random                1.2.2            py39hf11a4ad_0    defaults
[conda] numpy                     1.21.2           py39hfca59bb_0    defaults
[conda] numpy-base                1.21.2           py39h0829f74_0    defaults
[conda] pytorch                   1.10.0          py3.9_cuda10.2_cudnn7_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py39_cu102    pytorch
[conda] torchvision               0.11.1               py39_cu102    pytorch
```

CUDA 11.3 (have problem)
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (x86_64-posix-seh, Built by strawberryperl.com project) 8.3.0
Clang version: Could not collect
CMake version: version 3.22.0
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 471.21
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.3\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.3.1               h59b6b97_2    defaults
[conda] mkl                       2021.4.0           haa95532_640    defaults
[conda] mkl-service               2.4.0            py39h2bbff1b_0    defaults
[conda] mkl_fft                   1.3.1            py39h277e83a_0    defaults
[conda] mkl_random                1.2.2            py39hf11a4ad_0    defaults
[conda] numpy                     1.21.2           py39hfca59bb_0    defaults
[conda] numpy-base                1.21.2           py39h0829f74_0    defaults
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchvision               0.11.1               py39_cu113    pytorch
```

**Comment by mszhanyi** [comment] 2021-12-09 11:16
@TripleCoenzyme 

Could try the C++ Snippet with torch1.10+cu113?

```
#include <torch/torch.h>
#include <ATen/ATen.h>
#include <iostream>

using namespace torch;

Tensor test_function(const Tensor x, IntArrayRef dim) {
	return fft::fftn(fft::fftshift(x, dim), dim);
}

int main() {
	torch::Tensor a = torch::rand({ 4, 1, 64, 64, 64 }).cuda();
	auto b = test_function(a, {2, 3, 4});
	auto b1 = test_function(a, {2, 3, 4});

	//std::cout << b1 << std::endl;
	bool same = b.allclose(b1);
	if (same) {
		std::cout << "they are same" << std::endl;
	}
	std::cin.get();
}
```

You could check out https://pytorch.org/cppdocs/installing.html

**Comment by TripleCoenzyme** [comment] 2021-12-09 17:12
@mszhanyi 
Oops, it says `they are same` in debug version.

BTW, I get `[ CUDAComplexFloatType{4,1,2,3,4} ]` when printing b1.
Does {4, 1, 2, 3, 4} show the shape of b1?

**Comment by peterbell10** [comment] 2021-12-09 17:27
Yes that's the shape. `test_function` should read:
```
Tensor test_function(const Tensor x, IntArrayRef dim) {
	return fft::fftn(fft::fftshift(x, dim),
                 /*s=*/c10::nullopt,
                 /*dim=*/dim);
}
```

**Comment by TripleCoenzyme** [comment] 2021-12-10 03:22
@mszhanyi 
It says b1 and b are not same in Cpp program this time.

**Comment by mszhanyi** [comment] 2021-12-10 05:08
I still couldn't reproduce it. @TripleCoenzyme do you have chance to verify it in another machine.

**Comment by TripleCoenzyme** [comment] 2021-12-10 05:15
@mszhanyi ok I will try to verify at weekends or next week.

**Comment by mszhanyi** [comment] 2021-12-10 11:15
If you have extra time, you could debug PyTorch source code by referring to [my post] (https://github.com/pytorch/pytorch/wiki/Best-Practices-to-Edit-and-Compile-Pytorch-Source-Code-On-Windows) in that machine.
I think you should make a little change in  https://github.com/pytorch/pytorch/blob/master/test/cpp/api/fft.cpp and attach the test_api.exe

**Comment by TripleCoenzyme** [comment] 2021-12-10 11:24
@mszhanyi 
Same error on my colleague's PC. Both of us use RTX 2080Ti, but he haven't installed the system CUDA.
Also install torch+cu113 in a new conda environment:
```
PyTorch version: 1.10.0
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 教育版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.18363-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.0
[pip3] torchaudio==0.10.0
[pip3] torchvision==0.11.1
[conda] blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] cudatoolkit               11.3.1               h59b6b97_2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl                       2021.4.0           haa95532_640    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl-service               2.4.0            py39h2bbff1b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_fft                   1.3.1            py39h277e83a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] mkl_random                1.2.2            py39hf11a4ad_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy                     1.21.2           py39hfca59bb_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] numpy-base                1.21.2           py39h0829f74_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
[conda] pytorch                   1.10.0          py3.9_cuda11.3_cudnn8_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.0               py39_cu113    pytorch
[conda] torchvision               0.11.1  
```
Error information:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\1_software\anaconda\envs\torch_1_10\lib\site-packages\torch\testing\_asserts.py", line 971, in assert_close
    raise error_meta.to_error()
AssertionError: Tensor-likes are not close!

Mismatched elements: 1048576 / 1048576 (100.0%)
Greatest absolute difference: 131045.8349831721 at index (1, 0, 0, 0, 0) (up to 1e-05 allowed)
Greatest relative difference: 455.53047512298355 at index (0, 0, 18, 51, 31) (up to 1.3e-06 allowed)
```

**Comment by TripleCoenzyme** [comment] 2021-12-10 11:28
> If you have extra time, you could debug PyTorch source code by referring to [my post](https://github.com/pytorch/pytorch/wiki/Best-Practices-to-Edit-and-Compile-Pytorch-Source-Code-On-Windows) in that machine. I think you should make a little change in https://github.com/pytorch/pytorch/blob/master/test/cpp/api/fft.cpp and attach the test_api.exe

Alright I will try it at weekends or next week. (Didn't notice it before sending last message)

**Comment by mruberry** [comment] 2021-12-10 18:52
cc @ptrblck Maybe a cuFFT regression?

**Comment by mszhanyi** [comment] 2021-12-14 12:06
@peterbell10 @malfet 
I just reproduced it in one **2080** machine.
It's very likey that it has something with hardware because It's fine with **1080**  on Windows.

**Comment by mszhanyi** [comment] 2021-12-21 03:31
|                 | 1080Ti |  2080Ti
| ---------- | ----------- | ------
| cu10.2     | :heavy_check_mark: |:heavy_check_mark:
| cu11.1     | :heavy_check_mark: |:x:
| cu11.3     | :heavy_check_mark: | :x:
| cu11.5     | :heavy_check_mark: |:heavy_check_mark:

11.5 nightly download link
conda install pytorch[build="*11.5*"] cudatoolkit=11.5 -c pytorch-nightly -c conda-forge

**Comment by TripleCoenzyme** [comment] 2021-12-23 11:12
@mszhanyi I will try cu11.5 when I am available and thank you for your help.

**Comment by vladimir-aubrecht** [comment] 2023-01-31 16:18
@TripleCoenzyme did you have chance to verify that issue was fixed?

**Comment by vladimir-aubrecht** [comment] 2023-02-27 15:41
Could not reproduce with latest stack, closing the issue. Please create new issue if problem still persists.

**Closed by vladimir-aubrecht** 2023-02-27 15:41 UTC
Labels: high priority, needs reproduction, module: windows, triaged, module: fft
