### ISSUE TITLE
Bug when applying all gather in different group

### ISSUE THREAD

**Issue by a157801** [pytorch/pytorch#38375] opened 2020-05-13 02:48 UTC
## 🐛 Bug

I use a 8-gpu machine, and set 0-3 4-7 as two seperate group with new_group function. Then I use distributed.all_gather in each group. But there is a RuntimeError: Broken pipe.

## To Reproduce

```
import torch
import torch.distributed as distributed
import torch.multiprocessing as mp

import argparse

parser = argparse.ArgumentParser()
parser.add_argument('--rank', default=-1, type=int)


def main_worker(gpu, args):
    args.rank += gpu
    distributed.init_process_group(backend="nccl", init_method="tcp://127.0.0.1:34445", world_size=8, rank=args.rank)
    torch.cuda.set_device(args.rank)
    if args.rank <= 3:
        pg = distributed.new_group([0, 1, 2, 3], backend="nccl")
    else:
        pg = distributed.new_group([4, 5, 6, 7], backend="nccl")
    size = distributed.get_world_size(pg)
    num = torch.tensor(args.rank, device=args.rank, dtype=torch.float32)
    l = [torch.zeros_like(num) for k in range(size)]
    distributed.all_gather(l, num, group=pg, async_op=False)
    print(l)

def main():
    args = parser.parse_args()
    mp.spawn(main_worker, nprocs=8, args=(args,))


if __name__ == "__main__":
    main()
```

` python ddp.py --rank 0`

## Expected behavior

I hope that thread 0-3 output [0,1,2,3] and 4-7 ouput [4,5,6,7]. But the result is confusing

```
[tensor(0., device='cuda:7'), tensor(1., device='cuda:7'), tensor(2., device='cuda:7'), tensor(7., device='cuda:7')]
```

 and followed by a pipe broken runtimeerror.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 410.73
cuDNN version: /usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] numpydoc==0.9.2
[pip] torch==1.2.0
[pip] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.0.130                      0    defaults
[conda] mkl                       2020.0                      166    defaults
[conda] mkl-service               2.3.0            py37he904b0f_0    defaults
[conda] mkl_fft                   1.0.15           py37ha843d7b_0    defaults
[conda] mkl_random                1.1.0            py37hd6b4f25_0    defaults
[conda] numpy                     1.18.1           py37h4f9e942_0    defaults
[conda] numpy-base                1.18.1           py37hde5b4d6_1    defaults
[conda] numpydoc                  0.9.2                      py_0    defaults
[conda] pytorch                   1.2.0           py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchvision               0.4.0                py37_cu100    pytorch
```

## Additional context

cc @ngimel @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment] 2020-05-19 15:23
Hey @a157801 

As required by the [new_group API](https://pytorch.org/docs/stable/distributed.html#torch.distributed.new_group), all ranks need to call it even if they are not part of the group. See the related discussion [here](https://discuss.pytorch.org/t/simultaneous-communications-in-different-process-groups/75838).

So instead of doing:

```python
    if args.rank <= 3:
        pg = distributed.new_group([0, 1, 2, 3], backend="nccl")
    else:
        pg = distributed.new_group([4, 5, 6, 7], backend="nccl")
```

It should be 

```python
        pg1 = distributed.new_group([0, 1, 2, 3], backend="nccl")
        pg2 = distributed.new_group([4, 5, 6, 7], backend="nccl")
```

Closing this issue as this is not a bug.

**Closed by mrshenli** 2020-05-19 15:23 UTC
Labels: module: cuda, module: distributed, triaged
