### ISSUE TITLE
cuFFT error raised after trying FFT

### ISSUE THREAD

**Issue by mhkim0908** [pytorch/pytorch#89556] opened 2022-11-23 10:31 UTC
### 🐛 Describe the bug

```
import torch
device = torch.device("cuda:0")
aa = torch.ones(60,60).to(device)
torch.fft.fft2(aa)
```

returns

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [14], line 2
      1 aa = torch.ones(60,60).to(device)
----> 2 torch.fft.fft2(aa)

RuntimeError: cuFFT error: CUFFT_INTERNAL_ERROR
```

I'm using cuda 11.6, nvidia driver version 520.56.06, RTX 4090... with Ubuntu 22.04
I have reinstalled CUDA and NVIDIA drivers several times, but the problem is repeating.
I think there is no solution in the google.. 

please help me .
thanks.

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.15 (main, Oct 12 2022, 19:14:37)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4090
Nvidia driver version: 520.56.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.4
[pip3] torch==1.13.0+cu116
[pip3] torchaudio==0.13.0+cu116
[pip3] torchvision==0.14.0+cu116
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @ngimel @mruberry @peterbell10

**Comment by zou3519** [comment] 2022-11-28 14:35
This is a duplicate of https://github.com/pytorch/pytorch/issues/88038

**Closed** 2022-11-28 14:35 UTC
Labels: high priority, triage review, module: cuda, triaged, module: fft

**Comment by Linn0910** [comment] 2024-04-09 10:53
我遇到了一样的问题，请问怎么解决的啊？非常需要帮助！！

**Comment by wangqiang9** [comment] 2024-12-19 11:53
I have the same promblem...
