### ISSUE TITLE
RuntimeError: CUDA error: unknown error

### ISSUE THREAD

**Issue by MeteoRex11** [pytorch/pytorch#18989] opened 2019-04-06 18:16 UTC
**### Pretext:**

I recently installed pytorch-nightly, and my cuda version is upto date. But when I run my command, I get the following error:

**### Error:**

```
Traceback (most recent call last):
  File "main.py", line 77, in <module>
    algo.sample(datapath, cfg.STAGE)
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 238, in sample
    netG, _ = self.load_network_stageII()
  File "C:\Users\hunte\OneDrive\Documents\Projects\EAD Project\StackGAN-Pytorch-master\code\trainer.py", line 110, in load_network_stageII
    netG.cuda()
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 263, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 190, in _apply
    module._apply(fn)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 196, in _apply
    param.data = fn(param.data)
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 263, in <lambda>
    return self._apply(lambda t: t.cuda(device))
  File "C:\ProgramData\Anaconda3\lib\site-packages\torch\cuda\__init__.py", line 163, in _lazy_init
    torch._C._cuda_init()
RuntimeError: CUDA error: unknown error
```

**Comment by umanwizard** [comment] 2019-04-08 16:29
Duplicate of #18999

**Closed by umanwizard** 2019-04-08 16:29 UTC
