### ISSUE TITLE
torch.onnx can't export Hardswish()/ Hardsigmoid() activation 

### ISSUE THREAD

**Issue by Adhithya-tech** [pytorch/pytorch#54316] opened 2021-03-19 10:05 UTC
## 🐛 Bug

 Exporting the operator hardsigmoid to ONNX opset version 11 is not supported.

## To Reproduce

1. Pre-trained mobilenet v3 architecture and other similar image classification models can't be ported to onnx 
2. Pre-trained Fast RCNN with mobilenet v3 architecture and other similar object detection models can't be ported to onnx

## Expected behavior

 
Supposed to directly port to  .onnx model

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): Pytorch version 1.8, Torchvision 0.9
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by shubhambhokare1** [comment] 2021-04-08 06:01
Support for hardsigmoid was recently added in https://github.com/pytorch/pytorch/pull/54193
Could you try using the latest pytorch nightly version and check if this error still persists?

**Comment by garymm** [comment] 2021-11-20 00:51
Closing because we think it's fixed. Please open another one with repro instructions if this is reproducible with latest nightly pytorch.

**Closed by garymm** 2021-11-20 00:51 UTC
Labels: module: onnx, triaged
