### ISSUE TITLE
`tensor.repeat` fails because of non-resizable storage.

### ISSUE THREAD

**Issue by maciejkula** [pytorch/pytorch#4054] opened 2017-12-06 11:54 UTC
PyTorch version: 0.3.0
Python version: 3.6

This may well be desired behaviour, but it is a departure from 0.2.0. To reproduce:
```
In [5]: import numpy as np
In [6]: import torch
In [7]: torch.from_numpy(np.arange(10)).repeat(3)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-18d470bf42ef> in <module>()
----> 1 torch.from_numpy(np.arange(10)).repeat(3)

/path/torch/tensor.py in repeat(self, *sizes)
    273 
    274         size = torch.Size([a * b for a, b in zip(xsize, repeats)])
--> 275         xtensor.resize_(torch.Size(xsize))
    276         result.resize_(size)
    277         urtensor = result.new(result)

RuntimeError: calling resize_ on a tensor that has non-resizable storage. Clone it first or create a new tensor instead.
```

**Comment by albanD** [comment] 2017-12-06 11:58
The conversion from the numpy array is done by sharing memory.
While this sharing is active, neither the numpy array nor the torch tensor can be resized such that the sharing is not broken. This is expected behavior.
You need to add a `.clone()` after the `from_numpy` if you need a `Tensor` that can be resized.

**Comment by maciejkula** [comment] 2017-12-06 12:20
Thank you for your suggestion.

Just to clarify (and improve my mental model): repeat is necessarily a sharing-breaking operation because it allocates a new buffer and repeatedly copies the source. In that sense, I would argue that an implementation of `repeat` should be agnostic to whether the input tensor is shared or not; after all, allocating a new tensor is always necessary. In fact looking at the [code](https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L274) suggests that this is indeed the intention.

Given this reasoning, I see two possibilities:
1. The error is thrown to make it abundantly obvious to the user that sharing is broken, and this is the intention of the code.
2. The intention of the code _is_ to allocate a new tensor and copy, but there is a bug in the implementation.

**Comment by albanD** [comment] 2017-12-06 13:24
The problem comes from the fact that `resize_` is used here where it should actually be a `view` I think.
Resize raises the error that you see while `view` wouldn't.

The code does not allocate memory but uses a function that could.
It's a tricky function, maybe it is time to properly refactor and clean it :)

**Comment by colesbury** [comment] 2017-12-06 18:34
This looks like a bug in the implementation of `repeat` to me. These lines look suspicious:

https://github.com/pytorch/pytorch/blob/38f13447bce8b7dfe925664c2ef7e42659551cb4/torch/tensor.py#L277-L283

We shouldn't be resizing the original storage. We should create a new tensor of the correct size instead.

**Comment by soumith** [comment] 2018-01-23 17:02
fixed via https://github.com/pytorch/pytorch/pull/4084

**Closed by soumith** 2018-01-23 17:02 UTC
