### ISSUE TITLE
Dropout on integer tensor types dies with SIGFPE

### ISSUE THREAD

**Issue by alphadl** [pytorch/pytorch#15786] opened 2019-01-07 08:43 UTC
## To Reproduce

```
In[1] import torch
In[2] torch.nn.Dropout(0.3)(torch.LongTensor([1,0,0,0,1]))
>> Process finished with exit code 136 (interrupted by signal 8: SIGFPE)
```

cc @albanD @mruberry

**Comment by ezyang** [comment] 2019-01-07 14:02
Hi can you please try a nightly or build of master and see if you still have this problem? Also, could you please run https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py and paste the output here

**Comment by colesbury** [comment] 2019-01-07 17:52
This happens on master. I don't think dropout should work on long tensors. (It should raise a reasonable error message instead of dying with SIGFPE.) Since it divides by `1 - p` the result can't be represented as an integer tensor type.

We probably also should avoid SIGFPE with integer division by zero. For example, the following crashes with SIGFPE (and is the cause of the crash with Dropout):

```python
import torch
torch.LongTensor([1,0,0,0,1]) / 0
```

**Comment by alphadl** [comment] 2019-01-07 23:48
> Hi can you please try a nightly or build of master and see if you still have this problem? Also, could you please run https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py and paste the output here

@ezyang hi~ I just run it and got the following system env settings:
```
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None
OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: version 3.12.1
Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.6            py36hb8a8100_0
[conda] mkl_random                1.0.1            py36h5d10147_1
[conda] pytorch-nlp               0.3.7.post1               <pip>
[conda] torch                     0.4.1                     <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchnet                  0.0.4                     <pip>
[conda] torchtext                 0.3.1                     <pip>
[conda] torchvision               0.2.1                     <pip>
(python36)
```

**Comment by malmaud** [comment] 2019-08-23 21:25
I'm seeing the same error with PyTorch 1.2 (installed via `pip`) on OS X 10.14.5.

**Comment by ezyang** [comment] 2019-08-24 21:36
Thanks for the repros. This issue would be best resolved by following the suggested resolution from colesbury above. If you want to try fixing this, you can CC me as reviewer.

**Comment by mariosasko** [comment] 2020-09-19 00:03
@mruberry Think this issue can be closed since the signal is no longer raised.

Instead we get this error:

```RuntimeError: Integer division of tensors using div or / is no longer supported, and in a future release div will perform true division as in Python 3. Use true_divide or floor_divide (// in Python) instead.```

in both cases (the one with Dropout and the second one from @colesbury). I think now it's clear to the user what's the problem.

**Comment by albanD** [comment] 2020-09-21 14:14
Sounds good, thanks for the update.

**Closed by albanD** 2020-09-21 14:14 UTC
Labels: good first issue, module: nn, topic: crash, triaged
