### ISSUE TITLE
[ONNX] Refactor on torch.onnx.export_to_pretty_string

### ISSUE THREAD

**Issue by AllenTiTaiWang** [pytorch/pytorch#87321] opened 2022-10-19 21:10 UTC
`torch.onnx.export_to_pretty_string` is out of date compared to `torch.onnx.export`.

**Comment by thiagocrepaldi** [comment] 2022-10-20 21:12
Duplicate of https://github.com/pytorch/pytorch/issues/78834

**Closed** 2022-10-20 21:12 UTC
Labels: module: onnx, onnx-triaged
