### ISSUE TITLE
[Dynamo] nn.Module forward hook ends up with a separate graph

### ISSUE THREAD

**Issue by yanboliang** [pytorch/pytorch#121695] opened 2024-03-12 01:13 UTC
### 🐛 Describe the bug

```nn.Module.__call__``` should generates a single graph including ```forward``` and ```forward_hook``` if there is no graph break, but it ends up with two separate graphs.

Repro:
```
import torch
import torch.nn as nn


class MyLinear(torch.nn.Module):
    def __init__(self, in_features, out_features):
        super().__init__()
        self.weight = torch.nn.Parameter(torch.randn(out_features, in_features))
        self.bias = torch.nn.Parameter(torch.randn(out_features))

    def forward(self, x):
        return torch.nn.functional.linear(x, self.weight, self.bias)


class MockModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.register_buffer("buf0", torch.randn(10, 10))

    def forward(self, x):
        return x + self.buf0

def forward_hook(module: nn.Module, inputs: torch.Tensor, output: torch.Tensor):
    return output + 1

x = torch.randn(10, 10, device="cuda")
mod = MockModule().to("cuda")

mod.register_forward_hook(forward_hook)

opt_mod = torch.compile(backend="aot_eager", fullgraph=True)(mod)
y = opt_mod(x)
print(y)
```

Check the output with ```TORCH_LOGS=+dynamo```, and it prints out two graphs. The first graph from forward function:
```
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code] TRACED GRAPH
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]  ===== __compiled_fn_0 =====
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]  /home/ybliang/local/pytorch/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]     def forward(self, L_x_ : torch.Tensor):
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]         l_x_ = L_x_
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]         
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]         # File: /data/users/ybliang/debug/debug5.py:21 in forward, code: return x + self.buf0
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]         l__self___buf0 = self.L__self___buf0
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]         add = l_x_ + l__self___buf0;  l_x_ = l__self___buf0 = None
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]         return (add,)
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code]         
V0311 18:06:24.237000 140644996596864 torch/_dynamo/output_graph.py:1147] [0/0] [__graph_code] 
```
And the second one from forward hook:
```
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code] TRACED GRAPH
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]  ===== __compiled_fn_1 =====
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]  /home/ybliang/local/pytorch/torch/fx/_lazy_graph_module.py class GraphModule(torch.nn.Module):
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]     def forward(self, L_output_ : torch.Tensor):
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]         l_output_ = L_output_
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]         
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]         # File: /data/users/ybliang/debug/debug5.py:24 in forward_hook, code: return output + 1
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]         add = l_output_ + 1;  l_output_ = None
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]         return (add,)
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code]         
V0311 18:06:24.298000 140644996596864 torch/_dynamo/output_graph.py:1147] [1/0] [__graph_code] 
```

### Versions

N/A

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by anijain2305** [comment] 2024-03-13 06:18
Duplicate of https://github.com/pytorch/pytorch/issues/117584

**Comment by anijain2305** [comment] 2024-06-17 23:14
Closing as duplicate of https://github.com/pytorch/pytorch/issues/117584

**Closed** 2024-06-17 23:14 UTC
Labels: triaged, oncall: pt2, module: dynamo
