### ISSUE TITLE
OpenCV get Stuck in Transform when used in DataLoader

### ISSUE THREAD

**Issue by blukee** [pytorch/pytorch#1838] opened 2017-06-18 22:46 UTC
I'm using cv2.cvtColor() and cv2.warpPerspective to create new transforms. But the transforms get stuck at the above functions, when they are called DataSet's getitem function.

I tested the the transform in separate contexts, and they are working well.

After a few minutes, console threw out: 
`^CTraceback (most recent call last):
  File "EyeDataset.py", line 232, in <module>
    test()
  File "EyeDataset.py", line 225, in test
    for i, data in enumerate(dataloader, 0):
  File "/Users/home/anaconda/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 168, in __next__
    idx, batch = self.data_queue.get()
  File "/Users/home/anaconda/lib/python2.7/multiprocessing/queues.py", line 378, in get
    return recv()
  File "/Users/home/anaconda/lib/python2.7/site-packages/torch/multiprocessing/queue.py", line 21, in recv
    buf = self.recv_bytes()`

**Comment by apaszke** [comment] 2017-06-19 14:42
How do you know the process stopped in these functions? It's not shown in the stack trace

**Comment by blukee** [comment] 2017-06-19 20:13
Precisely speaking, I suspended the code are a few minutes and the console threw out the above stack trace. 
Actually, I found the issue. It should be MacOS multiple threading handling issue with OpenCV. 
https://github.com/opencv/opencv/issues/5150
I will try with on Ubuntu to see if this is still an issue.

**Comment by soumith** [comment] 2017-06-19 20:15
okay, I'm closing the issue here as it's related to opencv#5150

**Closed by soumith** 2017-06-19 20:15 UTC

**Comment by vadimkantorov** [comment] 2017-08-21 03:24
got hit by this. also a problem with opencv hanging

should the docs mention more explicitly that "spawn" multiprocessing method (and thus Python 3+) is preferred to avoid this issue?

**Comment by EKami** [comment] 2017-09-24 19:49
Getting hit by this too. On `cv2.warpPerspective`. What is weird about this is that the 1st epoch runs fine but the second epoch get stuck as soon as an item get transformed with `cv2.warpPerspective` from the `getitem()` Dataloader.

**Comment by vadimkantorov** [comment] 2017-09-24 21:14
For me it was the same, it got stuck at the second epoch. Maybe it's related to the fact that a new set of threads start up at the data loader iterator creation time. Anyway, OpenCV's unsafe to use with `fork` mode when OpenCV's multithreading is enabled (root cause https://github.com/opencv/opencv/issues/5150).

**Comment by youansheng** [comment] 2018-01-30 09:18
I have also encountered this problem. Are there any solutions? Thanks!

**Comment by heurainbow** [comment] 2018-02-05 07:16
@EKami Neat solution. Just add multiprocessing.set_start_method('spawn', force=True).

**Comment by abhisheksgumadi** [comment] 2019-07-18 16:29
... or just set cv2.setNumThreads(0)

**Comment by fzyzcjy** [comment] 2020-04-01 05:29
@Ekami Works for me! Thanks!

**Comment by LifeBeyondExpectations** [comment] 2020-08-17 17:43
I got some hint from https://stackoverflow.com/questions/54013846/pytorch-dataloader-stucked-if-using-opencv-resize-method
When I put cv2.setNumThreads(0), it works fine with me.

**Comment by EricCousineau-TRI** [comment] 2021-01-26 17:28
FWIW Confirmed this is still the case on CPython 3.6.9 (yup, default start method is `fork`) with PyTorch 1.6.0.

Also, I had compiled a few other don't-fork-pthread-pointer solutions as well:
https://gist.github.com/EricCousineau-TRI/8a2d1550f5fa4be4fed87d55a522dbf2
