### ISSUE TITLE
Using dill pickle module for load and save

### ISSUE THREAD

**Issue by sadanand-singh** [pytorch/pytorch#28313] opened 2019-10-18 21:53 UTC
In the latest codebase enforcing encoding='utf-8' breaks down the case when one uses the dill module for pickling, as dill does not take 'encoding' as an argument!

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by pietern** [comment] 2019-10-22 07:23
Relevant discussion for making `torch.load` use default encoding `utf-8` in #26421.

You can still pass an `encoding` kwarg to `torch.load` to override it.

**Comment by sadanand-singh** [comment] 2019-10-22 16:20
No, the issue is dill does NOT even take an argument of `encoding`. CCing @ezyang as he had opened the original #21743 issue.

**Comment by nmilosev** [comment] 2019-10-22 16:22
@ezyang please advise how to fix this, I would like to help

**Comment by ezyang** [comment] 2019-10-22 19:08
A cheap and cheerful fix is to pass utf-8 in, and if the call fails due to an argument error, retry again without that argument.

**Comment by pietern** [comment] 2019-10-24 13:26
(removing triaged label to make sure it is discussed in triage review)

**Comment by gchanan** [comment] 2019-10-28 17:22
We don't claim to support dill, but a lot of people seem to use it.

**Comment by nmilosev** [comment] 2019-11-02 22:05
I cannot reproduce this.

Did this get fixed in the meanwhile?

```py3
   def test_dill_serialization_no_encoding(self):
        try:
            import dill
        except:
            return

        x = torch.randn(5, 5)
        
        with tempfile.NamedTemporaryFile() as f:
            torch.save(x, f, pickle_module=dill)
            f.seek(0)
            x2 = torch.load(f, pickle_module=dill)
            self.assertIsInstance(x2, type(x))
            self.assertEqual(x, x2)

    def test_dill_serialization_encoding(self):
        try:
            import dill
        except:
            return

        x = torch.randn(5, 5)
        
        with tempfile.NamedTemporaryFile() as f:
            torch.save(x, f, pickle_module=dill)
            f.seek(0)
            x2 = torch.load(f, pickle_module=dill, encoding='utf-8')
            self.assertIsInstance(x2, type(x))
            self.assertEqual(x, x2)
```

I wrote these two tests, and both are passing. @sadanand-singh can you provide an example please?

1. `save` doesn't accept `encoding`.
2. `load` does but on my machine this doesn't brake the loading when using dill. See the second test.

I maybe didn't understand the report so if you could provide an example, that would be best.

**Comment by nmilosev** [comment] 2019-11-02 22:24
To add, I modified `torch/serialization.py`:

```
    _sys_info = pickle_module.load(f, **pickle_load_args)
    print(pickle_module, pickle_load_args, pickle_module.__version__)
    unpickler = pickle_module.Unpickler(f, **pickle_load_args)
    unpickler.persistent_load = persistent_load
    result = unpickler.load()
```

and I got this:

```
<module 'dill' from '/home/nmilosev/.conda/envs/pytorchcontrib/lib/python3.7/site-packages/dill/__init__.py'> {'encoding': 'utf-8'} 0.3.1.1
```

Even further just firing a REPL:

```
Python 3.7.5 (default, Oct 25 2019, 15:51:11) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import dill
>>> f = open('temp', 'r')
>>> dill.Unpickler(f, encoding='utf-8')
<dill._dill.Unpickler object at 0x7fbd028de050>
>>> dill.Unpickler(f, encodisdng='utf-8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nmilosev/.conda/envs/pytorchcontrib/lib/python3.7/site-packages/dill/_dill.py", line 467, in __init__
    StockUnpickler.__init__(self, *args, **kwds)
TypeError: 'encodisdng' is an invalid keyword argument for Unpickler()
>>> 
```

So seems to me that `dill` is definitely supporting `encoding` for the `Unpickler`, which is the only thing we added with the mentioned PR.

Seems to me, that since `dill` 0.3.1 this is supported: https://github.com/uqfoundation/dill/issues/156 and checking the code https://github.com/uqfoundation/dill/blob/master/dill/_dill.py#L268 it looks like they support it.

**Comment by umgupta** [comment] 2019-11-20 18:56
I faced the same issue, it seems like upgrading dill to 0.3.1.1 fixed the problem for me.

**Comment by zou3519** [comment] 2019-12-02 19:33
Upgrading to dill 0.3.1 as per @nmilosev's comment seems to be the solution here. Here's what we can do from the pytorch side, though, if we commit to supporting dill:
- Detect if the user is using dill as the picker. If so, check dill's version and error out gracefully if it's too small
- Add tests for dill

**Comment by zou3519** [comment] 2019-12-18 18:38
Fixed in https://github.com/pytorch/pytorch/pull/30985 by @kurtamohler

**Comment by ezyang** [comment] 2020-01-10 14:48
Acccording to @ljk53 this was only fixed in Python 3 and not Python 2.

**Comment by kurtamohler** [comment] 2020-01-22 18:04
Should I still fix this for Python 2, or is skipping the dill test (commit 03ff3eb) good enough? We are on the final version that will support Python 2 after all.

**Comment by zou3519** [comment] 2020-01-22 18:38
Yeah, we're not planning on supporting Python 2 in 1.5 so it is sufficient to just skip the dill test on python 2

**Closed** 2020-01-22 19:08 UTC
Labels: high priority, module: serialization, topic: dependency bug, triaged
