### ISSUE TITLE
Strided tensor in backward cause uninitialized output

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#112006] opened 2023-10-25 06:43 UTC
### 🐛 Describe the bug

if we pass the strided tensor to the backward function of GELU, we see that uninitialized output. Please use the below code to reproduce the issue. This issue present in PT2.1 as well.

```
import torch
def run_on_device():
    tensor = torch.randn([2, 2, 3], requires_grad=True)
    m = torch.nn.GELU(approximate="none")
    # forward result
    res = m(tensor)
    # bwd_tensor
    grad_in = torch.arange(12).reshape([2, 2, 3]).permute([1, 0, 2])
    res.backward(grad_in)
    print(tensor.grad)

if __name__ == "__main__":
    run_on_device()

```

```
tensor([[[2.7357e-34, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00]]])

```

In above reproduction code if we remove the stride by making the tensor contiguous then problem get solved. 
grad_in = grad_in.contiguous()

### Versions

[pip3] numpy==1.24.4
[pip3] torch==2.1.0
[pip3] torchaudio==2.0.1
[pip3] torchdata==0.6.1
[pip3] torchmetrics==1.2.0
[pip3] torchtext==0.15.2
[pip3] torchvision==0.15.1

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @bhosmer @cpuhrsch @erichan1 @drisspg

**Comment by mingfeima** [comment] 2023-10-25 08:25
@yanbing-j could you please help fix this one?

**Comment by albanD** [comment] 2023-11-02 17:54
The simplest fix is to add a `.contiguous()` in the backward formula. A more involved change will be to fix the formula to support arbitrary stride properly.

**Comment by yanbing-j** [comment] 2023-11-22 05:46
@jay746 , in the latest PyTorch, the issue is gone. Could you please verify it again? Thanks!

**Comment by jthakurH** [comment] 2024-02-23 17:51
That's right @yanbing-j , In PT2.2 i see, it is passing!
```
tensor([[[ 0.0000, -0.0524,  1.4309],
         [ 5.5390, -0.3139,  0.7154]],

        [[ 2.0605,  4.1351,  5.6143],
         [10.1405, -0.0673, -0.2192]]])
```

**Comment by jthakurH** [comment] 2024-02-23 17:53
let's close this issue
cc @albanD / @yanbing-j

**Closed** 2024-02-23 18:13 UTC
Labels: module: nn, triaged
