### ISSUE TITLE
LibTorch C++ mnist example gets an exception on Windows 10 with Visual Studio

### ISSUE THREAD

**Issue by lel4866** [pytorch/pytorch#15757] opened 2019-01-05 17:00 UTC
## 🐛 Bug

I get an exception executing the c++ mnist example using Visual Studio on Windows 10. This is the same problem as reported in #15711, but that issue was closed (it assumed the problem was due to trying to use MinGW). With respect to the Debug/Release issue, it is quite common to debug code in Debug configuration that uses libraries in Release configuration. But, in any event, the exception happens in both configurations.

![image](https://user-images.githubusercontent.com/1310042/50726831-57025480-10e0-11e9-97e6-ec84130e4a1a.png)

Here's the exception in torch::ordered_dict.h: 

![image](https://user-images.githubusercontent.com/1310042/50726882-21aa3680-10e1-11e9-9394-b383d776f762.png)

**Comment by peterjc123** [comment] 2019-01-05 18:34
Are you using VS 2015? Please update to VS 2017 if it is the case.

**Comment by lel4866** [comment] 2019-01-05 18:59
I'm using the latest VS 2017.

**Comment by lel4866** [comment] 2019-01-06 00:53
So, this is the same issue reported in the Pytorch forum by Hai_Bi: https://discuss.pytorch.org/t/libtorch-run-on-windows-error/32017

It is marked solved by hylke_kleve and it's stated that it was reported on GitHub, but I couldn't find it. Basically, it gives a reason why both the sample build and torch.dll must be Release builds.

However, even though I now get pas the Net() constructor, the sample still crashes with an error code. Since I can't debug it, I put in a couple of print statements. It gets to line 138, but not to line 140

![image](https://user-images.githubusercontent.com/1310042/50730789-78386480-1123-11e9-9a59-1b2332b0ecff.png)

The error on the console is:

![image](https://user-images.githubusercontent.com/1310042/50730791-956d3300-1123-11e9-8e81-785e8658c7a7.png)

**Comment by peterjc123** [comment] 2019-01-06 03:31
How did you set options.data_root? Could you give the full code so I can reproduce this issie?

**Comment by peterjc123** [comment] 2019-01-06 04:42
I tried the example MNIST code in https://github.com/goldsborough/examples/tree/cpp/cpp/mnist with the nightly libtorch and it worked. So apparently, it's related to the data path. You have to put the directory `data` (which contains the MNIST data) into `C:\users\larry\mnist\build\x64\Release`.

**Comment by peterjc123** [comment] 2019-01-06 04:43
@soumith Maybe we should close this issue because it's not a bug?

**Comment by peterjc123** [comment] 2019-01-06 04:46
@goldsborough Maybe we should add a warning/throw an exception if the file doesn't exist.

**Comment by lel4866** [comment] 2019-01-06 13:12
Thanks...this works by setting the data_root in struct Options to the path of the data. Especially thanks for working on the weekend.

I should point out, however, that the data directory exists in the "wrong" place (with respect to the original location specified in data_root) because its put there by the CMakeLists.txt file that comes in examples-cpp\cpp\mnist.

I think the best solution for others might just be a note that you have to set data_root.

**Comment by peterjc123** [comment] 2019-01-07 03:18
All of your points are based on the fact that you are using VS, which is something we could not control directly because the VS project is generated by CMake. If you use the command-line commands, these errors could be avoided. There's not much we can do to help you. But I agree with you that the notice in the document and the debug version of torch should be added.

**Comment by lel4866** [comment] 2019-01-07 13:58
Agree 100% This can be pretty much solved for everyone with a little documentation and a debug version of torch.dll.

**Comment by hyklv** [comment] 2019-01-07 23:00
> All of your points are based on the fact that you are using VS, which is something we could not control directly because the VS project is generated by CMake. If you use the command-line commands, these errors could be avoided. 

@peterjc123 I opened the folder directly from Visual Studio 15.7. It was relatively straightforward this way: It has relatively new [built-in support for CMake](https://docs.microsoft.com/en-us/cpp/ide/cmake-tools-for-visual-cpp?view=vs-2017). 

For me the steps for getting the sample to work were:
- Open the mnist folder via **File > Open Folder** 
- Edit `CMakeSettings.json`  "cmakeCommandArgs": "-DCMAKE_PREFIX_PATH=BlaBla\\Torch" for the required CMake variables.
- (Clean up unsupported x86/debug configurations in CMakeSettings.json via **CMake > Change Make Settings**.)
- Add command to copy dlls to target dir in `CMakeLists.txt`.

After that I could build and run the sample without any problems from the debugger. The data directory was generated by CMake in right place (same folder as the executable).

So these steps are very similar to the steps explained on [INSTALLING C++ DISTRIBUTIONS OF PYTORCH](https://pytorch.org/cppdocs/installing.html). Of course I do agree it would be very useful to have this information clearly layed out on a separate Windows page / section. Maybe these steps will help others in the mean time. HIH. Keep up the good work!

Bug rapport was on #15236 by the way. @lel4866

**Comment by peterjc123** [comment] 2019-03-15 05:15
Guys, we are now providing the debug version of libtorch in the nightlies.

**Closed** 2019-03-26 04:14 UTC
Labels: windows

**Comment by abreheret** [comment] 2019-08-20 13:01
To add another solution to this problem:
I also had windows crash with VS2017 and with the [MNIST example](https://github.com/goldsborough/examples/tree/cpp/cpp/mnist). I had put everything in release mode, and the only solution is to have the correct version MSVC Toolset "v141 in VS; version 14.11" (VS2017, version 15.3 & 15.4). And not the latest version (VS2017, version 15.9.15) or a other version.
So to downgrade the version with cmake it was enough to do:

`cmake -G "Visual Studio 15 2017 Win64" -T version=14.11 -DCMAKE_PREFIX_PATH=c:/path/to/libtorch ..`

It works and I tested with this config : 
- OS : Windows 10
- Visual Studio 2017 
- **MSVC 14.11**
- Release Mode
- libtorch 1.2 CUDA 9.2 (https://download.pytorch.org/libtorch/cu92/libtorch-win-shared-with-deps-latest.zip)

If you do not have the vc14.11 under VS2017 installed, you have to add here : 
![](https://devblogs.microsoft.com/wp-content/uploads/sites/9/2019/02/SxSIndividualComponents.png)

**Comment by peterjc123** [comment] 2019-08-20 15:44
@abreheret Yeah, your post reminds me of this post: https://devblogs.microsoft.com/cppblog/c17-progress-in-vs-2017-15-5-and-15-6/. It says that "Mixing an older STL with a newer compiler is untested and unsupported, but will typically work. However, mixing a newer STL with an older compiler is a recipe for doom." So we should actually pin the VS toolset version during the whole development process.

**Comment by luocheng610** [comment] 2020-01-10 08:18
Directly download the libtorch of the windows version 1.3.1 from the official website
It seems that it is not possible to directly build the project with vs. the compilation error, and did not go to the link step, some syntax errors were reported during the compilation process, and it was a large number. It seems that only the cmake method provided by the official website can be used to build the project. What I can confirm is that the tool set specified above on github (14.11.25503)
