### ISSUE TITLE
unable to install pytorch with conda on macOS 10.13

### ISSUE THREAD

**Issue by cciliber** [pytorch/pytorch#92002] opened 2023-01-11 13:08 UTC
### 🐛 Describe the bug

Hi, I am currently installing conda on a mac (macOS 10.13). 

I have installed pytorch via conda on macOS in the past in several occasions (not this version of the OS though) but I have encountered the following two issues this time:

1. If I install pytorch with conda on a fresh environment everything looks fine. However, if I then install something else (e.g. pandas), I get the following message 

```shell
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: /
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
```

At the end of this search it seems that conda tries to pick up the CPU version of torch from conda-forge (rather than using the pytorch channel)

2. If I install something else first, and then pytorch, I stumble upon a similar problem (with the conflict arising as soon as I try to install the second dependency). 

Please let me know if I can provide any additional info. 

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (x86_64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.1
Libc version: N/A

Python version: 3.11.0 | packaged by conda-forge | (main, Oct 25 2022, 06:24:51) [Clang 14.0.4 ] (64-bit runtime)
Python platform: macOS-13.0.1-x86_64-i386-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.24.1
[conda] numpy                     1.24.1          py311h62c7003_0    conda-forge

cc @malfet @seemethere @albanD

**Comment by albanD** [comment] 2023-01-12 19:24
Hi,

This is a duplicate of https://github.com/pytorch/pytorch/issues/91839
You can find details there about the current status of 3.11 conda binaries.

**Closed by albanD** 2023-01-12 19:24 UTC
Labels: module: build, module: macos
