### ISSUE TITLE
Differing behavior between CUDA and CPU for index_put

### ISSUE THREAD

**Issue by kofshinobi** [pytorch/pytorch#77406] opened 2022-05-13 08:49 UTC
### 🐛 Describe the bug

Perhaps a minor bug, but could point to something more major happening behind the scenes. There is a slight inconsistency in behavior between CPU and CUDA implementations for index_put; namely, as seen below, performing index put with accumulate=True works in one instance in CUDA where it fails due to a broadcasting shape mismatch on the CPU. Squeezing the values tensor results in all tests working properly.

```python
import torch

a = torch.zeros(4)
b = torch.tensor([[0.],[1.],[2.],[3.]])
i = torch.tensor([3,2,1,0])

a.index_put([i],b)
# RuntimeError: shape mismatch: value tensor of shape [4, 1] cannot be broadcast to indexing result of shape [4]

a.index_put([i],b,accumulate=True)
# RuntimeError: shape mismatch: value tensor of shape [4, 1] cannot be broadcast to indexing result of shape [4]

a.to('cuda').index_put([i.to('cuda')],b.to('cuda'))
# RuntimeError: shape mismatch: value tensor of shape [4, 1] cannot be broadcast to indexing result of shape [4]

a.to('cuda').index_put([i.to('cuda')],b.to('cuda'),accumulate=True)
# tensor([3., 2., 1., 0.], device='cuda:0')

a.index_put([i],b.squeeze())
# tensor([3., 2., 1., 0.])

a.index_put([i],b.squeeze(),accumulate=True)
# tensor([3., 2., 1., 0.])

a.to('cuda').index_put([i.to('cuda')],b.squeeze().to('cuda'))
# tensor([3., 2., 1., 0.], device='cuda:0')

a.to('cuda').index_put([i.to('cuda')],b.squeeze().to('cuda'),accumulate=True)
# tensor([3., 2., 1., 0.], device='cuda:0')
```

### Versions

Collecting environment information...
PyTorch version: 1.10.2
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 9.4.0
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:37)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.36.2.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-32GB
GPU 1: Tesla T4

Nvidia driver version: 510.47.03
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/targets/x86_64-linux/lib/libcudnn.so.7.6.2
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.2
/usr/local/cuda-9.2/targets/x86_64-linux/lib/libcudnn.so.7.6.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] hdtorch==0.0.0
[pip3] numpy==1.21.2
[pip3] torch==1.10.2
[pip3] torchaudio==0.10.2
[pip3] torchvision==0.11.3
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.3.1               h2bc3f7f_2  
[conda] hdtorch                   0.0.0                    pypi_0    pypi
[conda] mkl                       2021.4.0           h8d4b97c_729    conda-forge
[conda] mkl-service               2.4.0            py39h7e14d7c_0    conda-forge
[conda] mkl_fft                   1.3.1            py39h0c7bc48_1    conda-forge
[conda] mkl_random                1.2.2            py39hde0f152_0    conda-forge
[conda] numpy                     1.21.2           py39h20f2e39_0  
[conda] numpy-base                1.21.2           py39h79a1101_0  
[conda] pytorch                   1.10.2          py3.9_cuda11.3_cudnn8.2.0_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.2               py39_cu113    pytorch
[conda] torchvision               0.11.3               py39_cu113    pytorch

cc @ngimel

**Comment by ngimel** [comment] 2022-05-13 19:48
Duplicate of case 3 in #76176

**Closed by ngimel** 2022-05-13 19:48 UTC
Labels: module: cuda, triaged, module: advanced indexing
