### ISSUE TITLE
ReferenceError: weakly-referenced object no longer exists

### ISSUE THREAD

**Issue by mthrok** [pytorch/pytorch#107531] opened 2023-08-20 02:43 UTC
### 🐛 Describe the bug

TorchAudio's CI started to fail today with the following error;

```
/opt/conda/envs/ci/lib/python3.10/site-packages/torch/utils/data/dataloader.py:438: in __iter__
    return self._get_iterator()
/opt/conda/envs/ci/lib/python3.10/site-packages/torch/utils/data/dataloader.py:386: in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
/opt/conda/envs/ci/lib/python3.10/site-packages/torch/utils/data/dataloader.py:1010: in __init__
    super().__init__(loader)
/opt/conda/envs/ci/lib/python3.10/site-packages/torch/utils/data/dataloader.py:616: in __init__
    for g in _utils.worker._non_default_cpu_generators():
/opt/conda/envs/ci/lib/python3.10/site-packages/torch/utils/data/_utils/worker.py:344: in _non_default_cpu_generators
    return {
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

.0 = <list_iterator object at 0x7f88fe69b250>

    return {
        o for o in gc.get_objects()
>       if isinstance(o, torch.Generator) and
        o is not torch.random.default_generator and
        # We can't handle CUDA generators as the CUDA context may not be initialized.
        o.device.type == "cpu"
    }
E   ReferenceError: weakly-referenced object no longer exists
```

This is the test

https://github.com/pytorch/audio/blob/c5939616ddc17093747e896db6012b1f63792627/test/torchaudio_unittest/sox_effect/dataset_test.py#L112C1-L124C59

You can run it by installing nightly builds and cloning the repo and running the following command from the root directory.

```bash
cd test
pytest torchaudio_unittest/sox_effect/dataset_test -k test_apply_effects_tensor
```

### Versions

https://github.com/pytorch/audio/actions/runs/5914664863

It happens on Python 3.8, 3.9, 3.10

```
2023-08-20T01:46:02.7132211Z Collecting environment information...
2023-08-20T01:46:02.7132443Z PyTorch version: 2.1.0.dev20230819
2023-08-20T01:46:02.7132638Z Is debug build: False
2023-08-20T01:46:02.7132846Z CUDA used to build PyTorch: None
2023-08-20T01:46:02.7133066Z ROCM used to build PyTorch: N/A
2023-08-20T01:46:02.7133185Z
2023-08-20T01:46:02.7133277Z OS: CentOS Linux 7 (Core) (x86_64)
2023-08-20T01:46:02.7133559Z GCC version: (GCC) 9.3.1 20200408 (Red Hat 9.3.1-2)
2023-08-20T01:46:02.7133788Z Clang version: Could not collect
2023-08-20T01:46:02.7133989Z CMake version: version 3.26.4
2023-08-20T01:46:02.7134232Z Libc version: glibc-2.17
2023-08-20T01:46:02.7134355Z
2023-08-20T01:46:02.7134570Z Python version: 3.8.17 (default, Jul 5 2023, 21:04:15) [GCC 11.2.0] (64-bit runtime)
2023-08-20T01:46:02.7134939Z Python platform: Linux-4.14.252-195.483.amzn2.x86_64-x86_64-with-glibc2.17
2023-08-20T01:46:02.7135331Z Is CUDA available: False
2023-08-20T01:46:02.7135542Z CUDA runtime version: No CUDA
2023-08-20T01:46:02.7135756Z CUDA_MODULE_LOADING set to: N/A
2023-08-20T01:46:02.7135969Z GPU models and configuration: No CUDA
2023-08-20T01:46:02.7136194Z Nvidia driver version: No CUDA
2023-08-20T01:46:02.7136397Z cuDNN version: No CUDA
2023-08-20T01:46:02.7136594Z HIP runtime version: N/A
2023-08-20T01:46:02.7136789Z MIOpen runtime version: N/A
2023-08-20T01:46:02.7137002Z Is XNNPACK available: True
2023-08-20T01:46:02.7137129Z
2023-08-20T01:46:02.7137191Z CPU:
2023-08-20T01:46:02.7137355Z Architecture: x86_64
2023-08-20T01:46:02.7137610Z CPU op-mode(s): 32-bit, 64-bit
2023-08-20T01:46:02.7137825Z Byte Order: Little Endian
2023-08-20T01:46:02.7138009Z CPU(s): 48
2023-08-20T01:46:02.7138234Z On-line CPU(s) list: 0-47
2023-08-20T01:46:02.7138435Z Thread(s) per core: 2
2023-08-20T01:46:02.7138622Z Core(s) per socket: 24
2023-08-20T01:46:02.7138817Z Socket(s): 1
2023-08-20T01:46:02.7139077Z NUMA node(s): 1
2023-08-20T01:46:02.7139266Z Vendor ID: GenuineIntel
2023-08-20T01:46:02.7139469Z CPU family: 6
2023-08-20T01:46:02.7139654Z Model: 85
2023-08-20T01:46:02.7139880Z Model name: Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
2023-08-20T01:46:02.7140117Z Stepping: 7
2023-08-20T01:46:02.7140307Z CPU MHz: 1289.915
2023-08-20T01:46:02.7140489Z BogoMIPS: 5999.98
2023-08-20T01:46:02.7140691Z Hypervisor vendor: KVM
2023-08-20T01:46:02.7140904Z Virtualization type: full
2023-08-20T01:46:02.7141094Z L1d cache: 32K
2023-08-20T01:46:02.7141283Z L1i cache: 32K
2023-08-20T01:46:02.7141474Z L2 cache: 1024K
2023-08-20T01:46:02.7141650Z L3 cache: 36608K
2023-08-20T01:46:02.7141882Z NUMA node0 CPU(s): 0-47
2023-08-20T01:46:02.7142965Z Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves ida arat pku ospke avx512_vnni
2023-08-20T01:46:02.7143669Z
2023-08-20T01:46:02.7143765Z Versions of relevant libraries:
2023-08-20T01:46:02.7143972Z [pip3] numpy==1.22.4
2023-08-20T01:46:02.7144223Z [pip3] pytorch-lightning==2.0.7
2023-08-20T01:46:02.7144432Z [pip3] torch==2.1.0.dev20230819
2023-08-20T01:46:02.7144642Z [pip3] torchaudio==2.1.0a0+5565f05
2023-08-20T01:46:02.7144855Z [pip3] torchmetrics==1.0.3
2023-08-20T01:46:02.7145071Z [conda] blas 1.0 mkl
2023-08-20T01:46:02.7145420Z [conda] cpuonly 2.0 0 pytorch-nightly
2023-08-20T01:46:02.7145687Z [conda] mkl 2023.1.0 h213fc3f_46343
2023-08-20T01:46:02.7145993Z [conda] mkl-service 2.4.0 py38h5eee18b_1
2023-08-20T01:46:02.7146255Z [conda] mkl_fft 1.3.6 py38h417a72b_1
2023-08-20T01:46:02.7146506Z [conda] mkl_random 1.2.2 py38h417a72b_1
2023-08-20T01:46:02.7146765Z [conda] numpy 1.22.4 pypi_0 pypi
2023-08-20T01:46:02.7147113Z [conda] pytorch 2.1.0.dev20230819 py3.8_cpu_0 pytorch-nightly
2023-08-20T01:46:02.7147478Z [conda] pytorch-lightning 2.0.7 pypi_0 pypi
2023-08-20T01:46:02.7147845Z [conda] pytorch-mutex 1.0 cpu pytorch-nightly
2023-08-20T01:46:02.7148245Z [conda] torchaudio 2.1.0a0+5565f05 pypi_0 pypi
2023-08-20T01:46:02.7148527Z [conda] torchmetrics 1.0.3 pypi_0 pypi
```

cc @ezyang @gchanan @zou3519 @SsnL @VitalyFedyunin @ejguan @dzhulgakov @albanD

**Comment by albanD** [comment] 2023-08-23 16:14
This is caused by https://github.com/pytorch/pytorch/pull/107131 cc @NicolasHug 
We need to fix this before the release freeze on Friday!

**Comment by NicolasHug** [comment] 2023-08-23 16:32
I'll revert

**Comment by NicolasHug** [comment] 2023-08-23 17:10
Revert done. Thanks for the report @mthrok. The torchaudio tests should be back to green with the next nightly. I'll make sure to check those if I ever give this another try.

**Comment by albanD** [comment] 2023-08-28 17:03
Removing milestone and high pri as this was fixed in main (and was there for the branch cut).
@NicolasHug feel free to close this close this issue if you don't need it to track re-landing the PR.

**Closed** 2023-08-28 18:21 UTC
Labels: module: dataloader, triaged, module: custom-operators, module: python frontend
