### ISSUE TITLE
`torch.get_default_device()` gets error while `torch.set_default_device()` doesn't

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#126632] opened 2024-05-19 01:30 UTC
### 🐛 Describe the bug

[torch.get_default_device()](https://pytorch.org/docs/stable/generated/torch.get_default_device.html) gets error while [torch.set_default_device()](https://pytorch.org/docs/stable/generated/torch.set_default_device.html) doesn't as shown below:

```python
import torch

torch.set_default_device(device='cuda:0')
torch.get_default_device() # Error
```

> AttributeError: module 'torch' has no attribute 'get_default_device'

### Versions

```python
import torch

torch.__version__ # 2.2.1+cu121
```

**Comment by spzala** [comment] 2024-05-19 02:16
@hyperkai hello, with the latest `main` (`torch.__version__` 2.4.0a0+git7899034), I couldn't reproduce the error. I get the output `cuda:0` when `print(torch.get_default_device())` Please verify and if you are okay, we can close this issue. Thanks!

**Comment by hyperkai** [comment] 2024-05-19 07:52
Thanks @spzala. I upgraded PyTorch from `2.2.1+cu121` to `2.3.0`, then [torch.get_default_device()](https://pytorch.org/docs/stable/generated/torch.get_default_device.html) works as shown below:

```python
import torch

torch.set_default_device(device='cuda:0')
torch.get_default_device() # device(type='cuda', index=0)

torch.__version__ # 2.3.0
```

**Comment by drisspg** [comment] 2024-05-20 16:30
I am going to close this since it looks like it was solved on newer versions of pytorch

**Closed by drisspg** 2024-05-20 16:30 UTC

**Comment by spzala** [comment] 2024-05-20 16:37
Thanks for the quick reply and verifying with the newer version @hyperkai !! @drisspg sounds good to me, thank you!!
