### ISSUE TITLE
pip install does not work for LTS (1.8) - wheel index page might be broken

### ISSUE THREAD

**Issue by Julien-Moussou** [pytorch/pytorch#72579] opened 2022-02-09 10:42 UTC
## Issue description

The "install pytorch" section of the main page (https://pytorch.org/) proposes commands to install pytorch. When I select the following options:

- Pytorch build: LTS (1.8.2)
- Your OS: Windows
- Package: Pip
- Language: Python
- Compute platform: CPU

... then the installation command is given as

```
pip3 install torch==1.8.2+cpu torchvision==0.9.2+cpu torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
```

But that does not work:
```
> pip3 install torch==1.8.2+cpu torchvision==0.9.2+cpu torchaudio===0.8.2 -f https://download.pytorch.org/whl/lts/1.8/torch_lts.html
Looking in links: https://download.pytorch.org/whl/lts/1.8/torch_lts.html
DEPRECATION: The HTML index page being used (https://download.pytorch.org/whl/lts/1.8/torch_lts.html) is not a proper HTML 5 document. This is in violation of PEP 503 which requires these pages to be well-formed HTML 5 documents. Please reach out to the owners of 
this index page, and ask them to update this index page to a valid HTML 5 document. pip 22.2 will enforce this behaviour change. Discussion can be found at https://github.com/pypa/pip/issues/10825
ERROR: Could not find a version that satisfies the requirement torch==1.8.2+cpu (from versions: none)
ERROR: No matching distribution found for torch==1.8.2+cpu
```

Ignore the PEP 503 deprecation issue, which is already addressed in other issues, see for instance [that comment](https://github.com/pytorch/pytorch/issues/72045#issuecomment-1025177329).

On the other hand, I can install the Nightly build just fine with `pip3 install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html`.

## Possible explanation

I _believe_ the issue is that page https://download.pytorch.org/whl/lts/1.8/torch_lts.html is not well-formatted. The links to wheels for `torch`  are given with text `{compute-platform}/torch-{somestuff}.whl` and target `https://download.pytorch.org/whl/lts/1.8/{compute-platform}/torch-{somestuff}.whl)`, where {compute-platform} is one of "cpu", "cu101" etc. and {somestuff} includes library version and OS/environment. (Similar thing for `torchvision`.)

That possibly screws up whatever parsing pip does - if pip is looking for a link text of the form `torch-{somestuff}.whl`, then `cpu/torch-{somestuff}.whl` does not fit the bill.

The solution would then be to split the index pages between computing platforms: instead of https://download.pytorch.org/whl/lts/1.8/torch_lts.html, have the command-generator script point to https://download.pytorch.org/whl/lts/1.8/cpu/torch_lts.html, https://download.pytorch.org/whl/lts/1.8/cu102/torch_lts.html (I just realized those pages actually exist). That is the setup for the Nightly builds index page (https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html vs. https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html etc.), which I can install just fine.

## System Info

- How you installed PyTorch (conda, pip, source): pip
- OS: Win10>
- PyTorch version: None (trying to install)
- Python version: 3.9
- CUDA/cuDNN version: None

**Comment by EricZLou** [comment] 2022-02-10 00:52
+1!

**Comment by bdhirsh** [comment] 2022-02-10 02:48
This looks like a duplicate of https://github.com/pytorch/pytorch/issues/72571

**Comment by seemethere** [comment] 2022-02-10 03:19
Closing in favor of https://github.com/pytorch/pytorch/issues/72045 in order to keep the conversation in the same place

**Closed by seemethere** 2022-02-10 03:19 UTC
