### ISSUE TITLE
dist docs need an urgent serious update

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60754] opened 2021-06-25 17:01 UTC
## 📚 Documentation

https://pytorch.org/docs/stable/distributed.html goes:

> Launch utility
> 
> The torch.distributed package also provides a launch utility in torch.distributed.launch. This helper utility can be used to launch multiple processes per node for distributed training.
> 
> torch.distributed.launch is a module that spawns up multiple distributed training processes on each of the training nodes.
> 
> NOTE: This module is deprecated, use torch.distributed.run.

why is the deprecated Launch utility doc hasn't been updated with what is supposed to be used now? this is the main dist doc - seriously?

why is there no link to the new way - "use torch.distributed.run" - no link, no explanation :(

why is there no document explaining how to transition from `torch.distributed.launch` to `torch.distributed.run`?

if I try to switch from `launch` to `run` a very basic program fails, as it no longer sets `--local_rank` like it did with `launch`, where is the updated code on how one needs to write their dist programs? It's nowhere to be found on https://pytorch.org/docs/stable/elastic/run.html

Thank you.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by zhaojuanmao** [comment] 2021-06-25 22:10
cc @cbalioglu

**Comment by kiukchung** [comment] 2021-06-26 03:03
fwiw the details on writing dist programs for torch.distributed.run (aka training script) is documented here: https://pytorch.org/docs/stable/elastic/train_script.html

I’ll go ahead and update the distributed docs so that there are proper links to torch.distributed.run

**Comment by stas00** [comment] 2021-06-26 03:44
> fwiw the details on writing dist programs for torch.distributed.run (aka training script) is documented here: https://pytorch.org/docs/stable/elastic/train_script.html

Great! Thank you!

That page too too needs to be corrected, 

1. it should say: 

> If you were parsing local rank by parsing the --local_rank option, you need to get the local rank from the environment variable LOCAL_RANK (e.g. int(os.environ["LOCAL_RANK"])).

i.e. it's missing `int` - can't be a string.

2.

>rdzv_backend and rdzv_endpoint must be provided. For most users this will be set to c10d

"must" probably needs to be modified to something else, since the defaults take care of it. So it doesn't have to be provided.

Perhaps:

> rdzv_backend and rdzv_endpoint can be configured. If they aren't configured the default values of c10d will be used.

3. 

It also should say that a new (to `launch` users) `--max_restarts` flag with default value of 3 is forced on the users. And to be back-compatible it should be manually set to 0.

Elastic, IMHO, is not designed for a common user with a common use. Honestly I can't imagine why a normal user will want an auto-restart in the first place and do that 3 times. Surely the elastic library was written for very advanced uses, and I propose that the default will be set to 0. Since for most users when the training fails it's because something is wrong with their code.

At the very least it could have some logic that it restarts if the script failed after say 5min. When it restarts 3 times on instant failure, because something is broken in the script, this is madness. Please think about the logic - the current one makes little sense.

-------------------

So the big question is this: how is a library that has no idea how it will be invoked is supposed to know whether it's invoked with `run` or `launch` and work-around accordingly? HF transformers has to support much older pytorch, so we can't change to the new way, but have to support both.

Please document the answer to this question too.

Thank you!

**Comment by kiukchung** [comment] 2021-06-26 05:42
thanks for the suggestions + corrections, I'll make sure to incorporate them into the doc update. Generally speaking besides `--local_rank` expectations (which we plan to deprecate in favor of reading `LOCAL_RANK` from env vars) the scripts that are compatible with `torch.distributed.launch` should also work with `torch.distributed.run`. 

`torch.distributed.run` supports more "types" of scripts and launcher args in that you can specify `--nnodes=min:max` (for elasticity), mess with rendezvous settings and implementations. But scripts that have been working with `torch.distributed.launch` should continue working with `torch.distributed.run`.

That said, you've pointed out certain regressions (both functional and logging) in :

https://github.com/pytorch/pytorch/issues/60716
https://github.com/pytorch/pytorch/issues/60717
https://github.com/pytorch/pytorch/issues/60752

My thought is that once we address these, scripts should not have to discern which launcher it was launched from. So for HF transformers that have to support older scripts that cannot change and rely on `--local_rank` we'd have to:

1. continue supporting torch.distributed.launch (probably remove the deprecation message then, but we'd still print the warning message around wanting scripts to switch over to reading LOCAL_RANK from an env var)
2. and document the differences between launch and run and when you should chose to run with one vs the other.

**Comment by stas00** [comment] 2021-06-26 05:49
Thank you for taking care of these, @kiukchung 

I think at HF `transformers` and `accelerate` we will find a way to work around that and support both version, as long as we can find a programmatical way to do both, so there needs to be a way to eventually drop the dependency on  `torch.distributed.launch`.

so we would have to check `--local_rank` and if it's not supplied use the env var (probably more vice-versa).

That's why I suggested that there should be an item 3 added to your list above - and it's a guide for transitioning and perhaps another guide (4) on how to write a library that will support both `launch` and `run` - I'm sure it shouldn't be too complicated, but it'd be nice to have written to avoid hidden requirements and culprits.

Thank you!

**Comment by kiukchung** [comment] 2021-06-26 05:55
Makes sense, and thanks again for the suggestions/corrections and for providing context on how HF uses `torch.distributed.launch`. Will definitely incorporate these into the doc update!

**Comment by kiukchung** [comment] 2021-07-12 20:35
Many of the fixes have landed on master now. I see that the nightly docs have been updated accordingly:

1. torch.distributed.launch - https://pytorch.org/docs/master/distributed.html#launch-utility
2. torch.distributed.run - https://pytorch.org/docs/master/elastic/run.html#launcher-api

The one pending change is ensuring that `torch.distributed.launch` sets `--nprocs_per_node=1` by default. We will be fixing this today (will link the PR here so that we have it all in one place).

I've also been informed by our release team that these changes will roll out as part of the planned 1.10 release. cc) @jspisak.

**Comment by stas00** [comment] 2021-07-13 21:36
Thank you for the fixes, @kiukchung!

> I've also been informed by our release team that these changes will roll out as part of the planned 1.10 release. cc) @jspisak.

so no 1.9.1, right?

**Comment by kiukchung** [comment] 2021-07-13 21:39
Correct no plans for 1.9.1 as of now.

**Comment by kiukchung** [comment] 2021-08-30 20:47
Looks like 1.9.1 will happen after all. Tagged with 1.9.1 milestone. Closing.

**Closed by kiukchung** 2021-08-30 20:47 UTC
Labels: high priority, triage review, oncall: distributed
