### ISSUE TITLE
Travis Build Error: Cannot import _C.so file

### ISSUE THREAD

**Issue by varunagrawal** [pytorch/pytorch#2669] opened 2017-09-08 00:22 UTC
It seems that the `_C.*.so` shared object file is not being built correctly and this is leading to build errors on Travis.

```
Running JIT tests
Traceback (most recent call last):
  File "test_jit.py", line 1, in <module>
    import torch
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/torch/__init__.py", line 53, in <module>
    from torch._C import *
ImportError: /home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/torch/_C.so: undefined symbol: _ZN4thpp8THTensorIcEC1EP13THLongStorageS3_
```

**Comment by soumith** [comment] 2017-09-08 00:51
this is weird, i saw this intermittently on travis as well. But couldn't reproduce on subsequent builds on Travis or locally.

**Comment by varunagrawal** [comment] 2017-09-08 01:07
I ran a clean build on the latest commit locally just now and I can't reproduce it either. Is it that CCACHE is preserving some build files and those are interfering with subsequent builds?

**Comment by varunagrawal** [comment] 2017-09-08 01:14
Actually, I apologize, I am able to reproduce. Importing torch in an ipython shell gives the same issue.

**Comment by DuinoDu** [comment] 2017-09-08 12:52
I meet the same problem. I am using the newest version "commit 459cc5a346e25200eca1b921729d10363fac2b1b". And I checked all dependent libraries of _C.so, all of them are available. Any advices are welcome. Much thanks.

**Comment by ezyang** [comment] 2017-09-08 14:20
I have reproduced something similar. It seems to only happen when you do `python setup.py install`.

**Comment by varunagrawal** [comment] 2017-09-09 04:38
It also happens when you do `python setup.py build develop`

**Comment by soumith** [comment] 2017-09-09 05:00
Varun, i cant reproduce this. What's your OS version and python version?

**Comment by Pongroc** [comment] 2017-09-09 07:12
I have met the same problem as is mentioned above. I'm using Ubuntu 16.04.3 and Anaconda python 2.7.13.

**Comment by varunagrawal** [comment] 2017-09-09 16:58
Ubuntu 16.04.2
Python 3.6.2
Cuda 8.0

**Comment by soumith** [comment] 2017-09-09 17:32
@varunagrawal one last thing, what's your gcc version, and did you do python setup.py clean, or clone a fresh new folder

**Comment by varunagrawal** [comment] 2017-09-09 20:16
`gcc (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 2016060`

I did a `setup.py clean`, but am running it again to make sure.

**Comment by varunagrawal** [comment] 2017-09-09 22:02
On definitively running `setup.py clean`, I am not getting the error.

**Comment by soumith** [comment] 2017-09-11 12:54
thanks everyone, should be fixed on master now.

**Closed** 2017-09-11 12:53 UTC
