### ISSUE TITLE
Unsupported ONNX data type: INT64 (7)

### ISSUE THREAD

**Issue by GuanLianzheng** [pytorch/pytorch#19598] opened 2019-04-23 02:25 UTC
## Unsupported ONNX data type: INT64 (7)

I export a onnx for Bert, but when I use it by TensorRT onnx parser, it report this error.
So who can tell me if onnx support int64 data type (torch.LongTensor)?

**Comment by billpku** [comment] 2019-04-26 03:44
@GuanLianzheng 
Hi,
I also plan to transformer pytorch  BERT model into ONNX.
But I get problem when trying to use torch.onnx.export function.

First, I use 'hunggieface bert' run_classifier.py to train a text classifier with sentence length 512 and class num is 2.

Then I load the model again, setting a dummy_input like this:
dummy_input = torch.zeros(3,1,max_sentence_len).type(torch.LongTensor)
I set  this input ,because BERT take 3 inpute embedding, the inpute_token_embedding, segmentataion_embedding, mark_words_embedding, each one is based on the length of the sentence

At last, I transformer the model to ONNX by this:
torch.onnx.export(model, dummy_input, "bert.onnx",verbose=True)

Unfortunately, I came across error below:
'RuntimeError: number of dims don't match in permute'

Could you give me some hints on how to set dummy_input for BERT model?
Or how you set dummpy_input for the  torch.onnx.expprt() ?

Thank you.

**Comment by GuanLianzheng** [comment] 2019-04-26 04:12
@billpku 
I have finished pytorch Bert model to onnx.
Firstly, Bert Model has 3 inputs, so you should make 3 dummy_inputs. Then use a tuple to put these to torch,onnx.export() function.

For example:
`
dummy_input0 = torch.LongTensor(Batch_size, seg_length).to(torch.device("cuda"))
dummy_input1 = torch.LongTensor(Batch_size, seg_length).to(torch.device("cuda"))
dummy_input2 = torch.LongTensor(Batch_size, seg_length).to(torch.device("cuda"))
torch.onnx.export(model. (dummy_input0, dummy_input1, dummy_input2), filepath)
`

**Comment by houseroad** [comment] 2019-04-26 05:45
Yes, onnx does support LongTensor. https://github.com/onnx/onnx/blob/master/onnx/onnx.proto#L316

@GuanLianzheng do you have other question?

**Comment by billpku** [comment] 2019-04-26 13:50
> @billpku
> I have finished pytorch Bert model to onnx.
> Firstly, Bert Model has 3 inputs, so you should make 3 dummy_inputs. Then use a tuple to put these to torch,onnx.export() function.
> 
> For example:
> 
> dummy_input0 = torch.LongTensor(Batch_size, seg_length).to(torch.device("cuda"))
> dummy_input1 = torch.LongTensor(Batch_size, seg_length).to(torch.device("cuda"))
> dummy_input2 = torch.LongTensor(Batch_size, seg_length).to(torch.device("cuda"))
> torch.onnx.export(model. (dummy_input0, dummy_input1, dummy_input2), filepath)

Thank you @GuanLianzheng 
Your suggestion works like a charm!
Anyway, I will add more info from my practice, hope that it will help others:
1. About Apex
I am using pytorch==1.0.0, and I also install apex for training enhanced, please uninstall apex before you transform model to ONNX, or you  will get some error

2. About loading pytorch model
Before transform model to ONNX, we need to load pytorch BERT model which we trained before, remember not to set model = nn.DataParallel(model), or you will get some error

Next step, I will have a try to transform ONNX to tensorRT to see if I can reproduce the 'INT64 ' problem.

**Comment by GuanLianzheng** [comment] 2019-04-27 02:03
Thank you @houseroad
I find the error because TensorRT doesn't support INT64.
Bert Model use Embeddings ,so inputs must be LongTensor(int64).
I solve it by putting Embeddings out model. Put the first input and the second input into Embeddings, and we will get the result data of Embeddings. Then, put it and the third input to model.
But it will get some error about Double. I set model to float32, it can solve this question.
Finally, when I use TensorRT to transform ONNX to TensorRT, it prints some errors, I don't know how to solve this problem.

Number of errors : 1
File of the error : builtin_op_importers.cpp
Description of error : Assertion failed: dims.nbDims == 3
Line where the error occurred : 1238
Error code : UNSUPPORTED_NODE
Func where the error occurred : importMatMul
Node of the error : 2

Can you help me?

**Comment by GuanLianzheng** [comment] 2019-04-29 04:04
Hi, @billpku do you complete Bert to TensorRT?

**Comment by houseroad** [comment] 2019-04-29 17:17
@GuanLianzheng sorry, I am not a TensorRT expert. Seems PyTorch ONNX exporter work without problem. Probably you can reach out to Nvidia/TensorRT folks, they should be able to help.

**Comment by maeotaku** [comment] 2019-06-06 02:36
@GuanLianzheng did you fix this problem? It seems any model that uses pytroch embedding definition wont work with TRT :/

**Comment by GuanLianzheng** [comment] 2019-06-06 02:42
> @GuanLianzheng did you fix this problem? It seems any model that uses pytroch embedding definition wont work with TRT :/
I think so, I put embedding outside the model. And put the result of embedding into the model, as input data.

**Comment by maeotaku** [comment] 2019-06-06 02:52
> > @GuanLianzheng did you fix this problem? It seems any model that uses pytroch embedding definition wont work with TRT :/
> > I think so, I put embedding outside the model. And put the result of embedding into the model, as input data.

Thx! Were you using the BERT pytorch version by any change? if so, did it work after moving out the embeddings?
Im guessing the embedding data you had to cast it to int32. Did you face issues related to precision loss?

**Comment by GuanLianzheng** [comment] 2019-06-06 02:57
> > > @GuanLianzheng did you fix this problem? It seems any model that uses pytroch embedding definition wont work with TRT :/
> > > I think so, I put embedding outside the model. And put the result of embedding into the model, as input data.
> 
> Thx! Were you using the BERT pytorch version by any change? if so, did it work after moving out the embeddings?
> Im guessing the embedding data you had to cast it to int32. Did you face issues related to precision loss?

I find the error because TensorRT doesn't support INT64.
Bert Model use Embeddings ,so inputs must be LongTensor(int64).
I solve it by putting Embeddings out model. Put the first input and the second input into Embeddings, and we will get the result data of Embeddings. Then, put it and the third input to model.
But it will get some error about Double. I set model to float32, it can solve this question.
Finally, when I use TensorRT to transform ONNX to TensorRT, it prints some errors, I don't know how to solve this problem.

Number of errors : 1
File of the error : builtin_op_importers.cpp
Description of error : Assertion failed: dims.nbDims == 3
Line where the error occurred : 1238
Error code : UNSUPPORTED_NODE
Func where the error occurred : importMatMul
Node of the error : 2

I can't solve this problem. If you solve this, please tell me how to do. Thank you!

**Comment by jbmaxwell** [comment] 2019-07-10 16:12
I'm using the PyTorch implementation found here (https://github.com/codertimo/BERT-pytorch), but I'm hitting an error in the TransformerBlock: 
```
    def forward(self, x, mask):
        x = self.input_sublayer(x, lambda _x: self.attention.forward(_x, _x, _x, mask=mask)) // <-- Error!
        x = self.output_sublayer(x, self.feed_forward)
        return self.dropout(x)
```
It fails with `builtins.ValueError: Auto nesting doesn't know how to process an input object of type bert_pytorch.model.transformer.TransformerBlock.forward.<locals>.<lambda>. Accepted types: Tensors, or lists/tuples of them`, which I'm assuming is caused by the lambda. Has anyone hit a problem like this? Any workarounds?
BTW, I'm not using huggingface because I need to train it myself (on a music representation!).

I've also posted to stackoverflow, in case anyone with a solution wants some upvotes!

https://stackoverflow.com/questions/56962116/bert-pytorch-to-onnx-conversion-lambda-error

**Comment by garymm** [comment] 2021-11-19 23:27
Seems this is an issue with TensorRT not torch.onnx. Closing.

**Closed by garymm** 2021-11-19 23:27 UTC
Labels: module: onnx, triaged
