### ISSUE TITLE
Mask+Index Assignment Broken

### ISSUE THREAD

**Issue by half-potato** [pytorch/pytorch#80155] opened 2022-06-23 18:24 UTC
### 🐛 Describe the bug

I want to perform advanced indexing to set the value of a channel on a masked image. However, applying the mask before the index causes a silent failed assignment. Applying the index before the mask results in a success.
```
>>> import torch
>>> a = torch.rand(5, 3) > 0.2
>>> b = torch.zeros((5, 3, 2))
>>> b[a][:, 0] = 1
>>> b[a][:, 0]
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
>>> b[a, 0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: The shape of the mask [5, 3] at index 1 does not match the shape of the indexed tensor [5, 2] at index 1
>>> b[..., 0][a] = 1
>>> b[a][:, 0]
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

### Versions

Tested on 2 different machines.

Python 3.7.11 (default, Jul 27 2021, 14:32:16) [GCC 7.5.0] :: Anaconda, Inc. on linux
torch.__version__: '1.10.2'

Python 3.7.13 (default, Mar 29 2022, 02:18:16)  [GCC 7.5.0] :: Anaconda, Inc. on linux
torch.__version__: '1.11.0'

Python 3.10.4 (main, Mar 31 2022, 08:41:55) [GCC 7.5.0] on linux
torch.__version__: '1.13.0.dev20220622'

**Comment by ngimel** [comment] 2022-06-26 06:18
This is expected behavior, `b[a]` returns a new tensor (not a view into the current one), `b[a][:, 0] = 1` assigns value to this intermediate `b[a]` tensor, and `b[a]` is destroyed at the end of this line as there's no reference to it. 
This is a duplicate of a few other issues, not a bug and won't be fixed.

**Closed by ngimel** 2022-06-26 06:18 UTC
Labels: triaged, module: advanced indexing
