### ISSUE TITLE
intel mkl not in use / single thread on macOS

### ISSUE THREAD

**Issue by kmzzhang** [pytorch/pytorch#27419] opened 2019-10-05 07:18 UTC
## 🐛 Bug

CPU usage tops at 100% when running models on macOS

## To Reproduce

```
>>> import torch
>>> torch.get_num_threads()
1
>>> torch.torch.set_num_threads(4)
>>> torch.get_num_threads()
1
>>> import mkl
>>> mkl.get_max_threads()
4
```
Intel MKL allows 4 threads but cannot make torch go multithreaded.

Environment variables are set as
```
export MKL_NUM_THREADS=4
export OMP_NUM_THREADS=4
```
## Expected behavior

CPU usage > 100% and torch.get_num_threads()>1

## Environment

```

 - PyTorch Version (e.g., 1.0): 1.2.0
 - OS (e.g., Linux): macOS
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7.0
 - CUDA/cuDNN version: NA
 - GPU models and configuration: NA
 - Any other relevant information: Quad core CPU MacBook pro

```

## Additional context

Also tried to manually reinstall intel MKL with no avail.

**Comment by kmzzhang** [comment] 2019-10-06 23:52
This is solved by reinstalling torch with conda instead of pip. Would be helpful if an explanation could be given on the difference.

**Comment by soumith** [comment] 2019-10-07 06:00
duplicate of https://github.com/pytorch/pytorch/issues/18996 and will be fixed in upcoming release

**Closed by soumith** 2019-10-07 06:00 UTC
