### ISSUE TITLE
test_multiprocessing.py RuntimeError: unable to open shared memory object in read-write mode

### ISSUE THREAD

**Issue by zaferarican** [pytorch/pytorch#2706] opened 2017-09-12 09:32 UTC
macOS 10.12.6
CUDA 9.0rc
CUDNN 7.0 for CUDA 9.0rc
Python 3.6 (anaconda)
Xcode 8.3.3
Apple LLVM version 8.1.0 (clang-802.0.42)

Pytorch built fine with latest update. 

When running test_multiprocessing.py (python test_multiprocessing.py), I got the following error and it hanged (actually not proceeded anymore. I did Control +C to quit)

> s.sEsssss.E.Traceback (most recent call last):
>   File "/anaconda/lib/python3.6/multiprocessing/queues.py", line 241, in _feed
>     obj = _ForkingPickler.dumps(obj)
>   File "/anaconda/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
>   File "/anaconda/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 108, in reduce_storage
>     metadata = storage._share_filename_()
> RuntimeError: unable to open shared memory object </torch_547_2991312382> in read-write mode at /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/TH/THAllocator.c:230
> FEs.Traceback (most recent call last):
>   File "/anaconda/lib/python3.6/multiprocessing/queues.py", line 241, in _feed
>     obj = _ForkingPickler.dumps(obj)
>   File "/anaconda/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
>     cls(buf, protocol).dump(obj)
>   File "/anaconda/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 108, in reduce_storage
>     metadata = storage._share_filename_()
> **RuntimeError: unable to open shared memory object </torch_547_2991312382> in read-write mode at /Users/zafer/deeplearning/buildenv/pytorch/torch/lib/TH/THAllocator.c:230**
>

**Comment by bobwan1995** [comment] 2017-10-13 08:11
Do you solve the problem? I meet the same problem with you when the batch size is larger than 64 when using multiprocessing.

**Comment by MiaoDragon** [comment] 2017-11-08 03:43
I got the same problem here. I'm now trying to pass numpy array instead of Tensor to see if it works.

**Comment by MiaoDragon** [comment] 2017-11-08 04:48
Hi! Have you tried using semaphore for this problem? I think it might be a problem of synchronisation.

**Comment by PkuRainBow** [comment] 2018-01-25 06:08
![default](https://user-images.githubusercontent.com/4639578/35373395-27d3e050-01d9-11e8-82fb-f6d2951256c6.png)

Could any one help me about this problem?

**Comment by cc786537662** [comment] 2018-04-23 09:09
@PkuRainBow  hi, i got the same error when i set my num_workers in dataloader in 16,when i set it to 8,it works,and it seems caused by memory issue?

**Comment by lqyiii** [comment] 2018-12-04 07:08
@zaferarican @bobwan1995  i met the problem too,  do you solve the problem?

**Comment by 666xiaohei666** [comment] 2019-05-06 06:39
i met the problem too, do you solve the problem?

**Comment by 666xiaohei666** [comment] 2019-05-06 07:06
> ![default](https://user-images.githubusercontent.com/4639578/35373395-27d3e050-01d9-11e8-82fb-f6d2951256c6.png)
> 
> Could any one help me about this problem?

i met the problem too, do you solve the problem?

**Comment by lqyiii** [comment] 2019-05-06 07:25
i did not solve it , i guess that it is a bug of pytorch

**Comment by 666xiaohei666** [comment] 2019-05-06 08:12
https://github.com/huaweicloud/dls-example/issues/26
This help me,hope it can help you.




------------------ 原始邮件 ------------------
发件人: "lqyiii"<notifications@github.com>;
发送时间: 2019年5月6日(星期一) 下午3:26
收件人: "pytorch/pytorch"<pytorch@noreply.github.com>;
抄送: "568245360"<568245360@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [pytorch/pytorch] test_multiprocessing.py RuntimeError: unable toopen shared memory object in read-write mode (#2706)




i did not solve it , i guess that it is a bug of pytorch

**Comment by fzwqq** [comment] 2021-03-22 11:54
![image](https://user-images.githubusercontent.com/12872935/111985912-364f3980-8b48-11eb-9422-5f439e1f9eb2.png)
the same. 
what's the problem?

**Comment by Chuck-Yu** [comment] 2021-04-14 01:59
```shell
ulimit -a
ulimit -SHn 51200
```

**Comment by mruberry** [comment] 2021-08-29 23:15
Closing this issue due to age. If you're still experiencing this problem on a current version of PyTorch please reopen it, @zaferarican.

**Closed by mruberry** 2021-08-29 23:15 UTC
Labels: module: multiprocessing, module: tests, triaged
