### ISSUE TITLE
JIT makes model run x14 times slower in pytorch nightly

### ISSUE THREAD

**Issue by IgnacioJPickering** [pytorch/pytorch#52286] opened 2021-02-15 23:53 UTC
## 🐛 Bug

JITed model runs ~ x14 slower for its first ~ 20 evaluations in pytorch nightly, with respect to stable torch, 1.7.1

## To Reproduce

Run the following code in pytorch:

```
import torch
import time

class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):

        idx0 = torch.triu_indices(x.shape[1], x.shape[1], 1, device=x.device)
        pair = x.index_select(1, idx0.flatten()).view(x.shape[0], 2, -1, 3)
        dist = (pair[:, 0, ...] - pair[:, 1, ...]).norm(2, -1)
        idx1, idx2 = (dist <= 5.0).nonzero().unbind(1)
        idx1 = (idx0[:, idx2] + idx1 * x.shape[1]) 
        return idx1

device = torch.device('cuda')
m = TestModule().to(device)
m = torch.jit.script(m)
times = []

for j in range(20):
    x = torch.randn(1, 1000, 3).to(device) * 5.0

    start = time.time()
    torch.cuda.synchronize()

    _ = m(x)

    torch.cuda.synchronize()
    end = time.time()

    times.append(end - start)

print(f'{sum(times)/20} s')
```

in stable torch, in my system this takes  ~ 0.0083 s
in nightly torch, in my system this takes ~ 0.1332 s

Not JIT compiling the model makes the issue disappear.

## Expected behavior

JIT compilation should not reduce the performance of the model x14 for the first ~ 20 evaluations

## Environment

```
PyTorch version: 1.8.0.dev20210208+cu110
Is debug build: False
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.2.142
GPU models and configuration: GPU 0: Quadro RTX 6000
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] pytorch-memlab==0.2.2
[pip3] torch==1.8.0.dev20210208+cu110
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch-memlab            0.2.2                    pypi_0    pypi
[conda] torch                     1.8.0.dev20210208+cu110          pypi_0    pypi
```

## Additional context

I also reproduced this problem on nightly pytorch +cu92, running on a GeForce GTX 1080 Ti, with cuda driver 410.93

The code attached is semantically not very meaningful because I found this issue when running a fairly big model (~1000 lines of code) and the issue is compounded if I run the whole model, which makes the speed be x100 slower instead of x14 slower. Since I can't share the whole model I'm sharing this snippet which still seems to present the problem.

Making small modifications to the code snippet seems to make the performance penalty go away or at least be extremely reduced. For example, not multiplying the last line by `x.shape[1]` seems to get rid of the issue somhow, due to this I could not reduce the code further. I hope this is enough to reproduce and pinpoint the problem.
 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @brianjo @mruberry @gmagogsfm

**Comment by ngimel** [comment] 2021-02-16 01:55
Probably the reason for regression is that the shapes of the arguments are different for each iteration, which leads for a lot of recompilations. Try `torch._C._jit_set_bailout_depth(1)` to disable recompilation. 
High priority, as this is a large regression with defaults. Also high priority for documenting jit options (_jit_set_bailout_depth is undocumented).

**Comment by IgnacioJPickering** [comment] 2021-02-17 14:46
@ngimel `torch._C._jit_set_bailout_depth(1)` works well.

**Comment by jeromepatel** [comment] 2021-02-20 19:23
Hello, this is my first issue in PyTorch, can anyone guide me through an approach for solving this issue?

**Comment by Krovatkin** [comment] 2021-02-24 17:21
@IgnacioJPickering this looks indeed like a respecialization issue where we keep respecializing on complete tensor shapes until we hit the bailout depth (`_jit_set_bailout_depth`) with our ProfilingExecutor. We have been in discussions on how to better address this issue.
You could set `torch._C._jit_set_profiling_mode(False)` to disable the profiling executor or you could continue using `torch._C._jit_set_bailout_depth(1)`.

nightly JIT dump:
We keep respecializing on the shapes for `add` and `mul`:
https://gitlab.com/-/snippets/2081466

1.7.1 JIT dump:
shape is stable:
https://gitlab.com/-/snippets/2081472

**Comment by IgnacioJPickering** [comment] 2021-03-30 15:45
@Krovatkin Is there a way to bypass this in LibTorch without performance penalty? 

When loading a jit-scripted model from LibTorch  I have to disable profiling mode and texpr fuser as so:

```
  torch::jit::getProfilingMode() = false;                                                                                                             
  torch::jit::setTensorExprFuserEnabled(false);
```
but this has as a consequence a measurable performance penalty for my model with respect to the same model run directly in python. 
If **don't disable** these things then I have the same issue as in python, the first couple of iterations of the code are extremely slow, and unfortunately for my use case in some scenarios the model has to run with very large inputs, this makes the first couple of iterations take ~ 20 min sometimes. 

I currently have to choose weather to disable these optimizations and get hit with a performance penalty or allow the model to run extremely slowly for about 20 min. 

I suppose if I could set a bailout depth for libtorch I could bypass this issue, if this is not exposed right now maybe I could do a feature request.

**Comment by Krovatkin** [comment] 2021-03-30 17:58
@IgnacioJPickering 

Please, try

```cpp
#include <torch/csrc/jit/runtime/graph_executor.h>
torch::jit::getBailoutDepth() = 1;
```

**Comment by hgaiser** [comment] 2021-10-01 10:28
I'm running into a similar (maybe the same?) issue. I'm pretty sure I didn't have this issue in older versions of pytorch (pre 1.9.0). Without anything other than a torchvision retinanet model, converted to TorchScript, I get the following timings (forward pass in seconds) :

```
0.8029475212097168
0.32103800773620605
4.649818658828735
1.3163681030273438
0.029468059539794922
0.029541492462158203
0.029392480850219727
0.029961109161376953
0.029831647872924805
0.029504776000976562
0.029404401779174805
0.02970743179321289
0.02419877052307129
0.02255392074584961
0.02232837677001953
0.02244710922241211
0.02251887321472168
0.022424697875976562
0.02228260040283203
0.0223846435546875
0.02234029769897461
0.022953271865844727
0.022504568099975586
0.0225527286529541
0.023122072219848633
0.022552967071533203
0.022416114807128906
0.022455692291259766
0.022420406341552734
0.02243804931640625
0.02236199378967285
0.02243208885192871
0.02235555648803711
0.022435426712036133
0.022344112396240234
0.02243494987487793
0.02268218994140625
0.022035598754882812
0.02329397201538086
0.21356987953186035
0.20972204208374023
0.20908451080322266
0.20904755592346191
0.20871186256408691
0.2086780071258545
0.21153855323791504
0.20898127555847168
0.20852351188659668
0.03012394905090332
0.2269883155822754
0.030081748962402344
0.02982616424560547
0.02945566177368164
0.02938532829284668
0.22143793106079102
0.030416488647460938
0.029991865158081055
0.029781341552734375
0.02596426010131836
0.02489638328552246
```

Note the long processing time of the third image and the occasional longer processing time (roughly 10x slower) further along.

After some digging and testing, it seems that setting `torch._C._jit_set_profiling_executor(False)`, or equivalently setting the environment flag `TORCH_JIT_DISABLE_NEW_EXECUTOR=1`, I get the following timing:

```
1.0489234924316406
0.03160405158996582
0.031049728393554688
0.030988693237304688
0.030852317810058594
0.030902624130249023
0.03085470199584961
0.026110172271728516
0.024726390838623047
0.024410486221313477
0.024540185928344727
0.02442169189453125
0.0243990421295166
0.02436685562133789
0.024297237396240234
0.024382352828979492
0.0243222713470459
0.024276018142700195
0.024275779724121094
```

Note that the timings are much more consistent, albeit 2msec slower than the "fast" forward passes I had before. I don't know exactly what this "new" executor does, or how it differs from the "old" executor. It seems it does find some new optimizations, but at the cost of unpredictable timings.

Interesting to note is that I added `torch.jit.freeze` and `torch.jit.optimize_for_inference` as an additional test case. After adding these optimizations, the difference in timing is less than 1msec in the best cases, but the "new" executor is still sometimes roughly 10x slower.

**Comment by ezyang** [comment] 2021-10-04 02:43
cc @bertmaher

**Comment by bertmaher** [comment] 2021-10-04 14:14
Unfortunately this is a consequence of the new executor's choice to profile static shapes for the first 20 runs, before giving up.  You can see the compilation log by setting `PYTORCH_JIT_LOG_LEVEL=kernel` in the environment, and sure enough:
```
TensorExprKernel graph:
graph(%0 : Long(2, 39804, strides=[39804, 1], requires_grad=0, device=cuda:0),
      %idx1.1 : Long(39804, strides=[1], requires_grad=0, device=cuda:0),
      %2 : int):
  %3 : int = prim::Constant[value=1]()
  %4 : Long(39804, strides=[1], requires_grad=0, device=cuda:0) = aten::mul(%idx1.1, %2)
  %idx1.6 : Long(2, 39804, strides=[39804, 1], requires_grad=0, device=cuda:0) = aten::add(%0, %4, %3)
  return (%idx1.6)
TensorExprKernel graph:
graph(%0 : Long(2, 41602, strides=[41602, 1], requires_grad=0, device=cuda:0),
      %idx1.1 : Long(41602, strides=[1], requires_grad=0, device=cuda:0),
      %2 : int):
  %3 : int = prim::Constant[value=1]()
  %4 : Long(41602, strides=[1], requires_grad=0, device=cuda:0) = aten::mul(%idx1.1, %2)
  %idx1.7 : Long(2, 41602, strides=[41602, 1], requires_grad=0, device=cuda:0) = aten::add(%0, %4, %3)
  return (%idx1.7)
...
```

There's not a quick fix for this other than disabling the new executor.  @eellison might have some more info.

**Comment by eellison** [comment] 2021-10-04 21:58
A quick fix as well would be to use NVFuser instead of NNC. 
```
with torch.jit.fuser("fuser2"):
    scripted_model(...)
```

**Comment by hgaiser** [comment] 2021-10-07 13:19
I had to read up a bit on what a fuser is, but I see that conceptually they are optimization methods to 'fuse' operations together.

> A quick fix as well would be to use NVFuser instead of NNC.
> 
> ```
> with torch.jit.fuser("fuser2"):
>     scripted_model(...)
> ```

I tried your suggested quick fix. I couldn't run my previous test with `'fuser2'` for some reason (`RuntimeError: Cannot process input tensor without concrete number of dimensions.`) , but I ran "vanilla" COCO trained [RetinaNet](https://pytorch.org/vision/stable/models.html#id36) from torchvision.

The results are similar, but less severe. All tests have 10 black images as warmup, followed by 100 images taken from a camera. I show only the first 30 timings (10 warmup, 20 images) here for keeping things brief.

`fuser0`:
```
0.8141684532165527
0.3574798107147217
0.39315199851989746
0.13810396194458008
0.14111661911010742
0.1437983512878418
0.14154839515686035
0.13474726676940918
0.13788533210754395
0.1368100643157959
0.14231467247009277
0.12852215766906738
0.12970757484436035
0.12920141220092773
0.12031245231628418
0.10700607299804688
0.10682797431945801
0.10767960548400879
0.11117410659790039
0.12232232093811035
0.778123140335083
0.05173540115356445
0.05205845832824707
0.05185294151306152
0.0518183708190918
0.050576210021972656
0.05250239372253418
0.05196261405944824
0.05232667922973633
0.05225515365600586

```

After the first 21 images, the timings are quite consistent.

`fuser1`:
```
0.8140759468078613
0.7378966808319092
4.323630332946777
1.140568733215332
0.05633831024169922
0.05215191841125488
0.0452723503112793
0.04268932342529297
0.04398775100708008
0.042792558670043945
0.8333735466003418
0.8337554931640625
1.2232770919799805
1.2372713088989258
0.845618724822998
0.8388209342956543
0.8402013778686523
0.8434081077575684
0.44599175453186035
0.05387616157531738
0.05477547645568848
0.0472865104675293
0.04860424995422363
0.04750657081604004
0.048249006271362305
0.04760599136352539
0.04902029037475586
0.0473780632019043
0.04907488822937012
0.04771232604980469

```

After the first 19 images, the timings are quite consistent and a little bit faster than with `fuser0`. The third image (a black warmup image) always takes approximately 4 seconds. Not sure why this is. I noticed similar things with my custom model.

`fuser2`:
```
0.8105454444885254
0.3531055450439453
0.7597460746765137
0.17841863632202148
0.06977629661560059
0.06708049774169922
0.06607890129089355
0.0637354850769043
0.05921316146850586
0.05984950065612793
0.4675114154815674
/usr/lib/python3.9/site-packages/torch/nn/modules/module.py:1051: UserWarning: FALLBACK path is taken. This is an indication that codegenFailed for some reason. To debug try disable codegen fallback pathvia setting the env variable`export PYTORCH_CUDA_FUSER_DISABLE_FALLBACK=1` (Triggered internally at  /build/python-pytorch/src/pytorch-1.9.1-opt-cuda/torch/csrc/jit/codegen/cuda/manager.cpp:267.)
  return forward_call(*input, **kwargs)
0.06256604194641113
0.061629533767700195
0.06202411651611328
0.061949729919433594
0.06157112121582031
0.06261682510375977
0.06172919273376465
0.06228446960449219
0.06217670440673828
0.06276464462280273
0.0614933967590332
0.062093257904052734
0.0617828369140625
0.06200122833251953
0.061897993087768555
0.0626368522644043
0.061476945877075195

```

After the warmup, when objects in images are first introduced, a warning is generated claiming that the `FALLBACK` path is taken. No clue what this means exactly, but presumably it means optimization did not work successfully. Other than that, the timings are slower than both `fuser0` and `fuser1`.

To summarize my findings + questions:
- All timing issues using the "vanilla" retinanet model happens in the first ~20 runs. After that, timing is consistent. Based on what @bertmaher said, I'm assuming this is when the executor is profiling / optimizing the TorchScript model.
- For some reason, my custom model (using `fuser1`, the default) also has unexpected timings *after* 20 runs. Check [here](https://github.com/pytorch/pytorch/issues/52286#issuecomment-932111291) for the timings from my custom model. I don't have an explanation for why this happens, but it must be in the executor, since disabling the "new" executor fixes the issue. The model was converted quite a while ago (torch 1.6 I believe), maybe that could be an issue? I don't have the resources at the moment to generate a new TorchScript model from the original though, so I can't test that.
- I'm using TorchScript for production, I prefer it doesn't optimize anymore after it's deployed. Is there an option to optimize the TorchScript model and then store the optimized version, so that in the future optimizations are not needed? Can I simply save the TorchScript model after having used it for 20+ runs, so that it is optimized, then load it in production and disable optimization there? Would this work?

**Comment by navahgar** [comment] 2022-01-21 18:27
This slowdown goes away completely with the dynamic shape fusion that landed recently. In fact, with this feature, the fused version is significantly faster than the unfused version.

For the original test reported at the start of the issue (excluding warmup runs from timing):
```
current master w/ fuser  : 0.14231414794921876 s
current master w/o fuser : 0.00136241912841796 s

w/ dynamic shape fuser   : 0.00029482841491699 s
```

Note that the dynamic shape fusion is not turned on by default yet. Here is the flag to control it: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/tensorexpr_fuser.cpp#L33. 

I'm in the process of adding a python API for this flag as well: https://github.com/pytorch/pytorch/pull/71612

**Comment by navahgar** [comment] 2022-01-21 21:03
Actually, we already have a python API for this: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/python/init.cpp#L832

**Comment by MaxTranced** [comment] 2022-03-06 15:30
> Actually, we already have a python API for this:

@navahgar What do you mean to say when you say "for this"? You mean that the dynamic shape fusion can be turned on using that API? Is that documented? What version of PyTorch is it available from?

**Comment by navahgar** [comment] 2022-03-07 18:32
Here is the API I was referring to.
Python API: https://github.com/pytorch/pytorch/blob/master/torch%2Fcsrc%2Fjit%2Fpython%2Finit.cpp#L661
C++ API + documentation: https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/api/module.h#L304-L341.

It is available on master and should be part of the 1.11 release.

**Closed by navahgar** 2022-03-07 18:32 UTC
Labels: high priority, triage review, oncall: jit, module: docs, NNC

**Comment by MaxTranced** [comment] 2022-03-08 09:19
Thank you for the answer @navahgar! The C++ API comment really helps! I hope that in the future the defaults will be OK for most cases and that the options will be documented more comprehensively.
In the meantime for my project I will use an explicit warmup step with more than 20 hardcoded requests.

**Comment by wahlberg82** [comment] 2022-04-21 06:21
Hi,
I have an image processing application, where these type of optimizations doesn't make sense because the end user will not run big batches of images but rather one offs. So I have earlier used the "fix" mentioned above:
`#include <torch/csrc/jit/runtime/graph_executor.h>
torch::jit::getBailoutDepth() = 1;`
That has been working great for my use case, using pytorch 1.7.

I have recently updated my application's back end to use pytorch 1.11 because of other reasons. The fix above doesn't compile anymore, but is giving my the following error:
`(path removed).cpp:639:35: error: lvalue required as left operand of assignment
   torch::jit::getBailoutDepth() = 0;
`
I understand these parts in pytorch have changed a lot with the new fuser, executor and such. I first tried tweaking the settings using:
`torch::jit::FusionStrategy bailout = { {torch::jit::FusionBehavior::STATIC, 0}, {torch::jit::FusionBehavior::DYNAMIC, 0} };
torch::jit::setFusionStrategy(bailout);`

It's better speed wise than not tweaking the settings, but still not as fast as the old way of setting bail out to 0. So I'm trying to do that but with pytorch 1.11:
`
FLAGS_torch_jit_enable_new_executor = false; // Get back to the old fuser/executor type in pytorch. This line works!
FLAGS_torch_jit_bailout_depth = 0; // This doesn't work, don't understand why
FLAGS_torch_jit_num_profiled_runs = 0; // This doesn't work, don't understand why
`

The lines above give me this compile error:
`
(path removed).cpp:643:3: error: ‘FLAGS_torch_jit_bailout_depth’ was not declared in this scope
   FLAGS_torch_jit_bailout_depth = 0; // And set the bailout to 0
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(path removed).cpp:643:3: note: suggested alternative: ‘FLAGS_torch_jit_enable_new_executor’
   FLAGS_torch_jit_bailout_depth = 0; // And set the bailout to 0
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   FLAGS_torch_jit_enable_new_executor
(path removed).cpp:644:3: error: ‘FLAGS_torch_jit_num_profiled_runs’ was not declared in this scope
   FLAGS_torch_jit_num_profiled_runs = 0; // And turn off profile runs as well
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
(path removed).cpp:644:3: note: suggested alternative: ‘FLAGS_torch_jit_enable_new_executor’
   FLAGS_torch_jit_num_profiled_runs = 0; // And turn off profile runs as well
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   FLAGS_torch_jit_enable_new_executor
`
I've been looking at the source code, and I don't understand why the first flag to change to the old executor works, but that the other two flags don't seem to be exposed?

I even tried defining those two constants myself:
`C10_DEFINE_int64(
    torch_jit_num_profiled_runs,
    0,
    "Number of profiling runs");
C10_DEFINE_int64(
    torch_jit_bailout_depth,
    0,
    "Number of re-specializations");
`
But this results in a linker error like so:
`(path removed)/libtorch_cpu.a(profiling_graph_executor_impl.cpp.o):(.data+0x10): multiple definition of `FLAGS_torch_jit_bailout_depth'
(path removed).cpp.o:(.bss+0x30): first defined here
(path removed)/libtorch_cpu.a(profiling_graph_executor_impl.cpp.o):(.data+0x18): multiple definition of `FLAGS_torch_jit_num_profiled_runs'
(path removed).cpp.o:(.bss+0x40): first defined here
(path removed)/libtorch_cpu.a(profiling_graph_executor_impl.cpp.o):(.bss+0x1): multiple definition of `c10::g_C10FlagsRegistry_torch_jit_num_profiled_runs'
(path removed).cpp.o:(.bss+0x38): first defined here
(path removed)/libtorch_cpu.a(profiling_graph_executor_impl.cpp.o):(.bss+0x0): multiple definition of `c10::g_C10FlagsRegistry_torch_jit_bailout_depth'
(path removed).cpp.o:(.bss+0x28): first defined here`

Can somebody help me set the bailout depth to 0 for the old school executor, but in modern pytorch1.11? Maybe @navahgar ?

Thanks in advance!
All the best, David

**Comment by navahgar** [comment] 2022-04-21 16:43
Setting the `FusionStrategy` to what you did should ensure that no fusions happen. May be there is still some profiling happening. I'm not sure about that. @eellison Can you help answer this?

**Comment by eellison** [comment] 2022-04-21 16:45
Hi, @wahlberg, you want to use the api `setFusionStrategy` instead of declaring the variable twice. See https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/api/module.h#L350

**Comment by eellison** [comment] 2022-04-21 16:54
If you do:

`torch::jit::setFusionStrategy({torch::jit::FusionBehavior::STATIC, 0})` that should work! If it doesn't, please file a separate issue and we'll take a look.

**Comment by wahlberg82** [comment] 2022-04-21 20:04
Thanks for the responses!
OK, I've done some more testing and it turns out I'm getting similar performance on the first run using either:
`torch::jit::setGraphExecutorOptimize(false);
torch::jit::FusionStrategy static0 = { {torch::jit::FusionBehavior::STATIC, 0} };
torch::jit::setFusionStrategy(static0);
`
or
`FLAGS_torch_jit_enable_new_executor = false;`

I'm going to stick with the first, since that makes more sense to me.

I tried running the code `torch::jit::setGraphExecutorOptimize(false)` by itself though, and that was 25% slower than having the "STATIC, 0" FusionStrategy. It doesn't seem to do any difference really. I guess I leave it in anyway.

The reason why I wrote here was that I thought this line `FLAGS_torch_jit_enable_new_executor = false;` switched to the old executor that still respected the bailoutdepth constant. I can still see it's there in the code, line 49 in https://github.com/pytorch/pytorch/blob/orig/release/1.11/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp
I guess I'm wrong about it's use though. :)

Final question to close this subject for me:
What about kDefaultNumProfiledRuns? (line 48 in https://github.com/pytorch/pytorch/blob/orig/release/1.11/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp)
Does the `torch::jit::setGraphExecutorOptimize(false)` turn that profiledruns off as well?

Thanks again!
David

**Comment by venabled** [comment] 2022-04-26 17:07
> @IgnacioJPickering
> 
> Please, try
> 
> ```c++
> #include <torch/csrc/jit/runtime/graph_executor.h>
> torch::jit::getBailoutDepth() = 1;
> ```

For reference, in the detectron2 deployment example, I get an issue with that assignment (gcc10, cuda toolkit 11.6):

```
/home/venabled/source/detectron2/tools/deploy/torchscript_mask_rcnn.cpp:138:30: error: lvalue required as left operand of assignment
  138 |   torch::jit::getBailoutDepth() = 1;

```

**Comment by wahlberg82** [comment] 2022-04-30 20:25
Maybe my last question got kind of drowned in the long thread, so I'll post it again:

Final question to close this subject for me:
What about kDefaultNumProfiledRuns? (line 48 in https://github.com/pytorch/pytorch/blob/orig/release/1.11/torch/csrc/jit/runtime/profiling_graph_executor_impl.cpp)
Does the torch::jit::setGraphExecutorOptimize(false) turn that profiledruns off as well?

Cheers,
David

**Comment by eellison** [comment] 2022-05-09 19:19
@wahlberg82, yes it does

**Comment by snakers4** [comment] 2022-06-17 07:13
We encountered this problem when migrating from PyTorch `1.9` to `1.10` in our production environment.

**Some further info for people who will be googling for solutions and for maintainers:**

- All of this refers mostly to CPU version, though larger models have this behavior sometimes even on GPU;
- The "warmup" problem used to be noticeable only in large models with MHA modules and rotary embeddings, starting from `1.6` or `1.7`;
- Typically from 20 to 50 audio samples or texts were required for a warmup (for TTS and STT);
- The problem became really noticeable only when migrating to `1.10` on CPU, before that some rudimentary warmup was required, but not really noticeable;
- `torch._C._jit_set_bailout_depth(1)` or `torch._C._jit_set_profiling_mode(False)` helped for small STT models;
- For TTS models warmup is still required (this is model speed vs. number of audios generated):

   ![image](https://user-images.githubusercontent.com/12515440/174245351-3ec76a4e-5340-4def-ac8d-9d295ce6df5b.png)

P.S.

Looks like a 1% problem (quite complex, heavily optimized models with variable sized inputs), but probably this should described in the docs somewhere (did not find it there, please correct me).

**Comment by yaadhavraajagility** [comment] 2022-07-20 22:39
> > @IgnacioJPickering
> > Please, try
> > ```c++
> > #include <torch/csrc/jit/runtime/graph_executor.h>
> > torch::jit::getBailoutDepth() = 1;
> > ```
> 
> For reference, in the detectron2 deployment example, I get an issue with that assignment (gcc10, cuda toolkit 11.6):
> 
> ```
> /home/venabled/source/detectron2/tools/deploy/torchscript_mask_rcnn.cpp:138:30: error: lvalue required as left operand of assignment
>   138 |   torch::jit::getBailoutDepth() = 1;
> ```

Did you fix this?

**Comment by ppwwyyxx** [comment] 2022-07-20 23:59
>  torch::jit::getBailoutDepth() = 1;

This was fixed in https://github.com/facebookresearch/detectron2/commit/728ee8b0cfe045301a2ca479354b2fb969390e8e

**Comment by westfly** [comment] 2022-09-05 09:19
> ## 🐛 Bug
> JITed model runs ~ x14 slower for its first ~ 20 evaluations in pytorch nightly, with respect to stable torch, 1.7.1
> 
> ## To Reproduce
> Run the following code in pytorch:
> 
> ```
> import torch
> import time
> 
> class TestModule(torch.nn.Module):
>     def __init__(self):
>         super().__init__()
> 
>     def forward(self, x):
> 
>         idx0 = torch.triu_indices(x.shape[1], x.shape[1], 1, device=x.device)
>         pair = x.index_select(1, idx0.flatten()).view(x.shape[0], 2, -1, 3)
>         dist = (pair[:, 0, ...] - pair[:, 1, ...]).norm(2, -1)
>         idx1, idx2 = (dist <= 5.0).nonzero().unbind(1)
>         idx1 = (idx0[:, idx2] + idx1 * x.shape[1]) 
>         return idx1
> 
> device = torch.device('cuda')
> m = TestModule().to(device)
> m = torch.jit.script(m)
> times = []
> 
> for j in range(20):
>     x = torch.randn(1, 1000, 3).to(device) * 5.0
> 
>     start = time.time()
>     torch.cuda.synchronize()
> 
>     _ = m(x)
> 
>     torch.cuda.synchronize()
>     end = time.time()
> 
>     times.append(end - start)
> 
> print(f'{sum(times)/20} s')
> ```
> 
> in stable torch, in my system this takes ~ 0.0083 s in nightly torch, in my system this takes ~ 0.1332 s
> 
> Not JIT compiling the model makes the issue disappear.
> 
> ## Expected behavior
> JIT compilation should not reduce the performance of the model x14 for the first ~ 20 evaluations
> 
> ## Environment
> ```
> PyTorch version: 1.8.0.dev20210208+cu110
> Is debug build: False
> CUDA used to build PyTorch: 11.0
> ROCM used to build PyTorch: N/A
> 
> OS: Ubuntu 20.04.2 LTS (x86_64)
> GCC version: (Ubuntu 8.4.0-3ubuntu2) 8.4.0
> Clang version: 10.0.0-4ubuntu1 
> CMake version: version 3.16.3
> 
> Python version: 3.7 (64-bit runtime)
> Is CUDA available: True
> CUDA runtime version: 11.2.142
> GPU models and configuration: GPU 0: Quadro RTX 6000
> Nvidia driver version: 460.32.03
> cuDNN version: Could not collect
> HIP runtime version: N/A
> MIOpen runtime version: N/A
> 
> Versions of relevant libraries:
> [pip3] numpy==1.18.1
> [pip3] pytorch-memlab==0.2.2
> [pip3] torch==1.8.0.dev20210208+cu110
> [conda] blas                      1.0                         mkl  
> [conda] cudatoolkit               11.0.221             h6bb024c_0  
> [conda] mkl                       2020.1                      217  
> [conda] mkl-service               2.3.0            py37he8ac12f_0  
> [conda] mkl_fft                   1.2.0            py37h23d657b_0  
> [conda] mkl_random                1.1.1            py37h0573a6f_0  
> [conda] numpy                     1.18.1                   pypi_0    pypi
> [conda] numpy-base                1.19.2           py37hfa32c7d_0  
> [conda] pytorch-memlab            0.2.2                    pypi_0    pypi
> [conda] torch                     1.8.0.dev20210208+cu110          pypi_0    pypi
> ```
> 
> ## Additional context
> I also reproduced this problem on nightly pytorch +cu92, running on a GeForce GTX 1080 Ti, with cuda driver 410.93
> 
> The code attached is semantically not very meaningful because I found this issue when running a fairly big model (~1000 lines of code) and the issue is compounded if I run the whole model, which makes the speed be x100 slower instead of x14 slower. Since I can't share the whole model I'm sharing this snippet which still seems to present the problem.
> 
> Making small modifications to the code snippet seems to make the performance penalty go away or at least be extremely reduced. For example, not multiplying the last line by `x.shape[1]` seems to get rid of the issue somhow, due to this I could not reduce the code further. I hope this is enough to reproduce and pinpoint the problem.
> 
> cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @brianjo @mruberry @gmagogsfm

reproduce on my env
```shell
## 1.12
+ python python/perf.py
0.04357835054397583 s
##1.8.2 lts
+ python python/perf.py
0.17461243867874146 s
```
