### ISSUE TITLE
"import torch" failed

### ISSUE THREAD

**Issue by Luxios** [pytorch/pytorch#1618] opened 2017-05-23 04:47 UTC
I installed pytorch and torchvision using pip on alpine container, then it gave the following error.

python3.5.2 
ImportError: Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /usr/
lib/python3.5/site-packages/torch/_C.cpython-35m-x86_64-linux-gnu.so)

ipython 
ImportError: Error relocating /usr/lib/python3.5/site-packages/torch/lib/libcudnn.so.6: __strtod_internal:
 symbol not found

**Comment by soumith** [comment] 2017-05-23 04:54
Looks like libcudnn.so.6 (NVIDIA
s CuDNN library) links against glibc. 
Alpine provides musl as it's standard library, which misses the symbol __strtod_internal which is glibc specific.
I am not sure what to do here other than try to page nvidia folks. cc: @ngimel to alert appropriate folks.

The first error: `ImportError: Error loading shared library ld-linux-x86-64.so.2` seems to be an issue with your python installation and not pytorch itself.

Since either of these errors are not in our scope of fixing (1st is your python install, 2nd is a NVIDIA CuDNN issue, and CuDNN is a blackbox), I'll tag these as dependency bugs and close the issue.
If you do not plan to use GPUs, then you can install PyTorch from source on your machine without installing CUDA or CuDNN and it'll work for you. Instructions are here: https://github.com/pytorch/pytorch#from-source

**Closed by soumith** 2017-05-23 04:54 UTC
Labels: dependency bug

**Comment by ngimel** [comment] 2017-05-25 20:04
Got an answer from cudnn that alpine is not supported and won't be supported.

**Comment by shabazbpatel** [comment] 2017-08-16 06:55
You can use this [Dockerfile](https://github.com/pytorch/pytorch/blob/master/Dockerfile). This is built over ubuntu. You can also try using [datmo](https://datmo.com) in order setup environment and track machine learning projects for making models reproducible.
