### ISSUE TITLE
module.register_backward_hook Doesn't Work

### ISSUE THREAD

**Issue by Wuyxin** [pytorch/pytorch#38951] opened 2020-05-23 09:09 UTC
Hi, I have implemented a network GN and I need to change grad_input according to grad_out in some activation layers. So, I used **module.register_backward_hook** for some modules in Exp.model.named_children(). Strangely, when **“output[target].backward(retain_graph = True);input.grad”** took the derivative of ouput w.r.t inputs, the program can not print "finally"(in function hook_fn_backward), **which means although I have successfully hooked hook_fn_backward to the modules(it has been verified), this backward mechanism doesn't work at all.**

I wonder what's going on here, 
many thanks!
```
class Exp(Explainer):

    def __init__(self, graph, Model, activation_input, activation_output, path):
        super(Exp, self).__init__(graph, Model, path)
        
         # Rescale rules for activation
        def hook_fn_backward(module, grad_input, grad_output):
            print("finally")
            delta_out = self.delta_y.pop()
            delta_in = self.delta_x.pop()
            
            is_near_zero = torch.tensor(np.where(np.array(delta_in.detach()) > self.NEAR_ZERO_THRESHOLD, 1.0, 0.0))
            far_from_zero = 1.0 - is_near_zero
            
            # just to prevent delta_x from being near zero
            grads = [None for _ in grad_input]
            grads[0] = (is_near_zero * grad_input[0] + far_from_zero*grad_output[0]* (delta_out / delta_in) ).float()
            
            return tuple(grads)
            
        self.NEAR_ZERO_THRESHOLD = 1e-4
        self.act_in = activation_input
        self.act_out = activation_output
        modules = self.model.named_children()
        for name, module in modules:
            print(module._backward_hooks)
            if module.__class__.__name__ in ['ReLU', 'Sigmoid', 'Tanh']:
                module.register_backward_hook(hook_fn_backward)
            print(module._backward_hooks)
```

```
class GN(torch.nn.Module):
    
    def __init__(self):
        super(GN, self).__init__()
        
        # edge nn
        self.add_module('edge_linear1', Lin(in_features = 2, out_features = 4))
        self.add_module('edge_ReLU', nn.ReLU())
        self.add_module('edge_linear2', Lin(in_features = 4, out_features = 8 * 8))
        
        # node encoder
        self.add_module('node_linear', Lin(in_features = 4, out_features = 8))
        self.add_module('node_ReLU', nn.ReLU())
        
        self.conv = NNConv(in_channels = 8, out_channels = 8, 
                           nn = Seq(self.edge_linear1, self.edge_ReLU, self.edge_linear2))
        
        #node_readout
        self.add_module('node_ReLU1', nn.ReLU())
        self.add_module('node_linear1', Lin(in_features = 8, out_features = 4))
        self.add_module('node_ReLU2', nn.ReLU())
        self.add_module('node_linear2', Lin(in_features = 4, out_features = 1))
        
        
    def forward(self, graph):
        
        self.edge_index = graph.edge_index
        self.node_attr = Variable(graph.x, requires_grad=True)
        self.edge_attr = Variable(graph.edge_attr, requires_grad=True)
        
        x = self.node_ReLU(self.node_linear(self.node_attr))
        x = self.node_ReLU1(self.conv(x, self.edge_index, self.edge_attr))
        x = self.node_ReLU2(self.node_linear1(x))
        
        self.readout = self.node_linear2(x)
        return self.readout
```

cc @ezyang @SsnL @albanD @zou3519 @gqchen @mruberry

**Comment by ezyang** [comment] 2020-05-26 18:22
Hi, do you think this is the same thing as https://github.com/pytorch/pytorch/issues/598 ?

**Comment by albanD** [comment] 2020-05-26 18:54
Hi,

As you can see in the doc, the [register_backward_hook](https://pytorch.org/docs/stable/nn.html#torch.nn.Module.register_backward_hook) function is not very reliable right now.

But what is most likely happening here is that you put the hooks on different modules from the ones that you use during the forward.
Can you give a small code sample that we can run that reproduces this (with random data as input).

**Comment by Wuyxin** [comment] 2020-05-27 01:51
@albanD 
Oh yes, you're right. I simply add
```
# forward once after assigning hook
self.model(self.graph)
```
before 
```
output[target].backward(retain_graph = True)
print(input.grad)
```
and it works!
However, I still wonder what the forward process  is to do with the model's backward process？
 In detail, self.model is **created and forward once in Explainer**(Exp's parent class), and then I **put the hooks** on modules of self.model  **in Exp.__init__**, after that, output propagates backward in Exp.explain. In this process, the model remains unchanged, so why would it happend?
Maybe I still don't understand what's the meaning of "put the hooks on different modules from the ones that you use during the forward.".

**Comment by Wuyxin** [comment] 2020-05-27 01:54
@ezyang 
it seems to be a different question.

**Comment by albanD** [comment] 2020-05-27 11:51
The hooks are triggered when the forward pass happens. So if you forward first then add the hooks, they won't be used.

I'm going to close this as it is not a bug/feature request. Don't hesitate to send any follow-up questions on the forum: https://discuss.pytorch.org/

**Closed by albanD** 2020-05-27 11:51 UTC
Labels: module: autograd, module: nn, triaged
