### ISSUE TITLE
Error Message is misleading while installing torch from PyPI in 32-bit Python environment

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#50535] opened 2021-01-14 14:01 UTC
## 🐛 Bug

Due to the legacy torch packages in pyPI, error message is not friendly while install torch from pyPI in python 32 bit environment

## To Reproduce

In windows python 32bit environment, if we run pip install torch, it would try to install 0.1.2.post2.tar.gz

![image](https://user-images.githubusercontent.com/16190118/104599408-ac4fa400-56b2-11eb-9665-7d629156526b.png)

## Expected behavior
We should remove the legacy  torch 0.1.2, 0.1.2.post1, 0.1.2post2 from PyPI.
The error message should like the result with conda. It means we have no package for 32bit environment.
![image](https://user-images.githubusercontent.com/16190118/104600311-c938a700-56b3-11eb-88d6-e0871fe23366.png)

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by albanD** [comment] 2021-01-15 14:43
Keeping this on instead of the original issue https://github.com/pytorch/pytorch/issues/40511 as this one has more details.

**Comment by peterjc123** [comment] 2021-01-15 16:03
I don't think removing the packages is the right thing to do, given the fact that some mirrors that may not probably remove the cached packages. Instead, is it better to publish a stub binary package for win32? Or maybe we could publish a slightly newer package (e.g. 0.1.3) that prints better message.

**Comment by seemethere** [comment] 2021-01-28 22:52
The `0.1.2.post2` package has been yanked from PyPI and is only installable now if you include the version in your install command.

Can you try to `pip install torch` now and see what type of error it gives you?

**Comment by mszhanyi** [comment] 2021-01-28 23:54
The result is
![image](https://user-images.githubusercontent.com/16190118/106213254-3c3f3300-6207-11eb-87a1-6f4b272c488f.png)

**Comment by rgommers** [comment] 2021-11-09 11:37
> Instead, is it better to publish a stub binary package for win32?

That would help, but only for 32-bit Windows. Yanking is not enough here, the problem is that [PEP 592](https://www.python.org/dev/peps/pep-0592/) says: _"An installer MUST ignore yanked releases, if the selection constraints can be satisfied with a non-yanked version, and MAY refuse to use a yanked release even if it means that the request cannot be satisfied at all. "_ Because there are no newer sdists, anyone on a platform for which there are no binaries will still find the `0.1.2.post2` sdist. Such platforms include 32-bit Linux, `ppc64le`, Alpine Linux and other Musl-based distros, AIX, and so on.

Two possible solutions:
1. Delete all pre-0.3.0 releases from PyPI completely. The sdists can be moved to GitHub Releases for archival reasons.
2. Upload a dummy sdist for the latest release which immediately errors out when found with a clear error message.

**Comment by seemethere** [comment] 2021-11-15 18:00
> > Instead, is it better to publish a stub binary package for win32?
> 
> That would help, but only for 32-bit Windows. Yanking is not enough here, the problem is that [PEP 592](https://www.python.org/dev/peps/pep-0592/) says: _"An installer MUST ignore yanked releases, if the selection constraints can be satisfied with a non-yanked version, and MAY refuse to use a yanked release even if it means that the request cannot be satisfied at all. "_ Because there are no newer sdists, anyone on a platform for which there are no binaries will still find the `0.1.2.post2` sdist. Such platforms include 32-bit Linux, `ppc64le`, Alpine Linux and other Musl-based distros, AIX, and so on.
> 
> Two possible solutions:
> 
> 1. Delete all pre-0.3.0 releases from PyPI completely. The sdists can be moved to GitHub Releases for archival reasons.
> 2. Upload a dummy sdist for the latest release which immediately errors out when found with a clear error message.

0.1.2 releases have been removed (_deleted_) from PyPI as of now and @rgommers has gone ahead and uploaded the sdists from these releases to https://github.com/pytorch/pytorch/releases/tag/v0.1.2

**Comment by rgommers** [comment] 2021-11-15 18:48
When trying to install `torch` from PyPI on an unsupported platform, the installer will now report that there is no matching wheel. The error message is whatever the installer says as its default message for that. So currently for `pip` it will say:
```
No matching distribution found for torch
```
(as determined by https://github.com/pypa/pip/blob/8b0745678cccdb3a4f7370b07c1f9e99ae93dea2/src/pip/_internal/commands/index.py#L128)

For Poetry it's similar:
```
Could not find a matching version of package torch
```
(as determined by https://github.com/python-poetry/poetry/blob/70670fa42cd1e89b76d8ba8c2c3f5924973dc365/src/poetry/console/commands/init.py#L383)

Given that these are the standard messages, that seems sufficient - and doing better for all possible unsupported platforms through a custom sdist correctly is not completely trivial. So let's call this good.

One simple follow up for 32-bit Windows specifically will be to mention explicitly that that is not supported on https://pytorch.org/get-started/locally/#supported-windows-distributions. I'll open a PR for that.

**Comment by kit1980** [comment] 2022-10-04 22:48
Closing after consulting with Microsoft - no support for Windows 32-bit python.

**Closed by kit1980** 2022-10-04 22:48 UTC
Labels: oncall: binaries, module: windows, triaged
