### ISSUE TITLE
functorch.functionalize fails with exponential_ extreme behavior

### ISSUE THREAD

**Issue by alanwaketan** [pytorch/pytorch#93053] opened 2023-01-26 06:43 UTC
### 🐛 Describe the bug

Here is the PoC:
```
import torch
import functorch

# Reduced from test_torch.py: test_exponential
def poc7():
  device = 'cpu'

  test = (-0, float('inf'))
  t = torch.empty((1,), device=device, dtype=torch.bfloat16).exponential_(test[0])
  print(t.item() == test[1])


print("CPU")
poc7()
print()

print("CPU Functionalize")
functorch.functionalize(poc7)()

```

And here is the output:
```
CPU
True

CPU Functionalize
/workspaces/work/pytorch/torch/_functorch/deprecated.py:93: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.functionalize is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.func.functionalize instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  warn_deprecated('functionalize')
Traceback (most recent call last):
  File "poc7.py", line 19, in <module>
    functorch.functionalize(poc7)()
  File "/workspaces/work/pytorch/torch/_functorch/vmap.py", line 40, in fn
    return f(*args, **kwargs)
  File "/workspaces/work/pytorch/torch/_functorch/eager_transforms.py", line 1582, in wrapped
    func_outputs = func(*func_args, **func_kwargs)
  File "poc7.py", line 10, in poc7
    t = torch.empty((1,), device=device, dtype=torch.bfloat16).exponential_(test[0])
  File "/workspaces/work/pytorch/torch/_refs/__init__.py", line 432, in _fn
    return fn(a, *args, out=a, **kwargs)
  File "/workspaces/work/pytorch/torch/_prims_common/wrappers.py", line 223, in _fn
    result = fn(*args, **kwargs)
  File "/workspaces/work/pytorch/torch/_prims_common/wrappers.py", line 133, in _fn
    result = fn(**bound.arguments)
  File "/workspaces/work/pytorch/torch/_refs/__init__.py", line 5190, in exponential
    return -1 / rate * torch.log1p(-torch.rand_like(self))
ZeroDivisionError: float division by zero
```

### Versions

Nightly

CC @bdhirsh @min-jean-cho 

cc @bdhirsh @ezyang @soumith

**Comment by min-jean-cho** [comment] 2023-01-26 08:17
Thanks @alanwaketan for raising the issue. cc. @lezcano @fritzo why does  `torch.Tensor.exponential_`  check `lambda >= 0` ? `lambda` should be greater than 0. `torch.distributions.exponential.Exponential` correctly checks `lambda > 0`.

**Comment by min-jean-cho** [comment] 2023-01-26 08:23
Parameter check in exponential decomp is being added in #92709. But let's wait to align on the above.

**Comment by fritzo** [comment] 2023-01-26 16:49
@min-jean-cho 

> why does torch.Tensor.exponential_ check `lambda >= 0` ?

My guess is somebody thought the `lambd` meant the _mean_ which is a common parameterization of exponential distributions, but happens to not be the parameterization used in PyTorch.  In the mean parameterization it makes perfect sense to draw samples from a zero-mean exponential distribution: this would be equivalent to `torch.Tensor.zero_()`.  But because `torch.Tensor.exponential_` uses the reciprocal-mean as parameter, `lambd = 0` indeed does not make sense, or would be equivalent to `torch.Tensor.fill_(math.inf)` which would not be very useful.

So yes, I believe it's correct to narrow that check to `lambd > 0`.

**Comment by min-jean-cho** [comment] 2023-01-26 17:35
Thanks @fritzo for the detailed explanation. I will file a separate PR fixing `torch.Tensor.exponential_` to check `lambda > 0`.

**Comment by min-jean-cho** [comment] 2023-01-26 21:10
@fritzo, I just saw `torch.distributions.poisson.Poisson` and `torch.poisson` both check `lambda >= 0`. But `lambda` should be greater than 0 for poisson distribution as well. Exponential `lambda` originates from poisson `lambda`.

**Comment by fritzo** [comment] 2023-01-26 22:54
@min-jean-cho I do think it makes sense to allow `rate = 0` for `torch.distributions.Poisson` and `torch.poisson`.  For Poisson random variables the rate parameter is the mean, and the distribution converges to `delta(0)` as `rate -> 0`, and the density `.log_prob().exp()` is continuous and and differentiable at `rate = 0`.

**Comment by min-jean-cho** [comment] 2023-01-27 21:00
Thanks @fritzo again for the detailed explanation. I agree, it's sound for `rate = 0` with all mass at `x = 0`, this also matches `E[X] = Var[X] = rate = 0` and the distribution at its limit as `rate - > 0` as you've mentioned. So yes, let's keep `rate >= 0` check for the poisson distribution. My initial gut feeling was that, it didn't make sense intuitively to model distribution of events that never occur.

**Comment by alanwaketan** [comment] 2023-02-09 22:52
@min-jean-cho Trying to follow up to see what's the conclusion here? Should we just update the test?

**Comment by min-jean-cho** [comment] 2023-02-09 23:01
Thanks @alanwaketan, sorry for the delay. Yes, a check to validate `rate > 0` is being in #92709 here https://github.com/pytorch/pytorch/pull/92709/files#diff-0e8654681a3dcc5fe5ed434f4fc23d2a47d69421eb261371aebc8754d8de5e06R5262-R5265. The PR is ready, I will bump for review later today/tomorrow again.

**Comment by min-jean-cho** [comment] 2023-02-14 17:31
Hi @alanwaketan, the issue is fixed by #92709. We can close the issue.

**Comment by alanwaketan** [comment] 2023-02-14 19:30
> Hi @alanwaketan, the issue is fixed by #92709. We can close the issue.

Sounds good. Let me rebase and double check.

**Comment by alanwaketan** [comment] 2023-02-14 20:57
@min-jean-cho, verified it fixes the problem.

**Comment by min-jean-cho** [comment] 2023-02-14 20:58
Great, thanks for verifying @alanwaketan !

**Closed by min-jean-cho** 2023-02-14 20:58 UTC
Labels: triaged, module: functionalization
