### ISSUE TITLE
ARC runners timeout during Docker updates

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#124727] opened 2024-04-23 14:08 UTC
### 🐛 Describe the bug

I've made a few changes to files that trigger docker rebuilds and all ARC-migrated builds that depended on that change consistently timed out instead of rebuilding the docker, see https://github.com/pytorch/pytorch/actions/runs/8792008446/job/24127359804 for example

Four more examples from another PR:
- https://github.com/pytorch/pytorch/actions/runs/8785543894/job/24122332310
- https://github.com/pytorch/pytorch/actions/runs/8785543894/job/24122334812
- https://github.com/pytorch/pytorch/actions/runs/8785543894/job/24122336159
- https://github.com/pytorch/pytorch/actions/runs/8785543894/job/24122332549

### Versions

CI

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @pytorch/pytorch-dev-infra @ZainRizvi

**Comment by jeanschmidt** [comment] 2024-04-23 14:18
@malfet seems that the problem is not in the runner itself:

```
#70 201.0 + sudo -E -H -u jenkins env -u SUDO_UID -u SUDO_GID -u SUDO_COMMAND -u SUDO_USER env PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/opt/conda/envs/py_3.8/bin:/opt/conda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin LD_LIBRARY_PATH= conda run -n py_3.8 pip install --progress-bar off git+https://github.com/openai/triton@45fff310c891f5a92d55445adf8cc9d29df5841e#subdirectory=python
#70 266.2   Running command git clone --filter=blob:none --quiet https://github.com/openai/triton /tmp/pip-req-build-7cggbwil
#70 266.2   fatal: the remote end hung up unexpectedly
#70 266.2   fatal: early EOF
#70 266.2   fatal: index-pack failed
#70 266.2   error: subprocess-exited-with-error
#70 266.2   
#70 266.2   × git clone --filter=blob:none --quiet https://github.com/openai/triton /tmp/pip-req-build-7cggbwil did not run successfully.
#70 266.2   │ exit code: 128
#70 266.2   ╰─> See above for output.
#70 266.2   
#70 266.2   note: This error originates from a subprocess, and is likely not a problem with pip.
#70 266.2 error: subprocess-exited-with-error
#70 266.2 
#70 266.2 × git clone --filter=blob:none --quiet https://github.com/openai/triton /tmp/pip-req-build-7cggbwil did not run successfully.
#70 266.2 │ exit code: 128
#70 266.2 ╰─> See above for output.
#70 266.2 
#70 266.2 note: This error originates from a subprocess, and is likely not a problem with pip.
#70 266.2 
#70 266.2 ERROR conda.cli.main_run:execute(124): `conda run pip install --progress-bar off git+[https://github.com/openai/triton@45fff310c891f5a92d55445adf8cc9d29df5841e#subdirectory=python`](https://github.com/openai/triton@45fff310c891f5a92d55445adf8cc9d29df5841e#subdirectory=python%60) failed. (See above for error)
#70 266.2 Collecting git+https://github.com/openai/triton@45fff310c891f5a92d55445adf8cc9d29df5841e#subdirectory=python
#70 266.2   Cloning https://github.com/openai/triton (to revision 45fff310c891f5a92d55445adf8cc9d29df5841e) to /tmp/pip-req-build-7cggbwil
#70 266.2 
#70 ERROR: process "/bin/sh -c if [ -n \"${TRITON}\" ]; then bash ./install_triton.sh; fi" did not complete successfully: exit code: 1
```

so github is closing the connection during a git clone,

**Comment by jeanschmidt** [comment] 2024-04-23 14:19
...and I see that the 2nd run was successful: https://github.com/pytorch/pytorch/actions/runs/8792008446/job/24133923832

**Comment by jeanschmidt** [comment] 2024-04-23 14:24
but for the other ones, I see `Error: The operation was canceled.` 

What are the causes to have this error?

**Comment by jeanschmidt** [comment] 2024-04-23 14:52
I cross-checked with another successful build completed on `linux.2xlarge` and those are the times for protobuf extract and build:

OLD - 14:24 - 14:30
ARC - 15:30 - 16:14

So it seems that indeed ARC VERY is CPU underpowered OR this is because of the number of processes we use to build 

https://github.com/pytorch/pytorch/actions/runs/8785543894/job/24122332310#step:3:9167

It is using the number of available CPUs and not the CPU quota for the pod.

**Comment by zxiiro** [comment] 2024-04-23 15:13
This sounds similar to pytorch/ci-infra/issues#139 which I've been trying to track down as well. In my case it's on a specific job that always times out after 5.5 hrs in ARC runner. At first I thought maybe there wasn't enough CPUs in the ARC runner so I migrated the job to a much larger ARC runner with 16 CPUs and it didn't seem to have any effect on the build time.

I talked to @jeanschmidt on Slack and perhaps maybe the build scripts when run on ARC isn't properly picking up the number of CPUs or something. I'll try and see if I can get some data on that.

Ref: https://github.com/pytorch/pytorch-canary/actions/runs/8756146041/job/24031922752

**Comment by malfet** [comment] 2024-04-23 15:18
> @malfet seems that the problem is not in the runner itself:

@jeanschmidt I'm not saying that problem with the runners, I'm saying that ARC runner is unable to finish docker build + compile in 4 hours allotted for the job

**Comment by ZainRizvi** [comment] 2024-04-23 17:16
@malfet, @zxiiro is looking into the root cause here. Apologies for the pain here and thanks for consistently reporting these kinds of failures!

**Comment by zxiiro** [comment] 2024-04-23 20:35
I did some testing this afternoon and got some interesting data. 

A couple of things to note. `nproc` when run in a container always reports the host system's available CPU count so does not match the CPU limit set in the container. We can use `$(( $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us) / $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us) ))` to get the number of CPUs available to the running container where we limit it.

However when run inside of a docker-in-docker container it will report CPU count as 0 as our scripts do not set a cpu limit via the `docker run --cpu <num>` command.

This is unscientific but I basically compiled protobuf 3  times each using the `time` command to track how long it took. I ran the below compiles on a 64 CPU system with an arc-runner that is limited to 16 CPUs. Using the NPROC calculation I found in the protobuf script of `NPROC=$[$(nproc) - 2]`

Run on ARC runner with NPROC=62 (larger than CPUs available in container):

```
real	4m27.127s user	42m4.447s sys	2m56.273s
real	4m28.194s user	42m15.778s sys	2m57.363s
real	4m23.148s user	42m4.191s sys	2m56.683s
```

Run on ARC runner with NPROC=14 (match available CPUs):

```
real	3m32.245s user	27m17.634s sys	2m5.621s
real	3m33.660s user	27m17.620s sys	2m6.987s
real	3m34.282s user	27m19.583s sys	2m7.009s
```

So when protobuf is compiled on an ARC runner directly we can see that when setting NPROC to a higher number of CPUs than is available makes the compile time take about a minute longer than setting NPROC=14 which is 2 less than total available CPUs in that runner. So we can learn that setting an overly high NPROC value is detrimental to the compile time.

Next running the same tests inside a DIND container.

Run inside DIND container with NPROC=62 (larger than CPUs available):

```
real	2m53.021s user	42m18.015s sys	3m11.510s
real	2m51.563s user	42m12.448s sys	3m8.760s
real	2m50.972s user	42m15.448s sys	3m10.036s
```

Runs inside DIND container with NPROC=14 (match available CPUs):

```
real	3m48.066s user	27m39.297s sys	2m24.104s
real	3m47.736s user	27m38.968s sys	2m22.676s
real	3m47.021s user	27m39.542s sys	2m23.588s
```

In this case we learn that when NPROC=14 in DIND container the compile times seem to match (although slightly slower) when compiled directly on ARC. However with NPROC=62 build times is faster then all other configurations. At first this seemed strange until I realized we are not limiting CPUs in our DIND container.

See: https://github.com/pytorch/ci-infra/blob/4940394/modules/arc/runnerscaleset/dind-rootless-values.yaml#L78-L95

So this means our builds and tests are actually running inside of a dind container that has full access to the host systems CPU and Memory budgets. This means all builds sharing the same ARC host are fighting each other for resources.

I think there's 2 steps we need to take to improve things here:

1. Limit the dind docker container like we are doing for the runner container
2. Figure out a way to handle NPROC inside of a container so that it gets the right number of CPUs set for the runner

One issue with resolving the CPU / Memory limits for the dind container though would mean every arc pod would suddenly require double the CPU and Memory resources as it did before because each pod has a runner container as well as a dind container.

It would be better if we can limit the resources at the pod level rather than the container level so that we are not double allocating.

**Comment by ZainRizvi** [comment] 2024-04-23 22:01
Wow, great discoveries

To avoid having to double-allocate could we use `--cpuset-cpus` to allocate specific cores to each container?  Then we could grant the same set of cores to both the outer and inner containers.
https://www.thorsten-hans.com/docker-container-cpu-limits-explained

**Comment by zxiiro** [comment] 2024-04-25 14:48
Okay I'm not 100% sure on this but trying to understand Kubernetes resource limits (https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/) I _think_ that if we set `requests` for multiple containers in a pod, Kubernetes will allocate the sum of all CPU/Memory requests to the pod.

On the other hand limit is just a hard limit on resources the container is allowed to use and does not affect resource allocation when Kubernetes is assigning a pod to a node.

If I understand this correctly than I _think_ we just need to set requests only on the `runner` container while setting limits on both the `runner` and `dind` containers. This way the pod is allocated the right number of CPUs while ensure that both containers within the pod do not exceed that CPU limit.

**Comment by malfet** [comment] 2024-04-25 15:21
Q: Can't we replace `nrpoc` tool inside of the container with something that returns a sensible result?
IMO tuning build scripts to a specific virtualization solution feels somewhat wrong. It would be nice if the same script, with minimal notification, could  run in GitHub Actions containers, in the one PyTorch provided before ARC and in the one ARC is providing. 

As [`nproc`](https://man7.org/linux/man-pages/man1/nproc.1.html) documentation states:
> Print the number of processing units available to the current process, which may be less than the number of online processors

So it feels that container should indeed return number of processes available to it, rather the number of processors on the host.  I wonder if updating to a newer host/container OS image would update the tool to recognize cgroups constraints better

**Comment by zxiiro** [comment] 2024-04-25 16:14
Did some more testing this morning this time I set a CPU limit on the dind container to be the same as the limit on the runner container. I added the following to the dind container.

+      resources:
+        limits:
+          cpu: $(CPU)
+          memory: $(MEMORY)

The results for a run inside DIND container with NPROC=62 (larger than CPUs available) is now:

```
real	4m43.773s user	42m49.477s sys	3m12.177s
real	4m42.423s user	42m40.454s sys	3m12.467s
real	4m44.911s user	42m50.213s sys	3m10.777s
```

This is closer to what we were seeing when compiling on the runner container. So this confirms that we definitely need to set a limit on the DIND container as well so that a job is not able to access the full resources on the host system like it is now. That likely means that all job pods in ARC are all currently fighting each other for the same resources which definitely will hurt the performance of all pods on the same host.

It is important to note that we set the "limits" on BOTH the runner and dind containers to ensure they don't go over their CPU limits and only apply the "requests" config to the runner container so that we are not asking K8s to allocate the CPU/Memory resources to BOTH containers making us over allocate more resources than we intend to.

**Comment by zxiiro** [comment] 2024-04-25 16:29
> Q: Can't we replace `nrpoc` tool inside of the container with something that returns a sensible result? IMO tuning build scripts to a specific virtualization solution feels somewhat wrong. It would be nice if the same script, with minimal notification, could run in GitHub Actions containers, in the one PyTorch provided before ARC and in the one ARC is providing.
> 
> As [`nproc`](https://man7.org/linux/man-pages/man1/nproc.1.html) documentation states:
> 
> > Print the number of processing units available to the current process, which may be less than the number of online processors
> 
> So it feels that container should indeed return number of processes available to it, rather the number of processors on the host. I wonder if updating to a newer host/container OS image would update the tool to recognize cgroups constraints better

FWIW in my tests I've been using `ubuntu:latest` and the nproc provided by that seems to always report the number of CPUs on the host.

Using `echo $(( $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_quota_us) / $(cat /sys/fs/cgroup/cpu,cpuacct/cpu.cfs_period_us) ))` however seems to return the number of CPUs available to the container.

I've been searching for answers on stackoverflow and consensus seems to be that within a container we need to check `/sys/fs/cgroup/` data for this data.

I did find this one stackoverflow answer (https://stackoverflow.com/a/49153003) that seems to show that `nproc` should return the right number of CPUs inside the docker container but that wasn't my experience when I tested on our systems. Maybe it's because we have the additional complication of a Docker Daemon running inside of a Kubernetes container.

In any case I agree we need to simplify how to get this information. Either via a common_utils.sh function like `get_cpu_count()` or a tool similar to `nproc` that is able to get us accurate CPU information from both the host and containers so that we are not configuring the same custom scripts in multiple places.

**Closed** 2024-07-23 21:24 UTC
Labels: high priority, module: ci, triaged
