### ISSUE TITLE
The Bug of onnx model format exported by torch.onnx.export

### ISSUE THREAD

**Issue by kksweet8845** [pytorch/pytorch#42995] opened 2020-08-13 07:28 UTC
## 🐛 Bug

I export the MaskRCNN implemented by Detectron2 as a submodule. Trying to export it by torch.onnx.export.
After exporting successfully by torch.onnx.export, I use `onnx.check_model` to check the model, and it got the following error msg.

```
Traceback (most recent call last):
  File "export.py", line 64, in <module>
    onnx.checker.check_model(onnx_model)
  File "/media/nober_workspace/pyenv/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "325" op_type: "Constant" attribute { name: "value" s: "cpu" type: STRING }
```

# To Reproduce

### 1. The module class named `ToOnnx` defined in here
It is exported to onnx format successfully.
```
from torch import nn
import torch.utils.model_zoo as model_zoo
import torch.onnx as tonnx

from os.path import isfile, isdir, join

from detectron2.engine import DefaultPredictor
from detectron2.config import get_cfg
from detectron2 import model_zoo
import torch

from torch.onnx import ONNX_ARCHIVE_MODEL_PROTO_NAME, ExportTypes, OperatorExportTypes

class ToOnnx(nn.Module):
    def __init__(self, model_name, ckpt_dir):
        super(ToOnnx, self).__init__()
        self.model_name = model_name
        self.ckpt_dir = ckpt_dir
        self.initCfg()
        self.predictor = DefaultPredictor(self.cfg)

        self.add_module("mask_rcnn", self.predictor.model)

    def initCfg(self):
        cfg = get_cfg()
        cfg.merge_from_file(model_zoo.get_config_file(self.model_name))
        cfg.DATALOADER.NUM_WORKERS = 2
        cfg.MODEL.WEIGHTS = model_zoo.get_checkpoint_url(self.model_name)  # Let training initialize from model zoo
        cfg.SOLVER.IMS_PER_BATCH = 2
        cfg.SOLVER.BASE_LR = 0.00025  # pick a good LR
        cfg.SOLVER.MAX_ITER = 5400    # 300 iterations seems good enough for this toy dataset; you may need to train longer for a practical dataset
        cfg.MODEL.ROI_HEADS.BATCH_SIZE_PER_IMAGE = 128   # faster, and good enough for this toy dataset (default: 512)
        cfg.MODEL.ROI_HEADS.NUM_CLASSES = 4  # only has one class (ballon)

        cfg.OUTPUT_DIR = self.ckpt_dir
        cfg.MODEL.WEIGHTS = join(cfg.OUTPUT_DIR, "model_final.pth")
        cfg.MODEL.ROI_HEADS.SCORE_THRESH_TEST = 0.8   # set the testing threshold for this model

        self.cfg = cfg
        

    def exportModel(self, model, input, input_names, output_names,
    output_dir="super_resolution.onnx", version=10, dynamic_axes={}):
        def _check_eval(module):
            assert not module.training

        # model.eval()
        # print(model.training)
        # model.apply(_check_eval)
        with torch.no_grad():
            with open(output_dir, 'w') as f:
                tonnx.export(
                    model, ## Model being run
                    input,
                    "mask_rcnn.onnx",
                    verbose=False,
                    export_params=True,
                    opset_version=12,
                    do_constant_folding=True,
                    input_names=input_names,
                    output_names=output_names,
                    dynamic_axes=dynamic_axes,
                    use_external_data_format=True,
                    operator_export_type=OperatorExportTypes.ONNX_ATEN
                )


    def forward(self, original_image):

        original_image = np.asarray(original_image)

        out = self.predictor(original_image)
        predictions = out['instances'].to('cpu')
        img_height, img_width = predictions.image_size

        boxes = predictions.pred_boxes if predictions.has("pred_boxes") else None
        scores = predictions.scores if predictions.has("scores") else None
        classes = predictions.pred_classes if predictions.has("pred_classes") else None


        if predictions.has("pred_masks"):
            masks = torch.tensor(predictions.pred_masks, dtype=int).detach()
            # masks = [GenericMask(x, img_height, img_width) for x in masks]
        else:
            masks = None

        
        return {
            'pred_boxes' : boxes.tensor,
            'scores' : scores,
            'pred_classes' : classes,
            'pred_masks' : masks
        }

```

### 2. The code which the `ToOnnx` being invoked

```
    model_name = model_name = "COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_3x.yaml"
    ckpt_dirs = './output-R50_FPN-v2-10800'

    toonnx = ToOnnx(model_name, ckpt_dirs)
    toonnx.exportModel(toonnx,
                       original_image,
                       ['image'],
                       ['pred_boxes', 'scores', 'pred_classes', 'pred_masks'],
                       output_dir="./mask_rcnn.onnx",
                       dynamic_axes={
                           'image' : {
                               0 : 'C',
                               1 : 'H',
                               2 : 'W'
                           },
                           'pred_boxes' : {
                               0 : 'N'
                           },
                           'scores' : {
                               0 : 'N'
                           },
                           'pred_classes' : {
                               0 : 'N'
                           },
                           'pred_masks' : {
                               0 : 'N',
                               1 : 'H',
                               2 : 'W'
                           }

                       })
    
```
### 3. And I check the model shown as following, also the code from Pytorch tutorial.
Error occurred.
```
    onnx_model = onnx.load("mask_rcnn.onnx")
    onnx.checker.check_model(onnx_model)
```

```
Traceback (most recent call last):
  File "export.py", line 64, in <module>
    onnx.checker.check_model(onnx_model)
  File "/media/nober_workspace/pyenv/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "325" op_type: "Constant" attribute { name: "value" s: "cpu" type: STRING }
```

Environment
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.5.0

Python version: 3.6.9
Is CUDA available: Yes
CUDA runtime version: 10.2
GPU models and configuration: GPU 0: GeForce GTX 2080
Nvidia driver version: 450.57
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[pip3] onnx==1.7.0

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by kksweet8845** [comment] 2020-08-17 08:24
@kksweet8845

**Comment by spandantiwari** [comment] 2020-08-17 21:20
@kksweet8845 - where are you getting the model in: onnx_model = onnx.load("mask_rcnn.onnx")

**Comment by spandantiwari** [comment] 2020-08-19 18:44
@kksweet8845 , @chaorensx, @ShidiDaisy - can any one of your share a concise repro with all necessary files and code (including export code).

**Comment by chaorensx** [comment] 2020-08-20 11:36
**Error info:**

Traceback (most recent call last):
  File "demo/onnx_run.py", line 8, in <module>
    onnx.checker.check_model(model)
  File "/home/admin/.local/lib/python3.6/site-packages/onnx/checker.py", line 93, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Mismatched attribute type in ' : value'

==> Context: Bad node spec: output: "671" op_type: "Constant" attribute { name: "value" s: "cpu" type: STRING }

**When printed the graph,  I found a wired node:**
%741 = Constant[value = 'cpu']()

But, I can not found this node in netron when visualizing the graph.

I think the easiest way to reproduce the situation is:
1. install mmdetection
2. run tools/pytorch2onnx.py, transform the official mask rcnn network to onnx
3. check the model: onnx.checker.check_model(model)

**Comment by neginraoof** [comment] 2020-08-21 00:00
For exporting a model to ONNX, you should not set the export type to OperatorExportTypes.ONNX_ATEN.
Is there a specific reason you're using a different export type?

To try out the repro code, I added the code below to read the image:

```
input_img = osp.join(
            osp.dirname(__file__), '../tests/data/color.jpg')
original_image = mmcv.imread(input_img)
original_image = torch.from_numpy(original_image)
```

With this code, I two errors in exporter regarding missing symbolics:
1- Unsupported: ONNX export of roi_align with aligned=True
2-  Exporting the operator new_empty to ONNX opset version 12 is not supported

Can you please confirm if you see a similar behavior with pytorch 1.6 and detectron2 build from source?

Also, is there a reason you're exporting this model to external data format?
Running ONNX checker on models in external data format might be a bit different.
I tried bypassing the issue with symbolics (1- set aligned=False, and inserted a symbolic for new_empty),
and then tried export and checker with: onnx.checker.check_model("mask_rcnn.onnx")
Which seems to work and pass checker successfully.

**Comment by chaorensx** [comment] 2020-08-21 06:44
> For exporting a model to ONNX, you should not set the export type to OperatorExportTypes.ONNX_ATEN.
> Is there a specific reason you're using a different export type?
> 
> To try out the repro code, I added the code below to read the image:
> 
> ```
> input_img = osp.join(
>             osp.dirname(__file__), '../tests/data/color.jpg')
> original_image = mmcv.imread(input_img)
> original_image = torch.from_numpy(original_image)
> ```
> 
> With this code, I two errors in exporter regarding missing symbolics:
> 1- Unsupported: ONNX export of roi_align with aligned=True
> 2- Exporting the operator new_empty to ONNX opset version 12 is not supported
> 
> Can you please confirm if you see a similar behavior with pytorch 1.6 and detectron2 build from source?
> 
> Also, is there a reason you're exporting this model to external data format?
> Running ONNX checker on models in external data format might be a bit different.
> I tried bypassing the issue with symbolics (1- set aligned=False, and inserted a symbolic for new_empty),
> and then tried export and checker with: onnx.checker.check_model("mask_rcnn.onnx")
> Which seems to work and pass checker successfully.

Thanks for your reply.

What I want to do is to transform torch2onnx2tensorflow. I think I should use ONNX mode but ONNX_ATEN_FALLBACK. Although it can be transformed to onnx with ONNX_ATEN_FALLBACK mode, it can not be transformed to tensorflow because of ATEN.

In ONNX mode, I found some unsuported op. I will try to fix it and give all you some feedback as soon as possible.

**Comment by chaorensx** [comment] 2020-08-24 02:34
> Yes, the model with ATEN ops does not comply with ONNX spec. Please use the default export type when exporting the model to ONNX.
> Let us know if there are missing operators.
> Currently I can see two ops missing as I mentioned:
> 1- Unsupported: ONNX export of roi_align with aligned=True
> 2- Exporting the operator new_empty to ONNX opset version 12 is not supported
> 
> I'll look into adding support for these ops.

Using ONNX mode, I sovled the problem. I switched other op because some op is not supported:

1-Unsuppoted: torch.new_full
2-Unsuppoted: torch.linspace
3-Unsuppoted: dcn

**Comment by neginraoof** [comment] 2020-08-24 18:35
@chaorensx
What do you mean by solving the problem? Were you able to export the model? which operator export type did you choose?

I did not hit the dcn op. Can you clarify which operator it is? Do you happen to know the source code corresponding to this op?

**Comment by chaorensx** [comment] 2020-08-28 06:39
> @chaorensx
> What do you mean by solving the problem? Were you able to export the model? which operator export type did you choose?
> 
> I did not hit the dcn issue when trying the repro. Can you clarify which operator it is? Do you happen to know the source code corresponding to this op?

Solving problem means that I transoformed to onnx successfully with reducing some unsupported op.
I am trying to convert a mask rcnn model with lots of custom tricks. DCN is one of the tricks.
DCN means deformable convolution network, which is inserted in ROI pooling to promote mAP. You can refer to this [](https://arxiv.org/abs/1703.06211)

**Comment by neginraoof** [comment] 2020-08-28 18:57
Thanks @chaorensx 
PR for supporting ROIAlign export has been merged: https://github.com/pytorch/vision/pull/2613
You should be able to use this op with latest nightly build.

If you have a new model with unsupported ops (like DCN), would you please send us the complete repro model and export script?

**Comment by neginraoof** [comment] 2020-09-02 18:33
@chaorensx Would you please provide us the full script you use for model conversion?
Thanks!

**Comment by spandantiwari** [comment] 2020-10-21 22:12
Please reopen the issue if you are still having this issue.

**Closed by spandantiwari** 2020-10-21 22:12 UTC
Labels: module: onnx, triaged

**Comment by vegetable09** [comment] 2021-03-05 09:44
> 
> 
> > Yes, the model with ATEN ops does not comply with ONNX spec. Please use the default export type when exporting the model to ONNX.
> > Let us know if there are missing operators.
> > Currently I can see two ops missing as I mentioned:
> > 1- Unsupported: ONNX export of roi_align with aligned=True
> > 2- Exporting the operator new_empty to ONNX opset version 12 is not supported
> > I'll look into adding support for these ops.
> 
> Using ONNX mode, I sovled the problem. I switched other op because some op is not supported:
> 
> 1-Unsuppoted: torch.new_full
> 2-Unsuppoted: torch.linspace
> 3-Unsuppoted: dcn

@chaorensx Help! how to replace torch.linspace with other op? I meet the same problem
