### ISSUE TITLE
conda install fails - HTTP 000 CONNECTION FAILED

### ISSUE THREAD

**Issue by Minthos** [pytorch/pytorch#4207] opened 2017-12-16 10:40 UTC
I'm trying to get set up on a brand new install of ubuntu 16.04 on a slow and unreliable connection.

`
$ conda install -y pytorch torchvision cuda90 -c pytorch
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment /home/minthos/miniconda3:

The following NEW packages will be INSTALLED:

    cuda90:       1.0-h6433d27_0                              pytorch
    freetype:     2.8-hab7d2ae_1                                     
    intel-openmp: 2018.0.0-hc7b2577_8                                
    jpeg:         9b-h024ee3a_2                                      
    libpng:       1.6.32-hbd3595f_4                                  
    libtiff:      4.0.9-h28f6b97_0                                   
    mkl:          2018.0.1-h19d6760_4                                
    numpy:        1.13.3-py36ha12f23b_0                              
    olefile:      0.44-py36h79f9f78_0                                
    pillow:       4.3.0-py36h6f462bf_1                               
    pytorch:      0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4 pytorch [cuda90]
    torchvision:  0.2.0-py36h17b6947_1                        pytorch

pytorch-0.3.0- 100% |###########################################################################################| Time: 0:02:40   3.59 MB/s
pytorch-0.3.0- 100% |###########################################################################################| Time: 0:01:30   6.40 MB/s
pytorch-0.3.0- 100% |###########################################################################################| Time: 0:02:26   3.95 MB/s

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaError: CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

`

Well, a simple retry isn't enough. I even left it running overnight using this: `while true; do conda install -y pytorch torchvision cuda90 -c pytorch; done` but it seems it's not able to resume a failed download so it never finishes.

Trying to download the file manually using `wget -c https://conda.anaconda.org/pytorch/linux-64/pytorch-0.3.0-py36_cuda9.0.176_cudnn7.0.3hdc18817_4.tar.bz2
` seems to work for a little while, then I get:

> Read error at byte 359014594/578635335 (Connection reset by peer). Retrying.

followed by

> HTTP request sent, awaiting response... 403 Forbidden

So maybe I should leave that running in a while script overnight as well.. Anyway, I figured I'd let you guys know. It would be nice if the 3rd world could participate in AI development as well.

**Comment by Minthos** [comment] 2017-12-16 10:42
If this fails I'll install from source.

**Comment by zou3519** [comment] 2017-12-18 17:52
You could also try getting a binary for installation with pip (instructions on the [main site](http://pytorch.org/). 

If the problem is your connection, then building from source would probably help. There are plans for making a small CPU-only pytorch package (#4178) that could help with slow connections.

**Comment by Minthos** [comment] 2017-12-19 14:37
I had similar problems with pip, but at least pip allowed me to install from a file downloaded with wget so I finally got it installed.

**Comment by SarveshTS** [comment] 2017-12-22 09:00
Please update to the latest version of Navigator.

Open a terminal (on Linux or Mac) or the Anaconda Command Prompt (on windows)
and type

$ conda update anaconda-navigator

**Comment by Minthos** [comment] 2017-12-22 09:07
Sorry, after I got pytorch working using pip I disabled conda because its python conflicted with another python on my system.

**Comment by hennypurnomo** [comment] 2018-10-05 17:16
@ashukrishna100 thank you so much for sharing your solution. It does work for me.

**Comment by AbsolutelySaurabh** [comment] 2019-01-11 19:46
open the Anaconda prompt, update the anaconda navigator.
`` conda update anaconda-navigator

**Comment by xiaoshir** [comment] 2019-02-07 08:02
> open the Anaconda prompt, update the anaconda navigator.
> ` conda update anaconda-navigator`

Unfortunately I got this :(
PackageNotInstalledError: Package is not installed in prefix.
  prefix: C:\miniconda3_py37
  package name: anaconda-navigator

**Comment by gcourtade** [comment] 2019-02-20 14:40
@xiaoshir you have to be in (base) in order to update anaconda navigator
`conda deactivate`
`conda update anaconda-navigator`

**Comment by muhammadnasif** [comment] 2019-05-28 20:48
Try using anaconda prompt ... it solved my problem

**Comment by noeboito** [comment] 2019-06-10 23:23
> I recently got this issue resolved. Use this command to see proxy_servers
> `conda config --show`
> 
> If any proxy server is present in the configuration. Kindly use
> `conda config --remove-key proxy_servers`. It will remove saved proxy servers from anaconda configuration.
> Enter
> `conda clean --source-cache`
> Now your http error is gone.
> Give it a try and let me know in case of any difficulty.

When I try to make the second step, I have this

CondaKeyError: 'servers_proxy': key 'servers_proxy' is not in the config file

What's wrong ?

**Comment by MohgaEmam** [comment] 2019-06-28 17:35
i'm from egypt and i'm having the same problem

**Comment by sreerajr137** [comment] 2019-07-11 03:42
Showing connection error while installing -

conda install -c pytorch pytorch


WARNING conda.base.context:use_only_tar_bz2(632): Conda is constrained to only using the old .tar.bz2 file format because you have conda-build installed, and it is <3.18.3.  Update or remove conda-build to get smaller downloads and faster extractions.
Collecting package metadata (repodata.json): done
Solving environment: done
WARNING conda.core.package_cache_data:_make_single_record(350): Encountered corrupt package tarball at C:\Users\Cyber Guru\Anaconda3\pkgs\pytorch-1.1.0-py3.7_cuda100_cudnn7_1.tar.bz2. Conda has removed it, but you need to re-run conda to download it again.

## Package Plan ##

  environment location: C:\Users\Cyber Guru\Anaconda3

  added / updated specs:
    - pytorch


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pytorch-1.1.0              |py3.7_cuda100_cudnn7_1       496.0 MB  pytorch
    ------------------------------------------------------------
                                           Total:       496.0 MB

The following NEW packages will be INSTALLED:

  cudatoolkit        pkgs/main/win-64::cudatoolkit-10.0.130-0
  ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  pytorch            pytorch/win-64::pytorch-1.1.0-py3.7_cuda100_cudnn7_1


Proceed ([y]/n)? y


Downloading and Extracting Packages
pytorch-1.1.0        | 496.0 MB  | ######################2                                                      |  29%

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/win-64/pytorch-1.1.0-py3.7_cuda100_cudnn7_1.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your

**Comment by ni40in** [comment] 2019-08-02 19:41
i can't believe this issue is almost 2 years old. pytorch download still breaks in the middle, so random. extremely annoying

**Comment by Yaozuwu** [comment] 2019-08-03 16:13
All methods above don't work!

**Comment by soumith** [comment] 2019-08-05 03:31
there is unfortunately not much we can do about this issue -- as it is a result of network error / network issues.
We cant take any action that makes this better.

The positive that happened between now and 2 years ago is that Anaconda moved the PyTorch channel to a CDN, which helps with faster download speeds depending on where you are in the world.

Because this issue is not actionable, I'm closing it.

**Closed by soumith** 2019-08-05 03:31 UTC
Labels: module: binaries, triaged

**Comment by YehudaItkin** [comment] 2019-08-21 09:52
Hi. That is the problem of your firewall. Just add --insecure flag, like that 
`conda install --insecure  pytorch torchvision cudatoolkit=9.2 -c pytorch`

**Comment by AziziShekoofeh** [comment] 2019-09-30 19:43
@YehudaItkin Thanks! After a week having this issue and trying out different solution, finally setting ssl flag solved my issue!

**Comment by desikazone** [comment] 2019-12-18 10:34
#Yehudaltkin Thanks! After several days of endless search for solution, finally got pytorch 0.3.0 installed following your code... !!! :)

**Comment by djdeepak88** [comment] 2020-03-29 15:05
Yes by adding the config setting it works.

**Comment by sruthibc06** [comment] 2020-05-25 16:46
Try using anaconda propmt. it solved my problem

**Comment by vipul1799** [comment] 2020-05-27 19:10
Use pip
then the file it chooses to download,stop and download using the browser
Then in pip replace the link with the local address

**Comment by bunny64** [comment] 2020-06-12 04:54
i tried all the solution above but it doesnt work

**Comment by Anku5hk** [comment] 2020-09-21 08:07
One solution is to download torch .whl file manually, by going to [here](https://download.pytorch.org/whl/torch_stable.html). Then inside conda(anaconda command prompt), install it via `pip install file_location/file.whl` .Also for cudnn check this [doc](https://docs.nvidia.com/deeplearning/cudnn/install-guide/index.html#install-windows). This worked for me.

**Comment by nayanex** [comment] 2020-10-07 14:41
> conda clean --source-cache

'conda clean --source-cache' is deprecated.
    Use 'conda build purge-all' to remove source cache files

**Comment by GF-Huang** [comment] 2022-07-20 20:57
Not work.

```
(base) root@VM-48-14-debian:~# conda install pytorch torchvision torchaudio cpuonly -c pytorch --insecure -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /root/miniconda3

  added / updated specs:
    - cpuonly
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cpuonly-2.0                |                0           2 KB  pytorch
    ffmpeg-4.3                 |       hf484d3e_0         9.9 MB  pytorch
    pytorch-1.12.0             |      py3.9_cpu_0        76.6 MB  pytorch
    pytorch-mutex-1.0          |              cpu           3 KB  pytorch
    torchaudio-0.12.0          |         py39_cpu         6.0 MB  pytorch
    torchvision-0.13.0         |         py39_cpu         6.1 MB  pytorch
    ------------------------------------------------------------
                                           Total:        98.7 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  cpuonly            pytorch/noarch::cpuonly-2.0-0
  ffmpeg             pytorch/linux-64::ffmpeg-4.3-hf484d3e_0
  freetype           pkgs/main/linux-64::freetype-2.11.0-h70c0345_0
  giflib             pkgs/main/linux-64::giflib-5.2.1-h7b6447c_0
  gmp                pkgs/main/linux-64::gmp-6.2.1-h295c915_3
  gnutls             pkgs/main/linux-64::gnutls-3.6.15-he1e5248_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.4.0-h06a4308_3561
  jpeg               pkgs/main/linux-64::jpeg-9e-h7f8727e_0
  lame               pkgs/main/linux-64::lame-3.100-h7b6447c_0
  lcms2              pkgs/main/linux-64::lcms2-2.12-h3be6417_0
  libiconv           pkgs/main/linux-64::libiconv-1.16-h7f8727e_2
  libidn2            pkgs/main/linux-64::libidn2-2.3.2-h7f8727e_0
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libtasn1           pkgs/main/linux-64::libtasn1-4.16.0-h27cfd23_0
  libtiff            pkgs/main/linux-64::libtiff-4.2.0-h2818925_1
  libunistring       pkgs/main/linux-64::libunistring-0.9.10-h27cfd23_0
  libwebp            pkgs/main/linux-64::libwebp-1.2.2-h55f646e_0
  libwebp-base       pkgs/main/linux-64::libwebp-base-1.2.2-h7f8727e_0
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.3-h295c915_1
  mkl                pkgs/main/linux-64::mkl-2021.4.0-h06a4308_640
  mkl-service        pkgs/main/linux-64::mkl-service-2.4.0-py39h7f8727e_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.1-py39hd3c417c_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.2-py39h51133e4_0
  nettle             pkgs/main/linux-64::nettle-3.7.3-hbbd107a_1
  numpy              pkgs/main/linux-64::numpy-1.22.3-py39he7a7128_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.22.3-py39hf524024_0
  openh264           pkgs/main/linux-64::openh264-2.1.1-h4ff587b_0
  pillow             pkgs/main/linux-64::pillow-9.2.0-py39hace64e9_1
  pytorch            pytorch/linux-64::pytorch-1.12.0-py3.9_cpu_0
  pytorch-mutex      pytorch/noarch::pytorch-mutex-1.0-cpu
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  torchaudio         pytorch/linux-64::torchaudio-0.12.0-py39_cpu
  torchvision        pytorch/linux-64::torchvision-0.13.0-py39_cpu
  typing_extensions  pkgs/main/noarch::typing_extensions-4.1.1-pyh06a4308_0
  zstd               pkgs/main/linux-64::zstd-1.5.2-ha4553b6_0



Downloading and Extracting Packages
torchvision-0.13.0   | 6.1 MB    |                                                                                                   |   0% 
torchaudio-0.12.0    | 6.0 MB    |                                                                                                   |   0% 
ffmpeg-4.3           | 9.9 MB    |                                                                                                   |   0% 
cpuonly-2.0          | 2 KB      |                                                                                                   |   0% 
pytorch-1.12.0       | 76.6 MB   |                                                                                                   |   0% 
pytorch-mutex-1.0    | 3 KB      |                                                                                                   |   0% 

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/torchvision-0.13.0-py39_cpu.tar.bz2>
Elapsed: 00:01.676497

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/torchaudio-0.12.0-py39_cpu.tar.bz2>
Elapsed: 00:00.248295

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2>
Elapsed: 00:00.247924

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/cpuonly-2.0-0.tar.bz2>
Elapsed: 00:00.492093

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-1.12.0-py3.9_cpu_0.tar.bz2>
Elapsed: 00:00.248724

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cpu.tar.bz2>
Elapsed: 00:00.247503

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

```

**Comment by soheil** [comment] 2022-10-22 19:46
In my case `/etc/resolv.conf` file was missing, causing DNS issues. It probably happened last time the machine ran out of space.
