### ISSUE TITLE
load pretrained inception model failure

### ISSUE THREAD

**Issue by boyingl** [pytorch/pytorch#9011] opened 2018-06-29 01:10 UTC
configuration:
pytorch 0.3.1
python 3.6

I am trying to load a pretrained inception network

code: 
> inception = models.inception_v3(pretrained=True, num_classes=800, aux_logits=False)

error:

>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torchvision/models/inception.py", line 27, in inception_v3
>     model.load_state_dict(model_zoo.load_url(model_urls['inception_v3_google']))
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 66, in load_url
>     return torch.load(cached_file, map_location=map_location)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
>     return _load(f, map_location, pickle_module)
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
>     result = unpickler.load()
>   File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/autograd/variable.py", line 77, in __setstate__
>     self.requires_grad, _, self._backward_hooks = state
> ValueError: too many values to unpack (expected 3)

cc @mruberry

**Comment by SsnL** [comment] 2018-06-29 02:38
What's your torchvision version?

**Comment by boyingl** [comment] 2018-06-29 17:10
how can I check the version of torchvision specifically ?

**Comment by SsnL** [comment] 2018-06-29 17:11
`print(torchvision.__version__)`

**Comment by boyingl** [comment] 2018-06-29 20:23
it's 0.2.0

**Comment by karandwivedi42** [comment] 2018-06-29 20:28
`num_classes=800` , `pretrained=True` do not work together AFAIK. Using pretrained means you have to keep `num_classes=1000`

**Comment by karandwivedi42** [comment] 2018-06-29 20:34
I just checked, using pretrained with `aux_logits=False` is also not possible. To use the pretrained model, you have to use
```python
inception = models.inception_v3(pretrained=True, num_classes=1000, aux_logits=True)
```
After that it works and I am can't reproduce the error with same config (pt0.3.1, tv0.2.0)

**Comment by boyingl** [comment] 2018-06-29 20:35
just tried 

`        inception = models.inception_v3(pretrained=True, aux_logits=False)
`
still same error:
```
  File "/workspace/train_eval.py", line 50, in train_and_eval_factory
    model = model_dict[model_name](param_file_path, num_class)
  File "/workspace/models/binary_inception.py", line 21, in __init__
    inception = models.inception_v3(pretrained=True, aux_logits=False)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torchvision/models/inception.py", line 27, in inception_v3
    model.load_state_dict(model_zoo.load_url(model_urls['inception_v3_google']))
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/utils/model_zoo.py", line 66, in load_url
    return torch.load(cached_file, map_location=map_location)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/serialization.py", line 303, in load
    return _load(f, map_location, pickle_module)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/serialization.py", line 469, in _load
    result = unpickler.load()
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/autograd/variable.py", line 77, in __setstate__
    self.requires_grad, _, self._backward_hooks = state
ValueError: too many values to unpack (expected 3)

```

**Comment by SsnL** [comment] 2018-06-30 20:36
@boyingl Could you `rm -rf ~/.torch/models` and try again?

**Comment by boyingl** [comment] 2018-07-02 18:55
got the exact same error

**Comment by mruberry** [comment] 2020-12-29 18:10
Closing due to age and lack of reproduction. If this is still an issue please update and reopen.

**Closed by mruberry** 2020-12-29 18:10 UTC
Labels: module: serialization, needs reproduction, triaged
