### ISSUE TITLE
`argmin()` with an empty 1D tensor still gets error even if setting `dim=0` to it

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130120] opened 2024-07-04 17:01 UTC
### 🐛 Describe the bug

[argmin()](https://pytorch.org/docs/stable/generated/torch.argmin.html) with an empty 1D tensor gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.argmin(input=my_tensor) # Error
```

> IndexError: argmin(): Expected reduction dim to be specified for input.numel() == 0.

So, I set `dim=0` to `argmin()` following the error message above but it still gets other error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.argmin(input=my_tensor, dim=0) # Error
```

> IndexError: argmin(): Expected reduction dim 0 to have non-zero size.

In addition, `argmin()` with an empty 2D or 3D  tensor also gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.argmin(input=my_tensor) # Error

my_tensor = torch.tensor([[[]]])

torch.argmin(input=my_tensor) # Error
```

> IndexError: argmin(): Expected reduction dim to be specified for input.numel() == 0.

But setting `dim=0` to `argmin()` following the error message above works properly as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.argmin(input=my_tensor, dim=0)
# tensor([], dtype=torch.int64)

my_tensor = torch.tensor([[[]]])

torch.argmin(input=my_tensor, dim=0)
# tensor([], size=(1, 0), dtype=torch.int64)
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by albanD** [comment] 2024-07-08 14:47
Near duplicate of https://github.com/pytorch/pytorch/issues/130187
Let's continue discussion there since they have the same behavior

**Closed by albanD** 2024-07-08 14:47 UTC
