### ISSUE TITLE
Wrong error message from 'matmul' in 'functional.py'

### ISSUE THREAD

**Issue by R0bertoG** [pytorch/pytorch#4960] opened 2018-01-31 15:43 UTC
- OS: debian (docker container)
- PyTorch version: 0.3.0.post4
- How you installed PyTorch (conda, pip, source): Kaggle Docker Image (https://github.com/Kaggle/docker-python)
- Python version: 3.6.4
- Using CPU
_______
The error message: 

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-56-0e3aecff8c7c> in <module>()
      3 data = torch.autograd.Variable(data)
      4 print(data)
----> 5 y_ = myNetwork(data)

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    323         for hook in self._forward_pre_hooks.values():
    324             hook(self, input)
--> 325         result = self.forward(*input, **kwargs)
    326         for hook in self._forward_hooks.values():
    327             hook_result = hook(self, input, result)

<ipython-input-53-5dc90cb17d6e> in forward(self, x)
      5 
      6     def forward(self, x):
----> 7         x = self.fc1(x)
      8         return x
      9 

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    323         for hook in self._forward_pre_hooks.values():
    324             hook(self, input)
--> 325         result = self.forward(*input, **kwargs)
    326         for hook in self._forward_hooks.values():
    327             hook_result = hook(self, input, result)

/opt/conda/lib/python3.6/site-packages/torch/nn/modules/linear.py in forward(self, input)
     53 
     54     def forward(self, input):
---> 55         return F.linear(input, self.weight, self.bias)
     56 
     57     def __repr__(self):

/opt/conda/lib/python3.6/site-packages/torch/nn/functional.py in linear(input, weight, bias)
    835         return torch.addmm(bias, input, weight.t())
    836 
--> 837     output = input.matmul(weight.t())
    838     if bias is not None:
    839         output += bias

/opt/conda/lib/python3.6/site-packages/torch/autograd/variable.py in matmul(self, other)
    384 
    385     def matmul(self, other):
--> 386         return torch.matmul(self, other)
    387 
    388     def resize(self, *sizes):

/opt/conda/lib/python3.6/site-packages/torch/functional.py in matmul(tensor1, tensor2, out)
    166     elif dim_tensor1 == 1 and dim_tensor2 == 2:
    167         if out is None:
--> 168             return torch.mm(tensor1.unsqueeze(0), tensor2).squeeze_(0)
    169         else:
    170             return torch.mm(tensor1.unsqueeze(0), tensor2, out=out).squeeze_(0)

RuntimeError: Expected object of type Variable[torch.LongTensor] but found type Variable[torch.FloatTensor] for argument #1 'mat2'
```

It's produced by the code:

```
import torch
import torchvision
class Network(torch.nn.Module):
    def __init__(self):
        super(Network, self).__init__()
        self.fc1 = torch.nn.Linear(1, 10)
        
    def forward(self, x):
        x = self.fc1(x)
        return x

myNetwork = Network()

data = torch.Tensor([3]).long()
data = torch.autograd.Variable(data)
y_ = myNetwork(data)


```
The error happens because the input to the network is of type 'long' and it should be of type 'float'.
Changing the type to 'float' fix the problem.
But, it seems that the message is saying the opposite:

RuntimeError: Expected object of type Variable[torch.**LongTensor**] but found type Variable[torch.**FloatTensor**] for argument #1 'mat2'

The message should be:

RuntimeError: Expected object of type Variable[torch.**FloatTensor**] but found type Variable[torch.**LongTensor**] for argument #1 'mat2'

**Comment by SsnL** [comment] 2018-01-31 15:59
It's debatable. The current message says that the weights in your network should be Long to be consistent with your input rather than Float. It depends on whether you choose input or weight as reference.

**Comment by ezyang** [comment] 2020-08-07 16:30
I'm going to speculatively close this as a dupe of #37160

**Closed by ezyang** 2020-08-07 16:30 UTC
