### ISSUE TITLE
Embedding backward pass taking 1300x longer than forward pass

### ISSUE THREAD

**Issue by heiner** [pytorch/pytorch#24912] opened 2019-08-20 16:37 UTC
## 🐛 Bug

Taking a simple model with an nn.Embedding layer (`nn.Embedding(6000, 16)`) on the GPU, the forward pass takes ~32us while the backward pass takes ~42ms (42000us), which is over 1300 times slower.

I am aware there's a sparse backward version, but it's not compatible with the optimizers I want to use. Also this seems too slow for a dense backward pass regardless.

Perfetto trace: https://ui.perfetto.dev/#!/?s=8cc15ca3da8bd113fd972e1ef4865caca789b4ab998306da83e307882507bf4

Code: https://gist.github.com/heiner/c812a38a338878f5c02f6193511afc6a#file-simpleembed-py

## To Reproduce

1. `git clone https://gist.github.com/c812a38a338878f5c02f6193511afc6a.git embedding`
2. `cd embedding/`
3. `python simpleembed.py` (requires PyTorch >= 1.2)

Perfetto trace: https://ui.perfetto.dev/#!/?s=8cc15ca3da8bd113fd972e1ef4865caca789b4ab998306da83e307882507bf4 (use wasd navigation)

Code: https://gist.github.com/heiner/c812a38a338878f5c02f6193511afc6a#file-simpleembed-py

## Expected behavior

I'd expect a forward/backward ratio of up to 100x, but not this.

## Environment

```
PyTorch version: 1.3.0.dev20190816
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.88
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 410.79
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.3.0.dev20190816
[pip] torchvision==0.5.0a0+19315e3
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      243
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.3.0.dev20190816 py3.7_cuda10.0.130_cudnn7.6.2_0    pytorch-nightly
[conda] torchvision               0.5.0.dev20190816      py37_cu100    pytorch-nightly
```

## Additional context

cc @ezyang @gchanan @SsnL

**Comment by heiner** [comment] 2019-08-21 10:36
Sorry Perfetto link seems to have broken? Here's another one: https://ui.perfetto.dev/#!/?s=f3afa3daddbcce6d695d8674cbdafe990c48515379d3aaea99826fb3bd1645

Here's a screenshot:
![image](https://user-images.githubusercontent.com/69371/63425006-82377b00-c407-11e9-8b5b-c56e07a954b3.png)

Here's a trace file for Perfetto / chrome://tracing https://gist.github.com/heiner/c812a38a338878f5c02f6193511afc6a#file-simpleembed-trace-gz

**Comment by heiner** [comment] 2019-08-27 13:00
Please not that it should be rather easy to reproduce given the above steps. If this looks different for you, please let me know.

**Comment by colesbury** [comment] 2019-08-30 15:51
Thanks for including code to reproduce the issue. 

1. You need to set `torch.autograd.profiler.profile(use_cuda=True)` when profiling CUDA code. Otherwise you're just measuring CPU time, which can include long waits for CUDA kernels to execute in more or less arbitrary places (basically any time you launch a CUDA kernel it may block on previous launches).

2. Even with `use_cuda=True`, the timing for the embedding forward doesn't look accurate to me. The profiler shows ~90 us per call on my P100, but based on the benchmark below I'd expect it to be much more expensive (~700+ us). 90 us is hard to believe from a memory bandwidth perspective. Even just looking at the output that implies over a TB/sec which is more than the P100's global memory bandwidth (26214400*4 bytes/90 us=1.16TB/sec). I'm not sure what's going on here (@ngimel)

https://gist.github.com/colesbury/6075d12d586717f76d82a6f81ab48fa4

2. You've got a lot of indexes (1024*80*20=1.6 million) for 6000 rows. nn.Embedding makes the backwards deterministic by serializing the updates to a row.  index_select (which uses atomic ops) is a little faster, but it looks like the contention is still an issue.


```python
import torch

ROWS = 6000
embed = torch.nn.Embedding(ROWS, 16).cuda()
x = torch.randint(ROWS, [1024, 80, 20], device='cuda')
grad = torch.randn_like(embed(x))

print('forward nn.Embedding')
%timeit embed(x); torch.cuda.synchronize()  # 787 µs

print('forward+backward nn.Embedding')
%timeit embed(x).backward(grad); torch.cuda.synchronize()  # 3.65 ms

# handle reshaping x to 1-d and output back to N-d
def index_select(embed, x):
    out = embed.weight.index_select(0, x.reshape(-1))
    return out.reshape(x.shape + (-1,))

print('forward index_select')
%timeit index_select(embed, x); torch.cuda.synchronize()  # 786 us  

print('forward+backward nn.Embedding')
%timeit index_select(embed, x).backward(grad); torch.cuda.synchronize()  # 2.13 ms
```

**Comment by colesbury** [comment] 2019-08-30 16:09
nvprof shows an average of 824.48us for `indexSelectLargeIndex` (which is embedding forward), which matches my expectations.

I'm not sure why the event-based measurements (like the autograd profiler) are off.

**Comment by madsbk** [comment] 2019-09-02 10:34
I see something similar as @colesbury when running @heiner's code on my machine, a Quadro GV100.

`CUDA_LAUNCH_BLOCKING=1 python simpleembed.py` shows an average of 
  - 326.48us for `indexSelectLargeIndex` (embedding forward)
  - 575.75us for `EmbeddingBackwardKernel` (embedding backward)

Full nvprof output here: https://gist.github.com/madsbk/c67f358710e7024f3cad3f4a68bf980b

**Comment by madsbk** [comment] 2019-09-04 08:13
@heiner, could you try to run `nvprof python simpleembed.py`and post the profiling output?

**Comment by heiner** [comment] 2019-09-10 16:14
Hey, thanks for taking a look! And Sorry for the delay, I was on holiday.

Here's the nvprof output:
[nvprof.output.txt](https://github.com/pytorch/pytorch/files/3596639/nvprof.output.txt) (also in https://gist.github.com/heiner/25a4bd8e38fb33fbefc4c59e069ea475).

The issue I'm trying to reproduce here is showing up in an RL-related problem where the embedding is embedding different symbols in my environment. Those are in the range 0-6000, but far from uniformly distributed, which makes the lock contention worse I guess. The shape of [1024, 80, 20] comes from something like trajectory_length * batch_size * width * height.

**Comment by ngimel** [comment] 2019-12-04 19:56
Closing, the profiling data showed that embedding backward takes reasonable time.

**Closed by ngimel** 2019-12-04 19:56 UTC
Labels: high priority, module: cuda, module: nn, topic: performance, triaged

**Comment by heiner** [comment] 2021-11-29 13:56
Same issue happens at https://github.com/pytorch/pytorch/issues/20655.
