### ISSUE TITLE
torch.jit.script issue: RuntimeError: select() cannot be applied to a 0-dim tensor.

### ISSUE THREAD

**Issue by n2cholas** [pytorch/pytorch#37286] opened 2020-04-25 05:55 UTC
## 🐛 Bug

The following code should run but does not:

```
import torch

@torch.jit.script
def f(x):  # ? x 6
    return x.t()[[0, 1, 5]]  # 3 x ?

print(f(torch.zeros((2, 6))))
```

Here is the error produced when running the above code:

```
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<ipython-input-11-c4a594a6d126>", line 3, in f
@torch.jit.script
def f(x):  # ? x 6
    return x.t()[[0, 1, 5]]  # 3 x ?
           ~~~~~~~~~~~~~~ <--- HERE
RuntimeError: select() cannot be applied to a 0-dim tensor.
```

## Expected behavior

The code without the `@torch.jit.script` decorator prints:

```
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
```

## Environment
I tried this on Google Colab with PyTorch 1.4.0 and 1.5.0

 - PyTorch Version (e.g., 1.0): 1.4.0 and 1.5.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): pip install torch==1.5
 - Python version: 3.6.9

cc @ezyang @gchanan @zou3519 @suo

**Comment by suo** [comment] 2020-05-01 21:18
We should re-use the C++ frontend code here now that it supports advanced indexing.

**Comment by eellison** [comment] 2020-05-05 18:59
Dupe of https://github.com/pytorch/pytorch/issues/18616

**Closed** 2020-05-06 17:46 UTC
Labels: high priority, jit, triage review
