### ISSUE TITLE
ideep fails to compile on gcc-6

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#13988] opened 2018-11-14 19:08 UTC
cc: @mingfeima 
```
/home/jaliya/repos/pytorch_clean/third_party/ideep/mkl-dnn/src/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp: In member function ‘void mkldnn::impl::cpu::jit_avx512_core_u8s8s32x_wino_conv_dst_trans_t::generate()’:
/home/jaliya/repos/pytorch_clean/third_party/ideep/mkl-dnn/src/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp:222:56: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
         assert(id_reg_tmp < jcp.alpha * jcp.alpha + 14);
                                                        ^
/home/jaliya/repos/pytorch_clean/third_party/ideep/mkl-dnn/src/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp:222:56: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
         assert(id_reg_tmp < jcp.alpha * jcp.alpha + 14);
                                                        ^
/home/jaliya/repos/pytorch_clean/third_party/ideep/mkl-dnn/src/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp:222:56: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
         assert(id_reg_tmp < jcp.alpha * jcp.alpha + 14);
                                                        ^
/home/jaliya/repos/pytorch_clean/third_party/ideep/mkl-dnn/src/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp:222:56: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
         assert(id_reg_tmp < jcp.alpha * jcp.alpha + 14);
                                                        ^
```

cc @malfet @seemethere @walterddr @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by Jianhui-Li** [comment] 2018-11-14 23:00
Hi Soumith, 

I believe it is because gcc optimized the expression inside assertions to a simpler form like "assert(id<2)"  with the assumption that “jcp.alpha * jcp.alpha + 14” doesn’t overflow.  There are 7 assertions of this kind (4 in jit_avx512_core_u8s8s32x_wino_convolution.cpp, and 3 in jit_avx512_core_fp32_wino_conv_2x3.cpp).  We need to verify this but you may give it a try. 
 
    Zmm vreg_tmp(int id) { // 2
        const int id_reg_tmp = jcp.alpha * jcp.alpha + 12 + id;
        assert(id_reg_tmp < jcp.alpha * jcp.alpha + 14);   // => assert(id<2); 
        return Zmm(31 - id_reg_tmp);
    }

**Comment by soumith** [comment] 2018-11-15 00:58
I dont have access to that compile right now, it's from a user-report from someone at Microsoft.
Try gcc-6, hopefully it'll fail

**Comment by Jianhui-Li** [comment] 2018-11-15 06:16
We reproduced this and are working with MKL-DNN on cleaning up this warning [-Werror=strict-overflow].

**Comment by jgong5** [comment] 2018-11-23 00:59
PR https://github.com/pytorch/pytorch/pull/14308 is supposed to fix this issue.

**Comment by soumith** [comment] 2018-12-09 07:33
@toby5box workaround was posted in https://github.com/pytorch/pytorch/issues/14948#issue-388982574

**Comment by gujinghui** [comment] 2018-12-10 04:36
pls try this #14977

**Comment by malfet** [comment] 2021-05-17 16:52
Closing, as ideep can be compiled by gcc-7.5+

**Closed by malfet** 2021-05-17 16:52 UTC
Labels: module: build, module: mkldnn, triaged
