### ISSUE TITLE
cufft cache makes rfft with cuda tensors to return incorrect results in subsequent calls. 

### ISSUE THREAD

**Issue by jonboh** [pytorch/pytorch#67140] opened 2021-10-23 09:48 UTC
## 🐛 Bug

rfft returns incorrect results in subsequent calls in CUDA. This seems to be related to the cufft cache.
Clearing the cache with `torch.backends.cuda.cufft_plan_cache.clear()` makes the calculation to be performed correctly
.
## To Reproduce

1. Run fft with a cuda tensor twice
2. The second (and all subsequent results) will be different fromt the first (correct) result

```
import numpy as np
from scipy.stats import norm
import matplotlib.pyplot as plt
from torch.fft import rfft, irfft
device = 'cuda'
pdf = torch.from_numpy(
    norm.pdf(np.linspace(-10, 10, 1000).reshape(-1,1))
).to(device)
n_iter = 50
n_full = pdf.shape[0] * n_iter - n_iter + 1
fft0 = rfft(pdf, axis=0, n=n_full)
fft1 = rfft(pdf, axis=0, n=n_full)
plt.plot(np.abs(fft0.cpu()[:, 0]), label='fft0')
plt.plot(np.abs(fft1.cpu()[:, 0]), label='fft1')
plt.legend()
plt.title(f'On {device}')
```

## Expected behavior

Both resutls should be equal. When device='cpu' the result is the expected one.

## Environment
PyTorch version: 1.9.1
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19042-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 970
Nvidia driver version: 496.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.9.1
[pip3] torchaudio==0.9.1
[pip3] torchvision==0.2.2
[conda] _pytorch_select           0.1                       cpu_0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               11.1.1               heb2d755_9    conda-forge
[conda] libmklml                  2019.0.5             haa95532_0
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py38h196d8e1_0
[conda] mkl_fft                   1.3.0            py38h46781fe_0
[conda] mkl_random                1.1.0            py38hf9181ef_0
[conda] numpy                     1.19.2           py38hadc3359_0
[conda] numpy-base                1.19.2           py38ha3acd2a_0
[conda] pytorch                   1.9.1           py3.8_cuda11.1_cudnn8_0    pytorch
[conda] torchaudio                0.9.1                      py38    pytorch
[conda] torchvision               0.2.2                      py_3    pytorch
## Additional context
On GPU:
![on_gpu](https://user-images.githubusercontent.com/31407988/138551460-2783771d-bdf2-4827-93ee-dd3e23ac6cba.png)

On CPU:
![on_cpu](https://user-images.githubusercontent.com/31407988/138551455-7e3f50cd-7c98-45e8-884a-8de7cb40d1ab.png)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ngimel

**Comment by jbschlosser** [comment] 2021-11-01 17:11
Closing as duplicate of #63152

**Closed by jbschlosser** 2021-11-01 17:11 UTC
Labels: high priority, triage review, module: cuda, triaged, module: correctness (silent)
