### ISSUE TITLE
TORCH_CUDNN_V8_API Thread Safety Bug

### ISSUE THREAD

**Issue by tuero** [pytorch/pytorch#103793] opened 2023-06-17 04:07 UTC
### 🐛 Describe the bug

This is a follow from this discussion here: https://discuss.pytorch.org/t/threaded-inference-c10-cudnnerror/182191
I have a test repo here which demonstrates the bug.: https://github.com/tuero/torch_thread_test

I’m running into issues with threaded inference (multiple threads using the same single GPU model) when using multiple model instances. For an individual model type, I have it wrapped where threads sends query to a thread-safe queue and receive back inferences. On the model side, it just sits in a separate thread which pulls from the queue, run through the model, then send back. This works fine when using multiple threads for inference (think running a search algorithm, each thread has a separate problem, and all using the same single GPU to query).

The issues arises when I have a second model (for separate query types). Since it uses the same wrapper, no two threads will hit the same model at the same time. However, thread 1 can run inference on model A at the same time thread 2 runs inference on model B.

With `TORCH_CUDNN_V8_API_DISABLED` unset, the separate threads running inference on the separate models will get stuck and execution just freezes, with the occasional `c10::CuDNNError`. When I `export TORCH_CUDNN_V8_API_DISABLED=1`, I get the expected behaviour where both threads can run inference on their separate model instances without any issue.

I tried to make the codebase as minimal as possible, but just having a simple model and throwing random tensors at it doesn't reproduce the bug. Its only when I have a non-trivial workload (search algorithm) which hits the models at different time occurrences. The linked repo I have above demonstrates (at least on my machine) the odd behaviour.

CC: @eqy

### Versions

```
$ cat /usr/local/libtorch/build-version
2.0.1+cu118

$ g++ --version
g++ (Ubuntu 11.3.0-6ubuntu1) 11.3.0

$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:33:58_PDT_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0

$ cat /usr/local/cuda/include/cudnn_version.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 9
#define CUDNN_PATCHLEVEL 1
```

cc @csarofeen @ptrblck @xwang233

**Comment by tuero** [comment] 2023-06-17 04:13
Sorry to whomever I previously CC'd, made a typo! Should be @eqy

**Comment by eqy** [comment] 2023-06-17 05:04
I have a hunch that it could be that the concurrent use-case causes some cache updates (e.g., possibly because new algos with smaller workspaces need to be selected if memory is used up) and this note I left for myself: https://github.com/pytorch/pytorch/blob/main/aten/src/ATen/native/cudnn/Conv_v8.cpp#L165 is relevant. If one thread tries to run a conv with a stale execution plan while the other has already erased/updated it, then we could see this causing a bad interaction.

**Comment by eqy** [comment] 2023-06-17 05:11
@tuero

Some questions about your use-case to check whether this would apply (and to check if additional conditions for repro are needed):
1. I'm assuming model A and B, while distinct, can have workloads that are the same (e.g., they can run the same convolution with the same input and weight shapes). A quick glance at the repro code seems to confirm this.
2. You are fully utilizing GPU memory or nearly fully utilizing it.

**Comment by tuero** [comment] 2023-06-17 05:16
@eqy For my current use case where I notice this behaviour, this is correct. While I have may various model implementations for different use cases, they do look the same (think various policy networks which are parameterized the same, and differnt threads may be using different policy networks), and GPU usage (single GPU in my machine) is near 100%.

**Comment by eqy** [comment] 2023-06-17 05:16
Sorry, I'm referring to memory rather than compute, is memory also nearly fully utilized?

**Comment by tuero** [comment] 2023-06-17 05:19
No. On my machine I have a 3090 has 24GB of memory, and in the linked example IIRC the network only takes around ~1/2 GB of memory. Only the utilization (as reported by `nvidia-smi`) is high.

**Comment by eqy** [comment] 2023-06-17 05:45
OK, I think cache contention could still be a problem in that case during warmup where both threads see that a workload has not been cached yet, but one manages to finish its first run and reuse the cache entry while the second thread is trying to update it for the first time and wipes out the execution plan that the first thread was trying to use.

In this case we would except to see the failure pretty early on (soon after multiple threads start doing work on the GPU), not after a longer test. Let me know if this doesn't line up with your observations.

**Comment by tuero** [comment] 2023-06-17 05:53
When I first noticed this it was an odd use case, and maybe that was a separate bug, but for my condensed repo example linked above I notice the behaviour immediately after the first model query on each model instance per thread.

**Comment by eqy** [comment] 2023-06-17 18:56
After thinking for a bit I believe one potential workaround before I confirm/fix the issue in upstream is downgrading to `libtorch` `2.0.1`. `2.0.1` would contain this commit https://github.com/pytorch/pytorch/commit/aa4ea6e1f30f69a0a2438a4229946b26d4f3f183 that would fix another bug if the cache was being updated, but it potentially introduced this issue by causing pointers to go stale in a thread-unsafe manner. If you can manage to downgrade `2.0.0` and that resolves the issue (you can verify that the V8 API is being used with `TORCH_CUDNN_V8_API_DEBUG=1`) then we would be reasonably confident that this is indeed the issue.

**Comment by tuero** [comment] 2023-06-17 20:23
Downloading libtorch 2.0.0 from your link above does not fix the issue. I've tried both with `TORCH_CUDNN_V8_API_DEBUG=1` and unset, and get the same problem. It does work (just like with 2.0.1) if I set `TORCH_CUDNN_V8_API_DISABLED=1`.

**Comment by eqy** [comment] 2023-06-21 01:17
Just wanted to give some updates:
First, thanks for your repro! It was extremely helpful in narrowing down the issue.
I managed to craft a pure C++ / cudnn-frontend repro that has the same characteristics, which should be solid evidence that it is a thread-safety issue in `cudnnBackendExecute`. While the thread-safety issue I was thinking about earlier with the benchmark cache also seems to be real, it didn't seem to be the root-cause here as my testing agrees with what you observed when downloading the 2.0.0 version of `libtorch`.

#103939 adds a temporary workaround of adding a `mutex` to `cudnnBackendExecute`, which we can hopefully remove once the issue is addressed by cuDNN (I've forwarded the repro to the cuDNN team).

**Comment by tuero** [comment] 2023-06-21 04:53
Thanks for the update, glad I could help in terms of narrowing down the potential issue. I'll keep an eye on the commit status, and in the meantime I think disabling the V8 API will suffice.

**Comment by eqy** [comment] 2023-06-24 04:05
Closing as the PR has been merged. Please reopen if you are still experiencing the issue in a build that includes these changes!

**Closed** 2023-06-24 04:05 UTC
Labels: module: cudnn, triaged

**Comment by tuero** [comment] 2023-06-24 06:14
Will do, thanks again!
