### ISSUE TITLE
 'dict' object has no attribute 'transpose'

### ISSUE THREAD

**Issue by eliashossain001** [pytorch/pytorch#99294] opened 2023-04-17 07:32 UTC
I'm working on converting the Pytorch model to ONNX. But running the following script gives me error:  'dict' object has no attribute 'transpose'
```python
def modified_script(onnx_path):
    
    # create an instance of AlignTTSArgs with desired values
    args = AlignTTSArgs(num_chars=105, out_channels=80, hidden_channels=256, hidden_channels_dp=256, 
                        encoder_type='fftransformer', encoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                        decoder_type='fftransformer', decoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                        length_scale=1.0, num_speakers=0, use_speaker_embedding=False, use_d_vector_file=False, d_vector_dim=0)

    # create an instance of AlignTTS
    model = AlignTTS(config=args)
   
    
    # Load the saved checkpoint
    checkpoint = torch.load(onnx_path, map_location=torch.device('cpu'))
    # Load the state dict into the model
    model.load_state_dict(checkpoint['model'])

    print(model)

    # Set the model to evaluation mode
    model.eval()

    batch_size = 8
    num_graphemes = 105
    seq_len = 256

    dummy_input = torch.randn(batch_size, num_graphemes, seq_len)
    
    y_lengths = torch.tensor([seq_len] * batch_size)
    

    torch.onnx.export(model, (dummy_input, y_lengths), 'align_tts_model.onnx', verbose=True, export_params=True, opset_version=10)

if __name__ == '__main__':
    # Call the function with the checkpoint path
    checkpoint_path = '/home/elias/poc_checkpoint.pth'
   
    modified_script(checkpoint_path)

================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/home/elias/script/onnx.py", line 162, in <module>
    modified_script(checkpoint_path)
  File "/home/elias/script/onnx.py", line 156, in modified_script
    torch.onnx.export(model, (dummy_input, y_lengths), 'align_tts_model.onnx', verbose=True, export_params=True, opset_version=10)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/onnx/utils.py", line 1544, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/onnx/utils.py", line 1109, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/onnx/utils.py", line 985, in _create_jit_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/onnx/utils.py", line 889, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/jit/_trace.py", line 1327, in _get_trace_graph
    outs = ONNXTracedModule(f, strict, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1333, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/jit/_trace.py", line 186, in forward
    graph, out = torch._C._create_graph_by_tracing(
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/jit/_trace.py", line 177, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1333, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1320, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/elias/miniconda3/envs/dev-elias/lib/python3.10/site-packages/TTS/tts/models/align_tts.py", line 225, in forward
    y= y.transpose(1,2)
AttributeError: 'dict' object has no attribute 'transpose' ```


Here is the forward function of the model that I'm working:

```def forward(self, x, x_lengths, y, y_lengths=None, 
                aux_input={"d_vectors": None}, phase=None 
        ):
        
        print('Y lengths:', y_lengths)

        y = y.transpose(1, 2)
       
        g = aux_input["d_vectors"] if "d_vectors" in aux_input else None
        o_de, o_dr_log, dr_mas_log, attn, mu, log_sigma, logp = None, None, None, None, None, None, None
    
        
        
        if phase == 0:
            # train encoder and MDN
            o_en, o_en_dp, x_mask, g = self._forward_encoder(x, x_lengths, g)
            dr_mas, mu, log_sigma, logp = self._forward_mdn(o_en, y, y_lengths, x_mask)
            y_mask = torch.unsqueeze(sequence_mask(y_lengths, None), 1).to(o_en_dp.dtype)
            attn = self.generate_attn(dr_mas, x_mask, y_mask)
        elif phase == 1:
            # train decoder
            o_en, o_en_dp, x_mask, g = self._forward_encoder(x, x_lengths, g)
            dr_mas, _, _, _ = self._forward_mdn(o_en, y, y_lengths, x_mask)
            o_de, attn = self._forward_decoder(o_en.detach(), o_en_dp.detach(), dr_mas.detach(), x_mask, y_lengths, g=g)
        elif phase == 2:
            # train the whole except duration predictor
            o_en, o_en_dp, x_mask, g = self._forward_encoder(x, x_lengths, g)
            dr_mas, mu, log_sigma, logp = self._forward_mdn(o_en, y, y_lengths, x_mask)
            o_de, attn = self._forward_decoder(o_en, o_en_dp, dr_mas, x_mask, y_lengths, g=g)
        elif phase == 3:
            # train duration predictor
            o_en, o_en_dp, x_mask, g = self._forward_encoder(x, x_lengths, g)
            o_dr_log = self.duration_predictor(x, x_mask)
            dr_mas, mu, log_sigma, logp = self._forward_mdn(o_en, y, y_lengths, x_mask)
            o_de, attn = self._forward_decoder(o_en, o_en_dp, dr_mas, x_mask, y_lengths, g=g)
            o_dr_log = o_dr_log.squeeze(1)
        else:
            o_en, o_en_dp, x_mask, g = self._forward_encoder(x, x_lengths, g)
            o_dr_log = self.duration_predictor(o_en_dp.detach(), x_mask)
            dr_mas, mu, log_sigma, logp = self._forward_mdn(o_en, y, y_lengths, x_mask)
            o_de, attn = self._forward_decoder(o_en, o_en_dp, dr_mas, x_mask, y_lengths, g=g)
            o_dr_log = o_dr_log.squeeze(1)
        dr_mas_log = torch.log(dr_mas + 1).squeeze(1)
        
        outputs = {
            "model_outputs": o_de.transpose(1, 2),
            "alignments": attn,
            "durations_log": o_dr_log,
            "durations_mas_log": dr_mas_log,
            "mu": mu,
            "log_sigma": log_sigma,
            "logp": logp,
        }
        return outputs
```

Can you please help me to figure out what went wrong?

**Comment by titaiwangms** [comment] 2023-04-19 17:31
It seems like input y is a dict, so it doesn't have attribute transpose. I suppose you wanted a tensor? I would check that input y.

**Comment by eliashossain001** [comment] 2023-04-20 11:07
@titaiwangms The model I am working with is from the Coqui AI TTS repository and specifically, I am using the AlignTTS model for text-to-speech. I have saved the PyTorch model as poc_checkpoint.pth and loaded it into the conversion function. To create the inputs for the forward function, I have created dummy_input and y_lengths. However, I am encountering issues with the ONNX conversion process and I am not sure what went wrong. Could you please guide me on how to successfully convert my model to ONNX? Here is the model (.pth) for your consideration: https://drive.google.com/file/d/1gLC4I-CjWnFNC4jzXPaLuKFWn47moToo/view?usp=share_link

**Comment by titaiwangms** [comment] 2023-04-20 13:16
Based on the error message, it doesn't even hit any ONNX pass. It fails on JIT tracer, which is caused by the wrong type of input "y". Tracer needs to trace model one time with provided inputs to create JIT graph, and during that tracing, your input has an AttributeError. I suspect you can't even run this input on torch model. So my suggestion would be please check your input, especially y, because it's expected as torch.Tensor, and based on the error message, it's a dict.

**Comment by eliashossain001** [comment] 2023-04-20 16:50
@titaiwangms Thanks for the advice, I must have a look and will let you know the further progress.

**Comment by eliashossain001** [comment] 2023-05-03 08:49
@titaiwangms Here is another attempt so fat I have come but this time I'm having a different error! 

```
class AlignTTSModelClass(nn.Module):
    def __init__(self, num_graphemes, seq_len):
        super().__init__()

        # Create an instance of the AlignTTSConfig class with the desired parameters
        config = AlignTTSConfig(
            # model_name="align_tts",
            model_args=AlignTTSArgs(
                num_chars=num_graphemes,
                out_channels=80,
                hidden_channels=256,
                hidden_channels_dp=256,
                encoder_type="fftransformer",
                encoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                decoder_type="fftransformer",
                decoder_params={"hidden_channels_ffn": 1024, "num_heads": 2, "num_layers": 6, "dropout_p": 0.1},
                length_scale=1.0,
                num_speakers=0,
                use_speaker_embedding=False,
                use_d_vector_file=False,
                d_vector_dim=0,
            )
        )

        # Create an instance of the AlignTTS class using the config
        self.align_tts = AlignTTS(config)

        # Set the input shape of the model
        self.input_shape = (seq_len, num_graphemes)

    
    def forward(self, x, x_lengths, y, y_lengths):
        # Perform the forward pass through the AlignTTS model, passing the additional arguments
        return self.align_tts(x, x_lengths, y, y_lengths)

    

if __name__ == '__main__':
    # Parameters
    batch_size = 8
    num_graphemes = 105
    seq_len = 256

    # Load the PyTorch checkpoint
    checkpoint_path = '/home/elias/male_checkpoint.pth'
    checkpoint = torch.load(checkpoint_path, map_location=torch.device('cpu'))

    # Create a dummy input tensor for the model

    dummy_input = torch.randint(low=0, high=num_graphemes, size=(batch_size, seq_len), dtype=torch.long)

    dummy_input_lengths = torch.randint(low=1, high=seq_len+1, size=(batch_size,))
    dummy_output_lengths = torch.randint(low=1, high=seq_len+1, size=(batch_size,))
    dummy_output = torch.randn(batch_size, seq_len, 80)
    

    # Load the model architecture from the checkpoint
    model = AlignTTSModelClass(num_graphemes=num_graphemes, seq_len=seq_len)
    print(model)
    model.load_state_dict(checkpoint['model'], strict=False)

    # Export the model to ONNX format
    onnx_path = '/home/elias/male_model.onnx'
    
    onnx.export(model, (dummy_input, dummy_input_lengths, dummy_output, dummy_output_lengths), 
                onnx_path, export_params=True, opset_version=10)



    graph, out = torch._C._create_graph_by_tracing(
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/jit/_trace.py", line 118, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/elias/script/onnx_2.py", line 57, in forward
    return self.align_tts(x, x_lengths, y, y_lengths)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/TTS/tts/models/align_tts.py", line 247, in forward
    dr_mas, mu, log_sigma, logp = self._forward_mdn(o_en, y, y_lengths, x_mask)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/TTS/tts/models/align_tts.py", line 204, in _forward_mdn
    dr_mas, logp = self.compute_align_path(mu, log_sigma, y, x_mask, y_mask)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/TTS/tts/models/align_tts.py", line 108, in compute_align_path
    attn = maximum_path(log_p, attn_mask.squeeze(1)).unsqueeze(1)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/TTS/tts/utils/helpers.py", line 177, in maximum_path
    return maximum_path_numpy(value, mask)
  File "/home/elias/miniconda3/envs/elias-dev/lib/python3.10/site-packages/TTS/tts/utils/helpers.py", line 208, in maximum_path_numpy
    value = value * mask
RuntimeError: The size of tensor a (256) must match the size of tensor b (227) at non-singleton dimension 2 ```

**Comment by titaiwangms** [comment] 2023-05-03 13:30
It's supported in nightly. https://github.com/pytorch/pytorch/pull/99056

**Comment by titaiwangms** [comment] 2023-05-03 13:32
Closing this issue as the original problem has been solved. Feel free to open a new one!

**Closed by titaiwangms** 2023-05-03 13:32 UTC
Labels: module: onnx, triaged
