### ISSUE TITLE
Support channel first(or any dim) LayerNorm

### ISSUE THREAD

**Issue by PistonY** [pytorch/pytorch#74661] opened 2022-03-24 03:34 UTC
### 🚀 The feature, motivation and pitch

LayerNorm is widely used in Transformer and recently some CNN model(or Transformer + CNN model)  is trying to use this. But CNN has [B, C, H, W] output, that can not use LayerNorm which only support norm last N channel.

### Alternatives

Support specific dim of mean, not last N dim.

**Comment by vadimkantorov** [comment] 2022-03-24 13:29
related: https://github.com/pytorch/pytorch/issues/51455, https://github.com/pytorch/pytorch/issues/52143,

**Comment by vadimkantorov** [comment] 2022-03-24 13:56
duplicate of https://github.com/pytorch/pytorch/issues/71465?

**Comment by ngimel** [comment] 2022-03-24 16:57
Closing as a duplicate

**Closed by ngimel** 2022-03-24 16:57 UTC
