### ISSUE TITLE
[Documentation enhancement]: bold font for better readability for left panel

### ISSUE THREAD

**Issue by zuoxingdong** [pytorch/pytorch#11994] opened 2018-09-23 15:10 UTC
For current [documentation](https://pytorch.org/docs/master/nn.html), the font on the left panel is quite shallow and a bit hard to read. It might be nice to make it darker to improve the readability.

**Comment by vishwakftw** [comment] 2018-09-23 17:34
Duplicate of https://github.com/pytorch/pytorch/issues/11968 .

**Comment by zou3519** [comment] 2018-09-24 17:28
Closing because duplicate, please feel free to comment in that thread @zuoxingdong

**Closed by zou3519** 2018-09-24 17:28 UTC
