### ISSUE TITLE
torch.triu、torch.tril: gives different results under different devices.

### ISSUE THREAD

**Issue by triumph-wangyuyang** [pytorch/pytorch#89400] opened 2022-11-21 05:46 UTC
### 🐛 Describe the bug

Test on the CPU:

    import torch
    input = torch.randn(3)
    out = torch.triu(input)
    print(out)

result: IndexError: Dimension out of range (expected to be in range of [-1, 0], but got -2)

Test on the GPU:

    import torch
    input = torch.randn(3).cuda()
    out = torch.triu(input)
    print(out)

result: tensor([-0.2992,  1.0819,  1.2671], device='cuda:0')

torch.triu suggested that the input we input is a two-dimensional tensor, but when I deliberately used a one-dimensional tensor to test, I found that it failed on the CPU, but succeeded on the GPU.The same happens with the torch.tril operator.

### Versions

pytorch: 1.12.1
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.3
GPU models and configuration: RTX3060
Operating System：Windows

**Comment by ngimel** [comment] 2022-11-21 20:51
Duplicate of #83326

**Closed by ngimel** 2022-11-21 20:51 UTC
Labels: module: error checking, triaged
