### ISSUE TITLE
Intellisense on Windows doesn't report real error message by default

### ISSUE THREAD

**Issue by learner760221** [pytorch/pytorch#47900] opened 2020-11-13 06:21 UTC
## 🐛 Bug

Hi Guys:
I use CMake and the CMakeLists.txt is from pytorch.org , Libtorch 1.7 and Visual studio 2019,
I can output a tensor, it works just fine.
But there is a exception happened, when I simply run backward().
![image](https://user-images.githubusercontent.com/74396740/99035291-4794a200-25ba-11eb-862e-1d8359dfc255.png)

CMakeLists.txt I used.(just from pytorch.org )
![image](https://user-images.githubusercontent.com/74396740/99035101-d6ed8580-25b9-11eb-870c-61e581a898aa.png)

## To Reproduce

1. Download libtorch 1.7 debug cpu. (libtorch-win-shared-with-deps-debug-1.7.0+cpu.zip)
2. Use CMake just like pytorch.org recommended.
3. Run simple backward() function, and get exception.

## Environment

 - Win7 x64
 - Microsoft Visual Studio Professional 2019 version 16.8.0
 - libtorch-win-shared-with-deps-debug-1.7.0+cpu
 - CMake 3.18.4
 

### Anything wants me to pose to make this issue be reproduced and solve is welcome.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @peterjc123 @mszhanyi @skyline75489 @nbcsm @maxluk @guyang3532 @gunandrose4u @smartcat2010

**Comment by peterjc123** [comment] 2020-11-13 06:32
It seems to be an known issue on Windows 7. Could you please provide a backtrace or sth?

**Comment by learner760221** [comment] 2020-11-13 06:40
After putting all .pdb files into executed dir, I got this further error information.
**in c10 namespace**
![image](https://user-images.githubusercontent.com/74396740/99037089-01d9d880-25be-11eb-8bfa-939de73d95bb.png)

**Comment by learner760221** [comment] 2020-11-13 06:41
![image](https://user-images.githubusercontent.com/74396740/99037255-4feedc00-25be-11eb-9360-d4aaeec2da05.png)

**Comment by peterjc123** [comment] 2020-11-13 06:48
Could you please double link the second highlighted line in your second pic and then share a new screenshot?

**Comment by learner760221** [comment] 2020-11-13 06:51
@peterjc123  thanks you in advance. ^^
![image](https://user-images.githubusercontent.com/74396740/99037962-b58f9800-25bf-11eb-9f31-5d83a0045f38.png)

**Comment by peterjc123** [comment] 2020-11-13 07:06
No, I mean the line starting with `torch::autograd::_make_grads`.

**Comment by skyline75489** [comment] 2020-11-13 07:30
I can actually reproduce this on Windows. 

@learner760221  It would be nice if you just paste the code like this:

```cpp
int main() {
    torch::Tensor a = torch::ones({2, 2}, torch::requires_grad());
    torch::Tensor b = torch::randn({2, 2});
    torch::Tensor c = a + b;
    std::cout << c << std::endl;
    c.backward();
}
```

**Comment by learner760221** [comment] 2020-11-13 08:20
@skyline75489  OK ^^

**Comment by learner760221** [comment] 2020-11-13 08:21
It can not find the related cpp file.
![image](https://user-images.githubusercontent.com/74396740/99045388-381e5480-25cc-11eb-99b8-9a2de918fb34.png)

**Comment by learner760221** [comment] 2020-11-13 08:32
> I can actually reproduce this on Windows 10 x64.
> 
> @learner760221 It would be nice if you just paste the code like this:
> 
> ```c++
> int main() {
>     torch::Tensor a = torch::ones({2, 2}, torch::requires_grad());
>     torch::Tensor b = torch::randn({2, 2});
>     torch::Tensor c = a + b;
>     std::cout << c << std::endl;
>     c.backward();
> }
> ```

Thanks for trying that in Win10, because I plan to try it on Win 10. But I don't have to now.

**Comment by skyline75489** [comment] 2020-11-13 09:05
The error was caused by this line https://github.com/pytorch/pytorch/blob/e85d494707b835c12165976b8442af54b9afcb26/torch/csrc/autograd/autograd.cpp#L45

And I think it's expected? The `output.numel()` is 4 in this case, and the assertion is `output.numel() == 1`.

**Comment by learner760221** [comment] 2020-11-13 09:12
it seems that you got all the source code and can debug line by line. 
Am I right ? 
Where can I get all the source codes and debug like you did ?

**Comment by peterjc123** [comment] 2020-11-13 09:14
@learner760221 
```
git clone https://github.com/pytorch/pytorch.git --recursive -b v1.7.0
```

**Comment by skyline75489** [comment] 2020-11-13 09:18
Well, there's your beginner's guide:

See that "测试并寻找 autograd.cpp" button? All you need to do is find the correct version of `autograd.cpp`. In this case, you'll need v1.7.0 version of PyTorch. You can do this locally using `git checkout` , or you can use Github to browse the code at `1.7.0` (https://github.com/pytorch/pytorch/blob/v1.7.0/torch/csrc/autograd/autograd.cpp). Once you found the source code, the rest is a piece of cake. Just download it and feed it to VS, and you're good to go.

Note that finding the correct version is important. It has to be the exact match with the pdb. Otherwise VS will refuse to load the source file.

**Comment by skyline75489** [comment] 2020-11-13 09:20
@peterjc123 One thing I didn't expect is that the error message in `TORCH_CHECK` seems to be completely ignored. Is this normal? This would cause so many users confused with the exceptions, because there's no way they would know whether the error is cause by user code or PyTorch itself.

**Comment by peterjc123** [comment] 2020-11-13 09:31
@skyline75489 It isn't ignored (as you can see the message in the original command prompt) but is not properly shown in Intellisense. Maybe we should improve it.

**Comment by peterjc123** [comment] 2020-11-13 09:46
@skyline75489 After some simple googling, it seems that VS itself doeen't enable viewing the message of an exception on default. You'll have to switch it on manually. https://stackoverflow.com/questions/43231974/can-i-view-an-unhandled-exception-in-the-visual-studio-2017-debugger/46348413

**Comment by skyline75489** [comment] 2020-11-13 09:48
Yeah I found it, too. I feel terrible that people have to explicitly catch it like this:

```cpp
    try
    {
        torch::Tensor a = torch::ones({2, 2}, torch::requires_grad());
        torch::Tensor b = torch::randn({2, 2});
        torch::Tensor c = a + b;
        std::cout << c << std::endl;
        c.backward();
    }
    catch (std::exception &e)
    {
        std::cout << e.what() << std::endl;
    }
```

It would confuse so many people..

**Comment by peterjc123** [comment] 2020-11-13 09:52
@skyline75489 Maybe you should put up an issue to the VS team as a MSFT employee. LOL.

**Comment by peterjc123** [comment] 2020-11-13 09:55
@albanD Any thoughts on this?

**Comment by skyline75489** [comment] 2020-11-13 10:12
I think that adding more logging would also help. Otherwise, there's almost no information provided by LibTorch itself.

Is there some kind of debug switch we could ask people to use?

**Comment by albanD** [comment] 2020-11-13 15:32
@peterjc123 my thoughts about the error or the reporting?
For the error, the python version of that code:
```python
import torch
a = torch.ones(2, 2, requires_grad=True);
b = torch.randn(2, 2);
c = a + b;
print(c)
c.backward();
```
Does raise the proper error: "RuntimeError: grad can be implicitly created only for scalar outputs"

And I guess that this is the message in the TORCH_CHECK that happens in c++ is very similar?
So the error message itself sounds good to me.


For the reporting side. I am not sure to grasp the whole discussion here. But if VS eats up the error message, there is not much we can do right?

@skyline75489 What do you have in mind for "I think that adding more logging would also help."? What kind of information are you looking for here?

**Comment by peterjc123** [comment] 2020-11-14 05:25
@albanD Thanks for your reply.  
@learner760221 So the error is real. You could not do this.
@skyline75489 Yeah, I' m not sure which kind of information you want here. Actually, we wrapped something (like line of code, error message and even backtrace) into the `c10::Error` object. If we want to always print out the message for Debug builds. Maybe we could do sth in the constructor of `c10::Error` for MSVC only.

**Comment by skyline75489** [comment] 2020-11-14 10:39
@albanD @peterjc123  I was thinking something like `OutputDebugString`, to add least give _something_ that can help users with debugging. But you're right. I'm disappointed that VS eats up the error message. I'm even more disappointed that we don't seem to have a way to mitigate it .

**Comment by peterjc123** [comment] 2020-11-14 12:40
@skyline75489 Maybe we could use `_wassert`. 
```
#ifndef NDEBUG
  if (IsDebuggerPresent()) {
    _wassert(L"OMG", _CRT_WIDE(__FILE__), static_cast<unsigned>(__LINE__));
  }
#endif
```
The error message is printed out in the command prompt in this case and a modal message dialog is shown.

**Comment by mantaionut** [comment] 2023-04-24 10:09
This issue is purely a Visual Studio debugger issue since it can also happen with simple example:
```
#include <iostream>
#include <exception>
int main()
{
   throw std::bad_alloc();
   return 0;
}
```
So I am going to close this issue.
@learner760221 since this is a Visual Studio issue please open an issue https://developercommunity.visualstudio.com/t/ here instead.

**Closed by mantaionut** 2023-04-24 10:09 UTC
Labels: high priority, module: dependency bug, module: windows, module: error checking, module: molly-guard, triaged
