### ISSUE TITLE
`mp.spawn` fail when passing large dict of shared-memory-Tensors as args

### ISSUE THREAD

**Issue by JiaRu2016** [pytorch/pytorch#41481] opened 2020-07-15 16:56 UTC
## 🐛 Bug

Inconsistent behavior of `mp.spawn` when passing different "size" of dict of Tensors as `args`. As the number of dict elements grow, it raise different type of errors. See reproduce code for details.

## To Reproduce

```python
import torch
import torch.multiprocessing as mp    
import time

def main_worker(rank, share_memory_resources):
    print(f'rank={rank}')
    print(share_memory_resources['X'][0][:5])
    print(share_memory_resources['y'][0][:5])
    while True:
        time.sleep(5)
    
def main():
    world_size = 4
    n, m =  10, 360
    n_keys = 3000    # <---------- different number of `n_keys` gives different results
    #  3000: RuntimeError: unable to open shared memory object </torch_71861_711505626> in read-write mode
    #  500: OSError: [Errno 24] Too many open files
    #  100: OK

    share_memory_resources = {
        'X': {
            i: torch.rand(size=(n, m)) for i in range(n_keys)
        },
        'y': {
            i: torch.rand(size=(n, m)) for i in range(n_keys)
        }
    }

    # calculate memory_usage. Optional
    total_memory_usage = 0.0
    for k, inner_dict_ in share_memory_resources.items():
        for k_, v_ in inner_dict_.items():
            total_memory_usage += v_.data.numpy().nbytes
    print(f'total_memory_usage = {total_memory_usage / 1024 ** 2} MB')
    
    mp.spawn(main_worker, args=(share_memory_resources, ), nprocs=world_size, join=True)

if __name__ == "__main__":
    main()    
```

if n_keys = 100, No Error.
if n_keys = 500:  raise `OSError: [Errno 24] Too many open files`  

<details>
 <summary> here is full traceback </summary>

```python
total_memory_usage = 13.73291015625 MB
Traceback (most recent call last):
  File "reproduce_Error_Unable_to_open_ShareMemory_object.py", line 37, in <module>
    main()
  File "reproduce_Error_Unable_to_open_ShareMemory_object.py", line 34, in main
    mp.spawn(main_worker, args=(share_memory_resources, ), nprocs=world_size, join=True)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
    process.start()
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 58, in _launch
    self.pid = util.spawnv_passfds(spawn.get_executable(),
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/util.py", line 450, in spawnv_passfds
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*sta
```
</details>

if n_keys = 3000:  raise `RuntimeError: unable to open shared memory object </torch_71861_711505626> in read-write mode`  

<details>
 <summary> here is full traceback </summary>

```python
total_memory_usage = 82.3974609375 MB
Traceback (most recent call last):
  File "reproduce_Error_Unable_to_open_ShareMemory_object.py", line 34, in <module>
  File "reproduce_Error_Unable_to_open_ShareMemory_object.py", line 31, in main
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 149, in start_processes
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/process.py", line 121, in start
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
  File "/home/rjia/anaconda3/envs/gpu38/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 333, in reduce_storage
RuntimeError: unable to open shared memory object </torch_71861_711505626> in read-write mode
```
</details>

## Environment

```
PyTorch version: 1.5.1+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.17.1

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti
GPU 8: GeForce RTX 2080 Ti
GPU 9: GeForce RTX 2080 Ti

Nvidia driver version: 440.59
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.1+cu101
[pip3] torchvision==0.6.1+cu101
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.5.1+cu101              pypi_0    pypi
```

 - PyTorch Version (e.g., 1.0): 1.5.1+cu101
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source):  conda
 - Build command you used (if compiling from source):  no
 - Python version: 3.8
 - CUDA/cuDNN version:  CUDA 10.1
 - GPU models and configuration: didn't use GPU yet
 - Any other relevant information:

**Comment by ezyang** [comment] 2020-07-16 02:42
If I understand correctly, we created a shared memory file per tensor. You appear to be running out of shared memory. you can increase the amount of shm using sysctl.

**Comment by JiaRu2016** [comment] 2020-07-16 05:47
For those who do not havesudo authentication,  a temp solution is changing share_strategy to file_system (instead of default file_descriptor):

```python
mp.set_sharing_strategy('file_system')
```

**Comment by ezyang** [comment] 2020-07-16 15:52
closing as not a bug

**Closed by ezyang** 2020-07-16 15:52 UTC
Labels: module: multiprocessing, triaged
