### ISSUE TITLE
[Export] AssertionError in replace_autocast_with_hop_pass

### ISSUE THREAD

**Issue by desertfire** [pytorch/pytorch#140589] opened 2024-11-13 19:12 UTC
Repro:
//  See https://huggingface.co/nvidia/NV-Embed-v1 for installation instructions
//  Basically `pip install transformers` and make sure you have huggingface access

```
import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel

# Each query needs to be accompanied by an corresponding instruction describing the task.
task_name_to_instruct = {"example": "Given a question, retrieve passages that answer the question",}

query_prefix = "Instruct: "+task_name_to_instruct["example"]+"\nQuery: "
queries = [
    'are judo throws allowed in wrestling?',
    'how to become a radiology technician in michigan?'
    ]

# No instruction needed for retrieval passages
passage_prefix = ""
passages = [
    "Since you're reading this, you are probably someone from a judo background or someone who is just wondering how judo techniques can be applied under wrestling rules. So without further ado, let's get to the question. Are Judo throws allowed in wrestling? Yes, judo throws are allowed in freestyle and folkstyle wrestling. You only need to be careful to follow the slam rules when executing judo throws. In wrestling, a slam is lifting and returning an opponent to the mat with unnecessary force.",
    "Below are the basic steps to becoming a radiologic technologist in Michigan:Earn a high school diploma. As with most careers in health care, a high school education is the first step to finding entry-level employment. Taking classes in math and science, such as anatomy, biology, chemistry, physiology, and physics, can help prepare students for their college studies and future careers.Earn an associate degree. Entry-level radiologic positions typically require at least an Associate of Applied Science. Before enrolling in one of these degree programs, students should make sure it has been properly accredited by the Joint Review Committee on Education in Radiologic Technology (JRCERT).Get licensed or certified in the state of Michigan."
]

# load model with tokenizer
model = AutoModel.from_pretrained('nvidia/NV-Embed-v1', trust_remote_code=True)

# get the embeddings
max_length = 4096

class ExportWrapper(torch.nn.Module):
    def __init__(self, fn):
        super().__init__()
        self.fn = fn

    def forward(self, *args, **kwargs):
        return self.fn(*args, **kwargs)

encode = ExportWrapper(model.encode)
exported = torch.export.export(encode, (queries,), {"instruction": query_prefix, "max_length": max_length}, strict=False)
```

Error:
```
Traceback (most recent call last):
  File "/data/users/binbao/pytorch/aoti_nv_embed_v1/model.py", line 36, in <module>
    exported = torch.export.export(encode, (queries,), {"instruction": query_prefix, "max_length": max_length}, strict=False)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/__init__.py", line 368, in export
    return _export(
           ^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/_trace.py", line 1031, in wrapper
    raise e
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/_trace.py", line 1004, in wrapper
    ep = fn(*args, **kwargs)
         ^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/exported_program.py", line 122, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/_trace.py", line 1957, in _export
    export_artifact = export_func(  # type: ignore[operator]
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/_trace.py", line 1745, in _non_strict_export
    aten_export_artifact = _to_aten_func(  # type: ignore[operator]
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/_trace.py", line 775, in _export_to_aten_ir
    return _produce_aten_artifact(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/export/_trace.py", line 472, in _produce_aten_artifact
    gm, export_graph_signature = replace_autocast_with_hop_pass(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/_export/passes/replace_autocast_with_hop_pass.py", line 175, in replace_autocast_with_hop_pass
    return _replace_with_hop_pass_helper(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/_export/passes/replace_with_hop_pass_util.py", line 160, in _replace_with_hop_pass_helper
    new_gm, new_signature = sequential_split_and_maybe_inline_subgraphs(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/_export/passes/replace_autocast_with_hop_pass.py", line 155, in _sequential_split_and_maybe_inline_subgraphs
    new_gm = _split_autocast(gm)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/_export/passes/replace_autocast_with_hop_pass.py", line 135, in _split_autocast
    return sequential_split(gm, node_call_back)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/_export/utils.py", line 516, in sequential_split
    if node_call_back(node):
       ^^^^^^^^^^^^^^^^^^^^
  File "/home/binbao/local/miniconda3/envs/nightly/lib/python3.11/site-packages/torch/_export/passes/replace_autocast_with_hop_pass.py", line 128, in node_call_back
    assert node.args[0] == last_enter_autocast_node
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

cc @ezyang @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by desertfire** [comment] 2024-11-13 19:15
cc @yushangdi , assigning to you since you are the author of replace_autocast_with_hop_pass

**Comment by yushangdi** [comment] 2024-11-13 19:19
> cc @yushangdi , assigning to you since you are the author of replace_autocast_with_hop_pass

I'll take a look, thanks for reporting!

**Comment by yushangdi** [comment] 2024-11-14 21:30
The problem is that the current pass doesn't work well with nested autocast. I'll push a fix soon.

**Comment by yushangdi** [comment] 2024-11-19 23:28
I fixed the HOP pass error (Diffs landing, will reference them here once landed), but now I got a new error:

```
*** AttributeError: 'str' object has no attribute 'is_leaf'
```

Here: https://github.com/pytorch/pytorch/blob/9bc9d4cdb4355a385a7d7959f07d04d1648d6904/torch/export/_trace.py#L374


```
(Pdb) node
args_0_0
(Pdb) node.meta["val"]
'are judo throws allowed in wrestling?'
(Pdb) constant
tensor([[ 1.3182e-05,  4.4750e-03,  6.8875e-03,  ...,  5.0471e-03,
          7.6632e-03, -1.4466e-02],
        [ 1.0200e-02,  3.5591e-03, -5.6193e-03,  ..., -3.6126e-03,
         -1.5038e-02,  1.2344e-02],
        [-8.0463e-03, -2.9622e-03, -8.8552e-03,  ..., -1.1424e-02,
          1.0817e-02, -1.5624e-02],
        ...,
        [-3.5589e-03,  1.0632e-02,  5.5020e-03,  ..., -1.0838e-02,
         -1.2318e-02,  8.2871e-03],
        [-1.5981e-03, -8.8693e-03,  1.8261e-03,  ..., -2.2536e-03,
         -1.3661e-02, -1.2246e-02],
        [-5.8632e-03, -4.6527e-03, -4.5240e-03,  ...,  1.2603e-02,
          2.6685e-03, -2.3300e-03]])
```

This seems like a different bug now, and unrelated to the HOP pass now.

@tugsbayasgalan Do you know what's wrong here?

**Closed** 2024-11-22 01:08 UTC
Labels: oncall: pt2, oncall: export, empathy-day
