### ISSUE TITLE
Unknown CMake command "cuda_select_nvcc_arch_flags"

### ISSUE THREAD

**Issue by txdat** [pytorch/pytorch#8269] opened 2018-06-08 02:18 UTC
I have this error while building pytorch from source with gtx1060, cuda9.2, and cudnn7.1.4 on ubuntu 16.04

-- Caffe2: Found protobuf with new-style protobuf targets.
-- Caffe2: Protobuf version 3.5.0
-- Caffe2: CUDA detected: 9.2
-- Caffe2: CUDA nvcc is: /usr/local/cuda/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr/local/cuda
-- Caffe2: Header version is: 9.2
-- Found cuDNN: v7.1.4  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so.7)
CMake Error at /home/dat/.py/pytorch/torch/lib/tmp_install/share/cmake/Caffe2/public/cuda.cmake:338 (cuda_select_nvcc_arch_flags):
  Unknown CMake command "cuda_select_nvcc_arch_flags".
Call Stack (most recent call first):
  /home/dat/.py/pytorch/torch/lib/tmp_install/share/cmake/Caffe2/Caffe2Config.cmake:79 (include)
  CMakeLists.txt:7 (FIND_PACKAGE)

-- Configuring incomplete, errors occurred!
See also "/home/dat/.py/pytorch/torch/lib/build/libshm/CMakeFiles/CMakeOutput.log".
See also "/home/dat/.py/pytorch/torch/lib/build/libshm/CMakeFiles/CMakeError.log".
Failed to run 'bash tools/build_pytorch_libs.sh --with-cuda --with-nnpack nccl caffe2 nanopb libshm gloo THD'

**Comment by Yangqing** [comment] 2018-06-08 02:47
This is probably my fault due to #8200. What is your cmake version?

**Comment by soumith** [comment] 2018-06-08 02:48
i'm taking a look. it's a duplicate of https://github.com/pytorch/pytorch/issues/8249

**Comment by soumith** [comment] 2018-06-08 02:48
it turns out https://github.com/pytorch/pytorch/tree/master/cmake/Modules_CUDA_fix is not being included in latest master, under certain cmakes

**Comment by Yangqing** [comment] 2018-06-08 02:55
thanks @soumith ! basically the problem is we include the CUDA fix only in certain versions:

https://github.com/pytorch/pytorch/blob/4bf0202cac4cdf95bf437df5d2e8a8c5bb892569/cmake/MiscCheck.cmake#L264-L277

**Comment by soumith** [comment] 2018-06-08 02:58
@txdat what is the output of `cmake --version`?

**Comment by txdat** [comment] 2018-06-08 03:08
@soumith 
cmake --version
cmake version 3.5.1

CMake suite maintained and supported by Kitware (kitware.com/cmake).

**Comment by Yangqing** [comment] 2018-06-08 03:17
This seems to be because the inclusion is only there if you invoke it from the root CMakeLists.txt file, which further includes cmake/MiscCheck.cmake. In this case, it seems that the error is from torch/lib/build/libshm/ which is using setup.py and Extension (IIRC) which does not have that cmake path. I wrote up a quick fix at #8271 but my laptop has a newer CMake, so I will have to check it when I get back home today. Basically I moved the inclusion logic directly to public/cuda.cmake and included that as part of the installation too.

**Comment by Yangqing** [comment] 2018-06-08 04:51
#8271 passed our manual check (thanks @soumith) and is landed. I assume this would fix the issue, so closing this for now - feel free to reopen if problem persists!

**Closed by Yangqing** 2018-06-08 04:51 UTC

**Comment by divyansh2681** [comment] 2023-09-11 19:34
Hi, I am also facing the same issue. 

```
CMake Error at /home/divyansh/.local/lib/python3.10/site-packages/torch/share/cmake/Caffe2/public/utils.cmake:401 (cuda_select_nvcc_arch_flags):
  Unknown CMake command "cuda_select_nvcc_arch_flags".
Call Stack (most recent call first):
  /home/divyansh/.local/lib/python3.10/site-packages/torch/share/cmake/Caffe2/public/cuda.cmake:362 (torch_cuda_get_nvcc_gencode_flag)
  /home/divyansh/.local/lib/python3.10/site-packages/torch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  /home/divyansh/Documents/libtorch/share/cmake/Torch/TorchConfig.cmake:68 (find_package)
  CMakeLists.txt:288 (find_package)
```
My cmake version is: 3.27.0
