### ISSUE TITLE
Issues with multithreading in autograd profiler

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#32883] opened 2020-01-31 22:39 UTC
## 🐛 Bug
Was experimenting with using the autograd profiler in multithreaded scenarios and ran into a couple of issues that I would like to bring up:

1. Crashes when profiling is run on two separate threads: 
Repro (might take a couple tries):
```
def test_two_threads_crash(self):
        import threading
        def torch_adds():
            with torch.autograd.profiler.profile() as prof:
                return torch.add(1,1)
            print(prof.key_averages().table(sort_by="self_cpu_time_total"))
        def torch_mul():
            with torch.autograd.profiler.profile() as p1:
                torch.mul(1,1)

        t1 = threading.Thread(target=torch_adds, args=())
        t2 = threading.Thread(target=torch_mul, args=())
        t1.start() ; t2.start()
        t1.join() ; t2.join()
```
Stacktrace:
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "test/test_autograd.py", line 258, in torch_mul
    torch.mul(1,1)
  File "/home/rvarm1/pytorch/torch/autograd/profiler.py", line 286, in __exit__
    records = torch.autograd._disable_profiler()
RuntimeError: can't disable profiler when it's not running
```

It looks like there is a race to disable the profiler and the thread that loses has the exception thrown. What I would expect here is the profiler output being printed for both threads, one should have torch.add() and the other should have torch.mul(), since that is what we are explicitly profiling on the respective threads.

2. Segfault when profiling is running on one thread, and we are running threads with torch ops in the background:
Repro (Might take a couple tries):
```
def test_multithread_profiler(self):
        import threading
        def torch_mul():
            # yield
            import time ; time.sleep(0)
            return torch.mul(1,1)

        t2 = threading.Thread(target=torch_mul, args=())
        t2.start()
        with torch.autograd.profiler.profile() as prof:
            import time ; time.sleep(0) # yield
            torch.add(1,1)

        t2.join()
        print(prof.key_averages().table(sort_by="self_cpu_time_total"))
```
Stacktrace is just `Segmentation fault (core dumped)`

It looks like there is a segfault in `disableProfiler()`. I don't think we should crash here, the profile should be printed with only a `torch.add()` since we aren't explicitly profiling the other threads.

## Environment

This happens when built from source on latest master.

cc @ezyang @SsnL @albanD @zou3519 @gqchen @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by rohan-varma** [comment] 2020-01-31 22:40
cc @pritamdamania87

**Comment by rohan-varma** [comment] 2020-01-31 22:44
I added the RPC label since this is a use case we'd eventually like to support with RPC based training

**Comment by pritamdamania87** [comment] 2020-02-03 19:56
@ezyang @albanD @d4l3k We were wondering if we had evaluated running the autograd profiler from multiple threads before? A potential use case is where we might want to profile multiple jit threads separately (when using torch.jit._fork and torch.jit._wait). I guess torchscript doesn't support the `with autograd.profiler` clause yet, but this might be useful in the future.

**Comment by albanD** [comment] 2020-02-03 20:54
Hi,

I don't recall any discussion about this (but very possible I missed it if one happened).
But at the time where the profiler was created. Pytorch was python-only and everything there was single threaded. So I wouldn't be surprised if there are oversight here. In particular with the fact that all threads use the same autograd engine.

I would agree that it should at least not crash. And if possible return sensible data (or raise a meaningful error saying that we do not support profiling from different threads at once).

**Comment by ezyang** [comment] 2020-02-04 21:33
I agree that in principle the profiler should work in multiple threads; it was likely just not designed with it in mind

**Comment by jamesr66a** [comment] 2020-02-10 23:49
cc @ilia-cher who I believe looked into this before

**Comment by ilia-cher** [comment] 2020-02-11 03:09
profiler is indeed not thread-safe - in the previous discussion perf-related concerns were raised;
with a reasonable multiple readers single writer lock implementation it should be possible to make it thread safe

**Comment by ilia-cher** [comment] 2020-08-27 21:55
closing as profiler was rewritten to become thread safe to use

**Closed by ilia-cher** 2020-08-27 21:55 UTC
Labels: module: autograd, module: rpc, topic: crash, topic: multithreading, triaged

**Comment by vicilliar** [comment] 2023-08-31 03:21
> 

Hi @rohan-varma , sorry to bump this again, but do you know what Torch version you were using when the segmentation fault occurred? The reason is that I'm attempting to do a multi-threaded speed comparison between Torch 1.12.1 and 2.1.0: https://discuss.pytorch.org/t/torch-gets-slower-when-upgrading-the-version/186525/7

In both cases, multi-threaded profiling does not work as intended.
