### ISSUE TITLE
trymerge workflow should do a better job showing progress

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#80201] opened 2022-06-24 02:46 UTC
When you click a mergebot workflow link, the output is not very informative, because GitHub does not show historical logs for running jobs. It only shows logs that have been printed since you opened the page. This gives people the impression that the job is hanging even when it's actively waiting for a job to finish (feedback raised by @linbinyu).

We should be printing comprehensible updates every ~5 seconds so that people can see what the `trymerge` job is doing.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by suo** [comment] 2022-06-24 02:47
@zengk95 do you mind taking a look?

**Comment by ZainRizvi** [comment] 2022-10-28 22:07
Dupe of https://github.com/pytorch/pytorch/issues/78940

**Closed by ZainRizvi** 2022-10-28 22:07 UTC
Labels: module: ci, triaged, mergebot
