### ISSUE TITLE
torch/lib/c10d/test/ProcessGroupNCCLTest.cpp  isn't being built in CI

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#10699] opened 2018-08-20 19:32 UTC
See #10698

**Comment by mcarilli** [comment] 2018-08-20 19:42
duplicate of https://github.com/pytorch/pytorch/issues/10687, i believe.

**Comment by pietern** [comment] 2018-09-20 22:13
Caused by:

```
Found NCCL, but the NCCL version is either not 2+ or not determinable, will not compile with NCCL distributed backend
```

Yet NCCL 2 is installed in the environment. Something is triggering building the bundled version of NCCL (NCCL version 1) and that is taking precedence over the installed one.

**Comment by pietern** [comment] 2018-09-20 22:14
FYI, I looked at this build: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-xenial-cuda8-cudnn6-py3-build/23936/consoleFull

**Comment by teng-li** [comment] 2018-11-14 22:38
This should be fixed now I believe

**Closed by teng-li** 2018-11-14 22:38 UTC
Labels: distributed
