### ISSUE TITLE
setting self.maxDiff = None in CI does nothing (for expecttest)

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118226] opened 2024-01-24 21:09 UTC
We set it here: https://github.com/pytorch/pytorch/blob/main/test/dynamo/test_aot_autograd.py#L841C9-L841C28

Locally, if the test fails (it's flaky), then it'll print out the diff. But in CI, it never does:
![image](https://github.com/pytorch/pytorch/assets/5652049/74df6901-50d5-42a3-b0e6-f553028a7c58), e.g. https://ossci-raw-job-status.s3.amazonaws.com/log/19579164076

cc @ZainRizvi @kit1980 @huydhn @clee2000

**Comment by zou3519** [comment] 2024-01-24 21:10
tbh we should probably just have this setting on for all expecttest in CI since we do a lot of logging.

**Comment by clee2000** [comment] 2024-07-26 23:51
I can't reproduce this anymore, see my extremely contrived example https://hud.pytorch.org/pr/pytorch/pytorch/131954#27984856176 so I'm going to close this.  We do set maxDiff = None in the TestCase class, but that's been there since before this issue got made.  

Please feel free to open if you see it happening again

**Closed by clee2000** 2024-07-26 23:51 UTC
Labels: triaged, module: devx
