### ISSUE TITLE
Cant Build On Windows-Cannot Open file ``tbb.lib"

### ISSUE THREAD

**Issue by magicwyzh** [pytorch/pytorch#8150] opened 2018-06-05 04:03 UTC
## Issue description
Hi,
I want to build pytorch from source on windows. I follow the step in the official github site, and all required dependencies are installed.

However, when i run ``python setup.py build", i meet the following error:

LINK: fatal error LNK1104: cannot open file `tbb.lib’ [C:\Users\yizhiw\pytorch\build\caffe2\apply_utils_test.vcxproj]
Provide a short description.
![image 1](https://user-images.githubusercontent.com/19240414/40954495-6945efac-68b7-11e8-9736-b305c9418c7d.png)

I found tbb.lib is from intel SW tools, so I also installed it in my computer. But it seems it doesn't work...

My OS is win10, and the visual studio 2017 professional version is installed.

A simple environment setting script I used is as below:
`set CMAKE_INCLUDE_PATH=C:\Users\yizhiw\pytorch\mkl\include

set MAGMA_HOME=C:\Users\yizhiw\pytorch\magma
set CMAKE_PREFIX_PATH=C:\Users\yizhiw\AppData\Local\Continuum\anaconda3
set VS150COMNTOOLS=C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\VC\Auxiliary\Build
set CMAKE_GENERATOR=Visual Studio 15 2017 Win64

set DISTUTILS_USE_SDK=1
set MKLProductDIR=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows
set LIB=%MKLProductDir%\mkl\lib\intel64_win;%LIB%;
set LIB=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\tbb\lib\intel64\vc14;%LIB%
set LD_LIBRARY_PATH=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\tbb\lib\intel64\vc14;%LD_LIBRARY_PATH%
set LIBRARY_PATH=C:\Program Files (x86)\IntelSWTools\compilers_and_libraries\windows\tbb\lib\intel64\vc14;%LIBRARY_PATH%
set CMAKE_INCLUDE_PATH=%MKLProductDIR%\mkl\include

REM The following line is needed for Python 2.7, but the support for it is very experimental.
set MSSdk=1
call "%VS150COMNTOOLS%\vcvarsall.bat" x64 -vcvars_ver=14.11
`

Please help me,
Thanks a lot!!

**Comment by SsnL** [comment] 2018-06-05 18:38
@peterjc123 also reproduced this

**Comment by peterjc123** [comment] 2018-06-07 04:31
@magicwyzh Ah! A step is missing. You'll also need to specify the environmental variable `CMAKE_INCLUDE_DIR` to take in the Anaconda include dir.

**Comment by Wangwentao1** [comment] 2018-06-09 15:00
I also reproduced this

**Comment by peterjc123** [comment] 2018-06-10 02:11
@Wangwentao1 Does setting the current `CMAKE_INCLUDE_DIR` and `LIB` helps?

**Comment by peterjc123** [comment] 2018-06-12 02:09
So the complete workground is:
```CMD
conda install tbb -y

set USER_LDFLAGS=/LIBPATH:[AnacondaRoot]\Library\lib
set CMAKE_INCLUDE_PATH=[AnacondaRoot]\Library\include
set LIB=[AnacondaRoot]\Library\lib;%LIB%

python setup.py install
```

**Comment by zou3519** [comment] 2018-06-26 16:38
This is fixed on master because we are not building with tbb anymore: https://github.com/pytorch/pytorch/pull/8255

**Closed by zou3519** 2018-06-26 16:38 UTC
