### ISSUE TITLE
Bug with torch.matmul?（CPU torch1.3）

### ISSUE THREAD

**Issue by PierreHao** [pytorch/pytorch#28644] opened 2019-10-25 07:00 UTC
## To Reproduce

1. if we use torch.matmul(a, a.t()) on cpu with torch1.3 (a is a tensor with size (1024, 2)),  we will get Segmentation fault
1. if tensor size is (5, 2), it runs well
1. if matmul on gpu, it runs well. and with torch1.1, it runs well on cpu

1. import torch as th
2. a = th.ones(5,2)
3. th.matmul(a, a.t())
it runs well
4. a = th.ones(1024, 2)
5. th.matmul(a, a.t())
Segmentation fault
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3
 - OS (e.g., Linux): centos 7.2
 - How you installed PyTorch (`conda`, `pip`, source): conda3
 - Build command you used (if compiling from source): pip install torch-1.3.0+cu92-cp36-cp36m-linux_x86_64.whl
 - Python version: 3.6
 - CUDA/cuDNN version: 9.0
 - GPU models and configuration: V100
 - Any other relevant information:

## Additional context

I tried matmul on mac, it runs well

**Comment by gchanan** [comment] 2019-10-25 15:44
I wasn't able to reproduce this with the wheel you mentioned.

**Comment by PierreHao** [comment] 2019-10-28 07:55
> I wasn't able to reproduce this with the wheel you mentioned.

I have tried with torch1.2, the same problem. But with torch1.1 it runs well. 
mkl-fft 1.0.0
mkl-random 1.0.1
numpy 1.14.3
and any other libs do torch.matmul depend on ?

**Comment by mruberry** [comment] 2020-10-08 07:09
Closing this due to age and lack of reproduction. If you're still encountering this problem on a more recent PyTorch release please update and reopen the issue.

**Closed by mruberry** 2020-10-08 07:09 UTC
Labels: module: mkl, needs reproduction, triaged
