### ISSUE TITLE
[feature request] Implement derivative for eig

### ISSUE THREAD

**Issue by carlosgmartin** [pytorch/pytorch#10503] opened 2018-08-14 05:06 UTC
## Issue description
Implement derivative for `torch.eig(a, eigenvectors=True)`.

## Code example
```
import torch
a = torch.tensor(1., requires_grad=True)
(a * torch.eye(3)).eig(eigenvectors=True)[1].sum().backward()
```

yields
```
RuntimeError: the derivative for 'eig' is not implemented
```

## System Info
```
$ python collect_env.py
Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 9.2.148
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     0.4.1                     <pip>
[conda] torchvision               0.2.1                     <pip>
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.1.0 (clang-902.0.39.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
$ pip --version
pip 18.0 from /anaconda3/lib/python3.6/site-packages/pip (python 3.6)
```

**Comment by vishwakftw** [comment] 2018-08-14 07:07
Derivative for `symeig` is available.

This is a duplicate of https://github.com/pytorch/pytorch/issues/6890 which got closed due to #8586 .

**Comment by carlosgmartin** [comment] 2018-08-14 07:12
Isn't `symeig` only for symmetric matrices?

**Comment by vishwakftw** [comment] 2018-08-14 07:13
Yes, that's correct. I just thought I should let you just in case. :)

**Comment by ElleryL** [comment] 2018-08-27 07:38
How do I update my pytorch to incorporate the the derivative implementation for symeig? I still have RuntimeError: the derivative for 'symeig' is not implemented

**Comment by vishwakftw** [comment] 2018-08-27 07:40
@ElleryL What version of PyTorch are you using?

**Comment by ElleryL** [comment] 2018-08-27 07:41
@vishwakftw I'm using '0.4.0'

**Comment by vishwakftw** [comment] 2018-08-27 07:45
@ElleryL The derivative for `symeig` is available on `master`. Please upgrade your installation.

**Comment by ElleryL** [comment] 2018-08-27 07:52
@vishwakftw I have updated to 0.4.1 and still have the error; can you please refer me some link of how to upgrade on master?

**Comment by liuyvchi** [comment] 2018-08-29 08:35
@vishwakftw @ElleryL Dose it mean that the derivative for symeig is available on 0.4.1?

**Comment by ElleryL** [comment] 2018-08-29 08:37
@liuyvchi No, you have to install your pytorch up to the master branch source code. But I think they will release this version very soon

**Comment by liuyvchi** [comment] 2018-08-29 08:40
@ElleryL  Thanks !

**Comment by soumith** [comment] 2018-08-29 17:57
@liuyvchi yes.

**Comment by euhruska** [comment] 2018-09-29 20:09
any estimate when the derivative for non-symmetric matrices will be implemented?

**Comment by euhruska** [comment] 2018-10-10 21:09
any update?

**Comment by euhruska** [comment] 2018-11-05 17:48
@vishwakftw @soumith Status?

**Comment by euhruska** [comment] 2018-12-04 23:11
Hello

**Comment by Molugan** [comment] 2019-01-22 09:55
Well if you have any info on this I am also interested.

**Comment by xtibau** [comment] 2019-02-21 16:58
Any updates here?

**Comment by musikisomorphie** [comment] 2019-03-12 20:45
@zou3519, though this task is non-trivial for me, I would like to try it, is it okay?

**Comment by soumith** [comment] 2019-03-13 09:12
@musikisomorphie go for it

**Comment by musikisomorphie** [comment] 2019-03-13 16:19
@soumith, I will keep you informed if I make progress.

**Comment by carlosgmartin** [comment] 2019-09-29 16:31
@musikisomorphie Any success?

**Comment by musikisomorphie** [comment] 2019-10-01 11:46
@carlosgmartin, unfortunately for non-symmetric matrices there is no deterministic derivative, after reading some papers I think computing its derivative is an ill-posed problem.

**Comment by carlosgmartin** [comment] 2019-10-01 16:15
@musikisomorphie That seems doubtful. Where did you read that?

See [this paper](https://www.emis.de/journals/ELA/ela-articles/articles/vol16_pp300-314.pdf) (Computation of eigenvalue and eigenvector derivatives for a general complex-valued eigensystem by van der Aa et al.):

> A method is provided to compute first order derivatives of the eigenvalues and eigenvectors for a general complex-valued, non-defective matrix.

Every real symmetric matrix is non-defective, *but not every non-defective matrix is real symmetric*. In fact, any *normal* matrix is non-defective (but again, not every non-defective matrix is necessarily normal).

**Comment by musikisomorphie** [comment] 2019-10-02 07:17
@carlosgmartin, I should've been more rigorous. you are right about normal matrix. Unfortunately, I stop working on this problem long time ago. Currently I am occupied by my work, feel free to dig into it.

**Comment by heitorschueroff** [comment] 2020-08-14 19:56
This was implemented in https://github.com/pytorch/pytorch/pull/33090.

**Closed by heitorschueroff** 2020-08-14 19:56 UTC
Labels: medium priority (this tag is deprecated), triaged
