### ISSUE TITLE
how to load weights when using torch.nn.parallel.DistributedDataParallel?

### ISSUE THREAD

**Issue by aboy2018** [pytorch/pytorch#40016] opened 2020-06-15 03:53 UTC
platform: linux 16.04 ;python==3.8.2, pytorch==1.4.0-gpu

Stand-alone multi-card

I try to load weights when using torch.nn.parallel.DistributedDataParallel to load model, There have be wrong.

    model = torch.nn.parallel.DistributedDataParallel(model,device_ids=[args.local_rank],output_device=args.local_rank,find_unused_parameters=True)
  File "/home/jiashuaihe/anaconda2/envs/torch1.1/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 301, in __init__
    self._distributed_broadcast_coalesced(
  File "/home/jiashuaihe/anaconda2/envs/torch1.1/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 485, in _distributed_broadcast_coalesced
    dist._broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: Broken pipe
Traceback (most recent call
![image](https://user-images.githubusercontent.com/50036961/84616510-c350cc80-aefe-11ea-99c5-69b18c3fc676.png)

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment] 2020-06-15 16:09
Hey @aboy2018 

What parameters did you pass to `init_process_group`? Could you please share a min repro?

**Comment by aboy2018** [comment] 2020-06-16 08:56
![image](https://user-images.githubusercontent.com/50036961/84750752-47ce4880-afee-11ea-9277-d8ecdb1730c2.png)
Thank you,when loading the per-model,there  be a error.

**Comment by mrshenli** [comment] 2020-06-16 14:56
Hey @aboy2018 

How was the model saved? Did you directly saving ddp model or the `module` attributed in a ddp model? And what is the reason for manually modifying loaded stat dict in a loop?

**Comment by mrshenli** [comment] 2020-06-16 21:00
BTW, I am not sure if [this forum post](https://discuss.pytorch.org/t/failed-to-load-model-trained-by-ddp-for-inference/84841) is relevant to this error.

**Comment by rohan-varma** [comment] 2020-06-18 02:52
This doesn't currently seem like a bug, and more of a usage question which is better suited for the PyTorch forums (http://discuss.pytorch.org/c/distributed). Please ask this question on the forums instead (which is more for help/usage questions), while issues are for reporting bugs/regressions. Closing this out, but we can reopen if we find that there is indeed a bug.

**Closed by rohan-varma** 2020-06-18 02:52 UTC
Labels: module: distributed, needs reproduction, triaged
