### ISSUE TITLE
Conda MACOS  12 nightly jobs are failing since Sun, Oct 23

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#87637] opened 2022-10-24 21:04 UTC
### 🐛 Describe the bug

Following is a reference failure:
https://github.com/pytorch/pytorch/actions/runs/3310664820/jobs/5465160650

```
2022-10-24T07:13:41.2430180Z + MACOSX_DEPLOYMENT_TARGET=10.9
2022-10-24T07:13:41.2430680Z + CXX=clang++
2022-10-24T07:13:41.2430990Z + CC=clang
2022-10-24T07:13:41.2431380Z + python setup.py install
2022-10-24T07:13:53.7464040Z CMake Error at /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666595461276/_build_env/share/cmake-3.22/Modules/CMakeTestCXXCompiler.cmake:62 (message):
2022-10-24T07:13:53.7464530Z   The C++ compiler
2022-10-24T07:13:53.7464710Z 
2022-10-24T07:13:53.7464810Z     "/usr/bin/clang++"
2022-10-24T07:13:53.7464960Z 
2022-10-24T07:13:53.7465110Z   is not able to compile a simple test program.
2022-10-24T07:13:53.7465300Z 
2022-10-24T07:13:53.7465430Z   It fails with the following output:
2022-10-24T07:13:53.7465690Z 
2022-10-24T07:13:53.7466150Z     Change Dir: /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666595461276/work/build/CMakeFiles/CMakeTmp
2022-10-24T07:13:53.7466510Z     
2022-10-24T07:13:53.7467150Z     Run Build Command(s):/usr/bin/make -f Makefile cmTC_8af5a/fast && xcrun: error: missing DEVELOPER_DIR path: /Applications/Xcode9.app/Contents/Developer
2022-10-24T07:13:53.7468120Z     
2022-10-24T07:13:53.7468310Z     
2022-10-24T07:13:53.7468440Z 
2022-10-24T07:13:53.7468520Z   
2022-10-24T07:13:53.7468640Z 
2022-10-24T07:13:53.7468820Z   CMake will not be able to correctly generate this project.
2022-10-24T07:13:53.7469130Z Call Stack (most recent call first):
2022-10-24T07:13:53.7469420Z   CMakeLists.txt:23 (project)
2022-10-24T07:13:53.7469580Z 
2022-10-24T07:13:53.7469590Z 
2022-10-24T07:13:57.2531600Z Traceback (most recent call last):
2022-10-24T07:13:57.2532510Z Copying /Users/runner/work/pytorch/pytorch/pytorch to /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666595461276/work/
2022-10-24T07:13:57.2533160Z   File "/Users/runner/work/_temp/anaconda/bin/conda-build", line 11, in <module>
2022-10-24T07:13:57.2536930Z     sys.exit(main())
2022-10-24T07:13:57.2538580Z   File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 496, in main
2022-10-24T07:13:57.2542320Z     execute(sys.argv[1:])
2022-10-24T07:13:57.2545630Z source tree in: /Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666595461276/work
2022-10-24T07:13:57.2547300Z export PREFIX=/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666595461276/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl
2022-10-24T07:13:57.2548450Z   File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/conda_build/cli/main_build.py", line 485, in execute
2022-10-24T07:13:57.2548960Z     outputs = api.build(args.recipe, post=args.post, test_run_post=args.test_run_post,
2022-10-24T07:13:57.2549620Z   File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/conda_build/api.py", line 186, in build
2022-10-24T07:13:57.2549990Z     return build_tree(
2022-10-24T07:13:57.2550560Z   File "/Users/runner/work/_temp/anaconda/lib/python3.9/site-packages/conda_build/build.py", line 3091, in build_tree
2022-10-24T07:13:57.2551930Z export BUILD_PREFIX=/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666595461276/_build_env
2022-10-24T07:13:57.2553750Z export SRC_DIR=/Users/runner/work/_temp/anaconda/conda-bld/pytorch_1666595461276/work
2022-10-24T07:13:57.2554340Z -- The CXX compiler identification is unknown
2022-10-24T07:13:57.2554790Z -- The C compiler identification is unknown
2022-10-24T07:13:57.2555210Z -- Detecting CXX compiler ABI info
2022-10-24T07:13:57.2555640Z -- Detecting CXX compiler ABI info - failed
2022-10-24T07:13:57.2556080Z -- Check for working CXX compiler: /usr/bin/clang++
2022-10-24T07:13:57.2556550Z -- Check for working CXX compiler: /usr/bin/clang++ - broken
2022-10-24T07:13:57.2557030Z -- Configuring incomplete, errors occurred!
2022-10-24T07:13:57.2557380Z See also "$SRC_DIR/build/CMakeFiles/CMakeOutput.log".
2022-10-24T07:13:57.2557750Z See also "$SRC_DIR/build/CMakeFiles/CMakeError.log".
2022-10-24T07:13:57.2558190Z Building wheel torch-1.14.0.dev20221024
2022-10-24T07:13:57.2558590Z -- Building version 1.14.0.dev20221024
```

### Versions

1.14.nightly

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by weiwangmeta** [comment] 2022-10-24 21:20
<img width="1177" alt="image" src="https://user-images.githubusercontent.com/109318740/197631666-11ec2ebf-731c-431a-ad37-913c5ac9520e.png">

Looking at commits between 10-22 (https://github.com/pytorch/pytorch/commit/8e7fb108121daf3ca9eaf4fde90490507bd04089) and 10-23 (efdd43d5193435206fbe76cecc294961d10558db)

**Comment by huydhn** [comment] 2022-10-24 22:27
Could it be this one https://github.com/pytorch/pytorch/pull/87496? The `DEVELOPER_DIR` looks related

**Comment by weiwangmeta** [comment] 2022-10-24 22:29
Yes, I think so.

**Comment by malfet** [comment] 2022-10-24 22:37
It is indeed caused by that PR, but why are we setting to `/Applications/Xcode9.app/Contents/Developer`

**Comment by malfet** [comment] 2022-10-24 22:43
I guess

**Comment by weiwangmeta** [comment] 2023-03-24 18:05
Should be fixed by now.

**Closed by weiwangmeta** 2023-03-24 18:05 UTC
Labels: module: ci, triaged
