### ISSUE TITLE
[Caffe2] DLL load failed

### ISSUE THREAD

**Issue by vichgy** [pytorch/pytorch#23047] opened 2019-07-18 22:58 UTC
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

 After follow the instruction building caffe2, I see the  "Caffe2 built successfully".
However, when import using
`from caffe2.python import workspace`
It shows 
`WARNING:root:This caffe2 python run does not have GPU support. Will run in CPU only mode.
CRITICAL:root:Cannot load caffe2.python. Error: DLL load failed: The specified procedure could not be found.`
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Home
GCC version: (i686-posix-dwarf-rev0, Built by MinGW-W64 project) 8.1.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] Could not collect

**Comment by peterjc123** [comment] 2019-07-19 06:17
Duplicate of https://github.com/pytorch/pytorch/issues/22859.

**Closed by peterjc123** 2019-07-19 06:17 UTC
