### ISSUE TITLE
[Inductor] [CPU] Torchbench model hf_Longformer performance regression > 10% on 2023-03-22 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#97496] opened 2023-03-24 03:19 UTC
### 🐛 Describe the bug

Compare with data on 2023-03-19, there is a performance regression on torchbench model **hf_Longformer** on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1482188025) on 2023-03-22 as bellow:

|  2023-03-22  |   |     |   |  2023-03-19  |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|0.8311	|0.1187425	|0.098686892	|1	|0.9589	|0.102137	|0.097939169	|0.87	|0.99	|0.86

2023-03-22 SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[00891e96](https://github.com/pytorch/pytorch/commit/00891e96)|[f9a9a88 ](https://github.com/pytorch/pytorch/commit/f9a9a88)
Torchbench|/|[83a316df](https://github.com/pytorch/benchmark/commit/83a316df)
torchaudio|[375e751](https://github.com/pytorch/audio/commit/375e751)|[a8f4e97](https://github.com/pytorch/audio/commit/a8f4e97)
torchtext|[9749082](https://github.com/pytorch/text/commit/9749082)| [46e7eef](https://github.com/pytorch/text/commit/46e7eef)
torchvision|[8d15ca7](https://github.com/pytorch/vision/commit/8d15ca7)|[98c5815](https://github.com/pytorch/vision/commit/98c5815)
torchdata|[b3048d5](https://github.com/pytorch/data/commit/b3048d5)|[f1283eb](https://github.com/pytorch/data/commit/f1283eb)
dynamo_benchmarks|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|/

2023-03-19 SW information:
SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[422a1d3](https://github.com/pytorch/pytorch/commit/422a1d3)|[c1214ce](https://github.com/pytorch/pytorch/commit/c1214ce5)
Torchbench|/|[83a316df](https://github.com/pytorch/benchmark/commit/83a316df)
torchaudio|[375e751](https://github.com/pytorch/audio/commit/375e751)|[a8f4e97](https://github.com/pytorch/audio/commit/a8f4e97)
torchtext|[9749082](https://github.com/pytorch/text/commit/9749082)| [46e7eef](https://github.com/pytorch/text/commit/46e7eef)
torchvision|[8d15ca7](https://github.com/pytorch/vision/commit/8d15ca7)|[98c5815](https://github.com/pytorch/vision/commit/98c5815)
torchdata|[b3048d5](https://github.com/pytorch/data/commit/b3048d5)|[f1283eb](https://github.com/pytorch/data/commit/f1283eb)
dynamo_benchmarks|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|/

### Versions

Minified repro:
```bash
python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only hf_Longformer  --cold_start_latency
```

**Comment by chunyuan-w** [comment] 2023-03-30 14:52
The regression is caused by https://github.com/pytorch/pytorch/pull/97055

**Comment by wconstab** [comment] 2023-04-07 16:18
This should be fixed by https://github.com/pytorch/pytorch/pull/98371

**Closed by wconstab** 2023-04-07 16:18 UTC
Labels: triaged, module: cpu inductor
