### ISSUE TITLE
If .to() is called on nn.Parameter, it returns a tensor.

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#9303] opened 2018-07-10 12:58 UTC
For example:
```python
p = nn.Parameter(torch.zeros(5))
type(p)
>>> <class 'torch.nn.parameter.Parameter'>
p = p.to(torch.device('cuda:0'))
>>> <class 'torch.Tensor'>
p.to(torch.device('cuda:0'))
```
## System Info
PyTorch version: 2018.05.07
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.11.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 396.26
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.1.4
/usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn_static.a

Versions of relevant libraries:
[pip3] numpy (1.14.5)
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] magma-cuda90              2.3.0                         1    pytorch
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] pytorch-nightly           2018.05.07      py36_cuda9.0.176_cudnn7.1.2_1  [cuda90]  pytorch
[conda] pytorchviz                0.0.1                     <pip>
[conda] torch                     0.5.0a0+e8536c0           <pip>
[conda] torchvision               0.2.1                     <pip>

cc @albanD @mruberry

**Comment by vishwakftw** [comment] 2018-07-10 13:45
I have a fix for this, can I send it in?

**Comment by vadimkantorov** [comment] 2018-07-10 15:23
there were similar issue with `nn.Parameter().type_as()`: https://github.com/pytorch/pytorch/issues/5164

**Comment by zou3519** [comment] 2020-05-27 14:09
This happened here as well: https://github.com/pytorch/pytorch/issues/39062

**Comment by albanD** [comment] 2020-05-27 14:26
I'm afraid this has been here long enough that it is now expected behavior: calling `.to()` on a Parameter will return a non-leaf Tensor (and thus not a Parameter). This is because the `.to()` op is differentiable.

I don't think we want to change this behavior.

I'm closing this for now. If someone wants to argue the other way and justify the BC-breaking changes feel free to re-open!

**Closed by albanD** 2020-05-27 14:26 UTC
Labels: module: nn, topic: correctness (silent), triaged
