### ISSUE TITLE
[BUG] The dim of empty tensor is one in PyTorch 0.4.0

### ISSUE THREAD

**Issue by ghrua** [pytorch/pytorch#7240] opened 2018-05-03 13:32 UTC
## Issue description
The dim of empty tensor was 0 in version 0.3.0, but I got 1 in version 0.4.0

## Code example

```
In [1]: x = torch.Tensor([])

In [2]: x
Out[2]: tensor([])

In [3]: x.dim()
Out[3]: 1

In [4]: x = torch.Tensor([1])

In [5]: x
Out[5]: tensor([ 1.])

In [6]: x.dim()
Out[6]: 1
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): pip install torch
- Build command you used (if compiling from source):
- OS: Mac OS 10.12.6
- PyTorch version: 0.4.0
- Python version: 3.6.1

**Comment by fmassa** [comment] 2018-05-03 13:49
I would say that the current behavior is expected.

An empty tensor is a tensor with a 0 in one if its dimensions, so it should have at least 1 dimension. This is in contrast to a scalar, which has no dimensions.

Currently, we only support having a 1d empty tensors, but in the future we might be supporting nd empty tensors as well.

Also, this is the same behavior of numpy:
```python
np.array([]).ndim  # 1
np.array([]).shape  # (0,)
```
and we are consistent with numpy,

I'm closing the issue, but feel free to comment if you disagree.

**Comment by SsnL** [comment] 2018-05-03 13:50
Not a bug. In 0.4 we introduced scalars, and thus `[]` becomes dim 1, which is the more reasonable behavior than in 0.3.1. Note that it isn't empty, but it is of size `(0,)`. An empty tensor should be of size `()`.

See https://pytorch.org/2018/04/22/0_4_0-migration-guide.html

**Closed by fmassa** 2018-05-03 13:49 UTC
