### ISSUE TITLE
support torch.fft without MKL support, cannot compute on ppcle arch in cpu mode

### ISSUE THREAD

**Issue by Mon-ius** [pytorch/pytorch#42426] opened 2020-08-02 17:52 UTC
I am working on the IBM POWER9 Series cluster. When compute the fft with torch. I have to transfer it to GPU and then transfer back to CPU. It's real bad experience espcially when realted code called on Dataloader. Then I have to disable the multi-worker to prevent the error.

```
x = torch.randn(10,10,2)
torch.fft(x,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: fft: ATen not compiled with MKL support
```

**Comment by malfet** [comment] 2020-08-03 17:14
Is a duplicate of https://github.com/pytorch/pytorch/issues/41592, isn't it?

**Comment by ezyang** [comment] 2020-08-03 17:25
closing as dupe

**Closed by ezyang** 2020-08-03 17:25 UTC
Labels: feature, triage review, triaged
