### ISSUE TITLE
[inductor][cpu] Perf regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#108324] opened 2023-08-31 03:14 UTC
<p>perf regression found - compare with 2023_08_22 nightly</p>
<p>Repro</p>

bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
multiple inference performance suite model float32 first dynamic cpp 0

<p>new_perf_regression</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>doctr_det_predictor</td>
      <td>1</td>
      <td>1.069458</td>
      <td>0.148391054</td>
      <td>0.158697999828732</td>
      <td>33.396333</td>
      <td>1</td>
      <td>1.503562</td>
      <td>0.106578389</td>
      <td>0.160247215721618</td>
      <td>37.416409</td>
      <td>0.71</td>
      <td>1.01</td>
      <td>0.72</td>
      <td>1.12</td>
    </tr>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.862569</td>
      <td>0.310560677</td>
      <td>0.267880012599213</td>
      <td>18.169774</td>
      <td>1</td>
      <td>1.057315</td>
      <td>0.24839536899999998</td>
      <td>0.262632149574235</td>
      <td>27.68669</td>
      <td>0.82</td>
      <td>0.98</td>
      <td>0.8</td>
      <td>1.52</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>doctr_det_predictor</td>
      <td>1</td>
      <td>0.652977</td>
      <td>3.336484332</td>
      <td>2.178647529656364</td>
      <td>38.657023</td>
      <td>1</td>
      <td>1.20895</td>
      <td>1.828299074</td>
      <td>2.2103221655123</td>
      <td>36.253952</td>
      <td>0.54</td>
      <td>1.01</td>
      <td>0.55</td>
      <td>0.94</td>
    </tr>
    <tr>
      <td>pytorch_unet</td>
      <td>1</td>
      <td>0.915661</td>
      <td>5.48157092</td>
      <td>5.01926071017812</td>
      <td>20.518048</td>
      <td>1</td>
      <td>0.998196</td>
      <td>4.898655984</td>
      <td>4.889818808604864</td>
      <td>29.142998</td>
      <td>0.92</td>
      <td>0.97</td>
      <td>0.89</td>
      <td>1.42</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>
</table>

bash
[inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
multiple inference performance torchbench llama float32 first static default 0
<p>new_perf_regression</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>llama</td>
      <td>32</td>
      <td>0.578757</td>
      <td>0.053369041000000006</td>
      <td>0.030887706062037</td>
      <td>35.195648</td>
      <td>32</td>
      <td>1.143321</td>
      <td>0.027263855</td>
      <td>0.031171337962455</td>
      <td>40.613965</td>
      <td>0.51</td>
      <td>1.01</td>
      <td>0.51</td>
      <td>1.15</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>
</table>

<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>f54acf0</td>
      <td>bad3f2d</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td>66f661d</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td>60bea66</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td>a6dea86</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>1d231d1</td>
      <td>757c032</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>f228c8b</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

cc @ezyang @msaroufim @wconstab @bdhirsh @zou3519

**Comment by chunyuan-w** [comment] 2023-09-07 07:49
pytorch_unet regression starts from this commit: https://github.com/pytorch/pytorch/pull/107640

**Comment by chunyuan-w** [comment] 2023-09-26 03:38
llama regression is caused by https://github.com/pytorch/pytorch/pull/107578. cc @Valentine233

**Comment by chunyuan-w** [comment] 2023-09-26 06:02
`doctr_det_predictor` regression: we added `--freezing` and `export TORCHINDUCTOR_FREEZING=1` when running the dynamic shapes benchmark starting from 0825, which caused this regression.

**Comment by Valentine233** [comment] 2023-10-07 05:16
> llama regression is caused by #107578. cc @Valentine233

Thanks, @chunyuan-w.

The regression is caused by using the fused SDPA (flash-attention based-SDPA). Due to the small sequence length (32) in the model, the blocking is not able to be applied. However, to reduce memory access, the fused SDPA does more calculations compared to the unfused SDPA. Hence, the regression is expected and we need to tune a threshold for the input shape for using the fused SDPA.

**Comment by chunyuan-w** [comment] 2023-12-07 07:42
`doctr_det_predictor`
@chuanqi129 I checked the latest report on 2023-12-04 and the performance of doctr_det_predictorinductor-inference-float32-dynamic-cpp-wrapper is 0.096308208(multi-thread), 1.897524131(single-thread) and seems the regression has been fixed. Could you please help double-confirm it?

**Comment by chuanqi129** [comment] 2023-12-07 07:44
If so, I think we should have a new issue for it. Please @zxd1997066 help to double check it. And maybe it related with @Valentine233 's build flag change PR.

**Comment by chuanqi129** [comment] 2023-12-13 13:52
Have double checked that `doctr_det_predictor` perf issue has been fixed by the oneDNN 3.3.2 upgrade. 

time in s | oneDNN v3.3.2 | oneDNN v3.1.1
-- | -- | --
multi-thread | 0.093045079 | 0.136664209
single-thread | 1.936846355 | 2.752925339

@zxd1997066 please help to double check the `pytorch_unet` model with @Valentine233 check whether if the expected drop due to the build flag change. If not, please create a new one for it and close this one.

**Comment by Valentine233** [comment] 2023-12-14 02:27
> Have double checked that `doctr_det_predictor` perf issue has been fixed by the oneDNN 3.3.2 upgrade.
> 
> time in s	oneDNN v3.3.2	oneDNN v3.1.1
> multi-thread	0.093045079	0.136664209
> single-thread	1.936846355	2.752925339
> @zxd1997066 please help to double check the `pytorch_unet` model with @Valentine233 check whether if the expected drop due to the build flag change. If not, please create a new one for it and close this one.

I have checked that the speedup of FP32 single-thread and multi-threads are both `0.97` for building flag change. Hence, this is not the guilty commit for `pytorch_unet` drop.

**Comment by chunyuan-w** [comment] 2023-12-20 05:07
I'll re-assign this issue to @Valentine233  since the perf regression of `doctr_det_predictor` and `pytorch_unet` have all been fixed on the latest main branch. The only left issue is `llama` and the fix is needed as specified in https://github.com/pytorch/pytorch/issues/108324#issuecomment-1751604591.

**Comment by chunyuan-w** [comment] 2023-12-20 05:08
**Update (2023-12-20):**
According to the `Torchinductor-inductor-inference-float32-dynamic-cpp-Report(AWS)_2023_12_18`, `pytorch_unet ` perf is 0.216017387 (multi-thread), 4.681508366(single-thread). The regression is fixed. @chuanqi129

**Comment by Valentine233** [comment] 2024-01-11 07:01
The root cause of llama regression is the same as https://github.com/pytorch/pytorch/issues/109874. The application of flash attention introduces more extra buffer creations.

With https://github.com/pytorch/pytorch/pull/116899, the perf comes back.

- eager:  0.03427387704141438
- inductor:  0.024897337891161442
- speedup: 1.377x.

**Comment by Valentine233** [comment] 2024-01-11 07:04
In addition, I have tried to disable flash attention with different KV size thresholds, for llama and stable diffusion. It couldn't help and the perf would drop more or less. cc @jgong5 @mingfeima @Guobing-Chen

**Comment by leslie-fang-intel** [comment] 2024-01-30 05:48
Close this issue as per https://github.com/pytorch/pytorch/issues/93531#issuecomment-1916066655 , llama bs32 multi thread speed up is 1.36908x now.

**Closed by leslie-fang-intel** 2024-01-30 05:48 UTC
Labels: triaged, oncall: pt2, oncall: cpu inductor
