### ISSUE TITLE
Wrongly returns nan for complex numbers division

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#92043] opened 2023-01-11 22:58 UTC
### 🐛 Describe the bug

Pytorch wrongly returns nan for complex numbers division where the results are still within the range of the datatype.
For example: `(0.0 + 0.0j) / (1e-36 + 0.0j)` in `complex64`. In this case, both operands and the results (which is `0`) are within the defined range of complex64. However, it returns `(nan + nanj)`.

Here's the reproducing code:
```python
import torch
a = torch.tensor(0.0 + 0.0j)
b = torch.tensor(1e-36 + 0.0j)
print(a / b)  # it's (nan + nanj)
```

### Versions

I'm using the version in my latest pull request about unrelated case (so I don't touch the complex number division and hopefully it's latest enough). Tried with version 1.13.0, the results are the same.
```
PyTorch version: 2.0.0a0+git9cf2733
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.31

Python version: 3.9.15 (main, Nov  4 2022, 16:13:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-1025-gcp-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 520.61.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.6
[pip3] torch==2.0.0a0+gitde31b33
[conda] blas                      1.0                         mkl  
[conda] magma-cuda118             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.1.0           h06a4308_224  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.14.0a0+gitb0bd5c4          pypi_0    pypi
```

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by drisspg** [comment] 2023-01-12 19:24
I can reproduce this on my machine.

**Comment by lezcano** [comment] 2023-01-12 19:56
Does C++ work as expected here?

**Comment by drisspg** [comment] 2023-01-12 20:04
Godbolt:
```c++
#include <iostream>
#include <complex>

int main(){
    std::complex<float> a = 0 +0j;
    std::complex<float> b = 1e-36 + 0j;
    std::cout<<a<<std::endl;
    std::cout<<b<<std::endl;
    std::cout<<a/b<<std::endl;
    return 0;
}
```
-> 
```
(0,0)
(1e-36,0)
(0,0)
```

**Comment by mfkasim1** [comment] 2023-01-12 22:43
I suspect the calculation involves explicit calculation of `br ^ 2 + bi ^ 2` in the denominator. In most cases, it's fine, but with small numbers, the denominator produces 0 due to numerical precision. I can volunteer to fix this if anyone could help me pointing where the complex numbers division is implemented.

**Comment by lezcano** [comment] 2023-01-12 23:48
https://github.com/pytorch/pytorch/blob/b7cad020b59ec2c9b9d62a1e6ca78c5b53f186a1/c10/util/complex.h#L246-L258

**Comment by min-jean-cho** [comment] 2023-01-17 10:06
```python
>>> torch.tensor(0.0 + 0.0j) / torch.tensor(1e-22 + 0.0j)
tensor(0.+0.j)
>>> torch.tensor(0.0 + 0.0j) / torch.tensor(1e-23 + 0.0j)
tensor(nan+nanj)
```
Looks like this occurs when `c * c > 1e-45`, the smallest subnormal for fp32 is `1e-45`. 

https://github.com/pytorch/pytorch/blob/b7cad020b59ec2c9b9d62a1e6ca78c5b53f186a1/c10/util/complex.h#L254

**Comment by min-jean-cho** [comment] 2023-01-17 19:03
I checked out how numpy implements their complex divide https://github.com/numpy/numpy/blob/9b6a7b4f874f5502112f36d485b12d92889eb808/numpy/core/src/npymath/npy_math_complex.c.src#L87-L115. 

To avoid this type of underflow, they represent `c * c + d * d` as `c + d * (d / c)`. For example, 
```
c = torch.tensor(1e-23)
d = torch.tensor(1e-23)
torch.tensor(c*c + d*d) # tensor(0.)
torch.tensor(c + d * (d/c)) # tensor(2.0000e-23)
```

**Comment by lezcano** [comment] 2023-01-18 08:17
NumPy's solution LGTM. We'd accept a fix for this.

**Closed** 2023-01-26 01:14 UTC
Labels: triaged, module: complex, module: edge cases
