### ISSUE TITLE
CUDA error: device-side assert triggered for BERT Multi Class Classification

### ISSUE THREAD

**Issue by ozcangundes** [pytorch/pytorch#31247] opened 2019-12-13 09:59 UTC
I am getting this error continuously when trying to multiclass classification with BERT.

```
RuntimeError                              Traceback (most recent call last)
<ipython-input-38-9340b895bfde> in <module>()
     21   for step, batch in enumerate(train_dataloader):
     22     # Add batch to GPU
---> 23     batch = tuple(t.to(device) for t in batch)
     24     # Unpack the inputs from our dataloader
     25     b_input_ids, b_input_mask, b_labels = batch

<ipython-input-38-9340b895bfde> in <genexpr>(.0)
     21   for step, batch in enumerate(train_dataloader):
     22     # Add batch to GPU
---> 23     batch = tuple(t.to(device) for t in batch)
     24     # Unpack the inputs from our dataloader
     25     b_input_ids, b_input_mask, b_labels = batch

RuntimeError: CUDA error: device-side assert triggered
```
I could not find the reason in my case even if searching for all issues related to it. I have got 4 labels. And with binary classification I did not get this error though.
Thanks for your response in advance.

cc @ngimel

**Comment by t-vi** [comment] 2019-12-13 15:25
Very likely this isn't where the error happens, you could try with setting `CUDA_LAUNCH_BLOCKING=1` (see [Debugging Device Assert](http://lernapparat.de/debug-device-assert/) for some background.
Then the next step is to pin down the exact inputs to the operation triggering the inputs to get a repro.

**Comment by zou3519** [comment] 2019-12-16 16:33
Do you have a self-contained script which we could use to reproduce the problem?

**Comment by ozcangundes** [comment] 2019-12-18 09:34
Hello @zou3519 ! When I add the data types of tensors as "long" like shown below, the problem does not occur again, surprisingly.
```
train_inputs = torch.tensor(train_inputs)
validation_inputs = torch.tensor(validation_inputs)
train_labels = torch.tensor(train_labels, **dtype=torch.long**)
validation_labels = torch.tensor(validation_labels, **dtype=torch.long**)
train_masks = torch.tensor(train_masks, **dtype=torch.long**)
validation_masks = torch.tensor(validation_masks, **dtype=torch.long**)
```

**Comment by t-vi** [comment] 2019-12-18 09:39
Thank you, this is an important hint. Can you run with CUDA_LAUNCH_BLOCKING=1 and report the traceback, though? It would help to know which function precisely errored. (See the link above for more explanation.)

**Comment by mruberry** [comment] 2020-10-10 08:48
Closing due to lack of update and no reproduction. @ozcangundes, if you're still hitting this issue would you please update and reopen it?

**Closed by mruberry** 2020-10-10 08:48 UTC
Labels: module: cuda, module: operators (deprecated), triaged
