### ISSUE TITLE
Question about CUDA usage in libtorch 

### ISSUE THREAD

**Issue by lsd1994** [pytorch/pytorch#46172] opened 2020-10-12 04:06 UTC
Hi,
I have the same problem as #37124  #37481  #37741. Now I try to create a dll by using libtorch library to provide a function for others. When I test the dll, I found I must add -INCLUDE:?warp_size@cuda@at@@YAHXZ if want to use CUDA. But it's not convenient for others to use dll. So can someone help me solve this?
Also I want to know if these two methods can solve this:
1.Use Cmake to create the VS project and  then generate dll, is it different with now?
2.Use other version of libtorch(now 1.5) can help?  
Thank for help.

cc @yf225 @glaringlee @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by glaringlee** [comment] 2020-10-12 19:31
@peterjc123 
Can you comment?

**Comment by lsd1994** [comment] 2020-10-13 03:03
I use libtorch 1.4 and solve this problem. Now the CUDA works normally when calling dll functions.
But 1.5 and 1.6 have the same problem, do you know why?

**Comment by mszhanyi** [comment] 2021-07-16 05:20
@lsd1994 
I'm developing a VS extension to solve this issue.
The preview link is 
https://ossci-windows.s3.us-east-1.amazonaws.com/vsextension/VSIXTorch.vsix

The demo link is 
https://ossci-windows.s3.us-east-1.amazonaws.com/vsextension/demo.mp4

So far, it only support libtorch 1.9 (https://pytorch.org/). Any comments and suggestion are welcome

**Comment by seemethere** [comment] 2021-07-30 00:24
Duplicate of #60447

**Closed by seemethere** 2021-07-30 00:24 UTC
Labels: module: cpp, module: windows, triaged

**Comment by seungtaek94** [comment] 2021-09-07 00:40
> @lsd1994
> I'm developing a VS extension to solve this issue.
> The preview link is
> https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001
> 
> The demo link is
> https://ossci-windows.s3.us-east-1.amazonaws.com/vsextension/demo.mp4
> 
> So far, it only supports libtorch 1.9 (https://pytorch.org/). Any comments and suggestion are welcome

Hi. I tried to using that extention but it deosnt have any response when i click the `OK` button.

![image](https://user-images.githubusercontent.com/56434476/132268193-d925e211-fb51-460b-9f47-416e281ea133.png)

My env:
CUDA 11.1
libtorch 1.9
vs2019(16.10.4)

**Comment by mszhanyi** [comment] 2021-09-07 03:40
@seungtaek94 Thank your feedback very much. Could you please upgrade to latest version (0.1.6). It should be fixed now.

**Comment by seungtaek94** [comment] 2021-09-09 00:26
> @seungtaek94 Thank your feedback very much. Could you please upgrade to latest version (0.1.6). It should be fixed now.

Awesome !, It works now.
Thanks for sharing great extension :)
