### ISSUE TITLE
Trivial Bug in some of the torch.distributions.constraints implementations.

### ISSUE THREAD

**Issue by nonconvexopt** [pytorch/pytorch#67975] opened 2021-11-08 00:58 UTC
## 🐛 Bug

Code of the 'torch/distributions/constraints.py' seems to have a bug in implementations.
Below are the two classes checking the constraint of the matrix variables.

```
class _LowerTriangular(Constraint):
    """
    Constrain to lower-triangular square matrices.
    """
    event_dim = 2

    def check(self, value):
        value_tril = value.tril()
        return (value_tril == value).view(value.shape[:-2] + (-1,)).min(-1)[0]


class _LowerCholesky(Constraint):
    """
    Constrain to lower-triangular square matrices with positive diagonals.
    """
    event_dim = 2

    def check(self, value):
        value_tril = value.tril()
        lower_triangular = (value_tril == value).view(value.shape[:-2] + (-1,)).min(-1)[0]

        positive_diagonal = (value.diagonal(dim1=-2, dim2=-1) > 0).min(-1)[0]
        return lower_triangular & positive_diagonal

```
In the code, I wonder why it is using '.min(-1)[0]' instead of code like '.all()' for checking if the tensor contains only 'True' value.
It seems that it is checking only the first batch of the input.
Are there reasons of these implementations?

## Expected behavior

It may not check the constraint properly.

## Environment

General PyTorch distributions.

cc @fritzo @neerajprad @alicanb @nikitaved

**Comment by nonconvexopt** [comment] 2021-11-08 03:59
I will PR the fixed code if you allow me.

**Comment by fritzo** [comment] 2021-11-08 22:34
Closing as this is intended behavior.

Note that `.min(-1)` [returns a namedtuple](https://pytorch.org/docs/stable/generated/torch.min.html) with fields `(values, indices)` and the `[0]` pulls out the `.values`. In modern pytorch an alternative spelling is:
```py
.min(-1).values
```

**Closed by fritzo** 2021-11-08 22:34 UTC
Labels: module: distributions, triaged
