### ISSUE TITLE
Cannot build pytorch from source

### ISSUE THREAD

**Issue by Jimmy2027** [pytorch/pytorch#27467] opened 2019-10-07 17:28 UTC
## Cannot build pytorch from source

I am attempting to package your software for Gentoo Linux, and trying to build it with `python3.6 setup.py build` I get errors related to git and CMake, which seems strange.

## To Reproduce

```
python3.6 setup.py build
```

Here is the full output:
```
bartholin ~ # emerge -v pytorch

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  N     ] dev-python/pytorch-1.2.0::chymeric  USE="-test" PYTHON_TARGETS="python3_6" 0 KiB

Total: 1 package (1 new), Size of downloads: 0 KiB


>>> Verifying ebuild manifests

>>> Emerging (1 of 1) dev-python/pytorch-1.2.0::chymeric
 * pytorch-1.2.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                         [ ok ]
>>> Unpacking source...
>>> Unpacking pytorch-1.2.0.tar.gz to /var/tmp/portage/dev-python/pytorch-1.2.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/pytorch-1.2.0/work
>>> Preparing source in /var/tmp/portage/dev-python/pytorch-1.2.0/work/pytorch-1.2.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/pytorch-1.2.0/work/pytorch-1.2.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/pytorch-1.2.0/work/pytorch-1.2.0 ...
 * python3_6: running distutils-r1_run_phase distutils-r1_python_compile
python3.6 setup.py build -j 20
fatal: not a git repository (or any of the parent directories): .git
Building wheel torch-1.2.0a0
-- Building version 1.2.0a0
Could not find /var/tmp/portage/dev-python/pytorch-1.2.0/work/pytorch-1.2.0/third_party/gloo/CMakeLists.txt
Did you run 'git submodule update --init --recursive'?
```

## Expected behavior

I would expect it to build something

## Environment

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Gentoo/Linux
GCC version: (Gentoo 9.2.0-r1 p2) 9.2.0
CMake version: version 3.15.4

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 435.21
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

## Additional Info

I also notice that your `collect_env.py` script lacks a shebang line. I would suggest you add:

```
#!/usr/bin/env python
```

as the first line of the file and make it executable. I would be happy to submit a PR for this if you agree with the suggestion.

**Comment by pietern** [comment] 2019-10-08 13:28
I think this is a problem with the Gentoo package file instead. Please refer to the Gentoo issue tracker and the maintainer for the PyTorch package there. It looks like the `gloo` submodule isn't checked out (and probably others as well).

Closing this issue as this is not actionable here.

If this turns out to be a reproducible issue when building from source yourself, feel free to reopen.

**Closed by pietern** 2019-10-08 13:28 UTC

**Comment by TheChymera** [comment] 2019-10-09 17:46
@pietern we are the maintainers who are trying to figure this out.

This seems to be the link for your source code for thee respective release, yes? https://github.com/pytorch/pytorch/archive/v1.2.0.tar.gz

If so, what we do is download it and execute

```
python3.6 setup.py build -j 20
```

and get `fatal: not a git repository (or any of the parent directories): .git`

The question is why the setup script you provide is expecting this to be a git repository, if you do not provide a git repository in the archive which contains the script.

**Comment by pietern** [comment] 2019-10-10 04:21
The archive at that link is a copy of the source code at the `v1.2.0` tag of the repository. It turns out GitHub doesn't include checkouts of submodules in this archive.

Building from source is done only by checking out the repository and the submodules. There is no way that building from source without those submodules can work. To fix this, I would not use the archive, but clone and checkout the repository at the tag you want, and then building from source.

**Comment by aclex** [comment] 2019-11-27 18:17
@TheChymera you're right, the source code assets for the releases seem to be auto-generated and lack of the required submodules and all the git stuff, just as @pietern mentioned. Still I seem to elaborate the script (ebuild) to build Pytorch from the checkout of the release branch, if you're still interested, feel free to take a look at my try at https://github.com/aclex/pytorch-ebuild. Basically the approach I follow isn't something supported or recommended, but it seems to work, at least for me.

**Comment by TheChymera** [comment] 2019-11-27 21:36
@aclex what exactly do you mean by “your approach”? The ebuild mostly looks mostly ok.

Have you tried to run the tests? I'm not sure what your ebuild is doing regarding the tests. It seems to me like you are *deleting* test files when the test USE flag is enabled? That seems the wrong way around.

**Comment by aclex** [comment] 2019-11-27 21:50
@TheChymera Yes, in "my approach" I meant to prepare it to be installed system-wide (as far, as I know, PyTorch documentation recommends to install `libtorch` locally (and address it via changing `CMAKE_PREFIX_PATH` of the client project) and install PyTorch itself globally using `setup.py` in global Python destinations. And second, I'm changing the source, so that PyTorch (Python binding itself) used just-built `libtorch` instance, rather than re-compile its own copy (which is the default way in `setup.py`). So both of these things are sort of undocumented functionality, but it works for me (CPU version, don't have the necessary video-card to test other cases, but have just started trying ROCm to build).

Tests compile and mainly pass (except for a couple failing) if enabled in the profile. You're right, I'm removing all of it after the test phase, as they tend to pollute the target image with the supplementary things for tests, so otherwise one would have their system catalogs full of this test stuff after the merge, not obviously desired.

What's not working yet is building the documentation, there're a couple of dependencies, Python'ic and Node.js, so working at it now.
