### ISSUE TITLE
Training with nn.DataParallel and cross-fold validation issues

### ISSUE THREAD

**Issue by kleingeo** [pytorch/pytorch#30616] opened 2019-12-02 17:48 UTC
I am working on a code for cross-validation so the input data changes with the code snippets below. 

```python
if len(self.gpu_ids) > 0:
    os.environ['CUDA_VISIBLE_DEVICES'] = ','.join([str(x) for x in self.gpu_ids])
    device = torch.device(('cuda:{}').format(self.gpu_ids[0]) if self.gpu_ids else 'cpu')

if torch.cuda.device_count() > 1:
    net = torch.nn.DataParallel(net)

net.to(device)
image = input['image'].to(device)
label = input['label'].to(device)
pred = net(image)

```

The first iteration has no problem. However, one the second loop (second cross-validation test), I am getting this error.

```python
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1
```

When I have only one GPU used there is no issue, but when there are multiple GPUs with ```torch.nn.DataParallel(net)``` I get the error message from above. In the loop I verified that ```device``` does not change and is always ```device = device(type='cuda', index=0)```.

**Comment by pietern** [comment] 2019-12-03 08:31
You don't have to call `net.to(device)` for a module that's already wrapped with `nn.DataParallel`.

What is the value of `gpu_ids` for you? If you remap GPU 1 to 0 through `CUDA_VISIBLE_DEVICES`, you'll still have `device` equal to GPU 1, even though you remapped it to 0. I would try to get rid of setting `CUDA_VISIBLE_DEVICES` and instead pass a `device_ids` kwarg to `nn.DataParallel`.

**Comment by kleingeo** [comment] 2019-12-03 13:51
> You don't have to call `net.to(device)` for a module that's already wrapped with `nn.DataParallel`.
> 
> What is the value of `gpu_ids` for you? If you remap GPU 1 to 0 through `CUDA_VISIBLE_DEVICES`, you'll still have `device` equal to GPU 1, even though you remapped it to 0. I would try to get rid of setting `CUDA_VISIBLE_DEVICES` and instead pass a `device_ids` kwarg to `nn.DataParallel`.

I did not know about the net.to(device), I'll try to remove that and see how it works. In terms of the CUDA_VISIBLE_DEVICES, I am already using that with the snippet below to prefix them. I did not have much passing the ```device_ids``` to ```nn.DataParallel``` but I can give it a shot. I think what bothers me more is that it works on the first pass no problem but fails the second time. 
```python
if len(gpu_ids) > 0:
    os.environ['CUDA_VISIBLE_DEVICES'] = ','.join([str(x) for x in gpu_ids])
```

**Comment by pietern** [comment] 2019-12-03 13:58
Setting `CUDA_VISIBLE_DEVICES` remaps the device indices.

If you set it to `2,3`, for example, they will now be available as `0,1`. This is why you need to remap `gpu_ids` to `range(len(gpu_ids))` (effectively), after setting `CUDA_VISIBLE_DEVICES`.

**Comment by kleingeo** [comment] 2019-12-06 19:22
I have been using ```gpu_ids='"0,1"``` so I do not need remapping I believe. I tried the model again using```net = torch.nn.DataParallel(net)``` without additionally calling ```net.to(device)``` and the model no longer trains at all now and I receive the above error immediately. I also tried ```net = torch.nn.DataParallel(net, gpu_ids=range(len(['0', '1']))``` but it also does not work.

**Comment by pietern** [comment] 2019-12-10 09:29
Right, with `gpu_ids=0,1` it's the same.

I think the problem is hiding where you first construct `net`. Otherwise, where could the parameters possibly be placed on `cuda:1`? Moving parameters/buffers to CUDA land doesn't happen until `nn.DataParallel` kicks in.

**Comment by kleingeo** [comment] 2019-12-11 20:40
> Right, with `gpu_ids=0,1` it's the same.
> 
> I think the problem is hiding where you first construct `net`. Otherwise, where could the parameters possibly be placed on `cuda:1`? Moving parameters/buffers to CUDA land doesn't happen until `nn.DataParallel` kicks in.

You were right, part of the issue was in the `net` not having its weights reinitialized for the next pass. I tried to reinitialize the weights by rebuilding and overwriting the previous `net`, which does allow me to compute. However, now it is no longer training (the loss and metrics dont change per epoch).

**Comment by pietern** [comment] 2019-12-19 08:57
Thanks for the update. Sounds like you figured out a solution. Closing the issue.

**Closed by pietern** 2019-12-19 08:57 UTC
Labels: module: data parallel, triaged
