### ISSUE TITLE
UserWarning operator() profile_node %135 : int = prim::profile_ivalue(%121)  does not have profile information

### ISSUE THREAD

**Issue by baldassarreFe** [pytorch/pytorch#86793] opened 2022-10-12 14:01 UTC
### 🐛 Describe the bug

# Unclear warning when scripting a function

Running the following code generates a UserWarning, but it's unclear what is causing it, whether it affects performance, and how to avoid it.

```python
import torch
import torchvision.transforms.functional as T

@torch.jit.script
def blur(x: torch.Tensor, sigma: float=2.0) -> torch.Tensor:
    k = int(round(4.0 * sigma))
    if k % 2 == 0:
        k += 1
    x = T.gaussian_blur(x, [k, k], [sigma, sigma])
    return x

x = torch.rand(3, 16, 16)
blur(x, 1.0)
blur(x, 2.0)
```
```
tmp.py:16: UserWarning: operator() profile_node %135 : int = prim::profile_ivalue(%121)
 does not have profile information (Triggered internally at  /opt/conda/conda-bld/pytorch_1656352630480/work/torch/csrc/jit/codegen/cuda/graph_fuser.cpp:104.)
  blur(x, 2.0)
```

The warning is always produced the second time `blur` is called, regardless of the value of sigma, and regardless of device placement.

For reference, the scripted function is:
```python
print(blur.code)
```
```
def blur(x: Tensor,
    sigma: float=2.) -> Tensor:
  _0 = __torch__.torchvision.transforms.functional.gaussian_blur
  k = int(torch.round(torch.mul(4., sigma)))
  if torch.eq(torch.remainder(k, 2), 0):
    k0 = torch.add(k, 1)
  else:
    k0 = k
  return _0(x, [k0, k0], [sigma, sigma], )
```

And its graph is:
```python
print(blur.graph)
```
```
graph(%x.1 : Tensor,
      %sigma.1 : float):
  %30 : Function = prim::Constant[name="gaussian_blur"]()
  %2 : float = prim::Constant[value=4.]() # tmp.py:8:18
  %10 : int = prim::Constant[value=2]() # tmp.py:9:11
  %12 : int = prim::Constant[value=0]() # tmp.py:9:16
  %16 : int = prim::Constant[value=1]() # tmp.py:10:13
  %4 : float = aten::mul(%2, %sigma.1) # tmp.py:8:18
  %5 : float = aten::round(%4) # tmp.py:8:12
  %k.1 : int = aten::Int(%5) # tmp.py:8:8
  %11 : int = aten::remainder(%k.1, %10) # tmp.py:9:7
  %13 : bool = aten::eq(%11, %12) # tmp.py:9:7
  %k : int = prim::If(%13) # tmp.py:9:4
    block0():
      %k.9 : int = aten::add(%k.1, %16) # tmp.py:10:8
      -> (%k.9)
    block1():
      -> (%k.1)
  %26 : int[] = prim::ListConstruct(%k, %k)
  %29 : float[] = prim::ListConstruct(%sigma.1, %sigma.1)
  %x.5 : Tensor = prim::CallFunction(%30, %x.1, %26, %29) # tmp.py:11:8
  return (%x.5)
```

### Versions

```
PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.7 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.5.1
Libc version: glibc-2.23

Python version: 3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:35:26) [GCC 10.4.0] (64-bit runtime)
Python platform: Linux-4.4.0-210-generic-x86_64-with-glibc2.23
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti
GPU 4: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 470.86
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.12.0
[pip3] torch-fidelity==0.3.0
[pip3] torchac==0.9.3
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.13.0
[conda] numpy                     1.22.0          py310h454958d_0    conda-forge
```

**Comment by Linux-cpp-lisp** [comment] 2022-12-09 19:54
I'm also getting this warning in a codebase that has no interaction at all with `torchvision` (it isn't even installed) so that clearly isn't the issue.  I'm still trying to get a minimal reproducing example that isn't just my whole model, but will post again if I'm able to.

Is there any sense of whether or not this in an important warning, and whether one should be concerned about it?

**Comment by jjsjann123** [comment] 2022-12-09 22:43
pasted from slack

> This ~could as well be~ is a false alarm.
nvfuser requires profiling information (dtypes & dimension & profile-constant scalars) in order to generate kernels. So we have JIT infra throws warnings whenever whenever it sees an empty profile node that doesn't carry profiling information.
This could happen when you have a dead code path. e.g. branches with control flow that is not reached during profiling runs. As long as there's no fallback on codegen, you should be all right. 

In the example you posted, it's not obvious where that conditional is coming from in your script, but if you print out log graph `PYTORCH_JIT_LOG_LEVEL=profiling_graph_executor_impl python [your_example.py]` you'll see a couple cast ops which relies on a profile_ivalue node to determine output dtype, that sit on an idle path.

**Comment by jjsjann123** [comment] 2022-12-09 22:44
So there's not perf impact on this... sorry about this ugliness and this is also tricky for debug. But I think we can close this bug.

As a guide line, if you see codegen complains about taking a fallback path, that's usually when there's perf penalty for not carrying out fusion.

**Closed by jjsjann123** 2022-12-09 22:44 UTC
Labels: oncall: jit

**Comment by baldassarreFe** [comment] 2022-12-10 01:16
Thanks for looking into the issue! Apparently there is nothing to do to avoid the warning and anyway performance is not affected, I'll keep it like this for the moment.

**Comment by Linux-cpp-lisp** [comment] 2022-12-11 03:20
Thanks @jjsjann123 ! That makes sense. To make sure I'm understanding correctly, if those dead paths that are missing profile information do get called, a _different_ warning about having to use a fallback will be generated?  What might that warning look like, and am I right that there is no outcome here that leads to correctness problems, only performance regression?

**Comment by jjsjann123** [comment] 2022-12-12 19:07
> f those dead paths that are missing profile information do get called, a different warning about having to use a fallback will be generated?  

Nope, you won't see another warning about it.

> What might that warning look like, and am I right that there is no outcome here that leads to correctness problems, only performance regression?

Yes, it should be only performance impacted.

The reason is that, the un-profiled block is not being fused by us, because we can't fuse things without profiling information. So that block is just left for TorchScript to handle.
