### ISSUE TITLE
An error happends when using torch.backends.cudnn.CuDNNError before calling  torch.backends.cudnn._libcudnn

### ISSUE THREAD

**Issue by kamo-naoyuki** [pytorch/pytorch#5604] opened 2018-03-07 01:50 UTC
- OS: CentOS7
- PyTorch version:  0.3.1.post2
- How you installed PyTorch (conda, pip, source): conda
- Python version:  3.6
- CUDA/cuDNN version: 9.1/7
- GPU models and configuration:  
- GCC version (if compiling from source): 4.8.5

I'd like to use pytorch with multiprocessing, however, I met an error by the following code.

```python
# torch.multiprocessing could also reproduce
import multiprocessing
import traceback

import torch


class _ExceptionWithTraceback:
    """Hack to embed stringification of remote traceback in local traceback"""
    def __init__(self, exc, tb):
        tb = traceback.format_exception(type(exc), exc, tb)
        tb = ''.join(tb)
        self.exc = exc
        self.tb = '\n"""\n%s"""' % tb

    def __reduce__(self):
        return _rebuild_exc, (self.exc, self.tb)


def _rebuild_exc(exc, tb):
    exc.__cause__ = _RemoteTraceback(tb)
    return exc


class _RemoteTraceback(Exception):
    def __init__(self, tb):
        self.tb = tb

    def __str__(self):
        return self.tb


def f(queue):
    try:
        # version() in order to invoke _libcudnn()
        torch.backends.cudnn.version()
        # Emulate the case that some cudnn error happens
        raise torch.backends.cudnn.CuDNNError(1)
    except torch.backends.cudnn.CuDNNError as e:
        # _ExceptionWithTraceback, which is a technique for rebuild full traceback from other process, has no relations to this issue, but is inserted for  your understanding of my situation
        queue.put(_ExceptionWithTraceback(e, e.__traceback__))

q = multiprocessing.Queue()
p = multiprocessing.Process(target=f, args=[q])
p.start()
q.get()
```
```
Traceback (most recent call last):
  File "a.py", line 43, in <module>
    q.get()
  File ".../lib/python3.6/multiprocessing/queues.py", line 113, in get
    return _ForkingPickler.loads(res)
  File ".../lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 116, in __init__
    msg = '{}: {}'.format(status, get_error_string(status))
  File .../lib/python3.6/site-packages/torch/backends/cudnn/__init__.py", line 278, in get_error_string
    return lib.cudnnGetErrorString(status)
AttributeError: 'NoneType' object has no attribute 'cudnnGetErrorString'
```

This error is caused by instantiating CuDNNError before initialization of cudnn when unpickling from the other process. 

To say, this error can be reproduced by this small code,

```python
import torch
torch.backends.cudnn.CuDNNError(1)
```

This may be edge case,  however, because torch.backends.cudnn.CuDNNError, check_error, and etc. seems public functions, they should be enable to be invoked without exception even if torch.backends.cudnn._libcudnn never be called.

**Comment by ezyang** [comment] 2018-03-07 16:29
I think this might be moot in HEAD, because all of our cuDNN bindings have moved into C++, so CuDNNErroris no longer used by any of our code. But will have to try reproducing.

**Comment by soumith** [comment] 2018-03-13 15:54
closing because as @ezyang said this is fixed in master branch

**Closed by soumith** 2018-03-13 15:54 UTC
