### ISSUE TITLE
circular import with functorch 

### ISSUE THREAD

**Issue by thomaspdl** [pytorch/pytorch#100571] opened 2023-05-03 18:49 UTC
### 🐛 Describe the bug

I tried importing functorch and torch in python 3.9.7
```
import torch
from functorch import vmap, grad
```
and ran into a circular import  issue.

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/var/folders/4p/5v2n8wpn58v6xw674tjlss680000gn/T/ipykernel_64234/1530828949.py in <module>
      1 import torch
----> 2 from functorch import vmap, grad

/usr/local/lib/python3.11/site-packages/functorch/__init__.py in <module>
      5 # LICENSE file in the root directory of this source tree.
      6 import torch
----> 7 from . import _C
      8 
      9 # Top-level APIs. Please think carefully before adding something to the

ImportError: cannot import name '_C' from partially initialized module 'functorch' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/functorch/__init__.py)
```

Any way around it? Is this a bug in the packages? 
Submitting this here since I could not find an easy fix 

### Versions

I ran (note the `python3` instead of `python`)
```
wget https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python3 collect_env.py
```

and got

```
--2023-05-03 11:48:36--  https://raw.githubusercontent.com/pytorch/pytorch/main/torch/utils/collect_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 21550 (21K) [text/plain]
Saving to: ‘collect_env.py.1’

collect_env.py.1    100%[===================>]  21,04K  --.-KB/s    in 0,005s  

2023-05-03 11:48:36 (3,80 MB/s) - ‘collect_env.py.1’ saved [21550/21550]

Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.3 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.10.1
Libc version: N/A

Python version: 3.11.2 (main, Feb 16 2023, 03:15:23) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-12.6.3-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz

Versions of relevant libraries:
[pip3] async-torch==0.0.1
[pip3] functorch==2.0.0
[pip3] numpy==1.24.3
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.1
[pip3] torchvision==0.15.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py37hfbe908c_0  
[conda] mkl_fft                   1.0.15           py37h5e564d8_0  
[conda] mkl_random                1.1.0            py37ha771720_0  
[conda] numpy                     1.18.1           py37h7241aed_0  
[conda] numpy-base                1.18.1           py37h6575580_1  
[conda] numpydoc                  0.9.2                      py_0  
```

I also tried `import torch._functorch as functorch` only to get `ModuleNotFoundError: No module named 'torch._functorch'
`

**Comment by jbschlosser** [comment] 2023-05-03 19:26
Hey @thomaspdl, this sounds like an environment issue, and I'm unable to reproduce it. I suggest reinstalling, and if you still have no luck, posting on the [PyTorch Forums](https://discuss.pytorch.org/), as you're more likely to receive assistance there. Closing for now, but feel free to reopen if discussion on the forums leads you to believe there is a problem within PyTorch itself.

**Closed by jbschlosser** 2023-05-03 19:26 UTC

**Comment by thomaspdl** [comment] 2023-05-03 20:51
tks for the fast turnover @jbschlosser. Will do and reopen this ticket if needs be. Cheers.
