### ISSUE TITLE
CI Standardization for Domain APIs

### ISSUE THREAD

**Issue by vincentqb** [pytorch/pytorch#24344] opened 2019-08-14 18:12 UTC
## 🚀 Feature

We discussed on 8/15/2019 that Domain APIs (torchaudio, torchtext, torchvision) should standardize and unify their CIs around PyTorch's. Opening topic to have a centralized discussion about this :)

## Motivation

* Cover platforms requested by users (CPU/GPU and Linux/Mac/Windows)
* Generate nightly binaries, and simplified release binaries
* Extend binary testing
* Run periodic exhaustive testing
* Leverage examples and tutorials for testing
* Automated benchmarking
* Integrate more smoothly with FB code

## Alternatives

1. The status quo: fragmented effort. What is the status for 
    * torchvision? [related PRs](https://github.com/pytorch/vision/pulls?utf8=%E2%9C%93&q=is%3Apr++CI+) @fmassa
    * torchtext? [related PRs](https://github.com/pytorch/text/pulls?utf8=%E2%9C%93&q=is%3Apr++CI+) @zhangguanheng66
    * torchaudio? [related PRs](https://github.com/pytorch/audio/pulls?utf8=%E2%9C%93&q=is%3Apr++CI+) @cpuhrsch @jamarshon

1. Integrate the domain APIs (or together outside) within PyTorch, so that all the developments tools for PyTorch are automatically available to Domain APIs (as done for `torch.nn`).

1. Move such utilities outside of PyTorch, and import into each repository so that all the developments tools are available equally for each of PyTorch and Domain APIs.

## Additional context

@peterjc123 -- for Windows-related topics

@ezyang -- We discussed that Circle replaces Travis, and is the one being currently for PyTorch due to the following support table. Please feel free to update it.

|    | Linux | Windows | Mac |
| --- | --- | --- | --- |
| CPU | Circle, Azure | Circle, Azure | Circle, Azure |
| GPU | Circle | Jenkins (Circle might later) | -- |
| Binaries | Circle, Azure | Azure (might be replaced by GitHub action) | Circle, Azure |

The only option currently for windows server appears to be Azure.

#24859 -- for binaries discussion
#24915 -- for dataset standardization

cc @ezyang

**Comment by peterjc123** [comment] 2019-08-15 02:59
I think we should use unified scripts for building all of them. It is unwise to keep `torchvision.packaging`, `torchaudio.packaging`  and `torchtext.packaging`. These build scripts should share 90% of the common code, the 10% differences reflect in some environmental flags and build/test commands. One step more, we could even use `pytorch/builder` to build all the binaries, including `pytorch`.
As for Windows builds, I could extend a bit further. Here is the detailed support table.


CI | vCPU | Memory | OS | Boot time | Available disk space | Status | GPU
-- | -- | -- | -- | -- | -- | -- | --
Azure | 2 | 7GB | WS 2012 R2 / 2016 / 2019 | Fast | 14GB | Release | No
Travis | 2 | 8GB | WS 2016 | 60-120s | 19GB | Early Access | Yes
Circle | 4 | 15GB | WS 2019 | Fast | 100GB | Early Access | No
Appveyor | 2 | 6GB | WS 2012 R2 / 2016 | Fast | 50GB | Release | No

From the table, we can see that Azure supports almost all versions of WS and thus the safest choice. CircleCI has the best specs, but I'm worried about using it to build binaries for its lack of support in OS choices. Travis is the only one that has GPU, but its boot time is not so ideal.

**Comment by ezyang** [comment] 2019-08-16 12:42
> One step more, we could even use pytorch/builder to build all the binaries, including pytorch.

One thing that @soumith mentioned to me is that the fact builder/ lives in a separate repository does make it more challenging to do development, because now if you want to stage a change in builder and test if it works, you have to push a new branch, and then edit the PR on the main repository (which actually triggers the build) to use the new branch. I'm not sure there's any way we can solve this problem if we actually want to share code between repositories, but this is one of the reasons why @soumith has argued that packaging should be done separately in each repository. But there really is quite a bit of shared code, and my compromise has been to just copy paste the `pkg_helpers.bash` file between repositories and update the other repositories after I update mine. Perhaps a subtree is the best materialization of this workflow (though subtrees are pretty hard to use IME)

**Comment by soumith** [comment] 2019-08-16 14:35
we can take inspiration from `conda-forge`'s CI mechanism.
The CI and binary build files are checked into the repo, but at any point of time, a bot `re-renders` branches to have the latest CI scripts: [reference](https://github.com/conda-forge/sox-feedstock/pull/19#issuecomment-517371072).

This could be an option -- the source of truth lives in builder, but a bot copies and checks them into each library. Re-rendering via a bot on each PR will pull in the latest commits.
This way development is not hampered either, one can re-render or not, or just test local changes.

**Comment by ezyang** [comment] 2019-08-16 14:54
OK, so basically, it's what I've been doing with `pkg_helpers.bash`, but with a bot. Sounds plausible, though someone will have to build this bot lol.

**Comment by vincentqb** [comment] 2019-08-19 17:53
> we can take inspiration from `conda-forge`'s CI mechanism.
> The CI and binary build files are checked into the repo, but at any point of time, a bot `re-renders` branches to have the latest CI scripts: [reference](https://github.com/conda-forge/sox-feedstock/pull/19#issuecomment-517371072).

Do you mean "still lives inside PyTorch", or into a separate utils repository? Would it be advantageous to have such a separate repository as opposed to having the tools living within the PyTorch repository?

**Comment by huydhn** [comment] 2024-01-23 19:50
Closing this as the issue is old and not relevant anymore.  I think we have made this a reality with all the Nova CI/CD works for domains.

**Closed by huydhn** 2024-01-23 19:50 UTC
Labels: module: binaries, module: build, module: ci, triaged, better-engineering
