### ISSUE TITLE
LRN type mismatch when exported to onnx

### ISSUE THREAD

**Issue by lara-hdr** [pytorch/pytorch#18281] opened 2019-03-21 17:26 UTC
## 🐛 Bug

See https://github.com/Microsoft/onnxruntime/issues/649.

## To Reproduce

import torch
import torch.nn as nn

dummy_input = torch.randn(1, 3, 227, 227, device='cuda')
model = nn.LocalResponseNorm(5, alpha=0.0001, beta=0.75, k=1.0).cuda()
torch.onnx.export(model, dummy_input, "output/some.onnx", verbose=True, input_names=['data'], output_names=['prob'])

Converting this code to ONNX produces a type mismatch error. 
After debugging, it appears that the scalars are being converted as tensors of type Double instead of float for Add and Pow operators from LRN in symbolic.py. 
However, since the scalars are of type float, the tensor type should be float as well, as explained in this note https://github.com/pytorch/pytorch/blob/8356ffa922516f32742740d8ab284527fc6bf05d/torch/onnx/symbolic.py#L225.

Using tensors for beta and k solves the type mismatch issue.
(so using beta=tensor([0.75]), k=tensor([1.0]), instead of beta=0.75, k=1.0)

## Expected behavior

The scalars should be represented as tensors of type float for the add and pow operators from LRN in symbolic.py.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @BowenBao @neginraoof

**Comment by WilliamZhaoz** [comment] 2019-09-20 08:37
Hi, I hit the same bugs, but I did not use LRN, I use a lot of operations, so it is difficult to find the key operation where the problem is. Help. How can I fix this problem.

**Comment by dashesy** [comment] 2019-09-20 18:27
[This issue](https://github.com/pytorch/pytorch/issues/26184) is related. That may be a Python2 issue.

**Comment by WilliamZhaoz** [comment] 2019-09-25 08:26
> [This issue](https://github.com/pytorch/pytorch/issues/26184) is related. That may be a Python2 issue.
Hi dashesy, but I hit this bug when I use Python3, how may I solve the problem. Please.

**Comment by dashesy** [comment] 2019-09-25 18:12
Make sure this is the same issue (float constants exported as double). If it is a different you should open a new issue hopefully with some repro code.

**Comment by garymm** [comment] 2021-09-21 00:53
I think this was fixed at some point but I'm not entirely sure. @lara-hdr or others, can you reproduce on torch 1.9.0 or torch nightlies?

**Comment by thiagocrepaldi** [comment] 2022-01-03 20:36
It’s been over 2 months, so closing this. Feel free to open another one.

**Closed by thiagocrepaldi** 2022-01-03 20:36 UTC
Labels: module: onnx, triaged, onnx-needs-info
