### ISSUE TITLE
[jit] torchvision deeplabv3_resnet101 fails in interpreter

### ISSUE THREAD

**Issue by driazati** [pytorch/pytorch#27549] opened 2019-10-08 17:44 UTC
Noticed in https://github.com/pytorch/vision/pull/1430, `test_deeplabv3_resnet101` fails when executing in TorchScript but passes in eager mode:

```bash
cd vision
python test/test_models.py ModelTester.test_deeplabv3_resnet101
```

```
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 1. Got 38 and 1 in dimension 2 at /home/dev/pytorch/aten/src/TH/generic/THTensor.cpp:689
The above operation failed in interpreter, with the following stack trace:
at /home/dev/vision/torchvision/models/segmentation/deeplabv3.py:92:14
        for conv in self.convs:
            res.append(conv(x))
        res = torch.cat(res, dim=1)
                ~~~~~~~~~ <--- HERE
        return self.project(res)
```

cc @suo

**Comment by eellison** [comment] 2019-10-08 23:55
Fixed in https://github.com/pytorch/vision/pull/1436

This was caused by https://github.com/pytorch/pytorch/issues/26671

**Comment by eellison** [comment] 2019-10-14 20:35
Fix in https://github.com/pytorch/pytorch/pull/27763 landed

**Closed by eellison** 2019-10-14 20:35 UTC
Labels: jit
