### ISSUE TITLE
nn.Sequential constructor add support for regular dict in addition to OrderedDict

### ISSUE THREAD

**Issue by njin19** [pytorch/pytorch#115524] opened 2023-12-11 05:12 UTC
### 🚀 The feature, motivation and pitch

The current code is very strict, and only allows `OrderedDict` in the constructor, see https://pytorch.org/docs/2.0/_modules/torch/nn/modules/container.html#Sequential. 

However, in recent python 3 versions, regular `dict` already respects insertion order, and it would be a lot more convenient to support regular `dict` too, instead of having to manually construct an `OrderedDict`. 

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by albanD** [comment] 2023-12-11 16:48
Closing as a duplicate of https://github.com/pytorch/pytorch/issues/84751 which has quite a bit of discussion on this topic already.

**Closed by albanD** 2023-12-11 16:48 UTC
Labels: module: nn
