### ISSUE TITLE
Different behavior numpy / pytorch with broadcasting & in-place operators

### ISSUE THREAD

**Issue by eguendelman** [pytorch/pytorch#20854] opened 2019-05-23 08:02 UTC
## 🐛 Bug

In the example below, I want to subtract the value of the first column from all columns of a 2D array/tensor.
i.e. `X -= X[:,0][:,np.newaxis]`
(or with pytorch can also do `unsqueeze(1)` instead of `[:,np.newaxis]`)

However, the above expression gives different results when X is a numpy array vs when it is a pytorch Tensor.  Specifically, with pytorch it seems as though the broadcasting is "lazy", and only broadcasts the first column after the first column's self-subtraction.  While with numpy gives the "expected" results.
Is it possible that the above expression, with X appearing on both LHS and RHS and relying on broadcasting, does not have well defined semantics?  Or is this a bug?

## To Reproduce

```python
import torch
import numpy as np

A = torch.Tensor([[1,2,3], [4,5,6]])
B = A.numpy().copy()

print(A) # [[1,2,3],[4,5,6]]
print(B) # [[1,2,3],[4,5,6]]

# Subtract first column from all columns
A -= A[:,0][:,np.newaxis] # or unsqueeze(1)
B -= B[:,0][:,np.newaxis]

print(A) # [[0,2,3],[0,5,6]] (unexpected result / bug)
print(B) # [[0,1,2],[0,1,2]] (this is expected result in my opinion)
```

## Expected behavior

Expected pytorch result (A) to match numpy result (B).

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.9.4-2ubuntu1~14.04.1) 4.9.4
CMake version: version 3.2.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration:
GPU 0: NVS 310
GPU 1: TITAN X (Pascal)

Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.6.0.21
/usr/local/cuda-8.0/targets/x86_64-linux/lib/libcudnn.so.7.0.2

Versions of relevant libraries:
[pip3] numpy==1.16.2
[pip3] torch==1.1.0
[pip3] torchfile==0.1.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

**Comment by fmassa** [comment] 2019-05-23 08:50
This is a duplicate of https://github.com/pytorch/pytorch/issues/906 , https://github.com/pytorch/pytorch/issues/10756 and https://github.com/pytorch/pytorch/issues/8212

We are discussing on a potential solution to this problem by solving a diophantine equation like numpy does https://github.com/pytorch/pytorch/issues/8212, but to the best of my knowledge nobody is working on it.

I'm closing this issue as a duplicate, but I'm bumping the priority of of https://github.com/pytorch/pytorch/issues/8212 to high, because it's a recurrent issue.

**Closed by fmassa** 2019-05-23 08:50 UTC
