### ISSUE TITLE
torch.hub.load_state_dict_from_url fails for state dicts saved with torch==1.6.0

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#42596] opened 2020-08-05 12:05 UTC
## 🐛 Bug

`torch.hub.load_state_dict_from_url` errors when downloading a valid `state_dict`.

## To Reproduce

1. Create a `state_dict`

    ```python
    from torch import hub, nn
    import hashlib
    
    
    def sha256(file: str, chunk_size: int = 4096) -> str:
        hasher = hashlib.sha256()
        with open(file, "rb") as fh:
            for chunk in iter(lambda: fh.read(chunk_size), b""):
                hasher.update(chunk)
        return hasher.hexdigest()
    
    
    file = "conv2d.pth"
    model = nn.Conv2d(3, 3, 1)
    state_dict = model.state_dict()
    torch.save(state_dict, file)
    
    print(sha256(file)[:8])
    ```
    ```
    96603ba9
    ```
2. Upload it (not shown) and make sure its uploaded correctly

    ```python
    url = f"https://download.pystiche.org/models/{file}"
    
    downloaded_file = f"downloaded_{file}"
    hub.download_url_to_file(url, downloaded_file)
    print(sha256(downloaded_file)[:8])
    ```
    ```
    96603ba9
    ```
3. Try to download it directly with `torch.hub.download_state_dict_from_url`

    ```python
    state_dict = hub.load_state_dict_from_url(url)
    ```
    ```
    RuntimeError: Only one file(not dir) is allowed in the zipfile
    ```

## Expected behavior

Load the `state_dict` without error.

## Environment

```
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] Could not collect
```

**Comment by pmeier** [comment] 2020-08-05 12:14
This is related to the `1.6.0` release. I created the same `state_dict` with `torch==1.5.1` (https://download.pystiche.org/models/conv2d-1.5.1.pth) and it can be loaded just fine from `torch==1.6.0`.

**Comment by pmeier** [comment] 2020-08-05 12:27
Since `torch==1.6.0` switched to a zip file-based format, this path is triggered although this shouldn't happen

https://github.com/pytorch/pytorch/blob/b85216887ba76dc7e1e0035c77ebe358ac48f90d/torch/hub.py#L487-L494

Cc @ailzhang

**Comment by gchanan** [comment] 2020-08-05 17:27
Duplicate of https://github.com/pytorch/pytorch/issues/42239.

**Closed by gchanan** 2020-08-05 17:27 UTC
