### ISSUE TITLE
Assertion fails when using DataParallel with two nn.Embedding 

### ISSUE THREAD

**Issue by neocheema** [pytorch/pytorch#14365] opened 2018-11-26 10:24 UTC
## 🐛 Bug
I'm using the nightly build: 1.0.0.dev20181123. This issue is very similar to #13569 .  When I instantiate two nn.Embedding, with DataParallel and with max_norm=1.0, I get the following assert
```
RuntimeError: output_nr_ == 0 ASSERT FAILED at /pytorch/torch/csrc/autograd/variable.cpp:196, please report a bug to PyTorch.
```

If I remove the self.lut_dummy, the issue disappears. 

## To Reproduce
```
import torch
import os

print torch.__version__
class Moda(torch.nn.Module):
    def __init__(self):
        super(Moda, self).__init__()
        self.lut_dummy = torch.nn.Embedding(1, 1, max_norm=1.0).to("cuda")
        self.lut_a = torch.nn.Embedding(22, 256, max_norm=1.0).to("cuda")

    def forward(self, src):
        print "ok1"
        ebd = self.lut_a(src)
        print "ok2"
        return ebd

def main():
    os.environ['CUDA_VISIBLE_DEVICES'] = "0,1"
    model = Moda()
    model = torch.nn.DataParallel(model)
    src = torch.randint(4,(2,)).to("cuda")
    output = model(src)

if __name__ == '__main__':
    main()
```

## Output
1.0.0.dev20181123
/home/software/LM_stash/amitoj/pytorch1.0/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py:25: UserWarning:
    There is an imbalance between your GPUs. You may want to exclude GPU 0 which
    has less than 75% of the memory or cores of GPU 1. You can do so by setting
    the device_ids argument to DataParallel, or by setting the CUDA_VISIBLE_DEVICES
    environment variable.
  warnings.warn(imbalance_warn.format(device_ids[min_pos], device_ids[max_pos]))
ok1
ok1
ok2
Traceback (most recent call last):
  File "error_train.py", line 25, in <module>
    main()
  File "error_train.py", line 22, in main
    output = model(src)
  File "/home/software/LM_stash/amitoj/pytorch1.0/local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 479, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/software/LM_stash/amitoj/pytorch1.0/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 143, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/software/LM_stash/amitoj/pytorch1.0/local/lib/python2.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/software/LM_stash/amitoj/pytorch1.0/local/lib/python2.7/site-packages/torch/nn/parallel/parallel_apply.py", line 83, in parallel_apply
    raise output
RuntimeError: output_nr_ == 0 ASSERT FAILED at /pytorch/torch/csrc/autograd/variable.cpp:196, please report a bug to PyTorch.

## Additional context
Observations
1. If I comment out the self.lut_dummy, the issue disappears. Though in my real model, I am using the `lut_dummy`.
2. If max_norm is removed, the issue disappears again.
3. If I set os.environ["CUDA_VISIBLE_DEVICES"] to "0" or "1", again, the code works just fine.

cc @ezyang @gchanan @SsnL @albanD

**Comment by zou3519** [comment] 2018-11-26 19:49
I can reproduce this on master

**Comment by yf225** [comment] 2018-11-29 02:10
Another observation is that moving `self.lut_dummy = torch.nn.Embedding(1, 1, max_norm=1.0).to("cuda")` after `self.lut_a = torch.nn.Embedding(22, 256, max_norm=1.0).to("cuda")` would make it work. I am still investigating why this happens.

**Comment by yf225** [comment] 2018-11-29 17:50
This is fixed on master by https://github.com/pytorch/pytorch/commit/6d63e9dbfffba9f925ac3af5232390a76aa54dce. https://github.com/pytorch/pytorch/pull/14549 adds a test to make sure it doesn't happen in the future.

**Comment by zou3519** [comment] 2018-12-03 15:53
Some more observations:

`Broadcast` is called to replicate the module parameters.
https://github.com/pytorch/pytorch/blob/b15242f70cce10c0a0f8c36b690ac2481c51814f/torch/nn/parallel/_functions.py#L9-L32

`Broadcast` returns tensors that are views (in the broadcast_coalesced logic the code does some narrowing and viewing). However, autograd assumes that variables that are views must come from autograd functions with exactly one output. It's not entirely wrong but because (hypothesis, I'm going to test this now...) `Broadcast` is a big autograd function that hides its implementation, autograd triggers the assert seen in this issue.

**Comment by zou3519** [comment] 2018-12-03 16:13
I have a minimal repro that does not involve DataParallel:
```
import torch
from torch.autograd import Function

class Flatten3(Function):
    @staticmethod
    def forward(ctx, x, y):
        ctx.save_for_backward(x, y)
        return x.view(-1), y.view(-1)

    @staticmethod
    def backward(ctx, dx, dy):
        x, y = ctx.saved_tensors
        return dx.view(x.shape), dy.view(y.shape)

inputs = [torch.randn(2, 2, requires_grad=True) for _ in range(2)]

# a, b are all DifferentiableViewImpl with output_nr = {0, 1} respectively
a, b = Flatten3.apply(*inputs)

# Modify the counter in no_grad mode.
# b is still a DifferentiableViewImpl with output_nr = 1 (no_grad prevents
# a new autograd function from being created)
with torch.no_grad():
    b.zero_()

# Throws assert because:
# 1) b has been modified in place
# 2) b is a view
# 3) b's output_nr is not 0.
z = b + a
```

**Comment by enk100** [comment] 2019-02-21 14:39
@zou3519 , Are there any news regarding this issue? thanks..

**Comment by wanyu2018umac** [comment] 2019-03-13 03:20
Hi there, I encounter with the same issue.

Although I can call a norm function written by my own after calling backward at the end of every training step, I think it would be more efficient if this could be solved at the level of source code😆.

Thanks for your concern.

**Comment by eagerming** [comment] 2019-07-09 03:25
I encounter the same issue too. When the nn.Embedding initialized with "max_norm=1", then it occurs.

**Comment by albanD** [comment] 2019-08-22 21:27
To answer @zou3519 questions above:

> should torch.no_grad bump the version counter?

Yes, otherwise the computed gradients could be wrong and that should never be possible.

> should we support DifferentiableViewImpl where the output_nr is not 0?

No, the way all the inplace stuff is inplemented only supports single output Functions. It would be a large change to support Functions with more outputs

> should we just error out in this case (instead of assert) and tell the user we don't support modifying views in place when the views aren't the first output of their function?

I would agree that the few asserts at this place should be proper errors. The user can actually make this happen.

**Comment by albanD** [comment] 2020-02-09 02:11
Closing this as duplicate of https://github.com/pytorch/pytorch/issues/14707

**Closed by albanD** 2020-02-09 02:11 UTC
Labels: high priority, module: autograd, triaged
