### ISSUE TITLE
[ONNX] OnnxExporterError when exporting SAGEConv with dynamic_axes

### ISSUE THREAD

**Issue by huhk-sysu** [pytorch/pytorch#89190] opened 2022-11-17 06:09 UTC
### 🐛 Describe the bug

I'm exporting a model built with `torch_geometric.nn.SAGEConv`.
As different graph may have different number of nodes and edges, I make the first dimension of `x` and the second dimension of `edge_index` dynamic. Then the error occurs. 

```python
import torch
from torch_geometric.nn import SAGEConv

class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = SAGEConv(8, 16)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        return x

model = MyModel()
x = torch.randn(3, 8)
edge_index = torch.tensor([[0, 1, 1, 2], [1, 0, 2, 1]])

torch.onnx.export(
    model,
    (x, edge_index),
    "model.onnx",
    opset_version=16,
    input_names=["x", "edge_index"],
    dynamic_axes={
        "x": {0: "n_nodes"},
        "edge_index": {1: "n_edges"}
    }
)
```

```
torch.onnx.errors.OnnxExporterError: Unsupported: ONNX export of operator scatter_add, `index` ([None, None]) should have the same dimensionality as `src` ([None, 8]). Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
```

Without the `dynamic_axes`, the model can be exported sucessfully, however it can't infer on other graphs with different number of nodes or edges.

### Versions

```
torch==1.13.0
torch-geometric==2.1.0.post1
torch-scatter==2.0.9
torch-sparse==0.6.15
```

**Comment by AllenTiTaiWang** [comment] 2022-11-21 18:01
Does this work with nightly pytorch? Could you provide a stand alone scatter_add case for us to give suggestion? Looks like the src/index should match on dimensionality, and this dynamic setting might miss certain rank.

**Comment by AllenTiTaiWang** [comment] 2022-11-21 18:57
I guess you can find how to utilize `dynamic_axes` from #65138. It seems the first dimension of edges should be also dynamic (batches)?

**Comment by huhk-sysu** [comment] 2022-11-22 02:19
> I guess you can find how to utilize `dynamic_axes` from #65138. It seems the first dimension of edges should be also dynamic (batches)?

I have checked the example you provided, but the code there is a bit strange.
According to the [docs](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html#torch_geometric.nn.conv.SAGEConv), the first demension of edges is fixed to `2`. He did some other work before feed them into `SageConv`.
Also, I have a trial that making the first dimension dynamic, but the error remains.

![image](https://user-images.githubusercontent.com/14769033/203200287-c3d59d6d-9c03-4c9d-b60f-2d4886a34e86.png)

For your first question (providing a stand alone case), I can have a try, but it may cost some time for me, because I have to dive into the code of `pytorch_geometric` and I'm not quite familiar with it.

**Comment by titaiwangms** [comment] 2022-11-22 17:42
@huhk-sysu I would guess in the situation of `bipartite`, you would have to give two inputs? For example,
```
torch.onnx.export(
    model,
    ((x, x), edge_index),
    "model.onnx",
    opset_version=16,
    input_names=["x", "edge_index"],
    dynamic_axes={
        "x": {0: "n_nodes"},
        "edge_index": {1: "n_edges"}
    }
)
```
which I use (x, x) here. LMK if this makes sense to you.

**Comment by huhk-sysu** [comment] 2022-11-23 02:29
@titaiwangms 
Thanks but my graph is not `bipartite`, it is just a simple graph with some nodes connected, all nodes are in the same kind. Also the model can be trained and inferred correctly in.

**Comment by titaiwangms** [comment] 2022-11-23 05:20
I raised an issue in ONNX to ask about the spec https://github.com/onnx/onnx/issues/4672

**Comment by huhk-sysu** [comment] 2022-11-23 05:58
> If your model is not bipartite, why does it's first dimension of edge indices needs to be 2?

Hi, I'm following the [introduction](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html) here, `edge_index` has a shape of `[2, num_edges]`. 

![image](https://user-images.githubusercontent.com/14769033/203480743-2d9c8955-661b-4cae-8e7d-039eb010764e.png)

In my opinion my input is making sense.

**Comment by huhk-sysu** [comment] 2022-11-23 06:26
I'm a little confused. I agree that checking `src_sizes != index_sizes` may be useful, but I don't know what leads to the difference of shape. Please tell me if I have done something wrong. 
I have built the model, trained it and it has a good performance (~95% Acc on node classification task). So I don't think my model/ data is problematic.

**Comment by titaiwangms** [comment] 2022-11-23 06:32
So I revisit the problem with graph. If you set the second dim of x to be dynamic, the problem goes away. But I am not an expert on this Conv. Does it make sense semantically?

**Comment by huhk-sysu** [comment] 2022-11-23 06:48
Thank you, that work's for me.
The second dim means 'feature size`. During inferring it would not change, so I didn't make it `dynamic` at first. 
Since the error goes away, this may make sense. Maybe I misunderstood `dynamic_axes`? 
Now I'm going to check the exported onnx model, ensure it behaves like the original one. If everything goes well I will close this issue.

**Comment by huhk-sysu** [comment] 2022-11-23 07:50
@titaiwangms 
Hi, this indeed works for a model with single layer, but it fails when there's more layer.

I add the second layer in the toy model (in fact there're 3 layers in the real case):
```python
class MyModel(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = SAGEConv(8, 16)
        self.conv2 = SAGEConv(16, 8)

    def forward(self, x, edge_index):
        x = self.conv1(x, edge_index)
        x = self.conv2(x, edge_index)
        return x
```

Stacking layers is normal here, it just like stacking `nn.Linear`layers in other networks (I remove activations and dropouts for simplity).

Now the error message comes again:

```
torch.onnx.errors.OnnxExporterError: Unsupported: ONNX export of operator scatter_add, `index` ([None, None]) should have the same dimensionality as `src` ([None, 16]). Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues
```

The number `16` here stands for the `hidden dim size`, and it can't be passed by the `x` or `edge_index`. I don't know how can I do.

**Comment by titaiwangms** [comment] 2022-11-23 22:39
@huhk-sysu
Thanks, this means what we did earlier (making feature size to dynamic) making no sense... so the root cause is that when you make num_nodes dynamic, the index of scatter_add becomes dynamic too, but src isn't. And this difference is not supported in converter currently.

In ONNX spec, the scatter_add op requires `src_sizes == index_sizes`, which in PyTorch src would just accomodate the size to index. In current exporter, we set that as a condition to follow, however, I think we should make a change on that by accommodating src and index when we export it. I had some little experiment of making them both dynamic and it works. But I need more time to confirm if the changes make sense. I will have a PR later.

**Comment by huhk-sysu** [comment] 2022-11-24 02:40
Do you mean there is a special case that `src_sizes != index_sizes` for the `scatter_add` operation in some graph neural networks,  and the exporter don't support the case currently? I wonder when will be next version or pytorch be released, or maybe I should build a latest version myself after the PR?

**Comment by titaiwangms** [comment] 2022-11-28 22:42
> Do you mean there is a special case that src_sizes != index_sizes for the scatter_add operation in some graph neural networks, and the exporter don't support the case for now?

Yes, exporter is not supporting different shape of `src` and `index`. That's the root cause on this.

>  I wonder when will the next version of pytorch be released, or maybe I should build a latest version myself after the PR?

Yes, the PR won't be backported into old version. I guess it would be in 1.14.0. But you could always use master branch (nightly) once it's merged.

**Closed** 2022-12-29 21:30 UTC
Labels: module: onnx, triaged, onnx-triaged
