### ISSUE TITLE
Help/    RuntimeError: fractional_max_pool2d_backward_out_cuda failed with error code 0

### ISSUE THREAD

**Issue by Youarerare** [pytorch/pytorch#34450] opened 2020-03-08 11:43 UTC
My code works fine on cpu，but when I want to train my network on GPU, the error occurred:

Traceback (most recent call last):
  File "/data/private/syk/123/semantic_nli/Task3-Natural Language Inference/run.py", line 177, in <module>
    train(train_iter, dev_iter, loss_func, optimizer, EPOCHS,PATIENCE, CLIP)
  File "/data/private/syk/123/semantic_nli/Task3-Natural Language Inference/run.py", line 147, in train
    loss.backward()
  File "/home/syk/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/syk/anaconda3/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: fractional_max_pool2d_backward_out_cuda failed with error code 0
Process finished with exit code 1

The Error often occurs after training several batches. It's weird. how can I fix it？ Can someone give me some help, thanks.

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ptrblck** [comment] 2020-03-09 03:56
Could you rerun the code with `CUDA_LAUNCH_BLOCKING=1 python script.py args` and post the stack trace here?

Also, could you post a code snippet to reproduce this issue?

**Comment by ngimel** [comment] 2020-03-09 20:48
Likely related to #34083.

**Comment by Youarerare** [comment] 2020-03-10 15:24
Thank you for you reply.
I tried to install gdb for stack trace, but it failed because I am not root, and it took me a lot of time to install various dependencies.
I tried to reproduce this error with a shorter code. The network is the same as the code I used above, the data is a copy from real data. the error seems a little different.

![image](https://user-images.githubusercontent.com/18135822/76327219-b41d1a00-6324-11ea-8e24-a9d60a6626ae.png)
and the code I use is 
[esim.txt](https://github.com/pytorch/pytorch/files/4313182/esim.txt)


Some Other Information may be useful:

my code works well on torch 1.3 , but can't work on torch1.4
Cuda :10.0

**Comment by ngimel** [comment] 2020-03-10 16:21
The error above (device-side assert) is different and most likely related to the not valid data that you are trying to push through the network. Can you try @ptrblck's suggestion and run your original network with  `CUDA_LAUNCH_BLOCKING=1 python script.py args`?

**Comment by Youarerare** [comment] 2020-03-11 02:02
I run my original network with CUDA_LAUNCH_BLOCKING=1 python run.py   
 
the error is the same as 

Traceback (most recent call last):
File "/data/private/syk/123/semantic_nli/Task3-Natural Language Inference/run.py", line 177, in
train(train_iter, dev_iter, loss_func, optimizer, EPOCHS,PATIENCE, CLIP)
File "/data/private/syk/123/semantic_nli/Task3-Natural Language Inference/run.py", line 147, in train
loss.backward()
File "/home/syk/anaconda3/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
torch.autograd.backward(self, gradient, retain_graph, create_graph)
File "/home/syk/anaconda3/lib/python3.7/site-packages/torch/autograd/init.py", line 99, in backward
allow_unreachable=True) # allow_unreachable flag
RuntimeError: fractional_max_pool2d_backward_out_cuda failed with error code 0
Process finished with exit code 1

**Comment by lanjinraol** [comment] 2020-03-12 08:08
I also have the same error. It works when I reduce the size of features.  https://discuss.pytorch.org/t/maxpool2d-error-instead-of-1d/69444

**Comment by ngimel** [comment] 2020-03-12 15:59
@xwang233 can you please take a look if fractional_max_pool has the same bug as the one you recently fixed for max_pool?

**Comment by xwang233** [comment] 2020-03-13 01:05
For the `fractional_max_pool`, please check this 
https://github.com/pytorch/pytorch/blob/9f05fc932270d6758868df847c79e3e6974a052e/aten/src/ATen/native/cuda/DilatedMaxPool2d.cu#L574-L576
which is code within `max_pool2d_with_indices_backward_out_cuda_template` function. I have no idea why it's called `fractional_max_pool`. 

I've checked @Youarerare 's "esim.txt" code, and only `max_pool1d` is used. Similarly in the above [pytorch discuss](https://discuss.pytorch.org/t/maxpool2d-error-instead-of-1d/69444), only `max_pool1d` is used. This is because `max_pool2d` is used as the backend of `max_pool1d` implementation. Please check this 
https://github.com/pytorch/pytorch/blob/9f05fc932270d6758868df847c79e3e6974a052e/aten/src/ATen/native/Pooling.cpp#L45-L70
That's the reason we are seeing error messages from `max_pool2d` instead of `max_pool1d`. 

So both problems are somehow related to `max_pool2d`. Since none of these code is using `torch.channels_last`, I'm not sure if they are related to the channels_last fix. I will keep an eye on the other part of the `max_pool2d` code. 

I tried running the above "esim.txt" code and code posted in discuss forum on [9f05fc9](https://github.com/pytorch/pytorch/commit/9f05fc932270d6758868df847c79e3e6974a052e) with CUDA 10.1, but didn't get any error message. I think the next step is to rerun the code using nightly build after #34519 is merged, so that the CUDA error code can be displayed correctly?

**Comment by chinmay5** [comment] 2020-06-12 13:22
Is there an update on the issue since I am facing the same error. I am trying to port a code from PyTorch 0.4 and things worked fine in it but somehow here I get this error

**Comment by ngimel** [comment] 2020-06-12 16:38
Can you please check if the error you are seeing is fixed on master, and if not, provide a runnable script demonstrating the issue.

**Comment by Youarerare** [comment] 2020-06-12 17:19
> Is there an update on the issue since I am facing the same error. I am trying to port a code from PyTorch 0.4 and things worked fine in it but somehow here I get this error

Is your pytorch version 0.4? Maybe you can try to upgrade pytorch version.
You may try to maxpool a tensor with a larger dimension in the code, which may be a problem during loss backward. In the current version of pytorch, I can no longer reproduce this error.

**Comment by chinmay5** [comment] 2020-06-12 17:24
@Youarerare nop I tried running it uptil PyTorch version 1.5 (I started with 1.2 and moved uptil 1.5) and somehow it does not work. My tensor shape is  torch.Size([128, 442368, 5]) and the kernal is 5 X 5. I am trying to run MaxPool1D here

**Comment by Youarerare** [comment] 2020-06-12 17:42
Ohhhhhhhhhhhhhhhhhhhhhhhhhhh
Here is the short  script to reproduce the error.

`
import torch
import torch.nn.functional as F
from torch.autograd import Variable
device = torch.device("cuda:7")
p = torch.randn(2,12,2800).to(device)  #  batch_size * seqlen  * embedding_dim
lin = torch.nn.Linear(2800,5).to(device)

p = Variable(p,requires_grad=True).to(device)

max_p = F.max_pool1d(p.transpose(1, 2), p.size(1)).squeeze(-1)

result = lin(max_p)
gold_label = torch.tensor([0,1]).to(device)
loss_func = torch.nn.CrossEntropyLoss()

loss = loss_func(result,gold_label)
loss.backward()
`
This error has not been fixed . @ngimel

**Comment by ngimel** [comment] 2020-06-12 17:48
This snippet does not even have fractional max pool, and it runs without error on nightly.

**Comment by Youarerare** [comment] 2020-06-12 17:49
> @Youarerare nop I tried running it uptil PyTorch version 1.5 (I started with 1.2 and moved uptil 1.5) and somehow it does not work. My tensor shape is torch.Size([128, 442368, 5]) and the kernal is 5 X 5. I am trying to run MaxPool1D here

Can you run the code I commented above, I got that error on pytorch1.4, I am not sure if other versions...I did not upgrade pytorch to 1.5 due to some compatibility issues

**Comment by ngimel** [comment] 2020-06-12 17:52
So if you ran in 1.4 only, why do you say that "This error has not been fixed"?

**Comment by Youarerare** [comment] 2020-06-12 17:55
Emmm, Because the buddy above said he tried 1.2-1.5 and sometimes this problem occurred, this is just my guess.May be Possible causes of errors are consistent

**Comment by chinmay5** [comment] 2020-06-12 18:01
@Youarerare It does not work uptil Pytorch 1.5 for sure. I think it would work with the nightly build but I am still running a few tests before I can confirm.

**Comment by chinmay5** [comment] 2020-06-12 19:37
@Youarerare It works with the nightly build so things should be fine with version 1.6, as of now, it is broken

**Comment by xwang233** [comment] 2020-06-12 19:56
> My tensor shape is torch.Size([128, 442368, 5]) and the kernal is 5 X 5. I am trying to run MaxPool1D here

Thank you for the report! There is a known fix to max_pool1d recently #38953, that fixes the backward bug when c > 65535. You can check with master or nightly and see if that fixes the problem of max_pool1d.

@Youarerare @chinmay5 , can you also confirm if there is still any issue on `fractional_max_pool2d_backward_out_cuda`?  If so, please provide a runnable script, or maybe we can close this issue.

**Closed** 2020-06-13 07:24 UTC
Labels: high priority, module: cuda, module: operators, needs reproduction, triaged
