### ISSUE TITLE
Floating point exception(core dumped) pytorch

### ISSUE THREAD

**Issue by luckistmaomao** [pytorch/pytorch#15343] opened 2018-12-18 15:51 UTC
Run with floating point exception(core dumped). 
I try gdb python and get an error like this 

> Program received signal SIGFPE, Arithmetic exception.
> [Switching to Thread 0x7ff04f7fe700 (LWP 10686)]
> 0x00007fffb1b0956a in THCudaLongTensor_fillSliceWithIndex(THCState*, THTensor*, int) () from /dockerdata/anaconda3/lib/python3.6/site-packages/torch/lib/libcaffe2_gpu.so
> 

any help with his?

**Comment by zou3519** [comment] 2018-12-21 17:03
Can you provide a minimal repro that causes the crash?

**Comment by luckistmaomao** [comment] 2018-12-28 14:32
It is solved. I put an an empty tensor into the sort function.

**Comment by zou3519** [comment] 2018-12-28 16:47
Thank you for the response @luckistmaomao. We should fix the case, then, if an empty tensor causes a crash.

**Comment by zou3519** [comment] 2019-01-07 23:12
I can't repro this. @luckistmaomao could you provide some information about your environment?

**Comment by ysfalo** [comment] 2019-01-17 12:38
pytorch=0.4.1
In my case, if a tensor T has size 0 (T.size() retures torch.size(0)), call torch.sort(T, 0, True) will cause floating point exception.

**Comment by rkaplan** [comment] 2019-03-27 01:56
I am getting a `FloatingPointException (core dumped)` as well. This happens with `torch.__version__ == '1.0.0a0+db5d313'`, on a machine running Ubuntu 16.04. I have also verified that this same exception happens on my 2017 Macbook Pro (10.13.6), running PyTorch 1.0.0. Here is a minimal repro:

```python

import torch
import torch.nn as nn

conv = nn.Conv2d(512, 16, 1, stride=0, padding=0, bias=False)
inp = torch.load('fpe_input.torchtensor')
assert inp.shape == torch.Size([1, 512, 26, 40])

# Range of the input values
assert inp.min().item() == 0.0
assert inp.max().item() < 27750

# No NaN values:
assert (inp == inp).sum() == inp.numel()

# FPE happens here:
out = conv(inp)
```

And the `fpe_input.torchtensor` file is attached (inside a zipped directory because GitHub wouldn't let me upload the raw file).
[pytorch_fpe_repro.zip](https://github.com/pytorch/pytorch/files/3011137/pytorch_fpe_repro.zip)

**Comment by soumith** [comment] 2019-03-27 15:52
@rkaplan your particular case was fixed with a proper error message:

```
RuntimeError: invalid argument 11: stride should be greater than zero, but got dH: 0 dW: 0 at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_2.7/pytorch/aten/src/THNN/generic/SpatialConvolutionMM.c:15
```

It's part of master / nightlies, but I believe it's also in 1.0.1

**Comment by soumith** [comment] 2019-03-27 15:53
about the original issue, since we have received no reproduction, and we haven't been able to reproduce it, I'm closing the issue.

**Closed by soumith** 2019-03-27 15:53 UTC
Labels: 1hr, bootcamp, crash, medium priority, needs-reproduction

**Comment by lzkzls** [comment] 2020-04-21 09:38
> @rkaplan your particular case was fixed with a proper error message:
> 
> ```
> RuntimeError: invalid argument 11: stride should be greater than zero, but got dH: 0 dW: 0 at /Users/soumith/b101_2/2019_02_08/wheel_build_dirs/wheel_2.7/pytorch/aten/src/THNN/generic/SpatialConvolutionMM.c:15
> ```
> 
> It's part of master / nightlies, but I believe it's also in 1.0.1

Hi，How did you locate this error? I also have this problem. Floating point exception (core dumped)
