### ISSUE TITLE
`torch.randperm` default dtype is different between eager and TorchScript

### ISSUE THREAD

**Issue by gmagogsfm** [pytorch/pytorch#56676] opened 2021-04-22 07:02 UTC
## 🐛 Bug

`torch.randperm` document claims that when `dtype` arg is not specified, default dtype is set to `torch.int64`. However, this is only true in eager but not in TorchScript.

In eager, dtype is set correctly relying on a hack:
https://github.com/pytorch/pytorch/blob/57cba8e60116bfff37d10bc2b4596d8c478ffd0a/tools/codegen/api/python.py#L740

TorchScript didn't replicate this hack, instead it relies on `aten::randperm` kernel to figure out the dtype, causing inconsistency.

`aten::randperm` kernel uses `TensorOptions` which defaults to `float` when `dtype` is not set:
https://github.com/pytorch/pytorch/blob/57cba8e60116bfff37d10bc2b4596d8c478ffd0a/aten/src/ATen/native/TensorFactories.cpp#L883

I think we should update `aten::randperm` kernel to correctly set dtype when `dtype` arg is not set. 

## To Reproduce

```
import torch

@torch.jit.script
def fn():
    perm = torch.randperm(2)
    print("inferred dtype: %d" % perm.dtype)
    perm = torch.randperm(2, dtype=torch.int64)
    print("dtype with int64 is set: %d" % perm.dtype)

fn()
```

## Expected behavior

TorchScript would not need a hack and it still produces int64 tensor.

cc @ezyang @bhosmer @smessmer @ljk53 @bdhirsh @ailzhang @gmagogsfm

**Comment by gmagogsfm** [comment] 2021-04-22 07:04
@ezyang Ed, any concern in changing this kernel? I am a bit curious about why this hack exists in the first place rather than changing kernel behavior, would changing kernel behavior have implications? thanks.

**Comment by ezyang** [comment] 2021-04-22 14:38
This should get fixed but it will not be so easy to do 100% correctly. The problem is we never wrote code gen for properly defaulting TensorOptions, so TensorOptions currently get defaulted as `TensorOptions options = torch::int64_t`. The wrong thing happens if you pass `device(kCUDA)` to TensorOptions as this entirely overwrites the default, rather than getting merged. A hacky fix would be to force the internals of randperm to do the resolution correctly (reapplying the default if necessary), and probably would be relatively simple to do.

**Comment by Krovatkin** [comment] 2021-04-27 20:30
we also hit this internally. cc: @eellison @penguinwu

**Comment by gmagogsfm** [comment] 2021-04-28 01:57
> This should get fixed but it will not be so easy to do 100% correctly. The problem is we never wrote code gen for properly defaulting TensorOptions, so TensorOptions currently get defaulted as `TensorOptions options = torch::int64_t`. The wrong thing happens if you pass `device(kCUDA)` to TensorOptions as this entirely overwrites the default, rather than getting merged. A hacky fix would be to force the internals of randperm to do the resolution correctly (reapplying the default if necessary), and probably would be relatively simple to do.

I made an attempted fix:https://github.com/pytorch/pytorch/pull/56995

But it still doesn't work because generated `python_torch_function.cpp` still contain incorrect signature:
```
// randperm
static PyObject * THPVariable_randperm(PyObject* self_, PyObject* args, PyObject* kwargs)
{
  HANDLE_TH_ERRORS
  static PythonArgParser parser({
    "randperm(int64_t n, *, Generator? generator, Tensor out=None, ScalarType dtype=None, Layout layout=torch.strided, Device device=None, bool pin_memory=False, bool requires_grad=False)",
    "randperm(int64_t n, *, Tensor out=None, ScalarType dtype=None, Layout layout=torch.strided, Device device=None, bool pin_memory=False, bool requires_grad=False)",
  }, /*traceable=*/true)
```

Is this what you are referring to by "incorrect code gen"? This causes TensorOptions to set `dtype` based on `get_default_scalar_type`, which is `float`. Therefore, in `randperm` kernel, we don't get a chance to know whether `dtype` is specified by user or by TensorOption inference.

Could you clarify what you mean by this?
```
A hacky fix would be to force the internals of randperm to do the resolution correctly (reapplying the default if necessary), and probably would be relatively simple to do.
```

**Comment by gmagogsfm** [comment] 2021-04-28 05:36
Or another solution:
Add logic in randperm kernel to populate correct dtype (`kLong`), this will enable correct behavior in TorchScript. Leave the hack of
https://github.com/pytorch/pytorch/blob/57cba8e60116bfff37d10bc2b4596d8c478ffd0a/tools/codegen/api/python.py#L740 

as is, so that eager maintains current behavior too until code gen is fixed. @ezyang

**Comment by ezyang** [comment] 2021-04-28 15:28
https://github.com/pytorch/pytorch/issues/56676#issuecomment-828158068 is what I meant by the hacky fix.

**Comment by gmagogsfm** [comment] 2021-04-28 15:56
> [#56676 (comment)](https://github.com/pytorch/pytorch/issues/56676#issuecomment-828158068) is what I meant by the hacky fix.

Thanks for confirmation. Just sent PR your way for review.

**Closed** 2021-04-28 23:20 UTC
Labels: module: internals, oncall: jit

**Comment by gmagogsfm** [comment] 2021-04-29 00:48
> we also hit this internally. cc: @eellison @penguinwu

This has been fixed. Please try again, let me know if additional help is needed
