### ISSUE TITLE
test_proper_exit intermittently fails

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#14501] opened 2018-11-28 22:00 UTC
Log:

```
21:31:08 test_proper_exit (__main__.TestDataLoader)
21:31:08 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore ... Traceback (most recent call last):
21:31:10   File "<string>", line 1, in <module>
21:31:10   File "C:\Jenkins\Miniconda3\lib\multiprocessing\spawn.py", line 105, in spawn_main
21:31:10     exitcode = _main(fd)
21:31:10   File "C:\Jenkins\Miniconda3\lib\multiprocessing\spawn.py", line 115, in _main
21:31:10     self = reduction.pickle.load(from_parent)
21:31:10   File "C:\Jenkins\Miniconda3\lib\multiprocessing\connection.py", line 942, in rebuild_pipe_connection
21:31:10     handle = dh.detach()
21:31:10   File "C:\Jenkins\Miniconda3\lib\multiprocessing\reduction.py", line 129, in detach
21:31:10     self._access, False, _winapi.DUPLICATE_CLOSE_SOURCE)
21:31:10 PermissionError: [WinError 5] Access is denied
21:31:25 FAIL

21:32:15 ======================================================================
21:32:15 FAIL: test_proper_exit (__main__.TestDataLoader)
21:32:15 There might be ConnectionResetError or leaked semaphore warning (due to dirty process exit), but they are all safe to ignore
21:32:15 ----------------------------------------------------------------------
21:32:15 Traceback (most recent call last):
21:32:15   File "C:\Jenkins\workspace\pytorch-builds\pytorch-win-ws2016-cuda9-cudnn7-py3-test2\test\common_utils.py", line 117, in wrapper
21:32:15     fn(*args, **kwargs)
21:32:15   File "test_dataloader.py", line 726, in test_proper_exit
21:32:15     self.assertTrue(setup_event.is_set(), 'loader process setup timed out')
21:32:15 AssertionError: False is not true : loader process setup timed out
21:32:15 
21:32:15 ----------------------------------------------------------------------
```

Context: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-win-ws2016-cuda9-cudnn7-py3-test2/16532/console https://github.com/pytorch/pytorch/pull/14490

**Comment by ezyang** [comment] 2019-01-17 07:03
Not just on Windows: https://circleci.com/gh/pytorch/pytorch/570888?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by ezyang** [comment] 2019-01-22 15:57
https://circleci.com/gh/pytorch/pytorch/603394?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

cc @SsnL

**Comment by SsnL** [comment] 2019-01-23 02:03
The windows error is likely due to the Python bug https://bugs.python.org/issue34513, which isn't resolved yet. I'll take a look at the linux timeouts.

**Comment by ezyang** [comment] 2019-04-05 14:28
This is still flaky on master. https://circleci.com/gh/pytorch/pytorch/1184431?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by SsnL** [comment] 2019-04-05 17:05
sigh, i will get a docker image and see if I can reproduce this and failures in https://github.com/pytorch/pytorch/issues/16608

**Comment by ezyang** [comment] 2019-04-06 16:01
The test has been disabled, downgrading priority.

**Comment by SsnL** [comment] 2019-04-23 05:52
closed in favor of https://github.com/pytorch/pytorch/issues/16608

**Closed by SsnL** 2019-04-23 05:52 UTC
Labels: module: dataloader, topic: flaky-tests, triaged
