### ISSUE TITLE
torch.rfft segfaults with CPU, but works with GPU

### ISSUE THREAD

**Issue by WUhailing** [pytorch/pytorch#25640] opened 2019-09-04 07:43 UTC
## 🐛 Bug

torch.rfft does not work with CPU 

## To Reproduce

1. use example from docs: help(torch.rfft)
2. test torch.rfft on PyTorch 1.0 and 1.2,  return same segfaults info
3. test torch.fft with CPU and GPU, everything is fine

>>> x = torch.randn(5, 5)
>>> torch.rfft(x.cuda(),2).shape
       torch.Size([5, 3, 2])
>>> torch.rfft(x,2).shape
       Segmentation fault (core dumped)

## Expected behavior

 help find the root cause and fix the bug

## Environment

PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 415.27
cuDNN version: /usr/local/cuda-9.0/targets/x86_64-linux/lib/libcudnn.so.7.0.5

Versions of relevant libraries:
[pip3] numpy==1.14.0
[pip3] numpydoc==0.7.0
[conda] cuda90                    1.0                  h6433d27_0    
[conda] mkl                       2019.4                      243    defaults
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    
[conda] torchvision               0.4.0                py36_cu100

**Comment by chenzhekl** [comment] 2019-09-04 16:02
Probably it’s related to this according to the documentation of rfft

> For CPU tensors, this method is currently only available with MKL. Use torch.backends.mkl.is_available() to check if MKL is installed.

**Comment by WUhailing** [comment] 2019-09-04 16:09
Ya, I did check the docs and test that MKL is installed. Problem is I cannot find any source code of rfft to check if something does not work inside. :(





come from dingtalk mailbox------------------------------------------------------------------
Sender:Zhe Chen<notifications@github.com>
Date:2019/09/05 00:03:44
Recipient:pytorch/pytorch<pytorch@noreply.github.com>
Cc:WUhailing<hailing@smartahc.com>; Author<author@noreply.github.com>
Theme:Re: [pytorch/pytorch] torch.rfft segfaults with CPU, but works with GPU (#25640)

Probably it’s related to this according to the documentation of rfft 
For CPU tensors, this method is currently only available with MKL. Use torch.backends.mkl.is_available() to check if MKL is installed.

**Comment by ailzhang** [comment] 2019-09-04 17:56
@WUhailing Hmm I cannot reproduce this on master, would you mind try installing from source and see if that works?

**Comment by mruberry** [comment] 2020-10-10 09:08
Closing due to lack of reproduction. @WUhailing, if you can still reproduce this issue please update and reopen this issue.

**Closed by mruberry** 2020-10-10 09:08 UTC
Labels: module: mkl, module: operators (deprecated), triaged
