### ISSUE TITLE
Failed to build libtorch because "Multiple definition of at::naive::DispatchStub"

### ISSUE THREAD

**Issue by magicwyzh** [pytorch/pytorch#15785] opened 2019-01-07 07:40 UTC
Hi, I want to build libtorch from source without cuda because the official binary is using old C++ABI. The steps i did is as follows:

1. cd pytorch
2. mkdir build && cd build
3. BUILD_TORCH=ON ONNX_NAMESPACE=onnx_torch bash ../tools/build_pytorch_libs.sh --use-nnpack caffe2

And then i meet the following errors:
```
Linking CXX shared library ../lib/libcaffe2.so
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp.o:(.data.rel.local+0x0): multiple definition of `at::native::DispatchStub<void (*)(at::Tensor&, at::Tensor const&), at::native::truncImpl>::AVX2'
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.o:(.data.rel.local+0x0): first defined here
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp.o:(.data.rel.local+0x8): multiple definition of `at::native::DispatchStub<void (*)(at::Tensor&, at::Tensor const&), at::native::tanhImpl>::AVX2'
CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.o:(.data.rel.local+0x8): first defined here
//many errors like above
//many errors like above
collect2: error: ld returned 1 exit status
caffe2/CMakeFiles/caffe2.dir/build.make:58764: recipe for target 'lib/libcaffe2.so' failed
make[2]: *** [lib/libcaffe2.so] Error 1
CMakeFiles/Makefile2:1305: recipe for target 'caffe2/CMakeFiles/caffe2.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
```

There are a lot of similar errors like this. According to the comments in https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/DispatchStub.h, this file is compiled for multiple times and then linked. But this information still cannot help me figure out how to fix it.

My environment:
OS: Ubuntu18.04 LTS （Windows Linux Subsystem)
Compiler: GCC7.3
CMake: 3.12
pytorch master: eeb14675f12a19822d3a13f3d203c6396ee6cfdd

Is there any idea? Thanks very much!!

**Comment by ezyang** [comment] 2019-01-07 07:46
This should work. Can you post the full output of https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py

cc @goldsborough @cpuhrsch @colesbury

**Comment by magicwyzh** [comment] 2019-01-07 10:02
Hi @ezyang ,
The following is the output:

```
wyzh@DESKTOP-3VACA19:~/pytorch_src/pytorch$ python torch/utils/collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.1                      144
[conda] mkl-include               2019.1                      144
[conda] mkl-service               1.1.2            py37he904b0f_5
[conda] mkl_fft                   1.0.6            py37hd81dba3_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
```

Thanks for help:)

**Comment by magicwyzh** [comment] 2019-01-07 10:35
Or if somebody can provide me a libtorch binary that use new C++11 ABI (rather than the one downloaded from https://download.pytorch.org/libtorch/cpu/libtorch-win-shared-with-deps-latest.zip, which is built with -D_GLIBCXX_USE_CXX11_ABI=0), that will also be of great help:)

Thanks a lot!

**Comment by Xfel** [comment] 2019-01-28 09:03
I encountered the same error, and was able to solve it by cleaning up my working directory. The documentation for the build scripts did not mention that they use the current directory as build directory, so I accidentally created an in-source build. This did not work for other reasons, but when I switched to a separate build directory, the generated files were still in the regular source directory.

This is how you get source files like: 
`UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp`
The generator just picks up the already-generated files left in the source too. Delete those and do an out-of-source build, that should fix it. 

For the pytorch team: Since in-source builds don't work, the build scripts should automatically take care of creating a build directory.

**Comment by HerculesJack** [comment] 2019-02-15 00:42
I once encountered the same issue, though it's probably because I commented out a sanitary check and tried to do in-source builds. See #17139.

**Comment by soumith** [comment] 2019-03-01 03:24
@magicwyzh you can build libtorch via commands here: https://github.com/pytorch/builder/blob/master/manywheel/build_common.sh#L134
You can build it in docker image: soumith:manylinux100, see https://github.com/pytorch/builder/tree/master/manywheel

**Comment by ezyang** [comment] 2019-06-13 16:09
I think this is a dupe of #20686, as I see `UnaryOpsKernel.cpp.DEFAULT.cpp.DEFAULT.cpp.DEFAULT.cpp.AVX2.cpp.AVX2.cpp` which is due to us generating the files too many times. I'm going to close this in favor of that bug. Cleaning your source directory will help.

**Closed by ezyang** 2019-06-13 16:09 UTC
Labels: module: build

**Comment by marcjoos-phd** [comment] 2020-01-22 10:20
I have a related issue with the current version of PyTorch (1.4, which I got from a `git clone --recursive` of the GitHub repo), compiling with gcc 8.3.0, on RHEL 7.6. Here is what I do:

- `USE_BLAS=MKL setup.py bdist_wheel` (that fails for some reason because it is unable to efficiently detect my Intel MKL install)
- `cd build`
- `[cmake command line from the previous setup.py] -DINTEL_MKL_DIR=$MKLROOT`
- `cd ..; USE_BLAS=MKL setup.py bdist_wheel`

It is not a in-source build. The extraneous files are located in `build/` and not directely in the sources. I checked the sources, nothing weird seems to be there.
