### ISSUE TITLE
Gradient tests failing for `max_unpool3d` (`test_fn_grad`)

### ISSUE THREAD

**Issue by krshrimali** [pytorch/pytorch#67658] opened 2021-11-02 03:16 UTC
## 🐛 Bug

Following errors are observed (on both CUDA and CPU devices):

<details>

```python
======================================================================
ERROR: test_fn_grad_nn_functional_max_unpool3d_cpu_float64 (__main__.TestGradientsCPU)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/krshrimali/pytorch/test/test_ops.py", line 603, in test_fn_grad
    self._grad_test_helper(device, dtype, op, op.get_op())
  File "/home/krshrimali/pytorch/test/test_ops.py", line 586, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,
  File "/home/krshrimali/pytorch/test/test_ops.py", line 559, in _check_helper
    self.assertTrue(gradcheck(fn, gradcheck_args,
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_utils.py", line 2718, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1273, in gradcheck
    return _gradcheck_helper(**args)
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1286, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 947, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1168, in _fast_gradcheck
    _check_analytical_numerical_equal(analytical_vJu, numerical_vJu, complex_indices,
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1148, in _check_analytical_numerical_equal
    raise GradcheckError(_get_notallclose_msg(a, n, j, i, complex_indices, test_imag, is_forward_ad) + jacobians_str)
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor(0.1592)
analytical:tensor(0.2428)

The above quantities relating the numerical and analytical jacobians are computed
in fast mode. See: https://github.com/pytorch/pytorch/issues/53876 for more background
about fast mode. Below, we recompute numerical and analytical jacobians in slow mode:

Numerical:
 tensor([[0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 1.0000]])
Analytical:
tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.]])

The max per-element difference (slow mode) is: 1.0.


======================================================================
ERROR: test_fn_grad_nn_functional_max_unpool3d_cuda_float64 (__main__.TestGradientsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_utils.py", line 1422, in wrapper
    method(*args, **kwargs)
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_utils.py", line 1422, in wrapper
    method(*args, **kwargs)
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 376, in instantiated_test
    raise rte
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 371, in instantiated_test
    result = test(self, **param_kwargs)
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_device_type.py", line 737, in test_wrapper
    return test(*args, **kwargs)
  File "/home/krshrimali/pytorch/test/test_ops.py", line 603, in test_fn_grad
    self._grad_test_helper(device, dtype, op, op.get_op())
  File "/home/krshrimali/pytorch/test/test_ops.py", line 586, in _grad_test_helper
    return self._check_helper(device, dtype, op, variant, 'gradcheck', check_forward_ad=check_forward_ad,
  File "/home/krshrimali/pytorch/test/test_ops.py", line 559, in _check_helper
    self.assertTrue(gradcheck(fn, gradcheck_args,
  File "/home/krshrimali/pytorch/torch/testing/_internal/common_utils.py", line 2718, in gradcheck
    return torch.autograd.gradcheck(fn, inputs, **kwargs)
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1273, in gradcheck
    return _gradcheck_helper(**args)
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1286, in _gradcheck_helper
    _gradcheck_real_imag(gradcheck_fn, func, func_out, tupled_inputs, outputs, eps,
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 947, in _gradcheck_real_imag
    gradcheck_fn(func, func_out, tupled_inputs, outputs, eps,
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1168, in _fast_gradcheck
    _check_analytical_numerical_equal(analytical_vJu, numerical_vJu, complex_indices,
  File "/home/krshrimali/pytorch/torch/autograd/gradcheck.py", line 1148, in _check_analytical_numerical_equal
    raise GradcheckError(_get_notallclose_msg(a, n, j, i, complex_indices, test_imag, is_forward_ad) + jacobians_str)
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor(0.1246, device='cuda:0')
analytical:tensor(0.2419, device='cuda:0')

The above quantities relating the numerical and analytical jacobians are computed
in fast mode. See: https://github.com/pytorch/pytorch/issues/53876 for more background
about fast mode. Below, we recompute numerical and analytical jacobians in slow mode:

Numerical:
 tensor([[0.0000, 0.0000, 1.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        ...,
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 1.0000],
        [0.0000, 0.0000, 0.0000,  ..., 0.0000, 0.0000, 0.0000]],
       device='cuda:0')
Analytical:
tensor([[0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 1.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.],
        ...,
        [0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 1.],
        [0., 0., 0.,  ..., 0., 0., 1.]], device='cuda:0')

The max per-element difference (slow mode) is: 1.0.


----------------------------------------------------------------------
```

</details>

## To Reproduce

1. Checkout to the branch: https://github.com/krshrimali/pytorch/tree/origin/max_unpoolNd
2. Run the OpInfo tests after removing the skips for `max_unpool3d`. `python3 test/test_ops.py -k max_unpool3d`

## Expected behavior

The tests should pass.

## Additional context

* Please see #67328 and #67328 (comment) for the discussion.
* Please also note that `aten::max_unpool3d_backward` is not yet implemented, and hence - `test_fn_gradgrad` fails. Not raising an issue for this, since it's more like an implementation detail and I'm not sure if it's a TODO already.

cc: @albanD @nikitaved 

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @mruberry @walterddr

**Comment by nikitaved** [comment] 2021-11-10 16:55
I am taking this. The backward method is a custom kernel which was not tested. We can replace this kernel with a combination of reshape and gather.

**Comment by nikitaved** [comment] 2022-05-05 10:17
Closing it. The issue is not the backward, but that in sample inputs there are several elements that attain local max and gradcheck has no way to be aware about that.

**Closed by nikitaved** 2022-05-05 10:17 UTC
Labels: high priority, module: autograd, module: nn, triaged, actionable, module: correctness (silent), module: pooling
