### ISSUE TITLE
Running pytorch 1.0.0 on aws lambda

### ISSUE THREAD

**Issue by bendidi** [pytorch/pytorch#14968] opened 2018-12-09 18:29 UTC
## ❓ Questions and Help

Hello,

I'm trying to run pytorch v1.0.0 on aws lambda for object detection inference, and i'm building the package on `lambci/lambda:build-python3.6` docker image using the following command lines : 
```Docker
RUN git clone --recursive https://github.com/pytorch/pytorch.git --branch=v1.0.0

ENV NO_CUDA=1
ENV NO_TEST=1
ENV NO_NNPACK=1
ENV NO_QNNPACK=1
ENV NO_MKLDNN=1
ENV NO_DISTRIBUTED=1
ENV NO_CUDNN=1
ENV NO_FBGEMM=1
ENV NO_MIOPEN=1
ENV NO_CAFFE2_OPS=1
ENV BUILD_BINARY=0

RUN cd pytorch && python setup.py install
```

the torch package is build successfully and I'm able to upload it on aws lambda, but I get the following errors when I try to run inference : 
`Error in cpuinfo: failed to parse the list of possible procesors in /sys/devices/system/cpu/possible`
`Error in cpuinfo: failed to parse the list of present procesors in /sys/devices/system/cpu/present`

knowing that I disabled NNPACK, QNNPACK and  MKLDNN in the build above (I'm not sure if it's related or not) 

I was able to do the same a couple months back using just caffe2, here is the snippet of code and the commit I was using: 

```
RUN git clone --recursive https://github.com/pytorch/pytorch.git /caffe2
WORKDIR /caffe2
RUN git checkout 8601b33c079545bcd45b37983d2ec355b2215960
RUN git submodule update --init --recursive
RUN cp -a -r /caffe2/modules/detectron/*.cu /caffe2/caffe2/operators/
RUN cp -a -r /caffe2/modules/detectron/*.cc /caffe2/caffe2/operators/
RUN cp -a -r /caffe2/modules/detectron/*.h /caffe2/caffe2/operators/

RUN mkdir build && cd build && \
    cmake -DUSE_GFLAGS=OFF \
          -DUSE_GLOG=OFF \
          -DBUILD_SHARED_LIBS=OFF \
          -DCMAKE_INSTALL_PREFIX="/cf2/" \
          -DCMAKE_PREFIX_PATH="/cf2/" \
          -DUSE_GLOO=OFF \
          -DUSE_CUDA=OFF \
          -DUSE_MPI=OFF \
          -DUSE_METAL=OFF \
          -DUSE_NCCL=OFF \
          -DUSE_NNPACK=OFF \
          -DUSE_MOBILE_OPENGL=OFF \
          -DBUILD_CUSTOM_PROTOBUF=OFF \
          -DUSE_LEVELDB=OFF \
          -DUSE_LMDB=OFF \
          -DUSE_NUMA=OFF \
          -DUSE_OPENCV=OFF \
          -DUSE_NCCL=OFF \
          .. \
          &&  make -j$(nproc) \
          && make install/fast \
          && ldconfig
```

at that time I was getting the same cpuinfo error when i was building with NNPACK, but no problem once I disabled NNPACK 

Thanks,
Bendidi

**Comment by norahsakal** [comment] 2018-12-14 09:57
I built my package with the whl https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl and experienced the same issue, I switched back to building the package with https://download.pytorch.org/whl/cpu/torch-0.4.1-cp36-cp36m-linux_x86_64.whl instead as a quick fix, which made my image classification work.

**Comment by bendidi** [comment] 2018-12-14 12:06
Hi @norahsakal I'm trying to use https://github.com/facebookresearch/maskrcnn-benchmark on lambda and it's necessary to use pytorch 1.0 for it, and as I've said a previous version of caffe2/pytorch was working for me too

**Comment by norahsakal** [comment] 2018-12-15 05:10
Oh I see, exciting project, thanks! @bendidi

**Comment by ezyang** [comment] 2018-12-18 16:59
This is not a build issue, it looks like our runtime CPU detection via cpuinfo assumes that `/sys/devices/system/cpu/possible` is available, which apparently on Amazon Lambda it is not.

CC @Maratyszcza

**Comment by soumith** [comment] 2018-12-18 17:06
duplicate of https://github.com/pytorch/pytorch/issues/15213

Tracking a fix there.

**Closed by soumith** 2018-12-18 17:06 UTC

**Comment by mattmcclean** [comment] 2019-02-26 08:21
@bendidi did you try out the fix? keen to know if it worked. Also, by compiling from source are you able to get the package size under 250 MB to avoid going over the AWS Lambda package limit?

**Comment by bendidi** [comment] 2019-02-26 09:18
@mattdawkins i've answered in #15213
