### ISSUE TITLE
F.avg_pool2d() crashes with Complex tensor

### ISSUE THREAD

**Issue by torridgristle** [pytorch/pytorch#82266] opened 2022-07-26 22:18 UTC
### 🐛 Describe the bug

```
import torch
import torch.nn.functional as F

F.avg_pool2d(torch.view_as_complex_copy(torch.randn([1,1,32,32,2])),2)
```

Doing this crashes the session Colab. I can't tell you what exactly broke where.

However doing this with F.max_pool2d() doesn't crash at all and instead gives the error message `"max_pool2d" not implemented for 'ComplexFloat'`

### Versions

PyTorch version: 1.12.0+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.5
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.0+cu113
[pip3] torchaudio==0.12.0+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.0
[pip3] torchvision==0.13.0+cu113
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @ezyang @anjali411 @dylanbespalko @Lezcano @nikitaved

**Comment by jbschlosser** [comment] 2022-07-27 16:01
Hey @torridgristle, thanks for the report! I'm unable to reproduce this on a nightly version of PyTorch. It gives me the expected:

```
RuntimeError: "avg_pool2d" not implemented for 'ComplexFloat'
```

Would you mind checking if the issue persists when using a nightly?

**Comment by torridgristle** [comment] 2022-07-27 22:40
> Hey @torridgristle, thanks for the report! I'm unable to reproduce this on a nightly version of PyTorch. It gives me the expected:
> 
> ```
> RuntimeError: "avg_pool2d" not implemented for 'ComplexFloat'
> ```
> 
> Would you mind checking if the issue persists when using a nightly?

Installed nightly via `!pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu102/torch_nightly.html -U`

In nightly I get `RuntimeError: "avg_pool2d" not implemented for 'ComplexFloat'` as expected. No crashing.

**Comment by jbschlosser** [comment] 2022-07-28 13:53
Awesome - closing as addressed in nightly but feel free to reopen if needed.

**Closed by jbschlosser** 2022-07-28 13:53 UTC
Labels: needs reproduction, module: nn, triaged, module: complex
