### ISSUE TITLE
torch.svd() computes wrong result (compared to numpy.linalg.svd())

### ISSUE THREAD

**Issue by themightyoarfish** [pytorch/pytorch#16076] opened 2019-01-16 14:38 UTC
## Possibly 🐛 Bug

Maybe I'm using the API wrong (but params are identical for numpy and torch functions), but the [linked matrix](https://www.dropbox.com/s/sqmcrsl86e5ya70/invertme.npy?dl=0) results in completely different pseudoinverse matrices.
```
import numpy as np, torch

array = np.load('invertme.npy')
pinv_np = np.linalg.pinv(array)
pinv_th = torch.pinverse(torch.tensor(array))

assert np.allclose(pinv_np, pinv_th)
```

**Comment by themightyoarfish** [comment] 2019-01-16 14:46
I've narrowed it down to the application of SVD. The results are very different between numpy and pytorch. Out of U, S, V, only S is the same, the others are different.

**Comment by themightyoarfish** [comment] 2019-01-16 14:50
I've narrowed it down to the application of SVD. The results are very different between numpy and pytorch. Out of U, S, V, only S is the same, the others are different. 
The respective docs state that LAPACK `gesdd` is used in both cases, so it would surprise me if this was due to numerical issues.

**Comment by themightyoarfish** [comment] 2019-01-16 15:04
Here is a plot of the difference between numpy and pytorch results for U.

![figure_1](https://user-images.githubusercontent.com/11613312/51257624-4e473380-19a8-11e9-9ed8-2685606dbd7d.png)

**Comment by zou3519** [comment] 2019-01-17 16:06
This sounds bad if true

**Comment by themightyoarfish** [comment] 2019-01-17 16:11
I would appreciate it greatly if someone could take a look at this soon since it is blocking me severely right now.

**Comment by vishwakftw** [comment] 2019-01-17 17:14
I can reproduce this on both CPU (with LAPACK) and GPU (with MAGMA).

**Comment by soumith** [comment] 2019-01-17 17:16
i'm marking this as a 1.0.1 blocker. Let us know if you need help with progress @vishwakftw

**Comment by vishwakftw** [comment] 2019-01-17 17:17
Sure, thank you.

**Comment by vishwakftw** [comment] 2019-01-17 17:34
I can confirm that the matrix is terribly ill-conditioned.

Condition number = max singular value / min singular value ~ 10^8 .

**Comment by themightyoarfish** [comment] 2019-01-17 17:37
I see. It's interesting then; the problem occurs in the context of [google's svcca](https://github.com/google/svcca), where the input matrix consists of activations of a layer's neurons over a set of datapoints, i.e. each row is one neuron's activations. I wonder if the fact that such a matrix is ill-conditioned tells me anything.

**Comment by vishwakftw** [comment] 2019-01-17 18:11
I think the issue is possibly restricted to ill-conditioned matrices. The following script proves this behavior:

```python
import torch

device = 'cpu'  # modify to test on a different device
N = 954  # size

# Step 1: create an conditioned singular value vector
s = torch.arange(N + 1, 1, -1, device=device).float().log()  # the condition number here is ~ log(N)
s_mat = torch.diag(s)

# Step 2: generate orthogonal matrices using QR on a random matrix
q, _ = torch.randn(N, N, device=device).qr()
assert (q @ q.t() - torch.eye(N, device=device)).abs().max() < 1e-04

# Step 3: generate the well-conditioned matrix
a = q @ s_mat @ q.t()
u, sigma, v = a.svd()
assert (a - u @ torch.diag(sigma) @ v.t()).abs().max() < 1e-04
```

I have run this multiple (~ 100) times on CPU (with LAPACK) and on GPU (with MAGMA), and in none of the trials did the asserts fail.

**Comment by soumith** [comment] 2019-01-17 18:48
thanks a lot for looking into this quickly Vishwak. I'm closing this as it's expected behavior on ill-conditioned matrices.

@themightyoarfish pseudoinverse of an ill-conditioned matrix, is that even mathematically possible as a guarantee? I am not a linear algebra person, but I think the matrices have to have some constraints to begin with. Again, I am not an expert :)
I think @SsnL would know has he has a lot of experience here.

**Closed by soumith** 2019-01-17 18:48 UTC

**Comment by themightyoarfish** [comment] 2019-01-17 19:05
Yeah I'm not sure what I'm even asking right now, since the reality is more involved (svcca computes pseudoinverse of covariance matrices of activations). But maybe it's somehow informative if a covariance matrix is ill-conditioned?

**Comment by SsnL** [comment] 2019-01-18 01:46
Yeah, the U and V are not unique for singular input matrixes (think about the e-vectors for e-values=0). So this is expected.

**Comment by iperov** [comment] 2019-03-27 20:10
torch.svd different from numpy, scipy and tensorflow svd

**Comment by iperov** [comment] 2019-03-27 20:11
so if something trained with torch.svd, there is no way to port the model to other frameworks

**Comment by SsnL** [comment] 2019-03-27 20:27
@iperov only for the parts of U V matrices corresponding to singular e-values though. You should never depend on those.

**Comment by iperov** [comment] 2019-03-27 20:31
@SsnL but https://github.com/clovaai/WCT2 does

**Comment by iperov** [comment] 2019-03-27 20:34
@SsnL and NVIDIA WCT also depends on it 

https://github.com/NVIDIA/FastPhotoStyle/blob/master/photo_wct.py

**Comment by SsnL** [comment] 2019-03-27 20:36
sorry, but the NVIDIA WCT script you linked obviously filters out zero singular values.

**Comment by iperov** [comment] 2019-03-27 20:39
I am trying to port torch WCT to pure numpy in order to transfer style of decoder layers of https://github.com/clovaai/WCT2 repo
but result is very different, because network trained on wrong svd implementation.

**Comment by iperov** [comment] 2019-03-27 20:43
from WCT2 paper:
![firefox_2019-03-28_00-43-37](https://user-images.githubusercontent.com/8076202/55110892-867a9900-50f2-11e9-8364-b91f08672a73.jpg)
wct with wrong svd used in training.

**Comment by SsnL** [comment] 2019-03-27 20:44
1. There is no **wrong** svd impl. All libs your mentioned are correct. Read the mathematical definition before you claim something to be wrong.
2. The WCT2 repo you linked also obviously filters out zero singular values. See https://github.com/clovaai/WCT2/blob/22b16df7e6c30b5cf11c022235286ce565201241/utils/core.py#L33-L69.

**Comment by SsnL** [comment] 2019-03-27 20:46
The same matrix can have many SVD decompositions. I don't even know what you are complaining about.

**Comment by iperov** [comment] 2019-03-27 20:50
I already told enough information. If you dont know something - just leave this thread.

**Comment by iperov** [comment] 2019-03-27 20:56
photo wct uses `v` values to reconstruct features. But if these values is different, result also different, because `v` values used in matrix multiplications.

```
c_u, c_e, c_v = torch.svd(contentConv, some=False)
s_u, s_e, s_v = torch.svd(styleConv, some=False)

step1 = torch.mm(c_v[:, 0:k_c], torch.diag(c_d))
step2 = torch.mm(step1, (c_v[:, 0:k_c].t()))
whiten_cF = torch.mm(step2, cont_feat)

s_d = (s_e[0:k_s]).pow(0.5)
targetFeature = torch.mm(torch.mm(torch.mm(s_v[:, 0:k_s], torch.diag(s_d)), (s_v[:, 0:k_s].t())), whiten_cF)
```

**Comment by iperov** [comment] 2019-03-27 20:57
`( numpy.svd == scipy.svd == tf.svd ) != torch.svd`

and this is awful :(

**Comment by SsnL** [comment] 2019-03-27 21:01
I am pretty familiar with the gesvd/gesdd bindings in pytorch, and I don't think you ever told any useful information about the issue you see, i.e., was the matrix singular? if so, how ill-conditioned it is? what are the outputs for np, tf, pytorch and other libraries? And, most importantly, are you using the singular vectors of the null space or not?

And you insisted that the two repos you are referring to use the singular vectors of zero singular values are used. I just pointed out that those are not used. E.g., in your snippet from NVIDIA WCT, `k_c` and `k_s` are the ranks. Hence, those vectors are not used, contrary to what you claimed.

**Comment by zawlin** [comment] 2019-03-28 20:14
Hi,
      I run into a problem with svd in torch and found this thread. Here's some 'proof' if you will.

    R=[[ 0.41727819, -0.87345426,  0.25091147],
           [ 0.32246181,  0.40043949,  0.85771009],
           [-0.84964539, -0.27699435,  0.44875031]]
    Rnp = np.array(R)
    Rt = torch.from_numpy(Rnp)

    # numpy
    U,S,V=np.linalg.svd(np.array(R))
    np.matmul(U,V) # gets back R as expected

    # torch
    U,S,V=torch.svd(Rt)
    torch.matmul(U,V) # did not gets back R, and that's causing me headache...:(

**Comment by SsnL** [comment] 2019-03-28 20:19
@zawlin Hi, `np` returns `V^H` but `pytorch` returns `V`, so you are missing the transpose on V!

```

In [1]: import torch

In [2]: import numpy as np

In [3]: R=[[ 0.41727819, -0.87345426,  0.25091147],
   ...:        [ 0.32246181,  0.40043949,  0.85771009],
   ...:        [-0.84964539, -0.27699435,  0.44875031]]
   ...: Rnp = np.array(R)
   ...: Rt = torch.from_numpy(Rnp)
   ...:

In [4]:

In [4]: U,S,V=np.linalg.svd(np.array(R))

In [5]: S
Out[5]: array([1., 1., 1.])

In [6]: Rt.svd().S
Out[6]: tensor([1.0000, 1.0000, 1.0000], dtype=torch.float64)

In [7]:
   ...: # numpy
   ...: U,S,V=np.linalg.svd(np.array(R))
   ...: np.matmul(U,V) # gets back R as expected
Out[7]:
array([[ 0.41727819, -0.87345426,  0.25091147],
       [ 0.32246181,  0.40043949,  0.85771009],
       [-0.84964539, -0.27699435,  0.44875031]])

In [8]: # torch
   ...: U,S,V=torch.svd(Rt)
   ...: torch.matmul(U,V.t()) # did not gets back R, and that's causing me headache...:(
Out[8]:
tensor([[ 0.4173, -0.8735,  0.2509],
        [ 0.3225,  0.4004,  0.8577],
        [-0.8496, -0.2770,  0.4488]], dtype=torch.float64)

In [9]:

```

**Comment by zawlin** [comment] 2019-03-28 20:21
@SsnL , oh ya thanks so much. Apologies for the noise.

**Comment by SsnL** [comment] 2019-03-28 20:23
@zawlin No worries!

**Comment by anbai106** [comment] 2019-12-21 18:40
@SsnL Sorry to ask the same question, which you may have already explained clearly. I'm not quite familiar with SVD, but I do encounter in the similar situation, where I want to convert numpy/scipy.linalg.svd to pytorch, hopefully have exactly the same decomposition. Unluckily, I do need all U, S, V matrices for following code. I'm not saying that this is a bug (Cuz I don't know the technique inside), I just want to ask, there is no workaround to obtain exactly the same results compared to numpy/scipy? If that's the case, I think I will compute SVD using numpy on CPU and converted them back to GPU for pytorch....

**Comment by bensums** [comment] 2020-10-16 12:39
> I am pretty familiar with the gesvd/gesdd bindings in pytorch, and I don't think you ever told any useful information about the issue you see, i.e., was the matrix singular? if so, how ill-conditioned it is? what are the outputs for np, tf, pytorch and other libraries? And, most importantly, are you using the singular vectors of the null space or not?
> 
> And you insisted that the two repos you are referring to use the singular vectors of zero singular values are used. I just pointed out that those are not used. E.g., in your snippet from NVIDIA WCT, `k_c` and `k_s` are the ranks. Hence, those vectors are not used, contrary to what you claimed.

Just a comment here. The rank calculating code in both linked snippets seems incorrect: If there are no singular values > 0.00001 then they default to full rank, rather than zero rank. OTOH if the rank is guaranteed >= 1 then the code would be correct, but then there'd be no need for the default value at all because the if condition in the loop would always be entered and the rank would be set there.
