### ISSUE TITLE
ROCm git checkout failures

### ISSUE THREAD

**Issue by zhouzhuojie** [pytorch/pytorch#65541] opened 2021-09-23 16:31 UTC
https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-build/1469//console

```
16:17:54  * [new ref]               refs/pull/9980/merge  -> origin/pr/9980/merge
16:17:54  * [new ref]               refs/pull/999/head    -> origin/pr/999/head
16:17:54  * [new ref]               refs/pull/9991/head   -> origin/pr/9991/head
16:17:54  * [new ref]               refs/pull/9992/head   -> origin/pr/9992/head
16:17:54  * [new ref]               refs/pull/9992/merge  -> origin/pr/9992/merge
16:17:54  * [new ref]               refs/pull/9994/head   -> origin/pr/9994/head
16:17:54  * [new ref]               refs/pull/9994/merge  -> origin/pr/9994/merge
16:17:54  * [new ref]               refs/pull/9995/head   -> origin/pr/9995/head
16:17:54  * [new ref]               refs/pull/9995/merge  -> origin/pr/9995/merge
16:17:54  * [new ref]               refs/pull/9999/head   -> origin/pr/9999/head
16:17:54  * [new ref]               refs/pull/9999/merge  -> origin/pr/9999/merge
16:17:54 error: some local refs could not be updated; try running
16:17:54  'git remote prune https://github.com/pytorch/pytorch.git' to remove any old, conflicting branches
16:17:54 
16:17:54 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2042)
16:17:54 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:1761)
16:17:54 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$400(CliGitAPIImpl.java:72)
16:17:54 	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:442)
16:17:54 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:153)
16:17:54 	at org.jenkinsci.plugins.gitclient.RemoteGitImpl$CommandInvocationHandler$1.call(RemoteGitImpl.java:146)
16:17:54 	at hudson.remoting.UserRequest.perform(UserRequest.java:210)
16:17:54 	at hudson.remoting.UserRequest.perform(UserRequest.java:53)
16:17:54 	at hudson.remoting.Request$2.run(Request.java:358)
16:17:54 	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
16:17:54 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
16:17:54 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
16:17:54 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport

**Comment by driazati** [comment] 2021-09-23 17:07
interestingly Jenkins isn't reporting these failures to GitHub, recent PRs don't have Jenkins ROCm jobs and https://metrics.pytorch.org/goto/mTONxcHnk?orgId=1 has no data for the past several hours

**Comment by seemethere** [comment] 2021-09-23 17:27
Marking this as high priority since it's affecting signal quality on the HUD

**Comment by malfet** [comment] 2021-09-23 20:13
Likely this was triggered by creating branch called [pr/64052](https://github.com/pytorch/pytorch/tree/pr/64052)

**Comment by jeffdaily** [comment] 2021-09-23 20:15
> Likely this was triggered by creating branch called [pr/64052](https://github.com/pytorch/pytorch/tree/pr/64052)

Can that branch be renamed?

**Comment by malfet** [comment] 2021-09-23 20:39
The problem is mitigated now

**Comment by seemethere** [comment] 2021-09-23 20:42
> Likely this was triggered by creating branch called [pr/64052](https://github.com/pytorch/pytorch/tree/pr/64052?rgh-link-date=2021-09-23T20%3A13%3A28Z) as well as #64052
> @Chillee do you mind deleting/remaining this branch?

Why would this problem manifest itself now when we've had these branches for a bit

**Comment by seemethere** [comment] 2021-09-23 20:42
Removing high priority since initial problem was resolved and HUD is now green

**Comment by malfet** [comment] 2021-09-23 20:43
Branch protection rule created, only one more branch matches the pattern https://github.com/pytorch/pytorch/tree/pr/improve-custom-function-docs

**Closed** 2021-09-23 22:05 UTC
Labels: module: rocm, triaged

**Comment by zhouzhuojie** [comment] 2021-09-24 22:05
btw, adding `ci: sev` label back. We don't need to remove the label (closing the issue just works), so that we have a log to track SEV issues.
