### ISSUE TITLE
compiling error #3628 reappear

### ISSUE THREAD

**Issue by xqding** [pytorch/pytorch#4122] opened 2017-12-11 19:45 UTC
I'm trying to compile from source with gcc 4.8.5 and the following error occurs. It is the same as the error reported in #3628.
pytorch/torch/lib/build/aten/src/ATen/ATen/CPUCharTensor.cpp:69:64: error: expected ‘)’ before ‘PRId64’
   AT_ASSERT(numel == 1,"localScalar() called on Tensor with %" PRId64 " elements",numel);

It should have been fixed by #3629.

**Comment by zou3519** [comment] 2017-12-12 17:42
Could you please send a gist of the contents of your pytorch/torch/lib/build/aten/src/ATen/ATen/CPUCharTensor.cpp ?

**Comment by xqding** [comment] 2017-12-12 17:46
This is the top part of the file pytorch/torch/lib/build/aten/src/ATen/ATen/CPUCharTensor.cpp

```
#include "ATen/CPUCharTensor.h"
#include "ATen/CPUCharStorage.h"
#include "ATen/Scalar.h"
#include "ATen/Half.h"

// required for old g++ to compile PRId64 macros, see
// https://github.com/pytorch/pytorch/issues/3571
// for context
#define __STDC_FORMAT_MACROS

namespace at {

CPUCharTensor::CPUCharTensor(Context* context)
: CPUCharTensor(context,THCharTensor_new()) {}

CPUCharTensor::CPUCharTensor(Context* context, THCharTensor * tensor)
: TensorImpl(&context->getType(Backend::CPU,ScalarType::Char)),
  tensor(tensor),
  context(context) {}
CPUCharTensor::~CPUCharTensor() {
  THCharTensor_free( tensor);
}
...
```

**Comment by zou3519** [comment] 2017-12-12 20:38
I don't know what the problem is, but here are some suggestions/questions that may or may not be useful:

1. Have you tried `python setup.py clean && python setup.py build install`?
2. Could you please give information about the following:
- your OS
- python version
- How you installed python (ie, is it through conda?)

**Comment by calledbymountains** [comment] 2017-12-13 13:38
I concur that this problem has resurfaced in exactly the same way as described by @xqding  in the latest master

**Comment by zou3519** [comment] 2017-12-13 15:37
@calledbymountains could you please provide your OS, python version, and how you installed python? I'm unable to repro on my machine with gcc 4.8.5

**Comment by xqding** [comment] 2017-12-13 17:49
@zou3519 OS: CentOS release 6.9. Python version: 3.5.4. The python is installed using anaconda. Let me know if you need anything else.

**Comment by calledbymountains** [comment] 2017-12-14 15:16
I have exactly the same configuration as @xqding

**Comment by danielamassiceti** [comment] 2017-12-14 17:24
Same with me. I have CentOS release 6.6. Python version 3.6.0 and with conda. Got the pytorch master branch (commit 4f4e0df)

**Comment by rolloff** [comment] 2017-12-15 01:45
so if you see https://stackoverflow.com/questions/14535556/why-doesnt-priu64-work-in-this-code
it says that macro needs to be on top


but in this change https://github.com/pytorch/pytorch/commit/157f949cefb9b15d01160d2becb16c6572023536#diff-baf775c2b5e450a4cb312e908f6a5db7

they added the macro in the middle

**Comment by calledbymountains** [comment] 2017-12-18 11:11
@rolloff provided the correct solution. It works for me.

**Comment by soumith** [comment] 2017-12-18 14:32
fixed via https://github.com/pytorch/pytorch/commit/3b641dc80521bf78da9cbd2a0334cd321d336b08
Thanks for the reports

**Closed by soumith** 2017-12-18 14:32 UTC
Labels: build
