### ISSUE TITLE
Could not find a version that satisfies the requirement torch==0.4.1.post2

### ISSUE THREAD

**Issue by neverfox** [pytorch/pytorch#10443] opened 2018-08-11 22:38 UTC
## Issue description

In a fresh pipenv virtualenv (using Python 3.7 via pyenv), running `pipenv install torch torchvision` results in a successful install of 0.4.1 but also produces the following error:

```
Collecting torch==0.4.1.post2 ▉▉▉▉▉▉▉ 0/1 — 00:00:00

  Could not find a version that satisfies the requirement torch==0.4.1.post2 (from -r /var/folders/h3/59qfw93n6k92mh9lqzvpb1480000gn/T/pipenv-36_h8mxg-requirements/pipenv-wg1__hmp-requirement.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.4.1)
No matching distribution found for torch==0.4.1.post2 (from -r /var/folders/h3/59qfw93n6k92mh9lqzvpb1480000gn/T/pipenv-36_h8mxg-requirements/pipenv-wg1__hmp-requirement.txt (line 1))
```

## System Info
```
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.6
GCC version: Could not collect
CMake version: version 3.12.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

**Comment by adamshamsudeen** [comment] 2018-08-12 12:13
Try pipenv install torch==0.4.1, which is the latest stable

**Comment by neverfox** [comment] 2018-08-12 16:08
@adamshamsudeen Yes, that solves the immediate problem, but it still seems like a general issue given that the documented way to install the library is simply to reference the package name, so that should "just work" and install the latest stable, wouldn't you agree?

**Comment by soumith** [comment] 2018-08-14 04:08
I reproduced this, and it seems to actually be an issue in the way the resolver behaves in `pipenv`. 

See https://github.com/pypa/pipenv/issues/1988 and https://github.com/pypa/pipenv/issues/2490#issuecomment-401860216 outlines that it's a current constraint with `pipenv`, i.e. providing a `.post1` for only some platforms will screw with it's resolver.

They mentioned that new resolver logic is already underway.
It should also be fixed with the next PyTorch version.

**Closed** 2018-08-14 04:08 UTC

**Comment by huangbiubiu** [comment] 2019-05-05 14:26
`conda` is also a solution:

```
conda install -y pytorch=0.4.1
```

**Comment by frankcarey** [comment] 2019-06-28 03:54
@soumith this is happening again FYI.. seems to happen whenever the extra `.post`  releases happen. Is there a reason for these "post" releases instead of a new patch release?

**Comment by zamai** [comment] 2019-06-28 12:15
Same here, just end up in this issue after failing to install  `torch==1.1.0.post2`

**Comment by soumith** [comment] 2019-06-29 04:39
oh. I hoped it was fixed by now :-/

> Is there a reason for these "post" releases instead of a new patch release?

Yes, because we didn't add any new commits, we just fixed binary building.

**Comment by vamsitharun** [comment] 2019-07-04 10:45
if install below command
pip install torch==0.4.1
This is the error i am getting

ERROR: Could not find a version that satisfies the requirement torch<0.5.0,>=0.4.1 (from allennlp==0.7.0->-r requirements.txt (line 2)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch<0.5.0,>=0.4.1 (from allennlp==0.7.0->-r requirements.txt (line 2))

**Comment by RomainSabathe** [comment] 2019-07-08 08:49
Facing the same issue. Temporary solved it the way @adamshamsudeen suggested: `pipenv install torch==1.1.0`

**Comment by knowlsie** [comment] 2019-07-08 20:15
I think I'm getting the same issue with the pip resolver (on Windows), but let me know if this is unrelated, or if I'm confused. `pip install torch==1.1.0` gives the error:
```
Collecting torch==1.1.0
  ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.1.0
```

This is making installing/updating dev environments a real hassle, particularly for stuff with pip-specified torch requirements. I'd love a fix that doesn't involve conda workarounds...

**Comment by spott** [comment] 2019-07-09 20:34
@soumith: It looks like this problem in pipenv is a "won't fix"... which is pretty annoying.

Are the `.postX` releases usually just for different architectures (like the problem in https://github.com/pypa/pipenv/issues/1988), or is it something else.  If they are for different architectures, could pytorch release a new `.post` release for *all* architectures when it fixes one?  I imagine this wouldn't be ideal... but I'm not sure how else to avoid this problem.

**Comment by vamsitharun** [comment] 2019-07-11 07:02
Solution:
conda install pytorch=0.4.1 -c pytorch

Try this, It worked for me

**Comment by shantanuneema** [comment] 2019-07-13 16:11
Thanks vamsitharun, this is what i was looking for

**Comment by OscarVanL** [comment] 2019-08-27 13:05
I had this issue today.

**Comment by SahithiParsi** [comment] 2019-08-28 10:44
> pipenv install torch==0.4.1

tried this issue but got this  error

(virenv) C:\Users\sahithi\Desktop\ner\BERT-NER>pipenv install torch==0.4.1
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing torch==0.4.1…
Adding torch to Pipfile's [packages]…
Installation Succeeded
Installing dependencies from Pipfile.lock (ba0f9a)…
An error occurred while installing torch==0.4.1 --hash=sha256:108aef4c2744724d19d76c2344108db6abb60e86cfc9e06eb3d46386ea3b6097 --hash=sha256:2acd73723a0f0bd0b8114531e78b7ad3c753a2f2c0047623043cba4dae08ae90 --hash=sha256:400f50a9551c5ed2fbea9bd199e14e2ec79964dd792053802b51269eec96320b --hash=sha256:4bf7ffe72bf1af8305b6a3acbe246351f4e09a1c4d4de2364066064da56c869b --hash=sha256:725ae85be70a569583863c263e281938b21e5e92d9a8f480094555b59a82936d --hash=sha256:762eeb0ef4c6de1d9bf12616f362d979cabf1c2b988d5a90bb074adcdc30a079 --hash=sha256:7e3bac584473688720e26323bf209b97c015fc4e9a12a34962df3ff7ad0ce597 --hash=sha256:db668180b11144579d503041339025cc76a70bc0da877f2f91f386fe9229e292 --hash=sha256:e740fb4442ab0cf6a5e5c5279b6ad3cebdeb8f30ce1dabb293cf437178f12a78! Will try again.
  ================================ 1/1 - 00:00:02
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting torch==0.4.1 (from -r C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pipenv-r1wamorj-requirements\\pipenv-88xg7w6t-requirement.txt (line 1))']
[pipenv.exceptions.InstallError]: ['Could not find a version that satisfies the requirement torch==0.4.1 (from -r C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pipenv-r1wamorj-requirements\\pipenv-88xg7w6t-requirement.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)', 'No matching distribution found for torch==0.4.1 (from -r C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pipenv-r1wamorj-requirements\\pipenv-88xg7w6t-requirement.txt (line 1))']
ERROR: ERROR: Package installation failed...
     ================================ 0/1 - 00:00:02

**Comment by SahithiParsi** [comment] 2019-08-28 10:52
> with pipenv install torch==0.4.1, 

@adamshamsudeen 
 i am still facing the same issue. Please suggest a work around. 

'No matching distribution found for torch==0.4.1 (from -r C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pipenv-r1wamorj-requirements\\pipenv-88xg7w6t-requirement.txt (line 1))']
ERROR: ERROR: Package installation failed...

Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
Installing torch==0.4.1…
Adding torch to Pipfile's [packages]…
Installation Succeeded
Installing dependencies from Pipfile.lock (ba0f9a)…
An error occurred while installing torch==0.4.1 --hash=sha256:108aef4c2744724d19d76c2344108db6abb60e86cfc9e06eb3d46386ea3b6097 --hash=sha256:2acd73723a0f0bd0b8114531e78b7ad3c753a2f2c0047623043cba4dae08ae90 --hash=sha256:400f50a9551c5ed2fbea9bd199e14e2ec79964dd792053802b51269eec96320b --hash=sha256:4bf7ffe72bf1af8305b6a3acbe246351f4e09a1c4d4de2364066064da56c869b --hash=sha256:725ae85be70a569583863c263e281938b21e5e92d9a8f480094555b59a82936d --hash=sha256:762eeb0ef4c6de1d9bf12616f362d979cabf1c2b988d5a90bb074adcdc30a079 --hash=sha256:7e3bac584473688720e26323bf209b97c015fc4e9a12a34962df3ff7ad0ce597 --hash=sha256:db668180b11144579d503041339025cc76a70bc0da877f2f91f386fe9229e292 --hash=sha256:e740fb4442ab0cf6a5e5c5279b6ad3cebdeb8f30ce1dabb293cf437178f12a78! Will try again.
  ================================ 1/1 - 00:00:02
Installing initially failed dependencies…
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 1992, in do_install
[pipenv.exceptions.InstallError]:       skip_lock=skip_lock,
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 1253, in do_init
[pipenv.exceptions.InstallError]:       pypi_mirror=pypi_mirror,
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 859, in do_install_dependencies
[pipenv.exceptions.InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 763, in batch_install
[pipenv.exceptions.InstallError]:       _cleanup_procs(procs, not blocking, failed_deps_queue, retry=retry)
[pipenv.exceptions.InstallError]:   File "c:\users\sahithi\desktop\ner\bert-ner\virenv\lib\site-packages\pipenv\core.py", line 681, in _cleanup_procs
[pipenv.exceptions.InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: ['Collecting torch==0.4.1 (from -r C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pipenv-r1wamorj-requirements\\pipenv-88xg7w6t-requirement.txt (line 1))']
[pipenv.exceptions.InstallError]: ['Could not find a version that satisfies the requirement torch==0.4.1 (from -r C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pipenv-r1wamorj-requirements\\pipenv-88xg7w6t-requirement.txt (line 1)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)', 'No matching distribution found for torch==0.4.1 (from -r C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pipenv-r1wamorj-requirements\\pipenv-88xg7w6t-requirement.txt (line 1))']
ERROR: ERROR: Package installation failed...
     ================================ 0/1 - 00:00:02

**Comment by deleamefo** [comment] 2019-09-26 01:36
This worked for me 'conda install pytorch torchvision cudatoolkit=10.0 -c pytorch' 
I guess the installation command has changed.  
check this out https://pytorch.org/

**Comment by ibrahimishag** [comment] 2019-10-11 02:29
I got the same issue. However, luckily, **vamsitharun's** trick worked for me.

**Comment by ibrahimishag** [comment] 2019-10-11 02:31
> Solution:
> `conda install pytorch=0.4.1 -c pytorch`
> 
> Try this, It worked for me
I got the same issue. However, luckily, **vamsitharun's** trick worked for me.

**Comment by vinodyk** [comment] 2020-01-21 21:22
other option is to download the whl file and install. here is the link [http://download.pytorch.org/whl/cu92/torch-0.4.1-cp27-cp27mu-linux_x86_64.whl]

**Comment by zerocool95** [comment] 2020-01-23 12:28
This worked for me : 
# for OS: Windows, package: pip, Language: python3.6 (below command is valid for only mentioned python 3.6)

pip3 install https://download.pytorch.org/whl/cu90/torch-1.1.0-cp36-cp36m-win_amd64.whl
pip3 install https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp36-cp36m-win_amd64.whl

**Comment by swebalaji** [comment] 2020-01-28 10:03
One can Login in to to find the required version:
https://pytorch.org/get-started/locally/

**Comment by GillHawk** [comment] 2020-03-28 00:23
Thanks zerocool95,
I succeeded also to install it on Windows 10 and python3.7:
pip install https://download.pytorch.org/whl/cu90/torch-1.1.0-cp37-cp37m-win_amd64.whl
pip install https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp37-cp37m-win_amd64.whl

**Comment by gorpo** [comment] 2020-04-30 14:43
> 
> 
> Thanks zerocool95,
> I succeeded also to install it on Windows 10 and python3.7:
> pip install https://download.pytorch.org/whl/cu90/torch-1.1.0-cp37-cp37m-win_amd64.whl
> pip install https://download.pytorch.org/whl/cu90/torchvision-0.3.0-cp37-cp37m-win_amd64.whl

thanks bro, this solve my problem in windows10

**Comment by GuntaButya** [comment] 2020-05-06 09:21
An aweful problem for sure! Someone is going to get a smack on the hand!

# CUDA 9.0
conda install pytorch==1.0.1 torchvision==0.2.2 cudatoolkit=9.0 -c pytorch

# CUDA 10.0
conda install pytorch==1.0.1 torchvision==0.2.2 cudatoolkit=10.0 -c pytorch

# CPU Only
conda install pytorch-cpu==1.0.1 torchvision-cpu==0.2.2 cpuonly -c pytorch

**Comment by prh-t** [comment] 2020-05-23 12:29
For future viewers, this worked for me: 
1. Go to [PyTorch website](https://pytorch.org)
2. Get Started -> Start locally 
3. select the PyTorch version you want (e.g. Stable 1.5), select your OS, Package manager (e.g. conda, pip), select language (e.g. Python, Java), and your CUDA version if any
4. then the site will generate a command for you to run "Run this command", e.g. 
`pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`

NOTE: the command above didn't work for me due to some network error, so I went into the site and downloaded the whl packages I wanted, and installed them using `pip install xxx.whl`, happy days

**Comment by ronak34** [comment] 2020-05-24 14:45
> Solution:
> `conda install pytorch=0.4.1 -c pytorch`
> 
> Try this, It worked for me

Thanks. This worked for me.

**Comment by sohansputhran** [comment] 2020-06-01 18:20
> For future viewers, this worked for me:
> 
> 1. Go to [PyTorch website](https://pytorch.org)
> 2. Get Started -> Start locally
> 3. select the PyTorch version you want (e.g. Stable 1.5), select your OS, Package manager (e.g. conda, pip), select language (e.g. Python, Java), and your CUDA version if any
> 4. then the site will generate a command for you to run "Run this command", e.g.
>    `pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> NOTE: the command above didn't work for me due to some network error, so I went into the site and downloaded the whl packages I wanted, and installed them using `pip install xxx.whl`, happy days

Worked for me.
Thank you.

**Comment by BallerDavid** [comment] 2020-06-08 03:12
> For future viewers, this worked for me:
> 
> 1. Go to [PyTorch website](https://pytorch.org)
> 2. Get Started -> Start locally
> 3. select the PyTorch version you want (e.g. Stable 1.5), select your OS, Package manager (e.g. conda, pip), select language (e.g. Python, Java), and your CUDA version if any
> 4. then the site will generate a command for you to run "Run this command", e.g.
>    `pip install torch==1.5.0+cu101 torchvision==0.6.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html`
> 
> NOTE: the command above didn't work for me due to some network error, so I went into the site and downloaded the whl packages I wanted, and installed them using `pip install xxx.whl`, happy days

This helped a lot!

**Comment by proy0111** [comment] 2020-08-19 16:49
pip install torch===1.6.0 torchvision===0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by Oldes** [comment] 2020-10-15 14:49
@proy0111 I'm getting this:
```
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.6.0
```
I have `Python 3.9.0`.

**Comment by viraj123456789** [comment] 2020-10-16 17:27
ERROR: Could not find a version that satisfies the requirement torch===1.6.0 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.6.0

**Comment by Oldes** [comment] 2020-10-16 17:33
@viraj123456789 you must use Python 3.8, not 3.9!

**Comment by Oldes** [comment] 2020-10-16 17:38
Also as https://download.pytorch.org/whl/cu102/torch-1.6.0-cp38-cp38-win_amd64.whl is over 1GB and `pip` which I was using had problems with downloading it.. better is to download the file from browser (where one can do resume) and than install using:
```
pip install c:\path-to-downloads\torch-1.6.0-cp38-cp38-win_amd64.whl
```

**Comment by alanakbik** [comment] 2020-11-09 13:41
Hi all, we recently had some students that encountered this problem (and a related numpy error). And this seems to be a somewhat frequent torch issue (see [here](https://github.com/pytorch/pytorch/issues/35873), [here](https://github.com/pytorch/pytorch/issues/47444) and [here](https://github.com/pytorch/pytorch/issues/2731)). 

We were able to solve it in the following way: 

First, check that your Python is 64-bit and >=3.6 but <3.9. Set up correct Python if not and retry. 

If you have the correct Python but still see this error, try the following: 

1. a) First install torch like so: `pip install torch===1.7.0 -f https://download.pytorch.org/whl/torch_stable.html`. 
b) Then install Flair: `pip install flair`

If that doesn't work or throws GPU/numpy errors, do the following: 

2. a) Install torch like so: `pip install torch==1.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html` 
b) Then reinstall numpy like this: `pip install numpy==1.19.3`
c) Then install Flair: `pip install flair`

The second option was necessary for some students with windows and AMD cards.

**Comment by DarkCharade** [comment] 2021-02-19 00:32
Ty this `conda install -c pytorch torchvision`
https://anaconda.org/pytorch/torchvision

**Comment by SilenceMonk** [comment] 2022-09-03 15:43
maybe try to install it directly from whls?
```
pip install https://download.pytorch.org/whl/cu92/torch-1.2.0%2Bcu92-cp27-cp27m-manylinux1_x86_64.whl
```
all torch related packages are on
<https://download.pytorch.org/whl/torch_stable.html>

**Comment by SilenceMonk** [comment] 2022-09-04 15:56
maybe try to install it directly from whls
```
pip install https://download.pytorch.org/whl/cu92/torch-0.4.1.post2-cp37-cp37m-linux_x86_64.whl
```
[pytorch whls](https://download.pytorch.org/whl/torch_stable.html)
