### ISSUE TITLE
MaxPool1d wrecks Python kernel

### ISSUE THREAD

**Issue by OverLordGoldDragon** [pytorch/pytorch#47897] opened 2020-11-13 05:42 UTC
```python
import torch
import numpy as np

x = np.ones(200000) * (1 + 1j)
x_t = torch.tensor([[x]])
vec = torch.nn.MaxPool1d(100)(x_t.real)  # <-- fails here
```
This forces the Python kernel to crash and restart (reproduced in Spyder, JupyterLab, and terminal console); below, however, avert it:

 - Use `x.real` (or drop `+ 1j`)
 - Use `100000` instead of `200000`
 - Use `AvgPool1d`

Win10 x64, torch 1.7.0.

**Comment by xwang233** [comment] 2020-11-13 06:14
Might be a duplicate of https://github.com/pytorch/pytorch/issues/47054. MaxPool1d for non-contiguous tensor

**Closed** 2020-11-13 06:26 UTC
