### ISSUE TITLE
Operation incorrect output on GPU with PyTorch 1.8.1 and CUDA 11.1

### ISSUE THREAD

**Issue by e-sha** [pytorch/pytorch#57919] opened 2021-05-09 07:59 UTC
## 🐛 Bug

I use a simple network with a few linear layers. After a while I realized that the output of the first linear operation significantly depends on a type of used device ('cpu' vs 'cuda:0'). The expected output of the network is `[[-0.00885119]]`. But by changing device from 'cpu' to 'cuda:0' it becomes incorrect.

## To Reproduce

Simplest example to reproduce the behaviour:
1. Set up environment.
2. Run the script
```
import torch
import torch.nn as nn


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.l = nn.Linear(1, 1, bias=False)

    def forward(self, x):
        return self.l(x)


x = torch.ones((1, 1), dtype=torch.float32, device='cuda:0')
n = Net()
n.to('cuda:0')
print(n.state_dict())
with torch.no_grad():
    print(f'x = {x}, n(x) = {n(x)}')
n.to('cpu')
x = x.to('cpu')
print(n.state_dict())
with torch.no_grad():
    print(f'x = {x}, n(x) = {n(x)}')
```
Incorrect output that depicts difference for CPU and GPU devices:
```
OrderedDict([('l.weight', tensor([[0.2164]], device='cuda:0'))])
x = tensor([[1.]], device='cuda:0'), n(x) = tensor([[1.]], device='cuda:0')
OrderedDict([('l.weight', tensor([[0.2164]]))])
x = tensor([[1.]]), n(x) = tensor([[0.2164]])
```

1. Download the state fiel ([state.pth](https://drive.google.com/file/d/11L4oOO15TGQtwxZlZZNJFNF5kQW06A0j/view?usp=sharing))
1. Download the script from the issue.
1. Place them in the same folder
1. Set up the environment.
1. To get results on CPU run `python3 test.py --cpu`
1. To get results on GPU run `python3 test.py` 

```
import sys
import torch
import torch.nn as nn
import torch.nn.functional as F


class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.l0 = torch.nn.Linear(1, 30)
        self.l1 = torch.nn.Linear(30, 30)
        self.l2 = torch.nn.Linear(30, 1)

    def forward(self, x):
        print(x)
        x = F.relu(self.l0(x))
        print(x.view(-1).detach().cpu().numpy())
        x = F.relu(self.l1(x))
        print(x.view(-1).detach().cpu().numpy())
        x = self.l2(x)
        return x


if len(sys.argv) == 2 and sys.argv[1] == '--cpu':
    device = torch.device('cpu')
else:
    device = torch.device('cuda:0')

x = torch.ones([1, 1], dtype=torch.float32, device=device)

net = Net()
net.to(device)
net.load_state_dict(torch.load('state.pth', map_location=device))
with torch.no_grad():
    print(net(x).detach().cpu().numpy())

print({x: (y.max(), y.min()) for x, y in torch.load('state.pth', map_location='cpu').items()})
```

```
[10:33]~e-shalnov@e-shalnov-LIN:/tmp/1
python3 test.py 
tensor([[1.]], device='cuda:0')
[1.0726611e-03 5.5202913e-01 1.5320663e-01 0.0000000e+00 0.0000000e+00
 5.6659973e-01 2.8236285e-01 2.3436506e-01 6.7830633e-04 2.0812368e-01
 4.9936420e-01 0.0000000e+00 0.0000000e+00 2.7211350e-01 5.2923858e-03
 7.4736190e-01 0.0000000e+00 8.4141898e-01 0.0000000e+00 0.0000000e+00
 1.7436597e-01 0.0000000e+00 6.1321592e-01 1.4492695e-01 5.4469204e-01
 2.5996617e-03 5.9354883e-01 7.0698398e-01 0.0000000e+00 0.0000000e+00]
[0.         0.         0.         0.         0.         0.0797898
 0.         0.         0.         0.         0.36961123 0.6230774
 0.         0.10555211 0.59989965 0.         0.         0.
 0.8408997  0.         0.12672617 0.         0.         0.
 0.07867836 0.10410588 1.3034474  0.24006191 0.         0.5241062 ]
[[1.6439655]]
{'l0.weight': (tensor(1.3446), tensor(-1.8821)), 'l0.bias': (tensor(0.8414), tensor(-0.9363)), 'l1.weight': (tensor(1.6522), tensor(-1.1596)), 'l1.bias': (tensor(0.1560), tensor(-0.2284)), 'l2.weight': (tensor(0.9456), tensor(-0.3593)), 'l2.bias': (tensor(0.1332), tensor(0.1332))}
[10:37]~e-shalnov@e-shalnov-LIN:/tmp/1
python3 test.py --cpu
tensor([[1.]])
[1.32288    0.5132556  0.22237024 0.         0.         0.9266
 0.5103035  0.         1.1487343  0.4192577  0.8864711  0.
 0.         1.616749   0.         1.0684857  0.         0.047387
 0.99704236 0.8128693  0.603879   0.         1.1556516  0.
 0.9853891  0.         0.76424295 1.0838411  0.         0.        ]
[0.         0.         0.         0.         0.         0.3432532
 0.         0.         0.         0.         0.19419211 0.
 0.         0.08450146 0.56923693 0.53331405 0.         0.
 0.         0.         0.3731063  0.         0.         0.
 0.7474418  0.0455278  0.5378541  0.00176995 0.         0.4980051 ]
[[-0.00885119]]
{'l0.weight': (tensor(1.3446), tensor(-1.8821)), 'l0.bias': (tensor(0.8414), tensor(-0.9363)), 'l1.weight': (tensor(1.6522), tensor(-1.1596)), 'l1.bias': (tensor(0.1560), tensor(-0.2284)), 'l2.weight': (tensor(0.9456), tensor(-0.3593)), 'l2.bias': (tensor(0.1332), tensor(0.1332))}
```

## Expected behavior

The output of the network should not change with change of the device. The results on 'cpu' are correct.

## Environment

PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti with Max-Q Design
Nvidia driver version: 455.23.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.8.1+cu111
[pip3] torch-scatter==2.0.6
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
[conda] Could not collect

**Comment by ngimel** [comment] 2021-05-10 03:57
Duplicate of #56747, workaround is to either use conda package or cuda 10 pip wheel.

**Comment by bdhirsh** [comment] 2021-05-10 15:18
closing since this looks like a duplicate of the above linked issue

**Closed by bdhirsh** 2021-05-10 15:18 UTC
