### ISSUE TITLE
Disabled Tests Disable TestSuite instead of enumerating Each Individual Test

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#92555] opened 2023-01-18 17:47 UTC
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/issues/92517 is one of about 50 tests and issues in its test suite that is failing. There is a lot of visual noise in all of the replicated issues. It would be great if there could be one issue for the entire TestSuite instead of for each test.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment] 2023-01-20 01:46
I would separate into two problems:
- disable by wildcard
- automatically group failures 

Negative side of that behavior is that one can accidentally disable much more than intended...

**Comment by ZainRizvi** [comment] 2023-01-20 16:32
It would be risky for a bot to automatically ignore an entire test suite since it might be overzealous 

While I'd be open to letting humans disable tests by wildcard, that wouldn't solve your problem of a bot creating 50+ issues for flaky tests.

How did all those tests get marked as flaky at the same time? cc: @huydhn

**Comment by huydhn** [comment] 2023-01-20 18:06
> How did all those tests get considered flaky at the same time? cc: @huydhn

To give a bit of context here on what happened:

* https://github.com/pytorch/pytorch/issues/92517 disabled a bunch of flaky tests, all with the same cause as explained in the issue (test ordering, first test that ran after the problematic test would fail).  There were probably about 10+ of them created manually by oncall and automatically by flaky bot.  This is annoying but not exactly a flood of disabled tests
* Here come my mistake when trying to reproduce the issue on a runner running a job in trunk.  THIS IS the reason the bot suddenly disabled 50+ more tests.  The XML artifacts I accidentally left there was picked up by flaky bot.  This is a lesson learnt for me and credit to @clee2000 for uncovering this.  This is a fluke caused by my testing, not the bot
* The rootcause PR was reverted, all disabled test were closed

So, here are some of my thoughts on this:

* The problem of disabling 50+ tests is a fluke and it unlikely to happen again
* The bot sill created a bunch of similar tests before the flood, so I agree with @ZainRizvi that letting humans disable tests by wildcard sounds like a good option.

**Comment by ZainRizvi** [comment] 2023-01-20 18:13
Thanks for the context Huy! In that case, let's def not add wildcard support for bots, and to also inclined to not add it for humans until we see a couple more occurrences of humans needing to deliberately disable multiple tests that match a wildcard

At the moment, the law of human error says it's less likely to save toil and more likely to become a foot gun

**Closed** 2023-01-24 17:37 UTC
Labels: feature, module: ci, triaged, module: infra
