### ISSUE TITLE
with torch.device("meta") get Error

### ISSUE THREAD

**Issue by yuys0602** [pytorch/pytorch#97951] opened 2023-03-30 05:59 UTC
### 🐛 Describe the bug

code come from [pytorch tutorials](https://pytorch.org/tutorials/recipes/recipes/reasoning_about_shapes.html)

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(3, 6, 5)
        self.pool = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Conv2d(6, 16, 5)
        self.fc1 = nn.Linear(16 * 5 * 5, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        x = self.pool(F.relu(self.conv1(x)))
        x = self.pool(F.relu(self.conv2(x)))
        x = torch.flatten(x, 1) # flatten all dimensions except batch
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

def fw_hook(module, input, output):
    print(f"Shape of output to {module} is {output.shape}.")


# Any tensor created within this torch.device context manager will be
# on the meta device.
with torch.device("meta"):
    net = Net()
    inp = torch.randn((1024, 3, 32, 32))

for name, layer in net.named_modules():
    layer.register_forward_hook(fw_hook)

out = net(inp)
```

and get the error

```
in <module>
    with torch.device("meta"):
AttributeError: __enter__
```

### Versions

torch==2.0

cc @svekars @carljparker @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by jbschlosser** [comment] 2023-03-30 14:35
Hey @yuys0602, thanks for reporting this! The ability to use `with torch.device("meta")` was added fairly recently in #91796 and may not have made it into the initial 2.0 release. It should work with a master build of PyTorch.

cc @mikaylagawarecki to check on this / add a required version note to the docs

**Comment by mikaylagawarecki** [comment] 2023-03-30 15:23
Hey @yuys0602, thanks for the report. It looks like https://github.com/pytorch/pytorch/pull/91796 did make it into the 2.0 release, I was unable to reproduce this on 2.0.0+cu117. Further the output renders on [the tutorial](https://pytorch.org/tutorials/recipes/recipes/reasoning_about_shapes.html) (which uses 2.0)


Could you provide more information about your environment by running the collect_env script please 

```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

**Comment by yuys0602** [comment] 2023-03-31 17:48
> Hey @yuys0602, thanks for the report. It looks like #91796 did make it into the 2.0 release, I was unable to reproduce this on 2.0.0+cu117. Further the output renders on [the tutorial](https://pytorch.org/tutorials/recipes/recipes/reasoning_about_shapes.html) (which uses 2.0)
> 
> Could you provide more information about your environment by running the collect_env script please
> 
> ```
> wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
> # For security purposes, please check the contents of collect_env.py before running it.
> python collect_env.py
> ```


I'm sorry I mistook the version number of torch, I clicked `[Run in Google Colab]` on the page, and thought the torch here was the latest version, is 2.0, but is 1.13.
I tested version 2.0 on the local side, and there were no errors reported. 

This feature is great, I like it.

**Comment by mikaylagawarecki** [comment] 2023-03-31 18:18
Amazing, glad you like the feature! Closing this issue as complete then :)

**Closed by mikaylagawarecki** 2023-03-31 18:18 UTC
Labels: module: docs, module: nn, triaged
