### ISSUE TITLE
torch.angle is divergent from numpy.angle

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#41240] opened 2020-07-10 10:58 UTC
```
np.angle(-0.31516480719987516)
: 3.141592653589793
```

vs. 

```
torch.angle(torch.tensor(-0.31516480719987516))
: tensor(0.)
```

for example. 

cc @ezyang @anjali411 @dylanbespalko @mruberry @rgommers

**Comment by rgommers** [comment] 2020-07-10 13:55
This looks like a PyTorch bug. `angle` is defined for complex input, but:
```
In [1]: import torch                                                            

In [2]: import numpy as np                                                      

In [3]: x = -0.31516480719987516                                                

In [4]: t = torch.tensor(x, dtype=torch.complex128)                             

In [5]: t                                                                       
Out[5]: tensor(-0.3152+0.j, dtype=torch.complex128)

In [6]: torch.angle(t)                                                          
/home/rgommers/anaconda3/envs/pytorch/bin/ipython:1: UserWarning: Casting complex values to real discards the imaginary part (Triggered internally at  ../aten/src/ATen/native/Copy.cpp:165.)
  #!/home/rgommers/anaconda3/envs/pytorch/bin/python
```

For complex input NumPy's behavior returns a value in `(-pi, pi]`:
```
import numpy as np
import torch
import matplotlib.pyplot as plt


x = np.linspace(0, 2*np.pi, num=500)
z = np.cos(x) + 1.j * np.sin(x)

y1 = np.angle(z)

t = torch.tensor(z)
y2 = torch.angle(t)

fig = plt.figure()
ax = fig.add_subplot(111)
ax.plot(x, y1, label='numpy')
ax.plot(x, y2, label='pytorch')
ax.legend()

plt.show()
```

Behavior seems to roughly agree, but that script still gives the same warning of `Casting complex values to real discards ....` for `torch`.

<img width="529" alt="image" src="https://user-images.githubusercontent.com/98330/87162059-b2109b00-c2c5-11ea-812e-973a17c6e443.png">

**Comment by mruberry** [comment] 2020-07-10 20:33
I think @anjali411 is fixing the warning. I don't see the blue numpy line on that graph, am I missing something?

**Comment by rgommers** [comment] 2020-07-10 20:41
> I don't see the blue numpy line on that graph, am I missing something?

they're overlapping. updated linewidths for clarity

**Comment by mruberry** [comment] 2020-07-10 20:48
> > I don't see the blue numpy line on that graph, am I missing something?
> 
> they're overlapping. updated linewidths for clarity

Ah, thank you, @rgommers, sorry to bother you.

**Comment by rgommers** [comment] 2020-07-10 21:00
no worries

**Comment by anjali411** [comment] 2020-07-13 14:08
> I think @anjali411 is fixing the warning. I don't see the blue numpy line on that graph, am I missing something?

The warning is removed for `angle` and `abs` so it shouldn't show up in the latest build. 

On CPU we just call `std::arg` (for non-vectorization examples):
```
#include <iostream>
#include <complex>
 
int main() 
{
    std::complex<double> z1(1, 0); 
    std::cout << "phase angle of " << z1 << " is " << std::arg(z1) << '\n';
 
    std::complex<double> z2(0, 1); 
    std::cout << "phase angle of " << z2 << " is " << std::arg(z2) << '\n';
 
    std::complex<double> z3(-1, 0); 
    std::cout << "phase angle of " << z3 << " is " << std::arg(z3) << '\n';
 
    std::complex<double> z4(-1, -0.0); 
    std::cout << "phase angle of " << z4 << " (the other side of the cut) is "
              << std::arg(z4) << '\n';
}

Output:
phase angle of (1,0) is 0
phase angle of (0,1) is 1.5708
phase angle of (-1,0) is 3.14159
phase angle of (-1,-0) (the other side of the cut) is -3.14159
```

Also, I checked locally and it seems numpy does the same thing too:

```
>>> np.angle(np.array([-2+0j]))
array([3.14159265])
>>> np.angle(np.array([2+0j]))
array([0.])
```

**Comment by rgommers** [comment] 2020-07-13 20:10
So it looks like there's a tiny discrepancy where pytorch (and `std:arg`) use the closed `[-pi, pi]` interval while numpy uses the half open `(-pi, pi]` interval. I'd say both are valid and it's not worth worrying about. So close this issue?

**Comment by anjali411** [comment] 2020-07-13 20:17
@rgommers yeah agreed!

@mruberry the issue for real tensors is due to this hard coding: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cpu/zmath.h#L37

**Comment by kshitij12345** [comment] 2020-12-23 07:16
https://github.com/pytorch/pytorch/pull/49163 Fixes the previously hardcoded case for real tensors and tests it against NumPy (including behavior with `inf, -inf, nan`).

So the main issue here is resolved.

But one interesting thing as discussed above, is to note that C++ allows `complex<double>(-1, -0)`.
```
phase angle of (-1,-0) (the other side of the cut) is -3.14159
```

The above is not reproducible on NumPy as well as Pytorch as both treat `-0` as `+0`.
```python
>>> t = torch.tensor(-1-0.j)
>>> t
tensor(-1.+0.j)
>>> torch.angle(t)
tensor(3.1416)
>>> a = np.array(-1-0.j)
>>> a
array(-1.+0.j)
>>> np.angle(a)
3.141592653589793
```

**Comment by mruberry** [comment] 2020-12-23 18:39
Thanks for the follow-up, @kshitij12345!

So you would say that torch.angle is now consistent with numpy.angle? If so, let's close this issue.

Would you file a separate issue for the treatment of -0j and +0j? It's interesting that both PyTorch and NumPy treat them as equivalent values, but that C++ distinguishes between them.

**Comment by kshitij12345** [comment] 2020-12-28 09:40
Closing this issue.

Have filed a new issue https://github.com/pytorch/pytorch/issues/49884 for treatment of `+0j` and `-0j` as equivalent values.

**Closed** 2020-12-28 09:40 UTC
Labels: module: complex, module: numpy, triaged
