### ISSUE TITLE
RuntimeError: only Tensors of floating point and complex dtype can require gradients

### ISSUE THREAD

**Issue by nidhisingh14** [pytorch/pytorch#95110] opened 2023-02-18 05:13 UTC
### 🐛 Describe the bug

from tqdm import tqdm
model = cnn
# Define Optimizer and Loss Function
loss_func = nn.NLLLoss()

dtype = torch.float32
model = model.to(dtype)

optimizer = optim.SGD(cnn.parameters(), lr=0.001, momentum=0.9)
# cnn = cnn.to(device)

for epoch in range(1):
    epoch_start = time.time()
    print("Epoch: {}/{}".format(epoch+1, 1))
    
    # Set to training mode
    model.train()
    
    # Loss and Accuracy within the epoch
    train_loss = 0.0
    train_acc = 0.0
    
    valid_loss = 0.0
    valid_acc = 0.0
    
    for i, (inputs, labels) in enumerate(tqdm(train_data_loader)):

        inputs = inputs.to(device)
        labels = labels.to(device)
        
        # Clean existing gradients
        optimizer.zero_grad()
        
        # Forward pass - compute outputs on input data using the model
        outputs = model(inputs)
        ret, predictions = torch.max(outputs.data, 1)
        value_list = []
        for i in outputs[:,:1].cpu().detach().numpy():
          for j in i:
            value_list.append(j)
        # print(value_list)
        outputs = torch.Tensor(value_list)
        outputs.requires_grad = True
        outputs = outputs.to(device)
        # outputs.requires_grad = True
        print(outputs)
        print(f'Labels\n {labels}')
        print(f'predictions\n {predictions}')
        # print(labels)

        # break
        # Compute loss
        # ret, predictions = torch.max(outputs.data, 1)
        # predictions.requires_grad = True
        labels = labels.to(device).float()
        # labels.requires_grad = True
        predictions.requires_grad = True
        loss = loss_func(torch.log(predictions.float()), labels.float())
        
        # Backpropagate the gradients
        loss.backward()
        
        # Update the parameters
        optimizer.step()
        
        # Compute the total loss for the batch and add it to train_loss
        train_loss += loss.item() * inputs.size(0)
        
        # Compute the accuracy
        _, predictions = torch.max(outputs.data, 1)
        correct_counts = predictions.eq(labels.data.view_as(predictions))
        
        # Convert correct_counts to float and then compute the mean
        acc = torch.mean(correct_counts.type(torch.FloatTensor))
        
        # Compute total accuracy in the whole batch and add to train_acc
        train_acc += acc.item() * inputs.size(0)
        
        #print("Batch number: {:03d}, Training: Loss: {:.4f}, Accuracy: {:.4f}".format(i, loss.item(), acc.item()))
    break
    
    # Validation - No gradient tracking needed
    with torch.no_grad():

        # Set to evaluation mode
        model.eval()

        # Validation loop
        for j, (inputs, labels) in enumerate(tqdm(valid_data_loader)):
            inputs = inputs.to(device)
            labels = labels.to(device)

            # Forward pass - compute outputs on input data using the model
            outputs = model(inputs)

            # Compute loss
            loss = loss_func(torch.log(outputs), labels.long())

            # Compute the total loss for the batch and add it to valid_loss
            valid_loss += loss.item() * inputs.size(0)

            # Calculate validation accuracy
            _, predictions = torch.max(outputs.data, 1)
            correct_counts = predictions.eq(labels.data.view_as(predictions))

            # Convert correct_counts to float and then compute the mean
            acc = torch.mean(correct_counts.type(torch.FloatTensor))

            # Compute total accuracy in the whole batch and add to valid_acc
            valid_acc += acc.item() * inputs.size(0)

            #print("Validation Batch number: {:03d}, Validation: Loss: {:.4f}, Accuracy: {:.4f}".format(j, loss.item(), acc.item()))
    if valid_loss < best_loss:
        best_loss = valid_loss
        best_epoch = epoch

    # Find average training loss and training accuracy
    avg_train_loss = train_loss/train_data_size 
    avg_train_acc = train_acc/train_data_size

    # Find average training loss and training accuracy
    avg_valid_loss = valid_loss/valid_data_size 
    avg_valid_acc = valid_acc/valid_data_size

    history.append([avg_train_loss, avg_valid_loss, avg_train_acc, avg_valid_acc])
            
    epoch_end = time.time()

    print("Epoch : {:03d}, Training: Loss - {:.4f}, Accuracy - {:.4f}%, \n\t\tValidation : Loss - {:.4f}, Accuracy - {:.4f}%, Time: {:.4f}s".format(epoch, avg_train_loss, avg_train_acc*100, avg_valid_loss, avg_valid_acc*100, epoch_end-epoch_start))
    
    # Save if the model has best accuracy till now
    torch.save(model, dataset+'_model_'+str(epoch)+'.pt')

RuntimeError: only Tensors of floating point and complex dtype can require gradients

### Versions

Epoch: 1/1
  0%|          | 0/18 [00:05<?, ?it/s]tensor([0.2014, 0.2030, 0.2042, 0.2000, 0.1990, 0.2010, 0.2006, 0.2078, 0.2034,
        0.2055, 0.2055, 0.1979, 0.2038, 0.2064, 0.1986, 0.2053, 0.2024, 0.2004,
        0.2078, 0.2027, 0.2003, 0.2012, 0.2026, 0.2041, 0.2076, 0.1966, 0.1973,
        0.2050, 0.2034, 0.2024, 0.2087, 0.2093], device='cuda:0',
       grad_fn=<ToCopyBackward0>)
Labels
 tensor([2, 0, 5, 2, 0, 3, 2, 5, 1, 4, 1, 2, 1, 1, 2, 1, 2, 4, 3, 0, 4, 4, 3, 2,
        3, 3, 3, 1, 0, 1, 3, 5], device='cuda:0')
predictions
 tensor([4, 0, 4, 3, 2, 4, 4, 0, 4, 0, 4, 4, 0, 0, 4, 4, 4, 3, 4, 4, 4, 4, 4, 0,
        0, 2, 3, 4, 4, 4, 0, 0], device='cuda:0')

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-45-6e8c8d404908>](https://localhost:8080/#) in <module>
     55         labels = labels.to(device).float()
     56         # labels.requires_grad = True
---> 57         predictions.requires_grad = True
     58         loss = loss_func(torch.log(predictions.float()), labels.float())
     59 

RuntimeError: only Tensors of floating point and complex dtype can require gradients

**Comment by ptrblck** [comment] 2023-02-18 07:35
As the error explains, only floating point tensors can require gradients while you are trying to call `.requires-grad = True` on a `LongTensor` created by `torch.max`.
Please use the [Discussion board](https://discuss.pytorch.org/) for these questions.

Closing as the error is expected and not a bug.

**Closed by ptrblck** 2023-02-18 07:35 UTC
