### ISSUE TITLE
[inductor][cpu]hf_Whisper float32 dynamic shape CPP wrapper multiple threads performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#116755] opened 2024-01-04 02:10 UTC
### 🐛 Describe the bug

<p>hf_Whisper float32 dynamic shape CPP wrapper multiple threads in 2023-12-31</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_Whisper</td>
      <td>8</td>
      <td>1.308041</td>
      <td>0.133976362</td>
      <td>0.17524657452684198</td>
      <td>20.006007</td>
      <td>8</td>
      <td>1.499201</td>
      <td>0.118452427</td>
      <td>0.177583997010827</td>
      <td>20.105469</td>
      <td>0.87</td>
      <td>1.01</td>
      <td>0.88</td>
      <td>1.0</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>b419581</td>
      <td>4bfaa6b</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>6518fa9</td>
      <td>#3710</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td>#2167</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>f52fd33</td>
      <td>#8185</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td>#1147</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.3.0a0+git1ed8e26</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.18.0a0+ae6b134</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+6518fa9</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance torchbench hf_Whisper float32 first dynamic cpp

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/e0e90bc0d49928ddbe387d78d126d96be4fb4dd3
[torchbench-hf_Whisper-inference-float32-dynamic-cpp-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13825072/torchbench-hf_Whisper-inference-float32-dynamic-cpp-performance-multiple-drop_guilty_commit.log)
@WeizhuoZhang-intel @chuanqi129

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by leslie-fang-intel** [comment] 2024-01-05 02:55
Looks like the PR has re-landed, @chuanqi129 please help to verify.

**Comment by zxd1997066** [comment] 2024-01-11 06:48
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_Whisper</td>
      <td>8</td>
      <td>1.372223</td>
      <td>0.128445894</td>
      <td>0.176256410002362</td>
      <td>20.044245</td>
    </tr>
    <tr>
  </tbody>

In latest report, seems the performance does not come back

**Comment by leslie-fang-intel** [comment] 2024-01-11 07:20
Check the `hf_Whisper` fp32 cpp_wrapper multi thread testing result with 2023_12_11 (which is before the first landing of https://github.com/pytorch/pytorch/pull/116389), the speed-up is 1.54395x. Looks like this PR's landing didn't bring performance benefits to `hf_Whisper`. It looks strange that reverting this PR will cause the performance regression. @zxd1997066 could we manually confirm the guilty commit for this issue?

**Comment by leslie-fang-intel** [comment] 2024-01-18 07:45
Need to find the guilty commit manually @zxd1997066

**Comment by zxd1997066** [comment] 2024-01-24 15:09
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_Whisper</td>
      <td>8</td>
      <td>1.452245</td>
      <td>0.121488072</td>
      <td>0.17643044512164</td>
      <td>20.528435</td>
    </tr>
    <tr>
  </tbody>

In 2024_01_22 report, seems the performance comes back

**Comment by leslie-fang-intel** [comment] 2024-01-25 01:12
Close this issue as the performance coming back.

**Closed by leslie-fang-intel** 2024-01-25 01:12 UTC
Labels: triaged, oncall: pt2, oncall: cpu inductor
