### ISSUE TITLE
version:branch 0.4.1

### ISSUE THREAD

**Issue by zsk423200** [pytorch/pytorch#10347] opened 2018-08-08 09:45 UTC
i git clone branch0.4.1, 
`git clone --recursive -b v0.4.1 https://github.com/pytorch/pytorch.git`
and install from source, after install, use python print pytorch version, is 
`>>> torch.__version__ `
0.5.0a0+a24163a
and i find version in setup.py, is also 0.5.0a0, but i install from Binaries, print info is 0.4.1.
why??

**Comment by vishwakftw** [comment] 2018-08-08 11:42
Duplicate of https://github.com/pytorch/pytorch/issues/9926 .

**Comment by zou3519** [comment] 2018-08-09 18:38
See @vishwakftw's comment.

**Closed by zou3519** 2018-08-09 18:38 UTC
