### ISSUE TITLE
Trace model, error message improvement `TracedModules don't support parameter sharing between modules`

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#22677] opened 2019-07-10 08:02 UTC
When I try trace a model, I got this error:

```
TracedModules don't support parameter sharing between modules
```

After digging into jit module source codes, this error thrown for the reason that:
```
the module weights already inside a set, but id is different with exists one, then out performs this error
```

however, this message is confusing. I think **it's nothing to do with parameters sharing, instead, it because of 2 modules or more with same weights but not same id**.

I think the best way to indicates users to solve this, at least provide which layer or which modules conflicts with each other since they have same weights but not same id.

If you got same error when tracing a pytorch model. You should think about give my advise a :+1:

**Comment by driazati** [comment] 2019-07-10 18:02
That message could definitely have more info, can you post a repro script that generates the error?

**Comment by wanchaol** [comment] 2019-07-11 00:02
seems like a duplicate of https://github.com/pytorch/pytorch/issues/22680

**Comment by jinfagang** [comment] 2019-07-11 01:47
@wanchaol  Thank you wanchaol for the reference of the link.

There I have a tiny trace example to reveal the error.

**Comment by suo** [comment] 2019-12-16 18:10
Closing as a duplicate.

**Closed by suo** 2019-12-16 18:10 UTC
Labels: jit, module: docs, triaged
