### ISSUE TITLE
`import torch` failed after a clean install of CUDA pytorch 2.5.1

### ISSUE THREAD

**Issue by vadim0x60** [pytorch/pytorch#139875] opened 2024-11-06 10:19 UTC
### 🐛 Describe the bug

I am getting the exact same problem as described in #135867, except I don't need Intel GPU support and I tried to install CUDA pytorch using

```
conda create -n py312 python=3.12 pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia -y
```

Either this command is trying to install XPU support for some reason or issue #135867 is not limited to XPU

### Versions

```
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: AlmaLinux release 8.10 (Cerulean Leopard) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-22)
Clang version: Could not collect
CMake version: version 3.26.5
Libc version: glibc-2.28

Python version: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-4.18.0-553.22.1.el8_10.x86_64-x86_64-with-glibc2.28
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4
GPU 4: Tesla T4

Nvidia driver version: 550.90.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architectuur:         x86_64
CPU-modus(sen):       32-bit, 64-bit
Bytevolgorde:         Little Endian
CPU's:                64
Online CPU's-lijst:   0-63
Draden per kern:      2
Kernen per voet:      16
CPU-voeten:           2
NUMA-nodes:           2
Producent-ID:         GenuineIntel
CPU-familie:          6
Model:                85
Modelnaam:            Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
Stepping:             7
CPU-frequentie (MHz): 2300.000
BogoMIPS:             4600.00
L1d-cache:            32K
L1i-cache:            32K
L2-cache:             1024K
L3-cache:             22528K
NUMA-node0 CPU('s):   0-15,32-47
NUMA-node1 CPU('s):   16-31,48-63
Vlaggen:              fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==2.1.3
[pip3] torch==2.5.1
[pip3] torchaudio==2.5.1
[pip3] torchvision==0.20.1
[pip3] triton==3.1.0
[conda] blas                      2.106                       mkl    conda-forge
[conda] cuda-cudart               12.4.127                      0    nvidia
[conda] cuda-cupti                12.4.127                      0    nvidia
[conda] cuda-libraries            12.4.1                        0    nvidia
[conda] cuda-nvrtc                12.4.127                      0    nvidia
[conda] cuda-nvtx                 12.4.127                      0    nvidia
[conda] cuda-opencl               12.6.77                       0    nvidia
[conda] cuda-runtime              12.4.1                        0    nvidia
[conda] libblas                   3.9.0                     6_mkl    conda-forge
[conda] libcblas                  3.9.0                     6_mkl    conda-forge
[conda] libcublas                 12.4.5.8                      0    nvidia
[conda] libcufft                  11.2.1.3                      0    nvidia
[conda] libcurand                 10.3.7.77                     0    nvidia
[conda] libcusolver               11.6.1.9                      0    nvidia
[conda] libcusparse               12.3.1.170                    0    nvidia
[conda] liblapack                 3.9.0                     6_mkl    conda-forge
[conda] liblapacke                3.9.0                     6_mkl    conda-forge
[conda] libnvjitlink              12.4.127                      0    nvidia
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] numpy                     2.1.3           py312h58c1407_0    conda-forge
[conda] pytorch                   2.5.1           py3.12_cuda12.4_cudnn9.1.0_0    pytorch
[conda] pytorch-cuda              12.4                 hc786d27_7    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.5.1               py312_cu124    pytorch
[conda] torchtriton               3.1.0                     py312    pytorch
[conda] torchvision               0.20.1              py312_cu124    pytorch
```

cc @seemethere @malfet @osalpekar @atalman

**Comment by vadim0x60** [comment] 2024-11-06 16:24
I think I have a hypothesis. I think the root issue is that pytorch expects a newer version of `mkl` than what I have (2020.4), but [conda forge packages for pytorch 2.5.1](https://anaconda.org/pytorch/pytorch/files?version=2.5.1) don't specify a version for `mkl`.

Then anaconda figured that the latest installable version of `mkl` is 2020.4 (due to the lack of compiled `blas-mkl` binaries fresher than 2.106 for my platform) and missed an undeclared dependency conflict. If the version of `mkl` required by `pytorch` was specified, conda would instead just downgrade me to the latest pytorch compatible with `mkl==2020.4`

**Comment by malfet** [comment] 2024-11-06 18:47
@vadim0x60 can you please post an error you are seeing. Also, does it reproduces with wheels or only with conda packages? If later, see https://github.com/pytorch/pytorch/issues/138506

**Comment by seemethere** [comment] 2024-11-06 18:52
This would be weird since we don't even support xpu on anaconda at all. As well, the XPU binaries did not get released to any official channels so it would especially weird if you're seeing the same error here.

**Comment by ptrblck** [comment] 2024-11-06 20:47
FWIW the PyTorch==2.5.1 `conda`binaries with CUDA 12.4 work fine for Python 3.10 (see [this](https://discuss.pytorch.org/t/pytorch-gpu-via-conda-not-working/212586/4?u=ptrblck)) and Python 3.12 (tested just now):
```python
conda create -n py312 python=3.12 pytorch torchvision torchaudio pytorch-cuda=12.4 -c pytorch -c nvidia -y
...
conda activate py312
python -c "import torch; print(torch.__version__); print(torch.version.cuda); print(torch.randn(1).cuda())"
2.5.1                                                                                                                                                                                                                                                                             
12.4                                                                                                                                                                                                                                                                              
tensor([1.1019], device='cuda:0')             
```
so `conda-forge` might indeed cause dependency issues.

Try to install the pip wheels as already recommended.

**Comment by vadim0x60** [comment] 2024-11-07 10:54
> @vadim0x60 can you please post an error you are seeing. Also, does it reproduces with wheels or only with conda packages? If later, see #138506

```
OSError: libmkl_intel_lp64.so.2: cannot open shared object file: No such file or directory
```

I haven't tried wheels, since I'd need to handle system dependencies myself.

**Comment by vadim0x60** [comment] 2024-11-07 10:56
> FWIW the PyTorch==2.5.1 `conda`binaries with CUDA 12.4 work fine for Python 3.10 (see [this](https://discuss.pytorch.org/t/pytorch-gpu-via-conda-not-working/212586/4?u=ptrblck)) and Python 3.12 (tested just now):

What's your version of `mkl`? If it's `2023`, it's consistent with my hypothesis of undeclared `mkl` dependency

**Comment by vadim0x60** [comment] 2024-11-07 14:21
FYI I updated `mkl` and that fixed it for me

**Comment by seemethere** [comment] 2024-11-08 20:19
Going to close this since there is a resolution! Thanks for being responsive @vadim0x60!

**Closed by seemethere** 2024-11-08 20:19 UTC
Labels: needs reproduction, module: binaries, triaged
