### ISSUE TITLE
numel() works differently for torch.Tensor and torch.Size inputs, not documented

### ISSUE THREAD

**Issue by harsanyidani** [pytorch/pytorch#124167] opened 2024-04-16 12:57 UTC
### 📚 The doc issue

`numel()` works differently for `torch.Tensor` and `torch.Size` inputs. This is not mentioned in the [documentation](https://pytorch.org/docs/stable/generated/torch.numel.html).

**Example:**
```
import torch
a = torch.Tensor(3, 4)
print(a.numel(), a.shape.numel())
```
Output:
12
12

As I was reading code I expected shape.numel() to return the number of dimensions, so I was surprised that it works this way. I understand that this is a feature but I think this should be mentioned in the documentation.

### Suggest a potential alternative/fix

It could be mentioned in the documentation if `numel()` is called on a `Size `object it returns the number of items in a that sized `Tensor`.

cc @svekars @brycebortree

**Comment by tringwald** [comment] 2024-04-16 15:42
Duplicate of https://github.com/pytorch/pytorch/issues/61231.

**Closed** 2024-04-16 15:48 UTC
Labels: module: docs, triaged
