### ISSUE TITLE
 y.get_desc().is_nhwc() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by Andrey-847-2** [pytorch/pytorch#81054] opened 2022-07-07 19:34 UTC
### 🐛 Describe the bug

Tried to run audio transcription by speechbrain (https://speechbrain.github.io/) under windows and this code 

            conv_wave = torch.nn.functional.conv1d(
                input=wave_to_conv,
                weight=self.weights[i].repeat(num_channels, 1, 1),
                stride=self.conv_stride,
                groups=num_channels,
            )

after some success iterations raises this error:

    conv_wave = torch.nn.functional.conv1d(
RuntimeError: y.get_desc().is_nhwc() INTERNAL ASSERT FAILED at "C:\\actions-runner\\_work\\pytorch\\pytorch\\builder\\windows\\pytorch\\aten\\src\\ATen\\native\\mkldnn\\Conv.cpp":143, please report a bug to PyTorch. 

So reporting this bug as description said :) 

Is it known issue? how can I workaround it?

### Versions

PyTorch version: 1.12.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home Single Language
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22000-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce MX450
Nvidia driver version: 462.59
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[pip3] torchvision==0.13.0
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by XiaobingSuper** [comment] 2022-07-17 15:16
@Andrey-847-2 , could you try try the new pytorch code? https://github.com/pytorch/pytorch/pull/80864 may fix this issue, thanks!

**Comment by mingfeima** [comment] 2022-07-28 22:25
@XiaobingSuper are we able to reproduce this issue?

**Comment by jingxu10** [comment] 2022-07-28 22:39
yeah, sure.

**Comment by jingxu10** [comment] 2022-10-04 01:17
Could you verify if this error had been fixed in the latest master?

**Comment by mingfeima** [comment] 2022-10-16 23:59
@Andrey-847-2 with https://github.com/pytorch/pytorch/pull/80864 merged, this should been fixed, could you please verify? so that we can close this issue/

**Comment by neverstopZyy** [comment] 2022-11-02 03:33
Hi! I think I reproduce the problem again.
------env---
torch == 1.12.1
numpy == 1.23.2

---- code ----
`
import torch
import torch.nn as nn
from typing import Tuple
import numpy as np
import os
import torch
import torch.nn as nn
import torch.nn.functional as F

def get_gradient(out, point):
    d_output = torch.ones_like(out, requires_grad=False)
    gradient = torch.autograd.grad(
        outputs=out,
        inputs=point,
        grad_outputs=d_output,
        create_graph=True,
        retain_graph=True,
        only_inputs=True,
        allow_unused=True)[0]
    return gradient

# all copyright belong to pytorch geometry
def gaussian(window_size, sigma):
    def gauss_fcn(x):
        return -(x - window_size // 2) ** 2 / float(2 * sigma ** 2)

    gauss = torch.stack(
        [torch.exp(torch.tensor(gauss_fcn(x))) for x in range(window_size)])
    return gauss / gauss.sum()

def get_gaussian_kernel(ksize: int, sigma: float) -> torch.Tensor:
    if not isinstance(ksize, int) or ksize % 2 == 0 or ksize <= 0:
        raise TypeError("ksize must be an odd positive integer. Got {}"
                        .format(ksize))
    window_1d: torch.Tensor = gaussian(ksize, sigma)
    return window_1d


def get_gaussian_kernel2d(ksize: Tuple[int, int],
                          sigma: Tuple[float, float]) -> torch.Tensor:
    if not isinstance(ksize, tuple) or len(ksize) != 2:
        raise TypeError("ksize must be a tuple of length two. Got {}"
                        .format(ksize))
    if not isinstance(sigma, tuple) or len(sigma) != 2:
        raise TypeError("sigma must be a tuple of length two. Got {}"
                        .format(sigma))
    ksize_x, ksize_y = ksize
    sigma_x, sigma_y = sigma
    kernel_x: torch.Tensor = get_gaussian_kernel(ksize_x, sigma_x)
    kernel_y: torch.Tensor = get_gaussian_kernel(ksize_y, sigma_y)
    kernel_2d: torch.Tensor = torch.matmul(
        kernel_x.unsqueeze(-1), kernel_y.unsqueeze(-1).t())
    return kernel_2d
class SSIM(nn.Module):
    def __init__(
            self,
            window_size: int,
            reduction: str = 'none',
            max_val: float = 1.0) -> None:
        super(SSIM, self).__init__()
        self.window_size: int = window_size
        self.max_val: float = max_val
        self.reduction: str = reduction

        self.window: torch.Tensor = get_gaussian_kernel2d(
            (window_size, window_size), (1.5, 1.5))
        self.padding: int = self.compute_zero_padding(window_size)

        self.C1: float = (0.01 * self.max_val) ** 2
        self.C2: float = (0.03 * self.max_val) ** 2

    @staticmethod
    def compute_zero_padding(kernel_size: int) -> int:
        """Computes zero padding."""
        return (kernel_size - 1) // 2

    def filter2D(
            self,
            input: torch.Tensor,
            kernel: torch.Tensor,
            channel: int) -> torch.Tensor:
        return F.conv2d(input, kernel, padding=self.padding, groups=channel)

    def forward(self, img1: torch.Tensor, img2: torch.Tensor) -> torch.Tensor:
        if not torch.is_tensor(img1):
            raise TypeError("Input img1 type is not a torch.Tensor. Got {}"
                            .format(type(img1)))
        if not torch.is_tensor(img2):
            raise TypeError("Input img2 type is not a torch.Tensor. Got {}"
                            .format(type(img2)))
        if not len(img1.shape) == 4:
            raise ValueError("Invalid img1 shape, we expect BxCxHxW. Got: {}"
                             .format(img1.shape))
        if not len(img2.shape) == 4:
            raise ValueError("Invalid img2 shape, we expect BxCxHxW. Got: {}"
                             .format(img2.shape))
        if not img1.shape == img2.shape:
            raise ValueError("img1 and img2 shapes must be the same. Got: {}"
                             .format(img1.shape, img2.shape))
        if not img1.device == img2.device:
            raise ValueError("img1 and img2 must be in the same device. Got: {}"
                             .format(img1.device, img2.device))
        if not img1.dtype == img2.dtype:
            raise ValueError("img1 and img2 must be in the same dtype. Got: {}"
                             .format(img1.dtype, img2.dtype))
        # prepare kernel
        b, c, h, w = img1.shape
        tmp_kernel: torch.Tensor = self.window.to(img1.device).to(img1.dtype)
        kernel: torch.Tensor = tmp_kernel.repeat(c, 1, 1, 1)

        # compute local mean per channel
        mu1: torch.Tensor = self.filter2D(img1, kernel, c)
        mu2: torch.Tensor = self.filter2D(img2, kernel, c)

        mu1_sq = mu1.pow(2)
        mu2_sq = mu2.pow(2)
        mu1_mu2 = mu1 * mu2

        # compute local sigma per channel
        sigma1_sq = self.filter2D(img1 * img1, kernel, c) - mu1_sq
        sigma2_sq = self.filter2D(img2 * img2, kernel, c) - mu2_sq
        sigma12 = self.filter2D(img1 * img2, kernel, c) - mu1_mu2

        ssim_map = ((2 * mu1_mu2 + self.C1) * (2 * sigma12 + self.C2)) / \
                   ((mu1_sq + mu2_sq + self.C1) * (sigma1_sq + sigma2_sq + self.C2))

        loss = ssim_map
        # loss = torch.clamp(1. - ssim_map, min=0, max=1) / 2.

        if self.reduction == 'mean':
            loss = torch.mean(loss)
        elif self.reduction == 'sum':
            loss = torch.sum(loss)
        elif self.reduction == 'none':
            pass
        return loss

def ssim(
        img1: torch.Tensor,
        img2: torch.Tensor,
        window_size: int,
        reduction: str = 'none',
        max_val: float = 1.0) -> torch.Tensor:
    r"""Function that measures the Structural Similarity (SSIM) index between
    each element in the input `x` and target `y`.

    See :class:`torchgeometry.losses.SSIM` for details.
        - Input: :math:`(B, C, H, W)`
        - Target :math:`(B, C, H, W)`
        - Output: scale, if reduction is 'none', then :math:`(B, C, H, W)`
    """
    return SSIM(window_size, reduction, max_val)(img1, img2)
if __name__=="__main__":
    img1 = torch.zeros(1,800,800,3).cpu()
    img2 = torch.zeros(1,800,800,3).cpu()
    img1 = img1.permute(0, 3, 1, 2)
    img2 = img2.permute(0, 3, 1, 2)
    img1 = img1[:,:,66:672,0:799]
    img2 = img2[:,:,66:672,0:799]
    res = ssim(img1, img2, window_size=11, reduction='mean')  #error occurs
`
 `
Traceback (most recent call last):
  File "/data/anaconda3/envs/refnerf/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3378, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-63-76bca2318409>", line 7, in <module>
    res = ssim(img1, img2, window_size=11, reduction='mean')
  File "../code/utils/metrics.py", line 192, in ssim
    return SSIM(window_size, reduction, max_val)(img1, img2)
  File "/data/anaconda3/envs/refnerf/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "../code/utils/metrics.py", line 113, in forward
    mu1: torch.Tensor = self.filter2D(img1, kernel, c)
  File "../code/utils/metrics.py", line 83, in filter2D
    return F.conv2d(input, kernel, padding=self.padding, groups=channel)
RuntimeError: y.get_desc().is_nhwc() INTERNAL ASSERT FAILED at "../aten/src/ATen/native/mkldnn/Conv.cpp":143, please report a bug to PyTorch. 
`


---- Maybe it's due to the storage format of Tensor?  Hope my issues will help!

**Comment by yanbing-j** [comment] 2022-11-02 05:52
Hi @neverstopZyy , I have verified in PyTorch master 1.14.0a0+git7674af9, this issue has been fixed.

**Comment by neverstopZyy** [comment] 2022-11-02 07:05
@yanbing-j  Thank you!!

**Comment by mingfeima** [comment] 2022-11-07 05:23
close this one as the issue has been fixed on master.

**Closed by mingfeima** 2022-11-07 05:23 UTC
Labels: module: nn, module: convolution, triaged, module: mkldnn
