### ISSUE TITLE
c10 `MetaprogrammingTest.FilterMap_onlyCopiesIfNecessary` fails on Windows

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#35546] opened 2020-03-27 16:54 UTC
Per [pytorch_windows_vs2019_py36_cuda10.1_test2](https://app.circleci.com/pipelines/github/pytorch/pytorch/144817/workflows/c0ac3f91-edb1-4294-9cf4-aad70b6a89d0/jobs/4916119):
```
[ RUN      ] MetaprogrammingTest.FilterMap_onlyCopiesIfNecessary
..\c10\test\util\Metaprogramming_test.cpp(176): error: Expected equality of these values:
  2
  result[0].move_count
    Which is: 3
..\c10\test\util\Metaprogramming_test.cpp(178): error: Expected equality of these values:
  1
  result[1].move_count
    Which is: 2
..\c10\test\util\Metaprogramming_test.cpp(180): error: Expected equality of these values:
  2
  result[2].move_count
    Which is: 3
[  FAILED  ] MetaprogrammingTest.FilterMap_onlyCopiesIfNecessary (0 ms)
[ RUN      ] MetaprogrammingTest.FilterMap_onlyMovesIfNecessary_1
..\c10\test\util\Metaprogramming_test.cpp(194): error: Expected equality of these values:
  1
  result[0].move_count
    Which is: 2
..\c10\test\util\Metaprogramming_test.cpp(196): error: Expected equality of these values:
  1
  result[1].move_count
    Which is: 2
[  FAILED  ] MetaprogrammingTest.FilterMap_onlyMovesIfNecessary_1 (0 ms)
```

cc @peterjc123

**Comment by agolynski** [comment] 2020-03-27 18:12
just to make sure: for these issues you reported where tests fail on windows, the failures are limited to windows only?

**Comment by malfet** [comment] 2020-03-27 18:50
@agolynski yes, same test is passing if I run it on Linux

**Comment by agolynski** [comment] 2020-03-30 13:15
Thanks, @malfet! I presume that is the case with other windows issues you've reported 3 days ago?

**Comment by mantaionut** [comment] 2022-12-14 06:07
This is a duplicate of #25161 which is fixed with C++ 17.

**Closed by mantaionut** 2022-12-14 06:07 UTC
Labels: module: windows, triaged
