### ISSUE TITLE
OSX 10.13 Macbook pro CUDA driver 9.0.197 not recognized

### ISSUE THREAD

**Issue by zhanghang1989** [pytorch/pytorch#3090] opened 2017-10-12 14:48 UTC
When run ` A = Variable(torch.cuda.DoubleTensor(B,N,K).uniform_(-0.5,0.5)`
```
File "/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 317, in _lazy_new
    _lazy_init()
  File "/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 99, in _lazy_init
    _check_driver()
  File "/anaconda/lib/python3.6/site-packages/torch/cuda/__init__.py", line 61, in _check_driver
    http://www.nvidia.com/Download/index.aspx""")
AssertionError: 
Found no NVIDIA driver on your system. Please check that you
have an NVIDIA GPU and installed a driver from
http://www.nvidia.com/Download/index.aspx
```

**Comment by alykhantejani** [comment] 2017-10-13 23:31
Hi @zhanghang1989,

This is caused by the cuda library not recognizing your driver (see [here](https://github.com/pytorch/pytorch/blob/cc3058bdac925dc20ba18b5829f689a67227f753/torch/csrc/cuda/Module.cpp#L167)). I think this is most likely due to the fact that the driver you are using does not support your OSX version. On [Nvidia's website](http://www.nvidia.com/object/macosx-cuda-9.0.197-driver.html) it says it only supports `OSX 10.12.x`

**Comment by zhanghang1989** [comment] 2017-10-14 00:05
Thanks @alykhantejani! 
I got a temporary solution:
- In the desktop, press CMD + SHIFT + G and put this path: `/Library/Frameworks/CUDA.framework/Versions/A/Libraries`
- Make a copy of the file name `libcuda_378.05.05.15_mercury.dylib`, and rename to `libcuda_378.10.10.10.15_mercury.dylib`
- - Edit the file Info.plist and add the following lines as the last childs in the NVDAResmanVersions element and save it:
```
		<key>378.10.10.10.15</key>
		<string>378.10.10.10.15</string>
```

**Comment by apaszke** [comment] 2017-10-14 12:44
It's not a PyTorch problem, so I'm closing this. @zhanghang1989 Thanks for posting the workaround!

**Closed by apaszke** 2017-10-14 12:44 UTC
