### ISSUE TITLE
THD OSX Warnings

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#3440] opened 2017-11-02 14:18 UTC
```
In file included from /Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/../THD.h:10:
/Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/TensorDescriptor.h:14:29: warning: 'THDTensorDescriptor_newFromTHDoubleTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHDoubleTensor(THDoubleTensor *tensor);
                            ^
/Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/TensorDescriptor.h:15:29: warning: 'THDTensorDescriptor_newFromTHFloatTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHFloatTensor(THFloatTensor *tensor);
                            ^
/Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/TensorDescriptor.h:16:29: warning: 'THDTensorDescriptor_newFromTHLongTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHLongTensor(THLongTensor *tensor);
                            ^
/Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/TensorDescriptor.h:17:29: warning: 'THDTensorDescriptor_newFromTHIntTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHIntTensor(THIntTensor *tensor);
                            ^
/Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/TensorDescriptor.h:18:29: warning: 'THDTensorDescriptor_newFromTHShortTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHShortTensor(THShortTensor *tensor);
                            ^
/Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/TensorDescriptor.h:19:29: warning: 'THDTensorDescriptor_newFromTHCharTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCharTensor(THCharTensor *tensor);
                            ^
/Users/soumith/code/pytorch/torch/lib/tmp_install/include/THD/base/TensorDescriptor.h:20:29: warning: 'THDTensorDescriptor_newFromTHByteTensor' has C-linkage specified, but returns user-defined type 'THDTensorDescriptor' (aka 'at::Tensor') which is incompatible with C [-Wreturn-type-c-linkage]
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHByteTensor(THByteTensor *tensor);
```

**Comment by lantiga** [comment] 2017-11-08 23:17
I was wondering about these warnings today, then I noticed this issue.
I assume that C linkage for THD is intended here even if `at::Tensor` is returned, so the need is to suppress the warning. In `torch/lib/THD/base/TensorDescriptor.h`, just add these pragma directives:

```C++
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreturn-type-c-linkage"

THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHDoubleTensor(THDoubleTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHFloatTensor(THFloatTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHLongTensor(THLongTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHIntTensor(THIntTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHShortTensor(THShortTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCharTensor(THCharTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHByteTensor(THByteTensor *tensor);
#ifdef WITH_CUDA
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCudaDoubleTensor(THCudaDoubleTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCudaFloatTensor(THCudaTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCudaLongTensor(THCudaLongTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCudaIntTensor(THCudaIntTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCudaShortTensor(THCudaShortTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCudaCharTensor(THCudaCharTensor *tensor);
THD_API THDTensorDescriptor THDTensorDescriptor_newFromTHCudaByteTensor(THCudaByteTensor *tensor);
#endif

#pragma clang diagnostic pop
```

I see that the issue is already assigned, so I'm not sending in a PR.

**Comment by mruberry** [comment] 2020-05-05 23:13
Closing due to age. (Also, wouldn't it be nice if we were still fixing warnings?)

**Closed by mruberry** 2020-05-05 23:13 UTC
