### ISSUE TITLE
[JIT] terminate called after throwing an instance of 'torch::jit::script::ErrorReport'

### ISSUE THREAD

**Issue by loopdigga98** [pytorch/pytorch#17054] opened 2019-02-13 15:53 UTC
## 🐛 Bug

An error occurs during loading model in C++ saved in Python via torch.jit.ScriptModule.
In Python, my model works as expected.

## To Reproduce

1. C++ code that loads model
```
#include <torch/script.h> // One-stop header.
#include <ATen/ATen.h>

#include <iostream>
#include <memory>

int main(int argc, const char* argv[]) {
    if (argc != 2) {
        std::cerr << "usage: example-app <path-to-exported-script-module>\n";
        return -1;
    }

    // Deserialize the ScriptModule from a file using torch::jit::load().
    std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(argv[1]);

    assert(module != nullptr);
    std::cout << "ok\n";
}
```
2.Error message
```
terminate called after throwing an instance of 'torch::jit::script::ErrorReport'
  what():  
unknown builtin op:
        _24 = _23
      else:
        _24 = torch.eq(_21, 3)
      if _24:
        ret = 0
      else:
        ret = 1
      dim = ret
    else:
      dim0 = ops.prim.unchecked_unwrap_optional(0)
             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
      dim = dim0
    _25 = torch.__is__(annotate(Optional[int], None), None)
    if _25:
      ret0 = torch.softmax(backscore, dim)
    else:
      dtype = ops.prim.unchecked_unwrap_optional(annotate(Optional[int], None))
      ret1 = torch.softmax(backscore, dim, dtype)
      ret0 = ret1
    _26, idx0 = torch.max(backscore, 0, False)
Aborted (core dumped)

```
3. Python model
<details>
  <summary>Click to show Python model</summary>

 ```

class TaggerProd(torch.jit.ScriptModule):
    
    __constants__ = ['relearn_embeddings', 'use_rnn', 'use_crf', 
                     'tag_dict', 'start_tag', 'stop_tag', 'tagset_size']
    
    def __init__(self, tag_dict, layers):
        """layers - dict of TracedModules pretrained""
        super(TaggerProd, self).__init__()
        self.embedding2nn_traced = layers['embedding2nn_traced']
        self.rnn_traced = layers['rnn_traced']
        self.linear_traced = layers['linear_traced']
        self.transitions = layers['transitions_prod']
        
        self.relearn_embeddings = True
        self.use_rnn = True
        self.use_crf = True
        self.tag_dict = tag_dict
        self.start_tag = '<START>'
        self.stop_tag = '<STOP>'
        self.tagset_size = len(tag_dict)
    
    @torch.jit.script_method
    def forward(self, sentence_tensor, lengths, transitions):
            """
                sentence_tensor: tensor of shape [longest sequence, num_of_sentences, embedding_dim]
                lengths: tensor of shape [seq1_length, seq2_length, seq3_length]
            """

            if self.relearn_embeddings:
                sentence_tensor = self.embedding2nn_traced(sentence_tensor)

            if self.use_rnn:
                sentence_tensor, hidden = self.rnn_traced(sentence_tensor)

            feature = self.linear_traced(sentence_tensor).transpose_(0, 1)

            #create output tensor
            longest_sequence = int(lengths[0])
            num_of_sent = lengths.size(0)
            prediction_shape = (num_of_sent, longest_sequence, 2)
            tags_tensor = torch.zeros(prediction_shape)
            tags = []

            for idx in range(num_of_sent):
                feats = feature[idx]
                length = lengths[idx]
                feats_cutted = feats[:length]

                if self.use_crf:
                    confidences, tag_seq = self._viterbi_decode_prod(feats_cutted, transitions)
                else:
                    tag_seq = torch.zeros((length))
                    confidences = torch.zeros((length))

                    for i in range(len(feats_cutted)):
                        backscore = feats_cutted[i]
                        softmax = F.softmax(backscore, dim=0)
                        _, idx_max = torch.max(backscore, 0)

                        tag_seq[i] = int(idx_max)
                        confidences[i] = float(softmax[int(idx_max)])

                predictions = torch.stack((tag_seq, confidences), dim=-1)
                to_cat_shape = (longest_sequence - int(length), 2)
                diff = longest_sequence - int(length)
                if diff != 0:
                    to_cat = torch.ones(to_cat_shape)
                    #fill with value -1 (torch.tensor.new_full() is not working in scriptmode)
                    for j in range(to_cat_shape[0]):
                        to_cat[j][0] = -1
                        to_cat[j][1] = -1
                    predictions = torch.cat((predictions, to_cat), dim=0)
                tags_tensor[idx] = predictions

            return tags_tensor
    
    @torch.jit.script_method
    def _viterbi_decode_prod(self, feats, transitions):
            """feats - torch.Tensor [sequence_length, feature_vector]
            """
            backpointers = []
            backscores = []

            init_vvars_shape = (1, self.tagset_size)
            init_vvars = torch.zeros(init_vvars_shape)

            start_idx = 0
            stop_idx = 0
            for pair in self.tag_dict:
                if self.start_tag == pair[0]:
                    start_idx = pair[1]
                if self.stop_tag == pair[0]:
                    stop_idx = pair[1]

            #fill with value (torch.tensor.new_full() is not working in scriptmode)
            for i in range(init_vvars_shape[1]):
                init_vvars[0][i] = -10000.

            init_vvars[0][start_idx] = 0
            forward_var = init_vvars

            for i in range(feats.size(0)):
                feat = feats[i]
                next_tag_var = forward_var.view(1, -1).expand(self.tagset_size,
                                                              self.tagset_size) + transitions
                _, bptrs_t = torch.max(next_tag_var, dim=1)

                bptrs_t = bptrs_t.squeeze().detach()
                next_tag_var = next_tag_var.detach()

                viterbivars_t = next_tag_var[torch.arange(0, bptrs_t.size(0), 1).long(), bptrs_t.long()]
                forward_var = viterbivars_t + feat
                backscores.append(forward_var)
                backpointers.append(bptrs_t)

            terminal_var = forward_var + transitions[stop_idx]
            terminal_var.detach()[stop_idx] = -10000.
            terminal_var.detach()[start_idx] = -10000.

            #call of argmax function
            _, tag_id = torch.max(terminal_var.unsqueeze(0), 1)
            best_path = [int(tag_id.view(-1).detach()[0])]
            best_tag_id = best_path[-1]

            #reveresed indexing
            backptrs_len = len(backpointers)
            for idx in range(backptrs_len):
                bptrs_t = backpointers[backptrs_len - 1 - idx]
                best_path.append(bptrs_t[best_tag_id])

            best_scores = torch.ones((len(backscores)))
            for i in range(len(backscores)):
                backscore = backscores[i]
                softmax = F.softmax(backscore, dim=0)
                _, idx = torch.max(backscore, 0)
                best_scores[i] = float(softmax[int(idx)])

            start = best_path[-1]
            best_path = best_path[:-1]

            best_path_reversed = torch.ones((len(best_path)))
            for idx in range(len(best_path)):
                best_path_reversed[idx] = best_path[len(best_path) - 1 - idx]
            return best_scores, best_path_reversed
```
</details>

## Expected behavior

'ok' message to stdout

## Environment
```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti

Nvidia driver version: 410.73
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.3.2
[pip3] numpy==1.15.3
[pip3] numpydoc==0.8.0
[pip3] pytorch-pretrained-bert==0.3.0
[pip3] torch==1.0.0
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl    defaults
[conda] faiss-cpu                 1.4.0            py36_cuda0.0_1    pytorch
[conda] mkl                       2019.0                      118    defaults
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0    defaults
[conda] mkl_random                1.0.1            py36h4414c95_1    defaults
[conda] pytorch-pretrained-bert   0.3.0                    pypi_0    pypi
[conda] torch                     1.0.0                    pypi_0    pypi
[conda] torchsummary              1.5.1                    pypi_0    pypi
[conda] torchvision               0.2.1                    pypi_0    pypi
```

## Additional context
I cannot upload model itself here because it is 100mb size

**Comment by eellison** [comment] 2019-02-14 17:48
We'll look into this, thanks for raising the issue. Is it possible you serialized the model on a verison of pytorch that is ahead of the version you tried to run it in C++ on? Could you try installing the newest build and see if the error still occurs.

**Comment by loopdigga98** [comment] 2019-02-18 15:58
I am using C++ version of torch from here ```https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip```

Pytorch version is from master branch.

**Comment by loopdigga98** [comment] 2019-02-19 12:18
I just realised that error occurs somewhere in ```_viterbi_decode_prod``` method.

**Comment by eellison** [comment] 2019-02-19 20:53
I was able to run the following without error, which serializes an unchecked_unwrap_optional and then loads it again in c++. Could you try downloading libtorch with the preview release and see if it works for you? I think the issue is the non-preview release is behind pytorch master.   https://pytorch.org/get-started/locally/

```
  auto module = torch::jit::compile(R"JIT(
      def optional_int(a: Optional[int]):
        if a is None:
          a = 1
        return a
    )JIT");

  module->save("./hi.pt");
  auto mod_2 = torch::jit::load("./hi.pt");
  auto graph = mod_2->get_method("optional_int").graph();
  std::stringstream ss;
  ss << *graph;
  AT_ASSERT(ss.str().find("prim::unchecked_unwrap_optional") != std::string::npos);

```

**Comment by eellison** [comment] 2019-02-20 18:47
Closing until I hear further.

**Closed by eellison** 2019-02-20 18:47 UTC
Labels: jit, jit-triaged

**Comment by loopdigga98** [comment] 2019-02-25 11:58
Hi @eellison, sorry for late reply. I've tried nigthly version of libtorch and error dissapear. Thank you for your help!

**Comment by padmasreenagarajan** [comment] 2020-07-14 11:25
even I faced the same error.Could u pls specify how it works with nightly version.
Whats the difference between nightly version and stable one? @loopdigga96

**Comment by prrw** [comment] 2021-08-19 09:23
Hello, can someone tell how to solve this error ? I tried different versions Stable(1.9.0) and Nightly and it did not work for both.
