### ISSUE TITLE
[JIT] JITter sometimes doesn't see namedtuple types in function annotations in `jit.ignore`d methods

### ISSUE THREAD

**Issue by narfanar** [pytorch/pytorch#31864] opened 2020-01-05 01:02 UTC
## 🐛 Bug

NamedTuple names when used in a new style function type annotation are not recognized by the jitter in `jit.ignore`d methods.

```
~/.local/lib/python3.6/site-packages/torch/jit/annotations.py in ann_to_type(ann, resolver)
    256         if the_type is not None:
    257             return the_type
--> 258     raise ValueError("Unknown type annotation: '{}'".format(ann))
    259 
    260 

ValueError: Unknown type annotation: '<class '__main__.GG'>'
```

Same issue when a NamedTuple is part of another type (a Tuple, and probably a List or a Dict, but I haven't tried those).

Then the error manifests even for comment style annotations.

## To Reproduce

```py
import torch as T

from collections import namedtuple
from typing import Tuple
GG = namedtuple('GG', ['f', 'g'])

class Foo(nn.Module):
    def __init__(self):
        super().__init__()

    @T.jit.ignore
    def foo(self, x, z) -> GG:
		# Above does NOT work

        # ! type: (Tensor, Tensor) -> GG
        # Above works

		# ! type: (Tensor, Tensor) -> Tuple[GG, GG]
		# return GG(x, z), GG(x, z)
		# Above does NOT work

        return GG(x, z)
    def forward(self, x, z):
        y0, y1 = self.foo(x, z)
        return y0 + y1

foo = T.jit.script(Foo())
y = foo(T.randn(100, 100), T.randn(100, 100))
```

## Expected behavior

Both annotation styles should support NamedTuples properly.

## Environment

```
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.3.1
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.4.0
[pip3] torchviz==0.0.1
```

## Additional context

None

cc @suo

**Comment by eellison** [comment] 2020-01-14 23:54
@driazati this is probably a dupe of another issue we had about named tuples across files. Resolving annotations by value will fix this.

**Closed** 2020-02-29 02:36 UTC
Labels: jit, triaged
