### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by kirktsao** [pytorch/pytorch#1872] opened 2017-06-22 07:46 UTC
My operation is hacktonish OSX 12.
Graphic is GTX960.
Installed Cuda 8 and CLT.
Python version is 2.7
Try the install from the source show error.
How can i fix it?

[  4%] Linking CXX shared library libTHD.dylib
Undefined symbols for architecture x86_64:
  "_state", referenced from:
      _THDTensorDescriptor_newFromTHCudaDoubleTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaFloatTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaLongTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaIntTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaShortTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaCharTensor in TensorDescriptor.cpp.o
      _THDTensorDescriptor_newFromTHCudaByteTensor in TensorDescriptor.cpp.o
      ...
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libTHD.1.dylib] Error 1
make[1]: *** [CMakeFiles/THD.dir/all] Error 2
make: *** [all] Error 2

![sy](https://user-images.githubusercontent.com/29519350/27422722-d52a3b1e-5761-11e7-9145-962054c59b19.png)

**Comment by jeon30c** [comment] 2017-06-23 08:27
The same error on Sierra 10.12.5 with cuda 8/cudnn 5 on imac 2015 late.
Compile was successful before the os upgrade.

**Comment by apaszke** [comment] 2017-06-23 11:52
Duplicate of #1818. Please search before you open issues

**Closed by apaszke** 2017-06-23 11:52 UTC
