### ISSUE TITLE
Unexpected/inconsistent behavior of `tensor.cuda.clamp` on nan array

### ISSUE THREAD

**Issue by d-rams** [pytorch/pytorch#16817] opened 2019-02-06 20:32 UTC
## 🐛 Bug

The tensor.clamp function returns the upper bound when applied to a nan array on the GPU.  On the CPU it returns nan instead.

## To Reproduce

```
import numpy as np
import torch
t = torch.FloatTensor([np.nan])
t.clamp(-10, 10)
```
`Out[26]: tensor([nan])`
```
t.cuda().clamp(-10, 10)
```
`Out[25]: tensor([10.], device='cuda:0')`

## Expected behavior

I would expect to have the behavior be agnostic to the computational substrate.  Regardless, returning the upper bound on nan is completely arbitrary and can't possibly be the preferred solution.

## Environment

PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 18.10
GCC version: (Ubuntu 8.2.0-7ubuntu1) 8.2.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 415.27
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] numpydoc==0.8.0
[pip3] torch==1.0.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl  
[conda] cuda80                    1.0                           0    soumith
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] libmklml                  2018.0.3                      0  
[conda] mkl                       2019.1                      144  
[conda] mkl-dnn                   0.14                          2    intel
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.6            py37hd81dba3_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.0.0           py3.7_cuda8.0.61_cudnn7.1.2_1  [cuda80]  pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
[conda] torchvision               0.2.1                     <pip>

**Comment by fmassa** [comment] 2019-02-06 22:59
Thanks for opening the issue!

I believe this is a duplicate of https://github.com/pytorch/pytorch/issues/15338, and has already been fixed in master.

**Closed by fmassa** 2019-02-06 22:59 UTC
