### ISSUE TITLE
[Caffe2] Windows 10 + CUDA 10 build error 

### ISSUE THREAD

**Issue by Maosef** [pytorch/pytorch#14872] opened 2018-12-07 01:44 UTC
The first time I built it successfully (build_windows.bat), but it didn't seem to find CUDA or cuDNN. I deleted the build directory and tried 
set USE_CUDA=ON
It seemed to find the GPU locations successfully. However this error eventually popped up: 

"C:\Users\pazzu\Documents\pytorch\build\ALL_BUILD.vcxproj" (default target) (1) ->
       "C:\Users\pazzu\Documents\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (26) ->
       (CustomBuild target) ->
         Error : Internal Compiler error (codegen): "there was an error in verifying the lgenfe output!" [C:\Users\pazz
       u\Documents\pytorch\build\caffe2\caffe2_gpu.vcxproj]

    37821 Warning(s)
    1 Error(s)

Time Elapsed 01:50:03.60
"Caffe2 building failed"

I'm using VS 15 2017 Win64 for the compiler.

**Comment by peterjc123** [comment] 2018-12-07 05:37
Please post the full build log here.

**Comment by VladPekar** [comment] 2018-12-21 21:18
Removing all AT_CPP14_CONSTEXPR expressions from ArrayRef.h eliminates this issue and compilation continues but then it still fails with the error messages mentioned here: 

https://discuss.pytorch.org/t/compilation-error-while-compiling-pytorch-1-0-on-windows-visual-studio-2017/32539

The compiler used is from VS 15.9.4

**Comment by peterjc123** [comment] 2018-12-22 06:15
@VladPekar Hi, your error is duplicated with #14410. And looks like you posted in the wrong issue.

**Comment by xsacha** [comment] 2019-04-01 06:14
I had this issue too. Upgrading to CUDA 10.1 or downgrading compiler worked.

**Comment by cristianPanaite** [comment] 2022-10-19 07:55
Hello @Maosef,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. 

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.

**Closed** 2022-10-19 13:16 UTC
Labels: module: windows, caffe2
