### ISSUE TITLE
Incorrect scoped tracing result

### ISSUE THREAD

**Issue by lanpa** [pytorch/pytorch#4495] opened 2018-01-05 12:33 UTC
Using torch 0.4.0a0+408c84d, tracing code adapted from #4200

1. `F.log_softmax` is interpreted as:
```
  %29 : Float(13, 10) = Softmax[axis=1](%28)  <--missing scopename
  %30 : Float(13, 10) = Log(%29), scope: Net1
```

2. Tracing result of VGG19/Alexnet from torchvision model: The scope of conv2d layers is `ReLU[x]` instead of `conv2d[x]`

alexnet:
```
  %17 : Float(1, 64, 55, 55) = Conv[dilations=[1, 1], group=1, kernel_shape=[11, 11], pads=[2, 2, 2, 2], strides=[4, 4]](%0, %1, %2), scope: AlexNet/Sequential[features]/**ReLU[1]**
  %18 : Float(1, 64, 55, 55) = Relu(%17), scope: AlexNet/Sequential[features]/ReLU[1]
  %19 : Float(1, 64, 27, 27) = MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%18), scope: AlexNet/Sequential[features]/MaxPool2d[2]
  %20 : Float(1, 192, 27, 27) = Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1]](%19, %3, %4), scope: AlexNet/Sequential[features]/**ReLU[4]**
  %21 : Float(1, 192, 27, 27) = Relu(%20), scope: AlexNet/Sequential[features]/ReLU[4]
  %22 : Float(1, 192, 13, 13) = MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%21), scope: AlexNet/Sequential[features]/MaxPool2d[5]
```

vgg19:
```
  %39 : Float(1, 64, 224, 224) = Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%0, %1, %2), scope: VGG/Sequential[features]/ReLU[1]
  %40 : Float(1, 64, 224, 224) = Relu(%39), scope: VGG/Sequential[features]/ReLU[1]
  %41 : Float(1, 64, 224, 224) = Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%40, %3, %4), scope: VGG/Sequential[features]/ReLU[3]
  %42 : Float(1, 64, 224, 224) = Relu(%41), scope: VGG/Sequential[features]/ReLU[3]
  %43 : Float(1, 64, 112, 112) = MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%42), scope: VGG/Sequential[features]/MaxPool2d[4]
  %44 : Float(1, 128, 112, 112) = Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%43, %5, %6), scope: VGG/Sequential[features]/ReLU[6]
  %45 : Float(1, 128, 112, 112) = Relu(%44), scope: VGG/Sequential[features]/ReLU[6]
  %46 : Float(1, 128, 112, 112) = Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%45, %7, %8), scope: VGG/Sequential[features]/ReLU[8]
  %47 : Float(1, 128, 112, 112) = Relu(%46), scope: VGG/Sequential[features]/ReLU[8]
  %48 : Float(1, 128, 56, 56) = MaxPool[kernel_shape=[2, 2], pads=[0, 0, 0, 0], strides=[2, 2]](%47), scope: VGG/Sequential[features]/MaxPool2d[9]
```

3. [debug hint?] Tracing result of Resnet can be fixed if I rewrite `self.relu` as functional (`F.relu()`) 
http://35.197.26.245:6006/#graphs

Thanks

**Comment by ezyang** [comment] 2018-01-05 14:53
So, there are a few bugs here.

1. In the first case, the problem is that we are not correctly propagating scopes to *all* of the nodes generated by a symbolic definition, only one the output (`torch/csrc/jit/passes/onnx.cpp`):

```
      if (outputs[i]) {
        // Allow symbolic() to skip specifying the type of the return node.
        // Unfortunately, they are on the hook for all internal nodes
        // (though in practice, the types are not computed.)
        if (!outputs[i]->hasType()) {
          outputs[i]->setType(old->typeOption());
        }
        // Copy over source location information to all nodes created by
        // the symbolic
        outputs[i]->node()->setSourceLocation(node->getSourceLocation());
        outputs[i]->node()->setScope(node->scope());
        env[old] = outputs[i];
```

This probably should be a simple fix; we should just adjust the default scope of newly added nodes before running the symbolic (assuming this is how it works... haven't double checked)

2. I'm not sure why this case is getting a nonsense scope, but it's definitely not the same bug as (1).

BTW, why does the workaround work? When @lantiga initially added scopes in 4eb8e1276511a07ced781e7b36da39cedc4f15cc, we added scopes to Module (which has an obvious "hook" point) but not the functional API (which doesn't have a place to easily interpose.)  So probably the workaround is preventing us from setting a scope.

**Comment by ezyang** [comment] 2018-01-05 14:53
I'm going to tentatively assign this to myself but I am not going to get to it before the end of this week.

**Comment by lantiga** [comment] 2018-01-05 15:07
Hey @ezyang @lanpa, I'm taking a look.

**Comment by lanpa** [comment] 2018-01-05 15:36
@ezyang @lantiga 
I just fixed Alexnet tracing by explicitly made the forward call without using `nn.Sequential`

replace the [classifier](https://github.com/pytorch/vision/blob/master/torchvision/models/alexnet.py#L33) with

        x = F.dropout(x)
        x = self.fc1(x)
        x = self.relu1(x) 
        x = F.dropout(x)
        x = self.fc2(x)
        x = self.relu2(x)
        x = self.fc3(x)

hope that helps~

**Comment by lantiga** [comment] 2018-01-05 16:11
Hi @lanpa, I want to make sure I'm reproducing what you see. This is what I get on AlexNet (I'm working on current master 408c84de7c4d852beffb9c64e2351b16cfff8a1f):

```
class AlexNet(nn.Module):

        def __init__(self, num_classes=1000):
            super(AlexNet, self).__init__()
            self.features = nn.Sequential(
                nn.Conv2d(3, 64, kernel_size=11, stride=4, padding=2),
                nn.ReLU(inplace=True),
                nn.MaxPool2d(kernel_size=3, stride=2),
                nn.Conv2d(64, 192, kernel_size=5, padding=2),
                nn.ReLU(inplace=True),
                nn.MaxPool2d(kernel_size=3, stride=2),
                nn.Conv2d(192, 384, kernel_size=3, padding=1),
                nn.ReLU(inplace=True),
                nn.Conv2d(384, 256, kernel_size=3, padding=1),
                nn.ReLU(inplace=True),
                nn.Conv2d(256, 256, kernel_size=3, padding=1),
                nn.ReLU(inplace=True),
                nn.MaxPool2d(kernel_size=3, stride=2),
            )
            self.classifier = nn.Sequential(
                nn.Dropout(),
                nn.Linear(256 * 6 * 6, 4096),
                nn.ReLU(inplace=True),
                nn.Dropout(),
                nn.Linear(4096, 4096),
                nn.ReLU(inplace=True),
                nn.Linear(4096, num_classes),
            )

        def forward(self, x):
            x = self.features(x)
            x = x.view(x.size(0), 256 * 6 * 6)
            x = self.classifier(x)
            return x


a = AlexNet()

t = Variable(torch.ones(1, 3, 227, 227), requires_grad=True)

traced, _ = torch.jit.trace(a, (t, ))
g = torch._C._jit_get_graph(traced)
print(g)
```

outputs

```
graph(%0 : Float(1, 3, 227, 227)) {
  %1 : Float(64, 3, 11, 11) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[0]
  %2 : Float(64) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[0]
  %3 : Float(1, 64, 56, 56), %4 : Float(1, 363, 3136), %5 : Float(0) = thnn_conv2d_forward[kernel_size=[11, 11], stride=[4, 4], padding=[2, 2]](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
  %6 : Float(1, 64, 56, 56) = thnn_conv2d[kernel_size=[11, 11], stride=[4, 4], padding=[2, 2]](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
  %7 : Float(1, 64, 56, 56) = _convolution_nogroup[stride=[4, 4], padding=[2, 2], dilation=[1, 1], transposed=0, output_padding=[0, 0]](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
  %8 : Float(1, 64, 56, 56) = _convolution[stride=[4, 4], padding=[2, 2], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
  %9 : Float(1, 64, 56, 56) = threshold_forward[threshold={0}, value={0}](%8), scope: AlexNet/Sequential[features]/ReLU[1]
  %10 : Float(1, 64, 56, 56) = threshold[threshold={0}, value={0}](%9), scope: AlexNet/Sequential[features]/ReLU[1]
  %11 : Float(1, 64, 27, 27), %12 : Long(1, 64, 27, 27) = max_pool2d_forward[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%10), scope: AlexNet/Sequential[features]/MaxPool2d[2]
  %13 : Float(1, 64, 27, 27), %14 : Long(1, 64, 27, 27) = max_pool2d[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%10), scope: AlexNet/Sequential[features]/MaxPool2d[2]
  %15 : Float(192, 64, 5, 5) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[3]
  %16 : Float(192) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[3]
  %17 : Float(1, 192, 27, 27), %18 : Float(1, 1600, 729), %19 : Float(0) = thnn_conv2d_forward[kernel_size=[5, 5], stride=[1, 1], padding=[2, 2]](%13, %15, %16), scope: AlexNet/Sequential[features]/Conv2d[3]
  %20 : Float(1, 192, 27, 27) = thnn_conv2d[kernel_size=[5, 5], stride=[1, 1], padding=[2, 2]](%13, %15, %16), scope: AlexNet/Sequential[features]/Conv2d[3]
  %21 : Float(1, 192, 27, 27) = _convolution_nogroup[stride=[1, 1], padding=[2, 2], dilation=[1, 1], transposed=0, output_padding=[0, 0]](%13, %15, %16), scope: AlexNet/Sequential[features]/Conv2d[3]
  %22 : Float(1, 192, 27, 27) = _convolution[stride=[1, 1], padding=[2, 2], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%13, %15, %16), scope: AlexNet/Sequential[features]/Conv2d[3]
  %23 : Float(1, 192, 27, 27) = threshold_forward[threshold={0}, value={0}](%22), scope: AlexNet/Sequential[features]/ReLU[4]
  %24 : Float(1, 192, 27, 27) = threshold[threshold={0}, value={0}](%23), scope: AlexNet/Sequential[features]/ReLU[4]
  %25 : Float(1, 192, 13, 13), %26 : Long(1, 192, 13, 13) = max_pool2d_forward[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%24), scope: AlexNet/Sequential[features]/MaxPool2d[5]
  %27 : Float(1, 192, 13, 13), %28 : Long(1, 192, 13, 13) = max_pool2d[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%24), scope: AlexNet/Sequential[features]/MaxPool2d[5]
  %29 : Float(384, 192, 3, 3) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[6]
  %30 : Float(384) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[6]
  %31 : Float(1, 384, 13, 13), %32 : Float(1, 1728, 169), %33 : Float(0) = thnn_conv2d_forward[kernel_size=[3, 3], stride=[1, 1], padding=[1, 1]](%27, %29, %30), scope: AlexNet/Sequential[features]/Conv2d[6]
  %34 : Float(1, 384, 13, 13) = thnn_conv2d[kernel_size=[3, 3], stride=[1, 1], padding=[1, 1]](%27, %29, %30), scope: AlexNet/Sequential[features]/Conv2d[6]
  %35 : Float(1, 384, 13, 13) = _convolution_nogroup[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0]](%27, %29, %30), scope: AlexNet/Sequential[features]/Conv2d[6]
  %36 : Float(1, 384, 13, 13) = _convolution[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%27, %29, %30), scope: AlexNet/Sequential[features]/Conv2d[6]
  %37 : Float(1, 384, 13, 13) = threshold_forward[threshold={0}, value={0}](%36), scope: AlexNet/Sequential[features]/ReLU[7]
  %38 : Float(1, 384, 13, 13) = threshold[threshold={0}, value={0}](%37), scope: AlexNet/Sequential[features]/ReLU[7]
  %39 : Float(256, 384, 3, 3) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[8]
  %40 : Float(256) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[8]
  %41 : Float(1, 256, 13, 13), %42 : Float(1, 3456, 169), %43 : Float(0) = thnn_conv2d_forward[kernel_size=[3, 3], stride=[1, 1], padding=[1, 1]](%38, %39, %40), scope: AlexNet/Sequential[features]/Conv2d[8]
  %44 : Float(1, 256, 13, 13) = thnn_conv2d[kernel_size=[3, 3], stride=[1, 1], padding=[1, 1]](%38, %39, %40), scope: AlexNet/Sequential[features]/Conv2d[8]
  %45 : Float(1, 256, 13, 13) = _convolution_nogroup[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0]](%38, %39, %40), scope: AlexNet/Sequential[features]/Conv2d[8]
  %46 : Float(1, 256, 13, 13) = _convolution[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%38, %39, %40), scope: AlexNet/Sequential[features]/Conv2d[8]
  %47 : Float(1, 256, 13, 13) = threshold_forward[threshold={0}, value={0}](%46), scope: AlexNet/Sequential[features]/ReLU[9]
  %48 : Float(1, 256, 13, 13) = threshold[threshold={0}, value={0}](%47), scope: AlexNet/Sequential[features]/ReLU[9]
  %49 : Float(256, 256, 3, 3) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[10]
  %50 : Float(256) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[features]/Conv2d[10]
  %51 : Float(1, 256, 13, 13), %52 : Float(1, 2304, 169), %53 : Float(0) = thnn_conv2d_forward[kernel_size=[3, 3], stride=[1, 1], padding=[1, 1]](%48, %49, %50), scope: AlexNet/Sequential[features]/Conv2d[10]
  %54 : Float(1, 256, 13, 13) = thnn_conv2d[kernel_size=[3, 3], stride=[1, 1], padding=[1, 1]](%48, %49, %50), scope: AlexNet/Sequential[features]/Conv2d[10]
  %55 : Float(1, 256, 13, 13) = _convolution_nogroup[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0]](%48, %49, %50), scope: AlexNet/Sequential[features]/Conv2d[10]
  %56 : Float(1, 256, 13, 13) = _convolution[stride=[1, 1], padding=[1, 1], dilation=[1, 1], transposed=0, output_padding=[0, 0], groups=1, benchmark=0, deterministic=0, cudnn_enabled=1](%48, %49, %50), scope: AlexNet/Sequential[features]/Conv2d[10]
  %57 : Float(1, 256, 13, 13) = threshold_forward[threshold={0}, value={0}](%56), scope: AlexNet/Sequential[features]/ReLU[11]
  %58 : Float(1, 256, 13, 13) = threshold[threshold={0}, value={0}](%57), scope: AlexNet/Sequential[features]/ReLU[11]
  %59 : Float(1, 256, 6, 6), %60 : Long(1, 256, 6, 6) = max_pool2d_forward[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%58), scope: AlexNet/Sequential[features]/MaxPool2d[12]
  %61 : Float(1, 256, 6, 6), %62 : Long(1, 256, 6, 6) = max_pool2d[kernel_size=[3, 3], stride=[2, 2], padding=[0, 0], dilation=[1, 1], ceil_mode=0](%58), scope: AlexNet/Sequential[features]/MaxPool2d[12]
  %63 : Float(1, 9216) = view[size=[1, 9216]](%61), scope: AlexNet
  %64 : Float(1, 9216), %65 : Handle = ^Dropout(0.5, True, False)(%63), scope: AlexNet/Sequential[classifier]/Dropout[0]
  %66 : Float(1, 4096) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[classifier]/Linear[1]
  %67 : Float(9216!, 4096!) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[classifier]/Linear[1]
  %68 : Float(1, 4096) = addmm[beta={1}, alpha={1}](%66, %64, %67), scope: AlexNet/Sequential[classifier]/Linear[1]
  %69 : Float(1, 4096) = threshold_forward[threshold={0}, value={0}](%68), scope: AlexNet/Sequential[classifier]/ReLU[2]
  %70 : Float(1, 4096) = threshold[threshold={0}, value={0}](%69), scope: AlexNet/Sequential[classifier]/ReLU[2]
  %71 : Float(1, 4096), %72 : Handle = ^Dropout(0.5, True, False)(%70), scope: AlexNet/Sequential[classifier]/Dropout[3]
  %73 : Float(1, 4096) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[classifier]/Linear[4]
  %74 : Float(4096!, 4096!) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[classifier]/Linear[4]
  %75 : Float(1, 4096) = addmm[beta={1}, alpha={1}](%73, %71, %74), scope: AlexNet/Sequential[classifier]/Linear[4]
  %76 : Float(1, 4096) = threshold_forward[threshold={0}, value={0}](%75), scope: AlexNet/Sequential[classifier]/ReLU[5]
  %77 : Float(1, 4096) = threshold[threshold={0}, value={0}](%76), scope: AlexNet/Sequential[classifier]/ReLU[5]
  %78 : Float(1, 1000) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[classifier]/Linear[6]
  %79 : Float(4096!, 1000!) = Constant[value=<Tensor>](), scope: AlexNet/Sequential[classifier]/Linear[6]
  %80 : Float(1, 1000) = addmm[beta={1}, alpha={1}](%78, %77, %79), scope: AlexNet/Sequential[classifier]/Linear[6]
  return (%80);
}
```

**Comment by lanpa** [comment] 2018-01-05 16:50
@lantiga Here's my modified network: (I forward tensors explicitly)
https://gist.github.com/lanpa/452268a4e48106d79357dabf82d76054

And sorry, I forgot that I also called optimize:
https://github.com/lanpa/tensorboard-pytorch/blob/master/tensorboardX/graph.py#L45

so the output is much concise
```
graph(%0 : Float(1, 3, 224, 224)
      %1 : Float(64, 3, 11, 11)
      %2 : Float(64)
      %3 : Float(192, 64, 5, 5)
      %4 : Float(192)
      %5 : Float(384, 192, 3, 3)
      %6 : Float(384)
      %7 : Float(256, 384, 3, 3)
      %8 : Float(256)
      %9 : Float(256, 256, 3, 3)
      %10 : Float(256)
      %11 : Float(4096, 9216)
      %12 : Float(4096)
      %13 : Float(4096, 4096)
      %14 : Float(4096)
      %15 : Float(1000, 4096)
      %16 : Float(1000)) {
  %17 : Float(1, 64, 55, 55) = Conv[dilations=[1, 1], group=1, kernel_shape=[11, 11], pads=[2, 2, 2, 2], strides=[4, 4]](%0, %1, %2), scope: AlexNet/Sequential[features]/Conv2d[0]
  %18 : Float(1, 64, 55, 55) = Relu(%17), scope: AlexNet/Sequential[features]/ReLU[1]
  %19 : Float(1, 64, 27, 27) = MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%18), scope: AlexNet/Sequential[features]/MaxPool2d[2]
  %20 : Float(1, 192, 27, 27) = Conv[dilations=[1, 1], group=1, kernel_shape=[5, 5], pads=[2, 2, 2, 2], strides=[1, 1]](%19, %3, %4), scope: AlexNet/Sequential[features]/Conv2d[3]
  %21 : Float(1, 192, 27, 27) = Relu(%20), scope: AlexNet/Sequential[features]/ReLU[4]
  %22 : Float(1, 192, 13, 13) = MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%21), scope: AlexNet/Sequential[features]/MaxPool2d[5]
  %23 : Float(1, 384, 13, 13) = Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%22, %5, %6), scope: AlexNet/Sequential[features]/Conv2d[6]
  %24 : Float(1, 384, 13, 13) = Relu(%23), scope: AlexNet/Sequential[features]/ReLU[7]
  %25 : Float(1, 256, 13, 13) = Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%24, %7, %8), scope: AlexNet/Sequential[features]/Conv2d[8]
  %26 : Float(1, 256, 13, 13) = Relu(%25), scope: AlexNet/Sequential[features]/ReLU[9]
  %27 : Float(1, 256, 13, 13) = Conv[dilations=[1, 1], group=1, kernel_shape=[3, 3], pads=[1, 1, 1, 1], strides=[1, 1]](%26, %9, %10), scope: AlexNet/Sequential[features]/Conv2d[10]
  %28 : Float(1, 256, 13, 13) = Relu(%27), scope: AlexNet/Sequential[features]/ReLU[11]
  %29 : Float(1, 256, 6, 6) = MaxPool[kernel_shape=[3, 3], pads=[0, 0, 0, 0], strides=[2, 2]](%28), scope: AlexNet/Sequential[features]/MaxPool2d[12]
  %30 : Float(1, 9216) = Flatten[axis=1](%29), scope: AlexNet
  %31 : Float(1, 9216), %32 : UNKNOWN_TYPE = Dropout[is_test=1, ratio=0.5](%30), scope: AlexNet
  %33 : Float(1, 4096) = Gemm[alpha=1, beta=1, broadcast=1, transB=1](%31, %11, %12), scope: AlexNet/Linear[fc1]
  %34 : Float(1, 4096) = Relu(%33), scope: AlexNet/ReLU[relu1]
  %35 : Float(1, 4096), %36 : UNKNOWN_TYPE = Dropout[is_test=1, ratio=0.5](%34), scope: AlexNet
  %37 : Float(1, 4096) = Gemm[alpha=1, beta=1, broadcast=1, transB=1](%35, %13, %14), scope: AlexNet/Linear[fc2]
  %38 : Float(1, 4096) = Relu(%37), scope: AlexNet/ReLU[relu2]
  %39 : Float(1, 1000) = Gemm[alpha=1, beta=1, broadcast=1, transB=1](%38, %15, %16), scope: AlexNet/Linear[fc3]
  return (%39);
}
```

**Comment by lantiga** [comment] 2018-01-05 16:52
Thanks a lot. Indeed the issue seems to be the ONNX pass in optimize, as @ezyang already pointed to.

**Comment by lantiga** [comment] 2018-01-05 17:25
Ok I think I get it. I believe both are the expression of the same issue in `torch/onnx/__init__.py`.
The fix is not hard but not a one-liner, I'll work on it in the weekend.

**Comment by lantiga** [comment] 2018-01-06 01:36
The `log_softmax` issue is clear, I have a fix.

The issue with AlexNet, Resnet etc is trickier: it's related to Relu having `inplace=True` (it's independent from the use of Sequential).

Essentially, during the ONNX pass, the scope is correctly set to `AlexNet/Sequential[features]/Conv2d[0]` when the `_convolution` op is created, but then it gets overwritten with `AlexNet/Sequential[features]/ReLU[1]`.

This is because `outputs[i]` in
```
if (outputs[i]) {
        // Allow symbolic() to skip specifying the type of the return node.
        // Unfortunately, they are on the hook for all internal nodes
        // (though in practice, the types are not computed.)
        if (!outputs[i]->hasType()) {
          outputs[i]->setType(old->typeOption());
        }
        // Copy over source location information to all nodes created by
        // the symbolic
        outputs[i]->node()->setSourceLocation(node->getSourceLocation());
        outputs[i]->node()->setScope(node->scope());
        env[old] = outputs[i];
}
```
points to the same address for Conv and the subsequent ReLU.

Since the symbolic pass has no use for inplace, the output for ReLU should really be a new object even with `inplace=True`.

/cc @ezyang

**Comment by ezyang** [comment] 2018-01-06 05:15
@lantiga, although I was initially not convinced, you nailed it on the head; in fact, this bug was uncovered by hotpatch #4471 (for #4480), which is working around a tracing problem by returning identity, causing setOutputs to go wrong. (We return identity in other places but its occurrence is much more rare.)

I think the correct way to fix this is to test if `output[i]` aliases one of the inputs (the passthrough case) and skip the setting if it is. Should be easy!

**Comment by lantiga** [comment] 2018-01-06 18:53
@ezyang the plot thickens. So, this is what I get on AlexNet when I print out addresses of node, inputs and outputs at this point https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/passes/onnx.cpp#L89

```
OP NAME _convolution
node:                    0x7fbd786dfef0
input:                   0x7fbd7a8a4bb0
input->node:             0x7fbd786b40e0
output:                  0x7fbd78443b60
output->node:            0x7fbd78412f60

OP NAME threshold_forward
node:                   0x7fbd786e05f0
input:                  0x7fbd786dffe0
input->node:            0x7fbd786dfef0
output:                 0x7fbd78443b60     <-- same as Conv output
output->node:           0x7fbd78412f60     <-- same as Conv output->node

OP NAME threshold
node:                   0x7fbd786e0c70
input:                  0x7fbd786e08e0
input->node:            0x7fbd786e05f0
output:                 0x7fbd7873ba70
output->node:           0x7fbd7873b5b0
```
It seems that the later `threshold` behaves correctly, but that `threshold_forward` reuses `_convolution`'s output node. This leads to `threshold_forward`'s scope to overwrite `_convolution`'s scope.

Side note: I was expecting that #4471 would only make one of threshold and threshold_forward appear in the trace.

**Comment by ezyang** [comment] 2018-01-06 19:15
@lantiga That seems consistent? #4471 operates by effectively creating an ONNX translation for `threshold_forward` that is identity (i.e., whatever `Value` it gets as input, it returns as output).

Maybe your problem is, in your debug statements, you're mixing up the input nodes from the old graph, versus the new graph. You need to check for aliasing against the new graph (i.e., after `env` translation).

**Comment by lantiga** [comment] 2018-01-06 20:54
Thanks for the explanation @ezyang 

I'll look at this more closely, but in the meantime these are my debug statements:
```
      if (outputs[i]) {
        // Allow symbolic() to skip specifying the type of the return node.
        // Unfortunately, they are on the hook for all internal nodes
        // (though in practice, the types are not computed.)
        if (!outputs[i]->hasType()) {
          outputs[i]->setType(old->typeOption());
        }
        // Copy over source location information to all nodes created by
        // the symbolic
        outputs[i]->node()->setSourceLocation(node->getSourceLocation());
        outputs[i]->node()->setScope(old->node()->scope());

        for (auto* input : node->inputs()) {
          std::cout << "OP NAME " << op_name << " " << node << " INPUT " << input << " INPUT NODE " << input->node() << " OUTPUT " << outputs[i] << " OUTPUT NODE " << outputs[i]->node() << std::endl;
          break;
        }
```

**Comment by lantiga** [comment] 2018-01-07 01:18
Your suggestion worked @ezyang, I've got the fix. I'll submit a PR tomorrow, thanks!

**Comment by lantiga** [comment] 2018-01-07 13:51
Fix is in /cc @ezyang

**Comment by lanpa** [comment] 2018-01-09 11:59
@lantiga I just test with commit b3710a2 and This time the scope of Dropout in Alexnet disappeared.

`  %31 : Float(1, 9216), %32 : UNKNOWN_TYPE = Dropout[is_test=1, ratio=0.5](%30)`

**Comment by lantiga** [comment] 2018-01-09 12:01
@lanpa darn. Can you check if the scope is there in the non-optimized version of the trace?

**Comment by lanpa** [comment] 2018-01-09 12:11
@lantiga 
Dropouts are  `%70` and `%77`, and scope is correct before optimize.
https://gist.github.com/lanpa/57ac91b85c1fd8420bfdd8787162cff1

**Comment by ezyang** [comment] 2018-01-09 13:44
@lantiga Ack! I know exactly what the problem is: you need to set the scope guard for `callPySymbolicMethod` as well (really, any call site of `processSymbolicOutput`; and there are multiple).

This time, can we get `assertExpected` style tests too? Easier to see problems like that this way :)

**Comment by lantiga** [comment] 2018-01-09 13:45
Yep, that's it. I can fix this in a couple of hours.
I'll also change the tests. Thanks!

**Closed** 2018-01-09 20:57 UTC
Labels: onnx
