### ISSUE TITLE
Reduce the amount of TLS used in pytorch

### ISSUE THREAD

**Issue by lxj0276** [pytorch/pytorch#2083] opened 2017-07-13 16:36 UTC
when I run the code:https://github.com/bear63/sceneReco
I shows thatImportError:dlopen:cannot load any more object with static TLS

**Comment by soumith** [comment] 2017-07-13 17:12
this is a known issue when loading multiple libraries (`torch`, `cv2`) that use a lot of TLS. I'm not sure how to fix it.

**Comment by lxj0276** [comment] 2017-07-13 17:13
I have fixed it.anyway thx

**Comment by soumith** [comment] 2017-07-13 17:14
How did you fix it?

**Comment by lxj0276** [comment] 2017-07-13 17:18
the order of import
import cv2,torch,caffe is ok,not import caffe,torch,anyway ,it's import between torch and caffe

**Comment by cc786537662** [comment] 2017-09-30 05:17
very odd case,i solve it by add one line in the very beginningof my .py file: 
import torch,cv2
 wherever it comes this error.

**Comment by lionel3** [comment] 2017-11-07 11:54
Just like @cc786537662. I solved the problem  by putting the line " import torch"  in the very beginning of my .py file.

**Comment by jph00** [comment] 2017-11-15 01:56
There are some options proposed here that claim to fix it: https://stackoverflow.com/questions/19268293/matlab-error-cannot-open-with-static-tls . Not sure if any of these might help?

FYI I (and our students) can reliably replicate this bug by running lesson1 of the new fastai on Paperspace. It's not a high priority since we can just use AWS instead, but I figured you might be interested in a reliable replication environment.

**Comment by soumith** [comment] 2017-11-16 17:44
@jph00 i am building binaries for `v0.3.0` right now, so i am looking to fix this once and for-all for the new binaries.

I got a paperspace instance and tried to replicate this error. I ran a few notebooks that use pytorch under deeplearning2 but had no luck reproducing so far.

Which notebook is reproducing this error for you?
You said lesson1, but lesson1 doesn't even use pytorch: https://github.com/fastai/courses/blob/master/deeplearning1/nbs/lesson1.ipynb

Am I looking at the wrong location?

**Comment by soumith** [comment] 2017-11-16 17:55
nevermind, i see that you're talking about https://github.com/fastai/fastai
I'm working on reproducing that.

**Comment by htwaijry** [comment] 2017-11-17 18:47
@soumith I was having a similar issue, then I added these compile flags `-fPIC -ftls-model=global-dynamic` in `setup.py`, and recompiled pytorch, and it seems to have resolved my issue.

**Comment by soumith** [comment] 2017-11-17 19:01
@htwaijry from what i know the source installs dont have this problem (you dont even need the compile flags). Only the binary installs have this issue. Can you confirm that if you recompiled pytorch from source (without your flags) the problem doesn't exist?

**Comment by htwaijry** [comment] 2017-11-17 21:21
@soumith You are right, compiling from source without the flags also works. I just went ahead and added those flags when I ran into the problem without trying to compile from source directly without them.

**Comment by frankenstan** [comment] 2017-11-21 10:06
It is kind of hilarious. When I put cv2 before pytorch I got this error, and when I exchange the position I got the same error as #926 , what can I do?

**Comment by soumith** [comment] 2017-11-21 14:06
@frankenstan the workaround is to do this on your machine:

`rm $(dirname $(which python))/../lib/*/site-packages/torch/lib/libgomp.so*`

**Comment by frankenstan** [comment] 2017-11-21 16:11
@soumith thx for your reply. Sadly I didn't find it in that directory.
I am in anaconda2 and ubuntu14.04. Anything else I can do?

**Comment by xyiyy** [comment] 2017-11-24 09:29
I have found one solution but not perfect for this kind of problem. I hope the next version of pytorch can fix such problem.

We write a script called "main.py", in which we use the pytorch but without opencv. And as for opencv operation, we are mainly aimed to process data, so I create another script called "datautils.py", in which we import opencv without using any operation in pytorch. 

In order to get the data from datautils.py, we can take measures as following. For example
in main.py
```python
import torch 
# some operation in torch
from subprocess import PIPE,Popen
import pickle
p = Popen('python datautils.py ' + argv, shell=True, stdout=PIPE, stderr=PIPE)
out,err = p.communicate()
data = pickle.loads(out)
# some operation in torch
```
In datautils.py
```python 
import cv2
import pickle
if __name__ == "__main__":
    cap = cv2.VideoCapture(argv[1])
    has_next, img = cap.read()
    # and some other operation in cv2
    print(pickle.dumps(data))
```
It works in debian.

**Comment by liruilong940607** [comment] 2017-12-03 07:48
build pytorch from source can avoid this issue

**Comment by chenxi-ge** [comment] 2017-12-06 23:38
I solved this issue by separately `import torch` early in my program. (it could be cv2 issue, as later  fastai/imports.py will import cv2 for me)
However, I also saw people say we should import cv2 first.

Nevertheless, worth a try.

**Comment by PhotonChow** [comment] 2017-12-19 10:59
Use this instruction to update your pytorch to 0.3.0 and you shall solve this problem.
conda install pytorch torchvision -c pytorch

**Comment by teichert** [comment] 2017-12-20 21:14
Fwiw, note that the temporary workaround of putting `import torch` first source files using torch may be insufficient if functions from those source files are being imported elsewhere.

For example, if a.py imports torch and b.py doesn't import torch but imports functions defined in a.py, then other imports in b.py may happen before the torch import.

In my case, I saw that this was happening by noticing that some source files in the stack trace for the "ImportError:dlopen:cannot load any more object with static TLS" didn't even import torch at all. Adding `import torch` on the first line of source files lower on the stack trace "fixed" the problem for me.

(btw, I had this error and work-around even after the update to 0.3.0.)

**Comment by ayushidalmia** [comment] 2018-02-27 05:35
Do we have any resolution for this yet:
I am using pip install (have to use /usr/bin/python) method to install torch.

**Comment by zhangpiu** [comment] 2018-03-02 06:09
Similar issue when I import torch in Julia using PyCall.
![image](https://user-images.githubusercontent.com/992199/36885651-411f7194-1e23-11e8-85bb-2446c8c2dc16.png)

**Comment by wrobstory** [comment] 2018-05-17 21:34
For future readers: we are still seeing this with pytorch 0.3.1, and thus far our only working solution has been to move imports around as is mentioned above. I'd _really_ like to see pytorch fix this if at all possible: we're introducing some relatively brittle hacks to work around it right now.

**Comment by soumith** [comment] 2018-05-17 21:43
@wrobstory with pytorch v0.4.0 this should completely go away, as we no longer ship with our own libgomp.so (which was the problem-child in the first place)

**Comment by wrobstory** [comment] 2018-05-17 21:45
@soumith thanks for the quick reply, that's great to know!

**Comment by taojake** [comment] 2018-06-06 09:40
@soumith the issue till exist in v0.4.0, how can i fix it.

**Comment by jianchao-li** [comment] 2018-09-04 07:17
I just came across this problem when I did
```
import torch
import torchvison
import tensorflow as tf
import mxnet as mx
```
And it disappeared if I changed the order a little bit.
```
import tensorflow as tf
import mxnet as mx
import torch
import torchvision
```

**Comment by ezyang** [comment] 2019-07-26 14:20
With a more recent version of scikit learn, our gcc5.4 build is affected by this:

```
Jul 26 05:19:59 Running test_cuda ... [2019-07-26 05:19:59.821119]
Jul 26 05:20:01 Traceback (most recent call last):
Jul 26 05:20:01   File "/opt/conda/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 44, in <module>
Jul 26 05:20:01     from ._check_build import check_build  # noqa
Jul 26 05:20:01 ImportError: dlopen: cannot load any more object with static TLS
Jul 26 05:20:01 
Jul 26 05:20:01 During handling of the above exception, another exception occurred:
Jul 26 05:20:01 
Jul 26 05:20:01 Traceback (most recent call last):
Jul 26 05:20:01   File "test_cuda.py", line 20, in <module>
Jul 26 05:20:01     from test_torch import _TestTorchMixin
Jul 26 05:20:01   File "/var/lib/jenkins/workspace/test/test_torch.py", line 46, in <module>
Jul 26 05:20:01     import librosa
Jul 26 05:20:01   File "/opt/conda/lib/python3.6/site-packages/librosa/__init__.py", line 15, in <module>
Jul 26 05:20:01     from . import decompose
Jul 26 05:20:01   File "/opt/conda/lib/python3.6/site-packages/librosa/decompose.py", line 19, in <module>
Jul 26 05:20:01     import sklearn.decomposition
Jul 26 05:20:01   File "/opt/conda/lib/python3.6/site-packages/sklearn/__init__.py", line 75, in <module>
Jul 26 05:20:01     from . import __check_build
Jul 26 05:20:01   File "/opt/conda/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 46, in <module>
Jul 26 05:20:01     raise_build_error(e)
Jul 26 05:20:01   File "/opt/conda/lib/python3.6/site-packages/sklearn/__check_build/__init__.py", line 41, in raise_build_error
Jul 26 05:20:01     %s""" % (e, local_dir, ''.join(dir_content).strip(), msg))
Jul 26 05:20:01 ImportError: dlopen: cannot load any more object with static TLS
Jul 26 05:20:01 ___________________________________________________________________________
Jul 26 05:20:01 Contents of /opt/conda/lib/python3.6/site-packages/sklearn/__check_build:
Jul 26 05:20:01 __pycache__               setup.py                  _check_build.cpython-36m-x86_64-linux-gnu.so
Jul 26 05:20:01 __init__.py
Jul 26 05:20:01 ___________________________________________________________________________
Jul 26 05:20:01 It seems that scikit-learn has not been built correctly.
Jul 26 05:20:01 
Jul 26 05:20:01 If you have installed scikit-learn from source, please do not forget
Jul 26 05:20:01 to build the package before using it: run `python setup.py install` or
Jul 26 05:20:01 `make` in the source directory.
Jul 26 05:20:01 
Jul 26 05:20:01 If you have used an installer, please check that it is suited for your
Jul 26 05:20:01 Python version, your operating system and your platform.
Jul 26 05:20:01 Traceback (most recent call last):
Jul 26 05:20:01   File "test/run_test.py", line 408, in <module>
Jul 26 05:20:01     main()
Jul 26 05:20:01   File "test/run_test.py", line 400, in main
Jul 26 05:20:01     raise RuntimeError(message)
Jul 26 05:20:01 RuntimeError: test_cuda failed!
```

https://circleci.com/gh/pytorch/pytorch/2292470?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by Arctanxy** [comment] 2019-08-09 02:18
this error appeared when I upgrade torch from 1.1 to 1.2

**Comment by ezyang** [comment] 2019-08-16 20:30
To consolidate, I'm closing this as a dupe of #2575

**Closed by ezyang** 2019-08-16 20:30 UTC
Labels: high priority, needs discussion

**Comment by neverstopZyy** [comment] 2022-09-19 14:15
This error occurs after I upgrade the version of GCC with some wrong setting. 
And I fix this problem through compling the dependency of GCC, 
```
wget https://gcc.gnu.org/pub/gcc/infrastructure/isl-0.18.tar.bz2
tar xvf isl-0.18.tar.bz2 
cd isl-0.18
./configure --prefix=/usr/local/isl --with-gmp-prefix=/usr/local/gmp/
make && make install
```
Btw, I don't know the reason, and hope for futher disscussion.
