### ISSUE TITLE
UNSTABLE inductor / cuda12.4-py3.10-gcc9-sm86 / test (inductor_timm)

### ISSUE THREAD

**Issue by benjaminglass1** [pytorch/pytorch#141498] opened 2024-11-25 18:48 UTC
The `convnext_base` test appears to have been broken since https://github.com/pytorch/pytorch/pull/139206 merged.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov

**Comment by benjaminglass1** [comment] 2024-11-25 18:51
I don't know if opening this issue was the right thing to do; I can also open a PR that marks this test as an XFAIL if that would be better?

**Comment by huydhn** [comment] 2024-11-25 19:06
Opening this issue is fine, but need to remember to close it once the issue is fixed.  I think several folks have started looking into this.  cc @yf225 @desertfire @jerryzh168

**Comment by yf225** [comment] 2024-11-26 00:41
@benjaminglass1 curious do you also have a link to the test error message?

**Comment by benjaminglass1** [comment] 2024-11-26 15:29
@yf225 Sure, here's one from a branch I have in testing rn. https://hud.pytorch.org/pr/pytorch/pytorch/141369#33502250219

I rebased it regularly yesterday, but there's always the chance that something was fixed on `viable/strict` since then.

**Comment by jerryzh168** [comment] 2024-11-27 04:28
I have a failure here as well: https://github.com/pytorch/pytorch/actions/runs/12040838911/job/33572934620?pr=140627

**Comment by ezyang** [comment] 2024-12-05 14:31
I'm going to skip convnext_base and put this job out of unstable

**Comment by ezyang** [comment] 2024-12-05 14:36
Any progress on diagnosing this? @bertmaher

**Comment by bertmaher** [comment] 2024-12-05 19:24
It looks like this is only reproing on sm86, which is going to be a real pain to debug since we don't have any of those for local development.  Going to think through options here and report back

**Comment by huydhn** [comment] 2024-12-09 09:33
This has been mitigated by https://github.com/pytorch/pytorch/pull/142159, so I'm closing this to move this job back to trunk

**Closed by huydhn** 2024-12-09 09:33 UTC
Labels: module: ci, triaged, oncall: pt2, module: inductor, unstable
