### ISSUE TITLE
Tensor data dtype ComplexFloat not supported for NCCL process group

### ISSUE THREAD

**Issue by pfeatherstone** [pytorch/pytorch#99518] opened 2023-04-19 10:24 UTC
### 🐛 Describe the bug

```
net = torch.nn.Conv1d(1,1,dtype=torch.complex64)
```
Now try to use that in distributed training.
You get the error:
```
RuntimeError: Input tensor data type is not supported for NCCL process group: ComplexFloat
```

### Versions

I'm using torch  2.0.0+cu117

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by ezyang** [comment] 2023-04-19 19:31
dupe of https://github.com/pytorch/pytorch/issues/71613

**Closed by ezyang** 2023-04-19 19:31 UTC
Labels: oncall: distributed, feature, triaged, module: complex, module: nccl

**Comment by pfeatherstone** [comment] 2023-04-24 07:29
is there a workaround for this?

**Comment by ezyang** [comment] 2023-04-24 14:33
there's some workarounds on the thread, see if any of them help you
