### ISSUE TITLE
[jit] Autodiff bug on double backward for early expiration of grad_accumulator 

### ISSUE THREAD

**Issue by wanchaol** [pytorch/pytorch#19769] opened 2019-04-25 21:31 UTC
## 🐛 Bug

Our autodiff infrastructure have bugs on double backward for early expiration of grad_accumulator for some formulas (i.e. layer_norm, linear). 

It gives error like below

```
  File "test/test_jit.py", line 659, in checkTrace
    grads2_ge = torch.autograd.grad(l2_ge, flattened_recording_inputs, allow_unused=allow_unused)
  File "/scratch/wanchaol/local/pytorch/torch/autograd/__init__.py", line 149, in grad
    inputs, allow_unused)
RuntimeError: No grad accumulator for a saved leaf!
```

This is happening on master now, the bug is kinda complicated to trigger: when we add an non-trivial AD formula, sometimes non-trivial models will throw the above error, while in pure Autograd mode it runs fine. 

## To Reproduce

I noticed this problem appears in #20284 , after I added an AD formula for `linear` in #20039. 

1. git fetch origin; git checkout gh/wanchaol/5/origin
1. python setup.py develop
1. python test/test_jit.py TestEndToEndHybridFrontendModels.test_vae

## Expected behavior

The test will test in autograd mode and in JIT Autodiff mode, the autograd mode works fine, but the JIT autodiff second derivative gives the above error, which I think it related to our autodiff infrastructure early release one of the leaf Variable

**Comment by albanD** [comment] 2019-10-16 19:29
After some investigation, a minimal example to reproduce is the following:

```python
import torch
from torch import nn
import torchviz

class VAE(nn.Module):
    def __init__(self):
        super(VAE, self).__init__()

        self.fc1 = nn.Linear(2, 3)
        self.fc4 = nn.Linear(3, 4)

    def forward(self, x):
        x = self.fc1(x)
        x = self.fc4(x)
        print(x.size(), x.grad_fn, x.requires_grad)
        x = x**2
        return x.sum()


inp = torch.rand(1, 2).double()

model = VAE()
model.double()

print("Tracing")
ge = torch.jit.trace(model, (inp,))
print("Tracing done")

def get_grad_sum(*params):
    with torch.no_grad():
        for p_val, p in zip(params, model.parameters()):
            p.copy_(p_val)
    out = ge(inp)

    print(ge.code)

    gs = torch.autograd.grad(out, model.parameters(), create_graph=True)

    s = 0
    for g in gs:
        s += g.sum()
        print("grad", g.size())
    torchviz.make_dot(s).view()

    return s

s = get_grad_sum(*list(model.parameters()))
print("FW/BW ok")
torch.autograd.grad(s, model.parameters()) # Fails here
print("RUNS OK")

torch.autograd.gradcheck(get_grad_sum, list(model.parameters()))
print("GRAD CHECK OK")
```

By adding some printing in the graph executor [here](https://github.com/pytorch/pytorch/blob/b0f1b5c75740c285a61ff63b91cf93277a2d84ed/torch/csrc/jit/graph_executor.cpp#L338), It seems like the formulas that get computed are weird.
Here is a gist https://gist.github.com/albanD/3990b979f2e470d79ac9f1b96293e0bc with the full result of the printing.

Notice that the error comes from the Tensor of size `4x1` that is saved by the jit while no tensor in this code should have this size.
From what understand in the jit dumps, the backward  returns as %22 the transpose of the gradient it computed for some bias.

Also notice in the first forward that one linear is collapsed into a linear but the other is still expanded.

**Comment by bhosmer** [comment] 2019-12-12 06:53
Looks like it's fixed, @albanD's repro now runs to completion and prints GRAD CHECK OK - closing

**Closed by bhosmer** 2019-12-12 06:53 UTC
Labels: high priority, jit, triaged

**Comment by albanD** [comment] 2019-12-12 14:58
@zdevito was working on this. Is there a more general issue of fixing view returns from the symbolic diff? 
Maybe because of some internal changes, this does not happen anymore on this particular repro.

**Comment by bhosmer** [comment] 2019-12-12 16:27
> @zdevito was working on this. Is there a more general issue of fixing view returns from the symbolic diff?

Ah not sure, maybe Zach has more info

**Comment by wanchaol** [comment] 2019-12-12 23:02
We can close this issue to reduce duplication, but the underlying problem is not fixed yet. @albanD https://github.com/pytorch/pytorch/issues/20734 is a more general issue of fixing view returns from symbolic diff.
