### ISSUE TITLE
[ONNX] Export fails for aten::normal with argument types: Tensor, float, float, None, 

### ISSUE THREAD

**Issue by paulgavrikov** [pytorch/pytorch#51010] opened 2021-01-24 12:15 UTC
## Issue description

When trying to export any model from https://github.com/rosinality/stylegan2-pytorch I run into the following error:

```
RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::normal but it isn't a special case.  Argument types: Tensor, float, float, None, 
root@a0835aae1b85:/data/model_conversion/stylegan2-pytorch# python3 convert.py 
loading stylegan2-car-config-e.pt
/data/model_conversion/stylegan2-pytorch/model.py:261: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out = F.conv2d(input, weight, padding=self.padding, groups=batch)
/data/model_conversion/stylegan2-pytorch/model.py:246: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  out = F.conv_transpose2d(input, weight, padding=0, stride=2, groups=batch)
Traceback (most recent call last):
  File "convert.py", line 51, in <module>
    opset_version=11)  # store the trained parameter weights inside the model
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py", line 276, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 92, in export
    use_external_data_format=use_external_data_format)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 686, in _export
    dynamic_axes=dynamic_axes)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 454, in _model_to_graph
    dynamic_axes=dynamic_axes, input_names=input_names)
  File "/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py", line 135, in _optimize_graph
    torch._C._jit_pass_onnx_remove_inplace_ops_for_onnx(graph)
RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::normal but it isn't a special case.  Argument types: Tensor, float, float, None, 

```

## System Info
```
PyTorch version: 1.8.0.dev20210123
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce RTX 2080 Super with Max-Q Design
Nvidia driver version: 460.32.03
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.0.dev20210123
[pip3] torchvision==0.9.0.dev20210123
[conda] Could not collect
```

cc @gmagogsfm @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by gmagogsfm** [comment] 2021-01-28 00:08
@BowenBao, @spandantiwari could you help take a look? Thanks!

**Comment by KsenijaS** [comment] 2021-02-01 23:39
@paulgavrikov can you please share your export script?

**Comment by paulgavrikov** [comment] 2021-02-02 13:18
@KsenijaS:  Inside the above mentioned repo:
```
import os
import numpy as np
import torch.onnx
from model import Generator


if __name__ == "__main__":

        size = 512
        channel_multiplier = 1

        g = Generator(size, 512, 8, channel_multiplier=channel_multiplier)
        # g.load_state_dict(state_dict.get("g"))

        batch_size = {256: 16, 512: 9, 1024: 4}
        n_sample = batch_size.get(size, 25)
        z = np.random.RandomState(0).randn(n_sample, 512).astype("float32")

        gen_img = np.random.RandomState(0).random((n_sample, 3, size, size)).astype("float32")

        with torch.no_grad():
            # g.eval()

            filename = "model.onnx"
            torch.onnx.export(g,  # model being run
                              [torch.from_numpy(z)],  # model input (or a tuple for multiple inputs)
                              filename,  # where to save the model (can be a file or file-like object)
                              export_params=True,
                              opset_version=11)  # store the trained parameter weights inside the model
```

**Comment by KsenijaS** [comment] 2021-02-09 19:06
@paulgavrikov I looked at this model and I was able to repro the issue. After some debugging it look like this is a jit related issue.
aten::normal_is not handeled correctly: https://github.com/pytorch/pytorch/issues/51735

**Comment by spandantiwari** [comment] 2021-02-09 22:32
Closing this one, since the issue is being tracked in https://github.com/pytorch/pytorch/issues/51735.

**Closed by spandantiwari** 2021-02-09 22:32 UTC
Labels: module: onnx, triaged

**Comment by Mishra1995** [comment] 2022-08-08 12:58
Facing the same issue when trying to convert pretrained GAN model to ONNX.

[*** RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::normal but it isn't a special case.  Argument types: Tensor, float, float, None,]

Any update on the same?

**Comment by Mephisto405** [comment] 2022-10-05 16:37
Facing the same issue when trying to convert pretrained [CAGAN](https://openaccess.thecvf.com/content/CVPR2021/papers/Liu_Content-Aware_GAN_Compression_CVPR_2021_paper.pdf) model to ONNX.

`RuntimeError: 0 INTERNAL ASSERT FAILED at "/pytorch/torch/csrc/jit/ir/alias_analysis.cpp":532, please report a bug to PyTorch. We don't have an op for aten::normal but it isn't a special case.  Argument types: Tensor, float, float, None,`

Any update on the same?
