### ISSUE TITLE
copy_ doesn't allow NumPy arguments, += does

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#34308] opened 2020-03-05 16:17 UTC
```python
import torch
import numpy as np

a = torch.zeros(3)
b = np.zeros(3)

a += b # works

a.copy_(b) # doesn't work
#   File "bug.py", line 8, in <module>
#    a.copy_(b) # doesn't work
#TypeError: copy_(): argument 'other' (position 1) must be Tensor, not numpy.ndarray
```

The relevant discussion is probably here: https://github.com/pytorch/pytorch/issues/22402 https://github.com/pytorch/pytorch/issues/28361  https://github.com/pytorch/pytorch/pull/34303 https://github.com/pytorch/rfcs/pull/3

**Comment by mruberry** [comment] 2020-05-11 23:44
Dupe of https://github.com/pytorch/pytorch/issues/11695.

**Closed by mruberry** 2020-05-11 23:44 UTC
Labels: enhancement, module: numpy, module: operators, triaged
