### ISSUE TITLE
Native implementation of convolution for complex numbers

### ISSUE THREAD

**Issue by onkyo14taro** [pytorch/pytorch#52983] opened 2021-02-28 15:09 UTC
## 🚀 Feature

Native implementation for convolution functions for **complex** tensors (torch.complex32, torch.complex64, torch.complex128).  
The convolution functions are as follows:
```
torch.conv1d
torch.conv2d
torch.conv3d
torch.conv_transpose1d
torch.conv_transpose2d
torch.conv_transpose3d
```

## Motivation

Complex networks have received more attention since the paper "[Deep complex networks](https://arxiv.org/abs/1705.09792)" was published. PyTorch has already been working on complex network implementation.
https://pytorch.org/docs/stable/complex_numbers.html

However, **even though complex convolution is the most used of the complex networks, convolution functions are not yet supported for complex numbers** (See the bottom for current issues). Therefore, at present, complex convolution can only be realized by a combination of real convolutions. This causes the following problems:

1. There are various implementations of complex convolution by real convolution in disarray, and they are not compatible with each other.
   * For example, splitting the real and imaginary parts into separate tensors, combining the real and imaginary parts in the dimension of the channel, adding a dimension for the real and imaginary parts, and so on.
2. The implementation of complex convolution by combining real convolutions is considered to be inferior to native complex convolution in terms of performance.

I think that once complex convolution is implemented natively, PyTorch will be more actively used for research on complex neural networks.

## Pitch

It is desirable to be able to perform convolutional forward and back propagation on both CPUs and GPUs natively for complex tensors.

## Additional context

Currently, when convolution is executed on a complex tensor, the following RuntimeError is thrown.

Environments:
```
Mac/CPU

Python 3.9.0

torch 1.7.1
```

Snippet:
```python
import torch

input = torch.rand(5, 4, 16, 16, dtype=torch.complex64)
input.requires_grad_()
weight = torch.rand(8, 4, 3, 3, dtype=torch.complex64)
torch.nn.functional.conv2d(input, weight)
```

Error massages:
```python
RuntimeError                              Traceback (most recent call last)
<ipython-input-165-cf21b40be359> in <module>
      3 input = torch.rand(5, 4, 16, 16, dtype=torch.complex64)
      4 weight = torch.rand(8, 4, 3, 3, dtype=torch.complex64)
----> 5 torch.nn.functional.conv2d(input, weight)

RuntimeError: "unfolded2d_copy" not implemented for 'ComplexFloat'
```

Perhaps it is necessary to implement more than `unfolded2d_copy`, such as back propagation of convolution.

I checked, and it seems that `unfolded2d_copy` is defined only for floating-point types in the following script (sorry, I was not sure how to extend this to complex types).
https://github.com/pytorch/pytorch/blob/22a34bcf4e5eaa348f0117c414c3dd760ec64b13/aten/src/ATen/native/cpu/Unfold2d.cpp

cc @ezyang @anjali411 @dylanbespalko @mruberry

**Comment by ngimel** [comment] 2021-03-01 03:56
`unfolded2d_copy` is part of native convolution implementation that is typically pretty slow. Absent complex convolution implementation in the backend libraries pytorch relies on (cudnn, OneDNN), the path to fastest complex convolutions would still probably lie through separate real-imaginary implementations (with all the problems mentioned above) rather than through enabling folding and unfolding in the native path.

**Comment by onkyo14taro** [comment] 2021-03-01 12:13
> `unfolded2d_copy` is part of native convolution implementation that is typically pretty slow. Absent complex convolution implementation in the backend libraries pytorch relies on (cudnn, OneDNN), the path to fastest complex convolutions would still probably lie through separate real-imaginary implementations (with all the problems mentioned above) rather than through enabling folding and unfolding in the native path.

I did not know about that. Thanks for the technical advice.

Following your advice, how about formally providing convolution layer classes that accept complex tensors (e.g., torch.complex64) as input, although internally it is implemented as a combination of real convolutions?
I think that providing an official interface can help unify implementation variations.

**Comment by ngimel** [comment] 2021-03-01 18:57
cc @anjali411 for plans on adding complex support to convolutions.

**Comment by anjali411** [comment] 2021-03-02 15:11
Hi @onkyo14taro thanks for filing this issue. As Natalia pointed out that it's difficult for us to provide "true complex" support while the backend libraries that pytorch relies on (cudnn, OneDNN) don't support complex number. But even so, it seems like there's no community consensus on what's the best approach for writing complex neural nets -- treating real and imaginary values as two independent channels and using real operations on them or using true complex operations. There's a similar discussion on https://github.com/pytorch/pytorch/issues/46374
cc. @boeddeker @mmuckley who have been worked on complex valued neural nets for thoughts

**Comment by mmuckley** [comment] 2021-03-02 20:34
On the fastMRI project we've always done the separate real/imaginary thing, and it works pretty well for our applications. However, I think for an official implementation it would be good to have true complex operations under the hood. From a mathematical and signal processing perspective there will be cases when you want to design complex filters that are able to explicitly work with the phase of a signal.

For our projects it's no issue if PyTorch supports true complex operations - our code right now will be backwards-compatible and people can pretty easily write new code to separate real/imaginary channels.

**Comment by onkyo14taro** [comment] 2021-03-03 16:20
@anjali411
Thank you for sharing the relevant Issue #46374. I think the current issue is the one contained in #46374.

@mmuckley
I felt that fastMRI's code is sophisticated and handles complex numbers with care. I feel it would be useful if the functions in your project are officially supported for complex types by PyTorch.

Apparent complex networks with complex tensor parameters and complex tensor input and output might be possible with the current backend library. For example, the following code worked as intended on CUDA. Since `F.linear()` does not support complex types, it is processed by dividing it into real and imaginary parts.


Environments
```
Python version: 3.8 (64-bit runtime)

[pip3] numpy==1.20.1
[pip3] pytorch-lightning==1.2.1
[pip3] torch==1.7.1+cu101
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2+cu101
```

Snippets
```python
import torch
import torch.nn as nn
import torch.nn.functional as F


class ComplexLinear(nn.Module):
    def __init__(self, in_features:int, out_features:int, bias:bool=True, contiguous:bool=True):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.contiguous = contiguous
        self.weight = nn.Parameter(torch.complex(torch.Tensor(out_features, in_features),
                                                 torch.Tensor(out_features, in_features)))
        if bias:
            self.bias = nn.Parameter(torch.complex(torch.Tensor(out_features),
                                                   torch.Tensor(out_features)))
        else:
            self.register_parameter('bias', None)
        self.reset_parameters()

    def reset_parameters(self):
        nn.init.kaiming_normal_(self.weight)
        if self.bias is not None:
            nn.init.zeros_(self.bias)

    def forward(self, x):
        return _apply_linear_complex(F.linear, x, self.weight, self.bias, self.contiguous)


def _apply_linear_complex(linear_fn, x, weight, bias, contiguous=True):
    x_r, x_i = x.real, x.imag
    w_r, w_i = weight.real, weight.imag
    b_r, b_i = (None, None) if bias is None else (bias.real, bias.imag)
    y_rr = linear_fn(x_r, w_r, b_r)
    y_ir = linear_fn(x_i, w_r, b_r)
    y_ri = linear_fn(x_r, w_i, b_i)
    y_ii = linear_fn(x_i, w_i, b_i)
    return torch.complex(y_rr-y_ii, y_ir+y_ri)
```

**Comment by mmuckley** [comment] 2021-03-03 17:12
@onkyo14taro, it might be reasonable to alter fastMRI to use complex operations in the future. However, I do want to draw a distinction: fastMRI's goal is not to be a library, but rather a reference for reproducing experiments in publications associated with the project and example data loaders for working with the project data. Keeping in this mind our most likely switch to complex operations would be if a new fastMRI publication used them.

**Comment by onkyo14taro** [comment] 2021-03-05 13:27
@mmuckley, I don't think our goal is to make fastMRI into a library, as you say.  I think it's important that the PyTorch official ecosystem supports a wide range of complex operations, even if internally it's a combination of real operations.

**Comment by pfeatherstone** [comment] 2021-07-09 11:54
> `unfolded2d_copy` is part of native convolution implementation that is typically pretty slow. Absent complex convolution implementation in the backend libraries pytorch relies on (cudnn, OneDNN), the path to fastest complex convolutions would still probably lie through separate real-imaginary implementations (with all the problems mentioned above) rather than through enabling folding and unfolding in the native path.

How about implementing complex convolution/cross-correlation using FFTs? cuFFT would do the job on NVIDIA GPU and FFTW/MKL would do the job on CPU

**Comment by pfeatherstone** [comment] 2021-07-09 11:55
And it's not like you would have to do giant FFTs, you can do FFT based convolution using the overlap-add method.

**Comment by pfeatherstone** [comment] 2021-07-09 12:00
Also, does cuBLAS not implement ```cblas_cgemm()``` or ```cblas_zgemm``` ?

**Comment by onkyo14taro** [comment] 2021-07-16 12:35
@pfeatherstone Sorry for the late reply.

Thank you for pointing out the possibility of computing with FFTs (sorry, I am not familiar with the backend functions).
Your idea is interesting.

However, I am concerned about the computational error in the results with and without FFT.
If only complex convolution is implemented with FFT, it will be asymmetric to the current implementation of real convolution without FFT.
To solve the asymmetry, we need to be able to choose whether to use FFT or not when computing the real convolution.

**Comment by ngimel** [comment] 2021-07-16 15:50
cuFFT is not optimized for configurations that naturally arise in convolutions, when cudnn was implementing fft algorithm, they had to have special implementation that works for convolutions. And yes, it produced less accurate results then regular, gemm-based implementations do. 
Cublas does implement cblas_cgemm, but it is not very helpful, because for real numbers, unfold + gemm implementation is much slower than optimized implementations from OneDNN or cudnn.

**Comment by pfeatherstone** [comment] 2021-07-16 15:55
I don't know how people implement their convolutions with FFTs, but if you're doing it right, i.e. using appropriate zero padding to avoid circular convolution, then you should be getting identical results to a manual convolution. They are mathematically equivalent. If people are getting inconsistencies, then it's probably because incorrect padding is used. Also it could be because people are getting confused between convolution and cross-correlation. In the Fourier/spectral domain. that means a complex conjugate is possible taken or not taken depending on the operation.

**Comment by pfeatherstone** [comment] 2021-07-16 15:56
So if people just do:
A * B = iFFT(FFT(A) x FFT(B))
then you get bad results because if your FFT is wrapping.

**Comment by ngimel** [comment] 2021-07-16 15:58
They are mathematically equivalent, correct, but floating point computations are different, and the error accumulated with fft + gemm + ifft  approach is typically much larger.

**Comment by pfeatherstone** [comment] 2021-07-16 16:00
What is the order of magnitude of the error? Are we down at the error of the mantissa or larger?

**Comment by pfeatherstone** [comment] 2021-07-16 16:01
so if my inputs are in range [0,1] what is the typical error using cudnn conv vs FFT method ?

**Comment by pfeatherstone** [comment] 2021-07-16 16:02
if we are down to 1e-16 then it doesn't matter and it's worrying if one's model is sensitive at that magnitude, the model is probably overfitting anyway.

**Comment by ngimel** [comment] 2021-07-16 16:08
Getting reasonable estimates an "expected" error in convolution computation is a surprisingly non-trivial task that depends on input sizes, but numerical errors for typical sizes with gemm-based are 1e-4 - 1e-5, and for fft 1e-2 - 1e-3. One thing that has been an issue for some people is fft-based approach doesn't preserve the invariant that if both your image and filter are non-negative, the result will also be non-negative - it is easy to get small negative values. 
Of course, using double precision for computations will greatly reduce the error, but it also is very slow.

**Comment by pfeatherstone** [comment] 2021-07-16 16:10
okayyyy. I still find it hard to believe FFT based methods have errors in range 1e-2 - 1e-3. I use FFT based convolutions in signal processing all the time [FIR filters], and the results are almost identical to  manual convolutions. And that's using single precision floating point arithmetic and inputs in range [-1-1j,1+1j]

**Comment by pfeatherstone** [comment] 2021-07-16 16:26
So just did a quick test where i filtered a random array of complex valued samples (single precision) in range [-1-1j, +1+1j] with a kaiser-windowed sinc filter, using manual convolution and FFT convolution, and the errors are of the order of 10^-9. So that's -90dB floating point error noise floor. That's pretty low

**Comment by pfeatherstone** [comment] 2021-07-16 16:26
So i don't know how people are getting errors of the order of 10^-2, That's crazy

**Comment by onkyo14taro** [comment] 2021-07-16 16:45
Thank you, @ngimel  and @pfeatherstone, for the interesting discussion on numerical errors.

I was surprised that the numerical error could be as high as 1e-2, but the larger the input size, the larger the error as you say.
I think that sum operations (included in convolution, FFT, and IFFT) can be a major factor in producing large errors.
If we use half-precision arithmetic, the error is likely to be even larger.

This is a bit of a digression, but I remembered that when I used the [Gauss trick](https://en.wikipedia.org/wiki/Multiplication_algorithm#Complex_multiplication_algorithm) (lowering the number of convolution) to improve the efficiency of complex calculations, there was a large numerical error between two mathematically equivalent operations.
My memory of that time is fuzzy, but I think it resulted in an error of about 1e-3 or 1e-4.

I myself have been studying time-frequency representation, and I feel that @pfeatherstone thought is interesting.
However, from the point of view of numerical errors and computational speed pointed out by @ngimel, I understand that it is better to avoid implementing convolution based on FFT and IFFT in the current situation.

**Comment by ngimel** [comment] 2021-07-16 16:54
It's still an interesting experiment and someone has done it for 1d https://programmersought.com/article/58147632817/. There are definitely advantages to using fft, but it's not a silver bullet. 
Half-precision complex number support is almost non-existent, so that's a problem to solve for the future.

**Comment by pfeatherstone** [comment] 2021-07-16 17:11
```
    def fft_conv(x, y):
        x_h, x_w = x.shape[-2:]
        y_h, y_w = y.shape[-2:]
        c_h, c_w = x_h + y_h - 1, x_w + y_w - 1

        x = F.pad(x, (0, c_w - x_w, 0, c_h - x_h))
        y = F.pad(y, (0, c_w - y_w, 0, c_h - y_h))
        X = torch.fft.fft2(x, [-1,-1])
        Y = torch.fft.fft2(y, [-1,-1])
        C = X * Y.conj()
        c = torch.fft.ifft2(C, [-1,-1], norm="backward")
        return c.real

    x = torch.randn(1024, 1024)
    y = torch.randn(16, 16)
    c1 = F.conv2d(F.pad(x, (0,30,0,30)).unsqueeze(0).unsqueeze(0), y.unsqueeze(0).unsqueeze(0)).squeeze(0).squeeze(0)
    c2 = fft_conv(x,y)
```

Did a quick test in pytorch. I get differences of the order of 10^-6

**Comment by pfeatherstone** [comment] 2021-07-16 17:14
That might not be a correct function. I quickly wrote that.

**Comment by pfeatherstone** [comment] 2021-07-16 17:32
```
    def fft_conv(x, y):
        x_h, x_w = x.shape[-2:]
        y_h, y_w = y.shape[-2:]
        c_h, c_w = x_h + y_h - 1, x_w + y_w - 1

        x = F.pad(x, (0, c_w - x_w, 0, c_h - x_h))
        y = F.pad(y, (0, c_w - y_w, 0, c_h - y_h))
        X = torch.fft.fft2(x)
        Y = torch.fft.fft2(y)
        C = X * Y.conj()
        c = torch.fft.ifft2(C, norm="backward")
        return c.real

    x = torch.randn(1024, 1024)
    y = torch.randn(16, 16)
    c1 = F.conv2d(F.pad(x, (0,2*(y.shape[-1]),0,2*(y.shape[-1]))).unsqueeze(0).unsqueeze(0), y.unsqueeze(0).unsqueeze(0)).squeeze(0).squeeze(0)
    c2 = fft_conv(x,y)
    c1 = c1[0:x.shape[-2],0:x.shape[-2]]
    c2 = c2[0:x.shape[-2],0:x.shape[-2]]
    print(((c1 - c2) ** 2).mean())
    print(c1.shape)
```

no quite sure what i've done wrong and why i have to truncate back to the size of ```x``` but i get a mean squared error of ~10^-10

**Comment by pfeatherstone** [comment] 2021-07-16 17:35
Of course this doesn't take into account groups, stride, dilation and what not but in a simple case, the error being 10^-10 is not bad

**Comment by pfeatherstone** [comment] 2021-07-17 09:08
OK so i had another play around with the code i posted. It turns out the error is always attributed to the mantissa precision, which isn't entirely surprising.

Here is a final demo snippet:
```
    def fft_conv(x, y):
        x_h, x_w = x.shape[-2:]
        y_h, y_w = y.shape[-2:]
        c_h, c_w = x_h + y_h - 1, x_w + y_w - 1

        x = F.pad(x, (0, c_w - x_w, 0, c_h - x_h))
        y = F.pad(y, (0, c_w - y_w, 0, c_h - y_h))
        X = torch.fft.fft2(x)
        Y = torch.fft.fft2(y)
        C = X * Y.conj()
        c = torch.fft.ifft2(C, norm="backward")
        return c.real


    x = torch.randn(1024, 1024) * 100
    y = torch.randn(16, 16) * 100
    c1 = F.conv2d(F.pad(x, (0, 2 * (y.shape[-1]), 0, 2 * (y.shape[-1]))).unsqueeze(0).unsqueeze(0),
                  y.unsqueeze(0).unsqueeze(0)).squeeze(0).squeeze(0)
    c2 = fft_conv(x, y)
    c1 = c1[0:x.shape[-2], 0:x.shape[-2]]
    c2 = c2[0:x.shape[-2], 0:x.shape[-2]]

    mse = ((c1 - c2) ** 2).mean()
    c1_mantissa = torch.frexp(c1)[0]
    c2_mantissa = torch.frexp(c2)[0]
    mse_mantissa = ((c1_mantissa - c2_mantissa) ** 2).mean()

    print(mse)
    print(mse_mantissa)
```

Yes, the MSE in this case is of the order of 10^-2 but the mantissa MSE is of the order of 10^-6.
But this will be the case for any algorithm that is slightly different. I bet the different versions of CUDNN's convolution algorithms exhibit similar errors...

This is only really a problem if you let your intermediate outputs grow boundlessly. If you use appropriate activation functions, this isn't a problem. Moreover, one could argue that having imprecision is a useful regularizer ! 
Anybody have any thoughts on this?

I don't think it's fair to say that an FFT version would be bad. For the same reasons people would argue against an FFT version, i would throw back at them for using single precision convs instead of double precision convs. 

What we can say, is that an FFT version would immediately give a backend version for complex valued convolutions in pytorch. People could start using them now. Then one day, when cudnn, mlkdnn and the rest finally decide to implement complex valued convs, pytorch can update its backend without the user being any the wiser.

**Comment by divideconcept** [comment] 2021-07-17 09:42
I must say I'm seduced by this idea of FFT convolution for complex tensors. It might not be perfect, but it's a working solution nonetheless. Right now we can't do much in deep learning with complex tensors without this brick.

**Comment by pfeatherstone** [comment] 2021-07-17 14:24
The other solution is that you do what https://github.com/ivannz/cplxmodule or https://github.com/soumickmj/pytorch-complex do, where complex convolution is split into 4 separate convolutions. Indeed:
```
z1 * z2 = [r1 * r2 - i1 * i2] + i [r1 * i2 + r2 * i1]
```
This works fine, but it requires a lot more memory. So much so that you have to come up with tricks to reduce the number of channels or your kernel sizes, which isn't necessarily desirable. It would be nice if ```complex<float>``` operations required no more memory than ```double``` operations.

**Comment by divideconcept** [comment] 2021-07-17 15:54
Indeed I've heard of this trick, but I don't like it much. Looks slow, and memory hungry as you mentioned. The FFT solution seems more elegant. It would be worth testing if the error actually hurts the learning/inference process, or if it's negligible.

**Comment by pfeatherstone** [comment] 2021-07-17 15:58
I think so long as you use sensible activation functions such that values don't explode, maybe something like ```torch.sigmoid()```, then you're fine. As I showed above, the mantissa MSE is **always** low, but as your exponent increases so does the combined MSE. So if you keep your exponent low, i.e. have a sensible upper bound on your tensors, then you're fine.

**Comment by onkyo14taro** [comment] 2021-07-22 05:38
@pfeatherstone, thank you for providing some example codes. The numerical error was small in your example.

If we test the practicality, we will use the following algorithm and comparison items.

### Algorithms

Let the input be `x := a + ib` and the weitht be `w := c + id`.

1. Naive (4 convolution & 2 addition/subtraction, `*` denotes convolution):
   ```
   (a + ib) * (c + id) = (a * c - b * d) + i(a * d + b * c)
   ```
2. FFT/IFFT trick (`*` denotes Hadamard product):
   ```
   IFFT(FFT(x) * FFT(w))
   ```
3. Gauss' trick (3 convolution & 5 addition/subtraction, `*` denotes convolution): 
   ```
   (a + ib) * (c + id) = (k1 + k3) + i(k2 - k3)
   k1 = (a - b) * d
   k2 = (a + b) * c
   k3 = (c - d) * a
   ```

### Comparative items

The following items are compared for the CPU and GPU respectively:

* Computation error
* Speed
* Memory efficiency

**Comment by CerebralSeed** [comment] 2022-01-05 10:02
For anyone looking, here is a class definition that will combine real and imaginary on the fly:

```
class CombComp(nn.Module):
    def __init__(self):
        super(CombComp, self).__init__()
    def forward(self, r, i):
        return torch.view_as_complex(torch.cat([r.unsqueeze(-1), i.unsqueeze(-1)], dim=-1))
```

And here is a simple example used with Conv2d(although this will work with any Conv):

```

combiner=CombComp()
convlayer_real=nn.Conv2d(3, 16, (3,3))
convlayer_imag=nn.Conv2d(3, 16, (3, 3))

A=torch.rand(10, 3, 32, 32, dtype=torch.cfloat)

A_real=convlayer_real(A.real)
A_imag=convlayer_imag(A.imag)

A=combiner(A_real, A_imag)
```

**Comment by ni-chen** [comment] 2022-01-11 10:54
> C = X * Y.conj()

Hi, may I ask why do you use conj()?

**Comment by ngimel** [comment] 2022-02-07 19:28
closing in favor of #71108

**Closed** 2022-02-07 19:31 UTC
Labels: module: convolution, triaged, module: complex
