### ISSUE TITLE
Enable functorch testing for rocm

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#96560] opened 2023-03-10 22:14 UTC
While trying to enable functorch testing for rocm I see a couple of failures. Putting this issue up to track.

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @Chillee @samdow @soumith @kshitij12345 @janeyx99

**Comment by jeffdaily** [comment] 2023-03-10 23:59
Do you have a branch or log to share?

**Comment by malfet** [comment] 2023-03-14 17:55
@zou3519 on the other hand, once you move functorch to regular shards, it would be done automatically

**Comment by pruthvistony** [comment] 2024-05-14 16:40
PR - https://github.com/pytorch/pytorch/issues/96560 addresses few failures.

**Comment by alugorey** [comment] 2024-05-16 16:36
A large portion of these failures have been addressed as of this PR:
https://github.com/pytorch/pytorch/pull/125069

There are just a few lingering items related to scaled dot product attention that will be fixed in a future PR

**Comment by alugorey** [comment] 2024-06-05 22:31
Hi @zou3519 
The next batch of unit tests enabled under this umbrella are coming in here: https://github.com/pytorch/pytorch/pull/127966

With that PR, there is only once instance of the issue being referenced left. The test in question is:
test_vmap_autograd_grad_xlogy_cuda_float32

It fails with the following error:


		AssertionError: Tensor-likes are not close!
		
		Mismatched elements: 2 / 2 (100.0%)
		Greatest absolute difference: 0.00018310546875 at index (0,) (up to 1e-05 allowed)
		Greatest relative difference: 2.1878790903429035e-06 at index (0,) (up to 1.3e-06 allowed)
                Exception: Caused by sample input at index 3: SampleInput(input=Tensor[size=(10, 5), device="cuda:0", 
                dtype=torch.float32], args=TensorList[Tensor[size=(), device="cuda:0", dtype=torch.float32]], kwargs={}, broadcasts_input=False, name='')                                                                                                                                                          
                To execute this test, run the following from the base repo dir:                                                                        
                PYTORCH_TEST_WITH_ROCM=1 python test/functorch/test_ops.py -k 
                TestOperatorsCUDA.test_vmap_autograd_grad_xlogy_cuda_float32                                                                                                                                        
                This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0 

The test runs through a number of test cases with no problem but eventually fails when the following value comparisons are encountered in the output tensors
-83.6907 != -83.6909

Off by .0002

I reiterate, there are several hundred other values that go through this test with no problem at all.

I did some digging and found that the xlogy kernel (defined in pytorch/aten/src/ATen/native/BinaryMiscOpsKernels.cu) is affected by a particular limitation thanks to hipification. It is part of a special mapping (https://github.com/pytorch/pytorch/blob/main/torch/utils/hipify/cuda_to_hip_mappings.py#L35) that is required for certain math functions in ROCm device code. Looking at the hipify_python.py code, we see this:


        FIXME: Temporarily replace std:: invocations of math functions
        with non-std:: versions to prevent linker errors NOTE: This
        can lead to correctness issues when running tests, since the
        correct version of the math function (exp/expf) might not get
        called.  Plan is to remove this function once HIP supports
        std:: math function calls inside device code
https://github.com/pytorch/pytorch/blob/main/torch/utils/hipify/hipify_python.py#L473-L479


So looks like on the final test, we are just hitting this minor correctness issue due to not being able to call std::log(y) on ROCm yet and instead calling ::log(y). I propose to either loosen the tolerance on ROCm for f32 or update the skip message to point to this comment. Or both.

**Comment by zou3519** [comment] 2024-06-05 23:22
@alugorey I don't have a preference, either or both sound good to me.

**Comment by naromero77amd** [comment] 2024-11-18 22:02
@zou3519 Is there still an open issue?

We will plan to close in week unless there is an update.

**Comment by zou3519** [comment] 2024-11-19 17:13
There are some (<5) miscellaneous skipIfRocms remaining:
- https://github.com/pytorch/pytorch/blob/main/test/functorch/test_eager_transforms.py#L5143
- https://github.com/pytorch/pytorch/blob/main/test/functorch/test_ops.py#L972-L973

But in general I'm happy with the progress so feel free to close this

**Closed** 2024-11-25 20:03 UTC
Labels: module: rocm, triaged, module: functorch
