### ISSUE TITLE
Exception: Could not run 'aten::channel_shuffle' with arguments from the 'CUDA' backend. 

### ISSUE THREAD

**Issue by beanduan22** [pytorch/pytorch#121208] opened 2024-03-05 07:11 UTC
### 🐛 Describe the bug

```
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.fft
import torch.distributions.transforms as transforms
import torch.optim


class PreprocessAndCalculateModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.avg_pool1d = nn.AvgPool1d(kernel_size=2)
        self.avg_pool3d = nn.AvgPool3d(kernel_size=(2, 2, 2))
        self.channel_shuffle = nn.ChannelShuffle(groups=3)


    def forward(self, x):
        device = x.device

        x = x.view(-1, 3, 32 * 32)

        x = self.avg_pool1d(x).to(device)

        x = self.channel_shuffle(x)

        # Reshape for AvgPool3d
        x = x.view(-1, 3, 8, 4, 4)
        x = self.avg_pool3d(x).to(device)

        # Apply various operations
        x = torch.diag(x.view(-1)).to(device)

        x = torch.div(x, 2).to(device)

        x.floor_divide_(2)

        x = torch.conj(x).to(device)

        x = torch.log2(x).to(device)

        # FFT operations
        x = torch.fft.rfft2(x).to(device)

        x_irfft2 = torch.fft.irfft2(x).to(device)

        used_apis_sorted = sorted(set(self.used_apis), key=self.used_apis.index)

        return x_irfft2

real_inputs = torch.rand(2, 3, 32, 32)

### Versions

Exception: Could not run 'aten::channel_shuffle' with arguments from the 'CUDA' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::channel_shuffle' is only available for these backends: [CPU, QuantizedCPU, BackendSelect, Python, FuncTorchDynamicLayerBackMode, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradMTIA, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, FuncTorchBatched, FuncTorchVmapMode, Batched, VmapMode, FuncTorchGradWrapper, PythonTLSSnapshot, FuncTorchDynamicLayerFrontMode, PythonDispatcher].


cc @ptrblck

**Comment by tringwald** [comment] 2024-03-05 09:54
Seems to be a duplicate of https://github.com/pytorch/pytorch/issues/65325. It also seems to already be fixed on newer PyTorch versions, as I can't reproduce the exception on `2.2.0` or newer.

**Closed** 2024-12-18 20:13 UTC
Labels: needs reproduction, module: cuda, triaged
