### ISSUE TITLE
Distributed Training shut down on second epoch

### ISSUE THREAD

**Issue by yingjianling** [pytorch/pytorch#11327] opened 2018-09-06 07:17 UTC
## Issue description

Hi, guys. I am trying to train a resnet model on single node and 8 GPUs with DistributedDataParallel. Every thing is ok during the first epoch. However, the script shut down without any error report when the second epoch starts. I have tried to track the code and find that the code stops at:
`for batch_idx, (data, label) in enumerate(train_loader, 0):`
Meanwhile, I create a small version dataset with 34 classes, and the error is gone.
Here is my command line:
`python -m torch.distributed.launch --nproc_per_node=8 train.py`
Any help will be appreciate.
## Code example
```
import argparse,os,time
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.distributed as dist
import torch.utils.data
import torch.utils.data.distributed
import torchvision
from torchvision import datasets, transforms
import numpy as np
import models
from util import *

parser = argparse.ArgumentParser()
parser.add_argument('--start_epoch', type=int, default=1, help='start epoch number')
parser.add_argument('--epoch', type=int, default=25, help='number of epochs to train for')
parser.add_argument('--lr', type=float, default=0.1, help='learning rate, default=0.1')
parser.add_argument('--momentum', type=float, default=0.9, help='momentum, default=0.9')
parser.add_argument('--weight_decay', type=float, default=0.0002, help='weight_decay, default=0.0002')
parser.add_argument('--batch_s', type=int, default=64, help='input batch size')
parser.add_argument('--grid_s', type=int, default=8, help='grid size')
parser.add_argument('--data', type=str, default='../vgg2data', help='data directory')
parser.add_argument('--workers', type=int, default=1, help='number of data loading workers')
parser.add_argument('--output_dir', type=str, default='./output/', help='model_saving directory')
parser.add_argument('--resume', type=str, default='', help='resume')
parser.add_argument("--display_interval", type=int, default=50)
parser.add_argument("--local_rank", type=int)
opt = parser.parse_args()
torch.cuda.set_device(opt.local_rank)

dist.init_process_group(backend='nccl', init_method='env://', world_size=8)

train_dir = os.path.join(opt.data, 'train')
train_dataset = datasets.ImageFolder(
    train_dir,
    transforms.Compose([transforms.ToTensor()])
)
train_sampler = torch.utils.data.distributed.DistributedSampler(train_dataset)
train_loader = torch.utils.data.DataLoader(
        train_dataset,
        batch_size=opt.batch_s,
        num_workers=opt.workers,
        pin_memory=True,
        shuffle=False,
        sampler=train_sampler
    )

input_size = (opt.batch_s, 3, 128, 128)
num_classes = 9092
#num_classes = 34
model = models.se_resnet34_v3(input_size, opt.grid_s, num_classes)
if opt.resume:
    if os.path.isfile(opt.resume):
        print("=> loading checkpoint '{}'".format(opt.resume))
        checkpoint = torch.load(opt.resume)
        model.load_state_dict(checkpoint['state_dict'])
        print("=> loaded checkpoint '{}' (epoch {})"
            .format(opt.resume, checkpoint['epoch']))
model.cuda()
model = torch.nn.parallel.DistributedDataParallel(model,\
    device_ids=[opt.local_rank], output_device=opt.local_rank)

optimizer = optim.SGD([
        {'params': get_parameters(model, bias=False)},
        {'params': get_parameters(model, bias=True), 'lr':opt.lr * 2, 'weight_decay': 0},
        {'params': get_parameters(model, bn=True), 'lr':opt.lr * 1.00001001358, 'weight_decay':0}
    ], lr=opt.lr, momentum=opt.momentum, weight_decay=opt.weight_decay)
if opt.resume:
    if os.path.isfile(opt.resume):
        checkpoint = torch.load(opt.resume)
        optimizer.load_state_dict(checkpoint['optimizer'])

scheduler = optim.lr_scheduler.MultiStepLR(optimizer, \
    milestones=[8,15,18], gamma=0.5)

def train(epoch):
    for batch_idx, (data, label) in enumerate(train_loader, 0):
        optimizer.zero_grad()
        data, label = data.cuda(), label.cuda()
        output, grid = model(data)
        nll_loss = F.nll_loss(output, label)
        de_loss = deformation_constraint_loss(grid, opt.grid_s)
        loss =  nll_loss + de_loss
        loss.backward()
        optimizer.step()
for epoch in range(opt.start_epoch, opt.epoch + 1):
    train_sampler.set_epoch(epoch)
    scheduler.step() 
    model.train()
    train(epoch)
```

## System Info
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 390.12
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.7.0.1
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda80                    1.0                  h205658b_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] pytorch                   0.4.1           py27_cuda8.0.61_cudnn7.1.2_1  [cuda80]  https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch
[conda] torchvision               0.2.1                    py27_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch

**Comment by teng-li** [comment] 2018-09-07 02:58
How many dataloaders do you have? If more than one, please use `fork_server` or `spawn` start method for `multiprocessing` Like this:
```
import torch.multiprocessing as mp

if __name__ == '__main__':
      mp.set_start_method('forkserver')
```

**Comment by teng-li** [comment] 2018-09-07 03:07
I think I have hit the exact same problem when using the default `fork` start method for multiprocessing

**Comment by yingjianling** [comment] 2018-09-07 06:07
Is there any difference between `multiprocessing.set_start_method('forkserver')` and `torch.multiprocessing.set_start_method('forkserver')`? I have tried the former and the dataloader still hangs  after one epoch.

**Comment by mruberry** [comment] 2018-09-07 17:17
Hey @yingjianling, can you make a version of this that I can reproduce? For example, is there a model in torchvision we can use instead of models.se_resnet34_v3? I would really like to investigate this for you.

**Comment by mruberry** [comment] 2018-09-07 20:45
I created the following snippet (below) to try and simplify and reproduce the issue, but it's working OK for me with 8 workers, 20 epochs, and a batch size of 100 . Is it possible that you're setting the higher number of classes incorrectly?

```
import argparse,os,time
import torch.multiprocessing as mp
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.distributed as dist
import torch.utils.data.distributed
import torchvision
from torchvision import datasets, transforms
import numpy as np

class MLPNet(nn.Module):
    def __init__(self):
        super(MLPNet, self).__init__()
        self.fc1 = nn.Linear(28*28, 500)
        self.fc2 = nn.Linear(500, 256)
        self.fc3 = nn.Linear(256, 10)

    def forward(self, x):
        x = x.view(-1, 28*28)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x
    
    def name(self):
        return "MLP"


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--start_epoch', type=int, default=1, help='start epoch number')
    parser.add_argument('--epoch', type=int, default=25, help='number of epochs to train for')
    parser.add_argument('--lr', type=float, default=0.1, help='learning rate, default=0.1')
    parser.add_argument('--momentum', type=float, default=0.9, help='momentum, default=0.9')
    parser.add_argument('--weight_decay', type=float, default=0.0002, help='weight_decay, default=0.0002')
    parser.add_argument('--batch_s', type=int, default=64, help='input batch size')
    parser.add_argument('--grid_s', type=int, default=8, help='grid size')
    parser.add_argument('--data', type=str, default='../vgg2data', help='data directory')
    parser.add_argument('--workers', type=int, default=1, help='number of data loading workers')
    parser.add_argument('--output_dir', type=str, default='./output/', help='model_saving directory')
    parser.add_argument('--resume', type=str, default='', help='resume')
    parser.add_argument("--display_interval", type=int, default=50)
    parser.add_argument("--local_rank", type=int)
    opt = parser.parse_args()

    torch.cuda.set_device(opt.local_rank)
    
    dist.init_process_group(backend='nccl', init_method='env://')

    trans = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (1.0,))])
    mnist = torchvision.datasets.MNIST(root="~/Documents/workspace/datasets/mnist", train=True, transform=trans, download=True)

    train_sampler = torch.utils.data.distributed.DistributedSampler(mnist)
    train_loader = torch.utils.data.DataLoader(
            mnist,
            batch_size=opt.batch_s,
            num_workers=opt.workers,
            drop_last=True,
            pin_memory=False,
            shuffle=False,
            sampler=train_sampler
        )

    model = MLPNet().cuda()
    criterion = nn.CrossEntropyLoss()
    model = torch.nn.parallel.DistributedDataParallel(model, device_ids=[opt.local_rank], output_device=opt.local_rank)
    optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)

    scheduler = optim.lr_scheduler.MultiStepLR(optimizer,
        milestones=[8,10,12,14,15,16,17,18,19,20,21,22,23,24], gamma=0.5)
    
    for epoch in range(opt.start_epoch, opt.epoch + 1):
        print(epoch)
        train_sampler.set_epoch(epoch)
        scheduler.step()
        for batch_idx, (x, target) in enumerate(train_loader):
          optimizer.zero_grad()
          x, target = x.cuda(), target.cuda()
          out = model(x)
          loss = criterion(out, target)
          loss.backward()
          optimizer.step()
```

**Comment by mruberry** [comment] 2018-09-07 22:06
fyi @mcarilli

**Comment by yingjianling** [comment] 2018-09-09 05:44
@mruberry Hi, this problem only happen when the dataset is large. I have tried MNIST dataset and a small version of vggface2 dataset with only 34 classes, and it's working ok. However, when I used a full version of vggface2 dataset, this error happend. 
By the way, I think using imagenet dataset with resnet model may reproduce this problem.

**Comment by yingjianling** [comment] 2018-09-09 05:57
@mcarilli I use `ls -l |grep "^d"|wc -l` to get the number of folders. I think mismatch may not be the reason, because when I use `num_workers=0` on the full version of vggface2 dataset which uses both train and test set to train the model, It's working ok.

**Comment by mcarilli** [comment] 2018-09-10 16:20
@yingjianling Ok, I'll try it with imagenet.  I may not have a chance today though.

**Comment by wangdongxuking61** [comment] 2018-09-13 09:37
i have the same problem when is

PyTorch version: 0.4.1
torchvision version: 0.2.1
OS: Ubuntu 16.04.3 LTS

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2
Nvidia driver version: 396.44
GPU models and configuration:
GPU 0: Tesla V100-SXM2
GPU 1: Tesla V100-SXM2

**Comment by mcarilli** [comment] 2018-09-13 16:11
@wangdongxuking61 Thank you, I'm running this locally now the Pytorch dockerhub container (version 0.4.1).  I do get an error at the end of the first epoch, but it's not silent:
```
ConnectionResetError: [Errno 104] Connection reset by peer
```
25 is an unusually large number of workers.  There's no point having more workers than the number of (logical) cores on the machine, right?

As an initial sanity check, I'm going to try two things:  1.  Run with fewer workers per process.  2. Run with top-of-tree pytorch.

**Comment by yingjianling** [comment] 2018-09-14 01:37
@mcarilli Thanks a lot for your reply. I'll try that.

**Comment by mcarilli** [comment] 2018-09-14 15:53
`docker pull pytorch/pytorch` pulls the official Pytorch container, created by Facebook people, which contains (as far as I know) Pytorch 0.4.1.

The 18.0* containers are Nvidia-created containers, available through Nvidia NGC.  They contain snapshots of Pytorch master that are updated on a rolling basis, but the snapshots in publicly available NGC containers tend to lag behind top of tree master by 1-2 months.  For example, the 18.09 container I just used to train successfully is not yet publicly available.

Because of this lag, IMO the best thing to try in your case is to pull the latest Pytorch master from Github and rebuild from source.  If you don't have NCCL or CuDNN installed on bare metal, pull `pytorch/pytorch:0.4.1-cuda9-cudnn7-devel`, which should contain the NCCL and CUDNN shared object libraries.   Within that container, you can uninstall the existing Pytorch (0.4.1) and recompile top of tree:
```
pip uninstall torch
git clone https://github.com/pytorch/pytorch.git
cd pytorch
python setup.py install
```
It'll take about 20 minutes to compile, but using a more recent Pytorch did help me, so maybe this will enable your use case.

**Comment by wangdongxuking61** [comment] 2018-09-14 16:15
> @wangdongxuking61 Thank you, I'm running this locally now the Pytorch dockerhub container (version 0.4.1). I do get an error at the end of the first epoch, but it's not silent:
> 
> ```
> ConnectionResetError: [Errno 104] Connection reset by peer
> ```
> 25 is an unusually large number of workers. There's no point having more workers than the number of (logical) cores on the machine, right?
> 
> As an initial sanity check, I'm going to try two things: 1. Run with fewer workers per process. 2. Run with top-of-tree pytorch.

Now I tell my story...

At first, I want to run apex/example/imagenet/main.py with `fp16` on my server(have 2 V100, 56 logical core).

But I always got the `ConnectionResetError: [Errno 104] Connection reset by peer`and `EOFError`

at the last several iterations in first epoch.

So I go to see the pytorch's issues about `dataloader.py` . The [issue 10366](https://github.com/pytorch/pytorch/pull/10366) is similar to mine. So i update `dataloader.py`to the latest version.  Then I got  `shut down on second epoch`error (maybe some other reason cause the error, i can't remembered clearly, because i do a lot attempt to avoid the `ConnectionResetError` error...). Then i report my problem at this issue. 

Today, I can't reproduce `shut down on second epoch` error again now, but i am sure i have met it. Now I only got the first error:`ConnectionResetError: [Errno 104] Connection reset by peer`and `EOFError`



So I do a lot tests...

|       | #server | #gpu per server | torch version(python3.6)                                 | batch size per gpu | float precision(not important) | result |
| ----- | ------- | --------------- | -------------------------------------------------------- | ------------------ | ------------------------------ | ------ |
| test1 | 1       | 2               | 0.4.1                                                    | 256                | fp16                           | error  |
| test2 | 1       | 2               | 0.4.0                                                    | 256                | fp16                           | OK     |
| test3 | 1       | 2               | 0.4.1+replace dataloader.py by latest one in top-of-tree | 256                | fp16                           | error  |
| test4 | 1       | 1/4/8           | 0.4.1                                                    | 8/16/32/64/128     | fp16/fp32                      | OK     |
| test5 | 2       | 1               | 0.4.1                                                    | 8/16/32/64/128     | fp16/fp32                      | error  |
| test6 | 2       | 2/4/8           | 0.4.1                                                    | 8/16/32/64/128     | fp16/fp32                      | OK     |

- Ps1: test1,2,3 are only tested on apex's DDP. test4,5,6 are tested on both `apex' DDP`and `torch.nn.parallel.DistributedDataParallel`. The result is unrelated with these two DDP.
- Ps2: i use mp.set_start_method('forkserver'), it is useless. And i also change python3.6 to 2.7,3.7, it is useless too...



the command is:

```bash
# test1
python -m torch.distributed.launch --nproc_per_node=2 main.py --fp16 --arch resnet18 --epochs 90 --workers 25 --batch-size=256 /imagenet

# test2 test3
# the same as test1

# test4
# should change: nproc_per_node, batch-size, --fp16

# test5, test6
# should change: nproc_per_node, batch-size, --fp16
python -m torch.distributed.launch --nproc_per_node=NUM_GPUS_YOU_HAVE --nnodes=2 --node_rank=0 --master_addr="192.168.1.1" --master_port=1234 main.py --fp16 --arch resnet18 --epochs 90 --workers 25 --batch-size=256 /imagenet
```

**My personal Conclusion, the error will only happen in a certain situation:**

- torch version >=0.4.1(related to dataloader.py)
- DDP process number=2(two gpus in 1 server, or 2 servers each have a gpu)

Another two pieces of information:

- `python torch-0.4.1/test/test_dataloader.py` will also cause `ConnectionResetError: [Errno 104]`(torch0.4.1 installed in python env). 

  But torch-0.4.0/test/test_dataloader.py is OK(torch0.4.0 installed in python env).

- the stopped iteration number is associated with the worker number, like a linear relationship

**Comment by wangdongxuking61** [comment] 2018-09-14 16:19
> @mcarilli can I use 18.06.1 docker which is the latest version that I can update to get your pytorch image by running `docker pull pytorch/pytorch`?

如果你不关心这个bug，只想使用pytorch训练的话，我建议试试这两种方法之一：
1、使用pytorch-0.4.0
2、使用torch.nn.parallel.DataParallel替代DistributedDataParallel

Translated as follows:
If you don't care about this bug and just want to use pytorch training, I suggest you try one of these two methods:
1 using pytorch-0.4.0
2 use torch.nn.parallel.DataParallel instead of DistributedDataParallel

**Comment by ezyang** [comment] 2018-09-14 16:33
@wangdongxuking61 We have some evidence that it is fixed in master. Would you mind doing a build of PyTorch master and seeing if it still has the problem? That would help a lot!

**Comment by mcarilli** [comment] 2018-09-14 17:10
> @wangdongxuking61 We have some evidence that it is fixed in master. Would you mind doing a build of PyTorch master and seeing if it still has the problem? That would help a lot!

That's true, my tests indicated that the errors went away when I ran with a relatively recent version of Pytorch master (almost top of tree but not quite).  And dataloader.py pulls in utilities from other files as well, which may have been updated.  

I provided instructions in [my last post](https://github.com/pytorch/pytorch/issues/11327#issuecomment-421402529) for how to build a container with the most recent Pytorch master, without having to manually install NCCL or CuDNN (@ezyang probably knows better than I do though, so please correct me if there is an easier/more canonical way to do this)

**Comment by SsnL** [comment] 2018-09-14 17:30
alright I'm training on a master build. i'll report back later.

**Comment by SsnL** [comment] 2018-09-14 17:50
Successfully gets to epoch 1

**Comment by SsnL** [comment] 2018-09-14 17:58
@wangdongxuking61 If you could give me a docker image name that can repro the issue, I can try again. In the meantime, I also would suggest a master build. Note that you may need to change a the apex code according to this patch: https://gist.github.com/SsnL/6427cbf04a3c5e765f7de6e0874cfb50, and pytorch's `torch/utils/data/distributed.py`'s import to `import torch.distributed.deprecated as dist`.

**Comment by wangdongxuking61** [comment] 2018-09-15 09:05
> We have some evidence that it is fixed in master. Would you mind doing a build of PyTorch master and seeing if it still has the problem? That would help a lot!

  @mcarilli @ezyang @SsnL 

Thank you all. I have built PyTorch master. The problem disappears. 
BTW, who can explain the reason of the bug?

**Comment by wangdongxuking61** [comment] 2018-09-15 09:11
> @wangdongxuking61 If you could give me a docker image name that can repro the issue, I can try again. In the meantime, I also would suggest a master build. Note that you may need to change a the apex code according to this patch: https://gist.github.com/SsnL/6427cbf04a3c5e765f7de6e0874cfb50, and pytorch's `torch/utils/data/distributed.py`'s import to `import torch.distributed.deprecated as dist`.

As i said before, i can't reproduce the `shut down on second epoch` error.
But I can easily reproduce the `ConnectionResetError: [Errno 104] Connection reset by peer` or `EOFError` error with 
- python 3.6
- torch0.4.1
- apex/example/imagenet/main.py
```
python -m torch.distributed.launch --nproc_per_node=2 main.py --fp16 --arch resnet18 --epochs 90 --workers 2 --batch-size=128
```

**Comment by yingjianling** [comment] 2018-09-17 07:18
@wangdongxuking61 @mcarilli Thank you for your reply. The problem has been solved by building master.

**Comment by SsnL** [comment] 2018-09-17 14:57
@wangdongxuking61 I believe those have been fixed in master as well.

**Closed by SsnL** 2018-09-17 14:57 UTC
Labels: medium priority, needs-reproduction

**Comment by wangdongxuking61** [comment] 2018-09-18 01:28
> @wangdongxuking61 I believe those have been fixed in master as well.

yes, i get no error after building master . Thank you.

**Comment by XiXiRuPan** [comment] 2019-09-15 08:59
I troubled by the same question in Version pytorch 1.1  .  I want to kown which version is ok?

**Comment by ezyang** [comment] 2019-09-16 14:43
Based on the timing here, 1.2 should be ok
