### ISSUE TITLE
"OutOfMemoryError" is not a valid exception class

### ISSUE THREAD

**Issue by Avishka-Perera** [pytorch/pytorch#109961] opened 2023-09-24 02:26 UTC
### 🐛 Describe the bug

`torch.cuda.OutOfMemoryError` does not extend the `Exception` class. Hence, although the exception is caught, Pylance shows an exception.

Posted issue in Pylance: https://github.com/microsoft/pylance-release/issues/4874#issuecomment-1732457154

### Minimum reproducible code in VS Code
```
import torch
from torch.nn import Linear

try:
    model = Linear(64, 64)
except torch.cuda.OutOfMemoryError:
    print("Out of memory")
```

### Versions

Python: 3.10.12
PyTorch: 2.0.1

**Comment by tringwald** [comment] 2023-09-24 09:06
This is a duplicate of #95936 and was already fixed as part of [this commit](https://github.com/pytorch/pytorch/commit/3afa60bf0f849dd61c49b66a937bb214bcd98f38).

**Closed** 2023-09-24 09:28 UTC
