### ISSUE TITLE
System stuck while training with 2 gpus 

### ISSUE THREAD

**Issue by Ifrahmaqsood** [pytorch/pytorch#52294] opened 2021-02-16 08:14 UTC
I am training some pytorch models i-e Detectron2, MCAN etc. With 2 gpus It never starts training any of the model.System seems to be stuck always

my environment details

PyTorch version: 1.6.0+cu101
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.7 LTS
GCC version: (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010
CMake version: version 3.18.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: Tesla K80
GPU 1: Tesla K80

Nvidia driver version: 430.64
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.2
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.2
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.6.0+cu101
[pip3] torchtext==0.5.0
[pip3] torchvision==0.7.0+cu101
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.0.130 0
[conda] mkl 2020.2 256
[conda] mkl-service 2.3.0 py36he8ac12f_0
[conda] mkl_fft 1.2.0 py36h23d657b_0
[conda] mkl_random 1.1.1 py36h0573a6f_0
[conda] numpy 1.19.2 py36h54aff64_0
[conda] numpy-base 1.19.2 py36hfa32c7d_0
[conda] torch 1.4.0+cu100 pypi_0 pypi
[conda] torchtext 0.5.0 pypi_0 pypi
[conda] torchvision 0.7.0+cu101 pypi_0 pypi

with 2 gpus
![image](https://user-images.githubusercontent.com/67015296/108035195-6d699100-7058-11eb-9c2f-fe2127d12db5.png)

i am unable to understand how to resolve this issue. I have tried decreasing num_worker but it didn't work

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by TaridaGeorge** [comment] 2021-02-16 08:29
I also found it to be stuck when I try to train on TPU.

**Comment by zhaojuanmao** [comment] 2021-02-17 19:17
would you please paste the reproducible codes? thanks

**Comment by Ifrahmaqsood** [comment] 2021-02-18 07:39
@zhaojuanmao 

### For running https://github.com/facebookresearch/grid-feats-vqa code i used following steps

1-)sudo python3.6 -m pip install with specified version and -f
sudo python3.6 -m pip install torch==1.4.0 torchvision==0.5.0 -f https://download.pytorch.org/whl/cu100/torch_stable.html
2-)sudo python3.6 -m pip install 'git+https://github.com/facebookresearch/detectron2.git@ffff8ac'
3-)cd grid-feats-vqa-master
4-)
[grid-feats-vqa-master.zip](https://github.com/pytorch/pytorch/files/6000908/grid-feats-vqa-master.zip)
Note:- **annotations** and **dataset** files in **visual_genome** folder is left empty due to huge memory consumption-> **https://github.com/facebookresearch/grid-feats-vqa**  have provided the link to directly download them.

5-)python3.6 train_net.py **--num-gpus 2** --config-file configs/R-50-grid.yaml

the system stucks at 
Command Line Args: Namespace(config_file='configs/R-50-grid.yaml', dist_url='tcp://127.0.0.1:50170', eval_only=False, machine_rank=0, num_gpus=2, num_machines=1, opts=[], resume=False)
Note:- num-gpu 2 doesn't work but num-gpu 1 starts the training.

### For running https://github.com/facebookresearch/mmf I created conda environment and use the following steps
1-)conda create -n mmf python=3.6
conda activate mmf

2-)sudo /home/anaconda3/envs/mmf/bin/pip install with specified version and -f
sudo /home/anaconda3/envs/mmf/bin/pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html
3-)
[mmf-master.zip](https://github.com/pytorch/pytorch/files/6000954/mmf-master.zip)

4-)cd mmf-master
/home/anaconda3/envs/mmf/bin/pip install --editable .

5-) I gave my own features path of resnet50 grid features extracted from **https://github.com/facebookresearch/grid-feats-vqa** on coco dataset  instead of using default path of this file **https://github.com/facebookresearch/mmf/blob/master/projects/movie_mcan/configs/vqa2/defaults.yaml**

6-) Then ran 
CUDA_VISIBLE_DEVICES=0,1 mmf_run config=projects/movie_mcan/configs/vqa2/defaults.yaml \model=movie_mcan \dataset=vqa2 \run_type=train
Note:- CUDA_VISIBLE_DEVICES=0,1 stuck at **loading dataset...** work but CUDA_VISIBLE_DEVICES=0 starts the training

Any other details you want to know. Please let me know

**Comment by zhaojuanmao** [comment] 2021-02-18 20:39
To use two GPUs, the dataset and model need to be loaded to corresponding devices in your codes. For easier do multi-gpu training, you can use distributedDataParallel API to wrap your model. 

In your codes https://github.com/facebookresearch/grid-feats-vqa/blob/master/train_net.py, it does not load dataset and model to devices or use distributedDataParallel API. 

I'm closing this, as this is not a bug, feel free to ask question about this in the PyTorch Forum.

**Closed by zhaojuanmao** 2021-02-18 20:39 UTC
Labels: oncall: distributed

**Comment by Ifrahmaqsood** [comment] 2021-02-19 04:56
@zhaojuanmao please let me know what could be the issue in https://github.com/facebookresearch/mmf. As they said it's may be a pytorch error. They have a distributed training code in their repository

**Comment by zhaojuanmao** [comment] 2021-02-19 19:42
does "python train_net.py --num-gpus 8 --config-file <config.yaml>**" work for you? 

https://github.com/facebookresearch/mmf/blob/master/mmf/utils/distributed.py showed hostnames and nodes are resolved using "SLURM_STEP_NODELIST", "SLURM_JOB_NODELIST" and etc. Did you run the codes using Slurm and set these env variables properly?

Otherwise, did you see the logs printed out? e.g., "Initialized Host.....". If not, that means the distributed package is not initialized properly. this mostly is because your network environment is not set up correctly. https://pytorch.org/docs/stable/distributed.html showed how to set up common environment variables for using distributed packages.

**Comment by Ifrahmaqsood** [comment] 2021-02-19 19:56
@zhaojuanmao
When I run.... 

CUDA_VISIBLE_DEVICES=0,1 mmf_run config=projects/movie_mcan/configs/vqa2/defaults.yaml \model=movie_mcan \dataset=vqa2 \run_type=train \training.logger_level=debug

**It starts like this**

**2021-02-13T00:38:14 | mmf.utils.configuration: Overriding option config to projects/movie_mcan/configs/vqa2/defaults.yaml
2021-02-13T00:38:14 | mmf.utils.configuration: Overriding option model to movie_mcan
2021-02-13T00:38:14 | mmf.utils.configuration: Overriding option datasets to vqa2
2021-02-13T00:38:14 | mmf.utils.configuration: Overriding option run_type to train
2021-02-13T00:38:14 | mmf.utils.configuration: Overriding option training.num_workers to 0
2021-02-13T00:38:14 | mmf.utils.configuration: Overriding option training.logger_level to debug
2021-02-13T00:38:16 | mmf.utils.distributed: Distributed Init (Rank 0): tcp://localhost:19627
2021-02-13T00:38:17 | mmf.utils.distributed: Distributed Init (Rank 1): tcp://localhost:19627
2021-02-13T00:38:17 | mmf.utils.distributed: Initialized Host 127.0.0.1localhost.localdomainlocalhost as Rank 1
2021-02-13T00:38:17 | mmf.utils.distributed: Initialized Host 127.0.0.1localhost.localdomainlocalhost as Rank 0
2021-02-13T00:38:19 | mmf: Logging to: ./save/train.log
2021-02-13T00:38:19 | mmf_cli.run: Namespace(config_override=None, local_rank=None, opts=['config=projects/movie_mcan/configs/vqa2/defaults.yaml', 'model=movie_mcan', 'dataset=vqa2', 'run_type=train', 'training.num_workers=0', 'training.logger_level=debug'])
2021-02-13T00:38:19 | mmf_cli.run: Torch version: 1.6.0+cu101
2021-02-13T00:38:19 | mmf.utils.general: CUDA Device 0 is: Tesla K80
2021-02-13T00:38:19 | mmf_cli.run: Using seed 19127618

2021-02-13T00:38:19 | mmf.trainers.mmf_trainer: Loading datasets

**The system stucks here at loading datasets**



**On interuption**
^CTraceback (most recent call last):
File "/home/anaconda3/envs/mmf/bin/mmf_run", line 33, in
sys.exit(load_entry_point('mmf', 'console_scripts', 'mmf_run')())
File "/home/new-mmf/mmf-master/mmf_cli/run.py", line 118, in run
nprocs=config.distributed.world_size,
File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
while not context.join():
File "/home/anaconda3/envs/mmf/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 78, in join
timeout=timeout,
File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/connection.py", line 911, in wait
ready = selector.select(timeout)
File "/home/anaconda3/envs/mmf/lib/python3.6/selectors.py", line 376, in select
fd_event_list = self._poll.poll(timeout)
KeyboardInterrupt
^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
File "/home/anaconda3/envs/mmf/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt

**Comment by Ifrahmaqsood** [comment] 2021-02-19 20:12
For https://github.com/facebookresearch/grid-feats-vqa, I cannot train it on 8 gpus as I've got only 2 Gpus in my server

**Comment by Ifrahmaqsood** [comment] 2021-02-22 16:40
@zhaojuanmao any update regarding the latest output that I pasted?

**Comment by zhaojuanmao** [comment] 2021-02-22 17:46
@Ifrahmaqsood you logs showed distributed package are initialized as expected and stuck at loading dataset, you need to further debug why dataset can not be downloaded in your environment. This seems not to be related to distributed packages. 
If you still feel like this is related to distributed package, you can comment out data loading codes, and replace input as simulated dummy data and see whether the program can work. 

Otherwise, I would suggest you to dig into the data loading codes, data sets or your development environment to find out why your data can not be downloaded.

**Comment by Ifrahmaqsood** [comment] 2021-02-22 17:53
@zhaojuanmao thank you for your response. With single gpu it starts training, it means that loading the dataset/features isn't an issue. It only stucks with 2 gpus. I'll try out your suggestion as well.
