### ISSUE TITLE
Providing a pytorch index conforming to PEP-503

### ISSUE THREAD

**Issue by fridex** [pytorch/pytorch#47670] opened 2020-11-10 12:34 UTC
## ❓ Questions and Help

Hi all,

I would like to know if you plan to provide a proper Python package index that would be conforming [PEP-503](https://www.python.org/dev/peps/pep-0503/). This might have benefits when consuming wheel files for users.

Thanks in advance for any response.

cc @ezyang @seemethere @malfet @walterddr

**Comment by fridex** [comment] 2020-11-10 12:40
See http://tensorflow.pypi.thoth-station.ninja/ as an example of an index with multiple builds conforming PEP-503.

**Comment by ezyang** [comment] 2020-11-13 17:29
dupe of https://github.com/pytorch/pytorch/issues/25639

**Closed by ezyang** 2020-11-13 17:29 UTC
Labels: module: binaries, triaged
