### ISSUE TITLE
Migrate `gather` from the TH to Aten (CUDA)

### ISSUE THREAD

**Issue by VitalyFedyunin** [pytorch/pytorch#24567] opened 2019-08-16 19:12 UTC
Porting TH operators is essential for code simplicity and performance reasons.

Porting guides and Q&A are available in umbrella issue: #24507

Feel free to add @VitalyFedyunin as a reviewer to get a prioritized review.

**Comment by nikitaved** [comment] 2020-02-25 09:30
@ngimel, could you please your opinion on this one?
Shall I just reuse all the THC code, or doing it with TensorIterator is preferred?
Also, given the line of work on determinism (@v0dro), shall we make sure that each CUDA thread iterates over an operational dimension, while overall parallelization is taking place over all dimensions but the operational one?
Thank you!

**Comment by ngimel** [comment] 2020-02-25 18:11
You can do it with TensorIterator, using an approach similar to https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/IndexKernel.cu. I'm concerned that it'll lead to regressions compared to THC, but you can experiment with maybe simplifying indexing computations. Directly copying approach that you used for cpu, with separating the indexed dimension into a loop is not going to work here, both because the remaining exposed parallelism won't be enough on the gpu, and because memory accesses from a single thread are going to be very inefficient. So my suggestion is, experiment with TensorIterator-like approaches for some time (trying to reproduce general THC access pattern with TI), but if that does not work, just port THC code. 
As for determinism, let's ignore that for now and just use atomic operations.

**Comment by rgommers** [comment] 2020-05-20 14:30
The CUDA implementation of `gather` was ported in gh-37659, however the legacy implementation is not yet removed because it's still in use by `topk` (see https://github.com/pytorch/pytorch/pull/37659#issuecomment-626827286). @nikitaved will clean that up when he's done with `topk`.

Since ATen `gather` is available, I'll close this.

**Closed by rgommers** 2020-05-20 14:30 UTC
Labels: better-engineering, module: operators, topic: porting, triaged
