### ISSUE TITLE
torch.full (and other factory functions) supports requires_grad kwarg in eager mode but not jit

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#40363] opened 2020-06-22 03:53 UTC
```
t = torch.full((2, 2), 1., requires_grad=True)

def fn():
    return torch.full((2, 2,), 1., requires_grad=True)

scripted_fn = torch.jit.script(fn)
scripted_fn()
```

Will throw error:

```
Traceback (most recent call last):
  File "../../issues.py", line 28, in <module>
    scripted_fn = torch.jit.script(fn)
  File "/private/home/mruberry/git/pytorch/torch/jit/__init__.py", line 1384, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::full.names(int[] size, Scalar fill_value, *, str[]? names, int? dtype=None, int? layout=None, Device? device=None, bool? pin_memory=None) -> (Tensor):
  Argument names not provided.
  
  aten::full(int[] size, Scalar fill_value, *, int? dtype=None, int? layout=None, Device? device=None, bool? pin_memory=None) -> (Tensor):
  Keyword argument requires_grad unknown.
  
  aten::full.out(int[] size, Scalar fill_value, *, Tensor(a!) out) -> (Tensor(a!)):
  Argument out not provided.

The original call is:
  File "../../issues.py", line 26
def fn():
    return torch.full((2, 2,), 1., requires_grad=True)
           ~~~~~~~~~~ <--- HERE
```

cc @suo. @bhosmer

**Comment by ezyang** [comment] 2020-07-01 17:17
I was affected by this today when scripting the seq2seq model in https://github.com/stanfordnlp/stanza In that case, `requires_grad=False` so it was fairly easy to remove.

**Comment by ezyang** [comment] 2020-07-01 17:18
Dupe of https://github.com/pytorch/pytorch/issues/19393

**Closed by ezyang** 2020-07-01 17:18 UTC
Labels: jit
