### ISSUE TITLE
Crash on exit in Python 3.9.0a6

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#38230] opened 2020-05-11 14:46 UTC
## 🐛 Bug

PyTorch programs that use autograd crash on exit with Python 3.9.0a6. The underlying cause is the same as #38228, but changes to the implementation of `PyEval_RestoreThread` means this happens much more frequently in Python 3.9.0a6 than with previous Python versions.

In previous Python releases, threads that called `PyEval_RestoreThread` after the interpreter shutdown would deadlock. Now they call `pthread_exit(0)`, which triggers the issue in #38228.

The implementation of `PyEval_RestoreThread` has changed between alpha releases of 3.9.0 and may change in the future, so we might not want to rush any fixes.

The crash happens on exit with a message like:

```
terminate called without an active exception
Aborted
```

Example:

```python
import torch
torch.set_num_threads(1)  # optional
x = torch.randn(10, requires_grad=True)
x.sum().backward()
```

Tested on PyTorch master (324dc1623e2) and Python 3.9.0a6.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @SsnL

**Comment by Nuno-Mota** [comment] 2020-12-21 11:15
Any progress on this?
Experiencing this with 1.7.1rc2, python 3.9.0, on archlinux.

**Comment by ezyang** [comment] 2021-01-04 19:04
This was supposed to have been fixed by https://github.com/pytorch/pytorch/pull/48117 however this fix should be in 1.7.1. Can you try the non-RC maybe? cc @seemethere

**Comment by ccshan** [comment] 2021-01-05 04:09
I see the crash with Debian python3-torch 1.7.1-3 (torch.__version__ = 1.7.0a0) and python3 3.9.1-1

**Comment by malfet** [comment] 2021-01-11 18:15
Sounds like a duplicate of https://github.com/pytorch/pytorch/issues/50014 (destruction of GIL in autograd threads)

**Comment by mattip** [comment] 2021-01-19 09:49
@malfet isn't #50014 a duplicate of #38228?

**Comment by mattip** [comment] 2021-04-09 10:17
I think #50998 closed this issue

**Comment by malfet** [comment] 2021-04-09 13:55
Good point, closing

**Closed by malfet** 2021-04-09 13:55 UTC
Labels: high priority, module: autograd, module: crash, triaged
