### ISSUE TITLE
rpc crash

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#54463] opened 2021-03-23 00:01 UTC
## 🐛 Bug

```
% python test_cuda_rpc.py
[E thread_pool.cpp:112] Exception in thread pool task: !completed() INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/core/ivalue_inl.h":534, please report a bug to PyTorch.
Exception raised from setErrorInternal at /pytorch/aten/src/ATen/core/ivalue_inl.h:534 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f0723b4d2f2 in /private/home/msb/.conda/envs/fairseq-20210102-pt180/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x73b12f (0x7f07979b012f in /private/home/msb/.conda/envs/fairseq-20210102-pt180/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #2: std::_Function_handler<void (), c10::ivalue::Future::then(std::function<c10::IValue ()>, std::shared_ptr<c10::Type>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) + 0x6e (0x7f07979b024e in /private/home/msb/.conda/envs/fairseq-20210102-pt180/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: std::_Function_handler<void (), at::cuda::CUDAFuture::wrapCallback(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) + 0x336 (0x7f0797d257b6 in /private/home/msb/.conda/envs/fairseq-20210102-pt180/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xaa4f81 (0x7f0797d19f81 in /private/home/msb/.conda/envs/fairseq-20210102-pt180/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: c10::ThreadPool::main_loop(unsigned long) + 0x26b (0x7f0723b3e07b in /private/home/msb/.conda/envs/fairseq-20210102-pt180/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0xd6d84 (0x7f079895dd84 in /usr/lib/x86_64-linux-gnu/libstdc++.so.6)
frame #7: <unknown function> + 0x9609 (0x7f0799cd9609 in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x43 (0x7f0799c00293 in /usr/lib/x86_64-linux-gnu/libc.so.6)

```
## To Reproduce

1.
1.
1.

```
% cat test_cuda_rpc.py
import tempfile

import torch
import torch.distributed.rpc as rpc
import torch.multiprocessing as mp
import torch.nn as nn


def rpc_worker(rank, world_size, init_file, func):
    if torch.__version__.split('+')[0].split('.') == [1, 8, 0]:
        # Workaround for https://github.com/pytorch/pytorch/issues/53844
        options = rpc.TensorPipeRpcBackendOptions(init_method="file://" + init_file, _transports=["ibv", "uv"])
    else:
        options = rpc.TensorPipeRpcBackendOptions(init_method="file://" + init_file)
    for i in range(world_size):
        if i != rank:
            options.set_device_map("worker" + str(rank), {rank: i})
    rpc.init_rpc(
        "worker" + str(rank),
        rank=rank,
        world_size=world_size,
        backend=rpc.BackendType.TENSORPIPE,
        rpc_backend_options=options,
    )
    if rank == 0:
        func()
    rpc.shutdown()


def test_func():
    layer = rpc.remote("worker1", nn.Linear, args=(4,4))
    layer = layer.remote().to("cuda:1")


if __name__ == "__main__":
    world_size = 2
    mp.spawn(rpc_worker, args=(world_size, tempfile.mkstemp()[1], test_func), nprocs=world_size)
```
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).
Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0+cu111
[pip3] torch-pg==0.0.0
[pip3] torchaudio==0.8.0
[pip3] torchprof==1.3.3
[pip3] torchvision==0.9.0+cu111
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] torch                     1.8.0+cu111              pypi_0    pypi
[conda] torch-pg                  0.0.0                     dev_0    <develop>
[conda] torchaudio                0.8.0                    pypi_0    pypi
[conda] torchprof                 1.3.3                    pypi_0    pypi
[conda] torchvision               0.9.0+cu111              pypi_0    pypi
You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu

**Comment by rohan-varma** [comment] 2021-03-23 02:19
Just a comment on the error stacktrace here (cc @lw) - the error stacktrace here looks similar to https://github.com/pytorch/pytorch/issues/53717#issuecomment-800545655, where we can probably enhance then() implementation as discussed in that thread to get the true stacktrace and see whether this is failing in `postMarkCompletedHook`.

**Comment by mrshenli** [comment] 2021-03-23 15:21
I tried the code snippet on two different servers with different GPUs, but I cannot reproduce this on master. @msbaines, we did land several fixes after v1.8, could you please check if the error still persist in nightly?

**Comment by lw** [comment] 2021-03-23 15:31
@mrshenli Could this be again the issue with DataPtr extraction in CUDAFuture? The one for which we did land a fix in master but didn't backport to v1.8 because it was too invasive (and because CUDA support in RPC wasn't supposed to be present in v1.8)?

@msbaines In general, CUDA support for RPC isn't in a good shape in v1.8, it only made it into the release "by mistake". We recommend using the nightlies for that, we're landing fixes regularly on master and that will ensure you pick them all up.

**Comment by msbaines** [comment] 2021-03-23 18:17
I just tried nightly and the crash still happens.

**Comment by msbaines** [comment] 2021-03-23 19:22
> I just tried nightly and the crash still happens.

I had issues installing nightly. When I finally installed nightly the crash stopped happening.

**Comment by lw** [comment] 2021-03-23 19:37
I'd say we can close this issue: if the crash doesn't happen in master/nightlies, and if it only affects CUDA tensors, there's nothing we can do about it. We have already landed a fix, and we have chosen not to backport it to v1.8. Please reopen if I misunderstood and if there's more to do on this.

**Closed by lw** 2021-03-23 19:37 UTC
Labels: module: rpc, oncall: distributed, triaged
