### ISSUE TITLE
Torchscript torch.jit.trace nvrtc: error: failed to open libnvrtc-builtins.so.11.1.

### ISSUE THREAD

**Issue by HaiyueZhu** [pytorch/pytorch#68980] opened 2021-11-29 09:57 UTC
Hi, I am using torchscript to do the inference in Ubuntun20.04 + cuda 11.5 environment. But it appears the error as following:

[ERROR] [1638178650.943765]: **Error processing request: nvrtc: error: failed to open libnvrtc-builtins.so.11.1.
  Make sure that libnvrtc-builtins.so.11.1 is installed correctly.**
nvrtc compilation failed: 

In my system, I can only find libnvrtc-builtins.so.11.5 but no libnvrtc-builtins.so.11.1. I was tried to use symbolic link to create a libnvrtc-builtins.so.11.1 from libnvrtc-builtins.so.11.5, but seems no help. Does anyone have idea on this error? thank you.

cc @ezyang @seemethere @malfet @ngimel

**Comment by malfet** [comment] 2021-11-29 17:23
@HaiyueZhu can you please clarify how you've installed pytorch/libtorch? Using official binaries or locally built ones?
If you are using pytorch package, can you please run `python3 -mtorch.utils.collect_env` and share its output?

P.S. I suspect that `libnvrtc-builtins.so` is missing in libtorch package

**Comment by HaiyueZhu** [comment] 2021-11-30 02:23
Hi Malfet, thanks for the reply. Actually I am using torchscript in Python so there is no libtorch installed. The pytorch is installed using the official binaries. 

For the libnvrtc-builtins.so, I can found libnvrtc-builtins.so and libnvrtc-builtins.so.10.1 in /usr/lib/x86_64-linux-gnu; libnvrtc-builtins.so and libnvrtc-builtins.so.11.5 in /usr/local/cuda-11.5/targets/x86_64-linux/lib.

Run python3 -mtorch.utils.collect_env it shows:
_Collecting environment information...
PyTorch version: 1.8.2+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] torch==1.8.2+cu111
[pip3] torchaudio==0.8.2
[pip3] torchvision==0.9.2+cu111
[conda] Could not collect_

Thank you.

**Comment by HaiyueZhu** [comment] 2021-11-30 02:24
> @HaiyueZhu can you please clarify how you've installed pytorch/libtorch? Using official binaries or locally built ones? If you are using pytorch package, can you please run `python3 -mtorch.utils.collect_env` and share its output?
> 
> P.S. I suspect that `libnvrtc-builtins.so` is missing in libtorch package

Hi Malfet, thanks for the reply. Actually I am using torchscript in Python so there is no libtorch installed. The pytorch is installed using the official binaries.

For the libnvrtc-builtins.so, I can found libnvrtc-builtins.so and libnvrtc-builtins.so.10.1 in /usr/lib/x86_64-linux-gnu; libnvrtc-builtins.so and libnvrtc-builtins.so.11.5 in /usr/local/cuda-11.5/targets/x86_64-linux/lib.

Run python3 -mtorch.utils.collect_env it shows:
_Collecting environment information...
PyTorch version: 1.8.2+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3080
Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.3
[pip3] torch==1.8.2+cu111
[pip3] torchaudio==0.8.2
[pip3] torchvision==0.9.2+cu111
[conda] Could not collect_

Thank you.

**Comment by DaeyangCho** [comment] 2022-01-17 12:09
I encountered the same issue, and solved it.
Libtorch has cuda 11.1 (LTS) and cuda 11.3 (Stable) up to date.
So, to use libtorch, we need to install the appropriate cuda version, not 11.5.
I re-installed cuda and it works well with libtorch cuda 11.1 (LTS)

**Comment by ngimel** [comment] 2022-01-17 19:37
duplicate of #69689

**Closed by ngimel** 2022-01-17 19:37 UTC
Labels: module: binaries, oncall: jit, module: cuda

**Comment by haofanwang** [comment] 2022-08-08 12:19
libnvrtc-builtins.so.11.1 is not existed if you install Pytorch via pip. But you can find libnvrtc-builtins.so in PATH/torch/lib, and rename libnvrtc-builtins.so to libnvrtc-builtins.so.11.1. All is well.

**Comment by JonathanLehner** [comment] 2022-09-05 23:58
I had this problem with GLAMR

**Comment by mertkaraoglu** [comment] 2023-06-08 14:04
> libnvrtc-builtins.so.11.1 is not existed if you install Pytorch via pip. But you can find libnvrtc-builtins.so in PATH/torch/lib, and rename libnvrtc-builtins.so to libnvrtc-builtins.so.11.1. All is well.

This is the working solution, to be a bit safer use `ln -s libnvrtc-builtins.so  libnvrtc-builtins.so.11.1`. This will ensure the both the original file and a symbolic link with the required name coexists.
