### ISSUE TITLE
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by nabenabe0928** [pytorch/pytorch#118737] opened 2024-01-31 08:53 UTC
### 🐛 Describe the bug

The CI of Optuna integration, which uses Torch as a dependency, fails since the torch version was updated to v2.2.0.

Please check [here](https://github.com/optuna/optuna/actions/runs/7722855986/job/21051777682) for the error message.

With the version constraint `torch<2.2.0`, the same failure completely disappeared (Please check [here](https://github.com/optuna/optuna/actions/runs/7723123991/job/21052570860?pr=5217)).

### Versions

The environment is described in the Optuna CI.

https://github.com/optuna/optuna/actions/runs/7723123991/job/21052570860?pr=5217

Note that the same test will not fail on Ubuntu and Mac OS.
It fails only on Windows.

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @atalman @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment] 2024-01-31 16:54
Adding `oncall: distributed` (though may be I should not) as error seems to happen during c10 initialization:
```
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\torch\distributed\distributed_c10d.py", line 1177, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\torch\distributed\rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
torch.distributed.DistNetworkError: Unknown error
```

**Comment by atalman** [comment] 2024-01-31 22:10
Minimal Repro:

```
(py311) C:\Users\runneruser\temp\pytorch>python test/distributed/test_device_mesh.py -k test_init_process_group
Fail to import hypothesis in common_utils, tests are not derandomized
C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py:553: ResourceWarning: unclosed file <_io.BufferedRandom name='C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\2\\tmpw4diowbl'>
  self.file_name = tempfile.NamedTemporaryFile(delete=False).name
ResourceWarning: Enable tracemalloc to get the object allocation traceback
Fail to import hypothesis in common_utils, tests are not derandomized
Fail to import hypothesis in common_utils, tests are not derandomized
Fail to import hypothesis in common_utils, tests are not derandomized
Fail to import hypothesis in common_utils, tests are not derandomized
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR] Caught exception:
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR] Traceback (most recent call last):
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py", line 649, in run_test
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     getattr(self, test_name)()
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py", line 535, in wrapper
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     fn()
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_utils.py", line 2652, in wrapper
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     method(*args, **kwargs)
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\temp\pytorch\test\distributed\test_device_mesh.py", line 65, in test_init_process_group
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     DeviceMesh(device_type, mesh_tensor)
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\device_mesh.py", line 202, in __init__
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     self._get_or_create_default_group()
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\device_mesh.py", line 209, in _get_or_create_default_group
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     init_process_group()
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     func_return = func(*args, **kwargs)
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]                   ^^^^^^^^^^^^^^^^^^^^^
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1177, in init_process_group
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     store, rank, world_size = next(rendezvous_iterator)
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]                               ^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]   File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\rendezvous.py", line 174, in _create_c10d_store
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]     return TCPStore(
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]            ^^^^^^^^^
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR] torch.distributed.DistNetworkError: Unknown error
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR] To execute this test, run the following from the base repo dir:
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]      python test\distributed\test_device_mesh.py -k test_init_process_group
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR] This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
[2024-01-31 22:08:32,424] torch.testing._internal.common_distributed: [ERROR]  exiting process 0 with exit code: 10
Process 0 terminated with exit code 10, terminating remaining processes.
E
======================================================================
ERROR: test_init_process_group (__main__.DeviceMeshTest.test_init_process_group)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py", line 533, in wrapper
    self._join_processes(fn)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py", line 752, in _join_processes
    self._check_return_codes(elapsed_time)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py", line 802, in _check_return_codes
    raise RuntimeError(error)
RuntimeError: Process 0 exited with error code 10 and exception:
Traceback (most recent call last):
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py", line 649, in run_test
    getattr(self, test_name)()
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py", line 535, in wrapper
    fn()
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_utils.py", line 2652, in wrapper
    method(*args, **kwargs)
  File "C:\Users\runneruser\temp\pytorch\test\distributed\test_device_mesh.py", line 65, in test_init_process_group
    DeviceMesh(device_type, mesh_tensor)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\device_mesh.py", line 202, in __init__
    self._get_or_create_default_group()
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\device_mesh.py", line 209, in _get_or_create_default_group
    init_process_group()
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\c10d_logger.py", line 86, in wrapper
    func_return = func(*args, **kwargs)
                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\distributed_c10d.py", line 1177, in init_process_group
    store, rank, world_size = next(rendezvous_iterator)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\rendezvous.py", line 246, in _env_rendezvous_handler
    store = _create_c10d_store(master_addr, master_port, rank, world_size, timeout, use_libuv)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\rendezvous.py", line 174, in _create_c10d_store
    return TCPStore(
           ^^^^^^^^^
torch.distributed.DistNetworkError: Unknown error

To execute this test, run the following from the base repo dir:
     python test\distributed\test_device_mesh.py -k test_init_process_group

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0



----------------------------------------------------------------------
Ran 1 test in 3.729s

FAILED (errors=1)
```

**Comment by atalman** [comment] 2024-01-31 22:26
Using torch 2.1.0 and 2.1.2:
```
python test/distributed/test_launcher.py
```
returns
```
[2024-01-31 22:25:01,210] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Fail to import hypothesis in common_utils, tests are not derandomized
C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\launch.py:181: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
[2024-01-31 22:25:01,417] torch.distributed.run: [WARNING]
[2024-01-31 22:25:01,417] torch.distributed.run: [WARNING] *****************************************
[2024-01-31 22:25:01,417] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2024-01-31 22:25:01,417] torch.distributed.run: [WARNING] *****************************************
Success, smoke test
Success, smoke test
Success, smoke test
Success, smoke test
.
----------------------------------------------------------------------
Ran 1 test in 1.037s

OK
```
 
on PyTorch 2.2.0

```
=====================================================================
ERROR: test_launch_user_script (__main__.TestDistributedLaunch.test_launch_user_script)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_utils.py", line 2652, in wrapper
    method(*args, **kwargs)
  File "C:\Users\runneruser\temp\pytorch\test\distributed\test_launcher.py", line 52, in test_launch_user_script
    launch.main(args)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\launch.py", line 194, in main
    launch(args)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\launch.py", line 179, in launch
    run(args)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\run.py", line 803, in run
    elastic_launch(
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\launcher\api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\launcher\api.py", line 259, in launch_agent
    result = agent.run()
             ^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 727, in run
    result = self._invoke_run(role)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 862, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 699, in _initialize_workers
    self._rendezvous(worker_group)
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\metrics\api.py", line 123, in wrapper
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 542, in _rendezvous
    store, group_rank, group_world_size = spec.rdzv_handler.next_rendezvous()
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 55, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.distributed.DistNetworkError: Unknown error

To execute this test, run the following from the base repo dir:
     python test\distributed\test_launcher.py -k test_launch_user_script

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 1 test in 1.329s

FAILED (errors=1)
```

**Comment by mantaionut** [comment] 2024-02-01 08:38
The issue is due to the new Validate logic https://github.com/pytorch/pytorch/pull/107607 not working properly on Windows. I'll create a PR to fix this.

**Comment by atalman** [comment] 2024-02-02 20:50
Confirmed this if fixed:
```
python distributed/test_launcher.py
[2024-02-02 20:49:38,149] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
Fail to import hypothesis in common_utils, tests are not derandomized
C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\distributed\launch.py:183: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torchrun.
Note that --use-env is set by default in torchrun.
If your script expects `--local-rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
[2024-02-02 20:49:38,986] torch.distributed.run: [WARNING]
[2024-02-02 20:49:38,986] torch.distributed.run: [WARNING] *****************************************
[2024-02-02 20:49:38,986] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
[2024-02-02 20:49:38,986] torch.distributed.run: [WARNING] *****************************************
Success, smoke test
Success, smoke testSuccess, smoke test

Success, smoke test
.
----------------------------------------------------------------------
Ran 1 test in 2.345s

OK

```

**Comment by malfet** [comment] 2024-02-02 20:58
Let's keep this one open, until we cherry-pick the fix in the next patch release.
@nabenabe0928 would it be possible to run a one of round of Optuna CI against nightly to validate that fix covers all tests that you are running?

**Comment by nabenabe0928** [comment] 2024-02-05 05:16
@malfet @mantaionut @atalman 
Thank you for the quick fix of this issue!
I will check whether the fix works nicely on Optuna and get back to you!

**Comment by nabenabe0928** [comment] 2024-02-07 11:18
While torch nightly fails, torch<2.2.0 passes.

[Passed](https://github.com/nabenabe0928/optuna/actions/runs/7813880215/job/21313961231) / [Failed](https://github.com/nabenabe0928/optuna/actions/runs/7813816414/job/21313767675)

The difference between the passed commit and the failed commit:
https://github.com/nabenabe0928/optuna/pull/8/commits/c2398a6db0c5eca211e71c3fa5f25e9e6f4b2e96

**Comment by nabenabe0928** [comment] 2024-02-07 11:19
@malfet @mantaionut @atalman
While torch nightly fails, torch<2.2.0 passes.

[Passed](https://github.com/nabenabe0928/optuna/actions/runs/7813880215/job/21313961231) / [Failed](https://github.com/nabenabe0928/optuna/actions/runs/7813816414/job/21313767675)

The difference between the passed commit and the failed commit:
https://github.com/nabenabe0928/optuna/pull/8/commits/c2398a6db0c5eca211e71c3fa5f25e9e6f4b2e96

**Comment by atalman** [comment] 2024-02-12 23:34
Hi @nabenabe0928 from the log I see that it installs torch nightly from : 
```
2024-02-07T11:10:14.3634524Z torch==2.3.0.dev20240122+cpu
```

You need torch nightly after Feb 2.

**Comment by nabenabe0928** [comment] 2024-02-13 05:15
@atalman Thank you for notifying me that we were installing torch nightly 20240122.

I changed the order of the installation ([here](https://github.com/nabenabe0928/optuna/actions/runs/7882004823/job/21506548447?pr=8)), but GitHub tells me that torch after 2024-01-22 is not compatible.
The dependencies at the point when torch nightly is installed are Python 3.9, MPI, and the OS, i.e. Windows.

Probably, it is just impossible to try the latest torch nightly in my environment (for Windows)?

**Comment by mantaionut** [comment] 2024-02-13 07:10
@nabenabe0928 can you try to `pip install mkl==2021.4.0` before the `pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu`.
@atalman after the MKL dependency was added on Windows pip will fail to install it since MKL is not on https://download.pytorch.org/whl/nightly/cpu. Do we need to add it there?

**Comment by nabenabe0928** [comment] 2024-02-13 12:46
@mantaionut @atalman 
Thank you for the instruction!
It actually removed our error completely!
https://github.com/nabenabe0928/optuna/pull/8/commits/0fc21729a18e3fe38b7ea0bdcfd2604798216e77

**Comment by atalman** [comment] 2024-02-13 13:57
closing this issue. Cherry-Pick posted

**Closed by atalman** 2024-02-13 13:57 UTC
Labels: high priority, triage review, module: binaries, oncall: distributed, module: windows, module: regression

**Comment by atalman** [comment] 2024-02-19 22:52
Run test on final rc:
```
py311) C:\Users\runneruser\temp\pytorch>python test/distributed/test_device_mesh.py -k test_init_process_group
C:\Users\runneruser\.conda\envs\py311\Lib\site-packages\torch\testing\_internal\common_distributed.py:553: ResourceWarning: unclosed file <_io.BufferedRandom name='C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\2\\tmptfv_jylc'>
  self.file_name = tempfile.NamedTemporaryFile(delete=False).name
ResourceWarning: Enable tracemalloc to get the object allocation traceback
.
----------------------------------------------------------------------
Ran 1 test in 6.721s

OK
```
