### ISSUE TITLE
JIT LibTorch: Profiling Mode Enabled causes memory leak

### ISSUE THREAD

**Issue by xsacha** [pytorch/pytorch#46380] opened 2020-10-15 07:08 UTC
## 🐛 Bug

I noticed in a recent nightly (around 1.7.0-rc1) that memory seems to uncontrollable leak per forward run. I am seeing about 4-15MB/second in a particular app. I tracked it down to at::cat being called with memory that is never deallocated and noticed some calls to ProfilingRecord's.

Eventually I tracked down that turning off profiling mode successfully eliminates the memory leak.
Also, turning on profiling (torch::jit::EnableProfilingGuard) in earlier releases turns the memory leak on.

## To Reproduce

1. On old version, enable profiling or on new version disable profiling (now the default)
2. Continuously perform forward runs
3. Memory usage increases and never goes down

## Expected behavior

Stable memory as before

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0-rc1
 - OS (e.g., Linux): Linux and Windows
 - How you installed PyTorch (`conda`, `pip`, source): source and nightly
 - Build command you used (if compiling from source):
 - Python version: N/A
 - CUDA/cuDNN version: 11.0 / 8.0
 - GPU models and configuration: RTX 2060 and CPU as well
 - Any other relevant information:

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @heitorschueroff @gmagogsfm

**Comment by eellison** [comment] 2020-10-15 16:51
Hi, thanks for the issue. Do you have a repro you could share by any chance ?

**Comment by xsacha** [comment] 2020-10-15 21:02
@eellison Can confirm it happens simply running a face detector such as:
https://github.com/biubug6/Pytorch_Retinaface

**Comment by xsacha** [comment] 2020-10-16 04:26
I have worked out that the memory leaks occur with the following combination:
```C++
torch::jit::getProfilingMode() = true; // default
torch::jit::GraphOptimizerEnabledGuard guard{false};
model->forward(in);
```

Disabling graph optimiser + enabling profiling mode.

**Comment by Krovatkin** [comment] 2020-10-16 07:04
@xsacha 

I tried reproducing a memory leak in this commit: https://github.com/biubug6/Pytorch_Retinaface/commit/8e535c33c6b9019246a5c9be90b572cb059d7733 but, unfortunately, I couldn't see any significant increase in memory aside from very small fluctuations (0.3-1%) 😢  
I tried both mobilenet and resnet backbones. 

Could you please share with us 
1) a serialized model by `torch.jit.save(model)` and a simple standalone driver script with dummy inputs that reproduces the behaviour or **alternatively** a list of steps we could follow to reproduce with https://github.com/biubug6/Pytorch_Retinaface (the more detailed the better, e.g. how to get inputs, weights, which backbone to use, if you scripted or traced the model)
2) the versions of PyTorch, torchvision and Pytorch_Retinaface you were using
3) the tool you used for memory profiling


@eellison @ZolotukhinM Am I missing anything?

**Comment by xsacha** [comment] 2020-10-16 10:51
@Krovatkin 
To replicate you need to disable optimizer like so:
`torch._C._set_graph_executor_optimize(False)`
as in https://github.com/pytorch/pytorch/blob/f5c95d5cf1718bd4b2d5b787d7fae9151efff811/benchmarks/profiler_benchmark/profiler_bench.py

**Comment by Krovatkin** [comment] 2020-10-16 20:51
@xsacha  

Okay looks like we know what's going on here. 
`torch::jit::GraphOptimizerEnabledGuard no_optimizer_guard{false}` with profiling on hits a corner case where ProfilingGraphExecutor would still profile (i.e. insert profiling nodes and do 1 profiling run per our defaults) but disable optimizations in the optimization stage. The optimization stage also includes the pass that removes `prim::profile` nodes from a final optimized graph, so we keep collecting profiling information even in the optimization stage. Every run we would record types into `profiled_types_per_frame_`, so it would just keep growing. 

If you run the repro `https://github.com/Krovatkin/Pytorch_Retinaface/blob/master/run_mobilenet.sh` you would see memory slowly growing:

```
memory =  619.83203125
memory =  683.73046875
memory =  683.73046875
memory =  699.73046875
memory =  746.4453125
memory =  747.09375
memory =  763.69140625
memory =  779.73046875
memory =  795.69921875
memory =  811.73046875
memory =  827.73046875
memory =  843.73046875
memory =  859.734375
memory =  875.734375
memory =  891.734375
memory =  907.6796875
memory =  923.6015625
memory =  939.734375
memory =  955.734375
memory =  971.62109375
memory =  987.734375
memory =  1003.734375
memory =  1019.734375
memory =  1035.734375
memory =  1051.734375
memory =  1067.734375
memory =  1083.734375
memory =  1099.57421875
memory =  1115.7265625
memory =  1131.625
memory =  1147.5859375
memory =  1163.734375
memory =  1179.73046875
memory =  1195.62109375
memory =  1211.734375
memory =  1227.6484375
memory =  1243.625
memory =  1259.734375
memory =  1275.6171875
memory =  1291.50390625
memory =  1307.73046875
memory =  1323.69921875
memory =  1339.66796875
memory =  1355.58203125
memory =  1371.73828125
memory =  1387.73828125
memory =  1403.73828125
memory =  1419.73828125
memory =  1435.73828125
memory =  1451.73828125
memory =  1467.73828125
memory =  1483.73828125
memory =  1499.73828125
memory =  1515.73828125
memory =  1531.73828125
memory =  1547.73828125
memory =  1563.73828125
memory =  1579.73828125
memory =  1595.73828125
memory =  1611.73828125
memory =  1627.73828125
memory =  1643.73828125
memory =  1659.73828125
memory =  1675.73828125
memory =  1691.73828125
memory =  1707.73828125
memory =  1723.578125
memory =  1739.73828125
memory =  1755.73828125
memory =  1771.73828125
memory =  1787.73828125
memory =  1803.73828125
memory =  1819.73828125
memory =  1835.73828125
memory =  1851.65234375
memory =  1867.73828125
memory =  1883.7421875
memory =  1899.7421875
memory =  1915.62109375
memory =  1931.59765625
memory =  1947.578125
memory =  1963.7421875
memory =  1979.7421875
memory =  1995.7109375
memory =  2011.7421875
memory =  2027.7421875
memory =  2043.7421875
memory =  2059.67578125
memory =  2075.7421875
memory =  2091.7421875
memory =  2107.671875
memory =  2123.7421875
memory =  2139.7421875
memory =  2155.7421875
memory =  2171.6796875
memory =  2187.7421875
memory =  2203.7421875
memory =  2219.7421875
memory =  2235.7421875
memory =  2251.7421875
```

When we look at the final optimized graph we can see `prim::profile` nodes still being in the graph:

```
[DUMP profiling_graph_executor_impl.cpp:499] Optimized Graph:
[DUMP profiling_graph_executor_impl.cpp:499] graph(%self.1 : __torch__.models.retinaface.RetinaFace,
[DUMP profiling_graph_executor_impl.cpp:499]       %input.1 : Tensor):
[DUMP profiling_graph_executor_impl.cpp:499]   %2 : __torch__.torch.nn.modules.container.___torch_mangle_183.ModuleList = prim::GetAttr[name="LandmarkHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %3 : __torch__.models.retinaface.___torch_mangle_182.LandmarkHead = prim::GetAttr[name="2"](%2)
[DUMP profiling_graph_executor_impl.cpp:499]   %4 : __torch__.torch.nn.modules.container.___torch_mangle_183.ModuleList = prim::GetAttr[name="LandmarkHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %5 : __torch__.models.retinaface.___torch_mangle_180.LandmarkHead = prim::GetAttr[name="1"](%4)
[DUMP profiling_graph_executor_impl.cpp:499]   %6 : __torch__.torch.nn.modules.container.___torch_mangle_183.ModuleList = prim::GetAttr[name="LandmarkHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %7 : __torch__.models.retinaface.LandmarkHead = prim::GetAttr[name="0"](%6)
[DUMP profiling_graph_executor_impl.cpp:499]   %8 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="ClassHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %9 : __torch__.models.retinaface.___torch_mangle_171.ClassHead = prim::GetAttr[name="2"](%8)
[DUMP profiling_graph_executor_impl.cpp:499]   %10 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="ClassHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %11 : __torch__.models.retinaface.___torch_mangle_169.ClassHead = prim::GetAttr[name="1"](%10)
[DUMP profiling_graph_executor_impl.cpp:499]   %12 : __torch__.torch.nn.modules.container.ModuleList = prim::GetAttr[name="ClassHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %13 : __torch__.models.retinaface.ClassHead = prim::GetAttr[name="0"](%12)
[DUMP profiling_graph_executor_impl.cpp:499]   %14 : __torch__.torch.nn.modules.container.___torch_mangle_177.ModuleList = prim::GetAttr[name="BboxHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %15 : __torch__.models.retinaface.___torch_mangle_176.BboxHead = prim::GetAttr[name="2"](%14)
[DUMP profiling_graph_executor_impl.cpp:499]   %16 : __torch__.torch.nn.modules.container.___torch_mangle_177.ModuleList = prim::GetAttr[name="BboxHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %17 : __torch__.models.retinaface.___torch_mangle_174.BboxHead = prim::GetAttr[name="1"](%16)
[DUMP profiling_graph_executor_impl.cpp:499]   %18 : __torch__.torch.nn.modules.container.___torch_mangle_177.ModuleList = prim::GetAttr[name="BboxHead"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %19 : __torch__.models.retinaface.BboxHead = prim::GetAttr[name="0"](%18)
[DUMP profiling_graph_executor_impl.cpp:499]   %20 : __torch__.models.net.___torch_mangle_166.SSH = prim::GetAttr[name="ssh3"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %21 : __torch__.models.net.___torch_mangle_148.SSH = prim::GetAttr[name="ssh2"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %22 : __torch__.models.net.SSH = prim::GetAttr[name="ssh1"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %23 : __torch__.models.net.FPN = prim::GetAttr[name="fpn"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %24 : __torch__.torchvision.models._utils.IntermediateLayerGetter = prim::GetAttr[name="body"](%self.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %25 : (Tensor, Tensor, Tensor) = prim::CallMethod[name="forward"](%24, %input.1)
[DUMP profiling_graph_executor_impl.cpp:499]   %26 : Tensor, %27 : Tensor, %28 : Tensor = prim::TupleUnpack(%25)
[DUMP profiling_graph_executor_impl.cpp:499]   %29 : (Tensor, Tensor, Tensor, Tensor, Tensor) = prim::CallMethod[name="forward"](%23, %26, %27, %28)
[DUMP profiling_graph_executor_impl.cpp:499]   %30 : Tensor, %31 : Tensor, %32 : Tensor, %33 : Tensor, %34 : Tensor = prim::TupleUnpack(%29)
[DUMP profiling_graph_executor_impl.cpp:499]   %35 : Tensor = prim::CallMethod[name="forward"](%22, %30)
[DUMP profiling_graph_executor_impl.cpp:499]   %36 : Tensor = prim::CallMethod[name="forward"](%21, %31, %32)
[DUMP profiling_graph_executor_impl.cpp:499]   %37 : Tensor = prim::CallMethod[name="forward"](%20, %33, %34)
[DUMP profiling_graph_executor_impl.cpp:499]   %38 : Tensor = prim::CallMethod[name="forward"](%19, %35)
[DUMP profiling_graph_executor_impl.cpp:499]   %39 : Tensor = prim::CallMethod[name="forward"](%17, %36)
[DUMP profiling_graph_executor_impl.cpp:499]   %40 : Tensor = prim::CallMethod[name="forward"](%15, %37)
[DUMP profiling_graph_executor_impl.cpp:499]   %41 : Tensor = prim::profile[profiled_type=Float(1:131072, 32768:4, 4:1, requires_grad=0, device=cpu)](%38)
[DUMP profiling_graph_executor_impl.cpp:499]   %42 : Tensor = prim::profile[profiled_type=Float(1:32768, 8192:4, 4:1, requires_grad=0, device=cpu)](%39)
[DUMP profiling_graph_executor_impl.cpp:499]   %43 : Tensor = prim::profile[profiled_type=Float(1:8192, 2048:4, 4:1, requires_grad=0, device=cpu)](%40)
```

The fix should be landed shortly : https://github.com/pytorch/pytorch/pull/46479

CC: @gchanan  @suo

**Closed** 2020-10-19 19:27 UTC
Labels: high priority, oncall: jit, triage review

**Comment by jeffryuiop** [comment] 2021-05-03 08:07
Hi, I think im gonna post here since this is about a possible leak in a retinaface model read by jit trace. So when a face detection job is distributed using openmpi, the memory usage grows to up to 100 gb. This prompted me to check using valgrind. the leak summary is as follows:
==71193== LEAK SUMMARY:
==71193==    definitely lost: 0 bytes in 0 blocks
==71193==    indirectly lost: 0 bytes in 0 blocks
==71193==      possibly lost: 4,956,000 bytes in 6 blocks
==71193==    still reachable: 776,523 bytes in 12,086 blocks
==71193==         suppressed: 0 bytes in 0 blocks

i noticed here that the possibly lost memory is bigger, particularly when compared to other model. 
I am using pytorch c++ 1.8.1 for the inference.

**Comment by liubamboo** [comment] 2021-05-19 08:51
I try to add 
`torch::jit::getProfilingMode() = false;`
before
`module_ = torch::jit::load(model_path);`

and it seem to work. I run the program 5 times and there is no memory leak now. But the inference time increases.
Before add the code `torch::jit::getProfilingMode() = false;`I run the yolov5s, and it cost 20ms
After add the code `torch::jit::getProfilingMode() = false;`I run the yolov5s, and it cost 23-30ms

I don't know whether there is a better solution?

**Comment by liubamboo** [comment] 2021-05-25 16:27
@xsacha thanks, I have the same problem. use libtorch 1.8.0, so could you tell me how to solve it?

**Comment by xsacha** [comment] 2021-06-18 19:02
@liubamboo if you still get an issue in 1.8.0+, it's not likely related to this issue.
Are you using autocast in the C++? That can cause a leak like you've described. You only need to autocast the trace.
