### ISSUE TITLE
[Windows] Intermittent error in THAllocator.c:162 - MapViewOfFile returns 0x5 (ERROR_ACCESS_DENIED)

### ISSUE THREAD

**Issue by jhostetler** [pytorch/pytorch#4239] opened 2017-12-18 20:05 UTC
Following this tutorial, Section 4:
`http://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html#sphx-glr-beginner-blitz-cifar10-tutorial-py`

On the **first run only**, received following error:
`RuntimeError: Couldn't map view of shared file <torch_4600_2309694667>, error code: <5> at D:\pytorch\pytorch\torch\lib\TH\THAllocator.c:162`

Note that `D:\` is a DVD drive on my machine. Torch is actually installed on drive `C:\` under `C:\Users\<user-name>\AppData\conda\...`
Error occurred during epoch 2, between iterations 8000-10000.

Re-ran 5 times afterwards without error.

Windows 10 x64, Python 3.6, PyTorch 0.3.0, installed via:
`conda install -c peterjc123 pytorch cuda80`

(see [https://github.com/pytorch/pytorch/issues/494#issuecomment-350527200](url))

Stack trace:
```
File "C:\<path elided>\torch\utils\data\dataloader.py", line 210, in __next__
    return self._process_next_batch(batch)
  File "C:\<path elided>\torch\utils\data\dataloader.py", line 230, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
RuntimeError: Traceback (most recent call last):
  File "C:\<path elided>\torch\utils\data\dataloader.py", line 42, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "C:\<path elided>\torch\utils\data\dataloader.py", line 119, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "C:\<path elided>\torch\utils\data\dataloader.py", line 119, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "C:\<path elided>\torch\utils\data\dataloader.py", line 94, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "C:\<path elided>\torch\storage.py", line 111, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: Couldn't map view of shared file <torch_4600_2309694667>, error code: <5> at D:\pytorch\pytorch\torch\lib\TH\THAllocator.c:162
```

Code (note that my 'data/' directory is in parent directory of code directory):

```
import multiprocessing

import torch
import torchvision
import torchvision.transforms as transforms

import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


class Net(nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.conv1 = nn.Conv2d(3, 6, 5)
    self.pool = nn.MaxPool2d(2, 2)
    self.conv2 = nn.Conv2d(6, 16, 5)
    self.fc1 = nn.Linear(16 * 5 * 5, 120)
    self.fc2 = nn.Linear(120, 84)
    self.fc3 = nn.Linear(84, 10)

  def forward(self, x):
    x = self.pool(F.relu(self.conv1(x)))
    x = self.pool(F.relu(self.conv2(x)))
    x = x.view(-1, 16 * 5 * 5)
    x = F.relu(self.fc1(x))
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x

# Must have the next two lines or won't work on Windows
if __name__ == "__main__":
  multiprocessing.freeze_support()

  transform = transforms.Compose(
    [transforms.ToTensor(),
     transforms.Normalize( (0.5, 0.5, 0.5), (0.5, 0.5, 0.5) )] )
     
  trainset    = torchvision.datasets.CIFAR10( root="../data", train=True, transform=transform )
  trainloader = torch.utils.data.DataLoader( trainset, batch_size=4, shuffle=True, num_workers=2 )

  testset     = torchvision.datasets.CIFAR10( root="../data", train=False, transform=transform )
  testloader  = torch.utils.data.DataLoader( testset, batch_size=4, shuffle=False, num_workers=2 )

  classes = ("plane", "car", "bird", "cat", "deer", "dog", "frog", "horse", "ship", "truck")

  dataiter = iter(trainloader)
  images, labels = dataiter.next()
  
  net = Net()
  criterion = nn.CrossEntropyLoss()
  optimizer = optim.SGD( net.parameters(), lr=0.001, momentum=0.9 )
  
  for epoch in range(2):
    running_loss = 0.0
    for i, data in enumerate(trainloader):
      inputs, labels = data
      inputs, labels = autograd.Variable(inputs), autograd.Variable(labels)
      optimizer.zero_grad()
      
      outputs = net( inputs )
      loss = criterion( outputs, labels )
      loss.backward()
      optimizer.step()
      
      running_loss += loss.data[0]
      if i % 2000 == 1999:
        print( "[{:d}, {:5d}] loss: {:.3f}".format( epoch + 1, i + 1, running_loss / 2000 ) )
        running_loss = 0
        
  print( "done" )
```

cc @peterjc123

**Comment by peterjc123** [comment] 2017-12-22 16:27
@jhostetler According to the post [here](https://stackoverflow.com/questions/16027268/why-does-mapviewoffile-fail-with-error-access-denied), there's a possible explanation. The file mapping name was randomly generated, however the names seem to be the same at the same time, causing the later one to be rejected due to the difference in size. It's very rare, for it is almost impossible to get the the same random 64-bit number in such a short time in a process.

**Comment by aitaoquanyi** [comment] 2018-01-26 05:52
@jhostetler hi! I also met this problem, is it right now? thanks

**Comment by aitaoquanyi** [comment] 2018-01-26 05:53
@jhostetler So I set the worker 0(I find the training becomes  slower)

**Comment by peterjc123** [comment] 2018-01-26 05:54
@aitaoquanyi Can you please try whether num_worker = 1 helps?

**Comment by aitaoquanyi** [comment] 2018-01-26 06:01
@peterjc123 
![image](https://user-images.githubusercontent.com/30489150/35426913-567b3a48-02a1-11e8-9a71-798fe05a737d.png), i set worker = 1, but also fail.

**Comment by aitaoquanyi** [comment] 2018-01-26 06:02
@jhostetler  set worker = 0, it can work well, but much slower.

**Comment by peterjc123** [comment] 2018-01-26 06:03
The error code is different from here,okay, please send it [here](https://github.com/pytorch/pytorch/issues/3019#issuecomment-360692179).

**Comment by aitaoquanyi** [comment] 2018-01-26 06:13
@peterjc123 Is there any other way to read the image besides this method in pytorch?

**Comment by peterjc123** [comment] 2018-01-26 06:17
@aitaoquanyi You may write a DataLoader by yourself. And someone has written [one](https://github.com/fastai/fastai/blob/master/fastai/dataloader.py). But I think it will be as slow as `num_worker = 0`.

**Comment by aitaoquanyi** [comment] 2018-01-26 06:18
@peterjc123 thanks.

**Comment by redknightlois** [comment] 2019-08-16 13:23
`num_worker = 0` works, but that is no solution; the loading process is slow as hell in my case. I cannot sustain the GPU at more than 5% and couldnt find any clue of what might be happening to work around it. Any idea?

**Comment by peterjc123** [comment] 2019-08-16 13:43
@redknightlois Is the error code 5 or 1455?

**Comment by Blackhex** [comment] 2022-10-11 08:50
This does not seem to be reproducible with Windows 11, Python 3.9.13, and PyTorch 1.10.2. The following change to the mentioned script was needed:
```
67c67
<       running_loss += loss.data[0]
---
>       running_loss += loss.item()
```
Note that the issue was reported on quite old version of PyTorch 0.3.0 so I'd close it as obsolete/won't reproduce.

**Closed** 2022-10-17 13:36 UTC
Labels: module: windows, triaged
