### ISSUE TITLE
C++ CUDA Project in Windows  - Second call to DNN Module::forward() throws exception

### ISSUE THREAD

**Issue by rtrahms** [pytorch/pytorch#47590] opened 2020-11-09 04:50 UTC
## Environment/Setup

Using libtorch 1.7.0 / CUDA 10.1 / MS Visual Studio 2019

Using torchscript model pt file.

## To Reproduce

To reproduce:
1) Confirm CUDA device is present by checking torch::cuda::is_available() and torch::cuda::device_count()
2) Load a model using the torch::jit::script::Module class and torch::jit::load() to specify the pt torchscript file to load.  
3) Specify module.to(kCUDA) for CUDA DNN
4) Load an image and convert to a tensor:

    half_ = true // CUDA FP16
    cv::cvtColor(img_input, img_input, cv::COLOR_BGR2RGB);  // BGR -> RGB
    img_input.convertTo(img_input, CV_32FC3, 1.0f / 255.0f);  // normalization 1/255
    auto tensor_img = torch::from_blob(img_input.data, { 1, img_input.rows, img_input.cols, img_input.channels() }).to(kCUDA);

    tensor_img = tensor_img.permute({ 0, 3, 1, 2 }).contiguous();  // BHWC -> BCHW (Batch, Channel, Height, Width)

    if (half_) {
        tensor_img = tensor_img.to(torch::kHalf);
    }
    std::vector<torch::jit::IValue> inputs;
    inputs.emplace_back(tensor_img);

5) Perform inference:
       torch::jit::IValue output = module_.forward(inputs);

The first time this forward() call is made, it works.  Any subsequent call will throw an exception.  When using the kCPU version of this code, no exception is thrown.

## Expected behavior

Once a module is loaded, repeated calls to Module::forward() should return without exception.

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi @gmagogsfm

**Comment by mszhanyi** [comment] 2020-11-10 07:35
@rtrahms , thank your feedback. Could you attach your example (.py and .pt) that I could reproduce it easily?

**Comment by rtrahms** [comment] 2020-11-11 01:35
Not a python file but a libtorch cpp file, and a supporting Detector class cpp/h files.  Built into a MS Visual Studio 2019 project and linking with libtorch libraries.
[libTorchTestApp4.zip](https://github.com/pytorch/pytorch/files/5521136/libTorchTestApp4.zip)

**Comment by rtrahms** [comment] 2020-11-11 01:38
CUDA PT file for the network attached.
[yolov5s_ob12.torchscript-cuda.zip](https://github.com/pytorch/pytorch/files/5521143/yolov5s_ob12.torchscript-cuda.zip)

**Comment by mszhanyi** [comment] 2020-11-12 04:17
> CUDA PT file for the network attached.
> [yolov5s_ob12.torchscript-cuda.zip](https://github.com/pytorch/pytorch/files/5521143/yolov5s_ob12.torchscript-cuda.zip)
> 
> Labels file as well.
> [labels_ob_12.txt](https://github.com/pytorch/pytorch/files/5521149/labels_ob_12.txt)

@rtarquini , thank your reply. could you provide the image file

**Comment by rtrahms** [comment] 2020-11-12 14:14
It is just a standard JPG image loaded with OpenCV.  You can use any image file really.  The point is it shouldn't crash on feeding the image into forward() on the second pass.

**Comment by mszhanyi** [comment] 2020-11-16 06:41
@rtrahms, I tried your example and it passed.
I used py1.7.0+cu110 because there's cu110 in my local machine. opencv is opencv-4.5.0. vs2019 version is 16.7.7.
For convenience, I added torch path and opencv path in PATH.
![image](https://user-images.githubusercontent.com/16190118/99219967-ae16fb80-2818-11eb-8391-2042931ce7bf.png)
The test result is
![image](https://user-images.githubusercontent.com/16190118/99220008-c7b84300-2818-11eb-96ba-29271c367053.png)
The cmakelist file is attached.
[CMakeLists.txt](https://github.com/pytorch/pytorch/files/5544479/CMakeLists.txt)

The image I used is [Lenna](https://2.bp.blogspot.com/-Su3GDkjr5sE/VmXLcPz9tCI/AAAAAAAABcE/OGFk3z4-7Uo/s320/Lenna.png)

**Comment by mszhanyi** [comment] 2020-11-17 03:44
@rtrahms , I double checked with https://download.pytorch.org/libtorch/cu101/libtorch-win-shared-with-deps-debug-1.7.0%2Bcu101.zip. It passed too.

**Comment by mszhanyi** [comment] 2020-11-18 02:20
Close this issue since it 's not a bug. @rtrahms , feel free to reopen it if you have any new findings

**Closed by mszhanyi** 2020-11-18 02:20 UTC
Labels: module: windows, oncall: jit, windows-triaged

**Comment by DBraun** [comment] 2020-12-31 22:11
@rtrahms What was the solution?
