### ISSUE TITLE
Cannot export ScriptModule models to ONNX format

### ISSUE THREAD

**Issue by whl287** [pytorch/pytorch#34002] opened 2020-02-29 07:29 UTC
## 🐛 Bug

when i try to export a script module to onnx format, i got a runtime error
## To Reproduce
import torch
import torchvision

model = torchvision.models.resnet18(pretrained = True)
model2 = torch.jit.script(model)
input = torch.rand([1, 3, 224, 224])
example_output = torch.rand([1, 1000])
torch.onnx.export(model2, input, "resnet18.onnx", example_outputs = example_output)

(pytorch) D:\test>python test2.py
Traceback (most recent call last):
  File "test2.py", line 8, in <module>
    torch.onnx.export(model2, input, "resnet18.onnx", example_outputs = example_output)
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\onnx\__init__.py", line 144, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\onnx\utils.py", line 62, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\onnx\utils.py", line 411, in _export
    graph, params_dict, torch_out = _model_to_graph(model, args, verbose,
  File "C:\ProgramData\Anaconda3\envs\pytorch\lib\site-packages\torch\onnx\utils.py", line 265, in _model_to_graph
    method_graph, params = torch._C._jit_pass_lower_graph(model.forward.graph, model._c)
RuntimeError:
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="num_batches_tracked"](%7347, %7363)
:

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):  1.4
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.8.1 
 - CUDA/cuDNN version: 
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @suo @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by qianoh** [comment] 2020-04-02 08:34
I met the same problem. Please if anyone has an insight?

Best

**Comment by qianoh** [comment] 2020-04-02 08:54
@whl287 Hey would you mind sharing if you find a solution for this? Best

**Comment by suo** [comment] 2020-04-03 18:02
cc @spandantiwari as this appears related to trying to export a scriptmodule?

**Comment by qianoh** [comment] 2020-04-07 03:52
> cc @spandantiwari as this appears related to trying to export a scriptmodule?

For me it happens when we already have the scriptmodule (converted from pytorch model) and we try to export scriptmodule to onnx

**Comment by IlyaOvodov** [comment] 2020-04-13 07:08
@suo, @spandantiwari
Brief repro for it:
```
class MyClass(nn.Module):
    def __init__(self):
        super(MyClass, self).__init__()
        self.num_batches_tracked = 0
    def forward(self, x):
        self.num_batches_tracked = 1
        return x
model = MyClass()
img = torch.zeros((2, 3,))
torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img) # OK
model = torch.jit.script(model)
torch.onnx.export(model, img, 'f.onnx', verbose=False, opset_version=11, example_outputs=img) # fail
```
->
```
Traceback (most recent call last):
  File "d:\programming\3rd_party\pytorch\pytorch_master\torch\onnx\utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "d:\programming\3rd_party\pytorch\pytorch_master\torch\onnx\utils.py", line 320, in _model_to_graph
    method_graph, params = torch._C._jit_pass_lower_graph(model.forward.graph, model._c)
RuntimeError: 
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="num_batches_tracked"](%self, %2)
:
Process finished with exit code 1
```
torch version: both 1.5.0a0+2dc2933 and 1.4.0

Attribute is changed inside forward() at least in nn.BatchNorm2d (and I suppose not only in BatchNorm2d), so almost  any net can't be converted to ONNX using TorchScript.

**Comment by mdlockyer** [comment] 2020-04-29 22:13
I'm experience the same issue on 1.5.0. Haven't tested on an older version

**Comment by IlyaOvodov** [comment] 2020-05-02 16:09
Actually num_batches_tracked attribute in a BatchNorm module is an only place causing such a problem when exporting resnet to ONNX via TorchScript. It can be fixed by making self.traing as constant in _BatchNorm module (file: torch\nn\modules\batchnorm.py):
```
class _BatchNorm(_NormBase):
    __constants__ = ['training'] # fix issue #37672 34002
    def __init__(self, num_features, eps=1e-5, momentum=0.1, affine=True,
                 track_running_stats=True):
    .......
```
This modification closes this issue. But I don't propose it as PR because because it can spoil some other functionality: I'm not sure it is a good idea to always consider self.training as constant in scripted modules.
Still more general cause of the problem (module attributes can't be changed when exporting scriped module to ONNX) still persists and I am opening separate issue for this.

**Comment by kjdorow7** [comment] 2020-07-08 15:47
I have the same issue with:
torch                 1.5.1                
torchaudio        0.5.1                
torchvision        0.6.1
Setting training as a constant in batchnorm.py did not make a difference and I ran exactly what @IlyaOvodov ran.
```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    torch.onnx.export(model, img, 'f.onnx', example_outputs=img) # fail
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/utils.py", line 320, in _model_to_graph
    method_graph, params = torch._C._jit_pass_lower_graph(model.forward.graph, model._c)
RuntimeError: 
temporary: the only valid use of a module is looking up an attribute but found  = prim::SetAttr[name="num_batches_tracked"](%self, %2)
:
```

**Comment by kjdorow7** [comment] 2020-07-10 16:36
So upon further experimentation, I made some interesting discoveries that I felt was worthwhile to share.
With torch==1.3.1, if you run
```
class LoopModel2(torch.nn.Module):
    def __init__(self):
        super(LoopModel2, self).__init__()
        self.work = torch.ones(2, 3, dtype=torch.long)
        self.test: bool = True

    def forward(self, x, y):
        if self.test:
            for i in range(int(y)):
                x = x + i
            return x

model = torch.jit.script(LoopModel2())
dummy_input = torch.ones(2, 3, dtype=torch.long)
loop_count = torch.tensor(5, dtype=torch.long)
torch.onnx.export(model, (dummy_input, loop_count), 'loop.onnx', example_outputs=dummy_input)

print("Yeah we made it!")
```
Then you will get:
```
Traceback (most recent call last):
  File "test2.py", line 25, in <module>
    torch.onnx.export(model, (dummy_input, loop_count), 'loop.onnx', example_outputs=dummy_input)
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/onnx/utils.py", line 235, in _model_to_graph
    method_graph, params = model.forward._lowered_graph()
RuntimeError: isTensor() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/core/ivalue_inl.h:90, please report a bug to PyTorch. Expected Tensor but got Bool (toTensor at /pytorch/aten/src/ATen/core/ivalue_inl.h:90)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7fbfc7688813 in /home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x1876251 (0x7fbfc9351251 in /home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #2: torch::jit::script::Method::_lowered_graph() + 0x161 (0x7fbfcbaf4771 in /home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/lib/libtorch.so)
frame #3: <unknown function> + 0x5b1908 (0x7fc00fca8908 in /home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x210ba4 (0x7fc00f907ba4 in /home/USERNAME/anaconda3/envs/ENVNAME/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #28: __libc_start_main + 0xf0 (0x7fc01e26c830 in /lib/x86_64-linux-gnu/libc.so.6)
```
This error occurs because the attribute self.test is being used within the forward function. If you remove it from the forward function, the code will run fine.

torch==1.5.1 appears to have more complicated issues with its attributes. It will produces the same error with the code above, but without any of the info on frames. In addition to that, running the code below results in the error from my previous comment.
```
class MyClass(nn.Module):
    def __init__(self):
        super(MyClass, self).__init__()
        self.num_batches_tracked: int = 0
    def forward(self, x):
        self.num_batches_tracked += 1
        return x

model = MyClass()
img = torch.zeros((2, 3))
torch.onnx.export(model, img, 'f.onnx', example_outputs=img) # OK
model = torch.jit.script(model)
torch.onnx.export(model, img, 'f.onnx', example_outputs=img) # fail
```
However, if you were to run:
```
class MyClass(nn.Module):
    def __init__(self):
        super(MyClass, self).__init__()
        self.num_batches_tracked = torch.ones(2, 3, dtype=torch.long)
    def forward(self, x):
        self.num_batches_tracked[[0]] += 1
        return x
```
Then it will export to ONNX just fine as a script module.
It seems to me that with 1.5.1 that ONNX is only allowing attributes that are torch.Tensors to be ran. Anything else just results in that bizarre error from my comment above. Again, I'm still an up and coming learner with ONNX and TorchScript, I but I thought it would be worthwhile to share my observations.
 
Until these issues are resolved, a work-around for this bug seems to be to revert to PyTorch 1.3.1 and deal with the less tedious errors there. Anyone else have any thoughts?

**Comment by chriss2401** [comment] 2020-07-16 16:01
Following since I am having also the same issue.

**Comment by j-paulus** [comment] 2020-08-20 07:22
I'm observing the same BN problem when trying to export a scripted model. I tried to modify _BatchNorm the way @IlyaOvodov suggested with the constant definition. Tested with torch 1.5, 1.6, and 1.7-dev20200819, and it fails with all of them the same way: 

>   File "torch_2_onnx_test.py", line 73, in run_conversion
>     torch.onnx.export(model, (example_input,), new_file_name,
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/__init__.py", line 203, in export
>     return utils.export(model, args, f, export_params, verbose, training,
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
>     _export(model, args, f, export_params, verbose, training, input_names, output_names,
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/utils.py", line 517, in _export
>     with select_model_mode_for_export(model, training):
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/contextlib.py", line 113, in __enter__
>     return next(self.gen)
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/utils.py", line 63, in select_model_mode_for_export
>     model.train(is_export_training)
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1270, in train
>     module.train(mode)
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1268, in train
>     self.training = mode
>   File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/jit/__init__.py", line 2065, in __setattr__
>     self._c.setattr(attr, value)
> RuntimeError: Can't set constant 'training' which has value:False

I would somehow prefer exporting to ONNX from the scripted model, which is already there instead of using the "plain" model and having the headaches from tracing. So, going to keep on watching updates here.

**Comment by EZ4NO1** [comment] 2021-03-01 03:18
> I'm observing the same BN problem when trying to export a scripted model. I tried to modify _BatchNorm the way @IlyaOvodov suggested with the constant definition. Tested with torch 1.5, 1.6, and 1.7-dev20200819, and it fails with all of them the same way:
> 
> > File "torch_2_onnx_test.py", line 73, in run_conversion
> > torch.onnx.export(model, (example_input,), new_file_name,
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/**init**.py", line 203, in export
> > return utils.export(model, args, f, export_params, verbose, training,
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/utils.py", line 86, in export
> > _export(model, args, f, export_params, verbose, training, input_names, output_names,
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/utils.py", line 517, in _export
> > with select_model_mode_for_export(model, training):
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/contextlib.py", line 113, in **enter**
> > return next(self.gen)
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/onnx/utils.py", line 63, in select_model_mode_for_export
> > model.train(is_export_training)
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1270, in train
> > module.train(mode)
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1268, in train
> > self.training = mode
> > File "/opt/anaconda3/envs/torch1.6/lib/python3.8/site-packages/torch/jit/**init**.py", line 2065, in **setattr**
> > self._c.setattr(attr, value)
> > RuntimeError: Can't set constant 'training' which has value:False
> 
> I would somehow prefer exporting to ONNX from the scripted model, which is already there instead of using the "plain" model and having the headaches from tracing. So, going to keep on watching updates here.

meet the same problem

**Comment by isgursoy** [comment] 2021-12-09 01:13
Same with torch 1.10

**Comment by garymm** [comment] 2022-03-01 22:46
Original code from @whl287 and smaller repro from @IlyaOvodov both seem to work properly with torch 1.10.0, torchvision 0.11.1, so closing the issue. If someone still has problems please open a new issue with clear reproduction code including the call to `torch.onnx.export` and everything before it.

**Closed by garymm** 2022-03-01 22:46 UTC
Labels: oncall: jit, module: onnx, triaged
