### ISSUE TITLE
what():  version_number <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by MrWXfaster** [pytorch/pytorch#62309] opened 2021-07-28 06:18 UTC
## To Reproduce

terminate called after throwing an instance of 'c10::Error'
  what():  version_number <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED at /pytorch/caffe2/serialize/inline_container.cc:131, please report a bug to PyTorch. Attempted to read a PyTorch file with version 3, but the maximum supported version for reading is 1. Your PyTorch installation may be too old. (init at /pytorch/caffe2/serialize/inline_container.cc:131)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f5ae350c273 in /home/wx/libtorch/lib/libc10.so)
frame #1: caffe2::serialize::PyTorchStreamReader::init() + 0x1e9a (0x7f5ae626fd7a in /home/wx/libtorch/lib/libtorch.so)
frame #2: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >) + 0x53 (0x7f5ae6270f33 in /home/wx/libtorch/lib/libtorch.so)
frame #3: <unknown function> + 0x3c1ba42 (0x7f5ae734ea42 in /home/wx/libtorch/lib/libtorch.so)
frame #4: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x27 (0x7f5ae734d997 in /home/wx/libtorch/lib/libtorch.so)
frame #5: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x69 (0x7f5ae734dcd9 in /home/wx/libtorch/lib/libtorch.so)
frame #6: ./deblurgan() [0x40ee9b]
frame #7: __libc_start_main + 0xf0 (0x7f5ae18c0840 in /lib/x86_64-linux-gnu/libc.so.6)
frame #8: ./deblurgan() [0x40ea09]

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):libtorch-shared-with-deps-latest， cuda10.0
 - OS (e.g., Linux):ubuntu16.04
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Build command you used (if compiling from source):cmake -DCMAKE_PREFIX_PATH=/home/wx/libtorch ..
 - Python version:3.6
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:
CMakeList.txt

cmake_minimum_required(VERSION 3.5.1)
project(DeblurGan)
 
find_package(Torch REQUIRED)
find_package( OpenCV REQUIRED )
include_directories( ${OpenCV_INCLUDE_DIRS} )
 
add_executable(deblurgan deblurgan.cpp)
target_link_libraries(deblurgan "${TORCH_LIBRARIES}" ${OpenCV_LIBS} stdc++fs)
set_property(TARGET deblurgan PROPERTY CXX_STANDARD 11
## Additional context

cc @mruberry

**Comment by bdhirsh** [comment] 2021-07-28 15:28
Hi,

Providing a small program that reproduces the issue would help, since it's otherwise difficult to tell what's causing the internal assert. The error looks like it's indicating that you should try running with a newer version of PyTorch though?

**Comment by MrWXfaster** [comment] 2021-07-28 15:32
Hi， I have fix the issue!I change CMakeLists.txt，



---Original---
From: "Brian ***@***.***&gt;
Date: Wed, Jul 28, 2021 23:28 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [pytorch/pytorch] what():  version_number <= kMaxSupportedFileFormatVersion INTERNAL ASSERT FAILED (#62309)




 
Hi,
 
Providing a small program that reproduces the issue would help, since it's otherwise difficult to tell what's causing the internal assert. The error looks like it's indicating that you should try running with a newer version of PyTorch though?

**Comment by bdhirsh** [comment] 2021-07-28 15:33
Great. Closing the issue!

**Closed by bdhirsh** 2021-07-28 15:33 UTC
Labels: caffe2, module: assert failure, module: serialization, needs reproduction

**Comment by fujiawei0724** [comment] 2022-07-18 14:46
How to change the cmakelist? Could you tell me the details?
