### ISSUE TITLE
Multiple linux jobs are failing with version `GLIBCXX_3.4.30' not found 

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#105248] opened 2023-07-14 22:07 UTC
## Current Status
mitigated by reverting

## Error looks like
Linux jobs are failing with following error:
```
+ python -c 'import torch; torch._C._crash_if_debug_asserts_fail(424242)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/__init__.py", line 236, in <module>
    from torch._C import *  # noqa: F403
ImportError: /opt/conda/envs/py_3.10/bin/../lib/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
```

## Incident timeline (all times pacific)
5:00PM EST Issue start happening
5:45PM EST Issue was noticed and OSS CI channel advised

## User impact
multiple inductor, periodic, pull and trunk jobs are failing

## Root cause
tbd

## Mitigation
tbd

## Prevention/followups
tbd

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by malfet** [comment] 2023-07-14 22:08
Judging by the fact that all jobs that are failing are Bionic ones, conda updates strikes again...

**Comment by atalman** [comment] 2023-07-14 23:07
Somehow on latest docker build it installs gcc-13

```
2023-07-14T20:55:25.0355613Z The following additional packages will be installed:
2023-07-14T20:55:25.0356267Z   cpp-9 gcc-11-base gcc-13-base gcc-9 gcc-9-base libasan5 libatomic1 libcc1-0
2023-07-14T20:55:25.0357352Z   libgcc-9-dev libgcc-s1 libgomp1 libitm1 liblsan0 libquadmath0
2023-07-14T20:55:25.0360052Z   libstdc++-9-dev libstdc++6 libtsan0 libubsan1
2023-07-14T20:55:25.0366947Z Suggested packages:
2023-07-14T20:55:25.0367343Z   gcc-9-locales g++-9-multilib gcc-9-doc libstdc++6-9-dbg gcc-9-multilib
2023-07-14T20:55:25.0367753Z   libgcc1-dbg libgomp1-dbg libitm1-dbg libatomic1-dbg libasan5-dbg
2023-07-14T20:55:25.0368173Z   liblsan0-dbg libtsan0-dbg libubsan1-dbg libquadmath0-dbg libstdc++-9-doc
2023-07-14T20:55:25.0723070Z The following NEW packages will be installed:
2023-07-14T20:55:25.0724035Z   cpp-9 g++-9 gcc-11-base gcc-13-base gcc-9 gcc-9-base libasan5 libgcc-9-dev
2023-07-14T20:55:25.0728821Z   libgcc-s1 libstdc++-9-dev libubsan1
2023-07-14T20:55:25.0732848Z The following packages will be upgraded:
2023-07-14T20:55:25.0735237Z   libatomic1 libcc1-0 libgomp1 libitm1 liblsan0 libquadmath0 libstdc++6
2023-07-14T20:55:25.0738340Z   libtsan0
2023-07-14T20:55:25.2283959Z 8 upgraded, 11 newly installed, 0 to remove and 33 not upgraded.
2023-07-14T20:55:25.2284249Z Need to get 30.5 MB of archives.
2023-07-14T20:55:25.2284532Z After this operation, 122 MB of additional disk space will be used.
2023-07-14T20:55:25.2285111Z Get:1 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 gcc-13-base amd64 13.1.0-8ubuntu1~18.04 [19.1 kB]
```

**Comment by huydhn** [comment] 2023-07-14 23:17
I think this is correct root cause. Conda has `/opt/conda/envs/py_3.8/lib/libstdc++.so.6` and bionic has `/usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32`.  And `strings /opt/conda/envs/py_3.8/lib/libstdc++.so.6 | grep GLIBCXX_3.4.30` showed nothing while `strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.32 | grep GLIBCXX_3.4.30` found a match. 

The package (`libstdc++6 13.1.0-8ubuntu1~18.04)` come from `http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu` as @atalman points out:
```
(py_3.8) jenkins@110d36e9d7dc:/$ apt-cache policy libstdc++6
libstdc++6:
  Installed: 13.1.0-8ubuntu1~18.04
  Candidate: 13.1.0-8ubuntu1~18.04
  Version table:
 *** 13.1.0-8ubuntu1~18.04 500
        500 http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     8.4.0-1ubuntu1~18.04 500
        500 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages
        500 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages
     8-20180414-1ubuntu2 500
        500 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages
```

**Comment by malfet** [comment] 2023-07-15 00:49
@huydhn thank you for the investigation. So it sounds like what we have to do is to force conda not to install its libstdc++ as we don't need it in CI at all, do we?

**Comment by huydhn** [comment] 2023-07-15 01:40
> Also, I still can't reproduce it on PR, which means that docker builds aren't actually doing a thing...

I think the reason isn't reproducible in PR is due to the way we use `git rev-parse HEAD:.ci/docker` to calculate the Docker tag.  In https://github.com/pytorch/pytorch/pull/105227, you reland the change in https://hud.pytorch.org/pytorch/pytorch/commit/634659e262f82bbc76aa776119c9fea079fbffe3.  Because there is no change, the Docker tag is exactly the same, i.e. `4d35a7f72ddc3207f31647ddfffdddd467d4d60c`.  So here is what happens:

1. Docker build rebuilds the image.  This is correct.
2. On the other hand, CI jobs will check to see if an image with the tag `4d35a7f72ddc3207f31647ddfffdddd467d4d60c` exists and it does.  So the job uses that instead.  However, this image is the one built yesterday by https://hud.pytorch.org/pytorch/pytorch/commit/634659e262f82bbc76aa776119c9fea079fbffe3.   This predates the recent libstdc++ issue, so you would see any failure on your PR.

One way to reproduce it is to delete bionic images with tag `4d35a7f72ddc3207f31647ddfffdddd467d4d60c` on ECR, for example `308535385114.dkr.ecr.us-east-1.amazonaws.com/pytorch/pytorch-linux-bionic-cuda11.8-cudnn8-py3-gcc9:4d35a7f72ddc3207f31647ddfffdddd467d4d60c`.  Then the corresponding job on PR will rebuild the image, use it, and will fail accordingly.

**Comment by malfet** [comment] 2023-07-15 14:18
Ok, simply deleting `/opt/conda/envs/py_3.10/lib/libstdc++.so.6` fixes the problem for all builds but bazel...

**Comment by huydhn** [comment] 2024-01-17 03:01
Closing this issue now as the issue has been fixed by https://github.com/pytorch/pytorch/commit/5837e95d303464141009b8072636bb4442e2fcb2

**Closed by huydhn** 2024-01-17 03:01 UTC
Labels: module: ci, triaged
