### ISSUE TITLE
JIT fails for some types of attributes in the latest nightly

### ISSUE THREAD

**Issue by IgnacioJPickering** [pytorch/pytorch#58515] opened 2021-05-18 22:55 UTC
## 🐛 Bug

When setting attributes in a module, if the attribute set is a python class with a dict that has strings as keys 
JIT will fail, but if the main class has a dict with strings JIT works fine. 
This is an issue only with the nightly.

## To Reproduce

```
import torch

class Module(torch.nn.Module):

    def __init__(self, strings):
        super().__init__()
        self.inner = Inner(strings)
        self.map = {k: j for j, k in enumerate(strings)}

    def forward(self, x):
        return x


class Inner:

    def __init__(self, strings):
        self.map = {k: j for j, k in enumerate(strings)}

m = torch.jit.script(Module(['A', 'B', 'C']))
```
This produces the output:

```
Traceback (most recent call last):
  File "torch_bug.py", line 19, in <module>
    m = torch.jit.script(Module(['A', 'B', 'C']))
  File "/home/anaconda3/envs/torchani/lib/python3.7/site-packages/torch/jit/_script.py", line 1097, in script
    obj, torch.jit._recursive.infer_methods_to_compile
  File "/home/anaconda3/envs/torchani/lib/python3.7/site-packages/torch/jit/_recursive.py", line 412, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/home/ignacio/anaconda3/envs/torchani/lib/python3.7/site-packages/torch/jit/_recursive.py", line 474, in create_script_module_impl
    script_module = torch.jit.RecursiveScriptModule._construct(cpp_module, init_fn)
  File "/home/anaconda3/envs/torchani/lib/python3.7/site-packages/torch/jit/_script.py", line 497, in _construct
    init_fn(script_module)
  File "/home/anaconda3/envs/torchani/lib/python3.7/site-packages/torch/jit/_recursive.py", line 437, in init_fn
    cpp_module.setattr(name, orig_value)
RuntimeError: Could not cast attribute 'map' to type Dict[Tensor, int]: Unable to cast Python instance to C++ type (compile in debug mode for details)
```

## Expected behavior

No error

## Environment

```
[pip3] numpy==1.18.1
[pip3] pytorch-memlab==0.2.2
[pip3] torch==1.9.0.dev20210518+cu102
[pip3] torchani==2.3.dev69+g10c9826
[pip3] torchaudio==0.9.0.dev20210415
[pip3] torchvision==0.10.0.dev20210415
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.0.221             h6bb024c_0  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he8ac12f_0  
[conda] mkl_fft                   1.2.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpy-base                1.19.2           py37hfa32c7d_0  
[conda] pytorch-memlab            0.2.2                    pypi_0    pypi
[conda] torch                     1.9.0.dev20210518+cu102          pypi_0    pypi
[conda] torchaudio                0.9.0.dev20210415          pypi_0    pypi
[conda] torchvision               0.10.0.dev20210415          pypi_0    pypi
[conda] torchviz                  0.0.2                    pypi_0    pypi
```
## Additional context

As a workaround in my code I'm making the class `Inner` inherit from `torch.nn.Module` and decorating its methods with `torch.jit.unused`, this seems to work. I'm not sure if this is expected JIT behavior in nightly and now all attributes should be `torch.nn.Module`, or if this is a bug.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @gmagogsfm

**Comment by Lilyjjo** [comment] 2021-05-19 20:18
I can confirm that this behavior was supported in 1.8 and that this error is being thrown on the current master and in the 1.9 release branch. @gmagogsfm this might be high priority to fix

**Comment by gmagogsfm** [comment] 2021-05-19 21:08
Thanks for raising the priority @Lilyjjo. 

Here is error message in debug mode:
```
RuntimeError: Could not cast attribute 'map' to type Dict[Tensor, int]: Unable to cast Python instance of type <class 'str'> to C++ type 'at::Tensor'
```

My guess is that attribute type inference regressed between 1.8 and now.

**Comment by Lilyjjo** [comment] 2021-05-20 20:16
Calling `super().__init__()` in the non-module child class's `__init__` method fixes the issue, but it is still a regression. Looking into it now

**Comment by Lilyjjo** [comment] 2021-05-20 21:42
@SplitInfinity heads up this behavior was introduced in https://github.com/pytorch/pytorch/commit/6866c033d5aa134a83bc1cb84e3e084a7329167f

**Comment by Lilyjjo** [comment] 2021-05-21 20:54
Okay! I have some clarity about what is going on here. The issue isn't a type inference regression and this might be a no-action item.

The root cause of the error is a lack of a type annotation on the `Inner` class's `self.map` attribute. The behavior of TorchScript pre commit https://github.com/pytorch/pytorch/commit/6866c033d5aa134a83bc1cb84e3e084a7329167f was to ignore the attribute with the type `Inner` because it wasn’t scripted and it wasn’t used in the containing `Module` model. The changes in commit https://github.com/pytorch/pytorch/commit/6866c033d5aa134a83bc1cb84e3e084a7329167f activate this error because class `Inner` *is* scriptable so the attribute is retained on the ‘Module’ class even though the attribute is not used. The error is being thrown because `Inner`’s construction in `Module` is incorrect because `Inner.map` is auto inferred to be of type `Dict[Tensor, int]` but is being constructed as type `Dict[str, int]`. 

To fix this error, class `Inner` needs to be properly type annotated like so:
```
class Inner:
    def __init__(self, strings: List[str]):
        self.map: Dict[str, int] = {k: j for j, k in enumerate(strings)}
```

This *might* be considered a BC breaking change because the unused but scriptable attribute of type class `Inner` will cause the class `Module` to not be scriptable when it was scriptable before. I’m not sure why, but adding `super().__init__()` to `Inner`’s constructor causes the class to become unscriptable and ignored post commit  https://github.com/pytorch/pytorch/commit/6866c033d5aa134a83bc1cb84e3e084a7329167f. 

@gmagogsfm @SplitInfinity do y'all have opinons on what action to take on this issue?

**Comment by SplitInfinity** [comment] 2021-05-21 21:30
@Lilyjjo 

Thanks for your quick investigation!

Just curious, is the `Dict[str, int]` annotation needed too? Or is the `List[str]` annotation on `strings` sufficient? I ask because the type of `enumerate` should be inferable as `Tuple[int, str]` in the latter case.

> This might be considered a BC breaking change because the unused but scriptable attribute of type class Inner will cause the class Module to not be scriptable when it was scriptable before.

We can revert the change if the team feels it is necessary but in this regard, 6866c03 is BC-breaking by design (similar to how hooks were ignored before but now they are not).

> I’m not sure why, but adding super().__init__() to Inner’s constructor causes the class to become unscriptable and ignored post commit 6866c03.

This is because 6866c03 tries to compile the class first and does not compile the attribute of that type if the compilation fails.

Stepping back a bit, I think the guidance here should be to advise users to use `__jit_ignored_attributes__` if they know certain attributes won't be used in scripted code (like `self.inner` in this example).

**Comment by Lilyjjo** [comment] 2021-05-21 22:19
@SplitInfinity the `List[str]` annotation is sufficient on its own! Only having the `Dict[str, int]` will cause the class to not compile. 

I'm thinking that a revert isn't required, but we should probably make a release note comment of the BC breaking behavior just to save people some surprise.

**Comment by IgnacioJPickering** [comment] 2021-05-22 01:22
Great, thanks for the fix! Annotatning `strings` with `List[str]` works fine, `__jit_ignored_attributes__` also works perfectly fine and I think it is better for my use case, however, I believe this is undocumented? (at least I couldn't find any examples in the official docs, only in code in the repo).

**Comment by Lilyjjo** [comment] 2021-05-24 20:13
@ansley Hey this is a BC breaking change, is there a section in the release notes we can put this in? https://github.com/pytorch/pytorch/commit/6866c033d5aa134a83bc1cb84e3e084a7329167f

**Comment by Lilyjjo** [comment] 2021-05-24 20:14
Closing because this is an intended breakage. @IgnacioJPickering Thank you for pointing this out!

**Closed by Lilyjjo** 2021-05-24 20:14 UTC
Labels: high priority, oncall: jit, triage review
