### ISSUE TITLE
torch.compile gives "AssertionError: Deduped args out of bounds" for working pytorch code

### ISSUE THREAD

**Issue by jonmorton** [pytorch/pytorch#92925] opened 2023-01-24 22:46 UTC
### 🐛 Describe the bug

Unsure about what this error means exactly, but dynamo is failing an assert with the following code that works fine in eager mode. 
```python
import torch
from einops import rearrange, repeat
from torch import einsum, nn
from torch.nn import functional as F


def sum_squares(t, dim=-1):
    return (t**2).sum(dim=dim)


class VectorQuantization(nn.Module):
    def __init__(self, *, num_clusters, num_heads, dim_per_head, decay=0.999, epsilon=1e-6):
        super().__init__()
        self.decay = decay
        self.epsilon = epsilon
        self.num_heads = num_heads
        self.dim_per_head = dim_per_head
        self.num_clusters = num_clusters

        self.register_buffer("means", torch.randn(num_heads, num_clusters, dim_per_head))

    def forward(self, x, mask=None):
        h, dim_head, num_clusters, eps, decay, means = (
            self.num_heads,
            self.dim_per_head,
            self.num_clusters,
            self.epsilon,
            self.decay,
            self.means,
        )
        assert x.shape[-1] == (
            h * dim_head
        ), f"input embedding feature dimension must be {h * dim_head}"

        # split heads from input
        x = rearrange(x, "b n (h d) -> b n h d", h=h)

        # get distance of input embeddings from means
        dists = (
            rearrange(sum_squares(x), "b n h -> b n h 1")
            - 2 * einsum("b n h d, h k d -> b n h k", x, means)
            + rearrange(sum_squares(means), "h k -> 1 1 h k")
        )

        # get cluster ids
        cluster_ids = dists.argmin(dim=-1)

        if self.training:
            # get one hot, for calculating number of matches per mean
            nearest_one_hot = F.one_hot(cluster_ids, num_classes=num_clusters)
            per_cluster_count = nearest_one_hot.sum(dim=(0, 1))

            # sum of the input per each closest centroid.
            sum_x = einsum("b n h k, b n h d -> h k d", nearest_one_hot.to(x.dtype), x)

            # calculate new means
            new_means = sum_x / (eps + rearrange(per_cluster_count, "... -> ... 1"))

            # exponential moving average
            updated_means = (1.0 - decay) * new_means + decay * means
            self.means.data.copy_(updated_means)

        return cluster_ids


input = torch.randn(4, 32, 512)
model = VectorQuantization(
    num_clusters=512,
    num_heads=32,
    dim_per_head=16,
)

model(input)

model = torch.compile(model)

model(input)
```

Full error:

```
Traceback (most recent call last):
  File "/workspaces/sibyl/repro.py", line 84, in <module>
    model(input)
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _call_impl
    return forward_call(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 82, in forward
    return self.dynamo_ctx(self._orig_mod.forward)(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/workspaces/sibyl/repro.py", line 37, in forward
    x = rearrange(x, "b n (h d) -> b n h d", h=h)
  File "/workspaces/sibyl/repro.py", line 42, in <graph break in forward>
    rearrange(sum_squares(x), "b n h -> b n h 1")
  File "/workspaces/sibyl/repro.py", line 44, in <graph break in forward>
    + rearrange(sum_squares(means), "h k -> 1 1 h k")
  File "/workspaces/sibyl/repro.py", line 54, in <graph break in forward>
    nearest_one_hot = F.one_hot(cluster_ids, num_classes=num_clusters)
  File "/workspaces/sibyl/repro.py", line 63, in <graph break in forward>
    new_means = sum_x / (eps + rearrange(per_cluster_count, "... -> ... 1"))
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 403, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 153, in time_wrapper
    r = func(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 363, in _compile
    check_fn = CheckFunctionManager(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 549, in __init__
    self.check_fn = self.compile_check_fn(
  File "/opt/conda/lib/python3.10/site-packages/torch/_dynamo/guards.py", line 606, in compile_check_fn
    assert pos_b < len(self.output_graph.graphargs) and pos_a < len(
AssertionError: Deduped args out of bounds
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0.dev20230124
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A100-SXM4-40GB
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] torch==2.0.0.dev20230124
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0           py310h7f8727e_0  
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch                   2.0.0.dev20230124 py3.10_cuda11.8_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.8                 h8dd9ede_2    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchtriton               2.0.0+0d7e753227           py310    pytorch-nightly
```

cc @ezyang @gchanan @zou3519 @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment] 2023-01-25 12:47
This is also affecting our benchmark models. Cc @voznesenskym

**Comment by ezyang** [comment] 2023-01-25 15:51
Confirmed the reproducer reproduces for me

**Comment by ezyang** [comment] 2023-01-25 16:05
When I run this with `TORCHDYNAMO_REPRO_AFTER="dynamo"` it segfaults. Upgrading priority.

**Comment by ezyang** [comment] 2023-01-25 16:07
The error still occurs if `backend="eager"` and the minifier script can be written out in this case

**Comment by ezyang** [comment] 2023-01-25 16:07
Reproduced example doesn't trigger error though!

**Comment by ezyang** [comment] 2023-01-25 16:15
Assigned @voznesenskym as the person who introduced this assert

**Comment by ezyang** [comment] 2023-01-25 20:23
The segfaulting minifier command segfaults even when run with the new Triton MLIR backend.

**Comment by jonmorton** [comment] 2023-01-25 22:34
Just realized that although I originally got the error when using cuda, my repro was cpu only. But it seems the error I get is the same in both cases.

**Comment by eellison** [comment] 2023-01-25 23:14
@ezyang applying 

```
diff --git a/torch/_dynamo/output_graph.py b/torch/_dynamo/output_graph.py
index 00b4a7ee821..411c48866ee 100644
--- a/torch/_dynamo/output_graph.py
+++ b/torch/_dynamo/output_graph.py
@@ -673,7 +673,7 @@ class OutputGraph(fx.Tracer, Checkpointable[OutputGraphState]):
             elif config.DO_NOT_USE_legacy_non_fake_example_inputs:
                 compiled_fn = compiler_fn(gm, self.example_inputs())
             else:
-                compiled_fn = compiler_fn(gm, self.fake_example_inputs())
+                compiled_fn = compiler_fn(gm, self.example_inputs())
             _step_logger()(logging.INFO, f"done compiler function {name}")
             assert callable(compiled_fn), "compiler_fn did not return callable"
         except Exception as e:
```

Fixes that FakeTensor error. The root cause is the "eager" backend doesnt support compiling with fake tensors. We can either fix Eager to support it or add an attribute to the compiler like [_boxed_call](https://github.com/pytorch/pytorch/blob/master/torch/_inductor/compile_fx.py#L185-L186) that the compiler doesn't support Fake Tensor example inputs. WDYT ?

**Comment by ezyang** [comment] 2023-01-26 12:56
Isn't the eager backend trivial (it just returns gm.forward directly). Why would it not work with fake example inputs 🤔

**Comment by eellison** [comment] 2023-01-26 21:01
probably because it is running it with fake example inputs but not enabling a mode, so the constructors dont work

**Comment by ezyang** [comment] 2023-01-31 20:00
fixed on master

**Closed by ezyang** 2023-01-31 20:00 UTC
Labels: high priority, module: crash, triaged, oncall: pt2, module: fakeTensor, module: minifier
