### ISSUE TITLE
Export producing wrong overload for aten.mul

### ISSUE THREAD

**Issue by SherlockNoMad** [pytorch/pytorch#123478] opened 2024-04-05 22:09 UTC
### 🐛 Describe the bug

```
class M(torch.nn.Module):
    def forward(self, x):
        return x * 3.2
        
ep = torch.export._trace._export(M(), (x,), strict=False, pre_dispatch=True)
```
is exported as 
```
    class GraphModule(torch.nn.Module):
        def forward(self, arg0_1: "f32[1, 3, 299, 299]"):
            # No stacktrace found for following nodes
            mul: "f32[1, 3, 299, 299]" = torch.ops.aten.mul.Tensor(arg0_1, 3.2);  arg0_1 = None
            return (mul,)
```
This should have aten.mul.Scalar instead. 

### Versions

main

cc @ezyang @bdhirsh @anijain2305 @chauhang @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4 @zou3519

**Comment by angelayi** [comment] 2024-04-05 23:16
I remember asking @ezyang about this long time ago, and iirc the issue is because mul.Scalar was created after mul.Tensor and someone just needs to go and plumb it through the right places.

**Comment by zou3519** [comment] 2024-06-10 21:00
duplicate of https://github.com/pytorch/pytorch/issues/90923

**Closed by zou3519** 2024-06-10 21:00 UTC
Labels: triaged, oncall: pt2, oncall: export, module: pt2-dispatcher, module: export
