### ISSUE TITLE
RuntimeError: Exporting the operator uniform to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

### ISSUE THREAD

**Issue by bmahlbrand** [pytorch/pytorch#54483] opened 2021-03-23 05:15 UTC
## 🐛 Bug

RuntimeError: Exporting the operator uniform to ONNX opset version 12 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

## To Reproduce

```python
class Model(nn.Module):
    def __init__(self, dim, count = 8):
        super().__init__()
        self.w1 = nn.Parameter(torch.randn(count , dim, dim * 4))
        self.w2 = nn.Parameter(torch.randn(count , dim * 4, dim * 4))
        self.w3 = nn.Parameter(torch.randn(count , dim * 4, dim))
        self.act = nn.ELU(inplace = True)

    def forward(self, x):
        hidden1 = self.act(torch.einsum('end,edh->enh', x, self.w1))
        hidden2 = self.act(torch.einsum('end,edh->enh', hidden1, self.w2))
        out = torch.einsum('end,edh->enh', hidden2, self.w3)
        return out
```

1. create model
2. export w/pytorch 1.8 to ONNX

## Expected behavior

I was under the impression from digging through other issues einsum is supported in 1.8 when exporting to ONNX format

## Environment
Collecting environment information...
PyTorch version: 1.8.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.74
GPU models and configuration: GPU 0: GeForce RTX 2070 with Max-Q Design
Nvidia driver version: 456.43
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] pytorch-lightning==1.2.4
[pip3] torch==1.8.0+cu111
[pip3] torchaudio==0.8.0
[pip3] torchfile==0.1.0
[pip3] torchgeometry==0.1.2
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.9.0+cu111
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              h74a9793_1
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38h196d8e1_0
[conda] mkl_fft                   1.3.0            py38h46781fe_0
[conda] mkl_random                1.1.1            py38h47e9c7a_0
[conda] numpy                     1.19.2           py38hadc3359_0
[conda] numpy-base                1.19.2           py38ha3acd2a_0
[conda] pytorch                   1.8.0           py3.8_cuda10.2_cudnn7_0    pytorch
[conda] pytorch-lightning         1.2.4              pyhd8ed1ab_0    conda-forge
[conda] torch                     1.8.0+cu111              pypi_0    pypi
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu102    pytorch

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment] 2021-11-12 18:17
Duplicate of #42230

**Closed by garymm** 2021-11-12 18:17 UTC
Labels: module: onnx, triaged
