### ISSUE TITLE
gather torch.compile fails in backward for bf16 datatype input

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#96290] opened 2023-03-08 09:33 UTC
### 🐛 Describe the bug

Backward call on result for **torch.gather** causes compile error with torch.compile. It works fine in eager mode.

### Error logs

subprocess.CalledProcessError: Command '['g++', '/tmp/torchinductor_jthakur/po/cpohq5ao2egcccxwz4vnfbj2pthvgkfmiqmi2fglpiytflzjkk6y.cpp', '-shared', '-fPIC', '-Wall', '-std=c++17', '-Wno-unused-variable', '-I/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/include', '-I/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/include/torch/csrc/api/include', '-I/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/include/TH', '-I/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/include/THC', '-I/usr/include/python3.8', '-L/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/lib', '-L/usr/lib', '-lc10', '-ltorch', '-ltorch_cpu', '-ltorch_python', '-lgomp', '-DCPU_CAPABILITY_AVX512', '-O3', '-ffast-math', '-fno-finite-math-only', '-march=native', '-fopenmp', '-D', 'C10_USING_CUSTOM_GENERATED_MACROS', '-o/tmp/torchinductor_jthakur/po/cpohq5ao2egcccxwz4vnfbj2pthvgkfmiqmi2fglpiytflzjkk6y.so']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "gather_compile.py", line 18, in <module>
    res_fwd.backward(bwd_tensor)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/autograd/__init__.py", line 204, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2358, in backward
    out = call_compiled_backward()
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_functorch/aot_autograd.py", line 2329, in call_compiled_backward
    CompiledFunction.compiled_bw = aot_config.bw_compiler(
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_dynamo/backends/common.py", line 38, in _wrapped_bw_compiler
    return eval_frame.disable(eval_frame.disable(bw_compiler)(*args, **kwargs))
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 231, in _fn
    return fn(*args, **kwargs)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 473, in bw_compiler
    return inner_compile(
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_dynamo/debug_utils.py", line 595, in debug_wrapper
    compiled_fn = compiler_fn(gm, example_inputs)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/debug.py", line 239, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/compile_fx.py", line 180, in compile_fx_inner
    compiled_fn = graph.compile_to_fn()
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/graph.py", line 616, in compile_to_fn
    return self.compile_to_module().call
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 164, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/graph.py", line 605, in compile_to_module
    mod = PyCodeCache.load(code)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 603, in load
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_jthakur/dv/cdvzcwpw74adao2guncutzvg2gwhulfesaoqlishuabnnvrkus7l.py", line 38, in <module>
    async_compile.wait(globals())
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 790, in wait
    scope[key] = result.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 767, in task
    return CppCodeCache.load(source_code).kernel
  File "/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_inductor/codecache.py", line 582, in load
    raise exc.CppCompileError(cmd, e.output) from e
torch._inductor.exc.CppCompileError: C++ compile error

### Minified repro

Minifier run causes segfault hence create a custom test for this failure. please use below code to reproduce:
```
import torch


def fn(test_args):
    res = torch.gather(**test_args)
    return res


if __name__ == "__main__":
    test_args = {
        "input": torch.tensor([[3.0, -5.0]], dtype=torch.bfloat16, requires_grad=True),
        "dim": 1,
        "index": torch.tensor([[1]]),
    }
    fn = torch.compile(fn)
    res_fwd = fn(test_args)
    bwd_tensor = torch.randn(res_fwd.shape, dtype=torch.bfloat16)
    res_fwd.backward(bwd_tensor)
    print(res_fwd, test_args["input"].grad)
```

### Versions

Name: torch
Version: 2.1.0.dev20230303+cpu
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by davidberard98** [comment] 2023-03-08 22:15
@EikanWang assigning to you as it is inductor-CPU related.

**Comment by EikanWang** [comment] 2023-03-09 13:54
I will analyze the issue and fix it.

**Comment by EikanWang** [comment] 2023-03-12 05:00
The root cause is that the C++/OpenMP backend has not supported `atomic_add` for BF16 yet. @zhuhaozhe has created a PR(#96472 ) to support it.

**Comment by EikanWang** [comment] 2023-03-12 14:43
@jay746 , I have created a PR to fix this issue https://github.com/pytorch/pytorch/pull/96620.

**Closed** 2023-03-16 07:36 UTC
Labels: triaged, oncall: pt2
