### ISSUE TITLE
torch.finfo doesn't work for complex

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#35954] opened 2020-04-03 17:25 UTC
>>> import torch
>>> torch.finfo(torch.complex64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: torch.finfo() requires a floating point input type. Use torch.iinfo to handle 'torch.finfo'
>>> import numpy
>>> numpy.finfo(numpy.complex64)
finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
>>>

cc @ezyang @anjali411 @dylanbespalko

**Comment by Justin-Huber** [comment] 2020-04-06 19:36
I'd like to work on this issue

**Comment by anjali411** [comment] 2020-04-09 16:04
> I'd like to work on this issue

@Justin-Huber thank you :) you can start by looking at this file: https://github.com/pytorch/pytorch/blob/master/torch/csrc/TypeInfo.cpp let me know if you have any questions or need any help and add me as a reviewer when you have a working PR :D

**Comment by Justin-Huber** [comment] 2020-04-09 17:29
Sounds good, thanks!

**Comment by Shubhammishra-21** [comment] 2020-04-11 07:24
hello mam i'm facing the problem to getting error while doing the SBI Life insurance Datasets in Jupyter notebook ,By using Algorithm Logistic Regression,I'm unable to use Libaries Properly for SBI Life Insurance,Please help me out for this Problem.

**Comment by jdklee** [comment] 2020-04-27 02:20
@Justin-Huber  Did you get a crack at this? I was wondering maybe we could both work on it?

**Comment by Justin-Huber** [comment] 2020-04-27 03:26
@jdklee No I haven't, that sounds good to me! Let me know if you fork it and we can work on that together :)

**Comment by anjali411** [comment] 2020-04-27 12:53
On more thought, even though numpy supports finfo(floating point info) for complex dtypes, I think we should not support torch.finfo for complex dtypes as complex_tensor.is_floating_point() returns false. Perhaps we can add torch.cinfo for complex dtypes?

as an FYI, this is numpy's current behavior:
```
>>> np.finfo(np.complex64)
finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
>>> np.finfo(np.float32)
finfo(resolution=1e-06, min=-3.4028235e+38, max=3.4028235e+38, dtype=float32)
```
cc. @mruberry @ezyang

**Comment by mruberry** [comment] 2020-04-27 20:42
I agree that conceptually it would be more elegant for PyTorch (in a bubble) to have finfo and cinfo and finfo doesn't support complex types, but in practice it seems fine to have finfo return complex values since the user is explicitly requesting them (making the risk of user confusion very low) and we greatly prefer being compatible with NumPy where possible. We could also add a cinfo, too, if we wanted, with redundant functionality.

**Comment by Justin-Huber** [comment] 2020-05-09 00:37
I'm finally getting around to this and have a few questions. Are there any tests/documentation for finfo? Is the expected behavior the same as numpy's finfo and are the only complex types np.complex_, np.complex128, np.complex64?

**Comment by mruberry** [comment] 2020-05-10 10:57
@Justin-Huber There are existing tests for finfo in test/test_type_info.py and it's documented here https://pytorch.org/docs/master/type_info.html?highlight=finfo#torch.torch.finfo. 

I would focus on complex64 and complex128 and yes, the expected behavior is the same as NumPy's. It'd be great to see a PR for this.

**Comment by Justin-Huber** [comment] 2020-05-20 17:52
In https://github.com/pytorch/pytorch/blob/master/test/test_type_info.py#L40-L43, what's the reasoning behind constructing a tensor to then get the dtype back from? To be able to get the corresponding numpy dtype? I was looking at #33152 and saw that complex tensors were disabled for the current release, so was wondering if there's another build I should be working from or if just skipping the tensor construction would be fine.

**Comment by mruberry** [comment] 2020-05-20 18:29
There's a lot of historic behavior in this test, and I think you're right they're constructing a NumPy tensor as a method of accessing NumPy's finfo. In torch/testing/_internal/common_utils.py we actually have torch_to_numpy_dtype_dict which will map torch to NumPy dtypes for you.

You should work on the Master branch, which lets you construct complex tensors.

**Comment by Justin-Huber** [comment] 2020-05-23 01:57
Here's what I have so far. https://github.com/pytorch/pytorch/compare/master...Justin-Huber:master Should the default dtype support complex too?

**Comment by mruberry** [comment] 2020-05-27 04:08
Hey @Justin-Huber, hope you had a relaxing weekend.

No, the default dtype already supports too many tensors. We probably should have restricted it to float32 and float64. 

You can open a draft PR with a [WIP] tag on it, too, by the way. That'll make it easy to track the conversation and look at the code together. Add me as a reviewer when you do.

**Comment by rannlangel** [comment] 2020-05-31 23:55
I will check the problem next year I got lots of work to do STFU

**Comment by rannlangel** [comment] 2020-05-31 23:59
I though someone scamming me sorry

**Comment by mrshenli** [comment] 2020-09-01 21:43
It has been a while since the last update on this issue. I self-assigned to grab this for bootcamp. Let me know if anyone already has a PR for this.

**Comment by mruberry** [comment] 2020-09-01 21:46
I think we fixed this in https://github.com/pytorch/pytorch/pull/40488 and failed to close the issue.

**Closed** 2020-09-01 21:52 UTC
Labels: good first issue, module: complex, triaged
