### ISSUE TITLE
masked_fill_ does not fail on zero-strided tensor, whereas a simple mul_ does

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#22118] opened 2019-06-23 14:14 UTC
It seems that masked_fill_ is more dangerous for zero-strided tensors, because the mask may be different for the elements that refer to the single location in memor

Probably related issue: https://github.com/pytorch/pytorch/issues/12230

My Torch version is `1.1.0`.
```python
import torch
a = torch.zeros(2)
b = a.expand(2, 2)

b *= 2 # breaks
# RuntimeError: mul: unsupported operation: more than one element of the written-to tensor refers to a single memory location. Please clone() the tensor before calling mul

mask = torch.ByteTensor([[0, 1], [1, 0]])
b.masked_fill_(mask, 0) # works, but semantically unsafe
```

**Comment by vadimkantorov** [comment] 2019-06-23 16:38
Seems duplicate of https://github.com/pytorch/pytorch/issues/10756 ...

**Comment by VitalyFedyunin** [comment] 2019-06-24 15:43
Yes, closing as duplicate of #10756

**Closed by VitalyFedyunin** 2019-06-24 15:43 UTC
Labels: module: operators, topic: partial aliasing
