### ISSUE TITLE
Nondeterministic Windows CUDA compilation failure

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#64605] opened 2021-09-07 22:25 UTC
```
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust\system\cuda\detail\cub\util_type.cuh(901): error C2993: 'T': is not a valid type for non-type template parameter '__formal'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust\system\cuda\detail\cub\util_type.cuh(909): note: see reference to class template instantiation 'thrust::cuda_cub::cub::BinaryOpHasIdxParam<T,BinaryOp>' being compiled
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust\system\cuda\detail\cub\util_type.cuh(901): error C2065: '__T3': undeclared identifier
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust\system\cuda\detail\cub\util_type.cuh(901): error C2923: 'std::_Select<__formal>::_Apply': '__T3' is not a valid template type argument for parameter '<unnamed-symbol>'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust\system\cuda\detail\cub\util_type.cuh(901): error C2062: type 'unknown-type' unexpected
Retry attempt: 1
bucketize_op.cu
```

happened on pytorch_windows_vs2019_py38_cuda10.1_build ([link](https://app.circleci.com/pipelines/github/pytorch/pytorch/376352/workflows/1e19f21c-fea2-410c-a796-33acee8af643/jobs/15865672))

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @ngimel

**Comment by mszhanyi** [comment] 2021-09-08 15:05
Looks triggered by #61902

```
From github.com:pytorch/pytorch
 * [new ref]               refs/pull/61902/head -> origin/pull/61902/head
```

**Comment by mszhanyi** [comment] 2021-09-08 15:40
@peterjc123 BTW，I find randomtemp is 0.3 in pytorch but it's 0.4 in builder, what's the difference.

https://github.com/pytorch/pytorch/blob/master/.jenkins/pytorch/win-test-helpers/build_pytorch.bat#L97
https://github.com/pytorch/builder/blob/master/windows/build_pytorch.bat#L113

**Comment by peterjc123** [comment] 2021-09-08 15:53
See https://github.com/pytorch/builder/pull/835 and https://github.com/peterjc123/randomtemp-rust/pull/6.

**Comment by peterjc123** [comment] 2021-09-08 15:55
Well, I skimmed the log. Isn't the actual error this one?
```
reduce.cu
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(610): error C2065: 'S': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(611): note: see reference to class template instantiation 'thrust::cuda_cub::core::LoadIterator<PtxPlan,It>' being compiled
Retry attempt: 1
reduce.cu
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(610): error C2065: 'S': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(611): note: see reference to class template instantiation 'thrust::cuda_cub::core::LoadIterator<PtxPlan,It>' being compiled
Retry attempt: 2
reduce.cu
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(610): error C2065: 'S': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(611): note: see reference to class template instantiation 'thrust::cuda_cub::core::LoadIterator<PtxPlan,It>' being compiled
Retry attempt: 3
reduce.cu
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(610): error C2065: 'S': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/core/util.h(611): note: see reference to class template instantiation 'thrust::cuda_cub::core::LoadIterator<PtxPlan,It>' being compiled
-- Removing C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/utils/math/./torch_cuda_generated_reduce.cu.obj
C:/Jenkins/Miniconda3/Library/bin/cmake.exe -E remove C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/utils/math/./torch_cuda_generated_reduce.cu.obj
```

**Comment by peterjc123** [comment] 2021-09-08 16:05
I guess this is somehow related to https://github.com/NVIDIA/thrust/issues/1090, since it can only be observed in CUDA 10.1 builds.

**Comment by malfet** [comment] 2021-09-25 00:54
As @ngimel correctly pointed out, this looks like a duplicate of https://github.com/pytorch/pytorch/issues/25393
Should we close?

**Closed** 2021-09-30 06:45 UTC
Labels: module: build, module: windows, module: cuda, triaged
