### ISSUE TITLE
403 when trying to get multiple pytorch components

### ISSUE THREAD

**Issue by spdavern** [pytorch/pytorch#81798] opened 2022-07-20 19:04 UTC
### 🐛 Describe the bug

As part of a dockerfile we're conda installing multiple components from a yml.
Today we are getting these errors:
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2>
Elapsed: 00:00.298984

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-1.10.1-py3.9_cuda11.3_cudnn8.2.0_0.tar.bz2>
Elapsed: 00:00.073712

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/torchaudio-0.10.1-py39_cu113.tar.bz2>
Elapsed: 00:00.304133

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/torchvision-0.11.2-py39_cu113.tar.bz2>
Elapsed: 00:00.075025

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

I tried to build the docker image multiple times.  Then, got the same 403 error just trying to access any of the components directly via a browser.
### Versions

N/A

**Comment by rdutta1999** [comment] 2022-07-20 19:07
Can confirm. Created a fresh conda environment and ran `conda install pytorch torchvision torchaudio cudatoolkit=10.2 -c pytorch`.

Fails with the same `CondaHTTPError: HTTP 403 FORBIDDEN` errors as @spdavern mentioned.

**Comment by BrainSlugs83** [comment] 2022-07-20 21:37
I accidentally logged a duplicate of this bug (#81799).

It's the same issue I'm sure.  Seems to still be an issue right now. -- Is there a way to escalate the priority?

**Comment by GF-Huang** [comment] 2022-07-20 22:15
Same here.

```
(base) root@VM-48-14-debian:~# conda install pytorch torchvision torchaudio cpuonly -c pytorch -y
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /root/miniconda3

  added / updated specs:
    - cpuonly
    - pytorch
    - torchaudio
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cpuonly-2.0                |                0           2 KB  pytorch
    ffmpeg-4.3                 |       hf484d3e_0         9.9 MB  pytorch
    pytorch-1.12.0             |      py3.9_cpu_0        76.6 MB  pytorch
    pytorch-mutex-1.0          |              cpu           3 KB  pytorch
    ------------------------------------------------------------
                                           Total:        86.5 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/linux-64::blas-1.0-mkl
  bzip2              pkgs/main/linux-64::bzip2-1.0.8-h7b6447c_0
  cpuonly            pytorch/noarch::cpuonly-2.0-0
  ffmpeg             pytorch/linux-64::ffmpeg-4.3-hf484d3e_0
  freetype           pkgs/main/linux-64::freetype-2.11.0-h70c0345_0
  giflib             pkgs/main/linux-64::giflib-5.2.1-h7b6447c_0
  gmp                pkgs/main/linux-64::gmp-6.2.1-h295c915_3
  gnutls             pkgs/main/linux-64::gnutls-3.6.15-he1e5248_0
  intel-openmp       pkgs/main/linux-64::intel-openmp-2021.4.0-h06a4308_3561
  jpeg               pkgs/main/linux-64::jpeg-9e-h7f8727e_0
  lame               pkgs/main/linux-64::lame-3.100-h7b6447c_0
  lcms2              pkgs/main/linux-64::lcms2-2.12-h3be6417_0
  libiconv           pkgs/main/linux-64::libiconv-1.16-h7f8727e_2
  libidn2            pkgs/main/linux-64::libidn2-2.3.2-h7f8727e_0
  libpng             pkgs/main/linux-64::libpng-1.6.37-hbc83047_0
  libtasn1           pkgs/main/linux-64::libtasn1-4.16.0-h27cfd23_0
  libtiff            pkgs/main/linux-64::libtiff-4.2.0-h2818925_1
  libunistring       pkgs/main/linux-64::libunistring-0.9.10-h27cfd23_0
  libwebp            pkgs/main/linux-64::libwebp-1.2.2-h55f646e_0
  libwebp-base       pkgs/main/linux-64::libwebp-base-1.2.2-h7f8727e_0
  lz4-c              pkgs/main/linux-64::lz4-c-1.9.3-h295c915_1
  mkl                pkgs/main/linux-64::mkl-2021.4.0-h06a4308_640
  mkl-service        pkgs/main/linux-64::mkl-service-2.4.0-py39h7f8727e_0
  mkl_fft            pkgs/main/linux-64::mkl_fft-1.3.1-py39hd3c417c_0
  mkl_random         pkgs/main/linux-64::mkl_random-1.2.2-py39h51133e4_0
  nettle             pkgs/main/linux-64::nettle-3.7.3-hbbd107a_1
  numpy              pkgs/main/linux-64::numpy-1.22.3-py39he7a7128_0
  numpy-base         pkgs/main/linux-64::numpy-base-1.22.3-py39hf524024_0
  openh264           pkgs/main/linux-64::openh264-2.1.1-h4ff587b_0
  pillow             pkgs/main/linux-64::pillow-9.2.0-py39hace64e9_1
  pytorch            pytorch/linux-64::pytorch-1.12.0-py3.9_cpu_0
  pytorch-mutex      pytorch/noarch::pytorch-mutex-1.0-cpu
  six                pkgs/main/noarch::six-1.16.0-pyhd3eb1b0_1
  torchaudio         pytorch/linux-64::torchaudio-0.12.0-py39_cpu
  torchvision        pytorch/linux-64::torchvision-0.13.0-py39_cpu
  typing_extensions  pkgs/main/noarch::typing_extensions-4.1.1-pyh06a4308_0
  zstd               pkgs/main/linux-64::zstd-1.5.2-ha4553b6_0



Downloading and Extracting Packages
cpuonly-2.0          | 2 KB      |                                                                                                   |   0% 
ffmpeg-4.3           | 9.9 MB    |                                                                                                   |   0% 
pytorch-1.12.0       | 76.6 MB   |                                                                                                   |   0% 
pytorch-mutex-1.0    | 3 KB      |                                                                                                   |   0% 

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/cpuonly-2.0-0.tar.bz2>
Elapsed: 00:00.909810

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/ffmpeg-4.3-hf484d3e_0.tar.bz2>
Elapsed: 00:00.225389

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/linux-64/pytorch-1.12.0-py3.9_cpu_0.tar.bz2>
Elapsed: 00:00.225191

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cpu.tar.bz2>
Elapsed: 00:00.225416

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

```

**Comment by kit1980** [comment] 2022-07-21 00:08
This is a Conda issue - https://github.com/conda/conda/issues/11638
Closing this as a duplicate of https://github.com/pytorch/pytorch/issues/81760

**Closed by kit1980** 2022-07-21 00:08 UTC
