### ISSUE TITLE
RuntimeError: Expected a 'N2at13CUDAGeneratorE' but found 'PN2at9GeneratorE'

### ISSUE THREAD

**Issue by bdusell** [pytorch/pytorch#15867] opened 2019-01-09 07:55 UTC
## 🐛 Bug

When randomly initializing a CUDA tensor with a manually-seeded generator using `Tensor.uniform_()`, the function throws the following exception:
```
RuntimeError: Expected a 'N2at13CUDAGeneratorE' but found 'PN2at9GeneratorE'
```

This does not happen when the device is CPU; it works as expected then.

## To Reproduce

1. Run the code snippet below

```python
import torch
device = torch.device('cuda')
generator = torch.manual_seed(123)
x = torch.zeros(10, device=device)
x.uniform_(-1.0, 1.0, generator=generator)
```

## Expected behavior

The function should not fail. The CUDA tensor `x` should be initialized using the manually-seeded generator.

## Environment

```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 14.04.5 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: Tesla K40c
Nvidia driver version: 384.66
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

I installed PyTorch using pyenv and Pipenv.

## Additional context

The `generator` argument to `Tensor.uniform_()` does not seem to be documented, despite being extremely useful.

**Comment by bdusell** [comment] 2019-01-09 07:59
This looks relevant: https://github.com/pytorch/pytorch/issues/11340

**Comment by fmassa** [comment] 2019-01-14 14:19
I believe the problem is that `torch.manual_seed` returns the CPU random generator https://github.com/pytorch/pytorch/blob/7c08f1083e56ce7e9799a15b36947c46052f0058/torch/csrc/Module.cpp#L646

I'm not sure we are exposing the CUDA Generator in Python though.

**Comment by ezyang** [comment] 2019-01-15 17:17
cc @syed-ahmed

**Comment by fmassa** [comment] 2019-01-15 20:20
@ezyang I believe that in your first example, the generator is None, because it's not returned by `torch.cuda.manual_seed`

**Comment by ezyang** [comment] 2019-04-22 17:22
We should check in on this again after Syed's PR lands.

**Comment by syed-ahmed** [comment] 2019-04-23 07:02
Note that the error: `RuntimeError: Expected a 'N2at13CUDAGeneratorE' but found 'PN2at9GeneratorE'` originated from this line. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/CheckGenerator.h#L15. Before my PR, the generated dispatch code utilized this function: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/function_wrapper.py#L327, and put it on all random distribution function dispatch code. For CUDA side,`THGenerator*` is set to null: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/function_wrapper.py#L1247. Hence, with the THGenerator* being null, and the `check_generator` function resolving to `check_generator<CUDAGenerator>(null, &globalContext().defaultGenerator(at::CUDA))`, we were getting that error. In my PR, `check_generator` (now called `check_generator_with_default`) is removed from `function_wrapper.py` and is currently only being called for the CPU functions and hence "solves" the bug. 

The torch.manual_seed returning a CPU Generator is still there and I agree with @ezyang that it's weird. IMO, torch.manual_seed should return nothing, like how it's in torch.cuda.manual_seed. That is, [Py_RETURN_NONE](https://github.com/pytorch/pytorch/blob/53bb739b675a0dd2af2fcb2b02e37f64a432bd2f/torch/csrc/cuda/Module.cpp#L165) vs [(PyObject*)self](https://github.com/pytorch/pytorch/blob/53bb739b675a0dd2af2fcb2b02e37f64a432bd2f/torch/csrc/Generator.cpp#L104)

**Comment by syed-ahmed** [comment] 2019-06-21 00:00
Update:
After my PR, the reproducer script now says the following:
```
>>> device = torch.device('cuda')
>>> generator = torch.manual_seed(123)
>>> x = torch.zeros(10, device=device)
>>> x.uniform_(-1.0, 1.0, generator=generator)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Expected a 'cuda' device type for generator but found 'cpu'
```
which I think is the correct behavior as `torch.manual_seed` is returning a CPU generator and it is being fed to a cuda function. Whether `torch.manual_seed` should return a CPU generator is a different issue.

**Comment by gchanan** [comment] 2019-07-16 18:41
Looks fixed to me, I'm going to close this issue.

**Closed by gchanan** 2019-07-16 18:41 UTC
Labels: high priority, module: cuda, triaged
