### ISSUE TITLE
DISABLED test_torchscript_functions_not_supported (__main__.JitRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#34260] opened 2020-03-04 20:48 UTC
test_torchscript_functions_not_supported is flaky

Passed :
https://app.circleci.com/jobs/github/pytorch/pytorch/4691744

Failed:
https://app.circleci.com/jobs/github/pytorch/pytorch/4692485

```
Mar 04 20:33:44 Running tests...
Mar 04 20:33:44 ----------------------------------------------------------------------
Mar 04 20:33:48 ...[E request_callback.cpp:39] Received error while processing request type 0: attempted to get undefined function python_function (get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:69)
Mar 04 20:33:48 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f31d8c6679a in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Mar 04 20:33:48 frame #1: <unknown function> + 0x65b5bd (0x7f31d98625bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:48 frame #2: torch::distributed::rpc::RequestCallbackImpl::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType, long) const + 0x18dc (0x7f31d9aa823c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:48 frame #3: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0x55 (0x7f31d9aa94a5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:48 frame #4: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x33 (0x7f31d6579ed3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Mar 04 20:33:48 frame #5: <unknown function> + 0x88326b (0x7f31d9a8a26b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:48 frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x2fb (0x7f31d8c57cab in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Mar 04 20:33:48 frame #7: <unknown function> + 0xc8421 (0x7f31d915b421 in /opt/conda/lib/libstdc++.so.6)
Mar 04 20:33:48 frame #8: <unknown function> + 0x76ba (0x7f31e1d666ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Mar 04 20:33:48 frame #9: clone + 0x6d (0x7f31e1a9c41d in /lib/x86_64-linux-gnu/libc.so.6)
Mar 04 20:33:48 
Mar 04 20:33:49 .[E request_callback.cpp:39] Received error while processing request type 0: attempted to get undefined function nonexisting_script (get_function at /var/lib/jenkins/workspace/torch/csrc/jit/api/compilation_unit.h:69)
Mar 04 20:33:49 frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f800502a79a in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Mar 04 20:33:49 frame #1: <unknown function> + 0x65b5bd (0x7f8005c265bd in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:49 frame #2: torch::distributed::rpc::RequestCallbackImpl::processRpc(torch::distributed::rpc::RpcCommandBase&, torch::distributed::rpc::MessageType, long) const + 0x18dc (0x7f8005e6c23c in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:49 frame #3: torch::distributed::rpc::RequestCallbackImpl::processMessage(torch::distributed::rpc::Message&) const + 0x55 (0x7f8005e6d4a5 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:49 frame #4: torch::distributed::rpc::RequestCallback::operator()(torch::distributed::rpc::Message&) const + 0x33 (0x7f800293ded3 in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_cpu.so)
Mar 04 20:33:49 frame #5: <unknown function> + 0x88326b (0x7f8005e4e26b in /opt/conda/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
Mar 04 20:33:49 frame #6: c10::ThreadPool::main_loop(unsigned long) + 0x2fb (0x7f800501bcab in /opt/conda/lib/python3.6/site-packages/torch/lib/libc10.so)
Mar 04 20:33:49 frame #7: <unknown function> + 0xc8421 (0x7f800551f421 in /opt/conda/lib/libstdc++.so.6)
Mar 04 20:33:49 frame #8: <unknown function> + 0x76ba (0x7f800e12a6ba in /lib/x86_64-linux-gnu/libpthread.so.0)
Mar 04 20:33:49 frame #9: clone + 0x6d (0x7f800de6041d in /lib/x86_64-linux-gnu/libc.so.6)
Mar 04 20:33:49 
Mar 04 20:33:50 .[E request_callback.cpp:39] Received error while processing request type 0: The following operation failed in the TorchScript interpreter.
Mar 04 20:33:50 Traceback of TorchScript (most recent call last):
Mar 04 20:33:50   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 140, in raise_script
Mar 04 20:33:50 @torch.jit.script
Mar 04 20:33:50 def raise_script():
Mar 04 20:33:50     raise RuntimeError("Expected error")
Mar 04 20:33:50     ~~~~~~~~~~~~~~~~~~~~ <--- HERE
Mar 04 20:33:50     return 0
Mar 04 20:33:50 RuntimeError: Exception
Mar 04 20:33:50 
Mar 04 20:35:07 ...............Process process 3:
Mar 04 20:35:07 Traceback (most recent call last):
Mar 04 20:35:07   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 04 20:35:07     self.run()
Mar 04 20:35:07   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 04 20:35:07     self._target(*self._args, **self._kwargs)
Mar 04 20:35:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 243, in _run
Mar 04 20:35:07     getattr(self, test_name)()
Mar 04 20:35:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 68, in new_test_method
Mar 04 20:35:07     return_value = old_test_method(self, *arg, **kwargs)
Mar 04 20:35:07   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/jit/rpc_test.py", line 496, in test_torchscript_functions_not_supported
Mar 04 20:35:07     ret = rpc.rpc_sync("worker{}".format(dst_rank), MyScriptClass, args=())
Mar 04 20:35:07   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 20:35:07     return func(*args, **kwargs)
Mar 04 20:35:07   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 526, in rpc_sync
Mar 04 20:35:07     return fut.wait()
Mar 04 20:35:07 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.
Mar 04 20:35:08 Process process 1:
Mar 04 20:35:08 Traceback (most recent call last):
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 04 20:35:08     self.run()
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 04 20:35:08     self._target(*self._args, **self._kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 243, in _run
Mar 04 20:35:08     getattr(self, test_name)()
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 71, in new_test_method
Mar 04 20:35:08     rpc.shutdown(graceful=clean_shutdown)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 20:35:08     return func(*args, **kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 237, in shutdown
Mar 04 20:35:08     _wait_all_workers()
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 20:35:08     return func(*args, **kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 164, in _wait_all_workers
Mar 04 20:35:08     args=(sequence_id, self_worker_name,),
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 20:35:08     return func(*args, **kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 526, in rpc_sync
Mar 04 20:35:08     return fut.wait()
Mar 04 20:35:08 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.
Mar 04 20:35:08 Process process 2:
Mar 04 20:35:08 Traceback (most recent call last):
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
Mar 04 20:35:08     self.run()
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
Mar 04 20:35:08     self._target(*self._args, **self._kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 243, in _run
Mar 04 20:35:08     getattr(self, test_name)()
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 71, in new_test_method
Mar 04 20:35:08     rpc.shutdown(graceful=clean_shutdown)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 20:35:08     return func(*args, **kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 237, in shutdown
Mar 04 20:35:08     _wait_all_workers()
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 20:35:08     return func(*args, **kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 164, in _wait_all_workers
Mar 04 20:35:08     args=(sequence_id, self_worker_name,),
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 76, in wrapper
Mar 04 20:35:08     return func(*args, **kwargs)
Mar 04 20:35:08   File "/opt/conda/lib/python3.6/site-packages/torch/distributed/rpc/api.py", line 526, in rpc_sync
Mar 04 20:35:08     return fut.wait()
Mar 04 20:35:08 RuntimeError: RPC ran for more than 60000 milliseconds and timed out.
Mar 04 20:35:48 E.
Mar 04 20:35:48 ======================================================================
Mar 04 20:35:48 ERROR [100.047s]: test_torchscript_functions_not_supported (__main__.JitRpcTestWithSpawn)
Mar 04 20:35:48 ----------------------------------------------------------------------
Mar 04 20:35:48 Traceback (most recent call last):
Mar 04 20:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 175, in wrapper
Mar 04 20:35:48     self._join_processes(fn)
Mar 04 20:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 256, in _join_processes
Mar 04 20:35:48     self._check_return_codes(elapsed_time)
Mar 04 20:35:48   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 275, in _check_return_codes
Mar 04 20:35:48     raise RuntimeError('Process {} terminated or timed out after {} seconds'.format(i, elapsed_time))
Mar 04 20:35:48 RuntimeError: Process 0 terminated or timed out after 100.02777481079102 seconds
```

cc @ezyang @gchanan @zou3519 @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by zhaojuanmao** [comment] 2020-03-04 21:16
something is wrong, why these tests start to be flaky today?

**Comment by zhaojuanmao** [comment] 2020-03-09 19:48
GIL change in #33329 could cause deadlock

**Comment by mrshenli** [comment] 2020-03-13 03:52
closed by #34505

**Comment by rohan-varma** [comment] 2020-03-13 07:57
Unfortunately it looks like this is still failing, so I'm reopening the issue. It failed on my unrelated change () when I landed it: https://github.com/pytorch/pytorch/commit/fd355965857f5c281d0b60be864745e7b7a223bd

https://app.circleci.com/pipelines/github/pytorch/pytorch/139173/workflows/0d3e7e18-218e-4189-a0d7-504d7eeb15de/jobs/4798239
https://app.circleci.com/pipelines/github/pytorch/pytorch/139173/workflows/617f8d91-8340-40c1-a5b7-4b8b99ea4ee7/jobs/4798596

cc @mrshenli @xush6528 @zhaojuanmao

**Comment by zhaojuanmao** [comment] 2020-03-13 18:44
tried stress run 100 times locally and can not reproduce it so far

**Comment by zhaojuanmao** [comment] 2020-03-13 19:19
this test actually did not hit torch script code paths, all the user functions are running python call path

**Comment by zhaojuanmao** [comment] 2020-03-19 01:08
it passed on buck test, but it always failed on my local OSS test. Looks like program exited abnormally after throwing errors in "ret = rpc.rpc_sync(
                dst_worker_name, MyScriptModule, args=(self.rank,)
            )"

**Comment by xush6528** [comment] 2020-03-24 06:48
The failure is deterministic now. The error happens when serializing a Python object return value for Python RPC call. 
There is no error handling in Python serializer, so the exception is caught by RPC code. 

RPC error handling prepare the response Message using the exception string as message payload and MessageType::EXCEPTION as message type. 

See https://github.com/pytorch/pytorch/blob/43fc97db88d51911a8125c32b874cba68fc66053/torch/csrc/distributed/rpc/request_callback_impl.cpp#L481

The problem is this code hangs on exiting the catch block.

**Comment by xush6528** [comment] 2020-03-24 07:19
It turned out it's a GIL deadlock. The exception is actually a `py::error_already_set.` object, which holds 3 `py::object`s. Need to hold GIL and release the object first, before calling it's destructor.

**Closed** 2020-03-24 18:39 UTC
Labels: high priority, module: rpc, topic: flaky-tests, triaged
