### ISSUE TITLE
torch._C not found 

### ISSUE THREAD

**Issue by connermcb** [pytorch/pytorch#7323] opened 2018-05-06 03:04 UTC
I know this issues has been raised, but none of the purposed solutions have worked for me so far. I'm working in Anaconda on Windows 10, and after finally getting pytorch installed successfully, I'm getting this when importing:

```
(base) C:\Users\conner>python
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\conner\Anaconda3\lib\site-packages\torch\__init__.py", line 76, in <module>
    from torch._C import *
ImportError: DLL load failed: The specified module could not be found.
```

I've tried cd .. to another directory and reopening python there, without luck. I also tried abridging the _C file name as recommended in another thread, again to no avail. Here's what's in the package directory:

```
(base) C:\Users\conner\Anaconda3\Lib\site-packages\torch>dir
 Volume in drive C has no label.
 Volume Serial Number is F8D6-539E

 Directory of C:\Users\conner\Anaconda3\Lib\site-packages\torch

05/05/2018  07:52 PM    <DIR>          .
05/05/2018  07:52 PM    <DIR>          ..
05/05/2018  07:29 PM    <DIR>          autograd
05/05/2018  07:29 PM    <DIR>          backends
05/05/2018  07:29 PM    <DIR>          contrib
05/05/2018  07:29 PM    <DIR>          cuda
05/05/2018  07:29 PM    <DIR>          distributed
02/24/2018  05:49 AM             6,208 distributions.py
05/05/2018  07:29 PM    <DIR>          for_onnx
02/24/2018  05:49 AM             9,714 functional.py
05/05/2018  07:29 PM    <DIR>          jit
05/05/2018  07:29 PM    <DIR>          legacy
05/05/2018  07:29 PM    <DIR>          lib
05/05/2018  07:29 PM    <DIR>          multiprocessing
05/05/2018  07:29 PM    <DIR>          nn
05/05/2018  07:29 PM    <DIR>          onnx
05/05/2018  07:29 PM    <DIR>          optim
11/09/2017  07:38 PM             4,130 random.py
02/24/2018  05:49 AM            16,759 serialization.py
05/05/2018  07:29 PM    <DIR>          sparse
02/24/2018  05:49 AM             4,016 storage.py
02/24/2018  05:49 AM            14,497 tensor.py
05/05/2018  07:29 PM    <DIR>          utils
02/24/2018  01:46 PM                58 version.py
02/24/2018  01:52 PM        22,208,512 _C.pyd
02/24/2018  01:52 PM            10,240 _nvrtc.cp36-win_amd64.pyd
10/27/2017  09:31 PM             3,044 _six.py
09/17/2017  08:09 AM             1,164 _storage_docs.py
02/24/2018  05:49 AM            39,842 _tensor_docs.py
02/24/2018  05:49 AM            11,024 _tensor_str.py
05/05/2018  07:29 PM    <DIR>          _thnn
02/24/2018  05:49 AM           127,125 _torch_docs.py
02/24/2018  05:49 AM             9,201 _utils.py
02/24/2018  05:49 AM             9,313 __init__.py
05/05/2018  07:29 PM    <DIR>          __pycache__
              16 File(s)     22,474,847 bytes
              19 Dir(s)  318,426,836,992 bytes free
```

**Comment by peterjc123** [comment] 2018-05-06 06:34
Duplicate of #4518. I hope you could search before create a new one next time.

**Closed** 2018-05-06 19:51 UTC
