### ISSUE TITLE
pytorch 1.9 causes metaclass conflict with torchtyping when munged about by pytest

### ISSUE THREAD

**Issue by LinxiFan** [pytorch/pytorch#60839] opened 2021-06-27 23:01 UTC
## 🐛 Bug

`pytest` throws metaclass conflict error when using pytorch 1.9, but is fine with <= v1.8

## To Reproduce

Script: `test_me.py`

```py
import torch

def test_one():
    assert 1==1
```

Run with `pytest test_me.py`, gives:

```
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 319, in _prepareconfig
    pluginmanager=pluginmanager, args=args
  File "/opt/conda/lib/python3.7/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 87, in <lambda>
    firstresult=hook.spec.opts.get("firstresult") if hook.spec else False,
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/opt/conda/lib/python3.7/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/config/__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "/opt/conda/lib/python3.7/site-packages/pluggy/manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "/opt/conda/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/opt/conda/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/home/user/.local/lib/python3.7/site-packages/torchtyping/__init__.py", line 10, in <module>
    from .tensor_type import TensorType
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/user/.local/lib/python3.7/site-packages/_pytest/assertion/rewrite.py", line 170, in exec_module
    exec(co, module.__dict__)
  File "/home/user/.local/lib/python3.7/site-packages/torchtyping/tensor_type.py", line 176, in <module>
    class TensorType(torch.Tensor, TensorTypeMixin):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

## Environment

```
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.10

Python version: 3.7.7 (default, May  7 2020, 21:25:33)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-48-generic-x86_64-with-debian-buster-sid
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX
GPU 2: TITAN RTX
GPU 3: TITAN RTX
GPU 4: TITAN RTX
GPU 5: TITAN RTX
GPU 6: TITAN RTX
GPU 7: TITAN RTX

Nvidia driver version: 450.66
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] numpy-quaternion==2021.4.5.14.42.35
[pip3] pytorch-lightning==1.2.7
[pip3] torch==1.9.0
[pip3] torchmetrics==0.3.2
[pip3] torchtyping==0.1.3
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] pytorch                   1.7.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         1.1.8                    pypi_0    pypi
[conda] torchvision               0.8.1                py37_cu102    pytorch
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by erip** [comment] 2021-06-28 21:18
You have two different pytorch versions installed. What happens when you resolve that issue?

**Comment by LinxiFan** [comment] 2021-06-28 22:06
No, it doesn't solve the problem. Also the pip version is the one being used. Thanks!

**Comment by LinxiFan** [comment] 2021-06-28 22:08
I also just tried creating a fresh new virtual env, and installed nothing but pytorch v1.9 and pytest. The problem persists. Could you reproduce it too?

**Comment by erip** [comment] 2021-06-28 23:09
Your example works fine with 1.9.0 cpuonly. Unfortunately I don't have a GPU to test the exact configuration you've outlined, but maybe someone else can.

**Comment by pmeier** [comment] 2021-06-29 06:14
@LinxiFan Cannot reproduce with a single GPU either. What `pytest` version are you using?

**Comment by ezyang** [comment] 2021-06-29 14:53
This is probably due to https://github.com/pytorch/pytorch/pull/56147 and it looks like a problem with torchtyping specifically

**Comment by LinxiFan** [comment] 2021-06-29 18:48
@ezyang yes I think this is the difference between v1.8 and 1.9 that caused the problem. I'm using the latest pytest, v6.2.4. Thanks!

**Comment by ezyang** [comment] 2021-06-29 19:04
Long and difficult to explain reasons :) But at the time we thought it would not be observable as normally you can't multiply inherit from tensor anyway. Need to investigate.

**Comment by LinxiFan** [comment] 2021-06-29 20:42
Gotcha, thanks Edward! Is there a way to workaround this pytest bug in the meantime?

**Comment by ezyang** [comment] 2021-07-01 04:10
Idk, maybe uninstall torchtyping if you can.

Note that this doesn't repro:

```
(/home/ezyang/local/pytorch-tmp2-env) [ezyang@devvm066.ash0 ~/local/pytorch-tmp2] python a.py
(/home/ezyang/local/pytorch-tmp2-env) [ezyang@devvm066.ash0 ~/local/pytorch-tmp2] cat a.py
import torchtyping.tensor_type
```

so maybe this is some really crazy pytest bug

**Comment by ezyang** [comment] 2021-07-01 04:13
nvm, this is fixed in torchtyping 0.1.4, just update

**Closed by ezyang** 2021-07-01 04:13 UTC
Labels: high priority, module: regression, module: testing, triage review

**Comment by LinxiFan** [comment] 2021-07-01 06:54
This fixed the problem, thank you so much!

**Comment by nitesh-acog** [comment] 2023-05-23 09:13
My error specifically says 
packages/torch_geometric/__init__.py", line 2, in <module>
    import torch_geometric.data
  File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/__init__.py", line 7, in <module>
    from .batch import Batch
  File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/batch.py", line 11, in <module>
    from torch_geometric.data.dataset import IndexType
  File "/opt/conda/lib/python3.9/site-packages/torch_geometric/data/dataset.py", line 20, in <module>
    class Dataset(torch.utils.data.Dataset, ABC):
TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases.

I had to remove all the abstract classes from all the dependent modules in site packages of torch to make it work .
python=3.9.16
torch=1.13.1
torch_geometric=2.3.1
