### ISSUE TITLE
Python3.10 Support

### ISSUE THREAD

**Issue by jhirshman** [pytorch/pytorch#69220] opened 2021-12-01 15:48 UTC
I would like to use pytorch with python3.10

Is there a place where the timeline for supporting python3.10 is being tracked?

Will it be available with the next release of pytorch?

**Comment by malfet** [comment] 2021-12-01 15:50
Closing as duplicate of https://github.com/pytorch/pytorch/issues/66424

**Closed by malfet** 2021-12-01 15:50 UTC
