### ISSUE TITLE
[PrimTorch] Functionalization pass removes Instance Norm / Batch Norm running stats transformations

### ISSUE THREAD

**Issue by rdspring1** [pytorch/pytorch#88375] opened 2022-11-02 23:20 UTC
### 🐛 Describe the bug

The alias ops on running stats for Instance Norm are removed after functionalization pass. NvFuser uses the alias ops to map the running stats back to the fusion input's original shape, stride, and dtype.

References:
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/Normalization.cpp#L664-L670
https://github.com/pytorch/pytorch/blob/master/functorch/_src/aot_autograd.py#L393-L413

```python
====== Input graph ======
class joint_forward_backward(torch.nn.Module):
    def forward(self, primals, tangents):
        primals_1: f32[32, 32, 1, 1], primals_2: f32[32], primals_3: f32[32], primals_4: i64[], primals_5: f32[2, 32, 8, 8], tangents_1: f32[2, 32, 8, 8], = fx_pytree.tree_flatten_spec([primals, tangents], self._in_spec)
        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:20, code: out = self.conv(inp)
        convolution: f32[2, 32, 8, 8] = torch.ops.aten.convolution.default(primals_5, primals_1, None, [1, 1], [0, 0], [1, 1], False, [0, 0], 1)

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:21, code: out = out.relu()
        relu: f32[2, 32, 8, 8] = torch.ops.aten.relu.default(convolution);  convolution = None
        detach: f32[2, 32, 8, 8] = torch.ops.aten.detach.default(relu)

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:22, code: out = self.bn(out)
        repeat: f32[64] = torch.ops.aten.repeat.default(primals_2, [2])
        repeat_1: f32[64] = torch.ops.aten.repeat.default(primals_3, [2])
        view: f32[1, 64, 8, 8] = torch.ops.aten.view.default(relu, [1, 64, 8, 8]);  relu = None
        empty: u8[0] = torch.ops.aten.empty.memory_format([0], dtype = torch.uint8, layout = torch.strided, device = device(type='cuda', index=0))
        native_batch_norm = torch.ops.aten.native_batch_norm.default(view, None, None, repeat, repeat_1, True, 0.1, 1e-05)
        getitem: f32[1, 64, 8, 8] = native_batch_norm[0]
        getitem_1: f32[64] = native_batch_norm[1]
        getitem_2: f32[64] = native_batch_norm[2];  native_batch_norm = None

        # ===========================================
        # running mean for instance_norm
        alias: f32[32] = torch.ops.aten.alias.default(primals_2);  primals_2 = None
        view_1: f32[2, 32] = torch.ops.aten.view.default(repeat, [2, 32])
        mean: f32[32] = torch.ops.aten.mean.dim(view_1, [0]);  view_1 = None
        copy_: f32[32] = torch.ops.aten.copy_.default(alias, mean);  alias = mean = None
        # ===========================================

        # ===========================================
        # running var for instance_norm
        alias_1: f32[32] = torch.ops.aten.alias.default(primals_3);  primals_3 = None
        view_2: f32[2, 32] = torch.ops.aten.view.default(repeat_1, [2, 32])
        mean_1: f32[32] = torch.ops.aten.mean.dim(view_2, [0]);  view_2 = None
        copy__1: f32[32] = torch.ops.aten.copy_.default(alias_1, mean_1);  alias_1 = mean_1 = None
        # ===========================================

        view_3: f32[2, 32, 8, 8] = torch.ops.aten.view.default(getitem, [2, 32, 8, 8]);  getitem = None

        # No stacktrace found for following nodes
        is_same_size = torch.ops.aten.is_same_size.default(view_3, tangents_1)

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:22, code: out = self.bn(out)
        view_4: f32[1, 64, 8, 8] = torch.ops.aten.view.default(tangents_1, [1, 64, 8, 8]);  tangents_1 = None
        native_batch_norm_backward = torch.ops.aten.native_batch_norm_backward.default(view_4, view, None, repeat, repeat_1, getitem_1, getitem_2, True, 1e-05, [True, False, False]);  view_4 = view = repeat = repeat_1 = getitem_1 = getitem_2 = None
        getitem_3: f32[1, 64, 8, 8] = native_batch_norm_backward[0]
        getitem_4 = native_batch_norm_backward[1]
        getitem_5 = native_batch_norm_backward[2];  native_batch_norm_backward = None
        view_5: f32[2, 32, 8, 8] = torch.ops.aten.view.default(getitem_3, [2, 32, 8, 8]);  getitem_3 = None

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:21, code: out = out.relu()
        detach_1: f32[2, 32, 8, 8] = torch.ops.aten.detach.default(detach);  detach = None
        threshold_backward: f32[2, 32, 8, 8] = torch.ops.aten.threshold_backward.default(view_5, detach_1, 0);  view_5 = detach_1 = None

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:20, code: out = self.conv(inp)
        convolution_backward = torch.ops.aten.convolution_backward.default(threshold_backward, primals_5, primals_1, [0], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [False, True, False]);  threshold_backward = primals_5 = primals_1 = None
        getitem_6 = convolution_backward[0]
        getitem_7: f32[32, 32, 1, 1] = convolution_backward[1]
        getitem_8 = convolution_backward[2];  convolution_backward = None
        return pytree.tree_unflatten([view_3, getitem_7, None, None, None, None], self._out_spec)
```

Joint graph after functionalization pass:
https://github.com/pytorch/pytorch/blob/master/functorch/_src/aot_autograd.py#L419
```python
====== Joint graph ======
class fake_fn(torch.nn.Module):
    def forward(self, primals, tangents):
        primals_1: f32[32, 32, 1, 1], primals_2: f32[32], primals_3: f32[32], primals_4: i64[], primals_5: f32[2, 32, 8, 8], tangents_1: f32[2, 32, 8, 8], = fx_pytree.tree_flatten_spec([primals, tangents], self._in_spec)
        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:20, code: out = self.conv(inp)
        convolution: f32[2, 32, 8, 8] = torch.ops.aten.convolution.default(primals_5, primals_1, None, [1, 1], [0, 0], [1, 1], False, [0, 0], 1)

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:21, code: out = out.relu()
        relu: f32[2, 32, 8, 8] = torch.ops.aten.relu.default(convolution);  convolution = None
        detach_1: f32[2, 32, 8, 8] = torch.ops.aten.detach.default(relu)
        detach_2: f32[2, 32, 8, 8] = torch.ops.aten.detach.default(detach_1);  detach_1 = None

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:22, code: out = self.bn(out)
        repeat: f32[64] = torch.ops.aten.repeat.default(primals_2, [2]);  primals_2 = None
        repeat_1: f32[64] = torch.ops.aten.repeat.default(primals_3, [2]);  primals_3 = None
        view: f32[1, 64, 8, 8] = torch.ops.aten.view.default(relu, [1, 64, 8, 8]);  relu = None
        native_batch_norm = torch.ops.aten.native_batch_norm.default(view, None, None, repeat, repeat_1, True, 0.1, 1e-05)
        getitem: f32[1, 64, 8, 8] = native_batch_norm[0]
        getitem_1: f32[64] = native_batch_norm[1]
        getitem_2: f32[64] = native_batch_norm[2];  native_batch_norm = None
        
        # ===========================================
        # view_1 and view_2 are dropped after functionalization pass.
        view_3: f32[2, 32, 8, 8] = torch.ops.aten.view.default(getitem, [2, 32, 8, 8]);  getitem = None
        # ===========================================

        view_4: f32[1, 64, 8, 8] = torch.ops.aten.view.default(tangents_1, [1, 64, 8, 8]);  tangents_1 = None
        native_batch_norm_backward = torch.ops.aten.native_batch_norm_backward.default(view_4, view, None, repeat, repeat_1, getitem_1, getitem_2, True, 1e-05, [True, False, False]);  view_4 = view = repeat = repeat_1 = getitem_1 = getitem_2 = None
        getitem_3: f32[1, 64, 8, 8] = native_batch_norm_backward[0];  native_batch_norm_backward = None
        view_5: f32[2, 32, 8, 8] = torch.ops.aten.view.default(getitem_3, [2, 32, 8, 8]);  getitem_3 = None

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:21, code: out = out.relu()
        detach_3: f32[2, 32, 8, 8] = torch.ops.aten.detach.default(detach_2);  detach_2 = None
        detach_4: f32[2, 32, 8, 8] = torch.ops.aten.detach.default(detach_3);  detach_3 = None
        threshold_backward: f32[2, 32, 8, 8] = torch.ops.aten.threshold_backward.default(view_5, detach_4, 0);  view_5 = detach_4 = None

        # File: /home/rspring/workspace/debug_repro/dynamo_instance_norm.py:20, code: out = self.conv(inp)
        convolution_backward = torch.ops.aten.convolution_backward.default(threshold_backward, primals_5, primals_1, [0], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [False, True, False]);  threshold_backward = primals_5 = primals_1 = None
        getitem_7: f32[32, 32, 1, 1] = convolution_backward[1];  convolution_backward = None
        return pytree.tree_unflatten([view_3, getitem_7, None, None, None, None], self._out_spec)
```

Debug repro:
```python
import torch
import functorch
from torch._dynamo.optimizations.training import aot_nvprims_nvfuser, aot_nvprims_aten
from torch._prims.context import TorchRefsNvfuserCapabilityMode
optimize = torch._dynamo.optimize(aot_nvprims_aten)

torch.cuda.cudart().cudaProfilerStart()

class Fusion(torch.nn.Module):
  def __init__(self) :
    super(Fusion, self).__init__()
    self.conv = torch.nn.Conv2d(32, 32, (1, 1), bias=False)
    self.norm = torch.nn.InstanceNorm2d(32, track_running_stats=True)

  def forward(self, inp) :
    out = self.conv(inp)
    out = out.relu()
    out = self.norm(out)
    return out

model = Fusion().cuda()

input1 = torch.randn(2, 32, 8, 8, device="cuda")

optimized_model = optimize(model)
with torch.cuda.amp.autocast(False):
  for _ in range(5):
    out = optimized_model(input1)
    out.sum().backward()

torch.cuda.synchronize()
torch.cuda.cudart().cudaProfilerStop()
```

### Versions

upstream: a6acbad5

cc @ezyang @gchanan @zou3519 @mruberry @ngimel @Lezcano @fdrocha @peterbell10

**Comment by ezyang** [comment] 2022-11-03 02:21
cc @bdhirsh @Chillee 

Well hmph. I actually do not expect this to work, but that is not much consolation.

The root of the problem is that this is the "input of graph gets mutated case". What is supposed to happen is we are supposed to reject this graph for AOTAutograd, because AOTAutograd doesn't support mutation of inputs to the graph. But instance norm has a wrong mutability annotation and so we don't reject it:

```
- func: instance_norm(Tensor input, Tensor? weight, Tensor? bias, Tensor? running_mean, Tensor? running_var, bool use_input_stats, float momentum, float eps, bool cudnn_enabled) -> Tensor
  variants: function
```

Of course, rejecting instance norm is a pain because you do want to actually compile it. So how can we not reject it? I have a proposal for how to handle input mutations in AOT Autograd correctly at https://docs.google.com/document/d/19UoIh_SVrMy_b2Sx5ZaeOJttm6P0Qmyss2rdBuyfoic/edit?pli=1#heading=h.arzne7xas5cp It needs to be implemented though. 

I don't know if there is a hacky workaround that can side step this issue. So maybe I guess we do have to bump up the priority of implementing input mutation correctly.

**Comment by ngimel** [comment] 2022-11-03 03:01
What are we doing for batch norm that should have the same problem with running stats? Do we have a decomp for it that sidesteps this problem?

**Comment by jjsjann123** [comment] 2022-11-03 15:59
IIUC, BN doesn't have the problem because the in-place update is not visible to autograd. You'll have a BN op that implicitly mutates running stats. Decomposition of BN which expose the mutation happens after autograd so it sorta worked out?!

vs. InstanceNorm, the mutation is shown in the graph and can't be embedded in BN, because of the expand on running stats.

**Comment by bdhirsh** [comment] 2022-11-04 15:05
Yeah, it looks like the difference is that `layer_norm` is composite, while `native_batch_norm` is a primitive.

Both of their alias annotations are "wrong" - they both mutate their inputs, but don't advertise it in their schemas. But in the above repro, what happens with layer norm is:

(1) dynamo tries to detect input mutations, but fails - it uses `layer_norm`'s schema to check for input mutations, but layer_norm advertises as non-mutating. It sends the graph to aot autograd

(2) aot autograd runs decomposes `layer_norm()` (it's a CompositeImplicitAutograd op) into batch_norm + some `copy_()` nodes for the input mutations (compare this to `native_batch_norm`, which is still wrong but doesn't decompose).

(3) functionalization runs - it realizes that those copy_() nodes correspond to input mutations, so it keeps them in the graph to preserve semantics

(4) aot autograd runs DCE, which incorrectly eliminates the input mutations.

As Ed pointed out, there are a couple of broken things here:

(1) aot autograd can't handle input mutations today, and dynamo's analysis pass incorrectly sent the graph to aot autograd (which is was caused wrong results)

(2) Regardless of dynamo's analysis pass, we want to compile layer_norm and batch_norm. So "falling back to eager due to input mutations" would still be the wrong thing - we need to fix up aot autograd to handle input mutations. There's a prototype PR for it [here](https://github.com/pytorch/pytorch/pull/82602) that I'm going to push some more on, and Ed has a great doc on all of the various edge cases [here](https://docs.google.com/document/d/19UoIh_SVrMy_b2Sx5ZaeOJttm6P0Qmyss2rdBuyfoic/edit?usp=sharing).

(3) `native_batch_norm` will still do the wrong thing, because its alias annotations are wrong. The currrent plan is to add a decomposition for it into two new ops that have "correct" aliasing annotations, that functionalization will see.

**Comment by jjsjann123** [comment] 2022-11-04 17:35
Thanks a lot for the comment!

> (2) Regardless of dynamo's analysis pass, we want to compile instance_norm and batch_norm. So "falling back to eager due to input mutations" would still be the wrong thing - we need to fix up aot autograd to handle input mutations. Thttps://github.com/pytorch/pytorch/pull/82602's a prototype PR for it [here](https://docs.google.com/document/d/19UoIh_SVrMy_b2Sx5ZaeOJttm6P0Qmyss2rdBuyfoic/edit?usp=sharing) that I'm going to push some more on, and Ed has a great doc on all of the various edge cases here.

Yay on the part where we agree that `instance_norm` and `batch_norm` is important to be included in computation graph for backends! We would also like to have the option to selectively include certain inplace mutation in the computation graph. e.g. if we leave mutation in an opaque epilogue, we are missing out fusion opportunities. For BN that means two more copy kernel done by eager, which could have been handled by backends that supports IO tensors.

> (3) native_batch_norm will still do the wrong thing, because its alias annotations are wrong. The currrent plan is to add a decomposition for it into two new ops that have "correct" aliasing annotations, that functionalization will see.

This decomposition sounds like not being an opt-in thing? so this means backend using aot-autograd won't have the option to preserve `native_batch_norm` as a single node any more?

**Comment by ngimel** [comment] 2022-11-04 18:39
All backends using aot autograd can (and do) adjust things they want to decompose, aot is getting decompositions list as an argument

**Comment by byronyi** [comment] 2022-11-08 02:24
Increment of num_tracked_batches, or primals_4 in inputs, was not even in the joint graph before functionalization. 

Is this ever intended?

**Comment by eellison** [comment] 2022-11-21 17:56
@bdhirsh assigning this to you since this will be be covered by your input mutation work.

**Comment by bdhirsh** [comment] 2022-11-21 20:33
Is there a repro that includes a correctness test? I believe this should be fixed by https://github.com/pytorch/pytorch/pull/88817 - I ran the above repro, and it runs without erroring, at least.

Running the above repro locally with that patch gives the following FX graphs. The relevant bit is that there are two new outputs in the forward, `alias, alias_1`, that correspond to the updated running mean and running var. AOT Autograd then copies those fresh outputs back to the original running mean and var when it runs the epilogue, after the forward finishes executing.

```
(/scratch/hirsheybar/pytorch-scratch-env) hirsheybar@devfair017:/scratch/hirsheybar/pytorch-scratch$ AOT_FX_GRAPHS_JOINT=1 AOT_FX_GRAPHS=1 python tmp.py
/raid/hirsheybar/pytorch-scratch/torch/storage.py:315: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.
  warnings.warn(message, UserWarning)
====== Joint graph ======
class functionalized_joint(torch.nn.Module):
    def forward(self, primals, tangents):
        primals_1: f32[32, 32, 1, 1], primals_2: f32[32], primals_3: f32[32], primals_4: i64[], primals_5: f32[2, 32, 8, 8], tangents_1: f32[32], tangents_2: f32[32], tangents_3: f32[1, 64, 8, 8], = fx_pytree.tree_flatten_spec([primals, tangents], self._in_spec)
        # No stacktrace found for following nodes
        clone: f32[32] = torch.ops.aten.clone.default(primals_2);  primals_2 = None
        clone_1: f32[32] = torch.ops.aten.clone.default(primals_3);  primals_3 = None

        # File: /raid/hirsheybar/pytorch-scratch/tmp.py:16, code: out = self.conv(inp)
        convolution: f32[2, 32, 8, 8] = torch.ops.aten.convolution.default(primals_5, primals_1, None, [1, 1], [0, 0], [1, 1], False, [0, 0], 1)

        # File: /raid/hirsheybar/pytorch-scratch/tmp.py:17, code: out = out.relu()
        relu: f32[2, 32, 8, 8] = torch.ops.aten.relu.default(convolution);  convolution = None

        # File: /raid/hirsheybar/pytorch-scratch/tmp.py:18, code: out = self.norm(out)
        repeat: f32[64] = torch.ops.aten.repeat.default(clone, [2]);  clone = None
        repeat_1: f32[64] = torch.ops.aten.repeat.default(clone_1, [2]);  clone_1 = None
        view: f32[1, 64, 8, 8] = torch.ops.aten.view.default(relu, [1, 64, 8, 8])
        native_batch_norm = torch.ops.aten.native_batch_norm.default(view, None, None, repeat, repeat_1, True, 0.1, 1e-05)
        getitem: f32[1, 64, 8, 8] = native_batch_norm[0]
        getitem_1: f32[64] = native_batch_norm[1]
        getitem_2: f32[64] = native_batch_norm[2];  native_batch_norm = None
        view_1: f32[2, 32] = torch.ops.aten.view.default(repeat, [2, 32])
        mean: f32[32] = torch.ops.aten.mean.dim(view_1, [0]);  view_1 = None
        view_2: f32[2, 32] = torch.ops.aten.view.default(repeat_1, [2, 32])
        mean_1: f32[32] = torch.ops.aten.mean.dim(view_2, [0]);  view_2 = None

        # No stacktrace found for following nodes
        alias_2: f32[32] = torch.ops.aten.alias.default(mean);  mean = None
        alias_3: f32[32] = torch.ops.aten.alias.default(mean_1);  mean_1 = None

        # File: /raid/hirsheybar/pytorch-scratch/tmp.py:18, code: out = self.norm(out)
        native_batch_norm_backward = torch.ops.aten.native_batch_norm_backward.default(tangents_3, view, None, repeat, repeat_1, getitem_1, getitem_2, True, 1e-05, [True, False, False]);  tangents_3 = view = repeat = repeat_1 = getitem_1 = getitem_2 = None
        getitem_3: f32[1, 64, 8, 8] = native_batch_norm_backward[0];  native_batch_norm_backward = None
        view_4: f32[2, 32, 8, 8] = torch.ops.aten.view.default(getitem_3, [2, 32, 8, 8]);  getitem_3 = None

        # File: /raid/hirsheybar/pytorch-scratch/tmp.py:17, code: out = out.relu()
        threshold_backward: f32[2, 32, 8, 8] = torch.ops.aten.threshold_backward.default(view_4, relu, 0);  view_4 = relu = None

        # File: /raid/hirsheybar/pytorch-scratch/tmp.py:16, code: out = self.conv(inp)
        convolution_backward = torch.ops.aten.convolution_backward.default(threshold_backward, primals_5, primals_1, [0], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [False, True, False]);  threshold_backward = primals_5 = primals_1 = None
        getitem_7: f32[32, 32, 1, 1] = convolution_backward[1];  convolution_backward = None
        return pytree.tree_unflatten([alias_2, alias_3, getitem, 2, 32, 8, 8, 2048, 64, 8, 1, 0, getitem_7, None, None, None, None], self._out_spec)

====== Forward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, primals_1: f32[32, 32, 1, 1], primals_2: f32[32], primals_3: f32[32], primals_4: i64[], primals_5: f32[2, 32, 8, 8]):
        # No stacktrace found for following nodes
        clone: f32[32] = torch.ops.nvprims.clone.default(primals_2, memory_format = torch.preserve_format);  primals_2 = None
        clone_1: f32[32] = torch.ops.nvprims.clone.default(primals_3, memory_format = torch.preserve_format);  primals_3 = None
        convolution: f32[2, 32, 8, 8] = torch.ops.aten.convolution.default(primals_5, primals_1, None, [1, 1], [0, 0], [1, 1], False, [0, 0], 1)
        le: b8[2, 32, 8, 8] = torch.ops.nvprims.le.default(convolution, 0.0)
        where: f32[2, 32, 8, 8] = torch.ops.nvprims.where.default(le, 0.0, convolution);  le = None
        broadcast_in_dim: f32[2, 32] = torch.ops.nvprims.broadcast_in_dim.default(clone, [2, 32], [1]);  clone = None
        clone_2: f32[2, 32] = torch.ops.nvprims.clone.default(broadcast_in_dim, memory_format = torch.preserve_format);  broadcast_in_dim = None
        transpose: f32[2, 32] = torch.ops.nvprims.transpose.default(clone_2, [0, 1]);  clone_2 = None
        view: f32[64] = torch.ops.nvprims.view.default(transpose, [2, 32], [64]);  transpose = None
        broadcast_in_dim_1: f32[2, 32] = torch.ops.nvprims.broadcast_in_dim.default(clone_1, [2, 32], [1]);  clone_1 = None
        clone_3: f32[2, 32] = torch.ops.nvprims.clone.default(broadcast_in_dim_1, memory_format = torch.preserve_format);  broadcast_in_dim_1 = None
        transpose_1: f32[2, 32] = torch.ops.nvprims.transpose.default(clone_3, [0, 1]);  clone_3 = None
        view_1: f32[64] = torch.ops.nvprims.view.default(transpose_1, [2, 32], [64]);  transpose_1 = None
        view_2: f32[1, 64, 8, 8] = torch.ops.nvprims.view.default(where, [2, 32, 8, 8], [1, 64, 8, 8]);  where = None
        native_batch_norm = torch.ops.nvprims.native_batch_norm.default(view_2, None, None, view, view_1, True, 0.1, 1e-05);  view_2 = None
        getitem: f32[1, 64, 8, 8] = native_batch_norm[0]
        getitem_1: f32[64] = native_batch_norm[1]
        getitem_2: f32[64] = native_batch_norm[2];  native_batch_norm = None
        view_3: f32[2, 32] = torch.ops.nvprims.view.default(view, [64], [2, 32]);  view = None
        sum_1: f32[32] = torch.ops.nvprims.sum.default(view_3, [0]);  view_3 = None
        div: f32[32] = torch.ops.nvprims.div.default(sum_1, 2.0);  sum_1 = None
        view_4: f32[2, 32] = torch.ops.nvprims.view.default(view_1, [64], [2, 32]);  view_1 = None
        sum_2: f32[32] = torch.ops.nvprims.sum.default(view_4, [0]);  view_4 = None
        div_1: f32[32] = torch.ops.nvprims.div.default(sum_2, 2.0);  sum_2 = None
        alias: f32[32] = torch.ops.aten.alias.default(div);  div = None
        alias_1: f32[32] = torch.ops.aten.alias.default(div_1);  div_1 = None
        return [alias, alias_1, getitem, 2, 32, 8, 8, 2048, 64, 8, 1, 0, primals_1, primals_5, convolution, getitem_1, getitem_2]

====== Backward graph ======
class GraphModule(torch.nn.Module):
    def forward(self, primals_1: f32[32, 32, 1, 1], primals_5: f32[2, 32, 8, 8], convolution: f32[2, 32, 8, 8], getitem_1: f32[64], getitem_2: f32[64], tangents_1: f32[32], tangents_2: f32[32], tangents_3: f32[1, 64, 8, 8]):
        # No stacktrace found for following nodes
        le: b8[2, 32, 8, 8] = torch.ops.nvprims.le.default(convolution, 0.0)
        where: f32[2, 32, 8, 8] = torch.ops.nvprims.where.default(le, 0.0, convolution);  le = convolution = None
        view_2: f32[1, 64, 8, 8] = torch.ops.nvprims.view.default(where, [2, 32, 8, 8], [1, 64, 8, 8])
        broadcast_in_dim_2: f32[1, 64] = torch.ops.nvprims.broadcast_in_dim.default(getitem_1, [1, 64], [1]);  getitem_1 = None
        broadcast_in_dim_3: f32[1, 64, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_2, [1, 64, 1], [0, 1]);  broadcast_in_dim_2 = None
        broadcast_in_dim_4: f32[1, 64, 1, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_3, [1, 64, 1, 1], [0, 1, 2]);  broadcast_in_dim_3 = None
        sum_3: f32[64] = torch.ops.nvprims.sum.default(tangents_3, [0, 2, 3])
        broadcast_in_dim_5: f32[1, 64, 8, 8] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_4, [1, 64, 8, 8], [0, 1, 2, 3]);  broadcast_in_dim_4 = None
        sub: f32[1, 64, 8, 8] = torch.ops.nvprims.sub.default(view_2, broadcast_in_dim_5);  view_2 = broadcast_in_dim_5 = None
        mul: f32[1, 64, 8, 8] = torch.ops.nvprims.mul.default(tangents_3, sub)
        sum_4: f32[64] = torch.ops.nvprims.sum.default(mul, [0, 2, 3]);  mul = None
        mul_1: f32[64] = torch.ops.nvprims.mul.default(sum_3, 0.015625);  sum_3 = None
        broadcast_in_dim_6: f32[1, 64] = torch.ops.nvprims.broadcast_in_dim.default(mul_1, [1, 64], [1]);  mul_1 = None
        broadcast_in_dim_7: f32[1, 64, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_6, [1, 64, 1], [0, 1]);  broadcast_in_dim_6 = None
        broadcast_in_dim_8: f32[1, 64, 1, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_7, [1, 64, 1, 1], [0, 1, 2]);  broadcast_in_dim_7 = None
        mul_2: f32[64] = torch.ops.nvprims.mul.default(sum_4, 0.015625);  sum_4 = None
        mul_3: f32[64] = torch.ops.nvprims.mul.default(getitem_2, getitem_2)
        mul_4: f32[64] = torch.ops.nvprims.mul.default(mul_2, mul_3);  mul_2 = mul_3 = None
        broadcast_in_dim_9: f32[1, 64] = torch.ops.nvprims.broadcast_in_dim.default(mul_4, [1, 64], [1]);  mul_4 = None
        broadcast_in_dim_10: f32[1, 64, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_9, [1, 64, 1], [0, 1]);  broadcast_in_dim_9 = None
        broadcast_in_dim_11: f32[1, 64, 1, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_10, [1, 64, 1, 1], [0, 1, 2]);  broadcast_in_dim_10 = None
        broadcast_in_dim_12: f32[1, 64] = torch.ops.nvprims.broadcast_in_dim.default(getitem_2, [1, 64], [1]);  getitem_2 = None
        broadcast_in_dim_13: f32[1, 64, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_12, [1, 64, 1], [0, 1]);  broadcast_in_dim_12 = None
        broadcast_in_dim_14: f32[1, 64, 1, 1] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_13, [1, 64, 1, 1], [0, 1, 2]);  broadcast_in_dim_13 = None
        mul_5: f32[1, 64, 1, 1] = torch.ops.nvprims.mul.default(broadcast_in_dim_14, 1.0);  broadcast_in_dim_14 = None
        broadcast_in_dim_16: f32[1, 64, 8, 8] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_11, [1, 64, 8, 8], [0, 1, 2, 3]);  broadcast_in_dim_11 = None
        mul_6: f32[1, 64, 8, 8] = torch.ops.nvprims.mul.default(sub, broadcast_in_dim_16);  sub = broadcast_in_dim_16 = None
        sub_2: f32[1, 64, 8, 8] = torch.ops.nvprims.sub.default(tangents_3, mul_6);  tangents_3 = mul_6 = None
        broadcast_in_dim_17: f32[1, 64, 8, 8] = torch.ops.nvprims.broadcast_in_dim.default(broadcast_in_dim_8, [1, 64, 8, 8], [0, 1, 2, 3]);  broadcast_in_dim_8 = None
        sub_3: f32[1, 64, 8, 8] = torch.ops.nvprims.sub.default(sub_2, broadcast_in_dim_17);  sub_2 = broadcast_in_dim_17 = None
        broadcast_in_dim_18: f32[1, 64, 8, 8] = torch.ops.nvprims.broadcast_in_dim.default(mul_5, [1, 64, 8, 8], [0, 1, 2, 3]);  mul_5 = None
        mul_7: f32[1, 64, 8, 8] = torch.ops.nvprims.mul.default(sub_3, broadcast_in_dim_18);  sub_3 = broadcast_in_dim_18 = None
        view_5: f32[2, 32, 8, 8] = torch.ops.nvprims.view.default(mul_7, [1, 64, 8, 8], [2, 32, 8, 8]);  mul_7 = None
        le_1: b8[2, 32, 8, 8] = torch.ops.nvprims.le.default(where, 0.0);  where = None
        where_1: f32[2, 32, 8, 8] = torch.ops.nvprims.where.default(le_1, 0.0, view_5);  le_1 = view_5 = None
        convolution_backward = torch.ops.aten.convolution_backward.default(where_1, primals_5, primals_1, [0], [1, 1], [0, 0], [1, 1], False, [0, 0], 1, [False, True, False]);  where_1 = primals_5 = primals_1 = None
        getitem_4: f32[32, 32, 1, 1] = convolution_backward[1];  convolution_backward = None
        return [getitem_4, None, None, None, None]
```

**Comment by eellison** [comment] 2023-12-07 18:31
this is fixed right ?

**Closed** 2023-12-31 08:54 UTC
Labels: high priority, triaged, module: primTorch
