### ISSUE TITLE
Improve Pytorch script model inference performance by (ah) 2500 times !

### ISSUE THREAD

**Issue by whatdhack** [pytorch/pytorch#45815] opened 2020-10-04 01:30 UTC
## 🚀 Feature
Pytorch scritp model takes 347s for inference vs regular Pytorch that takes 0.14 s.

## Motivation

Script model infernce appears to be unacceptably slow

## Pitch

See above.

## Alternatives

None

## Additional context

None

cc @gmagogsfm @VitalyFedyunin @ngimel

**Comment by whatdhack** [comment] 2020-10-04 18:42
Looks like  the first iteration takes up taking a lot  of time. Subsequent itearations are ok.  Couple of question  - i) is there a way to diable optimiztion ( primarily for dev works); ii) is there away to pre-optimize ?

**Comment by robieta** [comment] 2020-10-05 16:31
Please provide a minimal, self contained repro.

**Comment by suo** [comment] 2020-10-06 17:03
Thanks for the report! As mentioned above, it would help us if you could provide an example of a workload you are seeing with slow optimization. Also, what version of PyTorch are you using? We had a regression in compilation times but it should be fixed on the nightly, so maybe trying that can help.

**Comment by gmagogsfm** [comment] 2021-07-29 17:52
Closing due to inactivity

**Closed by gmagogsfm** 2021-07-29 17:52 UTC
Labels: module: performance, oncall: jit, triaged
