### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '/p:CL_MPCount=8']' returned non-zero exit status 1

### ISSUE THREAD

**Issue by dusha1248** [pytorch/pytorch#46208] opened 2020-10-12 19:34 UTC
## 🐛 Bug

Hello! I have VS 17 version 15.9 with VC++ 2017 version 15.6 v14.13 toolset. I try to install pytorch like in instruction, but an hour later I get an error:

Traceback (most recent call last):
  File "setup.py", line 727, in <module>
    build_deps()
  File "setup.py", line 314, in build_deps
    build_caffe2(version=version,
  File "C:\Users\andre\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "C:\Users\andre\pytorch\tools\setup_helpers\cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "C:\Users\andre\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "C:\Users\andre\anaconda3\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '/p:CL_MPCount=8']' returned non-zero exit status 1.

## Environment

 - PyTorch Version: 1.8.0
 - OS: Windows 10
 - How you installed PyTorch: source
 - Build command you used (if compiling from source):
git submodule sync (optional)
git submodule update --init --recursive (optional)
set USE_NINJA=OFF
set CMAKE_GENERATOR=Visual Studio 15 2017
set CMAKE_GENERATOR_TOOLSET_VERSION=14.13   (optional)
set DISTUTILS_USE_SDK=1   (optional)
C:\Users\andre\pytorch>for /f "usebackq tokens=*" %i in (`"%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" -version [15^,16^) -products * -latest -property installationPath`) do call "%i\VC\Auxiliary\Build\vcvarsall.bat" x64 -vcvars_ver=%CMAKE_GENERATOR_TOOLSET_VERSION%  (optional)
C:\Users\andre\pytorch>set CUDAHOSTCXX=C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\cl.exe  (optional)
python setup.py install > build.log 2>&1
(I've tried to install with and without any optional commands)
 - Python version: 3.8.5
 - CUDA/cuDNN version: 10.0/7.6.5
 - GPU models and configuration: NVIDIA GeForce GTX 870M

 - Any other relevant information:

## Additional context

I've tried several solutions from similar problems, but they didn't work:
https://github.com/pytorch/pytorch/issues/28369
https://github.com/pytorch/pytorch/issues/20420

I attach a log file.
[build.log](https://github.com/pytorch/pytorch/files/5367116/build.log)

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by malfet** [comment] 2020-10-12 21:22
Few important excerpts from the log:
```
--   C++ compiler          : C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/HostX64/x64/cl.exe
--   C++ compiler version  : 19.13.26132.1
```
And than later (Having to use [CP-866](https://en.wikipedia.org/wiki/Code_page_866) brings back memories) :
```
C:\Users\andre\pytorch\aten\src\ATen/core/boxing/impl/boxing.h(150): error C2210: "_Ty": расширения пакетов невозможно использовать в качестве аргументов для неупакованных параметров в шаблонах псевдонимов 
(компилируется исходный файл C:\Users\andre\pytorch\aten\src\ATen\BatchingRegistrations.cpp) [C:\Users\andre\pytorch\build\caffe2\torch_cpu.vcxproj]
```,  where error roughtly translates as `pack expansions cannot be used as arguments to non-packed parameters in alias templates`

@dusha1248 is there any reason, why you need to use such an old compiler ? Something tells me, that 14.13 is not C++14 compliant, which causes a compilation failure.

**Comment by dusha1248** [comment] 2020-10-12 22:04
> Few important excerpts from the log:
> 
> ```
> --   C++ compiler          : C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/HostX64/x64/cl.exe
> --   C++ compiler version  : 19.13.26132.1
> ```
> 
> And than later (Having to use [CP-866](https://en.wikipedia.org/wiki/Code_page_866) brings back memories) :
> 
> ```
> C:\Users\andre\pytorch\aten\src\ATen/core/boxing/impl/boxing.h(150): error C2210: "_Ty": расширения пакетов невозможно использовать в качестве аргументов для неупакованных параметров в шаблонах псевдонимов 
> (компилируется исходный файл C:\Users\andre\pytorch\aten\src\ATen\BatchingRegistrations.cpp) [C:\Users\andre\pytorch\build\caffe2\torch_cpu.vcxproj]
> ```
> 
> where error roughly translates as `pack expansions cannot be used as arguments to non-packed parameters in alias templates`
> 
> @dusha1248 is there any reason, why you need to use such an old compiler ? Something tells me, that 14.13 is not C++14 compliant, which causes a compilation failure.

In your instruction is written:
:: [Optional] If you want to override the Cuda host compiler
set CUDAHOSTCXX=C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\cl.exe

Is 14.11 C++14 complaint? Does Visual Studio have suitable compiler? Sorry for stupid question.

**Comment by dusha1248** [comment] 2020-10-14 00:55
I install clang++ compiler and set it as CUDAHOSTCXX, but mistakes are repeated.

**Comment by twister1606** [comment] 2020-12-30 10:23
Traceback (most recent call last):
File "eval.py", line 185, in
main()
File "eval.py", line 86, in main
model = neurvps.models.VanishingNet(
File "C:\Users\Dimple\neurvps\neurvps\models\vanishing_net.py", line 23, in init
self.anet = ApolloniusNet(output_stride, upsample_scale)
File "C:\Users\Dimple\neurvps\neurvps\models\vanishing_net.py", line 90, in init
self.conv00 = ConicConv(32, 32)
File "C:\Users\Dimple\neurvps\neurvps\models\conic.py", line 12, in init
self.deform_conv = DeformConv(
File "C:\Users\Dimple\neurvps\neurvps\models\deformable.py", line 132, in init
DCN = load_cpp_ext("DCN")
File "C:\Users\Dimple\neurvps\neurvps\models\deformable.py", line 24, in load_cpp_ext
ext = load(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 986, in load
return _jit_compile(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1193, in _jit_compile
_write_ninja_file_and_build_library(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1285, in _write_ninja_file_and_build_library
_write_ninja_file_to_build_library(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1679, in _write_ninja_file_to_build_library
_write_ninja_file(
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\site-packages\torch\utils\cpp_extension.py", line 1790, in _write_ninja_file
cl_paths = subprocess.check_output(['where',
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\subprocess.py", line 411, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "C:\Users\Dimple\anaconda3\envs\neurvps\lib\subprocess.py", line 512, in run
raise CalledProcessError(retcode, process.args, output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['where', 'cl']' returned non-zero exit status 1.

Got this error while working on this project: https://github.com/zhou13/neurvps
Please help us resolve it ASAP

**Comment by peterjc123** [comment] 2020-12-31 03:29
> Command '['where', 'cl']' returned non-zero exit status 1.

You'll need to activate the VC env first.

**Comment by cristianPanaite** [comment] 2023-01-10 07:23
Hello @dusha1248,

With the latest version, following the steps from the current tutorial, I was able to install from source without any error.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.

**Comment by Blackhex** [comment] 2023-01-10 09:57
I am closing the issue for the reason above and as the VS2017 build is already not supported.

**Closed by Blackhex** 2023-01-10 09:57 UTC
Labels: module: build, module: windows, triaged
