### ISSUE TITLE
std: ambiguous in C++17.h, upgrading from LibTorch 1.6.0 to 1.8.1 with MSVC 2019 and c++17 standard 

### ISSUE THREAD

**Issue by hcyang** [pytorch/pytorch#57424] opened 2021-05-01 23:37 UTC
## 🐛 Bug

We have a C++ LibTorch project built with MSVC 2019 (V16.9.4) on Windows 10. Our C++ standard setting is C++17. This program built fine with LibTorch 1.6.0+cpu, but it cannot build after upgrading to LibTorch 1.8.1+cpu.
The error messages was "std: ambiguous" around C++17.h.

## To Reproduce

1. Write simple Lib Torch program:
    #include <torch/torch.h>
    #include <torch/script.h>

    {
        ...
        torch::jit::load( inputStream, device, extra_files);
        ....
    }

2. Setting a MSVC project with LibTorch 1.6.0+cpu following the steps in
    https://expoundai.wordpress.com/2020/10/13/setting-up-a-cpp-project-in-visual-studio-2019-with-libtorch-1-6/

3. Download the latest LibTorch 1.8.1+cpu and use it to replace the original 1.6.0 setup. The build fails with the "std: ambiguous" error in libtorch\include\c10\util\C++17.h.

## Expected behavior

The build process should not fail after upgrading LibTorch from 1.6.0 to 1.8.1

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

Below is the result of running collect_env.py, but almost of them are irrelevant to the LibTorch regression filed in this issue.

Collecting environment information...
PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.17.2

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: 10.1.168
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] numpydoc==1.1.0
[pip3] torch==1.7.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37h196d8e1_0
[conda] mkl_fft                   1.3.0            py37h46781fe_0
[conda] mkl_random                1.1.1            py37h47e9c7a_0
[conda] numpy                     1.19.2           py37hadc3359_0
[conda] numpy-base                1.19.2           py37ha3acd2a_0
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1
[conda] torch                     1.7.1                    pypi_0    pypi

## Additional context

cc @malfet @seemethere @walterddr @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by peterjc123** [comment] 2021-05-03 03:05
@hcyang Would you please share the complete list of errors?

**Comment by hcyang** [comment] 2021-05-03 18:29
[PytorchIssue57424.zip](https://github.com/pytorch/pytorch/files/6416878/PytorchIssue57424.zip)

Here is a repro solution. The main program does nothing except including two torch header files.
Below is the snapshot of the error messages.

![build_error_1 8 1](https://user-images.githubusercontent.com/370110/116916874-bca87200-ac02-11eb-9a9c-6bc325d673c8.png)

**Comment by hcyang** [comment] 2021-05-03 18:32
BTW, the VS2019 solution/project references two libtorch folder "libtorch" and "libtorch_debug", which were not included in the zip file. Please recreate them for repro.

**Comment by peterjc123** [comment] 2021-05-04 03:56
@hcyang The workaround is to append `::` before `std::function` calls in `C++17.h`. Further investigation is in progress.

**Comment by peterjc123** [comment] 2021-05-04 11:17
It seems the real problem is the implementation of `if constexpr` in MSVC. If we rewrite the function at question like the following, it doesn't fail.
```cpp
template<bool Condition, class ThenCallback>
decltype(auto) if_constexpr(ThenCallback&& thenCallback) {
    return std::forward<ThenCallback>(thenCallback)();
}
```
But if we add `if constexpr` there, then the compiler is unhappy.
```cpp
template<bool Condition, class ThenCallback>
decltype(auto) if_constexpr(ThenCallback&& thenCallback) {
if constexpr(Condition) {
    return std::forward<ThenCallback>(thenCallback)();
}
}
```
This piece of code throws `error C2872: 'std': ambiguous symbol`.

**Comment by peterjc123** [comment] 2021-05-04 11:54
Close this issue since this is a duplicate of https://github.com/pytorch/pytorch/issues/53409.

**Closed by peterjc123** 2021-05-04 11:54 UTC
Labels: module: build, module: windows, triaged
