### ISSUE TITLE
x.view() does not work after pooling on quantized tensors

### ISSUE THREAD

**Issue by raghuramank100** [pytorch/pytorch#25890] opened 2019-09-10 02:19 UTC
x.view() does not work for quantized tensors after pooling, likely due to layout optimizations in pooling for NHWC:
Repro code:
``` python
import torch
import torch.nn as nn
# Float works

X  = torch.rand(1, 1, 32,32)
X_q = torch.quantize_linear(X, 1.0, 0, torch.quint8)
conv1 = nn.Conv2d(1, 2, 5, 1)

y = conv1(X_q.dequantize())
z = torch.nn.functional.max_pool2d(y, 2, 2)
print(z.size())
z = z.view(-1,2*14*14)
```
```
torch.Size([1, 2, 14, 14])
```

``` 
# Quantized does not
conv1 = nn.quantized.Conv2d(1, 2, 5, 1)
y = conv1(X_q)
z = torch.nn.functional.max_pool2d(y, 2, 2)
print(z.size())
z = z.view(-1,2*14*14)
```
```
torch.Size([1, 2, 14, 14])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-34a3b8f0713f> in <module>
      4 z = torch.nn.functional.max_pool2d(y, 2, 2)
      5 print(z.size())
----> 6 z = z.view(-1,2*14*14)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.
```

**Comment by jamesr66a** [comment] 2019-09-10 02:33
I'd actually say this is now working as intended and not actually related to MaxPool2d. NHWC layouts throughout quantized networks is a choice we're explicitly making, and this is perhaps the best-case scenario for error reporting: the mismatch is explicit, the user has to option to opt-in to more data movement if needed, and the error states explicitly what the solution would be.

Closing for now as I don't believe this is actionable apart from switching FBGEMM to NCHW layout.

**Comment by jamesr66a** [comment] 2019-09-10 02:34
It should go without saying: we should communicate in the documentation that quantized Conv2d uses a different data layout, and that users may encounter scenarios like this

**Closed by jamesr66a** 2019-09-10 02:33 UTC
Labels: quantization_release_1.3
