### ISSUE TITLE
torch.sort returns incorrect results for integer vectors with size greater than 32,768 on Windows

### ISSUE THREAD

**Issue by aymenkhs** [pytorch/pytorch#133405] opened 2024-08-14 04:12 UTC
## Description
The `torch.sort` function returns incorrect values when the input is an integer vector with a size larger than 2^15 (32,768). The output appears to be random, sometimes some elements are zero (even when zero isn't in the original vector), other times the sorting start from seemingly random values.

This issue does not manifest under the following conditions:
- With vectors with sizes below 2^15 (32768)
- When the data type is a floating point (e.g., `float32`, `float64`). The issue is specific to integer data types.
- When using multi-dimensional tensors, even if one of the dimensions exceeds 2^15 (32768)
-On Linux and in Google Colab environments. I haven't tested on macOS, but I suspect the issue is limited to Windows on version 2.4.0. 

This issue might be related to #132486 and #131958 , although I couldn't verify whether it is CPU-specific.

## Minimal reproducible example:

```python
import torch

print("size = 9")
x = torch.arange(1, 10)
print(x)
print(torch.sort(x)) # works as expected

print("-"*10)

print("size = 2^15 - 1")
x = torch.arange(1, 32768)
print(x)
print(torch.sort(x)) # works as expected

print("-"*10)

print("size = 2^15")
x = torch.arange(1, 32769)
print(x)
print(torch.sort(x)) # give incorrect values

print("-"*10)

print("size = 100000")
x = torch.arange(1, 100000)
print(x)
print(torch.sort(x)) # give incorrect values
```

Output :
```
size = 9
tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])
torch.return_types.sort(
values=tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]),
indices=tensor([0, 1, 2, 3, 4, 5, 6, 7, 8]))
----------
size = 2^15 - 1
tensor([    1,     2,     3,  ..., 32765, 32766, 32767])
torch.return_types.sort(
values=tensor([    1,     2,     3,  ..., 32765, 32766, 32767]),
indices=tensor([    0,     1,     2,  ..., 32764, 32765, 32766]))
----------
size = 2^15
tensor([    1,     2,     3,  ..., 32766, 32767, 32768])
torch.return_types.sort(
values=tensor([29413, 29414, 29415,  ..., 32766, 32767, 32768]),
indices=tensor([29412, 29413, 29414,  ..., 32765, 32766, 32767]))
----------
size = 100000
tensor([    1,     2,     3,  ..., 99997, 99998, 99999])
torch.return_types.sort(
values=tensor([    0,     0,     0,  ..., 99997, 99998, 99999]),
indices=tensor([    0,     0,     0,  ..., 99996, 99997, 99998]))
```

### Versions

Collecting environment information...
PyTorch version: 2.4.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=893
DeviceID=CPU0
Family=205
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=1300
Name=13th Gen Intel(R) Core(TM) i5-1335U
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] torch==2.4.0
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex

**Comment by xuhancn** [comment] 2024-08-14 21:38
Hi @aymenkhs could you please validate it on nightly build?
```cmd
pip install torch  --index-url https://download.pytorch.org/whl/nightly/cu121 --force-reinstall
```

**Comment by aymenkhs** [comment] 2024-08-15 07:08
Hi @xuhancn Yes the problem is fixed on the nightly build on my end.

```python
import torch
x = torch.arange(1, 100000)
print(x)
print(torch.sort(x))
```

```
tensor([    1,     2,     3,  ..., 99997, 99998, 99999])
torch.return_types.sort(
values=tensor([    1,     2,     3,  ..., 99997, 99998, 99999]),
indices=tensor([    0,     1,     2,  ..., 99996, 99997, 99998]))
```

**Comment by xuhancn** [comment] 2024-08-19 23:02
Closed by it is root caused: https://github.com/pytorch/pytorch/issues/133405#issuecomment-2290790672

**Closed by xuhancn** 2024-08-19 23:02 UTC
Labels: module: windows, triaged
