### ISSUE TITLE
FAIL: test_torch (__main__.TestDocCoverage)

### ISSUE THREAD

**Issue by gottbrath** [pytorch/pytorch#27703] opened 2019-10-10 15:56 UTC
## 🐛 Bug

after our v1.3.0 doc changes i am seeing a test failure

FAIL: test_torch (__main__.TestDocCoverage)

## To Reproduce

1. git checkout upstream master
2. python ./test/test_docs_coverage.py

AssertionError: Items in the second set but not the first:
'real'
'imag'
'conj'
'angle' : 
The lists of tensor methods documented in tensors.rst and in python are
different. Did you forget to add a new thing to tensors.rst, or whitelist
things you don't want to document?

======================================================================
FAIL: test_torch (__main__.TestDocCoverage)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test/test_docs_coverage.py", line 73, in test_torch
    don't want to document?''')
AssertionError: Items in the first set but not the second:
'promote_types'
'result_type'
'can_cast'
Items in the second set but not the first:
'quantize_per_tensor'
'quantize_per_channel' : 
The lists of functions documented in torch.rst and in python are different.
Did you forget to add a new thing to torch.rst, or whitelist things you
don't want to document?

----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (failures=2)

## Expected behavior

git checkout pr-fix-doc-test-failure

gottbrath@ubuntu:~/pytorch-for-doc$ python ./test/test_docs_coverage.py 
..
----------------------------------------------------------------------
Ran 2 tests in 0.003s

OK

cc @ezyang

**Comment by gottbrath** [comment] 2019-10-10 15:56
por is https://github.com/pytorch/pytorch/pull/27684

**Comment by gottbrath** [comment] 2019-10-10 16:40
ok .. that PR might not quite do the trick. our index.rtf PR got reverted.. let me go see if I can solve that and this at the same time.

**Comment by cpuhrsch** [comment] 2019-10-10 17:30
@gottbrath I'm flagging this as triaged since I assume you're onto this.

**Comment by gottbrath** [comment] 2019-10-10 17:33
yep.. i am on it!

**Comment by ezyang** [comment] 2019-10-11 17:02
We reverted the diff

**Comment by zou3519** [comment] 2019-10-15 20:48
This does not seem like an issue (the docs test is behaving as intended), so I am closing this. Please feel free to reopen if I misinterpreted anything.

**Closed** 2019-10-15 20:50 UTC
Labels: module: doc infra, module: docs, module: tests, triaged
