### ISSUE TITLE
Pytorch build finds local mkl instead of conda version

### ISSUE THREAD

**Issue by meder411** [pytorch/pytorch#7083] opened 2018-04-30 01:47 UTC
I've followed the installation instructions for a Conda build on Linux:

```
export CMAKE_PREFIX_PATH="$(dirname $(which conda))/../" # [anaconda root directory]

# Install basic dependencies
conda install numpy pyyaml mkl mkl-include setuptools cmake cffi typing

# Add LAPACK support for the GPU
conda install -c pytorch magma-cuda80 # or magma-cuda90 if CUDA 9

git clone --recursive https://github.com/pytorch/pytorch
cd pytorch

python setup.py install
```

but I get an import error for MKL:

> ImportError: /usr/local/lib/libmkl_gf_lp64.so: undefined symbol: mkl_lapack_ao_zgetrf

when I try to import torch in Python.

This seems to be because during the build it links to the /usr/local/lib version rather than the anaconda version. I've set the CMAKE_PREFIX_PATH env variable (as above) as well as set LD_LIBRARY_PATH to include the anaconda lib directory (`/usr/local/anaconda2/lib`). I've also added a conda.conf file to my `/etc/ld.so.conf.d/` directory and ran `sudo ldconfig` to source the changes.

I tried setting the MKLROOT env variable as suggested in [this issue](https://github.com/pytorch/pytorch/issues/6131), but that didn't work either. Additionally, I tried setting `MKLMLROOT=/usr/local/anaconda2` based on line 111 of `pytorch/cmake/Modules/FindMKL.cmake` where it looks like that's the env variable it looks for:

```
find_path(MKLML_ROOT include/mkl.h PATHS $ENV{MKLMLROOT} ${INTEL_ROOT}/mkl
    DOC "Folder contains MKLML")
```
but that didn't work either.

I'm not quite sure what else I can do to indicate to the install to find the libraries in anacadona.

Is there a step I'm missing?

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): dependencies through conda, PyTorch from source
- Build command you used (if compiling from source): (above)
- OS: Ubuntu 16.04
- PyTorch version: source
- Python version: 2.7
- CUDA/cuDNN version: 9.0
- GPU models and configuration: Not relevant
- GCC version (if compiling from source): 5.4.0
- CMake version: 3.9.4
- Versions of any other relevant libraries: I ran `conda install mkl=2018` to make sure I had the most up to date

**Comment by ezyang** [comment] 2018-04-30 02:34
Yeah, it sounds like we're picking up the wrong MKL and not giving you a knob to change which one we pick. You can confirm this if you post the build log, and we can see in the cmake configuration lines which ones it's detecting.

It doesn't look like setup.py has a knob for setting MKL. @orionr is working on a refactor that would obsolete the setup.py, so it's probably not worth fixing directly.  You can probably poke it some more by editing `./aten/src/TH/cmake/FindMKL.cmake`

> I tried setting the MKLROOT env variable as suggested in this issue, but that didn't work either. Additionally, I tried setting MKLMLROOT=/usr/local/anaconda2 based on line 111 of pytorch/cmake/Modules/FindMKL.cmake where it looks like that's the env variable it looks for:

Wrong MKL find script. You want `./aten/src/TH/cmake/FindMKL.cmake` (and yes, we are in the process of consolidating these. Repo merge fallout.)

**Comment by meder411** [comment] 2018-04-30 02:48
Here's the configuration details from the build log after running `python setup.py install`

```
running install
running build_deps
+ WITH_CUDA=0
+ [[ --with-cuda == \-\-\w\i\t\h\-\c\u\d\a ]]
+ WITH_CUDA=1
+ shift
+ WITH_NNPACK=0
+ [[ --with-nnpack == \-\-\w\i\t\h\-\n\n\p\a\c\k ]]
+ WITH_NNPACK=1
+ shift
+ WITH_MKLDNN=0
+ [[ nccl == \-\-\w\i\t\h\-\m\k\l\d\n\n ]]
+ WITH_GLOO_IBVERBS=0
+ [[ nccl == \-\-\w\i\t\h\-\g\l\o\o\-\i\b\v\e\r\b\s ]]
+ WITH_DISTRIBUTED_MW=0
+ [[ nccl == \-\-\w\i\t\h\-\d\i\s\t\r\i\b\u\t\e\d\-\m\w ]]
+ CMAKE_INSTALL='make install'
+ USER_CFLAGS=
+ USER_LDFLAGS=
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ dirname tools/build_pytorch_libs.sh
+ cd tools/..
+++ pwd
++ printf '%q\n' /usr/local/src/pytorch
+ PWD=/usr/local/src/pytorch
+ BASE_DIR=/usr/local/src/pytorch
+ TORCH_LIB_DIR=/usr/local/src/pytorch/torch/lib
+ INSTALL_DIR=/usr/local/src/pytorch/torch/lib/tmp_install
+ THIRD_PARTY_DIR=/usr/local/src/pytorch/third_party
+ CMAKE_VERSION=cmake
+ C_FLAGS=' -DTH_INDEX_BASE=0 -I"/usr/local/src/pytorch/torch/lib/tmp_install/include"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/TH" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THC"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THS" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCS"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THNN" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCUNN"'
+ C_FLAGS=' -DTH_INDEX_BASE=0 -I"/usr/local/src/pytorch/torch/lib/tmp_install/include"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/TH" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THC"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THS" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCS"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THNN" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ LDFLAGS='-L"/usr/local/src/pytorch/torch/lib/tmp_install/lib" '
+ LD_POSTFIX=.so.1
+ LD_POSTFIX_UNVERSIONED=.so
++ uname
+ [[ Linux == \D\a\r\w\i\n ]]
+ LDFLAGS='-L"/usr/local/src/pytorch/torch/lib/tmp_install/lib"  -Wl,-rpath,$ORIGIN'
+ CPP_FLAGS=' -std=c++11 '
+ GLOO_FLAGS=
+ THD_FLAGS=
+ NCCL_ROOT_DIR=/usr/local/src/pytorch/torch/lib/tmp_install
+ [[ 1 -eq 1 ]]
+ GLOO_FLAGS='-DUSE_CUDA=1 -DNCCL_ROOT_DIR=/usr/local/src/pytorch/torch/lib/tmp_install'
+ [[ 0 -eq 1 ]]
+ [[ 0 -eq 1 ]]
+ CWRAP_FILES='/usr/local/src/pytorch/torch/lib/ATen/Declarations.cwrap;/usr/local/src/pytorch/torch/lib/THNN/generic/THNN.h;/usr/local/src/pytorch/torch/lib/THCUNN/generic/THCUNN.h;/usr/local/src/pytorch/torch/lib/ATen/nn.yaml'
+ CUDA_NVCC_FLAGS=' -DTH_INDEX_BASE=0 -I"/usr/local/src/pytorch/torch/lib/tmp_install/include"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/TH" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THC"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THS" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCS"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THNN" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1'
+ [[ '' -eq 1 ]]
+ '[' -z 20 ']'
+ BUILD_TYPE=Release
+ [[ -n '' ]]
+ [[ -n '' ]]
+ echo 'Building in Release mode'
Building in Release mode
+ mkdir -p torch/lib/tmp_install
+ for arg in '"$@"'
+ [[ nccl == \n\c\c\l ]]
+ pushd /usr/local/src/pytorch/third_party
/usr/local/src/pytorch/third_party /usr/local/src/pytorch
+ build_nccl
+ mkdir -p build/nccl
+ pushd build/nccl
/usr/local/src/pytorch/third_party/build/nccl /usr/local/src/pytorch/third_party /usr/local/src/pytorch
+ cmake ../../nccl -DCMAKE_MODULE_PATH=/usr/local/src/pytorch/cmake/FindCUDA -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local/src/pytorch/torch/lib/tmp_install '-DCMAKE_C_FLAGS= -DTH_INDEX_BASE=0 -I"/usr/local/src/pytorch/torch/lib/tmp_install/include"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/TH" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THC"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THS" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCS"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THNN" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1 ' '-DCMAKE_CXX_FLAGS= -DTH_INDEX_BASE=0 -I"/usr/local/src/pytorch/torch/lib/tmp_install/include"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/TH" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THC"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THS" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCS"   -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THNN" -I"/usr/local/src/pytorch/torch/lib/tmp_install/include/THCUNN" -DOMPI_SKIP_MPICXX=1  -std=c++11  ' -DCMAKE_SHARED_LINKER_FLAGS=
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "7.0") 
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/pytorch/third_party/build/nccl
+ make install
Scanning dependencies of target nccl
[100%] Generating lib/libnccl.so
Grabbing  src/nccl.h                          > /usr/local/src/pytorch/third_party/build/nccl/include/nccl.h
Compiling src/libwrap.cu                      > /usr/local/src/pytorch/third_party/build/nccl/obj/libwrap.o
Compiling src/core.cu                         > /usr/local/src/pytorch/third_party/build/nccl/obj/core.o
Compiling src/all_gather.cu                   > /usr/local/src/pytorch/third_party/build/nccl/obj/all_gather.o
Compiling src/all_reduce.cu                   > /usr/local/src/pytorch/third_party/build/nccl/obj/all_reduce.o
Compiling src/broadcast.cu                    > /usr/local/src/pytorch/third_party/build/nccl/obj/broadcast.o
Compiling src/reduce.cu                       > /usr/local/src/pytorch/third_party/build/nccl/obj/reduce.o
Compiling src/reduce_scatter.cu               > /usr/local/src/pytorch/third_party/build/nccl/obj/reduce_scatter.o
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
ptxas warning : Too big maxrregcount value specified 96, will be ignored
Linking   libnccl.so.1.3.5                    > /usr/local/src/pytorch/third_party/build/nccl/lib/libnccl.so.1.3.5
Archiving libnccl_static.a                    > /usr/local/src/pytorch/third_party/build/nccl/lib/libnccl_static.a
[100%] Built target nccl
Install the project...
-- Install configuration: "Release"
-- Installing: /usr/local/src/pytorch/torch/lib/tmp_install/include/nccl.h
+ mkdir -p /usr/local/src/pytorch/torch/lib/tmp_install/lib
+ cp lib/libnccl.so.1 /usr/local/src/pytorch/torch/lib/tmp_install/lib/libnccl.so.1
+ '[' '!' -f /usr/local/src/pytorch/torch/lib/tmp_install/lib/libnccl.so ']'
+ ln -s /usr/local/src/pytorch/torch/lib/tmp_install/lib/libnccl.so.1 /usr/local/src/pytorch/torch/lib/tmp_install/lib/libnccl.so
+ popd
/usr/local/src/pytorch/third_party /usr/local/src/pytorch
+ popd
/usr/local/src/pytorch
+ for arg in '"$@"'
+ [[ ATen == \n\c\c\l ]]
+ [[ ATen == \g\l\o\o ]]
+ [[ ATen == \A\T\e\n ]]
+ pushd /usr/local/src/pytorch/aten
/usr/local/src/pytorch/aten /usr/local/src/pytorch
+ build_aten
+ mkdir -p build
+ pushd build
/usr/local/src/pytorch/aten/build /usr/local/src/pytorch/aten /usr/local/src/pytorch
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DNO_CUDA=0 -DNO_NNPACK=0 -DCUDNN_INCLUDE_DIR=/usr/local/cuda/include -DCUDNN_LIB_DIR=/usr/local/cuda/lib64 -DCUDNN_LIBRARY=/usr/local/cuda/lib64/libcudnn.so.7 -DNO_MKLDNN=1 -DMKLDNN_INCLUDE_DIR= -DMKLDNN_LIB_DIR= -DMKLDNN_LIBRARY= -DATEN_NO_CONTRIB=1 -DCMAKE_INSTALL_PREFIX=/usr/local/src/pytorch/torch/lib/tmp_install -DCMAKE_EXPORT_COMPILE_COMMANDS=1 -DCMAKE_C_FLAGS= -DCMAKE_CXX_FLAGS= -DCMAKE_EXE_LINKER_FLAGS= -DCMAKE_SHARED_LINKER_FLAGS=
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test SUPPORT_GLIBCXX_USE_C99
-- Performing Test SUPPORT_GLIBCXX_USE_C99 - Success
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found CUDA: /usr/local/cuda (found suitable version "9.0", minimum required is "5.5") 
-- Autodetected CUDA architecture(s): 6.1 6.1 6.1 6.1 
-- Found CUDA with FP16 support, compiling with torch.CudaHalfTensor
-- Removing -DNDEBUG from compile flags
CMake Warning (dev) at /usr/local/anaconda2/share/cmake-3.9/Modules/FindOpenMP.cmake:200 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "c" will no longer be dereferenced when the policy is
  set to NEW.  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/local/anaconda2/share/cmake-3.9/Modules/FindOpenMP.cmake:324 (_OPENMP_GET_FLAGS)
  CMakeLists.txt:171 (FIND_PACKAGE)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
-- Compiling with OpenMP support
-- Checking prototype magma_get_sgeqrf_nb for MAGMA_V2 - True
-- Compiling with MAGMA support
-- MAGMA INCLUDE DIRECTORIES: /usr/local/anaconda2/include
-- MAGMA LIBRARIES: /usr/local/anaconda2/lib/libmagma.a
-- MAGMA V2 check: 1
-- Could not find hardware support for NEON on this machine.
-- No OMAP3 processor on this machine.
-- No OMAP4 processor on this machine.
-- Performing Test COMPILER_WORKS
-- Performing Test COMPILER_WORKS - Success
-- Looking for cpuid.h
-- Looking for cpuid.h - found
-- Performing Test HAVE_GCC_GET_CPUID
-- Performing Test HAVE_GCC_GET_CPUID - Success
-- Performing Test NO_GCC_EBX_FPIC_BUG
-- Performing Test NO_GCC_EBX_FPIC_BUG - Success
-- Performing Test C_HAS_SSE1_1
-- Performing Test C_HAS_SSE1_1 - Success
-- Performing Test C_HAS_SSE2_1
-- Performing Test C_HAS_SSE2_1 - Success
-- Performing Test C_HAS_SSE3_1
-- Performing Test C_HAS_SSE3_1 - Failed
-- Performing Test C_HAS_SSE3_2
-- Performing Test C_HAS_SSE3_2 - Success
-- Performing Test C_HAS_SSE4_1_1
-- Performing Test C_HAS_SSE4_1_1 - Failed
-- Performing Test C_HAS_SSE4_1_2
-- Performing Test C_HAS_SSE4_1_2 - Success
-- Performing Test C_HAS_SSE4_2_1
-- Performing Test C_HAS_SSE4_2_1 - Failed
-- Performing Test C_HAS_SSE4_2_2
-- Performing Test C_HAS_SSE4_2_2 - Success
-- Performing Test C_HAS_AVX_1
-- Performing Test C_HAS_AVX_1 - Failed
-- Performing Test C_HAS_AVX_2
-- Performing Test C_HAS_AVX_2 - Success
-- Performing Test C_HAS_AVX2_1
-- Performing Test C_HAS_AVX2_1 - Failed
-- Performing Test C_HAS_AVX2_2
-- Performing Test C_HAS_AVX2_2 - Success
-- Performing Test CXX_HAS_SSE1_1
-- Performing Test CXX_HAS_SSE1_1 - Success
-- Performing Test CXX_HAS_SSE2_1
-- Performing Test CXX_HAS_SSE2_1 - Success
-- Performing Test CXX_HAS_SSE3_1
-- Performing Test CXX_HAS_SSE3_1 - Failed
-- Performing Test CXX_HAS_SSE3_2
-- Performing Test CXX_HAS_SSE3_2 - Success
-- Performing Test CXX_HAS_SSE4_1_1
-- Performing Test CXX_HAS_SSE4_1_1 - Failed
-- Performing Test CXX_HAS_SSE4_1_2
-- Performing Test CXX_HAS_SSE4_1_2 - Success
-- Performing Test CXX_HAS_SSE4_2_1
-- Performing Test CXX_HAS_SSE4_2_1 - Failed
-- Performing Test CXX_HAS_SSE4_2_2
-- Performing Test CXX_HAS_SSE4_2_2 - Success
-- Performing Test CXX_HAS_AVX_1
-- Performing Test CXX_HAS_AVX_1 - Failed
-- Performing Test CXX_HAS_AVX_2
-- Performing Test CXX_HAS_AVX_2 - Success
-- Performing Test CXX_HAS_AVX2_1
-- Performing Test CXX_HAS_AVX2_1 - Failed
-- Performing Test CXX_HAS_AVX2_2
-- Performing Test CXX_HAS_AVX2_2 - Success
-- SSE2 Found
-- SSE3 Found
-- AVX Found
-- AVX2 Found
-- Performing Test HAS_C11_ATOMICS
-- Performing Test HAS_C11_ATOMICS - Failed
-- Performing Test HAS_MSC_ATOMICS
-- Performing Test HAS_MSC_ATOMICS - Failed
-- Performing Test HAS_GCC_ATOMICS
-- Performing Test HAS_GCC_ATOMICS - Success
-- Atomics: using GCC intrinsics
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of void*
-- Check size of void* - done
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_gf_lp64: /usr/local/lib/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /usr/local/lib/libmkl_gnu_thread.so
--   Library mkl_core: /usr/local/lib/libmkl_core.so
-- Found OpenMP_C: -fopenmp (found version "4.0") 
-- Found OpenMP_CXX: -fopenmp (found version "4.0") 
--   Library gomp: -fopenmp
--   Library pthread: /usr/lib/x86_64-linux-gnu/libpthread.so
--   Library m: /usr/lib/x86_64-linux-gnu/libm.so
--   Library dl: /usr/lib/x86_64-linux-gnu/libdl.so
-- Looking for cblas_sgemm
-- Looking for cblas_sgemm - found
-- MKL library found
-- Performing Test BLAS_F2C_DOUBLE_WORKS
-- Performing Test BLAS_F2C_DOUBLE_WORKS - Failed
-- Performing Test BLAS_F2C_FLOAT_WORKS
-- Performing Test BLAS_F2C_FLOAT_WORKS - Success
-- Performing Test BLAS_USE_CBLAS_DOT
-- Performing Test BLAS_USE_CBLAS_DOT - Success
-- Found a library with BLAS API (mkl).
-- Found a library with LAPACK API (mkl).
-- Found CUDNN: /usr/local/cuda/include  
-- Found cuDNN: v7.1.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so.7)
disabling MKLDNN because NO_MKLDNN is set
CMake Deprecation Warning at src/ATen/CMakeLists.txt:7 (CMAKE_POLICY):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Using python found in /usr/local/anaconda2/bin/python
-- Performing Test SUPPORTS_STDCXX11
-- Performing Test SUPPORTS_STDCXX11 - Success
-- Performing Test SUPPORTS_MRTM
-- Performing Test SUPPORTS_MRTM - Success
-- Performing Test SUPPORTS_FLIFETIME
-- Performing Test SUPPORTS_FLIFETIME - Failed
-- Looking for clock_gettime in rt
-- Looking for clock_gettime in rt - found
-- Looking for mmap
-- Looking for mmap - found
-- Looking for shm_open
-- Looking for shm_open - found
-- Looking for shm_unlink
-- Looking for shm_unlink - found
-- Looking for malloc_usable_size
-- Looking for malloc_usable_size - found
-- Performing Test C_HAS_THREAD
-- Performing Test C_HAS_THREAD - Success
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
disable contrib because ATEN_NO_CONTRIB is set
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    MKLDNN_INCLUDE_DIR
    MKLDNN_LIBRARY
    MKLDNN_LIB_DIR
    NO_NNPACK


-- Build files have been written to: /usr/local/src/pytorch/aten/build

```

**Comment by ezyang** [comment] 2018-04-30 03:10
```
-- Checking for [mkl_gf_lp64 - mkl_gnu_thread - mkl_core - gomp - pthread - m - dl]
--   Library mkl_gf_lp64: /usr/local/lib/libmkl_gf_lp64.so
--   Library mkl_gnu_thread: /usr/local/lib/libmkl_gnu_thread.so
--   Library mkl_core: /usr/local/lib/libmkl_core.so
```

means it's picking the wrong library up.

**Comment by ezyang** [comment] 2018-04-30 03:53
It's using `find_library`, so `-DCMAKE_PREFIX_PATH` in the cmake invocation should do the trick. Or really any of the knobs in https://cmake.org/cmake/help/v3.11/command/find_library.html

**Comment by meder411** [comment] 2018-04-30 13:11
For anyone else struggling with this, I made the following change to `pytorch/aten/CMakeLists`

```
SET(CMAKE_PREFIX_PATH
  /usr/local/anaconda2
  ${CMAKE_PREFIX_PATH})
```

just below `project(ATen)`.

This is obviously a hack (it will be overwritten on future `git pull`s if that file is modified. Nevertheless, it gets the job done in the meantime.

**Comment by apaszke** [comment] 2018-04-30 13:26
@meder411 I think a simpler way might be to simply `export CMAKE_PREFIX_PATH=...` before running the script.

**Comment by meder411** [comment] 2018-04-30 14:40
That's a good point. That worked too. 

As an aside, it could be useful to add a mechanism in setup.py that looks for the ANACONDA_ROOT env variable and automatically adds it to the CMAKE_PREFIX_PATH for the build. This would smooth the build process for folks like me who are using conda to isolate and manage the python packages for their pytorch build, but want to be able to access regular developments to the source without waiting for the next conda pytorch release. From what I understand, this is not an uncommon scenario. Just a thought.

Thanks for the help!

**Comment by RunningLeon** [comment] 2018-05-28 13:59
@meder411 Thanks a lot. It worked for me.

**Comment by lxtGH** [comment] 2018-06-07 14:18
@meder411 Thanks a lot. Only your solution worked for me

**Comment by W4ngatang** [comment] 2018-06-21 20:54
I'm running into the same issue of building with the system MKL install instead of the conda version.

I tried `export CMAKE_PREFIX_PATH=...` (set to my conda installation) but it didn't work. In particular, in the build summary the variable was empty. I added the following to CMakeLists.txt (top level)
```
SET(CMAKE_PREFIX_PATH
  /usr/local/anaconda2
  ${CMAKE_PREFIX_PATH})
```
and the build summary seemed to register that `CMAKE_PREFIX_PATH` was being set, but it was still using the system MKL installation.

I then went into `cmake/Dependencies.cmake` and restricted `find_package(MKL ...)` to only search in `CMAKE_PREFIX_PATH`, but then it didn't find MKL at all.

I'm pretty stuck as to what I should do or what the issue is...any help would be hugely appreciated! Thanks!

**Comment by soumith** [comment] 2018-06-21 21:00
@W4ngatang do you have `mkl-include` in `conda list`?

**Comment by W4ngatang** [comment] 2018-06-21 21:19
yea, `mkl` and `mkl-include`, both v2018.0.3

**Comment by W4ngatang** [comment] 2018-06-25 05:43
Hey @soumith , just wanted to follow up on this and see if you had any advice?

**Comment by yaceben** [comment] 2018-10-29 00:46
Hey all,

On pytorch rc1 I had the same problem and I "resolved" it by using a ugly hack in cmake/Modules/FindMKL.cmake to force it to not find system local mkl libs

`SET(INTEL_COMPILER_DIR "/optometriste/intel" CACHE STRING
  "Root directory of the Intel Compiler Suite (contains ipp, mkl, etc.)")
SET(INTEL_MKL_DIR "/optometriste/intel/mkl" CACHE STRING
  "Root directory of the Intel MKL (standalone)")
SET(INTEL_MKL_SEQUENTIAL OFF CACHE BOOL
  "Force using the sequential (non threaded) libraries")`

Since I have the Intel compiler suite (v19, not compatible, without much hacking, with Cuda) it would always override the anaconda mkl libs... since I don't know much about cmake beyond breaking things I think maybe adding a simple bool switch like USE_SYSTEM_MKL would be a good idea ?

Cheers

**Comment by orionr** [comment] 2018-10-29 14:56
MKL builds have been changing recently, so cc @yinghai and @ezyang who might have some thoughts on this one.

**Comment by yaceben** [comment] 2018-10-29 15:23
> MKL builds have been changing recently, so cc @yinghai and @ezyang who might have some thoughts on this one. For example, #12170 will be landing sometime soon.

Thanks for the quick reply @orionr, I've (locally) made the following modification to FindMKL.cmake, seems to work for now. 

```cmake
# Intel Compiler Suite
IF (USE_SYS_MKL)
    SET(INTEL_COMPILER_DIR "/opt/intel" CACHE STRING
      "Root directory of the Intel Compiler Suite (contains ipp, mkl, etc.)")
    SET(INTEL_MKL_DIR "/opt/intel/mkl" CACHE STRING
      "Root directory of the Intel MKL (standalone)")
    SET(INTEL_MKL_SEQUENTIAL OFF CACHE BOOL
      "Force using the sequential (non threaded) libraries")
ENDIF(USE_SYS_MKL)
```

From what I gather from #12170 and discussions from @yinghai  and @ezyang  a unified FindMKLDNN or something should eventually be available. I'm rather new to pytorch and never had the courage to embark on any serious cmake adventure... so take my proposition with a grain of salt :)

Btw, just out of curiosity, is there a particular thread where I could find some information regarding the dropping of avx2 support for mkldnn ? I have a crappy quadro k2100m card in my laptop and for me the cpu is much faster than using cuda, so I was just wondering what the impact might be or what would be the best options for me when compiling from source? 

Cheers!

**Comment by yinghai** [comment] 2018-10-29 18:30
We don't need to add `-avx2` in mkldnn as kernels are jitted. The dependency of avx2 used to come from Ideep which is not necessary and iirc we have removed that dependency recently.

**Comment by yaceben** [comment] 2018-10-29 23:56
Thanks a lot for taking the time to answer @yinghai! 
Btw pulled the new master with separate mkl and all and my cheap trick still works to avoid multiple mkl redefinitions. Maybe IF NOT USE_PY_MKL would be clearer though...

**Comment by ngimel** [comment] 2020-10-30 20:19
Closing due to age.

**Closed by ngimel** 2020-10-30 20:19 UTC
Labels: medium priority (this tag is deprecated)
