### ISSUE TITLE
Incorrect Result: Writing to Non-unique Indices of a Tensor (on CUDA)

### ISSUE THREAD

**Issue by saryazdi** [pytorch/pytorch#33798] opened 2020-02-26 01:50 UTC
## 🐛 Bug

When adding a tensor to another tensor `c` at some **non-unique indices**, we end up with an incorrect tensor. The output is stochastic (demonstrated below). 

This bug is also there when writing to `c` (instead of adding); I.e., `c1[b] = a; c2[b] = a`.

## To Reproduce

```
import torch
import numpy as np

def torch_indexing_test(device):
    a = torch.arange(10000).float().to(device)
    b = torch.tensor(np.random.choice(100, 10000)).to(device).long()
    
    c1 = torch.zeros(100).to(device)
    c2 = torch.zeros(100).to(device)

    c1[b] += a
    c2[b] += a

    print(torch.max(c1-c2)) # should be zero

if __name__ == '__main__':
    torch_indexing_test(device="cpu")
    torch_indexing_test(device="cuda:0")

    # print output:
    # tensor(0.)
    # tensor(9307., device='cuda:0')
```

## Expected behavior

I would expect the printed output for the code when ran on both cpu and gpu to be `0` (meaning no stochasticity), but the output is non-zero for the gpu code.

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Microsoft Windows 10 Home
GCC version: (Rev5, Built by MSYS2 project) 5.3.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.105
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 441.22
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] libblas                   3.8.0                    14_mkl    conda-forge
[conda] libcblas                  3.8.0                    14_mkl    conda-forge
[conda] liblapack                 3.8.0                    14_mkl    conda-forge
[conda] liblapacke                3.8.0                    14_mkl    conda-forge
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.15           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] pytorch                   1.4.0           py3.7_cuda101_cudnn7_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch

**Comment by xwang233** [comment] 2020-02-26 02:53
It seems like the backend function [index_put](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_put_) and [index_add](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_add_) are called. They mentioned in the doc that "undefined behavior" or "nondeterministic behaviour" could happen if there are duplicated indices.

**Comment by ngimel** [comment] 2020-02-26 04:29
This behavior is consistent with numpy https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html#detailed-notes
```
For advanced assignments, there is in general no guarantee for the iteration order. This means that if an element is set more than once, it is not possible to predict the final result.
```
Closing as not a bug.

**Closed by ngimel** 2020-02-26 04:29 UTC

**Comment by saryazdi** [comment] 2020-02-26 16:07
@ngimel With numpy, eventhough you don't know what the iteration order is, if you run the experiment multiple times, it will give you the same result (no stochasticity) which is not the case for Torch with CUDA backend.

@xwang233 Then this is something the developers are already aware of for [index_add_](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_add_), but no mention of it for [index_put_](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_put_). Wouldn't it make sense to give a warning when someone is trying to use [index_add_](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_add_) or [index_put_](https://pytorch.org/docs/stable/tensors.html#torch.Tensor.index_put_) with duplicate indices?

**Comment by ngimel** [comment] 2020-02-26 17:21
numpy explicitly does not give guarantees that result will be the same. The fact that it is the same is a current implementation detail that can be broken and no one should rely on that. `index_put_` documentation already has a relevant language:
```
If accumulate is True, the elements in tensor are added to self. If accumulate is False, the behavior is undefined if indices contain duplicate elements.
```
