### ISSUE TITLE
Error with cuda9 docker build

### ISSUE THREAD

**Issue by achigeor** [pytorch/pytorch#4655] opened 2018-01-13 14:10 UTC
When building pytorch with docker with 
`docker build -t pytorch_cuda9 -f tools/docker/Dockerfile9 .`

I get the following error and the build stops:
`Step 10/14 : RUN git submodule update --init
 ---> Running in 34e6a586e55a
fatal: Not a git repository: /home/ubuntu/pytorch/.git/modules/torch/lib/gloo
Unable to find current revision in submodule path 'torch/lib/gloo'
The command '/bin/sh -c git submodule update --init' returned a non-zero code: 1
`

I cloned the latest master with `git clone --recursive https://github.com/pytorch/pytorch`
Ubuntu 16.04
Docker version 17.09.1-ce, build 19e2cf6

**Comment by ngimel** [comment] 2018-01-14 00:47
Duplicate of #3542

**Closed** 2018-01-14 12:13 UTC
