### ISSUE TITLE
Installing torch_nighly using pip shows error

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#72571] opened 2022-02-09 05:24 UTC
### 🐛 Describe the bug

When installing torch from https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html the console now includes this warning:

```
~: pip install --pre torch -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
warning: missing-index-doctype

× The package index page being used does not have a proper HTML doctype declaration.
╰─> Problematic URL: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

note: This is an issue with the page at the URL mentioned above.
hint: You might need to reach out to the owner of that package index, to get this fixed. See https://github.com/pypa/pip/issues/10825 for context.
```

### Versions

PyTorch version: 1.12.0.dev20220207
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.2 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.2
Libc version: N/A

Python version: 3.9.10 (main, Jan 15 2022, 11:40:53)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-12.2-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.4
[pip3] torch==1.12.0.dev20220207
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @malfet @seemethere

**Comment by postrational** [comment] 2022-02-09 12:26
Same issue when using `requirements.txt` file like this one:

```
--find-links https://download.pytorch.org/whl/torch_stable.html
torch==1.10.2+cu113
torchvision==0.11.3+cu113
torchaudio==0.10.2+cu113
```

**Comment by bdhirsh** [comment] 2022-02-10 02:27
tentatively marking as hi-pri due to noise when installing nightly

**Comment by seemethere** [comment] 2022-02-10 03:18
This is most likely a duplicate of https://github.com/pytorch/pytorch/issues/72045

**Comment by seemethere** [comment] 2022-02-10 03:19
Closing in favor of https://github.com/pytorch/pytorch/issues/72045 in order to keep the conversation in the same place

**Closed** 2022-02-10 03:21 UTC
Labels: high priority, releng, triaged
