### ISSUE TITLE
`torch.hub.load_state_dict_from_url` incompatible with new zip serialization

### ISSUE THREAD

**Issue by bernardomig** [pytorch/pytorch#43106] opened 2020-08-15 11:18 UTC
## 🐛 Bug

`torch.hub.load_state_dict_from_url` does not work with the new zip serialization with `torch.load`/`torch.save`. Loading from an url report the error:

```
RuntimeError: Only one file(not dir) is allowed in the zipfile
```

I think it is due to the fact that before this serialization change, the weigths could be compressed into a zip file (minimizing download time). Now, we serialize everything as a zip bundle, an this is the reason it fails.

## To Reproduce

```python
>>> from torch.hub import load_state_dict_from_url
>>> load_state_dict_from_url('https://files.deeplar.tk/ark-weights/drn_d_38-imagenet-39a7863b82.pt') # for example
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-c0cdf3d7c81f> in <module>
----> 1 load_state_dict_from_url('https://files.deeplar.tk/ark-weights/drn_d_38-imagenet-39a7863b82.pt')

~/miniconda3/envs/torch/lib/python3.8/site-packages/torch/hub.py in load_state_dict_from_url(url, model_dir, map_location, progress, check_hash, file_name)
    488             members = cached_zipfile.infolist()
    489             if len(members) != 1:
--> 490                 raise RuntimeError('Only one file(not dir) is allowed in the zipfile')
    491             cached_zipfile.extractall(model_dir)
    492             extraced_name = members[0].filename

RuntimeError: Only one file(not dir) is allowed in the zipfile
```

## Expected behavior

`load_state_dict_from_url` should load the files appropriately.

## Environment

 - PyTorch Version (e.g., 1.7):
 - OS (e.g., Linux): OpenSuse Leap
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2

cc @ezyang @gchanan @zou3519 @ailzhang

**Comment by colesbury** [comment] 2020-08-18 14:40
Marked as "high priority" because this looks like a regression to me. Previously (PyTorch 1.5), I could write:

```python
import torch
import torchvision
import os
torch.save(torchvision.models.resnet50(pretrained=True).state_dict(), 'resnet50.pt')
state_dict = torch.hub.load_state_dict_from_url(f'file://{os.getcwd()}/resnet50.pt')
```

(Or serve it via HTTP). Now (PyTorch 1.6+) it breaks with the error @bernardomig reported ("Only one file(not dir) is allowed in the zipfile").

It still breaks even if I use the `_use_new_zipfile_serialization` kwarg!

```python
torch.save(torchvision.models.resnet50(pretrained=True).state_dict(), 'resnet50.pt', _use_new_zipfile_serialization=False)
state_dict = torch.hub.load_state_dict_from_url(f'file://{os.getcwd()}/resnet50.pt')
```

**Comment by ezyang** [comment] 2020-08-18 22:12
cc @mruberry

**Comment by mruberry** [comment] 2020-08-18 22:19
@jamesr66a are you the zip file serialization person, now?

**Comment by gchanan** [comment] 2020-08-24 17:08
I believe this is a duplicate of: https://github.com/pytorch/pytorch/issues/42239 and already fixed in: https://github.com/pytorch/pytorch/pull/42333

**Closed by gchanan** 2020-08-24 17:08 UTC
Labels: high priority, module: hub, module: serialization, triage review, triaged
