### ISSUE TITLE
Ambiguous / inconsistent wheel links in torch_stable

### ISSUE THREAD

**Issue by mackrorysd** [pytorch/pytorch#53821] opened 2021-03-11 16:24 UTC
## 🐛 Bug

If you use `pip install -f https://download.pytorch.org/whl/torch_stable.html`, torch 1.8.0+cu102 cannot be installed. There's a cu102 directory, but no package inside it has +cu102 in the name (unlike many other versions). If I simply try to install 1.8.0, I'm actually getting the rocm version.

## To Reproduce

```
$ pip install torch==1.8.0+cu102 -f https://download.pytorch.org/whl/torch_stable.html # Fails
$ pip install torch==1.8.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html # Works
$ pip install torch==1.8.0       -f https://download.pytorch.org/whl/torch_stable.html # rocm4.0.1 variant
```
## Expected behavior

1.8.0+cu102 should be reliably resolvable to the wheel in the cu102 directory when using this index.

## Environment

PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Pop!_OS 20.04 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1660 Ti
Nvidia driver version: 460.39
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] torch                     1.4.0                    pypi_0    pypi
[conda] torchvision               0.5.0                    pypi_0    pypi

cc @ezyang @seemethere @malfet @walterddr

**Comment by mackrorysd** [comment] 2021-03-11 16:28
As a workaround, you can use that link and search by directory name to identify the version you want, copy the entire https:// URL, and pass that as the argument to pip.

**Comment by seemethere** [comment] 2021-03-11 17:29
We’ve merged in a change to make this more consistent but generally it’s not recommended to use the base index and to use the index that’s specific to the compute architecture you’re actually target.

If you’d like CUDA 10.2 binaries I’d suggest using:
```
pip install -f https://download.pytorch.org/whl/cu102/torch_stable.html torch
```

**Comment by mackrorysd** [comment] 2021-03-12 19:31
Thanks @seemethere - I'll replace my direct-links workaround with that approach.

Admittedly I'm no expert on Python packaging, but it does still seem a little odd to me that the CUDA version is an important attribute of the binary, but Pip itself can't be aware of the distinction.

**Comment by walterddr** [comment] 2021-03-12 21:15
related to (or duplicate of) #53709?

**Comment by malfet** [comment] 2021-03-16 15:13
Indeed it is, closing as duplicate of #53709

**Closed by malfet** 2021-03-16 15:13 UTC
Labels: module: binaries, triaged
