### ISSUE TITLE
Exporting the operator affine_grid_generator to ONNX opset version 13 is not supported

### ISSUE THREAD

**Issue by mengpengfei** [pytorch/pytorch#67320] opened 2021-10-27 06:11 UTC
pytorch had made me very exited.I would like to convert the model of pytorch to the model of onnx.I meet a problem now.

The  torch.onnx.export operator do not support the following operator:
F.affine_grid 
F.grid_sample

Our network of pytorch contains the operator "F.affine_grid " and the operator "F.grid_sample".When i convert the model of pytorch to the model of onnx, 
the following exception occurs.
RuntimeError: Exporting the operator affine_grid_generator to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

please help me.
please support it.
wait for your answer.

**Comment by BowenBao** [comment] 2021-11-10 22:19
Hi @mengpengfei , `grid_sample` is not officially supported by ONNX. It is supported in ONNX Runtime as contrib op. Feel free to checkout https://github.com/XiyinOSS/onnxruntime/blob/d8abe5de145145b6e8746d460c1b9ae8fd1903a5/tools/python/register_custom_ops_pytorch_exporter.py#L59 for support.

**Comment by avostryakov** [comment] 2022-01-02 17:27
grid_sample is officially supported by ONNX 1.11. It's not released yet but it was committed:
https://github.com/onnx/onnx/commit/bc4c4c48f664d4d08cabd30a57063588d7537408

**Comment by qqaatw** [comment] 2022-06-06 15:35
`grid_sample` looks supported by #76159

**Comment by BowenBao** [comment] 2022-11-14 23:34
Closing since `grid_sample` is supported, and `affine_grid_generator` is duplicate of #60727

**Closed by BowenBao** 2022-11-14 23:34 UTC
Labels: module: onnx, triaged, onnx-triaged
