### ISSUE TITLE
Export torch.stft as Conv1d till ONNX supports stft op

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#31317] opened 2019-12-16 15:40 UTC
As far as I understand, for the time being STFT [isn't natively supported by ONNX](https://github.com/onnx/onnx/blob/master/docs/Operators.md)
 
STFT can be exported as a Conv1d op with precomputed (windowed) Fourier basis: https://github.com/NVIDIA/mellotron/blob/master/stft.py

This is useful for tracking/exporting speech recongition models.

I've done a pure PyTorch version in https://github.com/vadimkantorov/convasr/blob/master/models.py#L315-L334 and it seems to work

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by vadimkantorov** [comment] 2020-08-07 17:25
My current workaround:

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

class STFT(nn.Module):
    def __init__(self, win_length, hop_length, stft_mode = None):
        self.win_length = win_length
        self.hop_length = hop_length
        self.nfft = 2**math.ceil(math.log2(self.win_length))
	self.freq_cutoff = self.nfft // 2 + 1
        if stft_mode == 'conv':
		fourier_basis = torch.rfft(torch.eye(self.nfft), signal_ndim = 1, onesided = False)
		forward_basis = fourier_basis[:self.freq_cutoff].permute(2, 0, 1).reshape(-1, 1, fourier_basis.shape[1])
		forward_basis = forward_basis * torch.as_tensor(
				librosa.util.pad_center(self.window, self.nfft), dtype = forward_basis.dtype
			)
		self.stft = nn.Conv1d(
			forward_basis.shape[1],
			forward_basis.shape[0],
			forward_basis.shape[2],
			bias = False,
			stride = self.hop_length
		).requires_grad_(False)
		self.stft.weight.copy_(forward_basis)
	else:
		self.stft = None

    def forward(self, signal):
        pad = self.freq_cutoff - 1
        padded_signal = F.pad(signal.unsqueeze(1), (pad, pad), mode = 'reflect').squeeze(1))
        real, imag = self.stft(padded_signal.unsqueeze(dim = 1)).split(self.freq_cutoff, dim = 1) if self.stft is not None else padded_signal.stft(self.nfft, hop_length = self.hop_length, win_length = self.win_length, window = self.window, center = False).unbind(dim = -1)
        return real, imag
		
```

**Comment by spandantiwari** [comment] 2020-08-07 22:59
Great @vadimkantorov.  Please consider submitting a PR for adding ONNX export support.

**Comment by thiagocrepaldi** [comment] 2022-02-14 22:06
@vadimkantorov https://github.com/pytorch/pytorch/pull/62412 works for you?

**Comment by garymm** [comment] 2022-03-01 21:20
STFT will hopefully be added to the next ONNX op set by https://github.com/onnx/onnx/pull/3741 or similar. We already have #65666 covering export of STFT so closing this in favor of that one.

Duplicate of #65666.

**Closed by garymm** 2022-03-01 21:20 UTC
Labels: module: onnx, triaged, enhancement
