### ISSUE TITLE
The doc of `stack()` should say `tuple` or `list` of tensors for `tensors` argument

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130686] opened 2024-07-13 23:41 UTC
### 🚀 The feature, motivation and pitch

[The doc](https://pytorch.org/docs/stable/generated/torch.stack.html) of `stack()` says the type of `tensors` argument is `sequence of Tensors` as shown below:

> - tensors (sequence of Tensors) – sequence of tensors to concatenate

But the sequence of tensors with `stack()` doesn't work while a tuple or list of tensors works as shown below:

```python
import torch

tensor1 = torch.tensor(2)
tensor2 = torch.tensor(7)
tensor3 = torch.tensor(4)

torch.stack(tensor1, tensor2, tensor3) # Error

torch.stack((tensor1, tensor2, tensor3))
torch.stack([tensor1, tensor2, tensor3])
torch.stack(tensors=(tensor1, tensor2, tensor3))
# tensor([2, 7, 4])
```

So, the doc should say `tuple` or `list` of tensors for `tensors` argument as shown below:

> - tensors (tuple or list of Tensors) – sequence of tensors to concatenate

cc @albanD

**Comment by albanD** [comment] 2024-07-16 20:37
Closing as duplicate of https://github.com/pytorch/pytorch/issues/130693

**Closed by albanD** 2024-07-16 20:37 UTC
Labels: triaged, module: python frontend
