### ISSUE TITLE
floor_divide has wrong result

### ISSUE THREAD

**Issue by tgsmdww** [pytorch/pytorch#44858] opened 2020-09-17 03:01 UTC
## To Reproduce

```
import torch
a = torch.IntTensor([1, -1])
b = torch.IntTensor([2, 2])
print(torch.floor_divide(a, b))
```
The result is 
```
tensor([0, 0], dtype=torch.int32)
```

Use numpy:
`np.floor_divide(-1,2)` 
and the result is `-1`

## Expected behavior
![image](https://user-images.githubusercontent.com/17045617/93416703-e366a200-f8d8-11ea-805e-d21b1573c2c1.png)
```
tensor([0, -1], dtype=torch.int32)
```

## Environment

Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 专业版
GCC version: (x86_64-win32-seh-rev0, Built by MinGW-W64 project) 5.4.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.7 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] numpy==1.18.3
[pip3] torch==1.5.0+cpu
[pip3] torchtext==0.6.0
[pip3] torchvision==0.6.0+cpu
[conda] Could not collect

**Comment by mruberry** [comment] 2020-09-17 03:47
You are correct and we are fixing this. This issue is a dupe of https://github.com/pytorch/pytorch/issues/43874.

Thank you for reporting this, @tgsmdww.

**Closed by mruberry** 2020-09-17 03:47 UTC
