### ISSUE TITLE
Windows build does not work with Visual Studio generator with recent Windows AMI

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#24386] opened 2019-08-15 03:36 UTC
A sufficient workaround is `CMAKE_GENERATOR=Ninja` and we'll be using this to work around the problem in the caffe2 build (which historically used the Visual Studio generator). However this VS generator really ought to work. This bug is to not forget to look into it.

cc @peterjc123

**Comment by peterjc123** [comment] 2019-08-18 01:59
An interesting fact here is when you try to build it for the first time, it will pass. But it will consistently fail when trying to rebuild it again, even if cleaning the project won't help.

**Comment by Blackhex** [comment] 2022-12-06 09:37
@peterjc123 I believe this is deprecated and can be closed, right?

**Comment by peterjc123** [comment] 2022-12-06 12:11
@Blackhex I don't know. Haven't tried this recently.

**Comment by peterjc123** [comment] 2022-12-06 12:33
@Blackhex https://github.com/pytorch/pytorch/blob/master/scripts/build_windows.bat The script is still there but since it is configured through Jenkins, I don't know exactly the full script to reproduce the issue.

**Comment by peterjc123** [comment] 2022-12-06 12:37
@Blackhex https://caffe2.ai/docs/getting-started.html?platform=windows&configuration=compile This link might help.

**Comment by Blackhex** [comment] 2022-12-06 12:48
I see, thank you. Then we should change the title and description of the issue that it's about making [https://github.com/pytorch/pytorch/blob/master/scripts/build_windows.bat](https://github.com/pytorch/pytorch/blob/master/scripts/build_windows.bat) working/up-to-date in general and not about that windows AWS AMIs have some issues. Note that there is related issue updating AWS AMIs to VS 2022 pytorch/test-infra#1175.

**Comment by peterjc123** [comment] 2022-12-06 12:56
@Blackhex Yes. You'll need an internal discussion with the FB employees about whether we need standalone Caffe2 or not.

**Comment by mantaionut** [comment] 2023-04-20 06:47
Closing this ticket since Caffe2 is no longer supported on Windows.

**Closed by mantaionut** 2023-04-20 06:47 UTC
Labels: module: windows, triaged
