### ISSUE TITLE
Windows CI intermittent error: C2993: 'Derived': illegal type for non-type template parameter '__formal

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25393] opened 2019-08-29 14:25 UTC
Kind of similar to #25389

Sometimes our Eigen build fails this way:

```
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(366): error C2993: 'Derived': illegal type for non-type template parameter '__formal'
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(366): error C2065: 'RhsType': undeclared identifier
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(366): error C2923: 'std::_Select<__formal>::_Apply': 'RhsType' is not a valid template type argument for parameter '<unnamed-symbol>'
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(366): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(366): error C2144: syntax error: 'unknown-type' should be preceded by ')'
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(366): error C2144: syntax error: 'unknown-type' should be preceded by ';'
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(367): error C2062: type 'bool' unexpected
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(369): error C2059: syntax error: ')'
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(371): error C2143: syntax error: missing ';' before '{'
C:\Jenkins\workspace\caffe2-builds\py2-cuda9.0-cudnn7-windows-build\third_party\eigen\Eigen\src/LU/InverseImpl.h(371): error C2447: '{': missing function header (old-style formal list?)
```

It doesn't seem to reliably repro. 

cc @ezyang @gchanan @zou3519 @seemethere @peterjc123

**Comment by ezyang** [comment] 2019-09-03 17:57
I got some sort of similar-ish error persistently on a test branch:

```
14:06:51 L1Cost.cu
14:06:51 C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): error C2993: 'T': illegal type for non-type template parameter '__formal'
14:06:51 C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): note: see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_construct2_impl_has_member<T,Result(Arg1,Arg2)>' being compiled
14:06:51 C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): error C2065: 't': undeclared identifier
14:06:51 C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): error C2923: 'std::_Select<__formal>::_Apply': 't' is not a valid template type argument for parameter '<unnamed-symbol>'
14:06:51 C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): error C2062: type 'unknown-type' unexpected
14:06:51 -- Removing C:/Jenkins/workspace/caffe2-builds/py2-cuda9.0-cudnn7-windows-build/build/caffe2/CMakeFiles/torch.dir/__/aten/src/THCUNN/./torch_generated_L1Cost.cu.obj
```

**Comment by ezyang** [comment] 2019-09-03 18:16
Not that persistently; a PR stacked on the failing one succeeded. So there is something nondeterministic going on here.

**Comment by smessmer** [comment] 2019-09-03 18:48
another instance: CI on https://github.com/pytorch/pytorch/pull/23888

**Comment by peterjc123** [comment] 2019-09-06 11:52
Looks like an NVCC bug. The workground is protecting eigen headers with `#ifndef __CUDACC__.`  Can we extract some basic code example and compile it against NVCC?

**Comment by peterjc123** [comment] 2019-12-12 07:22
Another one in https://app.circleci.com/jobs/github/pytorch/pytorch/3919969.
```
unique_ops.cu
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/unique_by_key.h(211): error C2993: 'KeyInputIt': illegal type for non-type template parameter '__formal'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/unique_by_key.h(246): note: see reference to class template instantiation 'thrust::cuda_cub::__unique_by_key::UniqueByKeyAgent<KeyInputIt,ValInputIt,KeyOutputIt,ValOutputIt,BinaryPred,Size,NumSelectedOutIt>::PtxPlan<Arch>' being compiled
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/unique_by_key.h(589): note: see reference to class template instantiation 'thrust::cuda_cub::__unique_by_key::UniqueByKeyAgent<KeyInputIt,ValInputIt,KeyOutputIt,ValOutputIt,BinaryPred,Size,NumSelectedOutIt>' being compiled
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/unique_by_key.h(211): error C2065: 'IS_FIRST_TILE': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/system/cuda/detail/unique_by_key.h(211): error C2993: 'KeyInputIt': illegal type for non-type template parameter '__formal'
```

**Comment by gottbrath** [comment] 2019-12-16 21:54
Can you try with 10.2?

**Comment by gottbrath** [comment] 2019-12-16 22:48
Mingbo, can you put general information on the issue you are seeing here in this issue?

**Comment by gottbrath** [comment] 2019-12-16 23:00
latest  word on this is 

from mingbo:
"from what I can tell, it's a flaky one.  might depend on which VS version. I hit the problem before and problem fixed (at least seem so) after upgrading VS 2019 latest version" and "the same error showed up once last week, and re-run the job finished without problem."

**Comment by jmlundberg** [comment] 2020-02-04 09:07
Hi. Did anyone have this issue persistently, ie that a rebuild did not "fix" it? We've had this issue in another (closed source) project. Exposing cuda to less includes (such as boost) seems to help but is not predictable.

**Comment by ezyang** [comment] 2020-02-04 21:07
It's never been persistent for us, but this is mostly from our Windows CI builds where we blow everything away and rebuild from scratch, which may help.

**Comment by peterjc123** [comment] 2020-02-10 03:27
Other occurrence in the forum: https://discuss.pytorch.org/t/how-do-i-get-my-older-gpu-that-supports-cuda-to-work-with-pytorch-1-4/69005/13. It seems to be fixed by `set MAX_JOBS=1`, which implies this may be a race condition in reading the include files or generating the intermediate source files.

**Comment by peterjc123** [comment] 2020-02-24 17:37
I was able to reproduce the issue with a more verbose output with https://github.com/pytorch/pytorch/pull/33693: https://app.circleci.com/jobs/github/pytorch/pytorch/3919969. And then I inspected the variables carefully and found out that the VC env is activated twice. We should really avoid that.

**Comment by ezyang** [comment] 2020-02-25 03:24
You are SO COOL!!!

**Comment by peterjc123** [comment] 2020-02-25 06:34
I tried to build from scratch several times with this PR and could not reproduce the issue anymore. Let's assume it's fixed.

**Comment by peterjc123** [comment] 2020-02-26 04:10
Looks like it was not resolved. https://circleci.com/gh/pytorch/pytorch/4599162?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by peterjc123** [comment] 2020-03-04 04:45
Another occurrence: https://app.circleci.com/jobs/github/pytorch/pytorch/4683459
```
THCTensorSort.cu
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust/detail/allocator/allocator_traits.inl(35): error C2993: 'T': illegal type for non-type template parameter '__formal'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust/detail/allocator/allocator_traits.inl(35): note: see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_allocate_with_hint_impl_has_member<T,Result(Arg)>' being compiled
C:\Users\circleci\project\c10/core/MemoryFormat.h(55): note: see reference to class template instantiation 'c10::ArrayRef<__int64>' being compiled
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust/detail/allocator/allocator_traits.inl(35): error C2065: 't': undeclared identifier
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust/detail/allocator/allocator_traits.inl(35): error C2923: 'std::_Select<__formal>::_Apply': 't' is not a valid template type argument for parameter '<unnamed-symbol>'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include\thrust/detail/allocator/allocator_traits.inl(35): error C2062: type 'unknown-type' unexpected
-- Removing C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensorSort.cu.obj
C:/Jenkins/Miniconda3/Library/bin/cmake.exe -E remove C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensorSort.cu.obj
CMake Error at torch_cuda_generated_THCTensorSort.cu.obj.Debug.cmake:281 (message):
  Error generating file
  C:/Users/circleci/project/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/./torch_cuda_generated_THCTensorSort.cu.obj

```
This time it seems to claim the error is around the usage of `ArrayRef`.

**Comment by malfet** [comment] 2020-03-14 02:15
This sounds like a good old multiple-instances-of-nvcc-write-to-the-same-temp-file
One can invoke `nvcc -v` to see all temporary filenames it creates.
I guess on windows they are more likely to collide with each other than on linux.
One solution to the problem would be to invoke nvcc sequentially. Another is to tweak environment (there must be something similar to TMPDIR on Windows, mustn't it?)

**Comment by peterjc123** [comment] 2020-03-14 02:26
Yes, they are called TMP and TEMP.

**Comment by peterjc123** [comment] 2020-03-14 02:28
Is there any example of the latter method on Unix systems?

**Comment by peterjc123** [comment] 2020-03-14 08:47
I've written a utility `randomtemp`. https://github.com/peterjc123/randomtemp  Hopefully it can be used to resolve this problem if that's the case.

**Comment by peterjc123** [comment] 2020-03-18 02:30
New occurrence after the previous fix:
https://circleci.com/api/v1.1/project/github/pytorch/pytorch/4848808/output/105/0?file=true&allocation-id=5e715778abc2b72bcca749e6-0-build%2F6B231C7B

**Comment by ak-source** [comment] 2020-03-23 16:53
seems related to https://github.com/thrust/thrust/issues/1030

**Comment by peterjc123** [comment] 2020-03-23 16:59
If this is the case, maybe we could apply `/Zc:__cplusplus` to fix that.

**Comment by ak-source** [comment] 2020-03-25 07:30
> 
> 
> If this is the case, maybe we could apply `/Zc:__cplusplus` to fix that.

unfortunately, this introduces another thrust problem (e.g. CompareNEKernel.cu):
`D:/programs64/cuda101/include\thrust/detail/complex/catrig.h(607): error: no instance of function template "thrust::atanh" matches the argument list
            argument types are: (double)
`
with problematic include chain ATen/native/cuda/zmath.cuh -> thrust/complex.h -> thrust/detail/complex/catrig.h (has __cplusplus conditions) -> thrust/detail/complex/c99math.h where "using ::atanh" is omitted for MSVC.

Patching c99math.h (or even thrust\detail\config\cpp_dialect.h without using /Zc:__cplusplus) seems to work for me, but I'm not sure what's the best way to fix this within pytorch tree and whether c++ dialect is the only problem here.

**Comment by peterjc123** [comment] 2020-03-25 07:33
@ak-source Thanks for the investigation. BTW, could you please share with us how did you patch c99math.h?

**Comment by ak-source** [comment] 2020-03-25 10:31
Disregard that, still got same unreproducible C2993 error with /Zc:__cplusplus. Earlier, I had "build" directory reproducibly failing (at THCTensorSortShort.cu), and hardcoding c++17 in thrust\detail\config\cpp_dialect.h fixed that. But looks like it is just a symptom of some inconsistence in environment/flags (across nvcc stages maybe?)

> BTW, could you please share with us how did you patch c99math.h?
just added "using ::atanh"

**Comment by peterjc123** [comment] 2020-03-25 10:59
Yeah, maybe. I am considering to add a wrapper to retry the build a few times.

**Comment by peterjc123** [comment] 2020-04-26 08:46
I can now stably reproduce a related error by passing in `--Werror cross-execution-space-call`.
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3944): error: calling a __host__ function("std::_Idl_distance<long long *, long long *> ") from a __host__ __device__ function("std::move<long long *, long long *> ") is not allowed

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.25.28610\include\xutility(3945): error: calling a __host__ function("std::_Move_unchecked<long long *, long long *> ") from a __host__ __device__ function("std::move<long long *, long long *> ") is not allowed

```

**Comment by peterjc123** [comment] 2020-04-26 09:36
By commenting some part of the code, I find the code that causes the previous error.
```cpp
at::TensorIterator iter;
iter.add_output(input_grad);
iter.add_output(weight_grad_collector);
iter.add_input(input);
iter.add_input(grad_out);
iter.build();
```

**Comment by peterjc123** [comment] 2020-04-26 13:12
Well, I figured out the reason. It seems that `move` and `forward` are implicitly marked as `__HOST__` and `__DEVICE__`. This behavior can be disabled by adding `--no-host-device-move-forward`.

**Comment by ezyang** [comment] 2020-04-27 15:11
Nice work!

**Comment by leezu** [comment] 2020-05-09 03:52
Seems to be a nvcc bug https://github.com/thrust/thrust/issues/1090#issuecomment-626080333

**Comment by peterjc123** [comment] 2020-05-09 04:14
@leezu Thanks for reminding. I have commented there.

**Comment by allisonvacanti** [comment] 2020-05-11 17:49
This is indeed an nvcc bug. There is no known workaround at the moment, but the next release of the CUDA toolkit will contain a fix.

Ref thrust/thrust#1090.

**Comment by cloudhan** [comment] 2020-06-13 10:21
Met this problem:
```
[1385/1760] Building NVCC (Device) object caffe2/CMakeFiles/torch_cu...rc/THC/generated/torch_cuda_generated_THCTensorMathReduceByte.cu.obj
FAILED: caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/torch_cuda_generated_THCTensorMathReduceByte.cu.obj
cmd.exe /C "cd /D D:\pytorch\build\caffe2\CMakeFiles\torch_cuda.dir\__\aten\src\THC\generated && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E make_directory D:/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/. && "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -D verbose:BOOL=OFF -D build_configuration:STRING=RelWithDebInfo -D generated_file:STRING=D:/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMathReduceByte.cu.obj -D generated_cubin_file:STRING=D:/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMathReduceByte.cu.obj.cubin.txt -P D:/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/torch_cuda_generated_THCTensorMathReduceByte.cu.obj.RelWithDebInfo.cmake"
THCTensorMathReduceByte.cu
THCTensorMathReduceByte.cu
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\thrust/detail/allocator/allocator_traits.inl(193): error C2993: 'T': is not a valid type for non-type template parameter '__formal'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\thrust/detail/allocator/allocator_traits.inl(193): note: see reference to class template instantiation 'thrust::detail::allocator_traits_detail::has_member_max_size_impl_has_member<T,Result(void)>' being compiled
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\thrust/detail/allocator/allocator_traits.inl(193): error C2065: 't': undeclared identifier
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\thrust/detail/allocator/allocator_traits.inl(193): error C2923: 'std::_Select<__formal>::_Apply': 't' is not a valid template type argument for parameter '<unnamed-symbol>'
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\include\thrust/detail/allocator/allocator_traits.inl(193): error C2062: type 'unknown-type' unexpected
CMake Error at torch_cuda_generated_THCTensorMathReduceByte.cu.obj.RelWithDebInfo.cmake:281 (message):
  Error generating file
  D:/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorMathReduceByte.cu.obj
```

**Comment by peterjc123** [comment] 2020-06-13 10:39
@cloudhan Just try a few times.

**Comment by allisonvacanti** [comment] 2020-06-13 14:27
The CUDA TK 11.0 RC is now available: https://developer.nvidia.com/cuda-downloads 

This issue has been fixed in that version of nvcc.

**Comment by peterjc123** [comment] 2020-06-13 14:36
> The CUDA TK 11.0 RC is now available: https://developer.nvidia.com/cuda-downloads
> 
> This issue has been fixed in that version of nvcc.

Thanks for the info. Actually, our release binaries rely on the cudatoolkit package in anaconda cloud. So we won't be able to publish the binaries with CUDA 11 now. I'm just curious whether that is maintained by Nvidia? Another question, any plan to backport the changes to exisiting CUDA versions (e.g. cuda 10.1, cuda 10.2)?

**Comment by allisonvacanti** [comment] 2020-06-22 18:31
I don't have that information unfortunately -- it'd be best to contact the maintainer of that package and see when they plan to update.

I'm not aware of any plans to backport this fix.

**Comment by nbcsm** [comment] 2020-07-30 07:14
@maxluk

**Comment by leezu** [comment] 2021-03-09 15:26
@mstfbl this is a cuda bug. Please see above discussion and upgrade to cuda 11.

**Comment by mstfbl** [comment] 2021-03-11 01:18
@leezu I fixed the error by installing sscache for use with cuda 10.1 and cuda 10.2, as done here. https://github.com/pytorch/builder/blob/993e8b275e313641796db8a0b2869d5f3dd13828/windows/build_pytorch.bat#L98-L124

**Comment by leezu** [comment] 2021-03-11 18:00
@mstfbl it's an intermittent error and the probability of occurrence varies depending on your system. So it's not really fixed, but you may have found a way to reduce the occurrence in your system, which may be sufficient in your case :)

**Comment by peterbell10** [comment] 2021-05-10 23:51
Another instance, this time inside protobuf: 
```
roi_align_op.cu
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2993: 'T': is not a valid type for non-type template parameter '__formal'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(459): note: see reference to class template instantiation 'google::protobuf::Arena::InternalHelper<T>' being compiled
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2065: 'Second': undeclared identifier
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2923: 'std::_Select<__formal>::_Apply': 'Second' is not a valid template type argument for parameter '<unnamed-symbol>'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2144: syntax error: 'unknown-type' should be preceded by ')'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2144: syntax error: 'unknown-type' should be preceded by ';'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2238: unexpected token(s) preceding ';'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2059: syntax error: ')'
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2988: unrecognizable template declaration/definition
C:/Users/circleci/project/third_party/protobuf/src\google/protobuf/arena.h(427): error C2059: syntax error: '<end Parse>'
```
https://app.circleci.com/pipelines/github/pytorch/pytorch/317648/workflows/504abdce-7887-47a1-bf6a-de417da17503/jobs/13229319

Running `nvcc` with `--verbose --keep` I found the syntax error is introduced by `cudafe++` which is the cuda compiler front end. `cudafe++` operates on the output from the compiler's pre-processor and that output barely even changed to trigger the build error, only line number metadata and some extra whitespace was changed in the pre-processed output. 

Here is the diff of the two inputs, one of which failed and the other didn't:
```
$ diff nvcc-output/roi_align_op.cpp4.ii nvcc-output-2/roi_align_op.cpp4.ii
353964d353963
< #line 229 "C:/Users/circleci/project\\c10/macros/Macros.h"
353966c353965,353966
< #line 231 "C:/Users/circleci/project\\c10/macros/Macros.h"
---
> 
> 
```

And the corresponding change in the output:
```
$ diff nvcc-output/roi_align_op.compute_75.cudafe1.cpp nvcc-output-2/roi_align_op.compute_75.cudafe1.cpp
124779c124779
< template< class U> static char ArenaConstructable(const typename std::_Select< T> ::template _Apply< U, Second> ::InternalArenaConstructable_ *); 
---
> template< class U> static char ArenaConstructable(const typename U::InternalArenaConstructable_ *); 
162181c162181
< namespace _GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_c6fef629 { }; using namespace ::at::_GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_c6fef629; namespace _GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_c6fef629 { 
---
> namespace _GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_6d8ec415 { }; using namespace ::at::_GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_6d8ec415; namespace _GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_6d8ec415 { 
201406c201406
< #define _NV_ANON_NAMESPACE _GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_c6fef629
---
> #define _NV_ANON_NAMESPACE _GLOBAL__N__31_roi_align_op_compute_75_cpp1_ii_6d8ec415
```

This failure reproduced reliably on the CI machine. Running nvcc manually multiple times, it always fails or passes given the same inputs. I think it's a deterministic failure, but is annoyingly sensitive to any changes in the input file whatsoever.

**Comment by ngimel** [comment] 2022-02-07 19:43
closing due to age

**Closed by ngimel** 2022-02-07 19:43 UTC
Labels: high priority, module: build, module: windows, module: ci, triaged, module: flaky-tests

**Comment by ezyang** [comment] 2022-02-10 15:56
Wait, do we think this is fixed? It's not clear to me it is...

**Comment by seemethere** [comment] 2022-02-10 16:41
I think this was related to CUDA 10.2 builds on windows which we don't actually support anymore so it is probably safe to keep closed.
