### ISSUE TITLE
Linalg.eigh has a much faster computation speed in Numpy than in pytorch

### ISSUE THREAD

**Issue by mcmingchang** [pytorch/pytorch#121603] opened 2024-03-11 01:47 UTC
### 🐛 Describe the bug

start = time.time()
_, eigenvectors = np.linalg.eigh(cov_matrix)
print(round(time.time() - start, 5))  # 0.006s

cov_matrix2 = torch.from_numpy(cov_matrix).cuda()
start = time.time()
_, eigenvectors = torch.linalg.eigh(cov_matrix2)
print(round(time.time() - start, 5))  # 0.04s

### Versions

torch.__version__    '2.1.2+cu118'

**Comment by mcmingchang** [comment] 2024-03-11 01:49
cov_matrix.shape   (6241, 3, 3)

**Comment by vadimkantorov** [comment] 2024-03-11 09:05
Maybe related: https://github.com/pytorch/pytorch/issues/121482#issuecomment-1986096169

**Comment by albanD** [comment] 2024-03-11 13:55
Closing as a duplicate of https://github.com/pytorch/pytorch/issues/121482#issuecomment-1986096169 since it is also considering 3x3 matrices.

**Closed by albanD** 2024-03-11 13:55 UTC
