### ISSUE TITLE
`model.copy()` is broken

### ISSUE THREAD

**Issue by bwasti** [pytorch/pytorch#29170] opened 2019-11-05 01:27 UTC
## 🐛 Bug

Calling a scripted model.copy() is broken.  Throws an error here:

```
RuntimeError: class '__torch__.torch.nn.modules.module.___torch_mangle_5.Module' already defined. (register_type at caffe2/torch/csrc/jit/script/compilation_unit.h:167)
```

## To Reproduce

1. create a scripted model
2. call `model.copy()`

## Expected behavior

Expected a copy to be made.

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): linus
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): setup.py
 - Python version: 3.7

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by vadimkantorov** [comment] 2019-11-05 22:32
Also it seems that the copy method is not documented: https://pytorch.org/docs/master/search.html?q=copy&check_keywords=yes&area=default seems to not show any method named `copy()`

**Comment by zou3519** [comment] 2019-11-06 15:11
I don't think `model.copy()` exists or is supposed to exist on nn modules. This issue seems to be JIT-specific so I am tossing it onto the JIT queue.

**Comment by suo** [comment] 2019-11-06 18:31
Assigning to @ZolotukhinM as I believe he implemented `copy()` (feel free to bounce back to me if I'm wrong about that). Can you take a look?

**Comment by ZolotukhinM** [comment] 2019-11-06 19:42
I think @jerryzh168  fixed that in #29269

**Comment by jerryzh168** [comment] 2019-11-06 22:46
@bwasti can you provide an example? I can't reproduce with random scripted models

**Comment by jerryzh168** [comment] 2019-11-07 23:49
@bwasti my PR is landed, could you verify if this is resolved?

**Comment by jerryzh168** [comment] 2019-12-03 00:52
I'll close for now, feel free to re-open if the problem persists

**Closed by jerryzh168** 2019-12-03 00:52 UTC
Labels: high priority, jit, triaged
