### ISSUE TITLE
Flaky test test_cos_scalar_cpu TestAutogradDeviceTypeCPU on MacOS

### ISSUE THREAD

**Issue by dzhulgakov** [pytorch/pytorch#32502] opened 2020-01-22 19:55 UTC
Example job: https://circleci.com/gh/pytorch/pytorch/4317436?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

```
Jan 22 11:32:13 ERROR [0.015s]: test_cos_scalar_cpu (__main__.TestAutogradDeviceTypeCPU)
Jan 22 11:32:13 ----------------------------------------------------------------------
Jan 22 11:32:13 Traceback (most recent call last):
Jan 22 11:32:13   File "/Users/distiller/project/test/common_device_type.py", line 180, in instantiated_test
Jan 22 11:32:13     return test(self, device_arg)
Jan 22 11:32:13   File "test_autograd.py", line 4011, in do_test
Jan 22 11:32:13     check(name)
Jan 22 11:32:13   File "test_autograd.py", line 3936, in check
Jan 22 11:32:13     output_variable, (self_variable,) + args_variable)
Jan 22 11:32:13   File "test_autograd.py", line 3866, in run_grad_and_gradgrad_checks
Jan 22 11:32:13     test_case.assertTrue(gradgradcheck(apply_method, input_variables, gen_non_contig_grad_outputs=True))
Jan 22 11:32:13   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 407, in gradgradcheck
Jan 22 11:32:13     nondet_tol=nondet_tol)
Jan 22 11:32:13   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 297, in gradcheck
Jan 22 11:32:13     'The tolerance for nondeterminism was {}.'.format(nondet_tol))
Jan 22 11:32:13   File "/Users/distiller/workspace/miniconda3/lib/python3.7/site-packages/torch/autograd/gradcheck.py", line 229, in fail_test
Jan 22 11:32:13     raise RuntimeError(msg)
Jan 22 11:32:13 RuntimeError: Backward is not reentrant, i.e., running backward with same input and grad_output multiple times gives different values, although analytical gradient matches numerical gradient. The tolerance for nondeterminism was 0.0.
```

For some reason happens only on MacOS and is not obviously related to any recent PR

cc @ezyang @gchanan @zou3519 @albanD

**Comment by kostmo** [comment] 2020-01-24 17:54
The first `master` commit that manifested this issue was e37a24b.  Since then, the failure rate is 54%  (19/35).  It therefore seems likely that the cause was introduced in either e37a24b or one of the few commits immediately preceding.

**Comment by albanD** [comment] 2020-01-24 21:10
Given that the failure happens only in the very specific case:
- only on ci macos machine (cannot repro locally)
- only fails for `cos`, not all other operations
- only fails during the double backward check (the regular backward check runs just before and is always fine)

Connecting to a CI machine, I verified that the difference is of `1e-17` so it is floating point precision level.

**Comment by ezyang** [comment] 2020-01-27 15:03
The only plausible PR within the time window which could have caused this is https://github.com/pytorch/pytorch/issues/32502

**Comment by ezyang** [comment] 2020-01-27 19:14
https://github.com/pytorch/pytorch/pull/32650

**Comment by ezyang** [comment] 2020-01-27 20:00
On the OS X CircleCI machines this script is a reliable-ish reproducer (fails 50% of the time)

```
import torch    
import torch.autograd.gradcheck
                
input = torch.tensor(0.046130461896669264221237938273, requires_grad=True, dtype=torch.double)
print(torch.autograd.gradgradcheck(torch.cos, input)) 
```

**Comment by albanD** [comment] 2020-01-28 00:48
Deterministic repro is:
```python
inp1 = torch.tensor([0.0461304618966692642212379382730.046,1e300,0.0461304618966692642212379382730.046,0.0461304618966692642212379382730.046], dtype=torch.double)
inp2 = torch.tensor([0.0461304618966692642212379382730.046,0.0461304618966692642212379382730.046,0.0461304618966692642212379382730.046,0.0461304618966692642212379382730.046], dtype=torch.double)

v1 = inp1.cos()[0]
v2 = inp2.cos()[0]

print(v1 - v2)
```

This is fixed by initializing the content of `tmp_values` to fixed values [here](https://github.com/pytorch/pytorch/blob/39987de9e4a74dc64148422ba6ac6cad8875b386/aten/src/ATen/cpu/vec256/vec256_double.h#L64-L68). The problem being that the vectorized cos does not return the same results depending on the other values in the vector.

**Comment by ezyang** [comment] 2020-01-28 01:42
From personal correspondence: apparently this is a problem with sleef?

**Comment by albanD** [comment] 2020-01-28 01:56
Yes, the value returned by sleef for these vectors depends on the values of the other entries in the vector.
@colesbury what is your suggestion to properly fix this?

**Comment by ezyang** [comment] 2020-01-28 03:23
@albanD So, at least for determinism, if we pad out the vector with zeros until it is full, we should end up with the same result from sleef (even if it is one ULP of difference for bigger tensors).

**Comment by colesbury** [comment] 2020-01-28 03:24
Yeah, the problem is because we load the vector register from the stack which can be filled with garbage:

**Comment by ezyang** [comment] 2020-01-28 15:02
@albanD and I agreed that we should just zero initialize `tmp_values` in this case. Since the `count != size()` case is only used for the ragged end it's fine if we add a few more instructions here, since it's not in the tight loop.

**Comment by jgong5** [comment] 2022-10-22 00:36
> Can this issue be reopened please? The same problem exists with the VSX code: `loadu` uses uninitialized memory

I also visited the current implementation of in avx256/512. I guess a masked load/store implementation would be more efficient here? cc @sanchitintel 
https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/cpu/vec/vec512/vec512_float.h#L101

**Closed** 2022-12-02 18:20 UTC
Labels: high priority, triaged, module: flaky-tests
