### ISSUE TITLE
Matrix multiplication returns wrong result when middle dimension is 0

### ISSUE THREAD

**Issue by shapovalov** [pytorch/pytorch#31421] opened 2019-12-18 14:09 UTC
## 🐛 Bug

This may be a marginal use case. I expect the result of multiplying N×0 by 0×M matrices be `zeros(N, M)` as a particular case of matrix multiplication definition. However, `bmm` and `matmul` neither fail nor return zero tensor. Most likely, memory initialisation is skipped in that case.
Let’s discuss whether we consider it a legitimate input, and either fix the result, or raise an exception.

## To Reproduce

Unfortunately, this is a floating bug that depends on the state of the system.
```
t1 = torch.ones((3,2,0)).cuda(0)
t2 = torch.ones((3,0,3)).cuda(0)
res_bmm = torch.bmm(t1, t2)
res_matmul = torch.matmul(t1, t2)
```

## Expected behavior

Either:
* `res_bmm` and `res_matmul` should always be `zeros(3,2,3)`, regardless of the initial memory state,
or:
* exception raised.

## Environment

 - PyTorch Version (e.g., 1.0): 1.3.0+cu100
 - OS (e.g., Linux): linux
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.6
 - CUDA/cuDNN version: 10.0.130
 - GPU models and configuration: Quadro GP100

cc @ezyang @gchanan @zou3519 @csarofeen @ptrblck @ngimel

**Comment by albanD** [comment] 2019-12-18 19:52
I cannot reproduce this on cpu. Where it returns Tensors full of `0`s.
What is the error you see on cuda?

**Comment by ngimel** [comment] 2019-12-18 19:55
I cannot reproduce it even on cuda, even when I make it use initialized memory
```In [1]: import torch                                                                                                             

In [2]: a=torch.randn(1024*1024, device="cuda")                                                                                  

In [3]: del a                                                                                                                    

In [4]: torch.cuda.memory_allocated()                                                                                  
Out[4]: 0

In [5]: torch.cuda.memory_cached()                                                                                     
Out[5]: 20971520

In [6]: t1=torch.ones((3,2,0)).cuda(0)                                                                                 

In [7]: t2 = torch.ones((3,0,3)).cuda(0)                                                                               

In [8]: torch.cuda.memory_allocated()                                                                                  
Out[8]: 0

In [9]: torch.cuda.memory_cached()                                                                                     
Out[9]: 20971520

In [10]: res_bmm = torch.bmm(t1, t2)                                                                                   

In [11]: torch.cuda.memory_cached()                                                                                    
Out[11]: 23068672

In [12]: res_bmm                                                                                                       
Out[12]: 
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0')
```

**Comment by gchanan** [comment] 2019-12-18 20:53
Also would be helpful to show the output that doesn't have 0s.

**Comment by shapovalov** [comment] 2019-12-20 15:45
Thanks for the comments everyone!
I’ve tried to reproduce it standalone by allocating/freeing memory in the loop but failed as well. My hope was that someone here would know the code and could quickly check whether the memory is always initialised in `bmm`.

The actual line in my code is 
```
delta = torch.bmm(alpha[:, None, :], basis[:, 1:, :])
```

This is what I get:
```
(Pdb) alpha.size()
torch.Size([10, 0])
(Pdb) basis.size()
torch.Size([10, 1, 43200])
(Pdb) delta
tensor([[[-4.9469e-04,  3.1077e-02, -1.2956e-02,  ..., -5.8799e-03,
           3.2257e-03,  5.6009e-03]],

        [[ 6.5665e-03,  5.5072e-03,  9.1196e-03,  ...,  1.5373e-02,
          -3.3161e-02, -2.4766e-02]],

        [[ 3.9871e-02, -2.9234e-02,  1.2655e-02,  ...,  5.0681e-03,
           1.0401e-02, -1.0340e-03]],

        ...,

        [[ 2.0880e-11, -3.6763e-11, -4.3727e-11,  ...,  1.5785e-10,
           1.2219e-10,  5.8353e-11]],

        [[ 3.3565e-11, -1.8010e-11, -2.1607e-11,  ...,  1.4607e-10,
           1.1281e-10,  5.2787e-11]],

        [[ 2.2027e-11, -3.6393e-11, -3.4783e-11,  ...,  1.4274e-10,
           1.0893e-10,  5.0855e-11]]], device='cuda:0', grad_fn=<BmmBackward>)
```

One peculiarity I noticed is that it alternates between zero and non-zero results when running the same line several times.

Let me know if you have any ideas how to narrow it down.

**Comment by ngimel** [comment] 2019-12-26 07:01
Indeed, with the sizes in the previous snippet I can reproduce it. 
```
In [38]: a=torch.randn(10,1,0,device="cuda")                                                                                                    

In [39]: b=torch.randn(10,0,43200, device="cuda")                                                                                               

In [40]: out = torch.randn(10,1,43200).cuda()                                                                                                   

In [41]: torch.bmm(a,b,out=out)                                                                                                                 
Out[41]: 
tensor([[[ 0.1343, -1.8573, -0.4454,  ..., -0.0880, -0.1325,  1.4109]],

        [[ 0.6763, -1.6208,  0.3440,  ...,  0.5403, -1.1779,  0.3506]],

        [[ 0.0802, -0.6159, -0.3801,  ...,  0.9672,  0.4577, -0.7112]],

        ...,

        [[ 0.9164,  2.2342, -2.0074,  ..., -0.6363, -0.9746,  0.4483]],

        [[ 1.1386,  0.9839,  1.8808,  ..., -1.5350,  1.0081,  0.3232]],

        [[ 0.3560, -0.1623, -1.0822,  ..., -0.0443, -0.0282,  0.2387]]],
       device='cuda:0')

```

**Comment by ngimel** [comment] 2019-12-26 07:43
Looks like cublas bug. With the repro script and .ltrace.conf from this gist (put .ltrace.conf in the root directory) 
https://gist.github.com/ngimel/780f09d431906a522c4df2da3cd16fbd
I'm getting reasonable looking arguments for cublas call, yet output seems not to be overwritten:
```
(pytorch) ngimel@xxxxxxx:~/playground$ ltrace -f -e  'cublasSgemmStridedBatched'  python bmm.py
[pid 23443] --- Called exec() ---
[pid 23444] --- Called exec() ---
[pid 23444] +++ exited (status 0) +++
[pid 23443] --- SIGCHLD (Child exited) ---
[pid 23443] +++ exited (status 0) +++
[pid 23439] --- SIGCHLD (Child exited) ---
[pid 23439] libtorch_cuda.so->cublasSgemmStridedBatched(0x562bbf906850, 0, 0, 43200, 1, 0, 1.000000, 0, 43200, 43200, 0, 1, 1, 0.000000, 0x7ff76a400000, 43200, 43200, 10) = 0
tensor([[[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        ...,

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.]]], device='cuda:0')
```
We could implement a workaround zeroing the output for this case, actual cublas bugfixes take a long time. 
cc @ptrblck

**Comment by albanD** [comment] 2019-12-26 16:49
Is the issue linked to the fact that we have both 0-dimensional and 0-stride?

**Comment by ngimel** [comment] 2019-12-26 18:31
Cublas just does not handle this edge case correctly. In fact, regular matrix multiply with the same sizes produces expected zero result, so the strides are fine.

**Comment by shapovalov** [comment] 2019-12-31 13:48
Thanks for investigating it @ngimel ! I agree memset’ting  with 0s makes sense as a temporary solution.

**Comment by ptrblck** [comment] 2020-01-13 19:22
@shapovalov This issue should have been fixed in cublas shipping with CUDA10.1.
Could you please install the latest PyTorch with CUDA10.1 and retry your script?

**Comment by seemethere** [comment] 2020-01-30 16:15
I believe this should be resolved now:

```
❯ python test.py
===== [ res_bmm ] =====
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0')

===== [ res_matmul ] =====
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]], device='cuda:0')
```

<details>
<summary>`test.py`</summary>

```python
import torch

t1 = torch.ones((3,2,0)).cuda(0)
t2 = torch.ones((3,0,3)).cuda(0)
res_bmm = torch.bmm(t1, t2)
res_matmul = torch.matmul(t1, t2)

print("===== [ res_bmm ] =====")
print(res_bmm)
print()
print("===== [ res_matmul ] =====")
print(res_matmul)
```

</details>

Pytorch version: 1.5.0.dev20200129
CUDA Version: 10.1

**Comment by ezyang** [comment] 2020-01-31 14:47
Great, thank you!

**Closed by ezyang** 2020-01-31 14:47 UTC
Labels: high priority, module: cublas, module: cuda, module: operators, topic: dependency bug, triaged
