### ISSUE TITLE
Provide download of releases with all submodules

### ISSUE THREAD

**Issue by Flamefire** [pytorch/pytorch#62708] opened 2021-08-04 07:30 UTC
## 🚀 Feature

Add tarballs to Github releases which contain the current source code and all submodules, i.e. the result of a recursive clone/checkout bundles as a tarball.

## Motivation

The current Github releases contain only the default github tarballs, which is basically a shallow checkout of the repository. This means it is basically useless for building PyTorch from source.
It would be a lot easier for consumers/sys admins if there was a single, tagged and checksummable tarball for each release which one can simply download and unpack.
This works very well for all github repos by default, unless they contain submodules.

The common approach followed by others already is to provide explicit tarballs which include the submodules in the releases.
This can be done in a fully automated way using github actions.

Bonus: It avoids issues such as https://github.com/pytorch/pytorch/issues/62657 as people can just download that one file.

## Pitch

- Add github action which runs on tag or release (depending on your workflow)
- Recursively checkout the tag for that release (make sure it is a tag and not a branch, but the GHA checkout action will do that already)
- Create a tarball and add it to the release

Example of such a CD action is e.g. at https://github.com/Return-To-The-Roots/s25client/blob/a24429ffa9426557304144d523729013da3799f4/.github/workflows/release.yml which creates a release automatically on each tag push.

Final note: Please name the tarballs in a quasi standard way `%(name)s-%(version)s.tar.gz`, e.g. `pytorch-1.9.0.tar.gz`. Lot's of other software does this and it simplifies maintainers jobs :)

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @seemethere @malfet @walterddr

**Comment by malfet** [comment] 2021-08-05 15:18
By the way, I've added functionality to include submodule source code in sdist package in https://github.com/pytorch/pytorch/pull/52908 we just need to upload them to github

**Comment by malfet** [comment] 2021-08-05 19:00
Also, sounds like a duplicate of https://github.com/pytorch/pytorch/issues/13586, isn't it?

**Comment by Flamefire** [comment] 2021-08-06 07:08
Yes pretty much. Thanks for pointing that out.
TBH while the sdist would be great to have on pypi (I guess, because PyPi can have source archives and IIRC `pip install` will pick that if no matching whl is present, so not fully sure if you really want that...) I think we'd be more comfortable with an untouched source release. I.e. literally the result of a recursive clone packed into a tarball and added to the releases with a nice, generic name including the name and version (see above)

I even think that is much easier to achieve, isn't it?
If you close this in favor of #13586 please link in the hint with GHA automated tarball creation for releases so that won't be missing for new releases :)

**Comment by seemethere** [comment] 2021-08-09 17:06
We'd love to have help to build this out if you have some spare cycles @Flamefire!

**Comment by ezyang** [comment] 2021-08-09 23:59
@seemethere if you want to enlist OSS help need to have enough design to say how they can test and deploy whatever they do; Flamefire doesn't have rights to upload binaries :P

**Comment by Flamefire** [comment] 2021-08-10 08:52
I took the liberty and got my hands dirty. See https://github.com/pytorch/pytorch/pull/63022 and tell me what you think ;)

**Closed** 2021-08-11 19:48 UTC
Labels: high priority, module: binaries, releng, triaged
