### ISSUE TITLE
`multilabel_margin_loss` returns different results with the same input twice in cuda

### ISSUE THREAD

**Issue by upupyy** [pytorch/pytorch#77952] opened 2022-05-20 07:56 UTC
### 🐛 Describe the bug

`multilabel_margin_loss` has different results for input with and without grad in cuda

```python
import torch
input_tensor = torch.tensor([[0.2332, 0.1621, 0.2437, 0.1001]], dtype=torch.float32)
target_tensor = torch.tensor([[5, 5, 6, 2]], dtype=torch.int64)

reduction = "mean"

input = input_tensor.clone().detach().to('cuda')
target = target_tensor.clone().detach().to('cuda')
res1 = torch.nn.functional.multilabel_margin_loss(input, target, reduction=reduction, )

input = input_tensor.clone().detach().to('cuda')
target = target_tensor.clone().detach().to('cuda')
res2 = torch.nn.functional.multilabel_margin_loss(input, target, reduction=reduction, )

input = input_tensor.clone().detach().to('cuda')
target = target_tensor.clone().detach().to('cuda')
res3 = torch.nn.functional.multilabel_margin_loss(input, target, reduction=reduction, )

print(res1) # tensor(3.3126, device='cuda:0')
print(res2) # tensor(1.0626, device='cuda:0')
print(res3) # tensor(1.0626, device='cuda:0')
```

### Versions

pytorch: 1.11.0
cudakit: 11.3
GPU 0: NVIDIA GeForce RTX 3080 Ti

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @ngimel

**Comment by albanD** [comment] 2022-06-01 16:25
Hi,

The indices in your target are out of bound. So this is expected as you read out-of-bound memory.
Closing as duplicate of https://github.com/pytorch/pytorch/issues/73176

**Closed by albanD** 2022-06-01 16:25 UTC
Labels: module: nn, module: cuda, triaged
