### ISSUE TITLE
magic_number = pickle_module.load(f, **pickle_load_args) TypeError: file must have 'read', 'readinto' and 'readline' attributes

### ISSUE THREAD

**Issue by rahulvsharan** [pytorch/pytorch#33232] opened 2020-02-12 09:39 UTC
## 🐛 Bug

2020-02-12 01:34:22,801 copying C:\Users\1025289\AppData\Local\Temp\2\tmp5d0w7nip to cache at C:\Users\1025289\.flair\models\en-pos-ontonotes-fast-v0.4.pt
2020-02-12 01:34:22,973 removing temp file C:\Users\1025289\AppData\Local\Temp\2\tmp5d0w7nip
2020-02-12 01:34:22,988 loading file C:\Users\1025289\.flair\models\en-pos-ontonotes-fast-v0.4.pt
Traceback (most recent call last):
  File "fmain.py", line 16, in <module>
    main()
  File "fmain.py", line 4, in main
    intent_obj = GET_INTENT()
  File "C:\Users\1025289\Desktop\intent\get_intent.py", line 10, in __init__
    super().__init__(b_preprocess_query=b_preprocess_query)
  File "C:\Users\1025289\Desktop\intent\model_flair.py", line 24, in __init__
    self._load_flair_model(flair_model)
  File "C:\Users\1025289\Desktop\intent\model_flair.py", line 30, in _load_flair_model
    self._seq_tag = SequenceTagger.load(flair_model)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python38\lib\site-packages\flair\nn.py", line 86, in load
    state = torch.load(f, map_location=flair.device)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 529, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "C:\Users\1025289\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\serialization.py", line 692, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
TypeError: file must have 'read', 'readinto' and 'readline' attributes

## Environment
 - PyTorch Version (e.g., 1.0):1.4
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Python version: 3.81 x64
 - CUDA/cuDNN version: No
 - GPU models and configuration:No
 - Any other relevant information:

**Comment by peterjc123** [comment] 2020-02-12 09:46
Duplicate of #32289.

**Closed by peterjc123** 2020-02-12 09:46 UTC
