### ISSUE TITLE
[export] nn.LSTM fails to torch.export due to unimplemented operator

### ISSUE THREAD

**Issue by johnzlli** [pytorch/pytorch#123089] opened 2024-04-01 11:04 UTC
### 🐛 Describe the bug

The following model, containing a single nn.LSTM layer cannot be exported:

**Code**
```python
import torch
import torch.nn as nn
from torch.export import export

class Model(nn.Module):
    def __init__(self):
        super().__init__()
        self.rnn = nn.LSTM(800, 800)

    def forward(self, x):
        x = self.rnn(x)
        return x

mod = Model()
mod.eval()
mod.cuda()
exported = export(mod, (torch.rand(20, 800, 800).cuda(),))
```

**log**
![image](https://github.com/pytorch/pytorch/assets/38726413/d6685176-02b0-4068-a7b4-389cd6823401)

### Versions

torch == 2.2.0a0+81ea7a4
```[tasklist]
### Tasks
```

cc @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by janeyx99** [comment] 2024-04-01 15:59
Thanks for the report! By the way, could you paste either the raw logs in a code format or take a bigger screenshot? The current picture is too small to read and when clicked on says the private content cannot be found.

**Comment by angelayi** [comment] 2024-04-01 16:18
Duplicate of https://github.com/pytorch/pytorch/issues/120626

**Closed** 2024-04-08 16:56 UTC
Labels: oncall: export

**Comment by justinchuby** [comment] 2025-09-05 21:01
```py
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, p_rnn_weight_ih_l0: "f32[3200, 800]", p_rnn_weight_hh_l0: "f32[3200, 800]", p_rnn_bias_ih_l0: "f32[3200]", p_rnn_bias_hh_l0: "f32[3200]", x: "f32[20, 800, 800]"):
             # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/rnn.py:1089 in forward, code: h_zeros = torch.zeros(
            zeros: "f32[1, 800, 800]" = torch.ops.aten.zeros.default([1, 800, 800], dtype = torch.float32, device = device(type='cpu'), pin_memory = False)
            
             # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/rnn.py:1096 in forward, code: c_zeros = torch.zeros(
            zeros_1: "f32[1, 800, 800]" = torch.ops.aten.zeros.default([1, 800, 800], dtype = torch.float32, device = device(type='cpu'), pin_memory = False)
            
             # File: /home/justinchu/anaconda3/envs/onnx/lib/python3.13/site-packages/torch/nn/modules/rnn.py:1127 in forward, code: result = _VF.lstm(
            lstm = torch.ops.aten.lstm.input(x, [zeros, zeros_1], [p_rnn_weight_ih_l0, p_rnn_weight_hh_l0, p_rnn_bias_ih_l0, p_rnn_bias_hh_l0], True, 1, 0.0, False, False, False);  x = zeros = zeros_1 = p_rnn_weight_ih_l0 = p_rnn_weight_hh_l0 = p_rnn_bias_ih_l0 = p_rnn_bias_hh_l0 = None
            getitem: "f32[20, 800, 800]" = lstm[0]
            getitem_1: "f32[1, 1, 800, 800]" = lstm[1]
            getitem_2: "f32[1, 1, 800, 800]" = lstm[2];  lstm = None
            return (getitem, getitem_1, getitem_2)
            
Graph signature: 
    # inputs
    p_rnn_weight_ih_l0: PARAMETER target='rnn.weight_ih_l0'
    p_rnn_weight_hh_l0: PARAMETER target='rnn.weight_hh_l0'
    p_rnn_bias_ih_l0: PARAMETER target='rnn.bias_ih_l0'
    p_rnn_bias_hh_l0: PARAMETER target='rnn.bias_hh_l0'
    x: USER_INPUT
    
    # outputs
    getitem: USER_OUTPUT
    getitem_1: USER_OUTPUT
    getitem_2: USER_OUTPUT
    
Range constraints: {}
```
