### ISSUE TITLE
Docstring for Adam optimizer argument `differentiable` is missing.

### ISSUE THREAD

**Issue by alper111** [pytorch/pytorch#90690] opened 2022-12-12 09:47 UTC
The docstring for the `differentiable` argument is missing in the current documentation (https://pytorch.org/docs/stable/generated/torch.optim.Adam.html).

It can be put here: https://github.com/pytorch/pytorch/blob/2e0ce24890874ea5a6136e71d5d61308bee02a7e/torch/optim/adam.py#L104-L111. 

cc @svekars @carljparker @vincentqb @jbschlosser @albanD @janeyx99

**Comment by janeyx99** [comment] 2022-12-12 15:37
Closing as dupe of #90467

**Closed by janeyx99** 2022-12-12 15:37 UTC
Labels: module: docs, module: optimizer, triaged
