### ISSUE TITLE
IndexError while trying to save torchscript

### ISSUE THREAD

**Issue by hhsecond** [pytorch/pytorch#18126] opened 2019-03-18 11:45 UTC
## 🐛 Bug

I have a python script to save a mixture of both traced and  scripted `torchscript` as `.pt`. But on execution, it's thrown index error. I wrapped the `@script` functions into a ScriptModule class and everything is working fine now.

## To Reproduce

1. I am using a CharRNN model saved using `torch.jit.trace` -> code is available [here](https://colab.research.google.com/drive/1PquhW_ziRAEvRwPEDd-gE55-6r6L9Pde)
2. Trace model is then loaded into this script and mixing up with `@script` functions
```python
import torch
import string

debug = True
device = 'cpu' if not torch.cuda.is_available() else 'cuda'
traced_generator = torch.jit.load('CharRNN_model.pt', device)


@torch.jit.script
def post_processing(output):
    output_dist = output.squeeze().div(0.8).exp()
    prob = torch.multinomial(output_dist, 1)[0]
    return prob


@torch.jit.script
def seq_loop(inputs, hidden, prediction_seq_length: int):
    out = []
    i = 0
    while i < prediction_seq_length:
        output, hidden = traced_generator(inputs, hidden)
        inputs = post_processing(output)
        out.append(inputs)
        i += 1
    return out

torch.jit.save(seq_loop, 'pytorch_issue.pt')
```
3. Executing above script will throw `IndexError: _Map_base::at`

## Expected behavior

The .pt file should be saved. Because I wrapped the above code within a `ScriptModule` class and that's working
```python
import torch
import string

debug = True
device = 'cpu' if not torch.cuda.is_available() else 'cuda'
traced_generator = torch.jit.load('CharRNN_model.pt', device)

def str2int(string_data):
    return [all_characters.index(c) for c in string_data]

def int2str(int_data):
    return ''.join([all_characters[i] for i in int_data])

class ScriptModuleWrapper(torch.jit.ScriptModule):
    def __init__(self):
        super().__init__()
        self.traced_generator = traced_generator

    @torch.jit.script_method
    def forward(self, inputs, hidden):    
        out = []
        i = 0
        n_layers = 2
        hidden_size = 300
        prediction_seq_length = 200
        while i < prediction_seq_length:
            output, hidden = self.traced_generator(inputs, hidden)
            inputs = self.post_processing(output)
            out.append(inputs)
            i += 1
        return out

    @torch.jit.script_method
    def post_processing(self, output):
        output_dist = output.squeeze().div(0.8).exp()
        prob = torch.multinomial(output_dist, 1)[0]
        return prob

filename = 'CharRNN_pipeline.pt'
print('Saving pipeline to {}'.format(filename))
ScriptModuleWrapper().save(filename)
```
## Environment

PyTorch version: 1.0.0.dev20190307
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.10
GCC version: (Ubuntu 8.2.0-7ubuntu1) 8.2.0
CMake version: version 3.12.1

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] torch==1.0.0.dev20190307
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.1                      144  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch-nightly-cpu       1.0.0.dev20190307     py3.7_cpu_0    pytorch

**Comment by wanchaol** [comment] 2019-03-18 18:17
Thanks for raising the issue, @driazati can you take a look on it?

**Comment by driazati** [comment] 2019-03-20 00:27
Seems like there's a problem when tracing a module with `Parameter`s, they aren't making it to the Python Printer so some map lookup fails:

https://github.com/pytorch/pytorch/blob/9d455ac2fe83bf52dfcf940759c2c26ed1fd1cd5/torch/csrc/jit/passes/python_print.cpp#L1128

Minimal repro
```python
class M(nn.Module):
    def __init__(self):
        super(M, self).__init__()
        self.encoder = nn.Linear(2, 2)

    def forward(self, x):
        return self.encoder(x)

p = torch.ones(2, 2)
traced = torch.jit.trace(M(), (p,))

@torch.jit.script
def seq_loop(x):
    return traced(x)

torch.jit.save(seq_loop, 'pytorch_issue.pt')
```

**Comment by ezyang** [comment] 2019-03-20 02:01
https://github.com/pytorch/pytorch/pull/18139 might be related

**Comment by driazati** [comment] 2019-04-22 18:42
I can't seem to reproduce this on master, could you try again with nightly? 1 caveat, stateful modules have to be submodules of a `ScriptModule`, so pretty much that means you have to change `seq_loop` into a subclass of `torch.jit.ScriptModule` and assign `self.traced = traced` in the `__init__`

**Comment by driazati** [comment] 2019-04-22 22:51
Closing this since I can't reproduce and we fixed some similar errors recently, but feel free to re-open if you're still getting this error

**Closed by driazati** 2019-04-22 22:51 UTC
Labels: jit
