### ISSUE TITLE
RuntimeError: derivative for aten::_scaled_dot_product_flash_attention_backward is not implemented

### ISSUE THREAD

**Issue by thwgithub** [pytorch/pytorch#116348] opened 2023-12-23 03:24 UTC
### 🐛 Describe the bug

with torch.backends.cuda.sdp_kernel(enable_math=True):
    out = F.scaled_dot_product_attention(query, key, value)
g = grad(out, query, grad_outputs=torch.ones_like(out), create_graph=True)[0].reshape(32, -1)
g_norm = g.norm(p=2, dim=1) ** 2
gp = g_norm.mean()
gp.backward()

RuntimeError: derivative for aten::_scaled_dot_product_flash_attention_backward is not implemented

### Versions

I found the scaled_dot_product_attention() can't implemented the backwark() . The complete codes are as follows.

import torch
import torch.nn.functional as F
from torch.autograd import grad
query = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda",requires_grad=True)
key = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda",requires_grad=True)
value = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda",requires_grad=True)
with torch.backends.cuda.sdp_kernel(enable_math=True):
    out = F.scaled_dot_product_attention(query, key, value)
g = grad(out, query, grad_outputs=torch.ones_like(out), create_graph=True)[0].reshape(32, -1)
g_norm = g.norm(p=2, dim=1) ** 2
gp = g_norm.mean()
gp.backward()

RuntimeError: derivative for aten::_scaled_dot_product_flash_attention_backward is not implemented

cc @jbschlosser @bhosmer @cpuhrsch @erichan1 @drisspg @mikaylagawarecki

**Comment by mikaylagawarecki** [comment] 2024-01-02 15:24
Closing as this is a duplicate of https://github.com/pytorch/pytorch/issues/116350, please direct discussion there

**Closed by mikaylagawarecki** 2024-01-02 15:24 UTC
Labels: oncall: transformer/mha
