### ISSUE TITLE
nn.MultiHeadAttention should be able to return attention weights for each head.

### ISSUE THREAD

**Issue by ironcadiz** [pytorch/pytorch#34537] opened 2020-03-10 13:18 UTC
## Motivation
Currently when using the `nn.MultiHeadAttention` layer, the `attn_output_weights` consists of an average of the attention weights of each head, therefore the original weights are inaccessible. That makes analysis like the one made in this [paper](https://arxiv.org/abs/1906.04341v1) very difficult.

## Pitch
When the `nn.MultiHeadAttention` forward is called with `need_weights=True` (and maybe a second parameter like `nead_attn_heads=True`),  `attn_output_weights` should be a tensor of size `[N,num_heads,L,S]`,with the weights of each head, instead of the average of size `[N,L,S]` (following the notation in the [docs](https://pytorch.org/docs/stable/nn.html#multiheadattention))

## Additional context
A small discussion about this subject with a potential solution was made [here](https://discuss.pytorch.org/t/getting-nn-multiheadattention-attention-weights-for-each-head/72195)

If you guys agree, I'll gladly make a PR.

**Comment by gchanan** [comment] 2020-03-10 19:21
@zhangguanheng66 @cpuhrsch is this on the MultiHeadedAttention roadmap?

**Comment by zhangguanheng66** [comment] 2020-03-10 19:38
We are decomposing multiheadattention func soon (in-projection/out-projection layers plus scale-dot product layer). Then, you will be able to obtain the attention weights before averaging.

**Comment by zhangguanheng66** [comment] 2020-03-17 19:08
Landing one of the two PRs should be able to solve the issue.
https://github.com/pytorch/pytorch/pull/34719
https://github.com/pytorch/pytorch/issues/34573

**Comment by rbracco** [comment] 2021-11-09 15:43
Any update on this? It would be great to be able to access the individual heads for analysis as requested here and in #47583

**Comment by ngimel** [comment] 2021-12-15 17:27
Closing as duplicate of #47583

**Closed by ngimel** 2021-12-15 17:27 UTC
Labels: module: nn, triaged, enhancement, oncall: transformer/mha
