### ISSUE TITLE
Segmentation fault (core dumped) on LSTMCell on pytorch

### ISSUE THREAD

**Issue by saitarslanboun** [pytorch/pytorch#5132] opened 2018-02-08 10:58 UTC
I want to use LSTMCell for sequential data. I have defined it as follows:

    self.LSTM1 = nn.LSTMCell(embed_size * 2, hidden_size)

Afterwards, I wanted to use it for my sequential data.

    for time_step in range( x.size( 1 ) ):

            # Feed in x_t one at a time
            x_t = x[ :, time_step, : ]
            x_t = x_t.unsqueeze( 1 )

            #h_t, states = self.LSTM( x_t, states )
            hidden = Variable(torch.zeros(1, x.size(1), self.hidden_size))
            cell = Variable(torch.zeros(x.size(1), 1, self.hidden_size))
            hidden = hidden.cuda()
            cell = cell.cuda()
            #(hidden, cell) = (None, None)
            for a in range(len(x_t)):
                hidden, cell = self.LSTM1(x_t[a], (hidden, cell))
                #print cell.cpu()
                #atten_weight = self.adaptive([x_t[a]], [h_t1], )
                sys.exit()

Why I get **Segmentation fault (core dumped)** error on `hidden, cell = self.LSTM1(x_t[a], (hidden, cell))` line?

How I can fix this error?

Thanks,

**Comment by dasguptar** [comment] 2018-02-08 14:52
Hi @saitarslanboun 
Some sizes are missing in the snippet you provided, so I cannot exactly replicate it and get the segfault error. However, I think I can see a few potential mistakes in your code. I think you might be mistaking the input specifications for `LSTM` and `LSTMCell`. Note that by default, `LSTM` takes as input a tensor of shape `(seq_len, batch, input_size)`, whereas `LSTMCell` takes as input a tensor of shape `(batch, input_size)`.

In your code snippet, you seem to have `x` where `x.size(1)` specifies the number of timesteps. If I assume that `x` is then of the form `(batch_size, seq_len, input_size)`, the first thing we might want to do is to transpose the first 2 dimensions, by `x.transpose_(0,1)`, to make things `seq_len` first, or `batch_size` second. This is only because recurrent layers like to have the timesteps in the first dimension.

Now, ideally, with a tensor `x` in such a shape, you do not need to use either a for loop, or a `LSTMCell`, and can simply pass it to a `LSTM` module to get the desired output. You can find the documentation for LSTM [here](http://pytorch.org/docs/master/nn.html#torch.nn.LSTM). Your entire code will look like this:
```
# create lstmcell module
lstm = nn.LSTM(embed_size * 2, hidden_size)

# transpose from batch first to batch second for recurrent layers
x = x.transpose(0, 1).contiguous()
output, (h_t, c_t) = lstm(x)
```

Now let us assume that for some reason, you must use a `LSTMCell` instead of a `LSTM`. In this case, if you go through the documentation for `LSTMCell` [here](http://pytorch.org/docs/master/nn.html#torch.nn.LSTMCell), you will see that the input needs to be passed 1 time step at a time. So, assuming your `x` is of the form `(batch_size, seq_len, input_size)`, your entire code will look like this:
```
# create lstmcell module
lstm = nn.LSTMCell(embed_size * 2, hidden_size)

# initialize h,c outside for loop
h_t = Variable(x.data.new().resize_as_(x[:, 0, :].data).zero_())
c_t = Variable(x.data.new().resize_as_(x[:, 0, :].data).zero_())

# loop over time steps
for time_step in range(x.size(1)):
    x_t = x[:, time_step, :]
    (h_t, c_t) = lstm(x_t, (h_t, c_t))
```

From what I have understood from your snippet, there are a few potential mistakes:
- Wrong sizes to initialize `hidden` and `cell`, which should be `(batch_size, input_size)` for `LSTMCell`
- Two nested for loops, first over time steps, and second possibly over batch size, which is wrong

Let me know if this helps you and/or if there are any details in your question that I have misunderstood.

**Comment by ezyang** [comment] 2018-02-08 21:52
Even if the usage is wrong, it shouldn't segfault.

What version of PyTorch are you running, can you post a full reproducing script and can you gdb your program and post the backtrace that occurs during segfault?

**Comment by saitarslanboun** [comment] 2018-02-13 11:46
Thank you @dasguptar, it is amazing explanation. It works :)

**Comment by zou3519** [comment] 2020-08-11 14:25
I'm closing this issue under the assumption that we've fixed the segfault (because it's been two years since the last activity on this thread and if it still existed a user would have probably ran into it and submitted a new issue). Please feel free to reopen this if that is not the case.

**Closed by zou3519** 2020-08-11 14:25 UTC
