### ISSUE TITLE
Got "RuntimeError: y.get_desc().is_nhwc() INTERNAL ASSERT FAILED"  while applying conv2d over a transposed tensor

### ISSUE THREAD

**Issue by bincard** [pytorch/pytorch#80837] opened 2022-07-04 12:37 UTC
### 🐛 Describe the bug

I got this error on pytorch version 1.12.0.
The code that can reproduce the error:

```python
import torch
import torch.nn as nn


conv = nn.Conv2d(
    1,
    128,
    kernel_size=(5, 2),
    stride=(2, 1),
    padding=(0, 1),
    dilation=(1, 1),
    groups=1,
    bias=True,
    padding_mode='zeros')

t = torch.rand([1, 2, 321, 201, 1])
t = torch.transpose(t, 1, 4)
t2 = t[..., 0]
r = conv(t2)
```
The error message:
```
Traceback (most recent call last):
  File "/Users/bin.xue/Codes/iot/maasAEC/xxx.py", line 19, in <module>
    r = conv(t2)
  File "/Users/bin.xue/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/Users/bin.xue/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/Users/bin.xue/.pyenv/versions/3.7.3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 454, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: y.get_desc().is_nhwc() INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mkldnn/Conv.cpp":143, please report a bug to PyTorch. 

```

### Versions

PyTorch version: 1.12.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.20.2
Libc version: N/A

Python version: 3.7.3 (default, May 29 2019, 18:19:34)  [Clang 10.0.1 (clang-1001.0.46.4)] (64-bit runtime)
Python platform: Darwin-21.5.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.0
[pip3] torchaudio==0.12.0
[conda] Could not collect

cc @gujinghui @PenghuiCheng @XiaobingSuper @jianyuh @VitalyFedyunin

**Comment by mingfeima** [comment] 2022-07-28 23:09
Root cause is this ambiguity between is contiguous.

the given input has shape `[1, 1, 321, 201]` and stride `[129042, 1, 201, 1]`, this is considered as contiguous (memory format is channels last) for pytorch.

but onednn considered as not nhwc since
```
    inline bool is_nhwc() const {
      if (!is_plain() || data.ndims != 4) return false;
      const auto &dims = data.dims;
      const auto &strides = blocking_strides();
      const auto n = 0, c = 1, h = 2, w = 3;
      return strides[n] == dims[h] * dims[w] * dims[c]
          && strides[h] == dims[w] * dims[c]
          && strides[w] == dims[c]
          && strides[c] == 1;
    };
```
and the dim0 stride do not match, but actually it does not matter since size0 is 1 and so the index could only be 0.

we need to get rid of the ambiguity between pytorch and onednn, decide `use_channels_last` from pytorch side and pass it to onednn. On onednn side we don't make judgement, just believe in that pytorch passed down physically contiguous tensors in the aligned memory format (and it should be so).

**Comment by XiaobingSuper** [comment] 2022-10-18 13:48
it has been fixed by https://github.com/pytorch/pytorch/pull/83653.

**Closed by XiaobingSuper** 2022-10-18 13:48 UTC
Labels: triaged, module: mkldnn
