### ISSUE TITLE
DISABLED test_function_returns_input_inner_requires_grad_True_save_for_jvp_save_tensors_neither_mark_dirty_True_cpu (__main__.TestAutogradFunctionCPU)

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#113252] opened 2023-11-08 08:00 UTC
Platforms: dynamo

Flaky

First known bad happen on 11/5

```

==================================== RERUNS ====================================
_ TestAutogradFunctionCPU.test_function_returns_input_inner_requires_grad_True_save_for_jvp_save_tensors_neither_mark_dirty_True_cpu _
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/functorch/test_eager_transforms.py", line 1119, in test_function_returns_input
    b_dual = A.apply(a_dual)
             ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/autograd/function.py", line 551, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/autograd/function.py", line 293, in apply_jvp
    return self._forward_cls.jvp(self, *args)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 14, in guard
IndexError: tuple index out of range

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/functorch/test_eager_transforms.py -k test_function_returns_input_inner_requires_grad_True_save_for_jvp_save_tensors_neither_mark_dirty_True_cpu

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
----------------------------- Captured stdout call -----------------------------
ERROR RUNNING GUARDS jvp /var/lib/jenkins/workspace/test/functorch/test_eager_transforms.py:1076
lambda L, **___kwargs_ignored:
  ___guarded_code.valid and
  ___check_global_state() and
  hasattr(L['x_t'], '_dynamo_dynamic_indices') == False and
  ___check_obj_id(L['mark_dirty'], 8883552) and
  hasattr(L['ctx'].saved_tensors[0], '_dynamo_dynamic_indices') == False and
  utils_device.CURRENT_DEVICE == None and
  ___skip_backend_check() or ___current_backend() == ___lookup_backend(140510854941088) and
  ___check_tensors(L['x_t'], L['ctx'].saved_tensors[0], tensor_check_names=tensor_check_names)
----------------------------- Captured stderr call -----------------------------
/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_functorch/deprecated.py:36: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.grad is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.func.grad instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  def warn_deprecated(api, new_api=None):
/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/_functorch/deprecated.py:36: UserWarning: We've integrated functorch into PyTorch. As the final step of the integration, functorch.jvp is deprecated as of PyTorch 2.0 and will be deleted in a future version of PyTorch >= 2.3. Please use torch.func.jvp instead; see the PyTorch 2.0 release notes and/or the torch.func migration guide for more details https://pytorch.org/docs/master/func.migrating.html
  def warn_deprecated(api, new_api=None):
_ TestAutogradFunctionCPU.test_function_returns_input_inner_requires_grad_True_save_for_jvp_save_tensors_neither_mark_dirty_True_cpu _
Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/test/functorch/test_eager_transforms.py", line 1119, in test_function_returns_input
    b_dual = A.apply(a_dual)
             ^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/autograd/function.py", line 551, in apply
    return super().apply(*args, **kwargs)  # type: ignore[misc]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/envs/py_3.11/lib/python3.11/site-packages/torch/autograd/function.py", line 293, in apply_jvp
    return self._forward_cls.jvp(self, *args)  # type: ignore[attr-defined]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 14, in guard
IndexError: tuple index out of range

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/functorch/test_eager_transforms.py -k test_function_returns_input_inner_requires_grad_True_save_for_jvp_save_tensors_neither_mark_dirty_True_cpu

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0
```

This test was disabled because it is failing on main branch ([recent examples](https://hud.pytorch.org/failure?name=pull%20%2F%20linux-focal-py3.11-clang10%20%2F%20test%20(dynamo%2C%201%2C%202%2C%20linux.2xlarge)&jobName=linux-focal-py3.11-clang10%20%2F%20test%20(dynamo%2C%201%2C%202%2C%20linux.2xlarge)&failureCaptures=%5B%22functorch%2Ftest_eager_transforms.py%3A%3ATestAutogradFunctionCPU%3A%3Atest_function_returns_input_inner_requires_grad_True_save_for_jvp_save_tensors_neither_mark_dirty_True_cpu%22%5D)).

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by wconstab** [comment] 2023-11-09 00:58
test passes reliably for me on a build from yesterday... trying again on tip

**Comment by wconstab** [comment] 2023-11-14 01:02
@malfet if i can't repro this is the right thing to do re-enable? (and do i do that by just closing this issue?)

**Comment by malfet** [comment] 2023-11-14 01:05
@wconstab closing the issue will re-enable the test, but I guess it only happens if run in conjunction with other tests. Is it reproducible with the nightly on the day it was reported?

@clee2000 looks like link to recent examples is broken, perhaps it would be good to post a link against 1-2 workflows where it actually happened during the test run

**Comment by clee2000** [comment] 2023-11-14 01:22
Fixed link to recent examples, here are some examples if it breaks again:
https://github.com/pytorch/pytorch/actions/runs/6794699640/job/18471773300 
https://github.com/pytorch/pytorch/actions/runs/6789251643/job/18464042856
https://github.com/pytorch/pytorch/actions/runs/6733643409/job/18459384993

**Closed** 2023-12-05 21:39 UTC
Labels: needs reproduction, triaged, skipped, oncall: pt2
