### ISSUE TITLE
RTX 3090 create cuda tensors much slower after importing transformers library

### ISSUE THREAD

**Issue by hxssgaa** [pytorch/pytorch#45822] opened 2020-10-04 16:09 UTC
## 🐛 Bug

I'm using rtx 3090 to create a simple float32 tensor in cuda. It's very weird it would take too much time after importing huggingface transformers library. However the same code below doesn't have any issues in 20-series cards.

## To Reproduce

The following code would reproduce the behavior:

```
import torch
import time
import transformers

if __name__ == '__main__':
    t = time.time()
    x = torch.zeros((50273,), dtype=torch.float32).cuda()
    print('took:', time.time() - t)
    print('done')
```
result:

```
took: 137.26064133644104
done
```
I think the size doesn't matter, any size could reproduce this result in 3090 cards. I don't have rtx 3080, therefore don't know if the issue would exist in 3080 card.

## Expected behavior

Here is the result after commenting the `import transformers`:

```
took: 0.8175389766693115
done
```

## Environment
The pytorch is built from the master branch of pytorch github. The transformer library is 3.3.1.

```
Collecting environment information...
PyTorch version: 1.7.0a0+9d5607f
Is debug build: True
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: Could not collect
CMake version: version 3.18.2

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 455.23.05
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] numpydoc==1.1.0
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] torch==1.7.0a0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2020.2                      256  
[conda] mkl-include               2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.18.5                   pypi_0    pypi
[conda] numpy-base                1.19.1           py38hfa32c7d_0  
[conda] numpydoc                  1.1.0                      py_0  
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] torch                     1.7.0a0                  pypi_0    pypi
```
## Additional context

I don't know the issue come from transformer library or pytorch. But since the same code under same setting works in rtx 2080. I guess there is a higher chance the problem come from pytorch itself. Thanks for any help.

cc @ngimel @csarofeen @ptrblck

**Comment by ngimel** [comment] 2020-10-05 21:02
Duplicate of #45028 and other similar issues. You need cuda 11.1 for RTX 30XX cards.

**Closed by ngimel** 2020-10-05 21:02 UTC
Labels: module: cuda, module: cudnn, triaged

**Comment by hxssgaa** [comment] 2020-10-06 00:04
Sorry, I think I have have cuda 11.1 and latest pytorch nightly build installed, but the problem doesn't resolve, could you look into this? Thanks.

**Comment by ptrblck** [comment] 2020-10-06 00:14
I assume you've built PyTorch from source using CUDA11.1.
If so, did you compile it with compute capability `8.6` or `8.0+PTX`?

**Comment by hxssgaa** [comment] 2020-10-06 00:23
> I assume you've built PyTorch from source using CUDA11.1.
> If so, did you compile it with compute capability `8.6` or `8.0+PTX`?

I didn't explicitly specify the compute capability to 8.6, I assume the "python setup.py install" will detect the correct compute capability and I didn't encounter the issue "sm_86 is not compatible with the current PyTorch installation" during the installation. How I check if I'm compiling it with 8.6? Thanks.

**Comment by ptrblck** [comment] 2020-10-06 01:29
You could try to use ` python -c "import torch; print(torch._C._cuda_getArchFlags())"` to get the architectures used during the build step.
I verified that rebuilding with 8.6 takes approx. `1.14`s for the initial context creation using your initial code snippet on a 3090.

**Comment by hxssgaa** [comment] 2020-10-06 01:37
> You could try to use ` python -c "import torch; print(torch._C._cuda_getArchFlags())"` to get the architectures used during the build step.
> I verified that rebuilding with 8.6 takes approx. `1.14`s for the initial context creation using your initial code snippet on a 3090.

I verified the result of your script is "sm_86". I found the reason is because I have broken path for the tensorflow, so it will have some issues when I first load the transformers library. Thanks!

**Comment by stas00** [comment] 2020-11-22 01:23
`transformers` loads both tf and pt if it finds them, so chances are that a wrong library might be loaded via tf. See if you get a different outcome if you disable `tf`-loading (I assume that you had it)

```
USE_TF=0 python your_program.py 
```

I started using this to save a few seconds off loading time since I don't want `tf` loaded most of the time.

**Comment by Interesting6** [comment] 2021-01-13 04:56
Similar issue. In Ubuntu18.04, RTX3090, cuda-11.1, Anaconda3-5.2.0-Linux-x86_64, With latest conda and pip.

![image](https://user-images.githubusercontent.com/22903497/104407388-71f3e300-559c-11eb-8d4b-e819b463b404.png)

I have try pytorch 1.2, 1.4, 1.5, 1.6.0, 1.7.0, 1.7.1 in python3.6.8(virtual environment)
and pytorch1.6, 1.7 in python3.8.3(virtual environment).

all of them take more than 400s, when I run the same code above the picture.

Except for the combination of pytorch1.7 & python 3.8.3, which takes only 2s, but I think it also too slow compare to normal conditions.

![image](https://user-images.githubusercontent.com/22903497/104407692-2a218b80-559d-11eb-9c7e-b86e4bd1ab69.png)

But I want to use the combination of python3.6.8 & pytorch1.4.

**Comment by ptrblck** [comment] 2021-01-15 00:43
@Interesting6 PyTorch `1.4` didn't ship with the CUDA11 changes, so the CUDA will JIT compile the kernels in the first CUDA operation, which explains the slowdown.
To avoid this use the latest binaries with the CUDA11.0 runtime.

**Comment by Interesting6** [comment] 2021-01-20 12:36
> @Interesting6 PyTorch `1.4` didn't ship with the CUDA11 changes, so the CUDA will JIT compile the kernels in the first CUDA operation, which explains the slowdown.
> To avoid this use the latest binaries with the CUDA11.0 runtime.

I think these pytorchs are use the cudatoolkit provide by conda install. Not the system cuda11.1.
they are all download by the tips of authority website.
