### ISSUE TITLE
Can't load the model in Virtual environment 

### ISSUE THREAD

**Issue by multinucliated** [pytorch/pytorch#40922] opened 2020-07-02 15:32 UTC
`tacotron2 = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_tacotron2')`

I'm not able to load this model when I'm making the virtual environment and loading.
Though this same line of code is working fine in my Jupyter notebook .

Also Im using windows 10 and cuda 10.2 and latest pytorch !

Traceback (most recent call last):
  File "/voice/tts.py", line 9, in <module>
    tacotron2 = torch.hub.load('nvidia/DeepLearningExamples:torchhub', 'nvidia_tacotron2')
  File "\venv\lib\site-packages\torch\hub.py", line 369, in load
    model = entry(*args, **kwargs)
  File "C:\Users\Anshul/.cache\torch\hub\nvidia_DeepLearningExamples_torchhub/hubconf.py", line 130, in nvidia_tacotron2
    from PyTorch.SpeechSynthesis.Tacotron2.tacotron2 import model as tacotron2
  File "C:\Users\Anshul/.cache\torch\hub\nvidia_DeepLearningExamples_torchhub\PyTorch\SpeechSynthesis\Tacotron2\tacotron2\model.py", line 37, in <module>
    from common.layers import ConvNorm, LinearNorm
  File "C:\Users\Anshul\.cache\torch\hub\nvidia_DeepLearningExamples_torchhub\PyTorch\SpeechSynthesis\Tacotron2\common\layers.py", line 29, in <module>
    from librosa.filters import mel as librosa_mel_fn
  File "\venv\lib\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "\venv\lib\site-packages\librosa\core\__init__.py", line 125, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "\venv\lib\site-packages\librosa\core\time_frequency.py", line 11, in <module>
    from ..util.exceptions import ParameterError
  File "\venv\lib\site-packages\librosa\util\__init__.py", line 77, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "\venv\lib\site-packages\librosa\util\utils.py", line 5, in <module>
    import scipy.ndimage
  File "\venv\lib\site-packages\scipy\__init__.py", line 104, in <module>
    from . import _distributor_init
  File \venv\lib\site-packages\scipy\_distributor_init.py", line 61, in <module>
    WinDLL(os.path.abspath(filename))
  File "\Anaconda3\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

Process finished with exit code 1

cc @ailzhang @peterjc123 @nbcsm @guyang3532

**Comment by pbelevich** [comment] 2020-07-02 17:48
Not able to reproduce (win10, macos)

**Comment by peterjc123** [comment] 2020-07-02 17:51
Related: https://github.com/scipy/scipy/issues/12400
Workground:
Option 1: Downgrade scipy to 1.4.1
Option 2: Use the scipy from Anaconda Cloud

**Comment by multinucliated** [comment] 2020-07-02 18:49
Something weird I observed though this should not be the case but 
1. I was running that venv in Pycharm so that Error traceback was printed .
2. But When i activated the same venv in the normal command promt console they gave me error of "module not found Numba" 

```
pip install numba==0.43.0
pip install llvmlite==0.32.1
```

So I installed these two with specific version as the latest was not supporting and Now it made it run fine.


Can you please explain ?Why that error log came in the normal terminal not in the PyCharm terminal ?

**Comment by mszhanyi** [comment] 2020-09-23 08:08
@multinucliated since it's not a Pytorch bug/issue. For general questions, could you please ask in https://discuss.pytorch.org/.
We'll close the issue soon

**Closed** 2020-09-25 08:47 UTC
Labels: module: hub, module: windows, needs reproduction, triaged
