### ISSUE TITLE
Anchor links for documentation are gone in 1.8.0 docs

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#54683] opened 2021-03-25 15:03 UTC
## 📚 Documentation

In 1.7.1 (notice the anchor on right):
![image](https://user-images.githubusercontent.com/5652049/112494724-aaacf700-8d59-11eb-942e-21983e6f17ea.png)

In 1.8.0, the anchor doesn't show up anymore:
https://pytorch.org/docs/stable/autograd.html

cc @brianjo @mruberry

**Comment by brianjo** [comment] 2021-03-26 03:13
I'll fix this. I just need to copy a couple of js files in.

**Comment by brianjo** [comment] 2021-03-26 17:55
This should be working for stable/1.8.1 now.

**Comment by zou3519** [comment] 2021-03-29 14:31
Discussed offline: the problem reoccurred so re-opening this issue. cc @mattip as well.

**Comment by brianjo** [comment] 2021-03-29 14:40
I think the problem is that the vendor folder is missing from https://github.com/pytorch/pytorch.github.io/tree/site/docs/1.8.1/_static/js. (So they're not available in the stable folder on our master (gh-pages) branch. The missing folder can be found in the master folder: https://github.com/pytorch/pytorch.github.io/tree/site/docs/master/_static/js/vendor

**Comment by zou3519** [comment] 2021-03-29 21:34
They're back! https://pytorch.org/docs/stable/autograd.html#torch.autograd.backward . Thanks @brianjo.

Should we leave this issue open? I think there is still a question of why the vendor folder doesn't get copied as a part of the docs build process that we should work out so we don't have to remember to copy it every time we do a release

**Comment by brianjo** [comment] 2021-03-30 19:37
Could it be that jekyll is causing problems? https://github.com/mpetrovich/stylemark/issues/65. Do we need to add a .nojekyll to every new documentation release?

**Comment by brianjo** [comment] 2021-03-30 19:41
Just created https://github.com/pytorch/pytorch.github.io/pull/649 to try it out.

**Comment by brianjo** [comment] 2021-03-31 15:07
> Just created [pytorch/pytorch.github.io#649](https://github.com/pytorch/pytorch.github.io/pull/649) to try it out.

Just checked https://pytorch.org/docs/stable/autograd.html#torch.autograd.backward and the fix seems to be working. I'll close this for now. Please reopen if we have issues again. Thank you Richard! @zou3519

**Closed by brianjo** 2021-03-31 15:07 UTC
Labels: module: docs, triaged
