### ISSUE TITLE
linalg.eig segfault if NaN in tensor with mkl

### ISSUE THREAD

**Issue by cjekel** [pytorch/pytorch#64671] opened 2021-09-08 18:17 UTC
## 🐛 Bug

`torch.linalg.eig` segfaults if NaN is in tensor when using mkl

## To Reproduce

1. Run torch.linalg.eig on a tensor with `float('nan')` in at least one value (while using mkl as blas)

```python
import torch
x = torch.rand(6,6)
torch.linalg.eig(x)  # Okay
x[0, 4] = float('nan')
torch.linalg.eig(x)
```

One possible error you may see:
```
** On entry to SGEBAL, parameter number  3 had an illegal value
Segmentation fault: 11
```
Another possible error (on a different system)
```
Intel MKL ERROR: Parameter 3 was incorrect on entry to SGEBAL.
Segmentation fault (core dumped)
```

## Expected behavior

It would be nice if this threw a Python exception rather than a segfault, and was consistent with different blas back-ends. If that is not possible, it would be nice to add documentation that this could happen.

With an OpenBLAS build we get a nicer `RuntimeError`
```
 ** On entry to SGEBAL parameter number  3 had an illegal value
 ** On entry to SGEHRD parameter number  2 had an illegal value
 ** On entry to SORGHR parameter number  2 had an illegal value
 ** On entry to SHSEQR parameter number  4 had an illegal value
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-1-175d7981d746> in <module>
      3 torch.linalg.eig(x)  # Okay
      4 x[0, 4] = float('nan')
----> 5 torch.linalg.eig(x)

RuntimeError: torch.linalg.eig: Argument 4 has illegal value

```

or with numpy we get

```python
In [1]: import numpy as np
   ...: x = np.random.random((6, 6))
   ...: np.linalg.eig(x)  # Okay
   ...: x[0, 4] = float('nan')
   ...: np.linalg.eig(x)
---------------------------------------------------------------------------
LinAlgError                               Traceback (most recent call last)
<ipython-input-4-b119deb916a2> in <module>
      3 np.linalg.eig(x)  # Okay
      4 x[0, 4] = float('nan')
----> 5 np.linalg.eig(x)

<__array_function__ internals> in eig(*args, **kwargs)

~/anaconda3/envs/torchCPU/lib/python3.7/site-packages/numpy/linalg/linalg.py in eig(a)
   1315     _assert_stacked_2d(a)
   1316     _assert_stacked_square(a)
-> 1317     _assert_finite(a)
   1318     t, result_t = _commonType(a)
   1319 

~/anaconda3/envs/torchCPU/lib/python3.7/site-packages/numpy/linalg/linalg.py in _assert_finite(*arrays)
    206     for a in arrays:
    207         if not isfinite(a).all():
--> 208             raise LinAlgError("Array must not contain infs or NaNs")
    209 
    210 def _is_empty_2d(arr):

LinAlgError: Array must not contain infs or NaNs

```

## Environment

I'm able to reproduce this on linux and Mac using conda on different intel hardware. Here's the mac environment.

```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 10.15.7 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.20.2
Libc version: N/A

Python version: 3.7.11 (default, Jul 27 2021, 07:03:16)  [Clang 10.0.0 ] (64-bit runtime)
Python platform: Darwin-19.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] botorch==0.4.0
[pip3] gpytorch==1.4.1
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchinfo==1.5.2
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] botorch                   0.4.0                         0    pytorch
[conda] gpytorch                  1.4.1                         0    gpytorch
[conda] mkl                       2021.3.0           hecd8cb5_517  
[conda] mkl-service               2.4.0            py37h9ed2024_0  
[conda] mkl_fft                   1.3.0            py37h4a7008c_2  
[conda] mkl_random                1.2.2            py37hb2f4e1b_0  
[conda] numpy                     1.20.3           py37h4b4dc7a_0  
[conda] numpy-base                1.20.3           py37he0bd621_0  
[conda] pytorch                   1.9.0                   py3.7_0    pytorch
[conda] torchaudio                0.9.0                      py37    pytorch
[conda] torchinfo                 1.5.2                    pypi_0    pypi
[conda] torchvision               0.10.0                 py37_cpu    pytorch
```

## Additional context

Search of github issues with linalg.eig didn't come up with any hits.

### Possible solutions

Just a couple simple approaches for now to get some conversations started.

1. Add a python check for `nan` prior to compute the eigenvalue decomposition (similar to what numpy does)
2. Don't fix, but add documentation to `torch.linalg.eig` that this could happen. (There are already a bunch of notes and warnings, but a future user may find this addition helpful).

### Related
https://github.com/pytorch/pytorch/issues/61251

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by VitalyFedyunin** [comment] 2021-09-09 00:39
Hi-Pri because of SIGFAILT

**Comment by IvanYashchuk** [comment] 2021-09-15 21:43
Thank you, @cjekel, for an extended description of the problem and the expected behavior suggestions! As you already found the other issue about this problem and conveniently linked it in the "Related" section, I will close this one to continue the discussion in the earlier issue https://github.com/pytorch/pytorch/issues/61251.

**Closed by IvanYashchuk** 2021-09-15 21:43 UTC
Labels: high priority, module: error checking, triaged, module: mkl
