### ISSUE TITLE
torch.sum() should work on sparse tensors

### ISSUE THREAD

**Issue by ssnl** [pytorch/pytorch#86232] opened 2022-10-04 21:02 UTC
### 🚀 The feature, motivation and pitch

`sp_coo_tensor.sum()` and `torch.sum(sp_coo_tensor)` do not work because 
```py
NotImplementedError: Could not run 'aten::sum.dim_IntList' with arguments from the 'SparseCPU' backend. This could be because the operator doesn't exist for this backend, or was omitted during the selective/custom build process (if using custom build). If you are a Facebook employee using PyTorch on mobile, please visit https://fburl.com/ptmfixes for possible resolutions. 'aten::sum.dim_IntList' is only available for these backends: [CPU, CUDA, HIP, MPS, IPU, XPU, HPU, VE, Meta, PrivateUse1, PrivateUse2, PrivateUse3, FPGA, ORT, Vulkan, Metal, QuantizedCPU, QuantizedCUDA, QuantizedHIP, QuantizedMPS, QuantizedIPU, QuantizedXPU, QuantizedHPU, QuantizedVE, QuantizedMeta, QuantizedPrivateUse1, QuantizedPrivateUse2, QuantizedPrivateUse3, CustomRNGKeyId, MkldnnCPU, SparseCsrCPU, SparseCsrCUDA, NestedTensorCPU, BackendSelect, Python, Functionalize, Named, Conjugate, Negative, ZeroTensor, ADInplaceOrView, AutogradOther, AutogradCPU, AutogradCUDA, AutogradHIP, AutogradXLA, AutogradMPS, AutogradIPU, AutogradXPU, AutogradHPU, AutogradVE, AutogradLazy, AutogradMeta, AutogradPrivateUse1, AutogradPrivateUse2, AutogradPrivateUse3, AutogradNestedTensor, Tracer, AutocastCPU, AutocastCUDA, Batched, VmapMode, PythonTLSSnapshot].
```

However, it is as simple as `sp_coo_tensor._values().sum()`. I understand that with `dim=` arg, very special treatment is needed. But for simple ones like this, do we have to write `t.sum() if not t.is_sparse else torch.sparse.sum(t)`?

cc @nikitaved @pearu @cpuhrsch @amjames @bhosmer

**Comment by cpuhrsch** [comment] 2022-10-06 20:10
This should have just landed in https://github.com/pytorch/pytorch/pull/86300

**Comment by pearu** [comment] 2022-10-10 08:43
We can leave this issue open for the lack of `dim` and `keepdim` arguments support in the case of sparse inputs to su,.

**Comment by pearu** [comment] 2023-01-29 16:48
The issue is fixed by https://github.com/pytorch/pytorch/pull/92979

**Closed by pearu** 2023-01-29 16:48 UTC
Labels: module: sparse, triaged
