### ISSUE TITLE
can't print cifar pixel image to console

### ISSUE THREAD

**Issue by brando90** [pytorch/pytorch#6831] opened 2018-04-21 01:04 UTC
I was trying to print the x pixels values from pytorch and got a weird unicode error:

(Pdb) data_train[0]
*** UnicodeEncodeError: 'latin-1' codec can't encode character '\u22f1' in position 210: ordinal not in range(256)

only after I casted to numpy() did it print correctly. Shouldn't it be printing the floatTensor easily?

To reproduce the code just loop through cifar10 with trainloader and print the x feature pixels:

        for i,data_train in enumerate(trainloader):
              print(data_train[0]) # BUG

**Comment by ngimel** [comment] 2018-04-21 03:57
That's a dupe of #1660, with solution described in there ( set LANG environment variable) Tensor you are trying to print is too large, and ellipsis character is not printing because of encoding.

**Closed** 2018-04-21 11:39 UTC

**Comment by brando90** [comment] 2018-04-23 17:57
I ran into this just now. What fixed it for me is to set the environment variable LANG=C.UTF-8 LC_ALL=C.UTF-8. This is in a Docker container running Ubuntu.

**Comment by brando90** [comment] 2018-04-23 17:58
export LANG=C.UTF-8 LC_ALL=C.UTF-8
