### ISSUE TITLE
torch.dot gives strange results 

### ISSUE THREAD

**Issue by jy1993** [pytorch/pytorch#7064] opened 2018-04-28 03:01 UTC
<img width="528" alt="e6a64da7-bda7-47ab-9c42-ec09f1c44ca0" src="https://user-images.githubusercontent.com/18455572/39391291-829662cc-4ad3-11e8-91dd-7a04ecf795cd.png">

cc @VitalyFedyunin

**Comment by SsnL** [comment] 2018-04-28 03:27
Is this on mac?

**Comment by apaszke** [comment] 2018-04-28 10:00
Please update MKL and rebuild if you build from source. It’s a known bug in some older versions

**Comment by soumith** [comment] 2018-04-29 17:26
additionally, if `numpy` is installed with `nomkl` feature enabled, then you might also see this bug.

**Comment by iondel** [comment] 2018-05-19 17:36
I've met a similar problem (see #7692) and I just wanted to confirm that updating `mkl` did solve the problem for me.

**Comment by mruberry** [comment] 2020-02-12 18:40
Confirmed again this does not reproduce. Closing due to age + lack of current repro.

**Closed by mruberry** 2020-02-12 18:40 UTC
Labels: module: cpu, module: numpy, module: operators, module: third_party, topic: numerical-reproducibility, triaged
