### ISSUE TITLE
Pytorch Model Summary

### ISSUE THREAD

**Issue by tejan-rgb** [pytorch/pytorch#56378] opened 2021-04-19 14:23 UTC
## 🚀 Feature

Requesting a feature something like model.summary() to view the number of trainable parameters in each layer, like they have in keras.

cc @albanD @mruberry @jbschlosser

**Comment by humanzer0** [comment] 2021-04-19 14:32
I would like to pick up this task.

**Comment by jbschlosser** [comment] 2021-04-19 16:46
This was requested in https://github.com/pytorch/pytorch/issues/2001 and PR #3043 attempted to implement this before. Note that a full Keras-like `summary()` function showing connectivity, etc. doesn't work well in PyTorch since modules are flexible enough to dynamically generate computation graphs that can differ across forward passes; see [this comment](https://github.com/pytorch/pytorch/pull/3043#issuecomment-367014512) from the PR for more info.

However, if you're specifically just looking for trainable parameters per submodule, I think that could be worth adding as it seems fairly popular.

**Comment by tejan-rgb** [comment] 2021-04-20 01:40
So something along the lines of:

```
from prettytable import PrettyTable

def count_parameters(model):
    table = PrettyTable(["Modules", "Parameters"])
    total_params = 0
    for name, parameter in model.named_parameters():
        if parameter.requires_grad:
            param = parameter.numel()
            table.add_row([name, param])
            total_params+=param
    print(table)
    return f"{total_params:,}"
    
count_parameters(net)
```

which outputs:

```
+---------------------+------------+
|       Modules       | Parameters |
+---------------------+------------+
|  features.0.weight  |    1728    |
|   features.0.bias   |     64     |
|  features.3.weight  |   73728    |
|   features.3.bias   |    128     |
|  features.6.weight  |   294912   |
|   features.6.bias   |    256     |
|  features.8.weight  |   589824   |
|   features.8.bias   |    256     |
|  features.11.weight |  1179648   |
|   features.11.bias  |    512     |
|  features.13.weight |  2359296   |
|   features.13.bias  |    512     |
|  features.16.weight |  2359296   |
|   features.16.bias  |    512     |
|  features.18.weight |  2359296   |
|   features.18.bias  |    512     |
| classifier.0.weight | 102760448  |
|  classifier.0.bias  |    4096    |
| classifier.3.weight |  16777216  |
|  classifier.3.bias  |    4096    |
| classifier.6.weight |  4096000   |
|  classifier.6.bias  |    1000    |
+---------------------+------------+
```

could be done.

**Comment by pr2tik1** [comment] 2021-04-21 12:28
One can use https://github.com/sksq96/pytorch-summary too.  

Sample code-

from torchsummary import summary
summary(your_model, input_size=(channels, H, W))

**Comment by oke-aditya** [comment] 2021-04-24 19:04
Why not port torchsummary to PyTorch? :sweat_smile: 
it could be in utils and can be used as `from torch.utils.summary import model_summary`. 

torchsummary is very popular and is really a good choice.

**Comment by jbschlosser** [comment] 2021-06-01 20:18
Closing as duplicate of #2001; please continue discussion there.

**Closed by jbschlosser** 2021-06-01 20:18 UTC
Labels: enhancement, module: nn, triaged
