### ISSUE TITLE
torch.sparse.mm is not stable because it would suddenly cause nan

### ISSUE THREAD

**Issue by cloudyyyyy** [pytorch/pytorch#19546] opened 2019-04-21 17:38 UTC
when I use `torch.sparse.mm`, I find it will cause nan sometimes, like this:
```
torch.sum(torch.isnan(torch.sparse.mm(adj, support)))
Out[22]: tensor(0)
torch.sum(torch.isnan(torch.sparse.mm(adj, support)))
Out[23]: tensor(2)
torch.sum(torch.isnan(torch.sparse.mm(adj, support)))
Out[24]: tensor(0)
```
and I create `adj` by
```
torch.empty((num_left, num_right), layout=torch.sparse_coo)
``` 

If I use `torch.mm` or `torch.spmm` or a non-empty sparse matrix instead of `torch.empty` with `layout`,  I won't find this problem.

**Comment by aocsa** [comment] 2020-07-01 15:45
Hi @smessmer. 
I wasn't able to reproduce this bug. I tried with this code on PyTorch 1.5
```
import torch 
num_left = 10
num_right = 10
adj = torch.empty((num_left, num_right), layout=torch.sparse_coo)
support = torch.rand((num_left, num_right))
for i in range(100):
    print(torch.sum(torch.isnan(torch.sparse.mm(adj, support))))
```

**Comment by rgommers** [comment] 2020-07-14 15:45
This doesn't look like a valid bug report. One should never use the result of `torch.empty` without filling in values first, because it could contain anything - `nan`, `inf` or values that cause overflow for example.

I'll close the issue. @cloudyyyyy if you have a fully reproducible example please feel free to comment/reopen.

**Closed by rgommers** 2020-07-14 15:45 UTC
Labels: module: operators, module: sparse, triaged
