### ISSUE TITLE
RuntimeError: [ONNXRuntimeError] : 1 : GENERAL ERROR : Load model from waveglow.onnx failed:Type Error: Type parameter (T) bound to different types (tensor(int64) and tensor(float) in node ()

### ISSUE THREAD

**Issue by ajaysg-zz** [pytorch/pytorch#23724] opened 2019-08-02 07:05 UTC
**Description**
I am having a pytorch model which is exported to onnx format. I am trying to use that model in onnxruntime. But I am getting the error mentioned in the issue 

**System information**
- OS Platform and Distribution : **Linux Ubuntu 16.04**
- ONNX Runtime installed from (source or binary): **Binary via pip**
- ONNX Runtime version: **onnxruntime==0.4.0 (CPU version)**
- Python version: 3.6
- Visual Studio version (if applicable):**No**
- GCC/Compiler version (if compiling from source): **No**
- CUDA/cuDNN version:**CUDA 9/cuDNN 7**
- GPU model and memory:**Tesla K20XM and 6GB**

**Note: I am NOT USING onnxruntime-gpu**

**To Reproduce**
import onnx
import onnxruntime as rt
sess = rt.InferenceSession("waveglow.onnx")

**Expected Behavior**
After the session creation i should be able to infer with my model.

**Screenshots**
![oie_lcHA5bVXf4sL](https://user-images.githubusercontent.com/22977639/62302941-de5a4f80-b498-11e9-86a6-e3aa22eb8590.png)

Model is from the repository https://github.com/NVIDIA/waveglow/tree/4b1001fa3336a1184b8293745bb89b177457f09b

Link to original pytorch model: https://drive.google.com/file/d/1cjKPHbtAMh_4HTHmuIGNkbOkPBD9qwhj/view?usp=sharing

Link to onnx model:
https://drive.google.com/file/d/1N4D4pu-ibYBgm890ZJWRUkneQuyUKA_H/view?usp=sharing

**Script used to convert the pytorch model to onnx by passing dummy input**
waveglow_path = './waveglow_256channels.pt'
waveglow = torch.load(waveglow_path)['model']

mel_extra=torch.tensor(np.full((1,80,222),-10.0)).float()
dummy_input=torch.autograd.Variable(mel_extra).cuda().float()

audio = torch.tensor(np.full((1,222), -0.5)).float()
audio_input = torch.autograd.Variable(audio).cuda().float()

torch.onnx.export(waveglow, ((dummy_input, audio_input),), "./waveglow.onnx")

**Comment by mrshenli** [comment] 2019-08-02 16:58
cc @houseroad

**Comment by ajaysg** [comment] 2019-08-06 09:55
@BowenBao can u please help me where is the bug? is it with pytorch or onnx or onnxrt

**Comment by spandantiwari** [comment] 2019-08-09 18:59
@ajaysg - We have looked at this specific and will be fixing it in the exporter. In general for the Waveglow model there are may be some unsupported ops such a `det`. We will track those as well, but it may take some time because we might have to possibly update the ONNX spec.

**Comment by ajaysg** [comment] 2019-08-10 05:49
@spandantiwari as for operators like `det` and `logdet` , i had problems initially during onnx export. i followed this https://github.com/onnx/onnx/issues/1671#issuecomment-444314992 and added the functions in symbolic_opset9.py. Then onnx export became successful. Problem arised when i am trying to use the onnx graph in onnxruntime. i got the Type parameter error as mentioned in the issue

**Comment by spandantiwari** [comment] 2019-08-11 02:21
@ajaysg - Makes sense. We are adding support for det in ONNX. Also, working to fix type mismatch issue.

**Comment by ajaysg** [comment] 2019-08-11 16:43
@spandantiwari the Mul operator is causing trouble in shape inference in the onnx graph. please find the attached onnx graph https://github.com/onnx/onnx/files/3480378/2.txt

i could find opschema for Mul here

[https://github.com/onnx/onnx/blob/4eb737c8eacf48f8771d515d0a373a4b964cfab7/onnx/defs/math/defs.cc](url) line141

it is calling a function called **MathDocGenerator**

[https://github.com/onnx/onnx/blob/4eb737c8eacf48f8771d515d0a373a4b964cfab7/onnx/defs/math/defs.cc](url) line23
In the above mentioned line should we include different data types like 
float32 etc....
just an observation as i do not know the clear solution. please advise

**Comment by BowenBao** [comment] 2019-08-14 23:57
@ajaysg I have opened a PR for the data type mismatch issue, once it gets merged this should no longer be a problem.

We are working on getting `torch.unfold` and `torch.logdet` supported in ONNX.

**Comment by marcown** [comment] 2019-08-15 06:16
@ajaysg : 

The issue also occurs in my model. Is it possible to convert it before the export / or find the line where the error occurs?

**Comment by ajaysg** [comment] 2019-08-17 14:04
@BowenBao has the type mismatch error been resolved. i am still getting the same error. i cloned pytorch repo and compiled from source again

**Comment by ajaysg** [comment] 2019-08-20 05:49
@spandantiwari i am still getting the same error. Has the type mismatch issue been resolved?

**Comment by spandantiwari** [comment] 2019-08-20 19:57
@ajaysg - The PR has been submitted. https://github.com/pytorch/pytorch/pull/24378

**Comment by houseroad** [comment] 2019-09-18 23:03
The PR is merged, so close.

**Comment by ajaysg** [comment] 2019-09-19 05:14
Still the same error continues.

**Comment by Akshaysharma29** [comment] 2020-06-09 09:47
Hi, @ajaysg have you solved the issue?

**Comment by ajaysg** [comment] 2020-06-10 01:31
hi @Akshaysharma29 please go through this link
https://devblogs.nvidia.com/how-to-deploy-real-time-text-to-speech-applications-on-gpus-using-tensorrt/
previously waveglow model's `Aten` operator did not have support in `onnxrt` or `tensorrt`, So waveglow model's onnx conversion was not possible. But now i think the new pretrained `waveglow` model can easily be exported to onnx as per the above link. I have not tried that yet myself, but this documentation is recent and should work.

**Comment by Akshaysharma29** [comment] 2020-06-10 04:29
Thanks, @ajaysg 
but I want to know how the issue is resolved because I am trying to convert another model(OCR) and facing the same issue. Thanks once again.

**Comment by ajaysg** [comment] 2020-06-10 05:47
Hi @Akshaysharma29 i think the problem you are facing is similar to this https://github.com/onnx/onnx/issues/2226 and https://github.com/onnx/onnx/issues/2226. There is a mismatch between the data type of nodes in the onnx model graph and data type used by shape inference function of onnxrt. Try converting your model to float32 before converting to onnx. If it still does not work then may be it cannot be used in onnx. 
If you are training your own model try to address this issue by properly declaring data types before. If it is a pretrained model, we have to debug in the training code. This is the problem with pytorch framework and onnx. My advice would be "Try to use tensorflow models or train using tensorflow as it has proper community support.  pytorch is growing community and it will take some time for them to address these bugs and unify things".

**Comment by Akshaysharma29** [comment] 2020-06-10 09:17
Thanks, @ajaysg for a quick response as my model use indexing(which I have tried to handle) so I think I have to look some other way around.
Thanks for the help😊.

**Comment by nehasoni3** [comment] 2020-12-24 11:32
Hi, I am also stuck with similar kind of issue. ONNX model's input is of Float32 but its output is INT64. Therefore, when I convert this ONNX to TFLite. It includes Flex Delegate. Can I find some help to solve this. How to convert ONNX output from int64 to float32.

**Comment by garymm** [comment] 2021-12-22 21:49
Seems original issue has been resolved. For other similar issues please file a new issue with reproduction instructions.

**Closed by garymm** 2021-12-22 21:49 UTC
Labels: module: onnx, triaged
