### ISSUE TITLE
[pytorch][0.4][bug] "torch.min" and "torch.max" ignores "nan" in cuda case and crash with pure "nan" tensor

### ISSUE THREAD

**Issue by sytrus-in-github** [pytorch/pytorch#6996] opened 2018-04-26 15:39 UTC
## Issue description

`torch.min` and `torch.max` ignores `nan` in cuda case and crash with pure `nan` tensor.

## Code example
```python
>>> import torch
>>> a = torch.Tensor(4, 3).fill_(1)
>>> a = a.cuda()
>>> a[1, 2] = float('nan')
>>> a
tensor([[  1.,   1.,   1.],
        [  1.,   1., nan.],
        [  1.,   1.,   1.],
        [  1.,   1.,   1.]], device='cuda:0')
>>> torch.max(a)
tensor(1., device='cuda:0')
>>> torch.min(a)
tensor(1., device='cuda:0')
>>> a = torch.Tensor(4, 3).fill_(float('nan'))
>>> a = a.cuda()
>>> torch.max(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 218, in _str
    fmt, scale, sz = _number_format(self)
  File "anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 96, in _number_format
    if value != math.ceil(value.item()):
RuntimeError: Overflow when unpacking long
>>> torch.min(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "anaconda3/lib/python3.6/site-packages/torch/tensor.py", line 57, in __repr__
    return torch._tensor_str._str(self)
  File "anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 218, in _str
    fmt, scale, sz = _number_format(self)
  File "anaconda3/lib/python3.6/site-packages/torch/_tensor_str.py", line 96, in _number_format
    if value != math.ceil(value.item()):
RuntimeError: Overflow when unpacking long
```
## System Info

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): conda
- Build command you used (if compiling from source):
- OS: Ubuntu 16.04
- PyTorch version: 0.4.0
- Python version: 3.6.3
- CUDA/cuDNN version: 8 / 5
- GPU models and configuration: GTX 1050 Ti
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by zou3519** [comment] 2018-04-26 15:58
Thanks for the report, @sytrus-in-github. I have reproduced the issue and have seen the same behavior as you have.

**Comment by sytrus-in-github** [comment] 2018-04-26 16:57
by the way, same tests with nightly build 2018.04.20:
```python
>>> import torch
>>> torch.__version__
'2018.04.20'
>>> a = torch.Tensor(4, 3).fill_(1)
>>> a[1, 2] = float('nan')
>>> a = a.cuda()
>>> torch.max(a)
tensor(1.0000, device='cuda:0')
>>> torch.min(a)
tensor(1.0000, device='cuda:0')
>>> a = torch.Tensor(4, 3).fill_(float('nan'))
>>> a = a.cuda()
>>> torch.max(a)
tensor(1.00000e+38 *
       -3.4028, device='cuda:0')
>>> torch.min(a)
tensor(1.00000e+38 *
       3.4028, device='cuda:0')
```
This might shed some light as to why it crashes saying "overflow".

**Comment by SsnL** [comment] 2018-04-26 18:32
It's not really a crash but a printing bug (duplicate of #6339 ). cc @li-roy

**Comment by sytrus-in-github** [comment] 2018-04-26 18:44
@SsnL maybe not just a printing bug, in this case the tensor `a` contains only `nan`. The big values `1.00000e+38 * -3.4028` and `1.00000e+38 * 3.4028` seem to come from nowhere ...

**Comment by SsnL** [comment] 2018-04-26 18:53
Yes I agree that there is a bug in the kernel too. Sorry for not being clear. I was saying that the function didn't crash, but the printing function did.

**Closed** 2018-04-30 19:03 UTC
Labels: bug

**Comment by Bicheng16** [comment] 2020-04-29 12:10
Following this post, do we sort out the issue of nanmin and nanmax on non-cuda version? I still get the same problem.
`
>>>import torch
>>>a = torch.tensor([1, 2, 3, float('NaN')])
>>>a.min()
tensor(nan)
>>>a.max()
tensor(nan)
`
