### ISSUE TITLE
32-bit library Crash Based on Windows compilation

### ISSUE THREAD

**Issue by neuxys** [pytorch/pytorch#82082] opened 2022-07-25 03:09 UTC
### 🐛 Describe the bug

Because I want to use the library "libtorch with CPU" in 32-bit Windows applications, I use VS2019 to try to compile 32-bit "libtorch".

There are two problems encountered during compilation:

First, `pytorch_ src_ dir/c10/util/safe_ numerics. h(25,16): error C3861: “_addcarry_u64”: identifier not found`
I found that Windows only defined "_addcarry_u64" for 64-bit programs not 32-bit, so I use the following method to replace this function:
```
*out = a + b;
  if (UINT64_MAX - a < b)
	  return true;
  else
	  return false;
```
After modification, it can be compiled.

Next, I encounter the second problem, `pytorch_src_dir\aten\src\ATen\native\DispatchStub.cpp(155, 70): error C2065: "AVX2": undeclared identifier`
I found that "AVX2" is a macro definition about CPU instruction optimization, because "HAVE_AVX2_CPU_DEFINITION" is not defined, so it is bound to report an error. Therefore, I annotated the line 155. In this way, the program will take the DEFAULT branch, which can be compiled too.

After solving the above two problems, I can finally compile "touch.dll, touch_cpu.dll, c10.dll, torch_global_deps.dll" and their corresponding ".lib".

When I thought it had been compiled correctly, I found that I was wrong.
I correctly imported the compiled include/lib/dll into an empty VS project, and there was a crash during compilation,
`0x760FCA42 (located main.exe) unhandled exceptions: Microsoft C++ Exception: c10::Error，Located at memory location 0x0113e954`

Stack information:
```
c10.dll!c10::detail::torchCheckFail(const char * func, const char * file, unsigned int line, const std::string & msg) line 86	C++
c10.dll!c10::detail::torchCheckFail(const char * func, const char * file, unsigned int line, const std::string & msg) line 86	C++
torch_cpu.dll!c10::detail::getTypePtr_<c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>>>::call::__l2::<lambda>() line 1730	C++
[Inline framework] torch_cpu.dll!c10::detail::getTypePtr_<c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>>>::call() line 1726	C++
[Inline framework] torch_cpu.dll!c10::getTypePtr() line 1973	C++
torch_cpu.dll!c10::getTypePtrCopy<c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>>>() line 1980	C++
torch_cpu.dll!c10::detail::infer_schema::`anonymous namespace'::createArgumentVector(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef> args) line 26	C++
torch_cpu.dll!c10::detail::infer_schema::make_function_schema(std::string && name, std::string && overload_name, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef> arguments, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef> returns) line 34	C++
torch_cpu.dll!c10::detail::infer_schema::make_function_schema(c10::ArrayRef<c10::detail::infer_schema::ArgumentDef> arguments, c10::ArrayRef<c10::detail::infer_schema::ArgumentDef> returns) line 38	C++
torch_cpu.dll!c10::detail::infer_schema::createFunctionSchemaFromTraitsFlattenedReturns<c10::guts::function_traits<at::Tensor __cdecl(at::Tensor,c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> const &,double,__int64)>>() line 126	C++
torch_cpu.dll!c10::inferFunctionSchemaFlattenedReturns<at::Tensor __cdecl(at::Tensor,c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> const &,double,__int64)>() line 149	C++
torch_cpu.dll!c10::detail::inferFunctionSchemaFromFunctor<at::Tensor (__cdecl*)(at::Tensor,c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> const &,double,__int64)>() line 30	C++
[Inline framework] torch_cpu.dll!torch::CppFunction::{ctor}(at::Tensor(*)(at::Tensor, const c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> &, double, __int64)) line 113	C++
[Inline framework] torch_cpu.dll!torch::Library::impl(const char * name, at::Tensor(*)(at::Tensor, const c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> &, double, __int64)) line 659	C++
torch_cpu.dll!torch::Library::impl<at::Tensor (__cdecl&)(at::Tensor,c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> const &,double,__int64)>(torch::detail::SelectiveStr<1> name, at::Tensor(*)(at::Tensor, const c10::intrusive_ptr<ConvPackedParamsBase<2>,c10::detail::intrusive_target_default_null_type<ConvPackedParamsBase<2>>> &, double, __int64) raw_f) line 738	C++
torch_cpu.dll!at::native::`anonymous namespace'::TORCH_LIBRARY_IMPL_init_quantized_QuantizedCPU_4(torch::Library & m) line 1425	C++
[Inline framework] torch_cpu.dll!torch::detail::TorchLibraryInit::{ctor}(torch::Library::Kind fn, void(*)(torch::Library &)) line 842	C++
torch_cpu.dll!at::native::`anonymous namespace'::`dynamic initializer for 'TORCH_LIBRARY_IMPL_static_init_quantized_QuantizedCPU_4''() line 1423	C++
```

The test code is as follows (In this code, no functions related to "libtorch" are called except the header file <torch/torch.h>)：
```
#include <torch/torch.h>
#include <iostream>

int main() {
    std::cout << "hello world!" << std::endl;
    return 0;
}
```

Compile script content:
```
set DEBUG=0
set CONDA_FORCE_32BIT=ON
set USE_CUDA=OFF
set USE_GLOO=OFF
set USE_NINJA=OFF
set BUILD_TEST=OFF
set CAFFE2=OFF
set BUILD_CAFFE2=OFF
set BUILD_CAFFE2_OPS=OFF
set BUILD_PYTHON:BOOL=OFF
set CMAKE_GENERATOR=Visual Studio 16 2019
set CMAKE_GENERATOR_PLATFORM=Win32
set CMAKE_BUILD_TYPE=RelWithDebInfo
set DISTUTILS_USE_SDK=1
conda create -n build_libtorch python=3.8
conda activate build_libtorch
conda install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi typing

cd tools
python build_libtorch.py
```

### Versions

```
(build_libtorch) C:\Users\james\Documents\project\build_pytorch>python collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Professional Edition
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.12 (main, Apr  4 2022, 05:23:19) [MSC v.1916 32 bit (Intel)] (32-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h9f7ea03_640
[conda] mkl-include               2022.0.0           h9f7ea03_115
[conda] mkl-service               2.4.0            py39hc431981_0
[conda] mkl_fft                   1.3.1            py39h116a794_0
[conda] mkl_random                1.2.2            py39hcf78d83_0
[conda] numpy                     1.21.5           py39hf27c404_3
[conda] numpy-base                1.21.5           py39hb79ded8_3
```

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment] 2022-11-21 20:27
Removing "module: crash" as there are no crashes, just compilation errors. 
Please note, that 32-bit build of Pytorch on x86 platform are not supported, so there could be numerous issues associated with it. Just curious, what is the reason for trying to compile PyTorch as 32-bit binary?

**Comment by vladimir-aubrecht** [comment] 2022-11-25 15:24
@neuxys Is there anything preventing you to use one of the supported platforms?

**Comment by neuxys** [comment] 2022-12-03 10:52
> Thanks for your reply. I have used onnx instead of pytorch. In fact, I should not use pytorch as the runtime library.



> Removing "module: crash" as there are no crashes, just compilation errors. Please note, that 32-bit build of Pytorch on x86 platform are not supported, so there could be numerous issues associated with it. Just curious, what is the reason for trying to compile PyTorch as 32-bit binary?

**Comment by neuxys** [comment] 2022-12-03 11:01
> @neuxys Is there anything preventing you to use one of the supported platforms?

Deep question~
At that time, I didn't know which platforms were supported or not. After that, I chose onnx in win32 to run my model.

**Comment by iremyux** [comment] 2023-08-22 08:13
@neuxys 
Since the problem is no longer relevant, may we proceed with closing this issue?

**Comment by seemethere** [comment] 2023-08-24 19:02
I think we can proceed, will close now.

**Closed by seemethere** 2023-08-24 19:02 UTC
Labels: module: build, module: windows, triaged
