### ISSUE TITLE
Torchscript error "Unexpected indent" when lines start with #

### ISSUE THREAD

**Issue by qasfb** [pytorch/pytorch#32489] opened 2020-01-22 13:46 UTC
## 🐛 Bug

Torchscript seems to require comments (in a function) to be indented otherwise it complains with an error message that is not very explicit.

However when you comment stuff (e.g. on a jupyter notebook) the comment symbol can be placed at the beginning of the line. It can be confusing.

## To Reproduce

```
import torch
import torch.nn as nn

class M(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(inputs):
#         some comment
        return inputs

M_instance = M()
torch.jit.script(M_instance)
```

leads to:

```
File "/***/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)

  File "<unknown>", line 1
    def forward(inputs):
    ^
IndentationError: unexpected indent
```

However if I indent my comment it works:

```
import torch

class M(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(inputs):
        #         some comment
        return inputs

M_instance = M()
torch.jit.script(M_instance)

> RecursiveScriptModule(original_name=M)

```

## Expected behavior
I would expect it to simply ignore all lines where the first character is. #

## Environment

 - PyTorch Version (e.g., 1.0): 1.5.0a0-fb

## Additional context

cc @suo

**Comment by ailzhang** [comment] 2020-01-22 21:43
Yea we probably want to fix this.

**Comment by driazati** [comment] 2020-01-23 18:34
Thanks again for the report! This looks like a duplicate of #25043 so closing this one so we only have to track the issue in one place.

**Closed by driazati** 2020-01-23 18:34 UTC
Labels: enhancement, jit
