### ISSUE TITLE
[JIT] torchscript does not support torch.nonzero when as_tuple is True

### ISSUE THREAD

**Issue by chenbohua3** [pytorch/pytorch#38718] opened 2020-05-19 11:35 UTC
## 🐛 Bug

See the codes below.

## To Reproduce

```
# this function f is exported successfully
@torch.jit.script 
def f(x: Torch.Tensor):
    return torch.nonzero(x)
```
When I set as_tuple to True:
```
@torch.jit.script 
def f(x: Torch.Tensor):
    return torch.nonzero(x, as_tuple=True)
```
we will have errors below:
```
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::nonzero.out(Tensor self, *, Tensor(a!) out) -> (Tensor(a!)):
  Argument out not provided.
  
  aten::nonzero(Tensor self) -> (Tensor):
  Keyword argument as_tuple unknown.
```

## Expected behavior

torch.jit.script can handle the situation when as_tuple is True.

## Environment

 - PyTorch Version (e.g., 1.0): master
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): as described in [here](https://github.com/pytorch/pytorch#from-source)
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.0 / 7.6.5

cc @suo

**Comment by suo** [comment] 2020-05-19 18:14
hey @glaringlee, please don't add "triaged" to `jit`-labeled issues, we also use it for our own triage system 😛 thanks!

**Comment by suo** [comment] 2020-05-19 18:14
@eellison is this a case of a python-level argument not being captured by native_Functions?

**Comment by glaringlee** [comment] 2020-05-19 18:44
@suo Sry, I was not aware of it . Removed 'triaged'

**Comment by eellison** [comment] 2020-05-19 18:52
@suo `nonzero` is an example of an op that's registered in python when it shouldn't be, so it's probably implemented only on the python op https://github.com/pytorch/pytorch/issues/30780.

**Comment by eellison** [comment] 2020-05-19 18:56
I think nonzero is also deprecated. A workaround here is to use 
`torch.annotate(List[float], torch.nonzero(x).tolist())`

**Comment by chenbohua3** [comment] 2020-05-20 05:54
@eellison for now I think there seems no workaround to achieve full version of nonzero. I tried to use “JIT-capable” op and 'torch.jit._overload_method" to achieve wrapper of nonzero, but also failed:(
```
@torch.jit._overload_method
    def nonzero_(self, input: torch.Tensor, out: Optional[torch.Tensor] = None, as_tuple: bool = False) -> torch.Tensor:
        pass

    @torch.jit._overload_method
    def nonzero_(self, input: torch.Tensor, out: Optional[torch.Tensor] = None, as_tuple: bool = False) -> List[torch.Tensor]:
        pass

    def nonzero_(self, input: torch.Tensor, out: Optional[torch.Tensor] = None, as_tuple: bool = False):
        if not as_tuple:
            if out is not None:
                return torch.nonzero(input, out=out)
            else:
                return torch.nonzero(input)
        else:
            if input.dim() == 0:
                return input.unsqueeze(0).nonzero().unbind(1)
            return input.nonzero().unbind(1)
```

**Comment by gchanan** [comment] 2020-06-26 15:21
putting 1.6.0 milestone for now; this isn't the worst, but it's a pretty bad user experience.

**Comment by ppwwyyxx** [comment] 2020-09-27 00:27
related: https://github.com/pytorch/pytorch/issues/44284

**Comment by gchanan** [comment] 2020-10-09 20:19
See https://github.com/pytorch/pytorch/pull/45413 for the most up-to-date deprecation plan.  As such, this is no longer a pressing issue and I'll remove the milestone label.

**Comment by ppwwyyxx** [comment] 2020-10-09 20:59
`tensor.nonzero()` still issues warnings in 1.7 due to https://github.com/pytorch/pytorch/pull/45413#issuecomment-703947414. Would be great to remove that warning as well, but perhaps it's too late?

**Comment by rafale77** [comment] 2021-01-27 15:39
On 1.7.1 and am seeing the same problem even with as_tuple = False. Is there any workaround?

**Comment by ngimel** [comment] 2021-01-27 17:12
Closing as dupe of #45499.

**Closed** 2021-01-27 17:13 UTC
Labels: oncall: jit, triaged
