### ISSUE TITLE
M1 Mac: `torch.dot()` returns unexpeted values for tensors of `torch.float32`

### ISSUE THREAD

**Issue by onkyo14taro** [pytorch/pytorch#60351] opened 2021-06-21 07:14 UTC
## 🐛 Bug

When `torch.dot` is given a tensor of `torch.float32`, its output is unexpected value.

## To Reproduce and Expected behavior

Here is an example using tensors generated from `torch.arange()`, but for general tensors of `torch.float32`, `torch.dot()` returns unexpected values.

Inputs:
```python
import torch

N = 100  # this value is arbitrary
print('Expected value :', torch.sum(torch.arange(N).float() * torch.arange(N).float()))  # naive implementation of dot product
print('torch.int      :', torch.dot(torch.arange(N), torch.arange(N)))
print('torch.float64  :', torch.dot(torch.arange(N).double(), torch.arange(N).double()))
print('torch.float32  :', torch.dot(torch.arange(N).float(), torch.arange(N).float()))
```

Outputs:
```
python        : 328350
torch.int     : tensor(328350)
torch.float64 : tensor(328350., dtype=torch.float64)
torch.float32 : tensor(0.)
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): macOS Big Sur 11.4 (**M1** mac)
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Python version: 3.8.10 (with miniforge3-4.10.1-3 & without  miniforge3-4.10.1-3)

## Additional context

I have confirmed that this bug **does NOT occur** in the following environment.

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): macOS Big Sur 11.4 (**Intel** mac)
 - How you installed PyTorch (`conda`, `pip`, source): `pip`
 - Python version: 3.8.10 (without  miniforge3-4.10.1-3)

Therefore, I think this bug might be related to the M1 mac.

cc @malfet @ezyang @seemethere @walterddr @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @IvanYashchuk @xwang233 @Lezcano @albanD

**Comment by Lezcano** [comment] 2021-06-21 15:56
Could you confirm whether PyTorch was built with or without BLAS in the environments that you tried this on (e.g. by doing `print(torch.__config__.show())`)?

I was not able to reproduce this bug with PyTorch with BLAS from mkl.

**Comment by onkyo14taro** [comment] 2021-06-21 17:34
Thanks @Lezcano, here is the results of `print(torch.__config__.show())` in my environment.

PyTorch built with:  
  - GCC 4.2  
  - C++ Version: 201402  
  - clang 12.0.0  
  - CPU capability usage: NO AVX  
  - Build settings: BLAS_INFO=accelerate, BUILD_TYPE=Release, CXX_COMPILER=/Applications/Xcode-12.3.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const, LAPACK_INFO=accelerate, TORCH_VERSION=1.9.0, USE_CUDA=OFF, USE_CUDNN=OFF, USE_EIGEN_FOR_BLAS=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=OFF, USE_MKLDNN=OFF, USE_MPI=OFF, USE_NCCL=OFF, USE_NNPACK=OFF, USE_OPENMP=OFF,

**Comment by malfet** [comment] 2021-06-24 04:28
Can reproduce using official 1.9 binaries, but can not using top-of-tree build

**Comment by malfet** [comment] 2021-06-24 05:14
And crux of the problem is that BLAS_F2C and BLAS_USE_CBLAS_DOT is not defined correctly during cross-compilation :(
```
# Local build
% python -c "import torch;import os; print(open(os.path.join(os.path.dirname(torch.__file__), 'include', 'TH', 'THGeneral.h')).read())"|grep -A2 F2C
#define BLAS_F2C
#define BLAS_USE_CBLAS_DOT
# Nightly binaries
% /usr/bin/python3 -c "import torch;import os; print(open(os.path.join(os.path.dirname(torch.__file__), 'include', 'TH', 'THGeneral.h')).read())"|grep -A2 F2C
/* #undef BLAS_F2C */
/* #undef BLAS_USE_CBLAS_DOT */
```

**Comment by malfet** [comment] 2021-06-25 01:39
Will be fixed in next nightly build

**Closed** 2021-06-25 01:45 UTC
Labels: module: arm, module: binaries, module: correctness (silent), module: linear algebra, module: macos, triaged

**Comment by onkyo14taro** [comment] 2021-06-25 04:58
@malfet Thank you for identifying the cause and fixing it!
