### ISSUE TITLE
Exporting torch.stft and torch.istft to ONNX

### ISSUE THREAD

**Issue by GMPHL** [pytorch/pytorch#65666] opened 2021-09-26 13:00 UTC
how can i put “torch.stft“ and” torch.istft” function into onnx？

cc @BowenBao @neginraoof

**Comment by vadimkantorov** [comment] 2021-09-27 14:52
Related: https://github.com/pytorch/pytorch/issues/31317

**Comment by hwangdeyu** [comment] 2021-09-27 23:57
This is being tracked internally by Microsoft at https://msdata.visualstudio.com/Vienna/_workitems/edit/1429170.

**Comment by thiagocrepaldi** [comment] 2022-02-14 22:05
https://github.com/pytorch/pytorch/pull/62412

@vadimkantorov  does it work for you?

**Comment by vadimkantorov** [comment] 2022-02-14 22:15
I've worked around this problem long time ago by using Conv1d and precomputed basis. You can test if this works by exporting to ONNX one of nvidia's jasper speech recognition models (with frontend)

**Comment by garymm** [comment] 2022-03-01 21:16
Will wait to see these hopefully added to the next ONNX op set by https://github.com/onnx/onnx/pull/3741 or similar.

**Comment by justinchuby** [comment] 2022-09-15 23:44
Duplicate of https://github.com/pytorch/pytorch/issues/81075

**Closed by justinchuby** 2022-09-15 23:44 UTC
Labels: module: onnx, triaged, onnx-triaged

**Comment by ksasso1028** [comment] 2024-04-08 23:32
I have implemented the STFT/ISTFT using 1dconvs from a few different sources but they all seem to differ then the original torch implementation...im processing real/imag parts so have a feeling it has to do with the reconstruction piece.

**Comment by biendltb** [comment] 2025-02-13 16:08
The STFT is already supported in ONNX opset 17 so that we could export `torch.stft()` with `return_complex=False`. However, the iSTFT is not yet supported. Plus, from PyTorch 2.0, complex tensor input is required in `torch.istft()`. This might not be compatible with ONNX and prevent them from supporting `torch.istft()` in the future since they have no plan to support complex tensors in ONNX.

In the meantime, I create this workaround for exporting ISTFT in torch. I've tested the output and they are pretty close to `torch.istft()` implementation. Check it at: https://github.com/biendltb/torch-istft-onnx
