### ISSUE TITLE
Floating point exception when dividing pytorch.tensor() on a float

### ISSUE THREAD

**Issue by caizexin** [pytorch/pytorch#25829] opened 2019-09-08 04:30 UTC
## 🐛 Bug

Core dump when dividing the tensor with a float value obtain from time.time(). 
`Floating point exception (core dumped)`
## To Reproduce
just type torch.tensor(540) / 0.30365729331970215

1. import torch
2. torch.tensor(540) / 0.30365729331970215

## Expected behavior
it works fine when we code 540/ 0.30365729331970215, or torch.tensor(540).data.numpy(). / 0.30365729331970215, the result is 1778.320533969415

## Environment
```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 387.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.1.0
[conda] torch                     1.1.0                     <pip>
```
## Additional context
same at another environment:
```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 418.67
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.1
[pip] torch==1.2.0
[pip] torchvision==0.4.0
[conda] torch                     1.2.0                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi

```

**Comment by Nikronic** [comment] 2019-09-08 12:53
The problem is when you do not specify the `dtype`. If you set `dtype=torch.float32` or `dtype=torch.float64`, it won't throw an error on both `CPU` and `GPU`.
By the way, when I tried to use `dtype=torch.float16`, I got this error:
```
RuntimeError: "div_cpu" not implemented for 'Half'
```
My env:

```shell

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.3.0
[conda] Could not collect
```

**Comment by f2013519** [comment] 2019-09-08 17:17
Notice that the crash doesn't occur if you write something like 

torch.Tensor(540.1)/0.3.

What seems to be happening is torch.Tensor(540) is inferred to be an integer type and not a floating point type.  So integer division is performed which causes denominator to be rounded to zero, causing F.P exception.

Doc states that: "torch.Tensor is an alias for the default tensor type (torch.FloatTensor)." It doesn't seem to be honored here leading to the crash.

**Comment by caizexin** [comment] 2019-09-08 17:51
> Notice that the crash doesn't occur if you write something like
> 
> torch.Tensor(540.1)/0.3.
> 
> What seems to be happening is torch.Tensor(540) is inferred to be an integer type and not a floating point type. So integer division is performed which causes denominator to be rounded to zero, causing F.P exception.

Thanks a lot! I see. However, it did not crash when I tried torch.Tensor(540) / 0.3 or torch.Tensor(540) / 0.337362. So I think the precision of the float number (denominator) causes the exception. As you said, when the precision is too high (like 64bit), it would be rounded to zero.

**Comment by f2013519** [comment] 2019-09-08 18:01
What the "expected" result depends on the semantics of integer division by zero.

 In MATLAB for example, if you try to divide a non-zero integer by a zero integer, the result is the largest integer of that data type.

>> a = int16(10)
>> b = int16(0)
>> c = a  / b

returns 32767.

Python on the other hand returns ZeroDivisionError: division by zero.

I think it wouldn't be too much to ask Pytorch to do the same thing as python, i.e throw a run-time error instead of crashing on us. To do that, someone might need to update BinaryOpsKernel.cpp, for case of integer division.

**Comment by f2013519** [comment] 2019-09-09 04:45
It looks like this isn't that straightforward and that all libraries which have integer division may need to be updated to maintain consistency. This is same as issue #8079 and marked as "wontfix". This is not ideal, but it looks like that is the current situation.

**Comment by ezyang** [comment] 2019-09-09 21:51
Yes, I think this should be resolved in the same way.

**Comment by ezyang** [comment] 2019-09-09 21:51
Actually, @nairbv, does type promotion save us here?

**Comment by nairbv** [comment] 2019-09-11 15:18
> Actually, @nairbv, does type promotion save us here?

was this reported against 1.2 not master right? I'm not able to repro on current master:

```
In [1]: import torch
In [2]: torch.tensor(540) / 0.30365729331970215
Out[2]: tensor(1778.3206)
```

**Comment by fmassa** [comment] 2019-09-11 16:43
The original issue has been fixed in master, but there is still an issue dividing an integer tensor by 0, as discussed in https://github.com/pytorch/pytorch/issues/327
The question is if we want to add checks asserting that the divisor is non zero for integer tensors

**Comment by ezyang** [comment] 2019-09-11 18:58
No, for integer-integer division, this is WONTFIX.

**Closed by ezyang** 2019-09-11 18:58 UTC
Labels: module: operators, topic: type promotion, triaged
