### ISSUE TITLE
How to disable check onnx in torch.onnx.export in pytorch1.11 version?

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#76023] opened 2022-04-19 08:26 UTC
### 📚 The doc issue

Old params were removed, now how to disable check on onnx when export?

### Suggest a potential alternative/fix

Also, why disable this feature? Some onnx using customized op can not pass check.

**Comment by BowenBao** [comment] 2022-04-19 23:24
Hi @jinfagang , consider setting `operator_export_type=OperatorExportTypes.ONNX_FALLTHROUGH`, if you want to skip checker. 

Using customized ops should still pass the check though, as long as their respective domains are recorded in the `graph_proto.opset_import`. This should be covered by exporter by default. Could you share a simple repro for us to have a look?

**Comment by jinfagang** [comment] 2022-04-20 02:43
@BowenBao thanks for your suggestion.

I registered this op in my program (not torch source code):

```
def register_custom_op():

    # code from opset13
    @parse_args("v", "v", "v", "i", "i", "i")
    def fake_quantize_per_channel_affine(
        g, inputs, scale, zero_point, axis, quant_min=-128, quant_max=127
    ):
        if quant_min not in [0, -128] or quant_max not in [127, 255]:
            raise RuntimeError(
                "ONNX defines [0, 255] for quint8 and [-128, 127] for qint8, got [{}, {}]".format(
                    quant_min, quant_max
                )
            )

        # ONNX defines zero_point to be int8 or uint8
        if quant_min == 0:
            zero_point = g.op(
                "Cast", zero_point, to_i=sym_help.cast_pytorch_to_onnx["Byte"]
            )
        else:
            zero_point = g.op(
                "Cast", zero_point, to_i=sym_help.cast_pytorch_to_onnx["Char"]
            )
        return g.op(
            "::FixedPerChannelAffine",
            inputs,
            scale,
            zero_point,
            axis,
            quant_min,
            quant_max,
        )
register_custom_op_symbolic(
        "::_fake_quantize_learnable_per_tensor_affine",
        _fake_quantize_learnable_per_tensor_affine,
        11,
    )
```

but when I export, the checker still claims there is no such op registered, while the onnx can generate (I catch the error and make it won't raise), does there a way to make checker don't raise error? Also ,I dont know why it can not recognise my register

**Comment by BowenBao** [comment] 2022-04-20 17:38
Thanks for sharing. The problem is with
```
        return g.op(
            "::FixedPerChannelAffine",
```
This is setting to export operator in default(ONNX) namespace. To utilize custom operator, the custom namespace needs to be specified. e.g. "custom_domain::FixedPerChannelAffine".

**Comment by garymm** [comment] 2022-05-04 19:52
FYI the latest PyTorch nightly supports `fake_quantize_per_channel_affine` using standard ONNX ops:
https://cs.github.com/pytorch/pytorch/blob/8d31706b9e855a455a49dd0d7b0b368fb8726470/torch/onnx/symbolic_opset13.py?q=fake_quantize_per_channel_affine#L134

@jinfagang is your issue resolved? If so please close this.

**Closed** 2022-05-05 04:57 UTC
Labels: module: onnx, triaged, onnx-needs-info
