### ISSUE TITLE
torch.set_default_tensor_type() changes weights initialization

### ISSUE THREAD

**Issue by polo5** [pytorch/pytorch#32535] opened 2020-01-23 15:46 UTC
## 🐛 Bug

Different tensor types, as set with `torch.set_default_tensor_type` seem to use different seeds to initialize models. This makes it hard to compare the behavior of some code across data types

## To Reproduce

```python
import torch
import torchvision.models as models
import numpy as np
import random

SEED = 0

## FLOAT 32
torch.manual_seed(SEED)
torch.set_default_tensor_type(torch.FloatTensor)

a = torch.randn(1)
print(a) # --> 1.5410
alexnet = models.alexnet(pretrained=False)
for k,v in alexnet.state_dict().items():
    print(k, torch.sum(v)) # --> 3.7782
    break

## FLOAT 64
torch.manual_seed(SEED)
torch.set_default_tensor_type(torch.DoubleTensor)

a = torch.randn(1)
print(a) # --> 1.5410
alexnet = models.alexnet(pretrained=False)
for k,v in alexnet.state_dict().items():
    print(k, torch.sum(v)) # --> 6.9368, but I want this to be ~ 3.7782
    break

```

## Environment

Python 3.6
Pytorch 1.2.0 [cpuonly]

**Comment by albanD** [comment] 2020-01-23 16:07
Hi,

When you generate double numbers, you need more randomness than for a float number. So you won't get the same behavior between the two.
If you want to generate the same numbers, you need to have the same data-type. You can then convert it to float if you want.

Closing this as this is not a bug but expected behavior.
For future reference, you can ask questions on the forum if you're unsure if they are a bug or not: https://discuss.pytorch.org/

**Closed by albanD** 2020-01-23 16:07 UTC

**Comment by polo5** [comment] 2020-01-23 16:11
Thank you. I'd considered this hypothesis which is why I included `torch.rand(1)` which is the same for both data types. So there may be some inconsistency somewhere? 

I will find a workaround for now.

**Comment by albanD** [comment] 2020-01-23 16:49
It may be, by chance, that the `randn` only generates doubles and then truncate them to float if it is what you ask for.
But this is an implementation detail and I don't think you should rely on it because we might optimize the randn implementation in the future to only generate single precision float when a double is not needed.
