### ISSUE TITLE
PYTORCH_TEST_WITH_DYNAMO=1 pytest -n 4 test/test_nestedtensor.py fails

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#110288] opened 2023-09-29 16:11 UTC
Running `PYTORCH_TEST_WITH_DYNAMO=1 pytest -n 4 test/test_nestedtensor.py` causes a non-deterministic number of failures (ranging between 14-70 for me). Perturbing the Dynamo config in CI (e.g. https://github.com/pytorch/pytorch/pull/110107) seems to expose the failures in CI, but CI is otherwise green.  I might disable them for now so that we can land stuff without risking flaky CI. Opening this issue to track the problem.

![image](https://github.com/pytorch/pytorch/assets/5652049/40ae91fa-b8ff-482e-8895-c97e867e912e)

cc @ezyang @gchanan @kadeng @cpuhrsch @jbschlosser @bhosmer @drisspg @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by zou3519** [comment] 2023-09-29 16:15
Hi-pri because I'm about to turn off the PYTORCH_TEST_WITH_DYNAMO=1 nestedtensor tests in https://github.com/pytorch/pytorch/pull/110107 and we don't want to regress nestedtensor Dynamo support

**Comment by cpuhrsch** [comment] 2023-09-29 20:09
cc @soulitzer

**Comment by jbschlosser** [comment] 2023-10-25 17:21
I'm having a hard time reproducing this locally or on a devgpu, but it's clearly a problem based on the number of flaky test issues being opened. @zou3519 does this only happen with your changes in https://github.com/pytorch/pytorch/pull/110107?

**Comment by zou3519** [comment] 2023-10-25 18:35
I'm able to reproduce this without https://github.com/pytorch/pytorch/pull/110107

**Comment by soulitzer** [comment] 2023-11-01 17:29
I was able to reproduce what the ` NYI: aten._nested_tensor_from_tensor_list.default` error message. However, due to `torch._dynamo.config.suppress_errors = True`, this error is suppressed and the test passes. 

In the error message from the description and in this example failure https://ossci-raw-job-status.s3.amazonaws.com/log/17624383025, it appears that the test fails anyway, suggesting that `suppress_errors` is actually `False`.

Looking at places in the code where `suppress_errors` could be switched back to `False`. It looks like this logic https://github.com/pytorch/pytorch/blob/fd209543d5dfced3146d64df3af6361fc61fb74a/torch/_inductor/lowering.py#L1677-L1684 does this.

My guess of what is happening is that this value is not properly reset. And so the errors happens only when specific inductor tests are being run, triggering this logic to run. The fix should be to properly reset the suppress_errors setting after those tests are run.

The fact that we're seeing gradcheck tests failing doesn't make sense to me yet though, maybe thats just a pytest weirdness?

**Comment by ezyang** [comment] 2023-11-02 02:23
cc @wconstab

**Comment by jbschlosser** [comment] 2023-11-07 16:19
Hopefully addressed by #112662.

**Comment by voznesenskym** [comment] 2023-11-13 23:22
@jbschlosser can you confirm please

**Closed** 2023-11-14 00:57 UTC
Labels: high priority, triaged, module: nestedtensor, oncall: pt2
