### ISSUE TITLE
ImportError: DLL load failed: The operating system cannot run %1.

### ISSUE THREAD

**Issue by wuyi1983** [pytorch/pytorch#7579] opened 2018-05-15 15:33 UTC
I just found one opencv version is not compatible with pytorch 0.4.0 on Win 10.
I also got the solution.

## Issue description

After conda install -c conda-forge opencv 
it made the error when 'import torch': 

 File "C:\anaconda2\envs\pytorch\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: The operating system cannot run %1.

#The following one works fine#

conda install -c anaconda opencv

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.60
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by shldngzh** [comment] 2018-05-20 23:27
@wuyi1983 Hi, could you please explain more about why this issue is caused? I got a very similar issue with pytorch 0.4.0 - the same error message saying "the operating system cannot run %1" within import torch, but reinstall pytorch & opencv via conda does not work for me.

**Comment by peterjc123** [comment] 2018-05-21 12:44
@shldngzh May be this one #7458 helps.

**Comment by shldngzh** [comment] 2018-05-22 01:13
@peterjc123 Thanks. 

An update:
This issue is solved by 

1) uninstalling & reinstalling Anaconda 
2) conda update --all

Stil not quite sure what caused it but it looks like the most recent release of Anaconda 5.1 (as of 2018/5/20) is not ready for PyTorch 0.4.0 before you manually update packages by conda update --all.

**Comment by peterjc123** [comment] 2018-05-30 07:37
Guys, thanks to @lchen23, I found the root cause of this issue. It's about intel-openmp. If you installed the conda-forge version, then this issue will emerge. The way to fix it is very simple: `conda install -c defaults intel-openmp -f`.

**Comment by peterjc123** [comment] 2018-05-30 07:45
And actually it was an upstream [issue](https://github.com/conda-forge/openmp-feedstock/issues/8) of Anaconda and has been solved in recent versions.

**Comment by peterjc123** [comment] 2018-05-31 04:34
@soumith Fixed by #7979. Should we close this?

**Comment by soumith** [comment] 2018-05-31 13:03
fixed by https://github.com/pytorch/pytorch/pull/7979

**Closed by soumith** 2018-05-31 13:03 UTC

**Comment by gurpreetshanky** [comment] 2018-06-06 23:11
@peterjc123 Thanks for the solution. Wasted like 2 hours for solution.

**Comment by hemangjoshi37a** [comment] 2018-09-03 16:41
@soumith @peterjc123 @gurpreetshanky 
There is nothing written in #7979 
## Please help me.

**Comment by peterjc123** [comment] 2018-09-03 16:49
@hemangjoshi37a 

> Guys, thanks to @lchen23, I found the root cause of this issue. It's about intel-openmp. If you installed the conda-forge version, then this issue will emerge. The way to fix it is very simple: conda install -c defaults intel-openmp -f.
Have you tried this?

> There is nothing written in #7979
Sure. It is a PR, not a issue. The changes are written in the code, not in the conversions.

>Please help me.
Don't express like this, please. It doesn't help here. You will just have to make the issue clear.

**Comment by futscdav** [comment] 2018-10-31 15:55
I ran into this issue out of the blue, and was really perplexed by the error, I hadn't changed anything in conda or pytorch since last time when it worked.

However, having installed llvm stack, which added itself to PATH, seems to trigger this problem, I suspect it's because it contains omp dlls, and pytorch in conda relies on finding them in a way that is only used after all PATH paths have been exhausted. 

In any case, if anyone runs into this problem, check your PATH for any dlls that may have been added since last torch worked for you.

**Comment by engmubarak48** [comment] 2019-03-06 11:34
> Guys, thanks to @lchen23, I found the root cause of this issue. It's about intel-openmp. If you installed the conda-forge version, then this issue will emerge. The way to fix it is very simple: `conda install -c defaults intel-openmp -f`.

your solution is perfect thanks

**Comment by baggyg** [comment] 2020-01-09 14:45
I am having this issue. I previously had an Anaconda install. I removed everything I didn't need and started fresh just with python + pip + virtualenv. On 2 different environments I installed the CUDA version and non-cuda. Both have this issue.

**Comment by peterjc123** [comment] 2020-01-09 15:25
@baggyg Please see https://github.com/pytorch/pytorch/issues/31324.

**Comment by baggyg** [comment] 2020-01-09 15:40
> @baggyg Please see #31324.

Exactly that same DLL file which was the issue - thank you immensely! I wasn't expecting a reply so soon

**Comment by skycreeper2000** [comment] 2020-06-25 13:24
As per @peterjc123 the below code should work. Do I need to install it in every environment?
 conda install -c defaults intel-openmp -f.

**Comment by charloe12** [comment] 2023-03-20 14:25
peterjc123 thank you for your solution but you can just update anaconda without reinstalling it

**Comment by Sayuksh** [comment] 2024-03-31 12:27
@charloe12 i did that but it didn't help ...

**Comment by Sayuksh** [comment] 2024-03-31 12:28
@skycreeper2000  is your issue resolved if yes how did you do that..
