### ISSUE TITLE
AttributeError: module 'torch' has no attribute 'unique_dim'

### ISSUE THREAD

**Issue by GIS-PuppetMaster** [pytorch/pytorch#62793] opened 2021-08-05 02:35 UTC
## 🐛 Bug

When using `from torch import *`, the error `AttributeError: module 'torch' has no attribute 'unique_dim'` appears.

## To Reproduce

1. install pytorch 1.9.0
2. from torch import *

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: GeForce GTX 1060 6GB
Nvidia driver version: 461.40
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.1
[pip3] numpydoc==1.1.0
[pip3] pytorch-lightning==0.5.2.1
[pip3] torch==1.9.0+cu111
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               11.1.1               heb2d755_7    conda-forge
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py37h196d8e1_0    defaults
[conda] mkl_fft                   1.3.0            py37h46781fe_0    defaults
[conda] mkl_random                1.1.1            py37h47e9c7a_0    defaults
[conda] numpy                     1.21.1                   pypi_0    pypi
[conda] numpy-base                1.18.5           py37hc3f5095_0    defaults
[conda] numpydoc                  1.1.0              pyhd3eb1b0_1    defaults
[conda] pytorch                   1.9.0           py3.7_cuda11.1_cudnn8_0    pytorch
[conda] pytorch-lightning         0.5.2.1                  pypi_0    pypi
[conda] torch                     1.2.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi

## Additional context

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by zou3519** [comment] 2021-08-06 14:42
Triage review because I don't know how to label this.

`from torch import *` should work and we would accept a PR fixing this. I can repro the problem.

**Comment by rudaoshi** [comment] 2021-08-07 06:01
I have the same issue.  Also occurs for version  1.8.1

**Comment by rudaoshi** [comment] 2021-08-07 06:11
I found that the issue is because of the line 

   del torch.unique_dim 

 in  torch/funcitional.py . Comment that line fixes the issue. 

I also found that it has been fixed in the master branch.

**Comment by zou3519** [comment] 2021-08-09 17:11
This doesn't seem fixed on master, high-pri to fix it

**Comment by malfet** [comment] 2021-09-01 18:05
Moving to 1.10 milestone, as this problem existed as far back as  1.6:
```
% python -c 'import torch;print(torch.__version__); from torch import *'
1.6.0
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: module 'torch' has no attribute 'unique_dim'
```

**Closed** 2021-09-15 01:20 UTC
Labels: high priority, triaged, module: ux
