### ISSUE TITLE
pytorch 1.8.0 RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by dany-nonstop** [pytorch/pytorch#53720] opened 2021-03-10 17:39 UTC
## To Reproduce

1. Install pytorch 1.8.0 in virtual environment and activate 
```
python3 -m venv env
source env/bin/activate
```
2. Install pytorch 1.8.0
```
pip install torch==1.8 torchvision
```
3. Run the minimum code below
```python
import torch
import torchvision.models as models
from torch.autograd import Variable

device = 'cuda'
input = torch.rand(16,3,224,224)
input = Variable(input)
input = input.to(device)
model = models.alexnet().to(device)
model(input)
print('done')
```
4. Error produced
```
Traceback (most recent call last):
  File "pytorch-test-gpu.py", line 10, in <module>
    model(input)
  File "/home/user/testcuda/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/yudan/testcuda/env/lib/python3.8/site-packages/torchvision/models/alexnet.py", line 46, in forward
    x = self.features(x)
  File "/home/user/testcuda/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/testcuda/env/lib/python3.8/site-packages/torch/nn/modules/container.py", line 119, in forward
    input = module(input)
  File "/home/user/testcuda/env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/user/testcuda/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 399, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/user/testcuda/env/lib/python3.8/site-packages/torch/nn/modules/conv.py", line 395, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

## Expected behavior

Code should finish silently

## Environment
the environment info  from collect_env.py, it's a little weird to me that cuDNN version is not available.

```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] bert-pytorch==0.0.1a4
[pip3] numpy==1.20.1
[pip3] torch==1.8.0
[pip3] torch-struct==0.5
[pip3] torchtext==0.9.0
[pip3] torchvision==0.9.0
[conda] Could not collect
```

## Additional context

1. However running the code with torch==1.7, or with device='cpu', the code would execute without this error.
```
$ pip install torch==1.7.0 torchvision==0.8
Collecting torch==1.7.0
  Using cached torch-1.7.0-cp38-cp38-manylinux1_x86_64.whl (776.8 MB)
Collecting torchvision==0.8
  Using cached torchvision-0.8.0-cp38-cp38-manylinux1_x86_64.whl (11.9 MB)
Requirement already satisfied: dataclasses in ./env/lib/python3.8/site-packages (from torch==1.7.0) (0.6)
Requirement already satisfied: numpy in ./env/lib/python3.8/site-packages (from torch==1.7.0) (1.20.1)
Requirement already satisfied: future in ./env/lib/python3.8/site-packages (from torch==1.7.0) (0.18.2)
Requirement already satisfied: typing-extensions in ./env/lib/python3.8/site-packages (from torch==1.7.0) (3.7.4.3)
Requirement already satisfied: pillow>=4.1.1 in ./env/lib/python3.8/site-packages (from torchvision==0.8) (8.1.2)
```

2. Using the Ubuntu's Nvidia driver 450 would produce exactly the same error.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @ngimel @aocsa

**Comment by ngimel** [comment] 2021-03-10 20:50
What is your GPU model? Likely related to #53336

**Comment by malfet** [comment] 2021-03-10 22:29
Closing this one as duplicate of #53336, both are caused by pruning sm_75 architecture from cublas and cudnn libraries respectively.

**Closed by malfet** 2021-03-10 22:29 UTC
Labels: high priority, module: cuda, triage review
