### ISSUE TITLE
[inductor][cpu] quantization QAT/PTQ accuracy test meets crash

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#120869] opened 2024-02-29 01:43 UTC
### 🐛 Describe the bug

quantization QAT/PTQ accuracy test meets crash with [2024-02-25 nightly release](https://github.com/pytorch/pytorch/commit/53f5035912dc9736546a512713aeb60896d00027)
```
Traceback (most recent call last):
  File "/workspace/pytorch/inductor_quant_acc.py", line 176, in <module>
    run_model(model, args)
  File "/workspace/pytorch/inductor_quant_acc.py", line 144, in run_model
    quant_output = optimized_model(images)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 455, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/fx/graph_module.py", line 737, in call_wrapped
    return self._wrapped_call(self, *args, **kwargs)
  File "/workspace/pytorch/torch/fx/graph_module.py", line 317, in __call__
    raise e
  File "/workspace/pytorch/torch/fx/graph_module.py", line 304, in __call__
    return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1529, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/workspace/pytorch/torch/nn/modules/module.py", line 1538, in _call_impl
    return forward_call(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 912, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 777, in _convert_frame
    result = inner_convert(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 398, in _convert_frame_assert
    return _compile(
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 669, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 542, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 163, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 507, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2128, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 791, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 754, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2247, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 931, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1102, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1175, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1156, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/__init__.py", line 1730, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1332, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 57, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 879, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 604, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 434, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/runtime_wrappers.py", line 639, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 297, in aot_dispatch_autograd
    compiled_fw_func = aot_config.fw_compiler(fw_module, adjusted_flat_args)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1260, in fw_compiler_base
    return inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/opt/conda/lib/python3.9/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 430, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 698, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1281, in compile_to_fn
    return self.compile_to_module().call
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/graph.py", line 1233, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 2081, in load_by_key_path
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_root/ms/cmszw5bbvro2vrfyqzlvcv4oo2bzbpksugbype5v2vj4de27a6p2.py", line 706, in <module>
    async_compile.wait(globals())
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 2636, in wait
    scope[key] = result.result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/opt/conda/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/conda/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 1993, in load_pybinding
    result = cls.load(source_code + suffix, cuda)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 1867, in load
    compile_file(input_path, output_path, cmd)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 256, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/codecache.py", line 1807, in compile_file
    raise exc.CppCompileError(cmd, output) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CppCompileError: C++ compile error
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>a52607e</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>https://github.com/pytorch/benchmark/commit/1c6dcdc1202f0a66677ec6433860bce6ad21cb51</td>
      <td>/</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>5286f9f</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>a52607e</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0790338</td>
      <td></td>
    </tr>
  </tbody>

</table>
Repro:

python [inductor_quant_acc.py](https://github.com/chuanqi129/inductor-tools/blob/xiangdong/accuracy/scripts/modelbench/inductor_quant_acc.py)
```
prepare dataset like:
wget https://image-net.org/data/ILSVRC/2012/ILSVRC2012_img_val.tar --no-check-certificate
mkdir -p /home/ubuntu/imagenet/val && mv ILSVRC2012_img_val.tar /home/ubuntu/imagenet/val && cd /home/ubuntu/imagenet/val && tar -xvf ILSVRC2012_img_val.tar && rm -f ILSVRC2012_img_val.tar
wget https://raw.githubusercontent.com/soumith/imagenetloader.torch/master/valprep.sh
bash valprep.sh
```
change dataset path at https://github.com/chuanqi129/inductor-tools/blob/xiangdong/accuracy/scripts/modelbench/inductor_quant_acc.py#L59
select model at https://github.com/chuanqi129/inductor-tools/blob/xiangdong/accuracy/scripts/modelbench/inductor_quant_acc.py#L156
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/068659ddc2f3f85afd69d010fcb9d79f90c160e7
[alexnet_quantization_accuracy_crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/14441703/alexnet_quantization_accuracy_crash_guilty_commit.log)
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @WeizhuoZhang-intel @chuanqi129

**Comment by chuanqi129** [comment] 2024-02-29 07:15
Hi @ydwu4, this issue may caused by PR https://github.com/pytorch/pytorch/pull/119732, could you please help to double check it?

**Comment by leslie-fang-intel** [comment] 2024-02-29 08:22
Hi @ydwu4, since `PT2E PTQ/QAT quantization` with `Inductor backend` is a prototype feature released in `PyTorch 2.1/2.2`. If the accuracy has the functional regression, I think we may need to fix it before `PyTorch 2.3 release`. cc @jerryzh168 @supriyar @jgong5.

**Comment by leslie-fang-intel** [comment] 2024-02-29 08:49
Hi @zxd1997066, does this issue only happen when running with accuracy? I mean the performance testcases are fine.

**Comment by zxd1997066** [comment] 2024-02-29 08:56
> Hi @zxd1997066, does this issue only happen when running with accuracy? I mean the performance testcases are fine.

Yes, the performance testcases are fine.

**Comment by ydwu4** [comment] 2024-03-01 17:03
Sorry for the reply. I was on PTO yesterday. Yeah, the commit is mostly a local change in export and the change to split_graph is safe and won't change pre-existing code's behavior.

**Closed** 2024-03-07 06:23 UTC
Labels: oncall: pt2, module: inductor, oncall: cpu inductor
