### ISSUE TITLE
Importing torch breaks skimage.io.imload

### ISSUE THREAD

**Issue by zimmerrol** [pytorch/pytorch#11211] opened 2018-09-04 09:04 UTC
## Issue description

Importing `torch` before importing `PIL` or `skimage` breaks these two libraries in some ways: loading some images is not possible as an exception is caused. This can be solved by executing this *after* the imports

     from PIL import Image, ImageFile
     ImageFile.LOAD_TRUNCATED_IMAGES = True

but this does not seem as the intended behavior.

## Code example

     # executing the code in this order is not working
     import torch
     from skimage import io

     io.imread('image.jpg')

     # executing in this order, it is
     from skimage import io
     import torch

     io.imread('image.jpg')

[This](https://user-images.githubusercontent.com/5895436/45022095-eb42a900-b065-11e8-98b0-37c29ee94bcd.jpg) is the image I used to get the error.

## Stacktrace

```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/skimage/io/_plugins/pil_plugin.py in pil_to_ndarray(image, dtype, img_num)
     52         # this will raise an IOError if the file is not readable
---> 53         image.getdata()[0]
     54     except IOError as e:

~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/PIL/Image.py in getdata(self, band)
   1233 
-> 1234         self.load()
   1235         if band is not None:

~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/PIL/ImageFile.py in load(self)
    253             # still raised if decoder fails to return anything
--> 254             raise_ioerror(err_code)
    255 

~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/PIL/ImageFile.py in raise_ioerror(error)
     58         message = "decoder error %d" % error
---> 59     raise IOError(message + " when reading image file")
     60 

OSError: broken data stream when reading image file

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-3a91e073ace8> in <module>()
      2 from skimage import io
      3 
----> 4 io.imread('image.jpg')

~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/skimage/io/_io.py in imread(fname, as_gray, plugin, flatten, **plugin_args)
     60 
     61     with file_or_url_context(fname) as fname:
---> 62         img = call_plugin('imread', fname, plugin=plugin, **plugin_args)
     63 
     64     if not hasattr(img, 'ndim'):

~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/skimage/io/manage_plugins.py in call_plugin(kind, *args, **kwargs)
    212                                (plugin, kind))
    213 
--> 214     return func(*args, **kwargs)
    215 
    216 

~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/skimage/io/_plugins/pil_plugin.py in imread(fname, dtype, img_num, **kwargs)
     35         with open(fname, 'rb') as f:
     36             im = Image.open(f)
---> 37             return pil_to_ndarray(im, dtype=dtype, img_num=img_num)
     38     else:
     39         im = Image.open(fname)

~/anaconda2/envs/pytorch04/lib/python3.6/site-packages/skimage/io/_plugins/pil_plugin.py in pil_to_ndarray(image, dtype, img_num)
     59                          'Please see documentation at: %s'
     60                          % (image.filename, pillow_error_message, site))
---> 61         raise ValueError(error_message)
     62     frames = []
     63     grayscale = None

ValueError: Could not load "" 
Reason: "broken data stream when reading image file"
Please see documentation at: http://pillow.readthedocs.org/en/latest/installation.html#external-libraries
```

## System Info
```
Collecting environment information...
PyTorch version: 0.5.0a0+0d5e4a2
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 14.04.4 LTS
GCC version: (Ubuntu 4.8.4-2ubuntu1~14.04.4) 4.8.4
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration:
GPU 0: Tesla K40c
GPU 1: GeForce GTX 650

Nvidia driver version: 375.26
cuDNN version: Probably one of the following:
/usr/local/cuda-8.0/lib64/libcudnn.so.6.0.21
/usr/local/cuda-8.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] torch (0.5.0a0+0d5e4a2)
[pip] torchsummary (1.4)
[pip] torchvision (0.2.1)
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] pytorch                   0.4.1           py36_cuda8.0.61_cudnn7.1.2_1  [cuda80]  pytorch
[conda] torch                     0.5.0a0+0d5e4a2           <pip>
[conda] torchsummary              1.4                       <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch

```

**Comment by zou3519** [comment] 2018-09-04 16:28
Can i get a version for skimage and PIL?

In addition, if you could reproduce this in a docker image, this would be immensely helpful.

**Comment by FlashTek** [comment] 2018-09-05 02:27
scikit-image: 0.14.0
pillow: 5.2.0
I'll try to create a docker to reproduce this behavior.

**Comment by ngimel** [comment] 2021-03-13 04:42
Closing due to age

**Closed by ngimel** 2021-03-13 04:42 UTC
