### ISSUE TITLE
Libtorch torch::einsum(...) need support real tensor and complex tensor do einsum. 

### ISSUE THREAD

**Issue by majestichou** [pytorch/pytorch#73958] opened 2022-03-09 03:43 UTC
### 🚀 The feature, motivation and pitch

Now the latest version of Libtorch does not support  real tensor and complex tensor do einsum at the same time.  See the following code:
```
#include <torch/torch.h>
#include <iostream>
int main()
{
    auto a_real = torch::ones({2, 2});
    auto b_real = torch::randn({2, 2});
    auto b_imag = torch::randn({2, 2});
    auto b = torch::complex(b_real, b_imag);
    auto c = torch::einsum("ij,jk->ik", {a_real, b});
    std::cout << torch::real(c) << std::endl;
    return 0;
}
```
The code can compile succussfully but run error. The error information is as follows:
```
terminate called after throwing an instance of 'c10::Error'
  what():  expected scalar type Float but found ComplexFloat
Exception raised from data_ptr<float> at aten/src/ATen/core/TensorMethods.cpp:18 (most recent call first):
```
And if I change the code as follows to make two complex tensor do einsum.
```
#include <torch/torch.h>
#include <vector>
#include <iostream>
#include <chrono>
int main()
{
    auto a_real = torch::ones({2, 2});
    auto a_imag = torch::ones({2, 2});
    auto a = torch::complex(a_real, a_imag);
    auto b_real = torch::randn({2, 2});
    auto b_imag = torch::randn({2, 2});
    auto b = torch::complex(b_real, b_imag);
    auto c = torch::einsum("ij,jk->ik", {a, b});
    std::cout << torch::real(c) << std::endl;
    return 0;
}
```
The above code can run successfully.
### Alternatives

Libtorch torch::einsum(...) need support real tensor and complex tensor do einsum.

**Comment by ngimel** [comment] 2022-03-09 06:44
duplicate of #61909

**Closed by ngimel** 2022-03-09 06:44 UTC

**Comment by majestichou** [comment] 2022-03-09 07:09
> duplicate of #61909

Thanks a lot!
