### ISSUE TITLE
torch.nn.functional inconsistent loss behaviour

### ISSUE THREAD

**Issue by dizcza** [pytorch/pytorch#11175] opened 2018-09-01 17:35 UTC
## Issue description
I noticed that some loss functions in `torch.nn.functional` do tensor broadcasting while other does not.
I started using `cosine_embedding_loss` and was happy because it handles input tensors with (N, F) and (1, F) shapes, where N - number of examples, F - number of features in one example (vector). Then I moved to `mse_loss` and `l1_loss` to check for better results. And I was disappointed to see that the latter both require (N, F) and (N, F) tensors - they do not support tensor broadcasting as `cosine_embedding_loss` does. Now I need to either stack the second tensor N times (and I do not know whether the gradient history is stored if a tensor is copied; in any case it is memory and computationaly inefficient) or implement l1 and l2 losses on my own.

Please, make loss behavior consistent - either all functions require exactly the same shape or handle broadcasting for each of them. Thank you.

## Code example
```
t1 = torch.randn(5,7)
t2 = torch.randn(1,7)
loss_cosine = F.cosine_embedding_loss(t1, t2, target=torch.ones(5))  # works fine
loss_l2 = F.mse_loss(t1, t2)
# RuntimeError: input and target shapes do not match: input [5 x 7], target [1 x 7]
```

- How you installed PyTorch: `conda install pytorch-cpu torchvision-cpu -c pytorch`
- PyTorch version: 0.4.1
- Python version: 3.6.6

**Comment by ailzhang** [comment] 2018-10-23 17:36
This is a duplicate of #12129. I will make a PR for it later today.

**Closed by ailzhang** 2018-10-23 17:36 UTC
Labels: medium priority
