### ISSUE TITLE
NotImplementedErrors in `sparse_coo_tensor`

### ISSUE THREAD

**Issue by ev-br** [pytorch/pytorch#108667] opened 2023-09-06 16:50 UTC
### 🐛 Describe the bug

In https://github.com/pytorch/pytorch/pull/107863, this test fails:

```
PYTORCH_TEST_WITH_DYNAMO=1 python test/test_sparse.py -k test_scalar_cpu
```

What that PR does, https://github.com/pytorch/pytorch/pull/107863 uses `NotImplementedError`s in torch._dynamo to signal a need for a graph break. However, something in sparse emits

```
(Pdb) p e
NotImplementedError('Cannot access storage of SparseTensorImpl')
```

The error does not make it to a user in either eager mode or under compile, so it seems it is used to drive some internal logic. Should it really be a NotImplementedError or maybe it's an AttributeError or some such?

To reproduce the error: insert a breakpoint on top of gh-17863

```diff
$ git diff
diff --git a/torch/_dynamo/utils.py b/torch/_dynamo/utils.py
index 4b243ed3286..f4a578d77d7 100644
--- a/torch/_dynamo/utils.py
+++ b/torch/_dynamo/utils.py
@@ -1412,6 +1412,9 @@ def run_node(tracer, node, args, kwargs, nnmodule):
             assert "example_value" in node.meta
             return node.meta["example_value"]
     except NotImplementedError as e:
+
+        breakpoint()
+
         # NB: mimic how wrap_fake_exception does it
         from .exc import unimplemented
``` 

and then

```
$ PYTORCH_TEST_WITH_DYNAMO=1 python test/test_sparse.py -k test_scalar_cpu
> /home/ev-br/repos/pytorch/torch/_dynamo/utils.py(1419)run_node()
-> from .exc import unimplemented
(Pdb) p e
NotImplementedError('Cannot access storage of SparseTensorImpl')
```

cc @alexsamardzic @nikitaved @pearu @cpuhrsch @amjames @bhosmer @mruberry @rgommers @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @lezcano

### Versions

https://github.com/pytorch/pytorch/pull/107863

**Comment by amjames** [comment] 2023-09-06 17:28
> However, something in sparse emits
> `(Pdb) p e`
> `NotImplementedError('Cannot access storage of SparseTensorImpl')`

That would come from something invoking `t.storage()` with `t` having `sparse_coo` layout. That could be directly or indirectly. 


> The error does not make it to a user in either eager mode or under compile, so it seems it 
 is used to drive some internal logic.

It not making it to the user might be a side effect of one of the test wrappers? In general it should make it to the user, the script below does show the error to the user, so I am not quite sure what you mean. 

```python
import torch
t = torch.randn(10,10).to_sparse_coo().storage()
```
> Should it really be a NotImplementedError or maybe it's an AttributeError or some such? 

The `TensorImpl` [base class](https://github.com/pytorch/pytorch/blob/main/c10/core/TensorImpl.cpp#L594-L597) is where the exception actually comes from. So not just a question about what `SparseTensorImpl` should do with this, but actually all tensor implementations which do not directly carray a reference to storage. 

IMO I don't see any problem with it staying as is, or changing to an AttributeError. It is a function `const Storage& storage() const` which is in fact not implemented. It is also an attribute so I think either would be appropriate. 

Would that be considered BC breaking, to change the specific error type raised here?

**Comment by ev-br** [comment] 2023-09-06 17:41
Thanks @amjames! I guess I wasn't clear: is it intentended that this test https://github.com/pytorch/pytorch/blob/main/test/test_sparse.py#L595
relies on a NotImplementedError somewhere internally?

What I observe in gh-107863 is that if torch.dynamo special-handles NotImplementedError, `a._values().numel()` changes from 1 to 0.

**Comment by amjames** [comment] 2023-09-06 18:15
Ah, Now I am following.

No that test does not rely on the `NotImplementedError`, but dynamo does. Perhaps not specifically that type though. If you run the test under dynamo without your changes dynamo produces several warnings that it can't trace into those regions, the error raised by touching storage is re-wrapped [here](https://github.com/pytorch/pytorch/pull/107863/files#diff-b99ae8eb082046d6353fe4ee536a0d846e1007c7d3b21aefae468ded18fbf13eL1413) eventually is used to produce a warning, but the code executes cleanly and the test passes.

That error was probably captured somewhere above that layer to handle sparse tensors correctly and now the error is not getting there.

**Comment by lezcano** [comment] 2023-09-06 18:35
Ok, @amjames explanation makes sense. My guess is that dynamo calls internally to `storage()` somewhere, and it raises this.

I wouldn't worry too much about this right now, as sparse is not well supported in dynamo. Let's close this for now, as it's not a bug on sparse.

**Closed by lezcano** 2023-09-06 18:35 UTC
Labels: module: sparse, module: numpy, module: dynamo
