### ISSUE TITLE
ONNX: exporting model which uses tensor sizes to compute padding

### ISSUE THREAD

**Issue by oliver-batchelor** [pytorch/pytorch#27838] opened 2019-10-14 10:16 UTC
## 🐛 Bug

My model (for object detection) uses a function which computes padding to trim excess tensor size after pooling with ceil_mode then upsampling gives a size which is off by 1. However pytorch onnx exporter complains that this is a dynamic operation and can't export the model.

## To Reproduce

```

from torch import nn
import torch.nn.functional as F

import torch
import torch.onnx


def match_size_2d(t, sized):
    assert t.dim() == 4 and sized.dim() == 4
    dh = sized.size(2) - t.size(2)
    dw = sized.size(3) - t.size(3)

    pad = (dw // 2, dw - dw // 2, dh // 2, dh - dh // 2)
    return F.pad(t, pad)


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, input):

        x = F.avg_pool2d(input, 2, ceil_mode=True)  
        upscaled = F.interpolate(x, scale_factor=2)

        # input is 51x51, upscaled is 52x52, trim to match
        upscaled = match_size_2d(upscaled, input) 
                
        return torch.cat([input, upscaled], dim=1)

model = MyModel()

dummy = torch.ones((1, 64, 51, 51))
out = model(dummy)
torch.onnx.export(model,               # model being run
                  dummy,                         # model input (or a tuple for multiple inputs)
                  "model.onnx",   # where to save the model (can be a file or file-like object)
                  export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11,          # the ONNX version to export the model to
                  do_constant_folding=True,  # wether to execute constant folding for optimization
                  input_names = ['input'],   # the model's input names
                  output_names = ['output'], # the model's output names
                  dynamic_axes={'input_1':{0:'batch'}})
```

```
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 619, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 123, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 123, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 75, in _parse_arg
    raise RuntimeError("Failed to export an ONNX attribute, "
RuntimeError: Failed to export an ONNX attribute, since it's not constant, please try to make things (e.g., kernel size) static if possible

```

## Expected behavior

Since sizes are constant, they're not actually dynamic - is there a way to work around this restriction?

## Environment

PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 418.87.00
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.6.0.21
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] pytorch-tools==0.1
[pip] pytorchcv==0.0.50
[pip] torch==1.3.0
[pip] torch2trt==0.0.1
[pip] torchvision==0.4.1a0+d94043a
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0           py3.7_cuda10.0.130_cudnn7.6.3_0    pytorch
[conda] pytorch-tools             0.1                       dev_0    <develop>
[conda] pytorchcv                 0.0.50                   pypi_0    pypi
[conda] torch2trt                 0.0.1                    pypi_0    pypi
[conda] torchvision               0.4.1                py37_cu100    pytorch

**Comment by saulzar** [comment] 2019-10-14 10:24
Using this code instead of match_size_2d seems to work in the toy example.

```
@torch.jit.script
def trim_2d(t, sized):
    return t[:, :, :sized.size(2), :sized.size(3)]
```

**Comment by saulzar** [comment] 2019-10-14 10:33
```
@torch.jit.script
def trim_2d(t, sized):
    return t.narrow(2, 0, sized.size(2)).narrow(3, 0, sized.size(3))
```


  File "```
/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 619, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 123, in wrapper
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 123, in <listcomp>
    args = [_parse_arg(arg, arg_desc) for arg, arg_desc in zip(args, arg_descriptors)]
  File "/home/oliver/miniconda3/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py", line 82, in _parse_arg
    raise RuntimeError("Unexpected node type: {}".format(value.node().kind()))
RuntimeError: Unexpected node type: onnx::Gather

```

**Comment by gchanan** [comment] 2019-10-17 17:14
CC @houseroad.

Should you be on the auto-tagger for onnx issues?

**Comment by vincentqb** [comment] 2019-10-17 17:16
See #24422 for auto-tagger

**Comment by houseroad** [comment] 2019-10-17 18:13
cc: @spandantiwari @lara-hdr

**Comment by lara-hdr** [comment] 2019-10-18 05:22
@saulzar you are getting is error because dynamic padding is not yet supported in the exporter.
But there is a PR to support it for opset 11 https://github.com/pytorch/pytorch/pull/28225.

Regarding your comment "upsampling gives a size which is off by 1": are you getting this behavior with opset 11 or with a previous opset version?
We have noted this behavior in some cases with previous opset versions (as explained in: https://github.com/pytorch/pytorch/issues/27176) and we are working on a fix for that as well; there will be a PR very soon.

**Comment by saulzar** [comment] 2019-10-18 06:31
Oh thanks, dynamic padding looks like exactly what is needed. 

My comment about padding being off by 1 is not a bug (that I have noticed so far), but the justification for needing the padding... (once something is downscaled by 2 with ceil mode, an upsampled feature map needs trimming if the original map had an odd dimension).

**Comment by aviaisr** [comment] 2019-11-18 15:17
I think I have the same issue. Used opset 11.
https://github.com/pytorch/pytorch/issues/29993#issue-524345045

**Comment by saulzar** [comment] 2019-11-30 06:42
One question regarding the dynamic padding - is why pytorch is computing dimensions dynamically if the export function does not specify the dimensions as being dynamic?

i.e. in my export function I have:
`dynamic_axes={'input_1':{0:'batch'}})`

So, given that it would seem reasonable if pytorch would convert the shapes (other than the batch) in the output onnx to constants?

**Comment by pfeatherstone** [comment] 2021-01-10 11:00
I think https://github.com/pytorch/pytorch/issues/50348 is related

**Comment by opeide** [comment] 2021-03-09 15:27
Related issue with opset 11. Models with padding are being exported with pad values as non-constant tensors, even though constant-folding is enabled, and the padding is constant in practice. These models are UNUSABLE in tensorrt, which demands constant padding vaues. The only solution I have seen for this is to manually edit the exported model with graphsurgeon, and set the padding to constant. Does anyone know of a better solution, or if a fix is being considered?

**Comment by shubhambhokare1** [comment] 2022-11-15 18:13
Hi @oliver-batchelor,

We’ve gone ahead and closed this issue because it has been resolved elsewhere. This resolution can be found [here](https://github.com/pytorch/pytorch/pull/28225).
If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue.

**Closed by shubhambhokare1** 2022-11-15 18:13 UTC
Labels: module: onnx, feature, triaged
