### ISSUE TITLE
[Bug]BatchNormalization - normalization var and running var are not compatible

### ISSUE THREAD

**Issue by dianyancao** [pytorch/pytorch#19916] opened 2019-04-29 15:32 UTC
## 🐛 Bug

[19920](https://github.com/pytorch/pytorch/issues/19902)
I think this problem 19920 is a bug, because in practice,when the batchnorm use small batchsize and small spatio size, the output will vary large between train model and eval model.
So we don't need to fix this?

**Comment by SsnL** [comment] 2019-04-29 15:35
No it's not a bug. That behavior of BN is exactly what the original paper describes, and is consistent with all the ML framework out there. 

Furthermore, the Bessel's correction is what makes training and eval behavior more similar, rather than more different, as in training you are pretending working on all data to get more proper gradient, and when accumulating running stats you are indeed working with population stats estimators.

**Comment by dianyancao** [comment] 2019-04-29 15:37
But if I test batchnorm with small batchsize and small spatio size,the predict result is wrong.
Follow practice not paper.

**Comment by SsnL** [comment] 2019-04-29 15:39
What do you mean that it is wrong?

And batch size in testing doesn't matter.

> Follow practice not paper.

I also mentioned the common practice....

**Comment by dianyancao** [comment] 2019-04-29 15:39
It harms regression task more than classification task.

**Comment by dianyancao** [comment] 2019-04-29 15:40
> What do you mean that it is wrong?

 if I test batchnorm with few sample, small batchsize and small spatio size,the predict result is wrong

**Comment by SsnL** [comment] 2019-04-29 15:41
I was just asking about what about it is wrong....

**Comment by dianyancao** [comment] 2019-04-29 15:42
Use the following code,reproduce unconsistence result.
```
import torch
import torch.nn as nn
from torch.nn import Parameter, init

class MyBatchNorm(nn.Module):
    _version = 2
    __constants__ = ['track_running_stats', 'momentum', 'eps', 'weight', 'bias',
                     'running_mean', 'running_var', 'num_batches_tracked']

    def __init__(self, num_features, eps=1e-5, momentum=0.1, affine=True,
                 track_running_stats=True):
        super(MyBatchNorm, self).__init__()
        self.num_features = num_features
        self.eps = eps
        self.momentum = momentum
        self.affine = affine
        self.track_running_stats = track_running_stats
        if self.affine:
            self.weight = Parameter(torch.Tensor(num_features))
            self.bias = Parameter(torch.Tensor(num_features))
        else:
            self.register_parameter('weight', None)
            self.register_parameter('bias', None)
        if self.track_running_stats:
            self.register_buffer('running_mean', torch.zeros(num_features))
            self.register_buffer('running_var', torch.ones(num_features))
            self.register_buffer('num_batches_tracked', torch.tensor(0, dtype=torch.long))
        else:
            self.register_parameter('running_mean', None)
            self.register_parameter('running_var', None)
            self.register_parameter('num_batches_tracked', None)
        self.reset_parameters()

    def reset_running_stats(self):
        if self.track_running_stats:
            self.running_mean.zero_()
            self.running_var.fill_(1)
            self.num_batches_tracked.zero_()

    def reset_parameters(self):
        self.reset_running_stats()
        if self.affine:
            init.uniform_(self.weight)
            init.zeros_(self.bias)
        
    def forward(self, input):        
        input_size = input.size()
        input = input.transpose(1,0)
        input = input.view(input.size(0), -1)

        if self.training:
            mean = input.mean(dim=1)
            var = torch.var(input,dim=1, unbiased=True)
            self.running_mean[:] = (1. - self.momentum) * self.running_mean + self.momentum * mean
            self.running_var[:] = (1. - self.momentum) * self.running_var + self.momentum * var
        else:
            mean = self.running_mean
            var = self.running_var

        input = input - mean.view(-1,1)
        input = input / (torch.sqrt(var+self.eps).view(-1,1))
       
        input = self.weight.view(-1, 1) * input + self.bias.view(-1, 1)
        input = input.transpose(1,0)
        input = input.view(*input_size)
        return input

    def extra_repr(self):
        return '{num_features}, eps={eps}, momentum={momentum}, affine={affine}, ' \
               'track_running_stats={track_running_stats}'.format(**self.__dict__)

    def _load_from_state_dict(self, state_dict, prefix, local_metadata, strict,
                              missing_keys, unexpected_keys, error_msgs):
        version = local_metadata.get('version', None)

        if (version is None or version < 2) and self.track_running_stats:
            # at version 2: added num_batches_tracked buffer
            #               this should have a default value of 0
            num_batches_tracked_key = prefix + 'num_batches_tracked'
            if num_batches_tracked_key not in state_dict:
                state_dict[num_batches_tracked_key] = torch.tensor(0, dtype=torch.long)

        super(MyBatchNorm, self)._load_from_state_dict(
            state_dict, prefix, local_metadata, strict,
            missing_keys, unexpected_keys, error_msgs)

def test_batch_norm():
    momentum = 1.0
    torch.manual_seed(1234)

    batch_norm = MyBatchNorm(3,eps=1e-5,momentum=momentum,affine=True,track_running_stats=True)
    n1 = batch_norm
    torch.save(n1.state_dict(),'n1.pth')
    
    torch_batch_norm = nn.BatchNorm1d(3,eps=1e-5,momentum=momentum,affine=True,track_running_stats=True)
    n2 = torch_batch_norm
    n2.load_state_dict(torch.load('n1.pth'))
    
    x = torch.FloatTensor([[1,2,3], [3,4,0], [3,3,1]])
    y = torch.FloatTensor([[2], [3], [1]])
    criterion = nn.MSELoss()

    x = x.cuda()
    y = y.cuda()
    batch_norm.cuda()
    torch_batch_norm.cuda()

    print('Switch to eval mode.')
    batch_norm.eval()
    torch_batch_norm.eval()
    out1 = n1(x)
    out2 = n2(x)
    eval1 = (torch.abs(out2-out1).sum().item() < 1e-4)

    print('Swtich to train mode.')
    batch_norm.train()
    torch_batch_norm.train()

    out1 = n1(x)
    out2 = n2(x)
    train2 = (torch.abs(out2-out1).sum().item() < 1e-4)

    print('Switch to eval mode.')
    n1.eval()
    n2.eval()
    print('MyBatchNorm:')
    print('running_mean:',batch_norm.running_mean.cpu().numpy())
    print('running_var:',batch_norm.running_var.cpu().numpy())
    print('weight:',batch_norm.weight.data.cpu().numpy())
    print('bias:',batch_norm.bias.data.cpu().numpy())
    print()
    
    print('TorchBatchNorm:')
    print('running_mean:',torch_batch_norm.running_mean.cpu().numpy())
    print('running_var:',torch_batch_norm.running_var.cpu().numpy())
    print('weight:',torch_batch_norm.weight.data.cpu().numpy())
    print('bias:',torch_batch_norm.bias.data.cpu().numpy())
    out1 = n1(x)
    out2 = n2(x)
    eval3 = (torch.abs(out2-out1).sum().item() < 1e-4)
    print('eval1,train2,eval3:',eval1,train2,eval3)
    assert eval1 and train2 and eval3

if __name__ == '__main__':
    test_batch_norm()
```

**Comment by SsnL** [comment] 2019-04-29 15:43
yeah, because you did not implement BN, but just a variant of it.

**Comment by SsnL** [comment] 2019-04-29 15:44
I thought you figured out that BN normalizes using batch variance in training, and use population variance estimation in testing, no?

**Comment by dianyancao** [comment] 2019-04-29 15:46
Yes, then it will cause problem.
The above code,assert error message:
```
Switch to eval mode.
Swtich to train mode.
Switch to eval mode.
MyBatchNorm:
running_mean: [2.3333335 3.        1.3333334]
running_var: [0.8888889 0.6666667 1.5555557]
weight: [0.02897924 0.40189856 0.25984418]
bias: [0. 0. 0.]

TorchBatchNorm:
running_mean: [2.3333333 3.        1.3333334]
running_var: [1.3333334 1.        2.3333333]
weight: [0.02897924 0.40189856 0.25984418]
bias: [0. 0. 0.]
eval1,train2,eval3: True True False
Traceback (most recent call last):
  File "test_batch_norm_minimal.py", line 145, in <module>
    test_batch_norm()
  File "test_batch_norm_minimal.py", line 142, in test_batch_norm
    assert eval1 and train2 and eval3
AssertionError

```

**Comment by SsnL** [comment] 2019-04-29 15:48
I know. They are different because they have different arithmetics. You can't expect two different formulas to give same results.

**Comment by dianyancao** [comment] 2019-04-29 15:55
I set batchnorm momentum to 1.0,then test batchnorm with eval and then train mode.
The model output is not close.So when use it in regression task,it will harm performance.
test output:
```
Switch to eval mode.
Swtich to train mode.
Switch to eval mode.
MyBatchNorm:
running_mean: [2.3333335 3.        1.3333334]
running_var: [0.8888889 0.6666667 1.5555557]
weight: [0.02897924 0.40189856 0.25984418]
bias: [0. 0. 0.]

TorchBatchNorm:
running_mean: [2.3333333 3.        1.3333334]
running_var: [1.3333334 1.        2.3333333]
weight: [0.02897924 0.40189856 0.25984418]
bias: [0. 0. 0.]
eval1,train2,eval3: True True False
Traceback (most recent call last):
  File "test_batch_norm_minimal.py", line 150, in <module>
    test_batch_norm()
  File "test_batch_norm_minimal.py", line 148, in test_batch_norm
    assert torch.abs(torch_train_out - torch_eval_out).sum().item() < 1e-4
AssertionError
```
test code:
```
import torch
import torch.nn as nn
from torch.nn import Parameter, init

class MyBatchNorm(nn.Module):
    _version = 2
    __constants__ = ['track_running_stats', 'momentum', 'eps', 'weight', 'bias',
                     'running_mean', 'running_var', 'num_batches_tracked']

    def __init__(self, num_features, eps=1e-5, momentum=0.1, affine=True,
                 track_running_stats=True):
        super(MyBatchNorm, self).__init__()
        self.num_features = num_features
        self.eps = eps
        self.momentum = momentum
        self.affine = affine
        self.track_running_stats = track_running_stats
        if self.affine:
            self.weight = Parameter(torch.Tensor(num_features))
            self.bias = Parameter(torch.Tensor(num_features))
        else:
            self.register_parameter('weight', None)
            self.register_parameter('bias', None)
        if self.track_running_stats:
            self.register_buffer('running_mean', torch.zeros(num_features))
            self.register_buffer('running_var', torch.ones(num_features))
            self.register_buffer('num_batches_tracked', torch.tensor(0, dtype=torch.long))
        else:
            self.register_parameter('running_mean', None)
            self.register_parameter('running_var', None)
            self.register_parameter('num_batches_tracked', None)
        self.reset_parameters()

    def reset_running_stats(self):
        if self.track_running_stats:
            self.running_mean.zero_()
            self.running_var.fill_(1)
            self.num_batches_tracked.zero_()

    def reset_parameters(self):
        self.reset_running_stats()
        if self.affine:
            init.uniform_(self.weight)
            init.zeros_(self.bias)
        
    def forward(self, input):        
        input_size = input.size()
        input = input.transpose(1,0)
        input = input.view(input.size(0), -1)

        if self.training:
            mean = input.mean(dim=1)
            var = torch.var(input,dim=1, unbiased=False)
            self.running_mean[:] = (1. - self.momentum) * self.running_mean + self.momentum * mean
            self.running_var[:] = (1. - self.momentum) * self.running_var + self.momentum * var
        else:
            mean = self.running_mean
            var = self.running_var

        input = input - mean.view(-1,1)
        input = input / (torch.sqrt(var+self.eps).view(-1,1))
       
        input = self.weight.view(-1, 1) * input + self.bias.view(-1, 1)
        input = input.transpose(1,0)
        input = input.view(*input_size)
        return input

    def extra_repr(self):
        return '{num_features}, eps={eps}, momentum={momentum}, affine={affine}, ' \
               'track_running_stats={track_running_stats}'.format(**self.__dict__)

    def _load_from_state_dict(self, state_dict, prefix, local_metadata, strict,
                              missing_keys, unexpected_keys, error_msgs):
        version = local_metadata.get('version', None)

        if (version is None or version < 2) and self.track_running_stats:
            # at version 2: added num_batches_tracked buffer
            #               this should have a default value of 0
            num_batches_tracked_key = prefix + 'num_batches_tracked'
            if num_batches_tracked_key not in state_dict:
                state_dict[num_batches_tracked_key] = torch.tensor(0, dtype=torch.long)

        super(MyBatchNorm, self)._load_from_state_dict(
            state_dict, prefix, local_metadata, strict,
            missing_keys, unexpected_keys, error_msgs)

def test_batch_norm():
    momentum = 1.0
    torch.manual_seed(1234)

    batch_norm = MyBatchNorm(3,eps=1e-5,momentum=momentum,affine=True,track_running_stats=True)
    n1 = batch_norm
    torch.save(n1.state_dict(),'n1.pth')
    
    torch_batch_norm = nn.BatchNorm1d(3,eps=1e-5,momentum=momentum,affine=True,track_running_stats=True)
    n2 = torch_batch_norm
    n2.load_state_dict(torch.load('n1.pth'))
    
    x = torch.FloatTensor([[1,2,3], [3,4,0], [3,3,1]])
    y = torch.FloatTensor([[2], [3], [1]])
    criterion = nn.MSELoss()

    x = x.cuda()
    y = y.cuda()
    batch_norm.cuda()
    torch_batch_norm.cuda()

    print('Switch to eval mode.')
    batch_norm.eval()
    torch_batch_norm.eval()
    out1 = n1(x)
    out2 = n2(x)
    eval1 = (torch.abs(out2-out1).sum().item() < 1e-4)

    print('Swtich to train mode.')
    batch_norm.train()
    torch_batch_norm.train()

    out1 = n1(x)
    out2 = n2(x)
    train2 = (torch.abs(out2-out1).sum().item() < 1e-4)

    print('Switch to eval mode.')
    n1.eval()
    n2.eval()
    print('MyBatchNorm:')
    print('running_mean:',batch_norm.running_mean.cpu().numpy())
    print('running_var:',batch_norm.running_var.cpu().numpy())
    print('weight:',batch_norm.weight.data.cpu().numpy())
    print('bias:',batch_norm.bias.data.cpu().numpy())
    print()
    
    print('TorchBatchNorm:')
    print('running_mean:',torch_batch_norm.running_mean.cpu().numpy())
    print('running_var:',torch_batch_norm.running_var.cpu().numpy())
    print('weight:',torch_batch_norm.weight.data.cpu().numpy())
    print('bias:',torch_batch_norm.bias.data.cpu().numpy())
    out1 = n1(x)
    out2 = n2(x)
    eval3 = (torch.abs(out2-out1).sum().item() < 1e-4)
    print('eval1,train2,eval3:',eval1,train2,eval3)
    #assert eval1 and train2 and eval3

    n2.eval()
    torch_eval_out = n2(x)
    n2.train()
    torch_train_out = n2(x)
    assert torch.abs(torch_train_out - torch_eval_out).sum().item() < 1e-4
if __name__ == '__main__':
    test_batch_norm()

```

**Comment by dianyancao** [comment] 2019-04-29 15:55
the final test only test pytorch batchnorm

**Comment by dianyancao** [comment] 2019-04-29 16:14
BatchNorm some how like parameter reinitialization and refinement.
So near model convergence, one can use model.eval() continue for training with some epoch.
This time the problem comes, but if use popular variance also in training mode,there is no large error.

**Comment by fmassa** [comment] 2019-04-29 16:57
Batch Norm is known to give bad results during training in the small batch regime, see https://arxiv.org/abs/1607.06450 and https://arxiv.org/abs/1803.08494

GIven that this is a known aspect of `BatchNorm`, and not a bug in PyTorch, I'm closing this issue.

**Closed by fmassa** 2019-04-29 16:57 UTC

**Comment by wangguanan** [comment] 2020-09-30 09:08
when computing running_var, we need unbiased var estimated.\
like this

```
            self.running_mean = (1 - self.momentum) * self.running_mean + self.momentum * mean
            self.running_var = (1 - self.momentum) * self.running_var + self.momentum * var * bs / (bs-1)
```
