### ISSUE TITLE
tensor.numpy() does not convert cuda tensor to cpu tensor automatically.

### ISSUE THREAD

**Issue by Kyeongpil** [pytorch/pytorch#54401] opened 2021-03-22 05:51 UTC
## 🚀 Feature
Unlike tensor.tolist(), tensor.numpy() does not convert cuda tensor to cpu tensor automatically.

## Motivation
Unlike tensor.tolist(), tensor.numpy() does not convert cuda tensor to cpu tensor automatically.

For convenience, tensor.numpy() should call cpu() function when the tensor is cuda tensor type
For example)

## Pitch
It would be more convenient to directly use tensor.numpy() than tensor.cpu().numpy().

## Additional context

<img width="1188" alt="스크린샷 2021-03-22 오후 2 49 24" src="https://user-images.githubusercontent.com/6302455/111945927-ee1b2180-8b1d-11eb-8ba1-af224362c6e5.png">

cc @mruberry @rgommers @heitorschueroff

**Comment by martinPasen** [comment] 2021-03-22 11:05
Hey, I had a similar experience and I would appreciate it, if it would be automated. I can try to make it work. Should I just try to make it now and try to get PR accepted, or should I wait for reviewers to say that this is desired?

**Comment by heitorschueroff** [comment] 2021-03-22 16:57
I think this is a good feature request, @ngimel what do you think?

**Comment by mruberry** [comment] 2021-03-22 17:16
Thanks for the request, @Kyeongpil.

This is by design. We would accept a "force" kwarg, though. See https://github.com/pytorch/pytorch/issues/36560, and please comment there so we can keep the discussion in one place. Closing this in favor of the older issues.

**Closed by mruberry** 2021-03-22 17:16 UTC
Labels: enhancement, module: numpy, triaged

**Comment by Kyeongpil** [comment] 2021-06-20 09:49
@heitorschueroff @mruberry Thank you for considering my proposal :)

**Comment by mruberry** [comment] 2021-06-21 01:43
You're welcome, and look like someone is working on adding the "force" kwarg now, too
