### ISSUE TITLE
Seg Fault when using more than one layer in torch.nn.GRU

### ISSUE THREAD

**Issue by Wahou** [pytorch/pytorch#6627] opened 2018-04-16 13:33 UTC
- using PyTorch
- OS: Ubuntu 17.10
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: 3.6.4
- CUDA/cuDNN version: not using gpu 
- GPU models and configuration: not using gpu
- GCC version (if compiling from source):
- CMake version:
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

- A script to reproduce the bug. Please try to provide as minimal of a test case as possible.
Here is a minimal code to reproduce the bug (with 10 hidden layers) :

```python
import torch
from torch.autograd import Variable
import random

class GRU(torch.nn.Module):

    def __init__(self):

        self.d_data = 9
        self.d_out = 5
        self.d_hidden = 8
        nb_hidden_layers = 10
        super(GRU, self).__init__()
        self.input_size = self.d_data + self.d_hidden

        self.gru_layer = torch.nn.GRU(self.input_size, self.d_hidden, nb_hidden_layers, batch_first=True)
        self.output_layer = torch.nn.Linear(self.d_hidden, self.d_out, bias=False)

    def forward(self, x):
        hidden = Variable(torch.zeros(len(x), self.d_hidden))

        input = torch.cat((x, hidden), 1)
        input = input.unsqueeze(0)
        print(input.size())
        output, hidden = self.gru_layer(input)
        output = self.output_layer(output)
        output = output.squeeze(0)
        return output

    def fit(self):

        X = list()
        Y = list()

        for i in range(0, 1000):
            sizes = range(500)
            seq_size = random.choice(sizes)
            X.append(Variable(torch.rand(seq_size, 9)))
            label = random.choice([0,1,2,3,4])
            Y.append(Variable(torch.Tensor([label] * seq_size).long()))

        batch_size = 10

        criterion = torch.nn.CrossEntropyLoss(size_average=False)
        optimizer = torch.optim.Adagrad(self.parameters(), lr=0.01)
        epochs = 1
        for t in range(epochs):
            batch_count = 0
            batch_x = list()
            batch_y = list()

            for x, y in zip(X, Y):
                batch_x.append(x)
                batch_y.append(y)
                batch_count += 1

                if batch_count == batch_size:
                    x = torch.cat(batch_x)
                    y = torch.cat(batch_y)
                    y_pred = self(x)
                    loss = criterion(y_pred, y)

                    # Zero gradients, perform a backward pass, and update the weights.
                    optimizer.zero_grad()
                    loss.backward(retain_graph=True)
                    optimizer.step()

                    batch_count = 0
                    batch_x = list()
                    batch_y = list()
model = GRU()
model.fit()
```

- Error messages and/or stack traces of the bug 
segmentation fault (core dumped) (no other error message)

- Context around what you are trying to do : 
I'm trying to train a simple GRU (torch.nn.gru() ) on sequential data. My program works fine when I'm only using a one layered GRU. As soon as I put more layers, the program crashes when computing the criterion at the second computation of the criterion.

**Comment by zou3519** [comment] 2018-04-16 13:46
@Wahou thank you for your report and the reproduction script. I have reproduced the segfault on 0.3.1 and on master.

**Comment by SsnL** [comment] 2018-04-16 14:09
FYI The cause is https://github.com/pytorch/pytorch/issues/5534, we are looking into possible solutions.

**Comment by SsnL** [comment] 2018-04-16 14:09
Thanks for reporting, and I'll close this in favor of https://github.com/pytorch/pytorch/issues/5534.

**Closed by SsnL** 2018-04-16 14:09 UTC
Labels: crash
