### ISSUE TITLE
core dumped with logic_xor 

### ISSUE THREAD

**Issue by zoux1a** [pytorch/pytorch#117627] opened 2024-01-17 10:29 UTC
### 🐛 Describe the bug

Associate with #117624 , #117624 is about function `logic_or`.
```
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, input, other, out):
        input = torch.logical_xor(input=input, other=other, out=out)        
        return input

x = torch.rand([1, 2, 1, 4, 9, 7], dtype=torch.float32)
y = torch.rand([1, 2, 1, 4, 9, 7], dtype=torch.float32)
z = torch.rand([1, 2, 1, 4, 9, 7], dtype=torch.float16)

model = Model().to(torch.device('cpu'))
eag = model(x, y, z)
opt = torch.compile(model.forward, mode='reduce-overhead')(x, y, z)
```
error stacktrace 
```
free(): invalid pointer
Aborted (core dumped)
```

### Versions

...

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

**Comment by mikaylagawarecki** [comment] 2024-01-17 21:46
Seems to be compile related as commenting out the line with the `torch.compile` this runs

**Comment by jgong5** [comment] 2024-01-18 07:37
Related to fp16 legalization. Assign to @zhuhaozhe

**Comment by xmfan** [comment] 2024-01-18 18:40
Issue is also reproducible on cuda, changing above repro to: `model = Model().to(torch.device('cuda'))`. Issue goes away when we change float16 to float32

**Comment by zhuhaozhe** [comment] 2024-01-19 05:50
PR submitted https://github.com/pytorch/pytorch/pull/117830

**Comment by zhuhaozhe** [comment] 2024-01-23 09:01
Should be fixed by https://github.com/pytorch/pytorch/pull/117830. Feel free to re-open if you find it still not work.

**Closed by zhuhaozhe** 2024-01-23 09:01 UTC
Labels: high priority, triage review, triaged, oncall: pt2, module: inductor, oncall: cpu inductor
