### ISSUE TITLE
Convolution result inconsistent [bug]

### ISSUE THREAD

**Issue by ybzhou** [pytorch/pytorch#9326] opened 2018-07-10 22:38 UTC
## Issue description
2d Convolution result is inconsistent when applied to the full input as compared to partial input.

Provide a short description.
convolve on a 2D in put of WxH should have the same results when convolved on the full input as compared to convolved to the partial input, if one makes sure the corresponding input is the same for the same location output at partial and full convolution.

For example, if I convolve on a 180x110 image, with 11x11 filter with stride 1, the result should be a 170 x 100 output (lets call this one original output). If instead of convolving the whole image, I first convolve on the left 180x100 pixels, it should result a 170 x 90 output, which should match the 1st to 90th of the original output, i.e original[:,:90]. Then if I shift this window by 10 pixels, the resulting output should match with the 10th to 100th of the original output, i.e. original[:,10:]. However, the result does not match. See following example.

## Code example
```
import torch
import numpy as np


def test_conv():
    print("test conv")
    with torch.no_grad():
        W = 180
        F = 20
        B = 16
        H = 110
        x = torch.rand(B, 1, W, H)
        conv_layers = [
            torch.nn.Conv2d(1, F, (31, 11), (1, 1), ),
        ]
        conv = torch.nn.Sequential(*conv_layers)
        conv.eval()
        fx = conv(x)
        print(fx.shape)
        first_fx = conv(x[:, :, :, :100])
        second_fx = conv(x[:, :, :, 10:])
        for i in range(90):
            print(i, np.array_equal(fx[:, :, :, i], first_fx[:, :, :, i]))
        assert np.array_equal(fx[:, :, :, :90], first_fx),(
                        "first, diff:{}".format(
                            np.abs(fx[:, :, :, :90] - first_fx).max()
                        ))
        for i in range(90):
            print(i, np.array_equal(fx[:, :, :, i + 10],
                                    second_fx[:, :, :, i]))
        assert np.array_equal(fx[:, :, :, 10:], second_fx), (
                        "second diff:{}".format(
                            np.abs(fx[:, :, :, 10:] - second_fx).max()
                        ))


if __name__ == '__main__':
    torch.manual_seed(123)
    test_conv()
```

print outs:
```
0 True
1 True
...
81 True
82 False
83 False
84 False
85 False
86 False
87 False
88 False
89 False
```
## System Info
```
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.13.5
GCC version: (GCC) 4.8.5
CMake version: version 3.8.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] msgpack-numpy (0.4.3)
[pip] numpy (1.14.3)
[pip] numpydoc (0.8.0)
[pip] pytorch-ctc (0.1)
[pip] torch (0.4.0)
[pip] torchaudio (0.1)
[pip] torchtext (0.2.1)
[pip] torchvision (0.2.1)
[pip] warpctc-pytorch (0.1)
[conda] pytorch                   0.4.0           py36_cuda0.0_cudnn0.0_1    pytorch
[conda] pytorch_ctc               0.1                       <pip>
[conda] torchaudio                0.1                       <pip>
[conda] torchtext                 0.2.1                     <pip>
[conda] torchvision               0.2.1                    py36_1    pytorch
[conda] warpctc_pytorch           0.1                       <pip>
```

**Comment by albanD** [comment] 2018-07-11 10:45
Hi,

Running your code on python 2.7 from master gives only `True`s.
Could you install from master and verify if this has been fixed in master?

**Comment by ybzhou** [comment] 2018-07-11 18:32
did you test on MacOS? I tested with both python 3.6.5 and 3.6.6 from conda and get the same problem. The code passes on Linux though.

**Comment by ybzhou** [comment] 2018-07-11 18:40
In addition, if I change W to 161, on Linux it also fails. I would think it will fail on more values of W and different kernel sizes.

**Comment by bhushan23** [comment] 2018-07-12 07:07
I am able to repro issue with Python 3.6 TOT master 
But, I mismatch is at different place than stated above but consistent across runs.
Understanding the root cause

**Comment by SsnL** [comment] 2018-07-18 16:03
i can't reproduce this on latest master. it only gives True for me too.

**Comment by SsnL** [comment] 2018-07-27 14:36
Hi @ybzhou , how large is the difference? If it is small, it might be expected due to algorithm and precision issue.

**Comment by ybzhou** [comment] 2018-07-27 16:20
I did not get time to test on the latest master yet, will update this issue once I have time to test on the current master

**Comment by marii-moe** [comment] 2018-08-02 23:31
Looked into this one a bit and was able to reproduce it on my machine, I have not updated to the latest master. 

For a single array element after the convolution, here are some of the values I got: 

> 0 Difference:1.1920928955078125e-07 First:1.072272777557373 Original:1.0722728967666626
> 1 Difference:2.9802322387695312e-08 First:0.210195392370224 Original:0.2101954221725464
> 2 Difference:2.2351741790771484e-08 First:-0.06564547121524811 Original:-0.06564544886350632
> 3 Difference:5.960464477539063e-08 First:0.03386092185974121 Original:0.033860981464385986
> 4 Difference:-5.21540641784668e-08 First:-0.008438542485237122 Original:-0.0084385946393013
> 5 Difference:2.9802322387695312e-08 First:0.20290322601795197 Original:0.20290325582027435
> 6 Difference:5.960464477539063e-08 First:0.1302279829978943 Original:0.13022804260253906
> 7 Difference:-4.470348358154297e-08 First:-0.1371903419494629 Original:-0.13719038665294647
> 8 Difference:-2.9802322387695312e-08 First:-0.4632949233055115 Original:-0.46329495310783386
> 9 Difference:0.0 First:0.09715934097766876 Original:0.09715934097766876
> 10 Difference:-1.4901161193847656e-08 First:0.17278563976287842 Original:0.17278562486171722
.....I let this run for a bit
> 

Which would line up with the "it might be expected due to algorithm and precision issue"

This seems to most frequently happen in the lower right hand corner of the convolution's output for some reason.

**Comment by SsnL** [comment] 2018-08-06 17:50
@marii-moe Thanks for providing the results! I think this is indeed due to algorithmic and precision differences.

**Closed by SsnL** 2018-08-06 17:50 UTC
Labels: todo
