### ISSUE TITLE
System memory leak with mixed precision training

### ISSUE THREAD

**Issue by FabianIsensee** [pytorch/pytorch#40911] opened 2020-07-02 12:44 UTC
Hi there,
training a 2D U-Net with the new torch.cuda.amp package results in a system memory (RAM, not GPU memory) leak. Specifically, at every validation at the end of an epoch, and only if `with autocast(True):` is used, the memory utilization of the main python process jumps by 600-700MB until the entire system memory is full and the process is killed. This does not happen when `with autocast(False):` is used.

Here is some information that I think could be crucial in identifying the problem:
-  it does not happen on every system: 
    - It happens consistently on Ubuntu 18.04 and 20.04. I have been using RTX 2080 ti on both systems. Some users of my framework for medical image segmentation (nnU-Net) have also reported out of memory issues and they have also had Ubuntu as their OS (https://github.com/MIC-DKFZ/nnUNet/issues/209, https://github.com/MIC-DKFZ/nnUNet/issues/187)
    - it does not happen on CentOS 7, tested GPUs are TitanX, TitanXp, V100, 2080 ti and RTX Titan
- the same out of memory leak happens when using Nvidia apex/amp (https://github.com/NVIDIA/apex/tree/master/apex/amp). In fact, I hoped that switching to pytorch amp may resolve this issue, which it did not
- tested with the most recent pytorch nightly, the issue may be around for longer, though! 

I have created a small example that reproduces this issue. It uses some of my codebase, but setting up a test environment should be very easy:

Test environment setup
```bash
virtualenv -p python3 test_venv
test_venv/bin/activate
pip install numpy
pip install --upgrade --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cu101/torch_nightly.html
pip install nnunet  # you can ignore the pillow version mismatch error!
```

Then run the following script:
```python
from nnunet.network_architecture.generic_UNet import Generic_UNet
from nnunet.network_architecture.initialization import InitWeights_He
from nnunet.training.loss_functions.dice_loss import DC_and_CE_loss
from torch import nn
from torch.cuda.amp import autocast, GradScaler
from torch.optim import SGD
import numpy as np
import torch


def dummy_dl(batch_size, patch_size, data_channels, num_classes):
    data = np.random.random((batch_size, data_channels, *patch_size))
    seg = np.random.uniform(0, num_classes-1, (batch_size, 1, *patch_size)).round()
    data_torch = torch.from_numpy(data).float()
    seg_torch = torch.from_numpy(seg).float()
    while True:
        yield data_torch, seg_torch


def main():
    patch_size = [320, 256]
    batch_size = 40
    data_channels = 1
    num_classes = 2

    model = Generic_UNet(data_channels, 16, num_classes, 6, 2, 2, nn.Conv2d, nn.InstanceNorm2d,
                         {'eps': 1e-05, 'affine': True}, nn.Dropout2d,
                         {'p': 0, 'inplace': True}, nn.LeakyReLU, {'negative_slope': 0.01, 'inplace': True}, False,
                         False, lambda x: x, InitWeights_He(1e-2), [[2, 2], [2, 2], [2, 2], [2, 2], [2, 2], [2, 2]],
                         [[3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3], [3, 3]], False, True, True, 512)
    model = model.cuda()
    optimizer = SGD(model.parameters(), 0.01, 0.99, nesterov=True, weight_decay=3e-5)

    dl = dummy_dl(batch_size, patch_size, data_channels, num_classes)
    dl_val = dummy_dl(batch_size, patch_size, data_channels, num_classes)

    loss_fn = DC_and_CE_loss({'batch_dice': True, 'smooth': 1e-5, 'do_bg': False}, {})

    scaler = GradScaler()
    for ep in range(1000):
        print(ep)
        losses_train = []
        for batch in range(30):
            optimizer.zero_grad()

            data, seg = next(dl)
            data = data.cuda()
            seg = seg.cuda()

            with autocast():
                output = model(data)
                loss = loss_fn(output, seg)

            scaler.scale(loss).backward()
            #loss.backward()

            scaler.step(optimizer)
            #optimizer.step()

            scaler.update()

            losses_train.append(loss.item())
        print(np.mean(losses_train))

        losses_val = []
        with torch.no_grad():
            for batch in range(30):
                data, seg = next(dl_val)
                data = data.cuda()
                seg = seg.cuda()

                with autocast(True):
                    output = model(data)
                    loss = loss_fn(output, seg)
                losses_val.append(loss.item())
        print(np.mean(losses_val))


if __name__ == "__main__":
    main()
```

This does nothing more than instantiate a 2D U-Net and then running a dummy training that keeps reusing the same data and seg tensors. Every time the validation code runs, the system memory consumption increases by 600-700MB. If you set `with autocast(False):` in the validation run, the issue disappears. 

It would be great if you could look into this!

Best,
Fabian

PS: PDF with the network architecture is available here:
[network_architecture.pdf](https://github.com/pytorch/pytorch/files/4864285/network_architecture.pdf)

cc @ezyang @gchanan @zou3519 @mcarilli @ngimel

**Comment by FabianIsensee** [comment] 2020-07-02 16:40
Interestingly this does not happen with the nvcr.io/nvidia/pytorch:20.06-py3 docker

**Comment by albanD** [comment] 2020-07-06 17:33
Someone from nvidia will take a first look at this as the amp module is actively being worked on.

**Comment by FabianIsensee** [comment] 2020-07-07 05:51
Sounds great. If there is anything I can do please let me know.

**Comment by mcarilli** [comment] 2020-07-08 16:18
> the same out of memory leak happens when using Nvidia apex/amp

With apex amp, did you also observe a system/CPU memory leak, as opposed to a GPU-side memory leak?

Does it have anything to do with the `no_grad()` interaction?  can you try running the eval like an ordinary forward pass, not under `with no_grad()` and see if it persists?  I don't know why this would affect it, but it's a useful data point.

Does running `gc.collect()` after each iteration during eval have any effect?

Do you observe the memory use creeps up gradually during eval iterations, or is it one big jump every time you begin eval?  Or is it unclear?

**Comment by FabianIsensee** [comment] 2020-07-09 06:41
> With apex amp, did you also observe a system/CPU memory leak, as opposed to a GPU-side memory leak?

With apex I observe exactly the same behavior. The GPU memory is normal, no leak there. It's all RAM.

> Does it have anything to do with the `no_grad()` interaction? can you try running the eval like an ordinary forward pass, not under `with no_grad()` and see if it persists? I don't know why this would affect it, but it's a useful data point.

When I remove `with torch.no_grad():` the problem still persists but only ~130MB of memory leak each time the validation runs.

> Does running `gc.collect()` after each iteration during eval have any effect?

Running `gc.collect()` after each iteration works and the memory leak is gone. Not sure what the impact on validation speed is, though.
Interestingly, placing the `gc.collect()` after the validation (as opposed to in each iteration) has no effect and the problem persists.

> Do you observe the memory use creeps up gradually during eval iterations, or is it one big jump every time you begin eval? Or is it unclear?

It creeps up gradually. Another interesting observation: The amount of memory the leaks is proportional to the number of validation batches. If I increase the number of batches from 30 to 60 the amount of memory the leaks is doubled, too.

Have you been able to reproduce the problem with the code I posted above?

Best,
Fabian

**Comment by mcarilli** [comment] 2020-07-09 23:26
Ran your repro for 100 iterations, but the issue does not appear to reproduce in my environment (Ubuntu 16.04, python 3.7.7).  I'll try it in an 18.04 container.

**Comment by FabianIsensee** [comment] 2020-07-12 10:56
I have validated it again with the most recent pytorch nightly. The problem is still there (Ubuntu 18.04 and 20.04). Maybe try the 20.06-py3 docker (upgrade pytorch to latest nightly) to reproduce it.

**Comment by tsaizhenling** [comment] 2020-07-12 23:45
I am observing the same issue using a different trainer: https://github.com/ultralytics/yolov5
I'm on Ubuntu 20.04 LTS + pytorch nightly
`gc.collect()` did not help for me

**Comment by FabianIsensee** [comment] 2020-07-13 08:17
@tsaizhenling could you try to run my snipped from above and give feedback whether it also causes memory leaks for you? What GPU are you using? It could be that this issue is not only related to Ubuntu but also Turing GPUs

**Comment by FabianIsensee** [comment] 2020-07-20 06:30
@mcarilli : One of my users (https://github.com/MIC-DKFZ/nnUNet/issues/187#issuecomment-660114827) noted that the memory leak (this code has apex, but it's the same problem) does not occur on Ubuntu 16 which is in line with Your observation from above. Ubuntu 18 and 20 are still affected

**Comment by mcarilli** [comment] 2020-07-24 05:33
I just installed 20.04 so ill retry.

**Comment by FabianIsensee** [comment] 2020-07-24 05:35
Thanks! So far everyone who reported problems had a 2080ti, so it could be
that the problem appears only with Turing or maybe even just the 2080ti

**Comment by FabianIsensee** [comment] 2020-07-24 07:57
Here is a video of the leak in action :-)

https://www.youtube.com/watch?v=aqn_4bZIWCA&feature=youtu.be

**Comment by FabianIsensee** [comment] 2020-08-20 12:37
Hi @mcarilli , have you had the chance to work on this yet? If you need anything please let me know.
Best,
Fabian

**Comment by FabianIsensee** [comment] 2020-09-14 11:44
Update: When compiling pytorch from source with cuDNN 8.0.2 the problem goes away (tested on Ubuntu 20.04 and 18.04 with RTX 2080ti).
Any idea what has changed?

**Comment by mcarilli** [comment] 2020-10-05 16:52
@ptrblck recently installed a 2080 for our team to test on, but by that time you already noticed the cudnn update fixed the problem.

I have no idea what changed in cudnn.  Tracking it down could be a substantial effort.  Since gc.collect() fixes the problem, Amp isn't holding onto hard references over time, and there's a known fix outside of Amp, so i'm closing this for now.  If the fix doesn't work for anyone else, please reopen.

**Closed by mcarilli** 2020-10-05 16:52 UTC
Labels: high priority, module: amp (automated mixed precision), module: cuda, topic: memory usage, triaged
