### ISSUE TITLE
weird bug of torchscript: it thinks my python bool is a tensor but it's not

### ISSUE THREAD

**Issue by ChenchaoZhao** [pytorch/pytorch#41536] opened 2020-07-16 15:54 UTC
## 🐛 Bug

TorchScript assumed my python bool was a tensor though I clearly declared the type to be python bool

## To Reproduce

TorchScript Errors are usually very informative.

EMPTY_FLOAT = torch.zeros(0).float()

class Bug(nn.Module):

    def __init__(self):
        super(Bug, self).__init__()

    def forward(self,
                my_bool: bool,
                x=EMPTY_FLOAT):

        if my_bool:
            y = x
        else:
            y = EMPTY_FLOAT
Then run

bug = Bug()
bug_script = torch.jit.script(bug)
Then comes the compile time error

RuntimeError: 
python value of type 'Tensor' cannot be used as a value:
  File "<ipython-input-310-549c5631a7a3>", line 15
    
        if my_bool:
        ~~~~~~~~~~~...  <--- HERE
            
            y = x
The problem seems to be EMPTY_FLOAT if I use torch.zeros(0).float() instead it compiles correctly.

## Expected behavior

<!-- A clear and concise description of what you expected to happen. -->

## Environment

torchversion 1.4.0

## Additional context

<!-- Add any other context about the problem here. -->


cc @ezyang @gchanan @zou3519 @suo @gmagogsfm

**Comment by gmagogsfm** [comment] 2020-07-16 19:24
Thanks for reporting this bug. I can still reproduce it at head of master, marking as high priority.

**Comment by gmagogsfm** [comment] 2020-07-17 05:52
Looked a bit more into this, the error is actually just a red-herring. The error expr range is supposed to be entire if-else statement rather than just the condition of if.

Therefore, it is in fact complaining about EMPTY_FLOAT can not be used as a value. I crafted a smaller repro to make this more obvious:https://gist.github.com/gmagogsfm/cd43932f6d42b8caf059f52b09bdb228

Will look into it more tomorrow.

**Comment by gmagogsfm** [comment] 2020-07-17 22:37
I think this is working as intended (other than the confusing error expr range issue).

EMPTY_FLOAT is a mutable tensor outside of the scripted function, TorchScript wouldn't know how to deal with it. Think about the case where you save this model on disk and another program loads it back. This second program doesn't have access to the EMPTY_FLOAT object in the first program. Therefore TorchScript is being conservative here.

With that being said, I assume your intention is actually to use the value of EMPTY_TENSOR as constant. In that case, I would suggest adding EMPTY_TENSOR as another functional argument.

@suo, any better suggestions?

**Comment by ChenchaoZhao** [comment] 2020-07-17 23:15
right. that's how i fixed the issue. 
torchscript error messages are usually not informative at all.

**Comment by gmagogsfm** [comment] 2020-07-18 00:42
Indeed. Sorry for the confusion. I have filed a github issue to track the problem we are seeing about confusing error highlighting to make sure it is kept on our radar.

https://github.com/pytorch/pytorch/issues/41617

Closing this issue.

**Closed by gmagogsfm** 2020-07-18 00:42 UTC
Labels: high priority, jit, triage review
