### ISSUE TITLE
rocm support for windows

### ISSUE THREAD

**Issue by johnnynunez** [pytorch/pytorch#106161] opened 2023-07-27 20:19 UTC
### 🚀 The feature, motivation and pitch

https://github.com/RadeonOpenCompute/ROCm/discussions/2347 now it's avaible

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by yamfun** [comment] 2023-07-28 13:04
"[saadrahim]
From a technical standpoint, there are a few PyTorch build dependencies that need enablement on Windows such as MIOpen. Until the prerequisites are ported to Windows, pytorch support will not be possible."

😭😭😭

**Comment by johnnynunez** [comment] 2023-07-29 13:18
> "[saadrahim] From a technical standpoint, there are a few PyTorch build dependencies that need enablement on Windows such as MIOpen. Until the prerequisites are ported to Windows, pytorch support will not be possible."
> 
> 😭😭😭

https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2272 here

**Comment by hongxiayang** [comment] 2023-08-08 16:24
Windows Support for PyTorch is currently not available. This includes WSL2 based workflows.
AMD is continuing to invest in Windows support including the PyTorch ecosystem.
For details or future updates, please check: https://rocm.docs.amd.com/en/latest/rocm.html#rocm-on-windows

**Comment by khirasier** [comment] 2023-09-11 05:06
will we be getting windows rocm support in pytorch 2.1?

**Comment by KawaiiSelbst** [comment] 2023-09-21 08:03
> will we be getting windows rocm support in pytorch 2.1?

Выше же уже писали, что не хватает MIOpen, придётся дождаться, пока с ним наконец разберутся, до этого момента команда Pytorch физически не может осуществлять поддержку ROCm на Windows.
Следите за PR в MIOpen
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2272

**Comment by malfet** [comment] 2023-11-15 00:37
Closing as duplicate of https://github.com/pytorch/pytorch/issues/109204

(I wish there was a way to move discussion to the same issue)

**Closed by malfet** 2023-11-15 00:37 UTC
Labels: module: windows, module: rocm, triaged, enhancement
