### ISSUE TITLE
Inconsistent type conversion across add and mul when exporting to onnx

### ISSUE THREAD

**Issue by shawn-g-hu** [pytorch/pytorch#20941] opened 2019-05-25 00:25 UTC
## 🐛 Bug

Conversion to ONNX seems to export some constants as type float and some as type double. 

This part is not strictly your responsibility, but this causes type issues when trying to convert the ONNX model to other deep learning frameworks.

## To Reproduce

Here is a (mostly) minimal program. This was tested on the latest nightly, as well as 1.0.0 and 1.1.0.

```

class BugDemonstrator0(nn.Module):

    def __init__(self):
        super().__init__()

    def forward(self, features, x): 
        dtype = torch.float
        slice_1 = x[:, 3]
        slice_2 = x[:, 2]
        y1 = features[:, :, 0] - ( 
                slice_1.to(dtype).unsqueeze(1) * 0.16 - 69.04)
        return y1


device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
pytorch_model = BugDemonstrator0().to(device)

features = torch.rand(12000, 100, 4).to(device)                                                                                                                                                                 
x = torch.rand(12000, 4).to(device)

inputs = [features, x]
input_names = ['x']
output_names = ['stack']

torch.onnx.export(pytorch_model, tuple(inputs), "test_voxelnet.onnx", verbose=True, input_names=input_names, output_names=output_names)
```

The verbose output of the export is as follows:
```
graph(%x : Float(12000, 100, 4),
      %1 : Float(12000, 4)):
  %2 : Long() = onnx::Constant[value={3}](), scope: BugDemonstrator0
  %3 : Float(12000!) = onnx::Gather[axis=1](%1, %2), scope: BugDemonstrator0
  %4 : Tensor = onnx::Slice[axes=[2], ends=[1], starts=[0]](%x), scope: BugDemonstrator0
  %5 : Float(12000, 100!) = onnx::Squeeze[axes=[2]](%4), scope: BugDemonstrator0
  %6 : Float(12000!) = onnx::Cast[to=1](%3), scope: BugDemonstrator0
  %7 : Float(12000!, 1) = onnx::Unsqueeze[axes=[1]](%6), scope: BugDemonstrator0
  %8 : Tensor = onnx::Constant[value={0.16}]()
  %9 : Tensor = onnx::Mul(%7, %8)
  %10 : Tensor = onnx::Constant[value={69.04}]()
  %11 : Tensor = onnx::Sub(%9, %10)
  %stack : Float(12000, 100) = onnx::Sub(%5, %11), scope: BugDemonstrator0
  return (%stack)
```

Loading the onnx model and printing the verbose graph shows that %8 is of type float whereas %11 is of type double. Furthermore, inspection with pdb shows that the types of the args to mul() and add() in symbolic_opset9.py are different . While I can imagine legitimate reasons that that may happen, it suggests to me that there could be some flaws in the type inference logic.

Casting the constants to tensors and explicitly casting the tensors to type torch.float32 do not solve the problem.

## Expected behavior

Both constants should be exported to the same type in the ONNX graph, preferably float32.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 -Collecting environment information...
PyTorch version: 1.1.0.dev20190523
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: Tesla V100-SXM2-16GB
Nvidia driver version: 410.104
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.3.1

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] torch-nightly==1.1.0.dev20190523
[pip3] torchvision==0.2.2.post3

## Additional context

This seems like it might be related to #18281

cc @BowenBao @neginraoof

**Comment by houseroad** [comment] 2019-05-30 22:38
Yeah, this is known issue, one workaround for now it's using tensor factories such as torch.ones(..., dtype=...) to create the right type.

**Comment by WilliamZhaoz** [comment] 2019-09-20 08:42
Hi, I hit the same bugs, It is difficult to find the key operation where the problem is. Help. How can I fix this problem.

**Comment by shawn-g-hu** [comment] 2019-09-20 20:45
hey william, i was only able to hack around this issue very naively with the following:

i went straight to the source file for the add function in the symbolic logic files: this should be in a directory somewhere like usr/local/lib/python3.6/dist-packages/torch/onnx/ , and the contents of that directory should vary depending on what version of pytorch you're using. Then, wherever the definition of add() is, i simply did this:

```
#print (type(self))
    #print (type(other))
    if isinstance(other, torch.Tensor) and other.dtype == torch.float64:
        other = other.float()   
```
to directly coerce the types and "fix" the broken logic. this might have to be done in a slightly different way depending on what your error is, though

**Comment by garymm** [comment] 2021-09-21 00:48
@shawn-g-hu with your example, everything seems to be float using torch 1.9.0. Can you check if this is still an issue?
If it is, can you please include code that clearly shows the problem, perhaps using the onnx library to load the model proto?

**Comment by thiagocrepaldi** [comment] 2022-01-03 20:36
It’s been over 2 months, so closing this. Feel free to open another one.

**Closed by thiagocrepaldi** 2022-01-03 20:36 UTC
Labels: module: onnx, triaged, onnx-needs-info

**Comment by EmreOzkose** [comment] 2022-07-21 10:53
I have the same issue. Is there any progress?
