### ISSUE TITLE
multi_head_attention_forward tests input equality with torch.equal() which might return false negatives

### ISSUE THREAD

**Issue by ifeherva** [pytorch/pytorch#37508] opened 2020-04-29 16:19 UTC
## 🐛 Bug

multi_head_attention_forward(..) computes the keys, queries, values based on the whether the same inputs are passed for the respective function arguments. As seen here:
https://github.com/pytorch/pytorch/blob/master/torch/nn/functional.py#L3834
this test is done by torch.equal() which often returns false even for torch.equal(x, x) due to potential numerical instability.

Would it make sense to replace torch.equal() with something like torch.allclose() to fix this behavior?

**Comment by pbelevich** [comment] 2020-05-01 18:15
@zhangguanheng66 WDYT?

**Comment by zhangguanheng66** [comment] 2020-05-01 18:46
@ifedan The line lined above is confused. Could you double check?

**Comment by bhosmer** [comment] 2021-05-11 19:43
@ifeherva good point, but I think the issue is moot after #56674, which dispenses with the equality test and checks only for identity. Rationale being that testing for value equality is expensive and in the general case is purely sunk cost, and since output is the same along all paths (mod numerical stability), we're free to choose a sweet spot when it comes to optimizing the self-attention case.

**Comment by bhosmer** [comment] 2021-05-11 22:41
@ifeherva closing the issue per above comment, but feel free to reopen if you see problems with the current solution!

**Closed by bhosmer** 2021-05-11 22:41 UTC
Labels: module: numerical-stability, oncall: transformer/mha, triaged
