### ISSUE TITLE
`torch.as_strided` can create a tensor with negative dimension

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#70672] opened 2022-01-05 11:16 UTC
### 🐛 Describe the bug

`torch.as_strided` can create a tensor with negative dimension

```python
import torch
a = torch.rand([3, 3])
b = torch.as_strided(a, [1, -1], [1, 1])
print(b.shape)
# torch.Size([1, -1])
```

### Versions

pytorch: 1.10.1

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by albanD** [comment] 2022-01-06 13:56
The fun part is that trying to print it fails with `Trying to create tensor with negative dimension -1: [1, -1]`.

We should definitely raise an error in this case!

**Comment by dagitses** [comment] 2022-01-10 18:20
We would accept a PR, we expect this to be a simple fix. Please reach out if you are interested.

**Comment by kdesai2018** [comment] 2023-01-13 23:19
@dagitses I'd like to try putting up a PR for this!

**Comment by kdesai2018** [comment] 2023-01-14 19:53
@dagitses @albanD newbie question here. I can repro this issue with a fresh conda install of PyTorch 1.10.1. I'm not sure how to develop on this version of PyTorch though, since the instructions in [Contributing.md](https://github.com/pytorch/pytorch/blob/master/CONTRIBUTING.md#instructions) just seem to install torch 2.0.0. 

How could I install the older version of PyTorch in a way where I can test/reproduce this issue? And given that, would I make a PR merge back into master, or an older release branch for 1.10.1? I'm happy to come to office hours next week if that's a better way to get some help.

**Comment by albanD** [comment] 2023-01-17 16:58
Hi,
We do not backport bug fixes into older version. So there will not be 1.10.1.
To develop new patch, you should install from source as described in the contributing doc. That will give you the latest version. You can then do your changes in a branch and open a PR for it.

**Comment by kshitij12345** [comment] 2023-02-08 06:07
On latest master,
```
import torch
a = torch.rand([3, 3])
b = torch.as_strided(a, [1, -1], [1, 1])  # Errors : `RuntimeError: Storage size calculation overflowed with sizes=[1, -1] and strides=[1, 1]`
```

**Comment by dagitses** [comment] 2023-02-08 17:11
@albanD looks like this is fixed now?

**Closed by dagitses** 2023-02-08 17:11 UTC
Labels: high priority, module: error checking, triaged, module: correctness (silent)
