### ISSUE TITLE
Possible bug in rnn.py

### ISSUE THREAD

**Issue by wcneill** [pytorch/pytorch#41363] opened 2020-07-13 19:46 UTC
## 🐛 Bug

Two related bugs, as far as I can tell:

**1.** Calling `torch.tensor()` on a NumPy ndarray with `dtype=float64` randomly results in a tensor with `dtype=torch.float32` or `dtype=torch.float64`, regardless of the datatype of the ndarray. This behavior is counter to the documentation, which states:

> **dtype** (torch.dtype, optional) – the desired data type of returned tensor. Default: if None, infers data type from data.

**2.** Given a ndarray `x` with `dtype=float64` that we wish to convert to a tensor for feed-forward through an RNN layer, if `torch.tensor(x)` does not result in a tensor with `dtype=torch.float32`, then feed-forward fails. 

Because there is nothing in the documentation to specify that `float32` is required for feed-forward, this seems to be a bug in the code or perhaps just an overlooked piece of necessary information that should be included in the documentation. 

## To Reproduce

1. Define and initialize a simple RNN class:
```
class simpleRNN(nn.Module):
    def __init__(self, input_size, hidden_size, num_layers, output_size):
        super().__init__()
    
        self.hidden_size = hidden_size
        self.rnn = nn.RNN(input_size, hidden_size, num_layers, batch_first=True)
        self.fc  = nn.Linear(hidden_size, output_size)
        
    def forward(self, x, hs):
        
        # forward pass thru RNN layer
        rnn_out, hidden = self.rnn(x, hs)
        
        # reshape RNN output for input to FC layer
        rnn_out = rnn_out.view(-1, self.hidden_size)
        
        # forward pass thru FC layer
        output = self.fc(rnn_out)
        
        # return prediction and updated hidden state
        return output, hidden

input_size  = 1
hidden_size = 10
num_layers  = 2
output_size = 1

test_model = simpleRNN(input_size, hidden_size, num_layers, output_size)        
```

2. Generate sequence `x` of 20 data points (results in float64 array):
```
# Data gen 1: 
seq_len = 20

time = np.linspace(0, np.pi, seq_len + 1)
data = np.sin(time)

x = data[:-1]
y = data[1:]

test_input_1 = x.reshape((seq_len, 1)) 
test_input_1 = torch.tensor(test_input_1).unsqueeze(0) 

print(time.dtype)
print(data.dtype)
print(x.dtype)
print(test_input_1.dtype)
```

3. Generate sequence `x` of different 20 data points in an identical manner (results in float32):
```
# Data gen 2:
seq_len = 20

time = np.linspace(0, np.pi, seq_len)
data = np.sin(time)

test_input_2 = data.reshape((seq_len, 1))
test_input_2 = torch.Tensor(test_input_2).unsqueeze(0) # give it a batch_size of 1 as first dimension

print(time.dtype)
print(data.dtype)
print(test_input_2.dtype)
```

4. Call forward on both inputs:
```
test_model(test_input_2, hs=None)
test_model(test_input_1, hs=None)
```

The above code will result in expected behavior for `test_input_2` but will result in the following stack trace for `test_input_1`:

```
c:\users\wesle\appdata\local\programs\python\python38\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

<ipython-input-41-0cd36896dead> in forward(self, x, hs)
     12 
     13         # forward pass thru RNN layer
---> 14         rnn_out, hidden = self.rnn(x, hs)
     15 
     16         # reshape RNN output for input to FC layer

c:\users\wesle\appdata\local\programs\python\python38\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    548             result = self._slow_forward(*input, **kwargs)
    549         else:
--> 550             result = self.forward(*input, **kwargs)
    551         for hook in self._forward_hooks.values():
    552             hook_result = hook(self, input, result)

c:\users\wesle\appdata\local\programs\python\python38\lib\site-packages\torch\nn\modules\rnn.py in forward(self, input, hx)
    225         _impl = _rnn_impls[self.mode]
    226         if batch_sizes is None:
--> 227             result = _impl(input, hx, self._flat_weights, self.bias, self.num_layers,
    228                            self.dropout, self.training, self.bidirectional, self.batch_first)
    229         else:

RuntimeError: Expected object of scalar type Double but got scalar type Float for argument #3 'mat2' in call to _th_addmm_out
```

## Expected behavior

The expected behavior is simply that calling `forward(test_input_1)` results in the same behavior as `forward(test_input_2)`

## Environment

PyTorch version: 1.5.1+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Home
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] torch==1.5.1+cpu
[pip3] torchvision==0.6.1+cpu
[conda] Could not collect

cc @albanD @mruberry

**Comment by mruberry** [comment] 2020-07-16 05:30
This reproduces. You have a spelling error: `torch.Tensor()` is used to create the second tensor, which is why it's the wrong dtype. The model still won't work as written, however, because the model's weights are created in the default scalar type (float32). You can make them double by replacing your model construction line with:

```
test_model = simpleRNN(input_size, hidden_size, num_layers, output_size).double()
```

Those two changes should make your example pass.

Aside: I wonder if we should throw a warning when `torch.Tensor` is used?

**Comment by albanD** [comment] 2020-07-16 14:55
As mentionned above, the second return a float32 because you don't use the same function to convert to a Tensor. And `torch.Tensor()` never detects the type and always return a Tensor of the default Tensor dtype (float32 by default).

For the rnn model (just like all models), the Parameters are created with the default dtype (float32) again here.
If you want to change that, you can call `model.to(dtype=float64)`.
But you need to make sure that input dtype and network dtype match.

Also note that you can do `torch.tensor(test_input_1, dtype=torch.float32)` if you want to make sure of the dtype you get when converting as mentioned in the doc.


I'm going to close this as this is all expected behavior.
Don't hesitate to ask any follow up question you have on the forum: https://discuss.pytorch.org/

**Closed by albanD** 2020-07-16 14:55 UTC
Labels: module: nn, triaged
