### ISSUE TITLE
expected ) but found 'ident' here: quantized::fake_quantize_per_tensor_affine_forward

### ISSUE THREAD

**Issue by nazarblch** [pytorch/pytorch#20804] opened 2019-05-22 10:57 UTC
## 🐛 Bug

Got an error after transition from cuda 9.0 to 10.1.  The error occurs when I call methods from shared library built with cmake.   

## To Reproduce
 

```
cmake_minimum_required(VERSION 3.5.1)
project(java_torch_lib)

set(PROJECT_VERSION_MAJOR 0)
set(PROJECT_VERSION_MINOR 0)
set(PROJECT_VERSION_PATCH 0)

set(CMAKE_CXX_STANDARD 14)

find_package(Torch REQUIRED)

message (STATUS "TORCH_LIBRARIES=${TORCH_LIBRARIES}")
message (STATUS "TORCH_INCLUDE_DIRS=${TORCH_INCLUDE_DIRS}")

include_directories(${TORCH_INCLUDE_DIRS})

find_package(JNI)

if (${JNI_FOUND})
    message (STATUS "JNI_INCLUDE_DIRS=${JNI_INCLUDE_DIRS}")
    message (STATUS "JNI_LIBRARIES=${JNI_LIBRARIES}")
endif()

include_directories(${JNI_INCLUDE_DIRS})

set (LIB_NAME ${PROJECT_NAME}${PROJECT_VERSION_MAJOR})
add_library(${LIB_NAME} SHARED jnijavacpp.cpp java_torch_lib.cpp)
target_link_libraries(${LIB_NAME}  "${TORCH_LIBRARIES}")
target_link_libraries(${LIB_NAME} ${JNI_LIBRARIES})
```

THE ERROR:

When I execute any method from the builded ${LIB_NAME}

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  expected ) but found 'ident' here:
quantized::fake_quantize_per_tensor_affine_forward(Tensor X, float scale, int zero_point, int num_bits = 8, int quant_delay = 0, int iter = 0) -> Tensor
                                                                                                            ~~~ <--- HERE
```

## Expected behavior

no error 

## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.168
GPU models and configuration: 
GPU 0: Tesla V100-DGXS-16GB
GPU 1: Tesla V100-DGXS-16GB
GPU 2: Tesla V100-DGXS-16GB
GPU 3: Tesla V100-DGXS-16GB

Nvidia driver version: 418.67
cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.5.1

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[pip3] torchvision==0.2.2.post3
[conda] Could not collect

**Comment by ezyang** [comment] 2019-05-22 20:28
What if you do a fresh rebuild from scratch on master?

cc @jerryzh168

**Comment by nazarblch** [comment] 2019-05-23 10:26
I have made rebuild on master (using pytorch/tools/build_libtorch.py). 
The same error throws.

**Comment by Jonas1312** [comment] 2019-05-23 10:50
Same error I think: https://github.com/pytorch/pytorch/issues/20408#issuecomment-492250174

**Comment by nazarblch** [comment] 2019-05-23 13:06
After correcting that part of code I got similar sequence of errors in  pytorch/torch/csrc/jit/generated/register_aten_ops_0.cpp

for example:

terminate called after throwing an instance of 'std::runtime_error'
  what():  expected ) but found 'ident' here:
aten::embedding_bag(Tensor weight, Tensor indices, Tensor offsets, bool scale_grad_by_freq=False, int mode=0, bool sparse=False, Tensor? per_sample_weights=None) -> (Tensor, Tensor, Tensor, Tensor)
                   ~~~~ <--- HERE

**Comment by hriebl** [comment] 2019-05-29 17:41
I have the same issue. My guess is that it has nothing to do with CUDA, because I'm using the CPU-only build. Here is my environment:

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Fedora release 29 (Twenty Nine)
GCC version: (GCC) 8.3.1 20190223 (Red Hat 8.3.1-2)
CMake version: version 3.14.4

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[conda] Could not collect
```

As mentioned in #20408, I was able to work around this bug by downgrading to PyTorch 1.0.1. I'd prefer 1.1 however... :-p

**Comment by jerryzh168** [comment] 2019-05-29 18:52
cc @smessmer do you know what is the reason for this error

**Comment by hriebl** [comment] 2019-05-31 19:03
For me, the problem occurs when using Sphinx Autodoc. It seems that the module import fails when running Sphinx, but it works in plain Python...

In case anybody else encounters this issue with Sphinx, setting `autodoc_mock_imports = ['torch']` in the conf.py file is another way to work around this problem.

**Comment by ezyang** [comment] 2019-05-31 19:31
If someone has reproduction instructions from a fresh Docker image, that would be very helpful. (I haven't tried OP's instructions yet, but mostly because I don't have a working libtorch install)

**Comment by Jonas1312** [comment] 2019-05-31 19:51
Have you tried to apply this fix #20490 but with the preprocessor directive removed?

i.e. replace:
```
#ifdef _MSC_VER
C10_EXPORT double strtod_c(const char *nptr, char **endptr)
{
    static _locale_t loc = _create_locale(LC_ALL, "C");
    return _strtod_l(nptr, endptr, loc);
}
#else
C10_EXPORT double strtod_c(const char *nptr, char **endptr)
{
    char *fail_pos;
@@ -240,6 +247,7 @@ C10_EXPORT double strtod_c(const char *nptr, char **endptr)
    errno = EINVAL;
    return -1.0;
}
#endif
```

by:
```
C10_EXPORT double strtod_c(const char *nptr, char **endptr)
{
    static _locale_t loc = _create_locale(LC_ALL, "C");
    return _strtod_l(nptr, endptr, loc);
}

```
and build from source

**Comment by hriebl** [comment] 2019-05-31 21:08
Sorry, I have no experience with Docker, so I can't help with an image.

Recompiling as proposed by @Jonas1312 doesn't work on my system. The compilation error:
```
/home/hannes/Sync/Research/graphmlss/pytorch/torch/csrc/jit/script/strtod.cpp: In function ‘double torch::jit::script::strtod_c(const char*, char**)’:
/home/hannes/Sync/Research/graphmlss/pytorch/torch/csrc/jit/script/strtod.cpp:81:12: error: ‘_locale_t’ does not name a type; did you mean ‘locale_t’?
     static _locale_t loc = _create_locale(LC_ALL, "C");
            ^~~~~~~~~
            locale_t
/home/hannes/Sync/Research/graphmlss/pytorch/torch/csrc/jit/script/strtod.cpp:82:36: error: ‘loc’ was not declared in this scope
     return _strtod_l(nptr, endptr, loc);
                                    ^~~
/home/hannes/Sync/Research/graphmlss/pytorch/torch/csrc/jit/script/strtod.cpp:82:36: note: suggested alternative: ‘log’
     return _strtod_l(nptr, endptr, loc);
                                    ^~~
                                    log
/home/hannes/Sync/Research/graphmlss/pytorch/torch/csrc/jit/script/strtod.cpp:82:12: error: ‘_strtod_l’ was not declared in this scope
     return _strtod_l(nptr, endptr, loc);
            ^~~~~~~~~
/home/hannes/Sync/Research/graphmlss/pytorch/torch/csrc/jit/script/strtod.cpp:82:12: note: suggested alternative: ‘strtod_l’
     return _strtod_l(nptr, endptr, loc);
            ^~~~~~~~~
            strtod_l
make[2]: *** [caffe2/CMakeFiles/caffe2.dir/build.make:1028: caffe2/CMakeFiles/caffe2.dir/__/torch/csrc/jit/script/strtod.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:5502: caffe2/CMakeFiles/caffe2.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
Traceback (most recent call last):
  File "setup.py", line 756, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    build_dir='build')
  File "/home/hannes/Sync/Research/graphmlss/pytorch/tools/build_pytorch_libs.py", line 312, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib64/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '4', 'install']' returned non-zero exit status 2.
```

Maybe it helps to think about how the module import in Sphinx differs from
```
(venv) [hannes@linux graphmlss]$ python
Python 3.7.3 (default, May 11 2019, 00:45:16) 
[GCC 8.3.1 20190223 (Red Hat 8.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> 
```
?

**Comment by smessmer** [comment] 2019-06-04 19:57
Can you test if https://github.com/pytorch/pytorch/pull/21369 fixes it?

**Comment by hriebl** [comment] 2019-06-04 23:51
I can confirm that this issue is fixed for me with PR #21369 by @smessmer. Thank you!

**Comment by smessmer** [comment] 2019-06-06 22:17
We just committed https://github.com/pytorch/pytorch/pull/21293 which should have the same effect. Please reopen if this still happens on master.

**Closed by smessmer** 2019-06-06 22:17 UTC
Labels: jit, module: quantization, needs reproduction, triaged

**Comment by DoubleHub** [comment] 2019-06-28 15:39
Same bug happening here for me

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[pip3] torch==1.1.0
[pip3] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37he904b0f_5  
[conda] mkl_fft                   1.0.10           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch-cpu               1.1.0               py3.7_cpu_0    pytorch
[conda] torchvision-cpu           0.3.0             py37_cuNone_1    pytorch

**Comment by nazarblch** [comment] 2019-07-05 13:45
I have recently tested the initial issue. When I build LibTorch from master src it works fine now! Thanks! 
Note that in https://download.pytorch.org/libtorch/cu100/libtorch-shared-with-deps-latest.zip  the initial error hasn't been fixed.
