### ISSUE TITLE
memory leak problem?

### ISSUE THREAD

**Issue by jzthree** [pytorch/pytorch#1221] opened 2017-04-10 07:26 UTC
```
import torch

def batched_inverse(x):
    """Calculate matrix inverse for each channel separately. The input size should be C*M*M"""
    A_LU = torch.btrifact(x)
    b = torch.eye(x.size(1)).cuda().unsqueeze(0).expand(x.size())

    xinverse = x.clone()
    for i in range(x.size(1)):
        xinverse[:, :, i] = torch.btrisolve(b[:, :, i], *A_LU)
    return xinverse


x=torch.cuda.FloatTensor(10000,10,10).normal_()
y=torch.bmm(x,x)
while True:
    z = batched_inverse(y)
```

This code gives RuntimeError: cuda runtime error (2) : out of memory at /tigress/jzthree/pgm/pytorch/torch/lib/THC/generic/THCTensorMathBlas.cu:797

It fills memory faster when it is given many batches of small matrices (large first dimension).  Calling torch.btrifact line and torch.eye line alone seems to cause no problem. It looks like using b together with btrisolve is the cause.

**Comment by albanD** [comment] 2017-04-10 08:19
Hi,
Thanks for the good reproduction script.
It is indeed a memory leak due to [this](https://github.com/pytorch/pytorch/blob/f6fef3718e6f5acae33ae89a62fb12c68d93adb7/torch/lib/THC/generic/THCTensorMathBlas.cu#L797) alloc not being freed.
I will send a PR to solve this.

**Comment by apaszke** [comment] 2017-04-10 22:09
The fix is in master now.

**Closed by apaszke** 2017-04-10 22:09 UTC
Labels: bug, high priority
