### ISSUE TITLE
Support multiple simultaneous LR schedulers

### ISSUE THREAD

**Issue by jeanm** [pytorch/pytorch#13022] opened 2018-10-23 23:31 UTC
## 🚀 Feature

Currently only one `_LRScheduler` can be used with the same optimizer. It would be great to support using multiple ones simultaneously.

## Motivation

It's not uncommon in NLP (see e.g. [here](https://github.com/facebookresearch/InferSent)) to want to use both `StepLR` and `ReduceLROnPlateau`. This isn't possible currently, because `StepLR` calculates learning rate updates based on what was the initial learning rate, and how many epochs have gone by (see `get_lr()`). This is all based on the assumption the learning rate hasn't been touched by anything else.

## Pitch

This can be fixed by having `StepLR`,  `ExponentialLR` (and potentially others) query the optimizer to find out the current learning rate, instead of attempting to work it out what it should be. `ReduceLROnPlateau` already does this in `_reduce_lr()`.

**Comment by fmassa** [comment] 2019-03-26 13:29
I believe this can be closed with #14010?

**Comment by vincentqb** [comment] 2019-08-14 18:44
Unfortunately, #14010 had to be reverted due to unexpected behavior described in #20527.

**Comment by vincentqb** [comment] 2019-09-13 14:39
#24352

**Comment by ajuric** [comment] 2020-05-28 12:08
Any updates on this?

**Comment by vincentqb** [comment] 2020-05-28 15:24
A solution was implemented in #26423. Closing this PR, please feel free to re-open if needed.

**Closed by vincentqb** 2020-05-28 15:24 UTC
Labels: module: optimizer, triaged
