### ISSUE TITLE
Compilation error 

### ISSUE THREAD

**Issue by cindycia** [pytorch/pytorch#14948] opened 2018-12-09 03:21 UTC
I get the following compilation error when building pytorch 1.0.0 from source:

> pytorch/third_party/ideep/mkl-dnn/src/cpu/jit_avx512_core_u8s8s32x_wino_convolution.cpp:223:41: error: assuming signed overflow does not occur when assuming that (X + c) >= X is always true [-Werror=strict-overflow]
>          assert(id_reg_tmp < id_reg_tmp1);
>                                          ^

I worked around this issue by adding:
```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-strict-overflow")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-error=strict-overflow")
```
in third_party/ideep/mkl-dnn/CMakeLists.txt before adding the sub directories. 
But I wonder whether there are better ways to solve this error.

System configuration:

Ubuntu 18.04
Cmake 3.12.4
CUDA 9.2.148
gcc g++ 6.4.0 
pytorch pulled from master, commit 6651fae827fb6becd177fadb35c1913ca74950de

**Comment by soumith** [comment] 2018-12-09 07:32
duplicate of https://github.com/pytorch/pytorch/issues/13988

Closing as duplicate and tracking in the original issue.

Thanks a lot for the workaround

**Closed by soumith** 2018-12-09 07:32 UTC

**Comment by gujinghui** [comment] 2018-12-10 04:36
pls try this #14977
