### ISSUE TITLE
Feature request: named dimensions

### ISSUE THREAD

**Issue by shekhovt** [pytorch/pytorch#5613] opened 2018-03-07 18:19 UTC
Feature:
Make all Tensors have an optional list of dimension names like ['B','C','H','W']
Then the broadcasting in binary operations like
a + b
can be done according to the names (if they both have named dimensions). For example, if Tensor a has a list ['B','C','H','W'] and b has list ['C'] , then the expected result is efficiently equivalent to
a + b.view([1,-1,1,1])

This will make the broadcasting safe and very convenient to use.
Currently, because broadcasting is implicit, if something goes wrong it is a luck if a dimension mismatch happens somewhen later on or there is an out of memory error thrown.

I think it could further ease the writing of a generic code that has to work with different number of spatial dimensions (e.g. fully connected layers and conv layers), debug problems, etc. Maybe the named dimensions method be also adopted in functions to allow for the syntax like
log_softmax(axis='C')

Why the usual axis number is not sufficient? The axes are hardwired to the dimensionality. For example, the affine weight in BatchNorm is 1D, and its dimension 0 is by default not matching to the dimension 0 in e.g. the input data. So there going to be lots of these .view() commands and if you expect the input with or without spatial dimensions it is going to be more pain.

Now consider the code using named dimensions. It will pretty much work if you change the data layout (how it is linearized in the memory). Or if you increase the number of dimensions. For example, you want to extend to a siamese (or 4-stream) network processing, for which it is convenient to use 5D Tensors with dimensions  'instance', 'stream', 'channels','width','height'. Suddenly 'channels' becomes dimension number 2 instead of 1, but if dimensions are matched by names there is no problem.

**Comment by obust** [comment] 2018-03-12 16:26
See `xarray` for prior work https://github.com/pydata/xarray

**Comment by zou3519** [comment] 2018-03-12 19:40
cc @colesbury what do you think about this?

**Comment by colesbury** [comment] 2018-03-12 20:01
It seems tricky to implement and propagate named dimensions across all operations.

I'm concerned that it complicates the rules for broadcasting because now you have to handle numbered dimensions, named dimensions, and a combination of the two.

I don't see how this fixes the assumptions in batch norm: you still have to make assumptions about whether new dimensions are treated as part of the 'batch' or not. For example, 'stream' and 'channel' probably would be folded into the batch dimension, but 'time' should not.

**Comment by zou3519** [comment] 2019-04-10 19:30
This is a duplicate of #4164, so I'm closing this in favor of that.

**Closed by zou3519** 2019-04-10 19:30 UTC
Labels: feature, high priority, module: operators
