### ISSUE TITLE
torch::set_num_threads does not work 

### ISSUE THREAD

**Issue by oroojlooy** [pytorch/pytorch#19213] opened 2019-04-12 20:01 UTC
## 🐛 Bug

I added `torch::set_num_threads(2)` in the beginning of the `mnist` code and still the executable uses all of the available threads, i.e., my cpu usage is around 800-1100% in a machine with 12 threads. 

## To Reproduce

In the `mnist` code 
https://github.com/goldsborough/examples/blob/cpp/cpp/mnist/mnist.cpp

add `torch::set_num_threads(2);` in line `116`, change line `119` by `if (torch::cuda::is_available() && 0){` to make sure you use `cpu` and run the code. Then, just monitor the cpu usage. 

## Expected behavior
With `torch::set_num_threads(2);` you should never see `cpu` usage greater than `200%`. 

## Environment
```
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Red Hat Enterprise Linux Server 7.6 (Maipo)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 3.12.0

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 7.5.17
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P40

Nvidia driver version: 384.81
cuDNN version: /usr/lib64/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.2
[pip] tinynumpy==1.2.1
[pip] torch==1.0.1.post2
[pip] torchvision==0.2.1
[conda] Could not collect

```

**Comment by ezyang** [comment] 2019-04-12 22:00
If possible, could you try running your script off of a nightly and see if it still has the same behavior?

**Comment by oroojlooy** [comment] 2019-04-13 17:04
I had the nightly version of Apr 10, and got same result with that. 
Do you want me to downloaded the latest nightly version?

**Comment by mingfeima** [comment] 2019-04-19 07:13
@oroojlooy i can also reproduce this issue.
Indeed, pytorch is not listening to the value set by `torch::set_num_threads()` from `libtorch`.
But `torch.set_num_threads()` from python works as expected.

PyTorch uses different OpenMP thread pool for forward path and backward path so the cpu usage is likely to be < 2 * cores * 100%. In your case you can expect that cpu usage is below 400%.

Also it works to set environment variable `OMP_NUM_THREADS` when running the C++ binary.
```bash
OMP_NUM_THREADS=2 ./mnist
```

**Comment by oroojlooy** [comment] 2019-04-19 15:10
> @oroojlooy i can also reproduce this issue.
> Indeed, pytorch is not listening to the value set by `torch::set_num_threads()` from `libtorch`.
> But `torch.set_num_threads()` from python works as expected.
> 
> PyTorch uses different OpenMP thread pool for forward path and backward path so the cpu usage is likely to be < 2 * cores * 100%. In your case you can expect that cpu usage is below 400%.
> 
> Also it works to set environment variable `OMP_NUM_THREADS` when running the C++ binary.
> 
> ```shell
> OMP_NUM_THREADS=2 ./mnist
> ```

Thanks for comment. 
I also tried `OMP_NUM_THREADS=2`, and still got same behavior, i.e. I see `800%-1100%` CPU usage in a machine with 12 cores. Also, it seems that `cpu usage < 2 * cores * 100%.` does not work for me. Is it supposed to work on any machine?

**Comment by soumith** [comment] 2019-04-19 15:17
@oroojlooy 

how about:

`OMP_NUM_THREADS=2 MKL_NUM_THREADS=2`

**Comment by vpirogov** [comment] 2019-04-19 15:21
The only thing `MKL_NUM_THREADS` does is override the `OMP_NUM_THREADS` setting for Intel MKL library. There's no need to set it as long as `OMP_NUM_THREADS` is set.

**Comment by oroojlooy** [comment] 2019-04-19 15:27
> @oroojlooy
> 
> how about:
> 
> `OMP_NUM_THREADS=2 MKL_NUM_THREADS=2`

I am getting `600%-800%` now.

**Comment by weiqiangguo** [comment] 2019-05-07 01:41
You try to use pytorch 1.1, the bug has been fixed in pytorch 1.1,

**Comment by soumith** [comment] 2019-05-07 15:49
@oroojlooy please reopen issue if you can reproduce it with v1.1 pytorch

**Comment by kishwarshafin** [comment] 2019-05-26 01:02
I am facing this issue with v1.1 pytorch. 

![image](https://user-images.githubusercontent.com/10559039/58376098-239d5680-7f17-11e9-8ea3-956ce12ae88a.png)

I'm using CUDA 9.1 though, can that be an issue here?

**Comment by soumith** [comment] 2019-05-26 15:52
@kishwarshafin looks fine to me. we dont globally set a config -- you set the number of threads in your process' lifetime.

**Comment by thiagocrepaldi** [comment] 2019-06-05 16:56
I could reproduce this on Pytorch 1.1.0a0+465799f

On my experiment, I have set `torch.set_num_threads(1)` in the main script instantiating the Pytorch Datalaoder class and also at the `worker_init_fn`function for each dataloader worker.

For debugging, I also printed `torch.get_num_threads()` for each process and all of them returned "1" as expected, but all CPUs were used

**Comment by soumith** [comment] 2019-06-05 18:03
cc: @ilia-cher see the latest comment

**Comment by soumith** [comment] 2019-06-05 18:03
i think this was fixed by Ilia on master, you should see something like PyTorch 1.2.0a0+....

**Comment by ilia-cher** [comment] 2019-06-05 22:20
@thiagocrepaldi let me understand better your setup, you mentioned multiple processes? the setting of threads we have is per process, so it's expected that you'll use more than one thread

**Comment by thiagocrepaldi** [comment] 2019-06-06 00:18
Yes, I agree. I have created `n` processes, setting `torch.set_num_threads(1)` on each of them and instead of having `n` threads being used, I got all CPUs at 100%

On a 24 CPUs server, even if I spawn a single process, all 24 CPUs are used

**Comment by ilia-cher** [comment] 2019-06-06 00:33
is it possible to share a minimum reproducible example of this?

**Comment by thiagocrepaldi** [comment] 2019-06-11 21:37
Yes, I agree. I have created `n` processes, setting `torch.set_num_threads(1)` on each of them and instead of having `n` threads being used, I got all CPUs at 100%

On a 24 CPUs server, even if I spawn a single process, all 24 CPUs are used

I will try to create a minimal repro script soon. te current repro has lots of unrelated changes and not easily shareable

**Comment by ilia-cher** [comment] 2019-06-12 20:38
that'd be very helpful, thanks!

**Comment by AravindChandradoss** [comment] 2019-08-13 17:03
@thiagocrepaldi Were you able to reduce the CPU usage?

**Comment by thiagocrepaldi** [comment] 2019-08-13 18:31
> 
> 
> @thiagocrepaldi Were you able to reduce the CPU usage?
> 
> Thanks

it works by setting `OMP_NUM_THREADS=1` env var - it doesnt if you `torch.set_num_threads(1)`. I couldnt find a good minimal repro as my changes had a couple thousands lines that didnt go public

**Comment by AravindChandradoss** [comment] 2019-08-13 20:12
I tried setting `OMP_NUM_THREADS=1`but still PyTorch is using all the CPUs. 

This is the command I used to set OMP_NUM_THREADS
`$ OMP_NUM_THREADS=1 python foo.py ` 

Am I using it right?

**Comment by thiagocrepaldi** [comment] 2019-08-13 21:13
Yes, you are =/ if you have a script that I can reproduce the issue, I could try to debug and fix this issue

**Comment by AravindChandradoss** [comment] 2019-08-14 15:13
It was due to DataLoader (num_worker). The default value I had for num_worker was too high.

**Comment by danieleds** [comment] 2019-09-26 09:36
I can reproduce this on PyTorch 1.2.0.
I have tried to limit the number of threads by setting `torch.set_num_threads(n)` but it has not effect. I have been able to make it work by setting the env var `OMP_NUM_THREADS` instead.

**Comment by ilia-cher** [comment] 2019-09-26 19:28
> I can reproduce this on PyTorch 1.2.0.
> I have tried to limit the number of threads by setting `torch.set_num_threads(n)` but it has not effect. I have been able to make it work by setting the env var `OMP_NUM_THREADS` instead.

@danieleds could you provide a code snippet that reproduces this?

**Comment by danieleds** [comment] 2019-09-27 07:52
I can provide an example, which is not really minimal but it shows the behavior.

### Step 1:
    
    git clone https://github.com/danieleds/qc_with_untrained_recurrent_embeddings.git

### Step 2:
apply this patch

```
diff --git a/QC/leaky_esn_attn/__main__.py b/QC/leaky_esn_attn/__main__.py
index 38f7004..b800183 100644
--- a/QC/leaky_esn_attn/__main__.py
+++ b/QC/leaky_esn_attn/__main__.py
@@ -4,6 +4,8 @@ sys.path.extend(['.', '..', '../..'])
 from QC.leaky_esn_attn.model import ESNModelQC

 import torch
+torch.set_num_threads(1)
+
 from typing import Tuple, Any
 import argparse
 from datetime import datetime
diff --git a/QC/leaky_esn_attn/model.py b/QC/leaky_esn_attn/model.py
index 3e73800..8297cf3 100644
--- a/QC/leaky_esn_attn/model.py
+++ b/QC/leaky_esn_attn/model.py
@@ -90,7 +90,7 @@ class ESNModelQC:
         #dataloader = DataLoader(train_fold, batch_size=self.batch_size, collate_fn=collate_fn,
         #                        pin_memory=True, sampler=sampler)

-        dataloader = DataLoader(train_fold, shuffle=True, batch_size=self.batch_size, collate_fn=collate_fn, pin_memory=True)
+        dataloader = DataLoader(train_fold, shuffle=True, batch_size=self.batch_size, collate_fn=collate_fn, pin_memory=True, num_workers=4)

         optimizer = torch.optim.Adam(self.model.parameters(), lr=self.lr, weight_decay=self.weight_decay)

```

### Step 3:

run by issuing

    python3 QC/leaky_esn_attn --searches 0 --final-trials 10

After the small dataset is downloaded, training begins. During training you can observe that the number of threads is way higher than 1, and way higher than 4 (in fact on my server I see usage of ~60 threads).

This only happens when `num_workers` is set for the dataloader. If `num_workers` is not set, `torch.set_num_threads` works correctly.

**Comment by danieleds** [comment] 2019-11-27 11:06
Update: in v1.3.1, the OMP_NUM_THREADS env var doesn't work either.

**Comment by saeed-khorram** [comment] 2020-02-17 06:21
@danieleds I am also facing this issue on v1.3.1. Any luck?

**Comment by toliz** [comment] 2020-03-15 09:07
Having the same problem in v1.3.1 as well

**Comment by IoT-master** [comment] 2020-05-19 02:54
I'm also having the same issue with Pytorch 1.5.0

**Comment by arrayslayer** [comment] 2020-08-04 18:41
Same issue. I cannot run multiprocessing pool because pytorch uses all threads

**Comment by mchalecki** [comment] 2020-08-05 09:55
It's not big help but, after compiling from source pytorch version 1.6, in libtorch on device this function for me works.

**Comment by ilia-cher** [comment] 2020-08-06 20:04
thanks for the report, I will take one more look into the issue and will try to repro again to check if we miss propagating the setting in some use cases

**Closed** 2020-08-27 21:54 UTC
Labels: high priority, module: openmp, topic: multithreading, triaged

**Comment by ecolss** [comment] 2020-08-28 07:35
> It's not big help but, after compiling from source pytorch version 1.6, in libtorch on device this function for me works.

So looks like the `pip` or `conda` installed version doesn't have multi-threading support, and we have to compile from source?

**Comment by ilia-cher** [comment] 2020-08-28 07:45
@ecolss do you have a reproducible version for 1.6 that shows the issue?

**Comment by ecolss** [comment] 2020-08-28 16:45
> @ecolss do you have a reproducible version for 1.6 that shows the issue?

I posted here: https://discuss.pytorch.org/t/pytorch-seems-very-slow-on-cpu/94360/6

**Comment by ilia-cher** [comment] 2020-08-28 20:00
there's was a limitation (no multithreading with openmp) in mac binaries https://github.com/pytorch/pytorch/issues/43036
