### ISSUE TITLE
ImportError: DLL load failed  on windows

### ISSUE THREAD

**Issue by gdyxml2000** [pytorch/pytorch#7070] opened 2018-04-28 15:11 UTC
Successfully installed torch-0.4.0   (cu90/torch-0.4.0-cp36-cp36m-win_amd64.whl )

when run a  test.py  , got an errors like this:
File "E:/baidu/DuReader-master/DuReader-master/PyTorch/Test.py", line 1, in <module>
    import torch
  File "F:\Program Files\python3.6.1\lib\site-packages\torch\__init__.py", line 78, in <module>
    from torch._C import *
ImportError: DLL load failed: 找不到指定的模块。

My environment is  python3.6.1+cuda9.0.   the same environment  run tensorflow is ok!

**Comment by peterjc123** [comment] 2018-04-29 02:27
Duplicate of #4518. Close this please.

**Closed** 2018-04-29 09:46 UTC
