### ISSUE TITLE
Compile PyTorch core with -Werror

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#56085] opened 2021-04-14 22:09 UTC
PyTorch codebase should be reasonable warning free, which is not the case for now.
This is something that is very hard to achieve in one change, so perhaps a gradual approach can be taken:

- [ ] Add all source files to libtorch_compiler_with_Wnoerror_flag
- [ ] Modify CMake system to add -Werror to the CFLAGS unless file is in the list
- [ ] Modify build system to ignore warnings in 3rd party libraries
- [ ] Update default Wno-lists
This would allow us to stabilize the situation and eventually remove files from this list one by one

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by ezyang** [comment] 2021-04-15 00:09
This approach is fine. Another approach is to only selectively turn on specific Werror flags and make sure codebase is clean for those. This may be better as there are compiler variations.

Also need to make sure we don't force people to build with Werror when they just want to build PyTorch (not dev).

**Comment by driazati** [comment] 2021-04-15 00:23
If we can make PyTorch warnings-clean, what's wrong with `-Werror`-ing for all builds (including non-dev)?

Also just so I understand this approach is basically the opposite of what's in #56095? i.e. `-Werror` everywhere except for a list of specific warnings for specific files / anything in third_party?

**Comment by ezyang** [comment] 2021-04-15 01:33
Because different versions of compilers have different warnings, and no one wants a codebase that compiles on one compiler but not on another. See also https://twitter.com/trav_downs/status/1375575792604749826

**Comment by seemethere** [comment] 2022-02-28 20:09
@malfet confirmed that we do compile core with `-Werror` so closing.

**Closed by seemethere** 2022-02-28 20:09 UTC
Labels: module: ci, triaged, better-engineering
