### ISSUE TITLE
[inductor][cpu] performance regression

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#109700] opened 2023-09-20 09:24 UTC
<p>new_perf_regression 2023-09-17 compare with 2023-09-13 nightly release</p>

<p>Note: multi threads secnario for models above first *, single thread for models between two *</p>
<p>new_perf_regression</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_T5_generate</td>
      <td>1</td>
      <td>0.969546</td>
      <td>1.571509982</td>
      <td>1.523651217008172</td>
      <td>381.9721</td>
      <td>1</td>
      <td>1.087152</td>
      <td>1.3870738859999998</td>
      <td>1.5079601493126717</td>
      <td>205.124549</td>
      <td>0.89</td>
      <td>0.99</td>
      <td>0.88</td>
      <td>0.54</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
    <tr>
      <td>lennard_jones</td>
      <td>1</td>
      <td>0.979394</td>
      <td>7.776900000000001e-05</td>
      <td>7.616649198600001e-05</td>
      <td>9.569067</td>
      <td>1</td>
      <td>1.172059</td>
      <td>6.3225e-05</td>
      <td>7.4103430275e-05</td>
      <td>9.954492</td>
      <td>0.84</td>
      <td>0.97</td>
      <td>0.81</td>
      <td>1.04</td>
    </tr>
    <tr>
      <td>pyhpc_equation_of_state</td>
      <td>1</td>
      <td>19.094604</td>
      <td>5.9531e-05</td>
      <td>0.001136720870724</td>
      <td>12.447889</td>
      <td>1</td>
      <td>22.186139</td>
      <td>5.1889e-05</td>
      <td>0.001151216566571</td>
      <td>12.786719</td>
      <td>0.86</td>
      <td>1.01</td>
      <td>0.87</td>
      <td>1.03</td>
    </tr>
    <tr>
      <td>pyhpc_isoneutral_mixing</td>
      <td>1</td>
      <td>50.675985</td>
      <td>5.9053e-05</td>
      <td>0.002992568942205</td>
      <td>18.191096</td>
      <td>1</td>
      <td>58.979956</td>
      <td>5.122e-05</td>
      <td>0.0030209533463200003</td>
      <td>18.466515</td>
      <td>0.86</td>
      <td>1.01</td>
      <td>0.87</td>
      <td>1.02</td>
    </tr>
    <tr>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
      <td>*</td>
    </tr>
  </tbody>
</table>
<p>SW info</p>
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>0de2555</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ffbbebb9</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>475b6ae</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>142d029</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>8636bf3</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>eb9bf61</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>0200b11</td>
      <td>/</td>
    </tr>
  </tbody>
</table>

<p>Repro</p>
<a href=https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh>
  inductor_single_run.sh </a>
<code>
bash inductor_single_run.sh multiple/single inference performance torchbench/huggingface/timm_models model float32 first static default 0
</code>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @Xia-Weiwen

**Comment by leslie-fang-intel** [comment] 2023-09-21 08:14
`hf_T5_generate` and `lennard_jones` has also been reported in last week's testing: https://github.com/pytorch/pytorch/issues/109285. @Valentine233 @blzheng are already working on these.
I will take a look of  `pyhpc_equation_of_state` and `pyhpc_isoneutral_mixing`.

**Comment by leslie-fang-intel** [comment] 2023-09-22 06:05
For the regression of `pyhpc_equation_of_state`, narrow down to the commit of https://github.com/pytorch/pytorch/commit/94a54b89aae0bec1d1a079aff247a772c75fc843. Will further debug for root-cause.

**Comment by leslie-fang-intel** [comment] 2023-09-23 02:50
After some study of `pyhpc_equation_of_state` and `pyhpc_isoneutral_mixing`, https://github.com/pytorch/pytorch/commit/94a54b89aae0bec1d1a079aff247a772c75fc843 especially the `enter` and `leave` of  [`backend_cache_wrapper`](https://github.com/pytorch/pytorch/pull/107337/files#diff-c663df72d7a648204ff256e604fe3c9b393e7e2d58204e3bc818d90a99712911R391-R392)  induce a steady overhead with almost 0.007ms measured on a ICX system for both Eager and Inductor backend. This overhead is trivial for eager Backend since the E2E latency is almost 1~3 ms. However, it affects Inductor Backend since the E2E latency is almost 0.04ms for these 2 workloads. Refer to below detail data measured on a 32 Core ICX system:

|                         | PyTorch Commit 9b3f5823f339768490ac8d2a6a86e7cddd8f50c1 |                            |          | PyTorch Commit 94a54b89aae0bec1d1a079aff247a772c75fc843 |                            |          |                                             |                                                |
|-------------------------|---------------------------------------------------------|----------------------------|----------|---------------------------------------------------------|----------------------------|----------|---------------------------------------------|------------------------------------------------|
| Model                   | Eager backend Latency(ms)                                 | Inductor backend Latency(ms) | Speed up | Eager backend Latency(ms)                                 | Inductor backend Latency(ms) | Speed up | Eager backend absolute latency increament (ms) | Inductor backend absolute latency increament (ms) |
| pyhpc_equation_of_state | 1.1450                                                  | 0.0484                     | 23.6704  | 1.1534                                                  | 0.0563                     | 20.4918  | 0.0084                                      | 0.0079                                         |
| pyhpc_isoneutral_mixing | 3.0114                                                  | 0.0499                     | 60.3124  | 3.0148                                                  | 0.0579                     | 52.0789  | 0.0034                                      | 0.0080                                         |

I think 0.007ms should be trivial for most of the workloads. I think we can take it as expected.

**Comment by ezyang** [comment] 2023-09-23 03:54
Cc @anijain2305 @yanboliang @ydwu4  for guard overhead

**Comment by Valentine233** [comment] 2023-10-08 07:28
Test `hf_T5_generate` with 0917 nightly: speedup=`1.004x`.
Script: `bash inductor_single_run.sh multiple inference performance torchbench hf_T5_generate float32 first static default 0`.
Could not reproduce.

**Comment by leslie-fang-intel** [comment] 2023-12-07 08:14
Closed as some regression are as expected and some will tracked in other issue.

**Closed by leslie-fang-intel** 2023-12-07 08:14 UTC
Labels: triaged, oncall: pt2, module: inductor, oncall: cpu inductor
