### ISSUE TITLE
Support `antialias` option on `torch.interpolate` for ONNX export

### ISSUE THREAD

**Issue by cobacoba** [pytorch/pytorch#80033] opened 2022-06-22 14:22 UTC
### 🚀 The feature, motivation and pitch

Hi, I'm working on a model that uses `torch.interpolate` for upsampling/downsampling with `antialias` function, i.e., `torch>=1.11.0`.  Antialiasing is necessary before downsampling to remove upper half frequency components.

I would like to be able to export this model with ONNX. But, currently it does not yet support the exportation with `antialias` option. 

Is it possible to request this addition on ONNX export?

Many thanks before.

### Alternatives

It is also possible to create a custom convolution for low-pass filter to perform similar thing as the `antialias` option. In this case, ONNX export should be OK. However, it would also be nice to have it supported to sync with the latest functionality of PyTorch.

### Additional context

ONNX version 1.12.0

**Comment by AllenTiTaiWang** [comment] 2022-08-11 19:48
We have antialias in spec on Resize-18 , more detail on https://github.com/onnx/onnx/blob/main/docs/Changelog.md#resize-18. This will be implemented later.

**Comment by jackylu0124** [comment] 2023-01-09 03:22
Hi @titaiwangms,

I also came across the same limitation issue, do you by chance know the rough timeline on when the anti-aliasing option for `torch.nn.functional.interpolate` will be supported? Thanks a lot in advance!

**Comment by titaiwangms** [comment] 2023-01-09 17:15
Waiting for https://github.com/pytorch/pytorch/pull/90337

**Comment by tobaiMS** [comment] 2023-03-15 19:11
Hi, @titaiwangms, are we plan to have the antialias support anytime soon?

**Comment by titaiwangms** [comment] 2023-03-15 19:28
Unfortunately, I thought it would be a quick support on this, so did have a PR, but the performance on ONNX not aligned with PyTorch for some reason. It seems that some other processing are needed to make them equivalent on `antialias` which I don't have much bandwidth now.

**Comment by tobaiMS** [comment] 2023-03-15 20:18
@titaiwangms thanks for the update, do you mean exported the onnx model, but running with ort the performance is not aligned?

**Comment by titaiwangms** [comment] 2023-03-15 22:04
Yes, my guess is that PyTorch/ORT has different spec on antialias, but didn't actually looking into it.

**Comment by titaiwangms** [comment] 2023-03-15 22:06
If you are interested: https://github.com/pytorch/pytorch/pull/95255

**Comment by tobaiMS** [comment] 2023-03-16 20:56
Hi, I found an work around, I want to export Resize to 224*224, bicubic & antialias, (I target to run on CPU):
I export with pytorch 2.0 and with bicubic & antialias = False, 
`torchvision.transforms.Resize(size=(224, 224), interpolation=torchvision.transforms.InterpolationMode.BICUBIC, max_size=None, antialias=False)`
export with
`torch.onnx.export(resize_anti_false, dummy_input, preprocess_model_path_bilinear, input_names=['image'], output_names=['processed_image'], opset_version=18, dynamic_axes={
                      # dict value: manually named axes
                      "image": {2:'h', 3:'w'},
                  })`
then use the https://github.com/NVIDIA/TensorRT/tree/main/tools/onnx-graphsurgeon to change the antialias to True. 
```
def edit_onnx_graph_with_antialias(input_pth, output_pth):
    import onnx_graphsurgeon as gs
    import onnx
    graph = gs.import_onnx(onnx.load(input_pth))
    print("before editing")
    graph.nodes[-1].attrs
    graph.nodes[-1].attrs['antialias'] = 1
    onnx.save(gs.export_onnx(graph), output_pth)
    print("after editing")
    graph.nodes[-1].attrs
```

Run with onnxruntime 1.14.1, the latency is an part. (although the pytorch Resize still different compare with ONNX, but they are very close)
Hope this helps :)

**Comment by titaiwangms** [comment] 2023-03-16 23:40
> Hi, I found an work around, I want to export Resize to 224*224, bicubic & antialias, (I target to run on CPU): I export with pytorch 2.0 and with bicubic & antialias = False, `torchvision.transforms.Resize(size=(224, 224), interpolation=torchvision.transforms.InterpolationMode.BICUBIC, max_size=None, antialias=False)` export with `torch.onnx.export(resize_anti_false, dummy_input, preprocess_model_path_bilinear, input_names=['image'], output_names=['processed_image'], opset_version=18, dynamic_axes={ # dict value: manually named axes "image": {2:'h', 3:'w'}, })` then use the https://github.com/NVIDIA/TensorRT/tree/main/tools/onnx-graphsurgeon to change the antialias to True.
> 
> ```
> def edit_onnx_graph_with_antialias(input_pth, output_pth):
>     import onnx_graphsurgeon as gs
>     import onnx
>     graph = gs.import_onnx(onnx.load(input_pth))
>     print("before editing")
>     graph.nodes[-1].attrs
>     graph.nodes[-1].attrs['antialias'] = 1
>     onnx.save(gs.export_onnx(graph), output_pth)
>     print("after editing")
>     graph.nodes[-1].attrs
> ```
> 
> Run with onnxruntime 1.14.1, the latency is on part. (although the pytorch Resize still different compare with ONNX, but they are very close) Hope this helps :)

Hmmm.. Sounds like antialis=True with Bicubic mode should be close. I will find another time to try it again! Thanks!

**Comment by titaiwangms** [comment] 2024-05-22 07:42
@justinchuby Do we have this in torchlib already?

**Comment by justinchuby** [comment] 2024-05-22 14:15
I think so. antialiasing in ONNX and PyTorch are implemented differently but the option itself should be supported

**Comment by titaiwangms** [comment] 2024-05-22 15:30
We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team

**Closed by titaiwangms** 2024-05-22 15:30 UTC
Labels: module: onnx, triaged, onnx-triaged

**Comment by deo-abhijit** [comment] 2025-01-20 11:29
Hi, I was trying to export some torch models to onnx, and i also faced same issue with antialiasing operation in onnx. It was caused by the resampling operation of positional embeddings. So had to disable antialiasing when exporting model to onnx.  

But recently came across your comment above, and tried dynamo_api, but im getting same error i got last time. 

Here's small reproducible code : [mostly copy paste from timm](https://github.com/huggingface/pytorch-image-models/blob/5d535d7a2d4b435b1b5c1177fd8f04a12b942b9a/timm/layers/pos_embed.py#L60)

```python 

import onnx 
import torch.nn as nn 
import torch.nn.functional as F
class PositionalEmbeddings(nn.Module):
    def __init__(self,
        new_size,
        interpolation: str = 'bilinear',
        antialias: bool = True,
        verbose: bool = False,):
        super().__init__()
        self.new_size = new_size
        self.interpolation= interpolation
        self.verbose = verbose 
        self.antialias = antialias

    def forward(self,posemb):
        # print(posemb.shape)[-3]
       
        if self.new_size[0] == posemb.shape[-3] and self.new_size[1] == posemb.shape[-2]:
            return posemb

        orig_dtype = posemb.dtype
        posemb = posemb.float()
        posemb = posemb.reshape(1, posemb.shape[-3], posemb.shape[-2], posemb.shape[-1]).permute(0, 3, 1, 2)
        posemb = F.interpolate(posemb, size=self.new_size, mode=self.interpolation, antialias=self.antialias)
        posemb = posemb.permute(0, 2, 3, 1).to(orig_dtype)

        return posemb
import torch 

model = PositionalEmbeddings(new_size=(10,20))
torch.onnx.dynamo_export( model,  *(torch.randn(1,64,64,768),))



```
Error Trace:

```bash 
 File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/_exporter_legacy.py", line 1222, in dynamo_export
    ).export()
  File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/_exporter_legacy.py", line 976, in export
    graph_module = self.options.fx_tracer.generate_fx(
  File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 217, in generate_fx
    return self.pre_export_passes(options, model, graph_module, updated_model_args)  # type: ignore[return-value]
  File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/fx/dynamo_graph_extractor.py", line 226, in pre_export_passes
    return _exporter_legacy.common_pre_export_passes(
  File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/_exporter_legacy.py", line 1275, in common_pre_export_passes
    ).analyze(infra.levels.ERROR)
  File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/fx/analysis/unsupported_nodes.py", line 85, in analyze
    self._lint(analysis_result, diagnostic_level)
  File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/fx/analysis/unsupported_nodes.py", line 37, in _lint
    self.diagnostic_context.log_and_raise_if_error(diagnostic)
  File "/home/mzcar/miniconda3/envs/mzinferx/lib/python3.10/site-packages/torch/onnx/_internal/diagnostics/infra/context.py", line 356, in log_and_raise_if_error
    raise RuntimeErrorWithDiagnostic(diagnostic)
torch.onnx._internal.diagnostics.infra.context.RuntimeErrorWithDiagnostic: Unsupported FX nodes: {'call_function': ['aten._upsample_bilinear2d_aa.default']}. 


```

Sarif File generated: https://gist.github.com/deo-abhijit/44ba8ca73707f846559e1ea48d3424ec

I know aten._upsample_bilinear2d_aa op is not supported, but i thought of giving this try.

 https://pytorch.org/docs/stable/onnx_torchscript_supported_aten_ops.html

**Comment by xenova** [comment] 2025-09-02 03:49
Stumbled into this thread while trying to match the output of pytorch/PIL bilinear interpolation with antialias=True. i.e.,
```py
target = F.interpolate(
    image,
    size=(target_h, target_w),
    mode="bilinear",
    align_corners=False,
    antialias=True,
)
```


So, here's what I came up with... a version that is (1) ONNX exportable and (2) matches pytorch version with atol < 2e-6 on my tests. Hope it helps!
```
import torch

def bilinear_interpolation_antialias(image: torch.Tensor, target_h: int, target_w: int) -> torch.Tensor:
    if image.dim() != 4:
        raise ValueError(f"Input image must be a 4D tensor (N, C, H, W), but got shape {image.shape}")

    original_dtype = image.dtype
    device = image.device
    
    n_batch, n_channels, source_h, source_w = image.shape
    image_float = image.float()

    x_scale = source_w / target_w
    y_scale = source_h / target_h

    one = torch.tensor(1.0, device=device)
    x_radius = torch.max(one, x_scale)
    y_radius = torch.max(one, y_scale)

    kernel_h_size = torch.ceil(y_radius * 2).long() + 2
    kernel_w_size = torch.ceil(x_radius * 2).long() + 2

    y_new_coords = torch.arange(target_h, device=device, dtype=torch.float32)
    x_new_coords = torch.arange(target_w, device=device, dtype=torch.float32)
    
    y_source_centers = (y_new_coords + 0.5) * y_scale - 0.5
    x_source_centers = (x_new_coords + 0.5) * x_scale - 0.5

    y_min_bbox = torch.floor(y_source_centers - y_radius)
    x_min_bbox = torch.floor(x_source_centers - x_radius)

    kernel_y_offsets = torch.arange(kernel_h_size, device=device, dtype=torch.float32)
    kernel_x_offsets = torch.arange(kernel_w_size, device=device, dtype=torch.float32)

    y_s = y_min_bbox.view(target_h, 1, 1, 1) + kernel_y_offsets.view(1, 1, -1, 1)
    x_s = x_min_bbox.view(1, target_w, 1, 1) + kernel_x_offsets.view(1, 1, 1, -1)

    dist_y = torch.abs(y_s - y_source_centers.view(target_h, 1, 1, 1))
    dist_x = torch.abs(x_s - x_source_centers.view(1, target_w, 1, 1))
    
    zero = torch.tensor(0.0, device=device)
    weight_y = torch.max(zero, 1.0 - dist_y / y_radius)
    weight_x = torch.max(zero, 1.0 - dist_x / x_radius)
    weights = weight_y * weight_x

    valid_mask = (y_s >= 0) & (y_s < source_h) & (x_s >= 0) & (x_s < source_w)
    weights = weights * valid_mask.float()

    y_s_clamped = torch.clamp(y_s, 0, source_h - 1).long()
    x_s_clamped = torch.clamp(x_s, 0, source_w - 1).long()
    
    source_pixels = image_float[:, :, y_s_clamped, x_s_clamped]

    weights_expanded = weights.view(1, 1, target_h, target_w, kernel_h_size, kernel_w_size)

    weighted_sum = torch.sum(source_pixels * weights_expanded, dim=(-1, -2))
    total_weight = torch.sum(weights_expanded, dim=(-1, -2))
    total_weight = torch.where(total_weight == 0, torch.tensor(1e-7, device=device), total_weight)
    
    resized_image = weighted_sum / total_weight

    return resized_image.to(original_dtype)
```
