### ISSUE TITLE
Error when exporting a module to ONNX when ScriptModule is referenced

### ISSUE THREAD

**Issue by congkun-ck** [pytorch/pytorch#54203] opened 2021-03-17 20:11 UTC
## 🐛 Bug

When I tried to export a module with reference to another ScriptModule, onnx.export failed with error:
```
RuntimeError: Tried to trace <__torch__.TestScript object at 000001C5DEA513D0> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.
```
## To Reproduce
```
import torch as th
import torch.nn as nn
import torch.onnx

class TestScript(nn.Module):
    def __init__(self):
        super(TestScript, self).__init__()
    def forward(self, x):
        return (x, )

class Test(nn.Module):
    def __init__(self):
        super(Test, self).__init__()
        self.test = th.jit.script(TestScript())
    def forward(self, x):
        return self.test(x)

x = th.zeros(1, dtype=th.float32)
m = Test()
torch.onnx.export(m, (x,), 'test.onnx')
```
ScriptFunction looks fine. But I need some conditional operations on subgraphs so a bare script function cannot do that.

## Environment

PyTorch version: 1.7.1+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Enterprise
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.0

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.1
[pip3] torch==1.7.1+cpu
[pip3] torch-complex==0.2.1
[pip3] torchaudio==0.7.2
[pip3] torchvision==0.8.2+cpu
[conda] Could not collect

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity @gmagogsfm

**Comment by JaheimLee** [comment] 2021-06-21 07:27
Is there any progress?

**Comment by garymm** [comment] 2021-11-17 00:38
Duplicate of #47887

**Closed by garymm** 2021-11-17 00:38 UTC
Labels: module: onnx, triaged
