### ISSUE TITLE
false INTERNAL ASSERT FAILED at "libtorch\\include\\torch\\csrc\\api\\include\\torch\\detail\\TensorDataContainer.h":299, please report a bug to PyTorch. TensorDataContainer is already a Tensor type, `fill_tensor` should not be called

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#43545] opened 2020-08-25 09:43 UTC
## 🐛 Bug

Trying convert a RefArray into a tensor like this  :
 
```cpp
auto tmp = torch::ones({2,3});
auto shapes = torch::tensor({tmp.sizes()});
```
results in this exception message : 
```
false INTERNAL ASSERT FAILED at "D:\\Codes\\cpp\\port\\LibtorchPort\\Dependencies\\libtorch-debug-latest\\libtorch\\include\\torch\\csrc\\api\\include\\torch\\detail\\TensorDataContainer.h":299, please report a bug to PyTorch. TensorDataContainer is already a Tensor type, `fill_tensor` should not be called
```

## To Reproduce

Run this : 
 
```cpp
auto tmp = torch::ones({2,3});
auto shapes = torch::tensor({tmp.sizes()});
```
## Expected behavior

Shouldnt happen (since it has a `vec()` member which can be automatically used in this case!) or at least should issue a better error message. 

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.6
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip for python, downloaded the prebuilt libraries for libtorch
 - Build command you used (if compiling from source): - 
 - Python version: 3.7
 - CUDA/cuDNN version: - 
 - GPU models and configuration: - 
 - Any other relevant information: I use cpu-mode

cc @yf225 @glaringlee

**Comment by mruberry** [comment] 2020-08-26 04:04
Thank you for reporting this issue, Coderx7. I've cc'd our C++ API experts to review it.

**Comment by glaringlee** [comment] 2020-08-26 14:32
Hi, @Coderx7 
In short, you should call `auto shapes = torch::tensor(tmp.sizes())` with out extra `{}`.

Here is why if you are interested:
I think what happened here is that you thought temp.sizes() will return a vector of size (int), but it is actually not.
`auto tmp = torch::ones({2, 3});` returns a `torch::Tensor`, so `tmp.sizes()` return a `IntArrayRef` which the underlying in your case is a pointer of int. see here if you are interested: 
https://github.com/pytorch/pytorch/blob/9daba76ba12045fca2b9476484ddc4cb34fb7057/c10/util/ArrayRef.h#L52
https://github.com/pytorch/pytorch/blob/9daba76ba12045fca2b9476484ddc4cb34fb7057/c10/util/ArrayRef.h#L52

`auto shapes = torch::tensor({tmp.sizes()});` 
`torch::tensor` is defined here: https://github.com/pytorch/pytorch/blob/9daba76ba12045fca2b9476484ddc4cb34fb7057/tools/autograd/templates/variable_factories.h#L40
`{tmp.sizes()}` will be used to construct a `TensorDataContainer`, so you actually passed an `initialize_list of IntArrayRef` to the constructor of `TensorDataContainer` which will be interpolated into an initialize_list with one tensor (The IntArrayRef within the initialize_list will be interpolated into int64_t I believe and it will be further interpolated into a torch::Tensor obj). This messed up everything.
See the constructors from here:
https://github.com/pytorch/pytorch/blob/954a59a2f5054516e273ce55cb021c1bb76369af/torch/csrc/api/include/torch/detail/TensorDataContainer.h#L101
by removing extra `{}`, you passed an `IntArrayRef` directly which will be converted to vector<int64_t> implicitly.

**Comment by glaringlee** [comment] 2020-08-26 18:42
@Coderx7 
Can I close it?

**Comment by glaringlee** [comment] 2020-08-27 00:52
Per above answer, this is not a bug, close it. Feel free to re-open if needed.

**Closed by glaringlee** 2020-08-27 00:52 UTC
Labels: module: cpp, triaged
