### ISSUE TITLE
KPI: Number of issues resolved

### ISSUE THREAD

**Issue by vladimir-aubrecht** [pytorch/pytorch#87704] opened 2022-10-25 15:02 UTC
Goal of this ticket is find reliable way of how to measure resolved tickets. Meaning when ticket is resolved on our side, but it might not be delivered yet as it's awaiting for merge or something similar.

**Expectations**
- Propose solution for measuring resolved issues
- Go through team review
- Create issue for implementing proposed solution

**Meeting notes**
Following open questions were mentioned in the original meeting
- Based on number of PRs merged?
- What about team members changing? 
- What about contributions without PRs? 
- Include issues closed as invalid? 
- Can leverage labels for distinguishing?

**Comment by iremyux** [comment] 2022-12-06 12:32
Issues closed and related to a pr are now shown in the dashboard. Changing the status to blocked since further discussions needs to be done in order to decide what other issues (that are not necessarily related to a pr) count as 'resolved'.

**Comment by Blackhex** [comment] 2022-12-08 12:24
@iremyux I think we can consider "resolved" all closed issues (https://github.com/orgs/pytorch/projects/27/views/12) that we had any interaction with, i.e. we are either assignees or commented on it. If that will be hard to implement, we consider that only issues we are interacting with are in the `PyTorch On Windows` project, i.e. if the issue is closed but we have not contributed to closing it, it should be removed from the project.

**Comment by vladimir-aubrecht** [comment] 2022-12-08 13:22
> @iremyux I think we can consider "resolved" all closed issues (https://github.com/orgs/pytorch/projects/27/views/12) that we had any interaction with, i.e. we are either assignees, created PRs, or commented on it. If that will be hard to implement, we can consider that only issues we are interacting with are in the `PyTorch On Windows` project, i.e. if the issue is closed but we have not contributed to closing it, it should be removed from the project.

@Blackhex  Do you have in mind how we would use such metric? What I am afraid is, that this metric will have a lot of false positives ... (we commented to plenty of issues which are for example blocked, not resolved ...). On the PRs it could work if it closed PR. And about assignees, I don't think we should stay assigned to the ticket if we don't work on it and ticket is still open ...

**Comment by iremyux** [comment] 2023-08-01 10:48
Closing this issue since implementation of this KPI is no longer a priority.

**Closed by iremyux** 2023-08-01 10:48 UTC
Labels: module: windows, triaged
