### ISSUE TITLE
about the torch.randperm in torch1.8.1+cuda11.1   关于torch1.8.1和cuda11.1环境下randperm函数的奇怪输出

### ISSUE THREAD

**Issue by hjq052070** [pytorch/pytorch#57017] opened 2021-04-27 14:19 UTC
environment: cuda11.1+torch1.8.1
run the code：perm2 = torch.randperm(negative.shape[0], device=negative.device)[:num_neg]
get the result in this picture，obviously the result is weird
But in torch1.7.1+cuda11 or torch1.9（nightly）+cuda11.1 environment，the result is right.
![微信图片_20210427221723](https://user-images.githubusercontent.com/56314930/116257159-5fe22d00-a7a6-11eb-97dd-ffb8a9b089e3.jpg)

**Comment by eqy** [comment] 2021-04-27 18:23
Can you post a shorter repro with a more isolated environment? I cannot reproduce this on the current upstream with ` torch.randperm(128, device='cuda')[:128]`

**Comment by ngimel** [comment] 2021-04-27 20:29
This was fixed on master in #55292

**Comment by H-Huang** [comment] 2021-04-27 22:25
Closing since this is fixed in nightly build

**Closed by H-Huang** 2021-04-27 22:25 UTC
