### ISSUE TITLE
Conv2d padding gradient computation error

### ISSUE THREAD

**Issue by jainshobhit** [pytorch/pytorch#14798] opened 2018-12-05 07:06 UTC
## ❓ Questions and Help

I have a simple convolution class where as follows

```
class ConvLayer(torch.nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        super(ConvLayer, self).__init__()
        reflection_padding = kernel_size // 2
        self.reflection_pad = torch.nn.ReflectionPad2d(reflection_padding)
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride)

    def forward(self, x):
        out = self.reflection_padding(x)
        out = self.conv2d(out)
        return out
```

It works fine if I use this class as it is. However, if I change the class to 

```
class ConvLayer(torch.nn.Module):
    def __init__(self, in_channels, out_channels, kernel_size, stride):
        super(ConvLayer, self).__init__()
        reflection_padding = kernel_size // 2
        self.conv2d = torch.nn.Conv2d(in_channels, out_channels, kernel_size, stride. reflection_padding)

    def forward(self, x):
        out = self.conv2d(x)
        return out
```

It throws the following error during graph computation

```
  File "/home/.local/lib/python2.7/site-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/.local/lib/python2.7/site-packages/torch/autograd/__init__.py", line 90, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation
```

This is a quite strange behavior and I have not yet been able to figure out the cause for this issue even after hours of searching. I am not sure if it is a bug or some error in my implementation.

**Comment by zou3519** [comment] 2018-12-06 18:58
I don't see anything wrong with the Module definition you have provided. Could you provide a minimal example script that we could run to reproduce this error?

**Comment by BeierZhu** [comment] 2020-04-27 08:23
I met the same problem

**Comment by zou3519** [comment] 2020-04-27 17:25
@BeierZhu do you have a script that reproduces the problem you're having?

**Comment by colesbury** [comment] 2020-04-28 14:41
Closing this issue because it's been over a year. @BeierZhu please open a new issue for your problem and include a script that reproduces the issue, if possible.

**Closed by colesbury** 2020-04-28 14:41 UTC
Labels: needs reproduction
