### ISSUE TITLE
SVD MAGMA gesdd : the updating process of SBDSDC did not converge

### ISSUE THREAD

**Issue by ntuyt** [pytorch/pytorch#3002] opened 2017-10-06 13:55 UTC
Hi, when I use tensor.svd(), it reports below error.
Any suggestions to avoid this errors?

Traceback (most recent call last):
  File "maintestlogfast.py", line 304, in <module>
    main()
  File "maintestlogfast.py", line 131, in main
    prec1 = validate(val_loader, model, criterion, (epoch + 1) * len(train_loader))
  File "maintestlogfast.py", line 223, in validate
    output = model(input_var)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 60, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 70, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 67, in parallel_apply
    raise output
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 42, in _worker
    output = module(*input, **kwargs)
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ytan/sharedLocal/tsn-pytorch/modelstestlogfixfast.py", line 229, in forward
    base_out = self.base_model(input.view((-1, sample_len) + input.size()[-2:]))
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ytan/sharedLocal/tsn-pytorch/tf_model_zoo/bninception/pytorch_load.py", line 52, in forward
    data_dict[op[2]] = getattr(self, op[0])(x.view(x.size(0), -1))
  File "/home/ytan/miniconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 224, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/ytan/sharedLocal/tsn-pytorch/bilinearsuffast.py", line 12, in forward
    output = mylog(input)
  File "/home/ytan/sharedLocal/tsn-pytorch/logfunctionfast.py", line 21, in forward
    u,s,v = m6sub.svd()
RuntimeError: MAGMA gesdd : the updating process of SBDSDC did not converge (error: 1) at /opt/conda/conda-bld/pytorch_1503970438496/work/torch/lib/THC/generic/THCTensorMathMagma.cu:325

**Comment by apaszke** [comment] 2017-10-09 11:12
Maybe your matrices are very badly conditioned? How do you generate them?

**Comment by stsievert** [comment] 2017-12-04 02:04
I believe I'm also running into this error. Here's the end of the traceback:

> RuntimeError: MAGMA gesdd : the updating process of SBDSDC did not converge (error: 8) at /opt/conda/conda-bld/pytorch_1503965122592/work/torch/lib/THC/generic/THCTensorMathMagma.cu:325


Turns out my matrices are badly conditioned – I had numbers on the order of 1e38. Fixing this resolved the problem.


Note I see "(error: 8)" not "(error: 1)" as above. Looking at [sbdsdc.f], I see that the number is described as 

> INFO    (output) INTEGER
         = 0:  successful exit.
         < 0:  if INFO = -i, the i-th argument had an illegal value.
         > 0:  The algorithm failed to compute an singular value.
               The update process of divide and conquer failed.

[sgesdd.f]:http://www.netlib.org/lapack/lapack-3.1.1/html/sgesdd.f.html
[sbdsdc.f]:http://www.netlib.org/lapack/lapack-3.1.1/html/sbdsdc.f.html#SBDSDC.1

**Comment by nbansal90** [comment] 2018-02-19 05:34
@stsievert I am getting the same issue. How do you make sure that the matrix are not badly conditioned?

**Comment by stsievert** [comment] 2018-02-19 14:27
It was specific to my problem formulation.

I was dividing parts of the matrix by small values (less than 1e-6). Before division, I put in a check to make sure the value was large enough and that worked.

**Comment by vishwakftw** [comment] 2018-09-05 08:26
Is this issue resolved? From what I gather, it seems like ill-conditioned matrices were causing the issue.

**Comment by stsievert** [comment] 2018-09-05 19:37
After I resolved the problem formulation, the error went away. At best, I think a more informative error message could be raised.

**Comment by twmht** [comment] 2019-02-13 04:53
Having the same problem, it's weird that this issue happens randomly with fixed random seed.

**Comment by vishwakftw** [comment] 2019-07-29 09:29
Closing as this is not a bug.

**Closed by vishwakftw** 2019-07-29 09:29 UTC

**Comment by yaroslavvb** [comment] 2019-09-11 15:25
Ran into the same issue. This seems to be a feature of underlying algorithm (GESDD) and can be fixed by improving condition number to be better than 8000. GESVD seems to not have this problem, so if you care about tiny singular values, a workaround is to use scipy with lapack_driver `gesvd` 
https://github.com/pytorch/pytorch/issues/25978
