### ISSUE TITLE
Computing conv grads via nn.grad raises ValueError when using dilation>1

### ISSUE THREAD

**Issue by bbartoldson** [pytorch/pytorch#13008] opened 2018-10-23 22:14 UTC
## 🐛 Bug

The conv grads computed by https://github.com/pytorch/pytorch/blob/master/torch/nn/grad.py rely on the function ```_grad_input_padding()``` (from the same file). ```_grad_input_padding()``` raises a ValueError when ```dilation```>1 because  it does not account for ```dilation``` when computing its expected input size.

## To Reproduce

The following snippet appears to correctly create a grad with respect to the input  via ```torch.autograd.grad``` with dilation=2 (stored in ```grad_input```). We should be able to get the same grad by using ```torch.nn.grad.conv2d_input()```, but attempting to do so leads to a ValueError raised by ```_grad_input_padding()``` when dilation>1:

```python
import torch
import torch.nn.functional as F
input = torch.randn(1,1,5,5, requires_grad=True)
weight = torch.randn(1,1,3,3, requires_grad=True)
output = F.conv2d(input, weight, dilation=2)
grad_output = torch.randn(output.shape)
grad_input = torch.autograd.grad(output, input, grad_output)
torch.nn.grad.conv2d_input(input.shape, weight, grad_output, dilation=2)
```

## Error message: 

>File "/home/.../anaconda3/lib/python3.7/site-packages/torch/nn/grad.py", line 29, **in _grad_input_padding**
    grad_output.size()[2:]))

>ValueError: requested an input grad size of [5, 5], but valid sizes range from [3, 3] to [3, 3] (for a grad_output of torch.Size([1, 1]))

[As we would expect with a 5x5 input, 3x3 kernel, and dilation=2](https://ezyang.github.io/convolution-visualizer/index.html), the output size is [1,1]. According to ```_grad_input_padding()```, the only possible input size was [3,3]. I believe the fix is to make ```_grad_input_padding()``` account for ```dilation```. In this case, accounting for dilation would allow this function to know that  [5,5] is the only acceptable input size.

 - PyTorch 0.4.1 installed via conda
 - Ubuntu 18
 - Python 3.7

**Comment by bbartoldson** [comment] 2018-10-28 07:08
The following approach seems to allow me to compute gradients with respect to inputs that have gone through a filter with ```dilation```>1.

In the function ```_grad_input_padding()``` in the file https://github.com/pytorch/pytorch/blob/master/torch/nn/grad.py, change the definition of ```dim_size()``` to
```python
def dim_size(d):
     return ((grad_output.size(d + 2) - 1) * stride[d] - 2 * padding[d] + 
                kernel_size[d] + (kernel_size[d] - 1) *  (dilation[d] - 1))
```
and add ```dilation``` to the args of ```_grad_input_padding()```.

My approach to fixing this problem seems wrong, however, because I believe ```_grad_input_padding()```will always return a tuple of 0s after my "fix".

**Comment by ggggggggbahugoa** [comment] 2019-04-08 16:39
Have you solved this problem? I also encountered this error.
Thx.

**Comment by bbartoldson** [comment] 2019-04-08 17:21
I did not solve the problem, but this issue has gotten noticed since you commented, so it may be addressed.

**Comment by ggggggggbahugoa** [comment] 2019-04-08 17:25
I solve this problem!!!
https://github.com/pytorch/pytorch/issues/16012
Follow the steps to change the program!!!

**Comment by albanD** [comment] 2020-02-09 02:19
Closing in favor of https://github.com/pytorch/pytorch/issues/16012 that is the root cause for this issue.

**Closed by albanD** 2020-02-09 02:19 UTC
Labels: module: autograd, module: nn, triaged
