### ISSUE TITLE
cufft errors after lots of plan generation

### ISSUE THREAD

**Issue by isaacgerg** [pytorch/pytorch#11089] opened 2018-08-30 16:08 UTC
Regarding https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/CuFFTPlanCache.h
section starting at 281.  Has this bug been confirmed by NVIDIA or at least filed formally?  

@mruberry @SsnL

**Comment by SsnL** [comment] 2018-08-30 16:29
We have informed NVIDIA about this bug/behavior we observed. But I haven't asked them if they reproduced it.

**Comment by mruberry** [comment] 2018-08-30 16:32
I've notified the appropriate person at NVIDIA. They made a need a few days to respond to this particular issue.

**Comment by syed-ahmed** [comment] 2018-08-30 17:26
Thanks for following-up on this. I'm investigating on our end.

**Comment by syed-ahmed** [comment] 2018-09-08 06:15
We reproduced and fixed the bug on our end and won't be needing `CUFFT_MAX_PLAN_NUM` in the future.

**Comment by syed-ahmed** [comment] 2018-09-10 17:27
Unfortunately I don't have a timeline for you, but I have put this on my todo list to clean up the `CuFFTPlanCache.h` file when the time comes :)

**Comment by isaacgerg** [comment] 2018-09-26 15:15
@syed-ahmed Hy Syed. Just a friendly ask if there is any progress in NVIDIA land in providing a fix for this.

**Comment by syed-ahmed** [comment] 2018-09-26 18:04
As of CUDA 10 release last week, the bug has been fixed in cuFFT and I have updated the note here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/cuda/CuFFTPlanCache.h#L349. Also, I have added CUDA 10 guards to `CuFFTPlanCache.h` through this commit https://github.com/pytorch/pytorch/commit/ffbac7d0bb4e0772cab0054f79339478124ea9aa. Hence, if you compile PyTorch with CUDA 10, the cufft plan cache array should grow as intended without failing at the 1024th plan. I have tested this commit by building pytorch with CUDA 10 and running the test suite successfully.

Please let me know if there are any other queries regarding this issue. Otherwise, I think we are good to close this issue.

**Comment by isaacgerg** [comment] 2018-09-26 18:08
Thank you. I am okay if you close.

**Closed** 2018-09-26 18:18 UTC
