### ISSUE TITLE
Torch.compile don't seem to work properly with einops

### ISSUE THREAD

**Issue by nicolas-dufour** [pytorch/pytorch#99031] opened 2023-04-13 11:43 UTC
### 🐛 Describe the bug

Torch.compile don't seem to give reliable improvements with einops vs doing the exact same operations but with torch ops.

Einops is loved by a lot of people in the community and it would be great to be able to make it torch.compile compatible in the future.

Here is an issue in the einops repo describing the observation, it would be very much appreciated to have some input from torch dynamo experts!
https://github.com/arogozhnikov/einops/issues/250 

### Versions

pytorch 2.0 einops 0.6, Nvidia 3090

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by wconstab** [comment] 2023-04-13 16:41
Just a note for those looking  here, the main discussion is happening on the linked PR https://github.com/arogozhnikov/einops/issues/250 and the TLDR so far is that einops got added to skipfiles which makes using einops really slow, but there were issues with einops in torchbench which is why they got skipped in the first place.

**Comment by ngimel** [comment] 2023-04-13 18:32
duplicate of #93905

**Closed by ngimel** 2023-04-13 18:32 UTC
Labels: oncall: pt2, module: dynamo
