### ISSUE TITLE
XLA test jobs generate huge amounts of log spew

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#77286] opened 2022-05-11 20:11 UTC
Example: https://github.com/pytorch/pytorch/runs/6380089574?check_suite_focus=true

It looks like somewhere we are tricking the tests into thinking we're running from an attended terminal. This causes us to spew interactive log output to the logs, like:
```
[10,652 / 10,950] 8 actions running
    Compiling .../kernels/batchtospace_op.cc; 12s processwrapper-sandbox
    Compiling .../tf2xla/kernels/sendrecv_ops.cc; 11s processwrapper-sandbox
    Compiling .../tf2xla/kernels/broadcast_to_op.cc; 6s processwrapper-sandbox
    Compiling .../tf2xla/kernels/categorical_op.cc; 5s processwrapper-sandbox
    Compiling .../tf2xla/kernels/dequantize_op.cc; 5s processwrapper-sandbox
    Compiling .../tf2xla/kernels/softmax_op.cc; 4s processwrapper-sandbox
    Compiling .../tf2xla/kernels/cwise_ops.cc; 0s processwrapper-sandbox
    Compiling .../tf2xla/kernels/device_index_op.cc; 0s processwrapper-sandbox









[10,653 / 10,950] 8 actions running
    Compiling .../tf2xla/kernels/sendrecv_ops.cc; 11s processwrapper-sandbox
    Compiling .../tf2xla/kernels/broadcast_to_op.cc; 7s processwrapper-sandbox
    Compiling .../tf2xla/kernels/categorical_op.cc; 5s processwrapper-sandbox
    Compiling .../tf2xla/kernels/dequantize_op.cc; 5s processwrapper-sandbox
    Compiling .../tf2xla/kernels/softmax_op.cc; 5s processwrapper-sandbox
    Compiling .../tf2xla/kernels/cwise_ops.cc; 0s processwrapper-sandbox
    Compiling .../tf2xla/kernels/device_index_op.cc; 0s processwrapper-sandbox
    Compiling .../kernels/dynamic_partition_op.cc; 0s processwrapper-sandbox









```

This is bad because it causes logs to take a log time to load in GitHub, and it also makes things very noisy for people when trying to find errors.

cc @bdhirsh

**Comment by suo** [comment] 2022-05-11 20:11
cc @JackCaoG mind looking

**Comment by JackCaoG** [comment] 2022-05-11 20:19
@yeounoh Do you know if it is caused by the sandbox technique to bypass the build failure for tf?

**Comment by yeounoh** [comment] 2022-05-11 23:18
Thanks, will take a look.

**Comment by yeounoh** [comment] 2022-05-12 23:32
Hi @suo is the issue the amount of log? If I remember correctly the XLA test workflow always dumped a lot of logs as it builds & test in the same run. If that's the case, we can try to come up with a plan to move the build into the previous build phase (we only build PyTorch there), so that the test logging is more lighter.

Otherwise, I am not sure if I follow the "attended terminal" part. I am happy to sync offline, too.

**Comment by yeounoh** [comment] 2022-05-17 14:16
I am not sure how much of help this would be to reduce the amount of logs, but this one is testing cloud caching for build: https://github.com/pytorch/pytorch/runs/6472302741?check_suite_focus=true. Technically, every cache hit could generate less linens of interactive outputs.

**Comment by suo** [comment] 2022-05-23 19:16
yep!

**Comment by yeounoh** [comment] 2022-05-23 20:45
Thanks @suo , the fix has landed. Closing.

**Closed by yeounoh** 2022-05-23 20:45 UTC
Labels: triaged, module: xla
