### ISSUE TITLE
torch.inverse() performing very poorly on GPU vs CPU

### ISSUE THREAD

**Issue by sandeepkumar-skb** [pytorch/pytorch#42265] opened 2020-07-29 23:53 UTC
## 🐛 Bug
We observed a big increase in inference latency after adding `torch.inverse()` in the code path. After investigation and comparison with moving the op to CPU we found that there is a huge difference in performance of that op on GPU vs CPU.
The matrix size in our case is 4x4 which small for the GPU but `torch.inverse()` should be using `magma` library which has heuristics to move the op to CPU. We didn't see any magma invocations as well.

Based on @ptrblck suggestion we tried `inverse` on batched matrix to see if that made any difference but that also didn't result in any improvement.

**Performance Difference:**
```
╰─ python torch_inverse_exp.py
GPU Time: 8.78560 ms
CPU Time: 0.07149 ms
cpu/gpu: 122.90x
```
We increased the matrix dimensions to 1024x1024 but even then GPU is slower than CPU:
```
╰─ python torch_inverse_exp.py
GPU Time: 17.25289 ms
CPU Time: 9.54982 ms
cpu/gpu: 1.81x
```
## To Reproduce
Here is the snippet of code which can be run to reproduce the performance difference:
```
import torch
import time

a = torch.randn(4,4).cuda()
torch.cuda.synchronize()

num_iter = 100
def test1():
    s = time.time()
    for i in range(num_iter):
        x = torch.inverse(a)
    torch.cuda.synchronize()
    e = time.time()
    gpu_time = ((e - s)/num_iter)
    return  gpu_time

def test2():
    s = time.time()
    for i in range(num_iter):
        b = a.to('cpu')
        d = torch.inverse(b)
        y = d.to('cuda')
    torch.cuda.synchronize()
    e = time.time()
    cpu_time = ((e - s)/num_iter)
    return  cpu_time

gpu_time = test1()
print("GPU Time: {:.5f} ms".format(gpu_time*1000))

cpu_time = test2()
print("CPU Time: {:.5f} ms".format( cpu_time*1000))

print("cpu/gpu: {:.2f}x ".format(gpu_time/cpu_time))
```
**Run:** `python <script_name>`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py

Collecting environment information...
PyTorch version: 1.5.1 (pip package)
Is debug build: No
CUDA used to build PyTorch: 10.1 & 10.2 (NGC 20.03 container)

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
CMake version: version 3.17.3

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: TITAN RTX
GPU 1: TITAN RTX

Nvidia driver version: 440.100
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] numpydoc==1.1.0
[pip3] torch==1.5.1
[pip3] torchvision==0.6.0a0+35d732a
[pip3] torchviz==0.0.1
[conda] _pytorch_select           0.2                       gpu_0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.1                      217
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.1.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.18.5           py37ha1c710e_0
[conda] numpy-base                1.18.5           py37hde5b4d6_0
[conda] numpydoc                  1.1.0                      py_0
[conda] pytorch                   1.5.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.6.1                py37_cu101    pytorch
[conda] torchviz                  0.0.1                    pypi_0    pypi
```

@ptrblck @ngimel for visibility

cc @ngimel @vincentqb @vishwakftw @SsnL @jianyuh @VitalyFedyunin

**Comment by ptrblck** [comment] 2020-07-30 00:02
@xwang233 could you try to grab the nsight profiles and check the call trace for these methods, please?

**Comment by xwang233** [comment] 2020-07-30 23:05
I can reproduce this slow GPU impl on CUDA 11 + magma 2.5.4 and CUDA 10.2 + magma 2.5.1.

Testing script
```py
x = torch.randn(4, 4, device='cuda', dtype=torch.float)
with torch.autograd.profiler.emit_nvtx():
    y = torch.inverse(x)
```

nvprof nvtx results:
```
==3746000==       Range "aten::_inverse_helper, seq = 0"
            Type  Time(%)      Time     Calls       Avg       Min       Max  Name
          Range:  100.00%  1.56590s         1  1.56590s  1.56590s  1.56590s  aten::_inverse_helper, seq = 0
 GPU activities:   17.60%  7.2320us         7  1.0330us     800ns  1.3760us  [CUDA memcpy HtoD]
                   13.86%  5.6960us         1  5.6960us  5.6960us  5.6960us  strtri_diag_lower_kernel(magma_diag_t, int, float const *, int, float*)
                   11.14%  4.5760us         2  2.2880us  1.8560us  2.7200us  slacpy_full_kernel(int, int, float const *, int, float*, int)
                    8.26%  3.3920us         3  1.1300us  1.0560us  1.2480us  sswap_kernel(int, float*, int, float*, int)
                    7.55%  3.1040us         1  3.1040us  3.1040us  3.1040us  void gemmSN_NN_kernel<float, int=256, int=4, int=2, int=8, int=4, int=4, bool=0, cublasGemvTensorStridedBatched<float const >, cublasGemvTensorStridedBatched<float>>(cublasGemmSmallNParams<float const , cublasGemvTensorStridedBatched<float const >, float>)
                    7.17%  2.9440us         1  2.9440us  2.9440us  2.9440us  triple_sgemm16_part1_lower_kernel(int, float const *, int, float*, int, int)
                    7.09%  2.9120us         2  1.4560us  1.3760us  1.5360us  [CUDA memcpy DtoH]
                    6.39%  2.6240us         2  1.3120us  1.1520us  1.4720us  [CUDA memset]
                    6.31%  2.5920us         1  2.5920us  2.5920us  2.5920us  _ZN2at6native27unrolled_elementwise_kernelIZZZNS0_21copy_device_to_deviceERNS_14TensorIteratorEbENKUlvE0_clEvENKUlvE2_clEvEUlfE_NS_6detail5ArrayIPcLi2EEE16OffsetCalculatorILi1EjESC_NS0_6memory15LoadWithoutCastENSD_16StoreWithoutCastEEEviT_T0_T1_T2_T3_T4_
                    6.07%  2.4960us         1  2.4960us  2.4960us  2.4960us  triple_sgemm16_part2_lower_kernel(int, float const *, int, float*, int, int)
                    5.14%  2.1120us         1  2.1120us  2.1120us  2.1120us  slaset_lower_kernel(int, int, float, float, float*, int)
                    3.43%  1.4080us         1  1.4080us  1.4080us  1.4080us  slaset_full_kernel(int, int, float, float, float*, int)
      API calls:   45.73%  184.35us        12  15.362us  5.5090us  42.844us  cudaLaunchKernel
                   27.13%  109.36us         5  21.872us  15.111us  37.428us  cudaMemcpy
                   19.57%  78.875us         4  19.718us  12.290us  29.233us  cudaMemcpyAsync
                    5.04%  20.326us         1  20.326us  20.326us  20.326us  cudaMemsetAsync
                    2.53%  10.183us         1  10.183us  10.183us  10.183us  cudaMemset
```

It seems like there are some memcpy between host and device. I guess this code is the culprit 
https://github.com/pytorch/pytorch/blob/e98ad6c05b21f9ee04447de69e809af42f4e114a/aten/src/ATen/native/cuda/BatchLinearAlgebra.cu#L703-L705

`Tensor ipiv` is initiated on CPU, but later passed to `magma_sgetrf_gpu` [[ref]](https://icl.cs.utk.edu/projectsfiles/magma/doxygen/group__magma__getrf.html#gae1751a9b0d4ca3137eb6fbcd28ea2d55) as an integer pointer. I tried modifying that to
```cpp
Tensor ipiv = at::empty({n}, self.options().dtype(at::kInt));
```
but `magma_sgetrf_gpu` gives `segmentation fault (core dumped)` instead. 

@vishwakftw do you have time to take a look?

**Comment by mkolod** [comment] 2020-08-01 20:03
For more context, here's an implementation of sgetri_gpu from MAGMA 2.5.3. This particular file is code-generated, so can't be found int he MAGMA source, but I'm copying from magma/src after a make build: 

```
 it looks like PyTorch is using MAGMA, but MAGMA is doing insane stuff. Al the stupid calls like slacpy, slaset, strtri etc. are in the source that’s code-generated from core MAGMA:
extern "C" magma_int_t
magma_sgetri_gpu(
    magma_int_t n,
    magmaFloat_ptr dA, magma_int_t ldda, magma_int_t *ipiv,
    magmaFloat_ptr dwork, magma_int_t lwork,
    magma_int_t *info )
{
    #define dA(i, j)  (dA + (i) + (j)*ldda)
    #define dL(i, j)  (dL + (i) + (j)*lddl)
****
    /* Constants */
    const float c_zero    = MAGMA_S_ZERO;
    const float c_one     = MAGMA_S_ONE;
    const float c_neg_one = MAGMA_S_NEG_ONE;
****
    /* Local variables */
    magmaFloat_ptr dL;
    magma_int_t nb = magma_get_sgetri_nb( n );
    magma_int_t j, jmax, jb, jp, lddl;
****
    *info = 0;
    if (n < 0)
        *info = -1;
    else if (ldda < max(1,n))
        *info = -3;
    else if ( lwork < n*nb )
        *info = -6;
    if (*info != 0) {
        magma_xerbla( __func__, -(*info) );
        return *info;
    }
    /* Quick return if possible */
    if ( n == 0 )
        return *info;
****
    if (lwork >= ldda*n) {
        lddl = ldda;
    }
    else {
        lddl = n;
    }
    dL = dwork;
****
    /* Invert the triangular factor U */
    magma_strtri_gpu( MagmaUpper, MagmaNonUnit, n, dA, ldda, info );
    if ( *info != 0 )
        return *info;
****
    magma_queue_t queue = NULL;
    magma_device_t cdev;
    magma_getdevice( &cdev );
    magma_queue_create( cdev, &queue );
****
    jmax = ((n-1) / nb)*nb;
    for( j = jmax; j >= 0; j -= nb ) {
        jb = min( nb, n-j );
********
        // copy current block column of A to work space dL
        // (only needs lower trapezoid, but we also copy upper triangle),
        // then zero the strictly lower trapezoid block column of A.
        magmablas_slacpy( MagmaFull, n-j, jb,
                          dA(j,j), ldda,
                          dL(j,0), lddl, queue );
        magmablas_slaset( MagmaLower, n-j-1, jb, c_zero, c_zero, dA(j+1,j), ldda, queue );
********
        // compute current block column of Ainv
        // Ainv(:, j:j+jb-1)
        //   = ( U(:, j:j+jb-1) - Ainv(:, j+jb:n) L(j+jb:n, j:j+jb-1) )
        //   * L(j:j+jb-1, j:j+jb-1)^{-1}
        // where L(:, j:j+jb-1) is stored in dL.
        if ( j+jb < n ) {
            magma_sgemm( MagmaNoTrans, MagmaNoTrans, n, jb, n-j-jb,
                         c_neg_one, dA(0,j+jb), ldda,
                                    dL(j+jb,0), lddl,
                         c_one,     dA(0,j),    ldda, queue );
        }
        // TODO use magmablas work interface
        magma_strsm( MagmaRight, MagmaLower, MagmaNoTrans, MagmaUnit,
                     n, jb, c_one,
                     dL(j,0), lddl,
                     dA(0,j), ldda, queue );
    }
    // Apply column interchanges
    for( j = n-2; j >= 0; --j ) {
        jp = ipiv[j] - 1;
        if ( jp != j ) {
            magmablas_sswap( n, dA(0,j), 1, dA(0,jp), 1, queue );
        }
    }
****
    magma_queue_destroy( queue );
****
    return *info;
}
```

Indeed, it looks like cuSOLVER use is the best solution here.

Thanks @xwang233 for the PR!

@ptrblck @ngimel ^^

**Comment by vishwakftw** [comment] 2020-08-01 20:28
At the outset, I raised this issue a long time back https://github.com/pytorch/pytorch/issues/13546.

Can you try benchmarking the implementations - I'm not sure how different the speeds are - although TensorFlow is as fast as LAPACK for this problem size, and IIRC, TensorFlow uses cuSolver.

Re: `ipiv`, yes, MAGMA expects storage on the CPU. If I remember correctly, for small matrices, MAGMA resorts to running it on LAPACK and then transferring the data back to the GPU. You can see this in the following implementation of `magma_strtri_gpu` in used in `magma_sgetri_gpu`.

```
    /* Determine the block size for this environment */
    nb = magma_get_spotrf_nb(n);

    if (MAGMA_SUCCESS != magma_smalloc_pinned( &work, nb*nb )) {
        *info = MAGMA_ERR_HOST_ALLOC;
        return *info;
    }

    magma_queue_t queues[2];
    magma_device_t cdev;
    magma_getdevice( &cdev );
    magma_queue_create( cdev, &queues[0] );
    magma_queue_create( cdev, &queues[1] );

    if (nb <= 1 || nb >= n) {
        magma_sgetmatrix( n, n, dA(0,0), ldda, work, n, queues[0] );
        lapackf77_strtri( uplo_, diag_, &n, work, &n, info );
        magma_ssetmatrix( n, n, work, n, dA(0,0), ldda, queues[0] );
    }
```

**Comment by mkolod** [comment] 2020-08-08 00:48
@vishwakftw The issue is precisely because the code in question is being ported from TensorFlow, where the inverses for various matrix sizes run about 2 orders of magnitude faster. :)

**Closed** 2020-09-19 03:49 UTC
Labels: module: cuda, topic: linear algebra, topic: performance, triaged

**Comment by Mapoet** [comment] 2021-11-01 04:40
the reason to this issues is that too small rank of matrix to be solved, you can test with rank greater than 4000, it would show the significant improvement.
the follow is what i modified and the result:
```
a = torch.randn(4000,4000).cuda()
torch.cuda.synchronize()
num_iter = 1
```
the result is:
```
GPU Time: 114.15434 ms
CPU Time: 460.38413 ms
cpu/gpu: 0.25x 
```
