### ISSUE TITLE
Native Declared Functions Don't Support Full Aliasing Specification

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#30526] opened 2019-11-27 19:07 UTC
## 🐛 Bug

Trying to register the following function:
```
- func: _amp_non_finite_check_and_unscale_(Tensor(a!) self, Tensor(b!) found_inf, Tensor inv_scale) -> (Tensor(a!), Tensor(b!))
  variants: function                                                                               
  dispatch:                                                                                           
    CUDA: _amp_non_finite_check_and_unscale_cuda 
```

Gives the error: 

> Nov 22 06:03:31 AssertionError: aten::_amp_non_finite_check_and_unscale_(Tensor(a!) self, Tensor(b!) found_inf, Tensor inv_scale) -> (Tensor(a!), Tensor(b!)) is flagged as JIT signature compliant, but does not match the signature aten::_amp_non_finite_check_and_unscale_(Tensor(a!) self, Tensor found_inf, Tensor inv_scale) -> (Tensor(a!), Tensor)

Even though the the function is correctly declared. I have also seen this bug with:

```
AssertionError: aten::floor_div(Tensor(a) self, Tensor(b) other) -> Tensor(c) is flagged as JIT signature compliant, but does not match the signature aten::floor_div(Tensor self, Tensor other) -> Tensor
```

I was able to workaround the `floor_div` decl by removing the annotations, but I shouldn't have to, and there is no workaround for `_amp_non_finite_check_and_unscale_` decl.

## Expected behavior

Correct aliasing annotations should work. see aliasing note [here](https://github.com/pytorch/pytorch/blob/c800591030bf8baf69da5d721be9a56633ee9cfb/aten/src/ATen/native/README.md#func)

cc @suo

**Comment by eellison** [comment] 2019-11-27 21:10
In the case of `floor_div` it looks like the schema is being canonicalized wrt aliasing, and compared to the input schema. The input schema should be canonicalized as well. In the case of `_amp_non_finite_check_and_unscale_` the canonicalized schema looks like a bug: `aten::amp_non_finite_check_and_unscale(Tensor(a!) self, Tensor found_inf, Tensor inv_scale) -> (Tensor(a!), Tensor)` loses the writes on found_inf. 

cc @suo

**Comment by mcarilli** [comment] 2019-12-02 21:49
I can also work around by removing the annotations, but i’d rather not, because then my schema won’t be telling the whole truth about its inplace effects and aliasing.

**Comment by mcarilli** [comment] 2020-01-14 00:12
I think it's still broken as of this afternoon, although now it's a new error message (link time rather than parse time).  My native_functions.yaml declaration is
```
- func: _amp_non_finite_check_and_unscale_(Tensor(a!) self, Tensor(b!) found_inf, Tensor inv_scale) -> ()
```
My function signature (as manually written in aten/native/cuda/AmpKernels.cu) is
```
void _amp_non_finite_check_and_unscale_cuda_(Tensor& scaled_grad,
                                             Tensor& found_inf,
                                             const Tensor& inv_scale)
```
The error I see is in the final linking phase:
```
/home/mcarilli/Desktop/mcarilli_github/pytorchquickedits/build/lib/libtorch_cuda.so: undefined reference to `at::native::_amp_non_finite_check_and_unscale_cuda_(at::Tensor&, at::Tensor const&, at::Tensor const&)'
```
In the autogenerated build/aten/src/ATen/Functions.h, I see
```
static inline void _amp_non_finite_check_and_unscale_(Tensor & self, const Tensor & found_inf, const Tensor & inv_scale);
```
The codegen is making `found_inf` a `const Tensor &` even though the native_functions.yaml specifies `Tensor(b!) found_inf`, which should make it non-const `Tensor &`.

I can manually lie and declare `found_inf` as const in my function signature, ie
```
void _amp_non_finite_check_and_unscale_cuda_(Tensor& scaled_grad,
                                             const Tensor& found_inf,
                                             const Tensor& inv_scale)
```
in which case everything compiles/links (and runs) fine.  But `found_inf` IS modified in place by the function, so this makes me uncomfortable.

**Comment by bhosmer** [comment] 2020-01-14 19:39
Hi @mcarilli - thanks for flagging this. Per @eellison the root cause is some old assumptions being made in the codegen pipeline - should be fixable without tearing up a bunch of sidewalk, though not trivial - might take a week or two for it to land. Hopefully your workaround will tide you over until then?

**Comment by mcarilli** [comment] 2020-01-14 20:52
@bhosmer Understood, thanks!  My workaround is in a PR that's not yet merged, and some other aspects are still under review, so if the build fix takes a week to land that's not a huge problem.

**Comment by mcarilli** [comment] 2020-01-23 19:38
@bhosmer How's this going?  Is there a WIP PR I can track, or test with?

**Comment by bhosmer** [comment] 2020-01-23 20:26
Hey @mcarilli - yeah, sorry for the radio silence! There's a few intersecting considerations... working on it this afternoon and will update by EOD

**Comment by mcarilli** [comment] 2020-01-23 20:44
Excellent, thank you very much!

**Comment by bhosmer** [comment] 2020-01-24 09:37
@mcarilli it's before EOD in Hawaii, where I might well be typing this right now.
#32574 should observe the annotations properly - the correct types appear to be there in the generated code for your example signature. Per the comments in the PR there may need to be a followup before landing due to a small unrelated codegen delta, but meanwhile, LMK if you try this and run into any issues!

**Comment by mcarilli** [comment] 2020-01-24 18:25
Thanks!  You flew to Hawaii just to give yourself a longer day to work on it?  That's going above and beyond.  Do I need to cherry pick both PRs from the stack, or is https://github.com/pytorch/pytorch/pull/32574 alone sufficient?

**Comment by bhosmer** [comment] 2020-01-24 23:09
@mcarilli ahahah well that's a charitable way of looking at it, another would be that the unintended consequences multiplied to fill available time :P ...apropos of which, sorry I didn't come back with an answer earlier, had to actually fix some test failures before you'd be able to use it at all. 

Still some failures but all cosmetic so far, so probably fine to try out. And yeah #32574 should be all you need.

**Closed** 2020-01-30 22:02 UTC
Labels: jit, triaged

**Comment by mcarilli** [comment] 2020-01-31 21:23
After pulling in master, my build succeeds with the right signature.  Thank you very much!

**Comment by bhosmer** [comment] 2020-01-31 21:56
Excellent! thanks for raising the issue (and your patience :)

**Comment by mcarilli** [comment] 2020-01-31 22:17
https://xkcd.com/541/
