### ISSUE TITLE
Cpu memory leak when only doing model forwarding in a loop

### ISSUE THREAD

**Issue by jsyx1994** [pytorch/pytorch#22127] opened 2019-06-24 07:13 UTC
## To Reproduce
Cpu memory leak when only doing model forwarding in a loop

define the model as simple as :
```
class TestLeakModel(nn.Module):
    def __init__(self):
        super(TestLeakModel,self).__init__()
        self.conv1 = nn.Conv2d(in_channels=18, out_channels=16, kernel_size=3, padding=1)   # WEIGHTs ARE INITED
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3,
                               padding=1)  # WEIGHTs ARE INITED
        self.conv3 = nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3, padding=1)
        self.conv4 = nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3, padding=1)  # WEIGHTs ARE INITED
        self.conv5 = nn.Conv2d(in_channels=16, out_channels=16, kernel_size=3,
                               padding=1)  # WEIGHTs ARE INITED
        self.fc1 = nn.Linear(in_features=64*16, out_features=128)
        self.fc2 = nn.Linear(in_features=128, out_features=128)
        self.fc3 = nn.Linear(in_features=128, out_features=128)
        self.fc4 = nn.Linear(in_features=128, out_features=128)
        self.fc5 = nn.Linear(in_features=128, out_features=128)
        self.fc6 = nn.Linear(in_features=128, out_features=7)

    def forward(self, input):
        x = self.conv1(input)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.conv4(x)
        x = self.conv5(x)

        x = Flatten()(x)
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        x = self.fc4(x)
        x = self.fc5(x)
        x = self.fc6(x)

        x = F.softmax(x)
        return x
```
and write the test program as:
```
def test():
    x = torch.randn((1, 18, 8, 8))
    import gc
    for i in range(10000000):
        # gc.collect()
        with torch.no_grad():
            testmodel.forward(x)

```

## Expected behavior
look into the system monitor, the related python process's memory should be stable. but in fact the memory increase over time.

## Environment

 - PyTorch Version ( 1.1):
 - OS (Linux & OSX):
 - How you installed PyTorch (`pip`):
 - Python version: 3.6 & 3.7
 - Any other relevant information: when using gc.collect(), the increasing becomes slow, however it won't help since i want to use LSTM layers(quickly out of memory)

## Additional context

I am writing a reinforcement learning program, during every episode(in loops) I will do model forwardings. This memory leak problem is vital.

**Comment by fmassa** [comment] 2019-06-24 13:17
This might be related to https://github.com/pytorch/vision/issues/984#issuecomment-498603088, and is due to the implementation of malloc.

Can you try using `jemalloc` instead?

**Comment by zou3519** [comment] 2019-06-24 21:30
@jsyx1994 Another way to check if it is a real memory leak is to see if your program ever OOMs.

**Comment by yf225** [comment] 2019-06-26 03:19
@jsyx1994 Could you try out @fmassa 's and @zou3519 's suggestions, and let us know the result of your experiments?

**Comment by jsyx1994** [comment] 2019-06-27 02:46
emm...Sorry for the late reply and thanks for your suggestions. I have tried to use ```LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision python3 test.py``` in terminal and that works fine.  But I think the main problem is that I ran 'test.py' in **Pycharm IDE** before, since I type `python3 test.py` in terminal it works fine too.

**Comment by jsyx1994** [comment] 2019-06-27 03:41
I test ```LD_PRELOAD=`jemalloc-config --libdir`/libjemalloc.so.`jemalloc-config --revision` python3 ~/PycharmProjects/Coola_RTS/ServerAI.py``` on ubuntu. It seems no use.

**Comment by FerranPares** [comment] 2020-01-09 17:54
I have the same problem here. I tried to solve it using `jemalloc` with no success.

I would consider that a memory leak on model forwarding should be a high priority. However, this issue seems to be in standby for more than half a year. Any advance so far on this topic?

**Comment by albanD** [comment] 2020-01-09 19:24
Does the program actually OOM?  Or you only see memory increase?

In the last investigation, there was no memory leak in the forward. Just that `malloc` behavior make it buffer more and more memory (but you will never OOM as you can reuse it in this process).

**Comment by FerranPares** [comment] 2020-01-10 10:07
I just tried to reproduce the error with the same code that @jsyx1994 posted and I don't see that memory increases in 1000 steps. I have another code similar to this one and increases the memory a lot per step but guess this may be caused by another reason. I'm going to create a different issue for it then.

**Comment by albanD** [comment] 2020-01-10 14:42
Tentatively closing this as we cannot reproduce. Please re-open if you still see actual OOM errors.

**Closed by albanD** 2020-01-10 14:42 UTC
Labels: topic: memory usage, triaged
