### ISSUE TITLE
[Dynamo] torch.autocast context manager doesn't support graph break 

### ISSUE THREAD

**Issue by drisspg** [pytorch/pytorch#93890] opened 2023-02-01 23:51 UTC
### 🐛 Describe the bug

I wrote a unittest that is being skipped to track this failure:
https://github.com/pytorch/pytorch/pull/92917/files#diff-0daa64329e2d8648fc119f7809dc810c744508d345ea023116614ccc17e57dbeR2708

When raising the unimplemented here: https://github.com/pytorch/pytorch/pull/92917/files#diff-7bd43c6b174845f3450be42c8460ed021d1b39a98510cbea5d4e7e3a0b9d8d4fR494

the following error message is produced:
``` bash
Traceback (most recent call last):
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/bytecode_transformation.py", line 339, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/symbolic_convert.py", line 1715, in run
    super().run()
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/symbolic_convert.py", line 363, in wrapper
    self.output.compile_subgraph(self, reason=reason)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/output_graph.py", line 480, in compile_subgraph
    tx.prune_dead_locals()
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/symbolic_convert.py", line 446, in prune_dead_locals
    self.output.side_effects.prune_dead_object_new(self)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/side_effects.py", line 268, in prune_dead_object_new
    VariableTracker.apply(visit, (tx.stack, tx.symbolic_locals))
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 106, in apply
    result = tuple(cls.apply(fn, v, cache, skip_fn) for v in value)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 106, in <genexpr>
    result = tuple(cls.apply(fn, v, cache, skip_fn) for v in value)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 104, in apply
    result = [cls.apply(fn, v, cache, skip_fn) for v in value]
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 104, in <listcomp>
    result = [cls.apply(fn, v, cache, skip_fn) for v in value]
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 96, in apply
    updated_dict[key] = cls.apply(
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 99, in apply
    result = fn(value.clone(**updated_dict))
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 65, in clone
    return self.__class__(**args)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/base.py", line 27, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/misc.py", line 388, in __init__
    super(AutocastModeVariable, self).__init__(
  File "/scratch/drisspg/work/pytorch/torch/_dynamo/variables/misc.py", line 170, in __init__
    super(ContextWrappingVariable, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'mode'
```

### Versions

https://github.com/pytorch/pytorch/pull/92917

This will be merged to master though.

cc @ezyang @gchanan @zou3519 @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment] 2023-02-02 06:53
I can use the following code snippet to reproduce, it seems ```torch.autocast``` context manager doesn't support graph break very well.
```
def fn(x):
    with torch.autocast(device_type="cuda", dtype=torch.bfloat16):
        x = torch.mul(x, 5)
        torch._dynamo.graph_break()
        x = torch.relu(x)
    return x

x = torch.rand([4, 4])
print(fn(x))
opt_fn = torch._dynamo.optimize("inductor")(fn)
print(opt_fn(x))
```

**Comment by jon-chuang** [comment] 2023-02-03 02:31
Hi, could I be assigned this?

**Comment by yanboliang** [comment] 2023-02-03 03:38
@jon-chuang Sure!

**Comment by jon-chuang** [comment] 2023-02-04 05:43
I've fixed for `AutocastModeVariable` with const input params, and fixed old hacky implementation for `set_grad_enabled`, remaining work:
- adding tests (nested contexts, check the behaviour)
- and trying to extend to arbitrary `ContextManager`, and trying to encompass existing cases under a general impl as far as possible
- figure out the story for guards (esp. why `GradModeVariable` requires guards. Future work: var input params with guards.

PR incoming.

**Comment by ngimel** [comment] 2023-02-10 22:05
Marking as high pri, as graph breaks under autocast can be pretty common.

**Comment by jon-chuang** [comment] 2023-02-10 22:42
@ngimel I will get the simpler fix mergeable by the weekend. It will only be able to fix for graph breaks in the top-level straight line function, but not in an inner function call that has graph break; that will be fixed at a later date.

**Comment by yanboliang** [comment] 2023-02-11 05:15
@jon-chuang Let's make autocast support graph break firstly since the solution is clear. For the rest part of #94137, it need further discussion, let's do it in a separate PR.

**Comment by ezyang** [comment] 2023-02-15 01:45
reopening for the more complicated problem

**Comment by williamwen42** [comment] 2023-12-01 19:37
Underlying issue was already fixed and the added test `test_autocast_sdpa` is currently enabled. Closing as fixed.

**Closed by williamwen42** 2023-12-01 19:37 UTC
Labels: triaged, oncall: pt2, module: dynamo
