### ISSUE TITLE
Wrong result for CUDA 9 implementation of (m,).addmv((m, 0), (0,)) for fp16 on some old architecture

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#31006] opened 2019-12-09 22:35 UTC
## 🐛 Bug

See the failures in: https://github.com/pytorch/pytorch/pull/30991

The following test fails on CI which has CUDA 9.0:

```python
@skipCUDAIfRocm
@dtypesIfCUDA(torch.half, torch.float, torch.double)
@dtypes(torch.float, torch.double)
def test_blas_alpha_beta_empty(self, device, dtype):
    # ensure beta is respected
    value = 11
    input = torch.full((2,), value, dtype=dtype, device=device)
    mat = torch.ones((2, 0), dtype=dtype, device=device)
    vec = torch.ones((0,), dtype=dtype, device=device)
    out = torch.empty((2,), dtype=dtype, device=device)
    alpha = 6
    beta = 3
    self.assertEqual(torch.full((2,), beta * value, dtype=dtype, device=device),
                        torch.addmv(input=input, mat=mat, vec=vec, alpha=alpha, beta=beta))
    self.assertEqual(torch.full((2,), beta * value, dtype=dtype, device=device),
                        torch.addmv(input=input, mat=mat, vec=vec, alpha=alpha, beta=beta, out=out))

    # torch.addmm
    input = torch.full((2, 3), value, dtype=dtype, device=device)
    mat2 = torch.ones((0, 3), dtype=dtype, device=device)
    out = torch.empty((2, 3), dtype=dtype, device=device)
    self.assertEqual(torch.full((2, 3), beta * value, dtype=dtype, device=device),
                        torch.addmm(input=input, mat1=mat, mat2=mat2, alpha=alpha, beta=beta))
    self.assertEqual(torch.full((2, 3), beta * value, dtype=dtype, device=device),
                        torch.addmm(input=input, mat1=mat, mat2=mat2, alpha=alpha, beta=beta, out=out))
```

with error

```
Dec 09 22:19:52 ======================================================================
Dec 09 22:19:52 FAIL [0.027s]: test_blas_alpha_beta_empty_cuda_float16 (__main__.TestTorchDeviceTypeCUDA)
Dec 09 22:19:52 ----------------------------------------------------------------------
Dec 09 22:19:52 Traceback (most recent call last):
Dec 09 22:19:52   File "/var/lib/jenkins/workspace/test/common_utils.py", line 631, in wrapper
Dec 09 22:19:52     method(*args, **kwargs)
Dec 09 22:19:52   File "/var/lib/jenkins/workspace/test/common_utils.py", line 631, in wrapper
Dec 09 22:19:52     method(*args, **kwargs)
Dec 09 22:19:52   File "/var/lib/jenkins/workspace/test/common_device_type.py", line 196, in instantiated_test
Dec 09 22:19:52     result = test(self, device_arg, dtype)
Dec 09 22:19:52   File "/var/lib/jenkins/workspace/test/common_device_type.py", line 334, in dep_fn
Dec 09 22:19:52     return fn(slf, device, *args, **kwargs)
Dec 09 22:19:52   File "test_torch.py", line 11800, in test_blas_alpha_beta_empty
Dec 09 22:19:52     torch.addmv(input=input, mat=mat, vec=vec, alpha=alpha, beta=beta))
Dec 09 22:19:52   File "/var/lib/jenkins/workspace/test/common_utils.py", line 808, in assertEqual
Dec 09 22:19:52     assertTensorsEqual(x, y)
Dec 09 22:19:52   File "/var/lib/jenkins/workspace/test/common_utils.py", line 778, in assertTensorsEqual
Dec 09 22:19:52     self.assertLessEqual(max_err, prec, message)
Dec 09 22:19:52 AssertionError: tensor(22., device='cuda:0', dtype=torch.float16) not less than or equal to 1e-05 : 
```

I found this when working on https://github.com/pytorch/pytorch/pull/30898

~~Sorry, I don't have a CUDA 9.0 configuration to reproduce, but the same test succeeds on pip installing the nightly for CUDA 9.2 and CUDA 10.1.~~ Edit: see comment below.

This seems to be a fixed bug of cuBlas

cc: @ngimel @VitalyFedyunin 
cc: @csarofeen @ptrblck 

cc @ngimel

**Comment by zasdfgbnm** [comment] 2019-12-09 22:39
See also https://github.com/pytorch/pytorch/issues/30986

**Comment by zasdfgbnm** [comment] 2019-12-10 18:58
Update:
This seems not specific to 9.0 but 9.2 also has this problem. And this problem does not exist on Volta or CUDA 10 from what I see. Here is a summary:

|            | CUDA 9.0   | CUDA 9.2 | CUDA 10.1 |
|------------|------------|----------|-----------|
| Tesla M40  | Fail       | Fail     | Success   |
| Tesla V100 | Not tested | Success  | Success   |

**Comment by ngimel** [comment] 2019-12-10 21:20
Still not worth fixing. Is it possible to disable test based on cuda version?

**Comment by zasdfgbnm** [comment] 2019-12-10 21:28
> Still not worth fixing. Is it possible to disable test based on cuda version?

Yes, I will do that

**Comment by ngimel** [comment] 2019-12-16 19:06
I'm closing, as the issue is fixed on cuda 10, was not flagged before, is not a regression and affects only operations with empty tensors.

**Closed by ngimel** 2019-12-16 19:06 UTC
Labels: module: cuda, triaged
