### ISSUE TITLE
Numerical issue in torch.gesv(b, A) and torch.inverse()

### ISSUE THREAD

**Issue by gd-zhang** [pytorch/pytorch#3558] opened 2017-11-08 02:12 UTC
I found gesv would get completely wrong results once the dimension of matrix A is large, say 200. (The same problem also occurs in torch.inverse()). But in numpy, linalg.solve works very well in much larger A and b.

```python
A = torch.randn([200, 200])
b = torch.eye(200)
x, _ = torch.gesv(b, A)
rec = A.mm(x)
```

get rec:
   12.5733     0.7703     3.3207  ...    -71.7724   -10.3178    -4.7247
   28.7078     2.0905    17.2917  ...   -184.5936   -28.1566   -21.9251
   55.6995     3.9526    29.5577  ...   -357.7238   -53.0334   -37.8292
              ...                  ⋱                 ...               
  -29.2093    -2.0292   -15.7188  ...    188.9897    27.8947    19.6602
  -57.7021    -3.9133   -21.4146  ...    349.9576    51.1917    30.0501
   -5.3475    -0.3623    -1.7454  ...     31.8616     5.1076     3.6032

**Comment by ozancaglayan** [comment] 2017-11-09 11:08
It depends on the data generated and the precision I think. Wrote a quick snippet below where all results are at least equal with atol `1e-1` but for higher precisions the behaviour is data-dependent.

```python
#!/usr/bin/env python
import torch
import numpy as np

if __name__ == '__main__':
    for seed in (23, 435, 29, 560):
        print('Seed: {}'.format(seed))
        torch.manual_seed(seed)
        for dim in [10,100,200,400,800,1600,2000]:
            A = torch.randn([dim, dim])
            b = torch.eye(dim)
            x, _ = torch.gesv(b, A)

            xn = np.linalg.solve(A.numpy(), b.numpy())
            all_failed = True
            for atol in [1e-1, 1e-2, 1e-3, 1e-4]:
                if not np.allclose(x, xn, atol=atol):
                    print('Failed for dim {} (atol={})'.format(dim, atol))
                else:
                    all_failed = False
            if all_failed:
                print('All failed for dim {}'.format(dim))
```

**Comment by SsnL** [comment] 2017-11-09 17:01
@gd-zhang I can't reproduce this, neither on 0.2 nor on master. As @ozancaglayan mentioned, there are slightly off results sometimes due to precision. But they are always close to `b`. Could you dump an `A` that gave you error results please?

**Comment by gd-zhang** [comment] 2017-11-12 01:55
@SsnL I just updated to 0.2.0_4 and I cannot reproduce the problem. But in 0.2.0_3, my friends told me numerical problem remains.

**Comment by SsnL** [comment] 2017-11-12 01:57
Okay. Glad to now it is fixed now!

**Closed** 2017-11-12 05:41 UTC
Labels: needs-reproduction
