### ISSUE TITLE
CUDA torch.randn silently fails when the output has more than 2^31-1 elements

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#17898] opened 2019-03-11 23:45 UTC
## 🐛 Bug

`torch.randn` silently fails when the output has more than 2^31-1 elements. The output remains uninitialized (often all zeros).

## To Reproduce

Note: you need >8 GB on your GPU to run this example

```python
x = torch.randn(65536, 32768, device='cuda')
print(x)
```

## Environment

PyTorch master 066d1584 (Mar 11, 2019)
CUDA 9.2.88

**Comment by ezyang** [comment] 2019-03-18 17:59
Yeah, this is bad. (Methodological improvement suggestion: we can have a flag for a test suite to run large tests, and run them nightly on master. This is not just randn; there probably are a lot of operators that aren't working here.)

One thought: does the CircleCI machine have 8G of RAM, for this case? None of the g3 AWS machines have enough GPU per memory. So finding GPUs with enough RAM will take a little bit of work; maybe we can run these nightly on our own cluster machines; e.g., reusing the machines that are reserved for ONNX builds.

**Comment by ezyang** [comment] 2019-04-04 16:55
This is embarrassing but there isn't any indication anyone has actually run into this in the real world (Sam ran into it because he was trying to generate a testcase for #17897)

Note that slow tests now exist, but we still don't have any CircleCI machines we could run these tests on.

**Comment by SsnL** [comment] 2019-06-20 21:02
Neither I on master nor @syed-ahmed on #20626 can reproduce this anymore. So I'm closing it. :)

**Closed by SsnL** 2019-06-20 21:02 UTC
Labels: low priority, module: cuda, module: random, topic: 64-bit, triaged
