### ISSUE TITLE
TestONNXRuntime.test_gru_trilayer_forward_with_initial_state_without_sequence_lengths_without_dropout is flaky

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#24268] opened 2019-08-13 20:15 UTC
```
Aug 13 20:07:49 =================================== FAILURES ===================================
Aug 13 20:07:49 _ TestONNXRuntime.test_gru_trilayer_forward_with_initial_state_without_sequence_lengths_without_dropout _
Aug 13 20:07:49 
Aug 13 20:07:49 self = <test_pytorch_onnx_onnxruntime.TestONNXRuntime testMethod=test_gru_trilayer_forward_with_initial_state_without_sequence_lengths_without_dropout>
Aug 13 20:07:49 
Aug 13 20:07:49     def wrapper(self):
Aug 13 20:07:49         if self.opset_version < min_opset_version:
Aug 13 20:07:49             raise unittest.SkipTest("Skip verify test for unsupported opset_version")
Aug 13 20:07:49 >       return func(self)
Aug 13 20:07:49 
Aug 13 20:07:49 test/onnx/test_pytorch_common.py:54: 
Aug 13 20:07:49 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Aug 13 20:07:49 test/onnx/test_pytorch_onnx_onnxruntime.py:893: in f
Aug 13 20:07:49     **extra_kwargs)
Aug 13 20:07:49 test/onnx/test_pytorch_onnx_onnxruntime.py:756: in _dispatch_rnn_test
Aug 13 20:07:49     self._gru_test(*args, **kwargs)
Aug 13 20:07:49 test/onnx/test_pytorch_onnx_onnxruntime.py:870: in _gru_test
Aug 13 20:07:49     self.run_test(model, other_input, batch_size=RNN_BATCH_SIZE + 1)
Aug 13 20:07:49 test/onnx/test_pytorch_onnx_onnxruntime.py:78: in run_test
Aug 13 20:07:49     do_constant_folding=do_constant_folding)
Aug 13 20:07:49 test/onnx/test_pytorch_onnx_onnxruntime.py:67: in run_model_test
Aug 13 20:07:49     [np.testing.assert_allclose(out, ort_out, rtol=rtol, atol=atol) for out, ort_out in zip(outputs, ort_outs)]
Aug 13 20:07:49 _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
Aug 13 20:07:49 
Aug 13 20:07:49 .0 = <zip object at 0x7f1e4f231388>
Aug 13 20:07:49 
Aug 13 20:07:49 >   [np.testing.assert_allclose(out, ort_out, rtol=rtol, atol=atol) for out, ort_out in zip(outputs, ort_outs)]
Aug 13 20:07:49 E   AssertionError: 
Aug 13 20:07:49 E   Not equal to tolerance rtol=0.001, atol=1e-07
Aug 13 20:07:49 E   
Aug 13 20:07:49 E   Mismatch: 0.379%
Aug 13 20:07:49 E   Max absolute difference: 1.4901161e-07
Aug 13 20:07:49 E   Max relative difference: 0.01652892
Aug 13 20:07:49 E    x: array([[[-6.747356e-02, -3.877402e-01, -4.473854e-01],
Aug 13 20:07:49 E           [ 5.361904e-01,  2.344201e-01,  4.945948e-01],
Aug 13 20:07:49 E           [-8.875799e-02,  4.824059e-01, -4.619483e-01],...
Aug 13 20:07:49 E    y: array([[[-6.747360e-02, -3.877402e-01, -4.473855e-01],
Aug 13 20:07:49 E           [ 5.361904e-01,  2.344201e-01,  4.945948e-01],
Aug 13 20:07:49 E           [-8.875804e-02,  4.824059e-01, -4.619483e-01],...
Aug 13 20:07:49 
Aug 13 20:07:49 test/onnx/test_pytorch_onnx_onnxruntime.py:67: AssertionError

```

Example failure https://circleci.com/gh/pytorch/pytorch/2449049?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link/console

cc @neginraoof

**Comment by neginraoof** [comment] 2019-08-14 20:52
I'm unable to reproduce this. Was this a transient issue?

**Comment by ezyang** [comment] 2019-08-16 15:16
It only fails intermittently. On master it doesn't look like it's failed in the last day. Could you please double check the RNG in this test is deterministic?

**Comment by pietern** [comment] 2019-09-02 09:35
Another instance of this same flakiness issue: https://circleci.com/gh/pytorch/pytorch/2651845

**Comment by neginraoof** [comment] 2019-10-25 16:14
@ezyang Can we close this? Issue has been fixed.

**Closed** 2019-10-25 17:18 UTC
Labels: module: onnx, triaged
