### ISSUE TITLE
Cannot build caffe2 by build_anaconda.sh in OSX High Sierra

### ISSUE THREAD

**Issue by Grant-Tao** [pytorch/pytorch#7030] opened 2018-04-27 09:01 UTC
## Issue description
When run build_anaconda.sh (with or without GPU support), an EOFError appeared, this is the output:

++ uname
+ '[' Darwin == Darwin ']'
+ CONDA_BUILD_ARGS=()
+ CAFFE2_CMAKE_ARGS=()
+ CONDA_CHANNEL=()
+ [[ '' == *cuda* ]]
+ [[ '' == *cudnn* ]]
+ [[ '' == *full* ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ 0 -gt 0 ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
+ [[ -n '' ]]
++ date +%Y.%m.%d
+ export PYTORCH_BUILD_VERSION=0.8.dev.2018.04.27
+ PYTORCH_BUILD_VERSION=0.8.dev.2018.04.27
++ uname
+ [[ Darwin != \D\a\r\w\i\n ]]
+ [[ '' == 4* ]]
+ GCC_USE_C11=1
++ python --version
++ grep --only-matching '[0-9]\.[0-9]\.[0-9]*'
+ PYTHON_VERSION=3.6.4
+ [[ 3.6.4 == 3.6* ]]
+ CONDA_BUILD_ARGS+=(" --python 3.6")
+++ dirname ./scripts/build_anaconda.sh
++ cd ./scripts/..
++ pwd -P
+ PYTORCH_ROOT=/Users/grant/pytorch
+ CONDA_BUILD_DIR=/Users/grant/pytorch/conda
+ [[ -n '' ]]
+ [[ -n '' ]]
+ cp -r /Users/grant/pytorch/conda/caffe2/meta.yaml /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ CONDA_BUILD_DIR=/Users/grant/pytorch/conda/caffe2/normal
+ META_YAML=/Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's#path:.*#path: /Users/grant/pytorch#' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's#path:.*#path: /Users/grant/pytorch#' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ BUILD_STRING='py{{py}}'
+ [[ -z '' ]]
+ package_name=caffe2
+ [[ -n '' ]]
+ [[ -n '' ]]
+ BUILD_STRING='py{{py}}_cpu'
++ uname
+ [[ Darwin != \D\a\r\w\i\n ]]
+ [[ -n '' ]]
+ portable_sed 's/name: caffe2.*$/name: caffe2/' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's/name: caffe2.*$/name: caffe2/' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's/string:.*$/string: py{{py}}_cpu/' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's/string:.*$/string: py{{py}}_cpu/' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ [[ -n '' ]]
+ [[ -n '' ]]
+ add_package glog
+ append_to_section build '- glog '
+ add_before '# build section here' '- glog ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# build section here@\1- glog \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# build section here@\1- glog \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ append_to_section run '- glog '
+ add_before '# run section here' '- glog ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# run section here@\1- glog \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# run section here@\1- glog \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ add_package gflags
+ append_to_section build '- gflags '
+ add_before '# build section here' '- gflags ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# build section here@\1- gflags \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# build section here@\1- gflags \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ append_to_section run '- gflags '
+ add_before '# run section here' '- gflags ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# run section here@\1- gflags \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# run section here@\1- gflags \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ add_package opencv
+ append_to_section build '- opencv '
+ add_before '# build section here' '- opencv ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# build section here@\1- opencv \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# build section here@\1- opencv \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ append_to_section run '- opencv '
+ add_before '# run section here' '- opencv ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# run section here@\1- opencv \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# run section here@\1- opencv \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ [[ -n '' ]]
+ add_package leveldb
+ append_to_section build '- leveldb '
+ add_before '# build section here' '- leveldb ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# build section here@\1- leveldb \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# build section here@\1- leveldb \
\1# build section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ append_to_section run '- leveldb '
+ add_before '# run section here' '- leveldb ' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ portable_sed 's@( *)# run section here@\1- leveldb \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ sed -E -i '' 's@( *)# run section here@\1- leveldb \
\1# run section here@' /Users/grant/pytorch/conda/caffe2/normal/meta.yaml
+ [[ -n '' ]]
+ CAFFE2_CMAKE_ARGS+=("-DUSE_CUDA=OFF")
+ CAFFE2_CMAKE_ARGS+=("-DUSE_NCCL=OFF")
++ uname
+ [[ Darwin != \D\a\r\w\i\n ]]
+ [[ -n '' ]]
+ echo 'Finalized meta.yaml is'
Finalized meta.yaml is
+ cat /Users/grant/pytorch/conda/caffe2/normal/meta.yaml

package:
  name: caffe2
  version: {{ environ.get('PYTORCH_BUILD_VERSION') }}

source:
  path: /Users/grant/pytorch

build:
  number: 0
  string: py{{py}}_cpu
  skip: True  # [win]
  script_env:
    - CONDA_CAFFE2_CMAKE_ARGS
    - PACKAGE_CUDA_LIBS
    - BUILD_WITH_CUDA
  # features section here

requirements:
  build:
    - cmake
    - future
    - numpy
    - python
    - six
    - glog 
    - gflags 
    - opencv 
    - leveldb 
    # build section here
  run:
    - future
    - numpy
    - protobuf
    - python
    - six
    - glog 
    - gflags 
    - opencv 
    - leveldb 
    # run section here

test:
  # test section here
  imports:
    - caffe2.python.core

about:
  home: https://caffe2.ai/
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Caffe2 is a lightweight, modular, and scalable deep learning framework.

extra:
  recipe-maintainers:
    - pjh5
+ CONDA_CAFFE2_CMAKE_ARGS='-DUSE_CUDA=OFF -DUSE_NCCL=OFF'
+ conda build /Users/grant/pytorch/conda/caffe2/normal --python 3.6
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Adding in variants from config.variant
INFO:conda_build.variants:Adding in variants from config.variant
/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/environ.py:377: UserWarning: The environment variable 'CONDA_CAFFE2_CMAKE_ARGS' is being passed through with value -DUSE_CUDA=OFF -DUSE_NCCL=OFF.  If you are splitting build and test phases with --no-test, please ensure that this value is also set similarly at test time.
  UserWarning
/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/environ.py:369: UserWarning: The environment variable 'PACKAGE_CUDA_LIBS' is undefined.
  UserWarning
/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/environ.py:369: UserWarning: The environment variable 'BUILD_WITH_CUDA' is undefined.
  UserWarning
Attempting to finalize metadata for caffe2
INFO:conda_build.metadata:Attempting to finalize metadata for caffe2
Solving environment: ...working... done
Traceback (most recent call last):
  File "/Users/grant/anaconda3/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/api.py", line 193, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1944, in build_tree
    notest=notest,
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/build.py", line 1032, in build
    output_metas = expand_outputs([(m, need_source_download, need_reparse_in_env)])
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/render.py", line 582, in expand_outputs
    for (output_dict, m) in _m.get_output_metadata_set(permit_unsatisfiable_variants=False):
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 1845, in get_output_metadata_set
    permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/metadata.py", line 670, in finalize_outputs_pass
    fm = finalize_metadata(om, permit_unsatisfiable_variants=permit_unsatisfiable_variants)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/render.py", line 379, in finalize_metadata
    exclude_pattern)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/render.py", line 293, in add_upstream_pins
    permit_unsatisfiable_variants, exclude_pattern)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/render.py", line 284, in _read_upstream_pin_files
    extra_run_specs = get_upstream_pins(m, actions, env)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/render.py", line 271, in get_upstream_pins
    specs = _read_specs_from_package(pkg_loc, pkg_dist)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda/exports.py", line 178, in __call__
    value = self.func(*args, **kw)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/render.py", line 204, in _read_specs_from_package
    specs_yaml = utils.package_has_file(pkg_loc, 'info/run_exports.yaml')
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda/exports.py", line 178, in __call__
    value = self.func(*args, **kw)
  File "/Users/grant/anaconda3/lib/python3.6/site-packages/conda_build/utils.py", line 724, in package_has_file
    text = t.extractfile(file_path).read()
  File "/Users/grant/anaconda3/lib/python3.6/tarfile.py", line 2073, in extractfile
    tarinfo = self.getmember(member)
  File "/Users/grant/anaconda3/lib/python3.6/tarfile.py", line 1747, in getmember
    tarinfo = self._getmember(name)
  File "/Users/grant/anaconda3/lib/python3.6/tarfile.py", line 2332, in _getmember
    members = self.getmembers()
  File "/Users/grant/anaconda3/lib/python3.6/tarfile.py", line 1758, in getmembers
    self._load()        # all members, we first have to
  File "/Users/grant/anaconda3/lib/python3.6/tarfile.py", line 2355, in _load
    tarinfo = self.next()
  File "/Users/grant/anaconda3/lib/python3.6/tarfile.py", line 2286, in next
    self.fileobj.seek(self.offset - 1)
  File "/Users/grant/anaconda3/lib/python3.6/bz2.py", line 278, in seek
    return self._buffer.seek(offset, whence)
  File "/Users/grant/anaconda3/lib/python3.6/_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "/Users/grant/anaconda3/lib/python3.6/_compression.py", line 99, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

## Command issued:
CONDA_INSTALL_LOCALLY=1 BUILD_ENVIRONMENT=conda-cuda-macos  ./scripts/build_anaconda.sh

## System Info
** conda list output:

 # packages in environment at /Users/grant/anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36h2fc01ae_0  
alabaster                 0.7.10           py36h174008c_0  
anaconda                  custom           py36ha4fed55_0  
anaconda-client           1.6.9                    py36_0  
anaconda-navigator        1.7.0                    py36_0  
anaconda-project          0.8.2            py36h9ee5d53_0  
appnope                   0.1.0            py36hf537a9a_0  
appscript                 1.0.1            py36h9e71e49_1  
asn1crypto                0.24.0                   py36_0  
astroid                   1.6.1                    py36_0  
astropy                   2.0.3            py36h1de35cc_0  
attrs                     17.4.0                   py36_0  
babel                     2.5.3                    py36_0  
backports                 1.0              py36ha3c1827_1  
backports.shutil_get_terminal_size 1.0.0            py36hd7a2ee4_2  
beautifulsoup4            4.6.0            py36h72d3c9f_1  
bitarray                  0.8.1            py36h1de35cc_1  
bkcharts                  0.2              py36h073222e_0  
blaze                     0.11.3           py36h02e7a37_0  
bleach                    2.1.2                    py36_0  
bokeh                     0.12.13          py36h2f9c1c0_0  
boto                      2.48.0           py36hdbc59ac_1  
bottleneck                1.2.1            py36hbd380ad_0  
bzip2                     1.0.6                hd86a083_4  
ca-certificates           2018.03.07                    0  
certifi                   2018.4.16                py36_0  
cffi                      1.11.4           py36h342bebf_0  
chardet                   3.0.4            py36h96c241c_1  
click                     6.7              py36hec950be_0  
cloudpickle               0.5.2                    py36_1  
clyent                    1.2.2            py36hae3ad88_0  
colorama                  0.3.9            py36hd29a30c_0  
conda                     4.5.1                    py36_0  
conda-build               3.4.1                    py36_0  
conda-env                 2.6.0                h36134e3_0  
conda-verify              2.0.0            py36he837df3_0  
contextlib2               0.5.5            py36hd66e5e7_0  
cryptography              2.1.4            py36h842514c_0  
curl                      7.58.0               ha441bb4_0  
cycler                    0.10.0           py36hfc81398_0  
cython                    0.27.3           py36h6ecb376_0  
cytoolz                   0.9.0            py36h1de35cc_0  
dask                      0.16.1                   py36_0  
dask-core                 0.16.1                   py36_0  
datashape                 0.5.4            py36hfb22df8_0  
dbus                      1.12.2               h5243cc1_1  
decorator                 4.2.1                    py36_0  
distributed               1.20.2                   py36_0  
docutils                  0.14             py36hbfde631_0  
entrypoints               0.2.3            py36hd81d71f_2  
et_xmlfile                1.0.1            py36h1315bdc_0  
expat                     2.2.5                hb8e80ba_0  
fastcache                 1.0.2            py36h1de35cc_2  
filelock                  2.0.13           py36hf9de95b_0  
flask                     0.12.2           py36h5658096_0  
flask-cors                3.0.3            py36h7387b97_0  
freetype                  2.8                  h12048fb_1  
get_terminal_size         1.0.0                h7520d66_0  
gettext                   0.19.8.1             h15daf44_3  
gevent                    1.2.2            py36ha70b9d6_0  
glib                      2.53.6               h33f6a65_2  
glob2                     0.6              py36h94c9186_0  
gmp                       6.1.2                hb37e062_1  
gmpy2                     2.0.8            py36hf9c35bd_2  
greenlet                  0.4.12           py36hf09ba7b_0  
h5py                      2.7.1            py36h39cdac5_0  
hdf5                      1.10.1               ha036c08_1  
heapdict                  1.0.0                    py36_2  
html5lib                  1.0.1            py36h2f9c1c0_0  
icu                       58.2                 h4b95b61_1  
idna                      2.6              py36h8628d0a_1  
imageio                   2.2.0            py36h5e01289_0  
imagesize                 0.7.1            py36h3495948_0  
intel-openmp              2018.0.0             h8158457_8  
ipykernel                 4.8.0                    py36_0  
ipython                   6.2.1            py36h3dda519_1  
ipython_genutils          0.2.0            py36h241746c_0  
ipywidgets                7.1.1                    py36_0  
isort                     4.2.15           py36hceb2a01_0  
itsdangerous              0.24             py36h49fbb8d_1  
jbig                      2.1                  h4d881f8_0  
jdcal                     1.3              py36h1986823_0  
jedi                      0.11.1                   py36_0  
jinja2                    2.10             py36hd36f9c5_0  
jpeg                      9b                   he5867d9_2  
jsonschema                2.6.0            py36hb385e00_0  
jupyter                   1.0.0                    py36_4  
jupyter_client            5.2.2                    py36_0  
jupyter_console           5.2.0            py36hccf5b1c_1  
jupyter_core              4.4.0            py36h79cf704_0  
jupyterlab                0.31.5                   py36_0  
jupyterlab_launcher       0.10.2                   py36_0  
lazy-object-proxy         1.3.1            py36h2fbbe47_0  
libcurl                   7.58.0               hf30b1f0_0  
libcxx                    4.0.1                h579ed51_0  
libcxxabi                 4.0.1                hebd6815_0  
libedit                   3.1                  hb4e282d_0  
libffi                    3.2.1                h475c297_4  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 hdd342a3_7  
libpng                    1.6.34               he12f830_0  
libsodium                 1.0.15               hd9e47c5_0  
libssh2                   1.8.0                h322a93b_4  
libtiff                   4.0.9                h0dac147_0  
libxml2                   2.9.7                hab757c2_0  
libxslt                   1.1.32               hb819dd2_0  
llvmlite                  0.21.0           py36hff739e7_0  
locket                    0.2.0            py36hca03003_1  
lxml                      4.1.1            py36hef8c89e_1  
lzo                       2.10                 h362108e_2  
markupsafe                1.0              py36h3a1e703_1  
matplotlib                2.1.2            py36h6d6146d_0  
mccabe                    0.6.1            py36hdaeb55d_0  
mistune                   0.8.3                    py36_0  
mkl                       2018.0.1             hfbd8650_4  
mkl-service               1.1.2            py36h7ea6df4_4  
mpc                       1.0.3                h7a72875_5  
mpfr                      3.1.5                h711e7fd_2  
mpmath                    1.0.0            py36hf1b8295_2  
msgpack-python            0.5.1            py36h04f5b5a_0  
multipledispatch          0.4.9            py36hc5f92b5_0  
navigator-updater         0.1.0            py36h7aee5fb_0  
nbconvert                 5.3.1            py36h810822e_0  
nbformat                  4.4.0            py36h827af21_0  
ncurses                   6.0                  hd04f020_2  
networkx                  2.1                      py36_0  
nltk                      3.2.5            py36h1190bce_0  
nose                      1.3.7            py36h73fae2b_2  
notebook                  5.4.0                    py36_0  
numba                     0.36.2          np114py36hc2f221f_0  
numexpr                   2.6.4            py36habcfcfe_0  
numpy                     1.14.0           py36h8a80b8c_1  
numpydoc                  0.7.0            py36he54d08e_0  
odo                       0.5.1            py36hc1af34a_0  
olefile                   0.45.1                   py36_0  
openpyxl                  2.4.10                   py36_0  
openssl                   1.0.2o               h26aff7b_0  
packaging                 16.8             py36he5e8135_0  
pandas                    0.22.0           py36h0a44026_0  
pandoc                    1.19.2.1             ha5e8f32_1  
pandocfilters             1.4.2            py36h3b0b094_1  
parso                     0.1.1            py36hc90e01c_0  
partd                     0.3.8            py36hf5c4cb8_0  
path.py                   10.5             py36h7bcb313_0  
pathlib2                  2.3.0            py36h877a6d8_0  
patsy                     0.5.0                    py36_0  
pcre                      8.41                 hfb6ab37_1  
pep8                      1.7.1                    py36_0  
pexpect                   4.3.1                    py36_0  
pickleshare               0.7.4            py36hf512f8e_0  
pillow                    5.0.0            py36hfcce615_0  
pip                       9.0.1            py36h1555ced_4  
pkginfo                   1.4.1            py36h25bf955_0  
pluggy                    0.6.0            py36hb1d0581_0  
ply                       3.10             py36h10e714e_0  
prompt_toolkit            1.0.15           py36haeda067_0  
psutil                    5.4.3            py36h1de35cc_0  
ptyprocess                0.5.2            py36he6521c3_0  
py                        1.5.2            py36ha69170d_0  
pycodestyle               2.3.1            py36h83e8646_0  
pycosat                   0.6.3            py36hee92d8f_0  
pycparser                 2.18             py36h724b2fc_1  
pycrypto                  2.6.1            py36h1de35cc_7  
pycurl                    7.43.0.1         py36hdbc3d79_0  
pyflakes                  1.6.0            py36hea45e83_0  
pygments                  2.2.0            py36h240cd3f_0  
pylint                    1.8.2                    py36_0  
pyodbc                    4.0.22           py36h0a44026_0  
pyopenssl                 17.5.0           py36h51e4350_0  
pyparsing                 2.2.0            py36hb281f35_0  
pyqt                      5.6.0            py36he5c6137_6  
pysocks                   1.6.7            py36hfa33cec_1  
pytables                  3.4.2            py36hfbd7ab0_2  
pytest                    3.3.2                    py36_0  
python                    3.6.4                hc167b69_1  
python-dateutil           2.6.1            py36h86d2abb_1  
python.app                2                py36h54569d5_7  
pytz                      2017.3           py36hf0bf824_0  
pywavelets                0.5.2            py36h2710a04_0  
pyyaml                    3.12             py36h2ba1e63_1  
pyzmq                     16.0.3           py36he48b5ad_0  
qt                        5.6.2               h9975529_14  
qtawesome                 0.4.4            py36h468c6fb_0  
qtconsole                 4.3.1            py36hd96c0ff_0  
qtpy                      1.3.1            py36h16bb863_0  
readline                  7.0                  hc1231fa_4  
requests                  2.18.4           py36h4516966_1  
rope                      0.10.7           py36h68959ac_0  
ruamel_yaml               0.15.35          py36h1de35cc_1  
scikit-image              0.13.1           py36h1de35cc_1  
scikit-learn              0.19.1           py36hffbff8c_0  
scipy                     1.0.0            py36h1de22e9_0  
seaborn                   0.8.1            py36h595ecd9_0  
send2trash                1.4.2                    py36_0  
setuptools                38.4.0                   py36_0  
simplegeneric             0.8.1                    py36_2  
singledispatch            3.4.0.3          py36hf20db9d_0  
sip                       4.18.1           py36h2824476_2  
six                       1.11.0           py36h0e22d5e_1  
snowballstemmer           1.2.1            py36h6c7b616_0  
sortedcollections         0.5.3            py36he9c3ed6_0  
sortedcontainers          1.5.9                    py36_0  
sphinx                    1.6.6                    py36_0  
sphinxcontrib             1.0              py36h9364dc8_1  
sphinxcontrib-websupport  1.0.1            py36h92f4a7a_1  
spyder                    3.2.6                    py36_0  
sqlalchemy                1.2.1            py36h1de35cc_0  
sqlite                    3.22.0               h3efe00b_0  
statsmodels               0.8.0            py36h9c68fc9_0  
sympy                     1.1.1            py36h7f3cf04_0  
tblib                     1.3.2            py36hda67792_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1            py36h625a49b_0  
tk                        8.6.7                h35a86e2_3  
toolz                     0.9.0                    py36_0  
tornado                   4.5.3                    py36_0  
traitlets                 4.3.2            py36h65bd3ce_0  
typing                    3.6.2            py36haa2d9ef_0  
unicodecsv                0.14.1           py36he531d66_0  
unixodbc                  2.3.4                h4cb4dde_1  
urllib3                   1.22             py36h68b9469_0  
wcwidth                   0.1.7            py36h8c6ec74_0  
webencodings              0.5.1            py36h3b9701d_1  
werkzeug                  0.14.1                   py36_0  
wget                      1.19.4               h073198b_0  
wheel                     0.30.0           py36h5eb2c71_1  
widgetsnbextension        3.1.0                    py36_0  
wrapt                     1.10.11          py36hc29e774_0  
xlrd                      1.1.0            py36h336f4a2_1  
xlsxwriter                1.0.2            py36h3736301_0  
xlwings                   0.11.5                   py36_0  
xlwt                      1.2.0            py36h5ad1178_0  
xz                        5.2.3                h0278029_2  
yaml                      0.1.7                hc338f04_2  
zeromq                    4.2.2                ha360ad0_2  
zict                      0.1.3            py36h71da714_0  
zlib                      1.2.11               hf3cbc9b_2  

**deviceQuery output:
 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "GeForce GTX 1070"
  CUDA Driver Version / Runtime Version          9.1 / 9.1
  CUDA Capability Major/Minor version number:    6.1
  Total amount of global memory:                 8192 MBytes (8589737984 bytes)
  (15) Multiprocessors, (128) CUDA Cores/MP:     1920 CUDA Cores
  GPU Max Clock rate:                            1759 MHz (1.76 GHz)
  Memory Clock rate:                             4004 Mhz
  Memory Bus Width:                              256-bit
  L2 Cache Size:                                 2097152 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 65536
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 2 copy engine(s)
  Run time limit on kernels:                     Yes
  Integrated GPU sharing Host Memory:            No
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Supports Cooperative Kernel Launch:            Yes
  Supports MultiDevice Co-op Kernel Launch:      No
  Device PCI Domain ID / Bus ID / location ID:   0 / 1 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 9.1, CUDA Runtime Version = 9.1, NumDevs = 1
Result = PASS

##########

Any one can help?

thanks a lot

**Comment by JerryLauzzz** [comment] 2018-06-16 11:32
I think this is an issue caused by incomplete download. 
When I run 
```bash
./scripts/build_anaconda.sh --install-locally --cuda 9.0 --cudnn 7
```
When downloading some necessary packages, I enter 'ctrl+c'.
However, when I run the above command again, I met the same problem. 
I try to reboot to flash my cache, but I met the same problem.

**Comment by JerryLauzzz** [comment] 2018-07-24 03:39
You can try 
```bash
conda clean --all
```
This command will clean all the conda cache.

**Comment by mruberry** [comment] 2021-01-10 08:49
Closing this issue due to age and because PyTorch is now preferred to Caffe2. If this issue is still relevant then please open a new issue.

**Closed by mruberry** 2021-01-10 08:49 UTC
Labels: caffe2
