### ISSUE TITLE
custom collect_fn return None but collate_fn does not accept None 

### ISSUE THREAD

**Issue by ddshan** [pytorch/pytorch#57429] opened 2021-05-02 04:23 UTC
## 🐛 Bug

I wrote a custom collect_fn to filter out bad samples. But in some batches, all samples are being removed so it returns an empty list. But in the default_collate(batch) fn, it assumes the batch is not None since it immediately read batch[0]. This may cause some issues. It would be better to make the default_collate more flexible (can accept None and ignore it).

```ruby
def collate_fn(batch):
    batch = list(filter(lambda x: x is not None, batch))
    return torch.utils.data.dataloader.default_collate(batch)
```

```ruby
def default_collate(batch):
    """Puts each data field into a tensor with outer dimension batch size"""

    elem = batch[0]
    elem_type = type(elem)
    if isinstance(elem, torch.Tensor):
        out = None
        if torch.utils.data.get_worker_info() is not None:
            # If we're in a background process, concatenate directly into a
            # shared memory tensor to avoid an extra copy
            numel = sum([x.numel() for x in batch])
            storage = elem.storage()._new_shared(numel)
            out = elem.new(storage)
        return torch.stack(batch, 0, out=out)
    elif elem_type.__module__ == 'numpy' and elem_type.__name__ != 'str_' \
            and elem_type.__name__ != 'string_':
        if elem_type.__name__ == 'ndarray' or elem_type.__name__ == 'memmap':
            # array of string classes and object
            if np_str_obj_array_pattern.search(elem.dtype.str) is not None:
                raise TypeError(default_collate_err_msg_format.format(elem.dtype))

            return default_collate([torch.as_tensor(b) for b in batch])
        elif elem.shape == ():  # scalars
            return torch.as_tensor(batch)
    elif isinstance(elem, float):
        return torch.tensor(batch, dtype=torch.float64)
    elif isinstance(elem, int):
        return torch.tensor(batch)
    elif isinstance(elem, string_classes):
        return batch
    elif isinstance(elem, collections.abc.Mapping):
        return {key: default_collate([d[key] for d in batch]) for key in elem}
    elif isinstance(elem, tuple) and hasattr(elem, '_fields'):  # namedtuple
        return elem_type(*(default_collate(samples) for samples in zip(*batch)))
    elif isinstance(elem, collections.abc.Sequence):
        # check to make sure that the elements in batch have consistent size
        it = iter(batch)
        elem_size = len(next(it))
        if not all(len(elem) == elem_size for elem in it):
            raise RuntimeError('each element in list of batch should be of equal size')
        transposed = zip(*batch)
        return [default_collate(samples) for samples in transposed]

    raise TypeError(default_collate_err_msg_format.format(elem_type))
```

cc @SsnL @VitalyFedyunin @ejguan @ezyang

**Comment by SsnL** [comment] 2021-05-02 06:30
Without elements it would be impossible to infer the correct shape. I don't think the default collate should set an arbitrary one.

**Comment by ejguan** [comment] 2021-05-03 16:39
Except the problem of impossible inference, the size of each batch varies, which may not the expected behavior. Besides, for `default_collate `, we can't ignore `None` since we need to return something for DataLoader logic. But, if we return `None` from DataLoader, we are pushing data loading logic out of DataLoader.
But, we are designing and working on the new DataLoader which will be really flexible for this use case. Please checkout the RFC #49440 and we really appreciate your feedback.
In order to solve your problem, I recommend you to push the filtering logic into a custom DataSet to only yield (__iter__) or return (__getitem__). It can also provide better data loading performance.

**Comment by ddshan** [comment] 2021-05-05 14:25
Thanks for your response and the link. I am using filtering in my Dataset to solve the problem now. Really looking forward to seeing and using the new Dataloader!

**Comment by ejguan** [comment] 2021-05-10 15:32
Closing this issue. Feel free to re-open it if you have further question.

**Closed by ejguan** 2021-05-10 15:32 UTC
Labels: enhancement, module: dataloader, shadow review, triaged

**Comment by linminhtoo** [comment] 2022-05-31 06:28
> Thanks for your response and the link. I am using filtering in my Dataset to solve the problem now. Really looking forward to seeing and using the new Dataloader!

could you elaborate what you mean by `filtering in my Dataset` ?
