### ISSUE TITLE
how to install torch by python3.8? 

### ISSUE THREAD

**Issue by Fenghuixueha** [pytorch/pytorch#31543] opened 2019-12-21 03:15 UTC
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

**Comment by peterjc123** [comment] 2019-12-21 05:43
Closed by duplicate of #29090

**Closed by peterjc123** 2019-12-21 05:43 UTC
