### ISSUE TITLE
[JIT] b->inputs().size() == b->outputs().size() ASSERT FAILED

### ISSUE THREAD

**Issue by marcocannici** [pytorch/pytorch#18143] opened 2019-03-18 21:58 UTC
## 🐛 Bug

Cycling through a ModuleList in a nested loop of a ScriptModule generates an assertion error.
E.g.:
```
@jit.script_method
def forward(self, input):
    # type: (Tensor) -> Tensor
    for _ in range(2):
        for module in self.module_list:
            input = module(input)
    return input
```

```
Traceback (most recent call last):
  File "modulelist_error.py", line 31, in <module>
    module = TestModule(2)
  File "/tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py", line 952, in init_then_register
    _create_methods_from_stubs(self, methods)
  File "/tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/jit/__init__.py", line 913, in _create_methods_from_stubs
    self._create_methods(defs, rcbs, defaults)
RuntimeError: b->inputs().size() == b->outputs().size() ASSERT FAILED at /opt/conda/conda-bld/pytorch_1549628766161/work/torch/csrc/jit/script/compiler.cpp:370, please report a bug to PyTorch. (deleteExtraInputs at /opt/conda/conda-bld/pytorch_1549628766161/work/torch/csrc/jit/script/compiler.cpp:370)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x45 (0x7efe36631cf5 in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x737c3c (0x7efe161adc3c in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #2: <unknown function> + 0x74ddbb (0x7efe161c3dbb in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #3: <unknown function> + 0x74e707 (0x7efe161c4707 in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #4: <unknown function> + 0x74f138 (0x7efe161c5138 in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #5: <unknown function> + 0x74cd14 (0x7efe161c2d14 in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #6: <unknown function> + 0x7526bc (0x7efe161c86bc in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #7: <unknown function> + 0x72c96b (0x7efe161a296b in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #8: torch::jit::script::Method::ensure_defined() + 0xdb (0x7efe2d947e4b in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #9: torch::jit::script::defineMethodsInModule(std::shared_ptr<torch::jit::script::Module>, std::vector<torch::jit::script::Def, std::allocator<torch::jit::script::Def> > const&, std::vector<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::string const&, torch::jit::script::Method&, torch::jit::SourceRange const&)>, std::allocator<std::function<std::shared_ptr<torch::jit::script::SugaredValue> (std::string const&, torch::jit::script::Method&, torch::jit::SourceRange const&)> > > const&, std::shared_ptr<torch::jit::script::SugaredValue>) + 0x708 (0x7efe1619e018 in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch.so.1)
frame #10: <unknown function> + 0x3abedf (0x7efe2d91fedf in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #11: <unknown function> + 0x111826 (0x7efe2d685826 in /tmp/miniconda3/envs/py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #35: __libc_start_main + 0xf0 (0x7efe3cf20830 in /lib/x86_64-linux-gnu/libc.so.6)
```

## To Reproduce

A minimal script that reproduces the error:

```
import torch
import torch.nn as nn
import torch.jit as jit
from torch.jit import Tensor

class TestModule(jit.ScriptModule):
    __constants__ = ['module_list']

    def __init__(self, n):
        super().__init__()
        self.module_list = nn.ModuleList([DummyModule() for _ in range(n)])

    @jit.script_method
    def forward(self, input):
        # type: (Tensor) -> Tensor
        for _ in range(2):
            for module in self.module_list:
                input = module(input)
        return input

class DummyModule(jit.ScriptModule):
    @jit.script_method
    def forward(self, input):
        return input

if __name__ == "__main__":
    tensor = torch.tensor(1)
    module = TestModule(2)
    print(module(tensor))
```

## Environment

Output of collect_env.py:
```
Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: TITAN Xp
GPU 5: TITAN X (Pascal)

Nvidia driver version: 410.78
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.1

Versions of relevant libraries:
[pip3] numpy==1.15.4
[pip3] torchfile==0.1.0
[conda] mkl                       2019.1                      144
[conda] mkl_fft                   1.0.10                   py36_0    conda-forge
[conda] mkl_random                1.0.2                    py36_0    conda-forge
[conda] pytorch                   1.0.1           py3.6_cuda9.0.176_cudnn7.4.2_2    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
```

**Comment by suo** [comment] 2019-03-19 19:01
Thanks for the report! Definitely a bug on our side. @eellison can you take a look?

**Comment by eellison** [comment] 2019-03-27 20:55
I still need to do a complete fix for this but a workaround is to put module_list in nn.Sequential instead of iterating in a for loop.

```
def __init__(self, mod_list):
    super(M, self).__init__(False)
    self.mods = nn.Sequential(mod_list, mod_list)

@torch.jit.script_method
def forward(self, v):
    for m in self.mods:
        v = m(v)
    return v
```

**Comment by geoffsmith** [comment] 2019-06-20 09:49
That workaround didn't work for me because the modules I'm using in the ModuleList take multiple parameters in the forward method. Another workaround that worked for me is to factor the inner loop out to a new function.

**Comment by suo** [comment] 2019-10-03 18:21
Closing as this has been fixed (the repro in the initial post now works as intended)

**Closed by suo** 2019-10-03 18:21 UTC
Labels: jit
