### ISSUE TITLE
[pt2] `torch.compile` produces wrong results for `masked_fill`

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#93823] opened 2023-02-01 06:13 UTC
### 🐛 Describe the bug

```python
import torch

def fn(x, y):
    o = x.masked_fill(y, 0) # torch.Tensor.masked_fill-1 # v4: (4, 1040, 12)
    return o

x = torch.rand(2, 4, 8)
y = torch.ones(2, 4, 1).bool()

"""Other shapes may eliminate the error
x = torch.rand(2, 4, 6)
y = torch.ones(2, 4, 1).bool()
"""

eager = fn(x, y)
compiled = torch.compile(fn)
comp = compiled(x, y)

assert torch.allclose(
    eager, comp,
), '\n'.join([
    '',
    f'>>> eager',
    str(eager),
    f'>>> comp',
    str(comp),
])
print(f'==== finished! ====')
```

### Error logs

```python
Traceback (most recent call last):
  File "/home/colin/code/path/bug.py", line 19, in <module>
    assert torch.allclose(
AssertionError: 
>>> eager
tensor([[[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0., 0., 0., 0.]]])
>>> comp
tensor([[[0.2872, 0.6392, 0.9319, 0.1317, 0.4369, 0.1854, 0.3762, 0.6749],
         [0.2742, 0.7328, 0.8678, 0.8610, 0.6482, 0.3999, 0.2422, 0.5373],
         [0.9709, 0.2897, 0.3877, 0.1228, 0.8505, 0.0393, 0.3404, 0.1397],
         [0.1840, 0.1566, 0.1393, 0.5745, 0.0122, 0.1554, 0.6762, 0.0073]],

        [[0.8470, 0.9235, 0.8760, 0.2368, 0.9499, 0.7036, 0.7472, 0.0482],
         [0.6972, 0.6094, 0.1375, 0.7126, 0.6172, 0.0568, 0.4729, 0.1351],
         [0.7203, 0.2941, 0.4052, 0.0503, 0.7970, 0.7026, 0.1992, 0.9565],
         [0.6881, 0.2052, 0.8904, 0.0038, 0.5407, 0.7821, 0.0324, 0.8199]]])
```

### Versions

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230131+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230131+cu117
[pip3] torchaudio==2.0.0.dev20230131+cu117
[pip3] torchvision==0.15.0.dev20230131+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230131+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230131+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230131+cu117          pypi_0    pypi
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by Valentine233** [comment] 2023-02-03 02:32
I could not reproduce the error. Could you pls ensure to use the latest PyTorch and provide more examples?

**Comment by Co1lin** [comment] 2023-02-03 18:09
@Valentine233 Hi! I double-checked it, and I confirm that I can reproduce the error above with the version given above.
I can also reproduce it (the inconsistency error) using the latest version:

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230203+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230203+cu117
[pip3] torchaudio==2.0.0.dev20230203+cu117
[pip3] torchvision==0.15.0.dev20230203+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230203+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230203+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230203+cu117          pypi_0    pypi
```

Thank you!

**Comment by Valentine233** [comment] 2023-02-07 05:57
Fixed in https://github.com/pytorch/pytorch/pull/93922.

**Closed** 2023-02-08 00:53 UTC
Labels: triaged, oncall: pt2, module: inductor, module: cpu inductor
