### ISSUE TITLE
Failed to import transformer.

### ISSUE THREAD

**Issue by phantatbach** [pytorch/pytorch#111365] opened 2023-10-16 10:59 UTC
### 🐛 Describe the bug

!pip install datasets evaluate transformers[sentencepiece]

```python
from transformers import Trainer

trainer = Trainer(
    model,
    training_args,
    train_dataset=tokenized_datasets["train"],
    eval_dataset=tokenized_datasets["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer,
)
```

I am doing the NLP course by Hugging Face. On week 3, I cant seem the import anything from transformers.

```
{
	"name": "RuntimeError",
	"message": "Failed to import transformers.training_args because of the following error (look up to see its traceback):
[WinError 182] The operating system cannot run %1. Error loading \"d:\\Programmes\\anaconda3\\envs\\NLP310\\lib\\site-packages\\torch\\lib\\fbgemm.dll\" or one of its dependencies.",
	"stack": "---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
File ~\\AppData\\Roaming\\Python\\Python310\\site-packages\\transformers\\utils\\import_utils.py:1282, in _LazyModule._get_module(self, module_name)
   1281 try:
-> 1282     return importlib.import_module(\".\" + module_name, self.__name__)
   1283 except Exception as e:

File d:\\Programmes\\anaconda3\\envs\\NLP310\\lib\\importlib\\__init__.py:126, in import_module(name, package)
    125         level += 1
--> 126 return _bootstrap._gcd_import(name[level:], package, level)

File <frozen importlib._bootstrap>:1050, in _gcd_import(name, package, level)

File <frozen importlib._bootstrap>:1027, in _find_and_load(name, import_)

File <frozen importlib._bootstrap>:1006, in _find_and_load_unlocked(name, import_)

File <frozen importlib._bootstrap>:688, in _load_unlocked(spec)

File <frozen importlib._bootstrap_external>:883, in exec_module(self, module)

File <frozen importlib._bootstrap>:241, in _call_with_frames_removed(f, *args, **kwds)

File ~\\AppData\\Roaming\\Python\\Python310\\site-packages\\transformers\\training_args.py:30
     28 from packaging import version
---> 30 from .debug_utils import DebugOption
     31 from .trainer_utils import (
     32     EvaluationStrategy,
     33     FSDPOption,
   (...)
     37     ShardedDDPOption,
     38 )

File ~\\AppData\\Roaming\\Python\\Python310\\site-packages\\transformers\\debug_utils.py:21
     20 if is_torch_available():
---> 21     import torch
     24 logger = logging.get_logger(__name__)

File d:\\Programmes\\anaconda3\\envs\\NLP310\\lib\\site-packages\\torch\\__init__.py:128
    127     err.strerror += f' Error loading \"{dll}\" or one of its dependencies.'
--> 128     raise err
    129 elif res is not None:

OSError: [WinError 182] The operating system cannot run %1. Error loading \"d:\\Programmes\\anaconda3\\envs\\NLP310\\lib\\site-packages\\torch\\lib\\fbgemm.dll\" or one of its dependencies.

The above exception was the direct cause of the following exception:

RuntimeError                              Traceback (most recent call last)
d:\\OneDrive\\Data\\Learning\\Natural Science\\Computer Science\\AI, ML, DL\\Hugging Face NLP\
otebooks-main\\course\\en\\chapter3\\section3.ipynb Cell 5 line 1
----> <a href='vscode-notebook-cell:/d%3A/OneDrive/Data/Learning/Natural%20Science/Computer%20Science/AI%2C%20ML%2C%20DL/Hugging%20Face%20NLP/notebooks-main/course/en/chapter3/section3.ipynb#W4sZmlsZQ%3D%3D?line=0'>1</a> from transformers import TrainingArguments
      <a href='vscode-notebook-cell:/d%3A/OneDrive/Data/Learning/Natural%20Science/Computer%20Science/AI%2C%20ML%2C%20DL/Hugging%20Face%20NLP/notebooks-main/course/en/chapter3/section3.ipynb#W4sZmlsZQ%3D%3D?line=2'>3</a> training_args = TrainingArguments(\"test-trainer\")

File <frozen importlib._bootstrap>:1075, in _handle_fromlist(module, fromlist, import_, recursive)

File ~\\AppData\\Roaming\\Python\\Python310\\site-packages\\transformers\\utils\\import_utils.py:1272, in _LazyModule.__getattr__(self, name)
   1270     value = self._get_module(name)
   1271 elif name in self._class_to_module.keys():
-> 1272     module = self._get_module(self._class_to_module[name])
   1273     value = getattr(module, name)
   1274 else:

File ~\\AppData\\Roaming\\Python\\Python310\\site-packages\\transformers\\utils\\import_utils.py:1284, in _LazyModule._get_module(self, module_name)
   1282     return importlib.import_module(\".\" + module_name, self.__name__)
   1283 except Exception as e:
-> 1284     raise RuntimeError(
   1285         f\"Failed to import {self.__name__}.{module_name} because of the following error (look up to see its\"
   1286         f\" traceback):\
{e}\"
   1287     ) from e

RuntimeError: Failed to import transformers.training_args because of the following error (look up to see its traceback):
[WinError 182] The operating system cannot run %1. Error loading \"d:\\Programmes\\anaconda3\\envs\\NLP310\\lib\\site-packages\\torch\\lib\\fbgemm.dll\" or one of its dependencies."
}
```

### Versions

(NLP310) D:\OneDrive\Data\Learning\Natural Science\Computer Science\AI, ML, DL\Hugging Face NLP\notebooks-main\course\en\chapter3>python collect_env.py
Collecting environment information...
PyTorch version: 2.1.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3801
DeviceID=CPU0
Family=107
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=3801
Name=AMD Ryzen 7 5700G with Radeon Graphics
ProcessorType=3
Revision=20480

Versions of relevant libraries:
[pip3] numpy==1.26.0
[pip3] torch==2.1.0
[conda] _tflow_select             2.3.0                       mkl
[conda] blas                      1.0                         mkl
[conda] mkl                       2023.1.0         h6b88ed4_46357
[conda] mkl-service               2.4.0           py310h2bbff1b_1
[conda] mkl_fft                   1.3.8           py310h2bbff1b_0
[conda] mkl_random                1.2.4           py310h59b6b97_0
[conda] numpy                     1.26.0          py310h055cbcc_0
[conda] numpy-base                1.26.0          py310h65a83cf_0
[conda] tensorflow                2.10.0          mkl_py310hd99672f_0
[conda] tensorflow-base           2.10.0          mkl_py310h6a7f48e_0
[conda] torch                     2.1.0                    pypi_0    pypi

(NLP310) D:\OneDrive\Data\Learning\Natural Science\Computer Science\AI, ML, DL\Hugging Face NLP\notebooks-main\course\en\chapter3>

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @atalman @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment] 2023-10-16 14:03
Tentative hi-pri to get a reproducer..

**Comment by Zalnd** [comment] 2023-11-25 20:53
I encounter the same error when I run `import torch`. After some investigation, I discovered that the issue is somehow connected to Jupyter Notebook.

When I execute `import torch` in Python or IPython, it works as expected. However, I face the error when attempting to import PyTorch in a Jupyter Notebook. The issue persists even after stopping the Jupyter server, continuing through IPython as well.

```

(dlhub) d:\>cd D:\hidden

(dlhub) D:\hidden>python
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> exit()

(dlhub) D:\hidden>ipython
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: exit()

(dlhub) D:\hidden>jupyter notebook --no-browser
[I 2023-11-25 17:24:54.266 ServerApp] Package notebook took 0.0001s to import
[I 2023-11-25 17:24:54.425 ServerApp] Package jupyter_lsp took 0.1713s to import
[W 2023-11-25 17:24:54.425 ServerApp] A `_jupyter_server_extension_points` function was not found in jupyter_lsp. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-25 17:24:54.508 ServerApp] Package jupyter_server_terminals took 0.0816s to import
[I 2023-11-25 17:24:54.508 ServerApp] Package jupyterlab took 0.0000s to import
[I 2023-11-25 17:24:55.833 ServerApp] Package nbclassic took 0.0065s to import
[W 2023-11-25 17:24:55.849 ServerApp] A `_jupyter_server_extension_points` function was not found in nbclassic. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-25 17:24:55.849 ServerApp] Package notebook_shim took 0.0000s to import
[W 2023-11-25 17:24:55.849 ServerApp] A `_jupyter_server_extension_points` function was not found in notebook_shim. Instead, a `_jupyter_server_extension_paths` function was found and will be used for now. This function name will be deprecated in future releases of Jupyter Server.
[I 2023-11-25 17:24:55.849 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2023-11-25 17:24:55.865 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2023-11-25 17:24:55.865 ServerApp] jupyterlab | extension was successfully linked.
[I 2023-11-25 17:24:55.880 ServerApp] nbclassic | extension was successfully linked.
[I 2023-11-25 17:24:55.896 ServerApp] notebook | extension was successfully linked.
[I 2023-11-25 17:24:56.465 ServerApp] notebook_shim | extension was successfully linked.
[I 2023-11-25 17:24:56.512 ServerApp] notebook_shim | extension was successfully loaded.
[I 2023-11-25 17:24:56.512 ServerApp] jupyter_lsp | extension was successfully loaded.
[I 2023-11-25 17:24:56.528 ServerApp] jupyter_server_terminals | extension was successfully loaded.
[I 2023-11-25 17:24:56.528 LabApp] JupyterLab extension loaded from C:\Anaconda\envs\dlhub\lib\site-packages\jupyterlab
[I 2023-11-25 17:24:56.528 LabApp] JupyterLab application directory is C:\Anaconda\envs\dlhub\share\jupyter\lab
[I 2023-11-25 17:24:56.528 LabApp] Extension Manager is 'pypi'.
[I 2023-11-25 17:24:56.528 ServerApp] jupyterlab | extension was successfully loaded.

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|

Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[I 2023-11-25 17:24:56.543 ServerApp] nbclassic | extension was successfully loaded.
[I 2023-11-25 17:24:56.559 ServerApp] notebook | extension was successfully loaded.
[I 2023-11-25 17:24:56.559 ServerApp] Serving notebooks from local directory: D:\hidden
[I 2023-11-25 17:24:56.559 ServerApp] Jupyter Server 2.10.0 is running at:
[I 2023-11-25 17:24:56.559 ServerApp] http://localhost:8888/tree?token=HIDDEN
[I 2023-11-25 17:24:56.559 ServerApp]     http://127.0.0.1:8888/tree?token=HIDDEN
[I 2023-11-25 17:24:56.559 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2023-11-25 17:24:56.606 ServerApp]

    To access the server, open this file in a browser:
        file:///C:/Users/HIDDEN/AppData/Roaming/jupyter/runtime/jpserver-10136-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/tree?token=HIDDEN
        http://127.0.0.1:8888/tree?token=HIDDEN
[W 2023-11-25 17:24:56.653 ServerApp] Could not determine npm prefix: [WinError 2] The system cannot find the file specified
[I 2023-11-25 17:24:56.763 ServerApp] Skipped non-installed server(s): bash-language-server, dockerfile-language-server-nodejs, javascript-typescript-langserver, jedi-language-server, julia-language-server, pyright, python-language-server, python-lsp-server, r-languageserver, sql-language-server, texlab, typescript-language-server, unified-language-server, vscode-css-languageserver-bin, vscode-html-languageserver-bin, vscode-json-languageserver-bin, yaml-language-server
[I 2023-11-25 17:25:27.761 ServerApp] Kernel started: 444d3f83-bd10-4889-b984-403b8624b79b
[I 2023-11-25 17:25:29.835 ServerApp] Connecting to kernel 444d3f83-bd10-4889-b984-403b8624b79b.
[I 2023-11-25 17:25:58.638 ServerApp] Saving file at /readme.ipynb
[I 2023-11-25 17:26:09.485 ServerApp] Kernel shutdown: 444d3f83-bd10-4889-b984-403b8624b79b
[I 2023-11-25 17:26:13.283 ServerApp] Shutting down on /api/shutdown request.
[I 2023-11-25 17:26:13.284 ServerApp] Shutting down 6 extensions

[

THAT'S THE ERROR INSIDE JUPYTER NOTEBOOK:

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[1], line 1
----> 1 import tensorflow, torch

File C:\Anaconda\envs\dlhub\lib\site-packages\torch\__init__.py:128
    126     err = ctypes.WinError(last_error)
    127     err.strerror += f' Error loading "{dll}" or one of its dependencies.'
--> 128     raise err
    129 elif res is not None:
    130     is_loaded = True

OSError: [WinError 182] The operating system cannot run %1. Error loading "C:\Anaconda\envs\dlhub\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

]

(dlhub) D:\hidden>ipython
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Cell In[2], line 1
----> 1 import torch

File C:\Anaconda\envs\dlhub\lib\site-packages\torch\__init__.py:128
    126     err = ctypes.WinError(last_error)
    127     err.strerror += f' Error loading "{dll}" or one of its dependencies.'
--> 128     raise err
    129 elif res is not None:
    130     is_loaded = True

OSError: [WinError 182] The operating system cannot run %1. Error loading "C:\Anaconda\envs\dlhub\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

In [3]: exit()

(dlhub) D:\hidden>python
Python 3.10.13 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:15:57) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> exit()

(dlhub) D:\hidden>

```

**Comment by caelorza** [comment] 2024-02-27 18:32
I have the same error when running `import torch`. I have noticed that it happens when I also install either the `cyipopt` or `pynumero_libraries` packages. Before installing either, the line `import torch` runs as expected. It happens in both jupyter and in the terminal.
`>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\candr\anaconda3\envs\test4\lib\site-packages\torch\__init__.py", line 130, in <module>
    raise err
OSError: [WinError 182] The operating system cannot run %1. Error loading "C:\Users\candr\anaconda3\envs\test4\lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.`

**Comment by mantaionut** [comment] 2024-02-28 13:01
@caelorza  I managed to reproduce with installing cyipopt. Where you using conda to install pytorch?
I had no issues with pytorch when using pip, however if installing cyipopt using conda  after installing pytorch using conda then intel-openmp libiomp5md.dll will be overwritten by the one from conda-forge/win-64::openmp-5.0.0-vc14_1 needed by cyipopt.

**Comment by mantaionut** [comment] 2024-03-05 06:26
@Zalnd @phantatbach I could not reproduce it for your cases. Does it still happen to you? Are you using conda to install pytorch?If it does can you please check if libiomp5md.dll gets overwritten?

**Comment by caelorza** [comment] 2024-03-06 05:28
@mantaionut Yes, I figured that out as well. Installing pytorch with pip and the other packages with conda seems to work.

**Comment by sfc-gh-wzhao** [comment] 2024-04-05 22:06
I am also running into this issue, I figured out this potentially relates to the **tensorflow** from anaconda. I could reproduce the issue consistently by 
```
conda create -n tf_torch python=3.8 pytorch tensorflow
conda run -p tf_torch --no-capture-output python -c "import tensorflow; import torch;"
```

If I import either package, both work.

If I install both packages from PyPi, importing both works as well.
```
pip install torch tensorflow
python -c "import tensorflow; import torch;"
```

**Comment by mantaionut** [comment] 2024-04-09 07:45
Closing this issue since it is the same as https://github.com/pytorch/pytorch/issues/72293 to which I opened an issue in anaconda https://github.com/ContinuumIO/anaconda-issues/issues/13146.
@sfc-gh-wzhao This seems to be a different issue. For me it was an error in tensorflow failing to import numpy. And it did not work not even when importing only tensorflow. If your issue still persists and you think it is related to pytorch please open another issue.

**Closed by mantaionut** 2024-04-09 07:45 UTC
Labels: high priority, needs reproduction, module: binaries, module: windows, triaged
