### ISSUE TITLE
[PyTorch] [ONNX] All RNNs fail to export without bias weights

### ISSUE THREAD

**Issue by ryanleary** [pytorch/pytorch#7871] opened 2018-05-26 03:26 UTC
This issue exists in 0.4 and master (at least) and can be demonstrated with the following code:

```python
import torch
import onnx
import io

rnn_types = [torch.nn.RNN, torch.nn.LSTM, torch.nn.GRU]

for rnn_type in rnn_types:
    f = io.BytesIO()
    model = rnn_type(input_size=4, hidden_size=2, num_layers=1, bias=False)
    try:
        torch.onnx.export(model, torch.rand(2, 3, 4), f)
    except ValueError:
        print(rnn_type.__name__, "failed to export")
```

which returns

```
RNN failed to export
LSTM failed to export
GRU failed to export
```

the underlying issue is in `transform_weights` in https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic.py#L914. Should be able to simply add a case here to initialize zero'd tensors.

cc: @jekbradbury 

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by ryanleary** [comment] 2018-12-03 14:48
That patch will break for LSTM I think (due to the constant size), but otherwise is pretty close.

**Comment by jobpasin** [comment] 2020-06-30 09:16
Don't know if there is a patch for this yet or not, but for those who use this code for LSTM, you need to change bias size from

`bias_ih = g.op('Constant', value_t=torch.zeros([3 * hidden_size], dtype=torch.float32))`
`bias_hh = g.op('Constant', value_t=torch.zeros([3 * hidden_size], dtype=torch.float32))`
to
`bias_ih = g.op('Constant', value_t=torch.zeros([4 * hidden_size], dtype=torch.float32))`
`bias_hh = g.op('Constant', value_t=torch.zeros([4 * hidden_size], dtype=torch.float32))`

to make it works. (At least it works for me)

**Comment by garymm** [comment] 2021-08-13 00:47
The code provided by @ryanleary seems to work as expected on latest nightly PyTorch. If this is still an issue, please provide code to reproduce and explain how the observed behavior differs from expected. Thanks.

**Comment by garymm** [comment] 2021-10-16 00:13
Closing due to lack of reply. If this is still an issue in the latest nightly PyTorch please open another issue.

**Closed by garymm** 2021-10-16 00:13 UTC
Labels: module: onnx, triaged, onnx-needs-info
