### ISSUE TITLE
TorchScript sets requires_grad to True under some circumstances

### ISSUE THREAD

**Issue by hal-314** [pytorch/pytorch#43193] opened 2020-08-18 08:36 UTC
## 🐛 Bug

Scripted function occasionally sets tensor requires_grad to True without in tensor with requires_grad is False and no code is setting it. The same function in eager mode has always requieres_grad to False.

## To Reproduce

I had trouble isolation the code. I found this problem when after torch.empty_like or torch.zeros_like. However, in isolation, the bug doesn't show up. 

```python
import torch
import torchvision
from typing import Optional

@torch.jit.script
def friendly_ts_xywh2xyxy(x):
    """Friendly Torchscript function version of xywh2xyxy. Mark with # CHANGED the lines changed from the original version"""
    # Convert nx4 boxes from [x, y, w, h] to [x1, y1, x2, y2] where xy1=top-left, xy2=bottom-right

    # CHANGED TS doens't support np.zeros_like
    # y = torch.zeros_like(x) if isinstance(x, torch.Tensor) else np.zeros_like(x)
    y = torch.zeros_like(x)
    y[:, 0] = x[:, 0] - x[:, 2] / 2  # top left x
    y[:, 1] = x[:, 1] - x[:, 3] / 2  # top left y
    y[:, 2] = x[:, 0] + x[:, 2] / 2  # bottom right x
    y[:, 3] = x[:, 1] + x[:, 3] / 2  # bottom right y
    return y

#@torch.jit.script
def friendly_ts_non_max_suppression(prediction, conf_thres:float=0.1, iou_thres:float=0.6,
                                    merge:bool=False, classes:Optional[torch.Tensor]=None, agnostic:bool=False,
                                    run_on_mobile:bool=False):
    """It's only a fragment"""
    
    if prediction.dtype is torch.float16:
        prediction = prediction.float()  # to FP32

    nc = prediction[0].shape[1] - 5  # number of classes
    xc = prediction[..., 4] > conf_thres  # candidates

    # Settings
    min_wh, max_wh = 2, 4096  # (pixels) minimum and maximum box width and height
    max_det = 300  # maximum number of detections per image
    time_limit = 10.0  # seconds to quit after
    redundant = True  # require redundant detections
    multi_label = nc > 1  # multiple labels per box (adds 0.5ms/img)

    # REMOVED
    #t = time.time()

    # CHANGED type mismatch in scripting. The list is a list of tensors and not of Nones
    # output = [None] * prediction.shape[0]
    output = [torch.empty_like(prediction)]

    for xi, x in enumerate(prediction):  # image index, image inference
        # Apply constraints
        # x[((x[..., 2:4] < min_wh) | (x[..., 2:4] > max_wh)).any(1), 4] = 0  # width-height
        x = x[xc[xi]]  # confidence
        
        # If none remain process next image
        if not x.shape[0]:
            continue

        # Compute conf
        x[:, 5:] *= x[:, 4:5]  # conf = obj_conf * cls_conf
        # Box (center x, center y, width, height) to (x1, y1, x2, y2)
        # CHANGED use friendly TS version of xywh2xyxy
        print('x.requires_grad=', x.requires_grad)
        box = friendly_ts_xywh2xyxy(x[:, :4])# xywh2xyxy(x[:, :4])
        print('box.requires_grad=', box.requires_grad)
        # Detections matrix nx6 (xyxy, conf, cls)

    return output

tt = torch.rand([1, 20, 85])
ts_nms = torch.jit.script(friendly_ts_non_max_suppression)

```
The bug shows up calling `friendly_ts_xywh2xyxy`. However, it didn't appear if I call it directly.
```
friendly_ts_non_max_suppression(tt)
# Output:
# x.requires_grad= False
# box.requires_grad= False

ts_nms(tt)
# Output:
# x.requires_grad= False
# box.requires_grad= True <- It has requires_grad=True!!!!
```

Calling `friendly_ts_xywh2xyxy` returns:
```
def isolated(x):
    x2 = friendly_ts_xywh2xyxy(x)
    print(x.requires_grad, x2.requires_grad)
    
ts_isolated = torch.jit.script(isolated)

isolated(tt) # Prints False False
ts_isolated(tt) # Prints False False <- It doesn't have requires_grad=True!!!
```

## Expected behavior

Torchscript doesn't change required_grad value. In my particular case, I need to use torch.no_grad to be able to run scripted code.

## Environment

PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.6
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.16.4
[conda] _pytorch_select 0.1 cpu_0
[conda] _tflow_select 2.3.0 mkl
[conda] blas 1.0 mkl
[conda] mkl 2019.4 233
[conda] mkl-service 2.0.2 py37h1de35cc_0
[conda] mkl_fft 1.0.14 py37h5e564d8_0
[conda] mkl_random 1.0.2 py37h27c97d8_0
[conda] msgpack-numpy 0.4.3.2 py37_0
[conda] numpy 1.18.1 py37h7241aed_0
[conda] numpy-base 1.18.1 py37h6575580_1
[conda] numpydoc 0.9.2 py_0
[conda] pytorch 1.6.0 py3.7_0 pytorch
[conda] pytorch-lightning 0.8.5 pypi_0 pypi
[conda] tensorflow 1.15.0 mkl_py37hb249377_0
[conda] tensorflow-base 1.15.0 mkl_py37h032239d_0
[conda] torchsummary 1.5.1 pypi_0 pypi
[conda] torchvision 0.7.0 py37_cpu pytorch

## Additional context

I have another code that this happens when using `torch.empty_like(x, dtype=torch.bool)` right after `torch.empty_like(x)` assignments. Commenting `torch.empty_like(x, dtype=torch.bool)` out solves the problem with requires_grad set to True.  As before, it works fine if I isolate the call and I couldn't pinpoint the case

EDIT: it seems that someone has faced a similar problem (16-01-2020) before although with torch.clamp as posted in the [forum](https://discuss.pytorch.org/t/jit-enabling-requires-grad/66855).  

cc @ezyang @gchanan @zou3519 @gmagogsfm @suo

**Comment by eellison** [comment] 2020-09-09 00:39
Hi @hal-314, I tried this on master and could not reproduce. Closing, please re-open if you update to master and are still experiencing issues.

**Comment by gmagogsfm** [comment] 2020-10-13 17:05
Please update to HEAD PyTorch and try again : )

**Closed** 2021-03-25 00:42 UTC
Labels: oncall: jit, triage review
