### ISSUE TITLE
Exporting the pytorch grid_sample operator to ONNX opset version 9 is not supported

### ISSUE THREAD

**Issue by yingsiq** [pytorch/pytorch#44841] opened 2020-09-16 22:50 UTC
## ❓ Questions and Help

I tried to convert a PyTorch model that has a grid_sample operation to ONNX but it was not supported.
I'm using PyTorch version 1.6.0. Please help add support!

Issue was also described but not resolved in:
https://github.com/onnx/onnx/issues/883
https://github.com/pytorch/pytorch/issues/27212
https://github.com/onnx/onnx/issues/2383
https://github.com/microsoft/onnxruntime/issues/2962
https://github.com/AliaksandrSiarohin/first-order-model/issues/92
https://github.com/NVIDIA/TensorRT/issues/130

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment] 2020-09-17 17:32
This is a duplicate of https://github.com/pytorch/pytorch/issues/27212. Please consider submitting a PR for this. 

I will close this issue and track this enhancement request in https://github.com/pytorch/pytorch/issues/27212.

**Closed by spandantiwari** 2020-09-17 17:32 UTC
Labels: module: onnx, triaged
