### ISSUE TITLE
15x regression in 0-change build time for torch C++ files.

### ISSUE THREAD

**Issue by zdevito** [pytorch/pytorch#9680] opened 2018-07-21 17:31 UTC
When debugging the C++ files in torch, to get consistent debugging signal, we need to _always_ rebuild before running the python tests. Previously because torch files were all building in the `develop` phase, a non-changed build would take ~1 second, making it easy to run it all the time.

Now that some _but not all_ files have moved into the `build` phase, non-changed builds take 15 seconds, a 15x slowdown that makes it impractical to consistently re-build.

We need to improve the non-changed speed of the build phase for this to be an acceptable dev situation.

@anderspapitto @ezyang

**Comment by apaszke** [comment] 2018-07-21 18:33
An improvement is to do `python setup.py build_caffe2`, but it still takes 3-5x longer than our previous build.

**Comment by ezyang** [comment] 2018-07-21 20:51
IIUC, most of the problem is that it keeps rerunning cmake, is that right? `(cd build && ninja install)` might be a workaround if you just want to build.

**Comment by anderspapitto** [comment] 2018-07-24 21:36
so, what exactly do we want here? If I combine the above suggestions, I can do

```
(venv)[andersj@devgpu201.prn2 ~/local/pytorch] time bash -c '(cd build && ninja install) && python setup.py develop' >/dev/null 2>&1

real    0m0.910s
user    0m0.883s
sys     0m2.792s
```

is it enough to just make `setup.py rebuild` be a synonym for this?

**Comment by soumith** [comment] 2018-07-24 21:38
rerunning cmake shouldn't take very long if all the relevant variables are cached. So, ideally looking into caching all relevant cmake variables has to be done.
Anders' solution looks reasonable as well, if we dont need to spend too much time on this.

**Comment by ezyang** [comment] 2018-07-24 21:44
I think the problem is that the old build workflow keeps rerunning cmake, and there was never any communication how to do rebuilds without rerunning cmake.

**Comment by anderspapitto** [comment] 2018-07-24 21:50
@soumith is there a way to ask cmake which variables are uncached?

**Comment by soumith** [comment] 2018-07-24 22:12
there seems to be a way to print out all variables: https://stackoverflow.com/questions/9298278/cmake-print-out-all-accessible-variables-in-a-script

And then you can print out cached variables: `cmake -LA`. You can invert to get uncached variables.

**Comment by anderspapitto** [comment] 2018-07-26 19:49
there's two big chunks to the cost. One is build_pytorch_libs, and the other is generate_code(), also called from setup.py (and which still gets called even if you do `python setup.py build_caffe2`

**Comment by mruberry** [comment] 2021-01-20 13:28
Closing due to age. If this issue is still happening on a newer version of PyTorch please file a new issue.

**Closed by mruberry** 2021-01-20 13:28 UTC
