### ISSUE TITLE
'torch.IntTensor' object has no attribute 'neg'

### ISSUE THREAD

**Issue by ThaHypnotoad** [pytorch/pytorch#1894] opened 2017-06-23 22:16 UTC
Pretty simple. for an integer tensor foo, -foo gives this error.
Workaround: -1*foo

**Comment by nicci1771** [comment] 2017-07-10 09:21
Hi, I met a similar bug,
AttributeError: 'torch.cuda.ByteTensor' object has no attribute 'neg' 
Have you solved it yes?

Thanks!

**Comment by shrshore** [comment] 2017-08-09 02:44
@ThaHypnotoad @nicci1771 I met similar problem too. Otherwise I wonder how to implement similar features when I calculate the 'true negative' values like ``torch.sum((torch.eq(pred, targets) & (torch.neg(pred)))`` but the neg method is not implemented on ByteTensor. Actually I wonder whether there exists an alternative method to implement same features?

**Comment by leezu** [comment] 2017-08-09 02:47
This seems like a regression in pytorch v0.2, I think it should have higher priority as it breaks code that was working before.

**Comment by soumith** [comment] 2017-08-09 04:03
@gchanan issue a fix asap. @leezu sorry we didn't catch this

**Comment by leezu** [comment] 2017-08-09 04:37
No worries.

```
    neg_mask = (neg_mask - neg_mask.transpose(0, 1)) != 0
    # ByteTensor can't be used for - arithmetic in pytorch v0.2
    n_pos = (1 + (-1) * neg_mask).sum()  # Number of pairs
```

is an example of code that only works with the `* -1` trick now, as neg_mask is a ByteTensor

**Comment by gchanan** [comment] 2017-08-09 16:40
@leezu can you provide code and version that worked on a previous version and fails now?

This failed on v0.1.12 fail me:
```
>>> -torch.IntTensor(5)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/users/gchanan/pytorch8d/torch/tensor.py", line 327, in __neg__
    return self.neg()
AttributeError: 'torch.IntTensor' object has no attribute 'neg'
```

**Comment by gchanan** [comment] 2017-08-09 16:45
Looks like this was broken in v0.1.11:
https://github.com/pytorch/pytorch/commit/ef081526fcc349d500f733182022741450de674d

**Comment by gchanan** [comment] 2017-08-09 19:42
should be fixed by https://github.com/pytorch/pytorch/pull/2357 / https://github.com/pytorch/pytorch/pull/2358.

**Comment by glample** [comment] 2017-08-09 19:44
Does it also work for ByteTensors?

**Comment by gchanan** [comment] 2017-08-09 19:48
It's not defined for ByteTensors, which doesn't seem unreasonable because they are unsigned.  Is there a use case where you'd want this function defined?

**Comment by glample** [comment] 2017-08-09 20:55
When I select hidden states in a LSTM output of sequences with different lengths, I use masked_select to select all relevant hidden states (with a mask `m`). But in some cases (LSTM with attention, in my case), I was using masked_fill with `1-m` to fill with `0` the non relevant states, where `m` is the same as before. So now I have to do `1 + (-1) * m`, but I think it would be nice to be able to call `1-m` directly.
Moreover, numpy allows it.

**Comment by gchanan** [comment] 2017-08-09 21:12
You can do that right?
```
>>> a = torch.randn(10) < 0
>>> a

 1
 0
 1
 0
 0
 0
 0
 0
 1
 1
[torch.ByteTensor of size 10]

>>> 1-a

 0
 1
 0
 1
 1
 1
 1
 1
 0
 0
[torch.ByteTensor of size 10]
```

That being said, you are correct that numpy allows it:
```
>>> -np.uint8(2)
254
>>> np.negative(np.uint8(2))
254
```

**Comment by glample** [comment] 2017-08-09 21:13
I can, but not if this is a Variable.

**Comment by gchanan** [comment] 2017-08-09 21:19
right.  @glample do you know if this ever worked for you?

**Comment by glample** [comment] 2017-08-09 21:20
yes, it was working on my previous version of pytorch (0.1.12_2 I believe)

**Comment by soumith** [comment] 2017-08-15 07:15
fixed on master via https://github.com/pytorch/pytorch/pull/2357

**Closed by soumith** 2017-08-15 07:15 UTC
Labels: bug, enhancement, low priority
