### ISSUE TITLE
Unable to import 1.1 when installing with pip

### ISSUE THREAD

**Issue by MichaelDylan77** [pytorch/pytorch#20118] opened 2019-05-04 00:06 UTC
## 🐛 Bug

It seems there is an issue with the pip installation of 1.1. After upgrading, I get an error when calling `import torch`.

## To Reproduce

1. Install torch==1.1.0 with pip

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/torch/lib/python3.6/site-packages/torch/__init__.py", line 79, in <module>
    from torch._C import *
ImportError: dlopen(/anaconda3/envs/torch/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so, 9): Library not loaded: /usr/local/opt/libomp/lib/libomp.dylib
  Referenced from: /anaconda3/envs/torch/lib/python3.6/site-packages/torch/lib/libshm.dylib
  Reason: image not found

## Expected behavior

The torch package should import...

## Environment

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Mac OSX 10.14.4
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.16.3
[pip3] torch==1.1.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.3                      199  
[conda] mkl-service               1.1.2            py37hfbe908c_5  
[conda] mkl_fft                   1.0.10           py37h5e564d8_0  
[conda] mkl_random                1.0.2            py37h27c97d8_0

**Comment by codexetreme** [comment] 2019-05-05 09:20
I have the same issue when running with python 3.6, if you use 3.7 however, it works. I haven't checked for other versions though

**Comment by kaszperro** [comment] 2019-05-05 11:42
Probably duplicate of #20030
try `brew install libomp `

**Comment by MichaelDylan77** [comment] 2019-05-05 19:08
@kaszperro definitely is a duplicate. Looks like that issue was reopened. Installing libomp does indeed work as a quick-fix for this.

**Comment by izdeby** [comment] 2019-05-06 17:15
dup of #20030. lets discuss there

**Closed by izdeby** 2019-05-06 17:15 UTC
Labels: duplicate, high priority, module: build, needs discussion

**Comment by soumith** [comment] 2019-06-21 22:10
uploaded new binaries that remove dependency on `libomp.dylib`
