### ISSUE TITLE
Inplace add result is not correct under certain case

### ISSUE THREAD

**Issue by yenchanghsu** [pytorch/pytorch#1730] opened 2017-06-05 18:59 UTC
Case 1: with inplace add => incorrect result
```
import torch
source=torch.ones(91,91)
target=torch.zeros(91,91)
target.add_(source)
print(target)

    3     3     3  ...      3     3     3
    3     3     3  ...      3     3     3
    3     3     3  ...      3     3     3
       ...          ⋱          ...       
    3     3     3  ...      3     3     3
    3     3     3  ...      3     3     3
    3     3     3  ...      3     3     3
[torch.FloatTensor of size 91x91]
```

Case 2: without inplace add => works properly
```
source=torch.ones(91,91)
target=torch.zeros(91,91)
target = target.add(source)
print(target)

    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
       ...          ⋱          ...       
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
[torch.FloatTensor of size 91x91]
```

Case 3: inplace add with smaller tensor => works properly
```
source=torch.ones(90,90)
target=torch.zeros(90,90)
target.add_(source)
print(target)

    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
       ...          ⋱          ...       
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
    1     1     1  ...      1     1     1
[torch.FloatTensor of size 90x90]
```

Case 4: inplace add with larger tensor =>  incorrect result with larger values
```
source=torch.ones(300,300)
target=torch.zeros(300,300)
target.add_(source)
print(target)

    6     6     6  ...      6     6     6
    6     6     6  ...      6     6     6
    6     6     6  ...      6     6     6
       ...          ⋱          ...       
    6     6     6  ...      6     6     6
    6     6     6  ...      6     6     6
    6     6     6  ...      6     6     6
[torch.FloatTensor of size 300x300]
```

### More details:
Case 1 and 4 only failed on one machine but works properly on another machine (with the same pytorch version). I guess the issue is caused by a dependent module? Could someone give me a hint to further analyze the issue? 
- pytorch version: 0.1.12_2
- Linux, pip, python 2.7

**Comment by soumith** [comment] 2017-06-05 20:31
hi @yenchanghsu 

As you mentioned, I could not reproduce this on my machine either.

On the failing machine, can you give the output of:

```
cat /proc/cpuinfo
```

Next, can you please do the following.
Put this content into `foo.py`

```python
import torch
source=torch.ones(91,91)
target=torch.zeros(91,91)
target.add_(source)
print(target)
```

Then, run the following commands and tell which ones are incorrect:
```bash
TH_NO_AVX2=1 python foo.py
TH_NO_AVX=1  python foo.py
TH_NO_SSE=1  python foo.py
```

**Comment by yenchanghsu** [comment] 2017-06-05 23:16
Hi @soumith 
All three commands gave incorrect results.
Furthermore, if I repeatedly run "foo.py", the results are random patterns of {1,2,3}. Such randomness happened with all three options you gave. Here is an example:
```
    2     2     2  ...      1     1     1
    1     1     1  ...      1     1     1
    1     1     1  ...      2     2     2
       ...          ⋱          ...       
    3     3     3  ...      3     3     3
    3     3     3  ...      3     3     3
    3     3     3  ...      3     3     3
[torch.FloatTensor of size 91x91]
```
The cpuinfo:
```
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 45
model name	: Intel(R) Xeon(R) CPU E5-2667 0 @ 2.90GHz
stepping	: 7
microcode	: 0x710
cpu MHz		: 1200.000
cache size	: 15360 KB
physical id	: 0
siblings	: 12
core id		: 0
cpu cores	: 6
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm ida arat epb xsaveopt pln pts dtherm tpr_shadow vnmi flexpriority ept vpid
bogomips	: 5785.67
clflush size	: 64
cache_alignment	: 64
address sizes	: 46 bits physical, 48 bits virtual
power management:
```

**Comment by soumith** [comment] 2017-06-06 02:01
1. did you install pytorch from `pip`, `conda` or source?
2. did you `import` any other packages before or after you did `import torch`?
3. what's the output of the command:
```
ldd $(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")/torch/_C.so
```

**Comment by yenchanghsu** [comment] 2017-06-06 17:31
1. Installed from pip (ver. 9.0.1) with python 2.7
2. No. Simply run "python foo.py" you mentioned above could produce the issue on my machine.
3. The command you provided outputs:
```
ldd: /usr/lib/python2.7/dist-packages/torch/_C.so: No such file or directory
```
I run following instead:
```
ldd /usr/local/lib/python2.7/dist-packages/torch/_C.so
``````
And here are the outputs:
```
	linux-vdso.so.1 =>  (0x00007fffdc5a0000)
	/usr/lib/gcc/x86_64-linux-gnu/4.8/libgomp.so (0x00007f2d7b78e000)
	libshm.so => /usr/local/lib/python2.7/dist-packages/torch/lib/libshm.so (0x00007f2d7b4ae000)
	libcudart.so.8.0 => /usr/local/cuda/lib64/libcudart.so.8.0 (0x00007f2d7b248000)
	libcudnn.so.6 => /usr/local/lib/python2.7/dist-packages/torch/lib/libcudnn.so.6 (0x00007f2d71ce6000)
	libpython2.7.so.1.0 => /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0 (0x00007f2d71766000)
	libTH.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTH.so.1 (0x00007f2d711c2000)
	libTHS.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTHS.so.1 (0x00007f2d70f92000)
	libTHPP.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTHPP.so.1 (0x00007f2d70bff000)
	libTHNN.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTHNN.so.1 (0x00007f2d708fb000)
	libTHC.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTHC.so.1 (0x00007f2d61d1d000)
	libTHCS.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTHCS.so.1 (0x00007f2d619b2000)
	libTHCUNN.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libTHCUNN.so.1 (0x00007f2d5ed9a000)
	libnccl.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libnccl.so.1 (0x00007f2d5c0be000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f2d5bea8000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2d5bc8a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2d5b8c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f2d7c86c000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f2d5b6bd000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f2d5b3b7000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2d5b1b3000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f2d5aeaf000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2d5ac96000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f2d5aa93000)
	libmkl_intel_lp64.so => /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_lp64.so (0x00007f2d5a071000)
	libmkl_intel_thread.so => /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_thread.so (0x00007f2d5860c000)
	libmkl_core.so => /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_core.so (0x00007f2d56b14000)
	libiomp5.so => /usr/local/lib/python2.7/dist-packages/torch/lib/libiomp5.so (0x00007f2d5676a000)
	libcublas.so.8.0 => /usr/local/cuda/lib64/libcublas.so.8.0 (0x00007f2d53dba000)
	libcurand.so.8.0 => /usr/local/cuda/lib64/libcurand.so.8.0 (0x00007f2d4fe51000)
	libcusparse.so.8.0 => /usr/local/cuda/lib64/libcusparse.so.8.0 (0x00007f2d4d343000)
```
I compared the list between two machines.
The machine with the issue has the line:
```
/usr/lib/gcc/x86_64-linux-gnu/4.8/libgomp.so (0x00007f2d7b78e000)
```
The machine "without" the issue use the one in torch:
```
libgomp.so.1 => /usr/local/lib/python2.7/dist-packages/torch/lib/libgomp.so.1 (0x00007fa9f10eb000)
```
Could it cause the issue?

**Comment by soumith** [comment] 2017-06-06 17:51
hmm, that could certainly be related.
Can you run the program with:

```
OMP_NUM_THREADS=1 python foo.py
```

Does that fix the problem?
If so what Linux distro / version are you using (Example: Ubuntu 12.04, RHEL6)

**Comment by yenchanghsu** [comment] 2017-06-06 23:09
Yes, set OMP_NUM_THREADS=1 fix the problem.
The Linux distro is Ubuntu 14.04.5 LTS

**Comment by albanD** [comment] 2019-11-27 16:27
Closing tentatively as it was most likely a library compatibility issue.

**Closed by albanD** 2019-11-27 16:27 UTC
