### ISSUE TITLE
Feature request: mul(Sparse, Dense) -> Sparse

### ISSUE THREAD

**Issue by chivee** [pytorch/pytorch#2909] opened 2017-09-30 08:01 UTC
Hi, I would like to see that pytorch could offer an element-wise production for Sparse * Dense -> Dense.

for now, I need to convert Dense to Sparse then convert the result to Dense again.

BTW, as #2886 mentioned, the Sparse function was missing. does that intentional or bug?

cc @vincentqb

**Comment by IvanYashchuk** [comment] 2022-03-11 08:38
In general, an element-wise product of a sparse matrix and a dense matrix is sparse.
Sparse * Dense -> Dense can be obtained by converting the sparse result of Sparse * Dense. Element-wise product for COO tensors is being added in https://github.com/pytorch/pytorch/pull/69416.

**Comment by IvanYashchuk** [comment] 2022-03-11 08:46
This is a duplicate of https://github.com/pytorch/pytorch/issues/3158. Thank you for submitting both issues! I will close this one.

**Closed by IvanYashchuk** 2022-03-11 08:46 UTC
Labels: module: sparse, triaged
