### ISSUE TITLE
[quant] `_neg_view` segfaults with quantized tensor.

### ISSUE THREAD

**Issue by kshitij12345** [pytorch/pytorch#88484] opened 2022-11-04 09:08 UTC
### 🐛 Describe the bug

Following code segfaults:
```python
torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8)._neg_view()
```

I am not sure if `_neg_view` should work or return an Error but it shouldn't Segfault.

### Versions

master

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @VitalyFedyunin @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @gchanan @zou3519

**Comment by kshitij12345** [comment] 2022-11-04 09:09
cc: @anjali411

**Comment by anjali411** [comment] 2022-11-14 21:11
yeah we should fix this. fun fact though that this exits normally when run with gdb

**Comment by Xia-Weiwen** [comment] 2023-01-11 04:09
I will take a look of this. There is one thing I am not sure of. What should be the expected behavior of `_neg_view` with quantized tensors?

**Comment by ezyang** [comment] 2023-01-11 07:45
Cc @dagitses this is the same mechanism as infallible views

**Comment by Xia-Weiwen** [comment] 2023-01-12 03:03
Some findings:
- To reproduce it with gdb, add a `print` like
```
qx = torch.quantize_per_tensor(torch.tensor([-1.0, 0.0, 1.0, 2.0]), 0.1, 10, torch.quint8)
print(qx._neg_view())
```
- The `segfault` is caused by infinite recursion of `at::native::quantized_clone -> at::Tensor::qscheme -> at::native::negationFallback -> at::clone -> at::native::quantized_clone`. Not sure how to fix it yet. Any help would be much appreciated.

**Comment by mingfeima** [comment] 2023-02-10 04:59
@sanchitintel , could you please help debugging this one ? thank!

**Comment by Xia-Weiwen** [comment] 2023-03-06 02:13
Hi @sanchitintel. Do you have any updates on this? Shall I assign this to you? Thanks.

**Comment by sanchitintel** [comment] 2023-03-06 02:20
Hi @Xia-Weiwen, I'll look into it tonight. You can assign it to me. Thanks!

**Comment by sanchitintel** [comment] 2023-03-06 20:39
Hi @anjali411, please advise if `at::native::quantized_clone` needs to be modified to fix this issue, based on your comment here:

https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/MathBitsFallback.h#L24.

Currently, `at::native::negationFallback` -> `at::native::MathOpFallback::fallback_impl` calls `at::native::clone`, which, in turn calls `at::native::quantized_clone`, but when `at::Tensor::qscheme` is called here, it's redispatched back to `at::native::negationFallback`, and this forms an infinite loop. Please advise how to ensure correct dispatch of `qscheme`.

Thank you!

**Comment by ezyang** [comment] 2023-03-06 23:35
Fallthrough on q scheme sgtm

**Comment by sanchitintel** [comment] 2023-03-17 22:45
Thanks for your inputs, @ezyang!

An issue here that's orthogonal to preventing the segfault is that `at::native::negationFallback` is only being called when the output of `_neg_view` is to be printed. Can you please help explain this dispatching behavior? Thanks

**Comment by ezyang** [comment] 2023-03-18 12:43
That's expected; neg view lazily does the negation

**Closed** 2023-07-17 15:00 UTC
Labels: oncall: quantization, module: cpu, intel
