### ISSUE TITLE
Windows CI build failure: thrust/detail/allocator/allocator_traits.inl(101): error C2065: 't': undeclared identifier

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#25389] opened 2019-08-29 13:37 UTC
```
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): error C2065: 't': undeclared identifier
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): error C2923: 'std::_Select<__formal>::_Apply': 't' is not a valid template type argument for parameter '<unnamed-symbol>'
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/include\thrust/detail/allocator/allocator_traits.inl(101): error C2062: type 'unknown-type' unexpected
"
```

https://ci.pytorch.org/jenkins/job/caffe2-builds/job/py2-cuda9.0-cudnn7-windows-trigger-build/65967/

In this case it failed while `Building NVCC (Device) object caffe2/CMakeFiles/torch.dir/__/aten/src/THC/generated/torch_generated_THCTensorMaskedShort.cu.obj`

It doesn't seem to happen reliably which is very mysterious.

cc @peterjc123

**Comment by peterjc123** [comment] 2019-09-06 11:56
Again I'm suspecting it is an NVCC bug, especially in CUDA 10.1.

**Comment by peterjc123** [comment] 2020-03-05 05:02
Duplicate of https://github.com/pytorch/pytorch/issues/25393.

**Closed by peterjc123** 2020-03-05 05:02 UTC
Labels: module: build, module: windows, triaged
