### ISSUE TITLE
Unable to load nvprof trace

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#33986] opened 2020-02-28 23:38 UTC
## 🐛 Bug

Unable to load an nvprof trace (tried CUDA toolkit 10.1 and 10.0)

## To Reproduce

1. Wrap pyTorch code with autograd profiling
```
    with torch.cuda.profiler.profile():
         with torch.autograd.profiler.emit_nvtx():
            main()
```
2. Profile code using nvprof
3. Try to load profile with autograd
```
import torch
prof = torch.autograd.profiler.load_nvprof("file.nvprof")
```
4. Hit assertion
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/lib/python3.6/site-packages/torch/autograd/profiler.py", line 469, in load_nvprof
    return EventList(parse_nvprof_trace(path))
  File "/path/to/lib/python3.6/site-packages/torch/autograd/profiler.py", line 766, in parse_nvprof_trace
    assert row['cbid'] == 13  # 13 == Launch
AssertionError
```

## Expected behavior

No assertion.

## Environment

PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.105

Nvidia driver version: 418.116.00
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.4
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] magma-cuda101             2.5.1                         1    pytorch
[conda] mkl                       2019.4                      243
[conda] mkl-include               2019.4                      243
[conda] mkl-service               2.3.0            py36he904b0f_0
[conda] mkl_fft                   1.0.15           py36ha843d7b_0
[conda] mkl_random                1.1.0            py36hd6b4f25_0
[conda] pytorch                   1.4.0           py3.6_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py36_cu101    pytorch

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by ptrblck** [comment] 2020-02-29 02:06
I can reproduce this failure locally using the nightly binary from today + CUDA10.1.
As a workaround, could you use [`torch.autograd.profiler.profile(use_cuda=True)`](https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.profile), which seems to take another path.

We'll try to isolate this issue.

**Comment by msbaines** [comment] 2020-02-29 02:13
> I can reproduce this failure locally using the nightly binary from today + CUDA10.1.
> As a workaround, could you use [`torch.autograd.profiler.profile(use_cuda=True)`](https://pytorch.org/docs/stable/autograd.html#torch.autograd.profiler.profile), which seems to take another path.
> 
> We'll try to isolate this issue.

When I use  `torch.autograd.profiler.profile(use_cuda=True)`, my application (training a MT model using [fairseq](https://github.com/pytorch/fairseq)) runs 3.2x or 220% slower.

**Comment by ptrblck** [comment] 2020-02-29 02:14
I'm not sure at the moment, but the first command might skip the actual profiling, thus creating an invalid file and just run "fast".

**Comment by msbaines** [comment] 2020-02-29 06:21
> I'm not sure at the moment, but the first command might skip the actual profiling, thus creating an invalid file and just run "fast".

I am able to load the nvprof file from the first case with nvvp and I can see the autograd emitted nvtx annotations. I just can't load it with autograd (assertion).

In the second slow case, I export a chrome trace.  For measuring overhead, I compared the time for a single iteration using time.perf_counter().

**Comment by ezyang** [comment] 2020-03-02 19:41
Marking as high priority as it seems like basic functionality in the autograd profiler does not work. We may revise priority down if it turns out this only happens in rare circumstances, but given that ptrblck could repro that probably is not the case.

**Closed** 2020-03-20 15:25 UTC
Labels: high priority, module: profiler, triaged
