### ISSUE TITLE
[PT2.0][compile] torch._dynamo.config.log_level does not exist

### ISSUE THREAD

**Issue by jay746** [pytorch/pytorch#104022] opened 2023-06-22 05:39 UTC
### 🐛 Describe the bug

setting torch._dynamo.config.log_level=logging.DEBUG causes error in nightly build 20230622
while this link mentiones that we can have it. https://pytorch.org/docs/master/compile/troubleshooting.html  

### Error logs

torch_executor.py:21: in <module>
    torch._dynamo.config.log_level=logging.DEBUG
/home/jthakur/.pt_2_0/lib/python3.8/site-packages/torch/_dynamo/config_utils.py:71: in __setattr__
    raise AttributeError(f"{self.__name__}.{name} does not exist")
E   AttributeError: torch._dynamo.config.log_level does not exist

### Versions

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] torch==2.1.0.dev20230621+cpu
[pip3] torchaudio==2.1.0.dev20230621+cpu
[pip3] torchvision==0.16.0.dev20230621+cpu
[pip3] triton==2.0.0
[conda] Could not collect

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by mlazos** [comment] 2024-03-06 00:41
I need to update this doc

**Comment by mlazos** [comment] 2024-07-11 02:14
Closing as a duplicate of https://github.com/pytorch/pytorch/issues/126349

**Closed by mlazos** 2024-07-11 02:14 UTC
Labels: module: logging, triaged, oncall: pt2
