### ISSUE TITLE
Load pytorch tensor created by torch.save(tensor_name, tensor_path) in c++ libtorch failed.

### ISSUE THREAD

**Issue by Edwardmark** [pytorch/pytorch#36568] opened 2020-04-14 08:04 UTC
## 🐛 Bug

Load pytorch tensor created by torch.save(tensor_name, tensor_path) in c++ libtorch failed.
How can I save some tensor in python, but load it in libtorch?
## To Reproduce

using the following code:

I save tensor named piror using python, using the code:
```
prior = torch.ones(32145, 4)
torch.save(prior,  'prior.pth')
```
And I load the tensor in libtorch using C++, by the following code:
```
torch::Tensor priors = torch::ones({32145, 4});
torch::load(priors , "/app/model/prior.pth");
```

## Expected behavior
load the tensor successfully.
And get exact same value as in pytorch python-api.

## Environment
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Ubuntu 16.04.5 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.13.2

Python version: 3.5
Is CUDA available: N/A
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 430.26
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.4.2

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

## Additional context
But I got the error:
terminate called after throwing an instance of 'c10::Error'
  what():  `torch::jit::load()` received a file from `torch.save()`, but `torch::jit::load()` can only load files produced by `torch.jit.save()` (load at ../torch/csrc/jit/serialization/import.cpp:285)

Why is that? I do not use torch::jit::load but torch::load, so how to load tensor saved in pytorch?

Thanks in advance.

cc @suo @yf225

**Comment by mrshenli** [comment] 2020-04-14 14:31
cc @glaringlee

**Comment by forresti** [comment] 2020-04-14 19:31
I'm no expert, but here's a thing that I've done to save tensors from Python and load them in C++.

python:
```
import torch
from torch import nn

class TensorContainer(nn.Module):
    def __init__(self, tensor_dict):
        super().__init__()
        for key,value in tensor_dict.items():
            setattr(self, key, value)

prior = torch.ones(32145, 4)
tensor_dict = {'prior': prior}
tensors = TensorContainer(tensor_dict)
tensors = torch.jit.script(tensor_dict)
tensors.save('prior.pth') # I believe this is the 'torch.jit.save()' thing that your error message is asking for.
```

C++:
```
#include "torch/csrc/jit/import.h"
#include "torch/script.h"

void main(){
    torch::jit::script::Module tensors = torch::jit::load("prior.pth");
    torch::Tensor prior = tensors.get_attribute("prior").toTensor();
}
```

I don't know if the TensorContainer is necessary, or of there is a more elegant solution. I made the TensorContainer because I wanted to save multiple tensors (e.g. input data *and* ground-truth) to one file.

related: https://discuss.pytorch.org/t/load-tensors-saved-in-python-from-c-and-vice-versa/39435

**Comment by yf225** [comment] 2020-04-14 20:40
This is likely a duplicate of https://github.com/pytorch/pytorch/issues/20356, and we can try the solution @driazati suggested: https://github.com/pytorch/pytorch/issues/20356#issuecomment-567663701

**Closed** 2020-04-14 20:40 UTC
Labels: jit, module: cpp, module: serialization

**Comment by glaringlee** [comment] 2020-04-14 21:22
FYI - C++ frontend api currently only supports loading jit saved tensor file.
Please use jit save from python side at this point.

**Comment by Xavier31** [comment] 2021-11-19 11:35
torch.jit.save only save modules not tensor as far as i understand. Is there a simple way to save a tensor in pytorch and load it in libtorch without making any wrapper ?
