### ISSUE TITLE
Pytorch + CUDA build: CuSparseHandlePool.obj: error LNK2019

### ISSUE THREAD

**Issue by Andrej-sens** [pytorch/pytorch#30075] opened 2019-11-19 13:20 UTC
I was trying to build Pytorch from source using Cuda 10.1 on Windows 10. However, I got  
```
Creating library .../pytorch/build/lib/Debug/torch.lib and object .../pytorch/build/lib/Debug/torch.exp
8>CuSparseHandlePool.obj : error LNK2019: unresolved external symbol "char const * __cdecl cusparseGetErrorString(enum cusparseStatus_t)" (?cusparseGetErrorString@@YAPEBDW4cusparseStatus_t@@@Z) referenced in function "void __cdecl at::cuda::`anonymous namespace'::createCusparseHandle(struct cusparseContext * *)" (?createCusparseHandle@?A0x9150e0b4@cuda@at@@YAXPEAPEAUcusparseContext@@@Z)
8>  Hint on symbols that are defined and could potentially match:
8>    cusparseGetErrorString
8>...\pytorch\build\bin\Debug\torch.dll : fatal error LNK1120: 1 unresolved externals
```
I tried also use pre-built Libtorch but I got errors on gpu implementation. More information is [here](https://github.com/pytorch/pytorch/issues/30076#issue-525008428).
Can you help me out please?

cc @peterjc123

**Comment by peterjc123** [comment] 2019-11-19 13:32
Well, looks like that we will need to link against cusparse.lib too.

**Comment by peterjc123** [comment] 2019-11-19 13:40
Wait! Looks like the function should be only involved in CUDA 10.2. https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu#L11

**Comment by peterjc123** [comment] 2019-11-19 13:57
This is weird that we could not reproduce in the nightly CI. Could you please tell me how you tried to do the build?

**Comment by peterjc123** [comment] 2019-11-19 14:06
cc @ezyang

**Comment by Andrej-sens** [comment] 2019-11-19 14:07
In build directory

`cmake .. -G "Visual Studio 16 2019" -A x64`

It automatically linked CUDA 10.1 and all dependecies except Python Debug Library which I linked manually through CMake GUI. 
However, it found cuDNN 7.6.5 in Cuda 10.0 library folder but I think it doesn't matter where it is placed.

**Comment by peterjc123** [comment] 2019-11-19 14:22
This is how you configured the CMake project. How about the build process? Did you open the VS project (.sln/.vcproj) and build?

**Comment by peterjc123** [comment] 2019-11-19 14:26
I have to say it's totally weird. The macro `TORCH_CUDASPARSE_CHECK` is used both the source files:
```
aten\src\ATen\cuda\CuSparseHandlePool.cpp
aten\src\ATen\cuda\CublasHandlePool.cpp
```
which is defined in 
```
aten\src\ATen\cuda\Exceptions.h
```
However, the function `cusparseGetErrorString` is also declared in that file. The confusing part is that why only the symbol in one of the files is missing?

**Comment by Andrej-sens** [comment] 2019-11-19 14:37
> This is how you configured the CMake project. How about the build process? Did you open the VS project (.sln/.vcproj) and build?

Yes, compiled in VS2019. I forgot to mention (probably related) another change in project. Compailing a Torch project was causing error 
` cl: command line error D8016:'/Ox' and '/RTC' command-line options are incompatible.`

I found that this can be resolved by [this](https://stackoverflow.com/questions/23179136/visual-studio-command-line-error-d8016-ox-and-rtc-command-line-options-a) solution (setting it to Default)

**Comment by peterjc123** [comment] 2019-11-19 14:54
I believe these flags are indicating that you are not doing it in the right way. Usually, we will do this for a debug libtorch build.
```powershell
set DEBUG=1
set CMAKE_GENERATOR=Visual Studio 2019
python tools\build_libtorch.py
```

**Comment by peterjc123** [comment] 2019-11-19 14:56
For more details, you can read how we build the libtorch binaries:
https://github.com/pytorch/builder/blob/master/windows/internal/setup.bat#L34

**Comment by Andrej-sens** [comment] 2019-11-19 14:58
Thank you, I'll check it out.

**Comment by Andrej-sens** [comment] 2019-11-22 09:34
The build failed again. 

I configured cmakefile with `tools\build_libtorch.py` and build it in Visual Studio. I tried to build it directly in console but apparantelly every time I run out of memory even I have 16GB. I tried solution described [here](https://github.com/pytorch/pytorch/issues/20296) by setting `MAX_JOBS=1` but it did not help. I believe it can be done setting `/MP[x]` flag but in `build_libtorch.py` I have no idea where to set it. With Visual studio I could limit number of builds in settings.

Anyway, I have created [file](https://github.com/Andrej-sens/cudaDepthFilters-0.1a/blob/master/Pytoch_master_error) and put there whole print from build so it would not kidnap whole webpage here. Still the same error.

Spec for build.
- Windows 10
- CUDA 10.1
- NVIDIA Quadro P5000
- Visual Studio 16 2019
- Python 3.7.4 (Tried 3.5.4 as well)

**Comment by peterjc123** [comment] 2019-11-22 10:07
Would you please try the nightly build? For the memory issue, limiting the threads won't work because it is the linking process that takes much memory, but it only uses one process/thread. This issue should be resolved recently by splitting the libraries into `libtorch_cpu` and `libtorch`. @ezyang can tell you more about this.

**Comment by ezyang** [comment] 2019-11-22 14:17
That diff got reverted; you'll have to unrevert it and give it a try

**Comment by Andrej-sens** [comment] 2019-11-25 09:13
I managed to run a nightly build. I had to turn off every process due to running out of memory. However, the same issue, same error.

I've updated [file](https://github.com/Andrej-sens/cudaDepthFilters-0.1a/blob/master/Pytoch_master_error) with exact commands how I've run it. Maybe I am doing something wrong.

**Comment by peterjc123** [comment] 2019-11-25 10:12
The first error in your log has been detected by CI, which is https://github.com/pytorch/pytorch/issues/30296. But we could not reproduce the second one. FYI, we use VS 2017 Update 4 on the CI server.

**Comment by peterjc123** [comment] 2019-11-25 10:16
Wait, there are so many errors in your cmake log during configuration.
```
CMake Error at cmake/Dependencies.cmake:401 (add_subdirectory):
  The source directory

    C:/Users/Andrej/Documents/pytorch/third_party/cpuinfo

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at cmake/Dependencies.cmake:406 (set_property):
  set_property could not find TARGET cpuinfo.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at C:/Users/Andrej/Documents/pytorch/cmake/GoogleTestPatch.cmake:20 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/Andrej/Documents/pytorch/cmake/../third_party/googletest/googletest/cmake/internal_utils.cmake


CMake Warning at cmake/Dependencies.cmake:468 (message):
  Patching failed for Google Test.  The build may fail.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at cmake/Dependencies.cmake:481 (add_subdirectory):
  The source directory

    C:/Users/Andrej/Documents/pytorch/third_party/googletest

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at cmake/Dependencies.cmake:491 (add_subdirectory):
  The source directory

    C:/Users/Andrej/Documents/pytorch/third_party/benchmark

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at C:/Users/Andrej/Documents/pytorch/cmake/GoogleTestPatch.cmake:16 (file):
  file failed to open for reading (No such file or directory):

    C:/Users/Andrej/Documents/pytorch/cmake/../third_party/googletest/googletest/cmake/internal_utils.cmake.bak


CMake Warning at cmake/Dependencies.cmake:508 (message):
  Reverting changes failed for Google Test.  The build may fail.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Warning at cmake/Dependencies.cmake:527 (message):
  FBGEMM is currently not supported on windows with MSVC.  Not compiling with
  FBGEMM.  Turn this warning off by USE_FBGEMM=OFF.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at cmake/Dependencies.cmake:682 (add_subdirectory):
  The source directory

    C:/Users/Andrej/Documents/pytorch/third_party/FP16

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


-- Using third party subdirectory Eigen.
-- Could NOT find pybind11 (missing: pybind11_DIR)
-- Could NOT find pybind11 (missing: pybind11_INCLUDE_DIR)
-- Using third_party/pybind11.
-- pybind11 include dirs: C:/Users/Andrej/Documents/pytorch/cmake/../third_party/pybind11/include
-- MKL_THREADING = OMP
-- MKL_THREADING = OMP
-- Adding OpenMP CXX_FLAGS: -openmp:experimental
-- No OpenMP library needs to be linked against
-- Found CUDA: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1 (found version "10.1")
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1/bin/nvcc.exe
-- Caffe2: CUDA toolkit directory: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.1
-- Caffe2: Header version is: 10.1
-- Found CUDNN: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudnn.lib
-- Found cuDNN: v7.6.5  (include: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/include, library: C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v10.0/lib/x64/cudnn.lib)
-- Autodetected CUDA architecture(s):  6.1
-- Added CUDA NVCC flags for: -gencode;arch=compute_61,code=sm_61
-- Could NOT find CUB (missing: CUB_INCLUDE_DIR)
CMake Warning at cmake/Dependencies.cmake:1105 (message):
  Metal is only used in ios builds.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at cmake/Dependencies.cmake:1158 (add_subdirectory):
  The source directory

    C:/Users/Andrej/Documents/pytorch/third_party/onnx

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at cmake/Dependencies.cmake:1159 (add_subdirectory):
  The source directory

    C:/Users/Andrej/Documents/pytorch/third_party/foxi

  does not contain a CMakeLists.txt file.
Call Stack (most recent call first):
  CMakeLists.txt:380 (include)


CMake Error at cmake/public/utils.cmake:44 (get_target_property):
  get_target_property() called with non-existent target "onnx".
Call Stack (most recent call first):
  cmake/Dependencies.cmake:1169 (caffe2_interface_library)
  CMakeLists.txt:380 (include)
```
Did you forget to do `git submodule sync && git submodule update --init --recursive` before build?

**Comment by Andrej-sens** [comment] 2019-11-25 10:35
I remember to running it. If I wouln't I couln't execute the build due to some packages. I've run the command again and it synch some packages but didn't donwload. 

Now I'm getting only:
`
CMake Warning at cmake/Dependencies.cmake:141 (message):
MKL could not be found.  Defaulting to Eigen
Call Stack (most recent call first):
CMakeLists.txt:380 (include)
`
`
CMake Warning at cmake/Dependencies.cmake:160 (message):
Preferred BLAS (MKL) cannot be found, now searching for a general BLAS library
Call Stack (most recent call first): CMakeLists.txt:380 (include)
`

`
CMake Warning at cmake/Dependencies.cmake:324 (message): Target platform "Windows" is not supported in QNNPACK.  Supported platforms are Android, iOS, Linux, and macOS.  Turn this warning off by USE_PYTORCH_QNNPACK=OFF. Call Stack (most recent call first):
CMakeLists.txt:380 (include)
`

`
CMake Warning at cmake/External/nnpack.cmake:21 (message): NNPACK not supported on MSVC yet.  Turn this warning off by USE_NNPACK=OFF.
Call Stack (most recent call first):
  cmake/Dependencies.cmake:367 (include)
  CMakeLists.txt:380 (include)
`

`
CMake Warning at cmake/Dependencies.cmake:377 (message):
Not compiling with NNPACK.  Suppress this warning with -DUSE_NNPACK=OFF
Call Stack (most recent call first):
CMakeLists.txt:380 (include)
`

I'll run it again.

**Comment by henry1987** [comment] 2020-06-21 22:22
Hi, there!
I am struggling on fighting with this same issue these days. Any suggestions will be appreciated!
[build_log_10.1.txt](https://github.com/pytorch/pytorch/files/4810366/build_log_10.1.txt)

**Comment by cristianPanaite** [comment] 2022-10-19 12:04
@henry1987 it is no longer necessary to use build or rebuild with the latest versions. 

You can use:
To install:  `python setup.py install`
To develop locally: `python setup.py develop`
To force cmake to re-generate native build files (off by default): `python setup.py develop --cmake`

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.

**Comment by cristianPanaite** [comment] 2022-10-19 12:05
Hello @Andrej-sens,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. I tried to replicate this issue, but on the latest versions I don't get any error.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.

**Closed** 2022-10-19 13:17 UTC
Labels: module: build, module: windows, triaged
