### ISSUE TITLE
Dynamo not handling a NamedTuple 

### ISSUE THREAD

**Issue by msaroufim** [pytorch/pytorch#107040] opened 2023-08-11 16:05 UTC
### 🐛 Describe the bug

Context: https://discuss.pytorch.org/t/struggling-to-get-pytorch-fast-enough-to-use-in-public-competition/186015

Tried to poke around the NamedTupleVariable https://gist.github.com/msaroufim/24c0da855b28c8acbea4ddf2d628e977 to get this fixed in dynamo but haven't managed to solve it yet. Opening this while i work on librispeech now instead 

## Repro

Setup instructions here https://github.com/mlcommons/algorithmic-efficiency

```
python3 datasets/dataset_setup.py \
  --data_dir=~/data \
  --ogbg
```

```
python submission_runner.py \
    --framework=pytorch \
    --workload=ogbg \
    --experiment_dir=/home/ubuntu/algorithmic-efficiency \
    --experiment_name=ogbg_pytorch \
    --submission_path=reference_algorithms/development_algorithms/ogbg/ogbg_pytorch/submission.py \
    --tuning_search_space=reference_algorithms/development_algorithms/ogbg/tuning_search_space.json
```

### Error logs

Full logs: https://gist.github.com/msaroufim/36e68408c6cb156cf8cb38baabd17bd3

Error message: `torch._dynamo.exc.InternalTorchDynamoError: GraphsTuple.__new__() missing 6 required positional arguments: 'edges', 'receivers', 'senders', 'globals', 'n_node', and 'n_edge'`

Here's what a `GraphsTuple` is: https://github.com/deepmind/jraph/blob/master/jraph/_src/graph.py#L26

### Versions

n/a

cc @ezyang @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @gchanan @Xia-Weiwen @ipiszy

**Comment by voznesenskym** [comment] 2023-11-14 20:13
@msaroufim - can you try to make a simpler repro here?

**Comment by ezyang** [comment] 2023-11-14 20:19
Actually, I don't think I even want a repro here, I just want a TORCH_LOGS=+dynamo trace. Looking over the backtrace, it looks like we're improperly wrapping a user defined list-like variable inside a ListVariable (or some other subclass in that hierarchy). It shouldn't be possible for `self.python_type()` to be not a well-known constructor like list/set/etc. So the +dynamo trace should tell us when things had gone wrong in the model and give us enough info to construct a reproducer by hand.

**Comment by laithsakka** [comment] 2024-02-28 18:28
I fixed a bug that looks related from the stack trace
https://github.com/pytorch/pytorch/pull/119435/files
```
File "/home/ubuntu/.conda/envs/perf/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 495, in <genexpr>
    proxy_args = tuple(arg.as_proxy() for arg in args)
 ```

but i wont know if this fix that with out  a repo

**Comment by anijain2305** [comment] 2024-02-28 18:40
Yes, I am convinced from the stack trace that https://github.com/pytorch/pytorch/pull/119435 should fix this issue. Closing this, but feel free to reopen if the original model fails.

**Closed by anijain2305** 2024-02-28 18:40 UTC
Labels: needs reproduction, module: performance, triaged, oncall: pt2, module: dynamo, mlperf, dynamo-must-fix
