### ISSUE TITLE
With dynamo, peak memory usage is higher for the Adam family

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#116046] opened 2023-12-18 18:47 UTC
### 🐛 Describe the bug

When running `PYTORCH_TEST_WITH_DYNAMO=1 test_peak_memory_foreach`, the peak memory usage is higher for the Adam family:
NAdam uses 7168 more bytes
Adamax uses 1024 more bytes
Adam and AdamW use 8192 more bytes

For reference, the parameter list in question is 10 elements of 512-byte tensors, with a total memory of 5120.

RAdam passes the test somehow.

### Error logs

```
(pytorch-3.10) [janeyx@devgpu023.odn1 ~/local/pytorch (0ad33dda|REBASE-i|detached HEAD)]$  PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_peak_memory_foreach_NAdam
/home/janeyx/.conda/envs/pytorch-3.10/lib/python3.10/site-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.0
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
sF
======================================================================
FAIL: test_peak_memory_foreach_NAdam_cuda_float32 (__main__.TestOptimRenewedCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_utils.py", line 2674, in wrapper
    method(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 416, in instantiated_test
    result = test(self, **param_kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_optimizers.py", line 169, in test_wrapper
    return test(*args, **kwargs)
  File "/data/users/janeyx/pytorch/torch/testing/_internal/common_device_type.py", line 1110, in only_fn
    return fn(slf, *args, **kwargs)
  File "/data/users/janeyx/pytorch/test/test_optim.py", line 197, in test_peak_memory_foreach
    self.assertLessEqual(mt_max_mem, st_max_mem + intermediate_size * nintermediates)
AssertionError: 51712 not less than or equal to 44544

To execute this test, run the following from the base repo dir:
    PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_peak_memory_foreach_NAdam_cuda_float32

This message can be suppressed by setting PYTORCH_PRINT_REPRO_ON_FAILURE=0

----------------------------------------------------------------------
Ran 2 tests in 14.157s

FAILED (failures=1, skipped=1)
```

### Minified repro

For Optim in [Adamax, NAdam, Adam, AdamW], run `PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py -k test_peak_memory_foreach_<Optim>_cuda`

### Versions

on main

cc @vincentqb @jbschlosser @albanD @crcrpar @mruberry @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @mlazos

**Comment by janeyx99** [comment] 2023-12-18 20:14
Moreover, it seems that peak memory is not deterministic with dynamo. When running this test for Rprop by itself, the test passes. However, when run as a part of the entire test file (`PYTORCH_TEST_WITH_DYNAMO=1 python test/test_optim.py`), the test fails. This may be expected: maybe this has to do with the dynamo cache and I shouldn't test memory for torch.compile(), or maybe I should clear the cache within the test.

**Comment by anijain2305** [comment] 2024-02-01 06:48
Maybe try adding `torch._dynamo.reset()` between testing different optimizers?

**Comment by janeyx99** [comment] 2024-02-01 14:24
@anijain2305 I think that should already be True since dynamo tests run reset before and after by default, and each test is separated by optimizers already.

**Comment by mlazos** [comment] 2024-04-20 00:13
Figured this out - basically we use the eager backend, and even though kwargs doesn't contain capturable, we take the capturable path since we're compiling. As a result there is worse memory usage (due to capturable being True)

**Comment by ezyang** [comment] 2024-04-21 10:56
Hang on, why aren't deletions captured in the graph? Eager backend still generates FX graphs, which still have dels when variables go out of scope.

**Comment by mlazos** [comment] 2024-04-21 12:27
Are explicit deletions from the python code captured in the graph? We basically del them early in the optimizer to improve peak mem (the intermediates are still in scope at that time) and I don't think FX is doing that.

**Comment by ezyang** [comment] 2024-04-21 12:50
Well, are you del'ing locals or things stored on the optimizer? The locals get del'ed immediately after last use, even if they stayed live longer in original code

**Comment by mlazos** [comment] 2024-04-21 13:06
Hmm, okay let me try setting capturable properly in the test, maybe that's the only culprit here then. The eager graph should probably be as memory efficient as eager if they're getting del'ed after last use.

**Comment by mlazos** [comment] 2024-06-05 23:57
I am going to close this in favor of https://github.com/pytorch/pytorch/issues/125511
which is the root cause.

**Closed by mlazos** 2024-06-05 23:57 UTC
Labels: module: optimizer, module: tests, triaged, oncall: pt2, module: dynamo, module: pt2 optimizer
