### ISSUE TITLE
`torch.linalg.inv` outputs wrong results for singular matrix on CUDA

### ISSUE THREAD

**Issue by fuzzyswan** [pytorch/pytorch#86305] opened 2022-10-05 19:12 UTC
### 🐛 Describe the bug

Example code:
```
import torch
input = torch.tensor([[1.0]*2, [3]*2], requires_grad=True) 
output = torch.linalg.inv(torch.matmul(input, input))  # GPU passes silently, CPU would throw an error matrix cannot be inverted 
```
Since the input matrix is not invertable, CPU run throws `torch._C._LinAlgError: linalg.inv: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular`
However on cuda it produces wrong results:
Code:
```
import torch
input = torch.tensor([[1.0]*2, [3]*2], requires_grad=True).cuda() 
output = torch.linalg.inv(torch.matmul(input, input))
print(output)
```
Outputs:
```
tensor([[ 8388608.0000, -2796202.7500],
        [-8388608.0000,  2796202.7500]], device='cuda:0',
       grad_fn=<LinalgInvExBackward0>)
```

An error should be thrown because the matrix is not invertable.

### Versions

pytorch 1.13.0

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by Aidyn-A** [comment] 2022-10-06 19:13
Hi @fuzzyswan, 
I could not reproduce the issue. Could you please provide more information about device and library versions you are using (CUDA, cuBLAS, cuSOLVER and MAGMA)? 

```Python
import torch
torch.backends.cuda.preferred_linalg_library(backend="cusolver")  # both magma and cusolver backends fail as expected
input = torch.tensor([[1.0]*2, [3]*2], requires_grad=True).cuda()
output = torch.linalg.inv(torch.matmul(input, input))
print(output)
```
And could you please test what backed is failing?

@IvanYashchuk have you ever seen something like it?

**Comment by lezcano** [comment] 2022-10-06 20:00
This is expected and it has been reported before. See https://github.com/pytorch/pytorch/issues/77954#issuecomment-1134341945 and the answers there.
We should create a short linalg doc with common pitfalls that people keep rediscovering.

**Comment by lezcano** [comment] 2022-10-06 20:03
FWIW, the code throws in my config as well. Again, this is backend-dependent, but more generally, we cannot assure bit-wise comparable results across backends in linalg functions. As such, these issues will always exist and there's nothing we can do about it.

**Comment by lezcano** [comment] 2023-01-15 15:28
Closing as expected. For further info see https://pytorch.org/docs/master/notes/numerical_accuracy.html#extremal-values-in-linalg

**Closed by lezcano** 2023-01-15 15:28 UTC
Labels: module: cuda, triaged, module: linear algebra
