### ISSUE TITLE
Support CUDA 11.3

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#56721] opened 2021-04-22 19:35 UTC
This issue will track the current progress on adding CUDA 11.3 support; see https://github.com/pytorch/pytorch/issues/50232#issuecomment-825031470.

- [x] Installing to conda-builder and libtorch containers (https://github.com/pytorch/builder/pull/719 and https://github.com/pytorch/builder/pull/724)
     - [x] Push pytorch/conda-builder
     - [x] Push the libtorch image
- [x] Add setup to manywheels (https://github.com/pytorch/builder/pull/720 and some nice refactoring https://github.com/pytorch/builder/pull/722)
     - [x] Push pytorch/manylinux-builder
- [x] Update MAGMA (https://github.com/pytorch/builder/pull/721)
     - [x] Push magma-cuda113 to conda
     - [x] Add magma for windows into our S3 (Will be automated in future by https://github.com/pytorch/builder/pull/751)
- [x] Add Windows builder for 11.3 (https://github.com/pytorch/builder/pull/728)
     ~- [ ] Update Windows driver~ (unneeded this round as the current driver is sufficient)
     - [x] Add fixes that had to come up (Part of https://github.com/pytorch/builder/pull/751 and https://github.com/pytorch/builder/pull/755)
- [x] Replace 11.2 with 11.3 into CI (**Note:** we disabled a test for 11.3 https://github.com/pytorch/pytorch/issues/57482)
     - [x] Windows (https://github.com/pytorch/pytorch/pull/57223)
     - [x] Linux + add MAGMA to CI conda (https://github.com/pytorch/pytorch/pull/57222)
- [x] Include CUDA 11.3 into our nightly matrix (https://github.com/pytorch/pytorch/pull/58877)
     - [x] Update conda `build_pytorch.sh` script and add conda binaries (https://github.com/pytorch/pytorch/pull/61873, https://github.com/pytorch/builder/pull/806, https://github.com/pytorch/builder/pull/807)
     - [x] Tackle any bugs that come up (thanks @malfet for https://github.com/pytorch/pytorch/pull/58437, https://github.com/pytorch/pytorch/pull/58459, and https://github.com/pytorch/pytorch/pull/58287 that unblocked 11.3 binaries. Parallelized nvcc in https://github.com/pytorch/builder/pull/755)
     - [x] Windows
     - [x] Linux 
- [x] Add 11.3 to torchvision CI. (thanks @malfet for https://github.com/pytorch/vision/pull/4248)

cc @malfet @seemethere @walterddr @ezyang @pytorch/pytorch-dev-infra @ngimel

**Comment by Turakar** [comment] 2021-05-18 11:04
pytorch/builder#728 seems to be merged, but this is issue is not updated. Could you give a quick update on the status of CUDA 11.3 support?

**Comment by janeyx99** [comment] 2021-05-18 15:56
Yes, I've updated the above according to their completion--currently, we're working on debugging some of the binaries.

**Comment by emergix** [comment] 2021-06-04 09:05
Just to be sure: it means that you skip the cuda 11.2 ?

**Comment by janeyx99** [comment] 2021-06-04 15:55
@emergix Yes, currently CUDA 11.2 is "skipped" in favor for 11.3.

**Comment by ktaming** [comment] 2021-06-10 10:15
Hi there,

Not mean to be urging, but I'm wondering when do you expect PyTorch for CUDA 11.3 will be released? Thanks a lot for your working really hard during the pandemic!

Thanks,

**Comment by janeyx99** [comment] 2021-06-10 16:36
> ... I'm wondering when do you expect PyTorch for CUDA 11.3 will be released? 

Hi! The last piece missing would be the conda packages, which currently aren't available as there is no suitable `cudatoolkit11.3` yet on conda. CUDA 11.3 is set to be released with PyTorch 1.10, but you can test out the `pip` wheels here: https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html and try `libtorch` binaries by downloading them here: https://download.pytorch.org/libtorch/nightly/cu113/libtorch-shared-with-deps-latest.zip

**Comment by MotorCityCobra** [comment] 2021-06-13 15:16
> > ... I'm wondering when do you expect PyTorch for CUDA 11.3 will be released?
> 
> Hi! The last piece missing would be the conda packages, which currently aren't available as there is no suitable `cudatoolkit11.3` yet on conda. CUDA 11.3 is set to be released with PyTorch 1.10, but you can test out the `pip` wheels here: https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html and try `libtorch` binaries by downloading them here: https://download.pytorch.org/libtorch/nightly/cu113/libtorch-shared-with-deps-latest.zip

How do I use this to install pytorch for 11.3?

**Comment by realiti4** [comment] 2021-06-13 16:31
> > > ... I'm wondering when do you expect PyTorch for CUDA 11.3 will be released?
> > 
> > 
> > Hi! The last piece missing would be the conda packages, which currently aren't available as there is no suitable `cudatoolkit11.3` yet on conda. CUDA 11.3 is set to be released with PyTorch 1.10, but you can test out the `pip` wheels here: https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html and try `libtorch` binaries by downloading them here: https://download.pytorch.org/libtorch/nightly/cu113/libtorch-shared-with-deps-latest.zip
> 
> How do I use this to install pytorch for 11.3?

    pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html

**Comment by MotorCityCobra** [comment] 2021-06-13 22:42
> ```
> pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
> ```

Hmmm. I must need to be spoon fed because I can only get a CPU after this install. I can not get a GPU to work after using this line to install.
I'm using Windows 10, CUDA 11.3, and torch installed with the line above.

**Comment by tkgmomosheep** [comment] 2021-06-14 16:54
> > ```
> > pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
> > ```
> 
> Hmmm. I must need to be spoon fed because I can only get a CPU after this install. I can not get a GPU to work after using this line to install.
> I'm using Windows 10, CUDA 11.3, and torch installed with the line above.

I ran into the same issue. I noticed that there is no torchvision for windows, maybe that's the reason why GPU compute won't work.

**Comment by MotorCityCobra** [comment] 2021-06-14 18:59
> I ran into the same issue. I noticed that there is no torchvision for windows, maybe that's the reason why GPU compute won't work.

Funny you should mention. I got it with torch installed only. I also had to use `pip3` for some reason.

**Comment by aliencaocao** [comment] 2021-06-15 14:55
Installed using pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
and cuda.is_available returns false. Cuda latest version (11.3 update 1) together with the included driver 465.89 is installed. nvidia-smi works fine, and TensorFlow is able to detect and use gpu normally. Tried uninstall and reinstall many times, same behaviour.

**Comment by akiskyo** [comment] 2021-06-23 10:49
the problem is that if you look at https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html there's no torchvision version either for linux or windows, and the current latest torchvision 0.10.0 is not compatible with torch nightly cu113.

I tried to force the installation of torch cu113 together with torchvision 0.10.0 using -no-dependencies and received this rather clear error from yolo:

RuntimeError: Couldn't load custom C++ ops. This can happen if your PyTorch and torchvision versions are incompatible, or if you had errors while compiling torchvision from source. For further information on the compatible versions, check https://github.com/pytorch/vision#installation for the compatibility matrix. Please check your PyTorch version with torch.__version__ and your torchvision version with torchvision.__version__ and verify if they are compatible, and if not please reinstall torchvision so that it matches your PyTorch install.

**Comment by TobiFisch** [comment] 2021-06-27 17:22
@janeyx99 and @realiti4 I combined your comments as well on Ubuntu20 with CUDA 11.3.

> > > > ... I'm wondering when do you expect PyTorch for CUDA 11.3 will be released?
> > > 
> > > 
> > > Hi! The last piece missing would be the conda packages, which currently aren't available as there is no suitable `cudatoolkit11.3` yet on conda. CUDA 11.3 is set to be released with PyTorch 1.10, but you can test out the `pip` wheels here: https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html and try `libtorch` binaries by downloading them here: https://download.pytorch.org/libtorch/nightly/cu113/libtorch-shared-with-deps-latest.zip
> > 
> > 
> > How do I use this to install pytorch for 11.3?
> 
> ```
> pip install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html
> ```


This command yields:
```
ERROR: torchvision 0.10.0 has requirement torch==1.9.0, but you'll have torch 1.10.0.dev20210627+cu113 which is incompatible.
```
but contradicts itself directly afterwards:
```
Successfully installed numpy-1.21.0 pillow-8.2.0 torch-1.10.0.dev20210627+cu113 torchvision-0.10.0 typing-extensions-3.10.0.0
```
In the end, the `torchvision.ops.nms` fails to load when running yolov5 like @akiskyo already observed.

Could the be because the nightly wheels contain `torchvision` only for `macosx`? Searching https://download.pytorch.org/whl/nightly/cu113/torch_nightly.html for `torchvision` only yields `macosx` wheels, apparently in versions `0.10` and `0.11`.

**Comment by janeyx99** [comment] 2021-06-29 23:47
Ah sorry for the confusion. Currently, there's no support for `torchvision' with CUDA 11.3 yet. You'd have to try to build torchvision for CUDA 11.3 yourself, though there's no guarantee it will work.

**Comment by ktaming** [comment] 2021-06-30 02:59
> Ah sorry for the confusion. Currently, there's no support for `torchvision' with CUDA 11.3 yet. You'd have to try to build torchvision for CUDA 11.3 yourself, though there's no guarantee it will work.

Thanks for your clarification!

Just curious, I'm using a x64 computer with Ubuntu 20.04 and two NVIDIA GeForce 3090 graphic cards, and I successfully installed the whl file as well as the torchvision on it. Most things works fine, but there are two things drives me crazy:

1. The Inference/perdiction is OK, but when I try to do training, it warns me of: "GeForce RTX 3090 with CUDA capability sm_86 is not compatible with the current PyTorch installation." and refuse to start...
2. When I type:
>>> import torch
>>> print(torch.__version__)
It returns:
**1.8.1+cu102**

I though it should return **1.9.0+cu113** ...? What could be wrong?


Thanks for your time and devotion!

Regards,
L

**Comment by beniz** [comment] 2021-06-30 07:07
> Ah sorry for the confusion. Currently, there's no support for `torchvision' with CUDA 11.3 yet. You'd have to try to build torchvision for CUDA 11.3 yourself, though there's no guarantee it will work.

It does, at least from C++ with libtorch built against cu113.

**Comment by akiskyo** [comment] 2021-06-30 08:28
but then, why is there an unknown hero submitting torchvision nightly cuda 11.3 for only macosx in the repo?

**Comment by batrlatom** [comment] 2021-06-30 13:53
You can try docker version directly from nvidia :  
```
docker pull nvcr.io/nvidia/pytorch:21.06-py3
```

**Comment by malfet** [comment] 2021-06-30 18:57
@ktaming CUDA guarantees backward compatibility, so you should be able to install PyTorch and TorchVision build against CUDA-11.1 and it will work on the host that runs CUDA-11.3

**Comment by johnnync13** [comment] 2021-06-30 20:21
DirectStorage?
https://developer.nvidia.com/blog/discover-new-cuda-11-4-features/

**Comment by TobiFisch** [comment] 2021-07-01 17:13
@malfet That works perfectly indeed! Thanks for the hint :)

**Comment by akiskyo** [comment] 2021-07-03 10:52
@malfet would you explain more your approach? if I have CUDA 11.3 installed and just install torch and torchvision for cuda 111, they (and yolo) will complain that I have no cuda installed. how did you manage?

**Comment by ngimel** [comment] 2021-07-03 19:14
@akiskyo When you install pytorch binaries, they  don't need any system cuda toolkit install (only driver). How do you install pytorch, what is the error you are getting, and can you provide your environment info collected via collect_env.py script?

**Closed** 2021-08-06 22:01 UTC
Labels: module: build, module: cuda, module: ci, triaged
