### ISSUE TITLE
Bug in MPS permute for uint8

### ISSUE THREAD

**Issue by carsonswope** [pytorch/pytorch#80285] opened 2022-06-25 15:54 UTC
### 🐛 Describe the bug

Permute does not work in MPS with uint8 values:

Script:
```python
import torch

t = torch.uint8

t0_cpu = torch.arange(4*3, dtype=t).reshape((4, 3))
t0_mps = t0_cpu.to(torch.device('mps'))

t1_cpu = t0_cpu.permute((1, 0))
t1_mps = t0_mps.permute((1, 0))

print('CPU')
print(' in:')
print(t0_cpu)
print(' out:')
print(t1_cpu)

print('MPS')
print(' in:')
print(t0_mps)
print(' out:')
print(t1_mps)
```

Output:
```
CPU
 in:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], dtype=torch.uint8)
 out:
tensor([[ 0,  3,  6,  9],
        [ 1,  4,  7, 10],
        [ 2,  5,  8, 11]], dtype=torch.uint8)
MPS
 in:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]], device='mps:0', dtype=torch.uint8)
 out:
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], device='mps:0', dtype=torch.uint8)
```

This seems to first appear in nightly release `20220623`. It was not present in `20220622`. It appears to only affect the uint8 datatype, but I only tested a few other datatypes (float32, int64, int32).

### Versions

```
PyTorch version: 1.13.0.dev20220625
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.23.2
Libc version: N/A

Python version: 3.9.12 (main, Jun  1 2022, 06:34:44)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-12.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.3
[pip3] torch==1.13.0.dev20220625
[conda] numpy                     1.22.3           py39h25ab29e_0
[conda] numpy-base                1.22.3           py39h974a1f5_0
[conda] torch                     1.13.0.dev20220625          pypi_0    pypi
```

cc @kulinseth @albanD

**Comment by qqaatw** [comment] 2022-06-30 11:54
I can reproduce this issue.

**Comment by kulinseth** [comment] 2022-06-30 18:30
@qqaatw , are you planning to take a look at fixing this issue ? Please assign it to yourself if you are.

**Comment by qqaatw** [comment] 2022-07-01 14:52
@kulinseth I would try to fix this. As not a collaborator, I'm not able to assign myself. 

FYI, this issue was caused by #80049, reverting that PR solves it.

**Comment by DenisVieriu97** [comment] 2022-08-06 00:46
Similar as https://github.com/pytorch/pytorch/issues/82305

**Comment by malfet** [comment] 2022-08-18 23:59
> FYI, this issue was caused by #80049, reverting that PR solves it.
Yeah, but this is the right MPS type for uint8

By the way, this seems to work correctly for me against 20220818  nightly on x86_64 Mac.

**Comment by kulinseth** [comment] 2022-08-22 19:13
This seems to work correctly on latest torch nightly.

**Closed by kulinseth** 2022-08-22 19:13 UTC
Labels: triaged, module: regression, module: mps
