### ISSUE TITLE
Linear layer with local connections

### ISSUE THREAD

**Issue by arbishakram** [pytorch/pytorch#44617] opened 2020-09-13 18:30 UTC
I want to implement linear regression in Pytorch with sparse connections. To build such a network I cannot use nn.Linear because it is a densely connected layer. I have first tried to make a binary matrix with 0 and 1 to indicate the presence and absence of connections. But it won't work in my case because it is not computationally efficient. I am looking for a sparse weight matrix or sparse linear layer type solutions. I would be really grateful if someone would help me in this regard. I have attached a screenshot also to explain what I'm trying to do. 
![image](https://user-images.githubusercontent.com/58566628/93038137-9dea7080-f65d-11ea-8672-0861457df928.png)

**Comment by VitalyFedyunin** [comment] 2020-09-13 19:28
Posted URL is broken. Also if you already have discussion on the forum, it makes no sense to duplicate it here.

**Comment by arbishakram** [comment] 2020-09-14 02:42
I have attached the image in the above post. Please look again now. 
I didn't get any reply so far from anywhere. Please help me to fix this problem.

**Comment by albanD** [comment] 2020-09-14 16:57
Closing as duplicate of https://discuss.pytorch.org/t/linear-layer-with-local-connections/96201
No need to cross post things, we look at both and you should only use the forum to ask questions as github is only for bug report and feature requests.

**Closed by albanD** 2020-09-14 16:57 UTC
