### ISSUE TITLE
nondeterminism in torch.compile + custom op

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#127995] opened 2024-06-05 03:07 UTC
Doesn't look good. The following sometimes succeeds and sometimes fails for me:
```py
import torch
import numpy as np # E: module level import not at top of file # E: at least two spaces before inlin

lib = torch.library.Library("mylib", "FRAGMENT") 
lib.define("numpy_sin(Tensor input, Tensor(a!) output) -> ()")

def numpy_sin(input: torch.Tensor, output: torch.Tensor) -> None:
    assert input.device == output.device
    assert input.device.type == "cpu"
    input_np = input.numpy()
    output_np = output.numpy()
    np.sin(input_np, out=output_np)

lib.impl("numpy_sin", numpy_sin, "CPU")

numpy_sin = torch.ops.mylib.numpy_sin

@torch.compile(fullgraph=True)
def f(x):
    out = torch.empty(3)
    numpy_sin(x, out)
    return out

x = torch.randn(3)
y = f(x)
print(torch.__version__)
assert torch.allclose(y, x.sin())
```

cc @ezyang @gchanan @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @ColinPeppler @amjames @desertfire

**Comment by zou3519** [comment] 2024-06-05 03:30
Looks like a regression from 2.3.0. Also appears to only repro with backend="inductor" for me (though it is non-deterministic)

**Comment by zou3519** [comment] 2024-06-05 21:00
This is possibly a mutation issue (cc @Chillee). If I could reproduce this more reliably then I would bisect

**Comment by Chillee** [comment] 2024-06-05 21:28
@zou3519 will take a look

**Comment by bdhirsh** [comment] 2024-06-05 21:37
a few datapoints:

(1) it fails on cpu, but not cuda

(2) the generated code looks like this:
```
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (3, ), (1, ))
    buf0 = empty_strided_cpu((3, ), (1, ), torch.float32)
    # Source Nodes: [], Original ATen: []
    buf1 = torch.ops.mylib.numpy_sin.default(arg0_1, buf0)
    del arg0_1
    cpp_fused_empty_0(buf0)
    return (buf0, )
```

Where the "bug" appears to be that we are running a `cpp_fused_empty_0` that fills the tensor with zeros, **after** the custom op has run.

(3) I diff'd the GraphLowering when running the repro on cpu vs cuda, and one difference I see:

cpu:
```
[StorageBox(
  ComputedBuffer(name='buf0', layout=FixedLayout('cpu', torch.float32, size=[3], stride=[1]), data=Pointwise(
    'cpu',
    torch.float32,
    def inner_fn(index):
        i0 = index
        tmp0 = ops.constant(0.0, torch.float32)
        return tmp0
    ,
    ranges=[3],
    origin_node=full_default,
    origins={full_default}
  ))
)]
```

cuda:
```
[StorageBox(
  ComputedBuffer(name='buf0', layout=FixedLayout('cuda', torch.float32, size=[3], stride=[1]), data=Pointwise(
    'cuda',
    torch.float32,
    def inner_fn(index):
        i0 = index
        tmp0 = ops.constant(0, torch.float32)
        return tmp0
    ,
    ranges=[0],
    origin_node=empty,
    origins={empty}
  ))
)]
```

One difference is that the `empty_strided` lowering desugars into an `aten.full(0)` for cpu but not cuda. I'm also not sure why the `full()` lowering gets scheduled to run **after** the custom op.

**Comment by zou3519** [comment] 2024-06-05 23:45
I can reliably repro this on my mac. So far it looksl ike something between 4/7 to 5/1 caused it. So it's likely not @Chillee's recent Inductor mutation changes

**Comment by zou3519** [comment] 2024-06-05 23:57
Bisection says a commit between 04/08 and 04/10 caused the regression.

https://github.com/pytorch/pytorch/pull/122945 looks suspicious so far

**Comment by leslie-fang-intel** [comment] 2024-06-06 01:01
Testing with commit: 22712ba5c5cf0e06a74bc9e635273f9b4725e7ad
I didn't reproduce this issue on local system. Probably as @zou3519 mentions in summary

> it's `nondeterminism` as sometimes succeeds and sometimes fails.

The generated code is without the last `cpp_fused_empty_0(buf0)` on my local system. I guess I need to find a way to reproduce this steadily.

```
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (3, ), (1, ))
    buf0 = empty_strided_cpu((3, ), (1, ), torch.float32)
    # Source Nodes: [], Original ATen: []
    buf1 = torch.ops.mylib.numpy_sin.default(arg0_1, buf0)
    del arg0_1
    return (buf0, )
```

**Comment by leslie-fang-intel** [comment] 2024-06-06 02:28
I can reproduce this random failure on CPU now.

Totally 3 nodes,

- When this case passes on CPU
```
---- in realize self.data.name is: buf0
ComputedBuffer(name='buf0', layout=FlexibleLayout('cpu', torch.float32, size=[3], stride=[1]), data=Pointwise(
  'cpu',
  torch.float32,
  def inner_fn(index):
      i0 = index
      tmp0 = ops.constant(0, torch.float32)
      return tmp0
  ,
  ranges=[3],
  origin_node=None,
  origins={empty}
))
---- codegen node node is: NopKernelSchedulerNode(name='buf0')-----
---- codegen node node is: ExternKernelSchedulerNode(name='buf1')-----
---- codegen node node is: NopKernelSchedulerNode(name='buf2')-----
2.4.0.dev20240603+cpu
```

Buf0's origins is `empty` and generate `NopKernelSchedulerNode`

- When this case failed on CPU
```
---- in realize self.data.name is: buf0
ComputedBuffer(name='buf0', layout=FlexibleLayout('cpu', torch.float32, size=[3], stride=[1]), data=Pointwise(
  'cpu',
  torch.float32,
  def inner_fn(index):
      i0 = index
      tmp0 = ops.constant(0.0, torch.float32)
      return tmp0
  ,
  ranges=[3],
  origin_node=None,
  origins={full_default}
))
---- codegen node node is: SchedulerNode(name='buf0')-----
---- codegen node node is: ExternKernelSchedulerNode(name='buf1')-----
---- codegen node node is: NopKernelSchedulerNode(name='buf2')-----
2.4.0.dev20240603+cpu
Traceback (most recent call last):
  File "/ws1/zailiw/cases/pth_git_issues/127995.py", line 27, in <module>
    assert torch.allclose(y, x.sin())
AssertionError
```

Buf0's origins is `full_default` and generate `SchedulerNode`

**Comment by zou3519** [comment] 2024-06-06 06:53
This bisected to #122347 (cc @angelayi) but since it is non-deterministic that might not be right; I don't think that PR is related

**Comment by leslie-fang-intel** [comment] 2024-06-07 23:35
> @leslie-fang-intel any updates from your side? This seems like a regression, so we should really fix it for PyTorch 2.4. But I'm not very familiar with Inductor internals

Sure, I will further investigate the behavior with Python 2.3.

**Comment by Chillee** [comment] 2024-06-08 00:12
cc: @eellison

**Comment by leslie-fang-intel** [comment] 2024-06-08 00:17
It looks like https://github.com/pytorch/pytorch/pull/122347 is the real cause which causes the difference between PyTorch 2.4 and PyTorch 2.3.

Some finding from this issue

- Issue 1: the `torch.ops.aten.empty.memory_format` has been replaced to `full` as described in https://github.com/pytorch/pytorch/issues/127995#issuecomment-2151303109

- Issue 2: with PyTorch 2.3, even we replace `torch.ops.aten.empty.memory_format`  to `full`, it can still pass the testing. Here is the generated code in PyTorch 2.3 and PyTorch 2.4
PyTorch 2.3
```
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (3, ), (1, ))
    buf0 = empty_strided_cpu((3, ), (1, ), torch.float32)
    cpp_fused_empty_0(buf0)
    # Source Nodes: [], Original ATen: []
    buf1 = torch.ops.mylib.numpy_sin.default(arg0_1, buf0)
    del arg0_1
    return (buf0, )
```

PyTorch 2.4:
```
def call(args):
    arg0_1, = args
    args.clear()
    assert_size_stride(arg0_1, (3, ), (1, ))
    buf0 = empty_strided_cpu((3, ), (1, ), torch.float32)
    # Source Nodes: [], Original ATen: []
    buf1 = torch.ops.mylib.numpy_sin.default(arg0_1, buf0)
    del arg0_1
    cpp_fused_empty_0(buf0)
    return (buf0, )
```

The cause seems that `the high-order op` of external scheduler node return none device, and the buf0 didn't flush before we codegen in `high-order op` https://github.com/pytorch/pytorch/blob/ef2b5ed500cba0b8b2bf04e6006a0d64c910f440/torch/_inductor/scheduler.py#L2701-L2709

**Comment by leslie-fang-intel** [comment] 2024-06-15 01:32
- https://github.com/pytorch/pytorch/pull/128275 landed to fix the regression issue.
- As for the first bullet mentioned in https://github.com/pytorch/pytorch/issues/127995#issuecomment-2155718068

  > Issue 1: the torch.ops.aten.empty.memory_format has been replaced to full (which is nondeterminism)
  
  Hi @eellison, what do you think about whether `UniformValueConstantFolder` replaces `torch.empty` to `torch.full(0)` when `torch.empty` happens to allocate a block of memory with all zeros? If it doesn't make sense, should we add `torch.empty` as `is_impure` in `ConstantFolder` to prevent this behavior explicitly?

**Closed** 2024-06-18 18:41 UTC
Labels: high priority, triaged, oncall: pt2, module: inductor, oncall: cpu inductor, module: reinplacing

**Comment by atalman** [comment] 2024-07-09 15:57
confirmed works on 2.4.0 final rc
