### ISSUE TITLE
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED when batch_size is larger than 1024

### ISSUE THREAD

**Issue by chenyuntc** [pytorch/pytorch#1059] opened 2017-03-22 12:12 UTC
when the batch size is 1024, my model work fine, but when I change it to 1025, it throw error 
```python
RuntimeError: CUDNN_STATUS_NOT_SUPPORTED
```
this is how I load data:
```python
val_dataloader=t.utils.data.DataLoader(val_dataset,1025,True,num_workers=8,\
        collate_fn=my_collate)
```
the full trace is here:
```python
<ipython-input-4-91b240474ca9> in forward(self, input)
     21         self.model.add_module('conv5',nn.Conv2d(opt.ndf*8,1,4,1,0,bias=False))
     22     def forward(self,input):
---> 23         return self.model(input)
     24         gpuids=None
     25         if self.ngpu:

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    208 
    209     def __call__(self, *input, **kwargs):
--> 210         result = self.forward(*input, **kwargs)
    211         for hook in self._forward_hooks.values():
    212             hook_result = hook(self, input, result)

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/container.pyc in forward(self, input)
     61     def forward(self, input):
     62         for module in self._modules.values():
---> 63             input = module(input)
     64         return input

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.pyc in __call__(self, *input, **kwargs)
    208 
    209     def __call__(self, *input, **kwargs):
--> 210         result = self.forward(*input, **kwargs)
    211         for hook in self._forward_hooks.values():
    212             hook_result = hook(self, input, result)

/usr/local/lib/python2.7/dist-packages/torch/nn/modules/batchnorm.pyc in forward(self, input)
     41         return F.batch_norm(
     42             input, self.running_mean, self.running_var, self.weight, self.bias,
---> 43             self.training, self.momentum, self.eps)
     44 
     45     def __repr__(self):

/usr/local/lib/python2.7/dist-packages/torch/nn/functional.pyc in batch_norm(input, running_mean, running_var, weight, bias, training, momentum, eps)
    483     state = _functions.batchnorm.BatchNorm(
    484         running_mean, running_var, training, momentum, eps)
--> 485     return weight and state(input, weight, bias) or state(input)
    486 
    487 

/usr/local/lib/python2.7/dist-packages/torch/nn/_functions/batchnorm.pyc in forward(self, input, weight, bias)
     34                 input, output, weight, bias,
     35                 self.running_mean, self.running_var, self._save_mean,
---> 36                 self._save_std, self.training, self.momentum, self.eps)
     37         else:
     38             backend = type2backend[type(input)]

RuntimeError: CUDNN_STATUS_NOT_SUPPORTED

```

**Comment by apaszke** [comment] 2017-03-22 12:18
Duplicate of #1004. This will be fixed in the next binary release.

**Closed by apaszke** 2017-03-22 12:18 UTC
