### ISSUE TITLE
index_put_ has unreasonable checks

### ISSUE THREAD

**Issue by harry67yqh** [pytorch/pytorch#11856] opened 2018-09-19 08:51 UTC
## Issue description

`index_put_ function(indices, value)` in `torch.Tensor` has a check that size of `indices` must be less than or equal to the number of dimensions of `self`, which is **not reasonable**.
I checked the source code and found that 
```
  AT_CHECK(indices.size() <= (size_t)self.dim(),
           "too many indices for tensor of dimension ", self.dim(), " (got ", indices.size(), ")");
```
in
```
Tensor index_put(const Tensor & self, TensorList indices, const Tensor & value) {
  AT_CHECK(indices.size() <= (size_t)self.dim(),
           "too many indices for tensor of dimension ", self.dim(), " (got ", indices.size(), ")");

  Tensor src, linearIndex, expandedValue;
  std::tie(src, linearIndex) = makeLinearIndex(self, indices);
  std::tie(expandedValue) = expand_inplace(linearIndex, value);
  Tensor dst = src.clone();
  return dst.put_(linearIndex, expandedValue);
}
should be the root of this problem.
```
## Code example
```
target = torch.zeros([5,3])
indices = torch.LongTensor([[0,1], [1, 2], [2, 2], [3, 0], [4, 1]])
value = torch.ones(indices.shape[0])
target.index_put_(tuple(indices), value)
```
The **expected result** should be that target became
```
tensor([[ 0.,  1.,  0.],
        [ 0.,  0.,  1.],
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0.,  1.,  0.]])
```
while what **really happened** was an error was raised
```
RuntimeError: too many indices for tensor of dimension 2 (got 5)
```
## System Info
I guess that system info is out of concern in this issue.

**Comment by fmassa** [comment] 2018-09-19 11:46
You are not passing the `indices` in the right format. `index_put_` expect the index tensor to be the transpose of what you passed.
So this works

```python
target = torch.zeros([5,3])
indices = torch.LongTensor([[0,1], [1, 2], [2, 2], [3, 0], [4, 1]])
value = torch.ones(indices.shape[0])
target.index_put_(tuple(indices.t()), value)
```

Also, it is generally better to use advanced indexing in such cases, as it's more clear what it is doing
```python
target[idx1, idx2] = 1
```

Closing as not a bug.

**Closed by fmassa** 2018-09-19 11:46 UTC
