### ISSUE TITLE
AttributeError: 'profile' object has no attribute 'start'

### ISSUE THREAD

**Issue by prakharsdev** [pytorch/pytorch#84409] opened 2022-09-01 09:59 UTC
### 📚 The doc issue
Document link: [Profiler](https://pytorch.org/tutorials/intermediate/tensorboard_profiler_tutorial.html#run-the-profiler)
When I tried to add a profiler to detect performance bottlenecks of my model I got this error:

**AttributeError: 'profile' object has no attribute 'start'**

`print('Train:')
            
          prof = torch.profiler.profile(
                  schedule=torch.profiler.schedule(wait=1, warmup=1, active=3, repeat=2),
                  on_trace_ready=torch.profiler.tensorboard_trace_handler('./record'),
                  record_shapes=True,
                  with_stack=True)
        
          prof.start()  
            
          for i_batch, sample in enumerate(dataloader):
            image, mask = sample['image'], sample['label'] 
            if i_batch >= (1 + 1 + 3) * 2:
                break
            solver.set_input(image, mask)
            train_loss = solver.optimize()
            train_ep_loss += train_loss
            prof.i_batch()
            
          prof.stop()`

cc @svekars @holly1238 @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb

**Comment by spzala** [comment] 2023-09-10 01:52
I couldn't reproduce error, and I see the start method - https://github.com/pytorch/pytorch/blob/main/torch/profiler/profiler.py#L105 The issue is few months old and perhaps it's fixed now. We may want to close it. Thanks! cc @ezyang

**Closed** 2023-09-11 03:58 UTC
Labels: module: docs, oncall: profiler
