### ISSUE TITLE
ccache breaks when building nccl

### ISSUE THREAD

**Issue by anderspapitto** [pytorch/pytorch#13362] opened 2018-10-31 01:58 UTC
see https://github.com/pytorch/pytorch/pull/13340#issuecomment-434524046 for a discussion.

When this is fixed, be sure to remove any workarounds

cc @malfet @seemethere @walterddr

**Comment by ngimel** [comment] 2021-05-07 22:39
Closing due to age

**Comment by nairbv** [comment] 2021-07-26 15:32
This is still broken and I can consistently reproduce. I can get a cacche build to compile with USE_NCCL=0 or with DISABLE_CCACHE=1, but not without.

@pbelevich also apparently faced this issue, and was able to resolve with `ccache -C`. Builds succeed if the cache is restarted empty, but in a shared ccache environment (shared CCACHE_DIR) this slows down other developers.

I suspect ccache is caching files without including the NCCL flag in they cache key, which causes issues when moving back&forth compiling with and without nccl.

We had a workaround:
https://github.com/pytorch/pytorch/pull/13340

Which was recently removed:
https://github.com/pytorch/pytorch/pull/55814

cc @seemethere, @pbelevich, @mrshenli 


an example of one of the build errors when building with nccl and ccache:
```
/usr/local/cuda-11.1/bin/crt/link.stub:107:118: error: redefinition of ‘const unsigned char def_module_id_str_43_tmpxft_000040ce_00000000_7_sendrecv_cpp1_ii_f9db6a7a_17635 []’
 static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \
```

**Comment by davidberard98** [comment] 2022-08-29 17:56
#84007 caused issues when building on the AWS cluster, with errors like the following:

```
...
FAILED: nccl_external-prefix/src/nccl_external-stamp/nccl_external-build nccl/lib/libnccl_static.a /scratch/dberard/nccl-bisect/pytorch/build/nccl_external-prefix/src/nccl_external-stamp/nccl_external-build /scratch/dberard/nccl-bisect/pytorch/build/nccl/lib/libnccl_static.a
cd /scratch/dberard/nccl-bisect/pytorch/third_party/nccl/nccl && make -j24 -l24 CXX=/data/shared/bin/c++ CUDA_HOME=/usr/local/cuda-11.6 NVCC=/data/shared/bin/cuda/nvcc "NVCC_GENCODE=-gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_80,code=sm_80" BUILDDIR=/scratch/dberard/nccl-bisect/pytorch/build/nccl VERBOSE=0 && /usr/local/lib/python3.6/dist-packages/cmake/data/bin/cmake -E touch /scratch/dberard/nccl-bisect/pytorch/build/nccl_external-prefix/src/nccl_external-stamp/nccl_external-build
make -C src build BUILDDIR=/scratch/dberard/nccl-bisect/pytorch/build/nccl
make[1]: Entering directory '/scratch/dberard/nccl-bisect/pytorch/third_party/nccl/nccl/src'
make[2]: Entering directory '/scratch/dberard/nccl-bisect/pytorch/third_party/nccl/nccl/src/collectives/device'
/usr/local/cuda-11.6/bin/crt/link.stub:111:118: error: redefinition of ‘const unsigned char def_module_id_str_5b13a6ab_11_sendrecv_cu_2dca4361_39257 []’
 static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \
                                                                                                                      ^
/tmp/tmpxft_00010ccb_00000000-3_devlink.reg.c:4:1: note: in expansion of macro ‘DEFINE_REGISTER_FUNC’
 DEFINE_REGISTER_FUNC(_5b13a6ab_11_sendrecv_cu_2dca4361_39257)
 ^~~~~~~~~~~~~~~~~~~~
/usr/local/cuda-11.6/bin/crt/link.stub:79:30: note: ‘const unsigned char def_module_id_str_5b13a6ab_11_sendrecv_cu_2dca4361_39257 [44]’ previously defined here
 #define __DEFSTRNAME_CORE(X) def_module_id_str##X
                              ^
/usr/local/cuda-11.6/bin/crt/link.stub:80:25: note: in expansion of macro ‘__DEFSTRNAME_CORE’
 #define __DEFSTRNAME(X) __DEFSTRNAME_CORE(X)
                         ^~~~~~~~~~~~~~~~~
/usr/local/cuda-11.6/bin/crt/link.stub:111:28: note: in expansion of macro ‘__DEFSTRNAME’
 static const unsigned char __DEFSTRNAME(id) [] __attribute__((aligned(1))) __attribute__((section ("__nv_module_id"))) = "def " __TO_STRING(id); \
                            ^~~~~~~~~~~~
/tmp/tmpxft_00010ccb_00000000-3_devlink.reg.c:3:1: note: in expansion of macro ‘DEFINE_REGISTER_FUNC’
 DEFINE_REGISTER_FUNC(_5b13a6ab_11_sendrecv_cu_2dca4361_39257)
 ^~~~~~~~~~~~~~~~~~~~
...
```

**Closed** 2022-09-13 19:56 UTC
Labels: module: build, triaged, module: nccl
