### ISSUE TITLE
Error Sharing CUDA Models between Processes using `torch.multiprocessing`

### ISSUE THREAD

**Issue by yangky11** [pytorch/pytorch#9996] opened 2018-07-29 21:48 UTC
I got a runtime error when trying to share a CUDA model with a child process.

The code I was running:

```
import torch
import torch.multiprocessing as mp
import torch.nn as nn


def train(model):
  print(model)
  # do something..


if __name__ == '__main__':
    model = nn.Linear(10, 1)
    model.cuda()
    model.share_memory()

    mp.set_start_method('spawn')
    p = mp.Process(target=train, args=(model,))
    p.start()
    p.join()
```

The error traceback:

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    p.start()
  File "/home/yangky/anaconda3/lib/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/home/yangky/anaconda3/lib/python3.6/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/home/yangky/anaconda3/lib/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/yangky/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/yangky/anaconda3/lib/python3.6/multiprocessing/popen_fork.py", line 26, in __init__
    self._launch(process_obj)
  File "/home/yangky/anaconda3/lib/python3.6/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/home/yangky/anaconda3/lib/python3.6/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "/home/yangky/anaconda3/lib/python3.6/site-packages/torch/multiprocessing/reductions.py", line 179, in reduce_storage
    raise RuntimeError("Cannot pickle CUDA storage; try pickling a CUDA tensor instead")
RuntimeError: Cannot pickle CUDA storage; try pickling a CUDA tensor instead
```

## System Info

PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
CMake version: version 3.9.4

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.61
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 384.69
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.14.3)
[pip] numpydoc (0.7.0)
[pip] torch (0.4.1)
[pip] torchvision (0.2.1)
[conda] cuda80                    1.0                  h205658b_0    pytorch
[conda] magma-cuda80              2.3.0                         1    pytorch
[conda] pytorch                   0.4.1           py36_cuda8.0.61_cudnn7.1.2_1  [cuda80]  pytorch
[conda] torchvision               0.2.1                    py36_1    pytorch

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ailzhang** [comment] 2018-08-03 18:01
I can repro this on 0.4.1. Running bisect to find the offending commit.

**Comment by ailzhang** [comment] 2018-08-03 20:11
Seems to be related to this PR https://github.com/pytorch/pytorch/commit/976f9253a5425918eda7cf865b097cf42b5da8d7#diff-0d553ed0e9ca41fdac21632b4d503a10 cc: @ezyang

**Comment by ezyang** [comment] 2018-08-03 20:21
Ugh, I know what this is, but apparently I didn't fix it enough.

**Comment by ezyang** [comment] 2018-08-03 20:46
@yangky11 Can you please test https://github.com/pytorch/pytorch/pull/10220 and let me know if it works on your full model.

**Comment by yangky11** [comment] 2018-08-03 22:38
@ezyang I'm afraid I can't. I've been never able to build Pytorch from source due to some dependency issues on my server. And it's difficult for me to do anything about that since I don't have the root privilege.

**Comment by ezyang** [comment] 2018-08-04 17:46
Hmm, what's the error? I find that a fresh Anaconda environment can usually overcome any root-side misconfiguration, but maybe it's a CUDA related problem?

**Comment by yangky11** [comment] 2018-08-06 03:08
@ezyang I guess it's because of some version mismatches. 
```
[ 26%] Generating ../../../../third_party/protobuf/src/google/protobuf/compiler/js/well_known_types_embed.cc
../../../bin/js_embed: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ../../../bin/js_embed)
make[2]: *** [../third_party/protobuf/src/google/protobuf/compiler/js/well_known_types_embed.cc] Error 1
make[2]: *** Deleting file `../third_party/protobuf/src/google/protobuf/compiler/js/well_known_types_embed.cc'
make[1]: *** [third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by hyperfraise** [comment] 2018-09-12 10:40
Same problem... Are we not supposed to use multiprocess training anymore ?

**Comment by ezyang** [comment] 2018-09-13 00:06
@hyperfraise What version of PyTorch are you on? This was broken for a time but I was under the impression that it is fixed on master.

**Comment by ezyang** [comment] 2018-09-13 00:06
@lizhihao6 you as well, can you try this on master?

**Comment by arnaghizadeh** [comment] 2018-09-14 09:31
I have the same error and it seems package 0.4.0 is not in conda.

**Comment by arnaghizadeh** [comment] 2018-09-14 11:18
For future readers, in the end I had to use model.cpu() for sharing between threads and in each thread used model.cuda() to do the actual training. I have done that with version 0.4.1 because 0.4.0 has some weird issues on pickles. I hope the sharing problem solves soon so we don;t have to use such hacky and inefficient methods.

**Comment by ezyang** [comment] 2018-09-14 15:30
@arnaghizadeh If you upgrade to master past 0.4.1, this should fix your problem.

**Comment by arnaghizadeh** [comment] 2018-09-14 15:37
@ezyang do you guys have any nightly builds for us to use?

**Comment by ezyang** [comment] 2018-09-14 16:18
CC @pjh5  on nightlies

**Comment by soumith** [comment] 2018-10-11 18:39
@known-ai we dont ship nightly builds for Windows yet, so you are probably on `0.4.1`. This is a known problem for 0.4.1

**Comment by SPark9625** [comment] 2018-10-13 20:35
torch.__version__ == '1.0.0.dev20181013'

I tried OP's original code and on google Colab (K80 GPU), the code terminates without any problem. However, once you check the individual processes (just one in OP's original code), you can see that for all processes, exitcode is 1, meaning that the processes have terminated due to some issues.

So I guess it's still not entirely fixed? Or am I missing something?

**Comment by SPark9625** [comment] 2018-10-14 03:57
It turns out that jupyter notebook is not a good place to do multiprocessing. Setting the start method to 'spawn' or 'forkserver' for some reason stops even the most basic multiprocessing from working.

I don't personally own a GPU so would highly appreciate if anyone could try to reproduce OP's original code or give any comments on this.

**Comment by awarebayes** [comment] 2018-12-30 14:57
Same problem in A3C

**Comment by ezyang** [comment] 2019-01-03 07:36
If you are still having problems, please try 1.0 or master; @ailzhang fixed some more issues with CUDA sharing.

**Comment by michelgokan** [comment] 2020-01-31 20:28
This problem still exists :-(

**Comment by ailzhang** [comment] 2020-02-01 00:09
@michelgokan are you trying with the exact same script in this issue? It works for me on PyTorch master. 
Would you mind opening a new issue(or updating this one) with a repro script and the error you are seeing? Thanks!

**Closed** 2020-02-04 21:43 UTC
Labels: high priority, module: cuda, module: multiprocessing, nightly-announce, triaged

**Comment by ynuwm** [comment] 2020-09-10 07:52
torch 0.4.0 works.
