### ISSUE TITLE
torch.jit bug torch.cat() not working properly

### ISSUE THREAD

**Issue by faresVS** [pytorch/pytorch#43735] opened 2020-08-27 20:00 UTC
## 🐛 Bug

A `RuntimeError: vector::_M_range_check` is thrown when using torch.cat() inside a torch.jit function. The bug occurs only on the GPU (not CPU) if dim=-1 and some operations are being performed on the tensors in the list passed to the torch.cat() function.
The bug occurs with pytorch 1.6.0, and didn't happen in pytorch 1.5.1

## To Reproduce

Please run the following code to reproduce the problem.

```python

import torch
import torch.nn as nn

class DummyLayerNoBug(nn.Module):
    def __init__(self):
        super(DummyLayerNoBug, self).__init__()
    
    def forward(self, x):
        y = torch.cat([x, x], -1)
        return y

class DummyLayerBug(nn.Module):
    def __init__(self):
        super(DummyLayerBug, self).__init__()
    
    def forward(self, x):
        y = torch.cat([x + 0., x], -1)
        return y

class DummyLayerBugFix(nn.Module):
    def __init__(self):
        super(DummyLayerBugFix, self).__init__()
    
    def forward(self, x):
        y = torch.cat([x + 0., x], x.dim() - 1)
        return y


def test_DummyLaer_jit_vs_nojit(dummy_layer, device):
    input_tensor = torch.arange(6, dtype=torch.float32).reshape(1, 2, 3).to(device)
    target_tensor = torch.tensor([[[0.0000, 1.0000, 2.0000, 0.0000, 1.0000, 2.0000],
                                   [3.0000, 4.0000, 5.0000, 3.0000, 4.0000, 5.0000]]]).to(device)
    dummy_layer_jit = torch.jit.script(dummy_layer).to(device)
    dummy_layer = dummy_layer.to(device)

    y = dummy_layer(input_tensor)
    print("y: {}\n{}".format(y.shape, y))
    assert (y == target_tensor).all().item()
    y_jit = dummy_layer_jit(input_tensor)
    print("\ny_jit: {}\n{}".format(y_jit.shape, y_jit))
    assert (y_jit == target_tensor).all().item()


if __name__ == "__main__":

    print("\n\n=================== DummyLayerNoBug CPU ===================")
    test_DummyLaer_jit_vs_nojit(dummy_layer=DummyLayerNoBug(), device=torch.device("cpu"))

    print("\n\n=================== DummyLayerBugFix CPU ===================")
    test_DummyLaer_jit_vs_nojit(dummy_layer=DummyLayerBugFix(), device=torch.device("cpu"))

    print("\n\n=================== DummyLayerBug CPU ===================")
    test_DummyLaer_jit_vs_nojit(dummy_layer=DummyLayerBug(), device=torch.device("cpu"))


    print("\n\n=================== DummyLayerNoBug CUDA ===================")
    test_DummyLaer_jit_vs_nojit(dummy_layer=DummyLayerNoBug(), device=torch.device("cuda"))

    print("\n\n=================== DummyLayerBugFix CUDA ===================")
    test_DummyLaer_jit_vs_nojit(dummy_layer=DummyLayerBugFix(), device=torch.device("cuda"))

    print("\n\n=================== DummyLayerBug CUDA ===================")
    test_DummyLaer_jit_vs_nojit(dummy_layer=DummyLayerBug(), device=torch.device("cuda"))

```

Output of the script :
```
=================== DummyLayerNoBug CPU ===================
y: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]])

y_jit: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]])


=================== DummyLayerBugFix CPU ===================
y: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]])

y_jit: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]])


=================== DummyLayerBug CPU ===================
y: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]])

y_jit: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]])


=================== DummyLayerNoBug CUDA ===================
y: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]], device='cuda:0')

y_jit: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]], device='cuda:0')


=================== DummyLayerBugFix CUDA ===================
y: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]], device='cuda:0')

y_jit: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]], device='cuda:0')


=================== DummyLayerBug CUDA ===================
y: torch.Size([1, 2, 6])
tensor([[[0., 1., 2., 0., 1., 2.],
         [3., 4., 5., 3., 4., 5.]]], device='cuda:0')
Traceback (most recent call last):
  File "test_torch_cat_jit_regression.py", line 63, in <module>
    test_DummyLaer_jit_vs_nojit(dummy_layer=DummyLayerBug(), device=torch.device("cuda"))
  File "test_torch_cat_jit_regression.py", line 39, in test_DummyLaer_jit_vs_nojit
    y_jit = dummy_layer_jit(input_tensor)
  File "/home/fmenasri/torch1.6.0_p3.6_venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: vector::_M_range_check: __n (which is 18446744073709551615) >= this->size() (which is 3)

```

## Environment

Tested with PyTorch 1.6.0 on Ubuntu 18 (python 3.6.9), installed with pip in a virtualenv

The same code works correctly with PyTorch 1.5.1 on Ubuntu 18 (python 3.6.9), installed with pip in a virtualenv

cc @gmagogsfm

**Comment by ZolotukhinM** [comment] 2021-05-04 19:44
I wasn't able to reproduce it with a master (commit `74a4868d9a1`), with a 1.8-release build (commit `9112f4eded`), or with a 1.6-release build (commit `6a421d50abb`). Could anyone else please try reproing it?

**Comment by penguinwu** [comment] 2021-05-04 21:29
Please double check if this is not reproducible.

**Comment by desertfire** [comment] 2021-05-05 15:39
> I wasn't able to reproduce it with a master (commit `74a4868d9a1`), with a 1.8-release build (commit `9112f4eded`), or with a 1.6-release build (commit `6a421d50abb`). Could anyone else please try reproing it?

I was able to reproduce by "conda install pytorch==1.6.0 cudatoolkit=10.2 -c pytorch", both on Ubuntu 18 and CentOS 8. But building from commit 6a421d50abb did not reproduce it. @ZolotukhinM are we using the right commit ID?

**Comment by ZolotukhinM** [comment] 2021-05-05 16:07
Hm, interesting, I picked one of the branches that had "release" and "1.6" in its name, maybe it was still a wrong one. Is it reproducible with more recent releases or master?

**Comment by desertfire** [comment] 2021-05-05 20:57
> Hm, interesting, I picked one of the branches that had "release" and "1.6" in its name, maybe it was still a wrong one. Is it reproducible with more recent releases or master?

No. Master build and nightly are fine. I tried 1.7 and it is fine too.

**Comment by ZolotukhinM** [comment] 2021-05-05 21:09
Thanks for checking that! There's been a lot of changes in fusers/executors since 1.6, so I think it probably is no longer an issue. I suggest closing this as no longer reproducible.

**Closed** 2021-05-07 17:36 UTC
Labels: oncall: jit

**Comment by zyqm123** [comment] 2022-08-15 01:57
I reproduce this issue when I try to tain the stylegan-apa model in ubuntu with pytorch 1.7.1
