### ISSUE TITLE
Issue Exporting Pytorch model to ONNX that uses PackedSequence

### ISSUE THREAD

**Issue by daquilnp** [pytorch/pytorch#26462] opened 2019-09-19 13:45 UTC
## 🐛 Bug

There is an issue when you want to instantiate PackedSequence and then export that model to ONNX. it gives the following error:
`ONNX export failed: Cannot export individual pack_padded_sequence or pad_packed_sequence; these operations must occur in pairs.`

## To Reproduce

I have a model where I manipulate some data and place it in a PackedSequence.

Here is the snippet I use it for:

```
t_word_attention= self.word_attention(packed_sentences.data,
                                                     packed_words_per_sentence.data)  
t_word_attention= self.dropout(t_word_attention)
input_packed_sentences = PackedSequence(data=t_word_attention,
                                   batch_sizes=packed_sentences.batch_sizes,
                                    sorted_indices=packed_sentences.sorted_indices,
                                    unsorted_indices=packed_sentences.unsorted_indices)
out, _ = self.sentence_rnn(input_packed_sentences)
```
It works great during training and inference. However, when I try to export the model to ONNX I get the following error:
`ONNX export failed: Cannot export individual pack_padded_sequence or pad_packed_sequence; these operations must occur in pairs.`

## Expected behavior

For model to export properly

## Environment
I am running Pytorch 1.2.0 and ONNX 1.5.0

**Comment by zcarson92** [comment] 2020-12-10 18:22
Any updates on this? I am having the same issue when using `pack_padded_sequence()` and `PackSequence()`

**Comment by dingjie1993** [comment] 2021-01-28 12:14
I have met the same issue too, when pytorch can solve this problem?

**Comment by garymm** [comment] 2021-06-23 23:49
duplicate of #28423

**Closed by garymm** 2021-06-23 23:49 UTC
Labels: module: onnx, triaged
