### ISSUE TITLE
signbit on bf16 tensor causes compile error

### ISSUE THREAD

**Issue by jthakurH** [pytorch/pytorch#135341] opened 2024-09-06 09:22 UTC
### 🐛 Describe the bug

signbit on bf16 tensor causes compile error when compiled with torch.compile and "inductor" backend. it works fine in eager backend

### Error logs

Traceback (most recent call last):
  File "/tmp/lj.py", line 12, in <module>
    res = cm_fn(tensor)
  File "/tmp/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 433, in _fn
    return fn(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 1116, in __call__
    return self._torchdynamo_orig_callable(
  File "/tmp/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 948, in __call__
    result = self._inner_convert(
  File "/tmp/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 472, in __call__
    return _compile(
  File "/tmp/python3.10/site-packages/torch/_utils_internal.py", line 84, in wrapper_function
    return StrobelightCompileTimeProfiler.profile_compile_time(
  File "/tmp/python3.10/site-packages/torch/_strobelight/compile_time_profiler.py", line 129, in profile_compile_time
    return func(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/tmp/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 817, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/tmp/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 636, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/tmp/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1185, in transform_code_object
    transformations(instructions, code_options)
  File "/tmp/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 178, in _fn
    return fn(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 582, in transform
    tracer.run()
  File "/tmp/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2451, in run
    super().run()
  File "/tmp/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 893, in run
    while self.step():
  File "/tmp/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 805, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/tmp/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2642, in RETURN_VALUE
    self._return(inst)
  File "/tmp/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2627, in _return
    self.output.compile_subgraph(
  File "/tmp/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1098, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/tmp/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1318, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/tmp/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1409, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/tmp/python3.10/site-packages/torch/_dynamo/output_graph.py", line 1390, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/tmp/python3.10/site-packages/torch/_dynamo/repro/after_dynamo.py", line 129, in __call__
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/tmp/python3.10/site-packages/torch/__init__.py", line 1951, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/tmp/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1505, in compile_fx
    return aot_autograd(
  File "/tmp/python3.10/site-packages/torch/_dynamo/backends/common.py", line 69, in __call__
    cg = aot_module_simplified(gm, example_inputs, **self.kwargs)
  File "/tmp/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 954, in aot_module_simplified
    compiled_fn, _ = create_aot_dispatcher_function(
  File "/tmp/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_functorch/aot_autograd.py", line 687, in create_aot_dispatcher_function
    compiled_fn, fw_metadata = compiler_fn(
  File "/tmp/python3.10/site-packages/torch/_functorch/_aot_autograd/jit_compile_runtime_wrappers.py", line 168, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/tmp/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_inductor/compile_fx.py", line 1410, in fw_compiler_base
    return inner_compile(
  File "/tmp/python3.10/site-packages/torch/_dynamo/repro/after_aot.py", line 84, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/tmp/python3.10/site-packages/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/tmp/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_inductor/compile_fx.py", line 527, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/usr/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/tmp/python3.10/site-packages/torch/_inductor/compile_fx.py", line 831, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
  File "/tmp/python3.10/site-packages/torch/_inductor/graph.py", line 1749, in compile_to_fn
    return self.compile_to_module().call
  File "/tmp/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_inductor/graph.py", line 1699, in compile_to_module
    mod = PyCodeCache.load_by_key_path(
  File "/tmp/python3.10/site-packages/torch/_inductor/codecache.py", line 3062, in load_by_key_path
    mod = _reload_python_module(key, path)
  File "/tmp/python3.10/site-packages/torch/_inductor/runtime/compile_tasks.py", line 45, in _reload_python_module
    exec(code, mod.__dict__, mod.__dict__)
  File "/tmp/torchinductor_jthakur/af/cafaelhwcr6hmrrvgvip5wdvbuvsnbalpnlsksn64qxzgt4sid43.py", line 49, in <module>
    async_compile.wait(globals())
  File "/tmp/python3.10/site-packages/torch/_inductor/async_compile.py", line 247, in wait
    scope[key] = result.result()
  File "/tmp/python3.10/site-packages/torch/_inductor/codecache.py", line 3433, in result
    return self.result_fn()
  File "/tmp/python3.10/site-packages/torch/_inductor/codecache.py", line 2654, in future
    result = get_result()
  File "/tmp/python3.10/site-packages/torch/_inductor/codecache.py", line 2478, in load_fn
    future.result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/python3.10/site-packages/torch/_inductor/codecache.py", line 2504, in _worker_compile_cpp
    compile_file(input_path, output_path, shlex.split(cmd))
  File "/tmp/python3.10/site-packages/torch/_dynamo/utils.py", line 231, in time_wrapper
    r = func(*args, **kwargs)
  File "/tmp/python3.10/site-packages/torch/_inductor/codecache.py", line 2360, in compile_file
    raise exc.CppCompileError(cmd, output) from e
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CppCompileError: C++ compile error

### Minified repro

```
import torch


def fn(tensor):
    res = torch.signbit(tensor)
    return res


if __name__ == "__main__":
    tensor = torch.randn((2, 3, 4), dtype=torch.bfloat16)
    cm_fn = torch.compile(fn)
    res = cm_fn(tensor)
    print(res)

```

### Versions

[pip3] numpy==1.23.5
[pip3] torch==2.4.0
[pip3] torchaudio==2.4.0
[pip3] torchdata==0.7.1
[pip3] torchtext==0.18.0
[pip3] torchvision==0.19.0

cc @chauhang @penguinwu @voznesenskym @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @ColinPeppler @amjames @desertfire @aakhundov @ezyang

**Comment by bdhirsh** [comment] 2024-09-06 22:18
Marking with inductor, although I couldn't repro:

(1) can you test on a nightly and see if you still see the error?

(2) The `CppCompileError: C++ compile error` error from inductor is a bit reminiscent of a toolchain error (e.g. if you don't have a compatible C++ compiler toolchain installed locally). You might get a better error message though if you run with `TORCHINDUCTOR_COMPILE_THREADS=1`, so the error doesn't happen in a subprocess

**Comment by jthakurH** [comment] 2024-10-15 05:48
Hi @bdhirsh 
yes this is available in latest nightly as well.
and I see following error:
```
g++ /tmp/torchinductor_jthakur/sw/cswwxhyau5dqkfjfuws5icbxplhzkvwfx5qv53ymmics6r5swsny.cpp -shared -fPIC -Wall -std=c++17 -Wno-unused-variable -Wno-unknown-pragmas -D_GLIBCXX_USE_CXX11_ABI=1 -I/home/jthakur/.venv_pt_op_test/lib/python3.10/site-packages/torch/include -I/home/jthakur/.venv_pt_op_test/lib/python3.10/site-packages/torch/include/torch/csrc/api/include -I/home/jthakur/.venv_pt_op_test/lib/python3.10/site-packages/torch/include/TH -I/home/jthakur/.venv_pt_op_test/lib/python3.10/site-packages/torch/include/THC -I/usr/include/python3.10 -L/home/jthakur/.venv_pt_op_test/lib/python3.10/site-packages/torch/lib -L/usr/lib/x86_64-linux-gnu -L/home/jthakur/.venv_pt_op_test/lib/python3.10/site-packages/torch/lib -ltorch -ltorch_cpu -lgomp -ltorch_python -lc10 -mavx512f -mavx512dq -mavx512vl -mavx512bw -mfma -D CPU_CAPABILITY_AVX512 -O3 -DNDEBUG -ffast-math -fno-finite-math-only -fno-unsafe-math-optimizations -ffp-contract=off -march=native -fopenmp -D TORCH_INDUCTOR_CPP_WRAPPER -D C10_USING_CUSTOM_GENERATED_MACROS -o /tmp/torchinductor_jthakur/sw/cswwxhyau5dqkfjfuws5icbxplhzkvwfx5qv53ymmics6r5swsny.so

Output:
/tmp/torchinductor_jthakur/sw/cswwxhyau5dqkfjfuws5icbxplhzkvwfx5qv53ymmics6r5swsny.cpp: In function ‘void kernel(const bfloat16*, bool*)’:
/tmp/torchinductor_jthakur/sw/cswwxhyau5dqkfjfuws5icbxplhzkvwfx5qv53ymmics6r5swsny.cpp:16:1: error: unrecognizable insn:
   16 | }
      | ^
(insn 13 12 14 2 (set (reg:V4SI 115 [ vect__12.454 ])
        (lshiftrt:V4SI (subreg:V4SI (subreg:V4SF (reg:V4SI 169 [ vect__17.452 ]) 0) 0)
            (const_int 31 [0x1f]))) "/usr/include/c++/11/cmath":662:29 -1
     (nil))
during RTL pass: vregs
/tmp/torchinductor_jthakur/sw/cswwxhyau5dqkfjfuws5icbxplhzkvwfx5qv53ymmics6r5swsny.cpp:16:1: internal compiler error: in extract_insn, at recog.c:2770
0x7f7945293d8f __libc_start_call_main
        ../sysdeps/nptl/libc_start_call_main.h:58
0x7f7945293e3f __libc_start_main_impl
        ../csu/libc-start.c:392
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-11/README.Bugs> for instructions.


Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

```

**Comment by bdhirsh** [comment] 2024-10-15 17:54
The error looks related to the system compiler on your machine (inductor is generating C++ code to JIT-compile, but it invokes your system compiler, which is not compatible with the code that inductor is generating).

maybe cc @desertfire (do we have a recommended way of telling folks how to install a system compiler can properly compile inductor cpp code?)

**Comment by leslie-fang-intel** [comment] 2024-12-17 06:14
Hi @jthakurH, running your example code with latest main branch (a42ca5a45bd78fca62f944f8c3776990bdba0e0a), I didn't reproduce the same error. Could you help to check the latest main branch?

**Comment by leslie-fang-intel** [comment] 2024-12-24 01:36
Hi @jthakurH, close this issue as it looks like a system compiler on your machine. Feel free to re-open for further discussion.

**Closed by leslie-fang-intel** 2024-12-24 01:36 UTC
Labels: needs reproduction, triaged, oncall: pt2, module: inductor, oncall: cpu inductor
