### ISSUE TITLE
libtorch model predict cuda convert to cpu: C10::error at memory location

### ISSUE THREAD

**Issue by HeConnor** [pytorch/pytorch#73912] opened 2022-03-08 10:23 UTC
### 🐛 Describe the bug

hello,

  CPU tensor and CUDA tensor can be converted to each other：
```c++
auto tensor_image_cu = tensor_image.to(device);
auto tensor_image2 = tensor_image_cu.to(torch::kCPU);
```

**but  when  I converted the model prediect CUDA Tensor** to CPU tensor,  so confused!

Unhandled exception at 0x000007FEFCFDA06D in LibTorchDll.exe: Microsoft C++ exception: **c10::Error at memory location 0x00000000001CD900.**

part of code as blow:

```c++
auto input_x = torch::cat(tensor_vec).to(device);    // cuda, size [1, 1, 256, 256]

// single output!
auto output_y = module->forward({ input_x }).toTensor();  // get output, cuda type  [1, 1, 256, 256]

// Error! !!
auto yp = output_y.to(torch::kCPU);
// or !!!
auto yp2 = output_y.cpu();
```

### Versions

- window 7 x64, GTX 1080 Ti
- vs 2015
- libtorch 1.1.0+cu90, release version
- cuda 9.0

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser @ngimel

**Comment by bdhirsh** [comment] 2022-03-08 22:01
@HeConnor do you have a minimum repro with a code snippet? Does the bug only reproduce on windows?

**Comment by HeConnor** [comment] 2022-03-10 09:11
eh...  Only on windows.

I have tried to reproduce the bug with **vgg16**, but it works fine！
GPU memory cost 1209MiB!

```bash
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 391.35                 Driver Version: 391.35                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 108... WDDM  | 00000000:01:00.0 Off |                  N/A |
| 32%   58C    P2    60W / 250W |   1209MiB / 11264MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     83668      C   ...LibTorchDll\x64\Release\LibTorchDll.exe N/A      |
+-----------------------------------------------------------------------------+
```



but when I tried to use my own model,  **GPU memory exception**!!!   (**Total: 11264 MiB**)

- When using **libtorch**, the memory changes as follows:

  ​	1. empty: 137MiB

  ​	2. load image and model: 549MiB

  ​	3. forward: **11229MiB**

  ​	4. predict results (CUDA)  -> (CPU)    **c10::Error at memory location**

- When using **Pytorch**, the memory only use **4171MiB** (recording in forward, it works fine)

**I don't know how to solve it in libtorch………..**



**Test code** like that:

```c++
int main(int argc, const char* argv[]) {
    torch::DeviceType device_type;
    if (torch::cuda::is_available()) {
        std::cout << "Used: GPU!" << std::endl;
        device_type = torch::kCUDA;
    }
    else
    {
        std::cout << "Used: CPU" << std::endl;
        device_type = torch::kCPU;
    }
    torch::Device device(device_type);

    std::cout << "Loading Model...\n";

    // Deserialize the ScriptModule from a file using torch::jit::load().
    char model_path[1000];
    sprintf_s(model_path, "*****");
    std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(model_path, device);
    assert(module != nullptr);


    // read data and convert to tensor
    int xySamples = 224, zSamples = 3;
    float *image = new float[xySamples * xySamples * zSamples];

    char filename[1000];
    sprintf_s(filename, "image name****");
    readData(filename, image, xySamples * xySamples * zSamples);

    auto tensor_image = torch::from_blob(image, { 1, zSamples, xySamples, xySamples }, torch::kFloat);

    std::vector<torch::Tensor> tensor_vec;
    std::vector<torch::Tensor> zPatches_vec;

    // split z axis
    torch::NoGradGuard no_grad;
    tensor_vec.push_back(tensor_image.clone());
    zPatches_vec.push_back(module->forward({ torch::cat(tensor_vec).to(device) }).toTensor().detach().cpu());
    
    tensor_vec.clear();

    auto x = torch::cat(zPatches_vec);

}
```

**Comment by mszhanyi** [comment] 2022-03-10 09:46
libtorch 1.1.0?
why did you use so old version?

**Comment by mszhanyi** [comment] 2022-03-10 09:49
I think the latest Libtorch + cu11.X can run your machine GTX 1080

**Comment by HeConnor** [comment] 2022-03-10 09:55
I have tried to use the latest libtorch in VS 2015; 

compile failed： 
**You need C++14 to compile PyTorch**

................

> I think the latest Libtorch + cu11.X can run your machine GTX 1080

**Comment by mszhanyi** [comment] 2022-03-10 10:17
could you use VS 2019? 
I developed one [VS extension](https://marketplace.visualstudio.com/items?itemName=YiZhang.LibTorch001) for setting Libtorch Project

**Comment by HeConnor** [comment] 2022-03-11 03:57
@[mszhanyi](https://github.com/mszhanyi) Thanks for your advice, but the environment cannot be changed...

In addition, it seems to be a problem that existed a long time ago....

https://discuss.pytorch.org/t/libtorch-uses-much-more-gpu-memory-than-python/45310

**Comment by jbschlosser** [comment] 2022-03-14 18:38
Hey @HeConnor, I suggest moving this discussion to the [PyTorch forums](https://discuss.pytorch.org/) in hopes that someone there can help you out, since it's such an old version of PyTorch. Note that the issues here are used for bugs within PyTorch that we can address.

**Closed by jbschlosser** 2022-03-14 18:38 UTC
Labels: needs reproduction, module: windows, module: cpp, module: cuda, triaged
