### ISSUE TITLE
[inductor][cpu]basic_gnn_edgecnn performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#114495] opened 2023-11-24 03:54 UTC
### 🐛 Describe the bug

basic_gnn_edgecnn multiple thread performance regression in 2023-11-15
<table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>shape</th>
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>static</td>
      <td>basic_gnn_edgecnn</td>
      <td>1</td>
      <td>1.186295</td>
      <td>0.024034565</td>
      <td>0.028512084286675</td>
      <td>1</td>
      <td>1.415264</td>
      <td>0.019589376</td>
      <td>0.027724138635264</td>
      <td>0.84</td>
      <td>0.97</td>
      <td>0.82</td>
    </tr>
    <tr>
      <td>dynamic</td>
      <td>basic_gnn_edgecnn</td>
      <td>1</td>
      <td>1.13976</td>
      <td>0.023218447</td>
      <td>0.02646345715272</td>
      <td>1</td>
      <td>1.396895</td>
      <td>0.020098177</td>
      <td>0.028075042960415</td>
      <td>0.82</td>
      <td>1.06</td>
      <td>0.87</td>
    </tr>
  </tbody>

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">

SW | Nightly   commit | Main   commit
-- | -- | --
Pytorch | a5a4048 | 6f44090
Torchbench | / | 7617d3f5
torchaudio | 475b6ae | ede4309
torchtext | 142d029 | 45e4b8c
torchvision | 8636bf3 | 4ac707a
torchdata | eb9bf61 | d76d92c
dynamo_benchmarks | e6efc29 | /

</body>

</html>

Repro:

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)

bash inductor_single_run.sh multiple inference performance torchbench basic_gnn_edgecnn float32 first static/dynamic default

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/f97c2dabd9309ec3523e5b7df6ffed9f69abcbd7

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by zxd1997066** [comment] 2023-11-24 03:59
cc @WeizhuoZhang-intel @chuanqi129

**Comment by Le-Zheng** [comment] 2023-11-24 05:50
@guilhermeleobas We found the commit https://github.com/pytorch/pytorch/commit/f97c2dabd9309ec3523e5b7df6ffed9f69abcbd7 cause this performance regression. Could you please help to take a look?

**Comment by zxd1997066** [comment] 2023-11-24 06:58
[torchbench-basic_gnn_edgecnn-inference-float32-static-default-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13455961/torchbench-basic_gnn_edgecnn-inference-float32-static-default-performance-multiple-drop_guilty_commit.log)
attached the bisect search log

**Comment by guilhermeleobas** [comment] 2023-11-24 19:42
@zxd1997066 and @Le-Zheng, the changes I made in f97c2da are going to be superseded by https://github.com/pytorch/pytorch/pull/114471 and https://github.com/pytorch/pytorch/pull/114509.

> @guilhermeleobas We found the commit https://github.com/pytorch/pytorch/commit/f97c2dabd9309ec3523e5b7df6ffed9f69abcbd7 cause this performance regression. Could you please help to take a look?

It's likely that the source of the issue is the assert function (`TORCH_CHECK`/`tl.device_assert`) added by PyTorch when it cannot verify that the indices of an (indirect) index operation fall within bounds of a tensor.

Nonetheless, I ran the script above on three different commits to try to reproduce the regression. The numbers reported below represent the speedup column.

- commit 6f4409073f9 (baseline - as per first comment):
    - Static: 1.438x ~ 1.448x
    - Dynamic: 1.443x

- Current main (0d6d97d):
    - Static: 1.441x
    - Dynamic: 1.442x

- Lezcano PR (15c065b78ec):
    - Static: 1.454x
    - Dynamic: 1.453x

I guess my measures were a bit off as I was expecting 0d6d97d to be slower compared to baseline (6f4409073f9). The command I am using to execute the tests is the one @zxd1997066 mentioned in his first comment:

```
bash inductor_single_run.sh multiple inference performance torchbench basic_gnn_edgecnn float32 first static/dynamic default
```

**Comment by chuanqi129** [comment] 2023-12-01 05:00
Thanks @guilhermeleobas for the double check and update. Does it mean this issue will be fixed by those 2 PR https://github.com/pytorch/pytorch/pull/114471 and https://github.com/pytorch/pytorch/pull/114509?

**Comment by lezcano** [comment] 2023-12-15 07:28
The issue here is that not being able to prove statically that some indices are in-fact direct indexing and within bounds inhibits vectorisation on CPU. https://github.com/pytorch/pytorch/pull/114471 will improve this situation in the static shape case, but the dynamic shape case is not mathematically solvable in general, so there are some limitations there.

That being said, there is another way out of this. There is no reason why one operation in the kernel (indirect indexing in this case) should inhibit vectorisation in the whole kernel. We could have a fallback like that in the `Vectorized` class in eager that is equivalent to
```
for i in range(simd_width):
  op(x[i])
```
We could implement `TORCH_CHECK` and indirect indexing like this, and the PRs above would not produce such a performance hit when they cannot prove that an index is not within bounds.

**Comment by jgong5** [comment] 2023-12-18 14:45
In fact, I don't think the primary cause of this performance regression is caused by the adding of index bound checks but the pointwise fuse cat changes from https://github.com/pytorch/pytorch/pull/111233 and https://github.com/pytorch/pytorch/pull/114520 avoids the optimization on CPU and brought back most of the performance. Removing index bound checks brough more. Below are my test with multi-thread static shape on `basic_gnn_edgecnn`.

baseline (mainline: 34fe850d0083688abf0a27f3e864723f0858aab1):
0.913x
avoid pointwise fuse cat on cpu:
1.480x
remove index bound checks:
1.511x

> We could implement `TORCH_CHECK` and indirect indexing like this, and the PRs above would not produce such a performance hit when they cannot prove that an index is not within bounds.

@lezcano In fact, many of these cases (including this one) don't require the vectorized index bound checks while the kernel is vectorized. This is because we only promote the scalar to vector values on demand now. Take the kernel after disabling "pointwise fuse cat" as an example, the generated code for such kernels is below. It is vectorized and the index check is on scalar.
```c++
            #pragma omp for 
            for(long x0=static_cast<long>(0L); x0<static_cast<long>(200000L); x0+=static_cast<long>(1L))
            {
                for(long x1=static_cast<long>(0L); x1<static_cast<long>(64L); x1+=static_cast<long>(16L))
                {
                    auto tmp0 = in_ptr0[static_cast<long>(200000L + x0)];
                    auto tmp5 = in_ptr0[static_cast<long>(x0)];
                    auto tmp1 = decltype(tmp0)(tmp0 + 10000);
                    auto tmp2 = tmp0 < 0;
                    auto tmp3 = tmp2 ? tmp1 : tmp0;
                    TORCH_CHECK((0 <= tmp3) & (tmp3 < 10000L), "index out of bounds: 0 <= tmp3 < 10000L")
                    auto tmp4 = at::vec::Vectorized<float>::loadu(in_ptr1 + static_cast<long>(x1 + (64L*tmp3)));
                    auto tmp6 = decltype(tmp5)(tmp5 + 10000);
                    auto tmp7 = tmp5 < 0;
                    auto tmp8 = tmp7 ? tmp6 : tmp5;
                    TORCH_CHECK((0 <= tmp8) & (tmp8 < 10000L), "index out of bounds: 0 <= tmp8 < 10000L")
                    auto tmp9 = at::vec::Vectorized<float>::loadu(in_ptr1 + static_cast<long>(x1 + (64L*tmp8)));
                    auto tmp10 = tmp9 - tmp4;
                    tmp4.store(out_ptr0 + static_cast<long>(x1 + (128L*x0)));
                    tmp10.store(out_ptr1 + static_cast<long>(x1 + (128L*x0)));
                }
            }
```

The enabling of "pointwise fuse cat" disables the vectorization since we currently do not support vectorization on index_expr. I added this support in https://github.com/pytorch/pytorch/pull/114545, with which the speedup would become 1.438x but it is still lower than 1.480x. Below is the vectorized kernel generated from https://github.com/pytorch/pytorch/pull/114545 with the help of vec::arange. Still, the index bound checks are on scalar, not vector.
```c++
            #pragma omp for 
            for(long x0=static_cast<long>(0L); x0<static_cast<long>(200000L); x0+=static_cast<long>(1L))
            {
                for(long x1=static_cast<long>(0L); x1<static_cast<long>(128L); x1+=static_cast<long>(16L))
                {
                    auto tmp0 = c10::convert<int>(x1);
                    auto tmp1 = at::vec::Vectorized<int32_t>::arange(tmp0, 1);
                    auto tmp2 = static_cast<int>(0);
                    auto tmp3 = at::vec::Vectorized<int>(tmp2);
                    auto tmp4 = to_float_mask(tmp1 >= tmp3);
                    auto tmp5 = static_cast<int>(64);
                    auto tmp6 = at::vec::Vectorized<int>(tmp5);
                    auto tmp7 = to_float_mask(tmp1 < tmp6);
                    auto tmp8 = [&]
                    {
                        auto tmp9 = in_ptr0[static_cast<long>(200000L + x0)];
                        auto tmp10 = decltype(tmp9)(tmp9 + 10000);
                        auto tmp11 = tmp9 < 0;
                        auto tmp12 = tmp11 ? tmp10 : tmp9;
                        TORCH_CHECK((0 <= tmp12) & (tmp12 < 10000L), "index out of bounds: 0 <= tmp12 < 10000L")
                        auto tmp13 = masked_load(in_ptr1 + static_cast<long>(x1 + (64L*tmp12)), to_float_mask(tmp7));
                        return tmp13;
                    }
                    ;
                    auto tmp14 =
                    [&]
                    {
                        if (all_zero(to_float_mask(tmp7)))
                        {
                            return at::vec::Vectorized<float>(static_cast<float>(0.0));
                        }
                        else
                        {
                            return decltype(tmp8())::blendv(at::vec::Vectorized<float>(static_cast<float>(0.0)), tmp8(), to_float_mask(tmp7));
                        }
                    }
                    ()
                    ;
                    auto tmp15 = to_float_mask(tmp1 >= tmp6);
                    auto tmp16 = static_cast<int>(128);
                    auto tmp17 = at::vec::Vectorized<int>(tmp16);
                    auto tmp18 = to_float_mask(tmp1 < tmp17);
                    auto tmp19 = [&]
                    {
                        auto tmp20 = in_ptr0[static_cast<long>(x0)];
                        auto tmp21 = decltype(tmp20)(tmp20 + 10000);
                        auto tmp22 = tmp20 < 0;
                        auto tmp23 = tmp22 ? tmp21 : tmp20;
                        TORCH_CHECK((0 <= tmp23) & (tmp23 < 10000L), "index out of bounds: 0 <= tmp23 < 10000L")
                        auto tmp24 = masked_load(in_ptr1 + static_cast<long>((-64L) + x1 + (64L*tmp23)), to_float_mask(tmp15));
                        auto tmp25 = in_ptr0[static_cast<long>(200000L + x0)];
                        auto tmp26 = decltype(tmp25)(tmp25 + 10000);
                        auto tmp27 = tmp25 < 0;
                        auto tmp28 = tmp27 ? tmp26 : tmp25;
                        TORCH_CHECK((0 <= tmp28) & (tmp28 < 10000L), "index out of bounds: 0 <= tmp28 < 10000L")
                        auto tmp29 = masked_load(in_ptr1 + static_cast<long>((-64L) + x1 + (64L*tmp28)), to_float_mask(tmp15));
                        auto tmp30 = tmp24 - tmp29;
                        return tmp30;
                    }
                    ;
                    auto tmp31 =
                    [&]
                    {
                        if (all_zero(to_float_mask(tmp15)))
                        {
                            return at::vec::Vectorized<float>(static_cast<float>(0.0));
                        }
                        else
                        {
                            return decltype(tmp19())::blendv(at::vec::Vectorized<float>(static_cast<float>(0.0)), tmp19(), to_float_mask(tmp15));
                        }
                    }
                    ()
                    ;
                    auto tmp32 = decltype(tmp14)::blendv(tmp31, tmp14, tmp7);
                    tmp32.store(out_ptr0 + static_cast<long>(x1 + (128L*x0)));
                }
            }
```

**Comment by lezcano** [comment] 2023-12-18 15:05
Tentatively unassigning this issue from Guilherme as it seems that's not related to indirect indexing

**Comment by jgong5** [comment] 2023-12-19 02:26
> 2\. Unrelated to this issue: It seems like there's a bug with `TORCH_CHECK`s within masked sections. `TORCH_CHECK((0 <= tmp28) & (tmp28 < 10000L), "index out of bounds: 0 <= tmp28 < 10000L")` should not be `tmp28`, but `tmp28 & to_float_mask(tmp15)`, for example.

Not sure if I understand. Do you mean we only need to check the bound when `to_float_mask(tmp15)` holds? I guess it is already guaranteed since the check won't be executed when `to_float_mask(tmp15)` is all zero.

**Comment by lezcano** [comment] 2023-12-19 08:00
Sorry, the condition I wrote was wrong. Fixed it.
My point is that, as we do in CUDA, we should check that the mask associated to the load is true. If the mask is false at any point, the checked condition could be anything, as we are not going to use it in the load.

**Comment by jgong5** [comment] 2023-12-20 02:09
> My point is that, as we do in CUDA, we should check that the mask associated to the load is true. If the mask is false at any point, the checked condition could be anything, as we are not going to use it in the load.
> 2\. Unrelated to this issue: It seems like there's a bug with `TORCH_CHECK`s within masked sections. `TORCH_CHECK((0 <= tmp28) & (tmp28 < 10000L), "index out of bounds: 0 <= tmp28 < 10000L")` should not be `tmp28`, but `tmp28 | ~to_float_mask(tmp15)`, for example.

Got it but the case here is about the check of a scalar index not a vector. When the check code is executed, the mask would not be all zeros, meaning the check code is valid to run.

**Comment by lezcano** [comment] 2023-12-20 08:53
Yes, in this case it's alright because the mask would be of length 1 and would always have a 1 in it, so perhaps there's some piece of code that elides the mask. In this case, the whole masked sequence could be elided given that the mask is trivial.

I hope the mask is there when the masked sequence is of length greater than one...

**Comment by jgong5** [comment] 2023-12-21 01:21
> Yes, in this case it's alright because the mask would be of length 1 and would always have a 1 in it, so perhaps there's some piece of code that elides the mask. In this case, the whole masked sequence could be elided given that the mask is trivial.
> 
> I hope the mask is there when the masked sequence is of length greater than one...

Oh, the mask is not of length 1 in this case, it is a vector and could contain either 0 or 1 in it. Please note that `tmp15` is built from `tmp1` (`auto tmp15 = to_float_mask(tmp1 >= tmp6);`) which is created with vec arange: `auto tmp1 = at::vec::Vectorized<int32_t>::arange(tmp0, 1);`

**Comment by lezcano** [comment] 2023-12-21 09:55
Ooops. I misread badly the code. Now I understand and all looks good. Sorry for the noise!

**Comment by jiayisunx** [comment] 2024-01-18 05:44
Fixed by https://github.com/pytorch/pytorch/pull/116313

**Closed by jiayisunx** 2024-01-18 05:44 UTC
Labels: module: performance, triaged, oncall: pt2, oncall: cpu inductor
