### ISSUE TITLE
new_ones() missing 1 required positional arguments: "size"

### ISSUE THREAD

**Issue by jamarju** [pytorch/pytorch#46824] opened 2020-10-25 18:20 UTC
I'm getting this unexpected error on pytorch nightly (1.8.0.dev20201025) when I subclass Tensor and call `new_ones` on an instance of my subclass.

## To Reproduce

```
from torch import Tensor

class MyTensor(Tensor):
    pass

a = MyTensor([1,2,3])
a.new_ones(320)
```

## Expected result

A tensor of 320 ones.

## Actual result

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-75c7d48cef15> in <module>
      5 
      6 a = MyTensor([1,2,3])
----> 7 a.new_ones(320)

~/anaconda3/envs/sped3090/lib/python3.7/site-packages/torch/tensor.py in __torch_function__(cls, func, types, args, kwargs)
   1022 
   1023         with _C.DisableTorchFunction():
-> 1024             ret = func(*args, **kwargs)
   1025             return _convert(ret, cls)
   1026 

TypeError: new_ones() missing 1 required positional arguments: "size"
```

## Environment

```
PyTorch version: 1.8.0.dev20201025
Is debug build: True
CUDA used to build PyTorch: 11.0
ROCM used to build PyTorch: N/A

OS: Linux Mint 20 (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.7 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 455.23.04
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.8.0.dev20201025
[pip3] torchvision==0.8.0.dev20201025
[conda] blas                      1.0                         mkl    conda-forge
[conda] cudatoolkit               11.0.221             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.2.0            py37h23d657b_0
[conda] mkl_random                1.1.1            py37h0573a6f_0
[conda] numpy                     1.19.1           py37hbc911f0_0
[conda] numpy-base                1.19.1           py37hfa32c7d_0
[conda] pytorch                   1.8.0.dev20201025 py3.7_cuda11.0.221_cudnn8.0.3_0    pytorch-nightly
[conda] torchvision               0.8.0.dev20201025      py37_cu110    pytorch-nightly
```

cc @hameerabbasi @rgommers

**Comment by mrshenli** [comment] 2020-10-27 15:11
I tried locally, and I confirm I can reproduce. But this only happens to the derived class `MyTensor` not `torch.Tensor`. Adding this to triage review to check whether we want to support derived Tensor classes.

**Comment by mrshenli** [comment] 2020-10-27 15:16
Hey @jamarju, could you please share some more info on why do you need a derived Tensor class?

**Comment by jamarju** [comment] 2020-10-27 19:46
Yes: the fast.ai library uses subclassing to add semantics and/or metadata to Tensors, eg: TensorImage, TensorMask, TensorPoint, TensorBBox, etc. Issue #22402 has some discussion and elaborates further on that.

**Comment by jamarju** [comment] 2020-10-28 23:47
If it helps, `new_zeros` **does** work:

```
from torch import Tensor

class MyTensor(Tensor):
    pass

a = MyTensor([1,2,3])
a.new_zeros(320).shape
```

Result:

```
(320,)
```

**Comment by hameerabbasi** [comment] 2020-10-30 15:16
This is a duplicate of #47051

**Comment by mrshenli** [comment] 2020-11-02 18:07
#47115 is attempting to fix this.

**Comment by albanD** [comment] 2020-11-02 18:08
Closing as duplicate of #47051 per @hameerabbasi comments.

**Closed by albanD** 2020-11-02 18:08 UTC
Labels: module: __torch_function__, module: tensor creation, triage review

**Comment by hameerabbasi** [comment] 2020-11-02 18:10
> #47115 is attempting to fix this.

I believe you made an off-by-one error. 😅 it's #47114.
