### ISSUE TITLE
Subclass issue in multiprocessing.pool()

### ISSUE THREAD

**Issue by ameet20** [pytorch/pytorch#17155] opened 2019-02-15 07:49 UTC
## 🐛 Bug

Hello, 

Trying to subclass:

```python
class MyPool(torch.multiprocessing.Pool):
   pass
```

Ends up with:

```shell
TypeError: method expected 2 arguments, got 3
```

This does makes sense, as it is not possible to subclass python's `multiprocessing.Pool` as well - but only `multiprocessing.pool.Pool`.
`multiprocessing.Pool` is **not** a type, but rather a context method:

```python
print ( torch.multiprocessing.Pool)
#output:
<bound method BaseContext.Pool of <multiprocessing.context.DefaultContext object at 0x10f4bd550>>
```

The main problem is that `torch` doesn't expose the `torch.multiprocessing.pool` module - so it impossible to subclass `torch.multiprocessing.pool.Pool()`

```shell
AttributeError: module 'torch.multiprocessing' has no attribute 'pool'
```

This might be related to #16954 - but I don't think it's a dupe, as the main problem here is exposing the `torch.pool` module.

**Comment by lerks** [comment] 2019-02-15 14:15
Probably a duplicate of #17048.

**Comment by ameet20** [comment] 2019-02-15 14:33
facing the same that's why

**Comment by fmassa** [comment] 2019-02-15 15:18
let's keep the discussion in #17048

**Closed by fmassa** 2019-02-15 15:18 UTC
