### ISSUE TITLE
Getting started CPU version on Anaconda requires GPU libraries, probable error/bug in packaging

### ISSUE THREAD

**Issue by apiszcz** [pytorch/pytorch#30957] opened 2019-12-09 07:05 UTC
https://pytorch.org/get-started/locally/

This install line requires NVIDIA GPU CUDA libraries for the _C.pyd files. Stack traces indicate unable to load _C.dll, when DLL dependency checker is run on the file, it shows linking requirements for CUDA library DLLs.
Selection, Stable, Windows, Conda, Python 3.7, CUDA CPU None
conda install pytorch torchvision cpuonly -c pytorch

This install line does NOT require NVIDIA GPU CUDA libraries for the _C.pyd files and works properly as CPU only.
Selection, Stable, Windows, Pip, Python 3.7, CUDA CPU None
pip3 install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by peterjc123** [comment] 2019-12-09 07:15
I tried but it returns `pip3 install torch==1.3.1+cpu torchvision==0.4.2+cpu -f https://download.pytorch.org/whl/torch_stable.html`. I cannot reproduce your issue.

**Comment by peterjc123** [comment] 2019-12-09 07:25
I also tried out installing the conda package and didn't find any issue there. The logs are listed below:
```cmd
C:\Users\peter>conda create -n pytorch_cpu_test python=3.7
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\peter\Anaconda3\envs\pytorch_cpu_test

  added / updated specs:
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.11.27 |                0         163 KB  defaults
    certifi-2019.11.28         |           py37_0         157 KB  defaults
    openssl-1.1.1d             |       he774522_3         5.7 MB  defaults
    pip-19.3.1                 |           py37_0         1.9 MB  defaults
    python-3.7.5               |       h8c8aaf0_0        14.7 MB  defaults
    setuptools-42.0.2          |           py37_0         676 KB  defaults
    sqlite-3.30.1              |       he774522_0         962 KB  defaults
    ------------------------------------------------------------
                                           Total:        24.2 MB

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/win-64::ca-certificates-2019.11.27-0
  certifi            pkgs/main/win-64::certifi-2019.11.28-py37_0
  openssl            pkgs/main/win-64::openssl-1.1.1d-he774522_3
  pip                pkgs/main/win-64::pip-19.3.1-py37_0
  python             pkgs/main/win-64::python-3.7.5-h8c8aaf0_0
  setuptools         pkgs/main/win-64::setuptools-42.0.2-py37_0
  sqlite             pkgs/main/win-64::sqlite-3.30.1-he774522_0
  vc                 pkgs/main/win-64::vc-14.1-h0510ff6_4
  vs2015_runtime     pkgs/main/win-64::vs2015_runtime-14.16.27012-hf0eaf9b_0
  wheel              pkgs/main/win-64::wheel-0.33.6-py37_0
  wincertstore       pkgs/main/win-64::wincertstore-0.2-py37_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
sqlite-3.30.1        | 962 KB    | ############################################################################ | 100%
certifi-2019.11.28   | 157 KB    | ############################################################################ | 100%
setuptools-42.0.2    | 676 KB    | ############################################################################ | 100%
pip-19.3.1           | 1.9 MB    | ############################################################################ | 100%
ca-certificates-2019 | 163 KB    | ############################################################################ | 100%
openssl-1.1.1d       | 5.7 MB    | ############################################################################ | 100%
python-3.7.5         | 14.7 MB   | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate pytorch_cpu_test
#
# To deactivate an active environment, use
#
#     $ conda deactivate


C:\Users\peter>conda activate pytorch_cpu_test

(pytorch_cpu_test) C:\Users\peter>conda install pytorch torchvision cpuonly -c pytorch
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\peter\Anaconda3\envs\pytorch_cpu_test

  added / updated specs:
    - cpuonly
    - pytorch
    - torchvision


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    cffi-1.13.2                |   py37h7a1dbc1_0         227 KB  defaults
    cpuonly-1.0                |                0           2 KB  pytorch
    libtiff-4.1.0              |       h56a325e_0         997 KB  defaults
    mkl_fft-1.0.15             |   py37h14836fe_0         137 KB  defaults
    numpy-1.17.4               |   py37h4320e6b_0           5 KB  defaults
    numpy-base-1.17.4          |   py37hc3f5095_0         3.8 MB  defaults
    pillow-6.2.1               |   py37hdc69c19_0         714 KB  defaults
    pytorch-1.3.1              |      py3.7_cpu_0        57.4 MB  pytorch
    six-1.13.0                 |           py37_0          27 KB  defaults
    torchvision-0.4.2          |         py37_cpu         6.0 MB  pytorch
    ------------------------------------------------------------
                                           Total:        69.2 MB

The following NEW packages will be INSTALLED:

  blas               pkgs/main/win-64::blas-1.0-mkl
  cffi               pkgs/main/win-64::cffi-1.13.2-py37h7a1dbc1_0
  cpuonly            pytorch/noarch::cpuonly-1.0-0
  freetype           pkgs/main/win-64::freetype-2.9.1-ha9979f8_1
  icc_rt             pkgs/main/win-64::icc_rt-2019.0.0-h0cc432a_1
  intel-openmp       pkgs/main/win-64::intel-openmp-2019.4-245
  jpeg               pkgs/main/win-64::jpeg-9b-hb83a4c4_2
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0
  libtiff            pkgs/main/win-64::libtiff-4.1.0-h56a325e_0
  mkl                pkgs/main/win-64::mkl-2019.4-245
  mkl-service        pkgs/main/win-64::mkl-service-2.3.0-py37hb782905_0
  mkl_fft            pkgs/main/win-64::mkl_fft-1.0.15-py37h14836fe_0
  mkl_random         pkgs/main/win-64::mkl_random-1.1.0-py37h675688f_0
  ninja              pkgs/main/win-64::ninja-1.9.0-py37h74a9793_0
  numpy              pkgs/main/win-64::numpy-1.17.4-py37h4320e6b_0
  numpy-base         pkgs/main/win-64::numpy-base-1.17.4-py37hc3f5095_0
  olefile            pkgs/main/win-64::olefile-0.46-py37_0
  pillow             pkgs/main/win-64::pillow-6.2.1-py37hdc69c19_0
  pycparser          pkgs/main/win-64::pycparser-2.19-py37_0
  pytorch            pytorch/win-64::pytorch-1.3.1-py3.7_cpu_0
  six                pkgs/main/win-64::six-1.13.0-py37_0
  tk                 pkgs/main/win-64::tk-8.6.8-hfa6e2cd_0
  torchvision        pytorch/win-64::torchvision-0.4.2-py37_cpu
  xz                 pkgs/main/win-64::xz-5.2.4-h2fa13f4_4
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_3
  zstd               pkgs/main/win-64::zstd-1.3.7-h508b16e_0


Proceed ([y]/n)? y


Downloading and Extracting Packages
cpuonly-1.0          | 2 KB      | ############################################################################ | 100%
mkl_fft-1.0.15       | 137 KB    | ############################################################################ | 100%
cffi-1.13.2          | 227 KB    | ############################################################################ | 100%
six-1.13.0           | 27 KB     | ############################################################################ | 100%
numpy-1.17.4         | 5 KB      | ############################################################################ | 100%
torchvision-0.4.2    | 6.0 MB    | ############################################################################ | 100%
libtiff-4.1.0        | 997 KB    | ############################################################################ | 100%
pillow-6.2.1         | 714 KB    | ############################################################################ | 100%
numpy-base-1.17.4    | 3.8 MB    | ############################################################################ | 100%
pytorch-1.3.1        | 57.4 MB   | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(pytorch_cpu_test) C:\Users\peter>pip install psutil
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000001CF6E895F88>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /simple/psutil/
Collecting psutil
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9d/84/0a2006cc263e9f5b6dfbb2301fbcce5558f0d6d17d0c11c7c6749a45c79e/psutil-5.6.7-cp37-cp37m-win_amd64.whl (236kB)
     |████████████████████████████████| 245kB 97kB/s
Installing collected packages: psutil
Successfully installed psutil-5.6.7

(pytorch_cpu_test) C:\Users\peter>python
Python 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import psutil
>>> import torch
>>> import psutil, os
>>> p = psutil.Process( os.getpid() )
>>> for dll in p.memory_maps():
...   print(dll.path)
...
C:\Windows\System32\locale.nls
C:\Windows\System32\C_1252.NLS
C:\Windows\Globalization\Sorting\SortDefault.nls
C:\Windows\System32\en-US\KernelBase.dll.mui
C:\Windows\System32\en-US\kernel32.dll.mui
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\python.exe
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\torch\lib\torch.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\mkl_core.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\torch\lib\torch_python.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\mkl_avx2.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\mkl_intel_thread.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\mkl_vml_avx2.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\mkl_rt.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\libcrypto-1_1-x64.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\python37.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\libiomp5md.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\core\_multiarray_umath.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Library\bin\libssl-1_1-x64.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\torch\lib\c10.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\generator.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\mtrand.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_ssl.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\torch\lib\shm.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\sfc64.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\pcg64.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\bounded_integers.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\philox.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\bit_generator.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\common.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_decimal.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\random\mt19937.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\fft\_pocketfft_internal.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\linalg\_umath_linalg.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_ctypes.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\core\_multiarray_tests.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_multiprocessing.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\torch\_C.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_hashlib.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\numpy\linalg\lapack_lite.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_queue.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\Lib\site-packages\psutil\_psutil_windows.cp37-win_amd64.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_lzma.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_bz2.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\_socket.pyd
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\DLLs\select.pyd
C:\Users\peter\Anaconda3\vcruntime140.dll
C:\Windows\System32\version.dll
C:\Windows\System32\pdh.dll
C:\Windows\System32\msvcp140.dll
C:\Users\peter\Anaconda3\envs\pytorch_cpu_test\python3.dll
C:\Windows\System32\wtsapi32.dll
C:\Windows\System32\rsaenh.dll
C:\Windows\System32\IPHLPAPI.DLL
C:\Windows\System32\cryptbase.dll
C:\Windows\System32\winsta.dll
C:\Windows\System32\umpdc.dll
C:\Windows\System32\kernel.appcore.dll
C:\Windows\System32\profapi.dll
C:\Windows\System32\powrprof.dll
C:\Windows\System32\msasn1.dll
C:\Windows\System32\win32u.dll
C:\Windows\System32\cfgmgr32.dll
C:\Windows\System32\cryptsp.dll
C:\Windows\System32\KernelBase.dll
C:\Windows\System32\bcrypt.dll
C:\Windows\System32\windows.storage.dll
C:\Windows\System32\ucrtbase.dll
C:\Windows\System32\crypt32.dll
C:\Windows\System32\msvcp_win.dll
C:\Windows\System32\gdi32full.dll
C:\Windows\System32\bcryptprimitives.dll
C:\Windows\System32\rpcrt4.dll
C:\Windows\System32\kernel32.dll
C:\Windows\System32\advapi32.dll
C:\Windows\System32\oleaut32.dll
C:\Windows\System32\msvcrt.dll
C:\Windows\System32\shell32.dll
C:\Windows\System32\ws2_32.dll
C:\Windows\System32\sechost.dll
C:\Windows\System32\psapi.dll
C:\Windows\System32\gdi32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\SHCore.dll
C:\Windows\System32\imm32.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\user32.dll
C:\Windows\System32\shlwapi.dll
C:\Windows\System32\ntdll.dll
>>>
```

**Comment by peterjc123** [comment] 2019-12-09 07:27
Now that no problems could be found, I will close this issue. Just feel free to reopen when you disagree.

**Closed by peterjc123** 2019-12-09 07:27 UTC
