### ISSUE TITLE
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '32']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by G-YY** [pytorch/pytorch#31032] opened 2019-12-10 03:53 UTC
## 🐛 Bug

[1331/2730] Building CXX object caffe2\CMakeFiles\torch_cpu.dir\core\blob_serialization.cc.obj
FAILED: caffe2/CMakeFiles/torch_cpu.dir/core/blob_serialization.cc.obj 
C:\PROGRA~2\MICROS~4\2019\COMMUN~1\VC\Tools\MSVC\1424~1.283\bin\Hostx64\x64\cl.exe  /nologo /TP -DAT_PARALLEL_OPENMP=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -Dtorch_cpu_EXPORTS -Iaten\src -I..\aten\src -I. -I..\ -I..\cmake\..\third_party\benchmark\include -Icaffe2\contrib\aten -I..\third_party\onnx -Ithird_party\onnx -I..\third_party\foxi -Ithird_party\foxi -I..\caffe2\..\torch\csrc\api -I..\caffe2\..\torch\csrc\api\include -I..\caffe2\aten\src\TH -Icaffe2\aten\src\TH -I..\caffe2\..\torch\..\aten\src -Icaffe2\aten\src -Icaffe2\..\aten\src -Icaffe2\..\aten\src\ATen -I..\caffe2\..\torch\csrc -I..\caffe2\..\torch\..\third_party\miniz-2.0.8 -I..\aten\src\TH -I..\aten\..\third_party\catch\single_include -I..\aten\src\ATen\.. -Icaffe2\aten\src\ATen -I..\third_party\miniz-2.0.8 -I..\caffe2\core\nomnigraph\include -I..\c10\.. -I..\third_party\cpuinfo\include -I..\third_party\FP16\include -I..\cmake\..\third_party\googletest\googlemock\include -I..\cmake\..\third_party\googletest\googletest\include -I..\third_party\protobuf\src -I..\cmake\..\third_party\eigen -ID:\Aanaconda3\include -ID:\Aanaconda3\lib\site-packages\numpy\core\include -I..\cmake\..\third_party\pybind11\include -I\opt\rocm\hip\include -I\include -I..\cmake\..\third_party\cub -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\include" -I..\caffe2 /DWIN32 /D_WINDOWS /GR  /w /EHa /MP /bigobj -openmp:experimental -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION /MD /O2 /Ob2  /w /EHa /MP /bigobj   -DCUDA_HAS_FP16=1 -DUSE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD /Z7 /EHa /DNOMINMAX /wd4267 /wd4251 /wd4522 /wd4838 /wd4305 /wd4244 /wd4190 /wd4101 /wd4996 /wd4275 /bigobj -O2 -DCAFFE2_BUILD_MAIN_LIB -DONNX_BUILD_MAIN_LIB -std:c++14 /showIncludes /Focaffe2\CMakeFiles\torch_cpu.dir\core\blob_serialization.cc.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c ..\caffe2\core\blob_serialization.cc
D:\code\Obj_tracking\pytorch\caffe2/core/context_base.h(92): error C2338: CopyToCPU requires fundamental types
..\caffe2\core\blob_serialization.cc(602): note: 查看对正在编译的函数 模板 实例化“void at::BaseContext::CopyToCPU<c10::Half>(size_t,const T *,T *)”的引用
        with
        [
            T=c10::Half
        ]
ninja: build stopped: subcommand failed.
-- Building version 1.4.0a0+190dac1
cmake -GNinja -DBUILD_PYTHON=True -DBUILD_TEST=True -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=D:\code\Obj_tracking\pytorch\torch -DCMAKE_PREFIX_PATH=D:\Aanaconda3\Lib\site-packages -DNUMPY_INCLUDE_DIR=D:\Aanaconda3\lib\site-packages\numpy\core\include -DPYTHON_EXECUTABLE=D:\Aanaconda3\python.exe -DPYTHON_INCLUDE_DIR=D:\Aanaconda3\include -DPYTHON_LIBRARY=D:\Aanaconda3/libs/python37.lib -DTORCH_BUILD_VERSION=1.4.0a0+190dac1 -DUSE_NUMPY=True D:\code\Obj_tracking\pytorch
cmake --build . --target install --config Release -- -j 32
Traceback (most recent call last):
  File "setup.py", line 755, in <module>
    build_deps()
  File "setup.py", line 316, in build_deps
    cmake=cmake)
  File "D:\code\Obj_tracking\pytorch\tools\build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "D:\code\Obj_tracking\pytorch\tools\setup_helpers\cmake.py", line 337, in build
    self.run(build_args, my_env)
  File "D:\code\Obj_tracking\pytorch\tools\setup_helpers\cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "D:\Aanaconda3\lib\subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '32']' returned non-zero exit status 1.
Here is the build.log
## To Reproduce

1.git clone --recursive https://github.com/pytorch/pytorch
2.cd pytorch
3.python setup.py install

## Expected 

> behavior

## Environment
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A

OS: Microsoft Windows 10
GCC version: (MinGW.org GCC-8.2.0-5) 8.2.0
CMake version: version 3.16.0

Python version: 3.7
Is CUDA available: N/A
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX TITAN X
Nvidia driver version: 426.00
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] numpy==1.16.5
[pip] numpydoc==0.9.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.4                      245
[conda] mkl-include               2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.14           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0

**Comment by peterjc123** [comment] 2019-12-10 05:28
duplicate of https://github.com/pytorch/pytorch/issues/30932.

**Closed by peterjc123** 2019-12-10 05:28 UTC
Labels: module: build, triaged
