### ISSUE TITLE
DISABLED test_ddp_sync_bn_training_vs_eval (__main__.TestDistBackendWithSpawn)

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#68173] opened 2021-11-11 14:19 UTC
Platforms: rocm

https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/4865//console

```
13:00:51 ======================================================================
13:00:51 ERROR [105.046s]: test_ddp_sync_bn_training_vs_eval (__main__.TestDistBackendWithSpawn)
13:00:51 ----------------------------------------------------------------------
13:00:51 Traceback (most recent call last):
13:00:51   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 457, in wrapper
13:00:51     self._join_processes(fn)
13:00:51   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 676, in _join_processes
13:00:51     self._check_return_codes(elapsed_time)
13:00:51   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 728, in _check_return_codes
13:00:51     i, elapsed_time
13:00:51 RuntimeError: Process 0 terminated or timed out after 105.0231831073761 seconds
```

Happening consistently after https://github.com/pytorch/pytorch/pull/67445

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @jeffdaily @sunway513 @jithunnair-amd @ROCmSupport @KyleCZH

**Comment by malfet** [comment] 2021-11-11 19:08
See also https://github.com/pytorch/pytorch/issues/68189

**Comment by mrshenli** [comment] 2021-11-11 19:27
Is it possible to only disable this on ROCm? If it is impossible to do that using GH issue,  I can send a PR to skip rocm for this test

cc @malfet @janeyx99

**Comment by mruberry** [comment] 2021-11-11 19:40
> Is it possible to only disable this on ROCm? If it is impossible to do that using GH issue, I can send a PR to skip rocm for this test
> 
> cc @malfet @janeyx99

This is skipped only on ROCm. "Platforms for which to skip the test: rocm"

**Comment by mrshenli** [comment] 2021-11-11 20:29
> https://docs.google.com/spreadsheets/d/1_DcTx2sTC9t8nnnm2D3ulMHbCMbfUWZS59GcFgjrLIo/edit#gid=1115930144

Nice! Thanks! Is this achieved by adding the `Platforms: rocm` header in the issue body?

**Comment by mruberry** [comment] 2021-11-11 20:39
> > https://docs.google.com/spreadsheets/d/1_DcTx2sTC9t8nnnm2D3ulMHbCMbfUWZS59GcFgjrLIo/edit#gid=1115930144
> 
> Nice! Thanks! Is this achieved by adding the `Platforms: rocm` header in the issue body?

Yep

**Comment by mruberry** [comment] 2021-11-12 14:20
I'm not sure this is being skipped properly as it happened again here: https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/5082//console.

cc @janeyx99

**Comment by mrshenli** [comment] 2021-11-12 16:19
Hey @janeyx99, we used to have spawn and fork tests. So avoid code duplication, individual test cases are organized into a separate class. Then `TestDistBackendWithSpawn` inherit from both `DistributedTest._DistTestBase` and `TestDistBackend`. The later is a subclass of `common_utils.TestCase`. 

https://github.com/pytorch/pytorch/blob/c37f413e7505b2e9c51bc6ca3e13aa0856e96690/test/distributed/test_distributed_spawn.py#L31-L36

**Comment by janeyx99** [comment] 2021-11-12 16:26
I have seen that code, and it looks like the common_utils.TestCase setUp code is not getting called for this particular test case. How can I verify that it is/isn't getting called?

**Comment by rohan-varma** [comment] 2021-11-12 18:18
Might make sense that it happens after the referenced PR which is a kineto update, as this test uses the profiler to verify that some collectives are called/not called. So maybe some sort of issue with the profiler is being hit.

I think we can refactor this test to get rid of needing the profiler and having some other way to check if the collective was called (e.g. were gradients synchronized or not).

**Comment by janeyx99** [comment] 2021-11-12 19:35
I did more investigation, and I was wrong before when I thought the setUp was not being called. It _is_ called, however, the disabled_tests_dict was None at the time. 

I added code to print disabled_tests_dict in common_utils.py here right before this line https://github.com/pytorch/pytorch/blob/master/torch/testing/_internal/common_utils.py#L1284

When running locally with PYTORCH_TEST_WITH_ROCM=1, IN_CI=1 and after downloading the disabled-tests json by running `python test/run_test.py -i test_cpp_extensions_jit` (You could test anything, I just picked that test cuz it's relatively short), the test is properly skipped! And disabled_tests_dict was correct. So I was ultra confused.
Command: python distributed/test_distributed_spawn.py -k test_ddp_sync_bn_training_vs_eval --import-disabled-tests 

But then I remembered @rohan-varma's change put many tests in a subprocess so I tried running with --subprocess:
python distributed/test_distributed_spawn.py -k test_ddp_sync_bn_training_vs_eval --import-disabled-tests --subprocess
Two things:
1. It unfortunately doesn't respect the -k to only run 1 test case, but ran the whole test file
2. disabled_tests_dict was None for all the tests! Even though disabled_tests_dict is supposed to be a global variable, since it is still populated after runtime, it likely was lost when we switched to a new subprocess.

**Comment by rohan-varma** [comment] 2021-11-12 19:58
Can we just use unittest.skip() decorator for now?

**Comment by rohan-varma** [comment] 2021-11-12 20:24
@janeyx99 The log after the subprocess diff landed should show the way to repro the failure - 

```
BACKEND=gloo WORLD_SIZE=3 /opt/conda/bin/python3.6 distributed/test_distributed_spawn.py -v TestDistBackendWithSpawn.test_ddp_profiling_torch_profiler
```

i.e. grep for "command to reproduce" here https://ci.pytorch.org/jenkins/job/pytorch-builds/job/pytorch-linux-bionic-rocm4.3.1-py3.6-test-distributed/4942//console

**Comment by janeyx99** [comment] 2021-11-12 20:30
> Can we just use unittest.skip() decorator for now?

Yes, we always can do this, but we may have to retroactively do this for all disabled dist tests

**Comment by rohan-varma** [comment] 2021-11-30 22:11
Removing oncall: distributed label as it appears to be ROCM specific. Please feel free to loop in distributed if it turns out to be a wider issue or debugging help is needed.

**Comment by jaglinux** [comment] 2022-07-27 22:27
The test is passing when run in loop on ROCm 5.2

**Comment by jeffdaily** [comment] 2022-07-28 18:37
Closing based on latest comments.

**Closed by jeffdaily** 2022-07-28 18:37 UTC
Labels: high priority, triage review, module: rocm, module: flaky-tests, skipped
