### ISSUE TITLE
use heatmaps = dsntnn.flat_softmax(unnormalized_heatmaps),when translate to ONNX,show error

### ISSUE THREAD

**Issue by mathpopo** [pytorch/pytorch#31941] opened 2020-01-08 08:55 UTC
%2212 : Float(56) = aten::linspace(%2200, %2204, %2191, %3099, %3100, %2210, %3101), scope: CoordRegressionNetwork # /home/anaconda3/envs/MobilePose-pytorch1/lib/python3.6/site-packages/dsntnn/__init__.py:61:0

/home/anaconda3/envs/MobilePose-pytorch1/lib/python3.6/site-packages/dsntnn/__init__.py:61: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  return torch.linspace(first, last, length, dtype=dtype, device=device)
/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/utils.py:617: UserWarning: ONNX export failed on ATen operator linspace because torch.onnx.symbolic_opset9.linspace does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "/home/Downloads/MobilePose-pytorch-master/run_webcam.py", line 70, in <module>
    humans = e.inference(image)
  File "/home/Downloads/MobilePose-pytorch-master/estimator.py", line 112, in inference
    export_params=True)#,  # store the trained parameter weights inside the model file
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/utils.py", line 262, in _model_to_graph
    fixed_batch_size=fixed_batch_size)
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/__init__.py", line 174, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/utils.py", line 618, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/home/anaconda3/envs/human-pose-estimation/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: 'linspace'

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by mathpopo** [comment] 2020-01-08 09:01
https://github.com/anibali/dsntnn/blob/master/examples/basic_usage.md

class CoordRegressionNetwork(nn.Module):
    def __init__(self, n_locations):
        super().__init__()
        self.fcn = FCN()
        self.hm_conv = nn.Conv2d(16, n_locations, kernel_size=1, bias=False)

    def forward(self, images):
        # 1. Run the images through our FCN
        fcn_out = self.fcn(images)
        # 2. Use a 1x1 conv to get one unnormalized heatmap per location
        unnormalized_heatmaps = self.hm_conv(fcn_out)
        # 3. Normalize the heatmaps
        heatmaps = dsntnn.flat_softmax(unnormalized_heatmaps)
        # 4. Calculate the coordinates
        coords = dsntnn.dsnt(heatmaps)

        return coords, heatmaps

**Comment by mathpopo** [comment] 2020-01-08 09:09
def flat_softmax(inp):
    """Compute the softmax with all but the first two tensor dimensions combined."""

    orig_size = inp.size()
    flat = inp.view(-1, reduce(mul, orig_size[2:]))
    flat = torch.nn.functional.softmax(flat, -1)
    return flat.view(*orig_size)

**Comment by mathpopo** [comment] 2020-01-08 09:24
i move the dsntnn api directly to use,also show the issue

 %2229 : Float(56) = aten::linspace(%2217, %2221, %2194, %3106, %3107, %2227, %3108), scope: CoordRegressionNetwork # /home/Downloads/MobilePose-pytorch-master/func.py:41:0

 %2212 : Float(56) = aten::linspace(%2200, %2204, %2191, %3099, %3100, %2210, %3101), scope: CoordRegressionNetwork # /home/Downloads/MobilePose-pytorch-master/func.py:41:

**Comment by mathpopo** [comment] 2020-01-08 11:27
@houseroad

**Comment by mathpopo** [comment] 2020-01-09 03:04
https://github.com/anibali/dsntnn/issues/9

**Comment by zou3519** [comment] 2020-01-09 15:51
@mathpopo could you give us a self-contained script that reproduces the issue?

**Comment by mathpopo** [comment] 2020-01-10 05:43
@zou3519 hi , could you give me a tool to help me get this script?sorry , i just have the whole program

[model.txt](https://github.com/pytorch/pytorch/files/4044136/model.txt)

[func.txt](https://github.com/pytorch/pytorch/files/4044141/func.txt)

**Comment by mathpopo** [comment] 2020-01-16 03:54
@zou3519 what i give is the "self-contained script" ?if not ,could you give me some directions?

**Comment by mathpopo** [comment] 2020-01-17 03:34
@zou3519  i modify by meself ,just torch::flip and torch.linspace, i just translate numpy api to list (from tensor) to re-build it ,can onnx it.

**Comment by mathpopo** [comment] 2020-01-17 08:36
torch::flip and torch.linspace   cannot onnx

**Comment by garymm** [comment] 2022-03-01 21:27
linspace is supported as of https://github.com/pytorch/pytorch/pull/60246 (opset version 9 and above)
flip is supported as of https://github.com/pytorch/pytorch/pull/20533 (opset version 10 and above)

Closing this issue due to age and lack of clear reproduction instructions.
If you want to open a new issue, please provide the full repro code, including the model definition and the call to `torch.onnx.export`.

**Closed by garymm** 2022-03-01 21:27 UTC
Labels: module: onnx, triaged
