### ISSUE TITLE
Implementation of ISTFT

### ISSUE THREAD

**Issue by mravanelli** [pytorch/pytorch#15778] opened 2019-01-07 03:10 UTC
Hi,
is there any plan to implement the inverse short-time fourier transform (ISTFT)?  I saw that STFT is already implemented, but I cannot find the inverse transform. This would be a very important feature for people working on audio and speech.

Thank you!

Mirco

**Comment by SsnL** [comment] 2019-01-07 16:51
Yes, we want to do this, but no one has spent time to actually implement it yet.... Duplicate of https://github.com/pytorch/pytorch/issues/3775

**Comment by mravanelli** [comment] 2019-01-07 16:54
Great! I can help you debug it!

**Comment by vadimkantorov** [comment] 2019-08-15 13:10
@SsnL Seems that ISTFT has been implemented in torchaudio: https://pytorch.org/audio/functional.html#istft

It would be great if it was relocated to the core

**Comment by vincentqb** [comment] 2019-08-22 21:29
Closing since duplicate of #3775

**Closed by vincentqb** 2019-08-22 21:29 UTC
Labels: feature, module: operators, todo, triaged
