### ISSUE TITLE
Wrong grad of torch.symeig for degenerate eigenvalues

### ISSUE THREAD

**Issue by mfkasim1** [pytorch/pytorch#47599] opened 2020-11-09 14:32 UTC
## 🐛 Bug

Grad on `torch.symeig` gives the wrong value if there are repeated eigenvalues (degeneracy exists), even though the grad should be finite.

## To Reproduce

```python
import torch
torch.manual_seed(126)
n = 5
kwargs = {
    "dtype": torch.float64,
}
# random matrix to be orthogonalized for the eigenvectors
mat = torch.randn((n, n), **kwargs).requires_grad_()

# matrix for the loss function
P2 = torch.randn((n, n), **kwargs).requires_grad_()

# the degenerate eigenvalues
a = torch.tensor([0.5, 1.0, 2.0], **kwargs).requires_grad_()

def get_loss(a, mat, P2):
    # get the orthogonal vector for the eigenvectors
    P, _ = torch.qr(mat)

    # line up the eigenvalues
    b = torch.cat((a[:2], a[1:2], a[2:], a[2:]))

    # construct the matrix
    diag = torch.diag_embed(b)
    A = torch.matmul(torch.matmul(P.T, diag), P)

    eivals, eivecs = torch.symeig(A, eigenvectors=True)
    U = eivecs[:, 1:3]  # the degenerate eigenvectors

    loss = torch.einsum("rc,rc->", torch.matmul(P2, U), U)
    return loss

torch.autograd.gradcheck(get_loss, (a, mat, P2))
```

Error raised:

```
Traceback (most recent call last):
  File "new.py", line 38, in <module>
    torch.autograd.gradcheck(get_loss, (a, mat, P2))
  File "/home/user/anaconda2/envs/torchdev/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 388, in gradcheck
    checkIfNumericalAnalyticAreClose(a, n, j)
  File "/home/user/anaconda2/envs/torchdev/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 369, in checkIfNumericalAnalyticAreClose
    return fail_test(error_str + 'Jacobian mismatch for output %d with respect to input %d,\n'
  File "/home/muhammadkasim/anaconda2/envs/torchdev/lib/python3.8/site-packages/torch/autograd/gradcheck.py", line 287, in fail_test
    raise RuntimeError(msg)
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[-6.1062e-10],
        [ 1.1449e-10],
        [-1.3878e-11]], dtype=torch.float64)
analytical:tensor([[-0.0780],
        [-0.1282],
        [ 0.1291]], dtype=torch.float64)
```

## Expected behavior

The loss function above is chosen so that it doesn't depend on which linear combination of degenerate eigenvectors is chosen (see [this stackexchange link](https://math.stackexchange.com/questions/3887425/find-matrix-mathbfv-that-gives-constant-value-of-mathrmtr-mathbfut/3887520?noredirect=1#comment8017186_3887520)), so the gradient should be finite and well-defined.
The finite grad from finite difference also confirms this, so the expected behaviour is that the analytical gradient should match the numerical gradient.

## Environment

```
[pip3] numpy==1.19.1
[pip3] torch==1.8.0a0
[conda] blas                      1.0                         mkl
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.2                      256
[conda] mkl-include               2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.1           py38hbc911f0_0
[conda] numpy-base                1.19.1           py38hfa32c7d_0
[conda] torch                     1.8.0a0                  pypi_0    pypi
```

## Additional context

I already have a solution for this problem as I implemented in [xitorch](https://github.com/xitorch/xitorch/blob/93ef1bf3ec1cc852dc17bf3fc4afa49fea603360/xitorch/linalg/symeig.py#L216), which summarizes as:

1. Check if there is a degeneracy by comparing the eigenvalues (**need to decide** on how to compare the eigenvalue)
1. If the degeneracy exists, check the requirement: the loss function does not depend on which linear combination of the degenerate eigenvectors (see [this mathoverflow link](https://mathoverflow.net/questions/375410/requirements-for-finite-backward-derivatives-of-degenerate-eigenvectors))
1. If it doesn't satisfy the requirement, return `nan` or go ahead with the old computation (**need to decide**)
1. If it does satisfy, then use the new stabilized calculation for the backward computation (which probably just replacing the degenerate values with `inf` instead of replacing only the diagonal, as in [this line](https://github.com/pytorch/pytorch/blob/9e0102c10f57631000ebf28e55a055f480b9b780/torch/csrc/autograd/FunctionsManual.cpp#L1887)).

I submit this issue to see if PyTorch team is interested in having this.
If no objection, I'm happy to implement this.

Ref: https://arxiv.org/abs/2011.04366

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @gqchen @pearu @nikitaved @vishwakftw @jianyuh @mruberry @heitorschueroff

**Comment by ezyang** [comment] 2020-11-09 18:12
One thought: testing for degeneracy sounds like it would require a synchronization on CUDA, so there's a tradeoff here between being more correct and performance.

**Comment by mfkasim1** [comment] 2020-11-09 19:38
> One thought: testing for degeneracy sounds like it would require a synchronization on CUDA

Why would that be? Checking the degeneracy can be done using the F matrix in the current implementation of `symeig_backward`.
We can just check if any elements of it are less than a certain threshold.

**Comment by mruberry** [comment] 2020-11-10 06:08
> > One thought: testing for degeneracy sounds like it would require a synchronization on CUDA
> Why would that be? Checking the degeneracy can be done using the F matrix in the current implementation of `symeig_backward`.

Checking any property of  a CUDA tensor's values requires a synchronization between the CUDA device and the CPU since the result has to be sent to the CPU.

**Comment by mfkasim1** [comment] 2020-11-11 07:26
Ah, thanks for the clarification! 
How about adding a new argument in `symeig`, for example `degen_threshold`: the maximum value for absolute difference of two eigenvalues to be regarded as equal.
If it's < 0, it'll use the current backward (faster, but unstable for degenerate case).
Otherwise, it'll use the stabilized backward (slower, but more stable for degenerate case).

It also solves the problem on how to compare eigenvalues and maintains the backward compatibility by setting default value < 0.

**Comment by mruberry** [comment] 2020-11-12 07:05
That's an interesting idea, @mfkasim1. I think I'll need more time to understand this problem better, however, before I can credibly comment about what the right fix might be. I've added the "needs design" label to this issue.

**Comment by mfkasim1** [comment] 2020-11-12 12:10
@mruberry I have written several rough implementation options and show on which case they work and they don't: https://colab.research.google.com/drive/1wyt3357g8J91PQggLh8CLgvm4RiBmjQv

**Comment by ezyang** [comment] 2020-11-13 19:38
Thank you for the colab, it is very instructive. I indeed agree that symeig1 doesn't synchronize, but symeig2 does.

**Comment by ezyang** [comment] 2020-11-13 19:44
I'm still digesting the colab, but I had one other quick question: would it be useful to have a case of something like "yes it's degenerate, but trust me, we didn't depend on the degenerate eigenvectors", as opposed to directly checking for it as you do in symeig2.

**Comment by mfkasim1** [comment] 2020-11-13 21:21
> I'm still digesting the colab, but I had one other quick question: would it be useful to have a case of something like "yes it's degenerate, but trust me, we didn't depend on the degenerate eigenvectors", as opposed to directly checking for it as you do in symeig2.

It'd be still useful, at least in my case.
If the loss function depends on which linear combinations of eigenvector, they shouldn't expect any gradient anyway.

**Comment by ezyang** [comment] 2020-11-16 19:52
OK. I'm not an expert in linear algebra here, but it seems to me that we can have our cake and eat it too by simply assuming that, IF there are degenerate eigenvectors, then the loss function must not depend on it (otherwise, this is undefined behavior). The main downside of this approach is that it might cover up problems when you DID depend on the degenerate eigenvectors, but this is something that you could offer as an optional debugging check, sort of like how anomaly checking is turned on optionally. cc'ing @albanD for a second opinion here. I will have to lean on your expertise here, as to how likely a user is to make this error.

My primary constraint here is, my impression is most of the time people who are doing symeig aren't going to be dealing with degenerate eigenvalues, and as such I'd like to avoid slowing them down with an extra synchronization. I'm OK with doing extra unsynchronized work in the backwards though.

All this is a long way to say, this sounds good, please send us a PR, we'd appreciate it!

**Comment by albanD** [comment] 2020-11-17 17:44
@mfkasim1 thanks for the great colab!
I find it a bit surprising there that the `grad_eival` argument is never used in your backward formulas. Is that expected?

As a general rule, gradients formulas should return the right thing or raise an error.
Unfortunately, for these complex linear algebra primitive, checking if the backward is valid can be as expensive (if not more) than the backward computation itself.
So I am happy to relax a little bit this rule here. In particular, `qr` has the same approach with a big warning in the doc stating that some cases will lead to wrong gradients.

So my answer would be that most of the users for these functions are power users that know what they're doing and so if the check is too expensive, I am happy with only having the doc stating which cases are valid.
I also think that we could extend the anomaly detection mode to perform some of these checks yes!

**Comment by mfkasim1** [comment] 2020-11-17 19:29
Great, thanks for all your suggestions.

> I find it a bit surprising there that the `grad_eival` argument is never used in your backward formulas. Is that expected?

I intentionally left it to keep the code simple. The contribution from `grad_eival` is not problematic, even if there is degeneracy and the loss function fully depends on the degenerate eigenvectors.
It's only the contribution from `grad_eivec` that causes the problem.

Now the question is: how should we decide the threshold of two eigenvalues to be called "degenerate"?
I'm thinking of adding one argument in `torch.symeig`, say `degen_threshold` to be specified by the user.
If `degen_threshold < 0`, it doesn't have any special treatment on the degenerates (i.e. like the current computation) for backward compatibility.
If `degen_threshold >= 0`, then it uses the same algorithm as `symeig1` in the colab.

**Comment by albanD** [comment] 2020-11-17 19:43
> I intentionally left it to keep the code simple. 

What I was expecting, thanks for the confirmation.

> how should we decide the threshold of two eigenvalues to be called "degenerate"?

How close do they actually need to be for the backward to be bad?
Because if they are far enough (even if it is only due to numerical precision), the backward will work fine no?

> I'm thinking of adding one argument in torch.symeig

I am not a fan of adding backward specific args to the function.
Using anomaly mode to switch between the implementations should be good as well (especially if the threshold does not need to be user-tuned).

**Comment by mfkasim1** [comment] 2020-11-18 11:25
> How close do they actually need to be for the backward to be bad?
Because if they are far enough (even if it is only due to numerical precision), the backward will work fine no?

I'm not sure, I have to do some tests to see this, but I guess it's something proportional to `finfo(dtype).eps * input.shape[-1]`.
I'll let you know once I have it.

**Comment by Lezcano** [comment] 2021-03-17 09:08
Moving here the discussion that started here: https://github.com/pytorch/pytorch/pull/50942#issuecomment-800269453
I'm answering now comment https://github.com/pytorch/pytorch/pull/50942#issuecomment-800452030

That part I understand and agree with. What you are saying when you say that the function should be invariant under transformations by an orthogonal matrix is equivalent to saying that the function should descend from the Stiefel manifold into the Grassmannian. As mentioned before, I think that the formulae that you deduced in that MO post are exactly formulae that spell this out in terms of the eigenvectors of the matrix.

What I do not understand is whether the function that you are defining is actually differentiable, and if it is, in what sense it is. Let me be a bit more formal here.

Consider the 2-parameter family of matrices given in Section 4.2 of the second paper I cited, 

"The Geometry of Algorithms with Orthogonality Constraints" by Edelman, Arias and Smith.
https://arxiv.org/pdf/physics/9806030.pdf

This family are the "traceless 2x2 symmetric matrices", that is, matrices of the form `[[a, b], [b, -a]]`. As it says in the paper, this family of matrices have eigenvalues that are symmetric around zero, with the positive one being `\lambda_1 = (a^2 + b^2)^{1/2}`.
Furthermore, the first of the eigenvectors is of the form `v_1 = (cos(t/2), sin(t/2))`, for `tan(t) = y/x`. As such, we see that at `t=0` we have exactly the same singularity that we find when we change from cartesian coordinates to polar coordinates. This is very well explained in the paper, I very much recommend reading section 4.2 to understand this better. There's also a picture of this in Section 2 of the first paper I cited:

Jan R. Magnus On Differentiating Eigenvalues and Eigenvectors Econometric Theory, 1, 1985, 179-191
https://www.janmagnus.nl/papers/JRM011.pdf

Now, as there is a singularity there, things stop being differentiable, so the rules from differential calculus stop applying. The chain rule no longer holds (or at least the one I know for differentiable manifolds).

Now my question is the following:

> Prove **mathematically** (with hypotheses and saying where one uses them in every step) that the function that you are defining (for example the one that you used in this example via the trace) is in fact differentiable with respect to a and b for the matrix  `A = [[a,b], [b, -a]]`.

This is a calculus problem, as the function that takes a matrix `A` into `R` is an honest function from `R^2 -> R`. What I am asking you is to please prove that this function is indeed differentiable, as I am not sure that it is.

Again, I am not saying that your derivations are wrong, I just would like to understand them better, as my background in algebraic geometry, where these singularities are studied, is basically nonexistent :)

**Comment by mfkasim1** [comment] 2021-03-17 09:50
@Lezcano I might not be able to do formal derivation mathematically up to the standard you want as I am not trained to do that as a physicist.
If talking mathematically, maybe the case considered in this issue and PR is not where `a = b = 0`, but more like taking the limits of `a -> 0` and `b -> 0`, just like the case of `sin(x)/x` (undefined value for `x=0`, but equals to 1 when `x -> 0`).

The derivation from the matrix to `a` and `b` with the limit might be very large, but when combined with the gradient from the loss function (which must be independent of the `U -> UW` transformation), then the gradient of loss function w.r.t. `a` and `b` becomes finite.

If there are still things you want to discuss, why don't we move it to online meeting and post our conclusion here? I can contact you via email.

**Comment by Lezcano** [comment] 2021-03-17 10:12
The problem is that it is not like the case of `sin(x)/x`. That's a removable singularity. If it was like that, I would agree that your solution is the right one, but due to the analysis in those two papers, I believe it is not removable.

The singularities that we find here are a much wilder version of the one that we find in `relu`. The one in `relu` is tamer, as it is isolated, but the ones that we find here are not. We have to be able to really understand what we are working with to be able to come up with a correct solution.

At the moment I am moving cities, so I won't be able to arrange a call. I think I'll be able to call in a couple weeks.

In the meantime, even if you are not able to come-up with a formal proof up to mathematical standards, I would still suggest that you give it a go and see how far you can get. You can start from the definition of differentiability of a function in two variables from any undergrad calculus book (this is also treated in books for physicists) and try to work your way from there. I would be happy to look at your derivations and help in a few weeks :). Otherwise, it might be interesting to prod your closest mathematician and ask them for a bit of help. But again, I'd very much encourage you to give it a go, even more so given that you have uploaded a preprint to the arXiv.

**Comment by mfkasim1** [comment] 2021-03-17 10:24
I've tried my best on my arxiv paper: https://arxiv.org/pdf/2011.04366.pdf (it is written in a physics style)
Can you point out the mistake on the paper?

**Comment by Lezcano** [comment] 2021-03-17 10:52
I do not, and I do not have the time to find it (again, if there is any, it might very well be right). I will spend some time on this in a couple weeks.

On the more philosophical side, I believe it is the job of the person that writes the paper to show that everything in it is correct, not of the reviewer to prove that it is not wrong (at least it is this way when reviewing conferences and journals). Having said this, I repeat that I will be happy to help, I just do not have the time right now. I very much encourage you to try to prove or disprove the issue I raised above. We can then see how far you got, and we can try to make everything formal, so that we both understand better what's really going on here.

**Comment by Lezcano** [comment] 2021-04-02 13:51
After quite a lot of thinking, I think I understand a bit better what's going on here. I'm going to explain it here trying to give as much geometric intuition as I can. To do that, I will start with some very basic linear algebra facts. These are the "linearised" counterparts of the non-linear picture, so having a good understanding of these is important.

I will try be deliberately thorough, building up from the simpler concepts, so that this post is also readable for non-specialists. I will do this because the ideas here apply to all the matrix factorisation operations. As such, it would be good to have a good understanding of these problems to be able to give a consistent solution throughout PyTorch. What I really mean here is: sorry in advance for the very long post.

We will denote the canonical basis of Rⁿ by e₁, ..., eₙ. Let n ≥ k.

**Geometric interpretation of the rank of a matrix**
Let A ∈ Rⁿˣᵏ with columns a₁, ..., aₖ  ∈ Rⁿ. This matrix is the representation of an application T_A : Rᵏ → Rⁿ such that T_A(eᵢ) = aᵢ for i = 1, ..., k. In particular, T_A maps Rᵏ to the linear subspace generated by its columns span(a₁, ..., aₖ) ⊆ Rⁿ. This can be then thought as mapping its domain Rᵏ onto some subspace of Rⁿ. Since this subspace is generated by k vectors a₁, ..., aₖ, it will have dimension at most k, but it may have lower dimension. For example, if k=2 and n=3, T_A maps R² to a plane or a line of R³ going through 0. It may also map the whole R² to zero if A is the zero matrix.

Note: All that I'm going to say in the following two paragraphs can be seen very neatly assuming that one has an SVD A=UΣVᵀ and looking where the vectors e₁, ..., eₖ are mapped when applying first Vᵀ then Σ and finally U.

The rank of a matrix is the number of linearly independent columns of a matrix. Given the interpretation above, geometrically, the rank is the dimension of the image of T_A. Full-rank matrices (for n ≥ k) are matrices where the dimension of its image is k. In other words, they map the space Rᵏ to a subspace V ⊂ Rⁿ of dimension k. For example, in the case of k=2, n=3, they map the plane R² to a plane of R³. If a matrix is full rank, it acts as a (linear) isomorphism onto its image. This means that there exists an inverse (T_A)⁻¹ that maps the linear subspace V = Im(T_A) back to Rᵏ such that (T_A)⁻¹(T_A(x)) = x  for every x ∈ Rᵏ. If we say that (T_A)⁻¹ acts like that on Im(T_A), and sends any vector that's not on the image of T_A to zero, then the map that we get is the Moore-Penrose pseudo-inverse. [More on that here](https://en.wikipedia.org/wiki/Moore%E2%80%93Penrose_inverse#Geometric_construction`_).

If the matrix is not full-rank the picture is similar. When A is of rank r < k, what happens is that the domain Rᵏ is split into two subspaces Rₖ = U₁ ∪ U₂ with U₁ of dimension r and U₂ of dimension k-r. These split has the property that U₂ is mapped entirely to zero (this is often called the kernel of T_A). On the other hand, T_A is an isomorphism and maps the space U₁ of dimension r to Im(T_A) (which is also of dimension r by hypothesis). With the SVD decomposition in hand, it is direct to see that the space U₂ is the space generated by the singular vectors of V with singular value zero, and the space U₁ is generated by the other singular vectors of V. In the example of n=3, k=2, when T_A has rank 1 it means that one column is a multiple of the other. In the simplest case when a₁ = a₂, we see that U₁ = {(t, −t) | t ∈ R}, U₂ = {(t, t) | t ∈ R} and Im(T_A) is the line {t a₁ | t ∈ R} ⊂ R³.

Important point to remember until now: Full-rank matrices do not "forget" any dimensions, while low-rank matrices reduce the dimension.

From here on, we will use M(n, k, r) with n ≥ k ≥ r to denote the nxk matrices of rank r. Thus, the space of full-rank matrices is M(n, k, k)

**The (compact) QR decomposition**
We will not comment on the symmetric eigendecomposition until later, as the problem that happens there is more difficult. We will start with the QR as a warm-up, as it is easier to see what is going on.

We denote the space of matrices with orthonormal columns by St(n,k) = {X ∈ Rⁿˣᵏ | Xᵀ X = Iₖ}, and the space of kxk upper triangular matrices with strictly positive diagonal by Triu⁺(k). If a matrix is full-rank, it has a unique compact QR decomposition. In other words, we have that the map `qr` : M(n, k, k) → St(n,k) x Triu⁺(k) with `qr`(A) = (Q, R) is a bijection with inverse the matrix multiplication (Q, R) ↦ QR ((see here for example)[https://www.math.purdue.edu/~kkloste/cs515fa14/qr-uniqueness.pdf). Even more, by going through the derivation of the formulas for the gradient of the `qr` decomposition, one sees that this map is a diffeomorphism (it is differentiable with a differentiable inverse) on this domain.

What happens if the matrix is not full rank? Imagine that we have a matrix A of rank k-1. By the discussion above, if we look at it as a map T_A from Rᵏ into Rⁿ, we have that Rᵏ = U₁ ∪ U₂ with U₂ a subspace of dimension one (a line) mapped to zero, and U₁ of the same dimension as the image of T_A. We may change the basis of the domain Rᵏ so that the first k-1 vectors e₁, ..., eₖ₋₁ are mapped to the image and the last vector eₖ  is mapped to zero. To do this, consider a compact SVD A = UΣVᵀ with Σ having strictly decreasing eigenvalues and consider the matrix Ã := AV = UΣVᵀV = UΣ. We see that Ã is a matrix that maps eₖ to zero (as the last singular value is zero due to the rank k-1 hypothesis), so the map T_Ã is simply T_A in the base V. We may now represent the restriction of T_Ã to U₁ as an isomorphism onto its image by taking Ã = UΣ and deleting the zero singular value and the associated left-singular vector uₖ. Denote these by U', Σ'. A'=U'Σ' is a (n-1)x(k-1) full-rank matrix by A'. Since A' is full rank, we have a unique QR decomposition. Conveniently, U' Σ' constitute a QR decomposition of A', and since it is unique, `qr`(A') = (U', Σ'). For the same reason, `qr`(Ã) = (U, Σ), but in this case it is not unique, as we may replace uₖ by -uₖ.

If the rank is k-2, it's the same story, but in this case we may choose any two vectors that span the kernel of A to complete the Q part of `qr`(Ã). As such, this case is even worse, as it isn't unique, but it is also not locally unique (there are matrices Q₁, Q₂ that are very close together and both constitute QRs of Ã. This is problematic.

**The relation of all this and the PR linked to this issue**
Now, what the PR linked to this issue suggests geometrically is that we should compute the derivative of the eigenvalues in the part that we know how to do it because it is a diffeomorphism (so it is well-defined) and then extend that derivative to be zero everywhere else. This is sensible at times, but it is not sensible at others, as we will see now.

**Non-differentiability of factorisations at low-rank matrices**
From now on, the writing is going to get slightly more technical, but bear with me. This is necessary to explain what's going on geometrically. What's happening here behind the scenes is the following:
The set of matrices of matrices of size n x k with rank exactly r M(n, k, r) is actually a manifold. As such, we may decompose Rⁿˣᵏ as the disjoint union Rⁿˣᵏ = ⋃ᵣ M(n, k, r). This is what's called a stratified space. The formal definition of a stratified space is very technical, but the intuition behind it is what the name suggest. It is a layered space where each layer is a manifold and some extra properties so that the joints are not too wild. Before continuing, it is worth mentioning that M(n, k, r) for r < k is a disconnected manifold with plenty of components (k choose r components to be precise)

Now, we can think of the points at which a strata M(n,k,r) intersects a lower strata, say M(n,k,r-1), as something as follows:
![image](https://user-images.githubusercontent.com/3291265/113421356-d9167c00-93c2-11eb-9ae6-52bf0b5b94fa.png)


As we can see, we have a sphere and a plane intersecting. We could think that the sphere and the plane are part of the higher dimensional strata, and the circle on which they intersect as the lower-dimensional one. If we have a map defined on the whole space (on the stratified space, as it is our `qr` decomposition or `symeig` for the matter), at one of those intersection points, it is not clear whether its differential should be defined on a neighbourhood lying on the plane, on the sphere or the circle.

(nb. The general case of the intersection of one strata with a lower-dimensional one is _much_ wilder. This figure is just to give some intuition).

What this PR suggests (and what doing what we described in the part of the QR decomposition would account for) is to choose the differential on the lowest strata possible, in this case, the circle.

Now, what it is currently implemented is that, if a gradient descent algorithm comes from points on the sphere, it will compute the gradient on a neighbourhood of the sphere. Same if the previous gradient descent points were on the plane, then it would compute it on the plane.

The incorrect gradients come from asking the autograd "what's the gradient along the circle?" (i.e., it's computing the gradient on a low-dimensional strata).

**What to do?**
Alas, there's no right or wrong answer. One will work for some cases, one will work for others. The stratified space in question is not a manifold (it's an algebraic variety), so there is no well-defined notion what is differentiable and what is not. There is no notion of a differential (nor adjoint, nor "gradient" how it is called in PyTorch). Summarising, we just have to choose the behaviour that we want.

For one, the behaviour suggested by @mfkasim1 is actually very useful when using these factorisations in neural networks. I found the QR problem some time ago in a practical application of my library [GeoTorch](https://github.com/Lezcano/geotorch), when doing orthogonal constrained optimisation in neural networks (see https://github.com/pytorch/pytorch/issues/42792). This approach also solves the `NaN`s problem that appears if you happen to hit a gradient with two eigenvalues that are exactly the same .

On the other hand, this approach presents several issues over the more naïve one:
- Implementing this approach is more expensive.
- It might bite the user. In particular, the gradient of `symeig` or `qr` at the matrix zero is always zero, so it would seem like it's not updating this matrix. This was in fact the case that I found in GeoTorch.
- The problem of hitting a matrix with two exactly equal eigenvalues is terribly difficult if not done by construction. This is because there are numerical errors, and  matrices on which `symeig` is not differentiable have measure zero across all matrices.
- The gradient would become dis-continuous at those points (similar to that of `relu`).

**What I would suggest**
- I'd be keen on having this behaviour, but just as opt-in
- In order to determine the rank of the matrix and similar measures, we would have to pass an `atol` and `rtol` to the main function, but I guess this is already done for functions such as `matrix_rank` so that's fine.
- We would have to implement some other forward algorithms that allow for this. In the case of the QR for example, we would have to implement QR with Pivoting (see https://github.com/pytorch/pytorch/issues/10454).
- Definitely not for 1.9

**Comment by Lezcano** [comment] 2021-08-30 10:22
This behaviour is now documented in `torch.linalg.eigh` and is expected.

Closing this issue in favour of https://github.com/pytorch/pytorch/issues/57272 which tracks all these differentiability issues for matrix functions.

**Closed by Lezcano** 2021-08-30 10:22 UTC
Labels: high priority, module: autograd, triaged, module: linear algebra, needs design, module: correctness (silent)
