### ISSUE TITLE
Defaulting to ninja build doesn't forward includes in PyTorch C++/CUDA extensions

### ISSUE THREAD

**Issue by meder411** [pytorch/pytorch#37707] opened 2020-05-02 03:40 UTC
## 🐛 Bug

The new default setting of trying to use ninja to build extensions faster breaks existing C++/CUDA extensions. The reason appears to be that it does not forward the include directories specified to `CppExtension` or `CUDAExtension` classes to the ninja compiler properly.

It's also not well documented how to pass `use_ninja=False` to the basic `BuildExtension` (as given in the C++/CUDA tutorial) in order to workaround this issue. For anyone who comes across this issue, you can use `cmdclass={'build_ext': BuildExtension.with_options(use_ninja=False)}` in the `setup` function (as seen in [this test](https://github.com/pytorch/pytorch/blob/11a40410e755b1fe74efe9eaa635e7ba5712846b/test/cpp_extensions/setup.py#L62)).

## To Reproduce

I've [forked the c++/cuda extension tutorial code](https://github.com/meder411/extension-cpp) and modified it to demonstrate this issue. All I've done is added an empty file `tmp.h` in an `includes` directory and tried to include it in `lltm_cuda.cpp` relative to that `includes` directory, which is specified in the `setuptools` extension.

1. Clone the linked repo above
2. In the `demo` directory, run `python setup_no_ninja.py build`. Everything is copacetic (well, tons of warnings because the tutorial uses an old version of PyTorch, but no errors, and it compiles just fine).
3. Run `python setup_ninja.py build` and you should get:

```
 python3 setup_ninja.py build
running build
running build_ext
building 'lltm_cuda' extension
Emitting ninja build file /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/build.ninja...
Compiling objects...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/lltm_cuda.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -Iincludes -I/usr/include/python3.6m -c -c /playpen/extension-cpp/demo/lltm_cuda.cpp -o /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/lltm_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=lltm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
FAILED: /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/lltm_cuda.o 
c++ -MMD -MF /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/lltm_cuda.o.d -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -Iincludes -I/usr/include/python3.6m -c -c /playpen/extension-cpp/demo/lltm_cuda.cpp -o /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/lltm_cuda.o -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=lltm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
/playpen/extension-cpp/demo/lltm_cuda.cpp:2:10: fatal error: tmp.h: No such file or directory
 #include "tmp.h"
          ^~~~~~~
```

## Expected behavior

The ninja build should compile in the same way as the `setuptools` build.

## Environment

This is fairly environment agnostic although I used the demo code from the CUDA extensions, so CUDA is necessary to replicate with the code provided. FWIW, I'm using CUDA 10.1 with PyTorch 1.5.0 and the latest numpy version.

## Additional context

To confirm it's not a ninja issue in general, you can run `python jit.py` in that same directory and see that the JIT compilation strategy works just fine with ninja. There, I have added the include directory using the keyword argument `extra_include_paths=['includes']`.

The `build.ninja` files emitted differ between the JIT call and the setuptools call.

From JIT:

```
ninja_required_version = 1.3
cxx = c++
nvcc = /usr/local/cuda/bin/nvcc

cflags = -DTORCH_EXTENSION_NAME=lltm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -I/playpen/extension-cpp/demo/includes -isystem /usr/local/lib/python3.6/dist-packages/torch/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.6/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14
post_cflags = 
cuda_cflags = -DTORCH_EXTENSION_NAME=lltm_cuda -DTORCH_API_INCLUDE_EXTENSION_H -I/playpen/extension-cpp/demo/includes -isystem /usr/local/lib/python3.6/dist-packages/torch/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -isystem /usr/local/lib/python3.6/dist-packages/torch/include/TH -isystem /usr/local/lib/python3.6/dist-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /usr/include/python3.6m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_61,code=sm_61 --compiler-options '-fPIC' -std=c++14
cuda_post_cflags = 
ldflags = -shared -L/usr/local/lib/python3.6/dist-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda -ltorch -ltorch_python -L/usr/local/cuda/lib64 -lcudart

rule compile
  command = $cxx -MMD -MF $out.d $cflags -c $in -o $out $post_cflags
  depfile = $out.d
  deps = gcc

rule cuda_compile
  command = $nvcc $cuda_cflags -c $in -o $out $cuda_post_cflags

rule link
  command = $cxx $in $ldflags -o $out

build lltm_cuda.o: compile /playpen/extension-cpp/demo/lltm_cuda.cpp
build lltm_cuda_kernel.cuda.o: cuda_compile /playpen/extension-cpp/demo/lltm_cuda_kernel.cu

build lltm_cuda.so: link lltm_cuda.o lltm_cuda_kernel.cuda.o

default lltm_cuda.so
```

From `setuptools`:

 ```
ninja_required_version = 1.3
cxx = c++
nvcc = /usr/local/cuda/bin/nvcc

cflags = -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -Iincludes -I/usr/include/python3.6m -c
post_cflags = -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=lltm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -std=c++14
cuda_cflags = -I/usr/local/lib/python3.6/dist-packages/torch/include -I/usr/local/lib/python3.6/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.6/dist-packages/torch/include/TH -I/usr/local/lib/python3.6/dist-packages/torch/include/THC -I/usr/local/cuda/include -Iincludes -I/usr/include/python3.6m -c
cuda_post_cflags = -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options '-fPIC' -DTORCH_API_INCLUDE_EXTENSION_H -DTORCH_EXTENSION_NAME=lltm_cuda -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_61,code=sm_61 -std=c++14
ldflags = 

rule compile
  command = $cxx -MMD -MF $out.d $cflags -c $in -o $out $post_cflags
  depfile = $out.d
  deps = gcc

rule cuda_compile
  command = $nvcc $cuda_cflags -c $in -o $out $cuda_post_cflags



build /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/lltm_cuda.o: compile /playpen/extension-cpp/demo/lltm_cuda.cpp
build /playpen/extension-cpp/demo/build/temp.linux-x86_64-3.6/lltm_cuda_kernel.o: cuda_compile /playpen/extension-cpp/demo/lltm_cuda_kernel.cu
```

In the JIT `build.ninja` file, you can see that `-I/playpen/extension-cpp/demo/includes` is added in both `cflags` and `cuda_cflags`, while it is conspicuously absent from the `build.ninja` file emitted during the `setuptools` build.

cc @ezyang @gchanan @zou3519 @malfet @yf225 @glaringlee

**Comment by zou3519** [comment] 2020-05-05 21:12
Marking high-pri for regression

**Comment by glaringlee** [comment] 2020-05-05 22:47
Will take a look at this.

**Comment by glaringlee** [comment] 2020-05-06 20:26
@meder411
Thanks for pointing this out. 
I checked your example, there are 2 things here:
1. It seems that you put the 'include_dirs' at a wrong place, 'include_dirs' should be specified inside the CUDAExtension (ie, each Extension should have its own include_dirs if any). 
2. It turns out for jit build, it support relative path only while setuptools build support absolute path only which is not consistent here. I'll make change to CUDAExtension and CPUExtension to support relative path as well, but standard way will still be absolute path for setuptools since that's what standard library supported. 

The correct setup.py for your case should be:
```
setup(
    name='lltm_cuda',
    ext_modules=[
        CUDAExtension('lltm_cuda', [
            'lltm_cuda.cpp',
            'lltm_cuda_kernel.cu'],
            include_dirs=['/playpen/extension-cpp/demo/includes']
        ),
    ],
    cmdclass={
        'build_ext': BuildExtension
    })
``` 

It works for me, let me know if it works for you.

**Comment by meder411** [comment] 2020-05-06 20:36
Ah whoops. So the `include_dirs` misplacement is a bug in the minimal example. My bad on that. However, it is specified in the correct place in my actual code base. Did you find that simply making that change worked? If so, I can't seem to replicate that.

Could you elaborate a little more about the relative path issue? I have only ever been providing relative path include directories to `CUDAExtension` and never had an issue.

**Comment by glaringlee** [comment] 2020-05-06 22:51
@meder411
The include_dirs in setuptools accept absolute path, means you have to provide a path that start from your linux root. 
eg. let's say you have an 'includes' folder at '/usr/abc/includes' with tmp.h inside, and you are currently at /usr/abc and start to build your cpp extension. Your absolute path for  'includes' folder is /usr/abc/includes, and your relative path is includes. You have to provide the absolute path here to make sure your build will work, since the setuptools won't translate your relative path into absolute path. If you provide relative path, say you provide 'includes', then the standard build method won't work, say you run 'python setup.py install', it will create a folder /usr/abc/build/temp**** and do the compile there, now the relative folder 'includes' won't point to the correct location where the 'tmp.h' located at, since where the compile really happen is not /usr/abc, but /usr/abc/build/temp****. 

I am not sure how you make it work by providing relative path (jit works since it always translate relative path to absolute path, but it won't work in you provide absolute path directly), if you can update your repo, I can check.

**Comment by meder411** [comment] 2020-05-06 23:11
@glaringlee Sorry for the confusions. I understand the difference between absolute and relative paths. I wasn't understanding why you were saying using a relative path in the `CUDAExtension` or `CppExtension` instantiation shouldn't work. I've been doing that for the better part of 18 months now and haven't had an issue. 

I've updated the repo with the correct specification of `include_dirs`, but using a relative path.

**Note:** I don't have access to my machine with CUDa at the moment, so I've also modified the install to use `CppExtension` instead. I don't think it should make a difference though.

If you run `python setup_no_ninja.py build` it should work just fine.

**Comment by glaringlee** [comment] 2020-05-07 00:51
@meder411 
I did a depper check, here is what I have right now:

1. Why setuptools ninja compile need absolute path (at this point)?
The ninja and no-ninja has a totally different compile logic in our implementation.  no-ninja version works fine with relative path but ninja version doesn't. Here is why,
For no-ninja logic, we build the code inplace and put the .o file into 'build' folder, so the relative folder works since the build happened inplace, while for ninja logic, we put the build.ninja file into 'build' folder and build from there, that's why relative path won't work since the build root folder changed.

2. For ninja version compile,  'include_dirs' works at either location below as long as you give the absolute path. But I suggest you put include_dirs inside CUDAExtension for now.

```
setup(
    name='lltm_cuda',
    ext_modules=[
        CUDAExtension('lltm_cuda', [
            'lltm_cuda.cpp',
            'lltm_cuda_kernel.cu']
            include_dirs=['absolute path to demo/includes']
        ),
       #include_dirs=['absolute path to demo/includes']
    ],
    cmdclass={
        'build_ext': BuildExtension
    })
```

3. To make it consistent with JIT extension build and 'no ninja' version of setuptools build, I will put a fix to support relative path for 'include_dirs' outside CUDAExtension/CPUExtension. So you can go back to use relative path later (or just keep using absolute path witnin CUDAExtension).
```
setup(
    name='lltm_cuda',
    ext_modules=[
        CUDAExtension('lltm_cuda', [
            'lltm_cuda.cpp',
            'lltm_cuda_kernel.cu']
        ),
       include_dirs=['includes']
    ],
    cmdclass={
        'build_ext': BuildExtension
    })
``

Will update here once the fix landed.

**Comment by meder411** [comment] 2020-05-07 01:00
@glaringlee Thanks for digging into this!

**Comment by glaringlee** [comment] 2020-05-14 03:45
include_dirs now support both absolute and relative paths.

**Closed by glaringlee** 2020-05-14 03:45 UTC
Labels: high priority, module: build, module: cpp-extensions, topic: regression, triaged
