### ISSUE TITLE
Install from Source Error on Ubuntu16

### ISSUE THREAD

**Issue by zeakey** [pytorch/pytorch#1107] opened 2017-03-26 14:12 UTC
### Error message:
```
Scanning dependencies of target TH
[  5%] Building C object CMakeFiles/TH.dir/THGeneral.c.o
[ 10%] Building C object CMakeFiles/TH.dir/THHalf.c.o
[ 15%] Building C object CMakeFiles/TH.dir/THAllocator.c.o
[ 21%] Building C object CMakeFiles/TH.dir/THStorage.c.o
[ 26%] Building C object CMakeFiles/TH.dir/THTensor.c.o
cc: internal compiler error: Killed (program cc1)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions.
CMakeFiles/TH.dir/build.make:146: recipe for target 'CMakeFiles/TH.dir/THTensor.c.o' failed
make[2]: *** [CMakeFiles/TH.dir/THTensor.c.o] Error 4
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/TH.dir/all' failed
make[1]: *** [CMakeFiles/TH.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
```
#### GCC
```
gcc --version
gcc (Ubuntu 5.2.1-22ubuntu2) 5.2.1 20151010
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
#### CMAKE
```
cmake --version
cmake version 3.2.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```
#### Python
```
python --version
Python 2.7.10
```

**Comment by apaszke** [comment] 2017-03-26 14:29
It seems that the kernel has killed the compiler because it ran out of memory. How much free RAM do you have?

**Comment by zeakey** [comment] 2017-03-26 14:32
@apaszke Thanks for your quick reply. Actually I'm on a VPS that has 1G RAM, I don't think the RAM is the matter, BUT My 'swap' is not enough, So is it the matter of 'swap' ?

**Comment by apaszke** [comment] 2017-03-26 14:34
It's possible that 1G is not enough. It is a matter of RAM, because if you had more you wouldn't need any swap space. You need to increase the size of either of them. I'm closing this, because it's not a bug, but a problem with your system configuration and memory requirements of the used compiler.

**Closed by apaszke** 2017-03-26 14:34 UTC

**Comment by zeakey** [comment] 2017-03-26 14:38
@apaszke OK, thank you anyway.

I will try to install from the built binary as official document introduced.
