### ISSUE TITLE
Unable to autocomplete the code for some functions such as torch.zeros() etc.

### ISSUE THREAD

**Issue by CoderLiMing** [pytorch/pytorch#12987] opened 2018-10-23 14:58 UTC
I just started learning PyTorch, but it is puzzling that neither Pycharm nor VS Code can automatically complete the code for some functions, such as torch.empty(), torch.zeros(), etc. 
Can you give me some advice?
Thanks~ o(*￣︶￣*)o

**Comment by soumith** [comment] 2018-10-23 16:05
duplicate of https://discuss.pytorch.org/t/code-autocomplete-problem/27864 and https://github.com/pytorch/pytorch/issues/7318

fixes are being tracked in #7318

**Closed by soumith** 2018-10-23 16:05 UTC
