### ISSUE TITLE
RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict

### ISSUE THREAD

**Issue by olgapeled** [pytorch/pytorch#13040] opened 2018-10-24 09:31 UTC
Hi All,

I am trying to convert yolo2 pytorch to onnx model and I got:
"RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict"

This is the code example:
https://github.com/purelyvivid/yolo2_onnx/blob/master/1.yolo2_pytorch_onnx_save_model.ipynb

Any ideas?

cc @suo

**Comment by vince62s** [comment] 2018-11-09 16:16
same issue.
Is there any plan to support dict in ONNX ?
thanks to let us know.

**Comment by DJNing** [comment] 2019-01-16 09:49
same problem here, any solution now?

**Comment by wangshankun** [comment] 2019-05-16 13:05
same problem here， Centernet to onnx

**Comment by liuchang8am** [comment] 2019-05-17 00:33
Solved.Just change the output of your model from dict to list.

**Comment by cwjhx** [comment] 2019-05-25 08:51
> Solved.Just change the output of your model from dict to list.

same problem , Centernet to onnx. "change the output of your model from dict to list".How should I  change it ?

**Comment by zhyj3038** [comment] 2019-06-10 04:00
@wangshankun  @cwjhx  same problem. centernet to onnx. how u gays solved it? thanks!

**Comment by sivaprasadraju** [comment] 2019-06-14 07:56
> @wangshankun @cwjhx same problem. centernet to onnx. how u gays solved it? thanks!
> 
> SOLVED！

How did you change the output of model from dict to list? Thanks!

**Comment by zhyj3038** [comment] 2019-06-14 08:44
modify the original code which using  __setattr__  and __getattr__, it will generate dict . just using a list to gather 'hm', 'reg' and 'wh' layers.


 
---Original---

**Comment by westpilgrim** [comment] 2019-06-18 11:57
> modify the original code which using __setattr__ and __getattr__, it will generate dict . just using a list to gather 'hm', 'reg' and 'wh' layers.
> […](#)

how did you modify this?could you give some sample code?

**Comment by westpilgrim** [comment] 2019-06-19 07:31
I modify dlav0.py line 615 - 618 to :
        ret = []
        for head in self.heads:
            ret.append(self.__getattr__(head)(x))
        return [ret]

and convert to onnx successes.haven't test the model yet

**Comment by zhedasuiyuan** [comment] 2019-06-27 21:01
> modify the original code which using __setattr__ and __getattr__, it will generate dict . just using a list to gather 'hm', 'reg' and 'wh' layers.
> […](#)
> ---Original--- From: "Siva Prasad Raju"<notifications@github.com> Date: 2019/6/14 15:57:38 To: "pytorch/pytorch"<pytorch@noreply.github.com>; Cc: "zhang ya jun"<zhyj3038@qq.com>;"Comment"<comment@noreply.github.com>; Subject: Re: [pytorch/pytorch] RuntimeError: Only tuples, lists and Variables supported as JIT inputs, but got dict (#13040) @wangshankun @cwjhx same problem. centernet to onnx. how u gays solved it? thanks! SOLVED！ How did you change the output of model from dict to list? Thanks! — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

Hi, could you share more details or kindly share your changes on the code? Thanks!

**Comment by echan00** [comment] 2019-11-11 16:07
Yes, it would be nice if someone could off directions that will help here!

**Comment by visionandy** [comment] 2019-11-12 00:17
same problem here

**Comment by soumith** [comment] 2019-11-12 03:54
cc: @wanchaol @driazati because a couple of new responses in the last 24 hours

**Comment by echan00** [comment] 2019-11-12 04:00
More information to reproduce: https://github.com/pytorch/pytorch/issues/29551

**Comment by fujingling** [comment] 2019-11-27 04:29
upgrade your torch to 1.3.0, this problem will be resolved

**Comment by cpoptic** [comment] 2019-12-09 16:48
Currently running Torch 1.3.1 and this problem is definitely still a problem.  Upgrading to 1.3.x did not solve the problem at all.

**Comment by suo** [comment] 2019-12-10 19:32
@lara-hdr You added this capability to the ONNX converter, right? When was it released?

**Comment by lara-hdr** [comment] 2019-12-10 19:40
@suo, we added support for dicts in 1.3.0 https://github.com/pytorch/pytorch/pull/25889.
We only support it for ONNX and not jit.trace.
So calls to torch.jit.trace() will still give this error, but calls for torch.onnx.export() should work for PyTorch 1.3.0 and above.

**Comment by wangshuai66666** [comment] 2020-08-19 01:23
Solved.upgrade your torch to 1.3.0.

**Comment by spandantiwari** [comment] 2021-05-17 22:18
Closing now. Please reopen if the issue persists.

**Closed by spandantiwari** 2021-05-17 22:18 UTC
Labels: oncall: jit

**Comment by datouready** [comment] 2022-11-18 06:28
just read error tips, check your code,and fix it...

**Comment by fujingling** [comment] 2022-11-18 06:28
您好，邮件我已收到！
