### ISSUE TITLE
Can't ONNX export torch.jit.load-ed model

### ISSUE THREAD

**Issue by tsauri** [pytorch/pytorch#20096] opened 2019-05-03 07:15 UTC
## 🐛 Bug

```
  for j in range(seqlen):
Traceback (most recent call last):
  File "onnx_full_export.py", line 74, in <module>
    main()
  File "onnx_full_export.py", line 70, in main
    beam_search.save_to_db(args.output_file)
  File "/home/raden/translate/pytorch_translate/ensemble_export.py", line 1170, in save_to_db
    self.onnx_export(tmp_file)
  File "/home/raden/translate/pytorch_translate/ensemble_export.py", line 1130, in onnx_export
    export_type=ExportTypes.ZIP_ARCHIVE,
  File "/home/raden/anaconda3/lib/python3.7/site-packages/torch/onnx/__init__.py", line 19, in _export
    result = utils._export(*args, **kwargs)
  File "/home/raden/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/raden/anaconda3/lib/python3.7/site-packages/torch/onnx/utils.py", line 256, in _model_to_graph
    method.graph, tuple(args) + tuple(params), example_outputs, False, propagate)
RuntimeError: retval->inputs().size() == inputs.size() ASSERT FAILED at /pytorch/torch/csrc/jit/script/init.cpp:744, please report a bug to PyTorch. (_propagate_and_assign_input_and_output_shapes at /pytorch/torch/csrc/jit/script/init.cpp:744)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f6b9c93b441 in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f6b9c93ad7a in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x452376 (0x7f6bdbf5c376 in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #3: <unknown function> + 0x4793af (0x7f6bdbf833af in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x130fac (0x7f6bdbc3afac in /home/raden/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #31: __libc_start_main + 0xf0 (0x7f6beb660830 in /lib/x86_64-linux-gnu/libc.so.6)


```

## To Reproduce

Run onnx_full_export.py from https://github.com/pytorch/translate

## Environment
Pytorch 1.1 stable

**Comment by tsauri** [comment] 2019-05-08 03:34
#14869
bug since last year

**Comment by garymm** [comment] 2021-11-19 23:30
Duplicate of #14869

**Closed by garymm** 2021-11-19 23:30 UTC
Labels: oncall: jit, module: onnx, module: assert failure
