### ISSUE TITLE
INTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":263

### ISSUE THREAD

**Issue by LucaBonfiglioli** [pytorch/pytorch#67864] opened 2021-11-04 19:28 UTC
## 🐛 Bug

Sometimes - seems completely random to me - I get this `RuntimeError` when training any pytorch model.

## To Reproduce

Training any pytorch model with pytorch 1.10 (even a simple MLP on a toy classification task) sometimes results on this error. What's most strange is that the training works just fine, the model learns, the performance and the GPU memory usage are exactly as expected (compared to the previous version). It simply crashes, on a random iteration, which can be after hours of training.

Note that I am getting this error after upgrading to 1.10 from 1.9 and I am using code that is **thoroughly tested** and never had any issue of the sort. It was used in a production environment, for many trainings and for hundreds of hours without a single error.

```
Traceback (most recent call last):                                            
File "/usr/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
    obj = _ForkingPickler.dumps(obj)
File "/usr/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
File "/home/luca/venvs/dev/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_14497_2> in read-write mode 
```

## Expected behavior

Not getting a `RuntimeError`.

## Environment

```
PyTorch version: 1.10.0+113 
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A
OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 8.4.0-1ubuntu1~18.04) 8.4.0
Clang version: Could not collect
CMake version: version 3.19.2
Libc version: glibc-2.27
Python version: 3.8.0 (default, Feb 25 2021, 22:10:10)  [GCC 8.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-89-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 495.29.05
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.6.3
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.0
[pip3] pytorch-lightning==1.5.0
[pip3] pytorch-msssim==0.2.1
[pip3] segmentation-models-pytorch==0.2.0
[pip3] torch==1.10.0+cu113
[pip3] torchaudio==0.10.0+cu113
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.11.1+cu113
[conda] Could not collect
```

I found this similar issue, the error is different though, so I created a new one.
https://github.com/pytorch/pytorch/issues/67844

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @VitalyFedyunin

**Comment by malfet** [comment] 2021-11-08 18:07
Giving it a tentative 1.10.1 milestone

**Comment by ZaydH** [comment] 2021-11-11 16:49
FWIW, my code has been thoroughly tested with torch 1.6-1.9.  I only started seeing this error in 1.10 (specifically `1.10.0+cu111`).  I ran into the issue with a Tesla K80.

**Comment by ngimel** [comment] 2021-11-17 23:57
Can you please provide some instructions and scripts on how to repro the error?

**Comment by ZaydH** [comment] 2021-11-18 00:52
@ngimel In my case, it was highly non-repeatable.  My trains the same model multiple times for variance analysis.  In most instances, everything worked fine.  Occasionally it would report the error above (along with at least one other ATen assert).  I reverted back to `torch` 1.9.1 and have not seen it since.

**Comment by LucaBonfiglioli** [comment] 2021-11-18 11:06
Same here, I tried to isolate it but I could not, it's very time-consuming: code could run for 10 hours without a single error, then it crashes suddenly for seemingly no reason at all. Seems to happen with all our training scripts. I am not allowed to share the code, I will check if I can reproduce the bug with a boiled-down version of one of our training scripts and share it here.

As reported by @ZaydH, reverting to a previous pytorch version (1.8 in my case) solved the issue for me. Sort of solved, because I still need some 1.10 features, that's why I upgraded to 1.10 in the first place.

**Comment by malfet** [comment] 2021-11-18 14:40
@LucaBonfiglioli, can you please try setting `torch.multiprocessing.set_sharing_strategy("file_system")` to your code and see if it will solve the problem on 1.10?

**Comment by ZaydH** [comment] 2021-11-19 10:47
@malfet Our compute nodes are too loaded for me to replicate the previous setup I was using (K80).  I may be able to try on a debug workstation (RTX3090).  

Since you have a proposed solution, I assume you may have a hunch what is going wrong.  For the sake of this discussion (and me trying to replicate the issue on my debug machine) let's assume your hunch on the cause is right.  I then have two (hypothetical) questions: 

(1) I assume Python version is not relevant to the issue.  My debug station uses Python 3.7.1 and I did not see the same failure on that machine.  Our primary cluster where I saw the issue runs Python 3.6.5.

(2) Does GPU model at all affect this behavior?

**Comment by qgallouedec** [comment] 2021-11-19 17:09
For what it's worth, this code 

```python
import torch

buffers = []
for i in range(2000):
    print(i)
    buffers.append(torch.empty(size=(1,)).share_memory_())
```

gives 

```txt
0
1
[...]
1020
1021
Traceback (most recent call last):
  File "bug4.py", line 8, in <module>
  File "/home/qgallouedec/impact-driven-exploration/env/lib/python3.7/site-packages/torch/tensor.py", line 241, in share_memory_
  File "/home/qgallouedec/impact-driven-exploration/env/lib/python3.7/site-packages/torch/storage.py", line 114, in share_memory_
RuntimeError: unable to open shared memory object </torch_1556701_2897416291> in read-write mode
```

**Comment by qgallouedec** [comment] 2021-11-19 17:15
For what it's worth, this code

```python
import torch

buffers = []
for i in range(2000):
    print(i)
    buffers.append(torch.empty(size=(1,)).share_memory_())
```

always gives

```log
0
1
[...]
1020
1021
Traceback (most recent call last):
  File "bug4.py", line 8, in <module>
  File "/home/qgallouedec/impact-driven-exploration/env/lib/python3.7/site-packages/torch/tensor.py", line 241, in share_memory_
  File "/home/qgallouedec/impact-driven-exploration/env/lib/python3.7/site-packages/torch/storage.py", line 114, in share_memory_
RuntimeError: unable to open shared memory object </torch_1556701_2897416291> in read-write mode
```

is this related to this issue ?

- Ubuntu
- Python 3.7
- NVIDIA TITAN Xp
- Torch 1.1.0 (but also reproduced with 1.2.0 and 1.10.0)

**Comment by peterbell10** [comment] 2021-11-19 20:29
Your example is hitting the open file descriptor limit (default 1024 on my system). That could be the issue here, although that wouldn't explain why it only happens on the latest PyTorch release.

**Comment by malfet** [comment] 2021-11-19 20:59
@qgallouedec this error means that one run out of shared memory, to I'm quite confused why it would be the case for just 2000 1x1 tensors

**Comment by ZaydH** [comment] 2021-11-19 22:26
> Your example is hitting the open file descriptor limit (default 1024 on my system). That could be the issue here, although that wouldn't explain why it only happens on the latest PyTorch release.

Based on what @qgallouedec wrote, it looks like his issue is not exclusive to the latest release.  It seems it happens with `1.1.0` and `1.2.0` as well.

**Comment by seemethere** [comment] 2021-12-08 18:49
Moving from the 1.10.1 milestone to the 1.11.0 milestone since it appears as though we don't have a fix for this yet

**Comment by digantamisra98** [comment] 2022-01-25 02:15
```
Traceback (most recent call last):
  File "/home/mila/d/diganta.misra/.conda/envs/app1/lib/python3.9/multiprocessing/queues.py", line 245, in _feed
    obj = _ForkingPickler.dumps(obj)
  File "/home/mila/d/diganta.misra/.conda/envs/app1/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "/home/mila/d/diganta.misra/.conda/envs/app1/lib/python3.9/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
    fd, size = storage._share_fd_()
RuntimeError: falseINTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1639180585800/work/aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_9083_117> in read-write mode
```

Getting the same error in random times. Torch - 1.10.1

**Comment by NadavLightricks** [comment] 2022-01-31 09:18
I also experience this, happened only since moving to 1.10.

**Comment by ngimel** [comment] 2022-01-31 17:17
Adding to triage review based on user activity.

**Comment by mruberry** [comment] 2022-01-31 18:13
Maybe @xwang233 has a repro? https://github.com/pytorch/pytorch/issues/62780#issuecomment-899809730

**Comment by cicirori** [comment] 2022-02-02 04:59
any updates? I think it's a critical bug, many users on the platform I am responsible for encountered this problem on 1.10 and they had to roll back to version 1.8.2.

**Comment by ngimel** [comment] 2022-02-02 06:12
It would be tremendously helpful if there was a repro we can run, so far our attempts to repro haven't been successful.

**Comment by AlmogDavid** [comment] 2022-02-02 09:26
I had this crash also.
  I had this line in my code: `multiprocessing.set_start_method('spawn')`. When removing it everything worked. I hope it's helpful. (using pytorch 1.10.1 and  Ubuntu 18.04.5 LTS)

**Comment by davidrzs** [comment] 2022-02-03 01:04
Spent all day trying to get a reproducible version of this problem to post here and aid debugging, as it was seriously bugging me. 

I was not successful unfortunately - some models run for hours while other crash withing 15 minutes and other crash after 8 hours with the error above. But all in all, it is a highly nondeterministic bug where if you start training 8 models at the same time, 4 of them will have died from the bug while the others run completely fine.

Anyone who is interested in circumventing the problem: I can confirm that using PyTorch 1.8.1 as mentioned above does not exhibit the problem (as far as I have tested).

**Comment by ngimel** [comment] 2022-02-03 01:09
@davidrzs thanks, this is very helpful!
1) Would you be able to test a prospective fix if there's a PR? (You would probably need to build pytorch from source, or, if that doesn't work, wait for the fix to be merged and use nightly)
2) Does 1.9 have this bug? Other people on this issue say that it started with 1.10, so 1.9 should be ok.

**Comment by digantamisra98** [comment] 2022-02-03 01:14
@ngimel I had the bug on 1.9 as well. Haven't tested it with 1.8 yet. And I got the error even with: 
```
import torch.multiprocessing
torch.multiprocessing.set_sharing_strategy('file_system')
```

**Comment by digantamisra98** [comment] 2022-02-03 01:16
Agree with @davidrzs that the error is very random and doesn't have a meaningful trace to pinpoint the cause. But it is quite consistent. I have had atleast 20 cases where it has happened across nearly 100 runs with both 1.9 and 1.10 combined.

**Comment by ngimel** [comment] 2022-02-03 01:18
Can you try nightly build? It doesn't have a fix, but it has better error messages, so we'll have a better idea of what's going wrong.

**Comment by davidrzs** [comment] 2022-02-03 01:32
@[ngimel](https://github.com/ngimel) Thanks for your reply. I briefly tested with 1.9 and did not see the bug - but that could also just be pure luck, as the bug is very nondeterministic.

Another interesting piece of information: I am running my models on a big university cluster. From mid-November until mid-January I never saw the error, the error only started popping up two weeks ago (with the same code). The operating system (Debian) of the cluster has an uptime of about 80 days, I believe. Sounds very unlikely that this has any impact on the issue, but I thought I'd mention it anyway, as this is really strange.

I am actually super tight on a deadline, but I can spin up 8 models on a Friday or Saturday night on the cluster when it's not busy and test the nightly release.

**Comment by davidrzs** [comment] 2022-02-05 02:00
@[ngimel](https://github.com/ngimel) is the fix already implemented in PyTorch nightly, or just the better error message? I am currently running testing my code on the cluster with PyTorch nightly, and so far I have not seen the error (usually one would get see it quite quickly).

Will report back by Sat or Sun with more info.

**Comment by ngimel** [comment] 2022-02-05 02:17
The tentative fix is implemented on master, but unfortunately it wasn't picked up by the nightly build yet. It's interesting that you don't see the errors on current nightly though, thanks for checking!

**Comment by frederiksteiner** [comment] 2022-02-07 07:16
I had the same error twice now and for me it always happened, during an epoch where the learning rate was updated. Maybe this might be correlated

**Comment by JanGlinko** [comment] 2022-02-07 13:57
I can reproduce it every time i use DataLoader
```
transform = torchvision.transforms.Compose([
    torchvision.transforms.CenterCrop(1000),
    torchvision.transforms.ToTensor()
])
dataset = torchvision.datasets.CocoDetection(root='/home/avena/blenderproc/datasets/dataset_002/',
                                       annFile='/home/avena/blenderproc/datasets/dataset_002/coco_annotations.json',
                                       transform=transform)

train_dataloader = torch.utils.data.DataLoader(dataset, batch_size=1, shuffle=True, num_workers=1)

# this line
train_features, train_labels = next(iter(train_dataloader))

# or this lines
for t, l in train_dataloader:
    pass
```

and the error log is
```
Traceback (most recent call last):
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 329, in reduce_storage
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/multiprocessing/reduction.py", line 198, in DupFd
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/multiprocessing/resource_sharer.py", line 48, in __init__
OSError: [Errno 24] Too many open files
Traceback (most recent call last):
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/multiprocessing/queues.py", line 239, in _feed
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/multiprocessing/reduction.py", line 51, in dumps
  File "/home/avena/miniconda3/envs/blenderproc/lib/python3.8/site-packages/torch/multiprocessing/reductions.py", line 328, in reduce_storage
RuntimeError: falseINTERNAL ASSERT FAILED at "../aten/src/ATen/MapAllocator.cpp":263, please report a bug to PyTorch. unable to open shared memory object </torch_68365_6113> in read-write mode
```

**Comment by davidrzs** [comment] 2022-02-08 20:52
> @[ngimel](https://github.com/ngimel) is the fix already implemented in PyTorch nightly, or just the better error message? I am currently running testing my code on the cluster with PyTorch nightly, and so far I have not seen the error (usually one would get see it quite quickly).
> 
> Will report back by Monday evening with more info.

Was unsuccessful in replicating so far (cluster is considerably less busy - but not sure if that has anything to do with it). Will report once I get the error again.

**Comment by ngimel** [comment] 2022-02-08 20:53
Well if it got fixed somehow that's also good news :-)

**Comment by cicirori** [comment] 2022-02-09 02:35
bravo! the best bugfix I've ever seen.

**Comment by seemethere** [comment] 2022-02-17 19:24
Can we confirm if this bug is resolved in the latest RC for 1.11? Otherwise I suggest we remove this from the 1.11.0 milestone and move it to the 1.12.0 milestone.

**Comment by malfet** [comment] 2022-02-24 18:58
Moving to 1.12,  as https://github.com/pytorch/pytorch/pull/72232 hopefully mitigates the issue

**Comment by ekhahniii** [comment] 2022-03-15 21:30
> > @[ngimel](https://github.com/ngimel) is the fix already implemented in PyTorch nightly, or just the better error message? I am currently running testing my code on the cluster with PyTorch nightly, and so far I have not seen the error (usually one would get see it quite quickly).
> > Will report back by Monday evening with more info.
> 
> Was unsuccessful in replicating so far (cluster is considerably less busy - but not sure if that has anything to do with it). Will report once I get the error again.

@davidrzs Would "busy" perhaps mean other users training models with PyTorch? 

Wondering if there can be interaction between users' PyTorch code?

**Comment by davidrzs** [comment] 2022-04-10 23:32
Sorry for my late reply. Have been quite busy lately. @ekhahniii yes, with busy I mean other users / other jobs by other users or myself. We have a cluster with 8 GPUs per compute node. So there are often cases when multiple jobs (up to 8) are scheduled onto the same node (cluster runs slurm). 

Reverting to PyTorch 1.8 has solved the issue for me, but once the cluster is less busy, I might be able to experiment again.

**Comment by obilaniu** [comment] 2022-04-11 16:26
@davidrzs It turns out this bug is one of those you can work around with just an `LD_PRELOAD` of a suitable patch. I made a Gist [here](https://gist.github.com/obilaniu/b133470cb70410d841faca819d3921e5) with the compile instructions inside.

**Comment by atalman** [comment] 2022-05-18 14:59
Closing this issue as per above comment

**Closed by atalman** 2022-05-18 14:59 UTC
Labels: high priority, module: multiprocessing, triaged, module: regression

**Comment by abhijay9** [comment] 2022-11-18 20:40
I am getting a similar error 

![Screenshot from 2022-11-18 12-39-16](https://user-images.githubusercontent.com/11029633/202798305-c48c3a73-5960-48c9-aef9-f7f0334a15e4.png)

I put the two lines in a try block and set off the debugger when the exception occurs.

![Screenshot from 2022-11-18 12-11-56](https://user-images.githubusercontent.com/11029633/202797836-1f9202b6-4934-4cfe-9279-11626db515f7.png)

When the exception occurs, I ran the two lines in the debugger and they work fine without throwing an error. This is bizarre!

**Comment by mruberry** [comment] 2022-11-21 14:59
@abhijay9, would you please file a new issue describing what you're seeing?
