### ISSUE TITLE
failed to load torch lib with QTCreator

### ISSUE THREAD

**Issue by pc1122** [pytorch/pytorch#23056] opened 2019-07-19 03:52 UTC
## To Reproduce

1.clone the source pytorch and success build from source
1.load libtorch
1.compile failed

## Expected behavior

When load torch lib with QTCreator in Window 10,compile failed:
error LNK2019: unresolved external symbol "public: long * __cdecl at::Tensor::data<long>(void)const " (??$data@J@Tensor@at@@QEBAPEAJXZ) referenced in function "public: class at::TensorAccessor<long,1,struct at::DefaultPtrTraits,__int64> __cdecl at::Tensor::accessor<long,1>(void)const & " (??$accessor@J$00@Tensor@at@@QEGBA?AV?$TensorAccessor@J$00UDefaultPtrTraits@at@@_J@1@XZ)

my .pro:
INCLUDEPATH += D:/app/conda/envs/pytorch/Lib/site-packages/torch/include \
INCLUDEPATH += D:/app/conda/envs/pytorch/Lib/site-packages/torch/include/torch \
INCLUDEPATH += D:/app/conda/envs/pytorch/Lib/site-packages/torch/include/torch/csrc/api/include \
INCLUDEPATH += D:/app/conda/envs/pytorch/Lib/site-packages/torch/include/ATen

LIBS += -LD:/app/conda/envs/pytorch/Lib/site-packages/torch/lib \
        -lc10 -lc10_cuda -ltorch -ltorch_python -l_C \
        -lcaffe2_detectron_ops_gpu -lcaffe2_module_test_dynamic \
        -lfoxi_dummy -lonnxifi_dummy -lonnxifi_loader -lfoxi_loader -lonnx -lonnx_proto \
        -lshm -lcaffe2_observers -lcaffe2_detectron_ops_gpu -lcaffe2_nvrtc \
        -lcaffe2 -lcaffe2_gpu -lclog -lcpuinfo \
        -lcaffe2_module_test_dynamic -lthnvrtc -llibprotoc -llibprotobuf -llibprotobuf-lite

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): PyTorch 1.2.0a0+b1bf16e
 - OS (e.g., Linux): Window10
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): python setup.py install
 - Python version: Python 3.6.8
 - CUDA/cuDNN version: CUDA 9.0/cuDnn 7.5
 - GPU models and configuration: 
 - Any other relevant information:

**Comment by peterjc123** [comment] 2019-07-19 03:56
long -> int64_t

**Comment by peterjc123** [comment] 2019-07-19 03:56
Duplicate of https://github.com/pytorch/pytorch/issues/23013.

**Closed by peterjc123** 2019-07-19 03:56 UTC

**Comment by pc1122** [comment] 2019-07-20 08:54
> long -> int64_t

can you tell me how to change  it?very ths...

**Comment by peterjc123** [comment] 2019-07-20 09:39
Just replace all the occurrences of  `long`s in your code or the code you referenced with `int64_t`.

**Comment by pc1122** [comment] 2019-07-20 10:45
thank you very much,it's my class topid access wrong.like this:
auto top_indexs = top_probability_indexes.accessor<long,1>();
