### ISSUE TITLE
Tensor.all() fails on MPS for tensors with more than 4 dimensions

### ISSUE THREAD

**Issue by gau-nernst** [pytorch/pytorch#95538] opened 2023-02-25 01:07 UTC
### 🐛 Describe the bug

`Tensor.all()` fails on MPS for tensors with more than 4 dimensions

```python
import torch

x = torch.zeros(1, 1, 1, 1, 1, device="mps")
x.all()       # crash
x.all(dim=0)  # crash
x.all(dim=1)  # no crash
x.all(dim=2)  # no crash
x.all(dim=3)  # no crash
x.all(dim=4)  # no crash
```

Output

```bash
Assertion failed: (0 <= mpsAxis && mpsAxis < 4 && "Runtime canonicalization must simplify reduction axes to minor 4 dimensions."), function encodeNDArrayOp, file GPUReductionOps.mm, line 76.
[1]    77353 abort      python debug.py
```

I believe the MPS implementation is here: https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/mps/operations/ReduceOps.mm

Surprisingly, most ops don't have this problem, including `torch.any()`. I'm guessing this is an undocumented limitation by MPS op `reductionAndWithTensor`.

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230224
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.102)
CMake version: version 3.24.0
Libc version: N/A

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:26:08) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1

Versions of relevant libraries:
[pip3] mypy==1.0.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] torch==2.0.0.dev20230224
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] pytorch                   2.0.0.dev20230224        py3.10_0    pytorch-nightly

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen @razarmehr @abhudev

**Comment by kulinseth** [comment] 2023-03-04 23:16
Thanks @gau-nernst for reporting the issue. I am able to reproduce it. Will keep you posted when we have the fix.

**Comment by kulinseth** [comment] 2023-03-29 14:16
> #96131 removes this test:
> 
> https://github.com/pytorch/pytorch/blob/6871665a973b33aedd0376294645e217978d1495/test/test_mps.py#L10085-L10096
> 
> The only thing left for full compatibility of `torch.testing.assert_close` for the MPS device is a functioning `torch.all` for all dimensions. However, since the error is not recoverable, there is no configuration that could xfail the test.
> 
> Any fix for this issue should also include the patch from #96132.

Thanks @pmeier .

**Comment by dbl001** [comment] 2023-11-29 19:43
I ran into this exception enabling:
```
torch.autograd.set_detect_anomaly(True)
```
to track down NaN'a and -Inf's in llama2.c.

**Comment by jhavukainen** [comment] 2024-07-08 21:32
This seems like an unhandled use case by the MPSGraph `reductionAndWithTensor:axes:name`. My assumption is that the graph should handle this and do what it needs to support the dims > 4 case gracefully since the documentation is not explicitly stating this limitation. I've raised an issue internally with the MPSGraph to get clarity on if this is a case of missing documentation or functionality.

Once I get their comments on if this is something that they will fix or something we need to workaround on the pytorch side I'll update here.

**Comment by skotapati** [comment] 2024-07-23 21:24
Fixed by Nikita's PR

**Closed by skotapati** 2024-07-23 21:24 UTC
Labels: high priority, triaged, module: reductions, module: mps

**Comment by malfet** [comment] 2024-07-25 11:50
> ```
> In [2]: print(torch.__version__)
> 2.4.0a0+gitd990dad
> ```

@dbl001 how did you compile this torch build? Please note that https://github.com/pytorch/pytorch/commit/febadda107e5bfd78d32a276000a313b3b10f41b should be part of the build with 2.5.0 version in the prefix:
```
% python3
Python 3.9.6 (default, Aug 11 2023, 19:44:49) 
[Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> print(torch.__version__)
2.5.0a0+giteeef686
>>> x = torch.zeros(1, 1, 1, 1, 1, device="mps")
>>> x.all()
tensor(False, device='mps:0')
>>> x.all(dim=0)
tensor([[[[False]]]], device='mps:0')
>>> x.all(dim=1)
tensor([[[[False]]]], device='mps:0')
>>> x.all(dim=2)
tensor([[[[False]]]], device='mps:0')
>>> x.all(dim=3)
tensor([[[[False]]]], device='mps:0')
>>> x.all(dim=4)
tensor([[[[False]]]], device='mps:0')

```
