### ISSUE TITLE
Committed memory spike when spawning processes

### ISSUE THREAD

**Issue by SSS135** [pytorch/pytorch#38645] opened 2020-05-18 11:11 UTC
## 🐛 Bug

Committed memory rises by about 1GB for each process spawned with either `multiprocessing.Process`, `torch.multiprocessing.Process` or `torch.multiprocessing.spawn` if `torch` is imported in child process.

## To Reproduce

1. Run this script
```
import torch.multiprocessing as mp
import time


def proc_target(x):
    time.sleep(100000)      


if __name__ == '__main__':
	context = mp.spawn(fn=proc_target, nprocs=32)
```
2. Look at committed memory in task manager

## Expected behavior

Committed memory does not change much.

## Environment

```
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Њ ©Єа®б®дв Windows 10 Pro
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 442.19
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] efficientnet-pytorch==0.6.3
[pip] numpy==1.17.4
[pip] numpydoc==0.9.1
[pip] ppo-pytorch==0.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h74a9793_0
[conda] efficientnet-pytorch      0.6.3                    pypi_0    pypi
[conda] mkl                       2019.4                      245
[conda] mkl-service               2.3.0            py37hb782905_0
[conda] mkl_fft                   1.0.15           py37h14836fe_0
[conda] mkl_random                1.1.0            py37h675688f_0
[conda] numpy                     1.17.4           py37h4320e6b_0
[conda] numpy-base                1.17.4           py37hc3f5095_0
[conda] numpydoc                  0.9.1                      py_0
[conda] ppo-pytorch               0.1                       dev_0    <develop>
[conda] pytorch                   1.5.0           py3.7_cuda101_cudnn7_0    pytorch
[conda] pytorch-qrnn              0.2.1                    pypi_0    pypi
[conda] torchvision               0.6.0                py37_cu101    pytorch
```

cc @peterjc123 @nbcsm @guyang3532 @VitalyFedyunin @ngimel

**Comment by SSS135** [comment] 2020-08-03 11:10
Bug is still present in PyTorch 1.6.0

**Comment by mszhanyi** [comment] 2020-08-21 03:17
@VitalyFedyunin @ngimel , I compared python.multiprocessing and torch.multiprocessing in Linux with the below script.
It has a commited memory spike in Linux too for torch.multiprocessing, is it expected?
                                                commited_as.  (before)             commited_as (running)
torch.multiprocessing                  2,095,956  kB                     6,836,256 kB
python.multiprocessing               2,094,100.  kB                     2,198,036 KB

import multiprocessing as mp
import time

def proc_target():
    time.sleep(100000)      

if __name__ == '__main__':
    mp.set_start_method('spawn')
    for i in range(32): 
        p = mp.Process(target=proc_target)
        p.start()

**Comment by VitalyFedyunin** [comment] 2020-09-09 17:21
Pytorch binary code takes significant chunk of memory which you are likely seeing as committed as soon as any PyTorch module loaded.

**Comment by arquolo** [comment] 2020-09-21 15:00
However, this does not happen when `pytorch` is installed in `cpuonly` mode.

Given binary size (*.dll + *.pyd files) of 200 MB for CPU-only version of PyTorch each subprocess commits about 60 MB of RAM.
PyTorch built with CUDA has 1.2 GB binaries and commits about 1.3 GB of RAM.

I guess pytorch built with CUDA preloads all DLLs for each subprocess, what it shouldn't do.
At least until any `Tensor` is transfered to GPU or `torch.cuda.init()` is called.

I checked all DLLs in `torch/lib` directory, and found that when any DLL which depends on `torch_cuda.dll` is loaded, this overcommitment happens. So the problem is definetely there.

**Comment by arquolo** [comment] 2020-11-09 15:16
In other words @mszhanyi , @SSS135 , this is not because of the `torch.multiprocessing.spawn` usage instead of `multiprocessing.spawn`, it's because of importing `torch`. Something causes memory overcommitment before `torch.cuda()` is called, even though `torch.cuda.init()` has never been called.

**Comment by arquolo** [comment] 2020-11-09 17:54
Bug is still present in PyTorch 1.7

**Comment by albanD** [comment] 2022-05-31 19:55
To keep all discussions in one place, closing in favor of https://github.com/pytorch/pytorch/issues/12873

**Closed by albanD** 2022-05-31 19:55 UTC
Labels: module: windows, module: multiprocessing, triaged
