### ISSUE TITLE
Pytorch Freezes System

### ISSUE THREAD

**Issue by rosenfeldamir** [pytorch/pytorch#1659] opened 2017-05-26 14:30 UTC
I have a recurring issue with PyTorch - which is that training models causes very heavy lags on my system, meaning everything becomes choppy and the screen updates only between 2-3 times a second. This happens more in heavier models, e.g, ResNet, VGG,though it's still noticeable in less computationally intensive ones. I realize that the GPU use is probably the cause ,however I did not notice such things in other frameworks (Keras, Tensorflow). My System is quite strong - Titan X Pascal, Ubuntu 16.04, core i7 , 32GB Ram. This happens also when the GPU is underutilized, e.g, 4GB out of the maximal 12GB. I am using a recent version of PyTorch. 
Has anyone else encountered this? Is this a known issue?

**Comment by apaszke** [comment] 2017-05-26 14:52
Memory usage is not a good measure of GPU utilization. It's possible to use a small fraction of memory and still keep all the CUDA cores busy at 100%.

**Comment by rosenfeldamir** [comment] 2017-05-26 14:55
So, would you say it is typical for a PyTorch workflow to cause the system to be in such a state that I cannot effectively do anything else while training with the GPU?

**Comment by apaszke** [comment] 2017-05-26 14:58
It's not a "typical workflow". We haven't designed the framework trying to make the computer unusable for anything else 😄 I haven't ever experienced that, but I know that a lot of larger CNNs can utilize the GPU computing power in 99-100% (in `nvidia-smi`).

**Comment by soumith** [comment] 2017-05-26 14:59
it's not typical at all, there's something weird going on, but it's not the GPU memory.

Usually freezing indicates two things:
- you are running out of CPU memory and you are hitting disk swap
- a lot of hardware (say PCI-e or faulty GPU) / disk errors are being generated and the kernel is coping up with it slowly.

I wonder if your case is either of them.

**Comment by rosenfeldamir** [comment] 2017-05-26 15:12
@soumith - my CPU memory utilization is currently 12 out of 32GB. I don't believe that the issue is disk errors, since it happens when I load all of my dataset into memory (it's not really large, e.g, CIFAR-10/100). 
@apaszke  - As far as GPU utilization, I'm not sure what you mean by GPU computing-power, I have indicators of memory usage, temperature, volatile gpu-util

| 56%   85C    P2   232W / 250W |   3787MiB / 12186MiB |     88%      Default |

**Comment by rosenfeldamir** [comment] 2017-05-26 15:15
The problem is mostly gone when using num_workers=0. Is this parameter only relevant when loading images from a disk?

**Comment by soumith** [comment] 2017-05-26 15:17
if you are using CIFAR-10/CIFAR-100 then this parameter is fairly irrelevant. Were you using a large number of workers before? if you have a core i7 (4-core?) and you used more than 4 workers, it might start intermittent freezing as the CPU is all occupied by the workers.

**Comment by rosenfeldamir** [comment] 2017-05-26 15:20
Yup, i7-6700K. However, it happened for more than (wait for it:) zero workers.

**Comment by apaszke** [comment] 2017-06-03 11:42
I couldn't reproduce this on any system, so I'm closing this. It's likely a problem with your local configuration. I'd make sure you're not swapping out a lot of memory, because it might give similar symptoms.

**Closed by apaszke** 2017-06-03 11:42 UTC

**Comment by rosenfeldamir** [comment] 2017-06-05 03:59
How can I tell if I'm swapping out a lot of memory?

**Comment by soumith** [comment] 2017-06-05 15:13
you can look at the output of the `top` utility or `htop` utility, and see total memory usage, and somewhere in there there should be "swap space"

**Comment by rosenfeldamir** [comment] 2017-06-05 17:20
Ok, a reinstallation of the NVIDIA drivers solved it, though they were already pretty up to date (375.26...)
strange. 
I guess I was looking in the wrong place. Thanks for the help, @soumith  and @apaszke !

**Comment by thesamuel** [comment] 2019-04-26 05:09
This is a pretty old post, but hopefully this extra bit of information helps. I have also encountered this error while finetuning Resnet18 using a **large batch size (64)**. From what I understand however, this phenomenon is known by NVIDIA (see here: https://devtalk.nvidia.com/default/topic/1038170/cuda-programming-and-performance/cuda-accelerated-program-running-on-display-gpu-freezes-system/).

**Comment by zc-alexfan** [comment] 2019-07-30 22:23
Same problem here, and I think I have found the problem.

The issue occurs because of the disk I/O is 100% occupied (check by command `iostat -x 1`) when either the batch size being too big or too many workers. It is problematic because virtual memory is also used by other programs in the system. When the system cannot load virtual memory into RAM for other programs on time, the other programs will freeze until the virtual memory is loaded into RAM. 

This is probably why several of the above "solutions" work (such as having a lower batch size or having a smaller `num_worker`), because under those configuration, not many examples are beinig requested from the disk to RAM. 

Nevertheless, I think the PyTorch `DataLoader` should have resolved this.

**Comment by akinolawilson** [comment] 2021-02-12 15:59
For anyone that comes looking but doesn't find the solution through those proposed here, problem is related to this: [https://github.com/pytorch/pytorch/issues/24081#issuecomment-557074611]

**Comment by 1e100** [comment] 2023-09-20 04:09
Also, if reading from an SSD, use `posix_fadvise()` with `POSIX_FADV_DONTNEED` flag after reading the file. That way data loader will not pollute your page cache with the stuff it won't need until the next epoch.
