### ISSUE TITLE
import error: from torch._C import * RuntimeError: stoi

### ISSUE THREAD

**Issue by aespielberg** [pytorch/pytorch#7082] opened 2018-04-30 00:39 UTC
Hi all,

I just recently installed pytorch.  I'm using 3.5 but also tried it with 3.6  import torch gives me the following error:

```
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aespielberg/anaconda3/lib/python3.5/site-packages/torch/__init__.py", line 78, in <module>
    from torch._C import *
RuntimeError: stoi
```

I've tried upgrading conda, numpy, and pytorch.

- Pytorch
- conda
- PyTorch version:
- Python version: Python 3.5.5 :: Anaconda custom (64-bit)
- CUDA/cuDNN version: 8.0

**Comment by mitar** [comment] 2018-04-30 02:26
Same here. What is your OS? glibc version?

**Comment by stomachacheGE** [comment] 2018-06-01 10:00
I encountered the same error when my Matlab script runs python to import torch. However, I can import torch successfully when directly open a python console from terminal. Any suggestion is welcomed.

**Comment by mitar** [comment] 2018-06-01 16:14
In our case it was also connected to Matlab. It is the question of import order. If you load Matlab first in your Python script, then Torch 0.4.0 does not work. Other way around it seems to both work.

Torch 0.3.* continues to work though. So there is some difference between 0.4.0 and older versions.

**Comment by soumith** [comment] 2018-06-01 16:16
matlab ships with it's own libstdc++ that is too old, i think. And that becomes an issue.

**Comment by mitar** [comment] 2018-06-01 16:18
Not really, there is a new release of Matlab having pretty recent version. Also, I removed their old `libstdc++` so files and forced loading of system so files and it was still the same thing.

**Comment by mitar** [comment] 2018-06-01 16:18
My feeling (based on stack traces) is that it is something about threading. That or Matlab or Torch do not expect threading to be active when being imported, and one or the other does something with threads.

**Comment by mitar** [comment] 2018-06-04 06:39
Hm, if you are using `system()` command, then those are two separate processes, no? Then it is maybe really something about libraries and not threading.

**Comment by stomachacheGE** [comment] 2018-06-05 01:56
@mitar I think you are right. As a minimal example, if I run `python -c "import torch"` from terminal, it works perfectly. However, if I run `system('python -c "import torch"')`, the error occurs. I checked the PATH and LD_LIBRARY_PATH for both cases, and they are the same.

**Comment by he010103** [comment] 2018-06-26 07:51
@stomachacheGE @mitar I read your dicussion carefully. Do you solve the problem by running system('python -c "import torch"')  with error?

**Comment by mitar** [comment] 2018-06-26 13:09
I could not solve the problem. I am staying at 0.3.1 for now.

**Comment by he010103** [comment] 2018-06-27 11:00
@mitar ok, but pytorch0.4.0 doesnet have fft.

**Comment by SsnL** [comment] 2018-07-02 18:14
@he010103 0.4 definitely has fft.

**Comment by zou3519** [comment] 2018-07-02 18:15
Can any of you reproduce this in a docker image? That would really help with debugging.

**Comment by mitar** [comment] 2018-07-02 18:48
I use something like this to install Matlab into a Docker container:

```
RUN cd /usr/src && \
 wget --no-verbose http://ssd.mathworks.com/supportfiles/downloads/R2017b/deployment_files/R2017b/installers/glnxa64/MCR_R2017b_glnxa64_installer.zip && \
 unzip MCR_R2017b_glnxa64_installer.zip && \
 mkdir -p /opt/mcr && ./install -mode silent -agreeToLicense yes -destinationFolder /opt/mcr && \
 echo /opt/mcr/v93/runtime/glnxa64 > /etc/ld.so.conf.d/zzz-matlab.conf && \
 echo /opt/mcr/v93/bin/glnxa64 >> /etc/ld.so.conf.d/zzz-matlab.conf && \
 echo /opt/mcr/v93/sys/os/glnxa64 >> /etc/ld.so.conf.d/zzz-matlab.conf && \
 ldconfig && \
 cd / && rm -rf /usr/src/*
```

This is an older version, but new has also the same issues as mentioned in this thread.

So then just install pytorch and then import matlab first before torch and it will fail. Importing matlab is a bit tricky, I am seeing now in the code, I will see if I can extract it later. But it is generally importing the `/opt/mcr/v93/bin/glnxa64/matlabruntimeforpython3_6.so` file.

**Comment by SsnL** [comment] 2018-07-02 18:53
If matlab has a libstdc++ that is too old, can we do anything? @soumith

**Comment by mitar** [comment] 2018-07-02 18:58
From my testing I am not sure if it is the the question of old libstdc++, even if I force loading of system-wide libstdc++, error still happens.

My feeling is that it is something about threading. Does PyTorch uses threads?

**Comment by soumith** [comment] 2018-07-27 05:01
Yes, PyTorch uses threads in general, via OpenMP, MKL and also has it's own threads for a few things like `autograd`

**Comment by josephnunn** [comment] 2018-07-27 07:21
Hi there, I've got the exact same problem.

`from torch._C import *
ModuleNotFoundError: No module named 'torch._C'`

This from an empty file excepting
`import torch`

But of course, it works when run from the command line.

I build pyTorch from the github source against cuda 9.2 and intel mkl on Linux.  I'm using Eclipse + pyDev as the IDE.  Clearly something is getting set wrong in the environment when called one way vs the other but have not identified yet what that is.

**Comment by BestSonny** [comment] 2018-08-23 18:37
Is there any progress on this issue?

**Comment by aespielberg** [comment] 2018-08-23 23:31
This seems to still be an issue in 0.4.  I am running Ubuntu 16.04.  glibc version:
ldd (Ubuntu GLIBC 2.23-0ubuntu10) 2.23

This happens only when trying to use PyTorch from inside a MATLAB environment by invoking a system call.

**Comment by ezyang** [comment] 2018-08-30 15:55
Can you run the crashing version of Python under gdb and give us a backtrace?

**Comment by SsnL** [comment] 2018-08-30 18:06
@juanitoroter Also, what is the stdc++lib version (including minor) your matlab uses? What is the version of `~/.conda/envs/Py36Torch/lib/libstdc++.so.6 `?

**Comment by kidanger** [comment] 2018-10-22 15:50
I had the same error. I fixed it using: system('env -i /usr/bin/python3 -c "import torch"').
Some environment variable set by matlab is messing with pytorch, but I don't know which.

**Comment by yalaudah** [comment] 2018-11-01 19:37
@kidanger I've had the same issue as others here, and your solution worked. Thanks!!

**Comment by skyoung** [comment] 2018-11-08 07:01
Seems like `autograd.grad` does not work well even in Pytorch 0.3.x. Does anyone have any idea?

**Comment by hwh3304** [comment] 2018-11-10 15:41
@kidanger Thank you. This woks. Just add env -i before the previous command.

**Comment by wmasonku** [comment] 2018-12-27 20:31
Instead of 'env -i' try 'unset MKL_NUM_THREADS' before running. ex: system('unset MKL_NUM_THREADS; /usr/bin/python3 -c "import torch"')

**Comment by messcode** [comment] 2019-01-21 11:53
@wmasonku 's solution works two. Many thanks. I am using Matlab 2015b and torch 0.4.1.

**Comment by xi-mao** [comment] 2019-03-07 02:57
> Also I reproduce the same error when run system(['source activate Py36Torch; python -c "import torch"']) on Ubuntu 16.04.4 Matlab2016a and Matlab2018a (with and without CUDA8.0). Even if I force to Matab to use my system libraries or my Python environment libraries: LD_PRELOAD=~/.conda/envs/Py36Torch/lib/libstdc++.so.6 /home2/Softwares/MATLAB/R2016b/bin/matlab
> 
> It is really a pity if the only solution is just degrading pytorch (it is not possible for me!)

can i ask how to change matlab env PATH？

**Comment by xi-mao** [comment] 2019-03-07 02:59
> @juanitoroter Also, what is the stdc++lib version (including minor) your matlab uses? What is the version of `~/.conda/envs/Py36Torch/lib/libstdc++.so.6 `?

did you solved the problem?

**Comment by xi-mao** [comment] 2019-03-07 03:05
> Hi all,
> 
> I just recently installed pytorch. I'm using 3.5 but also tried it with 3.6 import torch gives me the following error:
> 
> ```
> >>> import torch
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/aespielberg/anaconda3/lib/python3.5/site-packages/torch/__init__.py", line 78, in <module>
>     from torch._C import *
> RuntimeError: stoi
> ```
> I've tried upgrading conda, numpy, and pytorch.
> 
> * Pytorch
> * conda
> * PyTorch version:
> * Python version: Python 3.5.5 :: Anaconda custom (64-bit)
> * CUDA/cuDNN version: 8.0

anyone  solved the problem？

**Comment by LCAR979** [comment] 2019-03-14 07:39
Same problem here. 

- Ubuntu 16.04
- Matlab R2017a
- PyTorch 0.4.1 (conda env)
- anconda2
Any progress on this issue?

**Comment by xi-mao** [comment] 2019-03-14 07:58
> Same problem here.
> 
> * Ubuntu 16.04
> * Matlab R2017a
> * PyTorch 0.4.1 (conda env)
> * anconda2
>   Any progress on this issue?

I have solved the problem. you should down grade your pytorch version to 0.3, and  use python2. The issue will be solved. Besides I didn't use conda env. I didn't suggest use conda environment。

**Comment by LCAR979** [comment] 2019-03-14 08:06
@xi-mao. Thanks, but downgrading is not an option for me since I strongly need the fft module in 0.4.

**Comment by bilylee** [comment] 2019-04-15 02:52
Thanks to @wmasonku . It works!

By the way, if you are calling a python script from matlab, you can achieve the same effects by putting the following line before importing torch. 
```python
# in a python script
del os.environ['MKL_NUM_THREADS']
import torch
```

**Comment by colesbury** [comment] 2019-04-15 18:00
This looks like an issue with the code here:

https://github.com/pytorch/pytorch/blob/422b01e78889a9fd283d8fb86bb5527c5cae3cbf/aten/src/ATen/Context.h#L170-L172

We should fix this before the next release

**Comment by gchanan** [comment] 2019-05-09 22:45
I believe this should be fixed after https://github.com/pytorch/pytorch/pull/19011 -- please reopen if that is not the case.

**Closed by gchanan** 2019-05-09 22:45 UTC
Labels: high priority, module: internals, small, triaged
