### ISSUE TITLE
Unable to find MPI backend with Torch 2.0 nightly build from source

### ISSUE THREAD

**Issue by ajindal1** [pytorch/pytorch#92573] opened 2023-01-18 20:28 UTC
### 🐛 Describe the bug

MPI backend is not working while initializing process group with Torch 2.0 when building torch from source. During my investigation I found that Backend._plugins is an empty dict (not sure if this is correct).

Steps to reproduce the error:
1. Build torch from source using the latest main branch. Install the build.
2. Run the below command in Python

```python
import torch.distributed as dist
dist.init_process_group(backend='mpi', rank=0, world_size=1)
```

Error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 863, in init_process_group
    default_pg = _new_process_group_helper(
  File "/opt/conda/envs/ptca/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1005, in _new_process_group_helper
    assert backend_str.upper() in Backend._plugins, (
AssertionError: Unknown c10d backend type MPI

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230117+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.0
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-135-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070
GPU 1: NVIDIA GeForce GTX 1070

Nvidia driver version: 510.108.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.22.2
[pip3] pytorch-lightning==1.6.3
[pip3] torch==2.0.0.dev20230117+cu116
[pip3] torch-nebula==0.15.9
[pip3] torch-ort==1.14.0.dev20230113
[pip3] torchmetrics==0.7.1
[pip3] torchvision==0.15.0.dev20230117+cu116
[conda] magma-cuda116             2.6.1                         1    pytorch
[conda] mkl                       2021.4.0                 pypi_0    pypi
[conda] mkl-include               2021.4.0                 pypi_0    pypi
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] torch                     2.0.0.dev20230117+cu116          pypi_0    pypi
[conda] torch-nebula              0.15.9                   pypi_0    pypi
[conda] torch-ort                 1.14.0.dev20230113          pypi_0    pypi
[conda] torchmetrics              0.7.1                    pypi_0    pypi
[conda] torchvision               0.15.0.dev20230117+cu116          pypi_0    pypi

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by eellison** [comment] 2023-01-18 21:31
CC @wconstab could you respond or further triage this ?

**Comment by wconstab** [comment] 2023-01-19 17:32
at first glance it appears unrelated to PT2 stuff and is a build issue (maybe MPI isn't being built?) - i'm not familiar with this stuff, lets tag @mrshenli @wanchaol and see if they can triage.

**Comment by ajindal1** [comment] 2023-01-19 21:54
Thanks @mrshenli for the reply. I am using the flag USE_MPI=1 and the host has MPI installed.
My guess is that there should elif instead of if in this line for Backend.GLOO (https://github.com/pytorch/pytorch/blob/647b8f8e3e6e971304162e7a6ea34e0e81d03239/torch/distributed/distributed_c10d.py#L976). Replacing if by elif resolves the above error.

More context:
Our pipeline was working fine before this PR (https://github.com/pytorch/pytorch/pull/88330). I don't have the complete knowledge on the code but previously, there was an if and else statement for Backend.MPI which was later changed to just if and the remaining else statement is currently running for all cases. Just wanted to point this out in case it is helpful.

**Comment by mrshenli** [comment] 2023-01-20 03:45
Hey @ajindal1, thanks a lot for sharing the context. This looks like a regression. 

Hey @H-Huang, could you please help take a look at this one? Thanks!

**Comment by H-Huang** [comment] 2023-01-23 21:15
Hi @ajindal1, thanks for reporting this issue. This is a regression and the fix is in https://github.com/pytorch/pytorch/pull/92847

**Closed** 2023-01-24 23:24 UTC
Labels: oncall: distributed, module: regression, module: c10d
