### ISSUE TITLE
Model behaves differently after saving and loading

### ISSUE THREAD

**Issue by magic282** [pytorch/pytorch#4333] opened 2017-12-23 09:15 UTC
Hi,

Recently I am working on a summarization project. During training, I saved the best model on the development set. However, loading the best model and testing again on the dev set gives me different ROUGE result (0.18218091939853281 -> 0.18217045231619222 ). Although the difference is small, it raises much concerns. And my colleagues told me that they have also encountered this issue (they observed about 2 points drop on their QA task). So I wrote a small [script](https://gist.github.com/magic282/94bdbb3b9ddef891d7aa40f0b0069a0f), and found that the parameters are identical, but the result is different after saving and loading.

And I also found this thread https://discuss.pytorch.org/t/saving-and-loading-a-model-in-pytorch/2610/21

The code on github gist runs on Windows (peterjc123’s 0.3.0 build). On linux (also 0.3.0 , I built a docker image myself by installing pytorch through conda) it raises an error that I don’t understand why:

```python
THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/THCTensorCopy.cu line=204 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "test.py", line 120, in <module>
    main()
  File "test.py", line 76, in main
    hidden = hidden.transpose(0, 1).contiguous().view(hidden.size(1), -1)
  File "/opt/conda/envs/pytorch-py3.6/lib/python3.6/site-packages/torch/autograd/variable.py", line 280, in contiguous
    self.data = self.data.contiguous()
RuntimeError: cuda runtime error (59) : device-side assert triggered at /opt/conda/conda-bld/pytorch_1512386481460/work/torch/lib/THC/THCTensorCopy.cu:204
```

The thread I posted https://discuss.pytorch.org/t/parameters-are-different-after-loading-model/11457

**Comment by apaszke** [comment] 2017-12-23 10:33
IIRC `assert` in CUDA kernels is not supported on Windows, so that's why you're not getting this error unless you use Linux. It means you have an error in your program (most likely an out-of-bound index somewhere). You can try running with `CUDA_LAUNCH_BLOCKING=1` to better pin point the point of error.

Are you sure you're evaluating both of these models in train/eval mode?

**Comment by ahmedanis03** [comment] 2017-12-25 20:54
here is a modified mnist example to reproduce the inconsistency:
to reproduce run:
```
python run.py --exp_name=testv1 --epochs=2 --no-cuda
python run.py --exp_name=testv2 --epochs=1 --no-cuda
python run.py --exp_name=testv2 --epochs=1 --no-cuda --resume-type=last
```
why --no-cuda: because running on GPU give a different result each time for the mnist example and i don't know why!.
```python
from __future__ import print_function
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
from torchvision import datasets, transforms
from torch.autograd import Variable
import os
import shutil

# Training settings
parser = argparse.ArgumentParser(description='PyTorch MNIST Example')
parser.add_argument('--batch-size', type=int, default=64, metavar='N',
                    help='input batch size for training (default: 64)')
parser.add_argument('--test-batch-size', type=int, default=1000, metavar='N',
                    help='input batch size for testing (default: 1000)')
parser.add_argument('--epochs', type=int, default=10, metavar='N',
                    help='number of epochs to train (default: 10)')
parser.add_argument('--lr', type=float, default=0.01, metavar='LR',
                    help='learning rate (default: 0.01)')
parser.add_argument('--momentum', type=float, default=0.5, metavar='M',
                    help='SGD momentum (default: 0.5)')
parser.add_argument('--no-cuda', action='store_true', default=False,
                    help='disables CUDA training')
parser.add_argument('--seed', type=int, default=1, metavar='S',
                    help='random seed (default: 1)')
parser.add_argument('--log-interval', type=int, default=10, metavar='N',
                    help='how many batches to wait before logging training status')
parser.add_argument('--start-epoch', default=0, type=int, metavar='N',
                    help='manual epoch number (useful on restarts)')
parser.add_argument('--resume-type', default='', type=str, metavar='PATH',
                    help='load from best/last checkpoint')
parser.add_argument('--exp_name', type=str, default='dummy',
                    help='experiment name to used across everything', metavar='exp_name', required=True)

args = parser.parse_args()
args.cuda = not args.no_cuda and torch.cuda.is_available()

torch.manual_seed(args.seed)
if args.cuda:
    torch.cuda.manual_seed(args.seed)


kwargs = {'num_workers': 1, 'pin_memory': True} if args.cuda else {}
train_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=True, download=True,
                   transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=args.batch_size, shuffle=True, **kwargs)
test_loader = torch.utils.data.DataLoader(
    datasets.MNIST('../data', train=False, transform=transforms.Compose([
                       transforms.ToTensor(),
                       transforms.Normalize((0.1307,), (0.3081,))
                   ])),
    batch_size=args.test_batch_size, shuffle=True, **kwargs)


class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        return F.log_softmax(x)

model = Net()
if args.cuda:
    model.cuda()

optimizer = optim.SGD(model.parameters(), lr=args.lr, momentum=args.momentum)

def train(epoch):
    model.train()
    for batch_idx, (data, target) in enumerate(train_loader):
        if args.cuda:
            data, target = data.cuda(), target.cuda()
        data, target = Variable(data), Variable(target)
        optimizer.zero_grad()
        output = model(data)
        loss = F.nll_loss(output, target)
        loss.backward()
        optimizer.step()
        # if batch_idx % args.log_interval == 0:
        #     print('Train Epoch: {} [{}/{} ({:.0f}%)]\tLoss: {:.6f}'.format(
        #         epoch, batch_idx * len(data), len(train_loader.dataset),
        #         100. * batch_idx / len(train_loader), loss.data[0]))

def test():
    model.eval()
    test_loss = 0
    correct = 0
    for data, target in test_loader:
        if args.cuda:
            data, target = data.cuda(), target.cuda()
        data, target = Variable(data, volatile=True), Variable(target)
        output = model(data)
        test_loss += F.nll_loss(output, target, size_average=False).data[0] # sum up batch loss
        pred = output.data.max(1, keepdim=True)[1] # get the index of the max log-probability
        correct += pred.eq(target.data.view_as(pred)).cpu().sum()

    test_loss /= len(test_loader.dataset)
    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(test_loader.dataset),
        100. * correct / len(test_loader.dataset)))


if args.resume_type:
    checkpoint_file = 'weights/' + args.exp_name + '/'
    checkpoint_file += 'checkpoint.pth.tar' if args.resume_type == 'last' else 'model_best.pth.tar'
    if os.path.isfile(checkpoint_file):
        print("=> loading checkpoint '{}'".format(checkpoint_file))
        checkpoint = torch.load(checkpoint_file)
        args.start_epoch = checkpoint['epoch']
        best_loss = checkpoint['best_loss']
        model.load_state_dict(checkpoint['state_dict'])
        optimizer.load_state_dict(checkpoint['optimizer'])
        print("=> loaded checkpoint '{}' (epoch {})"
              .format(checkpoint_file, checkpoint['epoch']))
    else:
        print("=> no checkpoint found at '{}'".format(checkpoint_file))


def save_checkpoint(state, is_best):
    exp_weights_root_dir = 'weights/' + args.exp_name + '/'
    os.makedirs(exp_weights_root_dir, exist_ok=True)
    filename = exp_weights_root_dir + 'checkpoint.pth.tar'
    torch.save(state, filename)
    if is_best:
        print('best beaten')
        shutil.copyfile(filename, exp_weights_root_dir + 'model_best.pth.tar')


for epoch in range(args.start_epoch, args.epochs + args.start_epoch):
    train(epoch)
    test()
    save_checkpoint(
                    {
                        'epoch': epoch + 1,
                        'state_dict': model.state_dict(),
                        'best_loss': 0,
                        'optimizer': optimizer.state_dict(),
                    }, True)
```

**Comment by apaszke** [comment] 2017-12-26 08:52
@ahmedanis03 can you please provide us with a diff for this file instead of a whole new version? That would make it easier to see what has changed.

@magic282 I'm glad to hear that you resolved some parts of the problem. I'm not entirely sure what's left. We're aware of the difference in speed between Windows and Linux, but note that you're not using official Windows packages (there are none at the moment). We will work on resolving these problems before we release 0.4 (which will have a Windows package).

**Comment by ahmedanis03** [comment] 2017-12-26 09:52
@apaszke HYG https://www.diffchecker.com/o1YJsfZo (i hope that is what you want)
and to clarify where is the inconsistency here is the steps i made:
1) train the model **from scratch** for 2 epochs, you will get exp1_epoch_one_accuracy and exp1_epoch_two_accuracy
2) train the model **from scratch** for 1 epochs, you will get exp2_epoch_one_accuracy = exp1_epoch_one_accuracy
3) train the model **from weights of exp_2** and train for 1 epochs, you will get exp2_epoch_two_accuracy != exp1_epoch_two_accuracy

**Comment by apaszke** [comment] 2017-12-29 11:26
You have dropout in your model, so the RNG state also affects the results. If you want full reproducibility after the checkpoint, you'll need to serialize all RNGs too (or e.g. at the beginning of each epoch do `torch.manual_seed(args.seed + epoch)`).

**Closed by apaszke** 2017-12-29 11:26 UTC

**Comment by rafaelvalle** [comment] 2018-04-02 17:04
@apaszke how does one save the RNG state?

**Comment by fikrisyad** [comment] 2018-05-04 04:44
@apaszke I have similar problem and I tried your suggestion (set `torch.manual_seed(SEED)` at every epoch) but the results still different compared
do you have any idea?

**Comment by sankhoroy** [comment] 2020-09-14 12:03
I also encountered the same issue while saving and loading the same model weights.

**Comment by bhosalems** [comment] 2023-03-13 12:14
I am observing similar issues, although I do not use dropouts.

**Comment by anushka192001** [comment] 2024-05-06 08:39
same problem .

**Comment by owenliang** [comment] 2024-11-02 13:52
same problem, still trying to figure it out

**Comment by LspongebobJH** [comment] 2025-01-30 12:10
same problem
