### ISSUE TITLE
torch.utils Cannot find reference 'utils' in '__init__.pyi | __init__.pyi' 

### ISSUE THREAD

**Issue by paantya** [pytorch/pytorch#41794] opened 2020-07-21 09:37 UTC
## 🐛 Bug

`torch.utils Cannot find reference 'utils' in '__init__.pyi | __init__.pyi' `

## To Reproduce

```
import torch; print(torch.__version__)
print(torch.utils.data.DataLoader)
```
## Expected behavior

Expected there would be a hint on the content of the module after entering a dot

## Environment

```
PCollecting environment information...
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 9.1.85
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.0
[pip3] pytorch-lightning==0.8.5
[pip3] torch==1.5.1
[pip3] torchvision==0.6.0a0+35d732a
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.0                   pypi_0    pypi
[conda] numpy-base                1.18.5           py37hde5b4d6_0  
[conda] pytorch                   1.5.1               py3.7_cpu_0  [cpuonly]  pytorch
[conda] pytorch-lightning         0.8.5                      py_0    conda-forge
[conda] torch                     1.5.1                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi
```

## Additional context

![scrin](https://github.com/paantya/tmp/blob/master/img/photo_2020-07-21_12-33-40.jpg?raw=true)

cc @ezyang @gchanan @zou3519 @SsnL @VitalyFedyunin @malfet @rgommers

**Comment by Markshilong** [comment] 2020-07-26 09:18
Same issue as yours, but I haven't found the solution yet.

**Comment by Xsurgeon** [comment] 2020-07-29 20:41
same issue here

**Comment by ezyang** [comment] 2020-07-30 17:43
due to activity marking as a high priority bug for type checking. I bet it is not too hard to do; just need to add stubs for utils.

**Comment by rgommers** [comment] 2020-08-05 18:36
I think this issue may already be fixed, the report is for PyTorch `1.5.1`. That version still had a stub file `torch/__init__.pyi`, this no longer exists in master nor in `1.6.0` so `utils` cannot really be missing from it anymore.

Can someone upgrade to `1.6.0` and confirm the issue disappears?

**Comment by paantya** [comment] 2020-08-06 14:14
I upgrading to 1.6.0 now

**Comment by paantya** [comment] 2020-08-06 14:16
disappears, but new issue
![image](https://user-images.githubusercontent.com/2975813/89542406-507e1680-d808-11ea-935f-ce7b1ff8e66a.png)
![image](https://user-images.githubusercontent.com/2975813/89542433-570c8e00-d808-11ea-9fe8-872959a86b75.png)

**Comment by paantya** [comment] 2020-08-06 14:17
```
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: No
CUDA used to build PyTorch: Could not collect

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: 9.1.85
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] pytorch-lightning==0.8.5
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.1.0            py37h23d657b_0  
[conda] mkl_random                1.1.1            py37h0573a6f_0  
[conda] numpy                     1.19.0                   pypi_0    pypi
[conda] numpy-base                1.19.1           py37hfa32c7d_0  
[conda] pytorch                   1.6.0               py3.7_cpu_0  [cpuonly]  pytorch
[conda] pytorch-lightning         0.8.5                      py_0    conda-forge
[conda] torch                     1.5.1                    pypi_0    pypi
[conda] torchvision               0.4.0                    pypi_0    pypi

Process finished with exit code 0

```

**Comment by paantya** [comment] 2020-08-06 14:19
@rgommers 
close this issue and open new issue, do nothing, or something else i can do?

**Comment by ezyang** [comment] 2020-08-06 14:46
It's possible that the new problem has to do with mypy and Python disagreeing about what entities are in scope. Specifying `__all__` or something similar may help.

**Comment by rgommers** [comment] 2020-08-06 14:49
Thanks @paantya. Let's keep this issue, no need for a new one. This one is due to an empty stub file, `torch/utils/__init__.pyi`. I'll fix that and will add complete type annotations for all parts of `torch.utils`, that will definitely fix it.

**Comment by rgommers** [comment] 2020-08-06 23:00
> It's possible that the new problem has to do with mypy and Python disagreeing about what entities are in scope. Specifying `__all__` or something similar may help.

It's actually by design that `torch.utils.data` and other `torch.utils` submodules are not imported into the `torch.utils` namespace. So there's nothing to put into `__all__`, and code completion should not work if all you have done is `import torch.utils`.

**Comment by rgommers** [comment] 2020-08-15 11:26
There's nothing left to do here, so I'll close this issue.

In general, type annotations are still quite incomplete (see the long list of `ignore_errors=True` in `mypy.ini`), so IDEs are likely to complain about lots of things. These will be worked out, but are mostly known.

**Closed by rgommers** 2020-08-15 11:26 UTC
Labels: high priority, module: dataloader, module: typing, triaged

**Comment by paantya** [comment] 2020-08-18 12:14
I have not done is `import torch.utils`.
I use `import torch`, and/or `from torch.utils.data import DataLoader`

**Comment by rgommers** [comment] 2020-08-18 12:46
So if you type `from torch.utils.data import DataLoader`, you should be using
```
print(DataLoader)
```
not 
```
print(torch.utils.data.DataLoader)
```
This really isn't broken, this is how Python imports work.

**Comment by paantya** [comment] 2020-09-21 13:16
@rgommers The problem is that I am expecting a hint about the available content afte the` torch.utils `, but I am not getting it.

**Comment by rgommers** [comment] 2020-09-21 15:56
Then you have to do `import torch.utils` and you will gets hints for what's in that namespace.

**Comment by freedom9393** [comment] 2020-10-28 02:58
You can try this:
`import torch.utils.data`

**Comment by NicoHambauer** [comment] 2021-06-07 15:19
Also having the same issue
![image](https://user-images.githubusercontent.com/58194361/121043005-87b8ad80-c7b4-11eb-95f3-1c766e5d3f88.png)

**Comment by rgommers** [comment] 2021-06-07 16:19
The import is right there, on the third line of your example - but it's greyed out. What does that mean for your IDE? Does the code actually run?

I've just tried this with pytorch 1.7.1, 1.8.0 and current master:

Save as `issue41794.py`:
```python
import random
import torch
from torch.utils.data import DataLoader, Dataset


class RandomDatasetMock(Dataset):
    def __getitem__(self, index):
        return torch.tensor([torch.rand(1).item(), random.uniform(0, 1)])

    def __len__(self):
        return 1000


dataloader = DataLoader(RandomDatasetMock(),
                        batch_size=2,
                        num_workers=1,
                        drop_last=False)

reveal_type(dataloader)
```
Then run `mypy issue41794.py`, it should give:
```
issue41795.py:19: note: Revealed type is 'torch.utils.data.dataloader.DataLoader[Any]'
```
