### ISSUE TITLE
https://conda.anaconda.org/pytorch/win-64/torchaudio-0.12.0-py39_cu116.tar.bz2 returns 403

### ISSUE THREAD

**Issue by ziyuang** [pytorch/pytorch#81825] opened 2022-07-20 22:55 UTC
## Issue description

Installing PyTorch 1.12 via conda on Windows gives the following errors:

```
> conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
...
CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/win-64/torchaudio-0.12.0-py39_cu116.tar.bz2>
Elapsed: 00:00.431512

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/win-64/torchvision-0.13.0-py39_cu116.tar.bz2>
Elapsed: 00:00.102336

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/win-64/pytorch-1.12.0-py3.9_cuda11.6_cudnn8_0.tar.bz2>
Elapsed: 00:00.102132

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

CondaHTTPError: HTTP 403 FORBIDDEN for url <https://conda.anaconda.org/pytorch/noarch/pytorch-mutex-1.0-cuda.tar.bz2>
Elapsed: 00:00.102145

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
```

## System Info
```
> python .\collect_env.py
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Education
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.18.2
Libc version: N/A

Python version: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: N/A
CUDA runtime version: 11.5.50
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2060
Nvidia driver version: 516.59
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.5\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] numpydoc==1.2
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           haa95532_640
[conda] mkl-service               2.4.0            py39h2bbff1b_0
[conda] mkl_fft                   1.3.1            py39h277e83a_0
[conda] mkl_random                1.2.2            py39hf11a4ad_0
[conda] numpy                     1.21.5           py39h7a0a035_1
[conda] numpy-base                1.21.5           py39hca35cd5_1
[conda] numpydoc                  1.2                pyhd3eb1b0_0
```

**Comment by kit1980** [comment] 2022-07-21 00:08
This is a Conda issue - https://github.com/conda/conda/issues/11638
Closing this as a duplicate of https://github.com/pytorch/pytorch/issues/81760

**Closed by kit1980** 2022-07-21 00:08 UTC
