### ISSUE TITLE
nccl build errors: Unable to checkout 'cd...' in submodule path 'third_party/nccl/nccl' and unable to build nccl_external

### ISSUE THREAD

**Issue by wpm** [pytorch/pytorch#47529] opened 2020-11-06 22:31 UTC
## 🐛 Bug

I am unable to install PyTorch [from source](https://github.com/pytorch/pytorch#from-source). There is a build error during `Performing build step for 'nccl_external'`. The `git submodule update --init --recursive` command also returns

```
fatal: reference is not a tree: cd5a9b73c3028d2496666201588111a8c8d84878
Unable to checkout 'cd5a9b73c3028d2496666201588111a8c8d84878' in submodule path 'third_party/nccl/nccl'
```

## To Reproduce

1. `git clone --recursive https://github.com/pytorch/pytorch`. I got commit `8eb228a7f`
1. `git submodule sync; git submodule update --init --recursive`. The submodule update command returns the error described above.
1. `export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}; python setup.py install`

The end of the compilation looks like this:

```
cmake --build . --target install --config Release -- -j 48
[7/5575] Performing build step for 'nccl_external'
FAILED: nccl_external-prefix/src/nccl_external-stamp/nccl_external-build nccl/lib/libnccl_static.a 
cd /home/wmcneill/src/pytorch/third_party/nccl/nccl && env CCACHE_DISABLE=1 SCCACHE_DISABLE=1 make CXX=/home/wmcneill/anaconda3/envs/layoutlm/bin/x86_64-conda_cos6-linux-gnu-c++ CUDA_HOME=/usr/local/cuda NVCC=/usr/local/cuda/bin/nvcc NVCC_GENCODE=-gencode=arch=compute_60,code=sm_60 BUILDDIR=/home/wmcneill/src/pytorch/build/nccl VERBOSE=0 -j && /home/wmcneill/anaconda3/envs/layoutlm/bin/cmake -E touch /home/wmcneill/src/pytorch/build/nccl_external-prefix/src/nccl_external-stamp/nccl_external-build
make: *** No targets specified and no makefile found.  Stop.
[30/5575] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf-lite.dir/__/src/google/protobuf/message_lite.cc.o
In file included from ../third_party/protobuf/src/google/protobuf/message_lite.h:47:0,
                 from ../third_party/protobuf/src/google/protobuf/message_lite.cc:36:
In member function 'google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, google::protobuf::uint8*)',
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at ../third_party/protobuf/src/google/protobuf/implicit_weak_message.h:88:35,
    inlined from 'bool google::protobuf::MessageLite::SerializeToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at ../third_party/protobuf/src/google/protobuf/message_lite.cc:372:49:
../third_party/protobuf/src/google/protobuf/io/coded_stream.h:699:16: warning: 'void* memcpy(void*, const void*, size_t)': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
     std::memcpy(ptr, data, size);
     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In member function 'google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, google::protobuf::uint8*)',
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at ../third_party/protobuf/src/google/protobuf/implicit_weak_message.h:88:35:
../third_party/protobuf/src/google/protobuf/io/coded_stream.h:699:16: warning: 'void* memcpy(void*, const void*, size_t)': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
     std::memcpy(ptr, data, size);
     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In member function 'google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, google::protobuf::uint8*)',
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at ../third_party/protobuf/src/google/protobuf/implicit_weak_message.h:88:35,
    inlined from 'bool google::protobuf::MessageLite::SerializeToFileDescriptor(int) const' at ../third_party/protobuf/src/google/protobuf/message_lite.cc:372:49:
../third_party/protobuf/src/google/protobuf/io/coded_stream.h:699:16: warning: 'void* memcpy(void*, const void*, size_t)': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
     std::memcpy(ptr, data, size);
     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In member function 'google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, google::protobuf::uint8*)',
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at ../third_party/protobuf/src/google/protobuf/implicit_weak_message.h:88:35,
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToFileDescriptor(int) const' at ../third_party/protobuf/src/google/protobuf/message_lite.cc:401:42:
../third_party/protobuf/src/google/protobuf/io/coded_stream.h:699:16: warning: 'void* memcpy(void*, const void*, size_t)': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
     std::memcpy(ptr, data, size);
     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In member function 'google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, google::protobuf::uint8*)',
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at ../third_party/protobuf/src/google/protobuf/implicit_weak_message.h:88:35,
    inlined from 'bool google::protobuf::MessageLite::SerializeToOstream(std::ostream*) const' at ../third_party/protobuf/src/google/protobuf/message_lite.cc:372:49:
../third_party/protobuf/src/google/protobuf/io/coded_stream.h:699:16: warning: 'void* memcpy(void*, const void*, size_t)': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
     std::memcpy(ptr, data, size);
     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
In member function 'google::protobuf::uint8* google::protobuf::io::EpsCopyOutputStream::WriteRaw(const void*, int, google::protobuf::uint8*)',
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToZeroCopyStream(google::protobuf::io::ZeroCopyOutputStream*) const' at ../third_party/protobuf/src/google/protobuf/implicit_weak_message.h:88:35,
    inlined from 'bool google::protobuf::MessageLite::SerializePartialToOstream(std::ostream*) const' at ../third_party/protobuf/src/google/protobuf/message_lite.cc:414:60:
../third_party/protobuf/src/google/protobuf/io/coded_stream.h:699:16: warning: 'void* memcpy(void*, const void*, size_t)': specified size between 18446744071562067968 and 18446744073709551615 exceeds maximum object size 9223372036854775807 [-Wstringop-overflow=]
     std::memcpy(ptr, data, size);
     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~
[54/5575] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotoc.dir/__/src/google/protobuf/compiler/cpp/cpp_message.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 763, in <module>
    build_deps()
  File "setup.py", line 318, in build_deps
    cmake=cmake)
  File "/home/wmcneill/src/pytorch/tools/build_pytorch_libs.py", line 62, in build_caffe2
    cmake.build(my_env)
  File "/home/wmcneill/src/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/home/wmcneill/src/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/home/wmcneill/anaconda3/envs/layoutlm/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '48']' returned non-zero exit status 1.
```

## Expected behavior

I expect PyTorch to build and be installed.

## Environment

```
PyTorch version: 1.7.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.0
Clang version: Could not collect
CMake version: version 3.18.4

Python version: 3.7.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB

Nvidia driver version: 455.32.00
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
```

cc @malfet @seemethere @walterddr

**Comment by ptrblck** [comment] 2020-11-07 06:59
I cannot reproduce this issue, the NCCL submodule can be found, and the mentioned PyTorch commit is installed successfully using CUDA11.1:

```
root@nvdl-a52-luna01:/workspace/src# git clone https://github.com/pytorch/pytorch
Cloning into 'pytorch'...
remote: Enumerating objects: 81, done.
remote: Counting objects: 100% (81/81), done.
[...]

root@nvdl-a52-luna01:/workspace/src# git checkout 8eb228a7f
Note: checking out '8eb228a7f'.
[...]
HEAD is now at 8eb228a7f3 Add support for log_softmax (#47409)

root@nvdl-a52-luna01:/workspace/src/pytorch# git submodule sync; git submodule update --init --recursive
[...]
Submodule 'third_party/nccl/nccl' (https://github.com/NVIDIA/nccl) registered for path 'third_party/nccl/nccl'
[...]
Cloning into '/workspace/src/pytorch/third_party/nccl/nccl'...
[...]
From https://github.com/NVIDIA/nccl
 * branch            cd5a9b73c3028d2496666201588111a8c8d84878 -> FETCH_HEAD
Submodule path 'third_party/nccl/nccl': checked out 'cd5a9b73c3028d2496666201588111a8c8d84878'
[...]

root@nvdl-a52-luna01:/workspace/src/pytorch# export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}; python setup.py install
[...]
```

The NCCL commit is also valid and returns:
https://github.com/NVIDIA/nccl/tree/cd5a9b73c3028d2496666201588111a8c8d84878

Could you clean the build and try to rerun the installation?
If that doesn't help, could you try to checkout NCCL at `cd5a9b7` separately and check, if this also fails on your system?

**Comment by wpm** [comment] 2020-11-08 19:06
Fresh checkout has the same effect.

On further investigation, it appears that a `git rm` got run in `pytorch/third_party/nccl/nccl` after cloning the repository even though I didn't run any other git commands.

```
git status
# On branch master
# Changes to be committed:
#   (use "git reset HEAD <file>..." to unstage)
#
#	deleted:    .gitignore
#	deleted:    LICENSE.txt
#	deleted:    Makefile
#	deleted:    README.md
#	deleted:    ext-net/dummy/Makefile
#	deleted:    ext-net/dummy/plugin.c
#	deleted:    makefiles/common.mk
#	deleted:    makefiles/formatting.mk
#	deleted:    makefiles/version.mk
#	deleted:    pkg/Makefile
[...]
```

The `pytorch/third_party/nccl/nccl` directory is empty. This happened with multiple fresh checkouts.

I fix this by running `git reset HEAD;git checkout -- .` This leaves me with commit `084207e6` of `nccl`. The files present in the directory now look like what is on github.

When I run compilation I now get several errors when compiling the caffe components. They look like this.

```
91 errors detected in the compilation of "/home/wmcneill/x/pytorch/aten/src/ATen/native/cuda/DistributionGeometricKernel.cu".
CMake Error at torch_cuda_generated_DistributionGeometricKernel.cu.o.Release.cmake:281 (message):
  Error generating file
  /home/wmcneill/x/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/native/cuda/./torch_cuda_generated_DistributionGeometricKernel.cu.o


[4496/5577] Building NVCC (Device) object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/torch_cuda_generated_THCTensorTopKDouble.cu.o
FAILED: caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/torch_cuda_generated_THCTensorTopKDouble.cu.o 
cd /home/wmcneill/x/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated && /home/wmcneill/anaconda3/envs/layoutlm/bin/cmake -E make_directory /home/wmcneill/x/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/. && /home/wmcneill/anaconda3/envs/layoutlm/bin/cmake -D verbose:BOOL=OFF -D build_configuration:STRING=Release -D generated_file:STRING=/home/wmcneill/x/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorTopKDouble.cu.o -D generated_cubin_file:STRING=/home/wmcneill/x/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/./torch_cuda_generated_THCTensorTopKDouble.cu.o.cubin.txt -P /home/wmcneill/x/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/THC/generated/torch_cuda_generated_THCTensorTopKDouble.cu.o.Release.cmake
/home/wmcneill/anaconda3/envs/layoutlm/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/bits/stl_pair.h(437): error: argument list for class template "std::pair" is missing

/home/wmcneill/anaconda3/envs/layoutlm/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/bits/stl_pair.h(437): error: expected a ")"

/home/wmcneill/anaconda3/envs/layoutlm/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/bits/stl_pair.h(437): error: template parameter "_T1" may not be redeclared in this scope

/home/wmcneill/anaconda3/envs/layoutlm/x86_64-conda_cos6-linux-gnu/include/c++/7.3.0/bits/stl_pair.h(437): error: expected a ";"
[...]
```

**Comment by wpm** [comment] 2020-11-08 19:07
I also tried the following.

1. `git clone https://github.com/pytorch/pytorch`
2. `cd pytorch pytorch/third_party/nccl/nccl`
3. `git checkout cd5a9b73c3028d2496666201588111a8c8d84878`

This returned `fatal: reference is not a tree: cd5a9b73c3028d2496666201588111a8c8d84878`.

**Comment by ptrblck** [comment] 2020-11-08 22:45
Thanks for the update, @wpm 

I also cannot checkout `cd5a9b73c` directly in NCCL and it seems that this particular commit doesn't belong to any branch of the NCCL repo as seen in the commit message:
https://github.com/NVIDIA/nccl/commit/cd5a9b73c3028d2496666201588111a8c8d84878

I'm still unsure why the PyTorch installation works properly on my system(s). 
As a workaround you could try to checkout https://github.com/NVIDIA/nccl/tree/v2.7.8-1 or https://github.com/NVIDIA/nccl/tree/v2.8 instead. 

@sjeaugey is this particular commit a "2.8-pre-release" and should we rather target e.g. this branch:
https://github.com/NVIDIA/nccl/tree/v2.8 instead?

CC @mingzhe09088 who updated NCCL in https://github.com/pytorch/pytorch/pull/46742

----

For the caffe2 build error:
which `nvcc` and host compiler are you using?

**Comment by wpm** [comment] 2020-11-08 23:59
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Tue_Sep_15_19:10:02_PDT_2020
Cuda compilation tools, release 11.1, V11.1.74
Build cuda_11.1.TC455_06.29069683_0
```

```
anaconda3/envs/layoutlm/bin/x86_64-conda_cos6-linux-gnu-c++
anaconda3/envs/layoutlm/bin/x86_64-conda_cos6-linux-gnu-cc
anaconda3/envs/layoutlm/bin/x86_64-conda_cos6-linux-gnu-g++
anaconda3/envs/layoutlm/bin/x86_64-conda_cos6-linux-gnu-gcc
```

All the C/C++ compilers are 7.3.0. I installed them with Anaconda.

**Comment by ptrblck** [comment] 2020-11-09 09:37
Could you give me some install and usage instructions to use this conda compiler set?
Also, as I think these issues are unrelated, it would be better if you create a separate issue or a forum topic and tag me in it so that I could follow up there in order to keep this issue clean.

**Comment by wjn922** [comment] 2020-11-09 10:19
@wpm I also encounter the same problem.
I firstly update my git version to 2.8.0. Though I have no idea whether it would help or not.
And then I solve the problem by the following steps:
`cd third_party/nccl
git clone https://github.com/NVIDIA/nccl.git
cd nccl
git checkout -b cd5a9b73c3028d2496666201588111a8c8d84878
cd ../../..
git submodule update
git status
git submodule update --init --recursive`

**Comment by malfet** [comment] 2020-11-09 15:46
@ptrblck , cd5a9b73c3028d2496666201588111a8c8d84878 used to correspond to:
```
    2.8.0b14
    
    Optimization for Tree allreduce on A100.

```
from v2.8, but looks like it has been force-updated to `31b5bb6f6447da98b9110c605465f9c09621074e`:
```
    2.8.3-1
    
    Optimization for Tree allreduce on A100.
```

**Comment by sjeaugey** [comment] 2020-11-09 17:31
> @sjeaugey is this particular commit a "2.8-pre-release" and should we rather target e.g. this branch:
> https://github.com/NVIDIA/nccl/tree/v2.8 instead?
Yes, this was a preview commit and any time we update the branch, we force-push a full patch, so those commits should not be referenced; using v2.8 is a more stable option, but it will disappear as soon as it is merged into master.

In general, I'd advise to not rely on preview commit/branches for anything important.

**Closed** 2020-11-09 20:39 UTC
Labels: module: build, triaged
