### ISSUE TITLE
RuntimeError: CUDA_tensor_histogram failed to get free global memory

### ISSUE THREAD

**Issue by hmcezar** [pytorch/pytorch#117545] opened 2024-01-16 14:26 UTC
### 🐛 Describe the bug

When running `torch.bincount` on AMD gpus I get:

```bash
Traceback (most recent call last):
  File "/opt/conda/bin/nequip-train", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.9/site-packages/nequip/scripts/train.py", line 104, in main
    trainer.train()
  File "/opt/conda/lib/python3.9/site-packages/nequip/train/trainer.py", line 780, in train
    self.epoch_step()
  File "/opt/conda/lib/python3.9/site-packages/nequip/train/trainer.py", line 913, in epoch_step
    self.batch_step(
  File "/opt/conda/lib/python3.9/site-packages/nequip/train/trainer.py", line 844, in batch_step
    loss, loss_contrib = self.loss(
  File "/opt/conda/lib/python3.9/site-packages/nequip/train/loss.py", line 104, in __call__
    _loss = self.funcs[key](
  File "/opt/conda/lib/python3.9/site-packages/nequip/train/_loss.py", line 85, in __call__
    N = torch.bincount(ref_dict[AtomicDataDict.BATCH_KEY])
RuntimeError: hipGetLastError() == hipSuccess INTERNAL ASSERT FAILED at "/var/lib/jenkins/pytorch/aten/src/ATen/native/hip/SummaryOps.hip":202, please report a bug to PyTorch. CUDA_tensor_histogram failed to get free global memory
```

I'm using the ROCm/pytorch Docker image to build a singularity container with `nequip` using:
```singularity
bootstrap: docker
from: rocm/pytorch:rocm5.7_ubuntu20.04_py3.9_pytorch_1.13.1

%post
    # Install software
    apt-get update
    apt-get install -y file g++ gcc gfortran make gdb strace wget ca-certificates git --no-install-recommends

    # Clone and install NequIP and Allegro
    pip install wandb
    git clone -b develop --depth 1 https://github.com/mir-group/nequip.git
    cd nequip
    sed -i 's/"torch>=1.10.0,<1.13,!=1.9.0",/"torch>=1.10.0",/g' setup.py
    pip install .
    cd ..
    rm -rf nequip
```

I tried the `rocm/pytorch:rocm5.7_ubuntu20.04_py3.9_pytorch_2.0.1` image as well, and got the same error.
On `rocm/pytorch:latest` I get `RuntimeError: Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding` but I think it might be related to #110940 that didn't hit the image yet (version in this image is `2.2.0a0+gitd925d94`).

Using this container, one can reproduce the error running `nequip-train configs/example.yaml` from the cloned `nequip` repository.
If you use the same container but run in CPU only, you'll get no errors.

### Versions

PyTorch version: 1.13.1+git2f7deaa
Is debug build: False
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: 5.7.31921-d1770ee1b

OS: Ubuntu 20.04.6 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: 17.0.0 (https://github.com/RadeonOpenCompute/llvm-project roc-5.7.0 23352 d1e13c532a947d0cbfc94759c00dcf152294aa13)
CMake version: version 3.26.4
Libc version: glibc-2.31

Python version: 3.9.7 | packaged by conda-forge | (default, Sep 29 2021, 19:23:11)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.14.21-150400.24.81_12.0.75-cray_shasta_c-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: AMD Instinct MI250X
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: 5.7.31921
MIOpen runtime version: 2.20.0
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.960
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.20.3
[pip3] torch==1.13.1+git2f7deaa
[pip3] torch-ema==0.3
[pip3] torch-runstats==0.2.0
[pip3] torchvision==0.14.0a0+5ce4506
[conda] mkl                       2022.0.1           h06a4308_117  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] numpy                     1.20.3                   pypi_0    pypi
[conda] torch                     1.13.1+git2f7deaa          pypi_0    pypi
[conda] torch-ema                 0.3                      pypi_0    pypi
[conda] torch-runstats            0.2.0                    pypi_0    pypi
[conda] torchvision               0.14.0a0+5ce4506          pypi_0    pypi

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hmcezar** [comment] 2024-01-16 15:21
Since what I provided was not exactly a minimal working example, I managed to make one:

```python
import torch

mydata = [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
        6, 6, 6, 6, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7,
        8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 8, 9, 9, 9, 9, 9, 9, 9, 9, 9,
        9, 9, 9, 9, 9, 9]
tensor_mydata = torch.tensor(mydata, device=torch.device('cuda'))

N = torch.bincount(tensor_mydata)
print(N)
```

Which gives:
```bash
Traceback (most recent call last):
  File "/project/project_465000259/musselic/running/test_nequip/nequip/configs/test.py", line 12, in <module>
    N = torch.bincount(tensor_mydata)
RuntimeError: hipGetLastError() == hipSuccess INTERNAL ASSERT FAILED at "/var/lib/jenkins/pytorch/aten/src/ATen/native/hip/SummaryOps.hip":202, please report a bug to PyTorch. CUDA_tensor_histogram failed to get free global memory
```

**Comment by hongxiayang** [comment] 2024-01-16 15:35
@hmcezar I tried your small sample code on MI250x with  `rocm/pytorch:rocm5.7_ubuntu20.04_py3.9_pytorch_2.0.1`, and could not reproduce the error. I got
```
tensor([15, 15, 15, 15, 15, 15, 15, 15, 15, 15], device='cuda:0')
```

**Comment by jeffdaily** [comment] 2024-01-16 17:45
This might be an incompatibility between the rocm userspace version (5.7) from the guest container rocm/pytorch:rocm5.7_ubuntu20.04_py3.9_pytorch_2.0.1 versus the rocm kernel you're using on your host.  Which version of rocm is installed outside the container on your host?  You might need to upgrade the rocm kernel driver on your host.

**Comment by hongxiayang** [comment] 2024-01-29 22:06
@hmcezar  Can we close this issue ? you can re-open it or open a new one after the system admin upgrade the rocm to a newer version

**Comment by hmcezar** [comment] 2024-01-30 08:08
Sure @hongxiayang! Thanks for your help.

**Closed** 2024-01-30 15:30 UTC
Labels: needs reproduction, module: rocm, triaged, module: assert failure
