### ISSUE TITLE
Anaconda installation CUDA requested, cpuonly obtained

### ISSUE THREAD

**Issue by joacorapela** [pytorch/pytorch#32369] opened 2020-01-17 20:15 UTC
## 🐛 Bug

Yesterday I successfuly used Anaconda3 to install pytorch with CUDA on env1 and it worked fine. Today I installed it on a new environment, env2, requested Pytorch Stable 1.4.0 with CUDA 10.1 but obtained Pytorch with cpuonly (which is not GPU enabled). I run collect_env.py on both environments (see below). 

Note that in the working environment (env1):

. the installed pytoch (1.3.1) includes cuda:
pytorch                   1.3.1           cuda100py37h53c1284_0**  
. CUDA used to build PyTorch is detected
. cuda.is_available()==True
. cuda runtime_version is detected

But in the non-working environment (env1):

. the installed pytoch (1.4.0) does not include cuda (cpuonly):
pytorch                   1.4.0               py3.7_cpu_0  [cpuonly]  pytorch
. CUDA used to build PyTorch is NOT detected
. cuda.is_available()==False
. cuda runtime_version is NOT detected

What could be the source of this problem?

# collect_env on Conda env1
Collecting environment information...
PyTorch version: 1.3.1
Is debug build: No
**CUDA used to build PyTorch: 10.0.130**

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
**Is CUDA available: Yes
CUDA runtime version: 10.0.130**
GPU models and configuration: 
GPU 0: Quadro RTX 5000
GPU 1: Quadro RTX 5000

Nvidia driver version: 430.64
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] numpydoc==0.9.1
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
**[conda] pytorch                   1.3.1           cuda100py37h53c1284_0**  
[conda] torchvision               0.4.2           cuda100py37hecfc37a_0

# collect_env on Conda env2
**PyTorch version: 1.4.0**
Is debug build: No
**CUDA used to build PyTorch: Could not collect**

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
**Is CUDA available: No
CUDA runtime version: 10.1.243**
GPU models and configuration: 
GPU 0: Quadro RTX 5000
GPU 1: Quadro RTX 5000

Nvidia driver version: 430.64
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] numpydoc==0.9.1
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
**[conda] pytorch                   1.4.0               py3.7_cpu_0  [cpuonly]  pytorch**
[conda] torchvision               0.5.0                  py37_cpu  [cpuonly]  pytorch

cc @ezyang @gchanan @zou3519

**Comment by ReinforcedMan** [comment] 2020-02-08 15:57
I had a similar issue installing from "conda install pytorch torchvision cudatoolkit=10.1 -c pytorch". I copied this line from the Pytorch main page asking for Cuda 10.1, but it installed Pytorch with cpu only.

I installed with pip, and it fixed the problem.

**Comment by joacorapela** [comment] 2020-02-12 12:12
> @joacorapela What command did you use for installing PyTorch with CUDA?

conda install pytorch torchvision cudatoolkit=10.1 -c pytorch

Today I tried once again and failed to install pytorch with cuda using conda. But, thanks to the comment from https://github.com/ReinforcedMan I was able to install it using pip.

Thanks https://github.com/ReinforcedMan!

**Comment by ezyang** [comment] 2020-02-12 16:05
I'm clearing "needs reproduction" as we have two independent reports of the problem from different users.

**Comment by rgommers** [comment] 2020-03-28 21:54
I tried to reproduce this in a clean env, but it works as expected for me:

```
$ conda create -n pytorch-condabug python=3.7
$ conda activate pytorch-condabug
$ conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
```
`conda list` shows the correct CUDA-enabled pytorch build is installed:

<details>

```
$ conda list
# packages in environment at /home/rgommers/anaconda3/envs/pytorch-condabug:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
blas                      1.0                         mkl  
ca-certificates           2020.1.1                      0  
certifi                   2019.11.28               py37_1  
cudatoolkit               10.1.243             h6bb024c_0  
freetype                  2.9.1                h8a8886c_1  
intel-openmp              2020.0                      166  
jpeg                      9b                   h024ee3a_2  
ld_impl_linux-64          2.33.1               h53a641e_7  
libedit                   3.1.20181209         hc058e9b_0  
libffi                    3.2.1                hd88cf55_4  
libgcc-ng                 9.1.0                hdf63c60_0  
libgfortran-ng            7.3.0                hdf63c60_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.1.0                hdf63c60_0  
libtiff                   4.1.0                h2733197_0  
mkl                       2020.0                      166  
mkl-service               2.3.0            py37he904b0f_0  
mkl_fft                   1.0.15           py37ha843d7b_0  
mkl_random                1.1.0            py37hd6b4f25_0  
ncurses                   6.2                  he6710b0_0  
ninja                     1.9.0            py37hfd86e86_0  
numpy                     1.18.1           py37h4f9e942_0  
numpy-base                1.18.1           py37hde5b4d6_1  
olefile                   0.46                     py37_0  
openssl                   1.1.1e               h7b6447c_0  
pillow                    7.0.0            py37hb39fc2d_0  
pip                       20.0.2                   py37_1  
python                    3.7.7           hcf32534_0_cpython  
pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
readline                  8.0                  h7b6447c_0  
setuptools                46.1.1                   py37_0  
six                       1.14.0                   py37_0  
sqlite                    3.31.1               h7b6447c_0  
tk                        8.6.8                hbc83047_0  
torchvision               0.5.0                py37_cu101    pytorch
wheel                     0.34.2                   py37_0  
xz                        5.2.4                h14c3975_4  
zlib                      1.2.11               h7b6447c_3  
zstd                      1.3.7                h0b5b093_0  
```

</details>

Note that conda will install `pip` into that env, and when it installs Python packages it will also update the `pip` registry of installed packages:

<details>

```
$ which pip
/home/rgommers/anaconda3/envs/pytorch-condabug/bin/pip

$ pip list
Package     Version            
----------- -------------------
certifi     2019.11.28         
mkl-fft     1.0.15             
mkl-random  1.1.0              
mkl-service 2.3.0              
numpy       1.18.1             
olefile     0.46               
Pillow      7.0.0              
pip         20.0.2             
setuptools  46.1.1.post20200323
six         1.14.0             
torch       1.4.0              
torchvision 0.5.0              
wheel       0.34.2
```

</details>

Running `collect_env.py` will (incorrectly) say that `numpy`, `torch` and
`torchvision` were installed with `pip`, other than that it looks as it should:
```
$ python /home/rgommers/code/pytorch/torch/utils/collect_env.py
Collecting environment information...
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Antergos Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.16.5

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.2.89
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 440.64
cuDNN version: /usr/lib/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.0                      166  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch
```
Would be useful if `collect_env.py` listed `cudatoolkit` though.

There's not enough information to say more in this issue so far, `collect_env.py` doesn't give enough information - we need at least `conda list` and preferably the whole history. That whole history can be found in the `conda-meta/history` file inside the env. E.g.:

<details>

```
$ cat ~/anaconda3/envs/pytorch-condabug/conda-meta/history    
==> 2020-03-28 21:54:41 <==
# cmd: /home/rgommers/anaconda3/bin/conda create -n pytorch-condabug python=3.7
# conda version: 4.7.12
+defaults::_libgcc_mutex-0.1-main
+defaults::ca-certificates-2020.1.1-0
+defaults::certifi-2019.11.28-py37_1
+defaults::ld_impl_linux-64-2.33.1-h53a641e_7
+defaults::libedit-3.1.20181209-hc058e9b_0
+defaults::libffi-3.2.1-hd88cf55_4
+defaults::libgcc-ng-9.1.0-hdf63c60_0
+defaults::libstdcxx-ng-9.1.0-hdf63c60_0
+defaults::ncurses-6.2-he6710b0_0
+defaults::openssl-1.1.1e-h7b6447c_0
+defaults::pip-20.0.2-py37_1
+defaults::python-3.7.7-hcf32534_0_cpython
+defaults::readline-8.0-h7b6447c_0
+defaults::setuptools-46.1.1-py37_0
+defaults::sqlite-3.31.1-h7b6447c_0
+defaults::tk-8.6.8-hbc83047_0
+defaults::wheel-0.34.2-py37_0
+defaults::xz-5.2.4-h14c3975_4
+defaults::zlib-1.2.11-h7b6447c_3
# update specs: ['python=3.7']
==> 2020-03-28 21:57:19 <==
# cmd: /home/rgommers/anaconda3/bin/conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
# conda version: 4.7.12
+defaults::blas-1.0-mkl
+defaults::cudatoolkit-10.1.243-h6bb024c_0
+defaults::freetype-2.9.1-h8a8886c_1
+defaults::intel-openmp-2020.0-166
+defaults::jpeg-9b-h024ee3a_2
+defaults::libgfortran-ng-7.3.0-hdf63c60_0
+defaults::libpng-1.6.37-hbc83047_0
+defaults::libtiff-4.1.0-h2733197_0
+defaults::mkl-2020.0-166
+defaults::mkl-service-2.3.0-py37he904b0f_0
+defaults::mkl_fft-1.0.15-py37ha843d7b_0
+defaults::mkl_random-1.1.0-py37hd6b4f25_0
+defaults::ninja-1.9.0-py37hfd86e86_0
+defaults::numpy-1.18.1-py37h4f9e942_0
+defaults::numpy-base-1.18.1-py37hde5b4d6_1
+defaults::olefile-0.46-py37_0
+defaults::pillow-7.0.0-py37hb39fc2d_0
+defaults::six-1.14.0-py37_0
+defaults::zstd-1.3.7-h0b5b093_0
+pytorch::pytorch-1.4.0-py3.7_cuda10.1.243_cudnn7.6.3_0
+pytorch::torchvision-0.5.0-py37_cu101
# update specs: ['torchvision', 'cudatoolkit=10.1', 'pytorch']
```

</details>

@joacorapela or @ReinforcedMan, if you still have the conda environment where `cpuonly` was installed (even if it's now overwritten by a `pip`-installed version), could you please provide the content of `conda-meta/history`? 

If you don't have that environment anymore, could you please try from scratch using the same commands I used?

**Comment by rgommers** [comment] 2020-03-30 16:25
I had another look at this, checking the metadata of the conda package for python 3.7 with cuda 10.1 and cpuonly. That all looks correct.

I also tried to find a way to get the `cpuonly` version from `conda install pytorch torchvision cudatoolkit=10.1 -c pytorch`. This is possible if the environment wasn't clean (e.g. it already had `cpuonly` in it before). Note that that command doesn't _force_ the GPU version, it's just that if for a particular version number there are both `cuda` and `cpuonly` versions of `pytorch` available, the `cuda` version is preferred _unless_ `cpuonly` is specified.

Finally I noticed that the original bug report is from the day where pytorch 1.4.0 was released. It's very well possible that `cpuonly` was available earlier than `cuda10.1` that day, because the former is ~40 MB and the latter ~400 MB, hence it's expected to upload and propagate through the hosting infrastructure faster.

So let's wait for `conda-meta/history` files to confirm. My tentative hypothesis is:
- there's no bug in conda packages or conda itself here
- initial bug was due to `cpuonly` appearing first on the day of release
- re-trying later in the same env is expected to keep giving `cpuonly`
- the second report: not sure, could be also from a non-empty env

**Comment by rgommers** [comment] 2020-04-05 10:23
There's a possible explanation for the observed behavior, I improved `collect_env.py` a little in gh-35646, and without the details in `conda-meta/history` for a conda env where this happened, there's very little else that can be done here. So I'll close the issue.

**Closed by rgommers** 2020-04-05 10:23 UTC
Labels: high priority, module: binaries, triaged

**Comment by rgommers** [comment] 2020-05-02 18:30
In case someone still runs into this: try setting `conda config --set channel_priority strict`.

A similar case was reported on Slack. After some investigation, I could trigger the cpu-only install by first installing 1.5.0 and then downgrading to 1.4.0 without having `channel_priority strict` set. 

This will install the `cuda10.1` package:
```
conda create -n pytorch14
conda activate pytorch14
conda install pytorch==1.4.0 -c pytorch
```

Starting again in a clean env:
```
conda create -n pytorch14
conda activate pytorch14
conda install pytorch==1.5.0 -c pytorch  # installs cuda10.1 version
conda install pytorch==1.4.0 -c pytorch  # wants to install cpu_only, say "no"

conda config --set channel_priority strict
conda install pytorch==1.4.0 -c pytorch   # installs cuda10.1 version
```

**Comment by rgommers** [comment] 2020-05-02 18:31
This is not a bug, it's simply how `conda` behaves. The strict channel priority will anyway become the default in conda 5, and gives fewer surprises like this, so is always good to set (and is recommended in the conda-forge docs [here](https://conda-forge.org/docs/user/introduction.html?highlight=channel_priority).

**Comment by isharifirad** [comment] 2020-08-06 09:41
> > @joacorapela What command did you use for installing PyTorch with CUDA?
> 
> conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
> 
> Today I tried once again and failed to install pytorch with cuda using conda. But, thanks to the comment from https://github.com/ReinforcedMan I was able to install it using pip.
> 
> Thanks https://github.com/ReinforcedMan!

I have similar problem.

**Comment by mlegore** [comment] 2021-11-18 04:39
I have a similar problem, I've used strict channel priority, but it still does not work...

**Comment by yunhao-qian** [comment] 2022-01-10 14:09
I have the same problem. After some experiments, it seems that what caused my issue is the `opencv` package. The CUDA version of pytorch can be installed normally if the `opencv` package does not appear.

**Comment by Jenaer** [comment] 2022-01-11 15:10
I had the same problem as @yunhao-qian where if I installed `opencv=4.1.0` in my conda environment then I could only install the cpu versions of pytorch with the  command `conda install pytorch torchvision torchaudio cudatoolkit=11.3 -c pytorch`. 

I removed the opencv package, ran the same command, and it automatically installed the GPU versions.

**Comment by fti-vsaxena** [comment] 2022-05-02 10:08
I had the same problem but I have verified that if we specify torch version above 1.10  it is working without the environment too.
`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge`

**Comment by Vishesh29** [comment] 2022-05-02 10:11
I had the same problem but I have verified that if we specify the torch version above 1.10  it is working without the environment too.
`conda install pytorch==1.10.1 torchvision==0.11.2 torchaudio==0.10.1 cudatoolkit=11.3 -c pytorch -c conda-forge`

**Comment by wichtlor** [comment] 2022-07-27 10:15
I had the same problem trying to install an environment that worked under linux with cuda but didn't work under windows.
The problem was, that there is no built version of torchvision 0.11.3 with cuda11.1 such that it fell back to the cpu version und windows, while there is one for linux. 
See https://anaconda.org/pytorch/torchvision/files?page=2
ctrl+f = torchvision-0.11.3-py39_cu111

**Comment by dstrande** [comment] 2022-08-17 20:54
If anyone else is still having this issue I've fixed this by specifying the pytorch version in the standard install steps:

conda install pytorch=1.12.1 torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge

**Comment by pseudotensor** [comment] 2022-10-28 18:00
For me, the installation line torch at https://pytorch.org/get-started/locally/ leads to cpu version being installed.

Specifically they say:
```
NOTE: 'conda-forge' channel is required for cudatoolkit 11.6
conda install pytorch torchvision torchaudio cudatoolkit=11.6 -c pytorch -c conda-forge
```
But this leads to cpu torch etc, because it pulls from pytorch first.  One has to get from conda-forge first, e.g.
```
conda install pytorch cudatoolkit=11.6 -c conda-forge
conda install torchvision torchaudio -c pytorch
```
This worked for me despite many other things discussed not being relevant (no cpuonly installed, no issue with GPU/driver/nvcc/etc.)
