### ISSUE TITLE
Irregular behavior of torch.max on cpu & gpu for a tensor containing -inf

### ISSUE THREAD

**Issue by rajarshd** [pytorch/pytorch#10237] opened 2018-08-05 01:32 UTC
## Issue description
```torch.max()``` has irregular behavior on a tensor containing all ```-inf```, depending on whether it is on cpu or gpu.
## Code example
```
>>> var = torch.zeros(5).log()
>>> var
-inf
-inf
-inf
-inf
-inf
[torch.FloatTensor of size 5]
>>> var.max()
-inf
# to gpu
>>> var = var.cuda()
>>> var
-inf
-inf
-inf
-inf
-inf
[torch.cuda.FloatTensor of size 5 (GPU 0)]
>>> var.max()
-3.4028234663852886e+38
```

## Environment
```
PyTorch version: 0.3.1
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-28)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X
GPU 2: GeForce GTX TITAN X
GPU 3: GeForce GTX TITAN X

Nvidia driver version: 390.48
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] msgpack-numpy (0.4.1)
[pip] numpy (1.13.1)
[pip] numpydoc (0.8.0)
[pip] torch (0.3.1)
[pip] torchtext (0.2.1)
[pip] torchvision (0.2.0)
[conda] Could not collect
```

**Comment by SsnL** [comment] 2018-08-05 05:06
reproducible on master

**Comment by apaszke** [comment] 2018-08-05 23:28
It's hard to argue what should variance be for a vector of infinities, but we never really committed to keeping 100% parity between backends. They have different performance characteristics, and so often use different algorithms, which might have subtly different numerical properties (especially in weird edge cases like this one). I'd say this is of low priority.

**Comment by SsnL** [comment] 2018-08-06 00:54
@apaszke the issue is about max, not variance. (The object is named “var” probably to mean “variable”). I think we should fix this soon.

**Comment by apaszke** [comment] 2018-08-06 01:34
Oh ofc, my bad. We probably just initialize the `max` with the smallest non-inf value on CUDA.

**Closed** 2018-09-02 06:10 UTC
