### ISSUE TITLE
PyTorch. DispatchStub: missing CUDA kernel operator ()

### ISSUE THREAD

**Issue by stefanopiovesan** [pytorch/pytorch#27851] opened 2019-10-14 16:12 UTC
## 🐛 Bug

I have this assert using libtorch-win-shared-with-deps-debug-latest.zip loading a saved model:

    cuda_dispatch_ptr INTERNAL ASSERT FAILED at 
    C:\w\1\s\windows\pytorch\aten\src\ATen/native/DispatchStub.h:74, please report a bug to 
    PyTorch. DispatchStub: missing CUDA kernel (operator () at 
    C:\w\1\s\windows\pytorch\aten\src\ATen/native/DispatchStub.h:74)
    (no backtrace available)

It works with the release version libtorch-win-shared-with-deps-latest.zip 

To Reproduce:
1. download the [nightly build](https://download.pytorch.org/libtorch/nightly/cu101/libtorch-win-shared-with-deps-debug-latest.zip) and compile with VS2019.
2. save a model to "cuda":
     `model = models.densenet121(pretrained=True)`
    `# do forward...`
     `traced_script_module.save("traced_resnet_model.pt")`
3. load the model:
    `module = torch::jit::load("traced_resnet_model.pt");`

 - PyTorch Version nightly build:
 - OS W10:
 - https://download.pytorch.org/libtorch/nightly/cu101/libtorch-win-shared-with-deps-debug-latest.zip
 - VS2019:
 - CUDA 10:

**Comment by peterjc123** [comment] 2019-10-14 16:22
Duplicate of https://github.com/pytorch/pytorch/issues/22681.

**Closed by peterjc123** 2019-10-14 16:22 UTC
