### ISSUE TITLE
Feature Request: Add a deterministic version of scatter_add_cuda_kernel

### ISSUE THREAD

**Issue by manacoa** [pytorch/pytorch#50469] opened 2021-01-13 12:01 UTC
Running stable_baselines3 in deterministic mode I get

RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.set_deterministic(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

Thanks

cc @ezyang @gchanan @zou3519 @ngimel @mruberry @kurtamohler

**Comment by mruberry** [comment] 2021-01-19 08:39
Thank you for filing this issue, @manacoa. 

@kurtamohler, maybe we should consider adding checks when the determinism flag is set to see if the operation performed would actually be nondeterministic? Or even implementing a deterministic version of this op?

**Comment by kurtamohler** [comment] 2021-01-19 21:17
@mruberry, seems like this is related to #50750. I like the idea of writing deterministic implementations for operations like this. Ideally, every operation would be available with determinism turned on.

**Comment by LSinev** [comment] 2021-06-18 10:45
As far as i see in the https://pytorch.org/docs/1.9.0/generated/torch.use_deterministic_algorithms.html#torch.use_deterministic_algorithms
`torch.Tensor.scatter_add_() when called on a CUDA tensor` is in paragraph starting with
> The following normally-nondeterministic operations will throw a RuntimeError when mode=True

If it is the same as `scatter_add_cuda_kernel` error of this issue and closing of  #50750 means that there is no real way to _prioritize adding deterministic support for this operation_, please remove this part from error message:
```You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.```

**Comment by kurtamohler** [comment] 2021-06-19 04:15
@LSinev, yes, `torch.Tensor.scatter_add_() when called on a CUDA tensor` is the same as the `scatter_add_cuda_kernel` in this issue.

The closing of #50750 does not mean that we can't write a deterministic implementation for this operation. It should be possible. Asking users to submit issues does help us prioritize. If people request a deterministic implementation of operation A, and no one has requested a deterministic implementation for operation B, then we'll tend to work on operation A first, since we know that someone will benefit from it.

**Comment by ErikVester** [comment] 2021-06-19 14:07
I am running into the same issue. I am quite new in all this, but is there a way to avoid using scatter_add_cuda_kernel? For me it gets used when I call backward() in my RL set-up and I am therefore not sure if there is a way to change this?

**Comment by ngimel** [comment] 2021-06-19 18:23
There's a deterministic implementation of scatter_add_ for 1D inputs (introduced in pytorch 1.9). @ErikVester if that doesn't help, you can try rewriting `gather` op in your network with indexing op.

**Comment by w00zie** [comment] 2021-07-06 12:44
@ErikVester did you manage to work it out somehow?

**Comment by monk1337** [comment] 2021-09-18 05:52
Anyone can share the solution to avoid this error?
Thanks!

**Comment by mruberry** [comment] 2021-09-20 03:08
> Anyone can share the solution to avoid this error?
> Thanks!

To just avoid the error you can stop running in deterministic mode when calling this (nondeterministic) function

**Comment by Acheron-Z** [comment] 2021-12-06 17:37
I'd like to add support for making a deterministic version of scatter_add_cuda_kernel.

This function has been used in science published in a high impact journal and yet we cannot verify the results because of this non-determinism.
  https://www.science.org/doi/abs/10.1126/science.abj8754

When we run the application twice with the same input we get different results.

Reproducibility in science is a big problem
  https://www.nature.com/articles/533452a

**Comment by nicosacco** [comment] 2022-02-05 16:02
I am getting the same error while using `gather`

**Comment by kurtamohler** [comment] 2022-02-07 19:19
@nicosacco, for forward passes, you can just wrap the operation in `use_deterministic_algorithms(True/False)` calls to turn off determinism temporarily:

```python
torch.use_deterministic_algorithms(False)
operation()
torch.use_deterministic_algorithms(True)
```

But unfortunately, `torch.gather` throws the nondeterministic error in the backward pass, not the forward pass. I'm pretty sure we currently don't have a way to toggle the determinism setting for just one node in the autograd graph. We could consider adding that feature if it would be useful

**Comment by mruberry** [comment] 2022-04-04 17:08
cc @cpuhrsch @mikaylagawarecki

**Comment by ezyang** [comment] 2022-04-04 17:10
> I'm pretty sure we currently don't have a way to toggle the determinism setting for just one node in the autograd graph. We could consider adding that feature if it would be useful

The last time we discussed it was here: https://github.com/pytorch/pytorch/issues/72831

Now we have a use case. Someone should implement it.

**Comment by kurtamohler** [comment] 2022-06-06 20:40
To add deterministic support for multidimensional inputs, it seems like it should be pretty straightforward to flatten the inputs, add offsets to the indices to get equivalent 1-D indices, and then run the deterministic 1-D implementation. Of course if the inputs aren't contiguous, we'd have to copy them, but determinism usually comes with a performance cost anyway.

Here's where the deterministic implementation of `scatter_add` CUDA for 1-D inputs is: https://github.com/pytorch/pytorch/blob/519347df49fe50fb46f40544e22225be485efb06/aten/src/ATen/native/TensorAdvancedIndexing.cpp#L1537

@ngimel, does this seem like a good idea?

**Closed** 2022-09-07 03:13 UTC
Labels: high priority, feature, module: cuda, triaged, module: determinism, module: scatter & gather ops
