### ISSUE TITLE
[PyTorch] ImportError: cannot import name '_TensorBase'

### ISSUE THREAD

**Issue by EmmaNguyen** [pytorch/pytorch#7701] opened 2018-05-19 06:50 UTC
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description

(Detailed) (Version 0.4.0) Stated as above applied to both cpus and single gpu

## Code example
```
from torch.tensor import _TensorBase
````
## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2: PyTorch
- How you installed PyTorch (conda, pip, source): Conda
- Build command you used (if compiling from source): 
- OS: Linux
- PyTorch version: 0.4.0
- Python version: 3.5.4
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

or

```
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 17.10
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.5
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.14.0)
[pip] torch (0.4.0)
[pip] torchvision (0.2.1)
[conda] pytorch                   0.4.0           py35_cuda8.0.61_cudnn7.1.2_1    pytorch
[conda] torchvision               0.2.1                    py35_1    pytorch
```

**Comment by apaszke** [comment] 2018-05-19 17:54
Not sure why would that be a problem? This class was for internal use only (as indicated by the underscore prefix), so we didn't promise it will be there in the future. Closing as not a bug.

**Closed by apaszke** 2018-05-19 17:54 UTC

**Comment by EmmaNguyen** [comment] 2018-05-21 05:57
It is a problem with a research code that I have been working for several months, now trying to refactor and upgrade with new features and modules. This class does not work on 0.4.0 but 0.3.0, however, I could not find any reference or docstring regarding articulate this issue. Thanks for providing information.
