### ISSUE TITLE
torch.split can't accept Tensor as the second positional argument in tracing mode

### ISSUE THREAD

**Issue by dreamingleo** [pytorch/pytorch#27584] opened 2019-10-09 00:20 UTC
## 🐛 Bug

In tracing mode integer input is converted to Tensor. However there's no corresponding torch.split that accepts Tensor as the second positional argument.

e.g.

  torch.split(_1, _1.size(1) // 2, dim=1)      # _1.size(1) returns a Tensor in tracing mode
  
  torch/functional.py", line 77, in split
  return tensor.split(split_size_or_sections, dim)

  torch/tensor.py", line 339, in split
  return super(Tensor, self).split_with_sizes(split_size, dim)

TypeError: split_with_sizes(): argument 'split_sizes' (position 1) must be tuple of ints, not Tensor

cc @ezyang @gchanan @zou3519 @suo

**Comment by cpuhrsch** [comment] 2019-10-10 17:20
I'm flagging this high priority as we're likely going to revisit this operator in context of tracing and in context of https://github.com/pytorch/pytorch/issues/27551 so we can fix this together.

**Comment by ezyang** [comment] 2019-10-11 17:03
Closing this as a dupe of the other issue

**Closed by ezyang** 2019-10-11 17:03 UTC
Labels: high priority, jit, triage review

**Comment by 227BaronChen** [comment] 2020-09-19 03:35
I was wondering has anyone solve the problem?

**Comment by 227BaronChen** [comment] 2020-09-19 05:15
I found a solution that seems to work. Using “int(_1.size(1) // 2)” instead of “_1.size(1) // 2”
