### ISSUE TITLE
Cannot compile CUDAExtension: cublasGetStream_v2 unresolved

### ISSUE THREAD

**Issue by lostmsu** [pytorch/pytorch#83385] opened 2022-08-14 03:13 UTC
### 🐛 Describe the bug

I am trying to install https://github.com/NVIDIA/apex from source.

The build (which uses `CUDAExtension`) fails with

> fused_weight_gradient_dense_16bit_prec_cuda.obj : error LNK2001: unresolved external symbol cublasGetStream_v2

In the log I can see linker does not have a flag to link cublas.lib: these are the only libraries linked against: c10.lib torch.lib torch_cpu.lib torch_python.lib cudart.lib c10_cuda.lib torch_cuda_cu.lib torch_cuda_cpp.lib

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: 13.0.0 (https://github.com/llvm/llvm-project.git d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
CMake version: version 3.23.22060601-MSVC_2
Libc version: N/A

Python version: 3.10.4 | packaged by conda-forge | (main, Mar 30 2022, 08:38:02) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 516.94
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] performer-pytorch==1.1.4
[pip3] torch==1.12.1+cu116
[pip3] torchaudio==0.12.1+cu116
[pip3] torchvision==0.13.1+cu116
[conda] numpy                     1.23.1                   pypi_0    pypi
[conda] performer-pytorch         1.1.4                    pypi_0    pypi
[conda] torch                     1.12.1+cu116             pypi_0    pypi
[conda] torchaudio                0.12.1+cu116             pypi_0    pypi
[conda] torchvision               0.13.1+cu116             pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @malfet @zou3519 @ngimel

**Comment by lostmsu** [comment] 2022-08-14 03:16
Does not seem to be a bug. There should be a way to add CUDA libraries to link against.

**Comment by chengscott** [comment] 2022-08-17 20:11
The problem is caused by missing libraries in setup.py of nvidia/apex.
You can add the kwarg `libraries=['cublas', 'cublasLt']` to `CUDAExtension`.

Reference: https://setuptools.pypa.io/en/latest/userguide/ext_modules.html#setuptools.Extension

**Comment by cristianPanaite** [comment] 2023-01-12 07:11
Hello @lostmsu,

Does the workaround provided by @chengscott work for you?

**Comment by lostmsu** [comment] 2023-01-12 23:20
@cristianPanaite this was a while ago, but I believe I was able to build APEX by tweaking its setup.py.

**Comment by cristianPanaite** [comment] 2023-01-13 08:39
@lostmsu Alright. It seems to me that this is an APEX problem. 

Considering that this is not a PyTorch bug and that you found a solution, I suggest to open a new issue on Apex repo if you remember the solution and think that this is indeed a bug which is still present and close this one.

What do you think about that?

**Comment by cristianPanaite** [comment] 2023-05-24 06:19
Closing as the ticket is stale and not related to PyTorch. Please feel free to create a new issue if the problem reappears.

**Closed by cristianPanaite** 2023-05-24 06:19 UTC
Labels: module: windows, module: cpp-extensions, module: cuda, triaged
