### ISSUE TITLE
Second derivative of automatically calculated derivative in custom autograd function wrong

### ISSUE THREAD

**Issue by marvinfriede** [pytorch/pytorch#99523] opened 2023-04-19 13:17 UTC
### 🐛 Describe the bug

I have a function with multiple parameters. For one parameter, I need a custom backward function, while the others should be calculated automatically. I created a minimal example based on #74802. While, `gradcheck` works,  `gradgradcheck` fails.

```python
import torch

def my_square(x):
    return x**2

class Square(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        x = x.detach().requires_grad_()
        ctx.x = x

        with torch.enable_grad():
            ctx.result = my_square(x)
        return ctx.result.detach()

    @staticmethod
    def backward(ctx, grad_out):
        (grad_x,) = torch.autograd.grad(
            ctx.result,
            ctx.x,
            grad_outputs=grad_out,
            create_graph=True,
        )

        return grad_x

x = torch.tensor([2, 3, 4], requires_grad=True, dtype=torch.double)
assert torch.autograd.gradcheck(Square.apply, x)
assert torch.autograd.gradgradcheck(Square.apply, x)
```

According to the error, I assume the analytical gradient is wrong.

```
torch.autograd.gradcheck.GradcheckError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 0.5797,  0.0000,  0.0000],
        [ 0.0000,  1.4253,  0.0000],
        [ 0.0000,  0.0000, -0.7444]], dtype=torch.float64)
analytical:tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

```

### Versions

Python 3.10.6 and PyTorch 2.0.0+cu117

**Comment by soulitzer** [comment] 2023-04-20 16:48
Closing because this is expected behavior. The grad_x you computed in backward is a function of x, but because you detached x in the forward, those gradients won't properly flow back to the original x.

You could technically get something to work by just not detaching, but I'm not really sure of why someone would want to do this:
```python
import torch

def my_square(x):
    return x**2

class Square(torch.autograd.Function):
    @staticmethod
    def forward(ctx, x):
        with torch.enable_grad():
          result = my_square(x)
        ctx.save_for_backward(x, result)

        return result.clone()

    @staticmethod
    def backward(ctx, grad_out):
        x, result = ctx.saved_tensors
        (grad_x,) = torch.autograd.grad(
            result,
            x,
            grad_outputs=grad_out,
            create_graph=True,
        )

        return grad_x

x = torch.tensor([2, 3, 4], requires_grad=True, dtype=torch.double)
out = Square.apply(x)
assert torch.autograd.gradcheck(Square.apply, x)
assert torch.autograd.gradgradcheck(Square.apply, x)
```
Feel free to open an issue on the forums https://discuss.pytorch.org/c/autograd/7 if you still have any questions.

**Closed by soulitzer** 2023-04-20 16:48 UTC
