### ISSUE TITLE
[functorch] [aot_autograd] 

### ISSUE THREAD

**Issue by sanketpurandare** [pytorch/pytorch#86427] opened 2022-10-06 20:10 UTC
This is what I am trying to do:

1. Create an input and target tensor
2. Create a list of models for ensemble
3. Use vmap to create an ensemble
4. Obtain the vmap function and pass it to aot_function, to obtain the forward and backward graphs

Repro:
```
from typing import List
import torch
from torch._subclasses import FakeTensorMode, FakeTensor
from functorch.compile import aot_function, print_compile, config, aot_module
from functorch import make_functional_with_buffers, vmap, combine_state_for_ensemble
from functorch._src.named_members_polyfill import _named_parameters, _named_buffers
from torchvision.models import resnet18

g = {}
def fake_wrapper(gtype):
    def fake_compiler(fx_g, inps):
        print(fx_g.code)
        nonlocal gtype
        g[gtype] = fx_g
        return fx_g
    return fake_compiler


inp = torch.randn(32, 3, 224, 224, dtype=torch.float32).cuda()
targets = torch.zeros(32, dtype=int).cuda()

b_models:List[torch.nn.Module] = [resnet18().cuda() for _ in range(5)]

func_model, params, buffers = combine_state_for_ensemble(b_models)
for p in params:
    p.requires_grad = True

def compute_loss(weights, buffers, batch, targets):
    output = func_model(weights, buffers, batch)
    loss = torch.nn.functional.nll_loss(output,targets)
    return loss
parallel_func = vmap(compute_loss, in_dims=(0,0,None, None))
aot_func = aot_function(parallel_func, fake_wrapper("forward"), fake_wrapper("backward"))
out = aot_func(params, buffers, inp, targets)
out.mean().backward()
```

Error:
`RuntimeError: !self.requires_grad() || self.is_contiguous() INTERNAL ASSERT FAILED at “/scratch/anijain/work/pytorch/aten/src/ATen/native/TensorShape.cpp”:3609, please report a bug to PyTorch. as_strided_scatter is currently only supported for contiguous inputs
While executing %new_empty_strided_1 : [#users=1] = call_function[target=torch.ops.aten.new_empty_strided.default](args = (%copy__1, [5, 512, 32, 7, 7], [25088, 49, 125440, 7, 1]), kwargs = {})
Original traceback:
Gradient addition node due to multiple use of tensor around:`

cc @zou3519 @bdhirsh @ezyang @msaroufim @wconstab @anijain2305 @soumith

**Comment by ezyang** [comment] 2022-10-07 00:15
For reference, here is the joint forward backward before it breaks: https://gist.github.com/ezyang/ddbd998f7062b6090424e86953309d18

**Comment by ezyang** [comment] 2022-10-07 00:15
cc @Chillee @zou3519

**Comment by ezyang** [comment] 2022-10-07 01:16
Actually this looks like a functionalization problem. cc @bdhirsh

**Comment by ezyang** [comment] 2022-10-07 01:32
This fixes it

```
diff --git a/functorch/_src/aot_autograd.py b/functorch/_src/aot_autograd.py
index fc561c6d4f..ba2a4efd77 100644
--- a/functorch/_src/aot_autograd.py
+++ b/functorch/_src/aot_autograd.py
@@ -374,7 +374,7 @@ def aot_dispatch_autograd(flat_fn, flat_args: List[Tensor], aot_config: AOTConfi
         # view and inplace ops that come from primtorch.
         # Eventually, functionalization should support primtorch view/inplace ops,
         # which will make it ok to run decompositions before functionalization.
-        fx_g = make_fx(functionalize(fake_fn), aot_config.decompositions)(*joint_inputs)
+        fx_g = make_fx(functionalize(fake_fn, remove='mutations_and_views'), aot_config.decompositions)(*joint_inputs)
         fx_g.graph.eliminate_dead_code()
         fx_g.recompile()
     else:
diff --git a/torchgen/gen_functionalization_type.py b/torchgen/gen_functionalization_type.py
index 2e85f05f6c..f5cdfe2849 100644
--- a/torchgen/gen_functionalization_type.py
+++ b/torchgen/gen_functionalization_type.py
@@ -91,7 +91,7 @@ at::Tensor view_copy_symint(const at::Tensor & self, at::SymIntArrayRef size) {
     return self.reshape_symint(size);
   } else {
     auto output = at::_ops::view::call(self, size);
-    return output.clone();
+    return output.clone(at::MemoryFormat::Contiguous);
   }
 }
 """
@@ -117,13 +117,13 @@ at::Tensor view_copy_symint(const at::Tensor & self, at::SymIntArrayRef size) {
 
     if g.view.func.returns[0].type == BaseType(BaseTy.Tensor):
         return_cloned_output = """\
-  return output.clone();"""
+  return output.clone(at::MemoryFormat::Contiguous);"""
     else:
         # If the return type is a list, we need to clone each tensor in the list.
         return_cloned_output = f"""\
   {view_copy_sig.returns_type().cpp_type()} out_clone;
   for (const auto i : c10::irange(output.size())) {{
-    out_clone.push_back(output[i].clone());
+    out_clone.push_back(output[i].clone(at::MemoryFormat::Contiguous));
   }}
   return out_clone;"""
 
```

However, we should understand (1) why so many `as_strided` show up in the trace prior to autograd, and (2) whether or not we can have functionalize desugar copies into as strided views as `contiguous().as_strided_scatter()` (or maybe we can figure out why we are tracing the joint graph with requires_grad == True)

**Comment by ezyang** [comment] 2022-10-07 04:02
OK, so I figured out why we have so many `as_strided`: we should apply the XLA view fn style. In CPU/CUDA, when we do the backwards of inplace operations on views, we shortcut all of the views by just applying AsStrided. In practice, this means every `relu_()` produces an as strided in backward.

You can prevent the emission of AsStrided by forcing autograd to generate view functions instead. This diff turns it on unconditionally:

```
diff --git a/tools/autograd/gen_inplace_or_view_type.py b/tools/autograd/gen_inplace_or_view_type.py
index d79212a093..f9334d8c5b 100644
--- a/tools/autograd/gen_inplace_or_view_type.py
+++ b/tools/autograd/gen_inplace_or_view_type.py
@@ -158,7 +158,7 @@ at::_ops::${unambiguous_name}::call(${unpacked_args})"""
 SETUP_REPLAY_VIEW_IF_NOT_SUPPORT_AS_STRIDED_OR_VIEW_WITH_METADATA_CHANGE = CodeTemplate(
     """\
 std::function<at::Tensor(const at::Tensor&)> func=nullptr;
-if (${is_view_with_metadata_change} || !self.unsafeGetTensorImpl()->support_as_strided()) {
+if (${is_view_with_metadata_change} || !self.unsafeGetTensorImpl()->support_as_strided() || true) {
   ${replay_view_func}
 }
 """
```

but we need to gate this on ... tracing ... or maybe the tensor having Python key or something (something something tensor subclasses probably don't want to see as strided?)

**Comment by albanD** [comment] 2022-10-07 13:04
Having the dispatch subclass report that they don't support as_strided is something we considered in the past but never did.
If we can take an extra boolean field on the TensorImpl, we can just make this an argument to `_make_{wrapper_}subclass()` and make sure we pass it for FakeTensor.
Does that sound good?

**Comment by ezyang** [comment] 2022-10-07 14:09
We agreed on making this toggleable for tensor subclasses. TLS might also be helpful later but it can be added later.

**Comment by albanD** [comment] 2022-10-07 14:33
Mode support will have to wait the TLS version anyways.
And no it doesn't prevent you from using as_strided() just that autograd won't use it. I'll find a nicer name for the user facing API (maybe).

**Comment by bdhirsh** [comment] 2022-10-07 14:58
Separately, on the as_strided_scatter error. Maybe instead of erroring, we should just take the perf hit and call `.contiguous()` on the input before running it? Since once we stop calling `as_strided()` during view replays while tracing, this should come up very rarely.

Alternatively we can just get `backward()` support for as_strided_scatter working, but that is definitely non-trivial and probably not high priority (https://github.com/pytorch/pytorch/blob/0e639ff45c616946fb3e5e3f06b9486d88ce86ca/torch/csrc/autograd/FunctionsManual.cpp#L2890)

**Comment by ezyang** [comment] 2022-10-07 15:16
I think it's semantically incorrect to call contiguous on the input before running it. The problem is that `as_strided_scatter` *ignores* the pre-existing stride information on the Tensor. So for example, if you had a `(2, 2)` tensor with strides `(2, 1)`, or if you had strides `(1, 2)`, `as_strided(t, (2, 2), (2, 1))` would be a no-op in the first case, but a transpose in the second case. If you contiguified the second tensor before calling as strided, it would turn into a no-op. This is why it's so complicated.

It is better to just avoid as_strided, IMO

**Comment by sanketpurandare** [comment] 2022-10-07 21:29
@ezyang @albanD  The patches still don't work for me. 
pytorch torchdynamo etc all have been rebuilt today:10/07/2022
Pasting the complete stack trace. (You can see the patch in practice)

```
Traceback (most recent call last):
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/testing/test_patch.py", line 34, in <module>
    out = aot_func(params, buffers, inp, targets)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/functorch/_src/aot_autograd.py", line 657, in returned_function
    compiled_fn = create_aot_dispatcher_function(
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/torchdynamo/torchdynamo/utils.py", line 76, in time_wrapper
    r = func(*args, **kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/functorch/_src/aot_autograd.py", line 510, in create_aot_dispatcher_function
    aot_dispatch_autograd(flat_fn, fake_flat_tensor_args, aot_config)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/functorch/_src/aot_autograd.py", line 378, in aot_dispatch_autograd
    fx_g = make_fx(functionalize(fake_fn, remove='mutations_and_views'), aot_config.decompositions)(*joint_inputs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/experimental/proxy_tensor.py", line 652, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/experimental/proxy_tensor.py", line 400, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/_symbolic_trace.py", line 739, in trace
    (self.create_arg(fn(*args)),),
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/_symbolic_trace.py", line 614, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/experimental/proxy_tensor.py", line 414, in wrapped
    out = f(*tensors)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/functorch/_src/vmap.py", line 35, in fn
    return f(*args, **kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/functorch/_src/eager_transforms.py", line 1460, in wrapped
    func_outputs = func(*func_args, **func_kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/functorch/_src/aot_autograd.py", line 370, in fake_fn
    return torch.fx.Interpreter(fx_g).run(primals, tangents)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/interpreter.py", line 130, in run
    self.env[node] = self.run_node(node)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/interpreter.py", line 171, in run_node
    return getattr(self, n.op)(n.target, args, kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/interpreter.py", line 243, in call_function
    return target(*args, **kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/utils/_python_dispatch.py", line 101, in __torch_dispatch__
    return old.__torch_dispatch__(func, types, args, kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/experimental/proxy_tensor.py", line 440, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/experimental/proxy_tensor.py", line 465, in inner_torch_dispatch
    out = proxy_call(self, func, args, kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/fx/experimental/proxy_tensor.py", line 304, in proxy_call
    out = func(*args, **kwargs)
  File "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/torch/_ops.py", line 257, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: !self.requires_grad() || self.is_contiguous() INTERNAL ASSERT FAILED at "/net/rcstorenfs02/ifs/rc_labs/idreos_lab/users/spurandare/develop/pytorch/aten/src/ATen/native/TensorShape.cpp":3633, please report a bug to PyTorch. as_strided_scatter is currently only supported for contiguous inputs

While executing %new_empty_strided_1 : [#users=1] = call_function[target=torch.ops.aten.new_empty_strided.default](args = (%copy__1, [5, 512, 32, 7, 7], [25088, 49, 125440, 7, 1]), kwargs = {})
Original traceback:
Gradient addition node due to multiple use of tensor around:
```

**Comment by ezyang** [comment] 2022-10-07 21:43
I tested the patch on the symbolic-shapes branch (https://dev-discuss.pytorch.org/t/state-of-symbolic-shapes-branch/777/6) so there might be other bugfixes on that branch you need

**Comment by sanketpurandare** [comment] 2022-10-08 23:05
@ezyang patches worked with the branch! thanks

**Comment by bdhirsh** [comment] 2023-12-11 23:47
hmm, I ran the repro again and it no longer errors for me. Tentatively closing, feel free to re-open if you still have issues.

**Closed by bdhirsh** 2023-12-11 23:47 UTC
Labels: triaged, module: vmap, module: functionalization, oncall: pt2, module: aotdispatch, module: pt2-dispatcher
