### ISSUE TITLE
Imaginary part is lost in functorch.jacrev(torch.linalg.eigvals)

### ISSUE THREAD

**Issue by i-a-morozov** [pytorch/pytorch#90499] opened 2022-12-08 06:19 UTC
```python
import torch
import functorch

m = torch.tensor([[0.30901699437494745, 0.9510565162951535], [-0.9510565162951535, 0.30901699437494745]], dtype=torch.float64)

print((functorch.jacfwd(torch.linalg.eigvals)(m)))
print()

print((functorch.jacrev(torch.linalg.eigvals)(m)))
print()

# tensor([[[0.5000+0.0000j, 0.0000+0.5000j],
#          [0.0000-0.5000j, 0.5000+0.0000j]],

#         [[0.5000+0.0000j, 0.0000-0.5000j],
#          [0.0000+0.5000j, 0.5000+0.0000j]]], dtype=torch.complex128)

# tensor([[[0.5000, 0.0000],
#          [0.0000, 0.5000]],

#         [[0.5000, 0.0000],
#          [0.0000, 0.5000]]], dtype=torch.float64)
```
## Edit. This second part is fixed
Why/where `torch.allclose` is invoked in `functorch.jacrev(torch.linalg.eig)`? 
Is it revalted to normalization of eigenvectors?

```python
import torch
import functorch

m = torch.tensor([[0.30901699437494745, 0.9510565162951535], [-0.9510565162951535, 0.30901699437494745]], dtype=torch.float64)

# OK
functorch.jacfwd(torch.linalg.eig)(m)

# RuntimeError: vmap over torch.allclose isn't supported yet. Please voice your support over at github.com/pytorch/functorch/issues/275
functorch.jacrev(torch.linalg.eig)(m)
```
cc @ezyang @gchanan @zou3519 @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7 @anjali411 @dylanbespalko @mruberry @Chillee @samdow @soumith

**Comment by zou3519** [comment] 2022-12-08 22:02
There's a couple of issues here, but I'm not sure if the way we handle complex autograd is expected or not (cc @anjali411, @albanD).

**Comment by albanD** [comment] 2022-12-28 11:24
The problem is that _chunked_standard_basis_for_ is not handling complext numbers properly. It should generate twice as many basis when the Tensor is conplex, one with 1 and one with 1j.

There is a more detailed doc on the complex autograd at: https://pytorch.org/docs/stable/notes/autograd.html#autograd-for-complex-numbers

**Comment by lezcano** [comment] 2022-12-28 13:28
About the `allclose`, we can elide that check if we have tensor subclasses, to allow for compositionality.

**Comment by lezcano** [comment] 2022-12-28 13:28
I'll submit a fix for that bit later today.

**Comment by atalman** [comment] 2023-02-06 20:11
@kshitij12345 @lezcano  could you please update ETA for this task? Since this is targeted for release 2.0 we would need fix to be landed by Feb 10, 2023

**Comment by lezcano** [comment] 2023-02-06 20:37
@kshitij12345 do you think you can take on this one? Otherwise, I can submit a fix for it tomorrow.

**Comment by kshitij12345** [comment] 2023-02-07 07:43
@lezcano it would be great if you can take care of it. I am still unsure about a couple of things. Thanks!

**Comment by lezcano** [comment] 2023-02-08 14:33
Filled a more comprehensive explanation of what's going on here in https://github.com/pytorch/pytorch/issues/90499. Let's track it there.

**Closed by lezcano** 2023-02-08 14:33 UTC
Labels: high priority, module: autograd, triaged, module: complex, actionable, module: correctness (silent), complex_autograd, module: functorch
