### ISSUE TITLE
The RNN implementation example in the documentation may be incorrect

### ISSUE THREAD

**Issue by suzakuwcx** [pytorch/pytorch#140928] opened 2024-11-18 04:50 UTC
### 📚 The doc issue

Link: 
https://pytorch.org/docs/main/generated/torch.nn.RNN.html#torch.nn.RNN
https://pytorch.org/docs/stable/generated/torch.nn.RNN.html#torch.nn.RNN

```
for t in range(seq_len):
    for layer in range(num_layers):
        h_t[layer] = torch.tanh(
            x[t] @ weight_ih[layer].T
            + bias_ih[layer]
            + h_t_minus_1[layer] @ weight_hh[layer].T
            + bias_hh[layer]
        )
    output.append(h_t[-1])
    h_t_minus_1 = h_t
```

After the first layer in the RNN, each subsequent layer should receive the output of the previous layer. Therefore, the input to the current layer should be h_t[layer - 1] rather than x[t]

Next, I tried printing the model parameters to inspect them.
```
model = nn.RNN(input_size=100, hidden_size=4, num_layers=3)
for weight in model.all_weights:
    for params in weight:
        print(params.shape)

# torch.Size([4, 100])
# torch.Size([4, 4])
# torch.Size([4]) 
# torch.Size([4]) 
# torch.Size([4, 4]) 
# torch.Size([4, 4]) 
# torch.Size([4]) 
# torch.Size([4])
# torch.Size([4, 4])
# torch.Size([4, 4])
# torch.Size([4])
# torch.Size([4])
```
It in line with my guess

### Suggest a potential alternative/fix

New implementation here
```
# Efficient implementation equivalent to the following with bidirectional=False
def forward(x, hx=None):
    if batch_first:
        x = x.transpose(0, 1)
    seq_len, batch_size, _ = x.size()
    if hx is None:
        hx = torch.zeros(num_layers, batch_size, hidden_size)
    h_t_minus_1 = hx
    h_t = hx
    output = []
    for t in range(seq_len):
        h_t[0] = torch.tanh(
                x[t] @ weight_ih[layer].T
                + bias_ih[layer]
                + h_t_minus_1[layer] @ weight_hh[layer].T
                + bias_hh[layer]
            )

        for layer in range(1, num_layers):
            h_t[layer] = torch.tanh(
                h_t[layer - 1] @ weight_ih[layer].T
                + bias_ih[layer]
                + h_t_minus_1[layer] @ weight_hh[layer].T
                + bias_hh[layer]
            )
            
        output.append(h_t[-1])
        h_t_minus_1 = h_t
    output = torch.stack(output)
    if batch_first:
        output = output.transpose(0, 1)
    return output, h_t
```

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mikaylagawarecki** [comment] 2024-11-21 20:42
Thanks! Closing as this reports issue that is duplicate of https://github.com/pytorch/pytorch/issues/138401 and https://github.com/pytorch/pytorch/issues/136926 

There is a PR to fix this https://github.com/pytorch/pytorch/pull/136971 so will close to point to https://github.com/pytorch/pytorch/issues/136926

**Closed by mikaylagawarecki** 2024-11-21 20:42 UTC
Labels: module: nn, module: rnn, triaged, topic: docs
