### ISSUE TITLE
Dynamo trouble shooting dead link

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#103276] opened 2023-06-08 22:22 UTC
### 📚 The doc issue

The dynamo page https://pytorch.org/docs/stable/dynamo/troubleshooting.html#accuracy-debugging link to TROUBLESHOOTING results in a dead link for me.

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @ipiszy @aakhundov

**Comment by SANTHOSH-MAMIDISETTI** [comment] 2023-06-10 19:25
can I work over it @rohan-varma  @ezyang  , 
If yes , please assign me Thanks

**Comment by ezyang** [comment] 2023-06-10 19:37
just send in pr

**Comment by SANTHOSH-MAMIDISETTI** [comment] 2023-06-10 19:39
> just send in pr

definitely , Thanks

**Comment by SANTHOSH-MAMIDISETTI** [comment] 2023-06-10 19:57
@ezyang  seems like the issue needs to be fixed at https://github.com/pytorch/pytorch.github.io repo

**Comment by SANTHOSH-MAMIDISETTI** [comment] 2023-06-10 20:39
@ezyang  there happens to be no "TROUBLESHOOTING.md" file 


![image](https://github.com/pytorch/pytorch/assets/92091342/891b04cd-a342-4206-8ed2-465a4671348e)


but in the line 660, they are calling the file which isn't there in the whole repo .


![image](https://github.com/pytorch/pytorch/assets/92091342/f969777b-dbf3-44b0-bccd-da8619be5c5b)

The same missing file was called again  in line 1086 


![image](https://github.com/pytorch/pytorch/assets/92091342/425f1caf-c37d-4a8c-bcb2-31a0ff5399cd)


This is due to a missing file , What would you suggest me to do ?

**Comment by svekars** [comment] 2024-05-09 18:53
I believe the [Troubleshooting](https://pytorch.org/docs/main/torch.compiler_troubleshooting.html) section was overhauled and the issue is no longer present. Closing as resolved. Feel free to reopen.

**Closed** 2024-06-18 18:50 UTC
Labels: good first issue, triaged, topic: docs, oncall: pt2, module: dynamo
