### ISSUE TITLE
nn.Linear does not give an error, even when the input matrix is too large or too small

### ISSUE THREAD

**Issue by sveinnpalsson** [pytorch/pytorch#62537] opened 2021-07-31 16:57 UTC
## 🐛 Bug

Shouldn't the nn.Linear layer give an error when you feed it a matrix that has size different from the expected size?

```
batch_size=10
layer = torch.nn.Linear(3000,512).cuda()
x = torch.rand(batch_size,5000).cuda()
y = layer(x)
print(y.shape) #torch.Size([10, 512])
```

Because the expected input size to the layer is 3000, and the variable x has 5000, I would expect an error. But what seems to happen is the extra columns of x are just ignored.

Interestingly, removing the .cuda(), an error does occur as it should.

Also, passing a too small matrix to Linear does not produce an error either:

```
batch_size=10
layer = torch.nn.Linear(3000,512).cuda()
x = torch.rand(batch_size,5000).cuda()
y = layer(x[:,:100])
print(y.shape) #torch.Size([10, 512])
```

It seems the slicing is simply ignored.

## Environment

Please copy and paste the output from our
[environment collection script]Collecting environment information...
```
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.1 (default, Jan  8 2020, 22:29:32)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-77-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: NVIDIA GeForce GTX 1080 Ti
GPU 1: NVIDIA GeForce GTX 1080 Ti
GPU 2: NVIDIA GeForce GTX 1080 Ti
GPU 3: NVIDIA GeForce GTX 1080 Ti
GPU 4: NVIDIA GeForce GTX 1080 Ti
GPU 5: NVIDIA GeForce GTX 1080 Ti
GPU 6: NVIDIA GeForce GTX 1080 Ti
GPU 7: NVIDIA GeForce GTX 1080 Ti

Nvidia driver version: 465.24.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] numpydoc==1.0.0
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2020.1                      217  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.1.0            py38h23d657b_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.18.5           py38ha1c710e_0  
[conda] numpy-base                1.18.5           py38hde5b4d6_0  
[conda] numpydoc                  1.0.0                      py_0  
[conda] torch                     1.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi

```

 - CUDA/cuDNN version: 7.6

cc @albanD @mruberry @jbschlosser

**Comment by malfet** [comment] 2021-08-02 15:11
Sounds like a duplicate of #61291, which was fixed by #57417, but this is 3rd issue in last 48 hours that is reported along the same line

**Comment by jbschlosser** [comment] 2021-08-02 17:13
Looks like #57417 broke the check but it was added back in in #61394.

**Comment by malfet** [comment] 2021-08-02 17:15
Closing this one as a duplicate, but we should consider 1.9.1 release that fix torch.nn regressions

**Closed by malfet** 2021-08-02 17:15 UTC
Labels: module: nn, triage review
