### ISSUE TITLE
TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error: Not within tolerance

### ISSUE THREAD

**Issue by KongCang** [pytorch/pytorch#23999] opened 2019-08-08 03:59 UTC
## To Reproduce
```python
import torch
import numpy as np


def model(mu):
    aa = [3, 4, 77, 9]
    aa = np.asarray(aa)
    aa_ts = torch.Tensor(aa).cuda().float()
    mu = mu + aa_ts
    # need to reset some idx of the valve but it not work in trace.jit
    mu[1] = 55
    return mu


x1 = torch.tensor([99, 2, 3, 4]).cuda().float()
x2 = torch.tensor([0, 0, 0, 0]).cuda().float()

print(model(x1))
print(model(x2))

fn = torch.jit.trace(model, x1)
fn.save("test_model_freeze.pt")
model_new = torch.jit.load('test_model_freeze.pt')
y1 = model_new(x1)
y2 = model_new(x2)
print(y1)
print(y2)
```

## Expected behavior
Connected to pydev debugger (build 182.4505.26)
tensor([102.,  55.,  80.,  13.], device='cuda:0')
tensor([ 3., 55., 77.,  9.], device='cuda:0')
E:/Company/Models/test_freeze_pytorch/test_np.py:8: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  aa_ts = torch.Tensor(aa).cuda().float()
D:\SoftInstall\Aconda\envs\tf\lib\site-packages\torch\jit\__init__.py:642: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Not within tolerance rtol=1e-05 atol=1e-05 at input[1] (6.0 vs. 55.0) and 0 other locations (25.00%)
  _check_trace([example_inputs], func, executor_options, module, check_tolerance, _force_outplace)
tensor([102.,   6.,  80.,  13.], device='cuda:0')
tensor([ 3.,  4., 77.,  9.], device='cuda:0')

## Environment

 - PyTorch Version (e.g., 1.0):1.0.0
 - OS (e.g., Linux):win10
 - How you installed PyTorch (`conda`, `pip`, source):pip
 - Python version:3.5
 - CUDA/cuDNN version:9.0

**Comment by haochange** [comment] 2019-08-08 08:37
same error：
/python3.6/site-packages/torch/jit/__init__.py:702: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Not within tolerance rtol=1e-05 atol=1e-05 at input[1, 158, 62, 6] (-0.10845498740673065 vs. -0.10844378173351288) and 0 other locations (0.00%)
  _check_trace([example_inputs], func, executor_options, traced, check_tolerance, _force_outplace)

**Comment by WeiChihChern** [comment] 2019-09-01 15:28
got same error too

**Comment by deep-practice** [comment] 2019-09-24 06:17
got the same error too

**Comment by hyc-xyz** [comment] 2019-10-31 02:10
Does any know how to fix this?

**Comment by InfluenceFunctional** [comment] 2019-11-04 13:30
got the same error, only occasionally, after moving training into a separate script

**Comment by agiokas-dbg** [comment] 2019-11-27 15:42
I only just witnessed this after updating my `venv` to `pytorch 1.3` didn't exist with versions `1.2` and `1.3`

**Comment by xiang1107** [comment] 2020-01-15 14:15
got the same error too

**Comment by SasCezar** [comment] 2020-01-17 20:28
Hi,

I get the same error when using the Tensorboard add_graph(). My model is an encoder-decoder with attention. Here is the log:

`Traceback (most recent call last):
  File "/home/sasce/PycharmProjects/NeuralCodeFix/ncf/main.py", line 87, in <module>
    writer.add_graph(model, [src, src_len, trg])
  File "/home/sasce/miniconda3/envs/PyTorch37/lib/python3.7/site-packages/torch/utils/tensorboard/writer.py", line 682, in add_graph
    self._get_file_writer().add_graph(graph(model, input_to_model, verbose))
  File "/home/sasce/miniconda3/envs/PyTorch37/lib/python3.7/site-packages/torch/utils/tensorboard/_pytorch_graph.py", line 234, in graph
    trace = torch.jit.trace(model, args)
  File "/home/sasce/miniconda3/envs/PyTorch37/lib/python3.7/site-packages/torch/jit/__init__.py", line 858, in trace
    check_tolerance, _force_outplace, _module_class)
  File "/home/sasce/miniconda3/envs/PyTorch37/lib/python3.7/site-packages/torch/jit/__init__.py", line 1007, in trace_module
    check_tolerance, _force_outplace, True, _module_class)
  File "/home/sasce/miniconda3/envs/PyTorch37/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/sasce/miniconda3/envs/PyTorch37/lib/python3.7/site-packages/torch/jit/__init__.py", line 676, in _check_trace
    raise TracingCheckError(*diag_info)
torch.jit.TracingCheckError: Tracing failed sanity checks!`

**Comment by jingpengw** [comment] 2020-01-21 22:36
got the same error with pytorch 1.4.0

**Comment by barkerje** [comment] 2020-02-04 00:36
I had the same error, but then I realized I had not called `model.eval()`.  If you don't set your model to evaluate mode, it will still use things like drop out which will add randomness to your model making the results not match.

**Comment by prfans** [comment] 2020-04-21 00:23
I got the same error with pytorch 1.4 and python 3.6. I used eval mode, anyone can help me?

**Comment by wanchaol** [comment] 2020-04-21 00:40
@prfans I believe this problem should have already been solved. Do you have a simple script that reproduces your problem?

You can always tries your program with pytorch nightlies or master to see if your problem still exist.

**Comment by kikirizki** [comment] 2020-05-26 05:51
any progress on this? I got the error when I use multiple input

**Comment by kikirizki** [comment] 2020-05-26 06:44
any progress on this. I face the same problem

**Comment by wanchaol** [comment] 2020-05-26 17:49
> any progress on this. I face the same problem

@kikirizki this problem have already been resolved, I tested it on master and it works as expected. For your problem, can you share what version of pytorch you are running on, and do you have a simple script that could reproduce the problem?

**Comment by wanchaol** [comment] 2020-05-26 17:51
I am going to close this issue as it's been resolved. @kikirizki If you still have this problem on nightly builds or master, can you submit a new issue describing how to reproduce your problem with a simple script? Thanks!

**Closed by wanchaol** 2020-05-26 17:51 UTC
Labels: jit, triaged

**Comment by BruceXSK** [comment] 2020-12-18 02:45
I solved the problem by adding model.eval() and deleting the model.cuda(), aka, map the model to cpu

**Comment by christinezuzart** [comment] 2021-04-07 11:24
With model.eval() I get an error Exception has occured: TypeError 'bool' object is not callable.
So I am calling model.eval = True which does not give the Exception error.

However I am getting below warning..Any inputs on how to resolve this is appreciated.

model.eval = True
with torch.jit.optimized_execution(True):
    traced_script_module = torch.jit.trace(model, (x, y, z))


TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:    
With rtol=1e-05 and atol=1e-05, found 2 element(s) (out of 2) whose difference(s) exceeded the margin of error (including 
0 nan comparisons). The greatest difference was 0.5916104316711426 (-6.0773491859436035 vs. -5.485738754272461), which occurred at index (0, 0).
  _module_class,

**Comment by MrWXfaster** [comment] 2021-07-28 03:46
> 我有同样的错误，但后来我意识到我没有调用`model.eval()`. 如果您没有将模型设置为评估模式，它仍然会使用 dropout 之类的东西，这会为您的模型增加随机性，使结果不匹配。

good job

**Comment by KongCang** [comment] 2022-02-10 01:47
Thanks [BruceXSK](https://github.com/BruceXSK) torch1.8.0 cpu can work!
`Python 3.8.12 (default, Oct 12 2021, 13:49:34) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.0.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch
   ...: import numpy as np
   ...: 
   ...: 
   ...: def model(mu):
   ...:     aa = [3, 4, 77, 9]
   ...:     aa = np.asarray(aa)
   ...:     aa_ts = torch.Tensor(aa).float()
   ...:     mu = mu + aa_ts
   ...:     # need to reset some idx of the valve but it not work in trace.jit
   ...:     mu[1] = 55
   ...:     return mu
   ...: 
   ...: 
   ...: x1 = torch.tensor([99, 2, 3, 4]).float()
   ...: x2 = torch.tensor([0, 0, 0, 0]).float()
   ...: 
   ...: print(model(x1))
   ...: print(model(x2))
   ...: 
   ...: fn = torch.jit.trace(model, x1)
   ...: fn.save("test_model_freeze.pt")
   ...: model_new = torch.jit.load("test_model_freeze.pt")
   ...: y1 = model_new(x1)
   ...: y2 = model_new(x2)
   ...: print(y1)
   ...: print(y2)
tensor([102.,  55.,  80.,  13.])
tensor([ 3., 55., 77.,  9.])
<ipython-input-1-7a00f6b4796a>:8: TracerWarning: torch.Tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  aa_ts = torch.Tensor(aa).float()
tensor([102.,  55.,  80.,  13.])
tensor([ 3., 55., 77.,  9.])

In [2]: torch.__version__
Out[2]: '1.8.0+cpu'
`

**Comment by Sehaba95** [comment] 2022-07-14 16:48
I faced the same problem, I have solved it by adding model.eval(). Thanks @[barkerje](https://github.com/barkerje) for sharing!

**Comment by GeneralJing** [comment] 2022-10-01 13:38
TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
With rtol=1e-05 and atol=1e-05, found 199 element(s) (out of 200) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 0.03144541382789612 (0.4692056179046631 vs. 0.43776020407676697), which occurred at index 199.
same question. the model is .eval() mode, and i print the forward results the the torch.jit.trace() is executed, i got two same forward results. can anyon give some advice? and the output of the python fuction is what?
when the model is traced, there are some warnings like these:
TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  torch.tensor(240, dtype=torch.float)).int().float()
TracerWarning: torch.tensor results are registered as constants in the trace. You can safely ignore this warning if you use this function to create tensors out of constant variables that would be the same every time you call this function. In any other case, this might cause the trace to be incorrect.
  topk_clses = (topk_ind / torch.tensor(K, dtype=torch.float)).int()
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert boxes.size(1) == 5, 'Input boxes shape should be (N, 5)'

**Comment by eval-dev** [comment] 2023-01-21 05:28
@KongCang, I suspect that it is `mu[1] = 55` causing the problem. It's an in-place tensor update. Because tracer runs the same input multiple rounds, in-place update alters the input of following passes. See https://pytorch.org/docs/stable/jit.html#tracing-edge-cases

> def model(mu):
>     aa = [3, 4, 77, 9]
>     aa = np.asarray(aa)
>     aa_ts = torch.Tensor(aa).cuda().float()
>     mu = mu + aa_ts
>     # need to reset some idx of the valve but it not work in trace.jit
>     mu[1] = 55
>     return mu
>

**Comment by lucidBrot** [comment] 2023-08-25 16:18
I had to additionally add `with torch.no_grad():`.
