### ISSUE TITLE
Perf regression for YoloV3 CPU eager eval

### ISSUE THREAD

**Issue by wconstab** [pytorch/pytorch#51380] opened 2021-01-29 22:41 UTC
approx 12% regression observed on nightly builds between 10/15/20 and 11/3/20 

Bisection result shows this commit is the reason of regression: 2397c8d

The mean time of test_eval[yolov3-cpu-eager] for this commit: 0.7140323325467761 seconds
The mean time of test_eval[yolov3-cpu-eager] for its parent, a602811: 0.6385891167126829 seconds.
There is about 11% slowdown.

cc @VitalyFedyunin @ngimel

**Comment by xuzhao9** [comment] 2021-02-24 22:19
Bisection result shows this commit is the reason of regression:
https://github.com/pytorch/pytorch/commit/2397c8d1f78cb5b48bcec9c180c1eef81c13b887

The mean time of test_eval[yolov3-cpu-eager] for this commit: 0.7140323325467761 seconds
The mean time of test_eval[yolov3-cpu-eager] for its parent, a602811da7: 0.6385891167126829 seconds.
There is about 11% slowdown.

**Comment by xuzhao9** [comment] 2021-02-25 19:00
Here is the full test result (filtered cuda ones since this commit doesn't affect much cuda result)

Benchmark                                                  Mean a602811    Mean 2397c8d  Delta
-------------------------------------------------------  --------------  --------------  --------
test_train[BERT_pytorch-cpu-jit]                            0.210158        0.206137     -1.914%
test_eval[BERT_pytorch-cpu-jit]                             0.0486281       0.0494229    +1.634%
test_train[BERT_pytorch-cpu-eager]                          0.217877        0.210052     -3.591%
test_eval[BERT_pytorch-cpu-eager]                           0.0572141       0.0577627    +0.959%
test_train[LearningToPaint-cpu-jit]                         0.039961        0.0401058    +0.362%
test_eval[LearningToPaint-cpu-jit]                          0.00711941      0.0071799    +0.850%
test_train[LearningToPaint-cpu-eager]                       0.0364838       0.0366123    +0.352%
test_eval[LearningToPaint-cpu-eager]                        0.00740297      0.00752973   +1.712%
test_train[attention_is_all_you_need_pytorch-cpu-jit]       1.04647         1.08134      +3.333%
test_eval[attention_is_all_you_need_pytorch-cpu-jit]        0.240338        0.258776     +7.672%
test_train[attention_is_all_you_need_pytorch-cpu-eager]     1.00692         1.02076      +1.374%
test_eval[attention_is_all_you_need_pytorch-cpu-eager]      0.264771        0.263759     -0.382%
test_train[demucs-cpu-jit]                                  0.367036        0.415652     +13.246%
test_eval[demucs-cpu-jit]                                   0.102801        0.112725     +9.654%
test_train[demucs-cpu-eager]                                0.398403        0.416321     +4.497%
test_eval[demucs-cpu-eager]                                 0.108384        0.11318      +4.424%
test_train[dlrm-cpu-eager]                                  0.00252268      0.00259629   +2.918%
test_eval[dlrm-cpu-eager]                                   0.000742887     0.000746654  +0.507%
test_train[fastNLP-cpu-jit]                                 0.00271941      0.00273904   +0.722%
test_eval[fastNLP-cpu-jit]                                  0.000288948     0.000297578  +2.987%
test_train[fastNLP-cpu-eager]                               0.00273349      0.00273015   -0.122%
test_eval[fastNLP-cpu-eager]                                0.000301358     0.000310928  +3.176%
test_train[pytorch_mobilenet_v3-cpu-jit]                    0.245543        0.241261     -1.744%
test_eval[pytorch_mobilenet_v3-cpu-jit]                     0.0225707       0.0215023    -4.733%
test_train[pytorch_mobilenet_v3-cpu-eager]                  0.255275        0.250736     -1.778%
test_eval[pytorch_mobilenet_v3-cpu-eager]                   0.0268016       0.0257635    -3.874%
test_train[pytorch_struct-cpu-jit]                          1.53412         1.50568      -1.854%
test_eval[pytorch_struct-cpu-jit]                           0.00227389      0.00227374   -0.007%
test_train[pytorch_struct-cpu-eager]                        1.51266         1.53117      +1.223%
test_eval[pytorch_struct-cpu-eager]                         0.00261645      0.00261734   +0.034%
test_eval[yolov3-cpu-eager]                                 0.654957        0.706422     +7.858%

**Comment by bertmaher** [comment] 2021-02-25 21:20
I'm almost certain what's going on here is that the heuristics change in the linked diff were tuned for single-thread performance, but are suboptimal when running on multiple cores.  I think it'll be a relatively easy fix so I'll pull it into my queue.

**Comment by ngimel** [comment] 2021-02-25 21:31
Also, with new mkldnn version intel claims they are much better at 1x1 convolutions #48885

**Comment by xuzhao9** [comment] 2021-03-01 17:44
The yolov3 cpu train result regression has been fixed after #52909 is merged.

**Closed** 2021-03-05 19:44 UTC
Labels: module: cpu, module: performance, triaged
