### ISSUE TITLE
Dataloader hanging when num_workers >0 

### ISSUE THREAD

**Issue by JamesMcCullochDickens** [pytorch/pytorch#89352] opened 2022-11-19 21:02 UTC
### 🐛 Describe the bug

The following code is hanging when num_workers > 0.

```
from torch.utils.data import Dataset
import torch

class dts(Dataset):
    def __init__(self, dataset_size=10):
        super().__init__()
        self.dataset_size = dataset_size
        self.data = torch.rand(dataset_size, 3, 600, 600)

    def __len__(self):
        return self.dataset_size

    def __getitem__(self, idx):
        return self.data[idx]


if __name__ == "__main__":
    dl = torch.utils.data.DataLoader(dataset=dts(), num_workers=0, batch_size=8)
    for data in dl:
        debug = "debug"
```

### Versions

PyTorch version: 1.14.0.dev20221119
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A
OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17
Python version: 3.7.15 (default, Nov  7 2022, 22:00:21)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-53-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA RTX A4000
GPU 1: NVIDIA RTX A4000
GPU 2: NVIDIA RTX A4000
Nvidia driver version: 520.56.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] pytorchvideo==0.1.5
[pip3] torch==1.14.0.dev20221119
[pip3] torchaudio==0.14.0.dev20221119
[pip3] torchvision==0.15.0.dev20221119
[conda] blas                      1.0                         mkl
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py37h7f8727e_0
[conda] mkl_fft                   1.3.1            py37hd3c417c_0
[conda] mkl_random                1.2.2            py37h51133e4_0
[conda] numpy                     1.21.5           py37h6c91a56_3
[conda] numpy-base                1.21.5           py37ha15fc14_3
[conda] pytorch                   1.14.0.dev20221119 py3.7_cuda11.7_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.7                 h67b0de4_0    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] pytorchvideo              0.1.5                    pypi_0    pypi
[conda] torchaudio                0.14.0.dev20221119      py37_cu117    pytorch-nightly
[conda] torchvision               0.15.0.dev20221119      py37_cu117    pytorch-nightly

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ptrblck** [comment] 2022-11-20 03:39
Cross-post from the [discussion board](https://discuss.pytorch.org/t/opening-pkl-in-a-dataset-used-with-a-dataloader-with-multiple-workers-causes-issues/166367/5).
The issue is not reproducible for me using the current CUDA 11.7 nightlies.
I've added :
```python
if __name__ == "__main__":
    print(torch.__version__)
    dl = torch.utils.data.DataLoader(dataset=dts(), num_workers=16, batch_size=2)
    for data in dl:
        debug = "debug"
        print(data.shape)
```
into the loop to see some kind of output:
```python
1.14.0.dev20221119+cu117
torch.Size([2, 3, 600, 600])
torch.Size([2, 3, 600, 600])
torch.Size([2, 3, 600, 600])
torch.Size([2, 3, 600, 600])
torch.Size([2, 3, 600, 600])
```

**Comment by ejguan** [comment] 2022-11-21 17:48
I couldn't reproduce this issue as well with the nightly release on Nov 20.

Wondering do you run your script in distributed training?

**Comment by JamesMcCullochDickens** [comment] 2022-11-21 18:58
@ejguan No I was not using a distributed setup. I'm wondering if it could be related to my CPU Intel 13900-K or maybe my Python version, and it's more of an overall multiprocessing issue? Any insights much appreciated.

**Comment by JamesMcCullochDickens** [comment] 2022-11-21 20:18
Apologies. It appears to be some kind of debug-mode issue with Pycharm. I tried simply running it, and it worked. You can close this and I will look up the issue on the PyCharm forums.

**Comment by ejguan** [comment] 2022-11-21 20:19
No worried. Glad you find the problem. Closing now

**Closed by ejguan** 2022-11-21 20:19 UTC
Labels: needs reproduction, module: dataloader, triaged
