### ISSUE TITLE
Tensor will become all zero on MPS after switching to other softwares

### ISSUE THREAD

**Issue by Zhangyanbo** [pytorch/pytorch#77829] opened 2022-05-19 06:07 UTC
### 🐛 Describe the bug

Running PyTorch on Jupyter notebook (with VSCode), simply do:

```python
x = torch.randn(5, 4).to('mps')
```

Then, switching to other software, such as WeChat. Going back to VSCode, I found x become:

```python
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='mps:0')
```

### Versions

PyTorch version: 1.12.0.dev20220518
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.3.1 (arm64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.12 | packaged by conda-forge | (default, Jan 30 2022, 23:13:24)  [Clang 11.1.0 ] (64-bit runtime)
Python platform: macOS-12.3.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] torch==1.12.0.dev20220518
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.0.4
[pip3] torch-scatter==2.0.9
[pip3] torch-sparse==0.6.13
[pip3] torch-spline-conv==1.2.1
[pip3] torchvision==0.2.2
[conda] numpy                     1.22.2           py38h9d822b3_0    conda-forge
[conda] pytorch                   1.12.0.dev20220518         py3.8_0    pytorch-nightly
[conda] torch-cluster             1.6.0                    pypi_0    pypi
[conda] torch-geometric           2.0.4                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torch-sparse              0.6.13                   pypi_0    pypi
[conda] torch-spline-conv         1.2.1                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch

cc @ezyang @gchanan @zou3519

**Comment by Zhangyanbo** [comment] 2022-05-19 06:11
Additional comment: I can reproduce this bug even without VSCode. Just on command and run python, the same bug still shows.

**Comment by frankroeder** [comment] 2022-05-19 12:30
I am also able to reproduce this bug by creating a tensor in ipython and moving it to the mps device
`>>>x = torch.randn(5, 4).to('mps')`
and printing it
`>>>x`
`tensor([[ 7.3350e-01,  4.8593e-01,  1.6498e+00,  9.3859e-01],
        [-1.6065e+00,  5.6393e-01,  6.5327e-01,  3.2433e-01],
        [ 2.3301e-01,  5.6508e-01,  6.7679e-01, -1.9650e-01],
        [ 4.4768e-01,  5.1787e-02, -7.6005e-01, -1.1392e+00],
        [-1.7853e+00,  1.2278e+00,  3.6426e-01, -6.9626e-01]], device='mps:0')`.
Meanwhile, I used other applications and came back to print it again
`>>>x`
`tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='mps:0')
`

**Comment by byronyi** [comment] 2022-05-21 02:56
I did a quick test and was indeed able to reproduce this issue using plain Python (not IPython) and nightly torch on macOS 12.3.1:

```
$ python3 --version -V
Python 3.8.9 (default, Apr 13 2022, 08:48:06)
[Clang 13.1.6 (clang-1316.0.21.2.5)]
$ python3 -c 'import torch; print(torch.version.git_version)'
2b57412cefbbfbc1cb09a82b4bd57394750a25c4
```

I switch to web browser (Safari) for 5-10 minutes before the content of MPS tensor turns to 0.0. Copying the tensor back to cpu using `tensor.cpu()` doesn't help, so it is unlikely to be caused by tensor printing.

**Comment by Zhangyanbo** [comment] 2022-05-21 04:20
> Could you please provide some more details?
> 
> E.g. how long did you use the other applications for before returning to ipython? Did you observe this for any specific applications, or did it happen after navigating away to any different window? Did you open the different application while running ipython, or was it already running, and you just navigated to its window?

@abhudev 
1. It doesn't matter what application is used. I tried WeChat, Safari, Slack, I can reproduce this bug with each of them. 
2. Often it takes about 5 seconds to reproduce this bug, if you just switch for 1~2 seconds, it won't turn zero. 
3. I switched to other application after the ipython session is done (but the ipython still open).

**Closed** 2022-05-25 21:27 UTC
Labels: high priority, triaged, module: mps

**Comment by albanD** [comment] 2022-05-26 13:33
Note that the PR got reverted due to unrelated issues.
We will reland it soon.
