### ISSUE TITLE
Adagrad not working with GPU

### ISSUE THREAD

**Issue by NiccoloSacchi** [pytorch/pytorch#7321] opened 2018-05-05 19:44 UTC
## Issue description

The code below is a simple example which raises 

> RuntimeError: Expected object of type torch.FloatTensor but found type torch.cuda.FloatTensor for argument #4 'tensor1'

when calling .step(). 
It looks like Adagrad works correctly when using the cpu while Adam optimizer works correctly with both cpu and gpu. 
Moreover, Adagrad works correctly if initialized after moving the parameters of the model (in this case a Linear) to the gpu.

## Code example

import torch
from torch import nn
from torch import optim

device = torch.device("cuda:0")
#device = torch.device("cpu") # works correctly on cpu

x = torch.Tensor(10, 2).to(device)
linear = nn.Linear(2, 4)#.to(device) # works correctly when moving the parameters to gpu before initializing Adagrad

o = optim.Adagrad(linear.parameters())
#o = optim.Adam(linear.parameters()) # works correctly with Adam

linear.to(device)

linear(x).mean().backward()
o.step()

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 8.0.44
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)
GPU 2: TITAN X (Pascal)
GPU 3: TITAN X (Pascal)

Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/local/MATLAB/R2016a/bin/glnxa64/libcudnn.so.7.0.64

Versions of relevant libraries:
[pip] numpy (1.11.3)
[pip] numpydoc (0.6.0)
[pip] torch (0.4.0)
[pip] torchvision (0.1.9)
[conda] pytorch                   0.4.0           py36_cuda8.0.61_cudnn7.1.2_1    pytorch
[conda] torchvision               0.1.9            py36h7584368_1    soumith

**Comment by SsnL** [comment] 2018-05-06 00:57
Not a bug. Your optimizer is asked to track the CPU parameters because you feed the parameters to it while they were in CPU. The moving to GPU operation creates new Tensor objects rather than modifying inplace, so the optimizer doesn't know that the parameters are on GPUs.

See notes on "Construct it" at https://pytorch.org/docs/master/optim.html.

**Closed by SsnL** 2018-05-06 00:57 UTC

**Comment by NiccoloSacchi** [comment] 2018-05-06 09:15
Thanks for pointing that out. I thought about that, it makes sense. But I noticed that other optimizers (e.g. Adam) somehow keep track of the parameters even if they are moved to the gpu after initializing the optimizer. So I thought all optimizers would work correctly in that case. I'll stick with what suggested in the documentation for now.

**Comment by adosar** [comment] 2025-03-08 20:38
@ssnl It seems that the relevant note in [old docs / version 0.4.0](https://pytorch.org/docs/0.4.0/optim.html#constructing-it) has been removed from the [new docs / version 2.6.0](https://pytorch.org/docs/2.6/optim.html). Is it ok now to `model.cuda()` after passing the parameters to the optimizer?
