### ISSUE TITLE
GPU Memory not being freed using PT 2.0, issue absent in earlier PT versions

### ISSUE THREAD

**Issue by SrihasY** [pytorch/pytorch#99835] opened 2023-04-23 19:37 UTC
### 🐛 Describe the bug

PyTorch 2.0 does not free GPU memory when running a training loop despite deleting related tensors and clearing the cuda cache. The same script frees memory with a PyTorch version before 2.0 (tested using 1.13.1). The issue prevents multiple models/batch sizes to be sequentially tested in the same file, since memory is held by the allocator.

Link to the script - https://gist.github.com/SrihasY/882f3fbab521980d1b0a9aa9479d4f86

**Expected output (without torch.compile, PT 1.13.1) -** 

> Starting run with dimensions = 128 and batch size = 128
Total memory: 11396382720, Allocated memory: 0
<pre>
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |       0 B  |    1042 MB |   25529 MB |   25529 MB |
|       from large pool |       0 B  |    1035 MB |   25474 MB |   25474 MB |
|       from small pool |       0 B  |       8 MB |      54 MB |      54 MB |
|---------------------------------------------------------------------------|
| Active memory         |       0 B  |    1042 MB |   25529 MB |   25529 MB |
|       from large pool |       0 B  |    1035 MB |   25474 MB |   25474 MB |
|       from small pool |       0 B  |       8 MB |      54 MB |      54 MB |
|---------------------------------------------------------------------------|
| GPU reserved memory   |       0 B  |    1390 MB |    1390 MB |    1390 MB |
|       from large pool |       0 B  |    1380 MB |    1380 MB |    1380 MB |
|       from small pool |       0 B  |      10 MB |      10 MB |      10 MB |
|---------------------------------------------------------------------------|
| Non-releasable memory |       0 B  |  162310 KB |    7879 MB |    7879 MB |
|       from large pool |       0 B  |  159744 KB |    7806 MB |    7806 MB |
|       from small pool |       0 B  |    7248 KB |      72 MB |      72 MB |
|---------------------------------------------------------------------------|
| Allocations           |       0    |     271    |    1492    |    1492    |
|       from large pool |       0    |      61    |     794    |     794    |
|       from small pool |       0    |     213    |     698    |     698    |
|---------------------------------------------------------------------------|
| Active allocs         |       0    |     271    |    1492    |    1492    |
|       from large pool |       0    |      61    |     794    |     794    |
|       from small pool |       0    |     213    |     698    |     698    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       0    |      31    |      31    |      31    |
|       from large pool |       0    |      26    |      26    |      26    |
|       from small pool |       0    |       5    |       5    |       5    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       0    |      35    |     527    |     527    |
|       from large pool |       0    |       9    |     300    |     300    |
|       from small pool |       0    |      29    |     227    |     227    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
</pre>
**Error using PT 2.0 (without torch.compile) -**
> Starting run with dimensions = 128 and batch size = 128
Total memory: 11396382720, Allocated memory: 17039360
<pre>
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      |  16640 KiB |   1042 MiB |  27506 MiB |  27490 MiB |
|       from large pool |  16640 KiB |   1036 MiB |  27464 MiB |  27448 MiB |
|       from small pool |      0 KiB |      8 MiB |     42 MiB |     42 MiB |
|---------------------------------------------------------------------------|
| Active memory         |  16640 KiB |   1042 MiB |  27506 MiB |  27490 MiB |
|       from large pool |  16640 KiB |   1036 MiB |  27464 MiB |  27448 MiB |
|       from small pool |      0 KiB |      8 MiB |     42 MiB |     42 MiB |
|---------------------------------------------------------------------------|
| Requested memory      |  16640 KiB |   1039 MiB |  27464 MiB |  27448 MiB |
|       from large pool |  16640 KiB |   1032 MiB |  27422 MiB |  27406 MiB |
|       from small pool |      0 KiB |      8 MiB |     42 MiB |     42 MiB |
|---------------------------------------------------------------------------|
| GPU reserved memory   | 102400 KiB |   1216 MiB |   1216 MiB |   1116 MiB |
|       from large pool | 102400 KiB |   1206 MiB |   1206 MiB |   1106 MiB |
|       from small pool |      0 KiB |     10 MiB |     10 MiB |     10 MiB |
|---------------------------------------------------------------------------|
| Non-releasable memory |  85760 KiB | 533968 KiB |  15608 MiB |  15524 MiB |
|       from large pool |  85760 KiB | 532480 KiB |  15551 MiB |  15467 MiB |
|       from small pool |      0 KiB |   7538 KiB |     57 MiB |     57 MiB |
|---------------------------------------------------------------------------|
| Allocations           |       2    |     272    |    1454    |    1452    |
|       from large pool |       2    |      60    |     766    |     764    |
|       from small pool |       0    |     212    |     688    |     688    |
|---------------------------------------------------------------------------|
| Active allocs         |       2    |     272    |    1454    |    1452    |
|       from large pool |       2    |      60    |     766    |     764    |
|       from small pool |       0    |     212    |     688    |     688    |
|---------------------------------------------------------------------------|
| GPU reserved segments |       2    |      21    |      21    |      19    |
|       from large pool |       2    |      16    |      16    |      14    |
|       from small pool |       0    |       5    |       5    |       5    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |       3    |      39    |     531    |     528    |
|       from large pool |       3    |      12    |     317    |     314    |
|       from small pool |       0    |      30    |     214    |     214    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
</pre>
> Traceback (most recent call last):
  File "/coc/scratch/sconce/projects/srihas/bugreport/memory_leak_repro.py", line 88, in <module>
    train_success = run_model("resnet18", "CrossEntropyLoss", "SGD", 128, 128)
  File "/coc/scratch/sconce/projects/srihas/bugreport/memory_leak_repro.py", line 82, in run_model
    train_success = model.run_train_steps(heights_and_width, batch_size)
  File "/coc/scratch/sconce/projects/srihas/bugreport/memory_leak_repro.py", line 70, in run_train_steps
    assert allocated_mem == 0, f"Memory leak: {allocated_mem} bytes allocated"
AssertionError: Memory leak: 17039360 bytes allocated

**Error with PT 2.0, using torch.compile -** 
> Starting run with dimensions = 128 and batch size = 128
Total memory: 11396382720, Allocated memory: 113070080
<pre>
|===========================================================================|
|                  PyTorch CUDA memory summary, device ID 0                 |
|---------------------------------------------------------------------------|
|            CUDA OOMs: 0            |        cudaMalloc retries: 0         |
|===========================================================================|
|        Metric         | Cur Usage  | Peak Usage | Tot Alloc  | Tot Freed  |
|---------------------------------------------------------------------------|
| Allocated memory      | 110420 KiB |   1044 MiB |  23809 MiB |  23701 MiB |
|       from large pool | 103680 KiB |   1038 MiB |  23761 MiB |  23660 MiB |
|       from small pool |   6740 KiB |      9 MiB |     47 MiB |     41 MiB |
|---------------------------------------------------------------------------|
| Active memory         | 110420 KiB |   1044 MiB |  23809 MiB |  23701 MiB |
|       from large pool | 103680 KiB |   1038 MiB |  23761 MiB |  23660 MiB |
|       from small pool |   6740 KiB |      9 MiB |     47 MiB |     41 MiB |
|---------------------------------------------------------------------------|
| Requested memory      | 108001 KiB |   1039 MiB |  23770 MiB |  23664 MiB |
|       from large pool | 101280 KiB |   1032 MiB |  23722 MiB |  23623 MiB |
|       from small pool |   6721 KiB |      9 MiB |     47 MiB |     41 MiB |
|---------------------------------------------------------------------------|
| GPU reserved memory   | 526336 KiB |   1292 MiB |   1292 MiB |    778 MiB |
|       from large pool | 518144 KiB |   1282 MiB |   1282 MiB |    776 MiB |
|       from small pool |   8192 KiB |     10 MiB |     10 MiB |      2 MiB |
|---------------------------------------------------------------------------|
| Non-releasable memory | 415916 KiB | 465980 KiB |  14790 MiB |  14384 MiB |
|       from large pool | 414464 KiB | 464896 KiB |  14740 MiB |  14335 MiB |
|       from small pool |   1452 KiB |   5216 KiB |     49 MiB |     48 MiB |
|---------------------------------------------------------------------------|
| Allocations           |     186    |     329    |    1939    |    1753    |
|       from large pool |      20    |      60    |     576    |     556    |
|       from small pool |     166    |     270    |    1363    |    1197    |
|---------------------------------------------------------------------------|
| Active allocs         |     186    |     329    |    1939    |    1753    |
|       from large pool |      20    |      60    |     576    |     556    |
|       from small pool |     166    |     270    |    1363    |    1197    |
|---------------------------------------------------------------------------|
| GPU reserved segments |      12    |      22    |      22    |      10    |
|       from large pool |       8    |      17    |      17    |       9    |
|       from small pool |       4    |       5    |       5    |       1    |
|---------------------------------------------------------------------------|
| Non-releasable allocs |      31    |      46    |     885    |     854    |
|       from large pool |       9    |      11    |     329    |     320    |
|       from small pool |      22    |      41    |     556    |     534    |
|---------------------------------------------------------------------------|
| Oversize allocations  |       0    |       0    |       0    |       0    |
|---------------------------------------------------------------------------|
| Oversize GPU segments |       0    |       0    |       0    |       0    |
|===========================================================================|
</pre>
> Traceback (most recent call last):
  File "/coc/scratch/sconce/projects/srihas/bugreport/memory_leak_repro.py", line 88, in <module>
    train_success = run_model("resnet18", "CrossEntropyLoss", "SGD", 128, 128)
  File "/coc/scratch/sconce/projects/srihas/bugreport/memory_leak_repro.py", line 82, in run_model
    train_success = model.run_train_steps(heights_and_width, batch_size)
  File "/coc/scratch/sconce/projects/srihas/bugreport/memory_leak_repro.py", line 70, in run_train_steps
    assert allocated_mem == 0, f"Memory leak: {allocated_mem} bytes allocated"
AssertionError: Memory leak: 113070080 bytes allocated

### Versions

> Script was run using a single RTX 2080 Ti by setting CUDA_VISIBLE_DEVICES.

### Environment with PT 2.0 - 
PyTorch version: 2.0.0+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.25.0
Libc version: glibc-2.27

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-202-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 9.1.85
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              24
On-line CPU(s) list: 0-23
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
Stepping:            7
CPU MHz:             1200.013
CPU max MHz:         3700.0000
CPU min MHz:         1200.0000
BogoMIPS:            5400.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] flake8==3.7.8
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0+cu118
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.0.1+cu118
[pip3] torchvision==0.15.1+cu118
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.2.1         h84fe81f_16997    conda-forge
[conda] numpy                     1.24.2          py310h8deb116_0    conda-forge
[conda] pytorch                   2.0.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0               py310_cu118    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0              py310_cu118    pytorch

### Environment with PT 1.13
PyTorch version: 1.13.1+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:20:04) [GCC 11.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-202-generic-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 9.1.85
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 2080 Ti
GPU 1: NVIDIA GeForce RTX 2080 Ti
GPU 2: NVIDIA GeForce RTX 2080 Ti
GPU 3: NVIDIA GeForce RTX 2080 Ti
GPU 4: NVIDIA GeForce RTX 2080 Ti
GPU 5: NVIDIA GeForce RTX 2080 Ti

Nvidia driver version: 525.60.13
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True
CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              24
On-line CPU(s) list: 0-23
Thread(s) per core:  1
Core(s) per socket:  12
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz
Stepping:            7
CPU MHz:             1200.099
CPU max MHz:         3700.0000
CPU min MHz:         1200.0000
BogoMIPS:            5400.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            19712K
NUMA node0 CPU(s):   0-11
NUMA node1 CPU(s):   12-23
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities
Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==1.13.1+cu117
[pip3] torchaudio==0.13.1+cu117
[pip3] torchvision==0.14.1+cu117
[conda] blas                      1.0                         mkl    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0            16_linux64_mkl    conda-forge
[conda] libcblas                  3.9.0            16_linux64_mkl    conda-forge
[conda] liblapack                 3.9.0            16_linux64_mkl    conda-forge
[conda] mkl                       2022.2.1         h84fe81f_16997    conda-forge
[conda] numpy                     1.24.2          py310h8deb116_0    conda-forge
[conda] pytorch                   2.0.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                2.0.0               py310_cu118    pytorch
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0              py310_cu118    pytorch

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment] 2023-04-24 18:04
cc @ngimel @eellison

**Comment by ngimel** [comment] 2023-04-24 18:15
cc @eqy - the memory usage w/o torch.compile is likely due to cublas workspaces?

**Comment by eqy** [comment] 2023-04-24 21:53
Right, I verified that adding `torch._C._cuda_clearCublasWorkspaces()` prior to the `torch.cuda.empty_cache()` in w/o `torch.compile` suppresses the "leak"

**Comment by eellison** [comment] 2023-04-25 15:16
Adding :

```
torch._C._cuda_clearCublasWorkspaces()
torch._dynamo.reset()
import gc
gc.collect()
torch.cuda.empty_cache()
```

after `del self.model, self.criterion, self.optimizer` releases the memory.

**Comment by ngimel** [comment] 2023-04-25 16:24
Should we add that as a utility function? It's becoming a pretty complicated recipe. ooc, do you know what's creating ref cycles such that gc is needed?

**Comment by anijain2305** [comment] 2023-09-18 21:14
Closing as duplicate of https://github.com/pytorch/pytorch/issues/105181

**Closed by anijain2305** 2023-09-18 21:14 UTC
Labels: module: memory usage, triaged, oncall: pt2, module: dynamo
