### ISSUE TITLE
Triangular solve fails on batches of matrices of size > (*, 524281)

### ISSUE THREAD

**Issue by 464hee** [pytorch/pytorch#97211] opened 2023-03-21 02:41 UTC
### 🐛 Describe the bug

linux
python3.9
pytorch==1.10.1-cu111
pytorch==1.13.1-cu117

### Versions

import torch

HE = torch.tensor([[0.5626, 0.2159], [0.7201, 0.8012],  [0.4062, 0.5581]]).cuda()
Y  = torch.randn(3,1024*1024).cuda()
ttt1=torch.linalg.lstsq(HE, Y)[0]

##################################################################
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasStrsmBatched( handle, side, uplo, trans, diag, m, n, alpha, A, lda, B, ldb, batchCount)`

If you change 1024 * 1024 to 700 * 700, no error will be reported

cc @ngimel @csarofeen @ptrblck @xwang233 @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @Lezcano

**Comment by lezcano** [comment] 2023-03-21 11:45
A simpler repro showing this issue:
```python
import torch

n = 3
X = torch.randn(n, n, device="cuda")
Y = torch.randn(n,1024*1024, device="cuda")
torch.linalg.solve_triangular(X, Y, upper=True)
```

It starts failing on `Y` of shape  `(3, 725, 725)`. Same happens for other `n` with the same cutoff at `725`. We can patch around this in core, but this really smells like a bug in cusolver @xwang233 @IvanYashchuk

**Comment by xwang233** [comment] 2023-03-21 22:51
Thank you for reporting this issue. I've forwarded the failures to cublas team. 

ref: /4038839

**Comment by bednarlukas** [comment] 2023-07-31 16:04
Has there been any progress on this since March?

**Comment by lezcano** [comment] 2023-07-31 16:06
Nope, I haven't found the time. We'd accept a fix for this one (not using cusolver when the size is too large)

**Comment by lezcano** [comment] 2023-08-31 21:31
Actually, this is a duplicate of https://github.com/pytorch/pytorch/issues/79191

**Closed by lezcano** 2023-08-31 21:31 UTC
Labels: module: cuda, good first issue, triaged, module: cublas, module: linear algebra
