### ISSUE TITLE
RuntimeError: Can't have size-dependent arguments to functions that take variable number of tensor arguments

### ISSUE THREAD

**Issue by wangyunxiaa** [pytorch/pytorch#13156] opened 2018-10-26 01:55 UTC
pytorch to onnx:
when do convert `torch.onnx.export(torch_model, (dummy_input1, dummy_input2), "lmmodel.onnx", verbose=True, input_names=input_names, output_names=output_names)`
cause an error:
```
File "/home/yunxiawang/codes/torch2onnx/nce.py", line 96, in forward
    self.noise[target.data.view(-1)].view_as(target)
RuntimeError: Can't have size-dependent arguments to functions that take variable number of tensor arguments
```
python 3.6,
pytorch 0.4.1,
onnx 1.3.0,
all installed by pip.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by garymm** [comment] 2021-08-25 00:56
@wangyunxiaa can you reproduce with latest nightly pytorch?
If so, please provide source code.

**Comment by garymm** [comment] 2021-10-16 00:42
Closing due to lack of reply from creator. Please open a new issue with clear repro instructions if this is still an issue on latest nightly PyTorch.

**Closed by garymm** 2021-10-16 00:42 UTC
Labels: module: onnx, triaged, onnx-needs-info
