### ISSUE TITLE
JIT profiling executor does not fuse Relu and Dropout for a GPU

### ISSUE THREAD

**Issue by kevinstephano** [pytorch/pytorch#30801] opened 2019-12-05 06:31 UTC
## To Reproduce

Script to reproduce behavior:
```
import torch
import torch.nn as nn
import torch.nn.functional as F
import argparse

parser = argparse.ArgumentParser(description='Relu-Dropout JIT Test')
parser.add_argument('--bad-jit', action='store_true', help='Use new executor that cause Relu not to fuse with dropout.')
args = parser.parse_args()

assert hasattr(torch._C, '_jit_set_profiling_executor'), "Old JIT behavior doesn't exist!"
if not args.bad_jit :
    torch._C._jit_set_profiling_executor(False)
    torch._C._jit_set_profiling_mode(False)

@torch.jit.script
def jit_relu_dropout(x, prob) :
    # type: (Tensor, float) -> Tensor
    out = F.threshold(x, 0., 0.)
    out = F.dropout(out, p=prob, training=True)
    return out 
                                                                                    
inputs = torch.randn(5120, 1024, dtype=torch.float16, device=torch.device("cuda")).requires_grad_(True)
outputs = jit_relu_dropout(inputs, 0.1)
```

## Expected behavior
I find it quick to tell if the kernel is jitted by looking at a nvprof trace on the GPU. `kernel_0` is the expected fused kernel in the properly fused case.

Good JIT behavior (without profiling executor):
```
nvprof --print-gpu-trace python relu_dropout_fusion.py
```
Output:
```
   Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*           Device   Context    Stream  Name
2.53452s  37.568us            (640 1 1)       (256 1 1)        48        0B        0B  Graphics Device         1         7  _ZN84_GLOBAL__N__60_tmpxft_000083da_00000000_10_Distributions_compute_75_cpp1_ii_c3aa7ee643distribution_elementwise_grid_stride_kernelIfLi4EZZZN2at6native18normal_kernel_cudaERNS1_14TensorIteratorEddPNS1_9GeneratorEENKUlvE_clEvENKUlvE1_clEvEUlP24curandStatePhilox4_32_10E0_ZNS_27distribution_nullary_kernelIN3c104HalfEfLi4ESB_ZZZNS2_18normal_kernel_cudaES4_ddS6_ENKS7_clEvENKS8_clEvEUlfE_EEvS4_PNS1_13CUDAGeneratorERKT2_T3_EUlifE_EEviSt4pairImmET1_SI_ [139]
2.69363s  58.305us           (1280 1 1)       (128 1 1)        32        0B        0B  Graphics Device         1         7  kernel_0 [171]
```
Bad JIT Behavior:
```
nvprof --print-gpu-trace python relu_dropout_fusion.py --bad-jit
```
Output:
```
   Start  Duration            Grid Size      Block Size     Regs*    SSMem*    DSMem*           Device   Context    Stream  Name
2.51873s  33.952us            (640 1 1)       (256 1 1)        48        0B        0B  Graphics Device         1         7  _ZN84_GLOBAL__N__60_tmpxft_000083da_00000000_10_Distributions_compute_75_cpp1_ii_c3aa7ee643distribution_elementwise_grid_stride_kernelIfLi4EZZZN2at6native18normal_kernel_cudaERNS1_14TensorIteratorEddPNS1_9GeneratorEENKUlvE_clEvENKUlvE1_clEvEUlP24curandStatePhilox4_32_10E0_ZNS_27distribution_nullary_kernelIN3c104HalfEfLi4ESB_ZZZNS2_18normal_kernel_cudaES4_ddS6_ENKS7_clEvENKS8_clEvEUlfE_EEvS4_PNS1_13CUDAGeneratorERKT2_T3_EUlifE_EEviSt4pairImmET1_SI_ [139]
2.51961s  37.569us          (10240 1 1)       (512 1 1)        16        0B        0B  Graphics Device         1         7  _ZN2at6native18elementwise_kernelILi512ELi1EZNS0_15gpu_kernel_implIZNS0_21threshold_kernel_implIN3c104HalfEEEvRNS_14TensorIteratorET_S8_EUlS5_S5_E_EEvS7_RKS8_EUliE0_EEviT1_ [150]
2.51993s  43.328us            (640 1 1)       (256 1 1)        32        0B        0B  Graphics Device         1         7  void at::native::_GLOBAL__N__54_tmpxft_0000859f_00000000_10_Dropout_compute_75_cpp1_ii_275f3a05::fused_dropout_kernel<c10::Half, float, unsigned int, int=1>(at::cuda::detail::TensorInfo<c10::Half, unsigned int>, unsigned int, at::cuda::detail<unsigned char, c10::Half>, c10::Half, float, std::pair<unsigned long, unsigned long>) [169]
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.4.0a0+a5b4d78
 - OS (e.g., Linux): Linux 18.04 LTS
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:  3.6.9
 - CUDA/cuDNN version: Cuda 10.1
 - GPU models and configuration:  TitanV/V100
 - Any other relevant information:

cc @suo

**Comment by ngimel** [comment] 2019-12-05 06:37
cc @Krovatkin

**Comment by Krovatkin** [comment] 2019-12-05 19:00
I love the option's name `--bad-jit` @kevinstephano 😄 

I think I know what the problem is here, I'll test the fix in the next few days.

**Comment by Krovatkin** [comment] 2019-12-18 00:23
@kevinstephano I'm working on a fix. Unfortunately, fixing this exposed another fairly tricky problem, I was trying to tackle in the last few days.

**Comment by Krovatkin** [comment] 2019-12-18 00:36
One of the enhancements needed to make sure relu + dropout are fused.
https://github.com/pytorch/pytorch/pull/31392

**Comment by eellison** [comment] 2020-01-22 20:19
Was this fixed @Krovatkin ?

**Comment by Krovatkin** [comment] 2020-01-23 19:58
@eellison we landed a few related things that hopefully fixes this, but I need to double check. Will do it in the next few days

**Comment by Krovatkin** [comment] 2020-01-23 22:05
the optimized graph from the legacy executor:

```
[DUMP graph_executor.cpp:610] Optimized Graph
[DUMP graph_executor.cpp:610] graph(%x.1 : Half(*, *),
[DUMP graph_executor.cpp:610]       %prob.1 : float):
[DUMP graph_executor.cpp:610]   %3 : bool = prim::Constant[value=1]() # test_fusion.py:19:42
[DUMP graph_executor.cpp:610]   %6 : float = prim::Constant[value=0.]() # test_fusion.py:18:25
[DUMP graph_executor.cpp:610]   %10 : str = prim::Constant[value="Exception"]() # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:803:8
[DUMP graph_executor.cpp:610]   %13 : float = prim::Constant[value=1.]() # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:21
[DUMP graph_executor.cpp:610]   %14 : bool = aten::lt(%prob.1, %6) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:7
[DUMP graph_executor.cpp:610]   %15 : bool = prim::If(%14) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:7
[DUMP graph_executor.cpp:610]     block0():
[DUMP graph_executor.cpp:610]       -> (%3)
[DUMP graph_executor.cpp:610]     block1():
[DUMP graph_executor.cpp:610]       %16 : bool = aten::gt(%prob.1, %13) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:17
[DUMP graph_executor.cpp:610]       -> (%16)
[DUMP graph_executor.cpp:610]    = prim::If(%15) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:4
[DUMP graph_executor.cpp:610]     block0():
[DUMP graph_executor.cpp:610]        = prim::RaiseException(%10) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:803:8
[DUMP graph_executor.cpp:610]       -> ()
[DUMP graph_executor.cpp:610]     block1():
[DUMP graph_executor.cpp:610]       -> ()
[DUMP graph_executor.cpp:610]   %20 : Half(*, *) = prim::DifferentiableGraph_0(%prob.1, %x.1)
[DUMP graph_executor.cpp:610]   return (%20)
[DUMP graph_executor.cpp:610] with prim::DifferentiableGraph_0 = graph(%1 : float,
[DUMP graph_executor.cpp:610]       %4 : Half(*, *)):
[DUMP graph_executor.cpp:610]   %69 : bool = prim::Constant[value=1]()
[DUMP graph_executor.cpp:610]   %10 : int = prim::Constant[value=1]() # <string>:103:64
[DUMP graph_executor.cpp:610]   %9 : float = prim::Constant[value=1.]() # <string>:100:18
[DUMP graph_executor.cpp:610]   %8 : None = prim::Constant()
[DUMP graph_executor.cpp:610]   %p1m.3 : float = aten::sub(%9, %1) # <string>:100:18
[DUMP graph_executor.cpp:610]   %22 : float = aten::div(%9, %p1m.3) # <string>:104:57
[DUMP graph_executor.cpp:610]   %res.1 : Half(*, *), %mask.4 : Bool(*, *), %result.3 : Half(*, *) = prim::FusionGroup_0(%4, %22, %p1m.3)
[DUMP graph_executor.cpp:610]   return (%res.1, %result.3, %8, %9, %10, %69, %p1m.3, %mask.4, %p1m.3)
[DUMP graph_executor.cpp:610] with prim::FusionGroup_0 = graph(%13 : Half(*, *),
[DUMP graph_executor.cpp:610]       %1 : float,
[DUMP graph_executor.cpp:610]       %9 : float):
[DUMP graph_executor.cpp:610]   %11 : int = prim::Constant[value=1]() # <string>:103:64
[DUMP graph_executor.cpp:610]   %14 : float = prim::Constant[value=0.]()
[DUMP graph_executor.cpp:610]   %result.3 : Half(*, *) = aten::threshold(%13, %14, %14) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:893:17
[DUMP graph_executor.cpp:610]   %12 : Half(*, *) = aten::rand_like(%result.3, %11) # <string>:103:27
[DUMP graph_executor.cpp:610]   %mask.4 : Bool(*, *) = aten::lt(%12, %9) # <string>:103:27
[DUMP graph_executor.cpp:610]   %7 : Half(*, *) = aten::type_as(%mask.4, %result.3) # <string>:104:26
[DUMP graph_executor.cpp:610]   %5 : Half(*, *) = aten::mul(%7, %result.3) # <string>:104:26
[DUMP graph_executor.cpp:610]   %res.1 : Half(*, *) = aten::mul(%5, %1) # <string>:104:26
[DUMP graph_executor.cpp:610]   return (%res.1, %mask.4, %result.3)
```
the optimized graph from the profiling executor.
```
[DUMP profiling_graph_executor_impl.cpp:099] Optimized Graph :
[DUMP profiling_graph_executor_impl.cpp:099] graph(%x.1 : Tensor,
[DUMP profiling_graph_executor_impl.cpp:099]       %prob.1 : float):
[DUMP profiling_graph_executor_impl.cpp:099]   %5 : bool = prim::Constant[value=1]() # test_fusion.py:19:42
[DUMP profiling_graph_executor_impl.cpp:099]   %4 : float = prim::Constant[value=0.]() # test_fusion.py:18:25
[DUMP profiling_graph_executor_impl.cpp:099]   %3 : str = prim::Constant[value="Exception"]() # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:803:8
[DUMP profiling_graph_executor_impl.cpp:099]   %2 : float = prim::Constant[value=1.]() # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:21
[DUMP profiling_graph_executor_impl.cpp:099]   %19 : int = prim::BailoutTemplate_0()
[DUMP profiling_graph_executor_impl.cpp:099]   %17 : Half(5120, 1024) = prim::BailOut[index=0](%19, %x.1, %prob.1)
[DUMP profiling_graph_executor_impl.cpp:099]   %8 : bool = aten::lt(%prob.1, %4) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:7
[DUMP profiling_graph_executor_impl.cpp:099]   %9 : bool = prim::If(%8) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:7
[DUMP profiling_graph_executor_impl.cpp:099]     block0():
[DUMP profiling_graph_executor_impl.cpp:099]       -> (%5)
[DUMP profiling_graph_executor_impl.cpp:099]     block1():
[DUMP profiling_graph_executor_impl.cpp:099]       %10 : bool = aten::gt(%prob.1, %2) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:17
[DUMP profiling_graph_executor_impl.cpp:099]       -> (%10)
[DUMP profiling_graph_executor_impl.cpp:099]    = prim::If(%9) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:4
[DUMP profiling_graph_executor_impl.cpp:099]     block0():
[DUMP profiling_graph_executor_impl.cpp:099]        = prim::RaiseException(%3) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:803:8
[DUMP profiling_graph_executor_impl.cpp:099]       -> ()
[DUMP profiling_graph_executor_impl.cpp:099]     block1():
[DUMP profiling_graph_executor_impl.cpp:099]       -> ()
[DUMP profiling_graph_executor_impl.cpp:099]   %20 : Tensor = prim::DifferentiableGraph_1(%prob.1, %17)
[DUMP profiling_graph_executor_impl.cpp:099]   %18 : Half(5120, 1024) = prim::BailOut[index=1](%19, %20)
[DUMP profiling_graph_executor_impl.cpp:099]   return (%18)
[DUMP profiling_graph_executor_impl.cpp:099] with prim::BailoutTemplate_0 = graph(%x.1 : Tensor,
[DUMP profiling_graph_executor_impl.cpp:099]       %prob.1 : float):
[DUMP profiling_graph_executor_impl.cpp:099]   %2 : Half(5120, 1024) = prim::BailOut[index=0](%x.1, %prob.1)
[DUMP profiling_graph_executor_impl.cpp:099]   %3 : float = prim::Constant[value=1.]() # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:21
[DUMP profiling_graph_executor_impl.cpp:099]   %4 : str = prim::Constant[value="Exception"]() # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:803:8
[DUMP profiling_graph_executor_impl.cpp:099]   %5 : float = prim::Constant[value=0.]() # test_fusion.py:18:25
[DUMP profiling_graph_executor_impl.cpp:099]   %6 : bool = prim::Constant[value=1]() # test_fusion.py:19:42
[DUMP profiling_graph_executor_impl.cpp:099]   %result.2 : Half(5120, 1024) = aten::threshold(%2, %5, %5) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:893:17
[DUMP profiling_graph_executor_impl.cpp:099]   %8 : bool = aten::lt(%prob.1, %5) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:7
[DUMP profiling_graph_executor_impl.cpp:099]   %9 : bool = prim::If(%8) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:7
[DUMP profiling_graph_executor_impl.cpp:099]     block0():
[DUMP profiling_graph_executor_impl.cpp:099]       -> (%6)
[DUMP profiling_graph_executor_impl.cpp:099]     block1():
[DUMP profiling_graph_executor_impl.cpp:099]       %10 : bool = aten::gt(%prob.1, %3) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:17
[DUMP profiling_graph_executor_impl.cpp:099]       -> (%10)
[DUMP profiling_graph_executor_impl.cpp:099]    = prim::If(%9) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:802:4
[DUMP profiling_graph_executor_impl.cpp:099]     block0():
[DUMP profiling_graph_executor_impl.cpp:099]        = prim::RaiseException(%4) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:803:8
[DUMP profiling_graph_executor_impl.cpp:099]       -> ()
[DUMP profiling_graph_executor_impl.cpp:099]     block1():
[DUMP profiling_graph_executor_impl.cpp:099]       -> ()
[DUMP profiling_graph_executor_impl.cpp:099]   %11 : Tensor = aten::dropout(%result.2, %prob.1, %6) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:807:17
[DUMP profiling_graph_executor_impl.cpp:099]   %12 : Half(5120, 1024) = prim::BailOut[index=1](%11)
[DUMP profiling_graph_executor_impl.cpp:099]   return (%12)
[DUMP profiling_graph_executor_impl.cpp:099] with prim::DifferentiableGraph_1 = graph(%1 : float,
[DUMP profiling_graph_executor_impl.cpp:099]       %4 : Half(5120, 1024)):
[DUMP profiling_graph_executor_impl.cpp:099]   %69 : bool = prim::Constant[value=1]()
[DUMP profiling_graph_executor_impl.cpp:099]   %10 : int = prim::Constant[value=1]() # <string>:103:64
[DUMP profiling_graph_executor_impl.cpp:099]   %9 : float = prim::Constant[value=1.]() # <string>:100:18
[DUMP profiling_graph_executor_impl.cpp:099]   %8 : None = prim::Constant()
[DUMP profiling_graph_executor_impl.cpp:099]   %p1m.3 : float = aten::sub(%9, %1) # <string>:100:18
[DUMP profiling_graph_executor_impl.cpp:099]   %22 : float = aten::div(%9, %p1m.3) # <string>:104:57
[DUMP profiling_graph_executor_impl.cpp:099]   %res.1 : Tensor, %mask.4 : Tensor, %result.3 : Half(5120, 1024) = prim::FusionGroup_0(%4, %22, %p1m.3)
[DUMP profiling_graph_executor_impl.cpp:099]   return (%res.1, %result.3, %8, %9, %10, %69, %p1m.3, %mask.4, %p1m.3)
[DUMP profiling_graph_executor_impl.cpp:099] with prim::FusionGroup_0 = graph(%13 : Half(5120, 1024),
[DUMP profiling_graph_executor_impl.cpp:099]       %1 : float,
[DUMP profiling_graph_executor_impl.cpp:099]       %9 : float):
[DUMP profiling_graph_executor_impl.cpp:099]   %11 : int = prim::Constant[value=1]() # <string>:103:64
[DUMP profiling_graph_executor_impl.cpp:099]   %14 : float = prim::Constant[value=0.]()
[DUMP profiling_graph_executor_impl.cpp:099]   %result.3 : Half(5120, 1024) = aten::threshold(%13, %14, %14) # /private/home/villedepommes/miniconda3/envs/enable_tests2/lib/python3.7/site-packages/torch/nn/functional.py:893:17
[DUMP profiling_graph_executor_impl.cpp:099]   %12 : Tensor = aten::rand_like(%result.3, %11) # <string>:103:27
[DUMP profiling_graph_executor_impl.cpp:099]   %mask.4 : Tensor = aten::lt(%12, %9) # <string>:103:27
[DUMP profiling_graph_executor_impl.cpp:099]   %7 : Tensor = aten::type_as(%mask.4, %result.3) # <string>:104:26
[DUMP profiling_graph_executor_impl.cpp:099]   %5 : Tensor = aten::mul(%7, %result.3) # <string>:104:26
[DUMP profiling_graph_executor_impl.cpp:099]   %res.1 : Tensor = aten::mul(%5, %1) # <string>:104:26
[DUMP profiling_graph_executor_impl.cpp:099]   return (%res.1, %mask.4, %result.3)
```

both have `threshold` fused into `prim::FusionGroup_0`

@kevinstephano you will need to run the graph twice (the first time we profile a graph)

**Closed by Krovatkin** 2020-01-23 22:05 UTC
Labels: jit, triaged
