### ISSUE TITLE
Discrepancy Between Eager Mode and Optimized Mode Results for hinge_embedding_loss

### ISSUE THREAD

**Issue by GwiHwan-Go** [pytorch/pytorch#113012] opened 2023-11-06 07:42 UTC
### 🐛 Describe the bug

There's an inconsistency between the results of `torch.nn.functional.hinge_embedding_loss` in eager mode and when using `torch.compile` in optimized mode (`reduce-overhead`).

Interestingly, changing the value of tensor x appears to eliminate the error, which might indicate that specific tensor values trigger this discrepancy.

### To Reproduce

Here is the code snippet that can be used to reproduce the issue:

```python
import torch
import torch.nn as nn

def forward(x, y):
  return torch.nn.functional.hinge_embedding_loss(input=x, target=y, margin=0.11, reduction='sum')        

x = torch.tensor([-668044.5], dtype=torch.float32)
y = torch.rand([1], dtype=torch.float32)

# Run in eager mode
no_op_info = forward(x, y)

# Run in compiled mode
op_info = torch.compile(forward, mode='reduce-overhead', fullgraph=True)(x, y)

# Check if both results are close
results_close = torch.allclose(no_op_info.to('cpu'), op_info.to('cpu'), rtol=1e-3, atol=1e-3, equal_nan=True)
print(f"Are the results close? {results_close}")
```

## Versions

PyTorch version: 2.2.0.dev20231023+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-86-generic-x86_64-with-glibc2.35

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by jgong5** [comment] 2023-11-06 13:49
Another issue caused by the usage of `-ffast-math` and more specifically, `-funsafe-math-optimizations` implied by it. The result of `hinge_embedding_loss` when the label is not `-1` or `1` is `margin - x + x` where `margin_diff = marge - x` and `margin_diff + x` are computed separately and the example inputs bring rounding error with fp32 representation. Even though, it is not documented officially, the eager mode implementation and the compiled code are supposed to match - the aot_eager's behavior matches the eager kernel implementation. In Inductor CPP backend, `margin - x + x`  is simplified to `margin` without rounding error, thus causing the discrepancy.

We have similar issue from `-ffast-math`: https://github.com/pytorch/pytorch/issues/93598 owned by @Valentine233 . I'm adding @Valentine233 on this issue too. Perhaps, we can disable `-funsafe-math-optimizations` if there is no performance regression.

**Comment by Valentine233** [comment] 2023-11-28 05:03
Fixed by https://github.com/pytorch/pytorch/pull/113347.

**Closed by Valentine233** 2023-11-28 05:03 UTC
Labels: triaged, intel, oncall: pt2, module: cpu inductor
