### ISSUE TITLE
torch.triangular_solve on CUDA returns nan if triangular matrix is not full rank

### ISSUE THREAD

**Issue by trenta3** [pytorch/pytorch#56326] opened 2021-04-17 09:00 UTC
## 🐛 Bug
Torch triangular_solve raises an error on CPU if the triangular matrix is not full rank, while it returns nan on CUDA.

## To Reproduce
```python3
>>> import torch
>>> b = torch.tensor([1, 3, 0], dtype=torch.float32)
>>> Re = torch.tensor([[1, 2, 3], [0, 4, 5], [0, 0, 0]], dtype=torch.float32)
>>> torch.triangular_solve(b.unsqueeze(-1), Re)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: triangular_solve_cpu: U(3,3) is zero, singular U.

>>> b = b.to("cuda")
>>> Re = Re.to("cuda")
>>> torch.triangular_solve(b.unsqueeze(-1), Re)
torch.return_types.triangular_solve(
solution=tensor([[nan],
        [nan],
        [nan]], device='cuda:0'),
cloned_coefficient=tensor([[1., 2., 3.],
        [0., 4., 5.],
        [0., 0., 0.]], device='cuda:0'))
```

## Expected behavior
Raise an error to conform to the CPU version.

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.14.0-rc1

Python version: 3.9 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 440.100
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] backpack-for-pytorch==1.2.0
[pip3] numpy==1.20.2
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0a0
[conda] backpack-for-pytorch      1.2.0                    pypi_0    pypi
[conda] cudatoolkit               10.2.89              h8f6ccaa_8    conda-forge
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] libcblas                  3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] magma                     2.5.4                h5da55e3_2    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.20.2           py39hdbf815f_0    conda-forge
[conda] pytorch                   1.8.0           cuda102py39hf89b2ab_0    conda-forge
[conda] pytorch-gpu               1.8.0           cuda102py39hf05f184_0    conda-forge
[conda] torchvision               0.9.0           py39cuda102h5ebb52a_0_cuda    conda-forge
```

cc @ngimel @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @IvanYashchuk @xwang233

**Comment by mruberry** [comment] 2021-04-23 05:53
Thanks for reporting this issue, @trenta3. That is an odd inconsistency, and we should probably revisit the design of this operation

**Comment by IvanYashchuk** [comment] 2021-04-23 08:33
This is a duplicate of https://github.com/pytorch/pytorch/issues/43141. Copying [my answer](https://github.com/pytorch/pytorch/issues/43141#issuecomment-692815473) from there:
> the GPU version is based on BLAS' `trsm` routine, while CPU version is based on LAPACK's `trtrs`.
The difference between those that `trsm` does not include any tests for singularity or near-singularity, it's intended to be used specifically for non-singular systems, therefore the behavior is as expected. MAGMA and cuSOLVER do not implement `trtrs`.

We could add a check for CUDA inputs whether the diagonal contains zeros, emulating the `trtrs` behavior, but that would degrade the performance.

**Comment by mruberry** [comment] 2021-04-27 11:24
Maybe another docs issue, @Lezcano?

**Comment by Lezcano** [comment] 2021-04-27 11:25
Very much looks like it. We should report all these behaviours in the documentation.

**Comment by Lezcano** [comment] 2021-04-27 11:27
Now, another take on this would be to do something like throw an error if the input does not have `NaNs`  but the output does. But then we would get again on the discussion that we have had on all `torch.linalg` functions about how to report this when we have a batch of matrices and `NaNs` appear in some of them...

**Closed** 2021-09-08 00:27 UTC
Labels: module: cuda, triaged, module: linear algebra
