### ISSUE TITLE
Dynamic casting fail

### ISSUE THREAD

**Issue by PierreGtch** [pytorch/pytorch#57194] opened 2021-04-28 21:40 UTC
## 🐛 Bug
The casting of a boolean tensor to a float tensor fails under certain conditions

## To Reproduce

```python
import torch
a = torch.tensor(1 ,dtype=torch.bool)                                    
b = torch.tensor(1 ,dtype=torch.bool)                                    
c = torch.tensor(0 ,dtype=torch.float16)                                 
torch.logical_and(a,b,out=c)                                          
```
 Output :
```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-189-accc88672979> in <module>
----> 1 torch.logical_and(a,b,out=c)

RuntimeError: !needs_dynamic_casting<func_t>::check(iter) INTERNAL ASSERT FAILED at "/pytorch/aten/src/ATen/native/cpu/Loops.h":194, please report a bug to PyTorch.
```
I got the same result with `c`'s dtype set at any other type of integer or float.

## Expected behavior
I'm not sure if this type of casting is expected to be supported but the error message said I should report the bug. 
If supported, the value of `c` should be set to `tensor(1., dtype=torch.float16)`.

## Environment

 - PyTorch Version: 1.7.0
 - OS: linux
 - How you installed PyTorch: pip
 - Python version: 3.8.7
 - CUDA/cuDNN version: -
 - GPU models and configuration: -
 - Any other relevant information: computed on CPU

**Comment by skyline75489** [comment] 2021-04-29 07:13
I can't reproduce this with latest master. Can you try this with 1.8.1?

**Comment by PierreGtch** [comment] 2021-04-29 09:06
I tried with pytorch 1.8.1 and I can't reproduce it either with this version

Le jeu. 29 avr. 2021 à 09:13, Chester Liu ***@***.***> a
écrit :

**Comment by gchanan** [comment] 2021-04-29 16:31
closing because the issue appears to be fixed.

**Closed by gchanan** 2021-04-29 16:31 UTC
