### ISSUE TITLE
[Flex attention] Error in create_block_mask with _compile=True on Torch 2.6

### ISSUE THREAD

**Issue by kebijuelun** [pytorch/pytorch#136306] opened 2024-09-19 07:57 UTC
### Issue Summary
When using `torch2.6.0.dev20240918+cu121`, the `create_block_mask` function with the `_compile=True` flag results in a runtime error. The error does not occur if `_compile=False` is used, nor does it occur on `torch2.5.0.dev20240907+cu121`.

### Code to Reproduce

The issue can be reproduced with the following script, which generates a document causal attention mask based on a document ID tensor:

https://gist.github.com/kebijuelun/a30a8a336329faed8e4b7dab515882fe

```python
from typing import List, Union
import torch
from torch import Tensor
from torch.nn.attention.flex_attention import _mask_mod_signature, create_block_mask

def _offsets_to_doc_ids_tensor(offsets):
    device = offsets.device
    counts = offsets[1:] - offsets[:-1]
    return torch.repeat_interleave(
        torch.arange(len(counts), device=device, dtype=torch.int32), counts
    )

def length_to_offsets(lengths: List[int], device: Union[str, torch.device]) -> Tensor:
    offsets = [0]
    offsets.extend(lengths)
    offsets = torch.tensor(offsets, device=device, dtype=torch.int32)
    offsets = torch.cumsum(offsets, dim=-1)
    return offsets

def generate_doc_mask_mod(offsets: Tensor) -> _mask_mod_signature:
    document_id = _offsets_to_doc_ids_tensor(offsets)

    def doc_mask_mod(b, h, q_idx, kv_idx):
        same_doc = document_id[q_idx] == document_id[kv_idx]
        return same_doc

    return doc_mask_mod

def main(device: str = "cpu"):
    import random
    random.seed(0)

    def generate_random_lengths(total_length, num_documents):
        lengths = [1] * num_documents
        remaining_length = total_length - num_documents
        for _ in range(remaining_length):
            index = random.randint(0, num_documents - 1)
            lengths[index] += 1
        return lengths

    max_seq_len, doc_count = 128, 4
    B, H, SEQ_LEN, HEAD_DIM = 1, 1, max_seq_len, 8

    lengths = generate_random_lengths(max_seq_len, doc_count)
    offsets = length_to_offsets(lengths, device)

    def make_tensor():
        return torch.ones(B, H, SEQ_LEN, HEAD_DIM, device=device)

    query, key = make_tensor(), make_tensor()
    document_causal_mask = generate_doc_mask_mod(offsets)
    block_mask = create_block_mask(document_causal_mask, 1, 1, SEQ_LEN, SEQ_LEN, device=query.device, _compile=True)

main()
```

### Error Message

The following error is raised when `_compile=True` is used:

```
torch._dynamo.exc.TorchRuntimeError: Failed running call_function <built-in function getitem>(*(FakeTensor(..., size=(128,), dtype=torch.int32), BatchedTensor(lvl=3, bdim=0, value=
    FakeTensor(..., size=(128,), dtype=torch.int64)
)), **{}):
vmap: It looks like you're calling .item() on a Tensor. We don't support vmap over calling .item() on a Tensor, please try to rewrite what you're doing with other operations. If error is occurring somewhere inside PyTorch internals, please file a bug report.
```

### Additional Information

- **PyTorch version**: `torch2.6.0.dev20240918+cu121`
- **Working version**: `torch2.5.0.dev20240907+cu121`
- The error disappears if `_compile=False`.

Could you provide guidance on how to resolve this issue? It seems related to vmap and tensor indexing with `item()` usage, but the problem doesn't appear in previous versions of PyTorch.

### versions
```
Collecting environment information...
PyTorch version: 2.6.0.dev20240918+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.250-2-velinux1u1-amd64-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A800-SXM4-80GB
Nvidia driver version: 535.129.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.9.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.9.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] flake8==6.1.0
[pip3] intel-extension-for-pytorch==2.2.0
[pip3] msgpack-numpy==0.4.8
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.26.4
[pip3] open_clip_torch==2.26.1
[pip3] pytorch-triton==3.1.0+5fe38ffd73
[pip3] pytorchvideo==0.1.5
[pip3] torch==2.6.0.dev20240918+cu121
[pip3] torchaudio==2.5.0.dev20240918+cu121
[pip3] torchvision==0.20.0.dev20240918+cu121
[conda] intel-extension-for-pytorch 2.2.0                    pypi_0    pypi
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] open-clip-torch           2.26.1                   pypi_0    pypi
[conda] pytorch-triton            3.1.0+5fe38ffd73          pypi_0    pypi
[conda] torch                     2.6.0.dev20240918+cu121          pypi_0    pypi
[conda] torchaudio                2.5.0.dev20240918+cu121          pypi_0    pypi
[conda] torchvision               0.20.0.dev20240918+cu121          pypi_0    pypi
```

cc @ezyang @chauhang @penguinwu @zou3519 @ydwu4 @bdhirsh @Chillee @drisspg @yanboliang @BoyuanFeng

**Comment by masnesral** [comment] 2024-09-21 21:29
@yanboliang: assigning to you so you can triage appropriately.

**Comment by yanboliang** [comment] 2024-09-24 00:40
This is the same as #136427, sorry I checked these issues in the reversed order. Check the root cause at [here](https://github.com/pytorch/pytorch/issues/136427#issuecomment-2369864733), I'll prioritize this issue.

**Comment by ppwwyyxx** [comment] 2024-09-24 01:10
This is different from #136427 : this issue is about `create_block_mask` which implemented a workaround for the issue that `__torch_function__` is not supported under compile: https://github.com/pytorch/pytorch/blob/06909803ccc1f6f92a101e40a67554078ba2cfa0/torch/nn/attention/flex_attention.py#L772-L775

According to OP, this workaround works in torch2.5.0.dev20240907+cu121 but not newer nightlies. 

So this issue is a regression that breaks existing workaround code; where in #136427, `create_mask` lacks the workaround and therefore was never expected to work.

**Comment by yanboliang** [comment] 2024-09-24 01:17
@ppwwyyxx The workaround is behind a flag ```_compile```, so I think we are talking the same thing?
https://github.com/pytorch/pytorch/blob/06909803ccc1f6f92a101e40a67554078ba2cfa0/torch/nn/attention/flex_attention.py#L740

**Comment by Chillee** [comment] 2024-09-24 03:04
This code runs correctly for me.

**Comment by kebijuelun** [comment] 2024-09-24 03:56
> This code runs correctly for me.

Are you able to reproduce this issue with torch2.6.0.dev20240918+cu121? Alternatively, I can check the code in your environment if you could share your PyTorch version.

**Comment by drisspg** [comment] 2024-09-26 00:16
I am able to repro this on latest nightly

**Comment by drisspg** [comment] 2024-09-26 00:22
Just updated my branch to include; https://github.com/pytorch/pytorch/pull/136590 and verified that this fixes the issue for me.

**Closed by drisspg** 2024-09-26 00:22 UTC
Labels: triaged, oncall: pt2, module: higher order operators, module: pt2-dispatcher, module: flex attention
