### ISSUE TITLE
caffe2 `RoiAlignTest.CheckCPUGPUEqual` fails on Windows

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#35547] opened 2020-03-27 16:59 UTC
From https://app.circleci.com/pipelines/github/pytorch/pytorch/144817/workflows/c0ac3f91-edb1-4294-9cf4-aad70b6a89d0/jobs/4916119 
```
[ RUN      ] RoiAlignTest.CheckCPUGPUEqual
unknown file: error: C++ exception with description "[enforce fail at roi_align_op.h:39] . Not Implemented.
Error from operator: 
input: "X" input: "R" output: "Y" name: "test" type: "RoIAlign" arg { name: "spatial_scale" f: 0.0625 } arg { name: "pooled_h" i: 6 } arg { name: "pooled_w" i: 8 } arg { name: "sampling_ratio" i: 2 } device_option { device_type: 0 }(no backtrace available)" thrown in the test body.
[  FAILED  ] RoiAlignTest.CheckCPUGPUEqual (148 ms)
```

cc @peterjc123

**Comment by ibrahimsoliman97** [comment] 2020-05-14 01:26
I am facing this problem using libtorch 1.5 C++ CPU Debug x64 version.
Here is my full log:
`The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__/detectron2/export/caffe2_modeling.py", line 16, in forward
    _5, _6, _7, _8, _9, _10, = (_2).forward(input, )
    _11 = (_1).forward(_5, _6, _7, _8, _9, im_info, )
    _12 = (_0).forward(_11, _5, _6, _7, _10, im_info, )
           ~~~~~~~~~~~ <--- HERE
    _13, _14, _15, = _12
    return (_13, _14, _15)
  File "code/__torch__/detectron2/modeling/roi_heads/roi_heads.py", line 15, in forward
    im_info: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
    _0 = self.box_head
    _1 = (self.box_pooler).forward(argument_1, argument_2, argument_3, argument_4, argument_5, )
          ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _2 = (self.box_predictor).forward((_0).forward(_1, ), )
    _3, _4, = _2
  File "code/__torch__/detectron2/export/c10.py", line 49, in forward
    argument_5: Tensor) -> Tensor:
    roi_fpn, roi_fpn0, roi_fpn1, roi_fpn2, rois_idx_restore_int32 = ops._caffe2.DistributeFpnProposals(argument_1, 224, 4, 5, 2, False, None)
    _25 = ops._caffe2.RoIAlign(argument_2, roi_fpn, "NCHW", 0.25, 7, 7, 0, True, None)
          ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _26 = ops._caffe2.RoIAlign(argument_3, roi_fpn0, "NCHW", 0.125, 7, 7, 0, True, None)
    _27 = ops._caffe2.RoIAlign(argument_4, roi_fpn1, "NCHW", 0.0625, 7, 7, 0, True, None)

Traceback of TorchScript, original code (most recent call last):
/opt/conda/lib/python3.6/site-packages/detectron2/export/c10.py(336): forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/opt/conda/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py(648): _forward_box
/opt/conda/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py(595): forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/opt/conda/lib/python3.6/site-packages/detectron2/export/caffe2_modeling.py(271): forward
/opt/conda/lib/python3.6/contextlib.py(52): inner
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/opt/conda/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
/opt/conda/lib/python3.6/site-packages/detectron2/export/api.py(135): export_torchscript
./caffe2_converter.py(84): <module>
RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented.
`

**Comment by malfet** [comment] 2020-05-14 01:30
@ibrahimsoliman97 not sure how this problem is related to abovementioned issue. But did you run into it using your own build of pytorch or using binaries downloaded from https://pytorch.org/get-started/locally/

**Comment by ibrahimsoliman97** [comment] 2020-05-14 01:38
It might be related since the error massage is : `RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented.`
I downloaded the binary from pytorch https://pytorch.org/get-started/locally/
I am trying the GPU version now and will let you know the result.

**Comment by ibrahimsoliman97** [comment] 2020-05-14 02:43
After my testing:
I can run my model successfully using PyTorch 1.5 on Python CPU and GPU versions (Linux),
Furthermore, i can run the model successfully using PyTorch 1.5 on C++ GPU version (Windows10).
**Finally, I am facing this error `RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented.` on PyTorch 1.5 C++ CPU version (Windows10).**

All my PyTorch are installed from binaries provided by PyTorch at  https://pytorch.org/get-started/locally/
Thanks.

**Comment by peterjc123** [comment] 2020-05-14 03:24
I think this error is caused by the fact that `CAFFE_ENFORCE_EQ` is not implemented on Windows.

**Comment by ibrahimsoliman97** [comment] 2020-07-01 09:54
This error of `RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented` still exists on PyTorch 1.5.1 C++ CPU version.
is there any solution for this issue ?

**Comment by peterjc123** [comment] 2020-07-01 14:45
It is interesting that the test itself is fixed. See https://github.com/pytorch/pytorch/pull/40857

**Comment by peterjc123** [comment] 2020-07-01 14:45
> This error of `RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented` still exists on PyTorch 1.5.1 C++ CPU version.
> is there any solution for this issue ?

Could you please post the stacktrace since you are using the Debug version?

**Comment by ibrahimsoliman97** [comment] 2020-07-02 02:02
Here is the stacktrace:
`The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 11, in forward
    _1 = torch.as_tensor([height, width, 1], dtype=6, device=None)
    info = torch.unsqueeze(_1, 0)
    _2 = (self.traced_model).forward((image, info), )
          ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _3, _4, _5, = _2
    return torch.list([_3, _4, _5])
  File "code/__torch__/detectron2/export/caffe2_modeling.py", line 16, in forward
    _5, _6, _7, _8, _9, _10, = (_2).forward(input, )
    _11 = (_1).forward(_5, _6, _7, _8, _9, im_info, )
    _12 = (_0).forward(_11, _5, _6, _7, _10, im_info, )
           ~~~~~~~~~~~ <--- HERE
    _13, _14, _15, = _12
    return (_13, _14, _15)
  File "code/__torch__/detectron2/modeling/roi_heads/roi_heads.py", line 15, in forward
    im_info: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
    _0 = self.box_head
    _1 = (self.box_pooler).forward(argument_1, argument_2, argument_3, argument_4, argument_5, )
          ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _2 = (self.box_predictor).forward((_0).forward(_1, ), )
    _3, _4, = _2
  File "code/__torch__/detectron2/export/c10.py", line 49, in forward
    argument_5: Tensor) -> Tensor:
    roi_fpn, roi_fpn0, roi_fpn1, roi_fpn2, rois_idx_restore_int32 = ops._caffe2.DistributeFpnProposals(argument_1, 224, 4, 5, 2, False, None)
    _25 = ops._caffe2.RoIAlign(argument_2, roi_fpn, "NCHW", 0.25, 7, 7, 0, True, None)
          ~~~~~~~~~~~~~~~~~~~~ <--- HERE
    _26 = ops._caffe2.RoIAlign(argument_3, roi_fpn0, "NCHW", 0.125, 7, 7, 0, True, None)
    _27 = ops._caffe2.RoIAlign(argument_4, roi_fpn1, "NCHW", 0.0625, 7, 7, 0, True, None)

Traceback of TorchScript, original code (most recent call last):
/opt/conda/lib/python3.6/site-packages/detectron2/export/c10.py(336): forward
/home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/opt/conda/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py(726): _forward_box
/opt/conda/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py(673): forward
/home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/opt/conda/lib/python3.6/site-packages/detectron2/export/caffe2_modeling.py(272): forward
/opt/conda/lib/python3.6/contextlib.py(52): inner
/home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
/home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): __call__
/home/jovyan/.local/lib/python3.6/site-packages/torch/jit/__init__.py(1027): trace_module
/home/jovyan/.local/lib/python3.6/site-packages/torch/jit/__init__.py(875): trace
./n.py(48): __init__
./n.py(127): <module>
RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented.`

**Comment by peterjc123** [comment] 2020-07-02 03:04
> Here is the stacktrace:
> `The following operation failed in the TorchScript interpreter.
> Traceback of TorchScript, serialized code (most recent call last):
> File "code/**torch**.py", line 11, in forward
> _1 = torch.as_tensor([height, width, 1], dtype=6, device=None)
> info = torch.unsqueeze(_1, 0)
> _2 = (self.traced_model).forward((image, info), )
> ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
> _3, _4, _5, = _2
> return torch.list([_3, _4, _5])
> File "code/**torch**/detectron2/export/caffe2_modeling.py", line 16, in forward
> _5, _6, _7, _8, _9, _10, = (_2).forward(input, )
> _11 = (_1).forward(_5, _6, _7, _8, _9, im_info, )
> _12 = (_0).forward(_11, _5, _6, _7, _10, im_info, )
> ~~~~~~~~~~~ <--- HERE
> _13, _14, _15, = _12
> return (_13, _14, _15)
> File "code/**torch**/detectron2/modeling/roi_heads/roi_heads.py", line 15, in forward
> im_info: Tensor) -> Tuple[Tensor, Tensor, Tensor]:
> _0 = self.box_head
> _1 = (self.box_pooler).forward(argument_1, argument_2, argument_3, argument_4, argument_5, )
> ~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
> _2 = (self.box_predictor).forward((_0).forward(_1, ), )
> _3, _4, = _2
> File "code/**torch**/detectron2/export/c10.py", line 49, in forward
> argument_5: Tensor) -> Tensor:
> roi_fpn, roi_fpn0, roi_fpn1, roi_fpn2, rois_idx_restore_int32 = ops._caffe2.DistributeFpnProposals(argument_1, 224, 4, 5, 2, False, None)
> _25 = ops._caffe2.RoIAlign(argument_2, roi_fpn, "NCHW", 0.25, 7, 7, 0, True, None)
> ~~~~~~~~~~~~~~~~~~~~ <--- HERE
> _26 = ops._caffe2.RoIAlign(argument_3, roi_fpn0, "NCHW", 0.125, 7, 7, 0, True, None)
> _27 = ops._caffe2.RoIAlign(argument_4, roi_fpn1, "NCHW", 0.0625, 7, 7, 0, True, None)
> 
> Traceback of TorchScript, original code (most recent call last):
> /opt/conda/lib/python3.6/site-packages/detectron2/export/c10.py(336): forward
> /home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
> /home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): **call**
> /opt/conda/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py(726): _forward_box
> /opt/conda/lib/python3.6/site-packages/detectron2/modeling/roi_heads/roi_heads.py(673): forward
> /home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
> /home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): **call**
> /opt/conda/lib/python3.6/site-packages/detectron2/export/caffe2_modeling.py(272): forward
> /opt/conda/lib/python3.6/contextlib.py(52): inner
> /home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(534): _slow_forward
> /home/jovyan/.local/lib/python3.6/site-packages/torch/nn/modules/module.py(548): **call**
> /home/jovyan/.local/lib/python3.6/site-packages/torch/jit/**init**.py(1027): trace_module
> /home/jovyan/.local/lib/python3.6/site-packages/torch/jit/**init**.py(875): trace
> ./n.py(48): **init**
> ./n.py(127): 
> RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented.`

I mean the C++ one, not the python one.

**Comment by ibrahimsoliman97** [comment] 2020-07-02 03:32
The orignal model is scripted using python, This is the C++ Error that i catch when i want to infer the TorchScript model using c++:
![image](https://user-images.githubusercontent.com/30038478/86313375-85baa600-bc57-11ea-910f-2d3022579c53.png)

**Comment by peterjc123** [comment] 2020-07-02 06:15
@ibrahimsoliman97 Could you please post the result in the `Call Stack` window?

**Comment by ibrahimsoliman97** [comment] 2020-07-02 06:16
I get it working using CPU, It only works with the **Nightly version** . Thank You. 
Note: the error has not been fixed on v1.5.1.

**Comment by peterjc123** [comment] 2020-07-02 06:17
@ibrahimsoliman97 Okay, thanks for the info. So it's fixed on master. I'll put up a fix to re-enable the test.

**Closed** 2020-07-02 18:24 UTC
Labels: module: windows, triaged

**Comment by SpaceView** [comment] 2020-07-23 01:21
I don't know how this problem is solved, since I'm facing the exact errors when deploying detectron2.
I cloned the repo days ago, build the pytorch successfully on win10, detectron setup OK, and I tried to use vscode to see the debug, as below,
Traceback (most recent call last):
  File "D:\Anaconda3\envs\tchdev\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\envs\tchdev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\Administrator\.vscode\extensions\ms-python.python-2020.7.94776\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "D:\Anaconda3\envs\tchdev\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "D:\Anaconda3\envs\tchdev\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "D:\Anaconda3\envs\tchdev\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\devPytorch\detectron2_deploy\caffe2_converter.py", line 65, in <module>
    caffe2_model = tracer.export_caffe2()
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\detectron2-0.2-py3.7-win-amd64.egg\detectron2\export\api.py", line 112, in export_caffe2
    predict_net, init_net = export_caffe2_detection_model(model, inputs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\detectron2-0.2-py3.7-win-amd64.egg\detectron2\export\caffe2_export.py", line 143, in export_caffe2_detection_model
    onnx_model = export_onnx_model(model, (tensor_inputs,))
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\detectron2-0.2-py3.7-win-amd64.egg\detectron2\export\caffe2_export.py", line 60, in export_onnx_model
    operator_export_type=OperatorExportTypes.ONNX_ATEN_FALLBACK,
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\onnx\__init__.py", line 168, in export
    custom_opsets, enable_onnx_checker, use_external_data_format)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\onnx\utils.py", line 69, in export
    use_external_data_format=use_external_data_format)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\onnx\utils.py", line 488, in _export
    fixed_batch_size=fixed_batch_size)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\onnx\utils.py", line 334, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\onnx\utils.py", line 291, in _trace_and_get_graph_from_model
    torch.jit._get_trace_graph(model, args, _force_outplace=False, _return_inputs_states=True)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\jit\__init__.py", line 278, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\nn\modules\module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\jit\__init__.py", line 361, in forward
    self._force_outplace,
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\jit\__init__.py", line 348, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\nn\modules\module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\nn\modules\module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\detectron2-0.2-py3.7-win-amd64.egg\detectron2\export\caffe2_modeling.py", line 272, in forward
    detector_results, _ = self._wrapped_model.roi_heads(images, features, proposals)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\nn\modules\module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\nn\modules\module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\detectron2-0.2-py3.7-win-amd64.egg\detectron2\modeling\roi_heads\roi_heads.py", line 674, in forward
    pred_instances = self._forward_box(features, proposals)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\detectron2-0.2-py3.7-win-amd64.egg\detectron2\modeling\roi_heads\roi_heads.py", line 727, in _forward_box
    box_features = self.box_pooler(features, [x.proposal_boxes for x in proposals])
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\nn\modules\module.py", line 548, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\torch\nn\modules\module.py", line 534, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "D:\Anaconda3\envs\tchdev\lib\site-packages\detectron2-0.2-py3.7-win-amd64.egg\detectron2\export\c10.py", line 336, in forward
    aligned=aligned,
RuntimeError: [enforce fail at roi_align_op.h:39] . Not Implemented.
<-------------------------------------------------------------------->
and I tried to see what is going on in python, as below
(tchdev) D:\devPytorch>python
Python 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:11:50) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch as tch
>>> dir(tch.ops._caffe2)
['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'name']
>>> dir(tch.ops._caffe2.__name__)
['__add__', '__class__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getnewargs__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mod__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__rmod__', '__rmul__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', 'capitalize', 'casefold', 'center', 'count', 'encode', 'endswith', 'expandtabs', 'find', 'format', 'format_map', 'index', 'isalnum', 'isalpha', 'isascii', 'isdecimal', 'isdigit', 'isidentifier', 'islower', 'isnumeric', 'isprintable', 'isspace', 'istitle', 'isupper', 'join', 'ljust', 'lower', 'lstrip', 'maketrans', 'partition', 'replace', 'rfind', 'rindex', 'rjust', 'rpartition', 'rsplit', 'rstrip', 'split', 'splitlines', 'startswith', 'strip', 'swapcase', 'title', 'translate', 'upper', 'zfill']
>>>

it seems indeed roi_align_op is not compiled in, and _caffe2 doesn't see to have any useful functions!
but why, and how can we compile the _caffe2 functions into the lib/dll ?
