### ISSUE TITLE
Backward consistent behavior for AvgPool2d/avg_pool2d in PyTorch 1.2

### ISSUE THREAD

**Issue by thanhmvu** [pytorch/pytorch#26610] opened 2019-09-21 22:50 UTC
## 🐛 Bug
Hi, it seems that pytorch 1.2 fixed a bug with `ceil_mode` in `F. avg_pool2d()` in previous versions of pytorch (at least 1.0 and 1.1). Particularly, before the default says `ceil_mode=False` but it seems to always be True. However, I wonder if the default behavior in pytorch 1.2 should be set to `ceil_mode=True` for backward consistency with 1.1 and 1.0. 

## To Reproduce
```
import torch
import torch.nn
import torch.nn.functional

x = torch.ones(1,3,2,2)
print('default ceil_mode', torch.nn.functional.avg_pool2d(x, 4).shape)
print('ceil_mode=True', torch.nn.functional.avg_pool2d(x, 4, stride=4, padding=0, ceil_mode=True, count_include_pad=True).shape)
print('ceil_mode=False', torch.nn.functional.avg_pool2d(x, 4, stride=4, padding=0, ceil_mode=False, count_include_pad=True).shape)
```
### torch 1.1
default ceil_mode torch.Size([1, 3, 1, 1])

ceil_mode=True torch.Size([1, 3, 1, 1])

ceil_mode=False torch.Size([1, 3, 1, 1])

### torch 1.2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Given input size: (3x2x2). Calculated output size: (3x0x0). Output size is too small

ceil_mode=True torch.Size([1, 3, 1, 1])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: Given input size: (3x2x2). Calculated output size: (3x0x0). Output size is too small

**Comment by VitalyFedyunin** [comment] 2019-09-24 18:36
Agree this looks like compatibility breaking, feel free to submit PR fixing it.

**Comment by sheikmohdimran** [comment] 2019-10-01 06:42
Hi @VitalyFedyunin,
Can I take this up?

**Comment by VitalyFedyunin** [comment] 2019-10-07 17:08
> Hi @VitalyFedyunin,
> Can I take this up?

Sure

**Comment by gchanan** [comment] 2019-10-07 18:10
I don't think this needs to be fixed -- if you follow the math from the documentation, your example should have output size 0.  I think this is probably: https://github.com/pytorch/pytorch/pull/22304 but I haven't confirmed that yet.

**Comment by gchanan** [comment] 2019-10-07 18:16
Yep, I tried before before https://github.com/pytorch/pytorch/pull/22304 and indeed get the old, incorrect behavior.  So I'm going to close this.

**Closed by gchanan** 2019-10-07 18:16 UTC
Labels: module: nn, topic: bootcamp, triaged
