### ISSUE TITLE
Support transferring TorchScripted Module via RPC

### ISSUE THREAD

**Issue by zzzwen** [pytorch/pytorch#37197] opened 2020-04-24 01:16 UTC
We are seeing exceptions when transferring a TorchScripted Module via RPC. Can we add support for it?

cc @suo @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by thiagocrepaldi** [comment] 2020-05-14 23:12
Do you have a minimal repro? Maybe my scenario is similar to yours. It is a rough simplification of the RNN example at [Pytorch RPC tutorial](https://pytorch.org/tutorials/intermediate/rpc_tutorial.html):

```python
import os
import time
import torch
import torch.distributed.rpc as rpc
from torch import Tensor

def get_local_rank():
    return int(os.environ['OMPI_COMM_WORLD_LOCAL_RANK'])

def init_rpc():
    world_size=2
    rank=get_local_rank()
    os.environ['MASTER_ADDR'] = '10.123.134.28'
    os.environ['MASTER_PORT'] = '21234'
    if rank == 1:
        rpc.init_rpc("rank1", rank=rank, world_size=world_size)
    else:
        rpc.init_rpc("rank0", rank=rank, world_size=world_size)

def shutdown_rpc():
    rpc.shutdown()

# Model
class ChildModule(torch.nn.Module):
    def __init__(self):
        super(ChildModule, self).__init__()

    def forward(self, input: Tensor):
        return torch.tensor(1234)

class MasterModule(torch.nn.Module):
    def __init__(self, master_name):
        super(MasterModule, self).__init__()
        self.child_rref = rpc.remote(master_name, ChildModule)

    def forward(self, input: Tensor):
        args = [input]
        fut_child= rpc.rpc_async(self.child_rref.owner(), ChildModule.forward, args=args)
        ret = fut_child.wait()
        return ret

# Action time
init_rpc()

rank = get_local_rank()
if rank == 1:
    model = MasterModule('rank0')
    scripted_model = torch.jit.script(model)
    print(f'{"*"*80}\n{scripted_model.code}\n{"-"*80}')

time.sleep(5)
shutdown_rpc()
```

The backtrace is below and I am pretty sure it is related to the args argument of rpc_async call. Maybe it is a bug or maybe just a misuse of API:

```python
$ mpirun -np 2 python model_rpc.py 
Traceback (most recent call last):
  File "model_rpc.py", line 55, in <module>
    scripted_model = torch.jit.script(model)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/__init__.py", line 1261, in script
    return torch.jit._recursive.create_script_module(obj, torch.jit._recursive.infer_methods_to_compile)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 305, in create_script_module
    return create_script_module_impl(nn_module, concrete_type, stubs_fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 361, in create_script_module_impl
    create_methods_from_stubs(concrete_type, stubs)
  File "/opt/conda/lib/python3.7/site-packages/torch/jit/_recursive.py", line 279, in create_methods_from_stubs
    concrete_type._create_methods(defs, rcbs, defaults)
RuntimeError: 
rpc_async(dst_worker_name, user_callable, args, kwargs)does not support kwargs yet:
  File "model_rpc.py", line 41
    def forward(self, input: Tensor):
        args = [input]
        fut_child = rpc.rpc_async(self.child_rref.owner(), ChildModule.forward, args=args)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        ret = fut_child.wait()
        return ret
```

**Comment by xush6528** [comment] 2020-05-15 21:27
@thiagocrepaldi This is not related to TorchScript module through RPC. Can you create a separate issue?

**Comment by thiagocrepaldi** [comment] 2020-05-15 22:27
> 
> 
> @thiagocrepaldi This is not related to TorchScript module through RPC. Can you create a separate issue?

Sorry, I had the impression it was looking the title

**Comment by xush6528** [comment] 2020-05-19 06:24
Duplicate of https://github.com/pytorch/pytorch/issues/33052.

**Closed by xush6528** 2020-05-19 06:24 UTC
Labels: jit, module: rpc, triaged
