### ISSUE TITLE
RuntimeError: quantile() input tensor is too large

### ISSUE THREAD

**Issue by 7starsea** [pytorch/pytorch#67592] opened 2021-10-31 00:45 UTC
```
import torch; 
p = torch.tensor([0.2, 0.9]) 
n = int(2000e4);
x = torch.rand(n);
torch.quantile(x, p)
```
If we try to run the above code, we will get the RuntimeError ```RuntimeError: quantile() input tensor is too large```.

Another minor issue, my understanding is that the pytorch-apis try their best to stay close to numpy-apis, however, the ```torch.quantile``` use quantile values in ```[0, 1]```, while ```np.percentile``` use values in ```[0, 100]```. Could we do some changes to keep consistency between torch and numpy apis?

Thanks.
Aimin

**Comment by ngimel** [comment] 2021-11-01 17:49
Duplicate of #64947 for "input tensor is too large" part. `torch.quantile` is similar to `np.quantile`, not `np.percentile`, and thus is consistent.

**Comment by 7starsea** [comment] 2021-11-02 00:58
Thanks, never know ```np.quantile``` before.

**Comment by mruberry** [comment] 2021-11-02 11:30
Thanks for reporting this issue, @7starsea. Closing this as a duplicate of the earlier issue.

**Closed by mruberry** 2021-11-02 11:30 UTC
