### ISSUE TITLE
Random errors：module 'torch.utils.data' has no attribute 'IterableDataset'

### ISSUE THREAD

**Issue by bb-1357** [pytorch/pytorch#46465] opened 2020-10-16 14:13 UTC
## 🐛 Bug

cuda10.0, torch 1.1, python3.6~3.7,Our team uses the same set of codes, and the version of torch is **consistent**.The strange thing is that only a few people meet this error,in any ways they cannot import this package.

## To Reproduce

1.Not everyone had this problem.
2.Our only current solution is to copy and paste all torch files from people who can  import this package successfully.

Traceback (most recent call last):
  File "/home/yhwu/opennmt/opennmt-simple-1.0/preprocess.py", line 8, in <module>
    import torchtext.vocab
  File "/home/yhwu/anaconda3/lib/python3.7/site-packages/torchtext/__init__.py", line 6, in <module>
    from . import experimental
  File "/home/yhwu/anaconda3/lib/python3.7/site-packages/torchtext/experimental/__init__.py", line 1, in <module>
    from . import datasets
  File "/home/yhwu/anaconda3/lib/python3.7/site-packages/torchtext/experimental/datasets/__init__.py", line 1, in <module>
    from .language_modeling import LanguageModelingDataset, WikiText2, WikiText103, PennTreebank, WMTNewsCrawl  # NOQA
  File "/home/yhwu/anaconda3/lib/python3.7/site-packages/torchtext/experimental/datasets/language_modeling.py", line 4, in <module>
    from torchtext.experimental.datasets.raw import language_modeling as raw
  File "/home/yhwu/anaconda3/lib/python3.7/site-packages/torchtext/experimental/datasets/raw/__init__.py", line 1, in <module>
    from .text_classification import AG_NEWS, SogouNews, DBpedia, YelpReviewPolarity, \
  File "/home/yhwu/anaconda3/lib/python3.7/site-packages/torchtext/experimental/datasets/raw/text_classification.py", line 34, in <module>
    class RawTextIterableDataset(torch.utils.data.IterableDataset):
AttributeError: module 'torch.utils.data' has no attribute 'IterableDataset'

## Expected behavior

clearly, I just want to import this package.

## Environment

 - PyTorch Version (1.1):
 - OS (Linux):
 - How you installed PyTorch ( `pip`,):
 - Python version:3.6~.37
 - CUDA/cuDNN version:10.0

**Comment by gchanan** [comment] 2020-10-16 16:31
what's your version of torchtext?

**Comment by ailzhang** [comment] 2020-10-16 22:24
pytorch version 1.1 is too old, it may not work well with torchtext i think. would you mind upgrading to a newer version?

**Comment by ailzhang** [comment] 2020-10-16 22:25
I'm going to close this issue as it's not a bug report/feature request. Please feel free to reopen if necessary. Thanks!

**Closed by ailzhang** 2020-10-16 22:25 UTC
Labels: triaged

**Comment by marjimbel** [comment] 2020-10-20 21:54
i am actually having the same issue

**Comment by bb-1357** [comment] 2020-10-21 08:16
I find a solution, downgrade torchtext to 0.3.1.Since I cannot change my development environment,I copy all the torch 0.3.1 files, and paste them in my torchtext 0
.7.0 .My colleagues are very satisfied with my method.Hope this can help you too.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "pytorch/pytorch"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月21日(星期三) 凌晨5:54
收件人:&nbsp;"pytorch/pytorch"<pytorch@noreply.github.com&gt;;
抄送:&nbsp;"吴一珩"<514773500@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pytorch/pytorch] Random errors：module 'torch.utils.data' has no attribute 'IterableDataset' (#46465)





 
i am actually having the same issue
