### ISSUE TITLE
torch.nn.functional.interpolate nearest behaviour changed in PyTorch 1.9 and appears incorrect

### ISSUE THREAD

**Issue by nicholasw-gc** [pytorch/pytorch#62237] opened 2021-07-27 00:48 UTC
## 🐛 Bug

torch.nn.functional.interpolate with mode='nearest' has changed in PyTorch 1.9. The previous behaviour is more logical given a scale factor so close to 1.0 should not affect the nearest pixel. 

## To Reproduce

```
import torch
import torch.nn.functional as F

t_in = torch.tensor([[[1.0, 2.0]]])
t_out = F.interpolate(t_in, scale_factor=1.00001, recompute_scale_factor=False)

print(t_in)
print(t_out)
```

PyTorch 1.8
tensor([[[1., 2.]]])
tensor([[[1., 2.]]])

Torch 1.9
tensor([[[1., 2.]]])
tensor([[[1., 1.]]])

## Expected behavior

t_out to be printed as tensor([[[1., 2.]]]) matching PyTorch 1.8

## Environment

**Pytorch 1.8**
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.18.4
Libc version: glibc-2.25

Python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.8.0
[pip3] torchvision==0.9.0
[conda] Could not collect

**Pytorch 1.9**
PyTorch version: 1.9.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.18.4
Libc version: glibc-2.25

Python version: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-5.3.0-42-generic-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.9.0
[pip3] torchvision==0.10.0
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411

**Comment by ezyang** [comment] 2021-07-27 15:34
cc @vfdev-5

**Comment by vfdev-5** [comment] 2021-07-27 15:55
@ezyang thanks for pinging, I'll check that asap

**Comment by vfdev-5** [comment] 2021-08-06 11:42
@nicholasw-gc yes, there is unintended BC between 1.8.0 and 1.9.0 due to the fact that 1.8.0 handled explicitly cases like 
`output_size == input_size` and `output_size == 2 * input_size`.

If we expect `scale=1.00001` to give the same output as input, we have to use `recompute_scale_factor=True`:
```python
import torch
import torch.nn.functional as F

t_in = torch.tensor([[[1.0, 2.0]]])
t_out = F.interpolate(t_in, scale_factor=1.00001, recompute_scale_factor=True)

print(torch.__version__)
print(t_in)
print(t_out)
```
such that the final scale is recomputed from the output size (which is computed using `scale_factor`) and input size. This would also match scikit-image behaviour.

What do you think ?

**Comment by nicholasw-gc** [comment] 2021-08-06 12:11
Many my maths is wrong, but I would have thought that the second value could never equal the first value. Is in truncating rather than rounding so that (1-(2-1)/2)/1.00001+(2-1)/2=0.99999500005 maps to input 0 rather than input 1?

**Comment by vfdev-5** [comment] 2021-08-06 12:22
@nicholasw-gc here is how it is computed:
```python
import torch

s = 10
t_in = torch.arange(s, dtype=torch.float).unsqueeze(0).unsqueeze(0)
scale = 1.00001

output_size = (1, 1, s)
resized = torch.zeros(output_size)
scales = (1, 1, 1.0 / scale)

for i in range(resized.shape[2]):
    x = i * scales[2]
    ii = int(x)
    resized[0, 0, i] = t_in[0, 0, ii]

print(resized)
```

Yes, it uses int(index) instead of round(index).

**Comment by nicholasw-gc** [comment] 2021-08-06 13:53
I see, so it is not scaling about the centre, which perhaps is fine if the output size changes, so the centre is shifting, but otherwise means you'll truncate or extend one side more than the other. But I guess it was always this way except for cases around 1.0 and 2.0 previously?

As for the int(x) instead of round(x), is it still nearest neighbour rather than lowest neighbour? With the fix, would it be better to just use `x= (i + 0.5) * scales[2]` with int(x)?

**Comment by vfdev-5** [comment] 2021-08-11 10:53
@nicholasw-gc thanks a lot for pointing out that. Yes, that's true that more appropriate code should be 
```python
scale = 1.0 * isize / osize

for o in range(osize):
    x = (o + 0.5) * scale - 0.5  # vs o * scale
    i = round(x)  # vs floor(x)
    output[o] = input[i]
```
and this is what Pillow et scikit-image/scipy do.

**Comment by malfet** [comment] 2021-09-01 18:23
Looks like regression has not been fixed yet, but no activity for quite a while on the issue, moving to 1.10 milestone.

**Comment by malfet** [comment] 2021-10-13 21:52
Issue is still open, removing the milestone

**Comment by fumihwh** [comment] 2021-11-11 02:56
I face a bug also related to `torch.nn.functional.interpolate` but with `linear` mode.

```
import torch
import numpy as np
import torch.nn.functional as F

x = np.array([[[
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16],
]]])
y = F.interpolate(
    torch.from_numpy(x.astype(np.float32)), **{
        'size': (3, 1),
        'scale_factor': None,
        'mode': 'bilinear',
        'align_corners': None,
        'recompute_scale_factor': False
    })
print(f"torch.__version__: {torch.__version__}\n" f"{y}")
```

Get different result in 1.8.1 and 1.10.0
```
torch.__version__: 1.10.0
tensor([[[[ 3.1667],
          [ 8.5000],
          [13.8333]]]])
```
```
torch.__version__: 1.8.1
tensor([[[[ 1.6667],
          [ 7.0000],
          [12.3333]]]])

```

**Comment by vfdev-5** [comment] 2021-11-11 16:33
@fumihwh thanks for reporting ! However, it is not a bug between pytorch versions as torch interpolate is intended to match opencv behaviour. If you check other input/output sizes, 1.8.1 and 1.10.0 both matches the opencv results.
The case with output size equals one for a dimension that you are reporting looks like was a bug for 1.8.1 and it was fixed in 1.9.0 and since 1.9.0 the result matches opencv.


- Code to compare with opencv
```python
import torch
import numpy as np
import torch.nn.functional as F
import cv2
import numpy as np


osize = (12, 12)
isize = (32, 32)

x = np.arange(isize[0] * isize[1]).reshape(1, 1, *isize)

pth_res = F.interpolate(
    torch.from_numpy(x.astype(np.float32)), **{
        'size': osize,
        'scale_factor': None,
        'mode': 'bilinear',
        'align_corners': None,
        'recompute_scale_factor': False
    })
cv_res = cv2.resize(x[0, 0, ...].astype("float"), dsize=osize[::-1], interpolation=cv2.INTER_LINEAR)

print(f"torch.__version__: {torch.__version__}\n")
print("pth: ", pth_res[0, 0, :5, :5].numpy())
print("opencv: ", cv_res[:5, :5])

assert np.allclose(pth_res[0, 0, ...].numpy(), cv_res)
```

- result by opencv for your case
```python
import cv2
import numpy as np

ret = cv2.resize(x[0, 0, ...].astype("float"), dsize=(1, 3), interpolation=cv2.INTER_LINEAR)
print(ret)
> array([[ 3.16666667],
       [ 8.5       ],
       [13.83333333]])
```

**Comment by fumihwh** [comment] 2021-11-15 03:20
@vfdev-5 Awesome! I've tried and got exactly result you said.

**Comment by jbschlosser** [comment] 2022-01-07 23:03
Closing as addressed by addition of the new `nearest-exact` mode in #64501.

**Closed by jbschlosser** 2022-01-07 23:03 UTC
Labels: high priority, triaged, module: interpolation
