### ISSUE TITLE
[inductor][cpu]lcnet_050 AMP multiple/single thread static/dynamic shape default/CPP wrapper performance regression in 2024-06-30 nightly release

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#130023] opened 2024-07-03 11:28 UTC
### 🐛 Describe the bug

<p>AMP static shape CPP wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>lcnet_050</td>
      <td>multiple</td>
      <td>256</td>
      <td>2.430061</td>
      <td>0.015252709</td>
      <td>0.037065013285249</td>
      <td>19.550323</td>
      <td>256.0</td>
      <td>4.429776</td>
      <td>0.008456258</td>
      <td>0.037459328738208</td>
      <td>16.385265</td>
      <td>0.55</td>
      <td>1.01</td>
      <td>0.55</td>
      <td>0.84</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>lcnet_050</td>
      <td>single</td>
      <td>1</td>
      <td>2.42228</td>
      <td>0.002253871</td>
      <td>0.005459506645880001</td>
      <td>18.760154</td>
      <td>1.0</td>
      <td>3.458971</td>
      <td>0.0016889099999999998</td>
      <td>0.00584189071161</td>
      <td>16.047419</td>
      <td>0.7</td>
      <td>1.07</td>
      <td>0.75</td>
      <td>0.86</td>
    </tr>
  </tbody>

</table>

<p>AMP dynamic shape CPP wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>lcnet_050</td>
      <td>single</td>
      <td>1.0</td>
      <td>2.408062</td>
      <td>0.00227352</td>
      <td>0.0054747771182399995</td>
      <td>18.849379</td>
      <td>1.0</td>
      <td>3.356411</td>
      <td>0.001713565</td>
      <td>0.005751428415215</td>
      <td>14.210496</td>
      <td>0.72</td>
      <td>1.05</td>
      <td>0.75</td>
      <td>0.75</td>
    </tr>
  </tbody>

</table>

<p>AMP static shape default wrapper</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>timm_models</td>
      <td>lcnet_050</td>
      <td>multiple</td>
      <td>256</td>
      <td>2.183369</td>
      <td>0.019427126000000003</td>
      <td>0.042416584667494005</td>
      <td>22.154458</td>
      <td>256.0</td>
      <td>3.705299</td>
      <td>0.01156073</td>
      <td>0.04283596130827</td>
      <td>12.047613</td>
      <td>0.59</td>
      <td>1.01</td>
      <td>0.6</td>
      <td>0.54</td>
    </tr>
    <tr>
      <td>timm_models</td>
      <td>lcnet_050</td>
      <td>single</td>
      <td>1</td>
      <td>2.325263</td>
      <td>0.002737161</td>
      <td>0.006364619198343</td>
      <td>21.091505</td>
      <td>1.0</td>
      <td>3.072152</td>
      <td>0.002034193</td>
      <td>0.006249350093336</td>
      <td>12.130772</td>
      <td>0.76</td>
      <td>0.98</td>
      <td>0.74</td>
      <td>0.58</td>
    </tr>
  </tbody>

</table>

5d1763d1593de24b9eb318a1a942e81b5402e0cd
```
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance timm_models lcnet_050 amp first static cpp
Testing with cpp wrapper.
Testing with freezing on.
multi-threads testing....
loading model: 0it [00:00, ?it/s]
cpu  eval  lcnet_050
running benchmark: 100%|████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 18.42it/s]
2.432x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,lcnet_050,256,2.432123,15.473375,22.819846,0.971190,312.711987,321.988608,100,1,0,0,0,0,0
```

89696db4b05759bf0db271bd0c256b42b31df9b5
```
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance timm_models lcnet_050 amp first static cpp
Testing with cpp wrapper.
Testing with freezing on.
multi-threads testing....
loading model: 0it [00:00, ?it/s]
cpu  eval  lcnet_050
running benchmark: 100%|████████████████████████████████████████████████████████| 50/50 [00:02<00:00, 21.06it/s]
4.455x
WARNING:common:Trying to call the empty_gpu_cache for device: cpu, which is not in list [cuda, xpu]
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles,cudagraph_skips
cpu,lcnet_050,256,4.455031,8.487942,16.801501,0.974779,313.074074,321.174323,139,1,0,0,0,0,0
```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>23512dbe</td>
      <td>main</td>
      <td>23512dbe</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>9ae78a578caff195821ad535a9e8d8ef59552142</td>
      <td>main</td>
      <td>00f675bb4c2ec02bb5ffecfc75571026e220701c</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
      <td>main</td>
      <td>0.19.0a0+d23a6e1</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.4.0a0+b829e93</td>
      <td>main</td>
      <td>2.4.0a0+b829e93</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
      <td>main</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>fea73cb</td>
      <td>main</td>
      <td>fea73cb</td>
    </tr>
  </tbody>
</table>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)

bash inductor_single_run.sh multiple inference performance timm_models lcnet_050 amp first static cpp
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/5d1763d1593de24b9eb318a1a942e81b5402e0cd
[timm_models-lcnet_050-inference-amp-static-default-single-performance-drop_guilty_commit.log](https://github.com/user-attachments/files/16082914/timm_models-lcnet_050-inference-amp-static-default-single-performance-drop_guilty_commit.log)
cc @ezyang @anijain2305 @chauhang @penguinwu @WeizhuoZhang-intel @chuanqi129

**Comment by zxd1997066** [comment] 2024-07-04 02:53
Hi @anijain2305. according to the bisect search log and test results, the PR https://github.com/pytorch/pytorch/pull/129775 may introduce this AMP performance regression issue on CPU, could you please help to double check whether it is expected ?

**Comment by anijain2305** [comment] 2024-07-04 16:40
I will take a look. I was expecting some perf degradation, but not this much. We are planning to turn this flag ON in a couple of weeks  by default. I will debug.

**Comment by anijain2305** [comment] 2024-07-06 23:08
@zxd1997066 Can you share the repro command for CPU runs?

**Comment by anijain2305** [comment] 2024-07-06 23:39
So, I looked at the GPU numbers 

Before PR https://github.com/pytorch/pytorch/pull/129775 - 1.63x
After PR - 1.55x

So, there is degradation but not to the magnitude that is reported in this issue, atleast for GPU. `inline_inbuilt_nn_modules` flag, introduced by the PR, increases guard overhead. Since guard runs before the execution of compiled region, it does not explain why CPU sees such a big slowdown (it should have been even less slowdown, because CPUs runtime is typically much larger).

I think there is something else going on, maybe a pattern matcher did not kick in because of the inlining of inbuilt nn modules, and you might have to write a pattern to adapt to the inlined nn module. Is it possible for you to check the Inductor input FX graphs w and w/o inlining?

**Comment by leslie-fang-intel** [comment] 2024-07-07 23:40
> @zxd1997066 Can you share the repro command for CPU runs?

Here is the CMD to run on CPU for reproducing:
```
numactl -C 56-111 --membind=1 python benchmarks/dynamo/timm_models.py --performance --amp -dcpu -n50 --no-skip --dashboard --only lcnet_050 --inference --freezing --timeout 9000 --backend=inductor --output=/tmp/inductor_single_test_mt.csv
```

> I think there is something else going on, maybe a pattern matcher did not kick in because of the inlining of inbuilt nn modules, and you might have to write a pattern to adapt to the inlined nn module. Is it possible for you to check the Inductor input FX graphs w and w/o inlining?

cc @jiayisunx could you help to do some profile and check is any pattern matcher failure?

**Comment by jiayisunx** [comment] 2024-09-09 03:11
Fixed by https://github.com/pytorch/pytorch/pull/133968.

**Closed by jiayisunx** 2024-09-09 03:11 UTC
Labels: triaged, oncall: pt2, oncall: cpu inductor
