### ISSUE TITLE
torch.chunk returns Proxy

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#50174] opened 2021-01-07 00:29 UTC
Can be reproduced by:
```python
import torch
from torch.fx import symbolic_trace
    
    
class M(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x = torch.cat(x, dim=1)
        return x
    
m = M().eval()
m = symbolic_trace(m)
print(m)
print(m.graph)
```

Error:
```python
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-7f6caf437bce> in <module>
     12 
     13 m = M().eval()
---> 14 m = symbolic_trace(m)
     15 print(m)
     16 print(m.graph)

/mnt/xarfuse/uid-127034/bfe90f9e-seed-nspid4026531836-ns-4026531840/torch/fx/symbolic_trace.py in symbolic_trace(root)
    330 
    331     """
--> 332     return GraphModule(root if isinstance(root, torch.nn.Module) else torch.nn.Module(), Tracer().trace(root))

/mnt/xarfuse/uid-127034/bfe90f9e-seed-nspid4026531836-ns-4026531840/torch/fx/symbolic_trace.py in trace(self, root)
    308             torch.nn.Module.__getattr__ = module_getattr_wrapper  # type: ignore
    309             torch.nn.Module.__call__ = module_call_wrapper
--> 310             self.create_node('output', 'output', (self.create_arg(fn(*args)),), {},
    311                              type_expr=fn.__annotations__.get('return', None))
    312         finally:

<ipython-input-4-7f6caf437bce> in forward(self, x)
      8 
      9     def forward(self, x):
---> 10         x = torch.cat(x, dim=1)
     11         return x
     12 
```

**Comment by jamesr66a** [comment] 2021-01-07 00:31
If the number of chunks is fixed, you can iterate and index as a workaround:

```
chunked = torch.chunk(x, 3)
torch.cat(tuple(chunked[i] for i in range(3)))
```

Otherwise, this program is dynamic and fundamentally not traceable

**Comment by jamesr66a** [comment] 2021-01-07 00:32
Closing as this is working as intended. We can make a follow-up to discuss informing the system about static chunking

**Closed by jamesr66a** 2021-01-07 00:32 UTC
Labels: fx
