### ISSUE TITLE
mps bug: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (6) is not less than length of dimension[0] (6)'

### ISSUE THREAD

**Issue by hchau630** [pytorch/pytorch#96153] opened 2023-03-07 00:07 UTC
### 🐛 Describe the bug

I got a bug that looks similar to #95883 that is just closed. Not sure if it's the same. I'm running on the latest nightly version.

Code:
```python
import torch

t = torch.ones((2,6,), device='mps')[1].reshape(2,3)
print("No error yet")
t = t + 1
```

Output:
```
No error yet
/AppleInternal/Library/BuildRoots/a0876c02-1788-11ed-b9c4-96898e02b808/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:82: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (6) is not less than length of dimension[0] (6)'
zsh: abort      python test/torch_mps_test.py
```

Interesting, if I change the code to
```
import torch

t = torch.ones((2,6,), device='mps')[1].reshape(3,2)
print("No error yet")
t = t + 1
```
then there is no error.

### Versions

```
Collecting environment information...
PyTorch version: 2.1.0.dev20230306
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.6.3 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.16 (main, Mar  1 2023, 12:19:04)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-12.6.3-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.2
[pip3] torch==2.1.0.dev20230306
[pip3] torchdiffeq==0.2.3
[conda] numpy                     1.24.2                   pypi_0    pypi
[conda] torch                     2.1.0.dev20230306          pypi_0    pypi
[conda] torchdiffeq               0.2.3                    pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment] 2023-03-07 02:35
Please note, that this is a regression from 1.13.0:
```
% python -c "import torch;print(torch.__version__);t=torch.ones(2,6,device='mps')[1].reshape(2, 3); t = t+1; print(t)"
1.13.0
tensor([[2., 2., 2.],
        [2., 2., 2.]], device='mps:0')

```

**Comment by brkirch** [comment] 2023-03-12 08:08
I've observed a similar crash also after slicing using `torch.narrow()`, but I don't have minimal code to reproduce and haven't isolated exactly what in [this code](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/master/modules/sub_quadratic_attention.py) causes it. The workaround I've been using is to clone the tensor after slicing (not shown in the code I linked to), which also prevents the crash in @hchau630's example:
```python
import torch

t = torch.ones((2,6,), device='mps')[1].clone().reshape(2,3)
print("No error yet")
t = t + 1
```

**Comment by hchau630** [comment] 2023-03-17 07:35
Is there any progress on this? I tested on torch 2.0.0 and this bug still happens. It seems like a pretty critical bug that will impact a lot of people since all it involves is indexing and reshaping.

**Comment by kulinseth** [comment] 2023-03-17 14:07
@hchau630 yes , we are looking into it .

**Comment by DronHazra** [comment] 2023-05-02 10:52
any update on this? i'm having this issue on the latest nightly build as well.

**Comment by Engineero** [comment] 2023-06-26 22:22
I am seeing the same error in 2.0.1:

```
❯ python -c "import torch;print(torch.__version__);t=torch.ones(2,6,device='mps')[1].reshape(2, 3); t = t+1; print(t)"
2.0.1
/AppleInternal/Library/BuildRoots/2acced82-df86-11ed-9b95-428477786501/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:84: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (6) is not less than length of dimension[0] (6)'
[1]    18858 abort      python -c
```

This is affecting me in a more complicated project where tracking down what specific operation(s) cause the issue is proving just about impossible.

**Comment by matteocitterio** [comment] 2023-10-27 08:15
same error in 2.2.0:
`>python -c "import torch;print(torch.__version__);t=torch.ones(2,6,device='mps')[1].reshape(2, 3); t = t+1; print(t)"`
2.2.0.dev20231025
/AppleInternal/Library/BuildRoots/9941690d-bcf7-11ed-a645-863efbbaf80d/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:84: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (6) is not less than length of dimension[0] (6)'
zsh: abort      python -c

**Comment by kulinseth** [comment] 2024-04-16 22:44
This is still reproducing with latest Nightly

**Comment by FedeMorenoOptima** [comment] 2024-04-18 13:30
Good morning! Any update on this bug?

**Comment by QuanyiLi** [comment] 2024-05-07 12:39
Any update? same issue..

**Comment by DenisVieriu97** [comment] 2024-05-08 01:33
Hi @QuanyiLi - a fix was just merged in couple minutes ago. Next nightly version should pick up this fix and issue should be gone. Please let me know if you still see any issues.

**Comment by QuanyiLi** [comment] 2024-05-08 09:45
Thank you. It persists. Seems my problem is another one, it is raised at line 120 of `MPSNDArray.mm`: `MPSNDArray.mm:120: failed assertion [MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (288) is not less than length of dimension[1] (276)`

I will file an issue for this and try to give you a minimal script to reproduce it..

**Comment by DenisVieriu97** [comment] 2024-05-08 17:21
Thanks @QuanyiLi for trying it out. 
Could you please share the nightly you are using? I've just downloaded latest nightly and this one contains the change:
```
$ pip list | grep torch
torch                        2.4.0.dev20240430
```
I've used following to upgrade:
```
 pip3 install --pre --upgrade torch --index-url https://download.pytorch.org/whl/nightly/cpu
```

With older pytorch I am seeing same crash as yours:
```
MPSNDArray.mm:124: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (6) is not less than length of dimension[0] (6)'
```
Latest one is running fine for me for above example:
```
$ python3 script.py
No error yet
tensor([[2., 2., 2.],
        [2., 2., 2.]], device='mps:0')
```

If you still see the crash, please let me know if you have a small repro case that I could use. Thanks!

**Comment by QuanyiLi** [comment] 2024-05-09 01:46
Hi @DenisVieriu97,

Thank you for your help. I reinstalled the nightly build version and yes, this bug is fixed for my code. However, I got a new error at exactly the same line where I do `torch.baddbmm`:
```RuntimeError: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm":387, please report a bug to PyTorch. Placeholder tensor is empty!```

**Comment by shink** [comment] 2024-05-09 03:42
I got the same error when running this test:

```bash
python test/test_mps.py
```

```
........./opt/anaconda3/envs/pth/lib/python3.11/site-packages/torch/nn/functional.py:4539: UserWarning: MPS: The constant padding of more than 3 dimensions is not currently supported natively. It uses View Ops default implementation to run. This may have performance implications. (Triggered internally at /Users/shenke/workspace/pytorch/aten/src/ATen/native/mps/operations/Pad.mm:472.)
  return torch._C._nn.pad(input, pad, mode, value)
........F......./Users/shenke/workspace/pytorch/test/test_mps.py:9859: UserWarning: The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at /Users/shenke/workspace/pytorch/aten/src/ATen/native/TensorShape.cpp:3689.)
  t1 = a.T
./Users/shenke/workspace/pytorch/test/test_mps.py:9229: UserWarning: TypedStorage is deprecated. It will be removed in the future and UntypedStorage will be the only storage class. This should only matter to you if you are using storages directly.  To access UntypedStorage directly, use tensor.untyped_storage() instead of tensor.storage()
  if base.storage().data_ptr() != other.storage().data_ptr():
...................../AppleInternal/Library/BuildRoots/ce725a5f-c761-11ee-a4ec-b6ef2fd8d87b/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:124: failed assertion `[MPSNDArrayDescriptor sliceDimension:withSubrange:] error: subRange.start (6) is not less than length of dimension[0] (6)'
[1]    55309 abort      python test/test_mps.py
```

**Comment by malfet** [comment] 2024-05-09 14:37
> Hi @DenisVieriu97,
> 
> Thank you for your help. I reinstalled the nightly build version and yes, this bug is fixed for my code. However, I got a new error at exactly the same line where I do `torch.baddbmm`: `RuntimeError: [srcBuf length] > 0 INTERNAL ASSERT FAILED at "/Users/runner/work/pytorch/pytorch/pytorch/aten/src/ATen/native/mps/OperationUtils.mm":387, please report a bug to PyTorch. Placeholder tensor is empty!`

@QuanyiLi can you share an example code that triggers that with `torch.baddbmm`?

**Comment by kulinseth** [comment] 2024-08-27 20:35
No activity on the issue.

**Closed by kulinseth** 2024-08-27 20:35 UTC
Labels: high priority, triaged, module: regression, module: viewing and reshaping, module: mps
