### ISSUE TITLE
why libtorch is slower than caffe

### ISSUE THREAD

**Issue by XSeanLiu** [pytorch/pytorch#25009] opened 2019-08-22 04:36 UTC
### gpu memory: 1079M libtorch vs. 581M caffe

so I want to know anyone has the same situation?

is my libtorch configure wrong?
any suggestion to run libtorch correctly?

my gcc version is gcc 6.5

**Comment by andreaskoepf** [comment] 2019-08-22 10:19
dupe of #19563 ? If you want to report a bug please use the issue template (e.g. it is unclear what model you use, how to reproduce the problem, pytorch, cuda version and hardware you have on your server. Do you run the benchmarks on the same machine etc.).

**Comment by XSeanLiu** [comment] 2019-08-22 13:33
> dupe of #19563 ? If you want to report a bug please use the issue template (e.g. it is unclear what model you use, how to reproduce the problem, pytorch, cuda version and hardware you have on your server. Do you run the benchmarks on the same machine etc.).

@andreaskoepf  thanks very much, I have found this issue #19563 , but I think may be difference.

we have designed a nn with the backbone of senet.

the system is centos 7.4, with gcc 6.5 and cuda 10.0 with cudnn 7.5.1, and the pytorch is 1.2.0

I think you can train a pytorch with the backbone of senet, and then find an caffe prototxt of senet, and then convert this pytorch model file to caffemodel and libtorch model. so you can run it on your system with inference codes.

Note that, we just compute the forward time, which we found pytorch data preprocess cost much more time than pytorch forward time, also much more than caffe.

Also we find the pytorch gpu memory is more than caffe. so maybe wei didnot set a right configure, so I hope any body can help me with right code or right configure

**Comment by XSeanLiu** [comment] 2019-08-29 10:02
Any body can give me a help or a reason?

**Comment by soumith** [comment] 2019-09-06 01:50
@XSeanLiu the reason could be many things under the sun, especially because there are CUDA version, CuDNN version etc. that are involved. Try running under nvprof or similar utilities to get insights as to what is going on.
If as you mention data preprocess time is costing much more in pytorch than in caffe, then maybe you can switch to a different underlying library for preprocessing (caffe uses opencv, pytorch by default uses PIL).

**Closed by soumith** 2019-09-06 01:50 UTC
Labels: topic: performance, triaged
