### ISSUE TITLE
Unreasonable memory usage for hello world example

### ISSUE THREAD

**Issue by cowwoc** [pytorch/pytorch#64720] opened 2021-09-09 01:32 UTC
sleep(1000)
## To Reproduce

Given:

```
from time import sleep
import torch

def main():
    print("Hello world")
    sleep(1000)

if __name__ == "__main__":
    main()
```

When running against the CPU-only version of the library:

```
PyTorch version: 1.9.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3080
Nvidia driver version: 461.37
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.4.5
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.10.0
[conda] Could not collect
```

I get a process commit size of 603MB. When running against the CUDA 11.1 version of the library:

```
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 3080
Nvidia driver version: 461.37
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] pytorch-lightning==1.4.5
[pip3] torch==1.9.0+cu111
[pip3] torchaudio==0.9.0
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.10.0+cu111
[conda] Could not collect
```

I get a process commit size of 4985MB.

The fact that the minimum commit size is so large is a problem because when run multiple worker processes the commit size balloons to 20GB-40GB per run, even if I never trigger GPU usage. I am expecting the commit size to be much smaller, ideally so that I can run 8-16 worker processes on a machine with 32GB of virtual memory.

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by cowwoc** [comment] 2021-09-09 01:44
For the record, my machine has 64MB of RAM and an initial commit size of ~74GB. I don't know if these numbers influence the size of the commit size per process, but I thought it would be worth mentioning.

**Comment by alexeygolyshev** [comment] 2021-09-09 08:15
```
import os

import psutil


def main() -> None:
    print(psutil.Process(os.getpid()).memory_info())
    
    import torch
    
    print(torch.__version__)
    
    print(psutil.Process(os.getpid()).memory_info())


if __name__ == '__main__':
    main()
    
```

**CPU (conda install pytorch cpuonly -c pytorch)**:
pmem(rss=13918208, vms=7163904, num_page_faults=3520, peak_wset=13922304, wset=13918208, peak_paged_pool=154304, paged_pool=154128, peak_nonpaged_pool=13440, nonpaged_pool=13440, pagefile=7163904, peak_pagefile=7163904, private=7163904)
1.9.0
pmem(rss=104108032, vms=98508800, num_page_faults=25683, peak_wset=104112128, wset=104108032, peak_paged_pool=1103488, paged_pool=1103408, peak_nonpaged_pool=35480, nonpaged_pool=35336, pagefile=98508800, peak_pagefile=98508800, private=98508800)

**GPU:**
pmem(rss=14471168, vms=7581696, num_page_faults=3651, peak_wset=14475264, wset=14471168, peak_paged_pool=154304, paged_pool=154128, peak_nonpaged_pool=13576, nonpaged_pool=13576, pagefile=7581696, peak_pagefile=7581696, private=7581696)
1.9.0
pmem(rss=156160000, vms=4222533632, num_page_faults=38539, peak_wset=156164096, wset=156160000, peak_paged_pool=9825952, paged_pool=9825856, peak_nonpaged_pool=46904, nonpaged_pool=46760, pagefile=4222533632, peak_pagefile=4222533632, private=4222533632)

**Comment by cowwoc** [comment] 2021-09-09 13:38
@alexeygolyshev So if I understand you correctly, you are able to reproduce the problem on your end. Is that correct?

**Comment by alexeygolyshev** [comment] 2021-09-09 14:04
Hello @cowwoc ! Yes, I can see a huge difference in `vms`. But I am not sure if this is critical or not.
https://stackoverflow.com/questions/59160903/what-uses-the-memory-of-my-python-process-rss-vs-vms

**Comment by cowwoc** [comment] 2021-09-09 14:19
I understand but here is some context on why this can be problematic: https://github.com/PyTorchLightning/pytorch-lightning/issues/9390

Granted, pytorch lightning should be more proactive in trying to free this memory but the fact that memory usage is so high coupled with multiple worker processes coupled with multiple Optuna trials makes this a very annoying problem.

**Comment by cowwoc** [comment] 2021-09-09 14:22
Also, I believe `vms` maps to "commit size" in Windows and the latter issues an out of memory error when you max out virtual memory even if there is plenty physical memory available. For example, I've got 64GB in my computer, only 32GB is actually in use, but Windows issues out of memory to python when the amount of committed memory surpasses ~120GB.

**Comment by albanD** [comment] 2021-09-09 14:30
Hi,

If you do any cuda op like (torch.rand(1, device="cuda")` does that jump again?

**Comment by alexeygolyshev** [comment] 2021-09-09 14:33
Hello @albanD ! Yes, it will jump again.

**Comment by alexeygolyshev** [comment] 2021-09-09 14:36
> Windows issues out of memory to python when the amount of committed memory surpasses ~120GB. When the virtual memory maxes out I still have 32GB of physical memory showing up as "available" in task manager.

Yes, I can confirm this.

`OSError: [WinError 1455] The paging file is too small for this operation to complete. Error loading "C:\Anaconda3\envs\torch19\lib\site-packages\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.`

![Untitled](https://user-images.githubusercontent.com/6998329/132705976-d3ced806-16ee-481c-978a-6e28dc1db90d.png)

**Comment by albanD** [comment] 2021-09-09 14:55
I'm afraid the answer is just the sheer amount of cuda code that we have and the way cuda distribution works.
The latest windows binary [here](https://download.pytorch.org/whl/nightly/cu111/torch-1.10.0.dev20210909%2Bcu111-cp38-cp38-win_amd64.whl) is 3GB+ which matches with the memory usage you see.

A binary compiled only for your GPU architecture should be smaller if that is really a big problem. But you will have to compile from source

**Comment by cowwoc** [comment] 2021-09-09 17:31
@albanD How does TensorFlow handle this problem? From what I've read in other tickets, their memory usage remains low.

**Comment by peterjc123** [comment] 2021-09-10 01:22
I guess lazy loading the libs should be the key to your problem here.

**Comment by cowwoc** [comment] 2021-09-10 01:26
@peterjc123 I'm not sure what lazy loading the libs would look like in this case. Is there an example I could look at?

**Comment by albanD** [comment] 2021-09-10 14:51
But lazy loading won't really solve the problem because all of these would eventually call into cuda and so load the whole thing in memory no?

**Comment by peterjc123** [comment] 2021-09-11 04:56
@albanD I guess it will do, especially when using dataloader, since the data in the child processes usually doesn't go to GPU.

**Comment by albanD** [comment] 2021-09-13 15:42
I guess.
My idea was that the use of pinned memory does trigger the cuda runtime init and so you actually initialize cuda on your workers.
But maybe not!

**Comment by arquolo** [comment] 2022-05-28 13:15
Problem is still persist on 1.11 too. And this issue is duplicate for [#38645](https://github.com/pytorch/pytorch/issues/38645).

**Comment by albanD** [comment] 2022-05-31 19:55
To keep all discussions in one place, closing in favor of https://github.com/pytorch/pytorch/issues/12873

**Closed by albanD** 2022-05-31 19:55 UTC
Labels: module: windows, module: memory usage, triaged
