### ISSUE TITLE
torch.matmul should have the same error report in the two cases of using cpu and using cuda

### ISSUE THREAD

**Issue by ilovepytorch** [pytorch/pytorch#65399] opened 2021-09-21 11:59 UTC
## 🐛 Bug

In the case of only using cpu, `torch.matmul` will report an error. But when using cuda, no error will be reported.

## To Reproduce

Only using cpu:
```python
import torch
arg_0 = torch.rand(torch.Size([16, 264, 32, 32]), dtype=torch.float32)
arg_1 = torch.rand(torch.Size([20, 2048]), dtype=torch.float32)
res = torch.matmul(arg_0,arg_1,)
```
Error report:
```
RuntimeError: mat1 and mat2 shapes cannot be multiplied (135168x32 and 20x2048)
```

Enabling cuda:
```python
import torch
arg_0 = torch.rand(torch.Size([16, 264, 32, 32]), dtype=torch.float32).cuda()
arg_1 = torch.rand(torch.Size([20, 2048]), dtype=torch.float32).cuda()
res = torch.matmul(arg_0,arg_1,)
```
No error report.

## Expected behavior

Cpu and cuda should have the same error report.

## Environment

 - PyTorch Version (e.g., 1.0): 1.9.0
 - OS (e.g., Linux): Ubuntu
 - Python version: 3.6.9
 - CUDA/cuDNN version: cuDNN 11.1
 - GPU models and configuration: RTX3090

## Additional context

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @brianjo

**Comment by malfet** [comment] 2021-09-21 15:02
Closing as duplicate of https://github.com/pytorch/pytorch/issues/61291

**Closed by malfet** 2021-09-21 15:02 UTC
Labels: triaged, module: linear algebra

**Comment by triumph-wangyuyang** [comment] 2022-11-19 07:07
pytorch: 1.8.0
Python version: 3.8
CUDA/cuDNN version: cuDNN 11.1
GPU models and configuration: RTX3060
