### ISSUE TITLE
Torch.compile not working with python 3.12 on windows

### ISSUE THREAD

**Issue by JINO-ROHIT** [pytorch/pytorch#136361] opened 2024-09-20 15:27 UTC
### Error logs

RuntimeError: Cannot find a working triton installation. Either the package is not installed or it is too old. More information on installing Triton can be found at https://github.com/openai/triton

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information

You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

### Versions

torch==2.6.0.dev20240919+cu124

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @ezyang @chauhang @penguinwu

**Comment by malfet** [comment] 2024-09-20 16:11
This is an expected behavior, as there are no Triton for Windows yet.

**Comment by malfet** [comment] 2024-09-20 16:13
Closing as duplicate of https://github.com/pytorch/pytorch/issues/90768

**Closed by malfet** 2024-09-20 16:13 UTC
Labels: module: windows, oncall: pt2
