### ISSUE TITLE
`kthvalue()` with an empty 1D tensor and `k=1` still gets the same error even if setting `dim=0` to it

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130134] opened 2024-07-05 01:25 UTC
### 🐛 Describe the bug

[kthvalue()](https://pytorch.org/docs/stable/generated/torch.kthvalue.html) with an empty 1D tensor and `k=1` gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.kthvalue(input=my_tensor, k=1) # Error
```

> IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.

So, I set `dim=0` to `kthvalue()` following the error message above but it still gets the same error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.kthvalue(input=my_tensor, k=1, dim=0) # Error
```

> IndexError: kthvalue(): Expected reduction dim 0 to have non-zero size.

In addition, `kthvalue()` with an empty 2D or 3D  tensor and `k=1` also gets the errors respectively as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.kthvalue(input=my_tensor, k=1) # Error

my_tensor = torch.tensor([[[]]])

torch.kthvalue(input=my_tensor, k=1) # Error
```

> IndexError: kthvalue(): Expected reduction dim 1 to have non-zero size.

> IndexError: kthvalue(): Expected reduction dim 2 to have non-zero size.

But setting `dim=0` to `kthvalue()` following the error messages above works properly as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.kthvalue(input=my_tensor, k=1, dim=0)
# torch.return_types.kthvalue(
# values=tensor([]),
# indices=tensor([], dtype=torch.int64))

my_tensor = torch.tensor([[[]]])

torch.kthvalue(input=my_tensor, k=1, dim=0)
# torch.return_types.kthvalue(
# values=tensor([], size=(1, 0)),
# indices=tensor([], size=(1, 0), dtype=torch.int64))
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by albanD** [comment] 2024-07-08 14:47
Near duplicate of https://github.com/pytorch/pytorch/issues/130187
Let's continue discussion there since they have the same behavior

**Closed by albanD** 2024-07-08 14:47 UTC
