### ISSUE TITLE
[BUG] c10d in torch.distributed.init_process_group() will not work without ipv6

### ISSUE THREAD

**Issue by Qubitium** [pytorch/pytorch#121807] opened 2024-03-13 13:01 UTC
### 🐛 Describe the bug

Very strange issue. c10d in torch.distributed will launch a socket on ipv6 even if provided init_method is ipv4 link. Setting env MASTER_ADDR and MASTER_PORT to ipv4 address (not 127.0.0.1) will throw:

```
W socket.cpp:697] [c10d] The IPv6 network addresses of ( 10.0.5.4, 8004) cannot be retrieved (gai error: -2 - Name or service not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of ( 10.0.5.4, 8004) cannot be retrieved (gai error: -2 - Name or service not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of ( 10.0.5.4, 8004) cannot be retrieved (gai error: -2 - Name or service not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of ( 10.0.5.4, 8004) cannot be retrieved (gai error: -2 - Name or service not known).
[W socket.cpp:697] [c10d] The IPv6 network addresses of ( 10.0.5.4, 8004) cannot be retrieved (gai error: -2 - Name or service not known).
````

The above error/warning, will loop and process never starts, shows even if given a system local ipv4 address, torch.distributed process will error due to ipv6 checks. This should not happen. I have given it an ipv4 address but why does the error show it wants to resolve it to ipv6?

Offending code is:

```
torch.distributed.init_process_group(
    backend="nccl",
    world_size=self.tp_size,
    rank=self.tp_rank,
    # commenting out below and using env MASTER_ADDR and MASTER_PORT also doesn't work
    init_method=f"tcp://10.0.5.4:8004",
)

```

OR

```
os.environ["MASTER_ADDR"] = "10.0.5.4"
os.environ["MASTER_PORT"] = "8004"

torch.distributed.init_process_group(
    backend="nccl",
    world_size=self.tp_size,
    rank=self.tp_rank,
)
```

```
# eth0 with the ipv4 ip
5: eth0@if6: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000    link/ether 00:16:3e:c5:13:10 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.0.5.4/24 metric 100 brd 10.0.5.255 scope global dynamic eth0
       valid_lft 3389sec preferred_lft 3389sec
```

Setting env NCCL_SOCKET_IFNAME=eth0 doesn't help.

### Versions

torch: 2.2.0
os: ubuntu 22.04
python: 3.11.8

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225 @chauhang @d4l3k @rohan-varma @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519

**Comment by tringwald** [comment] 2024-03-16 19:00
Are you running this inside of a Docker container? I remember there being problems with `--network=host`.

**Comment by Qubitium** [comment] 2024-03-16 22:08
@tringwald Not docker bur lxd container

**Comment by tringwald** [comment] 2024-03-17 12:32
I can reproduce this problem when adding a space in front of the IP addr: 

```python3
os.environ["MASTER_ADDR"] = " 10.0.5.4"
#                            ^
```

This space also seems to be present in the error message:
```
W socket.cpp:697] [c10d] The IPv6 network addresses of ( 10.0.5.4, 8004) ...
                                                        ^
```

It seems like the IP is then interpreted as a domain and resolving that throws the error.

**Comment by Qubitium** [comment] 2024-06-06 03:22
@c-p-i-o @tringwald Sorry for the delay. If memory serves me correct, I believe the it was indeed caused by a space prefix in setting the env ip var.

**Comment by c-p-i-o** [comment] 2024-06-07 22:23
No worries! I'll close this issue out for now. Feel free to re-open the issue if the issue still exists.

**Closed by c-p-i-o** 2024-06-07 22:23 UTC
Labels: oncall: distributed, triaged
