### ISSUE TITLE
[c10d] collective failure with single-device style (#119421) and nccl <= 2.12

### ISSUE THREAD

**Issue by oraluben** [pytorch/pytorch#130414] opened 2024-07-10 04:12 UTC
### 🐛 Describe the bug

The issue need to be reproduced with at least two gpus.

This is a regression in 2.3. After #119421, the following code no longer works with nccl 2.12.10 (nccl 2.13 works)

`torchrun --nproc-per-node=2 demo.py`

```
import torch
import torch.distributed as dist


if __name__ == '__main__':
    dist.init_process_group("nccl", init_method='env://')

    # rank = dist.get_rank()
    # local_rank = rank % torch.cuda.device_count()
    # torch.set_default_device(f"cuda:{local_rank}")
    # torch.cuda.set_device(local_rank)

    dist.barrier()
```

output:
```
iZmj7cfy2ysqwfo0nrci4pZ:2532579:2532579 [0] enqueue.cc:336 NCCL WARN Cuda failure 'invalid resource handle'
iZmj7cfy2ysqwfo0nrci4pZ:2532579:2532579 [0] NCCL INFO enqueue.cc:1382 -> 1
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/yyc/dist.py", line 45, in <module>
[rank1]:     main()
[rank1]:   File "/home/yyc/dist.py", line 40, in main
[rank1]:     dist_allreduce()
[rank1]:   File "/home/yyc/dist.py", line 18, in dist_allreduce
[rank1]:     dist.barrier()
[rank1]:   File "/home/yyc/repo/pytorch/torch/distributed/c10d_logger.py", line 79, in wrapper
[rank1]:     return func(*args, **kwargs)
[rank1]:   File "/home/yyc/repo/pytorch/torch/distributed/distributed_c10d.py", line 3936, in barrier
[rank1]:     work = default_pg.barrier(opts=opts)
[rank1]: torch.distributed.DistBackendError: NCCL error in: /home/yyc/repo/pytorch/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:2612, unhandled cuda error, NCCL version 2.12.12
[rank1]: ncclUnhandledCudaError: Call to CUDA function failed.
```

If change the code to explicit call `torch.cuda.set_device(local_rank)`, it works again.
I looked around but didn't find a nccl support policy, since both 2.2 and 2.3 compile and work well with nccl 2.12, I assume it is not out of date.

This issue can be reproduced with 2.3.1 release and same nccl version, also 2.4 branch with #130419.

I'm not familiar with nccl,
@eqy @kwen2501 maybe you know more about what happens here?

### Versions

Collecting environment information...
PyTorch version: 2.3.0a0+gitb2043c0
Is debug build: False
CUDA used to build PyTorch: 12.5
ROCM used to build PyTorch: N/A

OS: Alibaba Cloud Linux release 3 (Soaring Falcon)  (x86_64)
GCC version: (GCC) 12.2.1 20221121 (Red Hat 12.2.1-7)
Clang version: Could not collect
CMake version: version 3.26.5
Libc version: glibc-2.32

Python version: 3.10.14 (main, May  6 2024, 19:42:50) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.10.134-16.3.al8.x86_64-x86_64-with-glibc2.32
Is CUDA available: True
CUDA runtime version: 12.5.40
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA A10
GPU 1: NVIDIA A10

Nvidia driver version: 550.54.15
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.9.1.1
/usr/lib64/libcudnn_adv.so.9.1.1
/usr/lib64/libcudnn_cnn.so.9.1.1
/usr/lib64/libcudnn_engines_precompiled.so.9.1.1
/usr/lib64/libcudnn_engines_runtime_compiled.so.9.1.1
/usr/lib64/libcudnn_graph.so.9.1.1
/usr/lib64/libcudnn_heuristic.so.9.1.1
/usr/lib64/libcudnn_ops.so.9.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              64
On-line CPU(s) list: 0-63
Thread(s) per core:  2
Core(s) per socket:  32
Socket(s):           1
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               106
Model name:          Intel(R) Xeon(R) Platinum 8369B CPU @ 2.90GHz
Stepping:            6
CPU MHz:             2900.000
BogoMIPS:            5800.00
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           48K
L1i cache:           32K
L2 cache:            1280K
L3 cache:            49152K
NUMA node0 CPU(s):   0-63
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq monitor ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves wbnoinvd arat avx512vbmi avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid fsrm arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.12.1
[pip3] torch==2.3.0a0+gitb2043c0
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.12.1                   pypi_0    pypi
[conda] torch                     2.3.0a0+gitb2043c0           dev_0    <develop>

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @fegin @XilunWu @wanchaol @fduwjj @wz337 @wconstab @chauhang @d4l3k

**Comment by eqy** [comment] 2024-07-10 05:12
Looks like you're on 2.30, this should probably be fixed in #129908 which is in the nightlies.

**Comment by oraluben** [comment] 2024-07-10 05:13
> Looks like you're on 2.3.0, this should probably be fixed in #129908 which is in the nightlies.

Thanks for quick reply! I also see that, but cherry pick that onto 2.3 do not solve this.

**Comment by oraluben** [comment] 2024-07-10 07:37
And this issue does not affect `barrier` only, but all collective op.

A not minimized reproducer:
```
import logging
import torch
import torch.distributed as dist


def print_rank_0(msg, *args, **kwargs):
    rank = dist.get_rank()
    if rank == 0:
        logging.info(msg, *args, **kwargs)


def dist_allreduce():
    print_rank_0("all_reduce:")
    print(torch.get_default_device())

    rank = dist.get_rank()

    dist.barrier()

    tensor = torch.tensor(rank)
    input_tensor = tensor.clone()
    print(input_tensor)
    dist.all_reduce(tensor)

    logging.info(
        f"all reduce, rank: {rank}, before allreduce tensor: {repr(input_tensor)}, after allreduce tensor: {repr(tensor)}")
    dist.barrier()
    print(torch.cuda.current_device())


def main():
    dist.init_process_group("nccl", init_method='env://')

    rank = dist.get_rank()
    local_rank = rank % torch.cuda.device_count()
    torch.set_default_device(f"cuda:{local_rank}")

    print(torch.cuda.current_device())
    # torch.cuda.set_device(local_rank)
    dist_allreduce()


if __name__ == '__main__':
    logging.basicConfig(format=logging.BASIC_FORMAT, level=logging.INFO)
    main()
```

**Comment by LucasLLC** [comment] 2024-07-15 21:33
@oraluben , I think in general our recommendation is to always call `set_cuda_device` before calling collectives. Barrier's specifically depend on Tensor initialization so it makes sense to me that this is failing. 

That being said we should double check that the warning is still being properly generated, since if this wasn't broken before it counts as a regression.

cc @H-Huang who offered to take a look at this

**Comment by oraluben** [comment] 2024-07-17 10:11
> @oraluben , I think in general our recommendation is to always call `set_cuda_device` before calling collectives.

I agree. There is an warning deeply hidden, and you need `TORCH_CPP_LOG_LEVEL=INFO` to see:

https://github.com/pytorch/pytorch/blob/2300bb2a88081722ca4a4d52db16caabe5d33eeb/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L3915-L3922

Since torch intentionally warn this and later tries to set correct device, this issue looks more like a bug/regression rather than an ub to me.

I've created #130921 for a possible fix.

**Closed** 2024-09-20 13:41 UTC
Labels: high priority, triage review, oncall: distributed, module: regression
