### ISSUE TITLE
exporting with symbolic tracing mode fails on trivial model

### ISSUE THREAD

**Issue by suo** [pytorch/pytorch#91720] opened 2023-01-04 19:45 UTC
```
import torch

torch._dynamo.config.dynamic_shapes = True

class MyModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.my_param = torch.nn.Parameter(torch.randn([2, 3]))

    def forward(self, x):
        return x + self.my_param

m = MyModule()

torch._dynamo.export(m, torch.randn([2,3]), aten_graph=True, tracing_mode="symbolic")
```
raises an error:
```
Please convert all Tensors to FakeTensors first or instantiate FakeTensorMode with 'allow_non_fake_inputs'. 
Found in aten.add.Tensor(*(FakeTensor(FakeTensor(..., device='meta', size=(s0, s1)), cpu), Parameter containing:
tensor([[-2.3525e+00, -9.1233e-01,  2.8815e-02],
        [-2.1475e-03,  7.7734e-01, -4.0085e-01]], requires_grad=True)), **{}) 
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by suo** [comment] 2023-01-04 20:21
@tugsbayasgalan  suggested that I change the call to `make_fx` in `export` to have the flag `_allow_non_fake_inputs=True`. 

While this gets rid of the error, the computed shapes are not what I expect. Here is the graph for the above module:
```
class GraphModule(torch.nn.Module):
    def forward(self, orig_arg_0):
        arg0: f32[2, 3], = fx_pytree.tree_flatten_spec([orig_arg_0], self._in_spec)
        _param_constant0 = self._param_constant0
        add_tensor = torch.ops.aten.add.Tensor(arg0, _param_constant0);  arg0 = _param_constant0 = None
        return pytree.tree_unflatten([add_tensor], self._out_spec)
```

As you can see, I have a concrete `[2, 3]` shape for the input, which is not what I would expect out of dynamic shapes mode. 

If I change the forward function to be `x + x`, I see the expected symbolic shape annotation:

```
class GraphModule(torch.nn.Module):
    def forward(self, orig_arg_0):
        arg0: f32[s0, s1], = fx_pytree.tree_flatten_spec([orig_arg_0], self._in_spec)
        add_tensor = torch.ops.aten.add.Tensor(arg0, arg0);  arg0 = None
        return pytree.tree_unflatten([add_tensor], self._out_spec)
```

**Comment by ngimel** [comment] 2023-01-04 21:17
That's because parameters are assumed constant size, and `x + param` propagates those constraints to `x` too (note that addition is traced as non-broadcasting because your concrete input results in non-broadcasting addition).

**Comment by thiagocrepaldi** [comment] 2023-04-28 20:43
@ngimel is there any fix/workaround?

**Comment by ngimel** [comment] 2023-04-28 21:09
That's intended behavior, parameters are assumed to be constant size

**Comment by thiagocrepaldi** [comment] 2023-04-28 21:13
Thanks, it was my ba. forgot to add the dynamic batch dimension on input, so only the constant part of input was present

should we close this issue then?

**Closed** 2023-04-28 21:27 UTC
Labels: triaged, oncall: pt2, module: dynamic shapes
