### ISSUE TITLE
`Segmentaion Fault` while function return.

### ISSUE THREAD

**Issue by HanwGeek** [pytorch/pytorch#35756] opened 2020-03-31 12:59 UTC
## 🐛 Bug
When I train a seq2seq model for data embedding, it crash after I calculate the similarity matrix at a certain probability. I get the result **successfully** but it occurs a `segmentation fault` where the train function return.It seems to be a memory problem, but my memory is 16GB and CUDA is 4GB. The size of dataset is only couple of KBs.

## To Reproduce

1. Define a function
1. Generate a matrix `A` in a shape of `N x 256`
1. Calc a matrix `B` of `N x N`. `B[i][j] = torch.dot(A[i], A[j])`
1. When function return it crash

With `faulthandler`, the log is
```shell
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff7161bbc in _int_malloc (
    av=av@entry=0x7ffff74a4b20 <main_arena>, 
    bytes=bytes@entry=16) at malloc.c:3353
3353	malloc.c: No such file or directory.
```
The size of matrix is about `700 x 256`
## Environment
- PyTorch version: N/A
- Is debug build: N/A
- CUDA used to build PyTorch: N/A

- OS: Ubuntu 16.04.6 LTS
- GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
- CMake version: version 3.5.1

- Python version: 2.7
- Is CUDA available: N/A
- CUDA runtime version: 10.1.105
- GPU models and configuration: GPU 0: GeForce GTX 960M
- Nvidia driver version: 440.64
- cuDNN version: Could not collect

Versions of relevant libraries:
- [pip] numpy==1.14.5
- [pip] torch==1.4.0
- [pip] torchvision==0.5.0
- [conda] Could not collect

**Comment by vincentqb** [comment] 2020-03-31 20:51
Can you provide a full example to reproduce the error? I am unable to reproduce.

```python
def func():
  for i in range(N):
    for j in range(N):
      B[i][j] = torch.dot(A[i], A[j])

func()

# successful
```

Does this do the same as what you are trying to do?
```python
N = 100
A = torch.rand(N, 256)
B = A.matmul(A.T)

B.shape
# N x N
```

**Comment by HanwGeek** [comment] 2020-04-01 03:17
@vincentqb In fact, it will crash on a certain condition. But now I cannot determine what's the cause of this problem. For now, It will happen when the size of dataset tensor grows to about `20 x 1200`. And the function got a right result with a `seg fault` while function return. So is there any method to back trace the crash?

**Comment by vincentqb** [comment] 2020-04-01 17:07
Glad to know you were able to proceed. Since we cannot reproduce this error, I will close this issue. Please feel free to re-open.

**Closed by vincentqb** 2020-04-01 17:07 UTC
Labels: topic: crash, triaged
