### ISSUE TITLE
ONNX export does not support parallel model converted using nn.DataParallel(model) and will throw error message "untraced buffer"

### ISSUE THREAD

**Issue by xiaoyongzhu** [pytorch/pytorch#5315] opened 2018-02-20 19:18 UTC
Looks like ONNX support does not support dataparallel models (in particular, model that is converted after nn.DataParallel(model).

Here is a simple piece of code to repro the issue:
```
import os
import sys
import numpy as np
import pandas as pd
import torch
import torchvision.models as models
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import torch.nn.init as init
import time
from torch.optim.lr_scheduler import ReduceLROnPlateau
from torch.autograd import Variable
import torchvision.transforms as transforms
from torch.utils.data import DataLoader, Dataset
from sklearn.metrics.ranking import roc_auc_score
from sklearn.model_selection import train_test_split
from PIL import Image
import multiprocessing

model = models.densenet.densenet121(pretrained=True)
model = nn.DataParallel(model)
dummy_input = Variable(torch.randn(10, 3, 224, 224)).cuda()
model = model.cuda()
torch.onnx.export(model, dummy_input, "test.onnx", verbose=False, export_params=True)
```
The error message is:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-514806a4333a> in <module>()
    386 dummy_input = Variable(torch.randn(10, 3, 224, 224)).cuda()
    387 model = model.cuda()
--> 388 torch.onnx.export(model, dummy_input, "test.onnx", verbose=False, export_params=True)
    389 
    390 #model.load_state_dict(chkpt['state_dict'])

~/python3env/lib/python3.5/site-packages/torch/onnx/__init__.py in export(model, args, f, export_params, verbose, training)
     73             only, so you will generally not need to set this to True.
     74     """
---> 75     _export(model, args, f, export_params, verbose, training)
     76 
     77 

~/python3env/lib/python3.5/site-packages/torch/onnx/__init__.py in _export(model, args, f, export_params, verbose, training)
    120                            "something weird is happening in your model!")
    121 
--> 122     _optimize_trace(trace)
    123     if verbose:
    124         print(trace)

~/python3env/lib/python3.5/site-packages/torch/onnx/__init__.py in _optimize_trace(trace)
     79     torch._C._jit_pass_peephole(trace)
     80     torch._C._jit_pass_lint(trace)
---> 81     torch._C._jit_pass_onnx(trace)
     82     torch._C._jit_pass_lint(trace)
     83     torch._C._jit_pass_onnx_peephole(trace)

RuntimeError: untraced buffer
```

However if we remove the `model = nn.DataParallel(model)` line, i.e. change the code to the following:
```
model = models.densenet.densenet121(pretrained=True)
dummy_input = Variable(torch.randn(10, 3, 224, 224)).cuda()
model = model.cuda()
torch.onnx.export(model, dummy_input, "test.onnx", verbose=False, export_params=True)
```
It at least exports the model.

I hope either we fix this bug (i.e. also support the model that is converted using nn.DataParallel(model), or provide an explicit error message saying multiple GPU model is not supported.

BTW - for those who still want to export such a model, here is the workaround:
https://stackoverflow.com/questions/44230907/keyerror-unexpected-key-module-encoder-embedding-weight-in-state-dict
i.e. still loading the single GPU model and when loading the weights, change the dict name to exclude the string "module".

When submitting a bug report, please include the following information (where relevant):
- OS: Linux
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): pip
- Python version: 3.5
- CUDA/cuDNN version: 8.0/cuDNN 6
- GPU models and configuration: Tesla K80
- GCC version (if compiling from source): N/A

**Comment by bpinaya** [comment] 2018-11-06 09:54
@daniel-j-h I think you are using cpu only? On Pytorch 1.0 RC I get:
```
Traceback (most recent call last):
  File "onnx_second_test.py", line 22, in <module>
    torch.onnx.export(model, dummy, 'resnet50.pb')
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 27, in export
    return utils.export(*args, **kwargs)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 104, in export
    operator_export_type=operator_export_type)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 280, in _export
    example_outputs, propagate)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 223, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 191, in _trace_and_get_graph_from_model
    trace, torch_out = torch.jit.get_trace_graph(model, args)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 167, in get_trace_graph
    return LegacyTracedModule(f)(*args, **kwargs)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/jit/__init__.py", line 198, in forward
    out = self.inner(*trace_inputs)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 475, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 465, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 125, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 130, in replicate
    return replicate(module, device_ids)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/replicate.py", line 13, in replicate
    param_copies = Broadcast.apply(devices, *params)
  File "/home/bpinaya/anaconda3/lib/python3.6/site-packages/torch/nn/parallel/_functions.py", line 14, in forward
    raise TypeError('Broadcast function not implemented for CPU tensors')
TypeError: Broadcast function not implemented for CPU tensors
```

The following works for me:
```python
import torch.nn as nn
from torch.autograd import Variable
import torch.onnx
import torchvision

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

dummy = Variable(torch.randn(10, 3, 224, 224, device='cuda'))

model = torchvision.models.resnet50(pretrained=True)

model.to(device)

torch.onnx.export(model, dummy, "resnet50.pb")
```

**Comment by houseroad** [comment] 2018-12-04 19:41
Please don't directly export nn.DataParallel model, instead exporting the model you wrapped with DataParallel. Duplicate of https://github.com/pytorch/pytorch/issues/13397

**Closed by houseroad** 2018-12-04 19:41 UTC
Labels: onnx

**Comment by houseroad** [comment] 2018-12-04 19:45
Feel free to reopen if you still have problem.

**Comment by BurkeyLai** [comment] 2020-06-10 09:46
```python
state_dict = torch.load('/path/to/your/.pth/model')
model.load_state_dict(state_dict)
model.eval()
dummy_input = Variable(torch.randn(B, C, H, W))
torch.onnx.export(model.module, dummy_input, '/path/to/output/onnx/model', export_params = True)
```
This works for me.

**Comment by Parisa-Bagherzadeh** [comment] 2024-08-13 07:47
> ```python
> state_dict = torch.load('/path/to/your/.pth/model')
> model.load_state_dict(state_dict)
> model.eval()
> dummy_input = Variable(torch.randn(B, C, H, W))
> torch.onnx.export(model.module, dummy_input, '/path/to/output/onnx/model', export_params = True)
> ```
> 
> This works for me.
where did you put this code? and what's the pth model?
