### ISSUE TITLE
hypothesis.errors.InvalidArgument in test_qadd_scalar_relu

### ISSUE THREAD

**Issue by s-bernard** [pytorch/pytorch#37576] opened 2020-04-30 10:34 UTC
## 🐛 Bug

When I run quantized tests, I'm getting:
```
test_qadd_scalar_relu (__main__.TestQuantizedOps) ...
You can add @seed(39762171245839440607525939898097434553) to this test to reproduce
this failure. ERROR
--stacktrace--
hypothesis.errors.InvalidArgument: Generated array element 869554.54066114 from
one_of(floats(min_value=0.0, max_value=1000000.0), floats(min_value=0.0,
max_value=1000000.0).map(neg)) cannot be represented as dtype dtype('float32') -
instead it becomes 869554.56 (type <class 'numpy.float32'>).  Consider using a more
precise strategy, for example passing the `width` argument to `floats()`.
```

I changed the seed, same behavior.

```
@seed(12312)
hypothesis.errors.InvalidArgument: Generated array element 103122.3694481376 from
one_of(floats(min_value=0.0, max_value=1000000.0), floats(min_value=0.0,
max_value=1000000.0).map(neg)) cannot be represented as dtype dtype('float32') -
instead it becomes 103122.37 (type <class 'numpy.float32'>).  Consider using a more
precise strategy, for example passing the `width` argument to `floats()`.

@seed(93)
hypothesis.errors.InvalidArgument: Generated array element 854541.4162008369 from
one_of(floats(min_value=0.0, max_value=1000000.0), floats(min_value=0.0,
max_value=1000000.0).map(neg)) cannot be represented as dtype dtype('float32') -
instead it becomes 854541.44 (type <class 'numpy.float32'>).  Consider using a more
precise strategy, for example passing the `width` argument to `floats()`.
```

What could be wrong with my setup?

## To Reproduce

1. `python test/run_test.py --verbose -i quantized`

## Expected behavior

All tests pass

## Environment

- PyTorch version: v1.4.1
- built from source
- Is debug build: no
- CUDA used to build PyTorch: no
- OS: Ubuntu 18.04.4 LTS in docker
- kernel: Linux 5.6.7-arch1-1
- GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CMake version: version 3.10.2
- Python version: 3.6
- Is CUDA available: No but ROCm is
- ROCm runtime: 3.3.0
- GPU models and configuration: AMD Vega 56
- Versions of relevant libraries:
  + [pip3] numpy==1.18.3
  + [pip3] torch==1.5.0a0+074eef0
  + [conda] no conda

 - Build command you used (if compiling from source): python setup.py install --user

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by s-bernard** [comment] 2020-04-30 12:08
Adding `width=32` in `elements=st.floats(-1e6, 1e6, allow_nan=False, width=32)` makes the test pass.

**Comment by vkuzo** [comment] 2020-05-12 23:48
hi @s-bernard , just to confirm, this is on PyTorch v1.4.1 and not on master?  I believe https://github.com/pytorch/pytorch/pull/26853 should have fixed this, and I can't repro on master.

**Comment by vkuzo** [comment] 2020-05-14 15:27
closing since this should be fixed on master, please reopen if you can still reproduce!

**Closed by vkuzo** 2020-05-14 15:27 UTC
Labels: quantization
