### ISSUE TITLE
issue with ONNX and PyTorch

### ISSUE THREAD

**Issue by arijit17** [pytorch/pytorch#22069] opened 2019-06-21 10:50 UTC
Hi all:

I'm getting this error:
```
TypeError: i_(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Node, arg0: str, arg1: int) -> torch._C.Node

 

Invoked with: %112 : Tensor = onnx::RandomNormal(), scope: XXXXX
, 'shape', 108 defined in (%108 : int[] = prim::ListConstruct(%102, %107, %106), scope: XXXXX
) (occurred when translating randn)
```

Any idea how to get around it?

I'm using:
Python 3.5.2 
Pytorch '1.0.1.post2'
Ubuntu 16.04.2

**Comment by VitalyFedyunin** [comment] 2019-06-24 19:09
Can you please send us more details about onnx model and about the way you are calling it. 
For example how is %102, %107 and %106 getting defined.

**Comment by arijit17** [comment] 2019-06-24 22:49
Hi @VitalyFedyunin: Thanks for your help, but sorry I'm new to ONNX so didn't understand your question. 

I (successfully) created and trained the model in PyTorch.
But, now I'm trying to train and directly save the model in ONNX (instead of PyTorch checkpoint), and it's here I'm getting the error. 
I don't really understand what %102, %107 and %106 are.

**Comment by VitalyFedyunin** [comment] 2019-06-25 14:55
Aha, so you had Pytorch model trained and traced. I will direct you to people who can help you faster.

**Comment by arijit17** [comment] 2019-07-09 12:31
Hi @VitalyFedyunin: any update on this? 

What do you mean by "traced"?
Yes, I have trained a model in PyTorch. I usually save it as checkpoint (*.ckpt) after certain number of epochs. When fully trained, obviously inferencing with the *.ckpt works nicely as well.
Since everything works, I was thinking of "deployment". Hence, I thought of converting the above *.ckpt to ONNX format, and I was hoping to see some magic :-)

Am I taking the right approach? 
Or should I directly save the model in *.onnx format (instead of *.ckpt) while training.

**Comment by VitalyFedyunin** [comment] 2019-07-09 17:56
You are doing everything right. Conversion (exporting) of the model to onnx requires model to be processed by JIT first. And it is where PyTorch is failing. That is why I tagged issue with 'jit' label and waiting JIT team to take a look.

**Comment by arijit17** [comment] 2019-07-16 19:46
Hi @VitalyFedyunin thanks. So nothing can be done from my side, right?
I also raised an issue on ONNX github and they mentioned it’s a PyTorch issue.

**Comment by VitalyFedyunin** [comment] 2019-07-18 21:21
You can help us by providing minimal sized example Model which is causing this issue.

**Comment by arijit17** [comment] 2019-08-13 10:32
Hi @VitalyFedyunin : sorry for the delay in replying. Before taking next steps, I would like to get a confirmation on the following for my understanding:
Is it true that ideally I should have used TorchScript to trace my Python code to a Python-free, statically typed graph representation that can be optimized and executed in production environments?
(PLEASE NOTE: currently all my models are written and created using Eager mode, containing control flow - like typical research code). 
So, I guess - the answer is YES. 

But, from your e-mail I understand that this should have been done automatically by PyTorch during "Conversion (exporting) of the model to onnx". Correct?

**Comment by spandantiwari** [comment] 2019-08-25 20:36
@arijit17 - It is hard to say where exactly the issue is without looking at your model and export code. Could you please share the repro? 
FYI - if your model has input-dependent control flow, then ideally you will have to convert those modules to `ScriptModule` and decorate those modules' `forward()` method with with `@torch.jit.script` to enable correct JIT compilation. But once you do that the export process itself should not change.
If you can share a repro, we might be able to help better.

**Comment by arijit17** [comment] 2019-08-29 15:11
@spandantiwari all right, thanks! Based on what you are saying, I believe I need to educate myself with Script mode before ONNXifying with Pytorch.
My model has: input-dependent control flow!

Unfortunately, I cannot share codes externally.
But, I will be super obliged if you could point me to appropriate documentation (for my education) on how to ONNX-ify Pytorch model (written in Eager mode) which has input-dependent control flow.

You can close this issue.

**Comment by spandantiwari** [comment] 2019-08-29 17:10
@arijit17 OK. You can look at this page for more details https://pytorch.org/docs/master/onnx.html . The "Tracing vs Scripting" section is relevant for input-dependent control flow. 

I will close this issue now.

**Closed by spandantiwari** 2019-08-29 17:10 UTC
Labels: jit, module: onnx

**Comment by Rishav1** [comment] 2019-10-14 09:07
Facing the same issue. Here is a minimalistic code to reproduce the issue.

```
import torch
import torch.nn as nn
from torch import onnx
from torch.autograd import Variable 

class NoiseLayer(nn.Module):
    """adds noise. noise is per pixel (constant over channels) with per-channel weight"""
    def __init__(self, channels):
        super().__init__()
        self.weight = nn.Parameter(torch.zeros(channels))
    
    def forward(self, x, noise=None):
        shape2 = x[:,1,...].unsqueeze(1).size()
        noise = torch.randn(shape2)
        x = x + self.weight.view(1, -1, 1, 1) * noise
        return x

model = NoiseLayer(channels=3)
output = model.forward(Variable(torch.randn(3,256,256)))
print(output)
# Translate this model using ONNX
onnx.export(model, Variable(torch.randn(3,256,256)), '/tmp/model.onnx')
```

**Comment by louiskirsch** [comment] 2020-10-26 17:15
I'm facing the same issues. Any updates on this @Rishav1?
