### ISSUE TITLE
[ONNX] FX exporter: replace `aten::copy_` with out-place version

### ISSUE THREAD

**Issue by justinchuby** [pytorch/pytorch#103857] opened 2023-06-19 18:41 UTC
In-place ops like `aten::copy_` should be replaced or removed before converting to ONNX.

Standard cases are handled by functionalization pass. This issue targets edge cases like [nn.InstanceNorm with track_running_stats=True](https://pytorch.org/docs/master/generated/torch.nn.InstanceNorm2d.html#torch.nn.InstanceNorm2d), which **updates model state** even in inference mode. 

Perhaps solution is to write an `unsafe_remove_inplace_pass` that emits diagnostic warnings to detect and handle these inplace ops. 

Repro: 

```python
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.instance_norm = torch.nn.InstanceNorm1d(3, affine=True, track_running_stats=True)

    def forward(self, x, y):
        out = x + y
        out = self.instance_norm(out)
        out = out + x
        return out

model = Model()
model.eval()
x = torch.randn(1, 3, 3)
y = torch.randn(1, 3, 3)

torch.onnx.dynamo_export(model, x, y)
```

cc @BowenBao @thiagocrepaldi @wschin

**Comment by thiagocrepaldi** [comment] 2023-06-19 19:09
That is what the Functionalization pass does. It rewrites the in place as out of place. Have you seen an issue with that? have a repro?

**Comment by BowenBao** [comment] 2023-06-19 19:48
@justinchuby I think this is a one-off issue/bug w/ this model `pytorch_stargan`. Someone can take a closer look at how this op is (still) emitted.

**Comment by BowenBao** [comment] 2023-07-15 00:23
Updated with repro, and proposal.

**Comment by thiagocrepaldi** [comment] 2023-07-17 14:14
Although I am not against a local fix when needed, I believe it should be done (as a last resource) only if this is not a bug or missing feature on actual functionalization code. Adding workarounds on exporter for every bug on pytorch will make our exporter more and more complex and full of dead code/passes when the bug if fixed upstream.

**Comment by BowenBao** [comment] 2023-07-17 17:11
This is not a bug or missing feature on actual functionalization code, otherwise it should be fixed upstream.

**Comment by thiagocrepaldi** [comment] 2023-07-17 17:37
> This is not a bug or missing feature on actual functionalization code, otherwise it should be fixed upstream.

for our understanding, could you elaborate on why not?

It is expected that [in-place ops are replaced by out-of-place by functionalization](https://pytorch.org/functorch/nightly/generated/functorch.functionalize.html#functorch.functionalize)

**Comment by BowenBao** [comment] 2023-07-17 18:23
Per [functionalize doc](https://pytorch.org/docs/master/generated/torch.func.functionalize.html#torch.func.functionalize)
> functionalize works on **(intermediate)** mutations and aliasing from a function, while preserving the function’s semantics.

> Like other torch.func transforms, functionalize() doesn’t work with global state. If you call functionalize(f) on a function that takes views / mutations of non-local state, functionalization will simply no-op and pass the view/mutation calls directly to the backend. One way to work around this is is to ensure that any non-local state creation is wrapped into a larger function, which you then call functionalize on.

model state mutation is by design not covered.

> This issue targets edge cases like [nn.InstanceNorm with track_running_stats=True](https://pytorch.org/docs/master/generated/torch.nn.InstanceNorm2d.html#torch.nn.InstanceNorm2d), which updates **model state** even in inference mode.

**Comment by thiagocrepaldi** [comment] 2023-07-17 18:48
> One way to work around this is is to ensure that any non-local state creation is wrapped into a larger function, which you then call functionalize on

Yes, but the repro from OP seems to apply the suggested work around, so maybe it should work: 

> "One way to work around this is is to ensure that any non-local state creation is wrapped into a larger function, which you then call functionalize on"

In this case, the `Model` wraps `torch.nn.InstanceNorm1d` state, and thus the global state does not involve stuff from `InstanceNorm1d`?

**Comment by BowenBao** [comment] 2023-07-17 19:35
model state is always considered global state in the context of functionalize. Unless one takes the AOTAutograd approach and lift all weights & buffers into function inputs.

**Comment by BowenBao** [comment] 2024-05-16 00:48
@justinchuby might be worth revisiting this scenario with ExportedProgram.

**Comment by justinchuby** [comment] 2024-05-16 17:17
```
> print(ir.serde.deserialize_model(torch.onnx.dynamo_export(torch.export.export(model, (x, y)), x, y).model_pr
    ...: oto).graph)
/home/codespace/.local/lib/python3.10/site-packages/torch/onnx/_internal/exporter.py:137: UserWarning: torch.onnx.dynamo_export only implements opset version 18 for now. If you need to use a different opset version, please register them with register_custom_op.
  warnings.warn(
graph(
    name=main_graph,
    inputs=(
        %"arg0_1"<FLOAT,[3]>,
        %"arg1_1"<FLOAT,[3]>,
        %"arg2_1"<FLOAT,[3]>,
        %"arg3_1"<FLOAT,[3]>,
        %"arg4_1"<INT64,[]>,
        %"arg5_1"<FLOAT,[1,3,3]>,
        %"arg6_1"<FLOAT,[1,3,3]>
    ),
    outputs=(
        %"alias_1"<FLOAT,[3]>,
        %"alias_3"<FLOAT,[3]>,
        %"add_1"<FLOAT,[1,3,3]>
    ),
) {
     0 |  # aten_add_10
          %"add"<FLOAT,[1,3,3]> ⬅️ pkg.onnxscript.torch_lib::aten_add(%"arg5_1", %"arg6_1") {alpha=1.0}
     1 |  # Constant_11
          %"_val_8"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[1]>(name='')}
     2 |  # aten_repeat_12
          %"repeat"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_repeat(%"arg0_1", %"_val_8")
     3 |  # Constant_13
          %"_val_10"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[1]>(name='')}
     4 |  # aten_repeat_14
          %"repeat_1"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_repeat(%"arg1_1", %"_val_10")
     5 |  # Constant_15
          %"_val_12"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[1]>(name='')}
     6 |  # aten_repeat_16
          %"repeat_2"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_repeat(%"arg2_1", %"_val_12")
     7 |  # Constant_17
          %"_val_14"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[1]>(name='')}
     8 |  # aten_repeat_18
          %"repeat_3"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_repeat(%"arg3_1", %"_val_14")
     9 |  # Constant_19
          %"_val_16"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[3]>(name='')}
    10 |  # aten_view_20
          %"view"<FLOAT,[1,3,3]> ⬅️ pkg.onnxscript.torch_lib::aten_view(%"add", %"_val_16")
    11 |  # Constant_21
          %"_val_18"<?,?> ⬅️ ::Constant() {value_ints=[0, 2]}
    12 |  # _aten_native_batch_norm_inference_onnx_22
          %"_native_batch_norm_legit_no_training"<FLOAT,[1,3,3]>, %"_native_batch_norm_legit_no_training_1"<FLOAT,[0]>, %"_native_batch_norm_legit_no_training_2"<FLOAT,[0]>, %"_val_22"<?,?>, %"_val_23"<?,?> ⬅️ pkg.onnxscript.torch_lib::_aten_native_batch_norm_inference_onnx(%"view", %"repeat", %"repeat_1", %"repeat_2", %"repeat_3") {eps=9.999999747378752e-06, momentum=0.8999999761581421}
    13 |  # aten_alias_23
          %"alias"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_alias(%"arg2_1")
    14 |  # Constant_24
          %"_val_25"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[2]>(name='')}
    15 |  # aten_view_25
          %"view_1"<FLOAT,[1,3]> ⬅️ pkg.onnxscript.torch_lib::aten_view(%"repeat_2", %"_val_25")
    16 |  # Constant_26
          %"_val_27"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[1]>(name='')}
    17 |  # aten_mean_dim_27
          %"mean"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_mean_dim(%"view_1", %"_val_27") {keepdim=0}
    18 |  # aten_copy_28
          %"copy"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_copy(%"alias", %"mean") {non_blocking=0}
    19 |  # aten_alias_29
          %"alias_1"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_alias(%"copy")
    20 |  # aten_alias_30
          %"alias_2"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_alias(%"arg3_1")
    21 |  # Constant_31
          %"_val_32"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[2]>(name='')}
    22 |  # aten_view_32
          %"view_2"<FLOAT,[1,3]> ⬅️ pkg.onnxscript.torch_lib::aten_view(%"repeat_3", %"_val_32")
    23 |  # Constant_33
          %"_val_34"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[1]>(name='')}
    24 |  # aten_mean_dim_34
          %"mean_1"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_mean_dim(%"view_2", %"_val_34") {keepdim=0}
    25 |  # aten_copy_35
          %"copy_1"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_copy(%"alias_2", %"mean_1") {non_blocking=0}
    26 |  # aten_alias_36
          %"alias_3"<FLOAT,[3]> ⬅️ pkg.onnxscript.torch_lib::aten_alias(%"copy_1")
    27 |  # Constant_37
          %"_val_38"<?,?> ⬅️ ::Constant() {value=TensorProtoTensor<INT64,[3]>(name='')}
    28 |  # aten_view_38
          %"view_3"<FLOAT,[1,3,3]> ⬅️ pkg.onnxscript.torch_lib::aten_view(%"_native_batch_norm_legit_no_training", %"_val_38")
    29 |  # aten_add_39
          %"add_1"<FLOAT,[1,3,3]> ⬅️ pkg.onnxscript.torch_lib::aten_add(%"view_3", %"arg5_1") {alpha=1.0}
    return %"alias_1"<FLOAT,[3]>, %"alias_3"<FLOAT,[3]>, %"add_1"<FLOAT,[1,3,3]>
}
```

**Comment by justinchuby** [comment] 2024-05-16 17:18
Verified: export works, onnx dynamo fails.

**Closed** 2024-07-26 13:16 UTC
Labels: module: onnx, triaged
