### ISSUE TITLE
Periodic Multigpu test looks to be flaky (multiple trunk runs are being cancelled)

### ISSUE THREAD

**Issue by eqy** [pytorch/pytorch#105721] opened 2023-07-21 04:13 UTC
`periodic / linux-bionic-cuda11.8-py3.9-gcc7 / test (multigpu, 1, 1, linux.16xlarge.nvidia.gpu)` looks to be cancelled for several out of the last few trunk runs:
https://hud.pytorch.org/hud/pytorch/pytorch/main/1?per_page=50&name_filter=periodic%20%2F%20linux-bionic-cuda11.8-py3.9-gcc7%20%2F%20test%20(multigpu%2C%201%2C%201%2C%20linux.16xlarge.nvidia.gpu)

It looks like it could be a machine/hardware issue as the driver init or `nvidia-smi` step seems to be failing?

## Current Status
ongoing

## Error looks like
```
+ HAS_NVIDIA_DRIVER=0
++ command -v nvidia-smi
+ '[' -x /usr/bin/nvidia-smi ']'
+ set +e
++ nvidia-smi --query-gpu=driver_version --format=csv,noheader --id=0
Error: Final attempt failed. Timeout of 600000ms hit
```

## Incident timeline (all times pacific)
Appearing at least since last Fri ~11pm:
https://hud.pytorch.org/pytorch/pytorch/commit/7b4d080496a971563998c3a1bcc500e76e8baffe

## User impact
PRs with `ciflow/periodic` may hit this upon merging

## Prevention/followups

CC @huydhn , apologies if this is a known issue.

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by huydhn** [comment] 2023-07-21 16:31
This is an issue with the runner itself from what I see.  Multigpu runners frequently get into the state where one of its GPU crashs (it has 4) causing `nvidia-smi` to fail/hang.  I don't know the root cause yet but will take a look to see if I can find any breadcrumbs.

**Comment by janeyx99** [comment] 2023-07-24 14:52
There is also now an UNSTABLE issue for this job https://github.com/pytorch/pytorch/issues/105762

**Comment by atalman** [comment] 2023-07-24 17:22
cc @ptrblck 
Here is a recent example: https://github.com/pytorch/pytorch/actions/runs/5639653634/job/15275883611

**Comment by ptrblck** [comment] 2023-07-24 18:12
Do we know if this issue is observed on a specific runner or multiple (with the same specs)?

**Comment by huydhn** [comment] 2023-07-26 02:44
It always happen on g3.16xlarge runner with 4 NVIDIA Tesla M60 GPUs according to https://aws.amazon.com/ec2/instance-types/g3/.  We suspect that this is related to the recent NVIDIA driver update https://github.com/pytorch/test-infra/pull/4366.  On the other hand, the good news is that I haven't seen this issue happening again after we move the job to the new g5 runner that has 4 NVIDIA A10G Tensor Core GPU instead (https://github.com/pytorch/pytorch/pull/105759)

**Comment by atalman** [comment] 2023-07-26 20:38
Closing this issue. I don't see these crashes anymore after : https://github.com/pytorch/pytorch/pull/105759 has been merged

**Closed by atalman** 2023-07-26 20:38 UTC
Labels: module: ci, triaged
