### ISSUE TITLE
Convolution for complex tensors

### ISSUE THREAD

**Issue by anjali411** [pytorch/pytorch#71108] opened 2022-01-10 16:45 UTC
### 🚀 The feature, motivation and pitch

Convolution operation is currently unsupported for complex types since cuDNN (the library we call into) doesn't support complex. However there have been several requests to add complex convolution. One of the recent requests was from an internal team who need complex convolution to multiply two polynomials (equivalent to convolution of their roots).

As a way to unblock people, we can start by implementing complex convolution as three real convolutions. And then, if needed, add specialized kernels for better performance. 

* [x] conv1d
* [x] conv2d
* [x] conv3d
* [x] conv_transpose1d
* [x] conv_transpose2d
* [x] conv_transpose3d

cc @ezyang @gchanan @zou3519 @bdhirsh @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by v0dro** [comment] 2022-01-16 22:17
@anjali411 How do you think this should be implemented? I can start with a CPU implementation of `Conv1D` and `Conv2D` and then proceed to GPU. And then tackle 3D convolutions in `Conv3D`. CPU/GPU and dimensions can be separate PRs.

Do you think that would be a good plan?

**Comment by anjali411** [comment] 2022-01-19 20:50
@v0dro that sounds like a good plan! I guess the idea is to compute convolutions using four real convolutions `Wx+b = (W1 + W2j) * (x1 +x2j) = (W1 * x1 -W2*x2) + (W1*x2 + W2*x1)j + (b1+b2)j` Two convolutions with non-zero bias and two with zero bias?

**Comment by albanD** [comment] 2022-01-19 21:36
I think that is a good first step: a composite op that uses view_as_real and real convolution.
If we want to be extra fancy, for W = Wr +i Wi etc:
`conv(W, x, b) = conv(Wr, xr, br) - conv(Wi, xi, 0) + i(conv(Wi, xr, bi) + conv(Wr, xi, 0))`
But also with gauss trick: 
`a = conv(Wr, xr, br)`, `b = conv(Wi, xi, 0)` and `c = conv(Wr + Wi, xr + xi, bi - br)` we can have `conv(W, x, b) = a - b + i(c -a - b)`.
Such that we get the result with only 3 real conv.

**Comment by ngimel** [comment] 2022-02-07 19:27
see also #52983

**Comment by rajb245** [comment] 2022-06-06 18:27
@kshitij12345 @anjali411 Great job getting this stuff merged! I've been very interested in complex representations in deep learning frameworks for some time now, mostly because complex time-series and stacks of complex images are the datatypes of interest in my field of telecommunications/radio-frequency signal processing. Having native support is just great! I have done some testing with complex tensors inputs and complex weights and everything seems to do what I want it to do.

In the older issue (https://github.com/pytorch/pytorch/issues/52983), the transposed functions were also requested, and I can confirm for 2D complex convolutions that these do not yet work on CPU or with the CUDA backend. On the CPU, I get:
`RuntimeError: "slow_conv_transpose2d_out_cpu" not implemented for 'ComplexFloat'`
On CUDA I get:
`RuntimeError: getCudnnDataTypeFromScalarType() not supported for ComplexFloat`

Are the transposed functions on your roadmap for implementation?

**Closed** 2022-11-02 06:38 UTC
Labels: high priority, feature, module: convolution, triaged, module: complex
