### ISSUE TITLE
`torch.cuda.amp` is not compatible with` torch.utils.checkpoint.checkpoint`

### ISSUE THREAD

**Issue by lartpang** [pytorch/pytorch#47183] opened 2020-11-02 12:28 UTC
## 🐛 Bug

I want to use these two very useful functions at the same time: `torch.cuda.amp` and `torch.utils.checkpoint.checkpoint`, but I get this error:

```shell
Traceback (most recent call last):
  File "/home/lart/Coding/MyProj/utils/some_tools/test_amp_ck.py", line 72, in <module>
    scaler.scale(loss).backward()
  File "/home/lart/miniconda3/envs/pt16end/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lart/miniconda3/envs/pt16end/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same

Process finished with exit code 1
```

**BUT** IF I USE the APEX lib from NVIDIA, It works well...

## To Reproduce

A demo:

The shared part:

```python
# -*- coding: utf-8 -*-
# @Time    : 2020/11/2
# @Author  : Lart Pang
# @File    : test_amp_ck.py
# @Project : MyProj
# @GitHub  : https://github.com/lartpang
import apex
import torch
from torch.utils.checkpoint import checkpoint
from tqdm import tqdm


class MyNetWithCheckpoint(torch.nn.Module):
    def __init__(self):
        super(MyNetWithCheckpoint, self).__init__()
        self.dummy_tensor = torch.ones(1, dtype=torch.float32,
                                       requires_grad=True)
        self.in_conv = torch.nn.Conv2d(3, 10, 3, 1, 1)
        self.out_conv = torch.nn.Conv2d(10, 1, 1)

    def forward(self, x):
        x = checkpoint(self.ck_in_conv, x, self.dummy_tensor)
        x = checkpoint(self.ck_out_conv, x)
        return x

    def ck_in_conv(self, x, dummy_arg=None):
        assert dummy_arg is not None
        x = self.in_conv(x)
        return x

    def ck_out_conv(self, x):
        # assert dummy_arg is not None
        x = self.out_conv(x)
        return x


def cal_loss(pred, gt):
    pred = pred.sigmoid()
    loss = (pred - gt) ** 2
    return loss.mean()


mynet = MyNetWithCheckpoint().cuda()

optimizer = torch.optim.SGD(mynet.parameters(), lr=0.001)
USE_AMP = True
ITER_NUM = 10

in_data = torch.randn(4, 3, 20, 20).cuda()
in_gt = torch.randint(low=0, high=2, size=(4, 3, 20, 20)).float().cuda()
```

When I use `torch.cuda.amp`:

```python
# with torch.cuda.amp
scaler = torch.cuda.amp.GradScaler(USE_AMP)

for _ in tqdm(range(ITER_NUM), total=ITER_NUM):
    with torch.cuda.amp.autocast(USE_AMP):
        pred = mynet(in_data)
    loss = cal_loss(pred=pred, gt=in_gt)
    scaler.scale(loss).backward()
    scaler.step(optimizer)
    scaler.update()
    optimizer.zero_grad()
```

It will output:

```shell
Traceback (most recent call last):
  File "/home/lart/Coding/MyProj/utils/some_tools/test_amp_ck.py", line 72, in <module>
    scaler.scale(loss).backward()
  File "/home/lart/miniconda3/envs/pt16end/lib/python3.8/site-packages/torch/tensor.py", line 185, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/lart/miniconda3/envs/pt16end/lib/python3.8/site-packages/torch/autograd/__init__.py", line 125, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Input type (torch.cuda.HalfTensor) and weight type (torch.cuda.FloatTensor) should be the same
```

When I use APEX from NVIDIA:

```python
# with apex.amp
mynet, optimizer = apex.amp.initialize(mynet, optimizer, opt_level="O1")

for _ in tqdm(range(ITER_NUM), total=ITER_NUM):
    pred = mynet(in_data)
    loss = cal_loss(pred=pred, gt=in_gt)
    if USE_AMP:
        with apex.amp.scale_loss(loss, optimizer) as scaled_loss:
            scaled_loss.backward()
    else:
        loss.backward()
    optimizer.step()
    optimizer.zero_grad()
```

It will output:

```shell

Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
100%|██████████| 10/10 [00:00<00:00, 60.96it/s]
```

## Expected behavior

I hope these two features can be used at the same time.

## Environment

```shell
➜ python collect_env.py 
Collecting environment information...
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 440.100
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] efficientnet-pytorch==0.7.0
[pip3] numpy==1.19.1
[pip3] segmentation-models-pytorch==0.1.0
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.2.89              hfd86e86_1    defaults
[conda] efficientnet-pytorch      0.7.0                    pypi_0    pypi
[conda] mkl                       2020.2                      256    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.1.0            py38h23d657b_0    defaults
[conda] mkl_random                1.1.1            py38h0573a6f_0    defaults
[conda] numpy                     1.19.1           py38hbc911f0_0    defaults
[conda] numpy-base                1.19.1           py38hfa32c7d_0    defaults
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] segmentation-models-pytorch 0.1.0                    pypi_0    pypi
[conda] torchvision               0.7.0                py38_cu102    pytorch
```

## Additional context

None. Thanks.

cc @mcarilli

**Comment by mruberry** [comment] 2020-11-03 05:01
Thank you for reporting this issue, @lartpang.

**Comment by ptrblck** [comment] 2020-11-03 10:03
[This PR](https://github.com/pytorch/pytorch/pull/40221) might have a valid workaround.
Could you try it out and check if it solves your issue?

**Comment by lartpang** [comment] 2020-11-03 14:02
Thanks for your reply! @mruberry @ptrblck 

https://github.com/pytorch/pytorch/issues/37730

We did encounter the same problem. According to the discussion in this issue, the pr can indeed solve the problem. But I don't want to modify the pytorch code directly. 
At present, the most elegant solution is to use apex, I think.
I sincerely hope that pytorch can improve this issue as soon as possible.

**Comment by mcarilli** [comment] 2020-12-01 00:04
Closing as duplicate of https://github.com/pytorch/pytorch/issues/37730.

The PR with the fix (https://github.com/pytorch/pytorch/pull/40221) looks fine to merge but needs a test.

**Closed by mcarilli** 2020-12-01 00:04 UTC
Labels: module: amp (automated mixed precision), module: checkpoint, triaged

**Comment by guozhiyao** [comment] 2021-07-30 06:50
Is the loss of your model with `checkpoint` and APEX from NVIDIA normal?

**Comment by lartpang** [comment] 2021-07-30 07:39
@guozhiyao The loss looks normal. Benefited from enough batches, good results were finally obtained.

**Comment by guozhiyao** [comment] 2021-07-31 02:49
@lartpang 
Thanks for your reply, I compared the following two methods:
1. distributeddataparallel+checkpoint
2. distributeddataparallel+checkpoint+apex
It is found that the loss of 1 is normal, the loss of 2 will be large, and the GPU usage of 1 and 2 have no obvious changes. Do you use the checkpoint+apex with distributeddataparallel? Is there any significant change in GPU usage?
In addition, have you ever noticed whether checkpoint affects BN running average mean/var?
