### ISSUE TITLE
Segmentation fault (core dumped) While running the fast_neural_style repo!

### ISSUE THREAD

**Issue by pradeephike** [pytorch/pytorch#7334] opened 2018-05-07 11:50 UTC
def stylize(args):
    device = torch.device("cuda" if args.cuda else "cpu")

    content_image = utils.load_image(args.content_image, scale=args.content_scale)
    content_transform = transforms.Compose([
        transforms.ToTensor(),
        transforms.Lambda(lambda x: x.mul(255))
    ])
    content_image = content_transform(content_image)
    content_image = content_image.unsqueeze(0).to(device)

    if args.model.endswith(".onnx"):
        output = stylize_onnx_caffe2(content_image, args)
    else:
        with torch.no_grad():
            style_model = TransformerNet()
            state_dict = torch.load(args.model)
            # remove saved deprecated running_* keys in InstanceNorm from the checkpoint
            for k in list(state_dict.keys()):
                if re.search(r'in\d+\.running_(mean|var)$', k):
                    del state_dict[k]
            style_model.load_state_dict(state_dict)
            style_model.to(device)
            if args.export_onnx:
                assert args.export_onnx.endswith(".onnx"), "Export model file should end with .onnx"
                output = torch.onnx._export(style_model, content_image, args.export_onnx)
            else:
                output = style_model(content_image).cpu()
    utils.save_image(args.output_image, output[0])

def stylize_onnx_caffe2(content_image, args):
    """
    Read ONNX model and run it using Caffe2
    """

    assert not args.export_onnx

    import onnx
    import onnx_caffe2.backend

    model = onnx.load(args.model)

    prepared_backend = onnx_caffe2.backend.prepare(model, device='CUDA' if args.cuda else 'CPU')
    inp = {model.graph.input[0].name: content_image.numpy()}
    c2_out = prepared_backend.run(inp)[0]

    return torch.from_numpy(c2_out)

This is the part of code I am trying to run.
The pytorch model is successfully converted into onnx but when I try to infer using the onnx model, I am encountering segmentation fault. 

Any insights?

cc @ezyang @gchanan @zou3519 @jerryzh168 @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by martinbel** [comment] 2018-05-28 14:50
For me the problem is exactly after this import:
`import onnx_caffe2.backend`

**Comment by MarsTT** [comment] 2019-10-30 12:55
@martinbel has this problem been solved?

**Comment by martinbel** [comment] 2019-10-30 20:15
I tried this more than a year ago. Who knows.

**Comment by gchanan** [comment] 2019-10-31 01:57
@MarsTT did you run into this?

**Comment by MarsTT** [comment] 2019-10-31 03:11
I have solved this problem, you can import the library like:
`import caffe2.python.onnx.backend as backend`

**Comment by colesbury** [comment] 2019-11-04 18:19
I'm closing this because the issue is over a year old. Please re-open if you run into the problem!

**Closed by colesbury** 2019-11-04 18:19 UTC
Labels: high priority, module: onnx, topic: crash

**Comment by poornimajd** [comment] 2019-11-26 13:21
> I have solved this problem, you can import the library like:
> `import caffe2.python.onnx.backend as backend`

this did not work for me
