### ISSUE TITLE
The empty 1D or more D tensor for `nanmedian()` with the deepest `dim` gets errors, not getting NaNs

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#131149] opened 2024-07-19 07:20 UTC
### 🐛 Describe the bug

The empty 1D or more D tensor for [nanmedian()](https://pytorch.org/docs/stable/generated/torch.nanmedian.html) can get a NaN as shown below:

```python
import torch

my_tensor = torch.tensor([]) # 1D tensor

torch.nanmedian(input=my_tensor)
# tensor(nan)

my_tensor = torch.tensor([[]]) # 2D tensor

torch.nanmedian(input=my_tensor)
# tensor(nan)

my_tensor = torch.tensor([[[]]]) # 3D tensor

torch.nanmedian(input=my_tensor)
# tensor(nan)
```

But, the empty 1D or more D tensor for `nanmedian()` with the deepest `dim` gets the errors, not getting NaNs as shown below:

```python
import torch

my_tensor = torch.tensor([]) # 1D tensor

torch.nanmedian(input=my_tensor, dim=0) # Error

my_tensor = torch.tensor([[]]) # 2D tensor

torch.nanmedian(input=my_tensor, dim=1) # Error

my_tensor = torch.tensor([[[]]]) # 3D tensor

torch.nanmedian(input=my_tensor, dim=2) # Error
```

> IndexError: median(): Expected reduction dim 0 to have non-zero size.

> IndexError: median(): Expected reduction dim 1 to have non-zero size.

> IndexError: median(): Expected reduction dim 2 to have non-zero size.

### Versions

```python
import torch

torch.__version__ # 2.3.1+cu121
```

**Comment by malfet** [comment] 2024-07-19 15:31
Closing as duplicate of https://github.com/pytorch/pytorch/issues/131148

**Closed by malfet** 2024-07-19 15:31 UTC
