### ISSUE TITLE
DISABLED test_server_process_global_profiler (__main__.TensorPipeRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#49633] opened 2020-12-19 04:30 UTC
https://app.circleci.com/pipelines/github/pytorch/pytorch/253337/workflows/d7deaf65-3973-4e30-9892-c286d8b843b0/jobs/9751335/steps

```
Dec 18 03:58:28 ======================================================================
Dec 18 03:58:28 ERROR [3.451s]: test_profiler_with_sync_rpc_udf_single_threaded (__main__.TensorPipeRpcTestWithSpawn)
Dec 18 03:58:28 ----------------------------------------------------------------------
Dec 18 03:58:28 Traceback (most recent call last):
Dec 18 03:58:28   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 280, in wrapper
Dec 18 03:58:28     self._join_processes(fn)
Dec 18 03:58:28   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 397, in _join_processes
Dec 18 03:58:28     self._check_return_codes(elapsed_time)
Dec 18 03:58:28   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 433, in _check_return_codes
Dec 18 03:58:28     raise RuntimeError(error)
Dec 18 03:58:28 RuntimeError: Processes 1 exited with error code 10
```

```
Dec 18 23:47:13   test_server_process_global_profiler (__main__.TensorPipeRpcTestWithSpawn) ... ERROR:root:Caught exception: 
Dec 18 23:47:13 Traceback (most recent call last):
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 283, in wrapper
Dec 18 23:47:13     fn()
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Dec 18 23:47:13     return_value = old_test_method(self, *arg, **kwargs)
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1802, in test_server_process_global_profiler
Dec 18 23:47:13     self._assert_top_level_events(inner_events, ['aten::sub'])
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1779, in _assert_top_level_events
Dec 18 23:47:13     self.assertEqual(sorted(top_level_event_names), sorted(expected_top_level_event_names))
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1208, in assertEqual
Dec 18 23:47:13     exact_dtype=exact_dtype, exact_device=exact_device)
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1178, in assertEqual
Dec 18 23:47:13     super().assertEqual(x, y, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/unittest/case.py", line 829, in assertEqual
Dec 18 23:47:13     assertion_func(first, second, msg=msg)
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
Dec 18 23:47:13     self.fail(self._formatMessage(msg, standardMsg))
Dec 18 23:47:13   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Dec 18 23:47:13     raise self.failureException(msg)
Dec 18 23:47:13 AssertionError: 'aten::empty' != 'aten::sub'
Dec 18 23:47:13 - aten::empty
Dec 18 23:47:13 + aten::sub
Dec 18 23:47:13  : Attempted to compare [string] types: Expected: 'aten::empty'; Actual: 'aten::sub'.
Dec 18 23:47:13 exiting process with exit code: 10
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @mrzzd @agolynski @SciPioneer @H-Huang @cbalioglu

**Comment by mrshenli** [comment] 2021-02-03 18:47
another instance: https://app.circleci.com/pipelines/github/pytorch/pytorch/268819/workflows/2123475a-52df-42db-af42-b9c9ddaa56d4/jobs/10637196/steps

**Comment by rohan-varma** [comment] 2021-12-22 20:26
duplicate of https://github.com/pytorch/pytorch/issues/68850

**Closed by rohan-varma** 2021-12-22 20:26 UTC
Labels: oncall: distributed, triaged, module: flaky-tests, module: rpc, skipped
