### ISSUE TITLE
[Inductor] [CPU] Huggingface model MobileBertForQuestionAnswering performance regression > 10% on ww09.2

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#95683] opened 2023-02-28 02:59 UTC
### 🐛 Describe the bug

Compare with the ww08.4, there is a performance regression on huggingface model MobileBertForQuestionAnswering on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1447448011) on ww09.2 as bellow:

|  ww09.2  |   |     |   |  ww08.4   |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|1.2841	|0.0494711	|0.06352584	|1	|1.6596	|0.038657	|0.064155157	|0.77	|1.01	|0.78

WW09.2 SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[3313e86](https://github.com/pytorch/pytorch/commit/3313e86c033331a19d9bbea8dde343ca6f8320be)|[a88bfc6](https://github.com/pytorch/pytorch/commit/a88bfc60c75d22a047f03787aaa43130c6a8d6d9)
Torchbench|/|[916ab70](https://github.com/pytorch/benchmark/commit/916ab70b96f1a57de2a7cdf2823938416926b8b0)
torchaudio|[a9a520a](https://github.com/pytorch/audio/commit/a9a520af0810a843da2c551c4e5eeee33060db40)|[de54d86](https://github.com/pytorch/audio/commit/de54d864b271a5dde42aa650c828de18ea37580a)
torchtext|[08c309a](https://github.com/pytorch/text/commit/08c309a8373a0541f0baed20e8987fd564c9ef03)| [bb0efcd](https://github.com/pytorch/text/commit/bb0efcd41d34661ae167029162d0fc73344140a8)
torchvision|[9c365bd](https://github.com/pytorch/vision/commit/9c365bd9b1d500a6e2a9e22d59fcfac27db83320)|[c05ad81](https://github.com/pytorch/vision/commit/c05ad81bcb8a042a67abfd57efabb0778584b922)
torchdata|[eed68d9](https://github.com/pytorch/data/commit/eed68d98b5dfcbbb498d400be48e0b60bc99d7ce)|[e14927f](https://github.com/pytorch/data/commit/e14927f32a6cf99658f72b765425bf032116f724)
dynamo_benchmarks|[cb47373](https://github.com/pytorch/pytorch/commit/cb47373166c3cba2514589e917e228ca9f9682ca)|/

WW08.4 SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[5a6cf28](https://github.com/pytorch/pytorch/commit/5a6cf2804b0ee0c5da9a74322b2e2d0d836cdeb8)|[286d821](https://github.com/pytorch/pytorch/commit/286d821e61e29de8fd6c81abd78b84fea5a44c0b)
Torchbench|/|[916ab70](https://github.com/pytorch/benchmark/commit/916ab70b96f1a57de2a7cdf2823938416926b8b0)
torchaudio|[a9a520a](https://github.com/pytorch/audio/commit/a9a520af0810a843da2c551c4e5eeee33060db40)|[de54d86](https://github.com/pytorch/audio/commit/de54d864b271a5dde42aa650c828de18ea37580a)
torchtext|[08c309a](https://github.com/pytorch/text/commit/08c309a8373a0541f0baed20e8987fd564c9ef03)| [bb0efcd](https://github.com/pytorch/text/commit/bb0efcd41d34661ae167029162d0fc73344140a8)
torchvision|[9c365bd](https://github.com/pytorch/vision/commit/9c365bd9b1d500a6e2a9e22d59fcfac27db83320)|[c05ad81](https://github.com/pytorch/vision/commit/c05ad81bcb8a042a67abfd57efabb0778584b922)
torchdata|[eed68d9](https://github.com/pytorch/data/commit/eed68d98b5dfcbbb498d400be48e0b60bc99d7ce)|[e14927f](https://github.com/pytorch/data/commit/e14927f32a6cf99658f72b765425bf032116f724)
dynamo_benchmarks|[cb47373](https://github.com/pytorch/pytorch/commit/cb47373166c3cba2514589e917e228ca9f9682ca)|/

Graph dump by cosim:
WW09.2:
[graph.txt](https://github.com/pytorch/pytorch/files/10846136/graph.txt)

WW08.4:
[graph.txt](https://github.com/pytorch/pytorch/files/10846139/graph.txt)

### Versions

Minified repro:

```
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/huggingface.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only MobileBertForQuestionAnswering  --cold_start_latency --batch_size 1 --threads 1
```

cc @soumith @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by wconstab** [comment] 2023-03-06 18:14
I already landed #95931 but would like to ask if you can rerun the benchmark and confirm the impact.

**Comment by wconstab** [comment] 2023-03-06 18:16
closing 2 of 3 related issues now. Letting you guys close the last one once confirmed.  (or if it's still not fixed maybe just mention 3 models on one issue if the assumption is they are regressing with the same root cause)

**Closed by wconstab** 2023-03-06 18:16 UTC
Labels: triaged, module: inductor

**Comment by ESI-SYD** [comment] 2023-03-07 01:44
Confirmed. Performance data improved to **0.0413817** in 2023-03-05 nightly release benchmark.
