### ISSUE TITLE
Support using SymBool in arithmetics

### ISSUE THREAD

**Issue by arogozhnikov** [pytorch/pytorch#110738] opened 2023-10-06 18:31 UTC
### 🐛 Describe the bug

Currently expressions like  `(x > 1) + (x < 2)`  are not handled by `torch.compile` with dynamic shapes. 

### Error logs

```

RuntimeError: Failed running call_function <built-in function add>(*(s0 > 1, s0 < 3), **{}):
unsupported operand type(s) for +: 'SymBool' and 'SymBool'
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

```

### Minified repro

```python
import torch
compiled = torch.compile(lambda x: (x.shape[0] > 1) + (x.shape[0] < 3), dynamic=True)
compiled(torch.zeros([2]))
```

### Versions

tested on pytorch 2.0.1 and 2.1.0 
<other information irrelevant>

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by drubinstein** [comment] 2023-10-06 18:38
Hi. I originally found the issue when trying to find the reason for a graph break using `torch._dynamo.explain`

**Comment by jon-chuang** [comment] 2023-10-07 11:02
Yes, they will need to be coerced to symint when using add / sub  / mul / integer div operators.

**Comment by kk271kg** [comment] 2023-10-09 12:13
Hello,
Can I contribute on this issue? I would like to try to solve this.

**Comment by jon-chuang** [comment] 2023-10-09 13:24
hello @kk271kg, I am already investigating this issue if that's ok

**Comment by kkormond** [comment] 2023-10-09 15:31
Hello @jon-chuang, no problem.

**Comment by jon-chuang** [comment] 2023-10-13 00:00
Hmm, not sure if we need to somehow zero-one specialize on bool... 

seems like torch compile will check a lot of conditions on symints, but will these need to be propagated further when doing arithmetic with symbools? :thinking:

**Comment by ezyang** [comment] 2023-10-13 15:34
So, for the particular example here, it is a bit awkward because for x == 0 and x == 1 we will 0/1 specialize them, and so the expression is actually constant when x >= 2. However, this is only true if x is an input; if x is some derived quantity, you may still have an opportunity to do meaningful compute; likewise if x is unbacked.

If you have a derived quantity that happens to be zero or one, we won't 0/1 specialize it unless you try to, e.g., create a tensor from it. That's not the case here.

I guess I'll look at your PR.

**Comment by hgl71964** [comment] 2024-01-29 02:31
hey, it seems the Minified repro can be run with no problem

**Comment by arogozhnikov** [comment] 2024-01-29 02:52
just tried 2.1.2 and still fails

**Comment by ayush0x00** [comment] 2024-04-27 14:11
> hey, it seems the Minified repro can be run with no problem

Yupp... I just tried it. Working fine on `torch==2.3.0.dev20240212`. Does it mean the issue is fixed?

**Comment by zhxchen17** [comment] 2024-07-05 19:43
seems fixed on main branch

**Closed by zhxchen17** 2024-07-05 19:43 UTC
Labels: good first issue, triaged, bug, oncall: pt2, module: dynamic shapes
