### ISSUE TITLE
F.interpolate() cannot be successfully converted to ONNX/TensorRT

### ISSUE THREAD

**Issue by kaishian** [pytorch/pytorch#32110] opened 2020-01-13 18:57 UTC
pytorch : 1.4.0a0 + 46f32e1
onnx    : 1.6.0
onnx2trt: 7.0
tensorrt: 7.0.0.11

![image](https://user-images.githubusercontent.com/22209240/72283263-5ef0bf00-3679-11ea-8e54-f7023f09fc09.png)

![image](https://user-images.githubusercontent.com/22209240/72283323-78920680-3679-11ea-8d6c-c5132ed12f4a.png)

Any suggestions on this issue?

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment] 2020-01-15 19:16
@kaishian - I am not able to make much out of the TensorRT assertion. Do you see anything wrong with the exported model?

**Comment by kaishian** [comment] 2020-01-15 19:35
@spandantiwari Thank you for your attention!

This is the only warning I got when calling torch.onnx.export()
![image](https://user-images.githubusercontent.com/22209240/72464473-4bc42780-3810-11ea-9918-bb6255a5b515.png)

Here are the details when exporting the model to onnx:
[log file](https://drive.google.com/open?id=106S6UvX7pC2PZvtU07RZd7pY2rlxVqBt)

This is the onnx model file:
[model file](https://drive.google.com/open?id=108CHApvmqw9I7u7d2-WSY8-1byvdqnTU)

Hope these information helps.

**Comment by spandantiwari** [comment] 2020-01-15 19:39
That warning is mostly benign. Could you try exporting the model to latest Opset 11. You can do that by adding an argument in the export API call as follows:
`torch.onnx.export(......., opset_version=11)`

**Comment by lara-hdr** [comment] 2020-01-15 19:43
@kaishian , there are other similar open issues.
It seems like it is a problem with Resize in tensorrt.
https://github.com/onnx/onnx/issues/2524#issuecomment-572832327
https://github.com/NVIDIA/TensorRT/issues/284#issuecomment-573301643

**Comment by kaishian** [comment] 2020-01-16 06:43
@spandantiwari The ONNX model I created last time is under opset 11 and the problem seems to exist.

@lara-hdr Thank you for your reminder, I will take a closely look.

**Comment by conan-biu** [comment] 2020-01-19 07:47
I met this problem and solve it. It seems that the generated protobuf format could not been parsed by the TensorRT. Some constants should be "initialier" op but it is regard as "node". If you run yout X.onnx by using onnxruntime, this problem can be solve. So you can revise you code following onnxruntime.

**Comment by kingyj7** [comment] 2020-06-10 03:05
Hi, @conan-biu, sorry to bother you. 
Could you please share a detail on how to get an onnx model  that can be parsed by TensorRT correctly in this situation? I'm a bit green at onnx and tensorRT. Thank you in advance!

**Comment by garymm** [comment] 2022-03-01 21:31
Closing due to age and lack of reply from @kaishian. Feel free to open a new issue with clear reproduction instructions, including the model definition and the call to `torch.onnx.export`.

**Comment by kingyj7** [comment] 2022-03-01 21:31
信件已收到:)

**Closed by garymm** 2022-03-01 21:31 UTC
Labels: module: onnx, triaged
