### ISSUE TITLE
Improve error message for `unfold` when generating tensor with negative dimension

### ISSUE THREAD

**Issue by TestSomething22** [pytorch/pytorch#76617] opened 2022-04-30 11:49 UTC
### 🐛 Describe the bug

`unfold` could generate tensor with negative dimension

```python
import torch
input_tensor = torch.rand([5, 5, 5], dtype=torch.complex128)
dimension = 2
size = -1
step = 2
res = input_tensor.unfold(dimension, size, step)
print(res.shape)
# torch.Size([5, 5, 4, -1])
```

### Versions

pytorch: 1.10.0

cc @ezyang @gchanan @zou3519

**Comment by jbschlosser** [comment] 2022-05-09 16:45
I can't reproduce this on master:
```
RuntimeError: Storage size calculation overflowed with sizes=[5, 5, 4, -1] and strides=[25, 5, 2, 1]
```

May have been fixed by #73719.

**Comment by albanD** [comment] 2022-05-09 17:06
That error message doesn't sound right though? Or at least could be improved.

**Closed** 2024-11-09 17:12 UTC
Labels: triaged, actionable, module: shape checking, module: viewing and reshaping
