### ISSUE TITLE
[jit] Bug with list remove tensor

### ISSUE THREAD

**Issue by BowenBao** [pytorch/pytorch#28322] opened 2019-10-18 23:04 UTC
## 🐛 Bug

Does not work with tensors of size > 1.

## To Reproduce

A small change from zeros(1) to zeros(2) in the existing test case.

```
    def test_mutable_list_remove_tensor(self):
        def test_list_remove_tensor():
            a = [torch.ones(2), torch.zeros(2), torch.ones(2)]
            a.remove(torch.zeros(2))

            return len(a) == 2
        self.checkScript(test_list_remove_tensor, ())
```

Errors with

```
ERROR: test_mutable_list_remove_tensor (__main__.TestList)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 18955, in test_mutable_list_remove_tensor
    self.checkScript(test_list_remove_tensor, ())
  ...
RuntimeError: bool value of Tensor with more than one value is ambiguous
The above operation failed in interpreter, with the following stack trace:
at <string>:3:4
def test_list_remove_tensor():
    a = [torch.ones(2), torch.zeros(2), torch.ones(2)]
    a.remove(torch.zeros(2))
    ~~~~~~~~ <--- HERE

    return len(a) == 2
```

## Environment

PyTorch built from master.

cc @ezyang @gchanan @zou3519 @jerryzh168 @suo

**Comment by suo** [comment] 2019-10-21 01:44
Thanks for the report!

**Comment by suo** [comment] 2019-10-21 04:24
This behavior is actually intentional (and the same as what you would get in eager mode)

The error message contains a hint as to why: coercing a tensor more than one element to a boolean is ambiguous. The equality operator on Tensor (which is what `remove()` is using for its comparison) returns a bool tensor where each element says whether the corresponding elements on the two operands are equal, e.g.:
```
> print(torch.ones(2) == torch.ones(2))
tensor([True, True])
```

Turning that tensor to a scalar bool is ambiguous: does "True" mean all the elements must be true? at least one of them to be true? etc.

Closing this issue for now as this is intended behavior, but feel free to ask questions/comment.

**Closed by suo** 2019-10-21 04:24 UTC
Labels: high priority, jit, triaged
