### ISSUE TITLE
When I use torch. compile(), the inference speed of the model becomes very slow, even dozens of times slower

### ISSUE THREAD

**Issue by CZXIANGOvO** [pytorch/pytorch#121793] opened 2024-03-13 07:01 UTC
### 🐛 Describe the bug

When I use torch. compile(), the inference speed of the model becomes very slow, even dozens of times slower.As shown in the picture, the time after old is the inference time before compile, and after new is the inference time after compile, with a difference of many times in the middle.In my current usage scenario, I cannot tolerate this slowness and I need to accelerate immediately to reduce code runtime.
![屏幕截图 2024-03-13 144203](https://github.com/pytorch/pytorch/assets/121651120/af5874ca-c552-4f44-ad9b-74edc9e6eb14)

### Minified repro

    model_path = '/root/MR20233/torch_mutated_net/vgg11/2024_03_13_10_19_40/old/5.pth'
    model = torch.load(model_path)
    print(model)
    input = torch.ones(5,3,32,32).to('cpu')

    start = time.time()
    new_outputs = model(input)[0]
    end = time.time()
    run_time = end - start

    new_model = torch.compile(model)
    start_1 = time.time()
    new_outputs_1 = new_model(input)[0]
    end_1 = time.time()
    run_time_1 = end_1 - start_1
    print("old",run_time,"\nnew",run_time_1)

5.pth[https://drive.google.com/file/d/1WKLSMbLWQmxKdwlkK71w6_67DUWZRNyX/view?usp=sharing]

### Versions

torch                        2.0.0+cpu

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang

**Comment by CZXIANGOvO** [comment] 2024-03-13 08:41
> Hi @CZXIANGOvO , I have request for accessing the model file, could you please approve it?

Okay, I have already approved it

**Comment by ZhaoqiongZ** [comment] 2024-03-13 09:29
Hi 

> > Hi @CZXIANGOvO , I have request for accessing the model file, could you please approve it?
> 
> Okay, I have already approved it

Hi @CZXIANGOvO , Could you offer me the md5sum of 5.pth,  I downloaded but it throw error ModuleNotFoundError: No module named 'models' at torch.load step in serialization.
Here is the md5sum for 5.pth I downloaded  8e8b78e14c10bef4bc377a6ad1d9050e  5.pth

**Comment by ezyang** [comment] 2024-03-15 04:36
Can you try a more recent version of pt2, or perhaps a nightly?

**Comment by anijain2305** [comment] 2024-03-18 16:49
@CZXIANGOvO torch.compile is a JIT compiler. Therefore, it compile the model on the first invocation. Therefore, the time is so high. 

You should add a warmup stage, and then do a comparison.

**Comment by leslie-fang-intel** [comment] 2024-03-21 07:56
Hi @sanchitintel, could you help to take a look of this issue?

**Comment by sanchitintel** [comment] 2024-03-21 09:16
Hi @CZXIANGOvO, unfortunately, I'm unable to use your model file because of #18325 (`ModuleNotFoundError: No module named 'models')` error. @ZhaoqiongZ, the error you're encountering whiel loading the model is also because of this issue.

@CZXIANGOvO, are you able to reproduce the performance issue with torchvision's vgg16 as well?
As @anijain2305 mentioned, please compare the runtime of the second run of the model after `torch.compile`. During the first run, among other kernels that may be JIT compiled, oneDNN & oneMKL kernels would also be JIT compiled. So you can think of the first run as a warmup run.

Thanks!

**Comment by leslie-fang-intel** [comment] 2024-08-22 08:57
Hi @CZXIANGOvO, I am going to close this issue as it's still not reproduceable. Feel free to reopen if any further discussion needed here.

**Closed by leslie-fang-intel** 2024-08-22 08:57 UTC
Labels: needs reproduction, triaged, oncall: pt2, oncall: cpu inductor
