### ISSUE TITLE
Couple hundred MB are taken just by initializing cuda

### ISSUE THREAD

**Issue by lironmo** [pytorch/pytorch#20532] opened 2019-05-15 15:06 UTC
hello,
it's seems that any process that use cuda consume at initializing step around 300MB to 400MB!.
The problem that this memory overhead happened on the GPU RAM, what cause cuda OUT OF MEMORY ERROR.  

This is very problematic in my scenario of multiple process that use the cuda resource.
Environments:
Cloud: AWS
Machine Type: single p3.8xlarge machine with only 4 gpus
Machine Image: "Deep Learning AMI (Amazon Linux) Version 11.0" with pytorch 1.1(installed locally)
number of workers that use CUDA: 2 - 100 workers

to use cuda at all process i implemented smart GPU shared policy to allow all the worker to use the GPU(with acquiring available GPU and release at the end of the training)
 and accelerate the training time of distributed system.

at multiprocessing environment this initialization overhead in memory at the GPU is is not feasible and cause cuda OOM error, because each worker "contribute" 400MB for each GPU! what cause the exception (overthead of 400*num_workers MB for each GPU) 

i  test the init by creating a=torch.cuda.FloatTensor(1).

why it's need so many memory on the GPU?
can i release it?

**Comment by colesbury** [comment] 2019-05-15 18:55
> why it's need so many memory on the GPU?

It's used by the CUDA driver. I think it's used to store the CUDA kernels and PyTorch has a lot of CUDA kernels.

> can i release it?

No (other than quitting the process)

The standard practice is to **not** access the same GPU from multiple processes. i.e. use one process per GPU.

**Comment by colesbury** [comment] 2019-05-15 19:00
Also see https://stackoverflow.com/questions/7146226/device-memory-for-cuda-kernel-code-is-it-explicitly-manageable#tab-top

**Comment by lironmo** [comment] 2019-05-15 19:18
Thanks for the answer.
Maybe i can workaround it and spawn another child process for each batch and pass the models by queues - but it will slow down the process and probably be worst than cpu tesnsor. 

If the standard practice "is to not access the same GPU from multiple processes"  there is a scale problem that probably need to be fixed( at the distributed/federated world)


why it's allocate on the GPU? 
I can limit the resource of each contexts consume?

i read the link you send but i still didn't found what is the reason that the contexts cannot be released.

Do you know the interior design of pytorch/cuda memory management?
if yes, maybe we can find some hack to release the memory without killing the python(i see some other process  that use the gpu without this over head - so it's related to use at cuda )

**Comment by li-roy** [comment] 2019-05-16 23:32
Closing this because it's not an actionable issue.

**Closed by li-roy** 2019-05-16 23:32 UTC

**Comment by lironmo** [comment] 2019-05-20 09:30
@li-roy 
please refer to my questions above before closing.

**Comment by soumith** [comment] 2019-05-20 12:47
the context occupying memory is by design of the CUDA / NVIDIA software stack. It's non-actionable because there is nothing we can technically do about it.
We can release the context, because all memory will become invalid.

**Comment by lironmo** [comment] 2019-05-23 13:18
@soumith when the torch.cuda.memory_allocated return ~43MB and the actual memory is 700MB there is a bug in the cuda internal.
kernel at cuda are only functions,  design that for each process consume that mach of memory is small design mistake.

**Comment by soumith** [comment] 2019-05-26 16:33
@lironmo the CUDA driver and context take a certain amount of fixed memory for their internal purposes. on recent NVIDIA cards (Pascal, Volta, Turing), it is more and more. `torch.cuda.memory_allocated` returns only memory that PyTorch actually allocated, for Tensors etc. -- so that's memory that you allocated with your code. the rest of it (700 - 43 MB) is being taken by driver and cuda context

**Comment by lironmo** [comment] 2019-05-26 19:11
@soumith - i found the answer to my question(see link below). I need to make the change at torch.cuda and test it.
Thanks.

https://devtalk.nvidia.com/default/topic/1044191/cuda-programming-and-performance/determine-memory-cuda-context-memory-usage/

**Comment by IouJenLiu** [comment] 2019-08-19 19:11
Hi @lironmo 
I have the same issue. Do you solve the question? Would you mind share how do you change torch.cuda? Thanks.

**Comment by andyljones** [comment] 2019-10-10 14:43
Does anyone know why pytorch's init eats far more memory than other libraries? 

Checking `nvidia-smi` before and after, creating an empty tensor in pytorch costs 800MB of GPU memory,
```python
import torch; torch.zeros((), device='cuda')
```
or 170MB to run something similar in tensorflow:
```python
import tensorflow as tf; tf.constant([])
```
or 175MB in cupy
```python
import cupy; cupy.array([])
```
or 170MB in pycuda
```python
import pycuda.driver as cuda; import pycuda.autoinit; cuda.mem_alloc(1)
```
The extra 600MB is fine if you're running a single monolithic network, but for RL or hyperparameter opt where there're a bunch of interacting networks it tots up to a fair fraction of total GPU memory.

If it's just that pytorch has far more kernels hanging around than the other libraries, is there any way to avoid loading them, or compile it with some of them disabled?

**Comment by lironmo** [comment] 2019-10-19 17:06
@IouJenLiu, no - we had to switch to different framework.

**Comment by SamNPowers** [comment] 2020-04-15 06:11
This seems like an enormous issue. I'm trying to run my network (using shared memory) on many environments in parallel, but I'm bottlenecked by the fact that each process is allocating vastly more gpu space than it needs. 

Could there be basically a simple interface to [cuCtxSetLimit](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__CTX.html#group__CUDA__CTX_1g0651954dfb9788173e60a9af7201e65a)? or perhaps cudaDeviceSetLimit as referenced in the stackoverflow link posted above?

If those aren't feasible for some reason, I strongly vote for having an option to compile kernels on the fly. 

This is a large enough issue that I may need to consider other frameworks, even though I really like every other aspect of pytorch, and would be very disappointed to have to switch.

**Comment by andyljones** [comment] 2020-04-15 06:47
I suspect that calling `cuCtxSetLimit` with a value below 800MB would just make PyTorch crash with an OOM exception the moment it's initialized.

After running into this back in Oct, I experimented with other libraries but found that for the architecture I had in mind, neither the 5-odd processes PyTorch can reasonably fit into memory nor the 25-odd processes that Tensorflow can were enough to saturate compute. I ended up being pushed into a GPU-server setup where my actors ship experience through shared memory to the single GPU process.

(And when that still wasn't fast enough, I adapted the environment to release the GIL so I could stick them on threads rather than processes. And then when _that_ wasn't fast enough, I finally rewrote the entire env to be vectorized. I don't know how helpful these specific solutions will be to you, but it's more to say: yup, this is tricky)

**Comment by SamNPowers** [comment] 2020-04-15 07:46
Thanks for the quick reply! ~5 processes sounds consistent with what I'm doing as well, so it's good to know that about 5x is what I could expect from tensorflow. 

I'm thinking through solutions similar to what you suggested. It will be tricky, indeed.

**Comment by Patrick-Gourdet** [comment] 2020-08-11 10:17
I am a bit late to the game, but to answer why a GPU takes up so much Memory can be explained with a fundamental algorithmic theorem. It is called the "Space-Time Tradeoff." Assuming this holds, viewing the tremendous speed up that GPUs provide, we can extrapolate the immense amount of Memory needed to support it.

**Comment by lamhoangtung** [comment] 2020-09-16 13:55
Agree with @SamNPowers. The memory problem are soo bad that we may need to consider other frameworks. I really like every other aspect of pytorch, including TorchScript for production. I thought by using libtorch on C++ would somewhat can reduce the memory consumption but turn out it doesn't. 

I really wish that we could have an option to compile the kernels on-the-fly when needed @colesbury. Even if it only work with TorchScript interpreter that would be the game changing for many of us.

**Comment by bwesen** [comment] 2022-07-03 15:52
This issue discusses python multiprocessing, but I found that just spawning a Thread (using the python threading package) in my python program and calling pytorch from it, makes my program hit CUDA OOM as compared to calling pytorch in the main program.

Is my behaviour related to this same issue?

I.e. spawning the sub-thread might allocate another 800MB of GPU VRAM?

I thought the python threading module uses the global lock and doesn't in fact result in multiple OS-level processes like the multiprocessing module would do, but maybe the threading module causes this behaviour as well...
