### ISSUE TITLE
Find way to add comments to merge_rules json

### ISSUE THREAD

**Issue by b0noI** [pytorch/pytorch#83441] opened 2022-08-15 18:42 UTC
For some of the cases of merge_rules we have special cases (like pin XLA hash), we need to have to add comment in JSON to outline root cause why we have special cases like XLA hash otherwise we might attempt to merge special cases back to the generic rules (already been attempted).

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by ZainRizvi** [comment] 2022-08-15 23:10
An option: 
https://github.com/pytorch/pytorch/blob/75a73a906f598b5285d0a834b2fe2a02b22a0e64/tools/linter/adapters/s3_init_config.json

It's hacky but it works if there's no parser that barfs at extra parameters

**Comment by malfet** [comment] 2022-08-15 23:34
json does not have a comment section, by design, we can easily extend our parser to accept it, or use [JSON5](https://json5.org/)

**Comment by seemethere** [comment] 2022-08-15 23:49
Why not just use YAML in this case then? I feel like YAML would just be better to use if we want to have comments

**Comment by ZainRizvi** [comment] 2022-08-15 23:59
> json does not have a comment section, by design, we can easily extend our parser to accept it, or use [JSON5](https://json5.org/)

Looks like json5 only works for javascript though, right? We prob want to stick with something our usual languages can all parse

**Comment by clee2000** [comment] 2024-03-18 21:05
Fixed by #84065, closing

**Closed by clee2000** 2024-03-18 21:05 UTC
Labels: module: ci, triaged
