### ISSUE TITLE
torch.Tensor not creating tensor on cuda

### ISSUE THREAD

**Issue by ksurya** [pytorch/pytorch#12432] opened 2018-10-07 07:01 UTC
## 🐛 Bug

`torch.Tensor` is creating tensor only on CPU. The `device` argument isn't working

## To Reproduce

<img width="704" alt="screen shot 2018-10-07 at 2 58 28 am" src="https://user-images.githubusercontent.com/932927/46579323-e5c9dd00-c9dc-11e8-93e6-5ee08db479ec.png">

## Expected behavior

`torch.Tensor` should create tensor on `cuda:0` device

## Environment

Google Colaboratory + Python 3 + GPU

Collecting environment information...
PyTorch version: 0.4.1
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 17.10
GCC version: (Ubuntu 7.2.0-8ubuntu3.2) 7.2.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Tesla K80
Nvidia driver version: 384.111
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect

**Comment by vishwakftw** [comment] 2018-10-07 08:28
This is a duplicate of https://github.com/pytorch/pytorch/issues/11427 and has been fixed on master via https://github.com/pytorch/pytorch/pull/11669 .

The recommended way to create tensors on devices is using `torch.tensor(..., device=required_device)`.

**Comment by fmassa** [comment] 2018-10-07 18:15
Yes, @vishwakfw is right. The `torch.Tensor` construct is legacy, and we should prefer `torch.tensor` or `torch.empty` instead

**Comment by fmassa** [comment] 2018-10-07 18:17
You can obtain a version with the fix by installing the nightly package

**Closed** 2018-10-07 18:16 UTC
