### ISSUE TITLE
[feature request] F.interpolate to support 1d signals out of the box

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#33071] opened 2020-02-07 00:24 UTC
For audio / scalar time series / 1d signals of shapes T or BxT, one currently has to unsqueeze at least to 3d tensor and then squeeze back.

With PyTorch now used for everything and not just imaages, easy support for 1d signals would be great!

**Comment by fmassa** [comment] 2020-02-10 11:27
This is a duplicate of https://github.com/pytorch/pytorch/issues/10482

**Closed by fmassa** 2020-02-10 11:27 UTC
