### ISSUE TITLE
`torch.asarray` does not detect dtype of Python scalars

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#70591] opened 2022-01-04 07:36 UTC
```python
import torch

for obj in (True, 1, 1.0):
    print(f"{obj} -> {torch.asarray(obj).dtype}")
```

```
True -> torch.float32
1 -> torch.float32
1.0 -> torch.float32
```

The [documentation](https://pytorch.org/docs/master/generated/torch.asarray.html) does not mention support for Python scalars, but since the function doesn't bail out, the behavior shown above is at least unexpected. 

`torch.asarray` was added in #60627 and specifically mentions the array API standard for compatibility, but this [defines behavior for scalars](https://data-apis.org/array-api/latest/API_specification/creation_functions.html?highlight=asarray#asarray-obj-dtype-none-device-none-copy-none).

cc @gchanan @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi

**Comment by ysiraichi** [comment] 2022-01-04 08:46
Nice catch! As far as I could see, the problem is that we are unconditionally casting the output tensor into the default dtype. I think this can be fixed by conditioning this cast to whether the user explicitly specified the dtype or not.

https://github.com/pytorch/pytorch/blob/d9106116aa5e399f7d63feeb7fc77f92a076dd93/torch/csrc/utils/tensor_new.cpp#L1165-L1167

**Comment by mruberry** [comment] 2022-01-11 17:09
What is the table of what NumPy does and the Python Array API specifies for this operation?

We would probably accept a PR updating PyTorch's `asarray` to be consistent with them (so long as they agree) on scalars (modulo PyTorch's default float datatype being distinct from NumPy's).

**Comment by rgommers** [comment] 2022-01-11 17:51
The rules should be:
- Python `bool` -> `torch.bool`
- Python `int` -> default integer dtype: `torch.int64`
- Python `float` -> default floating point dtype: `torch.float32`

It should match what `as_tensor` already does.

**Closed** 2022-02-02 15:57 UTC
Labels: triaged, module: tensor creation, module: python array api
