### ISSUE TITLE
Loading cudnn network

### ISSUE THREAD

**Issue by Anmol6** [pytorch/pytorch#791] opened 2017-02-20 00:25 UTC
Hi,
What's the best way to load a neural network that uses cudnn?

I heard 'load_lua' doesn't work for cudnn (https://discuss.pytorch.org/t/convert-import-torch-model-to-pytorch/37/12).

**Comment by apaszke** [comment] 2017-02-20 00:52
Convert it to a non-cuDNN network in Lua first. Then use `load_lua`.

Please use [our forums](discuss.pytorch.org) for questions. GitHub issues are for feature requests and bugs only. This is a duplicate of #302.

**Closed by apaszke** 2017-02-20 00:52 UTC
