### ISSUE TITLE
print(x.grad) hang in autograd tutorial

### ISSUE THREAD

**Issue by arisliang** [pytorch/pytorch#37997] opened 2020-05-07 05:13 UTC
In the autograd tutorial, https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html

>print(x.grad)

gives output:
>tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

but it hangs afterwards.

pytorch version: 1.5.0
python: 3.7.7
OS: windows 7

cc @ezyang @SsnL @albanD @zou3519 @gqchen @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment] 2020-05-07 06:27
Seems to be the same one as https://github.com/pytorch/pytorch/issues/37997.

**Comment by agolynski** [comment] 2020-05-07 14:34
> Seems to be the same one as #37997.

@peterjc123 did you mean to cite a different issue?

**Comment by peterjc123** [comment] 2020-05-07 15:27
@agolynski Or sorry, it should be https://github.com/pytorch/pytorch/issues/29383.

**Comment by albanD** [comment] 2020-05-07 16:11
Given it is the same OS version and the same symptoms, I'm going to close this as a duplicate of #29383.
You can move anu further question to that issue.

**Closed by albanD** 2020-05-07 16:11 UTC
Labels: module: autograd, module: windows, triaged
