### ISSUE TITLE
AOT autograd - incorrect functionalization when requires_grad = False

### ISSUE THREAD

**Issue by karthiknagasub** [pytorch/pytorch#92129] opened 2023-01-13 03:17 UTC
### 🐛 Describe the bug

AOT autograd functionalizes the views correctly only if at least one of the input tensors is having required_grad == True.

In [pytorch/aot_autograd.py at master · pytorch/pytorch · GitHub](https://github.com/pytorch/pytorch/blob/master/torch/_functorch/aot_autograd.py)
if needs_autograd:
compiler_fn = aot_dispatch_autograd → This functionalizes the views correctly
else:
compiler_fn = aot_dispatch_base → This is resulting in incorrect view handling

Example:
``` Python
import torch
from functorch.compile import aot_function

def fn(a, b):
e = a[:]
e = a.as_strided([2, 2], [4, 2], 0)
e.add_(1.0)
a.mul_(2.0)
e[2:-1] = 3.0
return e[1::2]


def compiler_fn(fx_module: torch.fx.GraphModule, _):
print(fx_module.code)
return fx_module

aot_print_fn = aot_function(fn, fw_compiler=compiler_fn, bw_compiler=compiler_fn)

a = torch.randn(2, 4, requires_grad=False)
b = torch.randn(2, 4, requires_grad=True)
res = aot_print_fn(a, b)
```
Output:
``` Bash
def forward(self, primals_1, primals_2):
clone = torch.ops.aten.clone.default(primals_1); primals_1 = None
as_strided = torch.ops.aten.as_strided.default(clone, [2, 2], [4, 2], 0)
add = torch.ops.aten.add.Tensor(as_strided, 1.0); as_strided = None
as_strided_scatter = torch.ops.aten.as_strided_scatter.default(clone, add, [2, 2], [4, 2], 0); clone = add = None
mul = torch.ops.aten.mul.Tensor(as_strided_scatter, 2.0); as_strided_scatter = None
_tensor_constant0 = self._tensor_constant0
lift_fresh_copy = torch.ops.aten.lift_fresh_copy.default(_tensor_constant0); _tensor_constant0 = None
as_strided_2 = torch.ops.aten.as_strided.default(mul, [2, 2], [4, 2], 0)
slice_3 = torch.ops.aten.slice.Tensor(as_strided_2, 0, 2, -1); as_strided_2 = None
fill = torch.ops.aten.fill.Tensor(slice_3, lift_fresh_copy); slice_3 = lift_fresh_copy = None
as_strided_3 = torch.ops.aten.as_strided.default(mul, [2, 2], [4, 2], 0)
slice_scatter = torch.ops.aten.slice_scatter.default(as_strided_3, fill, 0, 2, -1); as_strided_3 = fill = None
as_strided_scatter_1 = torch.ops.aten.as_strided_scatter.default(mul, slice_scatter, [2, 2], [4, 2], 0); mul = slice_scatter = None
return [as_strided_scatter_1, 0, 2, 8, 2, 4]
```
Now if we change `b = torch.randn(2, 4, requires_grad=False) (True → False)`

output becomes:
```Bash
def forward(self, arg0_1, arg1_1):
slice_1 = torch.ops.aten.slice.Tensor(arg0_1, 0, 0, 9223372036854775807)
as_strided = torch.ops.aten.as_strided.default(arg0_1, [2, 2], [4, 2], 0)
add_ = torch.ops.aten.add_.Tensor(as_strided, 1.0); as_strided = None
mul_ = torch.ops.aten.mul_.Tensor(arg0_1, 2.0); arg0_1 = None
tensor_constant0 = self.tensor_constant0
lift_fresh_copy = torch.ops.aten.lift_fresh_copy.default(tensor_constant0); tensor_constant0 = None
slice_2 = torch.ops.aten.slice.Tensor(add, 0, 2, -1)
fill = torch.ops.aten.fill.Tensor(slice_2, lift_fresh_copy); slice_2 = lift_fresh_copy = None
slice_3 = torch.ops.aten.slice.Tensor(add, 0, 1, -1, 2); add_ = None
return [slice_3]
```
In the second case, the generate code is functionally incorrect

Question:
Why not make aot_dispatch_autograd the default/only option as it seem to functionalize views correctly?

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230110+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.3 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.23.3
Libc version: glibc-2.31

Python version: 3.8.15 (default, Nov 24 2022, 15:19:38)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-126-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.24.1
[pip3] pytorch-ranger==0.1.1
[pip3] torch==2.0.0.dev20230110+cpu
[pip3] torch-optimizer==0.0.1a15
[pip3] torchaudio==2.0.0.dev20230110+cpu
[pip3] torchmetrics==0.9.3
[pip3] torchvision==0.15.0.dev20230110+cpu
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] torch                     2.0.0.dev20230110+cpu          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230110+cpu          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230110+cpu          pypi_0    pypi

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ngimel** [comment] 2023-01-13 05:13
Duplicate of #90759

**Closed by ngimel** 2023-01-13 05:13 UTC
Labels: oncall: pt2
