### ISSUE TITLE
Disabled test_udf_remote_message_delay_timeout_to_self (__main__.FaultyAgentRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#41019] opened 2020-07-06 17:32 UTC
https://app.circleci.com/pipelines/github/pytorch/pytorch/187910/workflows/48b2adf2-4780-498c-97e7-b81aeffab49f/jobs/6117749/steps

```
Jul 05 00:36:45 ======================================================================
Jul 05 00:36:45 ERROR [23.394s]: test_udf_remote_message_delay_timeout_to_self (__main__.FaultyAgentRpcTestWithSpawn)
Jul 05 00:36:45 ----------------------------------------------------------------------
Jul 05 00:36:45 Traceback (most recent call last):
Jul 05 00:36:45   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 204, in wrapper
Jul 05 00:36:45     self._join_processes(fn)
Jul 05 00:36:45   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 311, in _join_processes
Jul 05 00:36:45     self._check_return_codes(elapsed_time)
Jul 05 00:36:45   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 344, in _check_return_codes
Jul 05 00:36:45     raise RuntimeError(error)
Jul 05 00:36:45 RuntimeError: Processes 0 exited with error code 10
```

```
Jul 05 00:36:22   test_udf_remote_message_delay_timeout_to_self (__main__.FaultyAgentRpcTestWithSpawn) ... ERROR:root:Caught exception: 
Jul 05 00:36:22 Traceback (most recent call last):
Jul 05 00:36:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 207, in wrapper
Jul 05 00:36:22     fn()
Jul 05 00:36:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 93, in new_test_method
Jul 05 00:36:22     return_value = old_test_method(self, *arg, **kwargs)
Jul 05 00:36:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 3575, in test_udf_remote_message_delay_timeout_to_self
Jul 05 00:36:22     self._test_remote_message_delay_timeout(func, args, dst=0)
Jul 05 00:36:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 3563, in _test_remote_message_delay_timeout
Jul 05 00:36:22     wait_until_owners_and_forks_on_rank(1, 0, rank=dst_rank)
Jul 05 00:36:22   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 262, in wait_until_owners_and_forks_on_rank
Jul 05 00:36:22     num_owners, num_forks, num_owners_on_rank, num_forks_on_rank
Jul 05 00:36:22 ValueError: Timed out waiting for 1 owners and 0 forks on rank, had 0 owners and 0 forks
Jul 05 00:36:22 exiting process with exit code: 10
Jul 05 00:36:23 ERROR (23.394s)
```

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar @jiayisuse

**Comment by rohan-varma** [comment] 2020-07-09 20:28
This seems like a legit error, although I tried running the test 1000 times and it didn't reproduce on my devserver.

**Comment by rohan-varma** [comment] 2020-07-09 23:34
Looks like it reproduces with TSAN.

**Comment by rohan-varma** [comment] 2020-07-20 23:02
Fixed by https://github.com/pytorch/pytorch/pull/41217

**Closed by rohan-varma** 2020-07-20 23:02 UTC
Labels: high priority, module: rpc, topic: flaky-tests, triage review, triaged
