### ISSUE TITLE
FAIL: test_numpy_array_interface 

### ISSUE THREAD

**Issue by snjagadale** [pytorch/pytorch#3277] opened 2017-10-25 04:08 UTC
Ported pytorch on Power Architecture. 
While executing test case found following error:

```
Running torch tests
/Pytorch/pytorch/test/common.py:211: RuntimeWarning: overflow encountered in ubyte_scalars
  self.assertLessEqual(abs(x - y), prec, message)
======================================================================
FAIL: test_numpy_array_interface (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4349, in test_numpy_array_interface
    self.assertEqual(asarray[i], wrapped_x[i])
  File "/home/aditi/Pytorch/pytorch/test/common.py", line 215, in assertEqual
    super(TestCase, self).assertEqual(x, y, message)
AssertionError: 0 != 254
----------------------------------------------------------------------
Ran 217 tests in 1.275s
```

Single test failed. Please help to understand the reason. We are running it on CPU only, RHEL OS.

**Comment by apaszke** [comment] 2017-10-25 08:33
```
/Pytorch/pytorch/test/common.py:211: RuntimeWarning: overflow encountered in ubyte_scalars
```
is not printed by PyTorch. This is likely the reason why you're seeing this. Add `print(asarray[i], wrapped_x[i])` before [this line](https://github.com/pytorch/pytorch/blob/master/test/test_torch.py?utf8=✓#L4349) and make sure the outputs match

**Comment by snjagadale** [comment] 2017-10-25 11:15
python test_torch.py
.........................ss.....s......sss.................s.......s........ss.s...........s........................................(1, 1)
(0, 254)
/Pytorch/pytorch/test/common.py:211: RuntimeWarning: overflow encountered in ubyte_scalars
  self.assertLessEqual(abs(x - y), prec, message)
F....sss..ss....ss.....................s................ss...........s.........ss..ss
======================================================================
FAIL: test_numpy_array_interface (__main__.TestTorch)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_torch.py", line 4350, in test_numpy_array_interface
    self.assertEqual(asarray[i], wrapped_x[i])
  File "/home/aditi/Pytorch/pytorch/test/common.py", line 215, in assertEqual
    super(TestCase, self).assertEqual(x, y, message)
AssertionError: 0 != 254

**Comment by apaszke** [comment] 2017-10-25 11:28
Can you `print(wrapped_x)` as well?

**Comment by sudarshanpsl** [comment] 2017-10-26 08:25
[root@pts00606-vm21 test]# python test_torch.py
.........................ss.....s......sss.................s.......s........ss.s...........s........................................(1, 1)
[  1 254   3 252]
(0, 254)
[  1 254   3 252]
/Pytorch/pytorch/test/common.py:211: RuntimeWarning: overflow encountered in ubyte_scalars
  self.assertLessEqual(abs(x - y), prec, message)
F....sss..ss....ss.....................s................ss...........s.........ss..ss
======================================================================
FAIL: test_numpy_array_interface (__main__.TestTorch)
----------------------------------------------------------------------

**Comment by apaszke** [comment] 2017-10-26 11:04
Alright, next experiment. Run this in your shell:
```python
wrapped_x = np.array([1, -2, 3, -4], dtype=dtype)
print(wrapped_x)
print(wrapped_x[1])
```

**Comment by sudarshanpsl** [comment] 2017-10-26 12:35
>>> import numpy as np
>>> wrapped_x=np.array([1, -2, 3, -4], dtype='int32')
>>> print(wrapped_x)
[ 1 -2  3 -4]
>>> print(wrapped_x[1])
-2

**Comment by apaszke** [comment] 2017-10-26 13:09
Ah, my bad. It was important that `dtype` should be `uint8`

**Comment by aditijadhav38** [comment] 2017-10-27 05:49
import numpy as np
wrapped_x=np.array([1, -2, 3, -4], dtype='uint8')
print(wrapped_x)
[  1 254   3 252]
print(wrapped_x[1])
254

**Comment by apaszke** [comment] 2017-10-27 17:21
Ok, that's weird. I'm running out of ideas. I'd need to poke around myself, but I don't have a POWER machine

**Comment by avmgithub** [comment] 2017-10-31 19:35
hi, it looks like there is something going on when passing torch tensor to numpy.  
Here is a sample code

import torch
import numpy as np

dtype = np.uint8 
x = torch.Tensor([1, -2, 3, -4])
asarray = np.asarray(x, dtype=dtype)
print ("asarray", asarray)
np_array = np.array(x, dtype=dtype)
print ("array x from torch", np_array)
array = np.array([1, -2, 3, -4], dtype=dtype)
print ("array x not from torch", array)

output
<class 'numpy.uint8'>
asarray [1 0 3 0]
array x from torch [1 0 3 0]
array x not from torch [  1 254   3 252]

If you can give me some suggestions on which code to look in  pytorch, I can try and help

**Comment by avmgithub** [comment] 2017-10-31 19:44
Some additional data.
The line  x = torch.Tensor([1, -2, 3, -4])   seems to default to [torch.FloatTensor of size 4]
>>> import torch
>>> x = torch.Tensor([1, -2, 3, -4])
>>> x

 1
-2
 3
-4
[torch.FloatTensor of size 4]

If I changed that line to be 
x = torch.ByteTensor([1, -2, 3, -4])  when testing with dtype  np.uint8
the test passes

**Comment by apaszke** [comment] 2017-11-01 10:39
That's really helpful. The code for numpy conversions is [here](https://github.com/pytorch/pytorch/blob/master/torch/tensor.py#L398-L402), and `numpy()` method is [here](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/methods/TensorSerialization.cwrap#L54-L122).

**Comment by avmgithub** [comment] 2017-11-04 12:37
I've been looking at this on and off and I can't seem to figure out where the problem is.  All the method does is create a new array object with the type of the original torch tensor and passes it on to numpy astype.  But I did also find that if I used x = torch.IntTensor([1, -2, 3, -4]) , it also passes.   I also changed to using numpy 1.13.3 but that did not help.  When I try to add casting='safe' to the astype I get an error that the casting is not safe going from float to uint8.   Unfortunately I do not have an x86 system to experiment.

**Comment by avmgithub** [comment] 2017-11-04 17:27
I think this test depending on which architecture you run x86 vs ppc64 or ARM will result in undefined behavior.  See this link http://www.embeddeduse.com/2013/08/25/casting-a-negative-float-to-an-unsigned-int/.  
Also I tried doing the following on ppc64le 
>>> x = np.array([1.,-2.])
>>> x
array([ 1., -2.])
>>> y = x.astype(np.uint8)
>>> y
array([1, 0], dtype=uint8)
So even numpy gives back a 0 when casting a negative float to unit8

**Comment by apaszke** [comment] 2017-11-04 20:39
Thanks a lot for investigating that. Today I learned that casting integral types to unsigned integral types is always well defined (in modulo arithmetic), but in case of floating point types you can cast it to any integral type, but result is only well defined if it can be represented as a truncated value (even when the destination type is unsigned!!!). An excerpt from C++ standard:

> #### Floating–integral conversions
> ...
> If the value cannot fit into the destination type, the behavior is undefined (even when the destination type is unsigned, modulo arithmetic does not apply).
> ...

To sum up, the test is incorrect. Can you please send a PR making it ignore these floating point -> unsigned conversions, but do additional integral -> unsigned to make sure that works?

**Comment by mruberry** [comment] 2020-05-05 23:30
Closing due to age. If this is still an issue please reopen.

**Closed by mruberry** 2020-05-05 23:30 UTC
