### ISSUE TITLE
[Feature request] Batch linear algebra operators

### ISSUE THREAD

**Issue by gpleiss** [pytorch/pytorch#7500] opened 2018-05-11 14:19 UTC
It would be awesome if there were batched versions of `potrf`, `potrs`, `potri`, and `qr`. The batch Cholesky functions would be useful in [`MultivariateNormal`](https://github.com/pytorch/pytorch/blob/master/torch/distributions/multivariate_normal.py#L41), which currently uses a for loop to compute a batch of Cholesky decompositions.

It looks like Magma has batched versions of these functions. Lapack does not, but the Lapack version of this function could always use a for-loop internally.

Open to a PR?
/cc @vishwakftw @SsnL @jacobrgardner

Edit: and batched matrix inverse
Edit [vishwakftw]: Added a checklist

- [x] `solve` a.k.a. `gesv` (#6100)
- [x] `inverse` (#9949)
- [x] `cholesky_solve` a.k.a `potrs` (#13453)
- [x] `cholesky` a.k.a `potrf` (#14017)
- [x] `lu` a.k.a `btrifact` (#14964)
- [x] `triangular_solve` a.k.a `trtrs` (#18025)
- [x] `qr` (#20689)
- [ ] `lstsq` a.k.a `gels`
- [x] `lu_solve` a.k.a `btrisolve` (#24333)
- [x] `svd` (#21588)
- [ ] `cholesky_inverse` a.k.a `potri` (#31275)
- [x] `det` / `logdet` / `slogdet` (#22909)
- [x] `symeig` (#21858)
- [x] `pinverse` (#26095)

**Comment by zou3519** [comment] 2018-05-11 15:00
Definitely open to a PR.  See [gesv](https://github.com/pytorch/pytorch/pull/6100/files) as an example of a non-batched operation that we added batch support for.

**Comment by vadimkantorov** [comment] 2018-07-27 14:24
Let's add batched matrix `inverse()` to the top post to not forget it? @soumith

**Comment by fmassa** [comment] 2018-07-27 14:42
There is a PR open for batches inverse, right? @vadimkantorov could you maybe have a look and review it?

**Comment by fmassa** [comment] 2018-07-27 14:51
I was referring to https://github.com/pytorch/pytorch/pull/9102
It actually requires some work left, but might be a good starting point

**Comment by vishwakftw** [comment] 2018-07-28 14:09
@fmassa I have got one completed. I was unaware of #9102 unfortunately.

**Comment by samuela** [comment] 2018-09-03 20:01
This issue is huge for me. My life would be way easier if everything just had batching by default. And ideally for arbitrary batch shapes, as in `torch.potrf` accepts [2, 3, 5, 5] just as well as [6, 5, 5].

**Comment by vishwakftw** [comment] 2018-10-28 17:08
@vidhishanair Batched Inverse is available in master now.

**Comment by vidhishanair** [comment] 2018-10-30 11:16
> @vidhishanair Batched Inverse is available in master now.

Thanks @vishwakftw  This greatly helps 👍 I'll use it in my model and update if there's any discrepency!

**Comment by carlosgmartin** [comment] 2018-11-05 02:06
Can `torch.det` be added to this list?

**Comment by vishwakftw** [comment] 2018-11-06 09:46
`torch.slogdet` should be able to give you the determinant. However, certain modifications (minor, I think) have to be made to enable batching for `torch.slogdet` and `torch.logdet`. I'll try to get it done in a few days.

**Comment by el3ment** [comment] 2018-11-11 17:43
By way of update, it looks like @vishwakftw finished batched `potrs` and it was merged into master a few days ago! Thanks!

**Comment by vishwakftw** [comment] 2018-11-17 19:05
Update: batched cholesky is merged into master.

**Comment by JurijsNazarovs** [comment] 2019-02-22 06:10
Since torch.det might be updated, I would also like to see torch.logdet.

**Comment by vishwakftw** [comment] 2019-02-22 06:15
Yes, this should be done once #14964 is merged into master.

**Comment by SergioRAgostinho** [comment] 2019-06-14 12:49
Request for  `torch.trace`.

**Comment by vishwakftw** [comment] 2019-06-14 14:07
torch.trace should be simple. A sample implementation is:

```
def trace(A):
    return A.diagonal(dim1=-2, dim2=-1).sum(-1)
```

**Comment by kefirski** [comment] 2019-06-19 10:09
Hi, @vishwakftw, Is there any ETA on adding batched det/logdet operations?

**Comment by vishwakftw** [comment] 2019-06-19 10:31
It should be done by the end of the month. The only thing hindering batched det / logdet / slogdet is the backward pass which requires batched SVD.

**Comment by Gsunshine** [comment] 2019-06-30 11:52
The end of the month! @vishwakftw 
We really need batched det/logdet/slogdet!
thx!

**Comment by vishwakftw** [comment] 2019-06-30 12:34
Thanks for your interest. An implementation of batch SVD is available in #21858, but it is a work in progress. Once this is done, the rest should follow.

**Comment by vishwakftw** [comment] 2019-07-05 13:46
While we don't have batched support for det / logdet / slogdet in the master branch just yet, please feel free to use [vishwakftw:batch-svd](https://github.com/vishwakftw/pytorch/tree/batch-svd) and [vishwakftw:batch-det-logdet-slogdet](https://github.com/vishwakftw/pytorch/tree/batch-det-logdet-slogdet). This combination of these two branches should effectively give you tentative support.

**Comment by calincru** [comment] 2019-07-09 14:35
> While we don't have batched support for det / logdet / slogdet in the master branch just yet, please feel free to use [vishwakftw:batch-svd](https://github.com/vishwakftw/pytorch/tree/batch-svd) and [vishwakftw:batch-det-logdet-slogdet](https://github.com/vishwakftw/pytorch/tree/batch-det-logdet-slogdet). The combination of these two branches should effectively give you tentative support.

Can you estimate when they'll be merged onto master?

**Comment by vishwakftw** [comment] 2019-07-09 15:13
I am not sure. I hope to have it reviewed and merged before the next release comes out.

**Comment by calincru** [comment] 2019-07-14 14:27
When is the next release scheduled for?  Sorry if this is mentioned somewhere, I couldn't find it.

**Comment by calincru** [comment] 2019-07-14 14:38
> torch.trace should be simple. A sample implementation is:
> 
> ```
> def trace(A):
>     return A.diagonal(dim1=-2, dim2=-1).sum(-1)
> ```

Just curious, why not implement it, though?  It's nice that it can be obtained pretty easily with the current features, but it would help readability and UX in general.

**Comment by vishwakftw** [comment] 2019-07-31 17:08
We have support for batched det / logdet / slogdet in master.

**Comment by yang-song** [comment] 2019-09-04 04:46
It would be great if batched `pinverse` can be added.

**Comment by vishwakftw** [comment] 2019-09-22 22:49
@yang-song batched `pinverse` has been added and is available in the nightly releases.

**Comment by Balandat** [comment] 2020-01-25 02:09
What's the status on batched `cholesky_inverse`? Would be nice to be able to use this.

**Comment by vishwakftw** [comment] 2020-01-25 02:12
During benchmarking, I saw a regression for small batch sizes. The PR is usable however.

I’m pretty occupied until the first week of February, so I won’t be able to take address that until then unfortunately.

**Comment by Lezcano** [comment] 2022-01-13 17:52
If I'm not mistaken, we currently support batches in all the linalg functions, so this one can go 🥳

**Closed by Lezcano** 2022-01-13 17:52 UTC
Labels: todo, triaged, module: linear algebra
