### ISSUE TITLE
torch.sum (used in Expand.backward) is slow

### ISSUE THREAD

**Issue by shawnjhenry** [pytorch/pytorch#700] opened 2017-02-08 14:42 UTC
Hi,

I'm trying to build a recurrent net which, instead of using the last hidden state, computes bilinear attention over the last k hidden states.  I have it implemented as a module as follows:
```
import torch as th

from torch.nn import Module, Parameter

from torch.autograd import Variable, Function

from torch.nn.functional import relu, softmax


class LocalRNN(Module):

	def __init__(self, window_size, hidden_size):
		super(LocalGlobalRNN, self).__init__()

		self.window_size = window_size
		self.hidden_size = hidden_size

		self.att_W = Parameter(th.Tensor(1, hidden_size, hidden_size))

		self.i2h_W = Parameter(th.Tensor(hidden_size, hidden_size))
		self.h2h_W = Parameter(th.Tensor(hidden_size, hidden_size))

		self.i2h_b = Parameter(th.Tensor(hidden_size))
		self.h2h_b = Parameter(th.Tensor(hidden_size))

		self.reset()

	def reset(self):
		stdv = np.sqrt(2.0/self.hidden_size)

		self.att_W.data.uniform_(-stdv, stdv)

		self.i2h_W.data.uniform_(-stdv, stdv)
		self.h2h_W.data.uniform_(-stdv, stdv)

		self.i2h_b.data.uniform_(-stdv, stdv)
		self.h2h_b.data.uniform_(-stdv, stdv)

		return self

	def forward(self, input, window=None):
		seq_length, batch_size, hidden_size = input.size()

		add_buffer = Variable(input.data.new(batch_size).fill_(1))

		output = []

		if window is None:
			window = [Variable(input.data.new(batch_size, 1, hidden_size).zero_())]*self.window_size

		for t in range(seq_length):
			x_t = input[t]

			w_t = th.cat(window[-self.window_size:], 1)

			att_W = self.att_W.expand(batch_size, hidden_size, hidden_size)

			h_tm1 = th.bmm(softmax(th.bmm(w_t, th.bmm(att_W, x_t.unsqueeze(2)))).transpose(1, 2), w_t).squeeze()

			h_t = relu(th.mm(x_t, self.i2h_W).addr_(add_buffer, self.i2h_b).addmm(h_tm1, self.h2h_W).addr_(add_buffer, self.h2h_b))

			output.append(h_t.unsqueeze(0))
			window.append(h_t.unsqueeze(1))

		output = th.cat(output)

		return output
```
With an input of size 100 x 50 x 512 (batch_first=False) forward prop takes ~0.6 s, but for some reason autograd back prop takes ~16 s, over 20x longer!  Am I using autograd incorrectly (I'm just stacking this module with other modules) or is this a bug?  How do I profile the backward graph to find the bottleneck?

**Comment by csarofeen** [comment] 2017-02-08 17:05
Do you ever clear your window variable? Otherwise it will accumulate history every time you call forward and when you call backward it will back over the entire history of training, not just the last time you called forward. If you need the information in window from one iteration to the next you can simply re-wrap it in a variable. I'm also wondering why you put window in a list of tensors instead of adding another dim to window.

**Comment by shawnjhenry** [comment] 2017-02-08 17:18
Why would `window` accumulate over training?  It's not returned by `forward`, it's either created and passed in for each batch, or created in the `forward` call.  I used a list of tensors because that turned out to be faster than narrowing and concatenating in each time step by a small amount.  That shouldn't be relevant - that's how the standard RNN implementation collects the outputs. 

Anyway, I'm talking about a single forward and backward call.  For any network those are expected to take the same order of magnitude amount of time.  If I push the hidden size high enough, back prop can take 100 x longer than forward prop, which means that either I'm doing something wrong or there is a bug.

**Comment by csarofeen** [comment] 2017-02-08 17:23
Could you include a dummy training script?

**Comment by shawnjhenry** [comment] 2017-02-08 17:30
This isn't a functional net, but it'll show the issue:
```
import torch as th

import torch.nn as nn
import torch.optim as optim

from torch.autograd import Variable

from torch.nn.functional import log_softmax, nll_loss


class Net(nn.Module):

	def __init__(self):
		super(Net, self).__init__()

		self.rnn = LocalRNN(16, 512)
		self.lin = nn.Linear(512, 6)

	def forward(self, input, hx=None):
		hx = [Variable(th.zeros(50, 1, 512))]*16
		
		output = self.rnn(input, hx)
		output = th.sum(output, 0).squeeze()
		output = self.lin(output)
		output = log_softmax(output)

		return output 
		

model = Net()

optimizer = optim.SGD(model.parameters(), lr=0.001)

x = Variable(th.Tensor(100, 50, 512).normal_())
y = Variable(th.LongTensor([0, 1, 2, 4, 5]*10))

optimizer.zero_grad()

import time

timer = time.time()

output = model(x)

loss = nll_loss(output, y)

loss.backward()

optimizer.step()

timer = time.time()-timer 

print(timer)
```

**Comment by csarofeen** [comment] 2017-02-08 21:21
Looks like CPU version of expand and bmm cause serious slow downs in backward. Repro:
```
weight = Parameter(th.Tensor(1, 1024, 1024))
inp = Variable(th.randn(64,1024,1), requires_grad=True)
target = Variable(th.randn(64,1024,1))

for i in range(10):
    forward_start = time.time()
    output = th.bmm(weight.expand(inp.size(0), 1024, 1024), inp)
    print("forward time " + str ( time.time()-forward_start ) )
    
    crit = nn.MSELoss()
    target = Variable(th.randn(*output.size()))
    loss = crit(output, target)
    
    backward_start = time.time()
    d = loss.backward(retain_variables=True)
    print("backward time " + str ( time.time()-forward_start ) )

```

Cuda version does not show a slow-down.

**Comment by apaszke** [comment] 2017-02-08 21:23
@shawnjhenry Are you running with cuDNN? Can you disable it and see if that helps:
```python
torch.backends.cudnn.enabled = False
```

**Comment by ngimel** [comment] 2017-02-08 21:24
@apaszke that's custom RNN cell that's not accelerated by cudnn anyway.

**Comment by ngimel** [comment] 2017-02-08 21:27
@apaszke Please do.

**Comment by apaszke** [comment] 2017-02-08 21:36
As far as I remember using expand has some memory issues when used with CUDA. `repeat` would likely give better performance. I can't remember what was the cause of the slowdown. @soumith?

Apparently something similar happens on the CPU too (likely because of some cache issues). If I use `expand` I get 0.017s for forward and 1.455s for backward, if I switch it to `repeat(inp.size(0), 1, 1)` they take 0.186s and 0.519s respectively.

**Comment by csarofeen** [comment] 2017-02-08 21:39
Even without expand, and directly using a larger Parameter there was something on the order of 10x slowdown on backwards.

**Comment by apaszke** [comment] 2017-02-08 22:11
@csarofeen the snippet you've posted is very slow on CPU, but that's probably because of an extremely poor cache utilization - expand needs to sum along the first dimension, and the elements are exactly 4MB away. Still, it completes immediately on the GPU. I'm looking into it.

**Comment by apaszke** [comment] 2017-02-08 22:45
Ok, so the problem is that our CPU code for `sum` appears to have significant cache problems, and this slows down backward of `expand` a lot. On GPU, the whole network finishes forward in 0.28s and backward in 0.17s for me. We'll have to fix that, thanks for pointing it out.

A fix for now would be to replace
```python
th.bmm(weights.expand(...), input)
```
with
```python
th.stack([weight.mm(i) for i in input], 0)
```
where weights should be 2d now.

**Comment by shawnjhenry** [comment] 2017-02-09 18:39
Thanks all of you for checking this out.  Is `repeat` a newly added op?  I get an `AttributeError` when I try to run the suggested replacement.

**Comment by shawnjhenry** [comment] 2017-02-09 18:47
Hmm, now I have another issue - I tried to update PyTorch with pip to see if I can get `repeat` to work, and I get `ImportError: No module named 'tools.setup_helpers'`.  Any idea what that's about?  I checked the directory and `tools/setup_helpers` appears to be there...

**Comment by apaszke** [comment] 2017-02-09 19:10
Yeah it's been added after the release but I think it should be in the binaries already. Huh, no idea about that issue, what's the command you're running and can you please show me the stack trace?

**Comment by apaszke** [comment] 2017-02-09 19:37
Fun fact is that you've hit one of the slowest possible dim sizes. Just increasing the size of the last 2 dimensions to 1025 cuts down the execution time from 1.2s to 800ms. It's still slow, because the algorithm is quite dumb, but the original sizes cause a lot of cache misses.

**Comment by adamlerer** [comment] 2017-02-10 03:19
I think I know how to fix this cache problem for `sum` (and similarly for prod, max, min, etc.). I'll try to put together a PR in the next day or two.

**Comment by apaszke** [comment] 2017-02-10 08:03
For first dim it might be enough to sum the whole slices instead of iterating over the dimension. But I don't think that it solves the case for sum along second dim too.

**Comment by adamlerer** [comment] 2017-02-16 17:37
There's an outstanding PR that fixes this FYI

https://github.com/torch/torch7/pull/934

**Comment by soumith** [comment] 2017-02-28 23:26
this perf issue should now be fixed in master

**Closed by soumith** 2017-02-28 23:26 UTC
Labels: enhancement, high priority
