### ISSUE TITLE
Test case failed but test job passed.

### ISSUE THREAD

**Issue by mszhanyi** [pytorch/pytorch#47103] opened 2020-10-30 07:16 UTC
## 🐛 Bug

Test case failed but test job passed in windows CI.

## To Reproduce

1. Check  recent PR's ci report, pytorch_windows_vs2019_py36_cuda10.1_test1 passed but in fact there's always one test cases failed.
It's the example [link ](https://app.circleci.com/pipelines/github/pytorch/pytorch/233135/workflows/f5cf2f9d-3f45-45d7-ac3c-cd6d9e4860f4/jobs/8578221)

## Expected behavior

The test job of pytorch_windows_vs2019_py36_cuda10.1_test1 should be failed and block the PR into master.

cc @ezyang @seemethere @malfet @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by mszhanyi** [comment] 2020-10-30 07:55
The snapshot
![image](https://user-images.githubusercontent.com/16190118/97674327-506c7a80-1ac8-11eb-91ec-6022ab456178.png)

**Comment by walterddr** [comment] 2020-10-30 14:21
duplicate of https://github.com/pytorch/pytorch/issues/45864 ?

**Comment by mszhanyi** [comment] 2020-10-30 15:48
> duplicate of #45864 ?

Yes. Sorry, I didn't see it

**Closed** 2020-11-03 18:31 UTC
Labels: module: ci, module: windows, triaged, windows-triaged
