### ISSUE TITLE
FAILED Build:  __AVX2__ is defined (via e.g. -mavx2) "     "but CAFFE2_PERF_WITH_AVX2 is not defined.

### ISSUE THREAD

**Issue by dendisuhubdy** [pytorch/pytorch#13061] opened 2018-10-24 18:12 UTC
## 🐛 Bug

I found out the torch nightly builds are sufficient for my needs but I keep one separate virtual environment that makes sure that my DL research code is always on Pytorch's HEAD. Thus do a build of torch from scratch at least once every week but since last month I've always got this strange error when building. The full build log is here https://gist.github.com/dendisuhubdy/3cf00b9224acdb8fe43281d922d05bf8

The error part is here if that's TLDR

```
FAILED: caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx.dir/common_avx.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DONNX_NAMESPACE=onnx_torch -DUSE_GCC_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -I../aten/src -I. -I../ -I../third_party/protobuf/src -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../cmake/../third_party/eigen -isystem /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -isystem /Users/grokmachine/torch/lib/python3.7/site-packages/numpy/core/include -isystem /usr/local/include --std=c++11  -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -faligned-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -fPIC   -mavx -mf16c -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -std=gnu++11 -MD -MT caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx.dir/common_avx.cc.o -MF caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx.dir/common_avx.cc.o.d -o caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx.dir/common_avx.cc.o -c ../caffe2/perfkernels/common_avx.cc
../caffe2/perfkernels/common_avx.cc:17:2: error: (     "You found a build system error: __AVX__ is defined (via e.g. -mavx) "     "but CAFFE2_PERF_WITH_AVX is not defined.");
#error( \
 ^
1 error generated.
[943/1793] Building CXX object caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx2.dir/common_avx2.cc.o
FAILED: caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx2.dir/common_avx2.cc.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DONNX_NAMESPACE=onnx_torch -DUSE_GCC_ATOMICS=1 -D_FILE_OFFSET_BITS=64 -I../aten/src -I. -I../ -I../third_party/protobuf/src -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../cmake/../third_party/eigen -isystem /usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/include/python3.7m -isystem /Users/grokmachine/torch/lib/python3.7/site-packages/numpy/core/include -isystem /usr/local/include --std=c++11  -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -faligned-new -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.9 -fPIC   -mavx2 -mfma -mavx -mf16c -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -std=gnu++11 -MD -MT caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx2.dir/common_avx2.cc.o -MF caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx2.dir/common_avx2.cc.o.d -o caffe2/perfkernels/CMakeFiles/Caffe2_perfkernels_avx2.dir/common_avx2.cc.o -c ../caffe2/perfkernels/common_avx2.cc
../caffe2/perfkernels/common_avx2.cc:17:2: error: (     "You found a build system error: __AVX2__ is defined (via e.g. -mavx2) "     "but CAFFE2_PERF_WITH_AVX2 is not defined.");
#error( \
 ^
1 error generated.
[949/1793] Generating src/x86_64-fma/softmax.py.o
ninja: build stopped: subcommand failed.
Failed to run 'bash ../tools/build_pytorch_libs.sh --use-nnpack caffe2 libshm THD'
```

## To Reproduce

I'm on a Mac OS X Mojave, and I'm on an MBP 15" 2016.

1. cd `pytorch`
2. `MACOSX_DEPLOYMENT_TARGET=10.9 CC=cc CXX=c++ python setup.py install`

## Environment

from running `collect_env.py`:
```
PyTorch version: 1.0.0.dev20181014
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.1
GCC version: Could not collect
CMake version: version 3.12.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect```

**Comment by zou3519** [comment] 2018-10-29 17:50
Does it help if you do
```NO_CAFFE2_OPS=1 MACOSX_DEPLOYMENT_TARGET=10.9 CC=cc CXX=c++ python setup.py install```? I am assuming you do not need the caffe2 operators.

**Comment by dendisuhubdy** [comment] 2018-11-06 18:51
@zou3519 lemme try, I still need the caffe2 operators tho

**Comment by dendisuhubdy** [comment] 2018-11-07 21:38
@zou3519 I still got the same error even after `NO_CAFFE2_OPS=1`

**Comment by robbine** [comment] 2019-02-01 12:37
I got the same error

**Comment by dendisuhubdy** [comment] 2019-02-01 15:14
Hmmm weird after Pytorch 1.0.0 release I never have gotten this error again @robbine

**Comment by zou3519** [comment] 2019-02-15 16:45
Going to close this now because the issue seems resolved after the 1.0.0 release (according to @dendisuhubdy , thank you for following up). If you keep on getting the error, please reopen this issue @robbine and we'll investigate.

**Closed by zou3519** 2019-02-15 16:45 UTC
Labels: build, caffe2

**Comment by TianDekuan** [comment] 2019-05-18 03:51
version  
2af5911 - (HEAD -> master, origin/master, origin/HEAD) Modify the Insert quant-dequant test cases to look for q-dq pattern (#20672) (2 hours ago) <Nishant Pandit>

this err appears again:
../caffe2/perfkernels/common_avx512.cc:18:2: error: #error ( "You found a build system error: __AVX512F__, __AVX512DQ__, __AVX512VL__ " "is defined (via e.g. -mavx512f, -mavx512dq, and -mavx512vl) " "but CAFFE2_PERF_WITH_AVX512 is not defined.");

**Comment by HenryJia** [comment] 2019-05-21 16:53
Also getting this error with the lastest version of master as of this comment

../caffe2/perfkernels/common_avx2.cc:17:2: error: #error ( "You found a build system error: __AVX2__ is defined (via e.g. -mavx2) " "but CAFFE2_PERF_WITH_AVX2 is not defined.");
...
../caffe2/perfkernels/common_avx512.cc:18:2: error: #error ( "You found a build system error: __AVX512F__, __AVX512DQ__, __AVX512VL__ " "is defined (via e.g. -mavx512f, -mavx512dq, and -mavx512vl) " "but CAFFE2_PERF_WITH_AVX512 is not defined.");

Anything?

**Comment by sth1997** [comment] 2019-05-25 07:29
@TianDekuan @HenryJia 

I got the same error, and solved it by replacing `#include "caffe2/core/macros.h" ` with `#include "build/caffe2/core/macros.h"` in caffe2/core/common.h and caffe2/utils/cblas.h.

caffe2/core/macros.h has no content, it's just a placeholder, the real content , that is, build/caffe2/core/macros.h, will be generated by the cmake script.

I noticed that there is `-I.` and `-I../` in the compile command, so the compiler should find both build/caffe2/core/macros.h and caffe2/core/macros.h for `#include "caffe2/core/macros.h"`. I don't know what will happen if the compiler find two header file with the same name.

**Comment by HenryJia** [comment] 2019-05-25 15:28
@sth1997 
That then gets me caffe2/caffe2/contrib/aten/gen_aten_op.h No such file or directory

Although I have git pulled and I'm now on 81e70ffa19c90e14c20d1369aae86d19f305dc7d

**Comment by sth1997** [comment] 2019-05-26 05:42
@HenryJia 
I can't find this file either. Which file include this header file?

**Comment by ZhihuiYangCS** [comment] 2019-05-27 20:26
@HenryJia I met this problem if I replace #include "caffe2/core/macros.h" with #include "build/caffe2/core/macros.h" in caffe2/core/common.h and caffe2/utils/cblas.h.

Now, are there any suggestions?

**Comment by HenryJia** [comment] 2019-05-28 11:17
@sth1997 @ZhihuiYangCS 

OK. I think you can solve that one by setting MAX_JOBS=4. I think the issue is that if you let it use the default MAX_JOBS it may run more than 4,  causing the job which generates macros.h to be complete after the jobs which need it

Still getting this error though

```
[1607/3186] Building CXX object caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/DistanceOpsKernel.cpp.DEFAULT.cpp.o
[1608/3186] Building CXX object caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/GridSamplerKernel.cpp.DEFAULT.cpp.o
[1609/3186] Building CXX object caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o
FAILED: caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o 
/usr/bin/g++  -DAT_PARALLEL_OPENMP=1 -DCPUINFO_SUPPORTED_PLATFORM=1 -DHAVE_MALLOC_USABLE_SIZE=1 -DHAVE_MMAP=1 -DHAVE_SHM_OPEN=1 -DHAVE_SHM_UNLINK=1 -DMAGMA_V2 -DNNP_CONVOLUTION_ONLY=0 -DNNP_INFERENCE_ONLY=0 -DONNX_NAMESPACE=onnx_torch -DUSE_C11_ATOMICS=1 -DUSE_CUDA -D_FILE_OFFSET_BITS=64 -D_THP_CORE -Dcaffe2_EXPORTS -I../aten/src -I. -I../ -I../third_party/protobuf/src -I../cmake/../third_party/benchmark/include -Icaffe2/contrib/aten -I../third_party/onnx -Ithird_party/onnx -I../third_party/foxi -Ithird_party/foxi -I../caffe2/../torch/csrc/api -I../caffe2/../torch/csrc/api/include -I../caffe2/aten/src/TH -Icaffe2/aten/src/TH -I../caffe2/../torch/../aten/src -Icaffe2/aten/src -Iaten/src -Icaffe2/../aten/src -Icaffe2/../aten/src/ATen -I../caffe2/../torch/csrc -I../caffe2/../torch/../third_party/miniz-2.0.8 -I../aten/src/TH -I../aten/../third_party/catch/single_include -I../aten/src/ATen/.. -Icaffe2/aten/src/ATen -I../caffe2/core/nomnigraph/include -I../third_party/miniz-2.0.8 -I/opt/cuda/include -I../c10/.. -Ithird_party/ideep/mkl-dnn/include -I../third_party/ideep/mkl-dnn/src/../include -I../third_party/QNNPACK/include -I../third_party/pthreadpool/include -I../third_party/NNPACK/include -I../third_party/cpuinfo/include -I../third_party/fbgemm/include -I../third_party/fbgemm -I../third_party/FP16/include -isystem third_party/gloo -isystem ../cmake/../third_party/gloo -isystem ../cmake/../third_party/googletest/googlemock/include -isystem ../cmake/../third_party/googletest/googletest/include -isystem ../third_party/gemmlowp -isystem ../third_party/neon2sse -isystem ../third_party -isystem /usr/include/opencv4 -isystem ../cmake/../third_party/eigen -isystem /usr/include/python3.7m -isystem /usr/lib/python3.7/site-packages/numpy/core/include -isystem ../cmake/../third_party/cub -isystem /opt/magma/include -isystem ../third_party/ideep/mkl-dnn/include -isystem ../third_party/ideep/include -isystem ../third_party/ideep/mkl-dnn/external/mklml_lnx_2019.0.3.20190220/include -isystem include -fvisibility-inlines-hidden -fopenmp -DUSE_FBGEMM -O2 -fPIC -Wno-narrowing -Wall -Wextra -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Wno-stringop-overflow -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -O3  -fPIC   -DCAFFE2_USE_GLOO -DCUDA_HAS_FP16=1 -DHAVE_GCC_GET_CPUID -DUSE_AVX -DUSE_AVX2 -DTH_HAVE_THREAD -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-unknown-pragmas -Wno-missing-braces -Wno-maybe-uninitialized -fvisibility=hidden -DCAFFE2_BUILD_MAIN_LIB -O2 -pthread -std=gnu++11 -MD -MT caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o -MF caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o.d -o caffe2/CMakeFiles/caffe2.dir/contrib/aten/aten_op.cc.o -c ../caffe2/contrib/aten/aten_op.cc
In file included from ../caffe2/contrib/aten/aten_op.cc:1:
../caffe2/contrib/aten/aten_op.h:1:10: fatal error: caffe2/caffe2/contrib/aten/gen_aten_op.h: No such file or directory
 #include "caffe2/caffe2/contrib/aten/gen_aten_op.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
[1610/3186] Building CXX object caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/BinaryOpsKernel.cpp.DEFAULT.cpp.o
[1611/3186] Building CXX object caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/CopyKernel.cpp.DEFAULT.cpp.o
[1612/3186] Building CXX object caffe2/CMakeFiles/caffe2.dir/__/aten/src/ATen/native/cpu/Activation.cpp.DEFAULT.cpp.o
ninja: build stopped: subcommand failed.
Building wheel torch-1.2.0a0+ff6cda0
-- Building version 1.2.0a0+ff6cda0
['cmake',
 '-GNinja',
 '-DBUILDING_WITH_TORCH_LIBS=ON',
 '-DBUILD_BINARY=True',
 '-DBUILD_CAFFE2_OPS=True',
 '-DBUILD_PYTHON=True',
 '-DBUILD_SHARED_LIBS=ON',
 '-DBUILD_TEST=True',
 '-DCAFFE2_STATIC_LINK_CUDA=False',
 '-DCMAKE_BUILD_TYPE=Release',
 '-DCMAKE_CXX_FLAGS= ',
 '-DCMAKE_C_FLAGS= ',
 '-DCMAKE_EXE_LINKER_FLAGS=',
 '-DCMAKE_INSTALL_PREFIX=/home/henry/Downloads/MachineLearning/pytorch/pytorch/torch',
 '-DCMAKE_PREFIX_PATH=/usr/lib/python3.7/site-packages',
 '-DCMAKE_SHARED_LINKER_FLAGS=',
 '-DCMAKE_VERBOSE_MAKEFILE=ON',
 '-DINSTALL_TEST=True',
 '-DNAMEDTENSOR_ENABLED=False',
 '-DNCCL_EXTERNAL=True',
 '-DNCCL_INCLUDE_DIR=/usr/include',
 '-DNCCL_ROOT_DIR=/usr/',
 '-DNCCL_SYSTEM_LIB=/usr/lib/libnccl.so.2.3.5',
 '-DNUMPY_INCLUDE_DIR=/usr/lib/python3.7/site-packages/numpy/core/include',
 '-DONNX_ML=False',
 '-DONNX_NAMESPACE=onnx_torch',
 '-DPYTHON_EXECUTABLE=/usr/bin/python3',
 '-DPYTHON_INCLUDE_DIR=/usr/include/python3.7m',
 '-DPYTHON_LIBRARY=/usr/lib/libpython3.7m.so.1.0',
 '-DTHD_SO_VERSION=1',
 '-DTORCH_BUILD_VERSION=1.2.0a0+ff6cda0',
 '-DUSE_ASAN=False',
 '-DUSE_CUDA=True',
 '-DUSE_DISTRIBUTED=True',
 '-DUSE_FBGEMM=True',
 '-DUSE_FFMPEG=False',
 '-DUSE_LEVELDB=False',
 '-DUSE_LMDB=False',
 '-DUSE_MKLDNN=True',
 '-DUSE_NCCL=True',
 '-DUSE_NNPACK=True',
 '-DUSE_NUMPY=True',
 '-DUSE_OPENCV=True',
 '-DUSE_QNNPACK=True',
 '-DUSE_ROCM=False',
 '-DUSE_SYSTEM_EIGEN_INSTALL=OFF',
 '-DUSE_SYSTEM_NCCL=True',
 '-DUSE_TENSORRT=False',
 '-DMKLDNN_ENABLE_CONCURRENT_EXEC=ON',
 '/home/henry/Downloads/MachineLearning/pytorch/pytorch']
Traceback (most recent call last):
  File "setup.py", line 744, in <module>
    build_deps()
  File "setup.py", line 309, in build_deps
    build_dir='build')
  File "/home/henry/Downloads/MachineLearning/pytorch/pytorch/tools/build_pytorch_libs.py", line 306, in build_caffe2
    check_call(ninja_cmd, cwd=build_dir, env=my_env)
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ninja', 'install', '-j', '4']' returned non-zero exit status 1.
sh build_install.sh  2386.56s user 112.30s system 384% cpu 10:49.38 total
tee build.log  0.00s user 0.07s system 0% cpu 10:49.38 total
```

**Comment by dendisuhubdy** [comment] 2019-05-28 11:55
@HenryJia interesting, I didn't think build threads were the problem

**Comment by HenryJia** [comment] 2019-05-28 12:12
@dendisuhubdy I went and read the macros.h file, it did mention that it was a placeholder for something generated by CMake.

I also noticed that compilation carried on for a bit even after the error triggered, which suggested maybe it was an issue of threads/jobs not being correctly synced. I also went through the Jenkins builds and noticed the automated builds had an export MAX_JOBS=4 line in them

**Comment by HenryJia** [comment] 2019-06-07 12:43
Found a better solution. It seems that the errors are not to do with build threads.

It turns out the errors were caused by cmake using Ninja instead of Make, if Ninja is installed. Adding USE_NINJA=OFF seems to fix it

**Comment by jinfagang** [comment] 2020-02-24 01:41
In the lastest master branch, using ninja off does make this error disappear, but make caused don't found cuda lib error, while everything of cuda lib installed.

**Comment by 1926627357** [comment] 2020-02-26 16:51
I come with this bug: #13061 and I successfully fix it after reading all comments above
I just make a summary about it
Centos 7 Cuda10.0+Cudnn
... do according to the requirements of the README.md
but before you execute "setup.py":

1. python setup.py clean
2. export CUDA_HOME=%your cuda root dir%
3. export CUDNN_LIB_DIR=%your cuda root dir%/lib64
4. export CUDNN_INCLUDE_DIR=%your cudnn root dir%/include
5. export CUDNN_LIBRARY=libcudnn.so
6. export USE_NINJA=OFF
7. export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}

finally,
python setup.py install

**Comment by zechendev** [comment] 2020-03-11 03:00
disable ninja, do solve this problem!
in my case, the pytorch version is 1.3.0 python version is 3.7.0.
Thank you!

**Comment by ludehui** [comment] 2020-08-25 09:21
good! Adding USE_NINJA=OFF solve this problem.

**Comment by gaohuazuo** [comment] 2021-02-04 12:17
It turns out that, for my case, the `CPLUS_INCLUDE_PATH` environment variable is the one to blame. If `CPLUS_INCLUDE_PATH`  contains the build directory (hint: check for extra `:`), the wrong header will be used.
