### ISSUE TITLE
Unable to use rpc with torch v1.8.0 and Ubuntu 16.0.4

### ISSUE THREAD

**Issue by msbaines** [pytorch/pytorch#53844] opened 2021-03-11 21:12 UTC
## 🐛 Bug

When trying to use rpc I get the following:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/circleci/venv/lib/python3.8/site-packages/torch/distributed/rpc/__init__.py", line 194, in init_rpc
    _init_rpc_backend(backend, store, name, rank, world_size, rpc_backend_options)
  File "/home/circleci/venv/lib/python3.8/site-packages/torch/distributed/rpc/__init__.py", line 230, in _init_rpc_backend
    rpc_agent = backend_registry.init_backend(
  File "/home/circleci/venv/lib/python3.8/site-packages/torch/distributed/rpc/backend_registry.py", line 99, in init_backend
    return backend.value.init_backend_handler(*args, **kwargs)
  File "/home/circleci/venv/lib/python3.8/site-packages/torch/distributed/rpc/backend_registry.py", line 278, in _tensorpipe_init_backend_handler
    api._init_rpc_states(agent)
  File "/home/circleci/venv/lib/python3.8/site-packages/torch/distributed/rpc/api.py", line 116, in _init_rpc_states
    _set_and_start_rpc_agent(agent)
RuntimeError: In Reactor at /pytorch/third_party/tensorpipe/tensorpipe/transport/shm/reactor.cc:49 "errorCouldn't allocate ringbuffer for reactor: mmap: Invalid argument"

## To Reproduce

1.
1.
1.

import torch.distributed.rpc as ripc
import os

os.environ["MASTER_ADDR"] = "127.0.0.1"
os.environ["MASTER_PORT"] = "8080"

bo = rpc.TensorPipeRpcBackendOptions(_channels=["basic", "cuda_basic"])
rpc.init_rpc("foo", rank=0, world_size=1, backend=rpc.BackendType.TENSORPIPE, rpc_backend_options=bo)

I've also tried without the rpc_backend_options and it still fails. The options used above were recommended to me as a workaround.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by pritamdamania87** [comment] 2021-03-12 22:30
I think @lw mentioned this was fixed in master, could you try a nightly build?

**Comment by rohan-varma** [comment] 2021-03-13 08:16
Tried to reproduce this with 1.8, but couldn't on a CentOS machine. I'm assuming the issue is specific to ubuntu machines?

**Comment by lw** [comment] 2021-03-13 14:36
After talking with @msbaines offline this issue has been solved. It's due to the PyTorch 1.8 binaries having been compiled on Ubuntu 18.04, which caused TensorPipe to pick up a flag that didn't yet exist in Ubuntu 16.04, thus causing a failure when running on Ubuntu 16.04. This has been fixed in master (and thus in the nightlies) and will also be cherry-picked into PyTorch 1.8.1.

This bug occurs in the SHM transports hence, as a temporary workaround, one can disable that transport. This can be achieved by passing `_transports=["ibv", "uv"]` to the TensorPipeRpcAgentOptions class. Use this with caution, and only when necessary, as disabling that transport might hurt performance for same-machine transfers.

**Closed by lw** 2021-03-13 14:36 UTC
Labels: oncall: distributed, triaged
