### ISSUE TITLE
Loading traced pytorch model to C++

### ISSUE THREAD

**Issue by ZarinaMaks** [pytorch/pytorch#124009] opened 2024-04-13 14:12 UTC
### 🐛 Describe the bug

Will be grateful for any help :(

I’m having a problem with using _pytorch 2.2.2+cpu_ pretrained model in C++ via _TorchLib 2.2.2 (cpu version)_. 
I’m also using Visual Studio 2022 to work with C++ project which is located on D:\ drive. I’ve added Torchlib to Cmake and it successfully downloads the model and works until line:

```
at::Tensor output = module.forward(inputs).toTensor();
```

After this line it crushes with the error: ``` INTEL MKL ERROR: The specified module could not be found. mkl_avx2.1.dll. Intel MKL FATAL ERROR: Cannot load mkl_avx2.1.dll or mkl_def.1.dll. ``` and I didn't figured out what is wrong with TorchLib here. Seems like the problem is with some part of the lib related to python, but it’s strange because the model loads to C++ by LibTorch successfully.

The .cpp code is here:

```
#include <torch/script.h>
...
    string path = "traced_energynn_model.pt";
    torch::jit::script::Module module;
    try {
        module = torch::jit::load(path);
    }
    catch (const c10::Error& e) {
        std::cerr << "error loading the model\n";
        return -1;
    }
    std::cout << "Model traced_energynn_model loaded fine\n";

    std::vector<torch::jit::IValue> inputs;
    inputs.push_back(torch::randn({ 1, 2 }));

    at::Tensor output = module.forward(inputs).toTensor();
    std::cout << output << "\n";
...
```
The way I saved the model in python 3.9:

```
from random import randrange

x = X_test.reset_index(drop=True).iloc[randrange(len(X_test))]
example = torch.tensor([x]).to(torch.float32)

traced_model = torch.jit.trace(model, example)
traced_model.save("traced_energynn_model.pt")
```

### Versions

Collecting environment information...
PyTorch version: 2.2.2+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1660 Ti
Nvidia driver version: 516.94
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2592
DeviceID=CPU0
Family=198
L2CacheSize=1536
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2592
Name=Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] flake8==4.0.1
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.25.2
[pip3] numpydoc==1.4.0
[pip3] torch==2.2.2
[pip3] torchvision==0.17.1
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           haa95532_640  
[conda] mkl-service               2.4.0            py39h2bbff1b_0  
[conda] mkl_fft                   1.3.1            py39h277e83a_0  
[conda] mkl_random                1.2.2            py39hf11a4ad_0  
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] numpydoc                  1.4.0            py39haa95532_0  
[conda] torch                     2.2.2                    pypi_0    pypi
[conda] torchvision               0.17.1                   pypi_0    pypi

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10

**Comment by LLimerence** [comment] 2024-04-18 02:37
Hello, have you solved this problem

**Comment by xuhancn** [comment] 2024-04-19 14:31
https://github.com/pytorch/builder/pull/1790 @jgong5 Please review and comment this PR.

**Comment by xuhancn** [comment] 2024-04-27 08:26
Hi @ZarinaMaks 
I have submitted some PRs to fix this issue: https://github.com/pytorch/pytorch/pull/124925 & https://github.com/pytorch/builder/pull/1798
Could you please help on test the latest nightly build?
Install command:
```cmd
python -m pip install --pre torch --index-url https://download.pytorch.org/whl/nightly/cpu --upgrade --force-reinstall
```

Thanks.

**Comment by leslie-fang-intel** [comment] 2024-05-07 06:44
Close this issue since the fixing PR landed. Feel free to re-open if any further discussion needed.

**Closed by leslie-fang-intel** 2024-05-07 06:44 UTC
Labels: module: windows, module: cpu, triaged, module: mkl, intel

**Comment by KuramaStone** [comment] 2024-06-06 21:15
I need some clarity on how to fix this issue. I am currently trying v3.0.1. I get the same errors on the same forward function. Is there a specific instruction that must be followed on Windows now, or is the issue supposed to be fixed? I can share more information if needed.

```
INTEL MKL ERROR: The specified module could not be found. mkl_avx2.1.dll.
Intel MKL FATAL ERROR: Cannot load mkl_avx2.1.dll or mkl_def.1.dll.
```

**Comment by leslie-fang-intel** [comment] 2024-06-07 01:20
> I need some clarity on how to fix this issue. I am currently trying v2.3.1. I get the same errors on the same forward function. Is there a specific instruction that must be followed on Windows now, or is the issue supposed to be fixed? I can share more information if needed.
> 
> ```
> INTEL MKL ERROR: The specified module could not be found. mkl_avx2.1.dll.
> Intel MKL FATAL ERROR: Cannot load mkl_avx2.1.dll or mkl_def.1.dll.
> ```

cc @xuhancn for this question.

**Comment by xuhancn** [comment] 2024-06-11 14:41
Conclusion:
This issue caused by `torch_cpu.dll` linked mkl as shared library, and it missing to package some mkl libraries.
I have fixed the issue by change to link mkl as static library. 
But pytorch 2.3 branch cut before my fixing. 

I have confirmed via check daily build:
<img width="788" alt="image" src="https://github.com/pytorch/pytorch/assets/8433590/bda27f87-5130-4b25-b81d-fbbbfb0a7c60">

**Comment by umurh** [comment] 2024-07-10 16:48
> > I have still not found a solution for this, but I have discovered more. It seems that Pytorch for Windows requires 2021.4 mkl only, and that future versions are incompatible. However, it is currently impossible to get older versions of MKL without buying a product license according to their official website, and I don't see it included anywhere in the pytorch files. If I am correct, it may mean that pytorch is unusable for any Windows user who has their intel mkl updated.
> > @xuhancn I am unsure if he was saying I should cc you or if he was just doing so himself...
> > Here is what I learned. Using `pip install mkl==2021.4` will download the necessary files to the python/Library path near where site-packages are stored. Copying the `mkl_axv2.1.dll`, `mkl_def.1.dll`, `mkl_vml_avx2.1.dll`, and `mkl_vml_def.1.dll` to the project build directory fixed this issue. I just grabbed whatever DLL's the console errors printed for me. It may not initially appear if you are testing with a batch size of 1 as it doesnt seem to invoke avx2.1.dll until doing multiple batches. I suspect the same would apply to avx512. So, the problem isn't fixed, but there is a very hacky solution for those who need it asap.
> 
> I successfully did something even hackier. I installed oneMKL 2024.1 from the Intel website, and then grabbed the missing DLL files from its installation folder, **renamed** them so that they could be found by LibTorch during runtime, and it works so far, it successfully performs the inference on a specific model I am using, so I'd say your mileage may vary.

Be careful, this solution caused unexpected behavior in my case. Specifically, the forward pass didn't work for a batch of states. I fixed it by downloading and using DLLs from oneMKL version 2024.4.1. Not the most desirable option, but it worked.

**Comment by syl20bnr** [comment] 2024-07-29 13:50
@umurh can you share the link you are using to download them ?

**Comment by umurh** [comment] 2024-07-30 00:46
> @umurh can you share the link you are using to download them ?

I have downloaded mkl_avx2.1.dll and mkl_vml_avx2.1.dll, both version 2021.4.1, from dllme.com:

https://www.dllme.com/dll/files/mkl_avx2_1/cc93b4c9cfea400837bb9178bad4c531
https://www.dllme.com/dll/files/mkl_vml_avx2_1/b7d543964968b81e8706667a095a8e78
