### ISSUE TITLE
Publish wheels for torch+CPU ARM64 arch

### ISSUE THREAD

**Issue by csuriano23** [pytorch/pytorch#110791] opened 2023-10-07 13:54 UTC
### 🚀 The feature, motivation and pitch

For my projects I develop and deploy on ARM64 (both darwin and linux/AWS Graviton). It would be nice if prebuilt wheel artifacts for torch CPU-only version were available as the x86-64 ones in https://download.pytorch.org/whl/torch/

### Alternatives

We have to manually build PyTorch CPU for target ARM64 architectures

cc @seemethere @malfet @osalpekar @atalman

**Comment by johnnynunez** [comment] 2023-10-07 15:28
The problem is the variety of aarch64. For example aarch64 architecture is supported by Jetson with Cuda, m1/m2 with metal from mac etc

**Comment by csuriano23** [comment] 2023-10-09 15:37
> @csuriano23 They are, aren't they? I.e. nightly aarch64 binaries are available from http://download.pytorch.org/whl/nightly/cpu and release ones are available on pypi, though technically they could be mirrored to https://download.pytorch.org/whl/cpu, but imo this is optional isn't it (as they are published elsewhere)

Hi @malfet, the repo URL you specified is for nightly versions, but what if I need the ARM64 wheel for 2.0.0+cpu?

**Comment by malfet** [comment] 2023-10-09 16:07
> The repo URL you specified is for nightly versions, but what if I need the ARM64 wheel for 2.0.0+cpu?
ARM binaries do not have `+cpu` suffix (same as MacOS ones), but it's there isn't  it?
https://download.pytorch.org/whl/cpu/torch
<img width="386" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/bc73bbf9-d02d-4f87-90eb-d0bbabed88ec">
There are also on PyPI:
<img width="572" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/64d354b7-a5f5-4ead-ab7e-1e51ac3acb4a">

**Comment by csuriano23** [comment] 2023-10-09 16:24
> > The repo URL you specified is for nightly versions, but what if I need the ARM64 wheel for 2.0.0+cpu?
> 
> ARM binaries do not have `+cpu` suffix (same as MacOS ones), but they are there aren't  they?
> https://download.pytorch.org/whl/cpu/torch
> <img width="386" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/bc73bbf9-d02d-4f87-90eb-d0bbabed88ec">
> 
> There are also on PyPI:
> <img width="572" alt="image" src="https://github.com/pytorch/pytorch/assets/2453524/64d354b7-a5f5-4ead-ab7e-1e51ac3acb4a">
> 
> 

Yes for the standard version, but I am looking for the cpu-only wheel

**Comment by seemethere** [comment] 2023-10-09 16:25
Since we do not publish GPU enabled binaries for arm64 this means that all aarch64 binaries are cpu only

**Comment by malfet** [comment] 2023-10-09 16:40
> > Since we do not publish GPU enabled binaries for aarch64 this means that all aarch64 binaries are cpu only
> 
> So they are just tagged differently depending on arch (x.y.z+cpu for x86, x.y.z for aarch64). This causes issues for some dependency resolvers like poetry. Anyhow, thank you for the explanation

`x.y.z+cpu` only for Linux and Windows, Mac binaries do not have the tag (as there are no CUDA-binaries to deal with)

Anyway, closing this issue, as binaries are already published, but please do not hesitate to open a new one (or a PR) if you want to propose dropping `+cpu` suffix for Linux and Windows wheels, as nobody seems to be relying on the old installation method anyway.

**Closed by malfet** 2023-10-09 16:40 UTC
Labels: oncall: binaries, triaged
