### ISSUE TITLE
`size()` type for `size` argument of `randn()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130876] opened 2024-07-16 23:47 UTC
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.randn.html) of `randn()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `size` argument as shown below:

> size ([int](https://docs.python.org/3/library/functions.html#int)...) – a sequence of integers defining the shape of the output tensor. Can be a variable number of arguments or a collection like a list or tuple.

But, `size()` type for `size` argument of `randn()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([8, 3, 6])

my_tensor.size()
# torch.Size([3])

torch.randn(size=my_tensor.size())
# tensor([ 0.2771, -0.4228,  0.7936])
```

**Comment by malfet** [comment] 2024-07-17 06:18
Please stop filing separate issue for the same problem! One can mention all ops that violate the standard in one issue
Closing as duplicate of https://github.com/pytorch/pytorch/issues/130872

**Closed by malfet** 2024-07-17 06:18 UTC
