### ISSUE TITLE
[JIT] torch.arange is basically untraceable

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#12580] opened 2018-10-11 21:11 UTC
```
import torch

def foo(x):
    dim = x.size(1)
    print('tracer state', torch._C._get_tracing_state())
    return torch.arange(0, dim)

traced = torch.jit.trace(foo, (torch.rand(3, 4),), check_trace=False)
print(traced.graph)
```

```
tracer state graph(%0 : Float(3, 4)) {
  %1 : int = prim::Constant[value=1]()
  %2 : int = aten::size(%0, %1)
  %3 : Long() = prim::NumToTensor(%2)
  return ();
}

graph(%0 : Float(3, 4)) {
  %4 : int = prim::Constant[value=0]()
  %5 : int = prim::Constant[value=4]()
  %6 : int = prim::Constant[value=1]()
  %7 : int = prim::Constant[value=4]()
  %8 : int = prim::Constant[value=0]()
  %9 : int[] = prim::Constant[value=[0, -1]]()
  %10 : Long(4) = aten::arange(%4, %5, %6, %7, %8, %9)
  return (%10);
}
```

We are hard-coding values into the graph. `arange` takes scalars, while the values we're getting are torch.Tensor by the time we get to arange calls. Are we not recording Tensor->Scalar conversion in tracing?

cc @suo

**Comment by apaszke** [comment] 2018-10-12 09:48
The problem is not with not recording the casts, but with the fact that we only record traces in C++ and at that point the arguments to arange are simply `int64_t`. We need to extend ArgumentStash to work with int arguments too if you want to fix it.

**Comment by lara-hdr** [comment] 2019-08-22 18:58
I am running through the same problem and noticed that by setting traceable=true in the arg parser, the issue is solved.
Is there a reason traceable is set to false? what are the consequences of switching it to true?

**Comment by zdevito** [comment] 2019-11-20 23:31
Never versions seem to trace correctly, so I am closing this.

```
graph(%x : Float(3, 4)):
  %1 : int = prim::Constant[value=1]() # hi.py:4:0
  %2 : int = aten::size(%x, %1) # hi.py:4:0
  %dim : Long() = prim::NumToTensor(%2)
  %4 : Scalar = prim::ImplicitTensorToNum(%dim)
  %5 : int = prim::Constant[value=0]() # hi.py:6:0
  %6 : int = prim::Constant[value=1]() # hi.py:6:0
  %7 : None = prim::Constant()
  %8 : int = prim::Constant[value=0]() # hi.py:6:0
  %9 : Device = prim::Constant[value="cpu"]() # hi.py:6:0
  %10 : bool = prim::Constant[value=0]() # hi.py:6:0
  %11 : Long(4) = aten::arange(%5, %4, %6, %7, %8, %9, %10) # hi.py:6:0
  return (%11)
```

**Closed by zdevito** 2019-11-20 23:31 UTC
Labels: jit, triaged
