### ISSUE TITLE
Backward segmentation fault

### ISSUE THREAD

**Issue by onlytailei** [pytorch/pytorch#1674] opened 2017-05-29 13:59 UTC
In ubuntu 14.04, cuda 7.5.
I install the pytorch with pip and python 2.7
I run the pytorch tutorial [neural networks](http://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html#sphx-glr-beginner-blitz-neural-networks-tutorial-py). 
For the notebook, the kernel keeps stopping and restarting in 
```
net.zero_grad()
out.backward(torch.randn(1, 10))
```

In the .py version, there is a segmentation fault.
Then _gdb --args python neural_networks_tutorial.py_ shows that:
```
$ gdb --args python neural_networks_tutorial.py
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...Reading symbols from /usr/lib/debug//usr/bin/python2.7...done.
done.
(gdb) r
Starting program: /usr/bin/python neural_networks_tutorial.py
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Net (
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear (400 -> 120)
  (fc2): Linear (120 -> 84)
  (fc3): Linear (84 -> 10)
)
10
(6L, 1L, 5L, 5L)
[New Thread 0x7fffd001d780 (LWP 14613)]
[New Thread 0x7fffcfc1c800 (LWP 14614)]
[New Thread 0x7fffcf81b880 (LWP 14615)]
[New Thread 0x7fffcf41a900 (LWP 14616)]
[New Thread 0x7fffcf019980 (LWP 14617)]
[New Thread 0x7fffcec18a00 (LWP 14618)]
[New Thread 0x7fffce817a80 (LWP 14619)]
[New Thread 0x7fffce416b00 (LWP 14620)]
[New Thread 0x7fffce015b80 (LWP 14621)]
[New Thread 0x7fffcdc14c00 (LWP 14622)]
[New Thread 0x7fffcd813c80 (LWP 14623)]
[New Thread 0x7fffcd412d00 (LWP 14624)]
[New Thread 0x7fffcd011d80 (LWP 14625)]
[New Thread 0x7fffccc10e00 (LWP 14626)]
[New Thread 0x7fffcc80fe80 (LWP 14627)]
[New Thread 0x7fffcc40ef00 (LWP 14628)]
[New Thread 0x7fff8fffef80 (LWP 14629)]
[New Thread 0x7fff8fafe000 (LWP 14630)]
[New Thread 0x7fff8f3fd080 (LWP 14631)]
[New Thread 0x7fff8effc100 (LWP 14632)]
[New Thread 0x7fff8ebfb180 (LWP 14633)]
[New Thread 0x7fff8e7fa200 (LWP 14634)]
[New Thread 0x7fff8e3f9280 (LWP 14635)]
[New Thread 0x7fff8dff8300 (LWP 14636)]
[New Thread 0x7fff8dbf7380 (LWP 14637)]
[New Thread 0x7fff8d7f6400 (LWP 14638)]
[New Thread 0x7fff8d3f5480 (LWP 14639)]
[New Thread 0x7fff8cff4500 (LWP 14640)]
[New Thread 0x7fff8cbf3580 (LWP 14641)]
[New Thread 0x7fff8c7f2600 (LWP 14642)]
[New Thread 0x7fff57fff680 (LWP 14643)]
Variable containing:
1.00000e-02 *
 -9.1825 -2.2400 -9.6241  8.7923 -9.5927 -5.7082  7.3887  6.0140 -8.8177 -2.8286
[torch.FloatTensor of size 1x10]

[New Thread 0x7fff54f8d700 (LWP 14644)]
[New Thread 0x7fff4bfff700 (LWP 14645)]
[New Thread 0x7fff4b7fe700 (LWP 14646)]
[New Thread 0x7fff4affd700 (LWP 14647)]
[New Thread 0x7fff5478b780 (LWP 14648)]
[New Thread 0x7fff4a7fb800 (LWP 14649)]
[New Thread 0x7fff4a3f9880 (LWP 14650)]
[New Thread 0x7fff49ff7900 (LWP 14651)]
[New Thread 0x7fff49bf5980 (LWP 14652)]
[New Thread 0x7fff497f3a00 (LWP 14653)]
[New Thread 0x7fff493f1a80 (LWP 14654)]
[New Thread 0x7fff48fefb00 (LWP 14655)]
[New Thread 0x7fff48bedb80 (LWP 14656)]
[New Thread 0x7fff487ebc00 (LWP 14657)]
[New Thread 0x7fff0fffec80 (LWP 14658)]
[New Thread 0x7fff0fbfcd00 (LWP 14659)]
[New Thread 0x7fff0f7fad80 (LWP 14660)]
[New Thread 0x7fff0f3f8e00 (LWP 14661)]

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff4bfff700 (LWP 14645)]
0x00007fff5663a2c3 in mkl_blas_avx2_xsgemm_acopiedbcopy () from /usr/local/mkl/mkl/lib/intel64/libmkl_avx2.so
(gdb) where
#0  0x00007fff5663a2c3 in mkl_blas_avx2_xsgemm_acopiedbcopy () from /usr/local/mkl/mkl/lib/intel64/libmkl_avx2.so
#1  0x00007fffda8f5dce in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_thread.so
#2  0x00007fffd8810d13 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libiomp5.so
#3  0x00007fffd87e0b17 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libiomp5.so
#4  0x00007fffd87e1bd3 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libiomp5.so
#5  0x00007fffd87b96f8 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libiomp5.so
#6  0x00007fffda8f57ae in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_thread.so
#7  0x00007fffda8f4ed9 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_thread.so
#8  0x00007fffda8f3ff0 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_thread.so
#9  0x00007fffda920ca1 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_thread.so
#10 0x00007fffdc196063 in ?? () from /usr/local/lib/python2.7/dist-packages/torch/lib/libmkl_intel_lp64.so
#11 0x00007fffece71f61 in THFloatBlas_gemm () from /usr/local/lib/python2.7/dist-packages/torch/lib/libTH.so.1
#12 0x00007fffecc0ee60 in THFloatTensor_addmm () from /usr/local/lib/python2.7/dist-packages/torch/lib/libTH.so.1
#13 0x00007fffec295df0 in THNN_FloatSpatialConvolutionMM_accGradParameters_frame () from /usr/local/lib/python2.7/dist-packages/torch/lib/libTHNN.so.1
#14 0x00007fffec34d4ef in THNN_FloatSpatialConvolutionMM_accGradParameters () from /usr/local/lib/python2.7/dist-packages/torch/lib/libTHNN.so.1
#15 0x00007ffff3891f0b in torch::nn::SpatialConvolutionMM_accGradParameters (input=input@entry=0x7fff40001ef0, gradOutput=gradOutput@entry=0x7fff400066d0, 
    gradWeight=<optimized out>, gradBias=gradBias@entry=0x7fff40001600, finput=finput@entry=0x14b3d30, fgradInput=fgradInput@entry=0x14b3d90, kW=5, kH=5, dW=1, dH=1, 
    padW=0, padH=0, scale=scale@entry=1) at torch/csrc/nn/THNN_generic.cpp:7624
#16 0x00007ffff38756f3 in torch::autograd::compute_grad_params (input=0x7fff40001ef0, grad_output=0x7fff400066d0, weight=weight@entry=0x7fff400015a0, 
    bias=bias@entry=0x7fff40001f70, columns=0x14b3d30, ones=0x14b3d90, kernel_size=std::vector of length 2, capacity 2 = {...}, params=...)
---Type <return> to continue, or q <return> to quit---
    at torch/csrc/autograd/functions/convolution.cpp:491
#17 0x00007ffff38773e7 in torch::autograd::ConvBackward::apply (this=0x14b4058, grad_outputs=...) at torch/csrc/autograd/functions/convolution.cpp:285
#18 0x00007ffff385bc68 in call_function (task=...) at torch/csrc/autograd/engine.cpp:132
#19 torch::autograd::Engine::evaluate_function (this=this@entry=0x7ffff4177640 <engine>, task=...) at torch/csrc/autograd/engine.cpp:137
#20 0x00007ffff385d8ab in torch::autograd::Engine::thread_main (this=this@entry=0x7ffff4177640 <engine>, queue=std::shared_ptr (count 3, weak 0) 0x1583430)
    at torch/csrc/autograd/engine.cpp:96
#21 0x00007ffff386f264 in PythonEngine::thread_main (this=0x7ffff4177640 <engine>, queue=std::shared_ptr (count 3, weak 0) 0x1583430)
    at torch/csrc/autograd/python_engine.cpp:21
#22 0x00007ffff3860d98 in operator()<std::shared_ptr<torch::autograd::ReadyQueue>, void> (__object=<optimized out>, this=<optimized out>)
    at /py/envs/py2k/gcc/include/c++/functional:601
#23 _M_invoke<0ul, 1ul> (this=<optimized out>) at /py/envs/py2k/gcc/include/c++/functional:1732
#24 operator() (this=<optimized out>) at /py/envs/py2k/gcc/include/c++/functional:1720
#25 std::thread::_Impl<std::_Bind_simple<std::_Mem_fn<void (torch::autograd::Engine::*)(std::shared_ptr<torch::autograd::ReadyQueue>)> (torch::autograd::Engine*, std::shared_ptr<torch::autograd::ReadyQueue>)> >::_M_run() (this=<optimized out>) at /py/envs/py2k/gcc/include/c++/thread:115
#26 0x00007fffdcb3aa60 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#27 0x00007ffff7bc4182 in start_thread (arg=0x7fff4bfff700) at pthread_create.c:312
#28 0x00007ffff78f147d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
```

There is a manually installed mkl in the system. Is that the problem? Should I compile it from source?

**Comment by apaszke** [comment] 2017-06-03 11:52
I can't reproduce this. How did you install MKL? Is it the one from conda?

**Comment by onlytailei** [comment] 2017-06-03 16:10
@apaszke 
No. The MKL is installed separately before. I install the pytorch with pip and there is no instruction about mkl.

Then I tried to install the pytorch with conda, now it works. It seems that there are conflicts between pytorch and the original mkl in my system.

**Comment by soumith** [comment] 2017-06-03 16:48
there could be conflicts between pytorch and original MKL on the system. (Pytorch ships mkl runtime with it).

**Comment by seanbow** [comment] 2017-06-29 02:00
I have this same crash and backtrace when trying to run the tutorial. Except I have ubuntu 16.04, python 3.5.2, and cuda 8.0.

**Comment by albanD** [comment] 2019-11-27 16:29
Tentatively closing as it looks like some conflicts with our old packaging.

**Closed by albanD** 2019-11-27 16:29 UTC
