### ISSUE TITLE
The libtorch test ConstantPropagation.CustomClassesCanBePropagated fails on Apple Silicon

### ISSUE THREAD

**Issue by samestep** [pytorch/pytorch#88613] opened 2022-11-07 22:32 UTC
### 🐛 Describe the bug

I have tried this both on v1.13.0 and on `master` (currently commit 23a3eb37cfa52fcbfb766bd733cfa60b28b83f42) and get the same error. Specifically (following [these docs](https://github.com/pytorch/pytorch/blob/v1.13.0/docs/libtorch.rst#building-libtorch-using-python)):

```sh
gh repo clone pytorch/pytorch && cd pytorch
git checkout v1.13.0
git submodule update --init --recursive
mkdir build_libtorch && cd build_libtorch
python ../tools/build_libtorch.py
build/bin/test_jit
```

Failing output:

```
[----------] 1 test from ConstantPropagation
[ RUN      ] ConstantPropagation.CustomClassesCanBePropagated
unknown file: Failure
C++ exception with description "Expected to not find "quantized::linear_prepack" but found it
  %0 : NoneType = prim::Constant()
  %11 : QInt8(3, 3, strides=[3, 1], requires_grad=0, device=cpu) = prim::Constant[value= 1  1  1  1  1  1  1  1  1 [ QuantizedCPUQInt8Type{3,3}, qscheme: per_tensor_affine, scale: 1, zero_point: 0 ]]()
  %8 : __torch__.torch.classes.quantized.LinearPackedParamsBase = quantized::linear_prepack(%11, %0)
                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
  return (%8)
From CHECK-NOT: quantized::linear_prepack
" thrown in the test body.
[  FAILED  ] ConstantPropagation.CustomClassesCanBePropagated (2 ms)
[----------] 1 test from ConstantPropagation (2 ms total)
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 12.6.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.9.7 (default, Sep  8 2021, 10:47:21)  [Clang 12.0.5 (clang-1205.0.22.11)] (64-bit runtime)
Python platform: macOS-12.6.1-arm64-arm-64bit
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.2
[pip3] torch==1.12.1
[pip3] torchvision==0.13.1
[conda] Could not collect

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by jcaip** [comment] 2022-11-11 17:06
Hi Sam, can you try using the second set of instructions in the doc you linked? I think there may be some flags that you need for quantization.

**Comment by samestep** [comment] 2022-11-14 13:58
@jcaip ah OK, thanks for the suggestion! I tried the second set of instructions instead (i.e. with just `cmake` instead of `python`), adding the CLI arg `-DBUILD_TEST:BOOL=ON`, and got the same error.

**Comment by jcaip** [comment] 2022-11-14 19:24
@samestep Thanks for flagging this! I think this may be because QNNPACK is not supported for M1 macs. This [test](https://github.com/pytorch/pytorch/blame/e1c123d29a40ae1f3eae312a118e22769b1db870/test/cpp/jit/test_misc.cpp#L3188) should probably be wrapped in an `#ifdef` to check for QNNPACK support before it runs.

**Comment by andrewor14** [comment] 2023-11-17 20:23
@jcaip Is the error expected behavior since QNNPACK is simply not supported on M1 then? Should we close this issue in that case?

**Closed** 2024-02-12 20:21 UTC
Labels: oncall: quantization, low priority, triaged, module: m1
