### ISSUE TITLE
support_out for gradient operator.

### ISSUE THREAD

**Issue by iramazanli** [pytorch/pytorch#56131] opened 2021-04-15 08:38 UTC
Currently gradient operator does not support out extension. It would be helpful to have this feature implemented.

**Comment by vadimkantorov** [comment] 2021-04-15 14:12
This would also be useful for inplace gradient computation also in Reversible Net context @albanD

**Comment by albanD** [comment] 2021-04-15 17:00
This is a duplicate of https://github.com/pytorch/pytorch/issues/29378
There is quite a bit of discussion there about why this is hard to do

Feel free to continue the discussion there.

**Closed by albanD** 2021-04-15 17:00 UTC
Labels: function request, triaged
