### ISSUE TITLE
`tensor[index_tensor] = value` fails in TorchScript

### ISSUE THREAD

**Issue by jatentaki** [pytorch/pytorch#32246] opened 2020-01-15 22:13 UTC
## 🐛 Bug

When assigning like `tensor[index_tensor] = value` (where value is a Python scalar) in TorchScript the call fails as below.

## To Reproduce
```python
@torch.jit.script
def method():
    mask1 = torch.tensor([True, True, True])
    mask2 = torch.zeros(mask1.shape[0], dtype=torch.int8)
    ixs = torch.arange(mask1.shape[0])[mask1]

    mask2[ixs] = -1
```

which fails with

```python
Traceback (most recent call last):
  File "../torch_repro2.py", line 3, in <module>
    @torch.jit.script
  File "/home/jatentaki/miniconda3/lib/python3.7/site-packages/torch/jit/__init__.py", line 1226, in script
    fn = torch._C._jit_script_compile(qualified_name, ast, _rcb, get_default_args(obj))
RuntimeError: 
Arguments for call are not valid.
The following operator variants are available:
  
  aten::index_put_(Tensor(a!) self, Tensor?[] indices, Tensor values, bool accumulate=False) -> (Tensor(a!)):
  Expected a value of type 'Tensor' for argument 'values' but instead found type 'int'.
  
  aten::index_put_(Tensor(a!) self, Tensor[] indices, Tensor values, bool accumulate=False) -> (Tensor(a!)):
  Expected a value of type 'List[Tensor]' for argument 'indices' but instead found type 'List[Optional[Tensor]]'.

The original call is:
at ../torch_repro2.py:9:4
@torch.jit.script
def method():
    mask1 = torch.tensor([True, True, True])
    mask2 = torch.zeros(mask1.shape[0], dtype=torch.int8)
    ixs = torch.arange(mask1.shape[0])[mask1]
    
    mask2[ixs] = -1
    ~~~~~~~~~~~~~~~ <--- HERE
```

I believe that the reason is that the call gets incorrectly desugared to `tensor.index_put_(index_tensor, value)` instead of `tensor.index_put_((index_tensor, ), torch.tensor(value))`, resulting in confusing error messages.

## Expected behavior
I would expect the code to get `jit`ed correctly, as it happens when manually desugaring.
```python
@torch.jit.script
def method():
    mask1 = torch.tensor([True, True, True])
    mask2 = torch.zeros(mask1.shape[0], dtype=torch.int8)
    ixs = torch.arange(mask1.shape[0])[mask1]

    mask2.index_put((ixs, ), torch.tensor(-1))
```

## Environment
PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] blas                      1.0                         mkl  
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] pytorch                   1.3.1               py3.7_cpu_0  [cpuonly]  pytorch
[conda] torchvision               0.4.2                  py37_cpu  [cpuonly]  pytorch

cc @suo

**Comment by driazati** [comment] 2020-01-15 23:03
Closing since this is a dupe of #27493, but you should be able to work around it in your code by wrapping `-1` in a tensor:

```python
@torch.jit.script
def method():
    mask1 = torch.tensor([True, True, True])
    mask2 = torch.zeros(mask1.shape[0], dtype=torch.int8)
    ixs = torch.arange(mask1.shape[0])[mask1]

    mask2[ixs] = torch.tensor(-1)
```

**Closed by driazati** 2020-01-15 23:03 UTC
Labels: jit
