### ISSUE TITLE
Exporting the operator 'triu'  to ONNX opset version 11 is not supported

### ISSUE THREAD

**Issue by laobadao** [pytorch/pytorch#51851] opened 2021-02-07 06:50 UTC
## To Reproduce

1. transformer model not support 'triu' operator to ONNX

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.1
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): conda 
 - Build command you used (if compiling from source):
 - Python version: 3.7.8
 - CUDA/cuDNN version: 10.1
 - GPU models and configuration:
 - Any other relevant information:

## Additional context

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by mathmax12** [comment] 2021-04-14 18:05
Hi @laobadao 
Did you get this fixed? I am facing the same issue.

**Comment by spandantiwari** [comment] 2021-04-26 18:23
We have just added a new op in ONNX called `trilu` in opset 14 which will be included in the latest release. Once it is available we will add support for it as we enable Opset 14.

**Comment by spandantiwari** [comment] 2021-04-26 18:27
Doing some issue consolidation here. There's an older issue tracking the support for `triu` and this is a duplicate of that: https://github.com/pytorch/pytorch/issues/32968.

Closing this one now. Let's track this request in that issue.

**Closed** 2021-04-26 18:27 UTC
Labels: enhancement, module: onnx, triaged
