### ISSUE TITLE
Windows, CUDA : OS call failed or operation not supported on this OS

### ISSUE THREAD

**Issue by Ashargin** [pytorch/pytorch#13117] opened 2018-10-25 13:02 UTC
## 🐛 Bug
```
OS call failed or operation not supported on this OS at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\torch\csrc\generic\StorageSharing.cpp:253
```
when iterating over DataLoader loader with cuda tensors.

## To Reproduce

1. Defining the dataset class where data is a pandas dataframe and target_cols is a list of the columns who should be the targets.
```python
device = torch.device('cuda:0')


class TrainDataset(Dataset):
    def __init__(self, data, target_cols):
        self.X = np.array(data.drop(target_cols, axis=1))
        self.y = np.array(data[target_cols])

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, idx):
        input = torch.from_numpy(self.X[idx]).float()
        target = torch.from_numpy(self.y[idx]).float()
        return input.to(device), target.to(device)
```
2. Creating an instance of the dataset and a DataLoader instance of it where X_train is my pandas dataframe and 'CONDOMINIUM_EXPENSES' is a column of the dataframe.
```python
X_train_set = TrainDataset(X_train, target_cols=['CONDOMINIUM_EXPENSES'])
X_train_loader = DataLoader(X_train_set, batch_size=4, shuffle=True, num_workers=4)
```
3. Simply iterating over it throws the message above.
```python
for data in X_train_loader:
```

Complete error message:
```
THTTCTuHdCauCHCdhaeCheccudkaCHkC h FAIeckFLAu IdLaFC Af fhiIiLl eecle=k =FfiAIL lfe=ile=cc:\progr:\aprcm:dogatrc\aa:\p\rpmmdaoirnogramtaid\mingramidatcaota\mia\minincniconoda3\ccodondan-bnda3da3\ld\conacod3a\p\-nbdac-olndd\aybtldo\py-pbrtlycdh\tpoyrtcoorchr__11ch_h5245_514987721495052254459\84wo7r7k9\t9o287072r945c\0h\49877wo2\csrr9c\ge02wk\ork\torcne\wtohork\\rrictccsh\csr\oSrtc\cg\oraegnrgerenerch\cseicShrc\ge\iScne\Storatroraiagng.cepShprgiac elr\SSihneitaorrinn=ggag..ecpp licSharpningep.cpp=  lliinen=e=25232552 533 3 ee error=rerrrororr63 :r= 6orOS3= 6c= a63 :3 : OS calll :  faOS ciOlSe ad lolr  coaplefrall fa iilatfaleeiion lndd ot su orpoerported  on otpehisr atOSi
don no o or opept supporerrateatditi on noot suon tnppho nrtiost  OSe
supported on thd ois OnS 
this OS
Process Process-2:
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 61, in _worker_loop
    data_queue.put((idx, samples))
  File "D:\Anaconda3\Lib\multiprocessing\queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "D:\Anaconda3\Lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "D:\Anaconda3\Lib\site-packages\torch\multiprocessing\reductions.py", line 108, in reduce_storage
    metadata = storage._share_cuda_()
RuntimeError: cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\torch\csrc\generic\StorageSharing.cpp:253
Process Process-4:
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 61, in _worker_loop
    data_queue.put((idx, samples))
  File "D:\Anaconda3\Lib\multiprocessing\queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "D:\Anaconda3\Lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "D:\Anaconda3\Lib\site-packages\torch\multiprocessing\reductions.py", line 108, in reduce_storage
    metadata = storage._share_cuda_()
RuntimeError: cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\torch\csrc\generic\StorageSharing.cpp:253
Process Process-1:
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 61, in _worker_loop
    data_queue.put((idx, samples))
  File "D:\Anaconda3\Lib\multiprocessing\queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "D:\Anaconda3\Lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "D:\Anaconda3\Lib\site-packages\torch\multiprocessing\reductions.py", line 108, in reduce_storage
    metadata = storage._share_cuda_()
RuntimeError: cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\torch\csrc\generic\StorageSharing.cpp:253
Process Process-3:
Traceback (most recent call last):
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\Anaconda3\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Anaconda3\Lib\site-packages\torch\utils\data\dataloader.py", line 61, in _worker_loop
    data_queue.put((idx, samples))
  File "D:\Anaconda3\Lib\multiprocessing\queues.py", line 341, in put
    obj = _ForkingPickler.dumps(obj)
  File "D:\Anaconda3\Lib\multiprocessing\reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
  File "D:\Anaconda3\Lib\site-packages\torch\multiprocessing\reductions.py", line 108, in reduce_storage
    metadata = storage._share_cuda_()
RuntimeError: cuda runtime error (63) : OS call failed or operation not supported on this OS at c:\programdata\miniconda3\conda-bld\pytorch_1524549877902\work\torch\csrc\generic\StorageSharing.cpp:253
```

## Expected behavior

It is supposed to iterate over the DataLoader object.

## Environment

```
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0

OS: Microsoft Windows 10 Famille
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1060
Nvidia driver version: 391.35
cuDNN version: Probably one of the following:
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin\cudnn64_7.dll

Versions of relevant libraries:
[pip] Could not collect
[conda] cuda90                    1.0                           0    pytorch
[conda] pytorch                   0.4.0           py36_cuda90_cudnn7he774522_1  [cuda90]  pytorch
[conda] torchvision               0.2.1                     <pip>
```

Also I don't know why the script didn't find my version of pip but it is 18.1.

## Additional context

The code was working last night and it suddenly started throwing this error for no apparent reason. I didn't change anything in the code and I didn't reboot the computer either. I am not aware than any update was done concerning the OS or drivers.

cc @ngimel @SsnL @peterjc123 @nbcsm @guyang3532

**Comment by peterjc123** [comment] 2018-10-25 15:46
This is not supported by the current CUDA mechanics. So we could actually do nothing on this. I just wonder how you could make it work. However, you can read [here](https://pytorch.org/docs/stable/notes/windows.html#cuda-ipc-operations) for the workground for this issue.

**Comment by alexjc** [comment] 2020-04-24 11:02
This issue appears to be still applicable to 1.4 and 1.5 on windows.  As a workaround, you need to set `num_workers=0` to disable multiprocessing for the dataloaders.

(I'm using fastai2 `train_imagenette.py` and this exception shows up by default.)

**Comment by peterjc123** [comment] 2020-04-24 13:40
Related issue: https://github.com/pytorch/pytorch/issues/16943. Looks like CUDA IPC is supported on Windows now, but you have to use TCC mode.

**Comment by cristianPanaite** [comment] 2022-10-19 08:14
Hello @Ashargin,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. I tried to replicate this issue, but on the latest versions I don't get this error.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.

**Closed** 2022-10-19 13:17 UTC
Labels: module: windows, module: dataloader, module: cuda, triaged
