### ISSUE TITLE
`argsort()` can use the 0D tensor of a complex type value against error message

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#129309] opened 2024-06-22 16:44 UTC
### 🐛 Describe the bug

[argsort()](https://pytorch.org/docs/stable/generated/torch.argsort.html) cannot use the tensor of `complex` type values according to the error message as shown below:

```python
import torch

my_tensor = torch.tensor([7.+5.j])

torch.argsort(input=my_tensor) # Error

my_tensor = torch.tensor([[7.+5.j]])

torch.argsort(input=my_tensor) # Error
```

> RuntimeError: "sorting_kernel_method_name" not implemented for 'ComplexFloat'

But `argsort()` can use the 0D tensor of a `complex` type value against the error message as shown below:

```python
import torch

my_tensor = torch.tensor(7.+5.j)

torch.argsort(input=my_tensor)
# tensor(0)
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by malfet** [comment] 2024-06-26 00:16
Closing as duplicate of https://github.com/pytorch/pytorch/issues/129296

**Closed by malfet** 2024-06-26 00:16 UTC
