### ISSUE TITLE
`permute` + `conv2d` crash/memory corruption on CPU in torch 2.2

### ISSUE THREAD

**Issue by tobbez** [pytorch/pytorch#120211] opened 2024-02-19 23:24 UTC
### 🐛 Describe the bug

The following code should finish in a few seconds after printing 0 through 127:

```py
import torch
import torch.nn.functional


def reproducer(radius: int):
    image = torch.rand([1, 1024, 1024, 3], dtype=torch.float32, device=torch.device('cpu'))
    image = image.permute(0, 3, 1, 2)
    # creating the tensor above with the appropriate shape directly does not reproduce the issue
    #image = torch.rand([1, 3, 1024, 1024])

    kernel_x = torch.zeros([3, 1, 1, radius * 2 + 1], device=image.device)

    image = torch.nn.functional.conv2d(image, kernel_x, groups=image.shape[-3])


for i in range(0, 128):
    print(i)
    reproducer(radius=i)
```

but (at least in certain environments) it crashes after printing `7`. Starting at other numbers can result in different failure modes (such as burning CPU for minutes or longer).

Best guess so far is that it's connected to the CPU in use, with 3 out of 3 reporters who encountered the issue and who posted their CPU model used Ryzen 9 7000 series CPUs (7950X, 7950X, 7900X).

The attached version info is from WSL1, but I could reproduce on:

- WSL1 / Python 3.10 / torch 2.2.0
- WSL1 / Python 3.10 / `torch==2.3.0.dev20240219+cpu`
- Windows (native) / Python 3.10 / torch 2.2.0
- Windows (native) / Python 3.12 / torch 2.2.0

Here's the CPU section from `collect_env.py` on the native Windows side:

```
CPU:
Architecture=9
CurrentClockSpeed=4501
DeviceID=CPU0
Family=107
L2CacheSize=16384
L2CacheSpeed=
Manufacturer=AuthenticAMD
MaxClockSpeed=4501
Name=AMD Ryzen 9 7950X 16-Core Processor
ProcessorType=3
Revision=24834
```

The issue does **not** occur on torch 2.1.2.

It was originally reported in:
- https://github.com/Acly/krita-ai-diffusion/issues/401
- https://github.com/Acly/comfyui-inpaint-nodes/issues/15

### Versions

```
PyTorch version: 2.2.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Address sizes:       36 bits physical, 48 bits virtual
Byte Order:          Little Endian
CPU(s):              32
On-line CPU(s) list: 0-31
Vendor ID:           AuthenticAMD
Model name:          AMD Ryzen 9 7950X 16-Core Processor
CPU family:          25
Model:               97
Thread(s) per core:  2
Core(s) per socket:  16
Socket(s):           1
Stepping:            2
CPU max MHz:         4501.0000
CPU min MHz:         0.0000
BogoMIPS:            9002.00
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave osxsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl avx512vbmi umip pku avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid
Virtualization:      AMD-V
Hypervisor vendor:   Windows Subsystem for Linux
Virtualization type: container

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==2.2.0+cpu
[pip3] torchaudio==2.2.0+cpu
[pip3] torchvision==0.17.0+cpu
[conda] Could not collect
```

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by mingfeima** [comment] 2024-02-20 04:52
@tobbez is this a regression ? does torch 2.1 works fine ?

**Comment by tobbez** [comment] 2024-02-20 20:55
Yes, like I wrote in the initial report, torch 2.1 works fine.

**Comment by mingfeima** [comment] 2024-02-21 03:34
@ZailiWang do we have access to amd CPUs? Could you please help debug whether this is related to onednn upgrade?

@tobbez could you please paste your crash log with this environment variable `export DNNL_VERBOSE=2`?

**Comment by tobbez** [comment] 2024-02-21 11:51
```
$ DNNL_VERBOSE=2 python reproducer.py
0
onednn_verbose,info,oneDNN v3.3.2 (commit 2dc95a2ad0841e29db8b22fbccaf3e5da7992b01)
onednn_verbose,info,cpu,runtime:OpenMP,nthr:16
onednn_verbose,info,cpu,isa:Intel AVX-512 with Intel DL Boost and bfloat16 support
onednn_verbose,info,gpu,runtime:none
onednn_verbose,info,graph,backend,0:dnnl_backend
onednn_verbose,primitive,info,template:operation,engine,primitive,implementation,prop_kind,memory_descriptors,attributes,auxiliary,problem_desc,exec_time
onednn_verbose,graph,info,template:operation,engine,partition_id,partition_kind,op_names,data_formats,logical_tensors,fpmath_mode,backend,exec_time
onednn_verbose,primitive,create:cache_miss,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:Abcde16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1024kw1sw1dw0pw0,1.83008
onednn_verbose,primitive,create:cache_miss,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:Abcde16a::f0,attr-scratchpad:user ,,3x1x1x1x1,0.808838
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:Abcde16a::f0,attr-scratchpad:user ,,3x1x1x1x1,0.00878906
onednn_verbose,primitive,exec,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:Abcde16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1024kw1sw1dw0pw0,12.113
1
onednn_verbose,primitive,create:cache_miss,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1022kw3sw1dw0pw0,0.125
onednn_verbose,primitive,create:cache_miss,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x3,0.104004
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x3,0.00708008
onednn_verbose,primitive,exec,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1022kw3sw1dw0pw0,10.7271
2
onednn_verbose,primitive,create:cache_miss,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1020kw5sw1dw0pw0,0.14502
onednn_verbose,primitive,create:cache_miss,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x5,0.100098
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x5,0.0109863
onednn_verbose,primitive,exec,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1020kw5sw1dw0pw0,0.565918
3
onednn_verbose,primitive,create:cache_miss,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1018kw7sw1dw0pw0,0.13501
onednn_verbose,primitive,create:cache_miss,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x7,0.11084
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x7,0.00610352
onednn_verbose,primitive,exec,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1018kw7sw1dw0pw0,0.63916
4
onednn_verbose,primitive,create:cache_miss,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1016kw9sw1dw0pw0,0.258057
onednn_verbose,primitive,create:cache_miss,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x9,0.13501
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x9,0.00708008
onednn_verbose,primitive,exec,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1016kw9sw1dw0pw0,0.64502
5
onednn_verbose,primitive,create:cache_miss,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1014kw11sw1dw0pw0,0.252197
onednn_verbose,primitive,create:cache_miss,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x11,0.101074
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x11,0.0129395
onednn_verbose,primitive,exec,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1014kw11sw1dw0pw0,0.752197
6
onednn_verbose,primitive,create:cache_miss,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1012kw13sw1dw0pw0,0.114014
onednn_verbose,primitive,create:cache_miss,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x13,0.0810547
onednn_verbose,primitive,exec,cpu,reorder,jit:uni,undef,src_f32::blocked:abcde::f0 dst_f32:p:blocked:deAbc16a::f0,attr-scratchpad:user ,,3x1x1x1x13,0.00488281
onednn_verbose,primitive,exec,cpu,convolution,brdgmm_dw:avx512_core,forward_training,src_f32::blocked:acdb::f0 wei_f32:ap:blocked:deAbc16a::f0 bia_undef::undef::: dst_f32::blocked:acdb::f0,attr-scratchpad:user ,alg:convolution_direct,g3mb1_ic3oc3_ih1024oh1024kh1sh1dh0ph0_iw1024ow1012kw13sw1dw0pw0,0.672852
7
Floating point exception (core dumped)
```

Thanks for the onednn pointer, I was wondering if it was possible to control the runtime dispatch.

The issue does not reproduce when running with `ONEDNN_MAX_CPU_ISA=AVX2`, which would implicate AVX512.

**Comment by chunyuan-w** [comment] 2024-02-26 08:16
@yanbing-j helped find that this issue is caused by oneDNN upgrade (https://github.com/pytorch/pytorch/pull/112700) and have reported the issue to oneDNN team to see if they can fix it and include it in the next oneDNN release.

**Comment by albanD** [comment] 2024-02-26 23:10
@chunyuan-w can you send a patch to disable oneDNN for this particular set of inputs where we know it will fail to make sure we fix this before the next release of PyTorch
?

**Comment by vpirogov** [comment] 2024-02-26 23:18
The issue is fixed in [oneDNN v3.4 release candidate](https://github.com/oneapi-src/oneDNN/releases/tag/v3.4-rc), so updating to v3.4-rc or the tip of rls-v3.4 branch is a viable option.

**Comment by albanD** [comment] 2024-02-26 23:39
Is that something you're confident you can do before the [branch cut in two weeks](https://dev-discuss.pytorch.org/t/pytorch-release-2-3-0-call-for-features/1872)?

**Comment by mingfeima** [comment] 2024-02-27 01:59
CC @Guobing-Chen

**Comment by chunyuan-w** [comment] 2024-02-28 03:06
@albanD oneDNN has quickly fixed the issue based on **v3.3** which we verified at local build. We are conducting more broad test and would suggest to upgrade OneDNN to a minor update version (**from current v3.3.2 to v3.3.5**) for PyTorch 2.3

**Comment by chunyuan-w** [comment] 2024-03-01 04:13
The PR to upgrade oneDNN to v3.3.5 to fix this issue has been created: https://github.com/pytorch/pytorch/pull/120767

**Comment by malfet** [comment] 2024-03-06 17:18
@chunyuan-w same as for another issue, please mention commit that fix this particular regression somewhere

**Comment by chunyuan-w** [comment] 2024-03-07 01:32
> @chunyuan-w same as for another issue, please mention commit that fix this particular regression somewhere

This is the commit which fixed the crash issue: https://github.com/oneapi-src/oneDNN/commit/bbaec145f8c64818fd5c3ed2cb9e2ae69daef887 (it's the same as the fix commit mentioned here https://github.com/pytorch/pytorch/issues/120406#issuecomment-1977755208).

**Comment by chunyuan-w** [comment] 2024-03-22 06:47
PR to upgrade oneDNN to v3.3.5 has landed: https://github.com/pytorch/pytorch/pull/120767
The issue should have already been fixed on main branch and the coming 2.3 release.

**Comment by atalman** [comment] 2024-04-02 18:48
Closing. We will validate in 2.3 release RC

**Closed by atalman** 2024-04-02 18:48 UTC
Labels: needs reproduction, module: crash, module: nn, module: convolution, triaged, module: regression

**Comment by PaliC** [comment] 2024-04-10 20:52
Validated that the script no longer crashes for the distribution of torch from `https://download.pytorch.org/whl/test/cpu` (relevant release rc)
