### ISSUE TITLE
Broadcasting for 1-dimensional tensors

### ISSUE THREAD

**Issue by psubodiosa** [pytorch/pytorch#105739] opened 2023-07-21 14:25 UTC
### 🐛 Describe the bug

Minimal bug can be recreated by the following:

```
import torch
def loss_func(x,y):
    return torch.mean((x-y)**2)

x = torch.rand(10,1)
y = torch.rand(10)

print(loss_func(x,y) == loss_func(torch.squeeze(x),y))
print(torch.abs(loss_func(x,y)-loss_func(torch.squeeze(x),y))>0.01)
```

### Versions

Pytorch Version 2.01

**Comment by janeyx99** [comment] 2023-07-24 18:06
Hi! It looks like the discrepancy happens very early on in loss_func, without the need for torch.mean or the **2. `x-y` returns something that is a completely different shape compared to `torch.squeeze(x)-y` already. The following shows that the broadcasting order matters. If you don't squeeze, the result will be broadcast into the bigger dimensioned tensor. If you squeeze first, you would not need broadcasting. I believe this is to be expected.

```
import torch
x = torch.tensor([10, 20, 30, 40, 50]).reshape(5, 1)
y = torch.tensor([1, 2, 3, 4, 5])
a = x - y 
b = torch.squeeze(x) - y
```

Returns:
![image](https://github.com/pytorch/pytorch/assets/31798555/f1267684-13e5-4514-867c-f5ff28dc8058)

**Comment by janeyx99** [comment] 2023-07-24 18:09
Closing the issue as I believe this is expected behavior, but feel free to reopen with any requests for action items on our end!

**Closed by janeyx99** 2023-07-24 18:09 UTC
Labels: triaged
