### ISSUE TITLE
libtorch 1.3.1 c4146

### ISSUE THREAD

**Issue by zhjw0927** [pytorch/pytorch#32038] opened 2020-01-10 13:21 UTC
Previously, my desktop was using libtorch 1.2.0 release and everything worked.
After generating the exe, I wanted to take the notebook for on-site deployment. I installed libtorch on the notebook. At that time, it had been updated to 1.3.1 but reported the C4146 error. Even if I commented out everything in the main function, the error was still reported.
In the end, I had to re-download 1.2.0 on my laptop to resolve this issue.
I wonder if this problem is a bug?

**Comment by peterjc123** [comment] 2020-01-10 13:32
Duplicate of #29654

**Closed by peterjc123** 2020-01-10 13:32 UTC
