### ISSUE TITLE
RuntimeError: Expected a proper Tensor but got None (or an undefined Tensor in C++) for argument #0 'grad_y'

### ISSUE THREAD

**Issue by lsch0lz** [pytorch/pytorch#103430] opened 2023-06-12 13:54 UTC
### 🐛 Describe the bug

I get the error ```RuntimeError: Expected a proper Tensor but got None (or an undefined Tensor in C++) for argument #0 'grad_y'``` when trying to pass the encoded Tensors to an ```torch.nn.LSTM``` layer.
Any suggestions on how I can fix this? Thanks!

This is my model:

```
import torch

from fastai.layers import TimeDistributed, Flatten, LinBnDrop
from fastai.torch_core import params, Module
from fastai.vision.learner import create_body
from torchvision.models import resnet34


class LSTM(Module):
    def __init__(self, arch=resnet34, n_out=101, num_rnn_layers=5):
        self.encoder = TimeDistributed(torch.nn.Sequential(create_body(arch(pretrained=True), pretrained=True), torch.nn.AdaptiveAvgPool2d(1), Flatten()))
        self.lstm = torch.nn.LSTM(512, 512, num_layers=num_rnn_layers, batch_first=True)
        self.head = LinBnDrop(num_rnn_layers*512, n_out)

    def forward(self, x):
        x = torch.stack(x, dim=1)
        x = self.encoder(x)
        bs = x.shape[0]
        _, (h, _) = self.lstm(x)
        return self.head(h.view(bs, -1))
```

Here is the full Traceback:
```
Traceback (most recent call last):-------------------------------------------------------------------------------| 0.00% [0/333 00:00<?]
  File "/Users/lukasscholz/repositorys/sequence_classification/main.py", line 43, in <module>
    learn.lr_find()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/callback/schedule.py", line 293, in lr_find
    with self.no_logging(): self.fit(n_epoch, cbs=cb)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 264, in fit
    self._with_events(self._do_fit, 'fit', CancelFitException, self._end_cleanup)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 253, in _do_fit
    self._with_events(self._do_epoch, 'epoch', CancelEpochException)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 247, in _do_epoch
    self._do_epoch_train()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 239, in _do_epoch_train
    self._with_events(self.all_batches, 'train', CancelTrainException)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 205, in all_batches
    for o in enumerate(self.dl): self.one_batch(*o)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 235, in one_batch
    self._with_events(self._do_one_batch, 'batch', CancelBatchException)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 223, in _do_one_batch
    self._do_grad_opt()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 211, in _do_grad_opt
    self._with_events(self._backward, 'backward', CancelBackwardException)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 199, in _with_events
    try: self(f'before_{event_type}');  f()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/learner.py", line 207, in _backward
    def _backward(self): self.loss_grad.backward()
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/torch/_tensor.py", line 478, in backward
    return handle_torch_function(
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/torch/overrides.py", line 1551, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/fastai/torch_core.py", line 382, in __torch_function__
    res = super().__torch_function__(func, types, args, ifnone(kwargs, {}))
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/torch/_tensor.py", line 1295, in __torch_function__
    ret = func(*args, **kwargs)
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/Users/lukasscholz/repositorys/sequence_classification/venv/lib/python3.10/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: Expected a proper Tensor but got None (or an undefined Tensor in C++) for argument #0 'grad_y'
```

### Versions

PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.4 (arm64)
GCC version: Could not collect
Clang version: 14.0.3 (clang-1403.0.22.14.1)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.11 (main, Apr  7 2023, 07:24:53) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.4-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] numpy==1.24.3
[pip3] timesformer-pytorch==0.4.1
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[conda] Could not collect

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki @malfet

**Comment by malfet** [comment] 2023-06-12 14:21
Can you please provide a minimal reproducible example, as there is nothing obviously wrong with the module example you've provided.
 Also, are you running on CPU or MPS device?

**Comment by lsch0lz** [comment] 2023-06-12 16:26
Sure! 
Sorry if this isnt exactly minimal, but I couldnt compress it to a more minimal approch. 
lstm.py:
```
import torch

from fastai.layers import TimeDistributed, Flatten, LinBnDrop
from fastai.torch_core import params, Module
from fastai.vision.learner import create_body
from torchvision.models import resnet34


class LSTM(Module):
    def __init__(self, arch=resnet34, n_out=101, num_rnn_layers=5):
        self.encoder = TimeDistributed(torch.nn.Sequential(create_body(arch(pretrained=True), pretrained=True), torch.nn.AdaptiveAvgPool2d(1), Flatten()))
        self.lstm = torch.nn.LSTM(512, 512, num_layers=num_rnn_layers, batch_first=True)
        self.head = LinBnDrop(num_rnn_layers*512, n_out)

    def forward(self, x):
        x = torch.stack(x, dim=1)
        x = self.encoder(x)
        bs = x.shape[0]
        _, (h, _) = self.lstm(x)
        return self.head(h.view(bs, -1))


def lstm_splitter(model): return [params(model.encoder), params(model.lstm)+params(model.head)]
```

dataloader.py:
```
import av
import os

from fastai.data.transforms import get_files


class DataLoader:
    def __init__(self, dest_video: str, dest_frames: str, video_extension: str):
        self.video_extension = video_extension
        self.dest_video = dest_video
        self.dest_frames = dest_frames

    def get_videos(self) -> list:
        return list(get_files(self.dest_video, extensions=[self.video_extension]))

    def extract_frames(self):
        videos = self.get_videos()
        for video in videos:
            video_parent = video.parts[3] + "/" + video.parts[4]
            if not os.path.exists(f"{self.dest_frames}/{video_parent[:-4]}"):
                os.makedirs(f"{self.dest_frames}/{video_parent[:-4]}")
                _video = av.open(str(video))
                for id, frame in enumerate(_video.decode(0)):
                    yield id, frame.to_image(), video_parent[:-4]

    def save_frames(self):
        if not os.path.exists(self.dest_frames):
            os.mkdir(self.dest_frames)
        for id, frame, path in self.extract_frames():
            frame.save(f"{self.dest_frames}/{path}/{id}.jpg")
```

datapipeline.py:
```
import os
from pathlib import Path

import torch
from fastai.torch_core import show_image
from fastai.vision.core import PILImage
from fastcore.basics import fastuple, store_attr
from fastcore.transform import Transform
from torch import Tensor, tensor


class DataPipeline:
    def __init__(self, path: str):
        self.path = path

    def get_instances(self):
        sequence_paths = []
        path = Path(self.path)
        for actions in path.iterdir():
            for instance in actions.iterdir():
                sequence_paths.append((str(instance)))
        return sequence_paths


class ImageTuple(fastuple):
    def show(self, ctx=None, **kwargs):
        n = len(self)
        img0, img1, img2 = self[0], self[n//2], self[n-1]
        if not isinstance(img1, Tensor):
            t0, t1, t2 = tensor(img0), tensor(img1), tensor(img2)
            t0, t1, t2 = t0.permute(2, 0, 1), t1.permute(2, 0, 1), t2.permute(2, 0, 1)
        else:
            t0, t1, t2 = img0, img1, img2
        return show_image(torch.cat([t0, t1, t2], dim=2), ctx=ctx, **kwargs)


def ls_sorted(path: Path):
    files = sorted(os.listdir(path))
    return sorted(files, key=lambda f: int(Path(f).stem))


class ImageTupleTfm(Transform):
    def __init__(self, seq_len=20):
        self.seq_len = seq_len
        store_attr()

    def encodes(self, path: Path):
        frames = ls_sorted(path)
        n_frames = len(frames)
        s = slice(0, min(self.seq_len, n_frames))
        return ImageTuple(tuple(PILImage.create(str(path)+"/"+f) for f in frames[s]))
```

main.py
```
import os
import argparse

from fastai.data.core import Datasets
from fastai.data.transforms import RandomSplitter, parent_label, Categorize, ToTensor, IntToFloatTensor, Normalize
from fastai.learner import Learner
from fastai.metrics import accuracy
from fastai.vision.augment import Resize
from fastai.callback.schedule import lr_find

from fastai.vision.core import imagenet_stats
from pathlib import Path

from dataloader import DataLoader
from datapipeline import ImageTupleTfm, DataPipeline
from models.lstm import LSTM, lstm_splitter
from models.resnet import CNN, simple_splitter
from models.timesformer import TimesFormer


def parse_arguments():
    parser = argparse.ArgumentParser()

    # Data loader arguments
    parser.add_argument('--video_path', type=str, default="", help='path to videos in folders, if the frames arent already extracted')
    parser.add_argument('--frames_path', type=str, default="", required=True,
                        help='path to where the frames should be saved')
    parser.add_argument('--video_extension', type=str, default=".avi", help='extension of video files')

    # Data pipeline arguments
    parser.add_argument('--sequence_length', type=int, default=5, help='length of sequence of frames')

    # Training arguments
    parser.add_argument('--model', type=str, default="cnn", choices=["cnn", "lstm", "transformers"],
                        help='model to train')
    parser.add_argument('--batch_size', type=int, default=32, help='batch size')
    parser.add_argument('--epochs', type=int, default=3, help='number of epochs')
    parser.add_argument('--lr', type=float, default=1e-3, help='learning rate')
    parser.add_argument('--img_resize', type=int, default=64, help='resize images to this size')
    parser.add_argument("--freeze_epochs", type=int, default=3, help="number of epochs to freeze the pretrained model")

    return parser.parse_args()


def train(opt: argparse.ArgumentParser()):
    if opt.video_path:
        data_loader = DataLoader(dest_video=opt.video_path, dest_frames=opt.frames_path,
                                 video_extension=opt.video_extension)
        data_loader.save_frames()

    data_pipeline = DataPipeline(path=opt.frames_path)
    instances_path = data_pipeline.get_instances()
    instances_path = [Path(path) for path in instances_path]

    splits = RandomSplitter()(instances_path)

    ds = Datasets(instances_path, tfms=[[ImageTupleTfm(opt.sequence_length)], [parent_label, Categorize]],
                  splits=splits)
    dls = ds.dataloaders(bs=opt.batch_size, after_item=[ToTensor, Resize(opt.img_resize)],
                         after_batch=[IntToFloatTensor, Normalize.from_stats(*imagenet_stats)])

    if opt.model == "cnn":
        model = CNN()
        learn = Learner(dls, model, metrics=[accuracy], splitter=simple_splitter)
        learn.fine_tune(opt.epochs, opt.lr, freeze_epochs=opt.freeze_epochs)

    if opt.model == "lstm":
        model = LSTM()
        learn = Learner(dls, model, metrics=[accuracy], splitter=lstm_splitter)
        learn.fine_tune(opt.epochs, opt.lr)

    if opt.model == "transformers":
        model = TimesFormer(
            dim=128,
            image_size=128,
            patch_size=16,
            num_frames=opt.sequence_length,
            num_classes=101,
            depth=12,
            heads=8,
            dim_head=64,
            attn_dropout=0.1,
            ff_dropout=0.1
        )
        learn_tf = Learner(dls, model, metrics=[accuracy])
        learn_tf.fit_one_cycle(opt.epochs, opt.lr)


if __name__ == "__main__":
    opt = parse_arguments()
    train(opt)
```

You can run the script like this:
```python main.py --video_path "./data/video/" --frames_path "./data/frames/" --model "lstm"``` and the script will automatically extract and save the frames from the given videos.

I use the UCF101 Dataset to train this model. For the resnet and TimesFormer everything works fine, but for the LSTM not.
You can download the dataset by yourself: 
```wget -P --no-check-certificate https://www.crcv.ucf.edu/data/UCF101/UCF101.rar``` and unrar the files, so that the .avi files are in their respective directory.

The ```video_path``` should be the directory where the unrared UCF-101 directory is. So here it would be ./video/:
│--- frames
   │--- ApplyEyeMakeup
      │--- v_ApplyEyeMakeup_g01_c01 ...
   │--- ApplyLipstick
   │--- Archery
│--- video
   │--- UCF-101
      │--- ApplyEyeMakeup
         │--- v_ApplyEyeMakeup_g01_c01.avi
      │--- ApplyLipstick 
      │--- Archery

Also you need to create the ```./data/frames/``` directory, so the script can extract the images from the .avi files
For reference I used this implementation:
https://docs.fast.ai/tutorial.image_sequence.html#ucf101-action-recognition
![Bildschirmfoto 2023-06-12 um 18 25 41](https://github.com/pytorch/pytorch/assets/40420097/615d4472-d3bc-4c12-a41b-d46ee0b51682)

**Comment by jbschlosser** [comment] 2023-06-16 19:23
To help us debug this, is it possible to rerun setting `TORCH_SHOW_CPP_STACKTRACES=1` and share with us the C++ stack-trace that results?

**Comment by lsch0lz** [comment] 2023-06-19 09:05
The nightly build is working. Thanks @jbschlosser!

**Comment by mikaylagawarecki** [comment] 2023-06-20 16:22
Closing as complete since this is fixed on the nightly. Feel free to re-open if there are further issues

**Closed by mikaylagawarecki** 2023-06-20 16:22 UTC
Labels: needs reproduction, module: nn, triaged, module: macos
