### ISSUE TITLE
torch.tensor with list of arrays orders of magnitude slower than np.array

### ISSUE THREAD

**Issue by futscdav** [pytorch/pytorch#57467] opened 2021-05-03 15:42 UTC
Creating a tensor from a list of np.arrays is unreasonably slower than just converting the list into a np.array first.

```
import torch
import numpy as np
from time import perf_counter as time

print(torch.__version__)

device = 'cuda:0'
# Init cuda driver
_ = torch.tensor(np.zeros((100,100)), device=device, dtype=torch.float32)

data = [np.empty((3,1024,1024)) for _ in range(0, 10)]
# Case 1
start = time()
_1 = torch.tensor(np.array(data), device=device, dtype=torch.float32)
print(f'Case 1 time: {time() - start}')

# Case 2
start = time()
_2 = torch.tensor(data, device=device, dtype=torch.float32)
print(f'Case 2 time: {time() - start}')

assert (_1 == _2).all(), "Arrays differ."
```

Output:
```
1.8.1
Case 1 time: 0.06299801508430392
Case 2 time: 1.9666567809181288
```

I don't know if this is a super common use case, but it seems plausible enough for constructing custom batches and I'm not really sure if there is a good reason it should be so much slower.

cc @mruberry @rgommers @heitorschueroff @VitalyFedyunin @ngimel

**Comment by rgommers** [comment] 2021-05-03 16:16
Thanks for the report @futscdav. This is a duplicate of gh-13918. That has 2 PRs pending to fix the issue. gh-51731 seems to be the preferred fix, but it hasn't moved in a month - I'll ping on there. And will close this as a duplicate.

**Closed by rgommers** 2021-05-03 16:16 UTC
Labels: module: numpy, module: performance, triaged
