### ISSUE TITLE
Does pytorch1.11 support pypy3.7 interpreter？

### ISSUE THREAD

**Issue by sataliulan** [pytorch/pytorch#74957] opened 2022-03-30 15:23 UTC
### 🚀 The feature, motivation and pitch

Hi there， as mentioned above，I want to know that if pypy3.7 interpreter (or above version) is supported by pytorch1.11，as pypy interpreter is known for its speed.

**Comment by malfet** [comment] 2022-03-30 18:53
Closing as duplicate of https://github.com/pytorch/pytorch/issues/17835

**Closed by malfet** 2022-03-30 18:53 UTC
