### ISSUE TITLE
torch.normal only issues error for negative sigma when shape argument is given

### ISSUE THREAD

**Issue by jeffwillette** [pytorch/pytorch#49998] opened 2021-01-02 05:37 UTC
## 🐛 Bug

As explained in [this forum thread](https://discuss.pytorch.org/t/how-does-torch-normal-work-with-a-negative-standard-deviation/107571/3) torch.normal only give an error for negative sigma when there is no size argument given in. Code examples are below.

## To Reproduce

This code cause an error...

```
torch.manual_seed(8)
torch.normal(0, -1, (10, ))

# output
# RuntimeError                              Traceback (most recent call last)
# <ipython-input-6-f3bb1e6c1119> in <module>()
    #   1 torch.manual_seed(8)
# ----> 2 torch.normal(0, -1, (10, ))

# RuntimeError: normal_ expects std > 0.0, but found std=-1
```

while this code causes no error...

```
mu = torch.tensor(0.0)
sigma = torch.tensor(-3.0)
torch.normal(mu, sigma)

# ...output
>>> torch.normal(mu, sigma)
tensor(-3.6977)
>>> torch.normal(mu, sigma)
tensor(-3.0448)
>>> torch.normal(mu, sigma)
tensor(-0.2327)
```

## Expected behavior

I would expect that the error reporting would be consistent and that a negative standard deviation on a singleton sample would also give an error.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.7.0+cu110
 - OS (e.g., Linux): 20.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): N/A
 - Python version: 3.8.5

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @fritzo @neerajprad @alicanb @vishwakftw @nikitaved @pbelevich

**Comment by ngimel** [comment] 2021-01-04 05:09
Thanks for reporting, it's a bug. The problematic functions are here https://github.com/pytorch/pytorch/blob/e44b2b72bd4ccecf9c2f6c18d09c11eff446b5a3/aten/src/ATen/native/DistributionTemplates.h#L219-L249, they don't check that std is positive. 
High pri for silent correctness, however, checking if std is valid is a perf penalty, we should discuss if we want it.

**Comment by jeffwillette** [comment] 2021-01-04 05:55
As I said in the forum thread I came across this bug in a repository where the user had no positive condition such as training the parameter in the log-space or using a softplus. I was confused as to why their code was working and more confused when I saw no error in Pytorch. 

I would strongly side in favor of checking even if there is a performance penalty because it is:

- very confusing that it fails only with the size argument
- silently works even though the user may be totally wrong in the way that they call it.

**Comment by mruberry** [comment] 2021-01-04 18:12
We would accept a PR fixing this. We're OK with checking the values of the tensor and paying the performance penalty and implicitly synchronizing on CUDA. We should document the cross-device sync.

**Comment by gchanan** [comment] 2021-01-04 18:18
@ngimel argued we can't (easily) on-device assert TensorIterator because our lambdas aren't complex enough.  It would be good to figure out how difficult it would be to do this.

**Comment by jeffwillette** [comment] 2021-01-05 03:27
I do not think it would be a good idea to add another inconsistent behavior on top of an existing one. If it can't be synced across CPU/CUDA. Would it be better to just document that a single sample (without size arg) does not enforce a positive sigma constraint?

**Comment by fritzo** [comment] 2021-01-22 20:00
(removing `module: distributions` label because the `distributions.Normal` wrapper already checks for negative sigma)

**Comment by ousou** [comment] 2021-01-26 13:14
I noticed that the same error is present in PyTorch version 1.7.1 also when using the distributions.Normal wrapper. This makes the log_prob function return NaN on any value:

```
>>> a = torch.distributions.Normal(0,-1)
>>> a.log_prob(0)
tensor(nan)
>>> a.log_prob(1)
tensor(nan)
>>> a.log_prob(0.5)
tensor(nan)
>>> a.log_prob(-0.5)
tensor(nan)
```

**Comment by kshitij12345** [comment] 2021-01-27 06:13
@ousou Looks to be fixed in master. Can you try nightly

```python
>>> a = torch.distributions.Normal(0,-1)
ValueError: The parameter scale has invalid values
```

**Comment by kurtamohler** [comment] 2021-04-27 00:20
This issue was fixed by #51317, apparently I didn't link it to auto close.

**Closed by kurtamohler** 2021-04-27 00:20 UTC
Labels: high priority, module: correctness (silent), module: random, triaged

**Comment by pjh4993** [comment] 2021-07-05 14:21
I found that during training model, gradient can change sigma to negative
Is that not bug and responsibility to check for negative sigma is for user?

**Comment by kurtamohler** [comment] 2021-07-06 18:50
If the gradient calculation is changing sigma, that seems like an issue. The backward functions for `torch.normal` should only be setting gradients to zero, so sigma (called `std` here) shouldn't change: https://github.com/pytorch/pytorch/blob/056a8e0d5cc6b53dd574b77eebf273ded646f81e/tools/autograd/derivatives.yaml#L1051-L1062

Do you have a reproducer script @pjh4993?

**Comment by jkbh** [comment] 2022-05-04 21:28
I was wondering why the behaviour was changed from requiring std < 0 to std <= 0. The normal distrbution is not defined for std=0 and I think this can still lead to silent correctness and unexpectedly working code.

**Comment by kurtamohler** [comment] 2022-05-13 20:19
@jkbh, I'm not a math expert by any means, so I don't know any of the formalism behind this. But as the standard deviation of a normal distribution approaches 0, the range of possible outputs shrinks to include only the mean of the distribution. Numpy does this as well:

```python
>>> import numpy as np
>>> import torch
>>> np.random.normal(loc=1, scale=0, size=())
array(1.)
>>> torch.normal(mean=1, std=0, size=())
tensor(1.)
```

Maybe someone else here can give a more rigorous explanation than me
