### ISSUE TITLE
`max()` with an empty 1D tensor still gets error even if setting `dim=0` to it

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130086] opened 2024-07-04 03:00 UTC
### 🐛 Describe the bug

[max()](https://pytorch.org/docs/stable/generated/torch.max.html) with an empty 1D tensor gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.max(input=my_tensor) # Error
```

> RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

So, I set `dim=0` to `max()` following the error message above but it still gets other error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.max(input=my_tensor, dim=0) # Error
```

> IndexError: max(): Expected reduction dim 0 to have non-zero size.

In addition, `max()` with an empty 2D or 3D  tensor also gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.max(input=my_tensor) # Error

my_tensor = torch.tensor([[[]]])

torch.max(input=my_tensor) # Error
```

> RuntimeError: max(): Expected reduction dim to be specified for input.numel() == 0. Specify the reduction dim with the 'dim' argument.

But setting `dim=0` to `max()` following the error message above works properly as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.max(input=my_tensor, dim=0)
# torch.return_types.max(
# values=tensor([]),
# indices=tensor([], dtype=torch.int64))

my_tensor = torch.tensor([[[]]])

torch.max(input=my_tensor, dim=0)
# torch.return_types.max(
# values=tensor([], size=(1, 0)),
# indices=tensor([], size=(1, 0), dtype=torch.int64))
```

And in addition, `max()` with two of empty 1D or more D tesnors works even if not setting `dim=0` to it as shown below:

```python
import torch

tensor1 = torch.tensor([])
tensor2 = torch.tensor([])

torch.max(input=tensor1, other=tensor2)
# tensor([])

tensor1 = torch.tensor([[]])
tensor2 = torch.tensor([[]])

torch.max(input=tensor1, other=tensor2)
# tensor([], size=(1, 0))

tensor1 = torch.tensor([[[]]])
tensor2 = torch.tensor([[[]]])

torch.max(input=tensor1, other=tensor2)
# tensor([], size=(1, 1, 0))
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by albanD** [comment] 2024-07-08 14:47
Near duplicate of https://github.com/pytorch/pytorch/issues/130187
Let's continue discussion there since they have the same behavior

**Closed by albanD** 2024-07-08 14:47 UTC
