### ISSUE TITLE
memory leak(cpu, not gpu) in convolution layer

### ISSUE THREAD

**Issue by nido4010** [pytorch/pytorch#1272] opened 2017-04-17 11:18 UTC
Hello
I have a problem related to memory leak(cpu, not gpu) in ubuntu os.

when I run below code with cudnn 5.1 and 6.0, memory usage increases every epoch.
(memory leak doesn't occur with cudnn 5.0, but cudnn 5.0 is 2x slower than cudnn 5.1 and 6.0)
https://gist.github.com/nido4010/6f533f1e55ae1fd38a017533f72dd3e8

To manually select convolution algorithm, I revise the code, pytorch-master/torch/csrc/cudnn/Conv.cpp
the revised code is below
https://gist.github.com/nido4010/5686db92b1bbf1f252154b42b1cca95c
revision list 
1. comment out "findAlgorithm(state, handle, conv, benchmark, algo);" ( line 240)
2. cudnnConvolutionFwdAlgo_t fwdAlg =
CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED;( line 320)
3. cudnnConvolutionBwdDataAlgo_t bwdDataAlg =
CUDNN_CONVOLUTION_BWD_DATA_ALGO_WINOGRAD_NONFUSED;( line 367)
4. cudnnConvolutionBwdFilterAlgo_t bwdFilterAlg =
CUDNN_CONVOLUTION_BWD_FILTER_ALGO_WINOGRAD_NONFUSED;(line 395)

I check memory leak, while I change the forward, backward data, backward filter algorithm.
Algorithm list is provided in cudnn user guide.

when I select CUDNN_CONVOLUTION_FWD_ALGO_WINOGRAD_NONFUSED for forward convolution, which is newly added in cudnn 5.1, memory usage increases by about 90MB every epoch.

when I select CUDNN_CONVOLUTION_BWD_DATA_ALGO_WINOGRAD_NONFUSED for backward data convolution, which is newly added in cudnn 5.1, memory usage increases by about 120MB every epoch.

when I select CUDNN_CONVOLUTION_BWD_FILTER_ALGO_WINOGRAD_NONFUSED for backward filter convolution, which is newly added in cudnn 5.1, memory usage increases by about 130MB every epoch.

About the other algorithms, memory leak doesn't occur.
I have not yet test the above experiment with cudnn 6.0, but memory leak occur when I compile pytorch with cudnn 6.0.

Is there anybody who experiences memory leak like above??

Experiment setup
1. OS : linux mint 18.1(ubuntu 16.04.1)
2. cuda : 8.0
3. cudnn : 5.1
4. python : 2.7

**Comment by AleximusOrloff** [comment] 2017-04-18 10:41
I also observe memory leaks
torch7+cudnn 5.1 + ubuntu 14.04

**Comment by apaszke** [comment] 2017-04-18 13:25
cc @ngimel

**Comment by ngimel** [comment] 2017-04-21 23:49
I can't repro with cudnn 6.0.20 (Ubuntu 16.04, cuda 8.0, python 3.5)

**Comment by nido4010** [comment] 2017-04-22 05:31
@ngimel 
memory leak also occurs in python 3.5.
I observed above memory leak in tensorflow.
Do you use original ubunte 16.04??

**Comment by ngimel** [comment] 2017-04-23 00:39
I've used image built from the Dockerfile provided in the repo. A few packages have to be additionally installed to be able to run the example.

**Comment by nido4010** [comment] 2017-04-24 16:19
I test above example using docker image and memory leak also occurred. 
I don't know the exact cause.

**Comment by nido4010** [comment] 2017-04-26 16:17
@ngimel 
@AleximusOrloff 

Finally I solved this problem.
Maybe, the above memory leak is related to nvidia driver.
I replaced driver version 375(default in cuda 8.0) to 367, and memory leak doesn't occur

**Comment by AleximusOrloff** [comment] 2017-04-26 19:41
> I replaced driver version 375(default in cuda 8.0) to 367, and memory leak doesn't occur
I have 1080Ti, so that's not a case.
BTW I discovered that memory leaks only during backpropogandition

**Comment by nido4010** [comment] 2017-05-09 04:35
@AleximusOrloff
I recently change gtx 770 to gtx 1080ti.
I install nvidia driver 378.13, and memory leak doesn't occur

**Comment by egborbe** [comment] 2017-05-25 15:14
Hi, I am seeing this on TitanX maxwell with both 375.66 and 378.13
I use tensorflow.
I caught the memory leak in gdb but its totally closed source.
#0  __libc_calloc (n=8, elem_size=32) at malloc.c:3170
#1  0x00007fbbb885a292 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#2  0x00007fbbb885a511 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#3  0x00007fbbb87b9c62 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#4  0x00007fbbb86eb259 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#5  0x00007fbbb88f2f1c in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#6  0x00007fbbb88f33a7 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#7  0x00007fbbb88f3439 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#8  0x00007fbbb879dc81 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#9  0x00007fbbb87a98a8 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#10 0x00007fbbb88cd876 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#11 0x00007fbbb86cfd26 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#12 0x00007fbbb86cff53 in ?? () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#13 0x00007fbbb8815300 in cuLaunchKernel () from /usr/lib/x86_64-linux-gnu/libcuda.so.1
#14 0x00007fbbc2349441 in ?? () from /usr/lib/x86_64-linux-gnu/libcudnn.so.5
#15 0x00007fbbc2364fed in ?? () from /usr/lib/x86_64-linux-gnu/libcudnn.so.5
#16 0x00007fbbc1fc4c06 in ?? () from /usr/lib/x86_64-linux-gnu/libcudnn.so.5
#17 0x00007fbbc1fc7739 in ?? () from /usr/lib/x86_64-linux-gnu/libcudnn.so.5
#18 0x00007fbbc1fc84a8 in ?? () from /usr/lib/x86_64-linux-gnu/libcudnn.so.5
#19 0x00007fbbc1fbfb58 in ?? () from /usr/lib/x86_64-linux-gnu/libcudnn.so.5
#20 0x00007fbbc1e87041 in cudnnConvolutionBackwardFilter () from /usr/lib/x86_64-linux-gnu/libcudnn.so.5
#21 0x00007fbbcc81e2f1 in bool perftools::gputools::cuda::CudnnSupport::DoConvolveBackwardFilterImpl<float>(perftools::gputools::Stream*, int, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float>, perftools::gputools::dnn::ConvolutionDescriptor const&, perftools::gputools::dnn::FilterDescriptor const&, perftools::gputools::DeviceMemory<float>*, perftools::gputools::ScratchAllocator*, perftools::gputools::dnn::AlgorithmConfig const&, perftools::gputools::dnn::ProfileResult*) () from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#22 0x00007fbbcc81e894 in perftools::gputools::cuda::CudnnSupport::DoConvolveBackwardFilter(perftools::gputools::Stream*, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float>, perftools::gputools::dnn::ConvolutionDescriptor const&, perftools::gputools::dnn::FilterDescriptor const&, perftools::gputools::DeviceMemory<float>*, perftools::gputools::ScratchAllocator*, perftools::gputools::dnn::AlgorithmConfig const&, perftools::gputools::dnn::ProfileResult*) () from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#23 0x00007fbbcc86e025 in perftools::gputools::Stream::ThenConvolveBackwardFilterWithAlgorithm(perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float> const&, perftools::gputools::dnn::BatchDescriptor const&, perftools::gputools::DeviceMemory<float>, perftools::gputools::dnn::ConvolutionDescriptor const&, perftools::gputools::dnn::FilterDescriptor const&, perftools::gputools::DeviceMemory<float>*, perftools::gputools::ScratchAllocator*, perftools::gputools::dnn::AlgorithmConfig const&, perftools::gputools::dnn::ProfileResult*) ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#24 0x00007fbbcc60b350 in tensorflow::Conv2DSlowBackpropFilterOp<Eigen::GpuDevice, float>::Compute(tensorflow::OpKernelContext*) ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#25 0x00007fbbcc723a12 in tensorflow::BaseGPUDevice::Compute(tensorflow::OpKernel*, tensorflow::OpKernelContext*) ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#26 0x00007fbbcc7645e3 in tensorflow::(anonymous namespace)::ExecutorState::Process(tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, long long) ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#27 0x00007fbbcc764e5a in std::_Function_handler<void (), tensorflow::(anonymous namespace)::ExecutorState::ScheduleReady(tensorflow::gtl::InlinedVector<tensorflow::(anonymous namespace)::ExecutorState::TaggedNode, 8> const&, tensorflow::(anonymous namespace)::ExecutorState::TaggedNodeReadyQueue*)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#28 0x00007fbbccaa8da0 in std::_Function_handler<void (), Eigen::NonBlockingThreadPoolTempl<tensorflow::thread::EigenEnvironment>::NonBlockingThreadPoolTempl(int, tensorflow::thread::EigenEnvironment)::{lambda()#1}>::_M_invoke(std::_Any_data const&) () from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#29 0x00007fbbccaa8050 in std::_Function_handler<void (), tensorflow::thread::EigenEnvironment::CreateThread(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) ()
   from /usr/local/lib/python2.7/dist-packages/tensorflow/python/_pywrap_tensorflow.so
#30 0x00007fbbc976dc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#31 0x00007fbc29d686ba in start_thread (arg=0x7fb9a2ffd700) at pthread_create.c:333

**Comment by jcjohnson** [comment] 2017-08-15 03:17
I've been going crazy chasing down a memory leak for the past few days, and I think it's the same issue here.

I'm using a Tesla K80 with Ubuntu 16.04, cuDNN 6, and PyTorch installed from source at 60e7966.

With 375.66 drivers, CPU memory usage steadily increases during training; however after installing 384.66 the problem went away. On a similarly configured machine with a Tesla P100 GPU, I saw no memory leak with 375.66.

**Comment by soumith** [comment] 2017-08-15 05:54
@jcjohnson I've had CPU memory leaks associated with NVIDIA drivers + GPUs for years. I've never been able to pinpoint the problem precisely, and it only happens in some unfortunate configurations of things. However, I've stopped seeing them after the release CUDA 7.0 (and I was so glad!).
If you can repro this in a docker container, with a particular GPU + driver version, the NVIDIA team might have some actionable items.

**Comment by jcjohnson** [comment] 2017-08-15 16:44
@soumith I'm (embarrassingly) not very adept with docker (especially managing different drivers) but here are a few minimal shell scripts to reproduce the problem:

https://gist.github.com/jcjohnson/4976067b503d8d1ebafb5eb6f38f9aae

I can reproduce on Google Compute Engine, starting from the public Ubuntu 16.04 image (ubuntu-1604-xenial-v20170811) and creating a machine with 4 vCPU, 16GB of RAM, 64 GB of standard persistent disk, and a single Tesla K80 GPU.

After creating the instance, run either install_driver_375.sh or install_driver_384.sh to install one of the drivers; this will also reboot the machine.

After the machine comes back up, the script run.sh will install PyTorch 0.2 (which ships with its own CUDA and cuDNN) using pip and run the script leak.py which reproduces the problem.

Using 375.66 drivers, CPU memory usage climbs from 1275 MB to 1574 MB over 10k forward / backward iterations, but with 384.66 drivers CPU memory usage stays at 1285 MB.

**Comment by soumith** [comment] 2017-09-13 13:04
Spoke to @ngimel about this, and if the issue is fixed in 384.xx, a patch is likely not going to be backported to 375.xx. Closing this because there's not much we can do.

**Closed by soumith** 2017-09-13 13:04 UTC
Labels: dependency bug, high priority

**Comment by arogozhnikov** [comment] 2017-10-12 13:29
>  if the issue is fixed in 384.xx,

I have 384.66, ubuntu 14, python 3.5 and it still leaks inside a docker (it seems that pytorch doesn't free memory when kernel is restarted).

- restarting kernel doesn't help
- restarting jupyter doesn't help
- restartng docker container does help 

I'm using latest pytorch/pytorch image + some minimal additional stuff over it.
