### ISSUE TITLE
Unable to download libtorch (1.8.1) from pytorch.org

### ISSUE THREAD

**Issue by goswamig** [pytorch/pytorch#55345] opened 2021-04-06 00:22 UTC
Following links returns `403`

Download here (Pre-cxx11 ABI):
https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.1.zip

Download here (cxx11 ABI):
https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.1.zip

**Comment by goswamig** [comment] 2021-04-06 00:52
@soumith

**Comment by izdeby** [comment] 2021-04-07 15:08
Closing as a fix is provided. Please reopen in case if the issue is still present

**Closed** 2021-04-07 15:07 UTC

**Comment by goswamig** [comment] 2021-04-07 21:26
The issue is still there, I still can't download those binaries.

**Comment by imaginary-person** [comment] 2021-04-07 23:48
@goswamig

https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.1%2Bcu102.zip

https://download.pytorch.org/libtorch/cu102/libtorch-cxx11-abi-shared-with-deps-1.8.1%2Bcu102.zip
