### ISSUE TITLE
Exporting the operator 'aten::fft_fft2' to ONNX opset version 18 is not supported.

### ISSUE THREAD

**Issue by Radyngzh** [pytorch/pytorch#98833] opened 2023-04-11 09:14 UTC
## Issue description
Exporting the operator 'aten::fft_fft2' to ONNX opset version 18 is not supported.
Trying to convert torch model to onnx model.
How can I solve this problem? 

- PyTorch version: 2.0.0
- onnx version: 1.13.1
- Python version: 3.8.10
- CUDA/cuDNN version: 11.2
- GPU models and configuration: RTX 3090 24G

**Comment by shushanxingzhe** [comment] 2023-04-21 14:01
Encounter a similar problem, Waiting for reply...
Exporting the operator 'aten::fft_rfft' to ONNX opset version 14 is not supported

**Comment by Pondiniii** [comment] 2023-08-18 08:17
Can confirm that PyTorch 2.0.1 and PyTorch nightly are still not supported. I used opset version 18.

**Comment by justinchuby** [comment] 2023-08-24 03:24
Opset 18 and fft will be supported by the dynamo exporter. Closed as a duplicate of #107588

**Closed by justinchuby** 2023-08-24 03:24 UTC
Labels: module: onnx, triaged

**Comment by EmreOzkose** [comment] 2023-10-12 11:50
My torch version is 2.0.1+cu117 and still cannot export.

**Comment by justinchuby** [comment] 2023-10-12 14:01
The dynamo exporter is torch.onnx.dynamo_export. FFT support should be added when https://github.com/microsoft/onnxscript/pull/926 is merged

**Comment by EvelynCarter** [comment] 2025-03-16 16:36
解决了吗  怎么解决的

**Comment by 1334926196** [comment] 2025-04-15 07:50
> ## 问题描述
> 不支持将运算符 'aten：：fft_fft2' 导出到 ONNX opset 版本 18。尝试将 torch 模型转换为 onnx 模型。我该如何解决这个问题？
> 
> * PyTorch 版本：2.0.0
> * ONNX 版本：1.13.1
> * Python 版本：3.8.10
> * CUDA/cuDNN 版本：11.2
> * GPU 型号及配置：RTX 3090 24G

May I ask about 'aten': Does fft_fft2 'not export to onnx format solve the problem
