### ISSUE TITLE
AccessDeniedAccess when download libtorch 1.8.1 for Linux for CUDA 10.2 from download.pytorch.org

### ISSUE THREAD

**Issue by lamhoangtung** [pytorch/pytorch#55029] opened 2021-03-31 06:24 UTC
## 🐛 Bug

Hi, I'm trying to download libtorch 1.8.1 for Linux for CUDA 10.2 from pytorch.org but it's seems like I cannot download it and always receive AccessDeniedAccess error

## To Reproduce

1. Go to https://pytorch.org
2. Select Install, and select this configuration:
![image](https://user-images.githubusercontent.com/26834698/113099316-f4975080-9223-11eb-90f7-a468645c2539.png)
The website gave me this link: https://download.pytorch.org/libtorch/cu102/libtorch-shared-with-deps-1.8.1.zip, click on it
3. Then you will get the error
```
AccessDeniedAccess DeniedDWJ16RYPQ18JZTGJUah43OBP0gOdaCNFczNYJykEl9l3P+pIPM1b9D2pt6YIN1RLiCCB3Y6nc8fligqnMwfv7nMhIec=
```

## Expected behavior

The link to download libtorch 1.8.1 for Linux for CUDA 10.2 is available and can be use

## Environment

MacOS BigSur 11.1 + Safari

## Additional context

I had tried to switch to a different network (different ISP), change browser, use VPN but the problem still persist.

**Comment by imaginary-person** [comment] 2021-03-31 06:40
Duplicate of #54855

**Comment by imaginary-person** [comment] 2021-03-31 06:55
Duplicate of #54855

**Closed** 2021-03-31 18:07 UTC

**Comment by lamhoangtung** [comment] 2021-03-31 23:39
I hope that this issue was close because it was duplicated. For now, the problem haven't been resolve yet.
