### ISSUE TITLE
LKJCholesky Error on GPU

### ISSUE THREAD

**Issue by hejj16** [pytorch/pytorch#58774] opened 2021-05-21 20:41 UTC
## 🐛 Bug

Getting 
```RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!```
When using ```torch.distributions.LKJCholesky.log_prob``` on CUDA

## To Reproduce

Just run```torch.distributions.LKJCholesky(dim=2, concentration=1).log_prob(torch.eye(2).to("cuda"))```, and the error can be reproduced

## Environment

PyTorch version: 1.8.1+cu101
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.12.0
Libc version: glibc-2.26

Python version: 3.7 (64-bit runtime)
Python platform: Linux-5.4.109+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.4
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.4
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.8.1+cu101
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.9.1
[pip3] torchvision==0.9.1+cu101
[conda] Could not collect

## Additional context

This error can be easily fixed by changing the ```order = torch.arange(2, self.dim + 1)``` to ```order = torch.arange(2, self.dim + 1).to(device)``` in the LKJCholesky class

cc @fritzo @neerajprad @alicanb @vishwakftw @nikitaved

**Comment by H-Huang** [comment] 2021-05-21 23:54
Thanks for catching this @hejj16. I can also repro this on latest, we would accept a PR for this fix.

**Comment by fritzo** [comment] 2021-05-23 15:20
I believe this is expected behavior when the default device is not cuda. The same issue happens with all ops, e.g.
```py
torch.tensor(0.0) + torch.eye(2).to("cuda")  # errors
torch.tensor(0.0, device="cuda") + torch.eye(2).to("cuda")  # succeeds
```
To similarly inform `LKJCholesky` of your desired dtype, you'll need to pass a well-placed tensor as the `concentration` parameter:
```py
torch.distributions.LKJCholesky(
    dim=2, concentration=torch.tensor(1., device="cuda")
).log_prob(torch.eye(2).to("cuda"))
```
@hejj16 Feel free to reopen if I've misunderstood your issue.

**Comment by roussel-ryan** [comment] 2022-04-14 22:20
@fritzo @hejj16 This code snippet 
```
torch.distributions.LKJCholesky(
    dim=2, concentration=torch.tensor(1., device="cuda")
).log_prob(torch.eye(2).to("cuda"))
```
does not work (on pytorch, 1.11.0, encountering the same issue). The following code
```
torch.distributions.LKJCholesky(
    dim=torch.tensor(2, device="cuda"), concentration=torch.tensor(1., device="cuda")
).log_prob(torch.eye(2).to("cuda"))
```
also does not work. The solution to the problem is given by @hejj16 above. If this issue could be reopened and fixed that would be great

**Comment by neerajprad** [comment] 2022-04-15 00:04
@roussel-ryan, @hejj16: Thanks for highlighting this. If you or @hejj16 would like to contribute a fix, I will approve it. Otherwise, I'll push a fix for this over the weekend.

**Comment by roussel-ryan** [comment] 2022-04-18 15:14
Looks like this is fixed in the nightly version so you can close the issue.

**Comment by neerajprad** [comment] 2022-04-19 14:47
Closing this as this should have been fixed by @dme's PR - https://github.com/pytorch/pytorch/pull/73980 which should be available on nightly. Please reopen if you continue to see any issues.

**Closed by neerajprad** 2022-04-19 14:47 UTC
Labels: module: distributions, triaged
