### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by WestbrookZero** [pytorch/pytorch#42441] opened 2020-08-03 09:20 UTC
My environment is Win10 , Pytorch:1.15.1、Torchvision:0.6.1、numpy：1.19.1 , when i change Torchvision to 0.2.2. Post 3 , hiddenimports=['numpy.core.dtype_ctypes'] and change numpy to 1.18.5 or 1.16.4 or 1.15.0 still have this error :

```
Traceback (most recent call last):
File "detect.py", line 3, in
File "d:\installpath\develop\anaconda3-5.1.0\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\torch_init.py", line 136, in
ImportError: numpy.core.multiarray failed to import
[8580] Failed to execute script detect
```

cc @mruberry @rgommers @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by agolynski** [comment] 2020-08-03 17:16
Could you give an example repro?

**Comment by mszhanyi** [comment] 2020-08-06 04:09
@WestbrookZero, could you please ensure your change in spec not reset. (https://stackoverflow.com/questions/49083667/updating-spec-file-for-pyinstaller-gets-reset)

Strictly, It's a pyInstaller issue rather than pytorch issue.

**Comment by zhousteven** [comment] 2020-10-22 08:31
My environment is Win10 , Pytorch:1.6.0+cpu、Torchvision:0.7.0+cpu、numpy：1.19.2,use pyinstaller:4.0 to make an .exe file, have try to change numpy to 1.18.5 or 1.17.5 or 1.15.0 still have this error :
Traceback (most recent call last):
  File "vgg.py", line 9, in <module>
  File "d:\programdata\anaconda3\envs\vgg\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\torch\__init__.py", line 189, in <module>
ImportError: numpy.core.multiarray failed to import
[20924] Failed to execute script vgg

**Comment by peterjc123** [comment] 2020-10-22 10:03
@zhousteven @WestbrookZero What if you do just `import numpy`?

**Comment by mszhanyi** [comment] 2020-10-22 10:42
@zhousteven , could you try the below in your app.sepc
![image](https://user-images.githubusercontent.com/16190118/96861146-475f2600-1496-11eb-961d-66846ea3ca0c.png)

**Comment by zhousteven** [comment] 2020-10-23 02:10
@mszhanyi i have try this way, still occuring  the same error

**Comment by mszhanyi** [comment] 2020-10-23 02:14
> @mszhanyi i have try this way, still occuring the same error

Could you please tailor you project and provide a small demo for us?

**Comment by zhousteven** [comment] 2020-10-23 03:58
@peterjc123 Have tried your idea, when i only import the relate packages, there isn't an error occring, when i use .exe file; the code coped below:
#!/usr/bin/python
# -*- encoding:utf-8 -*-
import numpy
import torch
import torch.nn as nn
from torchvision import transforms
from torch.autograd import Variable
from torchvision import models

from PIL import Image
import logging.config
import yaml
import json

but when i use pyinstaller compile contain invoking load model which trained by pytorch,occuring the error.
should i paste my whole repository code?

**Comment by zhousteven** [comment] 2020-10-23 09:36
@mszhanyi @peterjc123@WestbrookZero first, best appreciate yours kindly help and useful idea. after trail and error find that below method solved my error:
before input package commandline, enter "chcp 65001", after that
enter "pyinstaller -F vgg.py"

**Comment by volkov-maxim** [comment] 2020-11-14 15:23
I'd same error and I [solved it with change version of numpy](https://stackoverflow.com/a/64730012/4439762).

Result of `import torch`

 $ python
 Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
 Type "help", "copyright", "credits" or "license" for more information.
 import torch
  ** On entry to DGEBAL parameter number  3 had an illegal value
  ** On entry to DGEHRD  parameter number  2 had an illegal value
  ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
  ** On entry to DHSEQR parameter number  4 had an illegal value
 Traceback (most recent call last):
   File "<stdin>", line 1, in <module>
   File "C:\Projects\Aspose\lib\site-packages\torch\__init__.py", line 190, in <module>
     from torch._C import *
 ImportError: numpy.core.multiarray failed to import
 


Result of `import numpy`

import numpy
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Projects\Aspose\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Projects\Aspose\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Projects\\Aspose\\lib\\site-packages\\numpy\\__ini
t__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more in
formation: https://tinyurl.com/y3dm3h86


**Solution:**
`pip uninstall numpy`
`pip install numpy==1.19.3`

Hope this help.

**Comment by rgommers** [comment] 2020-11-17 21:57
The PyInstaller team is developing some hooks for NumPy to make sure all dll's are packaged, see https://github.com/numpy/numpy/issues/17184. Without it I think using PyInstaller won't work right now.

The `numpy.core.multiarray failed to import` error is the single most common issue for numpy, it just means the numpy install was incomplete (many root causes possible).

Also given that reinstalling numpy solves this, I don't think there's anything to do on the PyTorch side.

**Comment by mruberry** [comment] 2020-11-18 10:44
Closing this issue per @rgommers's comment.

**Closed by mruberry** 2020-11-18 10:44 UTC
Labels: module: numpy, module: windows, triaged, windows-triaged
