### ISSUE TITLE
when train with multi GPUS

### ISSUE THREAD

**Issue by cqray1990** [pytorch/pytorch#103954] opened 2023-06-21 07:45 UTC
### 🐛 Describe the bug

train command:
xport NGPUS=2
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 --master_port=9531 ./train.py

but when traininf fow a while ,raise errors: what did it  means?

ARNING:torch.distributed.elastic.multiprocessing.api:Sending process 25236 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -9) local_rank: 1 (pid: 25237) of binary: /anaconda3/envs/paddle_env/bin/python
Traceback (most recent call last):
  File "/anaconda3/envs/paddle_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/anaconda3/envs/paddle_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 195, in <module>
    main()
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in main
    launch(args)
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launch.py", line 176, in launch
    run(args)
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/anaconda3/envs/paddle_env/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
======================================================
./train.py FAILED
------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-21_15:26:09
  host      : xiexing-MS-7B17
  rank      : 1 (local_rank: 1)
  exitcode  : -9 (pid: 25237)
  error_file: <N/A>
  traceback : Signal 9 (SIGKILL) received by PID 25237
======================================================

### Versions

torch 1.13.1 cuda116

**Comment by janeyx99** [comment] 2023-06-21 15:57
Closing this as dupe of #103955 but that one has a better formatted issue description

**Closed by janeyx99** 2023-06-21 15:57 UTC
