### ISSUE TITLE
Torch.onnx.export is very slow for my neural network - 8 hours for a 39M file

### ISSUE THREAD

**Issue by sevagh** [pytorch/pytorch#63734] opened 2021-08-22 15:31 UTC
## 🐛 Bug

I tried to export a PyTorch model in the `.pth` format to `.onnx`, according to this tutorial (https://pytorch.org/tutorials/advanced/super_resolution_with_onnxruntime.html).

My model has ~6.7 million parameters and is 28MB on disk - that's not so big. torchinfo output:
```
===============================================================================================
Layer (type:depth-idx)                        Output Shape              Param #
===============================================================================================
OpenUnmix                                     --                        --
Total params: 6,669,912
Trainable params: 6,669,912
Non-trainable params: 0
Total mult-adds (G): 194.27
===============================================================================================
Input size (MB): 28.63
Forward/backward pass size (MB): 9359.33
Params size (MB): 26.68
Estimated Total Size (MB): 9414.64
```

However, it took 8 hours to export to a 39M ONNX file:
```
(umx-gpu-numba) sevagh:xumx-sliCQ $ ls -latrh xumx_slicq.onnx
-rw-r--r--. 1 sevagh sevagh 39M Jul 29 04:28 xumx_slicq.onnx
```

 Here's my original bug report: https://discuss.pytorch.org/t/torch-onnx-export-of-pytorch-model-is-slow-expected-completion-time/127979 

Strace shows that there is activity occuring throughout the full 8 hour operation:
```
pid 238336] munmap(0x7fb9bb300000, 262144) = 0
[pid 238336] munmap(0x7fb9bb7c0000, 262144) = 0
[pid 238336] munmap(0x7fb9bb800000, 262144) = 0
[pid 238336] munmap(0x7fb9bb700000, 262144) = 0
[pid 238336] munmap(0x7fb9bb380000, 262144) = 0
[pid 238336] munmap(0x7fb9bb180000, 262144) = 0
[pid 238336] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb9bb8c0000
[pid 238336] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb9bb880000
[pid 238336] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb9bb800000
[pid 238336] mmap(NULL, 262144, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb9bb7c0000
```

The verbose output of the export function showed the following:
```
%247701 : Long(device=cpu) = onnx::Constant[value={0}]()
  %247702 : Long(device=cpu) = onnx::Constant[value={1}]()
  %247703 : Long(1, device=cpu) = onnx::Range(%247701, %247700, %247702)
  %247704 : Long(4, strides=[1], device=cpu) = onnx::Shape(%247669)
  %247705 : Long(device=cpu) = onnx::Constant[value={3}]()
  %247706 : Long(device=cpu) = onnx::Gather[axis=0](%247704, %247705)
  %247707 : Long(device=cpu) = onnx::Cast[to=7](%247706)
  %247708 : Long(device=cpu) = onnx::Constant[value={0}]()
  %247709 : Long(device=cpu) = onnx::Constant[value={1}]()
  %247710 : Long(644, device=cpu) = onnx::Range(%247708, %247707, %247709)
  %247712 : Long(1, strides=[1], device=cpu) = onnx::Unsqueeze[axes=[0]](%247670)
  %247713 : Long(1, strides=[1], device=cpu) = onnx::Unsqueeze[axes=[0]](%247671)
  %247715 : Long(1, strides=[1], device=cpu) = onnx::Constant[value={1}]()
  %247716 : Long(184, device=cpu) = onnx::Slice(%247710, %247712, %247713, %263646, %247715)
  %247717 : Long(4, strides=[1], device=cpu) = onnx::Constant[value=-1  1  1  1 [ CPULongType{4} ]]()
  %247718 : Long(1, 1, 1, 1, strides=[1, 1, 1, 1], device=cpu) = onnx::Reshape(%247689, %247717)
  %247719 : Long(3, strides=[1], device=cpu) = onnx::Constant[value=-1  1  1 [ CPULongType{3} ]]()
  %247720 : Long(2, 1, 1, strides=[1, 1, 1], device=cpu) = onnx::Reshape(%247696, %247719)
  %247721 : Long(2, strides=[1], device=cpu) = onnx::Constant[value=-1  1 [ CPULongType{2} ]]()
  %247722 : Long(1, 1, strides=[1, 1], device=cpu) = onnx::Reshape(%247703, %247721)
  %247723 : Long(1, 2, 1, 1, strides=[2, 1, 1, 1], device=cpu) = onnx::Add(%247718, %247720)
  %247724 : Long(1, 2, 1, 1, strides=[2, 1, 1, 1], device=cpu) = onnx::Add(%247723, %247722)
```

## To Reproduce

1. Clone my neural network xumx-sliCQ repository: https://github.com/sevagh/xumx-sliCQ
2. Git-lfs fetch to get the pretrained model downloaded from GitHub LFS
3. Set up the conda environment: https://github.com/sevagh/xumx-sliCQ#training-and-inference 
4. Run the onnx export script on the pretrained `.pth` model to conver to a .onnx file: 
```
(xumx-slicq-gpu) sevagh:xumx-sliCQ $ ./scripts/onnx_export_demo.py ./pretrained-model/
Starting export to onnx...
```

## Expected behavior

I expect this to complete in under 8 hours. @ptrblck recommended that I open a GitHub issue if this is reproducible, and that 8 hours isn't normal.

## Environment

```
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Fedora 34 (Workstation Edition) (x86_64)
GCC version: (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)
Clang version: 12.0.1 (Fedora 12.0.1-1.fc34)
CMake version: version 3.20.5
Libc version: glibc-2.33

Python version: 3.9.6 | packaged by conda-forge | (default, Jul 11 2021, 03:39:48)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.13.10-200.fc34.x86_64-x86_64-with-glibc2.33
Is CUDA available: True
CUDA runtime version: 11.4.48
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 2070 SUPER
GPU 1: NVIDIA GeForce RTX 3080 Ti

Nvidia driver version: 470.63.01
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.8.2.2
/usr/lib64/libcudnn_adv_infer.so.8.2.2
/usr/lib64/libcudnn_adv_train.so.8.2.2
/usr/lib64/libcudnn_cnn_infer.so.8.2.2
/usr/lib64/libcudnn_cnn_train.so.8.2.2
/usr/lib64/libcudnn_ops_infer.so.8.2.2
/usr/lib64/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchinfo==1.5.3
[conda] blas                      2.108                       mkl    conda-forge
[conda] blas-devel                3.9.0                     8_mkl    conda-forge
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libblas                   3.9.0                     8_mkl    conda-forge
[conda] libcblas                  3.9.0                     8_mkl    conda-forge
[conda] liblapack                 3.9.0                     8_mkl    conda-forge
[conda] liblapacke                3.9.0                     8_mkl    conda-forge
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-devel                 2020.4             ha770c72_305    conda-forge
[conda] mkl-include               2020.4             h726a3e6_304    conda-forge
[conda] numpy                     1.21.2           py39hdbf815f_0    conda-forge
[conda] pytorch                   1.9.0           py3.9_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.9.0                      py39    pytorch
[conda] torchinfo                 1.5.3                    pypi_0    pypi
```

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment] 2021-08-24 00:05
When this pytorch model is converted to torchScript, it has more than 6300 inputs or initializers. Many are from 2652 `bucketed_unmixes_vocals`, 280 `aten::wait` and 560 `prim::fork_` in OpenUnmix. Is it possible to make it simpler?

**Comment by sevagh** [comment] 2021-08-24 01:43
If it's a result of poor design in my model, that's OK. I only opened the GitHub issue because I was suggested it on the PyTorch forum, that it might be a potential library issue.

**Comment by neginraoof** [comment] 2021-09-03 21:32
Thanks @sevagh I'm closing this issue then. Feel free to re-open if needed.

**Closed by neginraoof** 2021-09-03 21:32 UTC
Labels: module: onnx, triaged, onnx-needs-info

**Comment by tdewolff** [comment] 2022-08-04 13:19
@neginraoof I understand then that you think it is completely normal that it takes 8 hours to export to the ONNX format? I have a model of 31 million parameters, I shouldn't expect it to be ready this week then?

The problem obviously is with the implementation that is incredible slow, up to the point of being useless. Will there be any attempts made to improve the implementation? Should be really low hanging fruit I expect.

**Comment by ildoonet** [comment] 2022-09-12 12:20
In my case, I have more than 3B model and I have tried to export it in ONNX file. 

I has been one week, STILL runnning.

**Comment by ildoonet** [comment] 2022-09-13 02:10
@tdewolff which version do you use? I got below message

```
$ pip install -U onnx
Looking in indexes: https://pypi.org/simple, http://kakaobrain-pypi.dev.9rum.cc/, https://pypi.ngc.nvidia.com
Requirement already satisfied: onnx in /opt/conda/lib/python3.7/site-packages (1.12.0)
Requirement already satisfied: numpy>=1.16.6 in /opt/conda/lib/python3.7/site-packages (from onnx) (1.21.5)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /opt/conda/lib/python3.7/site-packages (from onnx) (4.1.1)
Requirement already satisfied: protobuf<=3.20.1,>=3.12.2 in /opt/conda/lib/python3.7/site-packages (from onnx) (3.19.4)
```

**Comment by ildoonet** [comment] 2022-09-15 07:28
@tdewolff in my case, it doesn't help.  T.T

**Comment by chez8990** [comment] 2022-11-01 17:13
> I meant the opset version, see https://pytorch.org/docs/stable/onnx.html#torch.onnx.export. It defaults to 13 but with 16 it was working fine for me.

can confirm that optset 16 is much faster than 13

**Comment by matt-deboer** [comment] 2022-12-01 21:56
For others stumbling on this, I tried exporting a few models from the `timm` collection ('resnest50d', 'resnet50d', 'deit3_large_patch16_224_in21ft1k', 'beit_larg_patch16_224' were the ones I tried); all of them ended up running much longer than I was willing to wait (> 30mins); I tried exporting in PyTorch 1.12 and 1.13, and both encountered this issue. Changing to opset 16 had no effect.

A downgrade to PyTorch 1.11 allowed the onnx export to complete normally in a second or two (was able to use opset 15 there).
I'll try posting a minimal repro case when I have time, since this issue is closed..

**Comment by fxmarty** [comment] 2023-02-14 13:53
I hit a similar issue exporting BigBird with block sparse attention.

**Comment by un-certainty** [comment] 2023-02-15 07:59
Same here. Very slow to export a decoder model with past key values. Opset 16 does no help.

What could be the root cause of this problem?

**Comment by tadejsv** [comment] 2023-02-23 09:05
Same here - a model with 700k parameters (`tinynet_e` from `timm`) did not finish converting to ONNX in 10 minutes in Pytorch 1.13. In Pytorch 1.11 it finised in a few seconds. IMO, this issue should be reopened @neginraoof

**Comment by take-cheeze** [comment] 2023-04-12 05:39
@tadejsv Thank you for your report
I had some torch.onnx.export too slow experiments in other env and trying this code which will test `tinynet_e`:
```python
    import timm
    m = timm.create_model("tinynet_e")
    print(torch.__version__)
    torch.onnx.export(m, (torch.rand(1, 3, 224, 224),), "test.onnx", opset_version=13)
```

But it won't take a few seconds to finish. Is there any other factor I'm missing?

**Comment by dbelenko** [comment] 2023-07-10 20:40
Exporting Transformers from Huggingface takes a very long time too. In fact I was not able to wait long enough for `LlamaForCausalLM` to finish exporting (GPU).

**Comment by dbelenko** [comment] 2023-07-10 20:53
In my case according to `perf top` there's no use of CPU by anything relevant, and according to `nvidia-smi` there's no use of GPU either. I wouldn't be surprised if this just deadlocks somewhere.

**Comment by dbelenko** [comment] 2023-07-10 21:30
Could be a clue: if I export the same script from Jupyter _as a script_ and run it standalone, it completes quickly and with no issues. This could be related to another bug I've seen - the one where ONNX export hangs when multiprocessing is in use. I don't know how Jupyter Lab manages its processes.

**Comment by philippkant** [comment] 2023-08-25 12:52
I tried changing the opset_version but it didn't work for me.
But changing verbose=True to verbose=False did it for me!

torch.onnx.export(model, x, "model.onnx", verbose=False)

**Comment by jcuenod** [comment] 2023-09-06 12:48
+1 `verbose=False` fixed it for me too

**Comment by Feynman1999** [comment] 2024-01-23 04:05
any solution?

**Comment by elsampsa** [comment] 2024-04-05 20:36
+1 ``verbose=False`` works for me from jupyter notebook and for huggingface

**Comment by MahmoudAshraf97** [comment] 2025-03-13 22:20
I had the same issue with torch 2.5.1, I can confirm that `verbose=False` fixes the issue

**Comment by kieferMaland** [comment] 2025-06-13 22:45
verbose=False was the solution for me as well.
