### ISSUE TITLE
Error after compiling with ROCM

### ISSUE THREAD

**Issue by jychoi-hpc** [pytorch/pytorch#119849] opened 2024-02-13 23:32 UTC
### 🐛 Describe the bug

I compiled torch from the source with ROCM. It went ok but I got the following error when running:
```
$ python -c "import torch"
terminate called after throwing an instance of 'c10::Error'
  what():  impl("_Bfloat16QuantizedToFloat", ...): Explicitly provided dispatch key (CUDA) is inconsistent with the dispatch key of the enclosing TORCH_LIBRARY_IMPL block (UnknownUnknown).  Please declare a separate TORCH_LIBRARY_IMPL block for this dispatch key and move your impl() there.  (Error occurred while processing TORCH_LIBRARY_IMPL block at /lustre/orion/cph161/world-shared/jyc/frontier/src/pytorch/torch/csrc/distributed/c10d/quantization/quantization_gpu.cu:152)
Exception raised from _impl at /lustre/orion/cph161/world-shared/jyc/frontier/src/pytorch/aten/src/ATen/core/library.cpp:224 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x8d (0x7f2bcf5b98fd in /lustre/orion/world-shared/cph161/jyc/frontier/sw/anaconda3/2022.10/envs/hydragnn2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd0 (0x7f2bcf567256 in /lustre/orion/world-shared/cph161/jyc/frontier/sw/anaconda3/2022.10/envs/hydragnn2/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #2: torch::Library::_impl(char const*, torch::CppFunction&&, torch::_RegisterOrVerify) & + 0xe36 (0x7f2bfd9d4856 in /lustre/orion/world-shared/cph161/jyc/frontier/sw/anaconda3/2022.10/envs/hydragnn2/lib/python3.8/site-packages/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x17a5926 (0x7f2bf32d3926 in /lustre/orion/world-shared/cph161/jyc/frontier/sw/anaconda3/2022.10/envs/hydragnn2/lib/python3.8/site-packages/torch/lib/libtorch_hip.so)
frame #4: torch::detail::TorchLibraryInit::TorchLibraryInit(torch::Library::Kind, void (*)(torch::Library&), char const*, std::optional<c10::DispatchKey>, char const*, unsigned int) + 0xe6 (0x7f2bf3294326 in /lustre/orion/world-shared/cph161/jyc/frontier/sw/anaconda3/2022.10/envs/hydragnn2/lib/python3.8/site-packages/torch/lib/libtorch_hip.so)
frame #5: <unknown function> + 0x504900 (0x7f2bf2032900 in /lustre/orion/world-shared/cph161/jyc/frontier/sw/anaconda3/2022.10/envs/hydragnn2/lib/python3.8/site-packages/torch/lib/libtorch_hip.so)
frame #6: <unknown function> + 0x1137a (0x7f2c2174a37a in /lib64/ld-linux-x86-64.so.2)
frame #7: <unknown function> + 0x11496 (0x7f2c2174a496 in /lib64/ld-linux-x86-64.so.2)
frame #8: _dl_catch_exception + 0x50 (0x7f2c204f10fe in /lib64/libc.so.6)
frame #9: <unknown function> + 0x157e6 (0x7f2c2174e7e6 in /lib64/ld-linux-x86-64.so.2)
frame #10: _dl_catch_exception + 0xbf (0x7f2c204f116d in /lib64/libc.so.6)
frame #11: <unknown function> + 0x1501b (0x7f2c2174e01b in /lib64/ld-linux-x86-64.so.2)
frame #12: <unknown function> + 0x13b6 (0x7f2c20ce03b6 in /lib64/libdl.so.2)
frame #13: _dl_catch_exception + 0xbf (0x7f2c204f116d in /lib64/libc.so.6)
frame #14: _dl_catch_error + 0x31 (0x7f2c204f11ff in /lib64/libc.so.6)
frame #15: <unknown function> + 0x1ba5 (0x7f2c20ce0ba5 in /lib64/libdl.so.2)
frame #16: dlopen + 0x73 (0x7f2c20ce0481 in /lib64/libdl.so.2)
<omitting python frames>
frame #19: python() [0x5a3250]
frame #20: python() [0x4e8cfb]
frame #35: python() [0x4e7aeb]
frame #42: python() [0x589f31]
frame #43: python() [0x4e8cfb]
frame #56: python() [0x4e7aeb]
frame #63: python() [0x5a5bd1]
```

I feel like something didn't pick correctly but I don't know what feature/library caused the error. I appreciate any advice. Thanks.

### Versions

I am using the master version:
```
$ git describe --tag
ciflow/periodic/f3e7d809936d9f1bf63102e8afe241e13ed8766a-84-g02b60e76c9
```
I got the same error with `v2.2.0` release version too.
I am using `rocm/5.7.1` and `gcc/12.2.0`

I used the following command to configure and build:
```
USE_KINETO=0 BUILD_TEST=0 python setup.py build --cmake-only
VERBOSE=1 MAX_JOBS=64 python setup.py build
```

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by jeffdaily** [comment] 2024-02-14 15:35
Did you run the 'hipify' script prior to running setup.py?  `python tools/amd_build/build_amd.py`?

**Comment by jychoi-hpc** [comment] 2024-02-14 15:54
Yes, I did.

**Comment by hongxiayang** [comment] 2024-02-14 16:48
Have you tried using `python setup.py install`, or `python setup.py develop` ?
See below:
https://github.com/pytorch/pytorch#from-source

**Comment by hongxiayang** [comment] 2024-03-18 19:31
can you run rocminfo and tell us the output?

Also where you run command relative to your pytorch directory? 

Also, can you compare with pytorch official wheel installation method and do an import torch?

**Comment by giltirn** [comment] 2024-03-21 18:21
I am hitting this same issue on the OLCF Frontier computer using the latest nightly 16935de9611b04ae0c01b45991d6959b1296aa5f as well as several older revisions from different forks (notably the ROCM fork). The error appears on importing torch:

```
terminate called after throwing an instance of 'c10::Error'
  what():  impl("_Bfloat16QuantizedToFloat", ...): Explicitly provided dispatch key (CUDA) is inconsistent with the dispatch key of the enclosing TORCH_LIBRARY_IMPL block (UnknownUnknown).  Please declare a separate TORCH_LIBRARY_IMPL block for this dispatch key and move your impl() there.  (Error occurred while processing TORCH_LIBRARY_IMPL block at /lustre/orion/ast153/proj-shared/ckelly/PyTorch_ROCM/pytorch_true_main_rocm6/torch/csrc/distributed/c10d/quantization/quantization_gpu.cu:152)
Exception raised from _impl at ../aten/src/ATen/core/library.cpp:224 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x99 (0x7eff11ac3ca9 in /lustre/orion/ast153/proj-shared/ckelly/PyTorch_ROCM/pytorch_true_main_rocm6/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xd0 (0x7eff11a73058 in /lustre/orion/ast153/proj-shared/ckelly/PyTorch_ROCM/pytorch_true_main_rocm6/torch/lib/libc10.so)
frame #2: torch::Library::_impl(char const*, torch::CppFunction&&, torch::_RegisterOrVerify) & + 0xe1c (0x7eff00a0ef1c in /lustre/orion/ast153/proj-shared/ckelly/PyTorch_ROCM/pytorch_true_main_rocm6/torch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1b7b656 (0x7efef543d656 in /lustre/orion/ast153/proj-shared/ckelly/PyTorch_ROCM/pytorch_true_main_rocm6/torch/lib/libtorch_hip.so)
frame #4: torch::detail::TorchLibraryInit::TorchLibraryInit(torch::Library::Kind, void (*)(torch::Library&), char const*, std::optional<c10::DispatchKey>, char const*, unsigned int) + 0xe6 (0x7efef53f53a6 in /lustre/orion/ast153/proj-shared/ckelly/PyTorch_ROCM/pytorch_true_main_rocm6/torch/lib/libtorch_hip.so)
frame #5: <unknown function> + 0x5c1050 (0x7efef3e83050 in /lustre/orion/ast153/proj-shared/ckelly/PyTorch_ROCM/pytorch_true_main_rocm6/torch/lib/libtorch_hip.so)
frame #6: <unknown function> + 0x115ea (0x7eff15bb05ea in /lib64/ld-linux-x86-64.so.2)
frame #7: <unknown function> + 0x11706 (0x7eff15bb0706 in /lib64/ld-linux-x86-64.so.2)
frame #8: _dl_catch_exception + 0x50 (0x7eff1595cfbe in /lib64/libc.so.6)
frame #9: <unknown function> + 0x15a76 (0x7eff15bb4a76 in /lib64/ld-linux-x86-64.so.2)
frame #10: _dl_catch_exception + 0xbf (0x7eff1595d02d in /lib64/libc.so.6)
frame #11: <unknown function> + 0x1528b (0x7eff15bb428b in /lib64/ld-linux-x86-64.so.2)
frame #12: <unknown function> + 0x13b6 (0x7eff15b503b6 in /lib64/libdl.so.2)
frame #13: _dl_catch_exception + 0xbf (0x7eff1595d02d in /lib64/libc.so.6)
frame #14: _dl_catch_error + 0x31 (0x7eff1595d0bf in /lib64/libc.so.6)
frame #15: <unknown function> + 0x1ba5 (0x7eff15b50ba5 in /lib64/libdl.so.2)
frame #16: dlopen + 0x73 (0x7eff15b50481 in /lib64/libdl.so.2)
frame #17: python() [0x5f6bc6]
frame #18: python() [0x5f5934]
frame #19: python() [0x52bc6b]
<omitting python frames>
frame #22: python() [0x524a53]
frame #26: python() [0x5c82ce]
frame #28: python() [0x5e1623]
frame #29: python() [0x51c107]
frame #32: python() [0x524a53]
frame #36: python() [0x5c82ce]
frame #38: python() [0x5e8807]
frame #39: python() [0x5e4e40]
frame #40: python() [0x5f9132]
frame #45: __libc_start_main + 0xef (0x7eff1583b24d in /lib64/libc.so.6)
frame #46: python() [0x5b6c6f]

Aborted

``` 
 and I have reproduced it for both rocm/5.7.0 and rocm/6.0.0 (gcc 12.2.0, python 3.11.5 in conda environment). Build process is standard: clone repo, run the hipify script and compile with
 
```
export CPATH=/opt/rocm-6.0.0/roctracer/include/:${CPATH}
export LD_LIBRARY_PATH=/opt/rocm-6.0.0/roctracer/lib:${LD_LIBRARY_PATH}
USE_KINETO=0 BUILD_TEST=0 CXXFLAGS='-Wno-maybe-uninitialized -Wno-uninitialized -Wno-free-nonheap-object -Wno-nonnull' CFLAGS='-Wno-maybe-uninitialized -Wno-uninitialized -Wno-free-nonheap-object -Wno-nonnull' python setup.py develop
``` 
I spent hours hacking around with the source to try to isolate the problem but to no avail. The file 
> torch/csrc/distributed/c10d/quantization/quantization_gpu.cu

is properly hipified and the code appears to be defining the implementation with the correct dispatch flag:
```
TORCH_LIBRARY_IMPL(quantization, CUDA, m) {
    DISPATCH_TO_CUDA("_Bfloat16QuantizedToFloat", _bfloat16_to_float_cuda);
    DISPATCH_TO_CUDA("_FloatToBfloat16Quantized", _float_to_bfloat16_cuda);
}
``` 
thus it is a mystery to me why this error is occuring.

**Comment by jychoi-hpc** [comment] 2024-03-24 14:19
I just tried again to build pytorch `v2.2.1`  release with rocm `5.7.1`, python `3.8.19` but got the same error.

The wheel install works:
```
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/rocm5.7
```

I feel like there is any specific flags/options we should. I will appreciate any advice.

Here is my rocminfo output:
<details>
<summary>rocminfo output</summary>
 ```
$ rocminfo
ROCk module is loaded
=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (0xFFFFFFFFFFFFFFFF) (timestamp count)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             
Mwaitx:                  DISABLED
DMAbuf Support:          YES

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD EPYC 7763 64-Core Processor    
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD EPYC 7763 64-Core Processor    
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        0                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    130717652(0x7ca97d4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    130717652(0x7ca97d4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    130717652(0x7ca97d4) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 2                  
*******                  
  Name:                    AMD EPYC 7763 64-Core Processor    
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD EPYC 7763 64-Core Processor    
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        1                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    132112468(0x7dfe054) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    132112468(0x7dfe054) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    132112468(0x7dfe054) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 3                  
*******                  
  Name:                    AMD EPYC 7763 64-Core Processor    
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD EPYC 7763 64-Core Processor    
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        2                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    132112468(0x7dfe054) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    132112468(0x7dfe054) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    132112468(0x7dfe054) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 4                  
*******                  
  Name:                    AMD EPYC 7763 64-Core Processor    
  Uuid:                    CPU-XX                             
  Marketing Name:          AMD EPYC 7763 64-Core Processor    
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0(0x0)                             
  Queue Min Size:          0(0x0)                             
  Queue Max Size:          0(0x0)                             
  Queue Type:              MULTI                              
  Node:                    3                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768(0x8000) KB                   
  Chip ID:                 0(0x0)                             
  ASIC Revision:           0(0x0)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   0                                  
  BDFID:                   0                                  
  Internal Node ID:        3                                  
  Compute Unit:            32                                 
  SIMDs per CU:            0                                  
  Shader Engines:          0                                  
  Shader Arrs. per Eng.:   0                                  
  WatchPts on Addr. Ranges:1                                  
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: FINE GRAINED        
      Size:                    132094680(0x7df9ad8) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    132094680(0x7df9ad8) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
    Pool 3                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    132094680(0x7df9ad8) KB            
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       TRUE                               
  ISA Info:                
*******                  
Agent 5                  
*******                  
  Name:                    gfx90a                             
  Uuid:                    GPU-a87cac04234ff835               
  Marketing Name:          AMD Instinct MI210                 
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128(0x80)                          
  Queue Min Size:          64(0x40)                           
  Queue Max Size:          131072(0x20000)                    
  Queue Type:              MULTI                              
  Node:                    4                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16(0x10) KB                        
    L2:                      8192(0x2000) KB                    
  Chip ID:                 29711(0x740f)                      
  ASIC Revision:           1(0x1)                             
  Cacheline Size:          64(0x40)                           
  Max Clock Freq. (MHz):   1700                               
  BDFID:                   51456                              
  Internal Node ID:        4                                  
  Compute Unit:            104                                
  SIMDs per CU:            4                                  
  Shader Engines:          8                                  
  Shader Arrs. per Eng.:   1                                  
  WatchPts on Addr. Ranges:4                                  
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      TRUE                               
  Wavefront Size:          64(0x40)                           
  Workgroup Max Size:      1024(0x400)                        
  Workgroup Max Size per Dimension:
    x                        1024(0x400)                        
    y                        1024(0x400)                        
    z                        1024(0x400)                        
  Max Waves Per CU:        32(0x20)                           
  Max Work-item Per CU:    2048(0x800)                        
  Grid Max Size:           4294967295(0xffffffff)             
  Grid Max Size per Dimension:
    x                        4294967295(0xffffffff)             
    y                        4294967295(0xffffffff)             
    z                        4294967295(0xffffffff)             
  Max fbarriers/Workgrp:   32                                 
  Packet Processor uCode:: 78                                 
  SDMA engine uCode::      8                                  
  IOMMU Support::          None                               
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 2                   
      Segment:                 GLOBAL; FLAGS:                     
      Size:                    67092480(0x3ffc000) KB             
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Accessible by all:       FALSE                              
    Pool 3                   
      Segment:                 GROUP                              
      Size:                    64(0x40) KB                        
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Accessible by all:       FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx90a:sramecc+:xnack-
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Size:      1024(0x400)                        
      Workgroup Max Size per Dimension:
        x                        1024(0x400)                        
        y                        1024(0x400)                        
        z                        1024(0x400)                        
      Grid Max Size:           4294967295(0xffffffff)             
      Grid Max Size per Dimension:
        x                        4294967295(0xffffffff)             
        y                        4294967295(0xffffffff)             
        z                        4294967295(0xffffffff)             
      FBarrier Max Size:       32                                 
*** Done ***             
```
</details>

**Comment by michael-sandoval** [comment] 2024-05-08 17:47
I just sifted through all of the commits that were known to work on Frontier until the error popped up and seemed to have found the issue. Looks like it was this PR: https://github.com/pytorch/pytorch/pull/101995 (commit: 165f4f6ccf7522d75df99c30821d583dfc58ad62 ). The commit directly before it builds fine from source with ROCm 5.6.0 / Python 3.10.13 .

**Comment by giltirn** [comment] 2024-05-08 18:25
Impressive! The interesting question is why the AMD nightlies are still able to build.

**Comment by michael-sandoval** [comment] 2024-05-10 19:43
I believe it's a Frontier-ism most likely something to do with `/opt/cray/pe/gcc/12.2.0/snos/include/g++/optional`. That commit I referenced shifted things to using the compiler's internal `optional` method. Before that change, everything really depended on Torch's `c10/util/Optional.h` header. So, looks like something was defined differently between Torch's previous `Optional.h` header (which worked) and the compiler's internal `optional` (which causes the import error). Having a hard time pinning down exactly which definition is the source, but have isolated to that at least.

**Comment by michael-sandoval** [comment] 2024-07-22 03:44
For any Frontier users that stumble on this. I made a fork/branch that reverts the commit mentioned above that fixes the issue. I'd still say the build is highly experimental though, as the build process is a bit involved still, and only works for specific ROCm versions. Recipe:

```bash
# Load modules
module load PrgEnv-gnu/8.3.3
module load gcc/12.2.0
module load rocm/5.6.0
module load craype-accel-amd-gfx90a
module load cmake
module load miniforge3/23.11.0-0
 
# Because using non-default cray-mpich
export LD_LIBRARY_PATH=${CRAY_LD_LIBRARY_PATH}:${LD_LIBRARY_PATH}
 
# Setup misc env vars
export HCC_AMDGPU_TARGET=gfx90a
export PYTORCH_ROCM_ARCH=gfx90a
export ROCM_HOME=/opt/rocm-5.6.0
export CC=cc
export CXX=CC
 
# Create conda env and install some dependencies
conda create -n pyt_env python=3.10 numpy=1 -c conda-forge
source activate pyt_env
pip install pyyaml typing_extensions ninja packaging
 
# Setup and clone repository
mkdir torch_tests && cd torch_tests/
git clone --recursive -b release/2.3-frontier-rocm https://github.com/michael-sandoval/pytorch
cd pytorch/
git submodule init
git submodule update
 
# If using GCC12 to build torch (ROCm >= 5.4.3):
export CFLAGS+=" -Wno-error=maybe-uninitialized -Wno-error=uninitialized -Wno-error=restrict -Wno-error=nonnull"
export CXXFLAGS+=" -Wno-error=maybe-uninitialized -Wno-error=uninitialized -Wno-error=restrict -Wno-error=nonnull"
export BUILD_TEST=OFF
 
# Generate HIP files
python3 tools/amd_build/build_amd.py
 
# Get the PyTorch build version
export PYTORCH_BUILD_VERSION='2.3.0'
export PYTORCH_BUILD_NUMBER=1
 
### Copy over misc Frontier fixes ###
 
# Point libkineto away from "/opt/rocm" to "/opt/rocm-x.y.z"
cp frontier_fixes/third_party/kineto/libkineto/CMakeLists.txt ./third_party/kineto/libkineto/CMakeLists.txt

# Fix "<rocm-core/rocm_version.h>" reference post HIP conversion (ONLY FOR ROCm < 6.0.0)
cp frontier_fixes/aten/src/ATen/hip/tunable/TunableGemm.h ./aten/src/ATen/hip/tunable/TunableGemm.h
 
# Build PyTorch
USE_ROCM=1 USE_CUDA=OFF USE_NVCC=OFF BUILD_CAFFE2_OPS=0 ROCM_SOURCE_DIR="/opt/rocm-5.6.0" MAX_JOBS=8 python setup.py bdist_wheel
 
# fails around build step 7013 (can't copy over this file ahead of time like the others)
# the error will be about std::optional not being declared in ViewFuncs.h and ViewFuncs.cpp
cp frontier_fixes/torch/csrc/autograd/generated/ViewFuncs.* ./torch/csrc/autograd/generated/
 
# Build PyTorch (resume build)
USE_ROCM=1 USE_CUDA=OFF USE_NVCC=OFF BUILD_CAFFE2_OPS=0 ROCM_SOURCE_DIR="/opt/rocm-5.6.0" MAX_JOBS=8 python setup.py bdist_wheel
 
# Install wheel
pip install dist/*.whl
 
# Double check installation
cd && python3 -c "import torch; print(torch.__version__)
```

Works with ROCm 5.6.0 and 6.0.0 (build completes for 5.7.x but fails on import due to other issues -- might be work aroundable though). Probably works for earlier ROCm versions as well, but has not been tested.

**Comment by naromero77amd** [comment] 2024-09-20 18:29
@michael-sandoval @jychoi-hpc @giltirn Can we close this one? Seems like the problem was specific to OLCF's Frontier.

**Comment by michael-sandoval** [comment] 2024-09-20 20:25
@naromero77amd Yeah I believe so -- I wish I was able to provide more info on _exactly_ what it was about Frontier's previous GNU implementation of `Optional` that caused this, but unfortunately don't have additional insight on that front.

Regardless, yup I believe this can be closed.

**Closed** 2024-09-20 21:20 UTC
Labels: module: rocm, triaged
