### ISSUE TITLE
Nightly libtorch doesn't contain recent refactoring of Generator code

### ISSUE THREAD

**Issue by meganset** [pytorch/pytorch#22368] opened 2019-06-29 10:22 UTC
## 🐛 Bug

I don't see the new work on Generators in the libtorch.zip file in the last couple of nightly builds.

e.g. a file like _ATen/CPUGenerator.h_
looks out of date in the libtorch.zip vs pytorch-master.zip
?

I had thought these two zips would generally have the same files or nearly the same..

Thanks

**Comment by meganset** [comment] 2019-06-29 10:50
Also the new work on optional data type for prod, cumprod,.. #21088

Does the nightly libtorch.zip hold off including commits that break the c++ code..
?

**Comment by soumith** [comment] 2019-06-30 03:37
@meganset the nightly runs some smoke tests before it uploads the binaries going live. It might have gotten broken, we'll have to look into it.

**Comment by rgommers** [comment] 2019-07-23 00:17
These differences seem to have disappeared. To verify:

download https://download.pytorch.org/libtorch/nightly/cu90/libtorch-shared-with-deps-latest.zip, and unpack in `~/Downloads/tmp`, then
```
$diff aten/src/ATen/CPUGenerator.h ~/Downloads/tmp/libtorch/include/ATen/CPUGenerator.h 
```
shows no changes. I also verified that the changes to `Tensor.h` from #21088 are in the latest nightly.

Does this need a complete script to grab the nightly and diff a whole bunch of files? Given that files are bound to be a little out of sync compared to master, it's probably a bit of work to do compare the latest nightly contents against the state of master robustly.

**Comment by meganset** [comment] 2019-07-23 20:57
I still see the older code in the nightly libtorch zip
e.g.
```
wget https://download.pytorch.org/libtorch/nightly/cu100/libtorch-shared-with-deps-latest.zip
wget https://github.com/pytorch/pytorch/archive/master.zip
```
unzip each, then comparing headers, e.g.

```
diff -y libtorch/include/ATen/CPUGenerator.h pytorch-master/aten/src/ATen/CPUGenerator.h
#pragma once							#pragma once

// @generated by aten/src/ATen/gen.py			      <
							      <
#include <TH/TH.h>					      <
							      <
#include <ATen/core/Generator.h>				#include <ATen/core/Generator.h>
							      >	#include <ATen/core/MT19937RNGEngine.h>
							      >	#include <ATen/core/PhiloxRNGEngine.h>
							      >	#include <c10/util/Optional.h>

namespace at {							namespace at {

class Context;						      |	struct CAFFE2_API CPUGenerator : public Generator {
struct CPUGenerator : public Generator {		      |	  // Constructors
  CAFFE2_API CPUGenerator(Context * context);		      |	  CPUGenerator(uint64_t seed_in = default_rng_seed_val);
  CAFFE2_API virtual ~CPUGenerator();			      |	  ~CPUGenerator() = default;
							      |
  CAFFE2_API virtual CPUGenerator& copy(const Generator& from |	  // CPUGenerator methods
  CAFFE2_API virtual CPUGenerator& free() override;	      |	  std::shared_ptr<CPUGenerator> clone() const;
							      |	  void set_current_seed(uint64_t seed) override;
  CAFFE2_API virtual uint64_t seed() override;		      |	  uint64_t current_seed() const override;
  CAFFE2_API virtual uint64_t initialSeed() override;	      |	  uint64_t seed() override;

```

**Comment by rgommers** [comment] 2019-07-25 02:47
Ah that helps, it's only the CUDA 10.0 build that's outdated. downloading both and checking dates:
```
$ ls -l
-rw-r--r-- 1 rgommers users 728760996 Jun  6 03:11 libtorch-shared-with-deps-latest-cu100.zip
-rw-r--r-- 1 rgommers users 609034323 Jul 22 06:17 libtorch-shared-with-deps-latest-cu90.zip
```
So it hasn't updated since June 6th.

**Comment by rgommers** [comment] 2019-07-25 02:51
gh-23039 is related.

**Comment by rgommers** [comment] 2019-07-25 02:59
Okay, this is an exact duplicate of gh-23039 and that has an explanation of what's going on. So closing this issue. Thanks @meganset

**Closed by rgommers** 2019-07-25 02:59 UTC
Labels: high priority, module: binaries, triaged
