### ISSUE TITLE
Unable to build from source

### ISSUE THREAD

**Issue by pj-parag** [pytorch/pytorch#5038] opened 2018-02-04 17:11 UTC
I am not able to build the current version.
Getting the following error:
pytorch/aten/src/TH/generic/THTensorLapack.c:860:7: warning: unused variable ‘n’ [-Wunused-variable]
   int n = ra__->size[1];
       ^
make[2]: *** [src/ATen/CMakeFiles/ATen.dir/__/TH/THTensor.cpp.o] Error 1
make[1]: *** [src/ATen/CMakeFiles/ATen.dir/all] Error 2
make: *** [all] Error 2

I am using Anaconda as directed in the readme.  I have created a conda environment and have set:
 export CMAKE_PREFIX_PATH="/u/anaconda2/envs/pyt4/"
As specified here: https://stackoverflow.com/questions/47799803/installing-from-source-within-anaconda-environment

Thanks

**Comment by apaszke** [comment] 2018-02-04 17:40
What you posted here is only a warning, and it won't stop the build. Please paste the full log into a GitHub gist and link it here

**Comment by pj-parag** [comment] 2018-02-05 02:34
Hi,
Here are the logs: https://gist.github.com/pj-parag/519bb9f0b92a9e03f8b3dba70993f083
I see it says  Could NOT find CUDNN, I am installing it in an env which submit jobs to a cluster, do I need to install CUDNN locally?

**Comment by soumith** [comment] 2018-02-05 06:41
what compiler do you have? and what OS are you using?

The issue is this:

```
/u/pytorch/aten/src/THS/generic/THSTensor.cpp:357:98: error: expected ‘)’ before ‘PRId64’
   THArgCheck(d1 < nDimI && d2 < nDimI, 0, "Transposed dimensions should be sparse. Got nDimI: %" PRId64 ", d1: %" PRId64 ", d2: %" PRId64, nDimI, d1, d2);
```

**Comment by pj-parag** [comment] 2018-02-05 06:43
**lsb_release -a**
LSB Version:    :core-4.1-amd64:core-4.1-noarch:cxx-4.1-amd64:cxx-4.1-noarch:desktop-4.1-amd64:desktop-4.1-noarch:languages-4.1-amd64:languages-4.1-noarch:printing-4.1-amd64:printing-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.2 (Maipo)
Release:        7.2
Codename:       Maipo


**uname -a**
Linux dccxc001.pok.ibm.com 3.10.0-327.el7.x86_64 #1 SMP Thu Oct 29 17:29:29 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by neerajprad** [comment] 2018-02-05 07:00
@soumith - We are seeing the same error above with the build scripts that you provided in #4178, on PyTorch master. I can bisect and let you know the commit that is breaking the build.

**Comment by neerajprad** [comment] 2018-02-05 08:01
The CPU build script fails with this commit (#4041) - https://github.com/pytorch/pytorch/commit/96239dd50e89bc2d1fd5d91cc5ee8fca95b07f90.

**Comment by bheinzerling** [comment] 2018-02-05 13:10
Got the same error when trying to compile under CentOS 7.2.1511 with GCC 4.8 and GCC 5.4 (no newer gcc available on that server).

**Comment by ezyang** [comment] 2018-02-05 16:33
CC @yf225

**Comment by bheinzerling** [comment] 2018-02-07 13:39
Searching issues for "PRId64" shows that this error popped up and has been fixed in various places in the pytorch codebase, e.g. https://github.com/pytorch/pytorch/issues/3571

The problem seems to be that this format specifier is not defined by default in C++ and/or old gcc versions. A hacky way to fix this is replacing `"%" PRId64 "` with `"%lld"` in the two files currently causing this error. A better way is to find the proper place for addding

```#define __STDC_FORMAT_MACROS
#include <inttypes.h>``` as described in the issue linked above.

**Comment by yf225** [comment] 2018-02-13 23:19
@bheinzerling Could you try and see if the `PRId64_fix` branch in https://github.com/yf225/pytorch/ fixes the issue? I wasn't able to reproduce the compile error locally, but based on the past issues it should be the right fix. Thanks!

**Comment by bheinzerling** [comment] 2018-02-14 00:45
@yf225 your branch compiles without error in GCC 5.4

**Closed** 2018-02-14 03:42 UTC
