### ISSUE TITLE
equal method of Variable is broken

### ISSUE THREAD

**Issue by odanado** [pytorch/pytorch#3106] opened 2017-10-13 11:27 UTC
# code
```python
a = autograd.Variable(torch.ones(1000))
b = autograd.Variable(torch.ones(1000))
print(a.data.eq(b.data).sum()) # 1000
print(a.eq(b).sum().data[0]) # 232
```

# environment
- ubuntu 16.04
- python3
- pytorch 0.2.0_4

**Comment by albanD** [comment] 2017-10-13 12:08
This is a duplicate of #2124 .

**Comment by odanado** [comment] 2017-10-13 12:34
OK, Thank you.

**Closed** 2017-10-13 12:34 UTC
