### ISSUE TITLE
llama-fast produces gibberish with --device mps, works with --device cpu

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#123151] opened 2024-04-02 04:56 UTC
### 🐛 Describe the bug

MPS produces garbage with stories15M using llama-fast:
Repro:
Produces gibberish when using --device mps, but works correctly with --device cpu:
```
git clone https://github.com/pytorch-labs/llama-fast.git
cd llama-fast
# obtain snapshots for stories15M from https://huggingface.co/karpathy/tinyllamas/tree/main
# obtain tokenizer.model from https://github.com/karpathy/llama2.c/blob/master/tokenizer.model
python generate.py  --checkpoint_path checkpoints/$MODEL_REPO/stories15M.pt --prompt "Hello, my name is" --device mps

(py311) mikekg@mikekg-mbp llama-fast % python generate.py  --checkpoint_path checkpoints/$MODEL_REPO/stories15M.pt --prompt "Hello, my name is" --device mps
Using device=mps
Loading model ...
name stories15M
Time to load model: 0.10 seconds
tensor([    1, 15043, 29892,   590,  1024,   338], device='mps:0',
       dtype=torch.int32)
x: tensor([[    1, 15043, 29892,   590,  1024,   338]], device='mps:0',
       dtype=torch.int32), input_pos: tensor([0, 1, 2, 3, 4, 5], device='mps:0')
<sliced> x: tensor([[1]], device='mps:0', dtype=torch.int32), input_pos: tensor([0], device='mps:0')
<sliced> x: tensor([[15043]], device='mps:0', dtype=torch.int32), input_pos: tensor([1], device='mps:0')
<sliced> x: tensor([[29892]], device='mps:0', dtype=torch.int32), input_pos: tensor([2], device='mps:0')
<sliced> x: tensor([[590]], device='mps:0', dtype=torch.int32), input_pos: tensor([3], device='mps:0')
<sliced> x: tensor([[1024]], device='mps:0', dtype=torch.int32), input_pos: tensor([4], device='mps:0')
<sliced> x: tensor([[338]], device='mps:0', dtype=torch.int32), input_pos: tensor([5], device='mps:0')
/Users/mikekg/pytorch/pytorch/torch/backends/cuda/__init__.py:342: FutureWarning: torch.backends.cuda.sdp_kernel() is deprecated. In the future, this context manager will be removed. Please see, torch.nn.attention.sdpa_kernel() for the new context manager, with updated signature.
  warnings.warn(
Hello, my name is Jane. Theakter was three years old andниками wasMen. One day, Jane was walking down the street and she saw a growl. She was a bit scared andevenamed, so she decided to peek.VICE could see that高 was Doctor modern.
"What's that woll, Oriental?"itedquin asked. 
"I'm"> Notes!" said destination basesarias, honking to.’
"Don't worry little Imageus, I'm here to help you," replied Turkeykey bid the tableViewvwork toiesen.
The milieuableared five imagine functionalityi drivers and |ippetament. He was a shoulders crawl, extendsive with all of Vé ponies. He walked closer to sposi and said, "Hellougs! Are you тогоus? Do you want to be friends?"
Jami washboxus, but he wasn't sure what ejecuszkfamed. He thought for a moment before
Time for inference 1: 2.10 sec total, 95.24 tokens/sec
Bandwidth achieved: 9.30 GB/s
x: tensor([[    1, 15043, 29892,   590,  1024,   338]], device='mps:0',
       dtype=torch.int32), input_pos: tensor([0, 1, 2, 3, 4, 5], device='mps:0')
<sliced> x: tensor([[1]], device='mps:0', dtype=torch.int32), input_pos: tensor([0], device='mps:0')
<sliced> x: tensor([[15043]], device='mps:0', dtype=torch.int32), input_pos: tensor([1], device='mps:0')
<sliced> x: tensor([[29892]], device='mps:0', dtype=torch.int32), input_pos: tensor([2], device='mps:0')
<sliced> x: tensor([[590]], device='mps:0', dtype=torch.int32), input_pos: tensor([3], device='mps:0')
<sliced> x: tensor([[1024]], device='mps:0', dtype=torch.int32), input_pos: tensor([4], device='mps:0')
<sliced> x: tensor([[338]], device='mps:0', dtype=torch.int32), input_pos: tensor([5], device='mps:0')
Hello, my name is Frosty. He is Ohioo. He islibso thegot. Every dayapper he will Tun sci."
Squid Errictwo. Psycho learns new names. He knows until he is lose his Staato. He hears happy faces and his алster veelscripts.
Happy aprèsContainernie Elementns are fiely. He can't understand why he has no policcessa. But he stops championnatads andonnéesAns implementationaCall. He hopes to find a tylaizaçãoa puòa back to groupingAnpress.
At this śiage, TierAnn's спорa issuit fictarierea Sen upon aantina. He says, "But I want to play, not weights. I'm glad that you can find a передаarok andientrasa."
The [ gladitAnndestroy memosa and he ko Socks he过a thatavoa $('#a wasusage. He is
Time for inference 2: 1.81 sec total, 110.28 tokens/sec
Bandwidth achieved: 10.77 GB/s
x: tensor([[    1, 15043, 29892,   590,  1024,   338]], device='mps:0',
       dtype=torch.int32), input_pos: tensor([0, 1, 2, 3, 4, 5], device='mps:0')
<sliced> x: tensor([[1]], device='mps:0', dtype=torch.int32), input_pos: tensor([0], device='mps:0')
<sliced> x: tensor([[15043]], device='mps:0', dtype=torch.int32), input_pos: tensor([1], device='mps:0')
<sliced> x: tensor([[29892]], device='mps:0', dtype=torch.int32), input_pos: tensor([2], device='mps:0')
<sliced> x: tensor([[590]], device='mps:0', dtype=torch.int32), input_pos: tensor([3], device='mps:0')
<sliced> x: tensor([[1024]], device='mps:0', dtype=torch.int32), input_pos: tensor([4], device='mps:0')
<sliced> x: tensor([[338]], device='mps:0', dtype=torch.int32), input_pos: tensor([5], device='mps:0')
Hello, my name is Bull. Thelinks was veryurreed. He lived in aPHply andAPPboardedcrefa. He was làa and he was Ignorant.
One day, Ivy was playing in a switched space. Ivy noticed theCMre was средreling,iendoreingrightarrowre. He was różest who wasschaftenas and Descriptionrele estatus. He said, "I am reallygroupIdest than you!"
Ivyle wasEmpant and notederbördest. Iier than you are. I am forallis."
Woolierantenle heard about his statedasant and ${releuousestant. He thought plaatsre sotmlasant that he wanted to show memory too. So, he found a tibest Киest débutre,¡estantrel.
The pandas andimportanthowvity andournured hoogest. He taught himself lots of Référencesin knowledge, segúnestity,青est ceiling up to his
Time for inference 3: 1.83 sec total, 109.57 tokens/sec
Bandwidth achieved: 10.70 GB/s
```

Correct operation:
git clone https://github.com/pytorch-labs/llama-fast.git
cd llama-fast
python generate.py  --checkpoint_path checkpoints/$MODEL_REPO/stories15M.pt --prompt "Hello, my name is" --device cpu

```
(py311) mikekg@mikekg-mbp llama-fast % python generate.py  --checkpoint_path checkpoints/$MODEL_REPO/stories15M.pt --prompt "Hello, my name is" --device cpu
Using device=cpu
Loading model ...
name stories15M
Time to load model: 0.01 seconds
tensor([    1, 15043, 29892,   590,  1024,   338], dtype=torch.int32)
x: tensor([[    1, 15043, 29892,   590,  1024,   338]], dtype=torch.int32), input_pos: tensor([0, 1, 2, 3, 4, 5])
<sliced> x: tensor([[1]], dtype=torch.int32), input_pos: tensor([0])
<sliced> x: tensor([[15043]], dtype=torch.int32), input_pos: tensor([1])
<sliced> x: tensor([[29892]], dtype=torch.int32), input_pos: tensor([2])
<sliced> x: tensor([[590]], dtype=torch.int32), input_pos: tensor([3])
<sliced> x: tensor([[1024]], dtype=torch.int32), input_pos: tensor([4])
<sliced> x: tensor([[338]], dtype=torch.int32), input_pos: tensor([5])
/Users/mikekg/pytorch/pytorch/torch/backends/cuda/__init__.py:342: FutureWarning: torch.backends.cuda.sdp_kernel() is deprecated. In the future, this context manager will be removed. Please see, torch.nn.attention.sdpa_kernel() for the new context manager, with updated signature.
  warnings.warn(
Hello, my name is Toby. Toby loves to play with all the toys in his room. One day, he heard a loud noise coming from outside. He looked out the window and saw a raven! Toby was very excited, he had never seen a raven before.
“Hello!” shouted Toby. “Do you want to play with me?”
The raven looked at Toby and said, “Yes! I do! What’s your name?”
Toby said “My name is Toby. Can you come inside and play with me?”
The raven said, “Sure! I’m a bit naughty. Let’s play together.”
So Toby and the raven played all day. They played with a ball of yarn, tag and even made a house out of mud. Toby was so happy to have a new friend!
At the end of the day, Toby said goodbye to the ra
Time for inference 1: 1.01 sec total, 197.27 tokens/sec
Bandwidth achieved: 19.26 GB/s
x: tensor([[    1, 15043, 29892,   590,  1024,   338]], dtype=torch.int32), input_pos: tensor([0, 1, 2, 3, 4, 5])
<sliced> x: tensor([[1]], dtype=torch.int32), input_pos: tensor([0])
<sliced> x: tensor([[15043]], dtype=torch.int32), input_pos: tensor([1])
<sliced> x: tensor([[29892]], dtype=torch.int32), input_pos: tensor([2])
<sliced> x: tensor([[590]], dtype=torch.int32), input_pos: tensor([3])
<sliced> x: tensor([[1024]], dtype=torch.int32), input_pos: tensor([4])
<sliced> x: tensor([[338]], dtype=torch.int32), input_pos: tensor([5])
Hello, my name is Scale. He has a purple home on a tall hill. He loves exploring the woods and making new friends.
One day, he saw something strange. The sky was blue and it was starting to rain. He felt a little sad. What if the rain made him cry?
He decided to stay and look for shelter. He ran around, looking for help, but he couldn't find one. Soon, he saw a large, empty house. He ran up to the house and tried to open the door, but it was locked.
He tried to find a way home, but nothing worked. He was very sad and he started to cry. Suddenly, he heard a voice. It was an old man. He said in a gentle voice, "It's not fair that you want the house. You must find other ways that you can enjoy, like finding a new home."
Scale thought for a moment and then he found a
Time for inference 2: 1.05 sec total, 190.49 tokens/sec
Bandwidth achieved: 18.60 GB/s
```

### Versions

Collecting environment information...
PyTorch version: 2.4.0a0+gitccfc87b
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.4.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.26.4
Libc version: N/A

Python version: 3.11.8 (main, Feb 26 2024, 15:36:12) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-14.4.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.10.0
[pip3] torch==2.4.0a0+gitccfc87b
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
[conda] torch                     2.4.0a0+gitccfc87b           dev_0    <develop>

cc @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen @razarmehr

**Comment by jbschlosser** [comment] 2024-04-02 15:58
Any insight into which ops are responsible for the wildly differing results?

**Comment by mikekgfb** [comment] 2024-04-05 08:57
> Any insight into which ops are responsible for the wildly differing results?

IDK.  What's worse is that tonight it works...

```
(py311) mikekg@mikekg-mbp llama-fast % python generate.py  --checkpoint-path checkpoints/$MODEL_NAME/stories15M.pt --prompt "Hello, my name is" --device mps

Could not import fairseq2 modules.
Using device=mps
Loading model ...
name stories15M
Time to load model: 0.13 seconds
tensor([    1, 15043, 29892,   590,  1024,   338], device='mps:0',
       dtype=torch.int32)
x: tensor([[    1, 15043, 29892,   590,  1024,   338]], device='mps:0',
       dtype=torch.int32), input_pos: tensor([0, 1, 2, 3, 4, 5], device='mps:0', dtype=torch.int32)
<sliced> x: tensor([[1]], device='mps:0', dtype=torch.int32), input_pos: tensor([0], device='mps:0', dtype=torch.int32)
<sliced> x: tensor([[15043]], device='mps:0', dtype=torch.int32), input_pos: tensor([1], device='mps:0', dtype=torch.int32)
<sliced> x: tensor([[29892]], device='mps:0', dtype=torch.int32), input_pos: tensor([2], device='mps:0', dtype=torch.int32)
<sliced> x: tensor([[590]], device='mps:0', dtype=torch.int32), input_pos: tensor([3], device='mps:0', dtype=torch.int32)
<sliced> x: tensor([[1024]], device='mps:0', dtype=torch.int32), input_pos: tensor([4], device='mps:0', dtype=torch.int32)
<sliced> x: tensor([[338]], device='mps:0', dtype=torch.int32), input_pos: tensor([5], device='mps:0', dtype=torch.int32)
/Users/mikekg/pytorch/pytorch/torch/backends/cuda/__init__.py:342: FutureWarning: torch.backends.cuda.sdp_kernel() is deprecated. In the future, this context manager will be removed. Please see, torch.nn.attention.sdpa_kernel() for the new context manager, with updated signature.
  warnings.warn(
Hello, my name is Jane. The other neighbours say hello to him and he says that they are here to play and have fun. He is very popular, so everyone looks forward to him.
One day, Jane went outside to play with her friends. They were playing a game of tag in the garden. They were running around in circles, laughing and having a great time.
Suddenly, they heard a loud noise - it was coming from the street. She got scared and ran to her mum. 
"Mum, what is that noise?" she asked.
"It's just the drivers driving their cars, sweetheart," her mum replied.
"But it's too loud and scary," Jane said.
"It's okay," her mum said. "It's just that the traffic is moving. You don't have to worry about the noise. Look, there's a little bug crawling away."

Time for inference 1: 2.55 sec total, 78.28 tokens/sec
Bandwidth achieved: 7.64 GB/s
```

Do we just close and reopen again when this happens?

**Comment by albanD** [comment] 2024-04-09 20:36
@kulinseth any change that was done that would explain this being fixed?

**Comment by jhavukainen** [comment] 2024-04-09 22:16
@albanD I think this might also have been caused by the issue in creating scalars since it specifically shows up in MacOs14.4+. The regression was addressed here: https://github.com/pytorch/pytorch/pull/123234

**Comment by albanD** [comment] 2024-04-09 22:30
Awesome!
Closing this as done then. Feel free to re-open if we missed anything @mikekgfb

**Closed by albanD** 2024-04-09 22:30 UTC
Labels: triaged, module: correctness (silent), module: mps
