### ISSUE TITLE
Convolutional layer with bias=True causing crash

### ISSUE THREAD

**Issue by Andrej-sens** [pytorch/pytorch#30462] opened 2019-11-26 11:54 UTC
Hello,
I was trying to code example of neural network on CUDA. I have run some examples which they were working on CPU but not on GPU. 

Not sure if it's a bug or my mistake.

Please note that CUDA version of [MNIST example](https://github.com/Andrej-sens/libtorch_examples_cpp/blob/master/MNIST_Example_GPU.cpp) is working properly. 

How to replicate error, just change bias to false. With `bias=true` I am able to move network model to CUDA.
```
#include <torch/torch.h>

// Define a new Module.
struct Net : torch::nn::Module {
	Net() {
		torch::nn::Conv2d conv = torch::nn::Conv2d(torch::nn::Conv2dOptions(3, 16, 3)
			.bias(true)
			.stride(1)
			.padding(1)
		);

		module->push_back(conv);

		register_module("Layer",module);
	}

	torch::Tensor forward(torch::Tensor x) {
		/**SOME FORWARD**/
		return x;
	}

	torch::nn::Sequential module;
};

int main() {
	auto net = std::make_shared<Net>();
	net->to(at::kCUDA); // It crashes here
}
```

It will throw
```
Exception thrown at 0x00007FFB4A2EA839 in Object_detection.exe: Microsoft C++ exception: c10::Error at memory location 0x000000635F0FDE90.
Unhandled exception at 0x00007FFB4A2EA839 in Object_detection.exe: Microsoft C++ exception: c10::Error at memory location 0x000000635F0FDE90.
```

Thank you very much for any advise.

cc @ezyang @gchanan @zou3519 @jerryzh168 @yf225

**Comment by Andrej-sens** [comment] 2019-11-26 14:14
Update:
It crashes even if `net->to(at::kCPU);` is called with `bias=false`. It seems the problem is in calling command itself.

Since CPU version of model is default it will work.

**Comment by pietern** [comment] 2019-11-27 15:23
@Andrej-sens Thanks for reporting. I've renamed the issue to reflect it's not specific to CUDA.

**Comment by Andrej-sens** [comment] 2019-11-27 15:27
Thank you. 
It seems it's related to [this post](https://github.com/pytorch/pytorch/issues/30508) with full report.

**Comment by pietern** [comment] 2019-11-27 15:34
Thanks for linking. It's the same issue with an exception included. Let's close this one.

**Closed by pietern** 2019-11-27 15:34 UTC
Labels: high priority, module: cpp, topic: crash, triage review

**Comment by pietern** [comment] 2019-11-27 15:35
Duplicate of #30508.
