### ISSUE TITLE
min/max refuse to work on non-zero dimension of empty tensors

### ISSUE THREAD

**Issue by xkszltl** [pytorch/pytorch#42429] opened 2020-08-02 20:55 UTC
## 🐛 Bug

min/max refuse to work on non-zero dimension of empty tensor.
My understanding is the "op does not have identity" issue should only apply to zero dimension.

## To Reproduce

```
Python 3.6.9 (default, Jul 17 2020, 12:50:27) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.rand((0,4)).max(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: cannot perform reduction function max on tensor with no elements because the operation does not have an identity
```

## Expected behavior

Empty tensor with proper size for non-zero dimensions.

## Environment

```
Collecting environment information...
PyTorch version: 1.7.0a0+72378e9
Is debug build: No
CUDA used to build PyTorch: 11.0

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.18.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 440.33.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.2

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.7.0a0+72378e9
[pip3] torchvision==0.8.0a0+6db1569
[conda] Could not collect
```

 - PyTorch Version (e.g., 1.0): master (1.7.0a0+72378e9)
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): source
 - Build command you used (if compiling from source): cmake+ninja+gcc-8
 - Python version: 3.6
 - CUDA/cuDNN version: 11.0/8.0
 - GPU models and configuration: V100

**Comment by ngimel** [comment] 2020-08-03 02:09
Duplicate of #34907, closing.

**Closed by ngimel** 2020-08-03 02:09 UTC
