### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement torch (from versions: none) ERROR: No matching distribution found for torch

### ISSUE THREAD

**Issue by perymerdeka** [pytorch/pytorch#114127] opened 2023-11-20 14:44 UTC
### 🐛 Describe the bug

I have followed the installation procedure, pytorch but I encountered an error

ERROR: Could not find a version that satisfies the torch requirements (from versions: none)
ERROR: No matching distribution found for torch

I use command

pip install torch -f https://download.pytorch.org/whl/cu113/torch_stable.html

and I followed the official docs: https://pytorch.org/get-started/locally/

and got the same error, anyone can help?

### Versions

$ python collect_env.py 
Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22621-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=206
L2CacheSize=1024
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3600
Name=Intel(R) Core(TM) i3-10100 CPU @ 3.60GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.2
[conda] Could not collect

**Comment by malfet** [comment] 2023-11-20 16:00
Closing as duplicate of https://github.com/pytorch/pytorch/issues/110436
Please downgrade to python-3.11 or even 3.8 as there unlikely going to be a version of PyTorch that supports 3.11 and CUDA-11.3
Please note, that PyTorch with 3.12 should be currently available from nighlites

**Closed by malfet** 2023-11-20 16:00 UTC

**Comment by selimunal** [comment] 2024-01-25 20:34
"pip3 install torch" doesn't work 
"pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu" works

**Comment by capamir** [comment] 2024-01-29 09:41
> pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu

it really worked, thanks buddy

**Comment by Aeron00** [comment] 2024-01-30 08:15
@selimunal thanks it worked

**Comment by HAyoHisaro** [comment] 2024-06-30 19:23
> «pip3 install torch» не работает «pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu » работает

можешь помочь не могу установить subprocess в Termux ни в какую не хочет.
![x8ccvLR-mCU](https://github.com/pytorch/pytorch/assets/174262040/870c57e2-cc27-40cd-8607-8bf4190816ee)

**Comment by Urtats-Code** [comment] 2024-12-05 11:08
> "pip3 install torch" doesn't work "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu" works

This has worked for me! Thanks buddy

**Comment by derainzhou** [comment] 2024-12-12 08:18
> "pip3 install torch" doesn't work "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu" works

Thanks a lot, that's work;

**Comment by DiplexTerror80-GitHub** [comment] 2024-12-25 20:01
> "pip3 install torch" doesn't work "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu" works

Thanks, it worked!

**Comment by devodii** [comment] 2024-12-30 14:44
> --pre torch torchvision to

works like a charm.

**Comment by devodii** [comment] 2024-12-30 14:44
> "pip3 install torch" doesn't work "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu" works

works like a charm!

**Comment by nopal-fz** [comment] 2025-01-29 04:18
> "pip3 install torch" doesn't work "pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu" works

it works to me bro, thanks

**Comment by brynwhyman** [comment] 2025-05-08 00:45
Hey, any thoughts on the issue I'm seeing?

`pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu` gives:

> Looking in indexes: https://download.pytorch.org/whl/nightly/cpu
> ERROR: Could not find a version that satisfies the requirement torch (from versions: none)

Running Python 3.10.17

**Comment by SurawutSukkum** [comment] 2025-05-12 08:50
> Python 3.14.0a7
> PS C:\Users\Downloads\ultralytics> pip install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu
> Looking in indexes: https://download.pytorch.org/whl/nightly/cpu
> ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
> ERROR: No matching distribution found for torch
