### ISSUE TITLE
torch.load() large tensor return 'invalid memory size'

### ISSUE THREAD

**Issue by NattapongSiri** [pytorch/pytorch#15728] opened 2019-01-04 10:31 UTC
## 🐛 Bug

Hello,

I'm having a problem of loading a serialized tensor from a file.
My tensor shape is [309000001, 2, 5] the dtype is torch.int8
When I deserialize the tensor using torch.load(), it yell "invalid memory size".
The line that it complain is:
https://github.com/pytorch/pytorch/blob/b740b92f3600840e09d4c93f3138333838d1e474/torch/serialization.py#L528-L529
It seem like the variable it used is destructured from here:
https://github.com/pytorch/pytorch/blob/b740b92f3600840e09d4c93f3138333838d1e474/torch/serialization.py#L525
Which also came from here:
https://github.com/pytorch/pytorch/blob/b740b92f3600840e09d4c93f3138333838d1e474/torch/serialization.py#L517
So I insert `print(saved_id)` where it yell:
Now, it print:
`('storage', <class 'torch.CharStorage'>, '2149339138576', 'cpu', -1204967286, None)`

It seem that size is negative.

## To Reproduce
```
import torch

torch.save(torch.zeros([309237982, 2, 5], dtype=torch.int8), './sample.pt')
torch.load('./sample.pt')
```
It can only be reproduce in MS.Windows environment.
My Windows version is:
10.0.17134.472
My Python version is:
3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)]
1. Run above code in MS. Windows

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-2-1e8f41ee3715> in <module>
      2 
      3 torch.save(torch.zeros([309237982, 2, 5], dtype=torch.int8), './sample.pt')
----> 4 torch.load('./sample.pt')

c:\users\nattapong\workspace\lstm_nlp\lib\site-packages\torch\serialization.py in load(f, map_location, pickle_module)
    365         f = open(f, 'rb')
    366     try:
--> 367         return _load(f, map_location, pickle_module)
    368     finally:
    369         if new_fd:

c:\users\nattapong\workspace\lstm_nlp\lib\site-packages\torch\serialization.py in _load(f, map_location, pickle_module)
    538     unpickler = pickle_module.Unpickler(f)
    539     unpickler.persistent_load = persistent_load
--> 540     result = unpickler.load()
    541 
    542     deserialized_storage_keys = pickle_module.load(f)

c:\users\nattapong\workspace\lstm_nlp\lib\site-packages\torch\serialization.py in persistent_load(saved_id)
    504                 print(data_type, size)
    505                 deserialized_objects[root_key] = restore_location(
--> 506                     data_type(size), location)
    507             storage = deserialized_objects[root_key]
    508             if view_metadata is not None:

RuntimeError: $ Torch: invalid memory size -- maybe an overflow? at ..\aten\src\TH\THGeneral.cpp:188

## Expected behavior

Tensor is loaded without error.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.0
 - OS (e.g., Linux): Windows 10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.7
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: No problem on Linux

## Additional context

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by NattapongSiri** [comment] 2019-01-04 10:38
The persisted file from Windows when loaded in Linux also result in the same error.
I didn't test load Linux file in Windows but save then load in Linux work fine.

**Comment by peterjc123** [comment] 2019-01-07 08:17
Probable duplicate of https://github.com/pytorch/pytorch/issues/12085 since Pickle is used when calling torch.save/load.

**Comment by ezyang** [comment] 2021-07-12 13:43
This is almost certainly due to someone using int where they should have used int64_t. Might have been accidentally fixed already

**Comment by cristianPanaite** [comment] 2022-10-18 10:05
Hello @NattapongSiri,

Closing this ticket as the ticket hasn't had any activity for a long period of time and it seems that it is not valid anymore. I tried to replicate this issue, but on the latest versions I don't get this error.

If you think the issue still persists, please open a new issue with details on how to reproduce it on the latest version.

**Closed** 2022-10-18 11:57 UTC
Labels: module: windows, triaged
