### ISSUE TITLE
[inductor][cpu]opacus_cifar10 fp32 static shape default wrapper multiple threads performance regression

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#117744] opened 2024-01-18 10:35 UTC
### 🐛 Describe the bug

<table border="1" role="table">
  <thead>
    <tr>
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>opacus_cifar10</td>
      <td>64</td>
      <td>0.613604</td>
      <td>0.011064978</td>
      <td>0.006789514760712</td>
      <td>59.939124</td>
      <td>64</td>
      <td>0.739715</td>
      <td>0.009038787</td>
      <td>0.006686126325705</td>
      <td>27.589113</td>
      <td>0.83</td>
      <td>0.98</td>
      <td>0.82</td>
      <td>0.46</td>
    </tr>

</table><p dir="auto">SW info</p><table border="1" role="table">
  <thead>
    <tr>
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/ea7e22973572b5fcf43ea05897c2cf56ace392da/hovercard" href="https://github.com/pytorch/pytorch/commit/ea7e22973572b5fcf43ea05897c2cf56ace392da"><tt>ea7e229</tt></a></td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>770d5cf7</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>dc83b38</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>c11d758</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>58366ab</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/1d231d1be03e66c1e3c929dd1d743f0358951d7d/hovercard" href="https://github.com/pytorch/pytorch/commit/1d231d1be03e66c1e3c929dd1d743f0358951d7d"><tt>1d231d1</tt></a></td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td><a class="commit-link" data-hovercard-type="commit" data-hovercard-url="https://github.com/pytorch/pytorch/commit/f228c8b8cac3db634516c7101dee077cbaa026ab/hovercard" href="https://github.com/pytorch/pytorch/commit/f228c8b8cac3db634516c7101dee077cbaa026ab"><tt>f228c8b</tt></a></td>
      <td>/</td>
    </tr>
  </tbody>
</table>

Repro:
bash [inductor_single_test.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh) multiple inference performance torchbench opacus_cifar10 float32 first static default 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/9862c7196b253973f81cea29503f961e9b393283
[torchbench-opacus_cifar10-inference-float32-static-default-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13975423/torchbench-opacus_cifar10-inference-float32-static-default-performance-multiple-drop_guilty_commit.log)
cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @WeizhuoZhang-intel @chuanqi129

**Comment by masnesral** [comment] 2024-02-15 18:39
This is assigned, so adding the triaged label to remove it from our queue of untriaged

**Comment by leslie-fang-intel** [comment] 2024-02-18 01:34
Also cc @yanboliang, since the suspected commit which causes regression points to https://github.com/pytorch/pytorch/commit/9862c7196b253973f81cea29503f961e9b393283

**Comment by blzheng** [comment] 2024-03-21 08:02
According to the latest report (https://github.com/pytorch/pytorch/issues/93531#issuecomment-2005389792), the absolute latency of inductor is 9.360099 ms, which is close to the latency before regression (9.038787ms).

**Comment by leslie-fang-intel** [comment] 2024-03-21 08:22
Close this issue as it's close to the data before regression.

**Closed by leslie-fang-intel** 2024-03-21 08:22 UTC
Labels: triaged, oncall: pt2, oncall: cpu inductor
