### ISSUE TITLE
Inconsistent behavior of fmod

### ISSUE THREAD

**Issue by Aidyn-A** [pytorch/pytorch#78855] opened 2022-06-03 22:24 UTC
### 🐛 Describe the bug

A short code snippet to reproduce the problem:
```
import torch

def check_fmod(n, dtype = torch.float32, device = 'cpu'): 
    a = torch.randn(n, device = device, dtype = dtype)
    b = torch.randn(n, device = device, dtype = dtype)

    random_index = torch.randint(0, n, size = (1,)).item()
    a[random_index] = torch.tensor(8.0, device = device, dtype = dtype)
    b[random_index] = torch.tensor(2.0e-38, device = device, dtype = dtype) 

    res1 = torch.fmod(a, b)
    print(n, res1[random_index])

for n in range(1, 64):
    check_fmod(n, dtype = torch.float32, device = 'cpu')
```

Expected output: all the returned results must be the same. 

Please pay attention that the code snippet prints consistent values for n<16 when `dtype = torch.float32` and for n<32 when `dtype = torch.bfloat16`.

cc @mruberry @ngimel @ptrblck @syed-ahmed 

### Versions

PyTorch version: 1.13.0a0+git7fc7328
Is debug build: True
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.19.6
Libc version: glibc-2.27

Python version: 3.9.12 (main, Apr  5 2022, 06:56:58)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-113-generic-x86_64-with-glibc2.27
Is CUDA available: False
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro P620
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: False

Versions of relevant libraries:
[pip3] mypy==0.950
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.13.0a0+git7fc7328
[pip3] torchviz==0.0.2
[conda] blas                      1.0                         mkl  
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-include               2022.0.1           h06a4308_117  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.20.0                   pypi_0    pypi
[conda] numpy-base                1.21.5           py39hf524024_1  
[conda] torch                     1.13.0a0+git7fc7328           dev_0    <develop>
[conda] torchviz                  0.0.2                    pypi_0    pypi

**Comment by ngimel** [comment] 2022-06-03 22:47
duplicate of #77742

**Closed by ngimel** 2022-06-03 22:47 UTC
