### ISSUE TITLE
Windows Cuda 11.5 cudnn 8.3.2.44 fails tests with RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#72091] opened 2022-02-01 00:16 UTC
### 🐛 Describe the bug

Following Windows job is failing:
https://github.com/pytorch/pytorch-canary/runs/5010488229?check_suite_focus=true

Error From Test 1:
======================================================================
ERROR [1.166s]: test_autocast_rnn (__main__.TestCuda)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 807, in wrapper
    fn(*args, **kwargs)
  File "test_cuda.py", line 3019, in test_autocast_rnn
    out, h_out = rnn(x, h)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\rnn.py", line 480, in forward
    result = _VF.rnn_tanh(input, batch_sizes, hx, self._flat_weights, self.bias,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

----------------------------------------------------------------------
Ran 164 tests in 30.750s

FAILED (errors=1, skipped=62, expected failures=3)

Generating XML reports...
Generated XML report: test-reports\python-unittest\test_cuda\TEST-TestCuda-20220131185549.xml
Generated XML report: test-reports\python-unittest\test_cuda\TEST-TestCudaComm-20220131185549.xml
Traceback (most recent call last):
  File "run_test.py", line 1101, in <module>
    main()
  File "run_test.py", line 1079, in main
    raise RuntimeError(err_message)
RuntimeError: test_cuda failed!

(base) C:\actions-runner\_work\pytorch-canary\pytorch-canary\test>if ERRORLEVEL 1 goto fail 

(base) C:\actions-runner\_work\pytorch-canary\pytorch-canary\test>exit /b 1 

Test #2 failure:

======================================================================
ERROR [1.863s]: test_snli_cuda (jit.test_models.TestModels)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\test\jit\test_models.py", line 412, in test_snli_cuda
    self._test_snli(self, device='cuda', check_export_import=False)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\test\jit\test_models.py", line 396, in _test_snli
    self.checkTrace(SNLIClassifier(Config()).to(device), (premise, hypothesis),
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\testing\_internal\jit_utils.py", line 563, in checkTrace
    ge = torch.jit.trace(func, input_tensors, check_tolerance=check_tolerance,
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\jit\_trace.py", line 741, in trace
    return trace_module(
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\jit\_trace.py", line 958, in trace_module
    module._c._create_method_from_trace(
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\test\jit\test_models.py", line 367, in forward
    premise = self.encoder(prem_embed)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\test\jit\test_models.py", line 329, in forward
    outputs, (ht, ct) = self.rnn(inputs, (h0, c0))
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1098, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\rnn.py", line 761, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

======================================================================
ERROR [0.150s]: test_weak_cuda (__main__.TestScript)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_jit.py", line 15168, in test_weak_cuda
    out = m(torch.ones(5, 5, 5).cuda())
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 422, in prof_meth_call
    return prof_callable(meth_call, *args, **kwargs)
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\testing\_internal\common_utils.py", line 416, in prof_callable
    return callable(*args, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "test_jit.py", line 15164, in forward
            @torch.jit.script_method
            def forward(self, x):
                return self.lstm(x)
                       ~~~~~~~~~ <--- HERE
  File "C:\actions-runner\_work\pytorch-canary\pytorch-canary\build\win_tmp\build\torch\nn\modules\rnn.py", line 761, in forward__0
        self.check_forward_args(input, hx, batch_sizes)
        if batch_sizes is None:
            result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
                     ~~~~~~~~ <--- HERE
                              self.dropout, self.training, self.bidirectional, self.batch_first)
        else:
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.


----------------------------------------------------------------------
Ran 2773 tests in 270.172s

FAILED (errors=2, skipped=154, expected failures=9)

### Versions

cudnn 8.3.2.44

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @csarofeen @ptrblck @xwang233

**Comment by ngimel** [comment] 2022-02-01 00:21
It's possible that #72089 will fix that

**Comment by ngimel** [comment] 2022-02-01 17:54
#72089 has landed, can you check if the issue is fixed?

**Comment by atalman** [comment] 2022-02-01 17:59
Yes running the test now, Test #2 passed, watiting for test #1 to pass, ref: https://github.com/pytorch/pytorch-canary/runs/5023876406?check_suite_focus=true

**Comment by ngimel** [comment] 2022-02-01 18:16
Tests passed.

**Closed by ngimel** 2022-02-01 18:16 UTC
Labels: module: windows, module: cudnn, triaged, module: regression
