### ISSUE TITLE
native functions: int arg does not accept np.int64

### ISSUE THREAD

**Issue by SsnL** [pytorch/pytorch#27714] opened 2019-10-10 19:29 UTC
```py
In [1]: import torch

In [3]: import numpy as np

In [9]: x = torch.randn(100)

In [11]: x.narrow(0, 0, np.array(3, dtype=np.int64).sum())
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-9e6bc07f0d80> in <module>
----> 1 x.narrow(0, 0, np.array(3, dtype=np.int64).sum())

TypeError: narrow(): argument 'length' (position 3) must be int, not numpy.int64

In [4]: torch.randn(np.array(3))  # notice IntArray parses these fine
Out[4]: tensor([-1.1104, -0.0871,  1.2771])

In [5]: torch.randn((np.array(3),))  # notice IntArray parses these fine
Out[5]: tensor([-0.5826, -0.1124, -0.4657])

In [6]: torch.randn(size=(np.array(3),))  # notice IntArray parses these fine
Out[6]: tensor([-0.9595, -0.6848, -0.6971])

In [7]: torch.randn(size=(np.array(3, dtype=np.int64),))  # notice IntArray parses these fine
Out[7]: tensor([-1.1161,  1.4269,  1.5838])

````

cc @ezyang @gchanan @zou3519

**Comment by cpuhrsch** [comment] 2019-10-10 20:53
Is this an error due to recent changes or a feature request?

**Comment by SsnL** [comment] 2019-10-10 20:57
@cpuhrsch More like a bug report. It is inconsistent. I'm not sure if it works before though...

**Comment by cpuhrsch** [comment] 2019-10-10 21:02
I'm marking this high priority and for triage review in case it's expected to case further issues down the road and because I don't have a good overview of the community here.

**Comment by ezyang** [comment] 2019-10-11 16:58
The suggested change seems reasonable to do, but I'm not sure I would mark it as high priority (seems pretty niche)

**Comment by SsnL** [comment] 2019-10-11 19:42
The root cause is that parsing `intlist` uses `THPUtils_unpackIndex` (which uses `PyNumber_Index`) while parsing an int uses `THPUtils_unpackLong` (which uses `PyNumber_Long`). I don't have enough knowledge on when to use one vs the other, and googling doesn't help much.

**Comment by gchanan** [comment] 2019-10-14 18:02
Removing "triaged" because this wasn't triaged.

**Comment by gchanan** [comment] 2019-10-14 18:03
Related issue: https://github.com/pytorch/pytorch/issues/27754 for better handling of numpy scalars.

I'd also probably not make it high priority, but it's a reasonable request, and it doesn't have complicated issues like https://github.com/pytorch/pytorch/issues/27754 does.

**Comment by zou3519** [comment] 2020-01-29 17:08
@nairbv I remember you had a PR that allows accepting np.ints as ints in python arg parser. Did that fix this issue?

**Comment by nairbv** [comment] 2020-01-29 18:51
> @nairbv I remember you had a PR that allows accepting np.ints as ints in python arg parser. Did that fix this issue?

Yes as far as I can tell this seems to be fixed by:
https://github.com/pytorch/pytorch/pull/30486

```
>>> x=torch.randn(100)
>>> x.narrow(0, 0, np.array(3, dtype=np.int64).sum())
tensor([0.3604, 0.8545, 1.5196])
```

**Comment by mruberry** [comment] 2020-02-18 21:02
Confirmed this passes on master.

**Closed by mruberry** 2020-02-18 21:02 UTC
Labels: module: numpy, module: operators, triaged
