### ISSUE TITLE
Implementation of nn.Conv2d.output_size(x: torch.Tensor)

### ISSUE THREAD

**Issue by tuttelikz** [pytorch/pytorch#82559] opened 2022-08-01 05:18 UTC
### 🚀 The feature, motivation and pitch

A helper function to estimate output size of PyTorch tensor after convolutional layer, according to definition in [`nn.Conv2d`](https://pytorch.org/docs/stable/generated/torch.nn.Conv2d.html). The idea is to get output size without actual forward pass, in `O(1)`.

![output_conv2d](https://user-images.githubusercontent.com/6753761/182076829-f4651b74-7e0c-4db7-93f5-5021008b4fc2.png)

Use case example:

```python
import torch
import torch.nn as nn

c_i, c_o = 3, 16
k, s, p = 3, 2, 1
  
sample_2d_tensor = torch.ones((c_i, 64, 64))
conv_layer = nn.Conv2d(in_channels=c_i, out_channels=c_o, kernel_size=k, stride=s, padding=p)  
  
print(f"Output size: {conv_layer.output_size(sample_2d_tensor)}")
```
```python
>>> Output size: (16, 32, 32)
```

A _possible_ implementation:
```python
import numpy as np
import torch
import torch.nn as nn

def conv2d_output_size(input_size, out_channels, padding, kernel_size, stride, dilation=None):
    if dilation is None:
        dilation = (1, ) * 2
    if isinstance(padding, int):
        padding = (padding, ) * 2
    if isinstance(kernel_size, int):
        kernel_size = (kernel_size, ) * 2
    if isinstance(stride, int):
        stride = (stride, ) * 2

    output_size = (
        out_channels,
        np.floor((input_size[1] + 2 * padding[0] - dilation[0] * (kernel_size[0] - 1) - 1) /
                 stride[0] + 1).astype(int),
        np.floor((input_size[2] + 2 * padding[1] - dilation[1] * (kernel_size[1] - 1) - 1) /
                 stride[1] + 1).astype(int)
    )
    return output_size
```

### Alternatives
I am currently using https://github.com/tuttelikz/conv_output_size / passing a dummy tensor through the layer / manually calculate.

### Additional context
With analogous functionality for [`nn.Conv1d`](https://pytorch.org/docs/stable/generated/torch.nn.Conv1d.html) and [`nn.Conv3d`](https://pytorch.org/docs/stable/generated/torch.nn.Conv3d.html).
  
What do you guys think?

cc @albanD @mruberry @jbschlosser @walterddr @kshitij12345 @saketh-are

**Comment by kshitij12345** [comment] 2022-08-01 06:08
Looks like a duplicate of https://github.com/pytorch/pytorch/issues/79512.

**Comment by albanD** [comment] 2022-08-02 14:03
It is indeed. The following code sample will give you the result you want!
As a bonus, this same pattern works with most of the functions in pytorch!

```
import torch

a = torch.rand(2, 3, 10, 10, device="meta")

m = torch.nn.Conv2d(3, 5, 2, device="meta")

print(m(a).size())
```

**Closed** 2022-08-02 14:04 UTC
Labels: module: nn

**Comment by tuttelikz** [comment] 2022-08-02 18:21
Thanks for info, nice to hear the work is already there!  
   
@albanD, I tried the suggested snippet, it returns:  
`"NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function "`  

My configurations are up-to-date:
```
python=3.10.5
torch=1.12.0+cu116
```

Does it mean this functionality is not currently for the stable version?

**Comment by albanD** [comment] 2022-08-02 18:56
Hi,

This is not in the stable version indeed. You can install the preview build to get this!

**Comment by tuttelikz** [comment] 2022-08-04 02:24
looking forward, thanks!

**Comment by jamesbraza** [comment] 2023-03-21 22:52
@albanD I think this was a creative solution reusing basic tools, I like it!

I would like to get your thoughts on two aspects of the `torch.nn.Conv2d(in_chans, out_chans, kernel_size, device="meta")` solution I think are missing:
- Support of both `Conv2d` and `Conv3d`, since it's the same formula
- Technically, `out_channels` arg is not required, but this solution would require it

**Comment by xiurobert** [comment] 2023-04-20 06:42
> @albanD I think this was a creative solution reusing basic tools, I like it!
> 
> I would like to get your thoughts on two aspects of the `torch.nn.Conv2d(in_chans, out_chans, kernel_size, device="meta")` solution I think are missing:
> 
>     * Support of both `Conv2d` and `Conv3d`, since it's the same formula
> 
>     * Technically, `out_channels` arg is not required, but this solution would require it

Pretty sure it already works in Conv3d since the formula is generalized.

**Comment by jamesbraza** [comment] 2023-04-20 07:42
I agree the formula is generalized, but the posed solution is not generalized across `Conv2d` and `Conv3d`:

```python
import torch

a = torch.rand(2, 3, 10, 10, device="meta")
torch.nn.Conv2d(3, 5, 2, device="meta")(a).size()  # Works
torch.nn.Conv3d(3, 5, 2, device="meta")(a).size()  # RuntimeError: Invalid channel dimensions
```

To see a possibly different solution, check Keras' [`utils.conv_utils.conv_output_length`](https://github.com/keras-team/keras/blob/v2.11.0/keras/utils/conv_utils.py#L118) or https://github.com/pytorch/pytorch/issues/97118#issue-1631165527, the `conv_conversion` there doesn't depend on being 2D or 3D.
