### ISSUE TITLE
How to add custom CUDA function as torchScript node?

### ISSUE THREAD

**Issue by Sun-Knight-Soral** [pytorch/pytorch#47572] opened 2020-11-08 10:25 UTC
Hi, i want to add my CUDA function to torchScript as a Node, but i don't want to use torchScript extention op as i can't let other people to load so file, is there any way? Thankyou very much!

cc @gmagogsfm

**Comment by zasdfgbnm** [comment] 2020-11-08 17:15
duplicate of https://github.com/pytorch/pytorch/issues/47574

**Closed by zasdfgbnm** 2020-11-08 17:15 UTC
Labels: oncall: jit
