### ISSUE TITLE
Sparse constructors don't work with cuda:1 values and non-CUDA indices

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#54075] opened 2021-03-16 18:10 UTC
```
>>> import torch
>>> v = torch.empty(2, 0).cuda()
>>> torch.sparse_coo_tensor(([0, 1],), v, (4, 0))
tensor(indices=tensor([[0, 1]]),
       values=tensor([], size=(2, 0)),
       device='cuda:0', size=(4, 0), nnz=2, layout=torch.sparse_coo)
>>> v = torch.empty(2, 0).cuda(1)
>>> torch.sparse_coo_tensor(([0, 1],), v, (4, 0))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: device of indices (0) must match device of values (1)
```

Pretty sure #54034 is gonna fix this.

cc @aocsa @nikitaved @pearu @mruberry @gchanan

**Comment by ezyang** [comment] 2021-03-16 18:34
cc @gchanan

**Comment by IvanYashchuk** [comment] 2021-12-13 08:04
Code from the issue description doesn't raise an error on master, so probably the problem is fixed now.

**Closed by IvanYashchuk** 2021-12-13 08:04 UTC
Labels: module: sparse, triaged, module: tensor creation
