### ISSUE TITLE
memory leaky when using torch.onnx.export()

### ISSUE THREAD

**Issue by WilliamZhaoz** [pytorch/pytorch#28414] opened 2019-10-22 07:35 UTC
when I use:
torch.onnx.export()
to convert my pytorch model to onnx model,
I can monitor the memory is used up by the converting process.
and then the process is killed.
no any other logs, just killed.

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by fmassa** [comment] 2019-10-23 11:34
Can you write a minimal example reproducing the problem?

**Comment by zhoudoufu** [comment] 2020-03-03 04:48
I had same error when I export onnx model on a small vm on aws, For my case the RAM did run out. 
It might worse a try to make smaller batch / maximum size per batch for the model.

**Comment by garymm** [comment] 2021-12-23 01:05
Duplicate of #61263

**Closed by garymm** 2021-12-23 01:05 UTC
Labels: module: onnx, module: memory usage, triaged
