### ISSUE TITLE
torch.save throws an error when the path uses mixed separators on Windows

### ISSUE THREAD

**Issue by Nerogar** [pytorch/pytorch#105488] opened 2023-07-18 18:41 UTC
### 🐛 Describe the bug

Using some combinations of \ and / as the path separator throws an exception. Windows prefers \ as the path separator, but also accepts /. torch.save throws an exception for paths that should be valid windows paths.

Reproducible using the following example
``` python
import os
import torch

data = [{'1': 1}]

torch.save(data, "H:/a\\a.ckpt")
```

replacing the path can lead to a few different results:

`torch.save(data, "H:\\a\\a.ckpt")` -> works
`torch.save(data, "H:/a/a.ckpt")` -> works
`torch.save(data, "H:/a\\a.ckpt")` -> Throws "Parent directory H: does not exist."
`torch.save(data, "H:\\a/a.ckpt")` -> works

But now it gets really strange:
`torch.save(data, "H:/a.ckpt")` -> Throws "Parent directory H: does not exist.". The file is created, but remains empty
`torch.save(data, "H:\\a.ckpt")` -> Throws "Parent directory H: does not exist.". The file is created, but remains empty

Stack trace
```
...
  File "H:\stable-diffusion\one-trainer\scripts\debug.py", line 17, in main
    torch.save(data, "H:\\a.ckpt")
  File "H:\stable-diffusion\one-trainer\venv\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "H:\stable-diffusion\one-trainer\venv\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "H:\stable-diffusion\one-trainer\venv\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory H: does not exist.
```

### Versions

PyTorch version: 2.0.1+cu118
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19045-SP0
Is CUDA available: True
CUDA runtime version: 11.8.89
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA RTX A5000
Nvidia driver version: 535.98
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3600
DeviceID=CPU0
Family=205
L2CacheSize=1536
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3600
Name=Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] pytorch-lightning==2.0.3
[pip3] torch==2.0.1+cu118
[pip3] torchmetrics==1.0.1
[pip3] torchvision==0.15.2+cu118
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by iremyux** [comment] 2023-07-20 10:05
Hi @Nerogar ,

I see that you've commented on [Training Issue and Requirements issue](https://github.com/Nerogar/OneTrainer/issues/13) about both of these issues being fixed. Can you please elaborate? If I understand correctly you are no longer having the problem with `torch.save` . In that case, can this issue be closed?

**Comment by iremyux** [comment] 2023-07-21 08:19
@Nerogar 
Okay I see. I am also able to reproduce this issue. I will be investigating this, thanks for reporting.

**Comment by Nerogar** [comment] 2023-07-25 17:02
@iremyux Sure.

With this script, the file a.txt is written successfully, including the content. The file b.ckpt is created, but without content. I get the same "Parent directory H: does not exist." error. Replacing \ with / doesn't change the result. So, to answer your question: yes, the user does have permissions to write directly to the H drive.
```python
import torch

data = [{"1": 1}]

with open("H:\\a.txt", "w") as f:
    f.write("test")

torch.save(data, "H:\\b.ckpt")
```

>It is encouraged to use forward slashes ( "/" ) with relative-paths and backward slashes ( "\\" ) with absolute-paths

Is this a Pytorch limitation? Or did you see this mentioned somewhere else? I never heard of this before. But as you can see, it doesn't matter if I use / or \\, both throw the same error for absolute paths without sub directories.

Here are a few more examples, maybe this helps with debugging:

---
1:
```python
import torch

data = [{"1": 1}]

with open("H:/a\\a.txt", "w") as f:
    f.write("test")

torch.save(data, "H:/a\\b.ckpt")
```
a.txt is saved successfully, b.ckpt is created, but empty

---
2:
```python
import torch

data = [{"1": 1}]

with open("H:/a/a.txt", "w") as f:
    f.write("test")

torch.save(data, "H:/a/b.ckpt")
```
both files are saved successfully

---
3:
```python
import torch

data = [{"1": 1}]

with open("H:/a/a\\a.txt", "w") as f:
    f.write("test")

torch.save(data, "H:/a/a\\b.ckpt")
```
both files are saved successfully

---
4:
```python
import torch

data = [{"1": 1}]

with open("H:\\a\\a.txt", "w") as f:
    f.write("test")

torch.save(data, "H:\\a\\b.ckpt")
```
both files are saved successfully

**Comment by iremyux** [comment] 2023-11-13 13:54
Hi @Nerogar, sorry for the delayed response. 

I will be investigating the issue but in the mean time I would like to post some suggestions. In your provided examples, it looks like either of the slashes works, but using a combination of them in the file path leads to errors. This is likely because the mixed separators are causing confusion in the path resolution process.

It's recommended to consistently use one type of path separator throughout your code. Since you are working on Windows, using backslashes as the path separator is a common practice. This should help avoid any unexpected issues related to path handling.

**Comment by alinpahontu2912** [comment] 2024-01-15 15:04
Hello @Nerogar, I have one update regarding this issue. It seems there was also another similar report with this issue happening when using libtorch as well (this [one](https://github.com/pytorch/pytorch/issues/111121)). It seems like there was a regression in Pytorch 1.6 that changed torch.save file formatting, according to here: https://github.com/pytorch/pytorch/blob/75818adcf74e8139ac98c8e30e93283ac1317120/torch/serialization.py#L587-L611 This being said, I tried using the extra argument **_use_new_zipfile_serialization=False_** as recommended in the docs and I had no issue in saving the file to my main directory, without an extra folder. Will continue to investigate this and check back, but I hope this helps for the moment.

**Comment by alinpahontu2912** [comment] 2024-02-05 10:40
Closing this because of no other question/reply. Feel free to reopen it if needed or open other issue for feature requests or if any bug is encountered.

**Comment by Nerogar** [comment] 2024-02-05 16:49
@alinpahontu2912 

Did I miss something? As far as I can see, you suggested a workaround. But the underlying bug still exists.
I just tested this with the most recent PyTorch version (2.2.0+cu118) and I still get the same error.

If I pass _use_new_zipfile_serialization=True to torch.save, the file is successfully written. But (according to the documentation) this also changes the file format.

**Comment by FurkanGozukara** [comment] 2024-04-14 21:24
please fix this error. currently i am having this problem and can't save Diffusers backup files on Windows

**Comment by FurkanGozukara** [comment] 2024-04-15 12:09
> @FurkanGozukara , thanks for the comment.
> 
> Could you please provide us more details for your saving scenario?
> 
> * What is the `path` you're providing for save function and what is the error message?
>   
>   * A follow-up question: is it happening only for saving files on drive (like `C:\file` or with a parent directory `C:\somefolder\file`)
> * Which version of PyTorch you're using?
> * What is your Python version and what is your OS platform (Window 10 / 11?) ?
> 
> Also, did you try to pass `_use_new_zipfile_serialization=False` flag?
> 
> We're investigating the problem for further solution.

Here the error I am getting - disk has over 600 GB - saving safetensors working

The error looks like related to forward and backward slashes ```\``` ```/``` 

```
caching resolutions:   0%|                                                                                        | 0/30 [00:00<?, ?it/s]
Creating Backup F:/onetrainer_workspace_diffusers_test\backup\2024-04-14_20-45-11-backup-870-29-0                  | 0/30 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "F:\OneTrainer\modules\trainer\GenericTrainer.py", line 330, in backup
    self.model_saver.save(
  File "F:\OneTrainer\modules\modelSaver\StableDiffusionXLModelSaver.py", line 139, in save
    self.__save_internal(model, output_model_destination)
  File "F:\OneTrainer\modules\modelSaver\StableDiffusionXLModelSaver.py", line 101, in __save_internal
    torch.save(model.optimizer.state_dict(), os.path.join(destination, "optimizer", "optimizer.pt"))
  File "F:\OneTrainer\venv\lib\site-packages\torch\serialization.py", line 628, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "F:\OneTrainer\venv\lib\site-packages\torch\serialization.py", line 502, in _open_zipfile_writer
    return container(name_or_buffer)
  File "F:\OneTrainer\venv\lib\site-packages\torch\serialization.py", line 473, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory F: does not exist.
Could not save backup. Check your disk space!
```

**Comment by alinpahontu2912** [comment] 2024-05-07 13:50
@FurkanGozukara @Nerogar  hello, we tested with the latest nightly version and the bug is now fixed, feel free to reopen if needed and don't hesitate to open new issues for other problems or requests you may have.

**Closed by alinpahontu2912** 2024-05-07 13:50 UTC
Labels: module: windows, triaged

**Comment by FurkanGozukara** [comment] 2024-05-07 14:02
> @FurkanGozukara @Nerogar hello, we tested with the latest nightly version and the bug is now fixed, feel free to reopen if needed and don't hesitate to open new issues for other problems or requests you may have.

thank you so much

**Comment by Nerogar** [comment] 2024-05-07 17:31
I can confirm that all the test cases are working when using the latest nightly build. Thanks everyone.
