### ISSUE TITLE
[ONNX] scatter_add result is wrong in ONNX model

### ISSUE THREAD

**Issue by zhang0557kui** [pytorch/pytorch#79005] opened 2022-06-07 09:09 UTC
### 🐛 Describe the bug

scatter_add result is wrong in ONNX model

### Versions

scatter_add result is wrong in ONNX model

cc @mikaylagawarecki

**Comment by samdow** [comment] 2022-06-07 13:31
Hi! Could you provide a repro for this? Thanks!

**Comment by BowenBao** [comment] 2022-06-07 18:52
Duplicate of #32960, closing.

`scatter_add` will be properly supported in opset 16 export soon.

**Closed by BowenBao** 2022-06-07 18:52 UTC
Labels: module: onnx, triaged, module: scatter & gather ops

**Comment by zhang0557kui** [comment] 2022-07-07 08:29
scatter_add result is still wrong in ONNX format model by onnxruntime's  inference
