### ISSUE TITLE
Aten looking for function cusparseDcsrmm2 in cuda 11.0.1 header but this is no more

### ISSUE THREAD

**Issue by mshaikh786** [pytorch/pytorch#40593] opened 2020-06-25 22:50 UTC
## 🐛 Bug

I am compiling pytorch/1.5.0 with CUDA 11.0.1 and on trying to compile a target torch_cuda_generated_SparseCUDABlas.cu.o the  error occurs complaining 

pytorch-1.5.0/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu(112): error: identifier "cusparseScsrmm2" is undefined
The cuda headers are on compile line so that is not the issue.
I searched that cuspares.h and cusparse_v2.h, both CUDA toolkit 11's in headers, don't exist anymore but do in CUDA 10.2.89 and below.

cc @malfet @ngimel

**Comment by xwang233** [comment] 2020-06-26 00:39
Do you have cublas 11 library installed?

**Comment by xwang233** [comment] 2020-06-26 00:56
Ok, I see where the problem is. `cusparseScsrmm2` is deprecated in CUDA 11. 

In 1.5 release, the CUDA 11 related cusparse code change hasn't updated yet. It is already merged in the current master. See https://github.com/pytorch/pytorch/blob/master/aten/src/ATen/native/sparse/cuda/SparseCUDABlas.cu#L84

So, you may want to compile pytorch from master.

**Closed** 2020-07-07 07:33 UTC
Labels: module: build, module: cuda, triaged

**Comment by GrimReaper420** [comment] 2020-08-01 12:30
I'm getting the same exact issue on windows and I am compiling from master.  The commit above by xwang233 states "CUDA release >= 10.2 and not windows", is it safe to remove the `!defined(_MSC_VER)` from the if statement?
