### ISSUE TITLE
torch.matmul output differs

### ISSUE THREAD

**Issue by david-j-sch** [pytorch/pytorch#57347] opened 2021-04-30 09:36 UTC
## 🐛 Bug

In one of my scripts, I noticed that the output of torch.matmul differs depending on whether the variables are located CPU or CUDA.

The bug appears only using cuda 11.1, with cuda 10.2 it's fine.

## To Reproduce

To reproduce the error, just run the following example:

```
import numpy as np
import torch

m1 = np.array([[1,0],[0,1]], dtype=np.float32)
m2 = np.array([[1,2],[3,4]], dtype=np.float32)

print('result np matmul:')
print(np.matmul(m1,m2))

m1_t = torch.from_numpy(m1)
m2_t = torch.from_numpy(m2)

print('result torch matmul cpu:')
print(torch.matmul(m1_t,m2_t))

m1_t = m1_t.cuda()
m2_t = m2_t.cuda()

print('m1_t is cuda:', m1_t.is_cuda)
print('m2_t is cuda:', m2_t.is_cuda)

print('result torch matmul gpu:')
print(torch.matmul(m1_t,m2_t))
```

## Expected behavior
In my case the output of CUDA matmul contains only zeros:

```
result np matmul:
[[1. 2.]
 [3. 4.]]
result torch matmul cpu:
tensor([[1., 2.],
        [3., 4.]])
m1_t is cuda: True
m2_t is cuda: True
result torch matmul gpu:
tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

```

## Environment

```
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: GeForce GTX 1080
Nvidia driver version: 460.73.01
cuDNN version: Probably one of the following:
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.1.1
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.1+cu111
[pip3] torchaudio==0.8.1
[pip3] torchvision==0.9.1+cu111
```

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @csarofeen @ptrblck @xwang233 @ngimel

**Comment by imaginary-person** [comment] 2021-04-30 15:09
Probably a duplicate of #56747.

**Comment by ngimel** [comment] 2021-07-21 01:05
Closing as duplicate

**Closed by ngimel** 2021-07-21 01:05 UTC
Labels: high priority, module: cublas, module: cuda, triaged
