### ISSUE TITLE
*** stack smashing detected *** after adding libtorch in CMake

### ISSUE THREAD

**Issue by trakaros** [pytorch/pytorch#22565] opened 2019-07-06 12:47 UTC
## To Reproduce

* I can successfully load the model file(model.pt).
* However,when the code reaches the command "image_window win;", a "stack smashing detected" error is thrown.
* I have also checked the size of the model file.It is 350KB.Is it too big and it causes overflow in stack? 
* The strange things is that the same code without any libtorch involvement is working fine.The problem was created when I inserted the libtorch code.
* My code is the following:

```
int main()
{
    try
    {
    	torch::jit::script::Module module = torch::jit::load("../model.pt");
        torch::NoGradGuard no_grad;
        cv::VideoCapture cap(0);
        if (!cap.isOpened())
        {
            cerr << "Unable to connect to camera" << endl;
            return 1;
        }
        image_window win;
        //Here is the error.After the " image_window win;" command, 
        //the *** stack smashing detected *** error is thrown.
        ...(rest of code..)...        
```
* I compiled the code with the following CMakelists.txt:
```
cmake_minimum_required(VERSION 2.8.12)
project(examples)
add_executable(webcam_face_pose_ex Regressor.cpp webcam_face_pose_ex.cpp Graphics.cpp)
set(CMAKE_PREFIX_PATH "libtorch/share/cmake/Torch")
add_subdirectory(../dlib-19.13/dlib/ dlib_build)

find_package(OpenCV QUIET)
find_package(HDF5 REQUIRED COMPONENTS C CXX)
find_package(SDL2 REQUIRED)
find_package(Torch REQUIRED)

include_directories(${DLIB_INCLUDE_DIRECTORY})
include_directories(${OpenCV_INCLUDE_DIRS})
include_directories(${HDF5_INCLUDE_DIRS})
include_directories(${SDL2_INCLUDE_DIRS})

target_link_libraries(webcam_face_pose_ex ${DLIB_LIBRARIES} dlib dlib::dlib)
target_link_libraries(webcam_face_pose_ex ${OpenCV_LIBS} dlib::dlib)
target_link_libraries(webcam_face_pose_ex ${HDF5_CXX_LIBRARIES} ${HDF5_LIBRARIES} dlib::dlib )
target_link_libraries(webcam_face_pose_ex ${SDL2_LIBRARIES} dlib::dlib)
target_link_libraries(webcam_face_pose_ex ${TORCH_LIBRARIES} dlib::dlib)

set_property(TARGET webcam_face_pose_ex PROPERTY CXX_STANDARD 11)


```
* I also tried to dynamically allocate the "torch::jit::script::Module module "
object in order to avoid overflow issues, using the command:
```
torch::jit::script::Module module = new torch::jit::load("../model.pt");
```
* However, it failed with error: "error: expected type-specifier"

## Environment
* PyTorch version: 1.1.0
* Is debug build: No
* CUDA used to build PyTorch: 9.0.176

* OS: Ubuntu 16.04.6 LTS
* GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
* CMake version: version 3.5.1

* Python version: 3.6
* Is CUDA available: No
* CUDA runtime version: 7.5.17
* GPU models and configuration: Could not collect
* Nvidia driver version: Could not collect
* cuDNN version: /usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7

* [pip3] numpy==1.15.4
* [pip3] numpydoc==0.8.0
* [pip3] torch==1.1.0
* [pip3] torchsummary==1.5.1
* [pip3] torchvision==0.3.0
* [conda] blas                      1.0                         mkl  
* [conda] mkl                       2019.1                      144  
* [conda] mkl-service               1.1.2            py36he904b0f_5  
* [conda] mkl_fft                   1.0.10           py36ha843d7b_0  
* [conda] mkl_random                1.0.2            py36hd81dba3_0  
* [conda] torch                     1.1.0                     <pip>
* [conda] torchsummary              1.5.1                     <pip>
* [conda] torchvision               0.3.0                     <pip>

**Comment by xuhdev** [comment] 2019-07-06 20:58
If you remove the first two lines related to `torch`, would your program still report such an error on the `image_window` line?

**Comment by trakaros** [comment] 2019-07-06 23:38
* Yes,the problem is still the same when I put in comments that 2 commands related to ```torch```(so,there isn't any problem with the model file).The problem is caused when I put in CMake the commands related to ``` Libtorch```.However,I can't figure out how these libraries affect the stack and smash it.
* Also, if I put a ```return 0;``` statement before the ```image_window``` line, the programm terminates successfully.However,if I put the ```return 0;``` statement after that command,it smashes the stack.
* I mention that when I compile the example code from the Pytorch website(https://pytorch.org/tutorials/advanced/cpp_export.html#a-minimal-c-application.I), it compiles/runs without any problem.

**Comment by xuhdev** [comment] 2019-07-08 00:21
If you add `return 0;` after the `image_window` line, comment out the two torch related lines, and remove libtorch from your linkage, and make sure you have a DEBUG build: What does `valgrind your_program` say?

**Comment by ezyang** [comment] 2019-07-08 17:08
This sounds serious. If someone else could try reproducing the error that would be very helpful.

**Comment by trakaros** [comment] 2019-07-08 19:48
* I run the ```valgrind``` command you mentioned above.It  detects 1 error,however I can't get enough information of how this could be related to the ```stack smashing```. 
* The full output is here: https://github.com/trakaros/MPIIGaze/blob/hpc-code/valgrind_out.txt

**Comment by xuhdev** [comment] 2019-07-08 22:52
It looks like there might be an issue with your dlib installation -- stack smashing can be caused by some unsafe code, but is only triggered under some certain circumstances due to the arbitrariness of the unsafe code.

I see valgrind reports that there is an issue with dlib, and you have a custom dlib build. Could you try with a stable dlib installation and see whether valgrind still reports this issue?

**Comment by trakaros** [comment] 2019-07-08 23:23
I'll check the stable build and I'll update the issue after that.Thank you.

**Comment by soumith** [comment] 2019-07-09 06:57
@trakaros if you are using pytorch binaries, then it might be our fault, where pytorch and dlib use different CXX ABIs. (In such a case, stack smashing can occur).
For more context, see https://github.com/pytorch/pytorch/issues/22447
Compiling pytorch from source might fix your issue until we fix the problem.

**Comment by trakaros** [comment] 2019-07-09 22:42
* I figured out the solution.I am not quite sure,but I think that it may not be related to ```Libtorch```
* I commented out every code line,where I use ```win``` variable,which was defined in ```image_window win;```.Everything worked fine.
* So,this specific command may have problems when some external libraries are linked(Libtorch,etc.).
* I wrote an issue on DLIB in order to get an answer on that:https://github.com/davisking/dlib/issues/1821

**Comment by nairbv** [comment] 2019-12-03 16:22
@trakaros Are you still suspecting the issue is with dlib? If we don't have something actionable to fix here then I'll close this ticket.

**Closed** 2019-12-03 18:12 UTC
Labels: high priority, module: build, needs reproduction, topic: crash, triaged
