### ISSUE TITLE
PyTorch 1.6, Probably issues ninja version call is incorrect in one place

### ISSUE THREAD

**Issue by apiszcz** [pytorch/pytorch#45820] opened 2020-10-04 14:08 UTC
ninja -v not support by recent versions of ninja

python\lib\site-packages\torch\utils\cpp_extension.py
LINE 1472
change '-v' to '--version'

Line 1289 already uses --version, the Visual Studio 2017 and 2019 apparently use the --version parameter.

VS2017
>ninja -v
ninja: error: loading 'build.ninja': The system cannot find the file specified.

>ninja --version
1.8.2

cc @malfet @seemethere @walterddr @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by VitalyFedyunin** [comment] 2020-10-05 20:55
We will gladly accept PR to fix it

**Comment by peterjc123** [comment] 2020-10-06 03:49
This is not a bug. Here `-v` refers to `--verbose`, not `--version`.  Could you please show me the full log? What are you trying to do?

**Comment by kit1980** [comment] 2022-10-04 22:41
Closing as PyTorch 1.6 is long obsolete.

**Closed** 2022-10-26 14:15 UTC
Labels: module: build, module: windows, triaged
