### ISSUE TITLE
Update README's gif to reflect Variable changes

### ISSUE THREAD

**Issue by Iwontbecreative** [pytorch/pytorch#7025] opened 2018-04-27 03:55 UTC
The README dynamic's graph gif ( e.g [dynamic graph](https://github.com/pytorch/pytorch/blob/master/docs/source/_static/img/dynamic_graph.gif) ) is still in 0.3 mode and has Variable all over. Considering the recent release, would make sense to update it.

**Comment by SsnL** [comment] 2018-04-27 03:56
Duplicate of #6180 . I'll do it.

**Closed by SsnL** 2018-04-27 03:56 UTC
