### ISSUE TITLE
Cannot install Pytorch?

### ISSUE THREAD

**Issue by GitHubCrazy1** [pytorch/pytorch#31686] opened 2019-12-29 07:08 UTC
## 🐛 Bug

Hello, I'm  trying to install Pytorch and it looks like neither the PIP nor the Conda package works.

Using the Anaconda Console, I ran as Administrator and tried the following:

```
(base) C:\WINDOWS\system32>conda install pytorch torchvision cudatoolkit=10.1 -c pytorch
Collecting package metadata (current_repodata.json): failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/pytorch/win-64/current_repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', port=443): Max retries exceeded with url: /pytorch/win-64/current_repodata.json (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000001DC15135048>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.15)'))"))
```

Then again with PIP:

```
(base) C:\WINDOWS\system32>pip3 install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html
Looking in links: https://download.pytorch.org/whl/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch===1.3.1 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.3.1
```

I am really not sure why this error message would exist - as far as I am aware, these are the latest versions of Torch and Pytorch. I've put this as a bug because as far as I can tell, these versions do exist. 

Here is my Python version:

```
(base) C:\WINDOWS\system32>python
Python 3.7.4 (default, Aug  9 2019, 18:34:13) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
```

I'm not sure if this is a fairly simple mistake or not (sorry if it is, I'm new to this and trying to learn). 

I tried turning off my firewall (I use Comodo),  but got the same result.

**Comment by peterjc123** [comment] 2019-12-29 09:36
Please try out the tsinghua mirror for anaconda if you are a user in China. https://mirror.tuna.tsinghua.edu.cn/help/anaconda/
Since the error you reported cannot be reproduced at our side, I'm going to close it. Please feel free to reopen it if you disagree.

**Closed by peterjc123** 2019-12-29 09:36 UTC

**Comment by GitHubCrazy1** [comment] 2019-12-29 21:03
Hello Peter, 

Thanks for the reply. I am writing for Canada, not China. 

That said, I tried and got this:

```
C:\WINDOWS\system32>pip3 install torch===1.3.1 torchvision===0.4.2 -f https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
Looking in links: https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud
ERROR: Could not find a version that satisfies the requirement torch===1.3.1 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch===1.3.1
```

I don't know if it makes a difference, but I installed the latest version of CUDA, which is now 10.2

**Comment by peterjc123** [comment] 2019-12-30 03:15
@GitHubCrazy1 The system CUDA version doesn't matter. Would you please try `python -m pip install torch===1.3.1 torchvision===0.4.2 -f https://download.pytorch.org/whl/torch_stable.html`

**Comment by GitHubCrazy1** [comment] 2019-12-30 23:52
Looks like a success. Thanks a lot peterjc123

**Comment by EphraimBane** [comment] 2020-01-14 23:37
I am actually having these problems as well, and these solutions are not working for me. Any suggestions? (Also, sorry for necropost.)

**Comment by peterjc123** [comment] 2020-01-14 23:57
> I am actually having these problems as well, and these solutions are not working for me. Any suggestions? (Also, sorry for necropost.)

Would you please open a new issue with all the detailed information?
