### ISSUE TITLE
Conda installation impossible (Linux, pytorch-2.1.1, cuda-12.1)

### ISSUE THREAD

**Issue by Youjin1985** [pytorch/pytorch#115498] opened 2023-12-10 07:39 UTC
### 🐛 Describe the bug

command
conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia
in fresh environment leads to 
```
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'bin/cjpeg'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'bin/djpeg'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'bin/jpegtran'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'bin/rdjpgcom'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'bin/wrjpgcom'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'include/jconfig.h'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'include/jerror.h'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'include/jmorecfg.h'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'include/jpeglib.h'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'lib/libjpeg.a'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'lib/libjpeg.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'lib/pkgconfig/libjpeg.pc'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'share/man/man1/cjpeg.1'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'share/man/man1/djpeg.1'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'share/man/man1/jpegtran.1'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'share/man/man1/rdjpgcom.1'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::jpeg-9e-h5eee18b_1, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
  path: 'share/man/man1/wrjpgcom.1'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::intel-openmp-2023.1.0-hdb19cb5_46306, defaults/linux-64::llvm-openmp-14.0.6-h9e868ea_0
  path: 'lib/libiomp5.so'


ClobberError: This transaction has incompatible packages due to a shared path.
  packages: defaults/linux-64::intel-openmp-2023.1.0-hdb19cb5_46306, defaults/linux-64::llvm-openmp-14.0.6-h9e868ea_0
  path: 'lib/libomptarget.so'
```

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.6.1810 (Core)  (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.9.18 (main, Sep 11 2023, 13:41:44)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090

Nvidia driver version: 525.85.12
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                32
On-line CPU(s) list:   0-31
Thread(s) per core:    1
Core(s) per socket:    16
座：                 2
NUMA 节点：         2
厂商 ID：           GenuineIntel
CPU 系列：          6
型号：              85
型号名称：        Intel(R) Xeon(R) Silver 4216 CPU @ 2.10GHz
步进：              7
CPU MHz：             2101.000
CPU max MHz:           2101.0000
CPU min MHz:           800.0000
BogoMIPS：            4200.00
虚拟化：           VT-x
L1d 缓存：          32K
L1i 缓存：          32K
L2 缓存：           1024K
L3 缓存：           22528K
NUMA 节点0 CPU：    0-15
NUMA 节点1 CPU：    16-31
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch epb cat_l3 cdp_l3 intel_ppin intel_pt ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 erms invpcid rtm cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts pku ospke avx512_vnni spec_ctrl intel_stibp flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] No relevant packages
[conda] No relevant packages

cc @seemethere @malfet @osalpekar @atalman

**Comment by tringwald** [comment] 2023-12-10 14:18
Can't reproduce this with a fresh conda env. Can you try again after running `conda clean --all` (warning: might break some non-standard conda setups)?.

**Comment by malfet** [comment] 2023-12-10 22:32
I can't reproduce it either, as jpeg=9e and `libjpeg-turbo` do not conflict with regular conda. I wonder if conflict comes from conda-forge

**Comment by malfet** [comment] 2024-01-20 07:51
No reply from an author in over a month, closing. Please do not hesitate to open a new issue if you encounter another problem with PyTorch.

**Closed by malfet** 2024-01-20 07:51 UTC
Labels: needs reproduction, module: binaries, triaged

**Comment by jacobwilliams** [comment] 2024-06-05 13:49
Just FYI: I have the same problem in another project (not PyTorch). It is indeed using the `conda-forge` channel:

```
ClobberError: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/linux-64::jpeg-9e-h166bdaf_2, conda-forge/linux-64::libjpeg-turbo-2.1.4-h166bdaf_0
  path: 'bin/cjpeg'

...etc...
```

**Comment by msh855** [comment] 2024-09-11 15:20
At the end, what's the solution? The `conda clear -all` did not work.

**Comment by xuelianl** [comment] 2025-05-06 09:12
As for me, before `ClobberError` reported, it reported a `SafetyError` earlier when I run the command `conda install pytorch==2.4.1 torchvision==0.19.1 torchaudio==2.4.1 pytorch-cuda=12.4 -c pytorch -c nvidia`.

> SafetyError: The package for pytorch located at /home/lixuelian/opt/miniconda/pkgs/pytorch-2.4.1-py3.9_cuda12.4_cudnn9.1.0_0
> appears to be corrupted. The path 'lib/python3.9/site-packages/torch/distributed/launch.py'
> has an incorrect size.
>   reported size: 7610 bytes
>   actual size: 7634 bytes
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'bin/cjpeg'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'bin/djpeg'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'bin/jpegtran'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'bin/rdjpgcom'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'bin/wrjpgcom'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'include/jconfig.h'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'include/jerror.h'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'include/jmorecfg.h'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'include/jpeglib.h'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'lib/libjpeg.a'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'lib/libjpeg.so'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'lib/pkgconfig/libjpeg.pc'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'share/man/man1/cjpeg.1'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'share/man/man1/djpeg.1'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'share/man/man1/jpegtran.1'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'share/man/man1/rdjpgcom.1'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::jpeg-9e-h5eee18b_3, pytorch/linux-64::libjpeg-turbo-2.0.0-h9bf148f_0
>   path: 'share/man/man1/wrjpgcom.1'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::intel-openmp-2023.1.0-hdb19cb5_46306, defaults/linux-64::llvm-openmp-14.0.6-h9e868ea_0
>   path: 'lib/libiomp5.so'
> 
> 
> ClobberError: This transaction has incompatible packages due to a shared path.
>   packages: defaults/linux-64::intel-openmp-2023.1.0-hdb19cb5_46306, defaults/linux-64::llvm-openmp-14.0.6-h9e868ea_0
>   path: 'lib/libomptarget.so'

The command `conda clean --packages --tarballs` can solve this problem for me.
