### ISSUE TITLE
3D Resnet is not scriptable

### ISSUE THREAD

**Issue by jiafatom** [pytorch/pytorch#61189] opened 2021-07-02 22:39 UTC
## 🚀 Feature
3D Resnet can be found [here](https://pytorch.org/hub/facebookresearch_pytorchvideo_resnet/). It is not scriptable.

## Motivation

We tried to convert this 3D Resnet to ONNX model, but scripting has some issues.

## Pitch

Run the following script on the model, and it fails:
```python
import torch
# Choose the `slow_r50` model 
model = torch.hub.load('facebookresearch/pytorchvideo', 'slow_r50', pretrained=True)
model = torch.jit.script(model)
```

This model has **three issues for scripting failure**, listed below:
(1) **'Conv3d.stride' is not a valid constant.**
See [here](https://github.com/facebookresearch/pytorchvideo/blob/7386650007ea49728af285ac61ab6b1c4d232884/pytorchvideo/models/resnet.py#L413-L427), the stride for Conv is `batch1_conv_stride`, but it is not a valid constant.
When scripting, the errors are:
```python
TypeError: 
'numpy.int64' object in attribute 'Conv3d.stride' is not a valid constant.
Valid constants are:
1. a nn.ModuleList
2. a value of type {bool, float, int, str, NoneType, torch.device, torch.layout, torch.dtype}
3. a list or tuple of (2)
```
To reproduce this, see this simple example:
```python
class ConvTest(torch.nn.Module):
    def __init__(self):
        super(ConvTest, self).__init__()
        conv_a_stride = (2, 1, 1)
        conv_b_stride = (1, 2, 2)
        stride = tuple(map(np.prod, zip(conv_a_stride, conv_b_stride)))
        self.conv = torch.nn.Conv3d(3, 2, (3, 5, 2), stride=stride, padding=(3, 2, 0), bias=False)

    def forward(self, x):
        return self.conv(x)

model = ConvTest()
model = torch.jit.script(model)
```
A similar issue that might be related [here](https://github.com/pytorch/pytorch/issues/43094).

(2) **function attribute is not scriptable.**
See [here](https://github.com/facebookresearch/pytorchvideo/blob/7386650007ea49728af285ac61ab6b1c4d232884/pytorchvideo/models/resnet.py#L1168), `branch_fusion` is an attribute of this module, but it is a Callable lambda function. Scripting gives the errors:
```python
Module 'ResBlock' has no attribute 'branch_fusion' (This function exists as an attribute on the Python module, but we failed to compile it to a TorchScript function. 
The error stack is reproduced here:
local variable 'idx' referenced before assignment:
  File "/home/david/.cache/torch/hub/facebookresearch_pytorchvideo_master/pytorchvideo/models/resnet.py", line 1179
            if self.branch1_norm is not None:
                shortcut = self.branch1_norm(shortcut)
            x = self.branch_fusion(shortcut, self.branch2(x))
                ~~~~~~~~~~~~~~~~~~ <--- HERE
            # x = shortcut + self.branch2(x)
        if self.activation is not None:
```
To reproduce this, see this simple example:
```python
import torch.nn as nn
from typing import Callable
def set_attributes(self, params: List[object] = None) -> None:
    if params:
        for k, v in params.items():
            if k != "self":
                setattr(self, k, v)

class IdentityModel(torch.nn.Module):
    def forward(self, a):
        return a

class ResBlock(nn.Module):
    def __init__(
        self,
        branch1_conv: nn.Module = None,
        branch2: nn.Module = None,
        branch_fusion: Callable = lambda x, y: x + y,
    ) -> nn.Module:
        super().__init__()
        set_attributes(self, locals())

    def forward(self, x) -> torch.Tensor:
        if self.branch1_conv is None:
            x = self.branch_fusion(x, self.branch2(x))
        return x

model = ResBlock(None, IdentityModel())
model = torch.jit.script(model)
```

(3) **ModuleList/Sequential indexing is only supported with integer literals.** For the loop variable, it won't work. 
See [here](https://github.com/facebookresearch/pytorchvideo/blob/7386650007ea49728af285ac61ab6b1c4d232884/pytorchvideo/models/net.py#L42-L43). `idx` is an iterable variable, not an integer literals like 0, 1, 2...So we have the errors:
```python
Expected integer literal for index. ModuleList/Sequential indexing is only supported with integer literals. Enumeration is supported, e.g. 'for index, v in enumerate(self): ...':
  File "/home/david/.cache/torch/hub/facebookresearch_pytorchvideo_master/pytorchvideo/models/net.py", line 43
    def forward(self, x: torch.Tensor) -> torch.Tensor:
        for idx in range(len(self.blocks)):
            x = self.blocks[idx](x)
                ~~~~~~~~~~~~~~~~ <--- HERE
        return x  
```
To reproduce this, see this simple example:
```python
import torch.nn as nn
class IdentityModel(torch.nn.Module):
    def forward(self, a):
        return a

class Net(nn.Module):
    def __init__(self, basic_model):
        super().__init__()
        self.blocks = nn.ModuleList([basic_model, basic_model, basic_model])

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        for idx in range(len(self.blocks)):
            x = self.blocks[idx](x)
model = Net(IdentityModel())
model = torch.jit.script(model)
```

Can we discuss to support those scenarios? Thank you!

cc @gmagogsfm

**Comment by jiafatom** [comment] 2021-07-02 23:20
cc @garymm @neginraoof @BowenBao

**Comment by garymm** [comment] 2021-07-06 18:57
1: seems like it could be worked around easily by changing the model. Do you agree?
Also seems like it'd be a useful feature to add to the JIT code. If we want to do that we should clarify with the owners of the code if they'd accept that contribution.

2: I don't really understand the issue. However the reproducing example code seems pretty hacky to me, which leads me to believe we should prefer to change the model rather than support this generally.

3: Seems like it'd be good to support this, but I'm not sure how difficult it would be.

**Comment by jiafatom** [comment] 2021-07-06 20:49
For 3, there is a related issue [here](https://github.com/pytorch/pytorch/issues/47496). Seems that the best way is to modify the model, not jit support.

**Comment by garymm** [comment] 2021-07-07 00:27
@jiafatom if we want to work on this please open an issue (or multiple) in ADO.

**Comment by tugsbayasgalan** [comment] 2021-07-12 21:52
For 2) 
Can you just create a function and use that in the code? Like 
`
def branch_fusion(self, x, y):
       return x + y

result = self.branch_fusion(x, y)
`

Closing this issue because 1 and 3 are already known issues. But feel free to open it again if you run into further issues.

**Closed by tugsbayasgalan** 2021-07-12 21:52 UTC
Labels: oncall: jit
