### ISSUE TITLE
403 while installing via pip

### ISSUE THREAD

**Issue by panki27** [pytorch/pytorch#81900] opened 2022-07-21 17:01 UTC
### 🐛 Describe the bug

I'm trying to install `pytorch` stable for Linux with CPU via pip, according to the [install guide](https://pytorch.org/get-started/locally/).

However, I get a 403 Cloudfront error. I initially thought this was related to #81760 but that ones already fixed.

```
$ python3 --version
Python 3.7.3
$ pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu                 [1]
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting torch
  Using cached https://download.pytorch.org/whl/cpu/torch-1.12.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
Collecting torchvision
  Using cached https://download.pytorch.org/whl/cpu/torchvision-0.13.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
Collecting torchaudio
  Using cached https://download.pytorch.org/whl/cpu/torchaudio-0.12.0%2Bcpu-cp37-cp37m-linux_x86_64.whl
Collecting typing-extensions (from torch)
Could not install packages due to an EnvironmentError: 403 Client Error: Forbidden for url: https://download.pytorch.org/whl/cpu/typing-extensions/
```

The 403 returned is somewhat strange:

```
HTTP/2 403 Forbidden
content-type: application/xml
date: Thu, 21 Jul 2022 16:58:57 GMT
server: AmazonS3
x-cache: Error from cloudfront
via: 1.1 9ce5bc08de451222a6a280b1273d60c6.cloudfront.net (CloudFront)
x-amz-cf-pop: DUS51-P1
x-amz-cf-id: <blanked>
X-Firefox-Spdy: h2
```

I am not behind a corporate firewall or any content filter.

### Versions

Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Debian GNU/Linux 10 (buster) (x86_64)
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.28

Python version: 3.7.3 (default, Jan 22 2021, 20:04:44)  [GCC 8.3.0] (64-bit runtime)
Python platform: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-10.12
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[conda] Could not collect

**Comment by kit1980** [comment] 2022-07-21 18:29
Closing this as a duplicate of https://github.com/pytorch/pytorch/issues/81760.
Maybe some time is needed for the fix to propagate to everyone.
Please re-open if still an issue after 24 hours.

**Comment by kit1980** [comment] 2022-07-21 18:30
Actually I'm re-opening it because this one is about pip, not conda.

**Comment by panki27** [comment] 2022-07-21 18:33
The conda install works for me, though. ¯\_(ツ)_/¯

**Comment by ptrblck** [comment] 2022-07-22 07:04
@panki27 Are you still hitting the issue?
I cannot reproduce it using your provided cmd:
```
pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu  
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu
Collecting torch
  Downloading https://download.pytorch.org/whl/cpu/torch-1.12.0%2Bcpu-cp38-cp38-linux_x86_64.whl (189.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 189.0/189.0 MB 8.1 MB/s eta 0:00:00
Collecting torchvision
  Downloading https://download.pytorch.org/whl/cpu/torchvision-0.13.0%2Bcpu-cp38-cp38-linux_x86_64.whl (13.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.5/13.5 MB 10.5 MB/s eta 0:00:00
Collecting torchaudio
  Downloading https://download.pytorch.org/whl/cpu/torchaudio-0.12.0%2Bcpu-cp38-cp38-linux_x86_64.whl (3.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.5/3.5 MB 6.6 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from torch) (4.2.0)
Requirement already satisfied: requests in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from torchvision) (2.28.1)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from torchvision) (9.2.0)
Requirement already satisfied: numpy in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from torchvision) (1.23.0)
Requirement already satisfied: idna<4,>=2.5 in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from requests->torchvision) (3.3)
Requirement already satisfied: charset-normalizer<3,>=2 in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from requests->torchvision) (2.1.0)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from requests->torchvision) (1.26.10)
Requirement already satisfied: certifi>=2017.4.17 in ./miniforge3/envs/tmp/lib/python3.8/site-packages (from requests->torchvision) (2022.6.15)
Installing collected packages: torch, torchvision, torchaudio
Successfully installed torch-1.12.0+cpu torchaudio-0.12.0+cpu torchvision-0.13.0+cpu
```

**Comment by seemethere** [comment] 2022-07-22 10:41
I think this might've been an extension of the Cloudflare issue that anaconda was experiencing.

Basically the resolver for pip will attempt to look through all available indices for a particular package with the "extra" one you specified being considered last.

In this case, pypi mirrors might've been down, which led pip to try to resolve the `typing-extensions` package from download.pytorch.org, which we do not provide. S3, for reasons, provides a 403 status instead of a 404 when trying to access an index that doesn't exist, thus leading to the error that you're seeing.

Going to close this one since I believe the cloudflare outage is resolved. Feel free to re-open if you can still reproduce.

**Closed by seemethere** 2022-07-22 10:41 UTC
Labels: releng, triaged

**Comment by wolfsprite** [comment] 2022-09-13 09:53
Having a 403 issue, seemingly due to a "/" being stripped from url during the process..

https://download.pytorch.org/whl/rocm5.1.1 = 403 AccessDenied
https://download.pytorch.org/whl/rocm5.1.1/ = works fine

---

With the following in environment.yaml:
```yaml
channels:
  - pytorch
  - defaults
  - https://download.pytorch.org/whl/rocm5.1.1/
  ```

This happens:
```sh
conda env update --file environment.yaml --prune
Collecting package metadata (repodata.json): failed

UnavailableInvalidChannel: The channel is not accessible or is invalid.
  channel name: whl/rocm5.1.1
  channel url: https://download.pytorch.org/whl/rocm5.1.1
  error code: 403
```

I'm noticing that the url does return a 403 error if the trailing slash is missing, and I'm not sure why it's getting omitted by conda/pip .. any help would be appreciated! Does not seem to be related to the Cloudflare outage resolved issue.
