### ISSUE TITLE
Chunkable Dataloader

### ISSUE THREAD

**Issue by sidazhang** [pytorch/pytorch#25033] opened 2019-08-22 17:14 UTC
## 🚀 Feature

Allow dataloader to be chunkable. Meaning, we can break each epoch into N chunks.

## Motivation

for users who have large training set, the pattern often looks like this

```
def train_model(self)
   while True:
           self.train()
           self.iterations += 1

           if self.iterations % VAL_ITER == 0:
                self.val()
```

This allows the user the evaluate many times per epoch. However, this means that there will be 2 active dataloader at a time.

A more ideal set up would be, to allow the user to specify the length of each chunk of dataloader. So the user can specify that, he/she wants to evaluate every N number of examples. So the train dataloader will exit before the val dataloader will begin. And when validation finishes, it will initialize a new train dataloader to train the next chunk

## Pitch

Currenlty, it means that there will be 2 active dataloader at a time. Which doubles the RAM usage.

Supporting this feature will half the memory usage for many users

**Comment by ifedan** [comment] 2019-08-22 18:33
I think this is a duplicate of https://github.com/pytorch/pytorch/pull/21232. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Closed by ifedan** 2019-08-22 18:33 UTC

**Comment by sidazhang** [comment] 2019-08-22 18:50
@ifedan But #21232 did not land. IT seems like that the PR was closed because the implementation was not pythonic
