### ISSUE TITLE
Tensor iteration changes behavior in 1.7 with no hint

### ISSUE THREAD

**Issue by parameciumvance** [pytorch/pytorch#47899] opened 2020-11-13 06:16 UTC
## 🐛 Bug
This slice of code
```
b = torch.rand(2,5,5,requires_grad=True)
for bb in b:
    bb[:,0].clamp_(min=0,max=0.3)
    bb[:,1].clamp_(min=0,max=0.3)
```
works in 1.6 but throws RuntimeError in 1.7. 

> Output 0 of UnbindBackward is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

Under researching I found the method Tensor.__ iter__ changes from
`iter(map(lambda i: self[i], range(self.size(0))))`[1.6.0] to `iter(self.unbind(0))`[1.7.0]

Also noticed that there is an issue(#36608), which is still open, about failure of inplace operation after torch.unbind.

**Comment by zanshuxun** [comment] 2020-11-14 05:06
I met this error, too. 
One solution is using indices:
```python
import torch
b = torch.rand(2, 5, 5, requires_grad=True)
# for bb in b:
for i in range(len(b)):
    bb=b[i]
    bb[:, 0].clamp_(min=0, max=0.3)
    bb[:, 1].clamp_(min=0, max=0.3)
```



Further, if you are interested in my problem, I simplify my code and reproduce the error below (works in previous versions but fails in 1.7)
```python
import torch

x = torch.tensor([[0.5, 0.2, 0.3, 0.8]], requires_grad=True)
w = torch.tensor([[0.2, 0.5, 0.1, 0.5]], requires_grad=True)
y_true = torch.tensor([1])

# In 1.7, `list(w)` returns list of UnbindBackward tensors, which further leads to inplace operation error.
# In previous versions, `list(w)` returns list of SelectBackward tensors and it works.
weight_list = list(w)
print('weight_list',weight_list) 

for i in range(2):
    l2_norm = torch.norm(weight_list[0], 2)
    y = w.mm(x.T)

    # mse with l2 regularization
    loss = pow(y - y_true, 2) + 0.5 * pow(l2_norm, 2)
    loss.backward()

    # simulate optimizer.step()
    with torch.no_grad():
        w.add_(w.grad, alpha=1e-3)

```

output:
**torch 1.7:** 
```
weight_list [tensor([0.2000, 0.5000, 0.1000, 0.5000], grad_fn=<UnbindBackward>)]
...
RuntimeError: Output 0 of UnbindBackward is a view and its base or another view of its base has been modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

Process finished with exit code 1
```

**previous versions:** 
```
weight_list [tensor([0.2000, 0.5000, 0.1000, 0.5000], grad_fn=<SelectBackward>)]

Process finished with exit code 0
```

My solution is to remove `list(weight_list)` operation for <class 'torch.nn.parameter.Parameter'> in https://github.com/shenweichen/DeepCTR-Torch/commit/a9402a474481fd186cb8428d6df9aadc2b3c69dd. Besides, if it's necessary to so such operation, using indices works:
```python
# weight_list = list(w)
weight_list = [w[i] for i in range(len(w))]
```

**Comment by gchanan** [comment] 2020-11-16 17:35
CC @albanD

**Comment by albanD** [comment] 2020-11-16 17:55
You can find it in the release note's BC-breaking section [here](https://github.com/pytorch/pytorch/releases/tag/v1.7.0).
There is a code sample there that shows how to avoid the issue by using `[[w[i] for i in range(len(w))]` (or something similar) as @zanshuxun mentioned above.

**Comment by parameciumvance** [comment] 2021-03-09 02:21
@zanshuxun  @albanD 
In torch 1.8, even workarounds mentioned above do not work
The error message becomes 

(if Select-->inplace)
`a view of a leaf Variable that requires grad is being used in an in-place operation.`

or (if unbind->Select-->inplace)
`Output 0 of SelectBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.`

**Comment by albanD** [comment] 2021-03-09 15:29
Hi,

Both of these are expected.
The first one happens because the Tensor over which you iterate is a leaf and you should not modify leaf Tensors inplace in a differentiable manner. Add a `.clone()` before the loop to avoid that.

The second one cannot be handled as mentioned above due to the unbind.

**Comment by albanD** [comment] 2021-03-09 15:30
Closing this as expected behavior.
Feel free to keep re-open if you think we can document this behavior better or that there is some mistakes that remain.

**Closed by albanD** 2021-03-09 15:30 UTC
Labels: module: viewing and reshaping, triaged
