### ISSUE TITLE
DISABLED test_profiler_remote_events_profiled_single_threaded (__main__.TensorPipeRpcTestWithSpawn)

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#49635] opened 2020-12-19 04:34 UTC
https://app.circleci.com/pipelines/github/pytorch/pytorch/253337/workflows/d7deaf65-3973-4e30-9892-c286d8b843b0/jobs/9751335/steps

```
Dec 18 23:49:33 ======================================================================
Dec 18 23:49:33 ERROR [1.442s]: test_profiler_remote_events_profiled_single_threaded (__main__.TensorPipeRpcTestWithSpawn)
Dec 18 23:49:33 ----------------------------------------------------------------------
Dec 18 23:49:33 Traceback (most recent call last):
Dec 18 23:49:33   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 280, in wrapper
Dec 18 23:49:33     self._join_processes(fn)
Dec 18 23:49:33   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 397, in _join_processes
Dec 18 23:49:33     self._check_return_codes(elapsed_time)
Dec 18 23:49:33   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 433, in _check_return_codes
Dec 18 23:49:33     raise RuntimeError(error)
Dec 18 23:49:33 RuntimeError: Processes 1 exited with error code 10
```

```
Dec 18 23:44:39   test_profiler_remote_events_profiled_single_threaded (__main__.TensorPipeRpcTestWithSpawn) ... ERROR:root:Caught exception: 
Dec 18 23:44:39 Traceback (most recent call last):
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_distributed.py", line 283, in wrapper
Dec 18 23:44:39     fn()
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 35, in wrapper
Dec 18 23:44:39     return_value = f(self, *args, **kwargs)
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/dist_utils.py", line 90, in new_test_method
Dec 18 23:44:39     return_value = old_test_method(self, *arg, **kwargs)
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1347, in test_profiler_remote_events_profiled_single_threaded
Dec 18 23:44:39     self._run_test_profiler_remote_events_profiled()
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/distributed/rpc/rpc_test.py", line 1338, in _run_test_profiler_remote_events_profiled
Dec 18 23:44:39     self.assertEqual(remote_events_list, EXPECTED_REMOTE_EVENTS)
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1208, in assertEqual
Dec 18 23:44:39     exact_dtype=exact_dtype, exact_device=exact_device)
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/site-packages/torch/testing/_internal/common_utils.py", line 1178, in assertEqual
Dec 18 23:44:39     super().assertEqual(x, y, msg=self._get_assert_msg(msg, debug_msg=debug_msg))
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/unittest/case.py", line 829, in assertEqual
Dec 18 23:44:39     assertion_func(first, second, msg=msg)
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
Dec 18 23:44:39     self.fail(self._formatMessage(msg, standardMsg))
Dec 18 23:44:39   File "/opt/conda/lib/python3.6/unittest/case.py", line 670, in fail
Dec 18 23:44:39     raise self.failureException(msg)
Dec 18 23:44:39 AssertionError: 'aten::sigmoid' != 'aten::threshold'
Dec 18 23:44:39 - aten::sigmoid
Dec 18 23:44:39 + aten::threshold
Dec 18 23:44:39  : Attempted to compare [string] types: Expected: 'aten::sigmoid'; Actual: 'aten::threshold'.
Dec 18 23:44:39 exiting process with exit code: 10
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @jjlilley @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd

**Comment by mrshenli** [comment] 2020-12-19 04:36
cc @rohan-varma looks like there are more occurrences. Is there any recent change in distributed profiler that could cause this?

https://app.circleci.com/pipelines/github/pytorch/pytorch/253200/workflows/38bf00e3-3b34-4a46-bca6-5d61ec83f412/jobs/9742942
https://app.circleci.com/pipelines/github/pytorch/pytorch/253144/workflows/8f90fb35-b33e-40ad-a159-c0e846694e96/jobs/9739671
https://app.circleci.com/pipelines/github/pytorch/pytorch/253135/workflows/3ee213bd-1f39-457a-8dd0-b679a1085d9e/jobs/9738813
https://app.circleci.com/pipelines/github/pytorch/pytorch/253031/workflows/f7b34e5f-dd2a-4abd-8066-c6d57848db87/jobs/9733852
https://app.circleci.com/pipelines/github/pytorch/pytorch/252914/workflows/0a689eb2-e06a-4daf-ae3c-9602bfd796ab/jobs/9725854
https://app.circleci.com/pipelines/github/pytorch/pytorch/252812/workflows/ca48a76a-bb79-4d83-a1f9-7edd23ed2953/jobs/9724659

**Comment by rohan-varma** [comment] 2020-12-19 07:35
We haven't changed the distirbuted profiling logic in a while, but this is likely coming from changes to the general profiler (not sure why they weren't caught on the corresponding PR). Seems to be an easy fix to just switch the operators expected

**Comment by rohan-varma** [comment] 2020-12-31 07:45
Tried the failing tests on the same CI machine thousands of times, but did not get a single failure. Not sure what caused the original. Sent https://github.com/pytorch/pytorch/pull/49983 to relax the assertions a bit in the tests, but other than that we probably could just let it run

**Comment by rohan-varma** [comment] 2021-01-25 21:28
Haven't been able to reproduce in CI after 1000+ runs, so closing to re-enable. Sent #49983 which should improve the logging a bit in case it does fail again.

**Closed by rohan-varma** 2021-01-25 21:28 UTC
Labels: module: flaky-tests, module: rpc, oncall: distributed
