### ISSUE TITLE
Enable MKLDNN support  on Windows packages by default as well

### ISSUE THREAD

**Issue by Coderx7** [pytorch/pytorch#32283] opened 2020-01-16 11:36 UTC
## 🚀 Feature
The MKLDNN is enabled by default for linux based packages (both pip and conda). However, on windows it is disabled by default and we are instructed to compile it from source code. 
Is there any technical reason behind  this, that made it disabled by default under windows and not linux? or is it just an unintentional bug?

## Motivation

MKLDNN has a profound affect on performance specially when used in CPU only mode. The inclusion of it by default in Windows based packages will then help a lot.
It may also be the reason behind the performance difference between the two platforms (Linux being much faster than its windows counter part)
 
## Pitch

Enable MKLDNN by default for pip/conda packages under Windows just like Linux

**Comment by peterjc123** [comment] 2020-01-16 13:21
Duplicate of #31355.

**Closed by peterjc123** 2020-01-16 13:21 UTC
