### ISSUE TITLE
Using a FastText model inside a PyTorch DataLoader

### ISSUE THREAD

**Issue by jaxony** [pytorch/pytorch#9015] opened 2018-06-29 02:51 UTC
I'm loading images and generating sentence vectors on-the-fly inside a PyTorch DataLoader. I am using FastText embedding model loaded with FastText's Python binding i.e., `fastText.load_model(bin_file_here)`.

When I pass into `torch.utils.data.DataLoader`:
* `num_workers > 0`  and `pin_memory=True`, `DataLoader.__iter__()` **never returns** and just hangs.
* `num_workers > 0` and `pin_memory=False`, `DataLoader.__iter__()` **returns successfully**.

I'm curious about why the vectors created by FastText in a multiprocessing environment can't be pinned onto CUDA memory. Thanks!

cc @SsnL @VitalyFedyunin @ejguan

**Comment by SsnL** [comment] 2018-06-29 05:42
Thanks for reporting! Could you share your Dataset code and enviroment information please?

**Comment by jaxony** [comment] 2018-06-29 06:21
Thanks for the fast reply @SsnL.

Environment:
* OS: Ubuntu 16.04.4
* Python distribution: Anaconda 4.5.4, Python 3.6
* PyTorch: built from master branch at `commit 77484d91db052`
* fastText: pip install from master branch at `commit 25d0bb04bf43d8b674f`
 
This is (most of) my Dataset code. `self.embedding` is a `FastText` object.
```python
class ImageVecDataset(Dataset):
    """A sample in this dataset is a single image
    and its associated 'semantic' vector.
    """

    def __init__(self, csv_file, root_dir, embedding, transform=None):
        """
        Args:
            csv_file (string): Path to the csv file with titles.
            root_dir (string): Directory with all the images.
            embedding (object): Object containing pretrained word embedding.
            transform (callable, optional): Optional transform to be applied
                on a sample.
        """
        self.df = utils.load_df(csv_file, preprocess=False, drop_duplicates=False)
        self.df = self.df.sample(frac=1)
        self.root_dir = root_dir
        if self.root_dir[-1] != "/": self.root_dir += "/"

        self.transform = transform
        self.embedding = embedding
        
     ...
    
    def __len__(self):
        return len(self.df)        
    
    def __getitem__(self, idx):
        item = self.df.iloc[idx]
        im_url = item['im_url']
        title = item['title']
        
        try:
            image_path = self._get_image_path(im_url)
            image = Image.open(image_path)
        except:
            # many images may be missing
            return None

        if self.transform:
            image = self.transform(image)
        label = self.embedding.get_sentence_vector(title)
        return image, label
```

**Comment by SsnL** [comment] 2018-07-09 20:05
When it hangs, can you interrupt it, e.g., using ctrl+C? If so, what's the stack trace it prints?

**Comment by mruberry** [comment] 2020-12-29 18:05
Closing due to age and lack of reproduction. If this is still an issue on a more recent version of PyTorch, like 1.7, please update and reopen.

**Closed by mruberry** 2020-12-29 18:05 UTC
Labels: module: dataloader, needs reproduction, triaged
