### ISSUE TITLE
XML test-reports get overwritten in case of retry

### ISSUE THREAD

**Issue by BLOrange-AMD** [pytorch/pytorch#123882] opened 2024-04-11 23:49 UTC
### 🐛 Describe the bug

The following job runs test_transformers.py and faces an error and then retries, skipping the already-run tests.
https://github.com/pytorch/pytorch/actions/runs/8641537318/job/23692796547
```
2024-04-11T06:33:50.7653197Z collecting ... collected 75517 items
2024-04-11T06:33:50.7653986Z stepcurrent: Cannot find last run test, not skipping
2024-04-11T06:33:55.8823446Z Running 75517 items in this shard: 
...
...
2024-04-11T06:34:03.3174724Z test_transformers.py::TestSDPACudaOnlyCUDA::test_flash_attention_vs_math_ref_grads_batch_size_8_seq_len_q_2048_seq_len_k_2048_head_dim_72_is_causal_True_dropout_p_0_22_bfloat16_scale0_cuda_bfloat16 [hsaKmtAllocMemory] failed to allocate 16777216 bytes from device
2024-04-11T06:34:03.3175634Z GPU mapping failed (-1) for obj at 0x7fd5b4780000, userptr (nil), size 715653120[hsaKmtAllocMemory] failed to allocate 16777216 bytes from device
2024-04-11T06:34:03.3177167Z :0:rocdevice.cpp            :2722: 10391684596329 us: [pid:43573 tid:0x7fd6dffff700] Callback: Queue 0x7fd388e00000 Aborting with error : HSA_STATUS_ERROR_OUT_OF_RESOURCES: The runtime failed to allocate the necessary resources. This error may also occur when the core runtime library needs to spawn threads or create internal OS-specific events. Code: 0x1008 Available Free mem : 0 MB
2024-04-11T06:34:03.3177274Z Fatal Python error: Aborted
...
...
2024-04-11T06:34:03.3196290Z collecting ... collected 75517 items / 25270 deselected / 50247 selected
2024-04-11T06:34:03.3196427Z stepcurrent: skipping 25270 already run items.
2024-04-11T06:34:03.3196535Z Running 50247 items in this shard
...
...
2024-04-11T06:34:03.3197597Z test_transformers.py::TestSDPACudaOnlyCUDA::test_flash_attention_vs_math_ref_grads_batch_size_8_seq_len_q_2048_seq_len_k_2048_head_dim_72_is_causal_True_dropout_p_0_22_bfloat16_scale0_cuda_bfloat16 [W411 06:31:44.703017462 attention.cpp:763] Warning: Dropout mask should only be used for testing purposes. (function operator())
2024-04-11T06:34:03.3197692Z PASSED [3.0140s] [  0%]
```

This is the artifact for the job mentioned above:
https://gha-artifacts.s3.amazonaws.com/pytorch/pytorch/8641537318/1/artifact/test-reports-test-default-3-6-linux.rocm.gpu.2_23692796547.zip

In the unzipped folder and file: unzipped-test-reports-test-default-3-6-linux.rocm.gpu.2_23692796547/test-reports/python-pytest/test_transformers/test_transformers-7c013daedec27cf0.xml, the unit test which faces an error and then retries is the first logged test in the xml file. All tests before the re-run test are overwritten (corresponding to **skipping 25270 already run items**).
```
<testsuites><testsuite name="pytest" errors="0" failures="0" skipped="43119" tests="50247" time="129.189" timestamp="2024-04-11T06:31:36.663051" hostname="d848c778d3bc"><testcase classname="TestSDPACudaOnlyCUDA" name="test_flash_attention_vs_math_ref_grads_batch_size_8_seq_len_q_2048_seq_len_k_2048_head_dim_72_is_causal_True_dropout_p_0_22_bfloat16_scale0_cuda_bfloat16" time="3.015" file="test_transformers.py" /><testcase classname="TestSDPACudaOnlyCUDA" 
```

### Expected behavior

Xml test-reports should contain info for all the tests that were run as part of different retries.

### Versions

PyTorch upstream CI

cc @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by jithunnair-amd** [comment] 2024-04-12 04:23
cc @clee2000 @huydhn This seems to be a bug in the xml-generating logic interacting with the rerun failures logic.

**Comment by clee2000** [comment] 2024-04-12 17:05
The XML files are generated after the entire test suite is run, so segfaults and other errors that cause the process to exit prematurely result in no XML getting made at all.  The rerun logic is such that we skip previously run tests in order to save time at the risk of losing some test reports.

Possible solutions:
* Use xdist?
* Rerun from start (ideally check if xml exists first, if not rerun from start, other wise rerun from last failed)
* Generate XML after every test or periodically (need to examine impact on test time, when this was done for unittest it took too long)

**Comment by jithunnair-amd** [comment] 2024-04-12 17:10
@clee2000 "The rerun logic is such that we skip previously run tests in order to save time at the risk of losing some test reports."
I see, so this is a known tradeoff. Our use case is to download the artifacts for the CI runs on trunk, and parse them to get an accurate idea of the unit test parity between ROCm and CUDA CI. If tests go missing like above, it creates a false impression of tests not being run in ROCm CI.

**Comment by jithunnair-amd** [comment] 2024-04-25 21:55
Closing this issue as it seems to be a "feature, not a bug" :)

**Closed by jithunnair-amd** 2024-04-25 21:55 UTC
Labels: module: ci, triaged
