### ISSUE TITLE
[dynamo] Unable to continue tracing graph after try/except graph break

### ISSUE THREAD

**Issue by jon-chuang** [pytorch/pytorch#112865] opened 2023-11-03 16:28 UTC
### 🐛 Describe the bug

repro

```python
def fn(x):
    x = x + 1
    try:
        raise AssertionError()
    except AssertionError:
        pass
    x = x + 2
    return x

x = torch.zeros(3)
eager = fn(x)

from torch._dynamo.testing import CompileCounter
cnt = CompileCounter()
compiled_fn = torch._dynamo.optimize(backend=cnt)(fn)
compiled = compiled_fn(x)

torch.testing.assert_close(eager, compiled)
assert cnt.frame_count == 2, cnt.frame_count  # 1, but should be 2!
```

### Versions

main

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jon-chuang** [comment] 2023-11-03 17:41
The reason for this is:
`all(b.can_restore() for b in self.block_stack) == False`

**Comment by jon-chuang** [comment] 2023-11-03 18:04
I think the root cause is identical to https://github.com/pytorch/pytorch/issues/112824, we cannot handle regions of graph breaks.

**Comment by jon-chuang** [comment] 2023-11-04 00:00
Handling nested try except is likely equivalent to fixing https://github.com/pytorch/pytorch/issues/111003

**Comment by jon-chuang** [comment] 2023-11-05 14:04
@Fidget-Spinner, since you may be interested in this general area:
1. What we are looking for is the ability to mark out a "resume point" / "break point"
2. We want to return execution to CPython for some modified code object, but have it return control to Dynamo, at the precise "break point"
3. Dynamo can then analyze the stack contents, block stack, and locals at the break point, and then create a call to `resume_at`.
4. Then Dynamo can trace the `resume_at` function and possibly compile part of it.

**Comment by jon-chuang** [comment] 2023-11-11 13:47
@Fidget-Spinner, similar to what you did in https://github.com/pytorch/pytorch/issues/112303#issuecomment-1793672202, do you think it is possible to, given a code object, with an annotation about a breakpoint (e.g. at a particular lineno), and its corresponding python code (i.e. AST), transform the remainder of the function definition after the breakpoint into a function call?

**Comment by Fidget-Spinner** [comment] 2023-11-12 01:15
Sorry for the late reply.
> 2. We want to return execution to CPython for some modified code object, but have it return control to Dynamo, at the precise "break point"

This sounds somewhat perilous to implement correctly. Off the top of my head, your best bet would be having a callable that wraps the "break point" with `set_eval_frame` and such.
  



> @Fidget-Spinner, <snipped> do you think it is possible to, given a code object, with an annotation about a breakpoint (e.g. at a particular lineno), and its corresponding python code (i.e. AST), transform the remainder of the function definition after the breakpoint into a function call?

Yes it's possible.

**Comment by anijain2305** [comment] 2024-02-01 00:21
Duplicate of https://github.com/pytorch/pytorch/issues/93720

**Comment by anijain2305** [comment] 2024-06-10 16:59
This is supported today.

**Closed by anijain2305** 2024-06-10 16:59 UTC
Labels: triaged, oncall: pt2, module: dynamo
