### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by CharlesxrWu** [pytorch/pytorch#6504] opened 2018-04-11 13:57 UTC
PyTorch GitHub Issues Guidelines
--------------------------------

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):
- PyTorch or Caffe2: PyTorch
- OS: Ubuntu 16.04
- PyTorch version: 0.3.1
- How you installed PyTorch (conda, pip, source): conda
- Python version: python 3.6.4
- CUDA/cuDNN version: 9.0 / 7
- GPU models and configuration: GTX 1080 Ti
- GCC version (if compiling from source): 
- CMake version:
- Build command you used (if compiling from source):
- Versions of any other relevant libraries:

In addition, including the following information will also be very helpful for us to diagnose the problem:
Running https://github.com/pytorch/examples/blob/master/imagenet/main.py#L10 changed the model to the GoogLeNet. Even batch_size=10, out of memory.

THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1522182087074/work/torch/lib/THC/generic/THCStorage.cu line=58 error=2 : out of memory

**Comment by zou3519** [comment] 2018-04-11 14:06
Could you verify in the `nvidia-smi` output that the memory is running out? Is GPU memory already allocated before you run imagenet?

**Comment by CharlesxrWu** [comment] 2018-04-11 14:32
I changed the batch_size from 128 to 16. I saw that python occupies up to 4GB, then the script crashed.

**Comment by zou3519** [comment] 2018-04-11 14:39
And to clarify: what exactly are the runs you've tried, and how exactly are you running the script? I'm not sure if you're running it normally or with GoogLeNet (which I don't know how to modify the script to run with)

**Comment by CharlesxrWu** [comment] 2018-04-11 15:04
import the GoogLeNet() from 
https://github.com/kuangliu/pytorch-cifar/blob/master/models/googlenet.py 
And replace the model=GoogLeNet() in the main script. Then run the script.

**Comment by ccampell** [comment] 2018-04-22 02:02
I am also getting the same error on a Windows machine (I know you are still un-released), see specific details below. The error occurs when following setup instructions listed below, and then using runtime parameter one sequence. 

## PyTorch GitHub Issues Guidelines

We like to limit our issues to bug reports and feature requests. If you have a question or would like help and support, please visit our forums: https://discuss.pytorch.org/

If you are submitting a feature request, please preface the title with [feature request].

When submitting a bug report, please include the following information (where relevant):

PyTorch or Caffe2: PyTorch
OS: Windows 10 Home 64-bit
PyTorch version: 0.3.1.post2
How you installed PyTorch (conda, pip, source): `conda install -c peterjc123 pytorch cuda90`
Python version: python 3.6.4
CUDA/cuDNN version: V9.1.85
GPU models and configuration: Geforce GTX 1080 Ti FTW3 Hybrid 
GCC version (if compiling from source): NA
CMake version: NA
Build command you used (if compiling from source): NA
Train and Validation Data: [PyTorch Transfer Learning Tutorial Hymenoptera ImageNet Subset](https://download.pytorch.org/tutorial/hymenoptera_data.zip)
Desired Transfer Learning Type: [ConvNet as fixed feature extractor](http://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html)
Versions of any other relevant libraries: 
* conda 4.5.0
* Anaconda 3

Steps to Reproduce:
1. Download the [Hymenoptera Data](https://download.pytorch.org/tutorial/hymenoptera_data.zip) to `DATA_DIR`
2. `git clone https://github.com/pytorch/examples.git`
3. Enter one of the commands from the list below into the python command line.

Runtime Parameters: 
* Run one: `python DATA_DIR --arch=inception_v3 --pretrained --b=256 main.py` 
* Run two: `python DATA_DIR --arch=inception_v3 --pretrained --b=10 main.py` 
* Run three: `python DATA_DIR --arch=inception_v3 --pretrained --b=256 --evaluate main.py`

Execution Results:
* Run one: [RuntimeError Gist](https://gist.github.com/ccampell/d703481f4d88fa6adadd8cafea427ee7)
* Run two: [RuntimeError Gist](https://gist.github.com/ccampell/5da5ad5f234729880a1d297522c53ced)
* Run three: [RuntimeError Gist](https://gist.github.com/ccampell/8ce1dc98a927eb51542b50d52f0df1e7)

I hope the provided information helps with debugging.

**Comment by fmassa** [comment] 2018-04-24 13:16
@CharlesxrWu it seems that you are using a model specific for cifar on ImageNet, which is not adapted, as the model for Cifar has very few downsampling, and you end up using way to much memory.

@ccampell your case looks a bit related. In the first case you are running out of memory because a batch size of 256 is too much for a single GPU for InceptionV3.
For the two other cases, it seems that your input images are smaller than what the model that you are passing expect. InceptionV3 expects inputs to be of size 299x299 if I recall correctly, and not 224x224, as is the default in the imagenet example

Closing as this looks like user-error, and not a bug in PyTorch

**Closed by fmassa** 2018-04-24 13:16 UTC
Labels: pytorch

**Comment by ccampell** [comment] 2018-04-24 17:10
@fmassa Agreed, user-error on my part.
