### ISSUE TITLE
DISABLED test_MaxUnpool_index_errors_case1_cuda (__main__.TestPoolingNNDeviceTypeCUDA)

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#103854] opened 2023-06-19 16:52 UTC
Platforms: slow

This test was disabled because it is failing on master ([recent examples](http://torch-ci.com/failure/nn%2Ftest_pooling.py%3A%3ATestPoolingNNDeviceTypeCUDA%3A%3Atest_MaxUnpool_index_errors_case1_cuda)).

cc @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by malfet** [comment] 2023-06-19 17:45
@huydhn, looks like slow is not recognized as a valid platform.

**Comment by xwang233** [comment] 2023-06-20 23:33
PR https://github.com/pytorch/pytorch/pull/95300 might exposed this error

**Comment by mikaylagawarecki** [comment] 2023-06-21 20:14
fwiw, I was looking into the other related MaxUnpool_index_errors_case{*} flaky tests and I can reproduce them locally with 
`PYTORCH_TEST_WITH_SLOW=1 python test/nn/test_pooling.py -k test_MaxUnpool_index_errors_case` 

https://github.com/pytorch/pytorch/issues/81989
https://github.com/pytorch/pytorch/issues/81966
https://github.com/pytorch/pytorch/issues/81840
https://github.com/pytorch/pytorch/issues/81841

if I change this line back from `CUDA_KERNEL_ASSERT2` --> `CUDA_KERNEL_ASSERT` 

https://github.com/pytorch/pytorch/blob/1c79003b3c13c7bc47e5796e4451d6565121f3a0/aten/src/ATen/native/cuda/MaxUnpooling.cu#L49

and run 

`PYTORCH_TEST_WITH_SLOW=1 python test/nn/test_pooling.py -k test_MaxUnpool_index_errors_case` 

all the tests pass.

However the flaky issues for the other cases have been open since July last year which feels odd since #95300 was only landed last week

**Comment by mikaylagawarecki** [comment] 2023-06-21 20:21
fwiw, I was looking into the other related MaxUnpool_index_errors_case{*} flaky tests and I can reproduce them locally with
`PYTORCH_TEST_WITH_SLOW=1 python test/nn/test_pooling.py -k test_MaxUnpool_index_errors_case`

https://github.com/pytorch/pytorch/issues/81989
https://github.com/pytorch/pytorch/issues/81966
https://github.com/pytorch/pytorch/issues/81840
https://github.com/pytorch/pytorch/issues/81841

if I change these two lines back from CUDA_KERNEL_ASSERT2 --> CUDA_KERNEL_ASSERT


https://github.com/pytorch/pytorch/blob/1c79003b3c13c7bc47e5796e4451d6565121f3a0/aten/src/ATen/native/cuda/MaxUnpooling.cu#L49

https://github.com/pytorch/pytorch/blob/1c79003b3c13c7bc47e5796e4451d6565121f3a0/aten/src/ATen/native/cuda/MaxUnpooling.cu#L72

and run

`PYTORCH_TEST_WITH_SLOW=1 python test/nn/test_pooling.py -k test_MaxUnpool_index_errors_case`

all the tests pass.

However the flaky issues for the other cases have been open since July last year which feels odd since https://github.com/pytorch/pytorch/pull/95300 was only landed last week

**Comment by mikaylagawarecki** [comment] 2023-06-21 22:32
Hm I ran the following script

```
import torch

unpool = torch.nn.MaxUnpool2d((2, 2)).to('cuda')
output = torch.rand((1, 3, 4, 5), dtype=torch.float32, device='cuda')
indices = torch.zeros((1, 3, 4, 5), dtype=torch.int64, device='cuda')
indices.flatten()[0] = -1
unpool(output, indices)
unpool(output, indices)
torch.cuda.synchronize()
```

and it doesn't seem to trigger the device-side assert :/ so it seems like maybe exception generation isn't happening

**Closed** 2023-07-05 21:39 UTC
Labels: module: nn, triaged, skipped
