### ISSUE TITLE
MaxUnpool2d docs have a misleading example using `output_size`

### ISSUE THREAD

**Issue by kylematoba** [pytorch/pytorch#68873] opened 2021-11-24 13:31 UTC
## 🐛 Bug
The `output_size` argument to `MaxUnpool2d` gives wrong results. 

## To Reproduce
```
import torch
if __name__ == "__main__":
    pool = torch.nn.MaxPool2d(2, stride=2, return_indices=True)
    unpool = torch.nn.MaxUnpool2d(2, stride=2)
    input = torch.torch.tensor([[[[ 1.,  2,  3,  4],
                                  [ 5,  6,  7,  8],
                                  [ 9, 10, 11, 12],
                                  [13, 14, 15, 16]]]])
    output, indices = pool(input)
    unpooled44 = unpool(output, indices)
    torch.testing.assert_allclose(pool(unpooled44)[0], output)
    unpooled55 = unpool(output, indices, output_size=torch.Size([1, 1, 5, 5]))
    torch.testing.assert_allclose(pool(unpooled55)[0], output)

Traceback (most recent call last):
  File "/xxx/localenv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-a977e504821f>", line 16, in <module>
    torch.testing.assert_allclose(pool(unpooled55)[0], output)
  File "/xxx/localenv/lib/python3.9/site-packages/torch/testing/__init__.py", line 232, in assert_allclose
    raise AssertionError(msg)
AssertionError: With rtol=0.0001 and atol=1e-05, found 2 element(s) (out of 4) whose difference(s) exceeded the margin of error (including 0 nan comparisons). The greatest difference was 2.0 (16.0 vs. 14.0), which occurred at index (0, 0, 1, 0).
```
(this is the example from the docs)
## Expected behavior
`pool(unpool(output, indices)[0]) == output`, for the example above, one of many possible correct inverses could be:

```
    unpooled55_correct = torch.tensor([[[[ 0.,  0.,  0.,  0.,  0.],
                                      [ 6.,  0.,  8.,  0.,  0.],
                                      [ 0.,  0.,  0., 0.,  0.],
                                      [14.,  0.,  0.,  16.,  0.],
                                      [ 0.,  0.,  0.,  0,  0.]]]])
    torch.testing.assert_allclose(pool(unpooled55_correct)[0], output)
```
## Environment

 - PyTorch Version (e.g., 1.0): 1.8.1
 - OS (e.g., Linux):  macOS 12.0.1 (x86_64)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: Python 3.9.2 (v3.9.2:1a79785e3e, Feb 19 2021, 09:06:10) 
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

cc @brianjo @mruberry @albanD @jbschlosser @walterddr

**Comment by jbschlosser** [comment] 2021-11-24 17:20
I think this behavior is expected. In your example, the `indices` were produced from pooling with an input of size `(1, 1, 4, 4)` so they are only guaranteed to produce a proper inverse when unpooling to that same size.

Note that the purpose of the `output_size` arg is to address ambiguity in the original input size, allowing for something like this to work:

```python
import torch

pool = torch.nn.MaxPool2d(2, stride=2, return_indices=True)
unpool = torch.nn.MaxUnpool2d(2, stride=2)
input = torch.torch.tensor([[[[ 1.,  2,  3,  4, 0],
                              [ 5,  6,  7,  8, 0],
                              [ 9, 10, 11, 12, 0],
                              [13, 14, 15, 16, 0],
                              [0, 0, 0, 0, 0]]]])
output, indices = pool(input)
unpooled55 = unpool(output, indices, output_size=torch.Size([1, 1, 5, 5]))
torch.testing.assert_allclose(pool(unpooled55)[0], output)
```

Closing as intended behavior but please feel free to reopen if you feel this is still unresolved.

**Comment by kylematoba** [comment] 2021-11-24 19:58
Thanks @jbschlosser for your reply. I see what you mean, but what you say is contradicted by the example at:

https://github.com/pytorch/pytorch/blob/543b7fb94282db604a869d1fe98e013dfe18cb0d/torch/nn/modules/pooling.py#L376

which does exactly what I did: call `unpool(*, *, output_size=torch.Size([1, 1, 5, 5]))` on `indices` generated from a 4 x 4 input? The comment (`# specify a different output size than input size`) as well indicates that the "expected behavior" might not be so expected! Can you talk to your team and decide what is right? I'll update the docs based on what you decide.

**Comment by jbschlosser** [comment] 2021-11-29 19:50
@kylematoba Makes sense, I'm good with accepting a PR that better demonstrates the intended purpose of `output_size` without being misleading.

**Comment by thomasjpfan** [comment] 2021-12-03 14:22
Closing issue since it was resolved in https://github.com/pytorch/pytorch/pull/68936

**Closed by thomasjpfan** 2021-12-03 14:22 UTC
Labels: module: docs, module: nn, triaged
