### ISSUE TITLE
[JIT] Cannot do type refinement on class attribute

### ISSUE THREAD

**Issue by xush6528** [pytorch/pytorch#36246] opened 2020-04-08 18:16 UTC
```py
class MyModule(nn.Module)
    number = Optional[int]

    def __init__(self, number=None):
        self.number = number

    def forward(self):
        if self.number is not None:
            self.number += 1

my_module = torch.jit.script(MyModule())
```

Always have to work around it.
```py
class MyModule(nn.Module)
    number = Optional[int]

    def __init__(self, number=None):
        self.number = number

    def forward(self):
        number = self.number
        if number is not None:
           number += 1

my_module = torch.jit.script(MyModule())
```

cc @suo

**Comment by jamesr66a** [comment] 2020-04-08 19:20
This seems to be a duplicate of https://github.com/pytorch/pytorch/issues/22155

**Closed by jamesr66a** 2020-04-08 19:20 UTC
Labels: jit
