### ISSUE TITLE
Autocast with LSTM cell (with bias) produces "expected scalar type Half but found Float"

### ISSUE THREAD

**Issue by phizaz** [pytorch/pytorch#45048] opened 2020-09-20 17:06 UTC
## 🐛 Bug

LSTM cell with bias produces "expected scalar type Half but found Float" error when called within an autocast context.

## To Reproduce

```
import torch
import torch.nn as nn
from torch.cuda.amp import *
dev = 'cuda'
net = nn.LSTMCell(3, 3, bias=True).to(dev)
x = torch.randn(2, 3).to(dev)
with autocast():    
    h, c = net(x.half())
```

Error produced:
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-16-1d68da89e14f> in <module>
      4 
      5 with autocast():
----> 6     h, c = net(x.half())

~/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    720             result = self._slow_forward(*input, **kwargs)
    721         else:
--> 722             result = self.forward(*input, **kwargs)
    723         for hook in itertools.chain(
    724                 _global_forward_hooks.values(),

~/miniconda3/lib/python3.7/site-packages/torch/nn/modules/rnn.py in forward(self, input, hx)
    967             input, hx,
    968             self.weight_ih, self.weight_hh,
--> 969             self.bias_ih, self.bias_hh,
    970         )
    971 

RuntimeError: expected scalar type Half but found Float
```

Note that there is no problem while setting `bias=False`.

## Expected behavior

No error.

## Environment

 - PyTorch Version (e.g., 1.0): 1.6.0
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source):
 - Python version: 3.7.6
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: GTX 1060

**Comment by ngimel** [comment] 2020-09-20 22:11
Duplicate of #42605, this was fixed in #44296

**Closed by ngimel** 2020-09-20 22:11 UTC
