### ISSUE TITLE
Indexed, in-place multiplication segfaults/drops values

### ISSUE THREAD

**Issue by andres-fr** [pytorch/pytorch#27824] opened 2019-10-13 22:07 UTC
## 🐛 Bug

Hi everyone! thanks for this amazing software. Playing around with the new boolean tensors, I found out this issue, likely to be a bug involving indexed and in-place operations.

Specifically in this minimal working example, indexed, in-place multiplication a non-zero constant float matrix by an all-True boolean matrix results in some values being dropped to zero, or even segfaults.

## To Reproduce

Script:
```
import torch
# import matplotlib.pyplot as plt


# TESTING GLOBALS
FLOAT_DTYPE = torch.float32  # also reproducible with float64
MASK_DTYPE = torch.uint8 # torch.bool
H, W = 400, 640  # also reproducible with many different resolutions
DEVICE = "cpu"  # reproducible on i7 cpu and RTX2060 cuda, Ubuntu17.10
SOME_FLOAT = 1.23
MIN_IDX = 1  # high values cause segfault

# CREATE AND INITIALIZE BUFFERS
D_TMP = torch.empty(H, W, dtype=FLOAT_DTYPE).to(DEVICE).fill_(SOME_FLOAT)
MASK_BUFF = torch.ones(H, W, dtype=MASK_DTYPE).to(DEVICE)

# CRITICAL PART
#
# D_TMP *= MASK_BUFF  # OK
# D_TMP[0:H, 0:W] *= MASK_BUFF[0:H, 0:W]  # OK
# D_TMP[[MIN_IDX:H, 0:W] *= MASK_BUFF[[MIN_IDX:H, 0:W]  # OK
D_TMP[MIN_IDX:H, MIN_IDX:W] *= MASK_BUFF[MIN_IDX:H, MIN_IDX:W]  # buggy
# D_TMP[0:H, MIN_IDX:W] *= MASK_BUFF[0:H, MIN_IDX:W]  # buggy


# CHECK IF ENTRIES ARE MISSING
assert MASK_BUFF.all(), "Mask has zeros?"
assert (D_TMP==SOME_FLOAT).all(), "D_tmp has dropped values?"
# plt.imshow(MASK_BUFF.to(torch.uint8).cpu().numpy())
# plt.imshow(D_TMP.cpu().numpy())
# plt.show()
```

## Expected behavior

In-place multiplication of a float tensor's subsection by an all-true boolean/uint8 subsection shouldn't alter its contents or segfault.
## Environment

 - PyTorch Version (e.g., 1.0): 1.3.0
 - OS (e.g., Linux): Ubuntu 17.10
 - How you installed PyTorch (`conda`, `pip`, source): conda nightly
 - Build command you used (if compiling from source): --
 - Python version:  3.7.2
 - CUDA/cuDNN version: 10.1/7603
 - GPU models and configuration: PNY RTX2060 SUPER
 - Any other relevant information:

## Additional context

Maybe I am missing something obvious and is not a bug?
 
Please let me know if I can help any further, I will be glad to try a fix if some more seasoned contributor can give me some pointers on where to look.

For the moment, **a temporary workaround is to perform non-indexed operations**, which isn't ideal due to potential computational overhead.

cc @ezyang @gchanan @zou3519 @izdeby

**Comment by vincentqb** [comment] 2019-10-14 18:39
@izdeby -- This does look like a bug. Can you respond to this?

**Comment by andres-fr** [comment] 2019-10-15 10:11
@vincentqb thanks a lot. After seeing the boolean label I tested the mask with int16 and int32, and can confirm that the issue also applies to those types, so maybe that label is too specific

**Comment by vincentqb** [comment] 2019-10-15 15:07
Marking as high priority since this can lead to seg faults, and affect booleans, int16 and int32.

**Comment by ezyang** [comment] 2019-10-16 20:39
reproduces for me on master:

```
$ python test.py
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    assert (D_TMP==SOME_FLOAT).all(), "D_tmp has dropped values?"
AssertionError: D_tmp has dropped values?
```

**Comment by gchanan** [comment] 2019-10-16 20:46
Could be related to type promotion -- same as https://github.com/pytorch/pytorch/issues/28010, maybe?

**Comment by nairbv** [comment] 2019-10-16 21:03
Can also be repro'd without the in-place op, seems related to how the mask is indexed:

```
>>> tmp = torch.empty(399, 639, dtype=torch.float).fill_(1.5)
>>> mask = torch.ones(400, 640, dtype=torch.uint8)
>>> tmp + mask[1:, 1:]
tensor([[2.5000, 2.5000, 2.5000,  ..., 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000,  ..., 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000,  ..., 2.5000, 2.5000, 2.5000],
        ...,
        [2.5000, 2.5000, 2.5000,  ..., 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000,  ..., 2.5000, 2.5000, 2.5000],
        [2.5000, 2.5000, 2.5000,  ..., 4.0000, 4.0000, 4.0000]])
```

@colesbury any thoughts on how indexing interacts with the promotion changes?

**Closed** 2019-10-24 22:18 UTC
Labels: high priority, module: internals, topic: type promotion, triaged

**Comment by andres-fr** [comment] 2020-02-21 15:41
Hi again!

Sorry for the noise, I don't quite understand the thread. Is this fixed? I'm profiling the pipeline and indexed operations would help

**Comment by gchanan** [comment] 2020-02-21 22:48
Yes, it has been fixed.
