### ISSUE TITLE
torch.cat accepts both Variable and tensor

### ISSUE THREAD

**Issue by ruotianluo** [pytorch/pytorch#2367] opened 2017-08-10 09:03 UTC
It seems that torch.cat can concatenate variables and tensors and output a variable. However, this will cause backward crash.

```
import torch
x = torch.autograd.Variable(torch.randn(3,4), requires_grad=True)
y = torch.randn(3,2)
z = torch.cat([x,y],1)
z.sum().backward()
```

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/rluo/anaconda2/lib/python2.7/site-packages/torch/autograd/variable.py", line 156, in backward
>     torch.autograd.backward(self, gradient, retain_graph, create_graph, retain_variables)
>   File "/Users/rluo/anaconda2/lib/python2.7/site-packages/torch/autograd/__init__.py", line 98, in backward
>     variables, grad_variables, retain_graph)
> RuntimeError: function ConcatBackward returned a gradient different than None at position 3, but the corresponding forward input was not a Variable

1. Is it a good feature?
2. If you want to keep it, should the framework be able to infer the tensor to be a leaf node?

**Comment by apaszke** [comment] 2017-08-10 16:14
It's not really intended to be used like this. We don't support mixing tensors and Variables in ops yet, but we could improve the error message

**Comment by srviest** [comment] 2017-08-29 15:22
Got the same problem in back propagation...I think torch.cat is supposed to accept the same type of tensor.

**Comment by robotcator** [comment] 2017-09-01 07:31
I do also come across this problem.
@apaszke In some paper's model[1], the `cat` operation actually was used, so it seems that this feature is needed.
![screenshot from 2017-09-01 15 26 48](https://user-images.githubusercontent.com/5803439/29959457-075c5612-8f2a-11e7-9ca7-bef88963df6f.png)

And I also curious how to implement this.

[1]: Perarnau, Guim, et al. "Invertible Conditional GANs for image editing." arXiv preprint arXiv:1611.06355 (2016).

**Comment by rrivera1849** [comment] 2017-11-22 22:00
Hello, I am a newbie and would like to tackle this issue. Is the intended behavior to throw an error when the types don't match?

**Comment by gchanan** [comment] 2018-04-24 20:30
variables and tensors have been merged, so this isn't relevant anymore.

**Closed by gchanan** 2018-04-24 20:30 UTC
