### ISSUE TITLE
Nightly Windows+CUDA+Conda+Py-3.10 tests fail

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#89935] opened 2022-11-30 18:37 UTC
### 🐛 Describe the bug

See https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=windows-binary-conda%20%2F%20conda-py3_10-cuda11_6-test and https://hud.pytorch.org/hud/pytorch/pytorch/nightly/1?per_page=50&name_filter=windows-binary-conda%20%2F%20conda-py3_10-cuda11_7-test

Other windows builds/tests are fine and failures started on Nov 22nd 2022.

### Versions

CI

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @seemethere @pytorch/pytorch-dev-infra

**Comment by malfet** [comment] 2022-11-30 18:46
Same regression was caught by nightly test matrix, but was not reported back as failure, see https://github.com/pytorch/builder/actions/runs/3584244365/jobs/6030672508

**Comment by Blackhex** [comment] 2022-12-02 00:59
I was not able to reproduce the issue locally so far using the following script:

```
set "CONDA_HOME=%CD%\conda"

curl -k https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -o "miniconda.exe"

start /wait "" "miniconda.exe" /S /InstallationType=JustMe /RegisterPython=0 /AddToPath=0 /D=%CONDA_HOME%

set "PATH=%CONDA_HOME%;%CONDA_HOME%\scripts;%CONDA_HOME%\Library\bin;%PATH%"
call conda create -qy python=3.10 -p "%CONDA_HOME%\testenv"
call %CONDA_HOME%\condabin\activate.bat "%CONDA_HOME%\testenv"
call conda update -n base -y -c defaults conda
call conda install -c=nvidia -yq protobuf numpy
call conda install -y pytorch torchvision torchaudio pytorch-cuda=11.6 -c pytorch-nightly -c nvidia
call conda update --all -c=nvidia -y -c pytorch -c defaults -c numba/label/dev

python -c "import torch; exit(0 if torch.backends.mkl.is_available() else 1)"
echo %errorlevel%
```

**Comment by Blackhex** [comment] 2022-12-02 01:29
Is there a way to download `C:\actions-runner\_work\_temp\artifacts\pytorch-1.14.0.dev20221201-py3.10_cuda11.6_cudnn8_0.tar.bz2` somewhere?

**Comment by malfet** [comment] 2022-12-02 13:28
Yes, it is available is the run artifact, though it is of no use right now as all nightly conda builds are broken, see https://github.com/pytorch/pytorch/issues/90059

**Comment by malfet** [comment] 2022-12-05 17:39
I think the logic of the test script is wrong: it first installs pytorch locally, but later re-installs it again from the nightly repository, which means that in most case it would end up testing previous version, or if one could not be found test whichever one is available on the default channel.

**Comment by Blackhex** [comment] 2022-12-05 18:29
@malfet Yes, it even happened once, when I was trying to reproduce the issue locally, that the update installed Python 3.8 and the smoke test was running under Python 3.8. I tried to reproduce this later but with no luck.

**Comment by Blackhex** [comment] 2022-12-06 19:56
I could reproduce the issue with the artifact from https://github.com/pytorch/pytorch/actions/runs/3623448501:

```
set "CONDA_HOME=%CD%\windows\conda"

curl -k https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -o "windows\miniconda.exe"

start /wait "" "windows\miniconda.exe" /S /InstallationType=JustMe /RegisterPython=0 /AddToPath=0 /D=%CONDA_HOME%

set "PATH=%CONDA_HOME%;%CONDA_HOME%\scripts;%CONDA_HOME%\Library\bin;%PATH%"
conda create -qyp "%CONDA_HOME%\testenv" python=3.10
call %CONDA_HOME%\condabin\activate.bat "%CONDA_HOME%\testenv"
call conda update -n base -y -c defaults conda
call conda install -c=nvidia -yq protobuf numpy

call conda install -c=nvidia -y "pytorch-1.14.0.dev20221205-py3.10_cuda11.6_cudnn8_0.tar.bz2" --offline 

call conda update --all -c=nvidia -y -c pytorch -c defaults -c numba/label/dev 

python -c "import sys; print(sys.version)"
python -c "import torch; exit(0 if torch.backends.mkl.is_available() else 1)"
echo %errorlevel%
```

**Comment by Blackhex** [comment] 2022-12-09 14:16
@malfet I am still reproducing the smoke test fail locally with latest nightly artifact [https://github.com/pytorch/pytorch/suites/9741704388/artifacts/467788197](https://github.com/pytorch/pytorch/suites/9741704388/artifacts/467788197) but, obviously, on the CI it being executed and no longer failing [https://github.com/pytorch/pytorch/actions/runs/3655563715/jobs/6179466224#step:13:434.](https://github.com/pytorch/pytorch/actions/runs/3655563715/jobs/6179466224#step:13:434.) As it might be  some sorft of environmental issue, I'd close this ticket anyway.

**Comment by Blackhex** [comment] 2022-12-09 16:30
@malfet After upading the test script according to the changes in [https://github.com/pytorch/builder/pull/1218/files](https://github.com/pytorch/builder/pull/1218/files,):

```
set "CONDA_HOME=%CD%\windows\conda"

::curl -k https://repo.anaconda.com/miniconda/Miniconda3-latest-Windows-x86_64.exe -o "windows\miniconda.exe"

::start /wait "" "windows\miniconda.exe" /S /InstallationType=JustMe /RegisterPython=0 /AddToPath=0 /D=%CONDA_HOME%

set "CONDA_EXTRA_ARGS=pytorch-cuda=11.6 -c nvidia -c pytorch-nightly"
set "PATH=%CONDA_HOME%;%CONDA_HOME%\scripts;%CONDA_HOME%\Library\bin;%PATH%"
conda create -qyp "%CONDA_HOME%\testenv" python=3.10
call %CONDA_HOME%\condabin\activate.bat "%CONDA_HOME%\testenv"

call conda install -yq pytorch %CONDA_EXTRA_ARGS%

call conda install -yq "pytorch-1.14.0.dev20221208-py3.10_cuda11.6_cudnn8_0.tar.bz2" --offline

python -c "import sys; print(sys.version)"

python -c "import torch; print(torch.__version__)"
python -c "import torch; print(torch.backends.mkl.is_available())"
```

I no longer can reproduce the issue so the recent changes resolved it even if installing the full deployed nightly package (old one?) and then reinstalling it from the artifact (new one) seems quite suspicious to me - using `--only-deps` Conda flag would be better/faster (https://conda.io/projects/conda/en/latest/commands/install.html).

So, I guess, the issue can be closed.

**Closed** 2022-12-14 16:24 UTC
Labels: high priority, module: windows, module: ci, triaged, module: regression
