### ISSUE TITLE
Missing info in Tensorboard's add_graph()

### ISSUE THREAD

**Issue by Dudly01** [pytorch/pytorch#39667] opened 2020-06-08 18:31 UTC
## 📚 Documentation

The information regarding the [_add_graph()_ function in the Tensorboard doc](https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_graph) is empty. The missing info seems to be there in its [source](https://pytorch.org/docs/stable/_modules/torch/utils/tensorboard/writer.html#SummaryWriter.add_graph) tough. 

cc @jlin27

**Comment by pbelevich** [comment] 2020-06-09 00:41
@Dudly01 would you like to submit a pull request to fix it?

**Comment by Dudly01** [comment] 2020-06-09 18:57
@pbelevich I apologise but I am unsure what needs to be done exactly. The only thing I can think of is that the C api call should be moved after the docstring. And as the two lines of code before that belongs to it, i would move those as well.

Here is the part for saving a click to the docs:
```
def add_graph(self, model, input_to_model=None, verbose=False):
        # prohibit second call?
        # no, let tensorboard handle it and show its warning message.
        torch._C._log_api_usage_once("tensorboard.logging.add_graph")
        """Add graph data to summary.

        Args:
            model (torch.nn.Module): Model to draw.
            input_to_model (torch.Tensor or list of torch.Tensor): A variable or a tuple of
                variables to be fed.
            verbose (bool): Whether to print graph structure in console.
        """
```

**Comment by Dudly01** [comment] 2020-06-09 18:58
If that is the solution to it, then I could try to make a pull-request.

**Comment by pbelevich** [comment] 2020-06-12 17:08
@Dudly01, let's start from this, your PR will be reviewed and if anything is missing reviewers will help

**Comment by martinbrose** [comment] 2020-08-06 08:44
Duplicate of #37415

**Closed** 2020-08-06 22:07 UTC
Labels: module: docs, module: tensorboard, triaged, visualization
