### ISSUE TITLE
DataLoader, does not work with Hdf5 file when number

### ISSUE THREAD

**Issue by yunyundong** [pytorch/pytorch#11928] opened 2018-09-21 06:43 UTC
[https://discuss.pytorch.org/t/dataloader-when-num-worker-0-there-is-bug/25643](url)

We Hope developers can help us.
Many pepole has the problems, but there is no solution available.

**Comment by soumith** [comment] 2018-09-21 12:58
closing as duplicate of https://github.com/pytorch/pytorch/issues/11887 and https://github.com/pytorch/pytorch/issues/11929

h5py doesn't allow reading from multiple processes:
https://github.com/h5py/h5py/blob/master/examples/multiprocessing_example.py#L17-L21

**Closed by soumith** 2018-09-21 12:58 UTC
