### ISSUE TITLE
svd_lowrank support for complex-valued matrices

### ISSUE THREAD

**Issue by RafiqKamel** [pytorch/pytorch#125588] opened 2024-05-06 13:45 UTC
### 🚀 The feature, motivation and pitch

I propose adding support for complex-valued matrices in the svd_lowrank function. Currently, the function only supports real-valued matrices, but extending it to handle complex entries would benefit applications where complex matrices are prevalent. This feature would simplify workflows by allowing direct low-rank approximations of complex matrices.

cc @ezyang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved @amjames @jianyuh @pearu @walterddr @xwang233

**Comment by lezcano** [comment] 2024-05-06 16:14
Dupe of https://github.com/pytorch/pytorch/issues/122188

Luckily for you, I just put up today a PR adding this behaviour https://github.com/pytorch/pytorch/pull/125580. It should be ready soonish :)

**Closed by lezcano** 2024-05-06 16:14 UTC
Labels: triaged, module: complex, enhancement, module: linear algebra
