### ISSUE TITLE
Memory leak with Conv1d on CPU

### ISSUE THREAD

**Issue by tbelhalfaoui** [pytorch/pytorch#29809] opened 2019-11-14 15:02 UTC
## 🐛 Bug

When training (on CPU) a simple one-layer CNN (with variable-width batches, as it is standard in text classification), the memory usage increases significantly at each `forward` call, and quickly causes an out of memory.

## To Reproduce

```
import random
import torch
from torch import nn
from memory_profiler import profile

class DummyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.embed = nn.Embedding(500000, 100)
        self.conv = nn.Conv1d(100, 200, 3)

    def forward(self, x):
        x = self.embed(x)
        x = torch.transpose(x, 1, 2)
        x = self.conv(x)
        return torch.mean(x)


model = DummyModel()

@profile
def run():
    x = torch.randint(0, 500000, (300, random.randint(100, 3000)))
    model(x)

for i in range(20):
    run()
```

When running `python example.py`, I get this OOM error after 30 iterations:
```
RuntimeError: [enforce fail at CPUAllocator.cpp:64] . DefaultCPUAllocator: can't allocate memory: you tried to allocate 633120000 bytes. Error code 12 (Cannot allocate memory)
```

The [memory profiler output](https://github.com/pytorch/pytorch/files/3846948/memory_profiler_output.txt) clearly shows a steady memory increase (and never decrease) at each `model(x)` call, of **190Mb per call** on average.

## Expected behavior

I would expect the memory usage to increase slightly at the first step, but then stabilize - not increase linearly.

## Environment

PyTorch version: 1.3.1+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] torch==1.3.1+cpu
[conda] Could not collect

## Additional context

Here all the things I tested, following advice in the multiples related issues I found (https://github.com/pytorch/vision/issues/984, https://github.com/pytorch/pytorch/issues/5285 and others):

1. Check that there are no references to a model output kept accross iterations (e.g. loss)

2. Remove anything possible to narrow down the issue (data loader, tqdm, backward, optimization, ...). This is why I only kept the forward pass with dummy data.

3. Use `jemalloc` :
`LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1 python example.py` 
Same exact issue happens.

4. With random but fixed-size tensors (replacing `x = torch.randint(0, 500000, (300, random.randint(100, 3000)))` with `x = torch.randint(0, 500000, (300, 3000))`), the issue disappears.
However, I am doing CNN on text, so unfortunately, I need batches to have variable width...

5. It I remove the `model(x)` line, the issue disappears as well, so it is not a problem with the data generation itelf.

6. I tried the following Pytorch versions and had the exact same issue with all of them:
* `1.3.1+cpu` from pip (`pip install torch==1.3.1+cpu -f https://download.pytorch.org/whl/torch_stable.html`)
* `1.3.1` from pip (`pip install torch`)
* `1.3.1 cpuonly` from conda (`conda install pytorch cpuonly -c pytorch`)

cc @ezyang @gchanan @zou3519 @jerryzh168

**Comment by ailzhang** [comment] 2019-11-14 22:50
Hmmm this sounds like a weird issue (with the additional context 4 & 5). 
I'll mark this high priority to reproduce the reported behavior as a first step at least.

**Comment by ezyang** [comment] 2019-11-15 15:36
Might be #27971 or #25267.

**Comment by tbelhalfaoui** [comment] 2019-11-18 08:38
Wow, indeed, `LRU_CACHE_CAPACITY=1` (from https://github.com/pytorch/pytorch/issues/27971) solves my issue!

Thanks a lot for pointing out, @ezyang!

**Comment by ezyang** [comment] 2019-11-18 15:02
Thanks, I'm going to close this as a dupe, but this is defo high priority.

**Closed by ezyang** 2019-11-18 15:02 UTC
Labels: high priority, triage review
