### ISSUE TITLE
Pytorch profiler stack exporting does not work

### ISSUE THREAD

**Issue by ipoletaev** [pytorch/pytorch#95238] opened 2023-02-21 21:17 UTC
### 🐛 Description

While trying to export stacks to profile CUDA kernels runtime performance via exporting stacks directly following [public documentation](https://pytorch.org/tutorials/recipes/recipes/profiler_recipe.html#examining-stack-traces) one can easily find empty stacks file which is unexpected. To be more specific, the following code

```
with torch.profiler.profile(activities=[torch.profiler.ProfilerActivity.CUDA], with_stack=True) as prof:
      self._training_step(...)

prof.export_stacks("stacks.txt", "self_cuda_time_total")
```

saves nothing 

```
cat stacks.txt | wc -l
0
```

The `training_step` above is an arbitrary's model regular backpropagation step like:

```
...
loss = model(**X, **y).loss
optimizer.zero_grad()
loss.backward()
optimizer.step()
...
```

Notes:
 - Nonetheless profiler does look to be working, e.g. calling `print(prof.key_averages().table(sort_by="self_cuda_time_total",
                                    row_limit=10))` results into:
    <img width="1201" alt="vanilla_attn_bf_16_100fwdbkwd_steps" src="https://user-images.githubusercontent.com/14129555/220458397-51e62a9b-9881-4c6a-8d21-ba58fc9a2380.png">
 - [Similar issue reported just recently.](https://discuss.pytorch.org/t/pytorch-profiler-not-exporting-any-stack-information/167477)

### Versions

- Torch version: 1.13.1
- GPU: A100
- CUDA: 11.7 / Driver Version: 515.65.01
- OS: Ubuntu XX.YY

cc @robieta @chaekit @aaronenyeshi @ngimel @nbcsm @guotuofeng @guyang3532 @gaoteng-git @tiffzhaofb @dzhulgakov @davidberard98

**Comment by sraikund16** [comment] 2024-06-10 22:24
Closing as this is duplicate of #100253

**Closed by sraikund16** 2024-06-10 22:24 UTC
Labels: oncall: profiler
