### ISSUE TITLE
v1.7 requirement "dataclasses" is not compatible with python > 3.6

### ISSUE THREAD

**Issue by ccoulombe** [pytorch/pytorch#46930] opened 2020-10-27 18:03 UTC
## 🐛 Bug

v1.7 for Python 3.7 and 3.8 has requirement for `dataclasses` but it is not compatible with 3.7 and 3.8.
```
ERROR: Package 'dataclasses' requires a different Python: 3.7.7 not in '>=3.6, <3.7'
```
This result in not install torch.

Note :  `dataclasses` is part of Python 3.7 : https://docs.python.org/3.7/library/dataclasses.html

## To Reproduce
Install pytorch in a virtual env. freshly created. With python 3.7
```
(env) $ pip install ./torch-1.7.0-cp37-cp37m-linux_x86_64.whl
```

## Expected behavior

Install correctly without package dependency failing.

## Environment

 - PyTorch Version (e.g., 1.0): v1.7
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.7 and 3.8
 - CUDA/cuDNN version: 11
 - GPU models and configuration: - 
 - Any other relevant information: -

Please add a marker to requirement for python 3.6 only.
https://github.com/pytorch/pytorch/blob/bbe5bfaa4f5ec1d80cd971198e4abcfd2ea96a7a/requirements.txt#L8
should be:
```
dataclasses; python_version<"3.7"
```

cc @malfet @seemethere @walterddr

**Comment by seemethere** [comment] 2020-10-27 19:28
`dataclasses` shouldn't produce an issue like this since the wheel for dataclasses should work for any Python version

We did see issues though if users have a version of dataclasses installed prior to installing PyTorch.

We did resolve this in https://github.com/pytorch/pytorch/pull/45844, but it didn't make the cut for the release

I also haven't been able to reproduce this locally using fresh python environments either so I'm curious to how you ended up here.

**Comment by ccoulombe** [comment] 2020-10-27 19:30
the `dataclasses` on PyPI is a backport for 3.6 and says :
https://github.com/ericvsmith/dataclasses/blob/75b24ef6d01d6c7a728b7ce6228b66f14c25db4f/setup.py#L23

**Comment by seemethere** [comment] 2020-10-27 19:36
Even with that the regular wheels should still work since the `pip` resolver should pick the `dataclasses` version that's compatible with your version of python.

In a fresh minconda container with `python v3.7.6` and `pip v20.0.2` it resolves to pick `dataclasses v0.6` for me which is compatible with `python v3.7.6`:

```
$ docker run --rm -it continuumio/miniconda3 sh -c 'set -x;python --version;pip --version; pip install torch==1.7.0'
+ python --version
Python 3.7.6
+ pip --version
pip 20.0.2 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
+ pip install torch==1.7.0
Collecting torch==1.7.0
  Downloading torch-1.7.0-cp37-cp37m-manylinux1_x86_64.whl (776.7 MB)
     |████████████████████████████████| 776.7 MB 7.1 kB/s
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting numpy
  Downloading numpy-1.19.2-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 43.1 MB/s
Collecting typing-extensions
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 42.3 MB/s
Building wheels for collected packages: future
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=1667c8b2a30e6bd45077e7cb52db05347d27b26c6c48bc4cb4c783be1a4d8642
  Stored in directory: /root/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built future
Installing collected packages: dataclasses, numpy, typing-extensions, future, torch
Successfully installed dataclasses-0.6 future-0.18.2 numpy-1.19.2 torch-1.7.0 typing-extensions-3.7.4.3
```

As well doing a install of just `dataclasses` on `python v3.7.6` yields the same results:
```
docker run --rm -it continuumio/miniconda3 sh -c 'set -x;python --version;pip --version; pip install dataclasses'
+ python --version
Python 3.7.6
+ pip --version
pip 20.0.2 from /opt/conda/lib/python3.7/site-packages/pip (python 3.7)
+ pip install dataclasses
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Installing collected packages: dataclasses
Successfully installed dataclasses-0.6
```

**Comment by mboisson** [comment] 2020-10-27 19:40
please leave conda out of a python discussion

**Comment by ccoulombe** [comment] 2020-10-27 19:42
The latest version of  `dataclasses` is 0.7 and not 0.6.

**Comment by seemethere** [comment] 2020-10-27 19:47
> The latest version of `dataclasses` is 0.7 and not 0.6.

Even with that the `pip` resolver should pick up the latest version of `dataclasses` that works with your version of `python`

Here's a trial with the base `python:3.7` image:
```
❯ docker run --rm -it python:3.7 pip install dataclasses
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Installing collected packages: dataclasses
Successfully installed dataclasses-0.6
```

And for posterity here's the same command with `python:3.6`
```
❯ docker run --rm -it python:3.6 pip install dataclasses==0.7.0
Collecting dataclasses==0.7.0
  Downloading dataclasses-0.7-py3-none-any.whl (18 kB)
Installing collected packages: dataclasses
Successfully installed dataclasses-0.7
```

**Comment by mboisson** [comment] 2020-10-27 19:49
What version of pip is that ?

**Comment by seemethere** [comment] 2020-10-27 19:51
Should be `pip v20.2.4` for both of those

**Comment by mboisson** [comment] 2020-10-27 19:53
It seems like `pip` is not resolving correctly when using `--find-links`  (which is in our default config).

**Comment by ccoulombe** [comment] 2020-10-27 19:54
Indeed it should, we are looking into this pip issue on our end but the requirements should still be marked for python 3.6

**Comment by mboisson** [comment] 2020-10-27 19:55
```(venv3.8) [mboisson@build-node ~]$ ls /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/dataclasses*
/cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/dataclasses-0.6-py3-none-any.whl  /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/dataclasses-0.7-py3-none-any.whl
(venv3.8) [mboisson@build-node ~]$ pip install --find-links /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic dataclasses
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Processing /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic/dataclasses-0.7-py3-none-any.whl
ERROR: Package 'dataclasses' requires a different Python: 3.8.2 not in '>=3.6, <3.7'
(venv3.8) [mboisson@build-node ~]$ pip install dataclasses
Collecting dataclasses
  Using cached dataclasses-0.6-py3-none-any.whl (14 kB)
Installing collected packages: dataclasses
Successfully installed dataclasses-0.6```

**Comment by seemethere** [comment] 2020-10-27 19:56
> It seems like `pip` is not resolving correctly when using `--find-links` (which is in our default config).

Couldn't reproduce with `--find-links` either when trying to install from download.pytorch.org 😕 

```
❯ docker run --rm -it python:3.7 sh -c 'pip install --find-links https://download.pytorch.org/whl/torch_stable.html torch==1.7.0+cpu'
Looking in links: https://download.pytorch.org/whl/torch_stable.html
Collecting torch==1.7.0+cpu
  Downloading https://download.pytorch.org/whl/cpu/torch-1.7.0%2Bcpu-cp37-cp37m-linux_x86_64.whl (159.3 MB)
     |████████████████████████████████| 159.3 MB 47.3 MB/s
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting numpy
  Downloading numpy-1.19.2-cp37-cp37m-manylinux2010_x86_64.whl (14.5 MB)
     |████████████████████████████████| 14.5 MB 2.4 MB/s
Collecting typing-extensions
  Downloading typing_extensions-3.7.4.3-py3-none-any.whl (22 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
     |████████████████████████████████| 829 kB 50.6 MB/s
Building wheels for collected packages: future
  Building wheel for future (setup.py) ... done
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491059 sha256=23011f8d880542aab3a8493a0677630fc6d24fb82fa45746b5c48b86da71063c
  Stored in directory: /root/.cache/pip/wheels/56/b0/fe/4410d17b32f1f0c3cf54cdfb2bc04d7b4b8f4ae377e2229ba0
Successfully built future
Installing collected packages: dataclasses, numpy, typing-extensions, future, torch
Successfully installed dataclasses-0.6 future-0.18.2 numpy-1.19.2 torch-1.7.0+cpu typing-extensions-3.7.4.3
```

**Comment by mboisson** [comment] 2020-10-27 19:57
So, there is a bug in both `pip` and in the requirements file for torch.   (and arguably, in `dataclasses`... it makes no sense to introduce new development for python 3.6 only...)

**Comment by seemethere** [comment] 2020-10-27 20:00
Sure, going to consider this one closed since I cannot reliably reproduce it, feel free to continue the discussion and if we find that this is a serious issue for a majority of users we can re-open.

Thanks for filing the issue and the discussion!

**Comment by mboisson** [comment] 2020-10-27 20:01
Why not update the `requirements.txt` file for pytorch  as suggested by Charles ?

**Closed by seemethere** 2020-10-27 20:00 UTC
Labels: module: build, releng, triaged

**Comment by ccoulombe** [comment] 2020-10-27 20:09
As stated earlier, the requirements.txt should still be updated. I've even made the PR ;)
Any reason to keep a deprecated requirement for python 3.7 and up?

**Comment by seemethere** [comment] 2020-10-27 20:36
Currently shipping your PR @ccoulombe

**Comment by ccoulombe** [comment] 2020-10-27 20:38
Great! :+1:

**Comment by lemondante** [comment] 2020-10-31 16:06
Sorry, emmm...I have the same problem...
ERROR: Package 'dataclasses' requires a different Python: 3.7.0 not in '>=3.6, <3.7'
Is there any simple solution to help me install pytorch?

**Comment by ccoulombe** [comment] 2020-10-31 17:04
@lemondante 
You can patch the wheel to remove the requirement in the metadata.
Or install it in two steps from the latest requirements (or manually) : 
```
pip install -r https://raw.githubusercontent.com/pytorch/pytorch/master/requirements.txt
pip install <torch_wheel> --no-deps
```

**Comment by pdxjohnny** [comment] 2020-11-05 19:06
@ccoulombe dataclasses 0.6 is not compatible with Python 3.7+, it's just that dataclasses pypi releases prior to 0.7 did not have the `python_requires` version specifier in it's `setup.py`. The fix implemented in https://github.com/pytorch/pytorch/commit/dc53eefd256ad0110fae098be96d403ae7b85a97 is incomplete, see: https://github.com/ericvsmith/dataclasses/issues/153 (reproduced below)

> With the new py version restriction, pip will now as a result install dataclasses 0.6 if install is attempted on py37, since this is the last available version that satisfies this constraint. This might be a problem, since it shadows the builtin version. The reason this comes up is packaging a module the depends on dataclasses, but only python>=3.6, becomes tricky to do correctly. I believe the correct line is:
> 
> ```
> dataclasses>='0.7';python_version<'3.7'
> ```
> 
> Ideally, I think it would be nice if this dataclasses module simply returns the builtin python module if it's available (although I'm not sure how to implement that in practice!) If this isn't possible/desirable, perhaps you could add to the readme/docs something about how to install only on python<3.7 (e.g. using the above line)?

If dataclasses is installed on Python >= 3.7, the following exception is raised:

```
2020-11-03T19:28:37.0941617Z   File "/usr/share/miniconda/lib/python3.7/site-packages/dataclasses.py", line 958, in dataclass
2020-11-03T19:28:37.0943155Z     return wrap(_cls)
2020-11-03T19:28:37.0945139Z   File "/usr/share/miniconda/lib/python3.7/site-packages/dataclasses.py", line 950, in wrap
2020-11-03T19:28:37.0946856Z     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)
2020-11-03T19:28:37.0949297Z   File "/usr/share/miniconda/lib/python3.7/site-packages/dataclasses.py", line 801, in _process_class
2020-11-03T19:28:37.0950864Z     for name, type in cls_annotations.items()]
2020-11-03T19:28:37.0952995Z   File "/usr/share/miniconda/lib/python3.7/site-packages/dataclasses.py", line 801, in <listcomp>
2020-11-03T19:28:37.0954526Z     for name, type in cls_annotations.items()]
2020-11-03T19:28:37.0956630Z   File "/usr/share/miniconda/lib/python3.7/site-packages/dataclasses.py", line 659, in _get_field
2020-11-03T19:28:37.0958026Z     if (_is_classvar(a_type, typing)
2020-11-03T19:28:37.0959965Z   File "/usr/share/miniconda/lib/python3.7/site-packages/dataclasses.py", line 550, in _is_classvar
2020-11-03T19:28:37.0961517Z     return type(a_type) is typing._ClassVar
2020-11-03T19:28:37.0962446Z AttributeError: module 'typing' has no attribute '_ClassVar'
```

This is because `_ClassVar` was renamed to `ClassVar` in 3.7. To avoid this issue, we need to be sure that the dataclasses=>0.7 is listed in the requirements.txt

**Comment by pdxjohnny** [comment] 2020-11-05 19:29
Alright I give up with the damn CLA, can someone else please do this

**Comment by mboisson** [comment] 2020-11-05 19:35
I'm not entirely sure what needs to happen, but we have pretty complex examples of requirements specification in this file : 
https://github.com/ComputeCanada/easybuild-easyconfigs/blob/computecanada-master/easybuild/easyconfigs/s/SciPy-Stack/requirements-2020a.txt


so maybe I can help write the correct one if I'm told exactly what must happen.

**Comment by pdxjohnny** [comment] 2020-11-05 19:40
@mboisson It's really just the addition of `>="0.7"` to the dataclasses line of the `requirements.txt`. Which is what https://github.com/ericvsmith/dataclasses/issues/153 is telling us.

```diff
diff --git a/requirements.txt b/requirements.txt
index 759baf3..6aadce4 100644
--- a/requirements.txt
+++ b/requirements.txt
@@ -5,4 +5,4 @@ requests
 setuptools
 six
 typing_extensions
-dataclasses; python_version<"3.7"
+dataclasses>="0.7";python_version<"3.7"
```

**Comment by ccoulombe** [comment] 2020-11-05 20:06
`dataclasses` is part of python 3.7+ (https://docs.python.org/3.7/library/dataclasses.html), the requirements says to install the backport for py3.6 or a universal version that is compatible for a python under 3.7. If you installed `dataclasses` in python 3.7+ it will effectively clashes.
Also, since it is now part of the default library, I believe that `0.7` will be the last version on PyPI.

**Comment by pdxjohnny** [comment] 2020-11-05 20:50
@ccoulombe Ah okay, sorry my bad, I was wrong. Thank you.

**Comment by Interstella12** [comment] 2020-11-11 03:46
met the same problem, I just do this "pip3.7 install dataclasses==0.6"

**Comment by willfrey** [comment] 2020-11-13 19:22
Would it be possible to do a 1.7.1 release on PyPI with this change? 🙏

**Comment by ccoulombe** [comment] 2020-11-13 19:27
@seemethere Can you close further commenting? The issue contains the fix :
https://github.com/pytorch/pytorch/issues/46930#issuecomment-719960757

**Comment by willfrey** [comment] 2020-11-13 19:29
@ccoulombe I'm using Poetry, so hacking around with `pip` isn't an ideal solution for me.

**Comment by willfrey** [comment] 2020-11-13 19:52
Pinning dataclasses to 0.6 worked as a workaround.
