### ISSUE TITLE
Good way to take inverse on large matrix

### ISSUE THREAD

**Issue by jerrybai1995** [pytorch/pytorch#16963] opened 2019-02-11 17:23 UTC
Hi!

I was wondering if there's any recommendation on how to compute the inverse of a relatively large matrix. I only need to call the `torch.inverse` once. However, I believe it's because of the MAGMA, I keep getting the following warning every time I call `torch.inverse` (which is annoying):
```
=========================================================================================
   WARNING batched routines are designed for small sizes. It might be better to use the
   Native/Hybrid classical routines if you want good performance.
=========================================================================================
```
After line profiling I found that `torch.inverse` is indeed the most inefficient part of the program; sometimes, using a scipy equivalent on CPU is faster.

An example code to reproduce this:
```
>>> a = torch.rand(2,3000,3000).cuda()
>>> b = torch.inverse(a)
# Warning should be here
```

**Comment by vishwakftw** [comment] 2019-02-11 17:35
Notwithstanding the overhead of slicing, I believe a neat way of doing this could be by using Schur complements. You can break the matrix into smaller matrices and perform the inverse on them, and finally stack them up appropriately.

Since MAGMA is brought into context, I am pasting the check that results in the warning being thrown:
```
if ( m >  2048 || n > 2048 ) {
    #ifndef MAGMA_NOWARNING
    printf("=========================================================================================\n"
           "   WARNING batched routines are designed for small sizes. It might be better to use the\n"
           "   Native/Hybrid classical routines if you want good performance.\n"
           "=========================================================================================\n");
    #endif
}
```

This is called from the `magma_dgetrf_batched` routine.

**Comment by jerrybai1995** [comment] 2019-02-11 17:38
Thanks @vishwakftw ! Schur complement is a great idea and I'll compare :-)

For the MAGMA, I traced to the same point that you posted above. However, I don't know how to turn it off as the program keeps yelling this warning...

**Comment by vishwakftw** [comment] 2019-02-11 17:42
One way to kill these warnings is to pass define the `MAGMA_NOWARNING`, but I believe this needs to be done while compiling MAGMA, and not PyTorch. I'll investigate this further. Thank you for reporting.

**Comment by vishwakftw** [comment] 2019-02-14 17:13
Hi @jerrybai1995, I think the only way to currently disable these warnings is to compile MAGMA from source while including `-DMAGMA_NOWARNING` in the list of flags passed to the C++ compiler. Perhaps, it would be better to have this enabled in when creating the binaries, to avoid such issues later on.

cc: @soumith

**Comment by fmassa** [comment] 2019-02-19 17:58
@vishwakftw can we dispatch to a different implementation depending on the size of the matrix / batch?

**Comment by vishwakftw** [comment] 2019-02-20 04:54
@fmassa there are no other implementations provided by other libraries. What we can do however, is to write up a Schur decomposition based algorithm for computing the inverses of large matrices.

**Comment by ngimel** [comment] 2021-08-17 17:56
Closing, warning is no longer present

**Closed by ngimel** 2021-08-17 17:56 UTC
Labels: triage review

**Comment by ZhangIceNight** [comment] 2022-07-21 02:44
This warning is still present when take inverse on large matrix

**Comment by Turakar** [comment] 2022-08-09 19:06
I can confirm that this warning still occurs.

**Comment by ry-jojo** [comment] 2022-10-04 14:03
confirm, the warning is still there. also for torch.linalg.cholesky(A)

**Comment by Turakar** [comment] 2022-10-04 14:25
The trick seems to be to use the CUDA 11.6 version of PyTorch

**Comment by Parskatt** [comment] 2022-11-28 17:59
Getting this warning on torch 1.13.0+cu116 :/

**Comment by noamelata** [comment] 2023-01-25 16:26
Has anyone found a way to suppress this warning?

**Comment by Parskatt** [comment] 2023-01-25 16:29
@noamelata for-loop works. There is also vmap (https://pytorch.org/tutorials/prototype/vmap_recipe.html) which might work.

**Comment by zwhou99** [comment] 2023-10-18 21:21
Even if I update to pytorch 2.1.0, it will still show this warning again and again, which is really annoying. Does anyone know how to close this warning?

**Comment by bosakstepan** [comment] 2024-12-20 14:57
The issues still persists, using PyTorch/2.3.0-foss-2023a-CUDA-12.3.0 and torchvision/0.18.0-foss-2023a-CUDA-12.3.0 .

**Comment by Yshuo-Li** [comment] 2024-12-28 16:18
The issues still persists
