### ISSUE TITLE
Using 'multiprocessing’ in PyTorch on Windows10 got error-``RuntimeError: Couldn’t open shared file mapping: <torch_13684_4004974554>, error code: <0>''

### ISSUE THREAD

**Issue by Di-Ma-S21** [pytorch/pytorch#63331] opened 2021-08-16 15:42 UTC
## 🐛 Bug
Hi,

I am currently running a PyTorch code on Windows10 using PyCharm. This code firstly utilised `DataLoader` function (`num_workers’=4) to load training data:

`train_loader = DataLoader(train_dset, batch_size, shuffle=True,
                                  num_workers=4, collate_fn=trim_collate)`

Then, in training process, it utilised a `for’ loop to load training data and train the model:

`for i, (v, norm_bb, q, target, _, _, bb, spa_adj_matrix,
                        sem_adj_matrix) in enumerate(train_loader):`

**Error:** I got the following error messages when running above `for’ loop:

`0%|          | 0/6934 [00:00<?, ?it/s]Traceback (most recent call last):
  File "E:\PyTorch_env\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\PyTorch_env\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "E:\PyTorch_env\lib\site-packages\torch\multiprocessing\reductions.py", line 286, in reduce_storage
    metadata = storage._share_filename_()
RuntimeError: Couldn't open shared file mapping: <torch_13684_4004974554>, error code: <0>
python-BaseException
Traceback (most recent call last):
  File "E:\PyTorch_env\lib\multiprocessing\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input
python-BaseException
  0%|          | 0/6934 [00:07<?, ?it/s]`

It seems that there are some issues with the `multiprocessing` function on Windows system. I have tried to put all the codes (including `def train()`) under `if__name__ == '__main__':`, but it didn't work-the same error message still existed. 

Could you please let me know if there are any possible solutions for this?

The environment settings:

1. Windows10, PyCharm
2. PyTorch v1.0.1, torchvision v0.2.2, Python 3.7.11
3. One GPU node

Many thanks!

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by Di-Ma-S21** [comment] 2021-08-17 21:45
To be more clearer, I would post all the codes:

`from os.path import join, exists
import argparse
from torch.utils.data import DataLoader, ConcatDataset, random_split
import random
import json

from dataset import Dictionary, VQAFeatureDataset, VisualGenomeFeatureDataset
from dataset import tfidf_from_questions
from dataset_cp_v2 import VQA_cp_Dataset, Image_Feature_Loader
from model.regat import build_regat
from config.parser import parse_with_config
from utils import trim_collate
from train import *

def parse_args():
    parser = argparse.ArgumentParser()
    '''
    For training logistics
    '''
    parser.add_argument('--epochs', type=int, default=20)
    parser.add_argument('--base_lr', type=float, default=1e-3)
    parser.add_argument('--lr_decay_start', type=int, default=15)
    parser.add_argument('--lr_decay_rate', type=float, default=0.25)
    parser.add_argument('--lr_decay_step', type=int, default=2)
    parser.add_argument('--lr_decay_based_on_val', action='store_true',
                        help='Learning rate decay when val score descreases')
    parser.add_argument('--grad_accu_steps', type=int, default=1)
    parser.add_argument('--grad_clip', type=float, default=0.25)
    parser.add_argument('--weight_decay', type=float, default=0)
    parser.add_argument('--batch_size', type=int, default=64)
    parser.add_argument('--output', type=str, default='saved_models/')
    parser.add_argument('--save_optim', action='store_true',
                        help='save optimizer')
    parser.add_argument('--log_interval', type=int, default=-1,
                        help='Print log for certain steps')
    parser.add_argument('--seed', type=int, default=-1, help='random seed')

    '''
    loading trained models
    '''
    parser.add_argument('--checkpoint', type=str, default="")

    '''
    For dataset
    '''
    parser.add_argument('--dataset', type=str, default='vqa',
                        choices=["vqa", "vqa_cp"])
    parser.add_argument('--data_folder', type=str, default='./data')
    parser.add_argument('--use_both', action='store_true',
                        help='use both train/val datasets to train?')
    parser.add_argument('--use_vg', action='store_true',
                        help='use visual genome dataset to train?')
    parser.add_argument('--adaptive', action='store_true',
                        help='adaptive or fixed number of regions')
    '''
    Model
    '''
    parser.add_argument('--relation_type', type=str, default='implicit',
                        choices=["spatial", "semantic", "implicit"])
    parser.add_argument('--fusion', type=str, default='mutan',
                        choices=["ban", "butd", "mutan"])
    parser.add_argument('--tfidf', action='store_true',
                        help='tfidf word embedding?')
    parser.add_argument('--op', type=str, default='c',
                        help="op used in tfidf word embedding")
    parser.add_argument('--num_hid', type=int, default=1024)
    '''
    Fusion Hyperparamters
    '''
    parser.add_argument('--ban_gamma', type=int, default=1, help='glimpse')
    parser.add_argument('--mutan_gamma', type=int, default=2, help='glimpse')
    '''
    Hyper-params for relations
    '''
    # hyper-parameters for implicit relation
    parser.add_argument('--imp_pos_emb_dim', type=int, default=64,
                        help='geometric embedding feature dim')

    # hyper-parameters for explicit relation
    parser.add_argument('--spa_label_num', type=int, default=11,
                        help='number of edge labels in spatial relation graph')
    parser.add_argument('--sem_label_num', type=int, default=15,
                        help='number of edge labels in \
                              semantic relation graph')

    # shared hyper-parameters
    parser.add_argument('--dir_num', type=int, default=2,
                        help='number of directions in relation graph')
    parser.add_argument('--relation_dim', type=int, default=1024,
                        help='relation feature dim')
    parser.add_argument('--nongt_dim', type=int, default=20,
                        help='number of objects consider relations per image')
    parser.add_argument('--num_heads', type=int, default=16,
                        help='number of attention heads \
                              for multi-head attention')
    parser.add_argument('--num_steps', type=int, default=1,
                        help='number of graph propagation steps')
    parser.add_argument('--residual_connection', action='store_true',
                        help='Enable residual connection in relation encoder')
    parser.add_argument('--label_bias', action='store_true',
                        help='Enable bias term for relation labels \
                              in relation encoder')

    # can use config files
    parser.add_argument('--config', help='JSON config files')

    args = parse_with_config(parser)
    return args

def train():

    args = parse_args()
    if not torch.cuda.is_available():
        raise ValueError("CUDA is not available," +
                         "this code currently only support GPU.")
    n_device = torch.cuda.device_count()
    print("Found %d GPU cards for training" % (n_device))
    device = torch.device("cuda")
    batch_size = args.batch_size * n_device

    torch.backends.cudnn.benchmark = True

    if args.seed != -1:
        print("Predefined randam seed %d" % args.seed)
    else:
        # fix seed
        args.seed = random.randint(1, 10000)
        print("Choose random seed %d" % args.seed)
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)

    if "ban" == args.fusion:
        fusion_methods = args.fusion + "_" + str(args.ban_gamma)
    else:
        fusion_methods = args.fusion

    # dictionary = Dictionary.load_from_file(
    #                 join(args.data_folder, 'glove/dictionary.pkl'))
    dictionary_path = os.path.join(args.data_folder, 'glove/dictionary.pkl')
    dictionary_path = os.path.normpath(dictionary_path)
    dictionary = Dictionary.load_from_file(dictionary_path)
    if args.dataset == "vqa_cp":
        coco_train_features = Image_Feature_Loader(
            'train', args.relation_type,
            adaptive=args.adaptive, dataroot=args.data_folder)
        coco_val_features = Image_Feature_Loader(
            'val', args.relation_type,
            adaptive=args.adaptive, dataroot=args.data_folder)
        val_dset = VQA_cp_Dataset(
            'test', dictionary, coco_train_features, coco_val_features,
            adaptive=args.adaptive, pos_emb_dim=args.imp_pos_emb_dim,
            dataroot=args.data_folder)
        train_dset = VQA_cp_Dataset(
            'train', dictionary, coco_train_features,
            coco_val_features, adaptive=args.adaptive,
            pos_emb_dim=args.imp_pos_emb_dim,
            dataroot=args.data_folder)
    else:
        val_dset = VQAFeatureDataset(
            'val', dictionary, args.relation_type, adaptive=args.adaptive,
            pos_emb_dim=args.imp_pos_emb_dim, dataroot=args.data_folder)
        train_dset = VQAFeatureDataset(
            'train', dictionary, args.relation_type,
            adaptive=args.adaptive, pos_emb_dim=args.imp_pos_emb_dim,
            dataroot=args.data_folder)

    model = build_regat(val_dset, args).to(device)

    tfidf = None
    weights = None
    if args.tfidf:
        tfidf, weights = tfidf_from_questions(['train', 'val', 'test2015'],
                                              dictionary, dataroot=args.data_folder)
    model.w_emb.init_embedding(join(args.data_folder,
                                    'glove/glove6b_init_300d.npy'),
                               tfidf, weights)

    #model = nn.DataParallel(model).to(device)

    if args.checkpoint != "":
        print("Loading weights from %s" % (args.checkpoint))
        if not os.path.exists(args.checkpoint):
            raise ValueError("No such checkpoint exists!")
        checkpoint = torch.load(args.checkpoint)
        state_dict = checkpoint.get('model_state', checkpoint)
        matched_state_dict = {}
        unexpected_keys = set()
        missing_keys = set()
        for name, param in model.named_parameters():
            missing_keys.add(name)
        for key, data in state_dict.items():
            if key in missing_keys:
                matched_state_dict[key] = data
                missing_keys.remove(key)
            else:
                unexpected_keys.add(key)
        print("Unexpected_keys:", list(unexpected_keys))
        print("Missing_keys:", list(missing_keys))
        model.load_state_dict(matched_state_dict, strict=False)

    # use train & val splits to optimize, only available for vqa, not vqa_cp
    if args.use_both and args.dataset == "vqa":
        length = len(val_dset)
        trainval_concat_dset = ConcatDataset([train_dset, val_dset])
        if args.use_vg or args.use_visdial:
            trainval_concat_dsets_split = random_split(
                trainval_concat_dset,
                [int(0.2 * length),
                 len(trainval_concat_dset) - int(0.2 * length)])
        else:
            trainval_concat_dsets_split = random_split(
                trainval_concat_dset,
                [int(0.1 * length),
                 len(trainval_concat_dset) - int(0.1 * length)])
        concat_list = [trainval_concat_dsets_split[1]]

        # use a portion of Visual Genome dataset
        if args.use_vg:
            vg_train_dset = VisualGenomeFeatureDataset(
                'train', train_dset.features, train_dset.normalized_bb,
                train_dset.bb, train_dset.spatial_adj_matrix,
                train_dset.semantic_adj_matrix, dictionary,
                adaptive=train_dset.adaptive,
                pos_boxes=train_dset.pos_boxes,
                dataroot=args.data_folder)
            vg_val_dset = VisualGenomeFeatureDataset(
                'val', val_dset.features, val_dset.normalized_bb,
                val_dset.bb, val_dset.spatial_adj_matrix,
                val_dset.semantic_adj_matrix, dictionary,
                adaptive=val_dset.adaptive,
                pos_boxes=val_dset.pos_boxes,
                dataroot=args.data_folder)
            concat_list.append(vg_train_dset)
            concat_list.append(vg_val_dset)
        final_train_dset = ConcatDataset(concat_list)
        final_eval_dset = trainval_concat_dsets_split[0]
        train_loader = DataLoader(final_train_dset, batch_size, shuffle=True,
                                  num_workers=1, collate_fn=trim_collate)
        eval_loader = DataLoader(final_eval_dset, batch_size,
                                 shuffle=False, num_workers=1,
                                 collate_fn=trim_collate)

    else:
        train_loader = DataLoader(train_dset, batch_size, shuffle=True,
                                  num_workers=2, collate_fn=trim_collate)
        eval_loader = DataLoader(val_dset, batch_size, shuffle=False,
                                 num_workers=2, collate_fn=trim_collate)

    output_meta_folder = join(args.output, "regat_%s" % args.relation_type)
    utils.create_dir(output_meta_folder)
    args.output = output_meta_folder + "/%s_%s_%s_%d" % (
        fusion_methods, args.relation_type,
        args.dataset, args.seed)
    if exists(args.output) and os.listdir(args.output):
        raise ValueError("Output directory ({}) already exists and is not "
                         "empty.".format(args.output))
    utils.create_dir(args.output)
    with open(join(args.output, 'hps.json'), 'w') as writer:
        json.dump(vars(args), writer, indent=4)
    logger = utils.Logger(join(args.output, 'log.txt'))

    # train(model, train_loader, eval_loader, args, device)
    N = len(train_loader.dataset)
    lr_default = args.base_lr
    num_epochs = args.epochs
    lr_decay_epochs = range(args.lr_decay_start, num_epochs,
                            args.lr_decay_step)
    gradual_warmup_steps = [0.5 * lr_default, 1.0 * lr_default,
                            1.5 * lr_default, 2.0 * lr_default]

    optim = torch.optim.Adamax(filter(lambda p: p.requires_grad,
                                      model.parameters()),
                               lr=lr_default, betas=(0.9, 0.999), eps=1e-8,
                               weight_decay=args.weight_decay)

    logger = utils.Logger(os.path.join(args.output, 'log.txt'))
    best_eval_score = 0

    utils.print_model(model, logger)
    logger.write('optim: adamax lr=%.4f, decay_step=%d, decay_rate=%.2f,'
                 % (lr_default, args.lr_decay_step,
                    args.lr_decay_rate) + 'grad_clip=%.2f' % args.grad_clip)
    logger.write('LR decay epochs: ' + ','.join(
        [str(i) for i in lr_decay_epochs]))
    last_eval_score, eval_score = 0, 0
    relation_type = train_loader.dataset.relation_type

    for epoch in range(0, num_epochs):
        pbar = tqdm(total=len(train_loader))
        total_norm, count_norm = 0, 0
        total_loss, train_score = 0, 0
        count, average_loss, att_entropy = 0, 0, 0
        t = time.time()
        if epoch < len(gradual_warmup_steps):
            for i in range(len(optim.param_groups)):
                optim.param_groups[i]['lr'] = gradual_warmup_steps[epoch]
            logger.write('gradual warmup lr: %.4f' %
                         optim.param_groups[-1]['lr'])
        elif (epoch in lr_decay_epochs or
              eval_score < last_eval_score and args.lr_decay_based_on_val):
            for i in range(len(optim.param_groups)):
                optim.param_groups[i]['lr'] *= args.lr_decay_rate
            logger.write('decreased lr: %.4f' % optim.param_groups[-1]['lr'])
        else:
            logger.write('lr: %.4f' % optim.param_groups[-1]['lr'])
        last_eval_score = eval_score

        mini_batch_count = 0
        batch_multiplier = args.grad_accu_steps

        for i, (v, norm_bb, q, target, _, _, bb, spa_adj_matrix,
                sem_adj_matrix) in enumerate(train_loader, 0):
            batch_size = v.size(0)
            num_objects = v.size(1)
            if mini_batch_count == 0:
                optim.step()
                optim.zero_grad()
                mini_batch_count = batch_multiplier

            v = Variable(v).to(device)
            norm_bb = Variable(norm_bb).to(device)
            q = Variable(q).to(device)
            target = Variable(target).to(device)
            pos_emb, sem_adj_matrix, spa_adj_matrix = prepare_graph_variables(
                relation_type, bb, sem_adj_matrix, spa_adj_matrix, num_objects,
                args.nongt_dim, args.imp_pos_emb_dim, args.spa_label_num,
                args.sem_label_num, device)
            pred, att = model(v, norm_bb, q, pos_emb, sem_adj_matrix,
                              spa_adj_matrix, target)
            loss = instance_bce_with_logits(pred, target)

            loss /= batch_multiplier
            loss.backward()
            mini_batch_count -= 1
            total_norm += nn.utils.clip_grad_norm_(model.parameters(),
                                                   args.grad_clip)
            count_norm += 1
            batch_score = compute_score_with_logits(pred, target, device).sum()
            total_loss += loss.data.item() * batch_multiplier * v.size(0)
            train_score += batch_score
            pbar.update(1)

            if args.log_interval > 0:
                average_loss += loss.data.item() * batch_multiplier
                if model.module.fusion == "ban":
                    current_att_entropy = torch.sum(calc_entropy(att.data))
                    att_entropy += current_att_entropy / batch_size / att.size(1)
                count += 1
                if i % args.log_interval == 0:
                    att_entropy /= count
                    average_loss /= count
                    print("step {} / {} (epoch {}), ave_loss {:.3f},".format(
                        i, len(train_loader), epoch,
                        average_loss),
                        "att_entropy {:.3f}".format(att_entropy))
                    average_loss = 0
                    count = 0
                    att_entropy = 0

        total_loss /= N
        train_score = 100 * train_score / N
        if eval_loader is not None:
            eval_score, bound, entropy = evaluate(
                model, eval_loader, device, args)

        logger.write('epoch %d, time: %.2f' % (epoch, time.time() - t))
        logger.write('\ttrain_loss: %.2f, norm: %.4f, score: %.2f'
                     % (total_loss, total_norm / count_norm, train_score))
        if eval_loader is not None:
            logger.write('\teval score: %.2f (%.2f)'
                         % (100 * eval_score, 100 * bound))

            if entropy is not None:
                info = ''
                for i in range(entropy.size(0)):
                    info = info + ' %.2f' % entropy[i]
                logger.write('\tentropy: ' + info)
        if (eval_loader is not None) \
                or (eval_loader is None and epoch >= args.saving_epoch):
            logger.write("saving current model weights to folder")
            model_path = os.path.join(args.output, 'model_%d.pth' % epoch)
            opt = optim if args.save_optim else None
            utils.save_model(model_path, model, epoch, opt)

if __name__ == '__main__':

    train()
`

Would appreciate any help. Thanks!

**Comment by peterjc123** [comment] 2021-08-18 01:16
Hey, I want to say something about this issue.
First, the PyTorch you are using is pretty old. Would you please try a newer version like 1.8 or 1.9?
Second, the code you provided is incomplete and verbose. Could you please send a minimal reproducible code example?

**Comment by Di-Ma-S21** [comment] 2021-08-20 12:09
> Hey, I want to say something about this issue.
> First, the PyTorch you are using is pretty old. Would you please try a newer version like 1.8 or 1.9?
> Second, the code you provided is incomplete and verbose. Could you please send a minimal reproducible code example?

@peterjc123 Hi Peter, thanks for your suggestions. I have upgraded the PyTorch to a latest version-but it still could not work. Yeah, I am going to provide a minimal reproducible code example.

**Comment by vladimir-aubrecht** [comment] 2022-11-04 16:35
@Di-Ma-S21 did you manage to solve the issue at the end? 😊

**Comment by vladimir-aubrecht** [comment] 2023-01-05 14:10
Closing issue as we are unable to reproduce it, we do not have means to collect minimal reproducible code example for more than a year and @Di-Ma-S21 seems not active anymore on GitHub.

@Di-Ma-S21 if you'll get back to this, feel free to open new issue with minimal reproducible code example.

**Closed by vladimir-aubrecht** 2023-01-05 14:10 UTC
Labels: module: windows, module: multiprocessing, triaged

**Comment by mszhanyi** [comment] 2023-01-06 03:30
may be duplicated with https://github.com/pytorch/pytorch/issues/67844.
Make sure producer process running until all consumers exits.
