### ISSUE TITLE
RuntimeError: ONNX export failed: Couldn't export operator aten::softmax

### ISSUE THREAD

**Issue by Dreamgang** [pytorch/pytorch#20643] opened 2019-05-17 12:42 UTC
### Please note that this issue tracker is not a help form and this issue will be closed.
Currently I am facing the errorRuntimeError: ONNX export failed: Couldn't export operator aten::softmax  According to the folks at ONNX, this is a bug in PyTorch

**Comment by Kirayue** [comment] 2019-05-20 03:21
Is there any update?

**Comment by houseroad** [comment] 2019-05-20 22:14
@Dreamgang could you provide a script to reproduce the problem?

**Comment by jasonlovescoding** [comment] 2019-05-21 07:14
@houseroad I've got the same problem here. It happens when you pass a non-2D tensor to a softmax layer. For instance,
```
class test(nn.Module):

    def __init__(self):
        super(test, self).__init__()

    def forward(self, x):
        return F.softmax(x, dim=1)
```
will reproduce this problem when you pass in a tensor of shape [1,3,224,224]

**Comment by Jason-xin** [comment] 2019-06-11 11:18
@jasonlovescoding Have you solved this problems? I changed dim=-1 and it works, but I was not sure whether the result was the same or not?

**Comment by spandantiwari** [comment] 2019-06-14 00:52
@jasonlovescoding @Dreamgang - I tried the repro steps above in the latest PyTorch master and I see the export happen without issues. Below's what the ONNX graph looks like. Could you let us know which version of PyTorch are you using?
![Softmax_ONNX_Export](https://user-images.githubusercontent.com/23646532/59476067-d9b3dc00-8e03-11e9-87d2-d72ccec104e9.png)

**Comment by Dreamgang** [comment] 2019-06-14 09:23
> @jasonlovescoding @Dreamgang - I tried the repro steps above in the latest PyTorch master and I see the export happen without issues. Below's what the ONNX graph looks like. Could you let us know which version of PyTorch are you using?
> ![Softmax_ONNX_Export](https://user-images.githubusercontent.com/23646532/59476067-d9b3dc00-8e03-11e9-87d2-d72ccec104e9.png)

my Pytorch version is 0.4.1

**Comment by spandantiwari** [comment] 2019-06-14 21:02
@Dreamgang - there have been many updates to the PyTorch-ONNX exporter since 0.4.1. Could you please try this in the latest version. Thanks.

**Comment by vadimkantorov** [comment] 2019-11-25 06:03
I've just encountered the same issue. I have a BCT tensor, and log_softmax is done across dim=1. A similar problem is reported in https://discuss.pytorch.org/t/converting-log-softmax-layer-into-onnx-format/40607

**Comment by vadimkantorov** [comment] 2019-11-25 11:51
possibly related https://github.com/pytorch/pytorch/issues/17918

**Comment by LexGrishin** [comment] 2020-01-12 17:30
I've got the same issue with torch.nn.LogSoftmax(dim=1).

**Comment by finnyang** [comment] 2020-01-15 01:37
I get the same issue with torch.nn.Softmax(dim=1) too!

**Comment by jeremycochoy** [comment] 2020-01-31 20:09
Using the current master version of https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py solved my issue.

I just copied the file on top of the v1.4.0 distribution. Very dirty, but for temporary machines (google colab) it does the job.

**Comment by amichayfeld** [comment] 2020-02-23 14:56
> Using the current master version of https://github.com/pytorch/pytorch/blob/master/torch/onnx/symbolic_opset9.py solved my issue.
> 
> I just copied the file on top of the v1.4.0 distribution. Very dirty, but for temporary machines (google colab) it does the job.

I tried to do this and got same error:

> error: (-2:Unspecified error) Can't create layer "57" of type "Exp" in function 'getLayerInstance'

>

**Comment by dulex123** [comment] 2020-02-27 12:51
Is there a fix for this?

**Comment by spandantiwari** [comment] 2020-02-27 18:03
Are you all seeing this issue in latest version of PyTorch? If you haven't tried, I would recommend trying it out. Let us know if you still see this issue.

**Comment by dulex123** [comment] 2020-02-28 12:58
@spandantiwari yes, 1.4.0

**Comment by spandantiwari** [comment] 2020-02-28 17:57
@dulex123 - I am not able to repro this. I just tried the master branch from a week ago and I was able to export softmax (repro code at the top) correctly. I am not sure why you are seeing an issue. To help investigate, could you please try using the latest nightly build from pytorch.org? If you still see this issue, please share the exact repro code you are using.

**Comment by saonianajian** [comment] 2020-04-03 01:33
Maybe the torch version is too low.
The torch version I used before 1.0.0 and encountered the same problem. Later, I updated the torch version to 1.4.0, and this problem did not appear.

**Comment by antimora** [comment] 2020-04-08 03:32
@saonianajian I have 1.4 but also facing the issue when exporting to ONNX format. 

This is the pytorch version: 
''''
__version__ = '1.4.0'
debug = False
cuda = '10.1'
git_version = '7f73f1d591afba823daa4a99a939217fb54d7688'
hip = None
'''

This is ONNX debug output:
'''
  %645 : Long() = onnx::Constant[value={1}]()
  %646 : None = prim::Constant()
  %647 : Float(1, 41, 40, 1) = aten::log_softmax(%644, %645, %646) # /home/pytorch/.local/lib/python3.6/site-packages/torch/nn/functional.py:1317:0
  %648 : Float(1, 41, 40) = onnx::Squeeze[axes=[3]](%647) 
  %649 : Float(1, 40, 41) = onnx::Transpose[perm=[0, 2, 1]](%648) 
  return (%649, %638)

''''

This is how LogSoftmax is initialized: 

```

nn.LogSoftmax(dim=1)

```

**Comment by saonianajian** [comment] 2020-04-08 08:25
@antimora 
May be ONNX export mechanism not supported nn.LogSoftmax(dim=1).
I think you can replace "nn.LogSoftmax(dim=1)" with the following code,and retraining the network.
`import torch.nn.functional as F
F.log_softmax(dim=1)`
After retraining,you can try exporting to ONNX format again,may be it did.

**Comment by tomsal** [comment] 2020-04-09 17:00
I have the same issue on pytorch 1.4.0. Replacing `nn.LogSoftmax(dim=1)` by `F.log_softmax(input, 1)` as suggested by @saonianajian did not work for me. However, I did not retrain, since I am loading the model from a pth file and want to export to onnx. But I guess that retraining would make a difference.
What did work for me is using `nn.Softmax(dim=1)` in combination with `torch.log`. For reasons stated [here](https://pytorch.org/docs/stable/nn.functional.html#torch.nn.functional.log_softmax), this should not be a longterm solution, though. I haven't checked yet whether this affects my results.

**Comment by vadimkantorov** [comment] 2020-04-09 17:14
@tomsal Could you try using a nightly version of PyTorch?

**Comment by tomsal** [comment] 2020-04-09 17:31
I just checked the nightly version! There it works fine!

**Closed** 2020-10-21 22:14 UTC
Labels: module: onnx, triaged
