### ISSUE TITLE
Metal performance shader topk not working after torch.topk>15

### ISSUE THREAD

**Issue by machineko** [pytorch/pytorch#83656] opened 2022-08-18 07:48 UTC
### 🐛 Describe the bug

torch.topk is not working properly when k value is bigger than 15 minimum example under

```python
import torch
a = torch.randn(1, 2400, 1200)

a1 = torch.topk(input=a, k=15)
a2 = torch.topk(input=a, k=20)

a1mps = torch.topk(input=a.to("mps"), k=15) # working fine
a2mps = torch.topk(input=a.to("mps"), k=20) # not working at all

print(torch.allclose(a1mps[0].to("cpu"), a1[0])) # True
print(torch.allclose(a2mps[0].to("cpu"), a2[0])) # False

print(a2mps[0,0]) # last 5 values are always 0 not proper top sorted values values
print(a2[0,0]). # last values are fine
```

### Versions

```
[pip3] coreml_pytorch_utils==0.1.2
[pip3] msgpack-numpy==0.4.8
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.1
[pip3] torch==1.12.0
[pip3] torch-flatbuffers==0.1.0
[pip3] torchaudio==0.14.0.dev20220603
[pip3] torchvision==0.14.0a0+f9f721d
```

cc @kulinseth @albanD

**Comment by albanD** [comment] 2022-08-18 15:45
Closing as duplicate of https://github.com/pytorch/pytorch/issues/78915

**Closed by albanD** 2022-08-18 15:45 UTC
Labels: triaged, module: mps
