### ISSUE TITLE
Apex Amp causes model to fail tracing with a strange error

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#40910] opened 2020-07-02 11:37 UTC
I have a DenseNet-like model for speech recognition (https://arxiv.org/abs/1904.03288). My code:  https://github.com/vadimkantorov/convasr/blob/master/models.py#L94

When I export it to ONNX as is, everything works okay. When I apply `model = apex.amp.initialize(model, opt_level = 'O3')` prior to export (basically to have model params converted to float16 and have input/output casts from float32), I get this:

`RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient`

The error is really strange.

When I cast model parameters to float16 manually and have input cast to float16 manually, I have this bug instead: https://github.com/microsoft/onnxruntime/issues/4405

Full stack trace:

```
Traceback (most recent call last):
  File "train.py", line 383, in <module>
    main(parser.parse_args())
  File "train.py", line 72, in main
    torch.onnx.export(model, (waveform_input,), args.onnx, opset_version = args.onnx_opset, export_params = args.onnx_export_params, do_constant_folding = True, input_names = ['x'], output_names = ['logits'], dynamic_axes = dict(x = {0 : 'B', 1 : 'T'}, logits = {0 : 'B', 2: 't'}))
  File "/miniconda/lib/python3.7/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/miniconda/lib/python3.7/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/miniconda/lib/python3.7/site-packages/torch/onnx/utils.py", line 416, in _export
    fixed_batch_size=fixed_batch_size)
  File "/miniconda/lib/python3.7/site-packages/torch/onnx/utils.py", line 279, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "/miniconda/lib/python3.7/site-packages/torch/onnx/utils.py", line 236, in _trace_and_get_graph_from_model
    trace_graph, torch_out, inputs_states = torch.jit._get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 272, in _get_trace_graph
    outs = ONNXTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 355, in forward
    self._force_outplace,
  File "/miniconda/lib/python3.7/site-packages/torch/jit/__init__.py", line 342, in wrapper
    outs.append(self.inner(*trace_inputs))
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/apex/amp/_initialize.py", line 197, in new_fwd
    **applier(kwargs, input_caster))
  File "/root/convasr/models.py", line 146, in forward
    x = subblock(x, residual = residual, lengths_fraction = xlen)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/root/convasr/models.py", line 74, in forward
    x = self.activation(bn(conv(x)), residual = residual_inputs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 530, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 516, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/miniconda/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 202, in forward
    self.padding, self.dilation, self.groups)
RuntimeError: Cannot insert a Tensor that requires grad as a constant. Consider making it a parameter or input, or detaching the gradient
```

cc @mcarilli @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by vadimkantorov** [comment] 2020-07-06 14:35
This is about Nvidia Apex that will probably become deprecated. I posted this issue mostly because it may indicate some JIT tracing / onnx export bug.

The error looks strange, and further, this all runs with `torch.set_grad_enabled(False)`, so not sure why "requiring grad" makes a difference at all. Also not sure what tensor ("Cannot insert a Tensor that requires grad as a constant") it refers to, since it fails inside convolution. Does it refer to convolution weight?

Does apex initialization change this kind of properties? Strange. I don't know if this affects new built-in autocast support as well.

**Comment by garymm** [comment] 2022-04-06 23:51
Closing as a duplicate of #50231 (even though this issue is older, the other issue makes it clear that the root cause is in the tracer, not ONNX export)

**Closed by garymm** 2022-04-06 23:51 UTC
Labels: module: onnx, triaged, module: amp (automated mixed precision)
