### ISSUE TITLE
Officially support torch._aminmax

### ISSUE THREAD

**Issue by frankseide** [pytorch/pytorch#62235] opened 2021-07-27 00:16 UTC
## 🚀 Feature
Could you please expose `torch._aminmax()` as an officially supported operation? Thanks!!

## Motivation

This operation is needed for hand-rolled runtime quantization. For example, we use it for a large recurrent model to save memory, by quantizing the state tensors to 8 bit. For that, we need to determine the numeric range on a per-tensor basis, which we do currently with `_aminmax()`. 

## Pitch

`torch._aminmax()` should become an officially supported API.

## Alternatives

The alternatives, besides using the internal API (which works fine!), are to use `max(abs())`, which creates a full temporary copy in memory, or run `max()` and `min()` separately, which requires two data passes.

**Comment by ngimel** [comment] 2021-07-27 05:43
Duplicate of #62164

**Closed by ngimel** 2021-07-27 05:43 UTC
