### ISSUE TITLE
Hash mismatch when installing torch

### ISSUE THREAD

**Issue by cloudy-sfu** [pytorch/pytorch#110847] opened 2023-10-09 05:49 UTC
### 🐛 Describe the bug

Installation:
```
pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 --no-cache-dir
```
Tried to follow [this solution](https://stackoverflow.com/questions/40183108/python-packages-hash-not-matching-whilst-installing-using-pip) to solve hash mismatch, therefore add `--no-cache-dir` option.

Response:
```
Looking in indexes: https://download.pytorch.org/whl/cu118
Collecting torch
  Downloading https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp311-cp311-linux_x86_64.whl (2325.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸━━━━ 2.1/2.3 GB 3.8 MB/s eta 0:01:04
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    torch from https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp311-cp311-linux_x86_64.whl#sha256=bcb17e2de6ca634d326203694d0bfb552587335e536c1917be3f28c5664b5506:
        Expected sha256 bcb17e2de6ca634d326203694d0bfb552587335e536c1917be3f28c5664b5506
             Got        f1a1a503fb72a82a21fcc46f9feb1b93c189f5744c64bc511963a055342ba644
```

### Versions

torch 2.1.0+cu118
Python 3.11
Ubuntu 22.04 LTS

cc @ezyang @gchanan @zou3519 @kadeng @seemethere @malfet @osalpekar @atalman

**Comment by malfet** [comment] 2023-11-06 18:42
Can't reproduce it on my end:
```
$ curl -OL https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp311-cp311-linux_x86_64.whl
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 2218M  100 2218M    0     0   342M      0  0:00:06  0:00:06 --:--:--  345M
(tmp-py311) nshulga@ip-10-200-84-248:~$ shasum -a 256 torch-2.1.0%2Bcu118-cp311-cp311-linux_x86_64.whl 
bcb17e2de6ca634d326203694d0bfb552587335e536c1917be3f28c5664b5506  torch-2.1.0%2Bcu118-cp311-cp311-linux_x86_64.whl
```

Which matches one specified in the index:
```
$ curl https://download.pytorch.org/whl/cu118/torch/|grep torch-2.1.0|grep cp311|grep linux
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 24450  100 24450    0     0   994k      0 --:--:-- --:--:-- --:--:--  994k
    <a href="/whl/cu118/torch-2.1.0%2Bcu118-cp311-cp311-linux_x86_64.whl#sha256=bcb17e2de6ca634d326203694d0bfb552587335e536c1917be3f28c5664b5506">torch-2.1.0+cu118-cp311-cp311-linux_x86_64.whl</a><br/>
```

**Comment by malfet** [comment] 2023-11-06 18:43
Closing, as it does not look like a problem with downloaded binaries

**Closed by malfet** 2023-11-06 18:43 UTC
Labels: high priority, module: binaries, triaged
