### ISSUE TITLE
RFC: Stop requiring OpInfos specify their dtypes

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#58292] opened 2021-05-14 05:25 UTC
This RFC is inspired by @eellison's suggestions for improving OpInfo usability here: https://github.com/pytorch/pytorch/issues/57577.

Today when writing an OpInfo the operator's supported dtypes must be explicitly specified, and if those dtypes vary across device types or on different versions of CUDA those variants must be specified, too. These dtype specifications can be simple or complicated, here's part of the addmm OpInfo as a complicated example:

```
OpInfo('addmm',
  ...
  dtypes=floating_and_complex_types_and(torch.float16),
  dtypesIfCPU=all_types_and_complex_and(torch.float16, torch.bfloat16),
  dtypesIfROCM=floating_and_complex_types_and(torch.float16, torch.bfloat16),
  dtypesIfCUDA=floating_and_complex_types_and(torch.float16, *[torch.bfloat16] if CUDA11OrLater else []),
```

Understanding which dtypes to specify can be tricky, sometimes requiring trial and error if the operation is composite, and if a user doesn't have access to a CUDA device then this requires trial and error with the PyTorch CI to set dtypes properly. Worse, setting dtypes may still require trial and error with PyTorch CI because different platforms may support different dtypes (like in the addmm case above).

A partial solution to this is to provide a tool that indicates which dtypes an operator supports, but that doesn't address the challenge of users who lack a CUDA device or when platform differences cause dtype differences.

One idea, then, is to let OpInfos specify that their dtypes should be programmatically determined by the test suite. This would change the above addmm OpInfo into something like:

```
OpInfo('addmm',
  ...
  dtypes=floating_and_complex_types_and(torch.float16, torch.bfloat16),
  dtypesIfCUDA=_PROGRAMMATIC,
```

And when the OpInfo was created it would run a test to determine the appropriate CUDA dtypes (which would be inherited by ROCm, too).

There are pros and cons to this change. Pros:

- it lets users without CUDA devices write OpInfos without going back and forth with CI
- it simplifies writing OpInfos where an operator's dtypes vary on different platforms

Cons:

- OpInfos using this pattern would no longer specify the dtypes an operator supports
- OpInfos using this pattern could have their supported dtypes change and there would be no test signal when that occurred

Overall I think the improved accessibility overweighs the cons, and we can always replace `_PROGRAMMATIC` or `_DYNAMIC` or whatever we call it with an actual list of dtypes later if we prefer it.

Please share your thoughts below!

cc @mruberry @VitalyFedyunin @walterddr @eellison @Krovatkin @ngimel @kshitij12345 @krshrimali @pmeier @anjali411 @heitorschueroff @jbschlosser @albanD

**Comment by albanD** [comment] 2021-05-14 13:51
The one thing that worries me is that we would not be catching regressions on dtypes anymore.
For example, if I forget some code when updating an operator, nothing in the test suite will tell me that this used to work on int but doesn't anymore.

Note also that it means that people implementing some backend cannot be sure that all their implementation work as they don't get an error if they failed to properly implement a dtype.

Another con with this approach, is that right now, we can easily scan the OpInfo db to get a clear picture of dtype supports for different operators. This won't be possible any more.


While I agree with your pros, I'm not sure they're gonna last.
Indeed, right now, most people are porting old tests to OpInfo and so I can see why they might not have the right hardware to test things.
But after this transition period when everything is ported. People that will work with OpInfo will be only people working on the operators (to add new ones or update existing ones) and so they must have the hardware to test their change.

**Comment by ngimel** [comment] 2021-05-14 16:29
I'm with Alban here, _PROGRAMMATIC option essentially amounts to skipping the test. You can skip it today, but while skip is inherently something to be fixed, _PROGRAMMATIC normalized this situation and allows it to linger forever.

**Comment by mruberry** [comment] 2021-05-14 18:46
Good points, @albanD and @ngimel. I was talking with @ngimel offline and we thought about this alternative proposal:

- we allow the _DYNAMIC or _PROGRAMMATIC keyword when submitting to CI
- this keyword programmatically identifies the operator's dtypes and runs the tests as normal, except `test_supported_dtypes` prints out the correct dtype metadata
- we add a new test, `test_no_dynamic`, that fails if _DYNAMIC is set

This would let users without GPUs set _DYNAMIC and have all the tests run plus identify the dtypes, but it would prevent merging with _DYNAMIC because `test_no_dynamic` would fail.

This requires one back-and-forth with CI, but that still seems better than today?

**Comment by albanD** [comment] 2021-05-14 20:32
If the user doesn't have the hardware, I feel like one back and forth will be needed anyways :D So that could work yes.

**Comment by jbschlosser** [comment] 2021-05-17 14:54
Agree with @albanD and @ngimel - I generally consider it better to optimize for read-time rather than write-time since reading is done much more often than writing. I like that dtypes are currently explicit, and I like the protection against dtype regressions.

Providing a mechanism for auto-identifying dtypes that are then entered manually + explicitly seems like a good middle ground to improving writing efficiency while maintaining the benefits of explicit dtypes.

**Comment by Krovatkin** [comment] 2021-05-17 16:01
@mruberry I also like the middle-ground approach. I have a tangentially related question with the discoverability of this option, though. How are we going to let users know that this option exists and how to use it? Would that be a part of an error message or would that just be default outside CI w/ test_no_dynamic() failing?

**Comment by mruberry** [comment] 2021-05-17 17:22
@Krovatkin Discoverability is always an issue. I think the error messages for related tests, like test_supported_dtypes, can point users to this option (and to the future OpInfo metadata helper tool), and we can also extend the documentation for OpInfos in their file + in the developer wiki, too.

**Comment by eellison** [comment] 2021-05-17 17:24
Thank you for the writeup @mruberry.

The existing testing mechanism of adding symbolic differentiation to JIT is to add to a registry of tests like so: 
`('relu', (S, S, S), (), '', (True,))`. This is *really easy*. It also runs a robust set of tests comparing forward, backward, double backward, etc. If any of these do not work in eager, we do not run the corresponding test in JIT. 

A similar mechanism exists for testing `NNC`, you just add a line to a registry of tests with the name of the op: `torch.sqrt`, and we compare against all cross products of dtypes with different inputs sizes. Just like with the autodiff tests, if something doesn't work in eager, we do not run the JIT test. It is also *really easy*. 

For the purposes of the JIT, with both of these tests you get more or less exactly what you get out of OpInfos. However, adding OpInfos is *really hard*.  I tried adding hardswish OpInfo, I had to fix three unrelated downstream tests that were using OpInfos, make sure all of the 30 or so input fields on OpInfo were correct or didn't relate, and on top of that I was developing the PR on a machine without a GPU. 

After the slow process of process of going back and forth on the CI, I saw that `float16` was the one dtype which hadn't been correctly included, so I switched the input dtypes to `floating_types`, and went ahead and landed. I felt confident it was correct and it was a very long wait to see if the one GPU test had passed. The PR then got reverted, because the dtype constructor `floating_types` does not include `float16`..

In general, I think it would be reasonable to make more of the input properties to OpInfos opt in, so that we can migrate tests more easily for the huge amount of testing that comes with OpInfos, even if some of the properties we only up-front specify later. But, the property that I think is most important to be able leave off is dtypes. The fact that I can't reasonable motivate a bootcamper or someone on OSS to work on OpInfos if they don't have a GPU is a major disadvantage of the current testing scheme. It is possible to ping the CI back and forth, but it's not an experience that I think they will enjoy and I am not going to recommend it.

**Comment by eellison** [comment] 2021-05-17 17:25
I appreciate that the reason the JIT tests are easier to add to is because they rely on eager correctness as a baseline, and that OpInfos are way better for the ecosystem. Still, the difference in difficulty between using our existing test mechanisms and OpInfos does give me pause for migrating our tests completely over.

**Comment by mruberry** [comment] 2021-05-23 05:53
> The existing testing mechanism of adding symbolic differentiation to JIT is to add to a registry of tests like so:
> `('relu', (S, S, S), (), '', (True,))`. This is _really easy_. It also runs a robust set of tests comparing forward, backward, double backward, etc. If any of these do not work in eager, we do not run the corresponding test in JIT.

method_tests() is easy for people familiar with the pattern and the JIT, but many arguments are arcane and it's not very general or extensible. I would also argue that the tests generated using method_tests() have poor coverage. For example, method_tests() has fields for validating autodiff properties, but these fields don't matter. Even if they're wrong the current tests generated from method_tests() will still happily pass. What's the point of a test so permissive that even wrong metadata will make it pass? Here's a PR that corrects the incorrect autodiff metadata: https://github.com/pytorch/pytorch/pull/58184. Here's another PR that verifies it doesn't matter what the autodiff metadata in method_tests() is: https://github.com/pytorch/pytorch/pull/58223. 

OpInfos also have considerably more metadata about each operator than method_tests() does, and that makes them suitable for use in more tests, and because they're a Python class more extensible to handle future test needs, too.

> A similar mechanism exists for testing `NNC`, you just add a line to a registry of tests with the name of the op: `torch.sqrt`, and we compare against all cross products of dtypes with different inputs sizes. Just like with the autodiff tests, if something doesn't work in eager, we do not run the JIT test. It is also _really easy_.

We could continue to make bespoke one-off solutions, but ultimately I don't think that's the best use of our time. Also I think NNC is switching to OpInfo-based testing (see https://github.com/pytorch/pytorch/pull/58719).

> For the purposes of the JIT, with both of these tests you get more or less exactly what you get out of OpInfos. However, adding OpInfos is _really hard_. I tried adding hardswish OpInfo, I had to fix three unrelated downstream tests that were using OpInfos, make sure all of the 30 or so input fields on OpInfo were correct or didn't relate, and on top of that I was developing the PR on a machine without a GPU.

Yeah that bites. They can be tricky to write but with improved tooling like this proposed tool I think they'll become easier to develop.

> After the slow process of process of going back and forth on the CI, I saw that `float16` was the one dtype which hadn't been correctly included, so I switched the input dtypes to `floating_types`, and went ahead and landed. I felt confident it was correct and it was a very long wait to see if the one GPU test had passed. The PR then got reverted, because the dtype constructor `floating_types` does not include `float16`..

Yeah that's confusing. So part of the criticisms here are about OpInfo and part, I think, are about how rigorous the new tests are and how confusing some related parts of our system, like the dtype macros, are. Note that "floating_types" in the test suite corresponds 1:1 with the "floating_types" dispatch macro in C++, but many PyTorch developers are not especially familiar with the dispatch macros. We should probably revisit them and what we expose in our test suite.

> In general, I think it would be reasonable to make more of the input properties to OpInfos opt in, so that we can migrate tests more easily for the huge amount of testing that comes with OpInfos, even if some of the properties we only up-front specify later. But, the property that I think is most important to be able leave off is dtypes. The fact that I can't reasonable motivate a bootcamper or someone on OSS to work on OpInfos if they don't have a GPU is a major disadvantage of the current testing scheme. It is possible to ping the CI back and forth, but it's not an experience that I think they will enjoy and I am not going to recommend it.

I agree that asking someone to OpInfo an operator without GPU support will require at least one roundtrip with the CI and that's not great, but we have to be careful about balancing our many competing concerns. 

> I appreciate that the reason the JIT tests are easier to add to is because they rely on eager correctness as a baseline, and that OpInfos are way better for the ecosystem. Still, the difference in difficulty between using our existing test mechanisms and OpInfos does give me pause for migrating our tests completely over.

I appreciate that, but let's try to identify and mitigate the pain points with improved tooling and documentation. Maybe adding an OpInfo will never be a great task for bootcampers or community members without access to a CUDA device, and that's unfortunate, but I don't think that should be blocking, either, right? 

Also, it's just tough to write tests that work well with EVERY operator in PyTorch and all their possible variations. And I think one part of the pain with OpInfos is that PyTorch's operators are much more inconsistent than we'd like, and this more systemic testing is helping us identify and address those inconsistencies.

**Closed** 2021-07-20 20:55 UTC
Labels: module: tests, triaged
