### ISSUE TITLE
`numel` + `div` + `mul` will trigger INTERNAL ASSERT FAILED in JIT on cuda

### ISSUE THREAD

**Issue by payphon** [pytorch/pytorch#86227] opened 2022-10-04 19:56 UTC
### 🐛 Describe the bug

`numel` + `div` + `mul` will trigger INTERNAL ASSERT FAILED in JIT on cuda

```py
import torch

def fn(input):
    fn_res = torch.numel(input, )
    fn_res = torch.div(fn_res, torch.tensor(-3, dtype=torch.float32, device='cuda'))
    fn_res = torch.mul(fn_res, torch.tensor(-6, dtype=torch.float32, device='cuda'))
    return fn_res

input_tensor = torch.rand([1, 2, 3, 4, 5], dtype=torch.float32)

jit_fn = torch.jit.script(fn)
for i in range(5):
    print(i)
    jit_fn(input_tensor.clone().to('cuda'))
```

```
0
1

RuntimeError: tensor_inputs_to_check.size() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1664608354311/work/torch/csrc/jit/codegen/cuda/graph_fuser.cpp":1558, please report a bug to PyTorch. CudaFusionGuard expects at least one tensor input
```

### Versions

```
PyTorch version: 1.13.0.dev20221001
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.2.0-19ubuntu1) 11.2.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.13 (main, Aug 25 2022, 23:26:10)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.19.5-051905-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.99
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3060
Nvidia driver version: 515.65.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.3
[pip3] torch==1.13.0.dev20221001
[pip3] torchaudio==0.13.0.dev20221001
[pip3] torchvision==0.14.0.dev20221001
[conda] blas                      1.0                         mkl  
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.3                   pypi_0    pypi
[conda] numpy-base                1.23.1           py39ha15fc14_0  
[conda] pytorch                   1.13.0.dev20221001 py3.9_cuda11.7_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.7                 h67b0de4_0    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torch                     1.13.0.dev20220923+cu116          pypi_0    pypi
[conda] torchaudio                0.13.0.dev20220923+cu116          pypi_0    pypi
[conda] torchvision               0.14.0.dev20220923+cu116          pypi_0    pypi
```

**Comment by payphon** [comment] 2022-10-05 00:22
Actually, many APIs that return an integer based on some attributes of tensor suffer this issue, such as `Tensor.dim`, `Tensor.element_size`, `Tensor.get_device`.

```py
import torch
# Tensor Info
# {"name": "_input_tensor", "shape": [3], "dtype": "torch.float32"}
class M(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, _input_tensor):
        fn_res = _input_tensor.dim()
        fn_res = torch.sub(fn_res, torch.tensor(-5, dtype=torch.float32, device='cuda'))
        fn_res = torch.sub(fn_res, torch.tensor(-7, dtype=torch.float32, device='cuda'))
        return fn_res

fn = M().to('cuda')

torch.random.manual_seed(54537)
input_tensor = torch.empty([3], dtype=torch.float32, memory_format=torch.contiguous_format)
input_tensor.uniform_(-32, 63)

jit_fn = torch.jit.script(fn)
for i in range(5):
    print(i)
    jit_fn(input_tensor.clone().to('cuda'))
```

```py
import torch

torch._C._jit_set_nvfuser_single_node_mode(True)

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, _input_tensor):
        _input_tensor = torch.nn.functional.tanhshrink(_input_tensor)
        _input_tensor = torch.cos(_input_tensor)
        fn_res = _input_tensor.element_size()
        fn_res = torch.sub(fn_res, torch.tensor(-7, dtype=torch.float32, device='cuda'))
        return fn_res

fn = M().to('cuda')

torch.random.manual_seed(32533)
input_tensor = torch.empty([1, 1, 3, 3], dtype=torch.float32, memory_format=torch.contiguous_format)
input_tensor.uniform_(-32, 127)

jit_fn = torch.jit.script(fn)
for i in range(5):
    print(i)
    jit_fn(input_tensor.clone().to('cuda'))
```

```py
import torch

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, _input_tensor):
        fn_res = _input_tensor.get_device()
        fn_res = torch.mul(fn_res, torch.tensor(-4, dtype=torch.float32, device='cuda'))
        fn_res = torch.nn.functional.tanhshrink(fn_res)
        return fn_res

fn = M().to('cuda')

torch.random.manual_seed(23049)
input_tensor = torch.empty([1, 96, 1, 1], dtype=torch.float32, memory_format=torch.contiguous_format)
input_tensor.uniform_(-64, 3)

jit_fn = torch.jit.script(fn)
for i in range(5):
    print(i)
    jit_fn(input_tensor.clone().to('cuda'))
```

All of them trigger `RuntimeError: tensor_inputs_to_check.size() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1664608354311/work/torch/csrc/jit/codegen/cuda/graph_fuser.cpp":1558, please report a bug to PyTorch. CudaFusionGuard expects at least one tensor input`

**Comment by kevinstephano** [comment] 2022-10-05 01:52
I think you filed a bug on the same issue last week.  This is a duplicate of #85872.

**Closed by kevinstephano** 2022-10-05 01:52 UTC
Labels: oncall: jit
