### ISSUE TITLE
[v.2.4.0] Release Tracker

### ISSUE THREAD

**Issue by atalman** [pytorch/pytorch#128436] opened 2024-06-11 18:50 UTC
We cut a [release branch](https://github.com/pytorch/pytorch/tree/release/2.4) for the 2.4.0 release.

Our plan from this point from this point is roughly:

* Phase 1 (until 7/1/24): work on finalizing the release branch
* Phase 2 (after 7/1/24): perform extended integration/stability/performance testing based on Release Candidate builds.

This issue is for tracking cherry-picks to the release branch.

## Cherry-Pick Criteria

**Phase 1 (until 7/1/24):**

Only low-risk changes may be cherry-picked from main:

1. Fixes to regressions against the most recent minor release (e.g. 2.3.x for this release; see [module: regression issue list](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22module%3A+regression%22+))
2. Critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+)
3. Critical fixes to new features introduced in the most recent minor release (e.g. 2.3.x for this release)
4. Test/CI fixes
5. Documentation improvements
6. Compilation fixes or ifdefs required for different versions of the compilers or third-party libraries
7. Release branch specific changes (e.g. change version identifiers)

Any other change requires special dispensation from the release managers (currently  @atalman, @PaliC , @huydhn, @malfet). If this applies to your change please write "Special Dispensation" in the "Criteria Category:" template below and explain.

**Phase 2 (after 7/1/24):**

Note that changes here require us to rebuild a Release Candidate and restart extended testing (likely delaying the release). Therefore, the only accepted changes are **Release-blocking** critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+)

Changes will likely require a discussion with the larger release team over VC or Slack.

## Cherry-Pick Process

1. Ensure your PR has landed in master. This does not apply for release-branch specific changes (see Phase 1 criteria).
2. Create (but do not land) a PR against the [release branch](https://github.com/pytorch/pytorch/tree/release/2.4).
   <details>

    ```bash
    # Find the hash of the commit you want to cherry pick
    # (for example, abcdef12345)
    git log

    git fetch origin release/2.4
    git checkout release/2.4
    git cherry-pick -x abcdef12345

    # Submit a PR based against 'release/2.4' either:
    # via the GitHub UI
    git push my-fork

    # via the GitHub CLI
    gh pr create --base release/2.4
    ```

    </details>
3. Make a request below with the following format:

```
Link to landed trunk PR (if applicable):
* 

Link to release branch PR:
* 

Criteria Category:
* 
```

1. Someone from the release team will reply with approved / denied or ask for more information.
2. If approved, someone from the release team will merge your PR once the tests pass. **Do not land the release branch PR yourself.**

**NOTE: Our normal tools (ghstack / ghimport, etc.) do not work on the release branch.**

Please note HUD Link with branch CI status and link to the HUD to be provided here.
[HUD](https://hud.pytorch.org/hud/pytorch/pytorch/release%2F2.4)

### Versions

2.4.0

**Comment by atalman** [comment] 2024-06-11 18:53
Link to landed trunk PR (if applicable):
* NA

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128347
* https://github.com/pytorch/pytorch/pull/128388
* https://github.com/pytorch/builder/pull/1863

Criteria Category:
* Release only changes, temp changes to build triton from pin rather then branch

**Comment by atalman** [comment] 2024-06-11 22:18
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/builder/pull/1862

Link to release branch PR:
* https://github.com/pytorch/builder/pull/1867

Criteria Category:
* Required to fix rocm nightly build error https://github.com/pytorch/pytorch/issues/128420

**Comment by atalman** [comment] 2024-06-12 18:28
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128358

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128530

Criteria Category:
* Critical fix

**Comment by atalman** [comment] 2024-06-12 19:14
Link to landed trunk PR (if applicable):
* Revert of https://github.com/pytorch/pytorch/pull/125343/

Link to release branch PR:
*  https://github.com/pytorch/pytorch/pull/128539

Criteria Category:
*  Reverted on main

**Comment by atalman** [comment] 2024-06-12 19:17
Link to landed trunk PR (if applicable):
* Revert of https://github.com/pytorch/pytorch/pull/123514

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128541

Criteria Category:
* Reverted on main

**Comment by atalman** [comment] 2024-06-12 19:23
Link to landed trunk PR (if applicable):
* Revert of https://github.com/pytorch/pytorch/pull/127690 

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128542

Criteria Category:
* Reverted on Main

**Comment by zhuhaozhe** [comment] 2024-06-13 02:03
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128473

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128577

Criteria Category:
* Critical fix, forward fix for https://github.com/pytorch/pytorch/issues/128287 on release branch. It's a regression on inductor, will crash on many benchmark models without this fix.

**Comment by zou3519** [comment] 2024-06-13 02:55
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128456

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128581

Criteria Category:
* (1) Fixes to regressions. In 2.4, we started spamming warnings if someone used pybind'ed functions with torch.compile. There were no such warnings in 2.3. This PR adjusts the warnings to be less spammy.

**Comment by etaf** [comment] 2024-06-13 11:00
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128383

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128602

Criteria Category:
* Fix UT and unblock the xpu CI:  before https://github.com/pytorch/pytorch/pull/127611 merged, the xpu-specific UT test/test_xpu.py was skipped temporarily because the test cases were disabled by TD. This PR aims to fix the UT bug introduced by https://github.com/pytorch/pytorch/pull/127741 .

**Comment by etaf** [comment] 2024-06-13 15:13
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128383

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128614

Criteria Category:
* Fix UT and unblock the xpu CI:  before https://github.com/pytorch/pytorch/pull/127611 merged, the xpu-specific UT test/test_xpu.py was skipped temporarily because the test cases were disabled by TD. This PR aims to fix the UT bug introduced by https://github.com/pytorch/pytorch/pull/127741 .

**Comment by zou3519** [comment] 2024-06-13 15:29
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128547

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128616

Criteria Category:
* (3) Critical fixes to new features. In 2.4 we are releasing a new torch.library.custom_op API. This PR fixes a critical bug that the API did not compose with FSDP and other distributed APIs.

**Comment by chunyuan-w** [comment] 2024-06-14 01:14
Link to landed trunk PR (if applicable):
* Revert of https://github.com/pytorch/pytorch/pull/123403 (the revert is done in https://github.com/pytorch/pytorch/pull/128377)

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128511

Criteria Category:
* Reverted on main to fix  a regression issue (https://github.com/pytorch/pytorch/issues/127513) that will impact the AOTI CPU performance on multiple CNN models in the dynamo benchmark.

**Comment by etaf** [comment] 2024-06-14 08:10
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/124842

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128615

Criteria Category:
* Critical fix, forward fix for https://github.com/pytorch/pytorch/issues/126173. Also update Intel triton for release 2.4.

**Comment by wanchaol** [comment] 2024-06-14 16:54
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128363

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128717

Criteria Category:
* Critical fixes for compile time regression

**Comment by wanchaol** [comment] 2024-06-14 16:58
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128431

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128719

Criteria Category:
* Critical fixes for silent correctness

**Comment by Xia-Weiwen** [comment] 2024-06-15 08:59
Link to landed trunk PR (if applicable):
- https://github.com/pytorch/pytorch/pull/127592

Link to release branch PR:
- https://github.com/pytorch/pytorch/pull/128591

Criteria Category:
- Critical fix for https://github.com/pytorch/pytorch/issues/127402. Without the fix, transformer-based models will fail to run with PT2E quantization on X86Inductor backend.

**Comment by xuhancn** [comment] 2024-06-17 06:40
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128770

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128811

Criteria Category:
* Critical fixes for PyTorch Windows cpp_extension. If user use cpp_extension to build extension and its code contains VEC, it will occur sleef dependency issue.

**Comment by zou3519** [comment] 2024-06-17 14:36
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128275

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128834

Criteria Category:
* (1) Regression (from 2.3.x) and (2) Critical fixes for: silent incorrectness

**Comment by lw** [comment] 2024-06-17 15:24
Link to landed trunk PR (if applicable):

https://github.com/pytorch/pytorch/pull/128688

Link to release branch PR:

https://github.com/pytorch/pytorch/pull/128837

Criteria Category:

Fixes to regressions against the most recent minor release (changes only logging, low risk)

**Comment by clee2000** [comment] 2024-06-17 23:29
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/test-infra/pull/5327

Link to release branch PR:
* https://github.com/pytorch/test-infra/pull/5348

Criteria Category:
* Release - needed to fix executorch release CI

**Comment by huydhn** [comment] 2024-06-18 02:27
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128718

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128921

Criteria Category:
Release - Debug debug

**Comment by huydhn** [comment] 2024-06-18 02:39
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/128718

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/128923

Criteria Category:
Release - Debug debug

**Comment by xuhancn** [comment] 2024-06-19 18:37
> Link to landed trunk PR (if applicable):
> 
> * [[cpp_extension][inductor] Fix sleef windows depends. #128770](https://github.com/pytorch/pytorch/pull/128770)
> 
> Link to release branch PR:
> 
> * [[cpp_extension][inductor] Fix sleef windows depends. (#128770) #128811](https://github.com/pytorch/pytorch/pull/128811)
> 
> Criteria Category:
> 
> * Critical fixes for PyTorch Windows cpp_extension. If user use cpp_extension to build extension and its code contains VEC, it will occur sleef dependency issue.
> 
> Hi @xuhancn this looks like feature work to enable inductor on PyTorch Windows, however for release 2.4 we don't support this yet. Do you have any tests with it ?

pytorch 2.4 not support Windows Inductor, but pytorch 2.4 enabled Windows x86 CPU vectorization(https://github.com/pytorch/pytorch/pull/118980). It will add sleef as dependency on cpp_extension. So, We need to cherry-pick this PR.

**Comment by atalman** [comment] 2024-06-20 14:16
Link to landed trunk PR (if applicable):
* NA

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/129139
* https://github.com/pytorch/builder/pull/1877

Criteria Category:
* Release only changes: Triton branch is now available here: https://github.com/triton-lang/triton/tree/release/3.0.x hence we don't need these temporary PRs anymore

**Comment by atalman** [comment] 2024-06-21 13:14
Link to landed trunk PR (if applicable):
* N/A (will be added later)

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/129227

Criteria Category:
* Release only change to fix triton rocm compilation. This change will be added to trunk later with moving of rocm pin in main

**Comment by zou3519** [comment] 2024-06-21 15:38
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/129177

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/129236

Criteria Category:
* Documentation improvements

**Comment by zou3519** [comment] 2024-06-21 15:39
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/129178

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/129237

Criteria Category:
* Documentation improvements -- we moved the custom ops docs and need to update the error messages.

**Comment by fegin** [comment] 2024-06-21 18:27
Link to landed trunk PR (if applicable):

* https://github.com/pytorch/pytorch/pull/128446
* https://github.com/pytorch/pytorch/pull/128755 (test)

Link to release branch PR:

* https://github.com/pytorch/pytorch/pull/129254
* https://github.com/pytorch/pytorch/pull/129255 (test)

Criteria Category:

* Critical fixes to crashes when loading HSDP1 + full state_dict with rank0 broadcasting feature.

**Comment by jingxu10** [comment] 2024-06-21 20:26
Link to landed trunk PR (if applicable):


- https://github.com/pytorch/pytorch/pull/127872
- https://github.com/pytorch/pytorch/pull/127280
- https://github.com/pytorch/pytorch/pull/127276
- https://github.com/pytorch/pytorch/pull/127278
- https://github.com/pytorch/pytorch/pull/127279

Link to release branch PR:

- https://github.com/pytorch/pytorch/pull/129266

Criteria Category:

Documentation improvements - Add documentation for XPU support to PyTorch

**Comment by atalman** [comment] 2024-06-21 20:59
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/builder/pull/1880

Link to release branch PR:
* https://github.com/pytorch/builder/pull/1881

Criteria Category:
* Release conda build required change

**Comment by etaf** [comment] 2024-06-24 06:42
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/129120

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/129337

Criteria Category:
* Important Intel GPU Inductor performance improvement for release 2.4.

**Comment by xuhancn** [comment] 2024-06-25 05:14
> Link to landed trunk PR (if applicable):
> 
> * [[cpp_extension][inductor] Fix sleef windows depends. #128770](https://github.com/pytorch/pytorch/pull/128770)
> 
> Link to release branch PR:
> 
> * [[cpp_extension][inductor] Fix sleef windows depends. (#128770) #128811](https://github.com/pytorch/pytorch/pull/128811)
> 
> Criteria Category:
> 
> * Critical fixes for PyTorch Windows cpp_extension. If user use cpp_extension to build extension and its code contains VEC, it will occur sleef dependency issue.
> 
> Hi @xuhancn this looks like feature work to enable inductor on PyTorch Windows, however for release 2.4 we don't support this yet. Do you have any tests with it ?

Hi @malfet , @atalman , I have added some test case to proof it is a cpp_extension enhancement fixing: https://github.com/pytorch/pytorch/pull/128811#issuecomment-2182104467 . Please don't forget to merge this PR.

**Comment by mikaylagawarecki** [comment] 2024-06-25 15:19
Link to landed trunk PR (if applicable):
*  #129244
* #129251
* #129239
* #129396

Link to release branch PR:
* #129478

Criteria Category:
* 129244 and 129251 are critical fixes to `torch.serialization.add_safe_globals` added in 2.4 that caused the API to not work for a large proportion of cases
* 129239 adds a warning
* 129396 is a documentation improvement

**Comment by mikaylagawarecki** [comment] 2024-06-26 15:32
Resubmit of https://github.com/pytorch/pytorch/issues/128436#issuecomment-2189242843 since some PRs in that list were reverted

Link to landed trunk PR (if applicable):
*  #129244
* #129251
* #129509 
* #129239
* #129396

Link to release branch PR:
* #129574
* #129573
* #129572 

Criteria Category:
* 129244 and 129251 are critical fixes to `torch.serialization.add_safe_globals` added in 2.4 that caused the API to not work with `weights_only` for a large proportion of cases, 129509 was a fix to prevent a dependency on private module in CPython (these three are submitted as 1 PR since they are related)
*  129239 adds a warning
* 129396 is a documentation improvement

**Comment by wz337** [comment] 2024-06-27 18:13
Link to landed trunk PR (if applicable):
*  https://github.com/pytorch/pytorch/pull/129398

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/129683

Criteria Category:
* Fix for regression

**Comment by atalman** [comment] 2024-06-27 21:19
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/builder/pull/1891

Link to release branch PR:
* 

Criteria Category:
* Critical fix MKL dependency

**Comment by oraluben** [comment] 2024-06-28 03:29
Link to landed trunk PR (if applicable):

* (not landed yet) https://github.com/pytorch/pytorch/pull/129669

Link to release branch PR:

* https://github.com/pytorch/pytorch/pull/129729

Criteria Category:
* Breaks building wheels in specific cases

**Comment by Skylion007** [comment] 2024-06-28 15:06
Wondering if we can get this landined in main so we can backport it. We've encoutered some hanging on certain hardware with certain firmware versions that only occur on this specific NCCL version (fixed in NCCL versions before and after): https://github.com/pytorch/pytorch/pull/124014

**Comment by tinglvv** [comment] 2024-07-01 18:57
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/builder/pull/1895

Link to release branch PR:
* https://github.com/pytorch/builder/pull/1902

Criteria Category:
* Fix for "libgfortran.so.5" missing error for CUDA ARM wheel at runtime

**Comment by wz337** [comment] 2024-07-02 02:17
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/129519

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/129923

Criteria Category:
* Critical fix. Need this to avoid silent correctness for a feature not ready.

**Comment by atalman** [comment] 2024-07-02 19:51
Please note, we are in:
Phase 2 (after 7/1/24): perform extended integration/stability/performance testing based on Release Candidate builds.
We do not accept new cherry-pick requests

**Comment by atalman** [comment] 2024-07-02 20:53
Please note, we are in:
Phase 2 (after 7/1/24): perform extended integration/stability/performance testing based on Release Candidate builds.
We do not accept new cherry-pick requests

**Comment by ppwwyyxx** [comment] 2024-07-14 00:11
Can we address https://github.com/pytorch/pytorch/issues/130658 and https://github.com/pytorch/pytorch/issues/130659 ? Otherwise 2.4 users will be guaranteed to see a lot of warnings.

**Comment by atalman** [comment] 2024-07-15 17:52
hi @ppwwyyxx both of the PRs https://github.com/pytorch/pytorch/issues/130658 and  https://github.com/pytorch/pytorch/issues/130659 are targeted for release 2.4.1

**Comment by XuehaiPan** [comment] 2024-07-20 16:20
Link to landed trunk PR (if applicable):
* #130895

Link to release branch PR:
* #131281

Criteria Category:
* Critical fixes for dependency update

**Closed** 2024-07-24 21:28 UTC
Labels: oncall: releng, triaged, release tracker
