### ISSUE TITLE
Multi-GPU causes runtime error (element 0 of variables does not require grad <...>)

### ISSUE THREAD

**Issue by Inoryy** [pytorch/pytorch#5735] opened 2018-03-13 09:36 UTC
Whenever I attempt to run the code in multi-gpu setup I immediately get this error:  

`RuntimeError: element 0 of variables does not require grad and does not have a grad_fn`  

 The error happens when I initiate `loss.backward()` and it's only specific to multi-gpu setup, as the code works fine on either GPU alone. Here's a snippet for context:

```python
inputs = Variable(inputs).cuda()
model(inputs, labels)
loss = model.loss(inputs, labels)
loss.backward() # <--- error here
optimizer.step()
optimizer.zero_grad()
```

Environment details:

- OS: Ubuntu 17.10
- PyTorch version:  0.4.0a0+15cc24a
- How you installed PyTorch: source
- Python version: 3.6.4
- CUDA/cuDNN version: 9.0 / 7.0.5
- GPU models and configuration: 2x 1080 Ti (same model)
- GCC version: 4.8.5

**Comment by apaszke** [comment] 2018-03-13 10:26
It probably happens because loss doesn’t require grad (and it should), but we can’t debug this without seeing the model first. The error message could be improved though

**Comment by Inoryy** [comment] 2018-03-13 18:12
Ok, but why would it only occur with multiple GPUs enabled? I'll see if I can create self-contained model that replicates this..

**Comment by emailhy** [comment] 2018-03-13 19:42
https://www.kaggle.com/c/data-science-bowl-2018/discussion/49692
this model will reproduce the problem with master branch

**Comment by soumith** [comment] 2018-03-19 19:48
should be fixed on master via https://github.com/pytorch/pytorch/pull/5880

@Inoryy can you please confirm?

**Comment by Inoryy** [comment] 2018-03-19 20:33
@soumith I can't even compile anymore, build fails with:
> CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
MKL_INCLUDE_DIR (ADVANCED)
used as include directory in directory <..>/pytorch/aten

Even though right above I can see:
> -- MKL library found
-- Found a library with BLAS API (mkl).
-- Found a library with LAPACK API (mkl).

**Comment by ezyang** [comment] 2018-03-19 20:42
We added a new conda dep. Run `conda install mkl-include` and try again.

**Comment by Inoryy** [comment] 2018-03-19 20:56
ok, that solves that but now it seems you're targeting some specific `gcc` version as the one working previously (`4.8.5`) fails with `error: unrecognized command line option ‘-flifetime-dse=1`, which seems to be `gcc 6+` feature. However, compiling it under `gcc 6.4.0` crashes with some cryptic message:

```[ 54%] Building NVCC (Device) object src/ATen/CMakeFiles/ATen.dir/native/cuda/ATen_generated_Unique.cu.o
<..>/pytorch/aten/src/ATen/native/cuda/Embedding.cu(36): warning: function "__any"
/usr/local/cuda/include/device_atomic_functions.h(180): here was declared deprecated ("__any() is deprecated in favor of __any_sync() and may be removed in a future release (Use -Wno-deprecated-declarations to suppress this warning).")

/usr/include/c++/6/tuple: In instantiation of ‘static constexpr bool std::_TC<<anonymous>, _Elements>::_MoveConstructibleTuple() [with _UElements = {std::tuple<at::Tensor&, at::Tensor&, at::Tensor&>}; bool <anonymous> = true; _Elements = {at::Tensor&, at::Tensor&, at::Tensor&}]’:
/usr/include/c++/6/tuple:626:248:   required by substitution of ‘template<class ... _UElements, typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor&, at::Tensor&, at::Tensor&>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor&, at::Tensor&, at::Tensor&>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor&, at::Tensor&, at::Tensor&>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> > constexpr std::tuple< <template-parameter-1-1> >::tuple(_UElements&& ...) [with _UElements = {std::tuple<at::Tensor&, at::Tensor&, at::Tensor&>}; typename std::enable_if<(((std::_TC<(sizeof... (_UElements) == 1), at::Tensor&, at::Tensor&, at::Tensor&>::_NotSameTuple<_UElements ...>() && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor&, at::Tensor&, at::Tensor&>::_MoveConstructibleTuple<_UElements ...>()) && std::_TC<(1ul == sizeof... (_UElements)), at::Tensor&, at::Tensor&, at::Tensor&>::_ImplicitlyMoveConvertibleTuple<_UElements ...>()) && (3ul >= 1)), bool>::type <anonymous> = <missing>]’
<..>/pytorch/torch/lib/build/aten/src/ATen/ATen/Functions.h:1626:61:   required from here
/usr/include/c++/6/tuple:483:67: error: mismatched argument pack lengths while expanding ‘std::is_constructible<_Elements, _UElements&&>’
       return __and_<is_constructible<_Elements, _UElements&&>...>::value;
```

**Comment by ezyang** [comment] 2018-03-19 21:16
OK, you should revert 22ef8e5654c45d1f5404e3add6ad19678c0b80a9 for now and try again.

**Comment by ezyang** [comment] 2018-03-19 21:19
UPDATE: Actually, `-flifetime-dse=1` is probably coming from tbb, so reverting won't help.

**Comment by ezyang** [comment] 2018-03-19 21:20
@Inoryy According to the tbb CMakeLists.txt, `-flifetime-dse=1` should only be set if the compiler supports it (we're testing for it.)   What happens if you do a clean rebuild from scratch (e.g., run `git clean -xfd`)?

**Comment by Inoryy** [comment] 2018-03-19 21:43
@ezyang compilation worked with `gcc 4.8.5` after running `git clean -xfd` and I can confirm the issue is now resolved. Thank you!

**Closed** 2018-03-19 22:21 UTC
