### ISSUE TITLE
scatter_ throwing a RunTimeError

### ISSUE THREAD

**Issue by abstractpaper** [pytorch/pytorch#40359] opened 2020-06-21 21:50 UTC
## 🐛 Bug

I'm trying to turn a tensor into three different tensors for a CNN with three channels. The following happened while testing.

## To Reproduce

```python
(Pdb) y
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0.])
(Pdb) (y == 0).nonzero()
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8]])
(Pdb) y.scatter_(0, (y == 0).nonzero(), 1)
*** RuntimeError: size.size() == stride.size() INTERNAL ASSERT FAILED at /pytorch/aten/src/ATen/native/Resize.h:96, please report a bug to PyTorch.
```

## Expected behavior

A tensor with `1` at every index.

## Environment

```console
$ python collect_env.py
Collecting environment information...
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Arch Linux
GCC version: (Arch Linux 9.3.0-1) 9.3.0
CMake version: version 3.17.1

Python version: 3.8
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.5
[pip3] torch==1.5.0
[conda] Could not collect
```

## Additional context

So squeeze solves it, however, I'm leaving this issue since an internal assert failed:

```python
>>> y = torch.zeros([9])
>>> y.scatter(0, (y == 0).nonzero().squeeze(), 1)
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1.])
```

**Comment by ngimel** [comment] 2020-06-22 21:34
cc @nikitaved - is something missing in the shape checks? We should not be getting internal assert.

**Comment by nikitaved** [comment] 2020-06-22 21:45
I cannot reproduce on master. What PyTorch version do you use?

**Comment by zou3519** [comment] 2020-06-23 19:52
I can confirm this bug exists on 1.5.0 and 1.5.1 but appears to be fixed in master. I am closing this issue because it has been fixed on master.

**Closed by zou3519** 2020-06-23 19:52 UTC

**Comment by ngimel** [comment] 2020-06-23 19:55
There's still something wrong with the shape checking it seems, the documentation says that the number of dimensions should be the same for src and idx, yet in this case idx has 2 dimensions (as a result of `.nonzero(0`), src is 1-d, and yet somehow it still works. @nikitaved can you please double check it?

**Comment by nikitaved** [comment] 2020-06-23 20:03
@ngimel, it works in this case because the shape check iterates over `self.dim`. So, yeah, it requires a fix, I guess.
Shall we actually allow `index/src` to have one dimension more if its size is `1`?

**Comment by ngimel** [comment] 2020-06-23 20:12
I'm not sure what exactly we should allow, but in any case it should be documented, and it also should be more or less general. E.g. in the cases you describe, why stop at one extra dimension and not allow [N, 1, 1]? Also, can singleton dimensions be appended only, or appended and prepended? Seems easier to me to just disallow all questionable cases, with good error messages :-)

**Comment by nikitaved** [comment] 2020-06-23 20:15
OK, it is much easier to fix the dim to be exactly the same for all inputs, otherwise we could allow broadcasting if needed.

**Comment by ngimel** [comment] 2020-06-23 20:47
I'm a bit wary about allowing general broadcasting - would require some thought to get right. E.g. for in-place scatter self cannot be broadcasted, so values/indices should be broadcastable to self, right? For gather it's probably enough to require indices and self to be broadcastable to a common shape. Do you remember if there were enhancement requests to enable broadcasting for scatter/gather ops? In any case, imo it makes sense for now to bring behavior in agreement with the documentation, and discuss broadcasting separately.

**Comment by nikitaved** [comment] 2020-06-23 20:59
No, I do not remember the broadcasting requests, but I do remember expectations that `index/src`, for example, do broadcast over `self` in scatter. Sure, I will make it as the documentation says.
