### ISSUE TITLE
[Inductor] [CPU] Torchbench model hf_BigBird performance regression > 10% on 2023-04-23 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#99962] opened 2023-04-25 03:54 UTC
### 🐛 Describe the bug

Compare with 2023-04-19, there is a performance regression on torchbench model **hf_BigBird** on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1521096532) on 2023-04-23 as bellow:

|  2023-04-23  |   |     |   | 2023-04-19  |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|0.9578	|0.2188655	|0.209629376	|1	|1.1559	|0.1801138	|0.208193541	|0.83	|0.99	|0.82

2023-04-23 SW information:

SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[1b3ac4a](https://github.com/pytorch/pytorch/commit/1b3ac4a)|[ebd47b0](https://github.com/pytorch/pytorch/commit/ebd47b0)
Torchbench|/|[a0848e19](https://github.com/pytorch/benchmark/commit/a0848e19)
torchaudio|[0a652f5](https://github.com/pytorch/audio/commit/0a652f5)|[d5b2996](https://github.com/pytorch/audio/commit/d5b2996)
torchtext|[c4ad5dd](https://github.com/pytorch/text/commit/c4ad5dd)| [79100a6](https://github.com/pytorch/text/commit/79100a6)
torchvision|[f2009ab](https://github.com/pytorch/vision/commit/f2009ab)|[b78d98b](https://github.com/pytorch/vision/commit/b78d98b)
torchdata|[5cb3e6d](https://github.com/pytorch/data/commit/5cb3e6d)|[f2bfd3d](https://github.com/pytorch/data/commit/f2bfd3d)
dynamo_benchmarks|[fea73cb](https://github.com/pytorch/pytorch/commit/fea73cb)|/

2023-04-19 SW information:
SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[b206fd2](https://github.com/pytorch/pytorch/commit/b206fd2)|[8e69879](https://github.com/pytorch/pytorch/commit/8e69879)
Torchbench|/|[a0848e19](https://github.com/pytorch/benchmark/commit/a0848e19)
torchaudio|[0a652f5](https://github.com/pytorch/audio/commit/0a652f5)|[d5b2996](https://github.com/pytorch/audio/commit/d5b2996)
torchtext|[c4ad5dd](https://github.com/pytorch/text/commit/c4ad5dd)| [79100a6](https://github.com/pytorch/text/commit/79100a6)
torchvision|[f2009ab](https://github.com/pytorch/vision/commit/f2009ab)|[b78d98b](https://github.com/pytorch/vision/commit/b78d98b)
torchdata|[5cb3e6d](https://github.com/pytorch/data/commit/5cb3e6d)|[f2bfd3d](https://github.com/pytorch/data/commit/f2bfd3d)
dynamo_benchmarks|[fea73cb](https://github.com/pytorch/pytorch/commit/fea73cb)|/

Graph dump by cosim:
2023-04-23:
[graph.txt](https://github.com/pytorch/pytorch/files/11316262/graph.txt)
2023-04-19:
[graph.txt](https://github.com/pytorch/pytorch/files/11316267/graph.txt)

### Versions

Minified repro:

```bash
python -m torch.backends.xeon.run_cpu --node_id 0 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only hf_BigBird  --cold_start_latency


```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by blzheng** [comment] 2023-04-26 09:51
This performance regression is caused by graph breaks triggered by inplace unsqueeze. 
https://github.com/pytorch/pytorch/blob/62f9189d9d6ad1578c1bfddd17d45dc132e4b9b6/torch/_dynamo/variables/tensor.py#L184-L185

**Comment by chuanqi129** [comment] 2023-05-21 12:03
Confirmed, the performance has been come back. @blzheng @XiaobingSuper we can close it now

**Closed** 2023-05-21 12:33 UTC
Labels: triaged, oncall: pt2, module: cpu inductor
