### ISSUE TITLE
PyTorch doesn't report useful error when forking after CUDA initialization (originally: Unknown cuda error with multiprocessing)

### ISSUE THREAD

**Issue by ayl** [pytorch/pytorch#15734] opened 2019-01-04 14:39 UTC
## 🐛 Bug

Strange cuda error when torch.cuda.device_count called before torch.cuda.get_device_properties with multiprocessing.

## To Reproduce

~~~~
import multiprocessing, torch

def mp_worker(gpu):
    print(torch.cuda.get_device_properties(gpu))

gpus = list(range(torch.cuda.device_count()))

processes = [multiprocessing.Process(target=mp_worker, args=(gpui,)) for gpui in gpus]
for process in processes:
    process.start()
for process in processes:
    process.join()
~~~~

causes this (unhelpful) error to occur: 
~~~~
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 144, in init
    _lazy_init()
  File "/usr/local/lib/python3.6/dist-packages/torch/cuda/__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCGeneral.cpp:51
~~~~

If I change the code so that it does not call torch.cuda.device_count before the multiprocessing processes start then it works correctly:

~~~~
import multiprocessing, torch, os

def mp_worker(gpu):
    print(torch.cuda.get_device_properties(gpu))

gpus = list(range(len(os.environ["CUDA_VISIBLE_DEVICES"].split(","))))

processes = [multiprocessing.Process(target=mp_worker, args=(gpui,)) for gpui in gpus]
for process in processes:
    process.start()
for process in processes:
    process.join()
~~~~

Outputs as expected:
~~~~
_CudaDeviceProperties(name='Tesla P100-PCIE-16GB', major=6, minor=0, total_memory=16276MB, multi_processor_count=56)
_CudaDeviceProperties(name='Tesla P100-PCIE-16GB', major=6, minor=0, total_memory=16276MB, multi_processor_count=56)
~~~~

## Environment

~~~~
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB
GPU 2: Tesla P100-PCIE-16GB
GPU 3: Tesla P100-PCIE-16GB
GPU 4: Tesla P100-PCIE-16GB
GPU 5: Tesla P100-PCIE-16GB
GPU 6: Tesla P100-PCIE-16GB
GPU 7: Tesla P100-PCIE-16GB

Nvidia driver version: 384.145
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy (1.15.4)
[pip3] torch (1.0.0)
[pip3] torchvision (0.2.1)
~~~~

## Additional context

I suspect this has something to do with cuda initialization not working with multiprocessing's fork, but if you wait to initialize cuda within each forked process then it initializes correctly.

**Comment by ezyang** [comment] 2019-01-07 05:08
Confirmed reproduction, but I get a different error:

```
  File "repro.py", line 4, in mp_worker
    print(torch.cuda.get_device_properties(gpu))
  File "/home/ezyang/pytorch-tmp/torch/cuda/__init__.py", line 298, in get_device_properties
    init()  # will define _get_device_properties and _CudaDeviceProperties
  File "/home/ezyang/pytorch-tmp/torch/cuda/__init__.py", line 144, in init
    _lazy_init()
  File "/home/ezyang/pytorch-tmp/torch/cuda/__init__.py", line 162, in _lazy_init
    torch._C._cuda_init()
RuntimeError: cuda runtime error (3) : initialization error at /home/ezyang/pytorch-tmp/aten/src/THC/THCGeneral.cpp:50
```

**Comment by ezyang** [comment] 2019-01-07 05:21
We can't fix this directly, because CUDA API must not be initialized before you fork (this is a well known limitation), but I was pretty sure we had a good error message for this case, which seems to have regressed.

You can use the spawn method instead. But you also have to make sure you wrap the parent script in an `if __name__ == '__main__'` block or you'll get an oblique error message about `freeze_support`:

```
import torch.multiprocessing as multiprocessing
import torch

def mp_worker(gpu):
    print(torch.cuda.get_device_properties(gpu))

if __name__ == '__main__':
    gpus = list(range(torch.cuda.device_count()))

    ctx = multiprocessing.get_context('spawn')

    processes = [ctx.Process(target=mp_worker, args=(gpui,)) for gpui in gpus]
    for process in processes:
        process.start()
    for process in processes:
        process.join()
~                        
```

**Comment by ezyang** [comment] 2019-01-07 05:48
Hmm, fixing this may involve a semi-involved rewrite of fork handling logic in `torch/cuda/__init__.py`. The basic problem is we only have a single concept of "initialized" (having called `_lazy_init`) which requires a valid CUDA driver, but we must poison future forks as soon as we do a call to `cudaGetDeviceCount`, which is sufficient to "initialize" the CUDA API. I'll try a simple version of the patch to see if it works though.

**Comment by ayl** [comment] 2019-01-07 09:31
It would be great to be able to use fork instead of spawn since there are some advantages to fork. Also it is useful to know how many GPUs are available so that you know how many processes to start. 

A few possible workarounds:
1. Start a process that returns `torch.cuda.device_count()` and block until that process finishes. Then start the rest of the processes.
2. Use something like [GPUtil](https://github.com/anderskm/gputil) which makes a system call to nvidia-smi to gather GPU information.

**Comment by ezyang** [comment] 2019-01-07 13:44
Yeah, I think it would be reasonable to come up with some out-of-process way to get the device info. But it's hard to tell what a good UX for this would be: you don't want this to be default because many users are not multiprocessing (and spawning new processes on Windows is hella expensive).

**Comment by EvenOldridge** [comment] 2019-05-02 04:30
@ezyang I'm running into this same issue when trying to launch multiprocessing dataloaders with datasets that use cuda.  You mention:

>You can use the spawn method instead. But you also have to make sure you wrap the parent script in an if __name__ == '__main__' block or you'll get an oblique error message about freeze_support:

Is there a workaround if you're using jupyter notebooks rather than a script?  I tried the spawn method but it still has the same error for me.

**Comment by ezyang** [comment] 2019-05-07 14:22
I don't know too much about Jupyter notebooks. But one thing to take care about is out-of-order execution; you really need to make sure that you spawn the subprocesses before you do any CUDA processing; just being at the top of the notebook is insufficient.

**Comment by EvenOldridge** [comment] 2019-05-07 17:35
One issue I ran into and was able to resolve was to make sure that any classes being used were wrapped in a module (per: https://stackoverflow.com/questions/48593694/python-multiprocessing-returning-attributeerror-when-following-documentation-cod)

I'm still running into invalid device memory issues when I try to share cuda tensors across different spawned processes though.  Unfortunately for what I'm trying to do (RAPIDS preprocessing of data before the dataloader) I'm forced into CUDA calls before the dataloader inits.

**Comment by ezyang** [comment] 2019-05-10 18:25
@EvenOldridge Invalid device memory sounds like a different problem. Do you want to file a separate issue for it?

Also, #20375 may be relevant to people on this thread.

**Comment by EvenOldridge** [comment] 2019-05-15 15:50
@ezyang I was able to figure it the invalid memory issues.  You're right, it was an embeddingbag layer that was receiving indexes outside of its range.

**Comment by ezyang** [comment] 2019-07-19 17:11
Closing this as a dupe of #17357 which is later but has a more detailed discussion on how to fix.

**Closed by ezyang** 2019-07-19 17:11 UTC
Labels: module: cuda, triaged
