### ISSUE TITLE
[inductor][cpu]6 models functionality gap between AMP dynamic shape and AMP static shape

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#119434] opened 2024-02-08 02:21 UTC
### 🐛 Describe the bug

below 6 models passed in AMP static shape, but failed in AMP dynamic shape.
<p></p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>accuracy</th>
      <th>perf</th>
      <th>suite</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_T5_generate</td>
      <td>X</td>
      <td>√</td>
      <td>torchbench</td>
    </tr>
    <tr>
      <td>pyhpc_isoneutral_mixing</td>
      <td>X</td>
      <td>√</td>
      <td>torchbench</td>
    </tr>
    <tr>
      <td>detectron2_fcos_r_50_fpn</td>
      <td>X</td>
      <td>X</td>
      <td>torchbench</td>
    </tr>
    <tr>
      <td>llama</td>
      <td>√</td>
      <td>X</td>
      <td>torchbench</td>
    </tr>
    <tr>
      <td>pyhpc_equation_of_state</td>
      <td>√</td>
      <td>X</td>
      <td>torchbench</td>
    </tr>
    <tr>
      <td>pyhpc_turbulent_kinetic_energy</td>
      <td>X</td>
      <td>X</td>
      <td>torchbench</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>7b9dec1</td>
      <td>735715e</td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>ff42d907</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>b2d9c3e</td>
      <td>#3723</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td>#2167</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>a00a72b</td>
      <td>#8096</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td>#1147</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>

</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance/accuracy torchbench **model** amp first dynamic default
cc @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment] 2024-02-15 11:09
Hi @jiayisunx, Could you help to take a look of 

- hf_T5_generate
- pyhpc_isoneutral_mixing
- detectron2_fcos_r_50_fpn

I will look into 

- llama
- pyhpc_equation_of_state
- pyhpc_turbulent_kinetic_energy

**Comment by leslie-fang-intel** [comment] 2024-02-15 12:33
Update the failure of `pyhpc_equation_of_state` and `pyhpc_turbulent_kinetic_energy`
- It also failed with CUDA BF16 dynamic case and FP32 dynamic case
- Failure msg is: 
```
  File "/old-root/home/leslie/inductor_quant/pytorch/benchmarks/dynamo/common.py", line 3846, in run
    assert marked, f"nothing in example_inputs had a dim with {batch_size}"
AssertionError: nothing in example_inputs had a dim with 1048576
```

- Root-Cause is:
  - The default running batch size is 1048576; https://github.com/pytorch/benchmark/blob/dbc109791dbb0dfb58775a5dc284fc2c3996cb30/torchbenchmark/models/pyhpc_turbulent_kinetic_energy/__init__.py#L127
  - The example_inputs's size does not equal to this batch size directly but with some mathematic relationship: https://github.com/pytorch/benchmark/blob/dbc109791dbb0dfb58775a5dc284fc2c3996cb30/torchbenchmark/models/pyhpc_turbulent_kinetic_energy/__init__.py#L8-L63
  - When running with dynamic batch size, it only annotates the dimension when its size equals to this batch size. And in this case, there is no such dimension which causes the failure; https://github.com/pytorch/pytorch/blob/e5bfdde7ba32fecb0364783115eda6e21fb3e400/benchmarks/dynamo/common.py#L3863-L3877

**Comment by leslie-fang-intel** [comment] 2024-02-15 12:44
Update the Failure of llama BF16 Dynamic size:

- Failed also for FP32 dynamic shape

- Root-Casue is:

  - The batch size and seq_len are both 32 as in https://github.com/pytorch/benchmark/blob/dbc109791dbb0dfb58775a5dc284fc2c3996cb30/torchbenchmark/models/llama/__init__.py#L14-L22
  - When running with dynamic batch size, it will annotates all the dimension when its size equals to this batch size. And in this case, both the batch size and seq_len has been marked as dynamic which causes the failure; https://github.com/pytorch/pytorch/blob/e5bfdde7ba32fecb0364783115eda6e21fb3e400/benchmarks/dynamo/common.py#L3863-L3877
 
I think may be we can change the batch size from 32 to some other values which can workaround this failure.

**Comment by leslie-fang-intel** [comment] 2024-02-29 00:41
- `pyhpc_isoneutral_mixing`, `pyhpc_equation_of_state` and `pyhpc_turbulent_kinetic_energy` skipped to annotate as dynamic bs in https://github.com/pytorch/pytorch/pull/120599
- `LLama` dynamic shape failure is caused by dynamo issue and tracked in  https://github.com/pytorch/pytorch/issues/106110
- Transfer this issue to @jiayisunx for the remaining failure of `hf_T5_generate` and `detectron2_fcos_r_50_fpn`.

**Comment by jiayisunx** [comment] 2024-02-29 04:20
Update the failure of `detectron2_fcos_r_50_fpn`:
* Error msg is
```
  File "/home/jiayisun/pytorch/benchmarks/dynamo/common.py", line 3877, in run
    assert marked, f"nothing in example_inputs had a dim with {batch_size}"
AssertionError: nothing in example_inputs had a dim with 4
```

* Root Cause is
Benchmark code will only annotate the inputs' dim as dynamic when its size equals to batch size https://github.com/pytorch/pytorch/blob/c617e7b4076a5f968f5827040a07b013e45cd0c6/benchmarks/dynamo/common.py#L3867-L3871. If it fails to find any dim equals to batch size, above error throws.
However, the inputs of `detectron2_fcos_r_50_fpn` are as follows:

```
([{'file_name': '/home/jiayisun/benchmark/torchbenchmark/data/.data/coco2017-minimal/coco/val2017/000000001268.jpg', 'height': 427, 'width': 640, 'image_id': 1268, 'image': tensor([[[147., 124.,  82.,  ...,   3.,   4.,   5.],
         [125., 104.,  65.,  ...,   3.,   3.,   4.],
         [ 87.,  68.,  34.,  ...,   2.,   2.,   2.],
         ...,
         [ 47.,  45.,  41.,  ...,  45.,  45.,  45.],
         [ 46.,  44.,  40.,  ...,  44.,  45.,  46.],
         [ 46.,  44.,  40.,  ...,  43.,  45.,  46.]],

        [[154., 129.,  84.,  ...,   3.,   4.,   5.],
         [133., 110.,  69.,  ...,   3.,   3.,   4.],
         [ 95.,  76.,  43.,  ...,   2.,   2.,   2.],
         ...,
         [ 44.,  42.,  38.,  ...,  34.,  37.,  39.],
         [ 43.,  41.,  37.,  ...,  35.,  39.,  41.],
         [ 43.,  41.,  37.,  ...,  35.,  40.,  43.]],

        [[171., 140.,  85.,  ...,   3.,   4.,   5.],
         [147., 120.,  71.,  ...,   3.,   3.,   4.],
         [103.,  83.,  47.,  ...,   2.,   2.,   2.],
         ...,
         [ 46.,  44.,  40.,  ...,  16.,  20.,  22.],
         [ 45.,  43.,  39.,  ...,  17.,  22.,  26.],
         [ 45.,  43.,  39.,  ...,  18.,  24.,  28.]]])}, ... ],)
```

None of the inputs' dim will equal to input batch size, so I think we may need to skip the dynamic batch size testing for this model.

**Comment by jiayisunx** [comment] 2024-03-05 10:06
Update the failure of `hf_T5_generate`:

* Error msg is
```
  File "/home/jiayisun/pytorch/torch/_dynamo/guards.py", line 705, in SHAPE_ENV
    guards = output_graph.shape_env.produce_guards(
  File "/home/jiayisun/pytorch/torch/fx/experimental/symbolic_shapes.py", line 3253, in produce_guards
    raise ConstraintViolationError(
torch.fx.experimental.symbolic_shapes.ConstraintViolationError: Constraints violated (L['inputs_tensor'].size()[0])! For more information, run with TORCH_LOGS="+dynamic".
  - Not all values of RelaxedUnspecConstraint(L['inputs_tensor'].size()[0]) are valid because L['inputs_tensor'].size()[0] was inferred to be a constant (4).
```

* Root Cause is
This error happens while creating guard for this [model script line](https://github.com/huggingface/transformers/blob/main/src/transformers/models/t5/modeling_t5.py#L561): `scores += position_bias_masked`
I run it with TORCH_LOGS="+dynamic" and got the key line : `I0305 00:21:00.849974 140376923287424 torch/fx/experimental/symbolic_shapes.py:3963] [6/0_1] eval Eq(s0, 4) [guard added] at miniconda3/envs/pt2/lib/python3.9/site-packages/transformers/models/t5/modeling_t5.py:561 in forward (_refs/__init__.py:403 in _broadcast_shapes)`
The reason for this error is that the batch dimension of `inputs_tensor` in the dynamic batch size test is marked as dynamic shape `s0`, so the batch dimension of `scores` generated by a series of operations with `inputs_tensor` is also `s0`. However, because the function of creating `attention_mask` is not in Dynamo but in python. The batch dimension of `attention_mask` is the real shape `4`, and the batch dimension of `position_bias_masked` generated by a series of operations with `attention_mask` is also the real shape `4`, not the dynamic shape `s0`. The current line of `scores += position_bias_masked` requires creating a guard and check whether the batch dimension of `scores` is always equal to the batch dimension of `position_bias_masked`, Eq(s0, 4), the error happens.
So the root cause of this error is that the function of creating `attention_mask` not in Dynamo but in python. The reason why the function of `attention_mask` not in Dynamo is that Dynamo has a graph break on this function (happened in the [model script line](https://github.com/huggingface/transformers/blob/main/src/transformers/generation/utils.py#L476): `is_pad_token_in_inputs = (pad_token_id is not None) and (pad_token_id in inputs)`) due to the following error:
`torch._dynamo.exc.Unsupported: Tensor.item`

**Comment by leslie-fang-intel** [comment] 2024-06-14 00:39
Close this issue as the related PRs are all landed.

**Closed by leslie-fang-intel** 2024-06-14 00:39 UTC
Labels: triaged, oncall: cpu inductor
