### ISSUE TITLE
maybe_group && maybe_group == fused_cat ASSERT FAILED

### ISSUE THREAD

**Issue by Kaixhin** [pytorch/pytorch#20144] opened 2019-05-05 16:46 UTC
## 🐛 Bug

I get the following error during the backwards pass of a JITted model that I'm training. The trace is as follows:

```sh
Traceback (most recent call last):
  File "main.py", line 157, in <module>
    (observation_loss + reward_loss + kl_loss).backward()
  File "/home/kai/miniconda3/lib/python3.6/site-packages/torch/tensor.py", line 107, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/kai/miniconda3/lib/python3.6/site-packages/torch/autograd/__init__.py", line 93, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: maybe_group && maybe_group == fused_cat ASSERT FAILED at /opt/conda/conda-bld/pytorch-cpu_1556653093101/work/torch/csrc/jit/passes/graph_fuser.cpp:1223, please report a bug to PyTorch.
```

## To Reproduce

This is from my [PlaNet repo](https://github.com/Kaixhin/PlaNet), where I'm trying to replace `nn.GRUCell` with my own JIT variant:

```py
class GRUCell(jit.ScriptModule):
  __constants__ = ['hidden_size']

  def __init__(self, input_size, hidden_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.weight = nn.Parameter(torch.randn(input_size + hidden_size, 3 * hidden_size))
    self.bias = nn.Parameter(torch.randn(3 * hidden_size))

  @jit.script_method
  def forward(self, input, hidden):
    update, reset = torch.chunk(torch.sigmoid(torch.addmm(self.bias[:2 * self.hidden_size], torch.cat([input, hidden], dim=1), self.weight[:, :2 * self.hidden_size])), 2, dim=1)
    candidate = torch.tanh(torch.addmm(self.bias[2 * self.hidden_size:], torch.cat([input, reset * hidden], dim=1), self.weight[:, 2 * self.hidden_size:]))
    return update * hidden + (1 - update) * candidate
```

## Environment

```
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.1.0
[pip] torchvision==0.2.2
[conda] blas                      1.0                         mkl  
[conda] cuda91                    1.0                  h4c16780_0    pytorch
[conda] faiss-cpu                 1.5.1            py36h6bb024c_1    pytorch
[conda] mkl                       2019.3                      199  
[conda] mkl_fft                   1.0.12           py36ha843d7b_0  
[conda] mkl_random                1.0.2            py36hd81dba3_0  
[conda] pytorch-cpu               1.1.0               py3.6_cpu_0    pytorch
[conda] torchvision-cpu           0.2.2                      py_3    pytorch
```

**Comment by ngimel** [comment] 2019-05-14 18:52
Hi @Kaixhin, I cannot reproduce your failure on a relatively fresh master with 
```
import torch
import torch.jit as jit
import torch.nn as nn

class GRUCell(jit.ScriptModule):
  __constants__ = ['hidden_size']

  def __init__(self, input_size, hidden_size):
    super().__init__()
    self.hidden_size = hidden_size
    self.weight = nn.Parameter(torch.randn(input_size + hidden_size, 3 * hidden_size))
    self.bias = nn.Parameter(torch.randn(3 * hidden_size))

  @jit.script_method
  def forward(self, input, hidden):
    update, reset = torch.chunk(torch.sigmoid(torch.addmm(self.bias[:2 * self.hidden_size], torch.cat([input, hidden], dim=1), self.weight[:, :2 * self.hidden_size])), 2, dim=1)
    candidate = torch.tanh(torch.addmm(self.bias[2 * self.hidden_size:], torch.cat([input, reset * hidden], dim=1), self.weight[:, 2 * self.hidden_size:]))
    return update * hidden + (1 - update) * candidate



m = GRUCell(1024,1024).cuda()
input = torch.randn(128, 1024, device="cuda").requires_grad_(True)
hidden = torch.randn(128, 1024, device="cuda").requires_grad_(True)
out = m(input, hidden)
gO = torch.rand_like(out)
out.backward(gO)
torch.cuda.synchronize()
```
Can you please provide either a small repro, or instructions on how to reproduce it from your PlaNet repo?

**Comment by Kaixhin** [comment] 2019-05-14 19:01
@ngimel just ran your script on my Mac (no CUDA) and Ubuntu desktop (no CUDA) and got the same error as before. However, running with CUDA there was no error. I'm using 1.1 on all of these machines.

**Comment by ngimel** [comment] 2019-05-14 20:15
Can confirm that it breaks on cpu-only builds. Just running the example on the cpu, but with cuda-enabled build is still fine.

**Comment by bhosmer** [comment] 2019-12-13 06:47
CPU-only build runs example (repointed to cpu) with no errors, closing

**Closed by bhosmer** 2019-12-13 06:47 UTC
Labels: high priority, jit, topic: assert failure, triaged
