### ISSUE TITLE
iOS predict got different result in simulator and device

### ISSUE THREAD

**Issue by yyang9887** [pytorch/pytorch#39506] opened 2020-06-04 05:15 UTC
## 🐛 Bug

A CRNN model with  [1,1,32, w] input can get correct predict  result in iOS simulator , but when I use iOS device , predict result is no correct. 
I have checked the model in ubuntu, Android simulator and Android device. They all no problem.
I am using pod install libtorch=1.5.0.  I  also try 1.4.0 and got same result.
Is there any different between libtorch 1.5.0 x86_64 and arm64 version?

My iOS code is based on https://github.com/pytorch/ios-demo-app/tree/master/HelloWorld
I only modify model and input image shape.

## Environment
XCode 11.4
iOS simulator (predict OK) & iPhone 11 device (predict  NG)
pod install libtorch 1.5.0 & 1.4.0

my CRNN model:
https://drive.google.com/uc?export=download&confirm=WNrX&id=1xb5-icIM1Rpd6f-Aaut1HNDcJfEZuc9X

**Comment by husthyc** [comment] 2020-06-04 18:45
@yyang9887 This issue is duplicated with https://github.com/pytorch/pytorch/issues/38186. Root cause found, working on the solution.

**Comment by xta0** [comment] 2020-06-07 23:05
Duplicated with #38186. Close it for now.

**Closed by xta0** 2020-06-07 23:05 UTC
Labels: mobile, module: ios, triaged
