### ISSUE TITLE
[jit] Slice assignment is completely elided in Onnx graph

### ISSUE THREAD

**Issue by daiwei89** [pytorch/pytorch#19948] opened 2019-04-30 05:28 UTC
## 🐛 Bug

Assignments like `a[:2] = x` is elided in ONNX graph.

## To Reproduce

Runs this code:

```
import torch

class TestModule(torch.nn.Module):
    def __init__(self):
        super(TestModule, self).__init__()

    def forward(self, x):
        a = x.repeat([3,2])
        a[:2] = x*2
        return a

onnx_path = "slice_assign.onnx"
model = TestModule()
torch_in = (torch.randint(0, 10, (2, 1)), )
torch.onnx.export(model, torch_in, onnx_path, verbose=True)
```

Observe in the output below that `2*x` is elided in Onnx graph.

```
slice_assign.py:9: TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect, because all other views that also reference this data will not not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
  a[:2] = x*2
graph(%0 : Long(2, 1)) {
  %1 : int[] = onnx::Constant[value= 3  2 [ CPULongType{2} ]]()
  %2 : Long(6, 2) = onnx::Tile(%0, %1), scope: TestModule
  return (%2);
}
```

## Environment

Collecting environment information...
PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.5
GCC version: Could not collect
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

**Comment by suo** [comment] 2019-04-30 20:38
@houseroad, can you take a look at this?

**Comment by houseroad** [comment] 2019-04-30 22:15
Please don't ignore the following warning:
```
TracerWarning: There are 2 live references to the data region being modified when tracing in-place operator copy_ (possibly due to an assignment). This might cause the trace to be incorrect,
because all other views that also reference this data will not reflect this change in the trace! On the other hand, if all other views use the same memory chunk, but are disjoint (e.g. are outputs of torch.split), this might still be safe.
```
We have checked the jit graph before converting to onnx graph:

```
jit graph:  graph(%0 : Long(2, 1)):
  %149 : int[] = prim::Constant[value=[3, 2]]()
  %5 : Long(6, 2) = aten::repeat(%0, %149), scope: TestModule
  return (%5)
```

I think the reason is that you did in-place update, and tracer didn't trace it correctly. The root cause is in tracer :-)

**Comment by houseroad** [comment] 2019-05-09 17:43
This is an expected behavior, and appropriate warning have sent out. So close the issue.

**Closed by houseroad** 2019-05-09 17:43 UTC
Labels: jit, module: onnx

**Comment by cong235** [comment] 2019-12-12 08:06
@houseroad How can fix it bro?
