### ISSUE TITLE
Conv3d with cudnn error

### ISSUE THREAD

**Issue by hukkai** [pytorch/pytorch#13636] opened 2018-11-06 20:30 UTC
When I use **torch.backends.cudnn.benchmark = True** in Conv3d, it returned error 
**RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR**

I tired **re -rf ~/.nv** but it doesn't work. The error only disappears when **torch.backends.cudnn.benchmark = False**.

Ubuntu 16.04.4 LTS Tesla P100 Cuda 9.0 cudnn 7.1 
pytorch 1.0.0a0+d03c6ba from source and 0.4.1 from pip both tried.

**Comment by zou3519** [comment] 2018-11-12 18:45
Could we get a repro? What are your input sizes?

**Comment by mruberry** [comment] 2021-05-12 04:02
Closing due to age and lack of reproduction; if this issue still occurs on the latest version of PyTorch please file a new issue

**Closed by mruberry** 2021-05-12 04:02 UTC
