### ISSUE TITLE
nonzero doesn't squeeze dimension

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#1834] opened 2017-06-17 21:15 UTC
`nonzero` isn't consistent with `sort` in terms of dimensions (though both return an indices vector).
```
>>> torch.rand(10).nonzero().size()
(10L, 1L)
>>> torch.rand(10).sort()[1].size()
(10L,)
```

**Comment by acgtyrant** [comment] 2017-06-30 09:42
I am amazing that this is not responded. The documentation of `torch.max` says:

```
>> a = torch.randn(4, 4)
>> a

0.0692  0.3142  1.2513 -0.5428
0.9288  0.8552 -0.2073  0.6409
1.0695 -0.0101 -2.4507 -1.2230
0.7426 -0.7666  0.4862 -0.6628
torch.FloatTensor of size 4x4]

>>> torch.max(a, 1)
(
 1.2513
 0.9288
 1.0695
 0.7426
[torch.FloatTensor of size 4]
,
 2
 0
 0
 0
[torch.LongTensor of size 4]
)
```

But I reproduced this code in PyTorch v0.1.12, the size of the results changed:

```
>> a = torch.randn(4, 4)
>> a

-1.8528 -2.6025  0.7865 -0.9720
-0.5096  1.2832  0.9036  0.6411
 0.3368 -0.1593  0.0521  0.4321
 0.8267  0.0115  0.7012  2.3030
[torch.FloatTensor of size 4x4]

>> torch.max(a, 1)

(
  0.7865
  1.2832
  0.4321
  2.3030
 [torch.FloatTensor of size 4x1], 
  2
  1
  3
  3
 [torch.LongTensor of size 4x1])
```

I watched the same phenomenon for `min`.

Is the documentation outdated? Or is it just a bug? @soumith

**Comment by vadimkantorov** [comment] 2017-06-30 10:23
Default documentation (the one you linked - http://pytorch.org/docs/master/torch.html#torch.max) reflects the `master` branch, not v0.1.12

**Comment by soumith** [comment] 2017-06-30 14:59
Yes, in master (and 0.2) we are making `keepDim=False`as the default. This is `0.1.12`'s documentation http://pytorch.org/docs/0.1.12/torch.html#torch.max

**Comment by alykhantejani** [comment] 2017-10-17 15:40
@soumith do we just want to squeeze the result of `nonzero` here and make a backwards incompatible change? (happy to send a PR)

**Comment by gokceneraslan** [comment] 2017-11-01 18:34
👍  for making `nonzero()` compatible with numpy. Current nonzero() output cannot be used for indexing e.g. `z[x.nonzero()] = 2.0` would be convenient. AFAIK it cannot be used with index_select or index_fill as well.

**Comment by acgtyrant** [comment] 2017-11-02 07:51
I vote to follow numpy befavior too.

**Comment by davidbau** [comment] 2017-12-14 06:24
Another reason to resemble numpy: the pytorch sparse API COO format is also sideways from the output of nonzero (but matches the orientation as numpy).  Would make sense to allow a sparse constructor to plug directly in to nonzero().

**Comment by gchanan** [comment] 2017-12-14 15:55
Yet another reason to follow numpy: other functions that we want to implement return nonzero-style formatting (e.g. `where` with a single parameter) and we will need to call out this difference in multiple places.

**Comment by hughperkins** [comment] 2018-09-13 14:06
I use `nonzero` all over the place, in performance critical sections, where the result is a cuda tensor:

```
# input: some_mask, some_tensor (both cudarized)
idxes = some_mask.view(-1).nonzero().long().view(-1)
some_tensor = some_tensor[idxes]
```

Preference to at least provide the functionality of changing from a mask into indices efficiently using some other differnetly-named function, if it becomes preferable to change the functionality of nonzero itself.

**Comment by fmassa** [comment] 2018-09-13 14:12
You can do something like
```python
def numpy_nonzero(tensor):
    return torch.unbind(tensor.nonzero(), 1)

idxs = numpy_nonzero(some_mask)
some_tensor = some_tensor[idxs]
```

Since the addition of tensors with 0 in its dimensions, the amount of workaround you need to do becomes way smaller.
Also, note that you can just as well do
```python
some_tensor = some_tensor[mask]
```
which internally performs `nonzero` for you.

**Comment by fmassa** [comment] 2018-09-13 14:52
oh, about returning tuples, it actually doesn't construct a tuple with python numbers, but just a tuple with tensors. So there is no overhead / synchronization happening.

If you want to apply the same mask to multiple tensors, then performing the `nonzero` before is indeed more efficient.

**Comment by yf225** [comment] 2018-09-13 16:40
I am going to put this task back to the pool, in case anyone is interested in picking it up.

**Comment by gchanan** [comment] 2019-05-06 21:19
https://github.com/pytorch/pytorch/issues/2228 seems like the relevant overall issue.

**Comment by umanwizard** [comment] 2019-05-13 22:30
closing this since it is basically a dupe of #20293

**Closed by umanwizard** 2019-05-13 22:30 UTC
Labels: module: docs, module: numpy, triaged

**Comment by vadimkantorov** [comment] 2019-05-14 08:46
@umanwizard super-duper :) glad to know it's about to be fixed :)
