### ISSUE TITLE
[PyTorch] Don't use scientific notation for printing integer tensors

### ISSUE THREAD

**Issue by colesbury** [pytorch/pytorch#6865] opened 2018-04-23 15:33 UTC
We currently use scientific notation (E-notation) to print large integer tensors. We shouldn't do this because it hides meaningful digits and because E-notation corresponds to floating point data types in Python.

```python
>>> x = torch.ones(525076, dtype=torch.int)
>>> x.sum()
tensor(5.2508e+05)
>>> x.sum().item()
525076
```

**Comment by SsnL** [comment] 2018-04-23 15:39
duplicate of https://github.com/pytorch/pytorch/issues/6811

**Comment by superbobry** [comment] 2018-05-04 13:15
I can look into fixing this unless someone is already on it.

**Comment by fmassa** [comment] 2018-05-04 19:00
@li-roy are you working on this?

**Comment by li-roy** [comment] 2018-05-04 21:41
@fmassa @superbobry Yeah I'm working on all of the tensor issues.

**Closed** 2018-06-14 06:57 UTC
Labels: 0.4, high priority, printing
