### ISSUE TITLE
List as a python constant type in script

### ISSUE THREAD

**Issue by li-roy** [pytorch/pytorch#27771] opened 2019-10-11 20:02 UTC
Currently, it's not possible to script a constant python list:

Suppose in module
```
LIST = [1,2,3]
TUPLE = (1,2,3)
```

```
for a in module.LIST:
   # stuff
```

Proposal is to make this behave like tuple
```
for a in module.TUPLE:
   # stuff
```

We can work around this by converting the list to a tuple outside of script, but it seems like something that script should be able to do.

cc @suo

**Comment by eellison** [comment] 2019-10-14 20:31
I don't think we're going to do this because we only bind to constant python values. For this reason we don't close over tensors either.

Also in the future it would be helpful to post a reproducible example so less context is needed to understand the issue.

**Comment by eellison** [comment] 2019-10-14 20:33
If someone else runs into this or @li-roy you want to discuss it further please reopen. I am going to close it for now.

**Closed** 2019-10-14 20:33 UTC
Labels: jit, triaged
