### ISSUE TITLE
torchvision MaskRCNN export to ONNX throws error; onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (ConstantOfShape_1966) Op (ConstantOfShape) [ShapeInferenceError] Invalid shape value: 0 

### ISSUE THREAD

**Issue by ankitdhall** [pytorch/pytorch#33489] opened 2020-02-19 10:45 UTC
## 🐛 Bug

MaskRCNN ONNX model fails to load when reading from disk or from buffer. However, FasterRCNN loads from buffer without errors but throws error when loading from disk. The ONNX model is generated by converting a PyTorch model. The test script has been inspired from the tests in the PyTorch repo. The model is from `torchvision` model zoo, MaskRCNN and FasterRCNN converted with opset=11.

## To Reproduce

```python
import numpy as np
import torch
import torchvision
import onnxruntime
import onnx

import io
import copy

import argparse


def ort_test_with_input(ort_sess, input, output, rtol, atol):
    input, _ = torch.jit._flatten(input)
    output, _ = torch.jit._flatten(output)

    def to_numpy(tensor):
        if tensor.requires_grad:
            return tensor.detach().cpu().numpy()
        else:
            return tensor.cpu().numpy()

    inputs = list(map(to_numpy, input))
    outputs = list(map(to_numpy, output))

    ort_inputs = dict((ort_sess.get_inputs()[i].name, input) for i, input in enumerate(inputs))
    ort_outs = ort_sess.run(None, ort_inputs)

    # compare onnxruntime and PyTorch results
    assert len(outputs) == len(ort_outs), "number of outputs differ"

    # compare onnxruntime and PyTorch results
    [np.testing.assert_allclose(out, ort_out, rtol=rtol, atol=atol) for out, ort_out in zip(outputs, ort_outs)]


def run_model_test(model,
                   batch_size=2,
                   state_dict=None,
                   input=None,
                   use_gpu=True,
                   rtol=0.001,
                   atol=1e-7,
                   example_outputs=None,
                   do_constant_folding=True,
                   dynamic_axes=None,
                   test_with_inputs=None,
                   input_names=None,
                   output_names=None,
                   fixed_batch_size=False,
                   save_and_read_from_disk=False):
    model.eval()

    if input is None:
        input = torch.randn(batch_size, 3, 224, 224, requires_grad=True)

    with torch.no_grad():
        if isinstance(input, torch.Tensor):
            input = (input, )
        # In-place operators will update input tensor data as well.
        # Thus inputs are replicated before every forward call.
        input_copy = copy.deepcopy(input)
        output = model(*input_copy)
        if isinstance(output, torch.Tensor):
            output = (output, )

        # export the model to ONNX
        if save_and_read_from_disk:
            f = "mrcnn_test.onnx"
        else:
            f = io.BytesIO()
        input_copy = copy.deepcopy(input)
        torch.onnx.export(model,
                          input_copy,
                          f,
                          opset_version=11,
                          example_outputs=output,
                          do_constant_folding=True,
                          dynamic_axes=dynamic_axes,
                          input_names=input_names,
                          output_names=output_names)

        # compute onnxruntime output prediction
        if save_and_read_from_disk:
            print('checking model: {} file'.format(f))
            loaded_model = onnx.load(f)
            onnx.checker.check_model(loaded_model)
            ort_sess = onnxruntime.InferenceSession(loaded_model)
        else:
            ort_sess = onnxruntime.InferenceSession(f.getvalue())
        input_copy = copy.deepcopy(input)
        ort_test_with_input(ort_sess, input_copy, output, rtol, atol)

        # if additional test inputs are provided run the onnx
        # model with these inputs and check the outputs
        if test_with_inputs is not None:
            for test_input in test_with_inputs:
                if isinstance(test_input, torch.Tensor):
                    test_input = (test_input, )
                test_input_copy = copy.deepcopy(test_input)
                output = model(*test_input_copy)
                if isinstance(output, torch.Tensor):
                    output = (output, )
                ort_test_with_input(ort_sess, test_input, output, rtol, atol)


def run(save_and_read_from_disk=False, mrcnn=False):
    if mrcnn:
        model = torchvision.models.detection.maskrcnn_resnet50_fpn(pretrained=True, min_size=200, max_size=300)
    else:
        model = torchvision.models.detection.faster_rcnn.fasterrcnn_resnet50_fpn(pretrained=True,
                                                                                 min_size=200,
                                                                                 max_size=300)
    model.eval()
    x = torch.randn(2, 3, 200, 300, requires_grad=True)
    run_model_test(model,
                   batch_size=2,
                   input=(x, ),
                   use_gpu=True,
                   rtol=1e-3,
                   atol=1e-5,
                   do_constant_folding=True,
                   dynamic_axes=None,
                   test_with_inputs=None,
                   input_names=None,
                   output_names=None,
                   fixed_batch_size=None,
                   save_and_read_from_disk=save_and_read_from_disk)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Run tests with ONNX')
    parser.add_argument('--save_and_read_from_disk',
                        action='store_true',
                        help='writes onnx to disk and then loads it to run test')
    parser.add_argument('--mrcnn', action='store_true', help='use maskrcnn or otherwise use fastercnn')
    args = parser.parse_args()
    run(save_and_read_from_disk=args.save_and_read_from_disk, mrcnn=args.mrcnn)

```
**MaskRCNN**
When running the above as `python from_torchvision_tests.py --mrcnn` gives `onnxruntime.capi.onnxruntime_pybind11_state.Fail: [ONNXRuntimeError] : 1 : FAIL : Node (ConstantOfShape_1966) Op (ConstantOfShape) [ShapeInferenceError] Invalid shape value: 0` while `python from_torchvision_tests.py --save_and_read_from_disk --mrcnn` throws `TypeError: Unable to load from type '<class 'onnx.onnx_ONNX_REL_1_6_ml_pb2.ModelProto'>`

**FasterRCNN**
When running the above as `python from_torchvision_tests.py` runs without any errors while `python from_torchvision_tests.py --save_and_read_from_disk` throws the aforementioned.

## Expected behavior

Loading from disk should not change behavior and work without errors instead it throws error `TypeError: Unable to load from type '<class 'onnx.onnx_ONNX_REL_1_6_ml_pb2.ModelProto'>`. It seems to not work for either MaskRCNN or FasterRCNN. FasterRCNN does not throw errors when loaded from buffer but MaskRCNN throws a new error in this case.

## Environment

```
PyTorch version: 1.5.0.dev20200217
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 435.21
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.5.0.dev20200217
[pip3] torchvision==0.6.0.dev20200217
[conda] Could not collect

- ONNX Runtime installed from (source or binary):pip
- ONNX Runtime version: onnxruntime (1.1.1)  onnx (1.6.0) 
```

## Additional context

**FasterRCNN Screenshots**
Without errors:
![image](https://user-images.githubusercontent.com/8938083/74826242-8b989600-530b-11ea-85e7-16969aefa80d.png)

With error:
![image](https://user-images.githubusercontent.com/8938083/74826318-aec34580-530b-11ea-9170-aa21f832badb.png)

**MaskRCNN screenshots**
Loading from buffer error:
![image](https://user-images.githubusercontent.com/8938083/74843122-c4486780-532b-11ea-8322-9e1bd834f0bf.png)

Loading from disk error:
![image](https://user-images.githubusercontent.com/8938083/74843200-e0e49f80-532b-11ea-8a89-8eab0b5a652f.png)

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @fmassa

**Comment by garymm** [comment] 2022-03-01 22:29
Things working differently from disk vs in-memory is probably an issue with ONNX Runtime or your particular installation of it.
The failure to load MaskRCNN from in-memory seems like it could be a separate issue.
I was unable to reproduce that using:

torch 1.10.0+cu111, torchvision 0.11.1+cu111, onnxruntime 1.10.0

Closing since there doesn't appear to be any bug in `torch.onnx.export`. If you have issues with loading models (e.g., in-memory vs on-disk), open an issue with onnxruntime.

**Closed by garymm** 2022-03-01 22:29 UTC
Labels: module: onnx, triaged, module: vision
