### ISSUE TITLE
MPS: `torch.nn.Linear`/`torch.nn.functional.linear` returns incorrect results for some shapes

### ISSUE THREAD

**Issue by danieldk** [pytorch/pytorch#97239] opened 2023-03-21 11:48 UTC
### 🐛 Describe the bug

`torch.nn.Linear`/`torch.nn.functional.linear` returns incorrect results for some shapes when using the MPS backend. It seems that the number of errors increases with the input size. Here is a reproducer:

```
import torch.nn as nn

def print_stats(y, y_p):
    abs_diff = (y - y_p).abs()
    items_different = (abs_diff > 1e-3).int().sum()

    print(
        f"linear diff sum: {abs_diff.sum()}"
    )
    print(
        f"items different (> 1e-3): {items_different} ({100*(int(items_different) / y.numel())}%)"
        )


x_cpu = torch.rand((253, 144, 768), dtype=torch.float32)

# This works, it seems like if you go higher than 129 in
# the second dimension, the errors start piling up.
# x_cpu = torch.rand((253, 129, 768), dtype=torch.float32)

linear_cpu = nn.Linear(in_features=x_cpu.shape[-1], out_features=3 * x_cpu.shape[-1])
linear_cpu.eval()
y_cpu = linear_cpu(x_cpu)

x_mps = x_cpu.to("mps")
linear_mps = linear_cpu.to("mps")

print("=== MPS Linear ===")
y_mps = linear_mps(x_mps)
print_stats(y_mps.to("cpu"), y_cpu)

print("=== MPS matmul ===")
y_mps_matmul = x_mps @ linear_mps.weight.t() + linear_mps.bias
print_stats(y_mps_matmul.to("cpu"), y_cpu)
```

Output:

```
=== MPS Linear ===
linear diff sum: 2246469.5
items different (> 1e-3): 8421751 (10.033140841918582%)
=== MPS matmul ===
linear diff sum: 5.270101547241211
items different (> 1e-3): 0 (0.0%)
```

As stated in the comments, everything works fine with an input of shape `(253, 129, 768)`, however, once the second dimension is increased to `130` part of the output is erroneous.

When manually inspecting the output, it seems that the trailing rows are incorrect (they just have repeating float patterns).

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.26.0
Libc version: N/A

Python version: 3.10.10 (main, Feb 22 2023, 11:52:44) [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Max

Versions of relevant libraries:
[pip3] mypy==1.0.1
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.2
[pip3] torch==2.0.0
[conda] Could not collect
```

cc @ezyang @gchanan @zou3519 @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by qqaatw** [comment] 2023-03-21 13:10
I'm not able to reproduce this on macOS 12.6. Probably a bug comes from macOS 13.

**Comment by albanD** [comment] 2023-03-21 22:36
Tentatively high priority as it might be a regression.

**Comment by DenisVieriu97** [comment] 2023-03-21 22:40
Same as https://github.com/pytorch/pytorch/issues/95188.
This was fixed in macOS13.3. @danieldk could you please update to latest macOS and let me know if you still see any issues?

**Comment by danieldk** [comment] 2023-03-22 08:41
Thanks! Updating to the 13.3 release candidate solves the issue, also in spaCy (where we bumped into this). For working around this: is this only an issue in 13.2.x (so anything prior 13.2 is fine)?

**Comment by kulinseth** [comment] 2023-03-23 18:14
Thanks @danieldk for checking. Yeah, so working around, please update to MacOS 13.3 (when the release goes out).

**Closed** 2023-03-23 18:16 UTC
Labels: triage review, triaged, module: mps

**Comment by danieldk** [comment] 2023-04-17 12:43
The workaround was actually slightly faster in our case.
