### ISSUE TITLE
torch.compile fails with .view(dtype)

### ISSUE THREAD

**Issue by mobicham** [pytorch/pytorch#120998] opened 2024-03-01 14:56 UTC
### 🐛 Describe the bug
``` torch.compile ``` fails when there's a dtype view call from float to int:

Here's a minimal code to reproduce it:
``` Python
import torch
@torch.compile()
def call(data):
	return data.view(torch.uint8) + 1

data = torch.randint(0, 2**4, [4096, 4096], device='cuda', dtype=torch.uint8)
out = call(data) #OK 
out = call(data.view(torch.float16)) #Error 
``` 
``` Python
BackendCompilerFailed: backend='inductor' raised:
LoweringException: NotImplementedError: bitcast torch.float16 to different bitwidth type torch.uint8 is not supported yet.
```

Wrapping the view call inside another function with ```torch.jit.ignore``` doesn't work either. 

Is there by any chance a way to avoid this without converting types back and forth?
Thanks a lot in advance!

### Versions
```
Versions of relevant libraries:
PyTorch version: 2.1.2+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

Nvidia driver version: 535.129.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

OS: Ubuntu 22.04.3 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-89-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 12.2.140
CUDA_MODULE_LOADING set to: LAZY

[pip3] numpy==1.26.4
[pip3] onnxruntime==1.17.1
[pip3] open-clip-torch==2.24.0
[pip3] pytorch-triton==2.2.0+e28a256d71
[pip3] torch==2.1.2
[pip3] torchaudio==2.2.0.dev20231221+cu121
[pip3] torchvision==0.16.2
[pip3] triton==2.1.0
[conda] Could not collect
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @amjames @desertfire

**Comment by ezyang** [comment] 2024-03-04 05:09
I think we're supposed to just support this conversion

**Comment by mobicham** [comment] 2024-03-04 08:49
Seems like It only happens between types that don't have the same bit-width (uint8 <> float16), but int32 <> float32 works fine since both are 32-bit:

```Python 
import torch
@torch.compile()
def call(data):
	return data.view(torch.int32) + 1

data = torch.randint(0, 2**4, [4096, 4096], device='cuda', dtype=torch.int32)
out = call(data) #OK 
out = call(data.view(torch.float32)) #OK 
```

**Comment by desertfire** [comment] 2024-03-04 21:55
We can make it a fallback op in this case, since this is likely not a common use case.

**Comment by hgl71964** [comment] 2024-03-10 15:12
there's a type conversionn: https://github.com/pytorch/pytorch/blob/660ec3d38d9d1c8567471ae7fe5b40ae7c6d7438/torch/_inductor/lowering.py#L527

should we just use it instead of raising exception?

**Comment by tfiala** [comment] 2024-03-12 04:30
I think I'll take a swing at this!

**Comment by tfiala** [comment] 2024-03-12 06:55
I was able to reproduce the reported issue:
```python
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
LoweringException: NotImplementedError: bitcast torch.float16 to different bitwidth type torch.uint8 is not supported yet.
  target: aten.view.dtype
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg1_1', layout=FixedLayout('cuda', torch.float16, size=[4096, s0], stride=[s0, 1]))
  ))
  args[1]: torch.uint8
```

**Comment by peterbell10** [comment] 2024-03-12 14:37
`torch.compile` is completely separate from `torch.jit`, you're probably looking for `torch._dynamo.disable`.

**Comment by mobicham** [comment] 2024-03-12 14:47
Thanks for your comment @peterbell10 . ```torch.jit.ignore``` actually works for example to ignore aten/cuda calls that are not compatible with ```torch.compile```, at least for me it has been useful like here: https://github.com/mobiusml/hqq/blob/master/hqq/core/quantize.py#L454

**Comment by tfiala** [comment] 2024-03-12 21:30
Question #1 is: are there bit-width-changing combinations that make no sense for correctness? For example, reducing # bits (16 bit -> 8 bit) is losing some bits of precision/range.  Would the expectation here be that bit-shrinking is outright not supported? Or is it valid if all the values are able to be represented -- maybe within some tolerance -- at a reduced bitdepth?

i.e. Where is this even valid to do?  Some use cases would be great.

**Comment by tfiala** [comment] 2024-03-12 22:55
So I gave [this idea from earlier](https://github.com/pytorch/pytorch/issues/120998#issuecomment-1987264618) a shot just to try it out.

I used a slightly modified script to see what would happen (I wanted to see if and how it was going to mess up the values, also using a fixed generator seed so this is repeatable):
```python
import torch


@torch.compile()
def call(data):
    return data.view(torch.uint8) + 1


@torch.compile()
def print_tensor(data):
    print(data)


generator = torch.Generator(device="cuda").manual_seed(1234567890)

data = torch.randint(
    0, 2**4, [4096, 4096], generator=generator, device="cuda", dtype=torch.uint8
)
print("unmodified random tensor (uint8):")
print(data)

out = call(data)  # OK
print("random tensor + 1 (uint8):")
print(out)

out = call(data.view(torch.float16))  # was error
print("random tensor cast to float16, then back to uint8, then + 1:")
print(out)

print("random tensor cast to float16:")
print_tensor(data.view(torch.float16))
```

What I get looks like the `to_dtype()` call is not actually converting the values:

```
tensor([[14,  0,  9,  ...,  3,  6,  9],
        [ 9, 15, 10,  ...,  9,  5,  6],
        [11, 15, 12,  ..., 14,  1,  5],
        ...,
        [ 0, 12, 11,  ...,  7, 10,  3],
        [ 5,  9, 15,  ...,  8,  7,  8],
        [13,  2, 14,  ..., 11, 14,  7]], device='cuda:0', dtype=torch.uint8)
random tensor + 1 (uint8):
tensor([[15,  1, 10,  ...,  4,  7, 10],
        [10, 16, 11,  ..., 10,  6,  7],
        [12, 16, 13,  ..., 15,  2,  6],
        ...,
        [ 1, 13, 12,  ...,  8, 11,  4],
        [ 6, 10, 16,  ...,  9,  8,  9],
        [14,  3, 15,  ..., 12, 15,  8]], device='cuda:0', dtype=torch.uint8)
random tensor cast to float16, then back to uint8, then + 1:
tensor([[1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        ...,
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1],
        [1, 1, 1,  ..., 1, 1, 1]], device='cuda:0', dtype=torch.uint8)
random tensor cast to float16:
tensor([[8.3447e-07, 1.5795e-05, 1.0753e-04,  ..., 2.1482e-04, 4.6253e-05,
         1.5330e-04],
        [4.2939e-04, 1.2326e-04, 2.4509e-04,  ..., 6.1274e-05, 1.5366e-04,
         9.1851e-05],
        [4.2987e-04, 1.5402e-04, 6.5565e-07,  ..., 1.6093e-05, 3.6788e-04,
         7.6354e-05],
        ...,
        [2.4414e-04, 1.0747e-04, 3.0577e-05,  ..., 2.1482e-04, 1.0717e-04,
         4.6372e-05],
        [1.5318e-04, 9.2447e-05, 2.4414e-04,  ..., 4.6432e-05, 1.2374e-04,
         1.2290e-04],
        [3.1292e-05, 3.6955e-04, 3.1114e-05,  ..., 7.6830e-05, 2.1362e-04,
         1.0765e-04]], device='cuda:0', dtype=torch.float16)
```

So it looks like, at the very least, there needs to be some element-wise real conversion that would need to take place, at least in the case of allowable conversions (e.g. the uint8 to float16) that would either need to be called or written if they don't exist.

**Comment by tfiala** [comment] 2024-03-12 23:26
If, instead, I start with the existing code and I just take out the bitness-diff guard only, I make it a little further and then fail in a triton step (which is what that initial guard was trying to prevent, but probably gets me closer to what potentially needs to be implemented):
```python
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
CompilationError: at 7:34:def triton_(in_ptr0, out_ptr0, xnumel, XBLOCK : tl.constexpr):
    xoffset = tl.program_id(0) * XBLOCK
    xindex = xoffset + tl.arange(0, XBLOCK)[:]
    xmask = xindex < xnumel
    x0 = xindex
    tmp0 = tl.load(in_ptr0 + (x0), None).to(tl.float32)
    tmp1 = tmp0.to(tl.float16).to(tl.uint8, bitcast=True).to(tl.float32)
                                  ^
ValueError('Cannot bitcast data-type of size 16 to data-type of size 8')
```

**Comment by tfiala** [comment] 2024-03-12 23:40
For this part:
```python
@torch.compile()
def call(data):
    return data.view(torch.uint8) + 1

    ...

    out = call(data.view(torch.float16))  # was error
    print("random tensor cast to float16, then back to uint8, then + 1:")
    print(out)
```

the tensor is converted from a uint8 to a float16, then back to a uint8 without any intervening access points. It kinda seems like that could be optimized away at a layer above element operations if it was a lossless conversion.  (If it was not a lossless conversion, then the act of going by way of the bit conversion is actually doing something.)

**Comment by peterbell10** [comment] 2024-03-13 00:01
> Question 1 is: are there bit-width-changing combinations that make no sense for correctness? For example, reducing # bits (16 bit -> 8 bit) is losing some bits of precision/range. Would the expectation here be that bit-shrinking is outright not supported? Or is it valid if all the values are able to be represented -- maybe within some tolerance -- at a reduced bitdepth?

The expected behavior is to view the underlying memory as if it was a tensor of the dtype being viewed as, and differences in element size manifest as differences in shape. e.g.
```
import torch
a = torch.randn([10], dtype=torch.float32)
a.view(torch.uint8).shape
# torch.Size([40])
```

There isn't a straight-forward way to do this in triton, so it makes sense to just fallback to aten. See uses of `fallback_handler` in `torch/_inductor/lowering.py` for how to fall back to eager.

**Comment by peterbell10** [comment] 2024-03-13 00:06
> Thanks for your comment @peterbell10 . torch.jit.ignore actually works for example to ignore aten/cuda calls that are not compatible with torch.compile, at least for me it has been useful like here: https://github.com/mobiusml/hqq/blob/master/hqq/core/quantize.py#L454

I can see that `torch.jit.ignore` sets `fn._torchscript_modifier` and that torch dynamo doesn't interact with this attribute at all so I don't think this is right. Try removing the decorator and see if it was just compiling anyway. `torch.compile` should gracefully fallback on unsupported code without any decorators (modulo bugs of course).

**Comment by tfiala** [comment] 2024-03-13 02:07
> The expected behavior is to view the underlying memory as if it was a tensor of the dtype being viewed as

Ah okay, this makes more sense. Thanks, @peterbell10.

> There isn't a straight-forward way to do this in triton, so it makes sense to just fallback to aten. See uses of fallback_handler in torch/_inductor/lowering.py for how to fall back to eager.

Understood. Thanks!

That casts it as much more of a starter problem :-) (This is my first time in the codebase.)

**Comment by tfiala** [comment] 2024-03-13 03:22
Okay this fallback approach seems to work:
```diff
diff --git a/torch/_inductor/lowering.py b/torch/_inductor/lowering.py
index 9f575a9cfd2..d3d7b116f09 100644
--- a/torch/_inductor/lowering.py
+++ b/torch/_inductor/lowering.py
@@ -565,9 +565,8 @@ def to_dtype_bitcast(x: TensorBox, dtype: torch.dtype, *, copy=False):
     src_bits = _get_primitive_bitwidth(x_dtype)
     dst_bits = _get_primitive_bitwidth(dtype)
     if src_bits != dst_bits:
-        raise NotImplementedError(
-            f"bitcast {x_dtype} to different bitwidth type {dtype} is not supported yet."
-        )
+        # fallback to aten eager implementation for differing bitwidths
+        return fallback_handler(aten.view.dtype)(x, dtype)

     def _to_dtype_bitcast(x):
         # Because we may promote tensor type from float16 or bfloat16
```

It does the right thing per description [here](https://github.com/pytorch/pytorch/issues/120998#issuecomment-1992758918) -- the view on uint8 -> uint16 changes the shape and takes the underlying uint8, combining them in little-endian style at 16-bit entries.

I'll put that together in a PR and look to add a test in there.

**Comment by mobicham** [comment] 2024-03-13 08:42
Thank you very much for looking into this!

> i.e. Where is this even valid to do? Some use cases would be great.

@tfiala The main use-case is (QLoRA) distributed training of quantized models via FSDP. The quantized weights are either uint8 or int32, depending on the bit-packing logic. The issue is that FSDP expects float parameters. dtype view is an efficient way to solve this issue since there's no copy and the memory usage is the same.  So the solution is to do uint8/int32 -> view as float before applying FSDP on the model, and the dequantization step uses the view back to int.

**Comment by tfiala** [comment] 2024-03-14 20:32
You're welcome, @mobicham!

Just added a test for this in [this PR](https://github.com/pytorch/pytorch/pull/121786) and marked it ready for review once the CI comes back.

**Comment by bertmaher** [comment] 2024-03-15 18:27
@mobicham As an aside I've previously done uint8->float32 by using bit-shifts to build up an int32, and then using view(float32) on the result, like `(x + (y << 8) + (z << 16) + (w << 24)).view(torch.float32)`. 

In fact I landed this for embedding_bag_byte_unpack: https://github.com/pytorch/pytorch/blob/239d87af5e5fecec452214a5e6e5e204b51c0597/torch/_inductor/decomposition.py#L532-L537

On CPU, llvm is sometimes able to turn that pattern into an actual 0-cycle bitcast, which is pretty wild.  I'm not sure if Triton would do the same on GPU, but it would be cool to find out how well it works :-)

**Closed** 2024-03-15 19:33 UTC
Labels: oncall: quantization, good first issue, triaged, oncall: pt2, module: inductor

**Comment by tfiala** [comment] 2024-03-15 20:12
Yeah I think I will come back to this, @bertmaher, and look to see if I can do it within pytorch.compile() without falling back to eager mode at some point in the future. For now I will attack a few more starter problems to get my feet wet :-)

**Comment by mobicham** [comment] 2024-03-16 14:49
Thanks @bertmaher ! In our case, that would require bit-unpacking twice, because we already need to do bit-unpacking to reconstruct weights from their quantized format. We could instead pack the quantized weights directly with int16 instead of uint8/int32, so int16 <> fp16/bfp16 would work, and do the same for int32 <> fp32.

The cost of bit-unpacking is actually the main bottleneck in this story. ```torch.compile``` does offer a speed-up, but it really depends. For example, it''s pretty slow with int32 packing used for 3-bit, and if you use <a href="https://github.com/mobiusml/hqq/blob/master/hqq/core/bitpack.py#L110">```torch.cat``` to copy the chunks</a> instead of <a href="https://github.com/mobiusml/hqq/blob/master/hqq/core/bitpack.py#L129"> initializing an empty layer first </a>, it slows down the whole model inference by over 2x. So I ended up doing it in CUDA.
You can see in the barchat below the relative inference speed with a quantized Llama2-7B compared to native Pytorch using ```torch.compile``` on the dequantization step-only and the CUDA implementation of the dequantization step:  
![image](https://github.com/pytorch/pytorch/assets/37179323/6b425f6c-29f8-440b-9981-5c5f7bcac98a)

Would love to hear your take on this kind of stuff to make it more efficient!

**Comment by mobicham** [comment] 2024-04-29 13:30
@tfiala I just tried with 2.3.0+cu121 and it's still giving the same error:
```Python
import torch
@torch.compile()
def call(data):
	return data.view(torch.uint8) + 1

data = torch.randint(0, 2**4, [4096, 4096], device='cuda', dtype=torch.uint8)
out = call(data) #OK 
out = call(data.view(torch.float16)) #Error 
```

```Python
BackendCompilerFailed: backend='inductor' raised:
LoweringException: NotImplementedError: bitcast torch.float16 to different bitwidth type torch.uint8 is not supported yet.
  target: aten.view.dtype
  args[0]: TensorBox(StorageBox(
    InputBuffer(name='arg1_1', layout=FixedLayout('cuda', torch.float16, size=[4096, s0], stride=[s0, 1]))
  ))
  args[1]: torch.uint8
```

**Comment by jsuarez5341** [comment] 2024-05-18 18:21
```python
def compilable_cast(u8, dtype):
    n = dtype.itemsize
    bytes = [u8[..., i::n].to(dtype) for i in range(n)]
    if not LITTLE_BYTE_ORDER:
        bytes = bytes[::-1]

    bytes = sum(bytes[i] << (i * 8) for i in range(n))
    return bytes.view(dtype)
```
    
This seems to work and does not break compilation on 2.3

**Comment by mobicham** [comment] 2024-05-20 08:38
@jsuarez5341 this doesn't work, if `dtype=torch.float16` for example, it's not possible to do the shift operation.

**Comment by jsuarez5341** [comment] 2024-05-27 19:46
@mobicham Whoops. Does work for whatever size uint. Anyways, this bug is fixed in the latest nightly! Tested with a bunch of dtypes.

**Comment by mobicham** [comment] 2024-05-27 20:43
Thanks! Will give a try!
