### ISSUE TITLE
INTERNAL ASSERT FAILED error

### ISSUE THREAD

**Issue by Eddowesselink** [pytorch/pytorch#75746] opened 2022-04-13 18:05 UTC
### 🐛 Describe the bug

Dear contributor

While training my CNN for muscle segmentation, I'm running into an error message that affects the stability and predictability of CNN learning. 

Description:
While training my CNN for muscle segmentation, after _k_ of iterations (the amount of iterations is variable per case) I will get the following error message:

'out_ptr == out_accessor[thread_count_nonzero[tid + 1]].data()INTERNAL ASSERT FAILED at ..\aten\src\ATen\native\TensorAdvancedIndexing.cpp:1723, please report a bug to PyTorch.'

Could you help me with this issue?

Kind regards,
Eddo Wesselink

### Versions

PyTorch version: 1.10.2+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 Pro
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19041-SP0
Is CUDA available: True
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 3090
Nvidia driver version: 460.89
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin\cudnn64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.2
[pip3] numpydoc==1.2
[pip3] pytorch-ignite==0.4.8
[pip3] torch==1.10.2+cu113
[pip3] torchvision==0.11.3
[conda] mypy_extensions           0.4.3            py38haa95532_1  
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] numpydoc                  1.2                pyhd3eb1b0_0  
[conda] pytorch-ignite            0.4.8                    pypi_0    pypi
[conda] torch                     1.10.2+cu113             pypi_0    pypi
[conda] torchvision               0.11.3                   pypi_0    pypi

**Comment by ngimel** [comment] 2022-04-13 18:27
cc @peterbell10

**Comment by peterbell10** [comment] 2022-04-14 01:08
@Eddowesselink could you run `python -c "import torch; print(torch.__config__.parallel_info())"` and copy the output here?

This exception is coming from inside `torch.nonzero`. It would be really helpful to get a script that you're able to reproduce the error from, or if that's not possible at least a rough idea of the inputs that are triggering the error in `nonzero`.

**Comment by Eddowesselink** [comment] 2022-04-14 18:39
@peterbell10 Thanks for your quick response and your help!

Hereby the output as asked:

ATen/Parallel:
	at::get_num_threads() : 10
	at::get_num_interop_threads() : 10
OpenMP 2019
	omp_get_max_threads() : 10
Intel(R) Math Kernel Library Version 2020.0.2 Product Build 20200624 for Intel(R) 64 architecture applications
	mkl_get_max_threads() : 10
Intel(R) MKL-DNN v2.2.3 (Git Hash 7336ca9f055cf1bfa13efb658fe15dc9b41f0740)
std::thread::hardware_concurrency() : 20
Environment variables:
	OMP_NUM_THREADS : [not set]
	MKL_NUM_THREADS : [not set]
ATen parallel backend: OpenMP

**Comment by peterbell10** [comment] 2022-04-19 14:28
@Eddowesselink any more info on this part:

>This exception is coming from inside `torch.nonzero`. It would be really helpful to get a script that you're able to reproduce the error from, or if that's not possible at least a rough idea of the inputs that are triggering the error in `nonzero`.

**Comment by peterbell10** [comment] 2022-05-13 23:36
Could possibly be related to #54789. I've found that some invalid `bool` values lead to undefined behavior that can trigger this error, so it would help to know if this is related to boolean tensors @Eddowesselink.

**Comment by ngimel** [comment] 2022-10-02 06:12
Closing, `bool` issues have been fixed, please reopen with more info if still an issue.

**Closed by ngimel** 2022-10-02 06:12 UTC
Labels: triaged, module: advanced indexing

**Comment by yongsiang-fb** [comment] 2022-10-24 19:02
We also observe the same error message and even if we are totally sure that the bool tensor is not poisoned, the error still happens. However, we have not been able to test this on a newer version of PyTorch yet due to the environment restrictions.
