### ISSUE TITLE
problem with cuda home

### ISSUE THREAD

**Issue by wqh17101** [pytorch/pytorch#55361] opened 2021-04-06 09:09 UTC
## 🐛 Bug

it is lack of compatibility  of  CUDA_HOME (or other environment variable)

## To Reproduce

https://github.com/pytorch/pytorch/blob/cdf93b03de7ffc33e2762f7fefb8f3c7586fd051/torch/utils/cpp_extension.py#L136

https://github.com/pytorch/pytorch/blob/cdf93b03de7ffc33e2762f7fefb8f3c7586fd051/torch/utils/cpp_extension.py#L27-L54

As you can see , `_find_cuda_home()` get a string from os env. However, it could be more than one path in the variable *CUDA_HOME* which sep by ":" on Linux and ';' on Windows.
So, it is very dangerous to use the env variable directly.
Maybe using system path sep to split the path and then choose one of string which is valid (existence) after splitting is a good idea .

**Comment by peterjc123** [comment] 2021-04-06 11:45
Duplicate of https://github.com/pytorch/pytorch/issues/55363

**Closed by peterjc123** 2021-04-06 11:45 UTC
