### ISSUE TITLE
torch.load issue on different folder

### ISSUE THREAD

**Issue by ZGHAP** [pytorch/pytorch#60068] opened 2021-06-16 03:37 UTC
## 🐛 Bug

I trained 2 set of model and place them on two folder.

One of them can not be loaded when I call them by a program runs on another folder, even though I can detect them all is exist.

but both of them could be loaded when the program runs on their parent folder. Why this happen?

## To Reproduce

def load_product_model(self, product, set_folder = 'Set'):
        actor_net_path = './' + set_folder + '/' + product + '/a_net.pkl'
        if os.path.exists(actor_net_path):
            print('exist')
        self.actor_net = torch.load(actor_net_path)

## Environment
ubuntu20.04 + pytorch1.8.1 + cuda10.2 + py3.8.5

cc @gmagogsfm

**Comment by nikithamalgifb** [comment] 2021-06-16 14:20
Can you try using the absolute path and see if that works?  Also how were these models saved. Using `torch.save` ?

**Comment by ZGHAP** [comment] 2021-06-16 14:38
> 
> 
> Can you try using the absolute path and see if that works? Also how were these models saved. Using `torch.save` ?

I had try absolute path, but still not work.
I use torch.save to save, should I using actor_net.state_dict()?

**Comment by ZGHAP** [comment] 2021-06-16 14:39
saving function:

def save_model(self, product, i = 0):
        a_path =f'./model/Intra_{product}/a_net{str(i)}.pkl'
        torch.save(self.actor_net, a_path)

**Comment by gchanan** [comment] 2021-06-16 14:46
not sure it's a JIT issue, but unlikely we'll be able to help without a reproduction.

**Comment by ZGHAP** [comment] 2021-06-16 15:03
btw , I try using .actor_net.load_state_dict(torch.load(actor_net_path))

python prompt 
1194         # copy state_dict so _load_from_state_dict can modify it
   1195         metadata = getattr(state_dict, '_metadata', None)
-> 1196         state_dict = state_dict.copy()
   1197         if metadata is not None:
   1198             # mypy isn't aware that "_metadata" exists in state_dict

**Comment by nikithamalgifb** [comment] 2021-06-16 16:12
> not sure it's a JIT issue, but unlikely we'll be able to help without a reproduction.
@gchanan , I will remove the JIT triage tag. Please tag the right project

**Comment by H-Huang** [comment] 2021-06-16 21:38
Based on my understanding of your directory structure, I am not able to reproduce any issues that you mentioned. For instance, the below example works fine:

`directory structure`
```
.
├── another_folder
│   └── another_folder.py
├── folder1
│   └── model1.pt
├── folder2
│   └── model2.pt
└── test.py
```

`test.py`
```
import torch
model1 = torch.load("folder1/model1.pt")
model2 = torch.load("folder2/model2.pt")
print(model1)
print(model2)
```

`another_folder.py`
```
import torch
model1 = torch.load("../folder1/model1.pt")
model2 = torch.load("../folder2/model2.pt")
print(model1)
print(model2)
```

This example works, so I am closing the issue. Please feel free to reraise the issue when you have a reproducible script that we can run locally and look into.

**Closed by H-Huang** 2021-06-16 21:38 UTC
