### ISSUE TITLE
The wrong behavior of ```torch.where```

### ISSUE THREAD

**Issue by yuhaoooo** [pytorch/pytorch#64161] opened 2021-08-30 06:59 UTC
## 🐛 The wrong behavior of ```torch.where``` function in PyTorch 1.9.0

When I utilize ```torch.where``` function to clip the tensor, I encounter an error as follows:
``` Python
RuntimeError: expected scalar type double but found float
```

## To Reproduce

The script is as follows:
```Python
import torch
print(torch.__version__)
x = torch.randn(3, 2)
print(x.dtype)
y = torch.where(x < 1e-8, 1e-8, x)  # <-- the error occurs
```

## Environment

PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.5.2 (x86_64)
GCC version: Could not collect
Clang version: 12.0.5 (clang-1205.0.22.11)
CMake version: Could not collect
Libc version: N/A

Python version: 3.6.8 |Anaconda, Inc.| (default, Dec 29 2018, 19:04:46)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] (64-bit runtime)
Python platform: Darwin-20.6.0-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.10.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  h0a44026_0    pytorch
[conda] mkl                       2019.4                      233  
[conda] mkl-service               2.3.0            py36h9ed2024_0  
[conda] mkl_fft                   1.3.0            py36ha059aab_0  
[conda] mkl_random                1.0.4            py36h27c97d8_0  
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpy-base                1.17.0           py36h6575580_0  
[conda] pytorch                   1.9.0                   py3.6_0    pytorch
[conda] torchaudio                0.9.0                      py36    pytorch
[conda] torchvision               0.10.0                 py36_cpu    pytorch

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @nairbv @mruberry

**Comment by mruberry** [comment] 2021-08-30 17:06
cc @kshitij12345 who's fixing this now and @saketh-are who's reviewing

**Comment by yuhaoooo** [comment] 2021-08-31 02:13
OK. Thanks a lot.

**Comment by mruberry** [comment] 2021-08-31 02:59
Let's keep this open until it's actually fixed ;)

**Comment by rgommers** [comment] 2022-01-07 07:54
This is a duplicate of gh-9190, which has much more context.

**Comment by ngimel** [comment] 2022-05-04 17:45
Fixed

**Closed by ngimel** 2022-05-04 17:45 UTC
Labels: high priority, triaged, module: type promotion, has workaround
