### ISSUE TITLE
amd windows

### ISSUE THREAD

**Issue by vincyxiroff** [pytorch/pytorch#89699] opened 2022-11-25 22:31 UTC
### 🚀 The feature, motivation and pitch

add it for amd windows too

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport

**Comment by malfet** [comment] 2023-11-15 00:05
Closing as duplicate of https://github.com/pytorch/pytorch/issues/109204

(Although this one was added before the other issue has much more details)

**Closed by malfet** 2023-11-15 00:05 UTC
Labels: module: windows, module: rocm, triaged
