### ISSUE TITLE
Confusing behavior with *= operator with torch.expand

### ISSUE THREAD

**Issue by maxjiang93** [pytorch/pytorch#17185] opened 2019-02-16 00:34 UTC
## 🐛 Bug

I am observing confusing (and probably errornous behavior) when using *= tensor operator with expand function. I don't think this should be an expected behavior, but if it is, there should at least be a user warning. Below is a minimally reproducible example:

## To Reproduce
code input:
```python
import torch
a = torch.tensor([1,2,3]).view(1,3)
b = torch.tensor([4,5]).view(2,1)
print(a)
print(b)
print(a*b) # directly multiplying will trigger the correct broadcast
```
output:
```bash
tensor([[1, 2, 3]])
tensor([[4],
        [5]])
tensor([[ 4,  8, 12],
        [ 5, 10, 15]])
```
code input:
```python
print(a.expand(2,3)*b.expand(2,3)) # explicitly using expand to broadcast followed by * is also fine
```
output:
```bash
tensor([[ 4,  8, 12],
        [ 5, 10, 15]])
```
code input:
```python
a *= b # trying to broadcast with *= doesn't work
```
output:
```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: output with shape [1, 3] doesn't match the broadcast shape [2, 3]
```
code input:
```python
a = a.expand(2,3) # explicitly broadcasting with expand
b = b.expand(2,3) # explicitly broadcasting with expand
a *= b # this produces weird values that I don't understand
print(a)
```
output:
```bash
tensor([[20, 40, 60],
        [20, 40, 60]])
```

## Environment
```bash
Collecting environment information...
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: version 3.10.1

Python version: 3.5
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.11.3
[pip3] torch==0.4.0
[pip3] torchvision==0.2.1
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.0                      118
[conda] mkl-service               1.1.2                    py35_3
[conda] mkl_fft                   1.0.6            py35hb8a8100_0
[conda] mkl_random                1.0.1            py35h5d10147_1
[conda] pytorch                   1.0.0                   py3.5_1    pytorch
[conda] torchvision               0.2.1                      py_2    pytorch
```

**Comment by fmassa** [comment] 2019-02-19 13:27
This is a duplicate of https://github.com/pytorch/pytorch/issues/957

I agree this is confusing and has bitten a lot of users in the past, we should discuss about how to circumvent this (maybe by adding a `WRITABLE = False` flag to expanded tensors?)

**Comment by maxjiang93** [comment] 2019-02-19 18:55
Apologies for missing the duplicate entry. Correct me if I'm wrong, my understanding of the issue is that since expand is not actually duplicating entries in the source tensor, during in-place ops, it's repeatedly multiplying the same source entry, which then gets expanded back into the full tensor?

I guess the issue reminds me of numpy's default behavior of passing references when doing `a = b` which bites a lot of new users. Adding a `writable=False` flag might help. Or perhaps just adding a warning to `torch.expand` documentation would be helpful.

I'm also a bit confused about broadcasting semantics. Why is this broadcast illegal?
```python
a = torch.rand(1,3)
b = torch.rand(2,1)
a *= b
```

**Comment by zou3519** [comment] 2019-02-20 18:33
The fastest workaround we can do to fix this is disallow in-place operations on tensors if the tensor being acted on has 0 strides. This should cover a lot of the error cases

**Comment by maxjiang93** [comment] 2019-02-20 19:49
Yeah I think that would be a great idea, a quick fix as well.

**Comment by zou3519** [comment] 2019-03-12 19:33
I'm closing this because it is a duplicate. I'll track my progress in #17935, which more clearly explains the plan of action.

**Closed by zou3519** 2019-03-12 19:33 UTC
Labels: duplicate, needs discussion
