### ISSUE TITLE
Broken loading of weights for jitted RNN

### ISSUE THREAD

**Issue by Chetter2** [pytorch/pytorch#18617] opened 2019-03-29 11:04 UTC
## 🐛 Bug

Incorrect loading of weights for jitted RNN modules when using CUDA. Weights seem randomly changing from time to time. Model is broken and outputs garbage. Loading model with `map_location='cpu'` fix the problem.

## To Reproduce
```python
import torch
from torch import nn

device = torch.device('cuda')

rnn = nn.GRU(input_size=256,
    hidden_size=128,
    num_layers=2,
    batch_first=False,
    dropout=0.1,
    bidirectional=True)

rnn.eval()
rnn = rnn.to(device)

with torch.no_grad():
    traced_rnn = torch.jit.trace(rnn, torch.rand((50, 10, 256), dtype=torch.float32).to(device))

params = {}

for k, v in traced_rnn.named_parameters():
    params[k] = v
    
torch.jit.save(traced_rnn, 'traced.pt')
traced_rnn = torch.jit.load('traced.pt')

for k, v in traced_rnn.named_parameters():
    diff = torch.max(torch.abs(params[k] - v)).item()
    
    if diff > 0:
        print(k, diff)
```
out
```
weight_hh_l0 0.17591434717178345
bias_ih_l0 0.17516206204891205
bias_hh_l0 0.16948461532592773
weight_ih_l0_reverse 1.2479848861694336
weight_hh_l0_reverse 1.129560947418213
bias_ih_l0_reverse 0.164781391620636
bias_hh_l0_reverse 0.1713828146457672
weight_ih_l1 0.8811493515968323
weight_hh_l1 0.17583367228507996
bias_ih_l1 0.16150619089603424
bias_hh_l1 0.17185932397842407
weight_ih_l1_reverse 0.17613038420677185
weight_hh_l1_reverse 0.1766989678144455
bias_ih_l1_reverse 0.17309224605560303
bias_hh_l1_reverse 0.17430740594863892
```
## Expected behavior

Weights correctly loading and model works

## Environment

PyTorch version: 1.0.1.post2
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 396.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.15.4
[pip] numpydoc==0.8.0
[pip] torch==1.0.1.post2
[pip] torchfile==0.1.0
[pip] torchnet==0.0.4
[pip] torchvision==0.2.2
[pip] warpctc-pytorch==0.1
[conda] blas                      1.0                         mkl
[conda] cuda92                    1.0                           0    pytorch
[conda] faiss-cpu                 1.4.0            py36_cuda0.0_1    pytorch
[conda] mkl                       2018.0.3                      1
[conda] mkl-service               1.1.2            py36h90e4bf4_5
[conda] mkl_fft                   1.0.6            py36h7dd41cf_0
[conda] mkl_random                1.0.1            py36h4414c95_1
[conda] pytorch                   1.0.1           py3.6_cuda9.0.176_cudnn7.4.2_2    pytorch
[conda] pytorch-nightly           1.0.0.dev20181206 py3.6_cuda9.2.148_cudnn7.4.1_0  [cuda92]  pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.2.2                      py_3    pytorch
[conda] warpctc-pytorch           0.1                      pypi_0    pypi

**Comment by driazati** [comment] 2019-04-15 18:38
Can you check and see if this still reproduces on master/nightly? I tried your code and didn't see any diffs in the weights.

**Comment by driazati** [comment] 2019-09-11 23:41
Closing since we couldn't get a repro working, if this is still an issue on master/nightly feel free to re-open

**Closed by driazati** 2019-09-11 23:41 UTC
Labels: jit, needs reproduction
