### ISSUE TITLE
some error with pth export onnx

### ISSUE THREAD

**Issue by tongchangD** [pytorch/pytorch#78233] opened 2022-05-25 02:29 UTC
### 🐛 Describe the bug

I was building this and encountered the following problem when PTH was transferred to ONNX.
```python
RuntimeError: Unsupported: ONNX export of batch_norm for unknown channel size.
```
### Further information
in [Face_Enhancement](https://github.com/microsoft/Bringing-Old-Photos-Back-to-Life/tree/master/Face_Enhancement).

### Versions

my export code
```python
input_semantics = torch.randn(1,18,256,256)
degraded_image = torch.randn(1,3,256,256)
if len(self.opt.gpu_ids) > 0:
    input_semantics = input_semantics.cuda(self.opt.gpu_ids[0])
    degraded_image = degraded_image.cuda(self.opt.gpu_ids[0])
with torch.no_grad():
    fake_image = self.netG(input_semantics, degraded_image, z=None)
    torch.onnx.export(self.netG,(input_semantics, degraded_image), 
                  "./Face_Enhancement_Setting_9_epoch_100_latest_net_G_model.onnx",
                  verbose=False,
                  opset_version=13,
                  export_params=True, do_constant_folding=True,
                  input_names=["image"],
                  output_names=["output"]
                  )
```

**Comment by justinchuby** [comment] 2022-05-26 17:26
Thanks for reporting the issue. Could you share steps on how you prepared the model to help us reproduce the error?

**Comment by tongchangD** [comment] 2022-05-30 02:36
here
[link](https://pan.baidu.com/s/1nFtfodKFffzdFCNdCUy1xQ) 
Extract the code is **puzp**

**Comment by tongchangD** [comment] 2022-05-30 03:10
I changed the model and the code [address](I changed the model and the code address)

**Comment by tongchangD** [comment] 2022-05-30 03:11
> here [link](https://pan.baidu.com/s/1nFtfodKFffzdFCNdCUy1xQ) Extract the code is **puzp**

I changed the model and the code [address](https://drive.google.com/file/d/1xhnd4QKKc5oDujyxxGOPXaDyQiMy9hc_/view?usp=sharing)

**Comment by tongchangD** [comment] 2022-05-30 03:11
> Thanks for reporting the issue. Could you share steps on how you prepared the model to help us reproduce the error?

I changed the model and the code [address](https://drive.google.com/file/d/1xhnd4QKKc5oDujyxxGOPXaDyQiMy9hc_/view?usp=sharing)

**Comment by tongchangD** [comment] 2022-06-07 01:14
Cut the network or rebuild and training the model

**Comment by tongchangD** [comment] 2022-06-30 02:58
how to solve it

**Comment by tongchangD** [comment] 2022-06-30 03:04
Have you solved the problem yet?
I think the first solution is to replace upsampling with deconvolution.
I think the second solution is to break up the trained network structure into a single output.
Is there any other suitable solution?

**Comment by adiojha629** [comment] 2022-08-30 00:28
@tongchangD What do you mean by "break up the trained network structure into a single output."
I'm currently having this [issue](https://github.com/pytorch/pytorch/issues/69346), and saw your link to this issue page.
Thanks for you help in advance!

**Comment by justinchuby** [comment] 2022-10-01 23:21
Circling back to this issue - thanks for sharing the model - would it be possible for you to create a minimal reproduction to help us debug? Debugging the whole model can be hard. I would also suggest trying the latest nightly build and confirm that the issue still exist.

**Comment by justinchuby** [comment] 2022-10-21 18:37
Closing since there is no movement. Please feel free to open a new issue if you still see the problem!

**Closed by justinchuby** 2022-10-21 18:37 UTC
Labels: needs reproduction, module: onnx, triaged, onnx-needs-info

**Comment by tongchangD** [comment] 2022-10-24 03:41
> Closing since there is no movement. Please feel free to open a new issue if you still see the problem!

thanks
