### ISSUE TITLE
`torch.cholesky_solve` free(): invalid pointer, Aborted (core dumped)

### ISSUE THREAD

**Issue by DNXie** [pytorch/pytorch#42648] opened 2020-08-06 00:59 UTC
## To Reproduce

~~~python
import torch
input = torch.zeros ([1,1,1])
input2 = torch.zeros ([1,4,1,1])
out= torch.zeros([1])
torch.cholesky_solve(input=input, input2=input2, out=out)
~~~

Output:
~~~python
free(): invalid pointer
Aborted (core dumped)
~~~

## Expected behavior
Expect no aborts

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.1.243 h6bb024c_0
[conda] mkl 2020.1 217
[conda] mkl-include 2020.1 217
[conda] mkl-service 2.3.0 py37he904b0f_0
[conda] mkl_fft 1.0.15 py37ha843d7b_0
[conda] mkl_random 1.1.0 py37hd6b4f25_0
[conda] numpy 1.18.1 py37h4f9e942_0
[conda] numpy-base 1.18.1 py37hde5b4d6_1
[conda] pytorch 1.5.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
[conda] torchvision 0.6.0 py37_cu101 pytorch

## Additional context

cc @ezyang @gchanan @zou3519

**Comment by malfet** [comment] 2020-08-06 15:01
Can reproduce with the latest build.

**Comment by DNXie** [comment] 2020-08-06 19:32
@malfet I just reported another issue with this API in #42695, please take a look. Apparently, it produces so many kinds of error message with abort, and even segfault. Thank you!

**Comment by malfet** [comment] 2020-08-07 16:46
Looks like this one is just a one corner case of  #42695 , so let's close this one as a duplicate and focus the investigation there

**Closed by malfet** 2020-08-07 16:46 UTC
Labels: high priority, topic: crash, triage review, triaged
