### ISSUE TITLE
torch.zeros for sparse matrices

### ISSUE THREAD

**Issue by mmoghimi** [pytorch/pytorch#4204] opened 2017-12-15 22:57 UTC
I’m trying to use a sparse matrix in my model. The sparse matrix is fixed and not being updated. I’m using a custom function for this. However, I’m getting the following error when I use DataParallel. Any ideas how to solve this?

`RuntimeError: zeros is not implemented for type torch.cuda.sparse.`

And here is the code. It works if you comment out the DataParallel line.

```
import torch

class MyFunction(torch.autograd.Function):
  def forward(self, tensor, sparse_tensor):
    self.save_for_backward(sparse_tensor)
    print sparse_tensor.size(), tensor.size()
    return torch.matmul(sparse_tensor, tensor.t()).t()

  def backward(self, grad_output):
    sparse_tensor, = self.saved_tensors
    print sparse_tensor.size(), grad_output.size()
    return torch.matmul(sparse_tensor.t(), grad_output.t()), None


class MyCustomNet(torch.nn.Module):
  def __init__(self):
    super(MyCustomNet, self).__init__()
    i = torch.LongTensor([[0, 1, 1],
                          [2, 0, 2]])
    v = torch.FloatTensor([3, 4, 5])
    self.sparse_map = torch.nn.Parameter(torch.sparse.FloatTensor(i, v, torch.Size([2,3])))
    print torch.sparse.FloatTensor(i, v, torch.Size([2,3])).to_dense()
  def forward(self, x):
    self.func = MyFunction()
    return self.func(x, self.sparse_map)

net = MyCustomNet()
net.eval()
net.cuda()
net = torch.nn.DataParallel(net)
data = torch.autograd.Variable(torch.zeros((10, 3))).cuda()
target = torch.autograd.Variable(torch.zeros((10, 2))).cuda()


out = net(data)
loss_fn = torch.nn.L1Loss()
loss = loss_fn(out, target)
loss.backward()

```

**Comment by zou3519** [comment] 2017-12-18 17:58
Implementing `torch.zeros` for sparse matrices isn't very difficult, but we'll probably have to implement a few other functions (like `narrow`, I think) for DataParallel to support sparse matrices.

**Comment by SsnL** [comment] 2017-12-18 18:11
Hmm I thought zeros already exists from https://github.com/pytorch/pytorch/pull/3271/files. Maybe not on Variables yet?

**Comment by zou3519** [comment] 2017-12-18 18:22
Oh good point @SsnL. Yeah, it looks like it's not on Variable.

**Comment by zou3519** [comment] 2018-01-26 16:49
@mmoghimi #4236 should fix the issue of not having `zeros` for sparse variables.

**Comment by weiyangfb** [comment] 2018-06-26 19:21
Should we close this since there is already torch.zeros() for sparse tensor? @zou3519 @SsnL 

```
a = torch.zeros((3, 3), layout=torch.sparse_coo, requires_grad=True)
a
```
torch.sparse.FloatTensor of size (3,3) with indices:
tensor([], dtype=torch.int64, grad_fn=<Error>)
and values:
tensor([], grad_fn=<Error>)

**Comment by SsnL** [comment] 2018-06-26 20:04
grad_fn looks wrong.

**Comment by weiyangfb** [comment] 2018-07-18 19:24
`grad_fn=<Error>` is caused by #9412

**Comment by weiyangfb** [comment] 2018-09-05 19:00
the printing issue will be fixed by: https://github.com/pytorch/pytorch/pull/10181

**Closed** 2018-09-06 02:46 UTC
Labels: todo
