### ISSUE TITLE
Export to Onnx error: "_thnn_fused_lstm_cell"

### ISSUE THREAD

**Issue by lk1983823** [pytorch/pytorch#25533] opened 2019-09-01 03:15 UTC
Hi guys:
I have build a seq2seq model using nn.LSTMCELL in it. And I want to export a trained one to onnx form. However, when I do this, I have an error says:

```
UserWarning: ONNX export failed on ATen operator _thnn_fused_lstm_cell because torch.onnx.symbolic_opset9._thnn_fused_lstm_cell does not exist
  .format(op_name, opset_version, op_name))
```
I think this maybe due to the opset nort supporting nn.LSTMCELL.
Any one could help and share some advice?
Thank you！

cc @albanD @mruberry @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @zou3519

**Comment by pbelevich** [comment] 2019-09-03 15:33
@lk1983823 please provide steps to reproduce

**Comment by daisuke834** [comment] 2019-10-05 15:15
@lk1983823 @pbelevich 
I am encountering the same problem. Here is my simple codes to replicate the it.
```
import torch
import torch.nn as nn
import torch.onnx

if __name__ == "__main__":
    device = 'cuda' if torch.cuda.is_available() else 'cpu'
    print('using ' + device)

    input_dim = 2
    hidden_dim = 4
    batch_size = 8
    x = torch.randn((batch_size, input_dim), device=device)
    h0 = torch.randn((batch_size, hidden_dim), device=device)
    c0 = torch.randn((batch_size, hidden_dim), device=device)
    print("******input*******")
    print("x, h0, c0", x.size(), h0.size(), c0.size())
    print("")

    print("******net*******")
    net = nn.LSTMCell(input_size=input_dim, hidden_size=hidden_dim).to(device)
    print(net)
    print("")

    print("******output*******")
    h1, c1 = net(x, (h0, c0))
    print("h1, c1", h1.size(), c1.size())
    print("")

    print("******onnx.export*******")
    torch.onnx.export(net, (x, (h0, c0)), "test.onnx", verbose=True,
                      input_names=['x', 'h0', 'c0'], output_names=['h1', 'c1'])
    print("")
```

Then, I got the following error messages.
```
$ python3 ./my_lstm.py 
using cuda
******input*******
x, h0, c0 torch.Size([8, 2]) torch.Size([8, 4]) torch.Size([8, 4])

******net*******
LSTMCell(2, 4)

******output*******
h1, c1 torch.Size([8, 4]) torch.Size([8, 4])

******onnx.export*******
/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py:562: UserWarning: ONNX export failed on ATen operator _thnn_fused_lstm_cell because torch.onnx.symbolic_opset9._thnn_fused_lstm_cell does not exist
  .format(op_name, opset_version, op_name))
Traceback (most recent call last):
  File "./my_lstm.py", line 31, in <module>
    input_names=['x', 'h0', 'c0'], output_names=['h1', 'c1'])
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 132, in export
    strip_doc_string, dynamic_axes)
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 64, in export
    example_outputs=example_outputs, strip_doc_string=strip_doc_string, dynamic_axes=dynamic_axes)
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 329, in _export
    _retain_param_name, do_constant_folding)
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 225, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 127, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/__init__.py", line 163, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/utils.py", line 563, in _run_symbolic_function
    op_fn = sym_registry.get_registered_op(op_name, '', opset_version)
  File "/miniconda3/lib/python3.6/site-packages/torch/onnx/symbolic_registry.py", line 91, in get_registered_op
    return _registry[(domain, version)][opname]
KeyError: '_thnn_fused_lstm_cell'
```

**Comment by tdas714** [comment] 2019-11-23 08:28
I'm having the same problem, when trying to export to onnx.

**Comment by chochobo** [comment] 2019-12-18 01:27
I'm having the same problem.

**Comment by MarkZXZX** [comment] 2020-03-26 13:37
I have the same problem, and I think this problem is maybe from CUDA. if I set device=CPU, it's fine.

**Comment by tdas714** [comment] 2020-04-04 06:20
Yeah, I've noticed that It's from CUDA. The latest PyTorch does not support old GPU.

**Comment by ArtificialCleverness** [comment] 2021-01-05 08:12
Any update on this?

**Comment by SunAnLan** [comment] 2021-04-01 03:17
Any update please?

**Comment by serg06** [comment] 2021-06-08 23:59
> Yeah, I've noticed that It's from CUDA. The latest PyTorch does not support old GPU.

I tried this on a 3090, no luck.

> I have the same problem, and I think this problem is maybe from CUDA. if I set device=CPU, it's fine.

I tried this but it seems to freeze somewhere. It never finishes.

**Comment by BowenBao** [comment] 2021-06-09 22:15
Will take a look on the GPU export side.

For CPU export, i tried above repro and can complete successfully. @serg06 could you provide more context how CPU export freezes?

**Comment by serg06** [comment] 2021-06-09 23:31
@BowenBao I'll try my best, I'm not very proficient with PyTorch though.

I'm working with [this Tacotron2 repo](https://github.com/NVIDIA/DeepLearningExamples/tree/master/PyTorch/SpeechSynthesis/Tacotron2) and trying to export their [model](https://github.com/NVIDIA/DeepLearningExamples/blob/778583481bb2e83c0ef4699c1fdfc6347da3c6a3/PyTorch/SpeechSynthesis/Tacotron2/tacotron2/model.py#L598).

When I try to export the model, it outputs a few warnings, then just never finishes running. (I tried waiting 15+ minutes and nothing happens, unlike with the GPU which errors out in <1 minute.)

Here's what my code looks like:
```
# Config
USE_CPU = True
OPSET_VERSION = 11

# Load model
tacotron2 = load_taco2(args.tacotron2)
tacotron2.eval()

# Generate dummy data
sequences = torch.randint(low=0, high=148, size=(1, 50), dtype=torch.long)
sequence_lengths = torch.IntTensor([sequences.size(1)]).long()
dummy_input = (sequences, sequence_lengths)
if not USE_CPU:
    dummy_input = tuple(t.cuda() for t in dummy_input)

# Run it through
with torch.no_grad():
    tacotron2(*dummy_input)

# Export model
print('exporting...')
torch.onnx.export(tacotron2, dummy_input, args.output + "/" + "taco2.onnx",
                  opset_version=OPSET_VERSION,
                  do_constant_folding=True,
                  input_names=["sequences", "sequence_lengths"],
                  output_names=["mel_outputs_postnet", "mel_lengths", "alignments"],
                  dynamic_axes={"sequences": {1: "text_seq"}})
print('done!')
```

And here's the output I get:
```
exporting...
./common/utils.py:51: TracerWarning: Converting a tensor to a Python number might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  max_len = torch.max(lengths).item()
./tacotron2/model.py:584: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if self.early_stopping and torch.sum(not_finished) == 0:
./tacotron2/model.py:586: TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  if len(mel_outputs) == self.max_decoder_steps:
./tacotron2/model.py:689: TracerWarning: Converting a tensor to a Python integer might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  alignments = alignments.unfold(1, BS, BS).transpose(0,2)
~/.local/lib/python3.7/site-packages/torch/onnx/symbolic_opset9.py:1805: UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with LSTM can cause an error when running the ONNX model with a different batch size. Make sure to save the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.
  "or define the initial states (h0/c0) as inputs of the model. ")
~/.local/lib/python3.7/site-packages/torch/onnx/symbolic_helper.py:446: UserWarning: ONNX export mode is set to inference mode, but operator dropout is set to training  mode. The model will be exported in inference, as specified by the export mode.
  training_mode + ", as specified by the export mode.")
```

As you can see, it prints out `exporting...` but not `done!`

**Comment by BowenBao** [comment] 2021-06-18 00:58
@serg06 Thanks, I think for the long export time it should be due to a separate issue, which is likely the export is unrolling large loops. You will need to try script the model first, before exporting, to preserve the dynamic control flow.

**Comment by serg06** [comment] 2021-06-18 17:28
@BowenBao What does it mean to "Script the model"?

**Comment by luvwinnie** [comment] 2021-07-20 08:48
Any alternative way to this error?I'm using LSTMCell throwing the same error.

**Comment by serg06** [comment] 2021-07-20 17:28
@luvwinnie I think Nvidia solved that issue here by replacing LSTMCell with LSTM when exporting: https://github.com/NVIDIA/DeepLearningExamples/blob/master/PyTorch/SpeechSynthesis/Tacotron2/tensorrt/convert_tacotron22onnx.py

In my testing, I couldn't find any noticeable difference in quality.

**Comment by luvwinnie** [comment] 2021-07-21 01:55
@serg06 I have try with my implementation that use for large OCR application with LSTM implementation, however it seems like I can't export the model.

**Comment by luvwinnie** [comment] 2021-07-21 02:26
```
Hi @luvwinnie,
Two issues here:

The converter (torch.onnx.export) does not support LSTMCell conversion.
To work around 1), using LSTM instead of LSTMCell for conversion. However, it seems that the converter failed due to the protobuf limitation. Please note that a protobuf python object cannot be larger than 2GB and it's a protobuf limitation. So the solution is just what you did: use_external_data_format=True. Then there will be separated files instead of one single model file. It's expected.
I would suggest you raise a question under PyTorch repo to ask how to convert models with LSTMCell to ONNX properly, or request this op support. Close now since it should not be an ONNX issue. Thanks.
```

It seems like this is an issue pytorch instead of ONNX repository. Does any plan that pytorch to support LSTMCell ops for exporting to ONNX?

**Comment by garymm** [comment] 2021-09-28 22:53
This is tracked internally at Microsoft by https://msdata.visualstudio.com/Vienna/_workitems/edit/1217280

**Comment by garymm** [comment] 2021-12-02 23:23
Duplicate of #21909

**Closed by garymm** 2021-12-02 23:23 UTC
Labels: module: onnx, module: nn, module: rnn, triaged, enhancement

**Comment by evo11x** [comment] 2021-12-06 19:57
I get this warning with GRU layers trained on cuda with rtx 3060, but the model gets saved, I don't know yet if the exported model work correctly.

UserWarning: Exporting a model to ONNX with a batch_size other than 1, with a variable length with GRU can cause an error when running the ONNX model with a different batch size. Make sure to save 
the model with a batch size of 1, or define the initial states (h0/c0) as inputs of the model.

**Comment by Charlyo** [comment] 2023-04-20 08:40
Still happening for latest torch dev veriosn 2.1.0.dev20230418+cu117

torch.onnx.errors.UnsupportedOperatorError: Exporting the operator 'aten::_thnn_fused_lstm_cell' to ONNX opset version 16 is not supported.

@garymm could you please reopen the issue?
