### ISSUE TITLE
MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 20480 bytes '

### ISSUE THREAD

**Issue by dbl001** [pytorch/pytorch#78492] opened 2022-05-30 15:46 UTC
### 🐛 Describe the bug

I modified the Winogrande project to utilize the 'mps' backend.

https://github.com/allenai/winogrande

I edited the file ./scripts/run_experiment on line(s) 490:
E.g.
```
    if args.local_rank == -1 or args.no_cuda:
        #device = torch.device("cuda" if torch.cuda.is_available() and not args.no_cuda else "cpu")
        #args.n_gpu = torch.cuda.device_count()
        device = torch.device("mps")
        args.n_gpu = 1
        print(device)
```
Ran the training script:
```
%  export PYTHONPATH=$PYTHONPATH:$(pwd)
(base) davidlaxer@x86_64-apple-darwin13 winogrande % python ./scripts/run_experiment.py \
--model_type roberta_mc \
--model_name_or_path roberta-large \
--task_name winogrande \
--do_eval \
--do_lower_case \
--data_dir ./data \
--max_seq_length 80 \
--per_gpu_eval_batch_size 4 \
--per_gpu_train_batch_size 16 \
--learning_rate 1e-5 \
--num_train_epochs 3 \
--output_dir ./output/models/ \
--do_train \
--logging_steps 4752 \
--save_steps 4750 \
--seed 42 \
--data_cache_dir ./output/cache/ \
--warmup_pct 0.1 \
--evaluate_during_training

mps
05/30/2022 08:36:06 - WARNING - __main__ -   Process rank: -1, device: mps, n_gpu: 1, distributed training: False, 16-bits training: False
05/30/2022 08:36:07 - INFO - pytorch_transformers.modeling_utils -   loading configuration file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-config.json from cache at /Users/davidlaxer/.cache/torch/pytorch_transformers/c22e0b5bbb7c0cb93a87a2ae01263ae715b4c18d692b1740ce72cacaa99ad184.2d28da311092e99a05f9ee17520204614d60b0bfdb32f8a75644df7737b6a748
05/30/2022 08:36:07 - INFO - pytorch_transformers.modeling_utils -   Model config {
  "architectures": [
    "RobertaForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "bos_token_id": 0,
  "eos_token_id": 2,
  "finetuning_task": "winogrande",
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 1024,
  "initializer_range": 0.02,
  "intermediate_size": 4096,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 514,
  "model_type": "roberta",
  "num_attention_heads": 16,
  "num_hidden_layers": 24,
  "num_labels": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "pad_token_id": 1,
  "torchscript": false,
  "type_vocab_size": 1,
  "vocab_size": 50265
}

05/30/2022 08:36:07 - INFO - pytorch_transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-vocab.json from cache at /Users/davidlaxer/.cache/torch/pytorch_transformers/1ae1f5b6e2b22b25ccc04c000bb79ca847aa226d0761536b011cf7e5868f0655.ef00af9e673c7160b4d41cfda1f48c5f4cba57d5142754525572a846a1ab1b9b
05/30/2022 08:36:07 - INFO - pytorch_transformers.tokenization_utils -   loading file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-merges.txt from cache at /Users/davidlaxer/.cache/torch/pytorch_transformers/f8f83199a6270d582d6245dc100e99c4155de81c9745c6248077018fe01abcfb.70bec105b4158ed9a1747fea67a43f5dee97855c64d62b6ec3742f4cfdb5feda
05/30/2022 08:36:08 - INFO - pytorch_transformers.modeling_utils -   loading weights file https://s3.amazonaws.com/models.huggingface.co/bert/roberta-large-pytorch_model.bin from cache at /Users/davidlaxer/.cache/torch/pytorch_transformers/195c00f28dc68ef13a307c6db84d566f801f03b2b6bcf8b29524f10f767fac2a.fc7abf72755ecc4a75d0d336a93c1c63358d2334f5998ed326f3b0da380bf536
05/30/2022 08:36:15 - INFO - pytorch_transformers.modeling_utils -   Weights of RobertaForMultipleChoice not initialized from pretrained model: ['classifier.dense.weight', 'classifier.dense.bias', 'classifier.out_proj.weight', 'classifier.out_proj.bias']
05/30/2022 08:36:15 - INFO - pytorch_transformers.modeling_utils -   Weights from pretrained model not used in RobertaForMultipleChoice: ['lm_head.bias', 'lm_head.dense.weight', 'lm_head.dense.bias', 'lm_head.layer_norm.weight', 'lm_head.layer_norm.bias', 'lm_head.decoder.weight']
05/30/2022 08:36:16 - INFO - __main__ -   Training/evaluation parameters Namespace(adam_epsilon=1e-08, cache_dir='', config_name='', data_cache_dir='./output/cache/', data_dir='./data', device=device(type='mps'), do_eval=True, do_lower_case=True, do_prediction=False, do_train=True, eval_all_checkpoints=False, evaluate_during_training=True, fp16=False, fp16_opt_level='O1', gradient_accumulation_steps=1, learning_rate=1e-05, local_rank=-1, logging_steps=4752, max_grad_norm=1.0, max_seq_length=80, max_steps=-1, model_name_or_path='roberta-large', model_type='roberta_mc', n_gpu=1, no_cuda=False, num_train_epochs=3.0, output_dir='./output/models/', output_mode='multiple_choice', overwrite_cache=False, overwrite_output_dir=False, per_gpu_eval_batch_size=4, per_gpu_train_batch_size=16, run_on_test=False, save_steps=4750, seed=42, server_ip='', server_port='', task_name='winogrande', tokenizer_name='', warmup_pct=0.1, warmup_steps=0, weight_decay=0.0)
05/30/2022 08:36:16 - INFO - __main__ -   Creating features from dataset file at ./data
05/30/2022 08:36:16 - INFO - scripts.utils -   Writing example 0 of 10234
05/30/2022 08:36:16 - INFO - scripts.utils -   *** Example ***
05/30/2022 08:36:16 - INFO - scripts.utils -   example_id: 3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-2
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 0
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> Ian Ġvolunteered Ġto Ġeat ĠDennis 's Ġmen udo Ġafter Ġalready Ġhaving Ġa Ġbowl Ġbecause </s> </s> Ian Ġdespised Ġeating Ġintestine . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 37733 20792 7 3529 8093 18 604 23259 71 416 519 10 5749 142 2 2 37733 43396 4441 41727 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 1
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> Ian Ġvolunteered Ġto Ġeat ĠDennis 's Ġmen udo Ġafter Ġalready Ġhaving Ġa Ġbowl Ġbecause </s> </s> D ennis Ġdespised Ġeating Ġintestine . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 37733 20792 7 3529 8093 18 604 23259 71 416 519 10 5749 142 2 2 495 28828 43396 4441 41727 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   label: 1
05/30/2022 08:36:16 - INFO - scripts.utils -   *** Example ***
05/30/2022 08:36:16 - INFO - scripts.utils -   example_id: 3QHITW7OYO7Q6B6ISU2UMJB84ZLAQE-1
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 0
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> Ian Ġvolunteered Ġto Ġeat ĠDennis 's Ġmen udo Ġafter Ġalready Ġhaving Ġa Ġbowl Ġbecause </s> </s> Ian Ġenjoyed Ġeating Ġintestine . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 37733 20792 7 3529 8093 18 604 23259 71 416 519 10 5749 142 2 2 37733 3776 4441 41727 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 1
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> Ian Ġvolunteered Ġto Ġeat ĠDennis 's Ġmen udo Ġafter Ġalready Ġhaving Ġa Ġbowl Ġbecause </s> </s> D ennis Ġenjoyed Ġeating Ġintestine . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 37733 20792 7 3529 8093 18 604 23259 71 416 519 10 5749 142 2 2 495 28828 3776 4441 41727 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   label: 0
05/30/2022 08:36:16 - INFO - scripts.utils -   *** Example ***
05/30/2022 08:36:16 - INFO - scripts.utils -   example_id: 3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-1
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 0
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> He Ġnever Ġcomes Ġto Ġmy Ġhome , Ġbut ĠI Ġalways Ġgo Ġto Ġhis Ġhouse Ġbecause Ġthe </s> </s> home Ġis Ġsmaller . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 894 393 606 7 127 184 6 53 38 460 213 7 39 790 142 5 2 2 8361 16 2735 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 1
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> He Ġnever Ġcomes Ġto Ġmy Ġhome , Ġbut ĠI Ġalways Ġgo Ġto Ġhis Ġhouse Ġbecause Ġthe </s> </s> house Ġis Ġsmaller . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 894 393 606 7 127 184 6 53 38 460 213 7 39 790 142 5 2 2 3138 16 2735 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   label: 0
05/30/2022 08:36:16 - INFO - scripts.utils -   *** Example ***
05/30/2022 08:36:16 - INFO - scripts.utils -   example_id: 3XWUWJ18TLO2DDRXF83QWLKRJ29UU4-2
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 0
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> He Ġnever Ġcomes Ġto Ġmy Ġhome , Ġbut ĠI Ġalways Ġgo Ġto Ġhis Ġhouse Ġbecause Ġthe </s> </s> home Ġis Ġbigger . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 894 393 606 7 127 184 6 53 38 460 213 7 39 790 142 5 2 2 8361 16 2671 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 1
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> He Ġnever Ġcomes Ġto Ġmy Ġhome , Ġbut ĠI Ġalways Ġgo Ġto Ġhis Ġhouse Ġbecause Ġthe </s> </s> house Ġis Ġbigger . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 894 393 606 7 127 184 6 53 38 460 213 7 39 790 142 5 2 2 3138 16 2671 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   label: 1
05/30/2022 08:36:16 - INFO - scripts.utils -   *** Example ***
05/30/2022 08:36:16 - INFO - scripts.utils -   example_id: 3D5G8J4N5CI2K40F4RZLF9OG2CKVTH-2
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 0
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> Kyle Ġdoesn 't Ġwear Ġleg Ġwarm ers Ġto Ġbed , Ġwhile ĠLogan Ġalmost Ġalways Ġdoes . </s> </s> Kyle Ġis Ġmore Ġlikely Ġto Ġlive Ġin Ġa Ġcolder Ġclimate . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 37468 630 75 3568 2985 3279 268 7 3267 6 150 9220 818 460 473 4 2 2 37468 16 55 533 7 697 11 10 19727 2147 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   choice: 1
05/30/2022 08:36:16 - INFO - scripts.utils -   tokens: <s> Kyle Ġdoesn 't Ġwear Ġleg Ġwarm ers Ġto Ġbed , Ġwhile ĠLogan Ġalmost Ġalways Ġdoes . </s> </s> L ogan Ġis Ġmore Ġlikely Ġto Ġlive Ġin Ġa Ġcolder Ġclimate . </s>
05/30/2022 08:36:16 - INFO - scripts.utils -   input_ids: 0 37468 630 75 3568 2985 3279 268 7 3267 6 150 9220 818 460 473 4 2 2 574 17302 16 55 533 7 697 11 10 19727 2147 4 2 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
05/30/2022 08:36:16 - INFO - scripts.utils -   input_mask: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   segment_ids: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
05/30/2022 08:36:16 - INFO - scripts.utils -   label: 1
05/30/2022 08:36:20 - INFO - scripts.utils -   Writing example 10000 of 10234
05/30/2022 08:36:20 - INFO - __main__ -   ***** Running training *****
05/30/2022 08:36:20 - INFO - __main__ -     Num examples = 10234
05/30/2022 08:36:20 - INFO - __main__ -     Num Epochs = 3
05/30/2022 08:36:20 - INFO - __main__ -     Instantaneous batch size per GPU = 16
05/30/2022 08:36:20 - INFO - __main__ -     Total train batch size (w. parallel, distributed & accumulation) = 16
05/30/2022 08:36:20 - INFO - __main__ -     Gradient Accumulation steps = 1
05/30/2022 08:36:20 - INFO - __main__ -     Total optimization steps = 1920
Epoch:   0%|                                              | 0/3 [00:00<?, ?it/s]
Iteration:   0%|    05/30/2022 08:36:20 - WARNING - pytorch_transformers.modeling_roberta -   A sequence with no special tokens has been passed to the RoBERTa model. This model requires special tokens in order to work. Please specify add_special_tokens=True in your encoding.
/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 20480 bytes
'
zsh: abort      python ./scripts/run_experiment.py --model_type roberta_mc  roberta-large    
/Users/davidlaxer/anaconda3/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 4 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
```

### Versions

'''
 % python collect_env.py
Collecting environment information...
PyTorch version: 1.13.0a0+gitcbdb694
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.4 (x86_64)
GCC version: Could not collect
Clang version: 13.1.6 (clang-1316.0.21.2.5)
CMake version: version 3.22.4
Libc version: N/A

Python version: 3.8.13 (default, Mar 28 2022, 06:16:26)  [Clang 12.0.0 ] (64-bit runtime)
Python platform: macOS-10.16-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.22.3
[pip3] numpydoc==1.2
[pip3] pytorch-lightning==1.6.3
[pip3] pytorch-transformers==1.1.0
[pip3] torch==1.13.0a0+gitcbdb694
[pip3] torchmetrics==0.8.2
[pip3] torchtext==0.12.0
[pip3] torchvision==0.13.0.dev20220517
[conda] blas                      1.0                         mkl    anaconda
[conda] libblas                   3.9.0              12_osx64_mkl    conda-forge
[conda] libcblas                  3.9.0              12_osx64_mkl    conda-forge
[conda] liblapack                 3.9.0              12_osx64_mkl    conda-forge
[conda] liblapacke                3.9.0              12_osx64_mkl    conda-forge
[conda] mkl                       2021.4.0           hecd8cb5_637    anaconda
[conda] mkl-include               2022.0.0           hecd8cb5_105    anaconda
[conda] mkl-service               2.4.0            py38h9ed2024_0    anaconda
[conda] mkl_fft                   1.3.1            py38h4ab4a9b_0    anaconda
[conda] mkl_random                1.2.2            py38hb2f4e1b_0    anaconda
[conda] numpy                     1.22.3                   pypi_0    pypi
[conda] numpy-base                1.21.5           py38h3b1a694_2    anaconda
[conda] numpydoc                  1.2                pyhd3eb1b0_0    anaconda
[conda] pytorch                   1.11.0                  py3.8_0    pytorch
[conda] pytorch-lightning         1.6.3                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.12.0.dev20220517          pypi_0    pypi
[conda] torchmetrics              0.8.2                    pypi_0    pypi
[conda] torchtext                 0.12.0                     py38    pytorch
[conda] torchvision               0.13.0.dev20220517          pypi_0    pypi
(base) davidlaxer@x86_64-apple-darwin13 winogrande % ipython
Python 3.8.13 (default, Mar 28 2022, 06:16:26) 
Type 'copyright', 'credits' or 'license' for more information
IPython 8.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: print(torch.__version__)
1.13.0a0+gitcbdb694

'''

**Comment by scalastic** [comment] 2022-05-31 03:24
I am reassured :) I got the same error on an Apple M1:

`
/AppleInternal/Library/BuildRoots/b6051351-c030-11ec-96e9-3e7866fcf3a1/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:782: failed assertion [MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 5120 bytes
`

**Comment by dbl001** [comment] 2022-05-31 14:22
I did a ‘git pull’, rebuilt PyTorch from source and now it’s running.

**Comment by razarmehr** [comment] 2022-05-31 17:25
Duplicate of #78247
This issue is fixed in the latest nightly build.

**Comment by kulinseth** [comment] 2022-05-31 17:29
Duplicate of https://github.com/pytorch/pytorch/issues/78247

**Closed by kulinseth** 2022-05-31 17:29 UTC
Labels: triaged, module: mps
