### ISSUE TITLE
NotImplementedError: The operator 'aten::_fft_r2c' is not currently implemented for the MPS device.

### ISSUE THREAD

**Issue by pradeepkr1003** [pytorch/pytorch#116392] opened 2023-12-25 12:09 UTC
+1 

NotImplementedError: The operator 'aten::_fft_r2c' is not currently implemented for the MPS device.

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment] 2023-12-26 18:26
Closing as duplicate of https://github.com/pytorch/pytorch/issues/78044 will try to push change soon

**Closed by malfet** 2023-12-26 18:26 UTC
Labels: triaged, module: mps
