### ISSUE TITLE
The empty 1D or more D tensor for `mode()` with the deepest `dim` doesn't work

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#131245] opened 2024-07-19 19:33 UTC
### 🐛 Describe the bug

The empty 1D or more D tensor for [mode()](https://pytorch.org/docs/stable/generated/torch.mode.html) with the deepest `dim` gets the errors as shown below:

```python
import torch

my_tensor = torch.tensor([]) # 1D tensor

torch.mode(input=my_tensor, dim=0) # Error

my_tensor = torch.tensor([[]]) # 2D tensor

torch.mode(input=my_tensor, dim=1) # Error

my_tensor = torch.tensor([[[]]]) # 3D tensor

torch.mode(input=my_tensor, dim=2) # Error
```

> IndexError: mode(): Expected reduction dim 0 to have non-zero size.

> IndexError: mode(): Expected reduction dim 1 to have non-zero size.

> IndexError: mode(): Expected reduction dim 2 to have non-zero size.

In addition, the empty 2D or 3D tensor for `mode()` with `dim=0` or `dim=0` and `dim=1` respectively works as shown below:

```python
import torch

my_tensor = torch.tensor([[]]) # 2D tensor

torch.mode(input=my_tensor, dim=0)
# torch.return_types.mode(
# values=tensor([]),
# indices=tensor([], dtype=torch.int64))

my_tensor = torch.tensor([[[]]]) # 3D tensor

torch.mode(input=my_tensor, dim=0)
torch.mode(input=my_tensor, dim=1)
# torch.return_types.mode(
# values=tensor([], size=(1, 0)),
# indices=tensor([], size=(1, 0), dtype=torch.int64))
```

### Versions

```python
import torch

torch.__version__ # 2.3.1+cu121
```

cc @malfet @albanD

**Comment by albanD** [comment] 2024-07-19 20:58
Thanks for the report.
We would accept a PR making the behavior consistent.

**Comment by ambareesh1510** [comment] 2024-07-20 01:54
Is this behavior unintended? [This comment](https://github.com/pytorch/pytorch/issues/34907#issuecomment-786737687) seems to imply that `mode()` should error when called on an empty dimension but work when called on a non-empty dimension of a zero-element tensor, which is consistent with the current behavior.

**Comment by albanD** [comment] 2024-07-22 16:53
Ho my bad!
I forgot that `my_tensor = torch.tensor([[]])` gives you a Tensor with shape `(1, 0)`, so it is expected that the last dimension behaves differently!

Closing as expected behavior then!

**Closed by albanD** 2024-07-22 16:53 UTC
Labels: module: error checking, triaged, actionable, module: python frontend, module: edge cases, module: empty tensor
