### ISSUE TITLE
ArrayRef length issue when export pytorch model to onnx

### ISSUE THREAD

**Issue by weidezhang** [pytorch/pytorch#39762] opened 2020-06-09 23:55 UTC
## 🐛 Bug

Hi 

I have some problem converting my pytorch model into onnx. My input to the model is a list(since I define my own data loader collate_fn), where length of the list is the batch size and each element in the list is a custom tuple of elements. My output is a tensor with shape: batchsize x height x width 

The code converting model to onnx:
<code>
        # Export the model
        torch.onnx.export(model, cuda(X), "final.onnx", export_params=True,  opset_version=9,        
                  do_constant_folding=True,  input_names = ['input'],   output_names = ['pred_traj_tensor'],  dynamic_axes={'input' : {0 : 'batch_size'},   'pred_traj_tensor' : {0 : 'batch_size'}}, verbose=True)
</code> 

Runtime Error: 
<code>
File “/home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/onnx/utils.py”, line 144, in _optimize_graph
torch._C._jit_pass_onnx_peephole(graph, _export_onnx_opset_version, fixed_batch_size)
RuntimeError: ArrayRef: invalid index Index = 0; Length = 0 (at at /opt/conda/conda-bld/pytorch_1579022034529/work/c10/util/ArrayRef.h:197)
</code> 

Really don't know how to debug further. Any help is greatly appreciated !  

Here is the detailed stack trace. 

<code>
Traceback (most recent call last):
  File "learning_algorithms/prediction/datasets/apollo_vehicle_trajectory_dataset/convert_onnx.py", line 113, in <module>
    'pred_traj_tensor' : {0 : 'batch_size'}})
  File "/home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/onnx/__init__.py", line 148, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "/home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "/home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 418, in _export
    fixed_batch_size=fixed_batch_size)
  File "/home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 298, in _model_to_graph
    fixed_batch_size=fixed_batch_size, params_dict=params_dict)
  File "/home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/onnx/utils.py", line 144, in _optimize_graph
    torch._C._jit_pass_onnx_peephole(graph, _export_onnx_opset_version, fixed_batch_size)
RuntimeError: ArrayRef: invalid index Index = 0; Length = 0 (at at /opt/conda/conda-bld/pytorch_1579022034529/work/c10/util/ArrayRef.h:197)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x47 (0x7fb2baa2c627 in /home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x6f484b (0x7fb2ed63184b in /home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #2: <unknown function> + 0x7003ec (0x7fb2ed63d3ec in /home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #3: torch::jit::PeepholeOptimizeONNX(std::shared_ptr<torch::jit::Graph>&, int, bool) + 0x125 (0x7fb2ed642985 in /home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0x6b496c (0x7fb2ed5f196c in /home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #5: <unknown function> + 0x28c076 (0x7fb2ed1c9076 in /home/weide/anaconda3/envs/fuel-py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
<omitting python frames>
frame #36: __libc_start_main + 0xe7 (0x7fb30ac9ab97 in /lib/x86_64-linux-gnu/libc.so.6)
</code>

 - PyTorch Version): 1.4
 - OS (e.g., Linux): Ubuntu 18.04
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Python version: 3,7
 - CUDA/cuDNN version: 10.1

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment] 2020-06-12 05:33
@weidezhang - I am not sure from the info youhave provided, but the cuda(X) input to the export may be something to look at. Can you try exporting the model on CPU only first? If you still see this issue, please share your model or some repro steps and the export code. 

As an aside, it would be great if you can update to PyTorch 1.5 as many ONNX related updates have gone in since 1.4.

**Comment by weidezhang** [comment] 2020-06-27 22:43
Hi I tried cpu input as well as switching to pytorch 1.5. The problem still exists. I will try to see if i can provide a simple script to reproduce this issue. Thank you.

**Comment by weidezhang** [comment] 2020-06-28 00:10
Please see the attached issue.tar.gz. In order to run, please use **python convert.py**. Attached is the convert code. 
[issue.tar.gz](https://github.com/pytorch/pytorch/files/4841461/issue.tar.gz)
Model file is located at: 
https://www.dropbox.com/s/v2giz7q8le65ndl/model_epoch2_valloss7.153702.pt?dl=0

**Comment by spandantiwari** [comment] 2020-06-30 22:47
Thanks @weidezhang.
@KsenijaS - can you please take a look? Thanks.

**Comment by KsenijaS** [comment] 2020-07-06 16:57
Hi @weidezhang,
The issue is caused by empty out list in scripted function roi_pooling, out is populated inside the loop with append method, when converted to ONNX out will still be an empty list. That is a know issue in ONNX scripting. I created a test case to reproduce your issue:
```
import torch
import torch.nn as nn

class Flatten(nn.Module):
    def forward(self, input):
        return input.view(input.size(0), -1)

@torch.jit.script
def roi_pooling(x):
    # type: (Tensor) -> List[Tensor]
    out = []
    for i in range(1):
        out.append(x)
    return out

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.adaptive_avg_pool = torch.nn.Sequential(
            nn.AdaptiveAvgPool2d((1,1)),
            Flatten(),
            nn.Linear(512, 50),
            nn.ReLU(),
            )
    def forward(self, x):
        out = roi_pooling(x)
        out = [self.adaptive_avg_pool(x) for x in out]
        output_concat = torch.cat(out, 0)
        return output_concat

x = torch.randn(1, 512, 10, 10)

model = MyModule()
torch.onnx.export(model,               # model being run
                   x,                         # model input (or a tuple for multiple inputs)
                  "final.onnx",   # where to save the model (can be a file or file-like object)
                  #export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=12, verbose=True,          # the ONNX version to export the model to
                  do_constant_folding=True)
```
And there are 2 issue here:
1. loop + append that creates an empty list in ONNX graph
2. avgpool is applied inside the loop and that part is not scripted
So the work around would look something like this:
```
import torch
import torch.nn as nn
class Flatten(nn.Module):
    def forward(self, input):
        return input.view(input.size(0), -1)

@torch.jit.script
def roi_pooling(x):
    # type: (Tensor) -> (Tensor)
    return x

class RoiPooling(torch.jit.ScriptModule):
    def __init__(self):
        super(RoiPooling, self).__init__()
        self.adaptive_avg_pool = torch.nn.Sequential(
            nn.AdaptiveAvgPool2d((1,1)),
            Flatten(),
            nn.Linear(512, 50),
            nn.ReLU(),
            )
    @torch.jit.script_method
    def forward(self, x):
        out = roi_pooling(x)
        out = self.adaptive_avg_pool(out)
        for i in range(1, 2):
            x_out = roi_pooling(x)
            x_out = self.adaptive_avg_pool(x)
            out = torch.cat([out, x_out], 0)
        return out

class MyModule(nn.Module):
    def __init__(self):
        super(MyModule, self).__init__()
        self.roi_pool = RoiPooling()
    def forward(self, x):
        out = self.roi_pool(x)
        return out

x = torch.randn(1, 512, 10, 10)
model = torch.jit.trace(MyModule(), x)
torch.onnx.export(model,               # model being run
                  x,                         # model input (or a tuple for multiple inputs)
                  "final.onnx",   # where to save the model (can be a file or file-like object)
                  #export_params=True,        # store the trained parameter weights inside the model file
                  opset_version=11, verbose=True,          # the ONNX version to export the model to
                  do_constant_folding=True,
                  example_outputs=model(x))
```
Maybe you can try to apply the same workaround in your model.

**Comment by spandantiwari** [comment] 2020-07-08 00:10
@weidezhang - As @KsenijaS mentioned this is know issue that stems from the fact that TorchIR is not functional IR whereas ONNX is. This root issue is also captured in this issue https://github.com/pytorch/pytorch/issues/39362. Could you please try the workaround and see if it unblocks you for now. We are investigating how to address this issue long-term. If the workaround unblocks you, we can close this issue and track the https://github.com/pytorch/pytorch/issues/39362 for the root cause.

**Comment by weidezhang** [comment] 2020-07-08 23:09
thank you. i will take a look and let you know shortly.

**Comment by weidezhang** [comment] 2020-07-09 04:17
Hi @KsenijaS, I changed based on your recommendation. 
[issue_v2.tar.gz](https://github.com/pytorch/pytorch/files/4894434/issue_v2.tar.gz). However, the model loading now has issues. RuntimeError: Error(s) in loading state_dict for TrajectoryPredictionSingle:
	Unexpected key(s) in state_dict: "adaptive_avg_pool.2.weight", "adaptive_avg_pool.2.bias".

**Comment by weidezhang** [comment] 2020-07-09 04:19
here is the model file i retrained: 
https://www.dropbox.com/s/0astqvqhps318tp/model_epoch1_valloss53.659508.pt?dl=0

**Comment by KsenijaS** [comment] 2020-08-10 20:05
If you want to use state _dict you need to update it, because init function has changed.
I modified image_model.py and convert.py files. Use the latest pytorch (pytorch-nightly to run) because you need support for tensor operator. 

[convert_to onnx.zip](https://github.com/pytorch/pytorch/files/5053090/convert_to.onnx.zip)

**Comment by spandantiwari** [comment] 2020-09-02 20:06
Should be addressed by https://github.com/pytorch/pytorch/pull/41872.

**Closed by spandantiwari** 2020-09-02 20:06 UTC
Labels: module: onnx, triaged
