### ISSUE TITLE
libtorch forward efficiency  synchroni

### ISSUE THREAD

**Issue by LoveZL0512** [pytorch/pytorch#19343] opened 2019-04-17 06:53 UTC
## 🐛 Bug
![image](https://user-images.githubusercontent.com/11365001/56267119-79b0fa00-6120-11e9-9b1d-cbebf41fb67f.png)

**Comment by VitalyFedyunin** [comment] 2019-04-17 17:28
Hi! Can you please add url of the original issue and describe what is the problem statement.

**Comment by soumith** [comment] 2019-04-17 21:29
duplicate of https://github.com/pytorch/pytorch/issues/19305

**Closed by soumith** 2019-04-17 21:29 UTC
