### ISSUE TITLE
torch.autograd.Function with multiple outputs returns outputs not requiring grad

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#55509] opened 2021-04-07 18:47 UTC
## torch.autograd.Function with multiple outputs returns outputs not requiring grad

If the forward function of a `torch.autograd.function` takes in multiple inputs and returns them as outputs, the returned outputs don't require grad. See repro below:

```
import torch
import torch.nn as nn
from torch.autograd import Function


class PassThrough(Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input

    @staticmethod
    def backward(ctx, grad_outputs):
        print(f"grad_outputs {grad_outputs}")
        return grad_outputs


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.a = nn.Linear(1, 1, bias=False)
        self.b = nn.Linear(1, 1, bias=False)

    def forward(self, x):
        a, b = self.a(x), self.b(x)
        ret = a, b
        print(f"In fwd pass {ret[0].requires_grad}")
        ret = PassThrough.apply(ret)
        print(f"After passthrough {ret[0].requires_grad}")
        return ret


model = MyModel()
inp = torch.ones(1)
out = model(inp)
loss = out[0] + out[1]
loss.backward()
```

According to the output, after applying `PassThrough`, the outputs no longer require grad, causing an error in the backward pass:
```
In fwd pass True
After passthrough False
Traceback (most recent call last):
  File "<string>", line 38, in <module>
  File "<string>", line 36, in __run
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/fbcode/platform009/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/users/rvarm1/fbsource/fbcode/buck-out/dev/gen/scripts/rvarm1/ddp/ddp_custom_function#link-tree/scripts/rvarm1/ddp/ddp_custom_function.py", line 44, in <module>
  File "/data/users/rvarm1/fbsource/fbcode/buck-out/dev/gen/scripts/rvarm1/ddp/ddp_custom_function#link-tree/torch/_tensor.py", line 255, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/data/users/rvarm1/fbsource/fbcode/buck-out/dev/gen/scripts/rvarm1/ddp/ddp_custom_function#link-tree/torch/autograd/__init__.py", line 146, in backward
    Variable._execution_engine.run_backward(
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

The following, which uses just a single tensor instead of a tuple of 2 tensors, works as expected:

```
import torch
import torch.nn as nn
from torch.autograd import Function


class PassThrough(Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        return input

    @staticmethod
    def backward(ctx, grad_outputs):
        print(f"grad_outputs {grad_outputs}")
        return grad_outputs


class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.a = nn.Linear(1, 1, bias=False)
        self.b = nn.Linear(1, 1, bias=False)

    def forward(self, x):
        a, b = self.a(x), self.b(x)
        ret = a
        print(f"In fwd pass {ret.requires_grad}")
        ret = PassThrough.apply(ret)
        print(f"After passthrough {ret.requires_grad}")
        return ret


model = MyModel()
inp = torch.ones(1)
out = model(inp)
out.sum().backward()
```

Output:
```
In fwd pass True
After passthrough True
grad_outputs tensor([1.])
```

My question is, is torch.autograd.function not intended to be used this way or should it work correctly with multiple output tensors? 

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by albanD** [comment] 2021-04-07 19:14
This is expected behavior. The custom Function only considers Tensors in the input/output (not ones that are nested inside python data structures).
You should take the Tensors out of the data structures if you want them to be considered by autograd.

**Comment by rohan-varma** [comment] 2021-04-07 21:07
Thanks for clarifying Alban, I think in DDP we can use `_find_tensors` and in general do something similar to what `Scatter` autograd function does in terms of finding the tensors in the nested python data structure. Then we can provide these tensors directly to the custom autograd function we need.

**Comment by zou3519** [comment] 2021-04-07 21:14
@rohan-varma there are some utilities for "finding tensors" in https://github.com/pytorch/pytorch/blob/master/torch/utils/_pytree.py, if you haven't written `_find_tensors` already. Some sample usage:
```
xs = [[torch.tensor(1), torch.tensor(2)], (torch.tensor(3),)]
tensors_in_xs, _ = tree_flatten(xs)
```

**Comment by rohan-varma** [comment] 2021-04-08 00:47
> @rohan-varma there are some utilities for "finding tensors" in https://github.com/pytorch/pytorch/blob/master/torch/utils/_pytree.py, if you haven't written `_find_tensors` already. Some sample usage:
> 
> ```
> xs = [[torch.tensor(1), torch.tensor(2)], (torch.tensor(3),)]
> tensors_in_xs, _ = tree_flatten(xs)
> ```

That's great! We had rolled our own `_find_tensors` in DDP: https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/distributed.py#L31 but it might be good to change this to tree_flatten.

**Comment by albanD** [comment] 2021-04-08 14:59
Closing as expected behavior. But feel free to continue the discussion about pytree here.

**Closed by albanD** 2021-04-08 14:59 UTC
Labels: module: autograd, triaged

**Comment by rohan-varma** [comment] 2021-04-09 07:23
@albanD one question that I'm still not clear on - is it expected behavior that the `requires_grad` field of the tensors nested in the tuple changes from True to False? That seems pretty unexpected and I'm not sure why that happens over the alternative of leaving the tensors untouched.

**Comment by albanD** [comment] 2021-04-09 21:59
Well, returning tuples from a python function is always dangerous, because doing `return a[0], a[1]` is the same as `return a`.
So effectively, in your custom function here, you actually return the Tensors "unpacked" and so they are properly post-processed by the custom Function. And since there were not inputs that required gradients (no Tensor in this case), then the outputs don't need to require gradients either.
