### ISSUE TITLE
tensor.to() raises error in C++

### ISSUE THREAD

**Issue by LinxiFan** [pytorch/pytorch#39525] opened 2020-06-04 16:02 UTC
## 🐛 Bug

`tensor.to(copy=True)` raises error in C++

## To Reproduce

```python
import torch

x = torch.tensor([1,2,3])
x.to(device=None, copy=True)
```

raises exception:
```
python: /opt/conda/..../work/c10/util/Optional.h:596: T& c10::optional<T>::operator*() [with T = c10::ScalarType]: Assertion `initialized()' failed.
[1]    13763 abort (core dumped)  python test.py
```

## Expected behavior

According to the doc, `to()` method should accept `copy=True` argument without problem.

## Environment

```
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration:
GPU 0: TITAN RTX

Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.6
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.16.6                   pypi_0    pypi
[conda] pytorch                   1.4.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py37_cu101    pytorch
```

**Comment by colesbury** [comment] 2020-06-04 19:41
Thanks for the bug report. I can reproduce the issue in 1.4.0. It is fixed in 1.5.0 and the 1.6 dev branch.

I'm closing the issue because it's fixed in the latest release and I don't think we'll be doing bug fixes for 1.4.0.

As a workaround, you can use: `x.clone()` to make a copy of `x`.

**Closed by colesbury** 2020-06-04 19:41 UTC
Labels: topic: crash
