### ISSUE TITLE
Pytorch in multi-cpu cluster

### ISSUE THREAD

**Issue by marcsv87** [pytorch/pytorch#2733] opened 2017-09-14 11:16 UTC
Hi, 
I would like to use the distributed module to train a convolution net in a CPU cluster. Investigating your code, the function torch.cuda.device_count() is called in several places, and is used to populate the device_ids list. Since I don't have any GPU devices in my cluster, the method device_count() will always return 0 and any subsequent attempt to access device_ids[0] will result in an index exception.
Taking a naive path and changing device_count so that it always returns the number of nodes I intend to use then I get a different error: 

if not all(input.is_cuda for input in inputs):
   raise TypeError('Broadcast function not implemented for CPU tensors')

So I would like to ask you whether you have any plans to implement the distributed module to train networks in a multi-cpu cluster.

Many thanks

**Comment by apaszke** [comment] 2017-09-19 21:16
Just to confirm - when you say multi-cpu cluster you don't mean having 2 CPUs within a single computer (NUMA), but an actual cluster with multiple machines, right?

The problem is that `DistributedDataParallel` doesn't support non-CUDA networks right now. We should implement it at some point.

**Comment by marcsv87** [comment] 2017-09-20 08:33
Yes I meant a cluster with multiple machines. 

No problem, I'll keep an eye for new updates.

Thanks

**Comment by rabeehk** [comment] 2019-01-14 13:52
Hi
I am trying to run distributeddataparallelCPU module for a simple model,
Here is the file(test.py) I wrote:

```
import torch.distributed as dist
import os
import argparse
import torch
import torch.nn as nn
import torch.nn.functional as F

parser = argparse.ArgumentParser()
parser.add_argument('--local_rank', default=0, type=int)
args = parser.parse_args()
dist.init_process_group(backend="mpi", init_method="env://",
                       world_size = int(os.environ["WORLD_SIZE"]), rank=args.local_rank)
## Model.
class Model(nn.Module):
    def __init__(self):
        super(Model, self).__init__()
        self.conv1 = nn.Conv2d(1, 20, 5)
        self.conv2 = nn.Conv2d(20, 20, 5)

    def forward(self, x):
       x = F.relu(self.conv1(x))
       return F.relu(self.conv2(x))

model = Model() 
net = torch.nn.parallel.DistributedDataParallelCPU(model)
```
and I call the file as below:
```
python -m torch.distributed.launch  --nnodes=1 --node_rank=0 --master_addr=127.0.0.1 --master_port=6006  test.py 
```
I got the error that 
RuntimeError: the MPI backend is not available; try to recompile the THD package with MPI support at /opt/conda/conda-bld/pytorch_1532581333611/work/torch/lib/THD/process_group/General.cpp:17

Thanks for your assistance

**Comment by sth1997** [comment] 2019-05-23 07:27
Excuse me, does `DistributedDataParallel'  support non-CUDA networks right now?

**Comment by sth1997** [comment] 2019-05-23 07:27
Excuse me, does `DistributedDataParallel` support non-CUDA networks right now?

**Comment by mrshenli** [comment] 2019-05-24 17:43
@sth1997 @marcsv87 DDP on CPU devices should be available now (see [doc](https://github.com/pytorch/pytorch/blob/master/torch/nn/parallel/distributed.py#L174)). I am closing this one,  but feel free to reopen this issue if it fails to work for you. 

@rabeeh that seems to be a different issue than the original published one. If you still need assistance on that, could you please post create a new issue for it?

**Closed by mrshenli** 2019-05-24 17:43 UTC
Labels: module: distributed, triaged
