### ISSUE TITLE
error: 'cout' is not a member of 'std' on ppc64le

### ISSUE THREAD

**Issue by cdeepali** [pytorch/pytorch#66077] opened 2021-10-04 13:29 UTC
## 🐛 Bug

Observed the following error while building PyTorch v1.10.0-rc1 on ppc64le. 

```
In file included from ../aten/src/ATen/cpu/vec/vec256/vsx/vec256_common_vsx.h:6:0,
                 from ../aten/src/ATen/cpu/vec/vec256/vec256.h:19,
                 from ../aten/src/ATen/cpu/vec/vec.h:4,
                 from ../aten/src/ATen/test/vec_test_all_types.h:2,
                 from ../aten/src/ATen/test/vec_test_all_types.cpp:1:
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h: In constructor 'at::vec::{anonymous}::Vectorized<double>::Vectorized(double)':
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h:42:39: warning: parameter 'scalar' set but not used [-Wunused-but-set-parameter]
   C10_ALWAYS_INLINE Vectorized(double scalar)
                                       ^~~~~~
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h: In member function 'void at::vec::{anonymous}::Vectorized<double>::dump() const':
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h:192:12: error: 'cout' is not a member of 'std'
       std::cout << _vec0[0] << "," << _vec0[1] << "," << _vec1[0] << "," << _vec1[1] << std::endl;
            ^~~~
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h:192:12: note: suggested alternative: 'count'
       std::cout << _vec0[0] << "," << _vec0[1] << "," << _vec1[0] << "," << _vec1[1] << std::endl;
```

## To Reproduce

Build PyTorch on ppc64le with USE_BREAKPAD=0. 

## Expected behavior

Build should succeed. 

## Additional context

This error is seen for the following files before the build fails:

```
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h:192:12: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_float_vsx.h:440:10: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_float_vsx.h:442:10: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_quint8_vsx.h:376:12: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_quint8_vsx.h:378:10: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_float_vsx.h:413:10: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_float_vsx.h:415:10: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_double_vsx.h:360:10: error: 'cout' is not a member of 'std'
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_complex_double_vsx.h:361:10: error: 'cout' is not a member of 'std'
```

**Comment by cdeepali** [comment] 2021-10-04 13:41
I have been trying to identify the change which could have caused this. And I start to see these error at the commit - 0a66d5b3253fd2d2304f3897526db3c8fb139376.

I have tried to remove `dump()` method from the above mentioned header files as in https://github.com/pytorch/pytorch/commit/b99a299c6002354acef5c43eba5cd25b41e773c7.  This solves the errors I pasted above but leads to numerous other errors in subsequent stage of the build.

**Comment by cdeepali** [comment] 2021-10-04 13:45
Just noticed that this has been reported in - https://github.com/pytorch/pytorch/issues/65956 as well.

**Comment by albanD** [comment] 2021-10-04 14:30
cc @malfet should we add a 1.10 milestone on this?

**Comment by malfet** [comment] 2021-10-04 15:28
Closing as duplicate of  #65956

**Closed by malfet** 2021-10-04 15:28 UTC
Labels: triaged, module: regression, module: POWER

**Comment by malfet** [comment] 2021-10-04 16:29
@cdeepali can you please check if https://github.com/pytorch/pytorch/pull/66085 will fix this particular issue?

**Comment by cdeepali** [comment] 2021-10-05 08:39
Thanks @malfet for quick PR on this. 

These changes do fix this current issue, but lead to other errors at the subsequent stage of compilation. 

The next error observed is:

```
../aten/src/ATen/native/cpu/layer_norm_kernel.cpp.VSX.cpp: In function 'void at::native::{anonymous}::LayerNormKernelImplInternal(const at::Tensor&, const at::Tensor&, const at::Tensor&, int64_t, int64_t, T, at::Tensor*, at::Tensor*, at::Tensor*)':
../aten/src/ATen/native/cpu/layer_norm_kernel.cpp.VSX.cpp:29:22: error: 'vec_scalar_t' in namespace 'at::vec' does not name a template type
   using T_ACC = vec::vec_scalar_t<T>;
                      ^~~~~~~~~~~~
../aten/src/ATen/native/cpu/layer_norm_kernel.cpp.VSX.cpp:30:31: error: 'T_ACC' was not declared in this scope
   using Vec = vec::Vectorized<T_ACC>;
                               ^~~~~
In file included from ../aten/src/ATen/cpu/vec/vec256/vsx/vec256_common_vsx.h:7:0,
                 from ../aten/src/ATen/cpu/vec/vec256/vec256.h:19,
                 from ../aten/src/ATen/cpu/vec/vec.h:4,
                 from ../aten/src/ATen/native/cpu/UnfoldBackwardKernel.cpp.VSX.cpp:2:
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_float_vsx.h: In constructor 'at::vec::{anonymous}::Vectorized<float>::Vectorized(float)':
../aten/src/ATen/cpu/vec/vec256/vsx/vec256_float_vsx.h:43:38: warning: parameter 'scalar' set but not used [-Wunused-but-set-parameter]
   C10_ALWAYS_INLINE Vectorized(float scalar)
                                      ^~~~~~
../aten/src/ATen/native/cpu/layer_norm_kernel.cpp.VSX.cpp:30:36: error: template argument 1 is invalid
   using Vec = vec::Vectorized<T_ACC>;
```
