### ISSUE TITLE
nn.utils.rnn.pack_padded_sequence: RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor

### ISSUE THREAD

**Issue by myleott** [pytorch/pytorch#43227] opened 2020-08-18 21:43 UTC
## 🐛 Bug

With latest nightly I can't pass a CUDA tensor for the `lengths` argument to `nn.utils.rnn.pack_padded_sequence`.

## To Reproduce

```python
import torch
from torch.nn.utils.rnn import pack_padded_sequence
seq = torch.tensor([[1,2,0], [3,0,0], [4,5,6]], device='cuda')
lens = torch.tensor([2, 1, 3], device='cuda')
pack_padded_sequence(seq, lens, enforce_sorted=False)
# RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

## Expected behavior

This works on torch 1.5:
```python
seq = torch.tensor([[1,2,0], [3,0,0], [4,5,6]], device='cuda')
lens = torch.tensor([2, 1, 3], device='cuda')
pack_padded_sequence(seq, lens, enforce_sorted=False)
# PackedSequence(data=tensor([0, 1, 2, 0, 3, 6], device='cuda:0'), batch_sizes=tensor([3, 2, 1]), sorted_indices=tensor([2, 0, 1], device='cuda:0'), unsorted_indices=tensor([1, 2, 0], device='cuda:0'))
```

## Environment

 - PyTorch Version (e.g., 1.0): 1.7.0.dev20200817+cu101
 - OS (e.g., Linux): Ubuntu
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version: 3.6.10
 - CUDA/cuDNN version: CUDA 10.1, cuDNN 7.6.5.32
 - GPU models and configuration: 8 x V100
 - Any other relevant information:

cc @ezyang @gchanan @zou3519 @bdhirsh @jlin27 @mruberry @ngimel

**Comment by ngimel** [comment] 2020-08-21 01:59
It's because of this PR https://github.com/pytorch/pytorch/pull/41984, that preserves the device of `as_tensor` argument if it's torch tensor. pack_padded_sequence calls `as_tensor` on the `lengths` tensor: https://github.com/pytorch/pytorch/blob/master/torch/nn/utils/rnn.py#L234 that used to cause implicit copy before, but does not now. 
Given that implementation does not do anything smart with the lengths on the GPU, and only copies and synchronizes behind users back, @myleott do you think we should restore previous behavior, or can you call `.cpu()` on the lengths in your script before calling `pack_padded_sequence`?

**Comment by KenaHemnani** [comment] 2020-11-19 17:03
@myleott I am getting the same error ,how to fix this?

**Comment by suryabulusu** [comment] 2020-11-20 18:31
@KenaHemnani for now, i converted `lengths` argument using `.cpu()`, as in,  `pack_padded_sequence(batch, lengths = seq_lens.cpu())` -- and it worked for me.

**Comment by KenaHemnani** [comment] 2020-11-20 19:07
@suryabulusu Thank you so much for replying. It worked for me as well.

**Comment by LysSanzMoreta** [comment] 2020-11-25 17:49
Hi! I am having the same problem and I am using a library(pyro-ppl) that requires all the tensors from the model/guide trace to be on the same device in order to estimate the loss. So even if lengths.cpu() solves the first issue #43227, it induces later errors in other libraries. Is it possible to be coherent and keep everything on the same device? Thank you very much for all the effort!!

**Comment by zou3519** [comment] 2020-11-30 14:51
Raising to hi-pri for user activity. I'm not sure what the final behavior should be, if we do a docs fix then we should also try to improve the error message

**Comment by gchanan** [comment] 2020-11-30 18:35
@LysSanzMoreta IMO that's a bug in the downstream library -- PyTorch's philosophy is that we try to avoid silent synchronizations not that we require all data to be on the same device.

**Comment by LysSanzMoreta** [comment] 2020-11-30 20:54
@gchanan Ok, thanks!, we found a work around

**Comment by ituantuan8** [comment] 2020-12-02 07:41
> @gchanan Ok, thanks!, we found a work around

Hello, how did you solve this problem？thank you

**Comment by ituantuan8** [comment] 2020-12-02 07:44
> @gchanan Ok, thanks!, we found a work around
@LysSanzMoreta Hello, how did you solve this problem？ thank you

**Comment by ituantuan8** [comment] 2020-12-02 07:46
@LysSanzMoreta Hello, how did you solve this problem?I have the same problee,thank you

**Comment by LysSanzMoreta** [comment] 2020-12-02 11:04
@ituantuan8 For pyro-ppl find the issue discussion here : https://forum.pyro.ai/t/pytorch-rnn-lengths-in-cpu-incompatibility-with-elbo-loss-calculation/2391/10

**Comment by ituantuan8** [comment] 2020-12-02 11:39
@LysSanzMoreta Thank you very much

**Comment by ituantuan8** [comment] 2020-12-02 11:44
@LysSanzMoreta My problem is solved, thank you so much

**Comment by Alan-hit** [comment] 2020-12-09 03:44
> @KenaHemnani for now, i converted `lengths` argument using `.cpu()`, as in, `pack_padded_sequence(batch, lengths = seq_lens.cpu())` -- and it worked for me.

work for me as well. Thank you!!

**Comment by saandeepa93** [comment] 2021-03-25 01:46
> Ah, in our case we get the lengths via something like `seq.ne(0).sum(dim=1)`, so we end up with a GPU tensor.
> 
> Perhaps we can add the CPU conversion to `pack_padded_sequence`? Otherwise we should document the CPU requirement for `lengths`. Either way I will add the `.cpu()` call to fairseq.

Hello, This doesn't seem to work for models under DataParallel module with multiple GPU nodes. Can you please let me know if there is a fix for it? 

Thank you

**Comment by samisnotinsane** [comment] 2021-04-28 22:21
> @KenaHemnani for now, i converted `lengths` argument using `.cpu()`, as in, `pack_padded_sequence(batch, lengths = seq_lens.cpu())` -- and it worked for me.

I tried this and it results in the following error:

`RuntimeError: transform: failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure`

PyTorch: 1.8.1
Platform: Windows 10
Device: GeForce GTX 1050

**Comment by javadba** [comment] 2021-06-09 01:09
I enabled cuda() and this error occurs using pytorch 1.7.1.  From the long discussion i'm still uncertain what am I supposed to do to deal with this issue.

**Comment by javadba** [comment] 2021-06-09 01:11
One of the last comments was: 

> I suggest we just document CPU requirement rather than implicitly cast the length. It's better if user is aware of the limitation instead of trying to debug why synchronization is happening.  

Is this required fix documented somewhere at this point

**Comment by MinionAttack** [comment] 2021-07-16 08:39
Hi, reading the comments we can't use anymore CUDA cores? I have to specify:

`pack_padded_sequence(scores[sort_ind], decode_lengths.cpu(), batch_first=True)[0]`

To be able to train with pytorch 1.9.0.

Regards.

**Comment by mruberry** [comment] 2021-08-12 21:50
> Hi, reading the comments we can't use anymore CUDA cores? I have to specify:
> 
> `pack_padded_sequence(scores[sort_ind], decode_lengths.cpu(), batch_first=True)[0]`
> 
> To be able to train with pytorch 1.9.0.
> 
> Regards.

You can still use CUDA but the second argument, "lengths," must be a CPU tensor if it is a tensor. Another option is to pass it as a list of integers.

**Comment by mruberry** [comment] 2021-08-12 21:51
> Hello, This doesn't seem to work for models under DataParallel module with multiple GPU nodes. Can you please let me know if there is a fix for it?

DataParallel is in maintenance mode while DistributedDataParallel, which typically has improved performance, is actively developed. Would you try it with DistributedDataParallel, instead?

**Comment by mruberry** [comment] 2021-08-12 21:52
Closing this issue because this behavior is by design and the documentation states the requirement that the "lengths" argument must be on the CPU.

If there are additional issues or a request to support a CUDA "lengths" argument then please file a new issue so we can track those requests separately.

**Closed by mruberry** 2021-08-12 21:51 UTC
Labels: high priority, module: docs, module: rnn, triaged, module: regression

**Comment by MrSworder** [comment] 2022-04-21 08:24
> Hi! I am having the same problem and I am using a library(pyro-ppl) that requires all the tensors from the model/guide trace to be on the same device in order to estimate the loss. So even if lengths.cpu() solves the first issue #43227, it induces later errors in other libraries. Is it possible to be coherent and keep everything on the same device? Thank you very much for all the effort!!

Me too...

**Comment by HeegonJin** [comment] 2022-10-19 06:23
This problem is still not resolved completely.

**Comment by ngimel** [comment] 2023-03-10 17:31
Yes

**Comment by PatrickSVM** [comment] 2023-03-10 22:56
Thanks!
