### ISSUE TITLE
BrokenPipeError on Windows when setting the num_workers as 4 in DataLoader 

### ISSUE THREAD

**Issue by songyuc** [pytorch/pytorch#31465] opened 2019-12-19 09:54 UTC
## 🐛 Bug

BrokenPipeError on Windows when setting the num_workers as 4 in DataLoader 

## To Reproduce

1. I used code like this,
```Python
 testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                             shuffle=False, num_workers=4)
```
2.
3.

> Here are the error messages:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Kaggle\Digit Recognizer\digit-recognizer\main_predict.py", line 7, in <module>
    import torch
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\site-packages\torch\__init__.py", line 81, in <module>
    from torch._C import *
ImportError: DLL load failed: 页面文件太小，无法完成操作。
Traceback (most recent call last):
  File "D:/Programs/Kaggle/Digit Recognizer/digit-recognizer/main_predict.py", line 62, in <module>
    main()
  File "D:/Programs/Kaggle/Digit Recognizer/digit-recognizer/main_predict.py", line 47, in main
    for data in testloader:
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\site-packages\torch\utils\data\dataloader.py", line 278, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\site-packages\torch\utils\data\dataloader.py", line 682, in __init__
    w.start()
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Path\Python\Anaconda3\envs\env_general\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
Process finished with exit code 1

And here is the code sample:
```Python
source = "../data/digit-recognizer/test.csv"
    transform = transforms.Compose(
        [transforms.ToTensor(),
         transforms.Normalize((0.5,), (0.5,))])
    # 其中transforms.ToTensor()的作用为将维度顺序为H*W*C的图像张量装换为适合于PyTorch的C*H*W的张量
    testset = MNISTTestDataset(csv_file=source,
                               transform=transform)
    testloader = torch.utils.data.DataLoader(testset, batch_size=4,
                                             shuffle=False, num_workers=4)
    # 如果有问题的话，就把num_workers设成0

    recognizer = DigitRecognizer()
    index = 0

    for data in testloader:
        index = index + 1
        if index > 6:
            break
```

## Expected behavior

I want setting the num_workers as 4 in DataLoader.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3.1
 - OS (e.g., Linux): Win10
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - Build command you used (if compiling from source): by PyCharm
 - Python version: 3.7.3
 - CUDA/cuDNN version: CUDA 10.1
 - GPU models and configuration: using CPU
 - Any other relevant information:

## Additional context

cc @SsnL @peterjc123

**Comment by peterjc123** [comment] 2019-12-19 10:39
See https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection.

**Comment by songyuc** [comment] 2019-12-19 11:21
> See https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-without-if-clause-protection.

Thank you for the reply, but the content in that site cannot help resolve the bug.
The relevant content [_Multiprocessing error “Broken pipe”_ ](https://pytorch.org/docs/stable/notes/windows.html#multiprocessing-error-broken-pipe)  pointed out

> Multiprocessing error “Broken pipe”
ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
This issue happens when the child process ends before the parent process finishes sending data. There may be something wrong with your code. You can debug your code by reducing the num_worker of DataLoader to zero and see if the issue persists.

But my code ran normally if I set the num_workers as 2.
However, the 4 num_workers would still cause the BrokenPipeError.

Looking forward to your reply!

**Comment by peterjc123** [comment] 2019-12-19 11:24
Do you have enough RAM?

**Comment by albanD** [comment] 2019-12-19 11:27
Re-opening while the discussion goes on.

**Comment by songyuc** [comment] 2019-12-19 11:28
> Do you have enough RAM?

I guess I did, because my RAM monitor showed a 71% usage of RAM at that time.
But I am not sure the index of the RAM monitor would be the usage of my program.

**Comment by peterjc123** [comment] 2019-12-19 12:29
Could you please post a minimal reproducible code example?

**Comment by songyuc** [comment] 2019-12-19 12:42
> Could you please post a minimal reproducible code example?

In fact, I just restart my computer, and the problem disappeared. So I guess the problem might be caused by the inefficient RAM, as I had opened a lot of other Programs at the same time.

And I see there's a Error message of "ImportError: DLL load failed: 页面文件太小，无法完成操作。", which is in Chinese, because I am student from China. And in English,it said "ImportError: DLL load failed: The page file is too small to complete the operation.", so I am wondering whether this might be due to the setting of virtual memory of Win10?

And as the available RAM is always changing, I want to know is there a safe way of coding to prevent my program from broking?

**Comment by peterjc123** [comment] 2019-12-19 14:12
You should increase the size of the page file according this [tutorial](https://zhuanlan.zhihu.com/p/37332255) in Chinese.

**Comment by peterjc123** [comment] 2019-12-19 14:13
I'll close this issue first because it's caused by your environment. You can reopen it at any time.

**Closed by peterjc123** 2019-12-19 14:13 UTC
Labels: module: dataloader, module: windows, topic: crash, triaged

**Comment by songyuc** [comment] 2019-12-19 14:23
> You should increase the size of the page file according this [tutorial](https://zhuanlan.zhihu.com/p/37332255) in Chinese.

So you can read Chinese, are you? It is interesting!

**Comment by peterjc123** [comment] 2019-12-19 14:29
Sure, as you can see in the Github profile, I live in Shanghai. But most of the devs here speak English so you need to translate the words to English.
