### ISSUE TITLE
Slowdown due to thread specific model caching

### ISSUE THREAD

**Issue by CoderHam** [pytorch/pytorch#27902] opened 2019-10-14 19:10 UTC
## 🐛 Bug

PyTorch appears to have an issue with threads that causes it to not properly warm up models if executed by different threads  in succession. This is why when using multi-instances of the model on the same GPU, it does not provide a speedup and in some cases is even slower than a single instance.

## To Reproduce

**Steps to reproduce the behavior:**

I have a simple libtorch code snippet that reproduces this issue. In short all it does is run the same model (Resnet50 model from the torchvision  that was traced to produce a torchscript version of the same). The code was run on a Titian V with a batch size of 1.

1. Create model in main thread
2. Launch thread that runs model N times in a loop, reporting the runtime each time
3. Launch N threads that each run the model once, reporting the runtime each time

```
#include <torch/script.h>

#include <pthread.h>
#include <unistd.h>
#include <chrono>
#include <iostream>

struct inferStruct {
  at::Tensor output_;
  torch::jit::script::Module module_;
  std::vector<torch::jit::IValue> inputs_;
};

// Run model 5 times
void*
NForwardPass(void* run)
{
  inferStruct* run_tmp = reinterpret_cast<inferStruct*>(run);
  for (int i = 0; i < 5; i++) {
    auto t1 = std::chrono::high_resolution_clock::now();
    run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
    auto t2 = std::chrono::high_resolution_clock::now();
    auto duration =
        std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
    std::cout << duration / 1000.0
              << " ms to run model in process thread (NForwardPass)"
              << std::endl;
  }
}

// Run model 1 time
void*
ForwardPass(void* run)
{
  inferStruct* run_tmp = reinterpret_cast<inferStruct*>(run);
  auto t1 = std::chrono::high_resolution_clock::now();
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
  auto t2 = std::chrono::high_resolution_clock::now();
  auto duration =
      std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
  std::cout << duration / 1000.0
            << " ms to run model in process thread (ForwardPass)" << std::endl;
}

int
main()
{
  // Model loaded in main thread
  torch::Device device_ = torch::Device(torch::kCUDA, 0);
  std::string model_path = "resnet50_libtorch.pt";
  torch::jit::script::Module module1 = torch::jit::load(model_path, device_);
  std::vector<torch::jit::IValue> inputs_(1);
  inputs_[0] = torch::zeros({1, 3, 224, 224}).to(device_);
  // pre-warm model
  at::Tensor output = module1.forward(inputs_).toTensor();

  inferStruct run1;
  pthread_t thread_id1;  //, thread_id2;

  run1.module_ = module1;
  run1.inputs_ = inputs_;

  // Run model in main thread N times and report runtime each time
  for (int i = 0; i < 5; i++) {
    auto t1 = std::chrono::high_resolution_clock::now();
    output = module1.forward(inputs_).toTensor();
    auto t2 = std::chrono::high_resolution_clock::now();
    auto duration =
        std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
    std::cout << duration / 1000.0 << " ms to run model in main thread"
              << std::endl;
  }
  sleep(1);

  // Run N threads and in each run model once and report runtime each time
  std::cout << std::endl;
  for (int i = 0; i < 5; i++) {
    pthread_create(&thread_id1, NULL, ForwardPass, &run1);
    pthread_join(thread_id1, NULL);
  }
  sleep(1);

  // Run 1 thread and in it run the model N and report runtime each time
  std::cout << std::endl;
  pthread_create(&thread_id1, NULL, NForwardPass, &run1);
  pthread_join(thread_id1, NULL);

  return 0;
}
```
## Environment

Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: No
CUDA runtime version: 10.1.243
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3

Versions of relevant libraries:
[pip] msgpack-numpy==0.4.3.2
[pip] numpy==1.16.4
[pip] torch==1.2.0a0+afb7a16
[pip] torchtext==0.4.0
[pip] torchvision==0.3.0a0
[conda] magma-cuda100             2.5.0                         1    local
[conda] mkl                       2019.1                      144  
[conda] mkl-include               2019.1                      144  
[conda] nomkl                     3.0                           0  
[conda] torch                     1.2.0a0+afb7a16          pypi_0    pypi
[conda] torchtext                 0.4.0                    pypi_0    pypi
[conda] torchvision               0.3.0a0                  pypi_0    pypi

cc @ezyang @gchanan @zou3519 @suo

**Comment by soumith** [comment] 2019-10-14 22:15
this looks like a good repro and a fix that would likely get a lot of long-tail "serving" perf unblocked. cc: @wanchaol @suo

**Comment by CoderHam** [comment] 2020-01-14 20:13
Has there been any progress on this?

**Comment by suo** [comment] 2020-04-21 18:31
looking into this, marking as high priority so we track it appropriately

**Comment by ngimel** [comment] 2020-08-12 03:56
Bump, looks like other users are also hitting this issue.

**Comment by kommons** [comment] 2021-04-26 18:47
@suo Has there been any progress on this?

**Comment by suo** [comment] 2021-04-26 20:01
Hm, I thought our profiling executor should be smarter about sharing profiling and optimization info between threads. @gmagogsfm, @Krovatkin, @ZolotukhinM any commentary on this?

**Comment by Krovatkin** [comment] 2021-04-26 20:45
@suo we should, AFAIK. The profiling information is associated with a model (or rather with the GraphExecutor instance of the forward method of the model). It shouldn't matter which thread a model is run on as long as it has been warmed up. However, if we start an unprofiled/unwarmed model on N threads, N-Y (where Y is the number of profiling runs) profiling runs will be wasted and then the threads will probably be blocked on one thread that will compile the optimized version.
I'll try to take a look to see if this is what happens here.

**Comment by mabdullahrafique** [comment] 2022-01-11 07:58
Any progress on this ??
We are facing the same issue. Multiple instances of same model is not running efficiently in parallel but process sequentially which is a big overhead.

**Comment by ermlickw** [comment] 2022-03-15 21:40
@suo  @Krovatkin I am also interested in the status of this. Thanks.

**Comment by saad039** [comment] 2022-04-01 04:20
I am facing the same issue but ran into something that's very strange. 

On a VM with an **Nvidia T4 GPU**, deploying multiple instances of the same model causes the inferencing time to increase linearly with the number of instances. 

Contrarily, deploying multiple instances on an **A100** GPU results in **no** pessimization at all. A100 comes up MIG(Multiple Instance GPU) technology that allows slicing the entire GPU in up to 7 slices and provides isolation at the hardware level. But It must be enabled explicitly. Despite it not being enabled on my server, I am still able to keep multiple instances on the GPU and their inferencing time is not affected at all. 

I don't have an explanation for this but I'll love to have one. 

**Specs:**
Driver Version: 495.29.05
CUDA Version: 11.5 
OS: Ubuntu 20.04.4 LTS x86_64
Kernel: 5.13.0-1021-gcp

**Comment by josephykwang** [comment] 2022-06-01 15:45
We see increases in P95 and P99 latency when we increase the GPU instance count from 2 to 8 and 12.

instance count		P95 latency
8         		                +0.9ms	        
12			                +5.9ms

**Comment by ptrblck** [comment] 2022-06-06 21:55
The original code snippet does neither synchronize the device before starting and stopping the timers, nor does it use enough warmup iteration (which could be visible via a slower first iteration).
An updated code snippet (adapted from @zasdfgbnm with added warmup iterations) can be found here:
```
#include <torch/script.h>

#include <pthread.h>
#include <unistd.h>
#include <chrono>
#include <iostream>

#include <cuda_runtime.h>

struct inferStruct {
  at::Tensor output_;
  torch::jit::script::Module module_;
  std::vector<torch::jit::IValue> inputs_;
};

// Run model 5 times
void*
NForwardPass(void* run)
{
  // Model loaded in main thread
  torch::Device device_ = torch::Device(torch::kCUDA, 0);
  std::string model_path = "resnet50_libtorch.pt";
  torch::jit::script::Module module1 = torch::jit::load(model_path, device_);
  std::vector<torch::jit::IValue> inputs_(1);
  inputs_[0] = torch::zeros({1, 3, 224, 224}).to(device_);
  // pre-warm model
  at::Tensor output = module1.forward(inputs_).toTensor();

  inferStruct run1;
  pthread_t thread_id1;  //, thread_id2;

  run1.module_ = module1;
  run1.inputs_ = inputs_;

  auto run_tmp = &run1;
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();

  for (int i = 0; i < 5; i++) {
    cudaDeviceSynchronize();
    auto t1 = std::chrono::high_resolution_clock::now();
    run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
    cudaDeviceSynchronize();
    auto t2 = std::chrono::high_resolution_clock::now();
    auto duration =
        std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
    std::cout << duration / 1000.0
              << " ms to run model in process thread (NForwardPass)"
              << std::endl;
  }
}

// Run model 1 time
void*
ForwardPass(void* run)
{
  // Model loaded in main thread
  torch::Device device_ = torch::Device(torch::kCUDA, 0);
  std::string model_path = "resnet50_libtorch.pt";
  torch::jit::script::Module module1 = torch::jit::load(model_path, device_);
  std::vector<torch::jit::IValue> inputs_(1);
  inputs_[0] = torch::zeros({1, 3, 224, 224}).to(device_);
  // pre-warm model
  at::Tensor output = module1.forward(inputs_).toTensor();

  inferStruct run1;
  pthread_t thread_id1;  //, thread_id2;

  run1.module_ = module1;
  run1.inputs_ = inputs_;

  auto run_tmp = &run1;
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();

  cudaDeviceSynchronize();
  auto t1 = std::chrono::high_resolution_clock::now();
  run_tmp->output_ = run_tmp->module_.forward(run_tmp->inputs_).toTensor();
  cudaDeviceSynchronize();
  auto t2 = std::chrono::high_resolution_clock::now();
  auto duration =
      std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
  std::cout << duration / 1000.0
            << " ms to run model in process thread (ForwardPass)" << std::endl;
}

int
main()
{
  // Model loaded in main thread
  torch::Device device_ = torch::Device(torch::kCUDA, 0);
  std::string model_path = "resnet50_libtorch.pt";
  torch::jit::script::Module module1 = torch::jit::load(model_path, device_);
  std::vector<torch::jit::IValue> inputs_(1);
  inputs_[0] = torch::zeros({1, 3, 224, 224}).to(device_);
  // pre-warm model
  at::Tensor output = module1.forward(inputs_).toTensor();

  inferStruct run1;
  pthread_t thread_id1;  //, thread_id2;

  run1.module_ = module1;
  run1.inputs_ = inputs_;
  run1.output_ = run1.module_.forward(run1.inputs_).toTensor();
  run1.output_ = run1.module_.forward(run1.inputs_).toTensor();
  run1.output_ = run1.module_.forward(run1.inputs_).toTensor();

  // Run model in main thread N times and report runtime each time
  for (int i = 0; i < 5; i++) {
    cudaDeviceSynchronize();
    auto t1 = std::chrono::high_resolution_clock::now();
    output = module1.forward(inputs_).toTensor();
    cudaDeviceSynchronize();
    auto t2 = std::chrono::high_resolution_clock::now();
    auto duration =
        std::chrono::duration_cast<std::chrono::microseconds>(t2 - t1).count();
    std::cout << duration / 1000.0 << " ms to run model in main thread"
              << std::endl;
  }
  sleep(1);

  // Run N threads and in each run model once and report runtime each time
  std::cout << std::endl;
  for (int i = 0; i < 5; i++) {
    pthread_create(&thread_id1, NULL, ForwardPass, &run1);
    pthread_join(thread_id1, NULL);
  }
  sleep(1);

  // Run 1 thread and in it run the model N and report runtime each time
  std::cout << std::endl;
  pthread_create(&thread_id1, NULL, NForwardPass, &run1);
  pthread_join(thread_id1, NULL);

  return 0;
}
```

Using this code I cannot see any slowdown in all three approaches:
```python
5.62 ms to run model in main thread
5.38 ms to run model in main thread
5.346 ms to run model in main thread
5.355 ms to run model in main thread
5.362 ms to run model in main thread

5.347 ms to run model in process thread (ForwardPass)
5.353 ms to run model in process thread (ForwardPass)
5.208 ms to run model in process thread (ForwardPass)
5.342 ms to run model in process thread (ForwardPass)
5.31 ms to run model in process thread (ForwardPass)

5.359 ms to run model in process thread (NForwardPass)
5.358 ms to run model in process thread (NForwardPass)
5.342 ms to run model in process thread (NForwardPass)
5.376 ms to run model in process thread (NForwardPass)
5.35 ms to run model in process thread (NForwardPass)
```
and get approx. the same speed so cannot reproduce the issue.

**Comment by ptrblck** [comment] 2022-07-20 18:45
I don't think this issue is valid, we should remove the `high priorty` tag, and consider closing it unless we get a proper code snippet to reproduce it.
Btw. using event based profiling also did not show any regression. 

@suo @Krovatkin  What do you think?

**Comment by SeungsuBaek** [comment] 2022-12-05 12:57
Has this issue been resolved?

**Comment by jbschlosser** [comment] 2022-12-05 18:13
Closing as non-reproducible, based on corrected performance testing by @ptrblck above. Please feel free to reopen if you have any new data.

**Closed by jbschlosser** 2022-12-05 18:13 UTC
Labels: high priority, triage review, oncall: jit, triaged
