### ISSUE TITLE
Unable to build from latest master - nccl.h not found

### ISSUE THREAD

**Issue by mfuntowicz** [pytorch/pytorch#13385] opened 2018-10-31 11:25 UTC
Hi, 

The cluster I'm running experiments on just updated CUDA & co so I wanted to recompile Pytorch to match the new dependencies. I'm building with nccl support for c10d, everything goes fine until I reach:

torch/csrc/cuda/nccl.cpp, torch/csrc/cuda/comm.cpp with the following error : 

```
gcc -pthread -B /home/mfuntowi/miniconda3/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/home/mfuntowi/Workspace/cudnn/7.3.1.20_92/cuda/include -I/home/mfuntowi/Workspace/pytorch -I/home/mfuntowi/Workspace/pytorch/torch/lib/tmp_install/include -I/home/mfuntowi/Workspace/pytorch/torch/lib/tmp_install/include/TH -I/home/mfuntowi/Workspace/pytorch/torch/lib/tmp_install/include/THNN -I/home/mfuntowi/Workspace/pytorch/torch/lib/tmp_install/include/ATen -I/home/mfuntowi/Workspace/pytorch/third_party/pybind11/include -I/home/mfuntowi/Workspace/pytorch/torch/csrc -Ibuild/third_party -I/home/mfuntowi/miniconda3/lib/python3.6/site-packages/numpy/core/include -I/home/mfuntowi/Workspace/pytorch/torch/lib/tmp_install/include/THD -I/usr/local/cuda/include -I/home/mfuntowi/Workspace/pytorch/torch/lib/tmp_install/include/THCUNN -Ibuild/nccl/include -I/home/mfuntowi/miniconda3/include/python3.6m -c torch/csrc/cuda/nccl.cpp -o build/temp.linux-x86_64-3.6/torch/csrc/cuda/nccl.o -D_THP_CORE -DONNX_NAMESPACE=onnx_torch -std=c++11 -Wall -Wextra -Wno-strict-overflow -Wno-unused-parameter -Wno-missing-field-initializers -Wno-write-strings -Wno-zero-length-array -Wno-unknown-pragmas -Wno-deprecated-declarations -fno-strict-aliasing -Wno-missing-braces -Wno-stringop-overflow -DUSE_NUMPY -DUSE_DISTRIBUTED -DUSE_C10D -DUSE_CUDA -DCUDA_LIB_PATH=/usr/local/cuda/lib64 -DUSE_NCCL -DUSE_CUDNN
In file included from torch/csrc/cuda/nccl.cpp:1:0:
torch/csrc/cuda/nccl.h:8:18: fatal error: nccl.h: No such file or directory
 #include <nccl.h>
                  ^
compilation terminated.
```

It appears even more strange that I ask to not take into account the system nccl and thus, it should build the one from third_party dependencies ...

I'm building with the following command : 

CUDNN_LIB=/home/mfuntowi/Workspace/cudnn/7.3.1.20_92/cuda/lib64/libcudnn.so CUDNN_INCLUDE_DIR=/home/mfuntowi/Workspace/cudnn/7.3.1.20_92/cuda/include NO_SYSTEM_NCCL=1 TORCH_CUDA_ARCH_LIST="6.0;7.0" python setup.py clean install

Do you have any clue about what might be missing ?

**Comment by soumith** [comment] 2018-10-31 16:12
@mfuntowicz can you please give the full build log (not just the failed part), I'll take a look.

**Comment by mfuntowicz** [comment] 2018-10-31 20:02
Hi @soumith,

Thanks for having a look.
Here is the full log attached :).

[pytorch_build.txt](https://github.com/pytorch/pytorch/files/2536202/pytorch_build.txt)

**Comment by anderspapitto** [comment] 2018-10-31 23:04
@mfuntowicz I'm looking into this. However the build system has been changing a lot recently, and I don't fully trust `setup.py clean` - could you try another build with a `git clean -fdx` first to make sure there's not any garbage leftover?

**Comment by mfuntowicz** [comment] 2018-11-01 09:51
@anderspapitto I just launched another build, running git clean -fdx before and it crashed again with the same error.

Here are the output for both the git clean and python setup.py install:

[pytorch_build.txt](https://github.com/pytorch/pytorch/files/2537993/pytorch_build.txt)
[git_clean.txt](https://github.com/pytorch/pytorch/files/2537994/git_clean.txt)

Morgan

**Comment by mfuntowicz** [comment] 2018-11-06 00:59
Some news on my side, I've been able to compile PyTorch by manually cloning NCCL and specifying NCCL_ROOT_DIR from the command line.

Let me know if you need more details.

**Comment by suo** [comment] 2018-11-21 05:03
@anderspapitto this is also happening on my devfair, on master. 
I ran `git clean -xfd` and `ccache -C`.
Build command: `NO_CAFFE2_OPS=1 NO_DISTRIBUTED=1 DEBUG=1 python setup.py build develop`
[Build output](https://gist.github.com/suo/f2b8e0f553c0fee1ffd1da3e704091d5).

**Comment by suo** [comment] 2018-11-21 05:12
Interestingly, issuing `DEBUG=1 python setup.py build develop` worked correctly.

**Comment by mfuntowicz** [comment] 2018-11-21 08:20
On my side the side is with NO_DISTRIBUTED=1. Disabling things related to THD seems to not being carried correctly to some dependencies and thus, some files are missing.

I'm compiling on CentOS servers/Fedora Workstation.

**Comment by anderspapitto** [comment] 2018-11-21 18:52
I'm not able to reproduce this so far, with all different combinations of USE_SYSTEM_NCCL={0,1} and USE_DISTRIBUTED={0,1}

**Comment by suo** [comment] 2018-11-27 20:41
@anderspapitto I patched in that PR, ran `git clean -xfd`, then ran: 
```
NO_CAFFE2_OPS=1 NO_DISTRIBUTED=1 DEBUG=1 python setup.py build develop
```
Still had the same problem. If it would be helpful to log into my devgpu to take a look at things just ping me on workplace.

**Comment by anderspapitto** [comment] 2018-11-28 02:05
fixed by the linked PR. Please reopen if there are further issues

**Closed by anderspapitto** 2018-11-28 02:05 UTC

**Comment by alessiosavi** [comment] 2019-08-24 07:30
You can download the **_NCCL_** library from here https://developer.nvidia.com/nccl

You have to be registered on developer.nvidia.com
