### ISSUE TITLE
THE C++ FRONTEND Example Can not run correctly

### ISSUE THREAD

**Issue by DeepCrazy9** [pytorch/pytorch#65388] opened 2021-09-21 02:19 UTC
Hi, I have spend 2 days trying to figure out why but still can't, it would be really appreciate if you can help.

Windows 10
VS Code
VS Studio

I have installed every necessary parts and set correctly, and I can successfully run libtorch + OpenCV examples, and other examples, but even I copied the example code on this page, it can not run correctly.
[The C++ Frontend — PyTorch master documentation](https://pytorch.org/cppdocs/frontend.html)

In Windows terminal, there are no error in ```cmake``` and no error during ```make```. However, after I excute ```./main```, and waiting for some time, it stopped without hints.
I added some ```std::cout << "Flag 1" << std::endl``` in the example code, and I found the program can not complete this step.
```
// Create a multi-threaded data loader for the MNIST dataset.

  auto data_loader = torch::data::make_data_loader(

      torch::data::datasets::MNIST("C:/Users/J Chen/Program/c-cpp/torchtest1/MNIST_Data/").map(

          torch::data::transforms::Stack<>()),

      /*batch_size=*/64);
```
Which may suggested that the ```MNIST``` can not read the ```MNIST datasets```. (I have tried uncompressed dataset or compressed dataset. I write a Python program to read the same dataset and it goes well.)

Then, in order to figure the error out, I changed into VS Studio, and it give an error as following screenshot.
![4f4cb8fb8a08f0fdfc01fdff61a9859fd1a2e3c2](https://user-images.githubusercontent.com/59865122/134101980-c09ac73b-ff26-474e-9798-f967f5b87fdc.png)

Then, I also trying to use the new example code here
[libtorch-mnist/mnist.cpp at master · TonyzBi/libtorch-mnist · GitHub](https://github.com/TonyzBi/libtorch-mnist/blob/master/mnist.cpp)

But it has two errors,
```
register_module("conv2_drop", conv2_drop);
torch::nn::FeatureDropout conv2_drop;
```
Said the ```FeatureDropout``` is not in ```torch::nn``` anymore.

I have searched the current libtorch API, and found 
```
torch::nn::functional::dropout
```
But the function ```torch::nn::functional::dropout is not a type nameC/C++(757)```
so it is different with the new example code usage.

Really hope someone can help me on this.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @brianjo @mruberry @yf225 @glaringlee @SsnL @VitalyFedyunin @ejguan @NivekT @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by ezyang** [comment] 2021-09-22 16:24
To help narrow down if this is a Windows specific problem, are you able to successfully run the example on Linux?

**Comment by DeepCrazy9** [comment] 2021-09-24 10:47
> To help narrow down if this is a Windows specific problem, are you able to successfully run the example on Linux?

Hi, appreciate for your help.

I have tested other examples such as libtorch + openCV on my Windows environment, and they are working well.
So I think my settings are ok?

But I didn't try the Linux yet, I will try to test them later.

**Comment by DeepCrazy9** [comment] 2021-09-26 07:07
> To help narrow down if this is a Windows specific problem, are you able to successfully run the example on Linux?

Hi ezyang, sorry for late reply, I have tested the same example code at here https://pytorch.org/cppdocs/frontend.html
in CentOS Stream 8.

And it also can not read the MNIST file and has following error.
![image](https://user-images.githubusercontent.com/59865122/134797434-03e9e785-4d28-4a02-8e1d-580bf42392be.png)

I have download the MNIST dataset from the official site and extract them in the ./data folder. (With .gz file and unbyte file) but still can not run the example code.

Appreciate if you can bring some new advices.

**Comment by ezyang** [comment] 2021-09-27 14:22
Seems like the tutorials code doesn't work. Upgrading priority

**Comment by malfet** [comment] 2021-10-04 20:43
Removing `module: windows` as this seems like a generic issue: docs contains ancient code snippet and points to a wrong repo

**Comment by malfet** [comment] 2021-10-04 21:28
Ok, crash is reproducible with something as trivial as 
```
  torch::nn::Linear model(3, 4);
  torch::save(model, "model.pt");
```
And does not reproduce if compiled against PyTorch-1.9.1

**Comment by malfet** [comment] 2021-10-04 22:43
Actually, besides updating link to the full sample I don't see any other problem with the code. I.e. after downloading mnist dataset and unpacking it into `data` folder, current sample works as expected

**Comment by malfet** [comment] 2022-07-27 16:18
Removing high-priority, but keeping the Windows label, as it could not be trivially reproduced on Linux/Mac

**Comment by Blackhex** [comment] 2022-11-08 11:16
I've expeerienced very similar crash (but with completely different reprocase) when running Debug version of PyTorch on Release version of Python. Can we confirm or decline that this is the same case on this issue as well?

**Comment by IgorAherne** [comment] 2022-12-08 11:57
> > Actually, besides updating link to the full sample I don't see any other problem with the code. I.e. after downloading mnist dataset and unpacking it into `data` folder, current sample works as expected
> 
> Thank you for your help, however, I tested the updated code here.[(https://github.com/pytorch/examples/blob/master/cpp/mnist/mnist.cpp)]
> 
> And on Visual Studio on Windows, still have error like this. ![image](https://user-images.githubusercontent.com/59865122/136650845-97fa9da1-8b4a-4f81-aaaf-ecf7356281ba.png)
> 
> Could you please figure it our...

....I'm getting exactly the same behavior :(
https://github.com/pytorch/pytorch/issues/90462#issue-1484436791

**Comment by Blackhex** [comment] 2022-12-08 12:08
@IgorAherne Can you be more specific on your setup or environment? According to the screenshot you are running the Debug version of the sample. Can you confirm or decline that all your dependencies linked to that sample executable, especially the PyTorch libraries, are compiled in Debug mode as well?

**Comment by IgorAherne** [comment] 2022-12-08 16:32
@Blackhex I am running Visual studio, the Configuration is 'Debug' and the platform is shown as 'Active(x64)'. 
Grabbed the libtorch yesterday, from https://pytorch.org/get-started/locally/
Stable (1.13.0), Windows, C++, Cuda 11.7 

I unpacked the downloaded libtorch archive, then in Visual studio project (project settings), I specified the C++ --> General --> Additional include directories to be:
```
C:\src\libtorch\include\
C:\src\libtorch\include\torch\csrc\api\include\
```
In the Linker->Input I've specified the following libs:  
```
torch.lib
torch_cuda.lib
c10.lib
c10_cuda.lib
torch_cuda_cpp.lib
torch_cpu.lib
caffe2_nvrtc.lib
```

And in the Post-build events I've specified: 
`xcopy /y "C:\src\libtorch\lib\*.dll" "C:\_myDrive\repos\harvest\x64\Debug\"`
Which copies all the dlls into the folder with my executable, after the build is complete.

Visual studio is 17.2.5

It would be awesome if Libtorch allowed to download Debug verison of the libraries, I am not very advanced in building stuff from source :(

**Comment by IgorAherne** [comment] 2022-12-08 17:33
@Blackhex Yep, all I needed to do was to get the Debug version instead of Release version and use it instead. 
The issue is no longer appearing.

**Comment by cristianPanaite** [comment] 2023-01-18 08:09
Considering that this issue has a solution (it was just a a mismatch between the Debug and Release versions) we are going to close it.

**Closed** 2023-01-18 08:10 UTC
Labels: module: windows, module: docs, module: cpp, module: dataloader, triaged
