### ISSUE TITLE
torch/csrc/distributed/c10d/Types.hpp: No such file or directory

### ISSUE THREAD

**Issue by jingxu10** [pytorch/pytorch#87173] opened 2022-10-18 05:38 UTC
### 🐛 Describe the bug

`Types.hpp` and `Store.hpp` are missing from `${CONDA_PREFIX}/lib/python3.8/site-packages/torch/include/torch/csrc/distributed/c10d/`, but `Types.hpp` is included in [`ProcessGroup.hpp`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/ProcessGroup.hpp#L13).
![image](https://user-images.githubusercontent.com/25193121/196344232-a0cd4589-f6fc-414c-a8d5-e5db07509850.png)

Error message:
```
In file included from /workspace/dl/pytorch/srcs/ipex/cpu/frameworks.ai.pytorch.torch-ccl/src/ProcessGroupCCL.hpp:41,
                 from /workspace/dl/pytorch/srcs/ipex/cpu/frameworks.ai.pytorch.torch-ccl/src/ccl_comm_collector.h:37,
                 from /workspace/dl/pytorch/srcs/ipex/cpu/frameworks.ai.pytorch.torch-ccl/src/ccl_comm_collector.cpp:4:
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/include/c10d/ProcessGroup.hpp:13:10: fatal error: torch/csrc/distributed/c10d/Types.hpp: No such file or directory
   13 | #include <torch/csrc/distributed/c10d/Types.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

`Types.hpp` and `Store.hpp` are not in directory `torch/csrc/distributed/c10d`, but in `torch/include/c10d`
```
# find $CONDA_PREFIX/lib/python3.8/site-packages/torch -name Types.hpp
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/include/c10d/Types.hpp
# find $CONDA_PREFIX/lib/python3.8/site-packages/torch -name Store.hpp
/root/miniconda3/envs/py38/lib/python3.8/site-packages/torch/include/c10d/Store.hpp
```

### Versions

Installed with command `pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cpu/torch_test.html`

```
PyTorch version: 1.13.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 11.2.1 20220127 (Red Hat 11.2.1-9)
Clang version: 3.4.2 (tags/RELEASE_34/dot2-final)
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.8.13 (default, Mar 28 2022, 11:38:47)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.15.0-50-generic-x86_64-with-glibc2.17
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.23.4
[pip3] torch==1.13.0+cpu
[pip3] torchaudio==0.13.0+cpu
[pip3] torchvision==0.14.0+cpu
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     1.13.0+cpu               pypi_0    pypi
[conda] torchaudio                0.13.0+cpu               pypi_0    pypi
[conda] torchvision               0.14.0+cpu               pypi_0    pypi
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @malfet @seemethere

**Comment by malfet** [comment] 2022-10-18 13:46
Thank you for reporting. It should not be the case.
cc: @minsii

**Comment by minsii** [comment] 2022-10-18 21:02
I tried a fresh installation with `pip3 install --pre torch torchvision torchaudio -f https://download.pytorch.org/whl/test/cpu/torch_test.html`. 

Output of pip3 install shows 
```
Successfully installed pillow-9.2.0 torch-1.13.0+cpu torchaudio-0.13.0+cpu torchvision-0.14.0+cpu
```

All c10d headers are still under `~/anaconda3/envs/my_pytorch/lib/python3.9/site-packages/torch/include/c10d`, except exception.h.  It looks like the image is still created with an older version of pytorch, before https://github.com/pytorch/pytorch/pull/86933. Is there a way to check if PR86933 has been applied?

**Comment by minsii** [comment] 2022-10-18 21:49
I also manually unpack [torch-1.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl](https://download.pytorch.org/whl/test/cpu/torch-1.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl), same as above, the all headers are under the old path. Likely these wheels are built before #86933 

Then I tried build wheel with the latest 1.13.0 branch. All headers are moved properly.  
```
$ git show --stat
commit 894bad72c9dfb946e9bdfebaf2db41473b3dd4fe (HEAD -> release/1.13, origin/release/1.13)
Author: Bowen Bao <bowbao@microsoft.com>
Date:   Tue Oct 18 11:46:58 2022 -0700

$ python3 setup.py develop
$ python3 setup.py bdist_wheel
```
```
$ wheel unpack dist/torch-1.13.0a0+git894bad7-cp39-cp39-linux_x86_64.whl
$ ls torch-1.13.0a0+git894bad7/torch/include/torch/csrc/distributed/c10d/
Backend.hpp             error.h                logger.hpp           PrefixStore.hpp       ProcessGroupRoundRobin.hpp  reducer.hpp        TCPStore.hpp    UCCUtils.hpp
c10d.h                  exception.h            logging.h            ProcessGroupGloo.hpp  ProcessGroupUCC.hpp         reducer_timer.hpp  TraceUtils.h    UnixSockUtils.hpp
comm.hpp                FileStore.hpp          NCCLUtils.hpp        ProcessGroup.hpp      ProcessGroupWrapper.hpp     sequence_num.hpp   Types.hpp       Utils.hpp
debug.h                 GlooDeviceFactory.hpp  Ops.hpp              ProcessGroupMPI.hpp   PyProcessGroup.hpp          socket.h           UCCForNCCL.hpp  WinSockUtils.hpp
default_comm_hooks.hpp  HashStore.hpp          ParamCommsUtils.hpp  ProcessGroupNCCL.hpp  python_comm_hook.h          Store.hpp          UCCTracing.hpp  Work.hpp
```

**Comment by kwen2501** [comment] 2022-10-18 22:28
Cc @malfet 
Note that the link in question is https://download.pytorch.org/whl/test/cpu/torch_test.html. (the test part in the url)
Do you know which branch this link builds wheels from?
It seems that a build from release/1.13 has correct header file locations per Min's investigation above.

**Comment by kwen2501** [comment] 2022-10-18 22:32
Oh, is it because we only cherry pick the https://github.com/pytorch/pytorch/pull/86933 PR onto the release/1.13 branch?

**Comment by minsii** [comment] 2022-10-18 22:57
Just checked, it was generated by
```
commit 95112ca043c37e38101e629c1f69663e911cc909 (tag: v1.13.0-rc3)
Author: Andrey Talman <atalman@fb.com>
Date:   Fri Oct 7 16:31:40 2022 -0400
```

Before merging https://github.com/pytorch/pytorch/pull/86933

**Comment by jingxu10** [comment] 2022-10-20 06:13
Hi @minsii , @malfet  May I know if you have updated the wheel files with this PR?

**Comment by atalman** [comment] 2022-10-20 20:51
@jingxu10 The new wheel should be generated on Oct 21 PM EST

**Comment by jingxu10** [comment] 2022-10-20 20:54
Thanks.

**Comment by atalman** [comment] 2022-10-21 14:09
@closing this issue since resolved in release. Will revalidate once new RC cut is generated

**Comment by malfet** [comment] 2022-10-24 16:39
Hmm, I can't find any of the headers mentioned in this issue in Oct 21st nightly builds:
```
$ python -c "import torch;print(torch.__version__, torch.__file__)"
1.14.0.dev20221021+cu117 /home/nshulga/miniconda3/envs/py37-torch114-dynamo/lib/python3.7/site-packages/torch/__init__.py
(py37-torch114-dynamo) nshulga@ip-10-200-93-49:~$ find /home/nshulga/miniconda3/envs/py37-torch114-dynamo/lib/python3.7/site-packages/torch -iname c10d -type d|xargs ls
exception.h
```
So I'm not sure what is the expected behaviour there

**Comment by atalman** [comment] 2022-10-24 16:41
Should we revert these 2 commits ? https://github.com/pytorch/pytorch/pull/87602

**Closed** 2022-10-24 19:38 UTC
Labels: oncall: distributed, module: build, triaged, module: regression, module: c10d

**Comment by jingxu10** [comment] 2022-10-24 21:29
Since `torch/csrc/distributed/c10d/Types.hpp` is included in the header file, should `Types.hpp` be in `torch/csrc/distributed/c10d` directory when deployed?
