### ISSUE TITLE
Incompatible Keys need not be returned when missing keys and unexpected keys are Null

### ISSUE THREAD

**Issue by nithinraok** [pytorch/pytorch#21639] opened 2019-06-11 17:13 UTC
## 🚀 Feature

when loading state_dict I'm getting
``` IncompatibleKeys(missing_keys=[], unexpected_keys=[]) ``` message though model is loaded correctly. I feel we can have a conditional case before returning this named tuple when missing keys and unexpected keys are null
## Motivation

I thought it was some error and wasted some time to figure out finally that this wasn't an error at all. I am not sure if this a warning though. 
## Pitch

I feel we can have a conditional case before returning this named tuple when missing keys and unexpected keys are null. If you are fine with this then please let me know, I'll submit at PR. Thanks

**Comment by SsnL** [comment] 2019-06-11 19:03
duplicate of https://github.com/pytorch/pytorch/issues/20128

**Closed by SsnL** 2019-06-11 19:03 UTC
