### ISSUE TITLE
[inductor][cpu] NotImplementedError: The original model code forces the use of CUDA.

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#116239] opened 2023-12-21 02:35 UTC
### 🐛 Describe the bug

Some models meet accuracy crash in 2023-12-13:
```
cpu  eval  timm_efficientdet                  
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 3586, in run
    ) = runner.load_model(
  File "benchmarks/dynamo/torchbench.py", line 435, in load_model
    benchmark = benchmark_cls(
  File "/workspace/benchmark/torchbenchmark/util/model.py", line 24, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/workspace/benchmark/torchbenchmark/models/timm_efficientdet/__init__.py", line 55, in __init__
    raise NotImplementedError("The original model code forces the use of CUDA.")
NotImplementedError: The original model code forces the use of CUDA.

```

### Versions

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>f13a21c</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>6518fa9</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>e12d200</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info(nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git0155706</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+526ec93</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.2.0a0+6518fa9</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)

bash inductor_single_run.sh multiple inference accuracy torchbench timm_efficientdet float32 first static default

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/acdd06e00ff2085180993495ef08a6f5d6a5fdf9
[torchbench-timm_efficientdet-inference-float32-static-default-accuracy-multiple-crash_guilty_commit.log](https://github.com/pytorch/pytorch/files/13734445/torchbench-timm_efficientdet-inference-float32-static-default-accuracy-multiple-crash_guilty_commit.log)
cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @WeizhuoZhang-intel @chuanqi129

**Comment by chuanqi129** [comment] 2023-12-21 02:44
Hi @zxd1997066, according to the bisect log, seems this model can't be run in each commit. So I think it maybe a environment issue or torchbench specific issue (may caused by dependency change of this model), please double check it in local.

**Comment by chuanqi129** [comment] 2023-12-25 08:56
It's not a new crash issue, it caused by this model still not support cpu device by default https://github.com/chuanqi129/benchmark/blob/xpu/torchbenchmark/models/timm_efficientdet/__init__.py#L55. Let's close this one and try to enable it on cpu device in Torchbench

**Closed by chuanqi129** 2023-12-25 08:56 UTC
Labels: triaged, oncall: pt2, oncall: cpu inductor
