### ISSUE TITLE
  what():  another list already started (listInsert at /pytorch/torch/csrc/jit/interpreter.cpp:563)

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#21823] opened 2019-06-15 15:59 UTC
What does this happen:

  what():  another list already started (listInsert at /pytorch/torch/csrc/jit/interpreter.cpp:563)

My situation is that I am training on pytorch and meanwhile try to inference on a libtorch demo. Does they can not co-exist?

**Comment by zdevito** [comment] 2019-06-17 16:37
Hi, is it possible to post an example that causes this issue, or to post the entire error message? Thanks!

**Comment by jinfagang** [comment] 2019-06-18 01:51
@zdevito  Same traced pt model, same c++ program, different machine on of them got this error. I can not even debug for why. I will udpate an error message when logging on to problem machine.

**Comment by suo** [comment] 2019-12-16 17:41
Going to close this out as there has not been much activity and the issue is not reproducible. Feel free to reopen if you want us to take another look!

**Closed by suo** 2019-12-16 17:41 UTC
Labels: jit, needs reproduction, triaged
