### ISSUE TITLE
[inductor][cpu]DebertaV2ForQuestionAnswering AMP static/dynamic shape multiple thread default wrapper regression 

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#122390] opened 2024-03-21 07:03 UTC
### 🐛 Describe the bug

<p>new_perf_regression in 2024-03-18</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>suite</th>
      <th>name</th>
      <th>thread</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
   <tr>
      <td>huggingface</td>
      <td>DebertaV2ForQuestionAnswering</td>
      <td>multiple</td>
      <td>1</td>
      <td>2.290567</td>
      <td>0.068807462</td>
      <td>0.157608101810954</td>
      <td>27.15124</td>
      <td>1</td>
      <td>2.609835</td>
      <td>0.059629811</td>
      <td>0.15562396779118498</td>
      <td>27.519487</td>
      <td>0.88</td>
      <td>0.99</td>
      <td>0.87</td>
      <td>1.01</td>
    </tr>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>target_branch</th>
      <th>target_commit</th>
      <th>refer_branch</th>
      <th>refer_commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>main</td>
      <td>d6015d42</td>
      <td>main</td>
      <td>1ef0a39e</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>main</td>
      <td>5bc7f7f97760d2d485621f9f30d0316e1f2440c6</td>
      <td>main</td>
      <td>41286f1505ffb214d386d72e4b72ebd680a4a475</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>main</td>
      <td>0.18.0a0+0325175</td>
      <td>main</td>
      <td>0.18.0a0+2c127da</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
      <td>main</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
      <td>main</td>
      <td>2.2.0a0+87aeb55</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
      <td>main</td>
      <td>0.7.1a0+0790338</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>main</td>
      <td>nightly</td>
      <td>main</td>
      <td>nightly</td>
    </tr>
  </tbody>
</table>

Repro:
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/main/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance huggingface DebertaV2ForQuestionAnswering amp first static/dynamic
[huggingface-DebertaV2ForQuestionAnswering-inference-amp-static-default-multiple-performance-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/14690312/huggingface-DebertaV2ForQuestionAnswering-inference-amp-static-default-multiple-performance-drop_guilty_commit.log)

Suspected guilty commit: https://github.com/pytorch/pytorch/commit/7084528eb9551fd0450b05a001195452041e899b
cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang @WeizhuoZhang-intel @chuanqi129

**Comment by zxd1997066** [comment] 2024-03-22 07:21
7084528
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance huggingface DebertaV2ForQuestionAnswering amp first static
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,DebertaV2ForQuestionAnswering,1,1.475397,87.109111,20.878096,0.932468,1284.147200,1377.148928,1088,1,0,0,0,0

2b06098
/workspace/pytorch# bash inductor_single_run.sh multiple inference performance huggingface DebertaV2ForQuestionAnswering amp first static
dev,name,batch_size,speedup,abs_latency,compilation_latency,compression_ratio,eager_peak_mem,dynamo_peak_mem,calls_captured,unique_graphs,graph_breaks,unique_graph_breaks,autograd_captures,autograd_compiles
cpu,DebertaV2ForQuestionAnswering,1,2.406015,54.670975,19.501593,0.937395,1284.246323,1370.016154,1088,1,0,0,0,0

**Comment by chuanqi129** [comment] 2024-03-28 06:54
Hi @anijain2305, by bisect search, it looks like the PR #122005 introduced this performance regression issue, could you please help to double check it?

**Comment by IvanKobzarev** [comment] 2024-09-14 21:55
Hi @anijain2305 , doing issue scrapping , is this issue still relevant or can be closed?

**Comment by anijain2305** [comment] 2024-10-01 16:29
This should be fixed on main. I don't recall but there was a refactor from WilliamWen which should have helped here.

**Closed by anijain2305** 2024-10-01 16:29 UTC
Labels: oncall: pt2, oncall: cpu inductor
