### ISSUE TITLE
[dataloader] segmentation fault when returning empty tensors and using a multi-worker dataloader

### ISSUE THREAD

**Issue by aldopareja** [pytorch/pytorch#15928] opened 2019-01-10 18:13 UTC
## 🐛 Bug

when using more than 0 workers in the dataloader the following code gives an error

## To Reproduce

```
import torch
from torch.utils.data import Dataset, DataLoader

class dataset(Dataset):
    def __len__(self):
        return 10

    def __getitem__(self,idx):
        return self.get_empty_tensor()

    def get_empty_tensor(self):
        adj = torch.ones([0,2],dtype = torch.long)
        vals = torch.ones([0], dtype = torch.long)
        return {'idx': adj.t(),'vals': vals}

if __name__ ==  '__main__':
    data = dataset()
    dl = DataLoader(data,shuffle = True, num_workers = 1)
    for t in dl:
        print(t)
```

## Expected behavior

when num_workers = 0 it prints:

> {'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}
{'idx': tensor([], size=(1, 2, 0), dtype=torch.int64), 'vals': tensor([], size=(1, 0), dtype=torch.int64)}

when num_workers > 0 it gives `segmentation fault: 11`

## Environment

```
PyTorch version: 1.0.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Mac OSX 10.14.2
GCC version: Could not collect
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy (1.15.4)
[pip] torch (1.0.0)
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.3                      1  
[conda] mkl_fft                   1.0.6            py37hb8a8100_0  
[conda] mkl_random                1.0.1            py37h5d10147_1  
[conda] pytorch                   1.0.0                   py3.7_1    pytorch
```

**Comment by fmassa** [comment] 2019-01-14 13:59
I believe this has been fixed on master, as I can't reproduce this with `1.0.0.dev20181224`.
Can you try installing a nightly and seeing if this fix your problem?

**Closed** 2019-01-14 14:00 UTC
Labels: needs-reproduction
