### ISSUE TITLE
[Inductor] [CPU] Torchbench model hf_Reformer performance regression > 10% on 2023-03-15 nightly release

### ISSUE THREAD

**Issue by ESI-SYD** [pytorch/pytorch#96997] opened 2023-03-17 03:16 UTC
### 🐛 Describe the bug

Compare with the benchmarks_update based on 2023-03-12, there is a performance regression on torchbench model **hf_Reformer** on [TorchInductor CPU Performance Dashboard](https://github.com/pytorch/pytorch/issues/93531#issuecomment-1473049949) on 2023-03-15 as bellow:

|  2023-03-15  |   |     |   |  update-2023-03-12  |   |     |   |  Result Comp  |     |   |
|  ----  | ----  |  ----  | ----  |  ----  | ----  |  ----  | ----  | ----  |  ----  | ----  |
| batch_size  | speedup | inductor  | eager | batch_size  | speedup | inductor  | eager | speedup ratio | eager ratio  | inductor ratio |
|1	|0.9103	|0.4018883	|0.365838919	|1	|1.0173	|0.3548287	|0.360967237	|0.89	|0.99	|0.88

2023-03-15 nightly release SW information:
SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[4f7cbd0](https://github.com/pytorch/pytorch/commit/4f7cbd0)|[c6a82e4](https://github.com/pytorch/pytorch/commit/c6a82e4)
Torchbench|/|[83a316df](https://github.com/pytorch/benchmark/commit/83a316df)
torchaudio|[375e751](https://github.com/pytorch/audio/commit/375e751)|[a8f4e97](https://github.com/pytorch/audio/commit/a8f4e97)
torchtext|[9749082](https://github.com/pytorch/text/commit/9749082)| [46e7eef](https://github.com/pytorch/text/commit/46e7eef)
torchvision|[8d15ca7](https://github.com/pytorch/vision/commit/8d15ca7)|[98c5815](https://github.com/pytorch/vision/commit/98c5815)
torchdata|[b3048d5](https://github.com/pytorch/data/commit/b3048d5)|[f1283eb](https://github.com/pytorch/data/commit/f1283eb)
dynamo_benchmarks|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|/

update 2023-03-12 nightly release SW information:
SW	| Nightly commit	| Master/Main commit
-- | -- | --
Pytorch|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|[82d3d05](https://github.com/pytorch/pytorch/commit/82d3d05)
Torchbench|/|[83a316df](https://github.com/pytorch/benchmark/commit/83a316df)
torchaudio|[375e751](https://github.com/pytorch/audio/commit/375e751)|[a8f4e97](https://github.com/pytorch/audio/commit/a8f4e97)
torchtext|[9749082](https://github.com/pytorch/text/commit/9749082)| [46e7eef](https://github.com/pytorch/text/commit/46e7eef)
torchvision|[8d15ca7](https://github.com/pytorch/vision/commit/8d15ca7)|[98c5815](https://github.com/pytorch/vision/commit/98c5815)
torchdata|[b3048d5](https://github.com/pytorch/data/commit/b3048d5)|[f1283eb](https://github.com/pytorch/data/commit/f1283eb)
dynamo_benchmarks|[1238ae3](https://github.com/pytorch/pytorch/commit/1238ae3)|/

Graph dump by cosim:
2023-03-15:
[graph.txt](https://github.com/pytorch/pytorch/files/10997500/graph.txt)

update-2023-03-12:
[graph.txt](https://github.com/pytorch/pytorch/files/10997505/graph.txt)

Minified repro:

```bash
python -m torch.backends.xeon.run_cpu --core_list 0 --ncores_per_instance 1 benchmarks/dynamo/torchbench.py --performance --float32 -dcpu -n50 --inductor  --no-skip --dashboard --only hf_Reformer  --cold_start_latency --batch_size 1 --threads 1

```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire

**Comment by chunyuan-w** [comment] 2023-03-30 15:36
Caused by https://github.com/pytorch/pytorch/pull/96492

**Comment by williamwen42** [comment] 2023-11-22 23:29
Closing - assuming regression has been fixed. Reopen if this is not the case.

**Closed by williamwen42** 2023-11-22 23:29 UTC
Labels: triaged, oncall: pt2, module: inductor, module: cpu inductor
