### ISSUE TITLE
MultiHeadAttention docs are unnecessarily confusing.

### ISSUE THREAD

**Issue by OliverFM** [pytorch/pytorch#68702] opened 2021-11-21 12:11 UTC
## 📚 Documentation

[The docs](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention) for the `forward` function give the dimensions of `key`, `query` and `value` as `E_k, E_q, E_v` respectively which is really confusing, since, if I am not mistaken they should all be the same.

The [transformer paper](https://arxiv.org/pdf/1706.03762.pdf), which is referenced in the docs, follows this convention, as far as I can tell. 
Moreover, this seems to be implemented in torch.
[we pass `embed_dim`](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/modules/activation.py#L1003) to the functional implementation to [check that it matches `query_dim`](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/functional.py#L5120) and [check that `key` and `value` have the same shape](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/functional.py#L5133).

We also [comment](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/functional.py#L4994) the code, saying that the dimension of the query and key are expected to be the same, and, indeed, if they aren't the matrix multiplication will fail.

## Proposed fix.

Replace `E_k, E_q, E_v` with `E, E, E`. We may also want to add explicit checking that all three are the same in a clearer way.

e.g.
```python
assert query.shape[-1] == key.shape[-1], f"query has embedding dimension {query.shape[-1]} which does n't match key embedding dimension: {key.shape[-1]}"
assert key.shape == value.shape
```

I'd be happy to make the changes, if they would be approved!

**Comment by OliverFM** [comment] 2021-11-21 12:20
Another point: in the original paper, the keys and querys have the same shape. Whereas the torch implementation leaves the keys and values having the same shape. Is this intentional? Perhaps it should be documented too.

**Comment by jbschlosser** [comment] 2021-11-22 17:59
Hey @OliverFM, thanks for the report! Hopefully the comments below will help clear up some of the confusion.

> [The docs](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html#torch.nn.MultiheadAttention) for the `forward` function give the dimensions of `key`, `query` and `value` as `E_k, E_q, E_v` respectively which is really confusing, since, if I am not mistaken they should all be the same.

We support different embedding dimensions for query, key, and value through the optional use of `kdim` / `vdim` & providing separate projection weights. See #60831 which resulted in the doc updates.

> [we pass `embed_dim`](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/modules/activation.py#L1003) to the functional implementation to [check that it matches `query_dim`](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/functional.py#L5120) and [check that `key` and `value` have the same shape](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/functional.py#L5133).

Note that the other branch explicitly allows for key and value to have different embedding dimensions:

https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/functional.py#L5128-L5133

> We also [comment](https://github.com/pytorch/pytorch/blob/c7ecf1498d961415006c3710ac8d99166fe5d634/torch/nn/functional.py#L4994) the code, saying that the dimension of the query and key are expected to be the same, and, indeed, if they aren't the matrix multiplication will fail.

The dimension of query and key embeddings are only required to be the same **post-projection** during scaled dot-product attention computation.

Closing as intended behavior + docs, but please feel free to reopen if you feel that the above rationale is insufficient.

**Closed by jbschlosser** 2021-11-22 17:59 UTC

**Comment by OliverFM** [comment] 2021-11-23 05:16
I see, that makes sense, thank!
