### ISSUE TITLE
[RFC] Unified quantization backend for x86 CPU platforms

### ISSUE THREAD

**Issue by Xia-Weiwen** [pytorch/pytorch#83888] opened 2022-08-23 04:07 UTC
## Description
Add a unified quantization backend ‘X86’ for x86 CPU platforms. Make it the default PyTorch quantization backend for x86 in place of FBGEMM.
It is implemented by auto selection between FBGEMM and ONEDNN during weight prepacking.

## Motivation
The ONEDNN quantization backend takes advantage of features of the latest Intel® CPU products. And it supports more fused ops. It has shown better performance over FBGEMM in many (but not all) cases.
From an API design point of view, it would not be user-friendly if we expose both FBGEMM and ONEDNN backends to end users. In that case, we propose a unified quantization backend named ‘X86’ to combine the goodness of both backends while keep API simple.
In the frontend, users will be using the x86 backend by default for x86 platforms. And in the backend, we decide for them about which kernel to run and hide the details. The selection between different kernels is automatically done during weight prepacking with static information.
Thus, the X86 backend can replace FBGEMM and offer better performance.

## Design philosophy
Auto kernel selection between FBGEMM and ONEDNN by simple heuristics without runtime info.
- For non-fused ops, choose ONEDNN if it's always better. Otherwise, use simple heuristics to make selection.
- For fused ops, from FX quantization, the x86 QEngine suggests the quant fusion patterns statically as how current fbgemm backend or onednn backend does now. The fusion patterns might include those from onednn backend that fbgemm backend doesn't support. If fused op (e.g. conv-add-relu) is always better on ONEDNN than non-fused conv + add-relu on FBGEMM, fused op is exposed. Otherwise, we expose conv + add-relu.
- During the runtime, x86 QEngine implements the fused ops by choosing the right kernels, fbgemm or onednn. The decision can be made statically (e.g., conv+add+relu is only available on onednn, then onednn kernel is used.)
- For implementation, the X86 backend will follow the `QEngine` and `backend_config` API.

## Proposed Heuristics
Rules for auto selection between FBGEMM and ONEDNN:
- On platforms without VNNI (e.g., Skylake), FBGEMM is always used.
- On platforms with VNNI (e.g., Cascade lake, Ice lake, and future platforms):
  - For linear, FBGEMM is always used.
  - For convolution, FBGEMM is used for depth-wise convolution whose groups > 100; otherwise, ONEDNN is used.
- Currently, X86 supports the same fusion patterns as FBGEMM.

For the unified backend, selection occurs during weight prepacking when ‘quantized::conv/linear_prepack’ is called. The prepack function will check hardware info (with or without VNNI) and op parameters and return a proper prepacked weight object accordingly.
For example, for linear or on platforms without VNNI, FBGEMM’s prepacked weight is always returned; and for convolution with groups=1, ONEDNN’s prepacked weight is returned. Then at runtime, it will automatically call corresponding kernels.

We have done implementation and run common models for benchmarking. The following table lists speedup ratio of throughputs of unified x86 backend vs. Pure FBGEMM:
| Device\Ratio Geomean | 1 core/instance | 2 cores/instance | 4 cores/instance | 1 socket/instance |
|-|-|-|-|-|
| Intel(R) Xeon(R) Cascade Lake | 1.701 | 1.821 | 1.921 | 1.513 |
| Intel(R) Xeon(R) Ice Lake | 1.767 | 1.810 | 2.042 | 1.346 |

(Table updated on Feb 21, 2023)

*Note*:
- Run multi-instance; using Jemalloc, IOMP
- Ratio > 1 means unified backend is better
- For details, please refer to the attached sheets
[unified_qengine_poc_performance_bechmark.xlsx](https://github.com/pytorch/pytorch/files/9399202/unified_qengine_poc_performance_bechmark.xlsx)
Performance data updated on Jan 20, 2023:
[int8_oob_x86_vs_fbgemm_20230119.xlsx](https://github.com/pytorch/pytorch/files/10463469/int8_oob_x86_vs_fbgemm_20230119.xlsx)

Performance data updated on Feb 5, 2023:
[int8_benchmark_x86_vs_fbgemm_20230205.xlsx](https://github.com/pytorch/pytorch/files/10636697/int8_benchmark_x86_vs_fbgemm_20230205.xlsx)
(Using PyTorch nightly build on Feb 4, 2023, installed by pip)

Performance data updated on Feb 21, 2023:
[int8_benchmark_x86_vs_fbgemm_20230221.xlsx](https://github.com/pytorch/pytorch/files/10793668/int8_benchmark_x86_vs_fbgemm_20230221.xlsx)
(Using PyTorch nightly build on Feb 20, 2023, installed by pip)

**About qconfig**
For compatibility, the new backend will use `reduce_range=True` to align with FBGEMM.
However, for accuracy, we hope to change it to `reduce_range=False` in the future.

**Accuracy**
We have run torchvision models to compare accuracy. Results show that FBGEMM and X86 backends give the same accuracy. For details, please see the worksheet:
[torchvision_accuracy_comparison_fbgemm_vs_x86.xlsx](https://github.com/pytorch/pytorch/files/9598114/torchvision_accuracy_comparison_fbgemm_vs_x86.xlsx)

## Plans
**Original plans**
> The implementation is still pending on some optimizations of the ONEDNN backend, which are not available yet in stock PyTorch. Thus the numbers we showed above cannot be reproduced by stock PyTorch right now.
In that case, we plan to take the steps below to finally unify x86 qengines:
> 1. Update ideep in stock PyTorch. Many optimizations are based on the ideep update.
> 2. Optimize performance of ONEDNN backend. PR(s) will be submitted after ideep's updates.
> 3. Prepare PR of the unified qengine
> 4. Publicize it to end users
>
> We hope all these changes will be landed before 1.13 release.

**Current status**
- Implementation is finished and PRs are landed
- This feature is expected to be publicized on PyTorch 2.0 release.
- We are continuing working on improvement of onednn backend. The dispatching heuristics and supported fusion patterns might change in the future.

### Alternatives

N/A

### Additional context

Example of implementing conv_prepack for unified X86 quantization backend.
```c++
template <int kSpatialDim = 2>
class QConvPackWeightInt8 final {
 public:
    // Public API to do conv prepack
 private:
  static c10::intrusive_ptr<ConvPackedParamsBase<kSpatialDim>> _run(
      Tensor weight,
      c10::optional<Tensor> bias,
      torch::List<int64_t> stride,
      torch::List<int64_t> padding,
      torch::List<int64_t> output_padding,
      torch::List<int64_t> dilation,
      int64_t groups,
      bool transpose) {
    auto& ctx = at::globalContext();
    if (ctx.qEngine() == at::QEngine::X86) {
#ifdef USE_FBGEMM
      if (no_vnni || groups > 100) {
        return PackedConvWeight<kSpatialDim>::prepack(
            weight, bias, stride, padding, output_padding, dilation, groups, transpose);
      }
#endif
#if AT_MKLDNN_ENABLED()
      return PackedConvWeightsOnednn<kSpatialDim>::prepack(
          weight, bias, stride, padding, output_padding, dilation, groups, transpose);
#endif
    }


#ifdef USE_PYTORCH_QNNPACK
    if (ctx.qEngine() == at::QEngine::QNNPACK) {
      return PackedConvWeightsQnnp<kSpatialDim>::prepack(
          weight, bias, stride, padding, output_padding, dilation, groups,
          transpose);
    }
#endif

    TORCH_CHECK(
        false,
        "Didn't find engine for operation quantized::conv2d_prepack ",
        toString(ctx.qEngine()));
  }
};
```
The prepacking function returns an object of prepacked weight which belongs to either FBGEMM or ONEDNN. The call to `prepacked_weight->run` will automatically run into the correct kernel.

Original code can be found here for reference:
https://github.com/pytorch/pytorch/blob/b29a074882a2194d61f1cd7ccf939618d8384d08/aten/src/ATen/native/quantized/cpu/qconv_prepack.cpp#L482

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @leslie-fang-intel

**Comment by Xia-Weiwen** [comment] 2022-08-23 07:13
Hi @jerryzh168, please review. Thanks!

**Comment by jerryzh168** [comment] 2022-08-23 16:38
looks good to me, will post in internal groups to have more people to review the doc.

One question I have is can we post the numbers comparing the performance of unified quantization backend and the previous fbgemm backend?

**Comment by supriyar** [comment] 2022-08-23 18:26
@Xia-Weiwen are there any results comparing the numerics of the model with the unified backend vs fbgemm only backend? This would be useful to access any internal impact on numerics for customers who are currently using fbgemm in production.

**Comment by supriyar** [comment] 2022-08-23 18:30
Another question is around the `reduce_range` setting https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/qconfig.py#L238. This is set to `true` for fbgemm backend before the observers are run. If the decision to use fbgemm vs onednn is made during the prepack function, what is the plan to ensure we set the `reduce_range` field correctly before calibration?

**Comment by vkuzo** [comment] 2022-08-23 20:39
> The selection between different kernels is automatically done at quantization time with static information.

The machine where quantization is done is not always the same machine which runs inference.  Thoughts on how this could be handled?  Are we sure we have enough data at quantization time to do the backend selection?  Do we need to relax this constraint?

**Comment by jerryzh168** [comment] 2022-08-23 21:19
> > The selection between different kernels is automatically done at quantization time with static information.
> 
> The machine where quantization is done is not always the same machine which runs inference. Thoughts on how this could be handled? Are we sure we have enough data at quantization time to do the backend selection? Do we need to relax this constraint?

I think the selection is done every time we prepacks the weight, so we will select backend again when we load the model from disk before inference, does that work in real use cases?

**Comment by Xia-Weiwen** [comment] 2022-08-24 07:02
> 



> @Xia-Weiwen are there any results comparing the numerics of the model with the unified backend vs fbgemm only backend? This would be useful to access any internal impact on numerics for customers who are currently using fbgemm in production.

Thanks for the question. We will provide some results later.

**Comment by Xia-Weiwen** [comment] 2022-08-24 07:03
> Another question is around the `reduce_range` setting https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/qconfig.py#L238. This is set to `true` for fbgemm backend before the observers are run. If the decision to use fbgemm vs onednn is made during the prepack function, what is the plan to ensure we set the `reduce_range` field correctly before calibration?

Good question. We will figure out a solution.

**Comment by jgong5** [comment] 2022-08-24 09:26
> > 
> 
> > @Xia-Weiwen are there any results comparing the numerics of the model with the unified backend vs fbgemm only backend? This would be useful to access any internal impact on numerics for customers who are currently using fbgemm in production.
> 
> Thanks for the question. We will provide some results later.

@supriyar FBGEMM and oneDNN backends should have the same numerics by design. In PyTorch UT, oneDNN backend also apply the same result checking logic as FBGEMM. Meanwhile, we can provide more end-to-end model accuracy comparison like @Xia-Weiwen mentioned.

> Another question is around the `reduce_range` setting https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/qconfig.py#L238. This is set to `true` for fbgemm backend before the observers are run. If the decision to use fbgemm vs onednn is made during the prepack function, what is the plan to ensure we set the `reduce_range` field correctly before calibration?

@supriyar The `reduce_range` setting is irrelevant to the decision whether fbgemm or onednn kernel is selected based on the proposed heuristics. Note that the heuristics only chooses the kernel, not the qengine configuration. Given a `reduce_range` setting, the fbgemm or onednn kernel should bring the same result on a given CPU. 


> > > The selection between different kernels is automatically done at quantization time with static information.
> > 
> > 
> > The machine where quantization is done is not always the same machine which runs inference. Thoughts on how this could be handled? Are we sure we have enough data at quantization time to do the backend selection? Do we need to relax this constraint?
> 
> I think the selection is done every time we prepacks the weight, so we will select backend again when we load the model from disk before inference, does that work in real use cases?

@jerryzh168 @vkuzo @supriyar A related question is what is the default `reduce_range` to use. `reduce_range` should be `True` for CPUs without VNNI support. Current FBGEMM qengine has `reduce_range` as `True` by default. I guess that is a conservative choice for out-of-the-box experience considering not all CPUs supporting VNNI and also different CPUs might be used in calibration and deployment? With that, and also considering the backward compatibility, we plan to set `True` value with the unified backend by default too. Does that sound good to you?
The tradeoff is that users are not able to get best accuracy by default, especially considering the fact that CPUs with VNNI are becoming mainstream. An alternative solution is to set `reduce_range` to `False` by default in this new unified backend while recommend users to explicitly set to `True` or use FBGEMM qengine on CPUs without VNNI. Comments?

**Comment by vkuzo** [comment] 2022-08-24 17:18
> > > The selection between different kernels is automatically done at quantization time with static information.
> > 
> > 
> > The machine where quantization is done is not always the same machine which runs inference. Thoughts on how this could be handled? Are we sure we have enough data at quantization time to do the backend selection? Do we need to relax this constraint?
> 
> I think the selection is done every time we prepacks the weight, so we will select backend again when we load the model from disk before inference, does that work in real use cases?

Should we modify the language of this RFC to make this clearer?  "done at quantization time" sounds like "done during prepare/convert calls", which is different from "done during weight prepacking".

**Comment by vkuzo** [comment] 2022-08-24 17:19
> A related question is what is the default reduce_range to use.

IMO, it's better for the default to be numerically correct and potentially slow compared to potentially numerically incorrect and fast.  This would point to keeping `reduce_range=True` as default, and documenting the behavior clearly.  Thoughts?

**Comment by jerryzh168** [comment] 2022-08-24 17:25
> > > 
> > 
> > 
> > > @Xia-Weiwen are there any results comparing the numerics of the model with the unified backend vs fbgemm only backend? This would be useful to access any internal impact on numerics for customers who are currently using fbgemm in production.
> > 
> > 
> > Thanks for the question. We will provide some results later.
> 
> @supriyar FBGEMM and oneDNN backends should have the same numerics by design. In PyTorch UT, oneDNN backend also apply the same result checking logic as FBGEMM. Meanwhile, we can provide more end-to-end model accuracy comparison like @Xia-Weiwen mentioned.
> 
> > Another question is around the `reduce_range` setting https://github.com/pytorch/pytorch/blob/master/torch/ao/quantization/qconfig.py#L238. This is set to `true` for fbgemm backend before the observers are run. If the decision to use fbgemm vs onednn is made during the prepack function, what is the plan to ensure we set the `reduce_range` field correctly before calibration?
> 
> @supriyar The `reduce_range` setting is irrelevant to the decision whether fbgemm or onednn kernel is selected based on the proposed heuristics. Note that the heuristics only chooses the kernel, not the qengine configuration. Given a `reduce_range` setting, the fbgemm or onednn kernel should bring the same result on a given CPU.
> 
> > > > The selection between different kernels is automatically done at quantization time with static information.
> > > 
> > > 
> > > The machine where quantization is done is not always the same machine which runs inference. Thoughts on how this could be handled? Are we sure we have enough data at quantization time to do the backend selection? Do we need to relax this constraint?
> > 
> > 
> > I think the selection is done every time we prepacks the weight, so we will select backend again when we load the model from disk before inference, does that work in real use cases?
> 
> @jerryzh168 @vkuzo @supriyar A related question is what is the default `reduce_range` to use. `reduce_range` should be `True` for CPUs without VNNI support. Current FBGEMM qengine has `reduce_range` as `True` by default. I guess that is a conservative choice for out-of-the-box experience considering not all CPUs supporting VNNI and also different CPUs might be used in calibration and deployment? With that, and also considering the backward compatibility, we plan to set `True` value with the unified backend by default too. Does that sound good to you? The tradeoff is that users are not able to get best accuracy by default, especially considering the fact that CPUs with VNNI are becoming mainstream. An alternative solution is to set `reduce_range` to `False` by default in this new unified backend while recommend users to explicitly set to `True` or use FBGEMM qengine on CPUs without VNNI. Comments?

yeah agree, I think the default should be True so that it is always correct, and we can provide documentations for users who knows that they are using CPUs with VNNI support and want to have a slightly better accuracy.

**Comment by jgong5** [comment] 2022-08-24 22:06
> > A related question is what is the default reduce_range to use.
> 
> IMO, it's better for the default to be numerically correct and potentially slow compared to potentially numerically incorrect and fast. This would point to keeping `reduce_range=True` as default, and documenting the behavior clearly. Thoughts?
> yeah agree, I think the default should be True so that it is always correct, and we can provide documentations for users who knows that they are using CPUs with VNNI support and want to have a slightly better accuracy.

Thanks for the suggestions. Make sense to me. BTW, I guess @vkuzo wanted to say "potentially worse accurate" right? `reduce_range` doesn't impact the inference speed. :)

**Comment by Xia-Weiwen** [comment] 2022-08-25 00:43
> > > > The selection between different kernels is automatically done at quantization time with static information.
> > > 
> > > 
> > > The machine where quantization is done is not always the same machine which runs inference. Thoughts on how this could be handled? Are we sure we have enough data at quantization time to do the backend selection? Do we need to relax this constraint?
> > 
> > 
> > I think the selection is done every time we prepacks the weight, so we will select backend again when we load the model from disk before inference, does that work in real use cases?
> 
> Should we modify the language of this RFC to make this clearer? "done at quantization time" sounds like "done during prepare/convert calls", which is different from "done during weight prepacking".

Thanks for the suggestion. Updated.

**Comment by vkuzo** [comment] 2022-08-25 15:23
> > > A related question is what is the default reduce_range to use.
> > 
> > 
> > IMO, it's better for the default to be numerically correct and potentially slow compared to potentially numerically incorrect and fast. This would point to keeping `reduce_range=True` as default, and documenting the behavior clearly. Thoughts?
> > yeah agree, I think the default should be True so that it is always correct, and we can provide documentations for users who knows that they are using CPUs with VNNI support and want to have a slightly better accuracy.
> 
> Thanks for the suggestions. Make sense to me. BTW, I guess @vkuzo wanted to say "potentially worse accurate" right? `reduce_range` doesn't impact the inference speed. :)

Yes, you are right, my mistake.

**Comment by Xia-Weiwen** [comment] 2022-09-19 10:31
> > 
> 
> > @Xia-Weiwen are there any results comparing the numerics of the model with the unified backend vs fbgemm only backend? This would be useful to access any internal impact on numerics for customers who are currently using fbgemm in production.
> 
> Thanks for the question. We will provide some results later.

Hi @supriyar We have run torchvision models with FBGEMM and X86 for accuracy comparison. Results show that they have the same accuracy. For details, please refer to the attached worksheet:
[torchvision_accuracy_comparison_fbgemm_vs_x86.xlsx](https://github.com/pytorch/pytorch/files/9598114/torchvision_accuracy_comparison_fbgemm_vs_x86.xlsx)

**Comment by fzhao3** [comment] 2023-01-13 09:17
This is being proposed as a feature for PT2.0, and here is the full list of PRs for this feature.
#84329 
#85461 
#86794 
#88799 
#74137
#69820
#84470 
#86876 
#86794
#91235 

https://github.com/pytorch/tutorials/pull/2081

**Comment by andrewor14** [comment] 2023-08-10 19:50
@jerryzh168 @Xia-Weiwen What is the status of this issue? Is it done?

**Comment by jgong5** [comment] 2023-08-14 04:34
> @jerryzh168 @Xia-Weiwen What is the status of this issue? Is it done?

Yes, it is completed as a feature of 2.0.

**Comment by andrewor14** [comment] 2023-08-16 16:13
Ok, I'm closing this then. Feel free to reopen if you think this is a mistake. Thanks.

**Closed by andrewor14** 2023-08-16 16:13 UTC
Labels: oncall: quantization, triaged
