### ISSUE TITLE
`size()` type for `size` argument of `randint()` works against the doc

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130880] opened 2024-07-17 00:04 UTC
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.randint.html) of `randint()` doesn't say [size()](https://pytorch.org/docs/stable/generated/torch.Tensor.size.html) type for `size` argument as shown below:

> - size ([tuple](https://docs.python.org/3/library/stdtypes.html#tuple)) – a tuple defining the shape of the output tensor.

But, `size()` type for `size` argument of `randint()` works against the doc as shown below:

```python
import torch

my_tensor = torch.tensor([8, 3, 6])

my_tensor.size()
# torch.Size([3])

torch.randint(high=10, size=my_tensor.size())
# tensor([4, 1, 8])
```

**Comment by malfet** [comment] 2024-07-17 06:17
Please stop filing separate issue for the same problem! One can mention all ops that violate the standard in one issue
Closing as duplicate of https://github.com/pytorch/pytorch/issues/130872

**Closed by malfet** 2024-07-17 06:17 UTC
