### ISSUE TITLE
Linux CUDA workflows failing at Install NVIDIA runtime step

### ISSUE THREAD

**Issue by janeyx99** [pytorch/pytorch#83928] opened 2022-08-23 18:25 UTC
## Current Status
*MITIGATED*

## Error looks like
*Provide some way users can tell that this SEV is causing their issue.*
Your workflow fails with logs that look like:
```
WARNING: The nvidia-drm module will not be installed. As a result, DRM-KMS will not function with this installation of the NVIDIA driver.

/home/ec2-user/actions-runner/_work/_actions/nick-fields/retry/71062288b76e2b6214ebde0e673ce0de1755740a/dist/index.js:1049
            throw err;
            ^

Error: kill EPERM
    at process.kill (internal/process/per_thread.js:199:13)
    at killPid (/home/ec2-user/actions-runner/_work/_actions/nick-fields/retry/71062288b76e2b6214ebde0e673ce0de1755740a/dist/index.js:1059:17)
    at /home/ec2-user/actions-runner/_work/_actions/nick-fields/retry/71062288b76e2b6214ebde0e673ce0de1755740a/dist/index.js:1036:21
    at Array.forEach (<anonymous>)
    at /home/ec2-user/actions-runner/_work/_actions/nick-fields/retry/71062288b76e2b6214ebde0e673ce0de1755740a/dist/index.js:1034:23
    at Array.forEach (<anonymous>)
    at killAll (/home/ec2-user/actions-runner/_work/_actions/nick-fields/retry/71062288b76e2b6214ebde0e673ce0de1755740a/dist/index.js:1033:27)
    at /home/ec2-user/actions-runner/_work/_actions/nick-fields/retry/71062288b76e2b6214ebde0e673ce0de1755740a/dist/index.js:1024:13
    at ChildProcess.onClose (/home/ec2-user/actions-runner/_work/_actions/nick-fields/retry/71062288b76e2b6214ebde0e673ce0de1755740a/dist/index.js:1080:17)
    at ChildProcess.emit (events.js:314:20) {
  errno: 'EPERM',
  code: 'EPERM',
  syscall: 'kill'
}
```
https://github.com/pytorch/pytorch/runs/7975726013?check_suite_focus=true

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*
- 8/22 5:53pm incident began
- 8/22 11:20pm detected by Jane looking at the miniHUD
- 8/23 9:00 pm root caused as…
- 8/23 9:10 pm mitigated by…
- 8/23 10: am closed by…

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment] 2022-08-23 18:39
Looks like a base AMI update happened recently, which updated kernel version from 4.14.252 to 5.10.130

**Comment by seemethere** [comment] 2022-08-23 18:52
Root cause analysis:

1. We (@seemethere and @jeanschmidt) enabled the canary autoscaling app to produce runners for all repositories this morning to test the roll out for organization runners
2. Discovered that the AMI used in canary roll out is different than production rollout (remedied in this [commit](https://github.com/fairinternal/pytorch-gha-infra/commit/2faa7805d1a60e5e1e6962b4d347f7524c6ca2e3))
3. Fix is rolled out but may take a while for the current node pool to drain

**Comment by seemethere** [comment] 2022-08-23 19:03
Batch terminating the instances using the following commands:

```
❯ aws ec2 describe-instances --filters Name=tag:Environment,Values=gh-ci-canary Name=instance-type,Values=g3.4xlarge --query 'Reservations[].Instances[].[InstanceId]' --output=text > instance_ids_to_terminate
❯ for instance_id in $(cat instance_ids_to_terminate); do (set -x; aws ec2 terminate-instances --instance-ids "${instance_id}"); done
```

**Comment by seemethere** [comment] 2022-08-23 21:03
Going to close this since the issue has been mitigated

**Closed by seemethere** 2022-08-23 21:03 UTC
Labels: ci: sev

**Comment by ZainRizvi** [comment] 2022-09-06 20:14
@seemethere , similar to https://github.com/pytorch/pytorch/issues/84089, can RelEng add some alerting to detect these kind of failures faster?

**Comment by ZainRizvi** [comment] 2022-09-06 20:22
Potential follow ups:
- Do we even need to install the cuda driver? AMI probably installs something recent enough. To do by @huydhn 
- Move to AMI Linux 4 (from AMI linux 2). Xenial couldn't parse kernel version > rev 256
- If not, should we build out a custom AMI for linux that has cuda preinstalled?
