### ISSUE TITLE
Guards elimination for unused variables

### ISSUE THREAD

**Issue by AIisnotai-available** [pytorch/pytorch#111194] opened 2023-10-13 09:06 UTC
### 🚀 The feature, motivation and pitch

For example 
`def f(m : Module, a : Tensor):
       return m.para + a
`
when this function compiled by dynamo, with config.guard_nn_modules true, totally three guards for m, m.para and a respectively will be generated. 

In fact, m itself is not used directly which incurs a NN_MODULE guard. If this function is called with different modules and the para field within them are of the same shape, perhaps the guard for m could be eliminated for less check and better hit chance.

Consider two implementation approaches:
1. Modify bytecode handlers in InstructionTranslatorBase and call_function/method in different VariableTracker subclasses to do some liveness analysis for variable guard and do elimination.
2. Perform analysis directly on compiled fx graphs and collect live variable guards, then use this collection as the base to generate GuardedCode.

Any suggestions? Thanks!

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng @wconstab

**Comment by anijain2305** [comment] 2024-06-10 23:21
Most of the guards on usused variables are eliminated with https://github.com/pytorch/pytorch/pull/111306

This issue points towards guard on the `nn.Module`. Today these guards are necessary because Dynamo does not inline through inbuilt nn modules. With the upcoming work on `inlining_inbuilt_nn_modules`, those guards will be eliminated as well.

So, closing this PR for now. The inlining work is a duplicate of this PR - https://github.com/pytorch/pytorch/issues/97909

**Closed by anijain2305** 2024-06-10 23:21 UTC
Labels: triaged, oncall: pt2, module: dynamo
