### ISSUE TITLE
Returning Variables sharing storage with other Variables that require grad is not supported in Python functions. Please submit a feature request if you hit this error.

### ISSUE THREAD

**Issue by Hui-Xie** [pytorch/pytorch#32625] opened 2020-01-25 22:32 UTC
## 🚀 Feature
In an inheriting torch.autograd.Function, I implemented static methods forward and backward.
In above forward method, I used ctx to save some tensors, e.g. ctx.tensor1 = tensor1 for using in the above backward.  It works good in training stage for forward and backward processes.

Now in the reference stage, under the context "with torch.no_grad():", I called the  above static forward method, it will save ctx.tensor1 = tensor1, but in this context, it does not need backward. 

Therefore it arises "RuntimeError: Returning Variables sharing storage with other Variables that require grad is not supported in Python functions. Please submit a feature request if you hit this error."

## Motivation
We need to an explicit method to  tell autograd engine not to call the customized backward method.

## Alternatives
Alternatives to bypass this error:
1  in the forward of the inheriting autograd.Function, use torch.is_grad_enabled() to judge whether to save ctx for backward: True, save ctx.tensor1; False, no save ctx.tensor;
2  in the backward of the  the inheriting autograd.Function, if torch.is_gad_enable() false, directly return all Nones as gradients.

I think  there is a better method to bypass this error.  

I put this issue here, hoping to get experts' opinions.  

code reference at line 110-120 of https://github.com/Hui-Xie/DeepLearningSeg/blob/master/OCTMultiSurfaces/network/OCTPrimalDualIPM.py

cc @ezyang @SsnL @albanD @zou3519 @gqchen

**Comment by zhangguanheng66** [comment] 2020-01-27 15:56
any ideas? @albanD

**Comment by albanD** [comment] 2020-01-27 17:02
Hi,

@Hui-Xie As mentioned in your comment [here](https://github.com/Hui-Xie/DeepLearningSeg/blob/b568215616214e43def1693e5e65af92bff9c776/OCTMultiSurfaces/network/OCTPrimalDualIPM.py#L103), `save_for_backward()` must be used for input/ouputs. In your case `Q` is an input I think.

Also I cannot reproduce this with a simple example. Do you have a failing example that we can easily run to share?
```pythonimport torch
from torch import autograd

class Foo(autograd.Function):
    @staticmethod
    def forward(ctx, x):
        # Inputs/output should not be saved in ctx
        # But use ctx.save_for_backward()
        ctx.save_for_backward(x)
        x1 = x.clone()
        ctx.x1 = x1
        x2 = x1.clone()
        return x2

    @staticmethod
    def backward(ctx, gx):
        print(ctx.x1)
        print(ctx.saved_tensors)
        return gx.clone()

inp = torch.rand(10, requires_grad=True)

Foo.apply(inp).sum().backward()
print("Ok")

with torch.no_grad():
    Foo.apply(inp).sum()
print("Ok")
```

**Comment by Hui-Xie** [comment] 2020-01-27 20:14
Thank you very much, @albanD . Your posts have helped me a lot in my using pytorch process.

Maybe I previous self-analysis is not correct. 
Basing on your example code, I made a simple example code below which can reproduce the problem " Foo.apply(inp).sum()
RuntimeError: Returning Variables sharing storage with other Variables that require grad is not supported in Python functions. Please submit a feature request if you hit this error."

I further analyze that issue is about backward, it is about sharing storage of a tensor.

`
import torch
from torch import autograd

class Foo(autograd.Function):
    @staticmethod
    def forward(ctx, x):
        s = x[0:10]
        # s =x.clone()[0:10] # if we  use this line to replace its above line, error disappears
        ctx.save_for_backward(x,s)
        return s

    @staticmethod
    def backward(ctx, gx):
        x,s = ctx.saved_tensors
        return s.clone()

inp = torch.rand(100, requires_grad=True)

with torch.no_grad():
    Foo.apply(inp).sum()
print("Ok")
'

**Comment by ezyang** [comment] 2020-01-28 03:00
@Hui-Xie what version of PyTorch are you running with

**Comment by Hui-Xie** [comment] 2020-01-28 15:45
to @ezyang: 
My torch version: 1.3.1

Conda information for pytorch package:
Name                     Version                   Build  Channel
_pytorch_select           0.2                       gpu_0  
pytorch                      1.3.1           cuda100py37h53c1284_0  
pytorch-gpu               1.3.1                         0  


My Linux OS version:
            NAME="Ubuntu"
            VERSION="18.04.3 LTS (Bionic Beaver)"

Python version: Python 3.7.6 (default, Jan  8 2020, 19:59:22)
 
Thanks.

**Comment by albanD** [comment] 2020-01-28 16:35
The reason why this happens is because `s` here requires gradient because it is a view of `x` that requires gradients. So `s` is marked as requirering gradient as well.

We should not do this check for views anymore in the `autograd.Function` output post-processing.

**Comment by gchanan** [comment] 2020-02-20 21:46
We should remove the error: ""RuntimeError: Returning Variables sharing storage with other Variables that require grad is not supported in Python functions. Please submit a feature request if you hit this error." from autograd.Function output post-processing. (custom_function.cpp)

As @albanD says above, this used to be a problem because we didn't track views in the forward of custom Functions (because only Variables tracked views, and forward was run with tensors).

**Comment by Hui-Xie** [comment] 2020-02-20 23:02
Yes. @gchanan is correct.  We need to remove this error hint in CPP code . 
At least "Please submit a feature request if you hit this error" is not proper in the original CPP code, which only makes users confuse.

I think it is time to close this issue.

**Comment by Hui-Xie** [comment] 2020-02-20 23:03
Thank you all.

**Comment by albanD** [comment] 2020-02-21 16:41
Let's keep this open to track the removal of the error message.
Hopefully we should have that done quite soon.

**Comment by Hui-Xie** [comment] 2020-02-21 16:53
Yes. It is good to trace to this issue is fixed. 
Good.

**Closed** 2020-03-10 15:00 UTC
Labels: actionable, fixathon, module: autograd, triaged
