### ISSUE TITLE
Crash when dividing Variable(LongTensor) by a float

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#5694] opened 2018-03-11 00:54 UTC
```python
import torch

torch.autograd.Variable(torch.LongTensor([18])) / 0.0625
# Floating point exception (core dumped)

torch.LongTensor([18]) / 0.0625
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File ".../lib/python2.7/site-packages/torch/tensor.py", line 294, in __div__
#    return self.div(other)
#TypeError: div received an invalid combination of arguments - got (float), but expected one of:
# * (int value)
#      didn't match because some of the arguments have invalid types: (float)
# * (torch.LongTensor other)
#      didn't match because some of the arguments have invalid types: (float)
```
at `0.4.0a0+b608ea9`;  related to https://github.com/pytorch/pytorch/issues/327 and maybe https://github.com/pytorch/pytorch/issues/5411 

Probably the cause is that in the variable case, it casts the divisor as Long and it triggers integer division by zero. But why only in the variable case?

Didn't test it after the tensor+variable merge, since don't want to migrate to vNext before ECCV deadline :)

**Comment by apaszke** [comment] 2018-03-11 15:24
In master it looks like in the first case you posted (floating point exception).

**Comment by li-roy** [comment] 2018-03-12 05:53
This is probably the same issue as #5008 (the float is being cast into a long). I'll take a look into it.

**Comment by vadimkantorov** [comment] 2018-05-21 19:56
Another confusing instance of this: `torch.tensor(10) * 0.1 == 0.0`

**Comment by t-vi** [comment] 2018-07-27 07:01
Contrary to what the title suggests, the crash resulting from the types, it is about division by 0 for long.

To for the scalar case, this is easily caught by checking == 0 in div_DEFAULT (and possibly others) and made into an exception (or should it be a warning as in NumPy?).
For the tensor case, that also has this, this is not all that efficient, so we might need to have a signal handler, have that set a flag and check that flag upon exit.

So two questions
- What should be the escalation level? (Exception or Warning)
- Is signal handler + checking OK? Or is there a completely other way to do it?

I think the question of whether float * Int Tensor should be float or int is separate.

**Comment by vadimkantorov** [comment] 2018-07-27 08:42
I agree there are two problems: divbyzero signal handling and implicit type casting.

But the second one is important as well: if implicit casting is supported, it should not lead to such severe type demotion and divbyzero.

**Comment by ailzhang** [comment] 2018-08-14 19:00
For the implicit cast, there are some ongoing work by @colesbury , let's use #6196 to track the progress

**Comment by ailzhang** [comment] 2018-08-14 19:04
The first issue is also caused by implicit type cast (float scalar to int) imo. Closing as duplicate of #6196.

**Closed by ailzhang** 2018-08-14 19:04 UTC
Labels: bug, crash, medium priority
