### ISSUE TITLE
BCELossWithLogits(input) != BCELoss(Sigmoid(input))

### ISSUE THREAD

**Issue by VasLem** [pytorch/pytorch#24933] opened 2019-08-20 21:29 UTC
## 🐛 Bug

I updated today to pytorch 1.2 and tried to train a neural network. While I was getting fine BCELossWithLogits (~1) during training step, the loss would become >1e4 during validation. I went on and tried BCELoss instead, after applying sigmoid to the input.  The loss on the same input and target became much, much smaller . I include the pickle file, as gotten from the following code:

```
class BCELoss(nn.Module, _Logger):
    __name__ = 'bce_loss'

    def __init__(self, with_logits=True, **kwargs):
        super().__init__()
        self.with_logits = with_logits
        if self.with_logits:
            self.bce_loss = torch.nn.BCEWithLogitsLoss(**kwargs)
        else:
            self.bce_loss = torch.nn.BCELoss(**kwargs)

    def forward(self, inputs, targets, logs=None):
        loss = self.bce_loss(inputs, targets)
        self.update_logs(logs, loss)
        return loss


class BCEAndDiceLoss(nn.Module):
    __name__ = 'bce_and_dice_loss'

    def __init__(self, with_logits=True, dice_loss_kwargs={}, bce_kwargs={}, _dice_loss_class=None):
        super().__init__()
        self.with_logits = with_logits
        if _dice_loss_class is None:
            _dice_loss_class = DiceLoss
        self.dice_loss = _dice_loss_class(
            with_logits=self.with_logits, **dice_loss_kwargs)
        self.bce_loss = BCELoss(with_logits=self.with_logits, **bce_kwargs)

    def forward(self, inputs, targets, logs=None, dice_loss_kwargs={}, bce_kwargs={}):
        d_loss = self.dice_loss(inputs, targets, logs=logs, **dice_loss_kwargs)
        b_loss = self.bce_loss(inputs, targets, logs=logs, **bce_kwargs)
        loss = b_loss + d_loss
        if not np.all(loss.cpu().data.numpy() < 1e4):
            import pickle
            with open('error_tensors.pkl', 'wb') as out:
                pickle.dump((inputs.cpu().detach(),
                             targets.cpu().detach(),
                             (b_loss.cpu().detach(),
                              BCELoss(with_logits=False,
                                      **bce_kwargs)(nn.Sigmoid()(inputs), targets).cpu().detach()
                                )), out)
        assert np.all(loss.cpu().data.numpy() < 1e4), (d_loss, BCELoss(
                                                           with_logits=True, **bce_kwargs)(
                                                               inputs, targets),

                                                       BCELoss(
                                                           with_logits=False, **bce_kwargs)(inputs, targets),
                                                       inputs.max(), inputs.min(), inputs.mean(),
                                                       targets.max(), targets.min(), targets.mean())
        return loss
```
The assertion prints:
```
(tensor(0.9884, device='cuda:0'), tensor(105739.7031, device='cuda:0'), tensor(1.8102, device='cuda:0'), tensor(391591.2188, device='cuda:0'), tensor(-2.1709e+08, device='cuda:0'), tensor(-6036326., device='cuda:0'), tensor(1., device='cuda:0'), tensor(0., device='cuda:0'), tensor(0.0093, device='cuda:0'))
```

I also note that the problem was observed only when the operation was performed inside a `with torch.no_grad():` context manager . I guess this might be an overflow error, as the input tensor values have high absolute value, but it still seems weird and I thought I had to report it.

[error_tensors.zip](https://github.com/pytorch/pytorch/files/3522644/error_tensors.zip)

cc @ezyang @gchanan @SsnL @albanD

**Comment by ezyang** [comment] 2019-08-21 10:04
Upgrading priority for some initial investigation. But based on your description, this might just be because `BCELoss(Sigmoid(x))` is just less numerically stable than `BCELossWithlogits`; this is a pretty common thing to happen with some fused operations. Did this work on 1.1 and stop working on 1.2?

**Comment by VasLem** [comment] 2019-08-21 13:06
I have not tested it on 1.1, but I will if needed. If what you describe is the case, then shouldnt' `BCELossWithLogits` give out lower magnitude values that `BCELoss(Sigmoid(x))`, as it is more numerically stable? Even so, is it not weird that this behavior is not displayed during training, only during validation, where the context manager `with torch.no_grad()` is active?
I will test it on 1.1 later today or tomorrow, I am currently running a resource hungry experiment that does not allow me to perform any further inverstigation.

**Comment by ezyang** [comment] 2019-08-21 20:51
I am not familiar with these operations so you may very well be right.

**Comment by kurtamohler** [comment] 2019-12-09 20:01
@izdeby, do you still want to work on this? If you want, I can take over it.

**Comment by izdeby** [comment] 2019-12-09 20:51
Hey, @kurtamohler, yeah sure, feel free to take it.

**Comment by kurtamohler** [comment] 2019-12-10 21:04
It looks like this issue only shows up on CPUs. If I enable CUDA, it goes away. I wrote a script to find out how `BCELoss(Sigmoid())`'s error acts with various input sizes. This script generates random 2-D target tensors and uses `target - 0.5` as the output tensor. It calculates the BCE loss between the target and output using both `BCELosWithLogits()` and `BCELoss(Sigmoid())`. For each tensor size, 5 different random inputs are generated and the losses are averaged.

```
import torch
import torch.nn as nn

def compare_bce_sigmoid_vs_logits(device):
  use_grad = False
  sizes = [2**exponent for exponent in range(10, 15)]

  print("tensor_size (x,y): mean_logits_loss, mean_sigmoid_loss, mean_loss_diff")
  print("---------")
  for y in sizes:
    for x in sizes:
      bce_logits_losses = []
      bce_sigmoid_losses = []
      for _ in range(5):
        target = torch.rand(x, y, requires_grad=use_grad, dtype=torch.float32, device=device)
        output = target - 0.5

        bce_logits_losses.append(nn.BCEWithLogitsLoss()(output, target))
        bce_sigmoid_losses.append(nn.BCELoss()(torch.sigmoid(output), target))

      bce_logits_losses = torch.tensor(bce_logits_losses, device=device)
      bce_sigmoid_losses = torch.tensor(bce_sigmoid_losses, device=device)
      loss_diffs = (bce_logits_losses - bce_sigmoid_losses).abs()

      logits_std, logits_mean = torch.std_mean(bce_logits_losses)
      sigmoid_std, sigmoid_mean = torch.std_mean(bce_sigmoid_losses)
      diff_std, diff_mean = torch.std_mean(loss_diffs)

      print('(%6d, %6d): %f +/-%.2e, %f +/-%.2e, %f +/-%.2e' % (
        x, y,
        logits_mean, 2*logits_std,
        sigmoid_mean, 2*sigmoid_std,
        diff_mean, 2*diff_std
      ))

    print()

print('=========')
print('CUDA:')
print('=========')
compare_bce_sigmoid_vs_logits(torch.device('cuda'))
print()
print()
print('=========')
print('CPU:')
print('=========')
compare_bce_sigmoid_vs_logits(torch.device('cpu'))
```

Output:
```
=========
CUDA:
=========
tensor_size (x,y): mean_logits_loss, mean_sigmoid_loss, mean_loss_diff
---------
(  1024,   1024): 0.620168 +/-1.04e-04, 0.620168 +/-1.04e-04, 0.000000 +/-6.53e-08
(  2048,   1024): 0.620205 +/-4.38e-05, 0.620205 +/-4.37e-05, 0.000000 +/-5.33e-08
(  4096,   1024): 0.620165 +/-5.39e-05, 0.620165 +/-5.40e-05, 0.000000 +/-6.53e-08
(  8192,   1024): 0.620157 +/-4.57e-05, 0.620157 +/-4.56e-05, 0.000000 +/-6.53e-08
( 16384,   1024): 0.620162 +/-1.91e-05, 0.620162 +/-1.91e-05, 0.000000 +/-6.53e-08

(  1024,   2048): 0.620169 +/-1.19e-04, 0.620169 +/-1.19e-04, 0.000000 +/-6.53e-08
(  2048,   2048): 0.620155 +/-3.10e-05, 0.620155 +/-3.10e-05, 0.000000 +/-5.33e-08
(  4096,   2048): 0.620168 +/-2.11e-05, 0.620168 +/-2.10e-05, 0.000000 +/-6.53e-08
(  8192,   2048): 0.620169 +/-4.81e-05, 0.620169 +/-4.80e-05, 0.000000 +/-9.97e-08
( 16384,   2048): 0.620164 +/-3.08e-05, 0.620164 +/-3.08e-05, 0.000000 +/-6.53e-08

(  1024,   4096): 0.620179 +/-7.24e-05, 0.620179 +/-7.24e-05, 0.000000 +/-6.53e-08
(  2048,   4096): 0.620172 +/-3.23e-05, 0.620172 +/-3.23e-05, 0.000000 +/-5.33e-08
(  4096,   4096): 0.620167 +/-2.70e-05, 0.620167 +/-2.70e-05, 0.000000 +/-6.53e-08
(  8192,   4096): 0.620162 +/-2.78e-05, 0.620162 +/-2.77e-05, 0.000000 +/-5.33e-08
( 16384,   4096): 0.620165 +/-1.66e-05, 0.620165 +/-1.66e-05, 0.000000 +/-6.53e-08

(  1024,   8192): 0.620158 +/-4.98e-05, 0.620158 +/-4.98e-05, 0.000000 +/-6.53e-08
(  2048,   8192): 0.620168 +/-2.32e-05, 0.620168 +/-2.32e-05, 0.000000 +/-5.33e-08
(  4096,   8192): 0.620165 +/-3.73e-05, 0.620165 +/-3.74e-05, 0.000000 +/-6.53e-08
(  8192,   8192): 0.620167 +/-6.46e-06, 0.620167 +/-6.46e-06, 0.000000 +/-6.53e-08
( 16384,   8192): 0.620170 +/-8.50e-06, 0.620170 +/-8.50e-06, 0.000000 +/-6.53e-08

(  1024,  16384): 0.620162 +/-1.97e-05, 0.620162 +/-1.96e-05, 0.000000 +/-6.53e-08
(  2048,  16384): 0.620162 +/-2.17e-05, 0.620162 +/-2.17e-05, 0.000000 +/-6.53e-08
(  4096,  16384): 0.620168 +/-1.42e-05, 0.620168 +/-1.42e-05, 0.000000 +/-6.53e-08
(  8192,  16384): 0.620165 +/-1.15e-05, 0.620165 +/-1.15e-05, 0.000000 +/-0.00e+00
( 16384,  16384): 0.620167 +/-5.82e-06, 0.620167 +/-5.83e-06, 0.000000 +/-5.33e-08



=========
CPU:
=========
tensor_size (x,y): mean_logits_loss, mean_sigmoid_loss, mean_loss_diff
---------
(  1024,   1024): 0.620124 +/-1.75e-04, 0.620215 +/-1.72e-04, 0.000091 +/-1.65e-05
(  2048,   1024): 0.620164 +/-7.57e-05, 0.619947 +/-9.66e-05, 0.000217 +/-2.77e-05
(  4096,   1024): 0.620181 +/-7.31e-05, 0.622703 +/-1.44e-04, 0.002522 +/-8.01e-05
(  8192,   1024): 0.620164 +/-3.59e-05, 0.602500 +/-4.57e-05, 0.017664 +/-3.72e-05
( 16384,   1024): 0.620175 +/-2.29e-05, 0.596263 +/-5.39e-05, 0.023912 +/-3.82e-05

(  1024,   2048): 0.620184 +/-6.33e-05, 0.619965 +/-6.00e-05, 0.000219 +/-1.84e-05
(  2048,   2048): 0.620140 +/-8.69e-05, 0.622649 +/-6.41e-05, 0.002509 +/-3.99e-05
(  4096,   2048): 0.620159 +/-3.68e-05, 0.602492 +/-6.02e-05, 0.017666 +/-4.22e-05
(  8192,   2048): 0.620161 +/-2.55e-05, 0.596252 +/-3.92e-05, 0.023910 +/-4.74e-05
( 16384,   2048): 0.620175 +/-1.77e-05, 0.500000 +/-0.00e+00, 0.120175 +/-1.77e-05

(  1024,   4096): 0.620139 +/-3.68e-05, 0.622642 +/-9.23e-05, 0.002503 +/-6.62e-05
(  2048,   4096): 0.620158 +/-4.40e-05, 0.602494 +/-4.29e-05, 0.017664 +/-3.54e-05
(  4096,   4096): 0.620168 +/-1.49e-05, 0.596253 +/-9.61e-05, 0.023915 +/-8.80e-05
(  8192,   4096): 0.620174 +/-1.23e-05, 0.500000 +/-0.00e+00, 0.120174 +/-1.23e-05
( 16384,   4096): 0.620141 +/-2.16e-05, 0.250000 +/-0.00e+00, 0.370141 +/-2.16e-05

(  1024,   8192): 0.620145 +/-4.48e-05, 0.602464 +/-4.56e-05, 0.017680 +/-2.83e-05
(  2048,   8192): 0.620160 +/-4.74e-05, 0.596235 +/-7.64e-05, 0.023925 +/-3.56e-05
(  4096,   8192): 0.620162 +/-2.47e-05, 0.500000 +/-0.00e+00, 0.120162 +/-2.47e-05
(  8192,   8192): 0.620140 +/-1.33e-05, 0.250000 +/-0.00e+00, 0.370140 +/-1.33e-05
( 16384,   8192): 0.620196 +/-1.06e-05, 0.125000 +/-0.00e+00, 0.495196 +/-1.06e-05

(  1024,  16384): 0.620163 +/-1.13e-05, 0.596284 +/-1.71e-05, 0.023880 +/-2.78e-05
(  2048,  16384): 0.620175 +/-2.26e-05, 0.500000 +/-0.00e+00, 0.120175 +/-2.26e-05
(  4096,  16384): 0.620142 +/-1.29e-05, 0.250000 +/-0.00e+00, 0.370142 +/-1.29e-05
(  8192,  16384): 0.620196 +/-1.06e-05, 0.125000 +/-0.00e+00, 0.495196 +/-1.06e-05
( 16384,  16384): 0.620010 +/-6.09e-06, 0.062500 +/-0.00e+00, 0.557510 +/-6.09e-06
```
A couple things I notice:
* We see mean_sigmoid_loss decrease as the input tensor's size increases, but only when CPU is used. When using CUDA or BCELossWithLogits(), the error always stays close to 0.6202.
* The decrease in mean_sigmoid_loss is directly dependent on the total size of the tensor--not just the size of the x-dimension or just the y-dimension.
* For some reason mean_sigmoid_loss is exactly 0.5 when the tensor has 64*1024 elements. Each time the size is doubled from that point on, mean_sigmoid_loss is cut exactly in half.

The fact that we only see this issue on CPU makes me think that `BCELoss(Sigmoid())` is not fundamentally too numerically unstable. I would guess that there's just an implementation issue. But the question is whether the issue is in `Sigmoid()` or `BCELoss()`. I'll figure that out and then I'll start looking into the code itself.

**Comment by kurtamohler** [comment] 2019-12-10 21:41
`sigmoid()` is not the source of error, which means that `BCELoss()` is. I wrote the following test to run sigmoid() on random tensors of all the same sizes that I used in my previous comment, on both CUDA and CPU. I saw no difference between the two.
```
def compare_sigmoid_cuda_vs_cpu():
  device_cpu = torch.device('cpu')
  device_cuda = torch.device('cuda')

  sizes = [2**exponent for exponent in range(10, 15)]
  for y in sizes:
    for x in sizes:
      t_cpu = torch.rand(x, y, requires_grad=False, dtype=torch.float32, device=device_cpu)
      t_cuda = t_cpu.clone().detach().to(device=device_cuda)

      sig_cpu = torch.sigmoid(t_cpu)
      sig_cuda = torch.sigmoid(t_cuda)

      mean_diff = (sig_cuda - sig_cpu.to(device=device_cuda)).abs().max()

      print('(%6d, %6d): %f' % (x, y, mean_diff))
    print()
```

**Comment by albanD** [comment] 2019-12-10 21:59
The thing is that your test above, when run with `dtype=torch.float64`, then all the errors are `0.` right?

It may be that the accumulation (before the `mean` operation) is reaching float32 precision.
In particular, once the value is such that `a + b = a`. Then the mean will have that behavior you observe that doubling the input size divide the output by two. Because the accumulation always gives a, but you divide by a different number.

Note that the difference between `BCELoss` and `BCEWithLogitsLoss` is that the first one is in TH and use the old TH_APPLY while the other one is in aten and does the reduction using `at::mean()`.

**Comment by kurtamohler** [comment] 2019-12-10 22:20
@albanD, thanks for the info. Maybe `at::mean()` is using a trick to avoid floating point error, while `BCELoss`'s reduction method is not. If so, I suppose the solution would be to convert BCELoss from TH to aten.

**Comment by kurtamohler** [comment] 2019-12-10 22:44
Setting BCELoss's `reduction` argument to "none", and then running torch.mean() on its output removes the error:
```
nn.BCELoss(reduction='none')(torch.sigmoid(output), target).mean()
```
So it does indeed appear that BCELoss's mean method is the source of error.

**Comment by albanD** [comment] 2019-12-10 23:40
Well, it has other quirks, but is potentially more precise indeed but only by chance: https://github.com/pytorch/pytorch/issues/27946

Moving BCELoss from TH to aten might solve the issue indeed.

**Comment by kurtamohler** [comment] 2019-12-12 21:22
I figured out how to move BCELoss over to ATen. As we thought, this fixed the error!
Next I need to implement the backward method, remove all the old BCELoss code from TH, and then write an error-checking test.

**Comment by kurtamohler** [comment] 2019-12-13 04:34
I was running the existing unit tests on my new implementation of BCELoss, and I found a case where the method fails and I'm not sure how to fix it.

My main problem is that one of the terms in the binary cross entropy equation is (target * ln(input)). What happens when the input and target are both set to 0?
0 * ln(0) = 0 * infinity

Maybe the answer is that the output of BCELoss should be 0 any time the input and output are equal to each other. Does that seem right?

**Comment by SsnL** [comment] 2019-12-13 04:34
0log0 is usually defined to be 0.

**Comment by XiaobingSuper** [comment] 2019-12-13 07:21
@kurtamohle,  there have a PR https://github.com/pytorch/pytorch/pull/30602 about move BCEloss from TH to Aten, can we corporate to do it?

**Comment by kurtamohler** [comment] 2019-12-13 15:55
@XiaobingSuper , it looks like your goal is to increase the performance of BCELoss for CPUs. My goal is to fix BCELoss's huge amount of error, in both CPU and GPU.

It might be possible to combine our efforts. However, I currently have no idea how well my implementation performs, so I'm going to try building your PR, and then I'll compare both of our implementations with your performance measurement script. You might want to try measuring my implementation's performance as well since we probably have different CPUs. We should probably look at performance of both `reduction='mean'` and `reduction='none'`.

If your implementation is significantly faster than mine, then we should think about how to work together on this. From looking at your code, it seems like the reductions are calculated pretty much the same way that TH did it, so I'm guessing that your implementation still gives inaccurate results when the input tensors have more than 2 million elements.

**Comment by kurtamohler** [comment] 2019-12-13 16:05
@XiaobingSuper, actually, I just realized that your performance script uses the backward method. My implementation doesn't have a backward method yet. Let me try to add one and then we can have a fair comparison.

**Comment by kurtamohler** [comment] 2019-12-13 17:55
@XiaobingSuper, I've added the backward method to my implementation, so if you'd like to measure it's performance, you can clone this branch: https://github.com/pytorch/pytorch/compare/master...kurtamohler:port-BCELoss-to-aten-24933. I made sure that it gives the correct gradient by checking that the gradient is the same when I use either `BCEWithLogits()(x, y).backward()` or `BCELogits()(sigmoid(x), y).backward()`, using both `reduction=mean` and `reduction=sum`.

I'm having a bit of trouble building your PR at the moment. I'm trying a couple things to fix that, but if I can't get it to build, I'll post the error that I'm seeing.

**Comment by kurtamohler** [comment] 2019-12-13 21:15
@XiaobingSuper, so far, I haven't been successful in building your PR--I'm probably doing something wrong. However, I did measure the performance of both my implementation and the old TH implementation using your script, with a few modifications to run larger sizes. I only ran the 'mean' reduction method for now--my implementation has an issue with 'none' that I still need to solve.

My target hardware:
CPU: AMD Ryzen Threadripper 2970WX
GPU: NVIDIA Corporation TU102GL [Quadro RTX 6000/8000] (rev a1)

Old TH implementation on CPU (multithread):
```
reduction='mean'
input size(128, 10) forward time is 0.05 (ms); backward avg time is 0.06 (ms).
input size(128, 100) forward time is 0.25 (ms); backward avg time is 0.21 (ms).
input size(128, 1000) forward time is 2.87 (ms); backward avg time is 3.07 (ms).
input size(128, 10000) forward time is 18.65 (ms); backward avg time is 22.46 (ms).
input size(128, 100000) forward time is 156.27 (ms); backward avg time is 142.50 (ms).
input size(128, 1000000) forward time is 1546.37 (ms); backward avg time is 1282.53 (ms).
```

My ATen implementation on CPU (multithread):
```
reduction='mean'
input size(128, 10) forward time is 0.06 (ms); backward avg time is 0.04 (ms).
input size(128, 100) forward time is 0.11 (ms); backward avg time is 0.07 (ms).
input size(128, 1000) forward time is 3.27 (ms); backward avg time is 0.23 (ms).
input size(128, 10000) forward time is 1.42 (ms); backward avg time is 0.71 (ms).
input size(128, 100000) forward time is 40.45 (ms); backward avg time is 30.87 (ms).
input size(128, 1000000) forward time is 370.68 (ms); backward avg time is 245.26 (ms).
```

Old TH implementation on GPU:
```
reduction='mean'
input size(128, 10) forward time is 0.08 (ms); backward avg time is 0.13 (ms).
input size(128, 100) forward time is 0.09 (ms); backward avg time is 0.14 (ms).
input size(128, 1000) forward time is 0.09 (ms); backward avg time is 0.14 (ms).
input size(128, 10000) forward time is 0.12 (ms); backward avg time is 0.15 (ms).
input size(128, 100000) forward time is 0.51 (ms); backward avg time is 0.44 (ms).
input size(128, 1000000) forward time is 3.95 (ms); backward avg time is 3.22 (ms).
```

My ATen implementation on GPU:
```
reduction='mean'
input size(128, 10) forward time is 0.14 (ms); backward avg time is 0.14 (ms).
input size(128, 100) forward time is 0.14 (ms); backward avg time is 0.14 (ms).
input size(128, 1000) forward time is 0.15 (ms); backward avg time is 0.12 (ms).
input size(128, 10000) forward time is 0.15 (ms); backward avg time is 0.12 (ms).
input size(128, 100000) forward time is 0.18 (ms); backward avg time is 0.13 (ms).
input size(128, 1000000) forward time is 0.66 (ms); backward avg time is 0.25 (ms).
```

The largest size your report included was size(128, 10000), so it's probably fairest for me to just compare my results for that size. For that size on your CPU (multithread), your implementation showed the following speedups for reduction='mean':
```
forward: (85.45 / 32.64) = 2.62x
backward: (13.81 / 0.14) = 98.6x
forward+backward: 3.03x
```

My implementation run on my CPU (multithread) showed these speedups for size(128, 10000):
```
forward: (18.65 / 1.42) = 13.13x
backward: (22.46 / 0.71) = 31.6x
forward+backward: 19.3x
```

Your implementation gives a phenomenal speedup to the backward method. However, it looks like the combined speedup of my backward and forward methods are greater.

If you run my implementation on your hardware and you see different performance, please let me know. But at this point, I think it makes sense for us to go with my implementation since it appears to be faster (although we don't know for sure since we have different hardware) and it also fixes the errors that occur when tensors are more than 2 million elements large.

But still, for me to be rigorous about this performance study, I will need to run with reduction='none'. Also I still want to try building your implementation. I'll post when/if I have that working.

Let me know what you think.

**Comment by kurtamohler** [comment] 2019-12-13 22:08
@XiaobingSuper, I was able to build your PR after all. Something was wrong in my environment. Here's the performance I see:

XiaobingSuper ATen implementation on CPU (multithread):
```
reduction='mean'
input size(128, 10) forward time is 0.03 (ms); backward avg time is 0.03 (ms).
input size(128, 100) forward time is 0.24 (ms); backward avg time is 0.04 (ms).
input size(128, 1000) forward time is 1.93 (ms); backward avg time is 0.30 (ms).
input size(128, 10000) forward time is 16.60 (ms); backward avg time is 0.64 (ms).
input size(128, 100000) forward time is 159.70 (ms); backward avg time is 15.40 (ms).
input size(128, 1000000) forward time is 1567.28 (ms); backward avg time is 107.71 (ms).
```

If we look at size(128, 10000) again, your implementation's speedups compared to the old TH implementation run on my CPU are:
```
forward: (18.65 / 16.6) = 1.12x
backward: (22.46 / 0.64) = 35.1x
forward+backward: ((18.65+22.46)/(16.6+0.64)) = 2.38x
```

So it still looks like you have a bit of an improvement on the backward method, and my implementation is faster overall on my hardware. But again, you might see different results on your hardware.

**Comment by XiaobingSuper** [comment] 2019-12-16 01:33
@kurtamohler,  my forward part is not be parallelized and vectorized, so your implementation can get a better performance, for the backward, my implementation can get a better performance is reason of fusion(it can also get a comparable performance for GPU path, see https://github.com/pytorch/pytorch/pull/26529 ). So can you pull a new request which combine your forward implementation with my backward implementation? Thanks!

**Comment by kurtamohler** [comment] 2019-12-16 17:44
@XiaobingSuper, ok I see. Sure, we can apply your performance improvement to the backward method. Before we do that, I'm going to finish fixing the functionality and add a unit test.

**Comment by kurtamohler** [comment] 2019-12-16 21:11
I was able to fix my 0*log(0) issue by doing this after the main BCE calculation:
```
    loss = at::where(
      at::isnan(loss),
      at::zeros_like(loss),
      loss
    );
```
But I feel like there should be a better way to do it. The problem is that there will probably be very few NaN values in a `loss` tensor. The `at::zeros_like(loss)` call is allocating an entire new tensor filled with zeros the size of the loss tensor. Furthermore, it's creating a new tensor to store the result of the `at::where()` call. It would be better to just do an in-place operation without allocating any new tensors, but at the moment I'm not sure how to do that with ATen functions.

**Comment by kurtamohler** [comment] 2019-12-16 22:20
I discovered another difference between BCELossWithLogits and my implemenation of BCELoss. The BCE loss equation `L = -( y * log(x) + (1-y) * log(1-x) )` tells us that if x = 0 and y != 0, then L = log(0) = infinity. Likewise, if x = 1 and y != 1, then L = infinity. However, BCELossWithLogits apparently limits these values.
```
import torch
import torch.nn as nn
target = torch.tensor([0., 1., 1., 0., 0.5, 0.5], dtype=torch.float)
output = torch.tensor([-100., 100., -100., 100., -100., 100.], dtype=torch.float)
print('sigmoid(output): %s' % str(torch.sigmoid(output)))
print('target: %s' % str(target))
print('BCELoss: %s' % str(
    nn.BCELoss(reduction='none')(torch.sigmoid(output), target)
))
print('BCEWithLogitsLoss: %s' % str(
    nn.BCEWithLogitsLoss(reduction='none')(output, target)
))
```
The output when my most recent commits are used:
```
sigmoid(output): tensor([0., 1., 0., 1., 0., 1.], dtype=torch.float32)
target: tensor([0.0000, 1.0000, 1.0000, 0.0000, 0.5000, 0.5000], dtype=torch.float32)
BCELoss: tensor([0., 0., inf, inf, inf, inf], dtype=torch.float32)
BCEWithLogitsLoss: tensor([  0.,   0., 100., 100.,  50.,  50.], dtype=torch.float32)

```
BCELoss shows the correct behavior according to the BCE loss equation. But BCEWithLogitsLoss seems to show a sort of percentage difference between the output and target. For instance, if sigmoid(x) = 1 and y = 0, then L = 100. If sigmoid(x) = 0.5 and y = 0, then L = 50.

However, I notice that if I try to calculate the gradient of BCELoss when the loss is infinite, I get NaN, which makes some sense--I'm guessing that's why BCEWithLogitsLoss clamps the loss to a finite value.

My question is: should I mimick BCEWithLogitsLoss? In my opinion, it should be acceptable to simply clamp infinity to a constant big number--I don't see why we would want the percentage difference that BCEWithLogitsLoss gives us.

**Comment by kurtamohler** [comment] 2019-12-16 23:37
For now, I just decided to follow suit with how BCEWithLogitsLoss works. We can change that if needed, but if so, we should change it in both places.

**Comment by kurtamohler** [comment] 2019-12-17 05:19
I've fixed BCELoss's error for large tensors, made sure that it matches BCEWithLogitsLoss, and added a check to make sure all input tensor elements are between 0 and 1. I added a unit test to compare both forward and backward results of BCELoss and BCEWithLogitsLoss, and another unit test to make sure the input tensor throws an error if elements are outside 0 and 1.

@XiaobingSuper, I think it would make sense for me to create a PR now, and then once my changes are merged, you could apply your optimized backward method to it. Does that sound good to you, or is there a better way?

**Comment by XiaobingSuper** [comment] 2019-12-17 05:26
@kurtamohler, you can creat a new PR to fix this issue first. Thanks!

**Comment by kurtamohler** [comment] 2020-01-29 21:52
@XiaobingSuper , my changes have been completed and merged, so feel free to make a PR that applies your vectorization method on top of it.

**Closed** 2020-01-29 21:53 UTC
Labels: high priority, module: autograd, module: nn, topic: numerical-stability, triaged
