### ISSUE TITLE
[inductor][cpu] llama and pytorch_stargan failed on CPP Wrapper

### ISSUE THREAD

**Issue by WeizhuoZhang-intel** [pytorch/pytorch#114869] opened 2023-11-30 13:59 UTC
### 🐛 Describe the bug

- [ ] `llama` failed on CPP Wrapper static and dynamic shape in 2023-11-29
- [ ] `pytorch_stargan` only failed on CPP Wrapper dynamic shape in 2023-11-29

**Error message:**
```shell
running  './bisect_run_test.sh' 'torchbench' 'llama' 'inference' 'float32' 'static' 'cpp' 'performance' 'crash' 'multiple' 'first' 'on' '0' '0' 'inductor' '1.1'
PT build success!
Testing with cpp wrapper.
Testing with freezing on.
multi-threads testing....

loading model: 0it [00:00, ?it/s]
loading model: 0it [00:00, ?it/s]cpu  eval  llama                              

ERROR:common:Backend dynamo failed in warmup()
Traceback (most recent call last):
  File "/workspace/pytorch/benchmarks/dynamo/common.py", line 2383, in warmup
    fn(model, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 489, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/eval_frame.py", line 655, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 721, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 383, in _convert_frame_assert
    compiled_product = _compile(
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 645, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 562, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/workspace/pytorch/torch/_dynamo/bytecode_transformation.py", line 1033, in transform_code_object
    transformations(instructions, code_options)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 151, in _fn
    return fn(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/convert_frame.py", line 527, in transform
    tracer.run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2123, in run
    super().run()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 818, in run
    and self.step()
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 781, in step
    getattr(self, inst.opname)(inst)
  File "/workspace/pytorch/torch/_dynamo/symbolic_convert.py", line 2238, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 912, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1069, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1141, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/workspace/pytorch/torch/_dynamo/output_graph.py", line 1122, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/workspace/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_dynamo/backends/inductor.py", line 9, in inductor
    return compile_fx(*args, **kwargs)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 986, in compile_fx
    return compile_fx(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 1168, in compile_fx
    return aot_autograd(
  File "/workspace/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 4952, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/workspace/pytorch/torch/_dynamo/utils.py", line 244, in time_wrapper
    r = func(*args, **kwargs)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 4492, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2831, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 3017, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/workspace/pytorch/torch/_functorch/aot_autograd.py", line 2130, in aot_dispatch_base
    compiled_fw = compiler(fw_module, updated_flat_args)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 915, in fw_compiler_freezing
    optimized_function = inner_compile(
  File "/workspace/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
  File "/workspace/pytorch/torch/_inductor/debug.py", line 303, in inner
    return fn(*args, **kwargs)
  File "/opt/conda/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 320, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
  File "/workspace/pytorch/torch/_inductor/compile_fx.py", line 514, in fx_codegen_and_compile
    post_grad_passes(gm, is_inference=is_inference)
  File "/workspace/pytorch/torch/_inductor/fx_passes/post_grad.py", line 100, in post_grad_passes
    reinplace_inplaceable_ops(gm.graph)
  File "/workspace/pytorch/torch/_inductor/fx_passes/post_grad.py", line 669, in reinplace_inplaceable_ops
    assert node.args[0].op == "placeholder"
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
AssertionError: 

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

**SW info**
SW | Nightly commit | Main commit
-- | -- | --
Pytorch | df0c1b3 |  
Torchbench | / | 94126be6
torchaudio | db62484 |  
torchtext | b0ebddc |  
torchvision | 893b4ab |  
torchdata | 11bb5b8 |  
dynamo_benchmarks | nightly | /

image: docker pull ccr-registry.caas.intel.com/pytorch/pt_inductor:2023_11_29_aws

Repro

[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)

```shell
# llama
bash inductor_single_run.sh multiple inference performance torchbench llama float32 first static cpp 0

# pytorch_stargan 
bash inductor_single_run.sh multiple inference performance torchbench pytorch_stargan float32 first dynamic cpp 0
```

**Suspected guilty commit:** https://github.com/pytorch/pytorch/commit/a378ae33e99fbdcc2c73c6456947212cb3fe647c

cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519

**Comment by WeizhuoZhang-intel** [comment] 2023-11-30 18:03
cc @WeizhuoZhang-intel @chuanqi129

**Comment by WeizhuoZhang-intel** [comment] 2023-11-30 18:04
cc @zxd1997066 @chuanqi129

**Comment by chuanqi129** [comment] 2023-12-01 01:44
Please @WeizhuoZhang-intel help to upload the bisect search log in the issue

**Comment by chuanqi129** [comment] 2023-12-01 04:31
Hi @tugsbayasgalan, we observed some functionality crash in cpu related tests, and seems caused by the PR #114421, could you please help to double check it? Thanks

**Comment by leslie-fang-intel** [comment] 2023-12-21 08:41
@tugsbayasgalan could you help to take a look?

**Comment by tugsbayasgalan** [comment] 2023-12-22 19:14
Hi could you double check if it is resolved or not? I landed a fix sometime ago

**Comment by leslie-fang-intel** [comment] 2024-01-04 08:22
Hi @WeizhuoZhang-intel, please help to confirm

**Closed** 2024-01-18 07:55 UTC
Labels: module: cpu, triaged, oncall: pt2, module: inductor, oncall: cpu inductor
