### ISSUE TITLE
torch.compile segmentation fault

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#113740] opened 2023-11-15 06:04 UTC
### 🐛 Describe the bug

Error stack:

```
BFD: DWARF error: section .debug_info is larger than its filesize! (0x5d4c26 vs 0x436168)
==== backtrace (tid:3341850) ====
 0 0x0000000000042520 __sigaction()  ???:0
 1 0x000000000016a659 _Py_XINCREF()  python-3.8.13/Include/object.h:531
 2 0x000000000016a659 _PyErr_SetObject()  python-3.8.13/Python/errors.c:115
 3 0x000000000016a659 _PyErr_SetString()  python-3.8.13/Python/errors.c:206
 4 0x000000000016a659 PyErr_SetString()  python-3.8.13/Python/errors.c:214
 5 0x0000000000001403 gpuAssert.constprop.0()  main.c:0
 6 0x0000000000001873 launch()  main.c:0
 7 0x000000000013bf90 cfunction_call_varargs()  python-3.8.13/Objects/call.c:758
 8 0x000000000013bf90 PyCFunction_Call()  python-3.8.13/Objects/call.c:773
 9 0x0000000000124631 _PyObject_MakeTpCall()  python-3.8.13/Objects/call.c:159
10 0x0000000000120481 _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:125
11 0x0000000000120481 call_function()  python-3.8.13/Python/ceval.c:4963
12 0x0000000000120481 _PyEval_EvalFrameDefault()  python-3.8.13/Python/ceval.c:3469
13 0x000000000011a461 PyEval_EvalFrameEx()  python-3.8.13/Python/ceval.c:741
14 0x000000000012c33c _PyFunction_Vectorcall()  python-3.8.13/Objects/call.c:436
15 0x000000000013e09c PyVectorcall_Call()  python-3.8.13/Objects/call.c:200
16 0x000000000013e09c PyObject_Call()  python-3.8.13/Objects/call.c:228
17 0x000000000011d870 do_call_core()  python-3.8.13/Python/ceval.c:5010
18 0x000000000011d870 _PyEval_EvalFrameDefault()  python-3.8.13/Python/ceval.c:3559
19 0x000000000011ab76 PyEval_EvalFrameEx()  python-3.8.13/Python/ceval.c:741
20 0x000000000011ab76 _PyEval_EvalCodeWithName()  python-3.8.13/Python/ceval.c:4298
21 0x000000000013b85c _PyFunction_Vectorcall()  python-3.8.13/Objects/call.c:436
22 0x000000000013b85c _Py_CheckFunctionResult()  python-3.8.13/Objects/call.c:25
23 0x000000000013b85c _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:128
24 0x000000000013b85c method_vectorcall()  python-3.8.13/Objects/classobject.c:60
25 0x000000000011c808 _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:127
26 0x000000000011c808 _Py_CheckFunctionResult()  python-3.8.13/Objects/call.c:25
27 0x000000000011c808 _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:128
28 0x000000000011c808 call_function()  python-3.8.13/Python/ceval.c:4963
29 0x000000000011c808 _PyEval_EvalFrameDefault()  python-3.8.13/Python/ceval.c:3515
30 0x000000000012c2a6 PyEval_EvalFrameEx()  python-3.8.13/Python/ceval.c:741
31 0x000000000012c2a6 _PyFunction_Vectorcall()  python-3.8.13/Objects/call.c:411
32 0x000000000011baab _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:127
33 0x000000000011baab _Py_CheckFunctionResult()  python-3.8.13/Objects/call.c:25
34 0x000000000011baab _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:128
35 0x000000000011baab call_function()  python-3.8.13/Python/ceval.c:4963
36 0x000000000011baab _PyEval_EvalFrameDefault()  python-3.8.13/Python/ceval.c:3500
37 0x000000000011ab76 PyEval_EvalFrameEx()  python-3.8.13/Python/ceval.c:741
38 0x000000000011ab76 _PyEval_EvalCodeWithName()  python-3.8.13/Python/ceval.c:4298
39 0x000000000012c33c _PyFunction_Vectorcall()  python-3.8.13/Objects/call.c:436
40 0x000000000011baab _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:127
41 0x000000000011baab _Py_CheckFunctionResult()  python-3.8.13/Objects/call.c:25
42 0x000000000011baab _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:128
43 0x000000000011baab call_function()  python-3.8.13/Python/ceval.c:4963
44 0x000000000011baab _PyEval_EvalFrameDefault()  python-3.8.13/Python/ceval.c:3500
45 0x000000000011a461 PyEval_EvalFrameEx()  python-3.8.13/Python/ceval.c:741
46 0x000000000012c33c _PyFunction_Vectorcall()  python-3.8.13/Objects/call.c:436
47 0x000000000011c808 _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:127
48 0x000000000011c808 _Py_CheckFunctionResult()  python-3.8.13/Objects/call.c:25
49 0x000000000011c808 _PyObject_Vectorcall()  python-3.8.13/Include/cpython/abstract.h:128
50 0x000000000011c808 call_function()  python-3.8.13/Python/ceval.c:4963
51 0x000000000011c808 _PyEval_EvalFrameDefault()  python-3.8.13/Python/ceval.c:3515
52 0x000000000011ab76 PyEval_EvalFrameEx()  python-3.8.13/Python/ceval.c:741
53 0x000000000011ab76 _PyEval_EvalCodeWithName()  python-3.8.13/Python/ceval.c:4298
54 0x000000000012c33c _PyFunction_Vectorcall()  python-3.8.13/Objects/call.c:436
55 0x000000000013e172 PyVectorcall_Call()  python-3.8.13/Objects/call.c:200
56 0x000000000013e172 _Py_CheckFunctionResult()  python-3.8.13/Objects/call.c:25
```

Python backtrace:

```
  File "<string>", line 6 in launcher
  File "torch/_inductor/triton_ops/autotune.py", line 190 in run
  File "/tmp/tmpz6xfo1g3/m7/cm7lt2eztbclmuwmkovykcboybniz3mtoovrrpp6qu7kem6q2cpx.py", line 11267 in call
  File "torch/_inductor/compile_fx.py", line 248 in run
  File "torch/_functorch/aot_autograd.py", line 1249 in call_func_with_args
  File "torch/_functorch/aot_autograd.py", line 2168 in forward
  File "torch/autograd/function.py", line 506 in apply
  File "torch/_functorch/aot_autograd.py", line 1224 in g
  File "torch/_functorch/aot_autograd.py", line 1249 in call_func_with_args
  File "torch/_functorch/aot_autograd.py", line 1900 in runtime_wrapper
  File "torch/_functorch/aot_autograd.py", line 2403 in debug_compiled_function
  File "torch/_functorch/aot_autograd.py", line 1224 in g
  File "torch/_functorch/aot_autograd.py", line 2836 in forward
  File "torch/_dynamo/eval_frame.py", line 209 in _fn
  File "torch/_dynamo/backends/distributed.py", line 247 in forward
  File "torch/nn/modules/module.py", line 1501 in _call_impl
  File "<eval_with_key>.253", line 347 in forward
  File "torch/_dynamo/eval_frame.py", line 209 in _fn
  File "torch/_dynamo/eval_frame.py", line 82 in forward
  File "torch/nn/modules/module.py", line 1501 in _call_impl
  File "foo.py", line 710 in forward
  File "torch/nn/modules/module.py", line 1501 in _call_impl
  File "torch/nn/parallel/distributed.py", line 1110 in _run_ddp_forward
  File "torch/nn/parallel/distributed.py", line 1156 in forward
  File "torch/_dynamo/eval_frame.py", line 209 in _fn
  File "torch/_dynamo/eval_frame.py", line 82 in forward
  File "torch/nn/modules/module.py", line 1501 in _call_impl
```

Running `$python /tmp/tmpz6xfo1g3/m7/cm7lt2eztbclmuwmkovykcboybniz3mtoovrrpp6qu7kem6q2cpx.py` also fails with a different error:

```
    assert_size_stride(buf1711, (10, 480, 1, 30), (14400, 1, 14400, 480))
AssertionError: expected size 480==480, stride 30==1 at dim=1
```

### Versions

PyTorch 2.0.1

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @muchulee8 @aakhundov @ColinPeppler

**Comment by wconstab** [comment] 2023-11-15 17:40
im not sure about the segfault, but the assertion error about strides mismatch looks suspiciously similar to this issue https://github.com/pytorch/pytorch/issues/107362.

The summary is that DDPOptimizer splits up a single graph into multiple graphs, and it uses fake tensor prop to find out output strides from one subgraph and uses those strides as the input strides for the next subgraph.  Inductor has a flag for preserving output strides, which iirc is defaulted to true and errors if set to false when used with DDPOptimizer, but, in the past we have seen cases where inductor did not preserve output strides despite this flag.

Separately there is another flag for inductor `TORCHINDUCTOR_LAYOUT_OPTIMIZATION=0` which may be a workaround if layout optimization is causing the stride mismatch.

**Comment by bdhirsh** [comment] 2023-11-15 17:56
Another useful datapoint might be to see if the issue still shows up when you run with `torch.compile(..., backend="aot_eager_decomp_partition")` (this will tell us if there's something wrong if the problem only shows up with inductor, or if it's something else)

Agreed with Will's suggestion about trying `TORCHINDUCTOR_LAYOUT_OPTIMIZATION=0` too

**Comment by pritamdamania87** [comment] 2023-11-15 19:12
@wconstab Running `TORCHINDUCTOR_LAYOUT_OPTIMIZATION=0 python /tmp/tmpz6xfo1g3/m7/cm7lt2eztbclmuwmkovykcboybniz3mtoovrrpp6qu7kem6q2cpx.py` is still giving me the same error as mentioned above about strides.

**Comment by wconstab** [comment] 2023-11-15 19:15
i think that env only affects how inductor _generates_ that .py file, so you'd have to try the flag along with the source program from which that file was generated.

**Comment by eellison** [comment] 2023-11-15 19:23
@pritamdamania87 would you mind posting the op that produced `buf1711` and its inputs ?

**Comment by pritamdamania87** [comment] 2023-11-15 19:29
@eellison 

```
# buf1709.size()=torch.Size([10, 80, 1, 30]) buf1708.size()=torch.Size([480, 80, 1, 1])
buf1711 = aten.convolution(buf1709, buf1708, None, (1, 1), (0, 0), (1, 1), False, (0, 0), 1)
```

**Comment by yf225** [comment] 2023-11-15 20:03
@pritamdamania87 Curious to narrow down on the issue:
1. Did you run the original program with `layout_optimization` or `keep_output_stride` set to True in `torch._inductor.config`?
2. Did you set `TORCHINDUCTOR_LAYOUT_OPTIMIZATION` or `TORCHINDUCTOR_KEEP_OUTPUT_STRIDE` envvars when running the original program?

**Comment by pritamdamania87** [comment] 2023-11-15 20:21
> 1. Did you run the original program with layout_optimization or keep_output_stride set to True in torch._inductor.config?
> 2. Did you set TORCHINDUCTOR_LAYOUT_OPTIMIZATION or TORCHINDUCTOR_KEEP_OUTPUT_STRIDE envvars when running the original program?

Didn't specify any of these options, the original program picked up whatever is the default for these.

**Comment by pritamdamania87** [comment] 2023-11-15 21:45
@wconstab @bdhirsh It looks like this combination seems to be working: `TORCHINDUCTOR_LAYOUT_OPTIMIZATION=0 TORCHDYNAMO_REPRO_AFTER="aot"` and `backend= aot_eager_decomp_partition`. Should I try using `TORCHINDUCTOR_LAYOUT_OPTIMIZATION=0 TORCHDYNAMO_REPRO_AFTER="aot"` with `backend=inductor` to see if I can get a minified repro?

**Comment by pritamdamania87** [comment] 2023-11-15 23:30
@wconstab I'm assuming in this case I can't get the minifier to work since it is a segfault and there is no opportunity for the minifier to work.

**Comment by pritamdamania87** [comment] 2023-11-15 23:45
@wconstab I did run the source program with `TORCHINDUCTOR_LAYOUT_OPTIMIZATION=0` but it looks like the newly generated .py file still fails with the same error.

**Comment by jon-chuang** [comment] 2023-11-19 20:26
> in the past we have seen cases where inductor did not preserve output strides despite this flag.

Maybe we need to assert on this somewhere, it shouldn't be a silent error in any case.

**Comment by pritamdamania87** [comment] 2023-11-20 18:38
`torch._dynamo.config.optimize_ddp=False` seems to mitigate this issue.

**Comment by jon-chuang** [comment] 2023-11-20 19:08
> torch._dynamo.config.optimize_ddp=False seems to mitigate this issue.

That's because it will not split the graph and potentially OOM the node.

**Comment by jon-chuang** [comment] 2023-11-20 19:55
@pritamdamania87, if you are able, please try the branch https://github.com/pytorch/pytorch/pull/114154 with default settings. It ought to work without any special config.

**Comment by pritamdamania87** [comment] 2023-11-20 19:58
@jon-chuang Is this expected to resolve https://github.com/pytorch/pytorch/issues/113788 and https://github.com/pytorch/pytorch/issues/113786 as well?

**Comment by jon-chuang** [comment] 2023-11-20 20:09
If the root cause is the same, as it seems judging by the logs, then yes.

**Comment by jon-chuang** [comment] 2023-11-21 22:41
@pritamdamania87 the fix has been merged on main.

Would appreciate confirmation on whether the 3 related issues have been fixed.

**Closed** 2023-11-28 06:29 UTC
Labels: high priority, triage review, triaged, module: ddp, oncall: pt2, module: inductor
