### ISSUE TITLE
set num_workers =0, the script is interrupted ,raising 'kernel is dead'.

### ISSUE THREAD

**Issue by huangjin520** [pytorch/pytorch#62878] opened 2021-08-06 06:09 UTC
## 🐛 Bug

  
I encounter a question about **torch.utils.data.DataLoader()**.When i run a train.py ,it will raise wrong message ,showing in the last .  In order to run the script normally , i find two
solutions. 
First, set num_workers =0. 
Second, run script  with other python interpreter. 
I test these solutions one by one ,but it still donesn't work . When i set **num_workers = 0, it will show'the kernel is dead'. When i set num_workers>0,it will show in the wrong message section.**  Maybe you will thik ,is there anything wrong in my code.however, no. the train.py can work normally in my old computer with python 3.7+torch1.5.0+cu101, but it can't work in my new computer with python 3.8.10+torch1.9.0+cu111.   So i want to know where is the error and how to solve the problem.  At the same time ,because the train.py is used to train a huge image dataset, I need to speed up the training process by set num_workers>1. 
In this condation, how to solve this problem?

**Thank you very much for your discussion and attention**
## Environment
pytorch=1.6.0
windows 10 profession
pip install pytorch
python=3.8.10
torch.__version__= 1.9.0+cu111
torch.version.cuda= 11.1
torch.backends.cudnn.version= 8005
python interpreter:pycharm/spyder/jupyter

## Material
**1.train.py**

```
from __future__ import print_function
import argparse
import torch
import torch.utils.data
from torch import nn, optim
from torch.nn import functional as F
from torchvision import datasets, transforms
from torchvision import models
from torchvision.utils import save_image
from torchvision.datasets import ImageFolder
import torch.backends.cudnn as cudnn
import random
import os
import tqdm
train_on_gpu = torch.cuda.is_available()
device = torch.device("cuda:0" if train_on_gpu else "cpu")

data_transform = transforms.Compose([transforms.ToTensor()])
train_data_root = r'D:\DeepLearning\Data\train'
train_dataset = ImageFolder(train_data_root, transform=data_transform)
train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=1,
                                           shuffle=True, num_workers=2)
test_data_root = r'D:\DeepLearning\Data\train'
test_dataset = ImageFolder(test_data_root, transform=data_transform)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=1,
                                          shuffle=True, num_workers=2)
def train(epoch):
    for iteration, (images, labels) in enumerate(train_loader):  ###here is wrong location
        images = images.to(device)
        labels = labels.to(device)
if __name__ == '__main__':
    best_acc = 0
    epoches =12
    for epoch in range(1, epoches + 1):
        train(epoch)
        print("===> Epoch({}/{})".format(epoch,epoches))
```
**2.wrong message**
![image](https://user-images.githubusercontent.com/68464169/128532694-93d381ba-0ab7-4118-92bf-eaa1606e10a4.png)

Traceback (most recent call last):

  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", **line 990**, in _try_get_data
    data = self._data_queue.get(timeout=timeout)

  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\multiprocessing\queues.py", **line 108,** in get
    raise Empty

Empty

**The above exception was the direct cause of the following exception:**

Traceback (most recent call last):

  File "D:\DeepLearning\Code\ResNet50\train_jin.py", line 151, in <module>
    train_loss = train(epoch)

  File "D:\DeepLearning\Code\ResNet50\train_jin.py", line 102, in train
    for iteration, (images, labels) in enumerate(train_loader):

  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 521, in __next__
    data = self._next_data()

  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 1186, in _next_data
    idx, data = self._get_data()

  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 1152, in _get_data
    success, data = self._try_get_data()

  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\torch\utils\data\dataloader.py", line 1003, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e

**RuntimeError: DataLoader worker (pid(s) 13980) exited unexpectedly**

cc @SsnL @VitalyFedyunin @ejguan

**Comment by ejguan** [comment] 2021-08-06 13:50
Could you please re-format your code? You can create fenced code blocks by placing triple backticks ` ``` ` before and after the code block. 
Please check https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks

For the case `kernel is dead`, I think you are still using jupyter interpreter. Can you use your python script and call `python xxx.py` to run your code?

**Comment by huangjin520** [comment] 2021-08-06 15:07
> Could you please re-format your code? You can create fenced code blocks by placing triple backticks `` ``` `` before and after the code block.
> Please check https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks
> 
> For the case `kernel is dead`, I think you are still using jupyter interpreter. Can you use your python script and call `python xxx.py` to run your code?

I update my question according to you advice, after that I run the new code with cmd ,but there is still something wrong making my script get error.

**Comment by ejguan** [comment] 2021-08-06 15:09
![image](https://user-images.githubusercontent.com/68879799/128531848-e0e5f65a-bbbd-4f6d-800f-82a9a212d3ba.png)
Here is the Error. You don't have data in that path.

**Comment by huangjin520** [comment] 2021-08-06 15:20
> ![image](https://user-images.githubusercontent.com/68879799/128531848-e0e5f65a-bbbd-4f6d-800f-82a9a212d3ba.png)
> Here is the Error. You don't have data in that path.
Yes,but this is a last error that i solved it .In the next cmd line, i run the script again , the error message is show in picture. Thanks  for your answer, and hope for your next solution.

**Comment by ejguan** [comment] 2021-08-06 15:25
Can you post if there is any Error when you use `num_workers=0` for debugging?

**Comment by huangjin520** [comment] 2021-08-06 15:57
> Can you post if there is any Error when you use `num_workers=0` for debugging?

I debug the code with `num_workers=0`, there are cases  below.

run with cmd:
work unnormally.
![image](https://user-images.githubusercontent.com/68464169/128537815-92ad747d-4b5a-477e-af4b-e2e995e26677.png)
run with spyder:
the script is interrupted ,and restarts kernel.
![image](https://user-images.githubusercontent.com/68464169/128538278-9d31ebfa-af73-4503-a9c6-68a9d6ab68cf.png)

**Comment by ejguan** [comment] 2021-08-06 16:02
I guess there is something wrong with your dataset. To debug, you'd better first iterate your dataset to see if any data is fetched from your filesystem.
Take a look at https://pytorch.org/vision/stable/datasets.html#torchvision.datasets.ImageFolder to see if your dataset is organized this way.

**Comment by huangjin520** [comment] 2021-08-06 16:50
I check my dataset, the dataset is organized as the right way. Next , i debug the script one sentence by one sentence,   finding that both` Imagefolder()` and `torch.utils.data.DataLoader() ` work normally.When the script run to the  **`for iteration, (images, labels) in enumerate(train_loader):`**, the error will raise.

**So special Error!**

![image](https://user-images.githubusercontent.com/68464169/128544600-b44fbedd-bf8e-4c19-af49-1b7c1ca30103.png)

**Comment by ejguan** [comment] 2021-08-06 16:52
Please use `num_worker=0` to debug!!!!

**Comment by huangjin520** [comment] 2021-08-06 17:14
![image](https://user-images.githubusercontent.com/68464169/128547780-64bcc877-d81d-466c-87c6-e10503388402.png)

**Comment by Aidenfaustine** [comment] 2021-08-07 14:43
@huangjin520 , 我看我们使用相同的数据集，可以加V：shai265130多交流。很抱歉邮件定期查看，希望你的问题解决了。

**Comment by ejguan** [comment] 2021-08-09 13:54
@huangjin520 
Could you validate the data by iterating `train_dataset`?
```
for d in train_dataset:
    print(d)
```

**Comment by huangjin520** [comment] 2021-12-14 08:53
I solved the problem after i upgraded the torch package.

**Comment by kushaangupta** [comment] 2022-07-23 02:38
Is this issue ever going to be resolved for windows? Windows users cannot properly utilize GPU for dataloaders. Setting num_workers=0 is sluggishly slow as doing the whole thing on GPU

**Comment by ejguan** [comment] 2022-07-25 13:43
@kushaangupta IIRC, multiprocessing (`num_worker>0`) is not working properly in notebook on Windows. Could you please try to run it as a normal script?

**Comment by ejguan** [comment] 2022-07-25 13:43
I am closing this Issue as the OP has reported the issue is resolved.

**Closed by ejguan** 2022-07-25 13:43 UTC
Labels: module: dataloader, triaged
