### ISSUE TITLE
[inductor][cpu] hf_T5_generate cpp wrapper static/dynamic shape multiple threads performance drop

### ISSUE THREAD

**Issue by zxd1997066** [pytorch/pytorch#115824] opened 2023-12-14 14:12 UTC
### 🐛 Describe the bug

<p>hf_T5_generate cpp wrapper static multiple threads performance regression in 2023-12-10</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_T5_generate</td>
      <td>1.0</td>
      <td>1.456816</td>
      <td>0.997716005</td>
      <td>1.4534886395400801</td>
      <td>492.982274</td>
      <td>1</td>
      <td>1.703512</td>
      <td>0.844548553</td>
      <td>1.4386985946181359</td>
      <td>213.512426</td>
      <td>0.86</td>
      <td>0.99</td>
      <td>0.85</td>
      <td>0.43</td>
    </tr>
  </tbody>

</table><p>hf_T5_generate cpp wrapper dynamic multiple threads performance regression in 2023-12-10</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>name</th>
      <th>batch_size_new</th>
      <th>speed_up_new</th>
      <th>inductor_new</th>
      <th>eager_new</th>
      <th>compilation_latency_new</th>
      <th>batch_size_old</th>
      <th>speed_up_old</th>
      <th>inductor_old</th>
      <th>eager_old</th>
      <th>compilation_latency_old</th>
      <th>Ratio Speedup(New/old)</th>
      <th>Eager Ratio(old/new)</th>
      <th>Inductor Ratio(old/new)</th>
      <th>Compilation_latency_Ratio(old/new)</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>hf_T5_generate</td>
      <td>1.0</td>
      <td>1.448865</td>
      <td>1.007798784</td>
      <td>1.46016438518016</td>
      <td>495.529855</td>
      <td>1</td>
      <td>1.694636</td>
      <td>0.8569847580000001</td>
      <td>1.4522772223580882</td>
      <td>212.124006</td>
      <td>0.85</td>
      <td>0.99</td>
      <td>0.85</td>
      <td>0.43</td>
    </tr>
  </tbody>

</table><p>SW info</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>SW</th>
      <th>Nightly commit</th>
      <th>Main commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Pytorch</td>
      <td>5da0a5d</td>
      <td></td>
    </tr>
    <tr>
      <td>Torchbench</td>
      <td>/</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>6518fa9</td>
      <td></td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>b0ebddc</td>
      <td></td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>e12d200</td>
      <td></td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>11bb5b8</td>
      <td></td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
      <td>/</td>
    </tr>
  </tbody>
</table><p>Reference SW info (nightly)</p><table border="1" class="dataframe table">
  <thead>
    <tr style="text-align: right;">
      <th>item</th>
      <th>commit</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>torchbench</td>
      <td>99944a2f</td>
    </tr>
    <tr>
      <td>torch</td>
      <td>2.2.0a0+git6fc9d89</td>
    </tr>
    <tr>
      <td>torchvision</td>
      <td>0.17.0a0+c1e2095</td>
    </tr>
    <tr>
      <td>torchtext</td>
      <td>0.16.0a0+b0ebddc</td>
    </tr>
    <tr>
      <td>torchaudio</td>
      <td>2.1.1+db62484</td>
    </tr>
    <tr>
      <td>torchdata</td>
      <td>0.7.0a0+11bb5b8</td>
    </tr>
    <tr>
      <td>dynamo_benchmarks</td>
      <td>nightly</td>
    </tr>
  </tbody>

Repro
[inductor_single_run.sh](https://github.com/chuanqi129/inductor-tools/blob/yudong/aws_auto/scripts/modelbench/inductor_single_run.sh)
bash inductor_single_run.sh multiple inference performance torchbench hf_T5_generate float32 first static cpp 0
Suspected guilty commit: https://github.com/pytorch/pytorch/commit/a70c85ce90c0cfb6ac0554e115fb3a36e653f5d3
[torchbench-hf_T5_generate-inference-float32-static-cpp-performance-multiple-drop_guilty_commit.log](https://github.com/pytorch/pytorch/files/13674312/torchbench-hf_T5_generate-inference-float32-static-cpp-performance-multiple-drop_guilty_commit.log)
cc @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @Guobing-Chen @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @peterbell10 @ipiszy @yf225 @chenyang78 @kadeng @muchulee8 @aakhundov @ColinPeppler @WeizhuoZhang-intel @chuanqi129

**Comment by leslie-fang-intel** [comment] 2023-12-15 09:05
Here is the

- generated code after regression: https://gist.github.com/leslie-fang-intel/ec1267d8c269280fbb2406bd6fe2f014

- generated code before regression: https://gist.github.com/leslie-fang-intel/7d004df90cf8f8a921f0382323582bb9

Looks like several more graph break found after the regression

**Comment by leslie-fang-intel** [comment] 2023-12-21 10:05
Hi @jansel, this https://github.com/pytorch/pytorch/commit/a70c85ce90c0cfb6ac0554e115fb3a36e653f5d3 causes the regression and it doesn't look like a CPU specific issue. Could you help to take a look?

**Comment by jansel** [comment] 2024-01-08 03:57
I think this may have removed a graph break which triggers some recompiles....

**Comment by masnesral** [comment] 2024-07-10 01:26
@leslie-fang-intel I'm helping scrub through old issues this week. There hasn't been any discussion for while. Do you think this is still an issue to leave open?

**Comment by leslie-fang-intel** [comment] 2024-07-10 02:45
I guess it may still be an issue. However, since `hf_T5_generate` has been removed from weekly test report, I think we can close this issue.

**Closed by leslie-fang-intel** 2024-07-10 02:45 UTC
Labels: module: cpu, triaged, oncall: pt2, module: inductor, oncall: cpu inductor
