### ISSUE TITLE
There should be metrics package

### ISSUE THREAD

**Issue by kaszperro** [pytorch/pytorch#22439] opened 2019-07-02 08:09 UTC
## 🚀 Feature
Why not implement some common metrics, to evaluate models, with strong GPU acceleration.

## Motivation

When I need to evaluate model accuracy (ex. measure r squared) I have to write it by hand, or use Numpy or other library (without GPU support). It'd be cleaner and simpler to have dedicated package with Pytonic API. It could also provide performance benefits because of low-level (c++) optimizations.  

## Pitch

I'd like to have some package ex: `torch.metrics` then I could do something like:

```python
from torch.metrics import RSquaredMetric
metric = RSquaredMetric()
out = model(input)
r_squared = metric(out, reference)
```
Or I could do:
```python
from torch.metrics import MSEMetric
metric = MSEMetric()
out = model(input)
mse = metric(out, reference)
```

## Alternatives

For now, I can use some Tensors modifications or use Numpy:

```python
ref_val = reference_batch[key].cpu().detach().numpy()
cor_matrix = np.corrcoef(val, ref_val, rowvar=False)
n = cor_matrix.shape[0] // 2
out_r2[key] = [cor_matrix[i][i + n] for i in range(n)]
```

If you agree, I'd like to contribute.

cc @ezyang @gchanan @zou3519 @albanD @mruberry

**Comment by albanD** [comment] 2019-07-02 08:37
I'm not sure what the difference would be with the [loss functions from torch.nn](https://pytorch.org/docs/stable/nn.html#id52) ?

**Comment by kaszperro** [comment] 2019-07-02 09:07
Correct me if I'm wrong, but losses functions are intended to do .backward() on the Tensors returned by them. But for some metrics, like RSquared, Quantiles, ... it doesn't make sense or is undoable. So metrics don't need to calculate gradients and so one.

**Comment by albanD** [comment] 2019-07-02 09:22
The autograd overhead is very small, even if you can do a .backward(), you don't have to.
Also, if the input does not require gradients, or you're executing the function within a `with torch.no_grad():` block, the autograd is not enabled and so these functions will run as fast as the version that never computes gradients.

I agree though that standard metrics could be implemented, either in [tnt](https://github.com/pytorch/tnt) or in the main package?

**Comment by kaszperro** [comment] 2019-07-02 09:33
I get your point, you are correct. 

In my opinion, those metrics should be added to the main package, because as you pointed, it could be done within losses function from torch.nn. If it'd be done in tnt project, how would you classify which metric or 'loss' should be implemented in main package or in tnt? 
Also there are already some in torch, like MSE, so it'd be intcosisnten to use ex. MSE from torch and RSquared from tnt.

**Comment by kaszperro** [comment] 2019-07-02 10:46
I'd like to also discuss, where should it be implemented? For sure as a new losses functions? If so, how should for example quantiles look like? 
I'd like it to be something like:
```python
from ..... import Quantile
quantile = Quantile(0.5, axis=0)

tensor = torch.tensor([[1, 2], [3, 4], [5, 6], [7, 8]])
quantile(tensor)
>>> [4, 5]
```

**Comment by albanD** [comment] 2019-07-03 08:34
The place to put it I guess is to implement a function in `torch.nn.functional` that performs what you want. Then you can wrap it as a module in `torch.nn`.

I would say it's fine to have non differentiable functions in `nn`, what do you think @soumith ?

**Comment by soumith** [comment] 2019-07-04 03:15
I want to see a fuller proposal for metrics that expands on what metrics **need** to be metrics instead of loss functions in `torch.nn.functional`. Adding a namespace and a full package into PyTorch core is possible, but the onus of proving that it needs to be in core, and it's design aspects need to be more like a fully fleshed [PEP](https://www.python.org/dev/peps/) at this stage rather than a short description.

I think a lot (or a significant) amount of metrics actually belong in `torchvision`, `torchtext` and `torchaudio`, and whatever are supposed to be generic metrics probably have a strong case to be differentiable (but I get it, there are non-differentiable metrics as well).

**Comment by kaszperro** [comment] 2019-07-04 08:36
It'd take some time to write full proposal, but for now I'd like to propose some ideas and hear your opinion.

1. It should have functionality for accumulating measurements. Imagine we have huge dataset, and we can't feed it all into memory, so we need some function for giving it batches of data and when we are finished, call some function like `.get()` to receive our metric, for all the data. For example:
```python
r_squared = RSquaredMetric()
for model_out, target_data in zip(model_outs, targets):
   r_squared.accumulate(model_out, target_data)
correlation_matrix = r_squared.get()
```
2. It should automatically not accumulate gradients and not track history of operations. Probably calling `with torch.no_grad()` internally will be okay for now.

3. In my opinion implementing them in losses, wouldn't be ideal because for some or most of them, you can't call .backwards(), and hardly anyone would use them for training purposes.

**Comment by albanD** [comment] 2019-07-04 09:00
What you present looks quite similar to the meters in tnt [here](https://tnt.readthedocs.io/en/latest/source/torchnet.meter.html) with new types of metrics.
Is there a key feature missing from the meter that you're looking for?

**Comment by kaszperro** [comment] 2019-07-04 09:37
I'm sorry but I know about existence of [tnt](https://tnt.readthedocs.io/en/latest/index.html) since you mentioned it two days ago. And now, after brief reading of its documentation, I thing that its meters package meets my needs, since it provide accumulating batched data functionality.

But there are only few (really few) meters available. And none of them probably is useful to me. So now I think, we need to implement more of them, including some losses from PyTorch (MSE, ...) and more.

**Comment by fmassa** [comment] 2019-07-04 11:52
Check ignite, it is more feature complete and maintained

https://github.com/pytorch/ignite

**Comment by varunagrawal** [comment] 2019-07-06 22:06
I was thinking about this recently as well and came across something [similar in Tensorflow](https://www.tensorflow.org/api_docs/python/tf/metrics).

I believe the idea is to have metrics such as mAP, precision (at k), nDCG etc., easily available and with strong GPU and multi-dimensional tensor support, so that there is less reinventing of the wheel and users don't get hit by bugs when trying to implement multi-dimensional versions of them.

Perhaps extending ignite's metrics module is the right way to go? Thoughts?

**Comment by kaszperro** [comment] 2019-07-08 07:03
@varunagrawal that's exactly the idea. 

I believe extending ignite's metrics, is what PyTorch members want. And I might be wrong, but I still don't know why should it be in separate project, as almost everyone using PyTorch, want to evaluate model accuracy.

**Comment by ezyang** [comment] 2019-07-08 17:20
@jeffreyksmithjr says that this issue has been filed multiple times. It's common in analogous libraries; it's a weird user experience that we don't have these metrics out of the box. (And it may become a requirement for some of our internal requirements.) We (in PyTorch core) may need to step up and do the design work for something like this. (In terms of internal priority, this might come after having non-neural network baseline models working in PyTorch.)

@fmassa says, if we can find someone to work on this, that would be great. But it will take some time to come up with a good design (echoing what @soumith said). Moving ignite metrics into PyTorch core is definitely a good idea; it's just not clear that ignite's design is stabilized to the extent that we can actually do this.

**Comment by jeffreyksmithjr** [comment] 2019-07-08 18:21
I continue to feel that the omission of metrics is just a hole in our feature set that should be filled. But I totally agree that some metrics belong in domain libraries (torchvision, etc.) and some belong completely outside of PT. There is some base level of functionality that I think could make a lot of sense for us to provide us the batteries obviously worthy of including.

Beyond the concerns of mine that @ezyang transcribed above, I would call out that we're increasing the amount of staffing of folks who are expected to produce materials like tutorials. Not having even basic metrics built in creates yet more weird devX for tutorial authors. In my book on machine learning systems, I always relied upon first-party library implementations of metrics to demonstrate any concept other than the single section where the reader was learning how to implement metrics code. It's just more comprehensible for a user to not need a whole separate component to check the performance of their trained model.

That said, I don't have strong feelings about how we would structure such a solution. I think we could try to ensure a level of modularity, if it was deemed valuable, so long as we eventually pointed users to something that didn't introduce a lot of new cognitive overhead (which I would argue that tnt and ignite do if you're literally only trying to call a single function like `.precision()` or whatever). 

I'll take responsibility for seeing if we can find an internal team member who could at least get us to a draft design that made sense to discuss. Low detail issues like this one tend to not really move the conversation more. We need an actual list of metrics to work from.

**Comment by varunagrawal** [comment] 2019-07-09 18:02
@jeffreyksmithjr @ezyang I would be more than happy to help with the implementation.

**Comment by kaszperro** [comment] 2019-07-09 20:25
@ezyang @jeffreyksmithjr I'm also willing to help.

**Comment by ezyang** [comment] 2019-07-10 02:11
I guess what should happen now is someone puts together some sort of
initial proposal, with reference to the existing out-of-PyTorch
implementations, and then we talk about it :)

Excerpts from Kasper Sapała's message of 2019-07-09 13:26:31 -0700:
> @ezyang @jeffreyksmithjr I'm also willing to help.
>

**Comment by kaszperro** [comment] 2019-07-11 07:09
@ezyang in what form should it be? As a comment to this issue? What should it contain?

**Comment by ezyang** [comment] 2019-07-15 19:00
A comment to this issue seems like the best format we have right now. I think at a first cut, a fuller description of the APIs that would be added, and some overall description about organization and philosophy, would be good.

**Comment by kaszperro** [comment] 2019-07-16 09:59
### Basic idea
Let me quote @varunagrawal:

> Implement metrics such as mAP, precision (at k), nDCG etc., easily available and with strong GPU and multi-dimensional tensor support, so that there is less reinventing of the wheel and users don't get hit by bugs when trying to implement multi-dimensional versions of them.

It's somewhat wired user experience that you have to write them by hand on import another package (Ignite) to have such a basic functionality. From my experience, I can tell that in pollution forecast, it's essential to measure [numpy corrcoef](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html) to check correlation between model output and target (measured) output, and I had to implement it by my self to allow batch accumulation and GPU support.
As you guys have already implemented many metrics in Ignite, I think, that it won't be very time consuming. And In my opinion, many users will be pleased to receive metrics in PyTorch, because minority of them know about Ignite package.

### Other Libraries
- ### Tensorflow (v 1.x)
In Tensorflow there is [metrics](https://www.tensorflow.org/api_docs/python/tf/metrics) package. All of metrics return two operations: first to calculate metric output, second to update metric (ex. accumulate over batches). 
Let's look at some code (based on [this tutorial](http://ronny.rest/blog/post_2017_09_11_tf_metrics/))
```python
# Placeholders to take in batches of data
tf_label = tf.placeholder(dtype=tf.int32, shape=[None])
tf_prediction = tf.placeholder(dtype=tf.int32, shape=[None])

# Define the metric and update operations
acc_metric, acc_metric_update = tf.metrics.accuracy(tf_label,
                                                      tf_prediction,
                                                      name="acc_metric")
```
`tf.metrics.accuracy` computes: `num_correct/num_items`. It creates two hidden variables, which accumulates num_correct and num_items. 

That's how to update metric:
```python
for i in range(n_batches):
        # Update the running variables on new batch of samples
        feed_dict={tf_label: labels[i], tf_prediction: predictions[i]}
        session.run(acc_metric_update, feed_dict=feed_dict)
```

Now we can actually compute our acc_metric:

```python
score = session.run(acc_metric)
``` 
---
Because Tensorflow uses static graphs, it's a bit complicated, we have to use sessions. 
But we can see that they only needed to operations: calculate metric, accumulate metric. It's also possible to reset metric state, by getting variables created by a metric and resetting them:
```python
# Get variables created by metric
running_vars = tf.get_collection(tf.GraphKeys.LOCAL_VARIABLES, scope="acc_metric")

# Define initializer to initialize/reset running variables
running_vars_initializer = tf.variables_initializer(var_list=running_vars)

# Reset variables
session.run(running_vars_initializer)
```
- ### Tensorflow (v 2.x)
As Tensorflow 2.0 is stil in beta stage, this (probably?) can change slightly. But for now each metric provide three methods (metrics are classes from now one):
- `reset_states()` resets all of the metric state variables,
- `result()` computes metric,
- `update_state(...)` accumulates metric statistics

Let's look at [Accuracy metric](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/metrics/Accuracy) as before but from the Tensorflow 2.x perspective:
```python
# Define metric as a class
m = tf.keras.metrics.Accuracy()
for i in range(n_batches):
        # Update the metrics on new batch of samples
        m.update_state(labels[i],  predictions[i])

# Get accuracy:
m.result().numpy()
>>> 0.99
```
---
In my opinion, PyTorch's metrics should be implemented in similar way as the Tensorflow's 2.x are. 
So each Metric is a Class with three methods. 
I believe that Ignite metrics work in a similar fashion as the Tensorflow ones, so I do not intend to quote them here, as you know much better how they are constructed.

### Summary
After looking at other libraries, and from my experience, I came to conclusion that there should be new package called: `torch.metrics`. It's base class should contain three methods:
- `reset()` resets current state
- `accumulate(*args, **kwargs)` accumulate metric statistic
- `compute()` compute metric result and return Tensor(s) with data.

It is not necessary for Metric to accumulate gradients, nor remember operations history. But it needs deeper look whether to implement it as `with torch.no_grad()` or should user call `with torch.no_grad()` before calling `accumulate` or other ideas.

There is also a matter of which device to use for computations. Maybe there should be another method or constructor parameter, which will set device for all contained Tensors? Something like `.to()` know from `nn.Module`? It also could be done on first `.accumulate()` call, depending on given Tensor's devices.

I'm happy contribute, and have already prototyped [numpy corrcoef](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html) and [numpy cov](https://docs.scipy.org/doc/numpy/reference/generated/numpy.cov.html#numpy.cov) equivalents. 
```python
class CovMetric:
    def __init__(self):
        self.x_mean = 0
        self.c = 0
        self.n = 0

    @staticmethod
    def __concat_input(x, y, rowvar):
        if not rowvar and x.shape[0] != 1:
            x = x.t()

        if y is not None:
            if not rowvar and y.shape[0] != 1:
                y = y.t()

            x = torch.cat((x, y), dim=0)

        return x

    def reset(self):
        self.x_mean = 0
        self.c = 0
        self.n = 0

    def accumulate(self, x, y=None, rowvar=True):
        x = self.__concat_input(x, y, rowvar)
        self.n += x.size(1)

        xs = torch.sum(x, 1).unsqueeze(-1).expand_as(x)

        new_mean = self.x_mean + (xs - self.x_mean * x.size(1)) / self.n

        m1 = torch.sub(x, new_mean)
        m2 = torch.sub(x, self.x_mean)

        self.c += m1.mm(m2.t())
        self.x_mean = new_mean

    def compute(self):
        return self.c / (self.n - 1)


class CorrcoefMetric:
    def __init__(self):
        self.cov = CovMetric()

    def reset(self):
        self.cov.reset()

    def accumulate(self, x, y=None, rowvar=True):
        self.cov.accumulate(x, y, rowvar)

    def compute(self):
        c = self.cov.compute()
        # normalize covariance matrix
        d = torch.diag(c)
        stddev = torch.sqrt(d)
        c /= stddev[:, None]
        c /= stddev[None, :]

        return torch.clamp(c, -1.0, 1.0)


if __name__ == '__main__':
    N = 1024
    M = 100
    batch_size = 64
    mat1 = torch.rand((N, M), dtype=torch.float64)
    mat2 = torch.rand((N, M), dtype=torch.float64)

    cor = CorrcoefMetric()

    for i in range(N // batch_size):
        cor.accumulate(
            mat1[i * batch_size:(i + 1) * batch_size, ],
            mat2[i * batch_size:(i + 1) * batch_size, ],
            False
        )

    accumulated_cor = cor.compute().numpy()
    numpy_cor = np.corrcoef(mat1.numpy(), mat2.numpy(), False)
    print(np.allclose(numpy_cor, accumulated_cor))

>>> True
```

**Comment by prasunanand** [comment] 2019-07-30 13:02
Is anyone working on it ?

**Comment by varunagrawal** [comment] 2019-07-30 13:46
@prasunanand I believe the consensus right now is to first come up with a proposal for this subpackage. This will be taken care of by someone on the Pytorch internal team, and after an initial setup is when we can start adding things.

**Comment by kaszperro** [comment] 2019-12-01 23:43
So is there any progress with this issue internally?

**Comment by ezyang** [comment] 2019-12-03 15:44
No, there has not been so far.

**Comment by ezyang** [comment] 2019-12-13 01:56
@hanfang wrote a note internally which I'm sharing with everyone here:

----

Hi, I was chatting with @NarineK  regarding the basic metrics functionality from the Pytorch core lib. It turns out we don't seem to have any. The closest module is the one from ignite.

There have been some discussions on a Github issue, but it doesn't seem like we have a plan around whether/how to do this. 

### HOW ARE PEOPLE DOING THIS TODAY?
A common pattern internally at FB is that people mostly use scikit-learn's metrics module to quickly calculate the metrics of interest. Other users also rely on (internal library)'s built-in metrics which is actually written on top of scikit-learn as well.

### WHY DO WE NEED THIS?
Today it feels odd to rely on other third-party library or one will have to do a lot of the customization to compute these model metrics. More imporantly, this will likely offer strong GPU and multi-dimensional tensor support (less error-prone and much faster). From an ecosystem standpoint, this also make it feel incomplete and sub-optimal from a user-experience perspective. When we do have the metrics modules in the Pytorch core lib, I will guess that will increase the adoption of Pytorch as well.

### PROPOSED METRICS
It would be super useful to have some common metrics to model evaluation, with native Pytoch support, so that users (internal/external) can just do something like

```
from torch.metrics import precision_recall_curve

pr_curve = precision_recall_curve(...)
```

Classification metrics

```
accuracy_score 
auc 
average_precision_score balanced_accuracy_score
brier_score_loss
confusion_matrix 
dcg_score 
f1_score
log_loss
multilabel_confusion_matrix
precision_recall_curve 
precision_score
recall_score
roc_auc_score 
roc_curve 
etc
```

Regression metrics

```
explained_variance_score 
mean_absolute_error   
mean_squared_error   
median_absolute_error 
r2_score
etc
```

This has been a (unexpected) long post. Is the Pytorch team planning on investing in this area in 2020? Thanks.

**Comment by ezyang** [comment] 2019-12-13 02:39
@Darktex adds:

----

200% agree. Having reference implementations for metrics also guarantees that different systems (at FB but also outside, across research) can always be comparable, without worrying of eg corner cases, or minor details.

I am in the middle of this right now as I'd like to compare a server model with a on-device model (on the MobileVision platform). Sklearn doesn't contain *a lot* of the metrics we routinely use. For example, ROC AUC does not work in the multiclass case out of the box. Do we do 1 vs all, and then we micro average? Or macro average? What's the right default?

When you compute Recall@Precision K, you'll have only a bunch of points depending on the classifier and on how many data samples. Maybe I have a value for Recall@Precision 0.79, and another @Precision @0.83. How do I compute the value @Precision 0.80? Do I interpolate, do I pick the lower bound, or do something else?

Our internal library implemented these and made some implementation choices along the way, but the lack of a reference implementation (with good documentation of those choices) is an obstacle for reproducibility

----

One more thing (long comments, sorry lol) that may not be obvious is that I would recommend for a bigger API than the sklearn drop-in that you recommended (and that is the most natural starting point)! I think that a metric object should not only expose how its value is computed, but also how it wants to be printed, and when. There is a ton of boilerplate code there that would be really nice to uniform once and for all.

I took a stab at this in Multimo (not published yet), building on top of the Ignite metrics. While I'm not very happy with the solution there (having to stick to Ignite limited what I could do...), maybe it's a good starting point.

Multimo metrics have a pretty_print method for terminals, and a visualize method for more capable outputs such as notebooks. This allows Multimo to print a confusion matrix as a bunch of tab-spaced text when launched via terminal, and to show a density-colored Plotly confusion matrix whose cells are clickable, etc when in notebooks.

Oh, and the metric computation function should really be parallelization-friendly. If I have 8 GPUs, or 128, I should be able to compute my metrics.

(Of course, maybe torch should really just contain sklearn-style implementations and we box them somewhere else, just saying that we may want to think about this)

**Comment by gchanan** [comment] 2019-12-13 16:29
It looks like there are really two different things being discussed here:
1) providing more metric calculations, under a common package.
2) tools for tracking/updating statistics in an online manner.

Sometimes these are combined (e.g. in tf2 example above), although I'm not really sure why.

**Comment by Darktex** [comment] 2019-12-17 20:38
I think splitting them up is the better idea.

I would shoot for something along these lines:

1. `torch.metrics` which should be a package which essentially just reimplements what we have in `sklearn.metrics` in a purely functional manner. I would say that this need not be parallelizable.
2. An external package `cool_metrics` that packs those implementations into objects. I would propose that it does the following: 
    1. Class hierarchy that marks what a metric is used for (for example, `ROC AUC` should be a `ClassificationMetric`, and `MSE` should be a `RegressionMetric`). Then we can standardize the API for each of these classes.
    2. Mixin to mark how parallelization is done. What should the Gather do? For example, for `loss` it can just average - but for something like ROC AUC, the only solution is to concat batch outputs and perform the calculation only at the end. There aren't that many parallelization strategies and by writing a few of these mixins we can help the community write more metrics as needed.
    3. Class hierarchy for the output. Is it a number? Is it a table? Is it a plot? Are you on a command-line terminal, are you in a Jupyter Notebook, are you running in a server with logs, or on TensorBoard etc etc. We could define what to print based on these once and for all.

Trainer libraries such as Lightning and Ignite could then just leverage `cool_trainer` and they would be the ones responsible for the control flow: how often to call them, what events to attach them to, etc.

**Comment by kaszperro** [comment] 2019-12-17 21:08
It makes sense. 
But what do you mean by "external package"? Package outside of PyTorch completely ex: separate repo?

**Comment by arita37** [comment] 2019-12-23 09:17
@kaszperro  @Darktex   @gchanan 

Am working on this one...
pip install metric
https://pypi.org/project/metric/

metric.WHATeverMetric_In_numpy_style_syntax(y_true, y_pred,..)

If anybody interested, we can discuuss

**Comment by Darktex** [comment] 2020-01-07 02:40
Hi @arita37 ! I don't see the source for that package in your GitHub (I found [this](https://github.com/arita37/metric), but there is no code!), would you mind sharing it with us? :)

**Comment by arita37** [comment] 2020-01-07 03:28
Thanks for replying.
This is under dev branch.

Am in middle of design/scope thinking....
If community can provide some comments,
It would be nice:


Goal : Compute metrics from inputs.
Syntax:  numpy/ sklearn style
    metric.WhatEverMetric(y_true, y_pred, y_pred_proba,...)

Scope :
    Numpy input
    Pytorch tensor (????)
    Tensorflow...


Maintenance/Dependance :
    sklearn, pandas, numpy, scipy
    Others (???)



Tricky part is to have one single package
acrosss platform ....

**Comment by brightening-eyes** [comment] 2020-01-19 19:39
hi,
look at mxnet's metric package
their design might help implementing such thing in pytorch.

**Comment by williamFalcon** [comment] 2020-02-12 16:01
@Darktex are you thinking we enable this in lightning? How would that look for you? We could add a flag called metrics or something and we'd call at the right times.

but maybe i'm not understanding, it seems like you just want to import this package and call at the end of your training_step or validation_step?

**Comment by Darktex** [comment] 2020-02-29 00:29
Reviving this thread to cross-link to the issue on Lightning [here](https://github.com/PyTorchLightning/pytorch-lightning/issues/973) and to spur more discussion. Let's take Lightning as an example of a library on top of PyTorch that might want to handle some wrapping for the pretty printing. This would align well with the [proposal](https://github.com/pytorch/pytorch/issues/22439#issuecomment-566739274) I wrote a few comments above. I like reasoning from more concrete stuff, so let me try to refine that proposal in a more concrete manner (I am not married to anything here, I think it just helps ground things).

1. Treat metrics as a subtype of `nn.Module`? We do that for [cost functions](https://pytorch.org/docs/stable/_modules/torch/nn/modules/loss.html), it seems good practice to do that for metrics too - the extra caveat would be that they are not differentiable. See later paragraph for a more detailed discussion on this.
2. The sklearn replacement would probably live in `F` as usual, so eg `nn.metrics.F1Score` will eventually call `F.f1_score`
3. The pretty printing, metrics reporting etc lives outside of PyTorch in client libs, for example Lightning.

The biggest question I have is whether we can find a way to support computing metrics nicely once we factor in DDP in a way that is completely independent. I like [how Ignite is doing it](https://pytorch.org/ignite/metrics.html#metrics-and-distributed-computations) and I would consider starting from their API for the one in PyTorch (potentially taking the implementation too and decoupling it from the Ignite specifics so everyone can use it!).

Here's a primer from their API:

```python
class Metric(metaclass=ABCMeta):
    _required_output_keys = ("y_pred", "y")

    def __init__(self, output_transform=lambda x: x, device=None):
        self._output_transform = output_transform

        # Check device if distributed is initialized:
        if dist.is_available() and dist.is_initialized():

            # check if reset and update methods are decorated. Compute may not be decorated
            if not (hasattr(self.reset, "_decorated") and hasattr(self.update, "_decorated")):
                warnings.warn("{} class does not support distributed setting. Computed result is not collected "
                              "across all computing devices".format(self.__class__.__name__),
                              RuntimeWarning)
            if device is None:
                device = "cuda"
            device = torch.device(device)
        self._device = device
        self._is_reduced = False
        self.reset()

@abstractmethod
    def reset(self):
        """
        Resets the metric to it's initial state.

        This is called at the start of each epoch.
        """
        pass


@abstractmethod
    def update(self, output):
        """
        Updates the metric's state using the passed batch output.

        This is called once for each batch.

        Args:
            output: the is the output from the engine's process function.
        """
        pass


@abstractmethod
    def compute(self):
        """
        Computes the metric based on it's accumulated state.

        This is called at the end of each epoch.

        Returns:
            Any: the actual quantity of interest.

        Raises:
            NotComputableError: raised when the metric cannot be computed.
        """
        pass

```
Source: [ignite.metrics.metric](https://pytorch.org/ignite/_modules/ignite/metrics/metric.html). 

To make them amenable to DDP, they use decorators to mark what they do during `all_reduce` and after it. To see a minimal implementation, take a look at their implementation of [Recall]:(https://pytorch.org/ignite/_modules/ignite/metrics/recall.html#Recall).

Another good thing that Ignite does very well here is making it easy for others to write their own DDP-compatible metrics without dealing with the DDP internals themselves. For example, take a look at the  [VariableAccumulation](https://pytorch.org/ignite/_modules/ignite/metrics/accumulation.html#VariableAccumulation) metric which is a parent/mixin that can bootstrap other concrete metrics such as [`GeometricAverage`](https://pytorch.org/ignite/_modules/ignite/metrics/accumulation.html#GeometricAverage).

For the sake of argument, let's say our metrics package looks exactly the same as Ignite's. The next question is how we are going to use it: Ignite is events-based so they just declare what metrics they want and stuff happens behind the scenes eg `evaluator = create_supervised_evaluator(model, metrics={'accuracy': Accuracy(device=device)}, device=device)`. The major difference with us is that we'd want users to have much more control about how they are going to use these.

Let's write a sample eval loop:

```python
macro_f1 = nn.F1Score("macro")

with torch.no_grad():
    for x, y in eval_dataloader:
        x_hat = F.softmax(model(x), dim=-1)
        macro_f1.update(x_hat, y)  # void method, just update state
        m = macro_f1()  # forward calls compute(), takes no args. Compute from state

        print(f"Macro f1: {m.item()}")  # or whatever else you want to do
```
With DDP, maybe this still works - normally we don't need to pass the loss through `torch.nn.DistributedDataParallel`. Worst case let's say we do, this is still not too bad:

```python
macro_f1 = nn.F1Score("macro")

torch.distributed.init_process_group(backend='nccl', world_size=4, init_method='...')
model = DistributedDataParallel(model, device_ids=[i], output_device=i)
macro_f1 = DistributedDataParallel(macro_f1, device_ids=[i], output_device=i)

with torch.no_grad():
    for x, y in eval_dataloader:
        x_hat = F.softmax(model(x), dim=-1)
        macro_f1.update(x_hat, y)  # void method, just update state
        m = macro_f1()  # forward calls compute(), takes no args. Compute from state

        print(f"Macro f1: {m.item()}")  # or whatever else you want to do
```

This is flexible, because we leave the responsibility of updating state and computing in the hands of the client, so they can do however they please. This will not limit researchers, actually quite the opposite: it will liberate them from writing metrics code that is unsexy and hard to do efficiently (for example on DDP). Trainer libraries can then do further magic by using events to update and compute for you at the right time.

Any feedback?

**Comment by kaszperro** [comment] 2020-03-03 14:58
That looks really nice. 
I like freedom that it provides and separation Model from Metrics (unlike lightning, which combines model with evaluation). 

And as I understand, sklearn functions replacement would be useful for small datasets, in which you don't have to accumulate state, because everything fits into memory, potentially increasing performance?

**Comment by Darktex** [comment] 2020-03-03 21:31
Yes, and we can factor out components as needed so that they share as much code as possible

**Comment by netw0rkf10w** [comment] 2020-04-14 22:55
> Let's write a sample eval loop:
> 
> ```python
> macro_f1 = nn.F1Score("macro")
> 
> with torch.no_grad():
>     for x, y in eval_dataloader:
>         y_hat = F.softmax(model(x), dim=-1)
>         macro_f1.update(y_hat, y)  # void method, just update state
>         m = macro_f1()  # forward calls compute(), takes no args. Compute from state
> 
>         print(f"Macro f1: {m.item()}")  # or whatever else you want to do
> ```
> 
> With DDP, maybe this still works - normally we don't need to pass the loss through `torch.nn.DistributedDataParallel`. Worst case let's say we do, this is still not too bad:
> 
> ```python
> macro_f1 = nn.F1Score("macro")
> 
> torch.distributed.init_process_group(backend='nccl', world_size=4, init_method='...')
> model = DistributedDataParallel(model, device_ids=[i], output_device=i)
> macro_f1 = DistributedDataParallel(macro_f1, device_ids=[i], output_device=i)
> 
> with torch.no_grad():
>     for x, y in eval_dataloader:
>         y_hat = F.softmax(model(x), dim=-1)
>         macro_f1.update(y_hat, y)  # void method, just update state
>         m = macro_f1()  # forward calls compute(), takes no args. Compute from state
> 
>         print(f"Macro f1: {m.item()}")  # or whatever else you want to do
> ```

Very nice! This is exactly what should be done!

**Comment by kaszperro** [comment] 2020-04-15 07:59
So now we have everything ready to start? 
As I understand, the steps: 
1. Implement as many metrics as possible in torch.nn.functional
2. Implement metrics using Ingite's API in torch.nn?

@Darktex proposed to put metrics in torch.nn:
But shouldn't metrics be separated from torch.nn, ex: torch.nn.metrics or torch.metrics?
They could be subclass of torch.nn.Module, but if they were put directly into torch.nn, it'd cause confusion and mix-up imo. 
I thing that they are different enough, that they deserve separate module
I cloud be wrong though.

**Comment by netw0rkf10w** [comment] 2020-04-15 17:04
I don't think the metrics should be separated from `nn`.

In `tf.keras` they have `tf.keras.metrics`, similar to `tf.keras.losses` or `tf.keras.optimizers`, but note that in PyTorch there's no `torch.nn.losses`.

Everything is inside `nn` (`nn.CrossEntropyLoss` is a loss, `nn.Conv2d` is a layer), so in my opinion, it makes more sense (and is less confusing) to do `nn.MeanIoU()` instead of `torch.metrics.MeanIoU()` (and `torch.nn.metrics.MeanIoU()` is even worse). 

(You may ask: Then why do we have `torch.optim.SGD` instead of `torch.nn.SGD`? I have no idea.)

For the implementation, it'd be obvious that the metrics should be implemented in a new `torch.nn` [module](https://github.com/pytorch/pytorch/tree/master/torch/nn/modules), and similar to the [losses](https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/loss.py), all metrics will derive from some `class _Metric(Module):`.

**Comment by soumith** [comment] 2020-04-29 16:11
1. Metrics should be different from `torch.nn`, because they are not differentiable
2. Metrics needs to fluidly interact with `torch.distributed`, and hence often in non-trivial ways with the training loop.

The APIs for a metrics package, especially because of (2), are not obvious.
Both 1 and 2 makes it nicer to have a separate metrics package that can eventually stabilize and come into core pytorch

**Comment by Raikan10** [comment] 2020-05-17 19:09
Hi, I'm a student who is a beginner at Pytorch but I understand what you guys are trying to do here. This comes from personal experience in that when I started the MNIST tutorial it was kind of weird I had to calculate accuracy myself. Thus I would love to help out, hopefully under some kind of mentorship!

**Comment by mruberry** [comment] 2020-05-18 02:18
Thanks @Raikan10! We'll post here as there are developments. If you're interested in contributing to PyTorch generally then you could also check out issues with the "OSS contribution wanted" label. See this query: https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22oss+contribution+wanted%22.

**Comment by williamFalcon** [comment] 2020-05-18 11:14
@Raikan10 for the metrics package we are looking for help with some metrics in lightning. good place to start!
ping @justusschock on the lightning slack

**Comment by arita37** [comment] 2020-05-20 01:37
@Southmith :

Interesting remarks.
Maybe, one can identify more in details
the couplings of metrics with core training

dataset : different from training
Compute:
    only forward pass ?
    Aggregation : distribution
    Callback ?

training time usage : 
  Scheduler, state of NN

**Comment by WeirdKeksButtonK** [comment] 2020-05-31 10:52
I definitely agree that `ignite.metrics` is an excellent package. I would like to share some thoughts on Ignite's [Accuracy](https://pytorch.org/ignite/metrics.html#ignite.metrics.Accuracy). There are two points that probably should be addressed while implementing `Accuracy` in a hypothetical `torch.metrics`:

#### Inconsistent input format for binary classification and multiclass problems
In the first case, Ignite's Accuracy expects labels as input, whilst in the second case it expects probabilities or logits. It was a big point of confusion to me.

#### No shortcuts for saying "I want to pass logits/probabilities as input"
Fundamentally, Accuracy is a metric that takes predicted and correct labels as input and returns the percentage of correct predictions as output. However, in practice neural networks trained for classification often return logits or probabilities. For example, in the case of binary classification, I have **never** written the following:
```python
accuracy = Accuracy()
```
Instead, I always have to write:
```python
accuracy = Accuracy(transform=lambda x: torch.round(torch.sigmoid(x)))
# either
accuracy = Accuracy(transform=lambda x: torch.round(x))
```

_Suggested solution for both problems:_ let the user explicitly say in which form input will be passed:
```python
import enum
class Accuracy(...):
    class Mode(enum.Enum):
        LABELS = enum.auto()
        PROBABILITIES = enum.auto()
        LOGITS = enum.auto()

    def __init__(self, mode=Mode.LABELS, ...):
        ...
```
The suggested interface can be also extended to support custom thresholds by adding the `__call__` method to the `Mode` class.

Yes, the `mode` argument serves as one more `transform` argument (see the original Ignite Accuracy). However, my hypothesis is that this shortcut will cover so many use cases and will make user code so much more expressive, that it may worth it.

cc: @vfdev-5

**Comment by vfdev-5** [comment] 2020-05-31 11:26
@WeirdKeksButtonK this can be a nice enhancement for Ignite as well. Please, open an issue in Ignite repository.

@soumith `ignite.metrics` module is rather stable can be a reference for a potential future `torch.metrics` module.

> The major difference with us is that we'd want users to have much more control about how they are going to use these.

@Darktex you do have also the same control of that in ignite with almost the same API : 
```python
metric = ...
metric.reset()
for _ in range(n):
    metric.update(y_pred, y)
result = metrics.compute()
```

Another point is about distributed package, currently native torch distributed supports only nccl, gloo, mpi backends. For users playing with XLA, aggregating methods should be readapted.

**Comment by chinokenochkan** [comment] 2020-11-03 19:23
https://github.com/chinokenochkan/torch-metrics

**Comment by chinokenochkan** [comment] 2020-11-03 20:02
https://github.com/chinokenochkan/torch-metrics

Feel free to suggest more metrics/ contributions are welcome!

**Comment by francois-rozet** [comment] 2021-01-10 23:07
For those who are interested, I have implemented a package of IQA metrics:
https://github.com/francois-rozet/piqa

**Comment by edenlightning** [comment] 2021-03-23 23:56
Check out https://github.com/PyTorchLightning/metrics!
Over 25 implementations and a simple API to build your own metric, optimized for distributed training!

**Comment by arita37** [comment] 2021-03-24 00:46
@edenlightning

Thanks
What about end to end sparseTensors support ?
Tzhx

**Comment by ezyang** [comment] 2021-08-12 18:09
For those following along, there is now a third-party torchmetrics package that may be helpful https://torchmetrics.readthedocs.io/en/latest/

**Comment by ananthsub** [comment] 2022-11-04 22:46
Closing this issue out since [torchmetrics](https://torchmetrics.readthedocs.io/en/latest/) and [torcheval](https://pytorch.org/torcheval/main/) fill this need now

**Closed by ananthsub** 2022-11-04 22:46 UTC
Labels: feature, triaged, module: numpy, quansight-nack
