### ISSUE TITLE
Autograd view CreationMeta are not properly propagated when chaining views

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#36608] opened 2020-04-14 20:31 UTC
```
In [3]: root = torch.arange(9.).reshape(3, 3).requires_grad_()

In [4]: x = root.clone()

In [5]: v1 = x.unbind()

In [6]: v1[0].mul_(2)
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-6-c912e1d6e469> in <module>
----> 1 v1[0].mul_(2)

RuntimeError: Output 0 of UnbindBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.

In [7]: v2 = v1[0].narrow(0, 0, 2)

In [8]: v2.mul_(2)
Out[8]: tensor([0., 2.], grad_fn=<AsStridedBackward>)

In [9]: v2.sum().backward()

In [10]: root.grad
Out[10]:
tensor([[2., 2., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
```
Note that while `v1` is correctly banned, `v2` (which is an inplace update on view) still successfully backward through output of `unbind`

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen

**Comment by vadimkantorov** [comment] 2020-04-14 21:08
I think, related: https://github.com/pytorch/pytorch/issues/31819

**Comment by albanD** [comment] 2020-04-15 14:47
I guess the one way to fix this would be to properly propagate the CreationMeta based on the input to the view op. Not sure how to properly do that. Maybe we should change the CreationMeta into a bitfield so that it can have multiple states at a time?

**Comment by ailzhang** [comment] 2020-04-15 16:31
@albanD Yea a similar idea would be we say `CreationMeta::MULTI_OUTPUT_NODES` has higher pri, so once it appears in the view chain, the final view should carry this instead of its own `CreationMeta`. 
So it could be we check `base_var`'s `CreationMeta` before going down to root base, and potentially passing that down to `make_variable_differentiable_view`.

**Comment by albanD** [comment] 2020-04-15 16:52
Yes.
But what should be the priority compared to https://github.com/pytorch/pytorch/blob/9cac2b83d9e6838de796e0cecfbacaa6a64dc6a8/torch/csrc/autograd/custom_function.cpp#L118-L126 for example?
It feels like we need a slightly more general framework here to make sure we can easily handle all of these and raise the proper error when needed.

**Comment by albanD** [comment] 2020-07-29 15:24
Bumping priority so that we don't forget about this as it is a correctness issue (you can get silently wrong gradients).

**Comment by jbschlosser** [comment] 2021-03-05 16:32
@albanD Is this the same issue as #49824?

Now that the fix for the above is in, I can't reproduce the problem:
```python
import torch

root = torch.arange(9.).reshape(3, 3).requires_grad_()
x = root.clone()
v1 = x.unbind()
v2 = v1[0].narrow(0, 0, 2)
v2.mul_(2)  # errors out as it should
v2.sum().backward()
print(root.grad)
```
```
RuntimeError: Output 0 of SliceBackward is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.
```

**Comment by albanD** [comment] 2021-03-05 16:52
Yes that's the same. It is fixed now!

**Closed by albanD** 2021-03-05 16:52 UTC
Labels: high priority, module: autograd, triaged
