### ISSUE TITLE
Allow register_buffer for non-Tensor attributes (e.g. TorchBind objects)

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#51228] opened 2021-01-27 19:30 UTC
## 🚀 Feature
Support more data types in register_buffer.

## Motivation

Currently register_buffer only supports registering Tensor objects: https://github.com/pytorch/pytorch/blob/master/torch/nn/modules/module.py#L270, however in quantized models we may also need to register packed params (TorchBind objects) as buffer values so that it shows up in state_dict.

Not sure if this has been discussed or not, but would like to know the plan.

## Pitch

```
module.register_buffer("torchbind_obj", torchbind_obj)
```
```
print(module.state_dict())
```
# torchbind_obj will show up in state_dict

## Additional context

cc @albanD @mruberry @jbschlosser

**Comment by albanD** [comment] 2021-01-27 21:02
Hi,

Why do you need these to be buffers and not just plain attributes to the Module?

**Comment by jerryzh168** [comment] 2021-01-27 21:06
> Hi,
> 
> Why do you need these to be buffers and not just plain attributes to the Module?
> Is it just about the state dict? Or also moving across dtype/devices?

yeah we need that because only buffers show up in state_dict and we would like to serialize the model with torch.save(model.state_dict())

**Comment by jbschlosser** [comment] 2021-01-27 21:20
> not sure about your comment on dtype/devices, we probably won't change dtype/devices for these buffers

There's one other main feature of buffers besides being added to the `state_dict`. When calling e.g. `m.to(torch.float64)` or `m.to(torch.device('cuda:0'))` on a module, its buffers will be moved across dtypes / devices.

Sounds like this isn't relevant for TorchBind objects in buffers- is that correct?

**Comment by albanD** [comment] 2021-01-27 22:12
I don't think we want to add as buffers objects that don't support being moved to different device.

If you only want to add things to the state dict, we also provide state dict hooks for you to add arbitrary data to the state dict and load them accordingly with a pre load state dict hook.
Not sure why these are not public btw :D

**Comment by jerryzh168** [comment] 2021-01-28 00:12
> Sounds like this isn't relevant for TorchBind objects in buffers- is that correct?

yeah that is correct.

**Comment by jerryzh168** [comment] 2021-01-28 00:23
> I don't think we want to add as buffers objects that don't support being moved to different device.
> 
> If you only want to add things to the state dict, we also provide state dict hooks for you to add arbitrary data to the state dict and load them accordingly with a pre load state dict hook.
> Not sure why these are not public btw :D

cc @jamesr66a can TorchBind object be moved to different devices?

OK, state_dict hook should work as well, I'll use that as a workaround.

**Comment by jamesr66a** [comment] 2021-01-28 00:34
> cc @jamesr66a can TorchBind object be moved to different devices?

No, that's not part of the object semantics

> OK, state_dict hook should work as well, I'll use that as a workaround.

I think the issue here is that TorchScript doesn't support these, so maybe forward this to that team

**Comment by jerryzh168** [comment] 2021-01-28 00:53
> I think the issue here is that TorchScript doesn't support these, so maybe forward this to that team

we're calling state_dict on GraphModule model in our use case actually. we will probably manually map these attributes to TorchScript model. would that work?

**Comment by mruberry** [comment] 2021-02-01 07:31
Hey @jerryzh168, thanks for the suggestion. 

One thing that would help this issue is separating the problem from proposed solutions. I think the problem is that there are (Torchbind) objects that are part of an nn.Module that make the module tricky to serialize. Is that correct? If we could repurpose this issue, or file a new issue, that just explained that problem, I think that would help us look at potential solutions. A longer code snippet demonstrating the issue would be very helpful, too.

**Comment by jerryzh168** [comment] 2021-02-01 17:53
TorchBind object is serializable, the problem is that it won't appear in state_dict and we would like to see it in state_dict

**Comment by jerryzh168** [comment] 2021-02-01 17:58
@mruberry a new issue just talking about problem is here: https://github.com/pytorch/pytorch/issues/51471, PTAL

**Comment by albanD** [comment] 2021-02-01 21:16
Closing this issue in favor of the more focused one: #51471

**Closed by albanD** 2021-02-01 21:16 UTC
Labels: feature, module: nn, module: serialization, module: torchbind, triaged
