### ISSUE TITLE
AdamW throwing UnboundLocalError when trying to do a .step()

### ISSUE THREAD

**Issue by constd** [pytorch/pytorch#53543] opened 2021-03-08 20:42 UTC
## 🐛 Bug

On pytorch 1.8 (on miniconda), trying to do a optimizer.step() with `AdamW` results in an UnboundLocalError on line 117 of `[..]/torch/optim/adamw.py`. This occurs if both if I use default `betas` parameter values or set my own during instantiation. I know I have an old CUDA version installed, but. at first glance, it doesn't look like it's a CUDA related error!

## To Reproduce

1. In a standard training loop, try to perform a `.step()`

```Traceback (most recent call last):
  File "train.py", line 175, in main
    train(cfg)
  File "train.py", line 76, in train
    optimizer.step()
  File "[...]/python3.8/site-packages/torch/optim/lr_scheduler.py", line 65, in wrapper
    return wrapped(*args, **kwargs)
  File "[...]/python3.8/site-packages/torch/optim/optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "[...]/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "[...]/python3.8/site-packages/torch/optim/adamw.py", line 117, in step
    beta1,
UnboundLocalError: local variable 'beta1' referenced before assignment
```

## Expected behavior

AdamW should use the default/given beta values, perform an optimization step and for the training loop to continue.

## Environment

Please copy and paste the output from our
```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.4 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: Tesla V100-PCIE-16GB

Nvidia driver version: 440.33.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] pytorch-lightning==1.1.8
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.2                      256  
[conda] mkl-service               2.3.0            py38he904b0f_0  
[conda] mkl_fft                   1.3.0            py38h54f3939_0  
[conda] mkl_random                1.1.1            py38h0573a6f_0  
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.8.0           py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         1.1.8              pyhd8ed1ab_0    conda-forge
[conda] torch                     1.6.0                    pypi_0    pypi
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu102    pytorch
```

**Comment by gchanan** [comment] 2021-03-08 23:34
duplicate of https://github.com/pytorch/pytorch/issues/53354.

**Closed by gchanan** 2021-03-08 23:34 UTC
