### ISSUE TITLE
AOTAutograd fails on simple view/transpose case.

### ISSUE THREAD

**Issue by williamwen42** [pytorch/pytorch#102564] opened 2023-05-30 20:51 UTC
Revealed by minifying the test `pytest ./generated/test_adapter_hub_adapter_transformers.py -k test_115` from https://github.com/pytorch/pytorch/issues/92670.

### Repro
```python
import torch
import torch._dynamo

class Good1(torch.nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, x):
        x = x.view((4, 4, -1))
        x = x.transpose(-1, -2)
        x /= 2.0
        return (x,)

class Good2(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(in_features=4, out_features=16, bias=False).cuda()

    def forward(self, x):
        x = self.lin(x)
        x = x.view((4, 4, -1))
        x = x.transpose(-1, -2)
        return (x,)

class Repro(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = torch.nn.Linear(in_features=4, out_features=16, bias=False).cuda()

    def forward(self, x):
        x = self.lin(x)
        x = x.view((4, 4, -1))
        x = x.transpose(-1, -2)
        x /= 2.0
        return (x,)

if __name__ == '__main__':
    inp1 = torch.randn(4, 4, 4, device="cuda")
    torch.compile(Good1())(inp1)

    inp2 = torch.randn(4, 4, device="cuda")
    torch.compile(Good2())(inp2)

    inp3 = torch.rand(4, 4, device="cuda")
    mod = Repro()
    mod(inp3)
    opt_mod = torch.compile(mod)
    opt_mod(inp3)
```

### Error
```
/scratch/williamwen/work/pytorch/torch/autograd/__init__.py:319: UserWarning: Error detected in torch::autograd::CopySlices. Traceback of forward call that caused the error:
  File "playground3.py", line 34, in forward
    x /= 2.0
 (Triggered internally at /scratch/williamwen/work/pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:114.)
  result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "playground3.py", line 48, in <module>
    opt_mod(inp3)
  File "/scratch/williamwen/work/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 287, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 440, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 527, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 127, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 360, in _convert_frame_assert
    return _compile(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 430, in _compile
    out_code = transform_code_object(code, transform)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/convert_frame.py", line 415, in transform
    tracer.run()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2019, in run
    super().run()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 703, in run
    and self.step()
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 663, in step
    getattr(self, inst.opname)(inst)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/symbolic_convert.py", line 2107, in RETURN_VALUE
    self.output.compile_subgraph(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 770, in compile_subgraph
    self.compile_and_call_fx_graph(tx, pass2.graph_output_vars(), root)
  File "/scratch/williamwen/work/torch-env-1/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 847, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 906, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/output_graph.py", line 902, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "/scratch/williamwen/work/pytorch/torch/__init__.py", line 1536, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "/scratch/williamwen/work/pytorch/torch/_inductor/compile_fx.py", line 729, in compile_fx
    return aot_autograd(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 3700, in aot_module_simplified
    compiled_fn = create_aot_dispatcher_function(
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/utils.py", line 180, in time_wrapper
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 3226, in create_aot_dispatcher_function
    compiled_fn = compiler_fn(flat_fn, fake_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2090, in aot_wrapper_dedupe
    return compiler_fn(flat_fn, leaf_flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2270, in aot_wrapper_synthetic_base
    return compiler_fn(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2677, in aot_dispatch_autograd
    fx_g = aot_dispatch_autograd_graph(flat_fn, flat_args, aot_config, fw_metadata=fw_metadata)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 2654, in aot_dispatch_autograd_graph
    fx_g = create_functionalized_graph(
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1376, in create_functionalized_graph
    fx_g = make_fx(helper, decomposition_table=aot_config.decompositions)(*args)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 788, in wrapped
    t = dispatch_trace(wrap_key(func, args, fx_tracer, pre_autograd), tracer=fx_tracer, concrete_args=tuple(phs))
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 287, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 484, in dispatch_trace
    graph = tracer.trace(root, concrete_args)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/eval_frame.py", line 287, in _fn
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/_symbolic_trace.py", line 810, in trace
    (self.create_arg(fn(*args)),),
  File "/scratch/williamwen/work/pytorch/torch/fx/_symbolic_trace.py", line 684, in flatten_fn
    tree_out = root_fn(*tree_args)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 501, in wrapped
    out = f(*tensors)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1365, in joint_helper
    return functionalized_f_helper(primals, tangents)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1318, in functionalized_f_helper
    f_outs = fn(*f_args)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1289, in inner_fn_with_anomaly
    return inner_fn(*args)
  File "/scratch/williamwen/work/pytorch/torch/_functorch/aot_autograd.py", line 1272, in inner_fn
    backward_out = torch.autograd.grad(
  File "/scratch/williamwen/work/pytorch/torch/autograd/__init__.py", line 319, in grad
    result = Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/scratch/williamwen/work/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 550, in __torch_dispatch__
    return self.inner_torch_dispatch(func, types, args, kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 575, in inner_torch_dispatch
    return proxy_call(self, func, self.pre_autograd, args, kwargs)
  File "/scratch/williamwen/work/pytorch/torch/fx/experimental/proxy_tensor.py", line 381, in proxy_call
    out = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_ops.py", line 398, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/williamwen/work/pytorch/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_subclasses/fake_tensor.py", line 1148, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_subclasses/fake_tensor.py", line 1376, in dispatch
    r = func(*args, **kwargs)
  File "/scratch/williamwen/work/pytorch/torch/_ops.py", line 398, in __call__
    return self._op(*args, **kwargs or {})
  File "/scratch/williamwen/work/pytorch/torch/_refs/__init__.py", line 4052, in view
    return _reshape_view_helper(a, *shape, allow_copy=False)
  File "/scratch/williamwen/work/pytorch/torch/_refs/__init__.py", line 3262, in _reshape_view_helper
    raise ValueError(msg)
torch._dynamo.exc.BackendCompilerFailed: backend='inductor' raised:
ValueError: Cannot view a tensor with shape torch.Size([4, 4, 4]) and strides (16, 1, 4) as a tensor with shape (4, 16)!


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Explanation

Compiling and running `Repro` causes the above AOTAutograd error. If we do not compile `Repro`, there are no errors.

Interestingly, if either the linear or the inplace division are removed, then the error does not occur.

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305 @zou3519 @Chillee @samdow @kshitij12345 @janeyx99

**Comment by ezyang** [comment] 2023-05-31 03:57
This is because we contiguified the gradients but didn't convert backwards views into reshapes

**Comment by Chillee** [comment] 2023-05-31 04:14
Aren't we contiguifying during tracing too 🤔

**Comment by bdhirsh** [comment] 2023-05-31 14:57
I think this might have been because of inductor using the copy() decomp that wasn't stride-preserving (fixed by https://github.com/pytorch/pytorch/pull/100115).

I tried running the repro on top of my local branch with that commit and that fixes the error. I haven't had a chance to try on a fresh main commit though.

**Comment by bdhirsh** [comment] 2023-05-31 15:06
(oh sorry, that PR hasn't actually landed yet. Blocked on some more work need in internal, aka killing the `inductor.skip_cpp_codegen` config).

**Comment by jon-chuang** [comment] 2023-10-22 00:16
I can confirm that no error shows up on main. Closing as fixed.

**Closed by jon-chuang** 2023-10-22 00:16 UTC
Labels: triaged, bug, oncall: pt2, module: functorch, module: aotdispatch
