### ISSUE TITLE
DTensor: summon full tensor API?

### ISSUE THREAD

**Issue by rohan-varma** [pytorch/pytorch#109762] opened 2023-09-21 01:23 UTC
### 🚀 The feature, motivation and pitch

Wondering if there's an API or plans to support materializing the full DTensor from their shards. I couldn't quite find anything in https://github.com/pytorch/pytorch/blob/main/torch/distributed/_tensor/api.py, but might be missing something. 

This could be useful for debugging / iterating on issues related to DTensor. Currently, the following seems like a workaround:

```
# redistribute to single world size
one_ws = DeviceMesh(dist.get_rank())
redist = dtensor.redistribute(one_ws)
whole_tensor = redist.to_local()
```

but not sure.

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by XilunWu** [comment] 2023-09-25 17:09
> materializing the full DTensor from their shards
I think we can simply `redistribute` the shards on the same mesh by:
```
# we want to materialize shards on device_mesh:
unshard = shards.redistribute(device_mesh, [Replicate()])
whole_tensor = unshard.to_local()
```

**Comment by rohan-varma** [comment] 2023-09-28 08:13
@XilunWu Understand there's a workaround, but I'd like to have a discussion on whether there should be a singular API for this, though.

**Comment by awgu** [comment] 2023-09-28 12:30
Personally, I think part of this discussion should include revisiting the use cases for `FSDP.summon_full_params()`. It seems to serve multiple purposes such as debugging typically micro-scale jobs in a single-node environment, implementing some part of the training loop, implementing full state dict, etc., where some of these were not the original intended use case. We may be able to address some of use cases in a more direct way.

**Comment by wconstab** [comment] 2024-01-16 21:45
> # we want to materialize shards on device_mesh:
unshard = shards.redistribute(device_mesh, [Replicate()])
whole_tensor = unshard.to_local()

a syntax sugar API that combines these 2 lines into one could be convenient, and also discoverable if named nicely.  any reason to not do it? (cc @wanchaol)

> Personally, I think part of this discussion should include revisiting the use cases for FSDP.summon_full_params()

@awgu what are you saying- if we had the DT api it'd help avoid 'abuse' of summon_full_params?  or something else

**Comment by awgu** [comment] 2024-01-17 15:33
> a syntax sugar API that combines these 2 lines into one could be convenient, and also discoverable if named nicely. any reason to not do it? (cc @wanchaol)

If we are looking to have a syntactic sugar for condensing two lines into one, I am not too motivated for it personally, but generally if the API remains at the tensor level, this seems okay to me.

The difference with that and `summon_full_params()` is that `summon_full_params()` is module-level and has the option to recurse to submodules (where it recurses by default). In the recursive case, we must be careful about GPU memory, which is why `summon_full_params()` has an `offload_to_cpu: bool` option. 

> @awgu what are you saying- if we had the DT api it'd help avoid 'abuse' of summon_full_params? or something else

I meant more that we should distinguish between the different use cases I mentioned above since they have different requirements and challenge whether they should be solved with the same API. For example, if we only care about using `summon_full_params()` as a helper for writing small unit tests, then we do not need an `offload_to_cpu: bool` option, and it should most likely exist only in our common unit test helper file rather than being a public API. Currently, we use `summon_full_params()` for debugging, state dict, and as a public API alike, which makes it more complex (e.g. for the non-debugging cases, we need to consider persisting changes to the parameters back to their shards).

**Comment by wanchaol** [comment] 2024-01-17 21:37
> a syntax sugar API that combines these 2 lines into one could be convenient, and also discoverable if named nicely. any reason to not do it? (cc @wanchaol)

@wconstab Actually I recently added a `full_tensor` API that materializes all the shards in https://github.com/pytorch/pytorch/pull/112224

Specifically for this issue we can close it.

@awgu I think for PPS FSDP we can possibly still keep a module level API and under the hood calls the `full_tensor` to collective shards? The problem is that whether we want to keep `summon_full_params` as a public API anymore?

**Closed** 2024-01-18 18:41 UTC
Labels: oncall: distributed, triaged
