### ISSUE TITLE
RuntimeError: _cat_out is not implemented for type torch.HalfTensor

### ISSUE THREAD

**Issue by codecookinging** [pytorch/pytorch#16000] opened 2019-01-13 12:33 UTC
## Description

- Image Type:

I use the torch.utils.data.Dataloader to wrap my dataset class , but  the Error message shows that the  image tensor was Torch.HalfTensor, but it was float64, Wha should I do to fix it?

(0, (3, 1280, 704), (1280, 704, 3), <class 'torch.Tensor'>, tensor(-0.4490, dtype=torch.float64))
(1, (3, 1280, 704), (1280, 704, 3), <class 'torch.Tensor'>, tensor(-0.4490, dtype=torch.float64))

dataloader_train = DataLoader(train_dataset, batch_size=1,
                              shuffle=True, pin_memory=True, num_workers=4)
dataloader_valid = DataLoader(test_dataset, batch_size=1,
                              shuffle=True, pin_memory=True, num_workers=4)

 - PyTorch Version (0.4.0):
 - OS (Linux):
 - How you installed PyTorch (`conda`):

**Comment by soumith** [comment] 2019-01-14 05:43
can I get a script to reproduce this? This seems strange.

**Comment by soumith** [comment] 2019-01-14 05:43
also, can you try PyTorch 1.0.0

**Comment by fmassa** [comment] 2019-01-14 13:44
This is actually a duplicate of https://github.com/pytorch/pytorch/issues/6968.

**Closed by fmassa** 2019-01-14 13:44 UTC

**Comment by codecookinging** [comment] 2019-01-15 14:08
NO,NO  it was totally different with that issue,if I use the transforms function 
(from torchvision import transforms) there will be the error , 
`composed=transforms.Compose([Rescale,Norm,ToTensor()])`

if I set composed None that will be fine ,sorry ,the code was too large ,so I can't copy that.

**Comment by codecookinging** [comment] 2019-01-15 14:10
`    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/xyz/anaconda3/envs/torch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 135, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/xyz/anaconda3/envs/torch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 135, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "/home/xyz/anaconda3/envs/torch/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 115, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: _cat_out is not implemented for type torch.HalfTensor`
