### ISSUE TITLE
Apple metal (MPS)  device returning incorrect keypoints for YOLOv8 pose estimation model 

### ISSUE THREAD

**Issue by xalil8** [pytorch/pytorch#99794] opened 2023-04-22 11:08 UTC
### 🐛 Describe the bug

I'm encountering an issue with the YOLOv8 pose estimation model inference using the MPS model. The model is returning incorrect key points. However, when I use the same method and code on the CPU, the key points are correct. I believe the issue may be related to the Apple Metal library. From my research, it seems to be causing the error. The bounding boxes detection seems to be working fine, but there's an issue with calculating the key points. Could you please help me solve this problem?

```python 
import cv2
import numpy as np
from ultralytics import YOLO

cv2.namedWindow("mps_test",cv2.WINDOW_NORMAL)
image = cv2.imread("pose_test.jpeg")
model = YOLO('yolov8s-pose.pt')  # load an official model

results = model(source=image,device="cpu",conf=0.6)
#results = model(source=image,device="mps",conf=0.6)

result_image = results[0].plot()

cv2.imshow("cpu_test", result_image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```
Output With "MPS" (apple metal)
<img width="1168" alt="Screenshot 2023-04-19 at 15 54 42" src="https://user-images.githubusercontent.com/46287166/233779812-87e363e1-b37e-4cbe-b628-5952c3bfc35f.png">

Output With "CPU"

<img width="1212" alt="Screenshot 2023-04-19 at 16 18 57" src="https://user-images.githubusercontent.com/46287166/233779839-1fb70ff8-2bc4-43db-b270-caa495e19921.png">

### Versions
Macbook Air m1 chip 
Metal: Version: 306.2.4
XCode:14.3
Macos Ventura:13.0
ultralytics Version: 8.0.81
Python Version: 3.10.8
Torch Version: 2.1.0.dev20230417
Opencv Version: 4.7.0.72

cc @ezyang @gchanan @zou3519 @seemethere @malfet @kulinseth @albanD @DenisVieriu97 @razarmehr @abhudev

**Comment by malfet** [comment] 2023-04-25 20:06
Can reproduce it on my end, and looks like predictions are correct, but one just fails to rescale the points correctly back to the original image

**Comment by malfet** [comment] 2023-04-26 22:55
Looks like it was fixed in the latest nightly (tested by running `yolo predict model=yolov8s-pose.pt source='https://ultralytics.com/images/bus.jpg' device=mps` and `yolo predict model=yolov8s-pose.pt source='https://ultralytics.com/images/bus.jpg' device=cpu` and comparing the output), but trying to find an PR that did it

**Comment by malfet** [comment] 2023-04-27 19:15
This is really weird: I could not find a single broken nightly version, but release 2.0.0 and release-2.0.1 RCs are currently broken...

**Comment by DenisVieriu97** [comment] 2024-05-08 01:13
@xalil8 thank you for filling this issue.
I am not able to reproduce the issue with following versions:
```
torch                     2.4.0.dev20240501
torchvision            0.19.0.dev20240507
```

Could you please let me know if the issue is still happening locally for you?

**Comment by jhavukainen** [comment] 2024-05-21 20:17
Closing this as its no longer reproducible on the latest version.

**Closed by jhavukainen** 2024-05-21 20:17 UTC
Labels: high priority, module: binaries, oncall: releng, triaged, module: correctness (silent), module: mps
