### ISSUE TITLE
Didn't find engine for operation quantized::conv_prepack NoQEngine (operator () at ..\aten\src\ATen\native\quantized\cpu\qconv_prepack.cpp:264) (no backtrace available)

### ISSUE THREAD

**Issue by mk123qwe** [pytorch/pytorch#34550] opened 2020-03-10 20:08 UTC
Didn't find engine for operation quantized::conv_prepack NoQEngine (operator () at ..\aten\src\ATen\native\quantized\cpu\qconv_prepack.cpp:264)
(no backtrace available)

win10
python3.6
pytorch1.3

code:
from torch.quantization import convert
model_quantized_and_trained = convert(model_ft_tuned, inplace=True)

cc @peterjc123 @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by peterjc123** [comment] 2020-03-11 02:33
Duplicate of #31684.

**Closed by peterjc123** 2020-03-11 02:33 UTC
Labels: module: windows, quantization

**Comment by uchihaltachi** [comment] 2020-04-24 14:05
I also meet this problem, how to solve please.

**Comment by peterjc123** [comment] 2020-04-24 14:08
@uchihaltachi If you are on Windows, then you'll need to update to 1.5.0.

**Comment by uchihaltachi** [comment] 2020-04-24 14:40
你好，刚才的问题解决了，但是我在用pytorch量化的时候，将convert之后的模型进行evaluate的时候又出现的了这个问题，请问您知道怎么解决吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peterjc123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 晚上10:08
收件人:&nbsp;"pytorch/pytorch"<pytorch@noreply.github.com&gt;;
抄送:&nbsp;"二呆子→_→"<1281659997@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pytorch/pytorch] Didn't find engine for operation quantized::conv_prepack NoQEngine (operator () at ..\aten\src\ATen\native\quantized\cpu\qconv_prepack.cpp:264) (no backtrace available) (#34550)





 
@uchihaltachi If you are on Windows, then you'll need to update to 1.5.0.

**Comment by peterjc123** [comment] 2020-04-24 14:42
@pytorch/quantization

**Comment by peterjc123** [comment] 2020-04-24 14:42
@uchihaltachi Any code to illustrate your problem?

**Comment by uchihaltachi** [comment] 2020-04-24 14:49
你好，谢谢您指导。根据报错的地方在107行，代码贴在下面。非常感谢








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"peterjc123"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月24日(星期五) 晚上10:43
收件人:&nbsp;"pytorch/pytorch"<pytorch@noreply.github.com&gt;;
抄送:&nbsp;"二呆子→_→"<1281659997@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [pytorch/pytorch] Didn't find engine for operation quantized::conv_prepack NoQEngine (operator () at ..\aten\src\ATen\native\quantized\cpu\qconv_prepack.cpp:264) (no backtrace available) (#34550)





 
@uchihaltachi Any code to illustrate your problem?
