### ISSUE TITLE
Improve docs search engine indexing

### ISSUE THREAD

**Issue by josherich** [pytorch/pytorch#32838] opened 2020-01-30 20:21 UTC
### There's no way to access api from search engine in one click.

I find it's very hard to search pytorch api from search engine. A typical example would be seaching `pytorch conv2d`, the top result points to `https://pytorch.org/docs/stable/nn.html` without the heading hash `#conv2d`. 

<img width="668" alt="Screen Shot 2020-01-27 at 12 28 28 PM" src="https://user-images.githubusercontent.com/1488391/73486826-e0339b80-4373-11ea-8c04-93551011b107.png">

In most cases, it's sth like the following img, where there's a `jump to xxx` link to the hashed url `https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#Body`

<img width="794" alt="Screen Shot 2020-01-30 at 2 40 14 PM" src="https://user-images.githubusercontent.com/1488391/73484929-30a8fa00-4370-11ea-9ded-0355951e9e15.png">

I'm not sure what's missing here, a quick search seems to suggest search engine need an unique id in headings like `<h4 id="xxx"></h4>` to tell the heading structure.

The search bar in the doc page definitely works, It's also nice to have one click search engine access.

cc @ezyang @gchanan @zou3519

**Comment by ezyang** [comment] 2020-01-31 17:25
I'm marking this as high priority as it seems like a very seriously usability issue for the docs.

**Comment by josherich** [comment] 2020-02-10 22:41
(could be outdated) According to [using-named-anchors-to-identify](https://webmasters.googleblog.com/2009/09/using-named-anchors-to-identify.html)

> There are a few things you can do to increase the chances that they might appear on your pages. First, ensure that long, multi-topic pages on your site are well-structured and broken into distinct logical sections. Second, ensure that each section has an associated anchor with a descriptive name (i.e., not just "Section 2.1"), and that your page includes a "table of contents" which links to the individual anchors.

there's no exact rules to follow, most likely, `id=xxx` on `h` tag is considered more "well-structured"

**Comment by cgarciae** [comment] 2020-02-24 22:36
The "single page per module" strategy makes it VERY HARD to search for Pytorch documentation since Google will just redirect you to the top of the page, then you have to hit `Ctrl + f` and type the term again (try finding `nn.Linear` which appears 23 times).

Why not break it into a page per function / class like most other libraries (numpy, pandas, sklearn, etc)? It would reduce the load time problem discussed in #20984 by virtue of just having to process less content and it would make its content easier to find.

**Comment by rgommers** [comment] 2020-04-08 10:36
+1 for the page per function/class/object in the API. The module page would then contain a short summary of the most important messages for the module (if needed), plus a table of public objects in the API with their summary line (example: http://scipy.github.io/devdocs/optimize.html).

**Comment by rgommers** [comment] 2020-05-08 05:44
This is fixed after gh-37419. Results in https://pytorch.org/docs/master/ (post-1.5.0). Thanks @mattip, all.

**Closed by rgommers** 2020-05-08 05:44 UTC
Labels: high priority, module: doc infra, module: docs, triaged

**Comment by ShawnZhong** [comment] 2020-05-23 00:27
As a quick followup to this issue, Google is starting to index the split docs. Huge thanks to @mattip!

![image](https://user-images.githubusercontent.com/6421097/82717511-2c2b8880-9c62-11ea-9c8c-6172462abef9.png)


BTW, I am not sure how big the issue is, but Google is picking the master docs in favor of the stable docs.
