### ISSUE TITLE
i run the example from you Tutorials,could you told me what's wrong please.

### ISSUE THREAD

**Issue by WangJie8682** [pytorch/pytorch#7239] opened 2018-05-03 12:31 UTC
/home/wj/anaconda2/bin/python2.7 /home/wj/PycharmProjects/untitled2/1.py
Files already downloaded and verified
Files already downloaded and verified
truck  ship   cat  frog
[1,  2000] loss: 2.224
[1,  4000] loss: 1.857
[1,  6000] loss: 1.713
[1,  8000] loss: 1.607
[1, 10000] loss: 1.555
[1, 12000] loss: 1.495
[2,  2000] loss: 1.423
[2,  4000] loss: 1.374
[2,  6000] loss: 1.373
[2,  8000] loss: 1.326
[2, 10000] loss: 1.309
[2, 12000] loss: 1.280
Finished Training
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa8c97b3050>> ignored
('GroundTruth: ', '  cat  ship  ship plane')
('Predicted: ', '  cat   car  ship  ship')
Accuracy of the network on the 10000 test images: 54 %
Accuracy of plane : 64 %
Accuracy of   car : 69 %
Accuracy of  bird : 40 %
Accuracy of   cat : 35 %
Accuracy of  deer : 53 %
Accuracy of   dog : 42 %
Accuracy of  frog : 76 %
Accuracy of horse : 44 %
Accuracy of  ship : 64 %
Accuracy of truck : 51 %
cpu
Exception NameError: "global name 'FileNotFoundError' is not defined" in <bound method _DataLoaderIter.__del__ of <torch.utils.data.dataloader._DataLoaderIter object at 0x7fa8aaaec810>> ignored

Process finished with exit code 0

**Comment by SsnL** [comment] 2018-05-03 13:51
Duplicate of #6932 . Sorry about this. This error can be ignored.

**Closed by SsnL** 2018-05-03 13:51 UTC
