### ISSUE TITLE
windows.8xlarge.nvidia.gpu testing is backlogged

### ISSUE THREAD

**Issue by jeanschmidt** [pytorch/pytorch#98502] opened 2023-04-06 14:05 UTC
## Current Status
ongoing

## Error looks like
![Screenshot 2023-04-06 at 13 56 33](https://user-images.githubusercontent.com/4520845/230401960-98e7310b-6323-4970-afb5-1028617efa0f.png)

## Incident timeline (all times pacific)
Detected: 13:57 CET

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment] 2023-04-06 14:22
Closing as duplicate of https://github.com/pytorch/pytorch/issues/98474

**Closed by malfet** 2023-04-06 14:22 UTC
Labels: ci: sev
