### ISSUE TITLE
Better error message when attempting to `torch.save` an optimized model

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#93553] opened 2022-10-20 02:30 UTC
A bunch of examples directly do `torch.save(model)`. For example https://github.com/pytorch/examples/blob/main/word_language_model/main.py#L234-L235

Right now, if a dynamo-optimized model is attempted to be saved, this is the error message.
Fixing this IMO is not a priority.
But, at the very least, a better error message should be displayed.

```
-----------------------------------------------------------------------------------------
| end of epoch   1 | time: 26.86s | valid loss  7.29 | valid ppl  1467.68
-----------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/soumith/code/examples/word_language_model/main.py", line 237, in <module>
    torch.save(model, f)
  File "/home/soumith/code/pytorch/torch/serialization.py", line 422, in save
    _save(obj, opened_zipfile, pickle_module, pickle_protocol)
  File "/home/soumith/code/pytorch/torch/serialization.py", line 634, in _save
    pickler.dump(obj)
AttributeError: Can't pickle local object '_TorchDynamoContext.__call__.<locals>.TorchDynamoNNModuleWrapper'
```

cc @ezyang @msaroufim @wconstab @bdhirsh @anijain2305 @zou3519 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng @ngimel

**Comment by ydwu4** [comment] 2023-11-27 21:51
Confirmed error persists in [D51598964](https://www.internalfb.com/diff/D51598964)

**Comment by MarchisLost** [comment] 2024-05-06 23:23
I would like to take a run at his one. To what exactly should be changed or what should be added?

**Comment by StrongerXi** [comment] 2024-09-17 23:28
Closing since this no longer repros.

**Closed by StrongerXi** 2024-09-17 23:28 UTC
Labels: good first issue, triaged, oncall: pt2, module: dynamo, dynamo-must-fix
