### ISSUE TITLE
No input shape check on matmul (also nn.Linear) with CUDA backend

### ISSUE THREAD

**Issue by VladislavZavadskyy** [pytorch/pytorch#62562] opened 2021-08-02 10:07 UTC
## 🐛 Bug

You can feed matrices with arbitrarily-sized column dimension of matrix A, as long as it's not smaller than row dimension of matrix B and get output perfectly fine with no warnings.

## To Reproduce

1. Have `torch.__version__ == 1.9.0+cu111` (everything appearas to be ok on 1.8.1)
1. Run the following:

```python
torch.randn(10, 15, device='cuda') @ torch.randn(14, 32, device='cuda')
```
You should see no error, because number of A's columns is sufficient to make the multiplication (I imagine A's last column is truncated when doing the multiplication). If you run the same code on the CPU you get a shape incompatibility error.

The same behavior is observed with linear layers:
```python
torch.nn.Linear(16, 32).cuda()(torch.randn(256, 17, device='cuda'))
```

It gets weirder when you transpose A:

```python
torch.randn(10, 15, device='cuda').T @ torch.randn(9, 32, device='cuda')
```

Then, the shape of the second tensor appears to not matter at all, as long as it's non-negative ;)

## Expected behavior

Would be nice to have a python-side shape mismatch assertion triggered, like it happens on the CPU.

## Environment

 - PyTorch Version 1.9.0:
 - OS Ubuntu 20.04.2 LTS
 - How you installed PyTorch: pip
 - Python version: 3.8.10
 - CUDA/cuDNN version: CUDA is 11.1, cuDNN is not installed 
 - GPU models and configuration: Tested on GeForce RTX 2080 Ti and laptop's 3080 Ti

cc @ezyang @seemethere @malfet @walterddr @ngimel @albanD @mruberry @jbschlosser

**Comment by malfet** [comment] 2021-08-02 15:08
Duplicate of https://github.com/pytorch/pytorch/issues/61291, was already fixed by https://github.com/pytorch/pytorch/pull/57417 and available in nightlies (Could you please try torch-1.10.0.dev20210731 and see if issue still reproduces )

**Closed** 2021-08-02 15:19 UTC
Labels: module: binaries, module: cuda, module: nn
