### ISSUE TITLE
Bug with the sparse mode of nn.Embedding

### ISSUE THREAD

**Issue by yf225** [pytorch/pytorch#17941] opened 2019-03-12 21:34 UTC
(Reported by internal user)

## 🐛 Bug

I'm observing some weird behaviors with the sparse mode of nn.Embedding. For instance, with the following code:
```python
m = nn.Embedding(10, 3, sparse=True)
m.zero_grad()
m(torch.LongTensor([7, 1, 3])).sum().backward()
print(m.weight.grad)
```
I'll get
```python
torch.sparse.FloatTensor of size (10,3) with indices:
tensor([[7, 1, 3]])
and values:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
```
as expected. But if I repeat the fwd/bwd line twice:
```python
m = nn.Embedding(10, 3, sparse=True)
m.zero_grad()
m(torch.LongTensor([7, 1, 3])).sum().backward()
m(torch.LongTensor([7, 1, 3])).sum().backward()
print(m.weight.grad)
```
I get random outputs, such as:
```python
torch.sparse.FloatTensor of size (10,3) with indices:
tensor([[7, 1, 3]])
and values:
tensor([[  2.0000,   1.0000,   1.0000],
        [  1.0000,   1.0000,   1.0000],
        [  1.0000,   1.0000, 793.1436]])
```
I guess this is not expected?
Also I noticed that if the input is different, it behaves very differently:
```python
m = nn.Embedding(10, 3, sparse=True)
m.zero_grad()
m(torch.LongTensor([7, 1, 3])).sum().backward()
m(torch.LongTensor([8, 1, 3])).sum().backward()
print(m.weight.grad)
```
Returns:
```python
torch.sparse.FloatTensor of size (10,3) with indices:
tensor([[7, 1, 3, 8, 1, 3]])
and values:
tensor([[1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 1.0000, 1.0000],
        [1.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])
```

## Expected behavior

It should behave the same as the dense version of nn.Embedding (aka. `nn.Embedding(10, 3, sparse=False)`.

## Additional Context

This is reproducible on nightly builds as of 3/12/2019.

**Comment by SsnL** [comment] 2019-03-12 22:27
duplicate of https://github.com/pytorch/pytorch/issues/17919.

**Closed by SsnL** 2019-03-12 22:27 UTC
