### ISSUE TITLE
Can't export onnx model from a torch script model

### ISSUE THREAD

**Issue by gvidaver** [pytorch/pytorch#100414] opened 2023-05-01 20:38 UTC
### 🐛 Describe the bug

Trying to run to do an onnx export of a torch script model, got 

RuntimeError: input_values.size() == param_count_list.size() INTERNAL ASSERT FAILED

```
/home/go22670/.conda/envs/torch/lib/python3.10/site-packages/torch/onnx/utils.py:825: UserWarning: no signature found for <torch.ScriptMethod object at 0x7f3115072ac0>, skipping _decide_input_format
  warnings.warn(f"{e}, skipping _decide_input_format")
================ Diagnostic Run torch.onnx.export version 2.0.0 ================
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

Traceback (most recent call last):
  File "/home/go22670/Projects/test2/test.py", line 25, in <module>
    out, vad, enhFile = enh.process(file,outFile=myout)
  File "/home/go22670/Projects/test2/src/ourcode/enhance.py", line 242, in process
    self.convert(self.model, tWin)
  File "/home/go22670/Projects/test2/src/ourcode/enhance.py", line 184, in convert
    Th.onnx.export(model, input, seamnet_onnx, verbose=True, input_names=input_names, output_names=output_names)
  File "/home/go22670/.conda/envs/torch/lib/python3.10/site-packages/torch/onnx/utils.py", line 506, in export
    _export(
  File "/home/go22670/.conda/envs/torch/lib/python3.10/site-packages/torch/onnx/utils.py", line 1548, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/go22670/.conda/envs/torch/lib/python3.10/site-packages/torch/onnx/utils.py", line 1113, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/go22670/.conda/envs/torch/lib/python3.10/site-packages/torch/onnx/utils.py", line 974, in _create_jit_graph
    graph = _C._propagate_and_assign_input_shapes(
RuntimeError: input_values.size() == param_count_list.size() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1678402411778/work/torch/csrc/jit/ir/graph_utils.cpp":57, please report a bug to PyTorch.  input_values:194 vs param_count_list:193
```

I wish I could provide a minimal example, but our network is pretty big.

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux 8.7 (Ootpa) (x86_64)
GCC version: (GCC) 8.5.0 20210514 (Red Hat 8.5.0-15)
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.28

Python version: 3.10.11 (main, Apr 20 2023, 19:02:41) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.18.0-425.3.1.el8.x86_64-x86_64-with-glibc2.28
Is CUDA available: True
CUDA runtime version: 11.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: GRID A100-40C
GPU 1: GRID A100-40C

Nvidia driver version: 510.85.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              16
On-line CPU(s) list: 0-15
Thread(s) per core:  1
Core(s) per socket:  2
Socket(s):           8
NUMA node(s):        1
Vendor ID:           AuthenticAMD
CPU family:          25
Model:               1
Model name:          AMD EPYC 7713 64-Core Processor
Stepping:            1
CPU MHz:             1996.249
BogoMIPS:            3992.49
Hypervisor vendor:   VMware
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            512K
L3 cache:            32768K
NUMA node0 CPU(s):   0-15
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl tsc_reliable nonstop_tsc cpuid extd_apicid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm cmp_legacy extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw topoext invpcid_single ibpb vmmcall fsgsbase bmi1 avx2 smep bmi2 invpcid rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves clzero wbnoinvd arat umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0
[pip3] torchaudio==2.0.0
[pip3] torchvision==0.15.0
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-fft                   1.3.1                    pypi_0    pypi
[conda] mkl-random                1.2.2                    pypi_0    pypi
[conda] mkl-service               2.4.0                    pypi_0    pypi
[conda] mkl_fft                   1.3.1           py310hd6ae3a3_0  
[conda] mkl_random                1.2.2           py310h00e6091_0  
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] numpy-base                1.23.5          py310h8e6c178_0  
[conda] pytorch                   2.0.0           py3.10_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_3    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.0.0                    pypi_0    pypi
[conda] torchaudio                2.0.0                    pypi_0    pypi
[conda] torchtriton               2.0.0                     py310    pytorch
[conda] torchvision               0.15.0                   pypi_0    pypi
[conda] triton                    2.0.0                    pypi_0    pypi
```

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel

**Comment by albert-grigoryan** [comment] 2023-07-09 20:00
I faced the similar problem with the latest torch(torch.onnx.export version 2.0.1+cu117), can share sources for the reproduction.
```
    graph = _C._propagate_and_assign_input_shapes(
RuntimeError: input_values.size() == param_count_list.size() INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/graph_utils.cpp":57, please report a bug to PyTorch.  input_values:80 vs param_count_list:79
```

**Comment by fxmarty** [comment] 2023-10-09 10:53
Here is a simple reproduction for this issue:

```python
import torch.nn as nn
import torch

class MyModule(nn.Module):
    def __init__(self):
        super().__init__()
        self.lin = nn.Linear(10, 20)
    
    def forward(self, x, trigger=False, y=None):
        x = self.lin(x)
        
        if trigger and y is not None:
            x = x + y
        
        return x

model = MyModule()

x = torch.rand(4, 10)
y = torch.rand(4, 20)

res = model(x, y=y)

inp = {"x": x, "y": y}

traced_model = torch.jit.trace(model, example_kwarg_inputs=inp)

res = traced_model(**inp)

# does work
torch.onnx.export(
    model,
    (inp,),
    "model.onnx"
)

# does not work
torch.onnx.export(
    traced_model,
    (inp,),
    "model.onnx"
)
```

with the error:
```
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 516, in export
    _export(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 1596, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 1135, in _model_to_graph
    graph, params, torch_out, module = _create_jit_graph(model, args)
  File "/home/fxmarty/anaconda3/envs/hf-inf/lib/python3.9/site-packages/torch/onnx/utils.py", line 996, in _create_jit_graph
    graph = _C._propagate_and_assign_input_shapes(
RuntimeError: input_values.size() == param_count_list.size() INTERNAL ASSERT FAILED at "../torch/csrc/jit/ir/graph_utils.cpp":57, please report a bug to PyTorch.  input_values:4 vs param_count_list:3
```

Basically `torch.onnx.export` is unable to handle the export from `ScriptModule` when the passed inputs are keyword arguments. Using positional arguments is fine but requires to reorder the inputs of the model in some cases (notably when some of the defaults are `None`, which is not optimal. Notably when some of the defaults are `None`, otherwise getting this error

```
RuntimeError: Type 'Tuple[NoneType, NoneType, Tensor, Tensor, Tensor, NoneType, NoneType, NoneType, Tuple[Tuple[Tensor, Tensor, Tensor, Tensor], Tuple[Tensor, Tensor, Tensor, Tensor], Tuple[Tensor, Tensor, Tensor, Tensor], Tuple[Tensor, Tensor, Tensor, Tensor]], Tensor]' cannot be traced. Only Tensors and (possibly nested) Lists, Dicts, and Tuples of Tensors can be traced
```

if `None` are added to the positional arguments (e.g. here https://github.com/huggingface/transformers/blob/b71f20a7c9f3716d30f6738501559acf863e2c5c/src/transformers/models/whisper/modeling_whisper.py#L1431)

cc @justinchuby @BowenBao @thiagocrepaldi

**Comment by titaiwangms** [comment] 2024-04-01 15:49
Hi @gvidaver 

We’ve gone ahead and closed this issue because we think it can be resolved with our new torch.onnx.dynamo_export api. Please try that instead! If you still believe this issue is relevant, please feel free to reopen the issue and we will triage it as necessary. Please specify in a comment any updated information you may have so that we can address it effectively. We encourage you to try the latest pytorch-preview (nightly) version to see if it has resolved the issue, as we are constantly working to make the converter experience better for everyone!

Thanks,
ONNX Converter team

**Closed by titaiwangms** 2024-04-01 15:49 UTC
Labels: oncall: jit, module: onnx, triaged
