### ISSUE TITLE
Wrong in nn.ParameterList and nn.DataParallel, pytorch1.6

### ISSUE THREAD

**Issue by yfsong0709** [pytorch/pytorch#42327] opened 2020-07-30 18:31 UTC
When using nn.ParameterList and nn.DataParallel at the same time, the length of ParameterList will be 0 after DataParallel.

See and run this code (with pytorch=1.6+cu101 installed by pip):
```
import torch

class Model(torch.nn.Module):
    def __init__(self):
        super(Model, self).__init__()

        self.param = torch.nn.ParameterList([torch.nn.Parameter(torch.zeros(3,3)) for _ in range(16)])
        print('Before DataParallel: ' + str(len(self.param)))

    def forward(self, x):
        print('After DataParallel: ' + str(len(self.param)))
        return x


model = Model()
model = model.to(torch.device('cuda'))
model = torch.nn.DataParallel(model)
x = model(torch.zeros(3,3))
```

And the results are:
```
Before DataParallel: 16
After DataParallel: 0
After DataParallel: 0
After DataParallel: 0
After DataParallel: 0
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar @jiayisuse @agolynski @albanD @mruberry

**Comment by SsnL** [comment] 2020-07-30 20:38
related to the distributed changes on `.parameters()`

**Comment by pritamdamania87** [comment] 2020-07-30 23:57
@ngimel I'm wondering if this is related to https://github.com/pytorch/pytorch/pull/33907?

**Comment by yfsong0709** [comment] 2020-07-31 01:52
I run this code with pytorch1.4 and pytorch1.5 installed by anaconda, and the results are correct.

**Comment by ngimel** [comment] 2020-07-31 01:57
#33907 is part of 1.5, so that means it's not the problem?

**Comment by yfsong0709** [comment] 2020-07-31 03:10
Sorry, pytorch1.5 is also incorrect, only pytorch1.4 outputs correct results. Maybe #33907 is a solution, I'm testing now.

**Comment by yfsong0709** [comment] 2020-07-31 04:31
I find the solution. Do this modification in torch.nn.parallel.replicate.py:

wrong code (around line 147):   setattr(replica, key, param)
modified code:   setattr(replica, key, Parameter(param))

and also need to add the code (from torch.nn import Parameter) in the beginning.

Then this bug will output correct results.

But I wonder if this modification will break other things.

**Comment by concretevitamin** [comment] 2020-08-02 19:34
This is a serious issue preventing us from upgrading to 1.6.  Working around ParameterList (e.g., assign directly as attributes) is non-ideal as it breaks loading prior checkpoints.  Adding glue code to load prior checkpoints would work, but it's something I don't expect from a stable release.

Also related to issue #36035.

**Comment by albanD** [comment] 2020-10-12 17:37
Closing as duplicate of #36035 
We can continue any discussion there.

**Closed by albanD** 2020-10-12 17:37 UTC
Labels: module: data parallel, module: nn, oncall: distributed, triaged
