### ISSUE TITLE
Hangs at tensor.float() in child process only if tensor.float() is called in main process 

### ISSUE THREAD

**Issue by HiroIshida** [pytorch/pytorch#89693] opened 2022-11-25 18:02 UTC
### 🐛 Describe the bug

Then following code is the minimal reproducing example. 
This code hangs at float() in the child process. This bug occurs only when `N` is set to large, and `do_task` is called in before running the child process. 

```python
import numpy as np
from multiprocessing import Process
import torch

def do_task(N):
    mat = np.random.randn(N ** 3)
    a = torch.from_numpy(mat)
    print("a")
    a.float()
    print("b")

N = 40  # hangs only if set larger (> 30)
do_task(N)  # don't hang without this line
p = Process(target=do_task, args=(N,))
p.start()
p.join()
```
Expected print output is like `a, b, a, b`. But hangs after outputting `a, b, a`.

NOTE: this bug can be circumvented by setting
```
multiprocessing.set_start_method(method="spawn")
```
but I don't want to do this if possible 
### Versions

Collecting environment information...
PyTorch version: 1.13.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.4 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.13.0-30-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 510.47.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] gpytorch==1.9.0
[pip3] mypy==0.990
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==1.13.0
[pip3] torchvision==0.12.0
[conda] Could not collect

**Comment by HiroIshida** [comment] 2022-11-26 15:32
I suspect that this caused by multithreading in numpy. And I tried
I tried executing `export MKL_NUM_THREADS=1`

**Comment by albanD** [comment] 2022-11-28 18:02
Hi,

I'm afraid this is caused by OMP that does not support forking.
Closing as duplicate of https://github.com/pytorch/pytorch/issues/17199 where there is a lot more discussion on this.

**Closed by albanD** 2022-11-28 18:02 UTC
