### ISSUE TITLE
Collective communications dramatically slow down

### ISSUE THREAD

**Issue by beccohov** [pytorch/pytorch#120428] opened 2024-02-22 19:37 UTC
### 🐛 Describe the bug

Hi!
I'm doing distributed training experiments with my a100 GPUs (all GPUs connected via NVLink).
I run a simple code to explore how DtoH transactions related with communications (specifically, AllGather).
Bellow is my simple code running with torch.distributed.run on 4 GPUs (within only one node)

```
import torch
import torch.distributed as dist
from torch.profiler import profile, record_function, ProfilerActivity
from torch.profiler import schedule

my_schedule = schedule(
    skip_first=1,
    wait=1,
    warmup=1,
    active=20,
    repeat=1)

dist.init_process_group("nccl")
n_gpus = torch.cuda.device_count()
print(f"Running on {n_gpus} gpus")
W = 2048
H = 8192
activation_tensor = torch.rand(W, H, 128, dtype=torch.bfloat16, device=f'cuda:{dist.get_rank()}') # large tensor activation
weight_tensor = torch.rand(W, H, 128//n_gpus, dtype=torch.bfloat16, device=f'cuda:{dist.get_rank()}') # large tensor
cpu_buffer = torch.empty(W, H, 128, dtype=torch.bfloat16, device='cpu', pin_memory=True)
to_tensor = torch.zeros_like(activation_tensor)
N_times = 30
comm_stream = torch.cuda.Stream()
offload_stream = torch.cuda.Stream()
with profile(activities=[ProfilerActivity.CPU, ProfilerActivity.CUDA], record_shapes=True,schedule=my_schedule) as prof:
    for op_idx in range(N_times):
        with torch.cuda.stream(comm_stream):
            torch.distributed.all_gather_into_tensor(to_tensor, weight_tensor) # AG
        with torch.cuda.stream(offload_stream):
            cpu_buffer.copy_(activation_tensor, non_blocking=True) # DtoH
        prof.step()
    torch.cuda.synchronize() # wait all kernels in all streams
prof.export_chrome_trace("my_profile.json")
dist.destroy_process_group()
```
I was suprised when I looked at resulted traces.
![image](https://github.com/pytorch/pytorch/assets/36795440/c12776fd-75bd-408a-9227-33f14eb6c71f)
As could be seen, AG time is dramatically increased (nearly 100 times). Because without DtoH communications looked like
![image](https://github.com/pytorch/pytorch/assets/36795440/74865ebe-75d1-46fb-a6a4-c2222c02411d)
So, my question is why there is such a huge slowdown ? Is it expected?
I might suppose that bus bandwidth may be crucial, but for HtoD instead DtoH there is no such a problem (i.e. it slowdowns too, but not that much).

P.S.
I ran my code with the following command:
```
CUDA_VISIBLE_DEVICES="0,2" python -m torch.distributed.launch --nproc_per_node 2 --master_port 25676 path_to_script.py
```

### Versions

torch==2.1.0a0+32f93b1
CUDA used to build PyTorch: 12.2
CUDA runtime version: 12.2.128
Nvidia driver version: 525.60.13
Python version: 3.10.12
NCCL 2.18.5

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @fegin @XilunWu @wanchaol @fduwjj @wz337 @tianyu-l @wconstab @yf225

**Comment by awgu** [comment] 2024-02-22 19:51
cc: @yifuwang this is interesting

**Comment by tringwald** [comment] 2024-02-22 20:24
Can you try again with `CUDA_VISIBLE_DEVICES="0,1"` and see if the issue persists?

**Comment by yifuwang** [comment] 2024-02-22 21:50
Interesting. Since NCCL kernels copy data from internal buffer to user buffer, some SM/memory bandwidth contention is expected. However, 100x difference seems abnormal.

One thing I noticed is that the all-gather kernel in your trace is prefixed with `ncclKernel_Allgather_RING_LL`. Normally when the NVLink path is used (via P2P), I think the kernel should be prefixed with `ncclDevKernel_Allgather_RING_LL`? I'm not 100% sure on this (e.g. if this is the case for all NCCL versions). However, if this were the case, you could be transfering data over PCIe, which could explain the severe contention with HtoD/DtoH copy (again not sure).

I'd first try to make sure the communication is really taking place over NVLink:
- Make sure NCCL_P2P_DISABLE is not set
- Verify `nvidia-smi topo -m` to make sure the participating GPUs are directly connected
- Use nsight system to check if there is traffic over NVLink

**Comment by beccohov** [comment] 2024-02-22 22:09
> Can you try again with `CUDA_VISIBLE_DEVICES="0,1"` and see if the issue persists?

Yep, I tried on different GPUs (i.e CUDA_VISIBLE_DEVICES) and got the same.

**Comment by beccohov** [comment] 2024-02-22 22:31
Thank you for your advices,

> * Make sure NCCL_P2P_DISABLE is not set
I've checked. It's all right.
> * Verify `nvidia-smi topo -m` to make sure the participating GPUs are directly connected
There is also all clear. All of GPUs are connected directly

> * Use nsight system to check if there is traffic over NVLink
Nsys profile showed that not all of GPUs were used separated streams for DtoH. In setup with two GPUs one used default stream for copying. Is it expected? How come one of GPUs ignored passed custom Stream ?

**Comment by yifuwang** [comment] 2024-02-22 22:38
Are you seeing NVLink traffic with nsys? e.g.

<img width="271" alt="image" src="https://github.com/pytorch/pytorch/assets/4156752/69cffb74-022c-4695-9ae7-1803425d9d57">

**Comment by yifuwang** [comment] 2024-02-23 08:57
I ran your code and was able to reproduce the same issue:

<img width="1145" alt="image" src="https://github.com/pytorch/pytorch/assets/4156752/47633b8a-0210-4f67-8cd0-add1f5c29fa1">

I think the problem is that you didn't call `torch.cuda.set_device` properly. After fixing this I get:

<img width="889" alt="image" src="https://github.com/pytorch/pytorch/assets/4156752/e5f6835e-96d5-4d80-9908-eb35bd9bebea">

**Comment by beccohov** [comment] 2024-02-27 14:42
Thank you all! This particular case had been resolved, I think.

P.S.
The next related to this experiment issues are [here](https://github.com/pytorch/pytorch/issues/120709) and [here](https://github.com/pytorch/pytorch/issues/120713).

**Comment by yifuwang** [comment] 2024-02-27 20:42
Closing as it's been resolved.

**Closed by yifuwang** 2024-02-27 20:42 UTC
Labels: oncall: distributed
