### ISSUE TITLE
Layer freezing doesn't work with model.train() in v0.4.0

### ISSUE THREAD

**Issue by nabihach** [pytorch/pytorch#8582] opened 2018-06-16 16:04 UTC
## Issue description

I just upgraded my Pytorch version from 0.3.0 to v0.4.0, and I'm running into the following issue.

I want to freeze the parameters of a layer (i.e. set `requires_grad to False` for that layer) and train. This worked fine of v0.3.0 but now, I get the following error at the line `loss.backward()`:
`RuntimeError: backward_input can only be called in training mode`

Based on what I found online, I added `model.train()` to the code, but now I get the following error on `loss.backward()`:
`RuntimeError: inconsistent range for TensorList output`

When I comment out the layer freezing, things work fine. It seems that model.train() assumes `requires.grad=True` for all the parameters. How can I make training work properly with freezing?

Giving the code example below.

## Code example
The following code ran fine on v0.3.0
```
for name, param in model.named_parameters():
    if name == 'encoder.embedding.weight':
        param.requires_grad = False
loss = model.forward()
loss.backward()
```
Running it on v0.4.0 yields to following error:
```
  File "/mnt/fs_default/Conversational-Agents/model.py", line 86, in train_batch
    loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: backward_input can only be called in training mode
```
So then I added `model.train()` to my code as follows:
```
for name, param in model.named_parameters():
    if name == 'encoder.embedding.weight':
        param.requires_grad = False
model.train()
loss = model.forward()
loss.backward()
```
but now I get the error:
```
  File "/mnt/fs_default/kaselby/Conversational-Agents/model.py", line 88, in train_batch
    loss.backward()
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 93, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 89, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: inconsistent range for TensorList output
```

Is this a bug? If not, can someone tell me how to make layer freezing work properly with model.train()?

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: Tesla P100-PCIE-16GB
GPU 1: Tesla P100-PCIE-16GB
GPU 2: Tesla P100-PCIE-16GB
GPU 3: Tesla P100-PCIE-16GB

Nvidia driver version: 384.111
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] msgpack-numpy (0.4.1)
[pip3] numpy (1.13.3)
[pip3] torch (0.4.0)
[pip3] torchtext (0.2.3)
[pip3] torchvision (0.1.9)
[conda] Could not collect

**Comment by LiyuanLucasLiu** [comment] 2018-06-22 22:07
Did you recompile with current master? It seems that the problem you met is similar to
#7722

**Comment by li-roy** [comment] 2018-07-16 21:49
Could you please provide a minimal reproduce for this bug? It would make this a lot easier to solve.

**Comment by t-vi** [comment] 2018-07-20 20:47
I think this might very well be a duplicate of #7722. If so, it is fixed in master and would be with the next release.

**Comment by t-vi** [comment] 2018-07-27 06:19
@nabihach Could you please check if 0.4.1 fixes this? If not we would need to take a deeper look.

**Comment by dpogosov** [comment] 2018-07-28 20:47
I faced the same issue. I tried versions 0.4.0 and 0.4.1, the result was the same.

**Comment by t-vi** [comment] 2018-07-28 20:56
@dpogosov but do you have a runnable code example?

**Comment by dpogosov** [comment] 2018-07-28 21:08
Well, I have a LSTM model and some linear layers. I run the following code to freeze  the LSTM part in order to continue training only the linear layers. 

`def freeze_layer(self, layer):
    for param in layer.parameters():
        param.requires_grad = False`

When it starts `loss.backward()` then the error occurs:
RuntimeError: inconsistent range for TensorList output

Without freezing the model works well.

Is that helpful?

**Comment by t-vi** [comment] 2018-07-29 06:57
So what would be most helpful would be a minimal .py that actually runs and produces the error. Either copy it here or  link to a gist or something. It doesn't need to do anything useful, just show the error.
Thanks!

**Comment by dpogosov** [comment] 2018-07-29 17:37
@t-vi may I send it to your email? I do not like to publish the code / model.

**Comment by t-vi** [comment] 2018-07-29 18:06
You can, but you if you want to be super-safe, I'd probably recommend to cut down the model to two or three standard layers and put random data of the appropriate size through them. That keeps your privacy and saves me a ton of work (because that would be the first thing I have to do *after* I figured out how to get your code running), so it means I can zoom into the error and fix it faster (if you look at the bug that I thought might be related, there it took only 15 minutes from taking the minimal reproduction example to the first fix even if that didn't end up to be the one that got adopted; I've never spent less than half a day to get other people's code to run).

**Comment by thomassutter** [comment] 2018-08-16 14:07
Is there any progress on this issue?

**Comment by t-vi** [comment] 2018-08-16 15:38
We still could use a (minimal if possible) example to reproduce.

**Comment by li-roy** [comment] 2018-08-16 23:41
@thomassutter If you're running into this issue, maybe first try 0.4.1 as @t-vi suggested.

**Comment by thomassutter** [comment] 2018-08-17 05:36
@li-roy I am currently using 0.4.1. I was trying the code from this repo:
https://github.com/wiseodd/controlled-text-generation

If you first run python train_vae.py --save --gpu and then python train_discriminator --save --gpu, you get this error message as well.
If you discard the --gpu option, the train_discriminator script runs fine.

**Comment by 314rated** [comment] 2018-10-31 12:20
I too am facing the same issue.
There is a LSTM model which needs to be frozen. The output of the LSTM goes to another net, Net2, which needs to be trained. 
I am setting lstm to eval mode, setting net2 to train. When I do backprop on loss, I get the error:
RuntimeError: cudnn RNN backward can only be called in training mode

If I change the LSTM to train mode and then do backprop, it works. However, I need the LSTM to be frozen.

Could you please help?
Thanks

**Comment by t-vi** [comment] 2018-10-31 12:43
@314rated No, you aren't facing the same issue, as you, in contrast to the others you want to put the LSTM in eval mode, while the others want train mode.

Your options are a) leave the LSTM in training mode (but you could `.requires_grad_(false)` the parameters and not pass them to the optimizer) or b) not use cudnn (by wrapping the LSTM call in `with torch.backends.cudnn.flags(enabled=False):`).

As it's not related to the issue, it would be best if we could move further discussion to the forum.

**Comment by 314rated** [comment] 2018-11-01 04:32
Thanks for your reply. Could you please clarify the following:
1. Would leaving the LSTM in training mode (but you could .requires_grad_(false) the parameters and not passing them to the optimize ensure that Dropout and BatchNorm are off?
2. All other nets are on GPU, so the tensors would be Cuda tensors. Would not using cudnn for LSTM make it compatible with rest of model?

**Comment by t-vi** [comment] 2018-11-01 08:50
Can you please ask those on the forum? There are much more competent people than me to answer your question there and other people will also benefit from your experience.
Also, you didn't just try the second method, did you?

**Closed** 2018-11-01 13:33 UTC
Labels: high priority

**Comment by Akhila-Yerukola** [comment] 2020-01-22 07:42
> @li-roy I am currently using 0.4.1. I was trying the code from this repo:
> https://github.com/wiseodd/controlled-text-generation
> 
> If you first run python train_vae.py --save --gpu and then python train_discriminator --save --gpu, you get this error message as well.
> If you discard the --gpu option, the train_discriminator script runs fine.

@thomassutter were you able to figure this out?
