### ISSUE TITLE
`mv()` outputs `tensor([0.])` with empty 2D and 1D tensor

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130054] opened 2024-07-03 20:33 UTC
### 🐛 Describe the bug

[mv()](https://pytorch.org/docs/stable/generated/torch.mv.html) outputs `tensor([0.])` with empty 2D and 1D tensor as shown below:

```python
import torch

t1 = torch.tensor([[]])
t2 = torch.tensor([])

torch.mv(input=t1, vec=t2)
# tensor([0.])

# Additional
t1 = torch.tensor([[0.]])
t2 = torch.tensor([0.])

torch.mv(input=t1, vec=t2)
# tensor([0.])
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by albanD** [comment] 2024-07-08 14:49
Is this the same as https://github.com/pytorch/pytorch/issues/130063 ?

**Comment by zou3519** [comment] 2024-07-09 13:49
Closing as intended due to https://github.com/pytorch/pytorch/issues/130063

**Closed by zou3519** 2024-07-09 13:49 UTC
Labels: triaged, module: edge cases
