### ISSUE TITLE
torch::jit::load("./lc_model.pt") failed 

### ISSUE THREAD

**Issue by azuredsky** [pytorch/pytorch#22196] opened 2019-06-25 10:21 UTC
## 🐛 Bug
what():  open file failed, file path

Debug:
```
terminate called after throwing an instance of 'c10::Error'
  what():  open file failed, file path: ./lc_model.pt (FileAdapter at /pytorch/caffe2/serialize/file_adapter.cc:11)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f1e3bc96441 in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f1e3bc95d7a in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::FileAdapter::FileAdapter(std::string const&) + 0x1f2 (0x7f1e3d887602 in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libcaffe2.so)
frame #3: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x30 (0x7f1e9e1b4d10 in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libtorch.so.1)
frame #4: /home/sky/cuda-workspace/eg_1/eg_torch/Debug/eg_torch() [0x402c95]
frame #5: __libc_start_main + 0xf5 (0x7f1e3b0c3a85 in /lib64/libc.so.6)
frame #6: /home/sky/cuda-workspace/eg_1/eg_torch/Debug/eg_torch() [0x402e7e]
```

Release:
```
terminate called after throwing an instance of 'c10::Error'
  what():  open file failed, file path: ./lc_model.pt (FileAdapter at /pytorch/caffe2/serialize/file_adapter.cc:11)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fd895e27441 in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fd895e26d7a in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::FileAdapter::FileAdapter(std::string const&) + 0x1f2 (0x7fd897a18602 in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libcaffe2.so)
frame #3: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x30 (0x7fd8f8345d10 in /run/media/sky/a5f86773-a7e2-4f0f-a16e-1fa289d496bd/CV_WORK/ar-sdks/thirdParty/libtorch/lib/libtorch.so.1)
frame #4: /home/sky/cuda-workspace/eg_1/eg_torch/Release/eg_torch() [0x402c95]
frame #5: __libc_start_main + 0xf5 (0x7fd895254a85 in /lib64/libc.so.6)
frame #6: /home/sky/cuda-workspace/eg_1/eg_torch/Release/eg_torch() [0x402e7e]
```

## To Reproduce

torch                              1.1.0    
torchvision                        0.3.0 

```
#include <iostream>
#include "torch/script.h"
//#include "torch/torch.h"
using namespace std;

int main() {
	// Create a vector of inputs.
	std::vector<torch::jit::IValue> inputs;
	inputs.push_back(torch::ones({1, 3, 224, 224}));

	// Deserialize the ScriptModule from a file using torch::jit::load().
	std::shared_ptr<torch::jit::script::Module> module = torch::jit::load("./lc_model.pt");
	assert(module != nullptr);
	std::cout << "load model ok\n";

	cout << "Hello, world!" << endl;
}
```

## Environment

python collect_env.py
```
**Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: CentOS Linux 7 (Core)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36)
CMake version: version 2.8.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 430.26
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.14.3
[pip] numpydoc==0.8.0
[pip] torch==1.1.0
[pip] torchvision==0.3.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.2                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.1            py36h3010b51_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] torch                     1.1.0                     <pip>
[conda] torchvision               0.3.0                     <pip>**


 - PyTorch Version: 1.1.0
 - OS:centos 7
 - How you installed PyTorch (`conda`, `pip`, source):  pip3 install torch torchvision
 - libtorch : https://download.pytorch.org/libtorch/cu90/libtorch-shared-with-deps-latest.zip

 - Python version: 3.6.5
 - CUDA/cuDNN version: cuda 9.0, cudnn7.0.5
 - GPU models and configuration: GTX 1080TI
 - Any other relevant information:

## Additional context
I use download libtorch 1.1
libtorch1.1.0

<!-- Add any other context about the problem here. -->

**Comment by jamesr66a** [comment] 2019-06-25 20:52
Hi @azuredsky, does the same code work if you instead pass in a fully-qualified path name to the file? And can you confirm that `./lc_model.pt` lives in the `pwd` of where you invoke your C++ binary?

**Comment by azuredsky** [comment] 2019-06-26 00:34
> Hi @azuredsky, does the same code work if you instead pass in a fully-qualified path name to the file? And can you confirm that `./lc_model.pt` lives in the `pwd` of where you invoke your C++ binary?

yes ,I'm sure ,I try the full path model instead,and it's the same failed messege.

**Comment by azuredsky** [comment] 2019-06-26 08:05
I solved it with torch script,thank you

**Comment by Jubird915** [comment] 2019-07-04 13:50
I met the same issue when I ran the command: example-app ../model.pt
./example-app ../model.pt 
terminate called after throwing an instance of 'c10::Error'
  what():  open file failed, file path: model.pt (FileAdapter at /pytorch/caffe2/serialize/file_adapter.cc:11)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7fe893af12a1 in /home/huzhipeng/learnAI/utility/libtorch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7fe893af042a in /home/huzhipeng/learnAI/utility/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::FileAdapter::FileAdapter(std::string const&) + 0x266 (0x7fe896f98986 in /home/huzhipeng/learnAI/utility/libtorch/lib/libtorch.so)
frame #3: torch::jit::load(std::string const&, c10::optional<c10::Device>, std::unordered_map<std::string, std::string, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, std::string> > >&) + 0x30 (0x7fe897c96ee0 in /home/huzhipeng/learnAI/utility/libtorch/lib/libtorch.so)
frame #4: main + 0x8d (0x40636c in ./example-app)
frame #5: __libc_start_main + 0xf0 (0x7fe894887830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #6: _start + 0x29 (0x406049 in ./example-app)

Aborted (core dumped)


anyone can help me?

**Comment by zhangjinsong3** [comment] 2019-07-05 02:23
@azuredsky Meet the same issue. How did you solve it?

**Comment by azuredsky** [comment] 2019-07-05 02:36
First, Be sure your model is saved by torch script. Second, When I use centos7 and gcc 4.8.5, it have the same problem, Instead  I change gcc to gcc4.9.2 ,it sloved @Jubird915  @zhangjinsong3

**Comment by zhangjinsong3** [comment] 2019-07-05 03:52
I tried gcc-4.9, and it works for me. I use ubuntu 16.04 and neither gcc 4.9.3 nor gcc 5.4.0  run correctly.
@azuredsky

**Comment by suo** [comment] 2019-12-13 21:48
Going to close this out as there has not been much activity and the issue is not reproducible. Feel free to reopen if you want us to take another look!

**Closed by suo** 2019-12-13 21:48 UTC
Labels: jit, module: cpp, triaged
