### ISSUE TITLE
Problem with BCELoss with weight

### ISSUE THREAD

**Issue by nian-liu** [pytorch/pytorch#1543] opened 2017-05-12 07:58 UTC
I am using the BCELoss for input and target with size of batchsize * channel * height * width, I also want to weight the loss using a weight matrix of the same size, then I get the below error:

File "/home/nianliu/anaconda3/lib/python3.6/site-packages/torch/nn/_functions/thnn/loss.py", line 15, in _resize_weight
    self.weight = self.weight.view(1, target.size(1)).expand_as(target)
RuntimeError: size '[1 x 1]' is invalid for input of with 320 elements at /py/conda-bld/pytorch_1493680494901/work/torch/lib/TH/THStorage.c:59

Apparently, on this line, it's incorrect to reshape the weight matrix to the size of 1*target.size(1), unless only the channel-wise weights are allowed. 

Since one may want to use sample-wise weights, channel-wise weights, pixel-wise weights, element-wise weights (jusk like my case), or other forms, I think we may remove the expanding operation and let users do it by themselves to ensure the flexibility.

**Comment by fmassa** [comment] 2017-05-12 22:57
I stumbled across this issue today as well. You can for the moment just view your tardet tensor to be 1d, but this should be fixed.

**Comment by apaszke** [comment] 2017-05-13 10:55
Duplicate of #264

**Closed by apaszke** 2017-05-13 10:55 UTC

**Comment by wlwsea** [comment] 2017-10-30 07:53
@nian-liu  @fmassa @apaszke @eklitzke @jfsantos 
hi, i met the same problem with you.  Have you solved this?
I also want to weitht the BCEloss, for example weight = 10 for class 1,  weight = 1 for class 2

**Comment by apaszke** [comment] 2017-10-30 09:30
You can always use `class_weights[labels]` as the weights vector for your loss

**Comment by wlwsea** [comment] 2017-10-30 10:50
@apaszke 
Thank you! 
But, for example, 
```
loss = torch.nn.BCEWithLogitsLoss()
Loss = self.loss(self.fake_B, self.real_B)
```
could you please show me where and how to use `class_weights[labels]`
`real_B is a tensor of 0,1 label `

**Comment by apaszke** [comment] 2017-10-30 11:12
`loss = F.binary_cross_entropy(self.fake_B, self.real_B, weights=class_weights[self.real_B])`

**Comment by wlwsea** [comment] 2017-10-30 11:39
@apaszke 
thanks a lot!
I still have a problem, my self.real_B si a Variable, 
So, how should i define `class_weights`?
