### ISSUE TITLE
PyTorch 1.8 CUDNN_STATUS_NOT_INITIALIZED

### ISSUE THREAD

**Issue by jonashaag** [pytorch/pytorch#53458] opened 2021-03-06 19:12 UTC
## 🐛 Bug

When running training with PyTorch 1.8 (installed using pip), I get `CUDNN_STATUS_NOT_INITIALIZED`. Works with PyTorch 1.7.1.

With `CUDA_LAUNCH_BLOCKING=1`:

```
Traceback (most recent call last):
  File "main.py", line 395, in do_train
    trainer.fit(system)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 457, in fit
    self.accelerator_backend.setup(model)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 48, in setup
    model.cuda(self.trainer.root_gpu)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/pytorch_lightning/utilities/device_dtype_mixin.py", line 130, in cuda
    return super().cuda(device=device)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/torch/nn/modules/module.py", line 491, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/torch/nn/modules/module.py", line 387, in _apply
    module._apply(fn)
  [Previous line repeated 6 more times]
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 186, in _apply
    self.flatten_parameters()
  File "/home/jo/.venvs/au/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 172, in flatten_parameters
    torch._cudnn_rnn_flatten_weight(
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_INITIALIZED
```

## Environment

```
Collecting environment information...
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Manjaro Linux (x86_64)
GCC version: (GCC) 10.2.0
Clang version: 11.0.1
CMake version: version 3.19.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: GeForce RTX 2080 Ti
Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] msgpack-numpy==0.4.7.1
[pip3] numpy==1.19.4
[pip3] pytorch-lightning==1.2.2
[pip3] pytorch-lightning-bolts==0.3.0
[pip3] pytorch-ranger==0.1.1
[pip3] torch==1.8.0
[pip3] torch-dct==0.1.5
[pip3] torch-optimizer==0.0.1a16
[pip3] torch-stoi==0.1.1
[pip3] torchaudio==0.8.0
[pip3] torchlibrosa==0.0.5
[pip3] torchvision==0.9.0
[conda] Could not collect
```

**Comment by ruotianluo** [comment] 2021-03-06 22:23
same here, was fine on 1080ti, but broke for 2080ti.

**Comment by gchanan** [comment] 2021-03-08 16:40
maybe related to https://github.com/pytorch/pytorch/issues/53336?

**Comment by malfet** [comment] 2021-03-10 17:47
Yes, CUDA-10.2 + sm_75 GPU (RTX 2080), closing as duplicate of #53336

**Closed by malfet** 2021-03-10 17:47 UTC
