### ISSUE TITLE
Speed of torch.istft in GPU settings

### ISSUE THREAD

**Issue by XPBooster** [pytorch/pytorch#84407] opened 2022-09-01 09:34 UTC
### 🐛 Description

The speed of torch.istft is much slower than its inverse torch.stft, and cannot be accelerated with cuda.
Specifically, you can reproduce the results by running the code as follow:
```python
device = torch.device('cuda')
t = torch.tensor([i/50 for i in range(50)])
input = torch.sin(t)
input = torch.stack([input for i in range(64*512)], dim=0)
input = input.to(device)
import time
start = time.time()
stft = torch.stft(input, 16, 10)
print(time.time()-start) # 0.00044
torch.istft(stft, 16, 10) - input
print(time.time()-start) # 0.5130
```
where the time of stft (istft) is 0.0004 (0.51). 
I further investigated the time under cpu setting, where the time of stft (istft) is 0.03 (0.15). 
It is strange because **stft runs faster on cuda, while istft runs much more slower on cuda**.
```python
device = torch.device('cpu')
t = torch.tensor([i/50 for i in range(50)])
input = torch.sin(t)
input = torch.stack([input for i in range(64*512)], dim=0)
input = input.to(device)
import time
start = time.time()
stft = torch.stft(input, 16, 10)
print(time.time()-start) # 0.0399
torch.istft(stft, 16, 10) - input
print(time.time()-start) # 0.1512
```
Maybe there are some bottleneck in torch.istft that limits its speed?

### Version

pytorch 1.12

cc @ngimel @mruberry @peterbell10

**Comment by XPBooster** [comment] 2022-09-01 10:00
I think it is because istft is not parallel w.r.t. the batch size. for example, if we set the batch_size from 64*512 to 64, we have 0.0004 (0.0021) for stft (istft). While for batch_size 64*512, we have 0.0004 (0.51) for stft (istft). As such, istft fails to conduct parallel computation w.r.t. batch_size.

**Comment by XPBooster** [comment] 2022-09-04 13:23
Hello. If there is any inspiration or localization of this abnormality, please comment me directly.

Best.

**Comment by ngimel** [comment] 2022-09-04 17:49
cc @peterbell10

**Comment by peterbell10** [comment] 2022-09-04 18:15
Yes, the profiler revealed the problem is coming from `at::col2im` which handles batch dimensions by launching kernels in a loop:
https://github.com/pytorch/pytorch/blob/7c4c7dafbdf2c41ccd9042f1db4f9f9f01a42f00/aten/src/ATen/native/cuda/Col2Im.cu#L122-L126 

Each individual kernel in this case isn't anywhere near large enough to saturate the hardware so it ends up being much slower.

**Comment by XPBooster** [comment] 2022-09-06 08:26
Many thanks for this accurate feedback by @peterbell10 ! 

Is there any approach/reference for me to fix this problem? Will this problem be fixed in the next official release of pytorch?

Best regards.

**Comment by Lezcano** [comment] 2022-09-06 09:48
There's a fix in https://github.com/pytorch/pytorch/pull/84543. When that PR is merged, you can start  using it in the nightly releases. It will also be present in the next release.

**Closed** 2022-09-06 21:17 UTC
Labels: module: cuda, triaged, module: fft
