### ISSUE TITLE
Results from pytorch  and ONNX BERT model are different

### ISSUE THREAD

**Issue by JohannaOm** [pytorch/pytorch#52667] opened 2021-02-23 13:30 UTC
Hi,

I am trying to export bert_base to onnx format with the following code:

```
import torch.onnx
from transformers import BertTokenizer, BertModel
import torch
import onnx
import onnxruntime
import numpy as np
import os

os.environ['KMP_DUPLICATE_LIB_OK']='True'

model = BertModel.from_pretrained('bert-base-uncased')
model.eval()
use_gpu = torch.cuda.is_available()
device = torch.device("cuda" if use_gpu else "cpu")

# Get the first example data to run the model and export it to ONNX
max_seq_length = 512
inputs = {"input_ids": torch.ones(1, max_seq_length, dtype=torch.int64),
          "attention_mask": torch.ones(1, max_seq_length, dtype=torch.int64),
          "token_type_ids": torch.ones(1, max_seq_length, dtype=torch.int64)}

outputs = model(**inputs)

# export model to onx
symbolic_names = {0: 'batch_size', 1: 'max_seq_len'}
torch.onnx.export(model, args=tuple(inputs.values()), f='bert_onnx.onnx',
                  input_names=['input_ids','token_type_ids','attention_mask'],
                  output_names=['output'],
                  dynamic_axes={'input_ids': symbolic_names,  # variable lenght axes
                                'token_type_ids': symbolic_names,
                                'attention_mask': symbolic_names},
                  do_constant_folding=True,
                  opset_version=11)
                  #operator_export_type=torch.onnx.OperatorExportTypes.ONNX_ATEN_FALLBACK)

onnx_model = onnx.load("bert_onnx.onnx")
onnx.checker.check_model(onnx_model)
ort_session = onnxruntime.InferenceSession("bert_onnx.onnx")

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

# compute ONNX Runtime output prediction
# inputs to onnx format
ort_inputs = {
'input_ids':inputs['input_ids'].cpu().numpy(),
"attention_mask":inputs['attention_mask'].cpu().numpy(),
"token_type_ids":inputs['token_type_ids'].cpu().numpy()
}
# outputs
ort_outs = ort_session.run(None, ort_inputs)
print('####ONNX Result')
print(ort_outs[0])

# Sanity check
# compare ONNX Runtime and PyTorch results
# export input
np.testing.assert_allclose(to_numpy(outputs.last_hidden_state), ort_outs[0], rtol=1e-03, atol=1e-05)

print("Exported model has been tested with ONNXRuntime, and the result looks good!")

# new input
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
new_inputs = tokenizer("Hello world", padding='max_length' , return_tensors="pt")
new_outpus = model(**new_inputs)
new_hidden_state = new_outpus.last_hidden_state
print('#### Last hidden state ',new_hidden_state)
new_ort_inputs = {
'input_ids':new_inputs['input_ids'].cpu().numpy(),
"attention_mask":new_inputs['attention_mask'].cpu().numpy(),
"token_type_ids":new_inputs['token_type_ids'].cpu().numpy()
}
new_ort_outs = ort_session.run(None, new_ort_inputs)
print('#### NEW ONNX Result')
print(new_ort_outs[0])
np.testing.assert_allclose(to_numpy(new_hidden_state), new_ort_outs[0], rtol=1e-03, atol=1e-05)

```

Versions of the packages
````
python 3.8
torch 1.7.1
onnx 1.8.1
onnxruntime 1.6.0
numpy 1.19.5
````

During the conversion I get the following trace warnings:

```
TracerWarning: Converting a tensor to a Python index might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  position_ids = self.position_ids[:, past_key_values_length : seq_length + past_key_values_length]
TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
  assert all(
````
After the conversion, the results from pytorch BERT and ONNX model are different.

`````
AssertionError: 
Not equal to tolerance rtol=0.001, atol=1e-05

Mismatched elements: 393107 / 393216 (100%)
Max absolute difference: 9.089439
Max relative difference: 112627.73
 x: array([[[-0.168883,  0.136063, -0.1394  , ..., -0.625112,  0.052173,
          0.367145],
        [-0.363275,  0.141218,  0.879987, ...,  0.10433 ,  0.288758,...
 y: array([[[-0.257178,  0.512342,  0.448079, ..., -0.335979,  0.382206,
         -0.258338],
`````
Does anyone have any suggestion what could cause the problem?

Thanks a lot in advance!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by kshitij12345** [comment] 2021-02-23 13:42
Following link could be helpful 
https://huggingface.co/transformers/serialization.html#onnx-onnxruntime

**Comment by spandantiwari** [comment] 2021-02-23 17:57
@JohannaOm  - which ONNX backend are you using for inference? Can you provide a full repro, including the exact versions of the packages that you are using?

**Comment by JohannaOm** [comment] 2021-02-25 13:50
@spandantiwari Hi, I just added the whole code and package versions

**Comment by neginraoof** [comment] 2021-02-26 20:59
Hi @JohannaOm 
Looks like the order of inputs to BertModel is different than tokenzier outputs.
I modified your code a bit to match the input orders:

```
    import torch.onnx
    from transformers import BertTokenizer, BertModel
    import torch
    import onnx
    import onnxruntime
    import numpy as np
    import os

    os.environ['KMP_DUPLICATE_LIB_OK'] = 'True'

    model = BertModel.from_pretrained('bert-base-uncased')
    model.eval()

    max_seq_length = 512
    inputs = {"input_ids": torch.ones(1, max_seq_length, dtype=torch.int64),
              "attention_mask": torch.ones(1, max_seq_length, dtype=torch.int64),
              "token_type_ids": torch.ones(1, max_seq_length, dtype=torch.int64)}
    print(inputs)

    outputs = model(**inputs)

    # export model to onx
    symbolic_names = {0: 'batch_size', 1: 'max_seq_len'}
    torch.onnx.export(model, args=tuple(inputs.values()), f='bert_onnx.onnx',
                      input_names=['input_ids', 'attention_mask', 'token_type_ids'],
                      output_names=['output'],
                      dynamic_axes={'input_ids': symbolic_names,  # variable lenght axes
                                    'attention_mask': symbolic_names,
                                    'token_type_ids': symbolic_names},
                      do_constant_folding=True,
                      opset_version=11)

    onnx_model = onnx.load("bert_onnx.onnx")
    onnx.checker.check_model(onnx_model)
    ort_session = onnxruntime.InferenceSession("bert_onnx.onnx")

    def to_numpy(tensor):
        return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

    # compute ONNX Runtime output prediction
    # inputs to onnx format
    ort_inputs = {
        'input_ids': inputs['input_ids'].cpu().numpy(),
        "attention_mask": inputs['attention_mask'].cpu().numpy(),
        "token_type_ids": inputs['token_type_ids'].cpu().numpy()
    }
    # outputs
    ort_outs = ort_session.run(None, ort_inputs)
    print('####ONNX Result')
    # Sanity check
    # compare ONNX Runtime and PyTorch results
    # export input
    np.testing.assert_allclose(to_numpy(outputs.last_hidden_state), ort_outs[0], rtol=1e-03, atol=1e-05)

    print("Exported model has been tested with ONNXRuntime, and the result looks good!")
    # new input
    text = """The rapid growth of submissions and the increasing popularity of preprints have caused several problems to the current ACL reviewing system. To address these problems, the ACL Committee on Reviewing has been working on two proposals for reforming the reviewing system of ACL-related conferences: short-term and long-term. The following document presents the short-term proposals: https://www.aclweb.org/adminwiki/index.php?title=Short-Term_Reform_Propo... It consists of four complementary actions that can be realistically implemented to improve the ACL review process in the near future (while the committee continues to investigate changes that require a longer lead time). These actions address several of the problems identified in the proposal. The ACL Executive Committee has adopted these proposals. We hope that their implementation will have a quick positive impact on reviewing at ACL conferences."""
    tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
    new_inputs = tokenizer(text, padding='max_length', max_length=128, return_tensors="pt")

    new_outpus = model(**new_inputs)
    new_hidden_state = new_outpus.last_hidden_state
    # print('#### Last hidden state ', new_hidden_state)
    new_ort_inputs = {
        'input_ids': new_inputs['input_ids'].cpu().numpy(),
        "attention_mask": new_inputs['attention_mask'].cpu().numpy(),
        "token_type_ids": new_inputs['token_type_ids'].cpu().numpy(),
    }
    ort_session = onnxruntime.InferenceSession("bert_onnx.onnx")
    new_ort_outs = ort_session.run(None, new_ort_inputs)
    np.testing.assert_allclose(to_numpy(new_hidden_state), new_ort_outs[0], rtol=1e-03, atol=1e-05)
```

However, with short sentences and longer tokenizer padding length, I'm still seeing a mismatch in the outputs that we need to look more into. Can you confirm the observed behavior on your side?

**Comment by JohannaOm** [comment] 2021-03-01 09:24
@neginraoof Thank you so much for your help!!!
I just ran your code with short text and pass the sanity test:
````
text = "Hello World"
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
new_inputs = tokenizer(text, padding='max_length', max_length=512, return_tensors="pt")

````
Which input causes mismatch?

**Comment by neginraoof** [comment] 2021-03-02 16:00
Great.
There's an issue in exporting embedding layer in pytorch nighlty version. The issue is due to an update in torch embedding op committed recently. Exporter needed an update to match the torch operator.
Here is the fix for that: https://github.com/pytorch/pytorch/pull/53053
Though it does not affect your model since you're using version 1.7.1.

**Comment by garymm** [comment] 2022-05-04 23:10
Sounds like this was resolved by changing the order of the inputs. Please open a new issue if this is still a problem with the latest PyTorch nightly.

**Closed by garymm** 2022-05-04 23:10 UTC
Labels: module: onnx, triaged
