### ISSUE TITLE
[yolo_decode.cu:122]:launch failed: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by yxplus1116** [pytorch/pytorch#107665] opened 2023-08-22 06:10 UTC
### 🐛 Describe the bug

![image](https://github.com/pytorch/pytorch/assets/40259902/ded3a856-2ad5-4eb7-a3f5-a70ba1911888)
CUDA V11.6

### Versions

CUDA --11.6

cc @ptrblck

**Comment by ptrblck** [comment] 2023-10-11 04:32
It's unclear if and how the issue is related to PyTorch as @yxplus1116 didn't post the required setup information and also no code snippet to reproduce the issue. The screenshot also shows `yolo_decode.cu`, which points to a custom CUDA extension, so I'll close the issue.

**Closed by ptrblck** 2023-10-11 04:32 UTC
Labels: module: cuda, triaged
