### ISSUE TITLE
serializing large tensors results in system error or zero

### ISSUE THREAD

**Issue by soumith** [pytorch/pytorch#1031] opened 2017-03-18 02:50 UTC
```python
import torch

a = torch.ones(800*3*480*640)
print(a.eq(0).sum())
torch.save(a, 'a.pth')
b = torch.load('a.pth')

print(b.eq(0).sum())
```

Running this on OSX:
```
0
Traceback (most recent call last):
  File "a.py", line 5, in <module>
    torch.save(a, 'a.pth')
  File "/Users/soumith/code/pytorch/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/Users/soumith/code/pytorch/torch/serialization.py", line 192, in _save
    serialized_storages[key]._write_file(f)
RuntimeError: Unknown error: -1
```

More details of failure in Ubuntu 14.04.1 in https://discuss.pytorch.org/t/value-changed-after-loading-a-saved-tensor/1133

**Comment by Jerrynet** [comment] 2017-03-18 04:14
Maybe it's caused by a [pickle bug](http://stackoverflow.com/questions/31468117/python-3-can-pickle-handle-byte-objects-larger-than-4gb)?

I just test this code and it doesn't work (on Mac OS X 10.12.3 with Python 3.6):
```python
import torch

a = torch.ones(800*3*480*640)
b = a.numpy()
torch.save(b, 'b.pth')
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jerry/anaconda/envs/tensorflow/lib/python3.6/site-packages/torch/serialization.py", line 120, in save
    return _save(obj, f, pickle_module, pickle_protocol)
  File "/Users/jerry/anaconda/envs/tensorflow/lib/python3.6/site-packages/torch/serialization.py", line 186, in _save
    pickler.dump(obj)
OSError: [Errno 22] Invalid argument
```

**Comment by jekbradbury** [comment] 2017-03-18 09:10
That thread links to this one http://bugs.python.org/issue24658, which says it’s an OS bug and proposes a workaround patch that hasn’t been merged. There’s also a numpy issue thread, which links to this Torch7 commit that implements a workaround https://github.com/torch/DEPRECEATED-torch7-distro/commit/40e65934e071e452f194a9d8c0fd740131babefa

**Comment by apaszke** [comment] 2017-03-18 10:57
We're doing a loop in case it writes less, but we always pass the full amount of remaining bytes. Putting a cap (std::min with INT_MAX) on the size of a single write might help.

**Comment by apaszke** [comment] 2017-03-22 12:09
I can't reproduce it on CentOS. I think it might have been a report for a PyTorch version prior to fixing #717.

**Closed** 2017-03-23 02:06 UTC
Labels: bug, high priority
