### ISSUE TITLE
Pytorch DCN native support

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#28486] opened 2019-10-23 02:26 UTC
Since DCN make convolution networks gain a massive accuracy, it's that possible adding DCN inside pytorch natively?

Or does it already supported in somewhere in someway?

**Comment by fmassa** [comment] 2019-10-23 12:43
Duplicate of https://github.com/pytorch/pytorch/issues/15864 and https://github.com/pytorch/pytorch/issues/2260

Let's add such a layer in torchvision

**Closed by fmassa** 2019-10-23 12:43 UTC
