### ISSUE TITLE
Statically linking to libtorch but also needing the shared library “libcaffe2_nvrtc.so”?

### ISSUE THREAD

**Issue by wahlberg82** [pytorch/pytorch#45603] opened 2020-09-30 20:30 UTC
## 🐛 Bug

Hi,
I started by posting a question in the forums here: https://discuss.pytorch.org/t/statically-linking-to-libtorch-but-also-needing-the-shared-library-libcaffe2-nvrtc-so/97166/2
But was asked to also post it here as well, so that why I'm writing this now.

I’m building a plugin for a commercial software application that is internally using libtorch. This plugin, which is in the form of a shared library (.so file), is statically linking libtorch (i.e. it’s baking all of it into it’s own so-file). The only libraries that are dynamically linked against are the CUDA libs and some standard system libraries of course. This plugin needs to be portable to other systems without the need to install lots of dependencies (CUDA is fine to be needed as an additional install).

Everything works, except I can’t get my shared library to not also need the torch library “libcaffe2_nvrtc.so”. Since it doesn’t exist a static version of this library “libcaffe2_nvrtc.a”, I can’t seem to get around it. Is there a way to not have libtorch dynamically depend on this library and still have GPU support? I can build libtorch with CPU support only, and then I don’t have the problem, but I need the GPU acceleration.

My guess here is that the libcaffe2_nvrtc library can’t be made static since it directly depends on CUDA which doesn’t exist statically, but that is only my guess, I and would like somebody more knowledgeable to confirm that this is the case. If so, I guess I just have to live with being forced to also distribute the file “libcaffe2_nvrtc.so” together with my plugin, right? Any other suggestions or solutions to get around this issue?

Cheers, David

## To Reproduce

1. Compile pytorch statically with CUDA support (-DBUILD_SHARED_LIBS=OFF -DUSE_MKLDNN=OFF -DUSE_CUDA=ON)
1. You do get all the static libraries as .a-files of course. But the "libcaffe2_nvrtc" library does still become a dynamic .so-file.
1. Compile and link an executable or dynamic library against the static libtorch. Torch will work, but still needs the file libcaffe2_nvrtc.so" to be around. All other libtorch dependencies are successfully baked into the new executable/dynamic library and will work. It will also work with CUDA and GPU acceleration.

## Expected behavior

That all libtorch libraries compiled to be static .a-files, that I could link against to not need extra dynamic library files on the side when I distribute my .so-file to other systems (where libtorch is not installed).

## Environment

PyTorch version: 1.7.0a0+2163d31
Is debug build: True
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: CentOS Linux 7 (Core) (x86_64)
GCC version: (GCC) 7.3.1 20180303 (Red Hat 7.3.1-5)
Clang version: Could not collect
CMake version: version 3.14.0

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.1.243
GPU models and configuration: GPU 0: GeForce GTX 1080 Ti
Nvidia driver version: 450.51.05
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.7.0a0+eeb43ff
[pip3] torchvision==0.8.0a0+2801a76
[conda] blas                      1.0                         mkl  
[conda] magma-cuda101             2.5.2                         1    pytorch
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2020.1                      217  
[conda] mkl-include               2020.1                      217  
[conda] mkl-service               2.3.0            py36he904b0f_0  
[conda] mkl_fft                   1.1.0            py36h23d657b_0  
[conda] mkl_random                1.1.1            py36h0573a6f_0  
[conda] numpy                     1.19.1           py36hbc911f0_0  
[conda] numpy-base                1.19.1           py36hfa32c7d_0  
[conda] torch                     1.7.0a0                  pypi_0    pypi
[conda] torchvision               0.8.0a0+38aab83          pypi_0    pypi

 - How you installed PyTorch: source
 - Build command you used (if compiling from source): cmake -GNinja -DBUILD_SHARED_LIBS=OFF -DUSE_MKLDNN=OFF -DUSE_CUDA=ON ..

## Additional context

Thanks,
David

cc @malfet @seemethere @walterddr

**Comment by izdeby** [comment] 2020-09-30 23:17
Im not sure how to triage this.

**Comment by ngimel** [comment] 2020-10-01 03:16
Looks like a dupe of #31985

**Comment by ezyang** [comment] 2020-10-05 17:05
nvrtc is being worked on in the other issue, closing this.

**Closed by ezyang** 2020-10-05 17:05 UTC
Labels: module: build, triage review
