### ISSUE TITLE
Pypi is missing dependencies

### ISSUE THREAD

**Issue by amfournda** [pytorch/pytorch#105731] opened 2023-07-21 13:38 UTC
### 🐛 Describe the bug

Asking Pypi.org for a list of dependencies for torch does not provide a complete list of dependencies. See the list from pypi's json:
```
~$ curl -s 'https://pypi.org/pypi/torch/json' | jq '.info.requires_dist|.[]'
"filelock"
"typing-extensions"
"sympy"
"networkx"
"jinja2"
"opt-einsum (>=3.3) ; extra == 'opt-einsum'"
```
And now compare it with the actual list of dependencies in the wheel file's metadata:
```
~$ grep -i requires-dist torch-2.0.1-cp39-cp39-manylinux1_x86_64/torch-2.0.1.dist-info/METADATA
Requires-Dist: filelock
Requires-Dist: typing-extensions
Requires-Dist: sympy
Requires-Dist: networkx
Requires-Dist: jinja2
Requires-Dist: nvidia-cuda-nvrtc-cu11 (==11.7.99) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-runtime-cu11 (==11.7.99) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cuda-cupti-cu11 (==11.7.101) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cudnn-cu11 (==8.5.0.96) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cublas-cu11 (==11.10.3.66) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cufft-cu11 (==10.9.0.58) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-curand-cu11 (==10.2.10.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusolver-cu11 (==11.4.0.1) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-cusparse-cu11 (==11.7.4.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nccl-cu11 (==2.14.3) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: nvidia-nvtx-cu11 (==11.7.91) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: triton (==2.0.0) ; platform_system == "Linux" and platform_machine == "x86_64"
Requires-Dist: opt-einsum (>=3.3) ; extra == 'opt-einsum'
```
I don't know why all the nvidida-* packages, as well as triton, are missing from the requires_dist field in the JSON of this package. Should they be there? This is a serious problem for people who are trying to build a consistent private python package mirror on an isolated network. We need to be able to programmatically determine all the dependencies for a package so that when we mirror the package, we also mirror it's requirements. If we cannot do this accurately, installing this package will fail on machines that cannot access pypi.org and rely on the mirror I'm building. 

### Versions

This is not relevant to this bug, as it does not rely on any specific python environment.

cc @seemethere @malfet @osalpekar @atalman

**Comment by bm371613** [comment] 2023-08-17 07:25
I asked on PyPA's discord and apparently the `/pypi/` API simply inspects the first artifact of a release and shows its metadata.

So it would work if all wheels had these "pytorch_extra_install_requirements", as they seem to be called in the codebase. Hopefully it wouldn't cause any trouble, as `platform_system == 'Linux' and platform_machine == 'x86_64'` would only match on systems using these wheels like

```
torch-2.0.1-cp310-cp310-manylinux1_x86_64.whl
torch-2.0.1-cp311-cp311-manylinux1_x86_64.whl
torch-2.0.1-cp38-cp38-manylinux1_x86_64.whl
torch-2.0.1-cp39-cp39-manylinux1_x86_64.whl
```

and these wheels have the `pytorch_extra_install_requirements` already.

Is this an acceptable solution?

cc @ptrblck (hopefully the person to ask, based on git blame `.github/scripts/generate_binary_build_matrix.py`)

**Comment by bm371613** [comment] 2023-08-17 10:27
duplicate of https://github.com/pytorch/pytorch/issues/100974

**Comment by bm371613** [comment] 2023-08-17 19:29
I discussed how poetry could handle this in https://github.com/python-poetry/poetry/issues/8326

In a https://github.com/python-poetry/poetry/issues/8326#issuecomment-1682808158, a poetry contributor suggested
- the same dependencies in all artifacts, with markers, as proposed above
- if needed, own build backend that follows PEP 517

**Comment by malfet** [comment] 2024-01-30 17:33
Closing, as our dependencies on PyPI are correct now. But please do not hesitate to open a new issue (or reopen this one) if it regresses

**Closed by malfet** 2024-01-30 17:33 UTC
Labels: module: binaries, triaged
