### ISSUE TITLE
mypy throws a lot of module has no attribute errors

### ISSUE THREAD

**Issue by vikigenius** [pytorch/pytorch#42787] opened 2020-08-08 23:45 UTC
## To Reproduce

1. ```mypy -c 'import torch; print(torch.cat)```

```
mypy -c 'import torch; print(torch.cat)'
<string>:1: error: Module has no attribute "cat"; maybe "_cat"?
```

The same error is reported for a lot of functions like arange, Size, max, long
## Expected behavior

mypy should be able to recognize these functions as attributes

## Environment

 - PyTorch Version: 1.6.0
 - OS (e.g., Linux): Linux
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.8
 - CUDA/cuDNN version: 10.2

## Additional context

I also tested the above using the latest nightly build and it has the same error. Older release that I was using: 1.4.0 did not produce this error. Also mypy takes unusually long for syntax checks with the latest pytorch version. It was much faster in older versions for some reason.

cc @ezyang @malfet @rgommers

**Comment by malfet** [comment] 2020-08-10 22:41
Related to https://github.com/pytorch/pytorch/issues/16574

**Comment by rgommers** [comment] 2020-08-10 22:57
I wonder if there's a place we can put a "Using mypy with PyTorch is incomplete as of now" statement somewhere visible enough.

> Also mypy takes unusually long for syntax checks with the latest pytorch version. It was much faster in older versions for some reason.

Isn't it just that there are many more type annotations in the code base now than in 1.4.0?

**Comment by rgommers** [comment] 2020-08-11 22:16
I cannot reproduce this on either 1.6.0 installed with conda, or master built from source. A valid annotation for `torch.cat` is present in `torch/_C/_VariableFunctions.pyi`, also in the Python 3.8 pip and conda packages.

@vikigenius maybe you are using the wrong `mypy`, installed in a different env from PyTorch itself? You can verify that the annotation is present by checking
```
# change ~/anaconda3/ to your Anaconda/Miniconda install location if needed
~/anaconda3/envs/pytorch-16-pip/lib/python3.8/site-packages/torch/_C/_VariableFunctions.pyi
```

Use 
```
$ python -m mypy -c 'import torch; print(torch.cat)'
```
if you need to be sure you're using the correct `mypy` for your env.

**Comment by vikigenius** [comment] 2020-08-12 01:10
@rgommers On further debugging I realized that it was an issue because of the default configuration I was using.

I typically use

```
implicit_reexport = False
```

Allowing implicit reexports causes the attribute error issues to go away.

**Comment by rgommers** [comment] 2020-08-12 01:27
> Now that I know what's causing the error it doesn't seem like a big issue, although I personally do not like implicit reexports

I suspect we don't want to change that. Building up a module namespace by importing objects (and their type annotations) from other private modules is very common, and really sane Python usage. At scale, doing `from foo import bar as bar` or dynamically updating `__all__` is a little painful. The latter still has some use (e.g. for tab completion and `from ... import *` so could be considered.

@malfet, @ezyang any preference, wontfix or being diligent with `__all__` everywhere?

**Comment by ezyang** [comment] 2020-08-12 16:43
I'm not opposed to using `__all__` tactically, but trying to apply it everywhere sounds tough, especially when the list of identifiers is coming from some of our codegen stuff. If implicit reexports works, we should just make people use that.

**Comment by rgommers** [comment] 2020-08-12 17:04
I've had a look at the specific `torch.cat` issue in relation to `__all__` and it's already done correctly. Relevant code in `torch/__init__.py`:
```
# Appease the type checker; ordinarily this binding is inserted by the
# torch._C module initialization code in C
if False:
    import torch._C as _C

__all__ += [name for name in dir(_C)
            if name[0] != '_' and
            not name.endswith('Base')]
```

which puts `'cat'` where it belongs:
```
In [1]: import torch                                                            

In [2]: 'cat' in torch.__all__                                                  
Out[2]: True
```

So nothing left to do here.

> If implicit reexports works, we should just make people use that.

I agree, thanks for the input. I'll close this issue then.

**Closed by rgommers** 2020-08-12 17:04 UTC
Labels: module: typing, triaged
