### ISSUE TITLE
torch.compile correctness when nn.Module attribute changes or weight changes

### ISSUE THREAD

**Issue by haijieg** [pytorch/pytorch#120958] opened 2024-03-01 00:31 UTC
### 🐛 Describe the bug

What's is the behavior of when we `torch.compile` an `nn.Module` which has changed after compilation? There could be attribute change or a weight change. Current behavior is torchdynamo will not recompile and reuse the original compiled function which leads to surprise. A motivation example is the `lora` use case in diffuser library, in which a layer's behavior changes when a function is called  to change the layer's state, e.g. `set_lora_layer`, `fuse_lora`, `unfuse_lora`. See below for a repro that illustrates the problem.

### Minified repro

```python3
import torch
import torch.nn as nn
from typing import Optional

# Simplified example of the diffuser lora layer here: https://github.com/huggingface/diffusers/blob/main/src/diffusers/models/lora.py#L380
class LoraCompatibleLinear(nn.Linear):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.lora_layer = None

    def set_lora_layer(self, lora_layer: Optional[nn.Module]):
        self.lora_layer = lora_layer

    def forward(self, x):
        if self.lora_layer is None:
            return super().forward(x)
        else:
            return super().forward(x) + self.lora_layer(x)


def test(compile):
    net = LoraCompatibleLinear(1, 1)
    nn.init.ones_(net.weight)
    nn.init.zeros_(net.bias)
    lora_layer = nn.Linear(1, 1)
    nn.init.ones_(lora_layer.weight)
    nn.init.zeros_(lora_layer.bias)

    if compile:
        net = torch.compile(net)

    x = torch.ones(1, 1, 1)

    with torch.no_grad():
        # no lora
        y1 = net(x)
        # apply lora
        net.set_lora_layer(lora_layer)
        y2 = net(x)
        # update lora weight
        nn.init.constant_(lora_layer.weight, 2)
        y3 = net(x)

    # expect 1, 2, 3
    return y1, y2, y3


# without torch.compile the code returns expected `1, 2, 3`
print(test(False))

# with torch.compile the code returns unexpected `1, 1, 1`
print(test(True))
```

### Versions

[pip3] torch==2.1.0

cc @ezyang @msaroufim @bdhirsh @anijain2305 @zou3519 @chauhang @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @kadeng

**Comment by anijain2305** [comment] 2024-03-01 00:38
This is a duplicate of https://github.com/pytorch/pytorch/issues/111785

If you want to work around, you can use torch._dynamo.config.guard_nn_modules=True. This will incur performance penalty because TorchDynamo will insert additional guards inside the nn module hierarchy.

We are investigating how we can catch this without incurring large perf penalty.

**Comment by haijieg** [comment] 2024-03-01 01:31
Thank you for the quick response @anijain2305 . I tried the workaround, it does produce expected results. However, I notice that it only retrigger compilation when module attr changes, but not when module weights change. 

After adding the following change
```
def custom_compile(gm, inputs):
    print("Compile")
    return gm.forward

...
    if compile:
        net = torch.compile(net, backend=custom_compile)
...
```

There are only two "Compile" printed. When the module's weight changes it doesn't trigger the `custom_compile` function. It doesn't affect compiler backends like Inductor or eager, but will affect compiler backend like onnxruntime or tensorrt which bakes weight into the compiled function and assumes they don't change. Is there a similar `guard` on nn module's parameter change?

**Comment by anijain2305** [comment] 2024-06-10 04:45
This should be fixed now. Closing. Feel free to reopen if there are issues.

**Closed by anijain2305** 2024-06-10 04:45 UTC
Labels: triaged, oncall: pt2, module: dynamo
