### ISSUE TITLE
[JIT] undefined symbol: cuCtxGetCurrent

### ISSUE THREAD

**Issue by qbx2** [pytorch/pytorch#15048] opened 2018-12-11 06:12 UTC
## 🐛 Bug

jit_script_method, cuda, and skip connection with /2 occurs this bug.

## To Reproduce

```python
import torch
import torch.nn as nn


class Block(torch.jit.ScriptModule):
    def __init__(self, dim):
        super().__init__()

        self.linear = nn.Linear(dim, dim)
        self.relu = nn.ReLU()

    @torch.jit.script_method
    def forward(self, x):
        # x = x + self.linear(x)
        # x = x / 2.
        # return self.relu(x)
        return self.relu((self.linear(x) + x) / 2.)


m = Block(32)
x = torch.randn(1, 32)
print('cpu:', m(x))

m.cuda()
x = x.cuda()
print('gpu:', m(x))
```

```
$ python test_jit.py
cpu: tensor([[0.3313, 0.2135, 0.0000, 0.0000, 0.0000, 0.0000, 0.0486, 0.0308, 0.6912,
         0.5355, 0.4852, 0.0000, 0.1473, 0.5116, 0.8522, 0.2075, 0.6240, 0.0820,
         0.3366, 0.1562, 0.0000, 0.0000, 0.0000, 0.2413, 0.0000, 0.2346, 0.0000,
         0.0000, 0.0773, 0.0000, 0.0000, 0.3382]],
       grad_fn=<DifferentiableGraphBackward>)
python3: symbol lookup error: /home/qbx2/anaconda3/lib/python3.7/site-packages/torch/lib/libtorch.so.1: undefined symbol: cuCtxGetCurrent
```

## Expected behavior

GPU result is expected to be same with the CPU result.

## Environment
PyTorch version: 1.0.0a0+db5d313
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.1 LTS
GCC version: (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
CMake version: version 3.12.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: GeForce RTX 2080
Nvidia driver version: 410.48
cuDNN version: Probably one of the following:
/usr/local/cuda-10.0/lib64/libcudnn.so.7.4.1
/usr/local/cuda-10.0/lib64/libcudnn_static.a

Versions of relevant libraries:
[pip] Could not collect
[conda] magma-cuda100             2.4.0                         1    pytorch
[conda] torch                     1.0.0a0+db5d313           <pip>

## Additional context
Disabled USE_NCCL in tools/setup_helpers/nccl.py while build to bypass compile errors.

EDIT: Rebuilt with USE_NCCL enabled but did not help :/

**Comment by zou3519** [comment] 2018-12-11 16:07
I can't reproduce this on my machine, but one thing to note:
- cuCtxGetCurrent is provided by the CUDA API so I'm surprised that it is complaining that it doesn't exist

**Comment by qbx2** [comment] 2018-12-11 16:30
```
$ python test/test_cuda.py
......ssss........ssssssssssssssssssssssss..................................................................................................................................................................ssss........ssssssssssssssssssssssss..............................................................................................................................................................................................................................................
...............................................................................................................................................................................................................................................
...............................................................................................................................................................................................................................................
...............................................................................................................................................................................................................................................
............................................................................................................................................ssss........ssssssssssssssssssssssss...............................................................
.........................................................................................................ssss........ssssssssssssssssssssssss..................................................................................................
......................................................................ssss........ssssssssssssssssssssssss.....................................................................................................................................
.............................ss....sss.s...s.s.......s...s...........ss..s............s....ssss...s............sss..ssssssss....s.s....s........s.....
----------------------------------------------------------------------
Ran 2062 tests in 96.400s

OK (skipped=174)

```

**Comment by qbx2** [comment] 2018-12-11 16:56
Could this issue be related to https://github.com/pytorch/pytorch/issues/14310 ?

**Comment by zou3519** [comment] 2018-12-11 18:41
@qbx2 let me try to grab a cuda 10 machine and see if I can repro this

**Comment by orionr** [comment] 2019-01-14 19:47
@zou3519 were you able to reproduce this? Did @zdevito's fix take care of this? Also cc @pjh5.

**Comment by zou3519** [comment] 2019-01-14 19:50
@orionr I was not able to reproduce this (wasn't able to get a cuda 10 machine, though this problem is probably not cuda version related...) but @apaszke has run into this a lot

**Comment by orionr** [comment] 2019-01-14 22:08
I think @apaszke's workaround is the right option for now, but it looks like CUDA isn't being found correctly. @qbx2 if you built from source can you paste in your CMake / stdout logs here? Thanks.

**Comment by suo** [comment] 2019-02-04 20:22
Going to close this out since there hasn't been movement on this issue for a while. Feel free to reopen if you are seeing this issue.

**Closed by suo** 2019-02-04 20:22 UTC
Labels: jit, jit-triaged, needs-reproduction

**Comment by ebetica** [comment] 2019-02-07 20:23
I just ran into this problem: The source is that `libcuda.so` isn't in one of the standard locations. Somehow, most of what pytorch needs to do can be done without `libcuda.so`, but the jit relies on it. If you find a libcuda and move it to a standard location that pytorch can find, then you will solve the problem.

**Comment by zdevito** [comment] 2019-02-07 20:33
This is a weird nvidia issue:  I think libcuda is part of the driver, while libcudart is part of the cuda runtime. So they end up installed in different places and by different installers. Often libcuda is just in `/usr/lib` so dynamic linking works fine. But sometimes it gets in weird places.

**Comment by qbx2** [comment] 2019-02-09 09:50
ld.so.conf contained /usr/local/cuda-9.2 not cuda-10 so upgrading cuda version caused this issue. Thanks for all your help.

**Comment by qbx2** [comment] 2019-02-09 09:51
FYI, When you install cuda, there's message:

===========
= Summary =
===========

Driver:   Installed
Toolkit:  Installed in /usr/local/cuda-10.0
Samples:  Installed in /home/ubuntu, but missing recommended libraries

Please make sure that
 -   PATH includes /usr/local/cuda-10.0/bin
 -   LD_LIBRARY_PATH includes /usr/local/cuda-10.0/lib64, or, add /usr/local/cuda-10.0/lib64 to /etc/ld.so.conf and run ldconfig as root

**Comment by marijnfs** [comment] 2019-02-11 12:34
Just chiming in, we are having this problem as well, even after explicitly setting LD_LIBRARY_PATHS to the right cuda paths. We have also reproduced it on another system with only one cuda version installed. All are running 396.54 version of the drivers.

**Comment by ebetica** [comment] 2019-02-12 18:54
FYI my issue was actually https://github.com/pytorch/pytorch/issues/16860

Soumith explains: pytorch cannot link against `libcuda` and `libnvrtc`, since those are provided by the driver, which changes much more often than the library. Thus, PyTorch looks it up at runtime via loading a dummy nvrtc [here](https://github.com/pytorch/pytorch/blob/e48ffa84d801a546d1c25bf52867e0fed8805723/torch/__init__.py#L80).

In the case that you are using pytorch from Python, you simply have to make sure libcuda is in your LD_LIBRARY_PATH.

In the case (my case) that you are using pytorch from C++, you have to manually dlload the right libcuda and libnvrtc at run time from your code :(
