### ISSUE TITLE
unique() has bug with randperm() in 1.8.1 version

### ISSUE THREAD

**Issue by XuechaoChen** [pytorch/pytorch#60174] opened 2021-06-17 10:56 UTC
When I run the code demmonstrated in "## To Reproduce" block, I got "illegal memory access" error. However, I didn't encounter the same error when using pytorch 1.2/1.4 version. And there's no error when I use randperm() or unique() seperately.

## 🐛 Bug

Traceback (most recent call last):
  File "torch_unique_error.py", line 10, in <module>
    unq, unq_inv, unq_cnt = torch.unique(a, return_inverse=True, return_counts=True, dim=0)
  File "/home/xuechao/anaconda3/lib/python3.8/site-packages/torch/_jit_internal.py", line 363, in fn
    return if_true(*args, **kwargs)
  File "/home/xuechao/anaconda3/lib/python3.8/site-packages/torch/_jit_internal.py", line 363, in fn
    return if_true(*args, **kwargs)
  File "/home/xuechao/anaconda3/lib/python3.8/site-packages/torch/functional.py", line 737, in _unique_impl
    output, inverse_indices, counts = _VF.unique_dim(  # type: ignore
RuntimeError: merge_sort: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered

## To Reproduce

import torch

a = torch.rand((120000, 4))
a = a.cuda()
a = torch.floor(a/0.001)
a = a.long()
a[:, 0] = 0
b = torch.randperm(a.shape[0], device=a.device)
a = a[b, :]
unq, unq_inv, unq_cnt = torch.unique(a, return_inverse=True, return_counts=True, dim=0)

## Environment

 - PyTorch Version: 1.8.1
 - OS: Ubuntu18.04
 - How you installed PyTorch: pip
 - Python version: 3.8
 - CUDA/cuDNN version: 11.1/8.0.5

**Comment by gchanan** [comment] 2021-06-17 16:33
I reproduced this on 1.8.1, but it seems to be fixed on 1.9.0 -- I'd encourage you to upgrade.

**Closed by gchanan** 2021-06-17 16:33 UTC
