### ISSUE TITLE
`torch.nn.BCELoss` triggers CUDA error: device-side assert triggered when inputs are negative

### ISSUE THREAD

**Issue by creakseek** [pytorch/pytorch#85728] opened 2022-09-27 16:57 UTC
### 🐛 Describe the bug

`torch.nn.BCELoss` triggers CUDA error: device-side assert triggered when inputs are negative, and corrupts CUDA state for all following computation.

```
import torch

try:
    x = torch.tensor([-1.0]).cuda()
    y = torch.tensor([2.0]).cuda()
    loss = torch.nn.BCELoss().cuda()
    output = loss(x, y) # Causes CUDA internal assertion failure
except Exception as e:
    print("init: exception caught: {}".format(e))
else:
    print("init: no exception")

for i in range(10):
    try:
        a = torch.tensor([-1.0]).cuda()
        b = torch.tensor([2.0]).cuda()
        c = a + b # Raises CUDA exception again
    except Exception as e:
        print("{}: exception caught: {}".format(i, e))
    else:
        print("{}: no exception".format(i))
```

Outputs:
```
init: no exception
0: exception caught: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
1: exception caught: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
2: exception caught: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
......
```

### Versions

PyTorch version: 1.12.1+cu113
Is debug build: False
CUDA used to build PyTorch: 11.3
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.6
Libc version: glibc-2.26

Python version: 3.7.14 (default, Sep  8 2022, 00:06:44)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.10.133+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.12.1+cu113
[pip3] torchaudio==0.12.1+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.1
[pip3] torchvision==0.13.1+cu113
[conda] Could not collect

**Comment by ptrblck** [comment] 2022-09-30 07:00
This is expected behavior, since `nn.BCELoss` expects model outputs as probabilities in `[0, 1]`. If you want to use logits, use `nn.BCEWithLogitsLoss`.

The [forum](https://discuss.pytorch.org/) is usually a better place for these questions. Closing as it's expected behavior.

**Closed by ptrblck** 2022-09-30 07:00 UTC

**Comment by creakseek** [comment] 2022-10-11 16:01
@ptrblck 

Hi sorry for the late reply. The issue here is that in this code snippet:
```
try:
    x = torch.tensor([-1.0]).cuda()
    y = torch.tensor([2.0]).cuda()
    loss = torch.nn.BCELoss().cuda()
    output = loss(x, y) # Causes CUDA internal assertion failure
except Exception as e:
    print("init: exception caught: {}".format(e))
else:
    print("init: no exception")
```
While the correct input should be between 0 and 1, we cannot catch the CUDA internal assertion failure if the input is not correct (above code will print "init: no exception"). This is a problem because later on, any cuda operation will be corrupted -- throwing CUDA exception (which can be caught). Note that this does not happen on the CPU, where we can catch the runtime error of "RuntimeError: all elements of input should be between 0 and 1". 

This could potentially be a **security** bug because a failure here cannot be caught by the program and later execution results will be affected.
