### ISSUE TITLE
nn.Linear layer does not throw a shape mismatch error when using cuda devices

### ISSUE THREAD

**Issue by shagunsodhani** [pytorch/pytorch#62539] opened 2021-07-31 19:18 UTC
## 🐛 Bug

nn.Linear layer does not throw a shape mismatch error when using cuda devices

## To Reproduce

```
device = "cuda"
m = torch.nn.Linear(in_features=52, out_features=1024, bias=True).to(device)
x = torch.rand(128, 2306).to(device)
m(x)
tensor([[ 0.2474, -0.1177,  0.4088,  ..., -0.5289, -0.0780,  0.1490],
        [-0.2928, -0.2327,  0.7396,  ..., -0.2528, -0.0397,  0.4774],
        [ 0.0034, -0.3901,  0.5064,  ..., -0.3769,  0.0585, -0.0378],
        ...,
        [-0.1379, -0.1625,  0.8369,  ..., -0.1036,  0.1076,  0.1202],
        [-0.1220, -0.0746,  0.8498,  ..., -0.2635, -0.1965,  0.0457],
        [-0.0450,  0.0677,  0.5749,  ..., -0.1845, -0.1974,  0.3070]],
       device='cuda:0', grad_fn=<AddmmBackward>)
m(x).shape
torch.Size([128, 1024])
```

## Expected behavior

Should throw an error because shapes do not match. It throws an error on the CPU device.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```
Collecting environment information...
PyTorch version: 1.9.0
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8.6 | packaged by conda-forge | (default, Dec 26 2020, 05:05:16)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.4.0-52-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: Quadro GP100
GPU 1: Quadro GP100

Nvidia driver version: 450.80.02
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.3
[pip3] torch==1.9.0
[pip3] torch-tb-profiler==0.2.0
[pip3] torchaudio==0.9.0a0+33b2469
[pip3] torchvision==0.10.0
[conda] Could not collect

## Additional context

Colab Notebook: https://colab.research.google.com/drive/1mcTFI4GbP4cB17yWPukAF9wl3jIOGil0?usp=sharing

**Comment by ptrblck** [comment] 2021-07-31 19:47
Reproduced in `1.9.0` while the proper errors are raised in `1.10.0.dev20210718` and `torch-1.10.0.dev20210731`.
Searching for similar issues points to https://github.com/pytorch/pytorch/issues/61291 where @ngimel already isolated it to https://github.com/pytorch/pytorch/pull/57417.

**Comment by malfet** [comment] 2021-08-02 15:07
Closing as duplicate of  #61291

**Closed by malfet** 2021-08-02 15:07 UTC
