### ISSUE TITLE
Want RTX 2080ti Support!!! RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/

### ISSUE THREAD

**Issue by xiongzhp** [pytorch/pytorch#13038] opened 2018-10-24 08:22 UTC
I have two GPUs installed, with the same script, if I select to run on RTX 2080 Ti, the error occurs, and if I run on GTX 1080 Ti, it works right.

`~/Molecule_Optimizer.py in forward(self, atom_list, bond_list, atom_degree_list, bond_degree_list, atom_mask)
     33         atom_mask = atom_mask.unsqueeze(2)
     34         batch_size,mol_length,num_atom_feat = atom_list.size()
---> 35         atom_feature = self.dropout(self.atom_fc(atom_list))
     36 
     37         bond_neighbor = [bond_list[i][bond_degree_list[i]] for i in range(batch_size)]

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py in __call__(self, *input, **kwargs)
    475             result = self._slow_forward(*input, **kwargs)
    476         else:
--> 477             result = self.forward(*input, **kwargs)
    478         for hook in self._forward_hooks.values():
    479             hook_result = hook(self, input, result)

~/anaconda3/lib/python3.6/site-packages/torch/nn/modules/linear.py in forward(self, input)
     53 
     54     def forward(self, input):
---> 55         return F.linear(input, self.weight, self.bias)
     56 
     57     def extra_repr(self):

~/anaconda3/lib/python3.6/site-packages/torch/nn/functional.py in linear(input, weight, bias)
   1024         return torch.addmm(bias, input, weight.t())
   1025 
-> 1026     output = input.matmul(weight.t())
   1027     if bias is not None:
   1028         output += bias

RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1533672544752/work/aten/src/THC/THCBlas.cu:249`

**Comment by albanD** [comment] 2018-10-24 09:23
@xiongzhp  this is a duplicate of #12977 No?

**Comment by xiongzhp** [comment] 2018-10-24 12:59
@albanD Thanks for your response, exactly the same question, but I actually want some remedies before the pytorch updated for RTX 2080 Ti support. I even compiled pytorch from source, but new problems come about. Whenever I call torch.cuda, it get stuck and hanging forever.

**Comment by soumith** [comment] 2018-10-24 14:45
closing as duplicate. I answered on the other thread.

**Closed by soumith** 2018-10-24 14:45 UTC

**Comment by IPSE-TEAM** [comment] 2019-08-23 10:37
cublas runtime error : the GPU program failed to execute at /root/torch/extra/cutorch/lib/THC/THCBlas.cu:246
stack traceback:
	[C]: in function 'v'
	/root/torch/install/share/lua/5.1/nn/THNN.lua:110: in function 'SpatialConvolutionMM_updateOutput'
	/root/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:79: in function </root/torch/install/share/lua/5.1/nn/SpatialConvolution.lua:76>
	[C]: in function 'xpcall'
	/root/torch/install/share/lua/5.1/nn/Container.lua:63: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./models/one_direction_test_model.lua:52: in function 'Forward'
	test.lua:100: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x55da80982570

WARNING: If you see a stack trace below, it doesn't point to the place where this error occurred. Please use only the one above.
stack traceback:
	[C]: in function 'error'
	/root/torch/install/share/lua/5.1/nn/Container.lua:67: in function 'rethrowErrors'
	/root/torch/install/share/lua/5.1/nn/Sequential.lua:44: in function 'forward'
	./models/one_direction_test_model.lua:52: in function 'Forward'
	test.lua:100: in main chunk
	[C]: in function 'dofile'
	/root/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:150: in main chunk
	[C]: at 0x55da80982570

**Comment by Ammexm** [comment] 2022-01-22 03:30
Want RTX 3090ti Support too!!! RuntimeError: cublas runtime error : the GPU program failed to execute at /opt/conda/conda-bld/pytorch_1565272271120/work/aten/src/THC/THCBlas.cu:331!!!
