### ISSUE TITLE
Unexpected MYPY linter errors on CI

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#126361] opened 2024-05-16 00:35 UTC
Recently, there have been reports of unexpected MYPY linter errors on CI that sometimes requires killing MYPY daemon to surface.  There was also an incident today captured on HUD https://hud.pytorch.org/hud/pytorch/pytorch/9c9d0c2fab650a8805421ec6641a3e20be31a53b/1?per_page=50 where some MYPY linter failures come and go unexpectedly.

cc @seemethere @malfet @pytorch/pytorch-dev-infra @ZainRizvi @kit1980 @clee2000 @ezyang

**Comment by malfet** [comment] 2024-08-20 21:00
Closing as duplicate of #128588

**Closed by malfet** 2024-08-20 21:00 UTC
Labels: module: ci, triaged, module: devx
