### ISSUE TITLE
`topk()` with an empty 1D tensor and `k=1` still gets the same error even if setting `dim=0` to it

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130135] opened 2024-07-05 01:38 UTC
### 🐛 Describe the bug

[topk()](https://pytorch.org/docs/stable/generated/torch.topk.html) with an empty 1D tensor and `k=1` gets the error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.topk(input=my_tensor, k=1) # Error
```

> RuntimeError: selected index k out of range

So, I set `dim=0` to `kthvalue()` but it still gets the same error as shown below:

```python
import torch

my_tensor = torch.tensor([])

torch.topk(input=my_tensor, k=1, dim=0) # Error
```

> RuntimeError: selected index k out of range

In addition, `topk()` with an empty 2D or 3D  tensor and `k=1` also gets the errors respectively as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.topk(input=my_tensor, k=1) # Error

my_tensor = torch.tensor([[[]]])

torch.topk(input=my_tensor, k=1) # Error
```

> RuntimeError: selected index k out of range

But setting `dim=0` to `topk()` works properly as shown below:

```python
import torch

my_tensor = torch.tensor([[]])

torch.topk(input=my_tensor, k=1, dim=0)
# torch.return_types.topk(
# values=tensor([], size=(1, 0)),
# indices=tensor([], size=(1, 0), dtype=torch.int64))

my_tensor = torch.tensor([[[]]])

torch.topk(input=my_tensor, k=1, dim=0)
# torch.return_types.topk(
# values=tensor([], size=(1, 1, 0)),
# indices=tensor([], size=(1, 1, 0), dtype=torch.int64))
```

### Versions

```python
import torch

torch.__version__ # 2.3.0+cu121
```

**Comment by albanD** [comment] 2024-07-08 14:47
Near duplicate of https://github.com/pytorch/pytorch/issues/130187
Let's continue discussion there since they have the same behavior

**Closed by albanD** 2024-07-08 14:47 UTC
