### ISSUE TITLE
torch.seed() fails after copying to cuda

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#41782] opened 2020-07-21 05:06 UTC
## 🐛 Bug

torch.seed() fails with `Overflow when unpacking long` after a tensor is copied to cuda

## To Reproduce

to reproduce:
```
# test.py
import torch
print(f"Torch version: {torch.__version__}")

x = torch.tensor(data=[[1,2],[3,4]], dtype=torch.long, device=None)
x = x.to('cuda:0')
seed = torch.seed()
```

```
$ python tests/test.py
Torch version: 1.5.1

Traceback (most recent call last):
  File "tests/test.py", line 10, in <module>
    seed = torch.seed()
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/random.py", line 45, in seed
    torch.cuda.manual_seed_all(seed)
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/cuda/random.py", line 111, in manual_seed_all
    _lazy_call(cb)
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/cuda/__init__.py", line 99, in _lazy_call
    callable()
  File "/home/stas/anaconda3/envs/main/lib/python3.7/site-packages/torch/cuda/random.py", line 109, in cb
    default_generator.manual_seed(seed)
RuntimeError: Overflow when unpacking long
```

It fails about 75% of time.

## Expected behavior

It shouldn't fail.

## Additional info

It seems to be related to: https://github.com/pytorch/pytorch/issues/33546

While CI passes, on my machine[`huggingface/transformers` tests fail with this error](https://github.com/huggingface/transformers/issues/5639).

## Environment

```
PyTorch version: 1.5.1
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 18.04.4 LTS
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce GTX TITAN X
GPU 1: GeForce GTX TITAN X

Nvidia driver version: 440.95.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.13.3
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] mkl                       2020.0                      166
[conda] mkl-service               2.3.0            py37he904b0f_0
[conda] mkl_fft                   1.0.15           py37ha843d7b_0
[conda] mkl_random                1.1.0            py37hd6b4f25_0
[conda] numpy                     1.18.1                   pypi_0    pypi
[conda] numpy-base                1.18.1           py37hde5b4d6_1
[conda] numpydoc                  0.9.2                      py_0
[conda] pytorch                   1.5.1           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         0.8.1                    pypi_0    pypi
[conda] pytorch-nlp               0.5.0                    pypi_0    pypi
[conda] pytorch-pretrained-bert   0.6.2                    pypi_0    pypi
[conda] pytorch-transformers      1.1.0                    pypi_0    pypi
[conda] torch                     1.5.0                    pypi_0    pypi
[conda] torchtext                 0.5.1                    pypi_0    pypi
[conda] torchvision               0.6.1                py37_cu102    pytorch
```

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by ezyang** [comment] 2020-07-27 17:10
I successfully repro'ed this on a relatively recent version of master:

```
(/scratch/ezyang/pytorch-tmp2-env) ezyang@devfair040:~/pytorch-tmp2$ python arf.py
Torch version: 1.6.0a0+9870ef2
Traceback (most recent call last):
  File "arf.py", line 6, in <module>
    seed = torch.seed()
  File "/private/home/ezyang/pytorch-tmp2/torch/random.py", line 45, in seed
    torch.cuda.manual_seed_all(seed)
  File "/private/home/ezyang/pytorch-tmp2/torch/cuda/random.py", line 111, in manual_seed_all
    _lazy_call(cb)
  File "/private/home/ezyang/pytorch-tmp2/torch/cuda/__init__.py", line 100, in _lazy_call
    callable()
  File "/private/home/ezyang/pytorch-tmp2/torch/cuda/random.py", line 109, in cb
    default_generator.manual_seed(seed)
RuntimeError: Overflow when unpacking long
```

**Comment by albanD** [comment] 2020-07-27 17:10
Duplicate of https://github.com/pytorch/pytorch/issues/33546

**Comment by albanD** [comment] 2020-07-27 17:11
Closing as duplicate. We can continue the discussion there.

**Closed by albanD** 2020-07-27 17:11 UTC
Labels: high priority, module: cuda, triage review

**Comment by stas00** [comment] 2020-07-27 17:54
I tried to comment there first, and nothing was happening. Clearly the original issue has been stalled - it's been submitted 5 months ago. So now it'll be buried again.

**Comment by albanD** [comment] 2020-07-27 18:20
Hi,

We bumped the priority of the original issue to reflect that.
Also we would be very happy to provide guidance and accept a PR fixing this!

**Comment by stas00** [comment] 2020-07-27 19:01
Thanks a lot for bumping the priority, @albanD!
