### ISSUE TITLE
Calling tensor.backward() from within a C++ extension hangs

### ISSUE THREAD

**Issue by mathisgerdes** [pytorch/pytorch#32045] opened 2020-01-10 16:45 UTC
A C++ extension calling backward() on a tensor hangs when called from python.

I've posted this same issue with some back tracing [in the forum](https://discuss.pytorch.org/t/tensor-backward-called-within-c-extension-hangs/65473).

## To Reproduce
Here is the basic extension, following the tutorial on C++/CUDA extensions. I get the same issue if I install the extension via `load_inline`.

1. Source `diff.cpp`
```cpp
#include <torch/extension.h>

void backw(torch::Tensor tens) {
    tens.backward({}, true, true);
}

PYBIND11_MODULE(TORCH_EXTENSION_NAME, m) {
    m.def("backw", &backw, "DIFF backw");
}
```

2. `setup.py` file
```python
from setuptools import setup, Extension
from torch.utils import cpp_extension

setup(name='diff_cpp',
      ext_modules=[cpp_extension.CppExtension('diff_cpp', ['diff.cpp'])],
      cmdclass={'build_ext': cpp_extension.BuildExtension})
```

3. Install via `python setup.py install`
The installation proceeds without error, and the extension can subsequently be installed as `diff_cpp`. The following test script hangs at the last line:
```python
import torch
import diff_cpp    # fine
x = torch.tensor([1.0, 2.0], requires_grad=True)
y = torch.sum(x)
diff_cpp.backw(y)  # hangs
```

## Environment
I have so far tried this on two machines in multiple configurations, each time inside a fresh `python -m venv env` virtual environment and installing pytorch using pip.
- python 3.7, torch 1.3.1, CPU
- python 3.6, torch 1.3.1, CUDA 10.1
- python 3.6, nightly, CUDA 10.1

Here are the details of one of the environments I've tried this on:
```
PyTorch version: 1.3.1+cpu
Is debug build: No
CUDA used to build PyTorch: None

OS: Arch Linux
GCC version: (GCC) 9.2.0
CMake version: version 3.16.2

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] torch==1.3.1+cpu
[pip3] torchvision==0.4.2+cpu
[conda] Could not collect
```

cc @ezyang @SsnL @albanD @zou3519 @gqchen @yf225

**Comment by izdeby** [comment] 2020-01-15 17:20
FYI, @albanD as a forum responser.

**Comment by albanD** [comment] 2020-01-15 20:50
After more investigation, the problem is that you are in a python world and initialize the autograd engine using the cpp api while holding the GIL.
Possible workaround are:
- initialize the engine from python beforehand by running `x.sum().backward()` for example **before** you use your cpp version
- release the gil in your function before calling the backward function with `pybind11::gil_scoped_release no_gil;` for example.

I'll try and find a proper fix on our side to avoid this deadlock.
Thanks for the report !

**Comment by albanD** [comment] 2020-01-23 18:48
This is now fixed in master.

**Closed by albanD** 2020-01-23 18:48 UTC
Labels: module: autograd, module: cpp, module: cpp-extensions, triaged
