### ISSUE TITLE
pack_padded_sequence requires lengths to be on CPU

### ISSUE THREAD

**Issue by david-waterworth** [pytorch/pytorch#47637] opened 2020-11-10 00:05 UTC
I've updated my GPU to a 3090 so I'm running torch 1.7.0+cu110 with CUDA 11.0

My Dataloader returns (sequences, targets, lengths) where sequences and targets are padded sequences. I'm using pytorch-lightning which moves the tensors return by the data loader to the GPU.

Previously (1.6.0)  this code worked, `sequences` and `lengths` are on the GPU

        x = self.embed(sequences)
        x = pack_padded_sequence(x, lengths, batch_first=True)
        x, _ = self.lstm(x, self.hidden)

Now it throws 

```
  File "/home/david/.pyenv/versions/transformer/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
    _VF._pack_padded_sequence(input, lengths, batch_first)
RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
```

By explicitly moving `lengths` back to the CPU it works. Was this a deliberate change?

        x = self.embed(sequences)
        x = pack_padded_sequence(x, lengths.to("cpu"), batch_first=True)
        x, _ = self.lstm(x, self.hidden)

cc @ezyang @gchanan @zou3519 @bdhirsh

**Comment by zou3519** [comment] 2020-11-16 22:22
Minimum repro:
```
sequences = torch.randn(10, 64, 128, device='cuda')
lengths = torch.randint(5, 10, [64], device='cuda')
torch.nn.utils.rnn.pack_padded_sequence(sequences, lengths, enforce_sorted=False)
```
Succeeds on 1.5.1, 1.6, but fails on 1.7.

I'm marking this hi-pri to investigate or clarify because this seems like a regression. There's a simple workaround but I am not sure if this was intentional or not

**Comment by ngimel** [comment] 2020-11-30 18:03
duplicate of #43227

**Closed by ngimel** 2020-11-30 18:03 UTC
Labels: has workaround, high priority, module: regression, module: rnn, triage review, triaged

**Comment by yipliu** [comment] 2020-12-21 14:12
> I've updated my GPU to a 3090 so I'm running torch 1.7.0+cu110 with CUDA 11.0
> 
> My Dataloader returns (sequences, targets, lengths) where sequences and targets are padded sequences. I'm using pytorch-lightning which moves the tensors return by the data loader to the GPU.
> 
> Previously (1.6.0) this code worked, `sequences` and `lengths` are on the GPU
> 
> ```
>     x = self.embed(sequences)
>     x = pack_padded_sequence(x, lengths, batch_first=True)
>     x, _ = self.lstm(x, self.hidden)
> ```
> 
> Now it throws
> 
> ```
>   File "/home/david/.pyenv/versions/transformer/lib/python3.8/site-packages/torch/nn/utils/rnn.py", line 244, in pack_padded_sequence
>     _VF._pack_padded_sequence(input, lengths, batch_first)
> RuntimeError: 'lengths' argument should be a 1D CPU int64 tensor, but got 1D cuda:0 Long tensor
> ```
> 
> By explicitly moving `lengths` back to the CPU it works. Was this a deliberate change?
> 
> ```
>     x = self.embed(sequences)
>     x = pack_padded_sequence(x, lengths.to("cpu"), batch_first=True)
>     x, _ = self.lstm(x, self.hidden)
> ```
> 
> cc @ezyang @gchanan @zou3519 @bdhirsh

Hi david-waterworth,
I use your method to fix the bug about pack_padded_sequence function in PyTorch 1.7
I want to know, due to the difference between “lengths.cpu ”and “lengths.gpu””, does the model training time change between version 1.6 and version 1.7?
@david-waterworth
