### ISSUE TITLE
The first 20 loops of inference are Extremely Slow on C++ libtorch v1.8.1

### ISSUE THREAD

**Issue by MamaShip** [pytorch/pytorch#56245] opened 2021-04-16 09:42 UTC
## 🐛 Bug

With our pre-Trained CNN model, we have input of different sizes. 

We use `torch::jit::load(model_file);` to load the model. And do inference with libtorch on GPU.
This works fine on libtorch v1.6. 
But inference turns out very slow on v1.8.1. 

Upon further investigation, we found that only the first 21 loops were abnormal.

the detail is shown below: (abnormal loops cost more than 3 seconds)
```
 loading model 
loop 0 <cost> 0.712879 s. size: 14700
loop 1 <cost> 3.70764 s. size: 14800
loop 2 <cost> 3.63273 s. size: 14900
loop 3 <cost> 3.6514 s. size: 15000
loop 4 <cost> 3.67014 s. size: 15100
loop 5 <cost> 3.65925 s. size: 15200
loop 6 <cost> 3.69206 s. size: 15300
loop 7 <cost> 3.66742 s. size: 15400
loop 8 <cost> 3.67505 s. size: 15500
loop 9 <cost> 3.67221 s. size: 15600
loop 10 <cost> 3.66073 s. size: 15700
loop 11 <cost> 3.66153 s. size: 15800
loop 12 <cost> 3.66444 s. size: 15900
loop 13 <cost> 3.67946 s. size: 16000
loop 14 <cost> 3.66667 s. size: 16100
loop 15 <cost> 3.67929 s. size: 16200
loop 16 <cost> 3.68425 s. size: 16300
loop 17 <cost> 3.67031 s. size: 16400
loop 18 <cost> 3.67817 s. size: 16500
loop 19 <cost> 3.67085 s. size: 16600
loop 20 <cost> 3.66137 s. size: 16700
loop 21 <cost> 0.074724 s. size: 16800
loop 22 <cost> 0.083596 s. size: 16900
loop 23 <cost> 0.081736 s. size: 17000
loop 24 <cost> 0.083907 s. size: 17100
loop 25 <cost> 0.084509 s. size: 17200
loop 26 <cost> 0.081011 s. size: 17300
loop 27 <cost> 0.0842 s. size: 17400
loop 28 <cost> 0.087529 s. size: 17500
loop 29 <cost> 0.087276 s. size: 17600
loop 30 <cost> 0.087559 s. size: 17700
loop 31 <cost> 0.086785 s. size: 17800
loop 32 <cost> 0.088623 s. size: 17900
loop 33 <cost> 0.083992 s. size: 18000
loop 34 <cost> 0.088985 s. size: 18100
loop 35 <cost> 0.087225 s. size: 18200
loop 36 <cost> 0.088353 s. size: 18300
loop 37 <cost> 0.089387 s. size: 18400
loop 38 <cost> 0.091879 s. size: 18500
loop 39 <cost> 0.091864 s. size: 18600
```

## To Reproduce

1. sample code:
```
#include "torch/script.h"
#include <exception>
#include <sys/time.h>
#include <string>
#include <vector>

class MyTimer {
public:
    static long GetTimeStamp() {
        struct timeval now;
        gettimeofday(&now, NULL);
        return 1000000 * now.tv_sec + now.tv_usec;
    }
    static double GetElapsedTime(long& start, long& end) {
        return (end - start) / 1000000.0;
    }
};

class ForwardModel {
public:
    void Init(std::string model_file) {
        try {
            std::cout << " loading model " << std::endl;
            module_ = torch::jit::load(model_file);
        } catch (const c10::Error& e) {
            std::cout << " error loading the model! " << std::endl;
            return;
        }
    }

    at::Tensor ModelForward(std::vector<float>& signal, size_t start, size_t end) {
        std::vector<torch::jit::IValue> inputs = {torch::unsqueeze(torch::unsqueeze(torch::tensor(at::ArrayRef<float>(&signal[start], &signal[end])), 0), 0).cuda()};
        torch::NoGradGuard no_grad;
        return std::move(module_.forward(inputs).toTensor().exp().cpu().squeeze(0));
    }

protected:
    torch::jit::script::Module module_;
};

int main(int argc, char** argv) {
    std::string model_path = "/Path/To/Model/Kirky@v2.pt";
    ForwardModel model;
    model.Init(model_path);
    std::vector<float> input(200000, 3);
    for (int i = 0; i < 40; i++) {
        int size = 14700 + i * 100;  // 14700 can be any other numbers

        long start = MyTimer::GetTimeStamp();
        auto output = model.ModelForward(input, 0, size);
        long end = MyTimer::GetTimeStamp();

        std::cout << "loop " << i << " <cost> " << MyTimer::GetElapsedTime(start, end) << " s. size: " << size << std::endl;
    }
    return 0;
}
```
2. Related model is attached. 
[Kirky@v2.zip](https://github.com/pytorch/pytorch/files/6323923/Kirky%40v2.zip)

3. Be aware of the variable `size`. It's changed in every loop.

If the value of size is fixed, output goes like this：(only the 2nd loop is slow, the subsequent loops become faster than 1st loop)
```
 loading model 
loop 0 <cost> 0.699467 s. size: 14700
loop 1 <cost> 3.70982 s. size: 14700
loop 2 <cost> 0.06808 s. size: 14700
loop 3 <cost> 0.068089 s. size: 14700
loop 4 <cost> 0.067956 s. size: 14700
loop 5 <cost> 0.068174 s. size: 14700
loop 6 <cost> 0.065999 s. size: 14700
loop 7 <cost> 0.068119 s. size: 14700
loop 8 <cost> 0.06794 s. size: 14700
loop 9 <cost> 0.068088 s. size: 14700
loop 10 <cost> 0.067833 s. size: 14700
loop 11 <cost> 0.068122 s. size: 14700
loop 12 <cost> 0.065984 s. size: 14700
loop 13 <cost> 0.067933 s. size: 14700
loop 14 <cost> 0.068068 s. size: 14700
loop 15 <cost> 0.068028 s. size: 14700
……
```
## Expected behavior

It seems that libtorch is doing some auto-optimization on those slower loops.
This will help speed things up later.

But this feature doesn't fit our usage scenario, and hurts our program performance.

3 seconds for 20 loops  = more than 60 seconds. This is not acceptable for our application.

## Environment

- libTorch Version (e.g., 1.0): 1.8.1
- OS: Ubuntu 18.04.5 LTS (x86_64)
- GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
- CMake version: version 3.20.1
- CUDA runtime version: 11.1.105
- GPU models and configuration:
--  GPU 0: GeForce RTX 3060
-- GPU 1: GeForce RTX 3060
- Nvidia driver version: 460.67

cc @VitalyFedyunin @ngimel @gmagogsfm

**Comment by ngimel** [comment] 2021-04-16 15:55
Duplicate of #52286

**Comment by MamaShip** [comment] 2021-04-18 01:22
@ngimel THX for your reply! I'll try the solution later.
BTW, is this a bug or a feature?

**Comment by gmagogsfm** [comment] 2021-04-18 05:20
> @ngimel THX for your reply! I'll try the solution later.
> BTW, is this a bug or a feature?

That's a bit of a philosophical question : ) When size is fixed, the first iteration is slower because additional optimization is run based on size observed, therefore following inferences would be faster.

**Closed by gmagogsfm** 2021-04-18 05:20 UTC
Labels: oncall: jit

**Comment by michele-arrival** [comment] 2021-09-27 11:07
Hi guys, I had the same issue (as in, the 2nd iteration being slow - for me it was like 1 minute). 
I tried the solution on the linked issue, however it didn't fix the higher timing on .

What did work though, was to set the bailout_depth to 0 with `torch._C._jit_set_bailout_depth(0)`. So now, using the sample code kindly provided by @MamaShip I see:

```
 loading model
loop 0 <cost> 0.096971 s. size: 14700
loop 1 <cost> 0.029639 s. size: 14700
loop 2 <cost> 0.016631 s. size: 14700
loop 3 <cost> 0.020363 s. size: 14700
loop 4 <cost> 0.031758 s. size: 14700
loop 5 <cost> 0.032027 s. size: 14700
loop 6 <cost> 0.031708 s. size: 14700
loop 7 <cost> 0.031402 s. size: 14700
loop 8 <cost> 0.031735 s. size: 14700
loop 9 <cost> 0.024627 s. size: 14700
loop 10 <cost> 0.019668 s. size: 14700
loop 11 <cost> 0.019744 s. size: 14700
loop 12 <cost> 0.013877 s. size: 14700
loop 13 <cost> 0.016756 s. size: 14700
loop 14 <cost> 0.02058 s. size: 14700
loop 15 <cost> 0.020284 s. size: 14700
loop 16 <cost> 0.023722 s. size: 14700
loop 17 <cost> 0.031561 s. size: 14700
loop 18 <cost> 0.032172 s. size: 14700
loop 19 <cost> 0.022009 s. size: 14700
loop 20 <cost> 0.015367 s. size: 14700
loop 21 <cost> 0.02421 s. size: 14700
loop 22 <cost> 0.032239 s. size: 14700
loop 23 <cost> 0.031856 s. size: 14700
loop 24 <cost> 0.031615 s. size: 14700
loop 25 <cost> 0.0317 s. size: 14700
loop 26 <cost> 0.031836 s. size: 14700
loop 27 <cost> 0.021729 s. size: 14700
loop 28 <cost> 0.022586 s. size: 14700
loop 29 <cost> 0.015341 s. size: 14700
loop 30 <cost> 0.016564 s. size: 14700
loop 31 <cost> 0.020435 s. size: 14700
loop 32 <cost> 0.019909 s. size: 14700
loop 33 <cost> 0.025367 s. size: 14700
loop 34 <cost> 0.031569 s. size: 14700
loop 35 <cost> 0.031391 s. size: 14700
loop 36 <cost> 0.020738 s. size: 14700
loop 37 <cost> 0.01665 s. size: 14700
loop 38 <cost> 0.026737 s. size: 14700
loop 39 <cost> 0.032014 s. size: 14700
```
with a Titan RTX, Ubuntu 20.04, pytorch 1.9.1

is it a good idea? is the fix for the linked issue going to address this too?

Thanks!

P.S. I had originally opened a discussion on discuss: https://discuss.pytorch.org/t/slow-forward-on-traced-graph-on-cuda-2nd-iteration/118445/7 hoping to get some explanation
