### ISSUE TITLE
Pytorch to ONNX failed due to unsupported max_unpool2d

### ISSUE THREAD

**Issue by YiruS** [pytorch/pytorch#43367] opened 2020-08-20 22:43 UTC
## To Reproduce

1. follow the instruction here https://colab.research.google.com/github/pytorch/tutorials/blob/gh-pages/_downloads/super_resolution_with_caffe2.ipynb#scrollTo=fUI45vwDNZR6
2. use onnx to convert pytorch to onnx

## Code to execute
model = SegNet_Small(
    input_channels=1,
    num_classes=4,
    skip_type="mul",
    BR_bool=False,
    separable_conv=False,
)
model = model.to(device)
x = torch.randn(1, 1, 184, 184, requires_grad=True).to(device)
torch.onnx.export(model, x, "test.onnx", verbose=True)

## Error information
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-991791c7188c> in <module>
      3 
      4 # Export the model
----> 5 torch.onnx.export(model, x, "test.onnx", verbose=True)
      6 
      7 # torch_out = torch.onnx._export(model,             # model being run
..................
~/anaconda3/lib/python3.7/site-packages/torch/onnx/symbolic_registry.py in get_registered_op(opname, domain, version)
    107         else:
    108             msg += "Please open a bug to request ONNX export support for the missing operator."
--> 109         raise RuntimeError(msg)
    110     return _registry[(domain, version)][opname]

**RuntimeError: Exporting the operator max_unpool2d to ONNX opset version 9 is not supported. Please open a bug to request ONNX export support for the missing operator.**

## Environment
 - PyTorch Versio: 1.6.0
 - OS (e.g., Linux): Fedora release 30 (Thirty) (x86_64)
 - How you installed PyTorch: conda
 - Python version: 3.7
 - CUDA/cuDNN version: 10.0.130 / 7.5.0
 - GPU models and configuration: TITAN RTX
 - Any other relevant information:

## Additional context
Versions of relevant libraries:
[pip3] numpy==1.18.1
[conda] _pytorch_select           0.2                       gpu_0  
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.3.0            py37he904b0f_0  
[conda] mkl_fft                   1.0.15           py37ha843d7b_0  
[conda] mkl_random                1.1.0            py37hd6b4f25_0  
[conda] numpy                     1.18.1           py37h4f9e942_0  
[conda] numpy-base                1.18.1           py37hde5b4d6_1  
[conda] numpydoc                  0.9.2                      py_0  
[conda] pytorch                   1.6.0           py3.7_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] pytorch-lightning         0.7.5                    pypi_0    pypi
[conda] pytorch-nn-tools          0.1.3                    pypi_0    pypi
[conda] torchvision               0.7.0                py37_cu102    pytorch

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by PatrickNa** [comment] 2020-09-23 11:47
I would also be in favor of having this. Thanks and greetings!

**Comment by garymm** [comment] 2022-04-07 00:29
Duplicate of #25088

**Closed by garymm** 2022-04-07 00:29 UTC
Labels: module: onnx, triaged, enhancement
