### ISSUE TITLE
Scripting nonzero fails when as_tuple=True

### ISSUE THREAD

**Issue by neginraoof** [pytorch/pytorch#52470] opened 2021-02-18 23:44 UTC
Scripting the model below currently fails:
```
        class NonzeroModel(torch.nn.Module):
            def forward(self, x):
                return x.nonzero(), x.nonzero(as_tuple=True)
```
Error is:
```
RuntimeError: 
Arguments for call are not valid.
The following variants are available:
  
  aten::nonzero.out(Tensor self, *, Tensor(a!) out) -> (Tensor(a!)):
  Argument out not provided.
  
  aten::nonzero(Tensor self) -> (Tensor):
  Keyword argument as_tuple unknown.

The original call is:
  File ...
            def forward(self, x):
                return x.nonzero(), x.nonzero(as_tuple=True)
                                    ~~~~~~~~~ <--- HERE
```

cc @gmagogsfm

**Comment by ngimel** [comment] 2021-02-19 01:12
Duplicate of #45499

**Closed by ngimel** 2021-02-19 01:12 UTC
Labels: oncall: jit
