### ISSUE TITLE
Interoperability with PyTorch hooks

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#93726] opened 2022-03-15 03:30 UTC
PyTorch has many hooks, for example those on `nn.Module()`, Tensors, and a few stored in global scope.

Currently, TorchDynamo will ignore these hooks and not properly call them.

We should check for hooks, inline them if they exist, and guard on them not changing.

To make the guards cheaper, we could add a "hooks changed" callback to PyTorch, allowing us to invalidate generated code rather than adding guards.

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by wconstab** [comment] 2023-02-09 17:51
duplicate of 
https://github.com/pytorch/pytorch/issues/91665

closing this one and adding the relevant implementation suggestion to the other issue.

**Closed by wconstab** 2023-02-09 17:51 UTC
Labels: enhancement, oncall: pt2
