### ISSUE TITLE
pytorch1.2  KeyError: 'triu'

### ISSUE THREAD

**Issue by laohur** [pytorch/pytorch#25838] opened 2019-09-08 19:05 UTC
## 🐛 Bug

> "(base)_ C:\WINDOWS\system32>conda_ install pytorch torchvision cudatoolkit=10.0"
device="cuda:0"
`_#1`` pytorch1.2     subsequent_mask = torch.triu(  torch.ones((len_s, len_s), device=seq.device, dtype=torch.uint8), diagonal=1)

KeyError: 'triu'
_#pytorch1.2     subsequent_mask = torch.triu(  torch.ones((len_s, len_s), device=seq.device, dtype=torch.bool), diagonal=1)
RuntimeError: name not implemented for 'Bool'
RuntimeError: ONNX export failed: Could not export a broadcasted operation; ONNX likely does not support this form of broadcasting.

> conda install pytoch=1.0.0 cuda100

_#pytorch1.0.0
D:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py:501: UserWarning: ONNX export failed on ATen operator ne because torch.onnx.symbolic.ne does not exist
  .format(op_name, op_name))
D:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py:501: UserWarning: ONNX export failed on ATen operator triu because torch.onnx.symbolic.triu does not exist
  .format(op_name, op_name))

## To Reproduce

1.
1.
1.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by vishwakftw** [comment] 2019-09-08 20:18
`tril` and `triu` have been made available for `torch.bool` in the nightly versions, please install a nightly version.

**Comment by laohur** [comment] 2019-09-09 14:34
>   File "D:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 132, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\__init__.py", line 170, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\utils.py", line 576, in _run_symbolic_function
    return op_fn(g, *inputs, **attrs)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\symbolic_helper.py", line 124, in wrapper
    return fn(g, *args)
  File "D:\ProgramData\Anaconda3\lib\site-packages\torch\onnx\symbolic_opset9.py", line 1189, in ones
    value_t=torch.tensor([1], dtype=sym_help.scalar_type_to_pytorch_type[dtype]))
**IndexError: list index out of range**

@parse_args('v', 'i', 'v', 'v', 'v')
def ones(g, sizes, dtype, layout, device, pin_memory=False):
    return g.op("ConstantOfShape", sizes,
                value_t=torch.tensor([1], dtype=sym_help.scalar_type_to_pytorch_type[dtype]))

**where sym_help.scalar_type_to_pytorch_type[11])  and** 
<class 'list'>: [torch.uint8, torch.int8, torch.int16, torch.int32, torch.int64, torch.float16, torch.float32, torch.float64, torch.complex64, torch.complex128, torch.bool]

**Comment by spandantiwari** [comment] 2021-04-26 18:29
This is a duplicate of https://github.com/pytorch/pytorch/issues/32968. Closing this one now. Let's track the `triu` support work on this other issue: https://github.com/pytorch/pytorch/issues/32968.

**Closed by spandantiwari** 2021-04-26 18:29 UTC
Labels: module: onnx, triaged
