### ISSUE TITLE
The doc of `cat()` should say `tuple` or `list` of tensors for `tensors` argument

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#130691] opened 2024-07-14 03:19 UTC
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.cat.html) of `cat()` says the type of `tensors` argument is `sequence of Tensors` as shown below:

> - tensors (sequence of Tensors) – any python sequence of tensors of the same type. Non-empty tensors provided must have the same shape, except in the cat dimension.

But the sequence of tensors with `cat()` doesn't work while a tuple or list of tensors works as shown below:

```python
import torch

tensor1 = torch.tensor([2, 7, 4])
tensor2 = torch.tensor([8, 3, 2])
tensor3 = torch.tensor([5, 0, 8])

torch.cat(tensor1, tensor2, tensor3) # Error

torch.cat((tensor1, tensor2, tensor3))
torch.cat([tensor1, tensor2, tensor3])
torch.cat(tensors=(tensor1, tensor2, tensor3))
# tensor([2, 7, 4, 8, 3, 2, 5, 0, 8])
```

### Suggest a potential alternative/fix

So, the doc should say `tuple` or `list` of tensors for `tensors` argument as shown below:

> - tensors (tuple or list of Tensors) – any python sequence of tensors of the same type. Non-empty tensors provided must have the same shape, except in the cat dimension.

cc @albanD

**Comment by albanD** [comment] 2024-07-16 20:37
Closing as duplicate of https://github.com/pytorch/pytorch/issues/130693

**Closed by albanD** 2024-07-16 20:37 UTC
Labels: triaged, module: python frontend
