### ISSUE TITLE
[nnc][perf] 50x performance regression from `_jit_override_can_fuse_on_cpu(True)`

### ISSUE THREAD

**Issue by jansel** [pytorch/pytorch#52264] opened 2021-02-14 20:51 UTC
I am seeing some big performance regressions from two benchmarks in [TorchBench](https://github.com/pytorch/benchmark/) when I enable `torch._C._jit_override_can_fuse_on_cpu(True)`.  LearningToPaint has the performance regression both with and without freezing, while pytorch_mobilenet_v3 only has the regression when I enable freezing as well (in this case a 922x regression).

Code to reproduce:
```
import torch, re, multiprocessing
from timeit import timeit
from torchbenchmark.models import LearningToPaint, pytorch_mobilenet_v3


def measure(fuse, benchmark_module, warmup=1, number=100):
    torch.set_num_threads(1)
    torch._C._jit_override_can_fuse_on_cpu(fuse)
    name = re.sub(r"^.*[.]", "", benchmark_module.__name__)
    benchmark = benchmark_module.Model(device="cpu", jit=True)
    model, example_inputs = benchmark.get_module()
    assert isinstance(model, torch.jit.ScriptModule)

    model = model.eval()
    timeit(lambda: model(*example_inputs), number=warmup)
    print(f"    script({name:20})         = {timeit(lambda: model(*example_inputs), number=number):.3f} sec")

    model = torch.jit.freeze(model)
    timeit(lambda: model(*example_inputs), number=warmup)
    print(f"    freeze(script({name:20})) = {timeit(lambda: model(*example_inputs), number=number):.3f} sec")


for fuse in (False, True):
    print(f"_jit_override_can_fuse_on_cpu({fuse}):")
    for benchmark_module in (LearningToPaint, pytorch_mobilenet_v3):
        # Doing a subproc to ensure we aren't running cached code
        p = multiprocessing.Process(target=measure, args=(fuse, benchmark_module))
        p.start()
        p.join()
```

Output:
```
_jit_override_can_fuse_on_cpu(False):
    script(LearningToPaint     )         = 5.862 sec
    freeze(script(LearningToPaint     )) = 5.131 sec
    script(pytorch_mobilenet_v3)         = 1.089 sec
    freeze(script(pytorch_mobilenet_v3)) = 0.460 sec
_jit_override_can_fuse_on_cpu(True):
    script(LearningToPaint     )         = 275.655 sec
    freeze(script(LearningToPaint     )) = 274.557 sec
    script(pytorch_mobilenet_v3)         = 1.108 sec
    freeze(script(pytorch_mobilenet_v3)) = 424.520 sec
```

I am running on PyTorch==96fd5d87f7c739fd62b57b6cb08fd41a60d0bf40 on Ubuntu 20.10/gcc-9.3.

cc @gmagogsfm

**Comment by jansel** [comment] 2021-02-14 20:56
cc @bertmaher  @Krovatkin @zheng-xq @navahgar @eellison

**Comment by ZolotukhinM** [comment] 2021-02-16 05:21
@jansel, is your pytorch built with LLVM? A common pitfall is that when LLVM is not available, the fused code gets interpreted.  One way to check it is to enable `PYTORCH_JIT_LOG_LEVEL=">>llvm_codegen"` - if the output is empty, then probably you'd need to rebuild pytorch with `USE_LLVM` (a side note: we probably should start including it to the builds by default).

**Comment by navahgar** [comment] 2021-02-16 07:57
This perf regr is only because of PyTorch built without LLVM, as @ZolotukhinM mentioned. I just confirmed this:

**Without LLVM**

```
_jit_override_can_fuse_on_cpu(False):
    script(LearningToPaint     )         = 8.731 sec
    freeze(script(LearningToPaint     )) = 8.006 sec
    script(pytorch_mobilenet_v3)         = 1.607 sec
    freeze(script(pytorch_mobilenet_v3)) = 0.784 sec
_jit_override_can_fuse_on_cpu(True):
    script(LearningToPaint     )         = 513.627 sec
    freeze(script(LearningToPaint     )) = 512.031 sec
    script(pytorch_mobilenet_v3)         = 1.548 sec
    freeze(script(pytorch_mobilenet_v3)) = 782.914 sec
```

**With LLVM**

```
_jit_override_can_fuse_on_cpu(False):
    script(LearningToPaint     )         = 9.847 sec
    freeze(script(LearningToPaint     )) = 8.631 sec
    script(pytorch_mobilenet_v3)         = 1.997 sec
    freeze(script(pytorch_mobilenet_v3)) = 1.326 sec
_jit_override_can_fuse_on_cpu(True):
    script(LearningToPaint     )         = 9.890 sec
    freeze(script(LearningToPaint     )) = 9.014 sec
    script(pytorch_mobilenet_v3)         = 1.986 sec
    freeze(script(pytorch_mobilenet_v3)) = 2.400 sec
```

Note that there is no way to get PyTorch with LLVM from prebuilt nightlies AFAIK. You will have to build PyTorch from source with USE_LLVM flag set in order to get the LLVM backend.

**Comment by jansel** [comment] 2021-02-16 17:02
Ah, that explains it.  Should we make this an error?  Or emit a warning?  I doubt anyone would want the 50x slower behavior.

Also, it looks like even with LLVM freeze(script(pytorch_mobilenet_v3)) is slower.

**Comment by Krovatkin** [comment] 2021-02-16 17:32
@wconstab I've noticed we are using a custom Docker file for `pytorch/benchmark`. Can we add this line https://github.com/pytorch/pytorch/blob/master/.circleci/docker/ubuntu/Dockerfile#L124 or we are using different circleci accounts?

**Comment by wconstab** [comment] 2021-02-16 17:38
It seems like it'd be easier on devs and users to keep things straight if we were clearer in requiring llvm or error;  are there good arguments in favor of supporting JIT without llvm?

**Comment by navahgar** [comment] 2021-02-16 17:46
I agree that it is better to keep things clearer w.r.t. requiring llvm. But sometimes users fail to realize that they are building without LLVM, even though thats not their intention and they have LLVM setup already. I know this because I have done this many times already. At the least, we should make sure that users understand that they are building without LLVM and their performance on CPU will be >50x slower. 

> Also, it looks like even with LLVM freeze(script(pytorch_mobilenet_v3)) is slower.

I updated my repo and checked again. That still seems to be ~2x slower. Anyone familiar with `freeze` have cycles to look into this?

**Comment by Krovatkin** [comment] 2021-02-16 18:04
I can look into the `freeze` slowdown

**Comment by Krovatkin** [comment] 2021-02-16 18:12
I was thinking that 

The most natural behaviour for most users would be that 
a) we don't have to fuse on CPU if we built without LLVM

For developers and early adopters that do want to test with LLVM
b) we could add a STRICT_LLVM flag to make sure we error out in case PyTorch was built without LLVM

**Comment by navahgar** [comment] 2021-02-16 18:18
Thanks @Krovatkin.

> a) we don't have to fuse on CPU if we built without LLVM

This would work for now. In future, assuming we have better performance when fused on CPU, users may not know to enable the appropriate flag to use that.

How about making the default build use LLVM and asking the users to specify a `NO_LLVM` flag if they do not want to use LLVM? Basically, the reverse of what is happening now. If the users didn't have LLVM, then the default build will fail (without the `NO_LLVM` flag). If they specify the `NO_LLVM` flag we can decide to not fuse on CPU.

**Comment by jansel** [comment] 2021-02-16 18:22
For the current behavior, I'd suggest `_jit_override_can_fuse_on_cpu(True)` throws an error if you don't have LLVM.  Once fusing becomes the default maybe we need to switch to the `NO_LLVM` flag.

**Comment by ZolotukhinM** [comment] 2021-02-16 19:47
Yeah, it's done this way simply because there hasn't been many users of CPU fusion and for our own experimentation it worked fine. Now that we're getting users we should change the behavior to more sane. I think trying to turn on fusion on CPU when no LLVM is available should either throw an error or do nothing unless we have another explicit option telling us to use IR eval instead of LLVM (that option would probably interest no one except us, NNC developers).

**Comment by navahgar** [comment] 2021-02-17 00:55
Throwing an error on `_jit_override_can_fuse_on_cpu(True)` is probably not the right approach for the following reasons:
1. It looks like all tests are run in CI without LLVM. So, all of them fail when we throw an error on this.
2. Disabling all these tests when LLVM is not set does not seem correct, since they will never run on CI in that case.
3. Even if we decide to disable all of them, there are 850+ tests (that failed for me) to disable. 

My suggestion is to go with the `NO_LLVM` flag as I described above. That will be off by default but can be set for CI builds to get around the problem with tests.

**Comment by jansel** [comment] 2021-02-17 01:21
Can we enable LLVM in CI?  I'd imagine those tests would be better if they actually checked the correctness of our generated LLVM.  What are they testing if LLVM is disabled?

**Comment by ZolotukhinM** [comment] 2021-02-17 01:21
Overall that sounds good to me, but how would we find LLVM without `USE_LLVM`? That option currently serves two purposes: 1) tells the build that LLVM is available, 2) points to the LLVM folder. If we switch to `NO_LLVM`, how would we do (2)?

**Comment by ZolotukhinM** [comment] 2021-02-17 01:22
> Can we enable LLVM in CI

I believe we have one or several builds with LLVM enabled in CI. Majority of the builds are done without LLVM though.

**Comment by navahgar** [comment] 2021-02-17 01:31
I had a chat with @bertmaher and his suggestion might work. We have a flag `te_must_use_llvm_on_cpu` which is off by default and is used in TE to enforce LLVM backend. The plan is to turn this flag on by default, which would ensure that we error out when CPU fusion is enabled without LLVM. And we can turn this flag off for all tests. Trying this now.

> What are they testing if LLVM is disabled?
It is still useful to test without LLVM, since we can then test other parts of our code base without LLVM codegen. However, I agree that these tests should be run with LLVM enabled as well. 

> If we switch to NO_LLVM, how would we do (2)?
NO_LLVM will be in addition to USE_LLVM. The purpose of USE_LLVM will be to just point to the LLVM build. 

Anyways, I realize that changing the default build options is a much bigger impact change. If we decide to go that route, that probably has to be done with proper messaging.

**Comment by bertmaher** [comment] 2021-02-17 17:51
> > Can we enable LLVM in CI
> 
> I believe we have one or several builds with LLVM enabled in CI. Majority of the builds are done without LLVM though.

Yeah this is correct, it's on for some but not all builds.  I think in the current state where the llvm fuser is off-by-default it makes sense to have some covered each way (though obviously not the long-term ideal).

**Closed** 2021-02-18 20:02 UTC
Labels: NNC, triaged

**Comment by navahgar** [comment] 2021-02-18 21:46
Created a new issue to track the perf decrease with `freeze(script(pytorch_mobilenet_v3))`: https://github.com/pytorch/pytorch/issues/52465
