### ISSUE TITLE
PyPI wheel for Python 3.10 missing

### ISSUE THREAD

**Issue by mikegerber** [pytorch/pytorch#71112] opened 2022-01-10 18:10 UTC
### 🐛 Describe the bug

On PyPI, [there is no wheel for Python 3.10](https://pypi.org/project/torch/1.10.1/#files) yet. This breaks installing via `pip`:

```
% pip --version 
pip 21.3.1 from /home/mike/.virtualenvs/sbb_ocr_postcorrection/lib/python3.10/site-packages/pip (python 3.10)
% pip install torch
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

### Versions

PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Fedora release 35 (Thirty Five) (x86_64)
GCC version: (GCC) 11.2.1 20211203 (Red Hat 11.2.1-7)
Clang version: 13.0.0 (Fedora 13.0.0-3.fc35)
CMake version: version 3.22.1
Libc version: glibc-2.34

Python version: 3.10.1 (main, Dec  9 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)] (64-bit runtime)
Python platform: Linux-5.15.12-200.fc35.x86_64-x86_64-with-glibc2.34
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] Could not collect
[conda] Could not collect

cc @ezyang @seemethere @malfet

**Comment by malfet** [comment] 2022-01-12 04:04
Closing as duplicate of https://github.com/pytorch/pytorch/issues/66424

**Closed by malfet** 2022-01-12 04:04 UTC
Labels: module: binaries, feature, triaged
