### ISSUE TITLE
[sm35] About install pytorch with source.

### ISSUE THREAD

**Issue by cainiaoshidai** [pytorch/pytorch#56572] opened 2021-04-21 08:00 UTC
I want to install pytorch with source, because my gpu's(Tesla k40) computer capability is 3.5. So I can only install with source. So you see I hava two gpu.

Now I have some problems as shown in the log file. In this files, I see `NVCC --device-c     : OFF`.

So is the problem here? Can you give me some suggestions. Thank you.

Behavior

`conda install numpy ninja pyyaml mkl mkl-include setuptools cmake=3.5.0 cffi typing_extensions future six requests dataclasses`

`conda install -c pytorch magma-cuda110

`
`git clone --recursive https://github.com/pytorch/pytorch`
`cd pytorch`
`git submodule sync`
`git submodule update --init --recursive`

`export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}`
`python setup.py install`

Environment

`Ubuntu 18.4`
`GPU Tesla k40 and Nvidia GT 720`
`Anaconda3`
`Python 3.7.8`
`Cuda 11.0`
`Cudnn 8.0.5`
`Cmake 3.5.0`

cc @malfet @seemethere @walterddr @ngimel

**Comment by cainiaoshidai** [comment] 2021-04-21 08:05
[Uploading log.txt…]()

**Comment by skyline75489** [comment] 2021-04-21 08:36
I don't think you really need to build from source. You can use 1.7.1 which has support for sm_35, if I recall correctly.

By the way we can't see your log. Seems not uploaded.

**Comment by cainiaoshidai** [comment] 2021-04-21 08:58
> I don't think you really need to build from source. You can use 1.7.1 which has support for sm_35, if I recall correctly.
> 
> By the way we can't see your log. Seems not uploaded.

Sorry, I uploaded in the first comment. I have tried the vision of pytorch1.6, pytorch1.7 and pytorch1.8.
When run the code, show that only sm_3.7 is supported at the minimum. But I don't tried pytorch1.7.1, I'll try it now. Thank you very much.

**Comment by cainiaoshidai** [comment] 2021-04-22 01:59
Hi, 
I have tried pytorch 1.7.1, but I get the follow error.

> (py37) gzm@gzm:/media/gzm/encode/paper-code/spiralnet_plus-master$ python -m correspondence.main
> Traceback (most recent call last):
>   File "/home/gzm/anaconda3/envs/py37/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/home/gzm/anaconda3/envs/py37/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/media/gzm/encode/paper-code/spiralnet_plus-master/correspondence/main.py", line 45, in <module>
>     target = torch.arange(d.num_nodes, dtype=torch.long, device=device)
> RuntimeError: CUDA error: no kernel image is available for execution on the device

where, the `import torch` operation can be used normally.

**Comment by skyline75489** [comment] 2021-04-22 04:18
Can you try `torch.cuda.get_arch_list()` to see the supported arch?

**Comment by cainiaoshidai** [comment] 2021-04-23 03:13
Sorry, I I thought it was a problem with the operating system, so I reinstalled ubuntu yesterday. Now the result I got after executing `torch.cuda.get_arch_list()` is as follows. 

```
(py2) gzm@gzm:/media/gzm/encode$ python
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.cuda.get_arch_list()
['sm_37', 'sm_50', 'sm_60', 'sm_61', 'sm_70', 'sm_75', 'sm_80', 'compute_37']
```

**Comment by ezyang** [comment] 2021-04-23 15:30
your log file didn't successfully upload

**Comment by cainiaoshidai** [comment] 2021-04-24 03:41
> 您的日志文件未成功上传

Sorry， I have update log file.
Thanks.

**Comment by cainiaoshidai** [comment] 2021-04-26 02:58
> your log file didn't successfully upload

Sorry, I re-uploaded the log file in the first comment.
Thanks!

**Comment by skyline75489** [comment] 2021-04-26 03:40
These lines in your log indicates some error while compiling NCCL:

```text
make[2]: 进入目录“/media/gzm/encode/1/pytorch/third_party/nccl/nccl/src/collectives/device”
Generating rules                               > /media/gzm/encode/1/pytorch/build/nccl/obj/collectives/device/Makefile.rules
/bin/sh: 1: ./gen_rules.sh: not found
```
Can you check if there's `gen_rules.sh` in `/media/gzm/encode/1/pytorch/build/nccl/obj/collectives/device/` ?

This error is the same as https://github.com/pytorch/pytorch/issues/43691#issuecomment-682103025 .

**Comment by cainiaoshidai** [comment] 2021-04-26 04:13
There is no `gen_rules.sh` file in this directory.

**Comment by skyline75489** [comment] 2021-04-26 04:17
Sorry, it should be `/home/chester/Projects/pytorch/third_party/nccl/nccl/src/collectives/device`, which matches the source repo of [NCCL](https://github.com/NVIDIA/nccl/tree/master/src/collectives/device).

**Comment by cainiaoshidai** [comment] 2021-04-26 04:23
Thank you!
I should download the source repo of NCCL, then replace my local files and compile again, right?

**Comment by skyline75489** [comment] 2021-04-26 04:24
I'm not actually sure why the file is not found (or broken), but it seems to be the root cause of the error. You can give it a try.

**Comment by cainiaoshidai** [comment] 2021-04-26 04:26
> I'm not actually sure why the file is not found (or broken), but it seems to be the root cause of the error. You can give it a try.

Ok, let me try. Thank you very much.

**Comment by cainiaoshidai** [comment] 2021-04-26 05:20
I replaced the complete [nccl](https://github.com/NVIDIA/nccl) library and then solved the problem. If just replace the source repo of [NCCL](https://github.com/NVIDIA/nccl/tree/master/src/collectives/device) , it won't work.
Thank you.

**Comment by skyline75489** [comment] 2021-04-26 05:48
Glad you figured it out. I'll close this for now.

**Closed by skyline75489** 2021-04-26 05:48 UTC
Labels: module: build, module: cuda, triaged
