### ISSUE TITLE
torch.sort may have a regression in nightly

### ISSUE THREAD

**Issue by xwang233** [pytorch/pytorch#65863] opened 2021-09-30 00:12 UTC
## 🐛 Bug

torch.sort may have a regression in nightly

## To Reproduce

```python
import torch

x = torch.randn(3, 5, dtype=torch.float, device='cuda')

b = torch.empty(1, device='cuda')
c = torch.empty(0, device='cuda', dtype=torch.long)

torch.sort(x[:, 0], out=(b, c))

print(b, b.size(), b.stride())
print(c, c.size(), c.stride())

torch.cuda.synchronize()
```
Passed at facff2e

Failed at aebde1b:
```
b.py:8: UserWarning: An output with one or more elements was resized since it had shape [1], which does not match the required output shape [3].This behavior is deprecated, and in a future PyTorch release outputs will not be resized unless they have zero elements. You can explicitly reuse an out tensor t by resizing it, inplace, to zero elements with t.resize_(0). (Triggered internally at  ../aten/src/ATen/native/Resize.cpp:16.)
  torch.sort(x[:, 0], out=(b, c))
Traceback (most recent call last):
  File "b.py", line 8, in <module>
    torch.sort(x[:, 0], out=(b, c))
RuntimeError: setStorage: sizes [3], strides [5], storage offset 0, and itemsize 4 requiring a storage size of 44 are out of bounds for storage of size 12
Exception raised from checkInBoundsForStorage at ../aten/src/ATen/native/Resize.h:101 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0x6c (0x7f84f0946b5c in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0xfa (0x7f84f0924c36 in /opt/pytorch/pytorch/torch/lib/libc10.so)
frame #2: <unknown function> + 0x168924a (0x7f852524424a in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #3: at::native::as_strided_(at::Tensor const&, c10::ArrayRef<long>, c10::ArrayRef<long>, c10::optional<long>) + 0x48 (0x7f8525234e38 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #4: <unknown function> + 0x345d51a (0x7f84f3e3051a in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #5: <unknown function> + 0x3467669 (0x7f84f3e3a669 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #6: at::meta::structured_sort_stable::meta(at::Tensor const&, c10::optional<bool>, long, bool) + 0x246 (0x7f85251bc6e6 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0x3350ee4 (0x7f84f3d23ee4 in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #8: <unknown function> + 0x3350faa (0x7f84f3d23faa in /opt/pytorch/pytorch/torch/lib/libtorch_cuda.so)
frame #9: at::_ops::sort_values_stable::call(at::Tensor const&, c10::optional<bool>, long, bool, at::Tensor&, at::Tensor&) + 0x1ad (0x7f852565c52d in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #10: at::native::sort_out(at::Tensor const&, long, bool, at::Tensor&, at::Tensor&) + 0x33 (0x7f85251bb773 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x1f52f86 (0x7f8525b0df86 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #12: at::_ops::sort_values::redispatch(c10::DispatchKeySet, at::Tensor const&, long, bool, at::Tensor&, at::Tensor&) + 0xf1 (0x7f85254bca51 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #13: <unknown function> + 0x3e17738 (0x7f85279d2738 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #14: <unknown function> + 0x3e1a40b (0x7f85279d540b in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #15: at::_ops::sort_values::redispatch(c10::DispatchKeySet, at::Tensor const&, long, bool, at::Tensor&, at::Tensor&) + 0xf1 (0x7f85254bca51 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #16: <unknown function> + 0x38fff28 (0x7f85274baf28 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #17: <unknown function> + 0x39001fb (0x7f85274bb1fb in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #18: at::_ops::sort_values::call(at::Tensor const&, long, bool, at::Tensor&, at::Tensor&) + 0x195 (0x7f852551e7b5 in /opt/pytorch/pytorch/torch/lib/libtorch_cpu.so)
frame #19: <unknown function> + 0xc667a8 (0x7f852e8267a8 in /opt/pytorch/pytorch/torch/lib/libtorch_python.so)
<omitting python frames>
frame #31: __libc_start_main + 0xf3 (0x7f8563b420b3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
```

## Expected behavior

no fail?

## Environment

built from source, V100

## Additional context

https://github.com/pytorch/pytorch/pull/62391 might be related?

This code snippet is used in a transformer model

https://github.com/NVIDIA/DeepLearningExamples/blob/36c2d7e8b823f4689fd689efa6b56cbec8424470/PyTorch/Translation/Transformer/fairseq/sequence_generator.py#L384-L388

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @ptrblck @ngimel @ysiraichi

**Comment by bdhirsh** [comment] 2021-09-30 02:18
Prepping a revert PR here: https://github.com/pytorch/pytorch/pull/65876. I'll confirm first that I don't see the failure after patching.

**Comment by bdhirsh** [comment] 2021-09-30 05:00
Definitely coming from the PR. Quick diagnosis: It looks like we get the exception because of the following code that's called by `set_output(...)` in the meta kernel:
```
void resize_out(const Tensor &out, IntArrayRef sizes, IntArrayRef strides, const TensorOptions &options) {
  TORCH_CHECK(options.dtype() == out.dtype(),
      "Expected out tensor to have dtype ", options.dtype(), ", but got ", out.dtype(), " instead");
  TORCH_CHECK(options.device() == out.device(),
      "Expected out tensor to have device ", options.device(), ", but got ", out.device(), " instead");
  const bool resized = at::native::resize_output(out, sizes);
  // Only restride if a resize occurred; otherwise we ignore the (advisory)
  // strides from the meta function and directly use the output tensor's
  // preexisting strides
  if (resized) {
    if (!strides.empty()) {
      TORCH_INTERNAL_ASSERT(!options.memory_format_opt().has_value());
      at::native::as_strided_(out, sizes, strides);
    } else if (options.memory_format_opt().has_value()) {
      out.unsafeGetTensorImpl()->empty_tensor_restride(*options.memory_format_opt());
    }
  }
}
```

In the meta kernel, we eventual end up plumbing the original input's sizes + strides to this function. The above calls `at::native::resize_output()` to resize the output, but it ignores the strides when performing the resize. That means when `as_strided_()` is called a few lines down, `out` at that point might not have the correct storage size in order to properly be restrided.

That looks like the cause of the error. It seems like that means we should really be passing the stride info into `resize_output` too, in order to make sure that the resized tensor gets an allocated data pointer of the correct size, but I'm not 100% sure yet. Looking into it more later.

**Comment by mruberry** [comment] 2021-09-30 06:28
Make sure to remove sort's test_out skip if updating it's out= handling. That test is currently skipped because sort isn't raising the out= resize warning properly.

**Comment by ysiraichi** [comment] 2021-09-30 07:58
@bdhirsh I think that's exactly what's happening: `resize_output` is called, and then `as_strided_` fails because there isn't enough allocated space.

**Comment by bdhirsh** [comment] 2021-10-01 16:15
Confirmed that after landing #65876 this is fixed in master

**Closed by bdhirsh** 2021-10-01 16:15 UTC
Labels: high priority, triage review, triaged, module: regression
