### ISSUE TITLE
`nn.Parameter` INTERNAL ASSERT FAILED for `quint8` input tensor

### ISSUE THREAD

**Issue by cafffeeee** [pytorch/pytorch#94688] opened 2023-02-11 22:48 UTC
### 🐛 Describe the bug

`nn.Parameter` INTERNAL ASSERT FAILED for `quint8` input tensor

```py
import torch
import torch.nn as nn

dtype = torch.quint8
weight = nn.Parameter(torch.ones(10, dtype=dtype))

# RuntimeError: false INTERNAL ASSERT FAILED at 
# "/opt/conda/conda-bld/pytorch_1672906354936/work/aten/src/ATen/quantized/Quantizer.cpp":444,
# please report a bug to PyTorch. 
# cannot call qscheme on UnknownQuantizer
```

### Versions

```
PyTorch version: 2.0.0.dev20230105
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration:
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 515.86.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.4.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.4.1
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==2.0.0.dev20230105
[pip3] torchaudio==2.0.0.dev20230105
[pip3] torchvision==0.15.0.dev20230105
[conda] blas                      1.0                         mkl
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py39h7f8727e_0
[conda] mkl_fft                   1.3.1            py39hd3c417c_0
[conda] mkl_random                1.2.2            py39h51133e4_0
[conda] numpy                     1.23.5           py39h14f4228_0
[conda] numpy-base                1.23.5           py39h31eccc5_0
[conda] pytorch                   2.0.0.dev20230105 py3.9_cuda11.7_cudnn8.5.0_0    pytorch-nightly
[conda] pytorch-cuda              11.7                 h67b0de4_2    pytorch-nightly
[conda] pytorch-mutex             1.0                        cuda    pytorch-nightly
[conda] torchaudio                2.0.0.dev20230105      py39_cu117    pytorch-nightly
[conda] torchtriton               2.0.0+0d7e753227            py39    pytorch-nightly
[conda] torchvision               0.15.0.dev20230105      py39_cu117    pytorch-nightly
```

cc @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @jgong5 @Xia-Weiwen @leslie-fang-intel

**Comment by leslie-fang-intel** [comment] 2023-02-14 02:05
@cafffeeee I think it's by designed since a `QTensor` needs the [`QScheme`](https://github.com/pytorch/pytorch/blob/ce474bc6439145b472987753e191e212767b7c62/c10/core/QScheme.h#L14-L21) for which kind of quantization is used. 
The issue not relates to `nn.Parameter` but you shouldn't create a `QTensor` like: `torch.ones(10, dtype=torch.quint8)`.
You can refer to this [doc](https://github.com/pytorch/pytorch/wiki/Introducing-Quantized-Tensor) for how to create a QTensor. cc @jerryzh168 @supriyar for more information.

**Comment by supriyar** [comment] 2023-02-14 03:56
> @cafffeeee I think it's by designed since a `QTensor` needs the [`QScheme`](https://github.com/pytorch/pytorch/blob/ce474bc6439145b472987753e191e212767b7c62/c10/core/QScheme.h#L14-L21) for which kind of quantization is used. The issue not relates to `nn.Parameter` but you shouldn't create a `QTensor` like: `torch.ones(10, dtype=torch.quint8)`. You can refer to this [doc](https://github.com/pytorch/pytorch/wiki/Introducing-Quantized-Tensor) for how to create a QTensor. cc @jerryzh168 @supriyar for more information.

yes, this is by design. Please use one of the options mentioned in https://github.com/pytorch/pytorch/wiki/Introducing-Quantized-Tensor#quantized-tensor-apis to create a quantized tensors. 
Closing this issue now, please use the pytorch discussion forums if you have further questions.

**Closed by supriyar** 2023-02-14 03:56 UTC
Labels: oncall: quantization, triaged
