### ISSUE TITLE
torch.mean(input, dim=()) grad_fn is not implemented.

### ISSUE THREAD

**Issue by GuillaumeRochette** [pytorch/pytorch#28286] opened 2019-10-18 16:21 UTC
## 🐛 Bug
It seems that for a specific case of torch.mean its grad_fn is not implemented, which raises an error during the backward pass. The same case for torch.sum is working though.

## To Reproduce
Here's is a sample code that reproduces the error:
```py
import torch

if __name__ == '__main__':
    a = torch.randn(32, 100, 3, requires_grad=True)

    b = torch.sum(a, dim=(), keepdim=False)
    print(b)
    b.backward()
    c = torch.mean(a, dim=(), keepdim=False)
    print(c)
    c.backward()
```
```py
tensor(74.7599, grad_fn=<SumBackward1>)
tensor(0.0078, grad_fn=<NotImplemented>)
Traceback (most recent call last):
  File "scratch.py", line 11, in <module>
    c.backward()
  File "miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/tensor.py", line 150, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "miniconda3/envs/pytorch/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: derivative for mean is not implemented
```
## Expected behavior
It was working in 1.2.0 for both torch.sum and torch.mean.

## Environment
```
PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1050 Ti
Nvidia driver version: 418.56
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[pip] torchvision==0.4.1a0+d94043a
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.1                py37_cu101    pytorch
```

cc @zou3519

**Comment by zou3519** [comment] 2019-10-18 17:00
I think this may have been caused by named tensors. Named tensors change how torch.mean gets parsed at the python arg parser level. They change the behavior in the following way:
- the dimname overload is parsed before the intlist overload. `torch.mean(tensor, dim=())` used to get called with the intlist overload; now it is called with the dimname overload.

```
static PyObject * THPVariable_mean(PyObject* self_, PyObject* args, PyObject* kwargs)
{
  HANDLE_TH_ERRORS
  static PythonArgParser parser({
    "mean(Tensor input, *, ScalarType? dtype=None)",
    "mean(Tensor input, DimnameList[1] dim, bool keepdim=False, *, ScalarType? dtype=None, Tensor out=None)",
    "mean(Tensor input, IntArrayRef[1] dim, bool keepdim=False, *, ScalarType? dtype=None, Tensor out=None)",
  }, /*traceable=*/true);
```

It sounds like there are two problems here:
1. something is wrong for the derivative formula for torch.mean (dimname overload)
2. The dimnamelist overload should come after the intlist overload in python arg parser

Fixing (1) is a short-term solution, but I suspect there are other operators that have this problem. We should try to do (2).

**Comment by SsnL** [comment] 2019-10-18 17:56
I agree that (2) sounds the correct fix here!

**Comment by pietern** [comment] 2019-10-22 07:14
@zou3519 Will you work on a fix for this?

**Comment by zou3519** [comment] 2019-11-06 15:27
Fixed by https://github.com/pytorch/pytorch/pull/29199

**Closed by zou3519** 2019-11-06 15:27 UTC
Labels: module: named tensor, module: operators, triaged
