### ISSUE TITLE
Can't solve torch.lstsq() with specific values

### ISSUE THREAD

**Issue by xiaosu-zhu** [pytorch/pytorch#44378] opened 2020-09-09 11:58 UTC
## 🐛 Bug

When using `torch.lstsq` to solve with specific values, `torch.lstsq` produces wrong result (on cuda) or raises error (on cpu) while `scipy.linalg.lstsq` not.

## To Reproduce

1. Use the dumped `.npy` file: `a.npy`, `b.npy` to perform `torch.lstsq`
2. Meanwhile, `lstsq` can also be solved in `scipy.linalg.lstsq`
3. With the given `numpy array`, `torch.lstsq` raises error on `cpu`, or gives wrong result on `cuda`, while `scipy.linalg.lstsq` not.

Code samples and error messages:

Download files:
* `a.npy`: https://github.com/xiaosu-zhu/archives/releases/download/torch.lstsq/a.npy
* `b.npy`: https://github.com/xiaosu-zhu/archives/releases/download/torch.lstsq/b.npy

```python
import numpy as np
import scipy.linalg
import torch

# sparse 0-1 matrix with shape [100000, 1024]
# each row contains exactly 4 ones and other zeros
a = np.load("a.npy").astype(np.float32)
# int matrix with shape [100000, 128]
b = np.load("b.npy").astype(np.float32)

x, _, _, _ = scipy.linalg.lstsq(a, b)

# 67480.16036171981
print(((a @ x - b) ** 2).sum(-1).mean())

b = torch.from_numpy(b).cuda()
a = torch.from_numpy(a).cuda()
x, _ = torch.lstsq(b, a)

# 7.4439e+15
print(((a @ x[:a.shape[-1]] - b) ** 2).sum(-1).mean())

# raise RuntimeError: Lapack Error in gels : 
# The 259-th diagonal element of the triangular factor of A is zero 
# at /opt/conda/conda-bld/pytorch_1595629395347/work/aten/src/TH/generic/THTensorLapack.cpp:177
x, _ = torch.lstsq(b.cpu(), a.cpu())
```

Raise `RuntimeError: Lapack Error in gels : The 259-th diagonal element of the triangular factor of A is zero at /opt/conda/conda-bld/pytorch_1595629395347/work/aten/src/TH/generic/THTensorLapack.cpp:177` when using `torch.FloatTensor`.
Or an irregular result when using `torch.cuda.FloatTensor`.

## Expected behavior

Produce the same result with `scipy.linalg.lstsq`.

## Environment

```console
PyTorch version: 1.6.0
Is debug build: False
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Clang version: Could not collect
CMake version: version 3.16.3

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti
GPU 4: GeForce GTX 1080 Ti
GPU 5: GeForce GTX 1080 Ti
GPU 6: GeForce GTX 1080 Ti
GPU 7: GeForce GTX 1080 Ti

Nvidia driver version: 450.51.05
cuDNN version: Could not collect

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.6.0
[pip3] torchvision==0.7.0
[conda] blas                      1.0                         mkl    defaults
[conda] cudatoolkit               10.2.89              hfd86e86_1    defaults
[conda] mkl                       2020.1                      217    defaults
[conda] mkl-service               2.3.0            py38he904b0f_0    defaults
[conda] mkl_fft                   1.1.0            py38h23d657b_0    defaults
[conda] mkl_random                1.1.1            py38h0573a6f_0    defaults
[conda] numpy                     1.19.1           py38hbc911f0_0    defaults
[conda] numpy-base                1.19.1           py38hfa32c7d_0    defaults
[conda] pytorch                   1.6.0           py3.8_cuda10.2.89_cudnn7.6.5_0    pytorch
[conda] torchvision               0.7.0                py38_cu102    pytorch
```

cc @ezyang @gchanan @zou3519 @bdhirsh @vishwakftw @jianyuh @nikitaved @pearu @mruberry @heitorschueroff @walterddr @rgommers @vincentqb

**Comment by mrshenli** [comment] 2020-09-09 14:40
Hey @mruberry, do we also have plan to add a `lstsq` to `torch.linalg` and retire existing ones in the near future?

**Comment by mruberry** [comment] 2020-09-09 17:20
Yes we do, see https://github.com/pytorch/pytorch/issues/42666. We would definitely take a fix for this.

**Comment by xiaosu-zhu** [comment] 2020-11-23 02:28
Found related issue #11174

**Comment by chrisby** [comment] 2020-11-27 22:06
In fact, I stumbled over the fact that you can reproduce this very easily with a 2 x 2 matrix:

```
from scipy import linalg
import torch

a = np.array([[0., 0.], [0., 1.]])
b = np.array([[0., 0.], [0., 1.]])

linalg.lstsq(a,b)[0] # Yields [[0., 0.], [0., 1.]]

a_t = torch.from_numpy(a)
b_t = torch.from_numpy(b)
torch.lstsq(a_t,b_t)
```
The last line throws `RuntimeError: Lapack Error in gels : The 1-th diagonal element of the triangular factor of A is zero at ../aten/src/TH/generic/THTensorLapack.cpp:177`

Is there a timeline on a fix? Seems to be rather relevant.

**Comment by mruberry** [comment] 2020-11-27 22:24
Thanks for the simpler reproduction, @chrisby. 

Our team is currently working through linear algebra updates, but I've changed this issue to high priority. It should be fixed before the next release.

**Comment by xiaosu-zhu** [comment] 2020-11-28 02:19
Thank you, @chrisby @mruberry. Look forward to the next release ❤️

**Comment by nikitaved** [comment] 2020-11-28 10:24
The fix will probably require some thinking, the current implementation is based on the LAPACK's `?gels` 
https://software.intel.com/sites/products/documentation/doclib/mkl_sa/11/mkl_lapack_examples/_gels.htm
And the documentation reads that it expects the input of full rank.

**Comment by mruberry** [comment] 2020-11-28 11:45
@nikitaved To the best of my knowledge no one is working on this.

**Comment by xiaosu-zhu** [comment] 2020-11-28 12:08
Yes, the current implementation can't handle rank-deficient matrices, while [`scipy.linalg.lstsq`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.lstsq.html) using three routines: [?gelss](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-fortran/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem-routines/lapack-least-squares-and-eigenvalue-problem-driver-routines/linear-least-squares-lls-problems-lapack-driver-routines/gelss.html), [?gelsd](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-fortran/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem-routines/lapack-least-squares-and-eigenvalue-problem-driver-routines/linear-least-squares-lls-problems-lapack-driver-routines/gelsd.html), [?gelsy](https://software.intel.com/content/www/us/en/develop/documentation/mkl-developer-reference-fortran/top/lapack-routines/lapack-least-squares-and-eigenvalue-problem-routines/lapack-least-squares-and-eigenvalue-problem-driver-routines/linear-least-squares-lls-problems-lapack-driver-routines/gelsy.html), also from LAPACK.

**Comment by nikitaved** [comment] 2020-11-29 13:39
`?gelss, ?gelsd, ?gelsy` use SVD, but handle rand-deficient cases, while `?gels` does not use SVD, hence is faster, but does not handle rank-deficient cases.
Does it make sense to entirely switch to the SVD solution? Yes, we loose some speed, but at least we can avoid nasty errors during long training if the input becomes rank-deficient.

**Comment by mruberry** [comment] 2020-11-29 21:54
Generally we should bias towards numerical correctness/stability/precision. However, in this case we don't have to decide one or the other. We can add an optional parameter to `linalg.lstsq` to select the current faster but less stable option.

**Comment by chrisby** [comment] 2020-11-30 15:44
Yeah, this is exactly how `scipy` is doing it:

```
if driver is None:
    driver = lstsq.default_lapack_driver
if driver not in ('gelsd', 'gelsy', 'gelss'):
    raise ValueError('LAPACK driver "%s" is not found' % driver)
```

**Comment by nikitaved** [comment] 2020-12-01 19:14
Well, for CUDA it seems like Magma has only `?gels` that works only for overdetermined matrices. Fear not, we can still use SVD + pseudo inverse for underdetermined/rank-deficient inputs in CUDA.

**Comment by nikitaved** [comment] 2020-12-01 19:49
@mruberry , I have started working on this issue. The next release you mentioned above is 1.7.1, right?

**Comment by mruberry** [comment] 2020-12-01 19:52
1.7.1 is only some bugfixes for the 1.7 release. The next release from nightly is 1.8.

**Closed** 2021-03-03 03:01 UTC
Labels: high priority, module: linear algebra, module: numpy, triaged
