### ISSUE TITLE
Conformer model export flow don't work

### ISSUE THREAD

**Issue by freddan80** [pytorch/pytorch#141551] opened 2024-11-26 07:06 UTC
### 🐛 Describe the bug

Using the parameters from the example in:

https://pytorch.org/audio/main/generated/torchaudio.models.Conformer.html

then trying to use the export flow, causes an errror.

```
import torch
from torchaudio.models import Conformer

input_dim=80
model = Conformer(input_dim,
                  num_heads=4,
                  ffn_dim=128,
                  num_layers=4,
                  depthwise_conv_kernel_size=31,
 )
lengths = torch.randint(1, 400, (10,)) 
input_data = torch.rand(10, int(lengths.max()), input_dim) 
model.eval()
exported_program = torch.export.export(model, (input_data, lengths))
```

Error message:

```
torch._dynamo.exc.UserError: Could not guard on data-dependent expression Eq(u0, 345) (unhinted: Eq(u0, 345)).  (Size-like symbols: u0)

Caused by: x, _ = self.self_attn(  # torchaudio/models/conformer.py:194 in forward (nn/functional.py:6314 in multi_head_attention_forward)
```

### Versions

```
Collecting environment information...
PyTorch version: 2.6.0.dev20241112
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.6.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.3.9.4)
CMake version: version 3.29.0
Libc version: N/A

Python version: 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:19) [Clang 12.0.5 (clang-1205.0.22.11)] (64-bit runtime)
Python platform: macOS-14.6.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3 Pro

Versions of relevant libraries:
[pip3] executorch==0.5.0a0+e1bde90
[pip3] flake8==6.0.0
[pip3] flake8-breakpoint==1.1.0
[pip3] flake8-bugbear==23.6.5
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-plugin-utils==1.3.3
[pip3] flake8-pyi==23.5.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.21.3
[pip3] pytorch_sphinx_theme==0.0.24
[pip3] torch==2.6.0.dev20241112
[pip3] torchao-nightly==2024.3.18
[pip3] torchaudio==2.5.0.dev20241112
[pip3] torchsr==1.0.4
[pip3] torchsummary==1.5.1
[pip3] torchvision==0.20.0.dev20241112
[conda] Could not collect
```

cc @chauhang @penguinwu @avikchaudhuri @gmagogsfm @zhxchen17 @tugsbayasgalan @angelayi @suo @ydwu4

**Comment by freddan80** [comment] 2024-11-26 07:08
@digantdesai fyi

**Comment by freddan80** [comment] 2024-11-26 16:35
@mcremon-meta fyi

**Comment by angelayi** [comment] 2024-12-02 22:48
duplicate of https://github.com/pytorch/pytorch/issues/139610

**Comment by zingo** [comment] 2024-12-04 07:01
This was proposed as a fix in the duplicate issue (merged)  https://github.com/pytorch/pytorch/pull/141918

**Closed** 2024-12-04 07:04 UTC
Labels: oncall: pt2, oncall: export
