### ISSUE TITLE
Jit traced model fail to inference after save&load

### ISSUE THREAD

**Issue by rnwang04** [pytorch/pytorch#90653] opened 2022-12-11 09:52 UTC
### 🐛 Describe the bug

Hi, I was trying to use `torch.jit.trace` to convert a YOLOv3 model, and I want to combine it with autocast bf16.
However, I can convert my model and normal inference, but if I save and load the model, the loaded model will report error at the second time of inference.
```python
Iteration: 0, inference time: 0.2515592575073242 sec.
Traceback (most recent call last):
  File "detect.py", line 136, in <module>
    detections = model(input_imgs)
  File "/home/cpx/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/cpx/.local/lib/python3.7/site-packages/bigdl/nano/utils/inference/pytorch/model.py", line 31, in forward
    outputs = self.forward_step(*inputs)
  File "/home/cpx/.local/lib/python3.7/site-packages/bigdl/nano/deps/ipex/ipex_inference_model.py", line 106, in forward_step
    return self.model(*inputs)
  File "/home/cpx/.local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: UNSUPPORTED DTYPE
```
The model is obtained here : https://github.com/eriklindernoren/PyTorch-YOLOv3/blob/44a3e519c0e10bea371fc08b09be09bf26ab374e/detect.py#L56
and my code looks like :
```python
with torch.no_grad():
   with torch.cpu.amp.autocast():
       model = torch.jit.trace(model, input_sample, check_trace=False)
# it can inference here
for i in range(10):
   model(sample)
with torch.no_grad():
   with torch.cpu.amp.autocast():
       model.save("jit_bf16.ckpt")
       model = torch.jit.load("jit_bf16.ckpt")
       for i in range(10):
            # it will reprot error when i = 1
           model(sample)
```

### Versions

Collecting environment information...
PyTorch version: 1.12.1+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.1 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.16.3
Libc version: glibc-2.17

Python version: 3.7.15 (default, Nov  7 2022, 22:00:21)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-128-generic-x86_64-with-debian-bullseye-sid
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] intel-extension-for-pytorch==1.12.300
[pip3] numpy==1.21.6
[pip3] pytorch-lightning==1.6.4
[pip3] torch==1.12.1
[pip3] torchmetrics==0.7.2
[pip3] torchvision==0.13.1
[conda] intel-extension-for-pytorch 1.12.300                 pypi_0    pypi
[conda] pytorch-lightning         1.6.4                    pypi_0    pypi
[conda] torch                     1.12.1                   pypi_0    pypi
[conda] torchmetrics              0.7.2                    pypi_0    pypi
[conda] torchvision               0.13.1                   pypi_0    pypi

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @mingfeima @XiaobingSuper @ashokei @jingxu10 @mcarilli @ptrblck @leslie-fang-intel

**Comment by jingxu10** [comment] 2022-12-12 08:35
@CaoE

**Comment by CaoE** [comment] 2022-12-21 09:10
@rnwang04  Can't reproduce it on nightly and PyTorch 1.13. It should be fixed.

**Comment by rnwang04** [comment] 2022-12-21 09:12
Thx, I will try it again with PyTorch 1.13 on my side.

**Comment by CaoE** [comment] 2023-03-19 07:45
Close it. @rnwang04  If you have questions you can reopen it at any time.

**Closed** 2023-03-19 07:45 UTC
Labels: oncall: jit, module: cpu, module: amp (automated mixed precision)
