### ISSUE TITLE
min and max are order dependent with nans

### ISSUE THREAD

**Issue by cfinlay** [pytorch/pytorch#32438] opened 2020-01-21 15:58 UTC
## 🐛 Order dependent min and max

The functions torch.min and torch.max depend on the order of their arguments when one of the arguments is nan. This is unexpected behaviour.

## To Reproduce

Here is a minimal working example
```python
import torch
import numpy as np
a, b = torch.tensor(0.), torch.tensor(np.nan)
print('min(0,nan): ', torch.min(a, b) )
print('min(nan, 0): ', torch.min(b, a))
```

## Expected behavior

These function should not depend on order.

## Environment

```
Collecting environment information...
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.14.3
[pip3] numpydoc==0.8.0
[pip3] torch==1.2.0
[pip3] torchfile==0.1.0
[pip3] torchnet==0.0.4
[pip3] torchvision==0.4.0a0+6b959ee
[conda] blas                      1.0                         mkl  
[conda] mkl                       2018.0.2                      1  
[conda] mkl-service               1.1.2            py36h17a0993_4  
[conda] mkl_fft                   1.0.1            py36h3010b51_0  
[conda] mkl_random                1.0.1            py36h629b387_0  
[conda] pytorch                   1.2.0           py3.6_cuda10.0.130_cudnn7.6.2_0    pytorch
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchnet                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.4.0                py36_cu100    pytorch
```

**Comment by pbelevich** [comment] 2020-01-22 14:23
duplicate of #25016

**Closed by pbelevich** 2020-01-22 14:23 UTC
Labels: module: operators, topic: NaNs and Infs, triaged
