### ISSUE TITLE
torch_dispatch mode silent incorrectness with torch.compile

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#115653] opened 2023-12-12 18:27 UTC
```py
import torch
import torch.utils._pytree as pytree
from torch.utils._python_dispatch import TorchDispatchMode

@torch.compile(backend="inductor", fullgraph=True)
def f(x):
    return x.clone()

class Mul2Mode(TorchDispatchMode):
    def __torch_dispatch__(cls, func, types, args=(), kwargs=None):
        out = func(*args, **kwargs)
        return out * 2

x = torch.ones([])
with Mul2Mode():
    y = f(x)
print(y)
assert torch.allclose(y, 2 * x)
```
y is 1., but in eager mode the result is 2. Looks like the TorchDispatchMode just got ignored

cc @ezyang @gchanan @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by voznesenskym** [comment] 2023-12-12 19:50
Fast: graph break
Longer term: proper support

**Comment by bdhirsh** [comment] 2023-12-21 16:38
We should probably:

(1) have dynamo ignore any TorchDispatchModes while it is tracing out the  torch IR graph
(2) re-enable any TorchDispatchModes from the user, when dynamo sends the graph to AOTAutograd

**Comment by zou3519** [comment] 2024-01-09 15:24
Dynamo shouldn't ignore TorchDispatchModes while it is tracing out the torch IR graph because it is necessary during FakeTensor propagation (the TorchDispatchMode may change the FakeTensors that are bouncing Dynamo. I think the question here is around 1) why it's being ignored and 2) how to not apply it multiple times when we run through AOTAutograd and Inductor.

**Comment by bdhirsh** [comment] 2024-01-09 15:28
Whoops you’re right, we need it in dynamo for proper faketensor prop

**Comment by zou3519** [comment] 2024-03-18 12:48
Removing hi-pri (this type of torch dispatch mode is unrealistic, and it is unclear *what* the semantics should actually be under torch.compile and decompositions).

**Comment by ezyang** [comment] 2024-05-28 01:43
Actually supporting torch dispatch in Dynamo is a big lift and I would recommend it as a starter bug. As you observe, we clear out the enabled modes before running Dynamo, because they would interfere with the Dynamo tracing process itself. Most notably, we support running Dynamo with an outer fake tensor mode (and we would ideally report that mode when list of modes is queried). But if we clear out the mode without doing anything else with them, that would not lead to similar behavior.

**Comment by bdhirsh** [comment] 2024-06-20 19:33
Closing as duplicate of https://github.com/pytorch/pytorch/issues/105929

**Closed by bdhirsh** 2024-06-20 19:33 UTC
Labels: triaged, module: correctness (silent), oncall: pt2, module: pt2-dispatcher
