### ISSUE TITLE
module:mps reliable PyTorch crash when using half precision

### ISSUE THREAD

**Issue by lsb** [pytorch/pytorch#95409] opened 2023-02-23 21:31 UTC
### 🐛 Describe the bug

When I run

```
from sentence_transformers import SentenceTransformer

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device="mps")
model = model.half() # problem

print(model.encode("some text").sum())
```

in a notebook I get output of

```
loc("varianceEps"("(mpsFileLoc): /AppleInternal/Library/BuildRoots/9e200cfa-7d96-11ed-886f-a23c4f261b56/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm":228:0)): error: input types 'tensor<1x4x1xf16>' and 'tensor<1xf32>' are not broadcast compatible
LLVM ERROR: Failed to infer result type(s).
```

right before my Python kernel SIGABRTs.

When I do not cast to half precision the call works.

### Versions

Collecting environment information...
PyTorch version: 2.0.0.dev20230220
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.2.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: Could not collect
Libc version: N/A

Python version: 3.9.6 (default, Oct 18 2022, 12:41:40)  [Clang 14.0.0 (clang-1400.0.29.202)] (64-bit runtime)
Python platform: macOS-13.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Ultra

Versions of relevant libraries:
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.23.5
[pip3] torch==2.0.0.dev20230220
[pip3] torchaudio==2.0.0.dev20230223
[pip3] torchvision==0.15.0.dev20230223
[conda] numpy                     1.22.3          py310hdb36b11_0  
[conda] numpy-base                1.22.3          py310h5e3e9f0_0  

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by lsb** [comment] 2023-03-18 01:15
Will dig in more deeply in a bit. Running torch.compile() on the model works in the fp32 version and fails in the fp16 version

**Comment by malfet** [comment] 2023-04-07 16:59
I can reproduce the crash using 2.0.0, but not on the latest nightly
```
Python 3.11.0 (main, Jan 16 2023, 11:11:51) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from sentence_transformers import SentenceTransformer
>>> 
>>> model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2", device="mps")
>>> model = model.half() # problem
>>> 
>>> print(model.encode("some text").sum())
0.15443188
>>> import torch
>>> torch.__version__
'2.1.0.dev20230407'

```

**Comment by malfet** [comment] 2023-04-07 17:20
Actually, looks like it was fixed by https://github.com/pytorch/pytorch/pull/96430
I wonder if this should be a good candidate for 2.0.1...

**Comment by malfet** [comment] 2023-04-08 14:19
Closing as fixed in trunk.

**Closed by malfet** 2023-04-08 14:19 UTC
Labels: module: crash, triaged, module: half, module: mps
