### ISSUE TITLE
Advanced indexing doesn't validate negative indexes (regression)

### ISSUE THREAD

**Issue by wranai** [pytorch/pytorch#6472] opened 2018-04-10 16:49 UTC
Minimum example:

    torch.zeros(10)[torch.LongTensor([-11])] # returns bogus result on 0.4, error on 0.3.1

These all fail as they should:

    torch.zeros(10)[10]
    torch.zeros(10)[-11]
    torch.zeros(10)[torch.LongTensor([10])]

Works correctly on 0.3.1.post2.
Doesn't work on 0.4.0a0+df039e2.

Compiled with:
```
⟫ gcc-5 -v
Using built-in specs.
COLLECT_GCC=gcc-5
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/5/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 5.5.0-8ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-5/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-5 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-5-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-5-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-5-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 5.5.0 20171010 (Ubuntu 5.5.0-8ubuntu1) 

```

**Comment by SsnL** [comment] 2018-04-10 17:39
Thanks for reporting. This appears to be fixed on latest master. I can't reproduce. Try pull and rebuild.

**Comment by wranai** [comment] 2018-04-10 19:58
Did so. Advanced indexing still doesn't raise an exception on negative out-of-bounds indexes, but returns an arbitrary result:
```
⟫ python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 18:21:58) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.__version__
'0.4.0a0+04c215b'
>>> torch.zeros(10)[-11]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: index -11 is out of bounds for dimension 0 with size 10
>>> torch.zeros(10)[torch.LongTensor([-11])]

1.00000e-09 *
  1.8028
[torch.FloatTensor of size (1,)]

>>> 
```

**Comment by SsnL** [comment] 2018-04-10 20:03
I can reproduce

**Comment by SsnL** [comment] 2018-04-10 20:05
Cuda version works through. I'll add a check to TH.

**Closed** 2018-04-11 16:12 UTC
Labels: pytorch
