### ISSUE TITLE
Support Pip / Pipenv Without Conda

### ISSUE THREAD

**Issue by orokusaki** [pytorch/pytorch#4793] opened 2018-01-23 01:23 UTC
The tagline of PyTorch is:

> PyTorch is a deep learning framework that puts Python first.

Pip and Pipenv are the quintessential Python package manager tools for Python...

However, upon following the Pip (Python 3.6, OS X) instructions on http://pytorch.org/, I was met with an error informing me I needed Conda. If I don't intend on using R, Fortran, etc. directly in my app, is Conda still an intrinsic requirement of projects like PyTorch that e.g., use Fortran, or could PyTorch be made to install via Pip alone?

If there are low-level system requirements, I (and I think I speak for more than myself) don't mind e.g., brew installing CUDA. IOW, I'd like to be told "look, you need to install Go and CUDA to use this library", and then be given the choice of how I want to install those low-level system requirements and / or tools. Anything else could then be easily installed via e.g., Pipenv, rather than having to install some monolithic system like Conda, which is the antithesis of `Python first`.

    import this

> ...
> There should be one-- and preferably only one --obvious way to do it.
> ...
> If the implementation is hard to explain, it's a bad idea.
> ...

cc @ezyang @seemethere @malfet

**Comment by soumith** [comment] 2018-01-23 02:29
hey @orokusaki . What was the error that you received that informed you that you needed Conda? We support Pip on Linux and OSX platforms without needing Conda.

**Comment by SsnL** [comment] 2018-01-23 05:14
There was a similar question on the forum. Could you check and log and see if your pip is also finding the 0.1.12 version of torch? The 0.3 version should work fine.

**Comment by orokusaki** [comment] 2018-01-24 17:49
@soumith thanks for your quick reply! I'm not sure what I did differently yesterday, but I was just able to successfully run this:

    pipenv install http://download.pytorch.org/whl/torch-0.3.0.post4-cp36-cp36m-macosx_10_7_x86_64.whl

However, upon running `pipenv install torchvision` I did hit an error when PIpenv tried to add torchvision to my Pipfile:

    Adding torchvision to Pipfile's [packages]…
    Locking [dev-packages] dependencies…
    Locking [packages] dependencies…
    Traceback (most recent call last):
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/bin/pipenv", line 11, in <module>
        load_entry_point('pipenv==9.0.1', 'console_scripts', 'pipenv')()
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/vendor/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 1934, in install
        do_lock(system=system, pre=pre)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/cli.py", line 1102, in do_lock
        pre=pre
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/utils.py", line 545, in resolve_deps
        resolved_tree = actually_resolve_reps(deps, index_lookup, markers_lookup, project, sources, verbose, clear, pre)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/utils.py", line 507, in actually_resolve_reps
        resolved_tree.update(resolver.resolve(max_rounds=PIPENV_MAX_ROUNDS))
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 102, in resolve
        has_changed, best_matches = self._resolve_one_round()
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 200, in _resolve_one_round
        for dep in self._iter_dependencies(best_match):
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/resolver.py", line 296, in _iter_dependencies
        dependencies = self.repository.get_dependencies(ireq)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/piptools/repositories/pypi.py", line 153, in get_dependencies
        result = reqset._prepare_file(self.finder, ireq)
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 639, in _prepare_file
        abstract_dist.prep_for_dist()
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/pip/req/req_set.py", line 134, in prep_for_dist
        self.req_to_install.run_egg_info()
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/pip/req/req_install.py", line 438, in run_egg_info
        command_desc='python setup.py egg_info')
      File "/usr/local/Cellar/pipenv/9.0.1_2/libexec/lib/python3.6/site-packages/pipenv/patched/pip/utils/__init__.py", line 707, in call_subprocess
        % (command_desc, proc.returncode, cwd))
    pip.exceptions.InstallationError: Command "python setup.py egg_info" failed with error code 1 in /var/folders/qq/k1pgcct33ln4kh09zwx8n0vc0000gn/T/tmpn6qd_cjvbuild/torch/

Any indication of what my cause that?

cc @SsnL thanks also

**Comment by hmaarrfk** [comment] 2018-02-09 19:04
@orokusaki , I get the same error.

In fact, after attempting to install torchvision through pipenv, you can't install other packages in the pipenv either.


```
pipenv --three
pipenv install http://download.pytorch.org/whl/cpu/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl
pipenv install torchvision
pipenv install pep8
```
torchvision fails.

You can try it with other packages too, numpy, matplotlib, I just picked pep8, because I knew it wasn't going to be installed as a dependency.

**Comment by hmaarrfk** [comment] 2018-02-09 19:11
FYI, this seems to be a duplicate of/related to #566

**Comment by hmaarrfk** [comment] 2018-02-20 01:38
Even better, you kinda have to build the egg yourself:
```bash
pipenv install git+https://github.com/pytorch/pytorch#egg=torchvision
```

**Comment by AlJohri** [comment] 2018-02-28 18:36
I think this was fixed by: https://github.com/pytorch/pytorch/issues/4768

**Comment by AlJohri** [comment] 2018-02-28 18:42
Other relevant issues for those tracking:

- https://github.com/pytorch/pytorch/issues/497
- https://github.com/pytorch/pytorch/issues/566
- https://github.com/pypa/packaging-problems/issues/120

Thanks for your work on this @soumith!

**Comment by DanielAtKrypton** [comment] 2020-07-03 11:42
[This](https://stackoverflow.com/questions/59752559/how-to-specify-pytorch-cuda-version-in-pipenv) looks like a great solution. But it requires a Pytorch website small change.

**Comment by rgommers** [comment] 2021-05-28 20:46
We can close this I believe, there are valid wheels for all platforms, all linked issues are closed, and changing the download site structure to make `pipenv` happy is tracked by gh-25639, which has much more detail and is currently active.

**Closed by rgommers** 2021-05-28 20:46 UTC
Labels: enhancement, module: binaries, triaged

**Comment by caniko** [comment] 2021-06-01 06:43
I wish FAIR would pay more attention to #25639. It isn't just pytorch that suffers from this. detectron2 is not even accessible through pip, and needs to be installed through git.

This stuff is important for packages that don't have funds and/or the manpower to allocate to versioning and thereby LTS.

**Comment by rgommers** [comment] 2021-06-01 14:11
Thanks for the feedback @caniko. I agree that that issue would be good to address. I've been doing some triaging over the past days to see what packaging issues are still valid and are important to address - that's certainly one of them.
