### ISSUE TITLE
Apple MPS: Failed to create indexing library 

### ISSUE THREAD

**Issue by iSach** [pytorch/pytorch#117465] opened 2024-01-14 17:23 UTC
### 🐛 Describe the bug

On the latest nightly build (see *Versions*), MPS acceleration fails for many commands, including for example `torch.ones`.

```python
import torch
if torch.backends.mps.is_available():
    mps_device = torch.device("mps")
    x = torch.ones(1, device=mps_device)  # ERROR
    print(x)
else:
    print ("MPS device not found.")

torch.ones(1)  # OK: tensor([1.])
torch.ones(1).to('mps')  # ERROR
torch.zeros(1).to('mps') # OK: tensor([0.], device='mps:0')
torch.randn(1).to('mps')  # ERROR
torch.rand(1).to('mps')  # ERROR
```
[The error can be found here.](http://gist.github.com/iSach/f44fb1b750473b1ce445f196114a4399)

I am struggling to identify exactly why this happens for some functions only (e.g., `ones` but not `zeros`).

On **PyTorch 2.1.2**, it works perfectly. 

### Versions

```
PyTorch version: 2.3.0.dev20240114
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 14.2.1 (arm64)
GCC version: Could not collect
Clang version: 15.0.0 (clang-1500.1.0.2.5)
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.9.18 | packaged by conda-forge | (main, Aug 30 2023, 03:53:08)  [Clang 15.0.7 ] (64-bit runtime)
Python platform: macOS-14.2.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M1 Pro

Versions of relevant libraries:
[pip3] configmypy==0.1.0
[pip3] functorch==1.13.1
[pip3] msgpack-numpy==0.4.8
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.25.2
[pip3] pytorch-wavelets==1.3.0
[pip3] tensorly-torch==0.4.0
[pip3] torch==2.3.0.dev20240114
[pip3] torch-fidelity==0.3.0
[pip3] torch-harmonics==0.6.2
[pip3] torchaudio==2.2.0.dev20240114
[pip3] torchmetrics==0.11.4
[pip3] torchtyping==0.1.4
[pip3] torchvision==0.18.0.dev20240114
[conda] functorch                 1.13.1                   pypi_0    pypi
[conda] libopenvino-pytorch-frontend 2023.2.0             h965bd2d_0    conda-forge
[conda] msgpack-numpy             0.4.8                    pypi_0    pypi
[conda] nomkl                     3.0                           0  
[conda] numpy                     1.25.2                   pypi_0    pypi
[conda] numpy-base                1.26.3           py39ha9811e2_0  
[conda] pytorch                   2.3.0.dev20240114         py3.9_0    pytorch-nightly
[conda] pytorch-wavelets          1.3.0                    pypi_0    pypi
[conda] tensorly-torch            0.4.0                    pypi_0    pypi
[conda] torch-fidelity            0.3.0                    pypi_0    pypi
[conda] torch-harmonics           0.6.2                    pypi_0    pypi
[conda] torchaudio                2.2.0.dev20240114        py39_cpu    pytorch-nightly
[conda] torchmetrics              0.11.4                   pypi_0    pypi
[conda] torchtyping               0.1.4                    pypi_0    pypi
[conda] torchvision               0.18.0.dev20240114        py39_cpu    pytorch-nightly
```

cc @ezyang @gchanan @zou3519 @kadeng @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr

**Comment by malfet** [comment] 2024-01-14 23:38
Interesting. Most likely caused by https://github.com/pytorch/pytorch/pull/116942 but I wonder how it's possible...

**Comment by malfet** [comment] 2024-01-14 23:50
Marking as high-pri as it affects many users, see https://www.reddit.com/r/pytorch/comments/195nzng/not_workingaccelerated_pytorch_for_macbook_with/ and https://stackoverflow.com/questions/77811695/accelerated-pytorch-for-macbook-with-amd-gpus/77817111#77817111

**Comment by malfet** [comment] 2024-01-15 00:43
And the solution is super simple change min metal language version from 2.2 (supported in macOS 10.15+) to 2.3 (supported by MacOS11+) in https://github.com/pytorch/pytorch/blob/61a181e83c8de1065aeb37ab875066da8eaf617a/aten/src/ATen/mps/MPSDevice.mm#L16-L18

**Comment by malfet** [comment] 2024-01-15 01:21
Let's keep this one open, until the next binary builds actually happens (and also, I want to be able to use Metal3 even on Conda)

**Comment by iSach** [comment] 2024-01-15 08:30
Thank you for the fast response and fixes!

**Closed** 2024-01-15 15:25 UTC
Labels: high priority, triage review, triaged, module: regression, module: mps
