### ISSUE TITLE
Debug builds break sparse CSR

### ISSUE THREAD

**Issue by pmeier** [pytorch/pytorch#61103] opened 2021-07-01 07:41 UTC
## 🐛 Bug

Debug builds break sparse CSR.

## To Reproduce

Reproduction shows failure for `.crow_indices()`, but the same also happens for `.col_indices()`. `.values()` on the other hand seems to work as expected.

### built with `DEBUG=OFF`

```python
>>> import torch
>>> torch.__version__
'1.10.0a0+gitdb1dd9e'
>>> assert not torch.version.debug
>>> crow_indices = (0, 1, 2)
>>> col_indices = (1, 0)
>>> values = (1, 2)
>>> t = torch.sparse_csr_tensor(crow_indices, col_indices, values, size=(2, 2))
>>> t.crow_indices()
tensor([0, 1, 2])
```

### built with `DEBUG=ON`

```python
>>> import torch
>>> torch.__version__
'1.10.0a0+gitdb1dd9e'
>>> assert torch.version.debug
>>> crow_indices = (0, 1, 2)
>>> col_indices = (1, 0)
>>> values = (1, 2)
>>> t = torch.sparse_csr_tensor(crow_indices, col_indices, values, size=(2, 2))
>>> t.crow_indices()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
RuntimeError: result.storage().use_count() == 1INTERNAL ASSERT FAILED at "../torch/csrc/autograd/generated/VariableType_3.cpp":3891, please report a bug to PyTorch. function: crow_indices
```

## Expected behavior

Sparse CSR should work regardless of debug builds.

## Environment

<details><summary>built with DEBUG=OFF</summary>
<p>

```
Collecting environment information...
PyTorch version: 1.10.0a0+gitdb1dd9e
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (crosstool-NG 1.24.0.133_b0863d8_dirty) 9.3.0
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.9

Python version: 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.12.12-arch1-1-x86_64-with-arch
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080
Nvidia driver version: 465.31
cuDNN version: Probably one of the following:
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_adv_infer.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_adv_train.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_cnn_infer.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_cnn_train.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_ops_infer.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytest-pytorch==0.0.0
[pip3] torch==1.10.0a0+gitdb1dd9e
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] mkl                       2021.2.0           h726a3e6_389    conda-forge
[conda] mkl-include               2021.2.0           h726a3e6_389    conda-forge
[conda] numpy                     1.19.5           py36h2aa4a07_1    conda-forge
[conda] pytest-pytorch            0.2.0              pyh44b312d_0    conda-forge
[conda] torch                     1.10.0a0+gitdb1dd9e           dev_0    <develop>
```

</p>
</details>

<details><summary>built with DEBUG=ON</summary>
<p>

```
PyTorch version: 1.10.0a0+gitdb1dd9e
Is debug build: True
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Arch Linux (x86_64)
GCC version: (crosstool-NG 1.24.0.133_b0863d8_dirty) 9.3.0
Clang version: Could not collect
CMake version: version 3.20.2
Libc version: glibc-2.9

Python version: 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)  [GCC 9.3.0] (64-bit runtime)
Python platform: Linux-5.12.12-arch1-1-x86_64-with-arch
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1080
Nvidia driver version: 465.31
cuDNN version: Probably one of the following:
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_adv_infer.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_adv_train.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_cnn_infer.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_cnn_train.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_ops_infer.so.8.1.1
/usr/local/cudnn-8.1.1-cuda-11/lib64/libcudnn_ops_train.so.8.1.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] pytest-pytorch==0.0.0
[pip3] torch==1.10.0a0+gitdb1dd9e
[conda] magma-cuda111             2.5.2                         1    pytorch
[conda] mkl                       2021.2.0           h726a3e6_389    conda-forge
[conda] mkl-include               2021.2.0           h726a3e6_389    conda-forge
[conda] numpy                     1.19.5           py36h2aa4a07_1    conda-forge
[conda] pytest-pytorch            0.2.0              pyh44b312d_0    conda-forge
[conda] torch                     1.10.0a0+gitdb1dd9e           dev_0    <develop>
```

</p>
</details>

## Additional context

I'm always building with `DEBUG=ON` and this failure only popped up for a fresh build a few hours ago. In the recent past #60286 seems to be a possible offender. cc @soulitzer

**Comment by cpuhrsch** [comment] 2021-08-10 21:19
I managed to reproduce this locally and can confirm the failure. Will investigate.

**Comment by IvanYashchuk** [comment] 2022-01-06 14:57
The problem was resolved with https://github.com/pytorch/pytorch/commit/b7adb3350ac9115869a0c54eec326e387ccbcf6b.

**Closed by IvanYashchuk** 2022-01-06 14:57 UTC
Labels: module: sparse, module: build, triaged
