### ISSUE TITLE
"import torch" crashed after "import sklearn"

### ISSUE THREAD

**Issue by tibbers622** [pytorch/pytorch#31409] opened 2019-12-18 04:56 UTC
## 🐛 Bug

`import torch` crashed segmentation fault

## To Reproduce

```
1. docker run -it python:3.6.9 bash
2. pip install scikit-learn torch
3. python -c "import sklearn, torch"
```
> segmentation fault

at first `import torch` and then `import sklearn`
it works well.
```
3. python -c "import torch, sklearn"
```

## Expected behavior

not happen the `segmentation fault`

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version 1.4.0:
 - scikit-learn Version 0.22:
 - OS (Linux (docker python image)):
 - How you installed PyTorch (`pip`):

**Comment by kan-bayashi** [comment] 2019-12-18 11:24
This seems to be caused by scipy update.
https://github.com/scipy/scipy/issues/11237

**Comment by MGough** [comment] 2019-12-18 11:30
This is a duplicate of https://github.com/pytorch/pytorch/issues/31362

**Comment by albanD** [comment] 2019-12-18 11:46
Closing as duplicate of #31362

**Closed by albanD** 2019-12-18 11:46 UTC
