### ISSUE TITLE
Pytorch Convolution Layer Blocking Process in Linux

### ISSUE THREAD

**Issue by Olloxan** [pytorch/pytorch#12531] opened 2018-10-10 13:52 UTC
I am trying to implement an A3C algorithm in pytorch with some convolution layers. Therefore I start multiple processes in my Python programm each with a local neuronal network. The Network gets an image as input witch is processed by a convolution layer.
When I run this programm on a windows machine it has no problems and works fine but on a linux machine the process is somehow blocked when it trys to use the forward method of the network.

Here is a minimal example:

`
    import numpy as np
    import torch
    import torch.nn as nn
    import torch.nn.functional as F
    import torch.multiprocessing as mp
    
    
    state_shape = (3,10,10)
    num_actions = 5
    
    class Net(nn.Module):
        def __init__(self, in_shape, num_actions):
            super(Net, self).__init__()
            self.in_shape = in_shape
            self.num_actions = num_actions
            
            self.features = nn.Sequential(
                nn.Conv2d(in_shape[0], 16, kernel_size=3, stride=1),
                nn.ReLU(),
                nn.Conv2d(16, 16, kernel_size=3, stride=2),
                nn.ReLU(),
            )
                                 
            self.fc = nn.Sequential(
                nn.Linear(self.feature_size(), 256), # <-- problematic
                nn.ReLU(),
            )
                       
        def forward(self, x):  
            x = self.features(x)   
                
        def feature_size(self):
            return self.features(torch.zeros(1, *self.in_shape)).view(1, -1).size(1)
    
    class Worker(mp.Process):
        def __init__(self):
            super(Worker, self).__init__()       
            self.local_network = Net(state_shape, num_actions)           # local network
                
        def run(self):        
            s = np.zeros((3,10,10), dtype=np.float32)                           
            for i in range(10):
                print("{0}_before".format(i))                
                self.local_network.forward(torch.FloatTensor(s).unsqueeze(0))
                print("{0}_after".format(i))
                time.sleep(0.1)  
                        
    if __name__ == "__main__":              
        # parallel training
        workers = [Worker() for i in range(1)]
        [w.start() for w in workers]
        
        [w.join(timeout=10) for w in workers]

        [w.terminate() for w in workers]
`
I am using:
torch                 0.4.1 and
torchvision           0.2.1

It seems that the initialisation process is somehow faulty. When initializing the Linear layer of the notwork the convolution output must be flattened to know the inputsize of the linear layer. Therefore 

    `self.feature_size()`

is called. The computation of the sequential in the initialization process seems to cause the problem. Unfortunately I have no idea why. Has anyone encountered the same issue?

**Comment by zou3519** [comment] 2018-10-15 17:43
I can't reproduce but we've seen this before so we will look into it

**Comment by ngimel** [comment] 2021-04-13 01:00
Closing due to age

**Closed by ngimel** 2021-04-13 01:00 UTC
Labels: medium priority (this tag is deprecated), needs reproduction
