### ISSUE TITLE
torch.compile + DDP + activation checkpointing not working

### ISSUE THREAD

**Issue by pritamdamania87** [pytorch/pytorch#108269] opened 2023-08-30 18:46 UTC
### 🐛 Describe the bug

Similar to https://github.com/pytorch/pytorch/issues/97436, but using DDP as well. The code works as expected if I remove `torch.compile`.

Repro:
```
#!/usr/bin/env python
from functools import partial
import os
import torch
import torch.distributed as dist
import torch.multiprocessing as mp
from torch.nn.parallel import DistributedDataParallel as DDP
from torch.distributed.algorithms._checkpoint.checkpoint_wrapper import (
    CheckpointImpl,
    apply_activation_checkpointing,
    checkpoint_wrapper,
)


class MyModel(torch.nn.Module):
    def __init__(self):
      super(MyModel, self).__init__()
      self.fc1 = torch.nn.Linear(64, 32)
      self.fc2 = torch.nn.Linear(32, 16)
      self.fc3 = torch.nn.Linear(16, 8)
    
    def forward(self, inp):
      return self.fc3(self.fc2(self.fc1(inp)))

def run(rank, size):
    """ Distributed function to be implemented later. """
    model = MyModel().to(rank)

    # Activation checkpointing for Linear layers.
    non_reentrant_wrapper = partial(
        checkpoint_wrapper,
        checkpoint_impl=CheckpointImpl.NO_REENTRANT,
    )
    check_fn = lambda submodule: isinstance(submodule, torch.nn.Linear)
    apply_activation_checkpointing(model, checkpoint_wrapper_fn=non_reentrant_wrapper, check_fn=check_fn)

    ddp = torch.compile(DDP(model, device_ids=[rank]))
    out = ddp(torch.rand(10, 64).cuda(rank))
    out.sum().backward()
    print(f"{rank=} done")

def init_process(rank, size, fn, backend='nccl'):
    """ Initialize the distributed environment. """
    os.environ['MASTER_ADDR'] = '127.0.0.1'
    os.environ['MASTER_PORT'] = '29500'
    dist.init_process_group(backend, rank=rank, world_size=size)
    fn(rank, size)


if __name__ == "__main__":
    size = 2
    processes = []
    mp.set_start_method("spawn")
    for rank in range(size):
        p = mp.Process(target=init_process, args=(rank, size, run))
        p.start()
        processes.append(p)

    for p in processes:
        p.join()
```

Error:

```
[rank0]:[2023-08-30 14:37:59,643] [0/0] torch._dynamo.variables.torch: [WARNING] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
[rank1]:[2023-08-30 14:37:59,651] [0/0] torch._dynamo.variables.torch: [WARNING] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored
[rank1]:[2023-08-30 14:37:59,724] [1/0] torch._dynamo.output_graph: [WARNING] nn.Module state_dict and backward hooks are not yet supported by torch.compile, but were detected in your model and will be silently ignored. See https://pytorch.org/docs/master/compile/nn-module.html for more information and limitations.
[rank0]:[2023-08-30 14:37:59,724] [1/0] torch._dynamo.output_graph: [WARNING] nn.Module state_dict and backward hooks are not yet supported by torch.compile, but were detected in your model and will be silently ignored. See https://pytorch.org/docs/master/compile/nn-module.html for more information and limitations.
Process Process-2:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "testcompile.py", line 47, in init_process
    fn(rank, size)
  File "testcompile.py", line 38, in run
    out = ddp(torch.rand(10, 64).cuda(rank))
  File "torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 487, in catch_errors
    return hijacked_callback(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 634, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 382, in _convert_frame_assert
    return _compile(
  File "torch/_dynamo/convert_frame.py", line 562, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 484, in compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 451, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2078, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 728, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 691, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 2166, in RETURN_VALUE
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 857, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 981, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1048, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1033, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/backends/distributed.py", line 291, in compile_fn
    return self.backend_compile_fn(gm, example_inputs)
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/__init__.py", line 1568, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "torch/_inductor/compile_fx.py", line 1154, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3844, in aot_module_simplified
    assert name in mod._param_name_to_source, f"{name} not found."
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
AssertionError: L__self___fc1._checkpoint_wrapped_module.weight not found.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True

Process Process-1:
Traceback (most recent call last):
  File "multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "testcompile.py", line 47, in init_process
    fn(rank, size)
  File "testcompile.py", line 38, in run
    out = ddp(torch.rand(10, 64).cuda(rank))
  File "torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 328, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/external_utils.py", line 17, in inner
    return fn(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1519, in forward
    else self._run_ddp_forward(*inputs, **kwargs)
  File "torch/nn/parallel/distributed.py", line 1355, in _run_ddp_forward
    return self.module(*inputs, **kwargs)  # type: ignore[index]
  File "torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "torch/_dynamo/eval_frame.py", line 487, in catch_errors
    return hijacked_callback(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 634, in _convert_frame
    result = inner_convert(frame, cache_entry, hooks, frame_state)
  File "torch/_dynamo/convert_frame.py", line 140, in _fn
    return fn(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 382, in _convert_frame_assert
    return _compile(
  File "torch/_dynamo/convert_frame.py", line 562, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/convert_frame.py", line 484, in compile_inner
    out_code = transform_code_object(code, transform)
  File "torch/_dynamo/bytecode_transformation.py", line 1028, in transform_code_object
    transformations(instructions, code_options)
  File "torch/_dynamo/convert_frame.py", line 451, in transform
    tracer.run()
  File "torch/_dynamo/symbolic_convert.py", line 2078, in run
    super().run()
  File "torch/_dynamo/symbolic_convert.py", line 728, in run
    and self.step()
  File "torch/_dynamo/symbolic_convert.py", line 691, in step
    getattr(self, inst.opname)(inst)
  File "torch/_dynamo/symbolic_convert.py", line 2166, in RETURN_VALUE
    self.output.compile_subgraph(
  File "torch/_dynamo/output_graph.py", line 857, in compile_subgraph
    self.compile_and_call_fx_graph(tx, list(reversed(stack_values)), root)
  File "contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "torch/_dynamo/output_graph.py", line 981, in compile_and_call_fx_graph
    compiled_fn = self.call_user_compiler(gm)
  File "torch/_dynamo/utils.py", line 189, in time_wrapper
    r = func(*args, **kwargs)
  File "torch/_dynamo/output_graph.py", line 1048, in call_user_compiler
    raise BackendCompilerFailed(self.compiler_fn, e).with_traceback(
  File "torch/_dynamo/output_graph.py", line 1033, in call_user_compiler
    compiled_fn = compiler_fn(gm, self.example_inputs())
  File "torch/_dynamo/backends/distributed.py", line 291, in compile_fn
    return self.backend_compile_fn(gm, example_inputs)
  File "torch/_dynamo/repro/after_dynamo.py", line 117, in debug_wrapper
    compiled_gm = compiler_fn(gm, example_inputs)
  File "torch/__init__.py", line 1568, in __call__
    return compile_fx(model_, inputs_, config_patches=self.config)
  File "torch/_inductor/compile_fx.py", line 1154, in compile_fx
    return aot_autograd(
  File "torch/_dynamo/backends/common.py", line 55, in compiler_fn
    cg = aot_module_simplified(gm, example_inputs, **kwargs)
  File "torch/_functorch/aot_autograd.py", line 3844, in aot_module_simplified
    assert name in mod._param_name_to_source, f"{name} not found."
torch._dynamo.exc.BackendCompilerFailed: backend='compile_fn' raised:
AssertionError: L__self___fc1._checkpoint_wrapped_module.weight not found.

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

### Versions

PyTorch version: 2.1.0.dev20230830+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

CMake version: version 3.19.1
Libc version: glibc-2.31

cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] flake8-bugbear==23.3.23
[pip3] flake8-comprehensions==3.12.0
[pip3] flake8-executable==2.1.3
[pip3] flake8-logging-format==0.9.0
[pip3] flake8-pyi==23.3.1
[pip3] flake8-simplify==0.19.3
[pip3] mypy==1.5.1
[pip3] mypy-extensions==1.0.0
[pip3] mypy-protobuf==3.3.0
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.1.0+e6216047b8
[pip3] pytorch3d==0.6.2
[pip3] torch==2.1.0.dev20230830+cu121
[pip3] torch-mlir==1689007104-8a8e1baf
[pip3] torch-scatter==2.1.0
[pip3] torch-tb-profiler==0.4.1
[pip3] torchaudio==2.1.0.dev20230830+cu121
[pip3] torchfile==0.1.0
[pip3] torchmetrics==1.1.1
[pip3] torchvision==0.15.2a0+fa99a53
[pip3] triton==2.1.0
[conda] magma-cuda121             2.6.1                         1    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-include               2023.2.0         h84fe81f_49572    conda-forge
[conda] numpy                     1.23.5           py38h7042d01_0    conda-forge
[conda] pytorch3d                 0.6.2                    pypi_0    pypi
[conda] torch                     2.0.1+1693352690.cuda120.cudnn891.nccl218.ap          pypi_0    pypi
[conda] torch-mlir                1689007104-8a8e1baf          pypi_0    pypi
[conda] torch-scatter             2.1.0                    pypi_0    pypi
[conda] torch-tb-profiler         0.4.1                    pypi_0    pypi
[conda] torchfile                 0.1.0                    pypi_0    pypi
[conda] torchmetrics              1.1.1              pyhd8ed1ab_0    conda-forge
[conda] torchvision               0.15.2a0+fa99a53          pypi_0    pypi
[conda] triton                    2.1.0                    pypi_0    pypi

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by wconstab** [comment] 2023-08-30 23:21
@anijain2305 can you do a first pass triage, what's the expected flow here with AC and compile if DDP is not in the picture? And then what would we expect to happen when DDPOptimizer splits up the graph?  does the compiled AC impl make any assumptions about full graph, or about graph-breaks not happening across checkpointed region boundaries?

**Comment by pritamdamania87** [comment] 2023-09-02 00:10
The error seems to be coming from here: https://github.com/pytorch/pytorch/blob/main/torch/_functorch/aot_autograd.py#L3844.

We are looking for `L__self___fc1._checkpoint_wrapped_module.weight` in the `_param_name_to_source` map but the contents of the map are as follows and instead has the name `self.fc1._checkpoint_wrapped_module.weight`:

```
mod._param_name_to_source={'self.fc1._checkpoint_wrapped_module.weight': ParamBufferSource(base=AttrSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc1'), member='_checkpoint_wrapped_module'), member='weight'), 'self.fc1._checkpoint_wrapped_module.bias': ParamBufferSource(base=AttrSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc1'), member='_checkpoint_wrapped_module'), member='bias'), 'self.fc2._checkpoint_wrapped_module.weight': ParamBufferSource(base=AttrSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc2'), member='_checkpoint_wrapped_module'), member='weight'), 'self.fc2._checkpoint_wrapped_module.bias': ParamBufferSource(base=AttrSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc2'), member='_checkpoint_wrapped_module'), member='bias'), 'self.fc3._checkpoint_wrapped_module.weight': ParamBufferSource(base=AttrSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc3'), member='_checkpoint_wrapped_module'), member='weight'), 'self.fc3._checkpoint_wrapped_module.bias': ParamBufferSource(base=AttrSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc3'), member='_checkpoint_wrapped_module'), member='bias'), 'L__self___fc3.weight': ParamBufferSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc3')), member='weight'), 'L__self___fc3.bias': ParamBufferSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc3')), member='bias'), 'L__self___fc2.weight': ParamBufferSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc2')), member='weight'), 'L__self___fc2.bias': ParamBufferSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc2')), member='bias'), 'L__self___fc1.weight': ParamBufferSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc1')), member='weight'), 'L__self___fc1.bias': ParamBufferSource(base=NNModuleSource(base=AttrSource(base=LocalSource(local_name='self', cell_or_freevar=False), member='fc1')), member='bias')}
```

Maybe its an issue in populating `_param_name_to_source` with the right names?

**Comment by pritamdamania87** [comment] 2023-09-02 00:26
If I modify the forward function as follows (to avoid CheckpointWrapper modules):

```
    def forward(self, inp):
      fc1 = torch.utils.checkpoint.checkpoint(self.fc1, inp, use_reentrant=False)
      fc2 = torch.utils.checkpoint.checkpoint(self.fc2, fc1, use_reentrant=False)
      fc3 = torch.utils.checkpoint.checkpoint(self.fc3, fc2, use_reentrant=False)
      return fc3
```

I don't hit the name issue, but instead run into a DDPOptimizer issue:
```
NotImplementedError: DDPOptimizer backend: Found a higher order op in the graph. This is not supported. Please turn off DDP optimizer using torch._dynamo.config.optimize_ddp=False. Note that this can cause performance degradation because there will be one bucket for the entire Dynamo graph. Please refer to this issue - https://github.com/pytorch/pytorch/issues/104674.
```

Full trace: https://gist.github.com/pritamdamania87/fd1c9985672a9382f0d87c1cf56c9e48

**Comment by pritamdamania87** [comment] 2023-09-02 00:27
Looks like https://github.com/pytorch/pytorch/issues/104674 is relevant

**Comment by pritamdamania87** [comment] 2023-09-02 00:29
Setting `torch._dynamo.config.optimize_ddp = False` and using `torch.utils.checkpoint.checkpoint` directly does work.

**Comment by pritamdamania87** [comment] 2023-09-02 00:35
So concretely I guess there are two issues:

1. The need to set `torch._dynamo.config.optimize_ddp = False`
2. Using [CheckpointWrapper](https://github.com/pytorch/pytorch/blob/main/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py#L108) seems to mess up naming

**Comment by bdhirsh** [comment] 2023-09-02 00:37
One issue is that torch.utils.checkpoint is lowers into a higher order operator by dynamo, but the DDPOptimizwd (explicitly) does not support higher order ops, since figuring out how to partition properly around higher order ops is a pain

**Comment by pritamdamania87** [comment] 2023-09-02 01:08
Thanks @bdhirsh, was wondering if there is some more detailed documentation about higher order ops and why partitioning around these is hard?

> Using [CheckpointWrapper](https://github.com/pytorch/pytorch/blob/main/torch/distributed/algorithms/_checkpoint/checkpoint_wrapper.py#L108) seems to mess up naming

Regarding this, was wondering if there is an easy fix for this or if there is some other API which can be used to apply checkpointing to a module without modifying the original model code.

**Comment by anijain2305** [comment] 2023-09-02 03:05
I will take a look at why CheckpointWrapper does not work early next week.

**Comment by anijain2305** [comment] 2023-09-05 22:28
Fixed by https://github.com/pytorch/pytorch/pull/108599

Note that higher order op and Dynamo's DDP optimizer is still an issue. And its unlikely to go away quickly. Dynamo's DDP optimizer works on Dynamo graph, and splits it into smaller graphs to have greater compute-communication overlap. HigherOrderOps do not allow this splitting, and thus the exception.

**Comment by pritamdamania87** [comment] 2023-09-05 22:36
@anijain2305 Awesome! Thanks a lot for the quick fix!

> HigherOrderOps do not allow this splitting, and thus the exception.

What is the reason for this? Would this work if the checkpoint boundary the DDPOptimizer boundary is the same? So you are not splitting a HigherOrderOp but rather each HigherOrderOp is contained completely within the Dynamo graph split by DDPOptimizer?

**Comment by anijain2305** [comment] 2023-09-06 00:07
> What is the reason for this? 

DDP optimizer, when it was designed, is conceptually straightforward. Go through a flattened graph, keep counting the param size, if param size is beyond a threshold, do a graph break.

HigherOrderOps make it complex. Different HigherOrderOps might have different glue logic around splits. Like for each split, do you need some setup and teardown etc etc. We dont have logic/infra to tell DDPOptimizer how to setup these things with splits.

> Would this work if the checkpoint boundary the DDPOptimizer boundary is the same? So you are not splitting a HigherOrderOp but rather each HigherOrderOp is contained completely within the Dynamo graph split by DDPOptimizer?

Conceptually, this make sense. But this would require some work. I don't think we are planning to do this.

We also feel that DDPOptimizer today is working at the wrong abstraction. If it was working on AOT graph, the graph would be flattened by then, and none of these problems would exist.

**Comment by pritamdamania87** [comment] 2023-09-06 00:19
@anijain2305 Thanks for the detailed explanation! I recall there was this work https://github.com/pytorch/pytorch/pull/103822 to trace through DDP hooks as suggested here: https://dev-discuss.pytorch.org/t/torchdynamo-update-9-making-ddp-work-with-torchdynamo/860/8.

Would this make things simpler for this particular issue if we no longer need to insert graph breaks and DDP bucketing strategy is orthogonal to graph breaks in Dynamo?

**Comment by anijain2305** [comment] 2023-09-06 00:41
The bucketing strategy is currently linked with graph breaks unfortunately. For each graph extracted by Dynamo, all the gradients will be available when that whole graph finished backward execution. this is different from eager where gradients are available after each op. DDPoptimizer adds this fake graph breaks to allow for these grads to appear early, enabling overlap.

If you are willing, you can also change your model and introduce graph breaks around the bucket boundaries, something like this.

~~~
class MyModel(torch.nn.Module):
    def __init__(self):
      super(MyModel, self).__init__()
      self.fc1 = torch.nn.Linear(64, 32)
      torch._dynamo.graph_break()
      self.fc2 = torch.nn.Linear(32, 16)
      torch._dynamo.graph_break()
      self.fc3 = torch.nn.Linear(16, 8)
    
    def forward(self, inp):
      return self.fc3(self.fc2(self.fc1(inp)))
~~~

**Comment by ezyang** [comment] 2023-09-06 15:17
@anijain2305 breaks in the forward, not in init lol

**Comment by pritamdamania87** [comment] 2023-09-06 19:29
> The bucketing strategy is currently linked with graph breaks unfortunately. For each graph extracted by Dynamo, all the gradients will be available when that whole graph finished backward execution. this is different from eager where gradients are available after each op. DDPoptimizer adds this fake graph breaks to allow for these grads to appear early, enabling overlap.

Yes, I do understand that currently the bucketing strategy is linked with graph breaks. I was wondering if there are longer term plans to ensure that these two are independent? Having these two being linked leads to suboptimal outcomes. For example, if we would like to remove graph breaks in our model to improve performance this can only be done by increasing the bucket size. However, increasing the bucket size then has an adverse effect on compute-communication overlap. The ideal case would be to have zero graph breaks in our model and bucket sizes tuned to optimally overlap compute and communication.

**Comment by ezyang** [comment] 2023-09-06 19:48
So, to be clear, these are not "true" graph breaks. We split the graph up before sending it to AOTAutograd, but we don't have the same limitations as Dynamo graph breaks (in particular, breaking can happen inside inlined functions, and we don't have to recheck guards.)

To do better, we need some bigger guns. I think the best approach is with compiled autograd. With compiled autograd, we can have the allreduce in the compiled backwards graph rather than having to trigger them in the autograd engine. Then it doesn't matter if naively everything would have been delayed to the end; a subsequent compilation pass can push them as early as possible.

cc @jansel @voznesenskym

**Comment by aviverma01** [comment] 2023-09-12 22:54
@anijain2305 Any chance we can re-open this issue since the Fix PR got reverted?

**Comment by anijain2305** [comment] 2023-09-14 18:12
Thanks for letting me know. I will work on it this week.

**Closed** 2023-09-15 03:44 UTC
Labels: high priority, module: checkpoint, triaged, module: ddp, oncall: pt2

**Comment by paulpak58** [comment] 2023-09-15 19:14
Have there been updates for torch.compile + FSDP + activation checkpointing as well. It seems the last one was [#95846](https://github.com/pytorch/pytorch/issues/95846)
