### ISSUE TITLE
torch.mm has CUDA memory leaks for sparse matrices

### ISSUE THREAD

**Issue by antspy** [pytorch/pytorch#2912] opened 2017-09-30 11:10 UTC
Hi, 

I am using pytorch 0.1.12. I think I have found a bug in torch.mm that creates memory leaks, see discussion here: https://discuss.pytorch.org/t/cuda-memory-leaks/8142

In short, I was creating a big sparse matrix, and then multiplying it by a vector. So I did something like

    big_sparse = big_sparse.cuda()
    return torch.mm(big_sparse, dense_vector.view(-1,1))

Running this code several times increased the CUDA usage enormously (from 700Mb to more than 12 GB). After some debugging, it appeared that torch.mm was responsible for the huge CUDA leaks. Therefore I tried to use make that operation run on CPU, with 

`    return torch.mm(big_sparse, dense_vector.view(-1,1).cpu()).cuda()`

With this change the memory leaks are not there anymore. I don't know if torch.mm is creating leaks into RAM now, but with a quick check it did not appear to be the case. 

Is this issue fixed in version 0.2?

**Comment by soumith** [comment] 2017-09-30 14:26
there are quite a few memory leaks in may/june, so they might be fixed in `0.2`.

**Comment by SsnL** [comment] 2017-11-07 16:42
Unable to reproduce this using cuda sparse FloatTensor with 40000000 elements, size (2000, 200000) dimI=2 dimV=0 (`torch.mm` doesn't allow dimV > 0) and dense tensor of size (200, 1000).

**Comment by soumith** [comment] 2017-11-07 16:56
probably fixed on master then.

**Closed by soumith** 2017-11-07 16:56 UTC
