### ISSUE TITLE
Hang: sampling VonMises distribution gets stuck in rejection sampling for small kappa

### ISSUE THREAD

**Issue by julian-urban** [pytorch/pytorch#88443] opened 2022-11-03 19:33 UTC
### 🐛 Describe the bug

Sampling the VonMises distribution gets stuck in rejection sampling for small values of the concentration parameter. With the location parameter set to 1, the problem starts around ~1e-4 for single and ~1e-8 for double precision.

```torch.distributions.von_mises.VonMises(torch.Tensor([1]), torch.Tensor([1e-4])).sample()```

Numpy doesn't have this problem, likely because small values of the concentration are caught and handled explicitly, see [here](https://github.com/numpy/numpy/blob/623bc1fae1d47df24e7f1e29321d0c0ba2771ce0/numpy/random/src/legacy/legacy-distributions.c#L421). Implementing this might solve the issue.

### Versions

Collecting environment information...
PyTorch version: 1.12.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (conda-forge gcc 12.1.0-17) 12.1.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.8.13 (default, Oct 21 2022, 23:50:54)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: 
GPU models and configuration: GPU 0: NVIDIA T600 Laptop GPU
Nvidia driver version: 515.76
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.12.1
[pip3] torchaudio==0.12.1
[pip3] torchvision==0.13.1
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               10.2.89              hfd86e86_1  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py38h7f8727e_0  
[conda] mkl_fft                   1.3.1            py38hd3c417c_0  
[conda] mkl_random                1.2.2            py38h51133e4_0  
[conda] numpy                     1.21.5           py38h6c91a56_3  
[conda] numpy-base                1.21.5           py38ha15fc14_3  
[conda] pytorch                   1.12.1          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.12.1               py38_cu102    pytorch
[conda] torchvision               0.13.1               py38_cu102    pytorch

cc @ezyang @gchanan @zou3519 @fritzo @neerajprad @alicanb @nikitaved @VitalyFedyunin @jgong5 @mingfeima @XiaobingSuper @sanchitintel @ashokei @jingxu10 @mruberry @rgommers

**Comment by mruberry** [comment] 2022-11-07 15:02
This example will cause Colab to hang

**Comment by malfet** [comment] 2022-11-07 18:32
Reproduces in nightlies:
```
>>> torch.distributions.von_mises.VonMises(torch.Tensor([1]), torch.Tensor([1e-4])).sample()
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/nshulga/git/pytorch/pytorch/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/nshulga/git/pytorch/pytorch/torch/distributions/von_mises.py", line 118, in sample
    return _rejection_sample(self.loc, self.concentration, self._proposal_r, x)
  File "/Users/nshulga/git/pytorch/pytorch/torch/jit/_trace.py", line 1212, in wrapper
    return fn(*args, **kwargs)
  File "/Users/nshulga/git/pytorch/pytorch/torch/distributions/von_mises.py", line 62, in _rejection_sample
    accept = ((c * (2 - c) - u2) > 0) | ((c / u2).log() + 1 - c >= 0)
```

**Comment by mingfeima** [comment] 2022-11-15 01:25
WIP. Just to check, does cuda tensor have the same problem? @julian-urban

**Comment by julian-urban** [comment] 2022-11-15 02:48
Yes, this also hangs for me:

`torch.distributions.von_mises.VonMises(torch.Tensor([1]).cuda(), torch.Tensor([1e-4]).cuda()).sample()`

**Comment by mingfeima** [comment] 2022-11-21 13:24
as @julian-urban pointed out that NumPy does have a special handing when `concentration` (the NumPy code calls it `kappa`) is very small. However, after several rounds of debugging, I found that this is NOT the root cause of the hang issue reported in this thread.

The root cause is the `dtype`, the internal implementation will create new tensors using default dtype set by torch and for von mises distribution, 'float32' is not enough to cover `kappa` of `1e-4`, need double here.

Even without change of any source code, this hang issue can be fixed by setting default dtype to be double, such as
```python
(pytorch-mingfei) [mingfeim@mlt-skx091 bug_fixing]$ python
Python 3.7.11 (default, Jul 27 2021, 14:32:16)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> torch.set_default_dtype(torch.double)
>>> torch.distributions.von_mises.VonMises(torch.Tensor([1]), torch.Tensor([1e-4])).sample()
tensor([-0.4651])
```

The current test cases in `test_distributions.py` also set double as default: https://github.com/pytorch/pytorch/blob/master/test/distributions/test_distributions.py#L43

@malfet , any suggestion how to deal with this type issue ?

**Comment by julian-urban** [comment] 2022-11-21 14:31
@mingfeima Using double precision just shifts the onset of the problem to smaller values of `concentration`, around `1e-8` as mentioned in my initial post. I.e., the following will also hang:

```
>>> import torch
>>> torch.set_default_dtype(torch.double)
>>> torch.distributions.von_mises.VonMises(torch.Tensor([1]), torch.Tensor([1e-8])).sample()
```

The implementation used by NumPy has double prec by default, but explicitly catches any values `kappa < 1e-8`. Just setting the default dtype to double in the PyTorch implementation will not fully solve this issue.

**Comment by mingfeima** [comment] 2022-11-22 01:46
Sure, that's the point :) I am not very familiar with this von mises from the mathematic perspective. here is my question: is `1e-8` a valid input for it? Or in other words, is it necessary to port numpy implementation? ( i have this doubt because it is marked as legacy in numpy)

IFF the answer is yes, then we need to:
* implicitly upscale dtype to torch.float64 inside von mises, (torch.float32 won't be able to cover even 1e-4)
* map numpy implementation: catch kappa < 1e-8 and kappa < 1e-5

**Comment by julian-urban** [comment] 2022-11-22 02:06
@mingfeima `kappa` can be arbitrarily small and the distribution becomes uniform in the limit where it is zero. The implementation should reproduce this behavior IMHO.

**Comment by neerajprad** [comment] 2022-11-22 03:37
cc. @ahmadsalim, author of the original implementation in Pyro, in case he has any ideas.

**Closed** 2023-12-04 23:07 UTC
Labels: high priority, module: distributions, module: cpu, triaged, module: numpy, module: deadlock
