### ISSUE TITLE
RuntimeError: DataLoader worker is killed by signal: Killed.

### ISSUE THREAD

**Issue by Lmy0217** [pytorch/pytorch#8976] opened 2018-06-28 03:06 UTC
## Issue description

Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/media/zonstlab0/c3e7052f-24ed-4743-8506-fb7b8c6f0ba7/zonstlab0/myluo/Diagnosis/main_PVC.py", line 161, in <module>
    train(epoch)
  File "/media/zonstlab0/c3e7052f-24ed-4743-8506-fb7b8c6f0ba7/zonstlab0/myluo/Diagnosis/main_PVC.py", line 104, in train
    for batch_idx, (data, label) in enumerate(train_loader):
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 280, in __next__
    idx, batch = self._get_batch()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 259, in _get_batch
    return self.data_queue.get()
  File "/usr/lib/python3.5/queue.py", line 164, in get
    self.not_empty.wait()
  File "/usr/lib/python3.5/threading.py", line 293, in wait
    waiter.acquire()
  File "/usr/local/lib/python3.5/dist-packages/torch/utils/data/dataloader.py", line 178, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4161) is killed by signal: Killed.

## Code

https://github.com/Lmy0217/MedicalImaging/blob/pve/main_PVC.py#L79

## System Info

PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: TITAN Xp
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.2
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip3] numpy (1.14.3)
[pip3] pytorchviz (0.0.1)
[pip3] torch (0.4.0)
[pip3] torchfile (0.1.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by SsnL** [comment] 2018-06-28 06:13
your data loader worker process was killed by a signal

**Comment by Lmy0217** [comment] 2018-06-28 06:50
@SsnL what should I do?

**Comment by SsnL** [comment] 2018-06-28 16:09
@Lmy0217 You can try running with `num_workers=0` and see if it gives you a better error (as it doesn't use subprocesses).

**Comment by Lmy0217** [comment] 2018-06-29 01:39
@SsnL I set `num_workers=0` and then there are no errors.

**Comment by SsnL** [comment] 2018-06-30 20:37
Then something in your dataset __getitem__ doesn't like multiprocessing. What's in there?

**Comment by Lmy0217** [comment] 2018-07-01 02:48
@SsnL But when I set `num_workers=1`, my code is working sometime.

**Comment by soumith** [comment] 2018-07-01 13:47
it seems like there isn't an isolated bug, but something in user's Dataset that might not like multiprocessing. Closing the issue to lead it into https://discuss.pytorch.org

**Closed by soumith** 2018-07-01 13:47 UTC

**Comment by sdsy888** [comment] 2019-04-09 21:12
I've encountered the same problem recently. 

If you're using the `docker` to run the pytorch program, with high probability, it's because the shared memory of docker is not big enough for running your program in the specified batchsize.

The solutions for this circumstance are:
1. use a smaller batchsize to train your model.
2. exit the current docker, and re-run the docker with specified "--shm-size=16g" or bigger depends on your machine.

Hope this could help those who have same problem .:+1:

**Comment by mainguyenanhvu** [comment] 2019-09-20 04:27
I have run it in CPU and also met an error: RuntimeError: DataLoader worker (pid 6790) is killed by signal: Killed.

I followed @Lmy0217 , it was killed and printed in terminal:

Count of instances per bin: [85308 31958]
Test: [ 0/5000] eta: 8:26:32 model_time: 5.8156 (5.8156) evaluator_time: 0.1168 (0.1168) time: 6.0785 data: 0.1460
Killed

Please, help me. Thanks a lot.

**Comment by SystemErrorWang** [comment] 2020-01-14 03:37
I met the same problem, even if i set num_workers=0, the training was ended unexpectedly with only information "Killed". would like to know if it's because of dataloader or memory problem or something else

**Comment by twangnh** [comment] 2020-01-29 07:07
same error with testing model

**Comment by qmpzzpmq** [comment] 2020-02-22 01:42
is it fixed or? is it still there?

**Comment by wizyoung** [comment] 2020-03-16 06:32
@SystemErrorWang Same condition. I have more than 252G memory but still get the Dataloader killed. I monitored the system memory usage with htop command and the memory usage was always less than 30G if I set num_workers= 16. I am using the ubuntu 18.04 system and not docker. This definitely should not be the memory problem. (btw, the pytorch version is 1.4.0 on python 3.7.4)

**Comment by Soar-Sir** [comment] 2020-04-08 15:25
So...How to fix it?

**Comment by gingsi** [comment] 2020-04-15 10:35
Increasing CPU memory and decreasing workers to 10 instead of 20 worked for me. Might also be related to using multiple GPUs with nn.DataParallel. I have only seen this when training big models that need 2-4 GPUs.

**Comment by import-antigravity** [comment] 2020-07-25 20:16
Has there been an official fix to this? I'm testing a very simple model on 8 cores and 32 GB of memory and I'm still getting this error no matter how low I set `num_workers` (other than 0)

**Comment by SsnL** [comment] 2020-07-26 01:51
@import-antigravity Could you share the dataset code?  This is usually caused by a combination of environment and dataset code.

**Comment by Light--** [comment] 2020-08-13 17:25
> This is usually caused by a combination of environment and dataset code.
@SsnL 
what do you mean? can you give some minimum examples?

**Comment by import-antigravity** [comment] 2020-08-13 17:29
@SsnL in this case the dataset was just drawing samples from a distribution:

```python
from torch import Tensor
from torch.distributions import Distribution
from torch.utils.data import Dataset

class ProceduralDataset(Dataset, ABC):
    @property
    @abstractmethod
    def distribution(self) -> Distribution:
        pass

    def __init__(self, num_samples: int):
        self._n = num_samples
        self._samples = None

    def __getitem__(self, i):
        if self._samples is None:
            self._samples = self.distribution.sample((self._n,))
        return self._samples[i], Tensor()

    def __len__(self):
        return self._n

    def __iter__(self):
        self._i = 0
        return self

    def __next__(self):
        return self[self._i]
```

**Comment by je-dbl** [comment] 2020-09-17 14:43
I've encountered the same problem recently. I am running models locally. 

However, I created multiple virtual environments with the virtualenv command. The error might be linked to this, since my computer did not have enough memory to run the dataloader with numerous workers. 

When I removed the virtual environments, the error disappeared.

Created virtual environments like this 
```
virtualenv ~/env
source ~/env/bin/activate
```
And removed them like this 
```
deactivate
rm -rf env
```

**Comment by wizyoung** [comment] 2020-11-27 05:40
> @SystemErrorWang Same condition. I have more than 252G memory but still get the Dataloader killed. I monitored the system memory usage with htop command and the memory usage was always less than 30G if I set num_workers= 16. I am using the ubuntu 18.04 system and not docker. This definitely should not be the memory problem. (btw, the pytorch version is 1.4.0 on python 3.7.4)

Update on 20201127: Finally I figured the reason out after reading through the pytorch dataloader source code and some debug stuff. 

This error has nothing to do with pytorch dataloader and it occurs when your data preprocessing code stops unexpectedly and gets killed rather than throws exceptions at the python level. Then the pytorch dataloader detects the related process is no longer alive  and thus throws a RuntimeError exception. The logic of this part is located here https://github.com/pytorch/pytorch/blob/f02753fabb8116ab202fd56b3fcaf9389b7cade6/torch/utils/data/dataloader.py#L830

here `_workers_status` is controlled by a function named `_shutdown_worker` detecting  whether a worker has finished its work like iterating to the end. `w.is_alive()` detects whether the process gets killed by the reason I mentioned above.

I used to use a python package named `decord` which is a nice python wrapper of ffmpeg to decode video files on the fly. In the early version of 0.4.0, decord crashed on some video files with weird codec formats. The problem is that decord crashs on the C level rather than throws an appropriate Python exceptio. So I cannot use try ... except ... to skipped this crashing condition on the Python level. At this time the `_workers_status` is True but `w.is_alive()` is not alive and the dataloader gets killed. Finally I upgrade decord to a newer version 0.4.2 and the problem gets solved.

**Comment by hilman-dayo** [comment] 2020-12-22 15:13
> > @SystemErrorWang Same condition. I have more than 252G memory but still get the Dataloader killed. I monitored the system memory usage with htop command and the memory usage was always less than 30G if I set num_workers= 16. I am using the ubuntu 18.04 system and not docker. This definitely should not be the memory problem. (btw, the pytorch version is 1.4.0 on python 3.7.4)
> 
> Update on 20201127: Finally I figured the reason out after reading through the pytorch dataloader source code and some debug stuff.
> 
> This error has nothing to do with pytorch dataloader and it occurs when your data preprocessing code stops unexpectedly and gets killed rather than throws exceptions at the python level. Then the pytorch dataloader detects the related process is no longer alive and thus throws a RuntimeError exception. The logic of this part is located here
> 
> https://github.com/pytorch/pytorch/blob/f02753fabb8116ab202fd56b3fcaf9389b7cade6/torch/utils/data/dataloader.py#L829-L835
> 
> here `_workers_status` is controlled by a function named `_shutdown_worker` detecting whether a worker has finished its work like iterating to the end. `w.is_alive()` detects whether the process gets killed by the reason I mentioned above.
> 
> I used to use a python package named `decord` which is a nice python wrapper of ffmpeg to decode video files on the fly. In the early version of 0.4.0, decord crashed on some video files with weird codec formats. The problem is that decord crashs on the C level rather than throws an appropriate Python exceptio. So I cannot use try ... except ... to skipped this crashing condition on the Python level. At this time the `_workers_status` is True but `w.is_alive()` is not alive and the dataloader gets killed. Finally I upgrade decord to a newer version 0.4.2 and the problem gets solved.

Can you share how you debug your code?
I am facing a quite similar problem. I am using DataParallel with 4 GPU and since I do not use docker and am using huge RAM, it is hard to think that it has something to do with the shared memory problem. However, I am using [lightnet](https://gitlab.com/EAVISE/lightnet) framework which uses pandas quite extensively.

**Comment by amurumanasa** [comment] 2021-01-07 16:14
Can anyone help  me  out  where  to  set  num_workers=0

**Comment by amurumanasa** [comment] 2021-01-07 16:16
> @SsnL I set `num_workers=0` and then there are no errors.

@Lmy0217 Can you please tell me where to set num_workers=0

**Comment by Lmy0217** [comment] 2021-01-07 17:14
@amurumanasa the argument of [DataLoader](https://pytorch.org/docs/stable/data.html?highlight=dataloader#torch.utils.data.DataLoader).

**Comment by HeyangQin** [comment] 2021-03-21 02:05
It is very likely there was a out-of-memory(OOM) in your system so the data worker got killed by the system. Try to use `dmesg -T` to see the detailed reason.

**Comment by melonora** [comment] 2021-05-06 05:43
I noticed that this problem can also occur when you do not explicitly call with torch.no_grad() when loading the test batch and passing it through the network. It will always give an error in that case indicating an out of memory issue and saying that the DataLoader is too blame.

**Comment by tensorturtle** [comment] 2021-06-16 02:35
For me the issue comes up when I run another python script that accesses the filesystem while I'm training with PyTorch.
For example, if I am running Jupyter Lab while training is happening.
I haven't bothered to debug it, because I can easily avoid that situation.

**Comment by HESHAM-data** [comment] 2021-10-04 14:28
setting num_workers=0 worked for me thanks

**Comment by Jingnan-Jia** [comment] 2021-11-28 13:06
Anyway, Pytorch should have clearer error information. For instance, the following error information 

`RuntimeError: DataLoader worker (pid 26164) is killed by signal: Killed.` 

Should be extended to some sentenses like: 

`RuntimeError: DataLoader worker (pid 26164) is killed by signal: Killed. Because CPU/GPU memory run out`

**Comment by samra-irshad** [comment] 2021-12-06 05:57
I believe this error has something to do with pytorch version. My code was working fine on pytorch 1.0 version with num_workers=4, but when I switched to pytorch 1.4, it started throwing errors

**Comment by jogardi** [comment] 2021-12-20 13:13
In my case I just needed more memory

**Comment by Piteryo** [comment] 2021-12-29 12:02
Tip: if you're using DDP or some parallelism try to run your code without it on one GPU, I caught an error in my collate function for one of the batches that wasn't shown if I run DDP.

**Comment by lennart7** [comment] 2022-02-20 09:01
I'm running into a similar issue. RAM is not the problem (using about 10%). My train script crashes mysteriously with signal killed after about 4-5hrs on 4 GPUs using DDP. The error does not appear to occur on a single GPU. Only thing visible in dmesg are related to docker, probably as a result of the container shutting down?
```
[Sun Feb 20 06:16:58 2022] veth3a36688: renamed from eth0
[Sun Feb 20 06:16:58 2022] docker0: port 1(vethde6db48) entered disabled state
[Sun Feb 20 06:16:58 2022] docker0: port 1(vethde6db48) entered disabled state
```

**Comment by Jing--Li** [comment] 2022-08-02 02:50
For me, the reason is the lack of available RAM memory.

**Comment by genghaifei** [comment] 2022-09-27 07:04
decrease your train batch_size config may slove RAM memory not enough

**Comment by cgr71ii** [comment] 2022-11-16 18:22
In my case, I was using SLURM, and in my script I had:

```bash
#SBATCH --cpus-per-task=2
#SBATCH --mem-per-cpu=4G
```

and since my model needed more than 8G, there it was the problem. In this case I could solve my problem either increasing one or another option.

**Comment by ajavanmardii** [comment] 2023-01-11 15:50
> your data loader worker process was killed by a signal

RIP

**Comment by yuyulin704** [comment] 2023-05-20 13:06
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 27, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/Users/uu/venv/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 3228) is killed by signal: Terminated: 15. 

Where's the problem??

**Comment by HerrYu123** [comment] 2023-07-07 09:29
For me, just reduce the workers_per_gpu to half and work. The reason may be the lack of available RAM memory.

**Comment by JohnTailor** [comment] 2023-08-19 08:45
I got the error when calling break inside the dataloader loop:
for ix,(x,y) in enumerate(data):
     do stuff
     if abc: break

However, the error seemed to have no negative implication

**Comment by hzwanglichun** [comment] 2023-12-12 02:53
In my case, it's due to memory being filled with cache. Please use htop to observe. If the memory cache is saturated, use the command `sudo sh -c 'echo 3 > /proc/sys/vm/drop_caches'` to clear the cache.

**Comment by ShirleySyh** [comment] 2024-05-15 01:56
> I was getting a similar error so i tried to reduce the NUM_WORKERS but the error remained.
> 
> when i set num_workers = 0. I am getting the following error:
> 
> ### LOG FILE
> ```
> /usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
> and will be removed in future. Use torchrun.
> Note that --use_env is set by default in torchrun.
> If your script expects `--local_rank` argument to be set, please
> change it to read from `os.environ['LOCAL_RANK']` instead. See 
> https://pytorch.org/docs/stable/distributed.html#launch-utility for 
> further instructions
>   
> warnings.warn(
> 2023-05-30 10:14:52,783: Dataset TFR-my_data, batch_size 1, weight 1.000000, scale 64, margin 0.400000
> 2023-05-30 10:14:52,784: Added key: store_based_barrier_key:1 to store for rank: 0
> 2023-05-30 10:14:52,784: Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
> 2023-05-30 10:14:52,798: world_size: 1, rank: 0, local_rank: 0
> 2023-05-30 10:14:52,798: Dataset TFR-my_data, class_num 3, total_sample_num 2, sample_num 2
> 2023-05-30 10:14:52,798: Dataset TFR-my_data, total_size 2, mine_size 2, batch_num 2
> 2023-05-30 10:14:52,798: MultiDistributedSampler max_batch_num 2
> 2023-05-30 10:14:52,798: Step_per_epoch = 2
> 2023-05-30 10:14:55,083: IR_50 Backbone Generated
> 2023-05-30 10:14:55,084: Split FC: [3]
> 2023-05-30 10:14:55,084: FC Start Point: [0, 3]
> 2023-05-30 10:14:55,085: Rank: 0, shards ranges [0, 3]
> 2023-05-30 10:14:55.318074: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2023-05-30 10:14:56.085894: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> 2023-05-30 10:14:57,587: Current epoch 1, learning rate 0.1
> ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 47397) of binary: /usr/bin/python3
> Traceback (most recent call last):
>   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
>     main()
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
>     launch(args)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
>     run(args)
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
>     elastic_launch(
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
>     return launch_agent(self._config, self._entrypoint, list(args))
>   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
>     raise ChildFailedError(
> torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> ======================================================
> /content/TFace/recognition/train.py FAILED
> ------------------------------------------------------
> Failures:
>   <NO_OTHER_FAILURES>
> ------------------------------------------------------
> Root Cause (first observed failure):
> [0]:
>   time      : 2023-05-30_10:15:01
>   host      : 1cdd804a4035
>   rank      : 0 (local_rank: 0)
>   exitcode  : -6 (pid: 47397)
>   error_file: <N/A>
>   traceback : Signal 6 (SIGABRT) received by PID 47397
> ======================================================
> ```

Hi, I meet the same problem with you. Have you solved the problem yet?

**Comment by lgx12345678** [comment] 2024-07-22 04:14
Have you encountered the following problems? How to solve them?
Traceback (most recent call last):
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1133, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/queue.py", line 179, in get
    self.not_empty.wait(remaining)
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/threading.py", line 306, in wait
    gotit = waiter.acquire(True, timeout)
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1817) is killed by signal: Killed. 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "train_meta.py", line 131, in <module>
    val_loader=[x for x in val_loader]
  File "train_meta.py", line 131, in <listcomp>
    val_loader=[x for x in val_loader]
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 634, in __next__
    data = self._next_data()
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1329, in _next_data
    idx, data = self._get_data()
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1285, in _get_data
    success, data = self._try_get_data()
  File "/public/home/wl_ligexian/anaconda3/envs/py38/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1146, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 1817) exited unexpectedly

**Comment by ShirleySyh** [comment] 2024-07-22 04:20
> > I was getting a similar error so i tried to reduce the NUM_WORKERS but the error remained.
> > when i set num_workers = 0. I am getting the following error:
> > ### LOG FILE
> > ```
> > /usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py:180: FutureWarning: The module torch.distributed.launch is deprecated
> > and will be removed in future. Use torchrun.
> > Note that --use_env is set by default in torchrun.
> > If your script expects `--local_rank` argument to be set, please
> > change it to read from `os.environ['LOCAL_RANK']` instead. See 
> > https://pytorch.org/docs/stable/distributed.html#launch-utility for 
> > further instructions
> >   
> > warnings.warn(
> > 2023-05-30 10:14:52,783: Dataset TFR-my_data, batch_size 1, weight 1.000000, scale 64, margin 0.400000
> > 2023-05-30 10:14:52,784: Added key: store_based_barrier_key:1 to store for rank: 0
> > 2023-05-30 10:14:52,784: Rank 0: Completed store-based barrier for key:store_based_barrier_key:1 with 1 nodes.
> > 2023-05-30 10:14:52,798: world_size: 1, rank: 0, local_rank: 0
> > 2023-05-30 10:14:52,798: Dataset TFR-my_data, class_num 3, total_sample_num 2, sample_num 2
> > 2023-05-30 10:14:52,798: Dataset TFR-my_data, total_size 2, mine_size 2, batch_num 2
> > 2023-05-30 10:14:52,798: MultiDistributedSampler max_batch_num 2
> > 2023-05-30 10:14:52,798: Step_per_epoch = 2
> > 2023-05-30 10:14:55,083: IR_50 Backbone Generated
> > 2023-05-30 10:14:55,084: Split FC: [3]
> > 2023-05-30 10:14:55,084: FC Start Point: [0, 3]
> > 2023-05-30 10:14:55,085: Rank: 0, shards ranges [0, 3]
> > 2023-05-30 10:14:55.318074: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
> > To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
> > 2023-05-30 10:14:56.085894: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
> > 2023-05-30 10:14:57,587: Current epoch 1, learning rate 0.1
> > ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -6) local_rank: 0 (pid: 47397) of binary: /usr/bin/python3
> > Traceback (most recent call last):
> >   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
> >     return _run_code(code, main_globals, None,
> >   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
> >     exec(code, run_globals)
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 195, in <module>
> >     main()
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 191, in main
> >     launch(args)
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launch.py", line 176, in launch
> >     run(args)
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/run.py", line 753, in run
> >     elastic_launch(
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 132, in __call__
> >     return launch_agent(self._config, self._entrypoint, list(args))
> >   File "/usr/local/lib/python3.8/dist-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
> >     raise ChildFailedError(
> > torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
> > ======================================================
> > /content/TFace/recognition/train.py FAILED
> > ------------------------------------------------------
> > Failures:
> >   <NO_OTHER_FAILURES>
> > ------------------------------------------------------
> > Root Cause (first observed failure):
> > [0]:
> >   time      : 2023-05-30_10:15:01
> >   host      : 1cdd804a4035
> >   rank      : 0 (local_rank: 0)
> >   exitcode  : -6 (pid: 47397)
> >   error_file: <N/A>
> >   traceback : Signal 6 (SIGABRT) received by PID 47397
> > ======================================================
> > ```
> 
> Hi, I meet the same problem with you. Have you solved the problem yet?

I met this problem when experimenting with DOTA dataset, and the reason is that I forgot to change the data loading path from the original DOTA dataset to the pre-processed DOTA dataset. After I changed the loading path, the problem was solved.
