### ISSUE TITLE
1.4 GB CPU memory jump when call torch.distributed.barrier

### ISSUE THREAD

**Issue by pbelevich** [pytorch/pytorch#106511] opened 2023-08-03 02:16 UTC
### 🐛 Describe the bug

```python
import torch
from memory_profiler import profile

@profile
def test():
    print("before")
    torch.distributed.barrier()
    print("after")

torch.distributed.init_process_group(backend='nccl', rank=0, world_size=1, init_method='tcp://localhost:23456')

test()
```
Output:
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     4    378.0 MiB    378.0 MiB           1   @profile
     5                                         def test():
     6    378.0 MiB      0.0 MiB           1       print("before")
     7   1800.1 MiB   1422.1 MiB           1       torch.distributed.barrier()
     8   1800.1 MiB      0.0 MiB           1       print("after")
```

### Versions

```
PyTorch version: 2.0.1
Is debug build: False
CUDA used to build PyTorch: 11.8
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2
Libc version: glibc-2.27

Python version: 3.9.17 (main, Jul  5 2023, 20:41:20)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-1103-aws-x86_64-with-glibc2.27
Is CUDA available: True
CUDA runtime version: 11.1.105
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4
GPU 2: Tesla T4
GPU 3: Tesla T4
GPU 4: Tesla T4
GPU 5: Tesla T4
GPU 6: Tesla T4
GPU 7: Tesla T4

Nvidia driver version: 530.30.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              96
On-line CPU(s) list: 0-95
Thread(s) per core:  2
Core(s) per socket:  24
Socket(s):           2
NUMA node(s):        2
Vendor ID:           GenuineIntel
CPU family:          6
Model:               85
Model name:          Intel(R) Xeon(R) Platinum 8259CL CPU @ 2.50GHz
Stepping:            7
CPU MHz:             1200.056
CPU max MHz:         3500.0000
CPU min MHz:         1200.0000
BogoMIPS:            5000.00
Virtualization:      VT-x
L1d cache:           32K
L1i cache:           32K
L2 cache:            1024K
L3 cache:            36608K
NUMA node0 CPU(s):   0-23,48-71
NUMA node1 CPU(s):   24-47,72-95
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cdp_l3 invpcid_single intel_ppin ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm mpx rdt_a avx512f avx512dq rdseed adx smap clflushopt clwb intel_pt avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req pku ospke avx512_vnni md_clear flush_l1d arch_capabilities

Versions of relevant libraries:
[pip3] numpy==1.25.0
[pip3] torch==2.0.1
[pip3] torchvision==0.15.2
[pip3] triton==2.0.0
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2023.1.0         h6d00ec8_46342  
[conda] mkl-service               2.4.0            py39h5eee18b_1  
[conda] mkl_fft                   1.3.6            py39h417a72b_1  
[conda] mkl_random                1.2.2            py39h417a72b_1  
[conda] numpy                     1.25.0           py39h5f9d8c6_0  
[conda] numpy-base                1.25.0           py39hb5e798b_0  
[conda] pytorch                   2.0.1           py3.9_cuda11.8_cudnn8.7.0_0    pytorch
[conda] pytorch-cuda              11.8                 h7e8668a_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchtriton               2.0.0                      py39    pytorch
[conda] torchvision               0.15.2               py39_cu118    pytorch
```

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @ptrblck

**Comment by pbelevich** [comment] 2023-08-03 02:16
From https://discuss.pytorch.org/t/what-is-1-4-gb-cpu-memory-jump-when-call-torch-distributed-barrier/185505

**Comment by wconstab** [comment] 2023-08-07 18:20
I realized this memory usage is not related to torch.distributed.  It appears to be related to the first usage of cuda in the torch program.  Perhaps it is due to torch's caching allocator warming up, or something else that happens during cuda init.

Note that if I allocate a ones tensor on cpu device right before calling .barrier(), I still observe .barrier() allocating 1.2G memory.
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     4   1067.8 MiB   1067.8 MiB           1   @profile
     5                                         def test():
     6   1067.8 MiB      0.0 MiB           1       print("before")
     7   1067.8 MiB      0.0 MiB           1       x = torch.ones([2,3], device='cpu')
     8   2271.3 MiB   1203.5 MiB           1       torch.distributed.barrier()
     9   2271.3 MiB      0.0 MiB           1       print("after")
```

But if I allocate the ones tensor on cuda device instead, a 1.15GB allocation shows up with the ones call and the barrier allocates a small amount of memory as would be more in line with expectations.

```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
     4   1067.7 MiB   1067.7 MiB           1   @profile
     5                                         def test():
     6   1067.7 MiB      0.0 MiB           1       print("before")
     7   2225.2 MiB   1157.5 MiB           1       x = torch.ones([2,3], device='cuda')
     8   2270.8 MiB     45.7 MiB           1       torch.distributed.barrier()
     9   2270.8 MiB      0.0 MiB           1       print("after")
```

**Comment by wconstab** [comment] 2023-08-07 18:22
@zdevito do you happen to know if this is just 'expected behavior of cuda caching allocator' or something worth digging into?

**Comment by zdevito** [comment] 2023-08-07 18:59
I think this is just the expected behavior of initializing the CUDA backend for PyTorch for the first time. There is a lot of text for CUDA kernels, and I think these end up in CPU memory when they get loaded.

**Comment by wconstab** [comment] 2023-08-07 20:28
ok- going to close the issue then.

**Closed by wconstab** 2023-08-07 20:28 UTC
Labels: oncall: distributed, module: cuda
