### ISSUE TITLE
test_logdet_1x1_cuda is flaky

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#31304] opened 2019-12-15 22:01 UTC
https://app.circleci.com/jobs/github/pytorch/pytorch/3958244
https://app.circleci.com/jobs/github/pytorch/pytorch/3958086

cc @ezyang @gchanan @zou3519

**Comment by SsnL** [comment] 2019-12-16 02:36
duplicate of https://github.com/pytorch/pytorch/issues/31102

**Closed by SsnL** 2019-12-16 02:36 UTC
Labels: high priority, topic: flaky-tests, triage review
