### ISSUE TITLE
Docker Images have Python 3.7.7 installed instead of python 3.8

### ISSUE THREAD

**Issue by maaft** [pytorch/pytorch#42604] opened 2020-08-05 15:26 UTC
## 🐛 Bug

E.g. `pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel` docker image has python 3.7.7 installed instead of python 3.8

## To Reproduce

1. docker run pytorch/pytorch:1.6.0-cuda10.1-cudnn7-devel python --version
2. --> Python 3.7.7
## Expected behavior

Python 3.8 should be installed

**Comment by malfet** [comment] 2020-08-05 21:28
@maaft  why do you think python-3.8 must be bundled in those images?
cc: @seemethere

**Comment by seemethere** [comment] 2020-08-05 21:30
Docker images purposefully have 3.7, see https://github.com/pytorch/pytorch/blob/master/docker.Makefile#L17

There's no particular reason why, but this is currently the expected behavior.

Closing this issue, since this is expected behavior.

**Closed by seemethere** 2020-08-05 21:30 UTC
Labels: enhancement, module: docker, triaged

**Comment by maaft** [comment] 2020-08-06 07:01
@malfet Oh, I was looking at the Dockerfile from the github repo and it there is this argument `ARG PYTHON_VERSION=3.8
`. So I guessed that it should be indeed python 3.8. 

See: https://github.com/pytorch/pytorch/blob/release/1.6/docker/pytorch/Dockerfile
