### ISSUE TITLE
Bug in tensor.mul() with different dtypes

### ISSUE THREAD

**Issue by koelscha** [pytorch/pytorch#28758] opened 2019-10-27 17:03 UTC
When I multiply two sliced tensors of different dtypes, the result is arbitrary. This happens silently without even a warning being printed. As this works fine in numpy I expected it to work in pytorch as well.
Apparently, this can be avoided by making the slices contiguous.

Here's a notebook for reproducing the behavior: https://gist.github.com/koelscha/4dc9255a83e39b36b1cf20afa3c6fa74

PS: I'm using pytorch 1.3.0

**Comment by fmassa** [comment] 2019-10-27 18:00
I believe this is a duplicate of https://github.com/pytorch/pytorch/issues/28747
Let's keep the discussion there, I think this is a pretty serious bug

**Closed by fmassa** 2019-10-27 18:00 UTC

**Comment by koelscha** [comment] 2019-10-28 08:17
Oh, sorry. Did not see this issue. Thanks for referencing.
