### ISSUE TITLE
Torchscript model Runtime Error after quantization

### ISSUE THREAD

**Issue by algat** [pytorch/pytorch#76726] opened 2022-05-03 08:13 UTC
### 🐛 Describe the bug

When applying quantization to a CNN - ReLu - Batch Norm model, and converting it to Torchscript format, the inference fails.

Reproductible code:

```python
import torch.nn as nn
import torch
from torch.quantization import get_default_qconfig
from torch.quantization.quantize_fx import prepare_fx, convert_fx

class MyModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.conv = nn.Conv2d(in_channels=1, 
                    out_channels=64, 
                    kernel_size=(8, 20), 
                    stride=(1, 1),
                    padding=0)
        self.relu = nn.ReLU()
        self.bn = nn.BatchNorm2d(num_features=64)

    def forward(self, x):
        # x = [batch_size, channel=1, height=10, width=20]
        x = self.conv(x)
        x = self.relu(x)
        x = self.bn(x)
        return x
    
model = MyModel()

## Quantize model (post-training Static quantization FX Graph mode)
torch.backends.quantized.engine = "qnnpack"

model.to("cpu")
model.eval()

prepared_model = prepare_fx(model, {"": get_default_qconfig("qnnpack")})

with torch.no_grad(): # calibrate using random data
    data = torch.rand((7,1,10,20))
    prepared_model(data)
model_quantized = convert_fx(prepared_model)

## Prediction using scripted model an error
model_quantized_scripted = torch.jit.script(model_quantized) # script model
model_quantized_scripted(torch.rand((7,1,10,20))) # raises an error
```

The error raised:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [1], in <module>
     39 ## Prediction using scripted model raises and error
     40 model_quantized_scripted = torch.jit.script(model_quantized) # script model
---> 41 model_quantized_scripted(torch.rand((7,1,10,20)))

File ~/.pyenv/versions/3.8.11/envs/torch-commands/lib/python3.8/site-packages/torch/nn/modules/module.py:1110, in Module._call_impl(self, *input, **kwargs)
   1106 # If we don't have any hooks, we want to skip the rest of the logic in
   1107 # this function, and just call forward.
   1108 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1109         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1110     return forward_call(*input, **kwargs)
   1111 # Do not call functions when jit is used
   1112 full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "<eval_with_key>.46", line 9, in forward
    quantize_per_tensor = torch.quantize_per_tensor(x, conv_input_scale_0, conv_input_zero_point_0, torch.quint8);  x = conv_input_scale_0 = conv_input_zero_point_0 = None
    conv = self.conv(quantize_per_tensor);  quantize_per_tensor = None
    bn = self.bn(conv);  conv = None
         ~~~~~~~ <--- HERE
    dequantize = bn.dequantize();  bn = None
    return dequantize
  File "/Users/myname/.pyenv/versions/3.8.11/envs/torch-commands/lib/python3.8/site-packages/torch/nn/quantized/modules/batchnorm.py", line 17, in forward
    def forward(self, input):
        return torch.ops.quantized.batch_norm2d(input, self.weight, self.bias, self.running_mean,
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
                                                self.running_var, self.eps, self.scale, self.zero_point)
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument

```

### Versions

CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.0.1 (x86_64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.3)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.8.11 (default, Jan 12 2022, 11:42:46)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-12.0.1-x86_64-i386-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.21.5
[pip3] torch==1.11.0
[pip3] torchaudio==0.11.0
[pip3] torchvision==0.12.0
[conda] Could not collect

cc @EikanWang @jgong5 @wenzhe-nrv @sanchitintel @jerryzh168 @jianyuh @raghuramank100 @jamesr66a @vkuzo @Xia-Weiwen @leslie-fang-intel

**Comment by andrewor14** [comment] 2022-05-06 21:52
Hi @algat, does this happen without scripting the model?

**Comment by z-a-f** [comment] 2022-05-14 03:48
I suspect that this might be caused by the node propagation in `jit`, and is thrown by the `aten::IntImplicit`. Probably someone more familiar with `jit` should take a look?

cc @swolchok @eellison

**Comment by luigiluz** [comment] 2022-07-03 02:13
Any updates? 
I'm currently getting the same error message in the same situation. After scripting a quantized CNN model.

**Comment by ChicoQ** [comment] 2022-07-08 11:07
Hi team, I've got a similar issue here. 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Input In [64], in <cell line: 1>()
----> 1 scripted(torch.rand((1,3,160,160)))

File ~/xx/venv/lib/python3.8/site-packages/torch/nn/modules/module.py:1130, in Module._call_impl(self, *input, **kwargs)
   1126 # If we don't have any hooks, we want to skip the rest of the logic in
   1127 # this function, and just call forward.
   1128 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1129         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1130     return forward_call(*input, **kwargs)
   1131 # Do not call functions when jit is used
   1132 full_backward_hooks, non_full_backward_hooks = [], []

RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/tmp/ipykernel_293499/471289242.py", line 332, in forward
        """
        x = self.quant(x)
        x = self.conv2d_1a(x)
            ~~~~~~~~~~~~~~ <--- HERE
        x = self.conv2d_2a(x)
        x = self.conv2d_2b(x)
  File "/tmp/ipykernel_293499/471289242.py", line 35, in forward
    def forward(self, x):
        x = self.conv(x)
        x = self.bn(x)
            ~~~~~~~ <--- HERE
        x = self.relu(x)
        return x
  File "/xx/venv/lib/python3.8/site-packages/torch/nn/intrinsic/quantized/modules/bn_relu.py", line 28, in forward
        if len(input.shape) != 4:
            raise ValueError("Input shape must be `(N, C, H, W)`!")
        return torch.ops.quantized.batch_norm2d_relu(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            input, self.weight, self.bias, self.running_mean,
            self.running_var, self.eps, self.scale, self.zero_point)
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument

**Comment by jerryzh168** [comment] 2022-08-02 22:07
does it work if you change:
```
return torch.ops.quantized.batch_norm2d(
            input, self.weight, self.bias, self.running_mean,
            self.running_var, self.eps, self.scale, self.zero_point)
``` in https://github.com/pytorch/pytorch/blob/master/torch/nn/quantized/modules/batchnorm.py#L67-L69
to 
```
return torch.ops.quantized.batch_norm2d(
            input, self.weight, self.bias, self.running_mean,
            self.running_var, self.eps, float(self.scale), int(self.zero_point))
```?

similar for the batch_norm2d_relu case

**Comment by gorkemalgan** [comment] 2022-08-10 10:56
Any improvements on this? I am getting the same error on quantized + scripted model. No error on quantized model though

**Comment by swolchok** [comment] 2022-08-10 18:50
> I suspect that this might be caused by the node propagation in `jit`, and is thrown by the `aten::IntImplicit`. Probably someone more familiar with `jit` should take a look?
> 
> cc @swolchok @eellison

I'm not particularly familiar with the JIT.

**Comment by gogoymh** [comment] 2023-01-10 09:09
I got same error for quantized + scripted model. Is still not solved yet?

**Comment by evekeen** [comment] 2023-02-26 20:53
> return torch.ops.quantized.batch_norm2d(
> input, self.weight, self.bias, self.running_mean,
> self.running_var, self.eps, float(self.scale), int(self.zero_point))

This does not help. BTW `zero_point` is supposed to be of `int` type; however, it still does not work - the same error.
Also, it does not matter if we can change the python code since the actual error happens on the mobile side using the PytorchLite library.

**Comment by jason-shang** [comment] 2023-03-26 14:33
Getting the same error for quantized TorchScript model still

**Comment by kai3316** [comment] 2023-05-25 07:58
Getting the same error

**Comment by malayaj2000** [comment] 2023-06-03 13:40
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript, serialized code (most recent call last):
  File "code/__torch__.py", line 14, in forward
    x_q = (quant).forward(x, )
    model = self.model
    y_q = (model).forward(x_q, )
           ~~~~~~~~~~~~~~ <--- HERE
    dequant = self.dequant
    return (dequant).forward(y_q, )
  File "code/__torch__.py", line 35, in forward
    x: Tensor) -> Tensor:
    preprocessor = self.preprocessor
    pre_x = (preprocessor).forward(x, )
             ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    encoL1 = self.encoL1
    encoL1_x = (encoL1).forward(pre_x, )
  File "code/__torch__/torch/nn/modules/container.py", line 12, in forward
    _0 = getattr(self, "0")
    _1 = getattr(self, "1")
    input0 = (_0).forward(input, )
              ~~~~~~~~~~~ <--- HERE
    return (_1).forward(input0, )
  def __len__(self: __torch__.torch.nn.modules.container.Sequential) -> int:
  File "code/__torch__.py", line 71, in forward
    bn = self.bn
    conv = self.conv
    _0 = (relu).forward((bn).forward((conv).forward(x, ), ), )
                         ~~~~~~~~~~~ <--- HERE
    return _0
class AttentionBlock(Module):
  File "code/__torch__/torch/ao/nn/quantized/modules/batchnorm.py", line 26, in forward
    scale = self.scale
    zero_point = self.zero_point
    _0 = ops.quantized.batch_norm2d(input, weight, bias, running_mean, running_var, 1.0000000000000001e-05, annotate(float, scale), annotate(int, zero_point))
                                                                                                            ~~~~~~~~~~~~~~~~~~~~~ <--- HERE
    return _0

Traceback of TorchScript, original code (most recent call last):
  File "<ipython-input-25-f921a25b6103>", line 16, in forward
  def forward(self,x):
    x_q = self.quant(x)
    y_q = self.model(x_q)
          ~~~~~~~~~~ <--- HERE
    y =  self.dequant(y_q)
    return y
  File "<ipython-input-24-f31ddffea9c9>", line 332, in forward
  def forward(self,x):
    pre_x = self.preprocessor(x)
            ~~~~~~~~~~~~~~~~~ <--- HERE
  
    encoL1_x = self.encoL1(pre_x)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/container.py", line 217, in forward
    def forward(self, input):
        for module in self:
            input = module(input)
                    ~~~~~~ <--- HERE
        return input
  File "<ipython-input-24-f31ddffea9c9>", line 246, in forward
  def forward(self,x):
    return self.relu(self.bn(self.conv(x)))
                     ~~~~~~~ <--- HERE
  File "/usr/local/lib/python3.10/dist-packages/torch/ao/nn/quantized/modules/batchnorm.py", line 70, in forward
        # disabling this since this is not symbolically traceable
        # self._check_input_dim(input)
        return torch.ops.quantized.batch_norm2d(
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            input, self.weight, self.bias, self.running_mean,
            self.running_var, self.eps, self.scale, self.zero_point)
RuntimeError: Cannot input a tensor of dimension other than 0 as a scalar argument

I am also getting this same error any update on this ??

**Comment by barry-cruxml** [comment] 2023-07-06 06:07
This still seems to be a problem in PyTorch 2.0.1.  Is this going to be fixed?

**Comment by jerryzh168** [comment] 2023-09-01 23:11
this is probably not going to be fix, with 2.0 we are moving to new compiler stack, both fx graph mode quantization and Torchscript are in maintenance mode now

**Comment by Xia-Weiwen** [comment] 2024-05-17 07:54
Hi @algat @kent252 . Looks like this issue is no longer there. Note that the `prepare_fx` API has changed since the issue was reported. And BTW, if you want to do quantization on x86 CPU, the `x86` backend, instead of `qnnpack`, is the default and preferred one.
```python
from torch.ao.quantization import get_default_qconfig_mapping
torch.backends.quantized.engine = "x86"
prepared_model = prepare_fx(model, get_default_qconfig_mapping("x86"), example_inputs=torch.rand((7,1,10,20)))
```

**Comment by kent252** [comment] 2024-05-17 09:24
> Hi @algat @kent252 . Looks like this issue is no longer there. Note that the `prepare_fx` API has changed since the issue was reported. And BTW, if you want to do quantization on x86 CPU, the `x86` backend, instead of `unpack`, is the default and preferred one.
> 
> ```python
> from torch.ao.quantization import get_default_qconfig_mapping
> torch.backends.quantized.engine = "x86"
> prepared_model = prepare_fx(model, get_default_qconfig_mapping("x86"), example_inputs=torch.rand((7,1,10,20)))
> ```

Dear @Xia-Weiwen, thank you for your reply, I tried it and it works. However, I observed a drop in accuracy. Since I use Post-training Quantization or QAT, the result is not dropping. but with the script above, the accuracy of the quantized model is very poor. Is that normal?

**Comment by Xia-Weiwen** [comment] 2024-05-17 11:16
Hi @kent252 Not sure about the problem you met. Since this issue is too old, API's may have changed. Please refer to the doc here: https://pytorch.org/docs/stable/quantization.html#quantization-api-summary and double check your script. If you believe it is still an issue, please create a new issue for it.

**Comment by Xia-Weiwen** [comment] 2024-05-17 11:18
Close as the issue no longer exists.

**Closed by Xia-Weiwen** 2024-05-17 11:18 UTC
Labels: oncall: jit, oncall: quantization, low priority, triaged

**Comment by valentin-fngr** [comment] 2024-07-02 13:25
I am actually having the same issue as @algat in the exact same context.
