### ISSUE TITLE
Race condition in docker image autogeneration

### ISSUE THREAD

**Issue by malfet** [pytorch/pytorch#62738] opened 2021-08-04 18:01 UTC
After commit modifying `.circleci/docker` is landed in default branch but before images are rebuild, `calculate-docker-image` jobs for all subsequent commits/PR will fail until the the build is done.

Consider following series of commits for example:
https://github.com/pytorch/pytorch/commit/76c447a730c77df9c571605d6b589db9876b4c3f <- modified `.circleci/docker` folder, all docker build jobs eventually succeed
https://github.com/pytorch/pytorch/commit/ddd916c21010c69b6015edd419d62f28664373a7 <- landed 6 min later, doesn't make any changes to the above-mentioned folder, but all the jobs have failed with "Something has gone wrong and the previous image isn't available for the merge-base of your branch", for example see [this](https://app.circleci.com/pipelines/github/pytorch/pytorch/359443/workflows/70baa3f5-bb29-48a3-90b4-08453ce60b15/jobs/15161809)
And all subsequent commits that made no changes to the above-mentioned folder, had some docker build failures until  https://github.com/pytorch/pytorch/commit/59dd12042e4e48d17bc6b1e04a7b51f2f1336af5, that  was landed an hour later

 

cc @ezyang @seemethere @malfet @walterddr @pytorch/pytorch-dev-infra

**Comment by seemethere** [comment] 2022-03-04 19:03
Duplicate of #70881, closing in favor of that issue

**Closed by seemethere** 2022-03-04 19:03 UTC
Labels: module: ci, triaged, module: docker, needs design
