### ISSUE TITLE
misleading warning about named tensors support

### ISSUE THREAD

**Issue by christian-rauch** [pytorch/pytorch#60369] opened 2021-06-21 14:01 UTC
## 🐛 Bug

Since version 1.9.0 I get a warning about the named tensor support:
```
UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  /pytorch/c10/core/TensorImpl.h:1156.)
```

The warning suggests that I deliberatively chose to use this experimental feature. But I think this is not the case. I am using the same code since version 1.5.1 and I believe that it does not use the named tensors experimental feature.

## To Reproduce

1. download https://github.com/magicleap/SuperPointPretrainedNetwork
2. run `./demo_superpoint.py camera`

## Expected behavior

As with version 1.8 there should be no warning message.

## Environment
```
Collecting environment information...
PyTorch version: 1.9.0+cu102
Is debug build: No
CUDA used to build PyTorch: 10.2

OS: Ubuntu 20.04.2 LTS
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
CMake version: version 3.16.3

Python version: 3.8
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: NVIDIA GeForce GTX 1650
Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1

Versions of relevant libraries:
[pip3] numpy==1.17.4
[pip3] numpydoc==1.1.0
[pip3] torch==1.9.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0
[conda] Could not collect
```

cc @zou3519

**Comment by gchanan** [comment] 2021-06-21 18:34
duplicate of https://github.com/pytorch/pytorch/issues/60053.

**Closed by gchanan** 2021-06-21 18:34 UTC
Labels: module: named tensor, triaged
