### ISSUE TITLE
i download preview libtorch(cuda9.0) release lib but can't run on Driver Version: 384.81?

### ISSUE THREAD

**Issue by mlinxiang** [pytorch/pytorch#14177] opened 2018-11-19 05:16 UTC
i download preview libtorch(cuda9.0) release lib but my c++ example can't run on Driver Version: 384.81 . but can run on Driver Version: 390.67, how to fix this without update driver?

**Comment by soumith** [comment] 2018-11-19 05:47
this cannot be fixed on cuda9.0 version of libtorch without driver update. Try downloading the CUDA 8.0 version

**Closed by soumith** 2018-11-19 05:47 UTC

**Comment by mlinxiang** [comment] 2018-11-19 06:40
i have two machine, both cuda version is 9.0, driver290.67 can run , but driver 384.81 will not .
i do as you say download cuda8.0 libtorch but the same error
![image](https://user-images.githubusercontent.com/6283983/48690341-09ea2200-ec09-11e8-90d2-1fd581ea1f82.png)

**Comment by soumith** [comment] 2018-11-19 06:50
i am not sure what the issue is, but it's related to CUDA/driver interaction. The error comes from CUDA API, we just print it out.
