### ISSUE TITLE
token ""CUDACC_VER is no longer supported. Use CUDACC_VER_MAJOR, CUDACC_VER_MINOR, and CUDACC_VER_BUILD instead."" is not valid in preprocessor expressions

### ISSUE THREAD

**Issue by Rahul-Venugopal** [pytorch/pytorch#9180] opened 2018-07-05 09:16 UTC
## I tried to install caffe2 by following this link  "https://caffe2.ai/docs/getting-started.html?platform=ubuntu&configuration=compile "

Every step was sucesfully compiled , but unfortunately while compiling the last command 

****sudo make install**   

I am getting the following ### output/error :

Scanning dependencies of target python_copy_files
[ 72%] Built target python_copy_files
[ 72%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/sgd/caffe2_gpu_generated_adagrad_op_gpu.cu.o
[ 72%] Building NVCC (Device) object caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o
In file included from /usr/local/cuda/include/common_functions.h:50:0,
                 from /usr/local/cuda/include/cuda_runtime.h:115,
                 from <command-line>:0:
/usr/local/cuda/include/crt/common_functions.h:64:24: error: token ""__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."" is not valid in preprocessor expressions
 #define __CUDACC_VER__ "__CUDACC_VER__ is no longer supported.  Use __CUDACC_VER_MAJOR__, __CUDACC_VER_MINOR__, and __CUDACC_VER_BUILD__ instead."
                        ^
/usr/include/eigen3/Eigen/src/Core/util/Macros.h:364:33: note: in expansion of macro ‘__CUDACC_VER__’
 #if defined(__CUDACC_VER__) &&  __CUDACC_VER__ >= 70500 && __cplusplus > 199711L
                                 ^
CMake Error at caffe2_gpu_generated_math_gpu.cu.o.Release.cmake:219 (message):
  Error generating
  /home/rv/pytorch/build/caffe2/CMakeFiles/caffe2_gpu.dir/utils/./caffe2_gpu_generated_math_gpu.cu.o

caffe2/CMakeFiles/caffe2_gpu.dir/build.make:63: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o' failed
make[2]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/utils/caffe2_gpu_generated_math_gpu.cu.o] Error 1
CMakeFiles/Makefile2:1456: recipe for target 'caffe2/CMakeFiles/caffe2_gpu.dir/all' failed
make[1]: *** [caffe2/CMakeFiles/caffe2_gpu.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**python collect_env.py**
Collecting environment information...
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: version 3.5.1

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: 9.0.252
GPU models and configuration: GPU 0: Quadro M2000M
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.4
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.11.0)
[pip] torch (0.4.0)
[conda] Could not collect

**Comment by pjh5** [comment] 2018-07-09 19:48
Can you post your cmake output? ctrl-f in all the output for "Summary" and it will be the list after that. 

What is "ls -lah /usr/local/cuda" ? Is CUDA_HOME set?

**Comment by pjh5** [comment] 2018-07-11 17:46
Closing as duplicate of #9181

**Closed by pjh5** 2018-07-11 17:46 UTC
Labels: caffe2
