### ISSUE TITLE
[feature request] torch.pi

### ISSUE THREAD

**Issue by chausies** [pytorch/pytorch#19123] opened 2019-04-10 18:25 UTC
It would be great if you could add `torch.pi`, which should return the constant 3.14159(etc).

Torch is highly desirable as a significantly faster alternative to numpy, implementing most of its functions. But it's missing a very basic thing, which is an easily accessible `pi` constant. It would be great and convenient if this simple thing were added.

As for implementation, literally linking to math.pi would be fine.

Currently, the only way to access `pi` would be to import it from another library like math/numpy, or to do `torch.asin(torch.tensor(1.))`.

**Comment by gchanan** [comment] 2019-04-10 18:49
duplicate of https://github.com/pytorch/pytorch/issues/6510.

**Closed by gchanan** 2019-04-10 18:49 UTC
Labels: duplicate

**Comment by chausies** [comment] 2019-04-10 19:00
I don't think this is a duplicate, nor should it be closed. In #6510, the user was satisfied with `pi` being in the `math` module, and closed it themselves. However, I am not satisfied with that, and argue that `pi` should be included directly in `torch` as a convenience and for completeness's sake. numpy, scipy, and sympy all include it as well, just as some examples.

**Comment by soumith** [comment] 2019-04-10 19:48
I believe the conclusion is the same. If they are constants in `math`, I dont see why they should be replicated in `torch`

**Comment by chausies** [comment] 2019-04-11 17:38
@soumith At the very least, for completeness's sake. And also, by that logic, why should numpy or scipy include `pi`? I think the precedent set by those libraries is a strong reason to do this. `torch` is a desirable fast alternative to them, so including `pi` like them would be a good idea, in my opinion. Finally, for convenience's sake is also an argument.

As for implementation, `torch.pi` could directly just link to `math.pi` (the same as for numpy and scipy).

Can we re-open up this issue to, at the very least, foster an open discussion on this topic, and reach some sort of educated consensus perhaps?

**Comment by soumith** [comment] 2019-04-11 18:22
We generally run on less of a bar than consensus, but I opened a more general feature request (again( in #19172
