### ISSUE TITLE
Port `torch.lt` from the TH code to ATen

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#23254] opened 2019-07-23 18:59 UTC
`lt` is a point-wise math operator so porting it from the TH code to Aten (and TensorIterator) expected to be easy. Such migration will help to clean up the code, simplify dispatch as well as provide immediate 2-3x operator performance gain.

Porting guide: https://github.com/pytorch/pytorch/wiki/TH-to-ATen-porting-guide

Example PR with porting of the adaptive_avg_pool2d: #14714

How to use TensorIterator: https://github.com/pytorch/pytorch/wiki/How-to-use-TensorIterator

**Comment by VitalyFedyunin** [comment] 2019-08-16 19:28
Duplicate of #24593 and #24727

**Closed by VitalyFedyunin** 2019-08-16 19:28 UTC
Labels: module: internals, topic: porting, triaged
