### ISSUE TITLE
_export_onnx(): incompatible function arguments

### ISSUE THREAD

**Issue by MichaelWU0726** [pytorch/pytorch#63141] opened 2021-08-12 08:58 UTC
### Please note that this issue tracker is not a help form and this issue will be closed.

We have a set of [listed resources available on the website](https://pytorch.org/resources). Our primary means of support is our discussion forum:

- [Discussion Forum](https://discuss.pytorch.org/)

when i export yolov5 to onnx format, it showed that: 
```
_export_onnx(): incompatible function arguments. The following argument types are supported:
    1. (self: torch._C.Graph, initializers: Dict[str, at::Tensor], onnx_opset_version: int = 0, dynamic_axes: Dict[str, Dict[int, str]], defer_weight_export: bool = False, operator_export_type: torch._C._onnx.OperatorExportTypes = <OperatorExportTypes.ONNX: 0>, strip_doc_string: bool = True, keep_initializers_as_inputs: bool = True, custom_opsets: Dict[str, int], add_node_names: bool = True, use_external_data_format: bool = False, onnx_file_path: str = '') -> Tuple[bytes, Dict[str, bytes]]
```  
 
I used the following:
```
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
inp = np.random.randn(batch_size, 3, x, y).astype(np.float32)
inp = torch.from_numpy(inp).to(device)
dynamic_ax = {'input_img': {0: 'batch', 2: 'image_height', 3: 'image_wdith'},
                      'out_1': {0, 2, 3},
                      'out_2': {0, 2, 3},
                      'out_3': {0, 2, 3}}
torch.onnx.export(model, inp, onnx_path,
                      input_names=["input_img"], output_names=["out_1", "out_2", "out_3"], verbose=True, opset_version=11,
                      dynamic_axes=dynamic_ax)
```
i hope to get help, thanks!

cc @BowenBao @neginraoof

**Comment by jiafatom** [comment] 2021-08-12 19:15
Closing this one since it is a duplicate of https://github.com/pytorch/pytorch/issues/63142

**Closed by jiafatom** 2021-08-12 19:15 UTC
Labels: module: onnx, triaged
