### ISSUE TITLE
AttributeError: Can't get attribute 'ChatDataset' on <module '__mp_main__' from 'c:\\Users\\hp\\Desktop\\Pytorch\\train.py'> Traceback (most recent call last):

### ISSUE THREAD

**Issue by srbusiness29** [pytorch/pytorch#87016] opened 2022-10-15 16:30 UTC
### 🐛 Describe the bug

import json
from nltk_utlis import tokenize, stem, bag_of_words
import numpy as np

import torch
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

from model import NeuralNet

if __name__ == '__main__':

    with open('intents.json', 'r') as f:
        intents = json.load(f)

    all_words = []
    tags =[]
    xy = []
    for intent in intents['intents']:
        tag = intent['tag']
        tags.append(tag)
        for pattern in intent['patterns']:
            w = tokenize(pattern)
            all_words.extend(w)
            xy.append((w, tag))

    ignore_words = ['?', '!', '.', ',']
    all_words = [stem(w) for w in all_words if w not in ignore_words]
    all_words = sorted(set(all_words))
    tags = sorted(set(tags))

    x_train = []
    y_train = []
    for (pattern_sentence, tag) in xy:
        bag = bag_of_words(pattern_sentence, all_words)
        x_train.append(bag)

        label = tags.index(tag)
        y_train.append(label) 

    x_train = np.array(x_train)
    y_train = np.array(y_train)

    class ChatDataset(Dataset):
        def __init__(self):
            self.n_samples = len(x_train)
            self.x_data = x_train
            self.y_data = y_train

        def __getitem__(self, index):
            return self.x_data[index], self.y_data[index]

        def __len__(self):
            return self.n_samples

    #Hyperparameters
    batch_size = 8
    hidden_size = 8
    output_size = len(tags)
    input_size = len(x_train[0])
    learning_rate = 0.001
    num_epochs = 1000

    dataset = ChatDataset()
    train_loader = DataLoader(dataset=dataset, batch_size=batch_size, shuffle=True, num_workers=2)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
    model = NeuralNet(input_size, hidden_size, output_size).to(device)

    # loss and optimizer 
    criterion = nn.CrossEntropyLoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    # Train the model
    for epoch in range(num_epochs):
        for (words, labels) in train_loader:
            words = words.to(device)
            labels = labels.to(device)
            
            # Forward pass
            outputs = model(words)
            # if y would be one-hot, we must apply
            # labels = torch.max(labels, 1)[1]
            loss = criterion(outputs, labels)
            
            # Backward and optimize
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            
        if (epoch+1) % 100 == 0:
            print (f'Epoch [{epoch+1}/{num_epochs}], Loss: {loss.item():.4f}')

    print(f'final loss: {loss.item():.4f}')

### Versions

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\hp\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
AttributeError: Can't get attribute 'ChatDataset' on <module '__mp_main__' from 'c:\\Users\\hp\\Desktop\\Pytorch\\train.py'>
Traceback (most recent call last):
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1163, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\multiprocessing\queues.py", line 114, in get
    raise Empty
_queue.Empty

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\hp\Desktop\Pytorch\train.py", line 82, in <module>
    for (words, labels) in train_loader:
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 681, in __next__
    data = self._next_data()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1359, in _next_data
    idx, data = self._get_data()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1325, in _get_data
    success, data = self._try_get_data()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\data\dataloader.py", line 1176, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str)) from e
RuntimeError: DataLoader worker (pid(s) 8052) exited unexpectedly

**Everytime I try to run this code I gets the same error even tough the guy who taught me this code in his pc he is not getting any error can anyone please help me? Thank you.** 

cc @SsnL @VitalyFedyunin @ejguan @NivekT

**Comment by ejguan** [comment] 2022-10-18 13:52
Please move you class definition out of 'if __name__ == "__main__".

**Comment by srbusiness29** [comment] 2022-10-18 16:07
> Please move you class definition out of 'if **name** == "**main**".

Even after removing if **name** == "**main**". it is receiving the same error

**Comment by ejguan** [comment] 2022-10-18 16:11
I mean
```py
class ChatDataset:
    ...

if __name__ == "__main__":
    dataset = ChatDataset()
    ...

```
Please take a reference from https://pytorch.org/docs/stable/data.html#platform-specific-behaviors

**Comment by srbusiness29** [comment] 2022-10-18 17:42
> I mean
> 
> ```python
> class ChatDataset:
>     ...
> 
> if __name__ == "__main__":
>     dataset = ChatDataset()
>     ...
> ```
> 
> Please take a reference from https://pytorch.org/docs/stable/data.html#platform-specific-behaviors

Still not working

**Comment by srbusiness29** [comment] 2022-10-18 17:44
> I mean
> 
> ```python
> class ChatDataset:
>     ...
> 
> if __name__ == "__main__":
>     dataset = ChatDataset()
>     ...
> ```
> 
> Please take a reference from https://pytorch.org/docs/stable/data.html#platform-specific-behaviors

Thank you that thing worked but now a new error has arisen.

**ValueError: optimizer got an empty parameter list**

can you please help me out with this

**Comment by ejguan** [comment] 2022-10-18 18:06
> Thank you that thing worked but now a new error has arisen.
> 
> **ValueError: optimizer got an empty parameter list**
> 
> can you please help me out with this

Based on this Error, I would guess it comes from your model `NeuralNet` where `parameter` are not properly attached.
Please check https://pytorch.org/tutorials/beginner/examples_nn/polynomial_module.html#pytorch-custom-nn-modules

If the Error still persists, please share a minimum reproducible script to us.

I am closing this Issue since it's not data-related.

**Closed by ejguan** 2022-10-18 18:06 UTC
Labels: module: dataloader, triaged
