### ISSUE TITLE
Unexpected behavior while computing grad((W * (x - x.mean())).sum(), W) together with the "unsqueeze" operation.

### ISSUE THREAD

**Issue by vacancy** [pytorch/pytorch#53488] opened 2021-03-08 03:08 UTC
## 🐛 Bug

There are unexpected behavior while computing grad((W * (x - x.mean())).sum(), W) together with the "unsqueeze" operation.

## To Reproduce

```
import torch


def testCase3a():
    CHANNELS = 18
    EPS = 1e-5

    input = torch.rand(CHANNELS, 16 * 24 * 12)
    input[:8] -= 0.5
    input[8:] += 0.5

    x = input
    assert x.size() == (CHANNELS, 16 * 24 * 12)
    numel = x.size(1)
    assert numel == 16 * 24 * 12

    x_s = x.sum(dim=1)
    x_mean = x_s / numel
    x = (input - x_mean.unsqueeze(-1))

    W = torch.ones(CHANNELS, requires_grad=True)
    b = torch.zeros(CHANNELS, requires_grad=True)

    output = x * W.unsqueeze(-1) + b.unsqueeze(-1)
    loss = output.sum()
    loss.backward()
    my_grad = x.sum(-1)

    assert torch.allclose(W.grad, my_grad)


def testCase3b():
    CHANNELS = 18
    EPS = 1e-5

    input = torch.rand(CHANNELS, 16, 24, 12)
    input[:8] -= 0.5
    input[8:] += 0.5

    x = input
    assert x.size() == (CHANNELS, 16, 24, 12)
    x = x.reshape(CHANNELS, -1)
    assert x.size() == (CHANNELS, 16 * 24 * 12)
    numel = x.size(1)
    assert numel == 16 * 24 * 12

    x_s = x.sum(dim=1)
    x_mean = x_s / numel
    x = (input - x_mean.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1))

    W = torch.ones(CHANNELS, requires_grad=True)
    b = torch.zeros(CHANNELS, requires_grad=True)

    output = x * W.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1) + b.unsqueeze(-1).unsqueeze(-1).unsqueeze(-1)
    loss = output.sum()
    loss.backward()
    my_grad = x.sum(-1).sum(-1).sum(-1)

    assert torch.allclose(W.grad, my_grad)


if __name__ == '__main__':
    testCase3a()
    testCase3b()
```

## Expected behavior

The behavior of testcase3a and testcase3b should be the same. However, the last tensor close assertion fails on my CPU.

## Environment

PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 16.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.5.1

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 11.0.221
GPU models and configuration:
GPU 0: TITAN Xp
GPU 1: TITAN Xp
GPU 2: TITAN Xp
GPU 3: TITAN Xp

Nvidia driver version: 450.51.06
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.4.0
[pip3] torchvision==0.5.0
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.1.243             h6bb024c_0
[conda] mkl                       2020.2                      256
[conda] mkl-service               2.3.0            py38he904b0f_0
[conda] mkl_fft                   1.2.0            py38h23d657b_0
[conda] mkl_random                1.1.1            py38h0573a6f_0
[conda] numpy                     1.19.2           py38h54aff64_0
[conda] numpy-base                1.19.2           py38hfa32c7d_0
[conda] pytorch                   1.4.0           py3.8_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.5.0                py38_cu101    pytorch

## Additional context

Running this script on torch1.7 also fails.

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer

**Comment by ngimel** [comment] 2021-03-15 17:07
Note that your expected value of x.sum(-1).sum(-1).sum(-1) is 0. You are changing the order of summation by summing x separately across dimensions. Depending on the order of summation, result would be slightly different (even though absolute values would still be very small compared to values in `x`, and `allclose` check would fail). I'd say this is expected behavior. 
If you change `my_grad` computation to `x.sum((1,2,3))`, assert passes, because it is the same computation as done in the autograd.

**Comment by ngimel** [comment] 2021-03-15 17:26
Closing, if you have additional questions please use discuss.pytorch.org

**Closed by ngimel** 2021-03-15 17:26 UTC
Labels: module: autograd, module: numerical-stability, triage review
