### ISSUE TITLE
cannot import name 'ngrams_iterator'

### ISSUE THREAD

**Issue by Z588588000** [pytorch/pytorch#49525] opened 2020-12-17 02:02 UTC
## To Reproduce

from torchtext.data.metrics import bleu_score

ImportError: cannot import name 'ngrams_iterator'

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by skyline75489** [comment] 2020-12-17 08:50
I think this should be reported in https://github.com/pytorch/text .

By the way you may want to fill the issue template and provide as much as information as possible, otherwise no one can simply reproduce your problem.

**Comment by mrshenli** [comment] 2020-12-18 02:30
+1 to @skyline75489's comment

Hey @Z588588000, could you please move this issue to torchtext repo? 

cc author of torchtext @zhangguanheng66 

I am closing this issue for now. If it turns out requiring changes in PyTorch, please feel free to open another issue here.

**Closed by mrshenli** 2020-12-18 02:30 UTC
