### ISSUE TITLE
[FX] `is None` condition check does not error out in symbolic tracing, and can produce silently incorrect results.

### ISSUE THREAD

**Issue by jerryzh168** [pytorch/pytorch#50178] opened 2021-01-07 00:41 UTC
```python
import torch
from torch.fx import symbolic_trace

class M(torch.nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, x, y):
        if y is None:
            # this path is not captured since when we trace y is a Proxy and it is not None
            y = x
        return x + y
    
m = M()
m = symbolic_trace(m)

x = torch.rand(1)
# this works
m(x, x)
# this does not work
m(x, None)
```
We get:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-7d8b689ec0f5> in <module>
     19 m(x, x)
     20 # this does not work
---> 21 m(x, None)
     22 

/mnt/xarfuse/uid-127034/bfe90f9e-seed-nspid4026531836-ns-4026531840/torch/fx/graph_module.py in wrapped_call(self, *args, **kwargs)
    300             try:
    301                 sys.excepthook = print_full_traceback
--> 302                 return cls_call(self, *args, **kwargs)
    303             finally:
    304                 sys.excepthook = old_excepthook

/mnt/xarfuse/uid-127034/bfe90f9e-seed-nspid4026531836-ns-4026531840/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    878             result = self._slow_forward(*input, **kwargs)
    879         else:
--> 880             result = self.forward(*input, **kwargs)
    881         for hook in itertools.chain(
    882                 _global_forward_hooks.values(),

<eval_with_key_5> in forward(self, x, y)
      1 
      2 def forward(self, x, y):
----> 3     add_1 = x + y;  x = y = None
      4     return add_1
      5 

TypeError: unsupported operand type(s) for +: 'Tensor' and 'NoneType'
```

Expected:

I think it would be better for this case to error out so that user will be aware that the model is not compatible with symbolic tracing.

**Comment by jamesr66a** [comment] 2021-08-19 16:27
Duplicate of https://github.com/pytorch/pytorch/issues/45685

**Closed by jamesr66a** 2021-08-19 16:27 UTC
Labels: oncall: fx
