### ISSUE TITLE
`torch.load()` fails under `enable_python_mode()`

### ISSUE THREAD

**Issue by cbalioglu** [pytorch/pytorch#66444] opened 2021-10-11 20:18 UTC
## 🐛 Bug

Calling `torch.load()` in the scope of `enable_python_mode()` causes a `RuntimeError`.

## To Reproduce

The following script when run from the master HEAD (#acb0157 as of this issue) within the environment listed below:

```
from contextlib import contextmanager
import torch

from torch._C import _DisableTorchDispatch
from torch.utils._python_dispatch import enable_python_mode


n = torch.ones([10, 10])  

torch.save(n, "python-mode")


@contextmanager
def no_dispatch():
    guard = _DisableTorchDispatch()
    try:
        yield
    finally:
        del guard


class TestTensor(torch.Tensor):
    @classmethod
    def __torch_dispatch__(cls, func, types, args=(), kwargs=None):
        with no_dispatch():
            return func(*args, **kwargs)


with enable_python_mode(TestTensor):
    m = torch.load("python-mode")
```

fails with:

```
Traceback (most recent call last):
  File "/data/home/balioglu/py-mode-test.py", line 30, in <module>
    m = torch.load("python-mode")
  File "/fsx/users/balioglu/repos/pytorch/torch/serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "/fsx/users/balioglu/repos/pytorch/torch/serialization.py", line 882, in _load
    result = unpickler.load()
  File "/fsx/users/balioglu/repos/pytorch/torch/_utils.py", line 137, in _rebuild_tensor_v2
    tensor = _rebuild_tensor(storage, storage_offset, size, stride)
  File "/fsx/users/balioglu/repos/pytorch/torch/_utils.py", line 133, in _rebuild_tensor
    return t.set_(storage, storage_offset, size, stride)
RuntimeError: Missing cases in 'toPyObject'! Can't convert Storage to a Python object
```

## Expected behavior

The `torch.load()` function should be able to load the saved tensors from a specified file regardless whether it is in the scope of `enable_python_mode()` or not.

## Environment

PyTorch version: 1.11.0a0+git8b4f50d
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 10.0.1 (https://github.com/llvm/llvm-project.git ef32c611aa214dea855364efd7ba451ec5ec3f74)
CMake version: version 3.21.0
Libc version: glibc-2.25

Python version: 3.6.14 (tags/v3.6.14-dirty:9a0099d, Jul 28 2021, 22:14:36)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1051-aws-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: 11.1.105
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/local/cuda-10.1/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-10.2/targets/x86_64-linux/lib/libcudnn.so.7.6.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.0/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_adv_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_cnn_train.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_infer.so.8.0.5
/usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.19.0
[pip3] pytorch-pretrained-bert==0.6.2
[pip3] pytorch-sphinx-theme==0.0.24
[pip3] torch==1.11.0a0+git8b4f50d
[pip3] torchtext==0.8.0
[conda] blas                      1.0                         mkl  
[conda] magma-cuda110             2.5.2                         1    pytorch
[conda] mkl                       2021.2.0           h06a4308_296  
[conda] mkl-include               2021.2.0           h06a4308_296  
[conda] mkl-service               2.3.0            py38h27cfd23_1  
[conda] mkl_fft                   1.3.0            py38h42c9631_2  
[conda] mkl_random                1.2.1            py38ha9443f7_2  
[conda] numpy                     1.20.2           py38h2d18471_0  
[conda] numpy-base                1.20.2           py38hfae3a4d_0

cc @mruberry @albanD

**Comment by zou3519** [comment] 2021-10-12 19:48
Not sure if Python Mode should have its own label, labeling as torch_dispatch for now

**Comment by tchaton** [comment] 2021-11-17 12:16
Hey @zou3519 @cbalioglu,

It seems TorchMetrics used within the context `init_meta_context` and `init_meta` recently merged with PyTorch Lightning fails due to a deepcopy happening on raw tensors within the `__init__` method of the Metric.

Here is a reproducible script built on top of https://github.com/pytorch/pytorch/pull/66317.

```
import torch
from copy import deepcopy

class TestModule(torch.nn.Module):
    def __init__(self):
        super().__init__()
        # this works
        default = torch.nn.parameter.Parameter(torch.tensor(1.0))
        deepcopy(default)

        # this doesn't
        default = torch.tensor(1.0)
        deepcopy(default)

torch.distributed.nn.utils.init_meta(TestModule)

"""
  deepcopy(default)
  File "/Users/thomas/.pyenv/versions/3.8.5/lib/python3.8/copy.py", line 153, in deepcopy
    y = copier(memo)
  File "/Users/thomas/Documents/GitHub/pytorch-lightning/.venv/lib/python3.8/site-packages/torch/_tensor.py", line 120, in __deepcopy__
    new_tensor.set_(new_storage, self.storage_offset(), self.size(), self.stride())
RuntimeError: Missing cases in 'toPyObject'! Can't convert Storage to a Python object
"""
```

We are totally aware this feature is highly experimental and bugs are to be expected, so no rush :) 
Keep us updated if you find any solution.

We have a working example with xformer there: https://github.com/facebookresearch/xformers/pull/110

Best,
T.C

**Comment by zou3519** [comment] 2021-11-17 14:29
Thanks for the bug report, @tchaton. If you see more please feel free to continue to surface them

**Closed** 2022-01-20 02:17 UTC
Labels: module: serialization, triaged, module: __torch_dispatch__
