### ISSUE TITLE
Segmentation fault on torch.true_divide when two inputs are float16

### ISSUE THREAD

**Issue by drewshark** [pytorch/pytorch#115068] opened 2023-12-04 09:26 UTC
### 🐛 Describe the bug

Here is the code to reproduce:

```
import torch
import numpy as np
x = torch.tensor(np.random.rand(), dtype=torch.float16)
y = torch.tensor(np.random.rand(0), dtype=torch.float16)
torch.true_divide(x, y)
```

I think this issue may be related to my previous issue: https://github.com/pytorch/pytorch/issues/115066

### Versions

[pip3] numpy==1.23.5
[pip3] torch==2.1.0
[pip3] torchaudio==2.1.0
[pip3] torchvision==0.16.0
[pip3] triton==2.0.0
[conda] blas 1.0 mkl
[conda] cudatoolkit 11.3.1 h2bc3f7f_2
[conda] ffmpeg 4.3 hf484d3e_0 pytorch
[conda] libjpeg-turbo 2.0.0 h9bf148f_0 pytorch
[conda] mkl 2021.4.0 h06a4308_640
[conda] mkl-service 2.4.0 py39h7f8727e_0
[conda] mkl_fft 1.3.1 py39hd3c417c_0
[conda] mkl_random 1.2.2 py39h51133e4_0
[conda] numpy 1.23.5 py39h14f4228_0
[conda] numpy-base 1.23.5 py39h31eccc5_0
[conda] pytorch 2.1.0 py3.9_cpu_0 pytorch
[conda] pytorch-mutex 1.0 cpu pytorch
[conda] torch 2.0.0 pypi_0 pypi
[conda] torchaudio 2.1.0 py39_cpu pytorch
[conda] torchvision 0.16.0 py39_cpu pytorch
[conda] triton 2.0.0 pypi_0 pypi

**Comment by tringwald** [comment] 2023-12-04 20:15
Most likely a duplicate of https://github.com/pytorch/pytorch/issues/113037. Will probably be fixed when https://github.com/pytorch/pytorch/pull/113210 is merged.

**Comment by malfet** [comment] 2023-12-04 22:32
Indeed a duplicate, which reminds me I need to restart looking into that PR

**Comment by malfet** [comment] 2023-12-04 22:33
Duplicate of https://github.com/pytorch/pytorch/issues/113037

**Closed by malfet** 2023-12-04 22:33 UTC
Labels: module: crash
