### ISSUE TITLE
Bug in masked_fill_ for non contiguous tensors

### ISSUE THREAD

**Issue by neerajprad** [pytorch/pytorch#12230] opened 2018-10-01 19:27 UTC
## 🐛 Bug

The in-place `masked_fill_` seems to give incorrect results on PyTorch master for non-contiguous tensors.

## To Reproduce

```python
In [1]: import torch

In [2]: torch.__version__
Out[2]: '1.0.0a0+572132f'

In [3]: mask = torch.tensor([[[1, 0]], [[0, 1]]], dtype=torch.uint8)

In [4]: mask.shape
Out[4]: torch.Size([2, 1, 2])

In [5]: x = torch.randn(2, 2)

In [6]: x, mask = torch.broadcast_tensors(x, mask)

In [7]: mask.shape
Out[7]: torch.Size([2, 2, 2])

In [8]: x.is_contiguous()
Out[8]: False

In [9]: x.masked_fill(mask, 0)  # This should be the correct behavior
Out[9]: 
tensor([[[ 0.0000,  0.9482],
         [ 0.0000,  0.0719]],

        [[ 0.6267,  0.0000],
         [-0.6296,  0.0000]]])

In [10]: x.masked_fill_(mask, 0)   # Incorrect result
Out[10]: 
tensor([[[0.0000, 0.9482],
         [0.0000, 0.0719]],

        [[0.0000, 0.9482],
         [0.0000, 0.0719]]])
```

We can retrieve the correct behavior by calling `.contiguous()` on the expanded tensor before doing a `masked_fill_`:

```python
In [11]: y = torch.randn(2, 2)

In [12]: y, mask = torch.broadcast_tensors(y, mask)

In [13]: y = y.contiguous()

In [14]: y.masked_fill_(mask, 0)
Out[14]: 
tensor([[[ 0.0000,  0.0579],
         [ 0.0000,  0.4561]],

        [[-0.0155,  0.0000],
         [-1.7522,  0.0000]]])
```

## Environment

```
  $ python collect_env.py 
Collecting environment information...
PyTorch version: 1.0.0a0+572132f
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Ubuntu 16.04.4 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
CMake version: version 3.12.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: 
GPU 0: GeForce GTX 1080
GPU 1: GeForce GTX 1080

Nvidia driver version: 390.30
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.1.3
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] numpy (1.15.1)
[pip] torch (1.0.0a0+572132f)
[pip] torchfile (0.1.0)
[pip] torchvision (0.2.1)
[conda] magma-cuda91              2.3.0                         1    pytorch
[conda] torch                     1.0.0a0+572132f           <pip>
[conda] torchfile                 0.1.0                     <pip>
[conda] torchvision               0.2.1                     <pip>
```

**Comment by neerajprad** [comment] 2018-10-01 19:28
cc. @fritzo, @zou3519, @apaszke

**Comment by fmassa** [comment] 2018-10-02 05:41
I'm not saying this is the desired behaviour, but it also boils down to performing in place operations on expanded tensors. I believe the same happens with something like
```python
a = torch.ones(1).expand(3)
a +=1
```

**Comment by neerajprad** [comment] 2018-10-02 14:35
@fmassa : I mistakenly thought that this was some regression in PyTorch master, because our unit test only fails on master; but I verified that there has been no change in behavior. The reason why our test is failing now is because `expanded_tensor * scalar` which previously copied the data into a new contiguous tensor, now copies it into a non contiguous tensor on linux. See below. 

```python
In [1]: import torch

In [2]: t = torch.randn(2, 2)

In [3]: t = t.expand([2, 2, 2])

In [4]: t.is_contiguous()
Out[4]: False

In [5]: u = t * 2.0

In [6]: u.is_contiguous()  # = True on release 
Out[6]: False
```

Note that this in itself doesn't violate any expectations, other than the non intuitive results on expanded tensor operations that might follow. To get around this we are calling `.contiguous` after the scalar multiplication. Please feel free to close this issue (or follow up), as you might see fit!

**Comment by fritzo** [comment] 2018-10-02 15:03
> `expanded_tensor * scalar` now copies it into a non contiguous tensor on linux

Good to know! We're relying on it triggering a `.contiguous()` in a number of places in Pyro.

**Comment by apaszke** [comment] 2018-10-03 16:10
That's actually very surprising. @colesbury is it a `TensorIterator` thing?

**Comment by fmassa** [comment] 2018-10-03 18:32
@apaszke yes, now TensorIterator doesn't always automatically converts tensor to contiguous after operations. FWIW this is the behaviour of numpy

**Comment by apaszke** [comment] 2018-10-03 21:12
I see. We should probably harden our in-place ops to better check at least for the common case of an expanded tensor and tell people that they will get incorrect results. Many programs that previously were perfectly safe will not give bad results, because people (or really our in-place ops that people use) assumed things will be non-overlapping in memory.

**Comment by fmassa** [comment] 2018-10-03 23:40
That's probably a good idea, we have been seeing misleading results from expanded tensors for a while already. But ideally, we would implement the memory overlap discussed in https://github.com/pytorch/pytorch/issues/8212, but that's more longer term goal.

**Comment by neerajprad** [comment] 2018-10-04 01:56
> We should probably harden our in-place ops to better check at least for the common case of an expanded tensor and tell people that they will get incorrect results.

+1 on throwing an exception here if in-place ops expect contiguous tensors. The bugs can be hard to track down otherwise as you get non deterministic end results, and different behavior on different platforms.

**Comment by colesbury** [comment] 2018-10-04 22:15
@apaszke, no this isn't related to TensorIterator. There's a few misunderstandings here, because of confusion between non-contiguous tensors (i.e. not C-contiguous) and the subset of tensors with overlapping elements.

1) It's not safe to do in-place operations on tensors with overlapping elements. This has always been the case, but we'd like to detect it in the future.

2) The results of arithmetic operations may not be in C-contiguous order if the inputs are not C-contiguous, but they are never overlapped.

3) That means it's safe to do in-place operations on result of arithmetic.

**Comment by fmassa** [comment] 2018-10-04 23:33
@colesbury this seems to be a regression that was (somewhat) recently introduced, your snippet works for me on `'0.5.0a0+a5d7abe'`, but gives different results with a PyTorch compiled today

**Comment by fmassa** [comment] 2018-10-04 23:37
The regression was probably introduced in https://github.com/pytorch/pytorch/pull/11359, as my committed version that works predates that PR

**Comment by soumith** [comment] 2018-10-05 05:00
cc: @mingfeima it looks like #11359 introduced a bug, see test case from @colesbury above

**Comment by fmassa** [comment] 2018-10-16 16:34
Fixed via https://github.com/pytorch/pytorch/pull/12594

**Closed by fmassa** 2018-10-16 16:34 UTC
Labels: high priority
