### ISSUE TITLE
PyTorch installation downgrades python 3.7 to python 3.5.6

### ISSUE THREAD

**Issue by sebderhy** [pytorch/pytorch#12929] opened 2018-10-22 13:32 UTC
## 🐛 Bug

My basic Conda environment is python 3.7, but creating a new environment and installing in it Pytorch ('conda install pytorch-nightly cuda92 -c pytorch'), python --version gives me 'Python 3.5.6 :: Anaconda, Inc.'.

This bug seems very similar to https://github.com/pytorch/pytorch/issues/9967, although the issue there is supposed to be closed, so I also left a comment there.

## To Reproduce

1. Install Anaconda with python 3.7 and Cuda 9.2 on Ubuntu 16.04
2. Create a new environment
3. Check that python version is still 3.7
4. Install Pytorch with 'conda install pytorch-nightly cuda92 -c pytorch'
5. Check the python version now. In my case, it is now 3.5.6

## Expected behavior

Pytorch is said to be working with python 3.7 in the download page, so there's no reason it would downgrade it.

## Environment

```
PyTorch version: 1.0.0.dev20181022
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.3 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.5
Is CUDA available: Yes
CUDA runtime version: 9.2.148
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 396.37
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy (1.15.2)
[pip] torch (1.0.0.dev20181022)
[conda] cuda92                    1.0                           0    pytorch
[conda] pytorch-nightly           1.0.0.dev20181022 py3.5_cuda9.0.176_cudnn7.1.2_0    pytorch

```

## Additional context

It's the first time I write an issue on Github, so I apologize in advance if it is not very clear or something ;)...

Thanks in advance for your help !!
Sebastien

**Comment by soumith** [comment] 2018-10-22 14:29
@sebderhy your root conda environment must've been Python 3.5. Subsequently, did you upgrade to Python 3.7 in a particular non-root conda environment? That's what I think might be the root cause.

> Install Anaconda with python 3.7 and Cuda 9.2 on Ubuntu 16.04
> Create a new environment
> Check that python version is still 3.7

If you want to install a conda package in a new particular environment, you have to do:

`conda install -n [environment-name] [package-name]`

**Comment by soumith** [comment] 2018-10-22 14:35
duplicate of https://github.com/pytorch/pytorch/issues/12929

**Comment by sebderhy** [comment] 2018-10-22 15:00
> @sebderhy your root conda environment must've been Python 3.5. Subsequently, did you upgrade to Python 3.7 in a particular non-root conda environment? That's what I think might be the root cause.
> 
> > Install Anaconda with python 3.7 and Cuda 9.2 on Ubuntu 16.04
> > Create a new environment
> > Check that python version is still 3.7
> 
> If you want to install a conda package in a new particular environment, you have to do:
> 
> `conda install -n [environment-name] [package-name]`

Hi Soumith.

My root Anaconda environment is python 3.7 (see screenshot below). It was also 3.7 on the environment I created to install pytorch there. However, after installation, it got downgraded to 3.5.6.

![image](https://user-images.githubusercontent.com/13600027/47299936-040e1a80-d624-11e8-878c-eeb63b4a37d7.png)

**Comment by soumith** [comment] 2018-10-24 05:01
just fyi, @pjh5 figured out the issue. Fixes are incoming.

**Comment by sebderhy** [comment] 2018-10-24 09:19
Great looking forward to it, thanks !

**Comment by pjh5** [comment] 2018-10-24 20:28
Actually, I reproed the issue on our own infra, but I suspect that it is actually an issue on condas side. I'll post here once I diagnose more

**Closed** 2018-10-30 03:32 UTC
