### ISSUE TITLE
DistributedDataParallel do not work with custom function in model

### ISSUE THREAD

**Issue by hadaev8** [pytorch/pytorch#30657] opened 2019-12-03 11:06 UTC
https://colab.research.google.com/drive/104LtQ1zIioIOMQEPgVve77m5Rd4Gm0wU
Here is code, it runs fine on single gpu colab instance.
But if i run same code on ml.p3.16xlarge amazon sagemaker, i get error like this

```
File “/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py”, line 60, in worker
output = module(*input, **kwargs)
File “/home/ec2-user/anaconda3/envs/pytorch_p36/lib/python3.6/site-packages/torch/nn/modules/module.py”, line 547, in call
result = self.forward(*input, **kwargs)
File “/home/ec2-user/SageMaker/tacotron2/model/model.py”, line 480, in forward
output_lengths)
File “/home/ec2-user/SageMaker/tacotron2/model/model.py”, line 452, in parse_output
outputs[0].data.masked_fill(mask, 0.0)
RuntimeError: The expanded size of the tensor (1079) must match the existing size (836) at non-singleton dimension 2. Target sizes: [4, 80, 1079]. Tensor sizes: [4, 80, 836]
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528

**Comment by zhaojuanmao** [comment] 2019-12-04 20:59
@hadaev8 you imported DistributedDataParallel, but it is never used in your code, you are using torch.nn.DataParallel(model), did you actually want to use 

torch.nn.parallel.DistributedDataParallel(
        model,
        device_ids=[gpu_index],
        output_device=gpu_index,
        broadcast_buffers=False,
        check_reduction=True
    )?

Also what does custom function in model mean?

**Comment by hadaev8** [comment] 2019-12-04 21:07
@zhaojuanmao 
I tried both DistributedDataParallel and DataParallel.
With both, I got same error about the wrong dimension.

Traceback lead to this part of model
https://github.com/NVIDIA/tacotron2/blob/master/model.py#L473
If I remove parce_batch from model, traceback lead to parse_output function

**Comment by zhaojuanmao** [comment] 2019-12-04 22:34
that sounds not related to ddp package itself, parse_output is user defined codes, would you like to debug further and narrow down it is ddp bug with reproducible small sample codes?

**Comment by pietern** [comment] 2019-12-05 19:33
@zou3519 Removing the distributed label here.

This doesn't look like an issue with `DistributedDataParallel` but rather a mismatch between the model output (in `outputs[0].data`) and the size of the mask that @hadaev8 is using.

The cause of the issue may be _related_ to distributed data parallelism, in that you only get shape mismatches if you're training in a distributed setting (e.g. because of the data loader or sampler), but that's not _caused_ by distributed data parallelism.

**Comment by hadaev8** [comment] 2019-12-06 12:44
@zhaojuanmao @pietern 
Okay, I got it.

this is shapes of data and mask print(outputs[0].shape, mask.shape, output_lengths):
```
torch.Size([8, 80, 900]) torch.Size([8, 80, 800]) tensor([800, 800, 800, 800, 800, 800, 700, 700], device='cuda:1')
torch.Size([8, 80, 900]) torch.Size([8, 80, 700]) tensor([700, 700, 700, 700, 700, 600, 600, 600], device='cuda:2')
torch.Size([8, 80, 900]) torch.Size([8, 80, 600]) tensor([600, 600, 600, 600, 500, 500, 500, 500], device='cuda:3')
torch.Size([8, 80, 900]) torch.Size([8, 80, 500]) tensor([500, 500, 400, 400, 400, 400, 400, 400], device='cuda:4')
torch.Size([8, 80, 900]) torch.Size([8, 80, 900]) tensor([900, 900, 900, 900, 900, 900, 900, 800], device='cuda:0')
torch.Size([8, 80, 900]) torch.Size([8, 80, 400]) tensor([400, 400, 400, 400, 400, 400, 300, 300], device='cuda:5')
torch.Size([8, 80, 900]) torch.Size([8, 80, 300]) tensor([300, 300, 300, 300, 300, 300, 300, 200], device='cuda:6')
torch.Size([8, 80, 900]) torch.Size([8, 80, 200]) tensor([200, 200, 200, 200, 200, 200, 200, 200], device='cuda:7')
```

The whole batch have zero padded to max len 900, while minibatch per gpu have different maxlen and masking returns this value.

What should be best way to solve it?

**Comment by gchanan** [comment] 2019-12-06 20:54
@hadaev8 please kindly ask questions on the discussion forums: https://discuss.pytorch.org/.  Since this doesn't appear to be a PyTorch bug, I'll close this.

**Closed by gchanan** 2019-12-06 20:54 UTC
