### ISSUE TITLE
GPU memory limit in PyTorch

### ISSUE THREAD

**Issue by Vijayvithal** [pytorch/pytorch#50938] opened 2021-01-22 10:34 UTC
Currently we can able to limit the GPU's memory usage using TensorFlow.

Same how to limit the GPU's memory usage with PyTorch and fastai.

For example, my GPU may have 6Gb available, but I'd like to assign 4Gb max to a particular process

**Comment by kshitij12345** [comment] 2021-01-22 12:34
Probably a duplicate of https://github.com/pytorch/pytorch/issues/18626

**Comment by zou3519** [comment] 2021-01-22 16:33
Closing because of duplicate. @Vijayvithal please voice your support of #18626 in the thread

**Closed by zou3519** 2021-01-22 16:33 UTC
