### ISSUE TITLE
Segmentation when running torch.linalg.ldl_solve on torch 1.13.1

### ISSUE THREAD

**Issue by nimashiri** [pytorch/pytorch#91611] opened 2023-01-03 07:36 UTC
### 🐛 Describe the bug

This API has very weird behavior, when I run it, it results in segmentation fault, then I run it for the second time, the segfault disappears. You can see the segfault by running multiple times. 

```
import torch
import numpy as np
arg_1_tensor = torch.rand([5, 5], dtype=torch.complex64)
arg_1 = arg_1_tensor.clone()
arg_2_tensor = torch.randint(-1,512,[5], dtype=torch.int16)
arg_2 = arg_2_tensor.clone()
arg_3_tensor = torch.rand([5, 1], dtype=torch.complex64)
arg_3 = arg_3_tensor.clone()
arg_4 = True
try:
  res = torch.linalg.ldl_solve(arg_1,arg_2,arg_3,hermitian=arg_4,)
except Exception as e:
  print("Error:"+str(e))
```

I get the following log messages:
```
corrupted size vs. prev_size
Aborted
```
and
```
Segmentation fault
```

### Versions

PyTorch version: 1.13.1
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Ubuntu 22.04.1 LTS (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-56-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] torch==1.13.1
[pip3] torchaudio==0.13.1
[pip3] torchvision==0.14.1
[conda] blas                      1.0                         mkl  
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640  
[conda] mkl-service               2.4.0            py39h7f8727e_0  
[conda] mkl_fft                   1.3.1            py39hd3c417c_0  
[conda] mkl_random                1.2.2            py39h51133e4_0  
[conda] numpy                     1.23.5           py39h14f4228_0  
[conda] numpy-base                1.23.5           py39h31eccc5_0  
[conda] pytorch                   1.13.1          py3.9_cuda11.6_cudnn8.3.2_0    pytorch
[conda] pytorch-cuda              11.6                 h867d48c_1    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.13.1               py39_cu116    pytorch
[conda] torchvision               0.14.1               py39_cu116    pytorch

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @IvanYashchuk @xwang233 @Lezcano @ezyang @gchanan @zou3519

**Comment by zou3519** [comment] 2023-01-04 15:33
hi-pri for crash. I can reproduce this on master

**Comment by malfet** [comment] 2023-01-09 18:14
We should check if similar would crash (or do a input values sanitization) in numpy/scipy

**Comment by lezcano** [comment] 2023-01-09 19:26
this issue is a dupe from another one that was already triaged I believe

**Comment by lezcano** [comment] 2023-01-09 23:52
Closing as dupe (or close cousin) of https://github.com/pytorch/pytorch/issues/91590. Let's track this issue there.

**Closed by lezcano** 2023-01-09 23:52 UTC
Labels: module: crash, triaged, module: linear algebra, module: edge cases
