### ISSUE TITLE
c++   error:"std":ambiguous symbol  it is in visual studio 2017.

### ISSUE THREAD

**Issue by sikuntiannan** [pytorch/pytorch#18607] opened 2019-03-29 04:33 UTC
Using the example in  https://pytorch.org/cppdocs/installing.html  page, developed in IDE, the error message is "std": ambiguous symbol.
![image](https://user-images.githubusercontent.com/26763453/55209599-7233ba80-521e-11e9-97b8-eae4e78f0a62.png)
There's a lot of information about this type of error.
You guys meet again? how do you solve this?
environment:windows10 ,visual studio 2017,cuda10,c++.

**Comment by peterjc123** [comment] 2019-03-29 05:36
Do something like this: https://github.com/pytorch/pytorch/pull/17863.

**Comment by sikuntiannan** [comment] 2019-03-29 09:30
thanks

**Comment by peterjc123** [comment] 2019-03-29 09:57
Would you please make a PR on this?

**Comment by sikuntiannan** [comment] 2019-03-29 10:16
I have no experience using GitHub, and I don't know what you mean by PR.

**Comment by peterjc123** [comment] 2019-03-29 10:18
Okay, just post your errors here. I'll do it for you.

**Comment by sikuntiannan** [comment] 2019-03-29 10:25
I have another question. Here is an operation
![image](https://user-images.githubusercontent.com/26763453/55226409-e76bb380-524f-11e9-8d12-9622408b2d33.png)
![image](https://user-images.githubusercontent.com/26763453/55226436-f5213900-524f-11e9-9cbf-3c961e910643.png)

 called cast-to-function that is illegal.

**Comment by sikuntiannan** [comment] 2019-03-29 10:34
![image](https://user-images.githubusercontent.com/26763453/55226881-0ae32e00-5251-11e9-8c6d-7bb4b17d9e35.png)

**Comment by peterjc123** [comment] 2019-03-29 12:57
I tried the example and could not reproduce your issue. Would you tell me which exact version of VS you are using? 
```
Open `x86_x64 Cross Tools Command Prompt for VS 2017` 
Do `where cl`
```
If the toolkit's lower than 14.11 (or VS version lower than 15.3.5), my recommendation is to update your VS.

**Comment by sikuntiannan** [comment] 2019-03-29 14:21
I looked at this code, it should be compiler failure,. Visual studio sometimes encounter this problem. Sometimes restarting or rebuilding projects can be solved. Syntactically, it thinks RNNFunctionSignatuie is an object. So report a mistake, think that the object can not be forced to convert into a function. I take the code out of the framework and compile it through.

If there is any mistake, I will reply to you again.

我看了这个代码，应该是编译器故障了。visual studio 有时会遇到这种问题。有时重启或者重建项目就能解决。
在语法上它认为RNNFunctionSignatuie是一个对象。所以报错，认为对象不能强制转化为函数。我自己将代码从框架中拿出来，编译时就可以的通过。

如果还有错误，我会再次回复你。

**Comment by sikuntiannan** [comment] 2019-03-29 14:22
I'll reinstall visual studio.


我重装visual studio试试

**Comment by peterjc123** [comment] 2019-03-29 14:26
It seems the problem is not on our side. I'm going to close this issue first. Please feel free to reopen it when you have trouble.

**Closed by peterjc123** 2019-03-29 14:26 UTC
Labels: windows

**Comment by sikuntiannan** [comment] 2019-03-30 02:15
![image](https://user-ima
ges.githubusercontent.com/26763453/55269973-73272380-52d4-11e9-818d-7337e75ba5d6.png)

This error is still being reloaded. The compiler recognizes the RNNFunctionSignature as an object. How do you solve this?

**Comment by sikuntiannan** [comment] 2019-03-30 02:18
![image](https://user-images.githubusercontent.com/26763453/55270034-255eeb00-52d5-11e9-84ff-46e9d64ce41b.png)

**Comment by sikuntiannan** [comment] 2019-03-30 02:35
![image](https://user-images.githubusercontent.com/26763453/55270236-930c1680-52d7-11e9-85b8-4f5143d61d3d.png)

**Comment by sikuntiannan** [comment] 2019-03-30 02:36
![image](https://user-images.githubusercontent.com/26763453/55270254-b3d46c00-52d7-11e9-801f-08f197c2fa9e.png)

**Comment by chjz1024** [comment] 2019-04-07 13:10
Hi @sikuntiannan,

Have you solved this problem? I'm having the same problem as I build the project with vs2019 community. All I've done is to modify the `Additional Dependencies` and `Additional Include Directories` in the property page of my project. But when I generate a new solution from a CMakeLists.txt file as described in <https://pytorch.org/tutorials/advanced/cpp_frontend.html> then it works.

I've also tested on vs2015 (without cmake), then there is no such warning. It seems like that's a new feature in vs2017 and 2019. Do you have any idea about that? I'm using the nightly built libtorch archive.

**Comment by peterjc123** [comment] 2019-04-07 13:27
@chjz1024 Are there any differences between the project generated by yourself and the one generated by CMake?

**Comment by chjz1024** [comment] 2019-04-07 14:08
@peterjc123 I havn't examined that carefully, but generally speaking they differ a lot and I just copied the `Additional Dependencies` and `Additional Include Directories` from the cmake generated project. I've created a repository for reference <https://github.com/chjz1024/plainTorch>.

**Comment by peterjc123** [comment] 2019-04-08 01:52
@chjz1024 Thanks a lot. I'll see if there's an equivalent for cmake.

**Comment by peterjc123** [comment] 2019-04-08 02:52
Looks like the flag `/permissive` should be added to turn it off.

**Comment by peterjc123** [comment] 2019-04-08 03:05
And the cast-to-function error should be a MSVC bug: https://developercommunity.visualstudio.com/content/problem/256712/c2066-with-type-alias-declaration-in-class-templat.html.

**Comment by liukuanlk** [comment] 2019-05-14 15:50
@chjz1024 @peterjc123 Thank you for all information you provided. They are very helpful. Actually I encountered the same issue "std ambiguous symbol" in latest VS 2017. I tried to change the `conformance` mode property to `No` but it does not help. I got new error as attached.
![image](https://user-images.githubusercontent.com/22803967/57710921-d62e0900-763b-11e9-8d3f-4d32b64a3631.png)

I can use Cmake to generate the project and that works well. So I want to know,
1. what is the difference between build with VS and build with CMake? Is there a transformation equation for them?
2. What's the correct procedure to generate a project in VS 2017 windows?
```
#include <iostream>
#include "torch/torch.h"

int main()
{
	std::cout << "Hello World!\n";
	torch::Tensor tensor = torch::eye(3);
	std::cout << tensor << std::endl;

}
```
With the simple example above, I followed the following steps and got errors while building. Please let me know if my procedure is wrong. Thanks.

step 1. create a project in  VS and copy the code above to Source files
step 2. set the `additional include directories`
```
\libtorch-win-shared-with-deps-latest\libtorch\include
\libtorch-win-shared-with-deps-latest\libtorch\include\torch\csrc\api\include
```
step 3. set the `additional library directories`
`libtorch-win-shared-with-deps-latest\libtorch\lib`

step 4. set `configuration `to `release `

step 5. set `conformance mode` property to `No`

step 5. build

**Comment by peterjc123** [comment] 2019-05-14 15:54
@liukuanlk One step is missing there. You'll need to add the addition libraries in Linker Options: `torch.lib;caffe2.lib;caffe2_gpu.lib;c10.lib;c10_cuda.lib`.

**Comment by liukuanlk** [comment] 2019-05-14 16:19
@peterjc123 thanks for reply. But sorry I did not get your point. I have already set `additional library directories` in step 3. Could you give me more specific instruction like where I should include the `.lib` you mentioned?

**Comment by peterjc123** [comment] 2019-05-14 16:31
https://images.app.goo.gl/5v5EpnA8CUDMPg787

**Comment by liukuanlk** [comment] 2019-05-14 20:29
@peterjc123 Thank you, that works! However, when I followed the above steps and worked on this advanced example https://github.com/pytorch/examples/blob/master/cpp/dcgan/dcgan.cpp I could build but I could not run. When I use debug mode I got 
```
'Project2.exe' (Win32): Loaded 'C:\Users\kuanliu\source\repos\Project2\x64\Release\Project2.exe'. Symbols loaded.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. Symbols loaded.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. Symbols loaded.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. Symbols loaded.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. Cannot find or open the PDB file.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. Cannot find or open the PDB file.
'Project2.exe' (Win32): Loaded 'C:\Users\kuanliu\source\repos\Project2\x64\Release\torch.dll'. Module was built without symbols.
'Project2.exe' (Win32): Loaded 'C:\Users\kuanliu\source\repos\Project2\x64\Release\c10.dll'. Module was built without symbols.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. Cannot find or open the PDB file.
'Project2.exe' (Win32): Loaded 'C:\Users\kuanliu\source\repos\Project2\x64\Release\caffe2.dll'. Module was built without symbols.
'Project2.exe' (Win32): Loaded 'C:\Users\kuanliu\source\repos\Project2\x64\Release\libiomp5md.dll'. Cannot find or open the PDB file.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. Cannot find or open the PDB file.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. Cannot find or open the PDB file.
'Project2.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. Cannot find or open the PDB file.
The thread 0x3cf4 has exited with code 0 (0x0).
The thread 0x16e8 has exited with code 0 (0x0).
The thread 0x1f2c has exited with code 0 (0x0).
The program '[1368] Project2.exe' has exited with code 0 (0x0).
```

**Comment by peterjc123** [comment] 2019-05-15 00:52
On Windows, debug and release builds are not ABI-compatible. If you plan to build your project in debug mode, please try the debug version of LibTorch.

**Comment by sikuntiannan** [comment] 2019-05-15 02:44
> @peterjc123 @sikuntiannan. I tested on different configurations and found that problem can be solved by change the `conformance mode` property to **`No`**. You can find that option in `C/C++->Language`. That's a new feature in vs2017 and 2019.

you think  use C++17 tandard?

**Comment by mdreammao** [comment] 2019-08-06 12:38
I've got the same error!  Is the bug fixed finally？

**Comment by mdreammao** [comment] 2019-08-06 12:38
I've got the same error!  Is the bug fixed finally？

**Comment by mdreammao** [comment] 2019-08-06 12:38
I've got the same error!  Is the bug fixed finally？

**Comment by mdreammao** [comment] 2019-08-06 12:38
I've got the same error!  Is the bug fixed finally？

**Comment by mdreammao** [comment] 2019-08-06 12:38
I've got the same error!  Is the bug fixed finally？

**Comment by mdreammao** [comment] 2019-08-06 12:38
I've got the same error!  Is the bug fixed finally？
