### ISSUE TITLE
torch.empty after construction puts a high load on CPU for a long time when the size is big

### ISSUE THREAD

**Issue by SergeyDidenko** [pytorch/pytorch#7755] opened 2018-05-22 07:07 UTC
## Issue description

`tensor_uninitialized = torch.empty(1000000)` returns immediately but just after that puts a 100% load an a CPU core that lasts about 40s. The longevity of this load seems to be proportional to the requested tensor size.

`numpy.empty()` and `torch.zeros()` have no this problem.

## Code example

```
tensor_uninitialized = torch.empty(1000000)
```

returns very fast but puts a long load on CPU

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 9.1.85

OS: Linux Mint 18.3 Sylvia
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.9) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 387.26
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip3] numpy (1.14.1)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.1)
[conda] Could not collect

**Comment by zou3519** [comment] 2018-05-22 13:58
@SergeyDidenko I'm having trouble reproducing this, but I don't have the same exact configuration as you. If you could reproduce this in a docker image that would be very helpful.

**Comment by SergeyDidenko** [comment] 2018-05-22 20:05
Sorry, my fault. 

I was testing in Jupyter Notebook and forgot that it added additional complexity to "vanilla" python. So there's no such problem in the python shell.

This problem gradually builds up with each "Kernel Restart". May be it's related to lazy deallocation of memory or maybe it has another reason. Anyway hard restart of Jupyter Notebook cleans out this problem.

So I don't see anything wrong on PyTorch side here.

**Comment by SsnL** [comment] 2018-05-22 20:09
Thanks for the update. I'm closing this for now. Feel free to reopen if you discover that the issue is from PyTorch.

**Closed by SsnL** 2018-05-22 20:09 UTC
