### ISSUE TITLE
torch.lobpcg always breaks for autograd

### ISSUE THREAD

**Issue by chausies** [pytorch/pytorch#38948] opened 2020-05-23 04:38 UTC
## 🐛 Bug

It seems that `torch.lobpcg` (https://pytorch.org/docs/stable/torch.html?highlight=lobpcg#torch.lobpcg) just always breaks when trying to take gradients via `backward`.

## To Reproduce

Here's a minimalist example showing `lobpcg` breaking.

```python3
# lob.py
import torch as T
T.autograd.set_detect_anomaly(True)

A = T.randn(10, 10)
A.requires_grad_()
S = A.matmul(A.t())
e, v = T.lobpcg(S, k=3)
S_hat = T.einsum('ij,j,kj->ik', v, e, v) # v * diag(e) * v^T
loss = S_hat.abs().sum()
loss.backward() # breaks here
```
Running that code produces the following error.

```
Warning: Error detected in MmBackward. Traceback of forward call that caused the error:
  File "lob.py", line 9, in <module>
    e, v = T.lobpcg(S, k=3)
  File "/usr/local/lib/python3.5/dist-packages/torch/_lobpcg.py", line 261, in lobpcg
    worker.run()
  File "/usr/local/lib/python3.5/dist-packages/torch/_lobpcg.py", line 408, in run
    self.update()
  File "/usr/local/lib/python3.5/dist-packages/torch/_lobpcg.py", line 343, in update
    self._update_ortho()
  File "/usr/local/lib/python3.5/dist-packages/torch/_lobpcg.py", line 498, in _update_ortho
    self.X[:, nc:] = mm(S_, Z[:, :n - nc])
 (print_stack at /pytorch/torch/csrc/autograd/python_anomaly_mode.cpp:60)
Traceback (most recent call last):
  File "lob.py", line 12, in <module>
    loss.backward() # breaks here
  File "/usr/local/lib/python3.5/dist-packages/torch/tensor.py", line 198, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/usr/local/lib/python3.5/dist-packages/torch/autograd/__init__.py", line 100, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [10, 5]], which is output 0 of SliceBackward, is at version 14; expected version 11 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

I have a feeling that the problem is that `torch.lobpcg`'s implementation is using an in-place operation when it shouldn't be.

This happened when running `torch.__version__ == '1.5.0+cpu'` installed with pip on Windows 10 WSL (Windows Subsystem for Linux) on Python 3.5.2.

Can this be fixed, or is `torch.lobpcg` not meant to support autograd?

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @vincentqb @vishwakftw @jianyuh @mruberry @SsnL

**Comment by ezyang** [comment] 2020-05-26 17:39
@pearu, could you please take a look at this?

**Comment by pearu** [comment] 2020-05-26 21:23
The LOBPCG algorithm is iterative, and indeed, the `torch.lobpcg` implementation uses in-place operations which cannot be avoided. However, the current issue can be resolved by implementing autograd support for `torch.lobpcg`: the same backward algorithm used in `torch.eig` ought to be a good starting point, it needs to be modified for the `k` parameter that restricts the number of eigenpairs.

**Comment by pearu** [comment] 2020-05-26 21:56
For reference: https://github.com/pytorch/pytorch/issues/32531 - gradient of `torch.eig`.

**Comment by pearu** [comment] 2020-05-27 11:50
The paper https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf
derives the backward formula for the standard eigenvalue problem that involves the inverse of the eigenvectors matrix. Since the lobpcg provides only the first `k` eigenvectors, the formula is not applicable here.

@nikitaved what do you think, is the problem of backward solvable in general with the restricted set of eigenpairs?

**Comment by albanD** [comment] 2020-05-27 12:10
The `torch.eig` function has a similar limitation that if you set `eigenvectors=False`, you won't be able to compute the backward pass.

**Comment by nikitaved** [comment] 2020-05-27 13:58
It is possible to derive the gradient for k-rank lobpcg, but it is not going to be unique because it will be a solution to an overdetermined system of linear equations. I will put my derivations a bit later so that you could tell whether you agree with them...

**Comment by nikitaved** [comment] 2020-05-27 14:48
Ah, sorry, the system is underdetermined, here it goes...
For simplicity, let's consider a general rank-k eigenvalue problem of the form  `AU = UD`, where `A is n by n, rank(U) = rank(D) = k`. Then applying the diff operator:
```
dA U + A dU = dU D + U dD,
U^T dA^T = (dU D + U dD - A dU)^T.
```
Let `K:=U^T, X = dA^T, B = (dU D + U dD - A dU)^T`. We want to find `X` by solving the following matrix equation:
```
K X = B, where K,B in (k, n), X in (n, n).
```
we can split it into `n` systems of linear equations of the form
```
K X[i] = B[i].
```
As you can see, we have `k < n` equalities with `n` unknowns, so it is underdetermined.
One possible solution could be this:
```
Let I = {i_i,...i_k} column indices, such that rank(K[I]) = k, then
X[i]_I = K[I]^{-1} B[i] for indices in I, and zero otherwise.
```
The non-uniqueness comes from the process if picking k columns...

**Comment by nikitaved** [comment] 2020-05-27 15:42
But I guess we might run into an issue when both input matrices for lobpcg require gradient...

**Comment by albanD** [comment] 2020-05-27 17:30
But in this case, if you consider the rank-k problem, `AU = UD` is not true in general. There are no rank-k matrix U and diagonal D that verifies this. So you can't base your gradient derivation on this equality right?

**Comment by nikitaved** [comment] 2020-05-27 17:45
Why is it not true in general? Take any k eigenvectors of A and fill diagonal of D with the corresponding eigenvalues, there you go...

**Comment by pearu** [comment] 2020-05-27 17:50
@albanD I am not sure I am following you. We have
```
E, V = torch.lobpcg(A, k=k)
```
so that
```
torch.mm(A, V) == torch.mm(V, torch.diag(E))
```
holds.

Replacing `k` with `n` will produce the same first `k` eigenpairs as when using the initial `k`.

**Comment by nikitaved** [comment] 2020-05-27 17:59
Yeah, exactly, lobpcg is a function  A -> U, D, such that AU = UD, in case of the basic eignevalue problem.

**Comment by pearu** [comment] 2020-05-27 18:04
> Replacing `k` with `n` will produce the same first `k` eigenpairs as when using the initial `k`.

This is not actually true as lobpcg works only when `3*k<=n`. Sorry for the confusion. But lobpcg will return the first `k` eigenpair.

**Comment by pearu** [comment] 2020-05-27 18:34
> One possible solution could be this:
> 
> ```
> Let I = {i_i,...i_k} column indices, such that rank(K[I]) = k, then
> X[i]_I = K[I]^{-1} B[i] for indices in I, and zero otherwise.
> ```

This method does seem to produce `X` such that `K X=B` holds only the `k` columns but for others not (as the corresponding columns in `B` are non-trivial).

**Comment by nikitaved** [comment] 2020-05-27 18:35
In my notation B is something different.

**Comment by nikitaved** [comment] 2020-05-27 18:38
> > One possible solution could be this:
> > ```
> > Let I = {i_i,...i_k} column indices, such that rank(K[I]) = k, then
> > X[i]_I = K[I]^{-1} B[i] for indices in I, and zero otherwise.
> > ```
> 
> This method does seem to produce `X` such that `K X=B` holds only the `k` columns but for others not (as the corresponding columns in `B` are non-trivial).

I am not sure I understand...

**Comment by albanD** [comment] 2020-05-27 18:40
@pearu  My concern is how can the k top eigenvalues be exact if A has rank > k:
```
import torch

A = torch.rand(10, 10) # Most likely rank > 3
k = 3

E, V = torch.lobpcg(A, k=k)

# This will print != 0
print(( torch.mm(A, V) - torch.mm(V, torch.diag(E)) ).abs().max())
```

**Comment by nikitaved** [comment] 2020-05-27 18:41
@alban, take k eigenvalues of A, so that we have Au_i = lambda_i u_i. Now, Let U = (u_1, ... u_k), D = diag(lambda_1,..., lambda_k). Now you have AU = UD.

**Comment by albanD** [comment] 2020-05-27 18:44
Ho right this system has only k columns! Thanks !

**Comment by pearu** [comment] 2020-05-27 18:47
> My concern is how can the k top eigenvalues be exact if A has rank > k

The input to `lobpcg` must be a symmetric positive defined matrix. So try
```
A = torch.mm(A.transpose(-2, -1), A)
```
before calling `lobpcg`.

**Comment by albanD** [comment] 2020-05-27 18:56
In that case you get an error in the order of 1e-3 (with the same parameters, n=10, k=3). Which is a worst case so ok I think.
But my concern is solved by seeing that we only have k vectors for which we verify this equality. So it makes sense that k eigenpairs are enough.

**Comment by pearu** [comment] 2020-05-27 19:10
> I am not sure I understand... In X only a submatrix of size of size (k, n) is non-zero, the rest is zero.
> `X[i][I] = K[I]^{-1} L[i]`, and `X[i][[n] \ I] = 0`. To be more prices, X has k non-zero rows, the rest is zero.

@nikitaved, it seems to be ok (I had a little bug before). Here is a quick example of your method:
```
import torch as T

class LOBPCG2(T.autograd.Function):

    @staticmethod
    def forward(ctx, A):
        k = 2
        e, v = T.lobpcg(A, k=k)
        res = T.mm(A, v) - T.mm(v, T.diag(e))
        assert (res.abs() < 1e-5).all()
        ctx.save_for_backward(e, v, A)
        return e, v

    @staticmethod
    def backward(ctx, de, dv):
        """
        solve `dA v + A dv = dv diag(e) + v diag(de)` for `dA`
        """
        e, v, A = ctx.saved_tensors

        vt = v.transpose(-2, -1)
        print('vt=', vt)
        print('de=', de)
        print('dv=', dv)
        rhs = (T.mm(dv, T.diag(e)) + T.mm(v, T.diag(de)) - T.mm(A, dv)).transpose(-2, -1)
        print('rhs=', rhs)

        n, k = v.shape
        K = vt[:, :vt.shape[0]]
        print('K.det=', K.det())  # should be > 0
        iK = K.inverse()

        dAt = T.zeros((n, n))
        dAt[:k] = T.mm(iK, rhs)[:k]
        print('dAt=', dAt)
        dA = dAt.transpose(-2, -1)

        res = T.mm(dA, v) + T.mm(A, dv) - T.mm(dv, T.diag(e)) - T.mm(v, T.diag(de))
        print('res=', res)
        return dA
    
T.random.manual_seed(123)

A = T.randn(6, 6)
S = A.matmul(A.t())
S.requires_grad_()

e, v = LOBPCG2.apply(S)

S_hat = T.einsum('ij,j,kj->ik', v, e, v) # v * diag(e) * v^T
loss = S_hat.abs().sum()
loss.backward()
```
(the printed `res` is close to zero).

**Comment by nikitaved** [comment] 2020-05-27 19:11
@pearu, so, does it work? :)

**Comment by pearu** [comment] 2020-05-27 19:14
Yes, the `backward` call works but the method requires verification against `torch.symeig` case and understanding the consequences of the arbitrariness of `dA`.

**Comment by nikitaved** [comment] 2020-05-27 19:16
You can compare it for the case `k=n`, for example.

**Comment by nikitaved** [comment] 2020-05-27 19:34
But it is analytic. I am sure there must be some linear equation solver somewhere in PyTorch..

**Comment by albanD** [comment] 2020-05-27 20:34
We do have a `torch.solve`.
Also if you want to compare to finite difference, you can use `torch.autograd.gradcheck` (with double input) with:
```
S = S.double().detach().requires_grad_(True)

# You need to make sure in your backward that your call to torch.zeros() creates the proper dtype
# by passing `dtype=A.dtype`.
T.autograd.gradcheck(LOBPCG2.apply, S)
```

Interestingly, the Jacobian wrt the eigenvalues given by the finite difference don't match because it generates a "dense" gradient while your method give gradients only for the first two columns of A :/

**Comment by nikitaved** [comment] 2020-05-27 21:21
Well, the issue is exactly we have an infinite number of solutions to the system of linear equations `K X = L, where X in (n, n), K, L in (k, n)`. Wlog assume that the first `k` columns of K are linearly independent, call it `K_k`. We split `X` into two submatrices `X_k` of size `(k, n)` and `X_-k` of size `(n-k, n)`, and similar we split `K`, then we get:
```
K X = L => [K_k K_-k] [X_k / X_-k] = L => K_k X_k + K_-k X_-k = L. K_k is full rank, so
X_k = K_k^{-1} (L - K_-k * X_-k).
```
We decided to pick one solution with `X_-k = 0`, but you can set `X_-k` to arbitrary matrix and get a different solution `[X_k / X_-k]`.
So, I am back to my claim, we have an infinite number of valid gradients ;)

**Comment by albanD** [comment] 2020-05-27 21:35
Are all of these (local) subgradients?

**Comment by nikitaved** [comment] 2020-05-27 22:09
Oh, wait we just found a forward differential with `X`, it is not the backward formula, however :)

**Comment by nikitaved** [comment] 2020-05-28 16:52
So, I know how to derive backward with full eigenspace, now I am thinking whether it is possible to avoid its full computation...

**Comment by nikitaved** [comment] 2020-05-29 07:18
Could it be like this? Again, assuming that
```
A is symmetric (n, n), U is (n, k) and orthogonal, i.e. U^T T = I, D is a k-scalar matrix.
We have AU = UD. Applyting diff we get:
dA U + A dU = dU D + U dD [multiply by U^T on the left, orthogonality of U]
U^T dA U + U^T A dU = U^T dU D + dD, [make a substitute dU = U dC, dC in (k, k)]
U^T dA U + U^T (AU) dC = (U^T U) dC D + dD, [AU = UD, U^T U = I]
U^T dA U + D dC = dC D + dD. (*)

Consider D dC - dC D, since D is a scalar matrix, it can be represented as
D dC - dC D = E o dC, where o is the Hadamard product and E_ij = d_j - d_i.

Substituting it all back into (*) gives:
U^T dA U + E o dC = dD. 
Note that E o dC has zero diagonal, while dD is a scalar matrix, hence
dD = I o (U^T dA U) (**) and
dC = F o (U^T dA U) (***), where F_ij = (d_j - d_i)^{-1} for i != j and F_ii = 0.
Recalling our substitute dU = U dC we get:
dU = U (F o (U^T dA U)) (****)

Now we have all the ingredients for the backward AD:
Tr(D.grad^T dD + U.grad^T dU) =
Tr(D.grad^T ( I o (U^T dA U))) + Tr(U.grad^T dU) = 
Tr(D.grad U^T dA U) + Tr(U.grad^T dU) = [cyclic property of trace]
Tr(U D.grad U^T dA) + Tr(U.grad^T dU) =
[1] + [2],

[2] =  Tr(U.grad^T dU) = Tr(U.grad^T U (F o (U^T dA U))) = [Tr(A (B o C)) = Tr((A o B^T) C)]
Tr((U.grad^T U o F^T)(U^T dA U)) =
Tr(U (U.grad^T U o F^T) U^T dA)

In [1], [2] we sum the terms to the left from the dA and transpose them to get:
A.grad = U (D.grad + (U^T U.grad o F)) U^T.
```

**Comment by pearu** [comment] 2020-05-29 09:23
gradcheck gives:
```
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 5.1314e-04,  1.3259e-01],
        [-2.1311e-02,  5.7138e-02],
        [-1.1582e-02, -5.3796e-01],
        [-2.1237e-02, -1.5204e-01],
        [-2.2161e-02,  3.7977e-01],
        [-2.2827e-02,  4.2838e-03],
        [ 0.0000e+00,  0.0000e+00],
        [ 2.2126e-01,  6.1558e-03],
        [ 2.4050e-01, -1.1592e-01],
        [ 4.4100e-01, -3.2760e-02],
        [ 4.6018e-01,  8.1831e-02],
        [ 4.7400e-01,  9.2305e-04],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 6.5354e-02,  5.4569e-01],
        [ 2.3968e-01,  3.0844e-01],
        [ 2.5010e-01, -7.7046e-01],
        [ 2.5761e-01, -8.6907e-03],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 2.1974e-01,  4.3584e-02],
        [ 4.5860e-01, -2.1774e-01],
        [ 4.7237e-01, -2.4561e-03],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 2.3927e-01,  2.7195e-01],
        [ 4.9292e-01,  6.1352e-03],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00],
        [ 2.5386e-01,  3.4603e-05]], dtype=torch.float64)
analytical:tensor([[ 5.1314e-04,  1.3259e-01],
        [-1.0655e-02,  2.8569e-02],
        [-5.7910e-03, -2.6898e-01],
        [-1.0619e-02, -7.6018e-02],
        [-1.1081e-02,  1.8989e-01],
        [-1.1413e-02,  2.1419e-03],
        [-1.0655e-02,  2.8569e-02],
        [ 2.2126e-01,  6.1558e-03],
        [ 1.2025e-01, -5.7958e-02],
        [ 2.2050e-01, -1.6380e-02],
        [ 2.3009e-01,  4.0916e-02],
        [ 2.3700e-01,  4.6153e-04],
        [-5.7910e-03, -2.6898e-01],
        [ 1.2025e-01, -5.7958e-02],
        [ 6.5354e-02,  5.4569e-01],
        [ 1.1984e-01,  1.5422e-01],
        [ 1.2505e-01, -3.8523e-01],
        [ 1.2881e-01, -4.3453e-03],
        [-1.0619e-02, -7.6018e-02],
        [ 2.2050e-01, -1.6380e-02],
        [ 1.1984e-01,  1.5422e-01],
        [ 2.1974e-01,  4.3584e-02],
        [ 2.2930e-01, -1.0887e-01],
        [ 2.3619e-01, -1.2281e-03],
        [-1.1081e-02,  1.8989e-01],
        [ 2.3009e-01,  4.0916e-02],
        [ 1.2505e-01, -3.8523e-01],
        [ 2.2930e-01, -1.0887e-01],
        [ 2.3927e-01,  2.7195e-01],
        [ 2.4646e-01,  3.0676e-03],
        [-1.1413e-02,  2.1419e-03],
        [ 2.3700e-01,  4.6153e-04],
        [ 1.2881e-01, -4.3453e-03],
        [ 2.3619e-01, -1.2281e-03],
        [ 2.4646e-01,  3.0676e-03],
        [ 2.5386e-01,  3.4602e-05]], dtype=torch.float64)
```
Notice that some elements of numerical and analytical approaches match, some not.

**Comment by nikitaved** [comment] 2020-05-29 09:59
Could you show your code?

**Comment by pearu** [comment] 2020-05-29 17:28
@albanD it the following behavior of `gradcheck` expected?:
```python
import torch as T
T.random.manual_seed(123)
A = T.randn(2, 2).double()
S = A.matmul(A.t())
S = S.double().detach().requires_grad_(True)
def mysymeig(A):
    return T.symeig(A, eigenvectors=True)
T.autograd.gradcheck(mysymeig, S)
```
results
```
RuntimeError: Jacobian mismatch for output 0 with respect to input 0,
numerical:tensor([[ 0.9947,  0.0053],
        [-0.1449,  0.1449],
        [ 0.0000,  0.0000],
        [ 0.0053,  0.9947]], dtype=torch.float64)
analytical:tensor([[ 0.9947,  0.0053],
        [-0.0724,  0.0724],
        [-0.0724,  0.0724],
        [ 0.0053,  0.9947]], dtype=torch.float64)
```

**Comment by nikitaved** [comment] 2020-05-29 17:55
@albanD , note that numerical value is the sum of lower and upper triangle of the analytic result, as if gradcheck takes into account the symmetry of input...

**Comment by albanD** [comment] 2020-05-29 18:07
The issue here is that gradcheck does finite differentiation only.
The issue here is that we do this in an unstructured way which breaks the symmetry of A.
The following works for me:
```python
import torch as T
T.random.manual_seed(123)
A = T.randn(2, 2).double()
S = A.double().detach().requires_grad_(True)
def mysymeig(A):
    A = A.matmul(A.t())
    return T.symeig(A, eigenvectors=True)
T.autograd.gradcheck(mysymeig, S)
```

**Comment by pearu** [comment] 2020-05-29 18:17
@albanD , this behavior is quite surprising as the modified `mysymeig` does not do what it was supposed to do anymore: solve the eigenproblem for `A`, not for `A A^T`.

**Comment by albanD** [comment] 2020-05-29 18:35
For this specific case, you could modify the gradcheck implementation to make sure you follow the hyperplane of symmetric matrices.
Changing l153 of gradcheck:
```python
            x_tensor = x_tensor.data
            for d_idx, x_idx in enumerate(product(*[range(m) for m in x_tensor.size()])):
                assert len(x_idx) == 2
                if x_idx[0] != x_idx[1]:
                    mul = 2
                else:
                    mul = 1
                orig = x_tensor[x_idx].item()
                x_tensor[x_idx] = orig - eps
                x_tensor[tuple(reversed(x_idx))] = orig - eps
                outa = fn(input).clone()
                x_tensor[x_idx] = orig + eps
                x_tensor[tuple(reversed(x_idx))] = orig + eps
                outb = fn(input).clone()
                x_tensor[x_idx] = orig
                x_tensor[tuple(reversed(x_idx))] = orig
                r = (outb - outa) / (mul * 2 * eps)
                d_tensor[d_idx] = r.detach().reshape(-1)
```

After this change, your original code passes the test.

> Are there any references for this design of gradcheck or autograd in general?

Unfortunately no :/ It "simply" does finite differentiation along each ei vectors.
If you ignore the complex, sparse, xla stuff, it boils down to:
```python

def get_numerical_jacobian(fn, input, target=None, eps=1e-3):
    if target is None:
        target = input
    output_size = fn(input).numel()
    # Make the empty jacobian will proper size
    jacobian = make_jacobian(target, output_size)

    # It's much easier to iterate over flattened lists of tensors.
    # These are reference to the same objects in jacobian, so any changes
    # will be reflected in it as well.
    x_tensors = iter_tensors(target, True)
    j_tensors = iter_tensors(jacobian)

    for x_tensor, d_tensor in zip(x_tensors, j_tensors):
        # Use .data here to get around the version check
        x_tensor = x_tensor.data
        for d_idx, x_idx in enumerate(product(*[range(m) for m in x_tensor.size()])):
            # Original value
            orig = x_tensor[x_idx].item()
            # Value on left
            x_tensor[x_idx] = orig - eps
            outa = fn(input).clone()
            # value on right
            x_tensor[x_idx] = orig + eps
            outb = fn(input).clone()
            x_tensor[x_idx] = orig
            # Compute the ratio
            r = (outb - outa) / (2 * eps)
            d_tensor[d_idx] = r.detach().reshape(-1)

    return jacobian
```

Which for a function f with a single input/output does:
`grad = ( f(x + eps) - f(x - eps)) / ( 2 * eps)`.
With a for-loop for multiple inputs/outputs.

**Comment by pearu** [comment] 2020-05-29 19:08
Thanks for these details.

To resolve this issue, we'll need to implement `lobpcg_backward`. The formula for backward is (using the notation from [NA-08-01.pdf](https://people.maths.ox.ac.uk/gilesm/files/NA-08-01.pdf)):
```
A_bar = U (D_bar + ((U^T U_bar) o F)) U^T
```
The main question is, what `lobpcg_backward` ought to return to match autograd expectations? 
I would assume that it should return `A_bar`.

Note that the `symeig_backward` [implementation](https://github.com/pytorch/pytorch/blob/a5d44800f07f34e2183270da4b9d8bf55eef3a4d/tools/autograd/templates/Functions.cpp#L1887) returns `(A_bar + A_bar^2)/2`.

It seems that to use `gradcheck` in tests, one has to use your modification (that is also in [test_autograd.py::test_symeig](https://github.com/pytorch/pytorch/blob/88c5fd94e79be0e2f01e26e717aad719f84ef19d/test/test_autograd.py#L2385)).

**Comment by lobpcg** [comment] 2020-07-17 16:05
Let me add my 2 cents.In
```
A_bar = U (D_bar + ((U^T U_bar) o F)) U^T
```
U and D uniquely determine the n-by-n matrix A and their perturbations uniquely determine the perturbed A, and vice versa. `lobpcg` setup  operates with just a small subset of k eigenvectors, columns of the n-by-n matrix U, that cannot possibly reconstruct the n-by-n matrix A uniquely without imposing constraints on A. One possibly reasonable constraint is assuming that A has rank k (assuming all non-zero eigenvalues), which would allow for a unique and possibly numerically stable backward formula, I guess.

**Comment by nikitaved** [comment] 2020-08-06 16:14
@pearu , sorry, been busy. So, the backward for a `k`-rank eigenproblem from above is correct, I only updated the definition of `E`, which was incorrect, it has to be `E_ij = d_i - d_j`.

Now, consider the generalized version `AU = BUD`. We know that `B` is positive-definite, so it is full-rank, hence `B^{-1}` exists. Let `C = B^{-1}A`, then the generalized problem can be rewritten as `CU = UD`. For this problem we already know how to get its backward, another words, during the backward AD:
```
Tr(U_grad^T dU) + Tr(D_grad^T dD) = Tr(C_grad^T dC), where
C_grad is a backward result of an eig problem with the input C=B^{-1}A and the output (U, D).
```
So, we can find `C_grad`, now we need to find `A_grad` and `D_grad`.
```
C = B^{-1}A => dC = dB^{-1}A + B^{-1}dA                                               (1)

Recall that BB^{-1} = I => dB B^{-1} + B dB^{-1} = 0 => dB^{-1} = -B^{-1} dB B^{-1}   (2)

Plug (2) into (1):

dC = -B^{-1} dB B^{-1} A + B^{-1} dA

```

Back to the backward AD:
```
Tr(C_grad^T dC) = Tr(-C_grad^T B^{-1} dB B^{-1} A) + Tr(C_grad^T B^{-1} dA)
= Tr(-B^{-1} A C_grad^T B^{-1} dB) + Tr(C_grad^T B^{-1} dA), hence

A_grad = B^{-1} C_grad [B^{-1}^T = B^{-1}],
B_grad = -B^{-1} C_grad C^T.
```

Please, check the math.

**Comment by nikitaved** [comment] 2020-08-12 13:15
@pearu , @albanD , lobpcg is not defined in `native_functions.yaml`. It is not going to be a problem with `derivatives.yaml`, right? How can I extract a relevant schema to be usable in `derivatives.yaml`?

**Comment by albanD** [comment] 2020-08-12 14:36
Hey,

The function is implemented [here](https://github.com/pytorch/pytorch/blob/master/torch/_lobpcg.py).
So I think the simplest way to go about this is to actually create a custom `autograd.Function` (https://pytorch.org/docs/stable/notes/extending.html) with the forward that already exists and your new backward.
Then you can make `torch.lobpcg` point to `LOBPCGFunction.apply`.

**Comment by pearu** [comment] 2020-08-12 14:44
@nikitaved , see https://github.com/Quansight/pearu-sandbox/blob/master/pytorch/issue38948.py for implementing lobpcg backward in Python.

**Comment by nikitaved** [comment] 2020-08-12 15:11
Thank you! Now I have a question, the function accepts two inputs and hence produces two grads. Is it always the case? Does it depend on whether `requires_grad` is set? Like, if for both `A` and `B` the grad is set, then return joint grads as in the derivation from above, otherwise treat one of them as constant.

**Comment by nikitaved** [comment] 2020-08-12 15:20
Ah, sorry, my comment got deleted by mistake. `derivatives.yaml` allow to specify grad for any subset of inputs. How do I do that with with `autograd.Function` approach? There are 3 cases: grad wrt to joint (A, B), wrt A, wrt B.

**Comment by albanD** [comment] 2020-08-12 15:29
You can check the example in the doc I sent. But you have `ctx.needs_input_grad` list that tells you what you need to compute the gradient for. You can use that to condition your backward code to only do the work that is needed (and you should return None for things that don't need gradients).

**Comment by nikitaved** [comment] 2020-08-12 15:30
I get what you say, so I can explicitly check the input which requires grad, I get it. Thank you!

**Comment by lobpcg** [comment] 2020-08-12 15:50
If I understand correctly the above, the backward computation is algorithm agnostic, i.e. comes from perturbation theory of eigenvalues and eigenvectors that are assumed to be computed exactly. LOBPCG only computes approximately, so the results of the backward computation are going to match only quite approximately. E.g., in an extreme case where LOBPCG performs just one iteration, the results of forward and backward computations will unlickly match each other well. This is very different from what is typically meant. Please confirm or correct me.

**Comment by pearu** [comment] 2020-08-12 15:59
> If I understand correctly the above, the backward computation is algorithm agnostic

yes

> LOBPCG only computes approximately, so the results of the backward computation are going to match only quite approximately. E.g., in an extreme case where LOBPCG performs just one iteration, the results of forward and backward computations will unlickly match each other well. This is very different from what is typically meant. Please confirm or correct me.

yes, that is all correct, however, I don't see problems with the above in the sense that if a user asks for less accuracy from lobpcg, s/he cannot expect forward/backward to be exact either.

**Comment by lobpcg** [comment] 2020-08-12 16:10
Thanks for the confirmation! I hope that this distinction is made clear to avoid confusion. There are simple iterative methods where forward/backward pair can be implemented quite accurately, for a fixed initial approximation.

Sent from my T-Mobile 4G LTE Device
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by nikitaved** [comment] 2020-08-12 19:46
@albanD , the `lobpcg` implementation accepts 14 parameters. Is it possible to implement `forward/backward` as a class method to make `forward/backward` accept and return only 2 parameters?

**Comment by albanD** [comment] 2020-08-12 19:50
You can do anything you want :D 
You can make the whole thing a custom Function that takes all 14 parameters (and will return None gradients for most of them as they are not differentiable).
Or you can have some pre/post processing that is autodiffed. And only the core that is a simpler custom Function with a limited number of arguments for which you implement the forward/backward.

**Comment by lobpcg** [comment] 2020-08-12 21:59
@nikitaved Since the proposed backward algorithm is generic and thus unrelated to lobpcg, its interface should not mimic that of lobpcg.

**Comment by nikitaved** [comment] 2020-08-12 22:33
Nothing I can do about it, the forward replicates the interface of lobpcg, and the backward requires grads for each input of forward. I could probably use some old `autograd.Function` style with a constructor to save the lobpcg relevant data and implement forward/backward as for a perfect Generalized Eigenvalue Solver, but the new style is probably better...
Maybe it actually makes sense to create a method with a name something like geigk (generalized eigenvalue problem of rank k), then implement backward for it, and then in the documentation state that its forward is implemented with lobpcg.

**Comment by albanD** [comment] 2020-08-12 23:45
>  I could probably use some old autograd.Function style 

Nope, most of the code has been removed. This don't work anymore.

> This method could be using less parameters by ignoring most optional ones from the lobpcg's interface.

Does such generalized solver exist in other python lib like scipy? If so, we can try to replicate their API.
If none exist, we do have a bit more freedom here.

**Comment by nikitaved** [comment] 2020-08-12 23:56
> Does such generalized solver exist in other python lib like scipy? If so, we can try to replicate their API.
> If none exist, we do have a bit more freedom here.

Yes, the scipy's [`eig`](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.linalg.eig.html#scipy.linalg.eig) does support the generalized interface.

**Comment by lobpcg** [comment] 2020-08-13 14:51
https://docs.scipy.org/doc/scipy/reference/generated/scipy.linalg.eigh.html 
https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.linalg.eigsh.html
since this is the symmetric case.

**Comment by nikitaved** [comment] 2020-08-19 19:38
Well, the formula above for the symmetric case, as does autograd show is incorrect. Upon closer I look I realized I cannot justify the substitute `dU = U dC`, as there is no guarantee that `span(dU) = span(U)`.

There is an alternative derivation below in which I am stuck at one point.
```
U^T U = I => dU^T U + U^T dU = 0 => du := U^T dU is skew-symmetric, so diag(du) = 0.
AU = UD => 
dA U + A dU = dU D + U dD [left-multiply by U^T]               (*)
U^T dA U + U^T A dU = du D + dD [AU = UD => U^T A = D U^T]
U^T dA U + D du = du D + dD
U^T dA U = (du D - D du) + dD [because du is skew symmetric, diag(du D) = diag(D du) = 0]

so we get
dD = I o (U^T dA U), and, similar to the derivation from above (**)
du = F o (U^T dA U), where F_ij = (d_j - d_i)^{-1}             (***)
```

Here goes the critical part
```
Let U_ortho be an orthonormal basis of a subspace orthogonal to the span(U).
Then we can write
dU = U du + U_ortho dX, where dX is (m-k) x k. This is true for some dX because <U, U_ortho> form a basis for R^m.

By Left-multipling (*) by U_ortho^T, and using the decomposition of dU and orthogonality we get:
U_ortho^T dA U + U_ortho^T A U_ortho dX = dX D. (x)
```
In `(x)` is a Sylvester equation wrt `dX` and we need to solve it explicitly, so that dA in this solution has to be only as a part of a matrix product. Do you know some tricks to solve it? `D` is diagonal.

**Comment by nikitaved** [comment] 2020-09-28 15:08
A PR that implements support for the symmetric case with `B=I` has been merged. After a short break I plan to implement the remaining two cases cases, that is
1. Grad wrt A for arbitrary B when `B.requires_grad == False` and
2. Grad wrt A and B when both require grads.

**Comment by mfkasim1** [comment] 2020-10-31 19:50
Hi @nikitaved, I've implemented the backward for symmetric A & B in [xitorch](https://github.com/mfkasim1/xitorch/blob/master/xitorch/linalg/symeig.py) for your reference. I have to admit it was not an easy task. I can write down the math derivation if you want.

**Comment by nikitaved** [comment] 2020-10-31 19:58
@mfkasim1 , hi! The symmetric case is already in PyTorch. The case for B requires the matrix square root, there is an issue I am assigned too. Maybe it is possible to avoid it. I am about to make a write-up. We could compare the math or become co-authors, up to you! You can check the code in torch/_lobpcg.py.

**Comment by mfkasim1** [comment] 2020-10-31 20:11
@nikitaved Ah, I thought you haven't implemented for non-identity `B`.
I'm using implicit matrices/linear operator for `A` and `B` in xitorch (only need to know `Av` and `Bv`), so it works for sparse matrices if you're interested in implementing that too. However, it involves iterative solve (e.g. cg, bicgstab, etc).

> Looks like you propagate over the whole eigenspace, right? Here the issue is that you only have a k-subspace, where k is generally much less than the dimension n

[`xitorch.linalg.symeig`](https://xitorch.readthedocs.io/en/latest/api/xitorch_linalg/symeig.html) function actually looks very similar to `lobpcg` where it only retrieves `k` eigenpairs for `k << n` and intended for applications where you can't store the `n-by-n` matrix.

**Comment by nikitaved** [comment] 2020-10-31 20:28
I see, thank you! Then you are right! B is only identity as of now. Would be cool to see alternatives which involve different methods.

Well, at least arXiv would be great for starters...

**Comment by lobpcg** [comment] 2020-10-31 20:59
The math trick avoiding the square root of B is to notice that inv(B)*A is symmetric in the B-based scalar product, i.e. x'Bx. So one can apply whatever standard theory or algorithms for generalized eigenvalue problems, as soon as B is SPD (our case). After the substitution, in many places one gets inv(B)B so it just goes away. But in a few key spots one still needs implementing  vector multiplication by inv(B)*A  - that is where a linear solve for B is needed.

**Comment by nikitaved** [comment] 2020-11-01 05:06
Upon further inspection, I can see how to extend the already implemented method to the generalized problem. And, yes, it does not require the matrix square root.

**Comment by mfkasim1** [comment] 2020-11-02 14:13
@nikitaved for your reference, I have written down the symeig derivative in xitorch: https://xitorch.readthedocs.io/en/latest/notes/deriv_symeig.html

**Comment by pearu** [comment] 2023-12-14 17:56
Closing as the example in the description now works (thanks to https://github.com/pytorch/pytorch/pull/43002)

**Closed by pearu** 2023-12-14 17:56 UTC
Labels: module: autograd, triaged, module: linear algebra
