### ISSUE TITLE
[bug] Behavior of torch.full is different from torch.zeros on int size

### ISSUE THREAD

**Issue by apsdehal** [pytorch/pytorch#42686] opened 2020-08-06 17:39 UTC
## 🐛 Bug

`torch.full` throws a typeerror when the size is a single element int. While the same thing works for torch.zeros.

## To Reproduce
```
import torch
torch.full(1, fill_value=2) # Throws typeerror
torch.zeros(1) # works
```
## Expected behavior

torch.full should have same semantics as torch.zeros

(I am on master)

**Comment by vadimkantorov** [comment] 2020-08-06 17:55
I think the problem is that `(1)` is not a tuple. For tuple you need `(1,)`

**Comment by apsdehal** [comment] 2020-08-06 18:21
@vadimkantorov Thanks. That's correct. I am updating the issue to reflect API consistency.

**Comment by vadimkantorov** [comment] 2020-08-06 19:57
I think it's becasue `torch.full(1, 2, 3, 4)` would be not very clear, that (1,2,3) is shape and 4 is fill_value. And fill_value is not a kwarg-only.

And I guess torch.zeros(1, 2, 3) is supported for historical reasons.

But above is just my perspective

**Comment by ailzhang** [comment] 2020-08-07 01:10
Yea I think this is the design is kinda intentional. I'm going to closing this issue as resolved, please feel free to reopen if you have followup questions.

**Closed by ailzhang** 2020-08-07 01:10 UTC
