### ISSUE TITLE
non-deterministic and (sometimes) wrong results from `torch.linalg.lstsq`

### ISSUE THREAD

**Issue by juliusbierk** [pytorch/pytorch#92537] opened 2023-01-18 11:28 UTC
### Wrong result from `torch.linalg.lstsq`

The following code

```python
import torch

a = torch.eye(5)
a[0, :] = 0
b = torch.ones(5)
for _ in range(100):
    sol = torch.linalg.lstsq(a, b)
    x = sol.solution
    print('Rank =', int(sol.rank), 'Error =', float(torch.sum((a @ x - b)**2)))
```

returns the correct result only about half the time. The loop will randomly return `rank = 4` (correct) or `rank = 0` (incorrect).

This is only a problem with the default `driver='gelsy'` and can be fixed by setting e.g. `driver='gelsd'`.

Related issue:  https://github.com/pytorch/pytorch/issues/75494.

### Versions

```
PyTorch version: 1.13.1+cu117
CUDA used to build PyTorch: 11.7
OS: Ubuntu 22.04.1 LTS (x86_64)
```

cc @mruberry @kurtamohler @jianyuh @nikitaved @pearu @walterddr @IvanYashchuk @xwang233 @Lezcano

**Comment by DrDryg** [comment] 2023-01-18 14:15
Experience the same issue, was just about to report it.

**Comment by lezcano** [comment] 2023-01-20 10:49
Dupe of https://github.com/pytorch/pytorch/issues/71222

**Closed by lezcano** 2023-01-20 10:49 UTC
Labels: triaged, module: determinism, module: linear algebra
