### ISSUE TITLE
[pt2] compile gives wrong result for `argmax` on CUDA tensor of `float16`

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#93815] opened 2023-02-01 02:19 UTC
### 🐛 Describe the bug

In the following program, sometimes compiled function produces wrong results.

```python
import torch

def fn(x):
    return x.argmax(0)

for i in range(100):
    x = torch.randint(-100, 100, (20, 20), dtype=torch.int16)

    cpu = fn(x)
    gpu = fn(x.cuda()).cpu()
    compiled = torch.compile(fn)
    comp = compiled(x.cuda()).cpu()

    print(i)

    assert torch.allclose(cpu, gpu), '\n'.join(['', 'cpu', str(cpu), 'gpu', str(gpu)])
    assert torch.allclose(cpu, comp), '\n'.join(['', 'cpu', str(cpu), 'comp', str(comp)]) # may fail sometimes
```

### Error logs

An example:

```python
0
1
2
3
4
5
6
7
8
9
Traceback (most recent call last):
  File "/home/colin/bug.py", line 21, in <module>
    assert torch.allclose(cpu, comp), '\n'.join(['', 'cpu', str(cpu), 'comp', str(comp)])
AssertionError: 
cpu
tensor([ 6, 19,  3, 15, 15,  1, 10,  2,  2, 12, 18, 16, 15,  1, 19,  1,  2, 13,
         2, 15])
comp
tensor([ 6, 19, 12, 15, 15,  1, 10,  2,  2, 12, 18, 16, 15,  1, 19,  1,  2, 13,
         2, 15])
```

### Versions

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230131+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.10.9 (main, Jan 11 2023, 15:21:40) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-58-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 2080 Ti
Nvidia driver version: 510.85.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.7.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.7.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.24.1
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230131+cu117
[pip3] torchaudio==2.0.0.dev20230131+cu117
[pip3] torchvision==0.15.0.dev20230131+cu117
[conda] numpy                     1.24.1                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230131+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230131+cu117          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230131+cu117          pypi_0    pypi
```

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh

**Comment by ezyang** [comment] 2023-02-01 02:27
This repros for me. I'll draw our attention to this statement in our docs:

> If there are multiple maximal values then the indices of the first maximal value are returned.

**Comment by ngimel** [comment] 2023-02-01 05:06
Yeah currently we cannot control which of the max values triton returns.

**Comment by ezyang** [comment] 2023-02-01 13:54
dupe of https://github.com/pytorch/pytorch/issues/93630

**Closed** 2023-02-01 16:59 UTC
Labels: oncall: pt2
