### ISSUE TITLE
git clone of pytorch -0.4.0 is broken

### ISSUE THREAD

**Issue by gautamkmr** [pytorch/pytorch#7892] opened 2018-05-28 06:00 UTC
If you have a question or would like help and support, please ask at our
[forums](https://discuss.pytorch.org/).

If you are submitting a feature request, please preface the title with [feature request].
If you are submitting a bug report, please fill in the following details.

## Issue description
Unable to do git clone 0.4.0 of pytorch
Provide a short description.

## Code example

Cloning into 'pytorch-src'...
remote: Counting objects: 101473, done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 101473 (delta 24), reused 20 (delta 10), pack-reused 101401
Receiving objects: 100% (101473/101473), 54.60 MiB | 49.09 MiB/s, done.
Resolving deltas: 100% (75514/75514), done.
~/pytorch/pytorch-src ~/pytorch
Note: checking out 'v0.4.0'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>
.....
Cloning into '/home/ec2-user/pytorch/pytorch-src/third_party/eigen'...
Username for 'https://github.com': gautamkmr
Password for 'https://gautamkmr@github.com':
remote: Repository not found.
fatal: repository 'https://github.com/RLovelett/eigen.git/' not found
fatal: clone of 'https://github.com/RLovelett/eigen.git' into submodule path '/home/ec2-user/pytorch/pytorch-src/third_party/eigen' failed
Failed to clone 'third_party/eigen' a second time, aborting
[ec2-user@ip-172-31-17-149 pytorch]$
## System Info
Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

- PyTorch or Caffe2:
- How you installed PyTorch (conda, pip, source):
- Build command you used (if compiling from source):
- OS:
- PyTorch version:
- Python version:
- CUDA/cuDNN version:
- GPU models and configuration:
- GCC version (if compiling from source):
- CMake version:
- Versions of any other relevant libraries:

**Comment by ailzhang** [comment] 2018-05-28 13:09
Duplicate of #7793

**Closed by ailzhang** 2018-05-28 13:09 UTC
