### ISSUE TITLE
Failure to deploy Self-Hosted runners - High Queue Times and canceled jobs

### ISSUE THREAD

**Issue by zxiiro** [pytorch/pytorch#140958] opened 2024-11-18 16:33 UTC
# PyTorch CI using up GitHub APIs over our ratelimit

## Current Status
*Status: ongoing

## Error looks like

GitHub self-hosted runners being terminated unexpectedly.

## Incident timeline (all times pacific)
* Began around Friday Nov 15th @ 9 am 

## User impact
Intermittently GitHub self-hosted runners may terminate mid-job.

## Root cause

Under investigation 

## Mitigation
Split infra load between Meta fleet and LF fleet to spread the API usage across both accounts.

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by zxiiro** [comment] 2024-11-18 16:36
We detected this issue Friday morning pacific time and was able to mitigate it by spreading the load between both Meta fleet and LF fleet. However the issue is still on going. Since Friday the GitHub API usage by the ALI has been significantly higher than what we had seen prior to Friday. This causes runners to be terminated by the ALI unexpectedly when the API rate limit is reached and the ALI can no longer accessed the GitHub API until it resets hourly.

<img width="1116" alt="Screenshot 2024-11-18 at 08 45 42" src="https://github.com/user-attachments/assets/ba9fa549-f8d2-4312-9972-64365d6193d0">

**Comment by jeanschmidt** [comment] 2024-11-18 17:01
After investigation, we identified that the main reason for the excess requests to GHA API is the requests we perform to [get runner information](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#get-a-self-hosted-runner-for-a-repository) when we can't obtain information about a particular instance by [listing all runners in a repo](https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28#list-self-hosted-runners-for-a-repository).

This causes us to make thousands of requests (on per runner we have live) to the API. Details on the flow can be seen [here](https://github.com/pytorch/test-infra/blob/main/terraform-aws-github-runner/modules/runners/lambdas/runners/src/scale-runners/scale-down.ts#L331).

The issue started to happen on Friday, and can clearly be seen to continue to this time:
![Screenshot 2024-11-18 at 17 58 11](https://github.com/user-attachments/assets/a0d2bee4-7da0-40f1-8fb8-251ddd26774e)

No change was introduced from our side, so we suspect a change/bug in GHA API `repos/OWNER/REPO/actions/runners`.

**Comment by jeanschmidt** [comment] 2024-11-18 17:37
Mitigation actions:

I manually increased the `gh-ci-scale-down-rule` and `gh-ci-canary-scale-down-rule` EventBridge rules for scale-down lambda. Both in main and canary.

This will increase the running costs for our infra. But will reduce the impact of the API issues we're facing.

Please be aware if you are deploying terraform, so to make sure to maintain those rules updated.

**Comment by huydhn** [comment] 2024-11-18 17:45
You can disable the deployment workflow to prevent it from running until the issue is resolved I think.  I don't have the owner permission to do so.

**Comment by malfet** [comment] 2024-11-18 17:48
Am I correct at assuming that this has be caused by some recent change? Or perhaps by the fact that we are running scale-up and scale-down lambdas from two accounts which doubles the load?

**Comment by zxiiro** [comment] 2024-11-18 17:49
> Am I correct at assuming that this has be caused by some recent change? Or perhaps by the fact that we are running scale-up and scale-down lambdas from two accounts which doubles the load?

Each account has a separate GitHub App so they have their own separate limit of 15,000 API call.

**Comment by jeanschmidt** [comment] 2024-11-18 17:50
@huydhn thanks for the headsup, disabled the workflows

**Comment by jeanschmidt** [comment] 2024-11-18 18:28
Updates, we reached out to GH team, and they are working on this.

**Comment by jeanschmidt** [comment] 2024-11-18 22:16
Updates: GH team provisioned a fix, we're monitoring

**Comment by jeanschmidt** [comment] 2024-11-18 22:22
## Updates

graphs show improvements, logs also don't show that there is a bug.

## Actions taken:

Removed all the mitigation actions:

* Scale down back to run every 15mins in both AWS accounts;
* GHA that trigger a terraform release got re-enabled;

**Comment by jeanschmidt** [comment] 2024-11-18 22:23
I am now closing this issue and standing down.

**Closed** 2024-11-18 22:24 UTC
Labels: ci: sev
