### ISSUE TITLE
SAGEConv ONNX export

### ISSUE THREAD

**Issue by Shra1-25** [pytorch/pytorch#64769] opened 2021-09-09 18:43 UTC
## ❓ Questions and Help
Hello Everyone, So past few days I have been trying to run GNN using ONNX runtime (Python and eventually on C++). However I get the following error after I successfully export the onnx model from pytorch which uses pytorch geometric layers (SAGE Convolution to be precise) and functions for the GNNs. Before blaming the ONNX runtime I want to make sure that the ONNX exporter indeed FULLY supports SAGEConv conversion. When I try to run the converted ONNX model I get the following error: 

`InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Non-zero status code returned while running ScatterElements node. Name:'ScatterElements_26' Status Message: Indices dim=12 at pos=0 is greater than input dim=6`

## Further Information
Here is the code I used for pytorch model creation:
```python
#%debug
import torch
import torchvision
import torch_geometric
import torch.nn.functional as F
from torch.nn import Linear as Lin, Sequential as Seq, ReLU, AvgPool1d, Dropout, Softmax, Sigmoid, BatchNorm1d
from torch_geometric.nn import EdgeConv, DynamicEdgeConv, BatchNorm, avg_pool_x, knn_graph, EdgePooling, DenseSAGEConv, dense_diff_pool, dense_mincut_pool, SAGEConv, max_pool_x, SAGPooling, JumpingKnowledge, global_mean_pool as gap, global_max_pool as gmp
#from torch_cluster import knn_graph

#dummy_input = (torch.randn(10,5, device='cuda'),torch.randn(2,10, device='cuda').type(torch.int64))
coords0 = torch.randn(1,6)
coords1 = torch.randn(1,6)


coords = torch.transpose(torch.cat((coords0,coords1),dim=0),0,1)
adj = knn_graph(coords, k=2, batch=None, loop=True)

edge_from = adj[0:1,:]
edge_to = adj[1:,:]

input_values = (coords0,coords1, edge_from, edge_to)
#model = torchvision.models.alexnet(pretrained=True).cuda()
class trial1(torch.nn.Module):
    def __init__(self):
        super(trial1, self).__init__()
        
        self.SAGEConvBlock1 = SAGEConv(2, 512, normalize=True)
        self.bano1 = BatchNorm(512)
        self.relu = ReLU()
        self.dense1 = Seq(Lin(512,1))
        self.sigmoid = Sigmoid()
    def forward(self, coords0, coords1, edge_from, edge_to):
      adj = torch.cat((edge_from,edge_to),dim=0)
      gra = torch.transpose(torch.cat((coords0,coords1),dim=0),0,1)
      
      x1 = self.SAGEConvBlock1(gra, edge_index=adj)
      x = torch.unsqueeze(torch.sum(x1), dim=0)
      return x

model2 = trial1()

input_names = ["coords0","coords1", "edge_from", "edge_to"]
output_names = [ "outputs" ]

torch.onnx.export(model2, input_values, "ONNX_models/trial2.onnx", verbose=True, input_names=input_names, output_names=output_names, opset_version=11, dynamic_axes={'coords0':{0:'batch_size',1:'features'}, 'coords1':{0:'batch_size',1:'features'}, 'edge_from':{0:'batch_size',1:'features'}, 'edge_to':{0:'batch_size',1:'features'}, 'outputs':{0:'batch_size'}})
```

The onnx runtime code to perform the inference is:
```python
import onnxruntime
print(onnxruntime.__version__)
ort_session = onnxruntime.InferenceSession("ONNX_models/trial2.onnx")

def to_numpy(tensor):
    return tensor.detach().cpu().numpy() if tensor.requires_grad else tensor.cpu().numpy()

ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(coords0), ort_session.get_inputs()[1].name: to_numpy(coords1), ort_session.get_inputs()[2].name: to_numpy(edge_from), ort_session.get_inputs()[3].name: to_numpy(edge_to)}
ort_outs = ort_session.run(["outputs"], ort_inputs)
``` 

I get the error in the last line of the above code: 
`ort_outs = ort_session.run(["outputs"], ort_inputs)`

Also, there is no error and the inference runs perfectly fine when I remove the SAGEConv layer from the model. The technical issue is the dimension mismatch between gra (shape: [6,2] )  and adj (shape: [2,36] )  where apparently the gra.shape[0] should be equal to adj.shape[1]. And it indeed works if we use only the first 6 elements of the adj (shape: [2,6] ) which essentially is not what we would intend to do. For my application I need to have multiple inputs of shape ('batch_size',nodes) and edges of the shape ('batch_size', k*nodes) where k indicates the number of k nearest neighbours.

### Notes
I would really appreciate if someone has any leads on this or if anyone has successfully deployed a GNN on ONNX using different input dimensions (where rank of each input <= 2).

cc @BowenBao @neginraoof

**Comment by Shra1-25** [comment] 2021-09-09 18:43
To clarify, the issue is not with using different dimensional inputs, since when I remove the SAGEConv layer, I am able to run/execute the model with different input dimensions. It is only when I add the SAGEConv layer I get the error.
The issue is with the ScatterElement operation apparently being used within the SAGEConv module which causes the error. From what I gather Scatter elements uses data, indices and update. In my case, indices dim=k*nodes whereas input dim = node and them not being equal is causing the issue. Please advise. Thank you!

**Comment by jiafatom** [comment] 2021-09-10 21:10
@Shra1-25 In the script `coords0.shape=[1, 6]`, `coords1.shape=[1, 6]`, `edge_from.shape=[1, 12]`, `edge_to.shape=[1, 12]`, is this what you expected?
If so, then when you export the model and set `dynamic_axes`, you need use `'edge_from':{0:'batch_size',1:'features_1'}, 'edge_to':{0:'batch_size',1:'features_1'}` to distinguish from `features` because they are not equal.
And in this case, `adj.shape = [2, 12]`, `gra.shape = [6, 2]` where adj.shape[1] != gra.shape[0]

I did another experiment to make `edge_from.shape=[1, 6]`, `edge_to.shape=[1, 6]`, then everything works.

**Comment by Shra1-25** [comment] 2021-09-11 06:19
Hi @jiafatom, Thanks for your reply. 

> @Shra1-25 In the script `coords0.shape=[1, 6]`, `coords1.shape=[1, 6]`, `edge_from.shape=[1, 12]`, `edge_to.shape=[1, 12]`, is this what you expected?
Yes this is exactly what I expect. And this is indeed the case for the pytorch model.

> If so, then when you export the model and set dynamic_axes, you need use 'edge_from':{0:'batch_size',1:'features_1'}, 'edge_to':{0:'batch_size',1:'features_1'} to distinguish from features because they are not equal.
Thanks for the suggestion. However, I tried this and still get the same error.

>  And in this case, adj.shape = [2, 12], gra.shape = [6, 2] where adj.shape[1] != gra.shape[0]
Yes correct, this is exactly how it is supposed to be in SAGEConv nn layer of pytorch geometric and the pytorch model works perfectly fine in this case.

 > I did another experiment to make edge_from.shape=[1, 6], edge_to.shape=[1, 6], then everything works.
As I mentioned earlier, I do not want edge_from and edge_to shapes to be [1,6] because these together basically form the adjacent matrix to be fed to the SAGEConv layer. To define these edges I use knn_graph of pytorch geometric with k = 2,3,4. So each node will have 'k' neighbors and hence if the shape of coords0/coords1 is [1,6], then the shape of edge_from/edge_to has to be [ 1, 6*k ].

Could you please let me know if you have any further suggestions? Or if it really is a bug in the converter given that this works perfectly fine with Pytorch. Thanks again!

**Comment by garymm** [comment] 2021-11-20 01:37
@jiafatom could you please take another look next time you're on duty?

I'm trying to reproducing this using the tip of onnx_ms_1, but it's a bit annoying since I have to install torch_geometric from source, which doesn't seem to be working for me.

**Comment by jiafatom** [comment] 2021-11-22 18:26
I just tried this but seems not working now. I tried install torch_geometric from source too. 
With latest torch onnx_ms_1 branch, Now when 
`from torch_geometric.nn import BatchNorm, knn_graph, SAGEConv`
it shows 
```python
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)
```
If I use torch 1.10, then when I `import torch-geometric`, it shows
```python
    import torch_geometric
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/__init__.py", line 7, in <module>
    import torch_geometric.data
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/data/__init__.py", line 1, in <module>
    from .data import Data
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/data/data.py", line 3, in <module>
    from torch_geometric.typing import OptTensor, NodeType, EdgeType
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch_geometric/typing.py", line 4, in <module>
    from torch_sparse import SparseTensor
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch_sparse/__init__.py", line 16, in <module>
    f'{library}_{suffix}', [osp.dirname(__file__)]).origin)
  File "/home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch/_ops.py", line 110, in load_library
    ctypes.CDLL(path)
  File "/home/david/anaconda3/envs/py37/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/david/anaconda3/envs/py37/lib/python3.7/site-packages/torch_sparse/_version_cuda.so: undefined symbol: _ZN5torch3jit17parseSchemaOrNameERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```
@Shra1-25 What is the environment you are using? Could you try torch 1.10 to see what the error is?

**Comment by thiagocrepaldi** [comment] 2022-01-24 19:15
It’s been over 2 months, so closing this. Feel free to open another one.

**Closed by thiagocrepaldi** 2022-01-24 19:15 UTC
Labels: module: onnx, triaged, onnx-needs-info
