### ISSUE TITLE
Warning when instantiating quantized model

### ISSUE THREAD

**Issue by z-a-f** [pytorch/pytorch#29538] opened 2019-11-11 04:44 UTC
## 🐛 Bug

When instantiating a quantized model, a warning pops up saying

![image](https://user-images.githubusercontent.com/4216323/68561371-21ae4d80-03fa-11ea-9a5e-68eff371b741.png)

```console
torch/quantization/observer.py:131: UserWarning: must run observer before calling calculate_qparams.                                    Returning default scale and zero point 
```

If the model is already quantized, I don't think this warning serves any purpose but pollute the terminal and confuse the user

## To Reproduce

```python
>>> from torchvision.models import quantization as models
>>> q_model = models.mobilenet_v2(pretrained=True, progress=True, quantize=True)  
```

## Expected behavior

If the model is already quantized (that is the `quantize=True` is set), there are no mode observers. This warning should be suppressed, and only be shown when the user actually  fails to run observers before converting the model

## Environment

```console
$> python ~/Git/pytorch/torch/utils/collect_env.py 
Collecting environment information...
PyTorch version: 1.4.0.dev20191110
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce GT 730

Nvidia driver version: 430.50
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.0

Versions of relevant libraries:
[pip3] numpy==1.17.3
[pip3] torch==1.4.0.dev20191110
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.4.0
[pip3] torchvision==0.5.0.dev20191110
[pip3] torchviz==0.0.1
[conda] Could not collect

```

cc @jerryzh168 @jianyuh @dzhulgakov @raghuramank100 @jamesr66a

**Comment by sheikmohdimran** [comment] 2019-11-15 04:19
Unable to recreate with the latest nightly

```
>>> from torchvision.models import quantization as models
>>> q_model = models.mobilenet_v2(pretrained=True, progress=True, quantize=True)
>>> import torch
>>> torch.__version__
'1.4.0.dev20191112'

```

**Environment**

```
Collecting environment information...
PyTorch version: 1.4.0.dev20191112
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: Could not collect

Python version: 3.7
Is CUDA available: No
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce GTX 1080

Nvidia driver version: 384.130
cuDNN version: Could not collect

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.4.0.dev20191112
[pip] torchvision==0.5.0a0+bfd4b2a
[conda] blas                      1.0                         mkl
[conda] mkl                       2019.3                      199
[conda] mkl_fft                   1.0.12           py37ha843d7b_0
[conda] mkl_random                1.0.2            py37hd81dba3_0
[conda] pytorch                   1.4.0.dev20191112 py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch-nightly
[conda] torchvision               0.5.0.dev20191112      py37_cu101    pytorch-nightly

```

**Comment by raghuramank100** [comment] 2019-11-22 23:58
@z-a-f : Can you confirm if this issue is not reproducible?. If so, please close it.

**Comment by z-a-f** [comment] 2020-01-13 22:23
I can still repro

```python
>>> from torchvision.models import quantization as models
>>> q_model = models.mobilenet_v2(pretrained=True, progress=True, quantize=True)
# /Users/zaf/Git/pytorch-is-quantized-docs/torch/quantization/observer.py:180: UserWarning: Must run observer before calling calculate_qparams.                           Returning default scale and zero point.
  Returning default scale and zero point.")
>>> import torchvision
>>> torchvision.__version__
# '0.5.0a0+66f2922'
>>> import torch
>>> torch.__version__
# '1.5.0a0+3490cd3'
```

**Comment by vkuzo** [comment] 2021-12-27 18:07
This is happening because 
1. torchvision's quantizeable MobileNetV2 has the option to add skip connections (https://github.com/pytorch/vision/blob/main/torchvision/models/quantization/mobilenetv2.py#L26)
2. the skip connections are implemented using `FloatFunctional`, in order to work with Eager mode quantization
3. the config used in this issue has skip connections turned off
4. the qconfig is still applied to the `FloatFunctional` modules, because Eager mode has no knowledge of the graph
5. the warning is thrown because calibrated data never entered skip connections

I'd say this warning is working as expected from POV of quantization, there were observers in the model which were never hit during calibration.  If there is a need to remove this warning, a fix the torchvision repo could do is set qconfig to None for the skip connections if the skip connection setting is turned off.

**Closed by vkuzo** 2021-12-27 18:07 UTC
Labels: oncall: quantization, triaged
