### ISSUE TITLE
[libtorch] torch::stack error

### ISSUE THREAD

**Issue by cindycia** [pytorch/pytorch#15037] opened 2018-12-11 01:59 UTC
I am trying to stack two tensors in the first dimension through the following code:

	torch::Tensor ch1 = torch::ones({1,32,32}, at::kFloat);

	torch::Tensor ch23 = torch::ones({2,32,32}, at::kFloat);

	torch::Tensor result = torch::stack({ch1, ch23}, 0);

But it gives me this error:

> 
> terminate called after throwing an instance of 'std::runtime_error'
>   what():  invalid argument 0: Sizes of tensors must match except in dimension 0. Got 1 and 2 in dimension 1
> 

What have I done wrong?

**Comment by vishwakftw** [comment] 2018-12-11 02:08
Assuming you require a result tensor if size (3, 32, 32), try using torch::cat.

**Comment by cindycia** [comment] 2018-12-11 02:11
> Assuming you require a result tensor of size (3, 32, 32), try using torch::cat.

Yes, cat works. Thanks a lot.

**Comment by vishwakftw** [comment] 2018-12-11 02:13
If the issue is resolved, please close it :)

Also, the forums (discuss.pytorch.org) will be able to help you out with questions like these faster.

**Closed** 2018-12-11 02:15 UTC

**Comment by cindycia** [comment] 2018-12-11 02:20
> If the issue is resolved, please close it :)
> 
> Also, the forums (discuss.pytorch.org) will be able to help you out with questions like these faster.

I see. Thanks.
