### ISSUE TITLE
Question/Possible bug with ddp/DistributedDataParallel accessing a parameter.data field

### ISSUE THREAD

**Issue by sneiman** [pytorch/pytorch#35858] opened 2020-04-02 01:30 UTC
I have run into a strange problem using DistributedDataParallel. I have solved it - but this looks like a bug to me. 

The error I am getting is:
```
... in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep
```

This occurs during the spawn() call from pytorch-lightning. The model I am using works in all other modes, and an identical model, trainer setup works in ddp, too.

After some hair pulling, I found the problem. During the construction of the new model, and before creating trainer, etc, I store the .data property of a Parameter:

```
self.class_p        = nn.Parameter(torch.Tensor(np.ones(self.data.num_classes) * np.log(1.0)), requires_grad=True)
self.class_p_t      = self.class_p.data # this is the offending line
```
I do NOT actually do anything with self.class_p_t - I assigned it in anticipation of logging these values to monitor progress of self learning curriculum learning class weights.

If the assignment above is present, I get the above failure. Without it, things work fine.

If this is something you expect, I'd appreciate knowing why - if it's a bug, thought you'd like to know.

For the record:Ubuntu 19.10, python 3.7.5, pytorch 1.4, venv, pytorch-lightning 0.7.1
Note that this is a fully up to date ubuntu ...

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @xush6528 @osalpekar

**Comment by mrshenli** [comment] 2020-04-06 17:12
@sneiman 

> This occurs during the spawn() call from pytorch-lightning. 

Can you trace which line in DDP throw that error, is it in DDP constructor or the backward pass?

> If the assignment above is present, I get the above failure. Without it, things work fine.

Would I be correct if I assume `self.class_p_t ` does not participate in the backward pass? If so, then you have a model with unused parameters. Can you try if setting [`find_unused_parameters=True`](https://pytorch.org/docs/stable/nn.html#torch.nn.parallel.DistributedDataParallel) work for you?

**Comment by sneiman** [comment] 2020-04-07 17:58
It is actually inside the pytorch `spawn()` call made within the `Trainer.fit()` call of pytorch-lightning:
`mp.spawn(self.ddp_train, nprocs=self.num_gpus, args=(model,))`. Please note that without the offending assignment, this works fine in all modes. And with it, it works fine in all modes except DDP.

I suppose this could be in pytorch-lightning - but it doesn't look like it at this point.

pytorch-lightning does the wrap - and does it with `find_unused_parameters=True`. Note that `LightningDistributedParallel()` inherits from `DistributedDataParallel()`
```
        model = LightningDistributedDataParallel(
            model,
            device_ids=device_ids,
            find_unused_parameters=True
        )
        return model
```
Here is the entire error trace from when this occurs. I have added a few comments to make things a little clearer (I hope):
```
  File "./gaze_11p.py", line 737, in <module>
    start(parser.parse_args())             # in my __main__
  File "./gaze_11p.py", line 671, in start
    trainer.fit(model)                     # in the above referenced 'start()'

# from here on we are in the pytorch_lightning, torch, and python 3.7 world
# at the point this spawn() call is made, the model has been constructed, 
# and is now being launched for ddp. ddp_train is the process function
# that pytorch_lightning uses for training. NOTE that the
# failure occurs BEFORE ddp_train is invoked ...

  File "/home/seth/dev/ptl-master.sn/pytorch_lightning/trainer/trainer.py", line 601, in fit
    mp.spawn(self.ddp_train, nprocs=self.num_gpus, args=(model,))
  File "/usr/local/lib/python3.7/dist-packages/torch/multiprocessing/spawn.py", line 162, in spawn
    process.start()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 59, in _launch
    cmd, self._fds)
  File "/usr/lib/python3.7/multiprocessing/util.py", line 432, in spawnv_passfds
    False, False, None)
ValueError: bad value(s) in fds_to_keep
```

Let me know if this inspires more questions. I would rather not work on creating a small model to reproduce unless you really need it ... swamped right now.

**Comment by sneiman** [comment] 2020-04-07 18:32
It was easier than I thought.
Here is a tiny file which will reproduce the error.
Copy it, rename it repro_error.py, set chmod to 755.
Check that you have a version of python 3 called python3.
Create a virtual environment, install pytorch-lightinig with `pip install pytorch-lightning`
Execute with ./repro_error.py

[repro_error.txt](https://github.com/pytorch/pytorch/files/4446405/repro_error.txt)

**Comment by mrshenli** [comment] 2020-04-07 19:48
@sneiman 

Thanks a lot for the repro. I will pull in lighting folks and investigate. I am not familiar with lighting, but from what I can see in the code, the following looks weird to me:

```python
class min_model():
    def __init__(self):

        self.class_p        = nn.Parameter(torch.Tensor(np.ones(81) * np.log(1.0)), requires_grad=True)
        self.class_p_t      = self.class_p.data
 
    def prepare_data(self):
        pass
```

This model does not even need to inherit from `nn.Module` and `implement` a `forward` function? How would DDP then loop over model parameters and check forward outputs? Maybe lighting is doing some super smart stuff.

**Comment by sneiman** [comment] 2020-04-07 22:01
Sorry if I was unclear. Yes - this is a completely stripped out model The reason it doesn't need those things is because the **failure occurs before it ever gets to the things you are talking about**. Take a close look at the trace - I was able to keep stripping things  away - and still get this error. Thought you would prefer the minimum ...

**Comment by sneiman** [comment] 2020-04-07 22:19
In case you are concerned that this tiny file is introducing the error, here is the entire file. You won't be able to run as it include some utilities and building blocks that you don't have. But just to put you mind at ease ...
[gaze_11p.txt](https://github.com/pytorch/pytorch/files/4447244/gaze_11p.txt)

**Comment by sneiman** [comment] 2020-04-08 15:22
Here is a version without pytorch-lightning that causes the same error. It is based on the ToyModel() tutorial for ddp (https://pytorch.org/tutorials/intermediate/ddp_tutorial.html?highlight=ddp)

Note that I have altered it slightly to follow the pattern of creation and spawning in pytorch-lightning. The model is created before the spawn() call, and the spawned function does the cuda move, etc. Line 39 has the offending assignment.

Hope this helps
[repro_error_noptl.txt](https://github.com/pytorch/pytorch/files/4451327/repro_error_noptl.txt)

**Comment by sneiman** [comment] 2020-04-08 16:00
Just updated the file - it had a bug in it that did not affect the error - just didn't want you to waste time fixing it.

**Comment by mrshenli** [comment] 2020-04-08 19:44
Confirm that I can reproduce the error. Checking.

**Comment by mrshenli** [comment] 2020-04-08 20:14
Looks like this is a multiprocessing issue. If I change the deepcopy the model before passing it to the subprocess, it worked.

```python
    mp.spawn(demo_fn,
             args=(copy.deepcopy(model), world_size,),
             nprocs=world_size,
             join=True)
```

It also works if I use multiprocessing Queue to pass the model:

```python
def demo_basic(rank, queue, world_size):
    model = copy.deepcopy(queue.get())
    print(f'entering demo_basic {rank}')
    setup(rank, world_size)


    # lets use 2 gpus not all of them
    n = 2 // world_size
    device_ids = list(range(rank * n, (rank + 1) * n))

    model.to(rank)
    ddp_model  = DDP(model, device_ids=[rank], find_unused_parameters=True)
    loss_fn    = nn.MSELoss()
    optimizer  = optim.SGD(ddp_model.parameters(), lr=0.001)

    optimizer.zero_grad()
    outputs    = ddp_model(torch.randn(20, 10))
    labels     = torch.randn(20, 5).to(rank)
    loss_fn(outputs, labels).backward()
    optimizer.step()

    cleanup()
    print(f'leaving demo_basic {rank}')


def run_demo(demo_fn, world_size):
    model = ToyModel()

    context = mp.get_context("spawn")
    queue = context.Queue()
    queue.put(model)
    queue.put(model)
    mp.spawn(demo_fn,
             args=(queue, world_size,),
             nprocs=world_size,
             join=True)
```

IIUC, there were two problems with the repro script:

1. The shm is not setup properly if we directly pass the model as parameter to multiple sub-processes, which caused the error.
2. Even if 1 is passed, two DDP processes cannot operate on the same model replica.

**Comment by mrshenli** [comment] 2020-04-08 21:21
@sneiman since this does not seem to be a bug, I am closing this issue for now. Please feel free to reopen if you believe sth needs to be fixed in PyTorch. Thanks!

**Closed by mrshenli** 2020-04-08 21:21 UTC
Labels: module: multiprocessing, triaged

**Comment by sneiman** [comment] 2020-04-08 23:24
Thanks for running this down. The question in my mind is whether or not pytorch-lightning is making the same error - as the ToyModel() version was just my quick attempt to duplicate what it does when using ddp. I will investigate ..

But to be clear - you think that the shallow copy of a model created outside of the function passed to spawn is the problem. Either create the model inside the function passed to spawn, or deepcopy it or send it by queue. Do I have that right?

**Comment by mrshenli** [comment] 2020-04-09 15:08
> you think that the shallow copy of a model created outside of the function passed to spawn is the problem. Either create the model inside the function passed to spawn, or deepcopy it or send it by queue. 

Yes, shallow copy of the model wouldn't work properly with DDP, as there will be multiple processes trying to move and update the same set of parameters. Even if it didn't crash, I would assume the result is not correctly.

Besides that, another issue is multiprocessing shared memory. In the code above, I explicitly use `multiprocessing.Queue` to pass the same model instance to two DDP processes, which will put the model in shared memory. Directly passing the model object to `args` would crash. Not sure if I understand this correctly, but it seems like `args` can handle memory space between the parent process and **one** child process correctly, but would fail if there are multiple children processes. Using `multiprocssing.Queue` worked in this case.

**Comment by mrshenli** [comment] 2020-04-09 15:11
cc @williamFalcon for PyTorch-Lightening discussion

**Comment by sneiman** [comment] 2020-04-09 16:29
Just verifying - in the real model that causes this problem, taking a lesson from your investigation guided me to the fix. This is **NOT** a pytorch-lightning bug. It is caused by the naive assignment of an already created Parameter to another class variable. When the model is moved to the appropriate gpu, the reference is not updated, as pytorch has no way of knowing it should be. It thus refers to memory in another process space, hence the mp fault. Fixed by doing a deepcopy() when assigning to the new variable.

**Comment by williamFalcon** [comment] 2020-04-09 16:31
good!

**Comment by sneiman** [comment] 2020-04-28 14:19
Users of pytorch lightning ddp mode and `spectral_norm()` are having the same problem - ie, getting this error (pytorch lightning issue 1550). Looks to me like the 'to clone/not to clone' decision within `spectral_norm()` does not take into account the use of pytorch multi-processing's `spawn()`. **Not certain**, as I do not have time to fully explore the mp behavior details. But definitely a problem for ptl users of ddp and `spectral_norm()` without any naive assignments as above.
