### ISSUE TITLE
torch.compile report torch._dynamo.exc.InternalTorchDynamoError: No module named 'nvi' when using customized triton kernel

### ISSUE THREAD

**Issue by arthursunbao** [pytorch/pytorch#125896] opened 2024-05-10 03:15 UTC
### 🐛 Describe the bug

@ezyang  @oulgen 

Hi Ed and oulgen,

Can you kindly help to take a look at this problem?

I tried to uninstall triton and pytorch-triton but it still seems to have this problem like in this thread: https://github.com/pytorch/pytorch/issues/125539

```
import torch
from torch.utils._triton import has_triton


if not has_triton():
    print("Skipping because triton is not supported on this device.")
else:
    import triton
    from triton import language as tl

@triton.jit
def _layer_norm_fwd_fused(
    X,  # pointer to the input
    Y,  # pointer to the output
    W,  # pointer to the weights
    B,  # pointer to the biases
    Mean,  # pointer to the mean
    Rstd,  # pointer to the 1/std
    stride,  # how much to increase the pointer when moving by 1 row
    N,  # number of columns in X
    eps,  # epsilon to avoid division by zero
    BLOCK_SIZE: tl.constexpr,
):
    # Map the program id to the row of X and Y it should compute.
    row = tl.program_id(0)
    Y += row * stride
    X += row * stride
    # Compute mean
    mean = 0
    _mean = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        a = tl.load(X + cols, mask=cols < N, other=0.).to(tl.float32)
        _mean += a
    mean = tl.sum(_mean, axis=0) / N
    # Compute variance
    _var = tl.zeros([BLOCK_SIZE], dtype=tl.float32)
    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        x = tl.load(X + cols, mask=cols < N, other=0.).to(tl.float32)
        x = tl.where(cols < N, x - mean, 0.)
        _var += x * x
    var = tl.sum(_var, axis=0) / N
    rstd = 1 / tl.sqrt(var + eps)
    # Write mean / rstd
    tl.store(Mean + row, mean)
    tl.store(Rstd + row, rstd)
    # Normalize and apply linear transformation
    for off in range(0, N, BLOCK_SIZE):
        cols = off + tl.arange(0, BLOCK_SIZE)
        mask = cols < N
        w = tl.load(W + cols, mask=mask)
        b = tl.load(B + cols, mask=mask)
        x = tl.load(X + cols, mask=mask, other=0.).to(tl.float32)
        x_hat = (x - mean) * rstd
        y = x_hat * w + b
        # Write output
        tl.store(Y + cols, y, mask=mask)

def forward(x, normalized_shape, weight, bias, eps):
    # allocate output
    y = torch.empty_like(x)
    # reshape input data into 2D tensor
    x_arg = x.reshape(-1, x.shape[-1])
    M, N = x_arg.shape
    mean = torch.empty((M, ), dtype=torch.float32, device='cuda')
    rstd = torch.empty((M, ), dtype=torch.float32, device='cuda')
    # Less than 64KB per feature: enqueue fused kernel
    MAX_FUSED_SIZE = 65536 // x.element_size()
    BLOCK_SIZE = min(MAX_FUSED_SIZE, triton.next_power_of_2(N))
    if N > BLOCK_SIZE:
        raise RuntimeError("This layer norm doesn't support feature dim >= 64KB.")
    # heuristics for number of warps
    num_warps = min(max(BLOCK_SIZE // 256, 1), 8)
    # enqueue kernel
    _layer_norm_fwd_fused[(M, )](  #
        x_arg, y, weight, bias, mean, rstd,  #
        x_arg.stride(0), N, eps,  #
        BLOCK_SIZE=BLOCK_SIZE, num_warps=num_warps, num_ctas=1)
    return y


eps=1e-5
dtype = torch.float16
x_shape = (1151, 8192)
w_shape = (x_shape[-1], )
weight = torch.rand(w_shape, dtype=dtype, device='cuda', requires_grad=True)
bias = torch.rand(w_shape, dtype=dtype, device='cuda', requires_grad=True)
x = -2.3 + 0.5 * torch.randn(x_shape, dtype=dtype, device='cuda')
dy = .1 * torch.randn_like(x)
x.requires_grad_(False)
# forward pass
forward = torch.compile(forward)
y_tri = forward(x, w_shape, weight, bias, eps)
```

reports the following error:
```
(env-novelai) [jasonbsun@9-165-213-52 /data/ComfyUI]$ TORCH_LOGS=dynamic TORCH_COMPILE_DEBUG=1 python  layernorm_demo.py 
W0510 11:07:18.859660 140103935530816 torch/_inductor/debug.py:414] [0/0_2] model__0_inference_0 debug trace: /data/ComfyUI/torch_compile_debug/run_2024_05_10_11_07_18_657237-pid_273696/torchinductor/model__0_inference_0.0
I0510 11:07:18.865029 140103935530816 torch/fx/experimental/symbolic_shapes.py:3326] [0/0_2] produce_guards
I0510 11:07:18.870723 140103935530816 torch/fx/experimental/symbolic_shapes.py:3326] [1/0_1] produce_guards
I0510 11:07:18.888381 140103935530816 torch/fx/experimental/symbolic_shapes.py:3326] [2/0_1] produce_guards
I0510 11:07:18.906366 140103935530816 torch/fx/experimental/symbolic_shapes.py:3326] [3/0_1] produce_guards
I0510 11:07:18.923733 140103935530816 torch/fx/experimental/symbolic_shapes.py:3326] [4/0_1] produce_guards
Traceback (most recent call last):
  File "/data/ComfyUI/layernorm_demo.py", line 94, in <module>
    y_tri = forward(x, w_shape, weight, bias, eps)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/eval_frame.py", line 420, in _fn
    return fn(*args, **kwargs)
  File "/data/ComfyUI/layernorm_demo.py", line 76, in forward
    _layer_norm_fwd_fused[(M, )](  #
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/triton/runtime/jit.py", line 207, in <lambda>
    return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/triton/runtime/jit.py", line 388, in run
    device = driver.active.get_current_device()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/triton/runtime/jit.py", line 389, in torch_dynamo_resume_in_run_at_388
    stream = driver.active.get_current_stream(device)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/triton/runtime/jit.py", line 390, in torch_dynamo_resume_in_run_at_389
    target = driver.active.get_current_target()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 981, in catch_errors
    return callback(frame, cache_entry, hooks, frame_state, skip=1)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 822, in _convert_frame
    result = inner_convert(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 410, in _convert_frame_assert
    return _compile(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_utils_internal.py", line 70, in wrapper_function
    return function(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 732, in _compile
    raise InternalTorchDynamoError(str(e)).with_traceback(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 703, in _compile
    guarded_code = compile_inner(code, one_graph, hooks, transform)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/utils.py", line 273, in time_wrapper
    r = func(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 570, in compile_inner
    out_code = transform_code_object(code, transform)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/bytecode_transformation.py", line 1167, in transform_code_object
    transformations(instructions, code_options)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 172, in _fn
    return fn(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/convert_frame.py", line 517, in transform
    tracer.run()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2234, in run
    super().run()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 884, in run
    while self.step():
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 799, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in wrapper
    return inner_fn(self, inst)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1253, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 737, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/lazy.py", line 132, in realize_and_forward
    return getattr(self.realize(), name)(*args, **kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2448, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2564, in inline_call_
    tracer.run()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 884, in run
    while self.step():
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 799, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 494, in wrapper
    return inner_fn(self, inst)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1253, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 737, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/user_defined.py", line 392, in call_function
    var.call_method(tx, "__init__", args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/user_defined.py", line 638, in call_method
    return UserMethodVariable(method, self, source=source).call_function(
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 339, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 293, in call_function
    return super().call_function(tx, args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/variables/functions.py", line 90, in call_function
    return tx.inline_user_function_return(self, [*self.self_args(), *args], kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 743, in inline_user_function_return
    return InliningInstructionTranslator.inline_call(self, fn, args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2448, in inline_call
    return cls.inline_call_(parent, func, args, kwargs)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2564, in inline_call_
    tracer.run()
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 884, in run
    while self.step():
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 799, in step
    self.dispatch_table[inst.opcode](self, inst)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2748, in LOAD_GLOBAL
    _, fglobals_vt, global_source = self.get_globals_source_and_value(name)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 2719, in get_globals_source_and_value
    module_source = self.import_source(module_name)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/site-packages/torch/_dynamo/symbolic_convert.py", line 1029, in import_source
    value = importlib.import_module(module_name)
  File "/data/miniconda3/envs/env-novelai/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
torch._dynamo.exc.InternalTorchDynamoError: No module named 'nvi'
```

### Versions

torch   2.4.0.dev20240508+cu121
torchvision    0.19.0.dev20240416+cu121
pytorch-triton               3.0.0+45fff310c8
triton                       2.3.0

**Comment by oulgen** [comment] 2024-05-10 03:46
This is being tracked under https://github.com/pytorch/pytorch/issues/125807 closing this issue since it is identical.

The gist is `CudaUtils` is coming from triton which appears to be in a module called `nvi` but there's no module called nvi inside triton.

**Closed by oulgen** 2024-05-10 03:46 UTC

**Comment by arthursunbao** [comment] 2024-05-10 06:24
> This is being tracked under #125807 closing this issue since it is identical.
> 
> The gist is `CudaUtils` is coming from triton which appears to be in a module called `nvi` but there's no module called nvi inside triton.

Hi,  is there any timeline for fixing this?

**Comment by oulgen** [comment] 2024-05-10 07:07
I plan on fixing it but since the root cause is not clear, I cannot promise a timeline.

**Comment by oulgen** [comment] 2024-05-10 17:07
@arthursunbao Just FYI, in your repro, removing the num_ctas=1 fixes the problem. Investigating why.

**Comment by oulgen** [comment] 2024-05-13 17:11
@arthursunbao https://github.com/pytorch/pytorch/pull/126083 fixes this issue
