### ISSUE TITLE
Generated installation command points to non existent version

### ISSUE THREAD

**Issue by jozefchutka** [pytorch/pytorch#54172] opened 2021-03-17 16:27 UTC
## 🐛 Bug

https://pytorch.org/ installation command for windows does not work

## To Reproduce

1. visit https://pytorch.org/
2. pick option stable+window+pip+python+cuda 10.2
3. following command is generated `pip install torch==1.8.0+cu102 torchvision==0.9.0+cu102 torchaudio===0.8.0 -f https://download.pytorch.org/whl/torch_stable.html`
4. when executed on windows with python 3.8 following error occurs:
```
ERROR: Could not find a version that satisfies the requirement torch==1.8.0+cu102 (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2, 1.4.0, 1.4.0+cpu, 1.4.0+cu92, 1.5.0, 1.5.0+cpu, 1.5.0+cu101, 1.5.0+cu92, 1.5.1, 1.5.1+cpu, 1.5.1+cu101, 1.5.1+cu92, 1.6.0, 1.6.0+cpu, 1.6.0+cu101, 1.7.0, 1.7.0+cpu, 1.7.0+cu101, 1.7.0+cu110, 1.7.1, 1.7.1+cpu, 1.7.1+cu101, 1.7.1+cu110, 1.8.0, 1.8.0+cpu, 1.8.0+cu101, 1.8.0+cu111)       
ERROR: No matching distribution found for torch==1.8.0+cu102
```

however `torch==1.8.0+cu101` works ok

## Expected behavior

generated command should provide only valid options

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @mszhanyi @skyline75489

**Comment by rgommers** [comment] 2021-11-12 17:41
This is a bug in the install instructions on the website. The files on https://download.pytorch.org/whl/torch_stable.html are named:
```
cu101/torch-1.8.0%2Bcu101-cp38-cp38-win_amd64.whl
cu102/torch-1.8.0-cp38-cp38-win_amd64.whl
cu111/torch-1.8.0%2Bcu111-cp39-cp39-win_amd64.whl
```
It looks like what is happening here is that the CUDA 10.2 versions don't have `+cu102` because for Linux that is the wheel tthat gets uploaded to PyPI. Makes sense, however on Windows the CPU rather than the CUDA 10.2 wheels go on PyPI. For Linux the instructions are not wrong, because toggling Windows to Linux for CUDA 10.2 gives `pip3 install torch` rather than `pip3 install torch==1.10.0+cu102 -f https://download.pytorch.org/whl/cu102/torch_stable.html`.

Still broken for `1.10.0`.

**Comment by rgommers** [comment] 2021-11-12 17:59
Also, this is a duplicate of gh-52662, so I'll close this issue and move my comment there.

**Closed by rgommers** 2021-11-12 17:59 UTC
Labels: module: windows, triaged
