### ISSUE TITLE
torch.eye(..., out=t) / nn.init.eye_ does not work on MPS for tensor slices

### ISSUE THREAD

**Issue by PiotrCzapla** [pytorch/pytorch#92098] opened 2023-01-12 19:52 UTC
### 🐛 Describe the bug

When a tensor is a slice / view, the nn.init.eye_ fails without error or notice.
Here is a minimal example:
```py
import torch
t = torch.zeros(1,3,3).to('mps')
nn.init.eye_(t[0]) # this leaves the t set to zeros
print('eye on mps:\n', t[0])  

t = torch.zeros(1,3,3).to('cpu')
nn.init.eye_(t[0]) # this works
print('eye on cpu:\n', t[0])
```

Here is the output of the script above:
```
eye on mps:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='mps:0')
eye on cpu:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
```

### Versions

Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0.1 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.8 (main, Nov 24 2022, 08:08:27) [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] lovely-numpy==0.2.5
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.5
[pip3] torch==1.13.0
[pip3] torchaudio==0.13.0
[pip3] torcheval==0.0.5
[pip3] torchtnt==0.0.4
[pip3] torchvision==0.14.0
[conda] lovely-numpy              0.2.5                    pypi_0    pypi
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] torch                     1.13.0                   pypi_0    pypi
[conda] torchaudio                0.13.0                   pypi_0    pypi
[conda] torcheval                 0.0.5                    pypi_0    pypi
[conda] torchtnt                  0.0.4                    pypi_0    pypi
[conda] torchvision               0.14.0                   pypi_0    pypi

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by drisspg** [comment] 2023-01-13 00:30
I tried to reproduce on my m1 mac using PyTorch master and I was unable to reproduce. Could you try that. I am going to close the issue for now.

**Closed by drisspg** 2023-01-13 00:30 UTC
Labels: needs reproduction, module: mps
