### ISSUE TITLE
Converting from IValue to double gives INTERNAL ASSERT failure

### ISSUE THREAD

**Issue by gautams3** [pytorch/pytorch#21882] opened 2019-06-17 22:48 UTC
## 🐛 Bug

Simple unit test to show how I get an internal assertion failure when converting from at::Tensor to double.

## To Reproduce

1. Compile this code, which tries to convert a vector of IValue to a vector of float

```cpp
/**
compile and run this gtest to get the internal assertion failure 
(I used `catkin build --make-args tests` inside my ROS package, you could any other tool)
**/
#include "gtest/gtest.h"
#include <ros/package.h>
#include <torch/script.h>
#include <vector>

namespace {
  TEST(TorchTest, TorchTest_TensorIValueCompare_Test) {
    std::vector<float> inputs_vec(21, 1.0);

    // Create a vector of inputs
    torch::Tensor my_tensor = torch::tensor(inputs_vec);
    std::vector<float> v1(my_tensor.data<float>(), my_tensor.data<float>() + my_tensor.numel());
 
    std::cout << "tensor vector: " << v1 << std::endl;

    //Get vector from blob
    std::vector<torch::jit::IValue> my_jit_vec;
    my_jit_vec.push_back(torch::from_blob(inputs_vec.data(), { 1, 21 }).cuda());
    std::vector<float> v2;

    for (auto i = 0; i < my_jit_vec.size(); i++)
    {
      v2.push_back(my_jit_vec[i].toDouble());
    }
    std::cout << "from blob vector: " << v2 << std::endl;

    EXPECT_EQ(v1, v2);
  }
}

GTEST_API_ int main(int argc, char **argv) {
  printf("Running main() from %s\n", __FILE__);
  testing::InitGoogleTest(&argc, argv);
  return RUN_ALL_TESTS();
}
```
2. Observe an error message similar to this

> Running main() from <path>/torch_tensor_ivalue.cpp 
> [==========] Running 1 test from 1 test case.
> [----------] Global test environment set-up.
> [----------] 1 test from TorchTest
> [ RUN      ] TorchTest.TorchTest_TensorIValueCompare_Test
> tensor vector: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
> unknown file: Failure
> C++ exception with description "isDouble() **INTERNAL ASSERT FAILED** at <path>/pytorch/torch/include/ATen/core/ivalue.h:161, **please report a bug to PyTorch**.  (toDouble at <path>/pytorch/torch/include/ATen/core/ivalue.h:161)
> frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6c (0x7f698232465c in /home/gautam/catkin_ws/src/pytorch/build/lib.linux-x86_64-2.7/torch/lib/libc10.so)

## Expected behavior

Test should pass

## Environment
PyTorch version: 1.2.0a0+fc3f702
Is debug build: No
CUDA used to build PyTorch: 10.1.105

OS: Linux Mint 19.1 Tessa
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 2.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: GPU 0: Quadro M2000
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.4
[pip] torch==1.2.0a0+fc3f702
[pip] torchvision==0.3.0
[conda] Could not collect

## Additional context
I built pytorch from source (following instructions on pytorch.org)

**Comment by driazati** [comment] 2019-06-27 23:51
The `.to...` methods don't do any conversion, you'll have to cast the IValue to a tensor `.toTensor()` then get the value out.

**Comment by suo** [comment] 2019-11-21 23:59
Closing this as this is intended behavior.

**Closed by suo** 2019-11-21 23:59 UTC
Labels: jit, topic: assert failure
