### ISSUE TITLE
Deterministic implementation of cumsum

### ISSUE THREAD

**Issue by Luedman** [pytorch/pytorch#135021] opened 2024-09-03 15:10 UTC
### 🚀 The feature, motivation and pitch

I got this error: 
> cumsum_cuda_kernel does not have a deterministic implementation, but you set 'torch.use_deterministic_algorithms(True)'. You can turn off determinism just for this operation, or you can use the 'warn_only=True' option, if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.

I would be great to have a deterministic implementation for that because I want to use it for reconstructing time series from increments generated by the ML model. 

cc @mruberry @kurtamohler

**Comment by kurtamohler** [comment] 2024-10-09 22:39
Duplicate of #89492

**Closed by kurtamohler** 2024-10-09 22:39 UTC
Labels: triaged, module: determinism
