### ISSUE TITLE
Segmentation fault in functional.adaptive_avg_pool2d

### ISSUE THREAD

**Issue by mjkim720** [pytorch/pytorch#42509] opened 2020-08-04 04:18 UTC
## 🐛 Bug

`torch.nn.functional.adaptive_avg_pool2d` causes a segmentation fault when the parameter `output_size` is an empty tuple, `()` or an empty array `[]`.

## To Reproduce
```python
import pytorch

torch.nn.functional.adaptive_avg_pool2d(torch.tensor([1,2,3,4,5]), ())
```

## Expected behavior

Proper error handling for an empty tuple or empty array like `adaptive_avg_pool1d`.

## Environment
PyTorch version: 1.5.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.4 LTS
GCC version: Could not collect
CMake version: version 3.14.0

Python version: 3.7
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.18.1
[pip] torch==1.5.0
[pip] torchvision==0.6.0a0+82fd1c8
[conda] blas 1.0 mkl
[conda] cudatoolkit 10.1.243 h6bb024c_0
[conda] mkl 2020.1 217
[conda] mkl-include 2020.1 217
[conda] mkl-service 2.3.0 py37he904b0f_0
[conda] mkl_fft 1.0.15 py37ha843d7b_0
[conda] mkl_random 1.1.0 py37hd6b4f25_0
[conda] numpy 1.18.1 py37h4f9e942_0
[conda] numpy-base 1.18.1 py37hde5b4d6_1
[conda] pytorch 1.5.0 py3.7_cuda10.1.243_cudnn7.6.3_0 pytorch
[conda] torchvision 0.6.0 py37_cu101 pytorch

cc @ezyang @gchanan @zou3519

**Comment by mjkim720** [comment] 2020-08-05 03:17
The same input does not give a segfault in `adaptive_avg_pool3d`.

**Comment by malfet** [comment] 2020-08-11 16:38
Closing as duplicate of https://github.com/pytorch/pytorch/issues/42578

**Closed by malfet** 2020-08-11 16:38 UTC
Labels: high priority, module: operators, topic: crash, topic: error checking, triaged
