### ISSUE TITLE
[Tensorboard] Error loading embeddings in projector tab

### ISSUE THREAD

**Issue by tarrencev** [pytorch/pytorch#21448] opened 2019-06-06 03:23 UTC
## 🐛 Bug

When running the `add_embedding` example provided in the documentation [here](https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_embedding), I am unable to visualize the output in Tensorboard. When loading the projector page, the Tensorboard backend returns a 500 and the CLI throws an error (details below).

## To Reproduce

1. Generate embedding logs following example [here](https://pytorch.org/docs/stable/tensorboard.html#torch.utils.tensorboard.writer.SummaryWriter.add_embedding).
2. Run Tensorboard and navigate to Projector tab

Backend returns the following response:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

The CLI throws the following error:

```
I0606 03:16:56.516376 140481921013504 _internal.py:97] ::ffff:172.17.13.114 - - [06/Jun/2019 03:16:56] "GET /data/plugin/projector/runs HTTP/1.1" 500 -
E0606 03:16:56.518899 140481921013504 _internal.py:97] Error on request:
Traceback (most recent call last):
  File "/home/tvanas/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 302, in run_wsgi
    execute(self.server.app)
  File "/home/tvanas/.local/lib/python3.6/site-packages/werkzeug/serving.py", line 290, in execute
    application_iter = app(environ, start_response)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/backend/application.py", line 346, in __call__
    return self.data_applications[clean_path](environ, start_response)
  File "/home/tvanas/.local/lib/python3.6/site-packages/werkzeug/wrappers/base_request.py", line 235, in application
    resp = f(*args[:-2] + (request,))
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 471, in _serve_runs
    return Respond(request, list(self.configs.keys()), 'application/json')
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 323, in configs
    run_path_pairs)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 403, in _read_latest_config_files
    ckpt_path = _find_latest_checkpoint(logdir)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorboard/plugins/projector/projector_plugin.py", line 663, in _find_latest_checkpoint
    ckpt_path = tf.train.latest_checkpoint(os.path.join(dir_path, os.pardir))
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 336, in latest_checkpoint
    ckpt = get_checkpoint_state(checkpoint_dir, latest_filename)
  File "/miniconda/envs/py36/lib/python3.6/site-packages/tensorflow/python/training/checkpoint_management.py", line 278, in get_checkpoint_state
    + checkpoint_dir)
ValueError: Invalid checkpoint state loaded from runs/..
```
## Expected behavior

SummaryWriter should correctly output logs, Tensorboard should properly read them.
 
## Environment

PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration:
GPU 0: GeForce GTX 1080 Ti
GPU 1: GeForce GTX 1080 Ti
GPU 2: GeForce GTX 1080 Ti
GPU 3: GeForce GTX 1080 Ti

Nvidia driver version: 384.111
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.5.0

Versions of relevant libraries:
[pip] numpy==1.16.3
[pip] torch==1.1.0
[pip] torchfile==0.1.0
[pip] torchvision==0.2.2.post3
[pip] tb-nightly@1.14.0a20190605

**Comment by fmassa** [comment] 2019-06-06 12:45
I couldn't reproduce the error you pointed out.

Here is the script I tried, which is a straight copy-paste from the documentation that you pointed out:

```python
import keyword
import torch


import torch
import torchvision
from torch.utils.tensorboard import SummaryWriter
from torchvision import datasets, transforms

# Writer will output to ./runs/ directory by default
writer = SummaryWriter()

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize((0.5,), (0.5,))])
trainset = datasets.MNIST('mnist_train', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)
model = torchvision.models.resnet50(False)
# Have ResNet model take in grayscale rather than RGB
model.conv1 = torch.nn.Conv2d(1, 64, kernel_size=7, stride=2, padding=3, bias=False)
images, labels = next(iter(trainloader))

grid = torchvision.utils.make_grid(images)
writer.add_image('images', grid, 0)
writer.add_graph(model, images)


meta = []
while len(meta)<100:
    meta = meta+keyword.kwlist # get some strings
meta = meta[:100]

for i, v in enumerate(meta):
    meta[i] = v+str(i)

label_img = torch.rand(100, 3, 10, 32)
for i in range(100):
    label_img[i]*=i/100.0

writer.add_embedding(torch.randn(100, 5), metadata=meta, label_img=label_img)
writer.add_embedding(torch.randn(100, 5), label_img=label_img)
writer.add_embedding(torch.randn(100, 5), metadata=meta)

writer.close()
```

I'm using torch `1.1.0.dev20190520` and tensorboard version `1.14.0a20190606`, and everything seems to work fine on my end.

![image](https://user-images.githubusercontent.com/9110200/59033630-693c1680-8869-11e9-9ce4-576d6752b6dd.png)

Please provide more information about the code you used to run this. If the problem persists, maybe updating to a PyTorch nightly might fix the issue.

I'm closing the issue, but if the error persists even after updating PyTorch, please open a new issue and provide the code that you used to obtain the error

**Closed by fmassa** 2019-06-06 12:45 UTC
Labels: module: tensorboard

**Comment by tarrencev** [comment] 2019-06-06 14:04
@fmassa I am still seeing this issue after updating to pytorch nightly and running the same script you provided. Would you mind sharing your checkpoint outputted by summary writer for comparison? Mine is:

[events.out.tfevents.1559829463.0c15a53a365c.48516.0.txt](https://github.com/pytorch/pytorch/files/3261930/events.out.tfevents.1559829463.0c15a53a365c.48516.0.txt)
