### ISSUE TITLE
NCCL Backend does not support ComplexFloat data type

### ISSUE THREAD

**Issue by JALB-epsilon** [pytorch/pytorch#71613] opened 2022-01-21 00:59 UTC
### 🐛 Describe the bug

I am using Torch 1.10. This is not the code I am working on, but this reproduce the error.

```
import torch
import os
import torch.distributed as dist
import torch.multiprocessing as mp
import torch.nn as nn
import numpy as np
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel as DDP


def example(rank, world_size):
    # create default process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)
    # create local model
    model = nn.Linear(10, 10, dtype=torch.cfloat).to(rank)
    # construct DDP model
    ddp_model = DDP(model, device_ids=[rank])
    # define loss function and optimizer
    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    # forward pass
    x = torch.rand(20,10)
    outputs = ddp_model(torch.randn(20, 10).to(rank))
    labels = torch.randn(20, 10).to(rank)
    # backward pass
    loss_fn(torch.abs(outputs), labels).backward()
    # update parameters
    optimizer.step()
    print(outputs)

def main():
    world_size = 2
    mp.spawn(example,
        args=(world_size,),
        nprocs=world_size,
        join=True)

if __name__=="__main__":
    os.environ['MASTER_ADDR'] =  'localhost' 
    os.environ['MASTER_PORT'] = str(np.random.randint(10000, 20000))
    main()
```
**Output**
```RuntimeError: Input tensor data type is not supported for NCCL process group: ComplexFloat```

NCCL backend should support the Complex datatype as in the backpropagation algorithm.

### Versions

PyTorch version: 1.10.1
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: NVIDIA DGX Station (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.17

Python version: 3.8.12 (default, Oct 12 2021, 13:49:34)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.15.2.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: Could not collect

Nvidia driver version: 450.102.04
cuDNN version: Probably one of the following:
/usr/lib64/libcudnn.so.7.6.3
/usr/lib64/libcudnn.so.8.0.5
/usr/lib64/libcudnn_adv_infer.so.8.0.5
/usr/lib64/libcudnn_adv_train.so.8.0.5
/usr/lib64/libcudnn_cnn_infer.so.8.0.5
/usr/lib64/libcudnn_cnn_train.so.8.0.5
/usr/lib64/libcudnn_ops_infer.so.8.0.5
/usr/lib64/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.2
[pip3] torch==1.10.1
[pip3] torchaudio==0.10.1
[pip3] torchvision==0.11.2
[conda] blas                      1.0                         mkl
[conda] cudatoolkit               10.2.89              hfd86e86_1
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2021.4.0           h06a4308_640
[conda] mkl-service               2.4.0            py38h7f8727e_0
[conda] mkl_fft                   1.3.1            py38hd3c417c_0
[conda] mkl_random                1.2.2            py38h51133e4_0
[conda] numpy                     1.21.2           py38h20f2e39_0
[conda] numpy-base                1.21.2           py38h79a1101_0
[conda] pytorch                   1.10.1          py3.8_cuda10.2_cudnn7.6.5_0    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torchaudio                0.10.1               py38_cu102    pytorch
[conda] torchvision               0.11.2               py38_cu102    pytorch

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @anjali411 @dylanbespalko @mruberry @Lezcano @nikitaved

**Comment by ezyang** [comment] 2022-02-10 03:14
oops, we should definitely fix this. As a workaround, view the complex to real and send that to nccl.

**Comment by rohan-varma** [comment] 2022-02-10 19:19
Removed "triaged" to discuss in distributed oncall

**Comment by rmchurch** [comment] 2022-02-23 16:58
@ezyang Sorry, I assume you mean use `torch.view_as_real`, but I'm unsure how to modify the above DDP example to use it, or do you mean for a custom distributed setup?

**Comment by anjali411** [comment] 2022-02-23 18:20
> oops, we should definitely fix this. As a workaround, view the complex to real and send that to nccl.

if the tensor is conjugated, you'd also need to materialize the conjugation before you can view it as real.

**Comment by zhaojuanmao** [comment] 2022-02-28 20:45
> @ezyang Sorry, I assume you mean use `torch.view_as_real`, but I'm unsure how to modify the above DDP example to use it, or do you mean for a custom distributed setup?

I guess we need to fix this inside DDP packages, will work on this fix

**Comment by Remponator** [comment] 2022-06-21 12:45
Has this issue been fixed yet?

**Comment by anjali411** [comment] 2022-06-22 20:32
cc. @kumpera who was working on #74039

**Comment by z870609382** [comment] 2022-09-14 12:53
Has this issue been fixed yet?

**Comment by Ayiing** [comment] 2022-09-15 09:41
Has this issue been fixed yet?

**Comment by aclifton314** [comment] 2022-10-20 16:15
Is there any update on this? I'm running into this issue currently.

**Comment by anjali411** [comment] 2022-10-27 13:34
cc. @kumpera @mrshenli are we still planning to push this PR https://github.com/pytorch/pytorch/pull/74039 through?

**Comment by qingkaikong** [comment] 2022-11-01 17:03
I had exactly the same problem when I try to do distributed training on the cluster. Just want to check if there is a timeline for the solution to push through.

**Comment by Dahoas** [comment] 2022-11-16 21:52
Also running into this problem.

**Comment by qingkaikong** [comment] 2022-11-17 18:37
@Dahoas, 
I found the walk-around solution given above works well at this moment before the new changes merge into the master. Try it for now: manually do the complex number operation by using the real and imaginary parts and then use the view_as_complex later.

**Comment by heibaidaolx123** [comment] 2023-02-07 08:56
Hi, any update on this issue?

**Comment by lucidrains** [comment] 2023-02-07 16:44
Can someone also detail the workaround if there are too many blockers for this issue to be completed in a timely manner? Thanks

**Comment by ezyang** [comment] 2023-02-07 19:11
Is https://github.com/pytorch/pytorch/issues/71613#issuecomment-1034448731 enough detail?

**Comment by lucidrains** [comment] 2023-02-07 19:16
Not for me, I'm slow 😆 but if that's all you will let on, fine I'll figure it out

@ezyang is this still in progress?

**Comment by lucidrains** [comment] 2023-02-07 19:19
alright, i'll be back, and provide a diff for the original issue once i figure it out

**Comment by lucidrains** [comment] 2023-02-07 21:18
@ezyang ok, i've figured it out, but the solution is not a solution at all. it means one cannot use any network with parameters of complex float, as noted by the comment above. judging by your curt response, i'm going to guess the answer to my original question is "no" so i will not press further. i'll find another way to train a discriminator i need to automate away music generation

**Comment by rmchurch** [comment] 2023-02-07 21:38
I think this gives you what you want:
```
class complexModel(nn.Module):
  def _init__(self, rank):
    super (complexModel, self).__init_
    weights1 = torch.rand(10,10,12,12, dtype=torch.cfloat).to(rank)
    self.weights1 = nn.Parameter(torch.view _as_real(weights1))
  def forward(self,x):
    weights1 = torch.view_as_complex(self.weights1)
    return weights1
```

**Comment by lucidrains** [comment] 2023-02-07 21:51
@rmchurch yes, i'm doing something similar [here](https://github.com/lucidrains/audiolm-pytorch/blob/main/audiolm_pytorch/soundstream.py#L211)

**Comment by lucidrains** [comment] 2023-02-08 03:29
@rmchurch ahh ok, what i was missing is that the pytorch functions can still manage complex representations. thank you for your example

the final running workaround for the issue is:

```python
import torch
import os
import torch.distributed as dist
import torch.multiprocessing as mp
import numpy as np
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel as DDP

import torch.nn as nn
import torch.nn.functional as F

class ComplexLinear(nn.Module):
    def __init__(
        self,
        dim,
        dim_out
    ):
        super().__init__()
        linear = nn.Linear(dim, dim_out, dtype = torch.cfloat)
        self.weight = nn.Parameter(torch.view_as_real(linear.weight))
        self.bias = nn.Parameter(torch.view_as_real(linear.bias))

    def forward(self, x):
        weight = torch.view_as_complex(self.weight)
        bias = torch.view_as_complex(self.bias)
        return F.linear(x, weight, bias)

class ModReLU(nn.Module):
    def __init__(self):
        super().__init__()
        self.b = nn.Parameter(torch.tensor(0.))

    def forward(self, x):
        return F.relu(torch.abs(x) + self.b) * torch.exp(1.j * torch.angle(x))

def example(rank, world_size):
    # create default process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

    # create local model
    model = nn.Sequential(
        ComplexLinear(10, 10),
        ModReLU()
    ).to(rank)

    # construct DDP model
    ddp_model = DDP(model, device_ids=[rank])

    # define loss function and optimizer
    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    # forward pass
    x = torch.view_as_complex(torch.rand(20, 10, 2)).to(rank)

    outputs = ddp_model(x)
    labels = torch.randn(20, 10).to(rank)

    # backward pass
    loss_fn(torch.abs(outputs), labels).backward()

    # update parameters
    optimizer.step()
    print(outputs)

def main():
    world_size = 2
    mp.spawn(example,
        args=(world_size,),
        nprocs=world_size,
        join=True)

if __name__=="__main__":
    os.environ['MASTER_ADDR'] =  'localhost' 
    os.environ['MASTER_PORT'] = str(np.random.randint(10000, 20000))
    main()
```

**Comment by ezyang** [comment] 2023-06-06 03:30
Ke tells me we won't fix this in NCCL directly; instead, we need to handle converting complex float to just float in userland

**Comment by Art-MC** [comment] 2024-03-14 03:45
Has there been any progress on this? I'm also in need of DDP for complex-valued NNs, and I am wondering if there are plans for this issue to be resolved.

**Comment by alundilong** [comment] 2024-04-16 21:33
just wondering any fix been done?

**Comment by JALB-epsilon** [comment] 2024-06-29 17:50
is there any progress on this?

**Comment by ezyang** [comment] 2024-07-06 16:54
I wanted to mention that at least as of Jul 6 nightly (a1a2023eb86805b1a3867dbda9c89be3cd63dd27) and possibly earlier, the original version of the script works:

```
import torch
import os
import torch.distributed as dist
import torch.multiprocessing as mp
import numpy as np
import torch.optim as optim
from torch.nn.parallel import DistributedDataParallel as DDP

import torch.nn as nn
import torch.nn.functional as F

class ComplexLinear(nn.Module):
    def __init__(
        self,
        dim,
        dim_out
    ):
        super().__init__()
        linear = nn.Linear(dim, dim_out, dtype = torch.cfloat)
        self.weight = nn.Parameter((linear.weight))
        self.bias = nn.Parameter((linear.bias))

    def forward(self, x):
        weight = (self.weight)
        bias = (self.bias)
        return F.linear(x, weight, bias)

class ModReLU(nn.Module):
    def __init__(self):
        super().__init__()
        self.b = nn.Parameter(torch.tensor(0.))

    def forward(self, x):
        return F.relu(torch.abs(x) + self.b) * torch.exp(1.j * torch.angle(x))

def example(rank, world_size):
    # create default process group
    dist.init_process_group("nccl", rank=rank, world_size=world_size)

    # create local model
    model = nn.Sequential(
        ComplexLinear(10, 10),
        ModReLU()
    ).to(rank)

    # construct DDP model
    ddp_model = DDP(model, device_ids=[rank])

    # define loss function and optimizer
    loss_fn = nn.MSELoss()
    optimizer = optim.SGD(ddp_model.parameters(), lr=0.001)

    # forward pass
    x = torch.view_as_complex(torch.rand(20, 10, 2)).to(rank)

    outputs = ddp_model(x)
    labels = torch.randn(20, 10).to(rank)

    # backward pass
    loss_fn(torch.abs(outputs), labels).backward()

    # update parameters
    optimizer.step()
    print(outputs)

def main():
    world_size = 2
    mp.spawn(example,
        args=(world_size,),
        nprocs=world_size,
        join=True)

if __name__=="__main__":
    os.environ['MASTER_ADDR'] =  'localhost' 
    os.environ['MASTER_PORT'] = str(np.random.randint(10000, 20000))
    main()

```

So as best as I can tell, this is fixed!

**Closed by ezyang** 2024-07-06 16:54 UTC
Labels: high priority, triage review, oncall: distributed, module: complex, module: nccl, has workaround
