### ISSUE TITLE
PyTorch nightly fails on Windows

### ISSUE THREAD

**Issue by lutzroeder** [pytorch/pytorch#31513] opened 2019-12-20 10:14 UTC
## 🐛 Bug

`import torch` fails to command prompt without an error for recent nightly builds on Windows.  

## To Reproduce

```
C:\> pip install future protobuf scipy
C:\> pip install --pre torch torchvision -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html

Looking in links: https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cpu/torch-1.4.0.dev20191216%2Bcpu-cp36-cp36m-win_amd64.whl
Collecting torchvision
  Using cached https://download.pytorch.org/whl/nightly/cpu/torchvision-0.5.0.dev20191215%2Bcpu-cp36-cp36m-win_amd64.whl
Requirement already satisfied: numpy in c:\python36\lib\site-packages (from torchvision) (1.17.4)
Requirement already satisfied: six in c:\python36\lib\site-packages (from torchvision) (1.13.0)
Requirement already satisfied: pillow>=4.1.1 in c:\python36\lib\site-packages (from torchvision) (6.2.1)
Installing collected packages: torch, torchvision
Successfully installed torch-1.4.0.dev20191216+cpu torchvision-0.5.0.dev20191215+cpu

C:\>python
Python 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 13:35:33) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch

C:\>
```

## Expected behavior

Import completes waiting for next Python command.

## Environment

`collect_env.py` does not complete as `import torch` fails.

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux): Windows 10 (1909 18363)
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Python version: 3.6.7

**Comment by peterjc123** [comment] 2019-12-20 10:22
Duplicate of https://github.com/pytorch/pytorch/issues/31370.

**Closed by peterjc123** 2019-12-20 10:22 UTC
