### ISSUE TITLE
torch.autograd.grad bug after migrate from 0.4 to 1.0

### ISSUE THREAD

**Issue by lixilinx** [pytorch/pytorch#15532] opened 2018-12-26 01:46 UTC
Code to reproduce this bug is here:

https://github.com/lixilinx/psgd_torch/blob/297612b79d8e43b28c6583b01156e55847ed8ca2/demo_LeNet5.py#L66

I use grad to calculate the Hessian-vector product. This line worked in both Windows 10 and Ubuntu with Pytorch version 0.4. 

Recently, I update to version 1.0. Now, this line only works in Windows 10, fails in Ubuntu. In Ubuntu, I must change this line to
Hv = grad(sum([torch.sum(a*b) for (a, b) in zip(grads, v)]), Ws)
to make it work again. But this is not as clean as 
Hv = grad(grads, Ws, v)
Furthermore, the two writings should do the same thing according to the documents. So where gets wrong?

**Comment by lixilinx** [comment] 2018-12-26 04:18
by the way, using 'Hv = grad(grads, Ws, v)' in ubuntu produces error message:
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
This does not make sense since element 0 is W1, and its requires_grad=True (to emphasize again: 'Hv = grad(grads, Ws, v)' works in windows and pytorch 0.4).

**Comment by lixilinx** [comment] 2018-12-27 04:12
maybe the bug is related to
https://github.com/pytorch/pytorch/issues/15353
Anyway, code is broken after migrate from Pytorch 0.4 to 1.0.0 (Python 3.6.7, Ubuntu 16.04.5 LTS)

**Comment by ezyang** [comment] 2019-01-07 05:06
Yes, I think it is quite likely the same as #15353. Can you upgrade to master and see if that fixes your problem? Thanks!

**Comment by lixilinx** [comment] 2019-01-07 18:10
Yes, upgrading to master can fix this issue!

Still, I do not fully understand that why 'Hv = grad(sum([torch.sum(a*b) for (a, b) in zip(grads, v)]), Ws)' works and Hv = grad(grads, Ws, v) does not work in the stable version since these two writings do the same thing in my code.

**Comment by zou3519** [comment] 2019-01-07 18:12
Closing because the issue is resolved on master

**Closed by zou3519** 2019-01-07 18:12 UTC
Labels: autograd, high priority
