### ISSUE TITLE
Float16 scaled_dot_product_attention returns NaNs on ROCm

### ISSUE THREAD

**Issue by tvaranka** [pytorch/pytorch#116176] opened 2023-12-20 07:16 UTC
### 🐛 Describe the bug

Using PyTroch's `scaled_dot_product_attention` with float16 results in NaNs with large vector values. The problem does not occur with CUDA float16 or ROCm float32. The problem seems to be different from https://github.com/pytorch/pytorch/issues/103963 , where the output partially contains NaNs when using masks.

Example modified from : https://pytorch.org/docs/stable/generated/torch.nn.functional.scaled_dot_product_attention.html
```python
import torch
import torch.nn.functional as F
query = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda") * -900
key = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda") * -900
value = torch.rand(32, 8, 128, 64, dtype=torch.float16, device="cuda")
with torch.backends.cuda.sdp_kernel(enable_math=True, enable_flash=False):
    out = F.scaled_dot_product_attention(query,key,value) #performed with float16 using autocast

#out contains NaNs for all of the values
>>> out #some values removed to save space
tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          ...,
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan]]]], device='cuda:0',
       dtype=torch.float16)
```

### Versions

Couldn't run the script due to an error, AttributeError: 'torch._C._CudaDeviceProperties' object has no attribute 'gcnArchName', seems to be a problem with ROCm, also here https://github.com/pytorch/pytorch/issues/113760

python 3.10.13
torch 2.1.2
rocm5.6
gpu mi250x

cc @ezyang @gchanan @zou3519 @kadeng @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @dllehr-amd @jataylo @hongxiayang

**Comment by hongxiayang** [comment] 2023-12-20 17:39
@tvaranka   The reason is that your input exceeds max value of FP16 resulting nan. 
Suggested not multiplying the value with (* -900) so that the input is not exceeding the range of FP16, and you should be fine.

**Comment by hongxiayang** [comment] 2023-12-20 17:44
cc @xinyazhang @groenenboomj

**Comment by tvaranka** [comment] 2023-12-20 17:46
@hongxiayang Yes, that seems to be the case that there is an overflow. However this problem does not occur with nvidia cuda.

The reason why I am multiplying with -900 is that this is a minimal reproducible sample. This actually happens when I am trying to run Stable Video Diffusion from https://github.com/Stability-AI/generative-models , but I have just pinpointed the problem to this exact issue of large values with scaled_dot_product_attention resulting with NaNs.

**Comment by hongxiayang** [comment] 2023-12-20 19:19
Would you mind sharing the steps to reproduce your issue in running Stable Video Diffusion? We will take a deeper look after we can reproduce, and check whether there is other issue.

**Comment by drisspg** [comment] 2023-12-20 21:18
This is based off of this new PR: https://github.com/pytorch/pytorch/pull/114309?
Or the math implementation?

**Comment by drisspg** [comment] 2023-12-20 21:19
Is there a particular op on ROCM that has different semantics to CUDA?

**Comment by tvaranka** [comment] 2023-12-21 05:58
To reproduce Stable Video Diffusion see below. Let me know if you need any help with the steps below or have any trouble running the code.

After running the script in step 4, it should save an mp4 to `outputs` folder. For me the video is completely black due to NaNs. I tracked the issue of NaNs raising in the second last output block of UNet.

1. `git clone https://github.com/Stability-AI/generative-models`
2. Load weights from https://huggingface.co/stabilityai/stable-video-diffusion-img2vid, `git lfs` for example
3. Environment/container (also see instructions from the generative-models repo)
     1. torch 2.1.2 with rocm5.6
     2. `pip install -r requirements/pt2.txt` # In generative-models folder
     3. `pip install -e .`
4. Run with `python scripts/sampling/simple_video_sample.py`, not other arguments necessary.

-  If it doesn't work due to xformers missing on ROCm, `pip uninstall xformers` and from scripts/sampling/config/svd.yaml remove `-xformers` instances from 2 places. (This is what I did)
- If you don't have enough memory on your GPU you can try reducing the `decoding_t` to a lower number from `scripts/sampling/simple_video_sample.py` (Didn't need to do this)

Thanks!

**Comment by hongxiayang** [comment] 2024-01-16 17:09
@tvaranka I was trying to run the scripts/sampling/simple_video_sample.py on MI250x with the steps you provided, and I got different error:

Have you seen this before?

```
PYTHONPATH=.:$PYTHONPATH python3 scripts/sampling/simple_video_sample.py

no module 'xformers'. Processing without...
no module 'xformers'. Processing without...
VideoTransformerBlock is using checkpointing
...
...

Initialized embedder #0: FrozenOpenCLIPImagePredictionEmbedder with 683800065 params. Trainable: False
Initialized embedder #1: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #2: ConcatTimestepEmbedderND with 0 params. Trainable: False
Initialized embedder #3: VideoPredictionEmbedderWithEncoder with 83653863 params. Trainable: False
Initialized embedder #4: ConcatTimestepEmbedderND with 0 params. Trainable: False
Restored from checkpoints/svd.safetensors with 0 missing and 0 unexpected keys
/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py:429: UserWarning: torch.utils.checkpoint: please pass in use_reentrant=True or use_reentrant=False explicitly. The default value of use_reentrant will be updated to be False in the future. To maintain current behavior, pass use_reentrant=True. It is recommended that you use use_reentrant=False. Refer to docs for more details on the differences between the two variants.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/torch/utils/checkpoint.py:61: UserWarning: None of the inputs have requires_grad=True. Gradients will be None
  warnings.warn(
OpenCV: FFMPEG: tag 0x5634504d/'MP4V' is not supported with codec id 12 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x7634706d/'mp4v'
scripts/sampling/simple_video_sample.py:195: RuntimeWarning: invalid value encountered in cast
  (rearrange(samples, "t c h w -> t h w c") * 255)

**Comment by tvaranka** [comment] 2024-01-16 17:31
@hongxiayang I don't believe I got this error. But it seems that you were able to run the whole generation process and are at the step of just putting the generated frames to an output video. Could you check whether the frames contain NaNs?

Could either `print` or use `torch.isnan` before the error at line 193 `print(samples)`

**Comment by hongxiayang** [comment] 2024-01-16 18:04
@tvaranka here is what the print samples got:
**Samples=tensor([[[[nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],
          [nan, nan, nan,  ..., nan, nan, nan],

**Comment by tvaranka** [comment] 2024-01-16 18:11
@hongxiayang Okay, so it's the same issue I have. With cuda, this issue does not exist and a video is generated. I tracked the issue to the sdpa as I mentioned above

**Comment by hongxiayang** [comment] 2024-01-16 18:18
> @hongxiayang Okay, so it's the same issue I have. With cuda, this issue does not exist and a video is generated. I tracked the issue to the sdpa as I mentioned above

I see. I guess it needs some patch in order for this test script to work.

**Comment by hongxiayang** [comment] 2024-01-19 17:39
> Is there a particular op on ROCM that has different semantics to CUDA?

The math backend performs the same on both. We have early support for flash, and we are working on support memory-efficient

**Comment by hongxiayang** [comment] 2024-01-19 19:08
@tvaranka  If you use the latest rocm/pytorch-nightly:latest docker image, and run with the following mode:
```
with torch.backends.cuda.sdp_kernel(enable_math=False, enable_flash=True):
```
the minimum reproducer test will be fine with float16 datatype.

**Comment by tvaranka** [comment] 2024-01-22 07:14
@hongxiayang Thanks for the quick update. The cluster I am currently running on doesn't have support for 5.7 yet so I cannot unfortunately test yet. I have requested for an update, but it may take a while, so you can close the issue if you believe it's fixed.

**Comment by hongxiayang** [comment] 2024-01-22 14:46
> @hongxiayang Thanks for the quick update. The cluster I am currently running on doesn't have support for 5.7 yet so I cannot unfortunately test yet. I have requested for an update, but it may take a while, so you can close the issue if you believe it's fixed.

@tvaranka  Yes, it needs ROCm 5.7+ for the flash-attention support. I am going to close it, and once you have the cluster updated, and if you still have issues, please open a new issue then. Thank you!

**Closed by hongxiayang** 2024-01-22 14:46 UTC
Labels: high priority, module: rocm, triaged, module: multi-headed-attention
