### ISSUE TITLE
enforce fail at inline_container.cc:137] . PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by Edwardf0t1** [pytorch/pytorch#16741] opened 2019-02-05 00:14 UTC
## 🐛 Bug

```python
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:137] . PytorchStreamReader failed reading zip archive: failed finding central directory
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f15338da111 in xxx/projects/libtorch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x49 (0x7f15338d9f29 in /xxx/projects/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::PyTorchStreamReader::valid(char const*) + 0x6b (0x7f156be4c54b in /xxx/projects/libtorch/lib/libcaffe2.so)
frame #3: caffe2::serialize::PyTorchStreamReader::init() + 0x9d (0x7f156be4e31d in /xxx/projects/libtorch/lib/libcaffe2.so)
frame #4: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >) + 0x3b (0x7f156be4fd7b in /xxx/projects/libtorch/lib/libcaffe2.so)
frame #5: <unknown function> + 0x6797de (0x7f157741e7de in /xxx/projects/libtorch/lib/libtorch.so.1)
frame #6: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>) + 0x95 (0x7f1577421f65 in /xxx/projects/libtorch/lib/libtorch.so.1)
frame #7: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x60 (0x7f1577422100 in /xxx/projects/libtorch/lib/libtorch.so.1)
frame #8: main + 0x125 (0x432291 in ./build/infer)
frame #9: __libc_start_main + 0xf0 (0x7f1532f78830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: _start + 0x29 (0x430eb9 in ./build/infer)

Aborted (core dumped)
```

## To Reproduce

We have a C++ script using PyTorch C++ api to test a model's performance , and when loading the saved model by our PyTorch script and calling this line:

```cpp
std::shared_ptr<torch::jit::script::Module> model = torch::jit::load("model.pt");
```

we got core dump error as described above.Please help.

We have the following included libraries in our C++ scripts:

```cpp
#include <chrono>
#include <stdio.h>
#include <torch/torch.h>
#include <torch/script.h>
```

## Environment

The C compiler identification is GNU 5.4.0
The CXX compiler identification is GNU 5.4.0
Ubuntu 16.04
Pytorch 1.0.0
cuda 10.0
cudnn:7.4.2
Python 3.6
Conda installed Pytorch

**Comment by driazati** [comment] 2019-02-05 21:49
Thanks for reporting! I couldn't reproduce this locally with a simple model in Python, are you able to supply the Python code to generate `model.pt`?

**Comment by Edwardf0t1** [comment] 2019-02-05 23:15
Thank you for the response. Our Python code is similar to this one:

https://github.com/LaurentMazare/deep-models/blob/5aa353f88065150b0a024578f4af09d5c4f2d651/cifar-10/train.py

We used the same way to generate "model.pt".

Btw, when we cmake our testing app, we pointed to the libtorch downloaded (2/4/2019) with the following configurations:
![screen shot 2019-02-05 at 2 40 48 pm](https://user-images.githubusercontent.com/24870971/52309199-3aae3d80-2954-11e9-85dd-4ad09e76708c.png)

**Comment by huxianer** [comment] 2019-02-22 03:09
@Edwardf0t1 @driazati I meet with the same error!,How to solve,Thank you for any help!

**Comment by suo** [comment] 2019-02-22 03:11
The most helpful thing would be to provide a simple script that can reproduce the error so that we can investigate. Thanks!

**Comment by huxianer** [comment] 2019-02-22 03:17
@Edwardf0t1 The log is below:
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:127] . PytorchStreamReader failed reading zip archive: failed finding central directory
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f4065d9f021 in /search/speech/huxianjun/project/Facetron-Release-master/c++/facetron/libtorch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x49 (0x7f4065d9edc9 in /search/speech/huxianjun/project/Facetron-Release-master/c++/facetron/libtorch/lib/libc10.so)
frame #2: torch::jit::PyTorchStreamReader::valid(char const*) + 0x80 (0x7f409593dc30 in /search/speech/huxianjun/project/Facetron-Release-master/c++/facetron/libtorch/lib/libcaffe2.so)
frame #3: torch::jit::PyTorchStreamReader::PyTorchStreamReader(std::string, std::istream*) + 0x1e6 (0x7f409593fc36 in /search/speech/huxianjun/project/Facetron-Release-master/c++/facetron/libtorch/lib/libcaffe2.so)
frame #4: <unknown function> + 0x6663b3 (0x7f40a1e243b3 in /search/speech/huxianjun/project/Facetron-Release-master/c++/facetron/libtorch/lib/libtorch.so.1)
frame #5: torch::jit::load(std::istream&, c10::optional<c10::Device>) + 0x7f (0x7f40a1e2773f in /search/speech/huxianjun/project/Facetron-Release-master/c++/facetron/libtorch/lib/libtorch.so.1)
frame #6: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x6c (0x7f40a1e278cc in /search/speech/huxianjun/project/Facetron-Release-master/c++/facetron/libtorch/lib/libtorch.so.1)
frame #7: main + 0x91 (0x446799 in ./facetron)
frame #8: __libc_start_main + 0xf5 (0x7f40628353d5 in /lib64/libc.so.6)
frame #9: ./facetron() [0x440b09]

**Comment by huxianer** [comment] 2019-02-22 03:19
@Edwardf0t1 
terminate called after throwing an instance of 'c10::Error'
  what():  [enforce fail at inline_container.cc:137] . PytorchStreamReader failed reading zip archive: failed finding central directory
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f15338da111 in xxx/projects/libtorch/lib/libc10.so)
frame #1: c10::ThrowEnforceNotMet(char const*, int, char const*, std::string const&, void const*) + 0x49 (0x7f15338d9f29 in /xxx/projects/libtorch/lib/libc10.so)
frame #2: caffe2::serialize::PyTorchStreamReader::valid(char const*) + 0x6b (0x7f156be4c54b in /xxx/projects/libtorch/lib/libcaffe2.so)
frame #3: caffe2::serialize::PyTorchStreamReader::init() + 0x9d (0x7f156be4e31d in /xxx/projects/libtorch/lib/libcaffe2.so)
frame #4: caffe2::serialize::PyTorchStreamReader::PyTorchStreamReader(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >) + 0x3b (0x7f156be4fd7b in /xxx/projects/libtorch/lib/libcaffe2.so)
frame #5: <unknown function> + 0x6797de (0x7f157741e7de in /xxx/projects/libtorch/lib/libtorch.so.1)
frame #6: torch::jit::load(std::unique_ptr<caffe2::serialize::ReadAdapterInterface, std::default_delete<caffe2::serialize::ReadAdapterInterface> >, c10::optional<c10::Device>) + 0x95 (0x7f1577421f65 in /xxx/projects/libtorch/lib/libtorch.so.1)
frame #7: torch::jit::load(std::string const&, c10::optional<c10::Device>) + 0x60 (0x7f1577422100 in /xxx/projects/libtorch/lib/libtorch.so.1)
frame #8: main + 0x125 (0x432291 in ./build/infer)
frame #9: __libc_start_main + 0xf0 (0x7f1532f78830 in /lib/x86_64-linux-gnu/libc.so.6)
frame #10: _start + 0x29 (0x430eb9 in ./build/infer)

Aborted (core dumped)

**Comment by driazati** [comment] 2019-03-11 22:19
This issue appears to be fixed on master, I'm able to load the model from the link with no issues:
```cpp
std::shared_ptr<torch::jit::script::Module> module =
      torch::jit::load("model.pt");
```

Feel free to re-open if you're still getting the issue on master/nightly.

**Closed by driazati** 2019-03-11 22:19 UTC
Labels: jit

**Comment by xzntek** [comment] 2019-03-15 07:48
I have same problem with version 1.0.0.dev20190312. This problem is not fixed

**Comment by xzntek** [comment] 2019-03-15 08:16
This bug still is there. I have tried lots of different models. All of them will give same error.

For example i get here same problem.
git code - https://github.com/Ugness/PiCANet-Implementation
models -  https://drive.google.com/drive/folders/1s4M-_SnCPMj_2rsMkSy3pLnLQcgRakAe
