### ISSUE TITLE
ImportError: No module named 'torch'

### ISSUE THREAD

**Issue by dicksonj** [pytorch/pytorch#16103] opened 2019-01-17 05:58 UTC
Unbale to load Pytorch from Jupyter Notebook.
I am using Windows 10 and Anaconda Navigator-Jupy Notebook. 
I did `conda install pytorch torchvision -c pytorch`
The package loads successfully in Terminal (Opened within Jupyter) when I do `import torch`
It doesn't work within the Notebook and keeps throwing ImportError. 
python v 3.6.5.
Note: `I tried conda update conda`
`conda install mkl=2018 `and still no luck

**Comment by peterjc123** [comment] 2019-01-17 06:16
It is likely your Notebook and the Jupyter are installed in different Python environments. So you have two choices:
1. Please install Notebook using Anaconda Navigator.
2. Find the python and pip tools that live with Notebook and install pytorch and torchvision in that environment.

Anyway, in the terminal or Anaconda prompt, you can use `where EXECUTABLE_NAME` to check which executable actually get selected first.

**Comment by peterjc123** [comment] 2019-01-17 06:20
@soumith Please close this one because it's not a bug.

**Closed** 2019-01-17 08:40 UTC
