### ISSUE TITLE
MultiheadAttention / transformer with batch first 

### ISSUE THREAD

**Issue by d5555** [pytorch/pytorch#25100] opened 2019-08-23 15:54 UTC
Is it possible to add option batch_first = True for MultiheadAttention and  transformer modules like it is done for RNN  ? 
Batch  x Sequence x Embedding
I find it more understandable and intuitive when batch_first is true

**Comment by izdeby** [comment] 2019-08-23 19:27
Please use https://discuss.pytorch.org (https://discuss.pytorch.org/) for questions. Please kindly feel encouraged to reopen this issue, if this does not apply.

**Comment by malmaud** [comment] 2019-08-23 21:48
@izdeby This seems like a reasonable feature request to me, and AFAIK feature requests are fair game for github issues.

**Comment by venkatasg** [comment] 2020-04-22 16:33
I think this should definitely be an option, since batch_first is an option with other modules.

**Comment by albanD** [comment] 2021-03-10 16:48
Closing as duplicate of https://github.com/pytorch/pytorch/issues/43112
We can continue the discussion there !

**Closed by albanD** 2021-03-10 16:48 UTC
Labels: enhancement, module: multithreading, oncall: transformer/mha, triaged
