### ISSUE TITLE
ImportError: libiomp5.so: cannot open shared object file

### ISSUE THREAD

**Issue by jdxyw** [pytorch/pytorch#936] opened 2017-03-06 10:05 UTC
Hi

My environment is Linux 2.6.32 gcc 4.8.2 cuda 8.0 python 2.7. Install pytorch by pip install
https://s3.amazonaws.com/pytorch/whl/cu80/torch-0.1.10.post1-cp27-none-linux_x86_64.whl 

The installation is successful However I got the error by import torch like below.

ImportError: libiomp5.so: cannot open shared object file: No such file or directory.

libiomp5.so should be a part of Intel compiler?

Best Regards,

**Comment by lykaust15** [comment] 2017-03-06 10:57
I got the same problem. My environment is CentOS 7, cuda 8.0, python 2.7. I installed it by pip as well.

**Comment by trypag** [comment] 2017-03-06 14:02
Can you try with conda instead ? `conda install pytorch torchvision cuda80 -c soumith` 
I think the problem is that openMP is not installed and only conda can manage this kind of external dependency.

**Comment by soumith** [comment] 2017-03-06 15:27
I'm taking a look at this. This is a problem only with the wheel files.
I'm fixing it, new wheels will be pushed in ~2-3 hours. Sorry about the issues.

**Comment by soumith** [comment] 2017-03-06 15:27
And yes, this is only with 0.1.10. It is because of this commit: https://github.com/pytorch/pytorch/commit/ff5fa111299bbe3aa47fd55bd94d971b90cda646

**Comment by soumith** [comment] 2017-03-06 17:31
this should now be fixed, new wheel files have been built!

**Comment by sirius27** [comment] 2017-03-08 01:24
great...failed to import just now and this issue helps

**Comment by ahwillia** [comment] 2017-05-02 02:01
I just got this same error with `0.1.12`. Can this be fixed/reopened? I'd rather not use conda...

```
pip install http://download.pytorch.org/whl/cu80/torch-0.1.12.post1-cp35-cp35m-linux_x86_64.whl 
```

**Comment by soumith** [comment] 2017-05-02 12:08
@ahwillia i'm looking at the wheel you pointed out, and libiomp5 is shipped with it. What's the exact error message you get? I cant reproduce this locally even in fresh docker images.

**Comment by ahwillia** [comment] 2017-05-03 16:13
```
In [1]: import torch
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c031d3dd82fc> in <module>()
----> 1 import torch

/home/alex/.pyenv/versions/3.5.0/envs/convnet2/lib/python3.5/site-packages/torch/__init__.py in <module>()
     51 sys.setdlopenflags(_dl_flags.RTLD_GLOBAL | _dl_flags.RTLD_NOW)
     52 
---> 53 from torch._C import *
     54 
     55 __all__ += [name for name in dir(_C)

ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by ahwillia** [comment] 2017-05-03 16:18
Apologies that this isn't `libiomp5.so` anymore... I redownloaded and changed a few things in `pyenv`. I can't reproduce it anymore. Any chance this is still related or should we close this?

**Comment by soumith** [comment] 2017-05-03 16:51
i think this is unrelated. And it looks like you dont have `libpython3.5m.so.1.0` in your LD_LIBRARY_PATH, so no python C extensions will work afaik.

**Closed by soumith** 2017-05-03 16:51 UTC

**Comment by salarora** [comment] 2017-10-05 22:59
I ran into the a similar issue in a new Python 3.6 virtual environment. The issue was resolved when I updated my machine with the Python 3.6 development package. This link has information to resolve this on various platforms: https://stackoverflow.com/questions/21530577/fatal-error-python-h-no-such-file-or-directory
