### ISSUE TITLE
Segfault at onnx export of fp16 model.

### ISSUE THREAD

**Issue by II245** [pytorch/pytorch#54529] opened 2021-03-23 18:58 UTC
## 🐛 Bug
When I export an fp16 model from Pytorch (1.7.1) to onnx with jit decorator I get segfault. Please, see the output below.

```
1.7.1
{'o': tensor([[0.3491, 0.9634, 0.3867, 0.0742, 0.5737, 0.4253, 0.9653, 0.7935, 0.5679,
         0.4507],
        [0.4006, 0.1095, 0.9175, 0.6177, 0.2668, 0.5767, 0.0000, 0.0000, 0.0000,
         0.0000]], device='cuda:0', dtype=torch.float16)}
Warning: ONNX Scalar Type Analysis - Scalar types mismatch for tensor inputs of operator onnx::Mul. Please report a bug to PyTorch. The scalar type Half of the first tensor is chosen.
Segmentation fault (core dumped)
```

## To Reproduce

Run script below

```python
import onnxruntime
from torch import nn
import torch

print(torch.__version__)

@torch.jit.script
def compute_output_lengths(x, lengths_fraction):
	if lengths_fraction is None:
		return torch.full(x.shape[:1], x.shape[-1], device = x.device, dtype = torch.long)
	return (lengths_fraction * x.shape[-1]).ceil().long()

@torch.jit.script
def temporal_mask(x, lengths):
	return (torch.arange(x.shape[-1], device = x.device, dtype = torch.long).unsqueeze(0) <
			lengths.unsqueeze(1)).view(x.shape[:1] + (1, ) * (len(x.shape) - 2) + x.shape[-1:])

class Model(nn.Module):
	def forward(self, x, xlen):
		l = compute_output_lengths(x, xlen)
		tm = temporal_mask(x, l)
		x = x * tm
		return dict(o=x)

model = Model()
model.to(dtype=torch.float16, device='cuda')

x = torch.rand(2, 10).to(dtype=torch.float16, device='cuda')
xlen = torch.rand(2).to(dtype=torch.float16, device='cuda')

print(model(x, xlen))

torch.onnx.export(
		model, (x, xlen),
		'fp16_jit_repro.onnx',
		verbose=False,
		opset_version=12,
		export_params=None,
		do_constant_folding=True,
		input_names=['x', 'xlen']
)

print('runtime...')
runtime = onnxruntime.InferenceSession('fp16_jit_repro.onnx')
print(runtime.run(None, dict(x=x.cpu().numpy(), xlen=xlen.cpy().numpy())))
```

For additional information, I run gdb, see output below.

```
*@b175cd407c0d:~/work/repro$ gdb -ex run --args python fp16_jit_repro.py 
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from python...done.
Starting program: /opt/conda/bin/python fp16_jit_repro.py
warning: Error disabling address space randomization: Operation not permitted
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1.7.1
[New Thread 0x7f93247d2700 (LWP 5083)]
[New Thread 0x7f9323fd1700 (LWP 5084)]
{'o': tensor([[0.6211, 0.9976, 0.1487, 0.6392, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.3657, 0.1152, 0.1771, 0.4727, 0.3413, 0.2419, 0.3040, 0.0609, 0.9688,
         0.0984]], device='cuda:0', dtype=torch.float16)}
Warning: ONNX Scalar Type Analysis - Scalar types mismatch for tensor inputs of operator onnx::Mul. Please report a bug to PyTorch. The scalar type Half of the first tensor is chosen.

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007f9381d3d80e in torch::jit::(anonymous namespace)::ImplicitCastForONNX(torch::jit::Block*) () from /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so
(gdb) bt
#0  0x00007f9381d3d80e in torch::jit::(anonymous namespace)::ImplicitCastForONNX(torch::jit::Block*) () from /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#1  0x00007f9381d07067 in void pybind11::cpp_function::initialize<void (*&)(std::shared_ptr<torch::jit::Graph> const&), void, std::shared_ptr<torch::jit::Graph> const&, pybind11::name, pybind11::scope, pybind11::sibling>(void (*&)(std::shared_ptr<torch::jit::Graph> const&), void (*)(std::shared_ptr<torch::jit::Graph> const&), pybind11::name const&, pybind11::scope const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call&) () from /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#2  0x00007f93819598c6 in pybind11::cpp_function::dispatcher(_object*, _object*, _object*) () from /opt/conda/lib/python3.8/site-packages/torch/lib/libtorch_python.so
#3  0x000055ee49b47706 in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=0x7f932c890950) at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:742
#4  PyCFunction_Call () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:772
#5  0x000055ee49b0525f in _PyObject_MakeTpCall () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:159
#6  0x000055ee49b8d719 in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x7f9323696a08, callable=0x7f932c890950) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:125
#7  call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x55ee4b8cbe90) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
#8  _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:3469
#9  0x000055ee49b522a2 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4298
#10 0x000055ee49b53243 in _PyFunction_Vectorcall.localalias.353 () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:435
#11 0x000055ee49ac850b in _PyObject_Vectorcall (kwnames=0x7f93236830a0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f9323686670) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:127
#12 call_function (kwnames=0x7f93236830a0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
#13 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:3515
#14 0x000055ee49b522a2 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4298
#15 0x000055ee49b53243 in _PyFunction_Vectorcall.localalias.353 () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:435
#16 0x000055ee49ac850b in _PyObject_Vectorcall (kwnames=0x7f9390cdb180, nargsf=<optimized out>, args=<optimized out>, callable=0x7f9323686ca0) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:127
#17 call_function (kwnames=0x7f9390cdb180, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
#18 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:3515
#19 0x000055ee49b522a2 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4298
#20 0x000055ee49b53243 in _PyFunction_Vectorcall.localalias.353 () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:435
#21 0x000055ee49ac850b in _PyObject_Vectorcall (kwnames=0x7f932bd15240, nargsf=<optimized out>, args=<optimized out>, callable=0x7f9323686ee0) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:127
#22 call_function (kwnames=0x7f932bd15240, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
#23 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:3515
#24 0x000055ee49b522a2 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4298
#25 0x000055ee49b53243 in _PyFunction_Vectorcall.localalias.353 () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:435
#26 0x000055ee49ac758e in _PyObject_Vectorcall (kwnames=0x0, nargsf=<optimized out>, args=0x55eeb2fd4d48, callable=0x7f93236864c0) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:127
#27 call_function (kwnames=0x0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=0x55ee4b8cbe90) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
#28 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:3469
#29 0x000055ee49b522a2 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4298
#30 0x000055ee49b53243 in _PyFunction_Vectorcall.localalias.353 () at /tmp/build/80754af9/python_1593706424329/work/Objects/call.c:435
#31 0x000055ee49ac850b in _PyObject_Vectorcall (kwnames=0x7f93aec4a0e0, nargsf=<optimized out>, args=<optimized out>, callable=0x7f932c329ee0) at /tmp/build/80754af9/python_1593706424329/work/Include/cpython/abstract.h:127
#32 call_function (kwnames=0x7f93aec4a0e0, oparg=<optimized out>, pp_stack=<synthetic pointer>, tstate=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4963
#33 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:3515
#34 0x000055ee49b522a2 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4298
#35 0x000055ee49b53054 in PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:4327
#36 0x000055ee49be15bc in PyEval_EvalCode (co=<optimized out>, globals=<optimized out>, locals=<optimized out>) at /tmp/build/80754af9/python_1593706424329/work/Python/ceval.c:718
#37 0x000055ee49be1664 in run_eval_code_obj () at /tmp/build/80754af9/python_1593706424329/work/Python/pythonrun.c:1125
#38 0x000055ee49c13874 in run_mod () at /tmp/build/80754af9/python_1593706424329/work/Python/pythonrun.c:1147
#39 0x000055ee49adc316 in PyRun_FileExFlags (fp=0x55ee4b931d30, filename_str=<optimized out>, start=<optimized out>, globals=0x7f93aed37c40, locals=0x7f93aed37c40, closeit=1, flags=0x7ffe7547f648) at /tmp/build/80754af9/python_1593706424329/work/Python/pythonrun.c:1063
#40 0x000055ee49adc6fb in PyRun_SimpleFileExFlags (fp=0x55ee4b931d30, filename=<optimized out>, closeit=1, flags=0x7ffe7547f648) at /tmp/build/80754af9/python_1593706424329/work/Python/pythonrun.c:428
#41 0x000055ee49add5c0 in pymain_run_file (cf=0x7ffe7547f648, config=0x55ee4b8cb230) at /tmp/build/80754af9/python_1593706424329/work/Modules/main.c:387
#42 pymain_run_python (exitcode=0x7ffe7547f640) at /tmp/build/80754af9/python_1593706424329/work/Modules/main.c:571
#43 Py_RunMain () at /tmp/build/80754af9/python_1593706424329/work/Modules/main.c:650
#44 0x000055ee49c16389 in Py_BytesMain () at /tmp/build/80754af9/python_1593706424329/work/Modules/main.c:1096
#45 0x00007f93ae5fbbf7 in __libc_start_main (main=0x55ee49ade040 <main>, argc=2, argv=0x7ffe7547f838, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffe7547f828) at ../csu/libc-start.c:310
#46 0x000055ee49ba6553 in _start () at ../sysdeps/x86_64/elf/start.S:103
```

## Expected behavior
Onnx export without segfault

## Environment

 - OS Platform and Distribution: Linux Ubuntu 18.04: Linux x86_64
 - ONNX Runtime version: onnxruntime-1.6.0
 - Python version: Python 3.8.5
 - Pytorch version: 1.7.1
 - How you installed PyTorch (`conda`, `pip`, source): conda
 - CUDA/cuDNN version: CUDA Version: 10.2
 - GPU model and memory: Tesla V100 (32G)

## Additional context

Note: Current problem is gone with the Pytorch version (1.8.0)
But then I got another fail and opened an issue at onnxruntime repo. See here https://github.com/microsoft/onnxruntime/issues/7098

Thanks for the reply!

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof @SplitInfinity

**Comment by BowenBao** [comment] 2023-01-04 17:56
Closing as the issue is resolved.

**Closed by BowenBao** 2023-01-04 17:56 UTC
Labels: module: onnx, triaged, onnx-triaged
