### ISSUE TITLE
The doc of `linalg.matrix_norm()` should say that there is `input` parameter instead of `A` parameter

### ISSUE THREAD

**Issue by hyperkai** [pytorch/pytorch#136619] opened 2024-09-25 09:41 UTC
### 📚 The doc issue

[The doc](https://pytorch.org/docs/stable/generated/torch.linalg.matrix_norm.html) of `linalg.matrix_norm()` says that there is `A` parameter as shown below:

> torch.linalg.matrix_norm(A, ord='fro', dim=(-2, -1), keepdim=False, *, dtype=None, out=None) → [Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)

> A ([Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)) – tensor with two or more dimensions. By default its shape is interpreted as (*, m, n) where * is zero or more batch dimensions, but this behavior can be controlled using dim.

But `A` parameter doesn't work as shown below:

```python
import torch
from torch import linalg

my_tensor = torch.tensor([[-2., -1., 0.],
                          [1., 2., 3.]])
linalg.matrix_norm(A=my_tensor) # Error
```

> TypeError: linalg_matrix_norm() missing 1 required positional arguments: "input"

While `input` parameter works as shown below:

```python
import torch
from torch import linalg

my_tensor = torch.tensor([[-2., -1., 0.],
                          [1., 2., 3.]])
linalg.matrix_norm(input=my_tensor)
# tensor(4.3589)
```

### Suggest a potential alternative/fix

So, [the doc](https://pytorch.org/docs/stable/generated/torch.linalg.matrix_norm.html) of `linalg.matrix_norm()` should say that there is `input` parameter as shown below:

> torch.linalg.matrix_norm(input, ord='fro', dim=(-2, -1), keepdim=False, *, dtype=None, out=None) → [Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)

> input ([Tensor](https://pytorch.org/docs/stable/tensors.html#torch.Tensor)) – tensor with two or more dimensions. By default its shape is interpreted as (*, m, n) where * is zero or more batch dimensions, but this behavior can be controlled using dim.

cc @jianyuh @nikitaved @pearu @mruberry @walterddr @xwang233 @Lezcano

**Comment by lezcano** [comment] 2024-09-26 07:37
Dupe of https://github.com/pytorch/pytorch/issues/136619

If you want to report docs issues with several functions, please open just one tracking issue.

**Closed by lezcano** 2024-09-26 07:37 UTC
Labels: triaged, module: linear algebra, actionable, topic: docs
