### ISSUE TITLE
In-place leakyReLu backward calculation is triggered with a non-positive slope which is not supported

### ISSUE THREAD

**Issue by chanshing** [pytorch/pytorch#37345] opened 2020-04-27 15:08 UTC
## 🐛 Bug

After recently updating to v1.5, I get an error when using `nn.LeakyReLU(0, inplace=True)`:

> RuntimeError: In-place leakyReLu backward calculation is triggered with a non-positive slope which is not supported

I believe it is related to https://github.com/pytorch/pytorch/pull/33639

By changing to `inplace=False` I stop getting the error. As I understand it, the issue is with inplace gradient computation with negative slopes. But shouldn't it still work with slope of _zero_? For example, `ReLU(inplace=True)` works (which is the same as `nn.LeakyReLU(0, inplace=True)`)

## To Reproduce

Just use `nn.LeakyReLU(0, inplace=True)`

## Environment

 - PyTorch Version: 1.5
 - OS: Ubuntu 16.04
 - How you installed PyTorch: `conda`
 - Python version: 3.7
 - CUDA/cuDNN version: 10.2
 - GPU models and configuration: TitanX

cc @ezyang @gchanan @zou3519 @SsnL @albanD @gqchen

**Comment by mrshenli** [comment] 2020-04-27 15:12
adding the "triage-review" tag as this seems to be a regression.

**Comment by gchanan** [comment] 2020-04-27 17:15
I think we should be able to take the derivative when the slope is 0.

**Comment by gchanan** [comment] 2020-04-27 17:16
CC @glaringlee.

**Comment by glaringlee** [comment] 2020-04-28 17:04
@chanshing 
The slope == 0.0 case is disabled for inplace backward calculation since I've thought the gradient calculation for slope==0 case is not predictable under our autograd infrastructure. We just revisited our infrastructure and confirmed the slope == 0 case can be supported. We will fix this shortly.

**Comment by albanD** [comment] 2020-04-29 14:08
The associated PR was merged.

**Closed by albanD** 2020-04-29 14:08 UTC
Labels: high priority, module: autograd, module: nn, topic: regression, triaged
