### ISSUE TITLE
torch.distributed.run future warning in 1.9.0

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60717] opened 2021-06-25 04:33 UTC
## 🐛 Bug

When running `torch.distributed.launch` 1.9.0 now gives a deprecated warning, sure I switch to `torch.distributed.run` - now it gives me a future warning:

```
/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:70: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
```

The past is gone and future isn't quite there yet, where is the present version?

## To Reproduce
```
echo 1 > x
python -m torch.distributed.run --nproc_per_node=2 x
```

```
[...]
/home/stas/anaconda3/envs/py38-pt18/lib/python3.8/site-packages/torch/distributed/elastic/utils/store.py:70: FutureWarning: This is an experimental API and will be changed in future.
  warnings.warn(
```

## Expected behavior

If it's experimental then `run` isn't ready yet and `launch` should be used? If it's the new `launch` then it shouldn't print future warnings, right?

Thank you!

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070 Ti
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu111
[pip3] torch-tb-profiler==0.2.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] mkl                       2021.2.0           h06a4308_296
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.9.0+cu111              pypi_0    pypi
[conda] torch-tb-profiler         0.2.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by zhaojuanmao** [comment] 2021-06-25 15:18
cc @cbalioglu for launcher

**Comment by kiukchung** [comment] 2021-06-26 03:38
Thank you for the report. This warning message should have been removed. I've gone ahead and submitted a PR to address this. https://github.com/pytorch/pytorch/pull/60807

**Comment by stas00** [comment] 2021-06-26 03:48
Thank you very much, @kiukchung !

Will all these changes automatically land in 1.9.1? or do we have to ask explicitly for this to happen?

**Comment by kiukchung** [comment] 2021-06-26 04:46
I'll circle back with the release team to see what we can do and report back. These BC issues do seem offensive enough to warrant a 1.9.1 patch release. We are also addressing your other 4 issues regarding the launcher so do stay tuned!

**Comment by kiukchung** [comment] 2021-06-28 19:58
PR has been merged. Closing this issue since the root cause has been fixed. Please track the release (1.9.1) as part of https://github.com/pytorch/pytorch/issues/60754.

**Closed by kiukchung** 2021-06-28 19:58 UTC
Labels: oncall: distributed

**Comment by kiukchung** [comment] 2021-06-28 23:02
@stas00 I'm keeping #60754 open until a 1.9.1 releases with all the relevant fixes for `torch.distributed.launch`. I'm not sure if whether we use github issues to track releases (I don't think we do). I've engaged the release team to make plans for a patch release with fixes so will update this issue if we end up creating a gh issue specifically to track the patch release. If not I'm keeping #60754 open until we do so that you can track the progress of the patch release from there.

**Comment by stas00** [comment] 2021-06-28 23:26
> I'm not sure if whether we use github issues to track releases (I don't think we do).

You do: https://github.com/pytorch/pytorch/issues/58518

But I don't see one started for 1.9.1 - it probably should be pinned like 1.9.0 was once it's started.

**Comment by kiukchung** [comment] 2021-06-28 23:45
oops should've clarified my statement - meant to say that I wasn't sure whether we have release "anchors" already in place for future releases. Yep those trackers get created once we decide on the release. Will circle back on #60754 with the link to the tracker issue once it is created.
