### ISSUE TITLE
[RPC] Support tensor shared_memory between processes on the same server 

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#24920] opened 2019-08-20 19:03 UTC
As pointed out by @zzzwen, current `distributed.rpc` implementation always serializes a tensor into bytes and creates a new tensor (and storage) during deserialization. For processes on the same server, it will be much more efficient if we can enable shared memory across processes. The basic idea is to do something similar to [`sharedFd`](https://github.com/pytorch/pytorch/blob/master/torch/csrc/generic/StorageSharing.cpp#L153) (thanks @yf225 ), and serialize the shared-memory tensor into `fd` and `size`. During deserialization, it will just attach the same storage to the new tensor. 

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera

**Comment by aazzolini** [comment] 2019-08-21 18:25
I believe this is pretty much what the pytorch custom storage reducer is currently doing in the ForkingPickler. Depending on the type of shared_memory it will do either what you described or filename if that method has been chosen.

**Comment by pietern** [comment] 2019-11-22 13:52
After much discussion, we decided not to support this because it invalidates the assumption of isolation. A tensor in shared memory can be modified by both the sender and the receiver. For something like a data loader, there is a well defined policy of a producer and a consumer of the data. For RPC this is not the case. Allowing for shared memory tensors to pass through can cause unintended behavior, means behavior within a machine and across machines is different, and will surely lead to many hard to debug numerical issues.

Closing the issue.

**Closed by pietern** 2019-11-22 13:52 UTC
Labels: feature, module: rpc, triaged
