### ISSUE TITLE
`torch.where` to support Python scalars and type promotion

### ISSUE THREAD

**Issue by vadimkantorov** [pytorch/pytorch#9190] opened 2018-07-05 18:52 UTC
```python
a = torch.Tensor([1, 2, 3])

# works, correctly produces tensor([-1.,  2.,  3.])
b = torch.where(a == 1, torch.Tensor([-1]), a)

# fails: TypeError: where(): argument 'input' (position 2) must be Tensor, not int
c = torch.where(a == 1, -1, a)

# works in numpy
np.where(a.numpy() == 1, -1, a.numpy())

# both fail: RuntimeError: expected scalar type Long but found Float
d = torch.where(a == 1, torch.tensor(-1), a)
d = torch.where(a == 1, torch.tensor([-1]), a)
```

cc @nairbv @mruberry @rgommers @pmeier @asmeurer @leofang @AnirudhDagar @asi1024 @emcastillo @kmaehashi

**Comment by t-vi** [comment] 2018-07-05 19:08
Python scalars are one thing, but
```
# both fail: RuntimeError: expected scalar type Long but found Float
d = torch.where(a == 1, torch.tensor(-1), a)
d = torch.where(a == 1, torch.tensor([-1]), a)
```
Yeah, but we never support mixing float and long tensors and maybe we shouldn't. The two cases work as expected when you fix your dtype:
```
d = torch.where(a == 1, torch.tensor(-1.), a)
d = torch.where(a == 1, torch.tensor([-1.]), a)
```
Best regards

Thomas

**Comment by t-vi** [comment] 2018-07-05 20:04
Well, it's the first relevant argument that determines the type. If you pass a long tensor as the first data argument, it expects the second to be one, too.

**Comment by bhushan23** [comment] 2018-07-05 20:15
I agree with @t-vi, user should specify with dtype.
Regarding scalar, I think we should support it. It is really intuitive to pass scalar here and we should be creating tensor out of it internally

**Comment by zou3519** [comment] 2018-07-09 17:37
> Yeah, but we never support mixing float and long tensors and maybe we shouldn't.

I think we're adding support for this. [This pr](https://github.com/pytorch/pytorch/pull/8919) could be a start

**Comment by vadimkantorov** [comment] 2018-10-31 13:55
Also, if the first argument is allowed to be a floating-point mask (instead of byte tensor), then a gradient may be backpropped through it as well.

**Comment by t-vi** [comment] 2018-10-31 14:20
And the gradient would be?

**Comment by vadimkantorov** [comment] 2018-10-31 14:31
it may come from this formula (modulo handling of the sum to avoid nan's): `torch.where(mask, a, b) := mask * a + (mask == 0) * b` but it may still be unintuitive for the negative case.

Another possible useful function is just linear interpolation that handles NaN's and Inf's (e.g. for computing entropy `p * log(p)` without problems when p == 0):
`convex_combination(gate, a, b) := gate * a + (1 - gate) * b`

**Comment by t-vi** [comment] 2018-10-31 14:55
The first isn't a valid gradient, because for `gate != 0` it shows a gradient when the function wouldn't change for a change in `gate`. By definition, the `where` function is either `a` or `b`, so it is a genuinely discrete-valued function of `gate`, and should not provide gradients for it.
So it probably is much better to have convex_combination if you need that, but it would be a different bug.

**Comment by vadimkantorov** [comment] 2018-10-31 15:19
@t-vi The first case is kind of equivalent `sparse_mul` (where there is no gradient to the strictly zero elements and gradient passes to nonzero elements), I guess.

**Comment by vadimkantorov** [comment] 2019-10-03 09:46
Recently had to write ` torch.ones_like(grad_output).masked_fill_(saved_input < 0, leaky_relu_param)` instead of `torch.where(saved_input < 0, leaky_relu_param, 1.0)`. For `torch.tensor(1.0)` route explicit devices are needed which makes it more cumbersome.

**Comment by vadimkantorov** [comment] 2019-12-26 02:52
Some cases wished to work:
```python
torch.where(torch.tensor([False, True]).cuda(), torch.rand(2).cuda(), 0)
# problem with python scalar

torch.where(torch.tensor([False, True]).cuda(), torch.rand(2).cuda(), torch.tensor(0.))
# problem with device

torch.where(torch.tensor([False, True]).cuda(), torch.rand(2).cuda(), torch.tensor(0).cuda())
# problem with dtype

torch.where(torch.tensor([False, True]).cuda(), torch.rand(2).cuda(), torch.tensor(0))
# problem with dtype and device
```

**Comment by vadimkantorov** [comment] 2019-12-26 02:54
although https://github.com/pytorch/pytorch/pull/29078 made it so that type casting won't work, but I think it's useful for cases when one of arguments is scalar

**Comment by t-vi** [comment] 2019-12-26 07:15
Also,
```
In[2]: numpy.where(numpy.random.randn(10)>0, numpy.zeros(10, dtype=numpy.float), numpy.ones(10, dtype=numpy.int))
Out[2]: array([0., 1., 1., 0., 1., 0., 1., 0., 0., 1.])
```
seems pretty sensible behaviour, I'm not sure why PyTorch would not do that.

**Comment by vadimkantorov** [comment] 2020-01-27 02:33
Another instance of uneconomical zero-array allocation that could be saved by torch.where accepting scalars: https://github.com/pytorch/pytorch/pull/32616/files

**Comment by vadimkantorov** [comment] 2020-09-18 11:25
@kshitij12345 Does it support `torch.where(torch.BoolTensor([True, False]), 3, 4)` i.e. where all arguments except condition are scalars / Python scalars?

**Comment by kshitij12345** [comment] 2020-09-18 11:33
> @kshitij12345 Does it support torch.where(torch.BoolTensor([True, False]), 3, 4) i.e. where all arguments except condition are scalars / Python scalars?

As far as I recall, that should work. I can confirm if it works or not in few hours.

**Comment by kshitij12345** [comment] 2020-09-20 07:39
```python
>>> import torch
>>> torch.where(torch.BoolTensor([True, False]), 3, 4)
tensor([3, 4])
```

**Comment by glaringlee** [comment] 2021-01-05 23:29
assign to myself, this is a good task for onboarding new team member.

**Comment by mruberry** [comment] 2021-01-06 15:19
> assign to myself, this is a good task for onboarding new team member.

fyi @glaringlee this could actually be very tricky to implement and test.

**Comment by glaringlee** [comment] 2021-01-06 18:02
@mruberry 
Thanks for letting me know! It seems to me that we have 2 problems here, type mixed and device mixed. We can probably fix type mixed (promotion) first and for device mixed issue, I am not sure whether we should support. 

The Tensoriterator will promote the input condition tensor as well, without changing the Tensoriterator, I guess what we can do instead is to get the promoted type from iter and  tweak the passed in kernel op here:
https://github.com/pytorch/pytorch/blob/15200e385a764721000f1dfadbcaf42c328bafdd/aten/src/ATen/native/cpu/TensorCompareKernel.cpp#L186
But need to make sure this will not affect the correctness. 
Let's discuss this further if our new team member is interested on doing this.

**Comment by vadimkantorov** [comment] 2021-01-06 18:55
Just to be sure, wasn't this issue fixed in https://github.com/pytorch/pytorch/pull/40336? what's left to be done?

**Comment by mruberry** [comment] 2021-01-06 19:02
> Just to be sure, wasn't this issue fixed in #40336 and this one was kept to not forget to fix the docs? what's left to be done?

Type promotion.

```
torch.where(torch.tensor((True, False)), torch.tensor((1., 2.)), 3)
: RuntimeError: expected scalar type float but found long int
```

**Comment by LoicGrobol** [comment] 2021-01-13 18:11
The lack of type promotion also makes is hard to deal with floats

```pycon
>>> torch.where(torch.tensor((True, False)), torch.tensor((1., 2.), dtype=torchfloat32), 3.0)
RuntimeError: expected scalar type float but found double
```

**Comment by vadimkantorov** [comment] 2021-07-20 17:51
Two recent quirks:
```
$ python -c 'import torch; torch.where(torch.ones(3) == 1, 1, torch.zeros(3))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: expected scalar type long int but found float
$ python -c 'import torch; torch.where(torch.ones(3) == 1, 1.0, torch.zeros(3))'

Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: expected scalar type double but found float
```

**Comment by vadimkantorov** [comment] 2022-02-08 18:27
Fixed in https://github.com/pytorch/pytorch/pull/62084

**Comment by ngimel** [comment] 2022-05-04 17:45
Fixed

**Closed by ngimel** 2022-05-04 17:45 UTC
Labels: triaged, module: type promotion, module: sorting and selection, function request, module: python array api

**Comment by vadimkantorov** [comment] 2022-06-29 23:44
Related? https://github.com/pytorch/pytorch/issues/80508

**Comment by thomasw21** [comment] 2023-05-12 15:36
Does it make sense to allow typical tensor constructor options to be available to `torch.where` when using two scalars?
```python
>>> torch.where(torch.BoolTensor([True, False]), 3, 4)
tensor([3, 4])
>>> torch.where(torch.BoolTensor([True, False]), 3, 4, dtype=torch.float16)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: where(): argument 'input' (position 2) must be Tensor, not float
```
