### ISSUE TITLE
ROCM runners timeout

### ISSUE THREAD

**Issue by huydhn** [pytorch/pytorch#90940] opened 2022-12-15 19:40 UTC
### 🐛 Describe the bug

We are seeing ROCM jobs timing out more frequently https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=rocm.  These jobs stuck while running tests and timeouts after 4+ hours while they normally only take about 3h to finish.  This happens on both the first and second shards and might be due to bad runners or due to a recent change (rocm5.3 migration?).  Here are some examples:

* https://hud.pytorch.org/pytorch/pytorch/commit/9b89ff0923251d2a30ceccf61120d051a687557c (worker-rocm-amd-30)
* https://hud.pytorch.org/pytorch/pytorch/commit/d6fe9838d19a5dee60410b3b9212bf10a43105a4 (worker-rocm-amd-64)
* https://hud.pytorch.org/pytorch/pytorch/commit/cdf4a80cc111b210f9ab9448da5aeea2007a0171 (worker-rocm-amd-42)

### Versions

ROCM

cc @jeffdaily @sunway513 @jithunnair-amd @pruthvistony @ROCmSupport @seemethere @malfet @pytorch/pytorch-dev-infra

**Comment by pruthvistony** [comment] 2022-12-15 20:30
We are suspecting this is happening due to running the test_*.py files in parallel. Checking on it

**Comment by jeffdaily** [comment] 2022-12-15 20:46
This started happening while still on ROCm 5.2, so isn't due to ROCm 5.3 upgrade.  It isn't specific to one or more runners, either.  Not sure why it is ROCm-specific.  We are considering not running two test files concurrently since this is the only info we could glean from the various log files.  It isn't one specific combination of running two test_*.py files, either.  We've seen various pairs of test files running concurrently that seem to stall.  Frustratingly, we have not been able to reproduce the hang when running the exact same CI steps on our development hosts.

**Comment by jeffdaily** [comment] 2022-12-19 18:30
Seeing dmesg errors on workers 30, 42, 64, 76, 86.  Rebooting them.

**Comment by huydhn** [comment] 2023-01-03 17:42
Periodic distributed rocm test has been temporarily disabled by https://github.com/pytorch/pytorch/pull/91632

**Comment by huydhn** [comment] 2023-01-05 18:45
It looks like time out error still happens after https://github.com/pytorch/pytorch/pull/91137 is in, i.e. https://hud.pytorch.org/hud/pytorch/pytorch/master/1?per_page=50&name_filter=rocm

**Comment by jeffdaily** [comment] 2023-01-05 19:04
Thanks for reopening.  Still looking at this.

**Comment by jeffdaily** [comment] 2023-01-12 20:20
We believe the timeouts were due to two different reasons, a KFD bug and a HIP IPC bug.  

We believe the KFD bug is triggered by running multiple processes on the same GPU.  It manifests as a hang, or less frequently as a memory access fault that then triggers a SIGIOT.  We know this from looking at dmesg logs.  `amdgpu: HIQ MQD's queue_doorbell_id0 is not 0, Queue preemption time out`, sometimes preceding a memory access fault.

The HIP IPC bug we believe to be latent.  We're saying "HIP IPC" because it manifests in test_multiprocessing or test_dataloader's use of multiprocessing with shared CUDA/HIP tensors.  We haven't yet root caused, but are leaning this way.

File granularity parallelism for tests started on Oct 3.  This starts putting NUM_PROCS=2 parallel processes using the same HIP_VISIBLE_DEVICES=0.

https://github.com/pytorch/pytorch/pull/85770

We see the first timeout on Nov 23.  A bit surprising it took this long, but it might have to do with how many test modules were present, the order they are executed, which ones are in the parallel set, etc.  This was a ROCm 5.2 docker image running on ROCm 4.2 KFD. 
 test_multiprocessing hung.  Unfortunately, we do not have logs showing the subtest or any dmesg logs.

https://hud.pytorch.org/pytorch/pytorch/commit/22a1b5e243e852e1c423c697e51975d1545d2a1b

Next, on Dec 6, we see a SIGIOT in test_ops running 2 shards on GPU 0.  Again, ROCm 5.2 docker image running on ROCm 4.2 KFD but no dmesg logs available.

https://hud.pytorch.org/pytorch/pytorch/commit/887249b2bb99e8807619a6df126c780eea15c74b

Then on Dec 7 there is a series of time outs due to a commit https://hud.pytorch.org/pytorch/pytorch/commit/cbb2d5af81dcfaf181db7e9083b9c41b29fdb4eb that is eventually reverted the next day.  This commit modified the test_multiprocessing specifically and caused a consistent hang.  The logs do not reveal which subtest was hanging.  The same commit was relanded on Dec 15 but seemingly without timeouts.

The next timeout we see is at this commit on Dec 9.

https://hud.pytorch.org/pytorch/pytorch/commit/282dfe8ba4d514b0b1ad41edcfcb253cac9582f6

I looked at the logs at it hung inside test_meta and test_schema_check running concurrently, but no useful logs to say why.  Other than this occurred on worker 86, which dmesg logs from that time period contain the warning about Queue preemption time out.

The next timeout is the revert of the above commit.  So it can't possibly be the root cause.  It hung right out of the gate, the first two test files running in parallel were hung.  test_unary_ufuncs and test_constraints.  This was worker 76.  dmesg shows similar Queue preemption time out.

https://hud.pytorch.org/pytorch/pytorch/commit/b2795d3c4eeff929a368f7b51492d0cfab2c3547

Still on Dec 9, the next timeout.  Worker 76 again.  This time it hung during the tests test_jit_fuser_te.py and test_meta.py.

https://hud.pytorch.org/pytorch/pytorch/commit/bb9fc32fe087af63b82de48eb2ebf2afa1e74629

Dec 10, similar time out on worker 76.  test_meta and test_jit_fuser_te again.

https://hud.pytorch.org/pytorch/pytorch/commit/9ef1d55e6b85f089f5d1f5a221b2dda4e7c052b2

Dec 10 again, but two hangs in two jobs for the same commit.  Worker 76 again.  Starting to think these timed-out workers are in a bad state and need a reboot.  test_meta and test_quantization hung this time.

https://hud.pytorch.org/pytorch/pytorch/commit/c7d2fb7f8649b798d805c18f3c1d21abd0bdb2dd

We also see our first distributed job time out.  Worker 30.  dmesg same as other failed hosts.  distributed jobs can ONLY run one file at a time and are part of the must_serial set of test modules because they spawn additional processes as part of the test.  This one hung during distributed/test_c10d_spawn_gloo.

There are sporadic time outs between Dec 10 and Dec 19 when I rebooted all workers that had shown the queue preemption dmesg errors.  30, 42, 64, 76, 86.

Dec 15, we start to take nodes down a few at a time for KFD and ubuntu upgrades.

Around Dec 20-ish, test_c10_spawn_gloo is hanging basically every time it runs, doesn't matter which host it runs on.  

Dec 20, ROCm CI gets disabled.  We begin all host upgrades in earnest while we're down.

Dec 22, host upgrades are complete.  CI is turned back on.

Jan 3, back in office after holiday, timeouts still occurring.  test_c10_spawn_gloo almost all the time.  Still not seeing any consistency in which test modules cause the hang.  Still suspect GPU oversubscription as the issue.

Jan 4 commit to fix device visibility is merged.  Still hangs.  There was a bug in that first attempt.  Jan 6 commit to further fix device visibility is merged.  Still hangs.  Check all CI hosts again for dmesg errors and rebooted them on Jan 10.

For last 2 days we only see test_dataloader and test_multiprocessing hang.  Will submit PR to skip the affected tests.  We were able to reproduce on worker 20 after taking it out of the CI pool.  Triage underway.

**Comment by jeffdaily** [comment] 2023-01-12 23:51
We were able to repro the hang in test_dataloader.py TestDataLoader.test_multiprocessing_contexts.

```
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      129442  0.0  0.0   6672  2812 pts/0    S+   Jan11   0:01 bash
root     2063495  0.0  0.1 24668896 747956 pts/0 Sl+  14:06   0:11  \_ python test/test_dataloader.py TestDataLoader.test_multiprocessing_contexts -v
root     2063563  0.0  0.0 24516072 319972 pts/0 Sl+  14:06   0:00      \_ python test/test_dataloader.py TestDataLoader.test_multiprocessing_contexts -v
root     2063626  0.0  0.0 24515828 309888 pts/0 Sl+  14:06   0:00      \_ python test/test_dataloader.py TestDataLoader.test_multiprocessing_contexts -v
root     2063689  0.0  0.0 24515840 316784 pts/0 Sl+  14:06   0:00      \_ python test/test_dataloader.py TestDataLoader.test_multiprocessing_contexts -v
```

We ran just that subtest in the test_dataloader module in a loop.  It ran for a few hours before hanging.  gdb attaching to each of the above 4 processes doesn't reveal much other than ROCm was not really being used.  In the parent, the ROCr runtime was initialized and it started its event polling loop.  The three children were created, and then nothing.  

The last output is simply
```
Test results will be stored in test-reports/python-unittest/test.test_dataloader

Running tests...
----------------------------------------------------------------------
```

**Comment by jeffdaily** [comment] 2023-01-13 17:28
For the PR that skips the hanging tests, it did not go far enough in test_multiprocessing.  The PR itself encountered the time out.  test_multiprocessing.test_cuda_memory_allocation.  Will skip all IPC tests now, not just piecemeal.

**Comment by jeffdaily** [comment] 2023-01-13 20:41
The test_dataloader repro was a false positive.  It failed due to out of space on /dev/shm device which is not the same reason we see hangs in multiprocessing tests.  Still trying to repro locally.

**Comment by jeffdaily** [comment] 2023-01-27 21:52
I think we can close this now.  Haven't seen timeouts since #92101 merged.

**Closed by jeffdaily** 2023-01-27 21:52 UTC
Labels: module: rocm, module: ci, triaged
