### ISSUE TITLE
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.

### ISSUE THREAD

**Issue by donhuvy** [pytorch/pytorch#94194] opened 2023-02-06 17:15 UTC
### 🐛 Describe the bug

```
Microsoft Windows [Version 10.0.22621.1105]
(c) Microsoft Corporation. All rights reserved.

C:\Windows\System32>pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cu118
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Looking in indexes: https://download.pytorch.org/whl/nightly/cu118, https://pypi.ngc.nvidia.com
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /whl/nightly/cu118/torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /whl/nightly/cu118/torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /whl/nightly/cu118/torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /whl/nightly/cu118/torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /whl/nightly/cu118/torch/
Could not fetch URL https://download.pytorch.org/whl/nightly/cu118/torch/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /whl/nightly/cu118/torch/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /torch/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /torch/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /torch/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /torch/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError("Can't connect to HTTPS URL because the SSL module is not available.")': /torch/
Could not fetch URL https://pypi.ngc.nvidia.com/torch/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.ngc.nvidia.com', port=443): Max retries exceeded with url: /torch/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
Could not fetch URL https://download.pytorch.org/whl/nightly/cu118/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='download.pytorch.org', port=443): Max retries exceeded with url: /whl/nightly/cu118/pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping
Could not fetch URL https://pypi.ngc.nvidia.com/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.ngc.nvidia.com', port=443): Max retries exceeded with url: /pip/ (Caused by SSLError("Can't connect to HTTPS URL because the SSL module is not available.")) - skipping

C:\Windows\System32>WARNING: pip is configured with locations that require TLS/SSL, however the ssl module in Python is not available.
```

### Versions

error.

![image](https://user-images.githubusercontent.com/1328316/217039363-a86580d3-687f-4927-aa9c-ecfd6c781220.png)

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm

**Comment by malfet** [comment] 2023-02-06 17:41
This does not sound like a PyTorch problem to me, but rather issue with your Python runtime. What version of python is it? How did you installed it?

**Comment by donhuvy** [comment] 2023-02-06 18:00
Thanks @malfet  , It is **Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32** https://gist.github.com/donhuvy/189964a635e506288b91abd2cbbf9493

**Comment by vladimir-aubrecht** [comment] 2023-06-05 12:32
Hi @donhuvy! Did you managed to solve the problem?

If not, where did you downloaded those binaries and how did you install it? Link is showing just installation of PyTorch, not Python. Your problem is caused by problem with Python, not PyTorch.

**Comment by vladimir-aubrecht** [comment] 2023-06-12 11:36
Closing as it's not PyTorch issue, but Python one. Feel free to create new issue if needed.

**Closed by vladimir-aubrecht** 2023-06-12 11:36 UTC
Labels: needs reproduction, module: windows, triaged
