### ISSUE TITLE
Backward kernels are always put on the default stream

### ISSUE THREAD

**Issue by ngimel** [pytorch/pytorch#7601] opened 2018-05-15 23:39 UTC
## Issue description
Streams in THC are thread local, so in backward, since autograd creates its own threads, kernels are always put on the default streams, and don't respect stream that was set previously. 
## Code example
```
import torch

a=torch.Tensor(128,512).cuda().uniform_()

model = torch.nn.Linear(512,512).cuda()

fwd_stream = torch.cuda.Stream()
bwd_stream = torch.cuda.Stream()


for i in range(3):
   with torch.cuda.stream(fwd_stream):
       out = model(a).sum()
   with torch.cuda.stream(bwd_stream):
       out.backward() #kernels are actually on the default stream
   a.detach()
```

Pytorch, current master

**Comment by apaszke** [comment] 2018-05-16 06:50
I don’t think anything like this should even work. What if the backward uses multiple devices? A single stream is not enough, and so the standard API is insufficient. This said, I think having a context manager for setting them (possible on all devices) would be useful. Should be a simple extension to the engine

**Comment by zou3519** [comment] 2018-05-21 17:41
Maybe it makes sense to record the streams that are used in the forward operator and respect those in the backward?

**Comment by apaszke** [comment] 2018-05-22 09:36
The danger is that you don't have a guarantee that the streams won't be destroyed before `backward`.

**Comment by soumith** [comment] 2018-05-22 13:52
streams can be re-allocated if destroyed. I dont think that danger is very common (I cant think of much cases except if you construct a test case)

**Comment by apaszke** [comment] 2018-05-22 14:41
Well that requires some complicated bookkeeping because now you not only need to associate a stream with every function, but you also need to track their lifetime. How expensive is it to change streams?

**Comment by ezyang** [comment] 2018-12-18 17:23
We can address this issue now, because we pool streams, so streams are guaranteed not to be destroyed before the backwards

**Comment by ezyang** [comment] 2018-12-18 17:23
cc @mruberry

**Comment by ezyang** [comment] 2019-07-29 15:41
FYI @mruberry is working on this (I can't assign him yet because he hasn't accepted his GitHub invite yet.)

**Comment by mruberry** [comment] 2019-07-29 16:38
Got it, thanks Ed!

**Comment by mruberry** [comment] 2019-09-11 06:56
#8354 has been merged and backward no longer exclusively uses default streams.

**Closed by mruberry** 2019-09-11 06:56 UTC
Labels: feature, module: cuda, triaged

**Comment by dmitrivainbrand** [comment] 2020-02-18 22:45
Hi guys,
I've got a reversed problem now. I need to set a different stream order for backward. For simplicity, let's say  I want my backward function NOT to respect the the forward streams and run the backward on a default stream. How can I do that now? Even writing a custom `torch.autograd.Function` and setting a stream to default doesn't seem to help.

**Comment by mruberry** [comment] 2020-02-18 22:49
I think we'd have to update the autograd API with a flag like `default_stream=False` to let you do this. Why, by the way, do you want to do this?

**Comment by dmitrivainbrand** [comment] 2020-02-18 23:04
Hi Mike, 
Glad you asked :)
The real underling problem is that the stream order I designed for forward() needs to be reversed for backward(). E.g. If I make stream(a) to wait on stream(b) in forward(), I need it to be reversed in backward(). This doesn't seem to happen automatically and task dependency gets broken. I'm guessing fixing that is heavy lift, so, as a WAR I want to run backward() without streams to fix the dependency.
Here is a snippet of my forward code to . I'm trying to do GPipe multi-GPU pipelining here:
`        for i, chunk in enumchunks:
            print('forward chunk', i, "on device", (i % self.mp_ngpus))
            for s,x in enumerate(chunk_outs):
                cur_gpu = i % self.mp_ngpus
                prev_gpu = (i-1) % self.mp_ngpus
                cur_ub = s % self.num_microb
                prev_ub = (s-1) % self.num_microb
                with torch.cuda.stream(multi_gpu_streams[prev_gpu][cur_ub]), torch.cuda.stream(multi_gpu_streams[cur_gpu][cur_ub]):
                    x=x.to(torch.device(cur_gpu))
                with torch.cuda.stream(multi_gpu_streams[cur_gpu][cur_ub]):
                    torch.cuda.current_stream().wait_stream(multi_gpu_streams[cur_gpu][prev_ub])
                    torch.cuda.current_stream().wait_stream(multi_gpu_streams[prev_gpu][cur_ub])
                    chunk_outs[s] = chunk(x)
        torch.cuda.synchronize(last_gpu)
        return torch.cat(chunk_outs)

**Comment by mruberry** [comment] 2020-02-18 23:15
The sync behavior you describe should be happening automatically. Can you provide a snippet showing where it fails?

**Comment by dmitrivainbrand** [comment] 2020-02-18 23:38
Mu hunch it has something to do with p2p copies not being accounted for when reversing dependencies...
I've got NVPROF-NVVP pictures. Will that help?

**Comment by mruberry** [comment] 2020-02-18 23:43
@mcarilli recently fixed a bug in streaming backward with cross-device synchronization. Would you check with him? If this is happening on a recent PyTorch build it would be very interesting.

**Comment by dmitrivainbrand** [comment] 2020-02-19 00:05
Thanks, I'll check with him and report back

**Comment by dmitrivainbrand** [comment] 2020-02-19 00:42
Regardless, I think adding an option to opt-out from streaming, e.g. `default_stream=False` in autograd API, could be a good feature to have.

**Comment by dmitrivainbrand** [comment] 2020-02-19 21:08
UPD: I tried the latest build and it seem to work! I don't have a numeric test yet to confirm it with 100% confidence but the fix **appears** to resolve all the data races in my case!
 @mcarilli and @mruberry  - thanks!!!

Maybe one thing to keep in mind - in some cases we'd synchronize streams for speedup purposes and not because of data dependencies. It would be nice if backprop respects manual dependencies instrumented into forward() even though they don't have an associated data dependency. I understand this may be challenging.

**Comment by dmitrivainbrand** [comment] 2020-02-27 01:20
**UPD**: after proper numerical testing, it appeared that the case was still broken with the latest build. As I said, it seem as producer-consumer dependencies were all kept and respected, but the diffs between no-stream and multi-stream version of the same code were consistently large. @mcarilli suspected that the problem is with the cache allocator and proposed to add .recodStream() to synchronize the allocators with the consumer stream. It worked like a charm! The no-stream vs. with-streams are now bit-exact... Almost always... Except for once in 20-30 runs or so, I see some non-deterministic behavior that causes diffs with order of magnitude of 1E-9. I'm not sure it's even related...

**The change:**  
added the line: `        c10::cuda::CUDACachingAllocator::recordStream(var.storage().data_ptr(), c10::cuda::CUDAStream(*opt_accumulate_stream));
`
after each`wait(event)`; in autograd/input_buffer.cpp 
```c++ 
  if (device_of(var)->is_cuda()) {
    const auto on_producer = opt_producer_stream
                        && device_of(var) == opt_producer_stream->device();
    const auto on_consumer = opt_consumer_stream
                        && device_of(var) == opt_consumer_stream->device();
    if (on_producer && on_consumer) {
      // (2a)
      opt_accumulate_stream = opt_consumer_stream;
      if (opt_accumulate_stream != opt_producer_stream) {
        // (2b)
        auto event = c10::Event{c10::DeviceType::CUDA};
        event.record(*opt_producer_stream);
        opt_accumulate_stream->wait(event);
        c10::cuda::CUDACachingAllocator::recordStream(var.storage().data_ptr(), c10::cuda::CUDAStream(*opt_accumulate_stream));
      }
    } else {
      c10::optional<c10::Stream> opt_sync_stream = c10::nullopt;
      const auto guard = c10::impl::VirtualGuardImpl{c10::DeviceType::CUDA};
      if (on_consumer && !on_producer) {
        // (3a)
        opt_accumulate_stream = opt_consumer_stream;
        opt_sync_stream = guard.getDefaultStream(opt_consumer_stream->device());
        TORCH_INTERNAL_ASSERT(opt_sync_stream == guard.getStream(*device_of(var)));
      } else if (on_producer && !on_consumer) {
        // (4a)
        opt_accumulate_stream = guard.getDefaultStream(opt_producer_stream->device());
        opt_sync_stream = opt_producer_stream;
      } else {
        // (5)
        opt_accumulate_stream = guard.getDefaultStream(*device_of(var));
      }
      if (opt_sync_stream && (opt_accumulate_stream != opt_sync_stream)) {
        // (3b), (4b)
        c10::OptionalDeviceGuard device_guard{opt_sync_stream->device()};
        auto event = c10::Event{c10::DeviceType::CUDA};
        event.record(*opt_sync_stream);
        opt_accumulate_stream->wait(event);
        c10::cuda::CUDACachingAllocator::recordStream(var.storage().data_ptr(), c10::cuda::CUDAStream(*opt_accumulate_stream));
      }
    }

**Comment by mruberry** [comment] 2020-02-27 06:52
Great you have a workaround, @dmitrivainbrand! I spoke with @mcarilli and we'll coordinate a follow-up. He may ask you to open a tracking issue.
