### ISSUE TITLE
Add support for numpy arrays in default collate_fn

### ISSUE THREAD

**Issue by bodokaiser** [pytorch/pytorch#782] opened 2017-02-18 19:01 UTC
I am working with a dataset which contains some target labels I want to filter before training.

```python
dataloader = DataLoader(dataset, batch_size=128)

def batch_filter(target):
    return np.any(target[0]) and np.any(target[1])

loader = filter(lambda (_, target): np.any(target), dataloader)
next(loader)
```

Yields:

```
/Users/bodokaiser/.virtualenvs/mrtous-pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py in __next__(self)
    144                 raise StopIteration
    145             indices = self._next_indices()
--> 146             batch = self.collate_fn([self.dataset[i] for i in indices])
    147             if self.pin_memory:
    148                 batch = pin_memory_batch(batch)

/Users/bodokaiser/.virtualenvs/mrtous-pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py in default_collate(batch)
     73         # of tensors; in that case we collate each element in the tuple
     74         transposed = zip(*batch)
---> 75         return [default_collate(samples) for samples in transposed]
     76 
     77     raise TypeError(("batch must contain tensors, numbers, or lists; found {}"

/Users/bodokaiser/.virtualenvs/mrtous-pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py in <listcomp>(.0)
     73         # of tensors; in that case we collate each element in the tuple
     74         transposed = zip(*batch)
---> 75         return [default_collate(samples) for samples in transposed]
     76 
     77     raise TypeError(("batch must contain tensors, numbers, or lists; found {}"

/Users/bodokaiser/.virtualenvs/mrtous-pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py in default_collate(batch)
     73         # of tensors; in that case we collate each element in the tuple
     74         transposed = zip(*batch)
---> 75         return [default_collate(samples) for samples in transposed]
     76 
     77     raise TypeError(("batch must contain tensors, numbers, or lists; found {}"

/Users/bodokaiser/.virtualenvs/mrtous-pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py in <listcomp>(.0)
     73         # of tensors; in that case we collate each element in the tuple
     74         transposed = zip(*batch)
---> 75         return [default_collate(samples) for samples in transposed]
     76 
     77     raise TypeError(("batch must contain tensors, numbers, or lists; found {}"

/Users/bodokaiser/.virtualenvs/mrtous-pytorch/lib/python3.6/site-packages/torch/utils/data/dataloader.py in default_collate(batch)
     72         # if each batch element is not a tensor, then it should be a tuple
     73         # of tensors; in that case we collate each element in the tuple
---> 74         transposed = zip(*batch)
     75         return [default_collate(samples) for samples in transposed]
     76 

TypeError: zip argument #65 must support iteration
```

Maybe we can add extra case handler for this?

**Comment by apaszke** [comment] 2017-02-19 18:06
It's an error in your dataset definition, but I can't help you without seeing the code. I ran the snippet with one of the vision datasets and it was fine.

**Comment by bodokaiser** [comment] 2017-02-19 18:08
Then I guess this must be something in h5py?

```python
import os
import h5py
import numpy as np

from torch.utils.data import Dataset, DataLoader

class MINC2(Dataset):
    def __init__(self, filename):
        self.minc = h5py.File(filename, 'r')
        self.volume = self.minc['minc-2.0/image/0/image']
        self.vrange = self.minc['minc-2.0/image/0/image'].attrs['valid_range']
        self.xlength = self.minc['minc-2.0/dimensions/xspace'].attrs['length']
        self.ylength = self.minc['minc-2.0/dimensions/yspace'].attrs['length']
        self.zlength = self.minc['minc-2.0/dimensions/zspace'].attrs['length']

    def __getitem__(self, index):
        slice = np.array(self.volume[index])
        return slice / np.sum(np.abs(self.vrange))

    def __len__(self):
        return self.zlength

def format_path(directory, filename, params):
    return os.path.join(directory, filename.format(params))

class MNIBITE(Dataset):
    def __init__(self, directory, id, transform=None):
        self.mr = MINC2(format_path(directory, '{}_mr.mnc', id))
        self.us = MINC2(format_path(directory, '{}_us.mnc', id))
        self.transform = transform

    def __getitem__(self, index):
        mr = self.mr[index]
        us = self.us[index]
        if self.transform is not None:
            mr, us = self.transform(mr, us)
        return mr, us

    def __len__(self):
        return len(self.mr)
```

**Comment by apaszke** [comment] 2017-02-19 18:13
I think the problem is that you return a numpy array from the dataset, but it should be a Tensor. Use `torch.from_numpy` to convert it before the `return`.

Nevertheless, I think it would make sense to support ndarrays too, so I'm reopening the issue with a different name.

**Comment by soumith** [comment] 2017-02-21 07:30
fixed in master

**Closed by soumith** 2017-02-21 07:30 UTC
Labels: enhancement, medium priority
