### ISSUE TITLE
test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA) error

### ISSUE THREAD

**Issue by KyleCZH** [pytorch/pytorch#77236] opened 2022-05-11 07:46 UTC
A recent PR https://github.com/pytorch/pytorch/pull/76790 causes consistent failure in rocm ci

test currently disabled in https://github.com/pytorch/pytorch/issues/77237 

full log: https://ossci-raw-job-status.s3.amazonaws.com/log/6376085362
error signature:
```
ERROR [0.453s]: test_broadcast_in_dim_cuda_float32 (__main__.TestPrimsCUDA)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/_prims/executor.py", line 64, in execute
    tuple(arg for arg in args if isinstance(arg, torch.Tensor))
RuntimeError: false INTERNAL ASSERT FAILED at "/var/lib/jenkins/workspace/torch/csrc/jit/codegen/cuda/executor_utils.cpp":1054, please report a bug to PyTorch. namespace CudaCodeGen {
```

@jeffdaily @pruthvistony

**Comment by davidberard98** [comment] 2022-05-12 21:29
@KyleCZH do you know how nvfuser is being enabled in this case?

At the time that this issue was opened, NVFuser was disabled by default (it was enabled on master around 1pm PST https://github.com/pytorch/pytorch/pull/77213)

But even after it's enabled by default, it still should be disabled automatically on rocm:
https://github.com/pytorch/pytorch/blob/master/torch/csrc/jit/codegen/cuda/interface.cpp#L40-L47

Or is this check somehow getting called even when nvfuser is disabled?

**Comment by jeffdaily** [comment] 2022-05-12 21:57
@davidberard98 no we do not have a root cause why nvfuser was enabled in this case.  And as you pointed out in the codegen for nvfuser, it should never be possible for rocm at this time (work is ongoing to reenable).

**Comment by davidberard98** [comment] 2022-05-12 22:07
It might be worth checking whether or not NVFuser was actually enabled - you can 

```python
old_value = torch._C._jit_set_nvfuser_enabled(False)
torch._C._jit_set_nvfuser_enabled(old_value)
print("NVFuser enabled ? ", old_value")
```

I think I mentioned this on slack - but the `#ifdef USE_ROCM` could be problematic depending on your build configuration.

**Comment by jjsjann123** [comment] 2022-05-14 00:00
Our prim torch tests are marked with `@onlyCUDA` which I believe also runs on ROCm?! https://github.com/kevinstephano/pytorch/blob/c31e0db09458c25f19ec14902ce8150225aea5d3/test/test_prims.py#L18

We should add a `skipCudaIfRocm`. This is Kevin's new python API, so it's not using TorchScript or affected by our previously added knobs cc'ing @davidberard98 

cc'ing @kevinstephano

**Comment by jjsjann123** [comment] 2022-05-16 21:30
#77468 is merged. We should also close this one.

**Closed** 2022-05-17 18:43 UTC
Labels: oncall: jit, module: nvfuser
