### ISSUE TITLE
When CUDA is enabled, recompiling after editing aten/src/ATen/core/dispatch/DispatchTable.h doesn't result in all necessary files getting recompiled

### ISSUE THREAD

**Issue by ezyang** [pytorch/pytorch#26304] opened 2019-09-16 19:46 UTC
Other files may also be susceptible, but the issue reproduces 100% on `aten/src/ATen/core/dispatch/DispatchTable.h`

Steps to reproduce:
1. Build PyTorch `python setup.py develop`
2. Edit the "Didn't find kernel to dispatch to" error message to insert some string. Example diff:

```
diff --git a/aten/src/ATen/core/dispatch/DispatchTable.h b/aten/src/ATen/core/dispatch/DispatchTable.h
index 7b4af315f1..3a5879cbda 100644
--- a/aten/src/ATen/core/dispatch/DispatchTable.h
+++ b/aten/src/ATen/core/dispatch/DispatchTable.h
@@ -263,7 +263,7 @@ private:
       }
 
       const std::string dispatch_key_str = dispatch_key.has_value() ? toString(*dispatch_key) : "None";
-      TORCH_CHECK(false, "Didn't find kernel to dispatch to for operator '", operator_name_,
+      TORCH_CHECK(false, "ARGLEBARGLEFARR Didn't find kernel to dispatch to for operator '", operator_name_,
                "'. Tried to look up kernel for dispatch key '", dispatch_key_str,
                "'. Registered dispatch keys are: ", listAllDispatchKeys());
   }
```

3. Rebuild PyTorch `python setup.py develop`
4. Run `python -c "import torch; torch.cat([], dim=1)`

Expected result: you see ARGLEBARGLEFARR
Actual result: you don't see it

I did an experiment where I did one of these botched recompiles, and then compared the set of files which had ARGLEBARGLEFARR with the set of files that had the normal error message. What I found is that CUDA generated files had not been recompiled, but CPU (and final library) all had the string. The fact that the CUDA files are not recompiling seems problematic; however, I don't understand how this could have caused the problem, as the test I made above is CPU (perhaps some sort of weak symbol situation?)

cc @ezyang @gchanan @zou3519 @smessmer

**Comment by ezyang** [comment] 2019-09-16 20:35
Update: The problem goes away when I build with `USE_CUDA=0`, so it must indeed be some sort of weak symbol situation.

**Comment by ezyang** [comment] 2019-09-16 20:38
A sampling of some files which fail to recompile:

```
 Binary file torch/test/cuda_tensor_interop_test matches
 Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/THC/THCTensor.cpp.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/cuda/detail/torch_generated_IndexUtils.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_DilatedMaxPool2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_AdaptiveAveragePooling.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UpSampleBilinear2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UpSampleNearest3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Copy.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_AdaptiveAveragePooling3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_AdaptiveMaxPooling3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_AveragePool2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_AdaptiveMaxPooling2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_AveragePool3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Col2Im.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_DilatedMaxPool3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_WeightNorm.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Im2Col.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UpSampleNearest1d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_SpectralOps.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_FractionalMaxPool2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_BatchLinearAlgebra.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_SoftMax.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_DistanceKernel.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_FractionalMaxPool3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_FillKernel.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_GridSampler.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_SummaryOps.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_EmbeddingBackwardKernel.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_MaxUnpooling.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_LossCTC.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UpSampleLinear1d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_TensorTransformations.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UpSampleTrilinear3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Loss.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_RangeFactories.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Dropout.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_NaiveConvolutionTranspose2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_NaiveConvolutionTranspose3d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Embedding.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_EmbeddingBag.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Indexing.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Repeat.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_NaiveDilatedConvolution.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_ReflectionPad.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_ReplicationPadding.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_RNN.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Lerp.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Normalization.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_PointwiseOpsKernel.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UpSampleBicubic2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UpSampleNearest2d.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Activation.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_SortingKthValue.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_BinaryOpsKernel.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_TensorFactories.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_PowKernel.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_UnaryOpsKernel.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_TensorCompare.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Unique.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/cuda/torch_generated_Distributions.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/torch_generated_SparseCUDATensor.cu.o matches
-Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/torch_generated_SparseCUDATensorMath.cu.o matches
 Binary file build/caffe2/CMakeFiles/torch.dir/__/aten/src/ATen/native/sparse/cuda/SparseCUDATensor.cpp.o matches

```

**Comment by Baranowski** [comment] 2020-04-14 15:41
I can no longer reproduce this. The `TORCH_CHECK` that ezyang mentioned in the original report has been moved to a different `.cpp` file, and the modified version shows up with `torch.cat([], dim=1)`. I have modified another method in `DispatchTable.h` and again, the modification was reflected when running `torch.cat([], dim=1)`

To be clear, I'm not claiming that the problem no longer exists, only that the repro instructions no longer work.

**Comment by ezyang** [comment] 2020-04-15 14:03
Thanks for the note @Baranowski. Could you post what diffs you attempted?

**Comment by Baranowski** [comment] 2020-04-15 18:27
IIRC, I tried the following:

```
diff --git a/aten/src/ATen/core/dispatch/Dispatcher.cpp b/aten/src/ATen/core/dispatch/Dispatcher.cpp
index 6573f17457..e4e80ebdeb 100644
--- a/aten/src/ATen/core/dispatch/Dispatcher.cpp
+++ b/aten/src/ATen/core/dispatch/Dispatcher.cpp
@@ -255,7 +255,7 @@ RegistrationHandleRAII Dispatcher::addRegistrationListener(std::unique_ptr<OpReg
 [[noreturn]] void Dispatcher::reportError(const DispatchTable& dispatchTable, DispatchKey dispatchKey) {
   if (dispatchKey == DispatchKey::Undefined) {
     TORCH_CHECK(false,
-          "There were no tensor arguments to this function (e.g., you passed an "
+          "ExpectoPatronum There were no tensor arguments to this function (e.g., you passed an "
           "empty list of Tensors), but no fallback function is registered for schema ", dispatchTable.operatorName(),
           ".  This usually means that this function requires a non-empty list of Tensors.  "
           "Available functions are ", dispatchTable.listAllDispatchKeys())
```

and

```
diff --git a/aten/src/ATen/core/dispatch/DispatchTable.h b/aten/src/ATen/core/dispatch/DispatchTable.h
index c6eaf89ac1..48d509da98 100644
--- a/aten/src/ATen/core/dispatch/DispatchTable.h
+++ b/aten/src/ATen/core/dispatch/DispatchTable.h
@@ -207,6 +207,7 @@ class DispatchTable final {
 
   // This function is a temporary hack, see comment at manuallyBoxedKernel_ member
   void setManuallyBoxedKernel_(KernelFunction::InternalBoxedKernelFunction* func) {
+    TORCH_INTERNAL_ASSERT(false, "Correctly recompiled");
     TORCH_INTERNAL_ASSERT(!manuallyBoxedKernel_.has_value(), "Cannot set multiple manually boxed kernels for the same operator ", operatorName_);
     manuallyBoxedKernel_ = func;
```

Each of those changes was manifested when running
```
python setup.py develop && python -c "import torch; torch.cat([], dim=1)
```

**Comment by ezyang** [comment] 2020-04-15 21:04
OK. I guess we will have to find some other repro for this problem

**Comment by Baranowski** [comment] 2020-04-16 13:52
I've managed to reproduce the issue in quite a roundabout way:
```
diff --git a/aten/src/ATen/core/dispatch/DispatchTable.h b/aten/src/ATen/core/dispatch/DispatchTable.h
index c6eaf89ac1..9662311406 100644
--- a/aten/src/ATen/core/dispatch/DispatchTable.h
+++ b/aten/src/ATen/core/dispatch/DispatchTable.h
@@ -20,6 +20,10 @@
 
 namespace c10 {
 
+[[noreturn]] inline void ExpectoPatronum() {
+  TORCH_CHECK(false, "ExpectoPatronum");
+}
+
 namespace impl {
 /**
  * A KernelFunctionTable is a map from DispatchKey to a KernelFunction.
diff --git a/aten/src/ATen/cuda/detail/IndexUtils.cu b/aten/src/ATen/cuda/detail/IndexUtils.cu
index e066917456..e0b0ae1830 100644
--- a/aten/src/ATen/cuda/detail/IndexUtils.cu
+++ b/aten/src/ATen/cuda/detail/IndexUtils.cu
@@ -71,6 +71,7 @@ bool maybeOverlappingIndices(const Tensor& t) {
 }
 
 bool canUse32BitIndexMath(const Tensor& t, int64_t max_elem) {
+  c10::ExpectoPatronum();
   int64_t elements = t.numel();
   if (elements >= max_elem) {
     return false;
diff --git a/test_cuda_cat.py b/test_cuda_cat.py
new file mode 100644
index 0000000000..52495be771
--- /dev/null
+++ b/test_cuda_cat.py
@@ -0,0 +1,3 @@
+import torch
+a = torch.cuda.FloatTensor([1.])
+torch.cat([a, a])
```

The test results in a RuntimeError, as expected:
```
$ python setup.py develop && python test_cuda_cat.py
...
Traceback (most recent call last):
  File "test_cuda_cat.py", line 3, in <module>
    torch.cat([a, a])
RuntimeError: ExpectoPatronum
```

Then when I modify the string:
```
diff --git a/aten/src/ATen/core/dispatch/DispatchTable.h b/aten/src/ATen/core/dispatch/DispatchTable.h
index 9662311406..b92ec737f5 100644
--- a/aten/src/ATen/core/dispatch/DispatchTable.h
+++ b/aten/src/ATen/core/dispatch/DispatchTable.h
@@ -21,7 +21,7 @@
 namespace c10 {
 
 [[noreturn]] inline void ExpectoPatronum() {
-  TORCH_CHECK(false, "ExpectoPatronum");
+  TORCH_CHECK(false, "Modified ExpectoPatronum");
 }
 
 namespace impl {
```

The error message is expected to change but it remains the same:
```
$ python setup.py develop && python test_cuda_cat.py
...
Traceback (most recent call last):
  File "test_cuda_cat.py", line 3, in <module>
    torch.cat([a, a])
RuntimeError: ExpectoPatronum
```

@ezyang, since you are assigned to this issue, do you mind if I dig in and try to fix it?

**Comment by ezyang** [comment] 2020-04-16 16:55
Please have at it!

**Comment by Baranowski** [comment] 2020-04-19 08:42
Note to self:

The build.ninja entries for `.cpp` sources properly point to dependency files, e.g.:

```
build caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/Utils.cpp.o: CXX_COMPILER__torch_cpu ../aten/src/ATen/Utils.cpp
  (...)
  DEP_FILE = caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/Utils.cpp.o.d                                                                                                                                        
  (...)
```

The `CXX_COMPILER__torch_cpu` rule in `rules.ninja` generates them explicitly:
```
rule CXX_COMPILER__torch_cpu       
  depfile = $DEP_FILE
  deps = gcc
  command = /home/wbaranowski/miniconda3/envs/pytorch-cuda-dev/bin/x86_64-conda_cos6-linux-gnu-c++  $DEFINES $INCLUDES $FLAGS -MD -MT $out -MF $DEP_FILE -o $out -c $in                                            
  description = Building CXX object $out
```

(Note: those dependency files are then transcribed into a more efficient format in `.ninja_deps` and the `.d` file is immediately removed; this detail is not important for how this whole thing works)

The `build.ninja` entries for `.cu` files are completely different, e.g.:
```
build caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/cuda/detail/torch_cuda_generated_IndexUtils.cu.o: CUSTOM_COMMAND ../aten/src/ATen/cuda/detail/IndexUtils.cu caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/cuda/detail/torch_cuda_generated_IndexUtils.cu.o.depend caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/cuda/detail/torch_cuda_generated_IndexUtils.cu.o.RelWithDebInfo.cmake (...)
  COMMAND = (...) /home/wbaranowski/miniconda3/envs/pytorch-cuda-dev/bin/cmake (...) -D generated_cubin_file:STRING=/home/wbaranowski/git/Quansight/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/cuda/detail/./torch_cuda_generated_IndexUtils.cu.o.cubin.txt -P /home/wbaranowski/git/Quansight/pytorch/build/caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/cuda/detail/torch_cuda_generated_IndexUtils.cu.o.RelWithDebInfo.cmake                                                                                   
  DESC = Building NVCC (Device) object caffe2/CMakeFiles/torch_cuda.dir/__/aten/src/ATen/cuda/detail/torch_cuda_generated_IndexUtils.cu.o                                                                          
  restat = 1

And `CUSTOM_COMMAND` is defined in `rules.ninja` as might be expected:
```
rule CUSTOM_COMMAND                                                                                                                                                                                                
  command = $COMMAND                                                                                                                                                                                               
  description = $DESC
```

Note: something actually generates a dependency file (in this example `torch_cuda_generated_IndexUtils.cu.o.depend`) but:
* It's not in the Makefile format which ninja could understand. Instead it's just a CMake file that propagates a single variable - `CUDA_NVCC_DEPEND` - with a list of all the header files that are dependencies)
* The `.cu.o` target depends on the dependency file, rather than its contents because the `.cu.o.depend` file is declared as one of the dependencies, instead of being pointed to by the `depfile` variable (see https://ninja-build.org/manual.html#_depfile). So editing the dependency file itself would trigger a rebuild, but editing one of the dependencies does not.

TODO:

- verify that ninja dependency system is in fact used (and is not circumvented by some other dependency system)
- find out what generates the `.cu.o.depend` and `.cu.o.RelWithDebInfo.cmake` files
- consider changing the `.cu.o.RelWithDebInfo.cmake` files so that they generate Makefile-like dependency files that cen be used by the ninja rules

**Comment by Baranowski** [comment] 2020-04-22 06:35
The PR was reverted - `.cu` source files were considered dirty too often.

**Comment by Baranowski** [comment] 2020-04-27 08:39
Status update: The PR could be easily patched up: One of the filenames in the dependency file needs the correct directory prepended to it. This could be done in CMake scripts and possibly would be similar to `cmake/Modules_CUDA_fix/upstream/FindCUDA/make2cmake.cmake`

However, the more I look into this, the more I feel that this is not the right thing to do.

I now suspect that the patch at the bottom of `tools/setup_helpers/cmake.py` should not be there:

```
        # in cmake, .cu compilation involves generating certain intermediates    
        # such as .cu.o and .cu.depend, and these intermediates finally get compiled
        # into the final .so.                                                    
        # Ninja updates build.ninja's timestamp after all dependent files have been built,
        # and re-kicks cmake on incremental builds if any of the dependent files 
        # have a timestamp newer than build.ninja's timestamp.                   
        # There is a cmake bug with the Ninja backend, where the .cu.depend files
        # are still compiling by the time the build.ninja timestamp is updated,  
        # so the .cu.depend file's newer timestamp is screwing with ninja's incremental
        # build detector.                                                        
        # This line works around that bug by manually updating the build.ninja timestamp
        # after the entire build is finished.                                    
        ninja_build_file = os.path.join(self.build_dir, 'build.ninja')           
        if os.path.exists(ninja_build_file):                                     
            os.utime(ninja_build_file, None)
```

When I remove that snipped, there is a lot of unnecessary rebuilding (~2000 files) on the second run of `setup.py develop` but not on subsequent runs. This happens because the list of include dirs in the variable `CUDA_NVCC_INCLUDE_DIRS` changes between the first and second run, which causes a lot of build files to be regenerated, which in turn are dependencies of many object files. I'm hoping that once I fix the change of that `CUDA_NVCC_INCLUDE_DIRS` variable between the first and second build, there will be no unnecessary rebuilds.

Although I still have to verify that there are no other triggers for the unnecessary rebuilds.

**Comment by ezyang** [comment] 2020-04-27 19:37
That sounds good to me! cc @soumith who wrote this comment

**Comment by soumith** [comment] 2020-04-27 19:46
yes, I was optimizing things for the second run, which arguably is super common

**Closed** 2020-05-06 21:26 UTC
Labels: high priority, internals, module: build, triaged
