### ISSUE TITLE
compiling code that converts between bf16 and fp16 fails

### ISSUE THREAD

**Issue by mikekgfb** [pytorch/pytorch#123830] opened 2024-04-11 09:27 UTC
### 🐛 Describe the bug

Yes, the code is atrocious (working around data type issues), but legal.  Input sequence:

```python
def linear_forward_int4(x, weight_int4pack, scales_and_zeros, out_features, groupsize):
    origin_x_size = x.size()
    x = x.reshape(-1, origin_x_size[-1])
    c = torch.ops.aten._weight_int4pack_mm(
        x.to(dtype=torch.bfloat16),
        weight_int4pack,
        groupsize,
        scales_and_zeros.to(dtype=torch.bfloat16)
    ).to(dtype=x.dtype)
    new_shape = origin_x_size[:-1] + (out_features,)
    c = c.reshape(new_shape)
    return c
```

Error:
```
Traceback (most recent call last):
  File "/Users/mikekg/pytorch/test/torchat/export.py", line 120, in <module>
    cli()
  File "/Users/mikekg/pytorch/test/torchat/export.py", line 117, in cli
    main(args)
  File "/Users/mikekg/pytorch/test/torchat/export.py", line 112, in main
    export_model_aoti(model, device, output_dso_path, args)
  File "/Users/mikekg/pytorch/test/torchat/export_aoti.py", line 50, in export_model
    so = torch._export.aot_compile(
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_export/__init__.py", line 380, in aot_compile
    so_path = torch._inductor.aot_compile(gm, args, kwargs, options=options)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/__init__.py", line 102, in aot_compile
    return compile_fx_aot(
           ^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1056, in compile_fx_aot
    compiled_lib_path = compile_fx(
                        ^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1162, in compile_fx
    return compile_fx(
           ^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1196, in compile_fx
    return compile_fx(
           ^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1393, in compile_fx
    return inference_compiler(unlifted_gm, example_inputs_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/compile_fx.py", line 1311, in fw_compiler_base
    return inner_compile(
           ^^^^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_dynamo/repro/after_aot.py", line 83, in debug_wrapper
    inner_compiled_fn = compiler_fn(gm, example_inputs)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/debug.py", line 304, in inner
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/miniconda3/envs/py311/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/compile_fx.py", line 469, in compile_fx_inner
    compiled_graph = fx_codegen_and_compile(
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/compile_fx.py", line 746, in fx_codegen_and_compile
    compiled_fn = graph.compile_to_fn()
                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/graph.py", line 1426, in compile_to_fn
    code, linemap = self.codegen_with_cpp_wrapper()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/graph.py", line 1336, in codegen_with_cpp_wrapper
    return self.codegen()
           ^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/graph.py", line 1347, in codegen
    self.scheduler.codegen()
  File "/Users/mikekg/pytorch/pytorch/torch/_dynamo/utils.py", line 265, in time_wrapper
    r = func(*args, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/scheduler.py", line 2473, in codegen
    self.get_backend(device).codegen_node(node)  # type: ignore[possibly-undefined]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/codegen/cpp.py", line 3832, in codegen_node
    cpp_kernel_proxy.codegen_nodes(_nodes)
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/codegen/cpp.py", line 3377, in codegen_nodes
    self.legalize_lowp_fp_dtype(nodes)
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/codegen/cpp.py", line 3337, in legalize_lowp_fp_dtype
    if all(
       ^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/codegen/cpp.py", line 3338, in <genexpr>
    isinstance(_node, SchedulerNode) and self.is_lowp_fp_scheduler(_node)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mikekg/pytorch/pytorch/torch/_inductor/codegen/cpp.py", line 3184, in is_lowp_fp_scheduler
    _lowp_fp_type == opt_ctx.dtype
AssertionError: scheduler node do not support bf16/fp16 mix
```

### Versions

Pytorch CI with nightlies

cc @ezyang @msaroufim @bdhirsh @anijain2305 @chauhang

**Comment by CaoE** [comment] 2024-04-23 02:13
@mikekgfb Could you please provide a complete example to facilitate reproduction? Thanks.  This example seems to use a mix of bf16 and fp16 dtypes.

**Comment by CaoE** [comment] 2024-05-09 01:31
This could be solved by https://github.com/pytorch/pytorch/pull/123562.

**Comment by leslie-fang-intel** [comment] 2024-10-09 01:12
Hi @mikekgfb, could you help to confirm if this issue got fixed since https://github.com/pytorch/pytorch/pull/123562 landed.

**Comment by CaoE** [comment] 2024-11-05 01:43
Close this since https://github.com/pytorch/pytorch/pull/123562 landed. Please feel free to reopen it if any issues persist.

**Closed by CaoE** 2024-11-05 01:43 UTC
Labels: enhancement, oncall: pt2, oncall: cpu inductor
