### ISSUE TITLE
Conv3D: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Kathrine94** [pytorch/pytorch#12416] opened 2018-10-06 11:24 UTC
## 🐛 Bug

RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generic/THCTensorCopy.c:20

## To Reproduce

import torch
a = torch.randn(1, 2048, 8, 11, 11).cuda()
conv = torch.nn.Conv3d(2048, 512, (3, 1, 1), stride(1, 1, 1)).cuda()
out = conv(a)
b = torch.randn(1, 2048, 8, 12, 12).cuda()
## Expected behavior
when execute the statement "out = conv(a)", the video memory of the computer suddenly became more than 5000 M . Then， I Input the code "b = torch.randn(1, 2048, 8, 12, 12).cuda()", direct display error reporting.The error is "RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at /pytorch/aten/src/THC/generic/THCTensorCopy.c:20"。When I change the size of a become (1, 2048, 8, 21, 21), the video memory is normal and no error。

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):0.4.1
 - OS (e.g., Linux):16.04
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source):
 - Python version:3.6
 - CUDA/cuDNN version:9.0
 - GPU models and configuration:
 - Any other relevant information: GPU : Titan Xp

**Comment by zou3519** [comment] 2018-10-08 17:38
Can reproduce on master

**Comment by Kathrine94** [comment] 2018-10-09 14:52
I install pytorch from source, the problem have solved.Thanks

> Can reproduce on master
> 
> ```
> 
> import torch
> a = torch.randn(1, 2048, 8, 11, 11).cuda()
> conv = torch.nn.Conv3d(2048, 512, (3, 1, 1), stride=(1, 1, 1)).cuda()
> out = conv(a)
> b = torch.randn(1, 2048, 8, 12, 12).cuda()
> ```

I install pytorch from source, the problem have solved.Thanks

**Comment by weiyangfb** [comment] 2018-10-11 22:06
closing this since it is resolved

**Closed by weiyangfb** 2018-10-11 22:06 UTC
Labels: high priority
