### ISSUE TITLE
ONNX export incorrectly uses state_dict

### ISSUE THREAD

**Issue by jamesr66a** [pytorch/pytorch#38887] opened 2020-05-21 20:02 UTC
ONNX export pulls out a flat list of parameters to use for the purpose of tracing: https://github.com/pytorch/pytorch/blob/a40049fd2a535f87142a91491b1dd0f38147bd1a/torch/jit/__init__.py#L346

However, this is not correct, since the contents of `state_dict` can be overridden by Modules by implementing `_save_to_state_dict`. This causes ONNX export to break in those cases, such as when exporting quantized Modules. 

Causes error messages like:
`Tried to trace ... but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.`

Repro code:
```python
import torch

class ConvModel(torch.nn.Module):
    def __init__(self):
        super(ConvModel, self).__init__()
        self.conv_stem = torch.nn.Conv2d(
            3, 5, 2, bias=True
        ).to(dtype=torch.float)

        self.bn1 = torch.nn.BatchNorm2d(5)
        self.act1 = torch.nn.ReLU()

    def forward(self, x):
        x = self.conv_stem(x)
        x = self.bn1(x)
        x = self.act1(x)
        return x

    def fuse(self):
        torch.quantization.fuse_modules(
            self, 
            ['conv_stem', 'bn1', 'act1'], 
            inplace=True
        )


def fuse_modules(module):
    module_output = module
    if callable(getattr(module_output, "fuse", None)):
        module_output.fuse()
    for name, child in module.named_children():
        new_child = fuse_modules(child)
        if new_child is not child:
            module_output.add_module(name, new_child)
    return module_output

def create_and_update_model():
    model = ConvModel()
    backend = 'qnnpack'
    model = fuse_modules(model)
    model.qconfig = torch.quantization.get_default_qat_qconfig(backend)
    torch.backends.quantized.engine = backend
    torch.quantization.prepare_qat(model, inplace=True)
    model.apply(torch.nn.intrinsic.qat.freeze_bn_stats)
    return model

def QAT(model):
    N = 100
    for idx in range(N):
        input_tensor = torch.rand(1, 3, 6, 6)
        model(input_tensor)
    return model

model = create_and_update_model()
model = QAT(model)
torch.quantization.convert(model, inplace=True)

model.eval()
inputs = torch.rand(1, 3, 6, 6)
# Export the model to ONNX
with torch.no_grad():
    with io.BytesIO() as f:
        torch.onnx.export(
            model,
            inputs,
            f,
            opset_version=11,
            verbose=True, 
            export_params=True,
        )
```

**Comment by jerryzh168** [comment] 2020-05-21 20:03
cc @houseroad could you assign this to Microsoft?

**Comment by daydayfun** [comment] 2020-05-27 10:18
with same problem, need  help +1

**Comment by garymm** [comment] 2022-04-06 23:45
Possibly the same root cause as https://github.com/pytorch/pytorch/issues/47887

**Comment by AllenTiTaiWang** [comment] 2022-10-24 19:51
tracked in #47887

**Closed by AllenTiTaiWang** 2022-10-24 19:51 UTC
Labels: oncall: jit, module: onnx, triaged, onnx-triaged
