### ISSUE TITLE
subprocess.CalledProcessError: Command '['make', '-j', '4', 'install']' returned non-zero exit status 2

### ISSUE THREAD

**Issue by GauravKrRoy** [pytorch/pytorch#21055] opened 2019-05-29 05:05 UTC
## To Reproduce

1.
1.
1.

      make[1]: Leaving directory '/media/gauravroy/pytorch/build'
Makefile:143: recipe for target 'all' failed
make: *** [all] Error 2
Traceback (most recent call last):
  File "setup.py", line 744, in <module>
    build_deps()
  File "setup.py", line 309, in build_deps
    build_dir='build')
  File "/media/gauravroy/pytorch/tools/build_pytorch_libs.py", line 309, in build_caffe2
    check_call(['make', '-j', str(max_jobs), 'install'], cwd=build_dir, env=my_env)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0):
 - OS (e.g., Linux):
 - How you installed PyTorch (`conda`, `pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by ailzhang** [comment] 2019-05-29 23:08
duplicate of #21056

**Closed by ailzhang** 2019-05-29 23:08 UTC
