### ISSUE TITLE
[v.2.5.0] Release Tracker

### ISSUE THREAD

**Issue by kit1980** [pytorch/pytorch#135522] opened 2024-09-09 19:22 UTC
We cut a [release branch](https://github.com/pytorch/pytorch/tree/release/2.5) for the 2.5.0 release.

Our plan from this point from this point is roughly:

* Phase 1 (until 9/30/24): work on finalizing the release branch
* Phase 2 (after 9/30/24): perform extended integration/stability/performance testing based on Release Candidate builds.

This issue is for tracking cherry-picks to the release branch.

## Cherry-Pick Criteria

**Phase 1 (until 9/30/24):**

Only low-risk changes may be cherry-picked from main:

1. Fixes to regressions against the most recent minor release (e.g. 2.4.x for this release; see [module: regression issue list](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22module%3A+regression%22+))
2. Critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+)
3. Critical fixes to new features introduced in the most recent minor release (e.g. 2.4.x for this release)
4. Test/CI fixes
5. Documentation improvements
6. Compilation fixes or ifdefs required for different versions of the compilers or third-party libraries
7. Release branch specific changes (e.g. change version identifiers)

Any other change requires special dispensation from the release managers (currently  @atalman, @PaliC , @huydhn, @malfet, @kit1980). If this applies to your change please write "Special Dispensation" in the "Criteria Category:" template below and explain.

**Phase 2 (after 9/30/24):**

Note that changes here require us to rebuild a Release Candidate and restart extended testing (likely delaying the release). Therefore, the only accepted changes are **Release-blocking** critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+)

Changes will likely require a discussion with the larger release team over VC or Slack.

## Cherry-Pick Process

1. Ensure your PR has landed in master. This does not apply for release-branch specific changes (see Phase 1 criteria).
2. Create (but do not land) a PR against the [release branch](https://github.com/pytorch/pytorch/tree/release/2.5).
   <details>

    ```bash
    # Find the hash of the commit you want to cherry pick
    # (for example, abcdef12345)
    git log

    git fetch origin release/2.5
    git checkout release/2.5
    git cherry-pick -x abcdef12345

    # Submit a PR based against 'release/2.5' either:
    # via the GitHub UI
    git push my-fork

    # via the GitHub CLI
    gh pr create --base release/2.5
    ```

    </details>
3. Make a request below with the following format:

```
Link to landed trunk PR (if applicable):
* 

Link to release branch PR:
* 

Criteria Category:
* 
```

1. Someone from the release team will reply with approved / denied or ask for more information.
2. If approved, someone from the release team will merge your PR once the tests pass. **Do not land the release branch PR yourself.**

**NOTE: Our normal tools (ghstack / ghimport, etc.) do not work on the release branch.**

Please note HUD Link with branch CI status and link to the HUD to be provided here.
[HUD](https://hud.pytorch.org/hud/pytorch/pytorch/release%2F2.5)

### Versions

2.5.0

**Comment by atalman** [comment] 2024-09-09 19:31
Link to landed trunk PR (if applicable):
* NA

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135506/
* https://github.com/pytorch/pytorch/pull/135517
* https://github.com/pytorch/builder/pull/1982

Criteria Category:
* Release Only changes, temporary changes for triton build

**Comment by justinchuby** [comment] 2024-09-09 19:45
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/issues/135372

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135526

Criteria Category:
* Documentation improvements

**Comment by atalman** [comment] 2024-09-09 21:19
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135528

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135534

Criteria Category:
* Critical fix for release

**Comment by kit1980** [comment] 2024-09-10 22:00
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135562

Link to release branch PR:
*https://github.com/pytorch/pytorch/pull/135625

Criteria Category:
* Critical  - revert

**Comment by atalman** [comment] 2024-09-10 22:04
Link to landed trunk PR (if applicable):
* NA

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135613

Criteria Category:
* Release only changes, build triton from branch

**Comment by titaiwangms** [comment] 2024-09-11 17:11
Link to landed trunk PR (if applicable):

https://github.com/pytorch/pytorch/pull/135710
Link to release branch PR:

https://github.com/pytorch/pytorch/pull/135594
Criteria Category:

Critical fixes for: [silent correctness](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+correctness+%28silent%29%22), [backwards compatibility](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+bc-breaking%22+), [crashes](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+crash%22+), [deadlocks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+deadlock%22+), (large) [memory leaks](https://github.com/pytorch/pytorch/issues?q=is%3Aissue+is%3Aopen+label%3A%22topic%3A+memory+usage%22+)

**Comment by fengyuan14** [comment] 2024-09-12 07:30
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135647

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135833

Criteria Category:
* Fixing the failure of loading PyTorch XPU dlls on Windows.

**Comment by justinchuby** [comment] 2024-09-12 16:10
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135786

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135868

Criteria Category:
* Critical fixes to new features introduced in the most recent minor release - ONNX exporter

**Comment by jiayisunx** [comment] 2024-09-13 03:37
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135574

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135935

Criteria Category:
* Critical - Fix Inductor: simplify indexing_exprs in LoopBody._init_with_copy

**Comment by zxd1997066** [comment] 2024-09-13 05:38
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135193

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135793

Criteria Category:
* Regression fixes

  - CPU huggingface dynamo test pass rate drops from 46/46 to 50/52  due to skip model list not works on CPU.
  - Fix LayoutLMForSequenceClassification accuracy failure and YituTechConvBert performance regression.

**Comment by chunyuan-w** [comment] 2024-09-13 07:15
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/134982

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/135561

Criteria Category:
* Critical correctness issue fixes to new feature introduced in the coming PyTorch 2.5 release - inductor max-autotune on CPU

**Comment by Skylion007** [comment] 2024-09-13 14:54
Link to landed trunk PR (if applicable):
* #135535

Link to release branch PR:
* 136000

Criteria Category:
* Critical regression

**Comment by shubhambhokare1** [comment] 2024-09-13 17:09
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135512

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136005

Criteria Category:
* Documentation improvements

**Comment by CaoE** [comment] 2024-09-14 08:53
Link to landed trunk PR (if applicable):

https://github.com/pytorch/pytorch/pull/135299
Link to release branch PR:

https://github.com/pytorch/pytorch/pull/136082
Criteria Category:

Documentation improvements

**Comment by jataylo** [comment] 2024-09-16 12:32
Link to landed trunk PR (if applicable):
- https://github.com/pytorch/pytorch/pull/133852

Link to release branch PR:
- https://github.com/pytorch/pytorch/pull/136139

Criteria Category:
- Bug fix

**Comment by justinchuby** [comment] 2024-09-17 17:12
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/136162

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136203

Criteria Category:
* Critical fixes to new features introduced in the most recent minor release - ONNX exporter

**Comment by atalman** [comment] 2024-09-17 17:55
Link to landed trunk PR (if applicable):
* NA

Link to release branch PR:
*  https://github.com/pytorch/pytorch/pull/136206

Criteria Category:
* Temporary Release-Only change to unblock RC build

**Comment by jiayisunx** [comment] 2024-09-18 13:28
Link to landed trunk PR (if applicable):

https://github.com/pytorch/pytorch/pull/135932
Link to release branch PR:

https://github.com/pytorch/pytorch/pull/136262
Criteria Category:

Critical - Fix the accuracy failure for 3 models of Inductor AMP FP16 benchmark on CPU.

**Comment by atalman** [comment] 2024-09-21 15:01
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/builder/pull/1988
* https://github.com/pytorch/builder/pull/1993

Link to release branch PR:
* https://github.com/pytorch/builder/pull/1994/

Criteria Category:
* Critical, CD wheel build with xpu dependencies

**Comment by guangyey** [comment] 2024-09-23 09:20
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135818

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136420

Criteria Category:
* Critical  - Fix XPU memory statistics error.

**Comment by Shan19900305** [comment] 2024-09-23 11:36
Link to landed trunk PR (if applicable):

https://github.com/pytorch/pytorch/pull/134546

Link to release branch PR:

https://github.com/pytorch/pytorch/pull/136426

Criteria Category:
Critical fixes to for_each op fast path select failed and fused adam/adamw/sgd ops check failed.

**Comment by jeffdaily** [comment] 2024-09-23 21:34
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/132555

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136467

Criteria Category:
* CI for release process, silent ROCm bug fix for miopen, ROCm amdsmi regression

**Comment by jbschlosser** [comment] 2024-09-24 15:30
Link to landed trunk PR (if applicable): #135964

Link to release branch PR: #136536

Criteria Category: Regression fix

**Comment by jithunnair-amd** [comment] 2024-09-24 21:32
Link to landed trunk PR (if applicable):


* https://github.com/pytorch/pytorch/pull/135995
* https://github.com/pytorch/pytorch/pull/135917

Link to release branch PR:

* https://github.com/pytorch/pytorch/pull/136557

Criteria Category:

Test/CI fixes: Address unit test failures on release/2.5 branch by cherry-picking skips

**Comment by huydhn** [comment] 2024-09-24 22:14
Link to landed trunk PR (if applicable):

* https://github.com/pytorch/test-infra/pull/5685
* https://github.com/pytorch/test-infra/pull/5668

Link to release branch PR:

* https://github.com/pytorch/test-infra/pull/5702
* https://github.com/pytorch/test-infra/pull/5701

Criteria Category:

Critical CI fix to unblock ExecuTorch 0.4 release.  Specifically, they are to address the following failures:

* AWS session expires after 1 hour https://github.com/pytorch/executorch/actions/runs/11005587854/job/30558922998
* Missing parameter https://github.com/pytorch/executorch/actions/runs/11005583929/workflow

**Comment by jithunnair-amd** [comment] 2024-09-25 14:59
Link to landed trunk PR (if applicable):

* https://github.com/pytorch/pytorch/pull/134498

Link to release branch PR:

* https://github.com/pytorch/pytorch/pull/135869

Criteria Category: Test/CI fixes, Cudagraph support for SDPA on ROCm

**Comment by kit1980** [comment] 2024-09-26 00:17
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/134108

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136696

Criteria Category:
* Critical CI fixes

**Comment by jithunnair-amd** [comment] 2024-09-26 00:41
Link to landed trunk PR (if applicable):


* https://github.com/pytorch/pytorch/pull/136283

Link to release branch PR:

* https://github.com/pytorch/pytorch/pull/136700

Criteria Category:
 Fixes usability issues when building CMake-based projects using PyTorch on ROCm

**Comment by GregoryComer** [comment] 2024-09-26 01:08
- Link to landed trunk PR (if applicable):
N/A - See below.

- Link to release branch PR:
https://github.com/pytorch/pytorch/pull/136522

Criteria Category: (1) Fixes regression in compiler flags in libtorch_cpu due to XNNPACK CMake bug, causes iOS simulator build failures and may increase binary size.

Notes:
I believe lowest risk option is to revert the XNNPACK library version directly on the release branch. Fixing on master requires rolling back internal (difficult as test failure was not seen until some time after land and other code needs the latest XNNPACK) or pulling in the latest XNNPACK to PyTorch, which unfortunately includes larger build changes (needing larger buck changes). If merging the revert PR directly on release/2.5 is not acceptable, I can either find a CMake workaround or split the OSS and internal XNNPACK Buck targets. However, I consider this higher risk than simply reverting XNNPACK to the version PyTorch was using prior to Aug 28.

**Comment by kit1980** [comment] 2024-09-26 01:18
Link to landed trunk PR (if applicable):

* https://github.com/pytorch/pytorch/pull/136571

Link to release branch PR:

* https://github.com/pytorch/pytorch/pull/136706

Criteria Category:
 CI fixes

---

@kit1980 merged

**Comment by kit1980** [comment] 2024-09-26 01:32
Link to landed trunk PR (if applicable):

* https://github.com/pytorch/pytorch/pull/136580

Link to release branch PR:

* https://github.com/pytorch/pytorch/pull/136710

Criteria Category:
 CI fixes

---

@kit1980 merged

**Comment by EikanWang** [comment] 2024-09-26 03:35
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/129946

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136731

Criteria Category:
* Documentation improvements

**Comment by EikanWang** [comment] 2024-09-26 03:37
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/136489

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136729

Criteria Category:
* Compilation fixes

**Comment by yanboliang** [comment] 2024-09-26 05:06
Link to landed trunk PR (if applicable):
* N/A

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136734

Criteria Category:
* Release Only changes, temporary revert as it's not a clean fix.

**Comment by albanD** [comment] 2024-09-26 17:43
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/136672

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136769

Criteria Category:
* Documentation-only change

**Comment by kit1980** [comment] 2024-09-26 22:55
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/136161

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136801

Criteria Category:
* Critical: CI fix

**Comment by eqy** [comment] 2024-09-27 19:28
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/130482

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136885

Criteria Category:
* exception for new feature (cuDNN SDPA + bias)

**Comment by jingxu10** [comment] 2024-09-27 20:16
Link to landed trunk PR (if applicable):
https://github.com/pytorch/pytorch/pull/134567
Link to release branch PR:
https://github.com/pytorch/pytorch/pull/136893
Criteria Category:
Docs -

**Comment by yifuwang** [comment] 2024-09-27 21:11
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/136577

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136894

Criteria Category:
* Critical fixes to new features introduced in the most recent minor release (SymmetricMemory)

**Comment by nWEIdia** [comment] 2024-09-27 21:48
Link to landed trunk PR (if applicable):

[https://github.com/pytorch/pytorch/pull/136818](https://github.com/pytorch/pytorch/pull/136818)

Link to release branch PR:
[https://github.com/pytorch/pytorch/pull/136898](https://github.com/pytorch/pytorch/pull/136898


Criteria Category:
Critical bug fixes for ARM CUDA binary. Making sure the binaries pick up the right cusparselt version that would support H100.

**Comment by wz337** [comment] 2024-09-27 22:29
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135725
* https://github.com/pytorch/pytorch/pull/136365

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136903

Criteria Category:
* Critical fix for crashes (due to hang and shape mismatch).

**Comment by drisspg** [comment] 2024-09-27 23:36
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135882

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/136905

Criteria Category:
* Critical Fix for bug when using flex-attention hard erroring

**Comment by Skylion007** [comment] 2024-09-28 15:18
Any PRs we need to add for notifying users for the CUDA 11.8/12.1 deprecation. They are no longer tested or supported by NVidia, and we do need to update them or overhaul our build system to use the latest NCCl / CUDNN libraries as a result.

**Comment by anijain2305** [comment] 2024-09-30 18:44
Link to landed trunk PR:
* https://github.com/pytorch/pytorch/pull/136516

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/137025

Critical Category:
* Critical bug fix to prevent recompilations with a new introduced feature in 2.5 called `inline_inbuilt_nn_modules`. This was discovered by Intel team in this [issue](https://github.com/pytorch/pytorch/issues/136254).

**Comment by chuanqi129** [comment] 2024-10-01 16:17
Link to landed trunk PR (if applicable):

https://github.com/pytorch/test-infra/pull/5648
https://github.com/pytorch/vision/pull/8656
https://github.com/pytorch/audio/pull/3833

Link to release branch PR:

https://github.com/pytorch/test-infra/pull/5728
https://github.com/pytorch/vision/pull/8663
https://github.com/pytorch/audio/pull/3836

Criteria Category:

Critical, CD wheel build with xpu on Windows to improve the UX

**Comment by atalman** [comment] 2024-10-01 23:32
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/builder/pull/2000
* https://github.com/pytorch/builder/pull/2003

Link to release branch PR:
* https://github.com/pytorch/builder/pull/2004

Criteria Category:
* CI/CD changes to remove usage of deprecated python 3.8

**Comment by drisspg** [comment] 2024-10-01 23:42
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135884

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/137146

Criteria Category:
* Part of previous critical fix, was blocked by triton pin update

**Comment by atalman** [comment] 2024-10-02 14:52
Link to landed trunk PR (if applicable):
* NA

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/137148
* https://github.com/pytorch/pytorch/pull/137177

Criteria Category:
* Release Only changes to allow push to DockerHub for Rocm builds

**Comment by atalman** [comment] 2024-10-03 13:55
Link to landed trunk PR (if applicable):
* https://github.com/pytorch/pytorch/pull/135510

Link to release branch PR:
* https://github.com/pytorch/pytorch/pull/137265

Criteria Category:
* Infra Related: Fix CI

**Comment by bsochack** [comment] 2024-10-05 11:21
Link to landed trunk PR (if applicable):
* #137394

Link to release branch PR:
* #137394

Criteria Category:
* Critical regression on Intel Gaudi accelerator

**Comment by vadimkantorov** [comment] 2024-10-07 21:18
Will https://github.com/pytorch/pytorch/pull/135404 make to 2.5.0? or also only to 2.5.1?

**Comment by ppwwyyxx** [comment] 2024-10-11 01:55
I wonder if it's too late to consider https://github.com/pytorch/pytorch/pull/137745. The same code that worked for us in 2.4 now crashed when using 2.5

**Comment by atalman** [comment] 2024-10-18 15:48
Closing this issue since 2.5.0 is completed

**Closed by atalman** 2024-10-18 15:48 UTC
Labels: oncall: releng, triaged, release tracker
