### ISSUE TITLE
[ONNX] How to export fx quantized model to onnx?

### ISSUE THREAD

**Issue by jinfagang** [pytorch/pytorch#75723] opened 2022-04-13 07:40 UTC
### 🚀 The feature, motivation and pitch

FX is great! How to export fx quantized model to onnx?

### Alternatives

Currently, I have traced the quantized int8 model to torchscript, it works OK.

### Additional context

I just wonder, If torch already supported export fx model to onnx, how to do it? I got error:
```
RuntimeError: Exporting the operator quantize_per_tensor to ONNX opset version 13 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.

```

If not support, then, when will support? What's the obstacles behind it?

**this is really needed, so that bring the gap between int8 quantize and other forward framework through onnx**

cc @ezyang @SherlockNoMad

**Comment by justinchuby** [comment] 2022-05-20 01:06
@BowenBao could you help adding information to this issue? Thanks!

**Comment by jinfagang** [comment] 2022-06-20 09:42
@BowenBao Does the newest torch version support fx quantized model export?

**Comment by justinchuby** [comment] 2022-07-26 19:14
quantize_per_tensor is supported I believe. Have you tried the latest nightly build?

**Comment by aimen123** [comment] 2022-08-07 02:00
nightly is supported,  but  gpu is not.    it is so bad

**Comment by thiagocrepaldi** [comment] 2022-11-15 23:44
@jinfagang This bug is being closed as there is no runnable repro to validate/help understand the exact issue.

Feel free to reopen it with a repro if the issue is still relevant on latest torch master branch

**Closed by thiagocrepaldi** 2022-11-15 23:44 UTC
Labels: module: onnx, triaged, onnx-needs-info, module: fx
