### ISSUE TITLE
random_ not working on cuda

### ISSUE THREAD

**Issue by glample** [pytorch/pytorch#1162] opened 2017-03-31 18:59 UTC
The first line is working, the second one, on GPU, returns an error

```python
torch.FloatTensor(3, 4).random_(2)
torch.FloatTensor(3, 4).cuda().random_(2)
```

```
AttributeError: 'FloatTensor' object has no attribute 'random_'
```

**Comment by albanD** [comment] 2017-03-31 19:46
It is expected as this function is not implemented in cuda.

**Comment by soumith** [comment] 2017-04-02 18:45
duplicate of https://github.com/pytorch/pytorch/issues/712

**Closed by soumith** 2017-04-02 18:45 UTC
Labels: enhancement, medium priority
