### ISSUE TITLE
torch._foreach_mul_ segmentation fault

### ISSUE THREAD

**Issue by alanhe151220037** [pytorch/pytorch#113156] opened 2023-11-07 13:11 UTC
### 🐛 Describe the bug

The following example will cause segmentation fault. 
```
import torch
import numpy as np
x_array = np.array([],dtype=np.float16)
x_tensor = torch.from_numpy(x_array)
torch._foreach_mul_((x_tensor,),1.0)
```
```
Segmentation fault (core dumped)
```
Strangely, only `torch._foreach_mul_` will have this problem and `torch._foreach_div_` is fine. Although I haven't quite understand the direct segmentation fault reason, but I think this may caused by the following code that `mul_.Scalar` calls `mul.out` but  `div_.scalar` calls `div_.Tensor`.
https://github.com/pytorch/pytorch/blob/c6f435befd633ae3fecf52c597c78f0934c7537c/aten/src/ATen/native/BinaryOps.cpp#L997-L999
https://github.com/pytorch/pytorch/blob/c6f435befd633ae3fecf52c597c78f0934c7537c/aten/src/ATen/native/BinaryOps.cpp#L897-L899
And, after I rewrite the `mul_.Scalar` like `div_.scalar`, it works!

### Versions

PyTorch version: 2.2.0a0+git0d669f0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (aarch64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: Could not collect
CMake version: version 3.20.5
Libc version: glibc-2.31

Python version: 3.9.17 (main, Jul  5 2023, 20:44:37)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-4.19.90-2107.6.0.0098.oe1.bclinux.aarch64-aarch64-with-glibc2.31
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

cc @malfet @mruberry @rgommers

**Comment by jon-chuang** [comment] 2023-11-07 14:29
Does this occur without `np`?

**Comment by malfet** [comment] 2023-11-07 16:57
I suspect root of the problem is the same as https://github.com/pytorch/pytorch/issues/113037 ....

**Comment by malfet** [comment] 2023-11-07 17:00
> Does this occur without `np`?

I suspect that it would not, because some of the assumption we made in PyTorch about what constitute a scalar (or tensor-wrapped-scalar) are wrong for empty tensors created from numpy

**Comment by alanhe151220037** [comment] 2023-11-07 17:06
> Does this occur without `np`?

No，only with np

**Comment by malfet** [comment] 2023-11-07 18:16
Yes, this might not look the same, but this is a duplicate of https://github.com/pytorch/pytorch/issues/113037 as it crashes because `iter.is_scalar(2)` returns true on an empty tensor

**Comment by malfet** [comment] 2023-12-15 18:05
Closing as duplicate of https://github.com/pytorch/pytorch/issues/113037 (also it is already fixed in nightlies)

**Closed by malfet** 2023-12-15 18:05 UTC
Labels: module: crash, module: error checking, triaged, module: numpy, module: edge cases
