### ISSUE TITLE
RFC: PyTorch Next Wheel Build Platform: manylinux

### ISSUE THREAD

**Issue by Mrsaim128** [pytorch/pytorch#143793] opened 2024-12-24 06:28 UTC
### 🐛 Describe the bug

 [https://rb.gy/5dxbov]

Overview
This Request for Comments (RFC) proposes updating the build platform for PyTorch wheels to support manylinux_2_28, the latest version of the manylinux standard. The update aims to enhance compatibility with modern Linux distributions, improve performance, and reduce the maintenance burden associated with legacy systems.

Motivation
PyTorch currently targets manylinux2014, which works for most Linux distributions. However, as modern Linux systems evolve, it’s important to adopt newer standards to:

Leverage modern system optimizations.
Reduce compatibility issues with outdated distributions.
Streamline the development and testing process.
Updating to manylinux_2_28 will support newer libraries and performance improvements, ensuring PyTorch remains optimized for a broad range of Linux environments.

Proposal
The proposal includes:

Migrating PyTorch wheel builds to manylinux_2_28.
Maintaining manylinux2014 support during a transition phase.
Updating the PyTorch CI/CD pipeline to test both manylinux2014 and manylinux_2_28 wheels for compatibility.
Compatibility Overview:
manylinux Version	Supported Distributions	Proposed Status
manylinux2014	CentOS 7, Ubuntu 18.04, etc.	Transitional Support
manylinux_2_28	CentOS 8, Ubuntu 20.04, etc.	Full Support
Benefits
Better Compatibility: Supports modern Linux distributions like CentOS 8 and Ubuntu 20.04.
Simplified Maintenance: Reduces complexity by focusing on more recent distributions and dependencies.
Performance Boost: Enhances system performance by utilizing more modern features and optimizations.
Challenges
Legacy Systems: Some users on older distributions may face compatibility issues during the transition.
Testing Overhead: Additional testing is required to ensure that both older and newer platforms function properly.
Timeline
Phase 1: Rollout of dual support for both manylinux2014 and manylinux_2_28 (3 months).
Phase 2: Discontinue manylinux2014 support after 6 months, based on community feedback.
Conclusion

1. This update ensures that PyTorch remains forward-looking and compatible with the most widely used Linux distributions, reducing future maintenance needs and enhancing performance for users.[https://rb.gy/5dxbov](url)

### Versions

RFC: PyTorch Next Wheel Build Platform: manylinux

cc @seemethere @malfet @osalpekar @atalman

**Comment by atalman** [comment] 2024-12-24 14:08
Hi @Mrsaim128 Thank you for the issue. We are currently Migrating to Manylinux 2.28. Issue:
https://github.com/pytorch/pytorch/issues/123649

Dev discuss post: https://dev-discuss.pytorch.org/t/pytorch-linux-wheels-switching-to-new-wheel-build-platform-manylinux-2-28-on-november-12-2024/2581

**Comment by malfet** [comment] 2024-12-26 17:58
Closing this one as duplicate of https://github.com/pytorch/pytorch/issues/123649

**Closed by malfet** 2024-12-26 17:58 UTC
Labels: module: binaries, module: build, triaged
