### ISSUE TITLE
torch.compile got RuntimeError for custom device with privateuse1

### ISSUE THREAD

**Issue by heidongxianhua** [pytorch/pytorch#101326] opened 2023-05-13 03:01 UTC
### 🐛 Describe the bug

I got runtimeError when run torch.compile for custom device  with custom device.
I build pytorch in DEBUG mode, and the fallowing is the error info:
 The testcase is in  https://github.com/pytorch/pytorch/compare/main...heidongxianhua:test_compile?expand=1
In the func of `custom_add_Tensor`, the device of input tensors should be `privateuse1`, but got `meta`. And I have debug it,  it was caused in  the `python_dispatcher` func `c10::DispatchKey k = ks.highestPriorityTypeId();` in file of `torch\csrc\PyInterpreter.cpp`. and I have compare to run the code on CUDA and Privateuse1.

```
  DispatchKey highestPriorityTypeId() const {
    auto functionality_k = highestFunctionalityKey();
    if (isPerBackendFunctionalityKey(functionality_k)) {
      return toRuntimePerBackendFunctionalityKey(
          functionality_k, highestBackendKey());   
        # on cuda, the value of highestBackendKey() is 'meta', but on privateuse1 it is `privateuse1`, and then I got the error.
    }
    return functionality_k;
  }
```
And  I can't find the root cause.

``` the error info when run testcase
Creating extension directory /root/.cache/torch_extensions/py38_cpu/custom_device_extension...
Emitting ninja build file /root/.cache/torch_extensions/py38_cpu/custom_device_extension/build.ninja...
Building extension module custom_device_extension...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] c++ -MMD -MF open_registration_extension.o.d -DTORCH_EXTENSION_NAME=custom_device_extension -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -I/home/shibo/device_type/pytorch_shibo/test/cpp_extensions -isystem /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/include -isystem /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/include/TH -isystem /root/anaconda3/envs/test/lib/python3.8/site-packages/torch/include/THC -isystem /root/anaconda3/envs/test/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -g -c /home/shibo/device_type/pytorch_shibo/test/cpp_extensions/open_registration_extension.cpp -o open_registration_extension.o
[2/2] c++ open_registration_extension.o -shared -L/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o custom_device_extension.so
Loading extension module custom_device_extension...
 [call] op=[aten::empty.memory_format], key=[BackendSelect]
  [redispatch] op=[aten::empty.memory_format], key=[PrivateUse1]
 [callBoxed] op=[profiler::_record_function_enter_new], key=[Undefined]
 [call] op=[aten::clone], key=[AutogradCPU]
  [redispatch] op=[aten::clone], key=[CPU]
   [call] op=[aten::empty_strided], key=[BackendSelect]
    [redispatch] op=[aten::empty_strided], key=[CPU]
   [call] op=[aten::copy_], key=[CPU]
 [call] op=[aten::empty_strided], key=[BackendSelect]
  [redispatch] op=[aten::empty_strided], key=[Meta]
 [call] op=[aten::detach], key=[AutogradMeta]
  [redispatch] op=[aten::detach], key=[ADInplaceOrView]
   [redispatch] op=[aten::detach], key=[Meta]
 [call] op=[aten::clone], key=[AutogradCPU]
  [redispatch] op=[aten::clone], key=[CPU]
   [call] op=[aten::empty_strided], key=[BackendSelect]
    [redispatch] op=[aten::empty_strided], key=[CPU]
   [call] op=[aten::copy_], key=[CPU]
 [call] op=[aten::add.Tensor], key=[PythonDispatcher]
  [redispatchBoxed] op=[aten::add.Tensor], key=[PythonDispatcher]
   [redispatch] op=[aten::add.Tensor], key=[PythonDispatcher]
    [callBoxed] op=[aten::add.Tensor], key=[PythonDispatcher]
in custom_add_Tensor self device:meta, other device:meta
 [callBoxed] op=[profiler::_record_function_exit._RecordFunction], key=[Undefined]
E
======================================================================
ERROR: test_custom_device_compile (__main__.TestCppExtensionOpenRgistration)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1309, in run_node
    return node.target(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/utils/_stats.py", line 20, in wrapper
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1105, in __torch_dispatch__
    return self.dispatch(func, types, args, kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_subclasses/fake_tensor.py", line 1314, in dispatch
    r = func(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_ops.py", line 398, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: tensor device should be privateuse1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1256, in get_fake_value
    return wrap_fake_exception(
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 850, in wrap_fake_exception
    return fn()
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1257, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1321, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in function add>(*(FakeTensor(..., device='foo:0', size=(4, 4)), FakeTensor(..., device='foo:0', size=(4, 4))), **{}):
tensor device should be privateuse1
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_cpp_extensions_open_device_registration.py", line 121, in test_custom_device_compile
    out = fn(inputs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 286, in _fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1502, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1511, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 439, in catch_errors
    return callback(frame, cache_size, hooks, frame_state)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 523, in _convert_frame
    result = inner_convert(frame, cache_size, hooks, frame_state)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 125, in _fn
    return fn(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 358, in _convert_frame_assert
    return _compile(
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 177, in time_wrapper
    r = func(*args, **kwargs)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 428, in _compile
    out_code = transform_code_object(code, transform)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 1000, in transform_code_object
    transformations(instructions, code_options)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 413, in transform
    tracer.run()
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 2010, in run
    super().run()
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 703, in run
    and self.step()
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 663, in step
    getattr(self, inst.opname)(inst)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 160, in impl
    self.push(fn_var.call_function(self, self.popn(nargs), {}))
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/variables/builtin.py", line 536, in call_function
    return wrap_fx_proxy(tx, proxy, **options)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 990, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/variables/builder.py", line 1025, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/root/anaconda3/envs/test/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 1288, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError:

from user code:
   File "test_cpp_extensions_open_device_registration.py", line 109, in forward
    x = x + x


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True


----------------------------------------------------------------------
Ran 1 test in 21.787s

FAILED (errors=1)


```

### Versions

version
master version git commit 253b9d3247d580f1d9ca8bd4d422107f26753131

cc @ezyang @msaroufim @wconstab @ngimel @bdhirsh @anijain2305

**Comment by bdhirsh** [comment] 2023-05-17 20:17
Thanks for the detailed logs Heidong! Looks like a dupe of https://github.com/pytorch/pytorch/issues/101244, so I'll close in favor of that issue.

**Closed by bdhirsh** 2023-05-17 20:17 UTC
Labels: triaged, oncall: pt2
