### ISSUE TITLE
How do you add quantized training?

### ISSUE THREAD

**Issue by bionicles** [pytorch/pytorch#27747] opened 2019-10-11 16:26 UTC
## 🚀 Feature
Would it be possible to train the model with quantization?

## Motivation
Memory issues are common and quantized training can help

## Pitch
User can set a flag for quantized training and it happens. Might require backprop over the expectation. If it's impossible to do quantized training, perhaps then docs could point to nevergrad (we could just evolve the weights in this case)

## Alternatives

NVIDIA APEX has reduced-precision; You can train in fp16 in tensorflow
https://github.com/NVIDIA/apex

Brevitas appears to offer this feature (havent tested personally)
https://github.com/Xilinx/brevitas

## Additional context
Smaller weights = More cool models

cc @jerryzh168 @jianyuh @dzhulgakov

**Comment by dzhulgakov** [comment] 2019-10-12 06:55
Actually training model in int8 is an open area of research at this point and I don't think it's been demonstrated to reliably work (float16 and bfloat16 work reasonably well as you pointed out).

What you probably refer is so called "quantization-aware training" which simulates accuracy drop in model's forward to allow the model to "learn around" the accuracy loss in inference. However, in this case forward and backward are still run in float, just the weights and activations are being clipped.

This is what Brevitas implements and it's roughly equivalent to what PyTorch quantization package supports: https://pytorch.org/docs/stable/quantization.html#quantization-workflows (see item 3).

We also will land a more detailed tutorial in the next couple of days on how to use it.

**Comment by bionicles** [comment] 2019-10-12 14:31
OK, any progress on reduced memory use in training would be useful on the biomolecular front. carry on

**Comment by raghuramank100** [comment] 2019-10-14 17:32
Hi, quantization aware training will require more memory than regular floating point training as additional modules (fake quantization modules) are inserted during training. The focus of quantization aware training is to produce a quantized model for inference with higher accuracy than other techniques. 
Apex can be used for training models, even with quantization aware training. We havent completed the experiments with apex, but will post code this week with an example training script. 
The current tutorial shows how to do quantization aware training: https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html.
Can you comment on what type of models would benefit with reduced precision during training?

**Comment by tmlstrong** [comment] 2020-07-24 11:36
Hi @raghuramank100, I am following the tutorial: https://pytorch.org/tutorials/advanced/static_quantization_tutorial.html for Quantization aware training, but I have an issue when run it.
This is the error log for my issue:

> Traceback (most recent call last):
  File "train_refinedet.py", line 271, in <module>
    train()
  File "train_refinedet.py", line 244, in train
    quantized_model = torch.quantization.convert(net.eval(), inplace=False)
  File "/usr/local/lib/python3.6/dist-packages/torch/quantization/quantize.py", line 299, in convert
    module = copy.deepcopy(module)
  File "/usr/lib/python3.6/copy.py", line 180, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib/python3.6/copy.py", line 280, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 240, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib/python3.6/copy.py", line 150, in deepcopy
    y = copier(x, memo)
  File "/usr/lib/python3.6/copy.py", line 220, in _deepcopy_tuple
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.6/copy.py", line 220, in <listcomp>
    y = [deepcopy(a, memo) for a in x]
  File "/usr/lib/python3.6/copy.py", line 161, in deepcopy
    y = copier(memo)
  File "/usr/local/lib/python3.6/dist-packages/torch/tensor.py", line 44, in __deepcopy__
    raise RuntimeError("Only Tensors created explicitly by the user "
RuntimeError: Only Tensors created explicitly by the user (graph leaves) support the deepcopy protocol at the moment

Can you tell me what the cause is?

**Comment by vkuzo** [comment] 2021-03-31 23:24
closing since there hasn't been activity for awhile.  Please feel free to ask us questions at https://discuss.pytorch.org/c/quantization/17

**Closed by vkuzo** 2021-03-31 23:24 UTC
Labels: feature, oncall: quantization, triaged
