### ISSUE TITLE
Support `scaled_dot_product_attention` onnx export

### ISSUE THREAD

**Issue by fxmarty** [pytorch/pytorch#96944] opened 2023-03-16 09:07 UTC
### 🚀 The feature, motivation and pitch

`scaled_dot_product_attention` is great, but it would be even better to have support for the ONNX export of it that would standardize it's representation for tools like ORT or TensorRT to consume it. This is probably not the highest priority given the torchinductor direction taken, but would still be useful to have a standardized representation.

I could give it a try if I find time.

Currently we hit `Exporting the operator 'aten::scaled_dot_product_attention' to ONNX opset version 18 is not supported.`

### Alternatives

disable the use of `scaled_dot_product_attention` during the export

cc @jbschlosser @bhosmer @cpuhrsch @erichan1

**Comment by abock** [comment] 2023-03-22 18:30
Closing as a duplicate of [97262](https://github.com/pytorch/pytorch/issues/97262). Please follow that issue as there is a suggestion to [register this as a custom op](https://pytorch.org/docs/master/onnx.html#onnx-script-functions).

**Closed by abock** 2023-03-22 18:30 UTC
Labels: module: onnx, oncall: transformer/mha
