### ISSUE TITLE
[elastic launcher] restart on startup failure makes no sense

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60910] opened 2021-06-28 22:07 UTC
## Motivation

If a program failed to start, elastic shouldn't try to restart. It should remain down. There needs to be some reasonable logic that restarts only when the program has started normally and then failed after some epochs / steps.

Since some programs may take as long as 10-15 min to start (huge models on multi-node envs), I propose a new configurable timer CLI arg, which I'd say should default to at least 15min - based on my current experiments. e.g. `--restart_threhold`

So the restart feature should kick in only if that threshold has been passed and otherwise do nothing.

thank you!

**Comment by stas00** [comment] 2021-07-22 22:55
anybody?

Can we at the very least have the old behaviour restored and set the default `--max_restarts 0`. 

The new launcher is not backward compatible.

**Comment by stas00** [comment] 2021-07-22 22:57
IMHO, It shouldn't be labelled `elastic`, but `distributed`. You made `elastic` the default, so it's no longer an obscure domain.

**Comment by stas00** [comment] 2021-07-22 23:08
Moreover, the new launcher dumps all this useless info obscuring the real error:

```

**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 3094556 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
  warnings.warn(_no_error_file_warning_msg(rank, failure))
Traceback (most recent call last):
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/distributed/launch.py", line 173, in <module>
    main()
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/distributed/launch.py", line 169, in main
    run(args)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/distributed/run.py", line 621, in run
    elastic_launch(
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 116, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 348, in wrapper
    return f(*args, **kwargs)
  File "/home/stas/anaconda3/envs/py38-pt19/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 245, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
***************************************
         pretrain_gpt.py FAILED
=======================================
Root Cause:
[0]:
  time: 2021-07-22_16:06:38
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 3094556)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
=======================================
Other Failures:
  <NO_OTHER_FAILURES>
***************************************
```

of what use is all that? I need to see the backtrace that lead to the failure, not the noise from the launcher.

**Comment by d4l3k** [comment] 2021-07-22 23:34
--max_restarts has been returned to 0 as of https://github.com/pytorch/pytorch/pull/61294

**Comment by kiukchung** [comment] 2021-07-23 00:02
> If it really has to be dumped, please save the real traceback, dump the info, and then print the actual traceback that the user needs to debug their program

This is precisely what the warning message is enabling:
```
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
```

We've added this feature in torchelastic from our experience in operating large scale distributed torch jobs at Facebook. When running with multiple workers per node, it is hard to dig through the logs to pinpoint the root cause error. Empirically we've observed that the "first" error is typically the root cause error hence by adding the `@record` decorator on each worker's main entrypoint function, it allows us to capture structured error information on the worker subprocess and display the most relevant stack trace to the end user.

The old `torch.distributed.launch` tool is a single file script so if it better fits your needs you should be able to clone it off the 1.8.1 branch (https://raw.githubusercontent.com/pytorch/pytorch/v1.8.1/torch/distributed/launch.py). 

As discussed extensively on https://github.com/pytorch/pytorch/issues/60754, we did introduce a couple of unintended functional regressions to `torch.distributed.launch` by proxying it to `torch.distributed.run`, for which the fixes have landed in the nightly builds & docs. For this particular issue, we do feel like this error surfacing logic will enhance the user experience long term. If you still observe annoyances after trying out the `@record` annotation in the training script, do let us know.

**Closed by kiukchung** 2021-07-23 00:02 UTC
Labels: module: elastic, triaged

**Comment by stas00** [comment] 2021-07-23 00:08
Thank you very much for explaining the new functionality, @kiukchung. I will give it a try.

Though you closed the issue prematurely. The OP Issue wasn't about the warnings. It was about elastic restarting itself on immediate failure, which at least to me is illogical. If it's logical to you, then indeed there is no reason to keep this issue alive.

**Comment by kiukchung** [comment] 2021-07-23 00:30
No problem @stas00, happy to provide context. There indeed were plans to add different types of "retry" policies with features like jitter between retries and "cool down" periods (just like you suggested). But we've actually built this functionality into our internal schedulers rather than elastic since retries driven outside the knowledge of the scheduler caused a couple of headaches (e.g. log streams are not partitioned per retry since the scheduler does not know about the "locally" driven retries).

In short --max_retries was supposed to be set to 0 by default and only set to >=1 for those users who were OK with the naive "immediate" retries. Even in the absence of torchelastic driven retries, torchelastic is still required to support advanced scheduler retry policies such as "retry node in-place" as the torchelastic agent essentially coordinates the shutdown and re-initialization of other nodes.

I think for the launcher CLI, setting retries to anything other than 0 doesn't make too much sense since the CLI's main audience are end users who are iterating on their training script or launching one-off jobs and these folks would much rather have a "fail-fast" rather than a "durable" experience.

**Comment by stas00** [comment] 2021-07-23 01:07
Your explanation is very satisfactory. Thank you, @kiukchung 

The only other thing I was thinking is to your comment https://github.com/pytorch/pytorch/issues/60910#issuecomment-885311778 - the issue is that this is end users that usually have to endure this problem, and they may or may not be able to insert `@record` into the code they don't own.

For example, I had troubles launching Megatron-LM, I can't change their code to insert `@record` as it's not under my control. Surely, I can edit the copy, but that requires a prior understanding of where to add it. Surely, this is a great feature for developers, but the end user is till left w/o control a bit.

Therefore perhaps the long output is only useful if the `record` was actually used and if not then just printing the traceback from the user script. Or at the very least having a `--no_record_bt_only_please` flag that can manually turn it off if the user knows they can't add the `record`. Does that make sense or am I missing something obvious here?

**Comment by kiukchung** [comment] 2021-07-23 02:25
> For example, I had troubles launching Megatron-LM, I can't change their code to insert @record as it's not under my control.
Gotcha, fair point

So I looked through the code again with @aivanou's help and it turns out we've actually addressed part of the "noisy" warning message with all the fixes that went into addressing the other regressions.

On `torch-1.10.0.dev20210721+cu102`, running a script that simply throws an error:

```
# test_script.py
raise RuntimeError("foobar")

$ python -m torch.distributed.launch ~/tmp/test_script.py

FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/ubuntu/tmp/test_script.py", line 5, in <module>
    raise RuntimeError("foobar")
RuntimeError: foobar
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 42122) of binary: /home/ubuntu/.pyenv/versions/venv385/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in <module>
    main()
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 187, in main
    launch(args)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 173, in launch
    run(args)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/run.py", line 688, in run
    elastic_launch(
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
******************************************
  /home/ubuntu/tmp/test_script.py FAILED
==========================================
Root Cause:
[0]:
  time: 2021-07-23_02:17:24
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 42122)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
==========================================
Other Failures:
  <NO_OTHER_FAILURES>
******************************************
```

and for more than 1 process:

```
python -m torch.distributed.launch --nproc_per_node 4 ~/tmp/test_script.py                                                                                                                                                               ~
FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed.
*****************************************
Traceback (most recent call last):
  File "/home/ubuntu/tmp/test_script.py", line 5, in <module>
    raise RuntimeError("foobar")
RuntimeError: foobar
Traceback (most recent call last):
  File "/home/ubuntu/tmp/test_script.py", line 5, in <module>
    raise RuntimeError("foobar")
RuntimeError: foobar
Traceback (most recent call last):
  File "/home/ubuntu/tmp/test_script.py", line 5, in <module>
Traceback (most recent call last):
    raise RuntimeError("foobar")
  File "/home/ubuntu/tmp/test_script.py", line 5, in <module>
RuntimeError: foobar
    raise RuntimeError("foobar")
RuntimeError: foobar
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 43258) of binary: /home/ubuntu/.pyenv/versions/venv385/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in <module>
    main()
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 187, in main
    launch(args)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 173, in launch
    run(args)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/run.py", line 688, in run
    elastic_launch(
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
******************************************
  /home/ubuntu/tmp/test_script.py FAILED
==========================================
Root Cause:
[0]:
  time: 2021-07-23_02:22:07
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 43258)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
==========================================
Other Failures:
[1]:
  time: 2021-07-23_02:22:07
  rank: 1 (local_rank: 1)
  exitcode: 1 (pid: 43259)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[2]:
  time: 2021-07-23_02:22:07
  rank: 2 (local_rank: 2)
  exitcode: 1 (pid: 43260)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
[3]:
  time: 2021-07-23_02:22:07
  rank: 3 (local_rank: 3)
  exitcode: 1 (pid: 43261)
  error_file: <N/A>
  msg: "Process failed with exitcode 1"
******************************************
```

The summary is still printed out at the end, but the output around `CHILD PROCESS FAILED WITH NO ERROR_FILE `:

```
**********************************************************************
               CHILD PROCESS FAILED WITH NO ERROR_FILE                
**********************************************************************
CHILD PROCESS FAILED WITH NO ERROR_FILE
Child process 3094556 (local_rank 0) FAILED (exitcode 1)
Error msg: Process failed with exitcode 1
Without writing an error file to <N/A>.
While this DOES NOT affect the correctness of your application,
no trace information about the error will be available for inspection.
Consider decorating your top level entrypoint function with
torch.distributed.elastic.multiprocessing.errors.record. Example:

  from torch.distributed.elastic.multiprocessing.errors import record

  @record
  def trainer_main(args):
     # do train
**********************************************************************
```

has been removed.

**Comment by kiukchung** [comment] 2021-07-23 02:35
Tried one more thing on `torch-1.10.0.dev20210721+cu102`. If you can and actually annotate the "main" function of the training script as:

```
# test_script.py
from torch.distributed.elastic.multiprocessing.errors import record

@record
def main():
    raise RuntimeError("foobar")

if __name__ == "__main__":
    main()
```

And run this as:

```
$ python -m torch.distributed.launch ~/tmp/test_script.py

(venv385) ubuntu@ip-172-31-26-180% python -m torch.distributed.launch --nproc_per_node 1 ~/tmp/test_script.py                                                                                                                                                               ~
/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py:177: FutureWarning: The module torch.distributed.launch is deprecated
and will be removed in future. Use torch.distributed.run.
Note that --use_env is set by default in torch.distributed.run.
If your script expects `--local_rank` argument to be set, please
change it to read from `os.environ['LOCAL_RANK']` instead. See
https://pytorch.org/docs/stable/distributed.html#launch-utility for
further instructions

  warnings.warn(
Traceback (most recent call last):
  File "/home/ubuntu/tmp/test_script.py", line 11, in <module>
    main()
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 351, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/tmp/test_script.py", line 8, in main
    raise RuntimeError("foobar")
RuntimeError: foobar
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 45074) of binary: /home/ubuntu/.pyenv/versions/venv385/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/.pyenv/versions/3.8.5/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 191, in <module>
    main()
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 187, in main
    launch(args)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launch.py", line 173, in launch
    run(args)
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/run.py", line 688, in run
    elastic_launch(
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 131, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 259, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
**********************************************************************************************************************************************************************************************************************************************************
                                                                                                          /home/ubuntu/tmp/test_script.py FAILED
==========================================================================================================================================================================================================================================================
Root Cause:
[0]:
  time: 2021-07-23_02:28:59
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 45074)
  error_file: /tmp/torchelastic_bzsdfvsx/none_ss2g9ply/attempt_0/0/error.json
  msg: "{'message': 'RuntimeError: foobar', 'extraInfo': {'py_callstack': 'Traceback (most recent call last):\n  File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 351, in wrapper\n    return f(*args, **kwargs)\n  File "/home/ubuntu/tmp/test_script.py", line 8, in main\n    raise RuntimeError("foobar")\nRuntimeError: foobar\n', 'timestamp': '1627007339'}}"
==========================================================================================================================================================================================================================================================
Other Failures:
  <NO_OTHER_FAILURES>
**********************************************************************************************************************************************************************************************************************************************************
```

As you can see, the summary message at the end will contain a structured error, with not just the stack trace but also a few other useful information like the rank, local_rank, pid, and the timestamp of the error. 

To give you a bit more context, the default "handler" prints this message into the console, but is easy to hook a custom implementation to parse and handle (similar to a custom logging handler) the error as needed by the production stack. For instance one could implement a error handler that instead records these errors to a error database then track particular error signatures and alarm on some threshold. Which is precisely what we do for our internal production jobs.

**Comment by stas00** [comment] 2021-07-23 02:40
1. To you previous to last comment - That'd be a noticeable improvement with 2-4 GPUs.

I currently work with 256 to 512 GPUs. Can you see that the above will now dump a huge amount of info per rank that is not helping to see the error? How many page up will I need to manually scroll up to get to the actual traceback?

2. To your last comment with proper annotation. Much much better! Except the traceback is not properly formatted - so it'd hard to make use of in quick debug cycles. We, the users need to see the familiar traceback to quickly make sense of it. The current output looks suited to feeding another program.

And we started a discussion on slack about having an option to print only one of those and not 512, since most of the time the traceback is identical.

**Comment by stas00** [comment] 2021-07-23 02:45
It might be difficult to satisfy all the different often conflicting preferences, so in such situations it often helps to have flags that can toggle any of these features on/off, while choosing the most sensible defaults for the most common use (or the least advanced use).

**Comment by kiukchung** [comment] 2021-07-23 04:15
> I currently work with 256 to 512 GPUs. 

I'm assuming you are launching 256-512 workers across 256/8 = 32, 512/8 = 64 hosts? What scheduler are you using? Typically the scheduler should provide logs per container so you would at max have 8 per rank (potentially duplicated) summaries at the end?

> Except the traceback is not properly formatted

Yep I noticed this as well. Should be straight forward to pretty print to make it look something like:

```
Root Cause:
[0]:
  time: 2021-07-23_02:28:59
  rank: 0 (local_rank: 0)
  exitcode: 1 (pid: 45074)
  error_file: /tmp/torchelastic_bzsdfvsx/none_ss2g9ply/attempt_0/0/error.json
  msg: 
   {
     "message": "RuntimeError: foobar",
      "extraInfo": {
         "py_callstack": 
              Traceback (most recent call last):
                 File "/home/ubuntu/.pyenv/versions/venv385/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 351, in wrapper
                      return f(*args, **kwargs)
                  File "/home/ubuntu/tmp/test_script.py", line 8, in main
                       raise RuntimeError("foobar")
               RuntimeError: foobar"
       }
   }
```

Will see if we can get a fix PR for this soon.

**Comment by stas00** [comment] 2021-07-23 04:49
On this particular HPC it's pt-1.8 so it's the good old `launch` if that's what you mean by the scheduler. It's of course via SLURM. It's per 4, so 64 and 128 hosts. I have never tried to count how many tracebacks are being dumped, but the output is a huge mix of interleaved tracebacks.

I'm using:
```
export LAUNCHER="python -u -m torch.distributed.launch \
    --nproc_per_node $GPUS_PER_NODE \
    --nnodes $NNODES \
    --master_addr $MASTER_ADDR \
    --master_port $MASTER_PORT \
    "
 srun --jobid $SLURM_JOBID bash -c '$LAUNCHER --node_rank $SLURM_PROCID $CMD' 
```

> Will see if we can get a fix PR for this soon.

Thank you!
