### ISSUE TITLE
[jit][script] torch.jit.script does not support nn.RNN

### ISSUE THREAD

**Issue by alanhdu** [pytorch/pytorch#28418] opened 2019-10-22 15:25 UTC
## 🐛 Bug

`torch.jit.script` does not seem to support `nn.RNN`

## To Reproduce

Running

```python
import torch
import torch.nn as nn

torch.jit.script(nn.RNN(32, 64, 1))
```

fails with

```
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    torch.jit.script(nn.RNN(32, 64, 1))
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/__init__.py", line 1203, in script
    return torch.jit.torch.jit._recursive.recursive_script(obj)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/_recursive.py", line 173, in recursive_script
    return copy_to_script_module(mod, overload_stubs + stubs)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/_recursive.py", line 95, in copy_to_script_module
    torch.jit._create_methods_from_stubs(script_module, stubs)
  File "/opt/anaconda/envs/test/lib/python3.6/site-packages/torch/jit/__init__.py", line 1423, in _create_methods_from_stubs
    self._c._create_methods(self, defs, rcbs, defaults)
RuntimeError: 
Tensor cannot be used as a tuple:
at /opt/anaconda/envs/test/lib/python3.6/site-packages/torch/nn/modules/rnn.py:184:67
    def forward(self, input, hx=None):
        is_packed = isinstance(input, PackedSequence)
        if is_packed:
            input, batch_sizes, sorted_indices, unsorted_indices = input
                                                                   ~~~~~ <--- HERE
            max_batch_size = batch_sizes[0]
            max_batch_size = int(max_batch_size)
        else:
            batch_sizes = None
            max_batch_size = input.size(0) if self.batch_first else input.size(1)
            sorted_indices = None
            unsorted_indices = None

        if hx is None:
```

## Expected behavior

That you can successfully jit `nn.RNN` like you can with `nn.LSTM` and `nn.GRU`.

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```PyTorch version: 1.3.0
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: Could not collect

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] numpy==1.17.2
[pip] torch==1.3.0
[conda] cpuonly                   1.0                           0    pytorch
[conda] mkl                       2019.4                      243  
[conda] pytorch                   1.3.0               py3.6_cpu_0  [cpuonly]  pytorch
```

cc @suo

**Comment by suo** [comment] 2019-10-22 17:18
Thanks for the report! afaik this should work—@wanchaol, @eellison, can you take a look?

**Comment by dreiss** [comment] 2019-12-05 00:50
`LSTM` and `GRU` (in the same file) have code that looks like this:

```
        # xxx: isinstance check needs to be in conditional for TorchScript to compile
        if isinstance(orig_input, PackedSequence):
```

Maybe the short-term fix is as simple as manually inlining `is_packed`?

**Comment by you74674** [comment] 2020-02-04 11:38
> Maybe the short-term fix is as simple as manually inlining `is_packed`?
It seems like that's not enough, another problem is about the rnn_impls dict.
I tried also inline _VF.rnn_tanh and _VF.rnn_relu, but there are still problems.
I think it need to be totally rewritten like LSTM and GRU.

**Comment by suo** [comment] 2020-02-04 19:48
This is a duplicate of https://github.com/pytorch/pytorch/issues/32976, there is a workaround there.

**Comment by you74674** [comment] 2020-02-05 03:01
> 
> 
> This is the same underlying cause as #32976, there is a workaround there. We'll be looking to fix this in a coming release.

That doesn't seem to be the same problem.
The problem in the issue you mentioned happens when calling forward function, 
but this problem happens when you call torch.jit.script on torch.nn.RNN.

**Comment by suo** [comment] 2020-02-06 18:11
you are correct, my mistake. @wanchaol do you have some time to look into this?

**Comment by wanchaol** [comment] 2020-02-06 18:13
I will take a look at this soon.

**Comment by suo** [comment] 2020-02-06 18:21
Actually, @eellison: it looks like when you added overloads to LSTM/GRU you didn't add to RNN as well

**Comment by eellison** [comment] 2020-02-07 03:59
that wasn't really related... i just refactored the existing implementations

**Comment by wantsu** [comment] 2020-05-23 15:43
I can't find the code of _VF.rnn_tanh and _VF.rnn_relu,  in source, anybody can tell me where are they? Thanks

**Comment by tengerye** [comment] 2020-09-28 11:37
Hi, by any chance, has the issue been solved yet please?

**Comment by neginraoof** [comment] 2020-10-06 15:45
I'm also facing this issue when trying to script and export the RNN module to ONNX.

**Comment by suo** [comment] 2020-11-17 19:02
The code in the issue description still doesn't work as written. For people following along at home I'm going to reproduce the workaround mentioned in https://github.com/pytorch/pytorch/issues/32976:
```
class Foo(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.scripted_lstm = scripted_lstm

    def forward(self, input):
        return self.scripted_lstm(input)

foo = torch.jit.script(Foo())
```

**Closed** 2021-11-16 00:22 UTC
Labels: oncall: jit, triaged
