### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED while trying to download pretrained model

### ISSUE THREAD

**Issue by muxgt** [pytorch/pytorch#33288] opened 2020-02-13 12:58 UTC
## 🐛 Bug

Trying to use pretrained model from torchvision and receiving `urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>` when downloading. In similar issues #33233 and #33234 it was said that problem is solved but I'm facing the issue right now.

## To Reproduce
vgg16 = torchvision.models.vgg16(pretrained=True)

## Expected behavior
Pre-trained models should be downloaded without certificate failures

## Environment
PyTorch version: 1.4.0
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 18.04.3 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.12.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration: GPU 0: Tesla P100-PCIE-16GB
Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.17.5
[pip3] torch==1.4.0
[pip3] torchfile==0.1.0
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.3.1
[pip3] torchvision==0.5.0
[conda] Could not collect
```


cc @ezyang @gchanan @zou3519

**Comment by Archetype90** [comment] 2020-02-13 13:46
Same thing when trying to pip install pytorch:

> pip install torch===1.4.0 torchvision===0.5.0 -f https://download.pytorch.org/whl/torch_stable.html

**Comment by Mxbonn** [comment] 2020-02-13 13:48
I'm having the same issue just now.

**Comment by Aquassaut** [comment] 2020-02-13 14:07
@Mxbonn I don't think it is the same issue. This issue is that the SSL certificate for download.pytorch.org expired today :)

**Comment by xen0f0n** [comment] 2020-02-13 16:08
@Mxbonn @Archetype90 until the certificate gets renewed, you can download the .whl you need from [here](http://download.pytorch.org/whl/torch_stable.html) and install it using pip.

**Comment by optimuspaul** [comment] 2020-02-13 16:11
@xen0f0n that doesn't help us download pertained models. Our entire inference pipeline is dead in the water right now because we can't download the models.

**Comment by albanD** [comment] 2020-02-13 16:18
You can use the same trick of using `http` instead of `https` as a temporary workaround.

**Comment by xen0f0n** [comment] 2020-02-13 16:20
@optimuspaul  Yeah, you're right... Although you could locate the url of the pretrained model and download it, right? 
e.g. https://s3.amazonaws.com/pytorch/models/resnet18-5c106cde.pth 
http://download.pytorch.org/models/alexnet-owt-4df8aa71.pth (with http instead of https as @albanD said)

**Comment by Lissanro** [comment] 2020-02-13 16:24
I encountered the same issue when downloading resnet152 after calling `cnn_learner(data, models.resnet152, metrics=error_rate)`. As a workaround, I downloaded it manually without checking certificate:
```
cd ~/.cache/torch/checkpoints/
wget -c --no-check-certificate https://download.pytorch.org/models/resnet152-b121ed2d.pth
```

**Comment by xen0f0n** [comment] 2020-02-13 16:28
@optimuspaul not sure if this helps... but if you tweak the model_urls  here https://github.com/Cadene/pretrained-models.pytorch/blob/master/pretrainedmodels/models/torchvision_models.py
and replace https://download.pytorch.org/ with https://s3.amazonaws.com/pytorch/ it will download the pretrained models. 
https://download.pytorch.org/models/alexnet-owt-4df8aa71.pth
https://s3.amazonaws.com/pytorch/models/alexnet-owt-4df8aa71.pth)

**Comment by albanD** [comment] 2020-02-13 16:34
Should be fixed now. Can you confirm it works for you?

**Comment by soumith** [comment] 2020-02-13 16:35
The SSL Certificate issue is fixed now. The Cert was expired for ~4 hours, and we root-caused the auto-renewal problem, it wont happen again.

**Closed by soumith** 2020-02-13 16:35 UTC
Labels: high priority

**Comment by Neoanarika** [comment] 2020-05-23 03:19
Hi,  I am having the same issue today on Mac OS X 10.14.6 when I tried to install pre-trained model of VGG.

**Comment by jiangyuang** [comment] 2020-05-29 02:23
I'm having the issue again while trying to download Resnet18

**Comment by stephenllh** [comment] 2020-06-03 14:54
Having the same issue today.

**Comment by mukultater** [comment] 2020-06-03 19:44
Having issues in downloading se_resnext50_32x4d(),
SSL expired.!
![WhatsApp Image 2020-06-04 at 12 35 26 AM](https://user-images.githubusercontent.com/29327107/83681908-c1366600-a600-11ea-873a-d474614179fe.jpeg)
![WhatsApp Image 2020-06-04 at 12 36 12 AM](https://user-images.githubusercontent.com/29327107/83681914-c398c000-a600-11ea-8f16-d5661aa4e620.jpeg)


![WhatsApp Image 2020-06-04 at 12 35 03 AM](https://user-images.githubusercontent.com/29327107/83681893-baa7ee80-a600-11ea-8bb3-acec05d9ff91.jpeg)

**Comment by hot9cups** [comment] 2020-06-08 11:30
I have the issue while trying to download Inception V2
```
from pretrainedmodels.models.inceptionresnetv2 import inceptionresnetv2
model_transfer = inceptionresnetv2(pretrained='imagenet')
```

I ran this on colab
The following was the output:
![image](https://user-images.githubusercontent.com/32614018/84025583-783c3400-a9a9-11ea-8188-34da1fdb4970.png)

But, when I set pretrained = False, the model gets downloaded just fine.
How do I solve this?

**Comment by will-maclean** [comment] 2020-06-12 22:30
Same issue downloading pre-trained vgg

**Comment by hot9cups** [comment] 2020-06-13 05:59
Okay, my problem didn't have to do with PyTorch itself, I was downloading the model from Cadenn, and that has some problems with the certificate.
A workaround to that is mentioned [here](https://github.com/Cadene/pretrained-models.pytorch/issues/193#issuecomment-635730515)
With that, my problem was solved, might help someone else as well.

**Comment by bdthombre** [comment] 2021-01-20 15:12
Same issue persistent while downloading torchvison.models.resnet18(pretrained= True)

**Comment by bellship24** [comment] 2021-01-22 17:37
Same issue !
===
<My code>
model = models.densenet121(pretrained=True)  
===
<error logs>
Traceback (most recent call last):
  File "xxxxxx/model.py", line 35, in <module>
    model = models.densenet121(pretrained=True)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/models/densenet.py", line 236, in densenet121
    return _densenet('densenet121', 32, (6, 12, 24, 16), 64, pretrained, progress,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/models/densenet.py", line 222, in _densenet
    _load_state_dict(model, model_urls[arch], progress)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torchvision/models/densenet.py", line 208, in _load_state_dict
    state_dict = load_state_dict_from_url(model_url, progress=progress)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/hub.py", line 555, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/torch/hub.py", line 425, in download_url_to_file
    u = urlopen(req)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>

**Comment by avico78** [comment] 2021-03-29 17:36
Same issue with installing torch:

  File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 159, in iter
    for x in it:
  File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/utils.py", line 64, in response_chunks
    for chunk in response.raw.stream(
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.8/site-packages/pip/_vendor/urllib3/response.py", line 449, in _error_catcher
    raise SSLError(e)
pip._vendor.urllib3.exceptions.SSLError: [SSL: DECRYPTION_FAILED_OR_BAD_RECORD_MAC] decryption failed or bad record mac (_ssl.c:2624)

**Comment by murthyn** [comment] 2021-10-16 20:25
Same issue with downloading CIFAR10:

```
import torchvision

torchvision.datasets.CIFAR10(root='cifar10' + '/data', train=True, download=True)
```

causes

```
Traceback (most recent call last):
  File "download_cifar10.py", line 3, in <module>
    cifar_trainset = torchvision.datasets.CIFAR10(root='cifar10' + '/data', train=True, download=True)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 65, in __init__
    self.download()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchvision/datasets/cifar.py", line 143, in download
    download_and_extract_archive(self.url, self.root, filename=self.filename, md5=self.tgz_md5)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 413, in download_and_extract_archive
    download_url(url, download_root, filename, md5)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 129, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 77, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/urllib/request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)>
```

**Comment by AbhishekMaruturiVH** [comment] 2021-11-29 19:57
> If anyone's short of time and can't wait till this is fixed, they can use the following hack: Just put these lines at the top of your codebase, and then run the same code again
> 
> ```
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
> 
> Link: https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3#answer-49174340

Thanks @adityasaini70 , This worked. Can you explain what we did here?

**Comment by BenjaminPoole** [comment] 2021-12-06 18:21
@adityasaini70, Thanks this worked for me as well.

**Comment by danton721** [comment] 2022-04-03 03:25
> The SSL Certificate issue is fixed now. The Cert was expired for ~4 hours, and we root-caused the auto-renewal problem, it wont happen again.

it happened, https://download.pytorch.org/ seems to have invalid certificates again

**Comment by knimet** [comment] 2022-04-03 03:29
same issue

**Comment by shengkunc** [comment] 2022-04-03 05:21
hit the same now

**Comment by edward-chalon** [comment] 2022-04-03 05:45
same issue as well

**Comment by RachitBansal** [comment] 2022-04-04 07:06
Yes, facing the same issue while downloading ```resnet50```. 
@adityasaini70's solution still works.

**Comment by lamoboos223** [comment] 2022-10-22 20:26
the issue is back again

**Comment by sanjayashokshetty** [comment] 2023-09-04 06:45
the issue is back again

**Comment by yassineAlouini** [comment] 2023-12-25 20:44
This is the best and fastest workaround for this recurrent issue: 

https://github.com/pytorch/pytorch/issues/33288#issuecomment-1086779194

**Comment by keshiriotinto** [comment] 2024-02-16 05:36
> If anyone's short of time and can't wait till this is fixed, they can use the following hack: Just put these lines at the top of your codebase, and then run the same code again
> 
> ```
> import ssl
> ssl._create_default_https_context = ssl._create_unverified_context
> ```
> 
> Link: https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3#answer-49174340

Still works in 2024

**Comment by CamiloMartinezM** [comment] 2025-02-02 15:54
> > If anyone's short of time and can't wait till this is fixed, they can use the following hack: Just put these lines at the top of your codebase, and then run the same code again
> > ```
> > import ssl
> > ssl._create_default_https_context = ssl._create_unverified_context
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Link: [stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3#answer-49174340](https://stackoverflow.com/questions/35569042/ssl-certificate-verify-failed-with-python3#answer-49174340)
> 
> Still works in 2024

I am getting this error, even with this hack.

```
torch                       2.6.0+cu126
torchaudio                  2.6.0+cu126
torchmetrics                1.6.1
torchvision                 0.21.0+cu126
```
