### ISSUE TITLE
[TorchScript Usability] Problems with `Any` type

### ISSUE THREAD

**Issue by penguinwu** [pytorch/pytorch#52301] opened 2021-02-16 16:33 UTC
## 🐛 Bug

Discovered two problems w/ usage of `Any` type

### Incorrect results when using `Any` type

Another test case: [test-local-annotation3.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-local-annotation3.py)

I tried to use if-then-else statement instead of conditional expressions, and found out that the value produced was wrong:
```
python test-local-annotation3.py 
Eager: 2
TorchScript: 1.0
```

### Conditional expression cannot be evaluated to `Any` type

Test case: [test-local-annotation2.py](https://github.com/penguinwu/hodgepodge/blob/master/TorchScriptStudy/bad-examples/test-local-annotation2.py)

In this test case, the type checker cannot infer a conditional expression into a type of `Any`, resulting in
```
python test-local-annotation2.py 
Traceback (most recent call last):
  File "test-local-annotation2.py", line 7, in <module>
    m = torch.jit.script(f)
  File "/home/pengwu/local/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/jit/_script.py", line 939, in script
    fn = torch._C._jit_script_compile(
RuntimeError: 
if-expression's true branch has type int but false branch has type float:
  File "test-local-annotation2.py", line 4
def f(a: int, b: float, flag: bool):
    value: Any = a if flag else b
                 ~~~~~~~~~~~~~~~~ <--- HERE
    return value
```

Related to #50444 

cc @gmagogsfm

**Comment by eellison** [comment] 2021-02-23 18:14
The first one is a duplicate of https://github.com/pytorch/pytorch/issues/43378 cc @SplitInfinity

**Comment by ansley** [comment] 2021-03-05 21:19
Spent way too long messing with this only to realize that the issue will automatically be fixed when I land Union...yay! (The problem was the call to `unifyTypes` in `convert_to_ssa.cpp::addIfLoadStores`)

**Closed by ansley** 2021-03-05 21:19 UTC
Labels: oncall: jit
