### ISSUE TITLE
c++ index_put_ crashes when autograd is turned on 

### ISSUE THREAD

**Issue by MaxMayya** [pytorch/pytorch#96426] opened 2023-03-09 15:56 UTC
### 🐛 Describe the bug

I'm using the C++ frontend of torch and experiencing a strange behavior using `index_put_`:

```c++
#include <torch/torch.h>
using namespace torch::indexing;

auto R = torch::eye(3);
R.index_put_({1,1}, -1.); // this works
R.set_requires_grad(true);
R.index_put_({1,1}, -1.); // this crashes
```
Error message:
```
Exception has occurred: CPP/c10::Error
Unhandled exception at 0x00007FF9DFF8CD29 in TorchExample.exe: Microsoft C++ exception: c10::Error at memory location 0x0000003C0F54EB20.
```

### Versions

- OS: Windows 10 Pro
- Torch C++ installation: libtorch-win-shared-with-deps-1.13.1+cu117
- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30147 for x64
- Build variant: RelWithDebInfo

cc @ezyang @gchanan @zou3519 @peterjc123 @mszhanyi @skyline75489 @nbcsm @jbschlosser @albanD @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by janeyx99** [comment] 2023-03-10 15:59
cautiously marking as hipri due to crash

**Comment by kshitij12345** [comment] 2023-03-11 15:41
On Linux, you get the appropriate error:
```
terminate called after throwing an instance of 'c10::Error'
  what():  a view of a leaf Variable that requires grad is being used in an in-place operation.
Exception raised from check_inplace at torch/csrc/autograd/VariableTypeUtils.h:53 (most recent call first):
```

**Comment by albanD** [comment] 2023-03-13 14:27
Looks like this is expected behavior here. I guess the default error handler you have on windows does not print the content of the error @MaxMayya ?

**Comment by MaxMayya** [comment] 2023-03-13 16:39
@albanD I'm using VSCode and for some reason it does not show any specific error messages. But could elaborate more on why this is expected to happen? Inplace operations are prohibited when auto-grad is turned on?

**Comment by malfet** [comment] 2023-03-13 16:47
Even on Linux one is not guaranteed that exception message would be printed to stderr, to get a consistent behavior one should always wrap the throwing code  in `try { ... } catch() {}` block.

I propose to close this issue as it does not demonstrate any discrepancy in behaviour between C++ and Python:
```
 % python -c "import torch;R=torch.eye(3,3,requires_grad=False); R[1,1]=-1;R.requires_grad=True;R[1,1]=-1"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.
```

**Closed** 2023-03-13 16:54 UTC
Labels: triage review, module: windows, module: cpp, module: autograd, triaged
