### ISSUE TITLE
pytorch-linux-xenial-py3-clang5-android-ndk-r19c docker build job is flaky

### ISSUE THREAD

**Issue by ailzhang** [pytorch/pytorch#36541] opened 2020-04-14 00:04 UTC
Reran 4 times on https://github.com/pytorch/pytorch/pull/36187/files and finally got android ndk downloaded successfully. 
Problematic line is `curl -Os --retry 3 https://dl.google.com/android/repository/android-ndk-r19c-linux-x86_64.zip`. 
We might want to consider hosting the files ourselves if it happens again in the future. 

cc @ezyang @gchanan @zou3519 @seemethere

**Comment by seemethere** [comment] 2020-07-24 17:20
Also experiencing this as well, this is very annoying to deal with

**Comment by IvanKobzarev** [comment] 2020-08-03 22:10
The problem is addressed in https://github.com/pytorch/pytorch/pull/42393, changes are merged into https://github.com/pytorch/pytorch/pull/40950

**Comment by seemethere** [comment] 2020-09-14 17:07
Closing this, this is now resolved

**Closed by seemethere** 2020-09-14 17:07 UTC
Labels: high priority, mobile, module: android, module: ci, topic: flaky-tests, triage review, triaged
