### ISSUE TITLE
forward() fails: vector subscript out of range

### ISSUE THREAD

**Issue by mnboos** [pytorch/pytorch#14402] opened 2018-11-27 06:50 UTC
## 🐛 Bug

On my Windows 10 machine, the traced model from the tutorial can not be executed. Calling `auto fwd = module->forward({ tensor_image });` crashes the application and a debug assertion from the Microsoft Visual C++ Runtime Library is shown.

![2018-11-27 07_30_36-microsoft visual c runtime library](https://user-images.githubusercontent.com/22575883/49063219-fa756500-f216-11e8-8f6a-c273cb8d97a1.png)

## To Reproduce

1. Save a traced model (I used [this for MNIST](https://github.com/tobiascz/MNIST_Pytorch_python_and_capi/blob/master/pythontracing.py))
2. Try the execute a forward pass with the loaded model

```c++
cv::Mat image;
image = cv::imread(imagePath, CV_LOAD_IMAGE_GRAYSCALE);

std::ifstream in(modelPath, std::ios_base::binary);
if (!in.good()) {
	std::cerr << "Loading failed" << std::endl;
} else {
	std::cout << "Binary file read success" << std::endl;
}

// Deserialize the ScriptModule from a file using torch::jit::load().
std::shared_ptr<torch::jit::script::Module> module = torch::jit::load(in);
std::cout << "Module loaded" << std::endl;
std::vector<int64_t> sizes = { 1, 1, image.rows, image.cols };
at::TensorOptions options(at::ScalarType::Byte);
at::Tensor tensor_image = torch::from_blob(image.data, at::IntList(sizes), options);
tensor_image = tensor_image.toType(at::kFloat);
std::cout << "Executing forward()" << std::endl;
auto fwd = module->forward({ tensor_image });
std::cout << "Forward() done" << std::endl;
at::Tensor result = module->forward({ tensor_image }).toTensor();
std::cout << "Got result" << std::endl;
```

which leads to the console output:
```
C:\src\sample-app\build\Debug>example-app.exe ../../model.pt C:/Temp/MNISTsamples/img_1.jpg
Binary file read success
Module loaded
Executing forward()

C:\src\sample-app\build\Debug>
```

## Expected behavior

`Forward()` should successfully complete and according to the code above, at least an addational line `Forward() done` should be written to the console.

## Environment

```
Collecting environment information...
PyTorch version: 1.0.0a0+60e7d04
Is debug build: No
CUDA used to build PyTorch: None

OS: Microsoft Windows 10 Pro
GCC version: (Rev3, Built by MSYS2 project) 8.2.0
CMake version: version 3.13.0-rc3

Python version: 3.6
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip] Could not collect
[conda] Could not collect
```

Pip version is: `pip 18.1 from c:\users\bmar\appdata\local\programs\python\python36\lib\site-packages\pip (python 3.6)`
Conda version is: `4.5.11`

## Additional context

Seems to be the windows version of #14299.

**Comment by aman-tiwari** [comment] 2018-11-28 23:22
#14299 is actually on Windows too

**Comment by peterjc123** [comment] 2019-01-04 06:37
Sorry for late reply. This problem may be caused by the mismatch of the configuration `Debug` and `Release`. In MSVC, they are not ABI-compatible. So would you please try building that with the Release config?

**Comment by mnboos** [comment] 2019-01-04 07:45
Oh cool, it worked when I built my app with the `Release` config.

Thanks!

**Comment by peterjc123** [comment] 2019-01-04 07:48
Glad it worked. Could you please close this issue now?

**Comment by peterjc123** [comment] 2019-01-04 07:50
CC @goldsborough Should we add this notice to the document? If you don't have to time to do it, please feel free to tell me where to add it.

**Comment by aman-tiwari** [comment] 2019-01-04 08:05
Sorry for the late reply. Just got a chance to try it again in the Release config and it worked!

**Closed** 2019-01-04 08:16 UTC
Labels: jit, windows
