### ISSUE TITLE
[Dynamo] Unable to Trace AdamW Optimizer when there is LR Scheduler

### ISSUE THREAD

**Issue by OrenLeung** [pytorch/pytorch#107076] opened 2023-08-12 02:59 UTC
## What is Broken
- the lr in AdamW Optimizer is a float so causes a recompile everytime LRScheduler changes the lr

## Suggested fix
- fix the graph break in `_multi_tensor AdamW Optimizer` and/or normal `AdamW Optimizer`
- change that LRScheduler base class outputs Scalar Tensor and AdamW Optimizer accepts Scalar Tensor for lr
   - this is similar to what @janeyx99 is doing in Fused AdamW Optimizer https://github.com/pytorch/pytorch/pull/106916

## Why this should be fixed
- a lot of the community uses AdamW Optimizer in combination with LR Scheduler and wants to torch compile it.

## Reprod Script
```python
import torch
import torch.nn as nn
import torch.optim as optim
import torch._dynamo.utils
import torch._dynamo
import logging
torch._dynamo.config.log_level = logging.INFO

class SimpleModel(nn.Module):
    def __init__(self, input_size, hidden_size,  num_classes):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.fc2 = nn.Linear(hidden_size, num_classes)


    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    

input_size = 784
hidden_size = 500
num_classes = 10

model = SimpleModel(input_size, hidden_size, num_classes)


criterion = nn.CrossEntropyLoss()
optimizer = torch.optim._multi_tensor.AdamW(model.parameters(), lr=0.001)
scheduler = optim.lr_scheduler.StepLR(optimizer,step_size=1, gamma=0.1)

inputs = torch.randn(64, 784)

labels = torch.randint(0,10,(64,))

num_epochs = 5
def opt_scheduler_step(optimizer):
    optimizer.step()

    return optimizer

opt_scheduler_step = torch.compile(opt_scheduler_step, backend="eager", fullgraph=False)

for epoch in range(num_epochs):
    outputs = model(inputs)
    loss = criterion(outputs, labels)

    optimizer.zero_grad()

    loss.backward()
    optimizer = opt_scheduler_step(optimizer)
    scheduler.step()

    print(loss.item())
```
## Logs
```
[2023-08-11 22:52:19,789] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing opt_scheduler_step
[2023-08-11 22:52:19,857] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing wrapper
[2023-08-11 22:52:19,858] torch._dynamo.variables.torch: [WARNING] Profiler will be ignored
[2023-08-11 22:52:19,869] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing _use_grad
[2023-08-11 22:52:19,874] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing step
[2023-08-11 22:52:19,878] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing <graph break in step>
[2023-08-11 22:52:19,898] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing adamw
[2023-08-11 22:52:19,910] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing <graph break in adamw>
[2023-08-11 22:52:19,912] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing <graph break in wrapper>
2.3640196323394775
[2023-08-11 22:52:19,927] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing adamw
1.709822654724121
[2023-08-11 22:52:19,949] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing adamw
1.6508420705795288
[2023-08-11 22:52:19,972] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing adamw
1.6449681520462036
[2023-08-11 22:52:19,993] torch._dynamo.symbolic_convert: [INFO] Step 1: torchdynamo start tracing adamw
1.6443781852722168
```

cc: @janeyx99 @cchan @ezhang887 

### Versions

python==3.8.13
torch==2.0.1

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @bdhirsh @anijain2305 @chauhang @mlazos @janeyx99 @vincentqb @jbschlosser @albanD @crcrpar @wconstab

**Comment by msaroufim** [comment] 2023-08-17 17:54
Just so I don't keep referring back to the 2 issues, this seems related as well https://github.com/pytorch/pytorch/issues/107188#issuecomment-1680550137

**Comment by janeyx99** [comment] 2023-09-22 18:01
cc @mlazos who was intending on looking into this more following our offline discussions (after he returns from PTO in a few weeks)

**Comment by voznesenskym** [comment] 2023-11-13 23:27
@mlazos are you still working on this?

**Comment by mlazos** [comment] 2023-11-13 23:41
Yes, actually working on it right now

**Comment by netw0rkf10w** [comment] 2024-02-21 10:52
Is this issue still active please? Using a learning rate schedule is a standard practice so I hope this will be fixed soon.

**Comment by janeyx99** [comment] 2024-02-21 12:56
@mlazos and I just talked about this yesterday offline—compiling with LRSchedulers should work with a Tensor lr (vs a float) but we haven’t closed this issue yet as we need to add tests and verify. Please don’t hesitate to try and it and let us know if you run into any issues!

**Comment by netw0rkf10w** [comment] 2024-02-21 13:46
> @mlazos and I just talked about this yesterday offline—compiling with LRSchedulers should work with a Tensor lr (vs a float) but we haven’t closed this issue yet as we need to add tests and verify. Please don’t hesitate to try and it and let us know if you run into any issues!

Thanks @janeyx99. I guess we have to set either `foreach=True; capturable=True` or `foreach=False; capturable=False`? Otherwise I got `ValueError: lr as a Tensor is not supported for capturable=False and foreach=True`. Which of the two would you recommend please?

**Comment by janeyx99** [comment] 2024-02-21 13:56
@netw0rkf10w try capturable=True! torch.compile will take that path under the hood anyway so if you plan on torch.compile’ing, that would be equivalent.

**Comment by netw0rkf10w** [comment] 2024-02-21 13:58
Hmm, setting `foreach=False; capturable=False` leads to NaN loss:

```bash
Epoch: [0]  [    0/20018]  eta: 12 days, 16:29:47  lr: 0.000000  loss: 6.9078 (6.9078)  time: 54.7601  data: 2.5447  max mem: 6330
Loss is nan, stopping training
[2024-02-21 14:49:42,509] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 603723) of binary: /opt/cray/pe/python/3.10.10/bin/python
Traceback (most recent call last):
```

whereas `foreach=True; capturable=True` leads to recompilation for each learning rate: 

```bash
Epoch: [0]  [    0/20018]  eta: 6 days, 20:42:58  lr: 0.000000  loss: 6.9078 (6.9078)  time: 29.6223  data: 2.2149  max mem: 6330
[rank0]:[2024-02-21 14:46:01,520] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[rank0]:[2024-02-21 14:46:01,520] torch._dynamo.convert_frame: [WARNING]    function: 'step' (/lus/home/CT1/c1614924/hdkle/.local/lib/python3.10/site-packages/torch/optim/adamw.py:151)
[rank0]:[2024-02-21 14:46:01,520] torch._dynamo.convert_frame: [WARNING]    last reason: L['self'].param_groups[0]['lr'] == 0.0                        # has_complex = self._init_group(  # optim/adamw.py:176 in step
[rank0]:[2024-02-21 14:46:01,520] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank0]:[2024-02-21 14:46:01,520] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
[rank0]:[2024-02-21 14:46:12,732] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[rank0]:[2024-02-21 14:46:12,732] torch._dynamo.convert_frame: [WARNING]    function: 'adamw' (/lus/home/CT1/c1614924/hdkle/.local/lib/python3.10/site-packages/torch/optim/adamw.py:279)
[rank0]:[2024-02-21 14:46:12,732] torch._dynamo.convert_frame: [WARNING]    last reason: L['lr'] == 5.910210236417168e-10                              # if isinstance(lr, Tensor) and not capturable:  # optim/adamw.py:503 in _multi_tensor_adamw
[rank0]:[2024-02-21 14:46:12,732] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank0]:[2024-02-21 14:46:12,732] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
[rank0]:[2024-02-21 14:46:26,740] torch._dynamo.convert_frame: [WARNING] torch._dynamo hit config.cache_size_limit (8)
[rank0]:[2024-02-21 14:46:26,740] torch._dynamo.convert_frame: [WARNING]    function: '_multi_tensor_adamw' (/lus/home/CT1/c1614924/hdkle/.local/lib/python3.10/site-packages/torch/optim/adamw.py:479)
[rank0]:[2024-02-21 14:46:26,740] torch._dynamo.convert_frame: [WARNING]    last reason: L['lr'] == 3.310926220464083e-09                              # if isinstance(lr, Tensor) and not capturable:  # optim/adamw.py:503 in _multi_tensor_adamw
[rank0]:[2024-02-21 14:46:26,740] torch._dynamo.convert_frame: [WARNING] To log all recompilation reasons, use TORCH_LOGS="recompiles".
[rank0]:[2024-02-21 14:46:26,740] torch._dynamo.convert_frame: [WARNING] To diagnose recompilation issues, see https://pytorch.org/docs/master/compile/troubleshooting.html.
Epoch: [0]  [   50/20018]  eta: 1 day, 2:50:05  lr: 0.000001  loss: 6.9078 (6.9078)  time: 0.1732  data: 0.0001  max mem: 7001
Epoch: [0]  [  100/20018]  eta: 13:59:30  lr: 0.000002  loss: 6.9077 (6.9078)  time: 0.1739  data: 0.0001  max mem: 7001
Epoch: [0]  [  150/20018]  eta: 9:39:09  lr: 0.000003  loss: 6.9077 (6.9078)  time: 0.1732  data: 0.0001  max mem: 7001
Epoch: [0]  [  200/20018]  eta: 7:28:15  lr: 0.000004  loss: 6.9077 (6.9077)  time: 0.1737  data: 0.0001  max mem: 7001
```

I'm using PyTorch 2.2.0 (CUDA 11.8).

**Comment by janeyx99** [comment] 2024-02-21 14:05
@netw0rkf10w hm this is bad, thank u for trying—to confirm, were both with torch.compile()? 

Or in other words, if you ran the foreach=False, capturable=False in eager, does it also lead to NaN loss?

**Comment by netw0rkf10w** [comment] 2024-02-21 14:22
> @netw0rkf10w hm this is bad, thank u for trying—to confirm, were both with torch.compile()?
> 
> Or in other words, if you ran the foreach=False, capturable=False in eager, does it also lead to NaN loss?

Yes I confirm that both were with torch.compile. In addition, when `foreach=False, capturable=False, fused=False, compiled=False`, training is good!


> @netw0rkf10w try capturable=True! torch.compile will take that path under the hood anyway so if you plan on torch.compile’ing, that would be equivalent.

I've also tried `foreach=False; capturable=True` and also obtained NaN loss, so it seems the NaN was caused by `capturable=True`.

Below is how I compile the optimizer (defining a new AdamW class with an additional `compiled` argument):

```python
class AdamW(torch.optim.AdamW):
    def __init__(
        self,
        params: ParamsT,
        lr: Union[float, Tensor] = 1e-3,
        betas: Tuple[float, float] = (0.9, 0.999),
        eps: float = 1e-8,
        weight_decay: float = 1e-2,
        amsgrad: bool = False,
        *,
        maximize: bool = False,
        foreach: Optional[bool] = None,
        capturable: bool = False,
        differentiable: bool = False,
        fused: Optional[bool] = None,
        compiled: Optional[bool] = None,
    ):
        if compiled:
            # foreach = False; capturable = False
            # foreach = True; capturable = True
            foreach = False; capturable = True
            lr = torch.tensor(lr, requires_grad=False)
            
        super().__init__(params, lr=lr, betas=betas, eps=eps, weight_decay=weight_decay, 
                         amsgrad=amsgrad, maximize=maximize, foreach=foreach, capturable=capturable,
                         differentiable=differentiable, fused=fused)
        if compiled:
            print("Compiling AdamW")
            @torch.compile(fullgraph=False)
            def fn(closure=None):
                return self.step_(closure)

            self.step = fn
        else:
            self.step = self.step_

    def step_(self, closure=None):
        return super().step(closure)
```

**Comment by mlazos** [comment] 2024-02-21 19:23
hi @netw0rkf10w, can you attach your full script so I can run to repro the NaN? It looks like the LR is still not a tensor for some reason in the recompile logs.

**Comment by netw0rkf10w** [comment] 2024-02-21 21:05
Hi @mlazos. To reproduce the error, please do the following:

```bash
git clone https://github.com/netw0rkf10w/mae.git
cd mae 
pip install timm==0.5.4

IMAGENET_DIR=<path-to-your-ImageNet-directory>
torchrun main_finetune.py \
    --accum_iter 4 \
    --batch_size 32 \
    --model vit_base_patch16 \
    --epochs 100 \
    --blr 5e-4 --layer_decay 0.65 \
    --weight_decay 0.05 --drop_path 0.1 --mixup 0.8 --cutmix 1.0 --reprob 0.25 \
    --dist_eval --data_path ${IMAGENET_DIR} --opt_compiled
```

You should obtained NaN loss error. Removing `--opt_compiled` from the above command, training should run successfully.

**Comment by mlazos** [comment] 2024-04-10 19:12
Handling this in https://github.com/pytorch/pytorch/pull/123753

I can investigate the NaN later this week

**Comment by netw0rkf10w** [comment] 2024-04-10 19:59
> Handling this in #123753
> 
> I can investigate the NaN later this week

Great progress! Thanks a lot!

**Comment by mlazos** [comment] 2024-05-21 18:52
@netw0rkf10w this should be fixed now, are you still hitting any issue?

**Comment by mlazos** [comment] 2024-06-06 00:01
I am closing since this is resolved by https://github.com/pytorch/pytorch/pull/125653

**Closed by mlazos** 2024-06-06 00:01 UTC
Labels: high priority, triaged, oncall: pt2, module: pt2 optimizer
