### ISSUE TITLE
Support for Exporting 'aten::fft_rfft' to ONNX

### ISSUE THREAD

**Issue by HaniBuOmer** [pytorch/pytorch#112382] opened 2023-10-30 11:21 UTC
### 🚀 The feature, motivation and pitch

I want to export a torch model to ONNX. My model uses torch.fft.rfft and torch.fft.rfftfreq. However, I got the following erroe:

"UnsupportedOperatorError: Exporting the operator 'aten::fft_rfft' to ONNX opset version 14 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub: https://github.com/pytorch/pytorch/issues."

I tried the latest opset version 17, but this operation is still not supportd.

**Comment by justinchuby** [comment] 2023-11-01 19:57
FFT operators will be supported by the `torch.onnx.dynamo_export` exporter. Duplicate of https://github.com/pytorch/pytorch/issues/107588

**Closed by justinchuby** 2023-11-01 19:57 UTC
Labels: module: onnx, triaged
