### ISSUE TITLE
Gradient computation on modified tensor by in-place operator

### ISSUE THREAD

**Issue by speedcell4** [pytorch/pytorch#74806] opened 2022-03-27 04:18 UTC
### 🐛 Describe the bug

Yes, I know I can simply `x + y + z`, but the following example is just a simplified script from a complex requirement.

I create an empty tensor without requiring gradients, copy the input to the corresponding positions, and then start to reduce them by putting the intermediate results on the next positions, e.g.,

```
x -> tensor[0]
y -> tensor[1]
z -> tensor[3]
tensor[0] + tensor[1] -> tensor[2]
tensor[2] + tensor[3] -> tensor[4]
```

Finally, the `tensor[4]` is returned as the final result. I found the following code works well if the reduction operator is `torch.add`, 

```python
import torch
from torch import Tensor


def reduce(x: Tensor, y: Tensor, z: Tensor, op) -> Tensor:
    tensor = torch.zeros((5,), dtype=torch.float32, requires_grad=False)
    tensor[0] = x
    tensor[1] = y
    tensor[3] = z

    tensor[2] = op(tensor[0], tensor[1])
    tensor[4] = op(tensor[2], tensor[3])
    return tensor[4]


with torch.autograd.set_detect_anomaly(True):
    inputs = [
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
    ]

    out = reduce(*inputs, op=torch.add)
    grad = torch.autograd.grad(
        out, inputs, torch.randn_like(out),
    )
    print(f'grad => {grad}')
    # grad => (tensor([1.2525]), tensor([1.2525]), tensor([1.2525]))
```

but switching `op` to any of `torch.logaddexp`, `torch.mul`, or `torch.mul`, it yields an error on the gradient computation step,

```python
out = reduce(*inputs, op=torch.logaddexp)
out = reduce(*inputs, op=torch.max)
out = reduce(*inputs, op=torch.mul)
```

The error information is here,

```
python3.8/site-packages/torch/autograd/__init__.py:275: UserWarning: Error detected in MulBackward0. Traceback of forward call that caused the error:
  File "tensor.py", line 28, in <module>
    out = reduce(*inputs, op=torch.mul)
  File "tensor.py", line 17, in reduce
    tensor[4] = op(tensor[2], tensor[3])
 (Triggered internally at  ../torch/csrc/autograd/python_anomaly_mode.cpp:104.)
  return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
Traceback (most recent call last):
  File "tensor.py", line 29, in <module>
    grad = torch.autograd.grad(
  File "python3.8/site-packages/torch/autograd/__init__.py", line 275, in grad
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor []], which is output 0 of AsStridedBackward0, is at version 5; expected version 4 instead. Hint: the backtrace further above shows the operation that failed to compute its gradient. The variable in question was changed in there or anywhere later. Good luck!
```

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: CentOS Linux release 7.9.2009 (Core) (x86_64)
GCC version: (GCC) 8.2.0
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.8.5 (default, Sep  4 2020, 07:30:14)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.49.1.el7.x86_64-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

Nvidia driver version: 460.73.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] functorch==0.1.0
[pip3] numpy==1.22.2
[pip3] pytorch-crf==0.7.2
[pip3] torch==1.11.0
[pip3] torch-batch-svd==1.0.0
[pip3] torch-scatter==2.0.9
[pip3] torchaudio==0.9.0
[pip3] torchdevice==0.1.0
[pip3] torchglyph==0.3.2
[pip3] torchlatent==0.4.2
[pip3] torchrua==0.4.0
[pip3] torchvision==0.10.0
[conda] functorch                 0.1.0                    pypi_0    pypi
[conda] numpy                     1.22.2                   pypi_0    pypi
[conda] pytorch-crf               0.7.2                    pypi_0    pypi
[conda] torch                     1.11.0                   pypi_0    pypi
[conda] torch-batch-svd           1.0.0                    pypi_0    pypi
[conda] torch-scatter             2.0.9                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchdevice               0.1.0                    pypi_0    pypi
[conda] torchglyph                0.3.2                    pypi_0    pypi
[conda] torchlatent               0.4.2                    pypi_0    pypi
[conda] torchrua                  0.4.0                    pypi_0    pypi
[conda] torchvision               0.10.0                   pypi_0    pypi
```

cc @ezyang @albanD @zou3519 @gqchen @pearu @nikitaved @soulitzer @Lezcano @Varal7

**Comment by Lezcano** [comment] 2022-03-28 22:23
Note that with `torch.add`, the backward pass does not need to look at the values of the input, as the jacobian of the transformation does not depend on the values of the inputs. This is a property of all linear functions, `add` being one of them.

The other functions that you mention do depend on the value of the input, and when the backward is triggered, it checks whether the input has been modified in place and boom, it throws this error.

**Comment by Lezcano** [comment] 2022-03-28 22:24
If you want to do things like this, you might want to perform the operations separately on different tensors and then either [stack](https://pytorch.org/docs/stable/generated/torch.stack.html?highlight=stack#torch.stack) them or [concatenate](https://pytorch.org/docs/stable/generated/torch.cat.html) them.

**Comment by speedcell4** [comment] 2022-03-29 00:08
Yes,  it is true that `torch.mul` depends on the value of the inputs, as you mentioned it checks whether the inputs have been modified in place. But in my script, I did not modify the inputs, right?

The shape of `tensor` is just `(5,)`, the `[0]`, `[1]`, and `[3]` elements are assigned with `x`, `y`, and `z`, respectively. `[2]` goes for the intermediate result and `[4]` is the final value. Each position is assigned a value once and only once, so, logically, I did not change the computation graph, if you treat each element separately instead of just a `tensor`.

Here is an example to show that PyTorch is capable of treating each element separately by just replacing from slicing to indexing as follows. `tensor[torch.tensor([2])]` leads to careful computation graph tracking while `tensor[2]` does not. In this example, `torch.mul` also works.

```python
import torch
from torch import Tensor


def reduce(x: Tensor, y: Tensor, z: Tensor, op) -> Tensor:
    tensor = torch.zeros((5,), dtype=torch.float32, requires_grad=False)
    tensor[torch.tensor([0])] = x
    tensor[torch.tensor([1])] = y
    tensor[torch.tensor([3])] = z

    tensor[torch.tensor([2])] = op(tensor[torch.tensor([0])], tensor[torch.tensor([1])])
    tensor[torch.tensor([4])] = op(tensor[torch.tensor([2])], tensor[torch.tensor([3])])
    return tensor[torch.tensor([4])]


with torch.autograd.set_detect_anomaly(True):
    inputs = [
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
        torch.randn((1,), requires_grad=True),
    ]

    out = reduce(*inputs, op=torch.mul)
    grad = torch.autograd.grad(
        out, inputs, torch.randn_like(out),
    )
    print(f'grad => {grad}')
    # grad => (tensor([2.1379]), tensor([1.0593]), tensor([0.9451]))
```

So is it possible to apply the same mechanism on slicing? I suppose this is relevant to the `.version` of each tensor.

**Comment by speedcell4** [comment] 2022-03-29 00:11
But the demerit of using indexing is that `tensor[torch.tensor([0,2,5])]` does copy the element at position 0, 2, and 5. This wastes time and memory, and I want to avoid copying as much as possible.

Yes, I have also considered using `torch.cat` and `torch.stack`, but for the same reason of avoiding copy, I don't prefer them.

**Comment by Lezcano** [comment] 2022-03-29 00:19
Alas, autograd requires copying things and saving things for the backward for the reasons described above. Note that the example where you index with tensors is called "Advanced indexing" and it does copy the tensors as opposed to when you index with scalars, as you mentioned. You can read more about it [here](https://dev-discuss.pytorch.org/t/how-does-advanced-indexing-work-when-i-combine-a-tensor-and-a-single-index/558/3) for example.

In a neural network, most intermediate results are saved for the backward pass, but there's not much that can be done about it, when you think about how the chain rule works (i.e. how the jacobian matrix `J(x)` is a function of the point it is computed at).

Closing as this is expected behaviour.

**Comment by ezyang** [comment] 2022-03-29 01:13
The problem here is that version counter tracking is not fine grained enough to detect that the mutated segments don't overlap, and PyTorch is conservatively assuming that something bad happened and that is what is tripping you up.

The usual workaround for bypassing version counter tracking is to do an indirect modification `x.data.add_(...)` which won't update the version counter on X, but this will also prevent gradients from being tracked, which is no good because you do want to backprop through these modifications.

IIRC, a long time ago @albanD had some crazy proposal for making VC in these disjoint cases more accurate, but I'm pretty sure we never implemented it.

Another way that is sure to work is if you create separate storages for each view slice and then do inplace modifications on tensors for disjoint storages; this will ensure that their VC's are disconnected but they can be still related in autograd. But we do not make this easy to do from the Python frontend.

**Comment by speedcell4** [comment] 2022-03-29 01:23
@ezyang Yes, you got my point about the version counter tracking.

> create separate storages for each view slice and then do inplace modifications on tensors for disjoint storages

This sounds like work. Thank you.

**Comment by speedcell4** [comment] 2022-03-29 01:24
So, is there any plan to implement the fine-grained version counter tracking?

**Comment by albanD** [comment] 2022-03-29 14:15
> So, is there any plan to implement the fine-grained version counter tracking?

There aren't any plans right now no. The main reason is that we don't have a working design that has low memory footprint, works well in multithreaded environment and is fast.

Could you clarify why you need all of these smaller Tensors to be part of a single big Tensor?

**Comment by speedcell4** [comment] 2022-03-30 02:13
> The main reason is that we don't have a working design that has low memory footprint, works well in multithreaded environment and is fast

Isn't the version counter tracking of advanced indexing already fine-grained enough? I guess applying the same mechanism to slicing will be just fine?

> Could you clarify why you need all of these smaller Tensors to be part of a single big Tensor?

Basically, it is for building a reduction algorithm, e.g., a tree-based reduction.

**Comment by albanD** [comment] 2022-04-08 20:54
> Basically, it is for building a reduction algorithm, e.g., [a tree-based reduction](https://developer.download.nvidia.com/assets/cuda/files/reduction.pdf).

So you should actually be able to have the main object be a list of Tensors. Like the test above could do `tensor = [None]*5` and will work just fine.

> Isn't the version counter tracking of advanced indexing already fine-grained enough?

It is not, it is just a side effect of advanced indexing of cloning. You could do ` tensor[2] = op(tensor[0].clone(), tensor[1].clone())` in the first example to get the same behavior

**Closed** 2022-04-09 11:46 UTC
Labels: module: autograd, triaged
