### ISSUE TITLE
torch.nn.functional.linear producing random results on pascal

### ISSUE THREAD

**Issue by duanyutong** [pytorch/pytorch#58754] opened 2021-05-21 14:52 UTC
## 🐛 Bug

Torch functional evaluation seems to have broken backwards compatibility with Pascal. Tested on Turing and no such problem.

## To Reproduce

1. on pascal (e.g. Titan X) load attached `x.pt` file onto CUDA: [x.txt](https://github.com/pytorch/pytorch/files/6523313/x.txt)
2. calculate `torch.nn.functional.linear(x, x)` several times; you would get different results
3. calculate `torch.nn.functional.linear(x.cpu(), x.cpu())` to compare which is always correct

## Expected behavior

torch.nn.functional always produces correct results on CUDA consistent with CPU for all archs.

## Environment

```
Collecting environment information...
PyTorch version: 1.8.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 11.1.0-1ubuntu1~20.04) 11.1.0
Clang version: 13.0.0-++20210507052630+70cbc6dbef70-1~exp1~20210507153420.403
CMake version: version 3.20.2
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-72-generic-x86_64-with-glibc2.29
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: 
GPU 0: TITAN X (Pascal)
GPU 1: TITAN X (Pascal)

Nvidia driver version: 460.73.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.2
[pip3] torch==1.8.1+cu111
[pip3] torchfile==0.1.0
[pip3] torchvision==0.9.1+cu111
[conda] Could not collect
```

## Additional context

![image](https://user-images.githubusercontent.com/865317/119156072-dda1fd00-ba21-11eb-83d5-50886c30a366.png)

cc @ngimel @albanD @mruberry @jbschlosser

**Comment by ngimel** [comment] 2021-05-22 05:48
Duplicate of #56747

**Closed by ngimel** 2021-05-22 05:48 UTC
Labels: module: cuda, module: nn, triaged
