### ISSUE TITLE
Multiple CUDA contexts created on first GPU when using pin_memory=True, multiprocessing and torch.cat()

### ISSUE THREAD

**Issue by maaft** [pytorch/pytorch#32424] opened 2020-01-20 16:37 UTC
## 🐛 Bug

When **spawning multiple processes** (e.g. for training models on different GPUs for hyperparameter search) that have their own dataloader with **pin_memory = True** and where the model uses **torch.cat()**, multiple CUDA contexts are created on the first GPU.

## To Reproduce

Execute following code sample and play with `use_cat` and `pin_memory` variables. If you set one of these to `False`, no additional context is created on GPU 0.

```python
import torch
import torch.nn as nn
import torch.multiprocessing as mp
from torch.utils.data import DataLoader, Dataset

ctx = mp.get_context("spawn")

class RandomSet(Dataset):

    def __getitem__(self, item):
        return torch.randn(256,256,256)

    def __len__(self):
        return 1000


class CatModel(nn.Module):
    def __init__(self, use_cat=True):
        super(CatModel, self).__init__()

        self.use_cat = use_cat

        if use_cat:
            self.conv = nn.Conv2d(512, 512, 3)
        else:
            self.conv = nn.Conv2d(256, 512, 3)

    def forward(self, x):

        if self.use_cat:
            x = torch.cat([x, x], dim=1)

        return self.conv(x)


# change either one to False: No additional CUDA context created
use_cat = True
pin_memory = True

class Trainer(ctx.Process):
    def __init__(self, device):
        super(Trainer, self).__init__()

        self.device = device

        self.dataset = RandomSet()
        self.dataloder = DataLoader(
            self.dataset,
            pin_memory=pin_memory,
            batch_size=8,
            num_workers=8
        )

    def run(self):
        self.model = CatModel(use_cat).to(self.device)

        # loop
        for x in self.dataloder:
            x = x.to(self.device)
            y = self.model(x)


if __name__ == "__main__":

    trainer1 = Trainer(0)
    trainer2 = Trainer(1)

    trainer1.start()
    trainer2.start()

    trainer1.join()
    trainer2.join()
```

## Expected behavior

No additional CUDA context should be created when using cat in combination with pin_memory on a multi-processing system.

## Environment

PyTorch version: 1.3.1
Is debug build: No
CUDA used to build PyTorch: 10.1.243

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 440.33.01
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5

Versions of relevant libraries:
[pip3] numpy==1.18.1
[pip3] torch==1.2.0
[pip3] torchvision==0.4.0
[conda] blas                      1.0                         mkl  
[conda] mkl                       2019.4                      243  
[conda] mkl-service               2.0.2            py37h7b6447c_0  
[conda] mkl_fft                   1.0.12           py37ha843d7b_0  
[conda] mkl_random                1.0.2            py37hd81dba3_0  
[conda] pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
[conda] torchvision               0.4.2                py37_cu101    pytorch

## Additional context

I also tried with latest pytorch 1.4 -> still happening.

**Comment by SsnL** [comment] 2020-01-20 17:32
memory pinning initializes cuda, which is unavoidable.

**Comment by maaft** [comment] 2020-01-21 07:49
Can you please re-read my issue?
How does memory pinning relate to torch.cat?

**Comment by matthiasreisser** [comment] 2020-01-21 07:59
Curious that I found this issue. I observe what I assume is the same behaviour. Upon executing torch.cat, additional memory is allocated on GPU0 although three of my four processes compute on GPU1,GPU2 and GPU3 respectively. 

What is going on?
Thx

**Comment by marcown** [comment] 2020-01-21 09:11
I encounter the same problem executing the code above.

@SsnL: 
the problem is that with
```
use_cat = True
pin_memory = True
```

an additional CUDA context gets initialized/created on GPU0.

**Comment by matthiasreisser** [comment] 2020-01-21 09:12
Related Issue: https://github.com/pytorch/pytorch/issues/21081

**Comment by SsnL** [comment] 2020-01-21 14:26
Sorry I misinterpreted the issue. You are right. Reopening.

**Comment by maaft** [comment] 2020-01-26 08:23
Anything I can do in the meantime?

**Comment by SsnL** [comment] 2020-06-12 19:51
should be fixed now by https://github.com/pytorch/pytorch/pull/22229

**Closed by SsnL** 2020-06-12 19:51 UTC
Labels: module: multiprocessing, triaged

**Comment by msbaines** [comment] 2020-08-31 19:34
The sample app still generates a GPU0 context for the process running on GPU1. I was able to avoid the extra context by adding `torch.cuda.set_device(self.device)` at the very beginning of Trainer.run.
