### ISSUE TITLE
[DDP + Dynamo] Traceable DDP hooks

### ISSUE THREAD

**Issue by sssiva81** [pytorch/pytorch#109697] opened 2023-09-20 07:15 UTC
### 🚀 The feature, motivation and pitch

https://github.com/pytorch/pytorch/pull/106738 has support to trace FSDP.  Is there any plan to add similar support for traceable DDP along with using functional collectives?

With support for CompiledAutoGrad + traceable DDP hook I am expecting the complete graph including the backward graph + (mul + allreduce) for all buckets which are present in the DDP hooks to be available at the compiler backend.  This helps the custom compiler backend to schedule the Allreduce calls for better compute + communication overlap.

def compiler_fn(gm):
    return torch.compile(gm, backend="inductor", fullgraph=True)

ddp_m = DDP(m, gradient_as_bucket_view=True, static_graph=True)
ddp_m = torch.compile(ddp_m, backend="inductor")
with compiled_autograd.enable(compiler_fn):
    loss = ddp_m(inp, target)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()

The current DDP hooks are not traceable where the first place dynamo tracing breaks is with this particular stack trace during pre_forward hooks.

> inputs, kwargs = self._pre_forward(*inputs, **kwargs)
> self._lazy_init()
> self._lazy_init_ran = True.

The graph compilation also fails with this particular error:
> AttributeError: type object '_DDPSink' has no attribute '_compiled_autograd_key'

Other than this there are multiple parts of the DDP backward hook implementation which are not traceable.  The expectation is with traceable DDP hook + CompiledAutoGrad by registering a comm hook with functional collectives we can get a combined graph along with the collective calls at the compiler backend.

@wconstab 

cc @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @H-Huang @kwen2501 @awgu @penguinwu @ezyang @msaroufim @wconstab @bdhirsh @anijain2305

**Comment by wconstab** [comment] 2023-09-20 16:56
yep, we're working on a compiled DDP.  @fegin is the POC.

It won't work _quite_ like you suggest: the DDP reducer (bucketer) will be totally skipped and we'll just trace one all-reduce per paramter.  Then inside the compiler we'll do bucketing.  But you can get one graph and have the functional collectives inside it.

**Comment by sssiva81** [comment] 2023-09-21 05:17
Thanks @wconstab. 
@fegin Can we expect something similar to
> param.register_hook(allreduce_hook)
for all parameters and the allreduce_hook containing functional allreduce along with mul or div.
Is it possible to share the design for the approach that will be taken?
Will the compiler bucketing implementation available only for inductor backend or will be available to be used by any custom compiler backend?
Is there any restriction on the usage of in place ops in the hooks?  With compiledAutoGrad, is functionalization expected to happen on the ops in the hooks?
Will the compiler backend be expected to support non-functionalized in-place variant of the op also?

**Comment by wconstab** [comment] 2024-02-07 04:34
Closing this issue as duplicate of #109774

**Closed by wconstab** 2024-02-07 04:34 UTC
Labels: oncall: distributed, triaged, oncall: pt2
