### ISSUE TITLE
Building PyTorch on Windows 11, CPU build, throws an error during "python setup.py develop"

### ISSUE THREAD

**Issue by OscarSavolainen** [pytorch/pytorch#118496] opened 2024-01-28 19:11 UTC
### 🐛 Describe the bug

I am having issues building PyTorch on my local Windows 11 laptop computer.

I cloned and checked out PyTorch. I then followed the [Install Dependencies](https://github.com/pytorch/pytorch/wiki/Install-Dependencies) - Windows track:
```
conda install cmake ninja
# Run this command from the PyTorch directory after cloning the source code using the “Get the PyTorch Source“ section below
pip install -r requirements.txt
```
Then:
```
conda install mkl mkl-include
```
I did NOT install the distributed package:
```
# Add these packages if torch.distributed is needed.
# Distributed package support on Windows is a prototype feature and is subject to changes.
conda install -c conda-forge libuv=1.39
```
I downloaded [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/), but did no other configuration (e.g. di not add to PATH).

Running
```python setup.py develop```
throws the following error. I have not included the full-traceback because it is exceedingly long. It includes messages such as:
```
C:\Users\oscar\torch-os\pytorch\third_party\fbgemm\include\fbgemm/Fbgemm.h(106): note: see declaration of 'fbgemm::PackMatrix<fbgemm::PackAWithIm2Col<uint8_t,int32_t,1>,uint8_t,int32_t>::PackMatrix'
C:\Users\oscar\torch-os\pytorch\third_party\fbgemm\include\fbgemm/Fbgemm.h(312): warning C4661: 'int fbgemm::PackMatrix<fbgemm::PackAWithIm2Col<uint8_t,int32_t,1>,uint8_t,int32_t>::packedBufferSize(int,int,const fbgemm::BlockingFactors *)': no suitable definition provided for explicit template instantiation request
```

Traceback of final error:
```
C:\Users\oscar\torch-os\pytorch\cmake\..\third_party\googletest\googletest\include\gtest/internal/gtest-internal.h(515): note: see reference to class template instantiation '`anonymous-namespace'::OptionalTest_Empty_Test<T>' being compiled
        with
        [
            T=Type
        ]
C:\Users\oscar\torch-os\pytorch\c10\test\util\optional_test.cpp(63): note: while compiling class template member function 'void `anonymous-namespace'::OptionalTest_Empty_Test<T>::TestBody(void)'
        with
        [
            T=Type
        ]
[6492/7614] Building CXX object caffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\native\mkl\SpectralOps.cpp.obj
FAILED: caffe2/CMakeFiles/torch_cpu.dir/__/aten/src/ATen/native/mkl/SpectralOps.cpp.obj
C:\PROGRA~2\MICROS~2\2022\BUILDT~1\VC\Tools\MSVC\1438~1.331\bin\Hostx64\x64\cl.exe  /nologo /TP -DAT_PER_OPERATOR_HEADERS -DCAFFE2_BUILD_MAIN_LIB -DCPUINFO_SUPPORTED_PLATFORM=1 -DFMT_HEADER_ONLY=1 -DMINIZ_DISABLE_ZIP_READER_CRC32_CHECKS -DNOMINMAX -DONNXIFI_ENABLE_EXT=1 -DONNX_ML=1 -DONNX_NAMESPACE=onnx_torch -DUSE_C10D_GLOO -DUSE_DISTRIBUTED -DUSE_EXTERNAL_MZCRC -DUSE_MIMALLOC -DWIN32_LEAN_AND_MEAN -D_CRT_SECURE_NO_DEPRECATE=1 -D_UCRT_LEGACY_INFINITY -Dtorch_cpu_EXPORTS -IC:\Users\oscar\torch-os\pytorch\third_party\pocketfft -IC:\Users\oscar\torch-os\pytorch\build\aten\src -IC:\Users\oscar\torch-os\pytorch\aten\src -IC:\Users\oscar\torch-os\pytorch\build -IC:\Users\oscar\torch-os\pytorch -IC:\Users\oscar\torch-os\pytorch\cmake\..\third_party\benchmark\include -IC:\Users\oscar\torch-os\pytorch\third_party\onnx -IC:\Users\oscar\torch-os\pytorch\build\third_party\onnx -IC:\Users\oscar\torch-os\pytorch\third_party\foxi -IC:\Users\oscar\torch-os\pytorch\build\third_party\foxi -IC:\Users\oscar\torch-os\pytorch\third_party\mimalloc\include -IC:\Users\oscar\torch-os\pytorch\torch\csrc\api -IC:\Users\oscar\torch-os\pytorch\torch\csrc\api\include -IC:\Users\oscar\torch-os\pytorch\caffe2\aten\src\TH -IC:\Users\oscar\torch-os\pytorch\build\caffe2\aten\src\TH -IC:\Users\oscar\torch-os\pytorch\build\caffe2\aten\src -IC:\Users\oscar\torch-os\pytorch\build\caffe2\..\aten\src -IC:\Users\oscar\torch-os\pytorch\torch\csrc -IC:\Users\oscar\torch-os\pytorch\third_party\miniz-2.1.0 -IC:\Users\oscar\torch-os\pytorch\third_party\kineto\libkineto\include -IC:\Users\oscar\torch-os\pytorch\third_party\kineto\libkineto\src -IC:\Users\oscar\torch-os\pytorch\aten\src\ATen\.. -IC:\Users\oscar\torch-os\pytorch\c10\.. -IC:\Users\oscar\torch-os\pytorch\third_party\pthreadpool\include -IC:\Users\oscar\torch-os\pytorch\third_party\cpuinfo\include -IC:\Users\oscar\torch-os\pytorch\third_party\fbgemm\include -IC:\Users\oscar\torch-os\pytorch\third_party\fbgemm -IC:\Users\oscar\torch-os\pytorch\third_party\fbgemm\third_party\asmjit\src -IC:\Users\oscar\torch-os\pytorch\third_party\ittapi\src\ittnotify -IC:\Users\oscar\torch-os\pytorch\third_party\FP16\include -IC:\Users\oscar\torch-os\pytorch\third_party\fmt\include -IC:\Users\oscar\torch-os\pytorch\build\third_party\ideep\mkl-dnn\include -IC:\Users\oscar\torch-os\pytorch\third_party\ideep\mkl-dnn\src\..\include -IC:\Users\oscar\torch-os\pytorch\third_party\flatbuffers\include -external:IC:\Users\oscar\torch-os\pytorch\build\third_party\gloo -external:IC:\Users\oscar\torch-os\pytorch\cmake\..\third_party\gloo -external:IC:\Users\oscar\torch-os\pytorch\cmake\..\third_party\googletest\googlemock\include -external:IC:\Users\oscar\torch-os\pytorch\cmake\..\third_party\googletest\googletest\include -external:IC:\Users\oscar\torch-os\pytorch\third_party\protobuf\src -external:IC:\Users\oscar\torch-os\pytorch\third_party\XNNPACK\include -external:IC:\Users\oscar\torch-os\pytorch\third_party\ittapi\include -external:IC:\Users\oscar\torch-os\pytorch\cmake\..\third_party\eigen -external:IC:\Users\oscar\torch-os\pytorch\third_party\ideep\mkl-dnn\include\oneapi\dnnl -external:IC:\Users\oscar\torch-os\pytorch\third_party\ideep\include -external:IC:\Users\oscar\torch-os\pytorch\caffe2 -external:W0 /DWIN32 /D_WINDOWS /GR /EHsc /Zc:__cplusplus /bigobj /FS /utf-8 -DUSE_PTHREADPOOL -DNDEBUG -DUSE_KINETO -DLIBKINETO_NOCUPTI -DLIBKINETO_NOROCTRACER -DUSE_FBGEMM -DUSE_XNNPACK -DSYMBOLICATE_MOBILE_DEBUG_HANDLE /wd4624 /wd4068 /wd4067 /wd4267 /wd4661 /wd4717 /wd4244 /wd4804 /wd4273 -DHAVE_AVX2_CPU_DEFINITION /O2 /Ob2 /DNDEBUG /bigobj -DNDEBUG -std:c++17 -MD -DCAFFE2_USE_GLOO /EHsc /bigobj -O2 -DONNX_BUILD_MAIN_LIB -openmp:experimental /showIncludes /Focaffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\native\mkl\SpectralOps.cpp.obj /Fdcaffe2\CMakeFiles\torch_cpu.dir\ /FS -c C:\Users\oscar\torch-os\pytorch\aten\src\ATen\native\mkl\SpectralOps.cpp
C:\Users\oscar\torch-os\pytorch\third_party\pocketfft\pocketfft_hdronly.h(156): error C2039: 'aligned_alloc': is not a member of '`global namespace''
[6505/7614] Building CXX object caffe2\CMakeFiles\torch_cpu.dir\__\aten\src\ATen\native\quantized\qlinear_unpack.cpp.ob
ninja: build stopped: subcommand failed.
```

### Versions

```Collecting environment information...
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Home
GCC version: Could not collect
Clang version: Could not collect
CMake version: version 3.28.1
Libc version: N/A

Python version: 3.12.1 | packaged by conda-forge | (main, Dec 23 2023, 07:53:56) [MSC v.1937 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22621-SP0
Is CUDA available: N/A
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: N/A

CPU:
Architecture=9
CurrentClockSpeed=1100
DeviceID=CPU0
Family=198
L2CacheSize=6656
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=1100
Name=12th Gen Intel(R) Core(TM) i7-1250U
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] optree==0.10.0
[conda] mkl                       2024.0.0         h66d3029_49658    conda-forge
[conda] mkl-include               2024.0.0         h66d3029_49658    conda-forge
[conda] numpy                     1.26.3                   pypi_0    pypi
[conda] optree                    0.10.0                   pypi_0    pypi
```

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @vladimir-aubrecht @iremyux @Blackhex @cristianPanaite

**Comment by malfet** [comment] 2024-01-29 02:13
This looks like a duplicate of  https://github.com/pytorch/pytorch/issues/117589
I.e. your mkl installation is faulty if PyTorch is trying to build with PocketFFT. On the other hand, this problem should be fixed with the latest submodule update

**Comment by malfet** [comment] 2024-01-29 02:14
Closing as duplicate of https://github.com/pytorch/pytorch/issues/117589

**Closed by malfet** 2024-01-29 02:14 UTC
Labels: module: build, module: windows, triaged
