### ISSUE TITLE
CUDNN_STATUS_EXECUTION_FAILED corrupted double-linked list 

### ISSUE THREAD

**Issue by zynos** [pytorch/pytorch#34779] opened 2020-03-15 09:55 UTC
## 🐛 Bug

After 62 hours of reinforcement learning network training my script gets killed by SIGABRT
`Process finished with exit code 134 (interrupted by signal 6: SIGABRT)`

<pre>Traceback (most recent call last):
  File "/home/nick/PycharmProjects/babyRudder/babyai/scripts/train_rl.py", line 194, in <module>
    logs = algo.update_parameters(status['i'])
  File "/home/nick/PycharmProjects/babyRudder/babyai/babyai/rl/algos/ppo.py", line 42, in update_parameters
    exps, logs = self.collect_experiences(update_nr)
  File "/home/nick/PycharmProjects/babyRudder/babyai/babyai/rl/algos/base.py", line 248, in collect_experiences
    action, self.rewards[i], done, preprocessed_obs.instr, preprocessed_obs.image)
  File "/home/nick/PycharmProjects/babyRudder/babyai/babyai/rl/algos/base.py", line 148, in update_rudder_and_rescale_rewards
    self.rudder.train_full_buffer()
  File "/home/nick/PycharmProjects/babyRudder/babyai/myScripts/Rudder.py", line 160, in train_full_buffer
    for i,episode in enumerate(episodes):
  File "/home/nick/PycharmProjects/babyRudder/babyai/myScripts/Rudder.py", line 140, in train_and_set_metrics
    loss.backward()
  File "/home/nick/PycharmProjects/babyRudder/venv3_7/lib/python3.7/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/nick/PycharmProjects/babyRudder/venv3_7/lib/python3.7/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
[INFO/MainProcess] process shutting down
[INFO/MainProcess] calling terminate() for daemon Process-2
[INFO/MainProcess] calling terminate() for daemon Process-196
...
corrupted double-linked list

</pre>

## To Reproduce

This happens in the function:
<pre>
    def train_and_set_metrics(self, episode,episode_id):    
        loss, returns, quality = self.feed_network(episode)

        loss.backward()

        self.optimizer.step()
        self.optimizer.zero_grad()

        loss = loss.detach().item()
        returnn = returns.detach().item()
        # print("Loss",loss)
        episode.loss = loss
        episode.returnn = returnn
        self.replay_buffer.fast_losses[episode_id]=loss
        # print("loss", loss)
        return quality > 0
</pre>

After the ` loss.backward()` call the script gets killed (see stacktrace) with the message `corrupted double-linked list` at the end.
## Expected behavior
It should not crash.
I monitored the cuda memory consumption which was fine, but maybe the RAM was full.
I would like to know if someone else saw a `corrupted double-linked list` after the backward call and how this could be fixed.

## Environment

<pre>
Package      Version Location                                    
------------ ------- --------------------------------------------
apex         0.1     
babyai       0.0.2   /home/nick/PycharmProjects/babyRudder/babyai
blosc        1.8.3   
cloudpickle  1.3.0   
future       0.18.2  
gym          0.17.1  
gym-minigrid 1.0.1   
numpy        1.15.4  
pip          20.0.2  
protobuf     3.11.3  
pyglet       1.5.0   
PyQt5        5.14.1  
PyQt5-sip    12.7.1  
scipy        1.4.1   
setuptools   41.2.0  
six          1.14.0  
tensorboardX 2.0     
torch        1.4.0   

</pre>

 - OS : ubuntu 18.04
 - How you installed PyTorch : pip 
 - Python version: 3.7
 - CUDA/cuDNN version: cuda 10.1, cudnn 7603
 - GPU models and configuration: 1x RTX 2070
 - NVIDIA-SMI 435.21

cc @ezyang @gchanan @zou3519 @ngimel @csarofeen @ptrblck

**Comment by ptrblck** [comment] 2020-03-15 10:17
I guess the `corrupted double-linked list` error might be raised by `glibc` as a sequential failure of the `RuntimeError`.
Could you explain your use case a bit more? I.e. are you changing the input shapes / model parameters during the RL training?
How large is the peak memory usage on the device and would it be possible to try to give us a code snippet to reproduce this issue (I imaging it might be hard, if the code runs fine for 62 hours :/ ).

**Comment by zynos** [comment] 2020-03-15 10:30
Hi, thanks for the quick response!
I am using the babyAI environment (https://github.com/mila-iqia/babyai)
and every timestep I collect data and store complete episodes (maximum of 128 timesteps at the moment) in an external replay buffer.
from this replay buffer i train an LSTM in a online fashion with the goal of predicting the episode's reward. The episodes vary in length.

The main trainnig is done in these two functions:

<pre>
 def predict_every_timestep(self, episode: ProcessData):
        hidden = None
        predictions = []
        for i, done in enumerate(episode.dones):
            ts_data = episode.get_timestep_data(i)
            pred, hidden = self.net(ts_data, hidden)
            predictions.append(pred)
            if done:
                break
      
        predictions = torch.cat(predictions, dim=1)
        return predictions
</pre>

and 
<pre>
 def forward(self, dic,hidden,batch=False):
        image, instruction, action, embedding=self.extract_dict_values(dic,batch)
        if batch:
            image = self.image_conv(image).squeeze(2).squeeze(2)
            instruction = self.instr_rnn(self.word_embedding(instruction))[1][-1]
            action = torch.nn.functional.one_hot(action, num_classes=self.action_space).float()
            x = torch.cat([image, instruction, action, embedding], dim=-1).unsqueeze(0).transpose(0,1)
        else:
            image=self.image_conv(image).squeeze(2).squeeze(2).unsqueeze(0)
            instruction=self.instr_rnn(self.word_embedding(instruction))[1][-1].unsqueeze(0)
            action=torch.nn.functional.one_hot(action, num_classes=self.action_space).float().unsqueeze(0)
            x=torch.cat([image,instruction,action,embedding],dim=-1)
        batch_size=x.shape[0]
        # self.init_hidden(batch_size)
        if hidden:
            x, hidden = self.lstm(x)
        else:
            x,hidden=self.lstm(x,hidden)
        x=self.linear_out(x.squeeze(1))

        return x,hidden
</pre>
i hope that helps.

if you want to reproduce this you would need to clone my branch
https://github.com/zynos/babyai/tree/fresh_foo
and run
`train_rl.py --env BabyAI-PutNextLocal-v0 --model SOMEMODELNAME --recurrence 20 --memory-dim 2048 --instr-dim 256 --instr-arch "attgru" --tb --procs 256`

**Comment by ptrblck** [comment] 2020-03-15 10:34
Do you have a limit on the max length of the episodes?
Also, how large was the peak memory usage during the run?

**Comment by zynos** [comment] 2020-03-15 10:37
The max length of an episode is 128 for this specific environment which also caused the crash.
Cuda memory is constant around 2579MiB / 7981MiB
My RAM (with open browser etc is around 14 / 16 GB

**Comment by ngimel** [comment] 2022-02-07 20:32
Closing due to age/new cudnn versions we are using.

**Closed by ngimel** 2022-02-07 20:32 UTC
Labels: high priority, needs reproduction, module: crash, module: cudnn, module: cuda, triaged
