### ISSUE TITLE
Error in CI: RuntimeError: CUDA error: an illegal memory access was encountered

### ISSUE THREAD

**Issue by Baranowski** [pytorch/pytorch#36722] opened 2020-04-16 14:18 UTC
## 🐛 Bug

When writing a new PR, CI reported `RuntimeError: CUDA error: an illegal memory access was encountered` for a test I added and all the subsequent tests in configuration `pytorch_linux_xenial_cuda10_2_cudnn7_py3_gcc7_test`.

## To Reproduce

1. (Re-)trigger a CI run for https://github.com/pytorch/pytorch/pull/36864

## Expected behavior

No error, or a more descriptive error message.

## Environment

CircleCI

## Additional context

Shoutout to @Pearu for narrowing it down and cc in case he has something to add.

https://github.com/pytorch/pytorch/issues/21819 has the same symptoms but according to https://github.com/pytorch/pytorch/issues/21819#issuecomment-614493009 it's a different issue.

cc @ezyang @gchanan @zou3519 @ngimel

**Comment by mruberry** [comment] 2020-04-18 05:10
Can you provide a reproduction that doesn't involve modifying PyTorch? If not, why do you think the modification is valid? That is, what's the issue in PyTorch preventing your modification from working properly?

**Comment by Baranowski** [comment] 2020-04-18 08:19
You are right. I'm pretty certain it's an existing issue with PyTorch or one of its dependencies but will need to dig some more to find a convincing reproducer. Assigning to myself until I do.

**Comment by mruberry** [comment] 2020-04-18 08:32
Thanks @Baranowski ;)

**Comment by Baranowski** [comment] 2020-04-19 08:46
I found a reproducer without modifying the PyTorch source code: https://github.com/pytorch/pytorch/pull/36864. I have updated the original bug report.

I tried to simplify the test but then the error no longer shows up, so it should be reasonably close to a MWE.

**Comment by mruberry** [comment] 2020-04-19 09:00
Awesome! That is extremely interesting. I can also run this locally without issue. I wonder what's going on with that particular test build?

**Comment by Baranowski** [comment] 2020-04-19 14:28
I also cannot reproduce it locally but one of my colleagues could reliably reproduce it on his setup, so it's not just a CI environment quirk.

**Comment by VitalyFedyunin** [comment] 2020-04-20 17:13
You could also try running test with `CUDA_LAUNCH_BLOCKING` to find failing tests.

**Comment by mruberry** [comment] 2020-05-08 19:42
Here's what I think is going on. The following script is a simple repro on multigpu systems with p2p access disabled:

```
import torch

a = torch.rand([], requires_grad=True, device='cuda:0')
b = torch.rand(10, requires_grad=True, device='cuda:1')

c = a * b
torch.cuda.synchronize()
```

To disable p2p access you can edit this line https://github.com/pytorch/pytorch/blob/0d9e3b48c4ef54a7b5395c501ee370a8eba34bad/aten/src/THC/THCGeneral.cpp#L130
to `if (false) {`. This will prevent PyTorch from enabling p2p access.

Running under cuda-memcheck then reveals:

```
========= Invalid __global__ read of size 4
=========     at 0x000013b8 in _ZN2at6native6modern27unrolled_elementwise_kernelIZZZNS0_15mul_kernel_cudaERNS_14TensorIteratorEENKUlvE_clEvENKUlvE2_clEvEUlffE_NS_6detail5ArrayIPcLi3EEE16OffsetCalculatorILi2EjESC_ILi1EjEEEviT_T0_T1_T2_
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0x7f4e87400200 is out of bounds
```

What's odd about this is that, as best I can tell, that address *should* be valid. The function receives a TensorIterator with three address (two inputs and one input), and they are:

```
0x7f4e87400400
0x7f4e87400200
0x7f4e87400000
``` 

which all live inside the same block allocated by the CUDACachingAllocator. The pointer attributes of these pointers also indicate that they are on the correct device (device 1 in this case). 

A slight modification to the script WILL work:

```
import torch

a = torch.rand([], requires_grad=True, device='cuda:0')
b = torch.rand(10, requires_grad=True, device='cuda:1')

c = a.to('cuda:1') * b
torch.cuda.synchronize()
```

Explicitly sending `a` to the same device as `b` before the multiplication avoids TensorIterator trying to create a copy of `a` on cuda:1, but what the issue is with TensorIterator's copying and why it only occurs when p2p access is disabled is still unclear.

A fix (and a test for the fix, since we don't currently expose whether p2p access is enabled in Python) will require additional follow-up.

**Comment by mruberry** [comment] 2020-05-10 09:51
@ngimel Identified the issue in a follow-up. While TensorIterator identifies a "common device" and moves zero-dim tensors to it, that device is never used. The kernel is launched on the device of its first CUDA argument. When p2p access is enabled this would work because a kernel would launch on device 0 and access two tensors on device 1 (since TensorIterator would move the zero-dim tensor to device 1). When p2p access is disabled this fails because the device 0 kernel attempts to access two device 1 tensors.

After some discussion, we think this may best be addressed by always preventing interactions between CUDA tensors on different devices. I filed https://github.com/pytorch/pytorch/issues/38205 to track that discussion.

**Closed** 2023-02-01 01:33 UTC
Labels: high priority, module: cuda, triaged, quansight-nack
