### ISSUE TITLE
Python3.11 Support

### ISSUE THREAD

**Issue by jhirshman** [pytorch/pytorch#87723] opened 2022-10-25 19:30 UTC
### 🚀 The feature, motivation and pitch

With Python3.11 out with speed upgrades, can we get the next version of pytorch to publish wheels for Python 3.11

**Comment by malfet** [comment] 2022-10-25 20:54
We already have python3.11 wheels, but not much tested (i.e. some JIT functionality is probably broken)

**Comment by malfet** [comment] 2022-10-25 20:54
Closing as duplicate of https://github.com/pytorch/pytorch/issues/86566

**Closed by malfet** 2022-10-25 20:54 UTC
