### ISSUE TITLE
[FSDP] Saving full_state_dict for optimizer can result in hang for medium+ size models

### ISSUE THREAD

**Issue by lessw2020** [pytorch/pytorch#80581] opened 2022-06-30 01:08 UTC
### 🐛 Describe the bug

Using FSDP with latest nightlies (ala 627), when attempting to save the optimizer via full_state_dict call, one can readily hit an internal OOM which is shown to the user as a hang.  Example, a 500M model on V100 4 gpu single node. 
simplified code:
~~~
optim_state = FSDP.full_optim_state_dict(model, optimizer)
    if rank==0:
        torch.save(optim_state, opt_save_full_path)
~~~
result = hang with the following debug info:
<img width="634" alt="hang2_optim_state" src="https://user-images.githubusercontent.com/46302957/176570878-16ea873f-73da-472b-9c13-c91097bf9df8.png">

The core communication calls all complete on ranks 1-3, but rank0 hangs. 
This works fine if running smaller models ala 8M or 60M.

[edited - removed references to OOM now that we know it's not memory but the movement to cpu]

### Versions

1.13.0.dev20220627+cu113

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @SciPioneer @H-Huang @kwen2501 @ezyang

**Comment by awgu** [comment] 2022-06-30 01:21
Discussed offline, but optim state checkpointing already offloads to CPU by default:
https://github.com/pytorch/pytorch/blob/master/torch/distributed/fsdp/_optim_utils.py#L157-L162

I will look into this.

**Comment by awgu** [comment] 2022-06-30 03:13
I have confirmed that the hang happens when copying all-gathered tensor state from device to host:
https://github.com/pytorch/pytorch/blob/dc7066a8f00f60bd055e78100b144f3373b11aba/torch/distributed/fsdp/_optim_utils.py#L162
- Removing the `.cpu()` **resolves** the hang.
- Waiting until _all_ all-gathers have finished first before moving all tensor states to CPU **resolves** the hang.
- `torch.cuda.synchronize()` before and/or after the device-to-host transfer **does not resolve** the hang.
- The hang appears to 
- Not reusing the same `tensor_buffer` for the all-gathers between a `FlatParameter`'s `exp_avg` and `exp_avg_sq` may **delay the hang**, and the hang seems to be slightly **non-deterministic**. I ran each config with `CUDA_BLOCKING_LAUNCH=1` several times.
    - For the 500M model, as is, the hang happens on the 13th out of 119 `FlatParameter`s. Not reusing the same `tensor_buffer` delays the hang to the 16th out of 119 `FlatParameter`s (or one time the 17th out of 119).
    - For the 1.5B model, both as is and not reusing the same `tensor_buffer`, the hang happens on the 29th out of 355 `FlatParameter`s. (I never saw it hang at a different place in the execution.)

cc: @rohan-varma @zhaojuanmao Any ideas on why the `.cpu()` call could be causing the hang and why delaying it until later resolves it?

**Comment by lessw2020** [comment] 2022-06-30 16:33
*minor update - removed the references to OOM in title since we now know it's not memory issue.

**Comment by awgu** [comment] 2022-07-07 15:23
Reopening because, even though we landed the fix, we do not have an explanation for why the fix works.

**Closed** 2023-03-28 18:43 UTC
Labels: oncall: distributed, module: fsdp
