### ISSUE TITLE
Transcendental functions broken on Jetson Xavier NX

### ISSUE THREAD

**Issue by honzasp** [pytorch/pytorch#48901] opened 2020-12-06 18:16 UTC
## 🐛 Bug

Transcendental functions (such as `torch.exp`, `torch.sin`, `torch.cos`) return random garbage on Jetson Xavier NX.

## To Reproduce

Sample session from Python REPL:

```
$ python3
Python 3.6.9 (default, Oct  8 2020, 12:12:24) 
[GCC 8.4.0] on linux
>>> import torch
>>> xs = torch.linspace(-5, 5, 11)
>>> xs
tensor([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])
>>> torch.exp(xs)
tensor([ 8.4078e-45,  0.0000e+00,  0.0000e+00,  1.4013e-45, -1.1519e+35,
         1.7796e-43, -4.2164e-19,  1.7796e-43,  3.0000e+00,  4.0000e+00,
         5.0000e+00])
>>> torch.sin(xs)
tensor([ 8.4078e-45,  0.0000e+00,  0.0000e+00,  1.4013e-45, -1.1519e+35,
         1.7796e-43, -4.2164e-19,  1.7796e-43,  3.0000e+00,  4.0000e+00,
         5.0000e+00])
>>> torch.cos(xs)
tensor([ 8.4078e-45,  0.0000e+00,  0.0000e+00,  1.4013e-45, -1.1519e+35,
         1.7796e-43, -4.2164e-19,  1.7796e-43,  3.0000e+00,  4.0000e+00,
         5.0000e+00])
```

Note that all three calls return exactly the same values.

## Expected behavior

The functions should return tensors with correct values.

## Environment

Running on the Jetson Xavier NX Development Kit from Nvidia.

PyTorch version: 1.7.0
Is debug build: True
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (aarch64)
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: version 3.10.2

Python version: 3.6 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: 10.2.89
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Probably one of the following:
/usr/lib/aarch64-linux-gnu/libcudnn.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_adv_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_cnn_train.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_infer.so.8.0.0
/usr/lib/aarch64-linux-gnu/libcudnn_ops_train.so.8.0.0
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.1
[pip3] torch==1.7.0
[pip3] torchvision==0.8.0a0+45f960c
[conda] Could not collect

cc @ngimel

**Comment by ailzhang** [comment] 2020-12-07 19:34
marking as triage review since we might not have CI for Jetson, but it's probably worth taking a look to see if it's reproducible.

**Comment by ngimel** [comment] 2020-12-07 19:38
#48451 can be related, I suspect it's arm, not cuda. cc @malfet

**Comment by honzasp** [comment] 2020-12-08 07:17
I agree that this seems to be an ARM issue, not CUDA issue, because CUDA is not used. #48451 suggests that this is caused by an old version of GCC, I will try building PyTorch using a newer version or using the nightly wheel.

**Comment by malfet** [comment] 2020-12-08 15:50
@honzasp can you please run `python3 -m torch.utils.collect_env` and share its output here?
Can not reproduce the problem on M1, but can using aarch64 nightlies:
```
$ pip3 install --pre torch  -f https://download.pytorch.org/whl/nightly/cpu/torch_nightly.html --user
Collecting torch
  Using cached https://download.pytorch.org/whl/nightly/cpu/torch-1.8.0.dev20201126-cp36-cp36m-linux_aarch64.whl
Collecting typing-extensions (from torch)
  Using cached https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl
Collecting dataclasses; python_version < "3.7" (from torch)
  Using cached https://files.pythonhosted.org/packages/fe/ca/75fac5856ab5cfa51bbbcefa250182e50441074fdc3f803f6e76451fab43/dataclasses-0.8-py3-none-any.whl
Collecting numpy (from torch)
Installing collected packages: typing-extensions, dataclasses, numpy, torch
Successfully installed dataclasses-0.8 numpy-1.19.4 torch-1.8.0.dev20201126 typing-extensions-3.7.4.3
ubuntu@ip-172-31-49-63:~$ python3 -c "import torch;xs=torch.linspace(-5, 5, 11); print(''.join([f'torch.{f.__name__}(xs)={f(xs)}\n' for f in (torch.exp, torch.sin, torch.cos)]))"
torch.exp(xs)=tensor([  1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,   1.0000,
          1.0000,  20.0855,  54.5981, 148.4132])
torch.sin(xs)=tensor([ 2.2421e-43,  0.0000e+00,  1.4013e-45,  0.0000e+00,  2.1536e-18,
         0.0000e+00,  5.1776e-18,  0.0000e+00,  1.4112e-01, -7.5680e-01,
        -9.5892e-01])
torch.cos(xs)=tensor([ 1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,  1.0000,
        -0.9900, -0.6536,  0.2837])
```
On M1 output looks as follows:
```
% python3 -c "import torch;xs=torch.linspace(-5, 5, 11); print(''.join([f'torch.{f.__name__}(xs)={f(xs)}\n' for f in (torch.exp, torch.sin, torch.cos)]))"
torch.exp(xs)=tensor([6.7379e-03, 1.8316e-02, 4.9787e-02, 1.3534e-01, 3.6788e-01, 1.0000e+00,
        2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01, 1.4841e+02])
torch.sin(xs)=tensor([ 0.9589,  0.7568, -0.1411, -0.9093, -0.8415,  0.0000,  0.8415,  0.9093,
         0.1411, -0.7568, -0.9589])
torch.cos(xs)=tensor([ 0.2837, -0.6536, -0.9900, -0.4161,  0.5403,  1.0000,  0.5403, -0.4161,
        -0.9900, -0.6536,  0.2837])
```

**Comment by honzasp** [comment] 2020-12-08 16:10
@malfet Thank you for looking into this issue! I included the output of this script in the issue description (the first comment at the top of the page).

**Comment by malfet** [comment] 2020-12-09 02:39
If PyTorch for AARCH64 is compiled by clang, problem goes away

**Comment by malfet** [comment] 2020-12-11 18:08
I suspect the compiler has trouble understanding register mapping or preserving NEON state
https://github.com/pytorch/pytorch/blob/f10b53d9eaa282d240fa79ee8f03ea42457803d5/aten/src/ATen/cpu/vec256/missing_vst1_neon.h#L5-L8

**Closed** 2020-12-14 18:12 UTC
Labels: module: arm, triage review

**Comment by malfet** [comment] 2020-12-14 18:20
Need to follow up with a better mechanism to triage/fix those in the future.

**Comment by honzasp** [comment] 2020-12-17 18:06
Wow, this was really a nasty bug, thank you very much for finding and fixing it!
