### ISSUE TITLE
torch.slice_copy incorrectly parses default value for the step argument

### ISSUE THREAD

**Issue by abulavin** [pytorch/pytorch#90291] opened 2022-12-06 15:48 UTC
### 🐛 Describe the bug

When `torch.slice_copy` is called without setting the `step` argument, the `step` argument is not set to be 1, which is the default value according to the signature of the function. This causes the output of `torch.slice_copy` to be incorrect. When `step` is explicitly set as a keyword argument, this bug does not occur.

Reproducer:
```python
import torch

t = torch.tensor([1, 2, 3])
print(torch.slice_copy(t, dim=0, step=1)) # [1, 2, 3]
# the default value of `step` is 1 in slice_copy
print(torch.slice_copy(t, dim=0)) # [1]

# fails
assert torch.equal(torch.slice_copy(t, dim=0, step=1), torch.slice_copy(t, dim=0))
```
The above assert should pass.
Likely to be an issue in the native slice handler in `TensorShapes.cpp`? I've ran the code above under GDB and it appears that the value for `step` is read from uninitialised memory if the default value is used.

### Versions

PyTorch version: 1.13.0+cpu
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 13.0.0 (https://github.com/llvm/llvm-project.git d7b669b3a30345cfcdb2fde2af6f48aa4b94845d)
CMake version: version 3.18.2
Libc version: glibc-2.10

Python version: 3.7.12 | packaged by conda-forge | (default, Oct 26 2021, 06:08:21)  [GCC 9.4.0] (64-bit runtime)
Python platform: Linux-5.4.0-110-generic-x86_64-with-debian-buster-sid
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.13.0+cpu
[pip3] torchvision==0.14.0+cpu
[conda] numpy                     1.21.6                   pypi_0    pypi
[conda] torch                     1.13.0+cpu               pypi_0    pypi
[conda] torchvision               0.14.0+cpu               pypi_0    pypi

**Comment by abulavin** [comment] 2022-12-07 12:08
The issue appears to be related to Python version.

Running with python 3.7.12 causes the script to fail, however after installing the nightly using conda and then running under python 3.10.8, there is no failure. Running on a nightly with 3.7.12 also causes the failure.

**Comment by ZailiWang** [comment] 2022-12-09 03:27
I tried with python=3.7.12. The issues can be reproduced for Pth=1.13 install package (conda install pytorch) but with master source build the result is good. The gen-ed code in slice_copy.h is same as above.

**Comment by jingxu10** [comment] 2023-02-08 06:59
Since the issue cannot be reproduced on master, let's close this ticket for now. If this issue occurs again with the latest code base, please reopen it. Thank you.

**Closed by jingxu10** 2023-02-08 06:59 UTC
Labels: needs reproduction, triaged
