### ISSUE TITLE
ONNX: torch.where() failing because of  __derive_index

### ISSUE THREAD

**Issue by fteufel** [pytorch/pytorch#50125] opened 2021-01-06 01:42 UTC
## 🐛 Bug

I'm trying to export a model using ONNX, the used operations are supposed to be supported. I'm using `torch.jit.script`. When compiling a call to `torch.where()`, onnx.export() fails.
```
RuntimeError: Exporting the operator __derive_index to ONNX opset version 11 is not supported. Please open a bug to request ONNX export support for the missing operator.
```

## To Reproduce

```
@torch.jit.script
def _viterbi_decode_onnx(emissions: torch.Tensor,
                    mask: torch.Tensor,
                    start_transitions: torch.Tensor,
                    end_transitions: torch.Tensor,
                    transitions: torch.Tensor) -> List[torch.Tensor]:

    score = start_transitions + emissions[0]
    history: List[torch.Tensor] = [] 

    # Viterbi algorithm recursive case: we compute the score of the best tag sequence
    # for every possible next tag
    
    for i in range(1, 70):
        
        broadcast_score = score.unsqueeze(2)
        broadcast_emission = emissions[i].unsqueeze(1)
      
        next_score = broadcast_score + transitions + broadcast_emission
        next_score, indices = next_score.max(dim=1)
        
        score = torch.where(mask[i].unsqueeze(1), next_score, score) #this is where it fails. It's the where op, not indexing/squeezing
        history.append(indices)
```

## Expected behavior

According to the docs, `torch.where()` is supposed to be supported by ONNX. Is there something wrong with the specific usage of where?

## Environment

Using nightly torch build 1.8.0.dev20210105

cc @houseroad @spandantiwari @lara-hdr @BowenBao @neginraoof

**Comment by spandantiwari** [comment] 2021-01-06 18:24
@fteufel - we have a PR enabling the export of __derive_index but it is not in master yet. https://github.com/pytorch/pytorch/pull/49514
Adding @neginraoof who is the author of the PR to see if torch.where() should be enabled after that.

**Comment by neginraoof** [comment] 2021-01-08 23:41
The issue here is that where operator has an input (mask) that is selected based on the iterator (i). So, the _derive_index op is taking the count of the iterator to select the mask and pass that to where op.
As you can see form the logs, the issue is that we do not have support for export of the _derive_index op in master yet.
This is already implemented in our dev branch, and will go to master soon.

I have tested a sample based on your code with our dev branch and it looks to be exported correctly.
Will update this thread once the PR is in.

**Comment by SeanLiaoy** [comment] 2021-07-11 14:00
Hi @fteufel , I am facing the same problem when trying to export a pytorch CRF model to ONNX.  Have you sovled the problem? Any suggestion would be grateful!

**Comment by fteufel** [comment] 2021-07-12 13:55
@SeanLiaoy unfortunately no, ended up using torchscript instead. Have not checked if the PR is in stable as of pytorch 1.9 though.

**Comment by thiagocrepaldi** [comment] 2022-10-24 21:46
Fixed by https://github.com/pytorch/pytorch/pull/49514

**Closed by thiagocrepaldi** 2022-10-24 21:46 UTC
Labels: needs reproduction, module: onnx, triaged
