### ISSUE TITLE
Crash with `numpy >=1.23.4` and `torch 1.13.0` due to `DLpack` interaction

### ISSUE THREAD

**Issue by shadeMe** [pytorch/pytorch#88082] opened 2022-10-31 12:31 UTC
### 🐛 Describe the bug

We use PyTorch in our ML framework [Thinc](https://github.com/explosion/thinc), and we started noticing CI failures on both Windows and Linux after `torch 1.13.0` was released late last week. After isolating the delinquent test case, we were able to reproduce the crash locally with the following minimum reproducible example:

```python
import torch

x = torch.zeros(10)
data_np = x.detach().cpu().numpy()
rev = torch.utils.dlpack.from_dlpack(data_np)
x.data = rev
```

`stderr` output:
```
Fatal Python error: PyEval_SaveThread: the function must be called with the GIL held, but the GIL is released (the current Python thread state is NULL)
Python runtime state: initialized

Current thread 0x00007f8a356bd480 (most recent call first):
File "/home/user/regression-testing/torch_segfault.py", line 60 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, torch._C, torch._C._fft, torch._C._linalg, torch._C._nested, torch._C._nn, torch._C._sparse, torch._C._special (total: 20)
[1]    8496 IOT instruction  python ~/regression-testing/torch_segfault.py
```

Attaching a debugger to the Python process yielded the following stack trace:
```
libc.so.6!__GI_raise(int sig) (/build/glibc-SzIz7B/glibc-2.31/sysdeps/unix/sysv/linux/raise.c:50)
libc.so.6!__GI_abort() (/build/glibc-SzIz7B/glibc-2.31/stdlib/abort.c:79)
fatal_error_exit(int status) (/usr/local/src/conda/python-3.10.6/Python/pylifecycle.c:2556)
fatal_error(int fd, int header, const char * prefix, const char * msg, int status) (/usr/local/src/conda/python-3.10.6/Python/pylifecycle.c:2667)
_Py_FatalErrorFunc(const char * func, const char * msg) (/usr/local/src/conda/python-3.10.6/Python/pylifecycle.c:2753)
_Py_FatalError_TstateNULL(const char * func) (/usr/local/src/conda/python-3.10.6/Python/ceval.c:271)
_Py_EnsureFuncTstateNotNULL() (/usr/local/src/conda/python-3.10.6/Include/internal/pycore_pystate.h:95)
PyEval_SaveThread() (/usr/local/src/conda/python-3.10.6/Python/ceval.c:529)
PyEval_SaveThread() (/usr/local/src/conda/python-3.10.6/Python/ceval.c:520)
libtorch_python.so!THPVariable_clear(THPVariable*) (Unknown Source:0)
libtorch_python.so!THPVariable_subclass_dealloc(_object*) (Unknown Source:0)
_multiarray_umath.cpython-310-x86_64-linux-gnu.so!array_dealloc (Unknown Source:0)
libc10.so!c10::deleteInefficientStdFunctionContext(void*) (Unknown Source:0)
libtorch_python.so!c10::StorageImpl::~StorageImpl() (Unknown Source:0)
libc10.so!c10::intrusive_ptr<c10::StorageImpl, c10::detail::intrusive_target_default_null_type<c10::StorageImpl> >::reset_() (Unknown Source:0)
libc10.so!c10::TensorImpl::~TensorImpl() (Unknown Source:0)
libc10.so!c10::TensorImpl::~TensorImpl() (Unknown Source:0)
libtorch_python.so!THPVariable_clear(THPVariable*) (Unknown Source:0)
libtorch_python.so!THPVariable_subclass_dealloc(_object*) (Unknown Source:0)
_Py_Dealloc(PyObject * op) (/usr/local/src/conda/python-3.10.6/Objects/object.c:2298)
_Py_DECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:500)
_Py_XDECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:567)
free_keys_object(PyDictKeysObject * keys) (/usr/local/src/conda/python-3.10.6/Objects/dictobject.c:628)
dictkeys_decref(PyDictKeysObject * dk) (/usr/local/src/conda/python-3.10.6/Objects/dictobject.c:337)
dict_dealloc(PyDictObject * mp) (/usr/local/src/conda/python-3.10.6/Objects/dictobject.c:2076)
odict_dealloc(PyODictObject * self) (/usr/local/src/conda/python-3.10.6/Objects/odictobject.c:1416)
_Py_Dealloc(PyObject * op) (/usr/local/src/conda/python-3.10.6/Objects/object.c:2298)
_Py_DECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:500)
_Py_XDECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:567)
dict_dealloc(PyDictObject * mp) (/usr/local/src/conda/python-3.10.6/Objects/dictobject.c:2068)
_Py_Dealloc(PyObject * op) (/usr/local/src/conda/python-3.10.6/Objects/object.c:2298)
_Py_DECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:500)
subtype_dealloc(PyObject * self) (/usr/local/src/conda/python-3.10.6/Objects/typeobject.c:1438)
_Py_Dealloc(PyObject * op) (/usr/local/src/conda/python-3.10.6/Objects/object.c:2298)
_Py_DECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:500)
_Py_XDECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:567)
dict_dealloc(PyDictObject * mp) (/usr/local/src/conda/python-3.10.6/Objects/dictobject.c:2068)
_Py_Dealloc(PyObject * op) (/usr/local/src/conda/python-3.10.6/Objects/object.c:2298)
_Py_DECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:500)
subtype_dealloc(PyObject * self) (/usr/local/src/conda/python-3.10.6/Objects/typeobject.c:1438)
_Py_Dealloc(PyObject * op) (/usr/local/src/conda/python-3.10.6/Objects/object.c:2298)
_Py_DECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:500)
_Py_XDECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:567)
list_dealloc(PyListObject * op) (/usr/local/src/conda/python-3.10.6/Objects/listobject.c:349)
_Py_DECREF(PyObject * op) (/usr/local/src/conda/python-3.10.6/Include/object.h:500)
clear_slots(PyTypeObject * type) (/usr/local/src/conda/python-3.10.6/Objects/typeobject.c:1267)
subtype_clear(PyObject * self) (/usr/local/src/conda/python-3.10.6/Objects/typeobject.c:1285)
delete_garbage(PyGC_Head * old, PyGC_Head * collectable, GCState * gcstate, PyThreadState * tstate) (/usr/local/src/conda/python-3.10.6/Modules/gcmodule.c:1017)
gc_collect_main(PyThreadState * tstate, int generation, Py_ssize_t * n_collected, Py_ssize_t * n_uncollectable, int nofail) (/usr/local/src/conda/python-3.10.6/Modules/gcmodule.c:1300)
_PyGC_CollectNoFail(PyThreadState * tstate) (/usr/local/src/conda/python-3.10.6/Modules/gcmodule.c:2123)
finalize_modules(PyThreadState * tstate) (/usr/local/src/conda/python-3.10.6/Python/pylifecycle.c:1528)
Py_FinalizeEx() (/usr/local/src/conda/python-3.10.6/Python/pylifecycle.c:1787)
Py_RunMain() (/usr/local/src/conda/python-3.10.6/Modules/main.c:672)
Py_BytesMain(int argc, char ** argv) (/usr/local/src/conda/python-3.10.6/Modules/main.c:1090)
libc.so.6!__libc_start_main(int (*)(int, char **, char **) main, int argc, char ** argv, int (*)(int, char **, char **) init, void (*)(void) fini, void (*)(void) rtld_fini, void * stack_end) (/build/glibc-SzIz7B/glibc-2.31/csu/libc-start.c:308)
_start() (/usr/local/src/conda/python-3.10.6/Python/getplatform.c:9)
```

### Versions
```
PyTorch version: 1.13.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: KDE neon 5.26 (x86_64)
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: Could not collect
CMake version: version 3.22.1
Libc version: glibc-2.35

Python version: 3.10.6 (main, Oct 24 2022, 16:07:47) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-52-generic-x86_64-with-glibc2.35
Is CUDA available: False
CUDA runtime version: 11.3.109
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3090
Nvidia driver version: 515.65.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.6.0
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.6.0
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy==0.982
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==1.13.0+cpu
[conda] numpy                     1.23.4                   pypi_0    pypi
[conda] torch                     1.13.0+cpu               pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @albanD

**Comment by albanD** [comment] 2022-10-31 22:12
The `array_dlpack_deleter` provided by numpy does not acquire the GIL before calling into python APIs, hence the error.
Note that it does work fine with numpy 1.21.6 for me locally.

I opened an issue on the numpy side to see what they think: https://github.com/numpy/numpy/issues/22507

**Comment by albanD** [comment] 2022-11-01 13:59
> Thanks for the speedy response! Although that doesn't fully explain why the crash doesn't happen when testing with torch 1.12.x, right?

Not sure tbh. It is possible that 1.12 didn't not support the full DLPack format either and thus was not leveraging the fast numpy implementation.

**Comment by albanD** [comment] 2022-11-07 18:10
This is now fixed in Numpy's main branch.

**Comment by cpuhrsch** [comment] 2022-11-07 18:16
In 1.13.1 we should guard against this version of NumPy and throw an informative error.

**Comment by albanD** [comment] 2022-11-07 18:21
We should do some testing on which exact versions of Numpy are affected by this so that we can warn users and recommend to upgrade their version of Numpy.

**Comment by shadeMe** [comment] 2022-11-22 16:48
I did a `git bisect` to determine which commit introduced this bug between versions `1.12.1` and `1.13.0` and arrived at [this PR](https://github.com/pytorch/pytorch/pull/83623). I do not have enough context to ascertain if this change breaks an existing pre-condition (of an acquired GIL during deallocation) inadvertently or if it coincidentally revealed a bug in `numpy`.

In any event, I thought I'd post it here for future reference.

**Comment by albanD** [comment] 2022-11-22 18:51
Thanks for looking into this in more details!
That PR is most likely the cause of this change in behavior indeed.
In general, C++ deallocators should not expect the GIL to be held (all our deallocators properly handle this case) so I don't think it breaks any pre-condition no.

We you able to go around that problem on your end by adapting the numpy version?

**Comment by adrianeboyd** [comment] 2022-11-22 19:14
No, it looks like the fix will first be included in v1.24.0, so all versions from v1.22-v1.23 are affected.

**Comment by albanD** [comment] 2022-11-22 19:16
Can you use numpy 1.21.6 in the meantime?

**Comment by adrianeboyd** [comment] 2022-11-22 19:26
It's not really a great solution because it's then missing the entire dlpack support. For many users torch v1.12.1 is a good option, but we were just planning to start promoting a lot of recent work on metal performance shaders following the torch v1.13.0 release, so there's just no good general solution.

The other practical problem is that our users have enough trouble installing torch in the first place and installing by any other option than the most recent release from pip/conda or from the quickstart is going to be difficult.

**Comment by albanD** [comment] 2022-11-22 19:45
Thanks for the details!
I think we would be ok with a fix in PyTorch that acquires the GIL (even if it costs perf) for these particular versions of numpy and only for dlpack Tensors.
I would be happy to review/merge such a patch but I don't have a good sense how to do it from the top of my head :/

**Comment by shadeMe** [comment] 2022-11-24 16:13
I have a local build that adds a check for the delinquent `numpy` versions, but from my (admittedly limited) testing, there doesn't appear to be any straight-forward way to determine if the bound `at::Tensor` is backed by DLPack storage. 

One could tag the `THPVariable`'s `PyObject` with a marker attribute in `THPModule_fromDLPack` and then checking for that in `THPVariable_clear`, but it's a fairly intrusive change that (I think) leaks an implementation detail to Python land. Also, this extra state would need to be managed manually when rebinding the variable to a different tensor. So for those reasons at least, I'm reluctant to go with that.

Suggestions/pointers/ideas are most welcome.

**Comment by ezyang** [comment] 2022-11-24 21:38
Don't need to do anything like that.

When we do THPModule_fromDLPack you have to specify a deleter for the data pointer you put in. If the input is a numpy ndarray, and the numpy version is buggy, replace the normal deleter with a custom deleter that takes the GIL first (you can use the context object to store the original deleter if necessary).

More problematic is if you can create a free floating dlpack object from numpy, and then pass that to torch. Is that an error case too? It's not the case in your repro.

**Comment by shadeMe** [comment] 2022-11-25 13:05
> When we do THPModule_fromDLPack you have to specify a deleter for the data pointer you put in. If the input is a numpy ndarray, and the numpy version is buggy, replace the normal deleter with a custom deleter that takes the GIL first (you can use the context object to store the original deleter if necessary).

Thanks for the suggestion, will try it out.

> More problematic is if you can create a free floating dlpack object from numpy, and then pass that to torch. Is that an error case too? It's not the case in your repro.

The following code also causes a crash due to a failed `PyGILState_Check` assertion albeit not in the same call chain as with the previous one:
```python 
import numpy
data_np = numpy.zeros(10)
rev = torch.utils.dlpack.from_dlpack(data_np)
```
Could you clarify why this failure case is more problematic? Reverting the [delinquent commit](https://github.com/pytorch/pytorch/pull/83623) fixes the issue in both cases.

**Comment by ezyang** [comment] 2022-11-25 14:53
Err, this one looks similar, where we can detect in `from_dlpack` that we have a numpy object, which is how you would decide to do a custom deleter. My concern is cases where you don't get to see that it's a numpy object at all, from PyTorch library code.

**Comment by shadeMe** [comment] 2022-11-25 15:47
I'm not sure I fully understand what a "free floating dlpack object from numpy" might be in this context. And how does one pass such a Dlpack object to `torch` without invoking `torch.utils.dlpack.from_dlpack`?

In any event, if we can't confidently determine the provenance of the capsule, it might be worth considering the option of unconditionally holding the GIL in `THPVariable_clear` when using a buggy `numpy` release. While neither is ideal, reduced performance (under these specific circumstances) seems like a better option than a crash IMO.

**Comment by ezyang** [comment] 2022-11-25 16:02
sure

**Closed** 2022-12-28 13:23 UTC
Labels: module: crash, triaged, module: dlpack, module: python frontend
