### ISSUE TITLE
TransformerEncoderLayer fast path errors under `torch.autocast`

### ISSUE THREAD

**Issue by wendazhou** [pytorch/pytorch#82783] opened 2022-08-04 00:06 UTC
### 🐛 Describe the bug

Pytorch errors when the fast path is taken in `TransformerEncoderLayer` under an `autocast` context. Minimal reproducer below.

```python
import torch

device = torch.device("cuda")

x = torch.randn(4, 1, 16).to(device=device)

encoder_layer = torch.nn.TransformerEncoderLayer(
    d_model=16,
    nhead=1,
    batch_first=True,
    dropout=0.1).to(device=device)
encoder_layer.eval()

with torch.inference_mode():
    with torch.autocast("cuda", dtype=torch.float16):
        y = encoder_layer(x)
```
Fails with error: 
```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    main()
  File "test.py", line 17, in main
    y = encoder_layer(x)
  File "/mnt/home/wzhou/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/mnt/home/wzhou/miniconda3/envs/pytorch/lib/python3.8/site-packages/torch/nn/modules/transformer.py", line 437, in forward
    return torch._transformer_encoder_layer_fwd(
RuntimeError: expected scalar type Half but found Float
```

### Versions

Note: I checked that the error happens on colab for both 1.12 release and current 1.13 nightly.

Collecting environment information...
PyTorch version: 1.13.0.dev20220803+cu102
Is debug build: False
CUDA used to build PyTorch: 10.2
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
CMake version: version 3.22.5
Libc version: glibc-2.26

Python version: 3.7.13 (default, Apr 24 2022, 01:04:09)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.188+-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: 11.1.105
GPU models and configuration: GPU 0: Tesla T4
Nvidia driver version: 460.32.03
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.0.5
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.21.6
[pip3] torch==1.13.0.dev20220803+cu102
[pip3] torchaudio==0.12.0+cu113
[pip3] torchsummary==1.5.1
[pip3] torchtext==0.13.0
[pip3] torchvision==0.13.0+cu113
[conda] Could not collect

cc @jbschlosser @bhosmer @cpuhrsch @erichan1

**Comment by ngimel** [comment] 2022-08-04 00:52
cc @erichan1

**Comment by erichan1** [comment] 2022-09-08 23:27
Closing as a duplicate of https://github.com/pytorch/pytorch/issues/84396. Fix in progress https://github.com/pytorch/pytorch/pull/84722.

**Closed** 2022-09-08 23:27 UTC
Labels: oncall: transformer/mha
