### ISSUE TITLE
AssertionError: failed to reach fixed point (Python 3.8)

### ISSUE THREAD

**Issue by carmocca** [pytorch/pytorch#97811] opened 2023-03-28 18:11 UTC
### 🐛 Describe the bug

An assertion is triggered. I believe this only happens with Python 3.8, it doesn't with Python 3.10 at least.

Reported in https://github.com/Lightning-AI/lightning/issues/17177

### Error logs

```python
Traceback (most recent call last):
  File "kk4.py", line 29, in <module>
    training_step()
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 209, in _fn
    return fn(*args, **kwargs)
  File "kk4.py", line 25, in foo
    apply_to_collection(torch.tensor(1.))
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/eval_frame.py", line 337, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 404, in _convert_frame
    result = inner_convert(frame, cache_size, hooks)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 104, in _fn
    return fn(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 262, in _convert_frame_assert
    return _compile(
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/utils.py", line 163, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 324, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 445, in transform_code_object
    transformations(instructions, code_options)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/convert_frame.py", line 311, in transform
    tracer.run()
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1726, in run
    super().run()
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 576, in run
    and self.step()
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 540, in step
    getattr(self, inst.opname)(inst)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 378, in wrapper
    resume_call_insts = self.create_call_resume_at(self.next_instruction)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/symbolic_convert.py", line 1755, in create_call_resume_at
    new_code: types.CodeType = ContinueExecutionCache.lookup(
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/resume_execution.py", line 154, in lookup
    cls.cache[code][key] = cls.generate(code, lineno, *key)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/resume_execution.py", line 233, in generate
    new_code = transform_code_object(code, update)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 446, in transform_code_object
    return clean_and_assemble_instructions(instructions, keys, code_options)[1]
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_transformation.py", line 470, in clean_and_assemble_instructions
    code_options["co_stacksize"] = stacksize_analysis(instructions)
  File "/home/carlos/venv/lib/python3.8/site-packages/torch/_dynamo/bytecode_analysis.py", line 184, in stacksize_analysis
    assert fixed_point.value, "failed to reach fixed point"
AssertionError: failed to reach fixed point

from user code:
   File "kk4.py", line 14, in apply_to_collection
    if is_dataclass_instance(data):
```

### Minified repro

The code doesn't make much sense, it's a minified version from what's actually run.

```python
import dataclasses

import torch


def is_dataclass_instance(obj):
    if isinstance(obj, type):
        return False
    cls = type(obj)
    return hasattr(cls, "__dataclass_fields__")


def apply_to_collection(data):
    if is_dataclass_instance(data):
        fields = {}
        for k, v in fields.items():
            try:
                pass
            except dataclasses.FrozenInstanceError as e:
                break
    return data


def foo():
    apply_to_collection(torch.tensor(1.))


training_step = torch.compile(foo)
training_step()
```

### Versions

Torch 2.0 and current nightly

cc @ezyang @soumith @msaroufim @wconstab @ngimel @bdhirsh @voznesenskym @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @desertfire

**Comment by yanboliang** [comment] 2023-03-30 21:08
cc @williamwen42

**Comment by ar0ck** [comment] 2023-06-14 19:56
The given repro works fine on the current nightly, but the issue is not fixed. Here is a new repro (also `python3.8` only):

```python
import torch

def make(g):
    @torch.compile(backend='eager')
    def f():
        while True:
            try:
                print(g)
            except Exception as _:
                break
    return f

make(None)()
```

**Comment by skawngus1111** [comment] 2023-06-26 07:26
I got same issue. But, after I changed python version into 3.8 -> 3.10, the problem is solved. Thank you!!

**Comment by janeyx99** [comment] 2024-04-02 15:45
I don't believe this is actually fixed in entirety. Here's another repro using `continue` and `deepcopy` on 3.8. 
```
import torch
from copy import deepcopy

def make(g):
     @torch.compile(backend='eager')
     def f():
         x = deepcopy(g)
         for _ in range(1):
             try:
                 print(g)
             except Exception as _:
                 continue
     return f
make({"hello": 56})()
```

Returns:
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[12], line 15
     12                 continue
     13     return f
---> 15 make({"hello": 56})()

File /data/users/janeyx/pytorch/torch/_dynamo/eval_frame.py:410, in _TorchDynamoContext.__call__.<locals>._fn(*args, **kwargs)
    408 prior = set_eval_frame(callback)
    409 try:
--> 410     return fn(*args, **kwargs)
    411 finally:
    412     set_eval_frame(prior)

File /data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py:939, in catch_errors_wrapper.<locals>.catch_errors(frame, cache_entry, frame_state)
    935             return hijacked_callback(frame, cache_entry, hooks, frame_state)
    937 with compile_lock, _disable_current_modes():
    938     # skip=1: skip this frame
--> 939     return callback(frame, cache_entry, hooks, frame_state, skip=1)

File /data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py:802, in convert_frame.<locals>._convert_frame(frame, cache_entry, hooks, frame_state, skip)
    800 counters["frames"]["total"] += 1
    801 try:
--> 802     result = inner_convert(
    803         frame, cache_entry, hooks, frame_state, skip=skip + 1
    804     )
    805     counters["frames"]["ok"] += 1
    806     return result

File /data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py:400, in convert_frame_assert.<locals>._convert_frame_assert(frame, cache_entry, hooks, frame_state, skip)
    386 compile_id = CompileId(frame_id, frame_compile_id)
    388 signpost_event(
    389     "dynamo",
    390     "_convert_frame_assert._compile",
   (...)
    397     },
    398 )
--> 400 return _compile(
    401     frame.f_code,
    402     frame.f_globals,
    403     frame.f_locals,
    404     frame.f_builtins,
    405     compiler_fn,
    406     one_graph,
    407     export,
    408     export_constraints,
    409     hooks,
    410     cache_size,
    411     frame,
    412     frame_state=frame_state,
    413     compile_id=compile_id,
    414     skip=skip + 1,
    415 )

File ~/.conda/envs/pytorch-3.8/lib/python3.8/contextlib.py:75, in ContextDecorator.__call__.<locals>.inner(*args, **kwds)
     72 @wraps(func)
     73 def inner(*args, **kwds):
     74     with self._recreate_cm():
---> 75         return func(*args, **kwds)

File /data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py:686, in _compile(code, globals, locals, builtins, compiler_fn, one_graph, export, export_constraints, hooks, cache_size, frame, frame_state, compile_id, skip)
    684 fail_user_frame_lineno: Optional[int] = None
    685 try:
--> 686     guarded_code = compile_inner(code, one_graph, hooks, transform)
    687     return guarded_code
    688 except (
    689     Unsupported,
    690     TorchRuntimeError,
   (...)
    697     BisectValidationException,
    698 ) as e:

File /data/users/janeyx/pytorch/torch/_dynamo/utils.py:265, in dynamo_timed.<locals>.dynamo_timed_inner.<locals>.time_wrapper(*args, **kwargs)
    263 with torch.profiler.record_function(f"{key} (dynamo_timed)"):
    264     t0 = time.time()
--> 265     r = func(*args, **kwargs)
    266     time_spent = time.time() - t0
    267 compilation_time_metrics[key].append(time_spent)

File /data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py:541, in _compile.<locals>.compile_inner(code, one_graph, hooks, transform)
    539 CompileContext.get().attempt = attempt
    540 try:
--> 541     out_code = transform_code_object(code, transform)
    542     break
    543 except exc.RestartAnalysis as e:

File /data/users/janeyx/pytorch/torch/_dynamo/bytecode_transformation.py:1078, in transform_code_object(code, transformations, safe)
   1075 instructions = cleaned_instructions(code, safe)
   1076 propagate_line_nums(instructions)
-> 1078 transformations(instructions, code_options)
   1079 return clean_and_assemble_instructions(instructions, keys, code_options)[1]

File /data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py:165, in preserve_global_state.<locals>._fn(*args, **kwargs)
    163 cleanup = setup_compile_debug()
    164 try:
--> 165     return fn(*args, **kwargs)
    166 finally:
    167     cleanup.close()

File /data/users/janeyx/pytorch/torch/_dynamo/convert_frame.py:503, in _compile.<locals>.transform(instructions, code_options)
    501 try:
    502     with tracing(tracer.output.tracing_context), tracer.set_current_tx():
--> 503         tracer.run()
    504 except exc.UnspecializeRestartAnalysis:
    505     speculation_log.clear()

File /data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py:2202, in InstructionTranslator.run(self)
   2201 def run(self):
-> 2202     super().run()

File /data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py:843, in InstructionTranslatorBase.run(self)
    841 try:
    842     self.output.push_tx(self)
--> 843     while self.step():
    844         pass
    845 except BackendCompilerFailed:

File /data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py:757, in InstructionTranslatorBase.step(self)
    754 self.update_block_stack(inst)
    756 try:
--> 757     self.dispatch_table[inst.opcode](self, inst)
    758     return not self.output.should_exit
    759 except ReturnValueOp:

File /data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py:479, in break_graph_if_unsupported.<locals>.decorator.<locals>.wrapper(self, inst)
    477 if speculation.failed:
    478     assert speculation.reason is not None
--> 479     return handle_graph_break(self, inst, speculation.reason)
    480 try:
    481     return inner_fn(self, inst)

File /data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py:597, in break_graph_if_unsupported.<locals>.decorator.<locals>.handle_graph_break(self, inst, reason)
    594 for _ in range(push):
    595     self.push(UnknownVariable())
    596 self.output.add_output_instructions(
--> 597     self.create_call_resume_at(self.next_instruction)
    598 )

File /data/users/janeyx/pytorch/torch/_dynamo/symbolic_convert.py:2266, in InstructionTranslator.create_call_resume_at(self, inst)
   2262 nargs = stack_len + len(argnames)
   2264 name = unique_id(f"__resume_at_{inst.offset}")
-> 2266 new_code: types.CodeType = ContinueExecutionCache.lookup(
   2267     self.f_code,
   2268     self.lineno,
   2269     inst.offset,
   2270     tuple(b.target.offset for b in self.block_stack),
   2271     stack_len,
   2272     argnames,
   2273     tuple(b.resume_fn() for b in self.block_stack),
   2274     tuple(null_idxes),
   2275 )
   2277 # Add original GraphModule context to the resume function to handle
   2278 # the case of a graph break while tracing a GraphModule
   2279 orig_graphmodule_maybe = code_context.get_context(self.f_code).get(
   2280     "orig_graphmodule", lambda: None
   2281 )()

File /data/users/janeyx/pytorch/torch/_dynamo/resume_execution.py:330, in ContinueExecutionCache.lookup(cls, code, lineno, *key)
    328 key = tuple(key)
    329 if key not in cls.cache[code]:
--> 330     cls.cache[code][key] = cls.generate(code, lineno, *key)
    331 return cls.cache[code][key]

File /data/users/janeyx/pytorch/torch/_dynamo/resume_execution.py:476, in ContinueExecutionCache.generate(cls, code, lineno, offset, setup_fn_target_offsets, nstack, argnames, setup_fns, null_idxes)
    473     # TODO(jansel): add dead code elimination here
    474     instructions[:] = prefix + instructions
--> 476 new_code = transform_code_object(code, update)
    477 ContinueExecutionCache.generated_code_metadata[new_code] = meta
    478 return new_code

File /data/users/janeyx/pytorch/torch/_dynamo/bytecode_transformation.py:1079, in transform_code_object(code, transformations, safe)
   1076 propagate_line_nums(instructions)
   1078 transformations(instructions, code_options)
-> 1079 return clean_and_assemble_instructions(instructions, keys, code_options)[1]

File /data/users/janeyx/pytorch/torch/_dynamo/bytecode_transformation.py:1111, in clean_and_assemble_instructions(instructions, keys, code_options)
   1108     code_options["co_linetable"] = lnotab
   1110 code_options["co_code"] = bytecode
-> 1111 code_options["co_stacksize"] = stacksize_analysis(instructions)
   1112 assert set(keys) - {"co_posonlyargcount"} == set(code_options.keys()) - {
   1113     "co_posonlyargcount"
   1114 }
   1115 if sys.version_info >= (3, 11):

File /data/users/janeyx/pytorch/torch/_dynamo/bytecode_analysis.py:250, in stacksize_analysis(instructions)
    247 low = min([x.low for x in stack_sizes.values()])
    248 high = max([x.high for x in stack_sizes.values()])
--> 250 assert fixed_point.value, "failed to reach fixed point"
    251 assert low >= 0
    252 return high

AssertionError: failed to reach fixed point

from user code:
   File "<ipython-input-12-91c6d46fbdfc>", line 7, in f
    x = deepcopy(g)

Set TORCH_LOGS="+dynamo" and TORCHDYNAMO_VERBOSE=1 for more information


You can suppress this exception and fall back to eager by setting:
    import torch._dynamo
    torch._dynamo.config.suppress_errors = True
```

**Closed** 2024-04-16 08:36 UTC
Labels: triaged, oncall: pt2, module: dynamo
