### ISSUE TITLE
pad_packed_sequence in rrn valueError: result of slicing is an empty tensor

### ISSUE THREAD

**Issue by jpilaul** [pytorch/pytorch#4757] opened 2018-01-20 04:05 UTC
hey, I just downloaded latest torch package (pip3 install http://download.pytorch.org/whl/cu80/torch-0.3.0.post4-cp36-cp36m-linux_x86_64.whl) for python 3.6 and got the following error:

`File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/u/pilaultj/Projects/enc_summary/gensen.py", line 60, in forward
    h, h_t = self.encoder(src_emb)
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/nn/modules/rnn.py", line 169, in forward
    output, hidden = func(input, self.all_weights, hx)
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 387, in forward
    return func(input, *fargs, **fkwargs)
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 247, in forward
    nexth, output = func(input, hidden, weight)
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 85, in forward
    hy, output = inner(input, hidden[l], weight[l])
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/nn/_functions/rnn.py", line 148, in forward
    step_input = input[input_offset:input_offset + batch_size]
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/autograd/variable.py", line 78, in __getitem__
    return Index.apply(self, key)
  File "/u/pilaultj/.conda/envs/myenv/lib/python3.6/site-packages/torch/autograd/_functions/tensor.py", line 89, in forward
    result = i.index(ctx.index)
ValueError: result of slicing is an empty tensor`

The error was odd because I had tested the code on the previous pytorch package on python 3.6 and had gotten no errors... to debug, I added in rnn.py print statements for `input` and `len(batch_sizes)`  before ` step_input = input[input_offset:input_offset + batch_size]`

This is what I get with the latest release:
`Variable containing:
 6.4042e-03  4.6973e-03  2.0913e-03  ...  -7.4448e-02  4.2790e-03  7.9663e-02
 6.4042e-03  4.6973e-03  2.0913e-03  ...  -7.4448e-02  4.2790e-03  7.9663e-02
 6.4042e-03  4.6973e-03  2.0913e-03  ...  -7.4448e-02  4.2790e-03  7.9663e-02
                ...                   ⋱                   ...                
-3.3624e-02 -2.8784e-02  4.7878e-02  ...   8.0091e-02  1.3992e-02 -4.7688e-02
-2.0559e-02  1.9310e-01 -9.8036e-03  ...   9.4705e-02  6.7008e-02 -1.3937e-01
-3.3624e-02 -2.8784e-02  4.7878e-02  ...   8.0091e-02  1.3992e-02 -4.7688e-02
[torch.FloatTensor of size 12347x512]

293`

This is what I get with the prior release:
`Variable containing:
 6.4042e-03  4.6973e-03  2.0913e-03  ...  -7.4448e-02  4.2790e-03  7.9663e-02
 6.4042e-03  4.6973e-03  2.0913e-03  ...  -7.4448e-02  4.2790e-03  7.9663e-02
 6.4042e-03  4.6973e-03  2.0913e-03  ...  -7.4448e-02  4.2790e-03  7.9663e-02
                ...                   ⋱                   ...                
-3.3624e-02 -2.8784e-02  4.7878e-02  ...   8.0091e-02  1.3991e-02 -4.7688e-02
-2.0559e-02  1.9310e-01 -9.8036e-03  ...   9.4705e-02  6.7008e-02 -1.3937e-01
-3.3624e-02 -2.8784e-02  4.7878e-02  ...   8.0091e-02  1.3991e-02 -4.7688e-02
[torch.FloatTensor of size 12347x512]

250`

The batch_sizes are different (293 vs 250) from the 2 versions and it is creating errors. My previous version of torch was 0.2.0_3
Thanks

**Comment by zou3519** [comment] 2018-01-25 20:40
@jpilaul do you have a script we could run to reproduce the error?

**Comment by jpilaul** [comment] 2018-02-10 17:21
It's actually related to my seq_lengths vector in torch.nn.utils.rnn.pack_padded_sequence(batch_in, seq_lengths, batch_first=True). If batch_in is of size batch_size x max_sequence_length x embedding_dimension, we need max(seq_lengths) = max_sequence_length. In the previous version, I didn't get error when max(seq_lengths) > max_sequence_length. In this update, I am getting the error that I have explained above. So, to conclude it is not related to the RNN but to the length vector.

**Comment by timbmg** [comment] 2018-02-17 19:10
Is this confirmed to be a bug in the current version? @jpilaul did you find a workaround?

**Comment by mcjoshi** [comment] 2018-04-17 19:49
I also had the same problem with 0.3.0 and was fixed when i downgraded to 0.2.0

**Comment by jpilaul** [comment] 2018-04-17 20:04
@timbmg sorry for such a late reply. The workaround that I found was just to make sure that the seq_lengths were exactly the same as in my tensor.

**Comment by mruberry** [comment] 2020-07-31 21:42
Closing due to age. If you're still experiencing a similar issue on a recent version of PyTorch then please update and reopen this issue.

**Closed by mruberry** 2020-07-31 21:42 UTC
