### ISSUE TITLE
Allow zero channels

### ISSUE THREAD

**Issue by jw3126** [pytorch/pytorch#58984] opened 2021-05-26 09:52 UTC
## 🚀 Feature
Currenly most or all layers throw an error, when instantiating them with zero input or output channels:
```python
import torch.nn
torch.nn.Conv2d(in_channels=1,out_channels=0,kernel_size=(2,2))
# IndexError: index 0 is out of bounds for dimension 0 with size 0
```
The proposal is, to allow having 0 input or output channels. I think from the math point of view there is a single natural definition of how these layers should act.

## Motivation

While layers with 0 input or output channels do something trivial, they can be useful for writing more generic code. A bit like it was useful to allow 0 as an actual number centuries ago, even if it is "trivial".
My personal use case is something like this. I have a net that takes multiple input tensors. For prototyping/debugging I want to be able to conveniently disable one of these inputs say. Feeding 0 input channels would be a slick way to do this.

cc @albanD @mruberry @jbschlosser

**Comment by jbschlosser** [comment] 2021-05-26 15:39
Hey @jw3126, thanks for the suggestion! This was added for `nn.Linear` in #56505, and support for `hidden_size=0` in RNNs was requested in #56767.

Given that, it looks like support for the various convolutional layers would be the main gap- are there others I'm missing?

**Comment by ngimel** [comment] 2021-05-26 16:11
Duplicate of #56998

**Comment by jw3126** [comment] 2021-05-26 17:57
> Are there other modules you're thinking of that I'm missing or would the above cover them?
Personally, I am was thinking of `Linear`, `ConvND` and `ConvTransposeND`. But I would expect that there are more.

**Comment by jbschlosser** [comment] 2021-05-27 15:35
> Personally, I am was thinking of `Linear`, `ConvND` and `ConvTransposeND`. But I would expect that there are more.

Closing for now as covered by the aforementioned issues but feel free to reopen for specific other modules.

**Closed by jbschlosser** 2021-05-27 15:35 UTC
Labels: module: nn, triaged
