### ISSUE TITLE
torch.max always returns zero on MPS

### ISSUE THREAD

**Issue by jscant** [pytorch/pytorch#90273] opened 2022-12-06 11:01 UTC
### 🐛 Describe the bug
EDIT: The bug in fact appears to be that max always returns the first value, rather than always zero.

This also has implications for libraries such as torch_scatter, as this uses max to find the number of items in a batch. I can find a workaround for the moment, but seems to be a pretty important issue (unless I'm missing something obvious!).
```
>>> import torch
>>> a = torch.Tensor([0, 1, 2, 3, 4]).long().to('cpu')
>>> b = torch.Tensor([0, 1, 2, 3, 4]).long().to('mps')
>>> torch.max(a)
tensor(4)
>>> torch.max(b)
tensor(0, device='mps:0')
```

### Versions

```
Collecting environment information...
PyTorch version: 1.13.0
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 13.0 (arm64)
GCC version: Could not collect
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.24.3
Libc version: N/A

Python version: 3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:52:10)  [Clang 14.0.6 ] (64-bit runtime)
Python platform: macOS-13.0-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] egnn-pytorch==0.2.6
[pip3] numpy==1.22.4
[pip3] torch==1.13.0
[pip3] torch-cluster==1.6.0
[pip3] torch-geometric==2.2.0
[pip3] torch-scatter==2.1.0
[pip3] torch-sparse==0.6.15
[pip3] torch-spline-conv==1.2.1
[pip3] torchaudio==0.13.0
[pip3] torchvision==0.14.0
[conda] egnn-pytorch              0.2.6                    pypi_0    pypi
[conda] numpy                     1.22.4                   pypi_0    pypi
[conda] pytorch                   1.13.0                  py3.9_0    pytorch
[conda] torch-cluster             1.6.0                    pypi_0    pypi
[conda] torch-geometric           2.2.0                    pypi_0    pypi
[conda] torch-scatter             2.1.0                    pypi_0    pypi
[conda] torch-sparse              0.6.15                    dev_0    <develop>
[conda] torch-spline-conv         1.2.1                    pypi_0    pypi
[conda] torchaudio                0.13.0                 py39_cpu    pytorch
[conda] torchvision               0.14.0                 py39_cpu    pytorch
```

cc @kulinseth @albanD @malfet @DenisVieriu97 @razarmehr @abhudev

**Comment by jscant** [comment] 2022-12-06 11:25
Oddly it's only for long tensors, not floats.

**Comment by jscant** [comment] 2022-12-06 11:33
> 

I'm trying to get set up with the nightly build but it doesn't help that the instructions don't work for me:
```
conda create -n torch14 pytorch torchvision torchaudio -c pytorch-nightly
```
On M1 Mac (13.0) leads to:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: / 
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                                                                                                                                                                                     

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package pytorch conflicts for:
torchaudio -> pytorch==1.14.0.dev20221022
pytorch
torchvision -> pytorch[version='1.10.2|1.14.0.dev20221022']

Package typing_extensions conflicts for:
pytorch -> typing-extensions -> typing_extensions[version='3.10.0.0|3.10.0.2|4.1.1|4.3.0|4.3.0|4.3.0|4.4.0|3.7.4.3|3.7.4.3|3.7.4.2',build='pyh06a4308_0|pyh06a4308_0|pyh06a4308_0|py310hca03da5_0|py38hca03da5_0|py310hca03da5_0|py38hca03da5_0|py39hca03da5_0|py39hca03da5_0|pyh06a4308_0|py_0|py_0']
pytorch -> typing_extensions

Package llvm-openmp conflicts for:
torchvision -> pytorch -> llvm-openmp[version='>=12.0.0|>=14.0.6']
pytorch -> llvm-openmp[version='>=12.0.0|>=14.0.6']
```

**Comment by jscant** [comment] 2022-12-06 11:37
```
>>> import torch
>>> torch.__version__
'1.14.0.dev20221206'
>>> a = torch.Tensor([0, 1, 2, 3, 4]).long().to('cpu')
>>> b = torch.Tensor([0, 1, 2, 3, 4]).long().to('mps')
>>> torch.max(a)
tensor(4)
>>> torch.max(b)
tensor(0, device='mps:0')
```
Still happening for me.

**Comment by jscant** [comment] 2022-12-06 11:41
Seems to be a problem with 64-bit integers:
```
>>> c = torch.tensor([0, 1, 2, 3, 4], dtype=torch.int).to('mps')
>>> torch.max(c)
tensor(4, device='mps:0', dtype=torch.int32)
```

**Comment by qqaatw** [comment] 2022-12-06 12:48
I'm not seeing an issue with long tensors as well per the code snippet provided. Weird indeed.

**Comment by qqaatw** [comment] 2022-12-13 11:28
I guess this is probably a bug only in macOS 13+. On macOS `12.6.1` there is no problem with `torch.max`.

**Comment by orrp** [comment] 2022-12-22 17:36
This issue reproduces for me on M1 Max, Ventura 13.1:

```
>>> torch.__version__
'2.0.0.dev20221220'
>>> a = torch.randint(100, (3,), dtype=torch.int64, device=torch.device('mps'))
>>> a
tensor([27, 55,  2], device='mps:0')
>>> a.max()
tensor(27, device='mps:0')
```

**Comment by DenisVieriu97** [comment] 2022-12-24 11:25
Hi @jscant. Thanks for filing this issue - reduction ops (including min/max) don't have support for int64 at this moment in the MPS backend. I have checked internally with the team and I will let you know once I have an update.  
For now, it will throw an error whenever int64 is passed to min/max ops (please see https://github.com/pytorch/pytorch/pull/91272).

**Comment by orrp** [comment] 2022-12-24 17:34
Thanks, @DenisVieriu97 ! Any clue why `int64` is currently not supported? I'm asking this because if the issue is deep and may take a while to fix, I will switch my project over to CUDA; but if it is a small thing, I will try to work around it for now.

**Comment by KyleMylonakisProtopia** [comment] 2023-02-08 13:24
I am experiencing the same issue with an M2 Macbook air on macOS 13.2 with PyTorch 1.13.1. 
I think I saw that there is now commit to main which should at least protect against this behavior. 

What release is this commit slated for? 

This bug caused me hours of debugging the other day and causes me to significantly distrust any results generated by Pytorch when using an MPS device.

**Comment by malfet** [comment] 2023-02-08 17:46
@KyleMylonakisProtopia this has been part of nightly release for a while and will be part of the upcoming 2.0 release. 
But yes, op should have thrown error rather than return a silently incorrect results, but this looks like a bug in MetalPerformanceShaders framework.

**Comment by malfet** [comment] 2023-02-08 17:46
Closing the issue as "fixed" by https://github.com/pytorch/pytorch/commit/bdbf188c804c7efe367e710e355342f67077f941 (nightly build will throw an error right now)

**Closed by malfet** 2023-02-08 17:46 UTC
Labels: triaged, module: correctness (silent), module: mps
