### ISSUE TITLE
[primTorch] `test_python_ref_executor` often fails due to concrete arg mismatch

### ISSUE THREAD

**Issue by mruberry** [pytorch/pytorch#79818] opened 2022-06-17 22:38 UTC
See the many xfails in common_methods_invocations, like:

```
PythonRefInfo(
        "_refs.chunk",
        torch_opinfo_name="chunk",
        skips=(
            # RuntimeError: Tracing expected 3 arguments but got 2 concrete arguments
            DecorateInfo(unittest.expectedFailure, 'TestCommon', 'test_python_ref_executor'),
        ),
    ),
```

cc @ezyang @gchanan @zou3519 @mruberry @ngimel @Chillee

**Comment by ezyang** [comment] 2022-06-25 03:14
@mruberry I recommend cc'ing the person who wrote the test, in this case, @IvanYashchuk 

Is this a dupe of https://github.com/pytorch/pytorch/issues/78923 >

**Comment by IvanYashchuk** [comment] 2022-06-25 09:22
Yes, those xfails were removed in https://github.com/pytorch/pytorch/pull/79858.

**Closed by IvanYashchuk** 2022-06-25 09:22 UTC
Labels: high priority, triaged, module: primTorch
