### ISSUE TITLE
Documentation for torch.nn.RNN contains an INACCURATE code snippet

### ISSUE THREAD

**Issue by Datarian723** [pytorch/pytorch#138401] opened 2024-10-19 22:22 UTC
### 📚 The doc issue

ProblematicLink: https://pytorch.org/docs/stable/generated/torch.nn.RNN.html
Issue: Right below the class header information, there is a code snippet, starting with the following comment: "# Efficient implementation equivalent to the following with bidirectional=False". The code supposedly intends to sketch an implementation of non-bidirectional stacked RNNs but an error is present in the update logic for hidden states. More specifically, the following code block from line11 to line17: 
"""       
 for layer in range(num_layers):
            h_t[layer] = torch.tanh(
                x[t] @ weight_ih[layer].T
                + bias_ih[layer]
                + h_t_minus_1[layer] @ weight_hh[layer].T
                + bias_hh[layer]
            )
"""

### Suggest a potential alternative/fix

(1)Issue identified
In the pasted code block, update logic for h_t[layer] relies on the vertical information flow:
input_to_hidden[t, layer] <- x[t] @ weight_ih[layer].T + bias_ih[layer].
This is inaccurate, since even when layer > 0, it still accepts x[t] as inputs, rather than (hidden)outputs from the previous layer(i.e. h_t[layer-1])

(2)Fix
At each layer, introduce a new variable 'input': input = x[t] if layer == 0 else h_t[layer-1]
Then, we can simply feed 'input' into the update equation: input @ weight_ih[layer].T + bias_ih[layer]
Here's the entire code block, modified:
"""
        for layer in range(num_layers):
            input = x[t] if layer == 0 else h_t[layer-1]
            h_t[layer] = torch.tanh(
                input @ weight_ih[layer].T 
                + bias_ih[layer]
                + h_t_minus_1[layer] @ weight_hh[layer].T
                + bias_hh[layer]
            )
"""

cc @svekars @brycebortree @sekyondaMeta @albanD @mruberry @jbschlosser @walterddr @mikaylagawarecki

**Comment by DeeExe** [comment] 2024-10-31 07:28
cool, I will try to work on that.

**Comment by mikaylagawarecki** [comment] 2024-11-21 20:43
Thanks! Closing as this reports issue that is duplicate of https://github.com/pytorch/pytorch/issues/138401 and https://github.com/pytorch/pytorch/issues/136926

There is a PR open to fix this https://github.com/pytorch/pytorch/pull/136971, will work towards merging that one

**Closed by mikaylagawarecki** 2024-11-21 20:43 UTC
Labels: module: docs, module: nn, module: rnn, triaged, actionable
