### ISSUE TITLE
BN layer does not update the parameters 

### ISSUE THREAD

**Issue by w1005444804** [pytorch/pytorch#53002] opened 2021-03-01 07:44 UTC
## 🐛 Bug

using the Topology of CSPDarknet53 , the bn of ResBlock does not update its parameters. for example: I using CSPDarknet53 for classify mnist data, then look the bn parameters (no update)

 - LibTorch Version 1.6, cuda10.2):
 - OS (windows):

```
## Additional context
`#pragma once
#include <torch/torch.h>

torch::nn::Conv2d conv3x3(
	int64_t in,
	int64_t out,
	int64_t stride = 1,
	int64_t groups = 1) {
	torch::nn::Conv2dOptions O(in, out, 3);
	O.padding(1).stride(stride).groups(groups).bias(false);
	return torch::nn::Conv2d(O);
}

torch::nn::ConvTranspose2d deconv4x4(
	int64_t in,
	int64_t out,
	int64_t groups = 1) {
	torch::nn::ConvTranspose2dOptions O(in, out, 4);
	O.padding(1).stride(2).groups(groups).bias(false);
	return torch::nn::ConvTranspose2d(O);
}

torch::nn::Conv2d conv1x1(int64_t in, int64_t out, int64_t stride = 1) {
	torch::nn::Conv2dOptions O(in, out, 1);
	O.stride(stride).bias(false);
	return torch::nn::Conv2d(O);
}

void print_tensor_shape(torch::Tensor tensor) {
	std::cout << "shape:  ";
	for (size_t i = 0; i < tensor.dim(); i++) {
		std::cout << tensor.size(i) << " ";
	}
	std::cout << std::endl;
}
// for change2caffe prototxt, then using deconv not upsample in tensorRT.
struct UpsampleX2 : torch::nn::Module {
	UpsampleX2(const int in) {
		deconv = deconv4x4(in, in);
		bn = torch::nn::BatchNorm2d(in);
		register_module("deconv", deconv);
		register_module("bn", bn);
	}
	torch::Tensor forward(torch::Tensor x) {
		//x = torch::upsample_nearest2d(x, { x.size(2) * 2, x.size(3) * 2 });
		x = deconv->forward(x);
		x = bn->forward(x).relu_();
		return x;
	}

private:
	torch::nn::ConvTranspose2d deconv{ nullptr };
	torch::nn::BatchNorm2d bn{ nullptr };
};
struct DBL : torch::nn::Module {
	DBL(int64_t in, int64_t out, int64_t kernel_size, int64_t stride = 1) {
		if (kernel_size > 1) {
			conv = conv3x3(in, out, stride);
		}
		else {
			conv = conv1x1(in, out, stride);
		}
		bn = torch::nn::BatchNorm2d(out);

		register_module("conv", conv);
		register_module("bn", bn);
	}
	torch::Tensor forward(torch::Tensor x) {
		//print_tensor_shape(x);
		x = conv->forward(x);
		x = bn->forward(x).relu_();
		return x;
	}

private:
	torch::nn::Conv2d conv{ nullptr };
	torch::nn::BatchNorm2d bn{ nullptr };
};

struct DBM : torch::nn::Module {
	DBM(int64_t in, int64_t out, int64_t kernel_size, int64_t stride = 1) {
		if (kernel_size > 1) {
			conv = conv3x3(in, out, stride);
		}
		else {
			conv = conv1x1(in, out, stride);
		}
		bn = torch::nn::BatchNorm2d(out);

		register_module("conv", conv);
		register_module("bn", bn);
	}
	torch::Tensor forward(torch::Tensor x) {
		x = conv->forward(x);
		x = bn->forward(x);
		x = x.mul(torch::softplus(x).tanh());
		return x;
	}

private:
	torch::nn::Conv2d conv{ nullptr };
	torch::nn::BatchNorm2d bn{ nullptr };
};

struct BasicResBlock : torch::nn::Module {
	BasicResBlock(int in, int out, int group, bool dilation = false) {
		cbr1->push_back(DBL(in, out, 1));
		cbr2->push_back(DBL(out, out, 3));
		/* register */
		register_module("cbr1", cbr1);
		register_module("cbr2", cbr2);
	}
	torch::Tensor forward(torch::Tensor x) {
		/* base */
		auto identity = x;
		auto out = cbr1->forward(x);
		out = cbr2->forward(out);
		out += identity;
		return out;
	}

private:
	torch::nn::Sequential cbr1, cbr2;
};

struct CSP_ResBlock_Body : torch::nn::Module {
	CSP_ResBlock_Body(int in, int out, int res_unit_num) {
		downDBL->push_back(DBL(in, out, 3, 2));
		ResBlocks->push_back(DBL(out, out, 3));
		for (size_t i = 0; i < res_unit_num; i++) {
			ResBlocks->push_back(BasicResBlock(out, out, 1));
		}
		ResBlocks->push_back(DBL(out, out, 3));
		DBL1->push_back(DBL(out, out, 1));
		DBL2->push_back(DBL(out * 2, out, 1));
		/* register */
		register_module("downDBL", downDBL);
		register_module("DBL1", DBL1);
		register_module("DBL2", DBL2);
		register_module("ResBlocks", ResBlocks);
	}

	torch::Tensor forward(torch::Tensor x) {
		/* base */
		x = downDBL->forward(x);

		auto out1 = DBL1->forward(x);
		auto out2 = ResBlocks->forward(x);

		auto y = torch::cat({ out1, out2 }, 1);
		y = DBL2->forward(y);
		return x;
	}

private:
	torch::nn::Sequential ResBlocks, downDBL, DBL1, DBL2;
};

struct DBLS : torch::nn::Module {
	DBLS(int in, int unit_num) {
		assert(unit_num % 2 == 1);
		int temp_in = in;
		int temp_out;
		for (size_t i = 0; i < unit_num; i++) {
			if (i % 2 == 0) {
				temp_out = temp_in / 2;
				DBLSBlocks->push_back(DBL(temp_in, temp_out, 1));
			}
			else {
				temp_out = temp_in * 2;
				DBLSBlocks->push_back(DBL(temp_in, temp_out, 3));
			}
			temp_in = temp_out;
		}
		register_module("DBLSBlocks", DBLSBlocks);
	}
	torch::Tensor forward(torch::Tensor x) {
		return DBLSBlocks->forward(x);
	}
private:
	torch::nn::Sequential DBLSBlocks;
};

struct SPP : torch::nn::Module {
	torch::Tensor forward(torch::Tensor x) {
		auto out1 = torch::avg_pool2d(x, 5, 1, 2);
		auto out2 = torch::avg_pool2d(x, 9, 1, 4);
		auto out3 = torch::avg_pool2d(x, 13, 1, 6);
		return torch::cat({ x, out1, out2 ,out3 }, 1);
	}
};

struct YOLOV4 : torch::nn::Module {
	YOLOV4(int in, const std::vector<int64_t> configx, int ANCHORNUM = 3, int CLASSNUM = 0) :
		config(configx) {
		//DBM1->push_back(DBM(3, config[0], 3));
		DBM1->push_back(DBL(3, config[0], 3));

		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[0], config[1], 1));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[1], config[2], 2));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[2], config[3], 8));// xout_shape_c
		CSPDarkNet8->push_back(CSP_ResBlock_Body(config[3], config[4], 8));// yout_shape_c
		CSPDarkNet4->push_back(CSP_ResBlock_Body(config[4], config[5], 4));
		CSPDarkNet4->push_back(DBLS(config[5], 3));//out->config[4]
		CSPDarkNet4->push_back(SPP());// out:4xin
		CSPDarkNet4->push_back(DBL(4 * config[4], config[4], 1));// zout_shape_c//UpsampleX2
		CSPDarkNet4->push_back(DBL(config[4], config[5], 3));
		CSPDarkNet4->push_back(DBL(config[5], config[4], 1));//out->config[4]

		DBL2->push_back(DBL(config[4], config[3], 1));
		DBL3->push_back(DBL(config[4], config[3], 1));
		//DBL3->push_back(deconv4x4(config[3], config[3]));//'upsample1'// xout_shape_c
		DBL3->push_back(UpsampleX2(config[3]));//'upsample1'// xout_shape_c
		//concat{DBL2_out,DBL3_out}
		DBL4->push_back(DBLS(config[4], 5));//out->config[3]

		DBL1->push_back(DBL(config[3], config[2], 1));// xout_shape_c
		DBL5->push_back(DBL(config[3], config[2], 1));
		DBL5->push_back(UpsampleX2(config[2]));//'upsample2'
		//DBL5->push_back(UpsampleX2());//'upsample2'
		//concat{DBL1_out,DBL5_out}

		DBL6->push_back(DBLS(config[3], 5));//out->config[2]--->out1
		DBL7->push_back(DBL(config[2], config[3], 3, 2));
		//concat{DBL7_out,DBL4_out}

		DBL8->push_back(DBLS(config[4], 5));//out->config[3]--->out2
		DBL9->push_back(DBL(config[3], config[4], 3, 2));
		//concat{DBL9_out,CSPDarkNet4_out}
		DBL10->push_back(DBLS(config[4] * 2, 5)); //out->config[4]

		DBLout1->push_back(DBL(config[2], config[2], 1));
		DBLout2->push_back(DBL(config[3], config[3], 1));
		DBLout3->push_back(DBL(config[4], config[4], 1));

		convout1 = conv1x1(config[2], ANCHORNUM * (1 + 4 + CLASSNUM));
		convout2 = conv1x1(config[3], ANCHORNUM * (1 + 4 + CLASSNUM));
		convout3 = conv1x1(config[4], ANCHORNUM * (1 + 4 + CLASSNUM));


		register_module("DBM1", DBM1);
		register_module("CSPDarkNet11", CSPDarkNet11);
		register_module("CSPDarkNet8", CSPDarkNet8);
		register_module("CSPDarkNet4", CSPDarkNet4);
		register_module("convout1", convout1);
		register_module("convout2", convout2);
		register_module("convout3", convout3);

		register_module("DBL1", DBL1);
		register_module("DBL2", DBL2);
		register_module("DBL3", DBL3);
		register_module("DBL4", DBL4);
		register_module("DBL5", DBL5);
		register_module("DBL6", DBL6);
		register_module("DBL7", DBL7);
		register_module("DBL8", DBL8);
		register_module("DBL9", DBL9);
		register_module("DBL10", DBL10);
		register_module("DBLout1", DBLout1);
		register_module("DBLout2", DBLout2);
		register_module("DBLout3", DBLout3);
	}
	std::tuple<torch::Tensor, torch::Tensor, torch::Tensor> forward(torch::Tensor x) {
		x = DBM1->forward(x);
		x = CSPDarkNet11->forward(x);
		auto y = CSPDarkNet8->forward(x);
		auto z = CSPDarkNet4->forward(y);

		auto DBL3_out = DBL3->forward(z);
		auto DBL2_out = DBL2->forward(y);
		auto concat1th = torch::cat({ DBL3_out, DBL2_out }, 1);
		auto DBL4_out = DBL4->forward(concat1th);

		auto DBL5_out = DBL5->forward(DBL4_out);
		auto DBL1_out = DBL1->forward(x);
		auto concat2th = torch::cat({ DBL5_out, DBL1_out }, 1);
		auto DBL6_out = DBL6->forward(concat2th);

		auto DBL7_out = DBL7->forward(DBL6_out);
		auto concat3th = torch::cat({ DBL4_out, DBL7_out }, 1);
		auto DBL8_out = DBL8->forward(concat3th);

		auto DBL9_out = DBL9->forward(DBL8_out);
		auto concat4th = torch::cat({ DBL9_out, z }, 1);
		auto DBL10_out = DBL10->forward(concat4th);

		auto DBLout1_out = DBLout1->forward(DBL6_out);
		auto DBLout2_out = DBLout2->forward(DBL8_out);
		auto DBLout3_out = DBLout3->forward(DBL10_out);

		/*auto out1 = convout1(DBLout1_out).sigmoid_();
		auto out2 = convout2(DBLout2_out).sigmoid_();
		auto out3 = convout3(DBLout3_out).sigmoid_();*/
		auto out1 = convout1->forward(DBLout1_out).sigmoid_();
		auto out2 = convout2->forward(DBLout2_out).sigmoid_();
		auto out3 = convout3->forward(DBLout3_out).sigmoid_();
		return std::make_tuple(out1, out2, out3);
	}
private:
	std::vector<int64_t> config;
	torch::nn::Sequential CSPDarkNet11, CSPDarkNet8, CSPDarkNet4;
	torch::nn::Sequential DBM1;
	torch::nn::Sequential DBL1, DBL2, DBL3, DBL4, DBL5, DBL6, DBL7, DBL8, DBL9, DBL10,
		DBLout1, DBLout2, DBLout3;

	torch::nn::Conv2d convout1{ nullptr }, convout2{ nullptr }, convout3{ nullptr };
};

struct CSPDarknet53 : torch::nn::Module {
	CSPDarknet53(int in, const std::vector<int64_t> config): fc(100, 10) {
		DBM1->push_back(DBM(in, config[0], 3));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[0], config[1], 1));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[1], config[2], 2));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[2], config[3], 8));// xout_shape_c
		CSPDarkNet11->push_back(conv1x1(config[3], 100));
		CSPDarkNet8->push_back(CSP_ResBlock_Body(config[3], config[4], 8));// yout_shape_c
		CSPDarkNet4->push_back(CSP_ResBlock_Body(config[4], config[5], 4));
		CSPDarkNet4->push_back(DBL(config[5], config[4], 1));
		CSPDarkNet4->push_back(SPP());// out:4xin
		CSPDarkNet4->push_back(DBL(4 * config[4], config[4], 1));// zout_shape_c//UpsampleX2
		convout = conv1x1(config[3], 100);
		
		register_module("DBM1", DBM1);
		register_module("CSPDarkNet11", CSPDarkNet11);
		register_module("CSPDarkNet8", CSPDarkNet8);
		register_module("CSPDarkNet4", CSPDarkNet4);
		register_module("convout", convout);
		register_module("fc", fc);
	}
	torch::Tensor forward(torch::Tensor x) {
		x = DBM1->forward(x);
		x = CSPDarkNet11->forward(x);
		//auto y = CSPDarkNet8->forward(x);
		x = torch::adaptive_avg_pool2d(x, { 1,1 });
		//print_tensor_shape(x);
		x = x.view({ -1,x.size(1) });
		x = fc->forward(x);
		//print_tensor_shape(x);
		//auto z = CSPDarkNet4->forward(y);
		return torch::log_softmax(x, /*dim=*/1);
	}
private:
	torch::nn::Sequential DBM1, CSPDarkNet11, CSPDarkNet8, CSPDarkNet4;
	torch::nn::Conv2d convout = {nullptr};
	torch::nn::Linear fc;
};
```
`

![image](https://user-images.githubusercontent.com/6340026/109466145-38236100-7aa4-11eb-8409-aa5eb0c38ca6.png)

cc @yf225 @glaringlee

**Comment by H-Huang** [comment] 2021-03-01 19:51
If you could isolate this to a smaller piece of code that is reproducible, that would really help in debugging.

**Comment by glaringlee** [comment] 2021-03-01 21:14
@w1005444804 
Can you write a small program to test BatchNorm2d only? 
And your libtorch seems a bit old, can you use latest version? or you can use nightly build.

**Comment by w1005444804** [comment] 2021-03-02 05:53
@H-Huang @glaringlee thanks
code show as below， which tested on the mnist  , (libtorch 17.1), 
Parameter look like in some bn layers :
"CSPDarkNet11.2.ResBlocks.7.cbr2.0.bn.weight
    data: 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 
CSPDarkNet11.2.ResBlocks.7.cbr2.0.bn.bias
    data: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 "

`#include <torch/torch.h>

#include <cstddef>
#include <cstdio>
#include <iostream>
#include <string>
#include <vector>

using namespace torch::autograd;
// Where to find the MNIST dataset.
const char* kDataRoot = "E:/workspace/examples-master/data/MNIST";

// The batch size for training.
const int64_t kTrainBatchSize = 64;

// The batch size for testing.
const int64_t kTestBatchSize = 1000;

// The number of epochs to train.
const int64_t kNumberOfEpochs = 10;

// After how many batches to log a new update with the loss value.
const int64_t kLogInterval = 10;

template <
    typename Optimizer = torch::optim::Adam,
    typename OptimizerOptions = torch::optim::AdamOptions>
inline auto decay(Optimizer& optimizer, double rate) {
  for (auto& group : optimizer.param_groups()) {
    if (group.has_options()) {
      auto& options = static_cast<OptimizerOptions&>(group.options());
      options.lr(options.lr() * (1.0 - rate));
      std::cout << options.lr() << std::endl;
    }
  }
}

torch::nn::Conv2d conv3x3(
	int64_t in,
	int64_t out,
	int64_t stride = 1,
	int64_t groups = 1) {
	torch::nn::Conv2dOptions O(in, out, 3);
	O.padding(1).stride(stride).groups(groups).bias(false);
	return torch::nn::Conv2d(O);
}

torch::nn::ConvTranspose2d deconv4x4(
	int64_t in,
	int64_t out,
	int64_t groups = 1) {
	torch::nn::ConvTranspose2dOptions O(in, out, 4);
	O.padding(1).stride(2).groups(groups).bias(false);
	return torch::nn::ConvTranspose2d(O);
}

torch::nn::Conv2d conv1x1(int64_t in, int64_t out, int64_t stride = 1) {
	torch::nn::Conv2dOptions O(in, out, 1);
	O.stride(stride).bias(false);
	return torch::nn::Conv2d(O);
}

void print_tensor_shape(torch::Tensor tensor) {
	std::cout << "shape:  ";
	for (size_t i = 0; i < tensor.dim(); i++) {
		std::cout << tensor.size(i) << " ";
	}
	std::cout << std::endl;
}

struct DBL : torch::nn::Module {
	DBL(int64_t in, int64_t out, int64_t kernel_size, int64_t stride = 1) {
		if (kernel_size > 1) {
			conv = conv3x3(in, out, stride);
		}
		else {
			conv = conv1x1(in, out, stride);
		}
		bn = torch::nn::BatchNorm2d(out);

		register_module("conv", conv);
		register_module("bn", bn);
	}
	torch::Tensor forward(torch::Tensor x) {
		//print_tensor_shape(x);
		x = conv->forward(x);
		x = bn->forward(x);
		return x;
	}

private:
	torch::nn::Conv2d conv{ nullptr };
	torch::nn::BatchNorm2d bn{ nullptr };
};

struct DBM : torch::nn::Module {
	DBM(int64_t in, int64_t out, int64_t kernel_size, int64_t stride = 1) {
		if (kernel_size > 1) {
			conv = conv3x3(in, out, stride);
		}
		else {
			conv = conv1x1(in, out, stride);
		}
		bn = torch::nn::BatchNorm2d(out);

		register_module("conv", conv);
		register_module("bn", bn);
	}
	torch::Tensor forward(torch::Tensor x) {
		x = conv->forward(x);
		x = bn->forward(x);
		x = x.mul(torch::softplus(x).tanh());
		return x;
	}

private:
	torch::nn::Conv2d conv{ nullptr };
	torch::nn::BatchNorm2d bn{ nullptr };
};

struct BasicResBlock : torch::nn::Module {
	BasicResBlock(int in, int out, int group, bool dilation = false) {
		cbr1->push_back(DBL(in, out, 1));
		cbr2->push_back(DBL(out, out, 3));
		/* register */
		register_module("cbr1", cbr1);
		register_module("cbr2", cbr2);
	}
	torch::Tensor forward(torch::Tensor x) {
		/* base */
		auto identity = x;
		auto out = cbr1->forward(x);
		out = cbr2->forward(out);
		out += identity;
		return out;
	}

private:
	torch::nn::Sequential cbr1, cbr2;
};

struct CSP_ResBlock_Body : torch::nn::Module {
	CSP_ResBlock_Body(int in, int out, int res_unit_num) {
		downDBL->push_back(DBL(in, out, 3, 2));
		ResBlocks->push_back(DBL(out, out, 3));
		for (size_t i = 0; i < res_unit_num; i++) {
			ResBlocks->push_back(BasicResBlock(out, out, 1));
		}
		ResBlocks->push_back(DBL(out, out, 3));
		DBL1->push_back(DBL(out, out, 1));
		DBL2->push_back(DBL(out * 2, out, 1));
		/* register */
		register_module("downDBL", downDBL);
		register_module("DBL1", DBL1);
		register_module("DBL2", DBL2);
		register_module("ResBlocks", ResBlocks);
	}

	torch::Tensor forward(torch::Tensor x) {
		/* base */
		x = downDBL->forward(x);

		auto out1 = DBL1->forward(x);
		auto out2 = ResBlocks->forward(x);

		auto y = torch::cat({ out1, out2 }, 1);
		y = DBL2->forward(y);
		return x;
	}

private:
	torch::nn::Sequential ResBlocks, downDBL, DBL1, DBL2;
};

struct DBLS : torch::nn::Module {
	DBLS(int in, int unit_num) {
		assert(unit_num % 2 == 1);
		int temp_in = in;
		int temp_out;
		for (size_t i = 0; i < unit_num; i++) {
			if (i % 2 == 0) {
				temp_out = temp_in / 2;
				DBLSBlocks->push_back(DBL(temp_in, temp_out, 1));
			}
			else {
				temp_out = temp_in * 2;
				DBLSBlocks->push_back(DBL(temp_in, temp_out, 3));
			}
			temp_in = temp_out;
		}
		register_module("DBLSBlocks", DBLSBlocks);
	}
	torch::Tensor forward(torch::Tensor x) {
		return DBLSBlocks->forward(x);
	}
private:
	torch::nn::Sequential DBLSBlocks;
};

struct SPP : torch::nn::Module {
	torch::Tensor forward(torch::Tensor x) {
		auto out1 = torch::avg_pool2d(x, 5, 1, 2);
		auto out2 = torch::avg_pool2d(x, 9, 1, 4);
		auto out3 = torch::avg_pool2d(x, 13, 1, 6);
		return torch::cat({ x, out1, out2 ,out3 }, 1);
	}
};

struct Net : torch::nn::Module {
	Net(int in, const std::vector<int64_t> config) : fc(100, 10) {
		DBM1->push_back(DBM(in, config[0], 3));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[0], config[1], 1));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[1], config[2], 2));
		CSPDarkNet11->push_back(CSP_ResBlock_Body(config[2], config[3], 8));// xout_shape_c
		CSPDarkNet11->push_back(conv1x1(config[3], 100));
		convout = conv1x1(config[3], 100);

		register_module("DBM1", DBM1);
		register_module("CSPDarkNet11", CSPDarkNet11);
		register_module("convout", convout);
		register_module("fc", fc);
	}
	torch::Tensor forward(torch::Tensor x) {
		x = DBM1->forward(x);
		x = CSPDarkNet11->forward(x);
		//auto y = CSPDarkNet8->forward(x);
		x = torch::adaptive_avg_pool2d(x, { 1,1 });
		//print_tensor_shape(x);
		x = x.view({ -1,x.size(1) });
		x = fc->forward(x);
		//print_tensor_shape(x);
		//auto z = CSPDarkNet4->forward(y);
		return torch::log_softmax(x, /*dim=*/1);
	}
private:
	torch::nn::Sequential DBM1, CSPDarkNet11, CSPDarkNet8, CSPDarkNet4;
	torch::nn::Conv2d convout = { nullptr };
	torch::nn::Linear fc;
};

struct NetX : torch::nn::Module {
  NetX()
      : conv1(torch::nn::Conv2dOptions(1, 10, /*kernel_size=*/5)),
        conv2(torch::nn::Conv2dOptions(10, 20, /*kernel_size=*/5)),
        fc1(320, 50),
        fc2(50, 10) {

    register_module("conv1", conv1);
    register_module("conv2", conv2);
    //register_module("conv2_drop", conv2_drop);
    register_module("fc1", fc1);
    register_module("fc2", fc2);
  }

  torch::Tensor forward(torch::Tensor x) {
    x = torch::relu(torch::max_pool2d(conv1->forward(x), 2));
    x = torch::relu(
        torch::max_pool2d(torch::dropout(conv2->forward(x), 0.5, this->is_training()), 2));
    x = x.view({-1, 320});
    x = torch::relu(fc1->forward(x));
    x = torch::dropout(x, /*p=*/0.5, /*training=*/is_training());
    x = fc2->forward(x);
    return torch::log_softmax(x, /*dim=*/1);
  }

  torch::nn::Conv2d conv1;
  torch::nn::Conv2d conv2;
  
  //torch::nn::Dropout2d conv2_drop;
  torch::nn::Linear fc1;
  torch::nn::Linear fc2;
};

template <typename DataLoader>
void train(
    size_t epoch,
    Net& model,
    torch::Device device,
    DataLoader& data_loader,
    torch::optim::Optimizer& optimizer,
    size_t dataset_size) {
  model.train();
  size_t batch_idx = 0;
  for (auto& batch : data_loader) {
    auto data = batch.data.to(device), targets = batch.target.to(device);
    optimizer.zero_grad();
    auto output = model.forward(data);
    auto loss = torch::nll_loss(output, targets);
    AT_ASSERT(!std::isnan(loss.template item<float>()));
    loss.backward();
    optimizer.step();

    if (batch_idx++ % kLogInterval == 0) {
      std::printf(
          "\rTrain Epoch: %ld [%5ld/%5ld] Loss: %.4f",
          epoch,
          batch_idx * batch.data.size(0),
          dataset_size,
          loss.template item<float>());
    }
  }
}

template <typename DataLoader>
void test(
    Net& model,
    torch::Device device,
    DataLoader& data_loader,
    size_t dataset_size) {
  torch::NoGradGuard no_grad;
  model.eval();
  double test_loss = 0;
  int32_t correct = 0;
  for (const auto& batch : data_loader) {
    auto data = batch.data.to(device), targets = batch.target.to(device);
    auto output = model.forward(data);
    test_loss += torch::nll_loss(
                     output,
                     targets,
                     /*weight=*/{},
                     torch::Reduction::Sum)
                     .template item<float>();
    auto pred = output.argmax(1);
    correct += pred.eq(targets).sum().template item<int64_t>();
  }

  test_loss /= dataset_size;
  std::printf(
      "\nTest set: Average loss: %.4f | Accuracy: %.3f\n",
      test_loss,
      static_cast<double>(correct) / dataset_size);
}

void print_tensor2data(torch::Tensor tensor, std::ostream& ofs) {
	float* data = reinterpret_cast<float*>(tensor.data_ptr());
	ofs << "    data: ";
	for (size_t i = 0; i < tensor.numel(); i++) {
		ofs << data[i] << " ";
	}
	ofs << "\n";
}
auto main() -> int {
  torch::manual_seed(1);

  torch::DeviceType device_type;
  if (torch::cuda::is_available()) {
    std::cout << "CUDA available! Training on GPU." << std::endl;
    device_type = torch::kCUDA;
  } else {
    std::cout << "Training on CPU." << std::endl;
    device_type = torch::kCPU;
  }
  torch::Device device(device_type);
  std::vector<int64_t> block_config = { 4, 8, 16, 32, 64, 64 };
  Net model(1, block_config);
  model.to(device);

  auto train_dataset =
      torch::data::datasets::MNIST(kDataRoot)
          .map(torch::data::transforms::Normalize<>(0.1307, 0.3081))
          .map(torch::data::transforms::Stack<>());
  const size_t train_dataset_size = train_dataset.size().value();
  auto train_loader =
      torch::data::make_data_loader<torch::data::samplers::SequentialSampler>(
          std::move(train_dataset), kTrainBatchSize);

  auto test_dataset =
      torch::data::datasets::MNIST(
          kDataRoot, torch::data::datasets::MNIST::Mode::kTest)
          .map(torch::data::transforms::Normalize<>(0.1307, 0.3081))
          .map(torch::data::transforms::Stack<>());
  const size_t test_dataset_size = test_dataset.size().value();
  auto test_loader =
      torch::data::make_data_loader(std::move(test_dataset), kTestBatchSize);

  torch::optim::SGD optimizer(
      model.parameters(), torch::optim::SGDOptions(0.01).momentum(0.5));
  //torch::optim::AdamW optimizer(model.parameters(), 0.01);

  for (size_t epoch = 1; epoch <= 1; ++epoch) {
    train(epoch, model, device, *train_loader, optimizer, train_dataset_size);
    test(model, device, *test_loader, test_dataset_size);
    decay<torch::optim::SGD, torch::optim::SGDOptions>(optimizer, 0.1);
  }
  std::ofstream ofs("./record.txt");
  for (auto para : model.named_parameters()) {
	  if (para.key().empty()) {
		  continue;
	  }
	  ofs << para.key()/* <<" : " << para.value()*/ << std::endl;
	  print_tensor2data(para.value().to(torch::kCPU), ofs);
  }
  ofs.close();
}
`

**Comment by glaringlee** [comment] 2021-03-02 15:40
@w1005444804 
Can you test the BatchNorm2d only?   
It is hard to tell where is the problem within such a big program with multiple layers. Can you write a simple code testing BatchNorm2d only? Probably just need 10 lines-insh code. If BatchNorm2d has no problem, then expand the test program to add more layers in.

**Comment by glaringlee** [comment] 2021-03-02 16:03
@w1005444804 another thing I noticed is that when you push_back a module into Sequential, you did not give a name to each DBL, in this case Sequential will use a default name based on the module size, but it might overwritten previously registered module in the same Sequential, if the size of each DBL module is the same. I am not sure whether this caused the issue, but please give each DBL module a name in Sequential container and try. https://github.com/pytorch/pytorch/blob/ac3f23deb0c87902e60750f26c632c32436c530b/torch/csrc/api/include/torch/nn/modules/container/sequential.h#L212

**Comment by w1005444804** [comment] 2021-03-03 01:38
@glaringlee  push_back a module into Sequential with a name has same  problem. the BatchNorm2d has no such problem in a small model.

**Comment by glaringlee** [comment] 2021-03-03 15:51
@glaringlee ok, I see. 
Then the next step is to put BatchNorm2d into a Sequential, see whether you have the same problem. I test this a bit, it works fine for me. Can you make sure this is not caused by your input tensor? You model is too big to  find out the root cause, are you able to create a smaller example to replicate this problem?

**Comment by w1005444804** [comment] 2021-03-04 09:04
@glaringlee  thanks
In the model, not all BN layers do not update parameters, only the BN layers which in resblock  do not update .

**Comment by w1005444804** [comment] 2021-03-04 09:07
@glaringlee 
![image](https://user-images.githubusercontent.com/6340026/109939466-0b718280-7d0c-11eb-93d5-aedb25a14bcd.png)

**Comment by w1005444804** [comment] 2021-03-04 15:58
@glaringlee 
it is my fault,:
it should be:{y = DBL2->forward(y);return y}; but I return x in the CSP_ResBlock_Body;
@glaringlee Sorry for wasting so much time

**Comment by glaringlee** [comment] 2021-03-04 16:26
@w1005444804 lol, glad you find out the issue! I'll close this now, feel free to re-open it if you need anything.

**Closed by glaringlee** 2021-03-04 16:26 UTC
Labels: module: cpp, module: norms and normalization, triaged
