### ISSUE TITLE
On the new Apple Silicon, when compiling from source, got this error:

### ISSUE THREAD

**Issue by slerman12** [pytorch/pytorch#49924] opened 2020-12-29 13:18 UTC
After running:

```
export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
MACOSX_DEPLOYMENT_TARGET=11.0 CC=clang CXX=clang++ python3 setup.py install
```

Got this trace:

```
Building wheel torch-1.8.0a0
-- Building version 1.8.0a0
cmake --build . --target install --config Release -- -j 8
[1/236] Linking CXX executable bin/test_parallel
FAILED: bin/test_parallel 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Xpreprocessor -fopenmp -I/Users/samlerman/code/miniforge3/include -DNDEBUG -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const -O3 -DNDEBUG -DNDEBUG -arch arm64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=11.0 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -rdynamic caffe2/CMakeFiles/test_parallel.dir/__/aten/src/ATen/test/test_parallel.cpp.o -o bin/test_parallel  -Wl,-rpath,/Users/samlerman/Code/Libraries/pytorch/build/lib  lib/libgtest_main.a  lib/libtorch.dylib  lib/libtorch_cpu.dylib  lib/libprotobuf.a  lib/libc10.dylib  lib/libgtest.a && :
Undefined symbols for architecture arm64:
  "___kmpc_end_serialized_parallel", referenced from:
      TestParallel_NestedParallel_Test::TestBody() in test_parallel.cpp.o
      TestParallel_Exceptions_Test::TestBody() in test_parallel.cpp.o
  "___kmpc_fork_call", referenced from:
      TestParallel_NestedParallel_Test::TestBody() in test_parallel.cpp.o
      TestParallel_Exceptions_Test::TestBody() in test_parallel.cpp.o
  "___kmpc_global_thread_num", referenced from:
      TestParallel_NestedParallel_Test::TestBody() in test_parallel.cpp.o
      TestParallel_Exceptions_Test::TestBody() in test_parallel.cpp.o
  "___kmpc_serialized_parallel", referenced from:
      TestParallel_NestedParallel_Test::TestBody() in test_parallel.cpp.o
      TestParallel_Exceptions_Test::TestBody() in test_parallel.cpp.o
  "_omp_get_max_threads", referenced from:
      TestParallel_NestedParallel_Test::TestBody() in test_parallel.cpp.o
      TestParallel_Exceptions_Test::TestBody() in test_parallel.cpp.o
  "_omp_get_num_threads", referenced from:
      _.omp_outlined. in test_parallel.cpp.o
      _.omp_outlined..33 in test_parallel.cpp.o
      _.omp_outlined..35 in test_parallel.cpp.o
  "_omp_get_thread_num", referenced from:
      _.omp_outlined. in test_parallel.cpp.o
      _.omp_outlined..33 in test_parallel.cpp.o
      _.omp_outlined..35 in test_parallel.cpp.o
  "_omp_in_parallel", referenced from:
      TestParallel_NestedParallel_Test::TestBody() in test_parallel.cpp.o
      TestParallel_Exceptions_Test::TestBody() in test_parallel.cpp.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[8/236] Building CXX object third_part...__/src/google/protobuf/stubs/time.cc.o
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "/Users/samlerman/Code/Libraries/pytorch/setup.py", line 773, in <module>
    build_deps()
  File "/Users/samlerman/Code/Libraries/pytorch/setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "/Users/samlerman/Code/Libraries/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/Users/samlerman/Code/Libraries/pytorch/tools/setup_helpers/cmake.py", line 346, in build
    self.run(build_args, my_env)
  File "/Users/samlerman/Code/Libraries/pytorch/tools/setup_helpers/cmake.py", line 141, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/Users/samlerman/code/miniforge3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Release', '--', '-j', '8']' returned non-zero exit status 1.

```

cc @malfet @seemethere @walterddr

**Comment by walterddr** [comment] 2020-12-29 20:45
could you run [collect_env.py](https://github.com/pytorch/pytorch/blob/master/torch/utils/collect_env.py) and share the result?

**Comment by slerman12** [comment] 2020-12-30 04:53
`Collecting environment information...
PyTorch version: 1.8.0a0+c068180
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 11.1 (arm64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.28)
CMake version: version 3.19.2

Python version: 3.9 (64-bit runtime)
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.4
[pip3] torch==1.8.0a0
[pip3] torchvision==0.9.0a0+83171d6
[conda] numpy                     1.19.4           py39h69a04d8_2    conda-forge
[conda] torch                     1.8.0a0                  pypi_0    pypi
[conda] torchvision               0.9.0a0+83171d6          pypi_0    pypi`

**Comment by SupperSu** [comment] 2021-02-04 23:41
Get exactly same error.

> [1/110] Linking CXX executable bin/test_parallel
FAILED: bin/test_parallel 
: && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -Wno-deprecated -fvisibility-inlines-hidden -Wno-deprecated-declarations -DUSE_PTHREADPOOL -Xpreprocessor -fopenmp -I/usr/local/include -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -Wno-invalid-partial-specialization -Wno-typedef-redefinition -Wno-unknown-warning-option -Wno-unused-private-field -Wno-inconsistent-missing-override -Wno-aligned-allocation-unavailable -Wno-c++14-extensions -Wno-constexpr-not-const -Wno-missing-braces -Qunused-arguments -fcolor-diagnostics -fno-math-errno -fno-trapping-math -Werror=format -Werror=cast-function-type -Wno-unused-private-field -Wno-missing-braces -Wno-c++14-extensions -Wno-constexpr-not-const -DHAVE_AVX_CPU_DEFINITION -DHAVE_AVX2_CPU_DEFINITION -g -fno-omit-frame-pointer -O0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.1.sdk -mmacosx-version-min=10.9 -Wl,-search_paths_first -Wl,-headerpad_max_install_names -rdynamic caffe2/CMakeFiles/test_parallel.dir/__/aten/src/ATen/test/test_parallel.cpp.o -o bin/test_parallel  -Wl,-rpath,/Users/yupengsu/pytorch/build/lib  lib/libgtest_maind.a  lib/libtorch.dylib  lib/libtorch_cpu.dylib  lib/libprotobufd.a  lib/libc10.dylib  lib/libdnnl.a  lib/libgtestd.a && :
Undefined symbols for architecture x86_64:
  "___kmpc_end_serialized_parallel", referenced from:
      void at::parallel_for<TestParallel_NestedParallel_Test::TestBody()::$_0>(long long, long long, long long, TestParallel_NestedParallel_Test::TestBody()::$_0 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_1>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_1 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_2>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_2 const&) in test_parallel.cpp.o
  "___kmpc_fork_call", referenced from:
      void at::parallel_for<TestParallel_NestedParallel_Test::TestBody()::$_0>(long long, long long, long long, TestParallel_NestedParallel_Test::TestBody()::$_0 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_1>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_1 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_2>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_2 const&) in test_parallel.cpp.o
  "___kmpc_global_thread_num", referenced from:
      void at::parallel_for<TestParallel_NestedParallel_Test::TestBody()::$_0>(long long, long long, long long, TestParallel_NestedParallel_Test::TestBody()::$_0 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_1>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_1 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_2>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_2 const&) in test_parallel.cpp.o
  "___kmpc_serialized_parallel", referenced from:
      void at::parallel_for<TestParallel_NestedParallel_Test::TestBody()::$_0>(long long, long long, long long, TestParallel_NestedParallel_Test::TestBody()::$_0 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_1>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_1 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_2>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_2 const&) in test_parallel.cpp.o
  "_omp_get_max_threads", referenced from:
      void at::parallel_for<TestParallel_NestedParallel_Test::TestBody()::$_0>(long long, long long, long long, TestParallel_NestedParallel_Test::TestBody()::$_0 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_1>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_1 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_2>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_2 const&) in test_parallel.cpp.o
  "_omp_get_num_threads", referenced from:
      _.omp_outlined._debug__ in test_parallel.cpp.o
      _.omp_outlined._debug__.33 in test_parallel.cpp.o
      _.omp_outlined._debug__.36 in test_parallel.cpp.o
  "_omp_get_thread_num", referenced from:
      _.omp_outlined._debug__ in test_parallel.cpp.o
      _.omp_outlined._debug__.33 in test_parallel.cpp.o
      _.omp_outlined._debug__.36 in test_parallel.cpp.o
  "_omp_in_parallel", referenced from:
      void at::parallel_for<TestParallel_NestedParallel_Test::TestBody()::$_0>(long long, long long, long long, TestParallel_NestedParallel_Test::TestBody()::$_0 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_1>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_1 const&) in test_parallel.cpp.o
      void at::parallel_for<TestParallel_Exceptions_Test::TestBody()::$_2>(long long, long long, long long, TestParallel_Exceptions_Test::TestBody()::$_2 const&) in test_parallel.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
[6/110] Linking CXX executable bin/test_jit
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "setup.py", line 773, in <module>
    build_deps()
  File "setup.py", line 315, in build_deps
    build_caffe2(version=version,
  File "/Users/yupengsu/pytorch/tools/build_pytorch_libs.py", line 58, in build_caffe2
    cmake.build(my_env)
  File "/Users/yupengsu/pytorch/tools/setup_helpers/cmake.py", line 345, in build
    self.run(build_args, my_env)
  File "/Users/yupengsu/pytorch/tools/setup_helpers/cmake.py", line 140, in run
    check_call(command, cwd=self.build_dir, env=env)
  File "/Users/yupengsu/anaconda3/envs/py38_pytorch/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '--build', '.', '--target', 'install', '--config', 'Debug', '--', '-j', '6']' returned non-zero exit status 1.

**Comment by SupperSu** [comment] 2021-02-04 23:42
PyTorch version: N/A
Is debug build: N/A
CUDA used to build PyTorch: N/A
ROCM used to build PyTorch: N/A

OS: macOS 10.15.4 (x86_64)
GCC version: Could not collect
Clang version: 12.0.0 (clang-1200.0.32.29)
CMake version: version 3.19.4

Python version: 3.8 (64-bit runtime)
Is CUDA available: N/A
CUDA runtime version: Could not collect
GPU models and configuration: Could not collect
Nvidia driver version: Could not collect
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.20.0
[conda] # packages in environment at /Users/yupengsu/anaconda3/envs/py38_pytorch:

**Comment by jotsif** [comment] 2021-03-12 13:36
```USE_OPENMP=NO python3 setup.py install```
works on my Apple M1.

The issue is some CMake thing that doesn't add the right OpenMP linking arguments for Apple Clang.  Something like this https://gitlab.kitware.com/cmake/cmake/-/issues/21818

**Comment by albanD** [comment] 2021-04-23 19:59
This should be fixed now.
Feel free to re-open if you encounter more issues.

**Closed by albanD** 2021-04-23 19:59 UTC
Labels: module: build, module: osx, triaged
