### ISSUE TITLE
ATen autograd functions don't handle None/undefined ATen grad tensors

### ISSUE THREAD

**Issue by gchanan** [pytorch/pytorch#3241] opened 2017-10-23 18:22 UTC
If a backward function returns None/ATen undefined tensor, it can be passed to a downstream ATen autograd function as a grad, but ATen autograd functions in general do not check that their grad arguments are defined.  This is in contrast to python autograd functions which will expand the undefined tensor to a tensor of 0s of the correct size/type/device.  I ran into this when implementing `chunk`s backward, but it's possible to hit this even for single-output functions.

Reproduction steps (for single-output function):
1) Define a "myz" function that returns a `None` in its backward as follows:
```
diff --git a/torch/autograd/_functions/basic_ops.py b/torch/autograd/_functions/basic_ops.py
index ef3b75b..5a705e7 100644
--- a/torch/autograd/_functions/basic_ops.py
+++ b/torch/autograd/_functions/basic_ops.py
@@ -42,6 +42,16 @@ class PowConstant(Function):
             var_result, = ctx.saved_variables
             return None, grad_output.mul(var_result).mul_(math.log(ctx.constant))

+class MyZ(Function):
+
+    @staticmethod
+    def forward(ctx, a):
+        return a * 0
+
+    @staticmethod
+    def backward(ctx, grad_output):
+        return None
+

 @traceable
 class Negate(InplaceFunction):
diff --git a/torch/autograd/variable.py b/torch/autograd/variable.py
index 5298090..31277f8 100644
--- a/torch/autograd/variable.py
+++ b/torch/autograd/variable.py
@@ -519,6 +519,9 @@ class Variable(_C._VariableBase):
     def __hash__(self):
         return id(self)

+    def myz(self):
+        return MyZ.apply(self)
+
     class _torch(object):

         @staticmethod
```

Then run the following script:
```
import torch
from torch.autograd import Variable
a=Variable(torch.randn(1), requires_grad=True)
b=Variable(torch.randn(1), requires_grad=True)
(a.mul(b)).myz().backward()
```
This results in a segmentation fault, although there is an open issue in ATen to throw a proper exception.

CC @colesbury

**Comment by elbamos** [comment] 2017-10-24 22:20
With the new ATen code I'm seeing `RuntimeError: undefined Tensor` when trying to use double backwards. Is it possible that this issue created a change in the behavior of `torch.autograd.grad`?

**Comment by colesbury** [comment] 2017-10-24 22:30
Yes, that's likely. Could you post code that reproduces the error?

**Comment by elbamos** [comment] 2017-10-24 22:38
It’s wrapped in a whole giant package implementing improved training of Wasserstein gans. If I can pin down the responsible layers I’ll try to produce a minimal example.

**Comment by elbamos** [comment] 2017-10-27 00:19
@colesbury I haven't been able to trace this to a particular layer, but it does seem to be caused by the ATen code - I don't get the issue when I revert to commit 28ed514.

(I'm also suspicious that something around the same time may have broken backwards for BatchNorm2d, but I haven't nailed that down fully yet.)  

(I hope it wouldn't be out of turn to suggest that ATen might be a good candidate for a separate feature branch?)

**Comment by soumith** [comment] 2017-10-27 09:49
@elbamos what do you mean by "broken backwards for BatchNorm2d"?

**Comment by elbamos** [comment] 2017-10-31 05:17
@soumith The issue I thought was related to backwards on batchnorm2d turned out to be unrelated.

**Comment by soumith** [comment] 2017-11-06 23:43
fixed in #3433 
@elbamos can you check that this is fixed on master or on https://github.com/pytorch/pytorch/tree/v0.3.0

**Closed by soumith** 2017-11-06 23:43 UTC

**Comment by elbamos** [comment] 2017-11-06 23:50
I’ll test it today, yes, thanks.

**Comment by elbamos** [comment] 2017-11-07 09:42
@soumith I no longer get `undefined Tensor`, but instead now after around 30 iterations CUDA runs out of memory. Is it possible a memory leak was introduced?

**Comment by soumith** [comment] 2017-11-07 12:02
@elbamos on both `master` and on `v0.3.0` branch??? it's possible and we'd like to take a look. Is there an chance we can get private access to your repo (purely for hunting down the bug purposes)?

**Comment by elbamos** [comment] 2017-11-07 19:06
That was on master. I can try v0.3.0 today. Will reach out to you on slack about access.

**Comment by elbamos** [comment] 2017-11-07 20:25
On v0.3.0 I get `undefined Tensor` again.  Will reach out...

**Comment by elbamos** [comment] 2017-11-08 05:15
I take it back - the memory issue seems tied to using `InstanceNorm` layers rather than to double backwards.
