### ISSUE TITLE
An error occurred when exporting a gcn model using torch.onnx.export().

### ISSUE THREAD

**Issue by dunesand** [pytorch/pytorch#66537] opened 2021-10-13 03:10 UTC
When using the torch.onnx.export() function to export the GCN model, an error occurred.

code:
torch.onnx.export(model,               
                  (tensor_adjacency,tensor_x), 
                  'gcn.onnx', 
                  export_params=True, 
                  opset_version=10,     
                  do_constant_folding=True, 
                  input_names = ['adjacency','feature'],
                  output_names = ['logits'], 
                  enable_onnx_checker=True,
                  _retain_param_name=True
                  )

output:

C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_trace.py in wrapper(*args)
    110 
    111             ret_inputs.append(
--> 112                 tuple(x.clone(memory_format=torch.preserve_format) for x in args)
    113             )
    114             if self._return_inputs_states:

C:\ProgramData\Anaconda3\lib\site-packages\torch\jit\_trace.py in <genexpr>(.0)
    110 
    111             ret_inputs.append(
--> 112                 tuple(x.clone(memory_format=torch.preserve_format) for x in args)
    113             )
    114             if self._return_inputs_states:

RuntimeError: unsupported memory format option Preserve

why this error occurs？I would be very grateful if it can be answered.

cc @BowenBao @neginraoof

**Comment by BowenBao** [comment] 2021-11-10 23:13
@dunesand are you using sparse tensors in this model?

**Comment by dunesand** [comment] 2021-11-12 03:15
> @dunesand are you using sparse tensors in this model?

Yes, and I have solved this problem by reprogramming the model in PyG .

**Comment by garymm** [comment] 2021-11-20 01:00
Duplicate of #54638

**Closed by garymm** 2021-11-20 01:00 UTC
Labels: oncall: jit, module: onnx, triaged

**Comment by intelsam** [comment] 2022-08-07 14:31
Hi @dunesand , Can you please share how exactly you solved this in PyG?
I need to do this but unable to yet.
