### ISSUE TITLE
 25 Dynamo test are failing with "argument of type: <class 'torch._ops.OpOverloadPacket'"

### ISSUE THREAD

**Issue by zou3519** [pytorch/pytorch#118789] opened 2024-01-31 20:28 UTC
25 Dynamo test are failing with "argument of type: <class 'torch._ops.OpOverloadPacket'".

## Repro

`PYTORCH_TEST_WITH_DYNAMO=1 pytest test_cpp_extensions_jit.py -v -k test_custom_compound_op_autograd`

You will need to remove the skip or expectedFailure before running the repro command.
This may be just removing a line in
[dynamo_test_failures.py](https://github.com/pytorch/pytorch/blob/main/torch/testing/_internal/dynamo_test_failures.py)

## Failing tests

Here's a comprehensive list of tests that fail (as of this issue) with the above message:
<details>
<summary>Click me</summary>
```
test_cpp_extensions_jit.py::TestCppExtensionJIT.test_custom_compound_op_autograd
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_False_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_False_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_True_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_True_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_False_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_False_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_True_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_True_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_False_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_False_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_True_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_True_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_False_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_False_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_True_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_True_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_False_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_False_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_True_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_True_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_False_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_False_contiguous_True_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_True_contiguous_False_cpu
nn/test_convolution.py::TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_True_contiguous_True_cpu
```

cc @ezyang @msaroufim @bdhirsh @anijain2305 @voznesenskym @penguinwu @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @wenzhe-nrv @jiayisunx @chenyang78 @aakhundov @kadeng

**Comment by jamesjwu** [comment] 2024-02-28 02:17
It looks like TestCppExtensionJIT.test_custom_compound_op_autograd is passing for me, at least locally: 

```
(base) [0] jjwu@devgpu086 (main) ~/pytorch/test $ PYTORCH_TEST_WITH_DYNAMO=1 pytest test_cpp_extensions_jit.py -v -k test_custom_compound_op_autograd
=============================================================================================================== test session starts ===============================================================================================================
platform linux -- Python 3.11.5, pytest-7.4.0, pluggy-1.0.0 -- /data/users/jjwu/miniconda3/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase(PosixPath('/data/users/jjwu/pytorch/test/.hypothesis/examples'))
rootdir: /data/users/jjwu/pytorch
configfile: pytest.ini
plugins: hypothesis-6.92.1
collected 26 items / 25 deselected / 1 selected
Running 1 items in this shard

test_cpp_extensions_jit.py::TestCppExtensionJIT::test_custom_compound_op_autograd [1/2] c++ -MMD -MF main.o.d -DTORCH_EXTENSION_NAME=is_python_module -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1016\" -isystem /data/users/jjwu/pytorch/torch/include -isystem /data/users/jjwu/pytorch/torch/include/torch/csrc/api/include -isystem /data/users/jjwu/pytorch/torch/include/TH -isystem /data/users/jjwu/pytorch/torch/include/THC -isystem /data/users/jjwu/miniconda3/include/python3.11 -D_GLIBCXX_USE_CXX11_ABI=1 -fPIC -std=c++17 -c /home/jjwu/.cache/torch_extensions/py311_cu120/is_python_module/main.cpp -o main.o
[2/2] c++ main.o -shared -L/data/users/jjwu/pytorch/torch/lib -lc10 -ltorch_cpu -ltorch -ltorch_python -o is_python_module.so
PASSED [10.1731s]                                                                                                                                         [100%]
```

Will try the others

**Comment by jamesjwu** [comment] 2024-02-28 04:45
Oh, it looks like those 96 are a duplicate of https://github.com/pytorch/pytorch/issues/118797.  I double checked that all 25 of the tests listed in the original issue pass:

```
(base) [0] jjwu@devgpu086 (main) ~/pytorch/test $ PYTORCH_TEST_WITH_DYNAMO=1 python nn/test_convolution.py -k TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch -v
test_conv_backend_empty_batch1d_has_bias_False_strided_False_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_False_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch1d_has_bias_False_strided_False_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_False_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch1d_has_bias_False_strided_True_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_True_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch1d_has_bias_False_strided_True_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_False_strided_True_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch1d_has_bias_True_strided_False_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_False_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch1d_has_bias_True_strided_False_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_False_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch1d_has_bias_True_strided_True_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_True_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch1d_has_bias_True_strided_True_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch1d_has_bias_True_strided_True_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_False_strided_False_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_False_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_False_strided_False_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_False_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_False_strided_True_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_True_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_False_strided_True_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_False_strided_True_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_True_strided_False_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_False_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_True_strided_False_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_False_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_True_strided_True_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_True_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch2d_has_bias_True_strided_True_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch2d_has_bias_True_strided_True_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_False_strided_False_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_False_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_False_strided_False_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_False_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_False_strided_True_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_True_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_False_strided_True_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_False_strided_True_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_True_strided_False_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_False_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_True_strided_False_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_False_contiguous_True_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_True_strided_True_contiguous_False_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_True_contiguous_False_cpu) ... ok
test_conv_backend_empty_batch3d_has_bias_True_strided_True_contiguous_True_cpu (__main__.TestConvolutionNNDeviceTypeCPU.test_conv_backend_empty_batch3d_has_bias_True_strided_True_contiguous_True_cpu) ... ok
```

None of these files are in dynamo_expected_failures/. Please reopen this issue if someone finds an actual repro.

**Closed by jamesjwu** 2024-02-28 04:45 UTC
Labels: triaged, oncall: pt2, module: dynamo, dynamo-must-fix
