### ISSUE TITLE
libtorch hardcoded libculibos.a causes build errors for C++ programs on Arch Linux

### ISSUE THREAD

**Issue by prashantraina** [pytorch/pytorch#15063] opened 2018-12-11 18:17 UTC
## 🐛 Bug

The sample C++ program for libtorch results in an incorrect Makefile because the path to libculibos.a is hardcoded somewhere as `/usr/local/cuda/lib64/libculibos.a`.
On Arch Linux, the default install directory for CUDA is `/opt/cuda`. 
**This is handled correctly for other linked libraries.**

## Workaround
After running CMake, modify `CMakeFiles/(project).dir/build.make` and modify the line:
(project): /usr/local/cuda/lib64/libculibos.a
to:
(project): /opt/cuda/lib64/libculibos.a

This fixes the problem for me with CUDA 10.

## To Reproduce

1. Be on Arch Linux with libtorch downloaded from the official download link.
1. Try to follow the [minimal C++ example]: https://pytorch.org/cppdocs/installing.html
1. You will get an error when running `make`, which can be fixed with the temporary workaround shown above.

**Comment by elPistolero** [comment] 2018-12-12 09:37
This is problem not just restricted to Arch Linux but a general problem if CUDA is not installed at /usr/local/cuda for any Linux distribution.

see (https://github.com/pytorch/pytorch/issues/13315#issuecomment-436415532)

**Comment by pjh5** [comment] 2018-12-13 19:52
Okay I see the problem. I'll look into a fix

**Comment by prashantraina** [comment] 2018-12-27 15:03
The problem seems to come from line 82 of libtorch/share/cmake/Caffe2/Caffe2Targets.cmake
And there's an easy fix which works for me
`INTERFACE_LINK_LIBRARIES "caffe2::cudart;c10_cuda;caffe2;caffe2::cufft;caffe2::curand;caffe2::cudnn;**${CUDA_TOOLKIT_ROOT_DIR}/lib64/libculibos.a;**caffe2::cublas"`

**Comment by pjh5** [comment] 2018-12-28 17:41
This isn't an rpath thing. This PR comes real close to fixing it; there's just one last error I have to fix. https://github.com/pytorch/pytorch/pull/15239

**Comment by teng-li** [comment] 2019-03-19 22:31
Looks like we hit this issue as well. @pjh5 Any updates on this?

**Comment by rgommers** [comment] 2019-07-26 06:10
> This is problem not just restricted to Arch Linux but a general problem if CUDA is not installed at /usr/local/cuda for any Linux distribution.

This is correct.

I propose to close this as a duplicate of gh-15476 (which now has more details, and is labeled as high-prio).

**Comment by soumith** [comment] 2019-07-26 11:41
closing in favor of #15476

**Closed by soumith** 2019-07-26 11:41 UTC
