### ISSUE TITLE
test_remote_script_module is flaky

### ISSUE THREAD

**Issue by mrshenli** [pytorch/pytorch#33948] opened 2020-02-28 19:42 UTC
Failed run:
https://app.circleci.com/jobs/github/pytorch/pytorch/4605753

Passed run:
https://app.circleci.com/jobs/github/pytorch/pytorch/4605780

cc @ezyang @gchanan @zou3519 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @gqchen @aazzolini @rohan-varma @xush6528 @jjlilley @osalpekar

**Comment by zhaojuanmao** [comment] 2020-02-28 21:56
the error is "Received error while processing request type 4: vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)", I checked this test, did not find suspicious causes. Also can not reproduce locally in stress runs, I checked master runs as well, it only happened once. I suspect it is due to some transient failure that is not related to our code bases. 

I will keep monitoring this error.

**Comment by zhaojuanmao** [comment] 2020-03-16 18:15
closing this, as it looks like it is not relevant and it never happened any more

**Closed by zhaojuanmao** 2020-03-16 18:15 UTC
Labels: high priority, module: rpc, topic: flaky-tests, triaged
