### ISSUE TITLE
more `torch.distributed.launch` issues in 1.9.0

### ISSUE THREAD

**Issue by stas00** [pytorch/pytorch#60752] opened 2021-06-25 16:53 UTC
## 🐛 Bug

started getting this:
```
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
```

## To Reproduce

```
$ cat test.py

import torch.distributed as dist
import argparse
import torch

parser = argparse.ArgumentParser()
parser.add_argument("--local_rank", type=int)
args = parser.parse_args()
torch.cuda.set_device(args.local_rank)
dist.init_process_group("nccl")

dist.barrier()
```
and then:
```
CUDA_VISIBLE_DEVICES=0,1 python -m torch.distributed.launch --nproc_per_node=2 test.py
```

(same problem in `.run` so that's the real source as `launch` now is a proxy to it)

## Expected behavior

```
torch.cuda.set_device(args.local_rank)
```
should be setting the correct device, and there should be no warning:

```
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
[W ProcessGroupNCCL.cpp:1569] Rank 1 using best-guess GPU 1 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
```

If there is a new requirement, nothing is said about it here: https://pytorch.org/docs/stable/elastic/train_script.html

## Environment

```
Collecting environment information...
PyTorch version: 1.9.0+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.2 LTS (x86_64)
GCC version: (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Clang version: 10.0.0-4ubuntu1
CMake version: version 3.16.3
Libc version: glibc-2.31

Python version: 3.8 (64-bit runtime)
Python platform: Linux-5.4.0-74-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: 11.3.109
GPU models and configuration:
GPU 0: NVIDIA GeForce GTX 1070 Ti
GPU 1: NVIDIA GeForce RTX 3090

Nvidia driver version: 465.19.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.5
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.1
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.1
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.5
[pip3] torch==1.9.0+cu111
[pip3] torch-tb-profiler==0.2.0
[pip3] torchaudio==0.9.0
[pip3] torchvision==0.10.0+cu111
[conda] mkl                       2021.2.0           h06a4308_296
[conda] numpy                     1.19.5                   pypi_0    pypi
[conda] torch                     1.9.0+cu111              pypi_0    pypi
[conda] torch-tb-profiler         0.2.0                    pypi_0    pypi
[conda] torchaudio                0.9.0                    pypi_0    pypi
[conda] torchvision               0.10.0+cu111             pypi_0    pypi
```

cc @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu @gcramer23

**Comment by kiukchung** [comment] 2021-06-26 04:51
Thanks for reporting this issue! I can indeed repro this on my local dev desktop. But I have a reason to believe the issue is not in the launcher but rather somewhere in the NCCL process group. Here's the reason why: I tried running the script as a single worker without the launcher as such:

```
CUDA_VISIBLE_DEVICES=0 RANK=0 WORLD_SIZE=1 MASTER_ADDR=localhost MASTER_PORT=8081 python test.py --local_rank 0
```

and get 
```
[W ProcessGroupNCCL.cpp:1569] Rank 0 using best-guess GPU 0 to perform barrier as devices used by this process are currently unknown. This can potentially cause a hang if this rank to GPU mapping is incorrect.Specify device_ids in barrier() to force use of a particular device.
```
I'll investigate further and report back. In the meanwhile please do not hesitate to point out glaring misses on my hypothesis or my repro steps!

**Comment by pritamdamania87** [comment] 2021-06-28 19:06
cc @rohan-varma Since this is related to the ProcessGroupNCCL init, I guess we've discussed this with @mcarilli in the past.

**Comment by rohan-varma** [comment] 2021-06-28 19:17
The log is coming from: https://github.com/pytorch/pytorch/blob/master/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L1622, and the motivation to add it was that `barrier`, if it is the first NCCL collective call, does not know which GPU to use if it has not been explicitly specified since there are no communicators initialized on the GPU intended for the process.

Although, agreed here that it is a false positive warning since we've explicitly specified which GPU to use via `set_device`. Ideally we should update the warning to not fire in this case, although I'm not sure if there's a reliable way to check if a device has been set explicitly by the user?

**Comment by pritamdamania87** [comment] 2021-06-28 19:23
@rohan-varma Maybe this should be an INFO level log since we are just mentioning what PG NCCL is using. This is triggered every time once for PG NCCL right? And my understanding is the WARNING logs probably should indicate a potential error/issue, whereas I don't think this is the case here.

**Comment by rohan-varma** [comment] 2021-06-28 19:39
> This is triggered every time once for PG NCCL right? 

Not necessarily, it is not triggered if:
1) User issued another collective before (i.e. allreduce) because there we have populated `usedDeviceIdxs_` map.
2) User specified `device_ids` into `barrier`

Regarding `warning` vs `info`, in the case this LOG is trying to help (basically the repro described here: https://github.com/pytorch/pytorch/issues/53658), I think it is more appropriate as a warning since there is a risk that rank N does not map to GPU N % num_nodes, which is what we default to in `barrier` if a collective was not called before. But in the repro described above it is a false warning. 

An appropriate fix might be to just change it to be an `INFO` log, and log it the first time `barrier` is called when `usedDeviceIdxs_` is empty.

**Comment by rohan-varma** [comment] 2021-06-28 20:38
@stas00 The tricky thing is we'd have to somehow detect if the user has explicitly called `torch.cuda.set_device` in their script, and give that setting precedence over our current approach. However we can't always do this, because if the user doesn't call `torch.cuda.set_device` we would like to preserve our existing logic. I think this can be a longer-term fix and @mcarilli has already sent out a PR for discussion. Perhaps for 1.9.1 we can bump the log down to INFO.

**Comment by stas00** [comment] 2021-06-28 20:58
modifiy `torch.cuda.set_device` to toggle some global variable, which `set_device_was_called` can query and the problem will be solved? It's very possible I'm missing a whole bunch of environment understanding and you have already thought of this simple solution and wasn't working.

**Comment by rohan-varma** [comment] 2021-06-29 04:59
@stas00 Agreed that is a good solution. We're evaluating how exactly do it with folks who have more context around those APIs so that fix might take a bit longer. In the meantime https://github.com/pytorch/pytorch/pull/60901 also slightly changes the wording to make the log line just information, and I think it can be helpful if users do run into issues and forget to call torch.cuda.set_device for example

**Comment by stas00** [comment] 2021-06-29 05:16
I think we are on the same page, I'm advocating that it eventually regains its WARNING status, since this is:
1. too critical to be INFO 
2. will be missed if run with log level WARNING (default)

As a result pytorch will have Issues reported when users forget to set `torch.cuda.set_device`.

**Comment by rohan-varma** [comment] 2021-06-30 00:41
I'll close this for now given that the above mitigation has landed and we have a separate issue tracking the longer-term fix. Feel free to reopen in case I missed anything.

**Closed by rohan-varma** 2021-06-30 00:41 UTC
Labels: oncall: distributed

**Comment by woshiyyya** [comment] 2024-02-01 20:40
One question: What would happen if we don't specify `device_id`? I guess there will be a deallock but why will that happen?
