### ISSUE TITLE
download.pytorch.org flaky

### ISSUE THREAD

**Issue by clee2000** [pytorch/pytorch#100400] opened 2023-05-01 17:29 UTC
downloading models from download.pytorch.org is flaky, causing mobile builds to fail, inductor tests

ex https://github.com/pytorch/pytorch/actions/runs/4852615634/jobs/8648441371

```
TIMING: entire_frame_compile:11.44043 backend_compile:10.18199
STATS: call_* op count: 367 | FakeTensor.__torch_dispatch__:2409 | FakeTensorMode.__torch_dispatch__:24044 | attempt fast:904 | fast is_contiguous:904 | ProxyTorchDispatchMode.__torch_dispatch__:6011
Dynamo produced 1 graphs covering 367 ops with 0 graph breaks (0 unique)
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/opt/conda/envs/py_3.10/lib/python3.10/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
cuda eval  soft_actor_critic                   pass
TIMING: entire_frame_compile:2.34851 backend_compile:2.19266
STATS: call_* op count: 23 | FakeTensor.__torch_dispatch__:47 | FakeTensorMode.__torch_dispatch__:3976 | attempt fast:36 | fast is_contiguous:36 | ProxyTorchDispatchMode.__torch_dispatch__:2042
Dynamo produced 1 graphs covering 23 ops with 0 graph breaks (0 unique)
Downloading: "https://download.pytorch.org/models/squeezenet1_1-b8a52dc0.pth" to /var/lib/jenkins/.cache/torch/hub/checkpoints/squeezenet1_1-b8a52dc0.pth
Traceback (most recent call last):
  File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/opt/conda/envs/py_3.10/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/opt/conda/envs/py_3.10/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/opt/conda/envs/py_3.10/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/lib/jenkins/workspace/benchmarks/dynamo/torchbench.py", line 408, in <module>
    torchbench_main()
  File "/var/lib/jenkins/workspace/benchmarks/dynamo/torchbench.py", line 404, in torchbench_main
    main(TorchBenchmarkRunner(), original_dir)
  File "/var/lib/jenkins/workspace/benchmarks/dynamo/common.py", line 2035, in main
    return maybe_fresh_cache(
  File "/var/lib/jenkins/workspace/benchmarks/dynamo/common.py", line 1031, in inner
    return fn(*args, **kwargs)
  File "/var/lib/jenkins/workspace/benchmarks/dynamo/common.py", line 2413, in run
    ) = runner.load_model(device, model_name, batch_size=batch_size)
  File "/var/lib/jenkins/workspace/benchmarks/dynamo/torchbench.py", line 301, in load_model
    benchmark = benchmark_cls(
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/util/model.py", line 21, in __call__
    obj = type.__call__(cls, *args, **kwargs)
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/models/squeezenet1_1/__init__.py", line 17, in __init__
    super().__init__(model_name="squeezenet1_1", test=test, device=device, jit=jit,
  File "/var/lib/jenkins/workspace/torchbench/torchbenchmark/util/framework/vision/model_factory.py", line 29, in __init__
    self.model = getattr(models, model_name)(weights=weights).to(self.device)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/torchvision/models/_utils.py", line 142, in wrapper
    return fn(*args, **kwargs)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/torchvision/models/_utils.py", line 228, in inner_wrapper
    return builder(*args, **kwargs)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/torchvision/models/squeezenet.py", line 223, in squeezenet1_1
    return _squeezenet("1_1", weights, progress, **kwargs)
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/torchvision/models/squeezenet.py", line 112, in _squeezenet
    model.load_state_dict(weights.get_state_dict(progress=progress))
  File "/var/lib/jenkins/.local/lib/python3.10/site-packages/torchvision/models/_api.py", line 89, in get_state_dict
    return load_state_dict_from_url(self.url, progress=progress)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/hub.py", line 750, in load_state_dict_from_url
    download_url_to_file(url, cached_file, hash_prefix, progress=progress)
  File "/opt/conda/envs/py_3.10/lib/python3.10/site-packages/torch/hub.py", line 612, in download_url_to_file
    u = urlopen(req)
  File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/opt/conda/envs/py_3.10/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
ERROR
```

## Current Status
*Status could be: preemptive, ongoing, mitigated, closed. Also tell people if they need to take action to fix it (i.e. rebase)*.

## Error looks like
``` urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address> ```

## Incident timeline (all times pacific)
*Include when the incident began, when it was detected, mitigated, root caused, and finally closed.*

<details>
<summary> Click for example </summary>

e.g.
- 10/30 7:27a incident began
- 10/30 8:30a detected by <method>
- 10/30 9:00 pm root caused as…
- 10/30 9:10 pm mitigated by…
- 10/31 10: am closed by…

</details>

## User impact
*How does this affect users of PyTorch CI?*

## Root cause
*What was the root cause of this issue?*

## Mitigation
*How did we mitigate the issue?*

## Prevention/followups
*How do we prevent issues like this in the future?*

**Comment by malfet** [comment] 2023-05-01 21:17
Looks like latest nightly builds were affected by the same...

**Comment by malfet** [comment] 2023-05-01 21:31
Perhaps are unrelated, but some Nova runners are affected by 
`/github/home/.profile: line 22: conda: command not found`, for example see https://github.com/pytorch/vision/actions/runs/4850791061/jobs/8653256078

**Comment by malfet** [comment] 2023-05-01 22:02
@huydhn yep:
```
curl --verbose https://download.pytorch.org/whl/nightly/cpu
*   Trying [2600:9000:24f5:a200:d:607e:4540:93a1]:443...
* Connected to download.pytorch.org (2600:9000:24f5:a200:d:607e:4540:93a1) port 443 (#0)
* ALPN: offers h2
* ALPN: offers http/1.1
*  CAfile: /etc/ssl/cert.pem
*  CApath: none
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Client hello (1):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Server hello (2):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Unknown (8):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Certificate (11):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, CERT verify (15):
* [CONN-0-0][CF-SSL] (304) (IN), TLS handshake, Finished (20):
* [CONN-0-0][CF-SSL] (304) (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / AEAD-AES128-GCM-SHA256
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=pytorch.org
*  start date: Mar 18 00:00:00 2023 GMT
*  expire date: Apr 15 23:59:59 2024 GMT
*  subjectAltName: host "download.pytorch.org" matched cert's "*.pytorch.org"
*  issuer: C=US; O=Amazon; CN=Amazon RSA 2048 M01
*  SSL certificate verify ok.
* Using HTTP2, server supports multiplexing
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* h2h3 [:method: GET]
* h2h3 [:path: /whl/nightly/cpu]
* h2h3 [:scheme: https]
* h2h3 [:authority: download.pytorch.org]
* h2h3 [user-agent: curl/7.87.0]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x136810400)
> GET /whl/nightly/cpu HTTP/2
> Host: download.pytorch.org
> user-agent: curl/7.87.0
> accept: */*
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 128)!
< HTTP/2 200 
< content-type: text/html
< content-length: 1475
< date: Mon, 01 May 2023 22:01:34 GMT
< last-modified: Mon, 01 May 2023 21:48:54 GMT
< etag: "8028ba9b19531ce08160de2d8f681562"
< x-amz-server-side-encryption: AES256
< cache-control: no-cache,no-store,must-revalidate
< x-amz-version-id: d128PYUPAsQXiv_QjoKTw3ka4eaQGjqr
< accept-ranges: bytes
< server: AmazonS3
< x-cache: Miss from cloudfront
< via: 1.1 41bff299fdda9786ca0451ad8ebed114.cloudfront.net (CloudFront)
< x-amz-cf-pop: IAD55-P4
< x-amz-cf-id: 7gfKHe3kiprXGn0kUgcgl-69vQ5RHHsbuMzQcWrUCk4JXSO0PpMm0g==
< 
<!DOCTYPE html>
<html>
  <body>
    <a href="Jinja2/">Jinja2</a><br/>
    <a href="MarkupSafe/">MarkupSafe</a><br/>
    <a href="Pillow/">Pillow</a><br/>
    <a href="certifi/">certifi</a><br/>
    <a href="charset-normalizer/">charset-normalizer</a><br/>
    <a href="cmake/">cmake</a><br/>
    <a href="colorama/">colorama</a><br/>
    <a href="filelock/">filelock</a><br/>
    <a href="idna/">idna</a><br/>
    <a href="lit/">lit</a><br/>
    <a href="mpmath/">mpmath</a><br/>
    <a href="nestedtensor/">nestedtensor</a><br/>
    <a href="networkx/">networkx</a><br/>
    <a href="numpy/">numpy</a><br/>
    <a href="packaging/">packaging</a><br/>
    <a href="portalocker/">portalocker</a><br/>
    <a href="pytorch-triton/">pytorch-triton</a><br/>
    <a href="pytorch-triton-rocm/">pytorch-triton-rocm</a><br/>
    <a href="requests/">requests</a><br/>
    <a href="sympy/">sympy</a><br/>
    <a href="torch/">torch</a><br/>
    <a href="torcharrow/">torcharrow</a><br/>
    <a href="torchaudio/">torchaudio</a><br/>
    <a href="torchcsprng/">torchcsprng</a><br/>
    <a href="torchdata/">torchdata</a><br/>
    <a href="torchdistx/">torchdistx</a><br/>
    <a href="torchrec/">torchrec</a><br/>
    <a href="torchtext/">torchtext</a><br/>
    <a href="torchvision/">torchvision</a><br/>
    <a href="tqdm/">tqdm</a><br/>
    <a href="typing-extensions/">typing-extensions</a><br/>
    <a href="urllib3/">urllib3</a><br/>
  </body>
</html>
* Connection #0 to host download.pytorch.org left intact
<!--TIMESTAMP 1682977733-->%                                              
```

**Comment by huydhn** [comment] 2023-05-01 22:09
I got this one a runner `i-0977a0c14c9833401` having connection issue with the domain.  It would recover after a while though

```
[ec2-user@ip-10-0-2-166 bin]$ dig +trace download.pytorch.org

; <<>> DiG 9.11.4-P2-RedHat-9.11.4-26.P2.amzn2.13 <<>> +trace download.pytorch.org
;; global options: +cmd
.			23	IN	NS	a.root-servers.net.
.			23	IN	NS	e.root-servers.net.
.			23	IN	NS	h.root-servers.net.
.			23	IN	NS	l.root-servers.net.
.			23	IN	NS	j.root-servers.net.
.			23	IN	NS	g.root-servers.net.
.			23	IN	NS	b.root-servers.net.
.			23	IN	NS	i.root-servers.net.
.			23	IN	NS	k.root-servers.net.
.			23	IN	NS	m.root-servers.net.
.			23	IN	NS	f.root-servers.net.
.			23	IN	NS	d.root-servers.net.
.			23	IN	NS	c.root-servers.net.
;; Received 239 bytes from 10.0.0.2#53(10.0.0.2) in 1 ms

org.			172800	IN	NS	a0.org.afilias-nst.info.
org.			172800	IN	NS	a2.org.afilias-nst.info.
org.			172800	IN	NS	b0.org.afilias-nst.org.
org.			172800	IN	NS	b2.org.afilias-nst.org.
org.			172800	IN	NS	c0.org.afilias-nst.info.
org.			172800	IN	NS	d0.org.afilias-nst.org.
org.			86400	IN	DS	26974 8 2 4FEDE294C53F438A158C41D39489CD78A86BEB0D8A0AEAFF14745C0D 16E1DE32
org.			86400	IN	RRSIG	DS 8 1 86400 20230514170000 20230501160000 60955 . opuadd0OcwdtF00u7YU2OphlHlUnFDpcxNmm/kr+LKq1XTkmoKbv3V1p 9A1sA8e92m0gwJcXLug1n+oh3eHVWgoqDilmrTEiZkIX/A2ByGwborvk EvFoims10Moqvm9c4pGA2s+gpHvYjCvRN9kKY7jlIpqtSjVQdX7nZ27A 6NI9HWo3Z/pACkKvUDdnlHRguzW4pwYvzAiKjyRQBz2juritjmjgLrPD k+PbXmJuwoVCA3v8hiFq/izF8usJI59ck7XH+88zDHA31Pa8bdGCwWW4 Ll12r2TjE00Fs5vHtZHEjKD0kxT7naj1kFTj9zvb2InKy3Tbvi9vXRjd YblWog==
;; Received 828 bytes from 199.7.83.42#53(l.root-servers.net) in 0 ms

pytorch.org.		3600	IN	NS	ns4.dnsimple-edge.org.
pytorch.org.		3600	IN	NS	ns2.dnsimple.com.
pytorch.org.		3600	IN	NS	ns1.dnsimple.com.
pytorch.org.		3600	IN	NS	ns3.dnsimple.com.
gdtpongmpok61u9lvnipqor8lra9l4t0.org. 3600 IN NSEC3 1 1 0 332539EE7F95C32A GDTREA8KMJ2RNEQEN4M2OGJ26KFSUKJ7 NS SOA RRSIG DNSKEY NSEC3PARAM
gdtpongmpok61u9lvnipqor8lra9l4t0.org. 3600 IN RRSIG NSEC3 8 2 3600 20230522220428 20230501210428 25533 org. w6t8pRyHve8dFSv1Y3vyck8S5c9+qtM8dxq/bpk8ygqG9szlGlKBXpgX ogRfl2V+pXTp5XX+u0r2o9+tWhvTh+esE0mnH3LE2gFDxFjswKErbuyi OGVX8CGCdwL6Sqg50xlH53BSgNpzV7gJHUItUTf4V0IBMMfVTWl2wjaf 2Vs=
ocekajosp3a7tju9gu444s3h9p5urrgr.org. 3600 IN NSEC3 1 1 0 332539EE7F95C32A OCETQP0JNULSM0FH85MLBPPODLQ71111 NS DS RRSIG
ocekajosp3a7tju9gu444s3h9p5urrgr.org. 3600 IN RRSIG NSEC3 8 2 3600 20230522152159 20230501142159 25533 org. Fmke99ObUAPgra+a73MwXb6px8XlBc53h35zbOUo+rt+2Jo16AcmuKPh fHOuP1n1MK1qWn1eF90iw4POOy01EMO+jt1Zvk+fPHrBqgaF1g3clSfm rRpRY3UKXHBSEK/lkpUh/dEo6jxHcXntiwxlpBsa9TsNcb4Bk1o3JDO6 PMw=
;; Received 698 bytes from 199.249.112.1#53(a2.org.afilias-nst.info) in 0 ms

download.pytorch.org.	1	IN	CNAME	d21usjoq99fcb9.cloudfront.net.
;; Received 92 bytes from 162.159.24.4#53(ns1.dnsimple.com) in 2 ms

[ec2-user@ip-10-0-2-166 bin]$ nslookup download.pytorch.org
Server:		10.0.0.2
Address:	10.0.0.2#53

** server can't find download.pytorch.org: NXDOMAIN
```

**Comment by malfet** [comment] 2023-05-01 23:08
```shell
%  cat /proc/sys/net/ipv4/ip_local_port_range
32768	60999
```

**Comment by malfet** [comment] 2023-05-02 01:21
I'm not sure how `-EADDRNOTAVAIL` and good old `-ENETUNREACH` are connected, but 2nd one is caused by DNS resolving download.pytorch.org either to its IPv4 or IPv6 address

**Comment by malfet** [comment] 2023-05-02 01:25
For post-mortem of the SEV, it would be interesting to understand, whether or not ipv6 setting for cloudfront were changed recently, or vpc for runners has been tweaked.

**Comment by malfet** [comment] 2023-05-02 01:48
@jeanschmidt is there a way to get a freshly minted instance and check if it has ipv6 address there?

**Comment by malfet** [comment] 2023-05-02 02:21
Following python script can be used to reliable reproduce the situation (and shows that it's remediated if one adds `options ipv6:off` to one's `/etc/resolv.conf`:
```python
import urllib.request
try:
    for i in range(400):
       x=urllib.request.urlopen('https://download.pytorch.org/models/squeezenet1_1-b8a52dc0.pth')
except Exception as e:
    e1 = e
    print(e1)
    import pdb
    pdb.set_trace()
```

**Comment by mthrok** [comment] 2023-05-03 13:27
Have we found the root cause of this?

**Comment by DanaBCooper** [comment] 2023-05-03 13:30
Also encountering this issue intermittently. Dig alternates between good responses (multiple cloudflare) and bad responses (1 dnssimple). This is causing large amounts of CI issues

**Comment by DFEvans** [comment] 2023-05-03 14:12
I note a lot of the discussion here mentions IPv6 - does it also cover the current unavailability via IPv4 as well (DNS queries also failing), or is that a separate issue?

**Comment by DanaBCooper** [comment] 2023-05-03 14:23
I don't think there's any issue covering the IPV4. I'm still not clear why there's not a ton of people encountering this issue.

FWIW, I think the certificates are good - My current feeling is that dnssimple is having an issue, and a number of the dnssimple servers are not properly able to give the right information?

Putting download.pytorch.org into https://simpledns.plus/lookup-dg seems to implicate a number of dnssimple servers.

Locally, using dig my unsucessful runs all go through dnssimple, whilst my sucessful ones seem to go via cloudflare (CNAME)?

I don't really know enough to know what is needed, but this seems to be a quite major issue? I'm curious why more people aren't effected.

**Comment by malfet** [comment] 2023-05-03 15:06
Closing issue as no longer causing an outage in PyTorch CI (mitigated by https://github.com/pytorch/pytorch/pull/100436 , https://github.com/pytorch/pytorch/pull/100509 ,  https://github.com/pytorch/pytorch/pull/100475 and https://github.com/pytorch/pytorch/pull/100507 ), but we should continue investigating the rootcauses, and roll back above-mentioned PRs,

Few observations:
 - `download.pytorch.org` resolves to 4 IPv4 addresses and 8 IPv6 ones
 - Amazon DNS server returns NXDOMAIN after several repeated `nslookup download.pytorch.org` calls
 - `urllib.request.urlopen('https://download.pytorch.org/whl/cpu/')` on runner nodes occasionally fails with either `-EADDRNOTAVAIL`(error 99) or `-ENETUNREACH` (error 101), both of them are attempts to reach the server via IPv6, which is not configured (in case of error 99) or does not have default gateway (in case of error 101)

**Closed by malfet** 2023-05-03 15:06 UTC
Labels: ci: sev

**Comment by mthrok** [comment] 2023-05-03 15:15
@malfet what about the downstream impact? audio tutorial build process seems to be still seeing the `cannot assign address` issue. It's been happening on both CircleCI and GHA for past 5 days or something.

On CCI
https://app.circleci.com/pipelines/github/pytorch/audio/16039/workflows/7eaf6c21-95c8-495a-ad22-363572f897b1/jobs/1195968

GHA
https://github.com/pytorch/audio/actions/workflows/build_docs.yml

**Comment by DFEvans** [comment] 2023-05-03 15:21
The underlying DNS issue also affects external users (hence me asking about IPv4!). For several combinations of inputs [on the getting started page](https://pytorch.org/get-started/locally/), PyTorch's website directs users to download modules from download.pytorch.com. It seems to be the only way to get some PyTorch builds - e.g. CPU-only builds aren't distributed via PyPI, as far as I can see.

**Comment by malfet** [comment] 2023-05-03 18:27
@DFEvans can you share any links/screenshots? There shouldn't be any references to download.pytorch.com on the website

**Comment by huydhn** [comment] 2023-05-03 18:33
Oh, I think if people use nightly build, that would be the case, i.e. `pip3 install --pre torch torchvision torchaudio --index-url https://download.pytorch.org/whl/nightly/cpu`

**Comment by malfet** [comment] 2023-05-03 18:38
@DFEvans this is fine, it points to download.pytorch.org (nor `.com` as you've stated in https://github.com/pytorch/pytorch/issues/100400#issuecomment-1533238774 )

Do you have an example when above instruction fails due to the network flakiness? And can you say `ping6 download.pytorch.org` from that host?

**Comment by malfet** [comment] 2023-05-03 19:27
> @malfet what about the downstream impact? audio tutorial build process seems to be still seeing the `cannot assign address` issue. It's been happening on both CircleCI and GHA for past 5 days or something.

Yeah, it's the same IPv6 problem, but I guess we have to fix it by wrapping urlopen in torch.hub with try/catch and forcing a retry on IPv4 address...
