### ISSUE TITLE
RuntimeError: Exporting the operator uniform to ONNX opset version 10 is not supported

### ISSUE THREAD

**Issue by Bresenham** [pytorch/pytorch#70497] opened 2021-12-29 16:40 UTC
### 🐛 Describe the bug

In my Python code I export a model like this:

```
torch.onnx.export(m,
              x,
              fn
              export_params=True,
              opset_version=10,
              do_constant_folding=True,
              input_names=['input'],
              output_names=['output'],
              dynamic_axes={'input': {0: 'batch_size'},
                            'output': {0: 'batch_size'}})
```

where `m` is a `torch.nn.Module`, `x` is the input which is fed to the model and `fn` is the `filename` where to save it.

The stack trace is:

```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 301, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 728, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 358, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1054, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1008, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/symbolic_registry.py", line 129, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator uniform to ONNX opset version 10 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

### Versions

```
Collecting environment information...
PyTorch version: 1.11.0.dev20211226
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 12.1 (arm64)
GCC version: Could not collect
Clang version: 13.0.0 (clang-1300.0.29.30)
CMake version: version 3.22.1
Libc version: N/A

Python version: 3.9.9 (v3.9.9:ccb0e6a345, Nov 15 2021, 13:06:05)  [Clang 13.0.0 (clang-1300.0.29.3)] (64-bit runtime)
Python platform: macOS-12.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.21.5
[pip3] torch==1.11.0.dev20211226
[pip3] torchvision==0.11.2
[conda] Could not collect
```

**Comment by fatcat-z** [comment] 2022-01-03 10:18
@Bresenham 

Could you please switch opset_version to 11 for another try?

**Comment by Bresenham** [comment] 2022-01-03 11:03
@fatcat-z 

Thank you for your reply.

This code:

```
torch.onnx.export(m,
              x,
              fn,
              export_params=True,
              opset_version=11,
              do_constant_folding=True,
              input_names=['input'],
              output_names=['output'],
              dynamic_axes={'input': {0: 'batch_size'},
                            'output': {0: 'batch_size'}})
```

leads to this error:

```
Error
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 301, in export
    return utils.export(model, args, f, export_params, verbose, training,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 118, in export
    _export(model, args, f, export_params, verbose, training, input_names, output_names,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 728, in _export
    _model_to_graph(model, args, verbose, input_names,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
    graph = _optimize_graph(graph, operator_export_type,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 358, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1054, in _run_symbolic_function
    symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1008, in _find_symbolic_in_registry
    return sym_registry.get_registered_op(op_name, domain, opset_version)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/symbolic_registry.py", line 129, in get_registered_op
    raise RuntimeError(msg)
RuntimeError: Exporting the operator uniform to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
```

**Comment by fatcat-z** [comment] 2022-01-03 11:05
> 



> @fatcat-z
> 
> Thank you for your reply.
> 
> This code:
> 
> ```
> torch.onnx.export(m,
>               x,
>               fn,
>               export_params=True,
>               opset_version=11,
>               do_constant_folding=True,
>               input_names=['input'],
>               output_names=['output'],
>               dynamic_axes={'input': {0: 'batch_size'},
>                             'output': {0: 'batch_size'}})
> ```
> 
> leads to this error:
> 
> ```
> Error
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 301, in export
>     return utils.export(model, args, f, export_params, verbose, training,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 118, in export
>     _export(model, args, f, export_params, verbose, training, input_names, output_names,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 728, in _export
>     _model_to_graph(model, args, verbose, input_names,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 503, in _model_to_graph
>     graph = _optimize_graph(graph, operator_export_type,
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 232, in _optimize_graph
>     graph = torch._C._jit_pass_onnx(graph, operator_export_type)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/__init__.py", line 358, in _run_symbolic_function
>     return utils._run_symbolic_function(*args, **kwargs)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1054, in _run_symbolic_function
>     symbolic_fn = _find_symbolic_in_registry(domain, op_name, opset_version, operator_export_type)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/utils.py", line 1008, in _find_symbolic_in_registry
>     return sym_registry.get_registered_op(op_name, domain, opset_version)
>   File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/torch/onnx/symbolic_registry.py", line 129, in get_registered_op
>     raise RuntimeError(msg)
> RuntimeError: Exporting the operator uniform to ONNX opset version 11 is not supported. Please feel free to request support or submit a pull request on PyTorch GitHub.
> ```

Could you please share your code snippet so we can have a local repro?

**Comment by Bresenham** [comment] 2022-01-03 11:10
@fatcat-z 

```
import torch as t

from src_to_implement.model import ResNet

model = ResNet()

if __name__ == '__main__':
    x = t.randn(1, 3, 300, 300, requires_grad=True)
    m = model.cpu()
    m.eval()
    t.onnx.export(m,
                  x,
                  "onnx_export",
                  export_params=True,
                  opset_version=11,
                  do_constant_folding=True,
                  input_names=['input'],
                  output_names=['output'],
                  dynamic_axes={'input': {0: 'batch_size'},
                                'output': {0: 'batch_size'}})

```

`ResNet` is my own implementation of the `ResNet`.

**Comment by fatcat-z** [comment] 2022-01-26 15:25
> @fatcat-z
> 
> ```
> import torch as t
> 
> from src_to_implement.model import ResNet
> 
> model = ResNet()
> 
> if __name__ == '__main__':
>     x = t.randn(1, 3, 300, 300, requires_grad=True)
>     m = model.cpu()
>     m.eval()
>     t.onnx.export(m,
>                   x,
>                   "onnx_export",
>                   export_params=True,
>                   opset_version=11,
>                   do_constant_folding=True,
>                   input_names=['input'],
>                   output_names=['output'],
>                   dynamic_axes={'input': {0: 'batch_size'},
>                                 'output': {0: 'batch_size'}})
> ```
> 
> `ResNet` is my own implementation of the `ResNet`.
> 
> Edit: Could this be because of `torch.randn`? Or because of my model? If necessary, I can also share the code of my model.

No, it's not caused by torch.randn. Please share the code of your model so I can take a local debug. Thanks.

**Comment by fatcat-z** [comment] 2022-04-19 07:39
It's been over 2 months, so closing this. Feel free to open a new one if the issue still exists.

**Closed by fatcat-z** 2022-04-19 07:39 UTC
Labels: module: onnx, triaged, onnx-needs-info
