### ISSUE TITLE
Pylint Error `torch.tensor is not callable`

### ISSUE THREAD

**Issue by Microsheep** [pytorch/pytorch#24807] opened 2019-08-17 08:34 UTC
## 🐛 Bug

Pylint returns the error `torch.tensor is not callable`

## To Reproduce

```python
import torch

if __name__ == "__main__":
    t = torch.tensor([1, 2, 3], dtype=torch.float64)
```

```
>>> pipenv run pylint test.py
test.py:4:8: E1102: torch.tensor is not callable (not-callable)
```

## Expected behavior

This shall not raise pylint error

## Environment

```
PyTorch version: 1.2.0
Is debug build: No
CUDA used to build PyTorch: 10.0.130

OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
CMake version: version 3.10.2

Python version: 3.7
Is CUDA available: Yes
CUDA runtime version: 10.0.130
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti

Nvidia driver version: 418.67
cuDNN version: /usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.1

Versions of relevant libraries:
[pip3] numpy==1.17.0
[pip3] torch==1.2.0
[conda] Could not collect

Pytorch installed in Pipenv Environment
pylint==2.3.1
```

## Additional context

None

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @bhosmer @smessmer @ljk53 @ailzhang @malfet @rgommers @xuzhao9 @gramster

**Comment by rrkarim** [comment] 2019-08-17 14:16
Expected behaviour, since `torch.tensor` is built-in-method, I guess, it is a static C function implemented somewhere in `torch/csrc/...`. Though, It will be really helpful/interesting to see the full call stack.

**Comment by danilo-augusto** [comment] 2019-08-23 03:10
It's actually shadowing: there is a file named `tensor.py` at the same level of `__init__.py`.

By renaming the file from 'tensor.py' to `_tensor.py` (following the convention adopted for the other modules) and changing the import inside `__init__.py` everything should go back to normal. A small PR and targeted PR should fix this. :)

**Comment by Microsheep** [comment] 2019-08-23 12:18
Thanks for @danilo-augusto pointing the problem and solution out.
I did not notice this previously. I have submitted a pull request to fix it.

**Comment by danilo-augusto** [comment] 2019-08-23 12:44
No problem @Microsheep 😁

**Comment by ucalyptus** [comment] 2019-11-17 19:57
Any updates? @Microsheep  and @danilo-augusto ? I encountered the same error. Did https://github.com/pytorch/pytorch/pull/25093 solve this issue?

**Comment by danilo-augusto** [comment] 2019-11-20 20:15
Normally the fix is sufficiently simple to allow for a local cherry-pick, avoiding the shadowing problem. I'm not in control of the PR though.

**Comment by danilo-augusto** [comment] 2019-11-20 20:16
And of course having everybody making the same changes locally and building from scratch is very far from ideal.

**Comment by Williamongh** [comment] 2020-01-02 09:13
Happy new year everyone!

**Comment by changx03** [comment] 2020-03-19 00:15
This error is still popping out even with 
```
generated-members=numpy.*,torch.*
```
in the `.pylintrc` file

**Comment by davidbnk** [comment] 2020-07-02 20:26
```
"python.linting.pylintArgs": [
    "--errors-only",
    "--generated-members=numpy.*,torch.*,*.data,*.grad"
]
```
In settings.json fixes for me

**Comment by ElsaBroso1** [comment] 2020-11-30 11:10
I have the same error, but I cannot find the file tensor.py. Where is it suppose to be?
![image](https://user-images.githubusercontent.com/75251123/100603120-f77d4580-3304-11eb-98bd-3ab49a83dadb.png)

**Comment by ViktorooReps** [comment] 2020-12-06 07:28
Had the same error with conda environment named after torch. Renaming the environment helped.

**Comment by zzxn** [comment] 2020-12-18 08:16
This problem comes back now for the newest version (1.7.1). It seems that `tensor.py` still exist.

**Comment by zou3519** [comment] 2021-01-22 16:39
Tentatively marking as high-pri due to user activity. The fix (renaming a file) should be relatively straightforward but might require mucking around in details of how the PyTorch python package is organized.

**Comment by ezyang** [comment] 2021-01-25 18:20
I think it's not actually BC-breaking to rename torch.tensor module because it seems like it is impossible to actually access it using `import torch.tensor`

**Closed** 2021-03-09 19:35 UTC
Labels: high priority, module: internals, module: typing, small, triaged
