### ISSUE TITLE
PyTorch android failing after 29/01/20 nightly

### ISSUE THREAD

**Issue by vishal-wiai** [pytorch/pytorch#32858] opened 2020-01-31 07:03 UTC
I am using a SSD object detection model to run on android using jit trace, developed in PyTorch 1.3.

2 days back, I was using the nightly `pytorch_android:1.5.0-SNAPSHOT` it was working fine and I was getting the expected output. But today the app is crashing and giving the following error `Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 17354`.

After this I tried other versions also.

`pytorch_android:1.4.0` and `pytorch_android:1.4.0-SNAPSHOT` : This is giving different output. For the same input Tensor, output tensors in python and android are coming out to be different.

`pytorch_android:1.3.0` : `com.facebook.jni.CppException: false CHECK FAILED at ../c10/core/Backend.h (tensorTypeIdToBackend at ../c10/core/Backend.h:106)`

Very confused with what’s going on! Can I revert back to the nightly build which was 2 days old?

cc @ezyang @gchanan @zou3519

**Comment by ljk53** [comment] 2020-02-03 18:23
@vishal-wiai thanks for reporting your problem!

Looks like there are 3 issues:
- 1.3.0: there are some known issues with initial experimental 1.3.0 release, which we fixed in later releases, so it's expected to fail with some models.
- 1.4.0: there were some related discussions around numerical difference between python v.s. android: https://discuss.pytorch.org/t/module-output-slightly-off-on-android/62838 - sometimes it can be caused by different jpeg libraries used to decode jpg into tensor. Could you please share more about your model structure / input?
- 1.5.0-snapshot: SIGSEGV sounds like master was broken. Could you please share the model you used to test? BTW, when it was working, did 1.5.0 produce the consistent output between python and android?

**Comment by ngimel** [comment] 2022-02-07 20:17
closing due to age

**Closed by ngimel** 2022-02-07 20:17 UTC
Labels: high priority, oncall: mobile
