### ISSUE TITLE
[JIT] Reverse slicing List gives runtime error

### ISSUE THREAD

**Issue by eellison** [pytorch/pytorch#27543] opened 2019-10-08 15:52 UTC
## To Reproduce

```
@torch.jit.script
def fn():
    a = [1, 2, 3, 4]
    return a[::-1]
fn()
```

> RuntimeError: vector::_M_range_check The above operation failed in interpreter, with the following stack trace: at test/test_jit.py:6263:19
        @torch.jit.script
        def test():
            a = [1, 2, 3, 4]
            return a[::-1]
                   ~~~~~~ <--- HERE



This should either give a compile error, or work (better), but it should not compile and be unsupported.

cc @suo

**Comment by driazati** [comment] 2020-01-23 21:06
Closing as duplicate of #25135

**Closed by driazati** 2020-01-23 21:06 UTC
Labels: jit
