### ISSUE TITLE
Exception in thread pool task: !completed() INTERNAL ASSERT FAILED

### ISSUE THREAD

**Issue by rafi-cohen** [pytorch/pytorch#53717] opened 2021-03-10 15:44 UTC
## 🐛 Bug

An iternal assert fails when making RPC calls using a `UserRRef`. This only happens if a device map is set in the `TensorPipeRpcBackendOptions`

## To Reproduce

1. init RPC with the TensorPipe backend and a device mapping
2. Get a `UserRRef` using an `rpc.remote` call
3. Make an RPC call using the `UserRRef`
4. The following error occurs:

```
[E thread_pool.cpp:112] Exception in thread pool task: !completed() INTERNAL ASSERT FAILED at "/opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/core/ivalue_inl.h":534, please report a bug to PyTorch. 
Exception raised from setErrorInternal at /opt/conda/conda-bld/pytorch_1614378083779/work/aten/src/ATen/core/ivalue_inl.h:534 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0x42 (0x7f6ec18e02f2 in path/to/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #1: <unknown function> + 0x7377cf (0x7f6f188937cf in path/to/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #2: std::_Function_handler<void (), c10::ivalue::Future::then(std::function<c10::IValue ()>, std::shared_ptr<c10::Type>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) + 0x6e (0x7f6f188938ee in path/to/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #3: std::_Function_handler<void (), at::cuda::CUDAFuture::wrapCallback(std::function<void ()>)::{lambda()#1}>::_M_invoke(std::_Any_data const&) + 0x336 (0x7f6f18c08e56 in path/to/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #4: <unknown function> + 0xaa1621 (0x7f6f18bfd621 in path/to/env/lib/python3.8/site-packages/torch/lib/libtorch_python.so)
frame #5: c10::ThreadPool::main_loop(unsigned long) + 0x26b (0x7f6ec18d107b in path/to/env/lib/python3.8/site-packages/torch/lib/libc10.so)
frame #6: <unknown function> + 0xc9067 (0x7f6f274a0067 in path/to/env/lib/python3.8/site-packages/torch/lib/../../../../libstdc++.so.6)
frame #7: <unknown function> + 0x76db (0x7f6f4b52c6db in /lib/x86_64-linux-gnu/libpthread.so.0)
frame #8: clone + 0x3f (0x7f6f4a8a871f in /lib/x86_64-linux-gnu/libc.so.6)
```

Reproduction code:
It's somewhat long, sorry. Most of this is based on the example code in the documentation. The issue is in lines 50-55 (surrounded by `####` lines).
```python
import os

import torch
from torch import multiprocessing as mp
from torch.distributed import rpc
from torch.distributed.rpc import TensorPipeRpcBackendOptions


def add(x, y):
    print(x)  # tensor([1., 1.], device='cuda:1')
    return x + y, (x + y).to(2)


class Adder:
    def __init__(self):
        pass

    def add(self, x, y):
        return add(x, y)


def worker0():
    options = TensorPipeRpcBackendOptions(
        num_worker_threads=8,
        device_maps={"worker1": {0: 1}}
        # maps worker0's cuda:0 to worker1's cuda:1
    )
    options.set_device_map("worker1", {1: 2})
    # maps worker0's cuda:1 to worker1's cuda:2

    rpc.init_rpc(
        "worker0",
        rank=0,
        world_size=2,
        backend=rpc.BackendType.TENSORPIPE,
        rpc_backend_options=options
    )

    x = torch.ones(2)
    rets = rpc.rpc_sync("worker1", add, args=(x.to(0), 1))
    # The first argument will be moved to cuda:1 on worker1. When
    # sending the return value back, it will follow the invert of
    # the device map, and hence will be moved back to cuda:0 and
    # cuda:1 on worker0
    print(rets[0])  # tensor([2., 2.], device='cuda:0')
    print(rets[1])  # tensor([2., 2.], device='cuda:1')

    print('so far so good')
    ####################################################
    x = torch.ones(2)
    adder_rref = rpc.remote("worker1", Adder)
    print('rref created successfully')
    rets = adder_rref.rpc_sync().add(x.to(0), 1)
    print(rets[0])  # tensor([2., 2.], device='cuda:0')
    print(rets[1])  # tensor([2., 2.], device='cuda:1')
    ####################################################
    rpc.shutdown()


def worker1():
    options = TensorPipeRpcBackendOptions(
        num_worker_threads=8,
    )

    rpc.init_rpc(
        "worker1",
        rank=1,
        world_size=2,
        backend=rpc.BackendType.TENSORPIPE,
        rpc_backend_options=options
    )

    rpc.shutdown()


def run(rank):
    os.environ['MASTER_ADDR'] = 'localhost'
    os.environ['MASTER_PORT'] = '12355'
    if rank == 0:
        worker0()
    else:
        worker1()


def main():
    mp.start_processes(run, nprocs=2, start_method='fork')


if __name__ == '__main__':
    main()
```

This code outputs:
```
tensor([1., 1.], device='cuda:1')
tensor([2., 2.], device='cuda:0')
tensor([2., 2.], device='cuda:1')
so far so good
rref created successfully
```
followed by the failed assertion error message.
The output indicates that `rpc.rpc_sync(...)` works as expected, while `rref.rpc_sync()...` crashes.

## Expected behavior

Should not crash.

## Environment
<details>
<summary>collect_env.py output</summary>
PyTorch version: 1.8.0
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect

Python version: 3.8 (64-bit runtime)
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 460.32.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] numpy==1.19.2
[pip3] torch==1.8.0
[pip3] torchaudio==0.8.0a0+a751e1d
[pip3] torchvision==0.9.0
[conda] blas                      1.0                         mkl  
[conda] cudatoolkit               11.1.1               h6406543_8    conda-forge
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] mkl                       2020.4             h726a3e6_304    conda-forge
[conda] mkl-service               2.3.0            py38h1e0a361_2    conda-forge
[conda] mkl_fft                   1.3.0            py38h5c078b8_1    conda-forge
[conda] mkl_random                1.2.0            py38hc5bc63f_1    conda-forge
[conda] numpy                     1.19.2           py38h54aff64_0  
[conda] numpy-base                1.19.2           py38hfa32c7d_0  
[conda] pytorch                   1.8.0           py3.8_cuda11.1_cudnn8.0.5_0    pytorch
[conda] torchaudio                0.8.0                      py38    pytorch
[conda] torchvision               0.9.0                py38_cu111    pytorch
</details>

PyTorch was installed using `conda env create -f environment.yml`, with the following `environment.yml`:
```yaml
name: env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch=1.8
  - cudatoolkit=11.1
  - torchvision
  - torchaudio
  - tqdm
  - viztracer
  - PyYAML
```
## Additional context

I'm not entirely sure about this, but I think that even if communication is done using CPU, as long as a device map is set, the error occurs when making `UserRRef` RPC calls.

cc @ezyang @gchanan @zou3519 @bdhirsh @jbschlosser @anjali411 @pietern @mrshenli @pritamdamania87 @zhaojuanmao @satgera @rohan-varma @gqchen @aazzolini @osalpekar @jiayisuse @agolynski @SciPioneer @H-Huang @mrzzd @cbalioglu

**Comment by rohan-varma** [comment] 2021-03-15 21:36
I can verify that this assert triggers with 1.8.0, but this script seems to successfully pass with nightly/master pytorch (verified by running the loop 100 times). Could you try using nightly/master and verify that fixes your issue?

We will also probably cherry pick the fix into 1.8.1 release. @mrshenli / @lw , do we know what PR fixed this and are we tracking to cherry pick it?

**Comment by rohan-varma** [comment] 2021-03-15 21:43
As a side note, I initially ran this on a 2 gpu machine but this needs at least 3 gpus, and the error message I got:
```
Invalid device_map configuration on {name}:\n"
                        f"device_maps = {device_maps}
```

can probably be enhanced with the issue that there's not enough devices.

**Comment by lw** [comment] 2021-03-16 07:47
@rafi-cohen Thanks for the detailed bug report!

Based on the stack trace, this appears to happen when invoking the callback of a CUDAFuture (see frames #2 and #3, which come from `c10::ivalue::Future::then` and `at::cuda::CUDAFuture::wrapCallback`). It appears we're double-setting a future as complete, though the only future we're handling at that point is the "child" future, i.e., the one returned by the `then` method. One possible explanation could be that the caller of `then` has accidentally already set that future as complete on its own, and thus when the future actually becomes complete we fail. However, a more likely option is that this bug is entirely within the `then` method itself, which looks like this:
https://github.com/pytorch/pytorch/blob/2ecb2c79312eac6924182fe343dc3cd9a205305c/aten/src/ATen/core/ivalue_inl.h#L471-L475
If an exception is thrown by the `markCompleted` method, after it has already set the flag, then this exception will be caught and we'll call `setError`, which will observe the flag as already being set and thus will fail that assert.

Since we're raising an exception while handling another exception, we're unfortunately hiding the root cause of the problem. An educated guess about what could be going on is that could come from CUDAFuture's `postMarkCompletedHook`. We know that that method can sometimes error out and raise, in particular when extracting DataPtrs from an IValue, if that IValue is unsupported. @mrshenli you've been taking care of this, do you think this could be the issue, and do you remember when this was fixed? The best candidate I found is #51820.

**Comment by rafi-cohen** [comment] 2021-03-16 07:59
> I can verify that this assert triggers with 1.8.0, but this script seems to successfully pass with nightly/master pytorch (verified by running the loop 100 times). Could you try using nightly/master and verify that fixes your issue?

Tried to run on nightly - the issue did not occur.

**Comment by rohan-varma** [comment] 2021-03-16 16:41
@lw Since this seems like it throws in `postMarkCompletedHook` should `fut->setError` be changed to `fut->setErrorIfNeeded`?

**Comment by lw** [comment] 2021-03-16 19:31
In this case I think the fault is on `postMarkCompletedHook` which should not throw but should instead "gracefully" set the future to error in order to properly inform the user that something went wrong. If we just replaced `setError` with `setErrorIfNeeded` in `then` the end result would be that the future is still marked as successfully completed, whereas the CUDA part isn't set-up correctly, which could lead to silent CUDA synchronization/correctness issues.

I do think however that the above code could be somewhat rewritten to make it easier to investigate these bugs in the future. I don't think C++ has an `else` statement in its `try`, but if it did I'd imagine something like this:
```
try {
  value = cb();
} catch (std::exception&) {
  fut->setError(std::current_exception)));
} else {
  // If this fails it could make sense to *fatal*, as if it had a `noexcept` flag.
  fut->markCompleted(std::move(value));
}

**Comment by rohan-varma** [comment] 2021-03-16 20:53
I guess we could just simulate `else` by doing:

```
exception = False
try {
  value = cb();
} catch (std::exception&) {
exception = True
  fut->setError(std::current_exception)));
}

if (!exception /* try-else */) {
  // If this fails it could make sense to *fatal*, as if it had a `noexcept` flag.
  fut->markCompleted(std::move(value));
}
```

**Comment by pritamdamania87** [comment] 2021-03-23 02:24
These types of errors happen quite often, I have a simple PR to improve the error reporting here somewhat.

**Comment by rohan-varma** [comment] 2021-03-23 02:38
@pritamdamania87 oops, I just sent out an error handling PR as well but yours is probably a better way to approach it. I'll go ahead and close mine

**Comment by rohan-varma** [comment] 2021-04-30 22:02
It looks like the actual crash is fixed in nightlies and we've added a couple PRs to improve error handling, so I'll go ahead and close this one out. Feel free to reopen if there are additional questions/issues.

**Closed by rohan-varma** 2021-04-30 22:02 UTC
Labels: high priority, module: assert failure, module: crash, oncall: distributed, triage review, triaged
