### ISSUE TITLE
TH_TENSOR_DIM_APPLY3 needs OpenMP support

### ISSUE THREAD

**Issue by danieljl** [pytorch/pytorch#1799] opened 2017-06-14 02:59 UTC
It should calculate topk for each dimension in parallel.

**Comment by soumith** [comment] 2017-07-13 14:16
More generally, the issue is:
- Add OpenMP support to [TH_TENSOR_DIM_APPLY3](https://github.com/pytorch/pytorch/blob/96febbb7622db6864542bd0e8735774b715c6a12/torch/lib/TH/THTensorDimApply.h#L4)
- topk pointer: https://github.com/pytorch/pytorch/blob/master/torch/lib/TH/generic/THTensorMath.c#L2547-L2566

**Comment by albanD** [comment] 2019-11-27 18:37
Closing as topk does not use this macro, has been moved to ATen and now uses OpenMP.

**Closed by albanD** 2019-11-27 18:37 UTC
Labels: feature, todo
