### ISSUE TITLE
`torch.compile` failed on `torch.bitwise_xor` with a constant python number

### ISSUE THREAD

**Issue by Co1lin** [pytorch/pytorch#93224] opened 2023-01-29 17:49 UTC
### 🐛 Describe the bug

This is similar to #92324 .

Program to reproduce:

```python
import torch

def fn(x):
    return torch.bitwise_xor(x, 18)
    # return torch.bitwise_xor(x, torch.tensor([18])) # works fine

x = torch.rand(2).int()
o = fn(x)
print('==== Eager mode OK! ====')
compiled = torch.compile(fn, fullgraph=True)
print(compiled(x))
print('==== compile mode OK! ====')
```

<details>
<summary>Error logs</summary>

```python
❯ python bug.py
==== Eager mode OK! ====
Traceback (most recent call last):
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1162, in run_node
    return node.target(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_subclasses/fake_tensor.py", line 933, in __torch_dispatch__
    r = func(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_ops.py", line 284, in __call__
    return self._op(*args, **kwargs or {})
RuntimeError: aten::bitwise_xor() Expected a value of type 'Tensor' for argument 'other' but instead found type 'int'.
Position: 1
Value: 18
Declaration: aten::bitwise_xor.Tensor(Tensor self, Tensor other) -> Tensor
Cast error details: Unable to cast 18 to Tensor

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1121, in get_fake_value
    return wrap_fake_exception(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 783, in wrap_fake_exception
    return fn()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1122, in <lambda>
    lambda: run_node(tx.output, node, args, kwargs, nnmodule)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1174, in run_node
    raise RuntimeError(
RuntimeError: Failed running call_function <built-in method bitwise_xor of type object at 0x7f76f6d39e20>(*(FakeTensor(FakeTensor(..., device='meta', size=(2,), dtype=torch.int32), cpu), 18), **{}):
aten::bitwise_xor() Expected a value of type 'Tensor' for argument 'other' but instead found type 'int'.
Position: 1
Value: 18
Declaration: aten::bitwise_xor.Tensor(Tensor self, Tensor other) -> Tensor
Cast error details: Unable to cast 18 to Tensor
(scroll up for backtrace)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/JawTitan/colin-data/code/my_proj/dir/bug.py", line 11, in <module>
    print(compiled(x))
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 211, in _fn
    return fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/eval_frame.py", line 332, in catch_errors
    return callback(frame, cache_size, hooks)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 103, in _fn
    return fn(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 261, in _convert_frame_assert
    return _compile(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 160, in time_wrapper
    r = func(*args, **kwargs)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 323, in _compile
    out_code = transform_code_object(code, transform)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/bytecode_transformation.py", line 341, in transform_code_object
    transformations(instructions, code_options)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/convert_frame.py", line 310, in transform
    tracer.run()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1727, in run
    super().run()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 564, in run
    and self.step()
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 527, in step
    getattr(self, inst.opname)(inst)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 333, in wrapper
    return inner_fn(self, inst)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 1000, in CALL_FUNCTION
    self.call_function(fn, args, {})
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/symbolic_convert.py", line 461, in call_function
    self.push(fn.call_function(self, args, kwargs))
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/variables/torch.py", line 471, in call_function
    tensor_variable = wrap_fx_proxy(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 764, in wrap_fx_proxy
    return wrap_fx_proxy_cls(
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/variables/builder.py", line 799, in wrap_fx_proxy_cls
    example_value = get_fake_value(proxy.node, tx)
  File "/home/colin/miniconda3/envs/py39/lib/python3.9/site-packages/torch/_dynamo/utils.py", line 1141, in get_fake_value
    raise TorchRuntimeError() from e
torch._dynamo.exc.TorchRuntimeError: 

from user code:
   File "/JawTitan/colin-data/code/my_proj/dir/bug.py", line 4, in fn
    return torch.bitwise_xor(x, 18)

Set torch._dynamo.config.verbose=True for more information


You can suppress this exception and fall back to eager by setting:
    torch._dynamo.config.suppress_errors = True
```
</details>

### Versions

```python
Collecting environment information...
PyTorch version: 2.0.0.dev20230129+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Ubuntu 20.04.5 LTS (x86_64)
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: version 3.25.0
Libc version: glibc-2.31

Python version: 3.9.15 (main, Nov 24 2022, 14:31:59)  [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.4.0-137-generic-x86_64-with-glibc2.31
Is CUDA available: True
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: 
GPU 0: NVIDIA RTX A6000
GPU 1: NVIDIA RTX A6000
GPU 2: NVIDIA RTX A6000
GPU 3: NVIDIA RTX A6000

Nvidia driver version: 510.68.02
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.2.2
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.2.2
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] numpy==1.23.5
[pip3] pytorch-triton==2.0.0+0d7e753227
[pip3] torch==2.0.0.dev20230129+cu117
[pip3] torchaudio==2.0.0.dev20230129+cu117
[pip3] torchtriton==2.0.0+0d7e753227
[pip3] torchvision==0.15.0.dev20230129+cu117
[conda] numpy                     1.23.5                   pypi_0    pypi
[conda] pytorch-triton            2.0.0+0d7e753227          pypi_0    pypi
[conda] torch                     2.0.0.dev20230129+cu117          pypi_0    pypi
[conda] torchaudio                2.0.0.dev20230129+cu117          pypi_0    pypi
[conda] torchtriton               2.0.0+0d7e753227          pypi_0    pypi
[conda] torchvision               0.15.0.dev20230129+cu117          pypi_0    pypi
```

cc @ezyang @gchanan @zou3519 @soumith @msaroufim @wconstab @ngimel @bdhirsh @mlazos @voznesenskym @yanboliang @penguinwu @anijain2305 @EikanWang @jgong5 @Guobing-Chen @XiaobingSuper @zhuhaozhe @blzheng @Xia-Weiwen @wenzhe-nrv @jiayisunx @peterbell10 @desertfire @chunyuan-w

**Comment by kshitij12345** [comment] 2023-02-06 05:00
Failure seems to be arising from `FakeTensor`.

`torch.add(x, 18)` works while `torch.bitwise_xor(x, 18)` doesn't. `torch.add` gets redispatched to `_refs.add` which correctly handles the input. But `torch.bitwise_xor` doesn't and it errors out. I tried to find if there is a special registration mechanism for FakeTensor for TensorXScalar overloads but couldn't find any.

NOTE: Both are registered as decomposition in `_refs/__init__.py`.

```python
import torch

def fn(x):
    # Dispatcher:
    # [call] op=[aten::add.Tensor], key=[PythonTLSSnapshot]
    #   [redispatchBoxed] op=[aten::add.Tensor], key=[AutogradCPU]
    #    [redispatch] op=[aten::add.Tensor], key=[Python]
    #     [callBoxed] op=[aten::add.Tensor], key=[Meta]
    #      [callBoxed] op=[prims::add], key=[Meta]
    #       [call] op=[aten::empty_strided], key=[BackendSelect]
    #        [redispatch] op=[aten::empty_strided], key=[Meta]
    #     [call] op=[aten::detach], key=[Meta]
    torch.add(x, 18)  # works

    # torch.lt(x, 18)  # works

    # Dispatcher:
    # [call] op=[aten::bitwise_xor.Scalar], key=[PythonTLSSnapshot]
    #   [redispatchBoxed] op=[aten::bitwise_xor.Scalar], key=[AutogradCPU]
    #    [call] op=[aten::bitwise_xor.Tensor], key=[PythonTLSSnapshot]
    #     [redispatchBoxed] op=[aten::bitwise_xor.Tensor], key=[AutogradCPU]
    #      [redispatchBoxed] op=[aten::bitwise_xor.Tensor], key=[Python]  # Errors!
    torch.bitwise_xor(x, 18)

from torch._subclasses.fake_tensor import (
    FakeTensorMode,
)

with FakeTensorMode():
    x = torch.ones(2, device=torch.device('cpu'), dtype=torch.int)
    fn(x)

# torch.ops.add.Tensor -> refs.add -> prims.add

# torch.ops.bitwise_xor.Tensor - Crash

```

**Comment by peterbell10** [comment] 2023-02-06 11:17
I think the main problem is that `bitwise_xor.Scalar` is registered as `CompositeImplicitAutograd` but uses `wrapped_scalar_tensor` which creates a tensor without dispatching.  `add.Scalar` uses `wrapped_scalar_tensor` as well, but is registered as `CompositeExplicitAutograd` so the tracing calls into the meta implementation instead.

**Comment by wconstab** [comment] 2023-02-06 18:56
I convinced myself, at least, that in the DDPOptimizer case it is incorrect to not force fake-mode.  We should be in a fake mode since we are doing fake tracing with a model that's converted manually to fake, but we neglected to account for composite ops that might create tensors internally.  So the 'rule' would be if you're running fake models, make sure you're in a fake mode.  In our case, we had the fake mode already, we just hadn't activated it as a contextmanager.

I'm not sure if that's helpful in this case.  Where are we missing the fake mode in torch.compile stack?

**Comment by peterbell10** [comment] 2023-02-06 19:51
I don't think the DDPOptimizer case is the same because `where.Scalar` creates the tensor by dispatching `at::scalar_tensor` which allows fake-mode to create a FakeTensor. In this case there is no dispatch for FakeTensorMode to intercept.

**Comment by ngimel** [comment] 2023-02-06 20:59
Yep ok, so we should audit cases where scalar-tensor conversion happens without dispatch?

**Comment by kshitij12345** [comment] 2023-02-07 05:37
BinaryOps which fail with same error

```
bitwise_or
bitwise_xor
__ror__
__rxor__
special.chebyshev_polynomial_t
special.chebyshev_polynomial_u
special.chebyshev_polynomial_v
special.chebyshev_polynomial_w
special.hermite_polynomial_h
special.hermite_polynomial_he
special.laguerre_polynomial_l
special.legendre_polynomial_p
special.shifted_chebyshev_polynomial_t
special.shifted_chebyshev_polynomial_u
special.shifted_chebyshev_polynomial_v
special.shifted_chebyshev_polynomial_w
```

<details>

<summary> Script </summary>

```python
from torch._subclasses.fake_tensor import (
    FakeTensorMode,
)
from torch.testing._internal.common_methods_invocations import op_db, BinaryUfuncInfo

binary_ops = list(filter(lambda op: isinstance(op, BinaryUfuncInfo), op_db))

for op in binary_ops:
    if op.supports_rhs_python_scalar:
        try:
            with FakeTensorMode():
                x = torch.ones(2, device=torch.device('cpu'), dtype=torch.int)
                op(x, 18)
        except Exception as e:
            if "Expected a value of type 'Tensor' for argument" in str(e):
                print(op.name)
            else:  # If different error from expected
                print(op.name)
                print(e)
                print()
            continue

    if op.supports_one_python_scalar:
        try:
            with FakeTensorMode():
                x = torch.ones(2, device=torch.device('cpu'), dtype=torch.int)
                op(18, x)
        except Exception as e:
            if "Expected a value of type 'Tensor' for argument" in str(e):
                print(op.name)
            else:  # If different error from expected
                print(op.name)
                print(e)
                print()
            continue
    
    if op.supports_two_python_scalars:
        try:
            with FakeTensorMode():
                op(18, 18)
        except Exception as e:
            if "Expected a value of type 'Tensor' for argument" in str(e):
                print(op.name)
            else:  # If different error from expected
                print(op.name)
                print(e)
                print()
            continue

```

</details>

**Comment by alanhe151220037** [comment] 2023-09-05 10:42
> I think the main problem is that `bitwise_xor.Scalar` is registered as `CompositeImplicitAutograd` but uses `wrapped_scalar_tensor` which creates a tensor without dispatching. `add.Scalar` uses `wrapped_scalar_tensor` as well, but is registered as `CompositeExplicitAutograd` so the tracing calls into the meta implementation instead.

@peterbell10  Sorry for bothering. I think this problem in detail is caused by that, tensor generated by `wrapped_scalar_tensor` will be roll back into scalar when dispatched to corresponding python method with key `python`. And I also find another kind of situation here. `torch.true_divide(tensor_a, scalar_b)` is fine with `FakeTensorMode`, but `true_divide.Scalar` is registered as `CompositeImplicitAutograd`  and  uses `wrapped_scalar_tensor` as well. Two reasons make for this:
https://github.com/pytorch/pytorch/blob/efc7c366f4fbccf649454726a96df291c8a9df43/torch/csrc/utils/python_arg_parser.cpp#L86-L99
1. Firstly, `true_divide` is in the above `allowed` list, which makes we always calling `true_divide.Tensor` in binding function even in the situation of `torch.floor_divide(tensor_a, scalar_b)` and, it also converts the scalar into tensor just like `wrapped_scalar_tensor`.
https://github.com/pytorch/pytorch/blob/efc7c366f4fbccf649454726a96df291c8a9df43/torch/csrc/utils/python_arg_parser.cpp#L1745-L1746 
2. Secondly, the implementation  of `true_divide.Tensor` simply called `div.Tensor`. But `div` is also in the above list, so it could accept scalar.

Finally, I still have two problem here.
- Why bitwise operators not in this `allowed` list? What is the rule for ops chosen in this list? And is it that scalar variants of these ops will never be called in python what we want?
- Why `bitwise_and.Scalar` is registered as `CompositeExplicitAutograd` but `bitwise_or.Scalar` and `bitwise_xor.Scalar` are registered as `CompositeImplicitAutograd` ? And Similar inconsistent situations also occur in many other funcs that have scalar variants. Some use `CompositeImplicitAutograd` and some other use `CompositeExplicitAutograd`. So, what is the rule for we to choose between these two key for the scalar variants?
https://github.com/pytorch/pytorch/blob/efc7c366f4fbccf649454726a96df291c8a9df43/aten/src/ATen/native/README.md?plain=1#L315-L324

**Comment by alanhe151220037** [comment] 2023-09-05 15:33
> @alanhe151220037 would you be interested in submitting a PR to update the dispatch to `CompositeExplicitAutograd`?
@peterbell10  Sure, I'll submit a PR soon  : )

**Comment by australopitek** [comment] 2023-09-29 09:48
Hi @alanhe151220037,
when do you plan to submit a PR? Do you think it will be included in the upcoming PT2.1?

**Comment by alanhe151220037** [comment] 2023-09-30 11:30
> Hi @alanhe151220037, when do you plan to submit a PR? Do you think it will be included in the upcoming PT2.1?

sry, I was too busy these days. But I plan to submit a PR in a week.

**Comment by jay746** [comment] 2023-10-11 10:21
@alanhe151220037 did PR merged?

**Closed** 2023-10-14 15:54 UTC
Labels: triaged, oncall: pt2, module: inductor
