### ISSUE TITLE
REPRODUCIBILITY about torch_geometric of Gat

### ISSUE THREAD

**Issue by bourne-3** [pytorch/pytorch#75179] opened 2022-04-04 11:06 UTC
### 📚 The doc issue

I encounter the problem about REPRODUCIBILITY.  Each time i run model trainning and then evaluate, the result show different even the seed had been set.
That is confuse me a lot.
Pre
1、i have set the seed to accordding to the post
like below
```
    os.environ['PYTHONHASHSEED'] = str(my_seed)
    random.seed(my_seed)
    np.random.seed(my_seed)
    torch.manual_seed(my_seed)
    torch.cuda.manual_seed(my_seed)
    torch.cuda.manual_seed_all(my_seed)

    torch.backends.cudnn.benchmark = False  
    torch.backends.cudnn.deterministic = True

    torch.backends.cudnn.enabled = False
```

2、already read the doc https://pytorch.org/docs/stable/notes/randomness.html
The cuda of mine is 11.4 , GPU is RTX A4000
so i set => torch.set_deterministic(True) .  The error show like this
```
  File "/home/shelly/.conda/envs/pyt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shelly/bourne/experiment/MTAG-hire/graph_model/dynamic_gnn_with_mtgat_prune.py", line 42, in forward
    nodes_feature = self.gcn_conv1(x, edge_index)
  File "/home/shelly/.conda/envs/pyt/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/shelly/.conda/envs/pyt/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 161, in forward
    self.improved, self.add_self_loops, dtype=x.dtype)
  File "/home/shelly/.conda/envs/pyt/lib/python3.6/site-packages/torch_geometric/nn/conv/gcn_conv.py", line 62, in gcn_norm
    deg = scatter_add(edge_weight, col, dim=0, dim_size=num_nodes)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/home/shelly/.conda/envs/pyt/lib/python3.6/site-packages/torch_scatter/scatter.py", line 22, in scatter_add
            size[dim] = int(index.max()) + 1
        out = torch.zeros(size, dtype=src.dtype, device=src.device)
        return out.scatter_add_(dim, index, src)
               ~~~~~~~~~~~~~~~~ <--- HERE
    else:
        return out.scatter_add_(dim, index, src)
RuntimeError: scatter_add_cuda_kernel does not have a deterministic implementation, but you set 'torch.set_deterministic(True)'. You can turn off determinism just for this operation if that's acceptable for your application. You can also file an issue at https://github.com/pytorch/pytorch/issues to help us prioritize adding deterministic support for this operation.
```
Can someone do me a favor to handle it ..?

cc @mruberry @kurtamohler

**Comment by mruberry** [comment] 2022-04-04 13:59
Duplicate of https://github.com/pytorch/pytorch/issues/50469

**Closed by mruberry** 2022-04-04 13:59 UTC
Labels: triaged, module: determinism
