### ISSUE TITLE
No padding_idx argument in the EmbeddingBag layer

### ISSUE THREAD

**Issue by guxd** [pytorch/pytorch#3194] opened 2017-10-20 02:49 UTC
The EmbeddingBag layer serves as Embedding+torch.mean().
However, it does not support the 'padding_idx' argument which is included in the Embedding layer.
Is it possible to support the argument as well?

cc @ezyang @gchanan @zou3519 @bdhirsh @albanD @mruberry

**Comment by vadimkantorov** [comment] 2019-12-10 18:13
Stumbled upon this as well...

**Comment by ezyang** [comment] 2020-11-13 15:57
Increasing priority based on user activity

**Comment by uwaisiqbal** [comment] 2020-11-22 19:15
Is anyone actively working on this?

**Comment by mruberry** [comment] 2020-11-26 23:23
@uwaisiqbal I don't think so.

**Comment by kurtamohler** [comment] 2020-12-01 16:59
I can start adding this

**Comment by uwaisiqbal** [comment] 2020-12-11 10:06
Nice - how long before this can be merged in and released?

**Comment by kurtamohler** [comment] 2020-12-11 16:33
@uwaisiqbal , I'm planning to open a PR within the next couple days. Currently there are a few problems I need to fix.

**Comment by uwaisiqbal** [comment] 2020-12-14 10:23
Awesome nice work @kurtamohler. Quick question- does the implementation ignore the zero tensors from the padding idx when taking the mean?

**Comment by kurtamohler** [comment] 2020-12-14 17:30
@uwaisiqbal, no, the zeros are taken into account for the reduction (mean/max/sum). EmbeddingBag is just a more efficient way of calculating the result we would get from an Embedding followed by a reduction, and in that case Embedding applies the zero padding before the reduction is performed, so EmbeddingBag should have the same behavior.

**Comment by vadimkantorov** [comment] 2020-12-14 17:42
For the `mean` case, the denomintor is well the number of non-pad tokens, right?

**Comment by kurtamohler** [comment] 2020-12-14 17:56
@vadimkantorov, the denominator includes the number of zeros. Here's an example comparing the results of Embedding+mean to EmbeddingBag. They produce the same result, so we know that EmbeddingBag's mean takes the zeros into account the same way that Embedding+mean does.

```
>>> weights = torch.randn(3, 4)
>>> weights
tensor([[-1.0225, -0.1379,  0.9568, -0.9563],
        [ 0.3814, -0.1118, -0.0506, -0.6546],
        [ 2.6506, -1.6717, -0.8073, -0.5124]])
>>> indices = torch.tensor([1, 2, 0])
>>> res_embedding = torch.nn.functional.embedding(indices, weights, padding_idx=0)
>>> res_embedding
tensor([[ 0.3814, -0.1118, -0.0506, -0.6546],
        [ 2.6506, -1.6717, -0.8073, -0.5124],
        [ 0.0000,  0.0000,  0.0000,  0.0000]])
>>> res_embedding_mean = res_embedding.mean(dim=0)
>>> res_embedding_mean
tensor([ 1.0107, -0.5945, -0.2859, -0.3890])
>>> res_embedding_bag = torch.nn.functional.embedding_bag(indices, weights, torch.tensor([0]), padding_idx=0, mode='mean')
>>> res_embedding_bag
tensor([[ 1.0107, -0.5945, -0.2859, -0.3890]])
>>> res_embedding_bag.eq(res_embedding_mean).all()
tensor(True)
```

**Comment by uwaisiqbal** [comment] 2020-12-16 12:15
Hmm, I see. Do you think you could add an additional argument to ignore the zero tensors when taking the mean? I mean it's just a matter of taking the sum and normalising by the number non-zero tensors. I can imagine the averaged vectors being skewed for documents with lots of padding for example.

**Comment by kurtamohler** [comment] 2020-12-16 20:35
@uwaisiqbal, that would certainly be possible, but I have no idea whether we should or shouldn't add that feature. Do you have a use case that would benefit from it?

@mruberry or @ezyang, what are your thoughts on adding an extra argument to choose to completely ignore padded zeros for the reduction in EmbeddingBag?

If we do choose to add this option, should it ignore all zeros (I assume not), or only ignore the zeros that `padding_idx` inserts (I assume so)?

**Comment by mruberry** [comment] 2020-12-16 20:41
Let's not move the goal posts on this issue. @uwaisiqbal, please open a new issue for the new feature.

**Comment by jbschlosser** [comment] 2020-12-23 20:37
I agree with @uwaisiqbal that it would be good for padding elements to be left out of the reduction. In fact, I have a hard time seeing a case where it makes sense to include them. The only case that comes to mind is if the user is utilizing a non-zero padding embedding vector (which I believe would be fairly rare) and, even then, they may still want to exclude padding.

> If we do choose to add this option, should it ignore all zeros (I assume not), or only ignore the zeros that padding_idx inserts (I assume so)?

I would expect it to ignore only the padding elements (i.e. zeros or w/e that padding_idx inserts).

> Let's not move the goal posts on this issue. @uwaisiqbal, please open a new issue for the new feature.

I agree with this sentiment as well regarding the additional option. However, I'll put forth the suggestion that the default behavior should be to _exclude_ padding elements from the reduction, and we can punt on a later option that allows for them to be _included_. I believe this will best match user intuition regarding the definition of "padding" and maximize immediate usefulness.

**Comment by kurtamohler** [comment] 2020-12-29 18:51
After some deliberation with @jbschlosser and @mruberry, we decided to go forward with the idea of ignoring the padded elements in the reduction by default.

The main point that brought us to an agreement is that is that `padding_idx`'s purpose is to allow us to create embeddings where each sample (dim=-1 of the embedding) is a different logical length. For instance, if the embedding represents a list of sentences, and each sentence is a different length, you would pad the ends of sentences so that they can fit into a matrix (which requires all rows to be of equal length). Since the padded indices are not actually part of the sentences, you not want to include them in the reduction.

So I will update my PR to ignore padding. Thanks for initially suggesting this change @uwaisiqbal!

**Comment by kurtamohler** [comment] 2021-01-08 00:13
I've discovered a conceptual problem related to ignoring padded elements in the reduction. What should happen if every element in a reduction is padded? A simple example:

```
indices = torch.tensor([1])
weights = torch.arange(12).resize_(3, 4).float()
res = torch.nn.functional.embedding_bag(indices, weights, torch.tensor([0], padding_idx=1, mode=mode)
```

What should `res` be? Here's what I think should happen:

The logical embedding result in this case would be of size `[0, 4]`, and we want to compute mean/sum/max across dim 0 of that tensor. So it would follow that the behavior should match that of `torch.sum`, `torch.mean`, or `torch.amax`, depending on the reduction mode:

```
>>> torch.Tensor([]).resize_(0, 4).sum(dim=0)
tensor([0., 0., 0., 0.])
>>> torch.Tensor([]).resize_(0, 4).mean(dim=0)
tensor([nan, nan, nan, nan])
>>> torch.Tensor([]).resize_(0, 4).amax(dim=0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: operation does not have an identity
```

In the `mode='max'` case, we would probably want a slightly different error message though. Maybe something like "cannot compute maximum value when embedding outputs are padded".

Is this an acceptable solution? cc @mruberry

**Comment by jbschlosser** [comment] 2021-01-08 19:41
@kurtamohler While your proposed suggestion makes sense, I think the all-padding case can be considered "user error". As a user, I'd prefer the logic error out for all reduction types rather than continue with silently incorrect behavior. This conservative error behavior can be easily changed in the future if a use case surfaces.

I was originally going to suggest defaulting to the current `EmbeddingBag` behavior for an empty input tensor, but I think the two cases are actually conceptually different: user error involving padding vs. an intentionally empty input tensor. Also, as I just found out, the current behavior for `EmbeddingBag` with an empty input tensor is [non-ideal](https://github.com/pytorch/pytorch/issues/50286).

**Comment by vadimkantorov** [comment] 2021-01-08 19:47
> @kurtamohler While your proposed suggestion makes sense, I think the all-padding case can be considered "user error". As a user, I'd prefer the logic error out for all reduction types rather than continue with silently incorrect behavior. This conservative error behavior can be easily changed in the future if a use case surfaces.
> 
> I was originally going to suggest defaulting to the current `EmbeddingBag` behavior for an empty input tensor, but I think the two cases are actually conceptually different: user error involving padding vs. an intentionally empty input tensor. Also, as I just found out, the current behavior for `EmbeddingBag` with an empty input tensor is [non-ideal](https://github.com/pytorch/pytorch/issues/50286).

This can realistically easily happen as a result of text-preprocessing. It would be good if it didn't do anything bad in this case.

**Comment by kurtamohler** [comment] 2021-01-08 20:47
Thanks for the responses! I think I agree with the idea to throw an error instead of attempting to reduce a fully padded tensor.

> It would be good if it didn't do anything bad in this case.

@vadimkantorov can you clarify, are you saying it would be bad to throw an error if the embedding output is fully padded?

**Comment by jbschlosser** [comment] 2021-01-08 20:50
> This can realistically easily happen as a result of text-preprocessing. It would be good if it didn't do anything bad in this case.

Absolutely, and I realized I wasn't being precise with the different possibilities. Consider a batch of N sentences; there's 3 cases I see:
1. Batch of N sentences where all N are empty (zero-length). This is the empty input tensor case.
2. Batch of N sentences where some are empty while the rest are non-empty. This will result in the empty sentences being all padding within the batch.
3. Batch of N sentences where all N are entirely padding. (This would be strange to encounter in practice, since padding is usually applied to reach the max sentence length in the batch. Case 1 is more likely.)

Ideally, I think conceptual no-op behavior would be desired for empty / padding sentences (i.e. those don't affect gradient updates). This should be easy for Case 1 by outputting an empty tensor of the same shape as the input.

But what should the output shape be to achieve no-op behavior for only the empty sentences in Case 2? If the output shape changes based on the existence of padding elements in the input, I think that would be unexpected and strange. I'd argue that an error is better for this case. I think having a consistent output shape is worth requiring users to manually ensure non-empty sentences within their batches.

@vadimkantorov Do you agree with this?

**Comment by kurtamohler** [comment] 2021-01-14 18:31
Actually, I realize now that `embedding_bag` already supports empty bags, and it sets their result to zero for all the reduction modes. Given a 1-D `input`, the `offsets` inputs indices where each bag begins in the `input` array. In the following example, I use an `offsets` array of `[0, 1, 1]`, which indicates that bag 0 should contain `indices[0]` up to and not including `indices[1]`, bag 1 should contain `indices[1]` up to and not including `indices[1]` (in other words, empty), and bag 2 should contain `indices[1]` and everything that comes after it.

```
>>> weights = torch.randn(10, 3)
>>> weights
tensor([[ 0.2868,  0.1833,  1.9236],
        [ 1.1501,  1.1183,  0.2423],
        [-0.6208, -1.4278,  0.5780],
        [-0.3674, -1.0986, -0.0076],
        [-0.2707,  2.1619,  0.8676]])
>>> torch.nn.functional.embedding_bag(weights, torch.tensor([0, 1]), torch.tensor([0, 1, 1]), mode='mean')
tensor([[0.2868, 0.1833, 1.9236],
        [0.0000, 0.0000, 0.0000],
        [1.1501, 1.1183, 0.2423]])
>>> torch.nn.functional.embedding_bag(weights, torch.tensor([0, 1]), torch.tensor([0, 1, 1]), mode='sum')
tensor([[0.2868, 0.1833, 1.9236],
        [0.0000, 0.0000, 0.0000],
        [1.1501, 1.1183, 0.2423]])
>>> torch.nn.functional.embedding_bag(weights, torch.tensor([0, 1]), torch.tensor([0, 1, 1]), mode='max')
tensor([[0.2868, 0.1833, 1.9236],
        [0.0000, 0.0000, 0.0000],
        [1.1501, 1.1183, 0.2423]])
```

So to be consistent with this, if one of the bags in a 2-D `input` is entirely filled with `padding_idx`, the empty bag should be zero.

**Comment by gchanan** [comment] 2021-04-06 23:55
@cpuhrsch points out that there are other cases with similar issues, e.g. CrossEntropyLoss / NLLLoss / MultiLabelSoftMarginLoss / MultiLabelMarginLoss`.

Note `CrossEntropyLoss` ignores the padding_idx (I think, the documentation isn't actually clear for `reduction`.

> ignore_index (int, optional) – Specifies a target value that is ignored and does not contribute to the input gradient. When size_average is True, the loss is averaged over non-ignored targets.

Could be worth looking over the other cases, making sure they make sense together and ensuring `reduction` actually works properly in those cases.

**Comment by jbschlosser** [comment] 2021-04-09 16:30
@gchanan also made a great point to me to ensure that the other `EmbeddingBag` args interact with `padding_idx` in a way that makes sense. Here's a summary of the way I think this should be (args from the recently-improved [docs](https://pytorch.org/docs/master/generated/torch.nn.EmbeddingBag.html)), and AFAICT this PR does all of this correctly:

* `max_norm` - If given, each embedding vector with norm larger than max_norm is renormalized to have norm max_norm
  * This should always apply to the embedding vector at `padding_idx` as well (will be a no-op for the all-zero padding embedding vector case)
* `norm_type` - The p of the p-norm to compute for the max_norm option
  * Affects previous arg; all norm_types should also apply to the embedding vector at `padding_idx`
* `scale_grad_by_freq` - If given, this will scale gradients by the inverse of frequency of the words in the mini-batch
    * Gradients for padding_idx never need to be scaled since they should always be 0
* `mode` - "sum", "mean" or "max". Specifies the way to reduce the bag
  * `padding_idx` needs to be handled for all modes / reduction types
* `sparse` - if `True`, gradient w.r.t. weight matrix will be a sparse tensor
  * Gradients for `padding_idx` should always be 0, even when the matrix is sparse
* `include_last_offset` - if True, offsets has one additional element, where the last element is equivalent to the size of indices. This matches the CSR format
  * Used with 1D input to identify bag boundaries; doesn't interact specially with `padding_idx`
* `per_sample_weights` (`forward()` arg) - a tensor of float / double weights, or None to indicate all weights should be taken to be 1. If specified, per_sample_weights must have exactly the same shape as input and is treated as having the same offsets, if those are not None
    * **When included in the reduction, `padding_idx` items should be scaled by the given weights**

I see use cases for both including the items with `padding_idx` in the reduction as well as excluding them. Between the two cases, only the behavior of `per_sample_weights` should change as specified above.

I originally made an argument that the exclusion case is more common and should be the default, but my overall goal is to minimize surprise, and it's important to be consistent with `Embedding`'s `padding_idx` semantics. During investigation of a recent regression (see https://github.com/pytorch/pytorch/issues/53368), the intended semantics for `Embedding`'s `padding_idx` became clear to me: the purpose of that arg is solely to avoid gradient updates for the embedding vector at the specified `padding_idx`, keeping its value fixed.

With that in mind, which is more surprising?
* Including `padding_idx` items in the reduction by default
  * Matches `Embedding`'s semantics in that the sole purpose is to avoid gradient updates for the embedding vector at `padding_idx`
  * Will skew mean reductions when the `padding_idx` embedding vector is all zeros
  * May surprise those who think of "padding" as more than just  "zero out gradients for this embedding vector to keep it fixed"
* Excluding `padding_idx` items in the reduction by default (currently done in this PR)
  * Will give incorrect results for non-zero `padding_idx` embedding vector in all reduction modes
  * May surprise those who expect identical `padding_idx` semantics to that of `Embedding`

Perhaps it's better to be identical to `Embedding`'s `padding_idx` for consistency (i.e. _include_ `padding_idx` items in the reduction by default)? Regardless of the default, a flag switching between the two behaviors is necessary to support both all-zero and non-zero `padding_idx` embedding vector use cases.

@gchanan @kurtamohler do you have any thoughts here- maybe I was wrong to suggest exclusion by default here given `Embedding`'s `padding_idx` semantics?

**Comment by kurtamohler** [comment] 2021-04-09 21:20
I agree that an option to exclude/include the padded values would be a good idea. As for which default mode would be least surprising, I don't know enough right now to have an informed opinion.

It seems like there are two things to balance here: usefulness and surprise. Ideally, the default behavior would be both more useful and least surprising. But in reality, we might have to sacrifice one in favor of the other. For instance, if we somehow determined that exclusion is more useful 90% of the time but "a little bit more surprising" than inclusion, then we may decide to make exclusion the default despite it being surprising. Or if exclusion is only 10% more useful and "a lot more surprising" than inclusion, then we might decide to make inclusion the default. I don't know how/if we would really quantify these things accurately though. Maybe we should try to poll for a lot of user's opinions?

But I don't really mind either way we choose to go.

**Comment by gchanan** [comment] 2021-04-14 16:36
> Matches Embedding's semantics in that the sole purpose is to avoid gradient updates for the embedding vector at padding_idx

I don't think this really applies -- Embedding doesn't have a reduction argument; if EmbeddingBag didn't exist you'd still have to decide what you wanted to do when you reduce over it.

**Comment by vadimkantorov** [comment] 2021-04-14 16:47
It looks strange that a commit in `pytorch/glow` can close down an issue in `pytorch/pytorch`? Is it expected?

**Comment by vadimkantorov** [comment] 2021-04-14 16:56
Maybe it's a bug with Facebook Github Bot

**Comment by jbschlosser** [comment] 2021-04-14 17:06
The diff that was landed had changes in both `pytorch/pytorch` and `pytorch/glow`, and I guess the bot displayed this as closed by the latter one.

**Comment by jbschlosser** [comment] 2021-04-14 18:39
> > Matches Embedding's semantics in that the sole purpose is to avoid gradient updates for the embedding vector at padding_idx
> 
> I don't think this really applies -- Embedding doesn't have a reduction argument; if EmbeddingBag didn't exist you'd still have to decide what you wanted to do when you reduce over it.

That's true- maybe this indicates that we can go either way reasonably.

That said, it occurred to me that for a newly constructed `EmbeddingBag`, the default for the embedding vector at `padding_idx` is all zeros. Since all-zeros should generally be excluded from the reduction to avoid skew, I am now convinced (again) that the default behavior should match this by excluding by default.

**Comment by malfet** [comment] 2021-04-14 20:39
@vadimkantorov no, it's a github feature: any PR landed to any GH repo with "Fixes https://url/to/gh/issue" keyword, would automatically close issue in referred repo if committer have permission to do so (i.e. I can land a PR to my personal repo and mark it as fixing pytorch issue)

**Comment by jbschlosser** [comment] 2021-04-14 21:01
Closing this issue as complete for now. Discussion for optionally including the `padding_idx` embedding vector within the reduction should continue at #56064

**Closed by jbschlosser** 2021-04-14 21:01 UTC
Labels: enhancement, high priority, module: nn, triaged
