### ISSUE TITLE
Tensor.norm() returns incorrect results with float32 and large CPU tensors

### ISSUE THREAD

**Issue by andrewilyas** [pytorch/pytorch#68326] opened 2021-11-14 22:25 UTC
## 🐛 Bug

When on CPU, the Tensor.norm() function returns incorrect results for very large tensors at 32-bit precision. The output of ``torch.sqrt(x.pow(2).sum()`` is actually correct in this case, and the issue is resolved on GPU and at 64-bit precision.

## To Reproduce

```python

In [1]:  import torch as ch

In [2]: x = ch.randn(100000000) / 1000

In [3]: x.norm()
Out[3]: tensor(9.2732)

In [4]: ch.sqrt(x.pow(2).sum())
Out[4]: tensor(10.0005)

In [5]: (x * x).sum() / (x.norm() * x.norm())
Out[5]: tensor(1.1630)

In [6]: (x * x).sum() / (ch.sqrt(x.pow(2).sum()) * ch.sqrt(x.pow(2).sum()))
Out[6]: tensor(1.)

In [7]: (x.double() * x.double()).sum()
Out[7]: tensor(100.0094, dtype=torch.float64)

In [8]: x.double().norm()
Out[8]: tensor(10.0005, dtype=torch.float64)

In [9]:

```

## Expected behavior

Output lines [3 and [4] should match above, and output line [6] should be equal to 1. The fact that [8] agrees with [7] and [4] makes me think that ``Tensor.norm()`` specifically is the problem.

## Environment

```
Collecting environment information...
PyTorch version: 1.9.1+cu111
Is debug build: False
CUDA used to build PyTorch: 11.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.5 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.27

Python version: 3.8.0 (default, Nov  6 2019, 21:49:08)  [GCC 7.3.0] (64-bit runtime)
Python platform: Linux-4.15.0-153-generic-x86_64-with-glibc2.10
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration:
GPU 0: GeForce RTX 2080 Ti
GPU 1: GeForce RTX 2080 Ti
GPU 2: GeForce RTX 2080 Ti
GPU 3: GeForce RTX 2080 Ti
GPU 4: GeForce RTX 2080 Ti
GPU 5: GeForce RTX 2080 Ti
GPU 6: GeForce RTX 2080 Ti
GPU 7: GeForce RTX 2080 Ti

Nvidia driver version: 460.91.03
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A

Versions of relevant libraries:
[pip3] fast-pytorch-kmeans==0.1.6
[pip3] msgpack-numpy==0.4.7.1
[pip3] mypy==0.812
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.20.2
[pip3] torch==1.9.1+cu111
[pip3] torchmetrics==0.5.1
[pip3] torchvision==0.10.1+rocm4.2
[conda] fast-pytorch-kmeans       0.1.6                    pypi_0    pypi
[conda] numpy                     1.20.2                   pypi_0    pypi
[conda] torch                     1.9.0a0+git2130f4c          pypi_0    pypi
[conda] torchmetrics              0.5.1                    pypi_0    pypi
[conda] torchvision               0.9.1                    pypi_0    pypi
```

cc @VitalyFedyunin

**Comment by ngimel** [comment] 2021-11-15 06:34
Dupe of #65815

**Closed** 2022-05-23 16:22 UTC
Labels: module: cpu, triaged, module: correctness (silent), module: norms and normalization
