### ISSUE TITLE
Export to ONNX failure with mismatched devices

### ISSUE THREAD

**Issue by Yebi1837** [pytorch/pytorch#79951] opened 2022-06-21 18:09 UTC
### 🐛 Describe the bug

hi PyTorch, I am trying to do ONNX conversion for a module and encountered following error:

```python
from torch.onnx.symbolic_helper import _constant_folding_opset_versions
        if do_constant_folding and _export_onnx_opset_version in _constant_folding_opset_versions:
            params_dict = torch._C._jit_pass_onnx_constant_fold(graph, params_dict,
>                                                               _export_onnx_opset_version)
E           RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

The code to reproduce this is:
```python
from typing import Dict
import io
import torch
import torch.nn as nn

class SampleModule(nn.Module):
    def __init__(self):
        super(SampleModule, self).__init__()
        self.a = 64

    def forward(self, input_dict: Dict[str, torch.Tensor]) -> torch.Tensor:
        data = input_dict["input"]
        x = torch.arange(self.a, device=data.device)
        y = x[None, None, :, None]
        z = torch.ones_like(data[:, :1], device=data.device) * y
        return z

    def gen_inputs(self):
        return {"input":torch.rand((1,2,64,64), device=torch.device('cuda:0'))}

def test_reproducer():
    model = SampleModule()
    model.cuda()
    model.eval()

    inputs = model.gen_inputs()
    input_names = ["input"]
    output_names = ["output"]

    onnx_bytes = io.BytesIO()
    #dynamic_axes = {"input": {0: "batch_size"}}
    empty_dynamic_axes = {}

    print("before onnx export")
    torch.onnx.export(
        model=model,
        args=inputs,
        f=onnx_bytes,
        verbose=False,
        input_names=input_names,
        output_names=output_names,
        dynamic_axes=empty_dynamic_axes,
        opset_version=12,
        export_params=True,
        operator_export_type=torch.onnx.OperatorExportTypes.ONNX,
    )
    print("after onnx export")
```

### Versions

Collecting environment information...
PyTorch version: 1.4.0
Is debug build: False
CUDA used to build PyTorch: 10.1
ROCM used to build PyTorch: N/A

OS: Ubuntu 18.04.6 LTS (x86_64)
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.15

Python version: 2.7.17 (default, Mar 18 2022, 13:21:42)  [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-5.4.0-1078-gcp-x86_64-with-Ubuntu-18.04-bionic
Is CUDA available: True
CUDA runtime version: Could not collect
GPU models and configuration: 
GPU 0: Tesla T4
GPU 1: Tesla T4

Nvidia driver version: 470.82.01
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: Could not collect

Versions of relevant libraries:
[pip] mypy-extensions==0.4.3
[pip] numpy==1.16.6
[pip] torch==1.4.0
[pip] torchvision==0.5.0
[conda] Could not collect

**Comment by AllenTiTaiWang** [comment] 2022-06-27 22:46
Hi @Yebi1837,

I can't reproduce your error. Could you try again with the latest version of Pytorch and ONNX (please provide onnx version as well)?

**Comment by justinchuby** [comment] 2022-06-28 19:18
@Yebi1837 You may need to find a way to use pytorch nightly. All fixes will only be available in the latest versions. According to Ti-Tai's experiment we think the error has been fixed in newer versions of PyTorch.

**Comment by Yebi1837** [comment] 2022-06-28 21:19
hi @justinchuby and @AllenTiTaiWang 
Unfortunately this is not a personal project but a company project instead, I am not able to move to a newer version because the whole organization depends on this. 
The source code I am using were picked up from v1.11 release here: https://github.com/pytorch/pytorch/tree/v1.11.0

**Comment by justinchuby** [comment] 2022-06-28 21:51
Would it be possible for you to move all tensors to cpu before exporting?

**Comment by Yebi1837** [comment] 2022-06-29 16:55
hi @justinchuby 
I tried this by doing something like:
`model = model.cpu(), inputs = inputs.cpu()`
but the onnx conversion still runs into the same problem.

Do you know which commit fixed this problem? maybe we can patch our pytorch source code?

**Comment by Yebi1837** [comment] 2022-06-29 17:08
this change may work for this toy model, but the thing is there are many models on our plates and the GPUs are available for developers, so such hardcoding of devices are all over the place. It would be hard to modify models one by one in different places. 
Are you able to reproduce this issue with[ v1.11 ](https://github.com/pytorch/pytorch/tree/v1.11.0)release? 
The ONNX conversion used to be fine with v1.09, but only broken in v1.11.

**Comment by justinchuby** [comment] 2022-06-29 17:12
I would try a few things: (1) move all tensors to gpu, because it only requires "all tensors to be on the same device," or (2) if possible, save the trained model and reload it with pytorch nightly. See if you can export it with the newer version.

To skip this code block, I would also try setting `do_constant_folding` to false.

**Comment by BowenBao** [comment] 2022-10-21 01:05
Closing since no activity.

**Closed by BowenBao** 2022-10-21 01:05 UTC
Labels: module: onnx, triaged, onnx-needs-info
