### ISSUE TITLE
'list' object has no attribute 'size'

### ISSUE THREAD

**Issue by kmj970311** [pytorch/pytorch#35673] opened 2020-03-30 14:02 UTC
```
from os.path import basename, join

import torch.optim as optim
from torch.utils.data import DataLoader

import torchvision.transforms as T

from cellcount.utils import (ChunkSampler, ImageWithMask, train,
                             get_val_example, save_epoch_image)
from cellcount.models import FPN
from cellcount.losses import fpn_loss,gpu_dtype


BBBC = 'synthetic-cell-images-and-masks-bbbc005-v1/'

transform = T.Compose([T.Scale((256)), T.ToTensor()])

NUM_TRAIN = 1000
NUM_VAL = 200

train_data = ImageWithMask(join(BBBC, 'BBBC005_v1_ground_truth/'),
                           transform=transform)
train_data.imgs = [(join(BBBC, 'BBBC005_v1_images/BBBC005_v1_images/%s') % basename(i), i)
                   for i, _ in train_data.imgs]

loader_train = DataLoader(train_data, batch_size=2,
                          sampler=ChunkSampler(NUM_TRAIN, 0))
loader_val = DataLoader(train_data, batch_size=2,
                        sampler=ChunkSampler(NUM_VAL, NUM_TRAIN))


x_var, y_var = get_val_example(loader_val,gpu_dtype)
_, _, h, w = x_var.size()

fpn = FPN(h, w).type(gpu_dtype)

lr = 5e-4
epochs = 1000
for i in range(epochs):
    print('epoch: %s' % i)
    if i > 0 and (i % 20 == 0):
        lr *= .95
    optimizer = optim.Adam(fpn.parameters(), lr=lr, weight_decay=0.)
    train(loader_train, fpn, fpn_loss, optimizer,gpu_dtype)
    if (i % 20 == 0):
        save_epoch_image(x_var, y_var, fpn, i)`



Error

AttributeError                            Traceback (most recent call last)
<ipython-input-1-b73e6adf9761> in <module>
     44     train(loader_train, fpn, fpn_loss, optimizer,gpu_dtype)
     45     if (i % 20 == 0):
---> 46         save_epoch_image(x_var, y_var, fpn, i)

~/MJ/cellcount/utils.py in save_epoch_image(x_var, y_var, model, epoch)
     94     show(make_grid(x_var), ax1)
     95     show(make_grid(y_var), ax2)
---> 96     show(make_grid(model(x_var)[-1], padding=5), ax3)
     97     fig.savefig('./test_images/FPN_epoch_%s.png' % epoch, dpi=300)
     98 

~/MJ/cellcount/utils.py in make_grid(imgs, padding)
     79     ax.imshow(np.transpose(img, (1, 2, 0)), interpolation='nearest')
     80 def make_grid(imgs, padding=20):
---> 81     N, C, H, W =imgs.size()
     82     M = np.zeros((C, H, W * N + (N - 1) * padding))
     83     for i in range(N):

AttributeError: 'list' object has no attribute 'size'
```

Help me please ㅠㅠ

**Comment by ailzhang** [comment] 2020-03-30 22:33
Looks like your issue is: 
- model forward returns a list, but `cellcount` is trying to call `size()` on list. 
It can be fixed by either fixing `make_grid` to handle list properly, or figure out whether returning list from model is expected behavior. 
Since this is not really a bug report, I'm going to close it for now. feel free to ask questions in our forum, or reopen this thread if you believe it's indeed a bug on pytorch. Thanks!

**Closed by ailzhang** 2020-03-30 22:33 UTC
