### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable (Occurred when translating col2im). Can't translate torch.nn.functional.fold in opset_version 18.

### ISSUE THREAD

**Issue by Rody-NKCS** [pytorch/pytorch#105134] opened 2023-07-13 08:08 UTC
### 🐛 Describe the bug

```python
import torch
import torch.nn as nn
import torch.nn.functional as F

x=torch.randn(176,64,56,56)
y=torch.randn(176,128,28,28)

input_names=['input']
output_names=['output']

class embedding_concat(nn.Module):
    def __init__(self):
        super(embedding_concat,self).__init__()
        
    def forward(self,x):
        
        y=torch.randn(176,128,28,28)
        B, C1, H1, W1 = x.size()
        _, C2, H2, W2 = y.size()
        s = int(H1 / H2)
        x = F.unfold(x, kernel_size=s, dilation=1, stride=s)
        x = x.view(B, C1, -1, H2, W2)
        z = torch.zeros(B, C1 + C2, x.size(2), H2, W2)
        for i in range(x.size(2)):
            z[:, :, i, :, :] = torch.cat((x[:, :, i, :, :], y), 1)
        z = z.view(B, -1, H2 * W2)
        print(z.shape)
        fold=nn.Fold(output_size=(H1,W1),kernel_size=s,stride=s)
        z = fold(z)
        
        return z



model=embedding_concat()
torch.onnx.export(model,
                  x,
                  "embedding_concat.onnx",
                  input_names=input_names,
                  output_names=output_names,
                  opset_version=18, 
                  do_constant_folding=False, # 是否压缩常量
                  #export_params=False,
                  dynamic_axes={"input":{1: "channel",2:"h",3:"w"},}
                  )
```

### Versions

```
Collecting environment information...
PyTorch version: 2.0.0+cu117
Is debug build: False
CUDA used to build PyTorch: 11.7
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 家庭中文版
GCC version: Could not collect
Clang version: Could not collect
CMake version: Could not collect
Libc version: N/A

Python version: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.22621-SP0
Is CUDA available: True
CUDA runtime version: 11.7.99
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050 Laptop GPU
Nvidia driver version: 528.79
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=2500
DeviceID=CPU0
Family=205
L2CacheSize=4096
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=2500
Name=12th Gen Intel(R) Core(TM) i5-12500H
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] flake8==6.0.0
[pip3] mypy-extensions==1.0.0
[pip3] numpy==1.24.4
[pip3] numpydoc==1.5.0
[pip3] torch==2.0.0+cu117
[pip3] torchaudio==2.0.1+cu117
[pip3] torchvision==0.15.1+cu117
[conda] numpy                     1.24.4                   pypi_0    pypi
[conda] numpydoc                  1.5.0                    pypi_0    pypi
[conda] torch                     2.0.0+cu117              pypi_0    pypi
[conda] torchaudio                2.0.1+cu117              pypi_0    pypi
[conda] torchvision               0.15.1+cu117             pypi_0    pypi
```

**Comment by WildChlamydia** [comment] 2023-07-13 20:07
Seems the same issue with unfold:
https://github.com/huggingface/pytorch-image-models/issues/1872

```python
Traceback (most recent call last):
  File "onnx_export.py", line 86, in <module>
    main()
  File "onnx_export.py", line 74, in main
    onnx_export(
  File "pytorch-image-models/timm/utils/onnx.py", line 71, in onnx_export
    torch_out = torch.onnx._export(
  File ".../lib/python3.8/site-packages/torch/onnx/_deprecation.py", line 30, in wrapper
    return function(*args, **kwargs)
  File ".../lib/python3.8/site-packages/torch/onnx/__init__.py", line 114, in _export
    return utils._export(*args, **kwargs)
  File ".../lib/python3.8/site-packages/torch/onnx/utils.py", line 1577, in _export
    graph, params_dict, torch_out = _model_to_graph(
  File ".../lib/python3.8/site-packages/torch/onnx/utils.py", line 1134, in _model_to_graph
    graph = _optimize_graph(
  File ".../lib/python3.8/site-packages/torch/onnx/utils.py", line 672, in _optimize_graph
    graph = _C._jit_pass_onnx(graph, operator_export_type)
  File ".../lib/python3.8/site-packages/torch/onnx/utils.py", line 1919, in _run_symbolic_function
    return symbolic_fn(graph_context, *inputs, **attrs)
  File ".../lib/python3.8/site-packages/torch/onnx/symbolic_helper.py", line 306, in wrapper
    return fn(g, *args, **kwargs)
  File ".../lib/python3.8/site-packages/torch/onnx/symbolic_opset18.py", line 52, in col2im
    num_dimensional_axis = symbolic_helper._get_tensor_sizes(output_size)[0]
TypeError: 'NoneType' object is not subscriptable
(Occurred when translating col2im).
```

**Comment by Rody-NKCS** [comment] 2023-07-14 01:39
Thank you. I completely know what happen to this bug. 
torch.nn.functional.fold will use col2im,and in opset_version  18, col2im do not support dynamic input.
Specially, for my code 
```
B, C1, H1, W1 = x.size()
fold=F.Fold(output_size=(H1,W1),kernel_size=s,stride=s)
z = fold(z)
```
I use dynamic input for F.fold, but if i write my code as follow:
```
fold=F.Fold(output_size=(64,64),kernel_size=s,stride=s)
z = fold(z)

```
It run and survive. I hope this helps.

**Comment by WildChlamydia** [comment] 2023-07-14 09:36
I do not use dynamic input but still the same

**Comment by WildChlamydia** [comment] 2023-07-14 15:07
@Rody-NKCS 
Seems like you're almost right, but the problem is not with the dynamic input, it's related to the data type.
I used the int conversion:
fold=F.Fold(output_size=(int(H1), int(W1)),kernel_size=s,stride=s)
And it worked.

**Comment by Rody-NKCS** [comment] 2023-07-17 03:54
Oh, yes, thank you very much.

**Comment by MasterHM-ml** [comment] 2023-08-10 07:06
> @Rody-NKCS Seems like you're almost right, but the problem is not with the dynamic input, it's related to the data type. I used the int conversion: `fold=F.Fold(output_size=(int(H1), int(W1)),kernel_size=s,stride=s)` And it worked.

How I can apply this fix in the conversion of VOLO model into `ONNX` format?
That would be a massive help. Thank you in advance.

Details:
I am converting [MiVOLO](https://github.com/WildChlamydia/MiVOLO) pytorch-timm-based model into ONNX format which will be further converted into OpenVINO IR. I am stuck at first place. I have added more details here in this [issue](https://github.com/pytorch/pytorch/issues/106939).

**Comment by Rody-NKCS** [comment] 2023-08-10 09:02
Your problem also seems to be caused by F.fold. So, in order to solve this problem, you need to find the F.fold function used in the neural network and add int in front of H,W as shown above. But I looked at the source code of MiVOLO and there is no F.fold in it. but there is another possibility, MiVOLO uses YOLO. imported by the ultralytics library, so there is a possibility that F.fold is used in yolo. @https://twitter.com/MHamzaHM_

**Comment by MasterHM-ml** [comment] 2023-08-10 09:08
@Rody-NKCS thanks for reply

Yolo is used in another pipeline, and my model is independent of that. However my model inherits VOLO from timm. So the issue is in VOLO as mentioned [here](https://github.com/huggingface/pytorch-image-models/issues/1872)


Can you guess how to fix it in VOLO model?

**Comment by justinchuby** [comment] 2024-04-03 16:32
As we are moving away from `torch.onnx.export` and into `torch.onnx.dynamo_export`, features and fixes will be developed for the new api. I am going to close this issue as unplanned since we do not plan to create significant improvements to the old api.

**Closed by justinchuby** 2024-04-03 16:32 UTC
Labels: module: onnx, triaged

**Comment by korotaS** [comment] 2024-04-27 14:03
Although @WildChlamydia's and @Rody-NKCS's solution is a workaround for constant input shapes, it doesn't work in general because if you export with torch.onnx.export model with `int(h)` and `int(w)` this variables become constants in ONNX and you cannot run model with different model shapes. 
I was trying the same `F.fold` export in a CNN model (with different input shapes) and it still doesn't work with different input shapes.
