### ISSUE TITLE
Add deterministic option to cuDNN backend

### ISSUE THREAD

**Issue by daemon** [pytorch/pytorch#2831] opened 2017-09-22 14:07 UTC
Some of of cuDNN's algorithms are non-deterministic, even with the seed set to X, for example

```C
typedef enum
{
    CUDNN_CONVOLUTION_BWD_FILTER_ALGO_0         = 0,  // non-deterministic
    CUDNN_CONVOLUTION_BWD_FILTER_ALGO_3         = 3,  // non-deterministic, algo0 with workspace
```
```C
typedef enum
{
    CUDNN_CONVOLUTION_BWD_DATA_ALGO_0                 = 0, // non-deterministic
```
(This list is probably non-exhaustive)

PyTorch currently provides no way for the user to select which specific algorithms to use in cuDNN. However, this is fine, since PyTorch was designed to be more high-level and abstract than some of the other frameworks. 

Perhaps instead of exposing the entire cuDNN algorithm choices, a boolean variable specifying non-determinism vs determinism should be added? This would be along the lines of the current `torch.backends.cudnn.enabled` option.

Currently, users have to resort to CPU or disabling cuDNN for reproducibility. Some optimizers do work deterministically (at least for us) on the GPU (e.g. SGD, Adam), but Adadelta and RMSprop do not.

**Comment by ezyang** [comment] 2017-09-22 14:21
CC @zdevito

**Comment by soumith** [comment] 2017-09-27 03:59
duplicate of https://github.com/pytorch/pytorch/issues/114
Closing this in favor of that, but copying the comment over for context.

**Closed by soumith** 2017-09-27 03:59 UTC
