### ISSUE TITLE
GPU torch.multinomial produces an out-of-bounds index

### ISSUE THREAD

**Issue by ankitkv** [pytorch/pytorch#871] opened 2017-02-27 22:27 UTC
`torch.multinomial` on the GPU can produce indices that are out of bounds.

Consider the following code:

```
from __future__ import print_function
import torch

i = 0
while True:
    logdist = torch.zeros(6, 6).cuda()  # no problem without .cuda()
    # the following is not logically correct, but is the fastest way I've found to reproduce the bug
    logdist.log_normal_(mean=0.0, std=2.5)
    prob = torch.exp(logdist)
    sampled = torch.multinomial(prob, 1)  # multinomial is supposed to reweight to get probabilities
    if ((sampled > 5).sum()):
        print('\niter', i)
        print('\nprob:', prob)
        print('sampled:', sampled)
        break
    if i % 5000 == 0:
        print('iter', i)
    i += 1
```

Here's output from an example run:

```
iter 0
iter 5000

iter 6491

prob: 
 3.0595e+38  1.2861e+00  5.2613e+37  1.3855e+00  2.9041e+00  1.2441e+01
 1.0531e+01  1.0103e+00  2.0693e+00  1.8121e+00  1.6328e+00  6.0454e+10
 1.5679e+03  1.5869e+00  1.5553e+03  5.1932e+03  5.0801e+01  1.3416e+00
 2.2532e+00  1.5512e+00  3.1946e+01  1.5208e+00  8.8690e+00  1.5255e+00
 1.6197e+02  1.0395e+00  1.1355e+38  3.9969e+00  8.2150e+00  1.5104e+05
 1.1240e+00  1.1315e+00  7.9896e+00  6.8996e+00  2.1447e+00  1.3858e+00
[torch.cuda.FloatTensor of size 6x6 (GPU 0)]

sampled: 
 9.0078e+18
 5.0000e+00
 3.0000e+00
 3.0000e+00
 2.0000e+00
 1.0000e+00
[torch.cuda.LongTensor of size 6x1 (GPU 0)]
```

Here, the sampled indices should be between 0 to 5, but one of the values is  `9.0078e+18`.

The iteration at which this happens is random.

The following code uses probabilities closer to actual probabilities

```
from __future__ import print_function

import torch
from torch.autograd import Variable
import torch.nn.functional as F

i = 0
while True:
    data = torch.zeros(6, 6).cuda()  # no problem without .cuda()
    data.normal_(mean=0.0, std=2.5)
    logdist = F.log_softmax(Variable(data)).data
    prob = torch.exp(logdist)  # prob.sum(1) are 1s.
    sampled = torch.multinomial(prob, 1)
    if ((sampled > 5).sum()):
        print('\niter', i)
        print('\nprob:', prob)
        print('sampled:', sampled)
        break
    if i % 10000 == 0:
        print('iter', i)
    i += 1
```

but it has the same problem (the problem occurs much later on average though). Example output snippet:

```
...
iter 27310000
iter 27320000
iter 27330000
iter 27340000

iter 27346838

prob: 
 0.0017  0.8274  0.1657  0.0004  0.0017  0.0031
 0.0123  0.0157  0.0001  0.0020  0.0015  0.9683
 0.0067  0.1369  0.8092  0.0422  0.0030  0.0021
 0.1306  0.0887  0.7521  0.0024  0.0005  0.0258
 0.0425  0.5981  0.0140  0.0565  0.1005  0.1885
 0.0006  0.0017  0.9819  0.0114  0.0038  0.0007
[torch.cuda.FloatTensor of size 6x6 (GPU 0)]

sampled: 
 1.0000e+00
 4.1752e+18
 1.0000e+00
 2.0000e+00
 1.0000e+00
 2.0000e+00
[torch.cuda.LongTensor of size 6x1 (GPU 0)]
```

**Comment by killeent** [comment] 2017-02-27 22:55
@ankitkv There are known problems with multinomial. See https://github.com/torch/cutorch/issues/636, https://github.com/torch/cutorch/issues/700 etc. Your code illustrates how this may occur (albeit very infrequently).

cc @pavanky

**Comment by ankitkv** [comment] 2017-02-27 23:03
I guess for now a good workaround is to use
```
_, sample = torch.max(log_dist - torch.log(-torch.log(torch.rand(*log_dist.size()).cuda())), 1)
```
where `log_dist` are batchwise log probabilities (e.g. output of `F.log_softmax`).

**Comment by pavanky** [comment] 2017-02-27 23:22
@killeent I am not too familiar with why it is breaking :) I just noticed that the tests for MultiNomial were failing frequently and sent in a fix that decreased the frequency. But it looks like there are other issues with it.

**Comment by killeent** [comment] 2017-02-28 01:27
Sure @pavanky - I just thought the fix you added (iirc by making sure the values weren't out of bounds) might have been related to this problem initially. @soumith I'll try and diagnose what the problem is on this one

**Comment by killeent** [comment] 2017-02-28 21:14
@ankitkv See my associated PR that fixes the first issue. I have not been able to repro the second issue (ran 20M iterations). Though I have a suspicion of what the problem is.

**Comment by ankitkv** [comment] 2017-02-28 23:02
@killeent I was able to reproduce the second issue a bunch of times, and I tried dumping the probability matrix whenever that happens. unfortunately, just loading it and calling `multinomial` on it doesn't seem to reproduce it immediately. based on my outputs in the bug report, this code usually runs into the problem at some point (longest I've seen is 30M iters):

```
from __future__ import print_function

import torch

prob = torch.cuda.FloatTensor(
    [[0.0017,  0.8274,  0.1657,  0.0004,  0.0017,  0.0031],
     [0.0123,  0.0157,  0.0001,  0.0020,  0.0015,  0.9683],
     [0.0067,  0.1369,  0.8092,  0.0422,  0.0030,  0.0021],
     [0.1306,  0.0887,  0.7521,  0.0024,  0.0005,  0.0258],
     [0.0425,  0.5981,  0.0140,  0.0565,  0.1005,  0.1885],
     [0.0006,  0.0017,  0.9819,  0.0114,  0.0038,  0.0007]])

i = 0
while True:
    nprob = prob + torch.randn(prob.size()).cuda()*1e-3
    sampled = torch.multinomial(nprob, 1)
    if ((sampled > 5).sum()):
        print('\niter', i)
        print('\nprob:', nprob)
        print('sampled:', sampled)
        break
    if i % 10000 == 0:
        print('iter', i)
    i += 1
```

**Comment by killeent** [comment] 2017-02-28 23:25
I have ran for a pretty long time and still see no errors. @ankitkv see my PR https://github.com/torch/cutorch/issues/714. If you want, try cloning CuTorch and patching in that PR. Then you can copy over the THC directory to your PyTorch repo:

```
cp -r <path/to/cutorch/>lib/THC <path/to/pytorch>/torch/lib/THC
```

and rebuild PyTorch. If you can repro the issue with that patch in place that would be tremendously useful, or if it fixes your error that is useful as well.

**Comment by ankitkv** [comment] 2017-03-01 01:09
@killeent I get:
```
iter 0
/home/ankit/devel/pytorch/torch/lib/THC/THCTensorRandom.cuh:135: void sampleMultinomialOnce(long *, long, int, T *, T *) [with T = float, AccT = float]: block: [2,0,0], thread: [0,0,0] Assertion `!isinf(sum)` failed.
THCudaCheck FAIL file=/home/ankit/devel/pytorch/torch/lib/THC/generated/../THCTensorMathCompare.cuh line=84 error=59 : device-side assert triggered
Traceback (most recent call last):
  File "test.py", line 11, in <module>
    if ((sampled > 5).sum()):
  File "/usr/local/lib/python2.7/dist-packages/torch/tensor.py", line 398, in __gt__
    return self.gt(other)
RuntimeError: cuda runtime error (59) : device-side assert triggered at /home/ankit/devel/pytorch/torch/lib/THC/generated/../THCTensorMathCompare.cuh:84
```
on running the first test code from the bug report.

**Comment by soumith** [comment] 2017-03-01 01:37
the first test code has sums that go to infinity, and hence this device side assert. this is expected. https://github.com/pytorch/pytorch/blob/master/torch/lib/THC/THCTensorRandom.cuh#L134
Instead of silently doing something wrong, it explicitly errors out.

**Comment by soumith** [comment] 2017-03-01 01:42
I'm running the 2nd test code and 3rd test code overnight. Will report back any failures.

**Comment by ankitkv** [comment] 2017-03-01 02:04
I ran it for a while, didn't see any problems. I guess if @soumith doesn't run into a failure, things are good.

**Comment by soumith** [comment] 2017-03-01 12:02
@killeent @ankitkv It did fail later in the night. So some work to do. I'll compile pytorch with Trevor's open PR and see if that fixes things:

script 3
```
iter 12765047

prob:
-0.0016  0.8267  0.1659  0.0018  0.0038  0.0020
 0.0124  0.0171  0.0008  0.0031  0.0006  0.9670
 0.0066  0.1375  0.8100  0.0417  0.0018  0.0021
 0.1305  0.0887  0.7545  0.0039 -0.0003  0.0249
 0.0437  0.5982  0.0130  0.0565  0.1013  0.1882
 0.0013  0.0021  0.9804  0.0143  0.0029  0.0003
[torch.cuda.FloatTensor of size 6x6 (GPU 0)]

sampled:
 1.0000e+00
 5.0000e+00
 4.2805e+18
 2.0000e+00
 4.0000e+00
 2.0000e+00
[torch.cuda.LongTensor of size 6x1 (GPU 0)]
```

script 2
```
iter 59848171

prob:
 0.0165  0.0230  0.8879  0.0002  0.0002  0.0723
 0.0013  0.2584  0.0149  0.6633  0.0609  0.0012
 0.7082  0.1997  0.0446  0.0071  0.0002  0.0402
 0.0088  0.1094  0.0770  0.0418  0.0002  0.7628
 0.0021  0.9485  0.0098  0.0276  0.0009  0.0111
 0.8859  0.1016  0.0060  0.0021  0.0039  0.0003
[torch.cuda.FloatTensor of size 6x6 (GPU 0)]

sampled:
 2.0000e+00
 4.0000e+00
 0.0000e+00
 5.0000e+00
 4.3265e+18
 0.0000e+00
[torch.cuda.LongTensor of size 6x1 (GPU 0)]
```

**Comment by soumith** [comment] 2017-03-01 17:22
Ok Trevor's latest PR fixes it. I'll merge it into pytorch now.

**Comment by soumith** [comment] 2017-03-01 17:30
fixed in master now via: https://github.com/pytorch/pytorch/commit/dfca8dfdc5988813ed5673589ffa4fdd1c4f3d2d

**Closed by soumith** 2017-03-01 17:30 UTC
Labels: bug, high priority

**Comment by neuralix** [comment] 2017-03-16 06:01
could you check whether none-image file is in your dataset directory.
in my case, the error was exactly same and the cause was that.
additionally, in fb.resnet.torch, this is exactly same.
