### ISSUE TITLE
torch.bitwise_{left,right}_shift should not support non-integral types

### ISSUE THREAD

**Issue by zasdfgbnm** [pytorch/pytorch#77119] opened 2022-05-10 00:27 UTC
### 🐛 Describe the bug

```python
>>> t = torch.ones(5)
>>> torch.bitwise_left_shift(t, t)
tensor([2., 2., 2., 2., 2.])
>>> torch.bitwise_right_shift(t, t)
tensor([0.5000, 0.5000, 0.5000, 0.5000, 0.5000])
```
I don't think this makes sense. The computation performed is not a bitwise shift. And all other bitwise ops do not support non-integral types.

### Versions

master

**Comment by zasdfgbnm** [comment] 2022-05-10 00:29
I found this issue while working on adding bitwise ops to the nvFuser frontend. And I don't think we should support floating types. cc: @mruberry @ngimel

**Comment by ngimel** [comment] 2022-05-10 00:38
Duplicate of #74358?

**Comment by zasdfgbnm** [comment] 2022-05-10 00:39
Ah, yes

**Comment by ngimel** [comment] 2022-05-10 00:40
But yes, we'll accept a PR fixing this :-)

**Closed** 2022-05-10 00:39 UTC
