### ISSUE TITLE
Mixed numpy-pytorch binary operators produce unexpected results

### ISSUE THREAD

**Issue by stepelu** [pytorch/pytorch#1819] opened 2017-06-16 08:04 UTC
Test case (the order is important):

```
print(type(numpy.exp(1) + Variable(torch.zeros(2, 5))))
# <class 'numpy.ndarray'> (of really strange shape)
```

I understand why this is happening but I'd prefer an error to be thrown here if possible when the "expected" behaviour cannot be achieved.

**Comment by fmassa** [comment] 2017-06-16 09:31
This is a duplicate of https://github.com/pytorch/pytorch/issues/1294

**Comment by soumith** [comment] 2017-06-16 10:48
closing because duplicate.

**Closed by soumith** 2017-06-16 10:48 UTC
