### ISSUE TITLE
UserWarning: FALLBACK path has been taken inside: torch::jit::fuser::cuda::runCudaFusionGroup

### ISSUE THREAD

**Issue by HolyWu** [pytorch/pytorch#88050] opened 2022-10-30 13:37 UTC
### 🐛 Describe the bug

[code](https://gist.github.com/HolyWu/dda18871c32bd1c6e5a0b7bf30cc2671)

```
C:\Python310\lib\site-packages\torch\nn\modules\module.py:1423: UserWarning: FALLBACK path has been taken inside: torch::jit::fuser::cuda::runCudaFusionGroup. This is an indication that codegen Failed for some reason.
To debug try disable codegen fallback path via setting the env variable `export PYTORCH_NVFUSER_DISABLE=fallback`
 (Triggered internally at ..\torch\csrc\jit\codegen\cuda\manager.cpp:336.)
  return forward_call(*input, **kwargs)
```

After setting `PYTORCH_NVFUSER_DISABLE=fallback`, I get the following:
```
Traceback (most recent call last):
  File "C:\Users\Holy\Downloads\IFNet.py", line 132, in <module>
    net(x, timestep)
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 777, in forward
    return compiled_f(
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 733, in returned_function
    out = cached_fn(flat_args)
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 299, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args, disable_amp=disable_amp)
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 255, in call_func_with_args
    out = normalize_as_list(f(args))
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 230, in g
    return f(*args)
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: stride == cur_contig_stride || size == 1 || (still_rightmost && stride == 1) || (!still_rightmost && stride % word_size == 0) INTERNAL ASSERT FAILED at "..\\torch\\csrc\\jit\\codegen\\cuda\\executor_utils.cpp":634, please report a bug to PyTorch. Vectorization of T0_g[ iS63{( ceilDiv(( ceilDiv(( ceilDiv(( 1 * ( T0.size[1] * ( T0.size[2] * T0.size[3] ) ) ), 4) ), 1) ), 128) )}, iS62{1}, iS60{4}, iS64{128} ] with word size 4 not possible due to invalid stride. Domain: iS60{4}, stride: 5
```

If I remove `memory_format=torch.channels_last` from the supplied code, I get the following instead:
```
Traceback (most recent call last):
  File "C:\Users\Holy\Downloads\IFNet.py", line 132, in <module>
    net(x, timestep)
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 777, in forward
    return compiled_f(
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 733, in returned_function
    out = cached_fn(flat_args)
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 299, in new_fn
    fw_outs = call_func_with_args(compiled_fw, args, disable_amp=disable_amp)
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 255, in call_func_with_args
    out = normalize_as_list(f(args))
  File "C:\Python310\lib\site-packages\functorch\_src\aot_autograd.py", line 230, in g
    return f(*args)
  File "C:\Python310\lib\site-packages\torch\nn\modules\module.py", line 1423, in _call_impl
    return forward_call(*input, **kwargs)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
RuntimeError: entry_it != disjointSetMap().end() INTERNAL ASSERT FAILED at "..\\torch/csrc/jit/codegen/cuda/disjoint_set.h":263, please report a bug to PyTorch. Strict mapping failed on element: T0_g[ bS0{1}, iS1{i2}, iS2{i3}, iS3{i4} ] either an error occured, or non strict mapping should have been used.
```

### Versions

Collecting environment information...
PyTorch version: 1.14.0.dev20221030+cu116
Is debug build: False
CUDA used to build PyTorch: 11.6
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 10 工作站專業版
GCC version: Could not collect
Clang version: 15.0.2
CMake version: version 3.24.2
Libc version: N/A

Python version: 3.10.8 (tags/v3.10.8:aaaf517, Oct 11 2022, 16:50:30) [MSC v.1933 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-10-10.0.19044-SP0
Is CUDA available: True
CUDA runtime version: 11.6.124
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 3050
Nvidia driver version: 526.47
cuDNN version: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\cudnn_ops_train64_8.dll
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

Versions of relevant libraries:
[pip3] mypy-extensions==0.4.3
[pip3] numpy==1.23.4
[pip3] torch==1.14.0.dev20221030+cu116
[pip3] torchaudio==0.14.0.dev20221030+cu116
[pip3] torchvision==0.15.0.dev20221030+cu116
[conda] Could not collect

cc @peterjc123 @mszhanyi @skyline75489 @nbcsm @kevinstephano @jjsjann123

**Comment by jjsjann123** [comment] 2022-11-01 19:55
Thanks for reporting and the repro. This is a failure that was patched in our devel repo: https://github.com/csarofeen/pytorch/issues/1843

I verified that the repro passed in our devel branch. We'll try to have it sync'ed in our next push.

**Comment by xsacha** [comment] 2022-11-03 22:47
I applied https://github.com/csarofeen/pytorch/pull/2044 on top of stable 1.13.0 and still get this warning (and error if i disable fallback).
Does it require any previous commits on that devel branch as well?

**Comment by jjsjann123** [comment] 2022-11-03 22:49
You also need https://github.com/csarofeen/pytorch/pull/2035, which is the real fix. 2044 is just a clean up on some false positive asserts.

**Comment by xsacha** [comment] 2022-11-03 22:49
Thanks!

**Comment by JFHlz** [comment] 2022-12-21 09:02
> Thanks! In that commit, there is a file vectorize_helper.cpp which doesn't appear in stable 1.13.0. I assume there's more commits for its enablement as well. Looks like: [csarofeen#1959](https://github.com/csarofeen/pytorch/pull/1959)

If your redirect your patch tool to utils.cpp in the same directory, two out of three hunks succeed. The last one is just a delete of some code, you can easily find the correct location and do it youself.

**Comment by mantaionut** [comment] 2023-01-23 10:40
I will close this issue since it cannot be reproduced on the nightly build. Please try on the nightly build and if it happens re-open it.

**Closed by mantaionut** 2023-01-23 10:40 UTC
Labels: module: windows, triaged, module: nvfuser

**Comment by josedev-union** [comment] 2023-09-12 06:30
@mantaionut Then exactly what version can I expect the fix from?
