### ISSUE TITLE
MaxUnpool1d error

### ISSUE THREAD

**Issue by syoungbaak** [pytorch/pytorch#771] opened 2017-02-17 13:49 UTC
I found some error in nn.MaxUnpool1d module.

    import torch
    import torch.nn as nn
    from torch.autograd import Variable

    pool = nn.MaxPool1d(kernel_size=3, stride=2, return_indices=True)
    unpool = nn.MaxUnpool1d(kernel_size=3, stride=2)
    input = Variable(torch.rand(32,128,263))
    output, inx = pool(input)
    input_ = unpool(output,inx)

However, if I use 2d instead, there is no error as blow.

    import torch
    import torch.nn as nn
    from torch.autograd import Variable

    pool = nn.MaxPool2d(kernel_size=(1,3), stride=(1,2), return_indices=True)
    unpool = nn.MaxUnpool2d(kernel_size=(1,3), stride=(1,2))
    input = Variable(torch.rand(32,128,1,263))
    output, inx = pool(input)
    input_ = unpool(output,inx)

**Comment by Teaonly** [comment] 2017-02-22 01:43
The issue is output of nn.MaxPool1d, the indices output is index of 1D ( CxHxW ) dimension . THNN_(SpatialMaxUnpooling_updateOutput_frame) wants indices is  index of W dimension.  

One solution is changing the  indices output from nn.MaxPool1d to index of W dimension. MaxPool1d is a MaxPool2d with height == 1.

**Comment by Teaonly** [comment] 2017-02-23 01:52
Currently the MaxPool1D 's backend is 'SpatialDilatedMaxPoolin' from THNN, but in Torch7, MaxPool1D's backend is 'TemporalMaxPooling'. 

```
th> help( nn.TemporalMaxPooling )
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
TemporalMaxPooling

 module = nn.TemporalMaxPooling(kW, [dW])

Applies 1D max-pooling operation in kW regions by step size dW steps.
Input sequence composed of nInputFrame frames. The input tensor in
forward(input) is expected to be a 2D tensor ( nInputFrame x inputFrameSize
)
or a 3D tensor ( nBatchFrame x nInputFrame x inputFrameSize ).

If the input sequence is a 2D tensor of dimension nInputFrame x inputFrameSize
, the output sequence will be nOutputFrame x inputFrameSize where
 nOutputFrame = (nInputFrame - kW) / dW + 1
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
``` 

In pytorch, if we want to MaxPool1D  like TemporalMaxPooling, we need change many files. If MaxPool1D is just a MaxPool2D which kernel_height equals 1, I will try to fix it, it is not a difficult task.

**Comment by syoungbaak** [comment] 2017-02-23 02:18
Thanks for your reply.
I will use MaxPool2D for a while.

**Comment by Teaonly** [comment] 2017-02-23 03:51
From comment in MaxPool1D module ,  MaxPool1D should accept 3D tensor( N*C*L). The actual backend is SpatialDilatedMaxPooling (THNN, THCUNN)，so we should change input to N*C*1*L 4D. The return indices will range from 0 to L.  If we don't change input's size, the return indices will range 0 to L*C, this range will produce error in MaxUnpool1D. 

So I think the solution is add a temporary size changing in MaxPool1D.

**Comment by Teaonly** [comment] 2017-02-23 06:25
https://github.com/pytorch/pytorch/pull/832  

I have verified in CPU and CUDA, the buggy code will not raise any error.

**Comment by soumith** [comment] 2017-02-25 13:54
fixed in master by @Teaonly

**Closed by soumith** 2017-02-25 13:54 UTC
Labels: bug, high priority
