### ISSUE TITLE
[MPS] Torch 2.5.x and Nightlies are using  50% more memory and are 60% slower than 2.4.1 run Stable Diffusion

### ISSUE THREAD

**Issue by Vargol** [pytorch/pytorch#139389] opened 2024-10-31 12:25 UTC
### 🐛 Describe the bug

I've seen a lot of people mentioning in various forums but not seen an issue raised here so here we go. I'm reporting this as an MPS issue as I've not been able to test on NVIDIA or AMD etc.

Running various Stable Diffusion and new transformer DiT models using 2.5.x and nightly releases of PyTorch shows a very significant downgrade in performance compared to running them in in the same environment using pytorch 2.4.1.

For example a standard SDXL run via Diffusers using 2.4.1, the python binary reports using 9.5Gb and runs at 5.7 seconds per iteration, under 2.5.1 or nightly it reports 14.9 GB and runs at 8.5 s/i

SD3.5 goes from running without setting  PYTORCH_MPS_HIGH_WATERMARK_RATIO  on a 24Gb M3 to failing if its not set to 0.0 and using 37Gb compared to 27.7GB when they first start iterating (2.5.1 takes ages to start iterating they'll use more when it kicks in properly).

Here is the diffusers SDXL script I used as that'll be the smallest and fastest model. Its a little messy as was a test script of something else  but I wanted to give you the exact same script, so you'll have to forgive the unused imports and variables :-)

```py
from diffusers import StableDiffusionXLPipeline, AutoencoderKL, EulerAncestralDiscreteScheduler
import torch
from torch import mps
import time

torch.mps.set_per_process_memory_fraction(0.0)

prompt = "Emily Booth as Sappho, cold color palette, vivid colors, detailed, 8k, 35mm photo, Kodachrome, Lomography, highly detailed"
negative_prompt = "painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured"

prompt="Nina Hagen as a 1960s (stingray puppet)++, supermarionation++ strings visible ,  ,  . vivid colors, detailed, 8k, 35mm photo, Kodachrome, Lomography, highly detailed"

negative_prompt="painting, drawing, illustration, glitch, mutated, cross-eyed, ugly, disfigured"

isteps=30
height=1024
width=1024
seed = 432773521 

vae = AutoencoderKL.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0",
                                    subfolder='vae',
                                    torch_dtype=torch.bfloat16,
                                    force_upcast=False).to('mps')


pipe = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", vae=vae,
    torch_dtype=torch.bfloat16, variant="fp16").to('mps')

#pipe.enable_vae_tiling()
#pipe.enable_attention_slicing()

pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)

generator =  torch.Generator("mps").manual_seed(seed);

image = pipe(prompt=prompt, negative_prompt=negative_prompt,
               height=height, width=width, 
               num_inference_steps=10,
               guidance_scale=8,
               generator=generator,
               ).images[0]

image.save(f'bfloat16.png')
```

environment id a straight forward diffusers venv
```sh
python -m venv sd35
cd sd35
. bin/activate
pip install diffusers accelerate transformers
```

torch version was switch around br doing an uninstall and reinstall

```sh
pip uninstall torch torchvision 
pip install torch==2.5.1 torchvision==0.20.1
```
or
```sh
pip uninstall torch torchvision 
pip install torch==2.4.1 torchvision==0.19.1
```

### Versions

 python lib/python3.11/site-packages/torch/utils/collect_env.py 
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False
CUDA used to build PyTorch: None
ROCM used to build PyTorch: N/A

OS: macOS 15.0.1 (arm64)
GCC version: Could not collect
Clang version: 16.0.0 (clang-1600.0.26.4)
CMake version: version 3.29.5
Libc version: N/A

Python version: 3.11.10 (main, Sep  7 2024, 08:05:54) [Clang 16.0.0 (clang-1600.0.26.3)] (64-bit runtime)
Python platform: macOS-15.0.1-arm64-arm-64bit
Is CUDA available: False
CUDA runtime version: No CUDA
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Apple M3

Versions of relevant libraries:
[pip3] numpy==2.1.2
[pip3] torch==2.5.1
[pip3] torchvision==0.20.1
[conda] Could not collect

cc @ezyang @gchanan @zou3519 @kadeng @msaroufim @kulinseth @albanD @malfet @DenisVieriu97 @jhavukainen

**Comment by malfet** [comment] 2024-11-01 22:56
@Vargol do you mind posting references to some of the forum threads here?

**Comment by Vargol** [comment] 2024-11-01 23:27
Struggling to find them again, crappy discord,  actually I keep finding people mentioning 2.4.0 period nightlies compared to 2.3.1 but try the example  it's hard to miss the slowdown and extra memory usage.

**Comment by malfet** [comment] 2024-11-01 23:31
I've modified script a bit
```python
from diffusers import StableDiffusionXLPipeline, AutoencoderKL, EulerAncestralDiscreteScheduler
import sys
import diffusers
import torch
import time


prompt = "Emily Booth as Sappho, cold color palette, vivid colors, detailed, 8k, 35mm photo, Kodachrome, Lomography, highly detailed"
negative_prompt = "painting, drawing, illustration, glitch, deformed, mutated, cross-eyed, ugly, disfigured"

prompt="Nina Hagen as a 1960s (stingray puppet)++, supermarionation++ strings visible ,  ,  . vivid colors, detailed, 8k, 35mm photo, Kodachrome, Lomography, highly detailed"

negative_prompt="painting, drawing, illustration, glitch, mutated, cross-eyed, ugly, disfigured"

isteps=30
height=1024
width=1024
seed = 432773521

print(f"Python version {sys.version} PyTorch version {torch.__version__} diffusers.version is {diffusers.__version__}")

vae = AutoencoderKL.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0",
                                    subfolder='vae',
                                    torch_dtype=torch.bfloat16,
                                    force_upcast=False).to('mps')


pipe = StableDiffusionXLPipeline.from_pretrained("stabilityai/stable-diffusion-xl-base-1.0", vae=vae,
    torch_dtype=torch.bfloat16, variant="fp16").to('mps')

pipe.scheduler = EulerAncestralDiscreteScheduler.from_config(pipe.scheduler.config)

generator =  torch.Generator("mps").manual_seed(seed);

start_time = time.time()
start_mps_mem = torch.mps.driver_allocated_memory()
image = pipe(prompt=prompt, negative_prompt=negative_prompt,
               height=height, width=width,
               num_inference_steps=10,
               guidance_scale=8,
               generator=generator,
               ).images[0]
end_mps_mem = torch.mps.driver_allocated_memory()
run_time = time.time() - start_time
print(f"run time in {run_time:.2f} sec, end_mps_mem {end_mps_mem/1024.0**2:.2f} Mb mem increase {(end_mps_mem-start_time)/1024.0**2:.2f} Mb")
image.save(f'bfloat16.png')
```
It reports that on my M2 Pro 2.4.1 finishes generation in 50 sec using 14Gb of memory, while 2.5.1 needs 64 sec and 16Gb RAM, so 30% slower and 15% more RAM, which is pretty bad

**Comment by Vargol** [comment] 2024-11-02 00:22
```
$ python gh.py
Python version 3.11.10 (main, Sep  7 2024, 08:05:54) [Clang 16.0.0 (clang-1600.0.26.3)] PyTorch version 2.4.1 diffusers.version is 0.31.0
Loading pipeline components...: 100%|███| 7/7 [00:14<00:00,  2.14s/it]
100%|████████████████████████████████| 10/10 [00:56<00:00,  5.64s/it]
run time in 63.50 sec, end_mps_mem 13596.62 Mb mem increase 11946.29 Mb
```

```
$ python gh.py
Python version 3.11.10 (main, Sep  7 2024, 08:05:54) [Clang 16.0.0 (clang-1600.0.26.3)] PyTorch version 2.5.1 diffusers.version is 0.31.0
Loading pipeline components...: 100%|███| 7/7 [00:10<00:00,  1.48s/it]
100%|█████████████████████████████████| 10/10 [01:26<00:00,  8.70s/it]
run time in 93.71 sec, end_mps_mem 16188.62 Mb mem increase 14538.29 Mb
```

**Comment by malfet** [comment] 2024-11-05 00:11
Doing a bit of a bisection, looks like regression happened between http://github.com/pytorch/pytorch/commit/cc1cc71c46029a70cda135ca0790f59283a49e47 and http://github.com/pytorch/pytorch/commit/07c73a964b881ee317e984a59aeedaef34a72b8d

**Comment by malfet** [comment] 2024-11-06 22:05
Let's keep it open for a bit until nightly is available and someone can confirm that this is working for them.
@Vargol can you build PyTorch from source using https://github.com/pytorch/pytorch/commit/68ef445c330d465d3d20f253583c2370c5df0139 or prefer to wait until nightly build is available?

**Comment by Vargol** [comment] 2024-11-06 22:06
As I'm off to bed in a few minutes it'll probably have to wait until the nightlies are built, what time is that normally ?

**Comment by skotapati** [comment] 2024-11-06 23:44
@malfet I just ran with ToT and the memory utilization + runtime is back in line with 2.4.1

**Comment by Vargol** [comment] 2024-11-07 12:14
Just tried a nightly.

```
Python version 3.11.10 (main, Sep  7 2024, 08:05:54) [Clang 16.0.0 (clang-1600.0.26.3)] PyTorch version 2.6.0.dev20241107 diffusers.version is 0.31.0
Loading pipeline components...: 
100%|██████████████████████████| 7/7 [00:09<00:00,  1.38s/it]
100%|██████████████████████████| 10/10 [00:53<00:00,  5.32s/it]
run time in 57.97 sec, end_mps_mem 14004.62 Mb mem increase 12353.83 Mb
```

speed is back, if fact its improved,  memory practically there ~ 3.4% .

**Comment by malfet** [comment] 2024-11-07 19:50
Cool thank you all for validating, closing now ,but need to figure out how we can monitor for something like that....

**Closed by malfet** 2024-11-07 19:50 UTC
Labels: high priority, module: memory usage, triaged, module: mps

**Comment by zacheryvaughn** [comment] 2024-11-14 15:18
I am struggling with the same issue right now.
dtype + torch 2.4.1 consistently performs inference 8X faster compared to torch_dtype + torch 2.4.1
torch 2.5.1 is 8X slower on when passing either dtype or torch_dtype.

Basically if you want "fast" inference on MPS right now, you have to use torch: 2.4.1 and pass dtype, not torch_dtype, and not torch: 2.5.1
