### ISSUE TITLE
Windows 10 pytorch installation with Python 3.8.6 not working

### ISSUE THREAD

**Issue by j-k** [pytorch/pytorch#47444] opened 2020-11-05 15:38 UTC
Hello, I just installed the current torch (1.7) and torchvision versions (0.8.1) and then this happend: 

>>> import torch
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD  parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\Python\Python38\lib\site-packages\torch\__init__.py", line 189, in <module>
    from torch._C import *
ImportError: numpy.core.multiarray failed to import

A working workaround seems to be:

pip install -U numpy==1.19.3

Installed was 1.19.4.

Then it can import torch. But I don't know if this is a real solution and if pytorch works as expeced.

cc @peterjc123 @maxluk @nbcsm @guyang3532 @gunandrose4u @smartcat2010 @mszhanyi

**Comment by peterjc123** [comment] 2020-11-05 18:12
I cannot reproduce it in the Circle CI environment. See https://github.com/peterjc123/pytorch_dll_load_smoketests/pull/17. Would you please share sth. more about your environment (e.g. Python distribution, IDE/Powershell/CMD)? Also, some logs about the process of DLL loading would be great.

**Comment by mszhanyi** [comment] 2020-11-06 03:48
do you run it in vscode? do you select the right python interpreter?

**Comment by peterjc123** [comment] 2020-11-09 16:43
Upstream issue:
https://github.com/numpy/numpy/issues/17726

Looks like we should pin numpy=1.19.3 for Pure Python users.

**Comment by j-k** [comment] 2020-11-10 16:20
I just installed python and and pytorch from scratch, called python from the console and tried to import torch. Nothing else. But I think you already found the issue. Thank you!

**Comment by jhenrich** [comment] 2020-11-14 20:16
@peterjc123 With that version if works for me

windows 10
python 3.8.6
pytorch 1.7.0+cpu

**Comment by sudonto** [comment] 2020-11-18 08:03
@j-k I face same issue with you and your suggestion works for me! Thanks.

**Comment by vladimir-aubrecht** [comment] 2022-11-04 16:10
Could not reproduce on latest stack and reading the comments seems it was fixed in time. Closing issue as it's old and seems solved. In case your issue still persists on latest stack, please create new issue.

**Closed by vladimir-aubrecht** 2022-11-04 16:10 UTC
Labels: module: windows, triaged
