### ISSUE TITLE
Compilation Error, x64-windows

### ISSUE THREAD

**Issue by Mateusz404** [pytorch/pytorch#135774] opened 2024-09-11 23:39 UTC
### 🐛 Describe the bug

**Flow**
1. Added the "libtorch" to vcpkg.json
2. Opened the project's SSL and Rebuild Solution
3. After a while _Build FAILED._

At the end of the build-torch_cpu-x64-windows-dbg-out:
ninja: build stopped: subcommand failed.

Whole log file:
[build-torch_cpu-x64-windows-dbg-out.log](https://github.com/user-attachments/files/16971396/build-torch_cpu-x64-windows-dbg-out.log)

Adding also build-header_gen-x64-windowsdbg-out, not sure if that helps:
[build-header_gen-x64-windows-dbg-out.log](https://github.com/user-attachments/files/16971398/build-header_gen-x64-windows-dbg-out.log)

config-x64-windows-dbg-err
[config-x64-windows-dbg-CMakeCache.txt.log](https://github.com/user-attachments/files/16971399/config-x64-windows-dbg-CMakeCache.txt.log)

### Versions

Collecting environment information...
PyTorch version: 2.4.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Microsoft Windows 11 Pro
GCC version: Could not collect
Clang version: 16.0.0
CMake version: version 3.28.0-rc1
Libc version: N/A

Python version: 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] (64-bit runtime)
Python platform: Windows-11-10.0.22631-SP0
Is CUDA available: False
CUDA runtime version: Could not collect
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: GPU 0: NVIDIA GeForce RTX 4080
Nvidia driver version: 546.29
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture=9
CurrentClockSpeed=3000
DeviceID=CPU0
Family=207
L2CacheSize=32768
L2CacheSpeed=
Manufacturer=GenuineIntel
MaxClockSpeed=3000
Name=13th Gen Intel(R) Core(TM) i9-13900KF
ProcessorType=3
Revision=

Versions of relevant libraries:
[pip3] flake8==7.0.0
[pip3] numpy==1.26.3
[pip3] torch==2.4.0
[conda] Could not collect

cc @malfet @seemethere @peterjc123 @mszhanyi @skyline75489 @nbcsm @iremyux @Blackhex @jbschlosser

**Comment by Mateusz404** [comment] 2024-09-12 00:46
It might be not related, but when I try to use:
**C:\vcpkg>vcpkg install libtorch**

instead, then I got magma compilation errors.

Logs
[config-x64-windows-dbg-ninja.log](https://github.com/user-attachments/files/16971838/config-x64-windows-dbg-ninja.log)

**Comment by malfet** [comment] 2024-09-12 21:06
You hit an internal compiler exception, what's your VC++ version:
```
C:\vcpkg\buildtrees\libtorch\src\v1.12.1-e1cb316ec6.clean\aten\src\ATen/cpu/vec/vec_base.h(134): fatal error C1001: Internal compiler error.
(compiler file 'D:\a\_work\1\s\src\vctools\Compiler\CxxFE\sl\p1\c\toinil.c', line 910)
 To work around this problem, try simplifying or changing the program near the locations listed above.
If possible please provide a repro here: https://developercommunity.visualstudio.com 
Please choose the Technical Support command on the Visual C++ 
 Help menu, or open the Technical Support help file for more information
```

Which might have been fixed by https://github.com/pytorch/pytorch/pull/117497 but you are trying to compile PyTorch-1.12, which might still containing this error

**Comment by malfet** [comment] 2024-09-12 21:07
Closing as duplicate of https://github.com/pytorch/pytorch/issues/115922

**Closed by malfet** 2024-09-12 21:07 UTC
Labels: needs reproduction, module: build, module: windows
