### ISSUE TITLE
torch.unique not supported for bfloat16 on GPU

### ISSUE THREAD

**Issue by raunaks13** [pytorch/pytorch#142192] opened 2024-12-06 01:03 UTC
### 🐛 Describe the bug

When I try to run `torch.unique()` on a tensor of type bfloat16, the operation fails if the tensor is on the cuda device. 

To reproduce: 
```
a = torch.tensor([1.0, 2, 1.0, 2.5, 3.5], dtype=torch.bfloat16)
unique, counts = torch.unique(a.to('cuda'), return_counts=True)
```
This gives an error `RuntimeError: "unique" not implemented for 'BFloat16'`
The code runs fine if the tensor is on CPU instead (I am not sure why), but this takes longer and is not scalable for large tensors.

Are there any alternatives to do this faster?

### Versions

```
Collecting environment information...
PyTorch version: 2.2.1+cu121
Is debug build: False
CUDA used to build PyTorch: 12.1
ROCM used to build PyTorch: N/A

OS: Red Hat Enterprise Linux Server release 7.9 (Maipo) (x86_64)
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: Could not collect
CMake version: version 2.8.12.2
Libc version: glibc-2.17

Python version: 3.11.8 (main, Feb 26 2024, 21:39:34) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-3.10.0-1160.119.1.el7.x86_64-x86_64-with-glibc2.17
Is CUDA available: True
CUDA runtime version: 11.7.64
CUDA_MODULE_LOADING set to: LAZY
GPU models and configuration: GPU 0: NVIDIA A40
Nvidia driver version: 545.23.08
cuDNN version: Could not collect
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian 
CPU(s):                128
On-line CPU(s) list:   0-127
Thread(s) per core:    1
Core(s) per socket:    64
Socket(s):             2
NUMA node(s):          2
Vendor ID:             AuthenticAMD  
CPU family:            23
Model:                 49
Model name:            AMD EPYC 7702 64-Core Processor
Stepping:              0
CPU MHz:               1996.374
BogoMIPS:              3992.74
Virtualization:        AMD-V
L1d cache:             32K
L1i cache:             32K
L2 cache:              512K
L3 cache:              16384K
NUMA node0 CPU(s):     0-63
NUMA node1 CPU(s):     64-127
Flags:                 fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc art rep_good nopl nonstop_tsc extd_apicid aperfmperf eagerfpu pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_l2 cpb cat_l3 cdp_l3 hw_pstate ssbd rsb_ctxsw ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local clzero irperf xsaveerptr arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif umip overflow_recov succor smca

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] nvidia-cublas-cu12==12.1.3.1  
[pip3] nvidia-cuda-cupti-cu12==12.1.105
[pip3] nvidia-cuda-nvrtc-cu12==12.1.105
[pip3] nvidia-cuda-runtime-cu12==12.1.105
[pip3] nvidia-cudnn-cu12==8.9.2.26   
[pip3] nvidia-cufft-cu12==11.0.2.54  
[pip3] nvidia-curand-cu12==10.3.2.106
[pip3] nvidia-cusolver-cu12==11.4.5.107
[pip3] nvidia-cusparse-cu12==12.1.0.106
[pip3] nvidia-nccl-cu12==2.19.3
[pip3] nvidia-nvjitlink-cu12==12.4.99
[pip3] nvidia-nvtx-cu12==12.1.105
[pip3] torch==2.2.1
[pip3] torchaudio==2.0.2
[pip3] torchvision==0.15.2
[pip3] triton==2.2.0
[conda] blas                      1.0                         mkl
[conda] cuda-cudart               11.7.99                       0    nvidia
[conda] cuda-cupti                11.7.101                      0    nvidia
[conda] cuda-libraries            11.7.1                        0    nvidia
[conda] cuda-nvrtc                11.7.99                       0    nvidia
[conda] cuda-nvtx                 11.7.91                       0    nvidia
[conda] cuda-runtime              11.7.1                        0    nvidia
[conda] ffmpeg                    4.3                  hf484d3e_0    pytorch
[conda] libcublas                 11.10.3.66                    0    nvidia
[conda] libcufft                  10.7.2.124           h4fbf590_0    nvidia
[conda] libcurand                 10.3.5.119                    0    nvidia
[conda] libcusolver               11.4.0.1                      0    nvidia
[conda] libcusparse               11.7.4.91                     0    nvidia
[conda] mkl                       2023.1.0         h213fc3f_46344
[conda] mkl-service               2.4.0           py311h5eee18b_1
[conda] mkl_fft                   1.3.8           py311h5eee18b_0
[conda] mkl_random                1.2.4           py311hdb19cb5_0
[conda] numpy                     1.26.4          py311h08b1b3b_0
[conda] numpy-base                1.26.4          py311hf175353_0
[conda] nvidia-cublas-cu12        12.1.3.1                 pypi_0    pypi
[conda] nvidia-cuda-cupti-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-nvrtc-cu12    12.1.105                 pypi_0    pypi
[conda] nvidia-cuda-runtime-cu12  12.1.105                 pypi_0    pypi
[conda] nvidia-cudnn-cu12         8.9.2.26                 pypi_0    pypi
[conda] nvidia-cufft-cu12         11.0.2.54                pypi_0    pypi
[conda] nvidia-curand-cu12        10.3.2.106               pypi_0    pypi
[conda] nvidia-cusolver-cu12      11.4.5.107               pypi_0    pypi
[conda] nvidia-cusparse-cu12      12.1.0.106               pypi_0    pypi
[conda] nvidia-nccl-cu12          2.19.3                   pypi_0    pypi
[conda] nvidia-nvjitlink-cu12     12.4.99                  pypi_0    pypi
[conda] nvidia-nvtx-cu12          12.1.105                 pypi_0    pypi
[conda] pytorch-cuda              11.7                 h778d358_5    pytorch
[conda] pytorch-mutex             1.0                        cuda    pytorch
[conda] torch                     2.2.1                    pypi_0    pypi
[conda] torchaudio                2.0.2               py311_cu117    pytorch
[conda] torchvision               0.15.2              py311_cu117    pytorch
[conda] triton                    2.2.0                    pypi_0    pypi
```

cc @ptrblck @msaroufim @eqy

**Comment by eqy** [comment] 2024-12-06 02:50
Support for this was added a while ago https://github.com/pytorch/pytorch/pull/136114

So you might consider upgrading to e.g., 2.5 and trying again

**Comment by malfet** [comment] 2024-12-06 16:57
Closing as duplicate of https://github.com/pytorch/pytorch/issues/136090

**Closed by malfet** 2024-12-06 16:57 UTC
Labels: module: cuda, triaged, module: bfloat16
