### ISSUE TITLE
Cannot export fasterrcnn/keypointrcnn/fasterrcnn to ONNX.

### ISSUE THREAD

**Issue by Exlsunshine** [pytorch/pytorch#27969] opened 2019-10-15 09:37 UTC
## 🐛 Bug

Cannot export torchvision.models.detection.fasterrcnn_resnet50_fpn to `ONNX` format.
There already many reports about this error, such [issue1](https://github.com/pytorch/pytorch/issues/24009), [issue2](https://discuss.pytorch.org/t/exporting-fasterrcnn-fasterrcnn-resnet50-fpn-to-onnx/55246), [issue3](https://github.com/pytorch/pytorch/issues/22960):
```

C:\x\Python\Python36\lib\site-packages\torch\tensor.py:410: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
Traceback (most recent call last):
  File "detect_test.py", line 62, in <module>
    torch.onnx.export(model, dummy_input, "test.onnx")
  File "C:\x\Python\Python36\lib\site-packages\torch\onnx\__init__.py", line 143, in export
    strip_doc_string, dynamic_axes, keep_initializers_as_inputs)
  File "C:\x\Python\Python36\lib\site-packages\torch\onnx\utils.py", line 66, in export
    dynamic_axes=dynamic_axes, keep_initializers_as_inputs=keep_initializers_as_inputs)
  File "C:\x\Python\Python36\lib\site-packages\torch\onnx\utils.py", line 382, in _export
    fixed_batch_size=fixed_batch_size)
  File "C:\x\Python\Python36\lib\site-packages\torch\onnx\utils.py", line 249, in _model_to_graph
    graph, torch_out = _trace_and_get_graph_from_model(model, args, training)
  File "C:\x\Python\Python36\lib\site-packages\torch\onnx\utils.py", line 206, in _trace_and_get_graph_from_model
    trace, torch_out, inputs_states = torch.jit.get_trace_graph(model, args, _force_outplace=True, _return_inputs_states=True)
  File "C:\x\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 275, in get_trace_graph
    return LegacyTracedModule(f, _force_outplace, return_inputs, _return_inputs_states)(*args, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torch\jit\__init__.py", line 352, in forward
    out = self.inner(*trace_inputs)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torchvision\models\detection\generalized_rcnn.py", line 48, in forward
    features = self.backbone(images.tensors)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torchvision\models\_utils.py", line 58, in forward
    x = module(x)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 539, in __call__
    result = self._slow_forward(*input, **kwargs)
  File "C:\x\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 525, in _slow_forward
    result = self.forward(*input, **kwargs)
RuntimeError: Tried to trace <__torch__.torchvision.ops.misc.FrozenBatchNorm2d object at 000001B12F03D030> but it is not part of the active trace. Modules that are called during a trace must be registered as submodules of the thing being traced.

Process finished with exit code 1

```

## To Reproduce

Execute the following code:

```
import torchvision
import PIL
import os

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()

image = PIL.Image.open(os.path.join(os.path.dirname(__file__), 'cat.jpg'))
image_tensor = torchvision.transforms.functional.to_tensor(image)

import torch.onnx
dummy_input = [torch.randn(3, 1199, 1200)]
torch.onnx.export(model, dummy_input, "test.onnx")

```
## Expected behavior

Generate a "test.onnx"

## Environment

Please copy and paste the output from our
[environment collection script](https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py)
(or fill out the checklist below manually).

You can get the script and run it with:
```
wget https://raw.githubusercontent.com/pytorch/pytorch/master/torch/utils/collect_env.py
# For security purposes, please check the contents of collect_env.py before running it.
python collect_env.py
```

 - PyTorch Version (e.g., 1.0): 1.3.0
 - OS (e.g., Linux): Windows10
 - How you installed PyTorch (`conda`, `pip`, source): pip
 - Build command you used (if compiling from source): None
 - Python version: 3.6
 - CUDA/cuDNN version: None
 - GPU models and configuration: None
 - Any other relevant information: None

**Comment by dashesy** [comment] 2019-10-16 00:06
Either `__torch__.torchvision.ops.misc.FrozenBatchNorm2d` can register a custom ops using `torch::jit::RegisterOperators().op(...)` and then you patch ONNX to make that a normal BN. 
Or as a workaround you can use `cfg.MODEL.BACKBONE.USE_BN = True` and make sure normal BN is used during tracing.

**Comment by Exlsunshine** [comment] 2019-10-16 09:05
> Either `__torch__.torchvision.ops.misc.FrozenBatchNorm2d` can register a custom ops using `torch::jit::RegisterOperators().op(...)` and then you patch ONNX to make that a normal BN.
> Or as a workaround you can use `cfg.MODEL.BACKBONE.USE_BN = True` and make sure normal BN is used during tracing.

I'd like to try the second workaround, but I don't have too much background about pytorch and onnx. It would be nice if you could explain more about how to set `cfg.MODEL.BACKBONE.USE_BN = True`? Really appreciate your help : )

**Comment by fmassa** [comment] 2019-10-16 14:49
As @RicCu mentioned, support for ONNX will be added very soon to torchvision models

**Comment by mehdiAtCellarEye** [comment] 2019-10-31 16:18
@RicCu and @fmassa,

Both PRs seems to be closed and merged. However, I still cannot get it working using the nightly (torch version 1.4.0.dev20191030 and torchvision 0.5.0.dev20191031). I tried with cuda as:

`import torch, torchvision
device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True).to(device)
model.eval()

image = torch.randn(3, 800, 1333, device=device)
images = [image]

torch.onnx.export(model, (images, ), 'faster_rcnn.onnx', do_constant_folding=True, opset_version=10)`

I got the following error:

`/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/transform.py in _onnx_dynamic_img_pad(self, img, padding)
     94     # it is used to process the images in _onnx_batch_images().
     95     def _onnx_dynamic_img_pad(self, img, padding):
---> 96         concat_0 = torch.cat((img, torch.zeros(padding[0], img.shape[1], img.shape[2])), 0)
     97         concat_1 = torch.cat((concat_0, torch.zeros(concat_0.shape[0], padding[1], concat_0.shape[2])), 1)
     98         padded_img = torch.cat((concat_1, torch.zeros(concat_1.shape[0], concat_1.shape[1], padding[2])), 2)

RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'`

Without cuda, I got the following error:

`/usr/local/lib/python3.6/dist-packages/torchvision/ops/poolers.py in infer_scale(self, feature, original_size)
    120         for s1, s2 in zip(size, original_size):
    121             approx_scale = float(s1) / s2
--> 122             scale = 2 ** torch.tensor(approx_scale).log2().round().item()
    123             possible_scales.append(scale)
    124         assert possible_scales[0] == possible_scales[1]

RuntimeError: log2_vml_cpu not implemented for 'Long'`
 
Could you please let us know when the conversion is expected to work?

**Comment by niaoyu** [comment] 2019-11-02 18:17
> @RicCu and @fmassa,
> 
> Both PRs seems to be closed and merged. However, I still cannot get it working using the nightly (torch version 1.4.0.dev20191030 and torchvision 0.5.0.dev20191031). I tried with cuda as:
> 
> `import torch, torchvision
> device = torch.device('cuda') if torch.cuda.is_available() else torch.device('cpu')
> model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True).to(device)
> model.eval()
> 
> image = torch.randn(3, 800, 1333, device=device)
> images = [image]
> 
> torch.onnx.export(model, (images, ), 'faster_rcnn.onnx', do_constant_folding=True, opset_version=10)`
> 
> I got the following error:
> 
> `/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/transform.py in _onnx_dynamic_img_pad(self, img, padding)
> 94 # it is used to process the images in _onnx_batch_images().
> 95 def _onnx_dynamic_img_pad(self, img, padding):
> ---> 96 concat_0 = torch.cat((img, torch.zeros(padding[0], img.shape[1], img.shape[2])), 0)
> 97 concat_1 = torch.cat((concat_0, torch.zeros(concat_0.shape[0], padding[1], concat_0.shape[2])), 1)
> 98 padded_img = torch.cat((concat_1, torch.zeros(concat_1.shape[0], concat_1.shape[1], padding[2])), 2)
> 
> RuntimeError: Expected object of backend CUDA but got backend CPU for sequence element 1 in sequence argument at position #1 'tensors'`
> 
> Without cuda, I got the following error:
> 
> `/usr/local/lib/python3.6/dist-packages/torchvision/ops/poolers.py in infer_scale(self, feature, original_size)
> 120 for s1, s2 in zip(size, original_size):
> 121 approx_scale = float(s1) / s2
> --> 122 scale = 2 ** torch.tensor(approx_scale).log2().round().item()
> 123 possible_scales.append(scale)
> 124 assert possible_scales[0] == possible_scales[1]
> 
> RuntimeError: log2_vml_cpu not implemented for 'Long'`
> 
> Could you please let us know when the conversion is expected to work?

@fmassa 
I just have the same issue, my env info is show as:
`
PyTorch version: 1.4.0a0+496d232
Is debug build: No
CUDA used to build PyTorch: 10.1

OS: Ubuntu 16.04.6 LTS
GCC version: (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609
CMake version: version 3.14.0

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 10.1.243
GPU models and configuration: 
GPU 0: Tesla V100-SXM2-16GB
GPU 1: Tesla V100-SXM2-16GB
GPU 2: Tesla V100-SXM2-16GB
GPU 3: Tesla V100-SXM2-16GB
GPU 4: Tesla V100-SXM2-16GB
GPU 5: Tesla V100-SXM2-16GB
GPU 6: Tesla V100-SXM2-16GB
GPU 7: Tesla V100-SXM2-16GB

Nvidia driver version: 418.67
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.6.3
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip] Could not collect
[conda] torch                     1.4.0a0+496d232          pypi_0    pypi
[conda] torchvision               0.5.0a0+9cdc814          pypi_0    pypi
`

**Comment by fmassa** [comment] 2019-11-03 10:39
@lara-hdr do you know what should be changed so that exporting to onnx work in this situation?

**Comment by lara-hdr** [comment] 2019-11-03 17:31
The PRs to support the ONNX export for FasterRcnn and MaskRcnn are merged in Torchvision, but as you can see in https://github.com/pytorch/vision/blob/master/test/test_onnx.py the tests are still disabled.
In PyTorch, https://github.com/pytorch/pytorch/pull/28225 is required to be able to export the models correctly and is not yet merged. This PR should be sufficient to export fasterRCNN (for maskrcnn there is one last bug fix that should be merged in PyTorch). Could you also try running the model once with the dummy input before exporting it?

I will look into the the GPU error.

**Comment by lara-hdr** [comment] 2019-11-03 17:35
Also note that in https://github.com/pytorch/vision/blob/master/test/test_onnx.py the tests use opset 10 (since opset 11 was not implemented in onnxruntime for testing). 
But the the models are exportable with opset 11, and test_onnx.py will be updated when enabling the tests, to use this version once the PRs are merged in PyTorch.

**Comment by edigeze** [comment] 2019-11-05 17:16
@fmassa  and @lara-hdr  
Thanks for your comments,
The PR #28225  seems to be closed and merged. However, I can't run the above script to convert fasterrcnn_resnet50_fpn to onnx even with opset=11. Otherwise could you explain me how to use directly https://github.com/pytorch/vision/blob/master/test/test_onnx.py to export model ?

**Comment by mehdiAtCellarEye** [comment] 2019-11-06 00:35
@fmassa and @lara-hdr 
Thanks a lot for helpful comments. @lara-hdr, as suggested, I passed the dummy input through the model before conversion (without CUDA). It went through and onnx.checker.check_model() did not  complain. However, I was not able to run the converted model with onnxruntime following the code below:

```
import onnxruntime
import torch, torchvision
import numpy as np

model = torchvision.models.detection.fasterrcnn_resnet50_fpn(pretrained=True)
model.eval()

# Input to the model
width = 1200
x = [torch.randn(1, 800, width, requires_grad=True)]
torch_out = model(x)

ort_session = onnxruntime.InferenceSession('faster_rcnn.onnx')

def to_numpy(input_list):
    out = []
    for x in input_list:
      out.append(x.detach().cpu().numpy() if x.requires_grad else x.cpu().numpy())
    return out

# compute ONNX Runtime output prediction
ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
ort_outs = ort_session.run(None, ort_inputs)

# compare ONNX Runtime and PyTorch results
np.testing.assert_allclose(to_numpy(torch_out), ort_outs[0], rtol=1e-03, atol=1e-05)

print("Exported model has been tested with ONNXRuntime, and the result looks good!")
```
I got the following error:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-c012fb3e4e09> in <module>()
     24 # compute ONNX Runtime output prediction
     25 ort_inputs = {ort_session.get_inputs()[0].name: to_numpy(x)}
---> 26 ort_outs = ort_session.run(None, ort_inputs)
     27 
     28 # compare ONNX Runtime and PyTorch results

/usr/local/lib/python3.6/dist-packages/onnxruntime/capi/session.py in run(self, output_names, input_feed, run_options)
    134             output_names = [output.name for output in self._outputs_meta]
    135         try:
--> 136             return self._sess.run(output_names, input_feed, run_options)
    137         except C.EPFail as err:
    138             if self._enable_fallback:

RuntimeError: Either type_proto was null or it was not of sequence type
```


I also tried using opset 11 and got the following error during the conversion:

```
/usr/local/lib/python3.6/dist-packages/torch/tensor.py:458: RuntimeWarning: Iterating over a tensor might cause the trace to be incorrect. Passing a tensor of different shape won't change the number of iterations executed (and might lead to errors or silently give incorrect results).
  'incorrect results).', category=RuntimeWarning)
/usr/local/lib/python3.6/dist-packages/torch/onnx/symbolic_opset9.py:1899: UserWarning: Exporting aten::index operator of advanced indexing in opset 11 is achieved by combination of multiple ONNX operators, including Reshape, Transpose, Concat, and Gather. If indices include negative values, the exported graph will produce incorrect results.
  "If indices include negative values, the exported graph will produce incorrect results.")
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:674: UserWarning: ONNX export failed on an operator with unrecognized namespace torchvision::nms; If you are trying to export a custom operator, make sure you registered it with the right domain and version.Otherwise please report a bug
  "Otherwise please report a bug".format(ns, op_name))
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py:674: UserWarning: ONNX export failed on an operator with unrecognized namespace torchvision::roi_align; If you are trying to export a custom operator, make sure you registered it with the right domain and version.Otherwise please report a bug
  "Otherwise please report a bug".format(ns, op_name))
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-5-ef7271cc27af> in <module>()
     17                   input_names = ['input'],   # the model's input names
     18                   output_names = ['output'], # the model's output names
---> 19                   dynamic_axes={'input' : {2 : 'width'}, }    # variable lenght axes
     20                                 )

2 frames
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py in _export(model, args, f, export_params, verbose, training, input_names, output_names, operator_export_type, export_type, example_outputs, propagate, opset_version, _retain_param_name, do_constant_folding, strip_doc_string, dynamic_axes, keep_initializers_as_inputs, fixed_batch_size)
    392             proto, export_map = graph._export_onnx(
    393                 params_dict, opset_version, dynamic_axes, defer_weight_export,
--> 394                 operator_export_type, strip_doc_string, val_keep_init_as_ip)
    395         else:
    396             proto, export_map = graph._export_onnx(

RuntimeError: ONNX export failed: Couldn't export operator torchvision::nms

Defined at:
/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py(31): nms
/usr/local/lib/python3.6/dist-packages/torchvision/ops/boxes.py(70): batched_nms
/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/rpn.py(367): filter_proposals
/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/rpn.py(442): forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(525): _slow_forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(539): __call__
/usr/local/lib/python3.6/dist-packages/torchvision/models/detection/generalized_rcnn.py(51): forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(525): _slow_forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(539): __call__
/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py(352): wrapper
/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py(365): forward
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py(541): __call__
/usr/local/lib/python3.6/dist-packages/torch/jit/__init__.py(283): get_trace_graph
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py(206): _trace_and_get_graph_from_model
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py(249): _model_to_graph
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py(382): _export
/usr/local/lib/python3.6/dist-packages/torch/onnx/utils.py(66): export
/usr/local/lib/python3.6/dist-packages/torch/onnx/__init__.py(146): export
<ipython-input-5-ef7271cc27af>(19): <module>
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py(2882): run_code
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py(2828): run_ast_nodes
/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py(2718): run_cell
/usr/local/lib/python3.6/dist-packages/ipykernel/zmqshell.py(533): run_cell
/usr/local/lib/python3.6/dist-packages/ipykernel/ipkernel.py(196): do_execute
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py(399): execute_request
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py(235): dispatch_shell
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelbase.py(283): dispatcher
/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py(277): null_wrapper
/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py(432): _run_callback
/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py(480): _handle_recv
/usr/local/lib/python3.6/dist-packages/zmq/eventloop/zmqstream.py(450): _handle_events
/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py(277): null_wrapper
/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py(888): start
/usr/local/lib/python3.6/dist-packages/ipykernel/kernelapp.py(477): start
/usr/local/lib/python3.6/dist-packages/traitlets/config/application.py(664): launch_instance
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py(16): <module>
/usr/lib/python3.6/runpy.py(85): _run_code
/usr/lib/python3.6/runpy.py(193): _run_module_as_main
```

**Comment by lara-hdr** [comment] 2019-11-06 00:46
@mehdiAtCellarEye the error with torchvision::nms is because the customs ops where registered for opset 10. Now that opset 11 is available, the tests will be enabled in this PR : https://github.com/pytorch/vision/pull/1555.
You mentioned the model went through onnx.checker.check_model(), maybe the issue is with the construction of ort_inputs? Could you test with the example in test_onnx.py in #1555?

**Comment by dashesy** [comment] 2019-11-06 01:03
@lara-hdr when we register a custom ops for opset10, exporting with opset11 should succeed. Similar to how opset9 operators will be used when there is no change in opset10 /11 ?
@mehdiAtCellarEye you can register nms against opset11 manually.

```python
def register_custom_nms_op(opset_version=10):
    # experimenting custom op registration.
    from torch.onnx.symbolic_helper import parse_args
    from torch.onnx.symbolic_opset9 import view, select
    @parse_args('v', 'v', 'f', 'i')
    def symbolic_nms(g, boxes, scores, iou_threshold, max_output_boxes):
        # if should return all
        if max_output_boxes <= 0:
            max_output_boxes = 10000
        boxes = view(g, boxes, (1, -1, 4))
        max_output_per_class = g.op('Constant', value_t=torch.tensor([max_output_boxes], dtype=torch.long))
        iou_threshold = g.op('Constant', value_t=torch.tensor([iou_threshold], dtype=torch.float))
        # center_point_box == 1 is for our center_x, centr_y, width, height format
        nms_out = g.op('NonMaxSuppression',
                       boxes, view(g, scores, (1, 1, -1)), max_output_per_class, iou_threshold,
                       center_point_box_i=1)
        idx = select(g, nms_out, 1, g.op('Constant', value_t=torch.tensor([2], dtype=torch.long)))
        return view(g, idx, (-1,))

    from torch.onnx import register_custom_op_symbolic
    register_custom_op_symbolic('roi_ops::nms', symbolic_nms, opset_version)
```

Make sure `roi_ops` is the correct namespace.

**Comment by niaoyu** [comment] 2019-11-06 07:58
> @mehdiAtCellarEye the error with torchvision::nms is because the customs ops were registered for opset 10 since opset 11 was not yet fully implemented.
> Now that opset 11 is available, the tests will be enabled in this PR : [pytorch/vision#1555](https://github.com/pytorch/vision/pull/1555) (the custom ops are also registered for opset 11 in this PR).
> You mentioned the model went through onnx.checker.check_model(), maybe the issue is with the construction of ort_inputs? Could you test with the example in test_onnx.py in [pytorch/vision#1555](https://github.com/pytorch/vision/pull/1555)?

Thanks for your comments. I have  transfered fasterrcnn model to onnx successfully by  merge the PR manually.  I just have 2 more questions.
1. There is no 'cuda' things in the  test_onnx.py for testing fasterrcnn.
What should be down for the testing with cuda?
Does the onnxruntime.InferenceSession run the onnx model with cuda automally just use the similar code without 'cuda things'?
Or do we need to  move the pytorch model to gpu and then convert it to ONNX?

2. How about the maskrcnn model? What is the meaning of "for maskrcnn there is one last bug fix that should be merged in PyTorch".

**Comment by mehdiAtCellarEye** [comment] 2019-11-06 22:21
Thanks @lara-hdr and @dashesy! Really appreciate the help. With PR #1555, I was able to successfully convert the Faster R-CNN model to ONNX using upset 11 and was able to run it with onnxruntime. Still conversion with CUDA does not work. In the Pytorch official tutorial https://pytorch.org/docs/stable/onnx.html, the model is converted with CUDA to run in Caffe2 or ONNX Runtime. Do I really need conversion with CUDA to take advantage of GPU acceleration? Sorry if I am not familiar with how ONNX works.

**Comment by niaoyu** [comment] 2019-11-12 09:24
> Thanks @lara-hdr and @dashesy! Really appreciate the help. With PR [pytorch/vision#1555](https://github.com/pytorch/vision/pull/1555), I was able to successfully convert the Faster R-CNN model to ONNX using upset 11 and was able to run it with onnxruntime. Still conversion with CUDA does not work. In the Pytorch official tutorial https://pytorch.org/docs/stable/onnx.html, the model is converted with CUDA to run in Caffe2 or ONNX Runtime. Do I really need conversion with CUDA to take advantage of GPU acceleration? Sorry if I am not familiar with how ONNX works.

I just tried use onnx-cpu to run it correctly, and onnx-gpu need to build from source if your cuda is not 10.0. Just use pip install onnx-gpu. However I went wrong with the onnx issues..

**Comment by fmassa** [comment] 2019-11-26 13:35
This is now fixed in PyTorch and torchvision master.

**Closed by fmassa** 2019-11-26 13:35 UTC
Labels: module: onnx, triaged
