### ISSUE TITLE
Windows 10 Build Error - caffee_gpu.vcxproj

### ISSUE THREAD

**Issue by ejoebstl** [pytorch/pytorch#13808] opened 2018-11-10 13:40 UTC
## Build Error'ing on Windows

I'm facing the following build error on Windows 10. 

```
"E:\Projects\code-dnn\pytorch\build\INSTALL.vcxproj" (default target) (1) ->
"E:\Projects\code-dnn\pytorch\build\ALL_BUILD.vcxproj" (default target) (3) ->
"E:\Projects\code-dnn\pytorch\build\caffe2\AlgorithmsTest.vcxproj" (default target) (4) ->
"E:\Projects\code-dnn\pytorch\build\caffe2\caffe2_gpu.vcxproj" (default target) (22) ->
(CustomBuild target) ->
  Error : Internal Compiler error (codegen): "there was an error in verifying the lgenfe output!" [E:\Projects\code-dnn\pytorch\build\caffe2\caffe2_gpu.vcxp
roj]

    13025 Warning(s)
    1 Error(s)
```

There are no prior errors in the output of cmake. 

## To Reproduce

Using Visual Studio 2017, Cuda 10, in a Native Tools Command Prompt:

1.  python setup.py build develop

**Comment by peterjc123** [comment] 2019-03-15 05:10
Duplicate of https://github.com/pytorch/pytorch/issues/15630.

**Closed by peterjc123** 2019-03-15 05:10 UTC
Labels: windows
