### ISSUE TITLE
Argmax performance slower than numpy

### ISSUE THREAD

**Issue by tbenst** [pytorch/pytorch#8817] opened 2018-06-23 01:19 UTC
## Issue description

torch.argmax on a cuda array is slower than transferring to CPU and then calling np.argmax

## Code example

https://gist.github.com/tbenst/de3f61ac9956778a2ca6d5db94b526ef

## System Info
PyTorch version: 0.4.0
Is debug build: No
CUDA used to build PyTorch: 8.0.61

OS: Ubuntu 16.04.4 LTS
GCC version: (GCC) 6.3.0
CMake version: version 3.5.1

Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.0.176
GPU models and configuration: GPU 0: GeForce GTX 1070
Nvidia driver version: 384.130
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.1.10
/usr/lib/x86_64-linux-gnu/libcudnn.so.7.0.5
/usr/lib/x86_64-linux-gnu/libcudnn_static_v5.a
/usr/lib/x86_64-linux-gnu/libcudnn_static_v7.a

Versions of relevant libraries:
[pip3] numpy (1.14.2)
[pip3] numpydoc (0.7.0)
[pip3] torch (0.4.0)
[pip3] torchvision (0.2.0)
[conda] cuda80                    1.0                           0    soumith
[conda] cuda90                    1.0                  h6433d27_0    pytorch
[conda] pytorch                   0.4.0            py36hd73e86b_0  
[conda] torchvision               0.2.0            py36h17b6947_1    pytorch

**Comment by tbenst** [comment] 2019-01-16 00:37
@colesbury any update on this? Appreciate the work!

**Comment by tbenst** [comment] 2019-04-03 18:10
@ailzhang do you know if @colesbury 's changes were merged by chance? Thanks for your attention!

**Comment by fmassa** [comment] 2019-04-03 18:15
@tbenst Sam's changes have been merged, via the TensorIterator reductions. But argmax hasn't been touched since then

**Comment by prasunanand** [comment] 2019-07-31 11:10
Got a blocker here. `filters = torch.rand(8,300,300,2).cuda()` in reproducer code doesn't work with CUDA10.1 

Already reported in issue:
https://github.com/pytorch/pytorch/issues/15296

**Comment by prasunanand** [comment] 2019-07-31 11:13
Switching to CUDA 9.

**Comment by prasunanand** [comment] 2019-07-31 15:25
This issue has been fixed already. 

Running @SsnL 's script I get the following.
```sh
(base) prasun@prasun-xps:~/dev$ python argmax_bench2.py 
27.332282066345215
2.1524667739868164
2.2240757942199707
```

**Comment by SsnL** [comment] 2019-07-31 15:56
@prasunanand The CPU perf seems to be addressed. But CUDA perf is still pretty bad :(

**Comment by prasunanand** [comment] 2019-08-01 08:04
OK, I am looking into it

**Comment by prasunanand** [comment] 2019-08-05 07:03
I think it's a deadlock issue. 
`THCudaTensor_max(globalContext().getTHCState(), max_, max_indices_, self_, dim, keepdim)`;
If I comment out this line, the code gets fast.

This line of code is in `build/aten/src/ATen/LegacyTHfunctionsCUDA.cpp` and its a legacy function.

Might be related to https://github.com/pytorch/pytorch/issues/9784

cc: @ezyang

**Comment by SsnL** [comment] 2019-08-05 13:18
@prasunanand if you comment out that line the function does literally nothing because that line calls the implementation kernels.

**Comment by prasunanand** [comment] 2019-08-05 13:20
Yeah, but is it possible that `globalContext().getTHCState()`  might be causing a slow down.

**Comment by prasunanand** [comment] 2019-08-05 13:23
`idx = conv.reshape(-1).max()` runs really fast compared to `idx = conv.argmax()`.

**Comment by SsnL** [comment] 2019-08-05 13:24
You can try to benchmark that by breaking it into two lines and using some cpp benchmarking. But I highly doubt that it is the issue because it exists in so many cuda function calls.

**Comment by SsnL** [comment] 2019-08-05 13:25
That is because they call different kernels (tensor.max vs tensor.argmax). The method .max doesn’t compute the index.

**Comment by prasunanand** [comment] 2019-08-05 13:28
If you look at `https://github.com/pytorch/pytorch/blob/f87a4cc23fae6b1561d35103149c4ce5ccdabe76/aten/src/ATen/native/TensorCompare.cpp#L230` , this is what's going on internally.

**Comment by fmassa** [comment] 2019-08-05 13:35
@prasunanand `torch.max` has two overloads:
- when you pass a dimension, it computes and returns the indices of the argmax as well
- when you don't pass a dimension, it just performs `max` globally over the tensor, without storing a dimension.

Compare the following:
```python
a = torch.rand(10000, device='cuda')

%timeit a.max()
34.3 µs ± 514 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)

%timeit a.max(0)
122 µs ± 0.751 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
```

**Comment by prasunanand** [comment] 2019-08-14 06:17
argmax calls `self.reshape({-1}).max()`[0]

The max step is very slow. Here the kernel that is called is `THC_transformReduceInnermostDimIndex`[1]
`THCTensor_(max)`[2] calls `THC_reduceDimIndex`[3] which calls `THC_transformReduceInnermostDimIndex`
The issue with `THC_reduceDimIndex` `THC_transformReduceInnermostDimIndex`
is that the loop that runs is pretty slow. The threads are scheduled in a manner that
memory access is not coalesced. The jump along grid access makes the loop really slow.

And in the code in `THC_reduceDimIndex` we see that num_rows is explicitly set to 1
before calling the kernel function and when the kernel is called, the loop checks
for stop condition as `block_row < num_rows`.

I am not sure how to go ahead with this.

[0]. https://github.com/pytorch/pytorch/blob/dc870a3761ecf15d3ad6ba7a1628b37b8a0be116/aten/src/ATen/native/TensorCompare.cpp#L233
[1]. https://github.com/pytorch/pytorch/blob/5bf299b1408356a4339580524aaab5ad435fccb8/aten/src/THC/THCTensorMathReduce.cuh#L494
[2]. https://github.com/pytorch/pytorch/blob/dc870a3761ecf15d3ad6ba7a1628b37b8a0be116/aten/src/THC/generic/THCTensorMathReduce.cu#L20
[3]. https://github.com/pytorch/pytorch/blob/5bf299b1408356a4339580524aaab5ad435fccb8/aten/src/THC/THCTensorMathReduce.cuh#L526

**Comment by ezyang** [comment] 2019-08-16 15:58
cc @ngimel @colesbury if you have any thoughts on ways forward

**Comment by ngimel** [comment] 2019-08-16 23:15
All the reductions should be moved to TensorIterator, see also https://github.com/pytorch/pytorch/pull/21295#issuecomment-499241569, that should fix performance issues. Not caring is also an option, but i don't know how big of a bottleneck this is.

**Comment by fmassa** [comment] 2019-08-17 08:00
Moving to TensorIterator is definitely a better strategy, but it will require reworking how Tensoriterator works to support the argmax (and sort, topk, etc) cases, which are not just reductions but requires to keep track of indices and values

**Comment by ngimel** [comment] 2019-08-17 08:46
Hopefully changes can be localized around here https://github.com/pytorch/pytorch/blob/a0b13b4fa55f4a42fc934e1dde52989a40b2c87b/aten/src/ATen/native/cuda/Reduce.cuh#L366-L404 where the data is loaded. `values` array is hardcoded to be `scalar_t` type, but for argmin/argmax reduction it would have to hold both index and value. All higher level reductions apply `combine` operation to arguments of `arg_t` type and that should be able to handle argmin/argmax reduction if `arg_t` is (index, value) pair.

**Closed** 2019-09-27 23:59 UTC
Labels: high priority, module: cuda, topic: performance, triaged
